### ISSUE TITLE
state_format attribute missing from MQTT switch/sensor description but exists in Processing JSON example

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant.github.io#10024]
In the first example [here](https://www.home-assistant.io/docs/mqtt/processing_json/) a `state_format` attribute is used, but there is nothing about it in MQTT [switch](https://www.home-assistant.io/components/switch.mqtt/) and [sensor](https://www.home-assistant.io/components/sensor.mqtt/) documentation.

**Comment by flashtel** [comment]
I can't get state_format to work and this article suggests it doesn't exist for the switch platform.

I think it should be removed from the JSON example.

https://community.home-assistant.io/t/setup-mqtt-switch-with-json-status-reply-need-help/9402/7

"state_format and state_template doesn’t exist in mqtt switch"

**Comment by JinxTL** [comment]
is there a way to do it without removing the state_template?

**Comment by zaarab001** [comment]
Am thinking we can do without state_template

**Comment by akasma74** [comment]
Adios field marshall
