### ISSUE TITLE
Install on Freenas 11.2

### ISSUE THREAD

**Issue by trommegutten** [home-assistant/home-assistant.github.io#10026]
I'm referring to install instructions at https://www.home-assistant.io/docs/installation/freenas/

When I follow the install guide, at the point
`virtualenv -p python3.7 .`
I'm getting:
`virtualenv: Command not found.`
Anyone having the same issue?

Second, I don't understand why some of the markdown has an # before the code and some other code don't? Is this just forgotten in the markdown, or does it mean something. If so, there should maybe be an explanation in the markdown?
```
[...cut...]
Create the configuration directory:
# mkdir -p /usr/local/homeassistant
# chown -R homeassistant:homeassistant /usr/local/homeassistant

Create the installation directory:
mkdir -p /usr/local/share/homeassistant
chown -R homeassistant:homeassistant /usr/local/share/homeassistant

Install Home Assistant itself:
# su homeassistant
[...cut...]
```

**Comment by pattyland** [comment]
You could try installing virtualenv through pip. The GitHub issue tracker should be uses for problems with the homepage, for help installing HA you should ask here: https://www.home-assistant.io/help/

The differences in formatting are presumably because many different people worked on the documentation. Would you like to submit a push request and unify the formatting? Most guides seem to always use $

**Comment by trommegutten** [comment]
I found out that these two lines with code will do the trick:
```
wget -O /tmp/homeassistant.json https://raw.githubusercontent.com/tprelog/iocage-homeassistant/master/homeassistant.json
sudo iocage fetch -P dhcp=on vnet=on bpf=yes -n /tmp/homeassistant.json --branch 'master'
```
If you need z-wave usb stick, then just click edit on the jail (in the ui), and then under "jail properties" change the devfs_ruleset to "4". That's it.. Very easy.

I am not able to understand args against, but shouldn't this overwrite the whole manual way (and the manual method is not working..) Should someone do a push request for this?

**Comment by trommegutten** [comment]
I found out that these two lines with code will do the trick:
```
wget -O /tmp/homeassistant.json https://raw.githubusercontent.com/tprelog/iocage-homeassistant/master/homeassistant.json
sudo iocage fetch -P dhcp=on vnet=on bpf=yes -n /tmp/homeassistant.json --branch 'master'
```
If you need z-wave usb stick, then just click edit on the jail (in the ui), and then under "jail properties" change the devfs_ruleset to "3". That's it.. Very easy.

I am not able to understand args against, but shouldn't this overwrite the whole manual way (and the manual method is not working..) Should someone do a push request for this?

**Comment by trommegutten** [comment]
I found out that these two lines with code as root in freenas shell (ui) will do the trick:
```
wget -O /tmp/homeassistant.json https://raw.githubusercontent.com/tprelog/iocage-homeassistant/master/homeassistant.json
sudo iocage fetch -P dhcp=on vnet=on bpf=yes -n /tmp/homeassistant.json --branch 'master'
```
If you need z-wave usb stick, then just click edit on the jail (in the ui), and then under "jail properties" change the devfs_ruleset to "3". That's it.. Very easy.

I am not able to understand args against, but shouldn't this overwrite the whole manual way (and the manual method is not working..) Should someone do a push request for this?

**Comment by trommegutten** [comment]
I found out that these two lines with code as root in freenas shell (ui) will do the trick:
```
wget -O /tmp/homeassistant.json https://raw.githubusercontent.com/tprelog/iocage-homeassistant/master/homeassistant.json
sudo iocage fetch -P dhcp=on vnet=on bpf=yes -n /tmp/homeassistant.json --branch 'master'
```
If you need z-wave usb stick, then just click edit on the jail (in the ui), and then under "jail properties" change the devfs_ruleset to "3". 

That's it.. Very easy!

I am not able to understand args against, but shouldn't this overwrite the whole manual way (and the manual method is not working..) Should someone do a push request for this?
