### ISSUE TITLE
Proposal on example configurations

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant.github.io#1003]
Right now our example configurations for each component/platform include all the options that are possible. This is bad as it tells users to use certain options that are not necessary.

Take for example the [Hue light platform](https://home-assistant.io/components/light.hue/). 95% of the users should not care about `filename` or `allow_unreachable`. Hence, we should offer the option but not add it to the example (because they copy paste that).

**Comment by balloob** [comment]
@fabaff @Landrash thoughts on this?

**Comment by Landrash** [comment]
Sounds like a plan and a great #hacktoberfest example. 
I can look closer at this under the weekend.

**Comment by fabaff** [comment]
Yeah, is not always the best way to show all possibilities...From my point of view it's usually faster to remove an option than to add one to a copied configuration sample. Let's go with minimal configuration samples aka only the parts which are actually required to improve the user experience.

**Comment by fabaff** [comment]
Tracking
-----------

- [ ] Alarm 
- [ ] Automation 
- [ ] Binary Sensor 
- [ ] Calendar
- [ ] Camera 
- [ ] Climate 
- [ ] Cover 
- [ ] DIY 
- [ ] Deprecated 
- [ ] Downloading 
- [ ] Energy 
- [ ] Fan 
- [ ] Finance 
- [ ] Front end 
- [ ] Health 
- [ ] History 
- [ ] Hub 
- [ ] Light 
- [ ] Lock 
- [ ] Media Player 
- [ ] Notifications 
- [ ] Organization 
- [ ] Presence Detection 
- [ ] Sensor 
- [ ] Social 
- [ ] Switch 
- [ ] System Monitor 
- [ ] Transport 
- [ ] Voice 
- [ ] Weather 
- [ ] Other

**Comment by Landrash** [comment]
Good list @fabaff. Are you planning on working on this one or so?

**Comment by fabaff** [comment]
Well, there are 438 files where approx. 200 to 250 needs an update...guess that we would be faster if it's a team effort.

**Comment by Landrash** [comment]
@fabaff Most definitely. If you , I or anyone else works on a section tag it in your list. Tagged the Health one as an example.

**Comment by robbiet480** [comment]
I wonder if we could dynamically generate the configuration section somehow? A thought for the future I guess.

**Comment by balloob** [comment]
Based on voluptuous PLATFORM_SCHEMA we should be able to get a long way…

**Comment by robbiet480** [comment]
@balloob Just would need the example values I guess.

**Comment by fabaff** [comment]
All done.

**Comment by balloob** [comment]
Wow

**Comment by Landrash** [comment]
@fabaff Really impressive!

**Comment by fabaff** [comment]
Missed Z-Wave (#1095).
