### ISSUE TITLE
Tellstick protocol comen?

### ISSUE THREAD

**Issue by pamm01** [home-assistant/home-assistant.github.io#10060]
Protocol comen works in tellduscenter, but not in tellstick for home assistant.

**Comment by frenck** [comment]
Thank you for reaching out. This is the issue tracker for our website, not for our code base.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

If you suspect a bug, please create one on the appropriate repository.

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
