### ISSUE TITLE
Integrations Search improvement/idea

### ISSUE THREAD

**Issue by mbo18** [home-assistant/home-assistant.github.io#10074]
It would be nice if we can search or sort integrations by the following (already existing) attributes: IoT Class and Quality Scale.

Users will be able to search for local polling integrations in order to find/buy devices with local mode. Or to find/buy devices with Gold or Platinum integrations.

**Comment by frenck** [comment]
Related to some rough sketches of this: #8895

Currently, I'm working on syncing data with the codebase & docs to make the data actually correct and available to allow for these kind of things.

**Comment by mbo18** [comment]
Nice sketch! Will love it.
