### ISSUE TITLE
Developer credit auto update

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/home-assistant.github.io#10087]
Do the developer credits at https://www.home-assistant.io/developers/credits/ still auto-generate?

I have had two pull requests merged, one on the homeassistant/home-assistant repo and one on NabuCasa/hass-nabucasa but notice that I am not showing.

Could this be due to me having email privacy enabled on GitHub?

**Comment by fabaff** [comment]
The credits page is auto-generated but executed manually on a irregular base. I haven't done it in a while...
