### ISSUE TITLE
Nest Documentation has a typo

### ISSUE THREAD

**Issue by jbrody17-zz** [home-assistant/home-assistant.github.io#10088]
In the documentation for the Nest component, the sensors listed for the Nest Thermostat are:

> humidity
> preset_mode
> temperature
> target
> hvac_mode

hvac_mode should actually be hvac_state

**Comment by frenck** [comment]
Hi there @jbrody17!

Every page has an edit button, feel free to use it and contribute to the docs this way! 👍

**Comment by jbrody17-zz** [comment]
Sounds great. Happy to join the gang and start contributing!

**Comment by jbrody17-zz** [comment]
Created pull request #10133

**Comment by klaasnicolaas** [comment]
PR merged so we can close this one 😄
