### ISSUE TITLE
Can't connect Home Assistant Bridge with HomeKit

### ISSUE THREAD

**Issue by barns102** [home-assistant/home-assistant.github.io#10093]
Hi 

I was having problems with my Home Assistant Bridge in the HomeKit app, all the devices stopped responding.  So I removed the bridge from the App and deleted the HomeKit.state file from my HA config.  Now I can't add it back again.  HA discovers it and provides me with the pairing code.  In the Home app I can see the bridge, but when I go to add it its says it can not connect accessory.  I am able to add with my partners phone, and it will add the bridge, and all the devices in HA, they work for about 5 mins, and then disappear.  But they never show on my phone (in the app).  

Could you please help?
Thanks

**Comment by klaasnicolaas** [comment]
The issues here are to report problems with the documentation, we do not offer support through this route. I will therefore close this issue.

For help with your config I would like to refer you to the [community forum](https://community.home-assistant.io) and the [Discord server](https://discord.gg/c5DvZ4e).
