### ISSUE TITLE
fan.xiaomi_miio Humidifier US version

### ISSUE THREAD

**Issue by lseufer** [home-assistant/home-assistant.github.io#10121]
zhimi.humidifier.cb1 is which is the US version of zhimi.humidifier.ca1 is not recognized. Could someone add it?

**Comment by frenck** [comment]
Hi there @lseufer,

This is the GitHub repository for our website & documentation. We use the GitHub Issue tracker to track issues.

For feature requests, please join our community forums. Thanks! 👍
