### ISSUE TITLE
Hass.io acces USB poort

### ISSUE THREAD

**Issue by RamonKranendonk** [home-assistant/home-assistant.github.io#10136]
Can sombody help/explain how to acces the USB poort in de docker container. to allow the acces of a smart meter.

https://www.home-assistant.io/components/dsmr/

best regards Ramon

**Comment by klaasnicolaas** [comment]
Hi there @RamonKranendonk ,

This is the GitHub repository for our website & documentation. 
We use the GitHub Issue tracker to track issues.

For help with your config, please join our community forum or Discord server. Thanks! 👍
