### ISSUE TITLE
tuya components: access denied - username or password wrong

### ISSUE THREAD

**Issue by MaurizioB84** [home-assistant/home-assistant.github.io#10162]
Hello,

I try to setup the integration with HA but I receive always username or pwd are wrong, I checked it via efamilyCloud app and that are correct, my configuration is the following:

tuya:
  username: !secret tuya_username
  password: !secret tuya_pwd
  country_code: 39
  platform: **smart_life**

username like 3401122333
my pwd without " or '

where i'm wrong?

thanks for anyone can help me

**Comment by klaasnicolaas** [comment]
Hi there @MaurizioB84  ,

This is the GitHub repository for our website & documentation. 
We use the GitHub Issue tracker to track documentation issues.

For help with your config, please join our community forum or Discord server. Thanks! 👍
