### ISSUE TITLE
after upgrading to 0.97.2 - Google location sharing

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#10179]
After upgrading to 0.97.2 from 0.96.4 the tracking using google location sharing stopped working.
The error was caused by the removal of the password property that was previously needed in the configuration.yaml.
The instructions prompt the user to install mapscookiegettercli, which if location sharing was already working in Home Assistant in the prior version is not necessary.
Simply delete the password entry, the cookie file already exists.
The documentation should reflect this possibility also since it is an easy fix with only a hassio server restart

**Comment by klaasnicolaas** [comment]
Feel free to open up a PR with a suggested change 👍

**Comment by claughinghouse** [comment]
@ciejepro is this still documented incorrectly? I cant find any reference to password here: [Google Maps](https://www.home-assistant.io/integrations/google_maps/)
