### ISSUE TITLE
Third-party addons doesn't make it clear the difference between homeassistant and hass.io

### ISSUE THREAD

**Issue by surak** [home-assistant/home-assistant.github.io#10184]
It's very unclear from the website that installing homeassistant without using a whole raspberry pi for it won't let you do things you otherwise could.

Here, for example, a note would be welcome saying that this won't work on the standard homeassistant: https://www.home-assistant.io/hassio/installing_third_party_addons/

**Comment by klaasnicolaas** [comment]
Sorry, but I don't quite understand the problem. Could you perhaps explain how you would improve it?

**Comment by surak** [comment]
The problem is that the page says "Home Assistant" at the top, and it does not specify that this is specifically the hass.io disk image. I would improve it by adding a note that this only works for the hass.io image, and *NOT* for other methods of installing home assistant (such as a python venv or a proper raspbian package). 

It's unclear and there are long threads around about the confusion of why home assistant is not able to run home assistant add-ons (because they are hass.io add-ons)

This is an example of a thread where there's this confusion.
https://community.home-assistant.io/t/what-would-it-require-to-get-the-hassio-add-on-store-in-a-normal-ha-installation/69628/9

**Comment by DubhAd** [comment]
The Add-ons page (https://www.home-assistant.io/addons/) makes that clear.

Sadly the confusion with Hass.io and add-ons isn't going to be solved easily.

**Comment by surak** [comment]
> The Add-ons page (https://www.home-assistant.io/addons/) makes that clear.
> 
> Sadly the confusion with Hass.io and add-ons isn't going to be solved easily.

That exact note which says 

```
Add-ons are only available if you've used the Hass.io installer. If you installed Home Assistant using any other method then you cannot use add-ons (but you can achieve the same result manually).
```

is what is missing on the third-party page, which is linked from many other places. That's it.

**Comment by surak** [comment]
Same story for this page: Would I have gone through the whole install like this, if I knew that half the functionality wouldn't be there? That simple note would have solved that:

[Installing home assistant with virtualenv](https://www.home-assistant.io/docs/installation/virtualenv/)

**Comment by DubhAd** [comment]
There's nothing stopping you submitting document updates, however I would be surprised if there was any interest in documenting the lack of add-on support in all non-Hass.io installs. The add-on page itself explains that it's specific to Hass.io, and the only other one that _might_ make sense would be the one you first highlighted.

**Comment by surak** [comment]
> There's nothing stopping you submitting document updates

how?

**Comment by DubhAd** [comment]
Find the page, and in the top right select _Edit this page in Github_ (or something like that)
