### ISSUE TITLE
Error in Version 2.2/ Hassio, Docker

### ISSUE THREAD

**Issue by wisesokol** [home-assistant/home-assistant.github.io#10214]
I have in Log:
[INFO] Running nginx...
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx.conf:45
In Home assistent forums there is such a problem
https://community.home-assistant.io/t/i-get-this-message-after-updating-nginx/132845

**Comment by frenck** [comment]
Hi there!

This is the issue tracker for our website and documentation.

I guess your issue is related to one of the Hass.io add-ons, please create an issue on the hassio-addons repository in that case:

https://github.com/home-assistant/hassio-addons

Thanks!

👍
