### ISSUE TITLE
Error: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by chadlyy** [home-assistant/home-assistant.github.io#10258]
I integrated in Elk M1 : https://www.home-assistant.io/components/elkm1/ 
I can trigger the arm/disarm with no issues from developer tools calling the services directly but when trying to use the alarm panel card I get an error (https://www.home-assistant.io/lovelace/alarm-panel/)

ERROR:  
Failed to call service alarm_control_panel/alarm_arm_home.invalid literal for int() with base 10:

I'm really new, so it may be a user error, but looking for any help I can get. :)

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
