### ISSUE TITLE
Ecobee defaults to Heat when turning on

### ISSUE THREAD

**Issue by MarshallCS** [home-assistant/home-assistant.github.io#10263]
If I turn the ecobee off with home assistant, and then turn it back on, it defaults to Heat instead of the last state that it was in.

Example. I'm currently in cool mode. I turn the ecobee off, and then turn it back on. It comes back on in Heat mode instead of cool mode.

**Comment by brubakerjeff** [comment]
Hi,
I'm still learning the ecobee integration myself. Are you using the dashboard such as below to control the ecobee?
![image](https://user-images.githubusercontent.com/6541166/64083568-97f24d80-ccef-11e9-95a4-dbaadd00881c.png)

Thanks,
Jeff

**Comment by klaasnicolaas** [comment]
Feel you free to make an PR and make the right adjustment 😉

**Comment by brubakerjeff** [comment]
@klaasnicolaas  are you sure it needs a PR?

**Comment by MarshallCS** [comment]
> Hi,
> I'm still learning the ecobee integration myself. Are you using the dashboard such as below to control the ecobee?
> ![image](https://user-images.githubusercontent.com/6541166/64083568-97f24d80-ccef-11e9-95a4-dbaadd00881c.png)
> 
> Thanks,
> Jeff

HI Jeff -  No, I'm not using the dashboard.  I"m using it in automations. In the dashboard - it allows you to turn off using the power icon, but to turn on you must select one of the other icons. When writing automations (or using things like node red) there is a climate.turn_on and a climate.turn_off.

When using the climate.turn_on instead of coming back on in the state that it was in previously, it comes back on and defaults to heat mode.



> 
> 
> Feel you free to make an PR and make the right adjustment 😉

Hi Klassnicolaas - I'm not exactly sure what a PR is - If it's something I need to add to report the issue, I'm happy to do so.

Thanks

**Comment by klaasnicolaas** [comment]
@MarshallCS PR is a Pull Request. In other words, if the current documentation is incorrect, you can change this by means of a pull request, we will check it and eventually merge it.

**Comment by brubakerjeff** [comment]
@MarshallCS a shot in the dark, does climate.ecobee_resume_program get the desired result?

Per your statement the thermostat program is losing its state when being turn_on'd and turn_off'd(?)
Could you post the whole automation if you don't mind?

**Comment by MarshallCS** [comment]
> @MarshallCS PR is a Pull Request. In other words, if the current documentation is incorrect, you can change this by means of a pull request, we will check it and eventually merge it.

Thanks for the explanation. I was actually looking more for a fix to this issue than documenting what it currently does.



> @MarshallCS a shot in the dark, does climate.ecobee_resume_program get the desired result?
> 
> Per your statement the thermostat program is losing its state when being turn_on'd and turn_off'd(?)
> Could you post the whole automation if you don't mind?

I'm doing my automation is node-red, but the same thing can be observed if you manually do it from the services tab in the developers options. 

Climate.ecobee_resume_program does not bring the ecobee out of an "Off". It's mostly used for bringing it out of an "Away" comfort setting.

I hope that helps

**Comment by brubakerjeff** [comment]
node-red? Can you paste the your automation.yaml and configuration.yaml file?

**Comment by klaasnicolaas** [comment]
Please guys stick with the issue that was created.

This is the issue tracker for our website and documentation. For help with your own config we would like to refer you to the other channels such as the Discord server or the community forum.

**Comment by MarshallCS** [comment]
I just want to reiterate that this is an issue with the integration, not with an automation or node red or anything else.

This can be reproduced by calling the climate.turn_off and climate.turn_on in the services tab.

**Comment by brubakerjeff** [comment]
I'm reproducing it here thank you. I'm thinking this is on-topic now? I'd like to help, could I ask for some help with breadcrumbs. 
In the following example, where could I expect to see turn_on implemented when using an ecobee?

https://github.com/home-assistant/home-assistant/blob/8ae5ece6bb88da72fdc4f4e2c5537a66b53344d9/homeassistant/components/climate/__init__.py#L449

    async def async_turn_on(self) -> None:
        """Turn the entity on."""
        if hasattr(self, "turn_on"):
            # pylint: disable=no-member
            await self.hass.async_add_executor_job(self.turn_on)
            return

        # Fake turn on
        for mode in (HVAC_MODE_HEAT_COOL, HVAC_MODE_HEAT, HVAC_MODE_COOL):
            if mode not in self.hvac_modes:
                continue
            await self.async_set_hvac_mode(mode)
            break

**Comment by MarshallCS** [comment]
I apologize for not understanding the terminology. Are you asking for the example of what I'm using the on off functions for?

**Comment by marthoc** [comment]
Just scanning this issue - if this is not a documentation issue then please open an issue on the main Home Assistant GitHub page and I will look into it: https://github.com/home-assistant/home-assistant.

**Comment by klaasnicolaas** [comment]
We can also transfer the issue to there 😉

**Comment by marthoc** [comment]
@klaasnicolaas OK go ahead! I'll keep dealing with it there.

**Comment by marthoc** [comment]
@MarshallCS @brubakerjeff 
The functionality here is easy to implement but there will be some guesswork in one scenario: if the thermostat is "off" when Home Assistant starts. In that case there won't be a last known mode to return to. I think the sensible default in that case is "auto" but am open to suggestions.

**Comment by MarshallCS** [comment]
I apologize that this was in the wrong place, but I'm grateful that it's moving to the correct one and is being actively worked on. 

I do believe that in the event of an unknown last state (such as home assistant being off, auto would be the smartest move. 

Thanks everyone
