### ISSUE TITLE
Z-Wave Query Stage

### ISSUE THREAD

**Issue by brubakerjeff** [home-assistant/home-assistant.github.io#10270]
Hi,
I'm reading this documentation for Z-Wave Query Stage.

https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/z-wave/query-stage.markdown

A statement which is causing me concern is below.

> Because of this, you can expect that after startup your battery powered devices will spend time in Initializing (CacheLoad) - **how long depends on the device**.

Is there any way to bound the statement how long to maybe an order of magnitude? My devices (first alert Zcombo-G, 1 in Initializing (Probe), 3 in Initializing (Static) and 1 in Initializing (CacheLoad) ) have been setting up for 24 hours and am unsure what I should be expecting.

Thanks,
Jeff

@frenck @DubhAd

**Comment by frenck** [comment]
Depends on your device and the configuration of that device. There is no way for us to tell what it will be or what to expect.

**Comment by brubakerjeff** [comment]
Is it reasonable to expect the devices won’t be in initializing (cachload) after 24 hours?

**Comment by frenck** [comment]
That depends on the device and the settings.
If you are in need of support, I would highly suggest joining our community forum or Discord chat.
