### ISSUE TITLE
Tizen app for samsung TV

### ISSUE THREAD

**Issue by mclaudiopt** [home-assistant/home-assistant.github.io#10318]
hello to all
any chance to have a app for interface on tizen TV's ?
it would be great to have an app on our samsung tv's...

**Comment by klaasnicolaas** [comment]
Hi there @mclaudiopt ,

This is the GitHub repository for our website & documentation.
We use the GitHub Issue tracker to track issues.

For help with your config or feature requests, please join our community forum or Discord server. Thanks! 👍
