### ISSUE TITLE
Xiaomi Gateway dgnwg05lm 

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [home-assistant/home-assistant.github.io#10337]
I can't get the key of this gateway, is there any way to add it to Home assistant?

**Comment by klaasnicolaas** [comment]
Hi there @JavierSegoviaCordoba ,

This is the GitHub repository for our website & documentation.
We use the GitHub Issue tracker to track issues.

For help with your config, please join our community forum or Discord server. Thanks! 👍
