### ISSUE TITLE
Binary Sensor and binary_sensor in Integrations

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant.github.io#10355]
In the integrations overview there is a category 'Binary Sensor' with currently 108 platforms. But there is a category 'binary_sensor' with only one platform. They both direct to the same subsets of platforms.

Binary Sensor | binary_sensor
---|---
![Screenshot_20190913-073331](https://user-images.githubusercontent.com/15657682/64839842-3f795500-d5f9-11e9-9d50-910b5db92bae.png) | ![Screenshot_20190913-073323](https://user-images.githubusercontent.com/15657682/64839846-42744580-d5f9-11e9-9d26-bef9b1fba0cf.png)

**Comment by Santobert** [comment]
I would fix this by myself, but I have no idea where to start...

**Comment by klaasnicolaas** [comment]
We already know about it, but have not yet found the pin in the haystack 🤣

**Comment by Santobert** [comment]
What are we looking for? How does the wrongly tagged platform differ from the others?

**Comment by klaasnicolaas** [comment]
It is all about using `- Binary Sensor` (good) or `- binary_sensor` (bad). But I may have already found the problem and a PR to solve it.

**Comment by Santobert** [comment]
Oh no. I have converted the updater to a binary sensor. I didn't know that the documentation doesn't use the backends definition of domains :see_no_evil:
