### ISSUE TITLE
use of - in yaml

### ISSUE THREAD

**Issue by poudenes** [home-assistant/home-assistant.github.io#10383]
Hi All,

Maybe a b.llsh.t request but for newcomers a handy thing to know.
I find it out myself and want to help others to get the feeling as well and become real HA users!

When you write yaml scripts and have conditions, actions, etc... sometimes you use:

`- service:`
or 
`service:`

same for 

`- condition:`
or
`condition:`

I cant find in document the reason of the -

When you have 1 service action or condition then you don't use the -
if you have more then you use - to let yaml know there are more services to handle, etc

Maybe a idea to explain the - in documentation as a separate part in the manual?

**Comment by fabaff** [comment]
How about [this](https://www.home-assistant.io/docs/configuration/yaml/)?

**Comment by poudenes** [comment]
Yes!! Very clear 😁
