### ISSUE TITLE
waze embed for iframe doesnt work with home assistant iframe

### ISSUE THREAD

**Issue by magiva** [home-assistant/home-assistant.github.io#10435]
https://developers.google.com/waze/iframe/ 
specifically states it can be used in an iFrame but it doesnt work with home assistant iframe

i found some notes in the forum, from a pc, it did not work in IE or Edge, only Chrome and Firefox
https://www.waze.com/forum/viewtopic.php?f=12&t=288615

**Comment by fabaff** [comment]
Waze works fine in a [`iframe`](https://www.home-assistant.io/lovelace/iframe/) with Firefox, Chrome and Midori.

If it doesn't work with Edge then it should be fixed by Waze. Nothing we can do.
