### ISSUE TITLE
Clicksend change sender

### ISSUE THREAD

**Issue by cometsfernbroccoli** [home-assistant/home-assistant.github.io#10446]
Hi All,

I use ClickSend for the first time, but adding a custom name for the SENDER, will not make the SMS to be send to clicksend. 

When I remove the option "sender", it will use "hass" and the message is send.

I have no idea to debug more specific information.

**Comment by fabaff** [comment]
This is the bug/issue tracker for Home Assistant. Please use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
