### ISSUE TITLE
📚 Page/File name for Generic IP Camera

### ISSUE THREAD

**Issue by klaasnicolaas** [home-assistant/home-assistant.github.io#10486]
After reviewing PR #10484 I noticed that some integrations actually have strange meaningless names or are too global, so there is no structure.

In this case the **[Generic IP Camera](https://github.com/home-assistant/home-assistant.io/blob/next/source/_components/generic.markdown)**
It has the name `general.markdown`, I suggest something like `generic_ip_camera.markdown`.

**Checklist:**
- [ ] Make PR's against the `current` branch
- [ ] Rename page
- [ ] Add redirect from old to new page in the [_redirects file](https://github.com/home-assistant/home-assistant.io/blob/current/source/_redirects)
- [ ] Adjust all current links to old URL

**Comment by thatguynikita** [comment]
@klaasnicolaas, @frenck , I'd like to help with this one.

**Comment by frenck** [comment]
Sure @thatguynikita! 🎉

**Comment by thatguynikita** [comment]
PR was merged. Yay! 🎉
I guess we could close this one. Although it seems I'm lacking permissions to do so.
Thanks again for the opportunity to get the first time issue done!

**Comment by frenck** [comment]
Yep! Let's close this! 👍
