### ISSUE TITLE
📚 Page/File name for Manual Alarm Control Panel

### ISSUE THREAD

**Issue by klaasnicolaas** [home-assistant/home-assistant.github.io#10487]
After reviewing PR #10484 I noticed that some integrations actually have strange meaningless names or are too global, so there is no structure.

In this case the **[Manual Alarm Control Panel](https://github.com/home-assistant/home-assistant.io/blob/next/source/_components/manual.markdown)**
It has the name `manual.markdown`, I suggest something like `manual_alarm_control_panel.markdown` or move the content to the `alarm_control_panel.markdown` file.

**Checklist:**
- [ ] Make PR's against the `current` branch
- [ ] Rename page
- [ ] Add redirect from old to new page in the [_redirects file](https://github.com/home-assistant/home-assistant.io/blob/current/source/_redirects)
- [ ] Adjust all current links to old URL

**Comment by Rita-Okonkwo** [comment]
can I work on this? @klaasnicolaas

**Comment by frenck** [comment]
Sure go ahead @Rita-Okonkwo! 👍

**Comment by Rita-Okonkwo** [comment]
Hi, I can't seem to find the _components file on the repo anymore

**Comment by frenck** [comment]
It has been moved to _integrations
