### ISSUE TITLE
📚 Page/File names for Telegram

### ISSUE THREAD

**Issue by klaasnicolaas** [home-assistant/home-assistant.github.io#10489]
After reviewing PR #10484 I noticed that some integrations actually have strange meaningless names or are too global, so there is no structure.

In this case the **Telegram** pages:
- [`broadcast.markdown`](https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/broadcast.markdown) to `telegram_broadcast.markdown`
- [`telegram_bot.markdown`](https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/telegram_bot.markdown) to `telegram_chatbot.markdown`
- [`polling.markdown`](https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/polling.markdown) to `telegram_polling.markdown`
- [`webhooks.markdown`](https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/webhooks.markdown) to `telegram_webhooks.markdown`

**Checklist:**
- [ ] Make PR's against the `current` branch
- [ ] Rename page
- [ ] Add redirect from old to new page in the [_redirects file](https://github.com/home-assistant/home-assistant.io/blob/current/source/_redirects)
- [ ] Adjust all current links to old URL

**Comment by paras151** [comment]
Well, I can perform 1st 2nd and 3rd step, but what about the fourth step. Can you help, in which file links can be adjusted

**Comment by frenck** [comment]
@paras151 Those links can be in any file on our website. All the code need to be searched for occurrences and adjusted.

**Comment by Ayoazeez26** [comment]
@frenck I can see a task has been completed here I want to know what's left if I can help with it
