### ISSUE TITLE
🔗 Fixing broken links on our website

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#10491]
Our website has been aging a bit over the last couple of years, unfortunately, this means a lot of links to external sites, have broken down. E.g., due to the website no longer exists, page has moved and bunch of other reasons. This is unfortunate for the users of our website.

This GitHub issue serves as a placeholder to get all those links fixed (or removed if fixing seems impossible).

**Want to help us out?**

Download [Xenu](http://home.snafu.de/tilman/xenulink.html) (for free) and scan our website for broken links and help us fixing them. 👍 🎖 🎉 🍾 
For those who prefer to skip scanning: [Home Assistant.zip](https://github.com/home-assistant/home-assistant.io/files/3720759/Home.Assistant.zip) (last update 12-10-2019)

(Any other tool is allowed as well of course).

**Notes**
- `credits.markdown` is a generated file. Unfortunately, we cannot fix broken links there at this moment.

**Please reference this issue in your PR**.

**Comment by klaasnicolaas** [comment]
O and btw scanning takes some hours 🤣 What if we do the scanning and publish the Xenu file here?

**Comment by srg74** [comment]
https://www.home-assistant.io/blog/ - error https://github.com/emontomery -> should be https://github.com/emontnemery

**Comment by srg74** [comment]
on page https://www.home-assistant.io/components/qwikswitch/ link https://www.home-assistant.io/components/qwikswitch/components/binary_sensor is broken

**Comment by frenck** [comment]
@srg74 Nice sir! 👍 

On all pages, there is a link in the top right "Edit on GitHub", which allows you to change it and open a PR! That way, you can contribute and help to fix those! 🏅 

Happy Hacktoberfest 🎉

**Comment by srg74** [comment]
Not on a first one :(

**Comment by frenck** [comment]
@srg74 Here you go: <https://github.com/home-assistant/home-assistant.io/blob/current/source/_posts/2019-09-18-release-99.markdown>

**Comment by klaasnicolaas** [comment]
In the main message I have put a zip file with an export of my scan with Xenu, so you can get started right away. To show only the broken links, click on **View** -> **Show broken links only**. Of course it is wise to do your own scan in a few days to keep it up to date 😉

**Comment by claughinghouse** [comment]
> O and btw scanning takes some hours 🤣 What if we do the scanning and publish the Xenu file here?

Maybe we should advise everyone not to spam the site and other sites linked to from HA with Xenu? I ran it and hit a lot of "Temporarily overloaded".

@klaasnicolaas could you post an updated scan every so often while this issue is open?

**Comment by klaasnicolaas** [comment]
@claughinghouse I just performed a new scan, the zip file has been replaced with a new version.

**Comment by UddeshJain** [comment]
Is it still open? Can I work on it?

**Comment by frenck** [comment]
Yes! Go ahead! Scan our website, there are still many left!

**Comment by akasma74** [comment]
> @srg74 Nice sir! 👍
> 
> On all pages, there is a link in the top right "Edit on GitHub", which allows you to change it and open a PR!

For some reason currently all "Edit on GitHub" links give Error 404 because instead of

> https://github.com/home-assistant/home-assistant.io/tree/current/xxx

they lead to

> https://github.com/home-assistant/home-assistant.github.io/tree/current/xxx

Could you look into it as well as I don't think non-devs can fix it.

**Comment by klaasnicolaas** [comment]
I have updated the Xenu file with a new fresh scan 😄

**Comment by akasma74** [comment]
It works!

**Comment by saurabhsharma001** [comment]
Link to http://bluesensenetworks.com/ is broken on following page. There is no "Edit this page" link on this page. How to solve it? These are blog pages. More like these exist.

[iBeacons: How to...](https://www.home-assistant.io/blog/2016/05/26/ibeacons-how-to-track-things-that-cant-track-themselves-part-ii/)

**Comment by saurabhsharma001** [comment]
[Pushetta integration](https://www.home-assistant.io/integrations/pushetta/) may no longer be there as the website http://www.pushetta.com is no longer accessible. 
Instead of fixing the link, would it be better to remove the integration?

**Comment by saurabhsharma001** [comment]
Fixed link for Microsoft TTS page.

Pull request: Update microsoft.markdown #10681

**Comment by claughinghouse** [comment]
> [Pushetta integration](https://www.home-assistant.io/integrations/pushetta/) may no longer be there as the website http://www.pushetta.com is no longer accessible.
> Instead of fixing the link, would it be better to remove the integration?

@saurabhsharma001 I asked about this one in discord yesterday and @balloob mentioned that it could be removed.

**Comment by hmmbob** [comment]
Any chance of getting edit rights in the existing blog items? Those contain loads of broken links too....

**Comment by frenck** [comment]
@hmmbob You can edit them just like any other file in the repository :+1:

**Comment by klaasnicolaas** [comment]
Again I have updated the .xenu file with a scan from today

**Comment by saurabhsharma001** [comment]
> > [Pushetta integration](https://www.home-assistant.io/integrations/pushetta/) may no longer be there as the website http://www.pushetta.com is no longer accessible.
> > Instead of fixing the link, would it be better to remove the integration?
> 
> @saurabhsharma001 I asked about this one in discord yesterday and @balloob mentioned that it could be removed.

I see the website is back up. I think we can leave it as is for now.

**Comment by hmmbob** [comment]
Did a fresh scan with Xenu today, with "max depth" set to 2. No further broken links than above pull request.

I'll start running a scan with "max depth" set to 3 now, see what that returns.

**Comment by hmmbob** [comment]
My latest PR (#10889) should have fixed all remaining items that showed up after the scan with max-depth 3.

Found two integrations (Stride, Hipchat) that should be decommissioned, I'll pick that up separately.

**Comment by klaasnicolaas** [comment]
@hmmbob Hipchat will be removed at the 0.101 release 😉

**Comment by hmmbob** [comment]
And stride? Same deal....

Edit: PR for removal made: https://github.com/home-assistant/home-assistant/pull/27934 & https://github.com/home-assistant/home-assistant.io/pull/10897

**Comment by frenck** [comment]
Hacktoberfest is over! Thanks for all the URL's fixed guys! You are amazing! 👍 🎖
