### ISSUE TITLE
mqtt climate control incomplete

### ISSUE THREAD

**Issue by RezzZ** [home-assistant/home-assistant.github.io#10566]
I like the fact that I can register mqtt climate components in HA (in my case fibaro heat controllers that are connected to a separate zwave2mqtt docker container), but right now the component available is only usable as a **read-only component** in case the supported modes of your device does't conform to the default modes that HA offers:
```
[“auto”, “off”, “cool”, “heat”, “dry”, “fan_only”]
```
There is a cool feature to create a template for mapping actual modes to these modes in HA via the mode_state_template configuration variable which gives HA the possibility to show the correct state of your component but right now, the mqtt climate component is not smart enough to 'reverse' this template for the use of the 'mode_command_topic'. There also isn't a mode_command_template configuration variable present and I believe this is a big miss! Any chance that this can be added/fixed?
 
In the below linked community page there are mentions of the following missing template variables:

1. mode_command_template
    Convert mode with a template for publishing to MQTT
3. fan_mode_command_template
    Convert fan_mode with a template for publishing to MQTT
5. hold_command_template
    Convert hold with a template for publishing to MQTT 

source: https://community.home-assistant.io/t/enhanced-version-of-mqtt-hvac-climate-platform-with-proper-history-chart/75304/31

**Comment by frenck** [comment]
Hi there,

Thank you for opening an issue on GitHub. We use GitHub to track issues and bugs. For feature requests, please use the Community Forums.

Besides that, this is the GitHub repository for our website 😉
