### ISSUE TITLE
[REQUEST] Zigbee documentation needed

### ISSUE THREAD

**Issue by Hedda** [home-assistant/home-assistant.github.io#10587]
Zigbee Home Automation integration is missing or needs to be improved.

I have created pull requests #10585 and #10586 to try to get this started.

I believe that much information can probably be copied from the existing Z-Wave documentation because their design and functionality Home Assistant should be very similar to each other.

My purpose of this request is just to get the existing Zigbee Home Automation integration into the main documentation as I think that could be used as a base for technical writers who can build on that and help improve the Zigbee documentation for Home Assistant. 

With this, I wish to expose the Zigbee Home Assistant integration and show in the same light as the Z-Wave integration. I hope that this will help the existing Zigbee integration become more of a first-class citizen in Home Assistant, just like the existing Z-Wave integration already is.

**Comment by frenck** [comment]
I don't get why you first open a bunch of PR's and next create an issue with `[REQUEST]` in the title?

The only thing that is will achieve at this point, it that discussions are prone to take place in different places. Let's close this and continue the discussion on the PR.
