### ISSUE TITLE
Page Troubleshooting Automations "Check Config" doesn't exist.

### ISSUE THREAD

**Issue by tuxick** [home-assistant/home-assistant.github.io#10591]
The page mentions "go to Configuration -> Server Control and click on Check Config button in Configuration validation section".
There is no such section, just "Server management: restart/stop"

**Comment by frenck** [comment]
This might need a big of updating indeed. 

### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by TomBrien** [comment]
I'm happy to take this on if you want to stick me down as an assignee. I take it we think the correct update is to explain that "Check Config" can be found by enabling "Advance Mode" in your user profile.
