### ISSUE TITLE
Integrations/Fan page should list available services

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant.github.io#10622]
The page [integrations/fan](https://www.home-assistant.io/integrations/fan/) is not very helpful at the moment. It should list available services and automation examples like [integrations/climate](https://www.home-assistant.io/integrations/climate)

**Comment by frenck** [comment]
### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by SoldierCorp** [comment]
Hi, can I take this one?

**Comment by klaasnicolaas** [comment]
Yes ofcourse, I will assign it to you

**Comment by SoldierCorp** [comment]
I do have a question,

I couldn't found any field for the `optional` column for each service so I just added `no` to all of them, is that ok?

**Comment by SoldierCorp** [comment]
One more thing @klaasnicolaas 

For this issue, I create a simple script to convert the content of the `fan.xml` service to a `markdown template`, I created this to avoid copy one service at time and editing the fields one by one.

https://github.com/SoldierCorp/integracion-service-markdown-homemeassistant.io
