### ISSUE TITLE
Some page titles are named in the plural

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant.github.io#10623]
Some page titles are named in the plural (lights instead of light). The majority of pages use the singular (e.g. [sensor](https://www.home-assistant.io/integrations/sensor), [fan](https://www.home-assistant.io/integrations/fan), [climate](https://www.home-assistant.io/integrations/climate) and [automation](https://www.home-assistant.io/integrations/automation/)).

The following pages use the plural:
- [ ] [integrations/light](https://www.home-assistant.io/integrations/light)
- [ ] [integrations/switch](https://www.home-assistant.io/integrations/switch)

**Comment by klaasnicolaas** [comment]
Can we close this issue?

**Comment by Santobert** [comment]
Looks good to me
