### ISSUE TITLE
listen_port 80

### ISSUE THREAD

**Issue by morrydavis** [home-assistant/home-assistant.github.io#10643]
Can't use this home assistant throws an error permission denied probably due to non root user running homeassistant but setcap command to alleviate this also doesn't work do to illegal option when used as stated

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.
Furthermore, this repository (and this issue tracker) is our documentation/website. If you believe it is a bug, please submit a bug at our main repository.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
