### ISSUE TITLE
Twitter Trends

### ISSUE THREAD

**Issue by balianurag** [home-assistant/home-assistant.github.io#10699]
import tweepy
consumer_key=xxxxxxxxxxxxxxx
consumer_secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
access_token_secret=xxxxxxxxxxxxxxxxxxxxxxxxx 
auth=tweepy.OAuthHandler(consumer_key,consumer_secret)
auth.set_access_token(access_token,access_token_secret)
api=tweepy.API(auth,wait_on_rate_limit=False,wait_on_rate_limit_notify=False,compression=False)
trends_result=api.trends_place(1)
trends=[]
for trend in trends_result[0]["trends"]:
    results=trend["name"]
    trends.append(results)
    print("-->",results)

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
