### ISSUE TITLE
0.10X is not appearing at the top of the version selection

### ISSUE THREAD

**Issue by peternijssen** [home-assistant/home-assistant.github.io#10755]
https://www.home-assistant.io/integrations/

If we take a look on this integrations page and you use the filter on version at the left side, you will notice 0.10X is missing. Well, it's not missing, it's part of 0.1X and thus is somewhere down in the drop down while it should be at the top.

I guess the problem is within this method, but I am lacking Ruby knowledge:
https://github.com/home-assistant/home-assistant.io/blob/d1efccfb2503a9f561846469dc63df7ab37e1299/plugins/filters.rb#L75

**Comment by frenck** [comment]
Nice! Thanks for reporting this one in, will take a look 👀

**Comment by frenck** [comment]
Fixed in #10775
