### ISSUE TITLE
Releases overview page

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant.github.io#1081]
To get users a better overview about what's "new" in Home Assistant, we would like to have a "**new**" section in the [components index](https://home-assistant.io/components/) which always point to the latest release. Grouping all platforms/components for a release could reduce the needed search time for users to see what the latest stuff is or which platforms/components were introduced with 0.xx.

It could be done by changing the category for all new platforms/components but that's not an option. Don't worry, we are using `ha_release` to keep track when a platform/component was introduced. 

As a side-effect this could allow us to point from the docs back to the overview (like https://home-assistant.io/components/0.28) as we are showing the release if it's present.  

![rel-link](https://cloud.githubusercontent.com/assets/116184/19028776/316f2b5a-8940-11e6-812f-d83b1b12553f.png)

Notes:

- The page is hosted by GitHub Pages which limits the available dependencies.
- It would be preferred if no new Javascript is introduced.
- More conversations can be found at https://community.home-assistant.io/t/new-section-in-components/4020/8

**Comment by robbiet480** [comment]
Ask and [ye shall (partially) receive](https://home-assistant.io/components/).

Pretty hard to do this for unlimited releases going back, both from a technical and UI standpoint. But I guess we could do it.
