### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant.github.io#1083]
Our documentation website has no search feature. A lot of people are using `site:home-assistant.io` with Google but a local search functionality would be preferred. There is a existing [feature request](https://community.home-assistant.io/t/search-option-on-main-website/3179) which could serve as a reference for already discussed stuff.

One option which came up was [Jekyll search using lunr.js](http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/). We guess that there are other solutions available that works with GitHub Pages.

**Comment by cdax** [comment]
I checked out the [Jekyll Cast](http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/) that outlines how something like this might be implemented, and I'd like to start working on this. I've been hoping to check out lunr.js for a while now and this looks like a great opportunity.

I'd like some inputs on how this should look on the site? I'm thinking something as simple as the search box on [Django's documentation website](https://docs.djangoproject.com/en/1.10/)?

**Comment by fabaff** [comment]
Simple is good :+1: 

At some point we need to discuss the position but I guess this can wait.

**Comment by balloob** [comment]
An alternative could be to have a query to DuckDuckGo / Google with site:home-assistant.io.

Since the index will be of significant size, we should make sure it won't get automatically downloaded on every page if we have a search box on every page 👍

**Comment by thebouv** [comment]
Just a drive-by suggestion (because I was looking through a bunch of `hacktoberfest` issues), but you might want to consider http://readthedocs.io for hosting your docs. Provides search et al, they host docs for tons of projects, and you won't have to reinvent the wheel.

**Comment by balloob** [comment]
@thebouv our dev docs are 👍  https://dev-docs.home-assistant.io/en/dev/

This would be for the website with all the documentation for the different platforms.

Which makes me think, maybe a different (or both) thing that we can do, is add search to the components page. Have it filter the components based on a search input.

**Comment by bdurrer** [comment]
Sorry to resurrect dead issues. I'm not sure why this one was closed.
A search feature over all components would really boost newbs like me getting started.

A static search index would be good enough for most usecases, so this might be an "easy" solution: http://robin.radic.nl/github-pages-search/

**Comment by balloob** [comment]
@bdurrer you're right, it's not done yet. Although you did add component search which helped a lot!

Another thing we might want to add is https://community.algolia.com/docsearch/

It seems easy to add?

**Comment by balloob** [comment]
I signed up for Algolia and will update if I have more info.

**Comment by fabaff** [comment]
Introduced by https://github.com/home-assistant/home-assistant.github.io/commit/6bc3041fe2215c9940cd27062625871bc6d2c364
