### ISSUE TITLE
Apple TV documentation refers to field which does not appear on screen

### ISSUE THREAD

**Issue by unikitty37** [home-assistant/home-assistant.github.io#11195]
The documentation says "Select apple_tv as domain and apple_tv_scan as service then press the button" — but there is no domain selector, even with advanced mode enabled:

![image](https://user-images.githubusercontent.com/139183/68992697-92c08b80-0866-11ea-93d7-9be0b842f7e2.png)

This is with a version of hass.io that was downloaded a week and a half ago — has something changed in a recent version of HA that requires a documentation update?

(The `apt-get` instructions also don't work on hass.io, and the documentation usually says when hass.io already has support built in. I'm not sure which flavour of Linux hass.io is based on, but it's certainly not an apt-based one 🙂 Could these instructions be clarified to state if hass.io already has the necessary support and, if not, how to install on hass.io?)

**Comment by ikifar2012** [comment]
I might try to work on updating these when I get a chance
