### ISSUE TITLE
Information about the cover rfxtx page

### ISSUE THREAD

**Issue by weado** [home-assistant/home-assistant.github.io#11206]
Is it possible to add some information about the RFXTX Cover for RFX/Somfy Shuttle (personal experience) ?

If you put the parameter `signal_repetitions: 2` in the configuration file for manage the Somfy cover, you could have a be a strange behavior when you click on "STOP" button, because When you put on the STOP button the cover stop and it goes down after 1s by itself.
You have to delete this parameter or change the number by 1.

https://community.home-assistant.io/t/strange-behavior-with-the-stop-button-somfy-rfxcom/148724

**Comment by frenck** [comment]
@weado Yes, sure!

On every page on our documentation, you can find an edit link on the top right. Feel free to open up a PR with a suggested change!

That would be highly appreciated (in general).

**Comment by frenck** [comment]
This has been adjusted. Thanks 👍
