### ISSUE TITLE
wled integration does not support white channel in RGBW LEDs

### ISSUE THREAD

**Issue by EspenT** [home-assistant/home-assistant.github.io#11269]
Integration does not let you configure white channel in RGBW leds.  It is expected that it has a slider to adjust  "WHITE_VALUE" like e.g. the esphome integration does.

**Comment by frenck** [comment]
The W channel is calculated from the RGB value for the WLED integration.

However, you are reporting this issue to our website repository. I'm pretty sure that this is not a website issue 😉 

So if you think it is a bug, please file an issue at our main repository: <https://github.com/home-assistant/home-assistant/issues>

Feature requests can be done on our community forum: <https://community.home-assistant.io/c/feature-requests>

Thanks! 👍
