### ISSUE TITLE
Rachio Component: Standby mode not updating

### ISSUE THREAD

**Issue by salsabeard** [home-assistant/home-assistant.github.io#11273]
As of 101.2 (not certain how long prior) standby mode of Rachio controllers is not updating properly in Home Assistant. The other binary sensors and switches seem to work properly. Only the standby mode seems to not update.

**Comment by frenck** [comment]
This is the issue tracker for our documentation. Please file an issue at:

<https://github.com/home-assistant/home-assistant/issues>

Thanks! 👍
