### ISSUE TITLE
Homematic Addon - which OCCU version?

### ISSUE THREAD

**Issue by steckenpferd** [home-assistant/home-assistant.github.io#11335]
Hi,

please add on the github page which OCCU version is used for the Addon - information is missing: 
https://www.home-assistant.io/addons/homematic/

Thank you 

Latest available OCCU: 3.47.22
https://github.com/jens-maus/occu/tree/b_3_47

**Comment by frenck** [comment]
The documentation will be removed from the website in the near future and be part of the add-on itself.

You can find the current version here: <https://github.com/home-assistant/hassio-addons/blob/master/homematic/build.json#L7>

Furthermore, on each add-on update, a changelog is provided.

Nevertheless, thank you for your suggestion.

**Comment by steckenpferd** [comment]
Thank you
