### ISSUE TITLE
Sensor /  Button States often not updating in Hassio

### ISSUE THREAD

**Issue by polyphia** [home-assistant/home-assistant.github.io#11376]
Since a few days ago I started noticing the state of my motion sensors and xiaomi switches not updating in Hassio 0.102.2 .

This is completely erratic and there is no apparent pattern I can identify .

Double checked multiple times in the Mi Home App and the movement is registered there but not in HA, which causes many of my light automations to fail .

Tried deleting database, changed between mysql and mariadb and nothing seems to work , sometimes the sensors / button clicks get the state updated, many other they don't !

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
