### ISSUE TITLE
mill integration unavailable

### ISSUE THREAD

**Issue by magiva** [home-assistant/home-assistant.github.io#11398]
i added mill integration, instructions very nice and simple
it discovers my heaters as i see them listed in devices but theyre unavailble with no status

**Comment by frenck** [comment]
@magiva This is the issue tracker for our documentation & website.

If you are in need of support, please check out our Community Forum or join our Discord chat for help via: <https://www.home-assistant.io/join-chat>

If you suspect an bug, please file an issue at our main code repository:
<https://github.com/home-assistant/home-assistant/issues>
