### ISSUE TITLE
Ecobee Pin

### ISSUE THREAD

**Issue by bluscooter** [home-assistant/home-assistant.github.io#11392]
The Home assistant generated Authorization pin is Alpha Numeric and the Ecobee website only accepts a 4 digit Numeric pin.

**Comment by frenck** [comment]
Hi there,

Thank you for opening up an issue here at GitHub, I'm sorry to hear you are having troubles. However, this GitHub repository is related to our website and documentation.

Please open up an issue at https://github.com/home-assistant/home-assistant, and provide the needed details in the process.

Thanks! 👍
