### ISSUE TITLE
Search for aws returns Nothing found!

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/home-assistant.github.io#11407]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/11855322/70416148-437d0d80-1a56-11ea-938d-7db6bd6b6772.png">

 Should return https://www.home-assistant.io/integrations/aws/

**Comment by frenck** [comment]
Thanks, @robmarkcole! 👍

**Comment by frenck** [comment]
Fixed!
