### ISSUE TITLE
First-time camera setup can take a LONG time

### ISSUE THREAD

**Issue by Moonbase59** [home-assistant/home-assistant.github.io#11400]
I’m on Hassbian, using a Raspi 3B+ and Home Assistant 0.102.3.

Setting up a MJPEG camera for the first time can take a LONG time, since HA seems to compile and install lots of things when running the config checker after adding a camera.

**You might want to add a word of warning** to the troubleshooting page at https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/stream.markdown **so that impatient users don’t abort the process and are probably left with a corrupt system by trying to reboot/reset it.**

The config checker took about 8 minutes in my case until everything was compiled and set up on my Raspi. Being patient and not interrupt anything paid: All works well. :-)

I had to do a
```bash
sudo apt-get install -y python-dev pkg-config libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev libavfilter-dev
```
first, then added my camera in `configuration.yaml` as:
```yaml
camera:
  - platform: mjpeg
    name: Studiodisplay Cam
    mjpeg_url: http://studiodisplay1:8081/
```
It’s a Raspi Cam powered by a Raspi 3B using the simple command
```bash
@reboot sleep 10s && /usr/local/bin/raspimjpeg.py -w 1280 -h 720 -r 25 | /usr/local/bin/streameye -p 8081
```
in crontab.

**Comment by frenck** [comment]
Feel free to open up a PR.
