### ISSUE TITLE
XIAOMI Mi Robot Instructions need update

### ISSUE THREAD

**Issue by pschneider87** [home-assistant/home-assistant.github.io#11412]
I read the intructions for the Mi Robot integration.
I do not succeed in getting the token

- Mi Toolkit only works with specific version, which does not run on Android 10
- Token is not exposed in the log files on Andorid, at least I can't find them

If someone is able to update this docs would be perfect!

**Comment by frenck** [comment]
Do these instructions work for you?

<https://github.com/home-assistant/home-assistant.io/pull/11401>

**Comment by pschneider87** [comment]
yes, indeed. This Information about the App Version is very valuable!
Thx

**Comment by frenck** [comment]
Fixed by the PR linked in my last comment.
