### ISSUE TITLE
ProxmoxVE user needs special privileges within proxmox

### ISSUE THREAD

**Issue by MarcJenningsUK** [home-assistant/home-assistant.github.io#11431]
Creating an unprivileged user in proxmox results in the containers / VMs being undiscoverable.  Suspect the required permissions are CT.Monitor and VM.Monitor but I'm not sure.

Adding an admin user works, or using the default root user, but that is.... problematic, at least from a security standpoint.  Minimum privs per user.  If the devs can clarify permission s required that would be awesome.  

Thanks

**Comment by MarcJenningsUK** [comment]
Clarity - it's not an issue with the component, just some info that would be good to have in the docs. :)

**Comment by frenck** [comment]
Feel free to open up a PR to clarify what a user needs to do.
On every page in our documentation, there is an edit link at the top right.

**Comment by MarcJenningsUK** [comment]
I'd be pleased to edit the page, but I don't have visibility on what the plugin is actually doing with proxmox so I am not sure what the requirements are for the user.  The options I mentioned are purely guesses

**Comment by jhollowe** [comment]
I'll be back home in a week or so and I'll play around with this and see what permissions are needed. I'll make a PR if I figure it out.
@frenck feel free to assign this to me

**Comment by jhollowe** [comment]
@MarcJenningsUK can you tell me what versions of PVE and hass you are running?
I'm trying to use PVE 6.0-9 and hass 0.103.5 and I can't get a successful connection to PVE.

**Comment by jhollowe** [comment]
@MarcJenningsUK What version of PVE are you using? I'm unable to find any CT.* permissions.

**Comment by jhollowe** [comment]
On PVE 6.0-9, all that is needed is a user with VM.AUDIT permission set. I'll work on getting that in a PR with some info on how to create a dedicated user in PVE for use with HA.
The API has been stable on v2 for quite a while, so I'm going to say that if it is working for my version, it should work for any other versions of PVE.

**Comment by jhollowe** [comment]
@MarcJenningsUK let me know if the new instructions don't work for you, but this should be done

**Comment by frenck** [comment]
Yep! Merged and live. Let's close it for now.

**Comment by MarcJenningsUK** [comment]
Just running through the instructions now, but looking great.  Thanks all.
