### ISSUE TITLE
help - no life360 integrtion option

### ISSUE THREAD

**Issue by bensil1** [home-assistant/home-assistant.github.io#11467]
after uninstaling old installation of life360  
i dont have the life360 option in integration

**Comment by frenck** [comment]
Hi there, this is the GitHub issues tracker for our documentation & website.

In case you are having issues with Home Assistant, please file an issue at:
<https://github.com/home-assistant/home-assistant>

In case you are looking for help or support, please try our [Community forum](https://community.home-assistant.io) or join our always active [Discord chat server](https://www.home-assistant.io/join-chat).

Thanks! 👍
