### ISSUE TITLE
Documented initial value vs restore state in input_boolean, input_select, input_datetime and input_text docs

### ISSUE THREAD

**Issue by jleeuwes** [home-assistant/home-assistant.github.io#11462]
The documentation page <https://www.home-assistant.io/integrations/input_number>
is clear about the `initial` value: "Default value: The value at shutdown". This is consistent with the text under "Restore state": "If you set a valid value for `initial` this integration will start with state set to that value. Otherwise, it will restore the state it had prior to Home Assistant stopping."

The other `input_*` integrations have the same "Restore state" text but also mention an explicit default value for `initial`. For instance, <https://www.home-assistant.io/integrations/input_select> says "Default value: First element of options".

I think the `input_number` page is clear but the other pages contradict themselves. If I don't set a value for `initial`, I would expect the state to be restored based on the "Restore state" explanation, but then the default `initial` value would never be used so it shouldn't be mentioned in the doc. Seen from the other angle: if I don't set a value for `initial`, it would get its default value and no state would be restored; I would have to set an explicitly invalid value for `initial` to trigger the behaviour described by "Restore state". If this is the case, I think that could be mentioned more clearly.

Sorry for the maybe somewhat long-winded description. I'm not familiar enough yet with these integrations to know what would be the proper correction to the docs, otherwise I would have just made a pull request.

**Comment by RichardUUU** [comment]
I'm not seeing the problem:

1 Create an input* without a value for initial / reboot / the value will be the default
2 Change to new-value (something other than default) / reboot / the value will be new-value

3 Create an input* with a value for initial / reboot / the value will be the initial

Which line does not reflect the docs?

**Comment by jleeuwes** [comment]
@RichardUUU  I'm assuming you are describing the actual behavior of home assistant in those three scenarios. I think all of your scenarios might be consistent with the docs.

I think what confuses me is the meaning of the mentioned default value. If I understand you correctly, the default value is the value the entity will get on startup if there is no `initial` configuration variable defined and also no value from a previous run known. So the default value is relevant for any input* that has never been manually changed **and** doesn't have a value for `initial`.

One thing that remains a bit strange is that `input_number`, according to the docs, has no explicit default (" Default value: The value at shutdown"). So would an `input_number` without a value for `initial` be in some sort of undefined state until the first manual change?
