### ISSUE TITLE
Red RM Mini 3 does not work

### ISSUE THREAD

**Issue by tota-5** [home-assistant/home-assistant.github.io#11532]
The different (I don't know if it's new or not) RM Mini colored red does not work with broadlink component.

I used broadlink_cli to try to get it into learning mode and got the following:

AttributeError: device instance has no attribute 'enter_learning'

In home assistant, the commands just don't execute in the device, altho the buttons goes from on to off normally.

The firmware on this is 44057

On intelligent home center app from broadlink, the devices work as intended.
It has no firmware upgrades available for it.
On e-control app, it shows as unrecognized device, but shows.

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
