### ISSUE TITLE
Google calendar integration does not work using the documentation provided

### ISSUE THREAD

**Issue by DTekNOdev** [home-assistant/home-assistant.github.io#11543]
Integration with the google calendar using the instructions here https://www.home-assistant.io/integrations/calendar.google/ does not work. The instructions are confusing and it seems that the google console has changed since the instructions were written.

I was not able to access calendars using this integration at all and kept on receiving an error in the notification window. 

It was ultimately possible to create an authentication key and validation screen that worked with the google integration using the Quickstart "enable calendar" link here: https://developers.google.com/calendar/quickstart/python

but it is not clear what the difference was to doing this manually.

**Comment by anderbak** [comment]
I was able to follow the home-assistant instructions and successfully did an authentication through HA; however, I am facing a different issue that I've been trying to resolve.

**Comment by Korte68** [comment]
I also facing issue with google calendar since a few days....I have to re-authenticate two times so far...(delete the .google.token file).

**Comment by PurelyNicole** [comment]
I know the issues that @jeremycook61 is speaking of. There are a few wording changes that could make the integration easier to follow. However, I'm seeing the same issue as @Korte68 and don't know if I should hold off making the changes in case there's a bigger issue going on. ([See core repo issue #27210.](https://github.com/home-assistant/core/issues/27210))

**Comment by frenck** [comment]
Oh hi! 👋 

Was going through some older reported feedback, and noticed this one still being open.

In the 4 years since this issue was created, a lot has changed. For example, this integration is now fully available through the UI and the documentation has significantly changed.

Given the fact the integration usage went up a lot since then, I'm going to safely assume this is no longer an issue.

../Frenck
