### ISSUE TITLE
D-Link Smart Plugs are discontinued and the guide requires updating

### ISSUE THREAD

**Issue by SakshamInABox** [home-assistant/home-assistant.github.io#11540]
URL: https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/dlink.markdown

The products in the guide above are now legacy/discontinued and are not being manufactured anymore (https://www.dlink.co.nz/home-solutions/connected-home/wi-fi-smart-plugs)

The guide above does not appear to be working with new models. DSP-W118, would appreciate an up to date guide/documentation if anyone has experience with getting this working.

**Comment by frenck** [comment]
I think this has been perfectly documented by the guide, by listing "supported models".

You are basically asking for support for newer models, which is fine, by a feature request.

We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
