### ISSUE TITLE
NGINX subdomain information update needed?

### ISSUE THREAD

**Issue by jhollowe** [home-assistant/home-assistant.github.io#11610]
I was looking through the [NGINX subdomain](https://www.home-assistant.io/docs/ecosystem/nginx_subdomain/) page and noticed that it seems a bit unnecessary to have a separate /api/websocket location. It is also not setting the X-forwarded-for header which is used by Home Assistant. There are also some differences between the [NGINX](https://www.home-assistant.io/docs/ecosystem/nginx/) and [NGINX subdomain](https://www.home-assistant.io/docs/ecosystem/nginx_subdomain/) pages.

Would it be of help to go through and rework this page (or both the NGINX pages) to be more concise and up-to-date?

**Comment by frenck** [comment]
Sure! Go ahead! 👍

**Comment by frenck** [comment]
This information is no longer present on our website, but part of the community forum wiki/guides.
