### ISSUE TITLE
Links not working inside {% configuration %} blocks

### ISSUE THREAD

**Issue by tribut** [home-assistant/home-assistant.github.io#11643]
When links are used inside `{% configuration %}` blocks, they are not rendered correctly but instead the source is retained verbatim, see for example [addons/google_assistant](https://www.home-assistant.io/addons/google_assistant) (`[Google Actions Console][GActionsConsole]`) or [integrations/alert](https://www.home-assistant.io/integrations/alert/) (`[template][template]`):

![Screenshot from 2020-01-06 09-27-06](https://user-images.githubusercontent.com/719105/71805522-c057d300-3066-11ea-880e-4b15e5286c5c.png)

**Comment by frenck** [comment]
It is because they are referenced outside that block. The configuration block is rendered separately from the full document.

These specific locations need to be fixed by linking directly instead of using a reference.

**Comment by tribut** [comment]
I see. I should have some time later to do that...

**Comment by frenck** [comment]
Yep!
