### ISSUE TITLE
Integrations Search experience

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant.github.io#11682]
It seems that currently, the search on [Integrations page](https://home-assistant.io/integrations/) of the website only searches titles. The problem with that is many integrations can be called different things. 

* Typing "PS4" doesn't show the PlayStation 4 integration. 
* "Fire TV" doesn't bring up the Android TV integration.
* "Chromecast" doesn't show the Google Cast integration
* "Google Home" doesn't show the Google Assistant integration
* "Echo" doesn't show Alexa integration.
* "SSH" doesn't show shell command. 
* "Nest Wifi" doesn't show Google Wifi. 
* If user adds a space to an integration (ie "Life 360" instead of "Life360", or "Home Kit" instead of "HomeKit" etc) that search will fail. Same for the reverse, "Apple TV" works but "AppleTV" does not..

And so on. Home Assistant _does_ have these integrations, and these are all valid search terms for them, but the user just gets a "Nothing found!" error and comes up empty handed. Some users might think of refining their search keyword, but others will just assume it's unsupported and move on.

Don't know whether this is possible with the current setup (as it appears to be a simple filter of title), but it'd be nice if there was a way to add additional metadata / aliases for search purposes so that it would catch these examples and point the user to the right place.

**Comment by dshokouhi** [comment]
I was thinking about this very issue the other day.  Another good example is that Neato was acquired by Vorwerk and users must know that those robots (vorwerk) support the Neato API and they can use them.  I wonder if we need to allow for custom search terms maybe?

**Comment by frenck** [comment]
Absolutely a good improvement, however, this needs quite a bit of rework on how we work with integrations in general on our website.

Part of setting this in motion has started, as I'm currently working on creating a central resource for our data (our codebase) and importing/syncing that data with the website.

I guess we could extend this for the future to make things like this possible.

**Comment by SeanPM5** [comment]
Still an issue (I know this is a longer-term thing, only posting for stalebot to keep it open)

edit: I guess I was too late on that... oops
