### ISSUE TITLE
Integrations Search bug

### ISSUE THREAD

**Issue by Tosko4** [home-assistant/home-assistant.github.io#11707]
When you go to the integrations page and type one letter (random any letter will do), the entire site disappears and shows one error message.

![258B5DCE-0612-4B96-BC0B-DCEBBAA60DEF](https://user-images.githubusercontent.com/1294707/72200475-2e770e00-344a-11ea-8b03-f5601faacb75.jpeg)

**Comment by klaasnicolaas** [comment]
think your problem was only short-lived, because I don't get any errors 🤔

**Comment by frenck** [comment]
Cannot reproduce it either 🤷‍♂ 

@Tosko4 Does it happen in a specific browser? Have you emptied your browser cache?

**Comment by Tosko4** [comment]
It’s been going on for months on my side. I use Safari, (iOS). I will try safari on my mac soon, to see if its a mobile thing only or maybe a browser thing.

**Comment by frenck** [comment]
which ios version?

**Comment by Tosko4** [comment]
I have just confirmed, works fine on safari (mac osx). I got nothing to do, tried some more letters. Doesn’t bug out with F for instance lol...

So it’s just my iOS device that has issues with that. 

Iphone running: ios 13.3
