### ISSUE TITLE
Homematic CCU3 issue with HmIP-BROLL / unknown parameter for value key: WORKING

### ISSUE THREAD

**Issue by adandl** [home-assistant/home-assistant.github.io#11720]
Hello All!
I have an issue with Homematic Integration with CCU3 and HmIP-BROLL (cover switch).
During startup I receive the following error-message for all 4 switches I have installed:
Any suggestions?

HMGeneric.getValue: WORKING on 00111A49A33A4B:4 Exception: <Fault -5: 'Unknown Parameter for value key: WORKING'>

Thank you!

**Comment by frenck** [comment]
Hi there @adandl!

Thank you for opening an issue with us, however, this issue tracker is for tracking issues with our website and documentation.

For reporting issue with Home Assistant, please open an issue here: <https://github.com/home-assistant/home-assistant/issues>

Thanks! 👍
