### ISSUE TITLE
Alarm Control Panel Template documentation: cleanup 'lock' references and expand on value_template

### ISSUE THREAD

**Issue by MatthewFlamm** [home-assistant/home-assistant.github.io#11731]
I am super excited about the new alarm control panel template functionality and I wanted to prepare for how to use it.  There are a few sections in the alarm control panel template documentation that look like they were copied in some form from the lock template and don't make too much sense to me.

> Another use case could be grouping a series of internal and external locks together to represent "Home" and "Away" lock states.

How would this be different than a "template lock" that shows "locked" and "unlocked" based on a grouping of locks?  Is it just to show "armed home" and "disarmed" instead?  If this is just to get different states for this, you could also use a template sensor and some automations to do the same thing.  Or is this about having the possibility of having a key code for operating the locks?

If you need another use case that is clearer, in my opinion, my use case is a custom alarm system built in ESPhome and use a set of services and sensors from the ESPhome device in the template alarm control panel.  The alarm is entirely controlled and automated from within the ESPhome device, but HA serves as one type of user interaction with the alarm system.

> In optimistic mode, the alarm control panel will immediately change state after every command. Otherwise, the lock will wait for state confirmation from the template. Try to enable it, if experiencing incorrect lock operation.

Here I assume lock just needs to be changed to alarm control panel.

Can the operation of the value_template also be expanded on, especially in relation to the `arm_*` and `disarm` sections?  Can my value_template have any arbitrary value, or does it need to conform to the existing states in the alarm_control_panel? There are more of these than exist in the current example, so are all of them supported, or just this subset?  

How are available 'arming' buttons displayed on the frontend?  Based on the available "arm_*" sections?  I think this is how it works for the manual alarm control panel.

For example, will this work?

```alarm_control_panel:
  - platform: template
    value_template: "{{ something_that_can_evaluate_to_arm_upstairs }}"
    arm_upstairs:
      service: script.turn_on
      entity_id: script.esphome_alarm_arm_upstairs

**Comment by frenck** [comment]
Thanks for suggesting improvements to the page. Feel free to open up a PR to improve wording, that is always appreciated. 👍 

Most of your questions are support questions, which is not what we use GitHub for. We use GitHub to track issues. For support, please join our Community Forum or join our Discord chat. Thanks 👍

**Comment by MatthewFlamm** [comment]
I agree that for the first few I can open a PR for the wording, although I'm not sure if I would be misinterpreting what was put on there.  But, I suppose that can be discussed on the PR review.

I do think the last piece is a documentation issue IMHO, since any of the behaviors I listed could be possible based on the documentation.  However, I understand there is a fine line between support and pointing out gaps in documentation that need to be addressed.  We may have different viewpoints on where this one stands.  You could consider adopting a policy to categorize between these, or simply reject all documentation issues that relate to usage.  But I think having a clear policy would be helpful here.

**Comment by MatthewFlamm** [comment]
PS.  I am reading the backend code now, and I think I understand the answer to 95% of my questions, so I can open up a PR.  So I think the discussion on this particular issue is moot, but I still softly suggest thinking about how to handle documentation issues vs. support issues.
