### ISSUE TITLE
z-wave.markdown pozw build inst seem to be missing a dep on Rasbian image

### ISSUE THREAD

**Issue by instantchow** [home-assistant/home-assistant.github.io#1174]
After following the instructions to image a new Rasbian 1.0 image, ran the python3 openzwave build procedure all the way to `make install` and adding the `zwave:` section to `configuration.yml` however I get:

> homeassistant.components.zwave: You are missing required dependency Python Open Z-Wave. Please follow instructions at: https://home-assistant.io/components/zwave/
> homeassistant.bootstrap: component zwave failed to initialize

**Comment by Landrash** [comment]
The image in question your referring to I'm assuming it's our Hassbian image. 
I'll add it to my list of things to look into and I'll try to get you the instructions your missing. 
A bit backlogged this weekend but I'll do my best :)

**Comment by instantchow** [comment]
Ok, I think I figured it out. Basically, using the Hasbian image, you need to activate and install into the virtualenv that hass runs from. I should have figured this out sooner. 

Either the Zwave or the Hasbian *getting started* page needs to be updated. Probably the former. Maybe a seperate section for building pyozw thats tailored just for Haspbian.

**Comment by brianjking** [comment]
@instantchow Since you're the one that created the issue you should be able to reopen the issue.

**Comment by jordandrako** [comment]
I'm really trying to get this to work. I've resorting to skipping hassbian and the AiO to install everything manually. Alarmdotcom works until I install openzwave.

**Comment by brianjking** [comment]
It might make more sense to open an issue in the home-assistant main repository or post in the support forums.

**Comment by Landrash** [comment]
Move over issue over to https://github.com/home-assistant/pi-gen/issues/4
