### ISSUE TITLE
Fix http documentation

### ISSUE THREAD

**Issue by klejejs** [home-assistant/home-assistant.github.io#11764]
**Home Assistant release with the issue:**

v0.104

**Last working Home Assistant release (if known):**
v0.101

**Operating environment (Hass.io/Docker/Windows/etc.):**

Docker

**Integration:**

https://www.home-assistant.io/integrations/http/

**Description of problem:**
In the http documentation it says api_password is deprecated but in the Home Assistant version 0.104 it doesn't work at all. Docker container crashes while starting.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml
http:
  api_password: "myPassword"
```

**Traceback (if applicable):**
```

```

**Additional information:**

**Comment by frenck** [comment]
Thanks!

I've adjusted the documentation (can take a moment before it appears on the live site).

**Comment by klejejs** [comment]
Thanks, it has been updated!
