### ISSUE TITLE
Architectural: inconsistent integrations' services' descriptions

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant.github.io#11762]
Recently I saw [plenty of integrations](https://www.home-assistant.io/integrations/input_select#services) adding a list of available services.

It's great, but the trouble is there is no standard of how to represent this information and at this point I think it's reasonable to create some to make the documentation more consistent and informative.

My proposal is to create a simple guidance on the structure of each integration's page (i.e description, configuration, services, examples) and  how each section should be displayed.

For example, in terms of services the way they do it for the [light](https://www.home-assistant.io/integrations/light) integration is more consistent and useable than for [input_select](https://www.home-assistant.io/integrations/input_select#services), perhaps because in the first case the services are described individually and have a common well-structured description when in the second case it's all squashed in one section and there is absolutely no information on service data apart form a list of variables, which is absolutely not enough to understand what their values can be.

Apart form that, plenty of integrations don't show information about their services to users at all and it needs to be tackled, too.

**Comment by frenck** [comment]
This is being worked on actually.

We are planning on syncing the services from the codebase for the documentation (instead of relying on manually maintaining the documentation for this).

The first steps are already in effect, we started syncing integration names, code owners, configuration flow or not and integration quality scale from the codebase to the documentation in an automation fashion.

**Comment by akasma74** [comment]
Glad to hear that!
Should I close the issue?

**Comment by frenck** [comment]
Yes lets close it for now :)
