### ISSUE TITLE
Etekcity VeSync attribute appear and disappear randomly

### ISSUE THREAD

**Issue by clandestine-avocado** [home-assistant/home-assistant.github.io#11776]
The `current_power_w` attribute appears and disappears frequently, making template sensors unusable. This does not appear to have anything to do with if there is currently power being drawn from the device.

This is not an issue of the attribute value not being returned - the attribute itself disappears from the states table. I.E if you put "current_power_w" in the filter, it will show the devices - and periodically devices will drop off, and come back.

Edit: It does appear to have something to do with whether or not there is power being drawn. Here is a history graph of the wattage. When the power spike, this is when a phone was being charged on the outlet. The bottom is a binary template sensor set to turn "on" when the outlet registers an "unavailable" reading from the current_power_w attribute, like this:

```
binary_sensor:
  - platform: template
    sensors:
      outlet_status:
        friendly_name: "Becca's Outlet unavailable?"
        value_template: >-
          {{
          is_state('sensor.becca_outlet_watts', 'unavailable') 
          }}
```

![outlet_wattage_etekcity_vesync](https://user-images.githubusercontent.com/56581105/72645052-a6f53780-3940-11ea-93f4-80339b764db6.jpg)

**Comment by ha14937** [comment]
Edit:  It does appear to have something to do with whether or not there is power being drawn. Here is a history graph of the wattage. When the power spike, this is when a phone was being charged on the outlet. The bottom is a binary template sensor set to turn "on" when the outlet registers an "unavailable" reading from the current_power_w attribute, like this:
```
binary_sensor:
  - platform: template
    sensors:
      outlet_status:
        friendly_name: "Becca's Outlet unavailable?"
        value_template: >-
          {{
          is_state('sensor.becca_outlet_watts', 'unavailable') 
          }}

```
![outlet_wattage_etekcity_vesync](https://user-images.githubusercontent.com/56581105/72639495-b0c46e00-3933-11ea-9649-8d94a2608b5a.jpg)

**Comment by frenck** [comment]
Hi there @ha14937!

Thank you for opening up an issue, however, it is created in an incorrect location. This is the issue tracker for our documentation and website. 

If you have issues with Home Assistant itself, please create an issue at:

<https://github.com/home-assistant/home-assitant/issues>

**Comment by clandestine-avocado** [comment]
> Hi there @ha14937!
> 
> Thank you for opening up an issue, however, it is created in an incorrect location. This is the issue tracker for our documentation and website.
> 
> If you have issues with Home Assistant itself, please create an issue at:
> 
> https://github.com/home-assistant/home-assitant/issues

Sorry - I'm new to Git and still feeling my way around. [Posted ](https://github.com/home-assistant/home-assistant/issues/30943)in the proper place, thanks!

FYSA - I'm guessing you copy paste this friendly redirection to noobs like me all the time, so I wanted to let you know that the link you posted has "assistant" misspelled - so it takes you to a 404 error page.
