### ISSUE TITLE
error Service zwave/start_network. Service not found.

### ISSUE THREAD

**Issue by ollimagic** [home-assistant/home-assistant.github.io#11771]
After update to the latest version my Z-Wave network is not more starting
any suggestions? Aeotec Z-Wave Stick Raspberry PI4

Error setting up entry Z-Wave for zwave
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/config/custom_components/zwave/__init__.py", line 438, in async_setup_entry
    async_entities_added_callback=lambda: None,
TypeError: __init__() got an unexpected keyword argument 'async_entities_added_callback'

**Comment by frenck** [comment]
Hi there, @ollimagic! Thanks for opening up an issue!

However, this is the GitHub issue tracker to track issues with our documentation and website. For an issue with Home Assistant, please create an issue here:

<https://github.com/home-assistant/home-assistant/issues>
