### ISSUE TITLE
HA 104.1 breaks Vizio

### ISSUE THREAD

**Issue by trentjw** [home-assistant/home-assistant.github.io#11792]
104.1 will not see Vizio TV if they are off during a server reboot and are unavailable, they are seen and seem to function as intended if they are on during server reboot

**Comment by frenck** [comment]
Hi there @trentjw,

This is the GitHub project for tracking issues on our documentation or website. If you have issues with Home Assistant itself, please use the GitHub issue tracker of the codebase: <https://github.com/home-assistant/home-assistant/issues>
