### ISSUE TITLE
Enhancement: log file rollover

### ISSUE THREAD

**Issue by chemelli74** [home-assistant/home-assistant.github.io#11810]
Hi,
would you consider implementing a daily rollover of the log file?
Would be really useful when you have debug active to identify an issue, so you just work on home-assistant-2020-01-18.log" for example.

I would also add a parameter to specify number of days to keep old log files.

Thank you,

Simone

**Comment by frenck** [comment]
Hi there, @chemelli74!

You have reached the issue tracker for our website and documentation. Not the main project. However, for feature requests, please use our Community Forum: <https://community.home-assistant.io>

Thanks! 👍
