### ISSUE TITLE
Component "media_player" lacking docs for "media_play" service

### ISSUE THREAD

**Issue by LordMike** [home-assistant/home-assistant.github.io#11874]
## The problem
On [this page](https://www.home-assistant.io/integrations/media_player/), the `media_play` service is listed, but it is never described.

I just came from using `media_play` where i should have used `play_media` (And I'm [not the first](https://github.com/home-assistant/home-assistant/issues/23483)).

Sidenote: If `media_play` serves no purpose, why is it there? -- edit: I think it might be used for "starting" a playback?..

**Comment by kaizersoje** [comment]
I do not think this has been resolved yet. There is still no documentation for the `media_play` service.
