### ISSUE TITLE
Darksky sensor and weather integration

### ISSUE THREAD

**Issue by VDRainer** [home-assistant/home-assistant.github.io#11878]
## The problem

The darksky sensor integration is shown as weather in the integration overview.
So there are two weather integrations shown.
![Auswahl_255](https://user-images.githubusercontent.com/26381449/73131408-b04e6600-400a-11ea-99a0-b2c3223c4135.png)

**Comment by frenck** [comment]
It is correct, there are 2 different darksky implementations.
One is using the `weather` platform, the other the `sensor` platform. 

Both show up in the `weather` category.
