### ISSUE TITLE
Extract Lovelace action documentation into a new page

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant.github.io#11886]
## The problem

Every Lovelace card that supports tap_action, double_tap_action etc has a full copy of all available data, which takes up a lot of screen real estate and leaves no place for examples etc.

We should extract it into its own page.

**Comment by PurelyNicole** [comment]
I can take this. Can someone assign it to me so it doesn't fall off my radar?

**Comment by PurelyNicole** [comment]
Thanks!

**Comment by PurelyNicole** [comment]
Update: Work started. New page created. Still working on updating individual cards.
