### ISSUE TITLE
latest-release-notes is also including android change logs.

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant.github.io#11909]
**Description of problem:**
The "Release notes"-link on the website, and also the link in the Hass.io dashboard next to the update button is using `https://www.home-assistant.io/latest-release-notes/` to redirect to the latest changelog, but it is currenly showing the changelog for the (nevertheless awesome) Android app.

**Comment by frenck** [comment]
Thanks for reporting that in, that is not correct behavior.

**Comment by frenck** [comment]
Added some additional logic to mitigate this.
Deployed on production, take a bit before it becomes visible.
