### ISSUE TITLE
bluetooth_tracker documentation is unclear

### ISSUE THREAD

**Issue by jsprenkle** [home-assistant/home-assistant.github.io#11932]
## The problem: Documentation is unclear.

This [page](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/bluetooth_tracker.markdown):  bluetooth_tracker

Gives instructions for debian distros but it's unclear how much, if any, of this applies to hass.io installs. Is there a separate documentation tree for each distro or should this be corrected to add info for hass.io on this page?

**Comment by frenck** [comment]
Hass.io (now just Home Assistant), takes care of dependencies for you. There is no additional software you need to install for that.

**Comment by jsprenkle** [comment]
Thanks, I'll submit a patch to the documentation page,
