### ISSUE TITLE
Remove state as a required field for the CLA

### ISSUE THREAD

**Issue by brettp** [home-assistant/home-assistant.github.io#11947]
## The problem
Is there a reason state is required to sign [the CLA](https://www.home-assistant.io/developers/cla_sign/)? This seems like unnecessary information to confirm the terms of the agreement.

It's also very likely a contributor may prefer to remain anonymous, or at the least not want to disclose their location. Also, state can [sometimes be considered PII](https://en.wikipedia.org/wiki/Personal_data#NIST_definition), so depending on the jurisdiction, the recording of it can trigger additional protection and disclosure burdens that a project may not want to be responsible for.

**Comment by fabaff** [comment]
IANAL, the state is needed because different countries have different interpretation of the ownership of contributions. In some countries the author is not always the owner and in others the author is always the owner (copyright holder) no matter if the works was done during employment for not.   

From my understanding all requirements for the CLA/DCO are personal data.

**Comment by brettp** [comment]
That makes sense, and I can understand why the _country_ is needed, but not why the state / territory is.

**Comment by frenck** [comment]
The things that apply to country also apply to State. State laws.

**Comment by brettp** [comment]
Also not a lawyer, but wouldn't the laws bind to the project's location, not the contributor's? For example, I don't think I'd be able to apply laws from Delaware state to a project based in California.

I've never seen this requirement in other CLAs, even for large, corporate-sponsored OSS projects. Here are a few examples:

* MS: https://cla.opensource.microsoft.com/microsoft/hcsshim (specifically says you're bound by Washington)
* Google: https://cla.developers.google.com/about/google-individual
* Django: https://www.djangoproject.com/foundation/cla/
* Linux: https://wiki.linuxfoundation.org/dco (a DCO, so not exactly the same)

As a contributor, I'd much rather not have to sign a CLA, but if I do I'd like to have a minimum bar of entry and minimal amount of personal information exposed.

**Comment by frenck** [comment]
@balloob ?

**Comment by balloob** [comment]
I talked with Robbie, as we did this together back then. We based the form back then on the GitHub CLA (which we can no longer find).

I don't feel comfortable to remove it without expert help and I don't want to pay an expert. 

We have had this for years and never had complaints so I don't want to fix this.

**Comment by brettp** [comment]
Thanks for the discussion and info. I'll go ahead and retract my PR. Please do let me know if this policy or the CLA changes.

**Comment by balloob** [comment]
Fine.

You don't want to put your state in a CLA form but on GitHub it's fine?

![image](https://user-images.githubusercontent.com/1444314/73783661-ed240680-4748-11ea-945a-636f972ad25a.png)

**Comment by brettp** [comment]
Yes, that's correct, because on GH it is not a requirement and I can put anything I want there without consequence or having to sign off on its validity.

CLAs are legally binding and impact both myself and my employer, so need to be more meticulously considered.
