### ISSUE TITLE
Markdown documentation error.

### ISSUE THREAD

**Issue by noppo** [home-assistant/home-assistant.github.io#11960]
Reported this first as a lovelace error:
https://github.com/home-assistant/home-assistant-polymer/issues/4732#issuecomment-581191696

But it seems to be more of a documentation error. 

The template example on the buttom does not work. Below is a working example:
```
type: markdown
entity_id:
  - light.bed_light
  - light.ceiling_lights
  - light.kitchen_lights
content: |
  The lights that are on are:
  {% for l in config.entity_id %}
    - {{ l }}
  {%- endfor %}
  And the door is {% if is_state('binary_sensor.door', 'on') %} open {% else %} closed {% endif %}.


```

**Comment by frenck** [comment]
Could you please open a PR to correct that? Thanks! 👍

**Comment by mikepan-ovoenergy** [comment]
This one is still reproducible. Shouldn't be closed.

**Comment by fabiopedrosa** [comment]
@frenck still applies. Parameter is not being used, which is a clear bug.
