### ISSUE TITLE
config_dir location

### ISSUE THREAD

**Issue by ob2s** [home-assistant/home-assistant.github.io#11998]
ignore

**Comment by frenck** [comment]
Hi there @ob2s!

Thanks for opening an issue, however, we use GitHub for tracking issues, and this repository specifically for tracking issues with our website.

If you are in need of support on running Home Assistant or Home Assistant Core, I would recommend on joining the Community Forum, or our Discord chat:

<https://www.home-assistant.io/join-chat>

Thanks! 👍
