### ISSUE TITLE
Can no longer ignore Samsung TV in discovery integration

### ISSUE THREAD

**Issue by Brazen00** [home-assistant/home-assistant.github.io#12003]
As of 0.105.0, using the following code:
`discovery:
  ignore:
    - samsung_tv
`

Results in this error

`2020-02-07 09:46:52 ERROR (MainThread) [homeassistant.config] Invalid config for [discovery]: value is not allowed @ data['discovery']['ignore'][0]. Got 'samsung_tv'. (See /config/configuration.yaml, line 93). Please check the docs at https://www.home-assistant.io/integrations/discovery
2020-02-07 09:46:52 ERROR (MainThread) [homeassistant.setup] Setup failed for discovery: Invalid config.`

Have also tried using `samsungtv` as the value with the same results.

**Comment by frenck** [comment]
Hi there @Brazen00!

Thanks for opening up an issue, however, this is the issue tracker for our website.

Please open up an issue on the Home Assistant Core repository:

<https://github.com/home-assistant/home-assistant/issues>

Be sure to fill out the issue template presented on that repository as complete as possible.

Thanks! 👍
