### ISSUE TITLE
support for SAMSUNG UE55LS003AUXZT

### ISSUE THREAD

**Issue by pilot1981** [home-assistant/home-assistant.github.io#12006]
Hi,
I tested samsungtv integration on SAMSUNG UE55LS003AUXZT, but it seems don0t works...
I have any chance to have it working? can I do beta tester?

**Comment by klaasnicolaas** [comment]
Hi there @pilot1981 

Thanks for opening an issue, however, we use GitHub for tracking issues, and this repository specifically for tracking issues with our documentation website.

If you are in need of support on running the Samsung TV integration, I would recommend on joining the Community Forum, or our Discord chat:

<https://www.home-assistant.io/join-chat>

If it appears that the integration really does not work in combination with your TV, create a pull request and add the TV's serial number to the list of non-working TVs.

Thanks! 👍
