### ISSUE TITLE
NU7090 Not Supported message

### ISSUE THREAD

**Issue by KrisRux** [home-assistant/home-assistant.github.io#12037]
Hi All,

in samsungtv integration NU7090 return a message than not supported. the same with configuration:

samsungtv:
#NU7090 (port must be set to 8801, On/Off, MAC must be specified for Power On)
  - host: !secret samsungtv_ip
    name: tv_cucina
    port: 8801

**Comment by frenck** [comment]
Hi there @KrisRux,

I'm kinda confused about the reason for opening this issue?
Is the documentation wrong? Or got an issue with the integration itself?

../Frenck

**Comment by KrisRux** [comment]
I have an issue for this integration.

**Comment by frenck** [comment]
OK, the reason why it caused confusion with me, is because this is the issue tracker for our website.

In case you have issue with the Home Assistant Core, please file an issue here:

<https://github.com/home-assistant/home-assistant/issues>

Thanks! 👍
