### ISSUE TITLE
Documentation - Modbus - switch.modbus example - Switch or Sensor confusion

### ISSUE THREAD

**Issue by Cloolalang** [home-assistant/home-assistant.github.io#12043]
https://www.home-assistant.io/integrations/switch.modbus/

The example documented here at the bottom of the page says it is a sensor however the YAML shows as a switch:

> Full example

Example a temperature sensor with a 10 seconds scan interval:

`switch:`
  platform: modbus
  scan_interval: 10
  coils:
    - name: Switch1
      hub: hub1
      slave: 1
      coil: 13
    - name: Switch2
      hub: hub1
      slave: 2
      coil: `14_`

>

**Comment by frenck** [comment]
Opened a PR to address that, thanks for reporting. 👍
