### ISSUE TITLE
how do users backup their lovelace UI configuration?

### ISSUE THREAD

**Issue by fermulator** [home-assistant/home-assistant.github.io#12131]
## The problem
Consider:
* https://www.reddit.com/r/homeassistant/comments/f6ctmu/storage_backup_recommendations/
* https://github.com/home-assistant/home-assistant.io/issues/11082

In a similar vain, today in early-2020, as the "states UI" is deprecated, and "lovelace UI" is the new thing to use, configuration is no longer defined by users in `yaml` files (by default), and so the default recommendations for backup and version control seem to have a gap (at minimum with lovelace).

https://www.home-assistant.io/docs/ecosystem/backup/backup_github/
https://www.home-assistant.io/lovelace/

I think it would be prudent to clear this up.  Ideally while we're considering this, we address more holistically any other gaps in terms of backups & version control.  However if owners prefer to limit the scope here to solving the documentation problem only for lovelace, that is fair.

**Comment by frenck** [comment]
I think the GitHub backup page we have is pretty clear about that:

> A remote copy of your Home Assistant YAML files in case you need to recover.

![image](https://user-images.githubusercontent.com/195327/74912357-da533800-53be-11ea-9532-b89916a5127a.png)


Home Assistant provides snapshots for making complete backups of your Home Assistant system.

**Comment by fermulator** [comment]
Fair point.  Home Assistant provides snapshots? (or do you mean only if running hass.io?) - I'm on a python venv installation

I still stand behind the idea that `lovelace` should be explicitly mentioned here as a candidate for git versioning. (as well as possibly others)

I think we'd do well to differentiate between:
1. which files should be version controlled
2. in addition, which files with the hass dir should be backed up
3. reference to the DB explicitly (covered by #11082) though that needs to be re-opened

Looking for the right recommendations first off before attempting to resolve in documentation. Open for debate/discussion certainly.

**Comment by frenck** [comment]
Hass.io = now called "Home Assistant".

> I still stand behind the idea that lovelace should be explicitly mentioned here as a candidate for git versioning. (as well as possibly others)

That is a feature request, please use our forums for that.

>  addition, which files with the hass dir should be backed up

This page is misleading since it is not about backups, but about publishing part of your configuration on GitHub. So I partly agree with you.

For example, this example clearly doesn't backup your secrets, yet you make a point out of Lovelace.

In your case, you run just the application. Backup of your operating system and thus file system, is out of scope for our documentation.

**Comment by fermulator** [comment]
> In your case, you run just the application. Backup of your operating system and thus file system, is out of scope for our documentation.

sorry I missed this comment or mis-understanding; where did I suggest that home assistant docs should talk about how to backup the operating system or file system?

**Comment by frenck** [comment]
In the title of this issue?
> "how do users backup their lovelace UI configuration"

**Comment by PurelyNicole** [comment]
Wouldn't the kind of comprehensive backup you're talking about be covered under [Configuration Backup to Dropbox](https://www.home-assistant.io/docs/ecosystem/backup/backup_dropbox/) or [Configuration Backup to USB drive](https://www.home-assistant.io/docs/ecosystem/backup/backup_usb/)?

**Comment by fermulator** [comment]
> In the title of this issue?
> 
> > "how do users backup their lovelace UI configuration"

this to me does not imply a request to have homeassistant document how to backup an entire operating system or filesystem

the goal of home assistant backup documentation should instruct users:
1. what is important to backup and what is important to version control (version control not the same as backups of course)
2. for each item, describe roughly WHY, and the IMPACT if lost (allows users to decide what is important to them)
2. for each item, describe recommendations for how (or provide reference to)

to my knowledge so far, we have at least 3x things (and possibly more)
1. the standard *.yaml configuration files (already sufficiently documented)
2. the new lovelace UI config (not documented)
3. the DB (which contains states, not sure what else); #11082 
4. what else? 

For "what else?", the ask here is to be a bit more explicitly clear in describing the various files that home assistant reads/creates/owns within the directory structure of the application.

**Comment by fermulator** [comment]
@bot go away

**Comment by fermulator** [comment]
(go away bot)
