### ISSUE TITLE
Xiaomi Aqara - znldp12lm bulb

### ISSUE THREAD

**Issue by antonbek89** [home-assistant/home-assistant.github.io#12143]
Hi
I not understand if i add the bulb znldp12lm to the hub
Why i not see it in HA?

In the description "https://www.home-assistant.io/integrations/xiaomi_aqara/"
Not write if it support or not

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
