### ISSUE TITLE
Discover Konnected Device

### ISSUE THREAD

**Issue by weswark** [home-assistant/home-assistant.github.io#12190]

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
