### ISSUE TITLE
New way of discovering and retrieve token for Xiaomi devices

### ISSUE THREAD

**Issue by viztor** [home-assistant/home-assistant.github.io#12204]
The current doc only described a hackish way of retrieving Xiaomi IoT token though its official mobile app, though a new way has been noticed.

Thanks to aholstenson/miio, It is actually much easier to use his package to discover Xiaomi IoT devices though MIIO discover, wonder when that will be part of home-assistant.

**Comment by frenck** [comment]
That method is described (via a different package), however, doesn't work in many many cases.

Furthermore, this is the issue tracker for our website/documentation, but your created issue is actually a feature request. Please use our Community Forum for those.

Thanks! 👍
