### ISSUE TITLE
Konnected.io config flow documentation

### ISSUE THREAD

**Issue by hunterjm** [home-assistant/home-assistant.github.io#12203]
## The problem
Moving the third item from https://github.com/home-assistant/home-assistant/issues/32076 here because it is docs related.

The documentation for the options flow for zone configuration is sparse in the docs website and is not very intuitive off the bat.  The only reference is as follows:

>You can then utilize the options flow to configure or modify the behavior of each zone.

It would be great to have some additional documentation around the steps it takes to configure the individual zones and how that shows up utilizing the config flow method introduced in 0.106.0.

@kit-klein

**Comment by kit-klein** [comment]
I can assist with this @frenck

**Comment by klaasnicolaas** [comment]
Well just go with the flow then @kit-klein 😉

**Comment by frenck** [comment]
Documentation is adjusted.
