### ISSUE TITLE
telegram_bot.send_sticker info seems to be wrong.

### ISSUE THREAD

**Issue by Mifulapirus** [home-assistant/home-assistant.github.io#12249]
It seems like [this information](https://github.com/home-assistant/home-assistant.io/blob/next/source/_integrations/telegram_bot.markdown#service-telegram_botsend_photo-and-telegram_botsend_sticker) is not right for the stickers as they don't have ```URL``` or ```paths```.

Here is the usual information in a sticker message, in case it helps:
```
"message": {
        [...]
        "sticker": {
            "width": 512,
            "height": 512,
            "emoji": "\ud83d\udc4d",
            "set_name": "BanditRaccoon",
            "is_animated": false,
            "thumb": {
                "file_id": "AAMCAgADGQEAAQWnYl5eR4ebTwhTKqskKCAuMSDntyBeAAJYAwACz7vUDnSoodcl1REsadyFDwAEAQAHbQADOGQAAhgE",
                "file_unique_id": "AQADadyFDwAEOGQAAg",
                "file_size": 22982,
                "width": 320,
                "height": 320
            },
            "file_id": "CAACAgIAAxkBAAEFp2JeXkeHm08IUyqrJCggLjEg57cgXgACWAMAAs-71A50qKHXJdURLBgE",
            "file_unique_id": "AgADWAMAAs-71A4",
            "file_size": 42148
        }
    }
```

**Comment by frenck** [comment]
Feel free to open up a PR to correct the information! 👍

**Comment by Mifulapirus** [comment]
I'd love to, but unfortunately everything I've tried has failed and it doesn't seem like anyone has actually made it work.
If I come up with a solution, I'll be happy to contribute.
😄

**Comment by ludeeus** [comment]
Handled with https://github.com/home-assistant/home-assistant.io/pull/19715
