### ISSUE TITLE
MELCloud integration - device not showing up

### ISSUE THREAD

**Issue by daggr8** [home-assistant/home-assistant.github.io#12246]
Regarding the new MELCloud integration https://www.home-assistant.io/integrations/melcloud/

I've tried adding it in the GUI and the yaml file with the X-MitsContextKey token. Both time the integration in HA shows up. But no devices.

EDIT: It worked with the custom component before (yes, i've deleted those files in the custom_components folder now).

**Comment by frenck** [comment]
Hi there @DanielGrankvist!

Thanks for opening up an issue, however, this is the issue tracker for our website. If you want to report a bug with the integration, please go here:

<https://github.com/home-assistant/core/issues>

For help and support, please use our Community Forum or the Discord chat server.

Thanks! 👍
