### ISSUE TITLE
Nginx configuration inconsistency

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant.github.io#12253]
## The problem

There are two different example configurations for nginx.

Here: https://www.home-assistant.io/docs/ecosystem/nginx/#nginx-configuration
And here: https://www.home-assistant.io/docs/ecosystem/nginx_subdomain/#subdomain

Both are different in several places that have nothing to do with the things of the domain/subdomain.

Maybe it would be easier to list the required headers and other specific configurations and reference the Mozilla SSL configuration generator for further configurations:
https://ssl-config.mozilla.org/

At least it should be made clear whether or not you need to split the location into `/` and `/api/websocket' and what subset of headers is really needed. Everything else is out of scope IMHO.

**Comment by frenck** [comment]
This one seems to be the most detailed and correct on first glance:

<https://www.home-assistant.io/docs/ecosystem/nginx/#nginx-configuration>

Let's remove the other one.

**Comment by Santobert** [comment]
We should drop `TLSv1 TLSv1.1` as well and add `TLSv1.3` instead.
Therefore I would suggest to point to another website instead of writing recommendations ourselves. They tend to be outdated.
@frenck What do you think about https://ssl-config.mozilla.org/?

Just a guess, but I think the only relevant things are:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
```
as well as
```
proxy_buffering off;
```
and
```
    location / {
        proxy_pass http://127.0.0.1:8123;
        proxy_set_header Host $host;
        proxy_redirect http:// https://;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
```

dhparams are nice to have, but not necessary for HA, even though the documentation implies otherwise

**Comment by frenck** [comment]
we follow the mozilla recommendations for the nginx proxy add-ons as well, so that is fine.

The connection upgrade mapping is required / really good thing to do. E.g., without it, you would have issues with applications on application served by aiohttp 3.6.2 (which is why we are pinned to 3.6.1 at this moment).

Rest looks ok. Generating and setting dhparams is recommended, but not required.

**Comment by Wonderbox2000** [comment]
Hi,
I am trying to host my Home Assistant instance behind an existing and working nginx server.
My nginx server is hosting a nextcloud and motioneye instance working quitely with https.

my /etc/nginx/nginx.conf:

`
user www-data;
worker_processes auto;
pid /var/run/nginx.pid;
events {
worker_connections 1024;
multi_accept on;
use epoll;
}
http {
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
server_names_hash_bucket_size 64;
upstream php-handler {
server unix:/run/php/php7.4-fpm.sock;
}
set_real_ip_from 127.0.0.1;
# set_real_ip_from 192.168.2.0/24;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
include /etc/nginx/mime.types;
include /etc/nginx/proxy.conf;
include /etc/nginx/ssl.conf;
include /etc/nginx/header.conf;
include /etc/nginx/optimization.conf;
default_type application/octet-stream;
access_log /var/log/nginx/access.log;
error_log /var/log/nginx/error.log warn;
sendfile on;
send_timeout 3600;
tcp_nopush on;
tcp_nodelay on;
open_file_cache max=500 inactive=10m;
open_file_cache_errors on;
keepalive_timeout 65;
reset_timedout_connection on;
server_tokens off;
resolver 127.0.0.53 valid=30s;
resolver_timeout 5s;
include /etc/nginx/conf.d/*.conf;
`
and my /etc/nginx/conf.d/hass.conf is:

`server {
    listen       80 ;
    server_name  hass2.lafoliedesgrandeurs.site;

    return 301 https://$host$request_uri;
}


server {
    listen       443 ssl;
    server_name  hass2.lafoliedesgrandeurs.site;

    ssl on;
 #   ssl_certificate /etc/nginx/ssl/countryside.example.org/countryside.example.org-bundle.crt;
 #   ssl_certificate_key /etc/nginx/ssl/countryside.example.org/countryside.example.org.key;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://localhost:8124;
        proxy_set_header Host $host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/websocket {
        proxy_pass http://localhost:8124/api/websocket;
        proxy_set_header Host $host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
}
`

I am still getting 502 - Bad Gateway error.

Can someone help me please ?

**Comment by Wonderbox2000** [comment]
Hi,
I am trying to host my Home Assistant instance behind an existing and working nginx server.
My nginx server is hosting a nextcloud and motioneye instance working quitely with https.

my /etc/nginx/nginx.conf:

```
user www-data;
worker_processes auto;
pid /var/run/nginx.pid;
events {
worker_connections 1024;
multi_accept on;
use epoll;
}
http {
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
server_names_hash_bucket_size 64;
upstream php-handler {
server unix:/run/php/php7.4-fpm.sock;
}
set_real_ip_from 127.0.0.1;
#set_real_ip_from 192.168.2.0/24;
real_ip_header X-Forwarded-For;
real_ip_recursive on;
include /etc/nginx/mime.types;
include /etc/nginx/proxy.conf;
include /etc/nginx/ssl.conf;
include /etc/nginx/header.conf;
include /etc/nginx/optimization.conf;
default_type application/octet-stream;
access_log /var/log/nginx/access.log;
error_log /var/log/nginx/error.log warn;
sendfile on;
send_timeout 3600;
tcp_nopush on;
tcp_nodelay on;
open_file_cache max=500 inactive=10m;
open_file_cache_errors on;
keepalive_timeout 65;
reset_timedout_connection on;
server_tokens off;
resolver 127.0.0.53 valid=30s;
resolver_timeout 5s;
include /etc/nginx/conf.d/*.conf;
```
and my /etc/nginx/conf.d/hass.conf is:

```
server {
    listen       80 ;
    server_name  hass2.lafoliedesgrandeurs.site;

    return 301 https://$host$request_uri;
}


server {
    listen       443 ssl;
    server_name  hass2.lafoliedesgrandeurs.site;

    ssl on;
 # ssl_certificate /etc/nginx/ssl/countryside.example.org/countryside.example.org-bundle.crt;
 #   ssl_certificate_key /etc/nginx/ssl/countryside.example.org/countryside.example.org.key;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://localhost:8124;
        proxy_set_header Host $host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /api/websocket {
        proxy_pass http://localhost:8124/api/websocket;
        proxy_set_header Host $host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
}
```

I am still getting 502 - Bad Gateway error when testing access to Home Assistant

Can someone help me please ?

**Comment by frenck** [comment]
@Wonderbox2000 This is the issue tracker for our website. If you are looking for help, please join our Discord server or Community forum.

Thanks 👍

**Comment by frenck** [comment]
This part of the documentation has moved the the community forums wiki and is no longer mentioned/managed on our main website.

Therefore this issue can be closed.
