### ISSUE TITLE
Developer docs are out of date

### ISSUE THREAD

**Issue by sebr** [home-assistant/home-assistant.github.io#12261]
## dev-docs.home-assistant.io is out of date

It appears that the developer docs have not been updated in a while. For example, on this page:

http://dev-docs.home-assistant.io/en/stable/api/helpers.html

the link to [`homeassistant.helpers.condition.and_from_config(config: Dict[str, Any], config_validation: bool = True)`](https://github.com/home-assistant/core/blob/master/homeassistant/helpers/condition.py#L34)

shows the incorrect line reference.

<img width="877" alt="Screen Shot 2020-03-04 at 11 56 14 am" src="https://user-images.githubusercontent.com/81972/75834102-29618a00-5e0f-11ea-8de2-2c1df325f6b3.png">

The impact is that I am not confident that the dev-docs are showing me all the helper methods which are available to use.

**Comment by springstan** [comment]
Please open an issue or a PR [here](https://github.com/home-assistant/developers.home-assistant).
