### ISSUE TITLE
Filter sensor documentation is missing quotes around window_size

### ISSUE THREAD

**Issue by sithmein** [home-assistant/home-assistant.github.io#12289]
https://www.home-assistant.io/integrations/filter/ has examples for the `window_size` parameter without quotes in the _configuration.yaml_. However in my case it didn't work (with the moving average filter) until I added quotes, e.g.
```
    window_size: "12:00"
```
After that it seems to behave as expected.
See also https://community.home-assistant.io/t/moving-average-filter-not-behaving-as-expected/176768 for more details.

**Comment by frenck** [comment]
Feel free to help out by correcting the error. Every page has an "Edit this page" link in the top right. 

Thanks! 👍
