### ISSUE TITLE
Add note about whitelisted dirs

### ISSUE THREAD

**Issue by Santobert** [home-assistant/home-assistant.github.io#12360]
## The problem
PR #8189 added the `whitelist_dirs` option, but not many people know about it.

1. https://community.home-assistant.io/t/problem-with-telegeram-after-update-0-48-0/20867
2. https://community.home-assistant.io/t/cannot-send-specific-jpg-via-telegram-bot-error-are-not-secure-to-load-data-from/107466
3. https://community.home-assistant.io/t/cant-send-video-with-telegram/51248
4. https://community.home-assistant.io/t/video-in-telegram-notification/22571/5
5. https://community.home-assistant.io/t/problem-sending-picture-to-telegram/141288

Even more, the telegram documentation provides an example that does not work without this option.

https://www.home-assistant.io/integrations/telegram/#photo-support

I think a small note and a link to the documentation would help a lot.

https://www.home-assistant.io/docs/configuration/basic/#whitelist_external_dirs

**Comment by frenck** [comment]
Feel free to open up a PR to help us to improve that. Thanks! 👍

**Comment by Santobert** [comment]
Hmm the note is already there, but well hidden:
https://www.home-assistant.io/integrations/telegram/

I guess that some people (including myself) just missed that. The whole telegram documentation is somehow messy, but I have no idea how to improve it.

I'm going to close this issue for now.
