### ISSUE TITLE
SwitchBot integration doesn't work

### ISSUE THREAD

**Issue by edoardop13** [home-assistant/home-assistant.github.io#12379]
I tried adding a switchbot plus to my home assistant instance but it doesn't work. in addition, a switch is created that is not enough for the plus or mini switchbot

- platform: switchbot
  mac: 'Mac address witch lower case letter'
  name: 'SwitchBot Hub Plus'

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
