### ISSUE TITLE
Minimal lifecycle docs for managing alternative supervised linux install from the host

### ISSUE THREAD

**Issue by rct** [home-assistant/home-assistant.github.io#12425]
## Where are minimal start, stop, restart, docs for the *supervised* install (aka the alternative Linux install) *from the host*?

After following, [Alternative: install Home Assistant Supervised on a generic Linux host](https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host) where should a user find some minimal instructions for working with the supervised install on the host - for example, stopping, starting, restarting, and whether access to any of the CLI commands is available?

I've tried a few things, I don't know whether I'm doing the wrong thing, or whether there are bugs/things that haven't been implemented yet.  

## Using systemctl to manage the supervised install.

`systemctl stop hassio-supervisor` stops the `hassio_supervisor` container, but leaves `homeassistant`, `hassio_dns`, and `hassio_audio` and add-on containers still running.

Should stopping the supervisor leave those other containers running?

Stopping the hassio-apparmor service with systemd does nothing, there is no ExecStop defined in the systemd unit file. 

## Trying to (re)start with systemctl

What's the right way to restart all of the containers without rebooting?

After stopping everything with `systemctl stop hassio-supervisor` and `docker stop homeassistant hassio_dns hassio_audio`.  

If I try:
```
systemctl start hassio-supervisor.service
systemctl start hassio-apparmor.service
```

At that point the `homassistant` container isn't running, only the `hassio_supervisor`, `hassio_dns`, and `hassio_audio` containers are running.

What is supposed to start the `homeassistant` container if it isn't the supervisor?

## Don't use `docker stop` to stop the supervisor?

Using `docker stop homeassistant hassio_supervisor hassio_dns hassio_audio`, without doing a `systemctl stop hassio-supervisor` appears to be the wrong thing to do because systemd will automatically restart the supervisor container.

## Are any of the `ha` CLI commands available/applicable with the supervised install?

Are any of the `ha`/hass* CLI commands applicable to the supervised install or should they be avoided? 

If they are still applicable how should they be accessed?

Installing the official or community ssh add-on needs to be done in a way that it won't conflict with the host's sshd.

----
Given that the supervised HA install is at least partially managed by the supervisor and is different than other methods, the docs should cover:

1. The default location for the data and configuration files is in `/usr/share/hassio`.  The configuration files are in the `homeassistant` sub directory.  This can be changed during installation using the `-d` and `-p` options,   The prefix and data share arguments are used together.
1. Mention that the installation process will add systemd unit files which will start the supervisor and HA on boot.  It is probably also worth mentioning that the supervisor container is managed by systemd and will be automatically restarted.
1. The recommended method of stopping all of the HA containers.
1. The recommended method to start all of the HA containers without resorting to rebooting.
1. Whether the CLI commands like `ha` are still applicable for this type of instalation, and if so how to access them.
1. Add-on advice - Are there any add-ons/types of add-ons that should be avoided for this type of install?  Possible port conflicts with add-ons and host service?

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

To answer your question: Home Assistant is managed from within Home Assistant. You can access the `ha` command using one of the Terminal/SSH add-ons available.

One should not manage or interfere with any of the Home Assistant parts from the operating system/host level.

**Comment by rct** [comment]
I opened this issue because there seems to be no doc on the basics of interacting with the supervised install. 

I'm willing to help with documentation. But I don't know what the correct procedures are. 

What I think should be documented:
1. As you pointed out "Home Assistant is managed from within Home Assistant. You can access the ha command using one of the Terminal/SSH add-ons available."
1. How to completely (and correctly) shut down the HA processes if you need to do system maintenance, like at the file system level. There is no `ha supervisor stop` 
1. The correct procedure for starting HA without rebooting. `systemctl start hassio-supervisor` only seems to start the homeassistant container on first boot. I don't know if that is a bug or feature.
