### ISSUE TITLE
Lovelace button docs should not have "entity" as required

### ISSUE THREAD

**Issue by pedrolamas** [home-assistant/home-assistant.github.io#12452]
## The problem

Since the change https://github.com/home-assistant/frontend/pull/4581, the `entity` is not required anymore for the Lovelace `button`, but documentation still says it does: https://www.home-assistant.io/lovelace/button/#entity

The documentation should be updated to replace the "(Required)" label with "(Optional)" and the samples updated to show this change.

**Comment by frenck** [comment]
Hi there!

Every page has an edit button in the top right! Please help us out by adjusting the documentation. Thanks and looking forward to the PR! ❤️

**Comment by pedrolamas** [comment]
PR now open! 🙂

**Comment by pedrolamas** [comment]
@frenck not sure of the process here so wanted to check before doing anything: my PR to fix this has now been merged, can we close this now?

**Comment by frenck** [comment]
Yeah, sorry, my bad. Should have closed this.

Thanks for letting me know! 👍
