### ISSUE TITLE
Tankerkoenig docs: scan_interval is seconds, not minutes

### ISSUE THREAD

**Issue by Vedeneb** [home-assistant/home-assistant.github.io#12454]
## The problem
Just a little issue with the new [tankerkoenig integration](https://www.home-assistant.io/integrations/tankerkoenig):
The configuration option for `scan_interval `looks like it expects the value to be in minutes, however it is seconds. So I set the value to `5` which I thought would be 5 minutes. Now my API Key was of course blocked because HAss fetched the API every 5 seconds :) 

It would probably be enough to change the `default_value` from `30` to 30*60 = `1800`.

Thanks in advance!

**Comment by frenck** [comment]
`scan_interval` is always in seconds in Home Assistant.

Feel free to open up a PR to adjust documentation if needed, that is always appreciated and looking forward to it! 👍

**Comment by Vedeneb** [comment]
Thanks, I created a pull request [here](https://github.com/home-assistant/home-assistant.io/pull/12459).

Please tell me whether I did everything correct. Thanks!

**Comment by frenck** [comment]
You did well, thank you! 👍 🏅
