### ISSUE TITLE
ERROR: "Message malformed: extra keys not allowed @ data['action'][0]['message']"

### ISSUE THREAD

**Issue by ericsopa** [home-assistant/home-assistant.github.io#12468]
## The problem
Problem is with this doc page:
https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/automation/editor.markdown

I am entering:
```
{
  "message": "Sensor value greater than 10"
}
```
In to "Service data" under Actions and getting the following error:
```
"Message malformed: extra keys not allowed @ data['action'][0]['message']"
```

Tried yaml, just the value with no key, can't get past this error.
Q: What is accepted here as input?
Can you please update the docs?

Thank you

**Comment by ericsopa** [comment]
This is what was finally accepted:

```
message: Camera detected motion
```

**Comment by fabaff** [comment]
JSON and YAML are working on `dev`. Tested with `persistent_notification.create`

```
{
  "message": "Sensor value greater than 10"
}
```

```yaml
message: Sensor value greater than 10
```
