### ISSUE TITLE
Lovelace dashboards  need a separate page

### ISSUE THREAD

**Issue by akasma74** [home-assistant/home-assistant.github.io#12462]
## The problem

Curently all information about LL dashboards is under [Advanced configuration](https://www.home-assistant.io/lovelace/yaml-mode/#advanced-configuration) on Lovelace YAML mode page.

However, it clearly says "You can also add YAML dashboards when your main dashboard is UI configurated" so it's not limited by YAML mode. Also, the current location makes it difficult to find as it's not obvious.

I suggest to create a separate page at the same level as Lovelace YAML mode and put the information about LL dashboards there.

**Comment by frenck** [comment]
There is no reason to split that page, as it is not big at all. Many pages don't help and we are even consolidating in general.

Feel free to improve the text on the current page in the form of a PR.

**Comment by akasma74** [comment]
I understand the concern about many pages.
Maybe we can add it to Views (making it Dashboards and Views)?

**Comment by akasma74** [comment]
closed by #12707
