### ISSUE TITLE
Docs: Input number: Attribute Step relevant also for box

### ISSUE THREAD

**Issue by edenhaus** [home-assistant/home-assistant.github.io#12470]
## Docs: Input number: Attribute Step relevant also for box
At the moment the docs specify, that the attribute step is only relevant for the slider, but in fact it is also relevant for the box mode.
More information can be found in the frontend issue home-assistant/frontend#5300

**Comment by frenck** [comment]
There is no need to open an issue for each PR.

**Comment by edenhaus** [comment]
@frenck Sorry First I wanted only to create the issue, but with the quarantine in italy I have time and therefore I fixed it directly.
