### ISSUE TITLE
Please reinstate Hassbian docs you've removed for no reason

### ISSUE THREAD

**Issue by orcinus** [home-assistant/home-assistant.github.io#12486]
https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/installation/hassbian.markdown

Hassbian is **not maintained** anymore.
It's not **deprecated**.

There is a difference.

There are still users using Hassbian and it works just fine, it just isn't supported by its maintainer anymore. Those users depend on the documentation you've removed.

Additionally, the "Please move to another installation method." link on the page is dead.

This project is getting more and more immature with each passing month.

**Comment by frenck** [comment]
Hassbian has been deprecated, is now unsupported and unmaintained (all these things).

The documentation will not be re-instated.

**Comment by orcinus** [comment]
Deprecated by what?
Where was it announced it was deprecated?

It's still in use by many, still works, and is still receiving code contributions.

**Comment by frenck** [comment]
https://www.home-assistant.io/blog/2019/10/26/rip-hassbian/

**Comment by orcinus** [comment]
`curl -s https://www.home-assistant.io/blog/2019/10/26/rip-hassbian/ | grep deprecated `

You haven't answered the question.
Deprecated by what? Which component of HA does not work or is incompatible with Hassbian?

**Comment by frenck** [comment]
I’m not sure which fight you are trying to pick. It is RIP (title of the blog post).

We don’t support it.

The documentation will not be re-instated as I told you before.

**Comment by orcinus** [comment]
You don't have to support it and no one is asking for support, just leave the documentation be for people who are still using it. That's the fight i'm trying to pick - don't remove documentation for no good reason. Stating "NOT SUPPORTED ANYMORE" at the top would get the message across just fine.

**Comment by frenck** [comment]
We removed it, not to imply support. Furthermore, it will outdate and need maintenance, which we don’t want. 

Hassbian runs a Home Assistant Core in a Python venv, all documentation we have on that applies.

Lastly, we are open source, everything is stored in git, feel free to get the history of those files and use or even publish them.

Thanks.

../Frenck

**Comment by pvizeli** [comment]
I looked the conversation because it ends in an endless loop and we want stay with https://www.home-assistant.io/code_of_conduct/
