### ISSUE TITLE
MIssing quality level on integrations.

### ISSUE THREAD

**Issue by janiversen** [home-assistant/home-assistant.github.io#12539]
## The problem

Have tried to find the quality level of different integrations, @frenck told (in chat) that it should be in the top right corner, but somehow it seems not to be present.

![Captura de pantalla 2020-03-29 a las 16 15 30](https://user-images.githubusercontent.com/6185391/77852020-a26cbb00-71dc-11ea-85e8-833e839f7207.png)

**Comment by frenck** [comment]
Modbus does not have a score.

![image](https://user-images.githubusercontent.com/195327/77852576-a64e0c80-71df-11ea-9b28-aa85410f694a.png)

**Comment by janiversen** [comment]
that would be good to write as:
Quality scale: no score

I thought it was not possible to get an integration merged without a score, but seems I was wrong.
