### ISSUE TITLE
SSL setup documentation suggests setting cert permissions to 777

### ISSUE THREAD

**Issue by dustin** [home-assistant/home-assistant.github.io#12547]
On https://www.home-assistant.io/docs/ecosystem/certificates/lets_encrypt/, there's a part describing how to configure the certs that's concerning:

    sudo chmod -R 777 /etc/letsencrypt/

**Comment by frenck** [comment]
Thanks!

Feel free to suggest an improvement, you can suggest a change for each page by click the "Edit on GitHub" link that is shown on the top right of each page.

**Comment by tiagofreire-pt** [comment]
The `600` permissions sheme should be enough.

**Comment by frenck** [comment]
The above-listed page has been moved to the community forums/guides and are now a wiki that can be edited by anyone. 👍
