### ISSUE TITLE
Xiaomi router device  Tracker

### ISSUE THREAD

**Issue by kasper1221** [home-assistant/home-assistant.github.io#12698]
## The problem
 homeassistant update 107 broke the device tracker integration of my xiaomi router, now i get the notification that device tracker could not be set up.

do i need to update my config somehow?

**Comment by frenck** [comment]
Hi there,

This is the issue tracker for our website, not Home Assistant itself.
If you are having issue with a Home Assistant integration, please raise an issue at <https://github.com/home-assistant/core/issues>.

Thanks 👍
