### ISSUE TITLE
NextCloud image preview doesn't exist

### ISSUE THREAD

**Issue by bkbilly** [home-assistant/home-assistant.github.io#12759]
## The problem

There is no image preview for the new integration of NextCloud.
https://www.home-assistant.io/integrations/nextcloud/
The image which points to the url doesn't exist: https://www.home-assistant.io/integrations/nextcloud/'/images/screenshots/nextcloud-sample-sensor.png'

**Comment by klaasnicolaas** [comment]
Closing it, should be fixed now 😄
