### ISSUE TITLE
Duplicate media player entries

### ISSUE THREAD

**Issue by artazzo** [home-assistant/home-assistant.github.io#1278]
Well done for your efforts!

I have set up a PanasonicViera TV as a device in HomeAssistant.  Entry in configuration.yaml below:

media_player:
  - platform: panasonic_viera
    host: 192.168.0.80
    name: "PanasonicTV"

Discovery is on.

The device appears in the web interface as it is supposed to do.  

However, a separate media player called Unnamed Device also appears.  This essentially controls the same TV.  When the TV is off, this goes away.

Tracking of devices is enabled and I have tried to edit the related entry in the known_devices.yaml file as follows:

PanasonicViera:
  name: Panasonic-Viera
  mac: CC:AA:CF:28:F7:4F
  picture: 
  track: yes
  hide_if_away: no

Somehow I cannot get rid of this second entry.

**Comment by danielperna84** [comment]
Not sure if it's related, but I've noticed something similar. In my case it's two Sony Bravias with Android TV. And additionally it seems as if the Plex web-client (when watching through Chrome in my case) also gets detected multiple times. Not long ago I had about 5 of them in the HASS UI.
They all have in common that they are media player entities, so maybe this is independet of the actual device that's being used.

**Comment by artazzo** [comment]
Did you find a solution by any chance ?

**Comment by artazzo** [comment]
Excuse my ignorance as I am new to this but can you explain where I should have posted please?

**Comment by danielperna84** [comment]
This would be the right location: https://github.com/home-assistant/home-assistant/issues
And now, I haven't, since it seemed to me to be an expected behavior.

**Comment by artazzo** [comment]
Thanks Daniel.

**Comment by artazzo** [comment]
moved to the right location advised.
