### ISSUE TITLE
Telegram Bot encodes "text" field as an encoded python dict and not as json encoded string

### ISSUE THREAD

**Issue by lsmonki** [home-assistant/home-assistant.github.io#12794]
I'm trying to use the telegram bot to download files to the server with node red, when you send a file to telegram all the object data is encoded as json on the text field and you can manipulate it, but the HA Telegram Bot encodes this field as a python dict and can't be manipulated or decoded.

This "text" field should be a JSON string.

**Comment by joogps** [comment]
@lsmonki I think you're looking for the [home-assistant/core](https://github.com/home-assistant/core) repository.

**Comment by lsmonki** [comment]
Yes sorry.

**Comment by joogps** [comment]
It's fine, you don't need to apologize. Just make sure to close this issue. :D
