### ISSUE TITLE
Roku Media Player power button not working

### ISSUE THREAD

**Issue by iptvcld** [home-assistant/home-assistant.github.io#12828]
Added the roku media player via integration and when I display the media player entity in LL, the power button does nothing. No error is reported in the logs as well.

**Comment by joogps** [comment]
@iptvcld I think you're looking for the [home-assistant/core](https://github.com/home-assistant/core) repository.

**Comment by frenck** [comment]
Yep, this is the issue tracker for our website. If you have issues with an integration, please report the issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
