### ISSUE TITLE
Service Dev tools Empty field with linefeed not posting

### ISSUE THREAD

**Issue by kellerza** [home-assistant/home-assistant.github.io#1303]
If the `Serive Data` field has a spare linefeed / `Enter` in it the data fails to post.

Expected behavior: Whitespace and linefeed should be stripped out before validating the user input

**Comment by Landrash** [comment]
Are you sure this is in the right repo @kellerza?

**Comment by kellerza** [comment]
Ah, https://github.com/home-assistant/home-assistant-polymer/issues/140
