### ISSUE TITLE
Improve documentation for Docker shared folders

### ISSUE THREAD

**Issue by JaneX8** [home-assistant/home-assistant.github.io#13120]
## The problem

I love this tool, started enthusiastically using it last week connecting all my Smart Home devices and scripts that I've already made before. I also love docker and use it for many things. I started my container using this command:

````bash
docker run --init -d \
    --name="home-assistant" \
    -e "TZ=Europe/Amsterdam" \
    -v /media/someMountedDisk/homeassistant:/config \
    --net=host
    homeassistant/home-assistant:stable
````

I did a lot of configuration and happily started using it but when I restarted docker everything was gone. I should have tested it before but I wasted a lot of time this way. I assumed that the /config folder would include all configuration of Home Assistant and that after a restart Home-Assistant would pick it up again. I'm not sure what went wrong here. Even after Removing the docker container and pulling the latest image, pointing it to the existing config I expect it to at least detect my previous configuration and not reset to default. I would like some help and I suggest we update the Docker documentation to be more clear about how to run it in a more solid way.

## Environment

The latest version, for the sake of my problem not getting worse I did not walk through the onboarding process again to check out Developer Tools > Info. But I used the latest docker version with the latest docker image on Ubuntu 18.04.4 LTS (bionic).

## Additional information
Unfortunately I did not back-up my `configuration.yaml` which contained most of my custom work, along with all the custom lovelace things I've lost.

**Comment by slamp** [comment]
The configuration you made thru the UI should be in 
/media/someMountedDisk/homeassistant/.storage

**Comment by frenck** [comment]
I don't see an issue with your Docker command. Maybe your issues is caused by something else system related?
