### ISSUE TITLE
Brunt Blind Engine document information

### ISSUE THREAD

**Issue by oneseventhree** [home-assistant/home-assistant.github.io#13200]
-->
## The problem

In the document: https://www.home-assistant.io/integrations/brunt/
It says "BRUNT_USERNAME" I tested this with my username and it DOES NOT work. I then used my email address and it worked. 

I think the document should say "BRUNT_USERNAME_OR_EMAIL_ADDRESS" or just "BRUNT_EMAIL_ADDRESS"

and this changed as well:
**username
(string)(Required)
Account username of your Brunt app**

As username doesn't work. 

## Environment

- Home Assistant Core release with the issue: 0.108.9
- Last working Home Assistant Core release (if known): N/A
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant
- Integration causing this issue: Brunt
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/brunt/

## Problem-relevant `configuration.yaml`

N/A

## Traceback/Error logs

N/A

## Additional information

N/A

**Comment by frenck** [comment]
Thanks for reporting an issue @oneseventhree!

On all pages, there is a link that says: "Edit this page on GitHub" which allows you to edit the page you see! Help is always greatly appreciated 👍
