### ISSUE TITLE
Update Lovelace Docs Page with a new YT Video

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/home-assistant.github.io#13208]
https://www.home-assistant.io/lovelace/
https://youtu.be/XY3R0xI45wA

Current Video is outdated

New Video should include talk about the HA managed Dashboard, Taking control of your dashboard, creating a card, editing a card, editing views, etc

**Comment by zsarnett** [comment]
Bye bot

**Comment by frenck** [comment]
I think we should remove the video. We can't keep up and non of the core members working on these parts do anything with video.

I feel like this is a never-ending open issue (or, a recurring one).

**Comment by zsarnett** [comment]
100% agree. I had started working on a guided tour but haven't visited it in a while. But I think it's the best option
