### ISSUE TITLE
Add Card Editor to Lovelace Card Documentation

### ISSUE THREAD

**Issue by zsarnett** [home-assistant/home-assistant.github.io#13206]
Right now the Card Documentation is all about YAML. While important this is not the only way to set up a card. We should have an Editor and YAML configuration sections.

This requires new images of Card Editors, new descriptions for editors and sectioning off Editor vs YAML

Editor Section
We should show the options in the card editor. An overview of the options you can see and explanations of how they affect the card.

YAML Sections can be more or less clones of the current docs

**Comment by zsarnett** [comment]
Go away bot

**Comment by KTibow** [comment]
Aren't they supposed to be self-explanatory? If this happened, you should only document the confusing parts probably.

**Comment by zsarnett** [comment]
While self-explanatory, without having all of the parts documented the documentation looks incomplete

**Comment by KTibow** [comment]
I guess... Here's the example shown on https://www.home-assistant.io/lovelace/:
https://youtu.be/XY3R0xI45wA

**Comment by KTibow** [comment]
Besides, you can always ask on the [fourm](https://community.home-assistant.io/)

**Comment by zsarnett** [comment]
I am not sure I am understanding what you are asking. This is not a random request :) this is a thought out a feature we want to add. This issue is a reminder and a way to track this.

I understand each of the editors as I helped build them :)
