### ISSUE TITLE
Whereis hass

### ISSUE THREAD

**Issue by Norfilas** [home-assistant/home-assistant.github.io#1321]
Hi all,

A Raspberry pi and Home Assistant newbie here, so be gentle!

I am trying to set up a service to launch Home Assistant on startup as the Home Assistant site, and a number of people on here have managed to successfully do. however, i am falling at the first hurdle, for some reason whereis hass is not returning the path for me to validate the service information, instead i just get a blank response. See below:

```
> pi@Home-Assistant-Pi:~ $ whereis hass
> hass:
```

I have tried rebooting, but to no avail. I am sure this is something simple that i don't quite understand yet, so any help is appreciated.

**Comment by arsaboo** [comment]
How did you install HA? If your HA is installed, you can go to http://RASPBERRY_PI_IP:8123 and the HA path is displayed under the Info (i) under developer tools.

It is easier to get such queries resolved in the [community forums](https://community.home-assistant.io/) or [Gitter channel](https://gitter.im/home-assistant/home-assistant)

**Comment by Landrash** [comment]
As @arsaboo said :)
