### ISSUE TITLE
Rename of the iOS section in Docs

### ISSUE THREAD

**Issue by djryan012** [home-assistant/home-assistant.github.io#13219]
With the integration of the Official android App the iOS section is now labelled incorrectly. The link takes you to a section that address both operating systems. It should be labled and branded for both OS. Maybe "Companion APP" with a mobile icon instead.

[https://www.home-assistant.io/docs/](https://www.home-assistant.io/docs/)

**Comment by frenck** [comment]
Those are actually referring to the old iOS integrations... but yeah you are right

**Comment by frankyhun** [comment]
i can do that, and file as a pull request

**Comment by KTibow** [comment]
Time to close?
As **frenck** said, it has been taken care of.
