### ISSUE TITLE
deCONZ daylight sensor missing, because it was intentionally disabled

### ISSUE THREAD

**Issue by mlangenberg** [home-assistant/home-assistant.github.io#13270]
I just spent a good hour figuring out why the deCONZ `sensor.daylight` entity was missing. I just knew I had seen working it before. 

In the end, I found that the daylight sensor has been disabled since January with the following PR (home-assistant/core#30625).

I don't understand why this decision was made, but the documentation should be updated accordingly: https://github.com/home-assistant/home-assistant.io/blob/next/source/_integrations/deconz.markdown#deconz-daylight-sensor

> **deCONZ Daylight Sensor**
> The deCONZ Daylight sensor is a special sensor built into the deCONZ software since version 2.05.12. It is represented in Home Assistant as a sensor called sensor.daylight. 

- What alternatives are included in HA for this sensor, when wanting to use the `golden_hour_2` state?
- What if I want to keep using this (virtual) sensor? Can I enable it again?

**Comment by frenck** [comment]
@mlangenberg If you go to your device in Home Assistant, you can enable it again (it shows an X device disabled link).

Every entity (that has a unique ID) can be enabled and disabled. Common ones are enabled by default and the more exotic or confusing ones are disabled by default.

It is up to you what you change on that.

**Comment by mlangenberg** [comment]
Thanks! Eventually I found the place where it was disabled and could enable it back again.
