### ISSUE TITLE
Document (mqtt) device triggers

### ISSUE THREAD

**Issue by max-te** [home-assistant/home-assistant.github.io#13272]
[source/_docs/automation/trigger.markdown](https://github.com/home-assistant/home-assistant.io/blob/next/source/_docs/automation/trigger.markdown) has zero documentation on `platform: device`-triggers. #12200 documents how autodiscovery for mqtt device triggers works and recommends to user them for stateless devices, but says not how to configure automations to react on them.

Currently the only sensible way to configure these seems to be via the Automations UI and if you want to manage your automations-yaml yourself, you can copy-and-paste the trigger from the ui. Is that correct or am I missing something? The documentation should address this.
There should also probably be links to and from `source/_integrations/device_trigger.mqtt.markdown`.

**Comment by frenck** [comment]
Feel free to jump in and help out! 👍

**Comment by max-te** [comment]
I'd be happy to help, but I am still confused myself. I came here from [the zigbee2mqtt documentation](https://www.zigbee2mqtt.io/integration/home_assistant.html#responding-to-button-clicks), which just shows an example config entry without commentary on where `device_id` and `discovery_id` come from.

I also just read [the blog post about the future of YAML](https://www.home-assistant.io/blog/2020/04/14/the-future-of-yaml/) and it leaves me even more confused: Are these triggers only intended to be set up via the web UI? If yes, is the documentation in `source/_docs/automation/trigger.markdown` purely user-facing? How much of this documentation belongs into the user docs and how much into the developer docs?

I guess, for the moment I can just write a short note in `source/_docs/automation/trigger.markdown`, but it feels like there's an architecture decision to be made here.

**Comment by jbouwh** [comment]
I think this is stale, if it is not, please let it now or open a new issue.
