### ISSUE TITLE
Media control card TTS box ignores TTS settings in configuration.yaml

### ISSUE THREAD

**Issue by jonnomolenaar** [home-assistant/home-assistant.github.io#13274]
## The problem

If you change things in the configuration.yaml for tts, the Lovelace media control card doesn't change with for example the language or the service you put in. But always uses Google translate in English.

**Comment by frenck** [comment]
This is the issue tracker for our website. If you have problems with the Home Assistant Core, please report it here:

<https://github.com/home-assistant/core>

**Comment by masdak** [comment]
how to chance the language to pt-br?
