### ISSUE TITLE
Unable to select light color

### ISSUE THREAD

**Issue by djiesr** [home-assistant/home-assistant.github.io#13339]
Since December, it is no longer possible to select the color of the Tuya lights. However, before I could do it without problem. The way of solving the problem on the community does not correct it well. I tested the November 2019 version of tuya and the lights become unavailable. the January version, the lights are available again but without the choice of colors. I imagine there has been an API update. Please correct the problem.

**Comment by frenck** [comment]
@djiesr Thanks for opening up an issue, however, this is the issue tracker for our website.

In case you have issues with an Home Assistant Core integration, please open up an issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
