### ISSUE TITLE
Configure Brother integration through configuration.yaml

### ISSUE THREAD

**Issue by HiranChaudhuri** [home-assistant/home-assistant.github.io#13358]
## The problem
I wa very happy to find HomeAssistant can already work with my brother printers. Following the advice on https://www.home-assistant.io/integrations/brother/ I was also able to get the integration up and running. However I did not see HomeAssistant to store values to it's configuration file.
As I run HomeAssistant inside Docker any temporary change will be forgotten, and I have to add the correct information to my configuration.yaml file so it is available after the next provisioning.
Unfortunately the documentation does not say how, and configuration via UI does not give any hint for the configuration file.

## Solution
The documentation should be extended.

**Comment by frenck** [comment]
`configuration.yaml` is not the storage, the configuration folder is. This is documented as well.

Things managed via the UI is stored in the configuration folder in the `.storage` directory. However, since we document to mount the configuration folder in your Docker container, this is automatically handled.

**Comment by HiranChaudhuri** [comment]
How in that folder would the configuration be stored?
Could you please guide me to where it s documented?

**Comment by HiranChaudhuri** [comment]
Ah, so now I found the 'hidden' folder and inside the files core.config_entries and core.entity_registry, both of which seem to contain stuff about the brother platform.

I am not sure where to find documentation that mentions .settings or the format for those files. The search function on https://www.home-assistant.io/docs/ seems not to help either.

**Comment by frenck** [comment]
It is not meant to be edited as the user.

**Comment by HiranChaudhuri** [comment]
So the brother integration can only be configured through the UI, and the files are kind of kept secret from the user as they are not meant for manual editing. That sounds like security by obscurity.

Other than that I am getting confused that now I setup some integrations (e.g. https://www.home-assistant.io/integrations/hue/) via configuration.yaml and some via UI (e.g. https://www.home-assistant.io/integrations/brother/). As this will impact the availability of the entities in HomeAssistant it also impacts whether my scripts will work or not.

So far I was happy to deploy them to Homeassistant from my version control. It seems I would have to change the whole process so that I configure integration and scripts all via the UI, and then eventually backup the configuration folder?

**Comment by frenck** [comment]
It is an open-source application. All of Home Assistant is here in GitHub... I think obscurity is the wrong term to use.

An integration that connects with devices or services will move away from YAML configuration. More information on that see: <https://www.home-assistant.io/blog/2020/04/14/the-future-of-yaml/>

Or read the architectural decision made on this in ADR-0010: <https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md>

**Comment by HiranChaudhuri** [comment]
Thank you frenck, these documents clarified a lot.

So I cannot even ask for the brother integration to be configured via YAML as this is exactly discouraged. And I should rather use the UI to configure the stuff I need, then backup/version control the .storage folder.

With that I am happy to close the issue. :-)
