### ISSUE TITLE
0.109.6 Islamic Prayer sensor broken

### ISSUE THREAD

**Issue by talondnb** [home-assistant/home-assistant.github.io#13361]
> This seems to have broken the times for me.
> 
> ![Screen Shot 2020-05-08 at 22 19 28](https://user-images.githubusercontent.com/3942363/81414738-fffc0c00-9179-11ea-9a51-39f33aaea112.png)
> 
> I've tried removing integration and re-adding and also tried changing the calculation method, but still shows the wrong times.
> 
> edit: rolling back to 0.109.5 has fixed this for me. 
> 
> ![Screen Shot 2020-05-08 at 22 40 30](https://user-images.githubusercontent.com/3942363/81416866-ef00ca00-917c-11ea-9ccc-c092b7837151.png)
> 

Please submit an issue for tracking. And mention the sensor state value (timestamp)

_Originally posted by @engrbm87 in https://github.com/home-assistant/core/pull/35243#issuecomment-625859863_

Timestamp example:

sensor.fajr_prayer	2020-05-08T21:30:00+00:00

As mentioned above, rolling back to 0.109.5 reverts the issue and works again. All time/date sensors are running on my setup.

**Comment by talondnb** [comment]
Ok this seems to be an issue with my value_templates sensor I have setup previously to display the time.

example:

        value_template: "{{ (states('sensor.fajr_prayer').split('T')[1].split(':')[0]) + ':' + (states('sensor.fajr_prayer').split('T')[1].split(':')[1])  }}"


I've since changed the lovelace displayed values using the format: time parameter and they're showing fine.

**Comment by webhostsg** [comment]
Doesn't really solve my issue, not having issues cards...  I'm running the following code to check against time to trigger automation:
```
{{ as_timestamp(states("sensor.date_time_iso")) == as_timestamp(states("sensor.fajr_prayer"))-600}}
```

I have to offset the time due to the timing is so off no matter if I set to MWL or Karachi, etc..

**Comment by engrbm87** [comment]
try this `{{ as_timestamp(as_timestamp(states.sensor.fajr_prayer.state) | timestamp_local) - 600 }}`

**Comment by webhostsg** [comment]
> try this `{{ as_timestamp(as_timestamp(states.sensor.fajr_prayer.state) | timestamp_local) - 600 }}`

Ok thank you, that work great! 

Changed from 
```
{{ as_timestamp(states("sensor.date_time_iso")) == as_timestamp(states("sensor.fajr_prayer"))-600}}
```
to 

```
{{ as_timestamp(states("sensor.date_time_iso")) == as_timestamp(as_timestamp(states.sensor.fajr_prayer.state) | timestamp_local) - 600}}
```

**Comment by naumz** [comment]
My Lovelace UI after the update also displays the prayer times in UTC in the overview page (I am on Pacific time). This is the default sensor reading as I haven't configured my UI in any way. Is there a way to fix this without taking control of the Lovelace UI? The date time ISO sensor displays time in local timezone.

![lovelace-overview-fajr-time-in-utc](https://user-images.githubusercontent.com/4783847/81785619-5a1b0b00-94b3-11ea-97de-5c42c54b9ef9.png)

![lovelace-UI-datetime-sensor](https://user-images.githubusercontent.com/4783847/81789654-26db7a80-94b9-11ea-8115-ce8cd08d29ca.png)

**Comment by aazimh** [comment]
Same here - prayer times are now in UTC instead of local time. I use the sensors to trigger some automations in NodeRED so can obviously add in the offset there but would be good to know if this can be fixed at source.

**Comment by talondnb** [comment]
Reopened this as I don’t believe our default sensors for this integration should be presenting UTC and should really be presenting local time.

**Comment by webhostsg** [comment]
> Same here - prayer times are now in UTC instead of local time. I use the sensors to trigger some automations in NodeRED so can obviously add in the offset there but would be good to know if this can be fixed at source.

I use NodeRed too, i use the Get Template node to trigger with time offset using this code:
```
{{ as_timestamp(states("sensor.date_time_iso")) == as_timestamp(as_timestamp(states.sensor.fajr_prayer.state) | timestamp_local) - 600}}

```
![Screenshot 2020-05-16 at 6 11 27 AM](https://user-images.githubusercontent.com/59085206/82100655-d2e0c800-973c-11ea-8ff6-76a7d0376301.png)

![Screenshot 2020-05-16 at 6 17 37 AM](https://user-images.githubusercontent.com/59085206/82100719-06235700-973d-11ea-9416-787235aebcd9.png)

and a switch node after that:

![Screenshot 2020-05-16 at 6 18 53 AM](https://user-images.githubusercontent.com/59085206/82100754-2521e900-973d-11ea-9bb1-0153fb18b518.png)

**Comment by naumz** [comment]
I actually don't need to convert with timestamp_local. In my case, this works.
`{{ as_timestamp(states('sensor.date_time_iso')) == as_timestamp(states('sensor.isha_prayer')) }}`

But the UTC view for the integration's sensor is definitely not ideal.

**Comment by frenck** [comment]
Hi guys, this issue is misplaced.

This is the issue tracker for our documentation/website, not our core Home Assistant application.

Please file an issue with the Home Assistant Core here: <http://github.com/home-assistant/core/issues>

Thanks! 👍

**Comment by naumz** [comment]
created new issue here: https://github.com/home-assistant/core/issues/35747
