### ISSUE TITLE
Missing details/instructions for  qcow2 image

### ISSUE THREAD

**Issue by cfergeau** [home-assistant/home-assistant.github.io#13374]
## The problem

I've been trying to use https://github.com/home-assistant/operating-system/releases/download/4.6/hassos_ova-4.6.qcow2.gz in a VM, and I've had a hard time with it. I was creating a new VM in virt-manager (which is using libvirt/qemu under the hood), and the boot process was hanging at "Booting from hard disk", so basically it was failing to boot the image. I've tried converting the vmdk, using the NUC .img, ... and all of these had the same behaviour.
After a few hours, I realized the architecture they were meant for was not specified on the download page, but I confirmed with guestfish that this was an x86_64 image, so this was not the reason for my issues.
It's only after reading through discord's logs that something made me realize they were *EFI* images. Since this is not the default in virt-manager created VMs, this is why the boot was failing.
Having a mention that these images are x86_64+EFI on the download page would be most helpful :)

**Comment by cfergeau** [comment]
Looking again at https://www.home-assistant.io/hassio/installation/ UEFI is actually mentioned a bit after the download links. I found this in the comments of https://www.home-assistant.io/blog/2020/05/09/deprecating-home-assistant-supervised-on-generic-linux/ , which shows I'm not the only one.
Maybe "As a virtual appliance:" could be changed to "As a virtual appliance (x86_64/UEFI)"?

**Comment by cfergeau** [comment]
or even encode this in the filename, `hassos_x86_64_uefi-4.6.qcow2.gz`

**Comment by fabaff** [comment]
I not able to run the qcow2 images as well.

Upstream bug report: https://github.com/home-assistant/operating-system/issues/665

**Comment by fabaff** [comment]
It's mentioned at least in this guide: https://github.com/home-assistant/operating-system/blob/37639fc3ff8ca0c3097192a5723e9a1856121129/Documentation/getting_started_development.md

Not easy to find. Guess that it wouldn't harm to add it to the installation page.

**Comment by frenck** [comment]
It is being worked on as announced in the latest blog post.
