### ISSUE TITLE
Consider adding GoControl to Z-Wave Controllers list

### ISSUE THREAD

**Issue by philfreo** [home-assistant/home-assistant.github.io#13376]
Consider adding "GoControl CECOMINOD016164 HUSBZB-1 USB Hub" ([Amazon link](https://www.amazon.com/GoControl-CECOMINOD016164-HUSBZB-1-USB-Hub/dp/B01GJ826F8/)) to https://github.com/home-assistant/home-assistant.io/blob/next/source/_docs/z-wave/controllers.markdown

I haven't tried it, but it seemed like one of the best reviewed ones on Amazon, is Z-Wave Plus, and several reviewers mention using Home Assistant with it.

**Comment by frenck** [comment]
Feel free to add it.

**Comment by bradsk88** [comment]
Subscribing to this as I have one of these coming in the mail and will try to document my experience with it.

**Comment by philfreo** [comment]
I got mine setup. I'm new to Home Assistant but I got it working and it seems to work just fine, so I opened a PR (#13481).
