### ISSUE TITLE
"Using Home Assistant the ARTIK Cloud" link invalid

### ISSUE THREAD

**Issue by JeffResc** [home-assistant/home-assistant.github.io#13509]
## The problem
The "Using Home Assistant the ARTIK Cloud" link in [the help index page](https://github.com/home-assistant/home-assistant.io/blob/249ea2db071e8328fc4ef4cc6a2d22a92b4a8d64/source/help/index.markdown) is invalid. This service has been shut down, but since it is in the "Media Coverage" section and not for actual documentation purposes, it may want to be left there.

## Options
- Remove the link as the link is invalid and the service is shutdown.
- Keep the link as it is for "Media Coverage" and not actual documentation purposes, and replace it with something like [the Archive.org archive of the page](https://web.archive.org/web/20191028191303/https://developer.artik.io/documentation/developer-guide/wireless-iot/hass.html).

If someone part of the Home Assistant project development team can point out which option would be best, I'd be happy to submit a pull request with the desired change.

**Comment by fabaff** [comment]
Let's remove the link.
