### ISSUE TITLE
Xiaomi Gateway Alarm - ha_release 0.110 shows as 0.11

### ISSUE THREAD

**Issue by vorostamas** [home-assistant/home-assistant.github.io#13528]
## The problem

In [alarm_control_panel.xiaomi_miio.markdown](https://github.com/home-assistant/home-assistant.io/blob/next/source/_integrations/alarm_control_panel.xiaomi_miio.markdown) the 
_ha_release_ is set to **0.11** however it should be **0.110**.
Also, the logo is broken.

![image](https://user-images.githubusercontent.com/9920416/82467019-6e699400-9ac1-11ea-9bc3-373418fbda2d.png)

Note: The raw file shows the right version: https://raw.githubusercontent.com/home-assistant/home-assistant.io/next/source/_integrations/alarm_control_panel.xiaomi_miio.markdown

**Comment by seanvictory** [comment]
Fixed in this[ Pull Request ](https://github.com/home-assistant/home-assistant.io/pull/13534)
