### ISSUE TITLE
Can I assist? CentOS page needs udpated for CentOS 8.

### ISSUE THREAD

**Issue by pghpete** [home-assistant/home-assistant.github.io#13559]
## Can I assist? Centos page needs udpated for CentOS 8.

The current page is out of date, has a broken link, etc. I would love to help edit this page to work with CentOS 7 and CentOS 8. Is this something you folks would be interested in?

Regards,
Pete

**Comment by frenck** [comment]
The CentOS guide is a community provided/supported guide.
We are currently in the process of removing these to an alternative location.

After this has been moved, help updating would be appreciated. 👍
