### ISSUE TITLE
Dublin Bus test not working

### ISSUE THREAD

**Issue by KTibow** [home-assistant/home-assistant.github.io#13568]
## The problem

It says that you can do this to check if the number is correct:  
https://github.com/home-assistant/home-assistant.io/blob/edd73f266815a24455e6cc7dafd9183090889fe5/source/_integrations/dublin_bus_transport.markdown#L13-L15  
I was testing that URL out, but I got this error message in my browser:
```
data.dublinked.ie took too long to respond.
```
Should the docs be updated? Is there a way to fix this? The GUI still works.

**Comment by frenck** [comment]
Hi there @KTibow!

This is the issue tracker for our documentation/website.

Considering your error message, I would say that that is an issue with the Home Assistant integration.

Could you please raise an issue at the core repository?

<https://github.com/home-assistant/core/issues>

Thanks! 👍

**Comment by KTibow** [comment]
@frenck Does the in-browser method do the same thing as the integration? To clarify, this is in a browser going to the specified URL, not Home Assistant.
