### ISSUE TITLE
Withings integration error

### ISSUE THREAD

**Issue by gpend** [home-assistant/home-assistant.github.io#13587]
## The problem
I am attempting to set up withing integration but I am getting an error. 

In the documentation it mentions:
Note: If you get a browser error saying the site is inaccessible, you can modify the http://domain portion of the URL to something you know is accessible, locally or publicly. For example, http://localhost:8123. This occurs when the base URL provided by Home Assistant to Withings is not accessible to the outside world. Changing the domain will not affect how data is synchronized.

however, the error I am getting is for a mismatch. I tried setting the URL to localhost as suggested but I get the same error:

{"errors":[{"message":"redirect_uri_mismatch: The redirect URI provided is missing or does not match partner callback url"}]}

**Comment by julien-vu** [comment]
Fixed in PR #36348 in the core, will be available in the 0.111 of the core part.
