### ISSUE TITLE
Atom feed broken

### ISSUE THREAD

**Issue by Crocmagnon** [home-assistant/home-assistant.github.io#13614]
The issue is similar to the one described in : https://github.com/home-assistant/home-assistant.io/issues/9861

It seems that the atom feed (https://www.home-assistant.io/atom.xml) returns HTML and not XML.

**Comment by Crocmagnon** [comment]
Miniflux tells me that it’s `Unable to parse Atom feed: "expected element type <feed> but have <html>"`

**Comment by frenck** [comment]
Thanks @Crocmagnon!

Fixed it, can take a moment before it becomes visible (because of caching).
