### ISSUE TITLE
Sene not woning ui and automation

### ISSUE THREAD

**Issue by magaraves** [home-assistant/home-assistant.github.io#13679]
I wanted to create a completly new sene from the ui in the config penal. I have version 0.110.5 and hassos 3.13. 

But when I create a new sene it will be created I van see that in the sene.yaml file but it doesn't display in the gui.

Hope someone can help me
See sceenshot below 

![Screenshot_20200606-130503](https://user-images.githubusercontent.com/35001947/83942705-6bc3aa00-a7f6-11ea-9610-460088b890d6.jpg)
![Screenshot_20200606-130449](https://user-images.githubusercontent.com/35001947/83942706-6cf4d700-a7f6-11ea-9854-60183471d4c9.jpg)

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
