### ISSUE TITLE
Document how to enable SSH access

### ISSUE THREAD

**Issue by lhanson** [home-assistant/home-assistant.github.io#13714]
## The problem
I've got a new installation of Home Assistant running that I'd like to SSH into. The very first sentence of [Home Assistant via the command line](https://www.home-assistant.io/hassio/commandline/) is "On the SSH command line [...]", but when I try to SSH to the machine I get "port 22: Connection refused".

Is there something I need to do to enable SSH access? If so, that documentation should be linked here.

**Comment by frenck** [comment]
You can install an SSH add-on to access that.

**Comment by lhanson** [comment]
I know that now, but it would be nice if the documentation on the website were self-contained and didn't rely on users scouring the forums or opening issues. Would it make sense for this page to explicitly mention that dependency and how to install it?

**Comment by TomBrien** [comment]
Problem I see here is it is dependent on the installation method. We could just cover the Home Assistant case with a note that users with Core or other installs should take appropriate steps to enable

**Comment by lhanson** [comment]
> We could just cover the Home Assistant case with a note that users with Core or other installs should take appropriate steps to enable

I think that would be helpful.
