### ISSUE TITLE
Raspberry Pi 4 Model B - 8GB model not supported by HassOS

### ISSUE THREAD

**Issue by alexgoldstone** [home-assistant/home-assistant.github.io#13728]
The documentation simply references **Raspberry Pi 4 Model B** however it has been confirmed that the 8GB model is not currently supported.

See: https://github.com/home-assistant/operating-system/issues/740

Suggest updating the [installation](https://www.home-assistant.io/hassio/installation/) page to note that the 8GB model is not currently supported.

**Comment by frenck** [comment]
Feel free to open up a PR to adjust this 👍
