### ISSUE TITLE
CSS issue with markdown code tags in "warning" box

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/home-assistant.github.io#13775]
## The problem
On top of this [knx binary sensor page](https://www.home-assistant.io/integrations/binary_sensor.knx), there is a blue box using the CSS class `note` in which markdown code tags are used for highlight the `knx` integration name. All is fine here.

![image](https://user-images.githubusercontent.com/114137/84764695-6e7c8700-afce-11ea-99de-0ae4a59984cf.png)

However, on the [knx entry page](https://www.home-assistant.io/integrations/knx/) the same is attempted but fails. In the yellow warning box with CSS class `note `and `warning` the highlight apparently breaks.

![image](https://user-images.githubusercontent.com/114137/84764722-776d5880-afce-11ea-9181-9385eb817b77.png)

**Comment by spacegaier** [comment]
The weird thing is, on other pages it seems to work fine, e.g. [here](https://www.home-assistant.io/integrations/luftdaten/).

**Comment by frenck** [comment]
That is not a CSS issue, the Markdown is wrong.

**Comment by spacegaier** [comment]
> 
> 
> That is not a CSS issue, the Markdown is wrong.

I had that thought for a split second whether those empty lines (that the working page has) could have anything to do with it. And my decision was a rather firm: "No" 😄
