### ISSUE TITLE
Misleading documentation on integration (Riemann sum)

### ISSUE THREAD

**Issue by valpackett** [home-assistant/home-assistant.github.io#13849]
https://www.home-assistant.io/integrations/integration/

> In case you have an appliance which produces spikey consumption (like an on/off electrical boiler) you should opt for the left method to get accurate readings. **If unit is set then unit_prefix and unit_time are ignored.**

No it's not! `unit_time` is not ignored! It matters for the calculation:

https://github.com/home-assistant/core/blob/25b093e69e9939c131f4dc83566a9571929803df/homeassistant/components/integration/sensor.py#L163

**Comment by frenck** [comment]
@myfreeweb Feel free to open a PR to adjust the documentation. Thanks already! 👍
