### ISSUE TITLE
Google Assistant - Manual setup instructions are not up to date

### ISSUE THREAD

**Issue by Segelfeldt** [home-assistant/home-assistant.github.io#13898]
## The problem

Trying to manually set up Goole Assistant integration and following the [Manual Setup steps](https://www.home-assistant.io/integrations/google_assistant/#manual-setup) and noticed a few issues

1. Under Account linking i should pick Linking type and select OAuth and Authorization Code. This option is not avaiable
2. There is no Test button in the Develop tab

Information that could be more clear
1. What is my project_id? I think i can find it in my url, https://console.actions.google.com/u/0/project/<project_id>/overview

I have tried to follow the instructions, and i did manage to complete the process and get the integration work also with the "sync device" command.

## Environment

- Home Assistant Core release with the issue: 
- Last working Home Assistant Core release (if known): N/A
- Operating environment (OS/Container/Supervised/Core): Core running in Docker on Synology
- Integration causing this issue: Google Assistant
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/google_assistant

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment]
Transferred the issue to the documentation issue tracker.

Feel free to help out and open a PR to  adjust/improve it 👍
