### ISSUE TITLE
Add Iot Class to the Simplisafe integration documentation

### ISSUE THREAD

**Issue by mike1237** [home-assistant/home-assistant.github.io#13933]
## The problem

Add Iot Class to the Simplisafe integration documentation.
It is missing, but included for Abode integration: e.g. Cloud Push.
https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/simplisafe.markdown

**Comment by frenck** [comment]
Feel free to open up a PR to add it! Thanks already 👍

**Comment by mike1237** [comment]
Unfortunately, I'm not sure what class it would be considered! Not sure if this is Cloud Push or Cloud Polling.

The code for the integration appears to use a websocket, so I suspect Cloud Push, but I'm not positive.

`        for event_type in (EVENT_LOCK_LOCKED, EVENT_LOCK_UNLOCKED):
            self.websocket_events_to_listen_for.append(event_type)`

https://github.com/home-assistant/core/tree/dev/homeassistant/components/simplisafe

If anyone can confirm, I am happy to write the PR for the documentation update.

**Comment by frenck** [comment]
<https://github.com/home-assistant/core/blob/dev/homeassistant/components/simplisafe/config_flow.py#L18>
