### ISSUE TITLE
Advanced Mode

### ISSUE THREAD

**Issue by austinmroczek** [home-assistant/home-assistant.github.io#13961]
## The problem

Advanced Mode for the user interface is not well documented.  I had to dig deep into Discord to find it while trying to figure out why MQTT switches were not available in the scene editor.

It's not mentioned at https://www.home-assistant.io/getting-started/configuration/ or https://www.home-assistant.io/cookbook/#user-interface

It's briefly mentioned but not explained at https://www.home-assistant.io/docs/scene/editor/

The https://www.home-assistant.io/docs/configuration/customizing-devices page mentions it and points to https://www.home-assistant.io/docs/authentication/#your-account-profile which does not mention it.

The best place I could find, which was the last thing found using the documentation search function was https://www.home-assistant.io/integrations/withings/#step-2---configure-home-assistant

I'll to put together a PR, but would like to discuss the most logical place to put the information.

**Comment by austinmroczek** [comment]
The best description seems to be https://www.home-assistant.io/blog/2019/07/17/release-96/#advanced-mode but I'd think a blog post is not the long term solution.

**Comment by SeanPM5** [comment]
Working on some other stuff at the moment but I plan to tackle this one afterwards.

I know pretty much everything the advanced mode toggle changes, the main challenge would be figuring out where a page like this would fit into the current site structure.

**Comment by austinmroczek** [comment]
For what it's worth, my recommendation would be:

a) Add a new section near the top of https://www.home-assistant.io/docs/configuration/ that says there are two basic ways to configure the system, either UI or YAML.  Link to the existing YAML page and a new page for UI.

b) Add a "UI config" page under https://www.home-assistant.io/docs/configuration/ Include an Advanced Mode section as discussed above.
