### ISSUE TITLE
venv installation guide issue

### ISSUE THREAD

**Issue by Kreuger** [home-assistant/home-assistant.github.io#14043]
Hey guys. I'm new to all of this. I have installed home assistant in a virtual environment following the guide on the site. However when I try to use 
> hass --open-ui

it tells me that hass is not found.

**Comment by frenck** [comment]
Could you please point me to the exact location/URL of the guide used?

**Comment by Kreuger** [comment]
It won't let me use the editor to add the link properly some I'll just post it.

https://www.home-assistant.io/docs/installation/virtualenv/


Edit: I got it to work. I think I somehow missed the step for activating the environment.
