### ISSUE TITLE
Documentation's new theme may be causing errors.

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/home-assistant.github.io#14040]
## The problem

The default `payload_on` and `payload_off` for an MQTT Binary Sensor are _uppercase_ `ON` and `OFF`. However, the new documentation theme appears to be forcing certain text into _lowercase_. As a result, it now shows that the **default states** are `on` and `off`.

![Screenshot from 2020-07-19 11-37-17](https://user-images.githubusercontent.com/44732909/87880108-fa624400-c9bc-11ea-8b35-7483723c864a.png)

So is the theme causing documentation errors or is there an upcoming breaking change to re-define the default payload values?

NOTE
The documentation may contain other instances of text forced to lowercase. I have mentioned the example of MQTT Binary Sensor because that's the first instance of the error I noticed.

**Comment by glmnet** [comment]
Also https://github.com/home-assistant/core/issues/39072#issuecomment-681779503

**Comment by springstan** [comment]
This issue affects various integrations:

- MQTT
  - binary_sensor
  - climate
  - fan
  - light
  - switch
- command_line
  - binary_sensor 
...
