### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by Mattat01** [home-assistant/home-assistant.github.io#14190]
## The problem
Hi, they went and changed the Adelaide (maybe other) station ID. You have it as an example on the documentaiton page as IDS60801.94675 but it is now IDS60901.94648 and the old number does not work anymore.
Thanks

**Comment by frenck** [comment]
Hi @Mattat01 You issue report is missing a bit of context, we have around over 2000 pages in our documentation. I have no idea what example you are talking about.

Could you clarify? Or, even better, click the "Edit on GitHub" link that is on top of each page, allowing you to suggest an edit for the page.

**Comment by Mattat01** [comment]
Sorry, it was alte and I didn't realise I was creating an issue on the full git, I thought it was specific to the sensor I was looking at. I also couldn't work out how to edit at that time of night, but I have now created a pull request on https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/bom.markdown to correct it.

Thanks,
Matthew
