### ISSUE TITLE
Improve vallox documention

### ISSUE THREAD

**Issue by spaetz** [home-assistant/home-assistant.github.io#14212]
The vallox integration documentation is great and contains a snippet that uses an input_select to display the ventilation profiles. It also contains an automation to actually set the ventilation profile when one selects a profile. What it does NOT do however, is to update the input_select when some external event or entity changes the vallox profile.
This could be a mechanical control switch at the ventilation unit or the vallox-internal web-interface.

I propose a merge request to update the docs to add the following automation snippet that updates the input select when the profile has been changed by external forces. It boils down to:

-`alias: Change vallox input_select
  description: Update vallox input_select when an external event changes the profile
  trigger:
  - entity_id: sensor.luftung_current_profile
    platform: state
  action:
  - data_template:
      entity_id: input_select.ventilation_profile
      option: '{{ states(''sensor.vallox_current_profile'') }}'
    service: input_select.select_option
```

**Comment by frenck** [comment]
You don't have to create an issue to create a PR. Instead, create a PR directly. Thanks 👍
