### ISSUE TITLE
I can't make any sense of the configuration help pages

### ISSUE THREAD

**Issue by peterspencer10** [home-assistant/home-assistant.github.io#14231]
Configuration pages in the help section don't seem to make any sense.

I'm looking at the getting started pages in the configurations, specifically the Adding devices page right now, and I can't find anything like that in the configuration.yaml file in the file editor. Where are these devices listed? I know that they're in the UI, but is it an either/or situation? I also don't see any basic information in my configuration.yaml. 

A direct answer would help me, but something of an explainer would help all the other newbies in the world.

Thanks for all your good work.

**Comment by frenck** [comment]
Hi there @peterspencer10!

Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

Considering your question, I would highly recommend trying our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

The latter is especially helpful for getting quick feedback and doing follow up questions. I'm sure a lot of people are around to help you out, getting your forward.

Thanks! 👍

**Comment by peterspencer10** [comment]
Hey Frenck,

The point really is that something as basic as where to find the information discussed on the the pages in question should really be presented somewhere on said page. I really am getting tired of having to search for every single little bit of information I need. I thought that the "Getting Started" section would actually help me - you know - get started. I wish there was an idiot's guide somewhere, because I sure feel like one!

Thanks for your quick response. I guess I'm going to Discord.
