### ISSUE TITLE
Cannot copy name of configuration variables without pain

### ISSUE THREAD

**Issue by Zocker1999NET** [home-assistant/home-assistant.github.io#14414]
## The problem

This may be multiple different issues, but both preventing the same action. I reproduced both errors in Firefox 80.0 and Chromium 83.0.4103.116 (if not stated otherwise) on Debian Unstable (using X11 as backend) without page modifying add-ons. I found the issues originally on https://www.home-assistant.io/lovelace/history-graph/, but could reproduce the issue on multiple other pages and due to the consistent design, this may happen on all pages.

It is about the theming of the "configuration variables" / "options for entities" / ... tables. There I tried to first select a name of one variable and then copy the variable / option name. I failed to select the name due to multiple small design flaws (as I think off):
1. Every name has a anchor icon left of it when hovering over the name (which is great per se), but it's clickable area does overlap a large part of the name (e.g. the first three characters of `type`) preventing me to double-click the name to let the browser automatically only select the word I wish to select.
2. Also due to the anchor, it is not possible to begin selecting the word from the left to the right using the mouse.
3. (*Firefox only*) Selecting the word from the right to the left also seems impossible also due to the anchor overlapping a significant part of the name. Chromium seems to continue selecting texts below other elements (z-axis), but Firefox doesn't, maybe thinking that the text is not visible to the user so it does not need to be selectable.
4. When trying to prevent clicking on the anchor works (e.g. on longer names like `hours_to_show`) and using a double-click, both browsers always (in my testcases) select the name **and** its type, see:
  ![Screenshot_20200906_195215](https://user-images.githubusercontent.com/1645646/92331962-84a05d80-f07a-11ea-801f-c037a56dc748.png)
  On other examples it may also include the `REQUIRED` marker:
  ![image](https://user-images.githubusercontent.com/1645646/92332370-cc74b400-f07d-11ea-8540-e5c9c4640d9b.png)
  A triple-click does select the whole "line" if not already done, which is expected:
  ![image](https://user-images.githubusercontent.com/1645646/92332121-8e769080-f07b-11ea-9d9e-8e96a5b08faa.png)
  This does happen because the website uses a padding to separate these words and so does not separate these words in a logical way like when using a common whitespace character (e.g. ` `), a grid, a flexbox, or using `display: inline-block` on the span. Then the browsers can detect that each item (name, type, …) are each a single entity.

It would be great if these could be fixed to improve the user experience while using the documentation.

**Comment by Zocker1999NET** [comment]
@frenck Thanks for fixing the selection bug (number 4), however the other problems (number 1-3) still exist and do prevent double-clicking in Firefox & Chrome on shorter names like "title" or "type" or at least at the beginning of longer names. Could the issue be reopened?

**Comment by frenck** [comment]
So, here is a general rule of thumb when reporting issues on any GitHub repository. Never stack them.

Edit: fixed the overlap, PR open.
