### ISSUE TITLE
Duplicate entry for Dark sky

### ISSUE THREAD

**Issue by yuvalabou** [home-assistant/home-assistant.github.io#14449]
## The problem

It seems that we have two darksky docs in the site.

![Annotation 2020-09-10 074538](https://user-images.githubusercontent.com/3170485/92682582-5b612500-f339-11ea-8659-ec689cbdcaa8.png)

https://www.home-assistant.io/integrations/darksky/
https://www.home-assistant.io/integrations/weather.darksky/

Is it intended?

**Comment by frenck** [comment]
Yes, one integration provides Dark Sky data as a weather entity, the other provides sensor entities.
