### ISSUE TITLE
Dyson Integration not working

### ISSUE THREAD

**Issue by roycegerikchua** [home-assistant/home-assistant.github.io#14496]
## The problem

Hello everyone, 
my dyson integration just suddenly stopped working no matter what i try, it always tell me this:

the following integrations and platforms could not be set up:

dyson
Please check your config.

however there was no change with my configurations and when i try using their app with the credentials its okay.

hoping someone can help

**Comment by frenck** [comment]
Hi there @roycegerikchua,

Thanks for opening an issue. However, this is the issue tracker for our website. If you have an issue with a Home Assistant integration, please file an issue here:

<https://github.com/home-assistant/core/issues>

For currently known/reported issues you can filter our issue tracker for Dyson as well:

<https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+dyson%22>

If you are looking for support, check out our help page for resources like our community forum or our Discord chat server:

<https://www.home-assistant.io/help>

Thanks 👍
