### ISSUE TITLE
Tuya Switches not changing state when toggle via Tuya App or manually on switch

### ISSUE THREAD

**Issue by caiosaoliveira** [home-assistant/home-assistant.github.io#14491]
Using tuya switches via HA works perfectly but when I toggle on/off directly from physical switch or Tuya app, HA don’t sync the correct state.

For example:
- Light is ON (HA shows ON)
- Toggle OFF from Tuya App (or manually), HA still shows ON

Thanks!

**Comment by frenck** [comment]
Hi there @caiosaoliveira,

Thanks for reporting an issue, however, you've reported an issue with our website. Considering the contents of your bug report, I guess you wanted to file a bug with Home Assistant itself.

Please use the core issues tracker for that:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
