### ISSUE TITLE
Kodi documentation references deprecated 'turn_on_action' and 'turn_off_action'

### ISSUE THREAD

**Issue by JeffLIrion** [home-assistant/home-assistant.github.io#14569]
## The problem

https://www.home-assistant.io/integrations/kodi/#kodi-turn-onoff-samples

The `turn_on_action` and `turn_off_action` configuration parameters are not utilized in 0.115, but they are still documented.  

On that note, a more descriptive example of how device triggers can be used to turn Kodi on/off would be helpful.  The current description simply states:

> You can customize your turn on and off actions through automations. Simply use the relevant Kodi device triggers and your automation will be called to perform the `turn_on` or `turn_off` sequence.

**Comment by ikifar2012** [comment]
what were they replaced with?

**Comment by ikifar2012** [comment]
I have put through a PR to remove them from the docs
