### ISSUE TITLE
Broadlink learningmode not working anymore after HA 0.115.2

### ISSUE THREAD

**Issue by canedje** [home-assistant/home-assistant.github.io#14585]
## The problem
After update to 0.115.2 the Broadlink learn_command is not working anymore.
HA is not waiting for the IR to learn.
It also is not creating the Broadlink file at .storage
So the send_command is also not working (Because the broadlink file in .storage is not there)

The use of the switch method is still working

It did work at 0.115

I do use NodeRED to handle this like:

```

[{"id":"c01438b8.345a08","type":"api-call-service","z":"ecdb8f1f.6c03b","name":"RM mini leer functie tv aan/uit","server":"783e002.7fe69","version":1,"debugenabled":false,"service_domain":"remote","service":"learn_command","entityId":"remote.rm_mini_remote","data":"{\"device\":\"TV\",\"command\":\"turn on off\",\"alternative\":\"true\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":370,"y":580,"wires":[["38a0ba2e.a27aa6"]]},{"id":"35bbe1f.0c3b51e","type":"inject","z":"ecdb8f1f.6c03b","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":580,"wires":[["c01438b8.345a08"]]},{"id":"94f85482.aec3d8","type":"comment","z":"ecdb8f1f.6c03b","name":"Leerfuncties voor de RM mini 3","info":"The learned codes are stored in the /configuration/.storage folder in a file called broadlink_remote_xxxxxxxxxxx_codes.json. You can open this file with a text editor and copy the codes to set up a custom switch, but beware: the files in the .storage folder should never be edited manually.","x":200,"y":540,"wires":[]},{"id":"38a0ba2e.a27aa6","type":"debug","z":"ecdb8f1f.6c03b","name":"Learn ir","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":620,"y":580,"wires":[]},{"id":"814a3dad.c0c03","type":"api-call-service","z":"ecdb8f1f.6c03b","name":"RM mini send tv aan/uit","server":"783e002.7fe69","version":1,"debugenabled":false,"service_domain":"remote","service":"send_command","entityId":"remote.rm_mini_remote","data":"{\"device\":\"TV\",\"command\":\"turn on off\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":350,"y":880,"wires":[[]]},{"id":"96cc3cda.e7f8b","type":"inject","z":"ecdb8f1f.6c03b","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":880,"wires":[["814a3dad.c0c03"]]},{"id":"5f5fab60.578724","type":"comment","z":"ecdb8f1f.6c03b","name":"uitvoer functies voor de RM mini 3","info":"The learned codes are stored in the /configuration/.storage folder in a file called broadlink_remote_xxxxxxxxxxx_codes.json. You can open this file with a text editor and copy the codes to set up a custom switch, but beware: the files in the .storage folder should never be edited manually.\n\n\nDe flows hierboven zijn de leer commandos","x":200,"y":840,"wires":[]},{"id":"783e002.7fe69","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```
Also using the methode at service in developpertools is not working

## Environment
current HA 0.115.2
It worked at HA 0.115 (I'm not sure if this problem occured at HA 0.115.1)
Running on HA supervised at a VM at a NUC under Unraid
I'm using an Broadlink RM mini 3

- Home Assistant Core release with the issue: 
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): 
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs
No error log
```txt

```

**Comment by Thunderbird2086** [comment]
[Release note](https://www.home-assistant.io/blog/2020/09/17/release-115/) already mentioned it 

>2. Discontinue broadlink.learn and broadlink.send services
>
>  remote.learn_command and remote.send_command are now registered automatically. Now you can use remote.send_command to send base64 codes.

And here is mine after invoking `remote.learn`
```
➜  config ls -l  .storage/broadlink_remote_*codes 
-rw-r--r--    1 root     root          1738 Sep 21 14:41 .storage/broadlink_remote_xxxxxxxxxxxx_codes
➜  config 
```

**Comment by dudusandi** [comment]
I have the same problem.. Crashed my broad link mini 3

**Comment by dudusandi** [comment]
Help US @felipediel

**Comment by felipediel** [comment]
Please check the on/off button in the remote entity.

**Comment by dudusandi** [comment]
Boa noite Felipe, sou de Caxias do Sul - RS, tem alguma forma de falar com você ? Vi que mudou algumas coisas no HA sobre o broadlink.

**Comment by dudusandi** [comment]
Sobre o botão esta ativo, mas mesmo assim não faz a leitura de IR

**Comment by felipediel** [comment]
Opa, beleza? Nós mudamos bastante coisa recentemente, você já leu a nova documentação?
Se não estiver funcionando posta a sua configuração e tipo de dispositivo para eu dar uma olhada.

**Comment by dudusandi** [comment]
Tranquilo e contigo. ? Pelo switch do modo antigo esta funcionando normalmente.. O que não consigo fazer é a leitura de novos códigos e salvar tudo pelo painel sem mexer no yaml... De qualquer forma bacana ver alguem aqui do Sul envolvido no hassio.. Deve ser raro no Brasil.. Você trabalha com isso ou é hobby ?

**Comment by felipediel** [comment]
Tudo certo. Sou desenvolvedor, mas tudo que envio ao Home Assistant são contribuições voluntárias.

Preciso da configuração exata ou os dados da chamada do serviço para que eu possa reproduzir o problema aqui.

**Comment by dudusandi** [comment]
![1](https://user-images.githubusercontent.com/41707380/94755653-9d471f00-036b-11eb-8e83-abbdfc3a9404.jpg)

Sem querer acabei achando o problema, onde diz entity_id tem o exemplo de remote.bedroom, no caso achei que fosse o nome da entidade que ele iria criar.. Mas na real é o nome dado ao broadlink.

Solution where it says entity_id has the example of remote.bedroom, in this case I thought it was the name of the entity that it would create. But in reality it is the name given to broadlink.

**Comment by dudusandi** [comment]
@felipediel Tu acha que o home assistant esta maduro pra comercializar ? Estava pensando em oferecer um serviço mais em conta de automação residencial.. Junto com switches Tuya que funcionam muito bem.

**Comment by dudusandi** [comment]
Estranho, tentei novamente com as mesmas informações e não grava nenhum log e também não faz leitura.

**Comment by felipediel** [comment]
Em termos de estabilidade o Home Assistant já está bem maduro. Mas se você quer trabalhar com isso, aqui vão minhas ressalvas:
1. O Home Assistant está passando por uma fase de transição. As integrações estão migrando do YAML para as entradas de configuração. Isso significa que muitas coisas vão quebrar ainda. Você terá que ajudar os seus clientes a migrarem as suas configurações frequentemente. E isso pode te consumir bastante tempo. Fica difícil escalar o negócio. Às vezes pode ser mais fácil você entregar ao cliente uma solução mais comercial, como o Hubitat. O equipamento é um pouco mais caro, mas te economizará horas de trabalho. Então acho que compensa.

2. Outro ponto a se considerar é que para fazer uma instalação decente com Alexa e Home Assistant sem mensalidade você precisará criar uma função lambda na Amazon, e para isso você precisará vincular um cartão de crédito à conta. Você já pensou como vai fazer isso para cada novo cliente?

**Comment by felipediel** [comment]
Verifica o botão on/off. O controle precisa estar ligado.

**Comment by dudusandi** [comment]
@felipediel Por algum motivo o botão foi para off mesmo.. Só confirmando então a mudança do broadlink, agora eu faço 1 script para leitura e após isso faço 1 script para enviar o IR com os nomes colocados no script 1 e ai crio os ícones selecionando o script ? Sobre a ideia, no iPhone eu uso o app atalhos, crio um  URL POST com endereço ddns do assino para comandar pela siri, assim funciona em qualquer lugar, sem depender de um serviço como google ou Amazon..

**Comment by felipediel** [comment]
Essa é uma forma de fazer, tem várias outras. Essas entidades são quase universais, você pode combiná-las com praticamente qualquer coisa. Quanto ao negócio, te recomendo a começar do seu jeito. Vai lá e faz. O mais importante é dar o primeiro passo, depois você ajusta a direção. Boa sorte!
