### ISSUE TITLE
SmartThings Intergration

### ISSUE THREAD

**Issue by ur7x** [home-assistant/home-assistant.github.io#14609]
## SmartThing Device polling

I use a Smartthings V2 hub as my Z-wave hub and have successfully completed the integration with HA.  If I toggle a Z-wave switch in HA then Smartthings updates... BUT if I toggle a Z-wave switch in Smartthings, or at the wall switch, HA ignores the state change.  If I reboot HA then it sees the state change or if I go into the integrations page and "reload" the SmartThings integration then HA sees the state change... Is can't be normal.. how do I fix it?

**Comment by frenck** [comment]
Thank you for reaching out, unfortunately, it seems you ended up in the wrong place.
This issue the issue tracker for our website, your issues seem to be about a core integration.

At this point, I'm unsure if you have a question/need support or trying to report a bug. In case of you think you've found a bug, please raise an issue here:

https://github.com/home-assistant/core/issues

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places in that case.

Thanks! 👍
