### ISSUE TITLE
HomeKit documentation should specify which integration you're editing

### ISSUE THREAD

**Issue by loganmarchione** [home-assistant/home-assistant.github.io#14618]
This might be a just because I'm a HA semi-noob, but I ran into an issue recently. 

# Problem
I had successfully setup [HomeKit](https://www.home-assistant.io/integrations/homekit) in HA via the UI, setup sensors and lights, and got it working on my iPhone's Home app.

However, I wanted to exclude a sensor from showing up in my iPhone, so I created an exclusion filter in my `configuration.yaml` file, but this didn't work.
```
homekit:
  filter:
    exclude_entities:
      - light.unknown_1
```

After messing around, I noticed a second HomeKit instance running on a different port, that was controlled via YAML. That's when I realized that creating the filter in my `configuration.yaml` was creating this second instance.

![Screenshot_20200925_232841](https://user-images.githubusercontent.com/4955337/94329191-68704c00-ffa8-11ea-961e-877f0be7e7da.png)

I then realized I needed to exclude the entity via the UI, which instantly removed it from my iPhone Home app.
![Screenshot_20200925_233111](https://user-images.githubusercontent.com/4955337/94329224-bc7b3080-ffa8-11ea-82b9-e74edbb6b5ef.png)

# Request
Can the [documentation](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/homekit.markdown) be updated with some warning about this? Maybe in the [Considerations](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/homekit.markdown#considerations) section?

For example:

> If you create a HomeKit integration via the UI (i.e., Configuration-->Integrations), it must be configured via the UI **ONLY**. Any attempt to configure the HomeKit instance created in the UI via the `configuration.yaml` file will result in another instance of HomeKit running on a different port.

If this is not an option, can the ability to exclude an entity be added to a brand-new HomeKit integration? Currently, when creating a new HomeKit integration, you can choose your domains to include (but not exclude) on initial setup.

**Comment by frenck** [comment]
Hi there @loganmarchione!

Feel free to help us out improving the documentation, but using the edit link that is on top of each page.

Thanks 👍
