### ISSUE TITLE
Move frontmatter redirects to redirects file

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#14662]
## The problem

We have quite a few pages that still rely on `redirect_from` in their page frontmatter.

These need to be removed and added to the `source/_redirects` file instead.

Files currently still having `redirect_from` frontmatter:

- [x] source/lovelace/index.markdown
- [x] source/code_of_conduct/index.markdown
- [x] source/_posts/2019-11-22-state-of-the-union.markdown
- [x] source/_posts/2019-06-05-release-94.markdown
- [x] source/hassio/index.markdown
- [x] source/cloud/alexa.markdown
- [x] source/_docs/tools/scripts.markdown
- [x] source/_docs/frontend/browsers.markdown
- [x] source/_docs/configuration/securing.markdown
- [x] source/_docs/configuration/devices.markdown
- [x] source/_docs/configuration/yaml.markdown
- [x] source/_docs/configuration/troubleshooting.markdown
- [x] source/_docs/configuration/customizing-devices.markdown
- [x] source/_docs/configuration/basic.markdown
- [x] source/_docs/configuration/platform_options.markdown
- [x] source/_docs/configuration/state_object.markdown
- [x] source/_docs/configuration/events.markdown
- [x] source/_docs/configuration/packages.markdown
- [x] source/_docs/configuration/splitting_configuration.markdown
- [x] source/_docs/configuration/secrets.markdown
- [x] source/_docs/configuration/templating.markdown
- [x] source/_docs/authentication/providers.markdown
- [x] source/_docs/authentication/multi-factor-auth.markdown
- [x] source/_docs/z-wave.markdown
- [x] source/_docs/authentication.markdown
- [x] source/_docs/backend/database.markdown
- [x] source/_docs/backend/updater.markdown
- [x] source/_docs/automation/examples.markdown
- [x] source/_docs/automation/troubleshooting.markdown
- [x] source/_docs/automation/condition.markdown
- [x] source/_docs/automation/trigger.markdown
- [x] source/_docs/automation/templating.markdown
- [x] source/_docs/automation/action.markdown
- [x] source/_docs/z-wave/devices.markdown
- [x] source/_docs/z-wave/installation.markdown
- [x] source/_docs/z-wave/control-panel.markdown
- [x] source/_docs/z-wave/device-specific.markdown
- [x] source/_docs/installation/troubleshooting.markdown
- [x] source/_docs/installation/docker.markdown
- [x] source/_docs/installation/virtualenv.markdown
- [x] source/_docs/installation/raspberry-pi.markdown
- [x] source/_docs/installation/updating.markdown
- [x] source/_docs/installation.markdown
- [x] source/_docs/scripts.markdown
- [x] source/_docs/scripts/service-calls.markdown
- [x] source/_docs/scripts/conditions.markdown
- [x] source/_docs/scripts/editor.markdown
- [x] source/_cookbook/notify.mqtt.markdown
- [x] source/getting-started/automation.markdown

**Comment by ProfessorLogout** [comment]
I'll take a stab at this later today

**Comment by klaasnicolaas** [comment]
At the moment all redirects have been processed or are almost processed (pull request open). No help is needed for this issue anymore, but also check out the other issues with the label **Help wanted**! 😄
