### ISSUE TITLE
Suggested solution for tracker fritz not working

### ISSUE THREAD

**Issue by Superheld** [home-assistant/home-assistant.github.io#1468]
Hello!

I hope, I'm right here ;-)

I would like to use fritz for precence dedection. On the website is a solution for linux to install necessary libs. But this is not working on a raspy.

```
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libxslt1-dev armhf 1.1.28-2+deb8u1
  404  Not Found [IP: 5.153.225.207 80]
Err http://mirrordirector.raspbian.org/raspbian/ jessie/main libxslt1.1 armhf 1.1.28-2+deb8u1
  404  Not Found [IP: 5.153.225.207 80]
Unable to correct missing packages.
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libx/libxslt/libxslt1-dev_1.1.28-2+deb8u1_armhf.deb  404  Not Found [IP: 5.153.225.207 80]

E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/libx/libxslt/libxslt1.1_1.1.28-2+deb8u1_armhf.deb  404  Not Found [IP: 5.153.225.207 80]
```

Page: https://home-assistant.io/components/device_tracker.fritz/

should be fixed to provide clear solutions

Bye`

**Comment by Landrash** [comment]
Output is an error from the repository your trying to fetch packages from. Not anything we can fix or change. Suggest you update your source list or have a look at the raspbian forums. Good luck.
