### ISSUE TITLE
document the list of "embedded scripts"

### ISSUE THREAD

**Issue by joejulian** [home-assistant/home-assistant.github.io#14694]
## The problem
The [command line help](https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/tools/hass.markdown) has a flag:
```
--script ...          Run one of the embedded scripts
```

There's no documentation (that I can find) as to what the list of embedded scripts are.

**Comment by KhushbuB** [comment]
Hello @joejulian 
As per my understandings, I see [3 embedded scripts](https://github.com/home-assistant/home-assistant.io/tree/current/source/_docs/scripts) for the command line [**_hass_**](https://www.home-assistant.io/docs/tools/hass/) to execute :
1. [Service Calls](https://www.home-assistant.io/docs/scripts/service-calls/)
2. [Conditions](https://www.home-assistant.io/docs/scripts/conditions/)
3. [Editor](https://www.home-assistant.io/docs/scripts/editor/)

But we can modify the `hass` `--script` statement to make it more sense.
I look ahead to work on this, let me know what you think of my findings.

**Comment by joejulian** [comment]
Perhaps that should be referenced on that documentation page as well? There's nothing that really links the term, "embedded scripts" with those in the documentation.
