### ISSUE TITLE
System Monitor - Mandatory Arguments Needs Updating for 0.116.0.b.0

### ISSUE THREAD

**Issue by townsmcp** [home-assistant/home-assistant.github.io#14710]
## The problem

  Following link needs updating:

https://rc.home-assistant.io/integrations/systemmonitor/

Affects the following sensors:
swap_use_percent
swap_use 
swap_free

They all are mandatory to set arguments on 116 beta.
If no arguments are set, HA won’t allow restart and throws an error notification.
Use Check Config to confirm before a restart

**Comment by CurrentThread** [comment]
documentation is correct, bug fixed in beta 2, see https://github.com/home-assistant/core/pull/41025

**Comment by spacegaier** [comment]
That is not correct. Those three sensors do not require any parameters, at least not in the latest one or two HA versions.

**Comment by frenck** [comment]
Right, this was fixed actually! Closing this issue as it is no longer an issue.
