### ISSUE TITLE
Markdown headings

### ISSUE THREAD

**Issue by stefanroelofs** [home-assistant/home-assistant.github.io#14784]
While testing the site for broken links with Xenu, I found a lot of these results:
```
https://www.home-assistant.io/integrations/xiaomi_miio#configuration-variables anchor occurs multiple times
https://www.home-assistant.io/integrations/xiaomi_miio#host anchor occurs multiple times
https://www.home-assistant.io/integrations/xiaomi_miio#token anchor occurs multiple times
https://www.home-assistant.io/integrations/xiaomi_miio#name anchor occurs multiple times
https://www.home-assistant.io/integrations/xiaomi_miio#features anchor occurs multiple times
https://www.home-assistant.io/integrations/xiaomi_miio#model anchor occurs multiple times
https://www.home-assistant.io/integrations/xiaomi_miio#platform-services anchor occurs multiple times
https://www.home-assistant.io/integrations/xiaomi_miio#configuration anchor occurs multiple times
```

The reason for this is that the documentation is written in markdown format. All headings are converted to a link. You can easily jump to a link with an anchor like this:
```[Go to sensors](#sensors)```

The problem is that some headings are not unique. That's why I see the messages 'anchor occurs multiple times'.

If that is the case, it should add "-1", "-2", "-3",... to make it unique. This does not happen.

See here for more information: https://gist.github.com/asabaylus/3071099

I don't know if this is something that we can fix, or if this is a problem in a dependency that we use to generate the html from the markdown?

**Comment by deosrc** [comment]
This is also present on the [webostv](https://www.home-assistant.io/integrations/webostv/#sources) integration. The "Sources" link in the navigation bar links to the "sources" parameter instead of the "Sources" header because they share the same anchor name.

**Comment by deosrc** [comment]
Still relevant

**Comment by deosrc** [comment]
Still relevant

**Comment by deosrc** [comment]
Still relevant

**Comment by deosrc** [comment]
Still relevant

**Comment by deosrc** [comment]
Still relevant

**Comment by pandabear41** [comment]
@deosrc Please see PR and review the purposed solution.
