### ISSUE TITLE
PR #1393 provides unclear instructions

### ISSUE THREAD

**Issue by Molodax** [home-assistant/home-assistant.github.io#1493]
PR #1393 "Simplified instructions" provides unclear (impossible?) instructions regarding HTML5 push notification component under subsection [Getting ready for Chrome ](https://home-assistant.io/components/notify.html5/#getting-ready-for-chrome).
See details of the issue here: https://community.home-assistant.io/t/html5-step-getting-ready-for-chrome-pls-help/6586

**Comment by Landrash** [comment]
@amahlaka Since you wrote the expanded documentation I'm hoping you could help here?

**Comment by amahlaka** [comment]
It can be difficult to verify domain if you can't open ports 80 and 443 on your router, recommend way is to use DNS provider that allows you to create txt records, you can get domains like that from namecheap for under 1$

**Comment by Molodax** [comment]
Hi @amahlaka and @Landrash, 
Unfortunately, the answer above doesn't make instructions clearer. 
1) Could you please elaborate more regarding ports 80 and 443? Do you mean port forwarding to set up encryption,  e.g. using Let's Encrypt or something else?
2) I think that instructions for HASS do not mention paid DNS providers for text records. Is this way is more simple than to upload html for verification?? See here https://community.home-assistant.io/t/html5-step-getting-ready-for-chrome-pls-help/6586
3) My html5 push notifications work ok (exept one device, details in issue #4506) without this verification process. Is really neccesary step?

**Comment by Molodax** [comment]
I've temporarily solved the issue on domain verification by adding the meta tag in `\Python35-32\Lib\site-packages\homeassistant\components\frontend\templates\index.html` however, I don't think that it is a good solution.
This step still needs clarification and some simple solution if its really necessary for html5 push notification.

**Comment by ianrobrien** [comment]
It seems like the instructions in general could use an update, as it was confusing which values to use for the keys. It even looks like the API key may be deprecated going forward.

**Comment by fabaff** [comment]
There was no action on this issue for over six months. I'm going to close it.
