### ISSUE TITLE
WoL causes issue with CoreDNS

### ISSUE THREAD

**Issue by joemadd3n** [home-assistant/home-assistant.github.io#14958]
## The problem

The WoL integration causes issues with CoreDNS when the "Host" parameter is not set. The documentation suggests that "HOST" is an optional key however, whenever it is not set the CoreDNS container reports the following error messages:

Oct 06 14:03:24 HomeAssistant 1008d0f60de7[458]: [ERROR] plugin/errors: 2 none.local.hass.io. A: unreachable backend: no upstream host
Oct 06 14:03:27 HomeAssistant 1008d0f60de7[458]: [INFO] 172.30.32.1:60123 - 49608 "A IN none.local.hass.io. udp 36 false 512" NOERROR - 0 0.00039084s

Port number changes but IP remains static.

https://imgur.com/a/PJ0Exz1
https://imgur.com/a/jwNewy3

**Comment by frenck** [comment]
Please report the issue in the appropriate repository.

If you want to report an issue with the WOL integration of Home Assistant:

<https://github.com/home-assistant/core/issues>

In case you want to report a bug with the DNS plugins of the Supervisor:

<https://github.com/home-assistant/supervisor/issues>

Thanks 👍
