### ISSUE TITLE
Missing SRI for external Javascript 

### ISSUE THREAD

**Issue by edent** [home-assistant/home-assistant.github.io#14962]
## The problem
Several pages call external Javascript. None of them use SubResource Integrity - https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

Are you happy for me to make a PR adding SRI?

For example:
* https://github.com/home-assistant/home-assistant.io/blob/current/source/integrations/index.html#L67

Some documentation tells people to create pages which call scripts, but don't use SRI:
* https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/smtp.markdown

**Comment by edent** [comment]
The SMTP documentation is still insecure.

**Comment by frenck** [comment]
SRI is not a requirement on the web.

Feel free to add it using a PR, but it is not an issue.
