### ISSUE TITLE
Warning on the way you use the TaHoma API - Somfy Integration

### ISSUE THREAD

**Issue by joemadd3n** [home-assistant/home-assistant.github.io#14997]
## The problem

Email recevied this evening from Somfy.

Dear customer,
In an ongoing effort to provide the best services to our users, we monitor the traffic generated by our applications and Smart Home boxes (TaHoma and Connexoon). It appears that you are using a third-party solution, either developed by yourself or provided by an external entity (developer or community of developers not working for Somfy). Such developments are made without our willingness and, sometimes, do not respect our usage guidelines.
We are contacting you today to update the way your script or your application behaves with our API as it is overconsuming our backend resources for your own installation. To do so, please contact the provider of your solution or update your code by October 31st.
We are asking all third-party scripts or application to reduce their polling activity on our API. In particular, the GET /setup endpoint is meant to be used once and only once by end-user session and not to regularly refresh the devices data.
As we do not want every TaHoma and Connexoon users be impacted by the overuse of some individuals, we will react in the coming months and set up rate limiters and automated bans if such changes are not applied.
Thank you for your understanding. 

Is this something that can be address in the integration?

**Comment by iMicknl** [comment]
See https://github.com/home-assistant/core/issues/41352. I believe your issue doesn't belong in the documentation repository.
