### ISSUE TITLE
Scripts document Variables section formatting problem

### ISSUE THREAD

**Issue by guystreeter** [home-assistant/home-assistant.github.io#15242]
## The problem

In the Variables section of the Scripts documentation [here](https://www.home-assistant.io/docs/scripts/#variables), the example needs to be escaped so that the usage of the variables will show up. I could not understand the example at all, until it occurred to me to look at the raw document on github. I think wrapping the example in `{% raw %}` / `{% endraw %}` will fix it.

**Comment by frenck** [comment]
Thanks, @guystreeter. Opened a PR to address it.
