### ISSUE TITLE
Clearification of missing information for https://www.home-assistant.io/integrations/roomba/

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#15316]
## The problem

Following the manual of this integration, it is too hard for unexperienced users to get the BLID and Password credentials with the current links on the bottom of the page: https://www.home-assistant.io/integrations/roomba/

I can't make an PR. But according to the information on github: "Website/Docs bug report Report incorrect/missing information" suggest this here also would be the right place to start.

I'd like to propose some extra information, here it is in concrete form, tested and currently working:

### Alternative option to retrieve Roomba Password and BLID using a regular Windows PC

1. Downloading files
Create a temporary folder on your desktop for extra convenience (you can name the folder whatever you want) and put these two files inside that folder:

- Python installation package
It's recommend getting the latest “executable installer”. You can find this in the ‘Download’ section of the official Python website https://www.python.org

- Roomba Python Library
This is a zip-package of files used to establish integration with your Roomba. You can find it at https://github.com/NickWaterton/Roomba980-Python. Look for a green button named “Code”, Click it and select “Download zip”.
Now you should have two files (one exe file and one zip file) in a folder on your desktop.

2. Install Python
a.	Start Python installation by running the exe-file. Select “Customize installation”.
Click “Next”. On the “Advanced options” page be sure to check “Add Python to environment variables”, and edit “Customize install location” to `c:\Python`, then click “Install”. (Please keep the Python installation file in your desktop folder for now).

b.	Open the Roomba zip-file and locate the “roomba” folder inside. Copy this folder into your freshly installed Python folder (c:\Python).

c.	Use your favourite method of opening a DOS prompt (example: click the magnifying glass besides the Start-menu icon and search for “cmd” or open a PowerShell window). Then use the DOS prompt to navigate to your C:\Python folder using the `cd \python` command.
Once inside the Python folder, type `pip install six` and press ENTER. Wait for the ”six” installation to finish. After a few seconds you should be back in the DOS prompt.

3. Run the script
Type `python .\roomba\getpassword.py`, hit ENTER and wait a few seconds. Now your Roomba should be detected by the script. From here on you should follow on-screen directions (something about making sure your Roomba is turned on and parked in the base, and then holding the “Home” button for a few seconds to hear a bleep. This should cause the wifi indicator on your Romba to flash - then hit ENTER to continue and wait a few seconds more).

Your Roomba’s BLID and password now appears in the bottom of the DOS window! Copy this info to a txt-file, grab a screenshot or whatever method you like best.

From here on you can follow the instructions found on the Home Asistant website on how to add your Roomba to your “configuration.yaml” file (https://www.home-assistant.io/components/vacuum.roomba/). Then you’re ready to reboot your Home Assistant and enjoy Roomba integration.

4. Cleanup
Start the Python installation by running the exe-file in your temporary desktop folder, select “Uninstall” and wait for uninstaller to finish. Now you can delete the ”C:\Python” folder, and also delete the temporary folder from your desktop.

**Comment by frenck** [comment]
Please open change proposals as pull requests. Thanks 👍

**Comment by ghost** [comment]
Done (first try).
