### ISSUE TITLE
Loop Energy are switching off their v1 infrastructure.

### ISSUE THREAD

**Issue by tocklime** [home-assistant/home-assistant.github.io#15345]
## The problem
Loop Energy are switching off their v1 infrastructure in favour of their v2. The home assistant loop energy integration does not support v2 at all (it's totally different, app only, no public API). They're switching it off on 13th Nov 2020. [Proof](https://email.loop.homes/action-required-how-to-claim-your-free-loop-upgrade-1).

The website should at have a warning saying so, and the integration should be scheduled for removal.

**Comment by frenck** [comment]
This is handled via PRs and not a website issues. Closing this issue because of that.
