### ISSUE TITLE
CC265x and CC135x with Z-Stack 3 should be considered stable in ZHA with zigpy-znp?

### ISSUE THREAD

**Issue by Hedda** [home-assistant/home-assistant.github.io#15367]
## The problem

Suggest that CC2652P/CC2652R/CC2652RB + CC1352P/CC1352R radios with Texas Instruments Z-Stack 3.x.x Zigbee firmware should be considered stable or "KNOWN WORKING" and no longer "EXPERIMENTAL" in the ZHA integration with zigpy-znp. 

Suggest that website page for ZHA integration component should be updated to reflect this:

https://www.home-assistant.io/integrations/zha/

- Texas Instruments based radios with Z-Stack 3.x.x (via the [zigpy-znp](https://github.com/zha-ng/zigpy-znp) library for zigpy)
  - [CC2652P/CC2652R/CC2652RB USB stick or dev board hardware flashed with Z-Stack 3.x.x coordinator firmware](https://www.zigbee2mqtt.io/information/supported_adapters)
  - [CC1352P/CC1352R USB stick or dev board hardware flashed with Z-Stack 3.x.x coordinator firmware](https://www.zigbee2mqtt.io/information/supported_adapters)

These Zigbee radios have upstream been considered stable with Z-Stack 3.x.x since in zigpy-znp since 12 of July 2020 which correspond to zigpy-znp v0.0.10 (which is a version before the ZHA integration added it) and Home Assistant 0.116 is now using zigpy-znp 0.2.0

https://github.com/zha-ng/zigpy-znp/blob/dev/README.md

https://github.com/zha-ng/zigpy-znp/commit/752779ee7bc2e942804f02242f3a2f70fc6c952f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Suggesting here that zigpy-znp for TI Z-Stack 3 use in ZHA integration component for Home Assistant is practical as "stable" and non-experimental as zigpy-deconz and zigpy-xbee if not bellows too.

**Comment by frenck** [comment]
Why the creation of an issue if you make a PR with the exact same content?! Please don't.
