### ISSUE TITLE
Manual for manual installation on raspi doesn't let user upgrade to python 3.8

### ISSUE THREAD

**Issue by johanf85** [home-assistant/home-assistant.github.io#15374]
## The problem

   I today tried an installation with [this manual ](https://www.home-assistant.io/docs/installation/raspberry-pi/)on a raspberry pi. However if you follow the instructions it updates to python 3.7 and not 3.8 as is needed and called in the manual.

as described here.
https://raspberrypi.stackexchange.com/questions/116118/updating-python-3-7-to-3-8

My knowledge is too little to make a commit for this.

**Comment by frenck** [comment]
I think we need to remove large parts of this manual. The setup of the Python environment is not the responsibility of Home Assistant.
