### ISSUE TITLE
Consistency of color in documentation page

### ISSUE THREAD

**Issue by jjc98375** [home-assistant/home-assistant.github.io#15392]
## The problem

Color of text in Topics section in documentation page are not consistent. It would look better to fix some of black color to blue

**Comment by frenck** [comment]
It is unclear what a "Topic" section is. Could you elaborate?

**Comment by KTibow** [comment]
Could be integration tags/categories?

**Comment by frenck** [comment]
@KTibow Thanks, but additional guessing is not really helpful.

@jjc98375 Could you please elaborate, maybe annotate some screenshots?

**Comment by frenck** [comment]
Closing this issue as stale.
