### ISSUE TITLE
homeassistant.reload_core_config conflicting documentation?

### ISSUE THREAD

**Issue by ronsum232** [home-assistant/home-assistant.github.io#15496]
Docs [here](https://www.home-assistant.io/integrations/homeassistant/) indicate that the homeassistant.reload_core_config service "Loads the main configuration file (configuration.yaml) and all linked files. Once loaded the new configuration is applied.".

The docs [here](https://www.home-assistant.io/docs/configuration/customizing-devices/#reloading-customize) indicates that it reloads customizations.

The latter seems to be more correct.

**Comment by frenck** [comment]
It reloads `homeassistant:` and everything in the base config (which indeed includes customizations)
