### ISSUE TITLE
Extend contribution guide with tips for faster reviews.

### ISSUE THREAD

**Issue by Landrash** [home-assistant/home-assistant.github.io#1553]
Extend our contributing with the following document either with a link or by forking the document and rewriting it to fit Home Assistant.
> We should link https://github.com/kubernetes/kubernetes/blob/master/docs/devel/faster_reviews.md in our contributing guide lines. - ballob

**Comment by balloob** [comment]
For now I have added a link in CONTRIBUTING.md
