### ISSUE TITLE
Add HG8245W5 as a supported Huawei router

### ISSUE THREAD

**Issue by andrewshadura** [home-assistant/home-assistant.github.io#15536]
Hi,
I’ve just verified the Huawei presence integration works very well with HG8245W5. Please add it to the supported routers list.

cc @abmantis

**Comment by abmantis** [comment]
Thanks for the report. Can you submit a PR with that?

**Comment by frenck** [comment]
This is not an issue. We are happy to process this information in the form of a pull request.

To do that, please click the "Edit this page on GitHub" link that is listed on top of each page. This will allow you to suggest a change to the page and add your suggested supported device.

Thanks 👍
