### ISSUE TITLE
Mentioning the use of a CONFIG directory on the getting started page

### ISSUE THREAD

**Issue by johanf85** [home-assistant/home-assistant.github.io#15574]
## The problem

On the [Getting Started](https://www.home-assistant.io/getting-started/) page on the Home Assistant website, it is mentioned that wifi credentials can be added by adding a USB drive named CONFIG with credentials for wifi. However on the page with [Installation instructions](https://www.home-assistant.io/hassio/installation/) the option to add a CONFIG directory to your hassos-boot partition is also being mentioned. 

Isn't it also a good idea to mention the CONFIG directory option too in the Getting Started page? It saves one USB drive to use. 

The Installation page is now referred to on the getting started page as "For advanced users (or if you don’t have a device that is supported by this guide)"

**Comment by frenck** [comment]
IMHO it is easier for people to understand the use of a USB stick versus adding files to a specific partition (that might be loaded on all systems).

This is the reason why it is written this way, as it is more accessible/understandable for less technical users.

Nevertheless, feel free to propose a change, there is an edit link on top of each page.
