### ISSUE TITLE
Automation example contains invalid entity_id: all 

### ISSUE THREAD

**Issue by gribouk** [home-assistant/home-assistant.github.io#15595]
## The problem
I am trying to reproduce the trigger from URL https://www.home-assistant.io/docs/automation/examples/ 
which would call the action if any entity changes it's state:
      - platform: state
        entity_id: all
but the form returns me that error:
Message malformed: Entity ID all is an invalid entity id for dictionary value @ data['entity_id']

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Kiev
version | 0.117.5
virtualenv | false

## Environment

- Home Assistant Core release with the issue: 
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): 
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by azerbinati** [comment]
Having this issue too..

**Comment by stefanroelofs** [comment]
This issue may be closed I think. (or remove the no-stale label)
The referenced documentation [(examples)](https://www.home-assistant.io/docs/automation/examples/) does no longer exist.
