### ISSUE TITLE
Link to "enable the I2C interface manually" not working

### ISSUE THREAD

**Issue by Maco65** [home-assistant/home-assistant.github.io#15669]
## The problem

  On this page: https://www.home-assistant.io/integrations/mcp23017/ the link to more information on how to enable I2C on RPi when using HassOS is not working.
The link name is " enable the I2C interface manually using a USB stick" and the link itself is: https://github.com/home-assistant/hassos/blob/dev/Documentation/boards/raspberrypi.md#i2c

I hope this is right place to "report" such relatively small issue...

**Comment by frenck** [comment]
Thanks, @Maco65!

Opened a PR to adjust that.
