### ISSUE TITLE
I spot a trivial error but I don't know how to fix it

### ISSUE THREAD

**Issue by Edo78** [home-assistant/home-assistant.github.io#15663]
## What's the variable name?
At the end of this page https://www.home-assistant.io/docs/installation/docker/ there is a confusing paragraph

> As Jemalloc can cause issues on certain hardware, it can be disabled by passing the environment variable DISABLE_JEMALLOC with any value, for example: -e "JEMALLOC_DISABLE=true".

Samone should clarify the right name of the variable

**Comment by frenck** [comment]
It is `DISABLE_JEMALLOC`, will adjust it.
