### ISSUE TITLE
Describe a working example at MPD integration 

### ISSUE THREAD

**Issue by katonage** [home-assistant/home-assistant.github.io#15665]
## The problem

It would be useful to name installable add-ons at the end of the mpd integration description. 
https://www.home-assistant.io/integrations/mpd/

Text sais 
"This platform works with Music Player Daemon and mopidy with Mopidy-MPD as used by Pi MusicBox."
But none of them is something that can be installed from within HA, there are a few mopidy add-on variants but hard to decide which one is the way to go. 
I understand there are a plurality of needs and a number of solutions, but the field is important enough to have an "official" how to for simple use cases.

**Comment by frenck** [comment]
> there are a few mopidy add-on variants but hard to decide which one is the way to go

We do not have an official solution, and we don't recommend or endorse 3rd party add-ons.
Adding a list, will not solve that problem.

Home Assistant's goal is to provide documentation about the integration itself.
