### ISSUE TITLE
The documentation needs to separate entities and objects

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [home-assistant/home-assistant.github.io#15671]
## The problem

I am new to HA and was familiarizing myself with the basic concepts. In a close reading of the docs, I see that there are entities, and domains which they belong to. However, this doc 

https://www.home-assistant.io/docs/configuration/state_object/

also mentions object id (in the example light.kitchen, the "kitchen" is an object id). Object IDs are not explained in the Glossary. Are they used/useful/required?

**Comment by frenck** [comment]
It is the latter part of an entity_id.
An entity ID consists of a `<domain>.<object_id>`

e.g., the entity with entity ID `light.living_room` is from the `light` domain and has the object ID `living_room`.

**Comment by FredrikKarlssonSpeech** [comment]
Fair enough. But, that is not communicated on the web site (in the glossary), so maybe it should?
