### ISSUE TITLE
Release Notes page endless loop refreshing

### ISSUE THREAD

**Issue by tiaanv** [home-assistant/home-assistant.github.io#15697]
## The problem
When navigating to https://www.home-assistant.io/latest-release-notes/
The page keeps rapidly refreshing some element, causing the page to not load.

**Comment by McGiverGim** [comment]
I suppose this will be fixed when this is deployed: https://github.com/home-assistant/home-assistant.io/pull/15693

**Comment by klaasnicolaas** [comment]
Closing this because we have a fix: #15693
