### ISSUE TITLE
Supervised vs. Core versions unclear in the docs

### ISSUE THREAD

**Issue by what-name** [home-assistant/home-assistant.github.io#15721]
### Intro
The [current installation docs](https://www.home-assistant.io/docs/installation/#recommended) do not mention clearly enough the difference between Supervised and Core versions of Home Assistant. I've been running HASS in Docker for a week and just understood why I do not have the "Supervisor" tab, running in Docker. The Docker installation docs mention quickly that it is only the Core version, but it is not clear enough and can be overlooked. I fell into this as well and just finally realized the differences between the "Full" vs. Core versions.

### The problem
The docs are not clear enough. The difference between the Supervised and Core versions are not clearly explain at places like the [FAQ](https://www.home-assistant.io/faq/ha-vs-hassio/) and the [Installation](https://www.home-assistant.io/docs/installation/#recommended).

### Solution
The docs should be clarified. There needs to be a clearer explanation on both of the above mentioned pages on what are the key differences between the two versions and which installation methods allow for which. There should also be more explanation on what are the functionalities that the Supervisor offers and what are the methods of achiving the same outcome without the presence of it [on a high level].

**Comment by frenck** [comment]
Feel free to contribute an improvement! 👍

**Comment by TRusselo** [comment]
google
first result
https://www.home-assistant.io/faq/ha-vs-hassio/

hassio is core plus tools

further googling:
supervised is hassio plus yet another tool to supervise the instance and keep it running.
