### ISSUE TITLE
Typos in QNAP Integration Documentation

### ISSUE THREAD

**Issue by RyanRoberts210** [home-assistant/home-assistant.github.io#15727]
source/_integrations/qnap.markdown

drivers list (optional, default: all drivers)
Array of drives to monitor (ex: 0:1).

In both places where it says "drivers" it should actually say "drives".  The first one is caught in Configuration Check if used.

Thx

**Comment by frenck** [comment]
Thanks, @RyanRoberts210 👍 

You can help us out by clicking the "Edit this page on GitHub" link that is on each page. That link allows you to make an edit to the page.

**Comment by RyanRoberts210** [comment]
I followed that link originally, can see the page and prior history but couldn’t figure out how to edit it myself.  I do see the Pencil icon that says “Fork this project and edit this page” but worried that would break things, not just edit the existing document…  Obviously I’m new to this…  If clicking that and making the edits is the right thing to do I’m happy to do it.    Thx

**Comment by frenck** [comment]
Well, if you like to explore, someone wrote a guide about that:

<https://community.home-assistant.io/t/editing-the-documentation-and-creating-a-pull-request-on-github/9573>

**Comment by RyanRoberts210** [comment]
Done, thank you for the link.
