### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by what-name** [home-assistant/home-assistant.github.io#15722]
## Documentation
The current amount and quality of documentation is good. However, it does not touch enough on topics and questions that Home Assistant beginners (such as myself) find hard to understand. As seen in #15721, some things are not clearly explained and warned about, which can result in a turnaway of new users due to the difficulty of onboarding.

I believe the documentation can be extended in ways that would make the initial onboarding and "getting started" process easier and more welcoming. I am currently setting up my smart home and will be using Home Assistant as one of the core pieces to the system. I will be contributiing to the documentation as I learn and understand things that have not been clearly explained in the docs. I would however like your input on what was or still is confusing to you that could be documented [better]. Here are some of my topics currently:

**Questions:**
- What are the functionalities that are present in Supervised and not present in the Core version?
- How to install integrations via the command line?
- Does an integration need to be installed before it can be added to the `configration.yaml`?

**Comment by frenck** [comment]
Feel free to contribute additional documentation.

To answer 2 questions:

> How to install integrations via the command line?

You can't, thus you won't find documentation on that.

> Does an integration need to be installed before it can be added to the configration.yaml?

Depends on the integration, please refer to the documentation of the specific integration for configuration instructions.
