### ISSUE TITLE
Datadog integration docs don't explain how to use it.

### ISSUE THREAD

**Issue by covertbert** [home-assistant/home-assistant.github.io#15769]
The docs suggest that it's as simple as adding `datadog:` to your config. Optionally you can provide an IP address and port but it makes no mention of where you're supposed to be getting the those values from. Presumably somehow an authentication with my DataDog account needs to happen?

I'm evidently not the only one confused by this based on [this forum post](https://community.home-assistant.io/t/datadog-component-getting-started/61510).

Would be good if someone could clarify what needs to be done. I'm happy to update the guide myself when I know what to do...

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/100517627-350a9300-318c-11eb-98f7-753bb5ce557c.png)

It sends it data into a datadog agent. The datadog agent documentation is linked in the description.
The agent passes gathered information into DataDog.

**Comment by frenck** [comment]
Closing this issue, as it is not a documentation issue IMHO. The documentation clearly states it works with a Datadog Agent on the very first line of the integration documentation.

Nevertheless, if you feel like this could be improved, please, go a head and suggest an improvement by clicking on the "Edit this page on GitHub" link.

**Comment by covertbert** [comment]
@frenck yeah I guess I don't think the DataDog agent docs are sufficient to understand how to do this if you don't already have the requisite DataDog knowledge/experience but I understand if you don't think this is the responsibility of the Home Assistant docs to solve.

My DataDog trial has ended anyway, so I no longer have the chance to figure this out or contribute to improving it so I'm happy for the issue to close.
