### ISSUE TITLE
Password resets aren't being sent

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [home-assistant/home-assistant.github.io#15782]
## The problem
Hi,

I have forgotten my password, and have attempted (several times) to reset it.  The reset emails aren't sent.

I can confirm that they are not stuck somewhere in the spam queue, as I have an external spam filter with a searchable archive.

Please let me know if there is further detail you need.

Thanks!

**Comment by SeanPM5** [comment]
For Home Assistant user accounts there's no password reset emails. After you enter and confirm your new password, you'll get a "changed successfully" message and will be able to log in with your new password immediately.

If you're trying to reset your password for the Home Assistant Cloud / Nabu Casa subscription service and it's not sending you the email, you can [contact their support](https://www.nabucasa.com/support/).

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Apologies.  My post wasn't clear.  This is for https://community.home-assistant.io/ .

**Comment by SeanPM5** [comment]
Ah, ok. I know someone else had a similar issue a few weeks ago with receiving their password reset email. You can try sending a private message to one of the forum admins like Paulus or Frenck and see if they can help.

https://community.home-assistant.io/u/balloob
https://community.home-assistant.io/u/frenck

This repository is for issues with the website documentation so community forum support stuff is off topic here, but the above links are your best bet. Good luck.
