### ISSUE TITLE
Rejseplanen integration documents the use of the wrong attribute

### ISSUE THREAD

**Issue by sthyregod** [home-assistant/home-assistant.github.io#15845]
## The problem

Rejseplanen integration documents that the `finalStop` as presented by the API needs to be used in order to to filter by `direction`:

> The values under `finalStop` is the ones you need to put under `direction`. Make sure you use the exact name and insert all possible finalstops [_sic_].

This does not hold true, at least in my case (described below), as directions are filtered by the `direction` attribute.

My case (slightly generalised as it would provide a stop _very_ close to my home), is that of Nordjyllands Trafikselskab's area, more precisely Aalborg. I don't have the time to check a larger sample and see if there's discrepancies between public transport providers, which I believe would be required prior to editing the documentation. 

I can in PM provide actual stops, or if needed check some random stops that is not privacy-sensitive for the same outcome.

## Recommended solution
If it is possible to find any case where my scenario does not hold true, the Rejseplanen API data is by proof of contradiction not uniformly represented across Denmark. In that case I believe we would need to figure out how to document the two cases so that it's clear that both `finalStop` and `direction` should be checked during configuration to see what works (not the best solution, but it does not require any change to the integration). If it is not possible to find any case that deviates from my finding, it is possible to infer that the documentation is incorrect on `finalStop` used to filter by direction.

**Comment by frenck** [comment]
Hi there,

Thanks for opening up an issue. When creating an issue, an issue template is presented. It looks like you've (partly) removed it. This causes your issue report to be incomplete.

Please edit your issue to have the full issue template back again and provide as much of the requested data as possible. Without it, we won't be able to help you.

Thanks already! 👍

**Comment by frenck** [comment]
I'm not sure what you are trying to report now? Is it a bug?

**Comment by sthyregod** [comment]
The documentation for the integration indicates the use of the wrong attribute under this section: https://www.home-assistant.io/integrations/rejseplanen/#direction

For my case it did not work. I had to use the API's `direction` attribute to get it working. I wouldn't call an incorrect documentation a bug, but yes, a 'bug' in the sense that it provides the wrong information.

**Comment by frenck** [comment]
That is disputable, it is described by the author it should work that way, if not, I suspect it is a bug, not a documentation bug?

**Comment by sthyregod** [comment]
It is possible to put it that way. I though think the actual outcome of the integration has a more predictable behaviour as `direction` is `direction`, not `finalStop` as the documentation describes. It is also more intuitive to look for any bus/train/etc. going in 'that' direction instead of arriving at 'this stop (at some street)' as final destination. If you look at Rejseplanens user interface ([rejseplanen.dk)](https://webapp.rejseplanen.dk/webapp/?language=en_EN) it also lists the `direction` visibly when presented with a list of routes so it's the default behaviour to ascertain a direction of a transport, not final stop.

With that in mind, I'd believe it's smarter to look at the documentation. Bonus is it should be easier to edit the text.

**Comment by frenck** [comment]
Could you make a suggested edit? Every page has an edit link in the top that allows you to suggest an edit.
