### ISSUE TITLE
Link to flashing n2 otg broken on installation guide

### ISSUE THREAD

**Issue by superdyoll** [home-assistant/home-assistant.github.io#15912]
## The link to flashing the n2 otg is broken in the installation guide
On the [installation page](https://www.home-assistant.io/hassio/installation/) there is a link to use otg to flash the odroid n2. The link on the page points to ` https://www.home-assistant.io/hassio/installation/hassio/flashing_n2_otg/` however the actual document is located at `https://www.home-assistant.io/hassio/flashing_n2_otg/` I've had a quick look at the installation markdown file but I couldn't see an obvious mistake to mean that the link would append to the existing URL rather than starting at the root so I've raised it as an issue here instead. Hopefully, someone else understands why this is happening.

**Comment by frenck** [comment]
Fixed! Thanks 👍
