### ISSUE TITLE
Blue 'Change of mood?' spacing issue

### ISSUE THREAD

**Issue by davidtedfordholt** [home-assistant/home-assistant.github.io#15921]
## The problem

The spacing of the two images of Zen mode and Dev mode is too small, such that they cover parts of the "Rotate the cover" language between them. This occurs in Chrome and Edge, at least, and changes but is a problem whether the page is full width or resized. I'd drop a PR if I knew a darned thing about spacing on webpages!

**Comment by frenck** [comment]
@ludeeus Is this something you could take a look at?
