### ISSUE TITLE
Counter documentation mentions 'None' for min/max, but GUI only accepts integers

### ISSUE THREAD

**Issue by ddppddpp** [home-assistant/home-assistant.github.io#15930]
## The problem
Setting up a Counter Helper from the GUI mandates Minimum/Maximum values. The doc page mentions 'None' means no minimum/maximum requirements, however the GUI only allows for integer input. This might confuse the user into setting/leaving the value to zero (0), which might lead to unexpected behavior (i.e. you set initial, max, min values to zero, you try to increment/decrement and you get no error but no change in value).

**Comment by frenck** [comment]
This not a documentation issue. YAML capabilities and UI capabilities may differ.

**Comment by ddppddpp** [comment]
That is entirely true, however I can see no way for a user to set no min/max using just the GUI. I think the text descriptions in the GUI are not clear enough, i.e. accepting the defaults will result in a counter that can't increment (pls see the screenshot)
<img width="400" alt="Screenshot 2020-12-22 at 7 57 34" src="https://user-images.githubusercontent.com/45116849/102854705-bc65c200-442b-11eb-9cfb-d3494aac2b2a.png">

**Comment by frenck** [comment]
Still, that is a feature request for the frontend, not a documentation issue. Feel free to raise a feature request at the frontend for this 👍
