### ISSUE TITLE
Nest Integration Instructions Do Not Work

### ISSUE THREAD

**Issue by tescophil** [home-assistant/home-assistant.github.io#15939]
## The problem

The instructions for integrating nest thremostats with HA do not work. The instructions fall apart after a few steps.

1. Device Access Registration, this works OK
2. Device Access Console, payment, this works OK
3. Device Access Console, Create Project, this works OK
4. Give your project a Name, his works OK
5. Creating OAuth client ID. This is where it all falls apart. When navigating to the Google Cloud Console credentials page, you cannot create credentials at this point. This page simply says "To view this page, select a project", but there are no projects to select because none have been created. So you cannot create an OAuth ID without first creating a project, and you cannot create a project unless you have an OAuth ID. Genius.

These instructions are pretty insane to start off with, but this is just ridiculous. Its built on too many assumptions, and clearly the workflow has not been tested properly with a "Virgin" account.

**Comment by bschatzow** [comment]
I believe you skipped a step.  You have to go to the page where it asks you for the $5.00 to get the id

**Comment by tescophil** [comment]
No, I paid the $5 in step 2, device access console payment, then step 3 is create project, then 4 name it, then 5 FAIL.

**Comment by tescophil** [comment]
Step 3 After payment
![image](https://user-images.githubusercontent.com/59442445/102698061-a50fb480-4232-11eb-9a1e-72c243353dbc.png)
then
![image](https://user-images.githubusercontent.com/59442445/102698082-b6f15780-4232-11eb-9f5a-6d9383ef61e0.png)
then
![image](https://user-images.githubusercontent.com/59442445/102698107-d1c3cc00-4232-11eb-951a-7154777fb38f.png)
So, then step 5, create OAuthID
![image](https://user-images.githubusercontent.com/59442445/102698134-020b6a80-4233-11eb-8bec-225aaf80c7f9.png)
and
![image](https://user-images.githubusercontent.com/59442445/102698176-56164f00-4233-11eb-98f1-c6077c43723c.png)
Epic Fail

**Comment by allenporter** [comment]
To get you unstuck: I believe you should click "New project" so that you have a cloud project, then you should be able to create an OAuth ID.  The "project' in this context (Cloud Console) is different than the "Project" in the Device Access Console. 

I appreciate your frustration.   I spend a couple hours per week updating the instructions and integration itself to make them easier for folks, but there are still some gaps.  Yes, I have like 5 cloud projects already, and I didn't delete them to make a virgin account.  Hope that is understandable, and the docs definitely appreciate contributions from folks who run into "ridiculous" "epic fails" and want to make them better.

Good luck.

**Comment by tescophil** [comment]
So, no, clicking "New Project" does not get me "unstuck".....

This is my developer console view
![image](https://user-images.githubusercontent.com/59442445/103206484-e28bd600-48f3-11eb-9495-d1d094fe9969.png)
Clicking on "Create Project"
![image](https://user-images.githubusercontent.com/59442445/103206516-fcc5b400-48f3-11eb-84cc-7c5de1649d62.png)
Then click "Create"
![image](https://user-images.githubusercontent.com/59442445/103206629-2bdc2580-48f4-11eb-8b1b-e833cfe5facc.png)
Then click 'Create Credentials -> Create OAUTH ID"
![image](https://user-images.githubusercontent.com/59442445/103206678-54641f80-48f4-11eb-86e1-d7ef7501c426.png)
So, problem.., you have to create a consent screen (whatever that is...), in order to create an OAUTH ID, so clicking on create consent screen gives you a load of options, check boxes, URL's etc to fill in, but where to start. ? The "Guide" makes no mention of this whatsoever
![image](https://user-images.githubusercontent.com/59442445/103206831-ac028b00-48f4-11eb-9d1a-fbcb77654d78.png)

1) Internal or external ?
2) App name ?
3) Support email ?
4) App Logo ?
5) App domain Application Home page ?
6) Application privacy policy link ?
7) Application terms of service link ?
8) Authorised domains ?
9) Developer contact information ?

**Comment by alexanderfitu** [comment]
I have the same issue. It does appear that google are changing this API process on a fairly regular basis, sending the documentation out of sync. I have also been unable to get anywhere past your screen. 

I did manage to create a blank consent screen, but the callback URL is not explained so I am not sure what to put there.

**Comment by allenporter** [comment]
@tescophil  I've sent a [PR](https://github.com/home-assistant/home-assistant.io/pull/16047) for review and I invite you to leave any feedback with additional improvements you'd like to see either here or in the PR.  There are already 20-30 steps, so as you can imagine there is already a ton of detail so its helpful to hear about your epic fails.

I won't be testing with a "virgin" account so hopefully we can use yours.  However, I did try with a new developer project to experience more of the pain your seeing since as @alexanderfitu mentioned the flow has changed since I last tried this.

**Comment by allenporter** [comment]
The new instructions are submitted, let me know if you have other feedback.

**Comment by alexanderfitu** [comment]
Small updated:  I did manage to follow the instructions [here ](https://community.home-assistant.io/t/google-nest-offical-device-access-console-finally-released/229146/263)

and successfully have the Nest thermostat showing. I have not tried to change the set point temperature yet.

**Comment by allenporter** [comment]
@alexanderfitu thank you for testing out the new instructions

@tescophil It has been a couple days so I am going to go ahead and close.  Feel free to file additional issues with feedback if you have more and I would be more than happy to have a look.  Good luck.

**Comment by tescophil** [comment]
@allenporter  Hi, sorry I could not test the new workflow sooner, busy over Christmas.

So, almost perfect.., just one step/instruction missing:

After creating a nest: entry in the configuration.yam. you then have to RESTART home assistant, this step is missing from the instructions.

Then (after a restart) adding the integration works perfectly.

Would still like to know what enormous crack pipe Google was smoking when it came up with this workflow, however, I've been waiting 2 years for this integration , and I can't thank you enough for the your efforts in making it happen.

I have two 'Nest Thermostat E' devices, so the original (pre-gopogle) integration, and the bad-nest integration never worked for me.

Thanks Again.
