### ISSUE TITLE
List of most frequently viewed components

### ISSUE THREAD

**Issue by mehuman** [home-assistant/home-assistant.github.io#1594]
Is there a list of the most frequently view component docs? It would be great to be able to focus documentation on the components people view the most. Same is true for the most frequently used components now that we are tracking stats.

**Comment by balloob** [comment]
So we actually don't track any usage of components. We only know the Python version/OS that is being used. Most popular based on visitor stats:

<img width="250" alt="screen shot 2016-12-15 at 8 06 29 pm" src="https://cloud.githubusercontent.com/assets/1444314/21251346/0213dbe8-c302-11e6-9a05-343ce3d5408b.png">

**Comment by mehuman** [comment]
Great! That's an awesome place to start. Tracking component usage just for a count would be a great metric to have for helping focus dev work as well.

Thanks!

**Comment by arsaboo** [comment]
Agree with @mehuman. If the objective is to help with (developer) resource allocation, knowing which components are being used is an important metric. Again, users can opt-out.

**Comment by Landrash** [comment]
@balloob Looking at that list a bunch of them are `toolbox` components that you often refer back to the documentation for and things linked to from the getting-started guide.

Best in this direction would to see what folks are googling for when it comes to Home Assistant.

A few suggestion for where to start adding documentation:
 - Work https://github.com/home-assistant/home-assistant.github.io/issues/1603 . It's going to be the next big thing I imagine.
 - Blog post's featuring a specific component. Deep dive in what it can do. Screenshots of how it looks in Home Assistant and advanced usage of the component in combination with templates and similar.
 - Blog post's of getting started with any of the [HUB](https://home-assistant.io/components/#hub) components.
 - Check for when components where written and see to that the documentation is up to date. Date is written in the top of each of the documentation files.
 - Look at the issues in the forum.
 - Expand our getting started guides to include more platforms and hardware?

Adding tracking of components could quickly get unpopular.

**Comment by Landrash** [comment]
Closing since there's no work being done on this issue.
In the future some data about used componentes by user opt-in via the updater component may be available.
