### ISSUE TITLE
Missing Step

### ISSUE THREAD

**Issue by Galapagon** [home-assistant/home-assistant.github.io#15945]
When Creating the OAuth client ID it is requesting an application type. I assume it should be Web application, but it is not listed in the documentation steps 
![2020-12-17_14-57-19](https://user-images.githubusercontent.com/30904284/102536877-371f8d80-4078-11eb-859f-1953e2d12986.jpg)

**Comment by frenck** [comment]
Hi there @Galapagon

We have over 1500 different integrations and platforms active in our system. Mind sharing which one we are talking about?

**Comment by Galapagon** [comment]
Oop, good point! Sorry about that, this is from the new nest integration

**Comment by danhood** [comment]
Noticed this was step is missing as well.

I'm trying to setup a new Nest thermostat.  I also assumed Web App, but I can't get the integration to work what-so-ever.  When I attempt to add the discovered Nest integration, on the "Link Nest Account" modal, the hass generated link for "authorize your account" results in a 404 on Nest's end.  Unsure if related?

**Comment by Galapagon** [comment]
https://www.home-assistant.io/integrations/nest/#device-access-registration step 6

**Comment by frenck** [comment]
The refactoring/improvements of the Nest integration documentation is tracked here: #15939

Please be sure to check our documentation again, as the instruction has been iterated at this point.
