### ISSUE TITLE
Google Assistant api_key still in documentation

### ISSUE THREAD

**Issue by ZuluWhiskey** [home-assistant/home-assistant.github.io#15948]
## The problem

The [configuration variables](https://www.home-assistant.io/integrations/google_assistant/#configuration-variables) for manually setting up Google Assistant say that `api_key:` will be removed as of 0.105 but they are still referenced in the documentation. Was this removed / depreciated or was a decision made to keep this?

I'm happy to do a quick PR to either remove it from the documentation if it has now been removed or remove the reference to it being depreciated.

**Comment by klaasnicolaas** [comment]
https://github.com/home-assistant/home-assistant.io/pull/15870

In progress, it will be removed in the next release 😉
