### ISSUE TITLE
Update Weather Underground status / warning

### ISSUE THREAD

**Issue by LordMike** [home-assistant/home-assistant.github.io#15990]
## The problem
I was seeing what options I had to integrate a PWS into my HA setup. I [came across this integration](https://github.com/home-assistant/home-assistant.io/blob/2ba507b79aae959366314ec1aef7830ccc2850dd/source/_integrations/wunderground.markdown), which has a warning that says that Weather Underground would stop their API Keys from working ... in 2018. We're soon to be 2021, and this warning is still in place.

I could create an API key on Weather Underground, but I couldn't find any pricing or such indication that the API key wasn't free, or wouldn't work. I haven't tested this key.

So while I don't have anything new to add, could _somebody_ update the warning? :)

**Comment by frenck** [comment]
There is an exception in that warning:

> "except you own a personal weather station and provide your data to WU"

Which, as far as I know, makes the whole thing valid.

**Comment by LordMike** [comment]
Oh - buut, the warning also states that the API is EoS'ed in 2018, but it must still be working since the integration exists. It also says "at this time existing free keys will continue to work" .. which can't still be true.. right? :)

I've reworded it a bit, would that work?

> Obtain a WUnderground API key here. API keys are not free, but must be acquired by purchasing them or providing data from a personal weather station. As of Sept 6, 2018 Weather Underground states they are declaring the End of Service for the Weather Underground API. They say they will develop new plans for non-commercial users. No timeline for this has been announced.

I'd link to the pricing for WUnderground, but I can't find that information. A [post on reddit](https://www.reddit.com/r/webdev/comments/8tjavu/now_that_the_free_wunderground_api_has_been/) links to a dead website.

**Comment by frenck** [comment]
Created a PR to improve/shorten the message.
