### ISSUE TITLE
No support for lupusec xt1 plus

### ISSUE THREAD

**Issue by allgrinder** [home-assistant/home-assistant.github.io#15994]
Hello HA community,

not sure, if this is the right place for my issue, but HA currently supports only the Lupusec XT1 alarm control panel. (https://www.home-assistant.io/integrations/lupusec/#configuration)

I bought the Lupusec XT1 Plus alarm control panel in the belief it would be working in combination with Home Assistant but it turns out to be not compatible with the current lupupy.

Thanks for all your good work

**Comment by frenck** [comment]
Hi there, thanks for reporting, but I'm unsure of the reason for opening an issue?
The system you mention isn't listed as supported by the integration. So...?

**Comment by allgrinder** [comment]
I was hoping that integration would be possible in the future.
While searching I found the following thread:
https://github.com/home-assistant/home-assistant.io/issues/8154

Sorry about the circumstances

Thanks and best regards
Allgrinder
