### ISSUE TITLE
Broken Sidebar Link in Nest Integration Documentation

### ISSUE THREAD

**Issue by danhood** [home-assistant/home-assistant.github.io#16029]
The [Nest Integration page](https://www.home-assistant.io/integrations/nest#setting-up-developer-account) has a sidebar link for a **Setting up developer account** section which is NOT present in the current version fo the page.  Furthermore, this step is referenced (by name, not a link) within the documentation itself ([under Device Setup](https://www.home-assistant.io/integrations/nest#device-setup)).  Looks like this heading was removed in 856377b76d5153dd929d3aa60c96d9ae0495fb00.

I assume the intent is still to reference the info where it was?  Though, I can't be 100% sure, as I can't get the Nest integration to work with an oauth fails with a vague "Something is Wrong" message on Google's end with nothing in HASS or Google Console logs (still debugging).

**Comment by frenck** [comment]
It is, in the bottom.

![image](https://user-images.githubusercontent.com/195327/103219056-fc8dde80-491c-11eb-857d-d7ef4c93f444.png)


Click to expand.

**Comment by danhood** [comment]
Ok, I missed that, but it's probably because the placement on the sidebar indicates the subsection is located under "Automation and Device Triggers" which it is not (still an issue in my opinion).  Additionally, the "Legacy Works With Nest API" heading doesn't show up, does it need to be rooted as a level 2 heading?

Edit: additionally, under "Device Setup" (under the non-legacy directions) it references that section as being above, but it is not.

**Comment by frenck** [comment]
Not an issue in my opinion, it is written in the introduction text as well. Hence I closed this issue.

**Comment by danhood** [comment]
I respectfully disagree.  I feel there are numerous related issues...

1. The (non-legacy) text references a section as being above in the narrative, when it is not.  Per your earlier comment, it's hidden behind a disclosure arrow in a section **below**, which is contradictory to what the text states.
2. The location of the navigation elements in the generated sidebar imply it's nested under a different section which it is not.
3. The Legacy API is missing altogether from the navigation sidebar (maybe due to incorrect markdown heading depth?).

I'm not bringing up these issues to be petty, but in looking through the forums there's a lot of confusion and missing steps (#15945) in the Nest integration instructions.  I feel that the broken references, dead navigation links, and missing navigation links likely (in part) contribute to the confusion.

**Comment by frenck** [comment]
The sidebar is generated, nobody creates those.

We don't have to agree.

**Comment by danhood** [comment]
I 100% get that the sidebar nav links are auto-generated.  

Not sure what that has to do with the narrative in the documentation being incorrectly worded (bullet 1)?  

I *think* the location in the link in the sidebar is a result of "Legacy Works With Nest API" being incorrectly scoped as a level 1 heading, vs. a level 2 (bullets 2 & 3).  It appears like that generation process may be ignoring level 1 markdown headings and picking back up with next heading greater than heading 1, thus resulting in "Setting up developer account" incorrectly being nested under "Automation and Device Triggers"?

If anyone is familiar with the process of how the markdown is generated can comment (or point me in the right direction), I'd gladly try make some edits myself and submit a pull request.

Edit: I located the [repo and website documentation docs](https://developers.home-assistant.io/docs/documenting/), will try to take a longer look this evening.

**Comment by danhood** [comment]
Looks like my hunch of level one headings being ignored is the case, thus the confusing generated TOC on the website.  Specifically, it appears as though the [defaults have been changed to ignore level 1 headings](https://github.com/home-assistant/home-assistant.io/blob/current/_config.yml#L156), as such a level 3 heading under the following level 1 heading is incorrectly generated in the wrong section.

Seems like the fix (at least to bullets 2 & 3) would be to change the "Legacy Works With Nest API" to be a level 2 heading, and then at least the sidebar navigation would be correctly generated.

**Comment by frenck** [comment]
The current generated site is not going to change for this single use-case. This is what it is at this point.

**Comment by danhood** [comment]
@frenck - by "generated site is not going to change" I assume you mean not adjusting the `min_level` in the `_config.yaml`?  If so, I agree - that makes sense (as there would likely be ripple effects beyond this one page), nor is it what I'm advocating.

But, I guess I'm struggling in understanding what you mean by "this is what it is at this point"?  Are you telling me to beat it, you don't care about the documentation enough to want someone to go down a path of fixing or improving it?  I can follow the steps for contributing (e.g. "Create a Pull Request (PR) against the current branch of home-assistant.io if you fix stuff, create Cookbook entries, or expand existing documentation."), but I'm getting the impression you simply don't care and/or will close the issue and deny a pull request related to addressing this?

For what it's worth, this is not an issue scoped to just a single page.  In looking through the markdown files and generated HTML (within integrations only, did not look beyond), the following page's TOCs are exhibiting issues as a result of incorrectly scoped headings in the markdown...

- [flume](https://www.home-assistant.io/integrations/flume/) (missing TOC entries)
- [lightwave](https://www.home-assistant.io/integrations/lightwave/) (missing TOC entries)
- [nest](https://www.home-assistant.io/integrations/nest/) (missing TOC entries, incorrect nesting of children)
- [opentherm_gw](https://www.home-assistant.io/integrations/opentherm_gw/) (missing TOC entries, nested children showing as top-level entries)
- [point](https://www.home-assistant.io/integrations/point/) (missing TOC entries)
- [time_date](https://www.home-assistant.io/integrations/time_date/) (missing TOC entries)
- [utility_meter](https://www.home-assistant.io/integrations/utility_meter/) (missing TOC entries)

Additionally, in going down this rabbit hole I've found another HTML generation issue / improvement that I could submit a PR against, but I don't want to waste time if it's not something that's interested in being addressed.

**Comment by frenck** [comment]
I'm saying your originally reported issue isn't valid in my eyes, thus not spending more time on this discussion.

**Comment by danhood** [comment]
@frenck - I was going to comment on your interactions, but you seem to openly acknowledge and flaunt it in the first part of your GitHub bio.  I feel I'm trying to engage to make Home Assistant documentation better - most people would have probably moved on in short order, but I persisted because I have been a long-time Home Assistant user, and wanted to contribute something, even if just corrections to the documentation.  I feel I've attempted to do so in constructive ways (e.g. offering to make the corrections myself and submit PRs), vs. the non-constructive complaints a lot of open-source projects regularly get.

While not egregious, I frankly feel your interactions are contrary to Home Assistant's published [Code of Conduct](https://github.com/home-assistant/home-assistant.io/blob/current/CODE_OF_CONDUCT.md).  I get the technical reasons one might not want to make a change, and I get if it's not of a significant enough of a scope for it to be on your radar, but I feel I've repeatedly tried to engage in constructive ways, and you've been nothing but closed and unwelcoming.  Even a response so basic along the lines of - sounds like there may be issues that have spun out of this, please submit new issues (ideally with an associated PR for consideration) - would have been more open/welcoming, and arguably more constructive for the larger community.

**Comment by frenck** [comment]
Sorry, @danhood I feel your first part of your last comment is out of line. Your original reported issue was a link not working, I've pointed you to the right location of that part of the documentation.

I feel like you are trying to open up a discussion because you feel like it, however, your original issue was marked as resolved, still you keep on going and stacking other things.

Feel free to open up a PR to make things better, however, your original reported issue was resolved as it was not an issue. If you feel like there are more issues, feel free to open issues containing single items, or feel free to open up a PR, that is always appreciated.

**Comment by danhood** [comment]
Please know that I was genuinely not trying to "open up a discussion because [I] feel like it".  We may disagree as to the  relevancy of the discussion that followed, but I genuinely felt the issues were directly related to the issue for which the ticket was opened.  Could I have worded the issue more precisely when initially submitted?  Perhaps - hindsight is 20/20.  But to some degree, I feel that's the nature of debugging - sometimes you believe something itself is an issue, but it's a side effect or manifests itself from something else.

I will attempt to submit several new issues to address the related underlying problems that led me to submit the issue in the first place as I have time to break out each into its own issue and PR.
