### ISSUE TITLE
SRP Daily / Hourly Issue

### ISSUE THREAD

**Issue by FedgarLurch** [home-assistant/home-assistant.github.io#16042]
The documents currently state:
"The SRP Energy integration shows information from SRP **hourly** energy usage report for their customers."

I created (and recreated for good measure) the integration with the SRP tool, and everything worked flawlessly (Thanks for that!)
The only problem is in the Developer tools, I am reading 32.70kWh for my hourly usage. When I go log into the online portal directly, that lines up with my daily usage. 
Personally, I would love to have hourly usage information, and I followed the trail of documents all the way to [this](https://srpenergy-api-client-python.readthedocs.io/en/latest/?badge=latest) page which clearly calls it out as hourly, but on my end, I am getting the daily usage. I am not sure if its a documentation issue, or if its actually acting up. 

Either way, I am happy to help in any way I can, and thanks everyone!

**Comment by frenck** [comment]
Hi there @FedgarLurch,

I suggest on creating an issue on the Core repository, so the integration code owner/maintainer can take a look at the actual content. At this point, I cannot be sure if it is a bug or a documentation issue.

Please, create an issue here: https://github.com/home-assistant/core/issues

Thanks and happy holidays!

**Comment by FedgarLurch** [comment]
Understood, sorry about the misplaced issue, I am still fairly unfamiliar to all of this. :)
Thanks Frenck, Happy Holidays to you as well!
