### ISSUE TITLE
Error in EvoHome Example

### ISSUE THREAD

**Issue by imellor** [home-assistant/home-assistant.github.io#16062]
## The problem

Last example on https://www.home-assistant.io/integrations/evohome/ 1 doesn’t work, line 222 “fault_type” should read “faultType”

Complete example reads:
`{% if state_attr('climate.bedroom', 'status').active_faults %}
  {% if state_attr('climate.bedroom', 'status').active_faults[0].fault_type == 'TempZoneActuatorLowBattery' %}
    There is a low battery
  {% endif %}
    There is a Fault!
{% else %}
  Yay, everything is OK :)
{% endif %}`

**Comment by frenck** [comment]
Thanks, @imellor!

That is indeed incorrect, opened up a PR to adjust it.
