### ISSUE TITLE
Remove Yi integration paragraph related to RTSP

### ISSUE THREAD

**Issue by astone123** [home-assistant/home-assistant.github.io#16070]
From the [Home Assistant Yi integration page](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/yi.markdown):

> Some alternative Yi firmwares enable an experimental RTSP server, which will allow you to connect to your camera via other Home Assistant camera platforms. However, this RTSP server disables the ability to use the supremely-useful Yi Home app. In order to maintain both Home Assistant compatibility and the native app, this platform retrieves videos via FTP.

Is this still true? I'm currently using a Yi Dome camera running [Yi Hack v4](https://github.com/TheCrypt0/yi-hack-v4). I have Home Assistant consuming the RTSP stream (so I am not using the Home Assistant Yi integration), but I can also still view and control the camera from the Yi Home app so I don't think that the paragraph above is true.

Am I missing something?

**Comment by frenck** [comment]
Yes, camera's could also still be running v3 versions or other versions. Thus, this is still true in some way.

**Comment by astone123** [comment]
I don't think Yi Hack v3 has an RTSP server option, but I suppose this could be true for some other versions that I'm not aware of. I'll close this out
