### ISSUE TITLE
RM4 Pro Sub Device Not Added as entities 

### ISSUE THREAD

**Issue by psyntium** [home-assistant/home-assistant.github.io#16105]
I’ve added the RM4 Pro Device on my HA (supervised). But the sub devices that I’ve setup on the Broadlink App on my iPhone are not added as entities. e.g.: Aircon and TV

**Comment by frenck** [comment]
Hi there @psyntium!

Thanks for opening on issue, however, this is the issue tracker for our documentation. It sounds like you are experiencing an issue with the integration in general and not a problem with out website.

If you want to report an issue with a Home Assistant Core integration, please create an issue here:

http://github.com/home-assistant/core/issues

Please be sure to fill out the presented issue template as much as possible.

Thanks! 👍
