### ISSUE TITLE
Broken link at http integration

### ISSUE THREAD

**Issue by N1co93** [home-assistant/home-assistant.github.io#16114]
## The problem

I just noticed that there is a broken link at the http integration: https://www.home-assistant.io/integrations/http/#apis
_There is also support for Server-sent events_

This link is pointing to https://developers.home-assistant.io/docs/external_api_server_sent_events/ This side was removed with this pull request https://github.com/home-assistant/developers.home-assistant/pull/508 Sadly there isn't any note if this site was moved or deleted completely.

I can create a PR, if you tell me if this site was moved or deleted.

**Comment by frenck** [comment]
Support for that has been removed.

**Comment by N1co93** [comment]
Closed, see #16117
