### ISSUE TITLE
Storage Minimum Requirement deceive people

### ISSUE THREAD

**Issue by GF-Huang** [home-assistant/home-assistant.github.io#16119]
![image](https://user-images.githubusercontent.com/4510984/103869246-07a6f280-5105-11eb-92f2-cc3eeb55fc14.png)

![image](https://user-images.githubusercontent.com/4510984/103869655-9582dd80-5105-11eb-8648-6d329bc40479.png)

The inaccurate documentation caused me to buy a new 64GB SD card. I had install the home-ass by docker and a lot of other things, less than 10GB of storage was used. My 16GB SD card just sits on the table and eats dust.

**Comment by frenck** [comment]
16 Gb is not enough. More space will be used over time. E.g., during upgrades it keep the old version, downloads a new version, extracts it, runs it in parallel and rolls back to the previous version if the upgrade failed.

But it is not just that, many more cases: Database growth, installation of add-ons and more of these things.

32 Gb is absolutely a minimum requirement to handle a system that is actually used.
