### ISSUE TITLE
Missing information why to use the Raspberry Pi Docker image.

### ISSUE THREAD

**Issue by MrDiba** [home-assistant/home-assistant.github.io#16239]
## The problem

When reading the documentation on how to install Home Assistant Core in Docker [(link)](https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/installation/docker.markdown) It is not clear to me why I should use the Raspberry Pi variant over the 'default' one. 

I would like to see some introduction to the RPi image as the [Docker Hub](https://hub.docker.com/r/homeassistant/raspberrypi4-homeassistant) has no information on the image as well. 

What is different between the images and why should I use the RPi image on a Pi as the other image works as well?

**Comment by frenck** [comment]
Isn't that clear from the naming? 

Those images are specifically made to have maximum compatibility and capabilities for these devices.

See for example <https://github.com/home-assistant/core/blob/dev/machine/raspberrypi4>

**Comment by MrDiba** [comment]
From the naming it is clear that there is a difference between the images. With the knowledge that Raspberry Pi OS == Linux I think it is a fair question to ask what the difference is between the two, especially because both images work. One could only assume that it is for optimization, but in my humble opinion assumptions in documentation are bad.

My suggestion would be to add the following to the installation instructions for Raspberry Pi OS:
"The Raspberry Pi Docker images are optimized to have maximum compatibility with a Raspberry Pi and do not functionally differ from the `homeassistant/home-assistant` images."

I would like to hear what you think of that.

_Off topic on my original question, but on the same page:_
I have the feeling that "Autostart using Docker" should not be located where it is now. I base this feeling on the fact that the "Platform installation" ends with a ":" and the Linux header a H3 is with no connection with the "Autostart using Docker" header. It should probably go somewhere around the "Restart" header.

**Comment by frenck** [comment]
I don't think that that addition is needed. The instruction clearly states it is instructions for the Raspberry Pi 3 and/or 4.

The other question feels a bit off-topic for here. Not sure about my opinion on it. I think if one uses Docker, one should have that knowledge and we should assume as such.
