### ISSUE TITLE
Numeric trigger description issue

### ISSUE THREAD

**Issue by kozerskil** [home-assistant/home-assistant.github.io#16256]
## The problem
Numeric trigger in the automation/trigger.markdown has this note:

> In the example above, the trigger would fire if a numeric_state goes to 17.1-24.9 (from strict above 17 and strict below 25).

while the example is:

>    above: 17
>    below: 25

As I understand, the note should say: 

> In the example above, the trigger would fire if a numeric_state goes to 17.1-24.9 (from non-strict below 17 or non-strict above 25).

**Comment by kozerskil** [comment]
Moreover, if I'm not wrong looking into the code: https://github.com/home-assistant/core/blob/de8f273bd09332dcda1206d925924570f48691f4/homeassistant/helpers/condition.py#L241
it should fire when the state changes inside the set, eg. 18->20.

**Comment by frenck** [comment]
Feel free to correct the error you see. Every page has an edit button, allowing you to suggest a change to our documentation 👍

**Comment by kozerskil** [comment]
Yes, I know, however there is one concern: I'm rather unexperienced HA user and it needs verification what I wrote 😄

**Comment by frenck** [comment]
That will happen, in a PR review.

**Comment by kozerskil** [comment]
Alright then.
