### ISSUE TITLE
Install dependencies cmd doesn't install python3.8

### ISSUE THREAD

**Issue by squirrd** [home-assistant/home-assistant.github.io#16291]
## The problem
The install dependencies cmd, [on this page](https://www.home-assistant.io/docs/installation/raspberry-pi/) doesn't install python3.8, which is now a requirement for homeassistant.

This was for Raspberry Pi OS v2020.12.04

The fix requires python v3.8.x to be complied, which seems overkill but easy enough done via this 
[raspberrypi stackexchange answer](https://raspberrypi.stackexchange.com/questions/116118/updating-python-3-7-to-3-8).

This is probably only required until Raspberry Pi OS catches up with Python releases, but placed me in a tailspin for a while.

I am happy to raise a PR for this but this will be my first ever PR.  Any guidence on procedure and process would be helpfull?

Also my recomeded change would be to leave the current pre-requisites in place and then test for python3.8 (I assume RPi will catchup sometime and the "if" will not be required).  If test fails, then, ask the reader to perform the addidnal pre-requisite steps (to be included in the PR) simialr to whats in the stackexchane post above.

Since I am new I am not sure if this would meet your requirements.

**Comment by frenck** [comment]
> which is now a requirement for homeassistant.

It isn't right now, it will be as of Core version 2021.2.0.

Running Python itself is not a direct concern for our project. As in; if you choose to run an installation type directly on Python, we will assume you know your way around. For that matter, we need to clean out some docs in general.

If you don't want that level off fuss, we offer multiple other installation types, to which we provide a Python version that works.

**Comment by squirrd** [comment]
Ok technically, I was wrong based on.

> It isn't right now, it will be as of Core version **_2021.2.0_**.

But if I take this log entry at its word... 

> Support for the running Python version 3.7.3 is deprecated and will be removed in the first release after December 7, 2020. Please upgrade Python to 3.8.0 or higher.

Since we are at release 2021.1.5 (released 23 Jan 2021) then we are in unsupported territory.

Its fine I get your point about needing to be technically savvy to install Core.  I am just seeing it with fresh eyes and was offering to make it a bit less bumpy for someone to install the first time.  I was also of two minds if it was a good idea or not.

I will close this.  Thanks for the feed back.
