### ISSUE TITLE
Auto Discovery Documentation Error

### ISSUE THREAD

**Issue by adumbrow** [home-assistant/home-assistant.github.io#16303]
## Documentation Error
`SetOption19 0` should read `SetOption19 1` to turnon autodisovery.

**Comment by frenck** [comment]
Could you add some context?  Which option? What integration? Which page?
Where?

Alternative, you could suggest an edit on each page, but clicking on the "Edit this page on GitHub" link that is shown on top of each page.

**Comment by adumbrow** [comment]
Apologies it was the Tasmota Integration.  I submitted a pull request so I will close this out.
