### ISSUE TITLE
Xiaomi documentation

### ISSUE THREAD

**Issue by AalianKhan** [home-assistant/home-assistant.github.io#16312]
## The problem

I am opening this issue as I am not sure if this was intentional or not. 

I think the documentation of the Xiaomi devices is a bit cluttered with either too many useless pages or too much information on 1 page which makes it hard to find what you need. 

To start out, when you search Xiaomi in integrations, the first result is a camera integration with not 1 word in the title portraying that its camera integration. 
Next, I want to talk about all the excess amount of pages that link to the Aquara gateway guide. If I own an Aquara hub that controls my lights then I will be probably looking for an integration that connects to my hub. These pages get useless as they just become a middle man and doesn't add much information except for the Binary sensor one. Moving on to the Mi app integration. This page is way too long and has too much information in one page where one can get easily lost and makes it hard for the user for what it's looking for. I suggest breaking it up as they are different integrations similar to how the MQTT documentation has it. 
I am willing to help but I am not sure if I was going the right way so I wanted some input from you guys.

**Comment by frenck** [comment]
Well, I agree, it is a mess.
What needs to happen is that the individual platform pages need to be consolidated in a single integration page. As that is the approach we are slowly moving towards: 1 page per integration.

Feel free to hit the edit links, that is listed on top of each page, to suggest edits.

**Comment by AalianKhan** [comment]
Gotcha,
So the Mqtt integration also needs to be reworked?

**Comment by frenck** [comment]
Yup. Back in the day, every integration had its own pages for each light, camera, switch (and whatever more). Most of them have been consolidated.
