### ISSUE TITLE
RFLink missing info for mortal users

### ISSUE THREAD

**Issue by JulianGro** [home-assistant/home-assistant.github.io#16354]
## The problem
The RFLink documentation at https://www.home-assistant.io/integrations/rflink/ is missing information that a "mortal" user doesn't necessarily have.

There is no information on how to find out what your devices name is. In my case it was easy to find out because it had `arduino` in `/dev/serial/by-id/`.

The [adding devices automatically](https://www.home-assistant.io/integrations/rflink/#adding-devices-automatically) section contains following code, but doesn't tell you where to put it.
```
light:
  - platform: rflink
    automatic_add: true
sensor:
  - platform: rflink
    automatic_add: true
```
This code seems to just go into the configuration.yaml outside of `rflink:`

The documentation tells you that you can change the configuration of a device, but doesn't tell you how you would do that. Personally I have no idea where I would configure this, since the UI doesn't allow changes to those entities and doesn't remember them across restarts.
```
However, once the ID of a switch is known, it can be used to configure it as a switch or a binary sensor type in Home Assistant, for example, to add it to a different group or configure a nice name.
```

**Comment by frenck** [comment]
> The adding devices automatically section contains following code, but doesn't tell you where to put it.

That is part of the getting started guide:

<https://www.home-assistant.io/getting-started/configuration/>

> There is no information on how to find out what your devices name is. In my case it was easy to find out because it had

That is correct, there isn't any. It can be any identifier. 🤷

**Comment by JulianGro** [comment]
> That is part of the getting started guide

The other code blocks say ``# Example configuration.yaml entry`` which would be helpful in this case as well.

**Comment by frenck** [comment]
Right! That might be helpful indeed!

You can suggest an edit for each page you come across, there is an edit link on top of each page.

**Comment by JulianGro** [comment]
> The documentation tells you that you can change the configuration of a device, but doesn't tell you how you would do that. Personally I have no idea where I would configure this, since the UI doesn't allow changes to those entities and doesn't remember them across restarts.
> 
> ```
> However, once the ID of a switch is known, it can be used to configure it as a switch or a binary sensor type in Home Assistant, for example, to add it to a different group or configure a nice name.
> ```

Only question would now be how this is supposed to work. Cannot suggest a documentation change if I don't have any idea how it is supposed to work ;)
