### ISSUE TITLE
Menu covers content when browser window is wide enough

### ISSUE THREAD

**Issue by skullydazed** [home-assistant/home-assistant.github.io#16350]
## The problem

My browser windows are normally ~ 2370x2200 (retina, so 1185x1100) and this puts the homeassistant site into a mode where the menu covers content.

<img width="1298" alt="Screen Shot 2021-01-29 at 07 57 18" src="https://user-images.githubusercontent.com/9553982/106299273-d7390c80-6209-11eb-9ebc-d6f35815e1da.png">

If I shrink the window by a few pixels to ~2350x2200 the menu collapses into the hamburger and everything displays correctly.

<img width="1287" alt="Screen Shot 2021-01-29 at 07 57 25" src="https://user-images.githubusercontent.com/9553982/106299453-064f7e00-620a-11eb-955e-e15b8b12dcef.png">

**Comment by skullydazed** [comment]
This is still an issue for me, now on Chrome Version 89.0.4389.90 (Official Build) (x86_64). In case it's not obvious in the first screenshot the navigation menu is shown between the first two lines of text, and remains fixed relative to the window frame as the content scrolls.

**Comment by ludeeus** [comment]
Correct @skullydazed (which is why I removed the label and assigned it to me :smiley:  )

**Comment by skullydazed** [comment]
Unfortunately github only sends an email for comments and I missed that before posting, but am glad to see you're on it. :)
