### ISSUE TITLE
Confusing Pi instructions?

### ISSUE THREAD

**Issue by Jc2k** [home-assistant/home-assistant.github.io#16376]
## The problem

I was reviewing https://www.home-assistant.io/docs/installation/raspberry-pi/ as part of https://github.com/home-assistant/architecture/issues/476. I think that page is potentially confusing. The way I read it is:

* This installation method for Home Assistant Core is based on Raspberry Pi OS Lite.
* Instructions assume a new installation of Raspberry Pi OS Lite
* You must have Python 3.8. This is not the case on Raspberry Pi OS. You must install it manually. (This is not documented)
* `apt install python3` <- proceed to install python 3.7

The guide is on the premise that Raspberry Pi OS Lite does have a modern version of python, when it does not. The docs gained a warning to cover this, but the docs as they are written are not applicable any more. At least not to Raspbian.

I would submit a PR but i'm not really sure how to address this conflict in a satisfactory way:

* We shouldn't be supporting users compiling python 3 from scratch
* Most of the guide would be fine if we used Ubuntu 20.04 as a base. We could make a generic Ubuntu 20.04 virtualenv guide and ditch Raspberry Pi specific advice. But there are a lot of raspbian users I think.
* We could just delete the page. If you can't make this work you really should use Home Assistant OS.

**Comment by frenck** [comment]
> We could just delete the page. If you can't make this work you really should use Home Assistant OS.
> Most of the guide would be fine if we used Ubuntu 20.04 as a base. 

I think we should remove all about installing Python. Installing Python is not our responsibility, nor or expertise or problem.

> apt install python3 <- proceed to install python 3.7

That depends on your system even... might be Python 3.6? 😄 

There are many ways to run Python, its up to the user to decide. If one lack the technical knowledge on running Python, running another installation method is recommended.

Considering that, it should be a matter of slimming down the page.

As a side note: There is a draft PR open to refactor all setup pages

**Comment by Jc2k** [comment]
That sounds like a good approach!
