### ISSUE TITLE
Confusing documentation location

### ISSUE THREAD

**Issue by dgomes** [home-assistant/home-assistant.github.io#16390]
## The problem

Documentation about `choose` lies under `script`:

https://www.home-assistant.io/docs/scripts/#choose-a-group-of-actions

Shouldn't it be under `automations` ?

**Comment by frenck** [comment]
Nope, it is a script.
None of the script features are documented with automations.

**Comment by dgomes** [comment]
I found it confusing because the example clearly shows its use in an automation... but I'm OK

**Comment by frenck** [comment]
automation and scripts are the same. The trigger syntax is different (well automations have a trigger syntax) but it doesn't change the script.

In the end, an automation is wrapping a script.
