### ISSUE TITLE
Tesla powerwall integration and sensors not working

### ISSUE THREAD

**Issue by zinoalex** [home-assistant/home-assistant.github.io#16471]
Tesla Powerwall integration (https://www.home-assistant.io/integrations/powerwall/) stopped working since HA version 2021.2.1.
Calls made via the GET method described by Tesla API still works but in HA the entities show Unavailable.
Any one else with the same issue?

**Comment by frenck** [comment]
Hi there @zinoalex!

This is the issue tracker for the Home Assistant website. In case you have issues with the Home Assistant Core integration check this issues tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍
