### ISSUE TITLE
CrimeReports Integration: should it be removed?

### ISSUE THREAD

**Issue by peterhajas** [home-assistant/home-assistant.github.io#16481]
**Feedback**

Based on the comments in #30598, it looks like the Crime Reports API may have been removed:

https://www.govtech.com/biz/Motorola-Parts-with-Socrata-Ends-Access-to-Open-Crime-APIs.html

Based on this, should the Integration be removed or deprecated? I added the sensor to my HA setup, and I'm seeing the same SSL errors. I can't hit the endpoint and get valid crime JSON.

**URL**

https://www.home-assistant.io/integrations/crimereports/

**Version**

2021.2.2

Here's the SSL error I'm seeing:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.crimereports.com', port=443): Max retries exceeded with url: /api/crimes/details.json?...
```

(details redacted)

**Comment by frenck** [comment]
Issues on the core repo:

<https://github.com/home-assistant/core/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22integration%3A+crimereports%22+is%3Aclosed>

No issues on the upstream package: <https://github.com/happyleavesaoc/python-crimereports>

**Comment by frenck** [comment]
Both used resources in the upstream library are indeed dead:

https://github.com/happyleavesaoc/python-crimereports/blob/b29df8b8df3b2d33306f133cf94dd57047449a46/crimereports/__init__.py#L10-L11

https://www.crimereports.com/home/#!/dashboard
https://www.crimereports.com/api/crimes/details.json

**Comment by peterhajas** [comment]
That was quick, thank you for the speedy response and fix!

**Comment by frenck** [comment]
Thanks for reporting ❤️
