### ISSUE TITLE
Dual Mode for dual mode AC units doing heating and cooling

### ISSUE THREAD

**Issue by brizoo** [home-assistant/home-assistant.github.io#16487]
**Feedback**

Hi team,

I have an air conditionner heat pump "Daikin" which is composed of two AC units in my house. 
Both AC units is "reversible" that means it can heat or cool. 
During winter, I heat the house like a normal heater since I do not have anything else to heat the house. 
But during summer, I cool the house when it's too hot. 

The problem with the thermostat is that I need to use two of them in order to manage one single physical unit... It seems not logical. 
I have tried to use dual mode generic custom thermostat integration (https://github.com/zacs/ha-dualmodegeneric), but then the problem is that I can't dynamically set the "away_temp" value of the thermostat. 
During winter or winter in heating or cooling mode, the Away Temps would be a lot different. 

So please let me know if it would be possible or not! 
Thanks

**URL**

https://www.home-assistant.io/lovelace/thermostat/

**Version**

2021.2.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
