### ISSUE TITLE
Flux led not visible in list of integrations

### ISSUE THREAD

**Issue by gijssenh** [home-assistant/home-assistant.github.io#16497]
**Feedback**

According to the description Flux_led should be visible in the list of integrations but it isn't actually. Maybe this is a matter of time? With kind regards. Herman

**URL**

https://www.home-assistant.io/integrations/flux_led/

**Version**

2021.2.2

**Comment by JOHLC** [comment]
Noticed the same here
Had to dig through the change history to figure out how to config via yaml 

Running 2021.2.3
![image](https://user-images.githubusercontent.com/63735432/108007401-ea9af480-6fcb-11eb-8687-9b9e34544cf3.png)
![image](https://user-images.githubusercontent.com/63735432/108007411-f090d580-6fcb-11eb-8a88-d8738c9d2323.png)

**Comment by CRZTFR** [comment]
Hi @JOHLC, any chance you could post your configuration or a link to the old docs? I'm struggling to find them.

**Comment by JOHLC** [comment]
@CRZTFR [here you go](https://github.com/home-assistant/home-assistant.io/commit/b96f3ee6cf0c7fbca6dd4b65509558fef0e6a7da#diff-9774444ece91fb49e198f3cdbfe83149104c86463dc0042abb3a3f4762886c8a)

Example:

````
light:
  - platform: flux_led
    devices:
      192.168.3.33:
        name: Joels desk LEDs
        mode: rgb
````

**Comment by GForceWeb** [comment]
Also experiencing this issue. 

I tried using the manual configuration example @JOHLC provided switching the IP address to the correct IP for my own setup but the device still doesn't appear in HA

EDIT: Nvm, I can now see the entity after updating HA. I do see the "This entity ("light.magichomestrip") does not have a unique ID" message though in HA, not sure how to resolve that but at least I can control the strip

**Comment by mimainka** [comment]
Also included my MagicHome LED Controller manually like mentioned. However, anyone got functions like strobe including changing speeds of it running?

**Comment by ldoench** [comment]
When the config flow is broken, should the manual method not be added to the wiki?

**Comment by sankarnair123** [comment]
how do you specify multiple devices ?
i still dont see it in devices or entities page 

for example will this work for specify 4 devices as follows ?

light:
  - platform: flux_led
    devices:
      192.168.86.77:
        name: BookShelf1
        mode: rgb
      192.168.86.71:
        name: BookShelf3
        mode: rgb
      192.168.86.67:
        name: BookShelf4
        mode: rgb
      192.168.86.76:
        name: BookShelf2
        mode: rgb

**Comment by iMrLopez** [comment]
Integration is still not present in UI, got it to work with manual setup in the configuration files

**Comment by iMrLopez** [comment]
If you are having problems with this please have a look at these links: I got it to work after reading here:

https://community.home-assistant.io/t/flux-led-magiclight-dont-work-since-few-updated/145179/71
https://community.home-assistant.io/t/fixed-flux-led-does-not-set-brightness-or-color-correctly-when-device-is-initially-off/157578/2

**Comment by Kenny-BC** [comment]
Can someone explain how to integrate a flux_led manually? 

With the manual setup it didn´t work
