### ISSUE TITLE
Telegram bot timeout unit missing

### ISSUE THREAD

**Issue by naitsimp** [home-assistant/home-assistant.github.io#16494]
**Feedback**

The unit of Service data attribute "timeout" is missing. Would be helpful if someone can add the unit. I am actually not sure which unit it is. 
Change the timeout Description to, if the timout is in seconds. For example: "Timeout in seconds for send photo. Will help with timeout errors (poor internet connection, etc)"

**URL**

https://www.home-assistant.io/integrations/telegram_bot/

**Version**

2021.2.2

**Comment by frenck** [comment]
Thanks! opened up a PR to correct it 👍
