### ISSUE TITLE
Benchmark page should be removed

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#16498]
**Feedback**

I think this page is generally more interesting for developers when changing code that affects performance. For the end-user, these values don't tell much.

**URL**

https://www.home-assistant.io/docs/tools/benchmark/

**Version**

2021.2.2

**Comment by klaasnicolaas** [comment]
Anyone already picked this up? Otherwise, I will handle this issue 😄

**Comment by frenck** [comment]
Go ahead @klaasnicolaas, just do it 🕺
