### ISSUE TITLE
Unclear mapping of remote media sources

### ISSUE THREAD

**Issue by michael-gaudet** [home-assistant/home-assistant.github.io#16504]
**Feedback**

From this page it's unclear how, or if, you can map media sources that aren't local to the Home Assistant host. 

Also, the "media source" is listed on this page as an Integration, but it doesn't appear in the list of integrations that are searchable within the Home Assistant => Configuration => Add Integration list (at least, in the latest version as of 2021/02/10). I've added a number of custom integrations to HA but the Media mapping is still very confusing.

**URL**

https://www.home-assistant.io/integrations/media_source/

**Version**

2021.2.2

![Capture](https://user-images.githubusercontent.com/6947456/107570835-1119f380-6bb8-11eb-8f29-af5a75365168.PNG)

Media Source does not appear in the Integrations lookup at all. I assume it was migrated into the core functionality in previous versions but the documentation does not make that clear.

**Comment by jlsjonas** [comment]
Also (still) wondering about this.

Pinging @hunterjm as they are mentioned as code owner above

**Comment by frenck** [comment]
Media source isn't UI configurable, configuration instructions are on the page linked/given feedback on.

Media folder/sources added, are local paths. How these local paths are mounted (remote or not) is not a concern for Home Assistant itself. I'll adjust the documentation to make that more clear.

**Comment by jlsjonas** [comment]
With plex integration I expected some form of search/list to query items to play (as part of a home panel, to quickly broadcast something to my tv that I know by (part of) name)
Does this mean the plex integration is limited to exact queries, i.e. you'd practically be limited to playing your favorite song/movie(s) from it only?

**Comment by frenck** [comment]
That can be done, but it is up to the plex integration to handle that. This is not limited or provided by the media sources integration.
