### ISSUE TITLE
Note about openweathermap API key activation

### ISSUE THREAD

**Issue by xorbital** [home-assistant/home-assistant.github.io#16509]
**Feedback**

When setting up a new openweathermap account, the generated API key takes some considerable time to get set up:
> Your API key will be activated automatically, between 10 minutes and 2 hours after your successful registration.
From: "Do I need to activate my API key" at https://openweathermap.org/faq

I think there should be a note on the integration page or the integration itself about that since currently you'll just get an error saying that your API key is invalid.

**URL**

https://www.home-assistant.io/integrations/openweathermap/

**Version**

2021.2.2

**Comment by fabaff** [comment]
Nobody complained so far about this issue.

**Comment by frenck** [comment]
Would it harm to add it?

@xorbital Did you run into this issue?

**Comment by xorbital** [comment]
@frenck Yes, I did. I created an account, pasted the API key into Home Assistant (even created a new one) but neither of them worked for about 20 minutes.
I get that this isn't really a Home Assistant issue, openweathermap should add a note to their API key section instead of burying it in their FAQ, but I guess we can only improve the situation by including a few words on the docs here. Doesn't even need to be a yellow box.
We could change
> You need an API key, which is free, but requires a registration.

into
> You need an API key, which is free, but requires a registration. API keys may take up to two hours to get activated after registration.

**Comment by fabaff** [comment]
> Would it harm to add it?

No, 20 min wait time is very long as most user will think that it happens within minutes.

**Comment by st-sha** [comment]
I am having this issue right now - consider this an additional "complaint" :)

**Comment by emericklaw** [comment]
I have also just had this issue after setting up an account.

They do mention it in the second welcome email but I did not open that until seeing this issue.

>Thank you for subscribing to Free OpenWeatherMap!
>
> API key:
> - Your API key is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> - Within the next couple of hours, it will be activated and ready to use
> - You can later create more API keys on your account page
> - Please, always use your API key in each API call
