### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by kraaidelft** [home-assistant/home-assistant.github.io#16502]
**Feedback**

If openweathermap shouldn't be configured in the yaml file, where shoud I change the monitored conditions or a changed password. It can't be done in the Lovelace interface.

**URL**

https://www.home-assistant.io/integrations/openweathermap/

**Version**

2021.2.2

**Comment by frenck** [comment]
The OpenWeatherMap integration uses a configuration flow, and can only be set up via the UI, as written on this page:

![image](https://user-images.githubusercontent.com/195327/107562922-b34dd180-6be0-11eb-92ff-dfe952c60581.png)>

Monitored conditions are something that is being slowly removed from Home Assistant. It is a leftover from the old days and is slowly phased out.

If you want to disable an entity you don't want to track/keep, you can do so by going into the UI -> Configuration panel -> Integration -> Click the integration you like to change. You can disable either individual devices or individual entities you are not interested in.


![image](https://user-images.githubusercontent.com/195327/107563184-09227980-6be1-11eb-8fd9-de40d0da0939.png)

A password change should be detected by integration and offer the possibility to re-authenticate (or a re-add can do the trick). But that is general across our integrations and not specific to this integration.

I think that actually covers your feedback already, with the current documentation. Or, I am misunderstanding it @kraaidelft?
