### ISSUE TITLE
Not connected to Dyson account. Unable to add devices

### ISSUE THREAD

**Issue by kritin81** [home-assistant/home-assistant.github.io#16512]
**Feedback**

Today I restarted Home assistant, after which the Dyson no longer works. Which I didn't make any configuration changes, which before I restarted Dyson still worked fine. I'm not sure what the problem is.

**URL**

https://www.home-assistant.io/integrations/dyson/

**Version**

2021.2.3

<img width="1552" alt="Screen Shot 2564-02-12 at 00 45 34" src="https://user-images.githubusercontent.com/71565294/107676365-a22dbf00-6ccb-11eb-9316-588e2004ea88.png">
<img width="1552" alt="Screen Shot 2564-02-12 at 00 46 23" src="https://user-images.githubusercontent.com/71565294/107676460-bffb2400-6ccb-11eb-903f-f1abd3935b26.png">
<img width="962" alt="Screen Shot 2564-02-12 at 00 47 49" src="https://user-images.githubusercontent.com/71565294/107676797-21bb8e00-6ccc-11eb-8404-12f213de2f6e.png">

**Comment by frenck** [comment]
I'm not sure, seems like you are reporting a bug with the Dyson integration?

**Comment by frenck** [comment]
Aah I see, this is an issue/bug with the Home Assistant integration. As shown at the top of the feedback form you have filled in for this; those should not be reported here.

However, someone already raised an issue on our Core repository for this integration, you can track it here: <https://github.com/home-assistant/core/issues/46400>
