### ISSUE TITLE
Installation linux

### ISSUE THREAD

**Issue by john-clark** [home-assistant/home-assistant.github.io#16519]
**Feedback**

I followed these instructions 
https://www.home-assistant.io/installation/linux

I downloaded the qcow2 image, booted this image on my proxmox installation and created the web account.

I can not log into the console with the account I created, there is no account information provided.

There is no information provided to how this image is built, how it works, what it contains, or how to keep the underlying os updated.

**URL**

https://www.home-assistant.io/installation/linux/

**Version**

2021.2.3

**Comment by frenck** [comment]
Common tasks on how to update can be found here:

<https://www.home-assistant.io/common-tasks/os/>

The image is based a firmware-based Linux distribution. Therefore, there is not much to explore on the commandline. Logging in via the console is not its use case. You can login if you want, the user is `root`, no password. 

The account created in the Home Assistant web interface is not related to the OS in any way.
