### ISSUE TITLE
Looks like using Smartthings as a Z-wave hub dosent provide all data?

### ISSUE THREAD

**Issue by casperse** [home-assistant/home-assistant.github.io#16523]
**Feedback**

Example: All my Fibaro Smart plugs - can not show any power consumption in HA using the Smartthings integration
I checked this list before buying a "Z-wave hub"now I now have to buy a new Z-wave controller for HA :-(

**URL**

https://www.home-assistant.io/docs/z-wave/controllers/

**Version**

core-2021.2.3

**Comment by frenck** [comment]
Every method of integration provides pro's and con's.

If you have a feature request for improving an integration, please create a topic on our community forum. E.g., A request for adding power consumption data from Fibro Smart Plugs when used via the SmartThings Integration.

As for an item to provide feedback on improving the documentation: There is no much I can do with this. It is documented correctly.

**Comment by casperse** [comment]
Shouldn't it be a note that for full Z-wave integration you need a USB adapter directly in HA?
Right now the two options a proposed as equal
