### ISSUE TITLE
Bad link in RPi HassOS installation page

### ISSUE THREAD

**Issue by DLHN-cz** [home-assistant/home-assistant.github.io#16529]
**Feedback**

in RPi HassOS installation page (https://www.home-assistant.io/installation/raspberrypi), chapter "WRITE THE IMAGE TO YOUR INSTALLATION MEDIA", point 4 (Get the URL for your Raspberry Pi:), there's a bad link for RPi3-32bit image:

https://github.com/home-assistant/operating-system/releases/download/5.11/hassos_rpi-5.11.img.xz

... instead of:

https://github.com/home-assistant/operating-system/releases/download/5.11/hassos_rpi3-5.11.img.xz

It took me at least 1 hour of re-downloading and re-flashing before I figured out ;)

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by ludeeus** [comment]
Thanks for the feedback, I have opened a PR to adjust this.
