### ISSUE TITLE
The Network Manager lacks info how to do what it is asking.

### ISSUE THREAD

**Issue by Rbroughton007** [home-assistant/home-assistant.github.io#16534]
**Feedback**

The Network Manager page in 'The Solution' says to "update the Network Manager on the host" but then fails to say how to do that update. I have terminal/web addon installed and there is no apt-get or any way I can see to 'update Network Manager'. More details of how to update the Network Manager would be extremely helpful. 

**URL**

https://www.home-assistant.io/more-info/unsupported/network_manager/

**Version**

2021.2.3

![image](https://user-images.githubusercontent.com/57209363/107825724-dc857380-6d40-11eb-92f6-05a7c29ea418.png)

**Comment by frenck** [comment]
That sounds somewhat correct. Could you provide the output of `ha info` of your system?

**Comment by Rbroughton007** [comment]
I did a ha repair. Here is the screen shot of ha info:
![image](https://user-images.githubusercontent.com/57209363/107827573-40f60200-6d44-11eb-9c4e-c7da6c38924e.png)

**Comment by Rbroughton007** [comment]
Using the ssh/web terminal addon, I did the following commands:
ha repair
ha supervisor restart
ha net update
They all completed successfully and the network updated.

Perhaps on the Network Manager page, include the ssh/web terminal addon part with the appropriate ha commands you feel are best. 

Thanks for your assistance in constantly making this a better platform.
