### ISSUE TITLE
How to correctly stop (switch off) Home Assistant

### ISSUE THREAD

**Issue by ChrigouTav** [home-assistant/home-assistant.github.io#16538]
**Feedback**

You should explain how to correctly stop Home Assistant and how to correctly switch off the Pi.
I did not find any information in the doc and it's very difficult to find something in the community forum.

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by frenck** [comment]
Good question! I guess in general, we kinda assume a Home Automation system is always on 😉 

Which installation method are you referring to in this case?

**Comment by ChrigouTav** [comment]
I refer to the last version of HA for my Raspberry Pi 3 model B downloaded from here:
[www.home-assistant.io/installation/raspberrypi](https://www.home-assistant.io/installation/raspberrypi)
The problem is how to stop the Rasberry Pi because just switch off the power may break the SD card.

**Comment by frenck** [comment]
Yes, but the page describes 3 different installation methods, the question was, which of those 3 methods did you use?

**Comment by ChrigouTav** [comment]
I used the first one:
Install Home Assistant Operating System

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/107848892-81628800-6df7-11eb-8a79-af2b51a40eb6.png)

Supervisor -> System.

I can see the confusion, we should indeed at an entry to the common tasks: <https://www.home-assistant.io/common-tasks/os/>

**Comment by ChrigouTav** [comment]
Ah OK, thanks, I did not see this page as I'm very new user to HA :-)
A link to this page from the Installation Process Page URL will be welcome.
