### ISSUE TITLE
Install Home Assistant Operating System

### ISSUE THREAD

**Issue by buffeh** [home-assistant/home-assistant.github.io#16531]
**Feedback**

URL: https://www.home-assistant.io/installation/raspberrypi

"Section 4. Get the URL for your Raspberry Pi:" has what I think is an error.

The link for "Raspberry Pi 3 32-bit" is "https://github.com/home-assistant/operating-system/releases/download/5.11/hassos_rpi-5.11.img.xz" - this is not consistent with the other file names that have a 3 or a 4 as appropriate for the Raspberrry Pi hardware. When flashed to my Raspberry Pi 3, this does not work (red light, file system not recognised). 

I went to the list of available releases (https://github.com/home-assistant/operating-system/releases/tag/5.11) and noted that there was a hassos_rpi3-5.11.img.xz so I downloaded this instead of hassos_rpi-5.11.img.xz and that worked perfectly.

I assume the file without the number in the name is for an older raspberry pi and the 3 just got missed off of the file name in the tutorial. Please fix this so other people don't spend 3 hours, multiple SD cards, and multiple flashing / formatting programs trying to sort this, like I did :(

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by ludeeus** [comment]
A fix for that was merged 4 minuttes ago <https://github.com/home-assistant/home-assistant.io/pull/16530> and the site is currently building.
Thanks for reporting :+1:
