### ISSUE TITLE
APCUPSD Integration Depends an unofficial add-on

### ISSUE THREAD

**Issue by akinomeroglu** [home-assistant/home-assistant.github.io#16542]
**Feedback**

Hi,

This integration depends unofficial add-on. The unofficial add-on repo is archived and there is redirection for hassio-addon. 

So I believe that we need to remove this integration or update the documentation. I can't be sure what is the proper approach so I decided to open an issue. I can create a PR for documentation update or removal.

Regards,

**URL**

https://www.home-assistant.io/integrations/apcupsd/

**Version**

2021.2.3

**Comment by frenck** [comment]
I think the paragraph can simply be removed. Feel free to open a PR for it to do so 👍

**Comment by frenck** [comment]
This has been resolved 👍 

Thanks for providing feedback!
