### ISSUE TITLE
Input Boolean Example

### ISSUE THREAD

**Issue by Noodleheader** [home-assistant/home-assistant.github.io#16548]
**Feedback**

Noob here, trying to learn and having trouble understanding how to configure an input_boolean without a clear example of how to craft it.  I see how to use it in an automation, but the example is too simplistic to get a sense for how to configure it.  I cannot infer just from the service listing.

More general feedback: I am not a programmer, engineer, or other professional techie.  I am just a nerd with a willingness to put in the work now so I can be lazy later.  This means I had to figure out how to use GitHub (still mostly clueless), I barely have a clue about Python, and so on.  I know you're all still working on this and it is utterly fantastic what has been created, however, I recommend upgrading or adding to the welcome content.  There are currently many assumptions about a person's skills that leave a pretty high hurdle for those just starting out...or maybe I missed something. 

Thank you!!!
Louis

**URL**

https://www.home-assistant.io/integrations/input_boolean/

**Version**

2021.2.3

**Comment by balloob** [comment]
I suggest to use the UI if YAML is too difficult

**Comment by frenck** [comment]
Reviewed the docs for this page. I think there are some small tweaks possible, but in general, it describes the manual / more advanced usage.

As suggested above (and in the documentation as well), if that is not comfortable for you, use the UI instead.
