### ISSUE TITLE
Heiman Siren

### ISSUE THREAD

**Issue by Gordan74** [home-assistant/home-assistant.github.io#16540]
**Feedback**

Dear all,
How can I activate Heiman Siren?
I see it as light and is set to "area" that I called alarm.
I saw on  page: https://www.home-assistant.io/integrations/deconz/
tat this device is supported.
I have ConBee II USB on HA.
Please help me...
Best regard,
Gordan Dinter

**URL**

https://www.home-assistant.io/integrations/deconz/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by Gordan74** [comment]
Will do!
Thanks and sorry for spamming wrong channel.
Best regards,
G

**Comment by frenck** [comment]
Don't worry! I hope you find an answer to your question 👍
