### ISSUE TITLE
generic thermostat documentation

### ISSUE THREAD

**Issue by xog64** [home-assistant/home-assistant.github.io#16547]
**Feedback**

What are the following steps after the generic thermostat entry is added in configuration.yaml?

**URL**

https://www.home-assistant.io/integrations/generic_thermostat/

**Version**

2021.2.3

**Comment by ludeeus** [comment]
Like any other change to YAML configuration, restart Home Assistant?
Or were you thinking of something else?

**Comment by xog64** [comment]
Yeah, I didn't restart home assistant properly.
I suggest to add "Restart Home Assistant after configuration.yaml has changed" as new users of HOAS can jump in this page and modify configuration.yaml for first time.
Thank you

**Comment by ludeeus** [comment]
<https://www.home-assistant.io/docs/configuration/#reloading-changes> That already exists under the main documentation for configuration.

**Comment by frenck** [comment]
I think it is reasonable to say, we cannot include a complete Home Assistant tutorial on each page (although I do understand the suggested reasoning).

Closing this suggestion for that reason.
