### ISSUE TITLE
Where is the WIFI setup documentation for the rashberry pi?

### ISSUE THREAD

**Issue by MBousss** [home-assistant/home-assistant.github.io#16555]
**Feedback**

Where is the WIFI setup documentation for the rashberry pi?

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by frenck** [comment]
This page lists 3 different setup methods, which one are you referring to?

That asked, of course running Wi-Fi is not recommend for something that is designed to control things in your home and run permanently 😉

**Comment by gwhiteCL** [comment]
None of the three setup methods on that page show any WiFi config info that I can find.

I'm also looking for Raspberry Pi WiFi configuration information (HassOS for me).

**Comment by MBousss** [comment]
> This page lists 3 different setup methods, which one are you referring to?
> 
> That asked, of course running Wi-Fi is not recommend for something that is designed to control things in your home and run permanently wink

At this moment it is only for testing. About a month ago I already tried Home Assistant at that time there was info about WiFi configurations on setup.

**Comment by frenck** [comment]
Network settings are available from the UI for the OS. Supervisor panel -> System tab. If you edit the network there, you can set all kind of things:

![image](https://user-images.githubusercontent.com/195327/107890928-f333f200-6f1b-11eb-8d3a-4463a7ca468e.png)


I agree it needs mentioning in the docs 👍

**Comment by MBousss** [comment]
Why is the option on setup been removed, it use to be there? @frenck thank you for the tip

**Comment by ludeeus** [comment]
A stable network connection is prefered at any time while running a server. Especially during the setup where a lot of data (containers) are downloaded to the unit using WiFi for that operation has caused a lot of issues.

**Comment by MBousss** [comment]
> A stable network connection is prefered at any time while running a server. Especially during the setup where a lot of data (containers) are downloaded to the unit using WiFi for that operation has caused a lot of issues.

I am fully aware off the risks, but I am not yet planning to permanently use Home Assistant. With an open-source project you at least should get the option, recommending a cabled connection is great, but forcing not so much. Also,  I do not have Ethernet cables just lying around so for testing I prefer Wi-Fi for now.

**Comment by ludeeus** [comment]
You are not forced to use ethernet.
The guides on the website should give the starting point of the best possible, sensible options, adding every edge case to the documentation will result in bloat and no one finding anything.

WiFi might seem harmless now, but next want how to run with  M.2, then with PoE, then with SIM card for mobile connection. and by that point, you can't even find the download links.

WiFi instructions: <https://github.com/home-assistant/operating-system/blob/dev/Documentation/network.md>

**Comment by MBousss** [comment]
I personally can't agree that WiFi configuration on setup a edge case is.
The link to the doc will probably help me out, thank you for that.
Still I think that the option should be available in the web doc.
