### ISSUE TITLE
Add a link to the tutorial for making blueprints

### ISSUE THREAD

**Issue by filmgarage** [home-assistant/home-assistant.github.io#16552]
**Feedback**

I think it would make sense to have a link to creating Blueprints from the page how to install them and vice versa. A lot of people will land on the wrong page in the first place just like with i.e. Homekit devices, you want to add a homekit device to HA or you want to share a device to HA? Similar issue.

This is the link:

https://www.home-assistant.io/docs/blueprint/

**URL**

https://www.home-assistant.io/docs/automation/using_blueprints/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thanks for the feedback @filmgarage!

I've opened up a PR to adjust the documentation with your suggestion.
