### ISSUE TITLE
USB only APC connection. 

### ISSUE THREAD

**Issue by incarvr6** [home-assistant/home-assistant.github.io#16569]
**Feedback**

It is unclear how to add UI integration for USB device. There is only options for host name, port, user, password. 
So how to add integration for USB connected device? 

**URL**

https://www.home-assistant.io/integrations/nut/

**Version**

2021.2.3

**Comment by frenck** [comment]
You can't.

> The nut sensor platform allows you to monitor a UPS (battery backup) by using data from a NUT (Network UPS Tools) server.

It fetches data from a NUT server, as stated in the first line.

**Comment by incarvr6** [comment]
Perhaps it would be good idea to mention in description that Network UPS Tools add-on installation is needed before.

**Comment by frenck** [comment]
It doesn't need to be an add-on, and some UPS-es already support it. However, it clearly states "a NUT (Network UPS Tools) server".
