### ISSUE TITLE
typo in Windows installation documentation.

### ISSUE THREAD

**Issue by iquix** [home-assistant/home-assistant.github.io#16565]
**Feedback**

https://www.home-assistant.io/installation/windows
at the last section of the page, 
it says

You can now reach your installation on your Raspberry Pi over the web interface on http://homeassistant.local:8123.

it should be 
You can now reach your installation on your Windows over the web interface on http://homeassistant.local:8123.

**URL**

https://www.home-assistant.io/installation/windows/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thanks, @iquix! I've opened up a PR to address your feedback.
