### ISSUE TITLE
Open Exchange Rate Integration configuration example is not helpful

### ISSUE THREAD

**Issue by eric72777** [home-assistant/home-assistant.github.io#16578]
**Feedback**

The example configuration.yaml is not helpful. When this example is used, the response does not provide 1 quote/attribute, but instead includes all currencies. I don't think the "quote: EUR" input is working as intended with this integration.

As a suggestion, a better example configuration.yaml could be:

      - platform: openexchangerates
        api_key: YOUR_API_KEY
        quote: EUR
      - platform: template
        sensors:
          exchange_usd_bitcoin:
            unique_id: sensor.exchange_usd_bitcoin
            friendly_name: Bitcoin Exchange Rate
            value_template: "{{ 1 / state_attr('sensor.exchange_rate_sensor', 'BTC') }}"
            unit_of_measurement: " "
            icon_template: mdi:currency-btc

**URL**

https://www.home-assistant.io/integrations/openexchangerates/

**Version**

2021.2.3

**Comment by frenck** [comment]
I'm confused by your example, you add a platform `openexchangerates`, set to quote `EUR` from the `USD` base and next use a template to extract `BTC`?

**Comment by eric72777** [comment]
In Home Assistant, the `quote` input is flagged as a mandatory input so I made sure to include it for the HA configuration checker. However, this input does not work or select a specific quote. Instead, this integration returns an array of all quotes that must be extracted using a template. It doesn't matter what quote input is used, so I left it as the previous example. However, you could change the example quote field to BTC to make it seem more consistent/logical (but again, it doesn't matter since this input doesn't affect the output).

**Comment by frenck** [comment]
>  the quote input is flagged as a mandatory input so I made sure to include it for the HA configuration checker. However, this input does not work or select a specific quote

? Should this be reported as a bug with the integration? Sounds like we are adjusting the documentation to workaround a bug.

**Comment by eric72777** [comment]
Yes, I think that's a great idea. I only saw how to provide this documentation feedback. How do I report this as a bug?

**Comment by frenck** [comment]
Bugs with integrations can be reported here:

<https://github.com/home-assistant/core/issues>

General more guidance on where to go in different cases: <https://www.home-assistant.io/help>

I'm closing the issue/feedback at this end for now.
