### ISSUE TITLE
Port is not selectable

### ISSUE THREAD

**Issue by drsound** [home-assistant/home-assistant.github.io#16572]
**Feedback**

In requirements section is clearly stated Home Assistand should be reachable using 443 port. But along the documentation it looks like you can have it listening on your port of choice, see:

1) [...] "your Home Assistant instance’s Internet accessible URL with port if needed" [...]
2) [...] "https://[YOUR HOME ASSISTANT URL:PORT]" [...]

This is misleading, because if you don't use port 443 you cant add your custom skill to Alexa in one of the later steps, since the login doesn't work.

I personally experienced this, since I didn't notice the 443 port in the requirements (please make it very bold!) and along the documentation I found the above references letting me think I can use my current custom port (8123).

I don't know if the meaning of the current documentation is that you may use your custom port (example 8123) as long as you ALSO listen on 443. If this is the meaning, that's not so clear anyway. I didn't try this configuration, I simply switched my listening port from 8123 to 443 and now it does work.

**URL**

https://www.home-assistant.io/integrations/alexa.smart_home/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thanks for the feedback @drsound! I've opened a PR to adjust this occurrence.
