### ISSUE TITLE
Add a note that scene.create does not save the state for every light in a group

### ISSUE THREAD

**Issue by dsteinborn** [home-assistant/home-assistant.github.io#16574]
**Feedback**

Please add a note that when using *scene.create* with a light group an average state of the lights in the group will be saved instead of the state of every single light. See https://github.com/home-assistant/core/issues/46492 for an example.

**URL**

https://www.home-assistant.io/integrations/scene/

**Version**

2021.2.3

**Comment by frenck** [comment]
IMHO that is expected? Scenes store states, a group hasn't a real state, the entities in the group have. Even with reading the linked issue, I have no idea on what to change on the documentation side of things.

**Comment by dsteinborn** [comment]
I expected that scene.create saves the state of every entity in the group. I did not remember that groups have a calculated state when implementing my automation using scene.create. In my opinion it could be helpful for other users if there is a note reminding that a group has a calculated state. This could be linked to the group documentation: https://www.home-assistant.io/integrations/group/#group-state-calculation

Feel free to close the issue if you disagree.

**Comment by dsteinborn** [comment]
In my opinion this is still relevant.

**Comment by frenck** [comment]
> I expected that scene.create saves the state of every entity in the group

No, it is an entity by itself.

This belongs on the group integration page, which it already is (as you have linked above). All expcetions and "odd" behaviors are documented on their respective integration pages.

Therefore, closing this issue. Thanks for providing feedback though 👍 

../Frenck 🚂
