### ISSUE TITLE
HyperV?

### ISSUE THREAD

**Issue by chrisbl01** [home-assistant/home-assistant.github.io#16577]
**Feedback**

Am I missing it? Where did the HyperV image go?  I don't even see it in the alternatives.

**URL**

https://www.home-assistant.io/installation/

**Version**

2021.2.3

**Comment by frenck** [comment]
HyperV is not part of our documentation as per the decision made in the architectural decision record:

<https://github.com/home-assistant/architecture/blob/master/adr/0015-home-assistant-os.md#supported-operating-systems-and-versions>

**Comment by chrisbl01** [comment]
Ahh, ok, couldn't remember if it got axed or not since it was there just a few days ago.
