### ISSUE TITLE
Some of the manual installation instructions are missing

### ISSUE THREAD

**Issue by Dgtlnetwks** [home-assistant/home-assistant.github.io#16589]
**Feedback**

In previous versions of the manual installation methods, there were steps shown for a cron entry to enable Home Assistant on boot-up of the Linux system. References to systemd and other methods are also missing. Explanation on updating Home Assistant is missing for a manual install also missing is a statement saying if you upgrade the Python version, then you will need to create a new Python virtual environment and a new Home Assistant installation.

I am running Home Assistant on a BeagleBone Black and have found those instructions to be extremely useful, especially since I have to install a new version of Python (Debian ships with 3.7).

**URL**

https://www.home-assistant.io/installation/linux/

**Version**

2021.2.3

**Comment by frenck** [comment]
That is correct. We had tons of instructions for different init systems, operating systems and all sorts of combinations more. Most incomplete, outdated or still use cases missing.

The manual installation we consider advanced use cases and we do assume someone using those installations methods, as capable of handling that themselves.

Most of those manuals have moved or are recreated in our Community Guides: <https://community.home-assistant.io/c/community-guides/51>

So the removal has been deliberate.
