### ISSUE TITLE
verification email not recieved

### ISSUE THREAD

**Issue by steeplejackfred** [home-assistant/home-assistant.github.io#16585]
**Feedback**

Hi
I have registered for the home assistant community, and it tells me I cant log in until verification email is recieved, but the email has never arrived.

I have been trying daily for about 3 weeks, have checked my junk mail etc.
ken@klongley.co.uk.

thanks

**URL**

https://www.home-assistant.io/help/

**Version**

2021.2.3

**Comment by frenck** [comment]
Sorry, this one fell through the cracks of my notifications as it seems.

Looked at the forums and seems like you've already resolved it 👍
