### ISSUE TITLE
Page outdated

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#16583]
**Feedback**

this page seems to outdated.. the page
1https://developers.home-assistant.io/docs/core/entity/fan`
seems to contain new information that does not match the page is question

**URL**

https://www.home-assistant.io/integrations/fan.template/

**Version**

2021.2.3

**Comment by frenck** [comment]
The developer documentation tracks the state of development. The end-user documentation shows the latest stable version of Home Assistant Core.

There are big changes planned for the next release (2021.3.0), which are already visible on the developer documentation, but not yet available on stable.

It is thus not outdated, but simply not released yet.
