### ISSUE TITLE
Service light.turn_on not found

### ISSUE THREAD

**Issue by WhoCares1337** [home-assistant/home-assistant.github.io#16591]
**Feedback**

I want to learn about automation in HA. The service "light.turn_on" that is suggested in the documentation is not found.

**URL**

https://www.home-assistant.io/getting-started/automation/

**Version**

2021.2.3

**Comment by frenck** [comment]
This is because you don't have lights configured at this point. Lights are the most common things people configure when getting started, hence that is used.

**Comment by ensastiga** [comment]
In my case light.* used to be listed under the call service drop down list but now is gone 

Version

2021.2.3
