### ISSUE TITLE
Should I use this integration for a fixed cameara

### ISSUE THREAD

**Issue by pmoneill** [home-assistant/home-assistant.github.io#16606]
**Feedback**

Through HA V2021.1.5, I could view my Foscam in a Lovelace picture elemement card after adding this to my configuration.yaml:
camera:
  - platform: foscam
    ip: 192.168.0.4
    port: 88
    username: 'User'
    password: 'Password'
    name: Porch

This no longer works in V2021.2.3  If add this Foscam integration, it finds my cameras but I can no longer view them in Lovelace, even after removing the above YAML code.  I don't have a PTZ camera so I don't know if I should use this integration.  The docs need to make it clear on what elements need to be added where to view a Foscam now.  I'm totally confused.

**URL**

https://www.home-assistant.io/integrations/foscam/

**Version**

2021.2.3

**Comment by Janthenman67** [comment]
Did find a solution yet? I have the exact same problem with my foscam camera's. Maybe the problem is that Yaml file auto migrates to the Foscam Ingration. After that I don't even know how to access the parameters again. I have read somewher that the camera is cheating with a portnumber. But where to check.
Another idea is to delete the Yaml and the Foscam integration. After restart install a clean integration and fill in the right parameters. This part ahsn't worked out for me yet, but probably its the way to go?

**Comment by pmoneill** [comment]
Janthenman67:  Yes, I did find a solution.  The old Foscam integration that was configured in YAML only used the HTTP stream on Port 88. This new GUI integration has blanks for both HTTP and RSTP video streams, defaulting to ports 88 and 554, respectively. RSTP doesn’t work for my model FI9900EP. I finally cleared the RSTP port, even though it is red to indicate that it is required, and that gave me an image in Lovelace again! Conclusion: only use HTTP on port 88 and delete the default port number for RSTP, leaving it blank.  To access the parameters again, you must delete the Foscam intergration instance for the camera in question, then recreate it.

**Comment by Janthenman67** [comment]
Yesss. it works, thanks a lot. Although I have a new problem now. I am using 2 Foscam Fl9900P camera's and I can't figure out how to place a second entity (camera with a different IP) in the Foscam integration. Also I can't find the location of the settings of the first camera. Could you point me in the right direction perhaps?

**Comment by pmoneill** [comment]
Unfortunately, this integration does not have a way to go back and view a camera's settings.  To edit an existing camera, you must delete it and recreate it.  To add another camera, you must add another instance of the Foscam integration by clicking the "+ ADD INTEGRATION" button in the bottom right corner of the Integrations page, then search for Foscam.  The navigation procedure I've discovered:  Go to Configurations > Integrations > Foscam.  In the Foscam tile you should see all of your cameras listed.  If you don't, it means that you have already selected one of them as indicated by its displayed name and a "<" to the left of "Foscam"; click the "<" to go back to the camera list.  This could be simpler.

**Comment by Janthenman67** [comment]
Yes, I allready tried the procedur you described. But while configuring the second camera it is not possibel to leave the RSTP port number blanc. The rusult is a cofiguration without a stream. Even "0"is not working. Did you have the same issue? And how did you fix it?

**Comment by Janthenman67** [comment]
Never mind, I got it working. Editing a "0" tot the RSTP port did work afterall. Thanks again for your help. Much appreciated!
