### ISSUE TITLE
Integration Needs Work

### ISSUE THREAD

**Issue by NRutt2005** [home-assistant/home-assistant.github.io#16608]
**Feedback**

This integration needs a little bit of debugging. You can't turn on the TV from the integration. I can only turn the TV off, change sources, and volume up. There is a lag a lot of times from when the unit powers up to when it is updated to the "On" state within Home Assistant. Being unable to turn the TV on over Home Assistant almost makes this integration pointless if trying the use Home Assistant as my go to smart home interface. Would love for this capability to come to existence. 

**URL**

https://www.home-assistant.io/integrations/samsungtv/

**Version**

2021.2.3

**Comment by frenck** [comment]
Hi there @NRutt2005!

This is the feedback form for our documentation, however, looking at your feedback: It seems like you want to report bugs and feature requests for the Samsung TV integration.

Please report issues with integrations at:

<https://github.com/home-assistant/core/issues>

For feature requests, please use our Community Forum:

<https://community.home-assistant.io/c/feature-requests/13>

Thanks! 👍
