### ISSUE TITLE
Missing info for the custom folder

### ISSUE THREAD

**Issue by pixel8383** [home-assistant/home-assistant.github.io#16601]
**Feedback**

1. HA needs write rights on the folder?
2. Is the system capable to scan the folder and the subfolders?

**URL**

https://www.home-assistant.io/more-info/local-media/setup-media/

**Version**

2021.2.3

**Comment by frenck** [comment]
> HA needs write rights on the folder?

That depends on the integration. Right now, I don't think it is required, however, we do allow for it.

> Is the system capable to scan the folder and the subfolders?

Yes.
