### ISSUE TITLE
Glances Integration Entities

### ISSUE THREAD

**Issue by veno77** [home-assistant/home-assistant.github.io#16612]
**Feedback**

Hello, 
Can you add Network and Diskio to the integration entities in the Hassio Glances Integration?

**URL**

https://www.home-assistant.io/integrations/glances/

**Version**

2021.2.3

![image](https://user-images.githubusercontent.com/4173325/108050865-dd751880-7052-11eb-8666-b9836245d8f2.png)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues and documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
