### ISSUE TITLE
No ssh nor access to drive (to create ssh file)...

### ISSUE THREAD

**Issue by MrLuis** [home-assistant/home-assistant.github.io#16614]
**Feedback**

I'm not sure if this is an image issue or is an Etcher issue. But the image is not readable by the operating system, therefore we can't create an ssh file. Since raspberry os now comes with ssh disabled...  Are we forced to have peripherals in order to access the system? 

Be aware, I'm new, and couldn't find a way to access ssh. 

tks,
Luis

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by frenck** [comment]
This is not Raspberry OS, but Home Assistant OS. There is no SSH and thus no file to create.

After the first boot and onboarding, SSH can be installed as an add-on in the add-on store (which can be found in the Supervisor menu.

**Comment by MrLuis** [comment]
Ups! Sorry, getting the ssh from the store!  Tks!
