### ISSUE TITLE
Topic "Adding local media" talks about setting up the local media folder; but nothing about how to add media to the folder

### ISSUE THREAD

**Issue by kgomara** [home-assistant/home-assistant.github.io#16616]
**Feedback**

Newbie here (obviously).  I'd like to add a video file to my Home Assistant instance, which is running on a VirtualBox instance on my Mac.  I believe I need to get a .mp4 file into the /media folder in that VBox instance.  The instructions in the topic are "After you have set up a local media folder, you can add any media to that folder you have set up.

Your media will show up in the Home Assistant frontend automatically."

So - HOW can I add "any media to that folder"?  I'm guessing SSH would be involved...

**URL**

https://www.home-assistant.io/more-info/local-media/add-media/

**Version**

2021.2.3

**Comment by frenck** [comment]
Hi there @kgomara!

That is more of a general support question, if you have those, please use our community forum or Discord chat.

As for the answer to your question: There are multiple add-ons available that can give you access to the media folder. For example, Samba, the FTP server or indeed the SSH add-on.
