### ISSUE TITLE
Wrong time estimate on install instructions.

### ISSUE THREAD

**Issue by iBobik** [home-assistant/home-assistant.github.io#16629]
**Feedback**

> Within a few minutes you will be able to reach Home Assistant on homeassistant.local:8123.

Not really. Within a few minutes I can access it just by IP and only message about another 20 minutes is there.

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thanks, I can see the confusion, however, the wording is correct. It is reachable in a couple of minutes. Yes, there might still be something going on, like downloading/updating, or maybe something is wrong even. All in all, that is shown on that page.

Nevertheless, thanks for your feedback 👍

**Comment by iBobik** [comment]
At least it is not correct it is reachable by mDND. It seems like that daemon starts later.

Jan Pobořil
https://honza.poboril.cz/

**Comment by frenck** [comment]
No, that is not a daemon that starts later.
