### ISSUE TITLE
Sample provided does not pass YAML lint

### ISSUE THREAD

**Issue by dbmix** [home-assistant/home-assistant.github.io#16621]
**Feedback**

The OpenWeatherMap sample does not pass YAML linting making it very difficult to adjust.
Is there someone with enough YAML experience that can debug why unexpected characters are found on line 12?

**URL**

https://www.home-assistant.io/integrations/rest/

**Version**

2021.2.3

**Comment by frenck** [comment]
There are many examples on that page, care to share which example?
