### ISSUE TITLE
Automations created by blueprints are written to automations.yaml

### ISSUE THREAD

**Issue by jonwaland** [home-assistant/home-assistant.github.io#16623]
**Feedback**

Automations created by blueprints are written to automations.yaml - which may be an issue if you are not including it in your configuration, and only include automations in a subdirectory....

Should have some form of warning...

**URL**

https://www.home-assistant.io/docs/automation/using_blueprints/

**Version**

2021.2.3

see https://community.home-assistant.io/t/automation-created-using-a-blueprint-not-showing-up-in-ui-after-creating/256753/13

**Comment by jonwaland** [comment]
I think I've done it all correctly...

**Comment by frenck** [comment]
In general, I think the added location is a bit out of context. The split configuration is an advanced subject, while this part of the documentation is not aimed at that subject/level of experience at all.

By default, this will work, unless one has manually modified the configuration in such a way. All this is extensively described on the pages regarding splitting a configuration.

**Comment by jonwaland** [comment]
I agree that that split configuration is an advanced subject, but suspect many (like me) haven't realised they are only including the files in the subdirectory and not the base directory. This wasn't a problem until there was the option to create automations from the GUI and then more so from blueprints (which I think more are likely to use) - and has left a number wondering why it doesn't work. 


If the consensus is that this isn't a good change to the documentation, then fair enough, I'm not precious about it.

**Comment by jonwaland** [comment]
updated and merged.
