### ISSUE TITLE
Move banner out of way on all pages

### ISSUE THREAD

**Issue by yelkenli1** [home-assistant/home-assistant.github.io#16633]
**Feedback**

There is a banner at the top of each page "make sure you run ... latest version" and the Home Assistant logo and menu drop down selection - These cover up the scroll bar.  you have to arrow down for a while to get the scroll bar to come down far enough to be seen.  I am using firefox on mac.  

On all pages, you should have a way to return to the community forum home page.  as it is now, you have to navigate to the "need help" page, then to the "forum" page.  If this is an effort to get people to use Discord, please don't.  I have found some answers on discord threads, but not many and they are hard to search through; I have NEVER had any one answer a question or even respond to me on Discord, except once where I contributed to a question.  I know it is all community based, and I don't expect a help desk.  The only place to get help is the forum and reddit.  

**URL**

https://www.home-assistant.io/integrations/timer/

**Version**

2021.2.3

**Comment by frenck** [comment]
> There is a banner at the top of each page "make sure you run ... latest version" and the Home Assistant logo and menu drop down selection - These cover up the scroll bar. you have to arrow down for a while to get the scroll bar to come down far enough to be seen. I am using firefox on mac.

Unfortunately, this is a known Firefox issue for years. It is fixable, by disabling scalability for the user, however, that is not friendly for users who want to scale (on all platforms and browsers). Which is a more important factor.

> If this is an effort to get people to use Discord, please don't.

?

> I have found some answers on discord threads, but not many and they are hard to search through; I have NEVER had any one answer a question or even respond to me on Discord, except once where I contributed to a question

Sorry to hear you are frustrated with the experience on Discord. Everybody prefers different mediums. My personal preference is Discord and Reddit second, some like the forums, others are loving the Facebook group 🤷 

> On all pages, you should have a way to return to the community forum home page. as it is now, you have to navigate to the "need help" page, then to the "forum" page.

Its in the footer.
