### ISSUE TITLE
The corona virus sensors have not been updated since 02.14

### ISSUE THREAD

**Issue by unicumnext** [home-assistant/home-assistant.github.io#16634]
**Feedback**

The corona virus sensors have not been updated since 02.14

I see the https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html page every day update, but the sensor not updated.

**URL**

https://www.home-assistant.io/integrations/coronavirus/

**Version**

2021.2.3

**Comment by LucaKaufmann** [comment]
Noticed the same issue as well, I tried removing and adding the integration again but so far no luck

**Comment by unicumnext** [comment]
work again

**Comment by frenck** [comment]
This is the issue tracker for our documentation, however, the reported issue is not related to our documentation.

If you want to raise an issue with an integration, please report one here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
