### ISSUE TITLE
Chose a profile: Only works if multiple profiles in Withings exist

### ISSUE THREAD

**Issue by jory3** [home-assistant/home-assistant.github.io#16638]
**Feedback**

I didn't get the possibility to chose a profile as mentioned in the documentation. My workaround was then to go to my.withings.com and add a second profile to my account, I could then chose my primary one and it seems to work. 

**URL**

https://www.home-assistant.io/integrations/withings/

**Version**

2021.2.3

**Comment by frenck** [comment]
So, it this a documentation issue? Or does that mean you cannot set up this integration when there is only 1 profile? (thus an integration bug?)

**Comment by jory3** [comment]
Setting it up when there is only one profile might work, I didn't test finally because I was searching for the selection possibility mentioned in the docs. You would need to know your profile name, tough. In my case the profile name was just "Firstname Lastname".

**Comment by reinerr16** [comment]
Hi,
i also run into this problem. If you have only one Profil which is the case for the most people you dont have an dropdown to select your profilename:
![grafik](https://user-images.githubusercontent.com/23479970/109037309-e016e400-76ca-11eb-9f7d-f581ecebd675.png)
Maybe its possible to skip the selection of profiles if theres only one in the withings account.

As @jory3 mensiond the unique profilename is "firstname lastname" from your personal withings account.

**Comment by frenck** [comment]
Ok, so this slowly is resulting in something else. As in, this is not a documentation issue, but an integration bug; as it is not possible to configure it, if one has a single profile. Right?

**Comment by reinerr16** [comment]
it's fully possible to configure. if you have an single profile you can just enter the profilename as  "firstname lastname", so it could be solved with an hint in the docs.

**Comment by jory3** [comment]
Adding something like "your profile name equals to the firstname and lastname you entered when creating your withings account or profile" to the dialog or docs would solve the issue for me. 
Of course a dropdown with possible profile names would be even more comfortable than the existing text field in the configuration dialog.
