### ISSUE TITLE
Remote Python Debugger does not work

### ISSUE THREAD

**Issue by IgnacioHR** [home-assistant/home-assistant.github.io#16647]
Hi,

Sorry for being so crude! And sorry if this is due to an error on my side. But this is what I'm doing and I can't remotely connect to the debugger:

1. As stated in the documentation. I've modified `configure.yaml` to add:

```
debugpy:
  start: false
  wait: false
  host: 0.0.0.0
  port: 5678

```

To verity I'm doing this correctly, I connect via ssh to the raspberry-pi where homeassistant is running using port 22222 and root account (and public/private key pair) then I `cd /mnt/data/supervisor/homeassistant` followed by `vi configuration.yaml`

2. reboot the system 
3. connect using ssh again and execute `netstat -an | grep LISTEN`

```
# netstat -an | grep LISTEN
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22222           0.0.0.0:*               LISTEN
tcp        0      0 192.168.1.29:51828      0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8123            0.0.0.0:*               LISTEN
...
```

In order to made this short, I've eliminated TCPV6 entries and additional garbage

I see external connections can be done to several ports but 5678 is not available.

additional information:
`docker ps `command reveals:
```
# docker ps
CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
17814e07b9db        ghcr.io/hassio-addons/grafana/aarch64:6.1.2            "/init"                  About an hour ago   Up About an hour                             addon_a0d7b954_grafana
1ceb9e99b47d        homeassistant/aarch64-addon-ssh:9.0.1                  "/init"                  About an hour ago   Up About an hour                             addon_core_ssh
ae35c101db95        ghcr.io/hassio-addons/influxdb/aarch64:4.0.3           "/init"                  About an hour ago   Up About an hour    0.0.0.0:8086->8086/tcp   addon_a0d7b954_influxdb
f146a6a777d3        ghcr.io/hassio-addons/chrony/aarch64:2.0.0             "/init"                  About an hour ago   Up About an hour    0.0.0.0:123->123/udp     addon_a0d7b954_chrony
d9f84ce8ac79        homeassistant/aarch64-hassio-multicast:3               "/init"                  About an hour ago   Up About an hour                             hassio_multicast
4a2723d3e509        homeassistant/aarch64-hassio-cli:2021.02.1             "/init /bin/bash -c …"   About an hour ago   Up About an hour                             hassio_cli
fa3256f7dd51        homeassistant/aarch64-hassio-audio:2021.02.1           "/init"                  About an hour ago   Up About an hour                             hassio_audio
ac2c1708d4cb        homeassistant/aarch64-hassio-dns:2021.01.0             "/init"                  About an hour ago   Up About an hour                             hassio_dns
0ce8e15a444c        homeassistant/aarch64-hassio-supervisor:latest         "/init"                  About an hour ago   Up About an hour                             hassio_supervisor
9a1f4188daef        homeassistant/raspberrypi4-64-homeassistant:2021.2.3   "/init"                  8 days ago          Up About an hour                             homeassistant
89e948f83747        homeassistant/aarch64-hassio-observer:2020.10.1        "/init"                  2 months ago        Up About an hour    0.0.0.0:4357->80/tcp     hassio_observer
```

so, not even the port is mapped on any docker?

I NEED HELP!

**Comment by frenck** [comment]
It doesn't need to map in Docker, as Home Assistant runs on the host network.

Additionally, in your shared configuration snippet states: `start: false`, thus meaning it does not start automatically (and thus does not open a port either).

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

If you want to report a bug with an integration:

<https://github.com/home-assistant/core/issues>

You are more likely to get the answer you are looking for in those places, as this issue tracker is used for documentation tracking.

Thanks! 👍
