### ISSUE TITLE
Documentation steps are wrong

### ISSUE THREAD

**Issue by bazzuk** [home-assistant/home-assistant.github.io#16659]
**Feedback**

homeassistant@pisdr:/srv/homeassistant $ python3.8 -m venv .
bash: python3.8: command not found

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by frenck** [comment]
This can differ based on the platform installed and the way one manages their Python environments. We consider this an advanced installation method, that one is familiar with and knows how to adopt too.

If not, I would strongly recommend using one of the generally recommended installation methods, Home Assistant Operating System or Home Assistant Container.

**Comment by JamesZzhan** [comment]
I guess the reason is you are not install python 3.8 yet

**Comment by bazzuk** [comment]
> I guess the reason is you are not install python 3.8 yet

I guess you didn't realize it was already installed, hence to statement the steps are wrong
