### ISSUE TITLE
Implementing Zones

### ISSUE THREAD

**Issue by zgadson** [home-assistant/home-assistant.github.io#16658]
**Feedback**

If I'm understanding your documentation correctly, it appears to say I can specify zones as individual media players. What it fails to explain is how to actually format the configuration for adding zones. Zone2: True? Does it need a dash in front? Colon? How do I do this?

Thanks!

**URL**

https://www.home-assistant.io/integrations/denonavr/

**Version**

2021.2.3

**Comment by frenck** [comment]
The zones have no specific format for the configuration, as the Denon AVR integration is configurable via UI, not the YAML configuration files.

Look for the Denon AVR integration from "Configuration" -> "Integrations" and click on the "Options" button in that card. It will give you the options to enable/disable those zones.

**Comment by zgadson** [comment]
Wow. That was too easy. I've been messing with this for a week and didn't
know that was there. THANK YOU!!!!!
