### ISSUE TITLE
Convenience script doesn't make supervisor privilledged

### ISSUE THREAD

**Issue by iamkarlson** [home-assistant/home-assistant.github.io#16655]
**Feedback**

Run the convenience script again and again and system is yet in unhealthy state. What is the set of requirements I need to satisfy to make supervisor privileged? 

**URL**

https://www.home-assistant.io/more-info/unsupported/privileged/

**Version**

2021.2.3

**Comment by frenck** [comment]
What OS are you running Supervised on? Could you please provide the output of `ha info` and `ha resolutions info`?

**Comment by DotNet2Web** [comment]
Same here, running the script doesn't make the difference.
Its running in Docker with Ubuntu 20.04 LTS

Here are the asked outputs: 

~ $ ha info
arch: amd64
channel: stable
docker: 20.10.3
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2021.2.3
hostname: ***********
logging: info
machine: qemux86-64
operating_system: Ubuntu 20.04 LTS
state: running
supervisor: 2021.02.11
supported: false
supported_arch:
- amd64
- i386
timezone: Europe/Amsterdam

~ $ ha resolutions info
issues: []
suggestions: []
unhealthy:
- privileged
unsupported:
- os

**Comment by frenck** [comment]
@DotNet2Web `Ubuntu 20.04 LTS` is not a supported system by the Home Assistant project.

Please read the requirements linked here @ step 1: <https://www.home-assistant.io/installation/linux#install-home-assistant-supervised>
