### ISSUE TITLE
OSError: [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by JamesZzhan** [home-assistant/home-assistant.github.io#16662]
**Feedback**

2021-02-20 13:42:13 WARNING (SyncWorker_5) [zeroconf] Error sending through socket 10
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/zeroconf/__init__.py", line 2952, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
OSError: [Errno 101] Network is unreachable

When I tried to install home assistant Core, this error comes out at the last step after I input hass.May I ask what is the reason to cause this error?

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues wit our documentation, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
