### ISSUE TITLE
No documentation on how to configure ESPHome from yaml

### ISSUE THREAD

**Issue by TheLastGimbus** [home-assistant/home-assistant.github.io#16664]
**Feedback**

Hi there!

I wanted to configure my ESPHome's through yaml, so I can version and backup them, but there seems to be no such option!

[Documentation](https://www.home-assistant.io/integrations/esphome/#configuration) says nothing, and even [the code](https://github.com/home-assistant/core/blob/43a5852561b6c464177fa016ab2a3216137fe418/homeassistant/components/esphome/__init__.py#L57) seems to not allow this! Thus, I'm not sure wheteher it's and issue with documentation or core, but I'm posting it here :shrug:

**URL**

https://www.home-assistant.io/integrations/esphome/#configuration

**Version**

2021.2.3

**Comment by frenck** [comment]
ESPHome is not configurable via YAML, hence this isn't documented either.

As in general, Home Assistant is moving away from the configuration using YAML for all integration that communicates with a device or service.

**Comment by TheLastGimbus** [comment]
Why?? This would make it so hard to version and backup :disappointed:

**Comment by frenck** [comment]
More information can be found here:

<https://www.home-assistant.io/blog/2020/04/14/the-future-of-yaml/>

And specified here:

<https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md>
