### ISSUE TITLE
Unifi Video is deprecated. Unifi Protect is their replacement product.

### ISSUE THREAD

**Issue by cdekesel** [home-assistant/home-assistant.github.io#16675]
**Feedback**

Unifi Video is deprecated. Unifi Protect is their replacement product.

**URL**

https://www.home-assistant.io/integrations/uvc/

**Version**

2021.2.3

**Comment by frenck** [comment]
Hi!

Thanks for the feedback, I'm missing a suggestion though. Could you please clarify your suggestion for this page in this case?

../Frenck
