### ISSUE TITLE
Documentation should include information for firewall configuration

### ISSUE THREAD

**Issue by taugusti** [home-assistant/home-assistant.github.io#16679]
**Feedback**

It would be great to have firewall configuration information included in the documentation.
I my case I have the hass on a special IoT-network segment and one lan-port of the synology is on the same network. The synology firewall has been configured to reject all unapproved traffic. So I need to create a pinhole for the synology integration. 
Also, if  the integration needs other ports for ex. cameras, please list them also.

**URL**

https://www.home-assistant.io/integrations/synology_dsm/

**Version**

2021.2.3

**Comment by frenck** [comment]
In general, we consider firewall configurations out of scope for our configuration.
If one goes advanced routes, we assume one is able to handle those as well.

Thanks for the suggestion, but closing it for the above reason.

**Comment by taugusti** [comment]
Ok - I assume that could be an argument
- but then at least which which protocol you use so I have a clue to search for.

**Comment by mib1185** [comment]
Hi @taugusti 
The used port is configured by user during setup of integration.
For camera streaming, the URLs provided by Surveillance Station are used and not influenced by `synology_dsm` integration.

**Comment by taugusti** [comment]
> Hi @taugusti
> The used port is configured by user during setup of integration.
> For camera streaming, the URLs provided by Surveillance Station are used and not influenced by `synology_dsm` integration.

not really - you can type someting in if you like - but if you leave it blank the integration will use a default that works.
I just do not understand the unwillingness to write a single line that saves hours and hours for users. Just name the protocol so we have a starting point for the search.

**Comment by mib1185** [comment]
As usual for the most integrations, the default ports are same as the ports you as user are using for accessing and managing the device. In case of DSM it is 5000 for http and 5001 for https.
I'm on the same side as frenck, that firewall configuration highly depends on users environment and if user implements advanced network configurations, the user should also be able to gather the needed information for eq. the applications which he wants to protect by an firewall.
