### ISSUE TITLE
Storage folder

### ISSUE THREAD

**Issue by Varming73** [home-assistant/home-assistant.github.io#16673]
**Feedback**

A storage folder for learned codes is mentioned but it doesn't seem to be documented where this folder actually is.

**URL**

https://www.home-assistant.io/integrations/broadlink/

**Version**

2021.2.3

**Comment by frenck** [comment]
It is actually!

<https://www.home-assistant.io/integrations/broadlink/#learned-codes-storage-location>

![image](https://user-images.githubusercontent.com/195327/109660132-cb25cf00-7b68-11eb-8232-b9a0dabd48b6.png)
