### ISSUE TITLE
Home Assistant Core

### ISSUE THREAD

**Issue by JamesZzhan** [home-assistant/home-assistant.github.io#16672]
**Feedback**

For the last step on Install Home Assistant Core. Entering http://homeassistant.local:8123 is not work for me, should be ip-address:8123.

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by frenck** [comment]
There are multiple variants that may work, depending on the network setup.

![image](https://user-images.githubusercontent.com/195327/115847215-0636d700-a423-11eb-90be-037631993650.png)


They are all listed.
