### ISSUE TITLE
QTS - TS-253Pro - firmware 4.5.2

### ISSUE THREAD

**Issue by jacasal** [home-assistant/home-assistant.github.io#16680]
**Feedback**

the operation is correct for this model.

**URL**

https://www.home-assistant.io/integrations/qnap/

**Version**

Home Assistant 2021.2.2

**Comment by colinodell** [comment]
Thanks for the note! I've updated https://github.com/colinodell/python-qnapstats/blob/master/README.rst accordingly.  I've also opened #16682 to suggest using that list instead, as it's more up-to-date.

**Comment by jacasal** [comment]
<img width="383" alt="Captura de pantalla 2021-02-22 a las 17 44 39" src="https://user-images.githubusercontent.com/12412903/108741136-b0cf6e00-7536-11eb-8055-ec3dc8a5a8dc.png">

For this model , the cpu and system temperature work fine
