### ISSUE TITLE
The QNAP container mentioned is obsolete

### ISSUE THREAD

**Issue by stenci** [home-assistant/home-assistant.github.io#16685]
**Feedback**

The QNAP container mentioned is obsolete. I wasted hours trying to figure out how it works, but it doesn't.

Then I found this article that uses a non QNAP official installation and worked like a charm:
https://poyu.co.uk/2020/07/10/setup-homeassistant-on-qnap-container-using-docker/

I think this page should warn the user not to use the official QNAP installation and mention this article.

**URL**

https://www.home-assistant.io/installation/alternative/

**Version**

2021.2.3

**Comment by frenck** [comment]
Let's update the documentation instead...

**Comment by frenck** [comment]
No stale
