### ISSUE TITLE
Agent DVR Iframe explanation 

### ISSUE THREAD

**Issue by HAjerry** [home-assistant/home-assistant.github.io#16688]
**Feedback**

I have followed the documentation for how to embed the Agent DVR viewer directly in Home Assistant. However, the Iframe only displays the login window from ispyconnect. It is not possible to get through the login prompt. Any ideas?

**URL**

https://www.home-assistant.io/integrations/agent_dvr/

**Version**

2021.2.3

**Comment by ispysoftware** [comment]
hello possibly because home assistant isn't using SSL and the web portal is? 
you could just use the direct interface at http://<localhost/ip address>:8090

**Comment by HAjerry** [comment]
Thanks!

Most probably that is the explanation. Unfortunately not possible to use http in a webpage card as I am connecting to home assistant with https.

/J

**Comment by HAjerry** [comment]
Furthermore, guess it would make sense to update the HA documentation https://www.home-assistant.io/integrations/agent_dvr/ if it no longer works to include a link to ispy on a webpage.

**Comment by frenck** [comment]
@HAjerry As far as I understand from the responses above, it is still possible, but you were mixing up http/https?

**Comment by HAjerry** [comment]
@frenck No, not possible. The https://www.ispyconnect.com/app/ is not possible to use because of SSL. Also not possible to use http://localhost... as I am using https to access Home Assistant.

**Comment by frenck** [comment]
But that is a problem for your setup? As in, it would work on mine? I'm not sure what to document about this, as in, this is general for anything on the internet and not specific to this integration.

**Comment by HAjerry** [comment]
Not sure I understand you, but I disagree. The page https://www.home-assistant.io/integrations/agent_dvr/ includes the following text: "Using the Webpage Card you can embed the Agent DVR viewer directly in Home Assistant. Just point it to https://www.ispyconnect.com/app/". From what I understand this not possible for any user or configuration: Webpage Card does not support SSL but the ispyconnect page requires SSL. Hence, I recommend that the text is updated. 

It is true that some users would be able to use the Webpage Card and point it to http://<localhost/ip address>:8090. But then the text should be updated to reflect this? However, I suppose that majority of HA users are using https which makes this workaround impossible.

**Comment by ispysoftware** [comment]
if the page is using SSL then an SSL webpage card should be fine shouldn't it?
What's happening on the login page? If it was an SSL error you shouldn't get anything.
Have you checked dev tools? What web browser are you using?

**Comment by HAjerry** [comment]
Hi there, the login page displays correctly on the webpage card. However, nothing happens when I fill out the login credentials – just staying on the same login page without getting to the other web pages. Also no errors shown. I am using Chrome. Have not checked dev tools. Is there an SSL webpage card available for Home Assistant, where can find it?

**Comment by frenck** [comment]
> Have not checked dev tools. 

Could you please check it, it might contain a vital hint in what is going on.

**Comment by HAjerry** [comment]
Sure, assume you mean Chrome dev tools (Ctrl+Shift+c)? The Console window is empty: no errors, no warnings.

**Comment by ispysoftware** [comment]
well. it was working - the webpage card doesn't seem to maintain session state any more - so when you login, it logs you in but on the next request there's no session. Is this something that's changed with home assistant or a browser update? maybe cookies are being denied?

**Comment by ispysoftware** [comment]
Think i've fixed it - was due to the samesite cookie settings in a recent chrome update. Will be live soon.

**Comment by HAjerry** [comment]
Awesome! Just tested, and now it works like a charm!!! Thanks a million! Amazing and impressive how fast things get resolved by the Home Assistant community.

**Comment by frenck** [comment]
Nice! Thanks, @ispysoftware 👍 

Will close the issue as resolved from this end. Thanks @HAjerry for reporting 👍

**Comment by ispysoftware** [comment]
This update broke other parts of our website :( had to roll it back. will work on a resolution
