### ISSUE TITLE
Describe nomenclature tree please

### ISSUE THREAD

**Issue by a-x-** [home-assistant/home-assistant.github.io#16692]
**Feedback**

something like this common scheme:

```
- component group
  - component
    - device_class
```

e.g.:
- input
  - sensor
    - binary_sensor
    - 
- output
  - switch
    - switch
    - outlet
  - light
  - fan

also will be useful to see tree with platforms.

all the tree nodes should be clickable.

docs are too hard to read now.

all the items can be linked to: 1) mqtt discovery config payload example 2) custom ha config example 3) services 4) state params 

also template and generic, integrations should be have a place too

**URL**

https://www.home-assistant.io/docs/configuration/

**Version**

2021.2.3

**Comment by frenck** [comment]
Describing that would describe something deprecated, as we are moving away from platform configurations.

Additionally, there are multiple formats, so a generic description on the page listed in this feedback, would be hard.

In the end, configuring devices and services will move fully into the UI.

**Comment by a-x-** [comment]
but taxonomy will be the same, isn’t ?

I need the domain tree to understand how to develop pi-mqtt-gpio ha discovery mode

**Comment by frenck** [comment]
> but taxonomy will be the same, isn’t ?

Not sure which part you are referring to with that question.

> I need the domain tree to understand how to develop pi-mqtt-gpio ha discovery mode

That sounds like an MQTT question? What does that have to do with: https://www.home-assistant.io/docs/configuration ?

**Comment by a-x-** [comment]
Not a mqtt only. MQTT can work with every HA domain items. e.g. components, device_classes

**Comment by a-x-** [comment]
Also, I want to navigate better when I read the docs. Currently it’s hard

**Comment by a-x-** [comment]
Now Categories links on the doc pages navigates to useless for me integrations list. But I expect domain hierarchy navigation.

**Comment by frenck** [comment]
> Not a mqtt only. MQTT can work with every HA domain items. e.g. components, device_classes

That is incorrect.

> Also, I want to navigate better when I read the docs. Currently it’s hard

> Now Categories links on the doc pages navigates to useless for me integrations list. But I expect domain hierarchy navigation.

Please don't stack different things in an issue, that isn't manageable and trackable. I'll ignore those comments.

**Comment by a-x-** [comment]
I don’t stack different things. I tried to describe better the reason 

Oh, it’s hard to explain anything here...

**Comment by frenck** [comment]
I was trying to figure out what you are looking for, instead general comments on navigation is hard came around. It is way more productive in general, to keep the scope of things small. Hence my stacking comment. I'm sorry if that came across as hard a misunstanding.

Closing the issue helps nobody.

**Comment by a-x-** [comment]
I can open new issue if you got something that can be implemented in track of ha development vision
