### ISSUE TITLE
i2c instructions don;t seem to work...

### ISSUE THREAD

**Issue by icornish72** [home-assistant/home-assistant.github.io#16693]
**Feedback**

cannot sudo raspi-config.

**URL**

https://www.home-assistant.io/integrations/tof/

**Version**

2021.2.3

**Comment by frenck** [comment]
Which operating system and which Home Assistant installation method are you using?

**Comment by icornish72** [comment]
Raspberry pi 3b; running on Hassio.

**Comment by frenck** [comment]
Hassio is ambiguous and not a term used anymore. You can find your operating system and installation methods in the Info panel: Configuration -> Info.

**Comment by icornish72** [comment]
Apologies...
System Health

version: core-2021.2.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.7
os_name: Linux
os_version: 5.4.83-v8
arch: aarch64
timezone: Europe/London

GitHub API: ok
Github API Calls Remaining: 4871
Installed Version: 1.11.3
Stage: running
Available Repositories: 751
Installed Repositories: 8

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 5.12
update_channel: stable
supervisor_version: supervisor-2021.02.11
docker_version: 19.03.13
disk_total: 115.2 GB
disk_used: 5.9 GB
healthy: true
supported: true
board: rpi3-64
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.2.0), Check Home Assistant configuration (3.6.0), SSH & Web Terminal (8.0.3), Grafana (6.1.2), Home Assistant Google Drive Backup (0.103.1), Samba share (9.3.0), InfluxDB (4.0.3), AdGuard Home (3.0.0)


dashboards: 2
resources: 2
views: 6
mode: storage

**Comment by frenck** [comment]
Home Assistant OS, the generic page on enabling I2C for Home Assistant OS can be found here:

<https://www.home-assistant.io/common-tasks/os/>
