### ISSUE TITLE
AirVisual docs list a deprecated config option

### ISSUE THREAD

**Issue by tannisroot** [home-assistant/home-assistant.github.io#16694]
**Feedback**

AirVisual docs seem to reference a deprecated configuration option `airvisual`. Adding it to `configuration.yaml` results in the following warning:
```WARNING (MainThread) [homeassistant.components.airvisual] The 'airvisual' option is deprecated, please remove it from your configuration```

More than that, from I've observed, it doesn't really do anything, as AirVisual keeps using configuration that it was given during the setup of the integration.
Since it no longer seems to serve any purpose and is deprecated, it should probably be removed.
However, even though this is an issue for HA itself, I should note that there seems to loss of functionality, as the configuration option allowed the user to specify a city as the location instead of coordinates, and from what I've seen, levels of pollution for a specific city seem to differ from pollution levels at coordinates the same as the center of that city, for whatever reason.

**URL**

https://www.home-assistant.io/integrations/airvisual/

**Version**

_No response_

**Comment by bachya** [comment]
@tannisroot Good catch! I'll get this corrected.

>However, even though this is an issue for HA itself, I should note that there seems to loss of functionality, as the configuration option allowed the user to specify a city as the location instead of coordinates, and from what I've seen, levels of pollution for a specific city seem to differ from pollution levels at coordinates the same as the center of that city, for whatever reason.

This isn't correct. When you configure AirVisual via the UI, you can select the city/state/country option:

![CleanShot 2021-02-23 at 17 00 26](https://user-images.githubusercontent.com/47216/108924813-a5dd1200-75f8-11eb-940e-4b9b7e4c191a.png)

**Comment by tannisroot** [comment]
Is that a new feature that is yet to be included in a release? Because I don't see such option in my 2021.2.3 instance.

**Comment by bachya** [comment]
@tannisroot Ah, excellent point! It's in the `dev` branch, so I expect it will be in 2021.3.0.

For reference, it was implemented here: https://github.com/home-assistant/core/pull/44116

**Comment by tannisroot** [comment]
Awesome! Thank you very much for your response.
