### ISSUE TITLE
Failed to Connect - Doc?

### ISSUE THREAD

**Issue by gar37bic** [home-assistant/home-assistant.github.io#16701]
**Feedback**
[Edit] Sorry, I did not realize this was at the top level of integrations etc. I was posting with reference to the Network UPS Tools [NUT] integration. I guess I'm just lost :{ I will try to find the integration and see if there is anything obvious.

Thanks for creating this integration. I, and some others apparently, have gotten NUT working fine on our RPi servers but when trying to configure the HA integration the only options are username and password, and every combination tried just results in a message "Failed to Connect, please try again.". Nobody seems to have any ideas on how to fix this issue, whether it's a configuration or permission problem, or an actual bug.

**URL**

https://www.home-assistant.io/integrations/nut/

**Version**

2021.2.3

https://melgrubb.com/2016/12/11/rphs-v2-ups/ is the documentation I used to set up NUT.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues with integration documentation, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places. If you, however, come to the conclusion this is a documentation error. Please let us know! 👍 

Thanks! 👍
