### ISSUE TITLE
RAZBERRY BOARD - proposed change

### ISSUE THREAD

**Issue by GitPetri** [home-assistant/home-assistant.github.io#16703]
**Feedback**

It is possible to have both Bluetooth and the GPIO pins, at least for RazBerry2, enabled at the same time.
Instead of having entries
          dtoverlay=disable-bt
          enable_uart=1
in config.txt, the proposed entries are
          dtoverlay=miniuart-bt
          core_freq=250
The 1st line switches BT to the miniUART and the 2nd line is needed with miniUART BT to set the VPU core clock to a fixed frequency, this is required based on https://www.raspberrypi.org/documentation/configuration/uart.md / UARTs and Device Tree -section, 3rd chapter.
https://github.com/home-assistant/operating-system/issues/1237

**URL**

https://www.home-assistant.io/docs/z-wave/device-specific/

**Version**

2021.2.3

**Comment by frenck** [comment]
This is the deprecated documentation for the old (deprecated) z-wave integration. These pages need to be moved in order to avoid confusion.

**Comment by GitPetri** [comment]
If there is a later version of the instructions, the settings change proposal still applies.
