### ISSUE TITLE
Suggest someone add "Home Assistant Server" to glossary

### ISSUE THREAD

**Issue by tnelson32** [home-assistant/home-assistant.github.io#16715]
**Feedback**

Suggest someone add "Home Assistant Server" to glossary. I'm having trouble identifying just exactly what this means and what it is and what its "scope" is.

**URL**

https://www.home-assistant.io/docs/glossary/

**Version**

2021.2.3

**Comment by frenck** [comment]
Honestly, I don't know what "Home Assistant Server" is even? Could you maybe point me in the direction where you've picked up this term?

**Comment by frenck** [comment]
Closing this feedback, as I don't know what it is either and didn't get a response back. Feel free to add a response when available again 👍

**Comment by tnelson32** [comment]
Sorry Frenck, I responded to the email I got from you from notifications@github.com. That looks very generic, I guess I should have posted back here. For what its worth this was my response:

I keep seeing it while googling for results for various things I'm trying to do or otherwise understand as a HA newbie.

A few examples search for "home assistant server" (with quotes) on these pages:

    https://github.com/home-assistant-ecosystem/home-assistant-cli
    https://github.com/home-assistant/core/issues/44918
    https://socraticowl.com/post/home-assistant-quick-start-tips/
    https://www.home-assistant.io/integrations/sonos/

I guess I'm mostly seeing it on sites other than home-assistant.io domain (except home-assistant.io for some descriptions/discussions of various add-ons)

google "home assistant server" (with the quotes) and you get 11,300 results.

add "site:home-assistant.io" (no quotes) to the search and you get far fewer results (927) so I guess its used much less often on the HA website.

I guess I just need to understand its probably being used "loosely" and then try to figure it out in the context of how its being used

**Comment by frenck** [comment]
Oh indeed we have a couple of occurrences on our website, that should not be there. So let's clean those up.

Third-party websites: There is not much I can do about that.

In the cases I've seen, they are just referring to the machine that runs Home Assistant. But as said before, that is not a term we generally use (or should use).
