### ISSUE TITLE
Provide ability to only track selected devices

### ISSUE THREAD

**Issue by lanrat** [home-assistant/home-assistant.github.io#16720]
**Feedback**

This device_tracker integration is great, but I have a LOT of wireless devices on my network and it pollutes the Home Assistant device database with all of them.

It would be nice if I could specify an allow list of mac addresses of the few devices I actually want to track.

**URL**

https://www.home-assistant.io/integrations/ruckus_unleashed/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
