### ISSUE TITLE
Supported hardware

### ISSUE THREAD

**Issue by carryonrewardless** [home-assistant/home-assistant.github.io#16725]
**Feedback**

I have a NAD C368 with a BluOS 2i module and cannot get it working using type=TCP.  Entity shows as unknown.  

Is there a list of supported hardware anywhere that could be linked?

**URL**

https://www.home-assistant.io/integrations/nad/

**Version**

2021.2.3

I have not specified a port number (Telnet only?)
sudo nmap -sS  192.168.1.88
[sudo] password for rbrown: 
Starting Nmap 7.80 ( https://nmap.org ) at 2021-02-24 22:13 AEDT
Nmap scan report for 192.168.1.88
Host is up (0.0074s latency).
Not shown: 995 closed ports
PORT      STATE SERVICE
8008/tcp  open  http
8009/tcp  open  ajp13
8443/tcp  open  https-alt
9000/tcp  open  cslistener
10001/tcp open  scp-config
MAC Address: 90:0C:C8:DD:2C:4C (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 0.57 seconds

**Comment by frenck** [comment]
According to the upstream package used:

> Note that the RS232 interface is only tested with the NAD T748v2. Commands are implemented based on the T748v2. Those commands should work with more NAD receivers. The Telnet interface is only tested with the NAD T787. 

<https://github.com/joopert/nad_receiver>
