### ISSUE TITLE
This documentation unclear, I don't understand how the discovery topic is related to the device! 

### ISSUE THREAD

**Issue by paganl** [home-assistant/home-assistant.github.io#16738]
**Feedback**

I don't understand how the discovery topic is related to the device! I still haven't gotten this to work. I can add devices manually, although the control of these devices is not working. This relates to zigbee2mqtt.  

**URL**

https://www.home-assistant.io/docs/mqtt/discovery/

**Version**

2021.2.3

**Comment by frenck** [comment]
This is the documentation for applications implementing the discovery protocol over MQTT. As a user, that is not really interesting. As for Zigbee2MQTT, it has support for speaking that discovery protocol, how to set it up in Zigbee2MQTT, is a question for that specific project.
