### ISSUE TITLE
Offer alternatives for storage extension, such as SSDs

### ISSUE THREAD

**Issue by erd82** [home-assistant/home-assistant.github.io#16736]
**Feedback**

Last resort: Would it make sense to describe also the extension of storage using SSDs?
- https://www.youtube.com/watch?v=WDCE4_sP5_E
- https://community.home-assistant.io/t/installing-home-assistant-on-a-rpi-4b-8gb-with-ssd-boot/230948

**URL**

https://www.home-assistant.io/more-info/free-space/

**Version**

2021.2.3

**Comment by frenck** [comment]
None of the methods linked are supported by Home Assistant, and thus not recommended. Therefore, not part of our documentation.
