### ISSUE TITLE
Crime Reports No Longer Supported

### ISSUE THREAD

**Issue by heytcass** [home-assistant/home-assistant.github.io#16731]
**Feedback**

Went to file a PR on the core code about Crime Reports, because the crimereports.com website has an invalid SSL sert, which seems to be breaking the component. However, I could not find any reference to the crimereports integration in the core code anywhere. Has support been removed? If so, this page should be taken off the site. If not, it should be considered to be removed anyway.

**URL**

https://www.home-assistant.io/integrations/crimereports/

**Version**

2021.2.3

**Comment by frenck** [comment]
The integration is pending deletion for Home Assistant Core 2021.3
