### ISSUE TITLE
Lacking documentation for custom component Sure petcare on how to utilize binary sensors

### ISSUE THREAD

**Issue by brnstd-dev** [home-assistant/home-assistant.github.io#16749]
**Feedback**

Lacking documentation for Sure Petcare custom component.

I'm using the "binary_sensor.pet_\<name\>" entity and the "where" attribute to trigger an automation when a pet either entered or left via the flap. But I'm having a hard time decoding from binary_sensors.py how I can differentiate whether the pet entered or left, and it seems there is no documentation on the sensors?

**URL**

https://www.home-assistant.io/integrations/surepetcare/

**Version**

2021.2.3

**Comment by frenck** [comment]
The binary sensors in general only have a `on` or `off` state, additionally, attributes can be provided (which are visible when you look at an entity in the UI). In this case the `where` attribute, which can be automated on as a normal, regular attribute.

I'm not entirely sure what your feedback or question is in this case. It seems you are looking for general Home Assistant guidance and working, and not specifically guidance on the workings of this integrations.

Could you provide me with a more clear example on what you are trying to make?

**Comment by brnstd-dev** [comment]
I think you're correct that my question is more general. However, you provided the response I needed:

> attributes can be provided (which are visible when you look at an entity in the UI).

I'm trying to trigger a script only when my pets state changes from outside to inside. My problem was figuring out which string to provide in fields "from" and "to":

![image](https://user-images.githubusercontent.com/65893730/109290999-ab20a380-7828-11eb-8459-7f60fc2782df.png)

The state might already be "Inside", in case the pet was let out by any means other than the pet flap, but I'm assuming the binary sensor will trigger even though the previous and current state attribute values are equivalent. Will update this when it's been tested.

**Comment by frenck** [comment]
⚠️ Please note, things are case sensitive 👍

**Comment by brnstd-dev** [comment]
> ⚠️ Please note, things are case sensitive 👍

Yep, noted, thanks again! 👍
