### ISSUE TITLE
Shopping list add properties

### ISSUE THREAD

**Issue by LukeScrewdriver** [home-assistant/home-assistant.github.io#16747]
**Feedback**

Can you insert the possibility to create more lists visible only to some users?

**URL**

https://www.home-assistant.io/integrations/shopping_list/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
