### ISSUE TITLE
My Home Assistant "Add Integration" badge display issue for some integrations

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/home-assistant.github.io#16743]
**Feedback**

Some integrations lack a full width logo and use a smaller icon size for their brand images. The new My Home Assistant "Add Integration" badge displays a bit weirdly in these cases, right next to the image without any spacing (see screenshots below).

Examples of such integrations are [IPP](https://rc.home-assistant.io/integrations/ipp/), [iCloud](https://rc.home-assistant.io/integrations/icloud/), [Transmission](https://rc.home-assistant.io/integrations/transmission/), [Sonarr](https://rc.home-assistant.io/integrations/sonarr/), [Subaru](https://rc.home-assistant.io/integrations/subaru/), [OwnTracks](https://rc.home-assistant.io/integrations/owntracks/), [Profiler](https://rc.home-assistant.io/integrations/profiler/), etc.

(edit: sorry, didn't mean for the bot to tag anyone, was just linking a couple example pages that had this visual issue)

**Version**

rc (2021.3.0b0)

<img width="362" alt="Screen Shot 2021-02-25 at 2 02 28 AM" src="https://user-images.githubusercontent.com/9065557/109115774-8a176000-770d-11eb-8679-57dae15fa874.png">

<img width="358" alt="Screen Shot 2021-02-25 at 1 56 17 AM" src="https://user-images.githubusercontent.com/9065557/109115184-aff03500-770c-11eb-8973-3038a270e3dc.png">

**Comment by ludeeus** [comment]
Which browser, resolution, and OS do you use?

**Comment by frenck** [comment]
Issue has been fixed in #16746
