### ISSUE TITLE
Integration failed to connect.

### ISSUE THREAD

**Issue by mjacobs63** [home-assistant/home-assistant.github.io#16748]
**Feedback**

I signed up for an account with Smart Meter Texas and am able to log into their page with my credentials.  When I attempt to configure the Smart Meter Texas integration using the same credentials it says it "failed to connect".

**URL**

https://www.home-assistant.io/integrations/smart_meter_texas/

**Version**

2021.2.3

**Comment by frenck** [comment]
Hi there, this is the issue/feedback tracer for the documentation (the content). If you have a technical issue with an integration itself, please report your issue here:

<https://github.com/home-assistant/core/issues>
