### ISSUE TITLE
Confused and frustrated 

### ISSUE THREAD

**Issue by paganl** [home-assistant/home-assistant.github.io#16740]
**Feedback**

Why is the supervisor option not available when I used a docker container, and why can I not add it. a lot of most documentation refers to this option; for example, I've been struggling with zigee2mqtt, which though node-red I've been using for some time, but I cannot get this to work with Home Assistant 

**URL**

https://www.home-assistant.io/installation/

**Version**

2021.2.3

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/109079789-bc21c580-76ff-11eb-92f8-ef06db4f9b13.png)

This table is shown at the bottom of that page you left this feedback on. The Supervisor is part of an installation type, and not a program one can just go and install.

Not sure what your suggestion is in this case?

>  I've been struggling with zigee2mqtt, which though node-red I've been using for some time, but I cannot get this to work with Home Assistant

Those are external and third-party applications, we cannot help you with that. If you struggle with using those, please contact the third-party creator for that.

**Comment by paganl** [comment]
I have an issue with those third-party applications; concerning said issue(s), third-party documentation refers to the "supervisor", which is not available in the container install. (as I now understand it). I don't understand why functionality is missing; that obviously seems important as it's referred to in multiple documents. If nothing else, it confusing and inconsistent.

**Comment by frenck** [comment]
> third-party documentation refers to the "supervisor", which is not available in the container install.

That would be correct and is reflected in the page referenced as well.

>  I don't understand why functionality is missing

I'm confused on the relevance of this? There are multiple ways to install Home Assistant, each installation type has pros and cons.

Some come with a complete operating system, others you provide your own. Some come with the Supervisor that manages parts of your system (including Docker), others you manage Docker (Container setup).

The Supervisor is not just a tool you can just go and install on any system. Its not a checkbox, its part of the ecosystem you install/choose. 

So I'm confused on your confusion. You want something that simply isn't possible on the installation type of choice 🤷

**Comment by paganl** [comment]
I have everything running in node-red, what I wanted was a simple dashboard and a way to give family members (children) there own dashboards, so it's not easy for Sarah to control Anne's devices. I was hoping HA could help be achieve this and reduce the amount of time much I was already spending at the keyboard. I'm not sure HA will achieve this anyway. Like most people, this isn't my full-time job, and it was taking far too much time. I guess this is a case of RTM; I've just gone over the architecture and now understand. However, this still doesn't explain why my zigbee2mqtt devices are not discovered.

**Comment by frenck** [comment]
Zigbee2MQTT is a third-party piece of software not provided by this project. If you need support with that, please check the support resources offered by that application.

**Comment by frenck** [comment]
Closing this issue at this end. The properties are documented here; and other raised issues are third-party related.
