### ISSUE TITLE
Missing Content

### ISSUE THREAD

**Issue by Sanitys** [home-assistant/home-assistant.github.io#16741]
**Feedback**

This page is linked to from https://www.home-assistant.io/integrations/smartthings/ and says Setup remote access via a domain name secured with SSL. Self-signed SSL certificates are not supported by the SmartThings Cloud API. But this page linked does not contain info on how to install SSL certs in homeassistant.

**URL**

https://www.home-assistant.io/docs/configuration/remote/

**Version**

2021.2.3

**Comment by andrewsayre** [comment]
This appears to be a support request rather than an issue. Please consult the forums, discord, or google your question (there are many results on how to setup SSL in Home Assistant).
