### ISSUE TITLE
Suggest : add "theme"

### ISSUE THREAD

**Issue by Rapace29** [home-assistant/home-assistant.github.io#16753]
**Feedback**

i suggest to add "theme" function, or at lease the capability to change "background color". ( when card is in transparency mode, it's unreadable).

**URL**

https://www.home-assistant.io/lovelace/history-graph/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback and issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
