### ISSUE TITLE
Reference to python3.8 does not work

### ISSUE THREAD

**Issue by wora55** [home-assistant/home-assistant.github.io#16759]
**Feedback**

The example on the page refers to pythin3.8, which is not found. Using 'python' seems to solve the problem

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

Secondary problem: When building homeassistant an error occurs:
"requests 2.25.0 has requirement idna<3,>=2.5, but you'll have idna 3.1 which is incompatible."

**Comment by frenck** [comment]
This can differ based on the platform installed and the way one manages their Python environments. We consider this an advanced installation method, that one is familiar with and knows how to adopt too.

If not, I would strongly recommend using one of the generally recommended installation methods, Home Assistant Operating System or Home Assistant Container.

**Comment by wora55** [comment]
ok, thanks for the instant reply

Franck Nijhof schrieb am Freitag, 26. Februar 2021 14:27:43 (+01:00):



This can differ based on the platform installed and the way one manages their Python environments. We consider this an advanced installation method, that one is familiar with and knows how to adopt too.

If not, I would strongly recommend using one of the generally recommended installation methods, Home Assistant Operating System or Home Assistant Container.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
Wolfgang Radke Schubertstr. 6f 76344 Eggenstein
