### ISSUE TITLE
No mentioning of WiFi anywhere?

### ISSUE THREAD

**Issue by michaelaye** [home-assistant/home-assistant.github.io#16750]
**Feedback**

First I was even at a loss if Wifi is supported on a RPi4 at all, as the installataion, the configuration and the advanced configuration doesn't mention it at all. Until I finally found a WLAN configuration interface in the Supervisor tab.

**URL**

https://www.home-assistant.io/getting-started/configuration/

**Version**

2021.2.3

**Comment by frenck** [comment]
That would be correct. We don't recommend using Wi-Fi, and Wi-Fi is not available in all situations either. Thus, for those reasons, not part of the getting started guide.

Nevertheless, thanks for your suggestion 👍
