### ISSUE TITLE
Unlatch integration

### ISSUE THREAD

**Issue by Stan191** [home-assistant/home-assistant.github.io#16768]
**Feedback**

Unlatch option not present after following the guid

**URL**

https://www.home-assistant.io/integrations/nuki/

**Version**

2021.2.3

**Comment by Donaldini** [comment]
I have this issue too. No devices or entities present after connecting:

![image](https://user-images.githubusercontent.com/2185680/111036190-53845980-841e-11eb-9e88-312a3f29886e.png)

**Comment by frenck** [comment]
Seems like you are reporting an integration bug, however, this is the issue tracker for documentation feedback. There is no amount of documentation that I can adjust to fix an integration bug.

Please report bugs with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
