### ISSUE TITLE
web interface certs

### ISSUE THREAD

**Issue by adamf663** [home-assistant/home-assistant.github.io#16764]
**Feedback**

Why is there no documentation on installing 3rd party certs?  My pfsense router has letsencrypt and pushes the certs to /ssl on home assistant.  But nothing I do can make home assistant's web UI use them.

**URL**

https://www.home-assistant.io/docs/configuration/securing/

**Version**

2021.2.3

**Comment by frenck** [comment]
The use of SSL certificates is documented as part of the `http` webserver integration (that services all other parts of system):

<https://www.home-assistant.io/integrations/http#ssl_certificate>

**Comment by adamf663** [comment]
Why does the web interface, lovelace, never use them? In configuration.yaml:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

The new (ignored) cert is from lets encrypt.  I use my pfsense firewall to automatically renew the cert and copy it over.  It seems HA uses them internally, but never updates the UI webserver.

**Comment by frenck** [comment]
If the certificate is renewed, the application must restart to pick them up.

**Comment by adamf663** [comment]
I would think rebooting would do the trick.  Maybe there some letsencrypt optimization going on.
The webui cert is dated 2/1/2021 while the cert/key in /ssl is dated 2/25.

----- Original Message -----
