### ISSUE TITLE
Update to python 3.9.x

### ISSUE THREAD

**Issue by wora55** [home-assistant/home-assistant.github.io#16762]
**Feedback**

Just installed for the second time because 'hass' told me, that python 3.8 will not be supported anymore after December of 2020 (which was fortunately not so)
Might add that to the top of the installation instructions, saves time

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

**Comment by ludeeus** [comment]
That was 3.7, you need 3.8+ to install Home Assistant as stated at the top of the Core instructions <https://www.home-assistant.io/installation/raspberrypi/#install-home-assistant-core>

**Comment by frenck** [comment]
3.8 & 3.9 are supported Python versions at this moment in time, none of those are unsupported, deprecated or any of those. Python 3.8 will be deprecated when Python 3.10 gets released (probably the fall of this year).
