### ISSUE TITLE
certificates

### ISSUE THREAD

**Issue by adamf663** [home-assistant/home-assistant.github.io#16763]
**Feedback**

Why does there seem to be no documentation on installing certs for the web frontend?  I want to get away from letsencrypt as my setup is behind a nat, isn't the only device with a web service and I don't want to redirect all HTTP (port 80) traffic to one device.

**URL**

https://www.home-assistant.io/integrations/frontend/

**Version**

2021.2.3

**Comment by frenck** [comment]
Setting SSL certificates is not part of the frontend, but part of the HTTP server:

<https://www.home-assistant.io/integrations/http#ssl_certificate>
