### ISSUE TITLE
offending containers

### ISSUE THREAD

**Issue by beny18241** [home-assistant/home-assistant.github.io#16769]
**Feedback**

where is the list of the containers? 

**URL**

https://www.home-assistant.io/more-info/unsupported/container/

**Version**

2021.2.3

**Comment by frenck** [comment]
That is hardcoded, nevertheless, ADR-0014 states:

> No additional software, outside of the Home Assistant ecosystem, is installed.

<https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#additional-supported-conditions>

This means it doesn't matter, as any additional container renders it unsupported.
