### ISSUE TITLE
Integration Tags

### ISSUE THREAD

**Issue by DanielXYZ2000** [home-assistant/home-assistant.github.io#16777]
**Feedback**

It is great to see how tne number of integrations is growing. 
It would be great to have the integrations tagged, so filter can be applied. Currently there are only the categories on the left side with then numbers of integrations in brackets. 
The idea is to be able to filter like e.g. at some shopping pages https://geizhals.at/?cat=nb
and use additional tags/categories for filtering: e.g.
introduces in release (information already available)
last update in release ( information could be extracted out of github repo?)
dev activity on release ( nformation could be extracted out of github repo? - indicates community is improving the integration)
privacy level (does the integration act only in the local network, encrypted?,...,e.g.  some cameras only work with cloud connection, - I would filter these )
cost (are there monthley payments for the service? e.g. spotify premium)
usage: (if HA useres share the metrics - how many users are using this integration? - how popular is it?)
type: device, service, core function
API key needed?
open source ?
open hardware (e.g. TagReader is open source and open HW, also many DIY stuff is open source, HW)

**URL**

https://www.home-assistant.io/integrations/

**Version**

2021.2.3

**Comment by frenck** [comment]
> introduces in release (information already available)

Is already available as filter:

![image](https://user-images.githubusercontent.com/195327/109419637-bd3c4680-79ce-11eb-9610-ca3df52919e4.png)

> last update in release ( information could be extracted out of github repo?)
> dev activity on release

That information isn't available. It is under discussion in the architecture repository.
The git repository does not provide that information, as most integrations can be touched by e.g., translation updates, which is not a real integration update at all.

Last touched on dev, is not possible at all. Branches are decoupled and the website is static.

> privacy level (does the integration act only in the local network, encrypted?,...,e.g. some cameras only work with cloud connection, - I would filter these )

We have IoT class for that.


> cost (are there monthley payments for the service? e.g. spotify premium)
> usage: (if HA useres share the metrics - how many users are using this integration? - how popular is it?)
> type: device, service, core function
> API key needed?
> open source ?
> open hardware (e.g. TagReader is open source and open HW, also many DIY stuff is open source, HW)

Most of these are question about the thing that is integrated with, and are not a concern or influenced by the integration.

**Comment by DanielXYZ2000** [comment]
Thanks, I think got the first points. Regarding the IoT class - this information can not be used for filtering yet.

As a home assistant user I 
- a) want to browse through the available integrations for an component e.g. doorbell to find one, which fits my needs (like privacy requirements), which I just can buy and integrate in home assistant - so if I could filter by IoT class this would directly bring me to Doorbird (local push)
- b) want to browse through all all available integrations and select based on (is it free, hardware required, do I need to register?) 
e.g. for weather that would lead to netatmo -> HW needed; vs. Deutscher Wetterdienst (DWD)  - no API /registration needed, 

I'm not sure if I got 
> Most of these are question about the thing that is integrated with, and are not a concern or influenced by the integration.
rigth!? - the properties of the "thing" that is integrated by the integration affect my decision if I want to use this integration or not.
I really apprechiate that home assistant integrates e.g. alexa and google home, but if I want to focus on privacy, I would filter all these kind of integrations out.
