### ISSUE TITLE
Tag names

### ISSUE THREAD

**Issue by oywino** [home-assistant/home-assistant.github.io#16775]
**Feedback**

Tags are named during creation. Are these names to be considered as "Friendly Names" ?
What use do these names have (except from being visible under Configuration --> Tags)
Can the Name be used in an Automation to reference a tag?

**URL**

https://www.home-assistant.io/integrations/tag/

**Version**

2021.2.3

**Comment by frenck** [comment]
> What use do these names have (except from being visible under Configuration --> Tags)

Purely a human-readable reference.

> Can the Name be used in an Automation to reference a tag?

No, they can not.

**Comment by oywino** [comment]
Well, that doesn't seem to be entirely true. I tried this, and it works:

![image](https://user-images.githubusercontent.com/18447119/109426359-a48f5900-79ed-11eb-9d96-4e0c06051097.png)

Except, in YAML, the tag name is automatically converted to the hex-ID.

**Comment by frenck** [comment]
? That is still a human-readable reference used by the UI. I'm not sure what the documentation feedback is in this case?
