### ISSUE TITLE
Feature request - Lovelace Grid Card

### ISSUE THREAD

**Issue by FragMenthor** [home-assistant/home-assistant.github.io#16772]
**Feedback**

Would it be possible to add the option, for a size, in percentage of the total, to each card in the grid? Thanks!!!

**URL**

https://www.home-assistant.io/lovelace/grid/

**Version**

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
