### ISSUE TITLE
After changing to the integration device tracker has broke

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/home-assistant.github.io#16786]
**Feedback**

Old configuration yaml:
```
evice_tracker:
  - platform: asuswrt
    host: 192.168.1.1
    username: !secret dt_un
    password: !secret dt_pw
    new_device_defaults:
      track_new_devices: true
```
No documentation on changes needed.

**URL**

https://www.home-assistant.io/integrations/asuswrt/

**Version**

2021.3.0

Worked first time with no issue.  Did a restart and got two errors.
The following integrations and platforms could not be set up:

device_tracker
proximity
Logger: homeassistant.setup
Source: setup.py:118
First occurred: 12:23:10 PM (1 occurrences)
Last logged: 12:23:10 PM

Unable to set up dependencies of proximity. Setup failed for dependencies: device_tracker

Logger: homeassistant.setup
Source: components/device_tracker/legacy.py:279
First occurred: 12:23:09 PM (1 occurrences)
Last logged: 12:23:09 PM

Error during setup of component device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/__init__.py", line 52, in async_setup
    await async_setup_legacy_integration(hass, config)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 153, in async_setup_integration
    legacy_platforms = await async_extract_config(hass, config)
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 279, in async_extract_config
    raise ValueError(
ValueError: Unable to determine type for asuswrt: None
Found I needed to delete the tracker yaml.  It now works again.  Need to update the documents.

**Comment by frenck** [comment]
`2021.3.0` is in beta right now, please read the breaking changes section of the beta release notes.

**Comment by bschatzow** [comment]
I did read this.  On the Asus docs it does not have any information on this.  I was trying to just update this to help others.

**Comment by frenck** [comment]
> Found I needed to delete the tracker yaml. It now works again.

That is documented as breaking change in the release notes. So I'm confused about your last message.
