### ISSUE TITLE
Changing category names

### ISSUE THREAD

**Issue by Balbao** [home-assistant/home-assistant.github.io#16784]
**Feedback**

Hello. How do I change the language? To put "light" "moisture" "conductivity"  in another language. When you change the names, they take the same name at each update.Thanks

**URL**

https://www.home-assistant.io/integrations/miflora/

**Version**

2021.2.3

**Comment by frenck** [comment]
This integration does not provide unique IDs for its entities, which means that is not possible.

Adding/implementing such a thing, would be a feature request, for which we use our community forum; not this issue tracker.
