### ISSUE TITLE
Smart bulbs in Tuya importing as Switches

### ISSUE THREAD

**Issue by TikiRoomSchmidt** [home-assistant/home-assistant.github.io#16787]
**Feedback**

I'm using the Smart Life app to do the import and the bulbs are Merkury Innovations from Walmart. I have other switches as well as other smart bulbs coming in through the Tuya integration that is working correctly. 

They're popping into Alexa correctly as rgb lights, so I'm not sure it's the app or bulb's problem.

**URL**

https://www.home-assistant.io/integrations/tuya/

**Version**

2021.2.3

**Comment by ollo69** [comment]
This a limitation of dedicated Tuya API used by HomeAssistant, some light devices is identified as switch. Only Tuya could solve this issue correcting the API. Refer to integration documentation for more details.
