### ISSUE TITLE
venv: error: the following arguments are required: ENV_DIR

### ISSUE THREAD

**Issue by torinnguyen** [home-assistant/home-assistant.github.io#16789]
**Feedback**

Error when executing this command:
python3.9 -m venv
venv: error: the following arguments are required: ENV_DIR

**URL**

https://www.home-assistant.io/installation/raspberrypi/

**Version**

2021.2.3

I'm following the installation instructions on rpi as documented.
Tested with python 3.9.2

cd /srv/homeassistant
python3.9 -m venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear] [--upgrade] [--without-pip] [--prompt PROMPT] [--upgrade-deps]
            ENV_DIR [ENV_DIR ...]
venv: error: the following arguments are required: ENV_DIR

**Comment by frenck** [comment]
You are missing an argument:

![image](https://user-images.githubusercontent.com/195327/109478128-25476700-7a79-11eb-8ad2-47a71079da0a.png)


There is a `.` (dot) at the end.

`python3.9 -m venv .`
