### ISSUE TITLE
Garmin Connect integration

### ISSUE THREAD

**Issue by OBubnik** [home-assistant/home-assistant.github.io#16792]
**Feedback**

Hello,
I've tried to integrate Garmin Connect to my Home Assistant. The integration finished correctly. But all entities are with status "unknown".
I did it repeatedly with the same result. Even when I switched off all entities except one "sensor.total_steps" where I'm sure should be some data.

**URL**

https://www.home-assistant.io/integrations/garmin_connect/

**Version**

2021.2.3

![Snímek obrazovky 2021-03-01 140859](https://user-images.githubusercontent.com/79849217/109501311-b88f9500-7a97-11eb-9822-30a884adc318.png)

**Comment by frenck** [comment]
Hi there, this is the feedback/issue tracker for our documentation, however, it seems like you are trying to report an issue with a Home Assistant Core integration.

Please report those issues here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
