### ISSUE TITLE
This is the biggest drawback of HA - automation editor for nerds

### ISSUE THREAD

**Issue by MBarti** [home-assistant/home-assistant.github.io#16793]
**Feedback**

Parentheses, entity.IDs, etc. are not a language a normal user should know or be using.

I'm sure this has been discussed before, but seriously, this is by far the biggest hurdle hampering HAs growth. Automations need a simple visual editor, with Icons, understandable language, big buttons .... you know, for normal people.
And no, installing node-red, does not solve it.

**URL**

https://www.home-assistant.io/docs/automation/editor/

**Version**

2021.2.3

**Comment by frenck** [comment]
This will be addressed in the next release of Home Assistant Core (2021.3.0), which will bring a UI to those things:

![image](https://user-images.githubusercontent.com/195327/109503515-ab27da00-7a9a-11eb-841b-a15f0bf187b7.png)

**Comment by MBarti** [comment]
A small step in the right direction, byt MY GOD, is this still using the horrible flow, language and editable fields?
"Pick entity"?
Filling in a form with RGB-format? Really? How would my dad be able to use it? :)

**Comment by MBarti** [comment]
The User story is not "I want to call a lighting service , by filling out a form with editable fields for desired color characteristics".

**Comment by frenck** [comment]
> How would my dad be able to use it? :)

Maybe he is not the target audience.

**Comment by MBarti** [comment]
Maybe the target audience should be the same as it is for the home automation system that are actually winning market share among non-technical people. Like Alexa, Homekit, etc.
A few taps on the app is all it takes to set up automations. Not form-filling, learnidn about IDs and calling services.

The interface you showed is just a prettier image of a very broken logic.
It's very simple to fix it, as all the other pieces are there (like simple install, nice visual control panel, etc.)

**Comment by spacegaier** [comment]
Let's move the discussion to the frontend repo discussion you created rather than here in the documentation repo (wrong place).
