### ISSUE TITLE
improve instruction for new users

### ISSUE THREAD

**Issue by bjorns163** [home-assistant/home-assistant.github.io#16797]
### Feedback

I’m new to this ha . I've been head budding myself over how to add a integration, this is the first one I wanted to add, and it took me way to long even when I’m in IT...... I guess understanding the basics would make understanding this instruction easy. but for new user I am missing vital information.

things to improve:
put in this link   https://www.home-assistant.io/getting-started/configuration/ helps new users about  configuration.yaml

 change:
evohome:
  username: YOUR_USERNAME
  password: YOUR_PASSWORD

to:

evohome:
  username: "YOUR_USERNAME"
  password: "YOUR_PASSWORD"

put a note in to restart the configuration after editing and mention to wait for rescan 300 seconds or force rescan by going to: service call and run evohome.refresh_system https://www.home-assistant.io/docs/scripts/service-calls/

Hope this helps the next person who is new to this :D

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2021.2.3

**Comment by frenck** [comment]
> put in this link home-assistant.io/getting-started/configuration helps new users about configuration.yaml

That we should not do, as it would riddle our documentation with it. However, it would be awesome if this integration could be moved over to the UI some day, in that case, this all isn't needed anymore :)

The YAML change suggested is good. This matches our recently introduced YAML standards, however, we are currently implementing those. I'll open up a PR to address that.

> put a note in to restart the configuration after editing and mention to wait for rescan 300 seconds or force rescan by going to

That I don't know, so hopefully @zxdavb can help with that 😁
