### ISSUE TITLE
Add more details to snapshots

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/home-assistant.github.io#16791]
**Feedback**

I see no documentation on snapshots and I would like to add information.  Not sure how or where.  The only mention of snapshot is on the common task doc.

**URL**

https://www.home-assistant.io/common-tasks/os/

**Version**

2021.2.3

I would be happy to try and help by capturing screen shots and directions.  Just need more information on how to do this.

**Comment by frenck** [comment]
> Just need more information on how to do this.

I'm not entirely sure on your question there? Could you be more specific on the question you have?

**Comment by bschatzow** [comment]
I think you addressed this on discord. What I think is needed is a sperate doc. You do not. I'll add to the existing doc and we will go from there. I know you are very good with HA and I appreciate all you do. I think you sometimes forget what should be obvious to us (me) is not. I assume that if it isn't obvious to me, others may have the same issue and I want to address this with doc changes.
