### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by skipishere** [home-assistant/home-assistant.github.io#16799]
### Feedback

The documentation mentions `Note: Switch entity requires api_key to be configured.` but nowhere does it specify where the api_key is meant to be added or used. The integration doesn't provide a way to add this and there doesn't appear to be any yaml generated that I can edit.

### URL

https://www.home-assistant.io/integrations/pi_hole/

### Version

2021.2.3

**Comment by frenck** [comment]
Thanks for reporting this @skipishere!

It seems like that line is originating from an older era. Setting an API key, is part steps when adding the Pi-Hole integration to Home Assistant. I've opened up a pull request to adjust the documentation to make that more clear.

**Comment by skipishere** [comment]
Having had to re-setup  a Pi Hole integration yesterday there doesn't appear to be any way to add in the API key via the UI. 😢

**Comment by frenck** [comment]
It is asked during the integration add/set up procedure (second step).

**Comment by skipishere** [comment]
Not sure if I had something left over from previous integration, looks like removing, rebooting and then re-adding it now it asks for the API key 🤷 
Sorry to have been a pain.

**Comment by frenck** [comment]
Don't worry! Thank you for bringing it up, as it helped to improve the documentation 👍
