### ISSUE TITLE
Inconsistent documentation for "default" schema

### ISSUE THREAD

**Issue by alexfranke** [home-assistant/home-assistant.github.io#16794]
### Feedback

The chart under the "Comparison of light MQTT schemas" heading suggests that flashing and transitions are NOT supported by the "default" schema. The text under the following heading ("Default schema") states that flashing and transitions ARE supported by the "default" schema. I suspect that flashing and transitions should be removed from the text in the "Default schema" heading, but I'm new to this so I'm not entirely sure. 

### URL

https://www.home-assistant.io/integrations/light.mqtt/

### Version

2021.2.3

![image](https://user-images.githubusercontent.com/1649271/109552372-b0d3ee80-7a9f-11eb-9998-27f3bbae41f2.png)

**Comment by emontnemery** [comment]
Thanks for reporting this!

**Comment by frenck** [comment]
Adjusted in #16795
