### ISSUE TITLE
Windows Options!

### ISSUE THREAD

**Issue by Tim-Ayling** [home-assistant/home-assistant.github.io#16803]
### Feedback

The cost in terms of time researching and reading how to install this product is incalculable.

I read all the reviews and decided that Home Assistant was probably the best suited and able system I had read about, so I set about installing it. I started playing with Windows when it was Windows286. I have never played with any Linux derivative. So I obviously checked that Home Assistant would run on Windows - yeah, right!

Your stated 3 installation options:

1. VirtualBox. Download and install this. It works, but the problems of installing the most basic (and recommend by your forums) hardware are (so far) insurmountable to a Windows user - and I'm very experienced - and a coder for over 50 years (but that's not to do with this page).

2. KVM. Why is this here. It doesn't even run on Windows!

3. VMWare. We are talking about OpenSource software, right? So how come the stated Hypervisor setup options of line 2. "Custom, Workstation & ESX", then line 5. "Advanced, Firmware & UEFI" are only available in VMWare PRO at a cost of £100.

Don't get me started  on the time spent trying to get any of these running on Windows 7.

### URL

https://www.home-assistant.io/installation/windows/

### Version

2021.2.3

**Comment by frenck** [comment]
Support for Windows is limited. The only way of running this project correctly on Windows is using a virtual machine/hypervisor. This is due to the limitations of the Windows platform, as it is not fully operable and compatible with all other solutions out there.

We have made available virtual machine images for multiple different Hypervisors, the choice in which one to go with is really a personal choice.

**Comment by Tim-Ayling** [comment]
Hi Franck,

I understand support is limited.

However, the inclusion of KVM as one of the alternative VM/hypervisor options is ridiculous !

It is not available for any Windows platform at all, so what use is a VM image for Windows for a VM environment that doesn’t exist?

Personal choice is fine – but a choice that is non-existent is a waste of time and effort.

I know you guys do a fantastic job, but OS worldwide share is Windows 30%+, OS X 7%+ and Linux <1%. I just feel that you are losing out on a lot of support and help by not being a bit more Windows friendly.

Slowly, I have got my Z-Stick running and am trying to get my Zigbee kit running.

Kind regards

Tim

**Comment by frenck** [comment]
> OS worldwide share is Windows 30%+, OS X 7%+ and Linux <1%

That doesn't add up 😁 

> However, the inclusion of KVM as one of the alternative VM/hypervisor options is ridiculous !

Its not actually. Although I'm not a Windows user myself, KVM/QEMU options are available in WSL2.

**Comment by Tim-Ayling** [comment]
OK, even I can laugh at the absurdity of taking Win10, running Linux via WLS2, then running a VM to run HA.

As stated, I’m not a Linux user, but I would of thought HA would be a native application there – or not?

Plus, as an aside, because I don’t mind playing, is there no way of running it natively on Windows. I suppose it depends on the root language.


Tim

**Comment by frenck** [comment]
It depends on the problems the host OS, in this case Windows, brings, not the root language.

The options are set out in our documentation; if there isn't an option available for you; then it might be that Home Assistant isn't the right choice for you. Sorry.

**Comment by Tim-Ayling** [comment]
Thank you for your time Franck.

I am slowly getting to grips with it – and it is slowly coming together.

One of the biggest problems seems to be that everything I try requires editing ‘configuration.yaml’. v5.12 seems to ignore this in preference to the GUI, but the options aren’t yet there. Perhaps things like Onkyo monitoring just aren’t there yet.

I’ll persevere for a while yet.

Thanks again.

Tim

**Comment by frenck** [comment]
> One of the biggest problems seems to be that everything I try requires editing ‘configuration.yaml’.

We are moving away from that, but that takes a lot of time.
