### ISSUE TITLE
Lack of conceptual documentation

### ISSUE THREAD

**Issue by lcavaleiro** [home-assistant/home-assistant.github.io#16818]
### Feedback

I have been using Home Assistant for about 4 months now. I recognize that there is a lot of information, documentation and examples about this framework. However, despite having already implemented different integrations, I cannot understand the logic / architecture of Home Assistant. The document on the available architecture is very generic and does not show the integration between the different concepts. For example, despite having searched for many hours, I still haven't been able to understand what a "platform" is. Thus, I just can implement solutions using copies (after being adjusted) of examples available on the WEB.

### URL

https://www.home-assistant.io/docs/glossary/

### Version

2021.2.3

**Comment by frenck** [comment]
I'm not sure if this is feedback on the end-user documentation or the developers documentation?

**Comment by lcavaleiro** [comment]
I don't know exactley what is an end-user or a devoloper. for me, an End user is my wife that uses Home Assitant just to open a gate ou activate the AC. I think we mean End User as the guy that configure Home Assistant (define automations, install new integrations, add devices, etc). The developer is the one that create new  integration.

So I think I am an End User and I don't exactely know the logic behind the configuration.yaml (for instance)
