### ISSUE TITLE
Tahoma integration problem

### ISSUE THREAD

**Issue by hirekpl97** [home-assistant/home-assistant.github.io#16826]
### Feedback

Logger: homeassistant.setup
Source: components/tahoma/__init__.py:89
First occurred: 10:16:28 (1 occurrences)
Last logged: 10:16:28

Error during setup of component tahoma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tahoma/__init__.py", line 89, in setup
    api.get_setup()
  File "/usr/local/lib/python3.8/site-packages/tahoma_api/tahoma_api.py", line 156, in get_setup
    self._get_setup(result)
  File "/usr/local/lib/python3.8/site-packages/tahoma_api/tahoma_api.py", line 167, in _get_setup
    device = Device(self, device_data)
  File "/usr/local/lib/python3.8/site-packages/tahoma_api/tahoma_api.py", line 687, in __init__
    raise ValueError(
ValueError: Active state 'core:NameState' has not been defined: {"creationTime": 1613418602000, "lastUpdateTime": 1613418602000, "label": "OGP KNX Bridge", "deviceURL": "ogp://1222-1863-5724/00000BE8", "shortcut": false, "controllableName": "ogp:Bridge", "definition": {"commands": [{"commandName": "sendPrivate", "nparams": 1}], "states": [{"type": "DataState", "qualifiedName": "core:Private10State"}, {"type": "DataState", "qualifiedName": "core:Private1State"}, {"type": "DataState", "qualifiedName": "core:Private2State"}, {"type": "DataState", "qualifiedName": "core:Private3State"}, {"type": "DataState", "qualifiedName": "core:Private4State"}, {"type": "DataState", "qualifiedName": "core:Private5State"}, {"type": "DataState", "qualifiedName": "core:Private6State"}, {"type": "DataState", "qualifiedName": "core:Private7State"}, {"type": "DataState", "qualifiedName": "core:Private8State"}, {"type": "DataState", "qualifiedName": "core:Private9State"}], "dataProperties": [], "widgetName": "DynamicBridge", "uiClass": "ProtocolGateway", "qualifiedName": "ogp:Bridge", "type": "ACTUATOR"}, "states": [{"name": "core:NameState", "type": 3, "value": "OGP KNX Bridge"}], "attributes": [{"name": "ogp:Features", "type": 10, "value": [{"name": "private"}]}, {"name": "core:Technology", "type": 3, "value": "KNX"}, {"name": "core:Manufacturer", "type": 3, "value": "Overkiz"}, {"name": "core:ManufacturerReference", "type": 3, "value": "OGP KNX Bridge"}], "available": true, "enabled": true, "placeOID": "50f20de5-d593-4b87-915f-521c411c5860", "widget": "DynamicBridge", "type": 1, "oid": "72e3eb12-8369-42d3-9f48-5739a26d364f", "uiClass": "ProtocolGateway"}

### URL

https://www.home-assistant.io/integrations/tahoma/

### Version

2021.2.3

**Comment by frenck** [comment]
Hi there!

This is the issue/feedback tracker for the documentation/website. It seems like you have an issue with a Home Assistant Core integration. Please report those with the Core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
