### ISSUE TITLE
Levoit Speed Settings

### ISSUE THREAD

**Issue by awakefie** [home-assistant/home-assistant.github.io#16821]
### Feedback

I noticed that when I upgraded from the older custom integration to the current one that the speed "auto" is no longer available on the filter units.  Can we get that option back on units that support it?

### URL

https://www.home-assistant.io/integrations/vesync/

### Version

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
