### ISSUE TITLE
Installation Info ist missing for raspberry pi with running os

### ISSUE THREAD

**Issue by tmuehlha** [home-assistant/home-assistant.github.io#16824]
### Feedback

Installation Info ist missing for raspberry pi with running os

### URL

https://www.home-assistant.io/installation/

### Version

2021.2.3

**Comment by frenck** [comment]
Hi there @tmuehlha!

Thanks for your feedback, although, I'm not entirely sure what your feedback is. Could you clarify/extend your feedback a bit? And maybe add a suggestion to what you think should be added.

Thanks! 👍
