### ISSUE TITLE
Missing Levoit Air Filter

### ISSUE THREAD

**Issue by awakefie** [home-assistant/home-assistant.github.io#16820]
### Feedback

I recently added another LeVoit smart air filter the Core 200S and noticed it does not show up.  

https://www.amazon.com/LEVOIT-Purifier-Allergies-Core-200S/dp/B08FJ678YK/ref=sxin_9_ac_d_rm?ac_md=0-0-bGV2b2l0-ac_d_rm&cv_ct_cx=levoit&dchild=1&keywords=levoit&pd_rd_i=B08FJ678YK&pd_rd_r=84a1bcdc-414a-4ea0-a1da-8e2cc2ba9eb3&pd_rd_w=u3S0E&pd_rd_wg=P34a6&pf_rd_p=876e1cf2-5a60-4de1-a37e-e4e3a1c07041&pf_rd_r=MNYWFF6W9XVQYJH4W051&psc=1&qid=1614726211&sr=1-1-12d4272d-8adb-4121-8624-135149aa9081

No idea why it would be different than the other LeVoit smart units.  Let me know if we can update the integration to expose this new air filter.  Happy to test if needed.

### URL

https://www.home-assistant.io/integrations/vesync/

### Version

2021.2.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
