### ISSUE TITLE
Evohome Security

### ISSUE THREAD

**Issue by ArieHaan** [home-assistant/home-assistant.github.io#16825]
### Feedback

Hi. I'm using Evohome for heating and security. It would be great if Evohome Security would also be available for HA. It is accessible through https://international.mytotalconnectcomfort.com/Account/Login but after a second login from within here. There is also an app that gives direct access, https://tc20e.total-connect.eu/. This is just for the security part. Hopefully you are able to create this feature.
Grtz. Arjan

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2021.2.3

Hi. I'm using Evohome for heating and security. It would be great if Evohome Security would also be available for HA. It is accessible through https://international.mytotalconnectcomfort.com/Account/Login but after a second login from within here. There is also an app that gives direct access, https://tc20e.total-connect.eu/. This is just for the security part. Hopefully you are able to create this feature.
Grtz. Arjan

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
