### ISSUE TITLE
Why? 

### ISSUE THREAD

**Issue by ChipMIK1** [home-assistant/home-assistant.github.io#16833]
### Feedback

These are +5 year old leaks where passwords have changed many times since....SO stupid to have these warnings and not even an option to remove them permanent. Truly hope you remove this outdated notice again.

### URL

https://www.home-assistant.io/more-info/pwned-passwords/

### Version

2021.3.0

**Comment by antisane** [comment]
Most useless notification I have ever seen in HA. It doesn't say what password, only that a password is compromised. Also, why am I seeing one for Core-Samba? That is a local-only (the way I have it setup) service!

**Comment by frenck** [comment]
This is the documentation feedback, for feature suggestions and changes, please use the community forums. Thanks! 👍
