### ISSUE TITLE
Add Shutters as a device class

### ISSUE THREAD

**Issue by alnavasa** [home-assistant/home-assistant.github.io#16835]
### Feedback

Add window Shutters as a device class, with its custom mdi:window-shutter and mdi: window-shutter-open icons

### URL

https://www.home-assistant.io/integrations/binary_sensor/

### Version

2021.3.0

Add window Shutters as a device class, with its custom mdi:window-shutter and mdi: window-shutter-open icons
<img width="297" alt="Captura de pantalla 2021-03-04 a las 0 24 02" src="https://user-images.githubusercontent.com/458370/109886159-ee8f6d80-7c7f-11eb-80be-c4d18786a2ad.png">

**Comment by alnavasa** [comment]
Same with gate: 
<img width="269" alt="Captura de pantalla 2021-03-04 a las 0 27 32" src="https://user-images.githubusercontent.com/458370/109886533-7c6b5880-7c80-11eb-8ba3-8a745b19db70.png">

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
