### ISSUE TITLE
Slight problem with adding integration

### ISSUE THREAD

**Issue by england-sudo** [home-assistant/home-assistant.github.io#16839]
### Feedback

In order to get the integration to work, when creating the app on the honeywell site I needed to use this url: http://homeassistant.local/auth/external/callback instead of using the IP address of my HA instance.

### URL

https://www.home-assistant.io/integrations/lyric/

### Version

2021.3.0

**Comment by frenck** [comment]
Sure, the documentation states:

> This needs to be the URL of your Home Assistant instance

If your URL is something different than the example, that is fine.

**Comment by england-sudo** [comment]
You’re totally right! Sorry, I thought it would be like a comment on the thread that may help some other monkey like me who followed the directions almost verbatim.
