### ISSUE TITLE
How about a section on pruning logs?

### ISSUE THREAD

**Issue by scstraus** [home-assistant/home-assistant.github.io#16830]
### Feedback

I have 10GB of logs generated by hass sitting in my /var/log folder, as well as a bunch of stuff that's accrued in my docker folders. Would be good to have a button to purge these or a best practice on that.

### URL

https://www.home-assistant.io/more-info/free-space/

### Version

2021.2.3

**Comment by frenck** [comment]
There should be no need for that with the installation method this part of the documentation was created for.

**Comment by frenck** [comment]
With our default setup, log pruning should not be needed. Journald, by default, will adjust if the amount of diskspace becomes problematic.

**Comment by scstraus** [comment]
Is there a reason journald isn't used for supervised installs? It seems to just spam all the logs- docker logs, syslog, user log.. I mean, I already have a homeassistant log, why do they have to go to so many places?

**Comment by frenck** [comment]
> Is there a reason journald isn't used for supervised installs

On Supervised installations, this is out of scope for the project, as we don't control the operating system.

**Comment by scstraus** [comment]
But it's either supervisor or core that's directing the logs to all those places isn't it? What about a feature at least to be able to tell it which places it should output logs to? I'd turn them all off except the home assistant logfile.
