### ISSUE TITLE
Feature request; show last update timestamp on actual location updates from tile

### ISSUE THREAD

**Issue by Pantsema** [home-assistant/home-assistant.github.io#16842]
### Feedback

Currently Tile devices show a last update timestamp probably from the last time a call was made to the Tile platform to receive the location. I have some devices with depleted batteries and within the Tile app I can see on which date the actual last location update (tracking) was done.
Not sure on which API this integration was build, but looking at this development; https://github.com/bachya/pytile more details can be retrieved. 

### URL

https://www.home-assistant.io/integrations/tile/

### Version

2021.3.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
