### ISSUE TITLE
Gateway illuminance sensor readout ( value in lux) is wrong

### ISSUE THREAD

**Issue by raiko86** [home-assistant/home-assistant.github.io#16848]
### Feedback

real value of illuminance is in lumens (lm)

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2021.3.0

**Comment by frenck** [comment]
That is incorrect, according to the codebase it is in lux:

<https://github.com/home-assistant/core/blob/dev/homeassistant/components/xiaomi_miio/sensor.py#L304>

It the codebase incorrect?

**Comment by raiko86** [comment]
> That is incorrect, according to the codebase it is in lux:
> 
> https://github.com/home-assistant/core/blob/dev/homeassistant/components/xiaomi_miio/sensor.py#L304
> 
> It the codebase incorrect?
according to real value output from gateway it is in lumens

**Comment by frenck** [comment]
That was not what I asked :S

**Comment by raiko86** [comment]
> It the codebase incorrect?
I think it is not :/

**Comment by frenck** [comment]
In that case, it is a bug that needs to be reported here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
