### ISSUE TITLE
Node Red credential secret

### ISSUE THREAD

**Issue by hugodejong** [home-assistant/home-assistant.github.io#16849]
### Feedback

I use an unsafe password (per the notification I get from HA) for my Node Red credential secret. I would like to change it, but can't, the add-on docs say Node Red will be unable to decrypt my existing credentials. 

### URL

https://www.home-assistant.io/more-info/pwned-passwords

### Version

2021.3.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
