### ISSUE TITLE
Home Assistant Alert - Insecure secrets in *****

### ISSUE THREAD

**Issue by adrianoam** [home-assistant/home-assistant.github.io#16844]
### Feedback

OK, the explanation is very good, but how can I solve this problem em Home Assistant and protect my passwords?

### URL

https://www.home-assistant.io/more-info/pwned-passwords/

### Version

2021.3.0

**Comment by frenck** [comment]
> It is strongly advised to change these secrets with a more secure alternative as soon as possible.

Replace the weak passwords with stronger ones.
