### ISSUE TITLE
 Insecure secrets in ... option to disable or acknowledge that I am aware of the problem.

### ISSUE THREAD

**Issue by pmitev** [home-assistant/home-assistant.github.io#16846]
### Feedback

Excellent idea! 
Unfortunately, I am in a situation where my Synology has fixed NUT UPS client password and I can not change it even if I want. How can I disable this warning, perhaps only for the Synology user?

### URL

https://www.home-assistant.io/more-info/pwned-passwords/

### Version

2021.3.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
