### ISSUE TITLE
Bug with calling service "notify" or "telegram_bot" in automations, scripts. Data field not appear in user interface mode.

### ISSUE THREAD

**Issue by franlmc** [home-assistant/home-assistant.github.io#16856]
### Feedback

Bug with calling service "notify" or "telegram_bot" in automations, scripts. Data field not appear in user interface mode just YAML mode.  However in developer tools user interface works ok, showing: message, tittle and data options.

### URL

https://www.home-assistant.io/help/reporting_issues/

### Version

2021.3.1

**Comment by frenck** [comment]
Hi there!

Seems like you want to report a bug with the Home Assistant frontend, and not the documentation (which you have reported a bug at right now).

Please report bugs with the frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks! 👍

**Comment by franlmc** [comment]
Oh sorry, thanks a lot.
