### ISSUE TITLE
NVR HDD Error when only one disk is fitted

### ISSUE THREAD

**Issue by G8YTZ** [home-assistant/home-assistant.github.io#16857]
### Feedback

1 HDD vs 2 in NVR

### URL

https://www.home-assistant.io/integrations/hikvision/

### Version

2021.3.1

I recently replaced a pair of old 750GB disk drives with a single WD Purple 6TB HDD in my HikVision DS-7608NI-K2 / 8P NVR. The main reason for this was energy efficiency, the other slot has been left empty.
Since this time I've seen a constant HDD Error reported to HA. Is there any way of muting this indication so that the not present disk is not reported on?

**Comment by frenck** [comment]
That is either a support question or a bug report.

If you want to report a bug for the integration; please do so here:

<https://github.com/home-assistant/core/issues>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
