### ISSUE TITLE
Actions page should contain info or link to Choose, Repeat, etc.

### ISSUE THREAD

**Issue by teleksterling** [home-assistant/home-assistant.github.io#16850]
### Feedback

I'm looking for help on the choose action/syntax, and this the page that I'm linked to from the automation UI ("Learn more about actions"). This page should contain, or link to information about all the dropdown options in the UI: Choose, Repeat, Delay, wait, wait for trigger, condition, device, etc.

### URL

https://www.home-assistant.io/docs/automation/action/

### Version

2021.3.0

**Comment by frenck** [comment]
It does, in the second sentence already:

![image](https://user-images.githubusercontent.com/195327/110126148-68c90a80-7dc4-11eb-8437-76cb695a80f7.png)
