### ISSUE TITLE
Shouldn't EvoHome also be in the Heating category

### ISSUE THREAD

**Issue by Virbius** [home-assistant/home-assistant.github.io#16862]
### Feedback

On the Integrations page there ia a list of Categories down the left.  I was surprised that EvoHome (from Honeywell) wasn't in the Heating category!  It's already in Hub, Climate, and Water Heater categories.

Was tempted to add it via GitHub, but thought it worth raising this issue instead.

Are there any other entries which are under Climate category which should, logically, also be under the Heating category.

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2021.3.1

**Comment by frenck** [comment]
Actually, that category should not exist 😟 

Thanks for reporting that!
