### ISSUE TITLE
How to disable the "Pwned passwords"?

### ISSUE THREAD

**Issue by antisane** [home-assistant/home-assistant.github.io#16868]
### Feedback

How can I disable the "Pwned passwords"? 

### URL

https://www.home-assistant.io/more-info/pwned-passwords/

### Version

2021.3.1

**Comment by antisane** [comment]
And before you close this, THIS IS FEEDBACK. There is no documentation on that page saying how you can (or even if you can) disable this annoying "feature".

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

At this time, you can't disable this.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by antisane** [comment]
THIS IS FEEDBACK. There is no documentation on that page saying how you can (or even if you can) disable this annoying "feature".

**Comment by frenck** [comment]
> And before you close this, THIS IS FEEDBACK. There is no documentation on that page saying how you can (or even if you can) disable this annoying "feature".

That is correct, we don't document what Home Assistant can't do, we document what it can do.

**Comment by antisane** [comment]
Funny, there are MANY pages on the HA website telling you how to enable AND disable MANY things.

**Comment by frenck** [comment]
The page informs about how to resolve the warning message: By changing the password to a safer alternative.

If you want something else, please file a feature request.

**Comment by RaceAap** [comment]
Problem I have with this feature is that my home-assistant system is 'leaking' information to hibp without my authorization !
This kind of features need to be disabled by default and enabled if someone wants it.

**Comment by frenck** [comment]
> Problem I have with this feature is that my home-assistant system is 'leaking' information to hibp without my authorization !
> This kind of features need to be disabled by default and enabled if someone wants it.

That is incorrect, privacy is kept, no passwords are leaked. Please read the article provided in the documentation. Thanks 👍

**Comment by RaceAap** [comment]
> > Problem I have with this feature is that my home-assistant system is 'leaking' information to hibp without my authorization !
> > This kind of features need to be disabled by default and enabled if someone wants it.
> 
> That is incorrect. Please read the article provided in the documentation. Thanks +1

Hashed or not: it is doing a query to hibp without my authorization

**Comment by frenck** [comment]
> Hashed or not: it is doing a query to hibp without my authorization

This is getting annoying now. I've replied a couple of times where to go with feature requests. This is not the place to discuss or bring this up.

Thank you for understanding.

**Comment by antisane** [comment]
If you don't want FEEDBACK about this feature then don't link to here asking for feedback,

**Comment by frenck** [comment]
This is the documentation feedback. I've been polite to reply where to go with the concerns, support and feature requests.

I'm locking this issue for the above reason, as being off-topic.
