### ISSUE TITLE
add documentation of config option "interval_seconds"

### ISSUE THREAD

**Issue by NotSteveAtGithub** [home-assistant/home-assistant.github.io#16861]
### Feedback

While wrestling with warnings from nmap, I discovered a note in this issue (https://github.com/home-assistant/core/issues/6262) that described a config option that is not documented on the nmap_tracker page.  This config option solved my problem and would be a great addition to the page.

### URL

https://www.home-assistant.io/integrations/nmap_tracker/

### Version

2021.3.1

I was getting this error:

"2021-03-05 06:27:38 WARNING (MainThread) [homeassistant.components.device_tracker] Updating device list from legacy took longer than the scheduled scan interval 0:00:12"

This note from balloob at the above-mentioned URL gave me the information I needed to solve my problem:

"Use the config option interval_seconds to change from the default 12 seconds to something more appropriate for your network."

I would offer to

**Comment by frenck** [comment]
There is no such option as `interval_seconds` ?

https://github.com/home-assistant/core/blob/0350a6ed215fef56696053efa6a63acea468ff45/homeassistant/components/nmap_tracker/device_tracker.py#L29-L32

**Comment by NotSteveAtGithub** [comment]
Thanks for the quick response.  Curious - because I changed it from the default 12 to 20 and the warning message updated to 
"... scheduled scan interval 0:00:20".  Then I changed it to 60 seconds and the warning went away.

Could it be inherited from somewhere else?

**Comment by frenck** [comment]
There is a `scan_interval` option available on all platform-based integrations (but that is generic Home Assistant configuration and not specific to this integration).

Documented here: <https://www.home-assistant.io/docs/configuration/platform_options#scan-interval>

**Comment by NotSteveAtGithub** [comment]
Thanks!  Makes perfect sense; I had no idea!   Feel free to close this, and thanks for all you do for us.  :)

**Comment by frenck** [comment]
No problem!
