### ISSUE TITLE
WiFi Configuration missing from installation docs

### ISSUE THREAD

**Issue by ddubau** [home-assistant/home-assistant.github.io#16879]
### Feedback

I was going though the docs for the installation process on Raspberry PI and there seem to be no documentation on how to configure the device to connect to wifi via hassio. This is not my first time going through the process and I thought I had remembered this being there at some point.

https://www.home-assistant.io/installation/raspberrypi

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.3.1

**Comment by ddubau** [comment]
I was able to piece together the information from this page:

https://github.com/home-assistant/operating-system/blob/dev/Documentation/network.md
"Inside the \CONFIG\network\ directory on the USB drive or SD card, create a file called my-network" ...etc

However, I am not sure where this is on the public facing documentation page. 

I think this information should be more available on the install page

**Comment by frenck** [comment]
You can just change the network setting from the UI from the Supervisor:

[![Open your Home Assistant instance and show your Supervisor system information.](https://my.home-assistant.io/badges/supervisor_info.svg)](https://my.home-assistant.io/redirect/supervisor_info/)

![image](https://user-images.githubusercontent.com/195327/110241769-d6a33c80-7f52-11eb-89b4-094948e226d6.png)


It is not part of the installation manual, as we do not recommend using Wi-Fi for a smart home hub like Home Assistant. Additionally, the Wi-Fi feature are not available for all boards Home Assistant supports.
