### ISSUE TITLE
rest configuration missing scan_interval definition

### ISSUE THREAD

**Issue by fcassirer** [home-assistant/home-assistant.github.io#16871]
### Feedback

Maybe I missed something, but there is a `scan_interval` parameter in the example but it is not defined in the following configuration.  Also, would be useful to have an example that is not a json value using a `value_template`.  While it is easy enough to google around to find somebody who has figured out the non-json syntax might be useful to just call it out here.
Thanks!

### URL

https://www.home-assistant.io/integrations/rest/

### Version

2021.3.1

**Comment by frenck** [comment]
`scan_interval` is documented here: <https://www.home-assistant.io/docs/configuration/platform_options#scan-interval>

It is a generic Home Assistant platform option, and not integration specific.

More examples can be found in the subpages of the rest integration, for example:
<https://www.home-assistant.io/integrations/sensor.rest>

**Comment by fcassirer** [comment]
OK, thanks for the clarification, sorry for the noise.  FWIW, it is not obvious when you land on this page from outside of HA, maybe some boiler plate at the top of these that link to the platform_options would make it more obvious.

**Comment by frenck** [comment]
`scan_interval` is being removed/phased out. So that would be a wasted effort, to be honest.

**Comment by fcassirer** [comment]
Ok, thanks, appreciate the feedback.   Thanks for all the work you guys put into HA!
