### ISSUE TITLE
Supported File Types

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [home-assistant/home-assistant.github.io#16885]
### Feedback

Let readers know what file types are supported by the Local File camera e.g. jpg, png, gif

### URL

https://www.home-assistant.io/integrations/local_file/

### Version

2021.3.2

I can get jpg to work but not png. I don't know if it is supposed to work or not.

**Comment by frenck** [comment]
There is no logic here that limits the file type. We don't limit the file type, thus is it not specified.
