### ISSUE TITLE
Additional parameter 

### ISSUE THREAD

**Issue by simaoguimaraes** [home-assistant/home-assistant.github.io#16880]
### Feedback

Hi! Thanks for this card, I would like to suggest an optional parameter, to always show the current brightness.

### URL

https://www.home-assistant.io/lovelace/light/

### Version

2021.3.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
