### ISSUE TITLE
Link dead to Asus 

### ISSUE THREAD

**Issue by danlun** [home-assistant/home-assistant.github.io#16889]
### Feedback

Hi, the top link on the page pointing to Asus gets a 404 error.
Thanks
Dan

### URL

https://www.home-assistant.io/integrations/asuswrt/

### Version

2021.3.2

**Comment by Ndrinta** [comment]
![image](https://user-images.githubusercontent.com/4704172/110203824-22c58280-7e68-11eb-8604-456d3fa0e7f2.png)

**Comment by danlun** [comment]
Ni problems! :-) Perfect
