### ISSUE TITLE
Notification doesn't disappear.

### ISSUE THREAD

**Issue by danilKh** [home-assistant/home-assistant.github.io#16886]
### Feedback

Hi! Can you help please?
Notification doesn't disappear.
lifecycle: 1
liftime:5

### URL

https://www.home-assistant.io/integrations/lametric/

### Version

2021.2.3

**Comment by frenck** [comment]
Hi there @danilKh, thank you for reaching out. We use this GitHub Issue tracker for tracking issues/improvements for the documentation, not for providing support or handling integration problems.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

If you want to report an issue with the LaMetric integration, create an issue:

<https://github.com/home-assistant/core/issues>

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
