### ISSUE TITLE
pointless

### ISSUE THREAD

**Issue by BullionMan** [home-assistant/home-assistant.github.io#16892]
### Feedback

This new feature seems silly to me. First of all, I do not appreciate having the system looking at my secrets.yaml file. Secondly, there is no point in checking all of my secrets against the 'have I been pwned' database without using an email+password combination. Or does it grab my email address and then use all of the secrets as possible passwords? My MQTT username is mikey. That's not really a secret that I need to guard. Nothing in my secrets file is a repeat password ever. Am I missing something?

### URL

https://www.home-assistant.io/more-info/pwned-passwords/

### Version

2021.3.2

**Comment by SeanPM5** [comment]
Hi,

This repository is for feedback on the documentation only (things like missing or unclear information, spelling, grammar, readability improvements etc). 

For discussion and support on the actual features themselves you can use the community forums. Feel free to share your thoughts in the [release note thread](https://community.home-assistant.io/t/2021-3-my-oh-my/286346) over there.

Thanks
