### ISSUE TITLE
MQTT QoS Definition

### ISSUE THREAD

**Issue by Crinisen** [home-assistant/home-assistant.github.io#16895]
### Feedback

Given the on of the goals of the HomeAssistant project is to make Home Automation easy for a larger audience, variables like "qos" should provide additional context beyond simply specifying a default.  I like to tinker and dig so it was not a large burden to dig into what Quality of Service means in the MQTT context.  However I expect at least a link to external documentation like I found at https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/ or https://en.wikipedia.org/wiki/MQTT#Quality_of_service_(QoS) would be useful to some readers.

### URL

https://www.home-assistant.io/docs/mqtt/service/

### Version

2021.3.2

**Comment by Crinisen** [comment]
Actually, I suppose the "[retain](https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/)" attribute would not hurt to have further detail as well.

**Comment by frenck** [comment]
The issue is, is that we don't want to end up being the MQTT end-user documentation, we provide integration documentation. Therefore, IMHO, it does not belong in our documentation.

**Comment by Crinisen** [comment]
That was why I was leaning towards links, but your response also seems reasonable enough.
