### ISSUE TITLE
Error message with Cookbook recipe: Dim (and brighten) lights via a remote

### ISSUE THREAD

**Issue by dubtec** [home-assistant/home-assistant.github.io#16897]
### Feedback

Copy-pasting the script portion of the recipe, i.e. ramp_light yields an error. More specifically the parser complains about: 
Message malformed: not a valid value for dictionary value @ data['sequence'][0]['repeat']['sequence'][0]['target']['entity_id']

### URL

https://www.home-assistant.io/cookbook/dim_and_brighten_lights/

### Version

2021.3.1

**Comment by frenck** [comment]
Which version of Home Assistant are you running? As that example would require at least Home Assistant Core 2021.3.0

**Comment by dubtec** [comment]
Thanks, frenck, I am actually on 2021.2.3. 

Managed to save the script when moving the entity_id to to data. 

Will update to a more current version and check once more.

**Comment by dubtec** [comment]
Alright, updated and checked. Now on 2021.3.2 the original script (with entity_id being part of the target) runs equally fine as previously, when the entity_id was child of data.

Many thanks for the swift response!
