### ISSUE TITLE
Not clear that feinstaub temp/huminity are difrent id voor same location 

### ISSUE THREAD

**Issue by hessel-a** [home-assistant/home-assistant.github.io#16891]
### Feedback

Het is niet duidelijk dat uit site te halen dat je 2x Integrations lufdaten moet toevoegen. 1x voor Feinstaub en 1x voor temp/humunity En dat sensor id verschillend is voor gps locatie. Nu 2 dagen lopen zoeken voor ik ergens las dat het 2 verschillende id is.

### URL

https://www.home-assistant.io/integrations/luftdaten/

### Version

2021.3.2

**Comment by fabaff** [comment]
Sorry, please update and re-open this issue when the content is available in English. I can only guess what the Dutch? content is. Thanks.
