### ISSUE TITLE
tns1:Device/Trigger/DigitalInput

### ISSUE THREAD

**Issue by jhallenb** [home-assistant/home-assistant.github.io#16898]
### Feedback

Hi would it be possible to add a binary sensor for Onvif event tns1:Device/Trigger/DigitalInput
My onvif camera (Imou New Bullet) has a built in PIR sensor in addition to Video based motion detection.
I can see in OnvifDevice Manager that the PIR sensor triggers the tns1:Device/Trigger/DigitalInput event. It would be great if the Onvif integration could support it.

### URL

https://www.home-assistant.io/integrations/onvif/

### Version

2021.3.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
