### ISSUE TITLE
Documentation appears to be missing some setup information

### ISSUE THREAD

**Issue by skipishere** [home-assistant/home-assistant.github.io#16905]
### Feedback

Having performed the steps I do not appear to have a way to use the Microsoft TTS (I already have the google_translate setup, if these can't be used in conjunction at the same time then this might need to be explained?)

Also might be handy to have an example usage on the page as well.

### URL

https://www.home-assistant.io/integrations/microsoft/

### Version

2021.3.2

**Comment by skipishere** [comment]
After rebooting 4 times (and refreshing the browser each time) it finally picked up the changes, but adding in an example of usage would still be beneficial

**Comment by frenck** [comment]
Feel free to add such an example, however, we would prefer linking to external documentation if possible.
