### ISSUE TITLE
Command not found: docker

### ISSUE THREAD

**Issue by AJediIAm** [home-assistant/home-assistant.github.io#16906]
### Feedback

When following the command: "docker exec -it CONTAINER_NAME_OR_ID python -c 'import roombapy.entry_points; roombapy.entry_points.password()' <MYIP>" 
Using a HA terminal
I get the error: "docker: command not found"

I used to terminal addon and VScode terminal, both with the same results. 
I run the Intel NUC image with the latest core and os. 

### URL

https://www.home-assistant.io/integrations/roomba/

### Version

2021.3.2

**Comment by frenck** [comment]
The documentation states:

![image](https://user-images.githubusercontent.com/195327/110314530-41fb1600-8008-11eb-83bf-990e45385bcb.png)


However, in this feedback, you are talking about add-ons. Add-ons indicate you are not running Home Assistant Container, but Home Assistant OS or Supervised. Thus, that does not apply to your installation method.

**Comment by AJediIAm** [comment]
Hi Frenck, 

Somehow I thought Home Assistant OS also used containers internally, but this was a wrong assumption on my part. Don't know where I got the idea, but it would explain everything. 

Thanks!

**Comment by frenck** [comment]
They share similar assets, yes, but the way those are used are completely different 😉
