### ISSUE TITLE
Hi, I would like to know when does the plugin update it's information

### ISSUE THREAD

**Issue by digdas1** [home-assistant/home-assistant.github.io#16900]
### Feedback

Hi, I would like to know when does the plugin update it's information, and/or how to enforce it?

I did do a server restart, which did update it.

### URL

https://www.home-assistant.io/integrations/cert_expiry/

### Version

2021.3.2

**Comment by frenck** [comment]
Every 12 hours the sensor will fetch and update information for the configured host.
