### ISSUE TITLE
Please add new features from merged PR #44711

### ISSUE THREAD

**Issue by nick2525** [home-assistant/home-assistant.github.io#16917]
### Feedback

In merged PR description "I added the following new services, adding supported_features logic for the two marked with an x:
repeat_set x
select_sound_mode x
toggle
" but I can't see it in docs. Also, check code here https://github.com/home-assistant/core/pull/44711/files for new features, to add at docs

### URL

https://www.home-assistant.io/integrations/universal/

### Version

2021.3.2

**Comment by frenck** [comment]
That has been documented and applies in this change:
<https://github.com/home-assistant/home-assistant.io/pull/16056/files>

It states that all features from the media player are now available. I'm not sure what could be missing now?

**Comment by nick2525** [comment]
Ok, I did't see (refer to the media_player documentation to see the full list)
