### ISSUE TITLE
Daily Disconnect

### ISSUE THREAD

**Issue by ChoamNomsky** [home-assistant/home-assistant.github.io#16918]
### Feedback

Every 24 hours, the robot becomes unavailable to HA. A reboot of HA buys you another 24 hours of robot connection. 

### URL

https://www.home-assistant.io/integrations/sharkiq/

### Version

2021.3.2

**Comment by frenck** [comment]
Hi there @ChoamNomsky!

Thanks for opening an issue, however, this is the issue/feedback tracker for the documentation. It seems like you want to report a bug/issue with an Home Assistant Core integration.

There is nothing I can change to the documentation that makes your issue go away.

Please report these type of issues here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
