### ISSUE TITLE
Not working for LG WebOS

### ISSUE THREAD

**Issue by hjkss** [home-assistant/home-assistant.github.io#16922]
### Feedback

This is my automation config:
 alias: Netflix Time
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.bed_room_tv_2
    from: '"Live_TV"'
    to: '"netflix"'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - scene: scene.bedroom_netflix
  mode: single

It doesn't work for me

### URL

https://www.home-assistant.io/cookbook/dim_lights_when_playing_media/

### Version

2021.3.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub issue tracker for the documentation to track improvement and suggestions for the documentation, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
