### ISSUE TITLE
DSMR integration with MQTT smart meter device

### ISSUE THREAD

**Issue by yann1420** [home-assistant/home-assistant.github.io#16924]
### Feedback

I have a situation where my HA instance is at home but the DSMR smart meter is in a different building using a different network. The smart meter is connected to P1 Smart Meter using this Tasmota solution https://tasmota.github.io/docs/P1-Smart-Meter/ . and it is able to connect to an MQTT service in the network that also holds the HA instance.
I am looking for an example/solution where I can connect the DSMR integration via MQTT to the tasmota edge device.

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2021.3.2

I use this HA version  core-2021.3.2 / supervisor-2021.03.4
The ESP8266 runs Program Version | 8.3.1

**Comment by frenck** [comment]
Hi there @yann1420!

> I am looking for an example/solution where I can connect the DSMR integration via MQTT to the tasmota edge device.

This is out of scope for the documentation and is more of a support question.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
