### ISSUE TITLE
Device and entity names

### ISSUE THREAD

**Issue by bduineveld** [home-assistant/home-assistant.github.io#16927]
### Feedback

It's unclear how to find the "Device" from trigger>event_data>device in order to listen to shelly.click. There's a big chapter about entity naming so that is confusing when trying to find how to address a device. 
I would suggest adding some information under "Events" about listening to events ("Developer tools">"Events">"Listen to events">"*" or "shelly.click")
Secondly, in entity naming it says "Names are set from the device web page". I was looking within Home Assistant for these settings (there's a device page, you can change the name, only not the channel). I suggest to change it to "Names are set from the >native< device web page"

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.3.3

I got stuck at this point myself in integrating Shelly actions (shelly.click). Took me an entire afternoon to figure this out, so I think is nice to add the information. Thanks!

**Comment by frenck** [comment]
> It's unclear how to find the "Device" from trigger>event_data>device in order to listen to shelly.click. There's a big chapter about entity naming so that is confusing when trying to find how to address a device.
> I would suggest adding some information under "Events" about listening to events ("Developer tools">"Events">"Listen to events">"*" or "shelly.click")

If you have never worked with events before, I agree, it might be confusing as described on that page. Makes me wonder, why haven't you used device automations instead?

> Secondly, in entity naming it says "Names are set from the device web page". I was looking within Home Assistant for these settings (there's a device page, you can change the name, only not the channel). I suggest to change it to "Names are set from the >native< device web page"

You can change the name from Home Assistant 🤷  All entities and devices can be renamed.

**Comment by bduineveld** [comment]
Beste Franck,
Thanks for your reply.
>>It's unclear how to find the "Device"...

> If you have never worked with events before, I agree, it might be confusing as described on that page. Makes me wonder, why haven't you used device automations instead?

Device automations do not work if you use Shelly in detached mode, and that was my case. A link to working with events would also help.

>>Secondly, in entity naming it says "Names are set from the device web page"...

> You can change the name from Home Assistant 🤷 All entities and devices can be renamed.

The "device name" from "native" Shelly is different from the name in HASS (see images down, they are the same device). Also, the explaination continues talking about a channel which you cannot alter in HASS itself. That is why I think it is important to add the word "native" so it will be clear which device web page we are talking about

![firefox_Knq1VlS16L](https://user-images.githubusercontent.com/47941071/110475298-01230000-80e1-11eb-8dae-755b709a38ff.png) ![firefox_QfXckDfRtA](https://user-images.githubusercontent.com/47941071/110475287-fe280f80-80e0-11eb-895a-5fe1ddf1e23b.png)

**Comment by frenck** [comment]
> Device automations do not work if you use Shelly in detached mode, and that was my case. A link to working with events would also help.

Uh? Device automations ARE predefined events. So if events work, device automations should work as well.

**Comment by bduineveld** [comment]
> > > Makes me wonder, why haven't you used device automations instead?
> 
> > Device automations do not work if you use Shelly in detached mode...
> 
> Uh? Device automations ARE predefined events. So if events work, device automations should work as well.
>
I understood you meant the picture below by automations. These automations don't work in detached mode, since the state of the light (device on/off) doesn't match the state of the switch (event shelly.switch). "Input is powered" did work but the delay was too big and was not sensitive enough. But it probably would have worked with shelly not in detached mode.
![firefox_SrPOhNIGv31](https://user-images.githubusercontent.com/47941071/110478180-60364400-80e4-11eb-8556-0a58001e914e.png)

**Comment by thecode** [comment]
@bduineveld device automations should work in detached mode, automation are created for input events and not only for switch.
However if you recently changed the button type you need to restart Home Assistant to detect the change. I will add this to the docs. Example for Shelly 2.5 with buttons in detached mode:

![image](https://user-images.githubusercontent.com/1858925/110480383-1bfc7100-80ef-11eb-8612-abe8da3c8bd4.png)
See the automations circled in red, they also automatically match the available events from the device. For example if you run it 
on Shelly I3 it will create additional options:

![image](https://user-images.githubusercontent.com/1858925/110480650-654cc080-80ef-11eb-9f0d-fd38d77522c6.png)

**Comment by bduineveld** [comment]
@thecode thanks for your reply. For me rebooting was not the issue. I realize that the shelly 2.5 and i3 have much more options than the shelly dimmer 1. (I know it's not logical to use the dimmer as detached but it was already installed)

**Comment by thecode** [comment]
Just note that the same events you see in the `shelly.click` events should be available via automations. if it is not the case please report it and we will fix it.

**Comment by bduineveld** [comment]
> 
> 
> Just note that the same events you see in the `shelly.click` events should be available via automations. if it is not the case please report it and we will fix it.

The strange thing is that I don't see any `shelly.click` events in automations. (not for my shelly 1/shelly 2.5 roller shutter/dimmer1/dimmer2)

**Comment by thecode** [comment]
In this case I think the proper way is to open an issue here:
https://github.com/home-assistant/core/issues/new/choose
This place is for documentation issues.
Before creating an issue please add the following to `configuration.yaml`, restart HA and post the log in the issue. 

```yaml
logger:
  default: info
  logs:
    homeassistant.components.shelly: debug
    aioshelly: debug 
```

It will save time solving the issue.
Thanks.

**Comment by bduineveld** [comment]
> In this case I think the proper way is to open an issue here:
> https://github.com/home-assistant/core/issues/new/choose
>
@thecode thanks, I posted it here: https://github.com/home-assistant/frontend/issues/8604
