### ISSUE TITLE
Authentication fails when http>base_url not set in configuration.yaml

### ISSUE THREAD

**Issue by bduineveld** [home-assistant/home-assistant.github.io#16928]
### Feedback

It would help to add the following information
If authentication fails, it might work to add the following code to configuration.yaml:

http:
  base_url: INTERNAL_HOME_ASSISTANT_URL

for example

http:
  base_url: http://192.168.x.x:8123

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2021.3.3

**Comment by frenck** [comment]
> If authentication fails, it might work to add the following code to configuration.yaml:

Your suggestion is incorrect, as the base_url has been deprecated and removed from the current stable Home Assistant version.

**Comment by bduineveld** [comment]
> 
> 
> > If authentication fails, it might work to add the following code to configuration.yaml:
> 
> Your suggestion is incorrect, as the base_url has been deprecated and removed from the current stable Home Assistant version.

I had a standard clean installation of HASS on a raspberry pi, I followed all the steps and authentication failed. That's why I think a lot of people will run into the same problem. While I was looking for an answer why it failed, I came across this and it worked for me. Before doing this, I tried to fill configuration>general>internal url instead, this didn't work. I didn't try to fill an external url, since my HASS device not accessible externally. Can you think of another solution? Or is this getting off topic

**Comment by frenck** [comment]
Well, Home Connect uses a default OAuth2 handling, so it just uses the URL from your browser. External/Internal URL is not involved in this.

**Comment by bduineveld** [comment]
I tried to reproduce the same problem with Spotify integration.
I found out that when browsing from http://homeassistant.local:8123 I got an error "INVALID_CLIENT: Invalid redirect URI". I got the same type of error with home connect. When I browsed from http://192.168.x.x:8123/ I didn't get the warning.
So maybe a warning: please follow these steps from the IP based rather than the .local based URI, of cource if you can also reproduce this error and solotion

**Comment by frenck** [comment]
> So maybe a warning: please follow these steps from the IP based rather than the .local based URI, of cource if you can also reproduce this error and solution

For the OAuth2 specification, that makes no difference. The Spotify integration I actually am a codeowner for and actually regularly connect with my local development host to it.

**Comment by frenck** [comment]
> "INVALID_CLIENT: Invalid redirect URI"

That is a response from the external party you are connecting with, meaning you have incorrectly configured the application on the other end.

**Comment by bduineveld** [comment]
> 
> 
> > "INVALID_CLIENT: Invalid redirect URI"
> 
> That is a response from the external party you are connecting with, meaning you have incorrectly configured the application on the other end.

You are right, this is not an accurate reproduction of the error I had that time. When I come across the same problem again I'll let you know. Thanks for thinking with me
