### ISSUE TITLE
Explain examples better

### ISSUE THREAD

**Issue by buteomont** [home-assistant/home-assistant.github.io#16921]
### Feedback

It would be nice to have a description, in English, of exactly what the examples do.  Instead of "Specify filter for a single entity", it would be better to have something like "Show a badge when a humidity sensor reports more than 50% humidity".

### URL

https://www.home-assistant.io/lovelace/badges/

### Version

2021.3.2

**Comment by frenck** [comment]
It is not trying to describe the content of the example, it is describing the use of a filter on a single entity. 🤷 

Your suggestion would not cover that.
