### ISSUE TITLE
iroomba docs doesn't mention that auto discovery seems to be in place?

### ISSUE THREAD

**Issue by scyto** [home-assistant/home-assistant.github.io#16931]
### Feedback

Today my HA discovered one of my roombas (an i7) and suggested I install the integration.
I did and all it required was me to press the home button on the roomba.  Most impressive.

However, it hasn't detected my 980 so i am unclear how to contribute to docs as i am not sure if the integrations new way of working is supposed to work for all models or not.

I assume this is new in current version?
How does autodiscover happen?
Should it be discovering my 980?

Happy to contribute to doc revisions once i know more! 

### URL

https://www.home-assistant.io/integrations/roomba/

### Version

2021.3.3

**Comment by frenck** [comment]
So, the Roomba's are discovered by DHCP requests they do on the network.

This means, that they are not instantly discovered (but only when they actually request a new IP address on your network).

See:

https://github.com/home-assistant/core/blob/ed679b263b89a76f6f567a4efc1fc06e9b72a68c/homeassistant/components/roomba/manifest.json#L8

```json
  "dhcp": [{"hostname":"irobot-*","macaddress":"501479*"}]
```

It will only discover the device if the hostname starts with `irobot-` and the mac address of the device starts with `50:14:79`.

What you could do, is verify in your router (or any other method to your liking) if the other Roomba matches that or not. If not, we could extend the discovery :)

**Comment by scyto** [comment]
Thanks for the detail.
Some observations:
- my lease time is 4 hours
- the i7 had been unplugged for a few weeks so it would have done a full DHCP offer flow
- the 980 has been plugged in for weeks so is just doing renew before the 4 hour lease expiration time
- the 980 name is Roomba-[somehex].mydomain.com

so i assume the issue is the name :-)  AFAIK roomba decided the name on the 980, i don't ever recall changing anything
 
--edit-- 
i realized from the fragment in your post you might need mac?
mac = 80a589*

**Comment by scyto** [comment]
i looked for other examples but couldn't find one, i am not a coder, was guessing this might work as a change?

 `"dhcp": [{"hostname":"irobot-*","macaddress":"501479*"}, {"hostname":"Roomba-*","macaddress":"80a589*"}]`
or maybe specify line twice?

```
  "dhcp": [{"hostname":"irobot-*","macaddress":"501479*"}]
  "dhcp": [{"hostname":"Roomba-*","macaddress":"80a589*"}]
```
just trying to learn :-)

--edit--
ok i think i taught myself to fish, i found https://developers.home-assistant.io/docs/creating_integration_manifest/#dhcp i can do PR  :-)

**Comment by scyto** [comment]
sorry to be dumbass, can't find where to edit the file locally on my hyper-v image to test

**Comment by scyto** [comment]
ok worked out how to test, now to wait 4 hours :-)  
![image](https://user-images.githubusercontent.com/11369180/110549554-14d16500-80e7-11eb-9df7-f31284ed37a0.png)
