### ISSUE TITLE
SamsungCTL

### ISSUE THREAD

**Issue by dnorthrupva** [home-assistant/home-assistant.github.io#1693]
Hey all,

SamsungCTL was updated to .6 - Can we have the dependency upgraded? I'm working on integration it myself, currently, but I have 3 devices that sometimes get discovered, sometimes don't, and none of them work.

https://github.com/Ape/samsungctl

**Comment by fabaff** [comment]
This is already an open PR (https://github.com/home-assistant/home-assistant/pull/5126) for this.
