### ISSUE TITLE
Troubles while connecting to Doorbird E/A Controller

### ISSUE THREAD

**Issue by specialequipment** [home-assistant/home-assistant.github.io#16938]
### Feedback

The Doorbird E/A Controller is discovered automatically, pretty nice. Connections to the device are not working. Maybe, because Doorbird is blocking all traffic except the connected Doorbird door station.

Please extend the documentation, how to connect this kind of device.

### URL

https://www.home-assistant.io/integrations/doorbird/

### Version

2021.3.3

**Comment by frenck** [comment]
@bdraco Could you provide clarity on this? I'm happy to adjust the docs, but missing the technical knowledge on this one.

**Comment by specialequipment** [comment]
The Doorbird E/A Controller has to be connected to a Doorbird DoorStation. All automation has to be done via the doorstation. Direct access to the E/A Controller is not working.
I have been a bit confused about this, because HomeAssistant autodiscoverd two devices (The door Station and the ea controller)

After some investigations, I recognized that the doorstation provided some additional Entities, after connecting the E/A Controller to the doorstation using the DoorBird App.

At least a hint would be helpful, that the controller automations have to be done using the doorstation but not the E/A Controller itself.

**Comment by bdraco** [comment]
There isn't a published api for doorbird accessories, they have to talk to the doorstation itself. Unfortunately they present the same discovery signature as a doorstation so the only solution right now is to ignore them.

**Comment by bdraco** [comment]
We could probably query the live image url and if it returns a 404 abort discovery

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/48710

**Comment by frenck** [comment]
The above PR is merged, addressing this feedback. Thanks @specialequipment 👍
