### ISSUE TITLE
OS installation

### ISSUE THREAD

**Issue by darnoldser** [home-assistant/home-assistant.github.io#16930]
### Feedback

I followed the OS installation, but it asks me a login.

### URL

https://www.home-assistant.io/installation/nuc/

### Version

2021.3.3

**Comment by frenck** [comment]
Hmm interesting, there is part of the documentation missing there!

You don't need to login, that is the whole point :)

Something like this needs to be added (and maybe helps you right now): 

> Once completed you will be able to reach Home Assistant on `http://homeassistant.local:8123`. If you are running an older Windows version or have a stricter network configuration, you might need to access Home Assistant at `http://homeassistant:8123` or `http://X.X.X.X:8123` (replace X.X.X.X with your ’s IP address).

**Comment by ikifar2012** [comment]
> Hmm interesting, there is part of the documentation missing there!
> 
> You don't need to login, that is the whole point :)
> 
> Something like this needs to be added (and maybe helps you right now):
> 
> > Once completed you will be able to reach Home Assistant on `http://homeassistant.local:8123`. If you are running an older Windows version or have a stricter network configuration, you might need to access Home Assistant at `http://homeassistant:8123` or `http://X.X.X.X:8123` (replace X.X.X.X with your ’s IP address).

I have added that line to the documentation to match the other pages

**Comment by ikifar2012** [comment]
> ### Feedback
> I followed the OS installation, but it asks me a login.
> 
> ### URL
> https://www.home-assistant.io/installation/nuc/
> 
> ### Version
> 2021.3.3

Did you complete the onboarding from the web interface?

**Comment by darnoldser** [comment]
yes, thanks! that is the solution. I tried to access on the directly
connected screen.

Franck Nijhof <notifications@github.com> schrieb am Di., 9. März 2021,
20:04:
