### ISSUE TITLE
feedback mqtt integration

### ISSUE THREAD

**Issue by FrankIJskes** [home-assistant/home-assistant.github.io#16941]
### Feedback

I cannot find anything about how home assistant will automatically add devices that are discovered through the mqtt interface. If i debug data coming in, via listening on topic "#" i see the mqtt integration is working. But i cannot find the next step to do. 
It would be a great help if this final step is docuemented here (or a link to the docs)

### URL

https://www.home-assistant.io/docs/mqtt/testing/

### Version

2021.3.3

**Comment by filmkorn** [comment]
@FrankIJskes I think you are looking for https://www.home-assistant.io/docs/mqtt/discovery/ . 

Basically, you publish to a topic with the default prefix `homeassistant` and the MQTT integration will pick it up and create an entity for it. For example on a tasmota device you enable publishing to that prefix by running `SetOption19 1` in the console and the mqtt integration will pick up the topic and create an entity for it. 

Alternatively you can create sensors and switches that listen or publish to other topics without the discovery prefix from the `configuration.yaml`: https://www.home-assistant.io/integrations/sensor.mqtt/

I agree though, the MQTT page could link to more information to help getting started.

**Comment by FrankIJskes** [comment]
Thank you for your feedback.

The line:
Alternatively you can create sensors and switches that listen or publish 
to other topics without the discovery prefix from the 
|configuration.yaml|: 
https://www.home-assistant.io/integrations/sensor.mqtt/ 
<https://www.home-assistant.io/integrations/sensor.mqtt/>
would have helped me. Perhaps it would be nice to have this line 
somewhere in the first paragraph?


The auto-discovery section mentions:

|<component>|: One of the supported MQTT components, eg. |binary_sensor|.

But what are the supported MQTT components? I now realize this is stated 
under "Supported by MQTT discovery", but things would have been better 
understandable (at least for me) if that line stated "MQTT components 
supported by MQTT discovery".


Thank you for your time. I did not get discovery to work, but the manual 
part did it for me. So for now it is ok.
