### ISSUE TITLE
Dock not accurately showing

### ISSUE THREAD

**Issue by nutsofamily** [home-assistant/home-assistant.github.io#16945]
### Feedback

When shark is docked it does not update

### URL

https://www.home-assistant.io/integrations/sharkiq/

### Version

2021.3.3

**Comment by frenck** [comment]
It seems like you want to report a bug with the Shark IQ, however, you have submitted documentation feedback? There is no amount of documentation I can adjust to fix a bug in the codebase.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
