### ISSUE TITLE
Missing group information

### ISSUE THREAD

**Issue by Davst** [home-assistant/home-assistant.github.io#16943]
### Feedback

Good work on the documentation, though as I came across a weird behavior (deconz groups report brightness, but it doesn't correspond to the brightness of the lamps in the group) I was trying to understand what the value was based on and unfortunately there is no group section in the docs.

### URL

https://www.home-assistant.io/integrations/deconz/

### Version

2021.3.3

**Comment by Kane610** [comment]
Hi!

It should correspond to the brightness of one of the lights in the group.

See https://github.com/Kane610/deconz/blob/c89a33b0f72216567209a8cab1e0ebd65111d1d6/pydeconz/gateway.py#L178 and https://github.com/Kane610/deconz/blob/c89a33b0f72216567209a8cab1e0ebd65111d1d6/pydeconz/group.py#L185

You need to share more data if you want me to understand what you're really asking. :)
