### ISSUE TITLE
It’s totally disappointing....

### ISSUE THREAD

**Issue by wowulavega** [home-assistant/home-assistant.github.io#16944]
### Feedback

I am really disappointed with the whole HA system and its documentation.
Nothing works and the documentation differs significantly from the running software. In addition, documentation is incomprehensibly written and referenced for software parts that are not present in the software, or cannot be found.
After almost a month, I have now given up on any extensions in HA and let the system run in rudimentary form.
It is really disappointing that the system is so poorly managed.

### URL

https://www.home-assistant.io/lovelace/

### Version

2021.3.3

**Comment by frenck** [comment]
Sorry to hear that. But this is more of a general opinion that I cannot process on the reported page.
