### ISSUE TITLE
This update is unacceptable. Requiring full admin to a storage appliance is a VERY BAD IDEA.

### ISSUE THREAD

**Issue by sondercoder** [home-assistant/home-assistant.github.io#16951]
### Feedback

I was using the Camera/Surveillance Station module to have a dashboard with outdoor cameras.  There is ZERO possibility I am storing 'Admin' credentials for an entire system just for that.  At least with the previous implementation, I could limit the account that had access to the cameras, and to which cameras, now that control is gone.  I guess I will be stuck on core-2021.2.3 - until I find a new product.  Full admin on storage appliance to view some cameras is a joke. Please separate the modules as there is ZERO to gain by having them FORCED to be combined.  It's like having access to the vault in the bank to use the bathroom.  Does anyone here think security first?  I guess its my fault for not crawling the releases, and saying something sooner.  I think its a matter of time until HA is the 'weak-link' to cause to many cryptolocker/data loss because of this. Please re-separate the modules, there is NOTHING to gain by having a 'ALL IN ONE' solution.

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2021.3.3

**Comment by frenck** [comment]
This is not documentation feedback. Please use the forums for these kinds of things. Thanks! 👍
