### ISSUE TITLE
Adding the ability to schedule restarts of the DoorBird

### ISSUE THREAD

**Issue by smeee-again** [home-assistant/home-assistant.github.io#16950]
### Feedback

So the DoorBird performs a soft restart automatically about every 24 hours.  In my current home automation system, the plugin for DoorBird allows the restart to be scheduled.  So in my case, at midnight I have the DoorBird's do their daily restart.  This prevents the DoorBird from performing a restart in the middle of the day.  The restart available is the same as the automatic one that happens.

The API guide for DoorBird:

RESTART
Restarts the device. There will be no diagnostic sound (e.g. “successfully connected
to internet”) after this restart.
Method: GET
Required permission: valid user, API operator permission
Syntax:
http://<device-ip>/bha-api/restart.cgi
Example Request:
http://<deviceip>/bha-api/restart.cgi
Return:
HTTP/1.0 200 OK\r\n
\r\n
HTTP status codes:
200 – OK
401 – Authentication required
503 – device is busy (e.g. currently installing an firmware update)

### URL

https://www.home-assistant.io/integrations/doorbird/

### Version

2021.3.3

https://www.doorbird.com/downloads/api_lan.pdf?rev=0.29

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
