### ISSUE TITLE
No power on button

### ISSUE THREAD

**Issue by jello1974** [home-assistant/home-assistant.github.io#16958]
### Feedback

My TV supports turn on action but the media player card does not show the ON button.
I can only shut the tv off and if I want to turn it back on I have to use a separate button.

My config:

  - platform: panasonic_viera
    host: local IP address
    name: "TV Panasonic"
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "TV MAC"

### URL

https://www.home-assistant.io/integrations/panasonic_viera/

### Version

2021.3.3

![media_tab](https://user-images.githubusercontent.com/45515078/110842398-b5728100-82af-11eb-8b60-398feda8377e.png)

**Comment by frenck** [comment]
Hi there @jello1974!

This is the feedback/issue tracker for our documentation, however, it seems like you want to report an issue with integration. Please report the integration issue with the core (as there is nothing I can change in the docs to fix your issue).

<https://github.com/home-assistant/core/issues>

Thanks! 👍
