### ISSUE TITLE
Add help content for users running HA in Virtualbox

### ISSUE THREAD

**Issue by paul-jewell** [home-assistant/home-assistant.github.io#16967]
### Feedback

The information for recovering files is clear for Raspberry Pi, but if you (like me!) are running HA in a virtualbox machine, I can't access the files remotely from the host system (I didn't set up Samba yet). Why do I have an issue? It seems the username and password I set up don't work (I did record them at the time with cut/paste). I am told the user isn't registered, and there isn't any way to list users, so I can find my way back in. I don't really want to start from scratch...!

### URL

https://www.home-assistant.io/docs/locked_out/

### Version

2021.3.3

**Comment by frenck** [comment]
<https://www.home-assistant.io/docs/locked_out/#connect-directly>

☝️ That method should work, regardless of how you installed it. Instead of attaching a keyboard and screen, you would open up the remote display/console in your virtual box of the virtual machine you have created.

**Comment by paul-jewell** [comment]
Hi Frenck! In the end, I realised my phone was still connected, so I went in and changed the password there, allowing me to re-connect on the PC. What I didn't realise:
- You can drop out of ha-cli into a normal shell, allowing the file system to be inspected. This did allow me to confirm that the username I was using was correct. I don't know why I was getting a message saying the user name wasn't registered. I hadn't found a way to do this inside ha-cli (as expected).
I also managed to mount the system in the host using qemu, and this also allowed me to inspect the file system contents.
So on reflection, and considering your comment perhaps no need to change anything!
