### ISSUE TITLE
please make clear which wind_speed unit is required

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/home-assistant.github.io#16970]
### Feedback

since not all weather integrations/sensors available  use the same metrics, at least m/s or km/h should be indicated to use as default for the Lovelace frontend representation in the forecast card

### URL

https://www.home-assistant.io/integrations/weather.template/

### Version

2021.3.3

**Comment by frenck** [comment]
As per <https://developers.home-assistant.io/docs/core/entity/weather#properties>

km/h or mi/h

Agreed, that should be clear in the property description in the template documentation.

**Comment by Mariusthvdb** [comment]
the more so, because several of these weather integrations still use m/s (meters, not miles)
Dark_sky, Openweathermap, Weatherbit (sorry not core)
so, where to start with this?

**Comment by frenck** [comment]
Those are other integrations. If you think those are incorrect, please open a separate issue on the core project. This is documentation feedback.

**Comment by Mariusthvdb** [comment]
Forgot about this, will have a look soon, or close
