### ISSUE TITLE
not enough info for shelly integration

### ISSUE THREAD

**Issue by cwestdoerp** [home-assistant/home-assistant.github.io#16978]
### Feedback

Hello, you are writing:
-----------
the bottom right, click on the Add Integration button.
From the list, search and select “Shelly”.
Follow the instruction on screen to complete the set up.
------------
Ok, the shelly integration is asking "Host:" 
Which host ? FOr a neewbie to less information.

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.3.4

**Comment by frenck** [comment]
The hostname or IP address of your Shelly device on your network.

Does that help you?

**Comment by frenck** [comment]
@cwestdoerp ?

**Comment by frenck** [comment]
Looking at the documentation, there is no reference to that. This is part of the integration configuration flow in the core, not the documentation.

**Comment by mamrai1** [comment]
Need to update documentation when users use shelly with unicast colot/coap instead of multicast.
Users hace to add under colot peer the home assistant ip and 5683 port
