### ISSUE TITLE
Examples required for entity objects

### ISSUE THREAD

**Issue by jrb80** [home-assistant/home-assistant.github.io#16977]
### Feedback

It's unclear how to use the [Configuration Variables](https://www.home-assistant.io/lovelace/picture-glance/#configuration-variables) for the [Options for Entities](https://www.home-assistant.io/lovelace/picture-glance/#options-for-entities) when using the [Picture Gland Card](https://www.home-assistant.io/lovelace/picture-glance). 

I was unable to find any useful examples to configure the Options For Entities and had to resort to Reddit. For example, here is an example to change icon https://www.reddit.com/r/homeassistant/comments/ct2ncv/change_icon_on_picture_glance_entities/

### URL

https://www.home-assistant.io/lovelace/picture-glance/

### Version

2021.3.4

**Comment by frenck** [comment]
I assume you mean: it is unclear what an entity object is, right?

**Comment by jrb80** [comment]
It's unclear how to use the [Configuration Variables](https://www.home-assistant.io/lovelace/picture-glance/#configuration-variables) for the [Options for Entities](https://www.home-assistant.io/lovelace/picture-glance/#options-for-entities) when using the [Picture Gland Card](https://www.home-assistant.io/lovelace/picture-glance). 

I would like to use options "prefix" and "suffix" against the entity however there are no reference examples for any of the options.

**Comment by frenck** [comment]
Ol, yeah: Entity objects that is.

That doesn't have an example on this page indeed.
