### ISSUE TITLE
自动化故障

### ISSUE THREAD

**Issue by a7496964** [home-assistant/home-assistant.github.io#16981]
### Feedback

117版本  的温度自动化正常        现在的版本温度自动化   比如说现在的温度是15度     设小于20度  触发            自动化打开   必须是从21到20度 才能触发 成功         以前的版本   自动化断开再打开  只要小于20度的温度 都能触发  一次成功 

### URL

https://www.home-assistant.io/integrations/cloud/

### Version

2021.3.4

**Comment by frenck** [comment]
I'm sorry, we only communicate in English on all official Home Assistant resources.
Please re-submit the issue in the English language. Thanks 👍
