### ISSUE TITLE
Change the order of the options in a input_select

### ISSUE THREAD

**Issue by RichardvanGestel** [home-assistant/home-assistant.github.io#16988]
### Feedback

When I create a helper via the menu option, I cannot easily change the order. It would be helpful if you could.

### URL

https://www.home-assistant.io/integrations/input_select/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
