### ISSUE TITLE
UPNP issue with Netgear R6700v3

### ISSUE THREAD

**Issue by Rudysmama** [home-assistant/home-assistant.github.io#16989]
### Feedback

Router is discovered upon set up of the home assistant integrations.  It is recognized as 1 device with 8 entities.  The entities do not populate data.  When the entities are selected it indicates that they are currently unavailable.  

### URL

https://www.home-assistant.io/integrations/upnp/

Upon research, it appears that the data would appear for other netgear routers that are compatible with PyNetgear - https://github.com/MatMaul/pynetgear/blob/master/README.md.  We have documented the issue, screenshots from both Home Assistant and our routers on the forum at https://community.home-assistant.io/t/problems-connecting-to-new-router/275818.  

Any assistance with this issue would be appreciated.

**Comment by StevenLooman** [comment]
Hi there @Rudysmama. Sorry for not responding earlier, I must have missed the notification.

From the forum thread I see that you're running from docker, using host mode. Can you confirm that you are able to connect to the router?

You can do this by installing `async_upnp_client` (already installed in your docker container) and run:
```
$ upnp-client search
{"Cache-Control": "max-age=1900", "location": "http://192.168.178.1:80/RootDevice.xml", "Server": "UPnP/1.0 UPnP/1.0 UPnP-Device-Host/1.0", "ST": "upnp:rootdevice", "USN": "uuid:upnp-InternetGatewayDevice-1_0-889ffacb9043::upnp:rootdevice", "EXT": "", "_location_original": "http://192.168.178.1:80/RootDevice.xml", "_timestamp": "2021-04-03 10:58:43.498965", "_host": "192.168.178.1", "_port": "1900", "_udn": "uuid:upnp-InternetGatewayDevice-1_0-889ffacb9043", "_source": "search"}
...
```

This will give you information about all the upnp devices on your network. Find the entries to your router and get the url from the `location` field, probably something like `http://192.168.68.1/...`. Then, using upnp-client again you can query the router:
```
$ upnp-client call-action http://192.168.178.1:80/RootDevice.xml WANCommonIFC1/GetTotalBytesReceived
{"timestamp": 1617440354.067579, "service_id": "urn:upnp-org:serviceId:WANCommonIFC1", "service_type": "urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1", "action": "GetTotalBytesReceived", "in_parameters": {}, "out_parameters": {"NewTotalBytesReceived": -1867186111}}
```


Note that the `upnp` integration will only give you traffic counters. Also, the `local_ip` setting should have the IP of your NUC, not your router. It is used to determine which IP to scan from, in case you have multiple IPs. Finally, the `upnp:` config entry should not be required, the regular config flow should pick up your router through the `ssdp` integration.
