### ISSUE TITLE
Enerwave dimmers 

### ISSUE THREAD

**Issue by stepheng67** [home-assistant/home-assistant.github.io#16987]
### Feedback

I just completed the migration to z-wave js. Great job so far but I found I have 2 dimmer not coming up. 

### URL

https://www.home-assistant.io/help/reporting_issues/

### Version

2021.3.4

There enerwave dimers. Looking at my old entities they were listed as: zwave.wenzhou_mtlc_electric_appliances_enerwave_unknown_type_0111_id_0201
Are this going to be supported in the near future? The other Enverwave I have non-dimmable seem fine and the energy reporting all works fine where as in the diminished version there was no support.   

Version
core-2021.3.4
supervisor-2021.03.4
Home Assistant OS 5.12

![z-wave js panel](https://user-images.githubusercontent.com/15041502/111037620-ea3b2100-83f2-11eb-9831-6a89bc71f3ab.PNG)

**Comment by frenck** [comment]
Hi there,

You've submitted a bug report as documentation feedback. That is a bit out of place. If you want to report a bug with an integration, please do so here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
