### ISSUE TITLE
Example problem

### ISSUE THREAD

**Issue by tayfunulu** [home-assistant/home-assistant.github.io#16982]
### Feedback

for line 74
Value_template is {} instead of {{ value_json.PN532.UID }} 
There is no %RAW% for first line of example. 

### URL

https://www.home-assistant.io/integrations/tag.mqtt/

### Version

2021.3.4

**Comment by emontnemery** [comment]
Thanks @tayfunulu for reporting this 👍

Fixed by  #17563
