### ISSUE TITLE
More examples with a view

### ISSUE THREAD

**Issue by Nelis77** [home-assistant/home-assistant.github.io#16984]
### Feedback

I am new and I am trying to make sense of the lovelace UI interface and its customization.
A lot of information well documented on how to use it. Except that the results of some actions are not fully known.
There are some example codes in yaml of the different options in the lovelace ui. A picture of how this would visualise in the ui would be nice. Now it is trial and error. Which of course is not the end of the world.

Keep up the good work. As I said I am new, and I am already loving HA.

### URL

https://www.home-assistant.io/lovelace/dashboards-and-views/

### Version

2021.3.4

**Comment by frenck** [comment]
I'm not sure about your suggestion. Could you be more specific in the examples you are looking for?

YAML configuration is considered more advanced; the UI configuration does not require this information. If you are new to Home Assistant, I would strongly advise you to use the UI instead of YAML.

**Comment by Nelis77** [comment]
Ik know the yaml is code of the graphical ui. I understand the code and how
it is used. But the specific names of actions don't really ring a Bell.
I know views is the tab like interface (thanks to the picture)
What does Panel (a picture would be Nice)
What does visible (a picture would be Nice)
I am probably a little bit too new. I guess I should search for more
examples of users.

But thanks anyway

Kind regards

Niels



Op za 13 mrt. 2021 18:37 schreef Franck Nijhof ***@***.***>:
