### ISSUE TITLE
Wheel Pressure in BAR not PSI

### ISSUE THREAD

**Issue by cwestdoerp** [home-assistant/home-assistant.github.io#16999]
### Feedback

Hello,
ich connected my car into homeassitant.
on my android phone the app shows wheel pressure in BAR not PSI,
Where can i switch it in homeassitant - i cant find it.

### URL

https://www.home-assistant.io/integrations/mazda/

### Version

2021.3.4

**Comment by bdr99** [comment]
Thanks for reporting this. Currently the Mazda integration uses PSI for tire pressure, regardless of your Home Assistant unit setting. In the future I will change it to use bar if your Home Assistant is set to metric units.

**Comment by bdr99** [comment]
By the way, this issue was posted in the wrong repo. This repo is for documentation issues. This should have been reported in [home-assistant/core](https://github.com/home-assistant/core)
