### ISSUE TITLE
Missing `scan_interval` documentation

### ISSUE THREAD

**Issue by denilsonsa** [home-assistant/home-assistant.github.io#16993]
### Feedback

The example code shows `scan_interval: 60`. However, there is no description of that key. Is it in seconds? Is it optional? What is the default?

This feedback applies to the main `rest` documentation, as well as those related pages (such as *RESTful Sensor* and others).

### URL

https://www.home-assistant.io/integrations/rest/

### Version

2021.3.4

**Comment by frenck** [comment]
Scan interval is a generic platform option (and documented as such). Thus is not a feature of this integration platform but a generic Home Assistant feature.

**Comment by denilsonsa** [comment]
Oh, this one: https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval

Too bad the built-in website search doesn't show it in the results. I had to resort to [Google search](https://www.google.com/search?q=site%3Awww.home-assistant.io+scan_interval) to find it.

![Screenshot of the search results for `scan_interval`](https://user-images.githubusercontent.com/121676/111054474-35921580-846d-11eb-9960-c6e20425e9be.png)

Thanks for your response, anyway!
