### ISSUE TITLE
What does 'wrapped in apostrophes' mean?

### ISSUE THREAD

**Issue by davs2rt** [home-assistant/home-assistant.github.io#17009]
### Feedback

Several times this page uses the phrase "wrapped in apostrophes".  An example would eliminate ambiguity.  Did you mean `x' or 'x'.

### URL

https://www.home-assistant.io/integrations/smtp/

### Version

2021.3.4

**Comment by systemcrash** [comment]
should read: "enclosed in double-quotes" - if the style guide is anything to go by.
