### ISSUE TITLE
Velux integration

### ISSUE THREAD

**Issue by Dragoniacs16** [home-assistant/home-assistant.github.io#17001]
### Feedback

Hi !
Can you add the possibility to intergate VELUX directly from web interface ? Such as many others....
Thank you !

### URL

https://www.home-assistant.io/integrations/velux/

### Version

2021.3.4

**Comment by Dragoniacs16** [comment]
Any news ?

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
