### ISSUE TITLE
HassOS on NUC install docs

### ISSUE THREAD

**Issue by sparkydave1981** [home-assistant/home-assistant.github.io#17008]
### Feedback

The docs speak of flashing an SD card which seems like a copy/paste from the RPi install procedure, however NUC's use a SSD so this needs to be correctly reflected.

Given the above, the procedure is different.  There should be two ways listed:
1) Remove SSD from the NUC and burn the HassOS image file to it using Etcher on another computer via a USB adaptor.  Re-install the SSD into the NUC and boot.
2) Create a Linux boot USB stick (ie: Ubuntu) and boot the NUC with the USB stick plugged in.  Select the Linux GUI to be loaded an install Etcher into the Linux GUI.  Run Etcher and burn the HassOS NUC image to the internal SSD.  (This can be from a second USB stick or by downloading the image from the HA website from within the Linux GUI)

### URL

https://www.home-assistant.io/installation/nuc

### Version

2021.03.4

**Comment by sparkydave1981** [comment]
This issue is still outstanding as the docs are still wrong.

**Comment by agners** [comment]
The docs have been updated with https://github.com/home-assistant/home-assistant.io/pull/18147.
