### ISSUE TITLE
It doesn't work as written...at all for macOS.

### ISSUE THREAD

**Issue by Fumado** [home-assistant/home-assistant.github.io#17017]
### Feedback

Supposedly, after you install the VirtualBox machine, you should be able to connect to the running instance using a browser to homeassistant.local:8123.  No, this does not happen, even if you using the IP address.  It also says to observe the VM boot process, and the documentation says it  assumes that you have python already installed.  Is this on the Mac or in the VM?  If on the VM, if it's a image of the OS, why would I have to install Python?  Doesn't it make sense to have the VM actually work? 

### URL

https://www.home-assistant.io/installation/macos/

### Version

2021.3.4

**Comment by frenck** [comment]
There are 2 different installation methods listed on that page. Not 1. So either install using the Home Assistant Operating System as a VM, or install Home Assistant Core directly in Python (as explained here: <https://www.home-assistant.io/installation/>, methods).

> Supposedly, after you install the VirtualBox machine, you should be able to connect to the running instance using a browser to homeassistant.local:8123. No, this does not happen, even if you using the IP address.

It should. It sounds like you are in need of support, for which I would recommend using the Discord chat or Community Forums.

**Comment by ikifar2012** [comment]
But why are the instructions for installing Home Assistant Core on Linux on the MacOS page? Shouldn't that be removed or shortened to not include the Debian commands?

**Comment by frenck** [comment]
That is indeed a different problem. However, your question was related to your VM originally?

**Comment by Fumado** [comment]
I couldn’t get the Mac VM to work, so I installed the Python version on a Rasberry pi, and that worked.  However all my devices are HomeKit, which aren’t supported.  But thanks for the response anyway!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by frenck** [comment]
> However all my devices are HomeKit, which aren’t supported.

? We have native HomeKit support... Both as a client and as a controller
