### ISSUE TITLE
What's missing from Lovelace cards descriptions

### ISSUE THREAD

**Issue by bobkal** [home-assistant/home-assistant.github.io#17029]
### Feedback

In reading the descriptions of the various Lovelace cards, what's missing is "What can I do with this?"
The Calendar card, for example, seems to have no purpose other than displaying a calendar. There must be another purpose to it. There are many other Lovelace cards without a meaningful purpose being expressed.

### URL

https://www.home-assistant.io/lovelace/calendar/

### Version

2021.3.4

**Comment by frenck** [comment]
> seems to have no purpose other than displaying a calendar. There must be another purpose to it. 

Don't want to disappoint, but uh... that its only purpose.

> There are many other Lovelace cards without a meaningful purpose being expressed.

That is definitely good feedback!

**Comment by bobkal** [comment]
Thanks! At least I know that I am not missing something.
