### ISSUE TITLE
No image available from the entity camera 

### ISSUE THREAD

**Issue by MiAutomations** [home-assistant/home-assistant.github.io#17028]
### Feedback

I have no image/video from the entity camera Blink outdoor over the blink integration 

### URL

https://www.home-assistant.io/integrations/blink/

### Version

2021.3.4

Hello Team 

I have installed the Blink integration with no problem. But I'm unable to get the image/vide from the camera entity 

I have the entity's of the camera created but no video 

![image](https://user-images.githubusercontent.com/47602733/111347891-8ecd9500-8677-11eb-9ec7-9dcfe43ccdf3.png)

![image](https://user-images.githubusercontent.com/47602733/111347916-94c37600-8677-11eb-864e-4722b71b7061.png)

Can you please help me in order to solve this issue? 

Thank you in advance for your help and support

**Comment by frenck** [comment]
Sounds like you want to report an issue with an integration. However, this is documentation feedback.

To report an issue with an integration, please report an issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
