### ISSUE TITLE
Command line sensor - using external python script

### ISSUE THREAD

**Issue by NguyenToan1984** [home-assistant/home-assistant.github.io#17036]
### Feedback

Guidline is not so clear for new member.
to imporve, for my opinion, please also show where to save external python script on hassio

### URL

https://www.home-assistant.io/integrations/sensor.command_line/

### Version

2021.3.4

For new member of hassio like me with less knowledge of hassio. I don't know where I can create python script and save on hassio.
![Capture](https://user-images.githubusercontent.com/29554537/111414729-0b618180-8713-11eb-8346-c1476e10a951.PNG)

**Comment by frenck** [comment]
> to imporve, for my opinion, please also show where to save external python script on hassio

That is up to you really?
