### ISSUE TITLE
RiscoCloud is becoming a paid feature

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#17033]
### Feedback

I just got notified that the RiscoCloud component is being set behind a paywall. So far it was free but also this has come to an end.

Maybe we should update the documentation to reflect/state this explicitly?

The changed would be applied starting on april/2021 apparently. With no local api available I think people should be well aware of usage for this integration to be able to use/activate it.

### URL

https://www.home-assistant.io/integrations/risco/

### Version

2021.3.4

**Comment by OnFreund** [comment]
Feel free to open a PR with the relevant changes.

**Comment by frenck** [comment]
I'm happy to help out with a PR.
Can any of you provide me details on where to find the information about this?

**Comment by ghost** [comment]
hi @frenck , I only have an email that I received from my security specialist. It seems that Risco doesn't mention any cost on their website directly but use their network of installers/specialist to push these changes (and charge the costs).

https://www.mes-systems.co.uk/changes-to-the-risco-cloud/
https://www.smartechsecurity.co.uk/renew-my-app/renew-risco-cloud
https://castlealarms.co.uk/risco-fees-2021/

> As from January 2021, Risco have implemented charges for use of their Cloud Features which includes iPhone/Android app you use to set & unset the alarm. This is a cost we will have to pass onto the customer for all existing and future alarm systems installed.
These charges fall in line with other alarm manufacturers such as Pyronix who charge end users for Cloud features also.
You will begin receiving advanced notification of what the charges are during December 2020 and invoiced from January 2021.
Should you not wish to pay this the Cloud features can be disabled and you will no longer be charged going forward, the alarm will continue to work using the standard features such as tags, fobs and codes.
Systems effected are as follows:
RISCO LightSYS2
RISCO Agility
RISCO ProSYS

If needed I can provide a similar mail I got.. lmk

I also looked into possible alternatives and it looks like the only way to connect to the alarm is using the KNX module: https://www.riscogroup.com/netherlands/products/product/52944 This wil ensure you can work completely offline but at a high cost off course. I was told it costs €1251 excl. VAT and excl. installation.

My gut feeling tells me that prices are bound to go up in the upcoming years once they know who pays and who doesn't.

**Comment by frenck** [comment]
Thanks for that! I've opened a small PR to add a note.
