### ISSUE TITLE
Drag and drop always enabled option

### ISSUE THREAD

**Issue by basje56** [home-assistant/home-assistant.github.io#17037]
### Feedback

Drag and drop is available since not so long ago, which is awesome. It would be great to have the option to leave Drag and Drop always on. Now you have to push a button before it's available

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
