### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by TompaNation** [home-assistant/home-assistant.github.io#17030]
### Feedback

Hi, I did not know were I should write about some feedback on all the different features so I just do it here. First of all I LOVE HomeAssistant! And I love that there are YAML examples of all the stuff that is here. All I miss is the same examples that are available with YAML could also be shown how to do within the UI. 

Best regards 
Tomas 

### URL

https://www.home-assistant.io/lovelace/

### Version

2021.3.4

**Comment by frenck** [comment]
We try to reach a point where that should not be needed. Additionally, our UI changes really fast, keeping the screenshots and such updated, is currently an impossible task.

**Comment by TompaNation** [comment]
That's understandable!

Den tis 16 mars 2021 18:45Franck Nijhof ***@***.***> skrev:
