### ISSUE TITLE
Gui vs Command line

### ISSUE THREAD

**Issue by MickW69** [home-assistant/home-assistant.github.io#17034]
### Feedback

Took me ages to eventually find out HOW to put xyz in configuration.yaml or even where that damn file was.  A comment about the addon store and Visual Studio Code would be REALLY helpful around here.

### URL

https://www.home-assistant.io/getting-started/automation/

### Version

2021.3.4

**Comment by frenck** [comment]
The page you link/left feedback on, does not use YAML configuration.

YAML configuration is introduced further into the getting started guide, when reaching the advanced configuration section: <https://www.home-assistant.io/getting-started/configuration/>

It also contains instructions on how to install an official add-on and start editing the configuration.yaml file.

My current guess, it that you didn't follow the getting started guide fully?

Please note, the VS Code add-on, is not an official add-on maintained by the Home Assistant project; thus not part of our documentation.

**Comment by MickW69** [comment]
Yep, fair point, I added it here because at the bottom of this page there are links to Triggers, Conditions and Actions, all of which have reference to command-line interface.

**Comment by frenck** [comment]
Aah right, that is good feedback, thanks 👍
