### ISSUE TITLE
gatebox (blebox)

### ISSUE THREAD

**Issue by garciave001** [home-assistant/home-assistant.github.io#17038]
### Feedback

I've a garage gate controlled with a gatebox with close position sensor. The blebox app gets the currentPos but homeassistant doesn't. Everything is updated to the last version. Gatebox firmware 0.1010.
How can I get the position values in Homeassistant?

### URL

https://www.home-assistant.io/integrations/blebox/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by garciave001** [comment]
I think is an issue. Homeassistant doesn't get positions from the gatebox since last firmware update.

**Comment by frenck** [comment]
Please report issues with integration in the core issue tracker. Documentation feedback is not going to fix an integration issue.
