### ISSUE TITLE
Is information regarding last_updated on the last_changed line?

### ISSUE THREAD

**Issue by pearson** [home-assistant/home-assistant.github.io#17031]
### Feedback

Information regarding the last_updated line seems to be on the last_changed line. This was somewhat confusing at first, as it suggests that last_changed might change under the same conditions as last_updated.

### URL

https://www.home-assistant.io/integrations/history/

### Version

2021.3.4

The line for `last_changed` states:
> `last_changed`: timestamp last time the state has changed. ___A `state_changed` event can happen when just attributes change.___

This is followed by the line for `last_updated`:
> `last_updated`: timestamp anything has changed (state, attributes)

It seems that the second sentence on the `last_changed` probably belongs on the `last_updated` line.

**Comment by frenck** [comment]
Yeah that is actually incorrect.

`last_changed`, is the last time when just the state was changed.
`last_updated`, is the last time anything has been changed. State changes, attribute changes, anything.

Thanks for the feedback! 👍
