### ISSUE TITLE
Fan integration doc page should list the possible preset modes

### ISSUE THREAD

**Issue by tonyh220** [home-assistant/home-assistant.github.io#17044]
### Feedback

With version 2021.3, the fan integration was changed and the new set_preset_mode service was introduced.  However, the main documentation page for the fan integration does not list the possible preset modes.  These are only available in full in the patch notes for 2021.3.  The documentation should be updated to list all valid, possible values for the set_preset_mode service call.

### URL

https://www.home-assistant.io/integrations/fan/

### Version

2021.3

**Comment by frenck** [comment]
It is technically not possible to list those.

Presets are integrated and device-specific and not generalized.
