### ISSUE TITLE
Rest option scan interval not defined but used in example

### ISSUE THREAD

**Issue by jane-t** [home-assistant/home-assistant.github.io#17047]
### Feedback

Rest option scan_interval not defined but used in example

### URL

https://www.home-assistant.io/integrations/rest/

### Version

2021.3.4

**Comment by frenck** [comment]
Scan interval is a generic Home Assistant platform option and not specific to the rest integration:

<https://www.home-assistant.io/integrations/image_processing#scan_interval-and-optimizing-resources>
