### ISSUE TITLE
Android IP Webcam - Describe how to add a switch manually

### ISSUE THREAD

**Issue by sadmin91** [home-assistant/home-assistant.github.io#17042]
### Feedback

Could add a section to create manually a switch like the Android IP Webcam integration does?

### URL

https://www.home-assistant.io/integrations/android_ip_webcam/

### Version

2021.3.4

**Comment by frenck** [comment]
I'm not sure what your question/suggestion is? Could you elaborate a bit more?

**Comment by sadmin91** [comment]
Hello,

On « Alternate Configuration Method » chapter, is it possible to describe how to create manually a sensor to control the light on telephone (if this option is avalaible)?

Regards
