### ISSUE TITLE
Adding a motor feeder

### ISSUE THREAD

**Issue by ebyna** [home-assistant/home-assistant.github.io#17052]
### Feedback

Please, I need to monitor the feeder motor. And then calculate the power

### URL

https://www.home-assistant.io/integrations/ecoal_boiler/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
