### ISSUE TITLE
joaoapps_join documentation config variables section unclear

### ISSUE THREAD

**Issue by goalcam** [home-assistant/home-assistant.github.io#17056]
### Feedback

The documentation doesn't explain the configuration variables for the joaoapps_join section of the config.yaml example. API key is mostly clear (though this was already provided?) but the group parts are not defined.

### URL

https://www.home-assistant.io/integrations/joaoapps_join/

### Version

2021.3.4

**Comment by frenck** [comment]
The group parts? The example/docs are showing that the device_id can be used to send messages to join groups.

![image](https://user-images.githubusercontent.com/195327/111838516-b9c71b80-88f9-11eb-827f-39593cbe0546.png)

A group is no different from a generic device ID.
