### ISSUE TITLE
 View pending feedback is not limited to open "issues"

### ISSUE THREAD

**Issue by ludeeus** [home-assistant/home-assistant.github.io#17050]
### Feedback

When you click the " VIEW PENDING FEEDBACK" link, you are taken to the issue tracker here on GitHub, but it does not filer on open status. A closed issue is no longer "pending", and those should be filtered out in the result.
![image](https://user-images.githubusercontent.com/15093472/111617543-8befb300-87e3-11eb-93a8-22d9047c9b0b.png)

### URL

https://www.home-assistant.io

Link to the source for the feedback "box": <https://github.com/home-assistant/home-assistant.io/blob/current/source/_includes/feedback.html>

**Comment by frenck** [comment]
Hmm, that is true...

I kinda did that on purpose (it does sort), to prevent multiple issues being opened on feedback that was given before.

So, maybe we should adjust the text to just "View feedback"?

**Comment by ludeeus** [comment]
I guess to also show 'invalid' feedback that make sense
