### ISSUE TITLE
Turn On Action not working

### ISSUE THREAD

**Issue by healeydave** [home-assistant/home-assistant.github.io#17059]
### Feedback

I have followed the documentation and the config on this page and the media player for my LG TV was created and shows me all the relevant information. I can even use the buttons, but if I power off the TV, I can't turn it back on again even after following the advanced configuration instructions.

### URL

https://www.home-assistant.io/integrations/lg_netcast/

### Version

2021.3.4

**Comment by frenck** [comment]
It sounds like you are trying to report an issue with an integration, however, this is the feedback form for the documentation. There is no amount of documentation we can adjust to fix an issue with the integration. Did you mean to report an issue with an integration on the core issue tracker instead?

<https://github.com/home-assistant/core/issues>

**Comment by ludeeus** [comment]
Actually, the docs could be clearer here.
I don't think this is an issue at all if you use a switch for the service that actually works

**Comment by frenck** [comment]
Ok, in that case, I'm not sure what the problem is?

**Comment by ludeeus** [comment]
LG (and other TVs) does not have a turn on function, so you need to set up something like waking lan if the tv support that, or some rf blaster, and use that as a service in the turn on action

**Comment by ludeeus** [comment]
OFC that's just guessing, since no config/logs are provided I'm not sure if that is the case here

**Comment by healeydave** [comment]
@ludeeus Oh, so the instructions for the turn on action require a separate trigger?

In that case apologies, I was reluctant to create an issue in the first place but I couldn't find any information other than what was on the HA doc page.

**Comment by ludeeus** [comment]
You need the service you define as the turn_on_action to actually work on its own before it can work here.

**Comment by healeydave** [comment]
ok, thanks for the clarification, I'll close this case as I don't want to waste any more of your time.

**Comment by ludeeus** [comment]
If you don't mind I don't think this should be closed just yet.
<https://www.home-assistant.io/integrations/webostv/#turn-on-action> for instance has proper description for that config, I think we should add some of that to netcast as well

**Comment by healeydave** [comment]
No problem at all, gives some justification for me opening in the first place :)
