### ISSUE TITLE
Broken Link: Contribute Config Files

### ISSUE THREAD

**Issue by TheDK** [home-assistant/home-assistant.github.io#17066]
### Feedback

The Link given in the last part of the info is broken:
https://zwave-js.github.io/node-zwave-js/#/development/config-files?id=contributing-configuration-files
I did not find a new URL to replace it...

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2021.3.4

**Comment by MartinHjelmare** [comment]
I think it's this url:
https://zwave-js.github.io/node-zwave-js/#/config-files/contributing-files

If you have time please make a pull request and adjust the link. Thanks!

**Comment by TheDK** [comment]
Done: https://github.com/home-assistant/home-assistant.io/pull/17070
