### ISSUE TITLE
ZHA.REMOVE

### ISSUE THREAD

**Issue by FelisucoVFR** [home-assistant/home-assistant.github.io#17072]
### Feedback

It would help a lot if we could see an example on how to use this service.
It took me a while knowing how is just the ieee id format to know what to search.
Of course, later failed to me. With an example I could may be realize what I am doing wrong.
I could not find anything at Google....

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2021.3.4

**Comment by Hedda** [comment]
FYI, there look to be a somewhat related discussion by the zigpy (and ZHA) developers here -> https://github.com/zigpy/zigpy/discussions/572

**Comment by Adminiuga** [comment]
When you open the service in Developer tab, it does show the parameters
![image](https://user-images.githubusercontent.com/5826160/114583432-93be3e00-9c4f-11eb-99db-709fb1d8c5a8.png)

IEEE address of the device is available on the device card of Zigbee devices
![image](https://user-images.githubusercontent.com/5826160/114583553-b6505700-9c4f-11eb-92c9-72cd108806ce.png)

**Comment by FelisucoVFR** [comment]
> When you open the service in Developer tab, it does show the parameters
> ![image](https://user-images.githubusercontent.com/5826160/114583432-93be3e00-9c4f-11eb-99db-709fb1d8c5a8.png)
> 
> IEEE address of the device is available on the device card of Zigbee devices
> ![image](https://user-images.githubusercontent.com/5826160/114583553-b6505700-9c4f-11eb-92c9-72cd108806ce.png)

Yes, thanks. As I said, later I could find it. I just wanted you to include a little more understandable instructions for future noobs.
I cannot live without ZHA now! ❤️

Thanks!

**Comment by Hedda** [comment]
>  I just wanted you to include a little more understandable instructions for future noobs.

Like so perhaps? -> https://github.com/home-assistant/home-assistant.io/pull/17457
