### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by digdilem** [home-assistant/home-assistant.github.io#17076]
### Feedback

Excellent documentation for a frankly absurd amount of steps required to get Nest working for third parties. 

Without this guide it would be almost impossible to achieve this, so full credit to the author(s). Top job.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.3.4

**Comment by frenck** [comment]
🎉  That one is for you @allenporter 

Thanks for sharing @digdilem! Always nice to hear a positive voice ❤️
