### ISSUE TITLE
Install Home Assistant Core - hass process killed on user exit

### ISSUE THREAD

**Issue by Wiggum127** [home-assistant/home-assistant.github.io#17080]
### Feedback

Following the instructions for the Home Assistant Core you end with running the hass process.
And all things work, great.
However, when logging out everything stops working due to end of the user session. It would be good to explain to use "nohup hass &" for example.

And how do you stop/start from the CLI ?
And it is not clear what sequence of commands to follow if you require to stop or start the process again.
for example: do you need to run the python3.8 -m venv . command everytime you wish to start hass ?

### URL

https://www.home-assistant.io/installation/linux/

### Version

2021.3.4

**Comment by ikifar2012** [comment]
I assume you are using the python venv install right?
If so most people who use the venv install method run home assistant as a systemd service which you can start or stop 
If you want something easy to manage I highly recommend the docker install method

**Comment by Wiggum127** [comment]
The installation guidelines for HA core are missing instructions how to make sure the hass service gets created correctly (with systemd or sysinit) and started/stopped. So I suggest to improve the guidelines with those steps in order close the loop.

**Comment by frenck** [comment]
> The installation guidelines for HA core are missing instructions how to make sure the hass service gets created correctly (with systemd or sysinit) and started/stopped.

We consider that an advanced topic and out of scope for our documentation. The installation method you are running (in a python environment) is meant for people familiar with their operating system and Python. We are not a guide on how to use systemd or Python itself.

> do you need to run the python3.8 -m venv . command everytime you wish to start has ?

That question indicates you are not. I would not recommend running that installation method in your case, as you don't match the target audience.

**Comment by frenck** [comment]
Thanks for your feedback, but going to close it. The way it is documented was deliberately chosen and part of a bigger architectural decision the project and its members made.
