### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by tomshaffner** [home-assistant/home-assistant.github.io#17090]
### Feedback

In my case it was very unclear what username was actually on my account. In the end it ended up being my phone number minus the country code (which was entered separately). This was true even though I have an email account linked. A note about this possibility might help others in my situation.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.3.4

**Comment by keatkong** [comment]
Please give more information and example will help me too.
