### ISSUE TITLE
Problem uploading an image via a link in Balenaetcher Could be the problem?

### ISSUE THREAD

**Issue by adeltut** [home-assistant/home-assistant.github.io#17096]
### Feedback

Hello, when trying to install your operating system through Balena Etcher, it was not crowned with success, which may be the problem. If you just follow the links and download this file and install the image on rasberri pi, then you just get a black screen (sometimes pink for some reason) and all to the Internet is not connected via a wire (LEDs are off) what could be the problem?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.3.4

Hello, when trying to install your operating system through Balena Etcher, it was not crowned with success, which may be the problem. If you just follow the links and download this file and install the image on rasberri pi, then you just get a black screen (sometimes pink for some reason) and all to the Internet is not connected via a wire (LEDs are off) what could be the problem?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
