### ISSUE TITLE
dlib wont work on hassio instance

### ISSUE THREAD

**Issue by checkiecheck** [home-assistant/home-assistant.github.io#17102]
### Feedback

Running on Hassio, the suggested apt-get wont work. so the whole integration seems unavailble for hassio in this context as integration doesnt load the requirements itself.

"If the platform fails to load because it could not install its requirement, install cmake: sudo apt-get install cmake."

### URL

https://www.home-assistant.io/integrations/dlib_face_identify/

### Version

2021.3.4

**Comment by frenck** [comment]
Yes this integration is not available for OS, Supervised and Container installation types. The page should make that clear.
