### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Spiffo** [home-assistant/home-assistant.github.io#17119]
### Feedback

Hi, would be good if you specify what the "language" parameter should look like (ISO 639-2 Code, ISO 639-1 Code, ...)

### URL

https://www.home-assistant.io/integrations/notify.tts/

### Version

2021.3.4

**Comment by Spiffo** [comment]
https://www.home-assistant.io/integrations/google_translate/ contains the text to use:

Check the complete list of supported languages (languages where “Talk” feature is enabled in Google Translate) for allowed values. Use the 2 digit language code which you can find at the end of URL when you click on Language name.

Let me try to fix this :)

**Comment by frenck** [comment]
This page is generic. The comment you are making is integration-specific. Please see the integration documentation for specifics.
