### ISSUE TITLE
Not Working for LED Control

### ISSUE THREAD

**Issue by rxilher** [home-assistant/home-assistant.github.io#17113]
### Feedback

After numerous attempts following steps noted I am only able to get Magic Hue Led controllers to show as an entity. I can turn them off once, but then control capability ceases. You cannot turn back on or control at all after turning off. No dimming, no action at all. 

### URL

https://www.home-assistant.io/integrations/flux_led/

### Version

2021.3.4

**Comment by frenck** [comment]
Hi there @rxilher!

Seems like you are trying to report an issue with an integration, not documentation.

Please report issue with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
