### ISSUE TITLE
Not amused folks

### ISSUE THREAD

**Issue by drewy-uk** [home-assistant/home-assistant.github.io#17110]
### Feedback

I’m sure the intent is to be helpful. However this functionality should most definitely be opt in, absolutely not on by default. 

### URL

https://www.home-assistant.io/more-info/pwned-passwords/

### Version

2021.3.4

**Comment by SeanPM5** [comment]
The "provide feedback" form is intended for improving the website documentation.

Feature requests and suggestions should be posted on the [community forums](http://community.home-assistant.io/) instead please. Thanks.
