### ISSUE TITLE
NissanConnect EV / Nissan Connect

### ISSUE THREAD

**Issue by Krolykke** [home-assistant/home-assistant.github.io#17141]
### Feedback

Hi,

Reading the documentation, something is not clear to me.

I am using Nissan Connect for my Leaf, is that compatible with this integration?

### URL

https://www.home-assistant.io/integrations/nissan_leaf/

### Version

2021.3.4

**Comment by frenck** [comment]
> The nissan_leaf integration offers integration with the NissanConnect EV cloud service. 

Do you have access to the NissanConnect EV Cloud service that is linked in the first line of the documentation?

<https://www.nissan.co.uk/dashboard.html>

**Comment by Krolykke** [comment]
Unfortunately not :-( I connect to "the other" platform, there seems to be 2. I am in Denmark, not UK.

**Comment by Krolykke** [comment]
I do, but not on the link you posted.

<img width="762" alt="Skærmbillede 2021-04-01 kl  12 37 03" src="https://user-images.githubusercontent.com/31382760/113283592-c2035b80-92e8-11eb-8f98-2fa8e556116c.png">

Does this image make any sense?

**Comment by Krolykke** [comment]
![image](https://user-images.githubusercontent.com/31382760/113287390-d0a04180-92ed-11eb-9f52-1fda0ab7dd44.png) the NissanConnect app is working

**Comment by Krolykke** [comment]
My issue looks like https://github.com/home-assistant/core/issues/44536 (closed).

2021-04-01 12:31:29 DEBUG (SyncWorker_1) [homeassistant.components.nissan_leaf] Logging into You+Nissan...
2021-04-01 12:31:33 ERROR (SyncWorker_1) [homeassistant.components.nissan_leaf] An unknown error occurred while connecting to Nissan: <class 'pycarwings2.pycarwings2.CarwingsError'>

`nissan_leaf:
username: "xxx@xxx.xx"
password: "xxxxxxxxxxxxx"
region: "NE"
update_interval: hours: 1
update_interval_charging: minutes: 15
update_interval_climate: minutes: 5
force_miles: false
logger:
default: critical
logs:
homeassistant.components.nissan_leaf: debug
homeassistant.components.sensor.nissan_leaf: debug
homeassistant.components.switch.nissan_leaf: debug`

Sorry, can't figure out how to format the config correct :-(

I checked the username and PWD, it is correct, it already works with the Nissan Connected EV App

Core Version: core-2021.3.4
Operating System: Home Assistant OS 5.12
Supervisor Version: supervisor-2021.03.6

**Comment by frenck** [comment]
The link I posted, is the one from the documentation... if you don't have access to that, according to the documentation, it doesn't work.

If you want additional features for an integration, please use our community forums. We have a feature requests section there.

**Comment by ugn79** [comment]
My a say some words on that. I have the same problem, but on my side it worked with my old Nissan LEAF. I got a newer LEAF 2 weeks ago and with this car, Nissan is unsing the newer Telematic system (Nissan Connect), the old one is Nissan Connect EV. The documentation at Hassio is refeering to the old telematic system (Nissan Connect EV). This works fine. The question now is: who has to be contacted to updaten the Hassio integration for the new Nssan telematic system (Nissan Connect)? Regards, Jürgen
