### ISSUE TITLE
Need a note about running HA in docker and using Lets Encrypt

### ISSUE THREAD

**Issue by Lunakin42** [home-assistant/home-assistant.github.io#17146]
### Feedback

see my message (posted as HighWing) on this post: https://community.home-assistant.io/t/solved-error-using-docker-and-ssl-invalid-config-for-http-not-a-file-for-dictionary-value/92230/13

Basically it would have helped me out greatly if there was a note that Lets's Encrypt uses symlinks for the certs. To which if you are running HA in Docker, you need to make sure you either expose the real location of the certs, or copy the real certs to a location the docker container can access.

### URL

https://www.home-assistant.io/integrations/http/

### Version

2021.3.4

**Comment by frenck** [comment]
That sounds more like something for the let's encrypt documentation. How you arrange your SSL certificates is out of scope for our project. Of course, if you want to use the files, Home Assistant needs to be able to access them.

Nevertheless, thank you for your feedback 👍
