### ISSUE TITLE
Console command `ha authentication reset` documentation is incorrect

### ISSUE THREAD

**Issue by Cylindric** [home-assistant/home-assistant.github.io#17148]
### The problem

When attempting to reset a user password from the console, the documentation states:

```
Examples:
  ha authentication reset --username "JohnDoe" --password "123SuperSecret!"
```

However when I try to run that command, the quotes are *not* parsed as indictated by the example.

```
ha > authentication reset --username "mark" --password "MyNewPassword"
Error: Unknown error, see supervisor
```

If I don't put the quotes, it works:
```
ha > authentication reset --username mark --password "MyNewPassword"
Command completed successfully
```

However, the password includes the quotes! So to login, my password is now "MyNewPassword" *including the quotes*. Not what one would expect from either common convention, or the documentation.

### What is version of Home Assistant Core has the issue?

core-2021.3.4

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
_No response_
```

### Anything in the logs that might be useful for us?

```txt
_No response_
```

**Comment by frenck** [comment]
Transferred the issue to the documentation repository.

**Comment by frenck** [comment]
Actually the documentation states:

![image](https://user-images.githubusercontent.com/195327/117026368-05902180-acfc-11eb-876e-3bb3a9835842.png)


https://www.home-assistant.io/docs/locked_out/#to-reset-a-users-password-via-console

**Comment by Cylindric** [comment]
Why did you close the issue though?  I was referring to the command line help text, not the website documentation. The CLI commands explicitly put quotes around things that don't expect them. Just because the docs are correct, doesn't mean the CLI docs shouldn't be fixed...
