### ISSUE TITLE
How to disable the service Have I Been Pwned (HIBP)?

### ISSUE THREAD

**Issue by ctm514** [home-assistant/home-assistant.github.io#17144]
### Feedback

If I do not want to receive these messages, how do I disable the service Have I Been Pwned (HIBP)?
It bothers me the fact that every time I open HA, a message appears about the node red password, which I can't change, because when the password is changed, Node Red stops talking to HA

### URL

https://www.home-assistant.io/more-info/pwned-passwords/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by ctm514** [comment]
sorry, I do not communicate well in English, I shot the title, I think now it’s clearer
