### ISSUE TITLE
add MQTT settings info to Tasmota page

### ISSUE THREAD

**Issue by cweinhofer** [home-assistant/home-assistant.github.io#17152]
### Feedback

It would be helpful if this page mentioned the need to add HA's MQTT settings to the MQTT config in Tasmota. Example below.

### URL

https://www.home-assistant.io/integrations/tasmota/

### Version

2021.3.4

Under requirements, add 

- Tasmota devices' MQTT setting configured to communicate with the MQTT broker

And then under configuration, below the bullets, add

You must also configure Tasmota's MQTT settings to communicate with whatever broker you are using. Enter the broker address under host and enter a username / password combination that allows access to the broker.

If using the Mosquitto Broker Add-on for Home Assistant, first create a new Home Assistant user under Configuration > Users. Then, in Tasmota > Configure MQTT under "**Host**" enter the address of your Home Assistant instance and under "**User**" and "**Password**" enter the Home Assistant user you just created.

**Comment by emontnemery** [comment]
Fixed by #17209
