### ISSUE TITLE
Opening ports on firewall may be needed for network_mode: host to work

### ISSUE THREAD

**Issue by Jiheffe** [home-assistant/home-assistant.github.io#17154]
### Feedback

Installing HA in a Docker container on a NUC.
I found that on my system (Ubuntu 20.04.2 LTS), port 8123 was not accessible. I needed to add a firewall rule to allow access to port 8123 from the local network.
See below in Additional information.

### URL

https://www.home-assistant.io/installation/nuc/

### Version

2021.3.4

Hi,
Installing HA in a Docker container on a NUC, using Docker-compose.
I found that on my system (Ubuntu 20.04.2 LTS), port 8123 was not accessible. I needed to add a firewall rule to allow access to port 8123 from the local network:
`ufw allow from 192.168.178.0/24 to any port 8123`
I found the solution in this [Reddit](https://www.reddit.com/r/homeassistant/comments/8bkky6/cant_connect_to_docker_ha_when_running_nethost/).
I am discussing this more in detail in the [HA Forum](https://community.home-assistant.io/t/solved-fresh-install-on-nuc-with-docker-cant-connect-to-8123/294056/2).
JF

**Comment by frenck** [comment]
Yes, that is possible, however, firewall management for your machine is out of scope for our project, this is more something documentation at Docker maybe even? There are many flavors of Linux and even more flavors of firewalls, which we don't want to describe.

**Comment by Jiheffe** [comment]
Hi Franck, no worries :-) Didn't mean there's a need to add detailled instructions to the page for each configuration :-).
Maybe just a short note that people might want to check their firewall or other settings if it does not work out of the box ?
Greetings from Belgium ;-)

If you want I can help by writing a short paragraph ;-) 

JF
