### ISSUE TITLE
Need to add details about zone support

### ISSUE THREAD

**Issue by DMailMan** [home-assistant/home-assistant.github.io#17159]
### Feedback

My Onkyo receiver can handle more than one zone. How can I control the extra zones via Home Assistant ? I guess that the Onkyo integration provides for this, but there is nothing in the docs to say how to use it.

### URL

https://www.home-assistant.io/integrations/onkyo/

### Version

2021.3.4

**Comment by frenck** [comment]
It will automatically create multiple media players/entities for each zone found.

**Comment by DMailMan** [comment]
No, it didn't.
Do the extra zones need to be powered on to be detected or something ?

**Comment by frenck** [comment]
You could try? The code shows not such a hint unfortunately. If we figure out we can document it :)

**Comment by DMailMan** [comment]
After some experimentation, I think this is the summary:
If you explicitly add in a "media_player:" with "platform: onkyo" into the configuration.yaml file, then your amplifier will be discovered; without that, no devices or entities are discovered. Unfortunately, no automatic discovery of the amplifier using it's broadcast/response protocol seems to have been implemented.

With only a media_player: and platform: onkyo config entry but nothing else, you get a single amplifier entity (no devices) created with what looks like a mac address suffix, something like: "media_player.tx_nr809_0009b04987d6". No zones are created.

Sidenote: because there is no device, you cannot control the amplifier as a device in automations etc, and instead have to use it as an entity, meaning that action type "device" in an automation won't work, and you have to use 'call service' instead when creating automations to turn the amplifier or zones on and off. This was very confusing for a while, as I assumed there would be devices available when I first tried to do this.

If you look up the IP address of the amplifier and add that into the config file with a "host: xxx.xxx.xxx.xxx" entry just after the "platform: onkyo" entry, then the zones supported by the amplifier will also be discovered, even if they are not turned on, so long as the amplifier itself is responding to network connections (which is enabled by a config setting on the amplifier, and may consume extra power).

Manually looking up the IP address and editing the config file as above is required for zones to appear.

You can name the amplifier by also including a "name: xxxxxx" entry in the config.yaml file too. I don't know how to rename a zone to a friendly name in config.yaml, but you can do this by overriding an entity via a "customize" value. Select the zone you want to adjust from the Lovelace dashboard, click the three dots at the top right of the card, then click the cog at the top right of the popup, and click the last link in the dialog, labelled "entity customizations". You may need to manually change the config.yaml file to allow customizations. 


Since the Onkyo integration is implemented as part of HA Core, no separate add-ons are needed, and no integrations are need or listed  when it's working. This also means that the 'restart core' option from the Supervisor config screen is enough to experiment with different config entries - you don't need a full restart of HA.


Working all of this out took some time for an HA newbie, so I hope this saves someone else some work in future!

**Comment by DMailMan** [comment]
Another detail to add to this: it seems that if the amplifier is powered off when Home Assistant starts up (as mine usually is, for power consumption reasons), then the base amplifier entity is still retained (maybe because it's specified explicitly in the config file), but the extra zones that had been discovered are removed. They are not automatically discovered even when the amplifier is later turned on - only a restart of HA will make them re-appear, which is obviously not ideal.

I'm not sure what can be done about this, but least the behaviour seems to be clear, now.
