### ISSUE TITLE
Not working in personal cloud 

### ISSUE THREAD

**Issue by ricard0g0mes** [home-assistant/home-assistant.github.io#17155]
### Feedback

Its not working for me since a few months.
I use it in a remote server where I keep my website.
The server is working good because I receive data from another node (total energy) but not from hassio.

### URL

https://www.home-assistant.io/integrations/emoncms_history/

### Version

2021.3.4

Its not working for me since a few months.
I use it in a remote server where I keep my website.
The server is working good because I receive data from another node (total energy) but not from hassio.

**Comment by frenck** [comment]
Hi there @ricard0g0mes!

Thanks for opening an issue, however, this is the issue tracker for the documentation and is used to provide documentation feedback.

It seems like you want to report an issue with the integration itself. For that, please open an issue here:

<https://github.com/home-assistant/core/issues>


Thanks already! 👍
