### ISSUE TITLE
Leads to unwanted off switches, needs improvement 

### ISSUE THREAD

**Issue by Till604** [home-assistant/home-assistant.github.io#17156]
### Feedback

A good starting point, single sensor version works, but:
- The multi sensor version starts timer on 'on', and will turn off the light after 10 minutes even if there is continuous uninterrupted motion the whole time. 

I think the correct approach is to start the timer on 'off', under the condition that all other sensors than the one raising the event are already off (in other words, only last sensor to go to off starts the timer), and canceling the timer whenever one of the sensors goes to 'on'. 

### URL

https://www.home-assistant.io/cookbook/turn_on_light_for_10_minutes_when_motion_detected/

### Version

2021.3.4

**Comment by frenck** [comment]
This is actually really outdated documentation. Using a `wait_for_trigger` wait and restart mode of the automation makes way more sense nowadays (and is what our similar example Blueprint is using for this as well).
