### ISSUE TITLE
missing information for climate.set_preset_mode

### ISSUE THREAD

**Issue by bhaywa1** [home-assistant/home-assistant.github.io#17153]
### Feedback

Can someone update the documentation to indicate what the preset modes are that can be set? The documentation is next to useless for letting us know how this can be used and what the options actually are. For instance, the "family" was all away from home today and apparently that means that climate went into "away_mode" because an automation that I had set up for away_mode triggered, and I had not expected that it would, since I had not found any documentation on how to actually set climate into away_mode yet, and it certainly isn't configured in my system. Looking over the brief explanation in the docs shows little of value. There is no indication of what the options are, and the only example simple shows "eco" as an option. But what is "eco" and how would it be used? How does one actually configure and implement a "preset mode" for a climate device? (not how is it set).
Thank you.

### URL

https://www.home-assistant.io/integrations/climate/

### Version

2021.3.4

**Comment by frenck** [comment]
Presets modes as specific to the integration and device (and thus can not be generic documented as suggested).


Please consult the specific integration documentation our the user manual of your device.
