### ISSUE TITLE
'optimistic mode' has unclear definition in documentation

### ISSUE THREAD

**Issue by josh-m-sharpe** [home-assistant/home-assistant.github.io#17162]
### Feedback

See definitions of 'optimistic' on these pages:

https://www.home-assistant.io/integrations/switch.mqtt/
https://www.home-assistant.io/integrations/cover.mqtt/

`Flag that defines if switch works in optimistic mode.`

Elsewhere on the page you can learn that the mode can be 'forced', but it is still unclear what 'optimistic mode' does.  What is it?

It would be better to define the feature/mode/setting with words other than itself.

### URL

https://www.home-assistant.io/integrations/switch.mqtt/

**Comment by thecode** [comment]
This is from the first paragraph ([Configuration](https://www.home-assistant.io/integrations/cover.mqtt/#configuration)):

"If neither a state topic nor a position topic are defined, the cover will work in optimistic mode. In this mode, the cover will immediately change state (`open` or `closed`) after every command sent by Home Assistant. If a state topic/position topic is defined, the cover will wait for a message on `state_topic` or `position_topic`.

Optimistic mode can be forced, even if a `state_topic` / `position_topic` is defined. Try to enable it if experiencing incorrect cover operation (Google Assistant gauge may need optimistic mode as it often send request to your Home Assistant immediately after send `set_cover_position` in which case MQTT could be too slow)."

Does this answer your question? if not can you explain what is missing or unclear? Thanks

**Comment by josh-m-sharpe** [comment]
No. Don’t define the word with the word that is being defined.

Restate everything you just said without using the word “optimistic”.

**Comment by thecode** [comment]
I don't see where in the quote I copy from the configuration paragraph the word optimistic is used. 
**"In this mode, the cover will immediately change state (open or closed) after every command sent by Home Assistant. If a state topic/position topic is defined, the cover will wait for a message on state_topic or position_topic"**

Your quoted statement is from the [CONFIGURATION VARIABLES](https://www.home-assistant.io/integrations/cover.mqtt/#configuration-variables) Which is a short description that assumes you read the first paragraph.
Anyhow I don't understand would be the right way to fix it, you are welcome to suggest the right way, I am willing to edit the page to fix it, or you can do it, but I don't see anything wrong there.
