### ISSUE TITLE
Multiple shopping list displays same items

### ISSUE THREAD

**Issue by soulfire03** [home-assistant/home-assistant.github.io#17176]
### Feedback

I added multiple shopping list for different stores, but the items are global for every lists.
Is it possible to add a grouping key so I can manage different list of items please?

### URL

https://www.home-assistant.io/lovelace/shopping-list/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by soulfire03** [comment]
I used the "Provide feedback" form in the application.
I didn't knew it would post in github. Sorry for that

**Comment by frenck** [comment]
Its ok!

![image](https://user-images.githubusercontent.com/195327/112901680-5a30f300-90e5-11eb-9e5e-f34043ba2271.png)


There is no amount of documentation that I can adjust to make a feature happen 😉
