### ISSUE TITLE
Unable to set up Withings integration

### ISSUE THREAD

**Issue by tdocsa** [home-assistant/home-assistant.github.io#17174]
### Feedback

Hi Guys,
I'm trying to use the Withings integration with latest (2021.3.4) version of HA and Nabu Casa cloud.
Followed the instructions in the documentation: created my dev account, configured client ID and secret in the yaml file, but when I should add the integration itself, I get this error: "Aborted. No URL available." 
It also offers a troubleshooting guide, I tried every possible solution without any luck. 
I don't see any relevant error in the logs.
Could you please help me figure out what is going wrong?
Thanks!

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2021.3.4

![image](https://user-images.githubusercontent.com/78645264/112886638-78d9be80-90d2-11eb-8c66-1b736b57cfa8.png)

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
