### ISSUE TITLE
Device status does not work 

### ISSUE THREAD

**Issue by jeneansantos** [home-assistant/home-assistant.github.io#17185]
### Feedback

When a device is turned on manually, such as a light switch, if I turn that switch on the on/off switch manually on switch, it does not show in Home Assistant that the switch has been turned on. In the SmartLife App it perfectly shows that the device has been turned on. 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.3.4

**Comment by frenck** [comment]
Hi there,

You've submitted documentation feedback, but it seems like you want to report an issue within integration. There is no amount of documentation we can adjust to fix a bug in the software.

Please report integration issues here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
