### ISSUE TITLE
Define Lovelace display for groups of binary sensors

### ISSUE THREAD

**Issue by BigFam194** [home-assistant/home-assistant.github.io#17198]
### Feedback

I've created groups of binary sensors which be themselves correctly display as open/closed. When grouping these binary sensors together the group states display as on/off. How can I display the state of a group as open/closed? Scenario is a group of windows represented by a group so I can check if all windows are closed before leaving home. It's not nice to see that windows are "off"..

### URL

https://www.home-assistant.io/integrations/binary_sensor/

### Version

2021.3.4

**Comment by mwunderling** [comment]
Did you set the device class as "window" in your group sensor definition? ...the default behavior is on/off instead of open/closed if that wasn't set.
