### ISSUE TITLE
Install Home Assistant Core on Windows

### ISSUE THREAD

**Issue by Anton0123** [home-assistant/home-assistant.github.io#17204]
### Feedback

The instructions are for Linux, not Windows.

### URL

https://www.home-assistant.io/installation/windows/

### Version

2021.3.4

**Comment by frenck** [comment]
Incorrect. In Windows, it should be used on WSL.

**Comment by JBoye** [comment]
> Incorrect. In Windows, it should be used on WSL.

That is not mentioned anywhere
