### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by looolz** [home-assistant/home-assistant.github.io#17215]
### Feedback

This text seems to have been written when the Hue 2.0 bridge was new and not default. New users will likely be using the 2.0 bridge and never the 1.0 hue app. 

I'm too stupid and was not able to follow these instructions. More examples on how to turn on/off all lights would be nice. And if "grouping natively" in Home Assistant is suggested, it would be great with examples on how this is done.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2021.3.4

**Comment by frenck** [comment]
> This text seems to have been written when the Hue 2.0 bridge was new and not default. New users will likely be using the 2.0 bridge and never the 1.0 hue app.

Not really. Works for any.

> More examples on how to turn on/off all lights would be nice.

Once added, it are just lights in Home Assistant. Like any other light. This page is about specifics for Hue, not about how to use the rest of Home Assistant.

> And if "grouping natively" in Home Assistant is suggested, it would be great with examples on how this is done.

I guess you are referring to "Home Assistant also supports grouping of entities natively". It means, if you create a group in Hue, it will show up in Home Assistant automatically. Nothing is needed for that.

**Comment by looolz** [comment]
I dont mean to get into a debate. I just want this to be as accessible as possible for n00bs like myself. Hue has grown insanely popular, and having users new to HomeAssistant easily succeed with Hue is great. However, there are a few lines that confuse and steer away from that objective, if it indeed is an objective. Some of those lines are assuming a base knowledge of how to interact with an API and ciphering out a very long string from the API reply in order to understand which parts constitute the actual IDs of light and Rooms.

_The Room and LightGroup can be created manually through the API or the mobile app_

This would instruct a novice user to try for the app, rather than the API. The very next paragraph says:

_The 2nd generation Hue app only has the ability to create a Room. You need to use the first generation app or the API to create a LightGroup._

OK, so maybe LightGroup isn't the best recommendation. Since it requires a discontinued app for Philips. When the article then goes into more detail with examples, it is then based on `LightGroup` instead of `Room`. Maybe these two are interchangeable in the example. It's not clear to me. #still_a_n00b

_**Using Hue Scenes in Home Assistant**_

Here a nice example is provided. But the example:

`script:
  porch_on:
    sequence:
      - service: hue.hue_activate_scene
        data:
          group_name: "Porch"
          scene_name: "Porch Orange"`

Goes right into script:, it humbly want to suggest we add an example as how to add this to a button-card. I've been trying to accomplish this, by piece together documentation from [botton doc](https://www.home-assistant.io/lovelace/button/), `[hue doc](https://www.home-assistant.io/integrations/hue/)` , Developer Tools -> Services and the code editor in the card configuration in the Lovelace interface.  And I come up with something like this, which doesn't work:

`type: button
tap_action:
  action: call-service
  service: hue.hue_activate_scene
  data: null
  group_name: Office
  scene_name: Work_mode
show_name: false
show_state: true`

I completely agree that this documentation shouldn't aim at teaching the rest of HomeAssistant or grouping. But getting this integration to work with specific lights is easy with the currently  documentation, and getting groups of lights/Rooms to work just as easily is unfortunately not. I would love to help out once I figure out the easiest way to accomplish this.

**Comment by frenck** [comment]
> I dont mean to get into a debate.

I'm sorry, you might be in the wrong place in that case.

> This would instruct a novice user to try for the app, rather than the API.

That is always a struggle. As the larger part of our audience is more advanced. I think the current wording covers both and thus fine.

Honestly, reading up, it seems like you are missing basic knowledge on Home Assistant itself.
If you need support on using Home Assistant, please use our community forum or Discord chat.

**Comment by looolz** [comment]
Thanks for considering my feedback.

**Comment by frenck** [comment]
ok... sorry. I keep asking and poking to get as many details as possible.

Based on current feedback I've opened up a PR to process a couple of things I did extract from the above.

See: https://github.com/home-assistant/home-assistant.io/pull/17290
