### ISSUE TITLE
Installation gives error

### ISSUE THREAD

**Issue by minttumaa** [home-assistant/home-assistant.github.io#17210]
### Feedback

Hi,
I'm installing HA core according to instructions and get this error about pip:

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
requests 2.25.1 requires idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.
aiohttp 3.7.4 requires chardet<4.0,>=2.0, but you'll have chardet 4.0.0 which is incompatible.

I don't know yet, if it matters for installation as 'hass' is still running.
Just wanted to let you know :)

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.3.4

**Comment by ludeeus** [comment]
You can safely ignore that one, we pin the version of pip we know is working.
