### ISSUE TITLE
need screenshots (pictorial guide) on changing language

### ISSUE THREAD

**Issue by copenhaus** [home-assistant/home-assistant.github.io#17225]
### Feedback

sorry, caught in a rock and a hard place.  For some reason when I initially fire up the install, it's in Chinese.  We can't navigate simply by words (because can't read ), it would be great if this is illustrated via screenshots.

Thanks in advance.

### URL

https://www.home-assistant.io/integrations/frontend/

### Version

2021.3.4

**Comment by SeanPM5** [comment]
It's explained already on the very bottom of that page: https://www.home-assistant.io/integrations/frontend/#manual-language-selection

You can access it via the profile page, it's the very last item in the sidebar (with either initials or an avatar if you set one). Or use this link:

[![Open your Home Assistant instance and show your Home Assistant user's profile.](https://my.home-assistant.io/badges/profile.svg)](https://my.home-assistant.io/redirect/profile/)

The language setting is the very first option/dropdown on that page.

**Comment by copenhaus** [comment]
Everything is shown in a language that I can't read...WHERE IS THAT?

![image](https://user-images.githubusercontent.com/25488700/113345546-77351400-92e7-11eb-96b1-d8c7c3058a10.png)

**Comment by SeanPM5** [comment]
It's the bottom left corner of that screenshot (the part you blurred out). Click that to go to your user profile page and the language dropdown will be at the very top of the page.

<img width="1089" alt="Screen Shot 2021-04-01 at 3 49 29 PM" src="https://user-images.githubusercontent.com/9065557/113346778-49a99400-9302-11eb-868d-b4d3c63d8eb0.png">

**Comment by copenhaus** [comment]
See, now we have a pictorial instruction...thanks...
