### ISSUE TITLE
Integration Options menu - what are the options?

### ISSUE THREAD

**Issue by Back-Man** [home-assistant/home-assistant.github.io#17223]
### Feedback

The options menu lists:
- Allow Hue Groups
and 
- Allow unreachable bulbs to report their state correctly

I can't see any references to the Options menu in the current Docs, I've only discovered them when a recent Hass upgrade triggered a breaking change and I lost the ability to control many, but not all, of my lights via Lovelace. I gather from the following link that it has something to do with non-unique identifiers, but it would be nice to have a more detailed description in the Docs.

The second Option has me totally confused. What does having this unticked (the default) do? Presumably if I am not going to allow a bulb to report its state correctly, then I must be requiring a bulb to sometimes report an incorrect state. Why is this the default and why is it even an option to require a device to report incorrectly? Hopefully I'm miossing something that will make sense once this setting is documented.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2021.3.4

![image](https://user-images.githubusercontent.com/76253069/113298832-f5c19e00-9347-11eb-9a3d-7bbdf2555bf9.png)

**Comment by frenck** [comment]
Thanks for the feedback @Back-Man 👍 

I've added clarification in #17290
