### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by roundel692** [home-assistant/home-assistant.github.io#17221]
### Feedback

Hi, This seems to be just what I'm looking for, but would it be possible to include some installation instructions please? I can't work out what on earth to do to get this running!

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2021.3.4

**Comment by frenck** [comment]
It is here: 

<https://www.home-assistant.io/integrations/evohome/#configuration>


![image](https://user-images.githubusercontent.com/195327/113273075-8febfc80-92dc-11eb-97df-dddbcc0ed155.png)


Add those 3 lines to your `configuration.yaml` file.
