### ISSUE TITLE
Multiple Device Configuration

### ISSUE THREAD

**Issue by lampunderbasket** [home-assistant/home-assistant.github.io#17224]
### Feedback

Can you provide any details on whether the climate platform will function correctly when multiple Venstar thermostats are present on the network? If so, what is the proper format for the configuration entry when multiple thermostats are present?

### URL

https://www.home-assistant.io/integrations/venstar/

### Version

2021.3.4

I have two Venstar thermostats, both model T7850 running firmware VH6.91. They have unique static IP addresses assigned and I  call them out individually in the configuration.yaml file:

# Entry for Main Home Venstar Thermostat
climate:
platform: venstar
    host: 192.168.0.200
    humidifier: false

# Entry for Addition Venstar Thermostat
climate:
platform: venstar
    host: 192.168.0.201
    humidifier: false

Home Assistant only recognizes the second instance, and does not report an entity for the first thermostat. If I delete the second instance, then the first thermostat is recognized.

I am uncertain as to whether my difficulty represents a genuine bug, or simply a need for clarification to the documentation for the configuration file. Please forgive my ignorance if I am reporting this issue to the wrong forum.

**Comment by frenck** [comment]
You can add multiple like so:

```yaml
climate:
  - platform: venstar
    host: IP_OR_HOSTNAME_OF_THERMOSTAT_1
  - platform: venstar
    host: IP_OR_HOSTNAME_OF_THERMOSTAT_2
```

The `-` dashes are YAML lists and indicate multiple.
