### ISSUE TITLE
Home assistant Virtual files dont work why are they .vdi.xz or .vmdk.xz   what is the xz for 

### ISSUE THREAD

**Issue by vjmaz** [home-assistant/home-assistant.github.io#17236]
### Feedback

I am tring to run Home assistant on virtual machine to learn & test on windows 10 using VMware and also Virtual box i also tried ubutu & cloud ready virtaulbox i can not open these virtaul files with the .xz on the end what is going on !!!

### URL

https://www.home-assistant.io/getting-started/

### Version

2021.3.4

I am tring to run Home assistant on virtual machine to learn & test on windows 10 using VMware and also Virtual box i also tried ubutu & cloud ready virtaulbox i can not open these virtaul files with the .xz on the end what is going on !!!

**Comment by vjmaz** [comment]
please email me on vjmaz@hotmail.com so i know what to do

**Comment by chuk-a** [comment]
Open it with zip extracter

**Comment by vjmaz** [comment]
Thank you

**Comment by vjmaz** [comment]
Thank you so much

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
