### ISSUE TITLE
Does not describe how to turn projector on

### ISSUE THREAD

**Issue by joopdo** [home-assistant/home-assistant.github.io#17239]
### Feedback

Thank you for making this integration. Currently, the documentation mentions it can turn on/off the projector. 

For Services, I can only see color mode (select_cmode). Could you please clarify if projector turn on/off can be called as a service?

Thank you!

### URL

https://www.home-assistant.io/integrations/epson/

### Version

2021.3.4

**Comment by pszafer** [comment]
read docs on media player https://www.home-assistant.io/integrations/media_player/

**Comment by joopdo** [comment]
Perfect, thank you for pointing me in the right direction. Much appreciated! Thanks again for creating this service!
