### ISSUE TITLE
Variable set_position_template's description text not shown properly.

### ISSUE THREAD

**Issue by ondrasy** [home-assistant/home-assistant.github.io#17244]
### Feedback

While viewing the page in Firefox 87 or Edge, the description paragraph at the variable set_position_template does not render properly and a core piece of information is missing: It does not render '{{position}}', rather it renders only ''. That has caused a lot of confusion for me until I found help on google and when displayed the source code for the page, it indeed shows '{{position}}'. I don't know why it does not render properly.

### URL

https://www.home-assistant.io/integrations/cover.mqtt/

### Version

current, but can't find the version.

![HA_issue_position](https://user-images.githubusercontent.com/65789790/113461891-caf64900-941e-11eb-9a83-bd8e830c704d.PNG)

**Comment by frenck** [comment]
Thanks for reporting @ondrasy 👍
