### ISSUE TITLE
RFLink doc not really doc

### ISSUE THREAD

**Issue by farmer2b** [home-assistant/home-assistant.github.io#17242]
### Feedback

the page tells me a bit of what but fails to tell me HOW.
example: it tells me that I need to provide a USB path via the port key in the configuration.yaml file
      BUT it does not tell me how I can get the correct path to the right usb device there.
suggest you insert a link here to another doc that tells me how to list the connected usb devices and how to select the correct one and copy it's path to the yaml file.
kind regards,
    Jan

### URL

https://www.home-assistant.io/integrations/rflink/

### Version

2021.3.4

**Comment by frenck** [comment]
There isn't a universal answer to that. Additionally, this documentation is about RFLink, not how to manage your system.
