### ISSUE TITLE
Complete example of stream setup

### ISSUE THREAD

**Issue by markusg1234** [home-assistant/home-assistant.github.io#17246]
### Feedback

Is it possible to include a complete example of a configuration.yaml example that will add a stream-ready camera entity using a rtsp stream.

### URL

https://www.home-assistant.io/integrations/stream/

### Version

2021.3.4

**Comment by frenck** [comment]
The stream integration does not set up camera's. The example on the page is a complete example. There isn't more to configure

**Comment by uvjustin** [comment]
As @frenck mentioned, stream is set up/configured by the camera entities. There are configuration examples under the camera platforms. For example:
https://www.home-assistant.io/integrations/generic#live-stream
https://www.home-assistant.io/integrations/onvif

**Comment by markusg1234** [comment]
Thankyou.
