### ISSUE TITLE
Window visible in the somphy integration

### ISSUE THREAD

**Issue by berryvanesch** [home-assistant/home-assistant.github.io#17253]
### Feedback

I've connected a view covers and one Velux window to my Somfy Connexoon, for integration within home assistent I'm using the default somfy integration.

All the covers are working fine with the home assistant integration, but only the window isn't available in the somf integration. 

It would be nice if windows are also working with the somfy integration.

### URL

https://www.home-assistant.io/integrations/somfy/

### Version

2021.3.4

**Comment by iMicknl** [comment]
@berryvanesch I don't think the documentation repo is the place to report this.

However, this is a known issue of the Somfy integration. The official Somfy API has limited device support and the only way to get all devices in Home Assistant is to use their internal API. You could give [ha-tahoma](https://github.com/imicknl/ha-tahoma) a try, which hopefully should be added to core in the next releases.
