### ISSUE TITLE
Disable Discovery

### ISSUE THREAD

**Issue by spencerthayer** [home-assistant/home-assistant.github.io#17254]
### Feedback

Please include in your documentation how to disable discovery universally.

### URL

https://www.home-assistant.io/integrations/discovery/

### Version

2021.3.4

**Comment by SeanPM5** [comment]
You can just remove `discovery:` from your `configuration.yaml` file to disable that.

However, there are other integrations that discover devices too. You can find them on the [default config](https://www.home-assistant.io/integrations/default_config/) page:

`dhcp:`
`ssdp:`
`zeroconf:`
