### ISSUE TITLE
VM images processor info missing

### ISSUE THREAD

**Issue by Tamadite** [home-assistant/home-assistant.github.io#17257]
### Feedback

There is no information about the processor specification for the images. I tried Vmware Workstation image (.vmdk) on arm and does not work. My wild guess is that those images are for x86 or x86-64 processors.

### URL

https://www.home-assistant.io/installation/linux/

### Version

2021.3.4

I tried .vmdk on Vmware ESXi on ARM Fling 7.0

**Comment by agners** [comment]
Yes, OVA images are x86-64 only. Also they only work with UEFI boot flow. I guess it makes sense to add a note on-top or similar.
