### ISSUE TITLE
Missing Random Sensor

### ISSUE THREAD

**Issue by archeious** [home-assistant/home-assistant.github.io#17255]
### Feedback

The document says it is dependent on the Getting Started section.  I must have missed a step as I cannot find in the Getting Started section where it sets up the sensor.random.

### URL

https://www.home-assistant.io/docs/automation/editor/

### Version

2021.3.4

**Comment by frenck** [comment]
The random sensor is linked in the first paragraph of this page:

<https://www.home-assistant.io/integrations/random#sensor>

That page contains setup instructions for the random sensor.

I agree the line needs rewording. I think it got disconnected from the getting started when it was re-written. Thanks for reporting! 👍
