### ISSUE TITLE
Missing switch documentation

### ISSUE THREAD

**Issue by jrnhrmn** [home-assistant/home-assistant.github.io#17256]
### Feedback

I see that the Harmony integration also creates switches for all activities. It seems like this is missing from the current documentation. Also would like to see what the preferred usage would be to turn on an activity.

### URL

https://www.home-assistant.io/integrations/harmony/

### Version

2021.3.4

**Comment by frenck** [comment]
I am not sure in your feedback. It creates switches, right? So, what would be missing than?

**Comment by jrnhrmn** [comment]
There is no mention of the switches creation or the use of them in the documentation. Maybe I am wrong and it shouldn't be there. But when you use it in automations you can simply use a switch instead of calling a service of the remote with data. This is not mentioned anywhere. 
But if I am completely wrong about what should be in this documentation please tell me :) Noob in that way.

**Comment by frenck** [comment]
> There is no mention of the switches creation or the use of them in the documentation

Every integration can create numerous other standardized entities. For example, lights, fans, climate, media_player, or switch entities (and a lot more).

These all work the same in Home Assistant and not specific to an integration. So a switch can be used the same as any switch in Home Assistant. You can toggle it in the UI, or use the services provided by the `switch` integration in your automations:

<https://www.home-assistant.io/integrations/switch>

**Comment by jrnhrmn** [comment]
Ok, understood. Thank you very much for taking the time to explain.
