### ISSUE TITLE
VM Image HA Supervised 2021.03.06 for VMware ESXi 7.0 on Arm Fling

### ISSUE THREAD

**Issue by Tamadite** [home-assistant/home-assistant.github.io#17258]
### Feedback

I can provide virtual machine image of HA Supervised 2021.03.06 for VMware ESXi 7.0 on Arm Fling. Please advise on how to proceed if relevant. 

### URL

https://www.home-assistant.io/installation/linux/

### Version

2021.3.4

Files to be delivered:
- HA_Supervised_2021_03_06_ESXi7_0_Arm.ovf
- HA_Supervised_2021_03_06_ESXi7_0_Arm.nvram
- HA_Supervised_2021_03_06_ESXi7_0_Arm-0.vmdk
- HA_Supervised_2021_03_06_ESXi7_0_Arm.mf
Total size: 1.68GB

**Comment by agners** [comment]
@Tamadite 
> I can provide virtual machine image of HA Supervised 2021.03.06 for VMware ESXi 7.0 on Arm Fling.

How did you create those images? Just modified/updated binary images are not that useful. 

Currently ova images are for x86-64 only. If we want to add support for Arm, we'll have to add a new machine to the operating system build system to generate ova images which support Arm. If that is what you have, please open a pull request to the https://github.com/home-assistant/operating-system/ repository.
