### ISSUE TITLE
Incorrect Status of HVAC in nexia app

### ISSUE THREAD

**Issue by Nbr1Sniper** [home-assistant/home-assistant.github.io#17262]
### Feedback

Hi,

My thermostat status doesn’t change ever from idle. I have to use another sensor within the entities that are created when I pull in my Nexia account. So I need to have my thermostat controller and a “sensor” tell me if it’s on or off as the sensor changes state but not the thermostat template. 

I’m new to HA so I’m sure it’s probably an easy status fix to a “sensor” but not sure. 

### URL

https://www.home-assistant.io/integrations/nexia/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
