### ISSUE TITLE
Missung WiFi Instructions

### ISSUE THREAD

**Issue by RdTrxx** [home-assistant/home-assistant.github.io#17278]
### Feedback

Hi! Thanks for that graet work!
But I missed a link to the instruction how to setup wifi on an raspberry PI.
I search the net and found it after a while. 
I think it would be great if you ad the link to
https://github.com/home-assistant/operating-system/blob/dev/Documentation/network.md
after the SUGGESTEST HARDWARE and the point
Ethernet cable. Home Assistant can work with Wi-Fi, but an Ethernet connection would be more reliable. (Link to WiFi Setup)

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.3.4

**Comment by frenck** [comment]
> But I missed a link to the instruction how to setup wifi on an raspberry PI.

Correct, we do not recommend using it.

The docs you link are internal docs for the Operating System, not end-user documentation.

If you really want to (but please, you should not), you can set up Wi-Fi via the UI in the Supervisor -> System tab (change network settings).
