### ISSUE TITLE
Connect Home Assistant to WiFi on Pi

### ISSUE THREAD

**Issue by spencerthayer** [home-assistant/home-assistant.github.io#17271]
### Feedback

How does one connect Home Assistant to both the LAN and WiFi? I am having an mDNS issue between WiFi devices and the Home Assistant connected to the LAN. The documentation states that in some cases, "[mDNS traffic may not be forwarded correctly between the wired and wireless interfaces of a Wi-Fi AP or router.](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/discovery.markdown)"   

That sucks. Seems like something that should be fixed. But I figure if I can just get Home Assistant on my WiFi the problem will likely resolve itself.

### URL

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/discovery.markdown

How does one connect Home Assistant to both the LAN and WiFi? I am having an mDNS issue between WiFi devices and the Home Assistant connected to the LAN. The documentation states that in some cases, "[mDNS traffic may not be forwarded correctly between the wired and wireless interfaces of a Wi-Fi AP or router.](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/discovery.markdown)"   

That sucks. Seems like something that should be fixed. But I figure if I can just get Home Assistant on my WiFi the problem will likely resolve itself.

**Comment by frenck** [comment]
> That sucks. Seems like something that should be fixed. But I figure if I can just get Home Assistant on my WiFi the problem will likely resolve itself.

That is a problem for your network, not Home Assistant.

Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by spencerthayer** [comment]
Thanks @frenck, I am aware of this. But how do I connect Home Assistant to the wifi? I can't find documentation for this at all.

**Comment by frenck** [comment]
We don't provide documentation on this, because we do not recommend it.

If you run a Supervisor enabled system, you can configure your Wi-Fi network in the Supervisor.

Supervisor -> Host -> System card. It provides a button to change your network settings.

**Comment by spencerthayer** [comment]
Is it possible to have ETH0 and WLAN0 both connected and broadcasting a DHCP IPv4 at the same time?
