### ISSUE TITLE
remote folders

### ISSUE THREAD

**Issue by keep-flying** [home-assistant/home-assistant.github.io#17279]
### Feedback

remote media folder

### URL

https://www.home-assistant.io/more-info/local-media/setup-media/

### Version

2021.3.4

is it possible to point to a media directory on another device on the same internal network?

**Comment by frenck** [comment]
That all depends on your installation type, used system and other factors. Home Assistant expects a local folder. Where this local folder is coming from is a system administrator thing and considered out of scope for the Home Assistant project.
