### ISSUE TITLE
Cant connect HA TUYU addon !!!

### ISSUE THREAD

**Issue by vjmaz** [home-assistant/home-assistant.github.io#17277]
### Feedback

guys i can connect on the app no probs on many of my devices , but i cant Set up a new integration ! were can i seek more support please 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by vjmaz** [comment]
Thank you Frank
               I will do I am very new to Linxu based systems and ways
