### ISSUE TITLE
Wink Hub no longer supports their API

### ISSUE THREAD

**Issue by jaredpavan** [home-assistant/home-assistant.github.io#17286]
### Feedback

If you navigate to https://developer.wink.com you can see that the site is down. I contacted Wink support and received this message: "Thanks for contacting Wink support. Unfortunately, the Wink API site is not available currently. We are not accepting any new applications to use the Wink API at this time. If you were in the past issued a Client ID and Secret, then you can continue to use them as any existing API applications will still function. However, we are not able to help you submit a new application to use the API or obtain new tokens, or a new set of Client ID and Secret."

Could this be removed from the Z-Wave controllers page?

### URL

https://www.home-assistant.io/docs/z-wave/controllers/

### Version

2021.3.4

**Comment by frenck** [comment]
I think this is a bigger problem for:

<https://www.home-assistant.io/integrations/wink>

**Comment by jaredpavan** [comment]
Oh yeah you're absolutely right. I bought a Wink Hub because of this guide. Not sure what else I could have done other than go through a dry run of all of the steps before I got the hub.
