### ISSUE TITLE
Incorrect instructions

### ISSUE THREAD

**Issue by MSJocke** [home-assistant/home-assistant.github.io#17281]
### Feedback

The instructions for integrating the Google Assistant to Home Assitant are way out of date. Half the things described on the instructions do not match anymore. Please update!

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2021.3.4

**Comment by frenck** [comment]
Feel free to provide updated instructions 👍

**Comment by MSJocke** [comment]
Hi,

I solved the issue by simply subscribing to Nabu Casa – much simpler!

Best regards
Jock

**Comment by red-yfronts** [comment]
Why thank you Franck, for your quick action.

However, this problem is not closed. 

All the "solutions" are for fee based services and not really solutions at all.

So again, when will these instructions be updated to reflect the changes in google actions?

**Comment by frenck** [comment]
@red-yfronts I didn't "close" the problem. I closed your duplicate issue. This issue is still open.
