### ISSUE TITLE
the command to change to a virtual environment for Home Assistant Core is wrong

### ISSUE THREAD

**Issue by cavico** [home-assistant/home-assistant.github.io#17297]
### Feedback

This command is not working:
```
python3.8 -m venv .
```

It needs to be changed to:
```
python3 -m venv .
```
to work

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.3.4

**Comment by cavico** [comment]
Actualy, after install python3 ive noticed that python3 is no longer supported, so the wrong command is on the Install the dependencies section.
```
sudo apt-get install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5
```
ive changed to:
```
sudo apt-get install -y python3.8 python3.8-dev python3.8-venv python3.8-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5
```
and worked

**Comment by frenck** [comment]
This depends on your system, virtual environment, and way of working.

This is considered an advanced installation method, and we assume you are able to adapt it to your environment. If you are not familiar with Python virtual environment, we do not recommend using this installation method.
