### ISSUE TITLE
Show Luftdaten pressure in hPa

### ISSUE THREAD

**Issue by tuxick** [home-assistant/home-assistant.github.io#17296]
### Feedback

Since most other sensors show pressure in hPa the only way i found to fix the data from Luftdaten to hPa is a value_template:

sensor:
  - platform: template
    sensors:
      luft_pressure:
        unit_of_measurement: 'hPa'
        value_template: "{{ states('sensor.luftdaten_XXXXX_pressure')|float/1000 }}"

### URL

https://www.home-assistant.io/integrations/luftdaten/

### Version

2021.3.4

``

**Comment by frenck** [comment]
That is nice @tuxick 👍 

But unit conversions are a general thing, as not specific to this integration. Nevertheless, thank for taking the time to provide feedback on this page! ❤️

**Comment by tuxick** [comment]
Well, in many cases you can set unit_of_measurement in configuration.yaml or in integration's config dialog. Since this doesn't seem to be the case for this integration i thought extra example could be helpful.
