### ISSUE TITLE
If you could expand to include examples for min and max

### ISSUE THREAD

**Issue by wreuvers** [home-assistant/home-assistant.github.io#17309]
### Feedback

I am new to Home Assitant (and loving it). Templates have proved very useful, but I am struggling with the basic syntax. Examples would be a huge help. I want to do something as simple as create a Excess Solar that will be the max(0, states("sensor.net_solar_production")) - but I cannot for the life of me figure it out :)

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2021.3.4

**Comment by frenck** [comment]
Prepared a small change for the docs to clarify it.

Example use:

`{{ [1, 2, 3] | max }}` -> `3`
`{{ [1, 2, 3] | min }}` -> `1`

Thanks for the feedback! 👍
