### ISSUE TITLE
Naming of Device and Entities is more advanced (better) than described on this page.

### ISSUE THREAD

**Issue by filmgarage** [home-assistant/home-assistant.github.io#17301]
### Feedback

The way this integration handles Shelly names is excellent. The Entities are named like described on this page, but the Device name is also set in HA if set on the local Shelly. All Shellies have the option to set a Device name and a Channel name. Device Name gets set to the HA Device, and Channel name gets set to the Entity Name. Works flawless! Thanks! It would be good if this gets mentioned on this page too so people can make use of it.

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.3.4

**Comment by frenck** [comment]
> Device Name gets set to the HA Device, and Channel name gets set to the Entity Name.

That is how Home Assistant in general works. It should (if possible) adopt the name set on the device, unless overridden in Home Assistant. This is not specific to this integration, many more integrations do this and its core functionality.

**Comment by filmgarage** [comment]
Nevertheless it is a very cool feature! And it saved me a lots of time... Thanks! :-)
