### ISSUE TITLE
state or states?

### ISSUE THREAD

**Issue by gabrielke** [home-assistant/home-assistant.github.io#17311]
### Feedback

Here: 
states.sensor.livingroom.attributes["Battery numeric"].

is it states or state (a typo) there?
States as collection is not explained on the page.

### URL

https://www.home-assistant.io/docs/configuration/state_object/

### Version

2021.3.4

**Comment by ludeeus** [comment]
It's both :) 

In the context on that page where `state` is used, it's a representation of the State object for instance `sensor.livingroom`
To get a single state attribute of a state object, you use `states.sensor.livingroom.attributes["Battery numeric"]` or the more prefered way `state_attr('sensor.livingroom', 'Battery numeric')`

**Comment by frenck** [comment]
This page is correct at this point. The example given is indeed bad practice, I've opened a PR to adjust that example: #17385 

Closing this feedback at this point. If you have additional feedback, please lets us know.
