### ISSUE TITLE
yale_smart_alarm update

### ISSUE THREAD

**Issue by Mr-Grover** [home-assistant/home-assistant.github.io#17313]
### Feedback

Hello,
The Yale app has gone untouched for awhile now.  The yale smart alarm client is on 0.3.1 and Home Assistant is still using 0.1.6. 

0.1.6 added support for lock status but the integration itself was never updated to use it. 0.3.1 has gone even further now and added the abilities to lock and unlock the door now. For awhile now I been using a custom component based off of 0.1.6  to grab the lock status but I am not much of a dev so it was poorly written. 
  
Is there any chance we can get Home Assistant on the latest version of the python client ? In truth this app needs a bit of work as it's not even on the integrations page. It would be nice if we kept yale_smart_alarm around and created a new integration called Yale Smart Sync which falls more inline with the current Yale products then just deprecated  yale_smart_alarm to avoid breaking changes.

Happy to help where I can but my skills are a bit limited. I can at least test as I have the hardware both alarm and lock 

Thanks so much for your time

pip page
https://pypi.org/project/yalesmartalarmclient/0.3.1/

### URL

https://www.home-assistant.io/integrations/yale_smart_alarm/

### Version

2021.3.4

**Comment by frenck** [comment]
Hi there @Mr-Grover 👋 

It seems like you have a feature request. Please use the Home Assistant community forums for those. This is for documentation feedback, and there is no amount of documentation I can just to make happen what you described in this issue.

Thanks!

../Frenck
