### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by lankylad9** [home-assistant/home-assistant.github.io#17316]
### Feedback

My Volvo knows what the outside temperature is (Volvo On Call App), but this isn't available in Homeassistant?

### URL

https://www.home-assistant.io/integrations/volvooncall/

### Version

2021.3.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests. It might be possible to add it, but... that is a feature :)

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
