### ISSUE TITLE
Enable Analytics - not accessible on the General Configuration screen

### ISSUE THREAD

**Issue by genem2** [home-assistant/home-assistant.github.io#17325]
### Feedback

As stated in the doc, I'm not finding any evidence of the integration on my Configuration >> General screen. Would that be because: Editor disabled because config stored in configuration.yaml.

### URL

https://www.home-assistant.io/integrations/analytics/

### Version

2021.4.0

**Comment by SeanPM5** [comment]
One possible cause for those being missing is that you need to be logged in to the "owner" account to see those settings. You can verify if you're an owner on the profile page:

![image](https://i.imgur.com/N7cLFzV.png)

Or at Configuration -> Users.

**Comment by genem2** [comment]
Owner. That's a new one on me.
I'm an administrator. I'm reading:

https://www.home-assistant.io/docs/authentication/

that introduces Owner, but maybe my installation (user) was created before this time? I was never prompted like that page suggests (first time the owner user account is created).  If Owner, rather than Administrator is the reason, I need to figure out how to change my user accounts.

**Comment by ludeeus** [comment]
For now you need to be owner to enable analytics, that will change in the next patch release to administrator instead.
