### ISSUE TITLE
Power Sockets appear as lights!

### ISSUE THREAD

**Issue by ericxls1978** [home-assistant/home-assistant.github.io#17328]
### Feedback

Have a bunch of Philips Hue power sockets but these appear under domain lights.xxxx when it should be switch.xxxx.  

Searched quite a bit how to convert these from "lights" into switches -but no luck.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2021.4.0

**Comment by frenck** [comment]
Hi there @ericxls1978,

Thanks for providing documentation feedback, however, it seems like you are trying to report an issue with integration.

If you want to report an issue with an integration, please, do so here:

<https://github.com/home-assistant/core/issues>

Thanks already 👍
