### ISSUE TITLE
Different app

### ISSUE THREAD

**Issue by JakubAnderwald** [home-assistant/home-assistant.github.io#17322]
### Feedback

Hi, I'm using "Broadlink" app fro my RM4C mini, not e-Control as mentioned in the article. The app I'm using doesn't have "share" option so I can't transfer the learned codes to Home Assistant. It would be great to provide manual for this app as well.

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2021.4.0

**Comment by JakubAnderwald** [comment]
Hi, this issue is still there. Luckily I was able to find a command set for my air conditioning unit in the integration so I didn't have the need to read codes from the app, but for any other device I would still be missing this function.

**Comment by JakubAnderwald** [comment]
Hello, the issue is still valid. I don't know if I can contribute somehow to solving it?

**Comment by felipediel** [comment]
Hi. For now there is no easy way to extract the codes. Many people do it by sniffing the communication between the app and device. It's not interesting to have this in the documentation.

It would be nice to connect to the cloud API with the user account and download the codes in an easy way, but this still needs to be developed by smart, nonconforming people with available time. A possible walk-through would be:

- Sniff the communication between the app and the cloud.
- Identify the commands we need: authenticate, list devices, get codes for device.
- Make Python functions to send these requests. Add them to the python-broadlink API.

In the Broadlink integration:
- Import these functions, add a step to link to the cloud in the config flow.
- Create an update method to fetch codes from the cloud.
- Adapt the entry setup to create entities for the subdevices downloaded from the cloud.

That's it. I won't do it btw. Have a good one! 😄
