### ISSUE TITLE
Redirect URL & First Reply Url

### ISSUE THREAD

**Issue by yashijoe** [home-assistant/home-assistant.github.io#17337]
### Feedback

I've no idea what to put in the Redirect URL & First Reply Url fields on the Legrand application page
Both of them are mandatory

thanks

### URL

https://www.home-assistant.io/integrations/home_plus_control/

### Version

2021.4.0

**Comment by frenck** [comment]
Sorry for the ping, @chemaaa, normally the bot will send you a message. Unfortunately, the bot messed up for this issue 😅

Since you are the code owner for this integration, could you be so kind to clarify the URLs that need to be used in this case?

**Comment by yashijoe** [comment]
This is the reply I got from chemaaa on his GitHub:


Hi @yashijoe ,

Are you referring to the "New Application" form in the Legrand Developer website? If so, here you have some more information about how that should be filled in: https://developer.legrand.com/tutorials/create-an-application/

Basically, you have to fill in a "Url" which is just an informative URL about the application. If this is for Home Assistant integration, I don't think it is of much relevance.

The more important URL is the "First Reply Url"... that one is the Redirect URI for the OAuth2 authentication flow. This should be filled in with the URL of your application. Again, if this is for Home Assistant integration, you should enter the URL that you use to access your HA instance, for example: https://my-ha-ip-address:8123

Let me know if this clarifies.

Regards.
