### ISSUE TITLE
Update to core-2021.4.0 seems to break this integration

### ISSUE THREAD

**Issue by KevinDAdam** [home-assistant/home-assistant.github.io#17339]
### Feedback

Hi,
Just upgraded to core-2021.4.0 and this seems to have broken the speediest integration. (edited - **SpeedTest** integration! Flipin autocorrect! :)
When clicking on options for the integration, I get the error message:
------------------
Error
Config flow could not be loaded
------------------

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2021.4.0

**Comment by robertboccia** [comment]
same issue, but i have not upgraded to 2021.4 as yet

**Comment by enricodx** [comment]
Same here...

WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: speedtestdotnet

**Comment by frenck** [comment]
Hi there @KevinDAdam!

Thanks for providing feedback on our documentation, but there is no amount of documentation I can adjust to fix an issue with the integration code.

If you want to report issues with an integration, please go here:

<https://github.com/home-assistant/core/issues>

In cases you don't know where to go with an issue, or anything else, check:

<https://www.home-assistant.io/help>

Thanks 👍
