### ISSUE TITLE
"zeroconf default interface" is unclear

### ISSUE THREAD

**Issue by evadim** [home-assistant/home-assistant.github.io#17331]
### Feedback

I read in release post about Zeroconf integration changes. In docs I see following statement:
`By default, zeroconf will broadcast on the default interface.`

And right here I have question - which of my 11 interfaces considered as default one? I see no info in logs and short search docs/internet not give me any idea.

It would be great if docs page provide a way to determine how to find "default interface".
Personally, I still have no answer to this question.

### URL

https://www.home-assistant.io/integrations/zeroconf/

### Version

2021.4.0

**Comment by frenck** [comment]
The interface holding the default route.

**Comment by evadim** [comment]
Thanks for the explanation. I think this is nice to have documented.

From my point of view this is good if HA deployed on standalone hardware. In my case it installed on home router/firewall/file server/etc and default route have PPPoE interface from internet provider, and LAN reside on different interface, heh.

Is it possible to set this interface somehow?

**Comment by frenck** [comment]
Yes, as documented: <https://www.home-assistant.io/integrations/zeroconf/#default_interface>

**Comment by evadim** [comment]
Document does not provide a way to set default interface, only option to enable all of them. But this is way to go in this case.

P.S. Looks like this thing tell me why in my setup different HA links for LAN and WAN access not work and it always show WAN link.

Thanks for explanation and help.
