### ISSUE TITLE
https://analytics.home-assistant.io not all graphs are updated

### ISSUE THREAD

**Issue by rkitzman** [home-assistant/home-assistant.github.io#17344]
### Feedback

https://analytics.home-assistant.io/#installations has 3 panels of graphs, line, pie and geographic.

the pie and geographic charts are not updating.

### URL

https://www.home-assistant.io/integrations/analytics/

### Version

2021.4.0

**Comment by ludeeus** [comment]
This is a known issue and stated at the top of the page <https://analytics.home-assistant.io/>

> We are currently experiencing issues handling the amount of data, because of that only the active installations graph is being updated.
