### ISSUE TITLE
Amazon Polly documentation contains invalid variable

### ISSUE THREAD

**Issue by stegmannb** [home-assistant/home-assistant.github.io#17345]
### Feedback

The documentation talks about the variable `name`, but that variable causes an error during validation.

I could not find any usage of that config variable in the code.
I assume that variable was replaced by [service_name](https://www.home-assistant.io/integrations/tts/#service_name).

### URL

https://www.home-assistant.io/integrations/amazon_polly/

### Version

2021.4.0

**Comment by stegmannb** [comment]
I created a [pull request](https://github.com/home-assistant/home-assistant.io/pull/17346) to simply remove the variable from the list.

**Comment by frenck** [comment]
You don't have to create issues for pull requests...

**Comment by stegmannb** [comment]
Sorry, I did not know that. I'm still new to this...

So I'm closing this issue and leaving the pull request open.

**Comment by frenck** [comment]
> Sorry, I did not know that. I'm still new to this...

Don't worry 👍
