### ISSUE TITLE
How to remove a dead node?

### ISSUE THREAD

**Issue by caylor93** [home-assistant/home-assistant.github.io#17347]
### Feedback

Doesn't seem to have a way to remove a dead node / device.  Is there any way to do that?

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2021.4.0

**Comment by frenck** [comment]
You can't, its on the upstream roadmap, see: <https://github.com/home-assistant-libs/zwave-js-server-python/issues/56>
