### ISSUE TITLE
Saddle Case

### ISSUE THREAD

**Issue by cdn4lf** [home-assistant/home-assistant.github.io#17349]
### Feedback

Is it possible to update the documentation to reflect that the entity_id should not include saddle case?

It isn't indicated in the documentation here, but does result in an invalid config error.

### URL

https://www.home-assistant.io/integrations/input_number/

### Version

2021.4.0

**Comment by balloob** [comment]
Saddle case?

**Comment by emontnemery** [comment]
Maybe it's auto correct version of "snake_case" ? :)

**Comment by emontnemery** [comment]
@cdn4lf can you explain your problem a bit further? Configuration of `input_number` takes existing `entity_id` as inputs, and those need to be correctly spelled.

**Comment by frenck** [comment]
It is the dictionary item keys he is referring to, for which the rules of a valid entity ID apply.

**Comment by emontnemery** [comment]
Oh, I see. That's a general comment for all integrations where entities are specified as a dictionary rather than a list then, and I agree it's not clear from the documentation there are any restrictions on the keys.

We should maybe do something like:
```diff
 input_number map REQUIRED
-Alias for the input. Multiple entries are allowed.
+`entity_id` of the input. Multiple entries are allowed. Rules for `entity_id` naming applies, see #<link>.
```

**Comment by cdn4lf** [comment]
I tried to go 
`input_number:
  accesscount_FrontDoor_Code1:
    name: Access Count
    min: 0
    max: 100`

HA didn't accept it and kept throwing an invalid config until I changed it `accesscount_frontdoor_code1`   

Apologies I don't know how to  format the larger code block but the yaml was correct.

**Comment by emontnemery** [comment]
Thanks @cdn4lf for clarifying 👍

**Comment by cdn4lf** [comment]
No problem.  I assume this comment goes for all of the other inputs.  It may be worth updating some of the other documents (input_text), etc.
