### ISSUE TITLE
Reference to reevaluation details not found

### ISSUE THREAD

**Issue by dc31xx** [home-assistant/home-assistant.github.io#17352]
### Feedback

Regarding:

> The ways to force template reevaluation are documented in the template binary_sensor.

If I click on the binary_sensor link and <kbd>Cmd</kbd>+<kbd>F</kbd> the word `reevaluation` I end up with nothing. 

Call me lazy, but I think this is how many people search for help :-)

Btw, thank you for all the work you put into this 👍 

### URL

https://www.home-assistant.io/integrations/bayesian/

### Version

2021.4.1

**Comment by frenck** [comment]
That is correct! That has been removed and isn't needed anymore. 

This is a reference that is leftover that needs to be cleaned up. Thanks for the feedback!

**Comment by dc31xx** [comment]
Thank you for the quick response!
