### ISSUE TITLE
iCloud Integration 

### ISSUE THREAD

**Issue by hamdanfadi** [home-assistant/home-assistant.github.io#17351]
### Feedback

The new update core-2021.4.0 cause iCloud integration to stop. I have revert to an old snapshot all working fine. May I know when are you going to fix this issue?

Cheers,

Fadi

### URL

https://home-assistant.io

### Version

core-2021.4.0

**Comment by SeanPM5** [comment]
This was fixed in https://github.com/home-assistant/core/pull/48815 which was included in core-2021.4.1 (just released about an hour ago). So if you update your Home Assistant it should be working again.

**Comment by hamdanfadi** [comment]
There is another issue with ZHA all devices become offline!

**Comment by SeanPM5** [comment]
This `home-assistant.io` repository is intended for issues with the website/documentation only, not integrations. You can create an issue on the "core" repo here for any ZHA issues that you're experiencing: https://github.com/home-assistant/core/issues/new/choose

Thanks.
