### ISSUE TITLE
Not integrating properly

### ISSUE THREAD

**Issue by treforparr** [home-assistant/home-assistant.github.io#17372]
### Feedback

Not working properly keep getting aborted won't integrate properly

### URL

https://www.home-assistant.io/integrations/hive/

### Version

2021.4.2

**Comment by KJonline** [comment]
This needs closing as it’s raised in the wrong repo. This has already been raised in core repo and a PR had been merged to address the issue

**Comment by treforparr** [comment]
What do you mean sorry

**Comment by treforparr** [comment]
Will this be fixed in the next update because I still can’t gain access to hIve

**Comment by KJonline** [comment]
This will be fixed in 2021.5
