### ISSUE TITLE
Shelly Button1 _ Push Count and Push Type

### ISSUE THREAD

**Issue by runwaygoats** [home-assistant/home-assistant.github.io#17389]
### Feedback

Shelly Button1 exposes the following data through MQTT

Battery

> Battery Percentage

Push Count

> Integer that increases by 1 with every push count

Push Type

> S for one short press, SS for double short press, SSS for triple short press, L for long press

But with Home Assistant native Shelly integration, only Battery sensor is created.

<img width="317" alt="Screen Shot 2021-04-10 at 11 17 37 AM" src="https://user-images.githubusercontent.com/68604297/114274886-6c1c6b00-99ee-11eb-92f2-6d675dd81338.png">

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.4.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
