### ISSUE TITLE
repeat_set documentation is unclear

### ISSUE THREAD

**Issue by skipishere** [home-assistant/home-assistant.github.io#17391]
### Feedback

From trying this out myself (and from finding a post on the forum) it appears that the repeat_set method doesn't work for all speakers/media sources. If this is the case, a list of those that support (or those that don't) would be of benefit to help reduce people going crazy trying to figure out why it's not working

### URL

https://www.home-assistant.io/integrations/media_player/

### Version

2021.4.3

**Comment by frenck** [comment]
We don't know which ones support it from this page. Please consult the page of the integration you are using for that information.

This is a base entity, that other (custom) integration can build upon. What they implement is not a concern for this page and should be documented for that specific integration.

Nevertheless, thank you for providing feedback 👍

**Comment by skipishere** [comment]
For other segments it says what ones are supported

> Service media_player.shuffle_set
> Currently only supported on Sonos, Spotify, MPD, Kodi, Roon, Squeezebox and Universal.

and

> Service media_player.select_sound_mode
> Currently only supported on Denon AVR and Songpal.

I don't know what ones support Repeat, otherwise I'd be happy to add in that it's not supported by the media player that HA uses (which is a shame, I'd have thought it would be one of the ones that did given it's baked into HA)
