### ISSUE TITLE
Home Assistant user realm

### ISSUE THREAD

**Issue by Quotacious** [home-assistant/home-assistant.github.io#17392]
### Feedback

The later section showing you how to setup a user in Proxmox VE are great, however, I kept getting an authentication failed message.

It fails because the configuration would need an additional line in this case:

    realm: pve

e.g.:
    username: homeassistant
    password: !secret proxmox_password
    realm: pve

Otherwise, Home Assistant tries to login using PAM, and the user created with those instructions is only a PVE account, so the login fails.

### URL

https://www.home-assistant.io/integrations/proxmoxve/

### Version

2021.4.3

**Comment by Quotacious** [comment]
This one is a bit more confusing because the configuration example does not include the realm parameter as a hint...

**Comment by frenck** [comment]
The `real` is an optional parameter and thus not part of the initial example. This is correctly documented and complies with our documentation standards.

The additional example provide it, and also this section states:

> If you use the pve realm, just be sure to add realm: pve to your configuration.

<https://www.home-assistant.io/integrations/proxmoxve/#create-home-assistant-user>


I'm not sure how this could be documented it any better, to be honest 🤷‍♂️

**Comment by jhollowe** [comment]
You can also include the realm in the username e.g. `username@realm` so you don't even have to set the separate config.

This feature could probably be better described in the documentation, but this *is* how PVE (and the proxmoxer library used for this integration) actually handle the username and realm. The separate realm config option is really just a nicety.

**Comment by Quotacious** [comment]
> The additional example provide it, and also this section states:
> > If you use the pve realm, just be sure to add realm: pve to your configuration.

Ouch. It turns out I completely ignored that paragraph and went straight to the steps. My mistake. 
 
> I'm not sure how this could be documented it any better, to be honest 🤷‍♂️

Well, I guess you could make it more idiot proof. 🤣  The problem with hand-holding sets of instructions is that we sometimes turn our brain off. I literally did not read that paragraph. (#excuses). 

It could be better if there was an another config at the bottom, indicating the need for the realm, or as @jhollowe jhollowe noted, just add a step 10: _In your configuration, make sure to use a user of homeassistant@pve.

Thanks and sorry for the trouble. 
...Donovan

**Comment by frenck** [comment]
Merged the PR above and with that, I'll declare this issue closed!

Thanks for the feedback, as it still caused an improvement to our documentation 👍
