### ISSUE TITLE
devices show unaccessible in home assistant after reboot of lamp

### ISSUE THREAD

**Issue by skynet-network** [home-assistant/home-assistant.github.io#17409]
### Feedback

devices show unaccessible in home assistant after reboot of lamp

I am seeing and can control the device in the akasa  app.

It has a fixed ip

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.4.3

**Comment by SeanPM5** [comment]
For issues with integrations please [create a bug report](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml&title=) on the "core" repository instead. This one is just for website/documentation issues.

Thanks.
