### ISSUE TITLE
How to install Home assistant analytics

### ISSUE THREAD

**Issue by alexkoel1958** [home-assistant/home-assistant.github.io#17403]
### Feedback

Analytics seems to be great. Perhaps I'm a fool, but how to install? I can't find anything about it. I'm not a super user, but sometimes I'm wondering why something didn't work. So I want to be able to use it. Core is 2021.4.2

### URL

https://www.home-assistant.io/integrations/analytics/

### Version

2021.4.2

**Comment by frenck** [comment]
You don't have to install it, it is just there 😄 

You can opt-in on the general settings page:

[![Open your Home Assistant instance and show your general Home Assistant settings.](https://my.home-assistant.io/badges/general.svg)](https://my.home-assistant.io/redirect/general/)
