### ISSUE TITLE
Documentation needs to include a section on unzipping/unarchiving as it is not a native function

### ISSUE THREAD

**Issue by Jacksonbm1** [home-assistant/home-assistant.github.io#17416]
### Feedback

I'm using an early 2011 macbook pro and I following the instructions on the website will not work. When downloading the virutalbox vid file, you can't actually import it into virtual box. You must first uncompress it with a third party app like TheUnarchiver. I suspect that on newer macs, it's built in, but on older macs (and I'm guessing a lot of people using macs for this are using older macs) can't do this. I'm not sure if I'm allowed to edit documentation, but if you want me to, I'm happy to edit it.

### URL

https://www.home-assistant.io/installation/macos/

### Version

2021.4.3

**Comment by frenck** [comment]
Discussed this with the team, and we agree. While .xz is a widely used format, it isn't that well known to the public and not natively supported on all platforms.

We are changing the way we distribute the images soon, using well-known methods.

For reference: <https://github.com/home-assistant/operating-system/pull/1327>

Thanks for your feedback 👍
