### ISSUE TITLE
add option for issues

### ISSUE THREAD

**Issue by Brtrnd** [home-assistant/home-assistant.github.io#17427]
### Feedback

see https://github.com/home-assistant/core/issues/24750
I had the same issue as described in the link above. I had searched for it on the documentation and couldnt' find it.
So I think it would be a good addition: 
"unable to connect to home assistant"
If you can open the login screen, but get this issue, make sure websockets are enabled

### URL

https://www.home-assistant.io/docs/authentication/

### Version

2021.4.3

**Comment by frenck** [comment]
This is not related to authentication. Home Assistant also doesn't provide guides on how to set up reverse proxies. We did in the past, but got too many guides and many became unmaintained or had multiple variants for all the use cases available.

As we consider it an advanced use case and out of scope for the Home Assistant project itself, we have removed all those guides quite a while ago. The Community Guides section on the forums now provides multiple guides provided by community members on how to configure it in different ways.

Nevertheless, thank you for your feedback, that is always appreciated 👍
