### ISSUE TITLE
MQTT configuratiom

### ISSUE THREAD

**Issue by oldfart101** [home-assistant/home-assistant.github.io#17425]
### Feedback

The documentation for MQTT is incorrect
it says:
Create a new user for MQTT via the Configuration -> Users (manage users)

there is no such entry in the menu system

also
configuration - MQTT - configure
MQTT settings - re-configure MQTT
no information about these settings in the documentation

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2021.4.3

**Comment by frenck** [comment]
I cannot find any occurrence of that on the page you gave feedback on, I searched for "Create a new user for MQTT via the Configuration".

Was it a different page maybe?

**Comment by azrael783** [comment]
He his addressing the documentation of the MQTT addon of hassos. And I guess he doesn't now that all users of Home-Assistant are also available for the MQTT addon. Sometimes it helps reading the whole document.

**Comment by frenck** [comment]
Ok, if that document need changing, please file an issue or PR on the add-on repository 👍
