### ISSUE TITLE
Is "json_attributes" deprecated/removed??

### ISSUE THREAD

**Issue by Danieldiazi** [home-assistant/home-assistant.github.io#17421]
### Feedback

Hi, I'm reading about  "json_attributes" but at https://community.home-assistant.io/t/solved-how-to-use-json-attributes-e-g-mqtt-sensor/40790/28 I can see a answer saying: "WARNING json_attributes is no longer deprecated; it has been REMOVED"

I don't know if "json_attributes" works at this moment and therefore the documentacion is ok, or maybe "json_attributes"  has removed.....

Thanks in advance!

### URL

https://www.home-assistant.io/integrations/sensor.rest/

### Version

2021.4.3

**Comment by frenck** [comment]
The topic you link is about MQTT. This documentation feedback is given on the REST sensor.
Those are not the same things. Could you please clarify?

**Comment by Danieldiazi** [comment]
> The topic you link is about MQTT. This documentation feedback is given on the REST sensor.
> Those are not the same things. Could you please clarify?

Hello! you're right, it's a mistake, I tried to use "json_atributtes" for the "rest" platform without success and I was confused reading similar post but about MQTT, sorry for the inconvenience

**Comment by frenck** [comment]
No problem! Glad we got it figured out 😄
