### ISSUE TITLE
How to integrate your Niko Home Control into Home Assistant?

### ISSUE THREAD

**Issue by Kaximat** [home-assistant/home-assistant.github.io#17428]
### Feedback

I have a wireless smart hub for Niko Home Control. Type 552-00001.
I have connected switches and electrical outlets on this hub. I want to integrate them in home assistant.
How do i start?
Is the integration even posible? 
On "https://www.home-assistant.io/integrations/niko_home_control/" they say it is.
Thats the reason i started with home assistant. But I don't get very far with it yet.
Is it possible to program/integrate this as a beginner?
Does anyone have experience with this?

Thank you

### URL

https://www.home-assistant.io/integrations/niko_home_control/

### Version

2021.4.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
