### ISSUE TITLE
Rename CLA to DCO

### ISSUE THREAD

**Issue by rigrig** [home-assistant/home-assistant.github.io#17436]
### Feedback

The text of the Contributor License Agreement was [changed](https://github.com/home-assistant/home-assistant.io/commit/ed7ff529af63ba05535a83994251c6150ca28777#diff-390ad7c33679ebd00f1d7e9fff62821a796bab29e912a816ee4e48cfc1a7249f) to a Developer Certificate of Origin, but the page still calls it a CLA, even though it explicitly mentions it is now based on the Linux DCO.
There is quite a significant difference between signing away your copyright vs. attesting that you can and want to license your contribution under the Apache 2.0 license (which is why I imagine the text was changed in the first place), so I think it would be better if the page title was "Developer Certificate of Origin". Especially as some contributors might be turned away just by the term CLA before closely examining the actual text.

### URL

https://www.home-assistant.io/developers/cla/

### Version

2021.4.4

**Comment by frenck** [comment]
Yeah that might be correct, I do however, think that changing that process/title is not worth the squeeze.

> Especially as some contributors might be turned away just by the term CLA before closely examining the actual text.

I do not agree; I've personally not seen any occurrences, feedback, comments, or other references in the past years to justify that statement.

**Comment by rigrig** [comment]
Simply changing the text without moving pages around seems like an improvement to me, but I agree it's probably not worth the effort to also change URLs and Github processes.
