### ISSUE TITLE
Coinbase Integration not working - Authentication error

### ISSUE THREAD

**Issue by Tokn59** [home-assistant/home-assistant.github.io#17435]
### Feedback

Hi, I tried to implement the Coinbase integration. Providee API Key and Secret in configuration.yaml. Starting HA (latest build and core) I get the following error:

Logger: homeassistant.components.coinbase
Source: components/coinbase/__init__.py:96
Integration: coinbase (documentation, issues)
First occurred: 10:53:11 AM (1 occurrences)
Last logged: 10:53:11 AM

Authentication error connecting to coinbase: APIError(id=authentication_error): API Key disabled

Keys are correct and active.

Config used: 

coinbase:
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxx
  api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  account_balance_currencies:
    - EUR
    - BTC
    - LTC
  exchange_rate_currencies:
    - BTC
    - ETH
    - LTC 

Thanks for helping me solve this issue !

### URL

https://www.home-assistant.io/integrations/coinbase/

### Version

2021.4.4

**Comment by frenck** [comment]
Hi there @Tokn59!

Thank you for providing documentation feedback, however, it seems like you are trying to report a bug for an integration. If you want to report a bug; please create an issue in the core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks 👍
