### ISSUE TITLE
Additional information on setting the sensor attributes

### ISSUE THREAD

**Issue by parautenbach** [home-assistant/home-assistant.github.io#17443]
### Feedback

The page states that it's possible to "populate a sensor state (and attributes)" but no examples are given. I've had a look at the code and it seems that besides the state getting set according to `column`, that all other columns from the query will become attributes with their corresponding values. 

Just to explain how I picked this up: My actual use case is to have a SQL sensor with a state and then more queries to set attributes. More specifically, I want to monitor my HA DB size and then e.g. have an attribute to say how large the `events` and `states` tables are. I understand that the current implementation doesn't allow for this and that this would be a feature request. I also know I can create individual sensors for this and then combine them with a template sensor as described. This probably never needs to be implemented (so I'm not going to log this as a feature request). It doesn't seem worth the extra complexity of the integration. 

(And an example for `value_template` would be nice too. I wasn't able to quickly think of one.)

### URL

https://www.home-assistant.io/integrations/sql/

### Version

2021.4.4

**Comment by dgomes** [comment]
Well you clearly described everything 😄 Can't add anything to all you described. This is indeed the situation and those are the possibilities. 

All is correct and since this would indeed be a feature request (and this is not the place for feature requests) I think we should close it.

**Comment by parautenbach** [comment]
I'm glad my analysis is accurate. Thanks for the feedback. 

I think the main issue is still as in my first paragraph (the rest was just to colour the issue): I couldn't understand from the docs what I will get as state attributes without reading the code (which every user will not be able to do). I think if the docs can just state that additional columns returned by the query will be set as attributes – and that only row one gets used – it should be perfect.

**Comment by dgomes** [comment]
We welcome contributions to the documentation :) 

The here a link at the bottom of the page you can use to submit changes/additions

**Comment by parautenbach** [comment]
Ok, let me check again... I thought that's what I did and then ended up here.
