### ISSUE TITLE
How does hs_color relate to HSL?

### ISSUE THREAD

**Issue by tggman** [home-assistant/home-assistant.github.io#17442]
### Feedback

hs_color is defined as "...two floats representing the hue (0-360°) and saturation (0-100%)".  I understand it's supposed to represent hue/saturation but I don't understand how it relates to the "standard" HSL (hue, saturation, lightness)

### URL

https://www.home-assistant.io/integrations/light/

### Version

2021.4.4

**Comment by frenck** [comment]
I think the best comparison is this website: 

http://colorizer.org/

It allows you to see the difference between HSL and HS(B) pretty well.

**Comment by tggman** [comment]
I've been there and played with it before I opened this issue. That tool does NOT answer my question and honestly, I'm by no means a light expert, but if its not clear to me (an engineer) its probably not clear in general?

By the way, this is why I'm asking:
https://github.com/home-assistant/core/issues/49002

**Comment by frenck** [comment]
What is not clear? You are asking a general question about colors? Home Assistant has HS (and a separate B for brightness). Not HSL. I'm not sure what your question about Home Assistant is? Could you clarify?

**Comment by frenck** [comment]
I'm not sure how the linked bug is related to HSL?

**Comment by tggman** [comment]
> I'm not sure how the linked bug is related to HSL?

because the workaround is to specify hs_color ...

**Comment by tggman** [comment]
So specifying brightness is essentially = the B in HSB? I played with beforehand and changing the brightness changed the color. I didn't think that's how it was supposed to work.  That's certainly not how it works in the LIFX app.  I'm clearly missing something - but I'm not a light expert

**Comment by frenck** [comment]
> because the workaround is to specify hs_color ...

Sure, but that is a bug, I'm not sure what this mean for the documentation and the HSL stuff in this feedback.

**Comment by tggman** [comment]
if you search the internet for hs color you are pointed to all sorts of tools and info relating to hsl or hsb/hsv. To me, its not clear that specifying hs_color in Home Assistant in combination with brightness is the same as HSB/HSV. That's all. You asked for documentation feedback --- and there you have it. If you believe that the documentation is clear and correct as is, GREAT! Its on me. I'm the exception. Otherwise, the fact that we needed to have this conversation in the first place says the documentation isn't clear.  Thanks for you help!
