### ISSUE TITLE
Lost how to install

### ISSUE THREAD

**Issue by hesspoint** [home-assistant/home-assistant.github.io#17450]
### Feedback

In the documentation it says I need to enter key and name during installation. However during the installation it asks me for IP address and MAC address. I am confused.

Also it links to a manual how I enable LAN access on the gateway. It says I need to change to region China Mainland. I have the hub and all the child devices setup in my region Germany. I did switch the region to China but then the app is completely empty. The hub is not there. When I switch back to Germany then everything is there again.

How can I enable LAN access? Is there another way?

### URL

https://www.home-assistant.io/integrations/xiaomi_aqara/

### Version

2021.4.4

**Comment by syssi** [comment]
Do you know the exact hardware version of the gateway do you own? If the version is supported you have to remove the gateway from the EU server, reset it, logoff from the EU server / mi cloud and login again at the mainland china server. Register/setup the gateway again and try to follow the documentation. If your hardware version doesn't fit you won't be able to enable the LAN access (at mainland china servers too).
