### ISSUE TITLE
Action on markdown

### ISSUE THREAD

**Issue by Bubule02** [home-assistant/home-assistant.github.io#17459]
### Feedback

Hi

It would be nice to have tap_action on markdown card.
(I never find a way to do it)

### URL

https://www.home-assistant.io/lovelace/markdown/

### Version

2021.4.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
