### ISSUE TITLE
describe add-on usage for container installation 

### ISSUE THREAD

**Issue by smougenot** [home-assistant/home-assistant.github.io#17454]
## Facts
A note explains add-ons are not available for evry one (sounds so strange to me but it is a fact)
But an almost salvation appears  telling us we can do it another way.

## Should
Please provide a link to the alternate way to use add-on for the unfortunate users that can not benefit of a nice UI to use add-on

### URL

https://www.home-assistant.io/addons/

### Version

2021.4.4

**Comment by ludeeus** [comment]
There is no alternative way to run add-ons, you need the Supervisor for that.
The software that runs _inside_ the add-on, however, in most cases they also provide standalone containers, look at the documentation/website for the software that is running inside the add-on you wanted.

**Comment by smougenot** [comment]
Documentation is still failing us even if you close the issue @ludeeus 

So you should either
*  remove the misleading comment 
* or (as I suggested here) document it further

![2021-04-14 03-47-54](https://user-images.githubusercontent.com/1217669/114642443-391af580-9cd4-11eb-9f88-44a510bcccfa.png)

**Comment by frenck** [comment]
Agree, we can add a little bit of extra text there to tell what it means 👍
