### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by Crono141** [home-assistant/home-assistant.github.io#17462]
### Feedback

I edited the configuration.yaml as per the documentation, and then rebooted the HA server.  I am still unable to add the Leviton integration.  The integration just doesn't appear in the search inside the HA configuration dashboard.

### URL

https://www.home-assistant.io/integrations/decora_wifi/

### Version

2021.4.4

**Comment by frenck** [comment]
It should not appear in the configuration dashboard. The integrations shown in the UI are only showing integrations that are set up via the UI.

In this case, the light entities should be added to Home Assistant; you can find them in the list of entities:

[![Open your Home Assistant instance and show your entities.](https://my.home-assistant.io/badges/entities.svg)](https://my.home-assistant.io/redirect/entities/)

**Comment by Crono141** [comment]
I see them now.  This could be made clearer in the documentation. Thanks.

I am not able to move them to a room, as the settings say "This entity ("light.theater_fan") does not have a unique ID, therefore its settings cannot be managed from the UI." Checking the documentation, I have enabled advanced mode for my user, but still cannot assign this entity to a room.

**Comment by frenck** [comment]
<https://www.home-assistant.io/faq/#this-entity-does-not-have-a-unique-id>

You cannot use frontend features for entities without unique IDs
