### ISSUE TITLE
Binary sensor Door lock is inverted

### ISSUE THREAD

**Issue by b3nny27** [home-assistant/home-assistant.github.io#17465]
### Feedback

Hi, I've noticed that the sensor entity displayed as binary_sensor.REGNR_door_lock is inverted. Whenever the car is parked and locked (verified via volvo on call app), its status in home assistant shows "unlocked", vice versa.

### URL

https://www.home-assistant.io/integrations/volvooncall/

### Version

2021.4.4

**Comment by frenck** [comment]
Hi there @b3nny27!

Thanks for providing documentation feedback, however, it seems like you want to report a bug with an integration. There is no amount of documentation I can adjust to fix a bug in the code base.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by b3nny27** [comment]
Ah ok my bad, thanks!
