### ISSUE TITLE
Shark IQ R101AE constantly unavailable

### ISSUE THREAD

**Issue by twistp** [home-assistant/home-assistant.github.io#17474]
### Feedback

Hi

I installed this integration but everyday the Shark's state goes back to unavailable. I don't have Pi-hole or AdGuard installed. The only way to fix this is to restart the server.

I can also access the vacuum remotely  

Thanks

### URL

https://www.home-assistant.io/integrations/sharkiq/

### Version

2021.4.4

**Comment by bmorgan99** [comment]
Still open.  It seems ajmarks has bailed.

**Comment by flz** [comment]
Having similar issues. Reloading the integration fixes it.

**Comment by bmorgan99** [comment]
It has never been fixed for me.  I hope someone else can take up the torch.

**Comment by frenck** [comment]
Oh hi there @twistp (and @bmorgan99),

I've just noticed this issue. I see you are trying to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

There is no amount to documentation we can adjust to fix an bug; please report bugs with Home Assistant integrations in the Home Assistant Core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
