### ISSUE TITLE
Known issue at Somfy server side

### ISSUE THREAD

**Issue by Wiggum127** [home-assistant/home-assistant.github.io#17487]
### Feedback

There appears to be a known limitation at Somfy API level which limits the number of commands one can send within a short timeframe (see https://github.com/home-assistant/core/issues/49300). It would be helpful to mention this on the integration documentation page so that other users are aware.

### URL

https://www.home-assistant.io/integrations/somfy/

### Version

2021.4.4

**Comment by Wiggum127** [comment]
There is a soft limit at somfy side of 10 items in queue at the gateway. For example: closing 10 screens at the same time works, trying to close an 11th while the first 10 are still closing, you will get an error back.

**Comment by frenck** [comment]
This is not a documentation issue, but an issue in the integration and the upstream libraries used. A user should not be able to break it like that, it should have been rate-limited. 

As there is already an upstream issue open, I'll go ahead and close this one on the documentation end.
