### ISSUE TITLE
Balena Etcher not usable if using Raspberry Pi itself to write Home Assistant OS image

### ISSUE THREAD

**Issue by schellj** [home-assistant/home-assistant.github.io#17488]
### Feedback

The installation instructions for the Raspberry Pi include a recommendation to use Balena Etcher to write the Home Assistant OS image to the installation media. This may be problematic if you are actually using the Raspberry Pi to attempt to write the image (e.g., to an SSD that the Pi will boot from) as Balena Etcher does not provide a pre-built binary or installer for the architecture that Pi uses (ARM). Being new to Raspberry Pis and HA, this tripped me up for a bit until I realized that I could just use the Raspberry Pi Imager that was already installed.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.4.4

**Comment by frenck** [comment]
Hi there @schellj!

Thanks for providing feedback. We consider your use case relatively rare and assume a normal workstation/desktop to do these actions on.

As for the reason provided (to write to an SSD that the Pi will boot from), is actually something the project does not support. We recommend booting from SD and move the data partition to SSD instead.

<https://github.com/home-assistant/operating-system/blob/master/Documentation/partition.md>

Nevertheless, thanks for providing feedback 👍

**Comment by schellj** [comment]
@frenck Interesting. Booting from the SSD obviates the need to have an SD card in use at all. This seems desirable as it removes a component and a point of failure from the system. What's the reasoning for recommending the use of an SD card even when it isn't strictly necessary? My SSD-only Pi is functioning fine so far as far as I can tell.
