### ISSUE TITLE
manually curated list?

### ISSUE THREAD

**Issue by olskar** [home-assistant/home-assistant.github.io#17499]
### Feedback

> Note that devices in the switch platform identify as lights, so there is a manually curated list that defines which “lights” are switches.

Perhaps ellaborate a bit on what that means? 

### URL

https://www.home-assistant.io/integrations/deconz/

### Version

2021.4.4

**Comment by Kane610** [comment]
`Perhaps ellaborate a bit on what that means? I noticed that HA treats the switches from deCONZ as lights, does that have something to do with this?`

What do you mean by this? I don't understand what you're requesting.

**Comment by frenck** [comment]
@Kane610 I think the question is about these notes in the integration docs:

![image](https://user-images.githubusercontent.com/195327/115221367-dda09b80-a109-11eb-82b9-f5b4ac492703.png)

I could raise questions like: What is this list? What is on this list? Can it be extended? How do I do this manually?

**Comment by Kane610** [comment]
I mostly meant what he means by "I noticed that HA treats the switches from deCONZ as lights, does that have something to do with this?"

**Comment by olskar** [comment]
> I mostly meant what he means by "I noticed that HA treats the switches from deCONZ as lights, does that have something to do with this?"

Sorry, I made a separate issue for this:
https://github.com/home-assistant/core/issues/49519

This issue was just about the information on this "manually curated list" could be clearer :)
