### ISSUE TITLE
You need to add the homeassistant user to the audio group

### ISSUE THREAD

**Issue by fixx-er** [home-assistant/home-assistant.github.io#17491]
### Feedback

is it homeassistant? or is it Hass.io?

Under users I have Hass.io

### URL

https://www.home-assistant.io/integrations/vlc/

### Version

2021.4.4

**Comment by frenck** [comment]
This is not needed for Home Assistant OS or Supervised installation types.
~~The note on that page needs to be adjusted.~~

**EDIT**

So looking at that page, there is a big note on the top:

> The VLC media player integration, is currently only available for installations that are based on the Home Assistant Core in a Python virtual environment.

If you have an "Hass.io" user, then you are not a Home Assistant Core user, thus this integration is not available on your system.
