### ISSUE TITLE
Specifying refresh rate.

### ISSUE THREAD

**Issue by OldManOfTheSea69** [home-assistant/home-assistant.github.io#17504]
### Feedback

It’s written "Additional sensors can be added but at the expense of a reduced refresh rate. 2 sensors can be updated every 2*87 = 174 seconds, and so on.". It’s not clear if refresh rate is calculated based upon the number of sensors specified, or if refresh rate is user specifiable value per sensor. If it is specifiable; how, and where?

### URL

https://www.home-assistant.io/integrations/uk_transport/

### Version

2021.4.4

**Comment by frenck** [comment]
This rate is automatically calculated by the integration. There is no manual configuration needed for that.

I've opened up a small PR to adjust the documentation to make that clear.

Thanks for the feedback! 👍 

../Frenck 🚂
