### ISSUE TITLE
Why OS is the only comprehensive type of deployment? What's wrong with containers or virtual env?

### ISSUE THREAD

**Issue by AlexBGoode** [home-assistant/home-assistant.github.io#17503]
### Feedback

Hello

As for me, it is a really great achievement on the planet Earth to have virtualization technologies like python env or even better containers like docker... bit we can see both of them as very limited in support and only the option to have comprehensive support of all features is to go with a preinstalled OS image

### URL

https://www.home-assistant.io/installation/

### Version

2021.4.4

**Comment by frenck** [comment]
Because many of those features cannot be offered in those environments in a reasonable, manageable, stable and maintainable way.

Every installation method offer pro's and cons 🤷 

As this is not really documentation feedback, I'll go ahead and close this documentation feedback issue.
