### ISSUE TITLE
Add Example for Modbus config of same hub in different files

### ISSUE THREAD

**Issue by chiefdeputy** [home-assistant/home-assistant.github.io#17502]
### Feedback

I'm using the following construct in my configuration.xml:
homeassistant:
    packages: !include_dir_named packages

So I'm able to have nice little config files, which I can separate rooms / devices / logical constructs without a 1000 line yaml file....

With the new Modbus config style I do not see a possibility to put a modbus switch in one yaml file and a modbus sensor connected to the same hub in another. With deprecated style this can easily be done...

Can you please add an example how to do this with the new config style.

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.4.4

**Comment by frenck** [comment]
Using split configuration is considered an advanced subject and isn't specific to any integration, thus shouldn't be documented on specific integration pages either.

For more information about splitting up your configuration see: <https://www.home-assistant.io/docs/configuration/splitting_configuration/>

If you are in need of support with that, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck 🚂
