### ISSUE TITLE
Update the integration in order to make it work on V3 clusters

### ISSUE THREAD

**Issue by Redblockmasteur** [home-assistant/home-assistant.github.io#17510]
### Feedback

Hello since the TTN is shutting down V2 clusters at the end of the year. And this integration is not working for apps that are moved to V3 it would be nice if you could update this integration by the end of the year to prevent users from being stuck.
Best regards.

### URL

https://www.home-assistant.io/integrations/thethingsnetwork/

### Version

2021.4.4

**Comment by Roberto6969** [comment]
Any news regarding v3 integration will be appreciated!

**Comment by Redblockmasteur** [comment]
> Any news regarding v3 integration will be appreciated!

Not i dont have any news but you can use MQTT to replace this integration

**Comment by Roberto6969** [comment]
As long as I remember Home Assistant supports only single MQTT broker. If I would like to use my local MQTT broker and TTN broker also, it wouldn't be possible. Is bridging TTN to my local MQTT solution in this case?
