### ISSUE TITLE
Sharing Broadlink IR and RF codes

### ISSUE THREAD

**Issue by mbbs1024** [home-assistant/home-assistant.github.io#17518]
### Feedback

Would it be interesting to add a link to the community forum topic for sharing Broadlink IR and RF codes ?
https://community.home-assistant.io/t/share-your-broadlink-ir-rf-codes/295055

In this way, more people would share their own recorded codes and in this way help others to find codes for their perhaps malfunctioning or lost remotes, or avoid having to record all of their remotes themselves.

IMO, a good place for this would be just before the chapter of "Conversion of codes from other projects"
As I am fairly new to HA, instead of directly editing the page, I submit this idea as feedback, to avoid messing up or going against the documentation guidelines.

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2021.4.4

**Comment by frenck** [comment]
It might make sense if such a topic is substantial. However, right now it is not.
In general, we try to avoid mixing up community-provided resources with our official documentation.

For now, I'm closing this, but maybe in the future. Thanks for providing feedback 👍 

../Frenck 🚂
