### ISSUE TITLE
How to integrate air_quality sensors?

### ISSUE THREAD

**Issue by pipetboy** [home-assistant/home-assistant.github.io#17524]
### Feedback

Maybe it's just me, but I just can't figure out how to get the data about air_quality. There is nothing in the documentation about what to add to the yaml files. Or am I missing something very obvious?

### URL

https://www.home-assistant.io/integrations/air_quality/

### Version

2021.4.5

**Comment by hmmbob** [comment]
The `air_quality`  integration is a base integration on which others can build. See https://www.home-assistant.io/integrations/#health for integrations that use this platform. 

I'll add a note about this in the docs.

**Comment by frenck** [comment]
Thanks, @hmmbob 👍 

../Frenck 🚂
