### ISSUE TITLE
Documentation not applicable to hass.io aka homeassistant 

### ISSUE THREAD

**Issue by OJBender** [home-assistant/home-assistant.github.io#17540]
### Feedback

A remark about the documentation not applicable to homeassistant operating system would be useful.
Example:
If you have a home assistant operating system installation that comes with a supervisor container and many more functions in comparison to the core-installtion, none of the instructions will apply for you.
Installing the pylacrosse package will work differently, if at all.
Many command line binaries like sudo, docker, pip-install you are used to will not be available in the home assistant operating system environment.

### URL

https://www.home-assistant.io/integrations/lacrosse/

### Version

2021.4.6

**Comment by frenck** [comment]
Thanks for the feedback @OJBender, that needs an update indeed 👍 

Please note: "hassio" is not a term used anymore. It is ambiguous as well. Please avoid using it.

**Comment by OJBender** [comment]
Apologies for the legacy terms. Changed them to best knowledge.
I stepped over this when trying to follow integration instructions in the supervised environment.
