### ISSUE TITLE
TX25 Dual Channel Sensors?

### ISSUE THREAD

**Issue by OJBender** [home-assistant/home-assistant.github.io#17545]
### Feedback

Great work. Can we find a statement if the TX25 sensors with dual channel temperature can be facilitated?

### URL

https://www.home-assistant.io/integrations/lacrosse/

### Version

2021.4.6

**Comment by frenck** [comment]
That would be a support question / a community question.

The documentation states it has been texted with the TX29. Others might work. If not, a feature request can be raised on our community forums.

Thanks! 👍 

../Frenck 🚂
