### ISSUE TITLE
dim display screen

### ISSUE THREAD

**Issue by toomservice** [home-assistant/home-assistant.github.io#17541]
### Feedback

i want display screen alway on in app home assistant
ios, and android

### URL

https://www.home-assistant.io/docs/scripts/service-calls/

### Version

2021.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
