### ISSUE TITLE
Integration stopped working after HA update to new version

### ISSUE THREAD

**Issue by OndHas** [home-assistant/home-assistant.github.io#17556]
### Feedback

Withings integration do not show data, it was warking before and I did not change any settings of this integration. Only what was done is HA update.

It is possible to delete integration and add it again, select profile but then I do not see any data (Not identified)
for example:
Withings diastolic_blood_pressure_mmhg. -> Not identified (I do not see data).

 

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2021.4.6

**Comment by thecode** [comment]
You should open the issue here: https://github.com/home-assistant/core/issues/new/choose
This repo is only for documentation issues
