### ISSUE TITLE
Z-Wave removed dead node is not accurate

### ISSUE THREAD

**Issue by steppel** [home-assistant/home-assistant.github.io#17559]
### Feedback

I have the latest version of Zwave JS and I have 3 dead nodes in the device list. In Developer those nodes do not show up. So the documentation doesn’t really help. 

### URL

https://www.home-assistant.io/docs/z-wave/adding/

### Version

2021.4.6

**Comment by frenck** [comment]
This is not the documentation of Z-Wave JS, but the documentation of the legacy `zwave` integration.

I'll make sure the page has a warning for that.
