### ISSUE TITLE
How can i change password for synology

### ISSUE THREAD

**Issue by OndHas** [home-assistant/home-assistant.github.io#17555]
### Feedback

I have change my password for synology. It ise very difficult to figure out how can I change passwort in Home Assistatn for already configured Synology DSM integration

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2021.4.6

**Comment by mib1185** [comment]
Hi @8811025080 

I'm afraid there is no re-auth-flow implemented in synology_dsm integration, yet :confused:

For now I see two options:

1. remove and add integration again

- this is the easiest way via UI
- but history for all entities got lost

2. change password in configuration backend file

- file: `/config/.storage/core.config_entries`
- search for config block of you NAS and change password - example:

```json
            {
                "entry_id": "1f8d8b73f1ea87b6659d5d322213f707",
                "version": 1,
                "domain": "synology_dsm",
                "title": "diskstation",
                "data": {
                    "host": "192.*.*.*",
                    "port": 5001,
                    "ssl": true,
                    "verify_ssl": false,
                    "username": "USERNAME",
                    "password": "PASSWORD",
                    "mac": [
                        "00-12-34-56-78-9A"
                    ]
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "cloud_poll",
                "unique_id": "***********",
                "disabled_by": null
            },
```

- reload integration via UI or restart HA at all

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
