### ISSUE TITLE
Error - Config Flow could not be loaded

### ISSUE THREAD

**Issue by pnneil** [home-assistant/home-assistant.github.io#17550]
### Feedback

I have attempted to add the Tasmota Integration into a new Home Assistant install on a Raspberry Pi 4 4GB. When I select it I get the error as above.  If I attempt to add another integration I get a spinning wheel with "Please wait while in integration is installed".  I quit this after 2 hours.  Is this still attempting to install Tasmota and if so how long should it take?

### URL

https://www.home-assistant.io/integrations/tasmota/

### Version

2021.4.6

**Comment by pnneil** [comment]
OK, I have loaded the 32 bit version of HA and gone through the neccessary prereqs.  Today it seems to have loaded but it only asked for a discovery topic prefix. I left the default of tasmota/discovery.  Is that it?

**Comment by frenck** [comment]
Hi there @pnneil,

It seems like you want to report an issue with an integration or are in need of help/support with setting up your system. However, you have now provided documentation feedback instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

If you instead want to report a bug with an integration, please report those here:

<https://github.com/home-assistant/core/issues>

Closing the issue on this end at this point.

Thanks! 👍

../Frenck 🚂
