### ISSUE TITLE
integration not shown already configured

### ISSUE THREAD

**Issue by BenFR23** [home-assistant/home-assistant.github.io#17567]
### Feedback

Hello, Somfy ntegration is not shown and when I try to install it, it says that it's already configured and just one can be.

Check script is without effect.

### URL

https://www.home-assistant.io/faq/component/

### Version

2021.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
