### ISSUE TITLE
Speech, where does it go ?

### ISSUE THREAD

**Issue by B0ndo2** [home-assistant/home-assistant.github.io#17569]
### Feedback

Please put more details on Speech, where does STT get processed

### URL

https://www.home-assistant.io/integrations/intent_script/

### Version

2021.4.6

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/115900629-744dbf00-a460-11eb-80e7-d5749ceeec72.png)

By the integrations that handle that, as written in the first paragraph. Maybe I'm misunderstanding your suggestion in this case?

../Frenck 🚂

**Comment by B0ndo2** [comment]
I understood the response as being the action part of the intent script. I am using Rhasspy for intent handling and from what is written it was not clear what happens with the text part of the script. Maybe an example or more explanation would be helpful

**Comment by frenck** [comment]
I'm sorry, I'm not following the concern you are raising (don't worry, I'm sure it's me in this case).

When an intent runs/triggers, it can do 3 things, return a text (which can be spoken if the device/integration supports that), trigger showing a card and run an action.

**Comment by B0ndo2** [comment]
I understand now but maybe it's me, how about adding something like this

speech map (Optional)

Text or template to return. The text will be returned to the integration that fired the intent, if the integration supports TTS; speech will be played.

I feel this is the case with most of the documentation, the description under the parameters are not really saying much. I know you definitely see it as clear  since you are involved in developing the system but for a user, it is not clear
