### ISSUE TITLE
no options button and no device update 

### ISSUE THREAD

**Issue by toben1997** [home-assistant/home-assistant.github.io#17575]
### Feedback

i renewed my tuya integration but i dont have any options button in the integration side for tuya and no device is updating if the state is changed  any other way then through home assistant 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.4.6

**Comment by frenck** [comment]
Hi there @toben1997!

Seem like you are trying to report an issue with the Tuya integration, however, you have submitted documentation feedback instead.

Please submit issues with an integration here:

<https://github.com/home-assistant/core/issues>

Thanks!

../Frenck 🚂
