### ISSUE TITLE
Homekit docs: Add some notes about zeroconf and using a discovery tool to debug issues

### ISSUE THREAD

**Issue by BenWoodford** [home-assistant/home-assistant.github.io#17574]
### Feedback

Just had to go through this myself, as it turned out the Homekit Integration was using the wrong interface for broadcasting due to `zeroconf`'s default value of `default_interface: true`

The moment I set that to false, everything worked.

A troubleshooting block when everything goes not responding or you can't add HASS as an accessory would be a big help for others with the same problem, I was digging around the HAP-Python issues when I found these troubleshooting steps:

Using either the [Discovery App](https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12) or [Bonjour Browser](https://hobbyistsoftware.com/bonjourbrowser) users should look for `_hap._tcp.` with mention to Home Assistant (this may be set to whatever they manually named their HASS bridge, not sure)

If it doesn't _ever_ pop up, chances are `zeroconf` needs to be set to broadcast on more than the default interface (i.e. setting `default_interface` to `false`), of note I was using an exotic environment setup (my HASS container has its own IP by way of macvlan) so it's probably worth mentioning this is likely to be required if using macvlan and/or multiple docker networks as docker can be a bit funny about which is your "default" network

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2021.4.6

**Comment by bdraco** [comment]
@BenWoodford Thanks for the report. We would appreciate it if you updated the documentation using this link: https://github.com/home-assistant/home-assistant.io/edit/current/source/_integrations/homekit.markdown

Thanks 👍

**Comment by bdraco** [comment]
We can close this since the network integration now controls all of this and we do much better auto detection.
