### ISSUE TITLE
Can i have multiple triggers on one device?

### ISSUE THREAD

**Issue by tuct** [home-assistant/home-assistant.github.io#17577]
### Feedback

An example would be nice, like this:

Topic: "homeassistant/device_automation/colorkeys/config"
Payload:
{ "automation_type":"trigger", "topic": "homeassistant/device_automation/colorkeysA/button_1", "type": "toggle", "subtype":"button_1","device":{"name":"tos-colorkeys","mf": "tob","identifiers":"tos-color-keys-01","model":"tck-01"}}

Also i am wondering if i only can register one type/subtype .... my self-made device has 8 buttons and 4*4 different actions i want to provide which would mean i have to register now 16 devices?

I would like to be able to register 1 device with multiple triggers

### URL

https://www.home-assistant.io/integrations/device_trigger.mqtt/

### Version

2021.4.6

**Comment by tuct** [comment]
I figured out that if I use the node ID as well I can add multiple triggers to one device as long as  use different config and trigger URLs but the same device entry. 
Only thing is I can't see the mqtt yaml Config in the UI, guess it's because I have multiple triggers. Using the device triggers work perfect! 

Definitely the documentation can be enhanced, I could share what I did.

**Comment by emontnemery** [comment]
There's no need to use multiple `node_id`, but the device triggers do need a unique topic for each trigger in the same way as entities do.
A PR to clarify this and/or add examples of MQTT triggers would be welcome.
