### ISSUE TITLE
MQTT sensor: device config variable doesn't say that connections and/or identifiers are required

### ISSUE THREAD

**Issue by nickagian** [home-assistant/home-assistant.github.io#17578]
### Feedback

I think there is a small detail that is misleading in the documentation for the **device** configuration parameter.

More specifically, I think that we should indicate that this parameter requires either the **connections** or the **identifiers** fields. Both right now are optional but when I tried to set up a device via MQTT discovery without these fields I got the error that 

(edit: put the whole error message)
> Exception in async_discover when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'name': 'testdev_battery', 'device_class': 'battery', 'state_topic': 'homeassistant/sensor/testdev_battery/state', 'unique_id': 'testdev_battery', 'device': {'name': 'testdev', 'manufacturer': 'me'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 152, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: Device must have at least one identifying value in 'identifiers' and/or 'connections' for dictionary value @ data['device']

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

(edit: core version is added)
2021.4.6 (using core version core-2021.3.4)

**Comment by emontnemery** [comment]
Thanks @nickagian for the good suggestion 👍 
Maybe something like (_with added text in italics_):
> Information about the device this sensor is a part of to tie it into the device registry. Only works through MQTT discovery and when unique_id is set. _At least one of `identifiers` or `connections` must be present to identify the device._

**Comment by emontnemery** [comment]
Fixed by #18199
