### ISSUE TITLE
Battery powered Shelly's

### ISSUE THREAD

**Issue by JPOliveGit** [home-assistant/home-assistant.github.io#17587]
### Feedback

How is the development of the shelly integration on the battery powered shelly's because it continues to show the wrong state of it, in the shelly app it shows closed on home assistant open. thanks for all

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.4.6

**Comment by chemelli74** [comment]
Hi @JPOliveGit , please enable debug log for `aioshelly` and attach log to a service like http://pastebin.com

Simone

**Comment by thecode** [comment]
@JPOliveGit there are no known issues about wrong states in Shelly integration.
If you have an issue please first look at the open issues in the core repo:
https://github.com/home-assistant/core/labels/integration%3A%20shelly

If you don't find something that help you there, open an issue at:
https://github.com/home-assistant/core/issues/new/choose

This repo is for documentation issues.
Thanks.
