### ISSUE TITLE
Home Assistant Core, auto start on machine restart

### ISSUE THREAD

**Issue by 5349U11** [home-assistant/home-assistant.github.io#17582]
### Feedback

When restarting the machine that HA runs on, you need to boot up HA again.
With an older install guide (home assistant core), the way that HA was installed it was easy enough how to google how to make it so HA starts with the machine (by creating a systemd services). 

Maybe I'm just dense, but it does not appear to be straight forward with the current install method for core (python VE), and I think adding in some code showing how to set this up would be well received.

### URL

https://www.home-assistant.io/installation/linux/

### Version

2021.4.6

**Comment by frenck** [comment]
We consider this an advanced subject, if one uses this installation method, we assume one is capable of setting up a startup for their systems as well.

This is not something we will be documenting for various reasons. If one is not sure how to achieve this, it is probably better to pick one of the other offered installation methods.

../Frenck 🚂
