### ISSUE TITLE
Decimal numbers on Shelly

### ISSUE THREAD

**Issue by JPOliveGit** [home-assistant/home-assistant.github.io#17586]
### Feedback

Can you insert in the documentation about shelly integration how can we make it show the decimal numbers, because when we use the developer tools and call the state of the sensor it show the value in decimals ex: 22.6 but when we make a button with the sensor it shows 23 removing the decimal

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.4.6

**Comment by thecode** [comment]
This is not related to Shelly integration documentation, the right place for this questions is in the community forums if you see the right value in developer tools the integration is working correctly. Anyhow if you need help start by showing the configuration you used to create the button.
