### ISSUE TITLE
Netatmo Doorbell

### ISSUE THREAD

**Issue by schumi69** [home-assistant/home-assistant.github.io#17588]
### Feedback

Hello, I have just purchased the new netatmo doorbell.  do you know if integration is planned in HA?

https://www.netatmo.com/fr-fr/security/doorbell

Thank you!!😁

### URL

https://www.home-assistant.io/integrations/netatmo/

### Version

2021.4.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
