### ISSUE TITLE
More services for NUKI please

### ISSUE THREAD

**Issue by Friedi1970** [home-assistant/home-assistant.github.io#17597]
### Feedback

First: Thanks for this great integration but I wonder why there is only one service integrated which is the LOCK_N_GO.
It would be really helpful to add more services like OPEN, UNLOCK etc.
Anyway the LOCK_N_GO with unlatch is a bit weird. I am coming home, the service is triggered, I get into my flat and then the door will be locked.

Please add the additional services.

### URL

https://www.home-assistant.io/integrations/nuki/

### Version

2021.4.6

**Comment by frenck** [comment]
Those are generic services, provided by Home Assistant for it being a lock.

See: <https://www.home-assistant.io/integrations/lock#services>
