### ISSUE TITLE
Change "alarm_control_panel.alarm" to "alarm_control_panel.ha_alarm"

### ISSUE THREAD

**Issue by craigtappin** [home-assistant/home-assistant.github.io#17609]
### Feedback

Configured the manual alarm panel as per https://www.home-assistant.io/integrations/manual/ and it created an entity called "alarm_control_panel.ha_alarm", yet the documentation for Alarm Panel Card refers to "alarm_control_panel.alarm". Suggest updating to include **ha_** in the entity name :)

### URL

https://www.home-assistant.io/lovelace/alarm-panel/

### Version

2021.4.6

**Comment by craigtappin** [comment]
Created a proposed change, sorry I'm a Github noob!

**Comment by frenck** [comment]
There are multiple examples in that document, one always has to adjust the examples to their situation.
IMHO non of them are wrong and making them, all the same, isn't possible either.
