### ISSUE TITLE
Configuring platform binary sensor, input_type string (Optional, default: holding)  type of adddress (holding/discrete/coil)

### ISSUE THREAD

**Issue by Fox350** [home-assistant/home-assistant.github.io#17608]
### Feedback

Hy,
just to mention that Configuring platform binary sensor, input_type string (Optional, default: holding)  type of adddress (holding/discrete/coil) is incorrect.  If I try to enter holding, it is invalid :
Invalid config for [modbus]: value must be one of ['coil', 'discrete_input'] for dictionary value @ data['modbus'][0]['binary_sensors'][0]['input_type']. Got 'holding'. (See /config/configuration.yaml, line 40). 
So it cannot be default or diefined.  
Thanks

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.4.6

**Comment by janiversen** [comment]
I think you are using the "old" configuration style. Where you have "sensors" separated from modbus. As the examples shows and documentation reads, you have to have "sensors" within "modbus" (new configuration style). 

"old" configuration style is no longer supported but silently accepted for a while.

If you still think there is a problem, please provide a sample configuration.yaml file, showing the problem.

**Comment by Fox350** [comment]
Hy Janiversen and thansk for your idea.  If I get it right, I do use the "new" way of editing the configuration.yaml.  I use HA for 3 months now.  I was not able to use the binary_sensor as described in the documentation for a holding register.  I was trying to read the first bit (weight of 1) in a 16 bit register using binary_sensor.  Unfortunately, HA is throwing me the error in the validation and at the restart if i try to implement input_type: holding :

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:486
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 19:37:03 (1 occurrences)
Last logged: 19:37:03

Invalid config for [modbus]: value must be one of ['coil', 'discrete_input'] for dictionary value @ data['modbus'][0]['binary_sensors'][0]['input_type']. Got 'holding'. (See /config/configuration.yaml, line 40).

Here is my modbus configuration section in configuration.yaml in short:

###########      MODBUS integration BEGIN      ################################
# https://www.home-assistant.io/integrations/modbus
modbus:
- name: vesp211-01
  type: rtuovertcp
  host: 192.168.1.93
  port: 502
  timeout: 3

  binary_sensors:
      - name: Sensor1
        slave: 1
        address: 23
        device_class: door
        input_type: holding
        scan_interval: 5

  sensors:
    - name: Minuterie ventilateur garage
      unit_of_measurement: minutes
      slave: 1
      address: 21
      count: 1
      data_type: int
      input_type: holding
      offset: 0
      precision: 0
      reverse_order: false
      scale: 1
      scan_interval: 5
    - name: Température garage
      unit_of_measurement: °C
      slave: 1
      device_class: temperature
      address: 20
      count: 1
      data_type: int
      input_type: holding
      offset: 0
      precision: 1
      reverse_order: false
      scale: 0.1
      scan_interval: 5
    - name: Consigne température garage
      unit_of_measurement: °C
      slave: 1
      device_class: temperature
      address: 22
      count: 1
      data_type: int
      input_type: holding
      offset: 0
      precision: 1
      reverse_order: false
      scale: 0.1
      scan_interval: 15

  ##############      MODBUS integration END      ###################################################

I am trying to read 

Holding register | Read-write | 16 bits | 4001 +23 on a schneider Zelio modbus plc.

Sensors and climate were tested working fine.

It is more an effort to update the documentation but it would be nice it would actually work :)

On thing I found strange is that Schneider is giving in their table 4001 + 23 and the modbus.org seem to give 400001 as the first address.. probably a typo or removing zeros but hey, it works for sensors so :)

**Comment by janiversen** [comment]
your binar_sensor Sensor1 cannot be type holding as stated in the documentation.

**Comment by Fox350** [comment]
Hy Janiverser, but it is stated like a input_type option... 
That is what I am saying is to be removed cause this is not a valid option, either a valid default.
input_type string (Optional, default: holding)

type of adddress (holding/discrete/coil)

![image](https://user-images.githubusercontent.com/78315589/116453143-86e34200-a82c-11eb-962a-f0f07359ff50.png)

**Comment by janiversen** [comment]
Sorry I do not know why, but I have been looking at sensors until you submitted your config.

You are correct, that is a copy/paste error. I will correct it a.s.a.p.

**Comment by janiversen** [comment]
Again sorry for having misread your issue, I have submitted a PR so we can get it fixed.

Thanks for catching it.

**Comment by Fox350** [comment]
Thanks for your work guys!  I appreciate
