### ISSUE TITLE
Enable multiple usage

### ISSUE THREAD

**Issue by Trufax** [home-assistant/home-assistant.github.io#17607]
### Feedback

Hello,

i would like to monitor the train departure in 2 directions. But i can only add this sensor once. Please make it possible to add the sensor multiple times so you can monitor multiple departures at once. 

Regards

Trufax

### URL

https://www.home-assistant.io/integrations/deutsche_bahn/

### Version

2021.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
