### ISSUE TITLE
Additional useful information

### ISSUE THREAD

**Issue by vahaldor** [home-assistant/home-assistant.github.io#17602]
### Feedback

Please, add to the configuration flow following:
- if you changed the DSM port or force HTTPS access than add port leading to your DSM (the integration works with 5000 or 5001 as defaults)

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2021.4.6

**Comment by mib1185** [comment]
Hi @vahaldor 

as you already wrote - the integration uses the default ports (_5000 for non-ssl and 5001 for ssl_).
If the user has changed port of DMS, it can be also used during setup of integration.
So to be honest, I do net get, what you would like to have added to the docs?

**Comment by vahaldor** [comment]
Hi @mib1185,
I would add exactly what you wrote. I did not realize for hours that the integration uses DSM ports, the error message does not say anything and documentation does not contain this info. I would say that this tiny note in the documentation will save a lot of stress for future users.
