### ISSUE TITLE
Webpage Card - Feature Suggestion

### ISSUE THREAD

**Issue by smoresrock** [home-assistant/home-assistant.github.io#17623]
### Feedback

Apart from the aspect_ratio, which appears to resize the height of the card within its column, another variable to set either the zoom level or resolution size the webpage is constrained to would be nice. This would enhance views of webpages and even invoke implicit measures the website has taken to handle a given resolution.

### URL

https://www.home-assistant.io/lovelace/iframe/

### Version

2021.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
