### ISSUE TITLE
Marmitek Smart me app

### ISSUE THREAD

**Issue by Marmitek-Peter** [home-assistant/home-assistant.github.io#17629]
### Feedback

Is it possible to support the Tuya based Marmitek Smart me app?
We will promote Home assistant then in the app and our website.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by frenck** [comment]
@Marmitek-Peter On Discord, feel free to reach out to me directly! 👍
