### ISSUE TITLE
Frontend caching is too aggressive

### ISSUE THREAD

**Issue by jurgenhaas** [home-assistant/home-assistant.github.io#17625]
### Feedback

When keeping the frontend open in the browser all the time on a desktop that runs 24/7, the cache size grows up to over 100 GB of data. Don't know what HA is doing with all that data on the client side, but I'm almost certain that's over the top.

On a mobile, where I open the app only now and then, the cache also grows to 4 GB which, I feel, is problematic.

### URL

https://www.home-assistant.io/faq/browser/

### Version

2021.4.6

**Comment by frenck** [comment]
Hi there @jurgenhaas! 👋 

It seems like you want to report a bug with the frontend, but instead, you have provided documentation feedback. There is no amount of documentation I can adjust to fix that issue...

Could you please raise a bug report at the frontend issue tracker instead?

<https://github.com/home-assistant/frontend/issues>

Thanks! 👍
