### ISSUE TITLE
Set the TXT record of your DuckDNS subdomain - isn't so obvoious really!

### ISSUE THREAD

**Issue by AlexBGoode** [home-assistant/home-assistant.github.io#17622]
### Feedback

I used to use DuckDNS services for a while but this advice to merely set the TXT record sounds isn't obvious! if we practically advise external people to follow this way then we'd better show how exactly to configure it! I mean a step-by-step instruction

If you are at the DuckDNS homepage then you are lost, as for me
 

### URL

https://www.home-assistant.io/integrations/duckdns/

### Version

2021.4.6

**Comment by frenck** [comment]
I'm not sure what your feedback exactly is?

The integration exposes a service for setting a TXT record on the domain, there isn't really much more to that?
