### ISSUE TITLE
Update blueprints

### ISSUE THREAD

**Issue by cinghialino** [home-assistant/home-assistant.github.io#17637]
### Feedback

there is no info regarding how update existing blueprints, I believe somethimes the blueprint creator wants to tweak or add functionalities to the sequence, and there is no way of update it automatically

### URL

https://www.home-assistant.io/docs/blueprint/tutorial/

### Version

2021.4.6

**Comment by frenck** [comment]
There is no update logic to blueprints. One can re-import or overwrite them (even adjust).
