### ISSUE TITLE
hass reports an error

### ISSUE THREAD

**Issue by klakro** [home-assistant/home-assistant.github.io#17659]
### Feedback

I used this documentation:
CREATE THE VIRTUAL ENVIRONMENT
First we will create a directory for the installation of Home Assistant Core and change the owner to the homeassistant account.
All steps are passed until tis command "hass"
(homeassistant1) homeassistant1@raspberrypi:/srv/homeassistant1 $ hass
Unable to find configuration. Creating default one in /home/homeassistant1/.homeassistant
2021-05-01 18:20:47 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward

What went wrong?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.4.6

### Additional information

I used homeassistant1 instead of homeassistant because i tried this before with no success.

**Comment by frenck** [comment]
Hi there @klakro 👋  Thank you for reaching out. We use this GitHub issue tracker for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
