### ISSUE TITLE
modbus integration verify_state validation failed 

### ISSUE THREAD

**Issue by rostislav-palivoda** [home-assistant/home-assistant.github.io#17657]
### Feedback

https://www.home-assistant.io/integrations/modbus#configuring-platform-switch - Switch has verify_state, if I put in config this parameter then I have error Invalid config for [modbus]: [verify_state] is an invalid option for [modbus]. Check: modbus->modbus->14->switches->3->verify_state. (See ?, line ?).    Latest version of HA. Probably caused by https://github.com/home-assistant/core/pull/46591/files - CONF_VERIFY_STATE changes

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.4.6

### Additional information

HA latest version, just updated and migrating to new config.

**Comment by rostislav-palivoda** [comment]
```
2021-05-01 19:26:22 ERROR (MainThread) [homeassistant.components.switch] Error while setting up modbus platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/modbus/switch.py", line 132, in async_setup_platform
    switches.append(ModbusRegisterSwitch(hub, entry))
  File "/usr/src/homeassistant/homeassistant/components/modbus/switch.py", line 253, in __init__
    self._verify_state = config[CONF_VERIFY_STATE]
KeyError: 'verify_state'
```

**Comment by janiversen** [comment]
yes it is a known issue with 2021.4.6 please upgrade to 2021.5

**Comment by rostislav-palivoda** [comment]
Is there any open PR ? ...or a patch I can apply to go with 4.6 version?

**Comment by rostislav-palivoda** [comment]
I'm on Hass OS and it does not offer any updates.  2021.5 is in Beta stage now? 

For my environment I really don't like idea of moving to Beta version and pulling other other untested changes. Rollback is a pain because configs already rewritten to new format. Just to enable  modbus Switch, is there a patch available? Any open PR for this? 

Switch is critical functionality for me.

## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | 

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.15
disk_total | 30.8 GB
disk_used | 3.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Visual Studio Code (3.3.0), Log Viewer (0.10.2), SQLite Web (3.1.0), Terminal & SSH (9.1.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 1
views | 11
mode | storage

</details>

**Comment by janiversen** [comment]
There are no patch for this in here, since there are nothing to change in the documentation.

Problems with the code are raised in https://github.com/home-assistant/core/issues, but I can already now tell you, that you
have 2 choices for a fast solution:
a) install beta with all the pain it contains.
b) use your backup of the functioning config and downgrade.

Between 2021.3 and 2021.5 are many patches for modbus including a library upgrade, so just cherry-picking one PR, might not be a good idea and is quite a risk to take.

**Comment by rostislav-palivoda** [comment]
For now I modified /switch.py line 253 with setting self._verify_state = True. This allows to bypass validation problem and keep verify _state set. Waiting for next stable release.

Here is my problematic config example that causes this error:
```
- name: test_switch
  slave: 3
  input_type: holding
  address: 5
  command_on: 0x0100
  command_off: 0x0200
  state_on: 0x0001
  state_off: 0x0000
  scan_interval: 15
```
If  input_type: coil then it works. 

Now it does not look like documentation fix. :)

What I miss in documentation page and see similar questions on forum: 
- no example for sensor with data_type: custom, like:
```
  data_type: custom
  structure: ">6L6h"
```
- retrieved values can be parsed with template, like:
```
    backup_battery_e:
      friendly_name: Backup Battery Energy
      value_template: >-
        {% set valid = not is_state('sensor.modbus_sensor1', 'unavailable') %}
        {% set values = states('sensor.modbus_sensor1').split(',') %}
        {{ (values[2]|float + (values[3]|float * 255)) / 10 if valid else 'unavailable' }}

```
- all examples are for ModBus TCP and none are for RTU.

**Comment by janiversen** [comment]
Well this is open source so feel free to submit a patch with a struct example.

All integrations can be passed with templates, which is why that is documented in templates and not in every integration.

Can we agree that this issue is solved, so please close it.
