### ISSUE TITLE
used by 100% of the active installations not possible due to opt in

### ISSUE THREAD

**Issue by lein1013** [home-assistant/home-assistant.github.io#17663]
### Feedback

Hi, I think the wording must be updated to give the true statistics here - If user can opt-in, there are always users who do not opt-in. Hence the 100% is related to the active installation where the user has opt-in for analytics. 
The number of active installations could maybe estimated by server metrics when the user does an update

Proposal:
change to "used by 100% of the active installations (which have opt-in for analytics)"

### URL

https://www.home-assistant.io/integrations/analytics/

### Version

2021.4.6

**Comment by frenck** [comment]
> The number of active installations could maybe estimated by server metrics when the user does an update

We actually don't have that number.

> change to "used by 100% of the active installations (which have opt-in for analytics)"

Considering the amount of instances reporting, it is safe to assume the result will be the same.

Nevertheless, thanks for your feedback! 👍
