### ISSUE TITLE
Strange implementation of a discrete low pass filter?

### ISSUE THREAD

**Issue by VdR1960** [home-assistant/home-assistant.github.io#17675]
### Feedback

By the nature of HA I would think all sensor data is sampled. Skipping the math, a discrete low pass filter for sampled data is usually implemented as:

y[k]=a × y[k−1] + (1−a) × x[k], with a = e^(−ωT), where ω is the corner frequency in rad/s and T is the sample interval in s.

It looks like the HA implementation can be used with the following transformation:

time_constant = 1 / (1 - e^(−ωT))

### URL

https://www.home-assistant.io/integrations/filter/

### Version

2021.4.6

### Additional information

A good explanation of the math can be found here:

http://controlsystemsacademy.com/0020/0020.html

**Comment by dgomes** [comment]
What are you addressing/trying to achieve with this issue ?

BTW: Not all home assistant sensors are sampled at a constant frequency.

**Comment by VdR1960** [comment]
The documentation is vague. The true meaning of time_constant in this context is unclear. That makes it difficult to make good use of this filter. I just wanted to be helpful improving that because a working filter can be very helpful for many automation tasks.I'm am aware that not all values are sampled at a constant rate. Definening a true low pass filter for such a situation is a bigger challenge.Greetings,VincentOn May 3, 2021 14:08, Diogo Gomes ***@***.***> wrote:
What are you addressing/trying to achieve with this issue ?
BTW: Not all home assistant sensors are sampled at a constant frequency.

**Comment by dgomes** [comment]
Well in that case you can propose a change directly to the documentation. Contributions are welcomed :)
