### ISSUE TITLE
Cover attributes wrong?

### ISSUE THREAD

**Issue by plh4** [home-assistant/home-assistant.github.io#17671]
### Feedback

Seems like documentation is wrong.

Tried the "Cover", but the attributes move_long_address and move_short_address are not valid?

### URL

https://www.home-assistant.io/integrations/knx/

### Version

2021.4.6

### Additional information

-

**Comment by frenck** [comment]
Could you please provide the configuration you have used, that should have worked it didn't?

Thanks @plh4!

**Comment by plh4** [comment]
Sorry.. it seems to be another problem. 

I had a typing error.  

Seems to be another problem..
