### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by chentadot** [home-assistant/home-assistant.github.io#17687]
### Feedback

I am missing a part usually found in integration documentation called "CONFIGURATION VARIABLES" with all the fields one can configure.

For instance, manual mode is mentiones in the page but not how to set it up.
Found in a community thread that to proper configuration is
`speedtestdotnet:
  manual: true`

In my humble opinion all options and examples should be found in the official doc.

Thanks.

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2021.4.6

**Comment by frenck** [comment]
This integration can only be set up via the UI. All integrations connecting to a device or service, will all be migrated to the UI (in time) and the YAML configurations for setting them up will be removed.

In case an integration exposes UI configuration, the YAML configuration becomes deprecated and should not be used.

Thus there is no information missing in this case.

**Comment by chentadot** [comment]
Such a quick response.
Understood the logic.
Thank you.
