### ISSUE TITLE
KP115 missing power monitoring in first list

### ISSUE THREAD

**Issue by purcell-lab** [home-assistant/home-assistant.github.io#17683]
### Feedback

https://www.home-assistant.io/integrations/tplink#:~:text=KP105-,KP115,-STRIP%20(MULTI-PLUG

KP115 should include standard text about power monitoring.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.4.6

**Comment by rytilahti** [comment]
Feel free to modify the documentation (there is an edit button at the bottom of the page) to account for this.

**Comment by purcell-lab** [comment]
Updated on document link.
