### ISSUE TITLE
Z-Wave names and locations seem to be propagated to HA?

### ISSUE THREAD

**Issue by TheDK** [home-assistant/home-assistant.github.io#17686]
### Feedback

Documentation says names and locations are only visible in HA if stored on device:
https://www.home-assistant.io/integrations/zwave_js/#i-renamed-my-devices-in-z-wave-js-2-mqtt-but-those-names-are-not-visible-in-home-assistant

Interestingly this seems to be working for me for all devices I have. Now, might be all my devices (mainly Fibaro wired switches / dimmer / roller shutter) store this on device. On the other hand, when I request a dump from Z-Wave JS integration it's also in the json file.

Is it possible, that ZWaveJS2MQTT now transfers the names and location to HA in any case so that the documentation is wrong?

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2021.4.6

**Comment by frenck** [comment]
Thanks for reporting this @TheDK 👍 

I've opened up a PR to adjust the documentation
