### ISSUE TITLE
Getting Started is unclear about configuring frontend

### ISSUE THREAD

**Issue by uSpike** [home-assistant/home-assistant.github.io#1768]
As a new HA user, I tried following instructions in the getting-started section.

There's a section titled "Password protecting the web interface", however nothing in the getting-started section mentions how to enable the web interface.  AFAIK, you must include `frontend:` in your `configuration.yaml` for the web interface to show up.  I think it would be helpful to include this on https://home-assistant.io/getting-started/basic/

**Comment by Landrash** [comment]
Feel free to add what you feel is missing @uSpike. There's an edit button on top of each page that let's you submit a pull request.
Somethings you stop seeing after using Home Assistant for a while and those are easier to document for newcomers.

**Comment by fabaff** [comment]
As far as I remember is the frontend  enabled by default. Anyway, we should address the observation by @uSpike with https://github.com/home-assistant/home-assistant.github.io/issues/1603.

**Comment by uSpike** [comment]
@Landrash I created #1779 in case you don't want to handle it in #1603 

@fabaff if you run `hass --open-ui` as the minimal introduction, it creates `~/.homeassistant/configuration.yaml` which contains:

```yaml
# Enables the frontend
frontend:
```
I tested 0.35.3 and the dev branch, both do not expose a frontend without this.

**Comment by uSpike** [comment]
I think there's also a lack of documentation for the `frontend` section.  It's a core component but there's not any documentation for it that I can see, and somewhat confusingly the `http` section controls some aspects of it.

**Comment by balloob** [comment]
Frontend is enabled by default: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/config.py#L52-L53

There is no need to further document it because there is no config for it - it represents the state of the devices and groups as configured throughout the rest of the config.

**Comment by uSpike** [comment]
@balloob I'm sorry, but you're mistaken.  Maybe the frontend **should** be enabled by default, but it **is not** in 0.35.3 and the dev branch.

Simple test case:
* create directory `conf`
* create `conf/configuration.yaml` with contents:
```yaml
homeassistant:
  name: Home Test
  unit_system: imperial
  latitude: 32.87336
  longitude: 117.22743
  elevation: 100
  time_zone: America/Chicago

http:
  api_password: assword
```
* run `hass --open-ui -c conf` and the web browser opens to a page which says only `404: Not Found`

By adding `frontend:` to `conf/configuration.yaml`, the frontend now works as expected.  *This is not documented.*

I think the code that you referenced is the configuration that's written to `~/.homeassistant/confuguration.yaml` when you run `hass` with a config directory without a `configuration.yaml` in it.

**Comment by balloob** [comment]
Home Assistant automatically generates a default config for you with the frontend enabled.

**Comment by balloob** [comment]
If you leave frontend: out of your config, yes, there will not be any frontend. We're not going to make it mandatory beause it means Home Assistant will always require the http server to be running.

**Comment by uSpike** [comment]
> If  you leave frontend: out of your config, yes, there will not be any frontend

I guess that's my issue here.  This is not documented anywhere except the auto-generated configuration file.

**Comment by balloob** [comment]
But it's how the system works. Everything is opt-in.

I think it is a very edge case that someone unfamiliar with Home Assistant will start off by making it's own configuration and so it's not something that I want to add to the getting started guide - it's already too bloated.

**Comment by uSpike** [comment]
I guess I'm an edge case, since that's what I did.  I won't bother you any more, but I do find it strange that the `frontend:` section is not documented anywhere.  I'd expect it to at least be in https://home-assistant.io/components/#other

**Comment by balloob** [comment]
You're right, it should be documented there.
