### ISSUE TITLE
Explain how to install Miiocli

### ISSUE THREAD

**Issue by rschuiling** [home-assistant/home-assistant.github.io#17680]
### Feedback

In the paragraph about 'Retrieving room numbers', the miiocli tool is mentioned. It is unclear how to find, obtain or install this miiocli tool. My suggestion is to explicitly mention this in the docs.

A Discord user mentioned it should not be installed on Home Assistant OS. But to use a separate machine running Python. Then follow the instructions on the offical python-mio website: https://python-miio.readthedocs.io/en/latest/index.html

Perhaps add a sentence: "Miiocli can be installed according to the instructions on the official python-cli website. It is recommended to install it on a separate machine (not in Home Assistant OS)."

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2021.4.6

**Comment by rytilahti** [comment]
If you access the shell in homeassistant os and the (xiaomi miio) integration is installed, miiocli should be available there. It is not an optimal as it requires installing the shell add-on, so I suppose that is why it's not recommended.

Feel free to create a PR to change the documentation though!

**Comment by rschuiling** [comment]
> If you access the shell in homeassistant os and the (xiaomi miio) integration is installed, miiocli should be available there. It is not an optimal as it requires installing the shell add-on, so I suppose that is why it's not recommended.

The miiocli command does not seem to be available for me. Please check out the screenshot. The integration has been installed but miiocli is not available.
![image](https://user-images.githubusercontent.com/27766675/116973455-dc9c6c00-acbc-11eb-87ea-f5cd6e3edab5.png)

**Comment by rschuiling** [comment]
Should I create a separate bug report for this?

**Comment by rytilahti** [comment]
Oh, yes, so this ssh addon is running in a separate container that does not have access to the main system... But yes, I think it'd make sense to document this somewhere, but I'm not sure where. In the documentation of the shell addon?

After asking about this on the discord chat, your options would be to install python-miio outside the homeassistant and use the commands (recommended way), or use a community addon that allows accessing the the main system using `docker exec` after disabling "protection mode". Unfortunately I don't know the details here, so I cannot really help you with that.

**Comment by frenck** [comment]
As of HA 2021.7, this becomes less relevant. As we now have token discovery (by temporary logging into your cloud account).

**Comment by rschuiling** [comment]
The clarification of the way to use the miiocli tool is still equally relevant in HA 2021.7 as it was in previous versions. The token discovery has improved, but finding out your room numbers is unchanged. I would still suggest to improve the documentation.

**Comment by frenck** [comment]
>  I would still suggest to improve the documentation.

Feel free to contribute.

**Comment by rschuiling** [comment]
> > I would still suggest to improve the documentation.
> 
> Feel free to contribute.

Sure did, the pull request is still in limbo (linked above).
