### ISSUE TITLE
Stopped communicating

### ISSUE THREAD

**Issue by 50Pesos** [home-assistant/home-assistant.github.io#17696]
### Feedback

I had the Tesla app running great for weeks and the it had to be reset every 2 minutes. I logged out and tried to log back in and it is not letting me back in. When it kept failing it said failed attempt talpa?

### URL

https://www.home-assistant.io/integrations/tesla/

### Version

2021.4.6

**Comment by frenck** [comment]
Hi there @50Pesos 👋 

It seems like you wanted to report an issue with an integration of Home Assistant, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to fix a bug in an integration, therefore, I suggest you raise an issue on the issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

**Comment by alandtse** [comment]
This is also already patched too. No need to file  a new issue.

**Comment by 50Pesos** [comment]
I apologize if it made it to the wrong destination but that is where the
help link sent me. I would like to disagree that the problem has been
patched, otherwise it would be happening right now and I wouldn't be
sending an email about the difficulties.

**Comment by alandtse** [comment]
It's in dev and waiting for the next release. If you search for this you'll find it was reported 2 weeks ago. If you open a new issue, it will be closed.

**Comment by 50Pesos** [comment]
included is the screenshot from trying reintegrate the application. I know
that my username and password works correctly
