### ISSUE TITLE
AVM FRITZ!Box Tools not available in HA

### ISSUE THREAD

**Issue by provinzio** [home-assistant/home-assistant.github.io#17708]
### Feedback

I can't find the AVM FRITZ!Box Tools integration in home assistant UI. The quick add button in the documentation does not work for me.

I run HA on a raspberry with following versions
- core-2021.4.5
- supervisor-2021.04.3

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.5.0

**Comment by frenck** [comment]
Please upgrade to Home Assistant 2021.5, which added it to the UI.
