### ISSUE TITLE
MotionEye documentation needs more detail

### ISSUE THREAD

**Issue by baronKanon** [home-assistant/home-assistant.github.io#17707]
### Feedback

Hi
There is little explanation on how to integrate MotionEye. I cannot find any explanation to how to integrate the Home Assistant Addon, and the (local) IP address to the Home Assistant instance is not sufficient. Can you please provide some explanation to this?

### URL

https://www.home-assistant.io/integrations/motioneye/

### Version

2021.5.0

**Comment by frenck** [comment]
The add-on is a third-party application and thus how it should be used is not a concern for the Home Assistant documentation.

**Comment by nmsousa76** [comment]
Couple of things.   

1 - Yes 3rd party app, but it would make sense to add some documentation on how to easily integrate with the Motioneye Addon (installed locally on HASS).  Like that we should enable the web interface on the addon.  I am a power user this this took me a bit to figure out.

2- Does the integration support motion detection, or do we still manually need to configure webhooks to make motion work.

**Comment by dermotduffy** [comment]
@nmsousa76 I'm the author of the integration. I think it's reasonable to include documentation on the integration page to help users of the addon to configure the integration correctly. @frenck Does that sound okay to you, or is there somewhere more appropriate for such documentation to live?

@nmsousa76 The motionEye integration in Core today is just stage 1 of moving the functionality from the custom integration (https://github.com/dermotduffy/hass-motioneye) . That custom integration supports motion detection and lots of other features. The plan is to move all of that into Core, it just takes a while to work through the codereview process. Feel free to use the custom integration until then, if you want.

**Comment by dermotduffy** [comment]
I finally got around to setting up hassos in a VM, and installing the motionEye add-on -- and then pointing the motionEye integration at it.

... It all just worked including camera detection and streaming.

URL was simply `http://localhost:28765`

Am I missing some issue? I'll work on a short documentation improvement for the add-on, but if there's some brokenness/difficulty here beyond just knowing the URL, please let me know.

**Comment by frenck** [comment]
This is not an open issue or an issue concerning this add-on. please respect the issue state. Thanks.
