### ISSUE TITLE
Support for wifi smart air sensor

### ISSUE THREAD

**Issue by gabriele-latino** [home-assistant/home-assistant.github.io#17718]
### Feedback

Hi, I'm trying to configure a tuya wifi smart air sensor but the I think the integration doesn't support this item; do you have a chance to add it, please?
Please ask me if you need further info about this device.
Thanks a lot

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.5.0

**Comment by frenck** [comment]
Thank you for reaching out @gabriele-latino 👋 
We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
