### ISSUE TITLE
Configuration failed

### ISSUE THREAD

**Issue by wobeco** [home-assistant/home-assistant.github.io#17714]
### Feedback

the described configuration with 'My button' as well the 'Manual configuration steps' failed on a installation of Home Assistant 2021.3.4 with well accessible SMA converter 'Sunny Tripower 6.0' (german)
Any ideas? Thx

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2021.5.0

**Comment by rklomp** [comment]
> ... a installation of Home Assistant 2021.3.4 ...


Please upgrade to 2021.5.0 to have the GUI config supported

**Comment by kellerza** [comment]
Indeed, please update to the latest version as there are some significant changes and the docs refer to these...

**Comment by wobeco** [comment]
thx for quick response

> Indeed, please update to the latest version as there are some significant changes and the docs refer to these...

done - but: the installation dialoge 'Set up SMA Solar' fails with 'connection failed'-error even the right information (proven at the web-access to the SMA-converter) have been entered, which are IP-adress (xxx.xxx.xxx.xxx), group (installer), password (...)
could the fault be due to the different GUI-languages of the SMA-converter (US vs. german)?
any idea?
