### ISSUE TITLE
Documentation unclear with respect to username configuration

### ISSUE THREAD

**Issue by kongo09** [home-assistant/home-assistant.github.io#17713]
### Feedback

The config flow in the UI asks for a username during configuration. The fritzbox however doesn't necessarily make use of a username. The documentation should explain what to do in this case:

![image](https://user-images.githubusercontent.com/640121/117258408-3cc21800-ae4d-11eb-9c92-e20f0f6e75c4.png)

![image](https://user-images.githubusercontent.com/640121/117258540-5ebb9a80-ae4d-11eb-9555-38b873828665.png)

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.5.0

**Comment by AaronDavidSchneider** [comment]
The default username is `admin`

**Comment by kongo09** [comment]
> The default username is `admin`

The default username doesn't work.

**Comment by kongo09** [comment]
Ok, I figured it out. The fritzbox automatically creates a random username for the admin user as a security measure:

![image](https://user-images.githubusercontent.com/640121/117267464-94b14c80-ae56-11eb-902d-cc47614f1cb5.png)

I'm happy to create a PR for the documentation to reflect this.

**Comment by kongo09** [comment]
This comes down to a change in FRITZ!OS 7.24 as documented here:
https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/Recommendations%20for%20user%20guidance%20for%20logging%20into%20a%20FRITZBox_v1.1_EN.pdf

**Comment by AaronDavidSchneider** [comment]
Thanks for the clarification. Feel free to open up the PR for the documentation.

**Comment by kongo09** [comment]
Reading the documentation by AVM it would actually be more user friendly to autodiscover the admin username. This can be done by calling the URL: http://fritz.box/login_sid.lua?version=2

I'll open a feature request for this.

**Comment by kongo09** [comment]
I just had to find out that I cannot open a FR on github so I added the necessary info for autodiscovery to bug https://github.com/home-assistant/core/issues/47102

**Comment by kongo09** [comment]
Reading-up on this a bit more, I now feel the username shouldn't be a required input field in the first place. The integration uses https://github.com/kbr/fritzconnection to manage connectivity with the FRITZ!Box. If I understand the [_reset_user function](https://github.com/kbr/fritzconnection/blob/b61c3b36819f7e5a82b1dfd0a97989b52007db19/fritzconnection/core/fritzconnection.py#L210) correctly, the library itself figures out the internal username if none is provided. Shouldn't this behaviour cascade down into Home Asssistant?

**Comment by frenck** [comment]
The documentation has been adjusted, thus this issue can be closed.
