### ISSUE TITLE
Scan_Interval

### ISSUE THREAD

**Issue by d3wy** [home-assistant/home-assistant.github.io#17717]
### Feedback

Scan_Interval can't be set from UI, and attempting to set it in configuration.yaml comes up with a list of errors relating to the integration not being correctly configred. Clearer instructions for setting scan_interval from UI are required.

### URL

https://www.home-assistant.io/integrations/google_travel_time/

### Version

2021.5.0

### Additional information

https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval May require updating also?

**Comment by frenck** [comment]
You can't set the scan interval for Google Travel Time, thus it isn't documented either.
