### ISSUE TITLE
Mutesync integration Host parameter

### ISSUE THREAD

**Issue by bourliam** [home-assistant/home-assistant.github.io#17719]
### Feedback

Hi ! I was trying to set up the mutesync integration but it was asking for a "host" parameter and I have no clue what it is or where i can find it.

Would be nice to talk about it in the documentation !

Thanks for the awesome work !

### URL

https://www.home-assistant.io/integrations/mutesync/

### Version

2021.5.0

**Comment by frenck** [comment]
The IP address or hostname that runs the MuteSync application you want to connect to.

**Comment by frenck** [comment]
Considering your PR, it seems you have figured out what it entails. Therefore closing the issue on this end.
