### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vanegmont** [home-assistant/home-assistant.github.io#17729]
### Feedback

I'm not sure if this is possible with the Tuya API, but are their plans, or is it possible to add the ability to read the power usage from their devices with this capability?

Thanks for your time and effort!

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.5.0

**Comment by ollo69** [comment]
Unfortunately the Tuya API used by HA (that are dedicated but not maintained anymore by Tuya) do not provide this information.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
