### ISSUE TITLE
Control panel clarification for JS server, and behavior when leaving supervised check box, and associations

### ISSUE THREAD

**Issue by yelkenli1** [home-assistant/home-assistant.github.io#17725]
### Feedback

The paragraph "Running the Z-Wave JS Server" indicates there is a control panel for Z-wave JS, but my understanding is that is only via zwaveJS2mqtt.  Or, it should be clarified exactly what the control panel is (e.g. does not include the ability to make associations and update firmware)

> The Z-Wave network can be configured via the built-in Z-Wave JS control panel in Home Assistant.

This could be rewritten as 

> The Z-Wave network can be configured via the control panel available through zwaveJS2mqtt in Home Assistant.  you must follow the procedures for zwaveJS2mqtt with the JS add-on for this to be available. 
or 
> The Z-Wave network can be configured for the security key and device location via the built-in Z-Wave JS add-on control panel in Home Assistant.  

The second point is the [inability to stop the JS add-on](https://community.home-assistant.io/t/z-wave-js-won-t-stop-running-when-stopped/305416).  I learned this recently and on the HASS forum, I was told that if the 'supervised' checkbox is checked, the supervisor will restart the add-on (which in my system occurs immediately).  If this is not true, please let me know. something is wrong with my system.  If this is true, I recommend adding a warning.  Maybe this is a 'who cares' though.  It does not seem to have impacted my system.  

Lastly, I see in the [development tracker](https://github.com/zwave-js/node-zwave-js/issues/6) that associations are complete in JS.  Can some instruction be provided on how to do this?  or are these complete in zwaveJS2mqtt?  If the latter, the page should give instructions to load zwaveJS2mqtt (and prior to JS, as configuring the zwaveJS2mqtt with JS appears to require deleting an existing JS integration and add-on (this might not be correct, but the only information I can find - in the forums and on youtube - indicate this is necessary).  

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2021.5.0

**Comment by frenck** [comment]
> The paragraph "Running the Z-Wave JS Server" indicates there is a control panel for Z-wave JS, but my understanding is that is only via zwaveJS2mqtt.

This is incorrect.

![image](https://user-images.githubusercontent.com/195327/117304317-e6b99880-ae7d-11eb-8f6f-eb8dd6f7b62a.png)


![image](https://user-images.githubusercontent.com/195327/117304335-eae5b600-ae7d-11eb-8b8e-49504c62778d.png)


Futhermore, each device exposes a control panel as well:

![image](https://user-images.githubusercontent.com/195327/117304369-f76a0e80-ae7d-11eb-97f7-92e4e6cd8acd.png)

![image](https://user-images.githubusercontent.com/195327/117304382-fafd9580-ae7d-11eb-8d62-3edf9c49b628.png)

For the other cases, it seems like you want to do a suggestion or feature request, for that, please use the community forums, as we have a feature request section there.

Thanks! 👍

**Comment by yelkenli1** [comment]
Thanks @frenck 
I can put in a request for new features: one is the ability to stop Z-wave JS add-on in HA.  The other is to be able to set direct associations.  Is the community forum the [HA community forum](https://community.home-assistant.io/), tag with z-wave?
