### ISSUE TITLE
This Integration is currently broken

### ISSUE THREAD

**Issue by mct370770** [home-assistant/home-assistant.github.io#17728]
### Feedback

I am using this configuration.yaml (only the wirelesstag parts are shown)
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
#        - 192.168.1.248
#      trusted_users:
#      - 192.168.1.248: 89d3c53eec8f4ae993535dfe3e98e6e7
#      allow_bypass_login: true

wirelesstag:
 username: x@y.z
 password: xyzxyz

binary_sensor:
  - platform: wirelesstag
    monitored_conditions:
      - presence
      - light
      - battery

sensor:
  - platform: wirelesstag
    monitored_conditions:
      - temperature
      - humidity

switch:
  - platform: wirelesstag
    monitored_conditions:
      - temperature
      - humidity
      - light
   
But I am not able to get the remarked lines to work
It goes to safe mode and claims invalid config each time I try ......

And I am in Home Assistant getting notifications all the time with: "Login attempt or request with invalid authentication from 192.168.1.248 (192.168.1.248). See the log for details." (My Wireless Manager is on IP 192.168.1.248).
The log details are: Logger: homeassistant.components.http.ban
Source: components/http/ban.py:116
Integration: HTTP (documentation, issues)
First occurred: 3:23:29 PM (195 occurrences)
Last logged: 6:51:16 PM
Login attempt or request with invalid authentication from 192.168.1.248 (192.168.1.248). (None)

### URL

https://www.home-assistant.io/integrations/wirelesstag/

### Version

2021.5.0

**Comment by frenck** [comment]
Hi there @mct370770 👋 

It seems like you are trying to report an issue with an Home Assistant integration, however, you have submitted documentation feedback. There is no amount of documentation I can adjust to bugfix an integration. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks!

../Frenck 🚂
