### ISSUE TITLE
how do i add !secret to SSH or samba or ftp it states invalid yaml 

### ISSUE THREAD

**Issue by vjmaz** [home-assistant/home-assistant.github.io#17724]
### Feedback

how do i add !secret to SSH or samba or ftp it states invalid yaml 
someone show a sample please 

### URL

https://www.home-assistant.io/more-info/pwned-passwords/

### Version

2021.5.0

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
