### ISSUE TITLE
customize entity

### ISSUE THREAD

**Issue by beajohnstone** [home-assistant/home-assistant.github.io#17737]
### Feedback

Would it be possible to add customize_integration: as an option to select entities to add customizations to?

I am looking for a way to select entities created by DeConz so I can add additional attributes not currently created by that integration.  I would also want to use the feature with other integrations as I expand my Home Assistant configuration.

Thank you for a superb project

Brian Johnstone

### URL

https://www.home-assistant.io/docs/configuration/customizing-devices/

### Version

2021.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
