### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by AriaGen** [home-assistant/home-assistant.github.io#17730]
### Feedback

Hi,

Not really an issue per say, more a FYI. Followed the guide to create my own Alexa Skill to incorporate, found that it was missing vital information, after several days of messing around, I found that the skill will only link once I was running my instance on port 443, it wouldn't even work with port forwarding enabled on my router.

I don't know if this would be the same for everyone, but I'm in the UK and and it's what I had to do to get alexa to link successfully. 

### URL

https://www.home-assistant.io/integrations/alexa.smart_home/

### Version

2021.5.0

**Comment by frenck** [comment]
I don't want to be a douchebag, but it is the first line in the requirements actually:

![image](https://user-images.githubusercontent.com/195327/117584637-62ca0f80-b10e-11eb-91e7-a3c733aec6ab.png)

**Comment by AriaGen** [comment]
Nope, that's fair. Please accept my apologies, I missed that somehow...  

    On Sunday, 9 May 2021, 20:35:09 BST, Franck Nijhof ***@***.***> wrote:  
 
 


I don't want to be a douchebag, but it is the first line in the requirements actually:
