### ISSUE TITLE
How to test for condition of an input_boolean 

### ISSUE THREAD

**Issue by philipmjones** [home-assistant/home-assistant.github.io#17751]
### Feedback

Please can you provide further clarification or an example of how to use a condition which tests the state of a boolean input.

The documentation is very clear about numerical inputs and how to test for values above and/or below certain thresholds. However there is no guidance on how to test whether a boolean is on or off.

I guess it may be done using a State condition, but what are the accepted values? 0? 1? -1? TRUE, true, "true", etc.? 

I've tried experimenting but not worked it out. Please can someone who knows this stuff please capture their knowledge in a small update here?

Many thanks in advance from a struggling newbie!

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2021.5.1

**Comment by frenck** [comment]
> "on" and "off"

For any entity, any integration, check the current values:

![image](https://user-images.githubusercontent.com/195327/117556235-fba55000-b066-11eb-9df9-bd8ec7d4f37d.png)

Check your own states:
[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)


This does not apply to conditions, but about everything in Home Assistant. State conditions no different for input_booleans.
