### ISSUE TITLE
Update demo

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/home-assistant.github.io#1776]
I can't seem to find documentation on how the demo on the homepage is created. It is currently displaying version 0.26. I guess it's not based on a real running hass instance?

It would make sense to display more components. There are a lot of really nice examples shared on github, so maybe the community can agree on a demo site that is nice looking and tries to show as much as possible what Home Assistant can do.

Ideally, updating should be easy and could be tied to the release procedure, so the demo is always up to date?

**Comment by JammyDodger231** [comment]
I have not been through the source code of the demo myself, however I think the main reason why it is not kept up to date is that some components need an actual platform to communicate with, if it does not then it won't work properly. Also I think it may be simple because the components that are on there, most people will want to use.

**Comment by balloob** [comment]
The demo data can be found here: https://github.com/home-assistant/home-assistant-polymer/tree/master/demo_data

I have tried to have the demo keep a balance between showcasing what we do without being overwhelming. Having too many components might become slow or will be too overwhelming, and a person will not be able to remember anything.

**Comment by balloob** [comment]
And honestly, since v0.26, we haven't changed much to how it all looks. We have always looked good ;-)

**Comment by bdurrer** [comment]
I think the thing with the version is mostly psychology. If you see the product for the first time and realize the demo is several versions old, it looks like its inactive or something.... regardless of how awesome it really is ;-)
Fake the version? (I am joking!)

**Comment by Landrash** [comment]
@balloob How do you feel about updating the demo now that there's a few more panels and functions?

**Comment by balloob** [comment]
I first want to finish our migration to Polymer 2.
