### ISSUE TITLE
Implies that command can be sent to microft, not just a notification

### ISSUE THREAD

**Issue by kstewart-lab** [home-assistant/home-assistant.github.io#17773]
### Feedback

<quote>
message: "Hey Mycroft. Turn on the office light. "
</quote>

The microft integration can only have mycroft speak the message, not execute a command. 

### URL

https://www.home-assistant.io/integrations/mycroft/

### Version

2021.5.1

**Comment by kbridger** [comment]
Agreed I found this statement misleading when setting it up for the first time.  Suggest an example that isn't like a command, and omits the trigger word etc.  Examples:

- "Good morning.  It is 8am so your lights will be turned on."
- "I sense a change in the force.  Your Dad must be home."
