### ISSUE TITLE
THis seems not to work anymore? 2021.1.5

### ISSUE THREAD

**Issue by WeterPeter** [home-assistant/home-assistant.github.io#17796]
### Feedback

I am trying to add the Integration but I get a blank page with: 404: Not Found

HA version: 2021.1.5

### URL

https://www.home-assistant.io/integrations/lyric/

### Version

2021.5.2

**Comment by klaasnicolaas** [comment]
Hi there @WeterPeter 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix a bug in the code.

Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

Klaas
