### ISSUE TITLE
REST sensor pages missing scan_interval parameter info

### ISSUE THREAD

**Issue by ChrisRomp** [home-assistant/home-assistant.github.io#17797]
### Feedback

The REST component pages all show a `scan_interval` parameter in their examples, but fail to document it in the parameters list.

1. [RESTful](https://www.home-assistant.io/integrations/rest)
2. [RESTful Binary Sensor](https://www.home-assistant.io/integrations/binary_sensor.rest)
3. [RESTful Sensor](https://www.home-assistant.io/integrations/sensor.rest)

I'm checking the code to confirm it's in seconds, and I'll submit a PR for this.

### URL

https://www.home-assistant.io/integrations/rest

### Version

2021.5.2

**Comment by ChrisRomp** [comment]
Looking at the source for core and some testing, it looks like the default value for `scan_interval` is 15 seconds for the REST component, and 30 seconds for the sensor and binary sensor components.  If this isn't correct I can fix it in the docs.

**Comment by frenck** [comment]
`scan_interval` is a generic platform option, not specific to the rest platforms. It is documented here: <https://www.home-assistant.io/docs/configuration/platform_options#scan-interval>

**Comment by ChrisRomp** [comment]
But where would a user find the default values for these components, other than looking at the source?
