### ISSUE TITLE
Setup a service for HA core

### ISSUE THREAD

**Issue by tdigu** [home-assistant/home-assistant.github.io#17803]
### Feedback

I get that this is for advanced users and many would probably look up or otherwise know how to do this.
However for the core install section it would be more useful to also have instructions on setting up HA core as a service to start automatically. Running the script it only runs as long as you have the ssh session open and at that prompt. 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.5.2

**Comment by frenck** [comment]
> I get that this is for advanced users and many would probably look up or otherwise know how to do this.

There are many permutations on how this should be done and can be done in many different ways as well. In the past, we ended up with many variants for different versions, distributions and/or init managers. Therefore, we have decided not to provide those, as we assume this is not a problem for the target audience of this installation method.

Nevertheless, thanks for the feedback 👍
