### ISSUE TITLE
EZVIZ Cam Wakeup

### ISSUE THREAD

**Issue by roliestermann** [home-assistant/home-assistant.github.io#17819]
### Feedback

Dear Developer
Thanks a lot for the integration. I worked before with the custom_component Ezviz_cloud, which was adding similar functionality. In this integration, there was also a service integrated to 'wake up' the camera, if it is in sleep mode.
Would it be possible to auto add this functionality, if I add a camera pic or live pic to via a card into the Lovelace dashboard? So, as soon as the camera pic should be loaded, the camera would be waken up automatically and the picture or stream will be refreshed?
Thanks a lot, Best Regards
Roli

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.5.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
