### ISSUE TITLE
HomeKit sprinkler support

### ISSUE THREAD

**Issue by kukacwap** [home-assistant/home-assistant.github.io#17813]
### Feedback

Hey,

im new to HA, and glad to see this integration available. As I use HomeKit as my main interface for the integration can this be shown as a sprinkler? Right now it tells it is a regular switch.

thanks

### URL

https://www.home-assistant.io/integrations/rainbird/

### Version

2021.5.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
