### ISSUE TITLE
Ive just added this elsewhere on HA Community:

### ISSUE THREAD

**Issue by orandaadnaro** [home-assistant/home-assistant.github.io#17817]
### Feedback

Ive just added this elsewhere on HA Community:
https://community.home-assistant.io/t/uk-envionment-agency-near-realtime-rainfall-monitor/307641

Please let me know if merging with your integration could/would be possible

### URL

https://www.home-assistant.io/integrations/eafm/

### Version

2021.5.3

**Comment by frenck** [comment]
Hi there @orandaadnaro 👋 

I'm not sure about your suggestion or question here? You've left documentation feedback on the eafm integration, but I think your message isn't related to that?

What is it you think that should be adjusted to that page?

../Frenck 🚂
