### ISSUE TITLE
log purging

### ISSUE THREAD

**Issue by InscapeM** [home-assistant/home-assistant.github.io#17818]
### Feedback

Could you please provide concise information on how to clean up the logs as it is growing at an incredible rate. 
I would this most people would find this handy rather than having a time bomb to system failure.

Thanks heaps

### URL

https://www.home-assistant.io/integrations/logger/

### Version

2021.5.3

### Additional information

I have looked everywhere, found a lot of confusion online and can not find clear instruction on how to do this.

Thank you

**Comment by frenck** [comment]
Why is the log "growing at an incredible rate"? That sounds bad, is there something flooding your logs?

**Comment by InscapeM** [comment]
Thanks mate for the amazingly fast response... I would not be surprised if
there are all sorts of issues as I am trying to learn this and I am finding
more issues that wins... are you able to provide any info on how to manage
these logs before it just clogs up and stops working? I have been looking
around and people are just throwing around one liners of code and i can not
find what to do with it.

Thanks again

**Comment by frenck** [comment]
So, the treason I ask this question, is that it should not be needed.
You are asking for a workaround instead of solving the problem. What is filling your logs? Solve that.

**Comment by InscapeM** [comment]
yes i understand,
it could be the hundreds of events  like this
I have lost 1 gb alone in the last hour

Google-Home-Mini Uptime changed to 2021-05-13T17:21:38.674870+10:00
8:42:53 PM - 51 seconds ago
ESP_3E0544 Uptime changed to 2021-04-29T21:17:31.674404+10:00
8:42:53 PM - 51 seconds ago
shellymotionsensor-60A423960928 Uptime changed to
2021-04-29T21:18:00.673909+10:00
8:42:53 PM - 52 seconds ago
Electric Blanket Uptime changed to 2021-04-29T21:17:31.673297+10:00
8:42:53 PM - 52 seconds ago
Uptime changed to 2021-04-29T21:17:31.672847+10:00
8:42:53 PM - 52 seconds ago
Chicken Door Uptime changed to 2021-05-13T17:22:05.672390+10:00
8:42:53 PM - 52 seconds ago
Amp Uptime changed to 2021-04-29T21:17:31.671892+10:00
8:42:53 PM - 52 seconds ago
ESP_4329EB Uptime changed to 2021-05-13T18:50:38.671251+10:00
8:42:53 PM - 52 seconds ago
Google-Nest-Hub-Max Uptime changed to 2021-05-13T02:20:22.670789+10:00
8:42:53 PM - 52 seconds ago
Uptime changed to 2021-04-29T21:15:39.271897+10:00
8:42:39 PM - 1 minute ago
unifi 90 02 a9 4f 21 9f default was detected at home
8:42:39 PM - 1 minute ago
Storage Uptime changed to 2021-04-29T21:15:24.260234+10:00
8:42:39 PM - 1 minute ago
Uptime changed to 2021-05-13T15:37:50.256464+10:00
8:42:39 PM - 1 minute ago
Storage was detected at home
8:42:29 PM - 1 minute ago

**Comment by frenck** [comment]
We don't log state changes, have you changed the logging settings? Or do you run something for uptime detection or something?

**Comment by InscapeM** [comment]
nothing for uptime just the defaults...what i have been trying to get home
assistant to message me when i join the unifi wifi and a different message
when i leave it, but that was a coupe of days ago still no joy.
 all i did was upgrade to Home Assistant 2021.5.3 from Home 2021.5.2

**Comment by InscapeM** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:124
Integration: Home Assistant WebSocket API (documentation
<https://www.home-assistant.io/integrations/websocket_api>, issues
<https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22>
)
First occurred: 8:50:17 PM (2 occurrences)
Last logged: 8:59:56 PM

   - [547359389296] Client unable to keep up with pending messages. Stayed
   over 512 for 5 seconds
   - [547647182640] Client unable to keep up with pending messages. Stayed
   over 512 for 5 seconds

**Comment by frenck** [comment]
Seems like you have something that hammers Home Assistant really hard...
The only way to figure that out is by slowly disabling/enabling things until you find the culprit.

**Comment by InscapeM** [comment]
Thanks mate, i will try it...
can you please tell me how to empty the logs so I dont have to race the
clock.

**Comment by frenck** [comment]
delete it?

**Comment by InscapeM** [comment]
I want to clear the log files to make room before the drive fills up. I am
sure it will continue to create more for purposes of diagnosis

**Comment by frenck** [comment]
> I want to clear the log files to make room before the drive fills up

Yes, I get that, delete the log file or truncate it.

**Comment by InscapeM** [comment]
ha, yes mate, how do i do that?

**Comment by frenck** [comment]
click it and delete the file? 😄 
I'm not sure what instruction on file management you'll need 😕

**Comment by InscapeM** [comment]
Thank you Franck, I have deleted the database, I assume that is all is
required.

 I really appreciate your patience and support.

Thank you
Michael
