### ISSUE TITLE
Denon "plays" but isnt playing

### ISSUE THREAD

**Issue by jensorium** [home-assistant/home-assistant.github.io#17829]
### Feedback

Hey
core-2021.5.1
spotify 0.8.2 
Spotcast 3.5.8
DENON AVR X 4000

Not sure wheter Im right here or not. If not: Please tell me where i had to ask for help.

i wrote a node red flow wich tells spotify to start a playlist and shuffles. Shuffle made some problems first as it has to be `{"shuffle":"true"}` with the quotation marks, the documentation and the node red says without and spotify wouldnt be supported, happy it is :)

Normally everything works fine, but sometimes it doesnt. Like today: I was watching Chromecast and told spotify to play, Nothing happened, when i looked into Spotify it told me: Playing on Denon. I had this problem sometimes. Any Idea?

Greets
Jens

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2021.5.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
