### ISSUE TITLE
Nuki Integration

### ISSUE THREAD

**Issue by remirr** [home-assistant/home-assistant.github.io#17823]
### Feedback

Instead of having to use the Bridge API to connect to the Nuki Devices, can we use the web.nuki.io API calls instead? This would allow us to access not only the lock but also the opener etc. 

### URL

https://www.home-assistant.io/integrations/nuki/

### Version

2021.5.3

**Comment by frenck** [comment]
Hi there @remirr 👋 

Thanks for your message, however, it seems like you want to report a bug? Or a feature request? I'm not sure. Anyways, this is the feedback/issue tracker for the documentation but your message is not documentation related.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you want to report an issue with a integration provided by Home Assistant, go here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
