### ISSUE TITLE
Setup device tracker link for platform "fritz" is outdated

### ISSUE THREAD

**Issue by brlnr23** [home-assistant/home-assistant.github.io#17824]
### Feedback

The link at the end of the page 
> See the device tracker integration page for instructions how to configure the people to be tracked.
is slightly outdated. Setting this up via configuration.yaml for a FritzBox leads to log warnings & errors, stating that the configuration of the integration need to be done in the UI. 

It would be great to list the configuration options on the page directly (e.g. how to define the `consider_home` and `interval_seconds`). But maybe this piece of configuration is missing in the integration anyways?

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.5.2

**Comment by chemelli74** [comment]
Hi @brlnr23 , thx for the feedback!

- `interval_seconds` is fixed in 30s
- `consider_home` is indeed missing, will try to code during this week.

Simone

**Comment by chemelli74** [comment]
`consider_home` is going to be added (see https://github.com/home-assistant/core/pull/50741 and #17854 ).

Simone

**Comment by chemelli74** [comment]
The link to the old device tracker should now be removed. Will update current PR to fix this.

Simone

**Comment by chemelli74** [comment]
Link removed
