### ISSUE TITLE
Select Nest Home During Device Setup

### ISSUE THREAD

**Issue by CamronWalker** [home-assistant/home-assistant.github.io#17835]
### Feedback

Step 3 of Device Setup could use an update to remind people that if they have multiple homes with nest devices connected to them this is where they select a home.
<img width="658" alt="Device Home Selection" src="https://user-images.githubusercontent.com/30887472/118311635-66162000-b4ad-11eb-861b-3b20a801d46e.png">

3 hours of Googling I hope to help someone else avoid (trying to figure out why some entities were missing).

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.5.3

**Comment by allenporter** [comment]
Still relevant

**Comment by allenporter** [comment]
Valid issue

**Comment by allenporter** [comment]
One other thing I noticed when testing: you can select devices across multiple homes and they all get added to home assistant. That is pretty nice.
