### ISSUE TITLE
Fronius Watpilot 

### ISSUE THREAD

**Issue by tim-ad08** [home-assistant/home-assistant.github.io#17834]
### Feedback

Hi,
Is there a plan for the Watpilot from fronius?

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2021.5.3

### Additional information

Watpilot

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by nielstron** [comment]
Hi,

I don't know what the watpilot is or where it is used :) However if this is about functionality provided by fronius devices, feel free to provide more details and post an issue over at https://GitHub.com/nielstron/pyfronius . If this is something independent I also recommend the community forum.
