### ISSUE TITLE
Configuration section does not explain what the URL field should be

### ISSUE THREAD

**Issue by Charli181** [home-assistant/home-assistant.github.io#17830]
### Feedback

What shoudl theURL field be. I am assuming the usernames and passwords are the mitoneye credentials. I ahve the MotionEye Add-On installed so not sure what the URL should be.

### URL

https://www.home-assistant.io/integrations/motioneye/

### Version

2021.5.3

**Comment by dermotduffy** [comment]
See: https://github.com/home-assistant/core/issues/50409

Lets close this bug as duplicate. I'll get proper instructions added for the add-on once I have the setup to experiment (I'll be using that other bug to track/report progress).

**Comment by frenck** [comment]
Documenting the addon is not a concern for the core documentation, but for the addon documentation.

**Comment by dermotduffy** [comment]
@frenck SGTM. I can work on the doc improvement, you tell me where you want it.

I am guessing this is where you want it: https://github.com/hassio-addons/addon-motioneye/blob/main/motioneye/DOCS.md

**Comment by dermotduffy** [comment]
@Charli181 Can you close this bug? Lets track progress at https://github.com/home-assistant/core/issues/50409 , so we're not bug-polluting.

Thanks.

**Comment by frenck** [comment]
Closing this issue on this end, as it is not a concern for the Home Assistant documentation.
