### ISSUE TITLE
FortiOS integration stops after upgrade to 7.0.0

### ISSUE THREAD

**Issue by FreekBos** [home-assistant/home-assistant.github.io#17838]
### Feedback

Hi,
Upgraded to FortiOS 7.0.0 (from 6.4) and integration broke down.

log (parameter verify_ssl produce identical results): 
2021-05-15 10:24:30 ERROR (SyncWorker_3) [homeassistant.components.fortios.device_tracker] Failed to login to FortiOS API: HTTPSConnectionPool(host='192.168.61.10', port=8080): Max retries exceeded with url: /api/v2/monitor/license/status?global=1 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))
2021-05-15 10:24:30 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy fortios

configuration.yaml
# Firewall Integration for Device Tracking
device_tracker:
  - platform: !secret fw_platform!
    host: !secret fw_ip_and_port!
    token: !secret fw_token!
    verify_ssl: false
    interval_seconds: 60

Anyone an idea?
Thanks a million in advance.

### URL

https://www.home-assistant.io/integrations/fortios/

### Version

2021.5.4

**Comment by frenck** [comment]
Hi there @FreekBos 👋 

It seems like you want to report an issue with an integration, however, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix that issue.

If you experience an issue with an integration, please submit an issue to this issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck 🚂

**Comment by kimfrellsen** [comment]
FortiOS 7.0.0 support will be available in the next release of the integration. Code is complete and tested it just need to make a pull request and update documentation.

**Comment by FreekBos** [comment]
@kimfrellsen Wonderful and thanks a million for your response. I was going crazy finding out what I'd done wrong ;-)
I'll be waiting for the update and feed you back upon its installation.
Again, thanks so much!
