### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by jbesclapez** [home-assistant/home-assistant.github.io#17847]
### Feedback

Hello,
This is not working when the Toon is rooted and with ToonStore.
I am using the older Toon.
Please could you give us a workaround?
Thanks

### URL

https://www.home-assistant.io/integrations/toon/

### Version

2021.5.4

**Comment by frenck** [comment]
The documentation states:

> For the Toon integration to work, you’ll need an active Toon subscription and a Toon API developer account.


That is not available on a rooted toon, thus you can't use this integration.
