### ISSUE TITLE
Documentation link requires login/sign up for a Hue Development account

### ISSUE THREAD

**Issue by skipishere** [home-assistant/home-assistant.github.io#17845]
### Feedback

The documentation mentions the use of [Hue Color Chart](https://developers.meethue.com/documentation/core-concepts#color_gets_more_complicated) but when clicked, this requires the person to have signed up for a developer account with Philips Hue (which is far from idea if a person just wants to look at the chart).

Ideally Philips wouldn't have it behind a sign-up wall, but alternatively either a better link (or a copy of the information that doesn't need signing up for) should be provided.

### URL

https://www.home-assistant.io/integrations/light/

### Version

2021.5.4

**Comment by frenck** [comment]
There is not much we can do about that, we can remove the login from Philips their end and we don't want to host their documentation.

Nevertheless, thanks for providing feedback 👍
