### ISSUE TITLE
Templates page doesn't mention where in home assistant interface to define templates

### ISSUE THREAD

**Issue by cooldome** [home-assistant/home-assistant.github.io#17844]
### Feedback

The page doesn't say where in the home assistant interface to define these template. Answer can't be googled either.

### URL

https://www.home-assistant.io/integrations/template/

### Version

2021.5.4

**Comment by frenck** [comment]
Thanks, let's make that more clear indeed. It is in your YAML configuration file (e.g., configuration.yaml). 

This is not available via the UI
