### ISSUE TITLE
Scripts created in the GUI don't get a unique ID, so cannot be deleted in the GUI

### ISSUE THREAD

**Issue by jj-uk** [home-assistant/home-assistant.github.io#17846]
### Feedback

When creating a script in the GUI, the script is not assigned a unique ID. As a result, it cannot be deleted by using the GUI.

Create a script in the gui.
In "scripts" list, click (information) -> (gear icon).

This is different to automations created in the gui, which can be deleted in the gui.

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2021.5.4

**Comment by frenck** [comment]
Hi there @jj-uk 👋 

It seems like you want to report an issue, however, you have submitted documentation feedback.
If you want to report an issue with the Home Assistant Core, please report an issue here:

<https://github.com/home-assistant/core/issues>

In case, you want to report an issue with the UI/Frontend, please report an issue here:

<https://github.com/home-assistant/frontend/issues>

../Frenck
