### ISSUE TITLE
Support for additional features?

### ISSUE THREAD

**Issue by Boulliebeest** [home-assistant/home-assistant.github.io#17855]
### Feedback

Hey all

Would love to be able to implement all features of Niko Home Control.
Not only lights, but also blinds, garage door openers, etc... which are all supported by NHC.

### URL

https://www.home-assistant.io/integrations/niko_home_control/

### Version

2021.5.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
