### ISSUE TITLE
Homekit - Categories for TV Media Player

### ISSUE THREAD

**Issue by Hatika78** [home-assistant/home-assistant.github.io#17850]
### Feedback

The Homekit integration works like a charm and thanks a lot for the work.
But do you think it's possible to add different categories to TV media player accessories, like Speaker or Audio receiver ?

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2021.5.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
