### ISSUE TITLE
File checksums

### ISSUE THREAD

**Issue by tolga-balci** [home-assistant/home-assistant.github.io#17853]
### Feedback

Hello,

Can you please also mention the checksums for the HomeAssistant files?

Thank you!

### URL

https://www.home-assistant.io/installation/

### Version

2021.5.4

**Comment by frenck** [comment]
We don't have those (yet) thus not listed at this point. We do sign our docker containers with codenotary. Hopefully it is something we can make part of the release procedure in the future.

../Frenck
