### ISSUE TITLE
This page confuses the issue of "Devices" vs "Entities" and seems to use them interchangeably

### ISSUE THREAD

**Issue by drphungky** [home-assistant/home-assistant.github.io#17865]
### Feedback

The page title is about adding "devices" to HA, but walks through adding entities. It then switches terms again about halfway through.

### URL

https://www.home-assistant.io/docs/configuration/devices/

### Version

2021.5.4

**Comment by frenck** [comment]
A device can provide one or more entities. I do agree it is kinda confusing on this page.

**Comment by drphungky** [comment]
> A device can provide one or more entities. I do agree it is kinda confusing on this page.

Right, I think I understand the concepts, but they're not explained well here. I was actually looking into how to add a device rather than adding entities, but it looks like I can't unless I use MQTT discovery or use an integration that happens to provide a device rather than an entity.

...on the other hand, if I _can_ add a device manually somehow, then that should probably be outlined here.

**Comment by frenck** [comment]
You can define a device with MQTT.

See: https://www.home-assistant.io/integrations/switch.mqtt#device

**Comment by drphungky** [comment]
Well that's sort of a separate issue than this documentation issue, but yes I know how to do it with MQTT. I haven't able to make a device out of entities, like from ESPHOME, or even just generically in the config file. Like instead of my template cover being a device, it's an entity that calls entities for its various functions...which I doubt is probably the preferred hierarchy.

Of course, while that's sort of a separate issue, it _is_ why I was looking at the documentation for devices in the first place.

**Comment by frenck** [comment]
>  like from ESPHOME, or even just generically in the config file

That is a per integration thing, and not general. Integrations can provide devices, they don't have too.

In ESPHome each ESPHome instance is a device already.

Additionally, an entity doesn't have to have a device represented in Home Assistant. It is not the hierarchy you are looking for I guess.

**Comment by drphungky** [comment]
> Additionally, an entity doesn't have to have a device represented in Home Assistant. It is not the hierarchy you are looking for I guess.

So I guess that brings us back to this page:  What is the point of a device and how does it differ from an entity? And more importantly for this page, if I have a real world device made up of a bunch of entities, how do I make that device in home assistant (short of designing my own integration, or having a microcontroller send out MQTT discovery JSON packets)?

**Comment by frenck** [comment]
A device has not state, an entity has.

Devices have some additional information (like firmware version and that kind of stuff), and group entities. Furthermore, it allows for device automation via the UI.

**Comment by MichaelNMaggs** [comment]
I agree with the original comment. The existing wording on this page seriously confused one new user (me).

**Comment by drphungky** [comment]
The referenced page still conflates the two concepts. It's probably easier to call it, "How to add entities", and change very little. Then a page about how integrations add devices, which are made up of entities. This confused me for months when I was new - it definitely needs fixed in the intro documentation.
