### ISSUE TITLE
Add extra sensor entities

### ISSUE THREAD

**Issue by DanielV88** [home-assistant/home-assistant.github.io#17863]
### Feedback

On https://www.arcgis.com/apps/dashboards/bda7594740fd40299423467b48e9ecf6 there are also numbers / graphs available for the following:

- Daily Cases
- Daily Deaths
- Total Vaccine Doses

Is it possible to add these to the integration? 

### URL

https://www.home-assistant.io/integrations/coronavirus/

### Version

2021.5.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
