### ISSUE TITLE
Add a clarification on brand names?

### ISSUE THREAD

**Issue by nbeernink** [home-assistant/home-assistant.github.io#17868]
### Feedback

It was a unclear to me if this integration could also be used to control by Luxaflex Powerview.  After some research it turns out Hunter Douglas is a brand used in America and Luxaflex is primarily used in Europe.  Same technical product, different brand names.

https://www.hunterdouglasgroup.com/company/brands-in-action/

Would it be a good idea to include a note about this on the integration page? Could save others some research time. :)

### URL

https://www.home-assistant.io/integrations/hunterdouglas_powerview/

### Version

2021.5.4

**Comment by bdraco** [comment]
Would you post how the device looks with the following so we can see if we need to update discovery:

`pip3 install netdisco`
`python3 -m netdisco dump`

and

`git clone https://github.com/bdraco/aiodiscover`
`cd aiodiscover`
`pip3 install --upgrade .`
`python3 demo.py`

Thanks!

**Comment by nbeernink** [comment]
Will do that as soon as the covers are hanging on the window sills. Might
take a couple of weeks though. 😁

**Comment by nbeernink** [comment]
> Would you post how the device looks with the following so we can see if we need to update discovery:
> 
> `pip3 install netdisco`
> `python3 -m netdisco dump`

```
$ python3 -m netdisco dump
Discovered devices:
homekit:
[{'host': '192.168.xx.xx',
  'hostname': 'PowerView-Hub.local.',
  'name': 'PowerView Hub',
  'port': 7766,
  'properties': {'c#': '21',
                 'ci': '2',
                 'ff': '1',
                 'id': 'xx:xx:xx:xx:xx',
                 'md': 'PowerView Hub 2.0',
                 'pv': '1.1',
                 's#': '1',
                 'sf': '3',
                 'sh': 'GF7czQ=='}}]
```


> `git clone https://github.com/bdraco/aiodiscover`
> `cd aiodiscover`
> `pip3 install --upgrade .`
> `python3 demo.py`

This just shows the powerview hub's hostname, ip and mac-address. 

It's really just a rebrand for the dutch (or maybe european? market) where it's called Luxaflex instead of Hunter Douglas. 

I used this powerview integration to add our Silhouette Shades. They're controllable except for the tilt function. That's the only thing that seems to be missing at the moment.

**Comment by nbeernink** [comment]
@bdraco, is the above still useful to add? If not this can be closed. I'm a happy user of the powerview integration which works for my luxaflex silhouette shade blinds.

The tilt position unfortunately is not visible as a state but that's a different problem and just using scenes to set predefined positions works fine for me.

**Comment by bdraco** [comment]
It seems reasonable to add. If you want to do it, please open a PR.  Thanks 👍
