### ISSUE TITLE
Apple iCloud 

### ISSUE THREAD

**Issue by MichaelNMaggs** [home-assistant/home-assistant.github.io#17876]
### Feedback

What does this warning mean?

_Low `max_interval` may cause battery drainage as it wakes up your device to get the current location._

There is no explanation of `max_interval`  here or on any other page that I can see. If usage is explained elsewhere a link would be helpful.

### URL

https://www.home-assistant.io/integrations/icloud/

**Comment by frenck** [comment]
This is stale documentation from the previous configuration method. Opened up a PR to remove it. Thanks for reporting! 👍
