### ISSUE TITLE
I still don't know how to track devices

### ISSUE THREAD

**Issue by rmikke** [home-assistant/home-assistant.github.io#17879]
### Feedback

OK, I have the asuswrt integration, I have enabled device tracker and I can check that 19 devices are connected.

Now what? How do I detect a particular device in an automation?

### URL

https://www.home-assistant.io/integrations/asuswrt/

### Version

2021.5.4

**Comment by ollo69** [comment]
This is not an integration issue. Please use the forum to ask support.
