### ISSUE TITLE
RecSwitch

### ISSUE THREAD

**Issue by albandy** [home-assistant/home-assistant.github.io#17870]
### Feedback

Hi,
It looks like the guide won't work. I can't get my socket strip integrated according to these instructions. It works in the Rec app.

Greetings Andy

### URL

https://www.home-assistant.io/integrations/recswitch/

### Version

2021.5.4

**Comment by frenck** [comment]
Hi there @albandy 👋 

It sounds like you want to report a problem with the integration, yet you have provided documentation feedback. Based on your message I'm not able to adjust much to the documentation. Please report integration issues here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
