### ISSUE TITLE
Installation Methods Containers

### ISSUE THREAD

**Issue by icemanch** [home-assistant/home-assistant.github.io#17884]
### Feedback

The table comparing installation methods lists the container as not being able to use Supervisor, Add-ons, or Snapshots.  That doesn't seem correct. My installation is on Ubuntu with Docker and has a supervisor, Add-ons and snapshots.  

### URL

https://www.home-assistant.io/installation/

### Version

2021.5.4

**Comment by ludeeus** [comment]
Then you have an (unsupported) Supervised installation, and not Container (all but Core use containers)

**Comment by icemanch** [comment]
> Then you have an (unsupported) Supervised installation, and not Container (all but Core use containers)

I just realized my mistake.  Trying to figure out how to delete this issue.
