### ISSUE TITLE
Platform citybikes not ready yet

### ISSUE THREAD

**Issue by cinghialino** [home-assistant/home-assistant.github.io#17888]
### Feedback

it's not working.
it's always "Platform citybikes not ready yet"

### URL

https://www.home-assistant.io/integrations/citybikes/

### Version

2021.5.4

**Comment by frenck** [comment]
Hi there @cinghialino! 👋 

Thanks for providing documentation feedback, however, it seems like you want to report an issue with an Home Assistant integration instead. There is no amount of documentation I can adjust to fix an integration.

Could you please raise an issue on the issue tracker?

<https://github.com/home-assistant/core/issues>

Thanks already! 👍 

../Frenck 🚂
