### ISSUE TITLE
sensor.time_date and Time Zone

### ISSUE THREAD

**Issue by vespadj** [home-assistant/home-assistant.github.io#17883]
### Feedback

I would like to print in notifications the time when an event occurs even the default format "10 hours ago".
So I find [time_date](https://www.home-assistant.io/integrations/time_date/).
_Suggestions for documentation._
I would like to know if today it's even the best way to do my goal and how impact in recording and database.
I suggest to put a note about: if the result is unexpected like date_time are the same date_time_utc, please check/change Time Zone in the General Settings form UTC to your time zone.

### URL

https://www.home-assistant.io/integrations/time_date/

### Version

2021.5.4

**Comment by fabaff** [comment]
Sorry, I can't really follow....is the issue that if one using the wrong time zone that the output doesn't give you the right value?

**Comment by vespadj** [comment]
Exactly! 
In my case the default installation had got a default value of TZ=UTC, and it takes me some time to understand if I have to check Operating System, or Docker or some else, ... so:

> I suggest to put a note about: if the result is unexpected, like date_time are the same date_time_utc, please check/change Time Zone in the General Settings form UTC to your time zone.

**Comment by fabaff** [comment]
The [installation/setup](https://www.home-assistant.io/getting-started/onboarding/) is mentioned the setting of the timezone. 

But we can mention that in the integration docs as well.
