### ISSUE TITLE
Potentially add `Stream` to default_config docs

### ISSUE THREAD

**Issue by chelming** [home-assistant/home-assistant.github.io#17886]
### Feedback

Based on the docs, I think [Stream](https://www.home-assistant.io/integrations/stream/) should be listed on that page too. I'm not totally sure on how to check whether it's loaded through there for sure or not.

### URL

https://www.home-assistant.io/integrations/default_config/

### Version

2021.5.4

**Comment by chelming** [comment]
[SSDP](https://www.home-assistant.io/integrations/ssdp) looks like it might be another?

**Comment by frenck** [comment]
- `stream` is not part of the `default_config`.
- `ssdp` is listed on the documentation page.


See: <https://github.com/home-assistant/core/blob/dev/homeassistant/components/default_config/manifest.json#L5>

**Comment by frenck** [comment]
@mkaplann I've deleted your message as it exposed personal email addresses.

**Comment by allenporter** [comment]
We updated the docs in https://www.home-assistant.io/integrations/stream/ to say it was automatically loaded as part of default_config and no config by end users was necessary.  Perhaps that was not correct?

(I've never had `stream:` in my config, but i'm not sure how its configured)

**Comment by frenck** [comment]
That is not correct indeed. It could be pulled in as a dependency from something else, but it is not part of the default config.

**Comment by uvjustin** [comment]
It gets loaded by the default_config component: https://www.github.com/home-assistant/core/tree/dev/homeassistant%2Fcomponents%2Fdefault_config%2F__init__.py

**Comment by frenck** [comment]
right! Only if `av` is available 👍
