### ISSUE TITLE
Scene Editor

### ISSUE THREAD

**Issue by jamesfriend76** [home-assistant/home-assistant.github.io#17898]
### Feedback

Hi, the documentation mentions that advanced mode allows entities to be added to a scene. 
There is no mention of where this mode is set. 
Thanks

### URL

https://www.home-assistant.io/docs/scene/editor/

### Version

2021.5.5

**Comment by frenck** [comment]
You can find it in your user profile. I've opened up a PR to adjust the documentation to make that clear.

Thanks for your feedback! 👍

**Comment by jamesfriend76** [comment]
Hi Franck.
Thanks, I actually found it by googling, but also think it would be good to
have a reference in the documentation.
Really enjoying HA so far!

Regards
James

**Comment by frenck** [comment]
I did add the reference 😉
