### ISSUE TITLE
Registers with 32-bit Integers

### ISSUE THREAD

**Issue by jcamm3** [home-assistant/home-assistant.github.io#17892]
### Feedback

Let me start by saying I'm new to modbus.  I was able to configure the integration to pull from registers with 16-bit signed and unsigned integers.  However, I am not able to pull 32-bit.  Is there something I need to do to be able to do so?  Most of the registers on my Schneider Electric Conext Solar device are 32-bit integers.

![supported_modbus_data_types](https://user-images.githubusercontent.com/6116518/118834899-8882b180-b890-11eb-9acf-508a8c4c967a.png)

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.5.4

**Comment by janiversen** [comment]
The modbus integration follow the standard strictly, please see https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf
and if you look at the datatypes 4byte registers do not exist. According to the standard you use 2 registers to read a int32.

So the documentation is correct, however we have seen some devices that have implemented non standard register types and we are thinking about a solution.

There is an open issue with a request https://github.com/home-assistant/core/issues/49941 the essence of the issue are good, but for other reasons there are a lot of less relevant messages.

I suggest you subscribe to that issue. We will of course also update the documentation when a PR is available so you can also keep looking here.

**Comment by jcamm3** [comment]
adding 'count: 2' to each of the 32-bit sensor config entries worked like a charm.

**Comment by janiversen** [comment]
super.

Closing issue.
