### ISSUE TITLE
Nuki Integration not available

### ISSUE THREAD

**Issue by guidowattenhofer** [home-assistant/home-assistant.github.io#17896]
### Feedback

I can not find the nuki integration within HomeAssistant. Help would be very apperciated.

Thanks
Guido Wattenhofer

## System Health

version | 2021.1.5
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
virtualenv | true
python_version | 3.7.3
os_name | Linux
os_version | 5.10.17-v7l+
arch | armv7l
timezone | Europe/Zurich

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 19. Juni 2021, 2:00
relayer_connected | true
remote_enabled | false
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | storage
views | 1
resources | 0

</details>

### URL

https://www.home-assistant.io/integrations/nuki/

### Version

2021.5.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
