### ISSUE TITLE
motioneye integration

### ISSUE THREAD

**Issue by Appie-rappie** [home-assistant/home-assistant.github.io#17904]
### Feedback

Thanks for this integration. I've been waiting for it for a long time.
Just tried it out, but got an 'unexpected error' when entering the Motioneye configuration parameters (see snip). It is entirely possible I interpreted the instructions wrong, but the credentials are correct. What an I doing wrong?

![Capture](https://user-images.githubusercontent.com/68786808/118970602-b6d6be80-b96e-11eb-8dca-259e86041784.JPG)

### URL

https://www.home-assistant.io/integrations/motioneye/

### Version

2021.5.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
