### ISSUE TITLE
Add some clarification around re-authenticate

### ISSUE THREAD

**Issue by gedger** [home-assistant/home-assistant.github.io#17901]
### Feedback

The instructions mention "The duration of this authentication is determined by Apple, so you will need to verify your account every now and then" but provides no information on how to actual do this? I'm getting log messages every 30 minutes 

Logger: pyicloud.base
Source: /usr/local/lib/python3.8/site-packages/pyicloud/base.py:185
First occurred: 8:38:37 (2 occurrences) 
Last logged: 8:38:37

So I presume I need to re-authenticate but how?

There is also no mention of the seemingly on-going issue of receiving regular messages from Apple saying that someone has logged into your account. This needs to be mentioned as an issue and needs to be ignored if you wish to use the component. 

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2021.5.5

**Comment by frenck** [comment]
The instructions have been updated on how to work with accounts that have two factor authentication.
