### ISSUE TITLE
Document How To Change Nest Thermostat Settings

### ISSUE THREAD

**Issue by bcwhite-code** [home-assistant/home-assistant.github.io#17919]
### Feedback

I love the detail that goes into these pages.  It makes a very complex configuration process almost easy.  Thank you for that.

There's nothing on the page about how to change settings like thermostat preset or mode (temp, heat/cool, on/off).  I can make adjustments from the Lovelace card but how do I do it with an Automation?  (I want to turn off the A/C when a sliding door is left open.)

If you would include how to do this, or even document that it's not yet possible, that would be appreciated.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.5.5

**Comment by frenck** [comment]
One of the goals of Home Assistant, is to provide a more uniform interface for all device. Nest brings in a normal Climate entity/device. 

You can find information on how to control climate devices in the climate documentation:

<https://www.home-assistant.io/integrations/climate>

**Comment by bcwhite-code** [comment]
Thanks for the link.  Maybe include that in the "nest" page?  There is info about how to set triggers so info about how to set desired temp would also be reasonable.
