### ISSUE TITLE
Fibaro Implant and Roller Shutter support

### ISSUE THREAD

**Issue by dpopovic** [home-assistant/home-assistant.github.io#17918]
### Feedback

I've installed Home Assistant support for Fibaro HC3 as described and it works almost as expected. I see status of all devices and synchronisation does everything what is necessary.

In my case (Fibaro HC3) I am not able to control Fibaro Implant and Fibaro Roller Shutter devices. I can see status of these devices but I am not able to switch them on/off from UI or through automation. I can see correct status of these devices in UI.

I can control Fibaro WallPlug on same installation so I conclude that communication is operational between Fibaro and Home Assistant.

### URL

https://www.home-assistant.io/integrations/fibaro/

### Version

2021.5.5

**Comment by frenck** [comment]
Hi there @dpopovic 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Could you please report this in the Home Assistant Core issue tracker?

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
