### ISSUE TITLE
Please add Two-factor authentication 

### ISSUE THREAD

**Issue by dimadusk** [home-assistant/home-assistant.github.io#17920]
### Feedback

Hello. Great work, integration really works. But have some security issues. When Two-factor authentication is enabled in Ezviz app, integration cannot work with it. There is no way to enter code from SMS in order to authorize integration in Ezviz app, therefore its not possible to view cameras in a secure mode. Please add two-factor authentication within integration. Many thanks. Also it would be nice to have same integration with Dahua/Imou.

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.5.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by dimadusk** [comment]
Two-factor authentication is not a feature, its part of a Ezviz and it doesn't work within integration. So its an Issue.

**Comment by frenck** [comment]
In that case, it is misplaced. You've submitted documentation feedback, there is no amount of documentation that I can write to make that happen.

Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

If you are unsure of where to go: <https://www.home-assistant.io/help>

Thanks! 👍 

../Frenck

**Comment by dimadusk** [comment]
Well, anyway thanks for your great work, its a huge progress towards making this fully functional. Too bad ezviz dont provide full info to make it complete. Is there anyway I can help you to make it work completely with all security features? Maybe its somehow has to do with push notifications?
