### ISSUE TITLE
Suggest update documentation to say whether this support only Basic or Digest auth or both

### ISSUE THREAD

**Issue by micarex** [home-assistant/home-assistant.github.io#17921]
### Feedback

I've been trying to use rest_command to activate a REST API that requires digest authentication.  The doco doesn't explain whether or not different authentication types work.  After a lot of trying and getting 401 errors, I have concluded it doesn't support digest but I could be wrong (there's various discussion forums entries with people trying to do the same thing).  Either way, can I suggest update doco to explicitly state what type of authentication is supported so people aren't left wondering, and if digest is supported, please provide an example.

### URL

https://www.home-assistant.io/integrations/rest_command/

### Version

2021.5.5

**Comment by frenck** [comment]
It doesn't support digest. I've opened up a PR to adjust the documentation. Thanks for your feedback 👍
