### ISSUE TITLE
Delay Function

### ISSUE THREAD

**Issue by manjotsc** [home-assistant/home-assistant.github.io#17923]
### Feedback

I would like to get delay function added to scrape module, for pages that takes few seconds to load so that data can be extracted correctly. 

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2021.5.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
