### ISSUE TITLE
The illusive HOST value

### ISSUE THREAD

**Issue by MrBill12** [home-assistant/home-assistant.github.io#17926]
### Feedback

At the very beginning of the Home Assistant Community Add-on: Network UPS Tools documentation there is a single line:

`Note: The host a0d7b954-nut can be used to allow Home Assistant to communicate directly with the addon`

As I read that line I made a mental note, "I bet I need this later".  After spending the next block of time learning and getting the add-on running I had completely forgotten the above Note.  

Next, when firing up the core integration for the first time I'm presented with a dialog box where 'host' defaults to _localhost_ Which is not the correct value, reviewing the integrations documentation, there are no clues, reviewing the NUT Add-on Logfile provides no clues.  I try many guesses, finally after many incorrect guesses, re-reading every word from the top brings me back to the NOTE above.   That of course was the obscure value needed.  

At the bare minimum, an update to the NUT integration documentation would prevent a frustrating guessing game.  "NOTE: If you're using 'Home Assistant Community Add-on: Network UPS Tools' the host value is likely a0d7b954-nut"

A better solution would be for the integrations init routine to try that value and if present present it as the default instead of _localhost_.

### URL

https://www.home-assistant.io/integrations/nut/

### Version

2021.5.5

**Comment by frenck** [comment]
The add-on is an external third-party NUT server. Nut servers can be installed anywhere, this is up to the server or software are using to document. We cannot document all use cases out there, that is out of scope for our documentation.

Nevertheless, thank you for the feedback 👍 

../Frenck
