### ISSUE TITLE
No information on initial config

### ISSUE THREAD

**Issue by jpravetz** [home-assistant/home-assistant.github.io#17935]
### Feedback

The initial integration pop-up asks for hostname, port, username, password, stream and RTSP port. There should be something in this dialog, or the help pages, that says what these are. Is this the IP address of the camera or a Foscam website?

### URL

https://www.home-assistant.io/integrations/foscam/

### Version

2021.5.5

**Comment by frenck** [comment]
You are setting up a connection to the camera right? So, it is information about the camera.

**Comment by jpravetz** [comment]
Actually I think it ended up being  information to log in to the website at foscam.com. "information about the camera" could be anything.

**Comment by skgsergio** [comment]
In the Integration docs you have a box at the right (or if using mobile at the bottom) with some info regarding the integration. 

If it says Local it means that you should use whatever local data you have to configure the integration. On the other hand if it says Cloud means you will have to configure an username and password or a token and likely some other data that is tied to a cloud service (website, app, ...). 

![image](https://user-images.githubusercontent.com/186349/119308871-dff89700-bc6d-11eb-9aa9-4bc37d4ea9ae.png)

https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/#classifiers

**Comment by jpravetz** [comment]
The page should say this then. 
I am providing feedback on the documentation, not asking for help. I am trying to help the next user.

**Comment by MairusuPawa** [comment]
Hello, I'm confused about the initial setup as well. A list of supported camera models would be nice, I suppose.

I was given an old Foscam FI8918W and wanted to add it to my HA setup, however I have no clue what RTSP port it is using. Default settings don't work (generic "can't connect" error), and neither the WebUI of the camera nor a quick nmap scan shows a RTSP port being a thing. Is this model even supported?

Side note: I do get a video feed using the generic mjpeg integration, pointing it at a CGI url.

**Comment by skgsergio** [comment]
Is difficult to give a list of supported models as Foscam doesn't give much
info about the cameras. I know there are at least 2 different camera
software, one that is not supported at all and another that is supported
but depending on the version the RTSP port reported is wrong and you have
to try it manually (usually between 88 and 554).

I'm sorry but I can't tell you more....

Maybe just try this: http://CAMERA_IP:CAMERA_PORT
/cgi-bin/CGIProxy.fcgi?cmd=getProductAllInfo&usr=USERNAME&pwd=PASSWORD
If the response is an error then the camera is likely not supported.

**Comment by MairusuPawa** [comment]
Thanks for the quick reply!

Turns out there's no "CGIProxy.fcgi" for this old camera, known as part of the "SD video" series now on the Foscam site. So, yeah, still getting an error. The MJPEG feed URI is thus also different from what this addon seems to expect:
https://www.foscam.com/faqs/view.html?id=128

I can confirm this method works for controlling movement:
https://tutoriels.domotique-store.fr/content/72/91/fr/utiliser-une-camera-ip-foscam-sd-avec-une-box-domotique.html

**Comment by skgsergio** [comment]
Looks like only the HD series (and even then and not all) are the only that
are supported as this integration uses that CGI.
