### ISSUE TITLE
installation types

### ISSUE THREAD

**Issue by Ghostbuster64** [home-assistant/home-assistant.github.io#17941]
### Feedback

Hi,

In the list of different installation types, i'm missing the Debian10-installation. You mention "Linux", but this is only HA-linux. There is a Debian10-installation manual on your site and you mention in this manual that Debian10 is a supported installation. So maybe it's an idea to mention it in the list of different installations. 

Cheers,

Richard

### URL

https://www.home-assistant.io/installation

### Version

2021.5.5

**Comment by frenck** [comment]
There are 2 methods listed that work on Debian 10.

- Home Assistant Core
- Home Assistant Supervised
