### ISSUE TITLE
Failed to connect 

### ISSUE THREAD

**Issue by aallye** [home-assistant/home-assistant.github.io#17942]
### Feedback

Failed to connect, the same email and password workks from garmin web

### URL

https://www.home-assistant.io/integrations/garmin_connect/

### Version

2021.5.5

**Comment by frenck** [comment]
Hi there @aallye 👋 

It seems like you want to report a bug with an Home Assistant integration, yet, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix a bug.

If you want to report an issue with an integration, please do so, in the Home Assistant issue tracker, here:

<https://github.com/home-assistant/core/issues>

../Frenck
