### ISSUE TITLE
There's good information here, but it doesn't quite answer the question of "What should I do?"

### ISSUE THREAD

**Issue by kauffy** [home-assistant/home-assistant.github.io#17944]
### Feedback

I have a few entities that show up without unique identifiers somehow (Magic Home strip lights).

I can't tell from reading the documentation if I can somehow assert a unique ID to make it compatible with the UI (e.g., based on MAC address or something else), for example, or remedy this another way. The system is able to address the lights, but it still complains they don't have a unique ID.

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2021.5.5

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/126715207-c38cb518-dd69-4600-b1ec-211497219cb7.png)

There is nothing you can do, it is a limitation of the integration used.
