### ISSUE TITLE
confidence value

### ISSUE THREAD

**Issue by chainsawbike** [home-assistant/home-assistant.github.io#17945]
### Feedback

setting a min confidence value is not documented here yet after reviewing the sourcecode and setting it in the configuration.yaml file it appears to change the value as expected from its default of 80, is there any reason for this not being documented yet?

### URL

https://www.home-assistant.io/integrations/tensorflow/

### Version

2021.5.5

**Comment by frenck** [comment]
the confidence value is a feature of the image processing integration, not the TensorFlow integration.
