### ISSUE TITLE
Casting with apps

### ISSUE THREAD

**Issue by dusopn** [home-assistant/home-assistant.github.io#17940]
### Feedback

Hello,

Is it possible to initiate casting with other apps (like TuneIn), or just the listed ones (like Plex)?

Thanks
Dusan

### URL

https://www.home-assistant.io/integrations/cast/

### Version

2021.5.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
