### ISSUE TITLE
Changing state of myStrom

### ISSUE THREAD

**Issue by ChrigouTav** [home-assistant/home-assistant.github.io#17951]
### Feedback

The command
`curl -G -X GET http://IP_ADDRESS/relay -d 'state=1'`
seems not to work.
Getting state works well but setting it gives me:
<pre>
<html><head><title>Error</title></head><body><h1>404 Not Found</h1></body></html>
</pre>

### URL

https://www.home-assistant.io/integrations/mystrom/

### Version

2021.5.5

**Comment by frenck** [comment]
We should remove most of that stuff from our documentation. We should not advise our users to dig into an API like that. That should not be needed.

**Comment by fabaff** [comment]
> seems not to work.

Works for hardware version 1 and version 2 (3.82.4). There is no API response if you change the state of the relay. Thus, from the command-line you would have to check `/report` for the current state after performing a state change.

> We should remove most of that stuff from our documentation. We should not advise our users to dig into an API like that. That should not be needed.

Indeed, especially if it's not marked as "troubleshooting" or alike and sitting inside a section of the setup like in this case.
