### ISSUE TITLE
All links in "IMPORTANT TEMPLATE RULES" goto a 404

### ISSUE THREAD

**Issue by OmgImAlexis** [home-assistant/home-assistant.github.io#17953]
### Feedback

All the links in the 'IMPORTANT TEMPLATE RULES" goto a 404 on the jinja site.

From what I can tell the new URL seems to be https://jinja.palletsprojects.com/en/3.0.x/templates/

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2021.5.5

**Comment by frenck** [comment]
Links have been adjusted. Thanks for reporting 👍
