### ISSUE TITLE
Garmin Connect

### ISSUE THREAD

**Issue by Bars1973** [home-assistant/home-assistant.github.io#17955]
### Feedback

Integration Garmin Connect stopped working after update . After entering the correct username and password, he writes that it was not possible to connect.

### URL

https://www.home-assistant.io/integrations/garmin_connect/

### Version

2021.5.5

**Comment by frenck** [comment]
Hi there @Bars1973 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix an integration. Could you please report the issue in the Home Assistant Core issue tracker?

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
