### ISSUE TITLE
Please document how to change username/password for Synology integration

### ISSUE THREAD

**Issue by evoncken** [home-assistant/home-assistant.github.io#17973]
### Feedback

The integration works like a charm, but I have not found any documentation on changing the credentials used to log on to the Synology server.

At the moment, the only way seems to delete the entire integration, then set everything up from scratch?

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2021.5.5

**Comment by frenck** [comment]
Just add it again 🤷 . Home Assistant will automatically detect the existing instance and update it.

**Comment by willemstoker** [comment]
Same issue here. I changed the password for the synology user, but can't change it in the integration UI. Where is it stored so I can change the password in home assistant?

**Comment by frenck** [comment]
@willemstoker The answer to your question is literally above your comment...

**Comment by willemstoker** [comment]
I tried adding the integration again, without deleting it first, but it says:

Afgebroken (Aborted)
Apparaat is al geconfigureerd (Device already configured)

Do I need to delete it first? I rather don't because it will likely break dashboards and history of the devices
