### ISSUE TITLE
Type "keyup" and "keydown" not working

### ISSUE THREAD

**Issue by pimw1** [home-assistant/home-assistant.github.io#17970]
### Feedback

Hi, the events are all pushed to home assistant when assigned to buttons, except for the following buttons:

- short press on +
- short press on -

![image](https://user-images.githubusercontent.com/74881023/119533256-f265f400-bd85-11eb-8cff-177bfbf32279.png)

I've validated this via the developer tools: no message is comming in.
![image](https://user-images.githubusercontent.com/74881023/119533465-280add00-bd86-11eb-9419-88f3d0e4cd29.png)

Oddly, it is working with a long press on the same buttons (thas is what you see in the screenshot above).

I think this relates to the following comment in the documentation:
- Some Android remotes send key up/down events instead of key presses.
-> not applicable to me, i'm using a Logitech Harmony Elite remote.
- Functionality other than key presses and app launches are not implemented yet.
-> this might be applicable: since these are the + and - buttons, the remark could be about these buttons? If that is the case, it would be wise to explicitly mention it in the below location to avoid any unclarity:
![image](https://user-images.githubusercontent.com/74881023/119533790-82a43900-bd86-11eb-850f-f707e15237c4.png)

Anyhow, i am not sure if this is a bug or not-implemented functionality. It would be great if this could be fixed or added (whatever is applicable).

### URL

https://www.home-assistant.io/integrations/emulated_roku/

### Version

2021.5.5

**Comment by frenck** [comment]
That would be a feature that is not implemented.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by pimw1** [comment]
Thanks again Frenck, sorry for posting this in the wrong location. I'll request this via the link you provided.
