### ISSUE TITLE
There is no option to enable CoIoT

### ISSUE THREAD

**Issue by jpravetz** [home-assistant/home-assistant.github.io#17975]
### Feedback

There is no option to enable CoIoT.
Using Shelly1 and firmware 20210429-100340/v1.10.4-g3f94cd7

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.5.5

**Comment by thecode** [comment]
You need to access the device web page via a browser, not using the Shelly App.
![image](https://user-images.githubusercontent.com/1858925/119624863-41596b00-be12-11eb-8538-11cd6dbbe78c.png)
![image](https://user-images.githubusercontent.com/1858925/119624957-5a621c00-be12-11eb-9b13-8942c9287648.png)

**Comment by jpravetz** [comment]
I was doing so, and it wasn't showing up. But I just made some configuration changes (setting static IP address and more) and now it is showing up. Perhaps there is a dependency that must be met before it shows up, or perhaps I'm going senile. Either is possible :-) thanks
