### ISSUE TITLE
Sonos - media_player.play_media - extra attributes, title & thumb not working

### ISSUE THREAD

**Issue by NiMa08** [home-assistant/home-assistant.github.io#17988]
### Feedback

I'm using the service media_player.play_media and the extra data attribute with the thumb and title options. The service works well for google speakers. But the sonos speakers don't recognise them so the title and thumb do not get set. Ive been asking everywhere for help, but no luck. I also see two attributes called media_info and metadata with datatypes map, unfortunately i don't know how they work and if that could be my solution. Also don't know if this is a bug or just not possible. Any help is greatly appreciated. 

All I would like to do is to change the entity_picture and title of a sonos media_player whenever i use the media_player.play_media service. Thanks

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2021.5.5

### Additional information

How sonos looks after service call:

<img width="496" alt="Screenshot 2021-05-26 at 20 53 33" src="https://user-images.githubusercontent.com/34718727/119715648-84442e80-be64-11eb-9832-2456e900fb80.png">

How google mini looks after service call:

<img width="496" alt="Screenshot 2021-05-26 at 20 53 49" src="https://user-images.githubusercontent.com/34718727/119715701-91f9b400-be64-11eb-8319-574c499982cc.png">

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by NiMa08** [comment]
Unfortunately I have been trying this for over a week now, I just wanted to know if it's even possible. If it's not a bug?

**Comment by jjlawren** [comment]
It's simply not supported. You're using a `cast`-specific feature.
