### ISSUE TITLE
Modbus switch examples missing required variables (and typo "adddress")

### ISSUE THREAD

**Issue by AdamoIV** [home-assistant/home-assistant.github.io#17982]
### Feedback

The "CONFIGURING PLATFORM SWITCH" configuration.yaml examples do not include **command_on** or **command_off**, yet they are listed as "REQUIRED".

There is also a typo "adddress" in the input_type definition.

### URL

https://www.home-assistant.io/integrations/modbus

### Version

2021.5.5

### Additional information

![Capture](https://user-images.githubusercontent.com/71228013/119671495-b5efd200-be31-11eb-8c70-7f919bf8db97.PNG)

**Comment by janiversen** [comment]
Actually command_on/off are now optional.

The “adddress” is a typo which we will correct.

Thanks for reporting this.

you can see the new documentation (for 2021.6) in 
https://next.home-assistant.io/integrations/modbus

**Comment by AdamoIV** [comment]
Awesome stuff - many thanks!
