### ISSUE TITLE
Incorrect Current temperature

### ISSUE THREAD

**Issue by andys73** [home-assistant/home-assistant.github.io#17983]
### Feedback

Hello,

I can see that in the XML the temperature reported by the API is correct (comparing temperature with an external accurate sensor it is matching the xml - in the first forecast entry date is ~ 45 min ago) but both wind and temperature is incorrect what is reported in the weather card.

http://metwdb-openaccess.ichec.ie/metno-wdb2ts/locationforecast?lat=5x.xxxx;long=-6.xxxxx

Can you review and correct please. the correct temperature is 15.7. It showed in the weather card as 16.3 since morning.

Thank you

`<time datatype="forecast" from="2021-05-26T14:00:00Z" to="2021-05-26T14:00:00Z">
<location altitude="50" latitude="5x.xxxxx" longitude="-6.xxxxx">
<temperature id="TTT" unit="celsius" value="15.7"/>
<windDirection id="dd" deg="42.7" name="NE"/>
<windSpeed id="ff" mps="1.6" beaufort="2" name="Svak vind"/>
<globalRadiation value="695.7" unit="W/m^2"/>
<humidity value="57.0" unit="percent"/>
<pressure id="pr" unit="hPa" value="1017.4"/>
<cloudiness id="NN" percent="54.6"/>
<lowClouds id="LOW" percent="54.6"/>
<mediumClouds id="MEDIUM" percent="0.0"/>
<highClouds id="HIGH" percent="0.0"/>
<dewpointTemperature id="TD" unit="celsius" value="7.2"/>
</location>`

![image](https://user-images.githubusercontent.com/77861753/119671122-6a3d2880-be31-11eb-97a3-3647084e72bd.png)

### URL

https://www.home-assistant.io/integrations/met_eireann/

### Version

2021.5.5

**Comment by andys73** [comment]
<product class="pointData">
<time datatype="forecast" from="2021-05-26T14:00:00Z" to="2021-05-26T14:00:00Z">
<location altitude="50" latitude="5x.xxxx" longitude="-6.xxxx">
<temperature id="TTT" unit="celsius" value="15.7"/>
<windDirection id="dd" deg="42.7" name="NE"/>
<windSpeed id="ff" mps="1.6" beaufort="2" name="Svak vind"/>
<globalRadiation value="695.7" unit="W/m^2"/>
<humidity value="57.0" unit="percent"/>
<pressure id="pr" unit="hPa" value="1017.4"/>
<cloudiness id="NN" percent="54.6"/>
<lowClouds id="LOW" percent="54.6"/>
<mediumClouds id="MEDIUM" percent="0.0"/>
<highClouds id="HIGH" percent="0.0"/>
<dewpointTemperature id="TD" unit="celsius" value="7.2"/>
</location>
</time>

**Comment by frenck** [comment]
Hi there @andys73 👋 

I stumble upon this issue, and I noticed that it tries to report a bug. However; you have submitted documentation feedback. We cannot fix this issue by adjusting documentation.

Issues with Home Assistant integrations should be reported here:

<https://github.com/home-assistant/core/issues>

Sorry for not spotting this sooner!

../Frenck
