### ISSUE TITLE
UniFi Video Documentation Poor

### ISSUE THREAD

**Issue by fishcharlie** [home-assistant/home-assistant.github.io#17990]
### Feedback

There following things don't make sense on this documentation:

- No information about 2FA
- `The API key is found in User -> My account -> API Access in the NVR software.`. This doesn't look to exist anymore (unless I'm looking in the wrong place, in which case more detail is needed).
- `The camera password is found in Settings -> Camera Settings -> Camera Password in the NVR software.` Same thing here. This doesn't look to exist anymore (unless I'm looking in the wrong place, in which case more detail is needed).

### URL

https://www.home-assistant.io/integrations/uvc/

### Version

2021.5.5

**Comment by frenck** [comment]
Thanks for the feedback @fishcharlie 👍 

Can you help us out with the correct settings/guide? It is absolutely possible the UI changed over time, however, nobody has contributed an update.

As an open-source project, we rely on contributions from the community for these things.

2FA isn't supported, which I can tell from the code. But that probably doesn't matter either, as this integration works with an API key and not logins.

**Comment by fishcharlie** [comment]
@frenck Would love to. However, I'm confused myself on these items. I spent a decent amount of time trying to search through where to find these settings but with no luck so far.

Makes sense on the 2FA.
