### ISSUE TITLE
Garmin Connect integration does not work about 2 weeks

### ISSUE THREAD

**Issue by spaymina** [home-assistant/home-assistant.github.io#17997]
### Feedback

Unable to parse data from the web. I tried to resolve the situation with reinstallation - the integration add dialog does not get through login / authentication and ends with the message connection failed

### URL

https://www.home-assistant.io/integrations/garmin_connect/

### Version

2021.5.5

**Comment by cyberjunky** [comment]
It was fixed some time ago, but still awaiting final review and merge, missed some builds already, sorry nothing I can do.
https://github.com/home-assistant/core/pull/50865

**Comment by cyberjunky** [comment]
This bug report is for the website, so nothing to do with the integration code. So can be closed.

**Comment by spaymina** [comment]
I don't understand that much. Are we waiting for the solution (release) that has already been made or are we waiting for something uncertain? :) PS: Link to (about) Cloudflare anti-bot measures I read. Thank you.

**Comment by spaymina** [comment]
Solution:

https://github.com/home-assistant/core/issues/50822#issuecomment-843363438
