### ISSUE TITLE
Additional Sensors for Sense Integration when using solar

### ISSUE THREAD

**Issue by dorgan-brillio** [home-assistant/home-assistant.github.io#18008]
### Feedback

It would be great if you could include some additional sensors when using solar

to_grid (when production is more than consumption)
from_grid (when consumption is more than production)

And then daily versions of both of these

### URL

https://www.home-assistant.io/integrations/sense/

### Version

2021.5.5

**Comment by kbickar** [comment]
The data is available on the API - both instantaneous and trends.  It would be a little simpler to just provide a grid_power that could be positive or negative or maybe just a live solar total and a usage total that the user could then combine to get the grid value.

For the daily trend data, would you see that as just a value that increases/decreases over the day?

**Comment by dorgan** [comment]
@kbickar  i think that would work

**Comment by frenck** [comment]
Hi there, just spotted this one.

It seems like you are trying to request/suggest a new feature, however, you have submitted documentation feedback instead.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
