### ISSUE TITLE
Outdated HA components

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#18011]
### Feedback

For me the "scope" is not clear: 
- the core, supervisor, os?  yes
- any installed addon such as Node-RED, Samba, MariaDB?
- any installed integration no included in core
- any HACS components (Lovelace cards) 

Is there a "script" or something else what shows all installed updated components similiar to "npm outdated [-g]"

### URL

https://www.home-assistant.io/integrations/updater/

### Version

2021.5.5

**Comment by frenck** [comment]
The scope for the update is solely the Home Assistant core.
