### ISSUE TITLE
Raspberry Pi hass-os documentation has no information on using WiFi

### ISSUE THREAD

**Issue by PaulKGrimes** [home-assistant/home-assistant.github.io#18015]
### Feedback

The Raspberry Pi Home-Assistant OS installation instructions give no information on how to set up the Pi on a WiFi network.

Most people don't have ethernet running around their home, so this omission is severely limiting.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.5.5

**Comment by frenck** [comment]
> Most people don't have ethernet running around their home

We strongly advise not to use Wi-Fi, and thus do not document it as part of the installation manual for that reason.

You can configure it via the UI: Supervisor menu -> System tab
There you can change your IP address and network settings, including Wi-Fi.
