### ISSUE TITLE
half degree control

### ISSUE THREAD

**Issue by hros** [home-assistant/home-assistant.github.io#18018]
### Feedback

My air conditioner can be controlled in 0.5°C increments
While the current temperature is being displayed correctly:
![image](https://user-images.githubusercontent.com/2613469/120088192-e87e2100-c0f6-11eb-98db-a09cbdeb4786.png)
The target temperature only shows the integral portion of the temperature
Moreover, controlling the temperature from the ui panel, either by moving the blue dot on the temperature dial, or by using the up/down controls in the detailed window (after pressing the three dots):
![image](https://user-images.githubusercontent.com/2613469/120088235-4b6fb800-c0f7-11eb-82f6-355d0e4be69e.png)
changes the target temperature by complete integers

please add an option (a radio button?) to select the temperature update resolution

### URL

https://www.home-assistant.io/lovelace/thermostat/

### Version

2021.5.5

**Comment by hros** [comment]
I see that this issue is about to be closed
I can try and resolve this issue myself with a pr
Please provide some reference to similar projects, regarding the build process; necessary testing and submission

**Comment by frenck** [comment]
Hi there @hros 👋 

> please add an option (a radio button?) to select the temperature update resolution

It seems like you have a feature request, however, you have submitted documentation feedback. This cannot be implemented by adjusting documentation of course.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
