### ISSUE TITLE
I would like to feed information collected in Home Assistant to APRS like the weather or radiation observations.

### ISSUE THREAD

**Issue by edegraaff** [home-assistant/home-assistant.github.io#18031]
### Feedback

 Would be nice to make use of this Integration component in a way do feed the APRS system with valuable data. 

### URL

https://www.home-assistant.io/integrations/aprs/

### Version

2021.5.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
