### ISSUE TITLE
Clarification on what data the sensor accepts

### ISSUE THREAD

**Issue by thekitehunter** [home-assistant/home-assistant.github.io#18035]
### Feedback

It's not clear to me what input this sensor needs and therefore its logic. Is it expecting cumulative meter readings periodically and it has a logic to calculate how much is being used during a period?
My data comes from a sensor on the cable and just shows periodically the power being taken at that instant in watts and I don't think this integration is for this.

The current text simply says "This sensor will track a source sensor values". Could this be expanded to more clearly say what that data is expected to be?

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.5.5

**Comment by dgomes** [comment]
The documentation states:

"This sensor will **track a source sensor values**, automatically **resetting the meter** based on the configured cycle."

So it's just that 😄  it tracks (carries the value from) the source and periodically resets that value periodically... This can be used in numerous use cases, some of which I never though previously about! Energy was my primary use case, but I've seen people using it to track pages printed per month!

Ultimately It's like one of those old mechanical meters (https://www.veeder.com/us/meter-registers/mechanical-meter-registers-and-dispenser-computers/7887-mechanical-meter-register) 

Now, given your use case, your source sensor is measuring **power**, not **energy**. If you want to measure **energy**, you must **integrate** (mathematical operation) power. Luckily for you, HA has such a sensor: https://www.home-assistant.io/integrations/integration/ 

There is much more information about using integration sensor and utility_meter together in our community forums.

**Comment by thekitehunter** [comment]
Thank you, that clarifies it. I think it would be useful if some of this was put on the page, or an example. I had a similar problem looking at how to enter 'tariff': 
    tariffs:
      - peak
      - offpeak
  Do I put '-12.0', or '- peak: 12.0'. Perhaps someone who has a lot of experience would know.
Anyway, thanks for the explanation.

**Comment by dgomes** [comment]
you don't put numbers in the tariff... you just fill the name

There is an example in the documentation
