### ISSUE TITLE
Since changes to 2.0TD prices doesn't work

### ISSUE THREAD

**Issue by mclemente1987** [home-assistant/home-assistant.github.io#18049]
### Feedback

This morning, with changes to new tariff 2.0TD, sensor with prices doesn't work.

I suppose it need to change new tariffs in api.

BR,

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2021.5.5

**Comment by frenck** [comment]
Hi there @mclemente1987 👋 

Seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please submit issues with Home Assistant integrations in the issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
