### ISSUE TITLE
No info available after PVPC changes on 06/01

### ISSUE THREAD

**Issue by alceasan** [home-assistant/home-assistant.github.io#18042]
### Feedback

After the changes on PVPC tariffs starting 06/01, this integration has stopped working and no data is received starting 06/01. Now there is only 1 common tariff (2.0 TD) with different hours only for Ceuta & Melilla regions.

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2021.5.5

### Additional information

This probably could be solved bumping **aiopvpc** lib version to [2.1.2](https://github.com/azogue/aiopvpc/releases/tag/v2.1.2) where this has been already solved.

**Comment by frenck** [comment]
Hi there @alceasan! 👋 

It seems like you want to report a bug with a Home Assistant integration, however, you have provided documentation feedback. There is no amount of documentation I can adjust to fix an bug with an integration.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
