### ISSUE TITLE
How to use the Purge service?

### ISSUE THREAD

**Issue by jellevervloessem** [home-assistant/home-assistant.github.io#18048]
### Feedback

How can the Purge service be used in combination with the apply_filter parameter?
- can I add entities? what is the format?
- If I add entities to the filter, are those the only entities that are being purged? Or are those entities the only that are not getting purged?

- How can i purge my recorder database and keep some monthly data (like monthly energy usages)

### URL

https://www.home-assistant.io/integrations/recorder/

### Version

2021.5.5

**Comment by azrael783** [comment]
How did you setup your recorder? Mine is only saving the data of 7 days in a MariaDB. In addition I use an InfluxDB to keep the data for more than 7 days.
My HA does an automatically purge of the Maria DB. I don't think that you can keep only a few data in and purge the rest.
