### ISSUE TITLE
Sensor is offline

### ISSUE THREAD

**Issue by manu-caballero** [home-assistant/home-assistant.github.io#18047]
### Feedback

This sensor is now offline. Since new tariffs applied on June 1st. Need revision

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2021.5.5

**Comment by frenck** [comment]
Hi there @manu-caballero 👋 

Seems like you want to report an issue with an integration, however, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix a bug.

Please report issues in issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
