### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by lalo-nrgz** [home-assistant/home-assistant.github.io#18053]
### Feedback

This plugin has been working wonderfully for the Spanish users. Today, June 1st, the PVPC scheme has changed with new tariffs and hours, and the plugin seems to have stopped working.

Will this issue be solved and the plugin will adapt to the new scheme?

Thanks!

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2021.5.5

**Comment by jd1900** [comment]
Same here. Not working anymore.

**Comment by lalo-nrgz** [comment]
I see there is already a thread for this: https://github.com/home-assistant/core/pull/51320

Sorry! Closing this one :(
