### ISSUE TITLE
Dual Mode thermostat?

### ISSUE THREAD

**Issue by mgoulet65** [home-assistant/home-assistant.github.io#18052]
### Feedback

Are there any plans to make the OOTB generic thermostat in HA dual mode (capable of controlling both heating and cooling)? I did away with my Ecobees that could do that in their integration but it seems like I need tow generic thermostats to control these two modes now.

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

### Version

2021.5.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
