### ISSUE TITLE
The Gauge Card documentation icon configuration

### ISSUE THREAD

**Issue by automaton82** [home-assistant/home-assistant.github.io#18055]
### Feedback

The Gauge Card documentation contains information that the icon can be specified, however this icon does not seem to ever show up when the card is used. If there's a way to make the icon show up the documentation does not say.

### URL

https://www.home-assistant.io/lovelace/gauge/

### Version

2021.5.5

**Comment by azrael783** [comment]
See: https://github.com/home-assistant/home-assistant.io/pull/18523
