### ISSUE TITLE
SIA Alarm Systems Integration

### ISSUE THREAD

**Issue by MichaelNRW** [home-assistant/home-assistant.github.io#18082]
### Feedback

The installation is not possible because the integration cannot be found:

![image](https://user-images.githubusercontent.com/56221179/120788070-562fb000-c530-11eb-90ee-4484fcf94769.png)

Result:

![image](https://user-images.githubusercontent.com/56221179/120788532-bb83a100-c530-11eb-9f31-b55e6f52ebf1.png)

### URL

https://www.home-assistant.io/integrations/sia/

### Version

2021.6.1

### Additional information

Supervisor-2021.05.4

Home Assistant OS 5.13

**Comment by MichaelNRW** [comment]
Please excuse me, I am not a codeowner

**Comment by eavanvalkenburg** [comment]
No problem @MichaelNRW, I can find it when I search for `sia alarm systems`, and usually `sia` is enough, so not sure how to debug this, you could reboot, and then see if there is something in the logs when you open the integrations page, because at that point all the config flows are loaded.
