### ISSUE TITLE
Somfy Oath v2 not working

### ISSUE THREAD

**Issue by erikmex-root** [home-assistant/home-assistant.github.io#18085]
### Feedback

Hi Homeassitant Comunity,

I've contacted Somfy Tech support to find out why I can't get the list of devices after authentication uisng Home assistant cloud and seems like recently, from May 31st, Somfy changed their polling policy allowing any number of calls but with a limited rate of max 1/minute.  They wrote: 

_"Dear customer,
 
As you might have noticed, we have updated the quota policy of the Somfy Open API, in an ongoing effort to provide the best services to our users.

We are contacting you today to inform you about the new rules we are now applying to the API: 
- First of all, no limitation will be applied on the POST /device/{deviceId}/exec endpoint as we want to provide you a total freedom on controlling your devices. 
- On the other hand, polling frequency on the GET /site and child endpoints will now have to be under 1 call per minute.

To preserve an efficient and available service to any of our users, we want to keep the usage of the Open API to a usable but reasonable level to everybody. As we will keep monitoring the generated traffic and the potential impacts, be aware that we do reserve the rights to modify the authorized polling frequency or take any additional measure at any time as stated in our General Terms of Use."_

I don't know if this ratelimit is the root cause of the problem, when testing via their own site (https://developer.somfy.com/somfy-open-api/apis) the post&get queries work OK i.e. get /site/{siteId}/device  

In home assistant it fails with the error message:
Retrying setup: 404 Client Error: Not Found for url: https://api.somfy.com/api/v1/site/{siteId}/device

As a side note.... Somfy developer support wrote "We do have an issue with App creation so if you created one, it is possible that this one will not be recognized by our authentication backend".   

Therefore the way to reproduce this issue is by using Homeassistant cloud (Nabucasa) to authenticate (instead of local Key and secret from the configuraion.yaml)   and once authenticated, it fails with the above message when trying to get the device list from a given {site id}.

Hope you can help to look into the problem.

Kind regards,
Erik

### URL

https://www.home-assistant.io/integrations/somfy/

### Version

2021.6.1

**Comment by tetienne** [comment]
Hi,

There is already an existing issue: https://github.com/home-assistant/core/issues/50815

This repository is about the documentation.
