### ISSUE TITLE
Mi_temp, binding/enryption key

### ISSUE THREAD

**Issue by mef-hamburg** [home-assistant/home-assistant.github.io#18087]
### Feedback

Newest update to this sensor does not seem to allow encryption key anymore?

I need to use the HACS integration now...

### URL

https://www.home-assistant.io/integrations/mitemp_bt/

### Version

2021.6.1

**Comment by frenck** [comment]
Hi there @mef-hamburg! 👋 

It sounds like you want to report a bug or issue with an Home Assistant Core integration, however, you have submitted documentation feedback. There is no amount of documentation that can be adjusted to fix such a thing 😉 

Please submit issues with Home Assistant Core integrations in the Core issue tracker:

<https://github.com/home-assistant/core/issues>


Thanks! 👍 

../Frenck
