### ISSUE TITLE
Low-pass filter initialization on restart.

### ISSUE THREAD

**Issue by bturrie** [home-assistant/home-assistant.github.io#18092]
### Feedback

It appears that the low-pass filter resets to 0 on restart rather than last value. That's very inconvenient my case I'm trying to filter on the total daily rain captured just before midnight. That means whenever I get a system update the filter takes days to recover. It's almost unusable. I guess I'm going to need to use a python script instead.

### URL

https://www.home-assistant.io/integrations/filter/

### Version

2021.6.2

**Comment by dgomes** [comment]
Shouldn't you be using the utility_meter for this use case ?

The filter sensor does reset **by definition**

**Comment by bturrie** [comment]
In industrial control systems at least, engineers generally generally initialize low pass filters to last known value after an outage shorter than the filter time. Otherwise you need to come up in manual control until until the filter has time to line out say 2-3  filter times to avoid process upsets. For what it's worth, not much, I have a Masters degree and over 30 years experience in process control. That said, I'll look at utility meter to see if it will do what I want. 

    On Saturday, June 5, 2021, 03:23:08 AM CDT, Diogo Gomes ***@***.***> wrote:  
 
 


Shouldn't you be using the utility_meter for this use case ?

The filter sensor does reset by definition

**Comment by dgomes** [comment]
The definition here is from the HA 😉 

We strive to keep writes to persistent storage to bare minimum not to wear out the SDCard's (most commonly used storage backend)

**Comment by bturrie** [comment]
In my case I need a filter that never resets, low pass filter would work if it didn't reset to 0 on a restart. Moving average would be less effective but okay unless it also resets on restart. Utility meter, assuming I completely understand, has a reset period which means It won't work for me. I'm trying to get an ongoing estimate of rainfall from my weather station that I can use to help me decide whether or not my lawn needs watering on a given day. The only way the low pass filter would work for my case is if I were to forgo most system updates.

    On Saturday, June 5, 2021, 03:23:08 AM CDT, Diogo Gomes ***@***.***> wrote:  
 
 


Shouldn't you be using the utility_meter for this use case ?

The filter sensor does reset by definition

**Comment by bturrie** [comment]
Alas it looks like appdaemon may be the only way to go.
    On Saturday, June 5, 2021, 05:12:47 PM CDT, Diogo Gomes ***@***.***> wrote:  
 
 


The definition here is from the HA 😉
 
We strive to keep writes to persistent storage to bare minimum not to wear out the SDCard's (most commonly used storage backend)

**Comment by frenck** [comment]
This is a feature request, not documentation feedback.

Please use our community forum to request new features, thanks!

../Frenck
