### ISSUE TITLE
Daikin AC - Finding API Key and Password

### ISSUE THREAD

**Issue by ryanerwin** [home-assistant/home-assistant.github.io#18095]
### Feedback

I wish the documentation gave more direction about how to validate that you have the correct API KEY and PASSWORD.

For example, my Daikin BRP072C42 included a sticker that shows the key, but I wasn't able to locate a password. I tried to use the factory default SSID as the password as mentioned in one github ticket, but no luck.

I found you can validate the API KEY with the `curl` procedure discussed here:
https://github.com/nzhook/hass_daikin_secure

Unfortunately still no idea how to validate the PASSWORD that home assistant requests to setup the Daikin AC.

I've attached a copy of my factory sticker, partially obscured, that you're welcome to add to the documentation.

![20210605_221015](https://user-images.githubusercontent.com/2156415/120896616-98e6aa80-c64c-11eb-91a2-7b50fd9a372f.jpg)

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2021.6.2

**Comment by ryanerwin** [comment]
Turns out that in my case, I just needed to leave the password EMPTY.

I tried a hundred permutations before my initial post, but I didn't think to try an empty password for some reason. Fortunately a friend from Daikin stumbled across the empty password, and it worked.

Anyway, if you could add something to the documentation like:

> When using BRP072XXX series devices, the sticker will show a "KEY"
> Use this exact same key as on the sticker in the "API Key" prompt
> For the password on these models, leave it empty.
> 
> ![image](https://user-images.githubusercontent.com/2156415/120995474-a0729480-c7af-11eb-96e7-5f6751ac3e5f.png)

**Comment by fredrike** [comment]
@ryanerwin What is unclear with this? (You clearly have a BRP072C unit so you should enter the KEY).

https://www.home-assistant.io/integrations/daikin/#supported-hardware
![Screenshot 2021-06-08 at 16 56 13](https://user-images.githubusercontent.com/676999/121208564-71752500-c87a-11eb-9aac-c25e715d0a0b.png)

I would be happy to help you open a pr for the documentation if you have suggestion on how to improve it.
