### ISSUE TITLE
Text message with an attachment information appears incorrect

### ISSUE THREAD

**Issue by Odis** [home-assistant/home-assistant.github.io#18090]
### Feedback

I attempted to use the attachments: command in the developer tools, and I get a message that attachments isn't valid.

### URL

https://www.home-assistant.io/integrations/signal_messenger/

### Version

2021.6.1

**Comment by frenck** [comment]
Hi there @Odis 👋 

Thank you for reaching out. I'm not sure if you are looking for support or want to report a bug with a Home Assistant Core integration; however, you have submitted documentation feedback?

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

If you want to report an issue with a Home Assistant Core integration, please create an issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
