### ISSUE TITLE
After update from HA 6.0 to 6.2 GC dont work

### ISSUE THREAD

**Issue by Jindra-git** [home-assistant/home-assistant.github.io#18093]
### Feedback

Hello.

After update from HA 6.0 into 6.2 GC stop to work. Problem with login.

### URL

https://www.home-assistant.io/integrations/garmin_connect/

### Version

2021.6.2

**Comment by HBDK** [comment]
i'm on 5.5 and i can't login either.

**Comment by aibaron** [comment]
I'd also like an update on this - Just got HA set up and Integrating with Garmin Connect isn't working. It spins at the login then fails.

**Comment by goldstar19** [comment]
Same issue for me as well, installed on TrueNAS - Home Assistant 2021.6.6

**Comment by The2rB** [comment]
Did you activate TFA on Garmin Connect?

**Comment by aibaron** [comment]
I never had two factor. I can set it up then disable it?

**Comment by DavidBurela** [comment]
I had it working previously. 
I just did a fresh install, and need to configure Garmin Connect integration again.
But now it gets stuck with a spinning wheel.

The same credentials let me log into the garmin comedy website directly. So it isn't a password or 2FA issue
I'm on core-2021.7.2, supervisor-2021.06.8

Edit:
After more research, seems there is a looong thread of the team trying to fix it. There was some success, but broke again. Seems they are still working on it

https://community.home-assistant.io/t/garmin-connect-integration-errors/284336

**Comment by geberl** [comment]
The version from https://github.com/cyberjunky/home-assistant-garmin_connect works for me, in HA 2021.6.6. The version that's comes bundled with HA 2021.6.6 still doesn't.

I found out about this solution in https://github.com/home-assistant/core/issues/50822#issuecomment-876201506
