### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by laurbede** [home-assistant/home-assistant.github.io#18107]
### Feedback

Perhaps this is clear for the experienced Hass users, but I fail to see how the  "**Script Example**" is able to control the group of lights as defined in the example "**configuration.yaml**" entry.  The "**Script Example**" refers to an entity_id "_light.kitchen_lights_" but such seems not to be defined in the  "**configuration.yaml**" entry. And when I add such definition in my Light Group definition, I receive a syntax error notice...
All the best.

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2021.6.2

**Comment by laurbede** [comment]
Just noticed #17408 , and understand that the entity_id is automatically generated on the basis of the "**name**" string which oddly is an optional parameter. Ok, say that I want to turn on the group named "Kitchen Lights", how should I define the "Actions" parameters ? For example, if I chose "Device" as [Action type], I can't find the "_light.kitchen_lights_" in the [Device] drop-down list-box. 
Many thanks for helping me out.

**Comment by frenck** [comment]
The documentation is correct.

I am not sure what you did differently that makes is not to work, however, for support please use our community forums or discord chat. Thanks!
