### ISSUE TITLE
tfiac intgeration

### ISSUE THREAD

**Issue by tammeryousef1006** [home-assistant/home-assistant.github.io#18103]
### Feedback

hello there
this integration is not working , i use other app than tfiac to control my ac , the name of the app intelligent ac . is there any chance to port the integration ?

many thanks in advance

### URL

https://www.home-assistant.io/integrations/tfiac/

### Version

2021.6.2

**Comment by frenck** [comment]
Hi there @tammeryousef1006 👋 

It seems you are either requesting a new feature or are trying to report a bug; However, you have submitted documentation feedback instead.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you want to report a bug with an existing integration, please report it in the issue tracker of the Home Assistant Core:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
