### ISSUE TITLE
Quiet mode is not working on 2021.6.2

### ISSUE THREAD

**Issue by Nunak** [home-assistant/home-assistant.github.io#18119]
### Feedback

After upgrade to 2021.6.2 is quiet mode mode not working.
![Screenshot 2021-06-07 at 20 10 16](https://user-images.githubusercontent.com/9319841/121068365-7b404f00-c7cc-11eb-946e-fb08d9dc9593.png)
It's not possible to enable those modes , they are grey(inactive).

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.6.2

**Comment by frenck** [comment]
Hi there @Nunak 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix a bug.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
