### ISSUE TITLE
description is wrong 

### ISSUE THREAD

**Issue by typxxi** [home-assistant/home-assistant.github.io#18113]
### Feedback

The first term has to be bslamp2 not 1 cause my tokenextractor shows for the Bedside Lamp 2 this yeelink.light.bslamp2
And on the bottom of my yeelight it states model "MJCTD02YL"

bslamp1 | MJCTD02YL | Xiaomi Mijia Bedside Lamp II
-- | -- | --

### URL

https://www.home-assistant.io/integrations/yeelight/

### Version

2021.6.2

**Comment by frenck** [comment]
`bslamp1` is used for both the MJCTD01YL and MJCTD02YL (bedside lamp 1 & 2).

The documentation has written this correctly.
