### ISSUE TITLE
growatt integration // Info on migrating from YAML to integration 

### ISSUE THREAD

**Issue by bockelaar** [home-assistant/home-assistant.github.io#18118]
### Feedback

if migrating from the depreciated YAML growatt sensor to the new integration it is unclear if historic data is retained or if new sensors with new data are created, losing history.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.6.2

**Comment by frenck** [comment]
This was documented in the release notes, everything is migrated.

See: <https://www.home-assistant.io/blog/2021/06/02/release-20216/#integrations-that-deprecated-yaml-import>

You can safely remove it from your YAML configuration.
