### ISSUE TITLE
Weekly re-authentication required

### ISSUE THREAD

**Issue by svdstra** [home-assistant/home-assistant.github.io#18112]
### Feedback

Hi,

I use the Lyric integration and it works flawless however... It asks me to re-authenticate almost every week.
Is there something that I should have done but didn't do properly?
After re-authentication everything works like a charm again for approximately 1 week.

Thanks,

Sander

### URL

https://www.home-assistant.io/integrations/lyric/

### Version

2021.6.2

**Comment by timmo001** [comment]
Wrong repository

This has already been raised on the Core project

**Comment by svdstra** [comment]
Hi timmo001,

Do you perhaps know which repository to use or where I can follow this issue in the core project?
Thanks.

svdstra

**Comment by frenck** [comment]
Hi there @svdstra 👋 

As stated above by Timmo already, this is not the correct repository. It seems like you wanted to report an issue with an Home Assistant integration, however, you've provided documentation feedback.

The issue tracker for Home Assistant itself can be found here:

<https://github.com/home-assistant/core/issues>

When in doubt, see: <https://www.home-assistant.io/help> on where to go.

Thanks 👍 

../Frenck

**Comment by svdstra** [comment]
Aha, Clear!

Thanks for your feedback!

Sander

Op ma 7 jun. 2021 om 12:37 schreef Franck Nijhof ***@***.***>:

**Comment by fergurza** [comment]
I have the same Issue, but I have to Reauthenticate Integration daily and I don't get where should I look for in case this is the wrong  place.

**Comment by frenck** [comment]
@fergurza The answer is in my previous message: <https://github.com/home-assistant/home-assistant.io/issues/18112#issuecomment-855814556>
