### ISSUE TITLE
Trend documentation still mentioning the States page

### ISSUE THREAD

**Issue by gigatexel** [home-assistant/home-assistant.github.io#18128]
### Feedback

The docs for Trend integration state:

`The current number of stored samples is displayed on the States page.`

But the States page is no longer supported.

### URL

https://www.home-assistant.io/integrations/trend/

### Version

2021.6.3

**Comment by frenck** [comment]
Wow, that piece of text is ancient! 😬

**Comment by gigatexel** [comment]
bump.

still present
