### ISSUE TITLE
integration option does not change value

### ISSUE THREAD

**Issue by DominikMoelter** [home-assistant/home-assistant.github.io#18126]
### Feedback

I'm running the "AVM FRITZ!Box Tools" integration in my HA instance. If I want to change the integration option "consider home" by entering a digit and confirm with return the value does not change, but it shows "Success". If you use the confirm button or use the slider/arrows to change the value and press return the change is successful.
Not sure if this is a bug from HA or the integration itself.

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.6.3

**Comment by chemelli74** [comment]
hi @DominikMoelter , this is the documentation repository and only issues on documentation should be reported here.

Your feedback was precious because we found a issue in the frontend. Is not specific for Fritz integration.
Will open a issue there so to fix it.

Simone

**Comment by chemelli74** [comment]
Here the reference: https://github.com/home-assistant/frontend/issues/9408
