### ISSUE TITLE
Onboarding map is unusable for setting location.

### ISSUE THREAD

**Issue by stephenhouser** [home-assistant/home-assistant.github.io#18121]
### Feedback

The map is nice and all but it's grey on black which is *very* hard to view/read and it does not show buildings or satellite view to help locate a building. 

I live in the country and it's nearly impossible to get the marker in the right place. Where can I just type in the Latitude and Longitude?

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2021.6.2

**Comment by frenck** [comment]
Hi there @stephenhouser 👋 

You cannot use coordinates directly, sorry.
Your suggestion is however, a nice feature request for the Home Assistant frontend, nevertheless, you have submitted documentation feedback.

Please submit suggestions for our frontend here:

<https://github.com/home-assistant/frontend/discussions>

Thanks! 👍 

../Frenck
