### ISSUE TITLE
cycle:  quarter-hourly = invalid option for Utility Meter - THIS DOES NO LONGER WORK 

### ISSUE THREAD

**Issue by typxxi** [home-assistant/home-assistant.github.io#18138]
### Feedback

```
  kwh_qh:
    source: sensor.kwh
    cycle:  quarter-hourly

```  

ERROR MESSAGE:
Invalid config for [utility_meter]: [kwh_qh_quarter-h] is an invalid option for [utility_meter]. Check: utility_meter->utility_meter->kwh_1_quarter-h. (See /config/configuration.yaml, line 398). 

This option might not look very usefull but at least for beginners it would be usefull to have that available. Testing will now take far longer ...

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.6.3

**Comment by dgomes** [comment]
Cannot reproduce.... 

Are you absolutely sure you copy-paste the EXACT configuration you have for the utility_meter ?
