### ISSUE TITLE
Does the Unifi Video integration for Home Assistant work when cameras are connected to Unifi Protect?

### ISSUE THREAD

**Issue by citykidz** [home-assistant/home-assistant.github.io#18140]
### Feedback

Unifi Video is going away.  Want to know if this integration for Home Assistant works when cameras are connected to the newer Unifi Protect.

### URL

https://www.home-assistant.io/integrations/uvc/

### Version

2021.6.3

**Comment by frenck** [comment]
This is not the place to get answers. I'm happy to adjust the documentation if a suggestion is provided.

You are more likely to get an answer on the community forums or Discord chat of Home Assistant.
