### ISSUE TITLE
video url ring doorbell

### ISSUE THREAD

**Issue by gertvanwij** [home-assistant/home-assistant.github.io#18141]
### Feedback

can you show a example of the video url

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2021.6.3

**Comment by frenck** [comment]
An example on how to use it is documented here:

<https://www.home-assistant.io/integrations/ring/#saving-the-videos-captured-by-your-ring-door-bell>

**Comment by gertvanwij** [comment]
Ja dat hebben we gedaan maar wat moeten we invullen als video url?
Ik den dat daar iets anders moet komen te staan dan video url.

Heb je daar een voorbeeld van?

Gr Gert

Op do 10 jun. 2021 13:22 schreef Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
? I don't get your question, it requests a state attribute containing the URL, there is nowhere or anything that needs to provide the URL manually.

**Comment by gertvanwij** [comment]
Ok thanks ik ga het verder proberen

Op do 10 jun. 2021 19:12 schreef Franck Nijhof ***@***.***>:

**Comment by gertvanwij** [comment]
when we push the doorbel we get this error

2021-06-16 20:14:25 ERROR (MainThread)
[homeassistant.components.automation.save_the_video_when_the_doorbell_is_pushed]
Save the video when the doorbell is pushed: Error executing script.
Invalid data for call_service at pos 1: invalid url for dictionary
value @ data['url']2021-06-16 20:14:25 ERROR (MainThread)
[homeassistant.components.automation.save_the_video_when_the_doorbell_is_pushed]
Error while executing automation
automation.save_the_video_when_the_doorbell_is_pushed: invalid url for
dictionary value @ data['url']


this is in the automations yaml


  alias: "Save the video when the doorbell is pushed"
  trigger:
  - platform: state
    entity_id: binary_sensor.voordeur_deurbel_ding
    to: "on"
  action:
  - service: downloader.download_file
    data:
      url: "{{ state_attr('camera.front_door', 'video_url') }}"
      subdir: "{{state_attr('camera.front_door', 'voordeur')}}"
      filename: "{{state_attr('camera.front_door', 'voordeurbeeld')}}"

we also made an folder config/downloads


what is wrong?

Gr Gert





<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op vr 11 jun. 2021 om 06:35 schreef Gert Wijk Van ***@***.***>:
