### ISSUE TITLE
call service failed

### ISSUE THREAD

**Issue by sirhideo** [home-assistant/home-assistant.github.io#18146]
### Feedback

Failed to call service remote.learn_command. Expecting property name enclosed in double quotes: line 17 column 9 (char 7040)
Same for send and delete command.
![image](https://user-images.githubusercontent.com/26427786/121452352-e1e28a00-c9d1-11eb-879e-951b9a59d6ba.png)

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2021.6.3

**Comment by frenck** [comment]
Hi there @sirhideo 👋 

It seems like you are in need for support or want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback. I cannot adjust documentation to fix issues :)

Cloud you please report issues here:

<https://github.com/home-assistant/core/issues>

Or, in case you need support, please use or Community Forum or Discord chat.

Thanks! 👍 

../Frenck
