### ISSUE TITLE
Ability to switch apps

### ISSUE THREAD

**Issue by ellipsiss** [home-assistant/home-assistant.github.io#18154]
### Feedback

The integration is fantastic!
Are we able to be able to put in the ability to switch the input to various apps such as Netflix, Spotify etc using the input value?
You are able to do it on Homebridge and would be very useful in hass
Example here: https://imgur.com/TBQMJcF

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2021.6.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
