### ISSUE TITLE
Plaato Integration breaks with upgrade to core-2021.6.3

### ISSUE THREAD

**Issue by bkuner-scuba** [home-assistant/home-assistant.github.io#18155]
### Feedback

I updated my Home Assistant OS system running on Raspberry Pi 4 from core-2021.6.2 to core-2021.6.3 earlier today.  After the upgrade I could see historical data in the graphs but it was not pulling new/current data.  I tried rebooting the Raspberry Pi and power cycled the Plaato Kegs I have with no improvement.  I did a restore to core-2021.6.2 and things are back to normal.

### URL

https://www.home-assistant.io/integrations/plaato/

### Version

2021.6.3

**Comment by frenck** [comment]
Hi there @bkuner-scuba 👋 

It seems like you want to report a bug with a Home Assistant integration, however, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix a bug with an integration.

Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
