### ISSUE TITLE
Energy Readings: KL130(US)

### ISSUE THREAD

**Issue by Steven-D-Morgan** [home-assistant/home-assistant.github.io#18172]
### Feedback

The KL130(US) is also confirmed to be working with energy monitoring template sensors. 

- Current Consumption
- Today's Consumption
- Monthly Consumption

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.6.4

**Comment by rytilahti** [comment]
The documentation page has an edit link at the bottom of the page, do you mind adjusting the documentation accordingly?  Thanks!

**Comment by Steven-D-Morgan** [comment]
For some reason it wouldn’t let me. Took me to that page :/

I apologize, just wanted to let others know what I found

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rytilahti** [comment]
No worries, thanks for reporting! I created a PR to add a generic note about bulbs exposing the emeter information.

I'm not sure why it didn't work for you, did you click on the edit button on the github page (on the right of the page) like shown in the screenshot? :-)
![image](https://user-images.githubusercontent.com/3705853/122613946-f71c8000-d085-11eb-906a-fa8d5b94c4a4.png)

**Comment by rytilahti** [comment]
There is a note about general energy readings support on bulbs ("Bulbs do generally report some energy consumption information, see the entity state attributes to find out what information is available."), so let's close this.
