### ISSUE TITLE
example for common use-case: setting duration interactively

### ISSUE THREAD

**Issue by richardwonka** [home-assistant/home-assistant.github.io#18177]
### Feedback

Hi there,

i am comfortable using scripts, scenes and blueprints, but this documentation appears to rely on knowledge or understanding that evades me. 

An example for a common use case of manually setting a timer when starting it would be very helpful. 

I am surprised that this appears to be such a complex matter. 

### URL

https://www.home-assistant.io/integrations/timer/n

### Version

2021.6.4

**Comment by frenck** [comment]
> An example for a common use case of manually setting a timer when starting it would be very helpful.


I'm not sure what you are looking for. A "kitchen" timer has many functionalities and use-cases.

**Comment by richardwonka** [comment]
That’s exactly the point; so many use cases and there is no example for even one. 

A simple 
- push a button
- Enter a time n
- Switch on a thing
- Wait for time n
- Switch off the thing

would do. 

What I haven’t found out: How to set a time at the start and then use it for the timer.

**Comment by frenck** [comment]
Honestly, a timer doesn't need use-cases IMHO. I've never seen a kitchen timer with a booklet with a bunch of use cases. It's a timer.

**Comment by richardwonka** [comment]
Yes, making one in HA should be as easy as that. 

And it isn’t. 

So we need either documentation or a change in UI.

**Comment by frenck** [comment]
In that case, I'm clearly not following your suggestion. I'm sorry 🤷‍♂️

**Comment by richardwonka** [comment]
I have tried to set up a timer for a smart plug and have not been able to figure out how to do it. 

I have looked for examples or blueprints and have not found any. 

This was surprising because it is such a common use case. 

My suggestion is to either add an example for a simple timer to the documentation or add a blueprint or add the functionality some other way. 

EDIT: if I knew how to, i would have done so already.

**Comment by frenck** [comment]
I'm not sure why Blueprints would even need this?

> This was surprising because it is such a common use case.

Your use case might be common, but your solution probably not. So I'm slowly starting to feel like you need support for automation, more than documentation for a timer...

**Comment by richardwonka** [comment]
Well, I don’t have a solution. If setting up an automation for something this simple and common is this hard, then something isn’t right. 

So, for a short-term solution, so i can get my timer, yes, i need support. 

For a long term solution, it should be more intuitive to do this, so future users won’t need support for such a common task.

**Comment by frenck** [comment]
I still don't know your use case...
Let talk a bit about what you are trying to do, as I think you are doing it too complicated/trying to use unconventional methods to solve your issue.

I feel this being an XY problem.

**Comment by richardwonka** [comment]
What I want to do:
- Push a button on lovelace or phone widget
- Be asked for a time in hours or hours and minutes 
- confirm
- A pre-defined device (wifi smart plug in this case) switches on (if it isn’t on already) and switches off after the time I entered. 

also: XY problem as in chromosomes? 😄

EDIT: I could also imagine entering a time in a lovelace tile and then confirming there. - I have managed to get an input_datetime helper into lovelace

EDIT: i am attaching my current setup. The “run” button does not work as expected. 
![2814FBD7-9566-4A84-845D-18B6514FD9B8](https://user-images.githubusercontent.com/304005/129609112-4c78a072-3ad0-4a61-9583-97db449e130f.jpeg)

**Comment by frenck** [comment]
> also: XY problem as in chromosomes?

Reporting problem X, but actually having problem Y.

**Comment by frenck** [comment]
> - Push a button on lovelace or phone widget
> - Be asked for a time in hours or hours and minutes
> - confirm

Asking for input on click on not functionality Home Assistant provides. Even with this timer you won't be able to achieve that.

**Comment by richardwonka** [comment]
Hmm. In the screenshot i added to the last post, i have a helper that I can adjust within lovelace. 

The missing link for me is how to access the value of this timer (time n) in an automation that
- Switch device on
- Delay (time n)
- Switch device off

**Comment by richardwonka** [comment]
Here is my “run” script:

it works as expected when i pass a delay time in the script. 

It does not pick up the time from the helper in hours or minutes 
```

1hr_charge:
  sequence:
  - type: turn_on
    device_id: ae2d683577ff78716d6637c67da21183
    entity_id: switch.60305084cc50e35fd01c
    domain: switch
  - delay:
      hours: '{{ input_datetime.he_charge_time.hours }}'
  - type: turn_off
    device_id: ae2d683577ff78716d6637c67da21183
    entity_id: switch.60305084cc50e35fd01c
    domain: switch
  mode: queued
  alias: Charge
  icon: mdi:motorbike
  max: 12
```

**Comment by frenck** [comment]
That is not a timer but a delay in the script.
The delay doesn't work like that.

I really recommend you on getting some more support at our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

As this has nothing to do with a timer, nor do you need a timer (or delay) to resolve this.

**Comment by richardwonka** [comment]
I am very confused what you mean by this not being a timer. I’ll head over to discord. 

Your time is much appreciated! Thank you!
