### ISSUE TITLE
change status update not fast, about 30 seconds

### ISSUE THREAD

**Issue by Donez84** [home-assistant/home-assistant.github.io#18171]
### Feedback

Hello,
  when I did a change status (i.e. from arm_home to away_home) the update is very slow, about 30 second to see the new new status in the UI.

### URL

https://www.home-assistant.io/integrations/ialarm/

### Version

2021.6.4

**Comment by Donez84** [comment]
> Hey there @RyuzakiKK, mind taking a look at this feedback as its been labeled with an integration (`ialarm`) you are listed as a [codeowner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L210) for? Thanks!
> (message by CodeOwnersMention)

I'm not the codeowner.

**Comment by frenck** [comment]
@lucaddr84 You are not the code owner indeed, but the bot pings the code owner in this case :)

Nevertheless, this is not a bug and correct. It is a polling integration, as documented as well:

![image](https://user-images.githubusercontent.com/195327/121782248-e44b0c80-cba8-11eb-89ce-d1c83b8380f1.png)

It means it will update the status of the data based on an interval.
