### ISSUE TITLE
just a small edit suggestion for better understanding

### ISSUE THREAD

**Issue by scheusal333** [home-assistant/home-assistant.github.io#18186]
### Feedback

just a clarification of the requirements part of the description: 

The requirements are:

1. You need to set up the Signal Messenger REST API (Please follow those [instructions](https://github.com/bbernhard/signal-cli-rest-api/blob/master/doc/HOMEASSISTANT.md))
2. You need a spare phone number to register with the Signal Messenger service. (you can find instructions of how to register the number in the link above)
3. Edit your configuration as shown below

### URL

https://www.home-assistant.io/integrations/signal_messenger/

### Version

2021.6.4

**Comment by frenck** [comment]
I think I don't fully understand the suggestion you are trying to make?

**Comment by scheusal333** [comment]
i just red the instructions for the integration and i missed the part that there is a separate installation needed besides the configuration.yaml change (although it is mentioned). Thats why i decided to suggest a small change to the description, to point it out more prominent, so anyone else will get it right away. 
Sorry if i used the wrong way to suggest it.
