### ISSUE TITLE
Lot's of new cloud based units are not supported 

### ISSUE THREAD

**Issue by vukisz** [home-assistant/home-assistant.github.io#18189]
### Feedback

See this thread for detauls: https://community.home-assistant.io/t/daikin-ac-integration-brp069c4x/270936/54

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2021.6.4

**Comment by frenck** [comment]
Hi there @vukisz,

Thanks for submitting documentation feedback, however, it is not clear how this is related to our current documentation?

Could you please clarify that?

../Frenck

**Comment by vukisz** [comment]
Well I would do ammendmend to this part:

> The European versions of the Wifi Controller Unit (BRP069A41, 42, 43, 45), which is powered by the Daikin Online Controller application. The new version of WiFi Controller Unit BRP069Bxx is also confirmed to work, tested and working devices are the BRP069B41 and BRP069B45.

Adding something like 

> "New Daikin units with cloud connection are currently not supported. Example - new daikin Perfera units. Could be more..". 

And I am not sure that this is only new daikin Prefera.

**Comment by frenck** [comment]
But the supported units are listed? Was this specific unit listed incorrectly?

**Comment by vukisz** [comment]
Ok it was just a suggestion.

**Comment by vukisz** [comment]
Ok it was only a suggestion. Closing
