### ISSUE TITLE
Supervisor update via CLI

### ISSUE THREAD

**Issue by Tokn59** [home-assistant/home-assistant.github.io#18188]
### Feedback

If you cannot update Supervisor via the GUI you can also not do it via CLI. 

Could you provide some clues as to what might cause this issue and how to resolve ? I see the following log entries in Supervisor:

21-06-14 12:54:46 INFO (MainThread) [supervisor.supervisor] Update Supervisor to version 2021.06.0
21-06-14 12:54:46 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-hassio-supervisor with tag 2021.06.0.
21-06-14 12:54:48 ERROR (SyncWorker_2) [supervisor.docker.interface] Can't install homeassistant/amd64-hassio-supervisor:2021.06.0 -> 500 Server Error for http+docker://localhost/v1.40/images/create?tag=2021.06.0&fromImage=homeassistant%2Famd64-hassio-supervisor: Internal Server Error ("Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: no such host").
21-06-14 12:54:48 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.UPDATE_FAILED - ContextType.SUPERVISOR / None
21-06-14 12:54:48 ERROR (MainThread) [supervisor.supervisor] Update of Supervisor failed: 
21-06-14 12:54:48 CRITICAL (MainThread) [supervisor.core] Can't update Supervisor! This will break some Add-ons or affect future versions of Home Assistant!

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2021.6.4

**Comment by frenck** [comment]
From the log posted:

`Get "registry-1.docker.io/v2": dial tcp: lookup registry-1.docker.io: no such host"`

Seems like you have a network configuration error/issue. If you need help with that, please use our community forums or discord chat.

Thanks! 👍 

../Frenck
