### ISSUE TITLE
Default port is 8088 not 8080

### ISSUE THREAD

**Issue by PCNZ** [home-assistant/home-assistant.github.io#18185]
### Feedback

Please update the default port in the documentation to be 8088, which is the default port used in the integration.
Port 8080 is the port for an indexer, not the default for the HTTP Event Collector which this integration actually uses.

### URL

https://www.home-assistant.io/integrations/splunk/

### Version

2021.6.4

### Additional information

https://github.com/home-assistant/core/blob/dev/homeassistant/components/splunk/__init__.py
DEFAULT_PORT = 8088

**Comment by Bre77** [comment]
Yep, agree this is a typo. You can edit the documentation directly in Github to correct this, otherwise I will when I can.
