### ISSUE TITLE
Shows broken image

### ISSUE THREAD

**Issue by hesspoint** [home-assistant/home-assistant.github.io#18180]
### Feedback

I set it up as described. Fridge is online. Still it shows a broken image in the dashboard.

What did I do wrong?

### URL

https://www.home-assistant.io/integrations/familyhub/

### Version

2021.6.4

**Comment by frenck** [comment]
Hi there @hesspoint 👋 

If the fridge is online, that would indicate you have set it up correctly. Which sounds an awful lot like a bug. However, you have submitted documentation feedback, and not a bug.

Could you please report your bug on the Home Assistant Core issue tracker?

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
