### ISSUE TITLE
Add Netowork monitoring sensors

### ISSUE THREAD

**Issue by The-Padi** [home-assistant/home-assistant.github.io#18181]
### Feedback

Would be great to alsow have sensors for the network interfaces, with RX and TX sensors 

### URL

https://www.home-assistant.io/integrations/glances/

### Version

2021.6.4

**Comment by fabaff** [comment]
The [`systemmonitor`](https://www.home-assistant.io/integrations/systemmonitor/) can do that. Also, the `netdata` can monitor various element of a system..

**Comment by The-Padi** [comment]
It's not to monitor the system on which Home Assistant is on. It's to monitor an other system that runs Glances.

**Comment by fabaff** [comment]
`netdata` should for a remote system. Nevertheless, the `glances` integration is still working as in the "old days". This integration should be re-written to get all available values like other sensor integrations.

Till this is happening. use a `rest` sensor with `http://0.0.0.0:61208/api/3/network` to get the network stats.

**Comment by frenck** [comment]
Hi there @Padi1111 👋 

Thank you for reaching out, it seems like you have a feature request, however, you have submitted documentation feedback instead.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
