### ISSUE TITLE
Server disconnected while attempting read

### ISSUE THREAD

**Issue by nfigueir** [home-assistant/home-assistant.github.io#18192]
### Feedback

I updated to the last version of HA and I am now getting the following error:

[homeassistant.components.rest.data] Error fetching data: http://pvoutput.org/service/r2/getstatus.jsp failed with Server disconnected while attempting read

If I call the service in the browser it works:

https://pvoutput.org/service/r2/getstatus.jsp?&key=<key>&sid=<id>

Returns:
20210614,17:15,4462,482,16407,805,0.455,NaN,NaN

The only difference seems to be that the platform is using http instead of https.

Tks

### URL

https://www.home-assistant.io/integrations/pvoutput/

### Version

2021.6.4

**Comment by frenck** [comment]
Hi there @nfigueir 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to fix a bug 😉 

Could you please raise an issue in the core issue tracker instead:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
