### ISSUE TITLE
Hint user about extra dashboards

### ISSUE THREAD

**Issue by Brtrnd** [home-assistant/home-assistant.github.io#18198]
### Feedback

I had created an extra dashboard aside from the default 'overview' that is created at installation; and set it as default.
Because of this it seemed that my yaml dashboard would never load. I did spend two hours trying to understand this, and no forum posts about it.

Before the title ADDING MORE DASHBOARDS WITH YAML
I would add the following phrase:

> if you've set the dashboards to yaml mode; but can't see changes; make sure that you are looking at the correct dashboard.
> Go "configuration" and click on "lovelace dashboards". Make sure that overview is the default dashboard and confirm it's set to yaml file.

### URL

https://www.home-assistant.io/lovelace/dashboards-and-views/

### Version

2021.6.4

**Comment by Brtrnd** [comment]
I also did this: https://github.com/home-assistant/home-assistant.io/compare/current...Brtrnd:patch-1

**Comment by frenck** [comment]
I cannot reproduce or understand the problem you are raising?
YAML & UI mode dashboards can be mixed and match. And yes, if you change a dashboard, you'd have to look at the dashboard you've changed to see the actual changes... That sounds logical already?
