### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bwo887** [home-assistant/home-assistant.github.io#18201]
### Feedback

After I enter the last command, Hass, it is kind of struck there. the prompt didn't return. what am i supposed to do next? if the command, hass, failed or stopped, what do i do next?

### URL

https://www.home-assistant.io/installation/windows

### Version

current

### Additional information

installation of home assistant

**Comment by frenck** [comment]
It doesn't return, that would be correct.

![image](https://user-images.githubusercontent.com/195327/122044154-738c3600-cddc-11eb-8e20-5f70be0bf96d.png)

While not returning, it is running and can be accessed as written in the instructions.

**Comment by bwo887** [comment]
Thank you for your reply. I tried to access it on the same pc, but the website didn't come up. I have vpn before on the PC but have since removed. I think the installation is corrupted somehow. How do I start fresh? I have windows 10, installed wsl 1 and 2, start wsl, followed the commands, ....Thank you
Sent from Yahoo Mail on Android 
 
  On Tue, Jun 15, 2021 at 6:21 AM, Franck ***@***.***> wrote:   


It doesn't return, that would be correct.



While not returning, it is running and can be accessed as written in the instructions.

**Comment by frenck** [comment]
So, you have provided documentation feedback, but it seems like you are in need of support.

In that case, I would recommend going to our community forums or Discord chat. You are more likely to get an answer there.

Please note; the installation method you are following there is called: Home Assistant Core, which is considered an advanced installation method. If you are not experienced with Python, we generally do not recommend using such an installation method.

Anyways, please head over to any of the above-listed community resources, I'm sure you'll find the help you need there.

../Frenck
