### ISSUE TITLE
Imrpovement: How to enable new devices to be tracked

### ISSUE THREAD

**Issue by senex44** [home-assistant/home-assistant.github.io#18215]
### Feedback

The documentation states:
_Note 1: All devices to be tracked, even the new detected, are disabled by default. You need to enable the wanted entities manually._

But there is no hint and no further reference where fo find a solution how the user can manually adapt these entities. It would be helpful to briefly explain this or at least give a link where to find more information

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.6.5

**Comment by chemelli74** [comment]
Enabling and disabling entities is a basic task, I don't think it should be described in every integration.

Just a brief summary: 

1. log into HA
2. Configuration
3. Entities
4. Select the wanted entity
5. Enable entity
6. Save

Simone

**Comment by senex44** [comment]
Thanks for your comment. 
I think my problem is, that I have the same problem as some others that I need to delete all tracker functions/integrations and known devices.yaml, and then set it up all new. Because currently, new devices are not added to my HA instance.
This confused me and without knowing about this issue, it is not clear how to get it running and enable new devices
