### ISSUE TITLE
What is the meaning of using # in the search field?

### ISSUE THREAD

**Issue by parautenbach** [home-assistant/home-assistant.github.io#18214]
### Feedback

I know this very much is a question about how the Google API works but there's no mention of using a # symbol in the [official docs](https://developers.google.com/calendar/api/v3/reference/events/list). However, the HA docs has a whole section on how to include a # but there's no explanation why one would do this. 

I've read a number of docs and did a number of searches on the HA community forum, and among these I've read about tags (and labels) but there also is no mention of this being identified by a #. I'd be happy to submit a PR to improve the docs but first I need to understand it better myself. 

I would like to include a reference to the [official docs](https://developers.google.com/calendar/api/v3/reference/events/list) as there is a convenient "try this API" feature which will make it a lot easier for users of this API to set up their HA integration. For example, I now know that this search API only does exact term matching after making everything lowercase and wildcards and other operators aren't supported. It also seems that including a hash anywhere in the search query makes no difference to the results. 

Lastly, it would be helpful if the docs stated that the default update interval is 15 min (I'll happily submit a PR for this too). 

### URL

https://www.home-assistant.io/integrations/calendar.google/

### Version

2021.6.5

**Comment by parautenbach** [comment]
I would still like to know someday. Commenting to keep this open, in case someone knows or can place a reference.

**Comment by parautenbach** [comment]
From the docs:

> If you use a # sign for search then wrap the whole search term in quotes. Otherwise everything following the hash sign would be considered a YAML comment.

What is the meaning of the `#`?

**Comment by drthanwho** [comment]
> What is the meaning of the `#`?

In YAML anything that has a `#` in front of is considered a comment. It's as simple as that. You can write anything you want and as long as it starts with `#` it will be ignored. 

Have a look here about a detailed explanation https://www.tutorialspoint.com/yaml/yaml_comments.htm

**Comment by parautenbach** [comment]
I think you misunderstood my question. I know a hash is a comment in YAML, but note the section I quoted: it's about when it's _quoted_ and _not_ a comment. A hash is used in the examples which make it seem like it potentially has a special meaning to the integration/Google. 

![3EFC1794-1D35-48D8-9B3B-41F963F24124](https://user-images.githubusercontent.com/743320/140457643-53fb989e-904a-4040-a28a-e2fa3c510ca6.jpeg)

**Comment by frenck** [comment]
Aah I see the confusion, but that is a google calendar feature and not Home Assistant specific.

The hashtag in those searches indicate a tag search.

**Comment by drthanwho** [comment]
I see now. I was under the impression it meant if what you search actually has a hashtag in the name of your event

**Comment by frenck** [comment]
Anyways, whatever it is... it is the search Google provides with its calendars and not something specific to Home Assistant. So your question is better answered by the Google documentation/support pages in this case.

**Comment by parautenbach** [comment]
Thanks for chiming in, @frenck – you're a busy man, so it's really appreciated. 

Yes, I was aware this might be a Google-specific question, but struggled to find any relevant info. I tried to highlight that in the my original report. 

My intention is still to submit a PR for the HA docs to some Google help pages – unless linking to such 3rd party content is discouraged (I don't think so, from what I've seen). 

Regardless, my question here has been answered sufficiently, so I will do my search in a new direction and separately submit my doc PR. I think it would be useful to other users in order to really leverage the power of this integration.
