### ISSUE TITLE
Show mmol/l

### ISSUE THREAD

**Issue by 2knarf** [home-assistant/home-assistant.github.io#18211]
### Feedback

Hi, would it be possible to have an option to show values in mmol/l?

### URL

https://www.home-assistant.io/integrations/nightscout/

### Version

2021.6.5

**Comment by frenck** [comment]
Hi there @2knarf 👋 

I really don't know, but if you have questions, you are more likely to get an answer on our community forums or Discord chat!

../Frenck

**Comment by marciogranzotto** [comment]
btw, we had a partial PR for implementing this, but the author didn't finish it (https://github.com/home-assistant/core/pull/41382)
I will try to pick it up when I have some spear time (which is hard to come by)
