### ISSUE TITLE
After update into HA 6.5 doesnt work

### ISSUE THREAD

**Issue by Jindra-git** [home-assistant/home-assistant.github.io#18222]
### Feedback

Hello. 

After update into HA 6.5 stop working. Problem with login - dont respond

### URL

https://www.home-assistant.io/integrations/garmin_connect/

### Version

2021.6.5

**Comment by thecode** [comment]
Hi @Jindra-git 
This is a place for documentation issues, please open an issue here:
https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml

Try to supply as much as information as possible there, which versions did work, what doesn't work, what do you see in the logs.
