### ISSUE TITLE
Selecting source

### ISSUE THREAD

**Issue by boggiano** [home-assistant/home-assistant.github.io#18227]
### Feedback

In the paragraph "Selecting a source" it's written only:
"It’s possible to switch between the 2 sources TV and HDMI."
but it' not to clear how to use this.

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2021.6.5

**Comment by chemelli74** [comment]
Please check the media player entity:

![image](https://user-images.githubusercontent.com/57354320/123350680-c479f800-d55b-11eb-8e1a-1b2238cbf833.png)

Simone

**Comment by boggiano** [comment]
Thank Simone,
I was thinking about yaml code: my bad.

Thanks
