### ISSUE TITLE
scrape

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#18228]
### Feedback

how do you get the information visible in hassio eg this from the page
sensor:
# Example configuration.yaml entry
  - platform: scrape
    resource: https://www.home-assistant.io
    name: Release
    select: ".current-version h1"
    value_template: '{{ value.split(":")[1] }}'

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2021.6.5

**Comment by frenck** [comment]
Hi there @pa0dow 👋 

That snippet creates a sensor entity, which can be used, for example, to add to a Lovelace dashboard or to be used in automations.

For this specific example, we have version information available using the version integration (<https://www.home-assistant.io/integrations/version>) so, no need to use scraping for that 😉 

If you need general support, it is generally recommended to use our community forum or Discord chat. Those channels you are more likely to get answers on how to use parts of Home Assistant or how things work. We try to keep our issue trackers for tracking bugs and concrete documentation feedback.

Thanks! 👍 

../Frenck

**Comment by ghost** [comment]
Bedankt Frank,
Al die voorbeelden die op die hassio page staan zijn mij duidelijk.
Ik vroeg het bij deze als een voorbeeld.
Er staat nergens in voor mij begrijpelijke taal hoe ik de ingelezen data kan tonen in bijv. lovelace of in een ander overzicht.
Ook het adres dat jij mij toestuurde (zie hieronder) geeft mij geen duidelijk voorbeeld hoe ik ze tevoorschijn kan “toveren”.
Gr
Dick pa0dow

Verzonden vanuit Mail voor Windows 10

Van: Franck Nijhof
Verzonden: vrijdag 18 juni 2021 11:49
Aan: home-assistant/home-assistant.io
CC: pa0dow; Mention
Onderwerp: Re: [home-assistant/home-assistant.io] scrape (#18228)

Hi there @pa0dow 👋
That snippet creates a sensor entity, which can be used, for example, to add to a Lovelace dashboard or to be used in automations.
For this specific example, we have version information available using the version integration (https://www.home-assistant.io/integrations/version) so, no need to use scraping for that 😉
If you need general support, it is generally recommended to use our community forum or Discord chat. Those channels you are more likely to get answers on how to use parts of Home Assistant or how things work. We try to keep our issue trackers for tracking bugs and concrete documentation feedback.
Thanks! 👍
../Frenck
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus
