### ISSUE TITLE
Cannot find sources when building automation

### ISSUE THREAD

**Issue by jgsieve** [home-assistant/home-assistant.github.io#18225]
### Feedback

I am using this with my 4 zone monoprice with IP, i am able to power on and select sources of each zone from the web UI, but i cannot find any options in automation to automatically select a source. I do see a number of extra zones that the integration page mentions, but those are not selectable. Any help is appreciated. Thanks

### URL

https://www.home-assistant.io/integrations/monoprice/

### Version

2021.6.5

**Comment by OnFreund** [comment]
Each zone is an instance of a media player, so you can set its source with the `media_player.select_source` service, just like you would for any other [media player](https://www.home-assistant.io/integrations/media_player/).
