### ISSUE TITLE
RM4C Pro Request

### ISSUE THREAD

**Issue by DannyFreedhorn** [home-assistant/home-assistant.github.io#18236]
### Feedback

Would the **RM4C PRO** be added to the Broadlink integration soon? 

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2021.6.5

**Comment by frenck** [comment]
Hi there @DannyFreedhorn 👋 

I really don't know. This open-source project relies on contributions from other volunteers, so it is hard to give you an answer to that question. That said, you have submitted documentation feedback, and I'm kinda sure you wanted to submit a feature request.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
