### ISSUE TITLE
Using cover for garden irrigation

### ISSUE THREAD

**Issue by raidnet-ms** [home-assistant/home-assistant.github.io#18233]
### Feedback

Hello, I wrote a yaml script for my esp device to manage 3 electrovalves for the irrigation of the garden. Actually i use this script with switch and gpio and a timer to push a 9v DC signal to the bistable solenoid on the valve.

I think that this script works in a similar way a time based cover do, so what about implementing a device class for the cover mechanism that actually can be used for this purpouse?

### URL

https://www.home-assistant.io/integrations/cover/

### Version

2021.6.5

### Additional information

new feature

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
