### ISSUE TITLE
Failed to add Integration in Home Assistant

### ISSUE THREAD

**Issue by silentsw** [home-assistant/home-assistant.github.io#18247]
### Feedback

When adding Tuya Integration in HA and entering Tuya credentials, it will not recognise and return in "Invalid authentication" message.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.6.5

**Comment by bqtran** [comment]
I'm also getting this "Invalid authentication" error. I am on 2021.6.6 and my account is registered with the "Smart Life" option.

**Comment by frenck** [comment]
Hi there 👋 

It seems like you two want to report an issue with an integration, however, you have submitted documentation feedback. Unfortunately, there is no amount of documentation I can adjust to make an integration suddenly work. Please file an issue with the Home Assistant Core issue tracker instead:

<https://github.com/home-assistant/core>

Thanks! 👍 

../Frenck
