### ISSUE TITLE
Unwatched tag does not work for TV shows

### ISSUE THREAD

**Issue by ETHREAL1** [home-assistant/home-assistant.github.io#18246]
### Feedback

This may be the wrong place to put this but with that said. The "unwatched" media_content_id Tag does not work for TV shows. This is the one time I would like to use the unwatched tag so that it would just find the first unwatched episode to play it.

### URL

https://www.home-assistant.io/integrations/plex/

### Version

2021.6.5

### Additional information

Again, this may be the wrong spot to put this but I know of no way to contact the makers of the integration so...

**Comment by jjlawren** [comment]
As it tells you when you open a new issue, feature requests should go on the forums: https://community.home-assistant.io/c/feature-requests/13.

However you're in luck with this one as there's a PR in progress which aims to add this feature: https://github.com/home-assistant/core/pull/51180.
