### ISSUE TITLE
Salt Cell Control

### ISSUE THREAD

**Issue by jefframsey0** [home-assistant/home-assistant.github.io#18243]
### Feedback

Great work on the integration. Can you add salt cell control? Looking to set salt cell level 0-100. Thanks

### URL

https://www.home-assistant.io/integrations/screenlogic/

### Version

2021.6.5

**Comment by dieselrabbit** [comment]
This would need support added in the base library. Please make this request here: https://github.com/dieselrabbit/screenlogicpy so it can be tracked.
Once you do, I believe you'd want to close this issue as this is the documentation-specific project for Home Assistant.
Thanks.

**Comment by jefframsey0** [comment]
> This would need support added in the base library. Please make this request here: https://github.com/dieselrabbit/screenlogicpy so it can be tracked.
> Once you do, I believe you'd want to close this issue as this is the documentation-specific project for Home Assistant.
> Thanks.

Thanks will do!
