### ISSUE TITLE
Instructions missing on finding device IDs

### ISSUE THREAD

**Issue by varyamereon** [home-assistant/home-assistant.github.io#18256]
### Feedback

Next to Flap IDs it says

> Flap ID to change - see below for instructions on finding device IDs

however these instructions are not included.

### URL

https://www.home-assistant.io/integrations/surepetcare/

### Version

2021.6.6

**Comment by frenck** [comment]
As far as I was aware, those are no longer needed, but I guess I am wrong then 😬 

@benleb Could you clarify how this works after the refactoring?

**Comment by benleb** [comment]
right @frenck, they are not needed to be supplied by the user and will be fetched automatically :) 

With the next (big) update coming soon, we will switch to the HA config flow "thing" and the integration can be fully configured via the ui :)

**Comment by robchandhok** [comment]
@benleb I'd be happy to work on the docs (entities and other instructions) but should I wait until your aforementioned "big update"?  Also happy to test if that's useful.  and thank you!

**Comment by benleb** [comment]
Hey, [sureha](https://github.com/benleb/sureha) is the upcoming version I am currently porting to get merged into home assistant (https://github.com/home-assistant/core/pull/52206) :) If you keep that in mind, I think theres no problem 👍
