### ISSUE TITLE
Need more information about unique_id and the importance in MQTT discovery

### ISSUE THREAD

**Issue by hyperbolic2346** [home-assistant/home-assistant.github.io#18253]
### Feedback

I am coding an esp with mqtt discovery and I was unable to add the device to a room in home assistant. The UI was good to point me to unique_id, but there is not much conversation about it on the mqtt discovery page. Unique id is mentioned and a best practice given for the discovery path, but no real indication of the importance of adding a unique id to the payload.

### URL

https://www.home-assistant.io/docs/mqtt/discovery/

### Version

2021.6.5

**Comment by frenck** [comment]
The MQTT documentation in the end-user website described the outer working, for the inner working, please consult the developer documentation.

Information about entities (and all entity platforms):
<https://developers.home-assistant.io/docs/core/entity>

For requirements around unique_ids:

<https://developers.home-assistant.io/docs/entity_registry_index#unique-id-requirements>
