### ISSUE TITLE
"PictureStyle" does not work on all Philips TV's

### ISSUE THREAD

**Issue by bgoncal** [home-assistant/home-assistant.github.io#18263]
### Feedback

I have the Philips TV "The One" 65" with Android TV and the command "PictureStyle" does not work, the rest works fine.

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2021.6.6

**Comment by elupus** [comment]
Then it's likely unsupported by the TV. We can't do much than update the docs to indicate that possibly.
