### ISSUE TITLE
Lyft integration no longer works due to API Change

### ISSUE THREAD

**Issue by zenofjazz** [home-assistant/home-assistant.github.io#18272]
### Feedback

they have changed the api/authentication.

### URL

https://www.home-assistant.io/integrations/lyft/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @zenofjazz! 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix a changed API or authentication handling.

Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
