### ISSUE TITLE
Must use https for call back URL

### ISSUE THREAD

**Issue by ChrisMolanus** [home-assistant/home-assistant.github.io#18278]
### Feedback

Google will not allow the user to use a call back non secure URL.
And since the user would need a TLS certificate to get Home Assistant to use HTTPS this is a little more work that your average user can do.
![Nest_no_http](https://user-images.githubusercontent.com/4310394/123099164-39511300-d432-11eb-95a4-1824e76f36f9.png)

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.6.6

### Additional information

I actually don't know how to fix this.
It makes sense that this connection should be HTTPS since it will contain your API key and secret, a basic packet sniffer could give a third party access to your Nest data.

**Comment by frenck** [comment]
> Google will not allow the user to use a call back non secure URL.

That is correct, the documentation also only lists `https://...` based URLs.

> And since the user would need a TLS certificate to get Home Assistant to use HTTPS this is a little more work than your average user can do.

Yes/no. Depends a bit. There are multiple options available for this. Using the DuckDNS or NGinx proxy add-ons, or using the Home Assistant Cloud service to tunnel your traffic. These solutions are generally doable for an average user (The Cloud service is actually really easy to do for anyone).

That said, this is more a support question/discussion and out of scope for this integration.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Those places generally are more suited to helping you with your journey 🗺️ 

../Frenck 🚂
