### ISSUE TITLE
Ezviz Home Assistant - unexpected error

### ISSUE THREAD

**Issue by JayMcG** [home-assistant/home-assistant.github.io#18287]
### Feedback

Hi, I am trying to link my HA to the Ezviz integration, however, I keep getting an abort message with an unexpected error. 

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @JayMcG 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to fix an unexpected issue with the integration.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
