### ISSUE TITLE
Mismatching Documentation

### ISSUE THREAD

**Issue by ajhurst** [home-assistant/home-assistant.github.io#18282]
### Feedback

I am trying to learn how to use Home-Assistant, but all the documentation I can find does not match what my HA does.  Nor can I find what version of HA I am using, in order to cross-check.

This makes life very difficult for a newbie!

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2021.6.6

**Comment by frenck** [comment]
You can find your Home Assistant version by going to "Configuration" in the sidebar and click on the "Info" item in the menu presented.

![image](https://user-images.githubusercontent.com/195327/123228382-b08bb300-d4d5-11eb-9869-bc92bf507d0d.png)


In my case, I run the development version (2021.7.0.devXXXXX), our current latest version is listed on our home page (at the time of writing 2021.6.6). Our documentation should always match the latest stable version.
