### ISSUE TITLE
Colours for graph lines

### ISSUE THREAD

**Issue by usdk1** [home-assistant/home-assistant.github.io#18299]
### Feedback

if you have several graphs for different time periods you may want identical parameters to be displayed in identical colors on different graphs. So it would be very helpful to be able to set a specific colour for one entity.

### URL

https://www.home-assistant.io/lovelace/history-graph/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @usdk1 👋 

Thank you for reaching out. It seems like you want to suggest a feature, however, you have submitted documentation feedback.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
