### ISSUE TITLE
google console actions web gui flow has been changed

### ISSUE THREAD

**Issue by victorputroagung** [home-assistant/home-assistant.github.io#18307]
### Feedback

the account linking steps are changed. but you can still access it through Test tab, settings, and the account linking is there.

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2021.6.6

**Comment by frenck** [comment]
Google seems to change this about every month, which is really annoying.
However, feel free to provide the correct steps, you can edit the page as well and suggest an edit.
