### ISSUE TITLE
Integration is for Automate Pulse Hub Version 1

### ISSUE THREAD

**Issue by tallcuss** [home-assistant/home-assistant.github.io#18306]
### Feedback

The Rollease Acmeda Automate document describes the Automate Pulse version 1 Hub Integration which uses the aiopulse API, both written by atmurray. The version 1 hub is no longer sold and is replaced by the Automate Pulse Pulse (version) 2 Hub.

An Integration for the Pulse 2 Hub has been written by sillyfrog (see github.com/sillyfrog/Automate-Pulse-v2). It uses the aiopulse2 API (see github.com/sillyfrog/aiopulse2) which is modified version of the aiopulse API.

Currently the Pulse 2 Integration is awaiting review for inclusion in HA, and therefore is designed to be added as a custom HACS repository.

### URL

https://www.home-assistant.io/integrations/acmeda/

### Version

2021.6.6

**Comment by frenck** [comment]
So your suggestion is to add a mention that the integration only works with v1, right?

**Comment by tallcuss** [comment]
Hi Franck,

Yes, that would be the very least to be done, so people (like myself) don't fall into the trap of purchasing a Pulse 2 Hub, installing this Integration in the belief it will work for them, and only later and with much frustration, discover it does nothing at all.

After thinking about it a bit more, perhaps this page should describe both versions. What do you think?

I'm willing to have a go at producing an initial draft. What tool is used to produce the html for these pages? Do you know how to find the current status of the Pulse 2 Integration (github.com/sillyfrog/Automate-Pulse-v2)?

Cheers, Ron

**Comment by thecode** [comment]
You can edit the page in one of the following options:
1. Use GitHub interface, by using "EDIT" from the integration page at the bottom:
![image](https://user-images.githubusercontent.com/1858925/123557920-3f315600-d79c-11eb-8398-45733f330aed.png)
2. Read here: https://developers.home-assistant.io/docs/documenting
If you have experience with working using dev containers in VS code there is also a ready made container for that.

You can check the status for the pull request to add V2 here, please don't comment there and ask questions about when it is going to be finished, the discussion there should kept technical, any other comments will just delay others from reviewing it:
https://github.com/home-assistant/core/pull/39501

**Comment by mgriffin13** [comment]
@thecode I'm not sure if you saw https://github.com/home-assistant/home-assistant.io/pull/14352, which already includes all the documentation for v2, as well as including the blurb that the current integration is v1 only.

**Comment by frenck** [comment]
The documentation has been adjusted for the next release.
