### ISSUE TITLE
Clarification of nfandroidtv options needed

### ISSUE THREAD

**Issue by rrroonn** [home-assistant/home-assistant.github.io#18309]
### Feedback

Happy with the integration but the doco needs to clarify the difference between "duration" and "timeout" settings/options.

### URL

https://www.home-assistant.io/integrations/nfandroidtv/

### Version

2021.6.6

**Comment by thecode** [comment]
Thanks @rrroonn, I hope the description is better now, closing the issue, feel free to reopen if you think it is still not clear.
