### ISSUE TITLE
Not working in HA 2021.6.6

### ISSUE THREAD

**Issue by Papi77** [home-assistant/home-assistant.github.io#18300]
### Feedback

New install of OS Version 6.1 with HA Core 2021.6.6 -> the integration doesn't work. (After entering credentials - the circle keeps rotating endlessly...)

### URL

https://www.home-assistant.io/integrations/garmin_connect/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @Papi77 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Unfortunately, there is no amount of documentation I can adjust to fix an integration.

Could you please report an issue in the Home Assistant issue tracker instead?

<https://github.com/home-assistant/core/issues>

(PS: Please be sure to check if an issue was already reported before submitting one).

Thanks! 👍 

../Frenck
