### ISSUE TITLE
Can't install Buienradar

### ISSUE THREAD

**Issue by HansHM** [home-assistant/home-assistant.github.io#18312]
### Feedback

Success!
Created configuration for 53.18546,5.54123.

The integration could not be loaded, try to restart Home Assistant.

After restart it is not loaded. 

### URL

https://www.home-assistant.io/integrations/buienradar/

### Version

2021.6.6

### Additional information

Logger: homeassistant.setup
Source: components/buienradar/__init__.py:140
First occurred: 3:40:26 PM (1 occurrences)
Last logged: 3:40:26 PM

Error during setup of component buienradar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/buienradar/__init__.py", line 35, in async_setup
    camera_configs = _filter_domain_configs(config, "camera", DOMAIN)
  File "/usr/src/homeassistant/homeassistant/components/buienradar/__init__.py", line 140, in _filter_domain_configs
    configs += [x for x in config[entry] if x["platform"] == platform]
  File "/usr/src/homeassistant/homeassistant/components/buienradar/__init__.py", line 140, in <listcomp>
    configs += [x for x in config[entry] if x["platform"] == platform]
TypeError: string indices must be integers

Home Assistant 2021.6.6
Frontend version: 20210603.0 - latest

**Comment by frenck** [comment]
Hi there @HansHM 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation that I can adjust to fix a bug in the code base.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>


Thanks 👍 

../Frenck
