### ISSUE TITLE
Area 1 Not Loading

### ISSUE THREAD

**Issue by rjbuss** [home-assistant/home-assistant.github.io#18318]
### Feedback

I have successfully added the Elk control to my Home Assistant. It has added areas 2-8 which I do not use and did not add Area 1 which I do use. The zones for Area 1 were added. What did I do incorrectly? Thank you!

### URL

https://www.home-assistant.io/integrations/elkm1/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @rjbuss 👋 

I'm not sure if you try to report an issue with an integration, or are seeing for support. Anyways, you have submitted documentation feedback, which is probably not the right location.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

If you want to report a bug with an Home Assistant integration, you can do so here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck

**Comment by rjbuss** [comment]
Thank you!



Best Regards,

Dick Buss
Manufacturers’ Representative
Dick Buss & Associates, LLC
711 N. Lynndale Dr.
Suite 2G
Appleton, WI 54914

o: 800-347-2104 d: 608-987-2100 m: 608-345-2104

w: www.dba-llc.com<http://www.dba-llc.com/>  e: ***@***.******@***.***>

Sales: ***@***.******@***.***>  Service: ***@***.******@***.***>

Connect with me on [IN] <http://www.linkedin.com/in/DickBuss>    Like us on [Facebook] <http://www.facebook.com/pages/Dick-Buss-Associates-LLC/167829999900498?ref=hl>     Follow us on [IN] <https://www.linkedin.com/company/dick-buss-&-associates-llc>

“Bridging the gap between the manufacturers we represent and the customers we serve for 35 years.”
