### ISSUE TITLE
HTML5 Push Notifications and Home Assistant Cloud

### ISSUE THREAD

**Issue by Aasikki** [home-assistant/home-assistant.github.io#18319]
### Feedback

I think the documentation could state more clearly that if I'm using Home Assistant Cloud, I'm in all good and can proceed with setting it up. Personally I had a little itch that it may not work when trying to set it up as a has cloud user, but of course it ended up working fine.

### URL

https://www.home-assistant.io/integrations/html5/

### Version

2021.6.6

**Comment by thecode** [comment]
Home assistant has various options for performing the same things, I don't think an integration needs to state that if you have another solution this is not needed, just to add to that, there are other options for notifications which also doesn't require Home Assistant Cloud.
Integrations in Home Assistant should state what they do, this is an integration for sending HTML5 notifications for Chrome/Firefox, it is not identical to the Home Assistant cloud solution.

**Comment by Aasikki** [comment]
I was thinking more about the part where ssl and domain is required to set up the hmtl5 notifications and a proxy won't work. I'm still fairly new to this kind of stuff and never bothered to learn how home assistant cloud work's so I wasn't sure if it had those things included or if it was configured in a way compatible with the html notifications. I just thought it might be a good idea to tell about that in the documentation just for other people like me.

**Comment by thecode** [comment]
I think it is mentioned few times:
![image](https://user-images.githubusercontent.com/1858925/123558164-908e1500-d79d-11eb-8d95-534858ef07ec.png)

**Comment by Aasikki** [comment]
Yeah so the problem is that someone new to this like me may not understand that they already have those things you rounded out in the image, when they are subscribed to home assistant cloud. For those who don't use home assistant cloud and did the manual method for ssl etc. that page is probably clear as a day.

Then again probably not many newbies even try to set this up looking at the fact it's only used by 1.8% of active home assistant installations...

This is definitely not a big deal or anything, just wanted to help in case someone else as dumb as me tries to set this up lol.
