### ISSUE TITLE
Guide for Troubleshooting and "beyond getting started"

### ISSUE THREAD

**Issue by bassclarinetl2** [home-assistant/home-assistant.github.io#1832]
Thought I'd let y'all know that I've written a guide to get some component going and how to fix some problems.  It's up here https://github.com/bassclarinetl2/hass/blob/master/docs/AQSG.md.  Bleed as needed over there if something is missing.

**Comment by JonMurphy** [comment]
Hi Will - On January 18 I installed HA and become an HA noob.  I just came across your **Notes for NOOBS** above.  Since I'm going thru HA for the first time I figured I could help.  

FYI - here is where I am stuck:
<img width="422" alt="screen shot 2017-01-30 at 8 21 31 pm" src="https://cloud.githubusercontent.com/assets/15616372/22450803/bf3602f0-e72e-11e6-96cf-ae2bd9a06328.png">

Is it ok if I offer a few suggestions to AQSG.md?

**Comment by bassclarinetl2** [comment]
Of course.  What can I add for you?

**Comment by JonMurphy** [comment]
Keep in mind these are just my 2 cents worth as a NOOB.  Feel free to trash any or all of them.  So here are my suggestions:

- Do just the single configuration file approach for **Notes for NOOBS** page. And do the multiple configuration files info on a Chapter 2 NOOBS page.  If you feel strongly about adding the "using multiple configuration files" section maybe add it as a detail at the bottom of the page.  
- Remove all of the TLAs (three letter acronyms) for NOOB-type pages.  
- Use the entire Title for the pages you reference.  So maybe change this:

> Assuming that you have used the [All in One (AIO) script](https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/), first let's change to the configuration directory.

to this:
> Assuming that you have used the [Raspberry Pi All-In-One Installer](https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/) script first let's change to the configuration directory

From either the Forum or the Getting Started pages (not what is written in the AQSG.md document): an item that confused me was the editing of the `configuration.yaml` file.  I've seen it written as you mentioned:
```
cd /home/homeassistant/.homeassistant/
sudo nano configuration.yaml
```
But I thought I saw it also written as (I cannot locate where at the moment):
```
sudo su -s /bin/bash homeassistant
cd /home/homeassistant/.homeassistant/
nano configuration.yaml
```
Which is the right way (or which is better)?

You may want to mention the `secrets.yaml` on a Chapter 2 NOOB page.

Hope this feedback helps.  I'll write additional thoughts soon.

**Comment by bassclarinetl2** [comment]
Thanks for the input. I write from the point of view of someone whose dealt
with the product before so its nice to have an outside point of view.

**Comment by bassclarinetl2** [comment]
Hello Jon,

I've made some changes for a ver 1.1 (some items are still omitted) but
lemme know what you think.

**Comment by bassclarinetl2** [comment]
Also lets go ahead and switch over to  the tracker on my repo so we dont spam the main issue tracker.   https://github.com/bassclarinetl2/hass/issues/2
