### ISSUE TITLE
how to get cookies to work please 

### ISSUE THREAD

**Issue by vjmaz** [home-assistant/home-assistant.github.io#18324]
### Feedback

I'm trying to add my Sems portal as a https webpage : https://www.semsportal.com  while using a Webpage Card Configuration card ! ... I press the button to accept cookies and does nothing !!! I need it please someone help ...

### URL

https://www.semsportal.com/PowerStation/PowerStatusSnMin/8bc1a27e-560d-47a1-867b-a5116aadfb06

### Version

2021.6.6

### Additional information

<html>
<body>

SE OF COOKIES | 1.Cookies are text files that are stored on the computer of the visitor to the website, allowing the visitor to be recognized on an anonymous basis. Cookies in general can be blocked or deleted by adjusting your browser settings.2.By using this website, you consent to the use of our websites being analyzed in the manner described above.
-- | --

</body>
</html>

**Comment by frenck** [comment]
Thank you for reaching out. We use this GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
