### ISSUE TITLE
cover update?

### ISSUE THREAD

**Issue by murcin** [home-assistant/home-assistant.github.io#18325]
### Feedback

there is time to make some update or modification... I mean TILT - very useful option for shutter as cover, but now there is not possible to do it. that is only one option to add and would be very useful to handle :)

### URL

https://www.home-assistant.io/integrations/ads/

### Version

2021.6.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
