### ISSUE TITLE
Warn about incompatibility with packages

### ISSUE THREAD

**Issue by usul0184** [home-assistant/home-assistant.github.io#18323]
### Feedback

Many users have been surprised that it is impossible to use new-style template sensors with packages, as shown in this [feature request](https://community.home-assistant.io/t/allow-integration-template-in-packages/305865).  This is extremely counter-intuitive and deserves a warning to users, especially if no alternative method of organizing configuration files is presented.

### URL

https://www.home-assistant.io/integrations/template/

### Version

(I don't see a version at the bottom of the page)

**Comment by frenck** [comment]
This integration is not any different than any other integration. Why would this need a warning and not all other integrations? That sounds inconsistent.

**Comment by usul0184** [comment]
Thanks so much for looking at this!  I'm not sure most people would agree that the template integration is no different than any other integration.  The template integration is more like the switch, light, automation, or groups integrations--all of which are listed as explicitly able to be included in packages in the [package documentation](https://www.home-assistant.io/docs/configuration/packages/).  Most integrations, I think, are conceptually self-contained; the entities they create all generally relate to the same type of physical device.  Template sensors are not; you can easily create dozens of them with no overarching idea connecting them.  I could have a few template sensors relating to lights, a few relating to cameras, a few relating to presence detection, etc.  These would have been separated into packages under the old format.  I'm not sure there's any way to do so with the modern format, and that seems like a huge obstacle to organization with even moderately complex installations.

**Comment by frenck** [comment]
You are mixing up base entities and platforms with integrations in your response above.

**Comment by usul0184** [comment]
Ah, apologies, not sure what's the difference--what base entities / platforms did I characterize as integrations?

In any case, I think the concern still stands; there is no way to split up template sensors into multiple files, and users are very likely to want to do so given their function.

**Comment by frenck** [comment]
> there is no way to split up template sensors into multiple files

There is, the package functionality applies as normal, within the same constraints as any other integration.

**Comment by usul0184** [comment]
But don't those constraints effectively make it impossible to do effectively?  If I want a trigger-based sensor and a state-based sensor in one file, and a different state-based sensor in another file, what is the syntax to include them?  Is the feature request misguided?

Sorry for all the questions, but I'd be elated if it turns out I'm wrong about this.

**Comment by frenck** [comment]
> If I want a trigger-based sensor and a state-based sensor in one file, and a different state-based sensor in another file, what is the syntax to include them?

You can't as that is not within the general scope of how packages work. As said, the same rules apply to all other integrations.

**Comment by usul0184** [comment]
Okay, so I think my concern still stands--this is a rather surprising outcome for users and should be documented even if it's within the general scope of how packages work.  This is because few integrations are used the way that template integrations are used, with the user defining possibility dozens of entities with no overarching theme but likely with logical groupings.  In other words, the template integration is intuitively more similar to switch, light, automation, and groups (not sure if these are integrations), and I think people expect template sensors to behave the same way for packages.

At least for myself, I'm really at a loss with how to organize my template sensors without reverting back to the old format or having an enormous configuration file.  Something needs to be said somewhere, if not to fix, at least to acknowledge this issue.

**Comment by frenck** [comment]
> this is a rather surprising outcome for users and should be documented even if it's within the general scope of how packages work

I do not agree, as we don't document it on the documentation of each of the other integrations either. The use of packages is considered an advanced use case, considering the above questionnaire we had, it seems that you are not aware of the difference in platforms and integration level configurations and how packages relate to configuration.yaml.

That is not a documentation issue of the template integration.

>  at least to acknowledge this issue.

It is not an issue.

**Comment by usul0184** [comment]
Hmm, okay.  It just feels like an important feature was taken away compared to the old style--the ability to organize template sensors into different files without constraint--and it's clear that multiple people feel the same way, hence the feature request and multiple issues being opened about this.  It is not a problem for other integrations because they are not used in a similar manner.

**Comment by frenck** [comment]
>  an important feature was taken away compared to the old style

There is no feature taken away? The package functionality has not been adjusted in any way.

> the ability to organize template sensors into different files without constraint

It is there. You have to use it to match the situation you are using it in.

> hence the feature request and multiple issues being opened about this.

Packages are a complex matter, it is unfortunately often used incorrectly.
The feature request will introduce workarounds that are not part of the general package or integration functionality. In general, those workarounds should be avoided.

> It is not a problem for other integrations because they are not used in a similar manner.

? I don't see this statement fitting in this context. Is KNX different for example? 🤷

**Comment by usul0184** [comment]
Thanks for walking me through this; I'll close it and leave it to more knowledgeable people to discuss.  I guess my last comments are: (1) you are probably correct that people are using packages incorrectly, but if so, I think it's helpful to query why they are doing so and whether clearer documentation might help, and (2) I'm not that familiar with KNX, but I see what you are saying.  Maybe the difference is simply popularity.  There are 43 times more installations using template compared to KNX.  I think it's pretty safe to say that almost everyone using packages is using a template sensor of some sort, and changing to the new style comes at a true organizational cost.  Template sensors are usually "help" some sort of broader concept, and people tend to organize concepts by package.  Perhaps they should not be, but the alternative is not obvious.

Anyway, appreciate all the work you are doing.

**Comment by farmio** [comment]
If I'm not mistaken the packages functionality relies on a platform config style
```yaml
sensor:
  - platform: ...
    ...
```
which is deprecated as of https://github.com/home-assistant/architecture/blob/master/adr/0007-integration-config-yaml-structure.md

So my question: shouldn't the 'package' function be marked deprecated as well - at least in documentation? 
Users trying to 'package' eg KNX entities will fail without any hint?!

**Comment by frenck** [comment]
> If I'm not mistaken the packages functionality relies on a platform config style

That is incorrect.

> shouldn't the 'package' function be marked deprecated as well

Packages are not limited or related to platform configuration? I'm not following.

**Comment by farmio** [comment]
Ok then I was informed wrong. 

I've seen some complaints from KNX users that packages wouldn't work anymore after moving away from `- platform: ` to new-style 
```yaml
knx:
  sensor:
    - ...
```
configuration. But I've never tried it.

**Comment by frenck** [comment]
These aren't platforms configurations but integrations.
