### ISSUE TITLE
Info to noobs about how to setup a secure home assistant 

### ISSUE THREAD

**Issue by kohekohebigsky** [home-assistant/home-assistant.github.io#18322]
### Feedback

improvement suggestion for the /SECURITY page.
Please add content to new users about how to set up secure connections between the various home automation parts.
eg: how to resolve the problem not just announce the problem.
ESP Home add integration: Limited functionality because you're not browsing the dashboard over a secure connection (HTTPS).
Step by step for adding secrets and https connections for addons.

Thanks.

### URL

https://www.home-assistant.io/security/

### Version

2021.6.6

**Comment by ludeeus** [comment]
That is not the purpose of that page.
Secrets are covered here <https://www.home-assistant.io/docs/configuration/secrets/>
Adding remote access over with SSL is covered here <https://www.home-assistant.io/docs/configuration/securing/>, and if that is too much <https://www.nabucasa.com/> offers an easy way to do it.

**Comment by frenck** [comment]
Yup, agree with the above response.

Setting up SSL can be done in like a thousand different ways, documenting a lot of them, doesn't help either. Many community provided guides can be found in the forums.
