### ISSUE TITLE
Can't find Purifier or Humidifier in Xiamo_miio

### ISSUE THREAD

**Issue by CharlyLara** [home-assistant/home-assistant.github.io#18330]
### Feedback

I'm trying to use the integration provide by Home Assistant but it doesn't work with my xiaomi device.

When I'm setting up the integration, neither of my devices is found automatically. 
"The device model is not known, not able to setup the device using config flow."

When I try to choose the device in the following step, neither of the devices appears listed... So I'm stuck.

Purifier Model: zhimi.airpurifier.mb3

Humidifier Model: deerma.humidifier.jsq

![image](https://user-images.githubusercontent.com/46820303/123615632-c6ff7a80-d805-11eb-8e2a-16aa03aff5a4.png)

![image](https://user-images.githubusercontent.com/46820303/123615773-e8f8fd00-d805-11eb-9a78-af7ee19df7aa.png)

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2021.6.6

**Comment by starkillerOG** [comment]
see: https://github.com/home-assistant/core/pull/47924#issuecomment-869523612

**Comment by frenck** [comment]
This feature is under development.

That said, you are trying to either report a bug, or do a feature request. However, you have submitted documentation feedback. There is no amount of documentation we can adjust to provide a solution to either of those. Therefore, I'm closing this feedback.

Thanks!

../Frenck
