### ISSUE TITLE
Array issue

### ISSUE THREAD

**Issue by tristanmunday** [home-assistant/home-assistant.github.io#18334]
### Feedback

I'm getting error on the sensor_id stating 'expecting array' when using the proper hex code for the sensor.

### URL

https://www.home-assistant.io/integrations/neurio_energy/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @tristanmunday 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please submit issues with Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
