### ISSUE TITLE
FinTS Integration - Deprecated

### ISSUE THREAD

**Issue by flirtysanchez** [home-assistant/home-assistant.github.io#18344]
### Feedback

Hi!

A few days ago I found the "FinTS" Integration for HA. I already had the suspicion before testing that this will no longer work like this. This has also been confirmed in the test!

I think this integration isn't working since ~14.09.2019. Since the introduction of the PSD2 guidelines, any software that wants to communicate with a bank via FinTS must be registered once by the "Deutschen Kreditwirtschaft".

Here are some informations (only german):
https://www.hbci-zka.de/register/register_faq.htm

If this is not done, then the software receives a rejection from the bank. This is also the case with HA:

`fints.dialog.FinTSDialogError: {'3079': 'Bitte wenden Sie sich an den Hersteller des Banking-Programms.', '9078': 'Dialog abgebrochen - **Banking-Programm ist nicht registriert.**', '9010': 'Initialisierung fehlgeschlagen, Auftrag nicht bearbeitet.', '9050': 'Die Nachricht enthält Fehler.', '9800': 'Dialog abgebrochen'}
`

I don't know if HA meets the requirements for registration, or if there are any requirements at all.
The registration itself would probably be free of charge.

Greetings

 

### URL

https://www.home-assistant.io/integrations/fints/

**Comment by Sennahoi** [comment]
Yes, there are also some information on the library's page:

> Note
> As of September 14th, 2019, all FinTS programs should be registered with the ZKA or banks will block access. You need  to fill out a PDF form and will be assigned a product ID that you can pass above.
> If you set the product_id to None, the library will fill in the default product ID for python-fints. This works fine for evaluation, but should never be used if you bundle python-fints within a larger project. This might also not be acceptable by some banks.

Source: https://python-fints.readthedocs.io/en/latest/quickstart.html

Because I'm also interested in this integration, I could check whether we can register Home Assistant to get a valid registration id which is needed to make API calls now.

But I can't just try a registration for project, can't I?

**Comment by flirtysanchez** [comment]
Thanks for the Feedback. I'm from Germany and I'm also working in a bank for electronic banking support.

Maybe I can help by the registration process and testing?!

**Comment by Sennahoi** [comment]
Since I don't know who to mention here, I'll bring this topic to the developer forum inside the HA community.

See https://community.home-assistant.io/t/fints-access-needs-product-id/322464

**Comment by Sennahoi** [comment]
So, no one seems to have an opinion on this. We should check whether we can register an open source project ourselves. @flirtysanchez Let's discuss this off this issue. Can you contact me at tonn [dot] johannes [at] the google mail?
