### ISSUE TITLE
The new integrations/braviatv can not turn on the TV

### ISSUE THREAD

**Issue by shawnzhou1120** [home-assistant/home-assistant.github.io#18342]
### Feedback

we used the yaml function to control MY braviatv in the older HA,it worked well.
but its can not work now when i update the HA to the new revision.
following the new instruction, i re-add my braviatv in the HA by the Integrations/braviatv  in the UI. 
The TV come back.
but i met a issue.that i can not turn on MY TV by the media_player.turn_on function. 
the turn off,select_source all are work well. turn on can not work only.
could u check it ?
MY TV is sony KDL-60W850B

### URL

https://www.home-assistant.io/integrations/braviatv/

### Version

2021.6.6

**Comment by bieniu** [comment]
You opened an issue in documentation repository.

Your issue is not related to the documentation or integration but to the backend library https://github.com/dcnielsen90/python-bravia-tv
