### ISSUE TITLE
No ability to change password after update

### ISSUE THREAD

**Issue by smck83** [home-assistant/home-assistant.github.io#18357]
### Feedback

Can you please assist with providing detail on where credentials are stored so they can be manually updated - if the password is changed.

There is no ability to change the credentials after connecting the integration.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.6.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use this GitHub tracker for collecting documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
