### ISSUE TITLE
String example.

### ISSUE THREAD

**Issue by mciaio** [home-assistant/home-assistant.github.io#18354]
### Feedback

A state string example would be helpful here.  I had to go to reddit and ask.  ie:  state: ["Cooling", "Heating"]

Thanks.

### URL

https://www.home-assistant.io/integrations/history_stats/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @mciaio 👋 

I'm not following your suggestion or question? Could you elaborate?

The type specified for the state is a string or a list.

![image](https://user-images.githubusercontent.com/195327/123993513-c5cc7a00-d9cc-11eb-8447-bbcea5542398.png)

The very first example shown on the linked page has a state as a string.

![image](https://user-images.githubusercontent.com/195327/123993601-dbda3a80-d9cc-11eb-8d6e-80d6183732f8.png)

So I guess I'm not understanding the feedback in that case?


../Frenck

**Comment by mciaio** [comment]
I guess I meant list, not string.  I had 2 states I wanted to track.
Heating and cooling.  I couldn't find the proper syntax and formatting to
add multiple states.

Someone on reddit suggested state: ["Cooling", "Heating"] which seems to
have worked.

**Comment by frenck** [comment]
I would not recommend that format.

```yaml
state:
  - "Cooling"
  - "Heating"
```

But your question/problem is not with this integration, but it is with YAML knowledge I guess.

Some basic YAML introduction can be found here:

<https://www.home-assistant.io/docs/configuration/yaml/>

If you like to many YAML examples and how you could style your configuration; You could check out our YAML Style Guide:

<https://developers.home-assistant.io/docs/documenting/yaml-style-guide>

../Frenck

**Comment by mciaio** [comment]
I appreciate your input.  I only suggest maybe adding an example at the
bottom with multiple states for new people like me.

**Comment by frenck** [comment]
Thanks for your suggestion, but I'm going to friendly decline it.

Mainly, because we have thousands of fields that can accept multiple items and even more fields that can accept multiple types. In the end, we cannot provide an example for every combination. That is not maintainable or even presentable in a respectable way.

Hoping the above links will at least help you 👍 

../Frenck
