### ISSUE TITLE
Possible typo in the MQTT beta release notes for 2021.7

### ISSUE THREAD

**Issue by ovitters** [home-assistant/home-assistant.github.io#18364]
### Feedback

This for the beta release notes of 2021.7 as per the rc website/blog.

For MQTT it mentions:

> It’s no longer possible to set attributes defined in the the base component via a configured json_attributes_topic.
> 
> For example a light no longer accepts brightness via the json_attribute_topic. This was unintended and undocumented functionality that lead to **_expected_** behavior.
> 
> This change applies to all supported MQTT platforms.

I think what is meant is it _could_ lead to _**un**expected_ behaviour, no?

### URL

https://rc.home-assistant.io/blog/2021/06/30/release-20217/#post-comments

### Version

2021.7

**Comment by frenck** [comment]
Thanks for that! Well spotted! 👀 

I have adjusted it locally, will push it with more correction later today (and close this issue when that has been done).

../Frenck

**Comment by frenck** [comment]
I've just pushed the update with the rest of the release blog progress.

Again, thanks for reporting! 👍 

../Frenck
