### ISSUE TITLE
Linux VM installation

### ISSUE THREAD

**Issue by louisdcoulombe** [home-assistant/home-assistant.github.io#18366]
### Feedback

Hi,
 Just wanted to add the precision to unzip the KVM image before creating the virtual machine.

The creation of the VM will work but won't boot if not done. I would add the precision to avoid loosing time.

### URL

https://www.home-assistant.io/installation/linux/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @louisdcoulombe 👋 

The KVM image is distributed in the xz format and can be directly used without unpacking. Hence, that detail isn't needed.

../Frenck
