### ISSUE TITLE
ring cameras stop working after a min or less. reload integration fixes for another min or so. started happening about 1 week ago(6-24-2021) or so.

### ISSUE THREAD

**Issue by randrcomputers** [home-assistant/home-assistant.github.io#18365]
### Feedback

Log is full of errors like i have attached here:
any ideas?

Error fetching Ring history data for device xxxxxxxxxxx: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error fetching Ring history data for device xxxxxxxxx: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error fetching Ring history data for device xxxxxxxxxxxx: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error fetching Ring history data for device xxxxxxxxxxx: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error fetching Ring history data for device xxxxxxxxxxx: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error fetching Ring active dings data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error fetching Ring device data: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error fetching Ring active dings data: 504 Server Error: Gateway Time-out for url: https://api.ring.com/clients_api/dings/active?api_version=9

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2021.6.6

**Comment by vMotionFailed** [comment]
I just set up HA for the first time and am seeing the same issues.  Reloading the integration fixes the issue temporarily, and I see the same log errors.  I'm also on version Home Assistant 2021.6.6

**Comment by craigmcewen** [comment]
I am so glad to see that I am not the only one with this issue! It was working fine up until about 4 days ago prior to that there was always an image displayed in the pic entity card and you could click to view the previous video capture, now no images and no vids.

**Comment by repier37** [comment]
I have the same issue
