### ISSUE TITLE
Speedtest - reload 

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#18368]
### Feedback

In my environment the speedtest integration rather often stops working and I have to reload it manually. 

Is there any service to reload this integration? I would like to use it in a script / lovelace dashboard.

Thanks for your answer.

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @hklages 👋 

Not really, to be honest, it sounds like you want to report an issue. However, you have provided documentation feedback instead.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

../Frenck

**Comment by hklages** [comment]
... thanks. Just did it.
