### ISSUE TITLE
Supported devices list

### ISSUE THREAD

**Issue by mediocaballero** [home-assistant/home-assistant.github.io#18372]
### Feedback

A list of supported devices for somfy integration would help, as in: Tahoma, Connexoon, etc...

I'm specially interested in knowing whether the new "Somfy Switch" would work as well...

### URL

https://www.home-assistant.io/integrations/somfy/

### Version

2021.6.6

**Comment by konstantinrudi** [comment]
Relevant still

**Comment by konstantinrudi** [comment]
I actually have the same question as I just got the new "switch" but sadly it does not seem to be added.

**Comment by tetienne** [comment]
Hi, I totally missed this issue 🙏 Sadly, I cannot give a list of working hub. Indeed, there is also a list of countries where the API is not available like Australia. 

But I highly suggest you to give a try to https://github.com/iMicknl/ha-tahoma I maintain with 2 other guys. This one is more stable, and returns more information which is not the case for the official AP. For sure, the switch hub works without countries restriction (from what we know). Just be sure to follow the [instructions](https://github.com/iMicknl/ha-tahoma#tahoma-switch).
