### ISSUE TITLE
Link to international AVM page

### ISSUE THREAD

**Issue by breti** [home-assistant/home-assistant.github.io#18377]
### Feedback

Perhaps it would be better to link to the international AVM homepage (https://en.avm.de/) instead of the german one.

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.7.0

**Comment by chemelli74** [comment]
Yes, I agree.
Please submit a PR for that change.

Thx,

Simone

**Comment by chemelli74** [comment]
Closed this via #18417
