### ISSUE TITLE
Synology Docker update documentation is out of date

### ISSUE THREAD

**Issue by pkininja** [home-assistant/home-assistant.github.io#18379]
### Feedback

Procedure for updating Home Assistant on Synology Docker has changed. Synology Docker 20.10.3-0554 (June 2021 update) changed the relevant Action menu item from "Clear" to "Reset". 

Old Documentation: 
Right-click on it and select “Action”->“Clear”
Proposed New Documentation: 
Right-click on it and select “Action”->“Reset”

### URL

https://www.home-assistant.io/installation/alternative/

### Version

2021.6.6

### Additional information

https://www.reddit.com/r/synology/comments/ocwj2e/docker_action_clear_now_action_reset/

**Comment by chemelli74** [comment]
Hi @pkininja , you can edit the doc yourself and submit a PR for the change to be accepted and merged.

Thx,

Simone

**Comment by chemelli74** [comment]
Documentation was updated.
