### ISSUE TITLE
Wet Bulb Globe Temperature?

### ISSUE THREAD

**Issue by ahgray** [home-assistant/home-assistant.github.io#18371]
### Feedback

The NWS appears to now be observing and forecasting the Wet Bulb Globe Temperature. Is it possible to have this as one of the sensor entities that are initially disabled.

https://digital.mdl.nws.noaa.gov/?zoom=4&lat=37&lon=-96.5&layers=F000BTTTFTT&region=0&element=8&mxmz=false&barbs=false&subl=TFFFFF&units=english&wunits=nautical&coords=latlon&tunits=localt

### URL

https://www.home-assistant.io/integrations/nws/

### Version

2021.6.6

**Comment by frenck** [comment]
Thank you for reaching out. It seems like you wanted to request a feature, however, you have submitted documentation feedback instead.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
