### ISSUE TITLE
Growatt Home Assistant

### ISSUE THREAD

**Issue by ciceroaferreira** [home-assistant/home-assistant.github.io#18375]
### Feedback

Hey, first of all thanks for share this add on.
Second, the HA website is very poor, i´m already set the integraton in HA but not able to get the monthly generation. Maybe would be nice some instructions or improvement how to get same data there is in Growatt Server website like data by time / day / month / year.

Thanks

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi @ciceroaferreira 👋 

Thank you for reaching out. Having additional data points is not about documentation or bugs. It is about having a feature request.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
