### ISSUE TITLE
TRÅDFRI integration - TRÅDFRI shortcut button limitations

### ISSUE THREAD

**Issue by breartoni** [home-assistant/home-assistant.github.io#18384]
### Feedback

Would be extremely helpful to mention in the IKEA TRÅDFRI integration documentation that TRÅDFRI Shortcut Buttons will only show up as a battery level sensor when using the IKEA TRÅDFRI Gateway with the associated IKEA TRÅDFRI integration.

![image](https://user-images.githubusercontent.com/565502/124367617-cf511e80-dc26-11eb-98be-dbec797e3381.png)

In addition to checking the entity list for the device, I listened to `state_changed` events and none occurred reliably when the shortcut button was pressed (occasionally the battery level reported would change and that would trigger a `state_changed` event).

At least at the present time, I would propose the documentation mention that users wishing to use Shortcut Buttons with HA should use an alternative Zigbee integration and compatible Zigbee gateway such as [deCONZ](https://www.home-assistant.io/integrations/deconz/) ([setup article](https://www.lucastechblog.com/home-automation/setup-ikea-tradfri-with-deconz-in-home-assistant/)) or [Zigbee Home Automation](https://www.home-assistant.io/integrations/zha/).

### URL

https://www.home-assistant.io/integrations/tradfri/

### Version

2021.6.6

**Comment by frenck** [comment]
I'm not sure what the feedback is?

Momentary buttons send events, at they do not retain a state. Although it sounds you expected an entity?

**Comment by breartoni** [comment]
I follow you about momentary buttons sending an event. To the best of my knowledge, the IKEA TRÅDFRI integration (which works with the IKEA TRÅDFRI Gateway) is not providing an event when a IKEA TRÅDFRI Shortcut Button is pressed.

If this is the case, the feedback would be to caution existing HA users looking to add the Shortcut Buttons to their home automation system to use a different Zigbee gateway when integrating with HA, since there is plenty of documentation on successful integration of the IKEA TRÅDFRI Shortcut Buttons when using alternative Zigbee gateways that do generate events on momentary button presses.
