### ISSUE TITLE
VPNs for Remote Access

### ISSUE THREAD

**Issue by Arrgg** [home-assistant/home-assistant.github.io#18386]
### Feedback

It is a shame that VPNs are not mentioned for remote access, especially Wireguard since there is an add-on available.

### URL

https://www.home-assistant.io/docs/configuration/remote/

### Version

2021.6.6

**Comment by frenck** [comment]
This is the Home Assistant documentation, not the VPN or system administration documentation.

We keep these subjects out of our documentation deliberately, as they are not in scope of the Home Assistant software itself.

Nevertheless, thanks for your feedback 👍 


../Frenck
