### ISSUE TITLE
Access generated credentials

### ISSUE THREAD

**Issue by philsson** [home-assistant/home-assistant.github.io#18382]
### Feedback

Love that this is now an official addon! Although after switching to using this component my ambilight does no longer work as the TV has generated new credentials. It would be awesome to get these somehow so I can continue using the custom integration for the ambilight.

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2021.6.6

**Comment by elupus** [comment]
Not really right place for this support. But you can find them in config/.storage/config_entries.json
