### ISSUE TITLE
Two way auth with IMAP

### ISSUE THREAD

**Issue by danlun** [home-assistant/home-assistant.github.io#18393]
### Feedback

Thanks for good info. Worked perfect when I, after been asking on FB groups, realised I need another password than my normal for this integration since I use two way auth. It would be great if this info also was available for us newbies on the this page. 

### URL

https://www.home-assistant.io/integrations/imap_email_content/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @danlun 👋 

I'm confused about your feedback, there is no two-factor authentication in the IMAP protocol, so are you confusing it with another integration?

**Comment by danlun** [comment]
Hi, no don’t think so. But who knows.

When using my normal password for my google mail it doesn’t work. When I
exchange the password to a new generated application password it does work.
I thought that had to do with 2 way authorizing?

//dan

mån 5 juli 2021 kl. 14:32 skrev Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
> When using my normal password for my google mail it doesn’t work. When I
exchange the password to a new generated application password it does work.
I thought that had to do with 2 way authorizing?

That is specific for the service you are using and is not related to this integration or the IMAP protocol.

**Comment by danlun** [comment]
I know, I was just hoping that by adding this as a general statement, other
people new on HA as I, don't get confused and quicker get things going. My
feeling is that this is part of the overall ambition of you all deeply
involved in the HA project. I think Im correct in that statement but you of
course better know when info gets too much on each page. For me it had
helped a lot. Of course you don't have to change it for one person,
specially not for one that now have learned by asking in FB groups, why it
didn't work.

On another note, info telling that the sensor will not be visibel in
Entities if the log in at the IMAP source is unsuccessful would also help I
think.

Thanks
Dan

Den mån 5 juli 2021 kl 15:22 skrev Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
> My feeling is that this is part of the overall ambition of you all deeply involved in the HA project.

This has nothing to do with the Home Assistant project. But is something your email provider does. There are millions of email providers in the world, it is not our responsibility to document how IMAP works for each of them.

> On another note, info telling that the sensor will not be visibel in
Entities if the log in at the IMAP source is unsuccessful would also help I
think.

This applies to all manual configured integrations. This is not unique for this integration, as this integration is not set up via the UI, it is not in the UI either.

**Comment by danlun** [comment]
Thanks Franck, sorry to be so bad in my English (Im from Sweden) so I was
misunderstood trying to imply you were to document all millions of e-mail
providers. That was absolutely not my thinking. Maybe more one sentence
mentioning it, as a general statement. Probably it also came to my mind
since the example used is Gmail.

I save your mail for future reference and please don't get angry with me if
I use the "Get documentation better" button wrong again. I'm as I say, new
at HA and of course still need to learn when its my mistake I don't
understand the info correctly. If I can manage this well, my input for
better documentation will be more precise in the future.

I just love HA and of course as you can understand use the different FB
supports groups a lot. Will continue to do so.

Have a great day and keep up the good work!!

Best regards

Dan

Den mån 5 juli 2021 kl 17:07 skrev Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
> Maybe more one sentence mentioning it, as a general statement.

I'm not sure what to mention? That is my problem. The integration needs an IMAP username & password... 🤷 


> I save your mail for future reference and please don't get angry with me i

I'm not angry? 🤷

**Comment by danlun** [comment]
Franck, this is funny now :-) I didn't say you are angry did I? You can't
just take half of a sentence. In the full sentence I said I hope you will
not get angry *next time* I use the "suggest better documentation" button
in a similar situation.

Again, keep up the good work, love HA!!!!

Best Regards

Dan

Den mån 5 juli 2021 kl 17:33 skrev Franck Nijhof ***@***.***>:
