### ISSUE TITLE
Homeconnect login issue

### ISSUE THREAD

**Issue by yunjies** [home-assistant/home-assistant.github.io#18402]
### Feedback

Hi there,

Trying to connect my homeconnect app(Chinese version) to home assistant. However, it seems Chinese version of homeconnect is not allow to login via email (I tried and said wrong password and my email cannot receive the reset password email from homeconnect). I tried to connect homeconnect chinese representatives but haven't heard from them yet.

So, is there a way that the link poped when installing the HomeConnect integration could allow me to login via phone number? Because that's the primary method I use when I login to my HomeConnect app.

Thanks.

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2021.6.6

**Comment by frenck** [comment]
Hi there @yunjies 👋 

I'm not sure if you are trying to report a bug or are looking for support. Either way, you have submitted documentation feedback, which will not help you with either case.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

If you want to report a bug, please use our issue tracker here:

<https://github.com/home-assistant/core/issues>

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
