### ISSUE TITLE
Introduction INTERVAL parameter

### ISSUE THREAD

**Issue by gerardsamara** [home-assistant/home-assistant.github.io#18413]
### Feedback

The IMAP integration cannot be setup to interrogated the IMAP server   with a frequency depending of the user need , for example each hour , each day.

Is it possible to add this parameter ?
Thank you 

### URL

https://www.home-assistant.io/integrations/imap/

### Version

2021.6.6

**Comment by ludeeus** [comment]
Set the desired `scan_interval`  for that platform <https://www.home-assistant.io/docs/configuration/platform_options#scan-interval>
