### ISSUE TITLE
Debugging instructions incompatible with HASS OS, no disclaimer provided.

### ISSUE THREAD

**Issue by amaisano** [home-assistant/home-assistant.github.io#18410]
### Feedback

https://www.home-assistant.io/docs/configuration/splitting_configuration/#debugging-multiple-configuration-files

These debug commands do not work with HASS OS. A disclaimer or alternate method should be provided for HASS OS.

### URL

https://www.home-assistant.io/docs/configuration/splitting_configuration/

### Version

2021.6.6

### Additional information

Hass OS install method doesn't provide access to the `hass` command. While `ha core check` is available, it doesn't allow for the debugging options listed in this section via CLI.

**Comment by frenck** [comment]
Agreed, the right documentation is here: <https://www.home-assistant.io/docs/configuration/troubleshooting/#problems-with-the-configuration>

We should indeed adjust this part (maybe just link it even)
