### ISSUE TITLE
Devices are becoming unavailable every 2-3 minutes

### ISSUE THREAD

**Issue by amaisano** [home-assistant/home-assistant.github.io#18421]
### Feedback

After upgrading to core-2021.7.0 today, all of my climate devices become 'Unavailable' every 1-3 minutes, and then return to working order again. This process has been repeating constantly since the core update.

The devices are using Homebridge and the [Frigidaire plugin](https://github.com/karlg100/homebridge-frigidaire) in a local docker container. I have 2 other similar Homebridge containers but those devices (Harmony plugin and Cmd4 plugin) are not experiencing these issues in HA.

These climate devices were working fine prior to today's HA Core update. I have already rebooted the host and restarted HA multiple times.

### URL

https://www.home-assistant.io/integrations/homekit_controller/

### Version

2021.7.0

**Comment by Jc2k** [comment]
Hi - this is the wrong place for reporting bugs. This is where we track documentation issues. Can you file an issue here? https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml

**Comment by Jc2k** [comment]
Also can you include some debug logs. They will help us figure out whether homebridge is returning data we can't parse or whether there is something strange happening in the network stack. We tend to suggest putting this in your config:

```
logger:
  logs:
    aiohomekit: debug
    homeassistant.components.homekit_controller: debug
```

Thanks!

**Comment by amaisano** [comment]
My bad @Jc2k! Will move over there and update once I see some of those debug logs.

**Comment by Jc2k** [comment]
No worries! Will keep an eye out for your ticket, though it's getting late here so if I don't reply it might be in the morning.
