### ISSUE TITLE
Retrying setup: Error occurred while communicating with Forecast.Solar API

### ISSUE THREAD

**Issue by fhopley** [home-assistant/home-assistant.github.io#18422]
### Feedback

After adding the forecast.solar integration (with all required fields populated - no API key or damping set). I get the following error message:

Retrying setup: Error occurred while communicating with Forecast.Solar API

I'm super keen to use this functionality - please let me know what if any troubleshooting steps are worth taking.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.7.0

**Comment by exup** [comment]
Hi same here, I even registered for an account and put the API key in but same message. 

"Retrying setup: Error occurred while communicating with Forecast.Solar API"

Core Version core-2021.7.0  and supervisor-2021.06.8
Error log also shows
Logger: homeassistant.config_entries
Source: config_entries.py:324
First occurred: 5:30:18 PM (1 occurrences)
Last logged: 5:30:18 PM

Config entry 'city and name' for forecast_solar integration not ready yet: 'list' object has no attribute 'items'; Retrying in background

**Comment by klaasnicolaas** [comment]
I see more people getting the same error. Could you give me all your entered data from the config flow, then I'll see if I can reproduce the problem in my dev environment.

Ps. @frenck can you transfer this issue to core? 😄

**Comment by exup** [comment]
Hi, not sure what you mean. Are you suggesting the values I put into the configuration like Azimuth inclination etc, only I would not like to post that publicly. I can PM you via email if that helps.

**Comment by frenck** [comment]
Hi there @fhopley 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix a bug in the code.

Please raise an issue in the Home Assistant core issue tracker instead:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
