### ISSUE TITLE
PV Inverter Size

### ISSUE THREAD

**Issue by philkirby** [home-assistant/home-assistant.github.io#18427]
### Feedback

Given the relative costs of solar panels many people install more panel wattage than what there inverter is capable. Therefore their PV output in the middle of the day will be limited to the inverter rating. For example the typical system in Australia has 6.6kW of panels coupled to a 5kW inverter.

Please add an inverter size rating/limit.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.7.0

**Comment by frenck** [comment]
Hi there @philkirby 👋 

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
