### ISSUE TITLE
Utility meter doesn't work correctly after update to 2021.7.0

### ISSUE THREAD

**Issue by jonisnet** [home-assistant/home-assistant.github.io#18432]
### Feedback

Since the new Version (2021.7.0) of the core the method for DSMR doesn't work any more.
the result will be the total sum of the template and will not show the current day or month only.

![prtscr development tools](https://user-images.githubusercontent.com/82890949/124928128-a3a3af00-dfff-11eb-91fc-e681aa115759.png)
![prtscr utility meter yaml files](https://user-images.githubusercontent.com/82890949/124928130-a43c4580-dfff-11eb-8daa-f71bc39182a9.png)
 
I will keep trying but cannot find a simple solution at this moment.

Kees de Bruin

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.7.0

**Comment by jonisnet** [comment]
After watching the lovelace a short while i think the problem is that the kWh value showed on daily and monthly is total meters minus today instead of today only. 
Hoop this helps.

Greetz Kees

**Comment by dgomes** [comment]
CC @emontnemery

**Comment by frenck** [comment]
Hi there @jonisnet 👋 

It seems like you want to report an issue with a Home Assistant integration, however, you have submitted documentation feedback instead.

If you want to submit an issue for an integration, please use the issue tracker here:

<https://github.com/home-assistant/core/issues>


Thanks! 👍 

../Frenck
