### ISSUE TITLE
recuperator bypass-flap

### ISSUE THREAD

**Issue by pkuiBUKVgbvku** [home-assistant/home-assistant.github.io#18437]
### Feedback

How can I read and set the state of the bypass-flap of the recuperator?

### URL

https://www.home-assistant.io/integrations/vallox/

### Version

2021.7.1

### Additional information

At least reading is already working in OpenHAB. 

Several other read/write options are sadly only available in OpenHAB and not in HomeAssistant yet (Channel-List).
 

https://www.openhab.org/addons/bindings/valloxmv/

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation suggestions, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
