### ISSUE TITLE
Maybe no longer working

### ISSUE THREAD

**Issue by msmith9xr4** [home-assistant/home-assistant.github.io#18440]
### Feedback

Error: 500 Server Error: Internal Server Error for url: https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=mycorrectserial%0A2&faucet_serial=mycorrectvalce%0A2
You will need to restart hass after fixing.

the URL is broken by browser but not sure if that's important. 

I can login fine from web and raincloud app. for sure it was working last year in HA. I'm 100% up to date hypervisor/homassistant on a rpi4.

### URL

https://www.home-assistant.io/integrations/raincloud/

### Version

2021.7.1

**Comment by frenck** [comment]
Hi there @msmith9xr4 👋 

It seems like you want to report an issue with an Home Assistant integration, however, instead, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix issues.

Please report issues with an Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
