### ISSUE TITLE
Update Wiki to make it clear it does not work in ASIA PAC

### ISSUE THREAD

**Issue by exup** [home-assistant/home-assistant.github.io#18443]
### Feedback

Suggest to put a comment to say click here to see if your area is supported.
https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html

So AU NZ CHINA JP KR etc it wont work.

As per feeback in this git hub message. https://github.com/home-assistant/core/issues/52691#issuecomment-876303982
I re read the wiki and found no mention of this fact.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.7.1

**Comment by ludeeus** [comment]
Added in #18801
