### ISSUE TITLE
Mention firmware that doesn’t work 

### ISSUE THREAD

**Issue by mikeykau** [home-assistant/home-assistant.github.io#18448]
### Feedback

Should mentioned that it doesn’t support Envoy firmware D7.0.43

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2021.7.1

**Comment by frenck** [comment]
Is that a bug? or designed as such?

**Comment by mikeykau** [comment]
I think its a bug, I have logged a bug but no one seems interested to investigate it, so in the mean time I think the documentation needs updating so no one tears their hair out trying to get something to work that wont.

**Comment by frenck** [comment]
In general, we don't document bugs 🤷

**Comment by ludeeus** [comment]
We should not document bugs.
If needed it can be added to <https://alerts.home-assistant.io/>

**Comment by Erica0011** [comment]
It's not a bug.  Enphase changed the API.  Starting in 7.0xxx They are forcing equipment owners to a cloud-based API.  There are rumors that there may be a local API again in a future release, but it will require a cloud token.  The most egregious part is that they did it as an automatic update without warning equipment owners.

Some Envoy owners, like myself, managed to firewall off our gear before the force "upgrade" so we are still using this integration.  A few folks say they got Enphase to roll them back to a 5.XXXX  firmware that still works.

Sorry for commenting on a closed issue, but I thought the info might be useful.  Some of us are taking about it on the Enphase forum.  https://support.enphase.com/s/question/0D53m00006ySLuRCAW/unimpressed-with-loss-of-local-api-connectivity-to-envoys
