### ISSUE TITLE
processor_use inconsistency

### ISSUE THREAD

**Issue by aschor** [home-assistant/home-assistant.github.io#18453]
### Feedback

ressource is named "processor_use", but the sensor created is named "processor_use_percent" .... shouldn't both be identical ? 

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2021.7.1

**Comment by klaasnicolaas** [comment]
If I look at the other options, this change would be more in line, but this has to be adjusted in core and then in the documentation.
