### ISSUE TITLE
Documentation about updating is confusing

### ISSUE THREAD

**Issue by tuxick** [home-assistant/home-assistant.github.io#18457]
### Feedback

In  section "Best practice for updating a Home Assistant installation" (which is confusing already)
the section about updating Home Assistant Operating System  says
"To update Home Assistant Core when you run Home Assistant Operating System you have 2 options:"
But isn't Home Assistant Core a different beast? Maybe the "Core" bit should be left out/replaced?

### URL

https://www.home-assistant.io/common-tasks/os/

### Version

2021.7.1

**Comment by frenck** [comment]
Nope, the wording is correct.
All installation methods run the Core.
