### ISSUE TITLE
East-West roof configuration

### ISSUE THREAD

**Issue by landandseatechnology** [home-assistant/home-assistant.github.io#18460]
### Feedback

Good Day,
I like the first implementation of the Forecast.Solar in Home Assistant, and do see a great benefit from it, to automate and plan consumer in the house.
A lot of houses in Europe do have the sloping roof facing east and west, hence one part of the solar panels are installed facing east and the other part of the solar panels are facing west.

It would be great if a multiple direction of solar panel installation could get implemented, that better reflects a more accurate energy production. For example under integration, configuration options, it should be possible to just to add + a second or third roof, with declination, azimuth and peak power.

Kind Regards
Oliver

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.7.1

**Comment by klaasnicolaas** [comment]
Hi there @landandseatechnology  👋

It seems like you want to report an feature request for an Home Assistant integration, however, you have submitted documentation feedback instead. You can raise suggestions for an integration on our [community forum](https://community.home-assistant.io/c/feature-requests/13).

Ps. You can add the integration multiple times for each side and combine the values with template sensors 😉 

Thanks! 👍

Klaas
