### ISSUE TITLE
Floodlight switch not showing up

### ISSUE THREAD

**Issue by appezatto** [home-assistant/home-assistant.github.io#18464]
### Feedback

Ring integration page says:

"Once you have enabled the Ring integration, you can start using the light platform. This will add a light for every camera that supports a light (such as a floodlight)."

Not being able to find the light entity on Ring Integration for my recently added/configured Ring Floodlight Wired Plus.

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2021.7.1

**Comment by frenck** [comment]
Hi there @appezatto 👋 

It seems like you want to report an issue with an Home Assistant integration, however, instead, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix an integration issue.

Could you please raise issues with integration in the issue tracker?

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by appezatto** [comment]
Well. I can certainly do that, however, either the documentation is incorrect or the integration is not working as expected. Either way, you as the documentation owner should be concerned and also interested in getting either fixed. Will submit the issue.
