### ISSUE TITLE
Severity ascending or descending color

### ISSUE THREAD

**Issue by Aviatorpaal** [home-assistant/home-assistant.github.io#18463]
### Feedback

I would like a button or command to describe if the gauge should be increasing or decreasing in color as the thresholds are reached

### URL

https://www.home-assistant.io/lovelace/gauge/

### Version

2021.7.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
