### ISSUE TITLE
api secret

### ISSUE THREAD

**Issue by stefanuytterhoeven** [home-assistant/home-assistant.github.io#18470]
### Feedback

api secret only available for coinbase Pro? 
it's not available in coinbase (non pro)....

### URL

https://www.home-assistant.io/integrations/coinbase/

### Version

2021.7.1

**Comment by ludeeus** [comment]
You have this for non-pro as well, but it's only shown when creating the API key, not later when you hit "Show" in their UI

**Comment by TomBrien** [comment]
Yep the secret is only ever shown one time in the pop up after creating the API key. You can create the a new key and delete the old one
![image](https://user-images.githubusercontent.com/12411302/125250435-28d3e000-e2ee-11eb-90e8-e37b587b4c21.png)

**Comment by stefanuytterhoeven** [comment]
apparently it's only for coinbase pro?

**Comment by ludeeus** [comment]
I do not have pro, and got the same screen as @TomBrien shared when testing

**Comment by stefanuytterhoeven** [comment]
Thx. Need to try it again then...

Op ma 12 jul. 2021 08:12 schreef Joakim Sørensen ***@***.***>:
