### ISSUE TITLE
Remote documentation is outdated

### ISSUE THREAD

**Issue by emontnemery** [home-assistant/home-assistant.github.io#18473]
### Feedback

Documentation for the remote entity is outdated with no documentation for `remote.learn_command`, `remote.send_command`, `remote.delete_command`

### URL

https://www.home-assistant.io/integrations/remote

**Comment by emontnemery** [comment]
@felipediel `delete_command` was added in https://github.com/home-assistant/core/pull/40605, could you take a stab at user-facing documentation for it?

**Comment by felipediel** [comment]
Hi @emontnemery. 

These services are relatively new. Not all integrations have implemented them yet, so the documentation may vary.

I created them when I was implementing new features in the Broadlink integration, so it has all the services and the [docs](https://www.home-assistant.io/integrations/broadlink) are up to date, we can basically copy and paste from there, but as I said, they are not 100% compatible with all the integrations. We could also use [this](https://github.com/home-assistant/core/blob/dev/homeassistant/components/remote/services.yaml).

Tell me what you think and I can help to organize the information.
