### ISSUE TITLE
Include a list of available regions

### ISSUE THREAD

**Issue by mshuflin** [home-assistant/home-assistant.github.io#18481]
### Feedback

Ambee seems to support some areas (e.g. United States) but not others (e.g. Malaysia) when configuring, there is no error feedback suggesting that the problem is the coordinates. A list of locations that will work would be helpful for the documentation. 

### URL

https://www.home-assistant.io/integrations/ambee/

### Version

2021.7.1

**Comment by frenck** [comment]
They don't provide such a list.

**Comment by mshuflin** [comment]
> They don't provide such a list.

Then maybe something like this, "Ambee is not available in all regions. The error, 'failed to connect' during configuration could mean Ambee is not available for your coordinates"

**Comment by frenck** [comment]
There is an issue open for that, as that is not handled correctly. Documentation based on an issue sounds a bit backward.
