### ISSUE TITLE
SMA sensor tables not rendered correctly

### ISSUE THREAD

**Issue by cgarwood** [home-assistant/home-assistant.github.io#18498]
### Feedback

The tables listing the different sensors are not correctly rendered:
![image](https://user-images.githubusercontent.com/7545841/125499334-fcbf41af-e5ed-47b0-9be5-3cab0df700f5.png)

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2021.7.2

**Comment by frenck** [comment]
@cgarwood PR in #18499
