### ISSUE TITLE
Unifi Integration Options (Uptime/Rx/Tx) can cause large DB increases

### ISSUE THREAD

**Issue by ryphez** [home-assistant/home-assistant.github.io#18501]
### Feedback

I'd suggest adding a warning to the integration for Unifi as the entities that get created have an extremely high write frequency which added 10s of GBs in a short time to my logs. There is a similar post existing in the community warning about this https://community.home-assistant.io/t/be-very-careful-with-the-unifi-integration-and-im-sure-others-as-well/322073 

A suggestion to use Recoder's filters would be beneficial to include including adding this to the user's config yaml

`recorder:
  exclude:
    entity_globs:
      - sensor.*_uptime
      - sensor.*_tx
      - sensor.*_rx`

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2021.7.2

**Comment by frenck** [comment]
I get that this integration might drive it a little harder, so it might be useful to add a note to the integration page somewhere.

That said, this of course applies to every single entity that has frequent updates.

**Comment by ryphez** [comment]
I cleaned up my DB yesterday and I went from 22GB to 9GB with 51 entities on Unifi. Sharing the recording frequency I think would be the most beneficial as uptime is recorded every 1 second with default Recorder settings

**Comment by frenck** [comment]
> Sharing the recording frequency I think would be the most beneficial as uptime is recorded every 1 second with default Recorder settings

That sounds like an integration bug, as uptime sensors should only update once every time they come online.

**Comment by Kane610** [comment]
> > Sharing the recording frequency I think would be the most beneficial as uptime is recorded every 1 second with default Recorder settings
> 
> That sounds like an integration bug, as uptime sensors should only update once every time they come online.

Yes I've started to look how to minimize the rounding errors of the uptime sensor

**Comment by ryphez** [comment]
Did this change address this problem? https://github.com/home-assistant/core/pull/53111
