### ISSUE TITLE
Integration will no longer work with American Standard 

### ISSUE THREAD

**Issue by gator73** [home-assistant/home-assistant.github.io#18502]
### Feedback

American Standard recently released their own app. It no longer uses mynexia.com for login. The new AS login site is  https://asairhome.com/  As a result, this integration no longer works with American Standard tstats. 

### URL

https://www.home-assistant.io/integrations/nexia/

### Version

2021.7.2

**Comment by frenck** [comment]
Hi there @gator73 👋 

It seems like you want to report an issue for this integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix this issue.

Please report issues with Home Assistant integration in the Core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by gator73** [comment]
Sorry for the incorrect post, new to this format. 

Thanks for the redirect.

⁣Get BlueMail for Android ​
