### ISSUE TITLE
Apple TV integration compatibility issues with tvOS 15 beta

### ISSUE THREAD

**Issue by jluo98** [home-assistant/home-assistant.github.io#18507]
### Feedback

The Apple TV integration is not working with the tvOS 15 beta. HA returns an error `A problem occurred while pairing protocol MRP. It will be ignored.` on the first stage. 

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2021.7.2

**Comment by frenck** [comment]
Hi there @Steve-luo 👋 

It seems like you want to report an issue with an Home Assistant integration, however, instead, you have submitted documentation feedback. There is no amount of documentation I can adjust to fix an issue in the integration itself.

Please report issues with Home Assistant integrations in the Core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
