### ISSUE TITLE
Enable i2c for argon40

### ISSUE THREAD

**Issue by sekt1953** [home-assistant/home-assistant.github.io#18510]
### Feedback

I have to enable i2c on home assistant os befor start of installation
I follow this link https://www.home-assistant.io/common-tasks/os#enable-i2c-via-home-assistant-operating-system-terminal

but it du not work all the way, so from console I did this

mkdir /tmp/mnt
mount /dev/sda1 /tmp/mnt
cd /tmp/mnt
vi config.txt

found the chapter:
#Uncomment some or all of thise to enable the optinal hardware interface
#dtparm=i2c_arm=no

and change it to

#Uncomment some or all of thise to enable the optinal hardware interface
dtparm=i2c_arm=no

and the I rebooted and make the installation og Argon40

### URL

https://www.home-assistant.io/common-tasks/os#enable-i2c-via-home-assistant-operating-system-terminal

### Version

2021.7.2

**Comment by frenck** [comment]
That is what is written in the docs? You describe a slightly different method, but the result it the same.

**Comment by sekt1953** [comment]
hej

if i follow thise step it do not work
echo dtparam=i2c_vc=on >> /tmp/mnt/CONFIG/config.txt echo dtparam=i2c_arm=on
>> /tmp/mnt/CONFIG/config.txt sync
if I edit config.txt direct
/tmp/mnt/config.txt
it works

that is the thing

Svenn-Erik

Den ons. 14. jul. 2021 kl. 19.50 skrev Franck Nijhof <
***@***.***>:

**Comment by frenck** [comment]
> if i follow thise step it do not work
> echo dtparam=i2c_vc=on >> /tmp/mnt/CONFIG/config.txt echo dtparam=i2c_arm=on

That is expected, as that is not was it written in the manual. you are missing a new line there, those are separate commands.

Nevertheless, glad you have figured out a method that works for you 👍 
At this point, the documentation is correct though, therefore closing the issue on this end.

**Comment by sekt1953** [comment]
sorry Franck
I did this, and it did not work:
if i follow thise step it do not work
echo dtparam=i2c_vc=on >> /tmp/mnt/CONFIG/config.txt
echo dtparam=i2c_arm=on >> /tmp/mnt/CONFIG/config.txt

if I do this:
echo dtparam=i2c_vc=on >> /tmp/mnt/config.txt
echo dtparam=i2c_arm=on >> /tmp/mnt/CONFIG/config.txt
it do not work, the dtparm wil bee added to the [All] section of the
config.txt file, so I had to edit direct in the config.txt file,
I yust what to tell that guid on this link
https://www.home-assistant.io/common-tasks/os#enable-i2c-via-home-assistant-operating-system-terminal
has a error, and my way around it, I hope you can see what the error is.

Svenn-Erik


Den ons. 14. jul. 2021 kl. 23.36 skrev Franck Nijhof <
***@***.***>:
