### ISSUE TITLE
How to set iframe size?

### ISSUE THREAD

**Issue by andrey170183** [home-assistant/home-assistant.github.io#18516]
### Feedback

It would be nice to set the dimensions of the iframe

### URL

https://www.home-assistant.io/lovelace/iframe/

### Version

2021.7.2

**Comment by frenck** [comment]
Hi there @andrey170183 👋 

Thank you for reaching out. It seems like you want to submit a feature request, however, you have provided documentation feedback instead.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
