### ISSUE TITLE
"code expired"

### ISSUE THREAD

**Issue by egesanli619** [home-assistant/home-assistant.github.io#18513]
### Feedback

I'm trying to setup google calendar integration. I need to click on a link on a home assistant notification, then write a code on the same notification. The problem is, this notification only shows for a moment. than it says "Authentication code expired, please restart Home-Assistant and try again". I'm restarting but nothing changes.

### URL

https://www.home-assistant.io/integrations/calendar.google/

### Version

2021.7.2

**Comment by frenck** [comment]
Hi there @egesanli619 👋 

I'm not sure if you want to report a bug or are seeking for support... In either case, you have submitted documentation feedback, which is not going to provide either.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

If you want to report a bug with an Home Assistant integration, please submit an issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
