### ISSUE TITLE
Update Installation Python Module

### ISSUE THREAD

**Issue by NotSoScientific** [home-assistant/home-assistant.github.io#18511]
### Feedback

Please consider updating the installation guide for the Home Assistant Core. The guide reads under the CREATE THE VIRTUAL ENVIRONMENT section:

```
sudo -u homeassistant -H -s 
cd /srv/homeassistant 
python3.8 -m venv . 
source bin/activate
```

This should be updated to `python3.9` as follows:

```
sudo -u homeassistant -H -s
cd /srv/homeassistant
python3.9 -m venv .
source bin/activate
```

The installation process halts when using `python3.8` since this is an older version which has been updated to `python3.9`. 

### URL

https://www.home-assistant.io/installation/linux#create-the-virtual-environment

### Version

2021.7.2

**Comment by frenck** [comment]
That depends on the environment you have set up. Python 3.8 is the current minimum version we support.
This is an advanced installation method, for which we expect our users to be able to adapt to their situation. If one isn't able to do that, we don't recommend using this installation method.

**Comment by NotSoScientific** [comment]
Fair enough, thanks for the feedback!
