### ISSUE TITLE
Some sensors have no unique id

### ISSUE THREAD

**Issue by RuntimeError123** [home-assistant/home-assistant.github.io#18526]
### Feedback

Sensors 
- sensor.envoy_current_energy_consumption, 
- sensor.envoy_current_energy_production, 
- sensor.envoy_last_seven_days_energy_consumption, 
- sensor.envoy_last_seven_days_energy_production, 
- sensor.envoy_lifetime_energy_consumption, 
- sensor.envoy_lifetime_energy_production, 
- sensor.envoy_today_s_energy_consumption and 
- sensor.envoy_today_s_energy_production 

Have no unique id and can therefore not be renamed or customized.

![image](https://user-images.githubusercontent.com/36066761/125849634-dd38bab7-9b72-4a1c-989c-a7daa6670a36.png)

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2021.7.2

**Comment by frenck** [comment]
See: <https://www.home-assistant.io/faq/unique_id/>

![image](https://user-images.githubusercontent.com/195327/125907237-baea168b-14bd-4169-89bb-d0e718bb63d7.png)

**Comment by RuntimeError123** [comment]
@frenck I think it would be a great addition if unique ID's could be included to these entities as I prefer to have the entity ID follow a naming scheme and as these entities don't have a unique ID, the entity ID cannot be renamed. Also I believe that many people like to disable the entities they do not actively use. That is also not possible for these entites.
