### ISSUE TITLE
REST API Turn the light on example not working

### ISSUE THREAD

**Issue by baracoder** [home-assistant/home-assistant.github.io#18522]
### Feedback

The example on https://developers.home-assistant.io/docs/api/rest
In `/api/services/<domain>/<service>`  "Turn the light on"
does not work with Home Assistant 2021.7.1
```
curl -X POST -H "Authorization: Bearer ABCDEFGH" \
  -H "Content-Type: application/json" \
  -d '{"entity_id": "switch.christmas_lights"}' \
  http://localhost:8123/api/services/switch/turn_on
```

I tried to adapt the example to my local instance. It only works if i replace `switch` with `light`

Does not work:
```
bara@hal ~> curl -X POST -H "Authorization: Bearer xxx" \
                  -H "Content-Type: application/json" \
                  -d '{"entity_id": "light.office_light"}' \
                  -i http://homeassistant:8123/api/services/switch/turn_on
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 2
Date: Thu, 15 Jul 2021 12:10:35 GMT
Server: Python/3.9 aiohttp/3.7.4.post0
```

Works:
```
bara@hal ~> curl -X POST -H "Authorization: Bearer xxx" \
                  -H "Content-Type: application/json" \
                  -d '{"entity_id": "light.office_light"}' \
                  -i http://homeassistant:8123/api/services/light/turn_on
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 2
Date: Thu, 15 Jul 2021 12:10:40 GMT
Server: Python/3.9 aiohttp/3.7.4.post0
```

### URL

https://developers.home-assistant.io/docs/api/rest

### Version

Last updated on 3/11/2021

**Comment by frenck** [comment]
The example given is correct:

![image](https://user-images.githubusercontent.com/195327/125789194-f89edbfc-8afe-4176-951e-fa78e47aa944.png)

It uses the switch service to turn on a switch entity. If you need to turn on light entities, sure you need to adopt it to your use case (same for things like fans, vacuum cleaners).

It works exactly as within Home Assistant itself, were you cannot use the `switch.turn_on` service for a light either.

Closing this issue, as the developer documentation is correct.

**Comment by baracoder** [comment]
Oh, I see now. I was confused by the wording "Turn the light on"
