### ISSUE TITLE
Code example of template binary_sensor is incorrect (doesn't pass config validation)

### ISSUE THREAD

**Issue by shlomki** [home-assistant/home-assistant.github.io#18536]
### Feedback

The following two pieces of code do not pass configuration validation.
The error is:

> Component template cannot be merged. Expected a dict.

The reason for this is because binary_sensor doesn't need a minus (-) before it.
When I removed the minus, the config passes validation.
Perhaps this is something that needs to be fixed in and of itself in HA, but for now, the documentation is wrong.

![image](https://user-images.githubusercontent.com/34508546/126044857-81df68a9-c3db-4927-a682-5d92de467b28.png)

### URL

https://www.home-assistant.io/integrations/template/#configuration-variables

### Version

2021.7.3

**Comment by TheFes** [comment]
I noticed this template as well today, the template should evaluate to True or False for a binary sensor.
I guess this would work: 
`"{{ states | selectattr('state', 'in', ['unavailalbe', 'unknown', 'none']) | list | count > 0 }}"`
