### ISSUE TITLE
Manually change IP Address

### ISSUE THREAD

**Issue by ryangottlieb** [home-assistant/home-assistant.github.io#18531]
### Feedback

It would be nice to be able to manually adjust the ip address.  (Was setup when PW was on wifi, and just switched to ethernet)  

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2021.7.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
