### ISSUE TITLE
Optimization in enroll & delete

### ISSUE THREAD

**Issue by raoulteeuwen** [home-assistant/home-assistant.github.io#18535]
### Feedback

Thanks for that integration to anyone that contributed.

My HA reported i had a new integration > i looked > Spotify. So, naive me, i click configure, enter my Spotify credentials and ... nothing. Tried a couple of times. Gave up. Now i see 3 rows on config/integrations in the Spotify integration, all with red exclamation marks. Whatever i tried, they won't disappear. Studying the doc, i see i should have 1st (?) set up a Spotify app.

Would be nice if, while enrolling initially in an integration that advertises itself so enthusiastically, the user would be more informed about the order of things? (if i missed any hints while setting up the integration: excuses me than)

After i have now set up a Spotify app, i was able to remove the 'stale' entities, and succeeded to 'enroll'. What i was wondering: the documentation mentions a callback URL, which should include a port. For people less familiar, could there be a hint in the doc about what to fill out there? I left that part out of the URL, and without having tested controlling Spotify, i did not notice any errors for now.

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2021.7.3

**Comment by frenck** [comment]
This change has been slowly rolling out, I have a task to update the documentation today.
