### ISSUE TITLE
More commands

### ISSUE THREAD

**Issue by dbarlocker** [home-assistant/home-assistant.github.io#18547]
### Feedback

It would be nice there were more commands for this integrations. Could you add the 2 menu buttons, the triggers and the bumpers.

### URL

https://www.home-assistant.io/integrations/xbox/

### Version

2021.7.3

**Comment by hunterjm** [comment]
GitHub issues are for problems with the integration, not feature requests. The community forum has a feature request section. That being said, Xbox does not expose input for the bumper buttons in their API.
