### ISSUE TITLE
Repo for Homematic IP communication not supported anymore

### ISSUE THREAD

**Issue by LucTs** [home-assistant/home-assistant.github.io#18545]
### Feedback

Hi,

the owner of the repo which is used to communicate with HM IP Servers is not supporting/continouing the work anymore.

https://github.com/coreGreenberet/homematicip-rest-api/issues/383

Maybe you can update that on the integration description and also support to find a successor.

### URL

https://www.home-assistant.io/integrations/homematicip_cloud/

### Version

2021.7.3

**Comment by frenck** [comment]
The documentation is for the end-user of Home Assistant, not the developer. Therefore, I don't think that such a mention is fitting for our documentation.

Nevertheless, thanks for you suggestion 👍
