### ISSUE TITLE
Getting the Device ID to use for the send command service

### ISSUE THREAD

**Issue by atebeta** [home-assistant/home-assistant.github.io#18548]
### Feedback

It took me a while to figure out that in order to get the device ID that is used for the bridge parameter when calling the system_bridge.send_command service you need to go to Developer Tools -> Services and select the  system_bridge.send_command in GUI mode, then you can select your bridge, then switch to YAML mode which reveals the identifier.

This should be included in the documentation or there should be a better way to get the id.

### URL

https://www.home-assistant.io/integrations/system_bridge/

### Version

2021.7.3

**Comment by frenck** [comment]
The device ID is a UI-specific feature and not created for manual use. That said, you can use it that way, but... it was not meant to be used like that, thus not documented as such.

**Comment by atebeta** [comment]
Fair enough, but what if you just wanted to use the send_command service in a script or an automation? Or is the only intended use via the Developer Tools -> Services?

Edit: Nevermind, realise that the same interface will be available in the script and automation GUI on Lovelace. I'm just used to doing everything in YAML.
