### ISSUE TITLE
Uninstall HA on Windows

### ISSUE THREAD

**Issue by kirstenak** [home-assistant/home-assistant.github.io#18557]
### Feedback

Onboarding hung, so I closed the window and now I cannot get back in!  I started the hass.cmd again, but it wants me to sign into the installation I started to set up, but was not completed by HA!

I had copied my password to save later, but it did not go to the clipboard. Now I have tried hard as I might to remember the password, it was not too hard, but I cannot get in. Maybe the username is not in correctly, though I am sure it is right.

Now I want to uninstall the thing and start fresh but I cannot figure out how to uninstall what has been installed!

### URL

https://www.home-assistant.io/installation/windows/

### Version

2021.7.3

**Comment by frenck** [comment]
Hi there @kirstenak 👋 

Seems like you are looking for support, however, you have submitted documentation feedback instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Additionally, this page in our documentation might help:

<https://www.home-assistant.io/docs/locked_out/>

../Frenck
