### ISSUE TITLE
iAqualink Limitation

### ISSUE THREAD

**Issue by benjycov** [home-assistant/home-assistant.github.io#18550]
### Feedback

The iAqualink integration as stands only supports the 'Jandy' (US Pool Systems), the european 'Zodiac' systems such as Exo IQ are not supported.

### URL

https://www.home-assistant.io/integrations/iaqualink/

### Version

2021.7.3

**Comment by flz** [comment]
That's an underlying library limitation. Feel free to open an issue [there](https://github.com/flz/iaqualink-py).

**Comment by frenck** [comment]
@flz This is end-user documentation feedback that is given. Maybe the integration page should list supported devices?

**Comment by benjycov** [comment]
In essence iAquaLink is an authentication layer for two different families of devices. If I add the integration and the login, it authenticates then throws an error because I have the Zodiac device.

I can list devices it won’t work with if that helps? I’m not family with the devices it will work with.

**Comment by frenck** [comment]
> I can list devices it won’t work with if that helps?

We should list what we know what does work, not the other way around.

**Comment by benjycov** [comment]
I agree!

**Comment by flz** [comment]
> @flz This is end-user documentation feedback that is given. Maybe the integration page should list supported devices?

Oh, my bad. Didn't realize this was the docs repo.



> In essence iAquaLink is an authentication layer for two different families of devices. If I add the integration and the login, it authenticates then throws an error because I have the Zodiac device.
> 
> I can list devices it won’t work with if that helps? I’m not family with the devices it will work with.

Depending on what the error is, it might not be a ton of work to add support. Could you copy/paste it here.

**Comment by benjycov** [comment]
The error reported by the integration is:

No systems detected or supported
19 July 2021, 11:25:37 – (ERROR) Jandy iAqualink

**Comment by flz** [comment]
If you enable debugging for the iaqualink module, you might see something like that (which would indicate that the library found a system but it doesn't know how to handle it):

> 2021-04-12 08:20:08 WARNING (MainThread) [iaqualink] i2d is not a supported system type.

**Comment by flz** [comment]
Coincidentally, some people have reverse-engineered at least part of the Exo API in the [community forums](https://community.home-assistant.io/t/jandy-iaqualink-pool-integration/105633/324?u=flauran). I can't commit to delivering support for it anytime soon but I might be able to help.

**Comment by stepir** [comment]
just wanted to add that I'm in the same boat owning a Exo. I'm happy to help in testing and support @flz development as I can: please let me know how I can help
