### ISSUE TITLE
Control4 Beyond Lights

### ISSUE THREAD

**Issue by Xesyliad** [home-assistant/home-assistant.github.io#18574]
### Feedback

Will there be an opportunity to add other Control4 integrations beyond just lights, for example Relays and Scenes? I have additional integrations such as relays for gates and doors, as well as scenes associated with those relays which are through Control4 that are not exposed to HomeAssistant.

Thanks.

### URL

https://www.home-assistant.io/integrations/control4/

### Version

2021.7.3

**Comment by frenck** [comment]
Hi there @Xesyliad 👋 

It seems like you have a question, however, you have submitted documentation feedback.

If you are in need of support or have general questions, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

To answer your question: This is an open-source project, we rely on contributions made voluntarily by people around the world. Therefore, the answer to your question is: Maybe 🤷  Feel free to contribute if you can!

../Frenck
