### ISSUE TITLE
Blueprints - Using Automation Modes

### ISSUE THREAD

**Issue by davearneson** [home-assistant/home-assistant.github.io#18578]
### Feedback

It took some digging, but [this blueprint yaml example](https://www.home-assistant.io/docs/blueprint/schema/#example-blueprints) on this page is the only place I could find any documentation referencing the use of automation modes within blueprints.

I saw that this page says "the full schema for an automation applies," but it may still be helpful to add a small section or note regarding the use of modes in blueprint automations on this [Blueprint schema](https://www.home-assistant.io/docs/blueprint/schema/) page, or perhaps on the [Blueprint tutorial](https://www.home-assistant.io/docs/blueprint/tutorial/) or [Automation Modes](https://www.home-assistant.io/docs/automation/modes/) pages.

### URL

https://www.home-assistant.io/docs/blueprint/schema/

### Version

2021.7.4

**Comment by frenck** [comment]
I'm not sure how "everying" is available is confusing for automation modes and not for e.g., triggers? variables?

Don't get me wrong, I try to understand, but it feels weird to highlight just this one...

**Comment by davearneson** [comment]
First of all, I really appreciate all the time and effort you have put into this project.

Regarding this issue, I eventually figured it out, but I had a difficult time interpreting this information using the documentation.

I'm only suggesting adding some clearer guidance because I wanted to try to help make it easier for the next person to figure out. Many HA users, including me, have no programming background, and as far as I can tell, nowhere in the automation documentation is anything defined as "schema." So, without a clear knowledge of how that term was being used to describe the available automation components, I wasn't sure what "the full schema for an automation applies" actually meant in terms of what we can and cannot use in blueprints.

Triggers and actions are a [main focus of the tutorial](https://www.home-assistant.io/docs/blueprint/tutorial/), and because of the interaction between inputs and templates, [variables](https://www.home-assistant.io/docs/blueprint/schema/#blueprint-inputs-in-templates) are specifically addressed in the blueprint documentation.

So, in my situation, it would have helped to clarify what is available. "The full schema for an automation applies," is more confusing to me than, as you paraphrased, "'everything' is available." Something along the lines of, "The full schema for an automation applies - including triggers, conditions, actions, run modes, and variables." would have made a big difference for me.
