### ISSUE TITLE
Display a non-mdi icon or another image.

### ISSUE THREAD

**Issue by SefDik** [home-assistant/home-assistant.github.io#18581]
### Feedback

Hello,

I'm using  <ha-icon icon="mdi:home-assistant" /> quite a lot but there are some icons I have in 'www/icon/myicon.png' (/local/icon/myicon.png) that I would like to use;  I have done quite a bit of searching such as below but I cannot do this.
https://community.home-assistant.io/t/lovelace-markdown-card-with-icon-on-text-line/94316
 
 Can you offer any assistance please?

### URL

https://www.home-assistant.io/lovelace/markdown/

### Version

2021.7.4

**Comment by SefDik** [comment]
Sorry, a bit more hunting and I found this and it works ...

`<img src="/local/icon/garbage_skip_1.png" alt="Skip" style="float: left; margin-right: 10px;" />`

Source:
https://medium.com/markdown-monster-blog/getting-images-into-markdown-documents-and-weblog-posts-with-markdown-monster-9ec6f353d8ec

/0^0\    8-)

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by SefDik** [comment]
OK, thanks  Sent from my Galaxy
-------- Original message --------From: Franck Nijhof ***@***.***> Date: 23/07/2021  12:23  (GMT+01:00) To: "home-assistant/home-assistant.io" ***@***.***> Cc: SefDik ***@***.***>, Author ***@***.***> Subject: Re: [home-assistant/home-assistant.io] Display a non-mdi icon or another image. (#18581) 

Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our Community Forum or join our Discord chat server.

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
