### ISSUE TITLE
Templates link not working

### ISSUE THREAD

**Issue by VNRARA** [home-assistant/home-assistant.github.io#18594]
### Feedback

This link on doesn't seem to work anymore: https://my.home-assistant.io/redirect/developer_templates

It's this one: 

"If your automation uses templates in any part, you can do the following to make sure it works as expected:

Go to Developer tools -> [Template tab](https://my.home-assistant.io/redirect/developer_templates)."

### URL

https://www.home-assistant.io/docs/automation/troubleshooting/

### Version

2021.7.4

**Comment by VNRARA** [comment]
Still broken link

**Comment by frenck** [comment]
Thanks for reporting this one @VNRARA! I've opened up a PR to address the issue 👍
