### ISSUE TITLE
Schneider Dimmrs

### ISSUE THREAD

**Issue by niraviry** [home-assistant/home-assistant.github.io#18595]
### Feedback

It seems like when I reboot HASSIO, I get a temporary warnings when addressing my Schneider Universal Dimmers.
It is a temporary issue as seen in the log file. The GUI is in Hebrew so some of it will not be clear to you but I guess you will understand. Anyway the dimmers do work fine but probably respond slower that normal thus generating this warning.
The Warnings are:

Could not sync group address '1/3/104' (basement_gym - Brightness)
18:59:56 – (WARNING) /usr/local/lib/python3.9/site-packages/xknx/remote_value/remote_value.py - ההודעה התרחשה לראשונה בשעה 18:59:42 והיא מופיעה 10 פעמים
Error: KNX bus did not respond in time (2.0 secs) to GroupValueRead request for: 1/3/104
18:59:56 – (WARNING) /usr/local/lib/python3.9/site-packages/xknx/core/value_reader.py - ההודעה התרחשה לראשונה בשעה 18:59:42 והיא מופיעה 10 פעמים

### URL

https://www.home-assistant.io/integrations/knx/

### Version

2021.7.4

**Comment by frenck** [comment]
Hi there @niraviry 👋 

Thanks for your message. It seems like you want to report an issue with the KNX integration of Home Assistant, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to fix a bug in the integration.

Please report issues with Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by niraviry** [comment]
OK.

Sorry.

‫בתאריך שבת, 24 ביולי 2021 ב-20:31 מאת ‪Franck Nijhof‬‏ <‪
***@***.***‬‏>:‬
