### ISSUE TITLE
Проблема с Moon

### ISSUE THREAD

**Issue by vvv279** [home-assistant/home-assistant.github.io#18598]
### Feedback

Не отрабатывает датчик moon значения (The moon value sensor does not work out): 

1. new_moon
2. waxing_crescent
3. first_quarter
4. full_moon
5. last_quarter
6. waning_crescent

### URL

https://www.home-assistant.io/integrations/moon/

### Version

2021.7.4

### Additional information

Выдает датчик moon значения (Outputs the moon value sensor): 

1. waxing_gibbous
2. waning_gibbous

**Comment by frenck** [comment]
Hi there @vvv279 👋 

It seems like you want to report an issue, however, you have submitted documentation feedback instead.
If you want to report an issue with an Home Assistant integration, please report it here:

<https://github.com/home-assistant/core/issues>

Please note: English only 👍 

../Frenck

**Comment by vvv279** [comment]
Thanks
