### ISSUE TITLE
Motion Sensors not reporting state other than clear & disconnected.

### ISSUE THREAD

**Issue by braymond1776** [home-assistant/home-assistant.github.io#18592]
### Feedback

It appears that the motion sensors are either not reporting or what I believe may be happening is that the state isn’t changed long enough to catch it on the api request. I know the motions are indeed reporting as the app notifications do work.  I wanted to report, just in case this is not expected behavior. Thanks!

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2021.7.4

**Comment by bachya** [comment]
[From the docs](https://www.home-assistant.io/integrations/simplisafe/):

>Sensor status is only available for SimpliSafe V3 systems and is updated once every 30 seconds, so information displayed in Home Assistant may be delayed.

Can you confirm that you alter a sensor, wait a full 30 seconds, and that even then, the Home Assistant entity doesn't update?

**Comment by braymond1776** [comment]
I can confirm that I've created motion in front of two seperate sensors (walking between two different rooms) for approx 90 seconds (on high sensitivity) and have not been able to get a successful state change in homeassistant. I have not looked into trying to alter the state via the Simplisafe API.

**Comment by bachya** [comment]
Unfortunately, you may just be experiencing the 30-second update interval: for the motion sensor to trigger in HASS, you'd need it to trigger _exactly_ when the update interval occurs. Not a bug in the integration – just an unfortunate downside of only being able to poll every 30 seconds.

**Comment by braymond1776** [comment]
Thanks that’s what I was assuming, but I just wanted to verify. Thanks
