### ISSUE TITLE
Contradictory description for sun elevation

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#18606]
### Feedback

The elevation variable for the sun entity is described in two different ways in this document.

In the subsection "configuration variables" it is described at "The (physical) elevation of your location, in **meters above sea level**"

In the State attributes table it is described as the "**angle between the sun and the horizon**"

Which one is correct for the current public release channel?

### URL

https://www.home-assistant.io/integrations/sun/

### Version

2021.7.4

**Comment by frenck** [comment]
Both are correct. One is the configuration, the other a state. Those are different things and different elevations.
