### ISSUE TITLE
Incomplete Instructions

### ISSUE THREAD

**Issue by Agoodpaddlin** [home-assistant/home-assistant.github.io#18607]
### Feedback

When setting up a VBox VM using the downloaded image, the instructions assume you know where to locate settings required when going through setup process.

1. Just writing Other Linux 64bit is not enough.
- Type = Linux
- Version - Other Linux 64bit

2. User must select EXPERT to see the option to use an existing virtual hard disk file.

Two very simple additions to save alot of time for newer users.

### URL

https://www.home-assistant.io/installation/windows/

### Version

2021.7.4

**Comment by ludeeus** [comment]
Please make a pull request with your findings against this file <https://github.com/home-assistant/home-assistant.io/blob/current/source/_includes/installation/operating_system.md?plain=1#L177>
