### ISSUE TITLE
Nexia integration not updating

### ISSUE THREAD

**Issue by Nbr1Sniper** [home-assistant/home-assistant.github.io#18604]
### Feedback

The integration doesn’t get temperature adjustments that are preformed on the thermostat by hand. Only when I make changes in Home Assistant 

### URL

https://www.home-assistant.io/integrations/nexia/

### Version

2021.7.4

**Comment by frenck** [comment]
Hi there @Nbr1Sniper 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

../Frenck
