### ISSUE TITLE
Provide a list of devices detected using DHCP

### ISSUE THREAD

**Issue by briandking** [home-assistant/home-assistant.github.io#18618]
### Feedback

In the discovery module they list all the devices that can be detected via zeroconf. A similar list for DHCP would be useful so that you know how to have your device auto detected. E.g. Reading the [broadlink page](https://www.home-assistant.io/integrations/broadlink/) it says it is able to be auto-discovered, but provides no clue how to trigger that auto discovery. Browsing through the module it seems like it uses DHCP. Ideally a user wouldn't have to know how to find the modules on the filesystem or read the code.

Thanks for creating and maintaining an incredibly useful piece of software. It's much appreciated!

I'm not 100% sure this is a correct list, but it appears as if these might be the current devices detectable via DHCP:

```
# find /usr/src/homeassistant/homeassistant/components/ -name manifest.json | xargs grep '"dhcp":' | awk -F/ '{print $(NF-1)}'
axis
tplink
emonitor
powerwall
guardian
somfy_mylink
goalzero
roomba
ring
rachio
blink
sense
screenlogic
myq
nuheat
solaredge
toon
samsungtv
verisure
yeelight
nest
isy994
gogogate2
nexia
smartthings
squeezebox
tado
tuya
flume
broadlink
august
lyric
hunterdouglas_powerview
nuki
tesla
```

### URL

https://www.home-assistant.io/integrations/dhcp/

### Version

2021.7.4

**Comment by frenck** [comment]
Personally I think such list are hard to maintain.

What would be the added benefit?

**Comment by briandking** [comment]
That is a valid point of view. It might be hard to maintain. I'm not sure how often new components are added that use dhcp discovery. Maybe the list would only be good for a few weeks, or maybe for a few years?

The benefit is that end users would have the option of reading the documentation to find answers rather than having to read the code. 

What prompted me to submit this as a suggestion was that I was trying to get my broadcom device added and after months of waiting for it to be auto discovered (like many of my other devices) I finally decide to dig through the code and realized it used dhcp auto-discovery while the rest of my successfully discovered devices used mDNS.  I assumed this meant I would have to reboot the device to generate a DHCP request so I gave that a shot. After doing that, I still wasn't sure I'd interpreted it correctly when the device didn't show up for quite some time.

Maybe there is a better option but I'm not sure what it is. As an end user ideally you should be able to stay in the GUI and the documentation for anything that is auto-discovered. You shouldn't have to dig through code. That works for you and I, but wouldn't work for a lot of people.

**Comment by frenck** [comment]
Alright, I'll look into it 👍
