### ISSUE TITLE
config file "path to your config" 

### ISSUE THREAD

**Issue by npaisnel** [home-assistant/home-assistant.github.io#18610]
### Feedback

You are talking to a simpleton here...

The instructions to create a yaml file I worked out by myself.
I created a homeassistant directory in /home/pi/

then sudo nano docker-compose.yml

I then pasted the text from the RPi3 'box'

`version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi3-homeassistant:stable"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host`

BUT

the line 
** - /PATH_TO_YOUR_CONFIG:/config**

I do not understand

do I just leave it as  - /PATH_TO_YOUR_CONFIG:/config
or do I change it ..

if so to what ?  What config file? do you mean the yaml file ? or is there another config file?

if another config file?  where is it located?
I cannot see any config files 

do i just put ..for instance

/home/pi/homeassistant

the instructions do not state what the config files is called or where it is expected to be. 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.7.4

**Comment by ludeeus** [comment]
If you want your configuration files to be located under `/home/pi/homeassistant` on the host, then yes, you replace `/PATH_TO_YOUR_CONFIG` with `/home/pi/homeassistant`
The files are created on first boot of the server if they are missing from the mapped directory

**Comment by npaisnel** [comment]
OK, thanks 

understood
