### ISSUE TITLE
Option for steady values

### ISSUE THREAD

**Issue by perozonp** [home-assistant/home-assistant.github.io#18616]
### Feedback

I have implemented a water counter with a flow meter that gives pulses for each XXX amout of water.  Image below shows how it looks:

![image](https://user-images.githubusercontent.com/35159481/126915121-d63814d3-e59b-49e5-aec5-5711487ea0e4.png)

That triangle shaped peak shouldn't be like that, it should have been a single vertical line, but since the previous value (0) stayed like that for several minutes then the db was not updated until a new value arrived (the meter reports every minute over mqtt), and the graph traced the line using raw data from the db, so technically the line is correct but the resulting graph is misleading as it makes think there was a steady increase in the counting over several minutes when what really happened is that increase in the counting was over a single minute.
I've seen this problem solved at the DB level, by repeating the previous value with a timestamp of "one second less", making the raw data correct for the graph. I think it would be possible to offer a pre-processing option in the graph itself so (if selected) it fills the raw (db) data with "one second less" values and then graph it.

Anyone willing to work on this improvement?

Regards... Nestor Perozo.

### URL

https://www.home-assistant.io/lovelace/history-graph/

### Version

2021.7.4

**Comment by frenck** [comment]
Hi there @perozonp 👋 

It seems like to request a feature, however, you have submitted documentation feedback instead.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
