### ISSUE TITLE
Splitting up the config

### ISSUE THREAD

**Issue by davidrustingha** [home-assistant/home-assistant.github.io#18617]
### Feedback

I think it would be a good idea to update the documentation about splitting the config. I came to this conclusion because I am trying to split my template entities config and can't for the life of me figure out how to split the trigger section. And since there have been lots of upgrades to Home Assistant and the way things have to be coded in the backend, an update would be nice.

### URL

https://www.home-assistant.io/docs/configuration/splitting_configuration/

### Version

2021.7.4

**Comment by frenck** [comment]
In sorry to day, but there hasn't been any upgrades on how templates worked.
I have check the page and the examples are correct.

Which specific part is outdated?

**Comment by davidrustingha** [comment]
I don't think it's outdated, because most of it is still relevant. But the part I struggle with is the following:

I have split up my config for the bigger part, like this

template:
  - sensor: !include ...

But I can't figure out how I could do the same for the template trigger because the indentation is different.

**Comment by frenck** [comment]
Aah, ok this is a support question.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
