### ISSUE TITLE
Load history

### ISSUE THREAD

**Issue by ovanpeve** [home-assistant/home-assistant.github.io#18625]
### Feedback

Hi,
Is there any way to load the history of SMA production into HA?

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2021.7.4

**Comment by frenck** [comment]
Hi there @ovanpeve 👋 

It seems you are in need of support / have questions about Home Assistant, however, you have submitted documentation feedback.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

As for your question: No, Home Assistant doesn't have such a thing.

../Frenck
