### ISSUE TITLE
'search for your integration in that list.'

### ISSUE THREAD

**Issue by IIREDII** [home-assistant/home-assistant.github.io#18626]
### Feedback

What if the integrations you are looking for aren't on there? For example, turns out Silvana Smart + off the bat aren't a simple search and add device, meross smart gararge, i still cant figure out how to get that integrated. 

Instead of assuming success here, we should assume failure, and start providing resources for devices that might not have simple plug and play functionality, As I have no clue what I'm looking for or doing to integrate half of my devices.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2021.7.4

**Comment by ludeeus** [comment]
None of those 2 examples exist <https://www.home-assistant.io/integrations>? so not sure what you are after here?

**Comment by IIREDII** [comment]
That answer alone is the point. You know that they don’t exist, how? Exist as in being? They exist. Exist as in work on homeassistant? They do that too. But not off the shelf there are other steps other things I’m going to have to do to integrate, most of my products do not immediately integrate with homeassistant. And digging out the information I need is terrible.

So to reiterate the existing complaint to just state integrate your devices, as if it’s as easy as 123 for 90% of the users.Expecting everyone to have this plethora of existing integrated devices and to know what they’re looking for is presumptuous, Assume on this step new people will fail miserably and let’s immediately provide them help with links and “known common devices” and example would be anything less than $25 at Walmart that calls itself a smart device. If it’s available for $25 or less someone is buying it and trying to use it. so Right here and there lets take new people to places that will help them integrate devices that may not have a easily supported solution. This will get them off the bat rolling on how to troubleshoot dig and re-search their own devices but we need to give helpful links immediately because digging this out alone is ridiculous and there are so many nuances and deviations most people don’t understand them.

Thanks
Roth Alexander
________________________________

**Comment by frenck** [comment]
Hi there Roth,

For each integration there is documentation on our website, which can be found here:

<https://www.home-assistant.io/integrations/>

> You know that they don’t exist, how?

Well, the above link is how. It is listed everywhere in the documentation and website and even is linked in the top menu of every single page.

As said by Ludeeus above, the ones you mentioned are not on the list. I'm not sure where your suggestion/comments need to go. If you need Home Assistant to add support for new devices, feel free to add them. This is an open-source project, which relies on contributions from people like me and you.

Alternatively, you can try requesting support for a new device/brand on our community forums:

<https://community.home-assistant.io/c/feature-requests/13>

Thanks

../Frenck
