### ISSUE TITLE
Referenced tool seems to be end of life

### ISSUE THREAD

**Issue by bioxz** [home-assistant/home-assistant.github.io#18633]
### Feedback

The referenced tool "LANnouncer" seems to be unavailable from official sources. The link to the developers webpage is dead, the application itself from the Play Store seems to be disabled as well (all my devices are incompatible, ranging from Android 4 to 12). I can't tell if the integration itself still works (I would guess so), but the documentation should mention that the used tool seems to be end of life.

### URL

https://www.home-assistant.io/integrations/lannouncer/

### Version

2021.7.4

**Comment by frenck** [comment]
At least 55 installation report the integration as active in use:

![image](https://user-images.githubusercontent.com/195327/127192431-7d5a4188-744a-4fbb-9144-c25a049c4811.png)
