### ISSUE TITLE
ph is wrong and need to control the heater

### ISSUE THREAD

**Issue by Vorms** [home-assistant/home-assistant.github.io#18632]
### Feedback

Hello,
Many thanks for the integration of omnilogic to H.A.
Unfortunatli, the ph is wrong.
Now I have 7.4 in the cell applicaiton and 8.0 in H.A.

And pleas add the heater control.
When it is raining I don't use the swiming pool and I can switch off the heater.

Many thanks for your work !

Best regards

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2021.7.4

**Comment by djtimca** [comment]
The heater control will come in a future release. We have it working, just taking some time to get each platform added to the Home Assistant core.

You should be able to adjust your pH using the integration configuration using the pH offset setting so that it reports correctly in your dashboard.

**Comment by Vorms** [comment]
how !
nice for the ph ! thanks a lot !

For your information about the heater, I wrote to hayward to ask to have a
future firmware able to connect the heat pump with the RS485 bus and not
with a single contact.

Best regards and many thanks for your work.
Please take me in touch about the heater switch !

Best regards
Thierry Vorms

Le mar. 27 juil. 2021 à 09:13, djtimca ***@***.***> a écrit :

> The heater control will come in a future release. We have it working, just
> taking some time to get each platform added to the Home Assistant core.
>
> You should be able to adjust your pH using the integration configuration
> using the pH offset setting so that it reports correctly in your dashboard.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/ed8bb3dcfd0e76544b119a232f5975ebac846492?url=https%3A%2F%2Fgithub.com%2Fhome-assistant%2Fhome-assistant.io%2Fissues%2F18632%23issuecomment-887501205&userId=3563000&signature=8f3160310b5e9034>,
> or unsubscribe
> <https://mailtrack.io/trace/link/39d1735afe2454d67d974a692ce7db98dfe7358b?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA6QD4NMSIAKDJSSNBSMUWTTZ2WHZANCNFSM5BCGV52Q&userId=3563000&signature=ac085ce9fb02fbfe>
> .
>


-- 
Thierry Vorms
Québec Canada
