### ISSUE TITLE
No longer available?

### ISSUE THREAD

**Issue by aceindy** [home-assistant/home-assistant.github.io#18639]
### Feedback

Doesn't show anymore as integration:
![image](https://user-images.githubusercontent.com/94692/127223064-9f1c1731-e056-4ad6-a790-bf65c568b697.png)

### URL

https://www.home-assistant.io/integrations/buienradar/

### Version

2021.7.4

**Comment by aceindy** [comment]
sorry..was looking at the wrong place...

**Comment by frenck** [comment]
Stuff happens! 👍 

![](https://media3.giphy.com/media/elsol3P5Jt2ASsxLva/giphy-downsized-medium.gif)
