### ISSUE TITLE
Numeric state for Conditional Card

### ISSUE THREAD

**Issue by liksvette** [home-assistant/home-assistant.github.io#18647]
### Feedback

It would be nice to set a numeric state for conditional cards. E.g. I have set up a gauge to tell me how many minutes till the bus arrives. This bus only leaves at night. Therefore I only want the gauge to show up when it's less than sixty minutes to departure.

### URL

https://www.home-assistant.io/lovelace/conditional/

### Version

2021.7.4

**Comment by frenck** [comment]
Hi there @liksvette 👋 

It seems like you want to request a feature, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust that builds a new feature 😉 

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by liksvette** [comment]
You're absolutely right. My mistake!
Thanks.

**Comment by frenck** [comment]
![](https://media0.giphy.com/media/QUlbCmsuVVAXu/giphy.gif)
