### ISSUE TITLE
Clearer Introduction

### ISSUE THREAD

**Issue by kieranskelly** [home-assistant/home-assistant.github.io#18643]
### Feedback

The difference between Home Assistant Core and Home Assistant Container is not clear to most novices. 

An introductory section could explain that there are three methods for installing Home Assistant.
i.e....

There are three ways to install Home Assistant on the Raspberry Pi.  The first is the easiest and most common, while the second and third are for more special cases. 
--
The suggested hardware section could be moved up into the aforementioned introduction section because it applies to all install methods. 

I am bringing this up because I just spent a morning and afternoon trying to install via methods 2 and 3, not realizing it was either OR. Hopefully others will not make this mistake in the future. 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.7.4

**Comment by klaasnicolaas** [comment]
What about this comparison? https://www.home-assistant.io/installation/#compare-installation-methods
