### ISSUE TITLE
Octoprint height sensor

### ISSUE THREAD

**Issue by hatjan** [home-assistant/home-assistant.github.io#18645]
### Feedback

Hi, great integration, very helpful to monitor printing while chilling in the living room!
I'd like to have one additional sensor: Current height. This is a known Octoprint value and should be easy to transfer.
Thx hatjan

### URL

https://www.home-assistant.io/integrations/octoprint/

### Version

2021.7.4

**Comment by frenck** [comment]
Hi there @hatjan 👋 

It seems like you want to request a new feature, however, you have submitted documentation feedback instead. There is no amount of documentation that I can adjust to make a new feature appear 😬 

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
