### ISSUE TITLE
Extra CGI commands PDF outdated

### ISSUE THREAD

**Issue by diegomontanaduarte** [home-assistant/home-assistant.github.io#18654]
### Feedback

Please update the link regarding Foscam CGI User Guide documentation.

https://www.foscam.es/descarga/Foscam-IPCamera-CGI-User-Guide-AllPlatforms-2015.11.06.pdf

### URL

https://www.home-assistant.io/integrations/foscam/

### Version

2021.7.4

**Comment by frenck** [comment]
Thanks, @diegomontanaduarte 👍 

I've opened up a PR to adjust the documentation.
