### ISSUE TITLE
Modbus tcp disconnection

### ISSUE THREAD

**Issue by Sberlone85** [home-assistant/home-assistant.github.io#18665]
### Feedback

Hello, I state that for problems connecting to the ADSL network I have to restart the modem every night. Unfortunately, when restarting, the connection to the modbus rs485 / tcp converter remains down. This happens from the core-2021.7.3 release. Before, everything worked fine. Below is my current configuration. Thanks
- name: hub2
     type: tcp
     host: 192.168.1.XX
     port: XXXX
     delay: 5
     timeout: 600
     close_comm_on_error: false

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.7.4

**Comment by janiversen** [comment]
Please make a debug log as pr documentation https://www.home-assistant.io/integrations/modbus/#opening-an-issue

**Comment by Sberlone85** [comment]
![Cattura2](https://user-images.githubusercontent.com/77581462/127726545-3b120a14-ca7f-492c-b438-3d791cbed99d.JPG)
![Cattura3](https://user-images.githubusercontent.com/77581462/127726552-c37fc925-5294-4aa1-81ec-f050d5bb49df.JPG)
after 03:57:27 (the moment when the modem is turned off) I no longer receive any data and the connection is down. It seems as if a buffer is clogged ..... after restarting the modem if I try to reach the web page of the modbus converter I reach it regularly but it signals me that it has not received any packets

**Comment by janiversen** [comment]
Just realised you have reported this issue on our documentation repo, this do not seem to be a documentation issue.

Development issues are here:
https://github.com/home-assistant/core/issues

**Comment by janiversen** [comment]
I made a small test setup to check this issue, and I see the following:
a) start modbus-tcp, start hass, sensor get values.
b) after a while stop modus-tcp, sensors changed to not available.
c1) restart modus-tcp after 10minutes, sensors get values again
c2) After 1 hours the modbus integration still tries to reconnect, and reconnects when modus-tcp is restarted, sensors get values again.

However why do you have "close_comm_on_error: false" I am not sure how the library handles this for tcp connections, but you want to opposite, you want the connection to be closed, to it can be reconnected or not ?

**Comment by Sberlone85** [comment]
I added:
     delay: 5
     timeout: 600
     close_comm_on_error: false
to try to overcome this problem but unfortunately it continues to present itself.
The sensors when they become unavailable do not return until I restart the core or the server.

**Comment by janiversen** [comment]
Why do you continue to have “close_comm_on_error: false” as I wrote before that is not what you want.

**Comment by janiversen** [comment]
This is not a documentation issue, if it is still open then please look at the open issues:
https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+modbus%22+
and either add your comments on one of these issues or file a new issue.

Closing documentation issue.
