### ISSUE TITLE
why i can't find service in my HA? (like Service ezviz.alarm_sound, Service ezviz.ptz, Service ezviz.set_alarm_detection_sensibility)

### ISSUE THREAD

**Issue by s1230988** [home-assistant/home-assistant.github.io#18661]
### Feedback

I success install this Ezviz integration into our HA,  but I just see Service `camera.disable_motion_detection’ and Service `camera.enable_motion_detection’ in our service, other service(like Service ezviz.alarm_sound, Service ezviz.ptz, Service ezviz.set_alarm_detection_sensibility, Service ezviz.sound_alarm, Service ezviz.wake_device) don't show on my service 
interface. I'm sure my camera support theses function.

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.7.4

**Comment by frenck** [comment]
These services have been added in Home Assistant 2021.7.0, make sure you run at last that version.

**Comment by s1230988** [comment]
> These services have been added in Home Assistant 2021.7.0, make sure you run at last that version.

Thank you for our reply, I will try update my version
