### ISSUE TITLE
Extend Function to AT Mega boards

### ISSUE THREAD

**Issue by aquavass** [home-assistant/home-assistant.github.io#18672]
### Feedback

Hi, is it possible to extend Function to AT Mega 256 and UNO boards as I am using wired ethernet connection.

Many Thanks

### URL

https://www.home-assistant.io/integrations/esphome/

### Version

2021.7.4

**Comment by jesserockz** [comment]
No nice way to say this, but... No, it won't work for regular Arduino boards and it's too much effort to adapt the code.
