### ISSUE TITLE
Manual Polling

### ISSUE THREAD

**Issue by AdamRidley** [home-assistant/home-assistant.github.io#18686]
### Feedback

Under manual polling the documentation says "To use more granular polling, disable automated polling in your config entry’s System Options."

As far as I can see there is no information anywhere on the home assistant docs about how to disable automated polling for an entity. I get the impression this can't actually be done! I can't even see documentation on how to change the polling interval for the maps travel time integration.

### URL

https://www.home-assistant.io/integrations/google_travel_time/

### Version

2021.7.4

**Comment by frenck** [comment]
Every integration has the system option to disable polling:

![image](https://user-images.githubusercontent.com/195327/127844811-b13aab0e-d873-46d2-ac81-c14cab9fc507.png)

Next, you can use the `homeassistant.update_entity` service to trigger a manual poll.

https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantupdate_entity

It has also been announced here:

<https://www.home-assistant.io/blog/2021/06/02/release-20216/#disable-polling-updates-on-any-integration>
