### ISSUE TITLE
The user manual

### ISSUE THREAD

**Issue by gladius7** [home-assistant/home-assistant.github.io#18684]
### Feedback

The user manual for connecting Google Assistant to nabucasa was written by a professional, not considering that a simple user has never done this. Need details or examples where to go
, what to do. I could not connect. Written through a translator, sorry for the mistakes.

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2021.7.4

**Comment by ludeeus** [comment]
That is explained here <https://www.nabucasa.com/config/google_assistant/> which you get to when clicking the link in:
> For Home Assistant Cloud Users, documentation can be found [here](https://www.nabucasa.com/config/google_assistant/).

**Comment by frenck** [comment]
Closing this as a misinterpretation for the documentation to use for the use case.

**Comment by gladius7** [comment]
Спасибо. Подключил.
