### ISSUE TITLE
 Cannot watch for dhcp packets: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by giuseppe072000** [home-assistant/home-assistant.github.io#18685]
### Feedback

Logger: homeassistant.components.dhcp
Source: components/dhcp/__init__.py:291
Integration: DHCP Discovery (documentation, issues)
First occurred: 6:13:47 PM (1 occurrences)
Last logged: 6:13:47 PM

Cannot watch for dhcp packets: [Errno 13] Permission denied

what happend?

### URL

https://www.home-assistant.io/integrations/dhcp/

### Version

2021.7.4

### Additional information

what solution is to make dhcp working ?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
