### ISSUE TITLE
Workday

### ISSUE THREAD

**Issue by tomsruk** [home-assistant/home-assistant.github.io#18690]
### Feedback

My alarm failed to go off this morning due to workday showing as “off”. Why? I’m in the UK, but more specifically England. 

Scotland does have a bank holiday today but England doesn’t. England doesn’t have its own country code though. 

Can this be fixed?

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2021.7.4

**Comment by frenck** [comment]
Hi there @tomsruk 👋 

Seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to fix a bug in code.

Please files issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks!

../Frenck
