### ISSUE TITLE
input_number

### ISSUE THREAD

**Issue by andrey170183** [home-assistant/home-assistant.github.io#18692]
### Feedback

Why does input_number display numbers with tenths ("..,0") on lovelace? The step = 10;
![1](https://user-images.githubusercontent.com/42129962/127840205-eaca5a59-eccd-41fd-89d7-ffd5f4ae8ef3.jpg)

input_number:
  u_s_air_quality_critical_level:
    name: Крит уровень
    min: 10
    max: 100
    step: 10
    unit_of_measurement: AQI

### URL

https://www.home-assistant.io/integrations/input_number/

### Version

2021.7.1

**Comment by frenck** [comment]
Hi there @andrey170183 👋 

It seems like you have a question, but you have submitted documentation feedback instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

To answer your question quickly (and maybe a bit technical), numbers are defined as floating-point numbers and thus will always have decimals.

Thanks! 👍
