### ISSUE TITLE
Talk

### ISSUE THREAD

**Issue by jdinkel** [home-assistant/home-assistant.github.io#18717]
### Feedback

Something I would be interested in is interacting with Nextcloud Talk - be able send messages from Talk to HA, send messages to Talk from HA, get pushed user status, whether or not in a video conference and whether or not muted, etc.

### URL

https://www.home-assistant.io/integrations/nextcloud/

### Version

2021.7.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
