### ISSUE TITLE
Mosquitto Add-On DOCS.md ACL Guidance Breaks Integration

### ISSUE THREAD

**Issue by rpfinneran** [home-assistant/home-assistant.github.io#18716]
### Feedback

The docs.md file for the mosquitto add-on has a section on leveraging an ACL to restrict user access to topics. Seems like a good practice.    

I'd recommend updating the documentation. If a user implements the ACL file, they must include the 'homeassistant' user with read/write priv to all topics, otherwise HA won't be able to discover new entities or even determine entity availability for manually added entities in the configuration.yaml.    

Took me about 15 minutes of watching MQTT messages on Explorer and checking and rechecking topic name and availability words trying to find my typo.    

Local documentation page is: /hassio/addon/core_mosquitto/documentation   

Bottom code block should be changed from:   

```
user [YOUR_MQTT_USER]
topic readwrite #
```

To:   

```
user homeassistant
topic readwrite #

user [YOUR_MQTT_USER]
topic readwrite #
```

### URL

https://github.com/home-assistant/addons/blob/master/mosquitto/DOCS.md

### Version

Mosquitto 6.0.1

**Comment by rpfinneran** [comment]
Still relevant, and a simple fix.

**Comment by frenck** [comment]
Hi there @rpfinneran 👋 

This is the issue tracker for our website: https://www.home-assistant.io,
however, your issue seems to be with an add-on. Please report the issue with the Add-on repository instead:

https://github.com/home-assistant/addons/issues>

Thanks 👍 

../Frenck
