### ISSUE TITLE
Blink integration stops working 

### ISSUE THREAD

**Issue by MiAutomations** [home-assistant/home-assistant.github.io#18714]
### Feedback

Hello Team 

I'm using the Blink integration for a long time, but today the stream stop working the camera entity goes to unavailable in order to try solve this issue I start to disable an re-enable the integration without any luck, after this I try to reload several times but still not working after this I deleted the integration and install it again, but now I only have one  entity  available over this integrations ....

![image](https://user-images.githubusercontent.com/47602733/128041299-1b256f39-29fa-4192-891d-e8e20ec65d62.png)

Can you please help me in oder to solve this issue ?

Thank you in advance for your support and best regards 

### URL

https://www.home-assistant.io/integrations/blink/

### Version

2021.7.4

### Additional information

Version Home Assistant 2021.7.4

**Comment by MiAutomations** [comment]
Hello @fronzbot 

After several tries I successfully get the camera again and is working, but with a diferente behavior in the past there is present one device and 7 entities and now no device is present from the integration as you can see in the picture bellow 
![image](https://user-images.githubusercontent.com/47602733/128082603-045c1847-ba08-4517-a207-c9eac9e60cbe.png)


Thank you for your support and best regards

**Comment by watzon** [comment]
I’m having this same issue, though I just stared with HA and just got my Blink cameras, so I can’t say I’ve ever experienced them working together. It would be nice to have a working stream or even just have a working image preview though

**Comment by frenck** [comment]
Hi there all 👋 

Is seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix an issue.

Please report issues with Home Assistant Core integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
