### ISSUE TITLE
Skybell integration no longer working

### ISSUE THREAD

**Issue by rkershenbaum** [home-assistant/home-assistant.github.io#18736]
### Feedback

Skybell seems to have changed their authentication mechanism and, unless you're a Skybell partner company, the authentication only works from the Skybell app.  So this integration no longer works.  The authentication fails.

### URL

https://www.home-assistant.io/integrations/skybell/

### Version

2021.8.0

**Comment by frenck** [comment]
Hi there @rkershenbaum 👋 

It seems like you want to report an issue with an integration, however, you have submitted documentation feedback instead.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
