### ISSUE TITLE
Total PV production does not show up in new Energy dahboard for Homeassistant

### ISSUE THREAD

**Issue by JanValkenier** [home-assistant/home-assistant.github.io#18735]
### Feedback

The latest home assistant provides a new energy dashboard. Howerver I can't get the sensor.grid_power configured for solar production in this dashboard.

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2021.8.0

### Additional information

https://www.home-assistant.io/more-info/statistics/

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
