### ISSUE TITLE
Need multiple color zones

### ISSUE THREAD

**Issue by booroondook-eng** [home-assistant/home-assistant.github.io#18744]
### Feedback

For example: I want to use a measurement chart to see the current voltage in my house. There is a standard allowable voltage of 230V ± 10%, that is, the range is 217V to 243V. And I would like the area below 217V to be red on the scale, the area from 217V to 243V to be green, and the area above 243V. - red again.
In other words, it is need to be able to create pairs of "yellow" and "red" areas on both sides of the "green" area.
Unfortunately, the current capabilities of this card do not allow this.

### URL

https://www.home-assistant.io/lovelace/gauge/

### Version

2021.8.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by amayii0** [comment]
Was looking for that feature request and found this issue
@booroondookZ please have a look at https://community.home-assistant.io/t/gauge-with-green-segment-in-the-middle/327348
