### ISSUE TITLE
Gauge sections

### ISSUE THREAD

**Issue by kruzgix** [home-assistant/home-assistant.github.io#18742]
### Feedback

Think about values, like humidity, that have several sections with the same colors. E.g.
Red: 0-20%
Yellow: 20-35%
Green: 35-60%
Yellow: 60-75%
Red: 75-100% 

### URL

https://www.home-assistant.io/lovelace/gauge/

### Version

2021.8.0

**Comment by frenck** [comment]
This is already supported.

**Comment by kruzgix** [comment]
If supported, please link to the documentation. It's not documented unter: https://www.home-assistant.io/lovelace/gauge/

**Comment by frenck** [comment]
https://www.home-assistant.io/lovelace/gauge/#severity

**Comment by kruzgix** [comment]
There's maybe a misunderstanding. The attached picture shows what I am looking for. The green range for humidity is a range (35-60%), if it's above it must become oragen/red again. Not good for your nor your house...

![ha_gauge_humidity](https://user-images.githubusercontent.com/49858723/128332820-32f2fcf1-20fd-4322-8d3c-161ff9c3b416.jpg)

**Comment by frenck** [comment]
That is a feature request, however, you have submitted documentation feedback instead.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by amayii0** [comment]
Here is link to feature request : https://community.home-assistant.io/t/gauge-with-green-segment-in-the-middle/327348
