### ISSUE TITLE
Broadlink SP3 Power Consumption Not Listed in Energy Configuration

### ISSUE THREAD

**Issue by jjmuriel** [home-assistant/home-assistant.github.io#18740]
### Feedback

Broadlink SP3 Power Consumption  is not listed in Energy Configuration:
![image](https://user-images.githubusercontent.com/17131600/128216669-d9af4778-c12a-4df7-b90a-00867b693956.png)
![image](https://user-images.githubusercontent.com/17131600/128216761-8c902cbe-56bb-41ae-911f-9c6a7f6f6af3.png)
![image](https://user-images.githubusercontent.com/17131600/128216831-04762ca5-46a0-47ca-9d72-14263dd55ae3.png)

### URL

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

### Version

2021.8.0

**Comment by frenck** [comment]
Power is not energy, those are different things.

Whatever is done, a power sensor cannot be added to the energy dashboard, as well, the energy dashboard is for energy, not for power.

**Comment by frenck** [comment]
More information can be found here:

<https://www.home-assistant.io/docs/energy/faq/#energy-vs-power>

And you could try this:

<https://www.home-assistant.io/docs/energy/faq/#creating-an-energy-sensor-out-of-a-power-sensor>

**Comment by jjmuriel** [comment]
Sorry and thank you, I configured this sensor:
# Calculate Energy (KWh) from Broadlink SP3
  - platform: integration
    source: sensor.toma_ventilador_estudio_switch_current_power
    name: Gasto Energía Ventilador Estudio
    unit_prefix: k
    unit_time: h
    round: 2

**Comment by jjmuriel** [comment]
Sorry and thank you.
