### ISSUE TITLE
Energy meters do not appear to support split phase metering (North America) "out of the box".

### ISSUE THREAD

**Issue by aaronsb** [home-assistant/home-assistant.github.io#18751]
### Feedback

Hi, in North America, energy meters in residential settings are most often found with split phase panels. That is, two legs and two clamp meters.

Please extend energy meter consumption and return to facilitate this difference in power delivery approach. Or, extend the documentation to give users a hint about how to build a template sensor to assist with this. My suggestion would be to open an improvement to the user experience, because asking someone to immediately start writing template sensors to use this nice new feature may put some people off of it.

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.0

### Additional information

![image](https://user-images.githubusercontent.com/2738471/128254545-2c843d04-f263-4178-81ee-c0ea8c1c9281.png)

**Comment by klaasnicolaas** [comment]
You can add multiple grid consumption and return to grid entities, if that is what you want/mean?

**Comment by aaronsb** [comment]
I was only able to select one entity. Then I realized I was not saving settings properly! Thanks.
