### ISSUE TITLE
GDPR Violation - Trackers on home-assistant.io

### ISSUE THREAD

**Issue by JanOstrowka** [home-assistant/home-assistant.github.io#18753]
### Feedback

To whom it may concern,

First of all, I would like to state that I have been a big fan of Home Assistant. It has set the new standard of smart homes and open source projects. What convinced me to try it in the first place was the following statement
> Open source home automation that puts local control and privacy first.
> via: [home-assistant.io/blog/](https://www.home-assistant.io/blog/)

Unfortunately, today I am opening the following issue, as the earlier mentioned website does not follow these standards. Most of all, home-assistant.io does not follow the GDPR either.

When visiting the official documentation of the Home Assistant we are greeted with the following list of trackers:

![image](https://user-images.githubusercontent.com/3185243/128245367-0b7e5505-54ba-48cf-85e0-2d53b7b0108a.png)
via: [Ublock Origin Browser Add-on](https://github.com/gorhill/uBlock/)

The following behavior is a serious violation of the GDPR as:
- There has been no consent given for tracking, and it has not been requested
_"‘consent’ of the data subject means any freely given, specific, informed and unambiguous indication of the data subject’s wishes by which he or she, by a statement or by a clear affirmative action, signifies agreement to the processing of personal data relating to him or her;"_
[GDPR Art. 4 (11)](https://gdpr-info.eu/art-4-gdpr/)

- there is no justified reason for the service's functionality, to collect the data using e.g connect.facebook.net tracker, used primarily for marketing purposes
_"The controller shall implement appropriate technical and organisational measures for ensuring that, by default, only personal data which are necessary for each specific purpose of the processing are processed."_
[GDPR Art. 25 (2)](https://gdpr-info.eu/art-25-gdpr/)

- Even if you decide to keep the earlier mentioned trackers, while requesting users consent to tracking, it has to be clearly stated in the privacy policy
_"The controller shall take appropriate measures to provide any information referred to in Articles 13 and 14 and any communication under Articles 15 to 22 and 34 relating to processing to the data subject in a concise, transparent, intelligible and easily accessible form, using clear and plain language, in particular for any information addressed specifically to a child. "_
[GDPR Art. 12 (1)](https://gdpr-info.eu/art-12-gdpr/)

___

Please take this issue seriously and respond within the next 30 days. I would appreciate if the appropriate actions are going to be undertaken, by the team responsible for the [home-assistant.io](https://www.home-assistant.io/) website. For starters, I would suggest removing the following:
- [connect.facebook.net](https://github.com/home-assistant/home-assistant.io/search?q=connect.facebook.net)
- [google-analytics.com](https://github.com/home-assistant/home-assistant.io/search?q=google-analytics)

Regards,
Jan

### URL

https://www.home-assistant.io/blog/

**Comment by balloob** [comment]
GDPR applies to companies. Home Assistant is not a company.

**Comment by ph00lt0** [comment]
@balloob sorry but this is complete non sense. The GDPR does not make any mention of it only applying to companies. There are only a few exceptions for example for law enforcement, but definitely not home assistant. 

Besides the legal part, I really don't think it matters. Home-assistant states that it puts privacy first, this is not the case on your website currently.

**Comment by JanOstrowka** [comment]
@balloob this is a very dull argument.

As @ph00lt0 has already said:
> The GDPR does not make any mention of it only applying to companies. There are only a few exceptions for example for law enforcement, but definitely not home assistant.

If the Home Assistant is not officially registered as an organization, you @balloob are personally liable for any privacy violation.

Moreover, how can you say that Home Assistant puts "privacy first" if you are openly tracking it's users? Don't you think it is unethical to do so, without even asking for consent or a good reason?
