### ISSUE TITLE
Growatt Solar integration doesn't show up at Energy solar

### ISSUE THREAD

**Issue by RualdOrdelman** [home-assistant/home-assistant.github.io#18754]
### Feedback

I used the Growatt integration for 3 solar panel inverters. Today I tried to add the sensor data from the Growatt integration to the new Energy implementation of the HA 2021.8.0 release. The Energy function doesn't show any of my Growatt sensor entities. 

I want to use sensor "sensor.pv_inverter_INVERTERNAME_curent_power_total" to show the current amount of power generated by that inverter. 

When I look at the new Energy functionality Growatt is listed as a supported integration. I also tried to remove the existing integration en re-add them. 

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.8.0

**Comment by RualdOrdelman** [comment]
@frenck. Good to know. Growatt inverters are not fully compatible yet with the new Energy functionality.

**Comment by frenck** [comment]
@RualdOrdelman Not sure why I needed to know?

**Comment by RualdOrdelman** [comment]
> @RualdOrdelman Not sure why I needed to know?

I thought you would be interested because Growatt is listed as supported. But nevermind, hopefully the original makers will reply / fix this issue.

**Comment by muppet3000** [comment]
@RualdOrdelman can you please show me where it says that Growatt is supported for the new "energy" functionality?

I only found out about this new functionality yesterday, I believe you're referring to this: https://www.home-assistant.io/lovelace/energy/

The fact that the plugin is tagged as "energy" has nothing to do with whether or not it supports the new energy functionality (afaik).

I believe this is a duplicate of https://github.com/home-assistant/core/issues/53963 so I'm going to track implementation progress against the original ticket that was raised.

@frenck I don't have permissions to link the two tickets, can you please mark this as a duplicate of 53963?

**Comment by RualdOrdelman** [comment]
> @RualdOrdelman can you please show me where it says that Growatt is supported for the new "energy" functionality?
> 
> I only found out about this new functionality yesterday, I believe you're referring to this: https://www.home-assistant.io/lovelace/energy/
> 
> The fact that the plugin is tagged as "energy" has nothing to do with whether or not it supports the new energy functionality (afaik).
> 
> I believe this is a duplicate of [home-assistant/core#53963](https://github.com/home-assistant/core/issues/53963) so I'm going to track implementation progress against the original ticket that was raised.
> 
> @frenck I don't have permissions to link the two tickets, can you please mark this as a duplicate of 53963?

You are right. I did the assumption that Solar was already fully supported in the new Energy panel because it listed on the Energy page. I will close this issue.
