### ISSUE TITLE
add another example with current receiver

### ISSUE THREAD

**Issue by defer110** [home-assistant/home-assistant.github.io#18755]
### Feedback

Hi Guys,
None of the methods that had examples worked for me so thought it would be helpful if there was another example. Also a few people in the forms struggled.

  - platform: nad
      type: Telnet
      port: 23
      host: "IP_ADDRESS"
      name: NAD T778
      min_volume: -60
      max_volume: -20
      sources:
        1: "TV"
        2: "BluRay"
        6: "bluOS

### URL

https://www.home-assistant.io/integrations/nad/

### Version

2021.8.0

**Comment by banan77** [comment]
Hi,
also have issues getting home assistant to work with NAD T758. It works fine with bluesound platform but the issue is I can't select external input sources with it. So headed to TCP or Telnet for NAD. Unfortunately TCP doesn't work at all (entity unavailable). It's bit better with Telnet - can switch receiver on/off, change volume but only using +/-, providing volume value (using i.e. slider) results in error and the same error appear when trying to change source (which is my biggest headache).
The error I get is: "can only concatenate str (not "int") to str"
[nad error log.txt](https://github.com/home-assistant/home-assistant.io/files/7055857/nad.error.log.txt)
Configuration:
media_player:
(...)
#NAD Telnet
  - platform: nad
    type: Telnet
    host: 192.168.50.30
    port: 23
    name: NAD Telnet
    volume_step: 1
    max_volume: -30
    sources:
        3: "3 PC"
        4: "4 Shield"
        6: "6 BluOS"
        7: "7 TV"

**Comment by richardsim7** [comment]
> Hi,
> also have issues getting home assistant to work with NAD T758. It works fine with bluesound platform but the issue is I can't select external input sources with it. So headed to TCP or Telnet for NAD. Unfortunately TCP doesn't work at all (entity unavailable). It's bit better with Telnet - can switch receiver on/off, change volume but only using +/-, providing volume value (using i.e. slider) results in error and the same error appear when trying to change source (which is my biggest headache).
> The error I get is: "can only concatenate str (not "int") to str"
> [nad error log.txt](https://github.com/home-assistant/home-assistant.io/files/7055857/nad.error.log.txt)

edit /usr/local/lib/python3.9/site-packages/nad_receiver__init__.py
line 46, from
`cmd = cmd + value`
to
`cmd = cmd + str(value)`

that should get input selection working on the T758 :)

**Comment by banan77** [comment]
Thank you richardsim7 !
Just had to find the path to file /nad_receiver/__init__.py (HA in docker) but that was exactly what was needed! Works fine now :)

**Comment by banan77** [comment]
> > Hi,
> > also have issues getting home assistant to work with NAD T758. It works fine with bluesound platform but the issue is I can't select external input sources with it. So headed to TCP or Telnet for NAD. Unfortunately TCP doesn't work at all (entity unavailable). It's bit better with Telnet - can switch receiver on/off, change volume but only using +/-, providing volume value (using i.e. slider) results in error and the same error appear when trying to change source (which is my biggest headache).
> > The error I get is: "can only concatenate str (not "int") to str"
> > [nad error log.txt](https://github.com/home-assistant/home-assistant.io/files/7055857/nad.error.log.txt)
> 
> edit /usr/local/lib/python3.9/site-packages/nad_receiver__init__.py line 46, from `cmd = cmd + value` to `cmd = cmd + str(value)`
> 
> that should get input selection working on the T758 :)

Hi,
Can this be fixed in source? Seems I need to apply this fix manually after each HA update...
