### ISSUE TITLE
No mention that there is no support for long-term statistics

### ISSUE THREAD

**Issue by ServusNL** [home-assistant/home-assistant.github.io#18767]
### Feedback

With the new Energy panel in the same version release of this (great) integration, it's a simple assumption that the Energy panel can be used with the YouLess integration. This does not appear to be the case at the moment because apparently the YouLess integration has no support (yet) for long-term stats. I believe it might prevent a lot of confusion and questions being asked if there is mention of this in the documentation. 

### URL

https://www.home-assistant.io/integrations/youless/

### Version

2021.8.0

**Comment by frenck** [comment]
We don't document this, as we believe all integrations should just support this. Raise an issue in the issue tracker instead (as instructed on the more information page).
