### ISSUE TITLE
Problem access user 

### ISSUE THREAD

**Issue by blade566** [home-assistant/home-assistant.github.io#18762]
### Feedback

I don't see the user name in the web. I think it is change in the web in Bmw. Can you change it ? Thanks you

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2021.8.0

**Comment by blade566** [comment]
Yes. But the code user not exist. Only the email in the web bmw connect

**Comment by frenck** [comment]
Hi there @blade566 👋 

It seems like you have a support question, however, you have submitted documentation feedback instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
