### ISSUE TITLE
Incorrect warning of Tesla MFA is not supported

### ISSUE THREAD

**Issue by patrickdev19** [home-assistant/home-assistant.github.io#18769]
### Feedback

Since 2021.8.0 the Tesla integration support MFA thanks to BreakingBread0! 
But on the documentation page it still says that MFA is not supported. I'm suppose that this can be removed. 

Thanks in advance!

### URL

https://www.home-assistant.io/integrations/tesla/

### Version

2021.8.0

**Comment by frenck** [comment]
PR is already open for this here: #18750
