### ISSUE TITLE
SolarEdge Power consumption meter not selectable for new Energy

### ISSUE THREAD

**Issue by TheBassman** [home-assistant/home-assistant.github.io#18761]
### Feedback

I have a SolarEdge integration (Web API) that provides production, consumption and grid power sensors, but in the new Energy module I can only select "solaredge (Lifetime energy)" sensor or some devices that provide power usage sensors, for the integration. Is there a plan to allow adding the others?:

sensor.solaredge_consumption_power
sensor.solaredge_grid_power

I tried changing the class of these sensors to "energy" but they were still not available to add to the UI.
Love where all this is going, keep up the great work!

### URL

https://www.home-assistant.io/docs/energy/solar-panels/

### Version

2021.8.0

**Comment by frenck** [comment]
You cannot use the power sensors for
The energy dashboard, as power is not energy. Those are different things.

**Comment by frenck** [comment]
See also:

https://www.home-assistant.io/docs/energy/faq/

**Comment by TheBassman** [comment]
Thanks for the info, I should have picked up on that.
The energy values are available via the API. Who maintains the integration? I would like to request that the values are pulled as part of the polling, and added as a sensor.
API Name: Site Energy 
Detailed site energy measurements including meters such as consumption, export (feed-in),
import (purchase), etc.

**Comment by frenck** [comment]
That would be a feature request, not a bug.

**Comment by kata685** [comment]
Hola buenas
Tengo creado sensores de energía a través de la platform: integration, pero cuando quiero utilizarlos no me aparecen en el listado de selección sabría decirme porque?

       consumo_casa:
        friendly_name: "consumo total casa"
        unit_of_measurement: "w"
        value_template: "{{ (states('sensor.shellyem_054356_channel_1_power')|float + states('sensor.shellyem_054356_channel_2_power')|float) |round(1) }}"


  - platform: statistics
    entity_id: sensor.consumo_casa
    name: consumo.stats
    precision: 1
    sampling_size: 60
    max_age:
      minutes: 60

Gracias

**Comment by Carlos-HA** [comment]
Hello, First of all thanks for all hard work!.
I’ve just added my solax variables, but I can’t see any graphs... May be I’ve selected wrong variables.
Is it possible changing variables?. Thanks a lot.
Carlos
