### ISSUE TITLE
Gauge Card does not show Blue color

### ISSUE THREAD

**Issue by sjikkervisje** [home-assistant/home-assistant.github.io#18772]
### Feedback

Just upgraded to 2021.8.1 and documentation states that is Severity value Green is higher than Min: then it should show the color blue. Instead it shows nothing see image. If I turn of Severity then it shows the whole gauge in the color blue. Please fix this.

![image](https://user-images.githubusercontent.com/1422692/128364961-ee94377a-8850-44d5-8748-57448c2781e7.png)

`type: gauge
max: 40
entity: sensor.sensor_voordeur_temperature
needle: true
severity:
  green: 0
  yellow: 15
  red: 25
min: -10
`

### URL

https://www.home-assistant.io/lovelace/gauge/

### Version

2021.8.0

**Comment by frenck** [comment]
Hi there @sjikkervisje 👋 

Sounds like you want to do a suggestion for a feature or a bug report. Anyways, you have submitted documentation feedback instead.

Please consult this page on where to go: <https://www.home-assistant.io/help>

Thanks 👍 

../Frenck
