### ISSUE TITLE
'Unexpected error' when using the API token provided by CO2 Signal in their email

### ISSUE THREAD

**Issue by kd7cnz** [home-assistant/home-assistant.github.io#18779]
### Feedback

I am getting a 'Unexpected error' when I try to configure the integration for CO2 Signal.
![image](https://user-images.githubusercontent.com/24941834/128396164-d767cc4b-a701-48b0-a04a-9c44781d7918.png)

### URL

https://www.home-assistant.io/integrations/co2signal/

### Version

2021.8.0

**Comment by rainyvalley** [comment]
I am experiencing the same issue, using two different API keys. It will work when I select “us” as the country code but not when I go by home location or manually adding my long/lag and provide the same error. 

Hope this helps,

**Comment by goncalvespedro** [comment]
I'm also having the same error, I have tried this on a clean build and it's working with no issues - so it must be down to my current config (both servers are on the same network). i can not find anything obvious in the logs.

**Comment by frenck** [comment]
Hi there 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to fix an issue.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
