### ISSUE TITLE
This guage would be very useful if it centered in as positive/negative scenario - to monitor charge vs. discharge in any battery or power system.

### ISSUE THREAD

**Issue by wreuvers** [home-assistant/home-assistant.github.io#18780]
### Feedback

In my solar and battery system I have 2x Reclaimed Tesla Model 3 Battery Packs (each 75kWh), 12x Reclaimed Tesla Model S modules (5kWh each for a total of 60kWh) and a bunch of other batteries (Nissan Leaf, etc). Depending on the time of day, the solar and wind production, the batteries are either being charged (receving power, so a negative value in Watts) or discharging power to power the island (producing power, so a positive value in Watts) . If the guage allowed an option to have zero as the mid point in the arc, and then drew left it negative and right if positive, it would be fantastic in all cases where people are using any battery system. Same for an Inverter, it is either taking power in from your panels and charging the battery or using the batteries to power your place. Same for the Grid (not in my case on the island as off grid), as you are either taking power from the grid, or sending back to the grid.

I am more than happy to give devs access to my IslandAssistant as on my island (in the Bahamas) I have setup 96 solar panels wach with microinverters, 1 wind generator, and a bunch of inverters and controllers. I have setup Node Red to minor the different batter states

### URL

https://www.home-assistant.io/lovelace/gauge/

### Version

2021.8.0

### Additional information

![Snap001](https://user-images.githubusercontent.com/80078939/128397358-64492fc8-eb5c-423b-8a22-ea2e84d3ddad.png)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
