### ISSUE TITLE
There is also a way to meter with an ESPCam

### ISSUE THREAD

**Issue by ZillionPrey** [home-assistant/home-assistant.github.io#18781]
### Feedback

I read the Energy page, since I'm already doing this with an ESPCam infront of my energy meter. I thought this would be a viable option to be added on the website.

The project I'm talking about can be found here: https://github.com/jomjol/AI-on-the-edge-device

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.0

**Comment by frenck** [comment]
Sure, it can, it talks over MQTT, so it can provide information.

However, this is considered out of scope for our project as this is third-party software you are asking a feature for.
