### ISSUE TITLE
Message: 'Config flow could not be loaded' when attempting to install 

### ISSUE THREAD

**Issue by colemorgan** [home-assistant/home-assistant.github.io#18788]
### Feedback

Trying to install from https://www.home-assistant.io/integrations/honeywell/ and I get the error message "Config flow could not be loaded"

I've seen that I need to set my external_url in order for this to work, and I've done that with DuckDns. 

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.8.0

**Comment by MVerBerkmoes** [comment]
Same issue here .. "Config flow could not be loaded".

Not sure external DNS is required and I'm connecting via my internal address when receiving the error.  HA does have access to the internet.

**Comment by Rodney18** [comment]
I am having this same issue when trying to install the Honeywell intergration, it just gives me 'Config flow could not be loaded' i tried with the internal url and external url via duckdns and i get the same error both times, i also tried on the android app and windows desktop portal with chrome

**Comment by Rodney18** [comment]
I just updated home assistant to latest version and everything works good now

**Comment by colemorgan** [comment]
Same here, update to the newest version and it will work. Alternatively, you can just add the Honeywell config to your configuration.ymal and it will work without the integration installing. That is how I got this working before I updated. 

Hope this helps!

**Comment by rdfurman** [comment]
Duplicate of https://github.com/home-assistant/core/issues/53981.
