### ISSUE TITLE
More login information needed

### ISSUE THREAD

**Issue by LouisKleiman** [home-assistant/home-assistant.github.io#18786]
### Feedback

I need more information regarding how to set up the Dexcom integration.  I have set up a follower in my Dexcom app, the details in the web page for the integration say "Follow the instruction on screen to complete the set up."  I have tried my user name and password with no success.  I didn't have to enter a password for the follower user, and the integration requires a password, so no joy there.  I would really love to set up this integration, but I need more information regarding which username/password to enter and where to find those entries in the Dexcom set processes.

Thanks.

### URL

https://www.home-assistant.io/integrations/dexcom/

### Version

2021.8.0

**Comment by gagebenne** [comment]
The login information is the same as the user who is logged in to the Dexcom app (the one who is "sharing" their glucose readings), not the user who is viewing the shared glucose readings. I'd recommend two things: per the [warning](https://www.home-assistant.io/integrations/dexcom/#configuration), try changing your password to something with a mix of numbers and letters, or trying different Dexcom Share servers. I just ran an integration test on the underlying library, and there seem to be no issues.

Here's what your Dexcom app should look like:
<img src="https://user-images.githubusercontent.com/22921548/128432095-7adcdb07-457a-4af7-b2a5-4a58987e6bc1.jpeg" alt="Dexcom Share example" height="800x"/>

**Comment by LouisKleiman** [comment]
I got it working!  The knowledge that it was my login helped me track down a password issue.  Sorry I had bad information, but I still think it would be helpful to state whose login information the config is looking for.  Thanks for the thorough response.

**Comment by gagebenne** [comment]
Nice, and yeah, definitely noted.
