### ISSUE TITLE
energy

### ISSUE THREAD

**Issue by veenstrahiem** [home-assistant/home-assistant.github.io#18784]
### Feedback

I cannot add energy sensors myself.
I have some shelly 1PM, and some older sensors that I get values from through node red api calls.
These are nodered.sensors in my home-assistant.\

How to add them in the energy tab

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2021.8.0

### Additional information

EXCELLENT THINGS, I love the new energy dash

**Comment by lein1013** [comment]
Similar issue: energy meter devices do not show up
I propose to change the title to "energy meter devices do not show up for energy consumer configuration"
I have broadlink sp3 power meter plugs. Further I use the integration component to integrate W to Wh  and have template sensors for e.g. a light which I switch on via esp home

It would be helpful to know what properties are needed that a energy meter device is shown there
is device_class: power  also recognized or only energy?

**Comment by klaasnicolaas** [comment]
Hi there @veenstrahiem 👋

It seems like you want to report an issue with an Home Assistant integration, hower, this repository is for documentation feedback.

Please raise an issue in the Home Assistant core issue tracker instead (and check if your question has been asked before):
https://github.com/home-assistant/core/issues

Thanks! 👍

Klaas
