### ISSUE TITLE
Color order in gauge card

### ISSUE THREAD

**Issue by JoSpey36** [home-assistant/home-assistant.github.io#18798]
### Feedback

Just noticed that the order of the colors in the gauge card changes if you don't put the values in numeric order. green 40 - yellow 60 and red 0 puts red left, green middle and yellow right. Would be nice to mention in the code. (other colors would be nice too but that requires development I guess)

### URL

https://www.home-assistant.io/lovelace/gauge/

### Version

2021.8.2

**Comment by frenck** [comment]
The order shouldn't matter in this case, please raise an issue for this case:

<https://github.com/home-assistant/frontend/issues>

../Frenck
