### ISSUE TITLE
Ambee new terms: only 15 days left for free usage for an unpaid membership 

### ISSUE THREAD

**Issue by revdbrink** [home-assistant/home-assistant.github.io#18800]
### Feedback

I just received an email from Ambee that they changed the terms for a free account, which was 100 free requests a day, this will stop working after 15 days (August 21th for me). From then I/you have to pay for all requests.

### URL

https://www.home-assistant.io/integrations/ambee/

### Version

2021.8.2

**Comment by Kertz1954** [comment]
Same here. I received the email on the Aug. 6. 

Platinum score, but at a price !

**Comment by rocketdyke** [comment]
issue is still relevant. integrations documentation needs to be updated to show this.

**Comment by rocketdyke** [comment]
> 

can anyone update the docs?
