### ISSUE TITLE
Tesla: Account with 2 MFA-devices unable to sign in to HA Tesla integration

### ISSUE THREAD

**Issue by raoulteeuwen** [home-assistant/home-assistant.github.io#18803]
### Feedback

My wife and i want to be able to access the Tesla account our model 3 is assigned to. We have connected both our phones for MFA. So both of us can sign in, upon which we get a choice which of the 2 phones we want to use for MFA, after choosing, we can input the MFA code, and have access to the account.

Why 2 MFA devices: so that when we're not in 1 room, we don't need the other person to give us the MFA code when we want to access the Tesla account.

I tried the 'MFA-enabled' version of the Tesla HA integration, but don't succeed to get it working: it keeps saying sign in details where wrong and offers an empty sign in form to try again. I have no problem signing in to tesla.com with either of the MFA-codes/phones.

Could it be, the current Tesla HA integration can't handle 2 MFA devices, so the HA integration tries to communicate with Tesla.com, Tesla.com says "which one of the 2 devices do you want to use MFA", and the HA integration after some time gives up, unable to understand what to do?

### URL

https://www.home-assistant.io/integrations/tesla/

### Version

2021.8.2

**Comment by raoulteeuwen** [comment]
(to test, i have removed 1 of the 2 MFA devices ... when i now sign in to Tesla.com, i don't get the MFA selection screen .... but still can't get the HA integration to work (getting "Invalid authentication" while having no problem to sign in to tesla.com))

**Comment by drnichols** [comment]
I have the same issue. I have three logins with access to my Tesla of which one is MFA enabled and I get the ‘Invalid authentication’ error with both MFA enabled and disabled accounts.

**Comment by FalconUK** [comment]
I have a similar issue, I can't sign in, without MFA, since today's upgrade to core-2021.8.2. I get the message "Invalid authentication". Nothing's changed anywhere else, part from the changes made as part of 2021.8.

**Comment by cyrilst** [comment]
Same here, I have an Invalid auth since 2021.8.2, without MFA.

**Comment by Hellplant** [comment]
Same problem here updated from 2021.7.x to 2021.8.2 to test it and it didn't work. Updated today to 2021.8.3 and no change.
I have tried disabling MFA and it didn't work and enabled it again and I still get invalid authentication.
I don't think it matters to the integration but I have a Model 3 and live in Sweden.

**Comment by alandtse** [comment]
This is not the correct place to report this as it's not a documentation issue. Please close this PR and follow https://github.com/home-assistant/core/issues/54177
