### ISSUE TITLE
Honeywell Total Comfort US

### ISSUE THREAD

**Issue by bkr1969** [home-assistant/home-assistant.github.io#18804]
### Feedback

With the new UI integration, this breaks having two thermostats.  I have two configurations, but the second one never shows my thermostat as an entity.

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.8.2

**Comment by bkr1969** [comment]
I have now tried adding both thermostats to the same area, but I still only ever get one entity.

**Comment by frenck** [comment]
Hi there @bkr1969 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with a Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
