### ISSUE TITLE
Use of net meter, Aeotec energy meter

### ISSUE THREAD

**Issue by patrickgohier** [home-assistant/home-assistant.github.io#18815]
### Feedback

It would be great to support metering devices that have one istead of two separate values for feedback vs consumed power.  The Aeotec Energy Meter (and others) only have a single KWH tag that accumulates up when power is consumed and down when feeding back to the grid.

A possible workaround would be supporting templates, but that doesn't even work at the moment.

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.3

**Comment by lenny76** [comment]
nice feedback. same problem here with Shelly's and sonnen battery meter.
only one value for grid in and out

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
