### ISSUE TITLE
Energy vs Power => they are alike, one is just the other over a certain time.

### ISSUE THREAD

**Issue by kittyscastle** [home-assistant/home-assistant.github.io#18817]
### Feedback

The start of the page says power is not like energy, the link then points out the wiki page:

Electric power is the rate, per unit time, at which electrical energy is transferred by an electric circuit. 

The SI unit of power is the watt, one joule per second.

so the are not alike but one is calculated using the other * a certain time in seconds? I’m not yet sure how to phrase this other than what that power wiki already says:

energy = measurement (points)
power = the integration of energy over time (area under the graph where one unit is W the other t in s)

love the new energy component/integration!

### URL

https://www.home-assistant.io/docs/energy/faq/

### Version

2021.8.3

**Comment by frenck** [comment]
I'm not sure about the suggestion you are trying to make here. The current documentation looks correct to me.

**Comment by kittyscastle** [comment]
Hi Frenck, the biggest part is okay, the first paragraph is rubbing on me. Stating power is not like energy.


It like a bit and kbps or m and m/s, volume and flow are related. You need to know the first one in order to calculate the second, with only the ‘time’ variable coming into the equation. To me that would make them akin and related because of common ground.


But I agree it could be only my feeling. In which case we can close this. Either way, thanks for considering and replying. (And the hard work: much appreciated!)

**Comment by frenck** [comment]
No problem, thanks for thinking along! ❤️ 

I think the current description is good to be honest, so I go and close this one up 👍
