### ISSUE TITLE
Home Assistant - Energy

### ISSUE THREAD

**Issue by sabatpoznan** [home-assistant/home-assistant.github.io#18819]
### Feedback

Does not show up in new energy dashboard

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2021.8.2

**Comment by ZEi20T** [comment]
it shows up for me, but its only selecting 1 total and using it for all 3 number attributes

**Comment by frenck** [comment]
Hi there @sabatpoznan,

It seems like you want to report an issue with integration, however, you have provided documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

../Frenck
