### ISSUE TITLE
Documentation on mqtt_sensor'  last_reset_topic is confusing.

### ISSUE THREAD

**Issue by middelink** [home-assistant/home-assistant.github.io#18822]
### Feedback

The documentation of the mqtt_sensor states for `last_reset_topic`:

> The MQTT topic subscribed to receive timestamps for when an accumulating sensor such as an energy meter was reset. If the sensor never resets, set it to UNIX epoch 0: 1970-01-01T00:00:00+00:00.

This let me to think I need to set the last_reset_**topic** to this timestamp.

However, when I tried that it did not work and when I look at the zigbee2mqtt code it seems to be implemented differently, https://github.com/Koenkk/zigbee2mqtt/blob/70891eec39018303a43349c875ad04d44b3b43cf/lib/extension/homeassistant.js#L461-L466
```javascript
energy: {
                    device_class: 'energy',
                    state_class: 'measurement',
                    last_reset_topic: true,
                    last_reset_value_template: '1970-01-01T00:00:00+00:00',
                },
```

I don't know if `true` is a special value to prevent HA from subscribing to the topic and only look at the template or if something else if going on. At least this special behaviour should be documented, right?

Sooo, I think the mqtt_sensor needs a bit of clarification in respect to last_reset_topic and last_reset_template.

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/#last_reset_topic

### Version

2021.8.3

**Comment by frenck** [comment]
- `last_reset_topic` must be a valid topic, `true` is not a valid MQTT topic.
- Zigbee2MQTT provides its general state topic and a fixed value template, as per specifications, Zigbee devices cannot reset this value.

It works just like all other values, provide the topic & template to extract the value from the topic.
`last_reset` is no different compared to e.g., states.

**Comment by middelink** [comment]
I understand how it/mqtt works. My point is that the documentation is confusing. See first paragraph of this bug.

(That example snippet from zigbee2mqtt was incorrect, https://github.com/Koenkk/zigbee2mqtt/blob/70891eec39018303a43349c875ad04d44b3b43cf/lib/extension/homeassistant.js#L829-L831 replaces the `true` it by the real state_topic; so all is fine there)
