### ISSUE TITLE
Option to hide "min/max" legends in the statistics graph

### ISSUE THREAD

**Issue by Giom-V** [home-assistant/home-assistant.github.io#18825]
### Feedback

I really like the statistics graph but I think the color scheme makes it clear what's the mean, the min and the max so I would love to have an option to continue to display the 3 graphs but not their legends.

### URL

https://www.home-assistant.io/lovelace/statistics-graph/

### Version

2021.8.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
