### ISSUE TITLE
Graph with ) values

### ISSUE THREAD

**Issue by Ace0510** [home-assistant/home-assistant.github.io#18827]
### Feedback

Use Shelly EM to display the energy used. However, the new energy display does not show the values. The graph is correct., but all the values are 0.
![image](https://user-images.githubusercontent.com/34573996/128606905-ebb2d477-d14c-40d6-8ac5-a372052c9238.png)

![image](https://user-images.githubusercontent.com/34573996/128606929-ba4235b9-8c75-4a8b-90b8-6464064c45f5.png)

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.3

### Additional information

![image](https://user-images.githubusercontent.com/34573996/128606950-2e262dbf-2a52-4963-bf81-1d811ef76ff2.png)

**Comment by frenck** [comment]
Hi there @Ace0510 👋 

It seems like you want to report an issue with Home Assistant inner workings, however, you have provided documentation feedback instead.

Please report issues with the Home Assistant Core here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
