### ISSUE TITLE
Issue with statistics when negative values ?

### ISSUE THREAD

**Issue by jjtoard** [home-assistant/home-assistant.github.io#18820]
### Feedback

I think the statistic integration has issues with negative values.

See same date : statistic and raw
![image](https://user-images.githubusercontent.com/24300782/128594498-712353c7-8cfd-450b-90aa-07d692fcc3c1.png)
![image](https://user-images.githubusercontent.com/24300782/128594504-a4fed8c3-1f53-489e-af73-02cfb4596710.png)

### URL

https://www.home-assistant.io/lovelace/statistics-graph/

### Version

2021.8.3

**Comment by frenck** [comment]
Hi there @jjtoard 👋 

Seems like you want to report an issue with Home Assistant, however, you have submitted documentation feedback instead.

Please report issues with Home Assistant Core here:

<https://github.com/home-assistant/core/issues>

And issues with the Home Assistant Frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 


../Frenck
