### ISSUE TITLE
"mode_command_template"  deprecated???

### ISSUE THREAD

**Issue by TNTLarsn** [home-assistant/home-assistant.github.io#18824]
### Feedback

althought config variable`mode_command_template` is in the [docs ](https://www.home-assistant.io/integrations/climate.mqtt/#mode_command_template)
VSCode shows an error:

> Property "mode_command_template" is not allowed

<img width="804" alt="Bildschirmfoto 2021-08-07 um 14 15 30" src="https://user-images.githubusercontent.com/5354495/128599999-91e4dfd2-398d-462c-8fb1-8114a708f21c.png">

as far as I can see, the integration still works though.
 

### URL

https://www.home-assistant.io/integrations/climate.mqtt/

### Version

2021.8.3

**Comment by frenck** [comment]
No, it is not deprecated. Please report this issue with the VSCode extension you are using.
