### ISSUE TITLE
Energy management

### ISSUE THREAD

**Issue by caitotheonlypotato** [home-assistant/home-assistant.github.io#18837]
### Feedback

Hi.  I've been able to successfully set up energy management, however I can't find an elegant and/or accurate way of setting up the integration with the powerwall home battery.  I have some sensors all ready to go and they are recognised by the energy management integration but no matter where I enter them into the configuration, if throws the calculatrions into chaos.  Is there an intention to add in a battery section in future updates?

### URL

https://www.home-assistant.io/docs/energy/

### Version

2021.8.3

### Additional information

![energy integration powerwall 1](https://user-images.githubusercontent.com/57476695/128621168-3841a88e-7a99-4d1e-a064-49907bdf94c5.png)
![energy integration](https://user-images.githubusercontent.com/57476695/128621169-23038053-8dde-447a-a656-c19da3bef606.png)

**Comment by klaasnicolaas** [comment]
Hi there @caitotheonlypotato 👋

It seems like you want to report an issue with an Home Assistant integration, hower, this repository is for documentation feedback. At the moment there is no support for batteries such as a powerwall, but this topic has certainly our attention.

Please raise an issue in the Home Assistant core issue tracker instead (and check if your question has been asked before):
https://github.com/home-assistant/core/issues

Thanks! 👍

Klaas
