### ISSUE TITLE
Please add field 'name' to example configuration.yaml

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [home-assistant/home-assistant.github.io#18831]
### Feedback

Maybe it’s obvious to the most people, but I wondered 30mins why my discord notification wasn’t working. It helped defining a name "discord" for the notify service. Maybe you can ad this in the documentation.

cheers

### URL

https://www.home-assistant.io/integrations/discord/

### Version

2021.8.3

**Comment by ludeeus** [comment]
This is already documented <https://www.home-assistant.io/integrations/discord/#name>
