### ISSUE TITLE
QNAP Update Guidance Useless

### ISSUE THREAD

**Issue by BlueMoon23** [home-assistant/home-assistant.github.io#18843]
### Feedback

Will someone please provide a structured way to update the QNAP version. I had a good set up, decided to update and have now lost everything.

### URL

https://www.home-assistant.io/installation/alternative/

### Version

2021.8.3

**Comment by frenck** [comment]
How come you'd lose everything? The documentation provides instructions on adding a separate mounted in configuration folder. Updating a Docker image should not be able to influence or cause that.

Could you provide a reproduction or provide alternative instructions that avoid the issue you had?

**Comment by BlueMoon23** [comment]
Hi Franck,

I had some significant problems when updating yesterday, which I resolved
with some support from the forum. In fairness, the QNAP instructions are
not wrong, they are just not helpful enough. The problem is that there is
very little help with Container Station, and for some reason when you
search for home assistant, the default return is a very old version, which
results in most of the integrations, devices and entities going
disappearing. I suspect this is a Container Station problem and not a HA
problem. I have re-written the instructions as follows, as they worked for
me.

*QNAP NAS*

As QNAP within QTS now supports Docker (with a neat UI), you can simply
install Home Assistant using Docker without the need for command-line. For
details about the package (including compatibility-information, if your NAS
is supported), see
https://www.qnap.com/solution/container_station/en/index.php

The steps would be:

   - Install “Container Station” package on your Qnap NAS
   - Launch Container Station and move to the “Create”-section (You may
   have to expand the Management area on the left-hand side)
   - Search image “home assistant”, and then make sure you have selected Docker
   Hub, select “homeassisitant/home-assistant” and click on “Install”
   - Choose “latest” version and click next
   - Choose a container-name you want (e.g., “homeassistant”)
   - Click on “Advanced Settings”
   - Within “Shared Folders” click on “Volume from host” > “Add” and choose
   either an existing folder or add a new folder. The “mount point has to be
   /config, so that Home Assistant will use it for the configuration and
   logs. Note: If you are updating home assistant, within “Volume from
   host” enter the location of the config files, e.g. the folder where the
   configuration.yaml file resides, this may be a folder such as “hass-config”
   - Within “Network” and select Network Mode to “Host”
   - To ensure that Home Assistant displays the correct timezone go to the
   “Environment” tab and click the plus sign then add variable = TZ & value
   = Europe/London choosing your correct timezone
   <http://en.wikipedia.org/wiki/List_of_tz_database_time_zones>. Note: If
   you are updating you can skip this step.
   - Click on “Create”
   - Wait for some time until your NAS has created the container
   - Your Home Assistant within Docker should now run and will serve the
   web interface from port 8123 on your Docker host (this will be your Qnap
   NAS IP address - for example http://192.xxx.xxx.xxx:8123)

Remark: To update your Home Assistant on your Docker within Qnap NAS, you
just remove container and image and do steps again (Don’t remove “config”
folder). To remove the container, first stop it and then select remove, to
remove the image, select “Images” from the left-hand side menu, identify
the image you want to remove (e.g. “home-assistant/home assistant”), select
the image and then click “remove”.
