### ISSUE TITLE
Add whether and if, how, this integration can use the new Energy dashboard

### ISSUE THREAD

**Issue by raoulteeuwen** [home-assistant/home-assistant.github.io#18842]
### Feedback

I'm happily using this integration. I hoped i could use it as input for the new Energy dashboard. But when trying to config that, the DSMR sensors for consumption and production are not shown in the drop downs of the Energy dashboard config UI.

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2021.8.3

### Additional information

(want to express thanks for all the work on HA & integrations!!!)

**Comment by RobBie1221** [comment]
It should work, I have them on my dashboard. Are you sure you are using the official integration?

**Comment by klaasnicolaas** [comment]
Hi there @raoulteeuwen  👋

It seems like you want to report an issue with an Home Assistant integration, hower, this repository is for documentation feedback.

Please raise an issue in the Home Assistant core issue tracker instead:
https://github.com/home-assistant/core/issues

Thanks! 👍

Klaas

**Comment by raoulteeuwen** [comment]
Hi @klaasnicolaas . Although the integration doesn't seem to work for me as expected, my 'issue' was that it would be nice that the doc would reflect explicitly whether the integration should already work with the Energy dash, and if so, how.

**Comment by klaasnicolaas** [comment]
I don't get that from your earlier post, but I'll bring it up internally to see if we can do something about it 😉 

regarding DSMR integration: support has already been made for this and should therefore work fine with the energy dashboard. For further help to get it working in your case, I refer you to the c[ommunity forum](https://community.home-assistant.io) or Discord 😉

**Comment by raoulteeuwen** [comment]
Sorry for not being clear. Will try the forum: tried Discord, and maybe i don't understand how it works, but after posting my question (https://discord.com/channels/330944238910963714/872496321574088765/873223147858583623), i never got a reply, and i assume once new messages get posted in the same thread, once chances on getting a reply decrease fast...
