### ISSUE TITLE
add instructions for where to find the network key

### ISSUE THREAD

**Issue by phillipredshirt** [home-assistant/home-assistant.github.io#18841]
### Feedback

It is mentioned several times that the network key needs to be copied down, but there is no explanation of where you can find it so you can copy it.

This

"Write down/copy your Z-Wave network key somewhere, you are going to need it later."

Should be something like this

"Write down/copy your Z-Wave network key somewhere, you are going to need it later. It can be found in this configuration file with the label XX"

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2021.8.3

**Comment by frenck** [comment]
That depends on your setup. This is only state in the migration part, for which you need to network key from your old setup (whatever that might have been, there are dozens of solutions out there). You have configured the network key and probably know best where you've put it.

**Comment by phillipredshirt** [comment]
It looks like the answer may be, there is no security key. Adding a security key is optional for the ZWave integration. That's why I can't find it and don't remember setting it.

I guess it's not a good time to upgrade to Zwave-JS

**Comment by frenck** [comment]
> I guess it's not a good time to upgrade to Zwave-JS

It is actually. All other integrations are considered unmaintained or deprecated.

I'm closing the issue on this end, as there is no way to universally describe on how to obtains your Z-Wave security key from other setups.
