### ISSUE TITLE
Statistics graph info popup shows values twice on last entry in line and bar mode

### ISSUE THREAD

**Issue by Kertz1954** [home-assistant/home-assistant.github.io#18846]
### Feedback

This only happens on last entry in line and bar mode.

![stats-popup-screen](https://user-images.githubusercontent.com/67558244/128638912-4b1ab2f5-10bc-4a5d-bb10-cbc80fd32883.png)

### URL

https://www.home-assistant.io/lovelace/statistics-graph/

### Version

2021.8.3

**Comment by frenck** [comment]
Hi there @Kertz1954 👋 

It seems like you want to report an issue with the Home Assistant frontend, however, you have submitted documentation feedback instead.

Please report issues with the Home Assistant frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks! 👍 

../Frenck
