### ISSUE TITLE
Can't Load Integration on New HA

### ISSUE THREAD

**Issue by kstempel** [home-assistant/home-assistant.github.io#18854]
### Feedback

When I updated the HA System to 2021.8.4 my simplisafe integration wouldn't work. I deleted it and then tried to re-add it. I put in the User name, password, and keypad code. I either get "Unexpected Error" or "Aborted".  

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2021.8.3

**Comment by bachya** [comment]
Please post issues in the correct repo (this is the docs repo). Also, please make sure you provide _all_ of the requested information in the issue template.
