### ISSUE TITLE
Missing information about the new energy feature of home assistant 

### ISSUE THREAD

**Issue by seb-5x** [home-assistant/home-assistant.github.io#18859]
### Feedback

Hello
I am missing information about the new energy function:

https://www.home-assistant.io/blog/2021/08/04/home-energy-management/

Not clear for me how to use the atome data with this new feature.
Thanks

### URL

https://www.home-assistant.io/integrations/atome/

### Version

2021.8.3

**Comment by frenck** [comment]
This is not a documentation issue for atome, as shown in the UI when trying to add it as an energy source. It links too:

<https://www.home-assistant.io/more-info/statistics/>

Please consult that page for more information and how to report such issues.

Thanks 👍

**Comment by seb-5x** [comment]
Many  thanks for your time

Le lun. 9 août 2021 à 10:44, Franck Nijhof ***@***.***> a
écrit :
