### ISSUE TITLE
Describe which data the solar integration should deliver

### ISSUE THREAD

**Issue by freemann** [home-assistant/home-assistant.github.io#18868]
### Feedback

For my Solar Inverter there's no integration, only a Linux commandline tool.
This tool can deliver different data sets such as cum. production kWh per day/month/year/overall and actual power in Watts.

Tried different values for the sensor I use to add to the Energy settings, but in no way I get solar data insights in the Energy Dashboard.

### URL

https://www.home-assistant.io/docs/energy/solar-panels/

### Version

no idea

**Comment by frenck** [comment]
More information can be found here: <https://www.home-assistant.io/more-info/statistics/> (which is listen in the UI).

Additionally, more internal details can be found on the developer blog about it, here:

<https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes>

(and of course in the dev docs)

**Comment by freemann** [comment]
Read that, but still unclear if the Solar Sensor should be;
- Current Power: 1,153kW
- Daily Production: 13,542kWh
- Overall Production: 34123kWh

Will try the community :)
