### ISSUE TITLE
Connection issue when turning off Surveilance Station

### ISSUE THREAD

**Issue by titiviking** [home-assistant/home-assistant.github.io#18860]
### Feedback

Synology DSM integration worked fien for a while, but has some issues now.

I started using Surveillance Station, but changed my mind rapidly because of the limited amount of camera's that can be configured for free (max 2).
Hence I stopped using Surveillance Station.

However the Synology integration onboarded the cameras and the home mode from Surveillance Station.
Now that it is turned down, I have no way to remove those entities and the integration returns connection issues.
I've attempted disabling the entities in HA, but no luck yet. 

How can I fully delete those entities to recover the other sensors?

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2021.8.4

**Comment by titiviking** [comment]
Errors:

`2021-08-09 11:27:19 DEBUG (MainThread) [homeassistant.components.synology_dsm] Unable to connect to DSM '14A0MIN121504' during setup: {'api': None, 'code': -1, 'reason': 'Unknown', 'details': 'ConnectionError = <urllib3.connection.HTTPSConnection object at 0xaae1eb68>: Failed to establish a new connection: [Errno 111] Connection refused'}
2021-08-09 11:27:22 DEBUG (MainThread) [homeassistant.components.synology_dsm] Unable to connect to DSM '14A0MIN121504' during setup: {'api': None, 'code': -1, 'reason': 'Unknown', 'details': 'ConnectionError = <urllib3.connection.HTTPSConnection object at 0xa741c808>: Failed to establish a new connection: [Errno 111] Connection refused'}`


There is no way to reload the integration, or to force ré-login either...

**Comment by frenck** [comment]
Hi there @titiviking 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

../Frenck

**Comment by titiviking** [comment]
Incorrect config on my end... Had to change port for security reasons, but HA does not allow for GUI based config changes..

Applied changes in core.config_entries, which resolved the issues.

Still it would be nice to be able to delete camera's that are no longer exposed by Surveillance Station.
