### ISSUE TITLE
Home Energy Meter Gen5 (ZW095), Vera and long-term-statistics

### ISSUE THREAD

**Issue by gniknalu** [home-assistant/home-assistant.github.io#18863]
### Feedback

We use the Vera integration to communicate with HA and interface with our Z-Wave/Zigbee devices (~90 devices). Within our infrastructure, we have used a Home Energy Meter Gen5 (ZW095) for many years. However it does not show up with the new energy dashboard. (I've been using it for years and it has a lot of data logged in HA)  According to the configuration, it directs me to open an issue for long term statistics using this:

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

### URL

https://www.home-assistant.io/integrations/vera/

### Version

2021.8.4

### Additional information

![20210809_Home_Energy_using_vera](https://user-images.githubusercontent.com/3652809/128714126-3198d73d-875e-4bb0-ba8c-6dd23cc42b95.jpg)

**Comment by frenck** [comment]
Hi there @gniknalu 👋 

It seems like you want to report an issue with the Home Assistant Vera integration, however, you have submitted documentation feedback. It is impossible to add documentation that fixes such a thing 😉 

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by gniknalu** [comment]
> Hi there @gniknalu 👋
> 
> It seems like you want to report an issue with the Home Assistant Vera integration, however, you have submitted documentation feedback. It is impossible to add documentation that fixes such a thing 😉
> 
> Please report issues with Home Assistant integrations here:
> 
> https://github.com/home-assistant/core/issues
> 
> Thanks 👍
> 
> ../Frenck

I was just clicking the link as requested in the documentation. . . . thx
