### ISSUE TITLE
Missing unit of max_age

### ISSUE THREAD

**Issue by kuuf1986** [home-assistant/home-assistant.github.io#18876]
### Feedback

I'm missing the unit of max_age. is it in seconds?

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2021.8.5

**Comment by frenck** [comment]
It accepts a time unit:

![image](https://user-images.githubusercontent.com/195327/134903797-0acc32a3-d3c2-4b04-93d1-29e82c943196.png)


This can be the number things, like just a number for seconds, but also a time format (e.g., `00:01:10`) and even a dictionary like `{ minutes: 1, seconds: 10 }"
