### ISSUE TITLE
Development break with ruby 2.4

### ISSUE THREAD

**Issue by adrianlzt** [home-assistant/home-assistant.github.io#1887]
Gem yajl-ruby should be set to version 1.3.0 to [be able to compile](https://github.com/brianmario/yajl-ruby/pull/165) with ruby 2.4.

Jekyll gives a warning:
```
/usr/lib/ruby/gems/2.4.0/gems/jekyll-3.2.1/lib/jekyll/hooks.rb:57: warning: constant ::Fixnum is deprecated
```

And maybe the docs should change:
``rake preview``by ``bundle exec rake preview`` and ``rake generate`` with ``bundle exec rake generate`` to solve this error:
```
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 10.5.0. Prepending `bundle exec` to your command may solve this.
```

**Comment by balloob** [comment]
Pull request welcome 👍

**Comment by fabaff** [comment]
#2644 was merged and should fix this issue as well.
