### ISSUE TITLE
Expected data source not listed

### ISSUE THREAD

**Issue by JBakers** [home-assistant/home-assistant.github.io#18877]
### Feedback

You’re configuring a statistic but you couldn’t find your source in the dropdown? That’s caused by a bug in the integration providing the entity. Integrations need to configure their entities correctly so Home Assistant knows that we need to track statistics for it and how.

Open an issue with the author of the integration and link them to

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

### URL

https://www.home-assistant.io/integrations/plugwise/

### Version

2021.8.5

**Comment by frenck** [comment]
Hi there @JBakers 👋 

It seems like you want to request support on long-term statistics, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to make that happen 😉 

Please open an issue here instead:

<https://github.com/home-assistant/cores/issues>

Also, please make sure there isn't an issue open for it already, before opening a new one.

Thanks 👍 

../Frenck

**Comment by bouwew** [comment]
@JBakers please see Core issue https://github.com/home-assistant/core/issues/53959

**Comment by JBakers** [comment]
Thank you.
