### ISSUE TITLE
Cannot find "supported MQTT components"

### ISSUE THREAD

**Issue by HankB** [home-assistant/home-assistant.github.io#18870]
### Feedback

On https://www.home-assistant.io/docs/mqtt/discovery/
Instructions indicate the second portion of the topic is `<component>`  and indicates that this should be " supported MQTT components". These are not listed on this page and searching the documents for that phrase only lists this page. It would be really helpful to link to " supported MQTT components." Searching "binary_sensor" doesn't find any useful information.
Thanks!

### URL

https://www.home-assistant.io/docs/mqtt/discovery/

### Version

2021.8.4

**Comment by frenck** [comment]
They are all listed at the top of the page.
