### ISSUE TITLE
Broken Integration - DTE Energy Bridge

### ISSUE THREAD

**Issue by reslip1** [home-assistant/home-assistant.github.io#18881]
### Feedback

This integration does not appear to work with the DTE energy bridge. I get unable to connect with both version 1 and version 2. The only way I've managed to get this to work is with the MQTT integration. 

### URL

https://www.home-assistant.io/integrations/dte_energy_bridge/

### Version

2021.8.5

**Comment by frenck** [comment]
Hi there @reslip1 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. If you want to report an issue with an integration, please do so here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
