### ISSUE TITLE
New energy interface not showing Solaredge all data 

### ISSUE THREAD

**Issue by sirihewa** [home-assistant/home-assistant.github.io#18886]
### Feedback

I have Solaredge inverter data working on all areas but on new energy integration, i could only see one entity which is how much energy it produce.. what happened to all other data on that inverter..

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2021.8.5

### Additional information

I have Solaredge inverter data working on all areas but can only see one entity under energy panel, why?

**Comment by frenck** [comment]
duplicate of https://github.com/home-assistant/core/issues/54017
