### ISSUE TITLE
Failing to connect

### ISSUE THREAD

**Issue by n9thcircle** [home-assistant/home-assistant.github.io#18895]
### Feedback

Verified the login works via the website yet the integration in home assistant keeps returning failed to connect.  I went as far as copy pasting from notepad the user and password to insure I was not mistyping.

### URL

https://www.home-assistant.io/integrations/smart_meter_texas/

### Version

2021.8.6

**Comment by grahamwetzler** [comment]
This issue should be fixed in this PR https://github.com/home-assistant/core/pull/54493

**Comment by frenck** [comment]
Hi there @n9thcircle 👋 

Seems like you want to report an issue with an Home Asistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
