### ISSUE TITLE
Statistic not working

### ISSUE THREAD

**Issue by Chaosflori25** [home-assistant/home-assistant.github.io#18892]
### Feedback

I tried adding the Forecast to my Integrations and the energy panel, but it keeps saying that no fitting statistics were found. I tried reconfiguring the integration many times and tried the Update from 2021.8.1 to 2021.8.6 but it didn't fix my problem. Did I configure something wrong?

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.8.6

### Additional information

I'm running Hassio on a Raspberry Pi 3B with core version 2021.8.6.

**Comment by frenck** [comment]
Thank you for reaching out. We use this tracker for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
