### ISSUE TITLE
Unable to login to Growatt server

### ISSUE THREAD

**Issue by JBoyKey** [home-assistant/home-assistant.github.io#18890]
### Feedback

Unable to login to Growatt server - While trying to install Growatt integrations, login fails on all 3 servers??
Using same credentials as logging into server at home.

### URL

https://my.home-assistant.io/redirect/config_flow_start/?domain=growatt_server

### Version

2021.8.6

**Comment by frenck** [comment]
Hi there @JBoyKey 👋 

I'm not sure if you are trying to report a bug, or seeking support. Anyways, you have submitted documentation feedback, which would not help you in either case.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

In case you want to report a bug with an Home Assistant integration, please create an issue in the issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
