### ISSUE TITLE
Pi4 8gb Current image is "too old" for hardware

### ISSUE THREAD

**Issue by WhiskyRidge** [home-assistant/home-assistant.github.io#18898]
### Feedback

The current image of home Assistant, 20200606, will not boot on a Pi4 8gb. It says this board requires newer software. Is there another link that I am unaware of that has a newer updated image for Home Assistant?

### URL

https://www.home-assistant.io/faq/rpi4_8gb/

### Version

2021.8.6

**Comment by frenck** [comment]
This version runs on on the Pi with 8Gb:

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system

**Comment by WhiskyRidge** [comment]
Thanks for the quick response. I tried that URL using balena etcher and it fails everytime. Balena etcher says the source is corrupted and cannot flash image.

**Comment by WhiskyRidge** [comment]
It worked when i imaged it on a windows 7 pc. Both of my windows 10 pc's wouldn't complete the imaging. This must be a bug with some new windows update and balena etcher.

**Comment by frenck** [comment]
You could try the Raspberry Pi Imager: <https://www.raspberrypi.org/software/>

This one has support to install Home Assistant built-in as well.
