### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by barkeeper** [home-assistant/home-assistant.github.io#18891]
### Feedback

hi there, first of all:  thanks for this amazing addon, I love it! 
Second of all, I'm not sure if it has anything to do with it, but I have my system setup in English, the date format for the container pickups is setup like this:  2021-08-18

Would it be possible to either turn it around, so it's in "European" format, or maybe even better have a countdown for the amount of days left, or both? 

Thanks in advance for looking at this.

JJ

### URL

https://www.home-assistant.io/integrations/twentemilieu/

### Version

2021.8.6

**Comment by frenck** [comment]
This is not documentation feedback, but a support question, so you are a bit in the wrong place 😉 

But no, the format is fixed. Home Assistant does not have the possibility to provide localized date formats.

../Frenck
