### ISSUE TITLE
Multiple thermostat config issue - honeywell

### ISSUE THREAD

**Issue by Gigabitkhan** [home-assistant/home-assistant.github.io#18902]
### Feedback

Cannot seem to locate additional data lid if two thermostats are available attached to the Honeywell account. Would be helpful on config.

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.8.6

**Comment by Ibycus314** [comment]
Same issue. Only first thermostat on account is loading….

**Comment by rdfurman** [comment]
Dupe of https://github.com/home-assistant/core/issues/53981

**Comment by kossimazaki** [comment]
Only first thermostat on account is visible after update to core-2021.8.6. I'm found this error:
ERROR (MainThread) [homeassistant.components.climate] Platform honeywell does not generate unique IDs. ID 00:d1:2d:c4:c8:2e already exists - ignoring climate.1livingroom

**Comment by frenck** [comment]
Closing this as a duplicate, additionally, this is submitted as documentation feedback, not as an integration issue.
