### ISSUE TITLE
Forecast using solar irradiation sensor

### ISSUE THREAD

**Issue by Ace0510** [home-assistant/home-assistant.github.io#18900]
### Feedback

Some of the weather stations like Ambient Weather Station have a radiation sensor that reports actual irradiation in W/m2 every 5 minutes so the sum of all data points divided by 12 is the kWh/m2. It will be really nice to use the actual data so you can calculate what size system fits your needs.

my current sensor is:  sensor.el_encanto_solar_rad

![image](https://user-images.githubusercontent.com/34573996/129114802-857433d8-d2ff-4224-8bdd-4d17dc4d993a.png)

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
