### ISSUE TITLE
Energy should have an energy integration documentation page

### ISSUE THREAD

**Issue by Petro31** [home-assistant/home-assistant.github.io#18905]
### Feedback

I've ran into support issues multiple times now on all platforms: Reddit, facebook, discord, and the forums.  The theme is common, people search for the energy integration to find nothing.  These people don't have default_config.  They do not see it on the main sidebar.  If we were to compare this to automation or scripts, both have integrations.

The proposal is to have an energy integration and mention that energy `energy:` is the full configuration.

### URL

https://www.home-assistant.io/docs/energy/

### Version

2021.8.6

**Comment by klaasnicolaas** [comment]
Related to this? https://github.com/home-assistant/home-assistant.io/pull/18746

**Comment by Petro31** [comment]
> Related to this? #18746

Yep, seems like it is.
