### ISSUE TITLE
Parameters for input_type not correct?

### ISSUE THREAD

**Issue by cvgs** [home-assistant/home-assistant.github.io#18908]
### Feedback

Apparently there have been changes to the input_type values since the modbus overhaul. The documentation states "discrete_input" and "coil", while HA itself says in its logs:
"Invalid config for [modbus]: value must be one of ['holding', 'input']"

So please update the documentation to state the new values. Also, the default value now is apparently "holding", as i have to explicitly specify "input" for my values now.

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.8.6

**Comment by cvgs** [comment]
Clarifiation: am trying to update my modbus "sensors:" to the new format, and they did not work before i explicitly added "input_type: input".  I am using modbus to collect a lot of data points from my heatpump into HA.
The parameter is only listed in the "binary_sensors" paragraph, so perhaps the values are different for those. But then they probably still should be listed in the common configuration section.

**Comment by janiversen** [comment]
Seems we have a paragraph fallen out from the struct section.

input_type can have the following values:
coil, discrete_input (binary_sensor and switch)
holding, input (all other entities)

**Comment by janiversen** [comment]
Now I wanted to solve this issue and I checked https://www.home-assistant.io/integrations/modbus/#configuring-platform-sensor

The sensor section contains:
‘’’
input_type string (optional)
Modbus register type (holding, input), default holding.
‘’’

So I am not sure what the issue is?

**Comment by cvgs** [comment]
Hmm, apparently i totally overlooked the specific sensor section and got confused while trying to convert my old config. It seems everything is correctly listed in that section. So sorry to waste your time…

Just one little thing that might have helped my in finding that section easier: On the bottom of the page, there is the section "Building on top of modbus", and the specific sub-modules for modbus are listed there. But clicking on "Modbus Sensor" just gets me to the top of the modbus page again (the link is "https://www.home-assistant.io/integrations/sensor.modbus/").
The link you wrote in your previous comment is "https://www.home-assistant.io/integrations/modbus/#configuring-platform-sensor", which is exactly what i needed. It would be nice if those five links at the bottom would work the same way as your anchored link.

Thanks again for all your hard work, i really appreciate HA and its community…
