### ISSUE TITLE
OpenUV clarity needed

### ISSUE THREAD

**Issue by ZuluWhiskey** [home-assistant/home-assistant.github.io#18910]
### Feedback

The **Sensors** section mentions `Protection Window` with the value being `‘On’ when protection window is needed` but it's not really clear exactly what this means. I wanted to add more context and I have tried to look on the OpenUV website which has [this page](https://www.openuv.io/protection). It mentions "Daily Protection Time" and their documentation says:

_Protection time is a time interval when the estimated UV Index stay over the provided 'from' and 'to' values. If no such interval found the null datetimes will be returned._

If this is the correct aspect of the API/tool - What are the 'from' and 'to' values that HA has set? The default is 3.5 so is it safe to assume that those values are used if users of the integration cannot define them themselves?

### URL

https://www.home-assistant.io/integrations/openuv/

### Version

2021.8.6

**Comment by bachya** [comment]
@ZuluWhiskey Correct: the integration uses the default of `3.5` for both values. So, two questions:

1. Does that answer your question?
2. Knowing what you know, would it be beneficial to allow users to configure those values?

**Comment by ZuluWhiskey** [comment]
> @ZuluWhiskey Correct: the integration uses the default of `3.5` for both values. So, two questions:
> 
> 
> 
> 1. Does that answer your question?
> 
> 2. Knowing what you know, would it be beneficial to allow users to configure those values?

1. It definitely does, thank you very much!
2. I think that'd be great! I honestly did try to take a look at how to do a PR to add the functionality but I have no idea where to start 😔 I use the integration to notify me when I'll need to put sunscreen on my daughter (or if the UV will be high in the day meaning I'll need to). I currently use the value of `current_uv_index` as a trigger, if it's over 5 then it notifies me. The protection window would be useful to set my own values so that I can notify when it turns on / off. Although it's also possible with my current method the timings etc. of the protection window would be ace 👍

**Comment by bachya** [comment]
@ZuluWhiskey Great! I'll work on both a functionality PR and a docs PR.
