### ISSUE TITLE
why i can't take a picture by camera.snapshot service?

### ISSUE THREAD

**Issue by s1230988** [home-assistant/home-assistant.github.io#18929]
### Feedback

I use camera.snapshot service to take a picture, but i got a picture with 0 size.
it's very strange. Sometimes I can success sometimes I can't. I don't why reason cause it.

![image](https://user-images.githubusercontent.com/85861172/129430685-64ea156a-4bd1-4cf8-9872-c4e3b146570e.png)
![image](https://user-images.githubusercontent.com/85861172/129430732-a2ead337-d1c0-4818-b68a-cd758b853252.png)

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.8.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
