### ISSUE TITLE
New Energy feature : integration of French Linky energy meter

### ISSUE THREAD

**Issue by virtorgan** [home-assistant/home-assistant.github.io#18920]
### Feedback

In France a lot of people have an Enedis Linky energy meter from Enedis. data can be sent to Home-assistant by using espHome "teleinfo" component. https://esphome.io/components/sensor/teleinfo.html
it just need a small hardware (optocoupler & couple of resistances) between meter and ESP32.  more information here : http://hallard.me/pitinfov12/ (note: I just bought this device I have no link to the creator)

I hope it will help some of French meter owners.

P.S: you did not mention the famous PZEM-004T https://esphome.io/components/sensor/pzemac.html

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.6

### Additional information

Maybe add link to a new page with different meters based on Country of use.
i.e. connection to providers meter + connection to generic devices (CT clamps etc...)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
