### ISSUE TITLE
Twitch documentation out of date

### ISSUE THREAD

**Issue by PenguinRage** [home-assistant/home-assistant.github.io#18932]
### Feedback

When using the suggested approach with this documentation. This results in getting an error message in the logs telling me that the token or client id is incorrect.

### URL

https://www.home-assistant.io/integrations/twitch/

### Version

2021.8.6

**Comment by JuniorGamingTime** [comment]
Any updates on this? having the same issue.

**Comment by VicariousVeteran** [comment]
Same here. 
I first set it up about a month ago and it actually worked, then after a few hours it stopped working and every time i restart home assistant i get a log that says: "Client ID or OAuth token is not valid".

**Comment by JuniorGamingTime** [comment]
Mine has been working for 2 years straight and last week it just died

**Comment by frenck** [comment]
Isn't this an integration issue and not a documentation feedback suggestion?

**Comment by JuniorGamingTime** [comment]
It's basically both the sensor does not work, and the document seems to be out dated

**Comment by frenck** [comment]
What is outdated? As far as I understand is that the integration won't work anymore?
Please provide some information on what is wrong (e.g., error one experience) or what needs to be changed.

**Comment by JuniorGamingTime** [comment]
So double checking the documentation seems good, the integration might be out of date.  The error I get is 
"Client ID or OAuth token is not valid" in the HA logs

**Comment by frenck** [comment]
Found an upstream issue in the core: <https://github.com/home-assistant/core/issues/54385>

This is not a documentation issue, therefore: Closing it on this end.
