### ISSUE TITLE
Alexa's gotta dim

### ISSUE THREAD

**Issue by dgarozzo** [home-assistant/home-assistant.github.io#18938]
### Feedback

After spending hours trying to get emulated_hue to expose my input_booleans, I finally found the hidden option that fixed it. In order to get Alexa to be able to see input_boolean, you can't allow emulated_hue to claim that a light it simply "on/off"; Alexa only understands dimmable lights. Use this currently undocumented flag to make emulated_hue work with your Alexa:

emulated_hue:
  lights_all_dimable: true

### URL

https://www.home-assistant.io/integrations/emulated_hue/

### Version

2021.8.6

**Comment by frenck** [comment]
This is not a correct workaround. `lights_all_dimable` is here for backward compatible reasons, but should not be used in general (and thus not documented).
