### ISSUE TITLE
Installation for x86 systems incorrectly refers to "Installation media" vs target "boot media" 

### ISSUE THREAD

**Issue by hiveai** [home-assistant/home-assistant.github.io#18933]
### Feedback

The installation instructions for x86 systems are very confusing because they incorrectly describe creating "Installation media" when, in fact, there is no Home Assistant installer, and you actually need to write the HAOS disk image to the  "boot media" 
The disk image does not create an installer that can be used to install Home Assistant.  It is a Home Assistant Operating System disk image that need to be written directly to the media that the x86 machine will boot from when running Home Assistant. 

### URL

https://www.home-assistant.io/installation/generic-x86-64

### Version

Not specified on the page

**Comment by frenck** [comment]
You don't have to open issues/feedback if you are going to fix it. Just create a PR directly in those cases.
