### ISSUE TITLE
2 sensor values not working

### ISSUE THREAD

**Issue by Yop1403** [home-assistant/home-assistant.github.io#18939]
### Feedback

Hi. Just installed the COVID integration. Whatever country I choose - I'm getting an 'unknown' info for both the current # of cases and # recovered sensor values. Any ideas? (in case you're wondering: my localization of HASS is in German)
![COVID](https://user-images.githubusercontent.com/7037677/129464101-d0cc989c-739f-4e56-80d3-87a565f16880.png)

### URL

https://www.home-assistant.io/integrations/coronavirus/

### Version

2021.8.6

**Comment by frenck** [comment]
Hi there @Yop1403 👋 

It seems like you want to report an issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can write to fix such an issue.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>


Thanks 👍 

../Frenck

**Comment by Yop1403** [comment]
Sorry Frenck and thanks. You can most likely tell I’m a newbie with HA :-)
BR
Guenther

Am 16.08.2021, 22:17:49 schrieb Franck Nijhof ***@***.***>:
