### ISSUE TITLE
scan_interval not documented

### ISSUE THREAD

**Issue by nsmits** [home-assistant/home-assistant.github.io#18946]
### Feedback

'scan_interval' is visible in the example but not documented in 'configuration variables'

### URL

https://www.home-assistant.io/integrations/sensor.rest/

### Version

2021.8.7

**Comment by ludeeus** [comment]
The reason for that, is that it applies to all entity platforms and is globally documented instead <https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval>
