### ISSUE TITLE
Missing info on SurePet integration

### ISSUE THREAD

**Issue by jimmyeao** [home-assistant/home-assistant.github.io#18947]
### Feedback

Doc states "Flap ID to change - see below for instructions on finding device IDs" but there are no instructions for finding the flap ID

### URL

https://www.home-assistant.io/integrations/surepetcare/

### Version

2021.8.7

**Comment by atxbyea** [comment]
The old docs stated the following, does that still work @jimmyeao 

`For now, please use the [sp_cli.py](https://github.com/rcastberg/sure_petcare/blob/master/sp_cli.py) from [@rcastberg](https://github.com/rcastberg) to fetch the IDs from the Sure Petcare API. With default setting, the IDs will be written as JSON to `~/.surepet.cache`.`
