### ISSUE TITLE
modbus

### ISSUE THREAD

**Issue by hesselb** [home-assistant/home-assistant.github.io#18940]
### Feedback

Logger: homeassistant.config
Source: config.py:445
First occurred: 13 augustus 2021 20:10:57 (1 occurrences)
Last logged: 13 augustus 2021 20:10:57

Invalid config for [sensor]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 23). Please check the docs at https://www.home-assistant.io/integrations/sensor

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
###http:
### ssl_key: /ssl/privkey.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
###########################################################################################################################
#############################################################################################################################
modbus:                             # Abilita il componente Modbus    Schakel de Modbus-component in
  type: tcp                         # Dichiara Modbus su protocollo TCP    Verklaart Modbus via TCP-protocol
  host: 192.168.1.202            # Ip del Gateway PowerTag link A9XMWD20 assegnato dal router
  port: 502                         # Porta del Gateway PowerTag link A9XMWD20

sensor:
    scan_interval: 10               # Periodo di scansione in secondi dei registri Modbus
    registers:
      - name: ptActueel totaal       #  Naam van de energiesensor
        slave: 150                    # Indirizzo Modbus assegnato dal PowerTag link A9XMWD20
        address: 2999              # Inizio lettura registro
        input_type: holding      # Tipo di registro
        unit_of_measurement: A      # Tipo dell' unità di misura
        count: 2                    # Numero registri da leggere
        precision: 1                # Numero dei decimali dopo la virgola
        data_type: float            # Tipo di dati da interpretare
        #######

        ####################################################################################

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2021.8.6

**Comment by hesselb** [comment]
core-2021.8.6
Nieuwste versie
core-2021.8.6
Supervisor
Versie
supervisor-2021.06.8
Nieuwste versie
supervisor-2021.06.8

**Comment by janiversen** [comment]
Did you try the to solve the error message:
nvalid config for [sensor]: required key not provided @ data['platform']. Got None 
by adding "platform: modbus" ?

I do not use default configuration but I suspect it will not work with the current configuration style used in modbus.

**Comment by janiversen** [comment]
Closing since this is not a documentation issue.

Please upgrade your configuration according to the documentation. key "platform" is an old keyword that have not been used since 2021.6 (or something like that).
