### ISSUE TITLE
Huawei-lte no updating after updae core to 2021.08.x

### ISSUE THREAD

**Issue by MiG-41** [home-assistant/home-assistant.github.io#18944]
### Feedback

Stopping updating integrations , picture showe SINR , 3h after update of core , manualy reload huawei_lte result ,that only one time is updating , and then it will be same forever.
![image](https://user-images.githubusercontent.com/57936100/129487052-c2fa05a5-9ee6-46f4-8b52-e04e8117e318.png)

### URL

https://www.home-assistant.io/integrations/huawei_lte/

### Version

2021.8.6

**Comment by scop** [comment]
Please note that home-assistant.io project is for the HA documentation https://github.com/home-assistant/core is for the HA code. Anyway this is fixed in https://github.com/home-assistant/core/pull/54447, 2021.8.7

**Comment by MiG-41** [comment]
@scop ,thank you . Today morning was able 2021.8.7 to upgrade ( perhaps it was in developer earlier but im not a developer ;) )
And everything is ok.
Yesterday i had 2021.8.6 , and still that problem was exist , so i thought there is a time to give a feedback ;)
So it can be closed ,or even erased.

**Comment by scop** [comment]
No problem, 8.7 wasn't available to me yet either when I posted the above, I just knew it was released and on its way.
