### ISSUE TITLE
Wrong Keyword in extended example

### ISSUE THREAD

**Issue by dylan09** [home-assistant/home-assistant.github.io#18958]
### Feedback

In the extended example the keyword `modes` is used. But it should be `mode` without the s.

Throughout the text the correct name for the key is used. 

### URL

https://www.home-assistant.io/integrations/frontend/

### Version

2021.8.7

**Comment by frenck** [comment]
Actually, the example is correct, the rest of the documentation shows the wrong key.

See: <https://github.com/spacegaier/frontend/blob/8576b13f74a49a5ebe29dee5cd5966deceb98969/src/common/dom/apply_themes_on_element.ts#L103>
