### ISSUE TITLE
Doesnt detect IP change

### ISSUE THREAD

**Issue by rcoodey** [home-assistant/home-assistant.github.io#18952]
### Feedback

The Pentair automation had been working great, thanks for the amazing work! Ran into an issue today though that the IP for the ScreenLogic device changed and the HA addon is still trying to connect to the old IP. Would be nice if it could scan for the IP change like the Pentair apps do. But exposing the IP to manually change on the configuration screen would be nice too. Thanks! 

### URL

https://www.home-assistant.io/integrations/screenlogic/

### Version

2021.8.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by rcoodey** [comment]
Thanks for the reply @frenck. I was thinking of this more as an issue than a feature request. Since the addon breaks when the underlying device gets a new IP. Unlike how the integration works on initial setup. But I see your perspective too and can log it that way, no problem.

I did find a workaround, rebooting the entire HA system then it does rescan for an updated IP.

Thanks!

**Comment by frenck** [comment]
Well, you have submitted documentation feedback, so either way, its in the wrong place 😉
