### ISSUE TITLE
motzeh shabat / hag

### ISSUE THREAD

**Issue by chaimt** [home-assistant/home-assistant.github.io#18969]
### Feedback

it would be nice to have a binary sensor for motzeh hag and shabat

### URL

https://www.home-assistant.io/integrations/jewish_calendar/

### Version

2021.8.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
