### ISSUE TITLE
Second installation does not show up in entities

### ISSUE THREAD

**Issue by TSD858** [home-assistant/home-assistant.github.io#18977]
### Feedback

I have two Growatt installations. The second installation (with two inverters) does not show up completely in the entities. Only a few numbers show up, no graphs.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.8.7

**Comment by frenck** [comment]
Hi there @TSD858 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations in our main issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
