### ISSUE TITLE
USB Extension Cable

### ISSUE THREAD

**Issue by Helvio88** [home-assistant/home-assistant.github.io#18988]
### Feedback

I just ran into an issue where my Z-Wave stick would suffer from interference for being connected directly to the computer. Some discord member suggested to use a USB extender cord, which brought my network back online pretty much instantly.

I figure it would be nice to add this hint into the documentation. According to the person who recommended that action, he went over 3 different sticks and they were all affected. For the record, I have a HUSBZB-1

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2021.8.7

**Comment by raman325** [comment]
if you're up for it, this would be a good first contribution for you 🙂

**Comment by atxbyea** [comment]
https://github.com/home-assistant/home-assistant.io/pull/19841

**Comment by MartinHjelmare** [comment]
Our docs have been updated:
https://www.home-assistant.io/integrations/zwave_js/#troubleshooting
