### ISSUE TITLE
Unable to install Picnic Integration in Docker on Raspberry

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [home-assistant/home-assistant.github.io#18982]
### Feedback

"Error:

Unable to load installation flow"

I tried to install it manually with custom component and a sensor in meiner sensor.yaml, but I cant get it to work. Anyone encountered the same problem?

### URL

https://www.home-assistant.io/integrations/picnic/

### Version

2021.8.7

**Comment by frenck** [comment]
Hi there @crustulumtheoneandonly 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by crustulumtheoneandonly** [comment]
Im really sorry, realised just now that Im in the wrong place. Sorry! Wont happen again.. @frenck

**Comment by frenck** [comment]
Don't worry!
