### ISSUE TITLE
Only daly counters.

### ISSUE THREAD

**Issue by juzel69** [home-assistant/home-assistant.github.io#18980]
### Feedback

Hi

In my installation I only have entergy counters, wich will be reseted every nigth. How can i integrate this sensors? 
How can I reset the data for the energy?

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.7

**Comment by frenck** [comment]
Hi there @juzel69 👋 

Thank you for reaching out. It seems like you have a support or development question.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
