### ISSUE TITLE
This integration doesn't work. Also how to add a 2nd switchbot?

### ISSUE THREAD

**Issue by starman2k01** [home-assistant/home-assistant.github.io#18984]
### Feedback

Doesn't work. How do you know if bluetooth operation worked? No log entries. HASS does not tell you status of RPi 4's internal bluetooth.

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2021.8.7

**Comment by Danielhiversen** [comment]
If it is a problem with the integration, you should post an issue here:  https://github.com/home-assistant/core/issues
Could you enable debug logging for the component?
https://www.home-assistant.io/integrations/logger/
