### ISSUE TITLE
ESP Home Light Component,  Flickering effect is not working?

### ISSUE THREAD

**Issue by aquavass** [home-assistant/home-assistant.github.io#18989]
### Feedback

Hi,

I had set up a custom flickering effect which worked perfectly. After the update it stopped working. Although you can select the effect from the drop down box the LED's don't flicker and the colors cannot be changed during the effect. Unlike other effects set up which work perfectly?

I used the following configuration ... 
    effects:
      - flicker:
      - flicker:
          name: Flicker Effect With Custom Values
          alpha: 95%
          intensity: 1.5%

Thanks for your help.

PS: As a work around I configured addressable flicker option  which seems to work however there is a slight pause after each cycle?

      - addressable_flicker:
          name: Addressable Flicker
          update_interval: 5ms
          intensity: 20%

 

### URL

https://esphome.io/components/light/index.html?highlight=effects#light-effects

**Comment by frenck** [comment]
Hi there @aquavass 👋 

It seems like you want to report an issue with an ESPHome component, however, you have submitted documentation feedback at the Home Assistant project for our ESPHome integration instead.

If you want to report issues with ESPHome itself, please report those with the ESPHome project.

<https://github.com/esphome/issues>

Thanks! 👍 

../Frenck
