### ISSUE TITLE
ovo energy French

### ISSUE THREAD

**Issue by BadGones0l** [home-assistant/home-assistant.github.io#18998]
### Feedback

Hello, 

Is it possible to use the ovo Energy integration for French accounts? 

 https://espace-client.ovoenergy.fr/

Sincerely 

### URL

https://www.home-assistant.io/integrations/ovo_energy/

### Version

2021.8.8

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
