### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by addboy58** [home-assistant/home-assistant.github.io#18997]
### Feedback

I have tried for three weeks to get this integration to work. I keep getting "The redirect uri included is not valid" I have made new applications on the Neat web site copied them from the web site. have them placed in the General External box as directed in the instructions. But still the same thing. I think this instigation needs some work..

### URL

https://www.home-assistant.io/integrations/neato/

### Version

2021.8.8

**Comment by dshokouhi** [comment]
the correct place to file an issue is in HA core and not the documentation site.  You need to make sure that you use a valid URL with https and a valid SSL cert.  Then you need to make sure you are accessing HA using the same URL before continuing with the integration.

**Comment by frenck** [comment]
Hi there @addboy58 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. We cannot fix an integration issue by adjusting documented, therefore, please report the such issues in the issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
