### ISSUE TITLE
Home Energy Management

### ISSUE THREAD

**Issue by Paul1881game** [home-assistant/home-assistant.github.io#18992]
### Feedback

Maybe not  100% of the users are interested in this feature or aren't yet ready to use, so... why not give the possibility to disable it from the sidebar? ;)

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.8

### Additional information

none

**Comment by ludeeus** [comment]
Go to your user profile and click "EDIT" here:
![Screenshot from 2021-08-19 10-10-04](https://user-images.githubusercontent.com/15093472/130032400-0ab4133e-bb21-40d5-88e6-603e75413b93.png)

Then remove it from your sidebar :)
