### ISSUE TITLE
Not sure about the warning 

### ISSUE THREAD

**Issue by pwwukpw** [home-assistant/home-assistant.github.io#19002]
### Feedback

Warning re the local API having been removed on newer units .. We have just installed 3 indoor units and the integration worked flawlessly .. many thanks to the dev team 

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2021.8.8

**Comment by frenck** [comment]
In that case, you are lucky.

Daikin themselves has informed us of this change, hence the warning was put up.

Nevertheless, thank you for letting us know!
Enjoy the cool breeze 🌬️  😄

**Comment by pwwukpw** [comment]
Yes it's working really well.

I've latest model so seems your integration will keep working ..

Much appreiate the integration.

Peter
