### ISSUE TITLE
Support to show solar battery -charge /discharge

### ISSUE THREAD

**Issue by sanjeewasam** [home-assistant/home-assistant.github.io#19009]
### Feedback

Thanks for the energy feature added. Currently only solar  and grid power import/export and usage supported. When you have a battery storage with solar the thing become slightly different. There usage= from solar+ from battery and import. Export could be from solar and also battery discharge. Import from grid can also be for usage and to charge the battery. This muddy the info and need more flows to show what is happening.

### URL

https://www.home-assistant.io/lovelace/energy/

### Version

2021.8.8

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

However, that said... Battery support will land in Home Assistant Core 2021.9 😉 

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
