### ISSUE TITLE
2 Factor Autentication

### ISSUE THREAD

**Issue by ZuhairKha** [home-assistant/home-assistant.github.io#19004]
### Feedback

It seems like August has introduced 2 factor authentication where they send an sms message with a code to your phone to complete the authentication process. Since the log-in process in HA doesn't cater for the sms code to be put in, authentication fails

### URL

https://www.home-assistant.io/integrations/august/

### Version

2021.8.8

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
