### ISSUE TITLE
No service for write setting values

### ISSUE THREAD

**Issue by tsenger** [home-assistant/home-assistant.github.io#19014]
### Feedback

In the docs is a description for a service to set some RW values of the Plenticore called
SERVICE KOSTAL_PLENTICORE.WRITE_SETTING_VALUE

But it seems there is no such service in the kostal_plenticore integration. 
"Unable to find service kostal_plenticore.write_setting_value"

Is the documentation wrong? Or do I missed something?

### URL

https://www.home-assistant.io/integrations/kostal_plenticore/

### Version

2021.8.8

**Comment by frenck** [comment]
These indeed never made it into the integration. I've opened up a pull request to adjust the documentation.

Thanks for reporting! 👍
