### ISSUE TITLE
Energy Panel

### ISSUE THREAD

**Issue by villamanuel1980** [home-assistant/home-assistant.github.io#19013]
### Feedback

Hey guys! Are there any plans to adapt the entities to the new Energy Panel? I did it manually but the reset seems to not be working properly so I get an incorrect daily negative value at the start of every day, equivalent to the total solar yield of the day prior. 

I hope this is the place to ask for this!

Thanks for all your great work!

### URL

https://www.home-assistant.io/integrations/kostal_plenticore/

### Version

2021.8.8

**Comment by frenck** [comment]
Thank you for reaching out. It seems like you have a question, however, you have submitted documentation feedback instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
