### ISSUE TITLE
Add example with transition under service_data

### ISSUE THREAD

**Issue by flowconic** [home-assistant/home-assistant.github.io#19019]
### Feedback

Point to improve this page is to show how to add scene “transition” under service_data:   
unsure how to p open structure this myself but it is possible to in the Call Service page, so I assume it’s here as well. 
this would help since transition under scene is currently throwing warnings in the log with a message to be deprecated in a future version. 

### URL

https://www.home-assistant.io/lovelace/button/

### Version

2021.8.8

**Comment by frenck** [comment]
All rules of general service calls apply. Another service call example/manual in our documentation will show which parameters a service call can accept and thus can be added to this example.
