### ISSUE TITLE
add information, how to optionally use a backup

### ISSUE THREAD

**Issue by aisbergde** [home-assistant/home-assistant.github.io#19020]
### Feedback

it is possible to optionally use and restore a backup. But this information is missing here in the onboarding page.

But if the installation is corrupted, then it is a natural process, to use a new SD card, to flash it, to follow the instruction how to setup hass and to restore a backup.

previous page in the workflow is:
https://www.home-assistant.io/installation/raspberrypi

there is a link to the next step "onboarding". 

I see 2 ways to improve the documentation

* The onboarding documentation should contain information about optional usage of a backup
* From the installation pages could be 2 different links: to "onboarding" and to a special page to "use a backup"

I think, the better an intuitive way is to provide this information on the onboarding documentation page. 
  

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2021.8.8

**Comment by frenck** [comment]
I don't think restoring a backup is relevant for "getting started", as the title of these guides says: Its for getting started with Home Assistant for the first time.
