### ISSUE TITLE
No data from Israel region

### ISSUE THREAD

**Issue by leonidfeldman1977** [home-assistant/home-assistant.github.io#19027]
### Feedback

Hello,
No updates from recovered and current 
from Israel region

### URL

https://www.home-assistant.io/integrations/coronavirus/

### Version

2021.8.8

**Comment by frenck** [comment]
Hi there @leonidfeldman1977 👋 

It seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integration here, as listed in various places, including the form you have just filled in incorrectly.

<https://github.com/home-assistant/core/issues>

Thanks already! 👍 

../Frenck
