### ISSUE TITLE
Command_Line sensor does not provide State_Class support

### ISSUE THREAD

**Issue by gilleskd007** [home-assistant/home-assistant.github.io#19026]
### Feedback

For the nicely provided CPU Temperature example to be used with the new Long term statistics graphs ([Link](https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics)), the sensor support must be updated to support State_Class.

### URL

https://www.home-assistant.io/integrations/sensor.command_line/

### Version

2021.8.8

### Additional information

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
