### ISSUE TITLE
Please allow to add state_class and last_reset to allow for long term statistics

### ISSUE THREAD

**Issue by airampg** [home-assistant/home-assistant.github.io#19039]
### Feedback

With the addition of the long-term statistics, the properties state_class and last_reset are necessary. 
Could it be possible to allow the user to specify the state_class and last_reset on the configuration of the min/max sensor, please?
It would also be great if we could specify device_class!
Have a great day!

### URL

https://www.home-assistant.io/integrations/min_max/

### Version

2021.8.8

### Additional information

https://www.home-assistant.io/blog/2021/08/04/release-20218/#long-term-statistics

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
