### ISSUE TITLE
List supported models

### ISSUE THREAD

**Issue by github-0** [home-assistant/home-assistant.github.io#19044]
### Feedback

Would it be possible to list the models that this integration should work with, or even a hint like Samsung API version/model year etc. if listing specific models is impossible?

I tried adding my Q7 (QE65Q7FAM) but the integration says "This Samsung device is currently not supported".

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2021.8.8

**Comment by chemelli74** [comment]
Will be very hard to list of supported or unsupported models.

This is why the integration has the above message 😉

Simone

**Comment by frenck** [comment]
We had such a list in the past, it resulted in something huge and unmaintainable.

Nevertheless, thanks for your suggestion 👍

**Comment by github-0** [comment]
Got it - thanks anyway! Is there no way to for me to determine if some model is supported or not? I.e. if I'm shopping for a new TV is it going to be completely random whether I can use it with the integration? Should I look out for some specific [API](https://developer.samsung.com/smarttv/develop/api-references.html)?
