### ISSUE TITLE
Script debugging gives error

### ISSUE THREAD

**Issue by Zylazy** [home-assistant/home-assistant.github.io#19055]
### Feedback

I am using a script which contains a long **choose** command, and one of its section contains an empty block, I mean there is no command in the **sequence** section.
I was useful because if it's condition was true, the rest has been skipped and jumped to the next command after the **choose** block. Other option would have been if I added it's negated condition to each conditions.
My solution is more simple, but in this case the debugging fails, and can not show my script.

### URL

https://www.home-assistant.io/integrations/script/

### Version

2021.8.8

**Comment by frenck** [comment]
Hi there @Zylazy 👋 

It seems like you want to report an issue with the Home Assistant script integration, however, you have submitted documentation feedback instead.

Please report bugs here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
