### ISSUE TITLE
Speak directly to the person on the doorbird

### ISSUE THREAD

**Issue by GehrigDaenu** [home-assistant/home-assistant.github.io#19059]
### Feedback

Very good description, thank you.
Is it also possible to speak directly to the person on the doorbird from the Home Assistant and if so, how?

If that were possible, I could then open the door from the Home Assistant with Nuki. If not, it doesn't help much to configure the Doorbird in the Home Assistant. Then I still need the Doorbird APP.

### URL

https://www.home-assistant.io/integrations/doorbird/

### Version

2021.8.8

**Comment by bdraco** [comment]
This is not currently possible.


Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
