### ISSUE TITLE
Receive status messages (coffee maker)

### ISSUE THREAD

**Issue by boehser-enkel** [home-assistant/home-assistant.github.io#19056]
### Feedback

Hey there,

I'd like to get messages about water, beans, tray for my coffe maker via HA.
I know this from homebridge so it is possible via the api

greetz

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2021.8.8

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by DavidMStraub** [comment]
@boehser-enkel, FYI some related discussion here: https://github.com/DavidMStraub/homeassistant-homeconnect/issues/42
