### ISSUE TITLE
Developer account not available

### ISSUE THREAD

**Issue by bafplus** [home-assistant/home-assistant.github.io#19050]
### Feedback

The needed developer account is not available anymore (since about a year already).
The only way to use the Toon with HA is to "root" the Toon.

Documentation needs to be revised.

### URL

https://www.home-assistant.io/integrations/toon/

### Version

2021.8.8

**Comment by frenck** [comment]
> The needed developer account is not available anymore (since about a year already).

Could you please point me to a resource that backs that up?


I've just registered a developer account for testing and that works?

<https://developer.toon.eu/>

The documentation seems to be correct as well.

**Comment by bafplus** [comment]
This is based that since about May you dont recieve login or confirmation email when registering for a new dev account or request a new password. Also multiple fora mention that this service doesnt allow for new accounts (same email issue).

I also tested it just now with different email adresses all of them dont recieve login info after registration. Also send a mail to servicedesk multiple times weeks ago, yet still no answer.

**Comment by frenck** [comment]
Meh, ok, I'll try to reach out as well and see what happens.
