### ISSUE TITLE
Daikin BRP072A43 unable to connect

### ISSUE THREAD

**Issue by Vorms** [home-assistant/home-assistant.github.io#19066]
### Feedback

I try to connect to the module using the home assistant integration, but I am still unable to connect.
I use key and password but ...
Can any body help me ? Is that possible to have logs ?

Thanks for the help.

Regards
Thierry

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2021.8.8

**Comment by Vorms** [comment]
unfortunately I am not the owner of the code !

Best regards
Thierry

Le lun. 23 août 2021 à 18:51, probot-home-assistant[bot] <
***@***.***> a écrit :

> Hey there @fredrike
> <https://mailtrack.io/trace/link/7d8e96f41dcb4cc7c7d074ed2d1be4c99beb162b?url=https%3A%2F%2Fgithub.com%2Ffredrike&userId=3563000&signature=cb0eda776f44a53e>,
> mind taking a look at this feedback as it has been labeled with an
> integration (daikin) you are listed as a code owner
> <https://mailtrack.io/trace/link/dfe687a3a01d86e22a729108c00d67c8504eebb9?url=https%3A%2F%2Fgithub.com%2Fhome-assistant%2Fhome-assistant.io%2Fblob%2Fcurrent%2FCODEOWNERS%23L96&userId=3563000&signature=799aa93a4230ec47>
> for? Thanks!
> (message by CodeOwnersMention)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/3eefa320870d1f488ead80bb748aae29ca8d1c63?url=https%3A%2F%2Fgithub.com%2Fhome-assistant%2Fhome-assistant.io%2Fissues%2F19066%23issuecomment-904186078&userId=3563000&signature=faeee9d7719ddf7b>,
> or unsubscribe
> <https://mailtrack.io/trace/link/30819d4acb619732352e973df122f56fb93c7f3d?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA6QD4LTIHJTSTGP4AG3HUTT6LGGFANCNFSM5CVTB6WQ&userId=3563000&signature=22f5c9225180243d>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://mailtrack.io/trace/link/b8ec5b97db1b05ef9d3b5a335bc10e37f6b86ecf?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&userId=3563000&signature=2a859992e6d0858a>
> or Android
> <https://mailtrack.io/trace/link/8f480d7017d1de6dc6e079030d4d0d624c45e371?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&userId=3563000&signature=98edb691d1e3ecb4>
> .
>


-- 
Thierry Vorms
Québec Canada

**Comment by frenck** [comment]
> unfortunately I am not the owner of the code !

That message was for someone else (as it says in the first sentence).

However, that said, it seems like you want to report a issue with an Home Assistant integration, nevertheless, you have submitted documentation feedback instead.

If you want to report an issue with an integration, please report it in the Home Assistant Core issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
