### ISSUE TITLE
Add information on Doorbird WebAdmin

### ISSUE THREAD

**Issue by tnagels** [home-assistant/home-assistant.github.io#19079]
### Feedback

Doorbird has a web service to administer your device from the web rather than from your phone. Is is much more comfortable to set up the devices for use with Home Assistant. Also very helpful when setting things up for a third party.

The url of the webservice is [https://webadmin.doorbird.com/login](https://webadmin.doorbird.com/login).

This way it is easy to set things up on a big screen and to copy/paste settings such as user name & password. 

Only requirement is that the doorbell & your computer must be able to access the internet.

### URL

https://www.home-assistant.io/integrations/doorbird/

### Version

2021.8.8

**Comment by bdraco** [comment]
Feel free to open a PR to add this to the door docs.  Thanks 👍
