### ISSUE TITLE
Add Growatt_server output power as a statistic

### ISSUE THREAD

**Issue by djoenez** [home-assistant/home-assistant.github.io#19074]
### Feedback

Hello, i was wondering if it is possible to add the growatt output power as a statistic as described here:
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

This to integrate it as a "solar panel" in the energy screen.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.8.8

**Comment by muppet3000** [comment]
Hi @djoenez this is a duplicate of https://github.com/home-assistant/core/issues/53963
This was merged in last week and will be part of the next release of HomeAssistant.

**Comment by djoenez** [comment]
Thanks alot! I'm sorry, I missed that one. Appreciate the work!
