### ISSUE TITLE
What metric should be used?

### ISSUE THREAD

**Issue by hofstee** [home-assistant/home-assistant.github.io#19076]
### Feedback

When adding an individual device to the Energy panel, it asks for Device Consumption Energy (kWh). But what's not clear to me is what metric Home Assistant actually wants.

Does it want:
1) The total energy consumption of the device over its lifetime?
2) The energy consumption of the device today?

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2021.8.8

**Comment by frenck** [comment]
Doesn't matter, if it is showing up as selectable in the energy dashboard setting, it will work.
