### ISSUE TITLE
Revert Button / Undo?

### ISSUE THREAD

**Issue by jcavalheri** [home-assistant/home-assistant.github.io#19088]
### Feedback

Hi team,

Would be possible to revert changes / Undo changes?
I already lost count, when I am typing and by mistake click on the side and the entire list is deleted/cleaned.

A simple revert button could help to avoid that,or maybe a double confirmation ( "Do you want to clean the entire list" )?

### URL

https://www.home-assistant.io/lovelace/shopping-list/

### Version

2021.8.8

### Additional information

![image](https://user-images.githubusercontent.com/48921229/130969614-4c8247ca-3087-4298-8409-d087bb6975b8.png)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
