### ISSUE TITLE
BUGs in 2021.8.8 documentation regarding the breaking changes in fritzbox netmonitor

### ISSUE THREAD

**Issue by typxxi** [home-assistant/home-assistant.github.io#19086]
### Feedback

The github documentation for 2021.8.8 mentions as breaking changes that fritz_netmonitor has merged into fritz.
But while fritz netmonitor has been removed fritz is missing - or I can not find it on the home-assistant.io site nor via google.

The documentation regarding netmonitor is also referring to a fritz doc which is a link that goes into nowhere even though it is the only document to find a solution for the netmonitor issue. All "fritz doc" on that page seem to link to this 

https://github.com/home-assistant/home-assistant.io/blob/5c8b23389f2bd1f2c7f6979d5747a9c968bd8a76/integrations/fritz 

which leads to this nice 404 page

![](https://community-assets.home-assistant.io/original/3X/b/3/b395460640c0284dadac02ca54e6ce85c0c69bb9.jpeg)

Here is the github release notes document with the breaking changes paragraphs that mention the breaking changes for fritzbox_netmonitor.

https://github.com/home-assistant/home-assistant.io/blob/5c8b23389f2bd1f2c7f6979d5747a9c968bd8a76/source/_posts/2021-08-04-release-20218.markdown#breaking-changes

Hope it can be fixed soon cause I have used this in all HA installations that are now showing errors even though I had commented the lines out in yaml before updating. 
Should have been a smoother transition I think.

### URL

https://github.com/home-assistant/home-assistant.io/blob/5c8b23389f2bd1f2c7f6979d5747a9c968bd8a76/source/_posts/2021-08-04-release-20218.markdown#breaking-changes

### Version

2021.8.8

**Comment by chemelli74** [comment]
Fritz documentation is here: <https://www.home-assistant.io/integrations/fritz>

Simone
