### ISSUE TITLE
After install and restart I get State: "status unknown" when I go to developer tools

### ISSUE THREAD

**Issue by quasimodo1427** [home-assistant/home-assistant.github.io#19081]
### Feedback

After install and restart I get State: "status unknown" when I go to developer tools

### URL

https://www.home-assistant.io/integrations/dte_energy_bridge/

### Version

2021.8.8

**Comment by Flash3200** [comment]
Same issue…

what else should be in the yaml file besides (ip, name, version) and in dev tools I have…

state_class: measurement
unit_of_measurement: kWh
friendly_name: DTE_Bridge
icon: mdi:flash

**Comment by ludeeus** [comment]
To report issues with integrations, please use this <https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc> issue tracker. Thanks :+1:
