### ISSUE TITLE
Features lost

### ISSUE THREAD

**Issue by raberrio** [home-assistant/home-assistant.github.io#19098]
### Feedback

In the past i used my A/C equipment with custom component Gree climate (by robhoffman) and worked great. Now i am trying to use the official gree integration, which is great for updating purposes.

Sadly, official integration lacks LOTS of features present in the custom component: Control over lights, fan speed, blade oscilation, x-fan, sleep mode, and so on.

Please review the custom component and please bring at least the same features.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.8.8

**Comment by cmroche** [comment]
All of the features you listed are supported in the latest version, as of 2021.8.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/1007595/131173583-86e7c0fe-e8a4-405c-9baf-947a173cd020.png">

Oscillation modes are also supported, just not shown in my configuration.

**Comment by klaasnicolaas** [comment]
Hi there @raberrio  👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
