### ISSUE TITLE
Username and password more details

### ISSUE THREAD

**Issue by B0ndo2** [home-assistant/home-assistant.github.io#19095]
### Feedback

The username and password are for the camera or the vendor cloud/api ?. Please explain more than username and password to use

### URL

https://www.home-assistant.io/integrations/hikvision/

### Version

2021.8.8

**Comment by frenck** [comment]
> The username and password are for the camera or the vendor cloud/api

Nope, it is the local account of your camera. The same credentials as you would use if you locally connected with your camera.

The host is the local camera to connect to, imho that would make it clear it is about the local connection.

![image](https://user-images.githubusercontent.com/195327/131035277-523f4b99-273e-47b8-8345-b37471e29006.png)

Additionally, this integration is classified and listed as "Local push" so, at this point, I'm not entirely sure how you got to "cloud" in this case?

**Comment by B0ndo2** [comment]
I got that it is a local username/password later but it is not obvious until you have looked at all the information on the page and sometimes it is not easy for someone new to HA. It wouldn't hurt to add those details "it is the local account of your camera. The same credentials as you would use if you locally connected with your camera." to the documentation. This is a general comment on most of the documents in HA
