### ISSUE TITLE
Home & away status really slow updating

### ISSUE THREAD

**Issue by victoroos** [home-assistant/home-assistant.github.io#19099]
### Feedback

Hi all,

So, I'm slowly making the switch from Homey to Home assistant. One of the things I'd like ot do, it use TADO's presence system for presence detection. 
But the status in home assistant updates really slowly. Why is this? Is there a way I can fix this. I checked via IFTTT and there it works like a snap!

Any tips?
Cheers
Vic

### URL

https://www.home-assistant.io/integrations/tado/

### Version

2021.8.8

**Comment by michaelarnauts** [comment]
This issue should be opened in the core repo, but actually, this has been changed by an employee of tado itself.

See https://github.com/home-assistant/core/pull/46915
