### ISSUE TITLE
Shelley link broken

### ISSUE THREAD

**Issue by cjj** [home-assistant/home-assistant.github.io#19092]
### Feedback

Recommendation for off the shelf CTs includes Shelley EM, however the link does not correspond to a current/real product. Would be great to have actual available hardware for people to learn and adopt

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.8.8

**Comment by chemelli74** [comment]
Link updated.

**Comment by cjj** [comment]
Link still not working @chemelli74 . Not sure if this is a country-product availability issue, but I'm in US and just goes to main product page. I think it should be (from products I can see): https://shopusa.shelly.cloud/shelly-em-50a-clamp-wifi-smart-home-automation#198

**Comment by chemelli74** [comment]
@cjj, works fine here.
I bet you get redirected automatically by IP detection and the site structure differ.
