### ISSUE TITLE
Documentation on using Secrets in sub-folders

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#19106]
### Feedback

Could an example be added to the documentation demonstrating the use of a secret from a sub-folder.

An example being where the secrets.yaml is at the root level, then a sub-folder called sensors has a file which would like to refer to a secret.

### URL

https://www.home-assistant.io/docs/configuration/secrets/

### Version

2021.8.8

**Comment by frenck** [comment]
> Could an example be added to the documentation demonstrating the use of a secret from a sub-folder.

There is no such a thing, thus there is no documentation about it.
The location of the secrets file is hardcoded in the Home Assistant Core.
