### ISSUE TITLE
luci-mod-rpc not available (any more?)

### ISSUE THREAD

**Issue by nerdoc** [home-assistant/home-assistant.github.io#19103]
### Feedback

on a recent OpenWRT (currently OpenWrt 19.07.4), there is no `luci-mod-rpc` package.
```
~# opkg install luci-mod-rpc
Unknown package 'luci-mod-rpc'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci-mod-rpc.
```

### URL

https://www.home-assistant.io/integrations/luci/

### Version

2021.8.8

**Comment by tosh-io** [comment]
Run an update before
~# opkg update

Then try again

**Comment by nerdoc** [comment]
Did you re-upload it again - because it works now. I did an `opkg update` before I tried in the first place...
Anyway, it works now, thanks.

**Comment by tosh-io** [comment]
I am just an ordinary user ;-)
Who had the same error as you and tried to give u my 2 cents..

Cheers

**Comment by nerdoc** [comment]
OMG. `opkg update`. What a shame... :smile: 
Github, could you please hide this issue, with my name on it? :smile: 

Thanks @tosh-io
