### ISSUE TITLE
HA OS documentation.

### ISSUE THREAD

**Issue by Sudo-Rob** [home-assistant/home-assistant.github.io#19109]
### Feedback

HA OS has one glaring shortcoming; there seems to be no way of adding USB peripheral drivers to a configured system once the OS has been built. If this is incorrect, there should be a tutorial for adding peripheral drivers to the OS documentation. 

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2021.8.8

**Comment by frenck** [comment]
> there seems to be no way of adding USB peripheral drivers to a configured system once the OS has been built

Correct.
