### ISSUE TITLE
What do you enter in the 'Host' field at the 1st step of adding the WLED integration?  

### ISSUE THREAD

**Issue by mjkasper01** [home-assistant/home-assistant.github.io#19107]
### Feedback

I have tried the IP address of the PC running HA, I've tried the machine name of PC running HA.  In all cases I receive a 'Failed to connect' message.  Your guide skips right over what is expected in that first dialog box.

### URL

https://www.home-assistant.io/integrations/wled/

### Version

2021.8.8

**Comment by mjkasper01** [comment]
I figured it out.  If there is a WLED controller on the network it will auto-discover it and provide it as an option.  In my case, my WLED controllers are only powered when I wont the LEDs on (power controlled by Z-wave switches).  Since my WLED controllers are off, nothing was auto-discovered and therefore nothing was prepopulated.  A note could be added to the install page to mention that a WLED controller must be on the network during the integration.

**Comment by frenck** [comment]
> I have tried the IP address of the PC running HA, I've tried the machine name of PC running HA. In all cases I receive a 'Failed to connect' message.

In general, Home Assistant integrations connect TO devices or services. This integration connect to WLED devices, thus needs the host address of the WLED device to connect to.

This is not unique to this integrations, this applies to ALL of Home Assistant.

>  A note could be added to the install page to mention that a WLED controller must be on the network during the integration.

Well, you can't connect to something that isn't there 🤷 

Auto-discovery is not a requirement.
