### ISSUE TITLE
Can't figure out what "code" refers to in integration setup

### ISSUE THREAD

**Issue by zoness32** [home-assistant/home-assistant.github.io#19108]
### Feedback

The configuration steps require adding a "code" value in addition to an email and password to connect to Simplisafe, but I can't find any references anywhere online to what that code actually is or where to find it.

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2021.8.8

**Comment by bachya** [comment]
The label says it all: "Code (used in Home Assistant UI)" – thus, if you want to have users provide a code to arm/disarm the alarm in the UI, put a value in this field. If not, leave it blank.
