### ISSUE TITLE
Lutron integration documentation should mention creating credentials in RadioRa2 software

### ISSUE THREAD

**Issue by zbrozek** [home-assistant/home-assistant.github.io#19119]
### Feedback

The once-default credentials `lutron` and `integration` no longer exist. Further, the Lutron integration software hammers away with incorrect credentials and triggers auto-lockout behavior on the main repeater. It would be good to tell folks that they need to go create an integration credential in the RadioRa2 software:
![integration_settings](https://user-images.githubusercontent.com/4878259/131234723-9f2a5554-4165-42f2-bb00-81118e669b49.png)

### URL

https://www.home-assistant.io/integrations/lutron/

### Version

2021.8.8

**Comment by JonGilmore** [comment]
Thanks for opening an issue with this @zbrozek  - please have a look at https://github.com/home-assistant/home-assistant.io/pull/19121 to see if it helps clarify things a bit more for new users of the integration.

**Comment by zbrozek** [comment]
That looks great, thanks! Might want to tell folks where the setting is within the RadioRa2 software (open a project, settings menu, integrations menu item, plus button in lower left) just to help them avoid hunting and pecking.

**Comment by JonGilmore** [comment]
This seems like a funny question, but my Windows machine just blew up last week.... and I haven't rebuilt it yet, would you mind providing a few screenshots of navigating to create new creds? :D

**Comment by zbrozek** [comment]
I think these two are probably sufficient. I didn't add markup (arrows or boxes or similar), but could. Thoughts?
![menu_location](https://user-images.githubusercontent.com/4878259/131237271-a5c0aa6d-158e-4004-bc65-4f5d2845b308.png)
![button_location](https://user-images.githubusercontent.com/4878259/131237273-aedb554a-83bf-47ab-ae43-26d8d4412df8.png)
