### ISSUE TITLE
I love this plugin! But...

### ISSUE THREAD

**Issue by joshcliffejones** [home-assistant/home-assistant.github.io#19118]
### Feedback

I am hugely grateful for this plug in as it pulls in useful information for my Solar without me having to log in to the Growatt web site.

However, i was really hoping that it would be compatible with the new Energy Monitoring in Home Assistant so that i could better plot out my consumption and generation.

Is this something that will be coming in the future?

Josh

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.8.8

**Comment by muppet3000** [comment]
Hi @joshcliffejones thanks for the awesome feedback.
This is actually a duplicate of: https://github.com/home-assistant/core/issues/53963
You can even see a screen grab of this new functionality working over there.
All the code has been merged and it will be in the next release of HASS.
Enjoy!

**Comment by joshcliffejones** [comment]
Thank you so much for your super fast response and for the awesome news! I look forward to the next update in that case! :D
