### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI - comment is not helpfull

### ISSUE THREAD

**Issue by giluriel** [home-assistant/home-assistant.github.io#19113]
### Feedback

OK. I'm getting this error. though there is a specific comment for that in the documentation, it says "compare" 
... compare and what ?....
 :(
still stuck with it 

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2021.8.8

**Comment by lein1013** [comment]
This note is maybe more for advanced users? For me it helped.

For the inital configuration I'd recommend to used the external callback AND the internal callback url in the spotify developer settings and AFTER the setup the external can be removed again

**Comment by atxbyea** [comment]
what have you actually put in the redirect uri field in the spotify developer console ? And what does it redirect to when you try to connect it @giluriel

**Comment by Kiggerbare** [comment]
Sorry im late to the party. 
If you use the cloud what you need to put is " https://YOUR_NABU_CASA_ID.ui.nabu.casa/auth/external/callback " in the spotify URI.

As to what page it takes you to it's one from spotify where you confirm who you are. :)
