### ISSUE TITLE
eSterownik - cannot install

### ISSUE THREAD

**Issue by OldShaterhan** [home-assistant/home-assistant.github.io#19116]
### Feedback

Hi,

I cannot run "eSterownik eCoal.pl Boiler". Why this is happens? Also it looks like noone has it installed:
![image](https://user-images.githubusercontent.com/1622866/131224731-93368cf1-a4ae-4bb0-920a-070bda8d384c.png)

Additional question: can this be run with other eSterownik systems like "PELLO"?

### URL

https://www.home-assistant.io/integrations/ecoal_boiler/

### Version

2021.8.8

### Additional information

![image](https://user-images.githubusercontent.com/1622866/131224740-00a71303-b0c9-4642-ba9c-ae8bb34f8cb8.png)

**Comment by frenck** [comment]
The screenshot shows you are trying to set up this integration via the UI, however, this integration can only be set up manually.

See: <https://www.home-assistant.io/integrations/ecoal_boiler/#configuration>

If it doesn't work as expected after that, please file a bug report in the issue tracker for Home Assistant Core, including error/warning logs and a description of the behavior you are experiencing.

To know where to go, see https://www.home-assistant.io/help>

Thanks 👍 

../Frenck

**Comment by OldShaterhan** [comment]
Thanks! It's my first steps using HomeAssistant and I didn't understand it yet! :) I'll look at that.
