### ISSUE TITLE
Keba: Add troubleshooting steps for sensors not being updated

### ISSUE THREAD

**Issue by Sirs0ri** [home-assistant/home-assistant.github.io#19117]
### Feedback

**Problem description**
Over the last few days, I tried figuring out why my Keba P30c was shown as "connected", but none of the other sensors were updated. The Plug sensor was constantly "unpplugged", most other sensors were "unavailable". The web-interface was available and updating as it's supposed to.

In the end, I figured out that the wallbox' UDP interface was turned off via a hardware "DIP" switch inside the device, turned the switch on and now everything's working as intended. I figured that it would be good if the documentation would cover that case since it's a problem that can occur easily depending on the installer, and it's easily fixed.

**Solution**
The status of the UDP interface is controlled by **DIP Switch 1.3** inside the Wallbox, relevant documentation from the manufacturer can be found in the [installation manual](https://www.keba.com/file/downloads/e-mobility/KeContact_KCP20_30_ih_en.pdf), chapter 4.6 (Page 32/48 in the English manual). To change the switch, the user needs to:

- Open the main cover of the device
- Take of the first internal cover to expose the DIP Switches, Ethernet Port, etc. This does _not_ expose any mains wiring.
- Flip the DIP switch to "on"
- Restart the Wallbox by either (reference installation manual, ch. 4.6):
  - Pressing the **service button** for 1 second or 
  - Switching the power supply voltage off/on

A screenshot of the relevant documentation is attached below.

I'm not sure what the best way would be to add these troubleshooting steps to the documentation, if I could get some guidance I can start a PR to update the docs myself.

### URL

https://www.home-assistant.io/integrations/keba/

### Version

2021.8.8

### Additional information

![2021-08-28 21_06_14-Window](https://user-images.githubusercontent.com/6765536/131228297-78b1734f-0b8e-4455-afbb-3eff6d190e90.png)

**Comment by dannerph** [comment]
Thanks for the hint, I added a small note to the documentation.

**Comment by Sirs0ri** [comment]
Thank you very much!
