### ISSUE TITLE
Typo in the MQTT beta release notes for 2021.9

### ISSUE THREAD

**Issue by ovitters** [home-assistant/home-assistant.github.io#19111]
### Feedback

This for the beta release notes of 2021.9 as per the rc website/blog.

> With release 2021.3 the support for legacy speeds was announced to be removed after a _quater_ (2021.7).

Instead of _quater_ you want _quarter_.

I didn't really notice anything else. Maybe "Thanks to @bdraco, camera images can now be scaled to a resolution" could reference that there's another section for the camera custom integrations.

### URL

https://rc.home-assistant.io/blog/2021/08/25/release-20219/

### Version

2021.9

**Comment by frenck** [comment]
Pushed an update for the typo! Thanks for reporting 👍
