### ISSUE TITLE
MQTT integration is confusing and does not mention anything about credentials

### ISSUE THREAD

**Issue by tggm** [home-assistant/home-assistant.github.io#19112]
### Feedback

The MQTT integration documentation page, available at: https://www.home-assistant.io/integrations/mqtt/ is very incomplete and confusing.

Issues with the page

- It's not made clear that the preferred way is to setup the MQTT add-on with this broker and there's a difference between the two. This easily causes confusions with new users since they google "home assistant MQTT" and end-up navigating between the two concepts.
- There are two sections of "Manual Configuration" (via the integration wizard and via the configuration.yaml)
- The last bullet "Follow the instruction on screen to complete the set up." does not contain any further instructions. 
- There are absolutely no instructions about what to place in Username and Password fields of the "Broker Options" dialog. 

The credentials part is the most confusing. There should be some clarification on what to put where and what's the relation (if any) of these credentials to the ones in the Add-On's Configuration. 

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2021.8.8

**Comment by evanheckert** [comment]
Agreed - also, it would be helpful to note the functions of the integration. Does it trigger an MQTT message each time something changes in Home Assistant? Does it cause Home Assistant to automatically listen for certain payloads, and will update entities based on it?

**Comment by emontnemery** [comment]
@tggm @evanheckert please help push this forward by clicking the edit button on the page and proposing changes 👍

**Comment by evanheckert** [comment]
@emontnemery I certainly would, but I don't know the answers. My examples are guesses. I stumbled upon this thread in search of definitive answers.
