### ISSUE TITLE
Typo in worked example

### ISSUE THREAD

**Issue by paulbarrnz** [home-assistant/home-assistant.github.io#19120]
### Feedback

In the install home assistant core section there is this code block:
`sudo -u homeassistant -H -s
cd /srv/homeassistant
python3.8 -m venv .
source bin/activate`

It fails because it is trying to call python 3.8 not just python 3
I suggest it should be:
`sudo -u homeassistant -H -s
cd /srv/homeassistant
python3 -m venv .
source bin/activate`

Thank you.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.8.8

**Comment by frenck** [comment]
That depends on your setup. This is an advanced installation method, therefore we will assume these type of issues can be resolved by the user of this installation method.
