### ISSUE TITLE
No information about configuration.conf 

### ISSUE THREAD

**Issue by jarekt70** [home-assistant/home-assistant.github.io#19122]
### Feedback

There is no information on the page how it is possible to configure the integration by settings parameters into configuration.conf file. Is it possible?

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.8.8

**Comment by frenck** [comment]
No, that is not possible, or else it would have been listed.

**Comment by jarekt70** [comment]
Thanks for the reply. Any idea how to connect it in case when my Gree AC is connected in a different subnetwork than the HomeAssistant?

**Comment by frenck** [comment]
That seems not possible with this integration.

**Comment by cmroche** [comment]
Gree discovery is broadcast based, the protocol was designed with the expectation that all endpoints can reach one another without routing.

**Comment by jarekt70** [comment]
It's a pity that this integration is brodcast based only. I'm succesfully using Gree integration based on Gree custom component and I'm able to provide IP/port of the device. I was thinking about switching to this integration because HA is complaining in the log about stability of the system because of this integration.
