### ISSUE TITLE
Unable to pull multiple entities - only 1 entity is pulled

### ISSUE THREAD

**Issue by amritgary** [home-assistant/home-assistant.github.io#19128]
### Feedback

There are two entities, but it's only pulling the first one..
The 'somecomfort --devices' command works well and pulls multiple devices, but the integration itself is limiting the pull to the first entity only

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.8.8

**Comment by rdfurman** [comment]
Duplicate of https://github.com/home-assistant/core/issues/53981.

**Comment by frenck** [comment]
Closing this as a duplicate
