### ISSUE TITLE
Local IP integration Feedback Request

### ISSUE THREAD

**Issue by Grey-Lancaster** [home-assistant/home-assistant.github.io#19126]
### Feedback

Would be nice if it showed gateway and DNS servers
Thanks,
Grey

### URL

https://www.home-assistant.io/integrations/local_ip/

### Version

2021.8.8

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
