### ISSUE TITLE
Vmware installation

### ISSUE THREAD

**Issue by Nanni50** [home-assistant/home-assistant.github.io#19123]
### Feedback

HI,
pls note that the described procedure is not coherent with the last free VMware version. 
It's not easy to use the provided disk (you must delete the disk created by VMware and then you can specify the downloaded file).
There is no motherboad tag and there is no way to specify the UEFI boot, but if I suppose this is the standard for new machines.
When in some way you finish the machine, you get a message "**no operative system found**"!!  I tried several times but the result  remained the same.

Indeed I had to use docker. In this case the instructions are fine.

### URL

https://www.home-assistant.io/installation/linux/

### Version

2021.8.8

**Comment by Grey-Lancaster** [comment]
This worked for me
https://sourceforge.net/projects/vmtweaker/
changed to uefi
