### ISSUE TITLE
HDMI CEC integration with host remote configuration not reconnecting

### ISSUE THREAD

**Issue by faniskou** [home-assistant/home-assistant.github.io#19129]
### Feedback

Hi a small report. At list in my configuration ( -Ha on docker- and -pycec on a pi4 media server- with pycec running as a service
) using cec integration with host : (pi address) 
, the integration loosing connection permanently after a pi media server restart .  
The problem of course is fixed if I restart ha causing a reload the integration .
If you can imagine any fix or workaround?

### URL

https://www.home-assistant.io/integrations/hdmi_cec/

### Version

2021.8.8

**Comment by frenck** [comment]
Hi there @faniskou 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
