### ISSUE TITLE
Requirement for device name

### ISSUE THREAD

**Issue by dakoellis** [home-assistant/home-assistant.github.io#19139]
### Feedback

While trying to get the component to work, I ran into an issue with the device not being recognized with how I set it up with my device descriptor.  Seems like the component needs the device to be passed in as /dev/input/<something> at least?  /dev/airmouse didn't work, and /dev/input didn't work either, but /dev/input/event0 did.  I did my testing in docker, but presumably that location would also be a requirement for udev rules?

### URL

https://www.home-assistant.io/integrations/keyboard_remote/

### Version

2021.8.8

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by dakoellis** [comment]
Is this not the way to provide feedback for updates on the wiki? I already had this resolved but the documentation wasn't sufficient for me so I figured I would ask about updating it

**Comment by frenck** [comment]
This depends on how you set up and manage your Docker environment and is not specific to this integration.

**Comment by dakoellis** [comment]
But that's what I'm saying. I tried multiple different docker setups and
while I was able to see everything in the docker container the integration
wasn't picking it up. It seems like /dev/input is hardcoded in the code as
the path to watch (init lines 112-118) so if you pass in the device at a
directory outside of /dev/input the integration will not see it.

**Comment by frenck** [comment]
Symlinks to alias devices should not be a problem, however, that depends on your setup.

**Comment by dakoellis** [comment]
But regardless if how you set it up, it still has to be under /dev/input based on the integration code and my testing.  What I'm saying is I set up an alias to /dev/airmouse, and I couldn't use that for the integration because it was not under /dev/input.  The only way to use /dev/airmouse (whether it be docker, udev, or something else) would be to set an alias from /dev/airmouse to /dev/input/airmouse (or whatever you want it to be).  All I'm saying is that the documentation should mention that it watches the /dev/input directory (as the integration is hardcoded to do so) in order to save someone the time trying to figure it out if they do want to use some sort of rename.
