### ISSUE TITLE
Platform switchbot

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#19135]
### Feedback

Reading the documentation it is not really clear what the prerequisits are: 

- the switchbot hub mini (bluetooth to wlan gateway)

or 

- just bluetooth hardware on the HA system

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2021.8.8

**Comment by Danielhiversen** [comment]
just bluetooth hardware on the HA system

**Comment by hklages** [comment]
... and the required mac address I can look up in the switchbot app? Or does it work with autodiscovery?

**Comment by Danielhiversen** [comment]
The mac address is required. I think you can find it in the switchbot app

**Comment by hklages** [comment]
Thanks for clarification.

**Comment by Danielhiversen** [comment]
I reopen it. We should improve the documentation

**Comment by jmottster** [comment]
If you want to provide a basic outline of some of the details (hub or device, if device which ones, if one needs a BLE receiver on HA host machine, etc.), I'm pretty good at turning that into easy to follow directions and/or information. I'd be happy to help.

**Comment by warksit** [comment]
![image](https://user-images.githubusercontent.com/5296633/131576961-7eadb7e0-5f78-44fb-85ee-598406594d54.png)

Bluetooth MAC address under 'device info' of the bot in the app.

**Comment by warksit** [comment]
> If you want to provide a basic outline of some of the details (hub or device, if device which ones, if one needs a BLE receiver on HA host machine, etc.), I'm pretty good at turning that into easy to follow directions and/or information. I'd be happy to help. 

The Host running HA requires Bluetooth. Pi3B works fine.

**Comment by hklages** [comment]
I can give you the information about Raspberry Pi 4 in few days. Should be similiar.

**Comment by hklages** [comment]
The Host running HA requires Bluetooth device. In Home Assistant Operating System the bluetooth software stack is included.
Pi4 works fine.

Switchbot app (either iPhone or Android) needs to be installed on Smartphone- there you can configure the Switchbot (mode, time, ...). The name is not transferred to HA.

Switchbot is being found automatically after Server Management restart.
Switchbot is shown as entity (not device).
Bluetooth mac looks like F3:E4:4B:CE:15:EE 
On Android Smartphones the mac can be found in settings and 3 dot menu Info.

There is no event handling: If you change the status of the Switchbot with the App the status on HA will not be updated and vice versa.
