### ISSUE TITLE
After the first reboot there is a Google Calendar Setup notification but it says its expired

### ISSUE THREAD

**Issue by ronaldvdmeer** [home-assistant/home-assistant.github.io#19137]
### Feedback

After the first reboot, after creating API and such, according to the documentation there should be a link provided. 

> The next time you run or restart Home Assistant, you should find a new notification (the little bell icon in the lower-left corner). Click on that notification it will give you a link and an authentication code. Click on that link to open a Google website where you should enter the code found in the notification (NOTE: You may get a message telling you that the API has not been verified and you will need to acknowledge that in order to proceed). This will grant your Home Assistant service read-only or read-write access (based on configuration) to all the Google Calendars that the account you authenticate with can read.

However I get the following error message after restarting Home Assistant each time.

```Authentication code expired, please restart Home-Assistant and try again```

### URL

https://www.home-assistant.io/integrations/calendar.google/

### Version

2021.8.8

### Additional information

Tried restarting Home Assistant but same error occurs.

**Comment by ronaldvdmeer** [comment]
With screen recording I was able to get the link and the code. It was available 2 seconds before the Authentication code expired message appears. However, even when I've filled in the code on the next restart the same error appears again in the screen.

**Comment by uaerbl** [comment]
##- [x] Nice ****
