### ISSUE TITLE
Is it possible to reset the value of the Riemann sum integration?

### ISSUE THREAD

**Issue by JvdBBBB** [home-assistant/home-assistant.github.io#19149]
### Feedback

Is it possible to reset the value of the Riemann sum integration?

I am trying to calculate the solar radiation sum, but want to reset this value everytime I have performed an action at a certain value. Watering the plants for a certain amount of energy.

Another question, I want to sum W/m2 but as a calculation result I want J/cm2. Is it possible to devide the result by 10000?

### URL

https://www.home-assistant.io/integrations/integration/

### Version

2021.8.8

**Comment by dgomes** [comment]
The sensor can't be reset. 

...but you can use utility_meter to programatically reset it (its common in energy monitoring scenarios and there is nothing impeding in utility_meter to use it on non energy scenario)

For your second question (which should have been a different issue!) you can use a template sensor to do any math you require

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
