### ISSUE TITLE
Lacks any details

### ISSUE THREAD

**Issue by jmottster** [home-assistant/home-assistant.github.io#19141]
### Feedback

This doesn't say if it's for individual switchbot devices, and if so which ones are supported, or if it's for the switch bot hub making all switchbot devices available. 

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2021.8.8

**Comment by Danielhiversen** [comment]
Duplicate of https://github.com/home-assistant/home-assistant.io/issues/19135
