### ISSUE TITLE
Firefox's "Enhanced Tracking Protection" breaks Add-Ons -> Document in browser compatibility list?

### ISSUE THREAD

**Issue by felurx** [home-assistant/home-assistant.github.io#19144]
### Feedback

Firefox's "Enhanced Tracking Protection" handles cookies in a way that breaks add-ons when set to the "Strict" setting. (They don't get the authentication cookie, so you just get a "401: Unauthorized".)
This really tripped me up as a new user, and I wasn't the first one, [apparently](https://github.com/home-assistant/frontend/issues/7090). You can easily fix add-ons by adding an exception with like 2 clicks.
It might be helpful to document this in this compatibility list in a footnote or the comment column (or somewhere else entirely), but I wanted to get some feedback on this before submitting a PR. What do you think, person who happens to read this? 

### URL

https://www.home-assistant.io/docs/frontend/browsers/

### Version

2021.8.8

**Comment by ludeeus** [comment]
This is a confirmed bug in firefox that is tracked here <https://github.com/home-assistant/supervisor/issues/3021> we should not document bugs.

**Comment by felurx** [comment]
Thanks for the feedback and the link to the bugtracker!
