### ISSUE TITLE
Q... is the Worx Landroid M500 supported?

### ISSUE THREAD

**Issue by boelle** [home-assistant/home-assistant.github.io#19143]
### Feedback

there is no date on the website hence i ask if this has been added to the list of supported mowers since the page was created

### URL

https://www.home-assistant.io/integrations/worxlandroid/

### Version

2021.8.8

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
