### ISSUE TITLE
Add warning that dynamic values for the filter are not possible

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#19158]
### Feedback

I think this section should have a small warning that dynamic values for "value:" are not possible.

I wanted to filter entities based on the value of another entity: e.g. are room temperatures colder than the outside temperature? Thus "value:" would be something like {{ states(sensor.outsidesensor_temp) }}. I've tried many different variations, but it was not possible. 

Would be nice if other people won't have to try that much and just get a small warning: this is not possible.

### URL

https://www.home-assistant.io/lovelace/entity-filter/

### Version

2021.8.8

**Comment by ludeeus** [comment]
We should not add this, we should only document where templates are supported, not where they are not supported

**Comment by frenck** [comment]
I agree with Ludeeus on this one. Therefore closing this issue.

Neverthless, thank you for your feedback 👍
