### ISSUE TITLE
URL disabled at Eufylife

### ISSUE THREAD

**Issue by redfameMN** [home-assistant/home-assistant.github.io#19153]
### Feedback

The current documented API URL results in a 404.  No word from eufy on what the right one is.

### URL

https://www.home-assistant.io/integrations/eufy/

### Version

2021.8.8

**Comment by ludeeus** [comment]
The right one is the one in the documentation, but you have to use it like the documentation says, if you open it in the browser it will indeed give a 404, since it does not allow that.
