### ISSUE TITLE
Install HA on Intel NUC with bootable UBS

### ISSUE THREAD

**Issue by GazTheGeek** [home-assistant/home-assistant.github.io#19154]
### Feedback

Hi team. I bought an Intel NUC and realised that to follow the offical guide I would need to remove the SSD and mount it in a USB case and then write the image to it. I didn't have a case and didn't want to get one so I used another method.

I downloaded a Debian live bootable image from [here](https://www.debian.org/CD/live/) and burned it to a USB stick.

I made sure the bios was set as per the official instructions.

I booted from the usb on the NUC to run Debian on the NUC from the USB and downloaded Belena Etcher and then burned the HA Image via URL to the SSD on the NUC. Worked great.

A word to the newbie. Don't try to do this with only a keyboard attached to the NUC. I couldn't open the link in Etcher that reveals the hidden drive - which in this case is the SSD. I had to start again with a mouse attached.

In a perfect word there would be a bootable installer image for HA available - but failing this - This method is a viable alternative.

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2021.8.8

**Comment by ludeeus** [comment]
> If you prefer to use a live operating system, follow the instructions of your Live distribution (e.g., this Ubuntu guide). Once you booted the live operating system, the following steps on how to write the image to your boot media can be followed.

This is already mentioned in there?

**Comment by GazTheGeek** [comment]
> > If you prefer to use a live operating system, follow the instructions of your Live distribution (e.g., this Ubuntu guide). Once you booted the live operating system, the following steps on how to write the image to your boot media can be followed.
> 
> This is already mentioned in there?

Fair enough - This comment wasn't obvious until after the event. In my case this was the only solution. I thought others would benefit from a bit more detail.
