### ISSUE TITLE
Incorrect Unit of measurement for energy sensors

### ISSUE THREAD

**Issue by svanimpelen** [home-assistant/home-assistant.github.io#19166]
### Feedback

Change "Unit_of_measurement" of the energy consumption sensors from kWh to EUR/kWH to resolve message on energy configuration page:
**Unexpected unit of measurement**
The following entities do not have the expected units of measurement 'EUR/kWh' or 'EUR/Wh':
- sensor.home_energy_consumption_price_high
- sensor.home_energy_consumption_price_low

Btw, awesome integration. much appreciated :)

### URL

https://www.home-assistant.io/integrations/p1_monitor/

### Version

2021.9.0

### Additional information

![image](https://user-images.githubusercontent.com/22742135/131808005-33c4fbc9-40f4-48f4-bdfa-2605f1b66cc9.png)
![image](https://user-images.githubusercontent.com/22742135/131808095-d5da21ee-58b7-423b-9350-685f1bebefdb.png)

**Comment by klaasnicolaas** [comment]
I also found out last night that this causes problems, there are more integrations with similar problem. The only problem is that the fix may not only be with the integration, but also something that can be improved overall in core.


ps. The yellow marked units are correct 😉

**Comment by klaasnicolaas** [comment]
BTW. You have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by svanimpelen** [comment]
@klaasnicolaas Oke sorry! Will raise an issue, thanks for the feedback
