### ISSUE TITLE
Override 'why is my entity not in the list' and show all entitys

### ISSUE THREAD

**Issue by sbeukers** [home-assistant/home-assistant.github.io#19163]
### Feedback

​Can we override the 'why is my entity not in the list' message and show everything in the energy tab?

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.9.0

### Additional information

I am using the Plugwise Smile P1

**Comment by ludeeus** [comment]
No, the entities need proper support to display correctly.
For feature requests please open those on the forums :+1:
