### ISSUE TITLE
Missing a link to the next step: building it into the dashboard

### ISSUE THREAD

**Issue by martinwk** [home-assistant/home-assistant.github.io#19172]
### Feedback

I am looking for a link which tells me the recommended way to get all the nice energy data visible in a dashboard

### URL

https://www.home-assistant.io/docs/energy/

### Version

2021.9.0

**Comment by ludeeus** [comment]
The first time you visit the energy panel in your sidebar you are shown a wizard to set it up.

**Comment by martinwk** [comment]
Yes you're right... My bad. I apparently did not upgrade to the latest version (I think I used stable instead of latest when pulling the docker container). The whole dashboard is auto created now, very nice. So I'll close this issue now.
