### ISSUE TITLE
Lovelace Statistics Graph

### ISSUE THREAD

**Issue by RouxChristian** [home-assistant/home-assistant.github.io#19171]
### Feedback

Hi,

is it planned to provide support for the new Lovelace statistics graph? https://www.home-assistant.io/lovelace/statistics-graph
I'm currently not able to select a knx value like temperature to show in this new graph.

### URL

https://www.home-assistant.io/integrations/knx/

### Version

2021.8.8

**Comment by farmio** [comment]
update to 2021.9 and configure a `state_class` to your sensor. https://github.com/home-assistant/core/pull/53996 (description is not accurate there, can't change it anymore).

PS: this issue tracker is for the documentation at home-assistant.io, not for feature requests or support questions.

**Comment by RouxChristian** [comment]
Thank you very much and sorry for addressing in the wrong channel. 2021.09 ist Not available in my supervisor yet but I will find a way to get this upgrade :)

**Comment by farmio** [comment]
Sure! Please close this issue.
