### ISSUE TITLE
No matching statistics found on WEM3080T from Iammeter

### ISSUE THREAD

**Issue by ultra-visionro** [home-assistant/home-assistant.github.io#19175]
### Feedback

Hi there!
I bought WEM3080T from Iammeter. All entities are available, i can set them in UI but i cant configure them in energy tab, because "No matching statistics found".

What can i do?

### URL

https://www.home-assistant.io/integrations/iammeter/

### Version

2021.9.0

**Comment by klaasnicolaas** [comment]
Hi there @ultra-visionro  👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
