### ISSUE TITLE
Instruction on screen unclear and fail to add integration

### ISSUE THREAD

**Issue by vpathuis** [home-assistant/home-assistant.github.io#19173]
### Feedback

It's not clear what to fill in for "Host". Is that only the ip (192.168.1.10), or the url (http://192.168.1.10), or something else altogether. (Neither work by the way, I'll submit a bug for that somewhere)

### URL

https://www.home-assistant.io/integrations/youless/

### Version

2021.9.0

**Comment by vpathuis** [comment]
Can't find where to submit the bug, so I'll add some more info here, since it's going to the code owner anyway :)

The integration says:
Success!
Created configuration for 192.168.1.10

But after that it shows a warning on screen:
Retrying setup: Expecting value: line 1 column 1 (char 0). 

In the log some more info is added: 
Config entry '192.168.1.10' for youless integration not ready yet: Expecting value: line 1 column 1 (char 0); Retrying in background

**Comment by vpathuis** [comment]
I'm using the Pvoutput firmware by the way. Not sure if this is relevant.

**Comment by gjong** [comment]
The pvoutput firmware is not supported, as the integration depends on some rest end points that are part of the default firmware. 

To be able to support pvoutput I woud need a lot more information. For example what rest interfaces this firmware exposes and what type of information is in the rest interface.

**Comment by vpathuis** [comment]
ah, that's a shame. Do you see that being supported in the future? I've developed the Youless plugin for the Vera a few years ago and it didn't seem to different/difficult to me. I could help of course. Perhaps even make the change as a pull request?

**Comment by gjong** [comment]
If you can provide information on what end-points are exposed by the pvoutput firmware and what response to expect then I can look into adding support in the library underneath. Considering you already did something similar I would expect that you could definitely help with either providing the needed information. I've created a ticket to look into adding this to the library underneath (https://jongsoftdev.atlassian.net/browse/YA-11) as it is not part of home assistant. Once the library supports it I can update home assistant to add support..

**Comment by klaasnicolaas** [comment]
Hi there @vpathuis 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

But to answer you question, you fill in the IP address of your Youless device.

./Klaas

**Comment by vpathuis** [comment]
Tnx for redirecting me. It's both documentation and an issue. But mainly an issue apparently :)

**Comment by klaasnicolaas** [comment]
Not being able to connect to the IP is clearly an issue for the integration in core.

Regarding the ambiguity of what is meant by `host`. Host is a typical term in the IT world to indicate an IP of a device you want to communicate with. And this term is also used throughout the website for many integrations.
