### ISSUE TITLE
Documentation for Gas Usage Card missing

### ISSUE THREAD

**Issue by jelmerkk** [home-assistant/home-assistant.github.io#19188]
### Feedback

With the addition of the gas usage graph in the energy dashboard, I would expect it also pops up here to be include in other dashboards. 

### URL

https://www.home-assistant.io/lovelace/energy/

### Version

2021.9.1

**Comment by jelmerkk** [comment]
Thanks @klaasnicolaas still learning how to contribute instead of complain ;)

**Comment by klaasnicolaas** [comment]
Well you can keep it open 😉
