### ISSUE TITLE
Smart Meter Texas Integration not working with Energy Dashboard

### ISSUE THREAD

**Issue by jdisom424** [home-assistant/home-assistant.github.io#19180]
### Feedback

I’m unable to use Smart Meter Texas with the Home Assistant Energy Dashboard. It does not show up under energy configurations for consumed energy.

### URL

https://www.home-assistant.io/integrations/smart_meter_texas/

### Version

2021.9.1

**Comment by klaasnicolaas** [comment]
Hi there @jdisom424 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
