### ISSUE TITLE
Host required

### ISSUE THREAD

**Issue by DotNet2Web** [home-assistant/home-assistant.github.io#19184]
### Feedback

Thanks for creating a P1 integration for homeassistant.

I was trying to add it to my homeassistant setup, the integration asks for a host. When I add my host, url of the homeassistant server or the ip address of the server, with or without the ports. 

The integrations sends a message that it couldnt connect.

In the documentation https://www.home-assistant.io/integrations/p1_monitor/ I cant find what you mean by host and what value should be entered. 

Can you help me (us) out?

Thanks in advance

### URL

https://www.home-assistant.io/integrations/p1_monitor/

### Version

2021.9.1

**Comment by klaasnicolaas** [comment]
Hi there @DotNet2Web 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

Ps. But to answer your question anyway, `host` is the ip address of your P1 Monitor device.

./Klaas
