### ISSUE TITLE
TP-Link Kasa - Alert wording doesn't match TP-links latest post

### ISSUE THREAD

**Issue by philr-biz** [home-assistant/home-assistant.github.io#19185]
### Feedback

The [alert](https://alerts.home-assistant.io/#tplink.markdown) linked to from the tplink integration docs states:

> TP-Link's latest firmware for Kasa Smart Home devices closes the port (9999) previously used for local control, rendering Home Assistant unable to communicate with these devices.

This wording suggests this breaking change affects all Kasa Smart Home devices.

The [post](https://community.tp-link.com/en/smart-home/forum/topic/239364) on TP-Link's community forum linked to from the alert states:

> In the latest Kasa firmware release, we upgraded the local communication authentication method for the two smart sockets HS100(UK)4.1 and HS110(UK)4.1 ONLY (Other models and hardware versions would not be affected) to prevent local communication security risks.

This clearly suggests the breaking change only affects the HS100 and HS110 models.

Which statement is true?!

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.9.1

**Comment by rytilahti** [comment]
Afaik the firmware using authentication has been only seen on a limited number of models, so I'd assume that the statement found on the tplink forums is correct. Maybe it's worth updating the alert accordingly?
