### ISSUE TITLE
Mention `scan_interval` in RESTful Sensor documentation?

### ISSUE THREAD

**Issue by ast0815** [home-assistant/home-assistant.github.io#19181]
### Feedback

I was looking for a way to change the polling frequency for the RESTful sensor to reduce the load I put on someone else's server. The documentation makes no mention of it except for a line in one of the example, but `scan_interval` looks like it might be doing what I want, though I am not sure. At least the configuration works with it specified.

So I guess it should be explained in the documentation, or removed from that one example, if it should not be used for whatever reason.

### URL

https://www.home-assistant.io/integrations/sensor.rest/

### Version

2021.9.1

**Comment by ludeeus** [comment]
This option applies to all polling platforms, and is therefor documented globally instead of on each platform <https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval>

**Comment by ast0815** [comment]
Ah, I see. Maybe it is worth it linking to the documentation of the platform options then? Like you can also automatically link to parent class documentation in Doxygen. In any case, thanks for the clarification!

**Comment by ludeeus** [comment]
I don't see a need to link it from every integrations that provides polling platforms, IMO this is documented correctly just the way it is.
This type of configuration is also considered legacy, and is gradually being phased out.

**Comment by frenck** [comment]
I agree with Ludeeus on this one, therefore closing this issue.

Nevertheless, thank you for providing feedback 👍
