### ISSUE TITLE
Printing (on paper) from home-assistant.io

### ISSUE THREAD

**Issue by foxsam21** [home-assistant/home-assistant.github.io#19183]
### Feedback

When trying to print from https://www.home-assistant.io/docs/ it only prints what is currently displayed on the screen not the whole webpage.

### URL

https://www.home-assistant.io/docs/blueprint/tutorial/

### Additional information

I am using google chrome on linux mint but asking around it seems I am not the only one having this issue.

**Comment by frenck** [comment]
Please consider the environment by not printing

**Comment by foxsam21** [comment]
While I do appreciate the environment and don't usually print, there are times that there is an overwhelming need for a hard copy of some instructions or the sort.
