### ISSUE TITLE
LG WebOs integration

### ISSUE THREAD

**Issue by ZunaidPatel** [home-assistant/home-assistant.github.io#19195]
### Feedback

Turn on Lan integration no longer works
![image](https://user-images.githubusercontent.com/90052441/132054419-d1e005bb-598b-4d49-b255-a891d82c1060.png)

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2021.9.2

**Comment by ludeeus** [comment]
For issues with integrations please fill out this template <https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml>. Thanks :+1:
