### ISSUE TITLE
Canceled status in HA not matching status on bahn.de

### ISSUE THREAD

**Issue by herrzettpunkt** [home-assistant/home-assistant.github.io#19198]
### Feedback

I just noticed that the canceled status in the deutsche_bahn sensor does not match the status on bahn.de. Deutsche Bahn is currently on strike in Germany and many trains are canceled.

<img width="359" alt="Bildschirmfoto 2021-09-04 um 00 14 22" src="https://user-images.githubusercontent.com/89742641/132070491-9bd7373c-9a89-4bc5-976a-66c8a18e6c87.png">
<img width="481" alt="Bildschirmfoto 2021-09-04 um 00 15 43" src="https://user-images.githubusercontent.com/89742641/132070506-1644a2a7-1b06-4ffb-af1b-d5d55b50ccfe.png">

### URL

https://www.home-assistant.io/integrations/deutsche_bahn/

### Version

2021.9.2

**Comment by ludeeus** [comment]
Hi there :wave: 

It seems like you wanted to report an issue with integration, this is not the place for that, this is for feedback for the documentation.

To report issues with integrations, please use this issue tracker <https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc>
