### ISSUE TITLE
Energy consumption feature

### ISSUE THREAD

**Issue by tescher** [home-assistant/home-assistant.github.io#19205]
### Feedback

Looks like there is a new Energy Consumption option in Home Assistant (as of 2021.9.x). But, the documentation talks about integrating devices that measure kW, when the new feature requires kWh measurements. Where is the documentation on how to convert from one to the other? Templating?

### URL

https://www.home-assistant.io/docs/energy/

### Version

2021.9.2

**Comment by erffrfez** [comment]
Hi tescher - this is not a full answer, just a note in passing that might help you.
there is a small conflict in the naming - there are 'integrations' that are addons that can be enabled in HA, and those are not the 'integrations' that are meant in this energy consumption portion of the app. That one is 'integrate' in the math definition as in 'find the area under the curve'
To get from a sensor that measures W (power) to one that measures kWh (energy) refer to this:
https://www.home-assistant.io/integrations/integration/#energy

**Comment by tescher** [comment]
I created these as integration sensors, and they show up in my entities list, but the new Energy module in HA still doesn't recognize them as a "statistic". What is missing?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
