### ISSUE TITLE
Clarify how to get token

### ISSUE THREAD

**Issue by quillerc** [home-assistant/home-assistant.github.io#19202]
### Feedback

The manual installation method requires a token, which the interface says is optional but is actually required. It would be nice if the instructions here explained how to generate or obtain the token from the Plex media server.

### URL

https://www.home-assistant.io/integrations/plex/

### Version

2021.9.2

**Comment by jjlawren** [comment]
The token is optional if the server is unclaimed. This is very uncommon, but that's the reason it's not required.

The standard Plex config flow will obtain a new dedicated token which is exclusive to the HA installation. The old method of borrowing a key from a browser session is a hacky method which is not recommended. The manual configuration is available as a fallback method for advanced use-cases where the automatic flow will not work for some reason.

If you have a scenario where a manual configuration is the only solution, please open an issue on `core` and I'll do my best to address it.
