### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by nostradada** [home-assistant/home-assistant.github.io#19203]
### Feedback

Hello,
How to configure the integration?
I have tried all combinations of Id, name and ip

### URL

https://www.home-assistant.io/integrations/p1_monitor/

### Version

2021.9.2

**Comment by klaasnicolaas** [comment]
Hi there @nostradada 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Ps. You fill in the IP address of the device that runs P1Mon.

Thanks! 👍

./Klaas
