### ISSUE TITLE
Not Working from integrations

### ISSUE THREAD

**Issue by mar72kuss** [home-assistant/home-assistant.github.io#19206]
### Feedback

it says impossible to load current flux 

### URL

https://www.home-assistant.io/integrations/tractive/

### Version

2021.9.2

**Comment by klaasnicolaas** [comment]
Hi there @mar72kuss 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
