### ISSUE TITLE
Full text of name not showing

### ISSUE THREAD

**Issue by ColinRobbins** [home-assistant/home-assistant.github.io#19209]
### Feedback

It would be good if the name of the entity showed correctly.
In the documented example, it shows “orative lights” with the start of the text omitted.

### URL

https://www.home-assistant.io/lovelace/history-graph/

### Version

2021.9.2

**Comment by ludeeus** [comment]
Can you open a bug report in the frontend repo?

https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug&template=bug_report.yml

**Comment by ColinRobbins** [comment]
Done: https://github.com/home-assistant/frontend/issues/9955
