### ISSUE TITLE
Balena Etcher; does not work

### ISSUE THREAD

**Issue by aszajlai** [home-assistant/home-assistant.github.io#19219]
### Feedback

Using a M1 Mac and Balena Etcher from a regular account it will not write the the USB key that holds the 32 GB SD micro.  I tried to write the file via a terminal window, was not able to find anything.  I was able to use the Pi OS writer to create the Home Assistant image to the card.  Not sure why the Etcher does not correctly handle the priv request, the one to write the Pi OS was able to correctly ask and prompt the user for details to write the image.

https://www.raspberrypi.org/software/

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.9.3

### Additional information

Was not sure how to help fix or comment that I was not able to complete the install based on what I found on the page.  So started here.

**Comment by ludeeus** [comment]
What version of etcher did you use?
It seems that 1.5.122 included a fix for this
