### ISSUE TITLE
s3 broadlink hub

### ISSUE THREAD

**Issue by blasserre** [home-assistant/home-assistant.github.io#19224]
### Feedback

Please add support for s3 hub 

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2021.9.3

**Comment by ludeeus** [comment]
Hi there :wave: 

For feature requests please open those on the 
[forums](https://community.home-assistant.io/). Thanks :+1:

**Comment by blasserre** [comment]
Sorry I am new in this I do not know where to ask them to do the Hub S3 compatible
