### ISSUE TITLE
Avatto thermostat

### ISSUE THREAD

**Issue by vikts83** [home-assistant/home-assistant.github.io#19220]
### Feedback

Hello. 
I have Avatto thermostat:
https://aliexpress.ru/item/1005001605377377.html?spm=a2g0o.store_pc_allProduct.8148356.44.62294f93li9P6T

Tuya integration found it, but i can just switch on and switch off it. 
I can’t receive information about temperature, can’t send any command for set temperature.

What problem may be with it. 

Thank you
BR 
Viktor

Device info (please complete the following information, which can be found in log):
like this:
{
"result": {
"active_time": 1622982586,
"biz_type": 0,
"category": "wk",
"create_time": 1620471936,
"icon": "smart/icon/ay1547110530245tcZgC/4f30abc26e40759cfde4ce336c4bbfbe.png",
"id": "xxxxxxxxxxxxxxxxxxxxxxxx",
"ip": "xxx.xxx.xxx.xxx",
"lat": "59.47102065939445",
"local_key": "xxxxxxxxxxxxxxxxxx",
"lon": "24.96008691429992",
"model": "ME102",
"name": "Cabinet",
"online": true,
"owner_id": "31921097",
"product_id": "pe7fxnkhp2dcvlh6",
"product_name": "Smart thermostats",
"status": [
{
"code": "switch",
"value": true
},
{
"code": "mode",
"value": "manual"
},
{
"code": "temp_set",
"value": 20
},
{
"code": "temp_set_f",
"value": 32
},
{
"code": "upper_temp_f",
"value": 86
},
{
"code": "upper_temp",
"value": 35
},
{
"code": "lower_temp_f",
"value": 41
},
{
"code": "temp_unit_convert",
"value": "c"
},
{
"code": "temp_current",
"value": 23
},
{
"code": "lower_temp",
"value": 5
},
{
"code": "temp_correction",
"value": -3
},
{
"code": "temp_current_f",
"value": 32
},
{
"code": "valve_state",
"value": "close"
},
{
"code": "factory_reset",
"value": false
},
{
"code": "child_lock",
"value": false
},
{
"code": "sensor_choose",
"value": "in"
}
],
"sub": false,
"time_zone": "+02:00",
"uid": "eu1622981141157WHaNq",
"update_time": 1630596713,
"uuid": "68773733e868e756ae80"
},
"success": true,
"t": 1630871016624
}

**Comment by ludeeus** [comment]
Hi there :wave: 

It seems you are trying to report an issue with integration, but this is the place to provide feedback for the documentation.

This is the issue tracker for integrations: <https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22integration%3A+tuya%22>
