### ISSUE TITLE
make it more user friendly 

### ISSUE THREAD

**Issue by ralong777** [home-assistant/home-assistant.github.io#19221]
### Feedback

Please add info how to edit this config. I need to remove the DHCP and I don't know how.
I have this issue:
https://community.home-assistant.io/t/ha-spamming-ptr-dns-lookups/143687/55

### URL

https://www.home-assistant.io/integrations/default_config/

### Version

2021.9.3

**Comment by ludeeus** [comment]
You can't edit it, so there is nothing to document.
For feature requests please raise those on the [forums](https://community.home-assistant.io/). Thanks :+1:
