### ISSUE TITLE
Shelly GU10 Bulb - DUO RGBW Version

### ISSUE THREAD

**Issue by thesebastianf** [home-assistant/home-assistant.github.io#19230]
### Feedback

The RGB Version of the the DUO GU10 bulb does not allow to set colors

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.9.3

**Comment by thecode** [comment]
This repo is for documentation issues, for bugs you should open a report at the core repository, there is already an open issue for your problem, for now switch the bulb to color mode via the device web or downgrade firmware.
https://github.com/home-assistant/core/issues/55582
