### ISSUE TITLE
Long term statistics information not yet in Documentation

### ISSUE THREAD

**Issue by johanf85** [home-assistant/home-assistant.github.io#19244]
### Feedback

In version 2021.8 en 2021.9 changes were made to the statistics so that they can be stored long term. Maybe I haven't looked well enough, but I think the information does need to be updated on the statistics integration user documentation.

In the release party video of 2021.8 the website data.home-assisant.io was discussed and there I found this page: https://www.home-assistant.io/integrations/statistics/

Also this page is available: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

I think a lot of information on both pages can be added to the user documentation on https://www.home-assistant.io/integrations/statistics/ . I considered making a PR, but I don't have enough knowledge about how the new statistics integration is set up right now.

### URL

https://www.home-assistant.io/integrations/statistics/

**Comment by frenck** [comment]
We consider these properties not user-facing, thus it is not part of the end-user documentation. If an integration doesn't correctly support long-term statistics or things like the energy dashboard, we consider that a bug. In that case, an issue can be filed to get it resolved.

Thanks for the feedback though! 👍

**Comment by johanf85** [comment]
Allright, understood. 

Good to see you back, saw some messages by you from the hospital. Beterschap gewenst!
