### ISSUE TITLE
broken link on "Energy Cards" page

### ISSUE THREAD

**Issue by yann1420** [home-assistant/home-assistant.github.io#19245]
### Feedback

I found a broken link on https://www.home-assistant.io/lovelace/energy .
It concerns the text  **energy configuration** page that points to a non-existing https://my.home-assistant.io/redirect/config_energy

### URL

https://www.home-assistant.io/lovelace/energy/

### Version

2021.9.4

**Comment by ludeeus** [comment]
That both exists and is working?

**Comment by yann1420** [comment]
this one exists https://www.home-assistant.io/lovelace/energy 
but it points to https://my.home-assistant.io/redirect/config_energy and that one does not exist. I.e. not with that URL

**Comment by ludeeus** [comment]
Not the same thing, the first is more documentation, while the second links to "my" which can redirect you to your config panel
![Screenshot from 2021-09-07 17-36-08](https://user-images.githubusercontent.com/15093472/132372746-be9538e5-fe1e-4c53-8fb3-85b5740207db.png)

**Comment by yann1420** [comment]
So, if I understand correctly I should point to **https://myduckdns.duckdns.org:PORTNUMBER/redirect/config_energy** and should end-up here **https://myduckdns.duckdns.org:PORTNUMBER/config/energy** ?
IOW, I should replace the first bit with my URL . If that is the case, it is not working for me.

**Comment by ludeeus** [comment]
Then you are missing `default_config` or `my`in your config <https://www.home-assistant.io/integrations/my/>
