### ISSUE TITLE
Days To expire

### ISSUE THREAD

**Issue by nikolas22t** [home-assistant/home-assistant.github.io#19242]
### Feedback

Its better to show just days to expire , so you can use as badges or have the option to display date as it is now or the days left to expire.

### URL

https://www.home-assistant.io/integrations/cert_expiry/

### Version

2021.9.4

**Comment by ludeeus** [comment]
The Cert Expiry Timestamp sensor is using a timestamp class, which means that in lovelace you will get xx days where xx represent the days until expiration.
