### ISSUE TITLE
[unique_id] is an invalid option for [light.group]. 

### ISSUE THREAD

**Issue by andriiguthub** [home-assistant/home-assistant.github.io#19259]
### Feedback

when specifying 
unique_id string (optional)
An ID that uniquely identifies this light group. If two lights have the same unique ID, Home Assistant will raise an error.
got an issue
Invalid config for [light.group]: [unique_id] is an invalid option for [light.group]. Check: light.group->unique_id. (See ?, line ?). 

issue resolves when I remove unique_id line

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2021.9.4

**Comment by ludeeus** [comment]
If 2 lights have the same unique ID, it's not unique.
The unique ID needs to be unique for that platform.

**Comment by emontnemery** [comment]
@andylebedev please share the full config of the light group

**Comment by frenck** [comment]
I've checked the documentation, it seems to be correct and matches the latest stable release of Home Assistant.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
