### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by monoboy-hh** [home-assistant/home-assistant.github.io#19258]
### Feedback

How can one remove the menu entry from the left vertical menu?

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.9.4

**Comment by ludeeus** [comment]
Click and hold the "Home Assistant" text, or go to your userprofile and click on "EDIT"
![Screenshot from 2021-09-08 08-03-54](https://user-images.githubusercontent.com/15093472/132454992-2161d42d-6a44-41dc-925a-0f997fa5cb5b.png)

**Comment by monoboy-hh** [comment]
Great tip, thank you! Wasn't aware of click and hold!
However, I have to tell every user to do that? But I guess that's how things are ...
