### ISSUE TITLE
More details for recovering from failed update using Console command

### ISSUE THREAD

**Issue by newkton1** [home-assistant/home-assistant.github.io#19256]
### Feedback

I had a failed update to 2021.9.1 on a RPi 3b but can still access Console screen by connecting monitor and keyboard to RPi.
I am sitting here looking at ha>
but your pages give no information (that works) on how to recover from this condition. In fact, I can only find ONE place that mentions Console at the whole site!
Am I missing something somewhere or does this help just not exist?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.9.4

**Comment by ludeeus** [comment]
The CLI has a section here <https://www.home-assistant.io/common-tasks/os/#home-assistant-via-the-command-line>

**Comment by newkton1** [comment]
![IMG_1341](https://user-images.githubusercontent.com/13056263/132453263-17da11ef-3d98-4b1b-b8b1-81c83564c660.JPG)
Thanks Joakim.  Yes I know these CLI commands BUT some of them don’t work from the Console prompt ha>

For example I can use:
ha> core info

and it gives me the attached screen OK.



But

ha> core update —version 2021.9.4 

Does nothing!

Any ideas why would be appreciated!

Best regards

Robert

**Comment by ludeeus** [comment]
`su logs`

**Comment by newkton1** [comment]
Sorry ludeeus but that reply is a bit too cryptic for me to understand what you mean. Could you expand the meaning a little please.

**Comment by ludeeus** [comment]
`su logs` display logs.
I suggest you join the [discord](https://discord.gg/c5DvZ4e) server to get help with this.

**Comment by newkton1** [comment]
Thanks for advice: posted problem twice at Discord and nobody came back; posted at Twitter Home Assistant thread too and nobody came back.
Not much else to try before nuking drive and starting over.

**Comment by ludeeus** [comment]
Try again and make sure to use the #homeassistant_os channel
