### ISSUE TITLE
name: not working

### ISSUE THREAD

**Issue by maceace** [home-assistant/home-assistant.github.io#19250]
### Feedback

name: not working

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.9.4

**Comment by ludeeus** [comment]
`name` is a valid option, so if that's not working, please raise an issue with the integration.
https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22integration%3A+utility_meter%22
