### ISSUE TITLE
Missing `white_value_state_topic` property for Light Default Schema

### ISSUE THREAD

**Issue by LordMike** [home-assistant/home-assistant.github.io#19265]
### Feedback

In the `default schema`, the following text exists:

```
color_temp_state_topic string (optional)
The MQTT topic subscribed to receive color temperature state updates. If the light also supports setting colors, also define a white_value_state_topic.
```

But no `white_value_state_topic` is described.

### URL

https://www.home-assistant.io/integrations/light.mqtt/#default-schema---configuration

### Version

2021.9.4

**Comment by emontnemery** [comment]
This is a mistake in the documentation, thanks for reporting 👍 

Note: Brightness of a light is controlled by brightness related topics. `white_value` has been deprecated and support for it will be removed completely during the last quarter of 2021.

**Comment by LordMike** [comment]
Cool - I'm subscribing to updates, so I'll see all changes in due time :)
