### ISSUE TITLE
'optimistic' property on MQTT Covers integration is a string?

### ISSUE THREAD

**Issue by LordMike** [home-assistant/home-assistant.github.io#19263]
### Feedback

Some integrations use strings for their "optimistic" value, while others use booleans. But it seems they all should be booleans.

While mapping out the models for the MQTT discovery docs, I found these to have string "optimistic" fields:

* Cover
* Light (Template)
* Lock

While these have boolean optimistic values:

* Cover (TiltOptimistic)
* Fan
* Light (Default, Json)
* Number
* Select
* Switch

This could probably be standardized :)

### URL

https://www.home-assistant.io/integrations/cover.mqtt/

### Version

2021.9.4

**Comment by emontnemery** [comment]
The documentation is incorrect, these are all treated as boolean in the code.
Thanks for reporting 👍
