### ISSUE TITLE
List of offending contianers not found in Supervisor log

### ISSUE THREAD

**Issue by dm7500** [home-assistant/home-assistant.github.io#19276]
### Feedback

The documentation states that if my system is marked as unhealthy due to containers known to cause issues, the list of offending containers will be listed in the supervisor log. 

I'm not seeing this list at all in the log. Am I missing something?

### URL

https://www.home-assistant.io/more-info/unsupported/container

**Comment by ludeeus** [comment]
It will be in the supervisor log after startup of it.

**Comment by dm7500** [comment]
Not seeing anything about it after a supervisor restart. Only the below lines.

```
21-09-09 09:52:30 WARNING (MainThread) [supervisor.core] System running in a unsupported environment!
21-09-09 09:52:30 CRITICAL (MainThread) [supervisor.core] System is running in an unhealthy state and needs manual intervention!
```

**Comment by ludeeus** [comment]
Then you should power off and reinstall your host OS, someone or something is messing with your environment. there should be a lot more logs.
