### ISSUE TITLE
Howto?  Integrating individual device energy usage

### ISSUE THREAD

**Issue by yann1420** [home-assistant/home-assistant.github.io#19270]
### Feedback

Hello team,
I'm trying to add a couple of **smart plugs** to my **energy dashboard** .
What attributes/properties should the smart plug have in order to be recognized as a smart plug that can be used in the **E-dashboard** ?

IMHO this should be part of the documentation.

Thanks in advance, Yann 

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2021.9.4

**Comment by NightFalcon650** [comment]
I also try to add individual devices like my shelly plugs, dimmers, etc. The only problemen is that they don't show up in the energy settings page.
How is this possible and what do I have to do to get it working?

**Comment by frenck** [comment]
> What attributes/properties should the smart plug have in order to be recognized as a smart plug that can be used in the E-dashboard ?

> IMHO this should be part of the documentation.

The device should report its energy usage (which is kinda implied as it is the energy dashboard). Furthermore, the integration that provides those entities needs to support it. If not, you can open up an issue for that specific integration. (This is also linked when trying to add a device to the energy dashboard).

This is not a documentation issue in my opinion.

Nevertheless, thanks for taking the time to provide feedback 👍 

../Frenck
