### ISSUE TITLE
YAML editing, on Linux

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19285]
### Feedback

Suggestions are to use visual studio to edit e.g. configuration.yaml
For Linux users, emacs has a yaml mode, https://melpa.org/#/yaml-mode
is this acceptable / usable (perhaps via copy / paste) please?

### URL

https://www.home-assistant.io/getting-started/configuration/

### Version

2021.9.5

**Comment by ludeeus** [comment]
If you use Linux and/or emacs you know what you are doing, these documentations are for users that do not.
Before you open more issues, I suggest you join the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e) server
