### ISSUE TITLE
Google doorbell (2021)

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19283]
### Feedback

Poor naming, but Googles new doorbell (Aug '21) is (somehow) different from the Nest doorbell.
Not found under 'Add integration'

I'm trying to set up other Google devices (Oddly under Google room cast) - e.g. speaker, to sound when
doorbell pressed. 

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2021.9.5

**Comment by ludeeus** [comment]
And what do you suggest should change on the <https://www.home-assistant.io/getting-started/onboarding/> documentation page?

**Comment by dpawson** [comment]
I think the addition should be on https://www.home-assistant.io/installation/raspberrypi
  Suggest 
Within a few minutes you will be able to reach Home Assistant on homeassistant.local:8123 on another computer, connected via
the same network, to the home assistant.
