### ISSUE TITLE
Load media file into /media?

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19284]
### Feedback

How to transfer a file (mp3) from connected computer to ha please?
Nothing seen on /integrations/media_source?

### URL

https://www.home-assistant.io/integrations/media_source/

### Version

2021.9.5

**Comment by frenck** [comment]
As described here: <https://www.home-assistant.io/integrations/media_source/#local-media>

> Home Assistant OS and Supervised users can access this folder by using, for example, the Samba add-on. Users of Home Assistant Container can mount a volume of their choice to /media.

> If you are a Home Assistant Core user, the default directory called is called media under the configuration path (where your configuration.yaml is located).
