### ISSUE TITLE
Slight fix to "effects"

### ISSUE THREAD

**Issue by jds11111** [home-assistant/home-assistant.github.io#19288]
### Feedback

I don't believe that the commas should be there after each of the effects. My Visual Studo editor complained about them. At any rate, removing them passes the HA configuration check, and it works fine without them.

### URL

https://www.home-assistant.io/integrations/marytts/

### Version

2021.9.5

**Comment by frenck** [comment]
Thanks for reporting this one @jds11111 👍 

I've opened up a PR to adjust this
