### ISSUE TITLE
New install, no gui

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19282]
### Feedback

New install from web, following instructions. Running on rpi 4.
On boot, runs 'ha' only. No gui.
https://www.home-assistant.io/docs/configuration/  configuration seems to assume either gui, or Linux alike commands available. None found?

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2021.9.5

**Comment by ludeeus** [comment]
Which parts suggest that?

Did you skip step 4 here maybe? <https://www.home-assistant.io/installation/raspberrypi#start-up-your-raspberry-pi>

**Comment by dpawson** [comment]
Resolved:
Reading  https://www.home-assistant.io/getting-started/onboarding/
I was setting up a Raspberry Pi, assumed (wrongly) this gui would appear on the rpi screen?
Wrong - but nothing in the docs to indicate I should use a browser on another computer to connect
to the rpi? Perhaps make this clear?

Leaves a question, can I now (having installed ha) reboot headless, remove keyboard, screen and mouse
to control the ha via my browser please?

**Comment by ludeeus** [comment]
yes, that's how the OS is designed to be used.
