### ISSUE TITLE
the workaround doesn't work anymore?

### ISSUE THREAD

**Issue by isaacandy** [home-assistant/home-assistant.github.io#19296]
### Feedback

i get this when running the apt-add-repository

`pi@iznd-node03:~ $ sudo add-apt-repository ppa:jonathonf/ffmpeg-4
 Backport of FFmpeg 4 and associated libraries. Now includes AOM/AV1 support!

FDK AAC is not compatible with GPL and FFmpeg can't be redistributed with it included. Please don't ask for it to be added to this public PPA.

---

PPA supporters:

BigBlueButton (https://bigbluebutton.org)

---

Donate to FFMPEG: https://ffmpeg.org/donations.html
Donate to Debian: https://www.debian.org/donations
Donate to this PPA: https://ko-fi.com/jonathonf
 More info: https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpze6o9bai/pubring.gpg' created
gpg: /tmp/tmpze6o9bai/trustdb.gpg: trustdb created
gpg: key 8CF63AD3F06FC659: public key "Launchpad PPA for J Fernyhough" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.`

### URL

https://www.home-assistant.io/integrations/stream/

### Version

2021.9.5

**Comment by allenporter** [comment]
@isaacandy Not sure that we'll be able to add much help without a lot more details for your particular system (e.g. linux distribution and version, steps to reproduce from a fresh install, etc).   Really I'd just search stackoverflow or whatever e.g. behalf https://askubuntu.com/questions/1054697/gpg-no-valid-openpgp-data-found-in-ubuntu

**Comment by isaacandy** [comment]
noted with thanks.
I was just sharing the issue & was wondering whether can I update the workaround on the site or do I perform the standard processes by raising an issue first.
