### ISSUE TITLE
ESPHome getting started out of date

### ISSUE THREAD

**Issue by kohekohebigsky** [home-assistant/home-assistant.github.io#19292]
### Feedback

image of the welcome page is out of date.
Please add more detail on how to connect to the home-assistant ESP web page to do the initial device download over a secure https connection.
The addon just states that there is limited functionality.
Example: x86 metal with Ubuntu 20.04LTS OS running Home-assistant OS in a Virtual box VM with Firefox browser.
browsing from Firefox my connection is http://homeassistant.local:8123/a0d7b954_esphome/dashboard
how does a newbee get a https connection on the same box? 
Not trying to access HA from outside the LAN.

### URL

https://www.home-assistant.io/integrations/esphome/

### Version

2021.9.5

**Comment by jesserockz** [comment]
Setting up Home Assistant with SSL is out of scope for the ESPHome documentation especially if you are not planning to access outside LAN.

**But** the add-on documentation itself gives you a kickstart on how to set up ssl for just the ESPHome add-on with a self signed certificate:

[![Screenshot from 2021-09-11 11-17-22](https://user-images.githubusercontent.com/3060199/132927050-2b0ef3dc-1663-441f-b0c2-db6bb8a38e04.png)](https://github.com/esphome/hassio/blob/main/esphome/DOCS.md)

**Comment by jesserockz** [comment]
If you continue to have issues, please check for or create an issue in the [ESPHome issue tracker](https://github.com/esphome/issues/issues) as this is not related to HA documentation or the HA integration.
