### ISSUE TITLE
Integration into brand new energy dashboard

### ISSUE THREAD

**Issue by JohanHardy** [home-assistant/home-assistant.github.io#19295]
### Feedback

Dear Guy's,

Would be great if IamMeter sensors are integrated into the the new Energy Dashboard of the HASS.
Can't find a way to add my grid meter into the dashboard .. need help!

Thanks in advance !
Johan

### URL

https://www.home-assistant.io/integrations/iammeter/

### Version

2021.9.5

**Comment by ludeeus** [comment]
The integration needs to add support for it to be used there.
Please raise a feature request for that on the forums. Thanks :+1: 
https://community.home-assistant.io/c/feature-requests/13
