### ISSUE TITLE
Recorder - Custom database engines is not updated according to Breaking Changes 2021.7

### ISSUE THREAD

**Issue by pixeldoc2000** [home-assistant/home-assistant.github.io#19303]
### Feedback

"Custom database engines" do not include Note about changed db_url -> required URL Encoding for @ sign introduced in 2021-7:
https://www.home-assistant.io/blog/2021/07/07/release-20217/#breaking-changes

The underlying library that is used for the database connections, has been updated. This fixes a bug, that might be a breaking change for you.

If you use an @ in your database username or password, you will have to adjust your database connection string to use %40 instead.

Database connection strings are considered URLs, thus special characters need to be encoded. %40 is the URL encoded version of @.

### URL

https://www.home-assistant.io/integrations/recorder/#custom-database-engines

### Version

2021.9.5

**Comment by ludeeus** [comment]
Not a single of those use @ as part of the username or password?

**Comment by pixeldoc2000** [comment]
I am sorry, is misread the Breaking Change. I though we had to replace the @ between username:password@dbserver.

My bad!
