### ISSUE TITLE
Vallox Integration additional feature: Set Supply air temperature for profile

### ISSUE THREAD

**Issue by PhillyGilly** [home-assistant/home-assistant.github.io#19300]
### Feedback

The existing integration allows  the fan speed for profiles to be set e.g. VALLOX.SET_PROFILE_FAN_SPEED_HOME.
It would be useful if the supply air temperature for profiles could be set to a value between 5C and 25C by a new function e.g. VALLOX.SET_SUPPLY_AIR_TEMPERATURE_HOME and if the HR (heat recovery) cell status could be returned as "HR cell bypass" or  "Heat recovery". This would make the HA integration provide the same functionality as the Adroit Home web interface on my CV145 unit, and enable me to automate switching between "winter mode" when I want the air supply temperature setting to be maximised and "summer mode" when I want the air supply temperature setting to be 18C to enable to MVHR to provide daytime cooling.
Overview
![Untitled](https://user-images.githubusercontent.com/56273663/132955476-2e91b558-4950-4120-abc3-e80e2a38a9e6.png)
Settings screen
![Untitled2](https://user-images.githubusercontent.com/56273663/132955514-15e95384-0aa6-4308-b0f5-8559b3612f43.png)

### URL

https://www.home-assistant.io/integrations/vallox/

### Version

2021.9.5

**Comment by klaasnicolaas** [comment]
Hi there @PhillyGilly 👋

It seems like you want to report an feature request with an Home Assistant integration, however, you have submitted documentation feedback instead. Please make a freature request topic on the Home Assistant community forum instead:

https://community.home-assistant.io/c/feature-requests/13

Thanks! 👍

./Klaas
