### ISSUE TITLE
The HA Tesla account problem 

### ISSUE THREAD

**Issue by iambbbb** [home-assistant/home-assistant.github.io#19316]
### Feedback

Hello I’m Calvin. The Tesla China account Cannot login now.  Thank you for helping 

### URL

https://www.home-assistant.io/integrations/tesla/

### Version

2021.9.5

### Additional information

I don’t know why the account cannot login now

**Comment by omelhus** [comment]
The Tesla component is coming out of core. Remove it and install the custom component from https://github.com/alandtse/tesla or find it on HACS.
