### ISSUE TITLE
Newbie info for templating needed

### ISSUE THREAD

**Issue by cjj** [home-assistant/home-assistant.github.io#19323]
### Feedback

I just went through the process of creating my first template, and it was a really basic one...adding the value of two sensors together. It involved a LOT of guess-and-check and reaching out on the discord channel. I did not feel like I had a clue how to actually do this based on the documentation. 

Questions I can't answer from the docs (including Templating page and the Jinkx: 
* Why do I need the ">" in some "state" lines? Apparently "> -" is a thing too? 
* If I am adding two values...is this a number or a sensor? I guessed sensor just because of something I had read in the forums. 
* Is  this Regex format? Where do I go if I know zilch about regex? Are there any HA-specific details I need to know to use what I would find about generic regex? I looked at the jinja page but honestly couldn't tell how it relates to HA. 
* Why can't I just use 
state: "{{ states('sensor.energy_production_tomorrow')|float + states('sensor.energy_production_tomorrow_2')|float }}"
Seems logical! But apparently I have to give them a name before I can add them??

These are some confusions of a templating newbie. Hope this can give some ideas for additional basic pointers that can be added to the main docs so neophytes aren't so lost. Thanks!

### URL

https://www.home-assistant.io/integrations/template/

### Version

2021.9.5

**Comment by frenck** [comment]
> Why do I need the ">" in some "state" lines? Apparently "> -" is a thing too?

That is a YAML-related question and not about templates. Please consult documentation about YAML for more information on the delimiters YAML uses.

> If I am adding two values...is this a number or a sensor? I guessed sensor just because of something I had read in the forums.

Not sure what your question is...

> Is this Regex format? Where do I go if I know zilch about regex? Are there any HA-specific details I need to know to use what I would find about generic regex? I looked at the jinja page but honestly couldn't tell how it relates to HA.

Home Assistant can do/support regex in templates, however, we are not here to teach/learn about regex. There are tons of resources out there to learn you all about using regular expressions. This is not a template-related question either.

> Why can't I just use

That example looks ok, not sure what your question is there. It is probably missing context.


I'm sorry, but based on your questions I'm not sure what I could add/change here to help you, as per above I'm unsure about your questions or the question are not template-related.
