### ISSUE TITLE
shallow explanation

### ISSUE THREAD

**Issue by SHoogland** [home-assistant/home-assistant.github.io#19320]
### Feedback

"to be able to do everything it needs to do."
A small specification or example of the process/features that need privileged acces to the docker host would be very nice.
I have been running a docker home assistant image for almost a year without it, so I was curious what it would do and why its necessary.

### URL

https://www.home-assistant.io/more-info/unsupported/privileged/

### Version

2021.9.5

**Comment by SHoogland** [comment]
To add a little context to that, I got there via google, so it took me a while to realise on what kind of issue I landed (unsupported warning apparently) and I think this has to do with a docker install of home assistant.

*a few minutes later*

I learned about the difference between the home assistant container and the home assistant core in a container (I think I have used the latter for the past year)

Which makes me assume this article is about the home assistant container that needs to control/update the docker image its running, but that context would be nice up front 😅 😇

**Comment by ludeeus** [comment]
This is a help page that is only linked from inside the supervisor.
If you don't have a supervisor the content here does not apply to you

**Comment by SHoogland** [comment]
Fair, but than maybe don't let google index it 🙈

**Comment by ludeeus** [comment]
It starts out with:
> The Supervisor needs to have privileged access to the docker runtime
