### ISSUE TITLE
Setting for Serial EOL character

### ISSUE THREAD

**Issue by Wim-N** [home-assistant/home-assistant.github.io#19332]
### Feedback

Is it possible to add a parameter to set the EOL character that is being used in the serial sensor platform. It seems to to be a <LF> (0x0A) character. But a lot of devices are using a <CR> (0x0D) as a line termination character.
It would be nice to have a way of specifying that the serial sensor platform should use the <CR> (0x0D) as an EOL character.

### URL

https://www.home-assistant.io/integrations/serial/

### Version

2021.9.5

**Comment by frenck** [comment]
This integration does not support setting that.

**Comment by Wim-N** [comment]
I know, but can it be added?
