### ISSUE TITLE
Qubino Smart Meter

### ISSUE THREAD

**Issue by seidel77** [home-assistant/home-assistant.github.io#19333]
### Feedback

Hello, 
I would appreciate if you could make the[ Qubino Smart Meter 3 Phases](https://qubino.com/products/3-phase-smart-meter/#takecontrol) available in the new energy integration.
Shoudl you need any infos, just contact me.
Thanks for your great work !

### URL

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics.

### Version

2021.9.5

### Additional information

https://qubino.com/products/3-phase-smart-meter/#takecontrol
https://qubino.com/products/3-phase-smart-meter/smart-meter-3phase-tech/

**Comment by ludeeus** [comment]
For that to be possible it has to exist as an integration.
Feature requests for new integrations need to be opened on the forums. Thanks :+1:

**Comment by seidel77** [comment]
Hi, thanks for your super fast feedback - the integration exist through z-wave. Isn't it enought ? it needs to be a single integration (sorry for the dumb question)?

**Comment by ludeeus** [comment]
If that is the case open a bug report against the zwave integration <https://github.com/home-assistant/core/issues>

**Comment by seidel77** [comment]
Thanks !
