### ISSUE TITLE
Integration is broken for homekit

### ISSUE THREAD

**Issue by iloveicedgreentea** [home-assistant/home-assistant.github.io#19334]
### Feedback

I am hoping to use this integration plus the homebridge integration so I can automate my system with homekit. The problem is when a request to interface with the alarm is sent to HA, there is no pin sent so it will not work. Is there no way to store the pin somewhere and have it get sent instead of relying on user input? Homekit has no way of inputting a pin.

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2021.9.5

**Comment by iloveicedgreentea** [comment]
Nevermind... looks like user error. I had the "code" param set which, admittedly due to confusing documentation, is actually to protect the UI and not sent directly. 

I would suggest keeping the simplisafe and homekit labels on this for visibility in case someone else has this issue. Considering adding a sentence about the code param to the page as well. Working as expected now.

**Comment by bachya** [comment]
FYI, the use of this code is clearly explained when configuring it:

![image](https://user-images.githubusercontent.com/47216/133117721-d09d69c9-4c26-4a82-8830-46daed5a3421.jpeg)

Glad you're good to go!

**Comment by iloveicedgreentea** [comment]
Really wouldn't say that is "clear" if it causes user error :) "Used in Home Assistant UI" is extremely vague. Lots of things are used in the UI. That doesn't really indicate what it really does.

I created a PR to clarify what it does and how it can break homekit integration. https://github.com/home-assistant/home-assistant.io/pull/19335
