### ISSUE TITLE
Energy dashboard not showing anything even though I have a sensor set up to track my usage

### ISSUE THREAD

**Issue by tchesket** [home-assistant/home-assistant.github.io#19341]
### Feedback

The title pretty much says it. I set up a python script to get my current energy usage data in kWh from my provider's api. It is working fine, and the sensor shows the correct and current usage. I configured the energy dashboard to use that sensor to track usage, and manually set a price per kWh, but nothing shows up on the graph in the energy dashboard. Not sure what is going wrong here. 
![Screenshot_20210914-005011](https://user-images.githubusercontent.com/40137713/133202160-d3c4146d-5555-4523-abc9-3edeaa26ad3e.png)

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.9.5

### Additional information

![Screenshot_20210914-005121](https://user-images.githubusercontent.com/40137713/133202265-0bfefb67-e60b-40e8-bb0b-de79d38b3e6f.png)
![Screenshot_20210914-005209](https://user-images.githubusercontent.com/40137713/133202350-0f123dd4-e9d6-45ea-8528-ec474a5ab836.png)
![Screenshot_20210914-005227](https://user-images.githubusercontent.com/40137713/133202382-8feea3ac-92b9-43a8-aa81-366f54c014da.png)

**Comment by ludeeus** [comment]
Does it sound like you want to report an issue?
This tracker is for feedback on the documentation.

This is the place for issues: <https://github.com/home-assistant/core/issues>

**Comment by tchesket** [comment]
Oops, thank you, I will do that.
