### ISSUE TITLE
Issue with Plugwise Smile P1 and Energy Management HA - No Statistics Found

### ISSUE THREAD

**Issue by climbernl** [home-assistant/home-assistant.github.io#19348]
### Feedback

I've installed the Plugwise integration into HA and it works fine. But recently HA release the Energy Management dashbord. When I try to add the Plugwise S1 as a source for energy use data, it says that no statistics can be found. HA advices the developer of the integration to have a look at the following page:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

### URL

https://www.home-assistant.io/integrations/plugwise/

### Version

2021.9.5

**Comment by bouwew** [comment]
@climbernl please use the Plugwise-beta custom_component https://github.com/plugwise/plugwise-beta instead of the Core Plugwise component. The bug you are reporting has been solved in Plugwise-beta.

It will be solved too in Core Plugwise some time in the future, not very soon...

**Comment by frenck** [comment]
Hi there @climbernl 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
