### ISSUE TITLE
Wants to request an update of the ELIQ integration to work with HA energy metering.

### ISSUE THREAD

**Issue by Prahlus** [home-assistant/home-assistant.github.io#19342]
### Feedback

I want to request an update of the ELIQ integration to work with HA energy metering. Where do I go about todo that ?

### URL

https://www.home-assistant.io/integrations/eliqonline/

### Version

2021.9.5

**Comment by ludeeus** [comment]
That would be on the feature request section of the forum <https://community.home-assistant.io/> :+1:
