### ISSUE TITLE
Mqtt plug (Gosund)

### ISSUE THREAD

**Issue by thomy3k** [home-assistant/home-assistant.github.io#19350]
### Feedback

How is it possible to integrate Gosund Plugs for Energy usage into home assistant.

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2021.9.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
