### ISSUE TITLE
Docker GPSD documentation

### ISSUE THREAD

**Issue by kryptonitecb3** [home-assistant/home-assistant.github.io#19359]
### Feedback

I have been trying to get the docker image working without using network_mode: host, and privileged: true. The issue I ran in to was getting gpsd on my local machine to work with the home assistant docker image. After spending a few hours I was able to find a single post on an RPI forum about changing gpsd.socket so that GPSD would listen on all ports and not only 127.0.0.1 (https://www.raspberrypi.org/forums/viewtopic.php?t=174446). It would be helpful for future users to have this in the documentation.

In /etc/default/gpsd add '-G' to GPSD_OPTIONS (GPSD_OPTIONS="-G"). In /lib/systemd/system/gpsd.socket comment out the 127.0.0.1 and uncomment the 0.0.0.0 lines. Then restart GPSD, or reboot for the changes to take effect.

### URL

https://www.home-assistant.io/integrations/gpsd/

### Version

2021.9.5

### Additional information

/etc/default/gpsd
------------------------------------------------------------------------------------
# Devices gpsd should collect to at boot time.
# They need to be read/writeable, either by user gpsd or the group dialout.
DEVICES="/dev/ttyACM0"

# Other options you want to pass to gpsd
GPSD_OPTIONS="-G"
START_DAEMON="true"
USBAUTO="true"
GPSD_SOCKET="/var/run/gpsd.sock"
------------------------------------------------------------------------------------

/lib/systemd/system/gpsd.socket
------------------------------------------------------------------------------------
[Unit]
Description=GPS (Global Positioning System) Daemon Sockets

[Socket]
ListenStream=/var/run/gpsd.sock
#ListenStream=[::1]:2947
#ListenStream=127.0.0.1:2947
# To allow gpsd remote access, start gpsd with the -G option and
# uncomment the next two lines:
ListenStream=[::1]:2947
ListenStream=0.0.0.0:2947
SocketMode=0600

[Install]
WantedBy=sockets.target
------------------------------------------------------------------------------------

**Comment by frenck** [comment]
> I have been trying to get the docker image working without using network_mode: host, and privileged: true. 

That is unfortunately not supported by the Home Assistant project.

Nevertheless, thank you for providing feedback 👍
