### ISSUE TITLE
Support for Solar systems with different anzimut/declination settings

### ISSUE THREAD

**Issue by tobox** [home-assistant/home-assistant.github.io#19352]
### Feedback

I have 2 PV systems: on one the house roof an one on the carport. 

They have completely different anzimut/declination settings. It would be nice if home assistant could support multiple instances, and compute the sum of the predictions.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.9.5

**Comment by klaasnicolaas** [comment]
You can add the integration multiple times, so for each "zone" you can specify the right settings 😉

**Comment by tobox** [comment]
Well, thats an easy an clean solution. Somehow I just did not try to add it multiple times. My bad. Thanks for the good work!
