### ISSUE TITLE
Bug in Energy Modem for Shelly 3EM

### ISSUE THREAD

**Issue by nikolas22t** [home-assistant/home-assistant.github.io#19369]
### Feedback

In energy module the return value of 3EM every morning at 3 o clock it adds to the daily usage the total return of all time , 
more info about my issue here 
https://community.home-assistant.io/t/energy-module-possible-bug/337898/3

### URL

https://www.home-assistant.io/help/

### Version

2021.9.6

**Comment by thecode** [comment]
Closing as you already opened an issue in the core repo
