### ISSUE TITLE
Twinkly documentation tweak

### ISSUE THREAD

**Issue by rec** [home-assistant/home-assistant.github.io#19363]
### Feedback

Hello.  I wrote [a Twinkly controller for BiblioPixel](https://github.com/rec/bpx/blob/master/bpx.py) so I'm somewhat familiar with it.

Twinkly does store some number of programs on the string itself in non-volatile memory - the specific number depends on the string itself.

More, there's a mode where you can send individual frames to an individual string in real time over the network (which is what I used above).

I'm don't at this time have the time to help you to integrate it into your excellent system, but wanted to correct the documentation.

### URL

https://www.home-assistant.io/integrations/twinkly/

### Version

2021.9.5

**Comment by dr1rrb** [comment]
@rec really interesting! Do you known if there is a way to get the list of effects stored on the device? Does your "BiblioPixel" offers a way to retrieve that list?

**Comment by rec** [comment]
Hello, and I'm so sorry to get back to you so late, lots happening!

[BiblioPixel](https://github.com/ManiacalLabs/BiblioPixel) is a generalized LED lighting library.  Unfortunately, it's not under development right now (through no fault of my own - the copyright owners of the name decided unilaterally).  

However, it's been very stable for years.

I have written a [tiny little driver for BiblioPixel that drives the Twinkly lights](https://github.com/rec/bpx), but it depends on changes to the [xled](https://github.com/scrool/xled) library that are under review right now.

The [new changes to xled](https://github.com/scrool/xled/pull/80) do allow you to retrieve and store patterns on the Twinkly!

But my feeling is that it will be several weeks before those are all resolved.
