### ISSUE TITLE
Missing note about legacy_templates

### ISSUE THREAD

**Issue by andras-tim** [home-assistant/home-assistant.github.io#19373]
### Feedback

I spent a half-day figuring out why the custom weather stuff doesn't work. I have no error message, but the whole weather object was empty.

Now I know, the **legacy_templates** causes my all problems.

After I fixed all of my templates and removed the following settings, everything started to work:

``` yaml
homeassistant:
  legacy_templates: true
```

So, I mentioned, please write a note about this issue.

### URL

https://www.home-assistant.io/integrations/weather.template/

### Version

2021.9.6

**Comment by balloob** [comment]
I don't think it's worth mentioning. The feature is very rarely used and should be phased out.

**Comment by andras-tim** [comment]
@balloob, I see your point, but while this compatibility mode exists this will be the only integration(?) that doesn't work, and besides this, the user will not have warning/error messages... so, this will be hard to fix.

**Comment by frenck** [comment]
If the integration doesn't work without enabling legacy templates, it should be reported as a bug and not a documentation issue.

Legacy templates was introduced for a transition possibility for existing users with complex templates, not as a compatibility/fix/option to use for things like these.

Could you please raise the issue you are having, including a reproduction scenario, in our Core issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks already! 👍 

../Frenck
