### ISSUE TITLE
Living Now is working

### ISSUE THREAD

**Issue by MapoDan** [home-assistant/home-assistant.github.io#19375]
### Feedback

Hello, 
Thanks a lot for all your job.
Just for your info, I've configured the Home+Control Integration with the BTicino Living Now series (https://www.bticino.it/placche-elettriche/living-now), so with its Zigbee Hub, and it is perfectly working for swithces.
I have no power outlets to test them, but I have roller shutter and I will test them as soon as they will be supported.

This Living Now series is using the same API from Legrand.

Thanks
Ciao
Daniele

### URL

https://www.home-assistant.io/integrations/home_plus_control/

### Version

2021.9.7

**Comment by atxbyea** [comment]
https://github.com/home-assistant/home-assistant.io/pull/19711

**Comment by matteocostantini** [comment]
Hi,
I’ve create an home+control account for my living now environment… perfectly working!

well, i’ve follow instructions for integration enable. Starter kit api (primary key and secondary key, im using primary) and new application as described in official guide. Then i ve configure configuation.yaml, enable third party access in home + control app and voilà: i see my 2 nlp module (2 washing machine). But i’m now seeing another light switches…. Why?
