### ISSUE TITLE
Solar energy consumed not configurable for me.

### ISSUE THREAD

**Issue by sjakief** [home-assistant/home-assistant.github.io#19379]
### Feedback

Hi,
My solar panels give back energy through phase 2 and phase 3, and i am probably not the only one who has a setup like this: The problem now is that i only have "energy consumed tariff 1 +2" and "energy produced tariff 1+2", and when i configure the energy with those options it looks like this
![image](https://user-images.githubusercontent.com/12416263/133924637-1a8ba9c6-9bd7-41de-b547-d1df0282559c.png)
it's giving nice graphs, but they are not correct:
![image](https://user-images.githubusercontent.com/12416263/133924669-2701995a-ca45-4b5e-a26e-7daec7587b4c.png)
I don't see how much energy is self consumed through my solar panels. So is that something that should be in HA, or is there another way to achieve this

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi there @sjakief 👋 

It seems like you want to report an bug with Home Assistant or its integration, however, you have submitted documentation feedback instead.

If you want to report an issue with an integration (or the data it provides), please report it here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
