### ISSUE TITLE
Debbugging

### ISSUE THREAD

**Issue by Megachip** [home-assistant/home-assistant.github.io#19376]
### Feedback

Missing informations for debugging issues...

### URL

https://www.home-assistant.io/integrations/edl21/

### Version

2021.9.7

**Comment by frenck** [comment]
We have generic tools available for debugging issues (unfortunately, your documentation feedback is not providing information on the issue you are experiencing).

Therefore, this documentation suggestion is hard to improve on.

Maybe try starting with getting information from the logger: <https://www.home-assistant.io/integrations/logger>

Please note, that if an integration doesn't work, it is recommended to get support or file a bug report.
See https://www.home-assistant.io/help for more information on where to go in those cases.

Thanks 👍 

../Frenck

**Comment by Megachip** [comment]
@frenck issue(s):
https://community.home-assistant.io/t/debugging-edl21/338053
https://community.home-assistant.io/t/edl21-doesnt-work-weidmann-electronics/276344/3
https://community.home-assistant.io/t/logging-for-component-edl21/272773
...

**Comment by frenck** [comment]
This is not the issue tracker for integrations. Please consult https://www.home-assistant.io/help on where to go.
