### ISSUE TITLE
Password for integration has changed, how can the HA integration be updated with new password

### ISSUE THREAD

**Issue by pederseg** [home-assistant/home-assistant.github.io#19385]
### Feedback

Ref doc for MILL integration, in HA logs I see that the password I configured the unit with (some time long ago) now is wrong.
Should the doc contain some information about how to store the new password in the HA integration.

Also should the doc contain some information about how to remove the integration, making it possible to redo the integration?

Logger: mill
Source: /usr/local/lib/python3.9/site-packages/mill/__init__.py:93
First occurred: 18. september 2021, 22:28:04 (930 occurrences)
Last logged: 19:05:07

Wrong password

### URL

https://www.home-assistant.io/integrations/mill/

### Version

2021.9.7

**Comment by Danielhiversen** [comment]
The Mill integration currently does not support reconfiguration, so you need to remove and add it again.

**Comment by pederseg** [comment]
Thanks for quick reply Daniel ! I found a way to change the password by ediing /config/.storage/core.config_entries file - looks like it worked for the passwd. But I was looking into removing the component :-)
I still think the doc could be updated, but I close the issue and let you update if you like to :-)
