### ISSUE TITLE
automation.yaml

### ISSUE THREAD

**Issue by blackest** [home-assistant/home-assistant.github.io#19382]
### Feedback

The ui editor uses automations.yaml and this page says to create automation.yaml and include it
but having

automation: !include automations.yaml
and
automation: !include automation.yaml

results in just automation.yaml automations getting loaded

further down the page better suggestions are made but it seems wrong to be setting inexperienced users for failure. 

### URL

https://www.home-assistant.io/docs/configuration/splitting_configuration/

### Version

2021.9.7

**Comment by frenck** [comment]
The suggestion you are making, is the default configuration. This is already present in every installation.

This page is explaining an advanced subject on splitting configuration and is not aimed towards inexperienced users.

Nevertheless, thanks for providing feedback 👍
