### ISSUE TITLE
docs on using libcec in a python virtual env creates symlink to wrong location

### ISSUE THREAD

**Issue by matt-cahill** [home-assistant/home-assistant.github.io#1939]
The docs here:
https://home-assistant.io/components/hdmi_cec/#libcec 
include instructions to symlink the cec package from inside an v_env to
`/usr/local/lib/python3.4/dist-packages/cec`
but it seems libcec gets installed to
`/usr/local/lib/python3.4/site-packages/cec`
this means users who follow the instructions see a failure when using the HDMI CEC component inside the v_env.

Discussion here for reference: https://community.home-assistant.io/t/hdmi-cec-configuration-error/10819

**Comment by fabaff** [comment]
Was merged.
