### ISSUE TITLE
Eenergy docs don't explain what kind of data is expected

### ISSUE THREAD

**Issue by hsmade** [home-assistant/home-assistant.github.io#19393]
### Feedback

The docs only talk about existing integrations. But when you're rolling your own, or have your own, you need to know what kind of data is expected by the system. 
For example, I rolled my own p1 -> mqtt system long ago. It publishes the values of each item in the telegram. 
So I have both the current usage in Watt, and the two total (since 'epoch') values for the two tarifs, in kWh.

Now here is another issue with the docs. The is a line saying to read https://www.home-assistant.io/docs/energy/faq/#split-consumption-by-tariffs if you want to split the reading by tarifs, but that's not what that page is about. It's about splitting a net meter's reading into multiple tarifs. There is no documentation about using the energy page with multiple tarifs.

So to make things simples, I created a templated sensor to hold the sum of both tarifs. So my total energy consumption since 'epoch'. This value never wraps. It has has a `device_class` of `energy` and a `state_class` of `total_increasing`.

Still the energy page somehow reads the values as a measurement. As it keeps recording the grand total, or even multiples of that, as the value for the last hour.

So what kind of data does this page assume? How should it populate over the day? And how should I configure it to understand multiple tarifs?

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.9.7

### Additional information

My config:
```yaml
sensor:
  - name: energy_consumption_low_tarif
    platform: mqtt
    state_topic: "/power/consumption_low_tarif"
    force_update: true
    unit_of_measurement: "kWh"

  - name:  energy_production_low_tarif
    platform: mqtt
    state_topic: "/power/production_low_tarif"
    force_update: true
    unit_of_measurement: "kWh"

  - name: energy_consumption_high_tarif
    platform: mqtt
    state_topic: "/power/consumption_high_tarif"
    force_update: true
    unit_of_measurement: "kWh"
  
  - name: energy_production_high_tarif
    platform: mqtt
    state_topic: "/power/production_high_tarif"
    force_update: true
    unit_of_measurement: "kWh"
  
  - name: energy_actual_consumption
    platform: mqtt
    state_topic: "/power/actual_consumption"
    unit_of_measurement: "W"
  
  - name: energy_actual_production
    platform: mqtt
    state_topic: "/power/actual_production"
    unit_of_measurement: "W"

template:
  - sensor:
    - name: energy_total_consumption
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      state: "{{ states('sensor.energy_consumption_low_tarif') | float + states('sensor.energy_consumption_high_tarif') | float }}"
    - name: energy_total_production
      unit_of_measurement: kWh
      device_class: energy
      state_class: total_increasing
      state: "{{ states('sensor.energy_production_low_tarif') | float + states('sensor.energy_production_high_tarif') | float }}"
    - name: energy_cost_current
      unit_of_measurement: EUR
      state: >
        {% if is_state('sensor.energy_actual_tarif_group', '1') %}
        {{ 0.21848 }}
        {% else %}
        {{ 0.23037 }}
        {% endif %}

**Comment by hsmade** [comment]
While fiddling with it, I found that this config seems to work:
```yaml
sensor:
  - name: energy_consumption_low_tarif
    platform: mqtt
    state_topic: "/power/consumption_low_tarif"
    force_update: true
    unit_of_measurement: "kWh"
    device_class: energy
    #state_class: total_increasing
    last_reset_value_template: "{{ '1970-01-01T00:00:00+00:00' }}"
    state_class: measurement
    value_template: "{{ value | float / 1000 }}"
```

So a state_class of measurement and device_class of energy, combined with a last_reset_value of epoch.
Note that I had to divide the value by 1000, it seems this telegram event is emitting Wh, not kWh (and I guess I could also fix the unit to make it work, but this works better for my other stuff).
Also, I found out that in order to 'see' multiple tarifs, you just need to add them separately to the board (using 'add consumption'). They then display as a stacked bar graph.

**Comment by pashdown** [comment]
Here's another example of a tariff sensor.  It took me a bit of time to realize that the utility_meter tariffs were not actual monetary tariffs, but simply buckets by which the energy consumption could be divided in.  This sensor is based on [Rocky Mountain Power's tariff sheet](https://www.rockymountainpower.net/content/dam/pcorp/documents/en/rockymountainpower/rates-regulation/utah/Utah_Price_Summary.pdf).

```yaml
sensor:
  - platform: template
    sensors:
      rocky_mt_power_tariff:
        friendly_name: 'Rocky Mt Power Tariff'
        unit_of_measurement: 'USD/kWh'
        value_template: >
          {% set monthly_kwh = (states('sensor.monthly_electric_peak') | float  + states('sensor.monthly_electric_offpeak') | float) %}
          {% if monthly_kwh < 400 %}
            {% if (now().month < 6) or (now().month > 9) %}
              {% set price = '.082126' | float %}
            {% else %}
              {# summer #}
              {% set price = '.092802' | float %}
            {% endif %}
          {% else %}
            {% if (now().month < 6) or (now().month > 9) %}
              {% set price = '.105959' | float %}
            {% else %}
              {# summer #}
              {% set price = '.119733' | float %}
            {% endif %}
          {% endif %}
          {{ price | float }}
```

If you're using the Time-of-Use (schedule 2E) for peak differentials, setup a switching tariff as explained in the docs and replace the last line with:

```yaml
          {% if is_state('utility_meter.monthly_electric', 'offpeak') %}
            {# offpeak #}
            {{ price - '.016334' | float }}
          {% else %}
            {# peak #}
            {{ price + '.043560' | float }}
          {% endif %}
```
I hope this can help someone add some clearer documentation to the energy integration.
