### ISSUE TITLE
Terminology.

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19402]
### Feedback

Looking at thermostats. Came across the word 'card'?
No idea what it means - I am a newbie.
Is there sufficient jargon to make a glossary worthwhile?

E.g. ''connector" - seems to mean an interface hw piece etc etc. 

### URL

https://www.home-assistant.io/lovelace/shopping-list/

### Version

2021.9.7

**Comment by milanmeu** [comment]
I'm not quite sure what you're asking, so correct me if this comment doesn't answer your question.
 
The highlighted area in the image below is the card.

![cards](https://user-images.githubusercontent.com/15276289/134071452-1d3a80e9-b290-4ef1-a0c1-09b17ff76c6c.png)

For me the meaning of card is clear:
- There is a screenshot of a card with caption
- There is a link to the card terminology page in the menu (see arrow)
- There is a list of all Lovelace cards in the menu

But maybe I've been using HA for too long. You can use the edit button at the bottom of the page to suggest a change.

Please use one of the community channels if you have more questions: https://www.home-assistant.io/help/#communication-channels.

**Comment by dpawson** [comment]
I note 'for you'. A card? A birthday card? A sheet of plain white card? The use here is overloaded. 
I was thinking more generally, for the home assistant project, to collect terms which are not familiar to a newbie,
to help with on-boarding. 
  Sorry if I was not clear.

**Comment by ludeeus** [comment]
<https://www.home-assistant.io/docs/glossary/> "Card" can be added here

**Comment by dpawson** [comment]
Apologies, glossary not found.

**Comment by dpawson** [comment]
Oddly, a search for 'glossary' returned zero results?

**Comment by milanmeu** [comment]
![image](https://user-images.githubusercontent.com/15276289/134380761-93ed83fc-cdbf-4d06-be37-26d27082f816.png)
