### ISSUE TITLE
PLEASE MARK AS DEPRECATED!

### ISSUE THREAD

**Issue by QuantumStar** [home-assistant/home-assistant.github.io#19407]
### Feedback

I wasted hours trying to get the SenseHAT to work with the Pi running HomeAssistant, obviously to no avail since there are dependencies that are missing. I wish I'd read the forum post related to this sooner, instead I trusted the official doccumentation.

Please mark this as DEPRECATED until it can be fixed. It would be awesome to be able to use the SenseHAT with the Pi, but until then, it's just a huge time waster for noobs like me.

### URL

https://www.home-assistant.io/integrations/sensehat/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi, I don't think we need to use caps like that. It is considered shouting and therefore I don't think it is polite.

That said, it sounds like you are experiencing an issue with an integration, for which an issue should be reported maybe? That said, there is no context in this documentation feedback (besides frustration and opinion on if something should be deprecated or not); which is not much for me to work with.

Could you please clarify?

**Comment by QuantumStar** [comment]
As this issue was raised two years ago, and ignored, I thought maybe if I used all caps it would finally be dealt with. It's not meant to be polite, it's meant to draw your attention to something that wasted hours of my time, and hours of other peoples' time.

If you read my post, you'd see what the issue is. The SenseHAT has dependencies that are missing from current distributions. SenseHAT does not work with Home Assistant. Nowhere in the current documentation does it say that it no longer works.

Here is the thread regarding the dependencies: https://github.com/home-assistant/core/issues/32692

30 seconds of someone putting something at the top of the SenseHAT integration page that says "THIS NO LONGER WORKS", or just removing it until it does work, would have saved hours of peoples' lives. I find that irritating.

**Comment by frenck** [comment]
The linked issue is closed stale. We don't use documentation to document issues, please raise issue for that.

> It's not meant to be polite

In that case I'll go ahead and close this up.
