### ISSUE TITLE
this doesn't work

### ISSUE THREAD

**Issue by ralong777** [home-assistant/home-assistant.github.io#19417]
### Feedback

this doesn't work

### URL

https://www.home-assistant.io/integrations/twitch/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi there @ralong777 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please see www.home-assistant.io/help on where and how to report issues with integrations.

Thanks 👍
