### ISSUE TITLE
Where can we edit value present in the documentation

### ISSUE THREAD

**Issue by fasavard** [home-assistant/home-assistant.github.io#19419]
### Feedback

Hi, 
I loaded the tuya integration with a succesful llogin. I do see my controller but have the know problem of avant the temperature with the wrong digit. The value should be 10 degree but it's 1.

In the documentation, there is such a tool to fix that: 
Temperature values divider,

But the setting is nowhere in the UI, well pretty much none of those setting are available. How to i edit them ?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.9.7

**Comment by ollo69** [comment]
Select Settings -> Integration

In Tuya integration select Options, then select device you want to configure and click submit. Option you are searching for are there

**Comment by fasavard** [comment]
<img width="1792" alt="Screen Shot 2021-09-21 at 7 17 56 PM" src="https://user-images.githubusercontent.com/49327442/134259997-ad72c586-9a7e-491e-89ca-6e205e3c25c6.png"
<img width="1792" alt="Screen Shot 2021-09-21 at 7 18 26 PM" src="https://user-images.githubusercontent.com/49327442/134260040-f31f1f2a-530a-4b76-b87c-e6c916461d80.png">
>

Im really sorry i think i might be not seeing something obvious, i do not see those settings here

**Comment by ollo69** [comment]
You must select (check) the device and click on submit. A new page will open with the options.

**Comment by fasavard** [comment]
Annnnd i'm a shame... 
Thank you very much, 
Pretty insane the quality of the service you just provided for free. 
Thanks again
