### ISSUE TITLE
Growatt Integration - Login error

### ISSUE THREAD

**Issue by ruudvddries** [home-assistant/home-assistant.github.io#19412]
### Feedback

Growatt integration was working flowless. Since two weeks login fails (JSON response unreadible by python script) and no data is being received. 

Seems to be related to this issue https://github.com/indykoning/PyPi_GrowattServer/pull/18 

I am unable to fix this myself. :(

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.9.7

**Comment by muppet3000** [comment]
This has been fixed in the latest release. 
Duplicate of: https://github.com/home-assistant/core/issues/56044

**Comment by ruudvddries** [comment]
My apologies! I was trying to find a fix in the past weeks. Just updated to 2021.9.7 and all is fine now. Thanks for the hard work!
