### ISSUE TITLE
Clarification for tag functionality blog post (need admin help)

### ISSUE THREAD

**Issue by CarlosGS** [home-assistant/home-assistant.github.io#19411]
### Feedback

**Note: I can't submit a PR because it is a post in the blog:**
https://www.home-assistant.io/blog/2020/09/15/home-assistant-tags/

The article says:

    “Tags are not bound to the phone that wrote them, any phone can scan them.”
Though technically correct, some of us misinterpreted that tags would be exposing access in some way (i.e. by writing the HASS installation url).

Note the blog post is effectively the landing page for new tag users, we arrive there when searching for tag documentation.
**To help new users, maybe this sentence could be clarified? Something like:**

    “Tags are not bound to the device that wrote them, any phone can scan them. They contain no private information, so automations can only be triggered by app-authenticated users.”

### URL

https://www.home-assistant.io/blog/2020/09/15/home-assistant-tags/

**Comment by CarlosGS** [comment]
Keeping an eye on Discord and it seems this keeps causing confusion, it would be nice to incorporate this edit to the blog post.

**Comment by frenck** [comment]
> “Tags are not bound to the device that wrote them, any phone can scan them. They contain no private information, so automations can only be triggered by app-authenticated users.”

This sounds weird as well... Tags do not trigger automations directly and can be scanned by other apps, authenticated to other systems.

**Comment by CarlosGS** [comment]
Did a deeper search in Discord, here are some of the messages to put the problem in context:

> Hi, I have a noob question. It seems like I can look for device-id when a Tag is scanned.. But can anyone scan my tag and trigger the automation unless I check for device_id or would they need to have the homeassistant-app and login for my instance?

> Can anyone use my qr tag without logging in to my home assistant instance?

> Are the nfc tags only allowed to be used by members you add to your home assistant account? or can anyone with a device that supports nfc trigger your automation? I'm trying to understand a little better how secure these tags are. I wouldn't want anyone just triggering my automation.

> Can anyone who knows that url fire an event, or do you have to be logged into HA?

The direction is clear, though I agree my edit proposal wasn't too clear x)
Maybe we could do with this leaner version? Open to suggestions here:

> Tags are not bound to the phone that wrote them, any phone can **use** them **as long as it's authenticated with the app.**

**Comment by frenck** [comment]
So what is the catch? Its about security right?

“Tags are not bound to the device that wrote them, any phone can scan them. They contain no private information, authentication, or information about your Home Assistant instance.”

**Comment by CarlosGS** [comment]
That clarifies it very well :D

**Comment by CarlosGS** [comment]
I'd still recommend clarifying that sentence, here are a couple recent messages from the forum:

> From a security perspective, is the device id only supplied by the phone and it’s not stored on the NFC card? I wouldn’t want someone with some kind of hacker tool to be able to read the card and get all the necessary info to clone a device and be able to unlock my door.

> I thought of having a (hidden) tag on the door, so I can open it by holding the phone there. Any security constraints here when doing it like this opposed to carrying the Tag with me and holding it to a scanner?

The issue is not evident for experienced users that already know how tags work: it specifically affects new users that are trying to understand its security. So any of the discussed clarifications would help :smile:

Closing for simplicity and less noise; this thread meant to be a documentation correction where a PR isn't possible.

**Comment by frenck** [comment]
What do you mean with:

> thread meant to be a documentation correction where a PR isn't possible.

?

Everything we do is here in these repos, and all can be PR-ed

**Comment by CarlosGS** [comment]
Oh, I didn't know the blog entries were in this repository too. Sorry for the noise...
