### ISSUE TITLE
Authentication issue?

### ISSUE THREAD

**Issue by christopher-walker** [home-assistant/home-assistant.github.io#19418]
### Feedback

Hi,
 Just got my heater installed added a Remote user client API in the Adax app tried to add the Adax integration in home assistant (one thing I notice is that the account id is a number rather than text).
 I selected 1 as the account Id and entered the password provided, got an error message _**Failed to connect**_

 When I look into the logs I see the following:

Logger: adax
Source: /usr/local/lib/python3.9/site-packages/adax/__init__.py:195
First occurred: 9:44:42 PM (6 occurrences)
Last logged: 9:53:56 PM

Adax: Failed to login to retrieve token: 400 {"error": "invalid_grant"}

I have updated to the latest version of Home Assistant 2021.9.7

I am running Home Assistant on Ubunu:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

In a docker container from:
https://hub.docker.com/r/homeassistant/home-assistant

Im not sure if this is a documentation issue or an issue with Home Assistant.

Thanks

Chris

### URL

https://www.home-assistant.io/integrations/adax/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi there @christopher-walker 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations here:L

<https://github.com/home-assistant/core/issues>

Thanks already! 👍 

../Frenck

**Comment by christopher-walker** [comment]
Thanks @frenck 
Turns out it is either an Idiot (me) or documentation issue though. I didnt understand what the account id referred to. Apparently this is not included in the Remote user client API screen but the User information screen in the app. Would stop fools like me posting issues if the doc was updated a little 👍
