### ISSUE TITLE
OBIS Values of published MQTT topics should be Nr. 1 source for energy data

### ISSUE THREAD

**Issue by OJBender** [home-assistant/home-assistant.github.io#19428]
### Feedback

Was looking for integration of OBIS data published by smart meter. 
Example:   state_topic: "/energy/smartmeter/sensor/1/obis/1-0:1.8.1/255/value"
I am surprised that I did not manage to use such data in the energy section, nor could I find useful hints how to integrate them. The OBIS values 1-0:1.8.2 will also contain the solar power fed into the grid but has all other data of current and past energy consumption. A howto for integration in the energy moduld would be warmly welcomed. 

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.9.7

### Additional information

Default and standard OBIS pattern of mostly all German Smart meters:

  - platform: mqtt
    name: "Netzbezug"
    state_topic: "/energy/smartmeter/sensor/1/obis/1-0:16.7.0/255/value"
    unit_of_measurement: "W"
    state_class: measurement

  - platform: mqtt                                                      
    name: "Gesamtverbrauch"                                                   
    state_topic: "/energy/smartmeter/sensor/1/obis/1-0:1.8.1/255/value"
    unit_of_measurement: "W"                                            
    state_class: total_increasing

  - platform: mqtt                                                      
    name: "Gesamteinspeisung"                                                   
    state_topic: "/energy/smartmeter/sensor/1/obis/1-0:2.8.1/255/value"
    unit_of_measurement: "W"                                            
    state_class: total_increasing

**Comment by frenck** [comment]
Your examples show power usage, not energy. Energy and power are not the same things. You need to set up energy sensors, once you do, they will become available for selecting in the energy dashboard.
