### ISSUE TITLE
Limitations of Gree?

### ISSUE THREAD

**Issue by chopperpl** [home-assistant/home-assistant.github.io#19426]
### Feedback

It would be nice to have the output from the temp sensor of the HVAC device showing current temperature in the room. This way we don't have to add/rely on additional/external temp sensor for automation via HA.
Thanks

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.9.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by cmroche** [comment]
To be clear though, this is already supported by the integration, however many Gree devices do NOT support reporting this information over the network.

**Comment by chopperpl** [comment]
Hello Clif,
DO you know if this feature is supported by U-Crown model? It seems to be one of the top models, so I would assume this data should be available some how.
Thanks

**Comment by cmroche** [comment]
I could not tell you from the model.

But if you set “greeclimate” to debug in your logging and attach those logs it will possibly let us know.. just make sure you set the target temperature to not be the same as the room temperature so we can identify the difference in the response.
