### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19424]
### Feedback

Page https://www.home-assistant.io/docs/automation/using_blueprints/

Text Done! If you want to revisit the configuration values, you can find it by going to Configuration and then Automations.

The hot 'configuration' link is 404

### URL

https://www.home-assistant.io/docs/automation/using_blueprints/

### Version

2021.9.7

**Comment by milanmeu** [comment]
Please also share the URL that returns the 404.
I tried the link and it works for me on 2021.8.
Is your `Your instance URL` correct?

---
![myconfig](https://user-images.githubusercontent.com/15276289/134525759-09967d43-d5e7-4e87-aa84-5c2fb7e4fa85.gif)

**Comment by dpawson** [comment]
I'm guessing it's because my rpi4 wasn't switched on?
How to add to documentation that 'this url is on your HA implementation'?

**Comment by milanmeu** [comment]
> How to add to documentation that 'this url is on your HA implementation'?

This is already in the [My Home Assistant FAQ](https://my.home-assistant.io/faq/). Link to the FAQ is at the bottom of the https://my.home-assistant.io/redirect/config/ page. You can propose changes in the My Home Assistant repository: https://github.com/home-assistant/my.home-assistant.io.
You previously set your instance URL, delete your cookies or use another browser to see the configuration page again.
