### ISSUE TITLE
use_webhook uri

### ISSUE THREAD

**Issue by mkaatman** [home-assistant/home-assistant.github.io#19421]
### Feedback

Would it be possible to document the uri that's used for use_webhook? I assume it's different than the callback.

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2021.9.7

**Comment by frenck** [comment]
I'm confused about your documentation suggestion in this case. The webhook set up and URL is handled by Home Assistant. You don't need to set the URL manually?

**Comment by mkaatman** [comment]
I'm fighting the infamous error code 293

https://github.com/home-assistant/core/issues/46425

I don't have my instance wide open. I'm reverse proxying specific urls through (oauth2 so far). My suspicion is that there is some webhook url being called that's getting blocked. I'm trying to figure out what that url is but the logs aren't detailed enough.

**Comment by frenck** [comment]
Well, that is not a documentation issue but a bug report. Please keep track of that issue instead.

Thanks 👍

**Comment by mkaatman** [comment]
If the URL was documented. I could forward it through and it would solve my problem

**Comment by frenck** [comment]
> If the URL was documented. I could forward it through and it would solve my problem

There is no documented URL, it is calculated and automatically handled. Thus not a documentation issue,.

**Comment by mkaatman** [comment]
If anyone finds this issue in the future, I found the url.

It's in /config/.storage/core.config_entries

The format is:
<external_url>/api/webhook/<webhook_id>
