### ISSUE TITLE
Duplicate blueprints?

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19425]
### Feedback

text: If you just want to practice importing, you can use this URL:

Followed that (is it a 'requirement' to change the filename? Not made clear).
Allowed me to save the automation. I then find that blueprint already exists, seems to be in the same location?
  Is there no 'Overwrite file of same name'?
============
No mention of where blueprints are stored - /config/blueprints/automation/home-assistant/motion_light.yaml
Seems to be the case?
============

(Rather subtle?) "Transforming" / Activating a blueprint?  
text: Find the blueprint that you want to use and click on “Create Automation”. 
 I guess this 'enables' the script to be run?
I don't find that clear at all.
Perhaps enhance the text to "Find the blueprint that you want to use and click on “Create Automation”. This will make the script 'live' i.e. it will be acted upon when the trigger occurs"

### URL

https://www.home-assistant.io/docs/automation/using_blueprints/

### Version

2021.9.7

### Additional information

These blueprints (great idea) - No mention of how to obtain the 'local' name of the sensor or light, to substitute into the yaml script? I would find that helpful.

**Comment by geoffreygarrett** [comment]
What even is this?'
