### ISSUE TITLE
Add integration of RTLAMR Collect or InfluxDB as Energy meter source

### ISSUE THREAD

**Issue by JoeDaddy7105** [home-assistant/home-assistant.github.io#19439]
### Feedback

I use an rtl-sdr receiver and this tool on a Raspberry Pi to pickup the consumption radio signals from my meters and feed them in to InfluxDB.

https://github.com/bemasher/rtlamr
https://github.com/bemasher/rtlamr-collect

Not sure if it would be easier to take in the signals from rtlamr-collect or to just take the reads out of InfluxDB but it would be helpful to see this included as an option on the electricity grid page.

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

**Comment by ludeeus** [comment]
For feature requests please use our 
[forums](https://community.home-assistant.io/). Thanks :+1:
