### ISSUE TITLE
Automation saves previous video

### ISSUE THREAD

**Issue by PehrGit** [home-assistant/home-assistant.github.io#19433]
### Feedback

Hi, 

The instructions for saving the video when there is movement result in the video of the _previous_ movement being downloaded. It seems the video_url is only updated 30 seconds after the motion was detected. Which makes sense as it should first record the video belonging with the motion. Should we configure the automation to trigger when the motion goes to off instead of to on?

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2021.9.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by PehrGit** [comment]
Thanks for the reply. I actually don't see this as a support ticket, I'm of the opinion that the example on the integration page is wrong/broken/faulty. So I'd say an issue is the appropriate place to discuss that, right?
