### ISSUE TITLE
Device area? Included in Entity ID?

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19444]
### Feedback

In developer-tools/state for a device, advanced settings, I can assign a device to an area?
Is this required to uniquely identify a specific device as per example, kitchen.light? Is 'kitchen' the area obtain / set
via the attributes?

### URL

https://www.home-assistant.io/docs/automation/basics/

### Version

2021.9.7

**Comment by frenck** [comment]
I'm confused about your question/explanation/documentation suggestion you are trying to make. Could you please clarify the suggestioN?

**Comment by dpawson** [comment]
I think the HA term is 'domain'? I see many devices (device ID's?) prefixed with <x> then period, where x seems to vary between a device type (e.g.light) and 'place' / room, e.g. kitchen. 
 I find this confusing and I'm looking for an explanation - e.g. how to set up the <x> prefix (or is it done automatically) etc. 
 Sorry if I was not clear.

**Comment by frenck** [comment]
You cannot set up this prefix.

More in-depth explanation (but out of scope for the linked page for sure).

An entity ID is composed of: `<platform>.<object_id>`

A `<platform>` can be a `light`, `switch`, `climate`, or many of the other entity platform Home Assistant provides. These platforms are a fixed set and not customizable. `<object_id>` is the name of the entity provided by a device (which can be customized in most cases).

Entity IDs are not related to areas in any way. However, devices & entities can be assigned to areas (as a way to group them).
