### ISSUE TITLE
Valuable but confusing

### ISSUE THREAD

**Issue by DaveDixon** [home-assistant/home-assistant.github.io#19448]
### Feedback

Thanks for the documentation! The first part "Install Home Assistant Operating System" seems thorough and what I'll do even though I'm a 40-year unix/linux veteran. What isn't clear from the organization of this page is whether the subsequent installation instructions are part of or exclusive to the first part. The disclaimer on the Docker section is that you already have an operating system installed, which is certainly the case at the completion of the first section. Both the Docker instructions and the Core instructions say they assume there is already "an" OS, but don't say which one: HASS, Debian, AIX? 

Then there's the question of why someone might choose these other options. I'm currently maintaining a Core installation of Home Assistant on an Ubuntu server. I'm not happy that all the good support/features are on the HA operating system, but I think I can live with it by installing on a Raspberry Pi. The Docker/container/virtual solutions seem to add maintenance and other overheads that aren't worth it. A definitive delineation of the different installation options and their relative merits/drawbacks would be beautiful - it's in dribs and drabs throughout the site - and it is certainly needed on this page. 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.9.7

**Comment by ludeeus** [comment]
We have that here <https://www.home-assistant.io/installation/#compare-installation-methods> which is on the page you see before getting to the raspberrypi page
