### ISSUE TITLE
Language configuration

### ISSUE THREAD

**Issue by Aviatorpaal** [home-assistant/home-assistant.github.io#19442]
### Feedback

Great integration! I would love to see customisable weather "output" language, e.g.: Weather: "Overskyet", not cloudy even though my HA install remains in English.

### URL

https://www.home-assistant.io/integrations/met/

### Version

2021.9.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
