### ISSUE TITLE
Cannot find vera_controller_url: to update IP 

### ISSUE THREAD

**Issue by markcm2** [home-assistant/home-assistant.github.io#19450]
### Feedback

I changed the IP of my vera controller and Home Assistant can no longer communicate. I cannot find the vera_controller_url:  to update the IP in HA. I assumed it would be under Configuration > Integrations > Vera but could not find any way to update the IP there.

When searching the documentation via Configuration > Integrations > Vera > documentation, reference to using a static IP is made but there is no reference as to where the IP can be updated in HA. A web search revealed that the following should be in configuration.yaml

`vera:
  vera_controller_url: http://10.0.0.6/port_3480`

My .yaml fild did not have any reference to vera. I added this line and updated with my IP, then restarted the supervisor which made no change. Next I restarted the core, then the IP for my vera controller updated in HA.

This was much too complicated, an easier path needs to be provided for updating a vera controller IP and the documentation should include how to perform the update.

### URL

https://www.home-assistant.io/integrations/vera/

### Version

2021.9.7

### Additional information

Here is the forum thread that helped me figure out how to update the IP for my very controller; without this, I was unable to find the IP to update it. https://community.home-assistant.io/t/cant-connect-vera-plus/144011

**Comment by ludeeus** [comment]
When authentication or connection details to the device/service change.
1) Remove the integration from Configuration > Integrations
2) Add it again with the new details.

This applies to all integrations that you manage in the UI.

**Comment by pavoni** [comment]
@markcm2 As @ludeeus said removing and re-adding is the easiest solution to this.

The devices names shouldn't change - so the only hassle is if you have a lot of excluded devices or switches remapped as lights. My vera isn't currently live - but I think you can just copy and paste that part of the config.
