### ISSUE TITLE
Shelly 1 Plus

### ISSUE THREAD

**Issue by mapulu** [home-assistant/home-assistant.github.io#19459]
### Feedback

New Device "Shelly 1 Plus" seems not supported and it says not supported Firmware Version
"Only supports firmware 1.8 and later"
Firmware version: 0.8.1
Firmware build ID: 20210921
Maybe it would work but it checks the firmware version and it is to low?

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2021.9.7

**Comment by bieniu** [comment]
Generation 2 Shelly devices will be supported after 2021.10 release.

**Comment by thecode** [comment]
Next core version (2021.10.0) will support Shelly Plus and Pro devices
