### ISSUE TITLE
use Energy usage graph for other entitys

### ISSUE THREAD

**Issue by alexswart** [home-assistant/home-assistant.github.io#19451]
### Feedback

i like it to use the style of the energy usage graph for other entity's
so that i can see what was the usage of my fridge or other electical equipment per hour, day, month etc

### URL

https://www.home-assistant.io/lovelace/energy/

### Version

2021.9.7

**Comment by frenck** [comment]
They are statistics graphs: <https://www.home-assistant.io/lovelace/statistics-graph/>
