### ISSUE TITLE
Minor typo - its vs it's

### ISSUE THREAD

**Issue by ApricotFarm** [home-assistant/home-assistant.github.io#19460]
### Feedback

There is a minor typo which should be corrected here:

https://www.home-assistant.io/integrations/template#change-the-icon-when-a-state-changes

In the following two sentences: 

> This example demonstrates how to use template to change the icon as it’s state changes. This icon is referencing it’s own state.

The word `it's` should be changed to `its` (no apostrophe for possessive form) 

### URL

https://www.home-assistant.io/integrations/template#change-the-icon-when-a-state-changes

**Comment by cgtobi** [comment]
Feel free to click that `Edit` button at the bottom of the page and add yourself to the list of contributors.  👍

**Comment by ApricotFarm** [comment]
I can't bring myself to do that for something so trivial...maybe when I contribute something a bit more substantive :-)
