### ISSUE TITLE
No gas in the new energy dashboard?

### ISSUE THREAD

**Issue by Hippe-Lip** [home-assistant/home-assistant.github.io#19461]
### Feedback

My DSMR4 energy meter is connected using a USB connection (/dev/ttyUSB0). I can see all electricity values and in the entities I can see a sensor.gas.consumption, but the energy panel shows me grid, solar and home (they work fine), but no gas. Tapping on the sensor.gas.consumption in entities shows me the usage graph, so the information is getting there, but it simply doesn’t show…

I couldn’t find any configuration items that could help, so my question is: why isn’t gas showing up in my energy panel?

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2021.9.7

### Additional information

Meter: dsmr4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by Hippe-Lip** [comment]
Sorry for late reaction, but this wasn’t a call for help. 
This was to point you to the fact that the energy panel automatically picks up the electricity meter, but lacks the existing gasmeter. 
I thought this to be an omission in the standard configuration and wanted to point that out as a suggestion for improvement. 
That’s all.

**Comment by frenck** [comment]
You have provided documentation feedback, while you are trying to report an issue with an integration that is not working with the energy integration, that is considered a bug and not fixable by adjusting the documentation.

Reporting issues with integrations can be done here:

<https://github.com/home-assistant/core/issues>

../Frenck
