### ISSUE TITLE
Home Assistant behind Reverse Proxy

### ISSUE THREAD

**Issue by Brulijam** [home-assistant/home-assistant.github.io#19468]
### Feedback

Hi,
I am running HA on docker on synology nas.
Docker created a network bridge that HA is using.
Docker assigned 172.17.0.2 to HA.
Authorization of Fitbit is not possible because HA returns http://172.17.0.2:8123/api/fitbit as redirect uri.
HA is accessable through https://home-assistant.[domain] and the redirect url should be https://home-assistant.[domain]/api/fitbit.
When accessing https://home-assistant.[domain]/api/fitbit I get redirected to fitbit.com/oauth2/authorize and the fitbit answers with "Developer information: invalid_request - Invalid redirect_uri parameter value"

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2021.9.7

**Comment by frenck** [comment]
- `Invalid redirect_uri parameter value`

This means there is a mismatch between the application configuration you created at FitBit & your Home Assistant setup. The URLs need to match. Home Assistant will detect the URL to use based on your browser and internal/external URL settings.

This is not a documentation issue. 

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
