### ISSUE TITLE
Error: unknown flag: --content-trust

### ISSUE THREAD

**Issue by flattery103** [home-assistant/home-assistant.github.io#19475]
### Feedback

You may need to revise your directions or you are missing a step or something.

### URL

https://www.home-assistant.io/more-info/unsupported/content_trust/

### Version

2021.9.7

**Comment by frenck** [comment]
Tested using the latest versions:

![image](https://user-images.githubusercontent.com/195327/134804208-51b05f37-fc2f-4b2c-bd62-1429e9bb1161.png)

You might need to look into updating your system? Anyways, the documentation is correct.

**Comment by KMDobrev** [comment]
This code is not working for me.

**Comment by frenck** [comment]
In that case, file a bug report in the appropriate repository, as it is not a documentation issue (this is provided by you are documentation feedback).

See our website for more information on where to go: <https://www.home-assistant.io/help>

Thanks 👍

**Comment by giantorth** [comment]
![image](https://user-images.githubusercontent.com/56210456/135120792-da621622-6649-46bb-a34c-bb1deb853c80.png)
Using core-2021.9.7 and supervisor-2021.09.4 I get this message from the host OS shell.  Does this command need to be run inside a docker container?

**Comment by KMDobrev** [comment]
> ![image](https://user-images.githubusercontent.com/56210456/135120792-da621622-6649-46bb-a34c-bb1deb853c80.png) Using core-2021.9.7 and supervisor-2021.09.4 I get this message from the host OS shell. Does this command need to be run inside a docker container?

It's exactly the same with me.

**Comment by frenck** [comment]
Don't use the Host OS to manage your system, use the SSH & Terminal add-on for those proposes

**Comment by giantorth** [comment]
Just tested with ssh addon and got identical result.

**Comment by frenck** [comment]
See above it works, feel free to raise an issue on the appropriate repository in case it doesn't work with reproduction details.

This issue is part of our documentation, for which we concluded the documentation is on par, hence this issue is closed and handled.

Thanks 👍

**Comment by giantorth** [comment]
Just one final comment, I manually installed os-agent again on my machine from the official repo and the 'unsupported installation' warning has since disappeared.  
Despite apparently fixing the issue, the command listed in the documentation still responds with an 'unknown flag' error when attempted.  Is this an issue with os-agent or the supervisor specifically in this case?  I'm not sure where the correct location to file a bug would be in these circumstances.

**Comment by frenck** [comment]
Sorry, its not a documentation issue.
