### ISSUE TITLE
How to install libraries mentioned in the documentation?

### ISSUE THREAD

**Issue by kiro7shiro** [home-assistant/home-assistant.github.io#19473]
### Feedback

In the documentation for the DHT22 sensor. Is described if one wants to use it, you first have to install `libgpiod2` via the command:

`sudo apt install libgpiod2`

But in the Home Assistant cli I don't have access to this or it's not even installed.

How am I suposed to install these dependencies?

### URL

https://www.home-assistant.io/integrations/dht/

### Version

2021.9.7

**Comment by frenck** [comment]
These only apply to manual installation types. For our Home Assistant OS, Supervised and Container, we already provide all needed dependencies.
