### ISSUE TITLE
Reauth often

### ISSUE THREAD

**Issue by askthomas** [home-assistant/home-assistant.github.io#19477]
### Feedback

This plugin ask for reconfugure every 2 days to the scale, have 2 persons in app. it ask for booth users.

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi there @askthomas 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. I'm not sure how we can fix this in documentation.

Please report issues with Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
