### ISSUE TITLE
Camera Integration

### ISSUE THREAD

**Issue by amathews84** [home-assistant/home-assistant.github.io#19471]
### Feedback

Is there any chance you can add camera integration?  Since Nest has direct integration with Smartthings I was hoping to bring in my Nest Hello Doorbell.

Also would a Nest thermostat be available when integrating Smartthings to Home Assistant?

### URL

https://www.home-assistant.io/integrations/smartthings/

### Version

2021.9.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
