### ISSUE TITLE
Extend valid domains

### ISSUE THREAD

**Issue by akloeckner** [home-assistant/home-assistant.github.io#19481]
### Feedback

The docs state:

> `domain`: The domain name this blueprint provides a blueprint for. Currently, only `automation` is supported.

However, my 2021.8.3 install ships with a `script` example blueprint. 

I suggest to extend the description to the correct supported domains. If implementation is currently ongoing, I suggest to include a link to the current state.

### URL

https://www.home-assistant.io/docs/blueprint/schema/

### Version

2021.9.7

**Comment by frenck** [comment]
Thanks for reporting @akloeckner 👍 

I've opened a PR to add the domain. There is nothing to link to for more information (as this is an open source project, which relies on contributions from others made in their free spare time, we cannot plan or predict that).
