### ISSUE TITLE
Not connecting to Dyson cloud

### ISSUE THREAD

**Issue by myevit** [home-assistant/home-assistant.github.io#19499]
### Feedback

Logger: homeassistant.components.dyson
Source: components/dyson/__init__.py:60
Integration: dyson (documentation, issues)
First occurred: 21:28:57 (1 occurrences)
Last logged: 21:28:57

Not connected to Dyson account. Unable to add devices

double checked login info, tested on dyson web site

### URL

https://www.home-assistant.io/integrations/dyson/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi there @myevit 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
