### ISSUE TITLE
Added "name" in configuration but does not change firendly_name

### ISSUE THREAD

**Issue by vistalba** [home-assistant/home-assistant.github.io#19510]
### Feedback

I added the "name" parameter to the configuration to rename the entity in the energy tab.
After adding "name" and restart of the server the "friendly_name" in the dev-tab still shows the old auto generated friendly_name. 

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.9.7

**Comment by dgomes** [comment]
Please submit the issue in the core repository and fill in the complete issue template
