### ISSUE TITLE
 addons/ssh/ perhaps missing information?

### ISSUE THREAD

**Issue by geoffreygarrett** [home-assistant/home-assistant.github.io#19514]
### Feedback

Installed the add-on, cannot SSH into the homeassistant OS on my raspberry pi, there's definitely documentation missing because the README on the SSH app has no leads.

### URL

https://github.com/home-assistant/addons/tree/master/ssh

**Comment by ludeeus** [comment]
That is documented on the "Documentation" tab inside the addon.
or here if you prefer <https://github.com/home-assistant/addons/blob/master/ssh/DOCS.md>
