### ISSUE TITLE
Unclear output of datetime.py

### ISSUE THREAD

**Issue by jdrescher2006** [home-assistant/home-assistant.github.io#19518]
### Feedback

In the example "USAGE OF JSON ATTRIBUTES IN COMMAND OUTPUT" the output of the datetime.py script is unclear. If you do not provide this file, you need at least to give the json output data.

### URL

https://www.home-assistant.io/integrations/sensor.command_line/

### Version

2021.9.7

**Comment by frenck** [comment]
The goal of that documentation is not to show the scripts that are run, but the usage of the configuration of the command_line sensor itself. That example (as described) shows how to process a command that outputs a JSON format.

What that command does or how it works, isn't relevant for the example.

Nevertheless, thank you for the feedback 👍

**Comment by jdrescher2006** [comment]
The problem is that I am not abvle to get this example running. I get 2 error messages:
Unable to parse output as JSON: {'time': '03:53:25 AM', 'milliseconds_since_epoch': 1362196405309, 'date': '03-02-2013'}
And:
Template variable error: 'value_json' is undefined when rendering '{{ value_json.time }}'

My guess is that the python scrpt is not giving the correct json on which the example is based.

In order to understand the correct syntax and how all the functions are playing together, for me this example makes no sense because a crucial part is missing.

**Comment by jdrescher2006** [comment]
My python script only does this:
print ({"time": "03:53:25 AM","milliseconds_since_epoch": 1362196405309,"date": "03-02-2013"})
