### ISSUE TITLE
Compatibility with newer models

### ISSUE THREAD

**Issue by lambrosfl** [home-assistant/home-assistant.github.io#19527]
### Feedback

Thank you for this integration, but unfortunately it is missing compatibility with latest Levoit air purifiers, like 400S and 300S.
Can you update it to get compatibility with 400S?

Thank you

### URL

https://www.home-assistant.io/integrations/vesync/

### Version

2021.9.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
