### ISSUE TITLE
How to authenticate with Control4

### ISSUE THREAD

**Issue by knwpsk** [home-assistant/home-assistant.github.io#19529]
### Feedback

How does HomeAssistant gain access to Control4? What credentials will I need?

I've moved into a home with a pre-existing Control4 setup.
I'm interested in taking more control so I don't need to use an installer for all changes. So, of course, I'm investigating installing HomeAssistant.
In the Control4 integration page, there's no indication of how HA+Integration will gain access to my C4 controller. Doesn't it need some credentials? Will that be simply my home-user credentials? Or will it have to have root or installer access to work with the controller?

It's important to me to know that this will work, and how it will work, before I invest a lot of time into installing and learning to use HA.

Thanks for any advice!

### URL

https://www.home-assistant.io/integrations/control4/

### Version

2021.9.7

**Comment by lawtancool** [comment]
Hi @knwpsk!

The integration just uses your Control4 mobile app login credentials. If you can login using the Control4 app, you can use this integration.

**Comment by knwpsk** [comment]
Great, thanks @lawtancool, this helps. (Suggest you might put that info on the Integration's page:
https://www.home-assistant.io/integrations/control4/

**Comment by knwpsk** [comment]
@lawtancool I've installed HA Blue device, got it connected to Control4. Now I have questions:
1. I see many of my Control4 devices but not all of them. In particular I don't see all of my 5-way programmable "keypad" devices -- it seems the ones that are "loaded" (have a light fixture directly connected to them) show up; but the ones with no "load" are not showing up. I had hoped that HA would allow me to program some routines when any of those 5 buttons on a keypad were pressed. Do you know why those non-loaded keypads aren't present in HA? Can that be fixed?

2. I only see "lighting" devices. I don't see other devices that are present in my Controller showing up in HA. For example, my Controller connects to my receiver and to a sound switch and a video switch. It looks like when you guys coded this Integration you only included the lighting stuff (correct?). Is there hope that you'll include the entertainment devices too?

I don't see a way to private message you with this stuff.... sorry.

**Comment by lawtancool** [comment]
Hi @knwpsk,

Those two things you mentioned are known limitations of the integration. Home Assistant can only recognize actual light devices, not keypad keys. Lighting is also the only device supported. 

The underlying pyControl4 library supports more devices, but I unfortunately do not have time to implement them in Home Assistant. Contributions are always welcome of course!

**Comment by knwpsk** [comment]
> Hi @knwpsk,
> 
> Those two things you mentioned are known limitations of the integration. Home Assistant can only recognize actual light devices, not keypad keys. Lighting is also the only device supported.
> 
> The underlying pyControl4 library supports more devices, but I unfortunately do not have time to implement them in Home Assistant. Contributions are always welcome of course!

OK, first, THANKS for the rapid reply!
I'd love to help/contribute, but don't know python... maybe I need to learn it!?

So, for now, what can I do with it?
- Obviously I can create _scheduled_ routines for lighting
- I could create routines driven by triggered events that HA knows, such as "I just got home"
- I don't see a way to create routines based on actions that I take, like "press a button". Any help with that?
