### ISSUE TITLE
Nie da się skonfigurować integracji

### ISSUE THREAD

**Issue by casper255** [home-assistant/home-assistant.github.io#19521]
### Feedback

W momencie konfiguracji integracji otrzymuję komunikat "Identyfikator stacji pomiarowej nie jest prawidłowy". Numer stacji wyszukany wg dokumentacji integracji

### URL

https://www.home-assistant.io/integrations/gios/

### Version

2021.9.7

**Comment by bieniu** [comment]
I jaki to numer stacji?

**Comment by casper255** [comment]
805. Ale np 814 czy 837 też nie działa. 

W dniu 29 wrz 2021, 13:31, o 13:31, użytkownik Maciej Bieniek ***@***.***> napisał:

**Comment by bieniu** [comment]
Issues related to the integration should be opened here https://github.com/home-assistant/core
