### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by behnam85** [home-assistant/home-assistant.github.io#19538]
### Feedback

Logger: homeassistant.components.statistics.sensor
Source: components/statistics/sensor.py:194
Integration: statistics (documentation, issues)
First occurred: 12:29:47 AM (1 occurrences)
Last logged: 12:29:47 AM

sensor.for_more_detail_please_enter: parsing error, expected number and received None

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2021.9.7

**Comment by behnam85** [comment]
After Reload Statist Entitys , will become State unknown
After restart Homeassistant, it works

**Comment by behnam85** [comment]
Attributes
Sampling size
1000
Count
0
Mean
unknown
Median
unknown
Quantiles
unknown
Standard deviation
unknown
Variance
unknown
Total
unknown
Min value
unknown
Max value
unknown
Min age
October 1, 2021, 1:24:58 AM
Max age
October 1, 2021, 1:24:58 AM
Change
unknown
Average change
unknown
Change rate
unknown

**Comment by behnam85** [comment]
![Screenshot_2021-10-01-01-28-32-057_io homeassistant companion android](https://user-images.githubusercontent.com/71830953/135538677-e258480b-e4a7-49dd-94e4-415f6b897174.jpg)

**Comment by fabaff** [comment]
The `statistics` sensor consumes the data from another sensor. If that sensor is not working properly then the `statistics` sensor doesn't either.

**Comment by behnam85** [comment]
I’ve been adding some statistics into my config and using the Reload Server management from Configuration > Server Control it's work. but when reload  Statist Entities from Configuration>server Control will become State unknown.

**Comment by frenck** [comment]
Hi there @behnam85 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
