### ISSUE TITLE
Add Modern Forms preset modes

### ISSUE THREAD

**Issue by tscibilia** [home-assistant/home-assistant.github.io#19539]
### Feedback

I'm not sure if this is a preset mode or a service (like the sleep timers), but my fan has a breeze mode that I'd like to activate.  

### URL

https://www.home-assistant.io/integrations/modern_forms/

### Version

2021.9.7

### Additional information

![Screenshot 2021-09-30 172112](https://user-images.githubusercontent.com/585808/135531855-05ac872d-c7b7-4ad4-b9e1-1241fbbdd05e.jpg)

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by tscibilia** [comment]
ok thanks. In case anyone finds this issue here, I'll link to the feature request I created...
https://community.home-assistant.io/t/modern-forms-add-additional-modes-breeze-mode/343140
