### ISSUE TITLE
Samsung Family Hub camera view not workinjg

### ISSUE THREAD

**Issue by DAB42** [home-assistant/home-assistant.github.io#19540]
### Feedback

Configured in configuration.yaml per Home Assistant documentation but no image displayed in Picture Glance Card.

### URL

https://www.home-assistant.io/integrations/familyhub/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi there @DAB42 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
