### ISSUE TITLE
Hydrawise Integration Limitation

### ISSUE THREAD

**Issue by WorldOfMaze** [home-assistant/home-assistant.github.io#19558]
### Feedback

The [Hydrawiser ](https://hydrawiser.readthedocs.io/en/latest/) code, which is used in this add-on, has a [limitation ](https://hydrawiser.readthedocs.io/en/latest/#limitations)that only one controller is supported.  It would helpful if this was noted in the documentation.  After spending quite a bit of time trying to get two controllers to work in HA and digging thru the code in GitHub, I tracked down the limitation.

Thanks.

### URL

https://www.home-assistant.io/integrations/hydrawise/

### Version

2021.9.7

**Comment by frenck** [comment]
The YAML makes this clear already as this is not a list or dictionary that is shown, but a fixed mapping.

Hopefully multiple can be supported in the future when the integration is ported to the UI.

> which is used in this add-on

Please note, this is an integration, not an add-on. Add-ons and integrations are not the same things.

**Comment by WorldOfMaze** [comment]
Thanks for the response, @frenck.  For those of you more familiar with HA, the YAML may make it clear but for us newbies, having the limitation spelled out more clearly in the doc would be helpful.
