### ISSUE TITLE
doorbell ezviz

### ISSUE THREAD

**Issue by liuk84** [home-assistant/home-assistant.github.io#19555]
### Feedback

please can you insert, since I have a doorbell db1 ezviz doorbell also the sensor that detects the pressure of the doorbell? it is essential to run subsequent automations

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.9.7

### Additional information

please can you insert, since I have a doorbell db1 ezviz doorbell also the sensor that detects the pressure of the doorbell? it is essential to run subsequent automations

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
