### ISSUE TITLE
How to read clients traffic from Cisco switch c3650

### ISSUE THREAD

**Issue by KirkKirk** [home-assistant/home-assistant.github.io#19550]
### Feedback

HI,

Recently started learning about Home Assistant and I found it is an extremely good platform.
I've done a few automation and I am very satisfied with it.
As a beginner, I am trying to figure out how to show traffic individually for the devices present on my home network.
For example, on the HA dashboard I would like to have live data traffic for a device with MAC: xx:xx:xx:xx:xx.
I tried with device_tracker and it's working fine but that is only for tracking presence.
I will appreciate any step by step guidance.

Thanks,
Kirk

### URL

https://www.home-assistant.io/integrations/cisco_ios/

### Version

2021.9.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
