### ISSUE TITLE
Request: Dimming support

### ISSUE THREAD

**Issue by pr3sidentspence** [home-assistant/home-assistant.github.io#1955]
It would be great if dimmer support could be added.

My understanding is powerline commands can set an arbitrary dim level (xdim), but rf (my situation) can only send the dim command. The former could use the standard dim slider, but the latter would need a dim button.

**Comment by Landrash** [comment]
Suggestions can be done in the forums.
This repository is for the documentation for Home Assistant.

**Comment by pr3sidentspence** [comment]
Oh, sorry.
