### ISSUE TITLE
Please add "Next" and "Previous" buttons to the bottom of every documentation page.

### ISSUE THREAD

**Issue by remulasce** [home-assistant/home-assistant.github.io#19568]
### Feedback

It's annoying trying to read the documentation from cover to cover because there's no easy way to just get to the next page. Some individual documentation pages have a text link to the next chapter at the bottom, but others don't, and some of them have multiple links.

So you end up having to scroll way back up to get to the navigation sidebar on the right. Then you need to scan all the sections to find the current one, and then click the next one.

It would be better if the documentation page template automatically put a next / previous button at the bottom of every doc page. Perhaps the bottom of the navigation sidebar would be a good place to share these buttons.

### URL

https://www.home-assistant.io/docs/automation/editor/

### Version

2021.9.7

**Comment by frenck** [comment]
There is no next/previous (as in, subject-wise), adding those buttons would be equally as weird in that case. We do use those, in case it does apply (for example, the getting started guide).

Nevertheless, thanks for the suggestion! 👍

**Comment by remulasce** [comment]
I know it's not necessarily meant to be read back-to-front, but there _is_ an order shown in the navigation sidebar. 
![image](https://user-images.githubusercontent.com/1064048/135942492-eb3d1233-b773-42c1-8efc-f23aee4ac426.png)

It seems like a pretty reasonable reading order. For instance, a user reading up on "Automation" would super reasonably want to read each of its subpages, and Conditions makes sense right after Triggers.

Lots of doc pages have global Next | Prev, eg [Python](https://docs.python.org/3/tutorial/datastructures.html#dictionaries), even if they don't all have subject-wise associations. It's not about being subject-wise, it's just a normal UX affordance.

**Comment by frenck** [comment]
>  It's not about being subject-wise, it's just a normal UX affordance.

We know, it has been applied on places we found appropriate, which I already mentioned in my previous response.
