### ISSUE TITLE
Top down shades support?

### ISSUE THREAD

**Issue by ihagens** [home-assistant/home-assistant.github.io#19572]
### Feedback

we have top down shades. they can drop down the top as well. however the controls for these actions are not included in tis software.

### URL

https://www.home-assistant.io/integrations/hunterdouglas_powerview/

### Version

2021.9.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
