### ISSUE TITLE
cable device is delayed

### ISSUE THREAD

**Issue by rhgiter** [home-assistant/home-assistant.github.io#19571]
### Feedback

i have issues with device on cable , in my case there is a delay on 3 hours --   wifi device works fine. 

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2021.9.7

**Comment by Kane610** [comment]
This is the project for the hass homepage and integration documentation. If you want to report an issue with the integration you should report it on the ha core project.

Furthermore you should try to be more descriptive in your issue as what you have written is far from enough to go on.
