### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by Nickleaton** [home-assistant/home-assistant.github.io#19587]
### Feedback

Would be useful to handle cookies and persist for a long time.

https://map.blitzortung.org/#5/51.102/-0.639

Is an example of a useful image to embed

### URL

https://www.home-assistant.io/lovelace/iframe/

### Version

2021.9.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
