### ISSUE TITLE
Energy Usage Dashboard in HA

### ISSUE THREAD

**Issue by anatwick** [home-assistant/home-assistant.github.io#19598]
### Feedback

would be nice to be able to use this sensor for the energy dashboard in ha:  https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

### URL

https://www.home-assistant.io/integrations/srp_energy/

### Version

2021.9.7

**Comment by briglx** [comment]
This looks like a great feature request.

**Comment by briglx** [comment]
I have a pull request open for this https://github.com/home-assistant/core/pull/58554

**Comment by frenck** [comment]
This is submitted as documentation feedback. There is no amount of documentation I can adjust to add such a thing.
