### ISSUE TITLE
Panasonic Comfort Cloud  ( has energy useage entity but wont show up ) 

### ISSUE THREAD

**Issue by vjmaz** [home-assistant/home-assistant.github.io#19595]
### Feedback

Hi team I was hoping to add the HACS integration Panasonic Comfort Cloud to my energy usage in the energy tab .with its two sensors daily_energy or _current_power one of them actually shows the usage , the problem is I cant tell you which one as HA has decided not to work with Panasonic Comfort Cloud integration the moment i started to write this up !!! go figure ..

Anyway I'm hoping someone might be able to get the entity added some how to work as my unit does use a lot of power 

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2021.9.7

**Comment by frenck** [comment]
> Hi team I was hoping to add the HACS integration Panasonic Comfort Cloud to my energy usage in the energy tab 

Custom integration are not supported by the Home Assistant project. If they don't work as expected, please report those issues with the integration author, not Home Assistant.

Thanks! 👍 

../Frenck
