### ISSUE TITLE
Error installing the integration

### ISSUE THREAD

**Issue by Roger4R** [home-assistant/home-assistant.github.io#19590]
### Feedback

I'm trying to enter the username and password (it's correct by site https://server.growatt.com) to integrate, an error occurs: Unknown error. 
Any ideas?
Tks.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.9.7

**Comment by muppet3000** [comment]
@Roger4R that's odd. It might be that the integration doesn't support your type of Growatt system yet.
Can you post me a picture like the below so I can see what type of system you have:
![GrowattSystemType](https://user-images.githubusercontent.com/10612068/135807585-341ad456-5058-47d4-a3e8-1955727a428b.PNG)

**Comment by indykoning** [comment]
Until 2021.10.0 the integration had the bug that it would return an unknown error if the login credentials were invalid.
If after the update you still get the unknown error could you try checking your home assistant logs? It should have some more information available there

**Comment by Roger4R** [comment]
Ok, 

I’ll try to install the new version and try it out. 

Hugs.

**Comment by hcostelha** [comment]
I had a similar problem. I updated today (running now core-2021.10.1, supervisor-2021.09.6 and Home Assistant OS 6.4), removed and added again the Growatt device, and is now working fine.

**Comment by Roger4R** [comment]
Hello my friends, It’s works now!

Core-2021.10.1, Supervisor-2021.09.6 and Home Assistant OS 6.4

Thanks.
