### ISSUE TITLE
Monoprice blackbird HDMI matrix 4 x 4 notworking

### ISSUE THREAD

**Issue by francoislegrange** [home-assistant/home-assistant.github.io#19601]
### Feedback

I can connect to the ip address over http

config as follows
media_player:
  - platform: blackbird
    host: !secret blackbird_ip
    zones:
      1:
        name: BB Master Bedroom
      2:
        name: BB Living Room
      3:
        name: BB BBQ TV
      4:
        name: BB Jacuzzi TV

    sources:
      1:
        name: BB ChromeCast
      2:
        name: BB Kodi
      3:
        name: BB Foxtel
      4:
        name: BB Not Used

### URL

https://www.home-assistant.io/integrations/blackbird/

### Version

2021.9.7

### Additional information

Logger: homeassistant.components.media_player
Source: components/blackbird/media_player.py:88
Integration: Media player (documentation, issues)
First occurred: 10:03:09 AM (1 occurrences)
Last logged: 10:03:09 AM

Error while setting up blackbird platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/blackbird/media_player.py", line 88, in setup_platform
    blackbird = get_blackbird(host, False)
  File "/usr/local/lib/python3.9/site-packages/pyblackbird/__init__.py", line 263, in get_blackbird
    return BlackbirdSync(url)
  File "/usr/local/lib/python3.9/site-packages/pyblackbird/__init__.py", line 176, in __init__
    self.socket.connect((self.host, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by atxbyea** [comment]
https://github.com/home-assistant/core/issues/39330#issuecomment-685098558 @francoislegrange

**Comment by frenck** [comment]
Hi there @francoislegrange 👋 

It seems like you want to report an issue with an integration, however, you have submitted documentation feedback instead.

Please report issues with integrations in the core issues tracker here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by atxbyea** [comment]
I have updated the documentation in a PR to reflect the actual supported device better.

https://github.com/home-assistant/home-assistant.io/pull/19710
