### ISSUE TITLE
fitbit integration: clarify that external URL is required for auth to work

### ISSUE THREAD

**Issue by ammgws** [home-assistant/home-assistant.github.io#19604]
### Feedback

After playing around trying to get the Fitbit integration to work, I realised that HA needs to have an external URL setup for the OAUTH flow to complete successfully. 

In my case I access HA (and the rest of my local network) remotely via VPN so this isn't an option for me - it would have been nice if it was explicitly mentioned in the docs.

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2021.9.7

**Comment by frenck** [comment]
FitBit uses OAuth2, which isn't required to be public accessible in its specifications.
It could be a specific FitBit requirement, however, that would not be according to specifications. Could you point me to a FitBit resource that states this is required?

**Comment by ammgws** [comment]
I believe it's because they require HTTPS for all URIs including the redirect/callback: https://dev.fitbit.com/build/reference/web-api/oauth2/#redirect-uris. So perhaps I should have said: "clarify that the integration requires your Home Assistant instance to be have a valid SSL certificiate" ?

Maybe I just have to setup a self-signed cert for my Home Assistant instance?

**Comment by frenck** [comment]
`The redirect URI requires HTTPS protocol.`

Aah right! I see, not sure if a self-signed cert will work, it might?

Anyways, I agree, we should add something in that case.

**Comment by ammgws** [comment]
Used `mkcert` to get a trusted SSL certificate for Home Assisant and now the integration is authorized and (seemingly) working. 

The redirect behaved a bit weirdly, but I guess that's a separate issue:

After clicking "Allow", the response from the callback URI (myhomeassistantIP:8123/api/callback) is served up as a file instead of redirecting to an actual page:

![image](https://user-images.githubusercontent.com/20397027/136015673-4aede8c4-fd2f-45f9-93b3-acca7a228ac2.png)

![image](https://user-images.githubusercontent.com/20397027/136015933-d4d9520d-26f5-4416-9728-183332e2edfd.png)

Also if you unknowingly keep clicking on the "Allow" button then you end up with multiple duplicates :laughing: 
![image](https://user-images.githubusercontent.com/20397027/136018454-41bb3f3a-510b-4b5c-b30b-533ac989130c.png)

EDIT: Looks like this has been "broken" for quite a while... post from 2020: https://community.home-assistant.io/t/fitbit-unable-to-authorize/80470/32?u=hoassmeintant

**Comment by ammgws** [comment]
Close via https://github.com/home-assistant/core/pull/57116
