### ISSUE TITLE
Broken Integration

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#19618]
### Feedback

Can the documentation for this integration be updated to properly indicate that doesn't work and there are no plans to fix it? I've wasted over $2000 on useless crap from eight sleep I thought I was going to be able to use. Now I can't return it.

### URL

https://www.home-assistant.io/integrations/eight_sleep/

### Version

2021.9.7

**Comment by frenck** [comment]
Hi @mikegrb 👋 

Sorry to hear you had a negative experience setting up the integration. Looking at our public analytics, 37 installations currently report the integration in active use. The integration and underlying libraries had updates 3 months ago.

However, it sounds like you should file a bug report so we can get things fixed. That is way more helpful for everybody. For that, please open an issue here:

<https://github.com/home-assistant/core/issues>

And lets take it from there 👍 

../Frenck

**Comment by mezz64** [comment]
Thanks @frenck.  Please do open an issue either here or on the pyEight repository and I can take a look to see what isn't working for you.
