### ISSUE TITLE
MQTT "property state_class not allowed"

### ISSUE THREAD

**Issue by DJF3** [home-assistant/home-assistant.github.io#19615]
### Feedback

Documentation lists "`state_class`" as a variable.

When using this variable (in VS code) I get a "`Property state_class not allowed`"

Is this a VS Code problem, HA core problem or an MQTT problem?

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/#state_class

### Version

2021.9.7

**Comment by emontnemery** [comment]
Please report this on the vscode plugin, it's not a bug in Home Assistant core 👍

**Comment by DJF3** [comment]
> Please report this on the vscode plugin, it's not a bug in Home Assistant core 👍

Done [here](https://github.com/hassio-addons/addon-vscode/issues/326)
