### ISSUE TITLE
Example json is not provided

### ISSUE THREAD

**Issue by cartwrightian** [home-assistant/home-assistant.github.io#19627]
### Feedback

Example json that relates to example configuration is not provided or linked, this makes it hard to understand the example and how it might be applied to specific json.

### URL

https://www.home-assistant.io/integrations/rest/

### Version

2021.10.0

**Comment by frenck** [comment]
I'm confused, there is no reference to any JSON on that page...

**Comment by BrckedmyRMpro** [comment]
@frenck 
I think that is what he is saying. There is currently no Json example. He would like a Json example to be provided to make it easier to understand how to implement the rest function

**Comment by frenck** [comment]
Its the same as what is provided, the URL might be different though, but 🤷 there is no difference

Hence I don't understand the suggestion given

**Comment by cartwrightian** [comment]
The config example refers to things like

' json_attributes_path: "$.response.system"
        value_template: "OK"
        json_attributes:
          - "runstate"
          - "model"
          - "opmode"
          - "freeze"
          - "time"
          - "sensor1"
          - "sensor2"
          - "sensor3"
          - "sensor4"
          - "sensor5"
          - "version"'

I just thought it would aid understanding to provide at example of the json payload this config operates on?

**Comment by frenck** [comment]
`json_attribute_path` provides the JSON path to the payload of the attribute, and `json_attributes` specifies which attributes to pick from that result (as described in the configuration settings of the rest sensor).

```json
{
  "response": {
    "system": {
      "runstate": "some value",
      "model": "some value",
      "opmode": "some value",
      ...
    }
  }
}
```
