### ISSUE TITLE
Manual integration documentation

### ISSUE THREAD

**Issue by GordonMoll** [home-assistant/home-assistant.github.io#19632]
### Feedback

What is the point of the new armed_vacation mode?  How does the Manual alarm behave any differently?

### URL

https://www.home-assistant.io/integrations/manual/

### Version

2021.10.0

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
