### ISSUE TITLE
Can add only one device ?

### ISSUE THREAD

**Issue by dragonfly69** [home-assistant/home-assistant.github.io#19639]
### Feedback

Hi, I just reconfigure my Tuya integration ( new version with IoT account ) and unfortunately can't have both of my devices :(, What ever I do integration always sees only one - always the same one... How can I force it see both devices ?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.0

**Comment by frenck** [comment]
Hi there @dragonfly69 👋 

It seems like you want to report an issue with an Home Assistant integration OR are looking for support. Unfortunately, you have submitted documentation feedback instead, which is not helping you with either of those two possibilities.

If you want to report a bug with a Home Assistant integration, please file a bug report here:

<https://github.com/home-assistant/core/issues>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
