### ISSUE TITLE
Vane Control

### ISSUE THREAD

**Issue by jsielect** [home-assistant/home-assistant.github.io#19643]
### Feedback

Hunter Douglas/Luxaflex make a blind called Twist, where you can control the position of the vanes in addition to the blind position (it has two speed motor to do this). Although I can get round this by using 'scenes' it would be nice to be able to control the vane position directly

### URL

https://www.home-assistant.io/integrations/hunterdouglas_powerview/

### Version

2021.10.0

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
