### ISSUE TITLE
Instructions don't allow for mobile web interface in Google Chrome

### ISSUE THREAD

**Issue by smithbill17** [home-assistant/home-assistant.github.io#19640]
### Feedback

The old Tuya integration has stopped working and users are now compelled to use this new integration (without prior warning!) that requires signing up for a Tuya IoT developer account and following the provided instructions.

However, the instructions simply do not match the web experience for users trying to follow them on a mobile web browser (Google Chrome).

Expected resolution: update these instructions appropriately for users accessing the Tuya IoT web portal using a mobile web browser.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.0

**Comment by smithbill17** [comment]
While signing up for the Tuya IoT account, it was apparent that the "Smart Home Devices Management" API service (Basic Edition $0) has a "Validity Period" of 12months - installation instructions for this integration needs to clarify that the API service will be free 'in perpetuity' and whether it requires renewal (at $0) after 12months.

**Comment by jwildman16** [comment]
I can confirm the issue described in #20549 is still present as of December 2, 2021.

**Comment by jwildman16** [comment]
@tuya - any update?

**Comment by smithbill17** [comment]
In addition to my original observation, it was apparent that the Tuya IoT 'Core' service is initially for 1-3months. There was an open ticket mentioning this, which directed me to 'apply' for a 12month extension - however, it took me sometime to realise that this simply does NOT work if you are using a mobile browser (eg. Chrome on Android). You *have* to use Chrome on a PC. Ludicrous!
And anyway, the Core service (if you can call it that) should be for an unlimited period, not 12months!
(and Tuya aren't interested in doing anything to resolve the issues with their integration)
