### ISSUE TITLE
Units of measurenent

### ISSUE THREAD

**Issue by Tom-Heitbrink** [home-assistant/home-assistant.github.io#19642]
### Feedback

It might be handy to define the accepted units of measurement, and possible ways to translate different units to this one. The version of august did accept different values than the one from september/october(current) 

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2021.10.0

**Comment by frenck** [comment]
Hi there, thanks for the feedback, however, it is not simply a matter of units of measurements; more factors are into play (like a lot).

In general, the energy dashboard will offer devices/entities that are capable by default. If an integration doesn't support the energy dashboard, that can be reported and it will be looked into.

Therefore documenting the unit of measurement isn't going to add in this case.

Nevertheless, thanks for thinking along!

../Frenck
