### ISSUE TITLE
Unable to control tuya/smartlife device from Home Assistant

### ISSUE THREAD

**Issue by mwright-git** [home-assistant/home-assistant.github.io#19653]
### Feedback

I have (I believe) followed the instructions for the new tuya integration in that I now have an entity that appears to be connected to my outdoor light strip.

This light strip responds correctly to the android app but does not respond to the home assistant entity being toggled. In fact, when the entity is toggled it just reverts to the current state after a second or so. Note that the entity state does reflect the device state if that state is changed by the app.

Any ideas where to start looking?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.0

**Comment by frenck** [comment]
Hi there @mwright-git 👋 

It seems like you either need support or want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead.

If you want to report an issue, please report it here:

<https://github.com/home-assistant/core/issues>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
