### ISSUE TITLE
Sensibo - Sync AC state

### ISSUE THREAD

**Issue by zivgin** [home-assistant/home-assistant.github.io#19668]
### Feedback

Hi,

The documentaion wasn't clear enough for me, but let's skip that as i was manage to get around it and implament it.

I'd like to know how can i set a state (on\off) from home assistant?
The sensibo keep missing the right state (i'm assuming that the signals that sensibo is sending are lost and not getting all the way to the ac, and then sebsibo thinks the AC is on when in reality it's not).

I then need to go to my cellphone --> open the app --> settings --> sync ac state --> approve

and that is really annoying (especially when it happens at night and i'm half a sleep).

Is there a way to expose the ability to do it from home assistant?
Since if so, i can at least create some kind of automation that will adjust the sync mode automatically.

### URL

https://www.home-assistant.io/integrations/sensibo/

### Version

2021.10.1

**Comment by thecode** [comment]
Sensibo integration has a service to set the assumed state, but it is missing the documentation, if you go to developer tools you can test it:
![image](https://user-images.githubusercontent.com/1858925/136771581-9fb5ecff-f840-4273-ba31-8e085a275a9f.png)

If you are in need of support I highly recommend to try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

We use GitHub for tracking issues with Home Assistant itself, not for providing support.

Thanks! 👍
