### ISSUE TITLE
Installation method is not working for Raspberry Pi home-assistant core

### ISSUE THREAD

**Issue by szimszon** [home-assistant/home-assistant.github.io#19663]
### Feedback

When I try to install home-assistant via 
`pip3 install homeassistant`
it complains about the missing of Rust compiler.

I did every step I saw in the documentation. Please correct the documentation about core installation. Thank you!

### URL

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core

### Version

2021.10

**Comment by gdgeist** [comment]
So many issues with the CORE installation.  Python 3.8+ which means compiling python yourself or running Bullseye.  Rust compiler required.  PyNaCl 1.4 install issues.  Conflicting dependencies.  Thought I would try HASS out after years of Openhab.  Getting the impression either write an image to disk or run a container.

**Comment by frenck** [comment]
Running Home Assistant Core in a Python environment is considered an advanced installation method (which is also listed as such).

If you go that route, we expect a user to be aware of Python and how to set up and manager their Python environment (in many different ways). The documentation lays out the basics, but how you manage and set up your Python environment is up to you (and can be done/managed in even more different methods and ways. For example, I personally prefer using pyenv, with added virtualenv plugin to centrally manage my environments).

If you are not comfortable in managing Python environments, we highly recommend looking into one of the other installation methods offered.
