### ISSUE TITLE
Documentation energy

### ISSUE THREAD

**Issue by wifiuk** [home-assistant/home-assistant.github.io#19669]
### Feedback

Can you list out full list of variables we can use instead of just some?

### URL

https://www.home-assistant.io/lovelace/energy/

### Version

2021.10.1

**Comment by frenck** [comment]
I've just looked at the page, but it looks complete.

What precisely are you missing?

**Comment by wifiuk** [comment]
is there not a full list of queries that can be used, just the handful on that page?

**Comment by frenck** [comment]
These are the energy cards that are available, could you be more concrete on what is missing?

**Comment by wifiuk** [comment]
I'm not sure how else to say It?

Is this a full list of what can be used, or are there other queries that can be used to show the results?

**Comment by frenck** [comment]
> Is this a full list of what can be used

The full list is on that page. That is it, there aren't more cards related to this and the cards don't have any other options available.
