### ISSUE TITLE
How to  enable LG Connect Apps

### ISSUE THREAD

**Issue by bas89** [home-assistant/home-assistant.github.io#19674]
### Feedback

The link in "To begin with enable LG Connect Apps feature in Network settings of the TV instructions." is not working anymore. I actually don't know a similar link.

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2021.10.1

**Comment by thecode** [comment]
Seems like the link was removed by LG, you can use this for now:
https://web.archive.org/web/20180604065840/http://www.lg.com/uk/support/product-help/CT00008334-1437131798537-others
I guess we will need to make our own guide how to enable it
