### ISSUE TITLE
New Tuya integration doesn't work correctly

### ISSUE THREAD

**Issue by fcassirer** [home-assistant/home-assistant.github.io#19675]
### Feedback

Went through the dance at Tuya to create the app developer free trial account.   After walking through the steps I get to the point I have linked the old Tuya account and clicking on `Devices->All Devices` and instead of seeing my devices it is empty.

Now what?  It appears the account is linked.   I chose the Eastern US data center, does this need to match whatever datacenter the Tuya Smart app is using?   Not clear.

Not sure why all of this is now required just to access a few lights, it worked just fine prior to the update.   For most people this is way way way over complicated and you will lose most of them.   If it was forced upon us by Tuya, shame on them, but I suspect there should be a way to just use it as it was without having to subject everyone to the developer account and additional steps, just makes things look less polished and unnecessarily complicated.

my $.02 ... 

Thanks for indulging ... 
-Fred  

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.1

### Additional information

![tuyadev](https://user-images.githubusercontent.com/4642327/136617647-fee0d439-ce73-43ab-bf7c-3ea9369e7c3e.png)

**Comment by Sk33t3rson** [comment]
my devices are not loading in after i linked my account as well for the Tuya Platform

**Comment by fcassirer** [comment]
More info:  Even though the Tuya developer account does not show my devices, I was able to use the secret/client-id in the HA integration and it found the devices so all is well, it is just disconcerting that it doesn't match the docs as described.   Maybe there is an addendum in order for the troubleshooting section.

**Comment by Sk33t3rson** [comment]
> More info: Even though the Tuya developer account does not show my devices, I was able to use the secret/client-id in the HA integration and it found the devices so all is well, it is just disconcerting that it doesn't match the docs as described. Maybe there is an addendum in order for the troubleshooting section.

I have them as well.. but there is some sort of disconnect between HA-Tuya Platform-Smart Life app- Device.. some times color change call works and sometimes it doesnt..

**Comment by waterwayne** [comment]
Thank you HA and Tuya developer for your contribution. Great efforts and really admire the time and enthusiasm you have been putting in.  

Same problem as above:
1. Nothing shown under [All devices] tab -
All setup went smoothly according to the Tuya instruction until the last step. Clicking on Devices-->All Devices and nothing is showing. However, under [Link Tuya App Account], it does seem the linking process went successful. I was linking it with Smartlift app, not sure if linking with Tuya app would make any difference. 

2. Switch status toggles by itself and does not match its latest state -
I was able to discover all switches and smart plugs. The only problem is the device status change then toggle back by itself. For example, light 1 is "OFF", so turn it "ON" fine but the switch in HA would quickly flick back although the light is still ON in about 2 second. I can quick click on the switch ON and OFF, so that an OFF command sent to turn the actual light OFF. I have multiple switch and power strip and they all behave the same.

**Comment by zlinoliver** [comment]
@waterwayne 

1. Please try to select the correct "Data Center" according to your Tuya App Account country region. For details, you can check this documentation to find the correct Data Center and configure in your cloud project: [Country & Data Center](https://developer.tuya.com/en/docs/iot/oem-app-data-center-distributed?id=Kafi0ku9l07qb)
<img width="939" alt="dataCenter" src="https://user-images.githubusercontent.com/907831/136679068-92eebc37-37b1-4b0f-a432-5f8be9563480.png">

2. Please double check if you have selected the "Device status notification" API in the project setting:
![device_notification](https://user-images.githubusercontent.com/907831/136679133-ebf9297b-c42f-45e5-8652-4a5c6411fddf.png)

If not, you can subscribe to it in the "Service API" of your cloud project:

<img width="1146" alt="device_notification_service" src="https://user-images.githubusercontent.com/907831/136679193-d4936bef-dcee-4a08-ab21-4eb6ecf63439.png">

You can check this issue for help: https://github.com/home-assistant/core/issues/57296

**Comment by waterwayne** [comment]
Hi Oliver,
    Thanks so much. The two problems I had are now being resolved with your
prompt instructions. Have a great day and thanks again for your generous
help.

Kind regards,

Wayne

**Comment by Sk33t3rson** [comment]
Yeah the instructions I followed said pick the data center closest to me.. welp that wasn't correct.. everything is showing up now that I loaded the data center for west coast us

**Comment by fcassirer** [comment]
Same here.  It wasn't obvious how to change the data center once you created a cloud project, but backing up a few screens and selecting the Overview and then edit let me change to the Western Americas data center.  Note that it allows you to select multiple data centers, but this apparently doesn't work, I had to remove the Eastern data center tag to make the devices show up.   I think this is simply a matter of tweaking the docs a bit to make sure people aren't confused when the data center the Tuya or SmartLife app apparently had been previously using isn't  the closest one as suggested by the docs.

Thanks for all the help.   I will take this last opportunity to say just because we can do all kind of complex things with a cloud providers API doesn't mean the default integration or interactions should require breaking into the developer options, in many cases this is way overkill and will get in the way of adoption.   Instead, consider an 'advanced' mode where the additional benefits for doing the dev setup are clearly defined.   Thanks for listening.   Keep up the great work!

Thanks
-Fred

**Comment by apworks1** [comment]
I selected Western Europe as DC for Italy and it did not work.
Then I found the above instructions where Central Europe is recommended for Italy and it did not work.
Finally I tried Western America and it worked.

**Comment by Dewieinns** [comment]
Can Confirm, I also had to select Western America in order to make this work as expected.

**Comment by FlyingHavoc** [comment]
This new Tuya integration is just another headache :(

I created the cloud app on iot.tuya.com, but I'm unable to authorize later in my Tuya/SmartLife app using QR code from the app.
Just getting the error in the message:
"You cannot scan the QR code to add a device deployed in another data center"

How come?

The app on iot.tuya has permissions for ALL data centers 
"China Data Center, Central Europe Data Center, India Data Center, Western America Data Center, Western Europe Data Center, Eastern America Data Center"

What to do now? Any idea?

**Comment by FlyingHavoc** [comment]
> This new Tuya integration is just another headache :(
> 
> I created the cloud app on iot.tuya.com, but I'm unable to authorize later in my Tuya/SmartLife app using QR code from the app. Just getting the error in the message: "You cannot scan the QR code to add a device deployed in another data center"
> 
> How come?
> 
> The app on iot.tuya has permissions for ALL data centers "China Data Center, Central Europe Data Center, India Data Center, Western America Data Center, Western Europe Data Center, Eastern America Data Center"
> 
> What to do now? Any idea?

Finally, I was able to login into iot.tuya...
I had to specify ONLY ONE data center, based on the link above
https://developer.tuya.com/en/docs/iot/oem-app-data-center-distributed?id=Kafi0ku9l07qb

For my country it was - "Central Europe Data Center"

So, if you select multiple data center (though this is ALLOWED on iot.tuya) that won't work unless you choose only ONE.

**Comment by fcassirer** [comment]
I found the same, you need to select only one data center.   For me, my assumption is that having previously setup the standard tuya/smartlife app, the app used the Western data center as a behind the scenes default when my devices were configured.   Selecting anything else for the cloud caused them to not show up.  It is not clear if there is a way to make the app select an alternate data center (for me it would be the east coast)

In any case, it does seem to be working once you get the quirky configuration sorted out.  I still believe the entire process is overkill for a few lights, I'm sure for some advanced control it is fine, but most people don't need that, just turn 'em on or turn 'em off ;-)

**Comment by niko123456000** [comment]
in Australia with the Smart Life app, I found that my data centre needed to be Central Europe.

On the HA integration setup, I needed to select 'Germany' as the country, otherwise I received the skill id error. The skill id error code suggestion (ensure your app is created after May 25) was not applicable in my case. 

Fortunately I only own two low-value Tuya switches (Toppersun), otherwise I'd be worried that Tuya is expecting people to pay for the API access, which is currently provided as a trial.

**Comment by niko123456000** [comment]
> > This new Tuya integration is just another headache :(
> > I created the cloud app on iot.tuya.com, but I'm unable to authorize later in my Tuya/SmartLife app using QR code from the app. Just getting the error in the message: "You cannot scan the QR code to add a device deployed in another data center"
> > How come?
> > The app on iot.tuya has permissions for ALL data centers "China Data Center, Central Europe Data Center, India Data Center, Western America Data Center, Western Europe Data Center, Eastern America Data Center"
> > What to do now? Any idea?
> 
> Finally, I was able to login into iot.tuya... I had to specify ONLY ONE data center, based on the link above https://developer.tuya.com/en/docs/iot/oem-app-data-center-distributed?id=Kafi0ku9l07qb
> 
> For my country it was - "Central Europe Data Center"
> 
> So, if you select multiple data center (though this is ALLOWED on iot.tuya) that won't work unless you choose only ONE.

You can select many data centres. On the app console of iot, you can toggle the data centre. Keep doing this until you find the correct match for your app. 

![image](https://user-images.githubusercontent.com/20216236/137833944-3ca16166-5dc2-4b73-9ef5-a9b14e223e67.png)

**Comment by YANG-Mingcong** [comment]
I find out there is a problem:
in this page [https://www.home-assistant.io/integrations/tuya/#28841105-no-permissions-this-project-is-not-authorized-to-call-this-api](https://www.home-assistant.io/integrations/tuya/#28841105-no-permissions-this-project-is-not-authorized-to-call-this-api) it shows we have to subscribe a service which called :"Smart Home Devices Management".

But in IoT Tuya Platform, there is not any service called "Smart Home Devices Management" in "Cloud -> All Services"

There is only one called "Device Connection Service", 

**I think it is should be update for this page.**


Secondly
For now, it should be renewed every month cause the Validity Period of "Trial Edition" only provides 1 month.

**Comment by sir90ha** [comment]
did not create a new thread of the question, but in truth the Tuya integration does not work correctly.  Here's an example: the list indicates support for the air conditioner, but when authorizing in the integration, the air conditioner is not observed.  as well as smart ir tuya.  I saw only 5 out of 10 available devices.
https://vfl.ru/fotos/99b9a84236420015.html

**Comment by lecocqe** [comment]
Hello, 

on my side i got all the tuya devices in HA, i can add them in lovelace... but when switching on a switch of light, nothing happens...

best regards

**Comment by drsmarsden** [comment]
I was told to delete device from smart life and re-add
This worked for a test contact sensor which had the same problem , looking for a solution which does not involve doing this for all devices

**Comment by lecocqe** [comment]
hello,

i gave a try but after troubleshooting a little, my problem is as follows:

if switch on a switch in ha, i see it changing in the smart app. but in ha, button state goes back to off but it is on. at that moemnt, i can't do anything more in ha until i reload integration  :(

**Comment by drsmarsden** [comment]
I have switched now to the Dev version of the core Tuya integration (Nov release) - appears much better and more stable, just missing a couple of critical sensors for me, which I might try to add if all else fails
