### ISSUE TITLE
Switchbot Integration looses connection and when connected it does not respond to commands

### ISSUE THREAD

**Issue by RolandGoud** [home-assistant/home-assistant.github.io#19670]
### Feedback

The integration looses commection a lot......leading in to all devices and entities being unavailable.

Also neither curtains or switches respond to command when the connection is working. 

Also meters are not in the list of devices to add 

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2021.10.1

**Comment by RolandGoud** [comment]
looks like the devices are online for 65 seconds after which they loose connection then it is offline for 65 seconds and this repeats it self.

So when ver you trigger the device in the minute it is not available nothing would happen....this provides a unstable integration and it not workable situation.

should this be solved with the scan interval settings?

**Comment by RolandGoud** [comment]
@frenck this integration is awful....it does not find all devices and refuses to give the command to the curtain. 

 On top of that the developer provides no support....not even a small remark on. any of the issues. This integration is HA unworthy

**Comment by frenck** [comment]
So uh, why ping me for that? Additionally, you are providing documentation feedback right now... you might want to raise an Core issue for issues you have instead?
