### ISSUE TITLE
How do I scan QR code with Smart Life?

### ISSUE THREAD

**Issue by ultimateguy** [home-assistant/home-assistant.github.io#19684]
### Feedback

I can't for life of me figure out: where do I go in the Smart Life app to enable it to scan the QR code?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.1

**Comment by NFis** [comment]
Touch on the 'profile' button at the bottom of the start screen, and then on the next screen at the top on the rigth side you'll find the scan symbol:  four edges and a horizontal line inside. 
Touching this starts the camera and the scanning process. Perhaps you must add camara access rights to the app.

**Comment by ultimateguy** [comment]
Thanks, found it!

**Comment by drthanwho** [comment]
This can be closed 😃
