### ISSUE TITLE
Where to find ID and Secret for Airthings Wave

### ISSUE THREAD

**Issue by twh-tech** [home-assistant/home-assistant.github.io#19689]
### Feedback

Thanks for the AirThings integration.
During setup it requests ID and Secret.
Where do I find those?
It would be nice to see the documentation be specific about how to find those.
It only says Login in here to find your credentials, which is a link that leads to the Airthings login.

I have logged into my Airthings account on the web, but find no information about ID and Secret.
In my Airthings account I find the serial number for my Wave device and I try to use that as ID and my Airthings account password as Secret, but that is not working.

### URL

https://www.home-assistant.io/integrations/airthings/

### Version

2021.10.0

**Comment by Danielhiversen** [comment]
Tried this https://dashboard.airthings.com/integrations/api-integration ?
