### ISSUE TITLE
Tradfri Integration is not working

### ISSUE THREAD

**Issue by neilschuerch** [home-assistant/home-assistant.github.io#19685]
### Feedback

The Integration works in the first minute after reboot or reload of the Integration.
I have wasted now +10 H on trying to set this up. I tried raspberry pi 4 iso, normal raspberry install and mostly docker. Nothing is working.
I really like the idea which homeassistant stands for, but this is just unacceptable.

Can i expect an update to come out, or should i give up?
I found people asking for this fix in the beginning of 2020.

Kind regards, Neil

### URL

https://www.home-assistant.io/integrations/tradfri/

### Version

2021.10.2

### Additional information

If you really want to debug this, you can ask me for logs and further information

**Comment by thecode** [comment]
This repository is used for documentation issues, please open an issue here: [Home Assistant Core - new issue](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml)
When opening the new issue, try to fill in as much as details as possible.

**Comment by janiversen** [comment]
Apart from that, please remember homeassistant is driven by volunteers. The bug might be unacceptable to you, but then do something about it and help out. Just complaining will get you nowhere.

Stay assured we are not going to “you can ask me for logs and further information” if you just want to complain please do not bother opening an issue in core.

**Comment by neilschuerch** [comment]
Hey guys :)
I want to say sorry. It was 3 AM in the morning and a just lost it.
I tried a lot of things, but nothing worked.

Thanks for doing a great job in developing homeassistant. Unfortunately it doesn't work for me.

Cheers, Neil
