### ISSUE TITLE
ONVIF refresh rate

### ISSUE THREAD

**Issue by GGBMLC** [home-assistant/home-assistant.github.io#19690]
### Feedback

ONVIF refresh rate.
I go my webcam to work with Home Assistant. 
Picture is ok.  But the UI only update the picture ever 10 sec. 

There is no option to change the refresh rate in the UI?

HW. RPI4-64bit
SW Home Assistant 2021.9.7
Docker 20.10.7

### URL

https://www.home-assistant.io/integrations/onvif/

### Version

2021.10.2

**Comment by frenck** [comment]
That is not the "ONVIF refresh rate" what you are looking for. By default the UI shows a snapshot every 10 seconds, this is default Home Assistant behavior.

You can change the behavior of the UI card showing the picture by enabling live view on the card displaying your camera, see:

<https://www.home-assistant.io/lovelace/picture-entity/#camera_view>
