### ISSUE TITLE
Please provide data for determining alarm types

### ISSUE THREAD

**Issue by Farleykri** [home-assistant/home-assistant.github.io#19695]
### Feedback

First of all, awesome integration, works flawlessly. i was wondering however if you may be able to add additional support for different alarm types for example:

Burgular Alarm 
CO Alarm
Fire Alarm
Gas Alarm ETC.

it would be great to be able to customize different automation/scripts with different alarm types based on the state of the system rather than just the existing "triggered" sensor

### URL

https://www.home-assistant.io/integrations/elkm1/

### Version

2021.10.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
