### ISSUE TITLE
broken some features

### ISSUE THREAD

**Issue by rchiileea** [home-assistant/home-assistant.github.io#19694]
### Feedback

was running netgear enhanced in config and its now broke

### URL

https://www.home-assistant.io/integrations/netgear/

### Version

2021.10.2

### Additional information

which gave me speed test and guest wifi switches, after added intergration from this, these have stopped working, tried rebooting as well as removing from config and rebooting and re adding them and rebooting I did have a switch for.

**Comment by rchiileea** [comment]
I thought I would show you what was in my config
under sensors I had

  - platform: netgear_enhanced
    host: !secret netgear_ip
    username: !secret netgear_username
    password: !secret netgear_password
    resources:
      - check_app_fw
      - traffic_meter
      - traffic_meter_on
      - traffic_meter_options
      - get_lan_config_info
      - dns_masq
      - info
      - supported_features
      - speed_test_result
      - bw_control
      - 2g_guest_wifi_on
      - 5g_guest_wifi_on
      - 2g_wifi_info
      - 5g_wifi_info
      - 2g_guest_wifi_info
      - 5g_guest_wifi_info
      - get_smart_conn

then under switches I had these, now after official intergration they dont work.
switch:
  - platform: netgear_enhanced
    host: !secret netgear_ip
    username: !secret netgear_username
    password: !secret netgear_password
    resources:
      - 'access_control'
      - 'traffic_meter'
      - '2g_guest_wifi'
      - '5g_guest_wifi'
      - 'run_speed_test'
      - 'reboot'

**Comment by frenck** [comment]
Hi there @rchiileea 👋 

It seems like you want to report an issue with an integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks!

../Frenck
