### ISSUE TITLE
Could you please add the RM4C Pro in the broadlink support list?

### ISSUE THREAD

**Issue by kim2140** [home-assistant/home-assistant.github.io#19697]
### Feedback

Currently, RM4C Pro has not been supported in home assistant, so I am manually updating the RM4C Pro code in the list.
Code is "0x6184"

Thanks,

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2021.10.2

**Comment by atxbyea** [comment]
Could you elaborate on "manually updating the RM4C Pro code in the list" @kim2140

**Comment by kim2140** [comment]
@atxbyea  Currently, I manually uploaded the code in the broadlink while updating supervisor
Please see this youtube clip. 
https://www.youtube.com/watch?v=mnUF-dpVvGo&t=673
I just followed this instruction. Thanks,

**Comment by felipediel** [comment]
Hi. This device is already in the dev branch, coming soon.

**Comment by frenck** [comment]
This is a feature request, not documentation feedback. Therefore closing it on this end.
