### ISSUE TITLE
How do I check that the stream is playable

### ISSUE THREAD

**Issue by GGBMLC** [home-assistant/home-assistant.github.io#19692]
### Feedback

I the guide there is stated:
First, check that your stream is playable by ffmpeg outside of Home Assistant with (use option -an or -vn to disable video or audio stream):

But how?
in the MS win 10 command promt? or ?
it is not cleary how to check the streaming is working. 

### URL

https://www.home-assistant.io/integrations/ffmpeg/

### Version

2021.10.2

**Comment by frenck** [comment]
Please consult the ffmpeg documentation on how to install and use their software. That is considered to be out of scope for Home Assistant.
