### ISSUE TITLE
Supported device

### ISSUE THREAD

**Issue by dmr1987** [home-assistant/home-assistant.github.io#19696]
### Feedback

Please add YLDD05YL Color Stripe to supported devices list. I bought this one, and tested with integration all works fine.

### URL

https://www.home-assistant.io/integrations/yeelight/

### Version

2021.10.2

**Comment by atxbyea** [comment]
@dmr1987 which `model ID` did you use to make it work ? `color1` or `color2` ?

**Comment by dmr1987** [comment]
> 
> 
> @dmr1987 which `model ID` did you use to make it work ? `color1` or `color2` ?

I'm just added integration from UI and wrote correct IP. Strip has been identified as "yeelight_strip6".

**Comment by atxbyea** [comment]
https://github.com/home-assistant/home-assistant.io/pull/19837
