### ISSUE TITLE
Only one Value

### ISSUE THREAD

**Issue by bttfw** [home-assistant/home-assistant.github.io#19706]
### Feedback

Its pretty nice but you can track only one value per eth adress or atleast display only one 

ETH Balance
0,000587313688642348 ETH

Shiba Inu Balance
False SHIB

but if you click on that balance you can see it in the graphs 

### URL

https://www.home-assistant.io/integrations/etherscan/

### Version

2021.10.2

**Comment by frenck** [comment]
Hi there @bttfw 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
