### ISSUE TITLE
Explain "Supervisor" for "Compare Installation Methods"

### ISSUE THREAD

**Issue by joel0** [home-assistant/home-assistant.github.io#19703]
### Feedback

The "Compare Installation Methods" table has a row for "Supervisor," but no explanation of what it is or what benefits it provides.  As a novice trying to install this for the first time, I ended up looking at the comparison table with very little knowledge of the whole system.  I'd guess there's an overview document somewhere that gives a good introduction of Supervisor that could be hyperlinked from the table.

### URL

https://www.home-assistant.io/installation/

### Version

2021.10.2

**Comment by ikifar2012** [comment]
The only explanation we have of the supervisor on the website is [in the glossary](https://www.home-assistant.io/docs/glossary/)

Do you think we should link to that?

**Comment by joel0** [comment]
I think linking to the glossary would be great.  I think the Supervisor description there would be very beneficial to people who are just getting started and looking at the comparison chart.

**Comment by ikifar2012** [comment]
> I think linking to the glossary would be great.  I think the Supervisor description there would be very beneficial to people who are just getting started and looking at the comparison chart.

Alright, I will create a PR later today
