### ISSUE TITLE
Smartplugs are losing the power monitor 

### ISSUE THREAD

**Issue by robi59italy** [home-assistant/home-assistant.github.io#19716]
### Feedback

all my plugs lost the power monitor capacity.
On device, I can only switch on-off.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.3

**Comment by frenck** [comment]
Hi there @robi59italy 👋 

It sounds like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please, report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by robi59italy** [comment]
> Hi there @robi59italy 👋
> 
> It sounds like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please, report issues with integrations here:
> 
> https://github.com/home-assistant/core/issues
> 
> Thanks! 👍
> 
> ../Frenck

Dear Frenck
I went to tuya integration page and I pushed the button "provide feedback" and it sent me here.
anyway this version (2021.10.X) is a disaster for Tuya and I'll be obliged to invest 50 euro to buy Atom plugs with Tasmota

**Comment by danielccm** [comment]
I'm having the same issue with my plugs... they are not reporting the consumption values correctly... as they sit at 0.1 all day and night, whether there is something plugged or not.
