### ISSUE TITLE
And what about Alexa devices?

### ISSUE THREAD

**Issue by derekcfoley** [home-assistant/home-assistant.github.io#19713]
### Feedback

Having massive issues getting my HA nodered flows to access TTS, can you show us how to set it up please from HA itself, so I can use the "service" from within NodeRed?

### URL

https://www.home-assistant.io/integrations/tts/

### Version

2021.10.3

**Comment by frenck** [comment]
TTS is a platform, which provides the base for other Text-to-Speech integrations to use.

To set up Text-To-Speech, please check the integration documentation for one of the integration providing TTS:

<https://www.home-assistant.io/integrations/#text-to-speech>

**Comment by derekcfoley** [comment]
There is no documentation for Alexa... only google home, which is why I
filled out this!


*Regards*Derek Foley

Email: ***@***.***
Mobile: 07958 758 712

**Comment by frenck** [comment]
Alexa isn't exposed as media player, this not available as TTS target.
