### ISSUE TITLE
Device not found, tp-link_smartplug_5FAF (105 plug)

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19717]
### Feedback

Followed the advice ('auto detect' and manual - still 'no device found' resulted.)
to no avail. 

How to add this device to HA please?

Control via 'KASA' app works fine. 

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.10.3

**Comment by frenck** [comment]
Hi there @dpawson 👋 

It seems like you are in need for support, or are trying to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead.

In case you want to report an issue with an integration, please report it here:

<https://github.com/home-assistant/core/issues>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
