### ISSUE TITLE
Additional Information for using Chromecast with Internal URL

### ISSUE THREAD

**Issue by linickx** [home-assistant/home-assistant.github.io#19718]
### Feedback

Additional consideration is required for users with different External URLs and Internal URLs.  (_Where the Internal URL is a name, not an IP address)_

Users can experience issues & confusion when trying to cast media, this error message:

`Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address`

Chromecast appliances by default are hard-coded to ignore DNS server(s) provided by DHCP and use Google's Public DNS Resolvers. By default internal DNS records are not visible to Chomecast devices.
Users with internal LAN DNS Servers for local zones/names will need to block their chromecast device from sending UDP/53 traffic to 8.8.8.8, 8.8.4.4 on their firewall/router. This will force the chromecast device to fall back to the DNS server provided by DHCP and therefore the internal url of HA can be resolved.

Chromecast appliances only support media casting via HTTPS, this means that the internal url also needs a valid/trusted certificate (_not self signed_) such as one from Let's Encrypt.

### URL

https://www.home-assistant.io/integrations/cast/

### Version

2021.10.2

**Comment by emontnemery** [comment]
Note that the warning message states that the URL must be "either a **publicly resolvable hostname** or an IP address"
It's perfectly fine that the **publicly resolvable** hostname resolves to a **private IP address**, e.g. 192.168.x.x, but it's not fine that the hostname can only be resolved via a private DNS server.

I don't think we should document blocking cast devices from accessing Google's DNS servers.

> Chromecast appliances only support media casting via HTTPS, this means that the internal url also needs a valid/trusted certificate (not self signed) such as one from Let's Encrypt.

I don't think this is correct, which cast devices have the limitation of only supporting non self signed https?
