### ISSUE TITLE
New Tuya integration not populating devices

### ISSUE THREAD

**Issue by Cr4z33** [home-assistant/home-assistant.github.io#19712]
### Feedback

Although I followed step-by-step the instructions, after 3 days the new integration didn't populate yet.

All I have associated with Tuya are bulbs and nothing else.
![Screenshot 2021-10-11 at 11-59-12 Tuya IoT Platform](https://user-images.githubusercontent.com/19343851/136776316-6b5595fe-1bec-402f-9afe-1b05e92f3efa.png)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.3

**Comment by jhstrateng** [comment]
I have a potentially similar issue. However, I have 10 devices, where 8 appear in HA, but 2 do not. The two that do not are wall dimmer switches. Looking at the http traffic on the iot Tuya website, it looks like they are categorized as a "Light Modulator".

![image](https://user-images.githubusercontent.com/6186692/136875555-991a839f-742d-4a53-ae9c-51552bcb0c97.png)

**Comment by stefanroelofs** [comment]
I think you have opened an issue in the wrong place. Here you can open issues for the documentation / website. 
Someone with sufficient rights can transfer the issue to the correct repo:
https://github.com/home-assistant/core/issues

**Comment by frenck** [comment]
Hi there @jhstrateng @Cr4z33 👋 

Seems you both want to report an issue with an integration, however, you have submitted documentation feedback instead. Reporting issues (as mentioned above by @stefanroelofs), can be done here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
