### ISSUE TITLE
WHY?!!

### ISSUE THREAD

**Issue by Vector-Int13** [home-assistant/home-assistant.github.io#19729]
### Feedback

Why did someone stop developing a classic web plugin that worked absolutely great?
Who wanted to work in LAN mode with API. Who did not use the WEB plugin.
Now it's complicated, it is necessary to renew the subscription every year, we never know when they will want money for it.
And to top it all, after completing all the steps, only the Tuya devices are displayed and not the Smart Life ... so I can push it all into the  A...

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.4

**Comment by frenck** [comment]
Closing this, as this is not documentation feedback.

There are several topics on our community forum you could look at, one of them has some responses from the founder of Home Assistant you can find here:

https://community.home-assistant.io/t/revert-back-to-the-old-way-of-handling-tuya-please/345837/28

../Frenck

**Comment by Vector-Int13** [comment]
> Closing this, as this is not documentation feedback.
> 
> There are several topics on our community forum you could look at, one of them has some responses from the founder of Home Assistant you can find here:
> 
> https://community.home-assistant.io/t/revert-back-to-the-old-way-of-handling-tuya-please/345837/28
> 
> ../Frenck

Sorry, that sounds like alibi nonsense to me.

You just don't have anything in the documentation or anywhere that describes what to do with the Smart_Life device. 
It doesn't work now because only Tuya devices are linked in the developer account co API.
It's convenient enough to bail on everything letting people read a bunch of nothing-resolving comments on the forum.

**Comment by frenck** [comment]
> Sorry, that sounds like alibi nonsense to me.

Sorry to hear you feel that way. Feel free to jump into the development of Home Assistant to improve things. That will help everybody.

If you read the actual forum thread and the responses from balloob, you will know that that is not a choice. The old API will go away, and this is what they have/offer. 🤷  Its either this or nothing at all, that is not a choice.

That said, this is not the right place to discuss this and therefore asking kindly to keep the issue tracker clean. Please use the community resources to discuss things like this. Thanks 👍 

../Frenck
