### ISSUE TITLE
Documentation about template creation

### ISSUE THREAD

**Issue by herwig-** [home-assistant/home-assistant.github.io#19725]
### Feedback

you write how to check if a template works - what is missing is the information on how to add a template to the yml file
which yml file to put it to and how to edit the yml file ...

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2021.10.3

**Comment by koskila** [comment]
This is a fair point, but I'm not sure if that file is the right place to add that information - templates can be used for multiple different use cases, and depending on what you're trying to do (and to an extent, how you've decided to order your files), the template would go to a different file.

For example, [Template-integration's docs](https://www.home-assistant.io/integrations/template/) go into more detail and come with plenty of copy-pasteable template samples, too. Then there are [Automations](https://www.home-assistant.io/docs/automation/trigger). And plenty more... 🤔
