### ISSUE TITLE
TP-LINK KP 105 plug

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#19735]
### Feedback

Not seen by HA until after 'connected' via the KASA app on a smartphone. 

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.10.3

**Comment by frenck** [comment]
Hi there @dpawson 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. If you want to report an issue with an integration, please do so here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by dpawson** [comment]
No. IMHO the documentation should warn users that the app is needed prior to use in HA. Hence a document change suggested.

**Comment by frenck** [comment]
Ah! Ok, I misunderstood that. Sorry about that 👍

**Comment by atxbyea** [comment]
https://github.com/home-assistant/home-assistant.io/pull/19836

Like this perhaps @dpawson ?
