### ISSUE TITLE
suggestions for google calendar event installation instructions

### ISSUE THREAD

**Issue by gerombo** [home-assistant/home-assistant.github.io#19745]
### Feedback

it would be good to add the following to the troubleshooting steps for the google calendar event integration:

-If after entering the authentication code, you see the following error in the webpage:

> Authorization Error
> Error 403: access_denied
> The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer (<google account>)

The google account you used needs to be added to the 'Test users' as described in Prerequisites.

### URL

https://www.home-assistant.io/integrations/calendar.google/

### Version

2021.10.4

**Comment by jeeljain19** [comment]
I would like you to assign me this issue and i like it very much . @gerombo
