### ISSUE TITLE
Service name change

### ISSUE THREAD

**Issue by jwmcintosh** [home-assistant/home-assistant.github.io#19742]
### Feedback

"Smart Home Data Service" does not exist as I search the site.  As I follow this guide, the only one I manually had to locate and subscribe/authorize to was "Device status notification" -- now aside from three of my lights reporting random colors even though they are white, things appear to work properly.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.4

**Comment by Dewieinns** [comment]
I too experienced this. I was able to follow other steps and get the devices to show up within the Tuya IoT Platform, was able to link Homeassistant to the account, but I'm not seeing any devices being detected by Homeassistant and I'm wondering if this mystery missing API Service is the reason why.

**Comment by maprolim** [comment]
Same problem here. I apreciate if we have the answers on this: this issue like make the tutorial useless. 

@zlinoliver, Can you take a look please?

**Comment by frenck** [comment]
@maprolim Please don't ping people to get things fixed. They have been already notified above. Patience is key. Thanks for understanding 👍
