### ISSUE TITLE
How to implement limits min max

### ISSUE THREAD

**Issue by haze1986** [home-assistant/home-assistant.github.io#19743]
### Feedback

I have been trying this step but did not get it to work. Is it still functional?

### URL

https://www.home-assistant.io/lovelace/sensor/

### Version

2021.10.4

**Comment by frenck** [comment]
Hi there @haze1986 👋 

This part of the documentation seems to be up to date. If something is not working or in case you are experiencing a bug, please file an issue for this specific case at our frontend issue tracker here:

<https://github.com/home-assistant/frontend/issues>

Thanks! 👍 

../Frenck
