### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by NABarnes** [home-assistant/home-assistant.github.io#19751]
### Feedback

Page says "if OS-Agent isn't running, start it", but doesn't even begin to explain how this is achieved.

### URL

https://www.home-assistant.io/more-info/unsupported/os_agent/

### Version

2021.10.4

**Comment by frenck** [comment]
> Page says "if OS-Agent isn't running, start it", but doesn't even begin to explain how this is achieved.

The OS-Agent is part of the Home Assistant Supervised installation type. For this installation type, we warn someone should have in-depth knowledge on administrating Linux systems. If this question is raised, I would strongly recommend looking into a different or more fitting installation type for you.

Nevertheless, thank you for providing feedback 👍 

../Frenck
