### ISSUE TITLE
Card "energy-distribution" does not reflect today

### ISSUE THREAD

**Issue by IntExCZ** [home-assistant/home-assistant.github.io#19758]
### Feedback

The independently used card does not reflect actual day (after midnight).
To change day of this card the card "energy-date-selection" must be additionaly used.

### URL

https://www.home-assistant.io/lovelace/energy/

### Version

2021.10.4

**Comment by frenck** [comment]
It should do that; please report issues/bug at:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
