### ISSUE TITLE
KVM Installation Steps lead to UEFI Shell: Disk not found

### ISSUE THREAD

**Issue by NoahKamara** [home-assistant/home-assistant.github.io#19769]
### Feedback

I've followed [this guide](https://www.home-assistant.io/installation/linux/#create-the-virtual-machine) but when I try to launch, I get the following error:
```
BdsDxe: failed to load Boot0001 "UEFI QEMU HARDDISK QM00001 " from PciRoot (0x0) /
rimary,Master,0x0) : Not Found
```

And then the VM is in UEFI Shell with the following output:
```
UEFI 02.70 (EDK II, Ox00010000)
  Mapping table
       BLKO: Alias (s):
             PciRoot (0x0) /Pci (0x1.0x1) /Ata (0x0)
```

### URL

https://www.home-assistant.io/installation/linux/#create-the-virtual-machine

### Version

2021.10.4

**Comment by atxbyea** [comment]
Is this on proxmox by chance ? If not, what is the base OS, what is the version of KVM and did you specify the UEFI fimware to use ?
