### ISSUE TITLE
Add Bayesian estimated probability in attribute

### ISSUE THREAD

**Issue by landaisbenj** [home-assistant/home-assistant.github.io#19768]
### Feedback

I would to use bayesian integration for "in bed" sensor like exemple (and more in futur). 
But, i think it's really complex to understand how it's work...

Maybe you can add the result of estimated probability in attribute ?

I think it could help to understand, test and try for another idea...

Another point, i never see in all binary_sensor configuration, state or entity_id write with surrounded garment:

![image](https://user-images.githubusercontent.com/32144431/137320926-c802b13c-9f45-4f62-a126-1ed3c1c6e03b.png)

### URL

https://www.home-assistant.io/integrations/bayesian/

### Version

2021.10.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
