### ISSUE TITLE
Time Too Long

### ISSUE THREAD

**Issue by RenzheLee** [home-assistant/home-assistant.github.io#19763]
### Feedback

About 24 hours later,it still:Preparing Home Assistant.  Time Too long
(RespberryPi 4B,last version of OS)

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.10.4

**Comment by frenck** [comment]
That is not normal, it should be around 20 minutes (depending a bit on your internet speed as well).

I would try to consult/ask for support on our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e) (chat is probably best/fastest for this).

You are more likely to get the answers and type of help you are looking for in those places.

Thanks! 👍
