### ISSUE TITLE
Cannot add PIR / Motion sensor

### ISSUE THREAD

**Issue by qazqazie** [home-assistant/home-assistant.github.io#19772]
### Feedback

Hello,

I have 4 tuya wifi plugs and 2 motion sensors. I managed to all devices synced from my smart life app to the tuya IOT platform without any issues. However, only the 4 wifi plugs appear in HA. I have tried deleting and adding again to no avail. The integration device category here: https://github.com/tuya/tuya-home-assistant/wiki/Supported-Device-Categor says the PIR sensor is supported. I added all the suggested API's in the tuya setup instructions. 

Any ideas to get these PIR sensors to work ? 

Thanks for your help and thanks for all the good work on HA and this and other integrations. 

Regards,
Brian

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.4

**Comment by frenck** [comment]
See: <https://www.home-assistant.io/integrations/tuya/>

Sensors are not supported. The external documentation you linked is not managed or reflects anything about Home Assistant. Please consult our official resource instead.
