### ISSUE TITLE
The integration entities was unavalable will not rescan entity 

### ISSUE THREAD

**Issue by skynet-network** [home-assistant/home-assistant.github.io#19780]
### Feedback

Please add rescan of entries don't stop if entity is found so we can can remove entitys to troubleshoot are devices. 

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.10.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
