### ISSUE TITLE
Real-time ambilight

### ISSUE THREAD

**Issue by Kemmal81** [home-assistant/home-assistant.github.io#19782]
### Feedback

Is it possible to know the real-time status of only one of the ambilight LEDs? This should not overload the event bus.
I think it would be useful for creating synchronized scenes with other colored lights.

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2021.10.4

**Comment by elupus** [comment]
You have to poll the LEDs over http. It's a rather heavy operation inside the TV as well. So doing realtime readout of ambilight status is not too nice. 

Untill we have some resolved situation for the crashprone behaviour of the TV, I'm hesitant to add more load.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
