### ISSUE TITLE
Dimmer switch issues

### ISSUE THREAD

**Issue by danielccm** [home-assistant/home-assistant.github.io#19785]
### Feedback

I have added a dimmer switch to control a wifi bulb.

I can only control the on/off of the device, not the brightness level... 

The device is listed in the Tuya IoT website as

Product Name
欧标旋钮调光器（零火Wi-Fi）

Ideas?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.4

### Additional information

Home Assistant 2021.10.4
core-2021.10.4

**Comment by frenck** [comment]
Hi there @danielccm 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have now submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

../Frenck

**Comment by danielccm** [comment]
@frenck could this be an issue like the other issue I added with the power metering, that the option to dim the light isn't encoded in the device drivers or something?

**Comment by frenck** [comment]
@danielccm  This is the documentation repository and this is submitted as documentation feedback. This is not the right place.

That said, I'm currently fully rewriting Light support adding support for the full spectrum, expect it to be finished today.

**Comment by danielccm** [comment]
If you need some testing, give me a shout.
