### ISSUE TITLE
Power plug with metering option stays at 0.1 in current consumption

### ISSUE THREAD

**Issue by danielccm** [home-assistant/home-assistant.github.io#19783]
### Feedback

I had the V1 integration working.

I updated to V2 because I wanted to get a dimmer switch working, which I will open another issue with.

Now I can only control on/off of the power plug, but I can't use the current consumption as it stays always at 0.1, with or without current flowing.

In the Smart Life app I can see the consumption alright.

I have updated everything in the supervisor and still nothing.

What can I try?

Thanks!

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.4

### Additional information

Home Assistant 2021.10.4
core-2021.10.4

**Comment by frenck** [comment]
You can help us with this issue by providing some information about your device.

To do that, please follow the next steps:

- Login into https://iot.tuya.com/cloud/
- Go to the "Cloud" tab in the left menu bar
- Click on the Project Name/Description that you are using for your Home Assistant instance.
- Once on that page, click on the "Devices" tab.
- Find this device in that list and click on the "Debug Device" link. A new window will open with information about the device.

From this debugger, we can get some information that can be useful. From the "Basic Information" tab, please provide:

- **Product Name***
- **Product Category**

Next, click on the "Device Debugging" tag. Once on that tab, you will find a small link called "JSON Editing", click on that link. It will now show a text field called `JSON_EDITOR` with some code in it. It looks something like this:

![image](https://user-images.githubusercontent.com/195327/136928992-1b94189f-27eb-4274-b78c-e6456a9f0c36.png)

Copy and share that code from that text field into this issue.

That will help a lot! Thanks already!

../Frenck

**Comment by danielccm** [comment]
Product Name
Smart Socket-16A
Product Category
cz

[
  {
    "code": "switch_1",
    "value": true
  },
  {
    "code": "countdown_1",
    "value": 0
  }
]

**Comment by danielccm** [comment]
I saw some improvements today with the new beta! But the power consumption isn't there yet... I know it's a work in progress... Thanks!!
