### ISSUE TITLE
Problem connecting to the AWAIR API

### ISSUE THREAD

**Issue by starcraft04** [home-assistant/home-assistant.github.io#19784]
### Feedback

I have received a token and when trying to install this, I get an error aborted.

When looking in the logs, I can see:
[homeassistant.components.awair] Unexpected API error: Error querying the Awair API.

Thanks if you can help...

### URL

https://www.home-assistant.io/integrations/awair/

### Version

2021.10.4

**Comment by ahayworth** [comment]
Hi @starcraft04 -

Thanks for bringing this to our attention. I just logged in to my instance and also see something similar. In my instance it looks like Home Assistant started experiencing a problem with the Awair API about 4 hours ago (3:17am US Central time).

I won't have time to look into this until later tonight, but I will reach out to Awair and ask if anything has changed. It's possible they've changed their API again, or that there's some kind of problem on their end.

**Comment by ahayworth** [comment]
Hi @starcraft04 - I spoke with Awair, and they have been experiencing some instability in their APIs. I was able to confirm that at least one of my two devices is reporting data correctly again - can you try as well?

I think otherwise we'll have to wait for them to shore things up on their end.

**Comment by starcraft04** [comment]
Hi,

It seems to be working fine again now.

Thanks for your quick reaction...
