### ISSUE TITLE
research into home assistant roadmapping and release planning 

### ISSUE THREAD

**Issue by MeesMouwen** [home-assistant/home-assistant.github.io#19791]
### Feedback

Dear people from Home-assistant,

I hope this message finds you well. We are two master students at the University of Utrecht, majoring in business informatics. Currently we are working on a horizontal research into the documentation and development of open source products and their release planning. Our research goal is to investigate the current state of release planning and roadmapping in open source products. In reviewing our literature we have found that roadmapping does provide major benefits within software production, but examples of roadmapping in practice have not been documented much within the open source community.
As we work in a horizontal research setup, we collectively decided upon selecting Home-assistant  to perform a case study and interview on. We found some information via your forum and website about your clear documentation and your architecture. Additionally, upcoming releases were shown. However, what the planning behind these releases are and how this is organised was not available. 
We were hoping to investigate your product further and ask a few questions online about the use of roadmapping within your product. These are 6 short questions which can be found at the bottom of this message. If you would like to take part in our research further, we would be more than delighted to have a short 15 minute interview with someone experienced within the development of Home-assistant, about the use of roadmapping for your release planning. We would also be happy to share the results of our research if this is of interest to you. 

Many thanks in advance for taking your time in answering this message! 

Kind regards,

Mees Mouwen
Douwe Wierda 

The questions:
Do you keep a well documented roadmap for your product? 
Answer:
If not, how do you document and plan for next releases?
Answer:
How often is this updated/ changed? 
Answer:
Who  is involved within the creation of the roadmap/planning next steps in the development? 
Answer:

Who is the roadmap / release planning shared with? 
Answer:

Do you have an example of a previous documented roadmap / release plan we can use in our research?
Answer:
 

### URL

https://developers.home-assistant.io/

### Version

2021.10.4

**Comment by frenck** [comment]
> Do you keep a well documented roadmap for your product?

No, we don't. It's an open-source project that is fed by people making open source contributions in their spare time. We can't guess what they will add and when they have time to do that.

> If not, how do you document and plan for next releases?

We don't. We have a timed-release cycle, with a monthly release cycle. We release what is ready to ship.

> How often is this updated/ changed?

What is "this" referring to? If it is about the release cycle, it is monthly.

> Who is involved within the creation of the roadmap/planning next steps in the development?

There is no roadmap/planning.

> Who is the roadmap / release planning shared with?

Well, there is no roadmap, but as it is an open-source project, it means everything is open for the world to see. You can find and see everything that is coming here on GitHub.

> Do you have an example of a previous documented roadmap / release plan we can use in our research?

There is no roadmap.
