### ISSUE TITLE
The Google Nest integration looks to be broken

### ISSUE THREAD

**Issue by mct370770** [home-assistant/home-assistant.github.io#19790]
### Feedback

Hi, I have carefully walked through the documentation on this integration - but Google will not let me access this way anymore. I get a; 
"Error 400: invalid_request. You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure. You can let the app developer know that this app doesn't comply with one or more Google validation rules."
The app is done excactly as described - and I noticed that you also use Nabu Casa in the URL statement - which I also use - but in the error from Google they further write; "redirect_uri: http://homeassistant.local:8123/auth/external/callback" and that is the local url - not the Nabu Casa url.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.10.4

### Additional information

Everything is of course fully updated 
core-2021.10.4
supervisor-2021.10.0 
Home Assistant OS 6.5

My Home Assistant is running as a virtual machine inside VMware and has many other integrations running.

**Comment by allenporter** [comment]
You need to access home assistant using your public url, you can't use a local url.

I recently updated the "my home assistant" link in the docs but now realize you may be using nabu casa for that. 

Can you repeat the steps but access home assistant from the public hostname?

**Comment by mct370770** [comment]
So - in short terms - the Nabu Case URL does not work - or?
In that case please change the screenshot used in the documentation - otherwise many others will think that is the way to go.

I need an external URL - 
This means fixed external IP address and a dns domain name attached to that IP address is that correctly understod?
To get a home system up and running .......

**Comment by mct370770** [comment]
The local URL was mentioned from Google - I was using the NABU Casa external url - just to make sure you understand

**Comment by allenporter** [comment]
Nabu casa works, you just need to make sure that is the url in the url bar when accessing home assistant.

E.g. How did Google get the url? It's the redirect url in your url bar.

**Comment by mct370770** [comment]
Hi, I now logged on in my browser with the Nabu Casa external url and I succeeded to get one step further.
Now in the log I get a 
"Configuration error: Subscription misconfigured. 
Expected topic name to match 'projects/sdm-[a-z]+/topics/.*'  
but was 'projects/xyzxyzxyz/topics/xyzxyz'"

I changed the actual names to xyz - 
but how is the exact syntax in the configuration.yaml for the "subscriber_id:" line?

**Comment by mct370770** [comment]
And - thanks a lot :-)

**Comment by allenporter** [comment]
The line entered looks like the topic name rather than the subscriber id. Check out the Integration docs which have a section about subscriber I'd and the last step talks about how topic and subscriber look similar.

**Comment by mct370770** [comment]
Thanks for helping out - I really appreciate it :-)

I did first time write the wrong topic information in the configuration.yaml file instead of subscriptions
Then I changed it to the correct subscription name that I located in the Google Cloud Platform page - but it still logs the same error with old error. I have even removed the whole nest section from the configuration file - rebooted - and reinserted - but the error message still sounds as if I had the old wrong subscription name???

**Comment by allenporter** [comment]
Oh oh, sorry. It's the config in the cloud console. Delete and recreaste the subscriber following the instructions and make sure to enter the topic name manually. The topic name configured by the subscriber is incorrect, not the configuration.yaml -- sorry about that.

**Comment by mct370770** [comment]
Thank you very much - got it working :-) 
Hope you have a beautiful day
