### ISSUE TITLE
The InitialView = List seems not to work

### ISSUE THREAD

**Issue by ArdJonker** [home-assistant/home-assistant.github.io#19792]
### Feedback

I've added a NextCloud caldav calendar to the configuration.yaml, this works fine.
I have a calendar card in my dashboard and this shows the calendar items.
I've set the initial view to List and the calendar items are shown as a list.

Unexpected behaviours:
1. The List contains one (or more?) item(s) in the past. I expected only future items. This does happen when i click the Listview button.
2. I expected the Listview button to be selected but the Month button is shown selected.

### URL

https://www.home-assistant.io/lovelace/calendar/

### Version

2021.10.4

**Comment by frenck** [comment]
Hi there @ArdJonker 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍
