### ISSUE TITLE
QR code to add Tuya devices doesn't work

### ISSUE THREAD

**Issue by Nick7767** [home-assistant/home-assistant.github.io#19806]
### Feedback

Hi,  in device tab, when i try to add devices in the tuya app with QR code, the app on the phone says that it's "impossible to add a device already in use on another data center".
I've tried to add different data centers and  all data centers but the issue stays the same.
Thanks for your help

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.5

**Comment by kitkat270** [comment]
Same issue. Previously used tuya integration without issue. Unable to setup new integration in 2021.10.4.
![image](https://user-images.githubusercontent.com/28577458/137597272-713dd51f-c932-4938-a79a-44f8c50960bf.png)

**Comment by xinux87** [comment]
I'm having the same problem, after the update using the given tutorial i can't connect.

**Comment by frenck** [comment]
Duplicate of https://github.com/home-assistant/core/issues/57864

**Comment by datascope11** [comment]
Same
