### ISSUE TITLE
Integration does not work properly

### ISSUE THREAD

**Issue by CasaTepeji** [home-assistant/home-assistant.github.io#19801]
### Feedback

when you turning on any entity, after 1 or 2 seconds the button goes back to off but the light is still on. If you just click on the button again nothing happened. and the button state goes back to off. You have to double-click (quickly) on the button again to turn off the light. Same case with any outlet.

Same situation is the switch is on and you want to switch off

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.5

**Comment by frenck** [comment]
Hi there @CasaTepeji 👋 

It seems like you want to report a bug with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise bugs with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by CasaTepeji** [comment]
thanks Frenck. i will do
