### ISSUE TITLE
Plugwise integration

### ISSUE THREAD

**Issue by fstelte** [home-assistant/home-assistant.github.io#19802]
### Feedback

I use the plugwise integration to read out my P1 port (through the plugwise P1 smile). But I cannot use the measurements from within the energy dashboard

### URL

https://www.home-assistant.io/integrations/plugwise/

### Version

2021.10.5

**Comment by bouwew** [comment]
First, this issue should not be here but in this github: https://github.com/home-assistant/core

Second, same as https://github.com/home-assistant/core/issues/57802

So please close this issue.
