### ISSUE TITLE
example for reboot script

### ISSUE THREAD

**Issue by flypenguin** [home-assistant/home-assistant.github.io#19807]
### Feedback

unfortunately i am completely unable to come up with a working version of a script rebooting the fritz box. the example tells me to use `fritzbox_tools.reboot`, which triggers the error message `Failed to call service script/fritz_box_reboot. Unable to find service fritzbox_tools.reboot`.

also the fritzbox_tools is discontinued in favor of the official integration, so ... 🤷🏼‍♂️ .

_some_ idea how this can be achieved would be nice, the docs do not provide enough information.

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.10.5

**Comment by chemelli74** [comment]
> unfortunately i am completely unable to come up with a working version of a script rebooting the fritz box. the example tells me to use `fritzbox_tools.reboot`, which triggers the error message `Failed to call service script/fritz_box_reboot. Unable to find service fritzbox_tools.reboot`.

Please read again the documentation.
The correct service name is different: `fritz.reboot`

Simone

**Comment by flypenguin** [comment]
which I - of course - also tried. and which also didn't work. I should have mentioned that, sorry. it does seem to work now (I just wanted to re-create the error message), **still it would be nice to update the documentation** with a concrete example or at least correct that old reference.

**Comment by chemelli74** [comment]
> which I - of course - also tried. and which also didn't work. I should have mentioned that, sorry. it does seem to work now (I just wanted to re-create the error message), **still it would be nice to update the documentation** with a concrete example or at least correct that old reference.

Sorry, but I miss the place with the old reference. Can you point it out ?

EDIT: Found out and fixed: https://github.com/home-assistant/home-assistant.io/pull/19844

Simone

**Comment by flypenguin** [comment]
ah you were faster @chemelli74 ;) . thanks!
