### ISSUE TITLE
Additional info

### ISSUE THREAD

**Issue by HFeenstra** [home-assistant/home-assistant.github.io#19816]
### Feedback

In the section Flashing an Odroid-N2+ I would like to suggest some extra information:

Between:
_The ODROID-N2+ will now boot into a terminal. Select Exit to shell from the menu.

Exit to shell

Use the following command at the console to confirm the storage device node:_

I would like to add: 
_**When using the command line, the command line will return: can't access tty; job control turned off. You can ignore this error and follow along the following lines.**
Use the following command at the console to confirm the storage device node:_

And so on...

### URL

https://www.home-assistant.io/common-tasks/os/#flashing-an-odroid-n2

### Version

2021.10.5

**Comment by ikifar2012** [comment]
How does this sound?
When using the command line, the it may return the following error:
`can't access tty; job control turned off.`
You can safely ignore this message and proceed with the installation
Also, is that the exact error?

**Comment by ikifar2012** [comment]
I have made some changes and a draft PR
Please take a look at the deploy preview and let me know what you think
https://deploy-preview-19828--home-assistant-docs.netlify.app/common-tasks/os/#flashing-an-odroid-n2

**Comment by HFeenstra** [comment]
Hello Mathewson,

That looks pretty clear! Exactly in the way Home Assistant gives warnings. 
The first line mentions *the it may…*, I guess that needs to be replaced by *the device may …* ?

Thanks, this helps Noobs like me 😉

Greetings,

Hette Feenstra
The Netherlands

**Comment by ikifar2012** [comment]
Ahh I must have made a typo I was thinking either `the device` or `it may`. I was thinking it because we are talking about the command line on the device not the actual device

**Comment by ikifar2012** [comment]
Check out the preview at:
https://deploy-preview-19828--home-assistant-docs.netlify.app/common-tasks/os/#flashing-an-odroid-n2
Changed to `it may`

**Comment by ikifar2012** [comment]
Let me know what you think @HFeenstra and I will mark it ready for review

**Comment by HFeenstra** [comment]
Matheson, it looks good. Good for a newbie. These kind of errors may confuse new users extremely!

So thank you, let’s go for it 💪

**Comment by ikifar2012** [comment]
> Matheson, it looks good. Good for a newbie. These kind of errors may confuse new users extremely! So thank you, let’s go for it 💪

It has been marked ready for review
