### ISSUE TITLE
Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead

### ISSUE THREAD

**Issue by FrankBurmo** [home-assistant/home-assistant.github.io#19811]
### Feedback

In the system-log during boot , this message is displayed:

_Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of AdGuard Home_

### URL

https://www.home-assistant.io/integrations/adguard/

### Version

2021.10.5

**Comment by frenck** [comment]
This is not an issue of the Home Assistant project, but with the add-on you linked.
