### ISSUE TITLE
More info in configuration wizard

### ISSUE THREAD

**Issue by Jottlas** [home-assistant/home-assistant.github.io#19819]
### Feedback

I am missing information about what this step in the "configuration wizard" actually means:
![image](https://user-images.githubusercontent.com/35530660/137640482-a3ce2fc3-cb62-4fe2-b638-d51ad9110676.png)
Especially "Autostart" is confusing.

And a more minor thing while we are at it..:
I would prefer "Next" instead of "Submit". "Submit" is too technical and makes you think you are done.
![image](https://user-images.githubusercontent.com/35530660/137640476-e2366c5b-3ee2-44b8-a437-4547f80368c8.png)

Thanks!

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2021.10.5

**Comment by frenck** [comment]
It actually needs to be removed 😬 
Its a leftover (hence the docs have been removed in the past already).
