### ISSUE TITLE
SNMP Mode of operration requires authentication password and Privacy Password

### ISSUE THREAD

**Issue by hossamnagy** [home-assistant/home-assistant.github.io#19810]
### Feedback

When enabling the suggested snmp mode of operation : "SNMPv3 read-write access and v1/v2c read-only access" , the printer asked to setup two password entires; Authentication Password and Privacy Password.
The Home assistant integration does not  allow to configure these passwords.  Now I get the below error after updating the SNMP mode of operation 

ERROR (MainThread) [homeassistant.components.brother] Error fetching brother data: No SNMP response received before timeout

I've reverted back to printer default setting "SNMP v1/v2c read-write access" and hassio is able to read the printer status correctly again.. 

### URL

https://www.home-assistant.io/integrations/brother/

### Version

2021.10.5

**Comment by bieniu** [comment]
The documentation says "For **some** Brother devices, SNMPv3 read-write access and v1/v2c read-only access is the option required". So if the default "SNMP v1/v2c read-write access" works, you don't need to change anything.

**Comment by hossamnagy** [comment]
The point here is the option in the documentation for write access requires password configuration . These passwords are not configurable in the integration ..

**Comment by hossamnagy** [comment]
I believe either the documentation or the integration need to be changed for both to to correctly align.
