### ISSUE TITLE
What if you have tuya and smartlife devices in both apps?

### ISSUE THREAD

**Issue by belowthedrone** [home-assistant/home-assistant.github.io#19818]
### Feedback

Not recognizing devices from both apps even if they are configured on the tuya IoT site.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.5

**Comment by frenck** [comment]
You can add the integration twice?

In case that causes problems, please raise a bug report in the core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

**Comment by belowthedrone** [comment]
But I’m receiving invalid authentication error even when placing the correct information and also the following error as well. 



Roberto Fernandez

On Oct 17, 2021, at 11:47 AM, Franck Nijhof ***@***.***> wrote:

﻿
You can add the integration twice?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by frenck** [comment]
> But I’m receiving invalid authentication error even when placing the correct information and also the following error as well.

In that case, please file an issue as I mentioned above. Thanks! 👍
