### ISSUE TITLE
invalid device classes

### ISSUE THREAD

**Issue by dave-parsons** [home-assistant/home-assistant.github.io#19822]
### Feedback

only the following device classes are accepted.

Valid values: "battery", "current", "energy", "humidity", "illuminance", "power", "power_factor", "pressure", "signal_strength", "temperature", "timestamp", "voltage".

### URL

https://www.home-assistant.io/integrations/sensor/

### Version

2021.10.5

**Comment by frenck** [comment]
It sounds like yoi are running an older version of Home Assistant?
