### ISSUE TITLE
Battery level missing from the integration with VOC

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#19834]
### Feedback

Hi,

I can't see the battery level in the integration with my car, in particular the parameters from below that are marked in **bold**:

battery_range
**battery_level**
time_to_fully_charged
**battery_charge_status**

I wonder if these appear only if the car is electric, or I can see the 12V battery status by looking at the **battery_level** and **battery_charge_status**. The model of my car is Volvo V40 and it's a gasoline-driven car.

Thank you,
Andreas

### URL

https://www.home-assistant.io/integrations/volvooncall/

### Version

2021.10.6

### Additional information

If I search for "battery" in the field marked with an arrow in the enclosed picture, I get no result. Do you know if my integration is missing anything and how can I fix it? Or is Volvo's API that no longer includes the **battery_level** parameter?
![battery level](https://user-images.githubusercontent.com/92714873/137693431-912170e2-464d-4eb1-b2df-3671b45c28b8.JPG)

**Comment by atxbyea** [comment]
All of these are hybrid \ EV only values, will never be produced on a pure ICE car.

**Comment by ghost** [comment]
I can see that they might be suitable for an EV/PHEV, and I still wonder if there is any parameter related to the 12V battery that is missing and can be added into the development.

I am sometimes getting warnings on the car’s computer from the dashboard that the audio system will shut down due to lower battery, and I wish I could be able to see the battery’s voltage without using a multimeter or without installing additional hardware. The battery voltage is not displayed neither in the Volvo VOC application.

Any thoughts on this?

**Comment by atxbyea** [comment]
If the main battery is not displayed it in the VOC app either it cannot be polled naturally.

There are generally two reasons for battery voltage problems
1. Battery is dying, I suggest buying a AGM battery from Biltema (I see you are swedish)
2. Alternator is not providing enough charge to keep the battery topped up at all times, this is either an issue with the regulator or the brushes, and can be easily diagnosed with a multimeter

Neither of those issues are related to HA though, but as stated, if the VOC does not list the battery voltage, neither can HA.
