### ISSUE TITLE
Tuya cover switches not working in new Tuya integragion

### ISSUE THREAD

**Issue by bramhendriks** [home-assistant/home-assistant.github.io#19835]
### Feedback

With the new Tuya integration the covers do not seem to be integrated into Home Assistant. I have two Tuya cover devices. I setup the cloud development API platform on the Tuya IoT platform page.

I've added the devices with the APP account (scanning the QR code) and the devices show up under the My Device list.

However when adding the Tuya integration in Home Assistant the devices do not get pulled into home assistant, the integration setup completes but there are no devices listed under it. 

In the previous (direct to app) integration the Covers worked like a charm, this release broke it unfortunatly. 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

**Comment by frenck** [comment]
This is correct, Cover has not been added to the new version.

This is also noted in the release notes of Home Assistant 2021.10 and in the breaking changes section of 2021.10.
