### ISSUE TITLE
Might be useful to include information about how to check configuration in an automation

### ISSUE THREAD

**Issue by gitawayu** [home-assistant/home-assistant.github.io#19833]
### Feedback

Might be useful to include information about how to check configuration as a condition in an automation, for example: for an automation that does a regular reboot - so that the reboot can be avoided (and a different action taken) if the configuration check fails.

### URL

https://www.home-assistant.io/docs/tools/check_config/

### Version

2021.10.6

**Comment by frenck** [comment]
I'm confused by your suggestion for the following reasons:

- A regular reboot should not be needed?
- Home Assistant restarts are already protected again restarting with invalid configuration
- There is no action to run such a check from an automation

**Comment by frenck** [comment]
OMG, I just learned we do have a service for that. Being here for 4 years now, I never knew... can you believe it? It does indicate a bit on how low the use is 😬
