### ISSUE TITLE
How to use the Number and Select Maps in Template integration

### ISSUE THREAD

**Issue by mrsnyds** [home-assistant/home-assistant.github.io#19843]
### Feedback

I have two suggestions related to the documentation of the "Template" integration.  My suggestions relate to the use of the Number map and the Select map that are documented in the Configuration Variables section of the doc'.

The first suggestion is to fix the hyperlink that appears in the "On this page" at the top, right, of the page.   The "Configuration Variables" hyperlink doesn't actually take you to that part of the page.

The second suggestion is to provide examples for how to use the Number and Select entities that you can be created.   The examples might clear up the questions I have when I read the document, but some additional explanation of the purpose of these entities, and how they are different than input_number and input_select entities, might also help.

Thanks for listening/reading.

### URL

https://www.home-assistant.io/integrations/template/#-----configuration-variables--

**Comment by PatrickGlesner** [comment]
+1
Documentation for "Number", and maybe for "Select", is incorrect and incomplete:

- "state" must be a string, not an action.
- Missing "set_value" is an action.
- What is the attribute "mode" discovered in Developer Tools ?
- What is the "optimistic" boolean ?
- ...

Here my trying config:

```
number:
  - name: Fan Speed
    unique_id: fan_speed
    min: 0
    max: 3
    step: 1
    icon: >
      {% set s = states('number.fan_speed')|int(0) %}
      {% if s == 0 %} mdi:fan-off
      {% elif s == 1 %} mdi:fan-speed-1
      {% elif s == 2 %} mdi:fan-speed-2
      {% elif s == 3 %} mdi:fan-speed-3
      {% else %} mdi:fan-remove
      {% endif %}
    set_value:
      service: script.set_ventilation_pulsion_speed_int
      data:
        speed: "{{ value }}"
    state: "{{ states('number.fan_speed')|int(0) }}"
```

Icon and state doesn't change. Slider is ok and calls the script well.

Thanks to upgrade this documentation.
Patrick.

PS: I use HAOS 7.1 and core-2021.12.10

**Comment by PatrickGlesner** [comment]
Hello,

this issue is still relevant.

Thanks.
