### ISSUE TITLE
how to _update_ fritz!box credentials?

### ISSUE THREAD

**Issue by flypenguin** [home-assistant/home-assistant.github.io#19842]
### Feedback

i changed the credentials for the user which was used by fritz tools. i had to delete and re-add the integration. is that the only way? seems cumbersome.

if there is another way it would be nice to have it documented here.

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.10.6

**Comment by chemelli74** [comment]
HI @flypenguin , you should have just waited for the integration to ask for reauth.

Also please take care that this space is for issues, not for support.
For that, please refer to the community: https://community.home-assistant.io/

Simone

**Comment by flypenguin** [comment]
well, there's a "provide feedback" link on the doc page which leads here. and my feedback is that i would have expected that kind of information on the page, so i think it is actually completely valid.

also, there was no asking for re-auth, which might be a support question, so nothing for here.

**Comment by chemelli74** [comment]
> my feedback is that i would have expected that kind of information on the page, so i think it is actually completely valid.

Usually we don't document main HomeAssistant features in each integration to avoid duplications.
 
> also, there was no asking for re-auth, which might be a support question, so nothing for here.

I just changed password and I got the reauth prompt after a while.
Maybe you were just too quick.

Simone

**Comment by flypenguin** [comment]
well the while was a couple of days at least, don't know how long i'm supposed to wait ;)

**Comment by chemelli74** [comment]
> well the while was a couple of days at least, don't know how long i'm supposed to wait ;)

Indeed to much, here I got the prompt after a few minutes.

I would suggest to close this issue and open a new one on https://github.com/home-assistant/core/issues once you have again the no reauth prompt.

Simone

**Comment by flypenguin** [comment]
if i remember i'll change the credentials and try to replicate, then will do! thanks :)
