### ISSUE TITLE
Trying to add Epson EB-585W to Home Assistant- Connection Failed

### ISSUE THREAD

**Issue by aperr69** [home-assistant/home-assistant.github.io#19845]
### Feedback

Set-up Projector Management (5.4) and iProjector (V3) and all working fine. Can turn projector on and off etc.

Attempting to add the integration to Home Assistant and completion of Host and Name in characters always give the error Failed to connect after around (4secs). If using the IP address the error message Failed to connect comes immediately.

### URL

https://www.home-assistant.io/integrations/epson/

### Version

2021.10.6

**Comment by pszafer** [comment]
Show logs. I can't tell you anything from information you provided.

**Comment by frenck** [comment]
Hi there @aperr69 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
