### ISSUE TITLE
Tuya integration of a project

### ISSUE THREAD

**Issue by stamendimitrov** [home-assistant/home-assistant.github.io#19858]
### Feedback

When I add the integration Tuya, the input fields are different. 
I have Username, Password, Country Code and registered app, while lacking the Tuya IoT Access ID and Tuya IoT Access Secret, as it is stated in the documentation. 
Possibly I'm doing something wrong, I'll keep on digging. 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

**Comment by frenck** [comment]
Please follow the steps to create an developer account and project as described here:

<https://www.home-assistant.io/integrations/tuya/#create-a-project>

After you did that, you can get those values as described here:

https://www.home-assistant.io/integrations/tuya/#get-authorization-key

**Comment by stamendimitrov** [comment]
Right, I did that part, but when adding a Tuya integration I don't have some options.
See image.

![image](https://user-images.githubusercontent.com/30045621/137922927-2f56dd03-1e56-421b-82f1-4864e99cf957.png)

**Comment by stamendimitrov** [comment]
An upgrade on the whole system changed the menu to what it should be, apologies. 
Thanks for the support,
Stamen
