### ISSUE TITLE
Foot Warmer Device?

### ISSUE THREAD

**Issue by capritzl** [home-assistant/home-assistant.github.io#19851]
### Feedback

Does this integration provide access to the foot warmer?  I see the Sleep Number number but nothing else.  I want to setup an automation to turn on the foot warmer if the temperature falls below a certain temp.  There is no device for the foot warmer. 

### URL

https://www.home-assistant.io/integrations/sleepiq/

### Version

2021.10.6

**Comment by frenck** [comment]
It does not support that.
