### ISSUE TITLE
Not working properly 

### ISSUE THREAD

**Issue by maceace** [home-assistant/home-assistant.github.io#19868]
### Feedback

Even if the installation procedure is strictly followed, integration is not functional. Doesn't work! 

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2021.10.6

### Additional information

Doesn't work.

**Comment by DavidMStraub** [comment]
Wrong repository, useless description, suggest to close this.

**Comment by frenck** [comment]
Hi @maceace 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted a documentation suggestion instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
