### ISSUE TITLE
No sensor.random_sensor available

### ISSUE THREAD

**Issue by vkuehn** [home-assistant/home-assistant.github.io#19866]
### Feedback

the senso.randodom_sensor mentioned in the URL is not always available

### URL

https://www.home-assistant.io/docs/automation/editor/

### Version

2021.10.6

### Additional information

just manually installed HomeAssitant in a virtual env and tried to follow the first steps to create the first automation.

not sure if/how there can be things installed  missing with such an approach. Not mentioned on the doc page

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/138069942-8262fadb-f4a6-4f55-a037-67523531a91c.png)

You need to set it up, or use any other numeric sensor. It uses a "random" sensor as example.
