### ISSUE TITLE
not unique IDs can never be changed in HA

### ISSUE THREAD

**Issue by ahbrims** [home-assistant/home-assistant.github.io#19862]
### Feedback

This page explains what the message "This entity does not have a unique ID" means.  There is no help in sorting this out, like how to set the unique id.  
It says "CAN BE CHANGED? Unique ID: No. It is a static identifier."  So I take from this that a unique ID can not be set for my entity that has a non unique ID?  
It would be help if this page suggested what can be done. 

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2021.10.6

**Comment by frenck** [comment]
There is nothing to be done. These features are not available. It requires either coding or in some cases, the device or service simply cannot be identified uniquely.
