### ISSUE TITLE
Add more cycle please

### ISSUE THREAD

**Issue by Dutchy-79** [home-assistant/home-assistant.github.io#19872]
### Feedback

Hi,

I would also like to see "past hour" "yesterday" "last month" "last year" etc

regards,

Jasper

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.10.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by dgomes** [comment]
You can use a "cron" pattern and use whatever imaginable cycle you can think of
