### ISSUE TITLE
Service does not work anymore

### ISSUE THREAD

**Issue by Kateriine** [home-assistant/home-assistant.github.io#19871]
### Feedback

The integration can't be found

### URL

https://www.home-assistant.io/integrations/surepetcare/

### Version

2021.10.6

**Comment by frenck** [comment]
> The integration can't be found

I'm not sure what you mean by that message? Could you clarify your documentation suggestion?

**Comment by Kateriine** [comment]
Hello, 

Sorry, it seems the feed back button gave you pretty vague infos indeed ^^

Actually I searched the integration of Sure Pet Care, but I can’t find it anywhere https://www.home-assistant.io/integrations/surepetcare/ <https://www.home-assistant.io/integrations/surepetcare/>

The button « Add integration » leads to a 404, andit doesn’t exist in ha config > integration > Add integration.

I hope it helps.

Kind regards

Catherine

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/138060364-7e50df52-4b24-4487-87ae-43edf9cd539a.png)

Are you running an older version of Home Assistant maybe?

**Comment by Kateriine** [comment]
Oh that’s weird: my version is not that old (core-2021.9.7)

I’m gonna update it and I’ll let you know

Many thanks!

**Comment by frenck** [comment]
> Oh that’s weird: my version is not that old

That should be new enough, any custom integrations related to this one?

**Comment by Kateriine** [comment]
Well it seems that was indeed an issue with the version, many thanks for your efficiency! (and many thanks from my cat, too!)

Kind regards

Catherine

**Comment by Danielhiversen** [comment]
Config flow was added in 2021.10
https://github.com/home-assistant/core/pull/56127
