### ISSUE TITLE
Where is that configuration.yaml file? 

### ISSUE THREAD

**Issue by crystal-way** [home-assistant/home-assistant.github.io#19880]
### Feedback

Hello. I'm very new user. Installed just 1 hour ago my first home assistant server on RPi 4. The problem is that i see a lot of information about configuration file configuration.yaml. But where i can find it? Tried to SSH in to RPi, but looks like there is no SSH service running. I have only web access to the home assistant. So how do i edit this file?

Thank you

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2021.10.6

**Comment by frenck** [comment]
Its written right on the page you left feedback on:

https://www.home-assistant.io/docs/configuration/#editing-configurationyaml

**Comment by crystal-way** [comment]
Thank you :)
