### ISSUE TITLE
Error 1013 is missing

### ISSUE THREAD

**Issue by marcokreeft87** [home-assistant/home-assistant.github.io#19887]
### Feedback

There is a reported bug : https://github.com/tuya/tuya-home-assistant/issues/534
This error code is missing from the docs

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

**Comment by frenck** [comment]
Could you provide full error details on this?
Like logs?

**Comment by marcokreeft87** [comment]
There is no log entry in the log. It says "Aanmeldingsfout (1013): request time is invalid"

**Comment by marcokreeft87** [comment]
Ah I've resolved it. The time on my NAS wasnt correct.

**Comment by frenck** [comment]
Oh, then SSL will become an issue! Nice find and glad you got it resolved.
