### ISSUE TITLE
Possible values?

### ISSUE THREAD

**Issue by kraaidelft** [home-assistant/home-assistant.github.io#19883]
### Feedback

It doesn't tell what values the boolean can hold. The example uses string "on" while the yaml specs allow only true and false, sinds v1.2
So what values will the boolean return?

### URL

https://www.home-assistant.io/integrations/input_boolean/

### Version

2021.10.6

**Comment by frenck** [comment]
Either works.

In the end, the entity state is always a string (thus the right example). However, we handle it gracefully.
