### ISSUE TITLE
Add Integration links to wrong integration (Waze linking to Samsung TV)

### ISSUE THREAD

**Issue by bakerboy908** [home-assistant/home-assistant.github.io#19886]
### Feedback

The Add integration button on the Waze Travel Time is adding the wrong integration to Home assistant.

### URL

https://www.home-assistant.io/integrations/waze_travel_time/

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/138223959-4b9b8a45-7941-41df-b825-9f8da337c669.png)

Seems correct?

**Comment by bakerboy908** [comment]
Strange, still not for me.
![image](https://user-images.githubusercontent.com/11485213/138226414-38dfa8a5-f668-4b1f-9c79-c1bec65bf74b.png)
I have also tried in incognito too
Using Chrome

**Comment by bakerboy908** [comment]
Looks like this link is redirecting to different integrations for me.
https://my.home-assistant.io/redirect/config_flow_start?domain=waze_travel_time

Any advice on who i can find out what is causing this?
Tried in edge too.

**Comment by frenck** [comment]
That link is perfectly fine.

**Comment by bakerboy908** [comment]
Must have been some strange DNS issue, working fine now
