### ISSUE TITLE
Add sample Sensor definition specifically for watching Electricity usage, Solar production

### ISSUE THREAD

**Issue by hmakmur** [home-assistant/home-assistant.github.io#19892]
### Feedback

Could you add sample sensors definition needed for this statistics? I have been trying to get my solar production to show up but had not been able to do so since I dont know what is expected.

### URL

https://www.home-assistant.io/more-info/statistics/

### Version

2021.10.6

**Comment by frenck** [comment]
This page is not about sensors? 
Statistics is something the integration needs to support, to adjust an integration, please consult the developer documentation.
