### ISSUE TITLE
Please add support for recently released Smartmi Humidifier

### ISSUE THREAD

**Issue by easuvorov** [home-assistant/home-assistant.github.io#19891]
### Feedback

Please add support for recently released Smartmi Humidifier model deerma.humidifier.jsq4 (CJSJSQ01DY). It's a nice little guy who does his job quite decently. It's supported in Mi Home but curently Xioami Miio integration fails to connect to the device.

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2021.10.6

**Comment by bieniu** [comment]
This is a documentation repository. You shouldn't open issues that target `core` here. Besides, feature requests should be opened [here](https://community.home-assistant.io/c/feature-requests/13). You can tag me in the feature request on the community and I'll try to help.
