### ISSUE TITLE
According to the installation operation on the official website, the installation error is reported, and the same problem occurs when installing the latest version or the old version on Pi4b! !

### ISSUE THREAD

**Issue by LA-cctv** [home-assistant/home-assistant.github.io#19897]
### Feedback

21-02-02 17:19:06 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information 
21-02-02 17:19:06 INFO (MainThread) [supervisor.host] Host information reload completed 
21-02-02 17:19:34 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection 
21-02-02 17:19:34 WARNING (MainThread) [supervisor.homeassistant.core] Error on Home Assistant installation. Retry in 30sec
 21-02-02 17:20:04 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection 
21-02-02 17:20:04 WARNING (MainThread) [supervisor.homeassistant.core] Error on Home Assistant installation. Retry in 30sec 
21-02-02 17:20:34 WARNING (MainThread) [supervisor.jobs] 'Updater.fetch_data' blocked from execution, no supervisor internet connection 21-02-02 17:20:34 WARNING (MainThread)

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.10.6

### Additional information

![还是不行](https://user-images.githubusercontent.com/92729962/138389698-0aab768c-f675-43c6-af69-637e0bfc289b.png)
![log日志](https://user-images.githubusercontent.com/92729962/138389750-6611b4b1-213d-4871-88f3-ccb8106d1511.png)

**Comment by LA-cctv** [comment]
Can anyone help me

**Comment by ikifar2012** [comment]
I don't think this is a docs issue but it seems like this is a problem with your Pi's internet connection

**Comment by frenck** [comment]
Thank you for reaching out. It seems like you are in need of support, however, you have submitted a documentation feedback form instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
