### ISSUE TITLE
Installation of integration fails with API Key

### ISSUE THREAD

**Issue by stuarts0011** [home-assistant/home-assistant.github.io#19898]
### Feedback

The integration does not accept the API key generated from the Amberelectric dev website

### URL

https://www.home-assistant.io/integrations/amberelectric/

### Version

2021.10.6

**Comment by madpilot** [comment]
Can you email info@amber.com.au with your account info? I'll need it to troubleshoot.

**Comment by madpilot** [comment]
Account has no active sites, need to show error message when that occurs.

**Comment by madpilot** [comment]
Will also update HA docs to include note about requiring an active site

**Comment by stuarts0011** [comment]
Why not enable former clients to monitor?

**Comment by madpilot** [comment]
Privacy - we have no way to know if you still live at that house.

The fact you can still see it in the app at the moment is a bug.

**Comment by stuarts0011** [comment]
I can't see usage. Just the current price?

**Comment by madpilot** [comment]
Usage isn't supported in home assistant yet, as we don't provide it in real-time.

We are working on being able to add it retrospectively, but that requires some change to the home assistant recorder

**Comment by stuarts0011** [comment]
Sure. What I mean is that there is no privacy issue allowing former
customers to use the integration. It's just pricing data, not site usage.

**Comment by madpilot** [comment]
The limitation is at the API level (there are some legacy technical reasons for this)

We are going to add demo accounts soon (once we sort out those limitations) that will allow you to do what you want to do.


----------------------------------------------
Myles Eftos
Mobile: +61-409-293-183
