### ISSUE TITLE
Update to include Instructions for Nabu Casa users

### ISSUE THREAD

**Issue by iotemylabs** [home-assistant/home-assistant.github.io#19908]
### Feedback

Updating the documentation for the Flash Briefing API to include instructions for the Nabu Casa users :)

### URL

https://www.home-assistant.io/integrations/alexa.flash_briefings/

### Version

2021.10.6

**Comment by frenck** [comment]
This won't work with the Home Assistant cloud features.
You can use the manual instructions on that page, while using the Home Assistant Cloud Remote UI URL.

This indeed can be clarified on the page referenced.
