### ISSUE TITLE
Shopping List - Sort Order

### ISSUE THREAD

**Issue by Xiondewah** [home-assistant/home-assistant.github.io#19902]
### Feedback

It would be great to be able to sort these alphabetically

### URL

https://www.home-assistant.io/lovelace/shopping-list/

### Version

2021.10.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
