### ISSUE TITLE
iCloud Recofiguration

### ISSUE THREAD

**Issue by dobytunn** [home-assistant/home-assistant.github.io#19905]
### Feedback

When I restarted HA today the iCloud integration is asking to be reconfigured.  After I enter my password I never get the verification code from apple until I restart HA and then the code doesn't work.  I have looked in my config for the .storage and do not have one, I also searched for a iCloud folder and I do not have one either.

Is there another fix for this?

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2021.9.7

### Additional information

I can not update to 2021.10.x yet due to the new Tuya integration.

**Comment by frenck** [comment]
Hi there @dobytunn 👋 

It seems like you want to report an issue with an Home Assistant integration, or a looking for support; However, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
