### ISSUE TITLE
Can't find Binary Sensor page via Search

### ISSUE THREAD

**Issue by GrizzlyAK** [home-assistant/home-assistant.github.io#19914]
### Feedback

If I do a search for Binary Sensor, Binary, or Sensor, Search results never show the Binary Sensor page in the results.  I've noticed this on other pages as well. The title of the page (or the URL) should ALWAYS appear in the searches.

### URL

https://www.home-assistant.io/integrations/binary_sensor/

### Version

2021.10.6

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/138550850-ccb1c383-d06c-42ae-b109-65cecfcc918a.png)

![image](https://user-images.githubusercontent.com/195327/138550859-fa8ec1a1-c7fc-4e68-94b2-d3e3bd57979b.png)


Seems to work?

**Comment by GrizzlyAK** [comment]
No, sorry. I didn't mean there. I mean using the search function at the top right of [this ](https://www.home-assistant.io/)page. If you put Binary in that search field, you don't see the page I referenced above. I DO see Binary Sensor Group though. 

I wouldn't normally search for help on the Integrations page, unless I KNOW for sure something is an Integration, and I hardly ever know that for sure. I still don't fully grasp how things are bolted together in HA, and what's an Integration, a Component, an Built in Add-On,  Community Add-On, etc., etc., and the Achitecture Docs never really helped me much.

**Comment by GrizzlyAK** [comment]
This is still a problem. In the Home Assistant Community, if I type Binary into the Search Bar, I don't see the Binary Integration. However, I do see Binary Group and several others. Also, if I type Switch, I see the Switch Integration. Same with every other integration I try. Not sure why, but I've noticed it with other pages as well where a Search does not find the Integration. I don't know how these pages are indexed for the Search function, but something is MISSING on the Binary Integration page that excludes it from the Search Bar.
