### ISSUE TITLE
This tutorial is outdated, many of the Tuya's services are no longer avaliable

### ISSUE THREAD

**Issue by averdion** [home-assistant/home-assistant.github.io#19910]
### Feedback

Trying to configure Tuya iot I am having problems that the tutorial cannot solve.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

**Comment by frenck** [comment]
> Trying to configure Tuya iot I am having problems that the tutorial cannot solve.

Could you be more specific? This documentation is not even 3 weeks old and seems up to date.

Are you running the latest version of Home Assistant?

**Comment by info-path** [comment]
A few days back, everything also worked for me according to the instructions, but today nothing works. Some API services have disappeared on the developer.tuya.com server, such as:

* Smart Home Devices Management
* Smart Home Family Management

There are some new ones, but most are charged.

**Comment by frenck** [comment]
Aah right, A PR is pending to update that indeed.
