### ISSUE TITLE
Flashing an ODROID-N2+: Documentation steps to succeed 

### ISSUE THREAD

**Issue by Tom-ahawk** [home-assistant/home-assistant.github.io#19919]
### Feedback

The docs are not precies enought.

**Flashing an ODROID-N2+**

Change the following:
"Connect a USB keyboard and HDMI connected monitor to your ODROID-N2+, and then connect power."

to

**Enabling SPI boot mode**
"1. Remove the power cord the ODROID-N2+
 2. Toggle the ODROID-N2+ boot mode switch from MMC to SPI. 
 3. Connect a USB keyboard and HDMI connected monitor to your ODROID-N2+
 4. Conect the USB-USB Mini cable to your PC and ODROID-N2+
 5. Connect the power cord to your ODROID-N2+"

### URL

https://www.home-assistant.io/common-tasks/os#flashing-an-odroid-n2

**Comment by GPrince00** [comment]
@Tom-ahawk , Is it just makes this simple text changes?

**Comment by Tom-ahawk** [comment]
As the N00b I am, I used a couple hours not getting the N2+ to appear as a hard drive on my PC. Did eventually find a post in the HA forum where others have had the same problem and the solution explained, - the USB-USB Mini cable must be hooked up between the N2+ and the PC **before t**he N2+ is powered on.
Would think this eliminates a lot of frustration for N00bs starting with N2+.
