### ISSUE TITLE
calculation of Adhan time

### ISSUE THREAD

**Issue by samimasad** [home-assistant/home-assistant.github.io#19920]
### Feedback

Hi
I  just do not know where do you set the location for the Adhan calcualtion because it is not part of the config and it is wildly wrong from my side

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2021.10.6

**Comment by frenck** [comment]
The integration picks up the location setting from Home Assistant itself.
You can configure those coordinates in the general settings of Home Assistant.

[![Open your Home Assistant instance and show your general Home Assistant settings.](https://my.home-assistant.io/badges/general.svg)](https://my.home-assistant.io/redirect/general/)
