### ISSUE TITLE
Measurement Units configured in Dashboard are not the same ones in HA

### ISSUE THREAD

**Issue by santibur06** [home-assistant/home-assistant.github.io#19932]
### Feedback

I've changed the measurement units all to Metric/Celsius, etc. in my Ambient Weather's website dashboard but when I set up the integration in HA it defaults to Imperial, i've tried changing them back and forth, creating new API and App keys, deleting and re-adding the integration and nothing has helped.

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/931452/138575930-ed322d1b-da79-4cbb-839c-8938ec9b1cb7.png">

<img width="197" alt="image" src="https://user-images.githubusercontent.com/931452/138575954-3181e073-9736-40fd-8cb7-fe5cd8e1c02c.png">

### URL

https://www.home-assistant.io/integrations/ambient_station/

### Version

2021.10.6

**Comment by frenck** [comment]
Hi there @santibur06 👋 

It sounds like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
