### ISSUE TITLE
mieu01 Manual Alarm Triggering

### ISSUE THREAD

**Issue by OzanDost** [home-assistant/home-assistant.github.io#19947]
### Feedback

I'm trying to use my non-mi sensors to trigger my mi hub's siren but I can't seem to manually trigger the alarm. It's an european version gateway (lumi.gateway.mieu01)

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2021.10.6

**Comment by frenck** [comment]
hi there @OzanDost 👋 

It seems like you are in need of support, however, you have submitted documentation feedback instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
