### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PatrickGlesner** [home-assistant/home-assistant.github.io#19949]
### Feedback

Broken link "OS-Agent" in "Diagnostics" section.

Best regards,
Patrick.

### URL

https://www.home-assistant.io/integrations/analytics/

### Version

2021.10.6

**Comment by stefanroelofs** [comment]
This issue may be closed.
Is fixed by: #19958

**Comment by cgtobi** [comment]
Thanks for letting us know.
