### ISSUE TITLE
using tracker with Huawei HG659

### ISSUE THREAD

**Issue by Flaming-crossbow** [home-assistant/home-assistant.github.io#19964]
### Feedback

I am missing what one should do when one wants to follow the example with different parameters. 
The example shows a Netgear router for example but i have a Huawei HG659 router. How do i figure out how to make use of the device tracker with a huawei router?

the second thing i am missing is an example of what ends up on the dashboard when the example was followed incorrectly. 

### URL

https://www.home-assistant.io/integrations/device_tracker/

### Version

2021.10.6

**Comment by frenck** [comment]
The example on the page you linked, is a random example to give an idea of what device_tracker does/is.

If you want to configure your device, you need to see if there is an integration for it that supports your device. You can find all our integrations on this page: <https://www.home-assistant.io/integrations/>

**Comment by Flaming-crossbow** [comment]
> If you want to configure your device, you need to see if there is an integration for it that supports your device. You can find all our integrations on this page: https://www.home-assistant.io/integrations/

okay thanks, another "new to HA" question: if my device is not supported in the current integrations what would be the next step? i was thinking to raise a request on the community.home-assistant and contact the developers behind the Huawei LTE and Huawei Router integrations to ask what is needed to get the Huawei HG659 routers supported. Would that be a logic step? I like HA but i am really having a hard time finding my way in the basics.

**Comment by frenck** [comment]
If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
