### ISSUE TITLE
hue accessories

### ISSUE THREAD

**Issue by nrichards0000** [home-assistant/home-assistant.github.io#19974]
### Feedback

It is unclear to me if we must have the Hue "Hub" device to control Hue Accessories.  

For example can I just buy Hue motion sensor and add it or can I only add the hub and subsequently the devices?

thank you

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2021.10.6

**Comment by balloob** [comment]
The first sentence on the linked page mentions you need a Hue bridge: (emphasis mine)

> The Philips Hue integration allows you to control and monitor the lights and motion sensors connected to your **Hue bridge**.

**Comment by nrichards0000** [comment]
Thank you for your response

Recommend for clarity title be changed to Philips Hue Bridge.

Kind regards
