### ISSUE TITLE
Sensor definitions

### ISSUE THREAD

**Issue by kbray0009** [home-assistant/home-assistant.github.io#19973]
### Feedback

Hey I'm new to this, and I would appreciate a little more detail around what the sensors are measuring. Thanks.

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2021.10.6

**Comment by frenck** [comment]
I'm not sure what kind of details you are looking for, isn't this enough?

![image](https://user-images.githubusercontent.com/195327/138783021-01463d1d-4879-4928-b518-0fb2a5c5d0ce.png)

If not, could you try to explain what you'd expected?

**Comment by kbray0009** [comment]
Specifically, I don't know the different between Site and Load. Thanks!

**Comment by frenck** [comment]
Site is what Tesla calls Grid in their mobile app, and I think Load is what is called Home in the mobile app. But I can't verify that (don't own a Powerwall).

**Comment by kbray0009** [comment]
Honestly the only values that make sense to me are the Powerwall Site Now, Powerwall Load Now, and Powerwall Solar Now.  These correspond to values in the ap.  Here are some screenshots of my integration. 
![IMG_7873](https://user-images.githubusercontent.com/1383878/138894390-974716c5-1f96-41c9-8a40-1e6d77451e85.PNG)
![IMG_7872](https://user-images.githubusercontent.com/1383878/138894400-78148284-62a9-42db-a065-bdbd816d4e09.PNG)
<img width="363" alt="Screen Shot 2021-10-26 at 9 51 51 AM" src="https://user-images.githubusercontent.com/1383878/138894438-618f482f-a50e-49c2-b2cf-c20f2d9659ab.png">

**Comment by frenck** [comment]
I have no idea, maybe the one of the codeowner can respond ohis.

**Comment by kbray0009** [comment]
I think I figured it out, thanks for your help.
