### ISSUE TITLE
Some versions no longer seem supported

### ISSUE THREAD

**Issue by cralwalker** [home-assistant/home-assistant.github.io#19977]
### Feedback

[Newbie warning] 

Hi, would it be possible to update this document? I have tried to update versions myself and got into a knot, not able to successfully install Home Assistant.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.10.6

**Comment by frenck** [comment]
> Hi, would it be possible to update this document?

This document is up to date.

I would help if you could tell us a little more about the problems you have been experiencing.
