### ISSUE TITLE
Statistics Graph - Colors

### ISSUE THREAD

**Issue by Tokn59** [home-assistant/home-assistant.github.io#19986]
### Feedback

Hi, great implementation but it would be very nice if could define colors of the lines/bars ourselves. Also a combination of bars and lines in the same graph would be very nice.

### URL

https://www.home-assistant.io/lovelace/statistics-graph/

### Version

2021.10.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
