### ISSUE TITLE
Using tracker with Huawei HG659 router

### ISSUE THREAD

**Issue by Flaming-crossbow** [home-assistant/home-assistant.github.io#19985]
### Feedback

Are there plans to add support for the Huawei HG659 routers? Is there anything i can do to help creating support for these routers?

### URL

https://www.home-assistant.io/integrations/huawei_lte/

### Version

2021.10.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by scop** [comment]
To expand a bit, if the huawei_lte integration doesn't work with your router, I suggest first verifying if https://github.com/Salamek/huawei-lte-api/ works with it. If it doesn't, then that's the project to look into, we use it under the hood. If it does, you can file another issue here along with details what exactly doesn't work, and tracebacks and log entries with diagnostic info and we can have a look.

**Comment by Flaming-crossbow** [comment]
> To expand a bit, if the huawei_lte integration doesn't work with your router, I suggest first verifying if https://github.com/Salamek/huawei-lte-api/ works with it. If it doesn't, then that's the project to look into, we use it under the hood. If it does, you can file another issue here along with details what exactly doesn't work, and tracebacks and log entries with diagnostic info and we can have a look.

Thanks for the reply and explanation Scop.
I will look into it!
