### ISSUE TITLE
Data cannot be updated continuously

### ISSUE THREAD

**Issue by WeR-Best** [home-assistant/home-assistant.github.io#19981]
### Feedback

The data can only be updated continuously for a few hours, after which real-time data cannot be obtained.

This question started on the weekend
core-2021.10.6
supervisor-2021.10.6

### URL

https://www.home-assistant.io/integrations/atome/

### Version

2021.10.6

**Comment by frenck** [comment]
Hi there @ideatechfr 👋 

It sounds like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. We cannot fix such an issue by adjusting the documentation.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
