### ISSUE TITLE
Secure access guideline

### ISSUE THREAD

**Issue by TheS1ngularity** [home-assistant/home-assistant.github.io#19994]
### Feedback

Hi there,
Thanks a lot for your hard work on Home Assistant, an amazing ecosystem.
I've been trying to configure secure remote access to my HA, but I'm finding mixed blogs mostly, nothing official from HA? 

Please add DuckDNS + Let's Encrypt + HTTP configuration tutorial directly in HA documentation, it's critical that all remote access is correctly secured and not hindered by some blogger with bad intentions. 

I'm still confused as to what configuration to add to my configuration.yaml for the http integration, please advise and add this to your documentation

### URL

https://www.home-assistant.io/docs/configuration/securing/

### Version

2021.10.6

### Additional information

Using the latest stable release of HassOS

**Comment by frenck** [comment]
> nothing official from HA?

We don't have anything official, as with security, things are hard. Our recommendation is: If you don't know what you are doing: do not expose your instance to the outside internet. Use a VPN solution or Home Assistant Remote UI (Cloud) if you really want to access it remotely.

There are community guides, but like everything with security, things quickly change and might give you a false sense of security. Anyways, those are not our responsibility.
