### ISSUE TITLE
Suspend on Debian

### ISSUE THREAD

**Issue by benblb** [home-assistant/home-assistant.github.io#19995]
### Feedback

I know it doesn't exactly pertain to the HA installation, but a note to **disable Suspend mode on Debian** would be awesome! I did a fresh Debian 11 install and was super confused that HA kept going down. Finally tracked it back to the OS going to sleep. 

Might save some others a bit of time. This note might belong with the convenience installation script or on HA docs. Either would be okay. 

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2021.10.6

**Comment by frenck** [comment]
This is system configuration and considered out of scope for the Home Assistant project.
When using a Home Assistant Supervised installation, we expect the user to have sufficient  knowledge to maintain and configure their own system (it is considered an advanced installation method).

Nevertheless, thanks for your suggestion.

**Comment by benblb** [comment]
That's fair. What may be considered in scope is that HA supervised does not keep the system awake. Maybe a note about that somewhere? I made the (unfounded and incorrect) assumption that it would which is why during installation I totally forgot to disable suspend. 

While I know this instruction isn't in scope, I don't see the harm in including it if it could help others. Even advanced users have lapses in judgement, but we're really good at following complete documentation! 

PS @frenck - absolute legend. I was reading through the forums yesterday and kept seeing your name pop up.

**Comment by frenck** [comment]
> Maybe a note about that somewhere?

Again, out of scope. We assume one know how to manage their Debian systems. If one needs these hints, we recommend looking into a different installation method.

> PS @frenck - absolute legend.

❤️
