### ISSUE TITLE
The new Tuya integration is a real mess

### ISSUE THREAD

**Issue by avviano** [home-assistant/home-assistant.github.io#20003]
### Feedback

First, setting up the new Tuya integration is super complicated. Second, I followed the instruction yet nothing works. The APIs are missing (not the same as in the instructions). Then, when I try to scan the QR code, I get an error message something about not using the right data center. And and and. Terrible experience.  

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

**Comment by avviano** [comment]
The API Services "Smart Home Devices Management" does not exist. Its in the screenshot on the instructions page, but missing when you try to set up the APIs.  
When I try to scan the QR code in the iOT Platform, I get an error message "You cannot scan the QR code to add a device deployed in another data center". 

Why did my previous integration stop working after I updated HA without a warning? Now I have to go through this super complicated migration. I wouldn't complain, if the migration went smoothly, but the instruction in no way reflect what actually happens when you try to follow them.  

Sorry to say, but this "new" integration and these installation procedures are a real mess!!!!!

**Comment by avviano** [comment]
I think I am just going to sell all my tuya devices. I am really fed up with this nonsense.

**Comment by frenck** [comment]
Thanks for your opinion on the new Tuya integration, but that is not what this form is for.

If you'd like to express and discuss suchs things, please use the community forums. Thanks!
