### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by DTTerastar** [home-assistant/home-assistant.github.io#20002]
### Feedback

I find this warning quite ridiculous.  Docker contains things.  Thus why we call them containers...

### URL

https://www.home-assistant.io/more-info/unsupported/software/

### Version

2021.10.6

**Comment by frenck** [comment]
If you want to have full control and do your own thing, please use the Home Assistant Container installation method.

Furthermore, this is not documentation feedback, and thus closing this.
