### ISSUE TITLE
Example of use of services missing

### ISSUE THREAD

**Issue by Hippe-Lip** [home-assistant/home-assistant.github.io#20015]
### Feedback

Nice page! But for the just a bit less technical people I miss examples how to use the services like
SERVICE BLUESOUND.JOIN
Sorry, but I have no idea how and where to use these. Any help or clear example for at least one of the services would be appreciated!

### URL

https://www.home-assistant.io/integrations/bluesound/

### Version

2021.10.6

**Comment by Hippe-Lip** [comment]
Doesn't seem important enough to take any action?
In that case I have to simply wait.... (?)

**Comment by Hippe-Lip** [comment]
Unfortunately there is no one to pick up this item. 🤷‍♂️

Would be nice if anyone reacted, though…

**Comment by frenck** [comment]
It's an open-source project, it relies on contributions from people.

I personally have no idea about the blue sound stuff, but if you do, feel free to edit the page!

../Frenck
