### ISSUE TITLE
Tuya power, voltage and current?

### ISSUE THREAD

**Issue by JayMcG** [home-assistant/home-assistant.github.io#20010]
### Feedback

Hi.

I have updated my HA to incorporate the latest Tuya integration. I see that it still does not import power, voltage and current information from the devices? Is there a way to get this information?

I am currently using the Local Tuya integration but the attributes are only being updated when I go into the Smart Life app, which is frustrating and makes the data useless. I am not sure if there is a way to poll the platform?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

**Comment by frenck** [comment]
Sensors are not supported in Home Assistant 2021.10 (not listed in the documentation as support either).

It will be part of the upcoming 2021.11 release though.
