### ISSUE TITLE
Not understanding what code to use?  I assume the code in the URL after the email from SS?

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/home-assistant.github.io#20024]
### Feedback

Tried the code in the url and it does not work.
https://tsv.prd.platform.simplisafe.com/v1/tsv/confirm?code=xxxxxx.x.xx...........
I used the information after code=xxx and got invalid authentication
### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2021.10.6

### Additional information

Updated integration, deleted, tried to reinstall and code fails.

**Comment by bachya** [comment]
This was added in the 2021.11.0 beta; are you sure you're using 2021.10.6?

Either way, the docs that go with this haven't been released yet. They refer to these instructions: https://simplisafe-python.readthedocs.io/en/latest/usage.html#accessing-the-api (pay particular attention to step 8 and the structure of the URL that contains the code – you're attempting to use a different URL).

**Comment by bschatzow** [comment]
I am using the beta. Not sure where the 2021.10.6 came from, maybe the supervisor version. I have the latest and am updating the supervisor to .8. I will try again after the update to the supervisor update. Tried several times getting different authorization codes each time. Each failed.  I looked at your instructions again and 8 references a different url then I am getting.  When verify the code my link is https://tsv.prd.platform.simplisafe.com/v1/tsv/confirm?code=xxxxxx so I must be going to the wrong tab.  I am opening the tab that gets emailed to me. I'll try again and see if there is a code in any of the other tabs.  
I have tried again and none of my tabs have anything to do with mobile.  Maybe it is different on a PC vs iphone?  I will try on my android phone and see if it makes a difference.

I tried on my phone no difference. My urls do not match yours. 
Your url: com.simplisafe.mobile://auth.simplisafe.com/ios/com.simplisafe.mobile/callback?code=<CODE>
mine is https://tsv.prd.platform.simplisafe.com/v1/tsv/confirm?code=<CODE>
This is from the tab:
![image](https://user-images.githubusercontent.com/36886571/139292857-7af41767-e86e-4729-a510-73647287c039.png)
This was tab 1, but turned into tab 2.

Tab 1 prior to verify.

![image](https://user-images.githubusercontent.com/36886571/139293650-17e09353-d428-492c-878f-f6fa263775b8.png)

Not sure where I can capture the correct code.  Tab 1, now tab 2 has a very long token.

Tried incognito and no difference.  I'll turn on the console in chrome and see if any code is there.

Found the correct code in the console:
Failed to launch 'com.simplisafe.mobile://auth.simplisafe.com/ios/com.simplisafe.mobile/callback?code=<CODE>' because the scheme does not have a registered handler.
It now works.
![image](https://user-images.githubusercontent.com/36886571/139295579-ef440659-ad3e-46a9-85aa-bcb8bc608fea.png)

**Comment by bachya** [comment]
Correct, the code comes with the `com.simpliSafe.mobile` URL. Glad you got it working.

**Comment by craigccfl** [comment]
Know this is closed, had the same issue and fixed successfully using developer tools and using the code in the console.

**Comment by bschatzow** [comment]
SimpliSafe just lost authentication (again).  I had no updates on my end.
