### ISSUE TITLE
The expand function and filter can not be used with media player and light groups

### ISSUE THREAD

**Issue by cdrfun** [home-assistant/home-assistant.github.io#20028]
### Feedback

The `expand` function and filter can not be used directly with media player and light groups. This should be addressed in the documentation. A working alternative could be:
`{{ expand(state_attr('media_player.lautsprecher', 'entity_id')) | map(attribute='entity_id') | list }}`

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2021.10.6

**Comment by frenck** [comment]
- Isn't this a bug?
- How would it map `entity_id`? As that is a single value?

**Comment by cdrfun** [comment]
>     * Isn't this a bug?

I don't exactly know. This seems to be common knowledge within the community. I stumbled upon this when [I asked for help in the forum](https://community.home-assistant.io/t/template-to-get-entities-with-specific-state-out-of-a-media-group/350751).

>     * How would it map `entity_id`? As that is a single value?

You are correct - this was specific for my use case. I'd think it's `{{ expand(state_attr('media_player.lautsprecher', 'entity_id')) | map(attribute='entity_id') | list }}` then, but don't take that for granted, I'm not good in templating, yet, and I don't have a "normal" group I can test it with.

**Comment by cdrfun** [comment]
This issue is still relevant.
