### ISSUE TITLE
Somfy API

### ISSUE THREAD

**Issue by ClaireRovic** [home-assistant/home-assistant.github.io#20027]
### Feedback

The documented API is only available for end-users from Europe, Middle-East and Africa.

https://developer.somfy.com/faq-page (Who is the program designed for ?

### URL

https://www.home-assistant.io/integrations/somfy/

### Version

2021.10.6

### Additional information

Have rang Australian support and they clearly stated it was not available - so angry as bought it based on HA Somfy API

**Comment by Psykoflex2019** [comment]
Hey,

The somfy api, is it compatible with the somfy alarm? just with the "link"?

Thanks you
