### ISSUE TITLE
Adax - get KWh Energy reading

### ISSUE THREAD

**Issue by MichaelRV82** [home-assistant/home-assistant.github.io#20030]
### Feedback

Hi,

it would be great to add energy readings to the ADAX integration. The Adax App is providing the total energy usage for the heating. Would be great if that reading can be part of the Adax Home Assistant Integration so it can be used in the Energy Dashboard.

It might be a limitation on Adax side though: https://adax.no/en/wi-fi/api-development/

/Michael

### URL

https://www.home-assistant.io/integrations/adax/

### Version

2021.10.6

**Comment by Danielhiversen** [comment]
Data are not available from the Adax API.
Ask Adax to add support for it :)
