### ISSUE TITLE
Storing Secrets -> Debugging Secrets

### ISSUE THREAD

**Issue by LucaMannella** [home-assistant/home-assistant.github.io#20034]
### Feedback

Hi all,

I am sorry if this issue could be solved with more experience with Home Assistant, but I am new to this platform (like other developers that read the documentation, I guess :D).
Currently, inside the documentation page "Storing Secrets", specifically in "Debugging Secrets", there is written to execute this command to retrieve the list of secrets:

``` console
hass --script check_config --secrets
```

However, this command does not work on my Home Assistant OS installation.
I don't know if I should create or import this script somewhere or if this command was designed for a different Home Assistant installation. Anyway, whatever is the reason, I think this part inside the documentation could be more precise and provide developers with more information.

I hope to be useful, and thank you for your time!

### URL

https://www.home-assistant.io/docs/configuration/secrets/

### Version

2021.10.6

### Additional information

Currently, I'am running Home Assistant OS 6.5 (core-2021.10.6, supervisor-2021.10.6) on a Linux virtual machine.

**Comment by frenck** [comment]
Option 2 is not available on normal installations, but only on the manual Home Assistant Core installation types.

We need to adjust the documentation to make that clear indeed.

**Comment by LucaMannella** [comment]
Dear Franck,
Thank you for your fast reply.

I would like to propose you also to clarify the Option 1.

From my point of view, it is not completely clear how to visualize this debug information.
I understand that the line `logger: debug` should be added in the `secrets.yaml` file (e.g., I put it on the top of the secrets file).
However, I don't understand where and exactly when I can visualize this debug information.

Thank you again for your time.

**Comment by frenck** [comment]
Honestly, I don't see the whole point of all this debugging.
Just click on check configuration button on the Server Controls page and be done.

**Comment by LucaMannella** [comment]
I am new to the platform, and I was trying to understand the functionalities offered by Home Assistant.
I would like to understand how I can use this feature and, at the same time, help you in improving the documentation.
If this feature is not particularly useful, I forget about it, and I will follow your suggestion.

Thank you again for your time.
