### ISSUE TITLE
recorder: db_url with secret.yaml

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#20045]
### Feedback

It is not clear whether db_url supports the use of passwards, usernames stored in secret.yaml

### URL

https://www.home-assistant.io/integrations/recorder/

### Version

2021.10.6

**Comment by ludeeus** [comment]
That is not an integration consern.
The `db_url` is a string, you can not have parts of that string be from secrets, but you can have the entire `db_url` as a secret.
