### ISSUE TITLE
usage of data_template

### ISSUE THREAD

**Issue by shivrick** [home-assistant/home-assistant.github.io#20041]
### Feedback

Could you mention data_template on this page, or link to a page that describes more about it?
I spent a lot of time watching the UI eat my template because I was trying to put it on a data: element.

For example, the "light" page example (https://www.home-assistant.io/integrations/light/)
uses data:
`  - service: light.turn_on
    target:
      entity_id: light.master_bathroom_lamp
    data:
      brightness: 127
`

so, I was trying to use the template in place of the 127.
`  - service: light.turn_on
    target:
      entity_id: light.master_bathroom_lamp
    data:
      brightness: '{{ trigger.to_state.attributes.brightness }}'
`
But the automation would error out if I left the single quotes, and the UI would eat the template if I removed them.

I finally found some mention about data vs data_template, which helped me do this (which worked)
`  - service: light.turn_on
    target:
      entity_id: light.master_bathroom_lamp
    data_template:
      brightness: '{{ trigger.to_state.attributes.brightness }}'
`

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2021.10.6

**Comment by frenck** [comment]
`data_template` doesn't exist anymore.

It is a thing from the past, it has been removed from Home Assistant over a year ago.
It still works though, but is simply an alias to `data`. So, there is no difference at this point in using `data` vs `data_template`.

We recommend using `data` as `data_template` might be deprecated or removed in the future.
