### ISSUE TITLE
SENSOR_ID requires quotes

### ISSUE THREAD

**Issue by ccsrsj** [home-assistant/home-assistant.github.io#20049]
### Feedback

Feedback

Although all are strings, I found SENSOR_ID requires quotes around it to work?

sensor:
platform: neurio_energy
api_key: CLIENT_ID
api_secret: CLIENT_SECRET
sensor_id: SENSOR_ID

didn't work, I kept getting errors about wrong type in sensor.py.

sensor:
platform: neurio_energy
api_key: CLIENT_ID
api_secret: CLIENT_SECRET
sensor_id: "SENSOR_ID"

solved the problem.

### URL

https://www.home-assistant.io/integrations/neurio_energy/

### Version

2021.10.6

### Additional information

I can see someone else raised the same problem in #18334 which was redirected as an integration problem, but it does appear to simply be an issue with the documentation on this page now being incorrect.

**Comment by frenck** [comment]
> Although all are strings, I found SENSOR_ID requires quotes around it to work?

That depends on the contents and YAML, not Home Assistant.
