### ISSUE TITLE
Missing login command under Console access

### ISSUE THREAD

**Issue by primoz-k** [home-assistant/home-assistant.github.io#20048]
### Feedback

Hi,

in **Console access** section it should mention the `login` command so users know how to get to login prompt for the `root` access.

### URL

https://www.home-assistant.io/common-tasks/os/#console-access

### Version

2021.10.6

**Comment by frenck** [comment]
It is either not needed or, in case it does, already listed on that page. Am I missing something?

**Comment by axilleas** [comment]
It is mentioned here https://www.home-assistant.io/common-tasks/os/#enable-i2c-via-home-assistant-operating-system-terminal, but not under https://www.home-assistant.io/common-tasks/os/#console-access.

>  in case it does

I submitted https://github.com/home-assistant/home-assistant.io/pull/20083 :rocket:
