### ISSUE TITLE
Include information on event triggers for MotionEye core integration

### ISSUE THREAD

**Issue by ConorIA** [home-assistant/home-assistant.github.io#20057]
### Feedback

From the motioneye integration options, it was clear to me that Home Assistant created a webhook for motion detection. What was not clear to me was how this information was actually used. I eventually found the information over at the [readme](https://github.com/dermotduffy/hass-motioneye#motion-event) by @dermotduffy. I recommend that this information be incorporated into https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/motioneye.markdown

### URL

https://www.home-assistant.io/integrations/motioneye/

### Version

2021.10.6

**Comment by dermotduffy** [comment]
Yes. I plan to move that entire README over to Core, once the code is all submitted for the migration (the PRs are all awaiting review for multiple months). If you'd like to accelerate that, PRs are very welcome to move parts of the README over now.
