### ISSUE TITLE
Feature request: Multiple modes - we should provide the option to turn on 'cool', 'heat', 'dry' etc... if this is an AC

### ISSUE THREAD

**Issue by zivgin** [home-assistant/home-assistant.github.io#20063]
### Feedback

I believe we should also add the possibility for humidity sensor to be attached to the thermostat

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

### Version

2021.10.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
