### ISSUE TITLE
Unable to scan QR code - wrong data center.

### ISSUE THREAD

**Issue by craigsup93** [home-assistant/home-assistant.github.io#20061]
### Feedback

Hi,

I have followed the guide, and added all the data centers to my cloud project (I tried both singular China & Western Europe to no success). When I scan the QR code on my Smart Life app, I get "You cannot scan the QR code to add a device deployed in another data center."

I thought adding all the data centers to the project would allow me to link my account but it doesn't seem to be working.
Has anyone figured this out?

Thanks

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

**Comment by craigsup93** [comment]
to add further information, when attempting to authorise on the home assistant integration, I get "Login error (2406): skill id invalid". I have set everything to be UK but I still get these errors. My Tuya IOT platform account is registered as the UK too.

**Comment by frenck** [comment]
@zlinoliver Any idea on this?
