### ISSUE TITLE
Access onkyo-eiscp

### ISSUE THREAD

**Issue by ray557913** [home-assistant/home-assistant.github.io#20068]
### Feedback

I am not sure how to access onkyo-eiscp to check sources.  I see the query but when I try to run it in the Home Assistant terminal, running it in vm player says it can't be found

### URL

https://www.home-assistant.io/integrations/onkyo/

### Version

2021.10.6

**Comment by frenck** [comment]
For information on the use and installation of third-party tools, please consult the third-party tools documentation or website.

In this case: <https://github.com/miracle2k/onkyo-eiscp>
