### ISSUE TITLE
List of devices?

### ISSUE THREAD

**Issue by tekrox** [home-assistant/home-assistant.github.io#20079]
### Feedback

Is there a list of devices? For example, I have a Somfy alarm system in my Tahoma which is not recognized. Maybe the device will help

### URL

https://www.home-assistant.io/integrations/tahoma/

### Version

2021.10.6

**Comment by frenck** [comment]
Alarm Control Panel isn't listed in the list that is in the top of the page you linked?
So, not sure what is missing in this case?
