### ISSUE TITLE
No Information on how to reach the command line execution from the web UI

### ISSUE THREAD

**Issue by ipogodin** [home-assistant/home-assistant.github.io#20086]
### Feedback

No Information on how to reach the command line execution from the web UI
Would you like to add any info?

### URL

https://www.home-assistant.io/docs/tools/hass/

### Version

2021.10.6

**Comment by frenck** [comment]
> No Information on how to reach the command line execution from the web UI

You can't.

If anything,  we should add a note about this tool only being available to Home Assistant Core users.

**Comment by drthanwho** [comment]
I'd also argue that both hass and check_config pages should be merged into one since check_config relies on hass

**Comment by ludeeus** [comment]
Check configuration already exists in each common task page:
- https://www.home-assistant.io/common-tasks/os/#configuration-check
- https://www.home-assistant.io/common-tasks/container/#configuration-check
- https://www.home-assistant.io/common-tasks/core/#configuration-check
- https://www.home-assistant.io/common-tasks/supervised/#configuration-check

**Comment by eikowagenknecht** [comment]
> > No Information on how to reach the command line execution from the web UI
> 
> You can't.
> 
> If anything, we should add a note about this tool only being available to Home Assistant Core users.

I think that's a good idea, as a (new) HassOS user I see value in adding that clarification, especially since "The command-line part of Home Assistant" (hass) and "The Home Assistant CLI" (ha) sound almost the same.
