### ISSUE TITLE
Allow multiple pilight protocols per device.

### ISSUE THREAD

**Issue by mmende** [home-assistant/home-assistant.github.io#2008]
In the pilight configuration you can use [multiple protocols per device](https://wiki.pilight.org/doku.php/config#multiple_protocols_per_device) what increases the success rate when switching devices (in other words the switching process is more likely to happen successfully since multiple protocols will be send to switch the device).

It would be great if the home-assistant pilight plugin would allow this as well or even better: if the plugin would allow switching the devices in the pilight configuration like [pilight-control](https://wiki.pilight.org/doku.php/pilight-control) does.

**Comment by robbiet480** [comment]
This issue should be opened in the primary [Home Assistant repository](https://github.com/home-assistant/home-assistant/issues/new), not this one (docs repo).
