### ISSUE TITLE
Tuya Integration - Can't setup

### ISSUE THREAD

**Issue by stuarts0011** [home-assistant/home-assistant.github.io#20089]
### Feedback

I have linked my Tuya app to the IOT platform and can see my Tuya devices on the IOT platform

On configuring the HA integration I get "Unknown error occurred"

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.6

**Comment by stuarts0011** [comment]
Ok I'm now getting Login error (2406): skill id invalid but all the details are correct.

**Comment by drthanwho** [comment]
There are common errors and their solutions further down on the page e.g. https://www.home-assistant.io/integrations/tuya/#2406-skill-id-invalid

**Comment by stuarts0011** [comment]
Yes I read that. All of the inputs are correct. I should not be getting error 2406

**Comment by RubenWeijers-TomTom** [comment]
I'm experiencing the same error

**Comment by drthanwho** [comment]
In most cases I've seen it's the difference between data centre chosen and region. Also some specific countries seem to be affected as well based on this [#57945](https://github.com/home-assistant/core/issues/57945). Regardless, better to ask in that issue which is in the Core repository. This repository is about issues with the documentation itself.

**Comment by stuarts0011** [comment]
thanks
Regards

Stuart
