### ISSUE TITLE
SwitchBot integration page does not mention Bluetooth conflicts

### ISSUE THREAD

**Issue by ellaizee** [home-assistant/home-assistant.github.io#20087]
### Feedback

The SwitchBot integration page does not mention that other integrations using Bluetooth may interfere with the SwitchBot integration (including BLE tracking). I understand that many users are knowledgeable enough to know this already, but there are plenty of us who don't.

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2021.10.6

**Comment by drthanwho** [comment]
Was it not a `Config flow could not be loaded` error? Because that is already mentioned here https://www.home-assistant.io/integrations/switchbot/#config-flow-could-not-be-loaded

**Comment by ellaizee** [comment]
No. And even if it was that error, the explanation doesn't make sense to a mid-level user like me. Not every person who uses Home Assistant is a developer. I'm just simply suggesting a more straightforward note that you cannot have two Bluetooth dependent integrations using the same Bluetooth dongle. I would also argue the BLE tracker is not a "custom integration" (as mentioned in the error description).

**Comment by AlexCherrypi** [comment]
The other thing is, besides it conflicting with other Bluetooth integrations, you also currently can't select a specific dongle to use with the switchbot integration (as far as I am aware). I just bought another Bluetooth dongle to tackle that exact problem, but after a restart of Homeassistant, the switchbot integration decided to use my new dongle and not keep using the old one.
It would be really beneficial to have a way of selecting what Bluetooth dongle is used with the Switchbot integration.

**Comment by AlexCherrypi** [comment]
Just in case someone has the same problem as me:
I tried to use the SwitchBot integration in conjunction with [the Passive BLE Monitor integration from HACS](https://github.com/custom-components/ble_monitor).
After one action with the SwitchBot integration, the SwitchBot integration just stopped working and did no longer open curtains and so on.
The solution is to buy another BLE dongle. Then configure the Passive BLE Monitor integration to use hci0. Then restart the whole server. The SwitchBot integration will always use the Bluetooth dongle with the highest number (e.g. you have two dongles hci0 and hci1, it will use hci1).
