### ISSUE TITLE
Wrong speedtest

### ISSUE THREAD

**Issue by Marow** [home-assistant/home-assistant.github.io#20099]
### Feedback

I use the speedtest integration.
But for some reason, there is much lower download, upload and the ping is also bad.

Please make it possible to add server_id back or just in input field in the Configuration of the integration where can typing in the server_id of speedtest.net or just make that the server_list in dropdown has all servers that also speedtest.net gives please

If i make speedtest on my pc with correct server, i have around doubled the values...

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2021.10.6

**Comment by frenck** [comment]
Hi there @Marow 👋 

It seems like you want to report an issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
