### ISSUE TITLE
Information about automation upgrade path was removed from the document

### ISSUE THREAD

**Issue by Moonj64** [home-assistant/home-assistant.github.io#20090]
### Feedback

Originally the automation editor document included information about using "automation old:" in configuration.yaml in order to simultaneously use the new automation editor alongside automations that were already created using the older yaml based format.  However this information was removed in commit [b6f43edbb3e5232a2c3ea2afb1d5fe27bef605ba](https://github.com/home-assistant/home-assistant.io/commit/b6f43edbb3e5232a2c3ea2afb1d5fe27bef605ba#diff-2df784e9800cfad7d9f5e3814f184f6fb651a02dc7f6a64057c7ad9e7015e7f0).  This documentation removal makes the upgrade path much more difficult as the information it contained is important in doing a gradual transition.

### URL

https://www.home-assistant.io/docs/automation/editor/

### Version

2021.10.6

**Comment by frenck** [comment]
This is part of splitting a configuration, and information on that subject can be found here:

<https://www.home-assistant.io/docs/configuration/splitting_configuration/#example-combine-include_dir_merge_list-with-automationsyaml>
