### ISSUE TITLE
Cargo is missing on the dependency list

### ISSUE THREAD

**Issue by majuss** [home-assistant/home-assistant.github.io#20093]
### Feedback

2021.10 requires cargo, otherwise cryptographie package cannot be installed.

https://www.home-assistant.io/installation/raspberrypi#install-dependencies

### URL

https://www.home-assistant.io/installation/raspberrypi#install-dependencies

### Version

2021.10

**Comment by frenck** [comment]
That installation method is considered advanced. The packages can differ, depending on the OS, system architecture, choice between 32/64 bits OS and depending on how one manages their Python/System environments.

We are expecting users the use such advanced installation method, to know what they are doing and expect them to be able to handle these things.

If this is not the case, we don't recommend on running this installation method, but instead, use e.g., Home Assistant OS or the Home Assistant Container installation methods.
