### ISSUE TITLE
Multiple IFTTT keys not working

### ISSUE THREAD

**Issue by jlhcmx** [home-assistant/home-assistant.github.io#20091]
### Feedback

If I set 3 IFTT keys I get the following errors:

Invalid config for [ifttt]: expected a dictionary for dictionary value @ data['ifttt']['key']. Got None
extra keys not allowed @ data['ifttt']['YOUR_KEY_NAME1']. Got 'YOUR_API_KEY1'
extra keys not allowed @ data['ifttt']['YOUR_KEY_NAME2']. Got 'YOUR_API_KEY2'
extra keys not allowed @ data['ifttt']['YOUR_KEY_NAME3']. Got 'YOUR_API_KEY3'. (See /config/configuration.yaml, line 19).

### URL

https://www.home-assistant.io/integrations/ifttt/

### Version

2021.10.6

**Comment by drthanwho** [comment]
This is the repository for the documentation. You should open your issue under /core repo not here. 

IFTTT can also be setup via the UI maybe that is easier for you to set up. If you open an issue please also provide your configuration

**Comment by frenck** [comment]
As per above, please report issues with Home Assistant integration in the Core issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by jlhcmx** [comment]
> This is the repository for the documentation. You should open your issue under /core repo not here.
> 
> IFTTT can also be setup via the UI maybe that is easier for you to set up. If you open an issue please also provide your configuration

I'm sorry, I have post it here because I followed documentation and documentation is wrong.

**Comment by frenck** [comment]
Could be, or the documentation is correct and it's a bug. The latter can only be concluded as a result from a bug report:

**Comment by drthanwho** [comment]
I suspect your ifttt configuration is not correct. Double check your structure. I just set up 3 keys and I got no errors so something else is wrong

**Comment by jlhcmx** [comment]
> I suspect your ifttt configuration is not correct. Double check your structure. I just set up 3 keys and I got no errors so something else is wrong

Restart your server and you will see the issue

**Comment by drthanwho** [comment]
I did restart and had no issue. Anyway this is now closed. 

Either open an issue under Core repository and provide an example of your configuration or on Discord and someone should be able to help 😃

**Comment by jlhcmx** [comment]
What!! How?! I've just checked again and still get the same error, how did
you set them up? I set them as follows:

-------------------------------------------------------------------
ifttt:
  key:
  jlhmx: dBZl_YRGl9kEIzdk6QKE7W
  jlh_mx: bNRvpvkVtd0M86r2c5wA9
  jorgedez: d6rF-seo4W-Jw25XOeHylD
-------------------------------------------------------------------

then after config validation I get:

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Invalid config for [ifttt]: expected a dictionary for dictionary value @
data['ifttt']['key']. Got
None
extra keys not allowed @ data['ifttt']['jlhmx']. Got
'dBZl_YRGl9kEIzdk6QKE7W'
extra keys not allowed @ data['ifttt']['jlh_mx']. Got
'bNRvpvkVtd0M86r2c5wA9'
extra keys not allowed @ data['ifttt']['jorgedez']. Got
'd6rF-seo4W-Jw25XOeHylD'.
(See /config/configuration.yaml, line 19).
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
thanks for your help

**Comment by drthanwho** [comment]
> I set them as follows:

Look back at the documentation on multiple keys. Your YAML is not valid. There is no spacing between key: and the list of keys . That explains your error you've been getting.

Also probably not a good idea to be sharing your keys. You might want to revoke them now.

**Comment by jlhcmx** [comment]
Really? spaces matter in this type of code? I fix it using the exact same
spaces thanks for your help and apologies for you and Franck again. 🙈 Dont
worry about the keys thanks, they are fake.

**Comment by drthanwho** [comment]
Its YAML. Spaces matter everywhere! 😆
