### ISSUE TITLE
swing positions

### ISSUE THREAD

**Issue by karkaaa** [home-assistant/home-assistant.github.io#20092]
### Feedback

Hello,

Please add feature to set swing positions (bottom, middle, low etc.)

Thank you.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.10.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
