### ISSUE TITLE
problem with day saving

### ISSUE THREAD

**Issue by samimasad** [home-assistant/home-assistant.github.io#20101]
### Feedback

when time switch to day saving , praying times are not adjusted , so it is offseted by one hour

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2021.10.6

**Comment by frenck** [comment]
Hi there @samimasad 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please, report an issue with an integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
