### ISSUE TITLE
Installing without docker?

### ISSUE THREAD

**Issue by xbeaudouin** [home-assistant/home-assistant.github.io#20115]
### Feedback

Hello,
According to your installation document you suggest to install HA without docker for some good reasons (hint "compare installation methods").
But looking on the Installation, you always suggest to either install the prebuild images (whatever is for RPI / virtual environement / whatever) or launch a docker.
As non Linux user but a FreeBSD user, I would like to install that on a jail (well you know something that exist loooooooong time before docker)... But... no documentation or use the dockerfile code...
I know that most users don't give any clue about security, installation and keep the system up to date, but... docker is the new windows OS. "Just install the docker to make it run", is not an option, and not the way OpenSource Operating Systems has been made. 
So please, provide a section : source only installation / power unix administrator to make some people that wish to contrib (or not) to HA the right to install without the hell of docker.

### URL

https://www.home-assistant.io/getting-started/

### Version

2021.10.7

### Additional information

I am using FreeBSD and there is NO docker usuable on this os.

**Comment by ludeeus** [comment]
<https://www.home-assistant.io/installation/linux#install-home-assistant-core> is what you want.

**Comment by xbeaudouin** [comment]
Well this was not really "easy" to find inside the documentation. Regards

**Comment by ludeeus** [comment]
At the top of the installation page it's described like this:
<https://www.home-assistant.io/installation/>
> There are two alternative installation methods available for experienced users:
  ...
  **Home Assistant Core**: Manual installation using Python virtual environment.
  
 Evey section below it shows which installation method is supported on that platform.
