### ISSUE TITLE
will light bulbs be supported soon LB27 r1 team 

### ISSUE THREAD

**Issue by vjmaz** [home-assistant/home-assistant.github.io#20113]
### Feedback

Hi is will wifi Broadlink LB27 R1 be supported please i have purchased 38 and need to add to HA please 

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2021.10.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
