### ISSUE TITLE
How do I add all entities to the logbook card?

### ISSUE THREAD

**Issue by Talor-A** [home-assistant/home-assistant.github.io#20111]
### Feedback

I'd like to enter "all" into the logbook so I can see the last few logbook entities at a glance. is this possible? I can't find a way to do it in the UI and it's not documented. but since that's what the main "logbook" screen is doing it seems like the card should be able to do this

### URL

https://www.home-assistant.io/lovelace/logbook/

### Version

2021.10.7

**Comment by frenck** [comment]
It can't do that.
