### ISSUE TITLE
Tuya Smart Platform Step 3 needs more screen shots 

### ISSUE THREAD

**Issue by joshsinykin** [home-assistant/home-assistant.github.io#20110]
### Feedback

The Tuya Cloud Platform needs more screen shots of the process. For instance scan the QR code is not enough to show people how to find the QR scanning feature in those apps.

Also with the Tuya Cloud Platform steps, I am getting a odd error about linking accounts due to Data Center selections. There is no information about this and what it means. I tired all of the data center choices.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.10.7

**Comment by joshsinykin** [comment]
FYI in the smart life app, if you click on the account profile, then in the top right corner there is a[-] symbol which is the QR scanning feature. I finally got my tuya integration to connect. but this was not obvious the first time thru.

**Comment by joshsinykin** [comment]
Data center choice appears to be only one correct data center, not all of them in the list. For the US, I had to reference the error table at the bottom of the documentation for the correct choice.

**Comment by esbart** [comment]
![TuyaIiot2](https://user-images.githubusercontent.com/58782700/140650685-3db00ede-c4b8-45dd-be03-489881310dcb.PNG)
![TuyaIiot3](https://user-images.githubusercontent.com/58782700/140650692-772009f7-e2e1-4559-ae18-56f45f5b9523.PNG)
![TuyaIiot6](https://user-images.githubusercontent.com/58782700/140650699-f8703e73-fc70-45dd-96b4-9a5ffcfcc69d.PNG)
![TuyaIiot7](https://user-images.githubusercontent.com/58782700/140650701-9558fd9b-abbe-4540-9ef0-d11d8a18454c.PNG)

**Comment by esbart** [comment]
the  4  4 Curtain Switch  but can oly swich with one switch  Two are oly  visble but dont respond to switch commands  If I look in the  Tuya iot debug of the switch i see that the new Tuya doenot com on the IOT platform. The last one is only in the tuya old seen and olso working
The working one in Tuya old and new is a  Curtain Switch 
The  2 others  who are working in the old and well in the new tuya  are two Smart Curtain Switch
The last one that is working in tuya old is from C601   this one is not seen in tuya new 
I have made different debug 	
Anny idea what I do wrong to get the new tuya working
