### ISSUE TITLE
Panels to more world sides

### ISSUE THREAD

**Issue by proasnet** [home-assistant/home-assistant.github.io#20129]
### Feedback

Hi. This is a great integration.
Now I am using it, but is possible add only one world side of panels. On my roof I have a string to two world sides and it can not possible add more than one world side.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.10.7

**Comment by frenck** [comment]
> Now I am using it, but is possible add only one world side of panels. On my roof I have a string to two world sides and it can not possible add more than one world side.

You can just add the integration multiple times. 2, 3, 4, 5, ..10 times if you wanted too :)
