### ISSUE TITLE
Spain electricity hourly pricing (PVPC) Dont works

### ISSUE THREAD

**Issue by auveele** [home-assistant/home-assistant.github.io#20126]
### Feedback

Since this afternoon this integration doesn't load the data from de API.
I didn't find any error in the current log about this integration.
![imagen](https://user-images.githubusercontent.com/5937690/139952158-37e8c264-2c9b-4d9a-844e-51f7101d5618.png)

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2021.10.7

**Comment by auveele** [comment]
> you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L395) for?

No, I'm not listed as code owner!

**Comment by auveele** [comment]
I found this:
`sensor.pvpc_2_0_dha: repeated bad data update, mark component as unavailable source`

**Comment by acrespog** [comment]
Edit: mi error. Mixed log output.

**Comment by azogue** [comment]
It appears they updated 'something' in the ESIOS API server and now it needs some headers to make a successful call :(

I'll try to make a hotfix in the `aiopvpc` library asap 👍

**Comment by frenck** [comment]
Hi there @auveele 👋 

It seems like you want to report an issue with an integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by auveele** [comment]
Oh sorry! The page of homeAssistant brought me here. I've seen that there is already an issue
Thanks a lot!
