### ISSUE TITLE
`last_reset_topic` for MQTT sensors has been deprecated, but not listed as such in docs

### ISSUE THREAD

**Issue by sdwilsh** [home-assistant/home-assistant.github.io#20124]
### Feedback

https://github.com/home-assistant/core/pull/55463 appears to have deprecated this and added a warning, but the documentation does not indicate it is deprecated.

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2021.10.7

**Comment by sdwilsh** [comment]
I also don't see a blog post about this on https://developers.home-assistant.io/blog/, so this change may surprise other makers of X2mqtt software.

**Comment by emontnemery** [comment]
@sdwilsh you're right that the documentation update was forgotten, fixed here: https://github.com/home-assistant/home-assistant.io/pull/20133
