### ISSUE TITLE
joaoapps_join.xxxx_send_tasker

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/home-assistant.github.io#20128]
### Feedback

I am getting a failed to call service calling any of the send_tasker devices.  The error says "unknow error".
The only error in the log is:
```
 File "/usr/src/homeassistant/homeassistant/components/joaoapps_join/__init__.py", line 88, in send_tasker_service
    send_notification(
  File "/usr/local/lib/python3.9/site-packages/pyjoin/__init__.py", line 15, in send_notification
    req_url = SEND_URL + api_key + "&text=" + text
```
not sure if this helps.

### URL

https://www.home-assistant.io/integrations/joaoapps_join/

### Version

2021.10.8 supervisor, core-2021.11.0b4

**Comment by frenck** [comment]
Hi there @bschatzow 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
