### ISSUE TITLE
ZIGBEE 3.0 USB DONGLE PLUS ZHA integration issues 

### ISSUE THREAD

**Issue by MiAutomations** [home-assistant/home-assistant.github.io#20138]
### Feedback

Hello 

I'm trying to add the integration ZHA working with a new Sonoff ZIGBEE 3.0 USB DONGLE PLUS in a HA machine that is based into the proxmox 

But as you can see I can't load the integration/USB PEN into the integration is still in -  Retrying setup always or not loaded This for several Minutes, after this some times the integration and the PEN is discovered ....

I Already performed several Uninstall/install enable/disable, I also check the USb/serial device into the HA Home Assistant I change the USB physical  port and the device is available ... But I cant understand where is the error 

I use this tutorial to perform the installation/configuration :

[https://sonoff.tech/product-review/zigbee-3-0-usb-dongle-plus/   ](url)

But I can't add any device ... I perform the search and I can't find any zigbee device ...  
![image](https://user-images.githubusercontent.com/47602733/140102564-63540ed4-a60b-4276-be92-ba88cb8920f8.png)

The PEN is detected 
![image](https://user-images.githubusercontent.com/47602733/140102624-c8ecdb6b-1631-45ec-985f-c7890611bf88.png)
![image](https://user-images.githubusercontent.com/47602733/140102654-376687b0-7327-4368-b19b-658c29eb07fb.png)

The PEN/Integrations is not detected or loaded 
![image](https://user-images.githubusercontent.com/47602733/140096640-0be1fafc-c93b-4c78-9fac-855af36e6292.png)
![image](https://user-images.githubusercontent.com/47602733/140096709-759ddb8a-144f-41d0-8ada-cdc78c9554b2.png)

Can you please help me in order to try solve this issue? 

Thank you 

### URL

https://www.home-assistant.io/integrations/zha/

### Version

core-2021.10.7

**Comment by Adminiuga** [comment]
This is not a support forum. Try Zigbee channel on HA Discord server

**Comment by MiAutomations** [comment]
> server

Thank you for your reply can you please let me know the  link for this support forum? 

By the way I think this is a issue ... Sorry for the post.

Thank you and best regards
