### ISSUE TITLE
Automation with trigger id used in actions

### ISSUE THREAD

**Issue by sirKitKat** [home-assistant/home-assistant.github.io#20142]
### Feedback

On this [trigger page](https://www.home-assistant.io/docs/automation/trigger/)   it states you can assign id's to triggers that are then referenced by conditions or actions but no example was found on how to implement this

### URL

https://www.home-assistant.io/docs/automation/action/

### Version

2021.11.0

**Comment by frenck** [comment]
Using IDs with triggers is documented on the triggers page:

<https://www.home-assistant.io/docs/automation/trigger/#trigger-id>

Using them in conditions is documented in the conditions page:

<https://www.home-assistant.io/docs/scripts/conditions/#trigger-condition>
