### ISSUE TITLE
Counter docs issue

### ISSUE THREAD

**Issue by piotrtobolski** [home-assistant/home-assistant.github.io#20154]
### Feedback

I think there is issue in the counter documentation. It states that:
> If restore is set to false, the initial value will only be used when no previous state is found or when the counter is reset.

I think it should be:
>If restore is set to **true**, the initial value will only be used when no previous state is found or when the counter is reset.

In the current form it doesn't make sense in combination with previous paragraph

### URL

https://www.home-assistant.io/integrations/counter/

### Version

2021.11.0

**Comment by frenck** [comment]
Thanks, @piotrtobolski 👍 

Opened up a PR to address the statement.

Happy New Year 🍾
