### ISSUE TITLE
Unclear Instructions on automatically added devices / entities

### ISSUE THREAD

**Issue by T1ppes** [home-assistant/home-assistant.github.io#20159]
### Feedback

The Fritz Box Integration provides device tracker entities for devices connected to the network by creating a Home Assistant Device including a device tracke entity. By default it seems that new devices are being created in Home Assistant, but the device tracker entity is being disabled by default.

The integration provides a system option to "enable newly added entities".
Further it is saying that newly discovered devices for AVM FRITZ!Box Tools should be automatically added.

I have this option enabled and see the above described behaviour (i.e. devices are added automatically, the entities are all disabled by default). The aim of this option to me is unclear as it is talking about entities in the first line and devices in the second line.

The documentation of the integration does not help to understand the intended behaviour. Under Device Tracker two notes can be found. Note 1 states that all device trackers added will always be disabled and need to be enabled manually.
Note 2 states that the system option needs to be disabled, if new devices should not be tracked automatically. 
The word tracked to me means that the device tracker entity is enabled, but if Note 1 is true, these entities will never be enabled automatically, regardless of the setting.

I am in favor of an option to automatically enable the device tracker entity of newly added devices.
It seems that this integration does not support this at the moment, but from the documentation this is not clear to me.

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2021.11.1

**Comment by chemelli74** [comment]
Current system option (`entry.pref_disable_new_entities`) is not built to avoid adding all entities to the registry; instead is meant to avoid adding the entities to the state machine (this means that entities are still created but disabled).

More details @ https://github.com/home-assistant/core/pull/56740#discussion_r718912465

Simone

**Comment by T1ppes** [comment]
If I understand you correctly, the intended behavior of that switch in other words is, 
* if enabled, disabled entities are created for all newly added devices
* if disabled, no entities are created for newly added devices.
Can you please confirm or correct my statement?
Further, there is currently no option to automatically add enabled device tracker entities, ever since the integration moved to a UI setup, neither is this option currently being developed. Is this also correct?
Because in my use case this would be very helpful, as I am tracking the presence of guests with home assistant.
