### ISSUE TITLE
SONOS integration, services

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#20158]
### Feedback

The SONOS Integration documentation page shows several services such as " SONOS.RESTORE". 
On the Home Assistant integration page the SONOS integration shows 4 devices, 4 entities but does not mention any services. 

On the other hand the integraton "Speedtest" shows 1 service and 3 entities. 

Question: Why is the amount of SONOS services not show on the integration page? 
What services are shown on the integration page.  

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2021.11.1

**Comment by jjlawren** [comment]
Those are the services you can call from scripts or automations. You can review them at `Developer Tools > Services`.
