### ISSUE TITLE
Diwscard my last edit

### ISSUE THREAD

**Issue by smarthomejunkie** [home-assistant/home-assistant.github.io#20151]
### Feedback

Hi, 
You can discard my last edit of the documentation. It doesn't solve the whole problem.

Sorry,
Ed

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.0

**Comment by frenck** [comment]
I don't see an last edit?

![image](https://user-images.githubusercontent.com/195327/140515355-9d4c6358-e62c-4792-b87c-5c39361d2895.png)

<https://github.com/home-assistant/home-assistant.io/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Asmarthomejunkie>
