### ISSUE TITLE
Ezviz's account has not entities. 

### ISSUE THREAD

**Issue by panisin000** [home-assistant/home-assistant.github.io#20156]
### Feedback

Ezviz's account has not entities. 
Can not stream video to home assistant.
But the older version is useable.

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.10.6

**Comment by farmio** [comment]
Hi 👋!

It seems like you want to report a bug with an Home Assistant integration, but this repository is for documentation feedback only.
Please report issues with Home Assistant integrations at https://github.com/home-assistant/core/issues

Thanks! 👍
