### ISSUE TITLE
Smarthings security

### ISSUE THREAD

**Issue by msmith9xr4** [home-assistant/home-assistant.github.io#20157]
### Feedback

Is there a way to determine Smarthings IPs for firewallingt? It seems absurd to open a HASS to the internet when you can just buy a  <$99 box to bridge to a HASS from within your network. 

But, for some locations a firewall rule would be enough, allowing Samsung Sthings ranges to an exposed 443 public. Also one less point of failure. Today, this gets done with vera/smarthings boxes (wink until recently). 

Any thoughts? 

### URL

https://www.home-assistant.io/integrations/smartthings/

### Version

2021.11.0

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
