### ISSUE TITLE
Per capita option in statistics world map

### ISSUE THREAD

**Issue by raderarn** [home-assistant/home-assistant.github.io#20160]
### Feedback

I think it would be great to see installations per capita as well as in exact numbers. In the active installations and version history there is a checkbox for logaritmic scale. A checkbox in world map "show per capita" would be a nice thing.

### URL

https://analytics.home-assistant.io/

### Version

2021.11.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
