### ISSUE TITLE
Gas Detector

### ISSUE THREAD

**Issue by grzestel** [home-assistant/home-assistant.github.io#20163]
### Feedback

unsupported  GAS and CO detector can u add this device ?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.1

### Additional information

Device Information
Product Name
燃气一氧化碳复合报警器
Device ID
201814225002916b2128
Product Category
dgnbj
Device Status
Online
Activated At
2020-12-10 16:50:18
Device Association
Project
HomeAssistant
Association
grzestel@gmail.com
Data Center
Central Europe Data Center
Extension Information
Sub-Device or Not
No

![image](https://user-images.githubusercontent.com/73305177/140510179-8bef7c2a-fc13-468b-8ebd-7d103fd47d73.png)

Standard Instruction SetStandard Status Set
Code
Type
Values
self_checking	Boolean	
"{true,false}"
checking_result	Enum	
{
  "range": [
    "checking",
    "check_success",
    "check_failure",
    "others"
  ]
}
preheat	Boolean	
"{true,false}"
muffling	Boolean	
"{true,false}"
gas_sensor_state	Enum	
{
  "range": [
    "alarm",
    "normal"
  ]
}
gas_sensor_value	Integer	
{
  "unit": "",
  "min": 0,
  "max": 10000,
  "scale": 1,
  "step": 1
}
alarm_state	Enum	
{
  "range": [
    "alarm_sound",
    "alarm_light",
    "alarm_sound_light",
    "normal"
  ]
}
co_state	Enum	
{
  "range": [
    "alarm",
    "normal"
  ]
}
co_value	Integer	
{
  "min": 0,
  "max": 1000,
  "scale": 1,
  "step": 1
}

![image](https://user-images.githubusercontent.com/73305177/140510405-c512d13b-fccd-40fb-9650-e49eb823a451.png)
![image](https://user-images.githubusercontent.com/73305177/140510448-d255be14-72bd-46c4-9036-d9f20ae181d6.png)
![image](https://user-images.githubusercontent.com/73305177/140510596-387c8dfc-aa4d-41a3-ba9b-7e8b46c2a6bf.png)
![image](https://user-images.githubusercontent.com/73305177/140510630-12ee78ff-5173-4ee3-a677-843d9c3bae3b.png)

**Comment by frenck** [comment]
Hi there @grzestel 👋 

I think you are in the wrong place, as you have submitted documentation feedback.
Please see http://www.home-assistant.io/help on where to go with these requests.

Thanks! 👍 

../Frenck
