### ISSUE TITLE
Homekit "User input malformed" error message

### ISSUE THREAD

**Issue by mike1627** [home-assistant/home-assistant.github.io#20167]
### Feedback

After upgrading Home Assistant to 2021.11.x, HomeKit now reports an error "User input malformed" error message when trying to add/remove entities from the configuration.  I have deleted the integration and then re-created it, this temporarily resolved the issue but the problem unexpectedly came back.  The logs do not report any relevant errors.

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2021.11.1

### Additional information

<img width="594" alt="Screen Shot 2021-11-04 at 10 36 58 PM" src="https://user-images.githubusercontent.com/70400778/140556094-d4d12d7a-aac2-474d-b637-d52db1b06ccf.png">

**Comment by Talor-A** [comment]
+1, I'm also seeing the same error on the adaptive lighting integration (issue is being tracked [here](https://github.com/basnijholt/adaptive-lighting/issues/213))

**Comment by Daneish** [comment]
While it seems 2021.11.3 fixed this error for some other integrations, I’m still seeing this error with HomeKit on core-2021.11.3 (supervisor-2021.10.8, Home Assistant OS 6.6). It still occurs after rebooting the host and in both the web interface and iPadOS app (v2021.11.1).

**Comment by bdraco** [comment]
This was fix in home-assistant/core#60061 but not released yet.  2021.12
