### ISSUE TITLE
SimpliSafe documentation is unclear on 2021.11.0 Core

### ISSUE THREAD

**Issue by sbcrumb** [home-assistant/home-assistant.github.io#20165]
### The problem

Upgraded to new Core version today and my SimpliSafe integration that was working stopped working. I would try to use the authcode and it would say invalid. 
I rolled back and did a restore to core-2021.10.6, and I was able to re-verify and get it working with no issues.

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What was the last working version of Home Assistant Core?

2021.10.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

SimpliSafe

**Comment by shemeel** [comment]
I don't have 2FA set but the above method is working for me.
