### ISSUE TITLE
offset understanding

### ISSUE THREAD

**Issue by mrnegpants** [home-assistant/home-assistant.github.io#20173]
### Feedback

your examples shows an offset but not explanation what does a negative offset do ? is before or after the event ?

### URL

https://www.home-assistant.io/integrations/sun/

### Version

2021.11.1

**Comment by frenck** [comment]
negative time means before the event, positive time after the event.
The offset is added to the event time.

**Comment by mrnegpants** [comment]
Please look at the page you just sent a link to. it does not explain the
offset. I am sure you know what it does, but others do not.


Frank

**Comment by frenck** [comment]
I am sorry, I don't think it needs further explanation. 

Feel free to suggest an edit of the page in a PR
