### ISSUE TITLE
Efergy Sensor Consumption Breakout 

### ISSUE THREAD

**Issue by rodders99** [home-assistant/home-assistant.github.io#20175]
### Feedback

I have multiple sensor with my efergy setup. One monitoring the whole house, one measuring the EV Charger.

However,there appears to only be one consumption total. 

Is there any way of splitting out the separate sensor consumption figures ?

### URL

https://www.home-assistant.io/integrations/efergy/

### Version

2021.11.1

### Additional information

![image](https://user-images.githubusercontent.com/16765672/140609056-b80f601c-08f7-4f86-9634-12ced259d7bd.png)

![image](https://user-images.githubusercontent.com/16765672/140609070-2d2abc09-11cb-4f4e-92f3-af7889701a25.png)

**Comment by tkdrob** [comment]
You have 2 sensors. The screenshot shows 3 consumption totals: one for the whole system and the other two are for each sensor.

**Comment by rodders99** [comment]
Thanks for responding. 

Those are power readings for each sensor, not consumptions readings. The sensor doesn't increase during the day, it's recording the load at that moment in time. 

While I can use the [Reimann Sum ](https://www.home-assistant.io/integrations/integration/) integration platform to sort of overcome the limitation, it would be nice if we could access each sensor separately. 

I appreciate this may not be possible and is subject to the Efergy API limitations.

**Comment by tkdrob** [comment]
Here is the documentation: http://napi.hbcontent.com/document/index.php

I will look into it but can't promise anything.

**Comment by rodders99** [comment]
Thanks, I'll have a look at it.
