### ISSUE TITLE
device class: tamper

### ISSUE THREAD

**Issue by sevorl** [home-assistant/home-assistant.github.io#20183]
### Feedback

device class: tamper seems to be no longer supported.

### URL

https://www.home-assistant.io/integrations/binary_sensor/

### Version

2021.11.1

**Comment by ludeeus** [comment]
It is <https://github.com/home-assistant/core/blob/dev/homeassistant/components/binary_sensor/__init__.py#L98-L99>, <https://github.com/home-assistant/core/blob/dev/homeassistant/components/binary_sensor/__init__.py#L134>
