### ISSUE TITLE
Add link to info on packages

### ISSUE THREAD

**Issue by jofotoo** [home-assistant/home-assistant.github.io#20181]
### Feedback

I suggest adding a link to [packages](https://www.home-assistant.io/docs/configuration/packages/) from this page.  I think that many people looking to break up their config file would want to organize the files by integration/concept/etc, so you can add and remove them all in one shot when adding/removing the related integration (for ex, alexa, fordpass, garbage collection). I spent a lot of time staring at the "splitting" page trying to figure out how to get automations, scripts, and other types of configs into multiple files, trying to understand which would be best, and then figuring out it's not possible because you can't define 'automations' in more than one place with this method. 

Packages offered exactly what I wanted to do, but was not highlighted or promoted in the docs, so I only came across it after googling and finding it in a reddit or HA forum post. 

Thanks for your consideration!

### URL

https://www.home-assistant.io/docs/configuration/splitting_configuration/

### Version

2021.11.1

**Comment by frenck** [comment]
Feel free to suggest an edit to do that! 👍
