### ISSUE TITLE
Smartplug power monitor is not updated

### ISSUE THREAD

**Issue by robi59italy** [home-assistant/home-assistant.github.io#20182]
### Feedback

Teckin SP21 smart plug with power monitor
In the past connected to home assistant vers. 9.7 with localtuya - working perfectly

Now with Tuya integration HA 2021.11.1
at the first installation, HA shows the right power,current,ect. but they are never updating. The entities show the first numbers...

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.1

**Comment by frenck** [comment]
This is not something we can do anything about. We receive updates pushed from Tuya. If they don't push data, data won't be updated.

Please contact Tuya support about this.
