### ISSUE TITLE
Solaredge integration has unavailable enitites after Hassio core update to core-2021.11.1

### ISSUE THREAD

**Issue by gody01** [home-assistant/home-assistant.github.io#20198]
### Feedback

Hi,

After core update to 2021.11.1 solaredge integration show most sensors as unavailable. 
Only current_power and lifetime_energy are working normaly.

Unavailable sensor.se_go_energy_this_year SolarEdge Integration
Unavailable sensor.se_go_energy_this_month SolarEdge Integration
Unavailable sensor.se_go_energy_today SolarEdge Integration
Unavailable sensor.se_go_site_details SolarEdge Integration
Unavailable sensor.se_go_meters SolarEdge Integration
Unavailable sensor.se_go_sensors SolarEdge Integration
Unavailable sensor.se_go_gateways SolarEdge Integration
Unavailable sensor.se_go_batteries SolarEdge Integration
Unavailable sensor.se_go_inverters SolarEdge Integration
Unavailable sensor.se_go_power_consumption SolarEdge Integration
Unavailable sensor.se_go_solar_power SolarEdge Integration
Unavailable sensor.se_go_grid_power SolarEdge Integration
Unavailable sensor.se_go_storage_power SolarEdge Integration
Unavailable sensor.se_go_imported_energy SolarEdge Integration
Unavailable sensor.se_go_production_energy SolarEdge Integration
Unavailable sensor.se_go_consumption_energy SolarEdge Integration
Unavailable sensor.se_go_selfconsumption_energy SolarEdge Integration
Unavailable sensor.se_go_exported_energy SolarEdge Integration
Unavailable sensor.se_go_storage_level SolarEdge Integration

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2021.11.1

### Additional information

If I can provide any additional info, please let me know. Can also create additional user on monitoring portal for testing.

**Comment by purcell-lab** [comment]
> After core update to 2021.11.1 solaredge integration show most sensors as unavailable. Only current_power and lifetime_energy are working normaly.

Have a look at this article here to assist:
https://community.home-assistant.io/t/solaredge-energy-module/327131/37

**Comment by frenck** [comment]
> After core update to 2021.11.1 solaredge integration show most sensors as unavailable.

Please, read the release notes. We put a lot of effort into those to help you with these things.

<https://www.home-assistant.io/blog/2021/11/03/release-202111/#breaking-changes>

![image](https://user-images.githubusercontent.com/195327/140900623-0c76a3d5-fa4c-4d60-b347-1a24fff1769c.png)

**Comment by gody01** [comment]
Thanks,

I was confused, as most entities become disabled. Now I enabled them and are visible again.

**Comment by frenck** [comment]
👍  As described :)
