### ISSUE TITLE
Missing Configuration Information

### ISSUE THREAD

**Issue by wperry1** [home-assistant/home-assistant.github.io#20199]
### Feedback

The basic configuration information for the Pi-Hole is missing from this page. There also appears to be no information on how to provide an API key so that the Pi-Hole can be controlled.

### URL

https://www.home-assistant.io/integrations/pi_hole/

### Version

2021.11.1

**Comment by frenck** [comment]
Its right in the middle of the page?

![image](https://user-images.githubusercontent.com/195327/140916177-d75a8bd3-b30d-4625-90fc-835fb83b6c75.png)

**Comment by wperry1** [comment]
I apologize if this is not the place to put this. I've never actually had someone respond to a feedback button on a website before. When I went through the GUI to configure my pi-hole I did not see an option to add my API key so I was looking to add it to my configuration.yaml. The YAML config is listed for the pi-hole disable service but the basic YAML config is missing.

**Comment by frenck** [comment]
There is no YAML configuration for this integration.

**Comment by SnowViet** [comment]
I have the same problem, there is no option for the API key ont the configuration screen:
![image](https://user-images.githubusercontent.com/28396654/142609617-4c06479d-f54b-4e03-96d4-99b46d409a69.png)

**Comment by frenck** [comment]
It will ask that in the next step... @SnowViet

**Comment by SnowViet** [comment]
Not in my case.... @frenck 

The next step is the room selection (see screenshot).
And obviously it's the last step, and I can't put my API key...
![image](https://user-images.githubusercontent.com/28396654/142630554-e7560156-e2a5-48d5-928f-2a1d4c70690b.png)

**Comment by frenck** [comment]
You have checked statistics only:

![image](https://user-images.githubusercontent.com/195327/142865825-7661a6ed-e3af-4b9a-b60f-e907e75362ad.png)


Which doesn't require an API key, thus it does not ask for it...
