### ISSUE TITLE
Graph units

### ISSUE THREAD

**Issue by lukerix** [home-assistant/home-assistant.github.io#20193]
### Feedback

Hi there,
The graph is shown in basic units, but it would be nice to be able to set it to show with a multiply.
A example is in the additional information.

Regards,
lukerix

### URL

https://www.home-assistant.io/lovelace/statistics-graph/

### Version

2021.11.1

### Additional information

A atmospheric presure sensor (in "hPa") is shown in "Pa". So the graph instead oscillating around 1013hPa is oscillating around 101300Pa it is not intuitive to view.

![Screenshot_20211107_130353](https://user-images.githubusercontent.com/93864731/140644119-468d4ade-8583-4143-bd0c-9cf1367fcb25.jpg)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
