### ISSUE TITLE
Unclear documentation on packages

### ISSUE THREAD

**Issue by eitau** [home-assistant/home-assistant.github.io#20197]
### Feedback

I just can't quite parse this paragraph:
> Packages are configured under the core `homeassistant/packages` in the configuration and take the format of a package name (no spaces, all lower case) followed by a dictionary with the package configuration. For example, package `pack_1` would be created as:
> \<example follows\>

What's <q>core `homeassistant/packages` </q>? It refers to a part of software? From later reading i infer it's a directory. It's unusual wording considering the rest of the documentation.

Secondly: the example given here is not in right form to be placed in `packages` directory but rather in main `configuration.yaml` file.

### URL

https://www.home-assistant.io/docs/configuration/packages/

### Version

2021.11.1

**Comment by tgallacher** [comment]
> Packages are configured under the core homeassistant/packages in the configuration and take the format of a package name (no spaces, all lower case) followed by a dictionary with the package configuration [...]

I would read this as suggesting something along the lines of:

Packages are configured  via a "packages" key living under the core "homeassistant" key within the `configurations.yaml` file. Each individual package is created using further child keys (e.g. yaml dictionary) where each key below this "packages" node denotes the name of the package; Each package name should be all lowercase with no spaces. For example, the following would create a single package with a name of "`pack_1`": 

```yaml
# configurations.yaml

homeassistant:
  packages:
    pack_1: 
       ...
```

I think there is a more succinct way to say this, but it would assume more familiarity with YAML from the audience, which I think the docs tend to caution as not being the case to ensure wider accessibility.
