### ISSUE TITLE
Upgrade HomeAssistant to Python3.9

### ISSUE THREAD

**Issue by claasse4** [home-assistant/home-assistant.github.io#20192]
### Feedback

Please update the Windows (WSL) instructions to work on Python 3.9 (3.8 warned for deletion per Feb. 22).

### URL

https://www.home-assistant.io/help/

### Version

2021.11.1

**Comment by frenck** [comment]
fixed in #20525

**Comment by claasse4** [comment]
Appreciated :-). Will again try to setup on ReadyNas ..
Thnx, Coen
