### ISSUE TITLE
SimpliSafe Web api authentication

### ISSUE THREAD

**Issue by subarunut333** [home-assistant/home-assistant.github.io#20208]
### Feedback

Trying to re-authorize my HomeAssistant with my SimpliSafe and following the directions on both my windows laptop's as well as my android phone, I am unable to get past the text code.  The browser window just stops.  It appears that it is using the iOS auth page.  I this correct?  Should I be trying on my iOS device instead?

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2021.11.1

**Comment by bachya** [comment]
Duplicate of https://github.com/home-assistant/home-assistant.io/pull/20164.
