### ISSUE TITLE
Tentando novamente a configuração: [Errno 111] Connect call failed ('192.168.0.98', 5577)

### ISSUE THREAD

**Issue by ClausCaus** [home-assistant/home-assistant.github.io#20207]
### Feedback

Hello,

Can you help and insert on documentation what is the meaning of the error codes?

Tks!

### URL

https://www.home-assistant.io/integrations/flux_led/

### Version

2021.11.1

**Comment by frenck** [comment]
> `Connect call failed`

I'm not sure how more clear it could be?
