### ISSUE TITLE
Add linked devices and group retrieval

### ISSUE THREAD

**Issue by akloeckner** [home-assistant/home-assistant.github.io#20206]
### Feedback

The rest interface also supports linking it to an existing number on signal. So, this should be lined out in the docs. The current docs suggest you need a free phone number to use this integration.

Also, notifying a group has a few pitfalls that should be clarified:
1. In order to see any group, the receive command has to be issued. (https://github.com/AsamK/signal-cli/issues/82) 
2. This has to be done after the group was created. So, probably we should suggest to use the auto-receive parameter?
3. The group id is the actual `group_id` and not the internal id. That should also be clarified.

### URL

https://www.home-assistant.io/integrations/signal_messenger/

### Version

2021.11.1

**Comment by akloeckner** [comment]
:-) @bbernhard, I avoided to open the issue in your repo, as I wasn't sure of the owner of the HA docs. I hope, it'll find its way to you anyways.

**Comment by bbernhard** [comment]
Thanks for the feedback!

regarding 1. & 2.: Please have a look at the new [JSON-RPC Mode](https://github.com/bbernhard/signal-cli-rest-api#modes). This mode works way faster than the normal/native mode and doesn't have the issues you've mentioned above. 

regarding the documentation: I can try to make the documentation more clear, but especially for the documentation I highly appreciate input (in form of pull requests) from users. Documenting stuff is always hard and its even harder when you want to document the stuff you've written yourself ;-). So, if you feel like that something could be improved/clarified, please feel free to create a PR here (or in the `signal-cli-rest-api` repo). Many thanks!

**Comment by akloeckner** [comment]
> regarding 1. & 2.: Please have a look at the new [JSON-RPC Mode](https://github.com/bbernhard/signal-cli-rest-api#modes). This mode works way faster than the normal/native mode and doesn't have the issues you've mentioned above.

So, this mode auto-receives? Or how does it circumvent the issue in the underlying `signal-cli`? I'll try the new mode at least to gain some speed. Thanks for the hint!
 
> I highly appreciate input (in form of pull requests) from users. 

Alright! I'll try and contribute to your repo then probably, because the setup is described there.

**Comment by bbernhard** [comment]
> > regarding 1. & 2.: Please have a look at the new [JSON-RPC Mode](https://github.com/bbernhard/signal-cli-rest-api#modes). This mode works way faster than the normal/native mode and doesn't have the issues you've mentioned above.
> 
> So, this mode auto-receives? Or how does it circumvent the issue in the underlying `signal-cli`? I'll try the new mode at least to gain some speed. Thanks for the hint!
> 
> > I highly appreciate input (in form of pull requests) from users.
> 
> Alright! I'll try and contribute to your repo then probably, because the setup is described there.

In normal/native mode, we are invoking the `signal-cli` binary (with the appropriate parameters) for every REST request. In JSON-RPC mode a `signal-cli` instance per registered number is started in daemon mode, which listens for incoming/outgoing requests. That means that we do not need to periodically call the `receive` endpoint anymore, but instead `signal-cli` tells us when a new message is received. That change is also reflected in the REST API. In normal/native mode, the `receive` endpoint is a `GET` request, in JSON-RPC mode its a websocket connection. 

Thanks A LOT for the PR - very nice!

**Comment by akloeckner** [comment]
Ah ok. I think, I get the idea. Thanks.

I'll close the issue, as it's adressed now in your repo.
