### ISSUE TITLE
Remove [orphan] entities

### ISSUE THREAD

**Issue by jd1900** [home-assistant/home-assistant.github.io#20205]
### Feedback

There is no way to remove entities.

I don't know how, but the addon "restarted", and all of the renamed entites became orphan.
And newly created entities with names from 1 to n were created.

Orphan entities don't work anymore, but I can't delete them.

### URL

https://www.home-assistant.io/integrations/homekit_controller/

### Version

2021.11.1

**Comment by Jc2k** [comment]
Hi - this is the place for documentation issues not bugs in home assistant or user support.

You'll need to raise an issue here:

https://github.com/home-assistant/core

Please make sure to include details of what hardware you are using as it might be the root of the problem. E.g. I use Hue with homekit and they (hue) recently changed the serial numbers of all my devices and did exact same thing to me. I ended up unpairing and repairing to get it sorted.

Also in your new issue tell us - have you ever run any beta releases?
