### ISSUE TITLE
What is scan_interval

### ISSUE THREAD

**Issue by landaisbenj** [home-assistant/home-assistant.github.io#20216]
### Feedback

In rest integration, scan_interval is not documented. What is the default value ? Is it 60 ?

### URL

https://www.home-assistant.io/integrations/rest/

### Version

2021.11.1

### Additional information

Documentation referer to rest sensor of binary sensor, but here's no info on scan_interval too

**Comment by frenck** [comment]
Scan interval is a generic platform option, documented here: <https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval>
