### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by jespermeyer** [home-assistant/home-assistant.github.io#20229]
### Feedback

The top link / URL to https://github.com/ciotlosm/lovelace-thermostat-dark-card/tree/master/group-card doesn't work. 

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2021.11.2

**Comment by ludeeus** [comment]
Where did you find that link?
It is not anywhere in the documentation source

**Comment by jespermeyer** [comment]
HI, 

Please see attachment, the URL is marked with the red circle

![image](https://user-images.githubusercontent.com/4678618/140903840-460e56c4-9a4f-4814-9996-ee2fd4633813.png)

**Comment by ludeeus** [comment]
That is not a part of this documentation, please add a comment in that thread on the forum :+1:
