### ISSUE TITLE
heating_type is not optional anymore

### ISSUE THREAD

**Issue by LucVanDyck** [home-assistant/home-assistant.github.io#20244]
### Feedback

In the description of this integration is mentioned that the configuration variable _**heating_type**_ is optional. This is no longer correct. My log shows this error: "Invalid config for [vicare]: value must be one of ['auto', 'fuelcell', 'gas', 'heatpump', 'oil', 'pellets'] for dictionary value @ data['vicare']['heating_type']. Got None. (See /config/configuration.yaml, line 65). Please check the docs at https://www.home-assistant.io/integrations/vicare".

Furthermore, the possible values for heating_type seems to have changed from generic, gas, heatpump or fuelcell to 'auto', 'fuelcell', 'gas', 'heatpump', 'oil', 'pellets'.

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2021.11.2

**Comment by oischinger** [comment]
thanks for the info.
this should be irrelevant with the upcoming vicare config flow https://github.com/home-assistant/home-assistant.io/pull/20403
