### ISSUE TITLE
is there any way to rotate the image

### ISSUE THREAD

**Issue by markrharvey** [home-assistant/home-assistant.github.io#20252]
### Feedback

i would like to rotate the image so that it is horizontal rather than verticle is there any way i could do thi

### URL

https://www.home-assistant.io/lovelace/picture-elements/

### Version

2021.11.2

**Comment by frenck** [comment]
> i would like to rotate the image so that it is horizontal rather than verticle is there any way i could do thi

There is no functionality to do that. Instead, rotate the actual source image before using it.
