### ISSUE TITLE
Integration Documentation Lacking

### ISSUE THREAD

**Issue by TechBrain64** [home-assistant/home-assistant.github.io#20250]
### Feedback

It would be helpful if there were examples accompanied with this integration. Actually, I've been looking up documentation on several integrations and the examples are lacking adequate details for understanding their use.

FYI: You cannot expect someone with no understanding of a program to document it's use.

### URL

https://www.home-assistant.io/integrations/number/

### Version

2021.11.2

**Comment by frenck** [comment]
This is an integration component, it cannot be used directly, it is provided by other integrations.

Looking at the documentation, it isn't clear from the description, so that should be added.

**Comment by TechBrain64** [comment]
@frenck I believe it's understood "number" is a variable and used to hold a value, however, how does one go about using this variable is in question.

**Comment by frenck** [comment]
It is not a variable, it is an entity. An entity that can be provided by other integrations. For example:

The WLED integration provides a number entity (shown as slider) to set the speed of the effect on the LED strip:

![image](https://user-images.githubusercontent.com/195327/141185561-6660889b-9cc7-4915-9fb9-d22628a28496.png)

So, number entities (like light, switch, fan, climate, ... entities) are provided by other integrations and can be used to control a device.

**Comment by TechBrain64** [comment]
So then I (a user) cannot use the "number" entity in a custom sensor, script, automation...etc?

**Comment by frenck** [comment]
The user version of such a thing would be Input Number (aka a Number helper):

<https://www.home-assistant.io/integrations/input_number/>

**Comment by TechBrain64** [comment]
Got It....then yes, you are correct in stating the "number" entity doc needs to clearly indicate it's purpose. 

BTW: the reason I'm looking into this, i'm trying to figure out how i can calculate a value (cost) based on whether a value is above or below another entity, then executes a mathematical formula where results are assigned to entity.

**Comment by frenck** [comment]
Your description sounds more like a templated sensor?

**Comment by TechBrain64** [comment]
Yes, that's what I've chosen to use, but I'm having difficulty figuring out the syntax that will bring it all together. I've search to forums, youtube and online; most are using it with devices comparing/manipulating attributes. I need to use state values (input_number) greater than/less than state of another input number.

Hence, my comment about the examples lacking adequate details.
