### ISSUE TITLE
Stookalert intergration not in current homeassitant?

### ISSUE THREAD

**Issue by Xaos1990** [home-assistant/home-assistant.github.io#20261]
### Feedback

RIVM Stookalert intergration is not showing up in integrations page on homeassitant core-2021.10.2. 

### URL

https://www.home-assistant.io/integrations/stookalert/

### Version

2021.10.2

**Comment by frenck** [comment]
It has been added to the UI in Home Assistant Core 2021.11. Please upgrade your instance.
