### ISSUE TITLE
placing of additions to yaml files

### ISSUE THREAD

**Issue by dirksenrdh** [home-assistant/home-assistant.github.io#20268]
### Feedback

in many cases the HA documentation advises to make changes in configuration, boot, script or yaml files.
sometimes thes additions can be placed anywhere, but I can imagine that some additions are place sensitive.
It would be helpfull to always give a reference as where to place an addition.

### URL

https://www.home-assistant.io/integrations/python_script/

### Version

2021.11.2

**Comment by frenck** [comment]
> but I can imagine that some additions are place sensitive.

Not really?

**Comment by dirksenrdh** [comment]
ok,
that makes life easy.
thnx
