### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by smarthomeproxy** [home-assistant/home-assistant.github.io#20276]
### Feedback

`FULL CONFIGURATION FOR 2.XX INSTALLATIONS`

Has the sample config:
influxdb:
  api_version: 2
  **ssl: false**

Why is ssl set to false in the sample config?

### URL

https://www.home-assistant.io/integrations/influxdb/

### Version

2021.11.2

**Comment by mdegat01** [comment]
Because it is showing an example configuration if someone had deployed InfluxDB locally, just like the 1.xx one above. When deploying services locally that are only accessible within their network people usually don't use SSL since they don't want to mess with self-signed certificates.

**Comment by mdegat01** [comment]
Also `ssl` is `true` by default there wouldn't be any point in including `ssl: true` in the example, you would just omit `ssl`. With the examples I thought generally it was good to pick something realistic that leverages as many of the configuration options as possible, hence I picked non-ssl local.
