### ISSUE TITLE
Tuya "integration" impossible if user only has a phone

### ISSUE THREAD

**Issue by GNious** [home-assistant/home-assistant.github.io#20283]
### Feedback

Following the process for Tuya integration fails if user only has a phone (e.g. on the step of scanning the barcode with that phone, but also repeatedly earlier due to issues with the Tuya website)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.3

**Comment by buczoprazy** [comment]
I do not see any flag next to the integration, which one require internet connection. I understand all integrations (the reason why we using HA) work offline, except google assistant, Alexa etc.? 

```
The Tuya integration integrates all Powered by Tuya devices you have added to the Tuya Smart and Tuya Smart Life apps. Tuya officially maintains this integration.

All Home Assistant platforms are supported by the Tuya integration, except the lock and remote platform.
```

**Comment by smithbill17** [comment]
Very similar to issue #19640
