### ISSUE TITLE
Power Not Yielding Expected Behavioir

### ISSUE THREAD

**Issue by Tylast** [home-assistant/home-assistant.github.io#20293]
### Feedback

"Leave out to keep the power as it is."  

I have no power elements in my commands in Node Red, yet when triggered - my lights always come on.  They should retain the current power state.

### URL

https://www.home-assistant.io/integrations/lifx/

### Version

2021.11.3

**Comment by frenck** [comment]
I'm not sure what the documentation feedback is you are giving in your message, could you please clarify?
