### ISSUE TITLE
Github link no longer valid

### ISSUE THREAD

**Issue by stirls1** [home-assistant/home-assistant.github.io#20302]
### Feedback

Hi,  https://github.com/home-assistant/operating-system/releases/download/6.6/haos_rpi4-64-6.6.img.xz doesn't work any more - it gives a 'needs authorisation' error and then fails.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.11.3

**Comment by frenck** [comment]
see #20303
