### ISSUE TITLE
Honeywell TCC

### ISSUE THREAD

**Issue by Phrede** [home-assistant/home-assistant.github.io#20301]
### Feedback

Include in the instructions........If coming from a previous (depreciated) version where the User and Password were under climate-platform-honeywell you must delete and reinstall the integration itself.  This lets you set the user and password

I wonder where the credentials are now stored and where to set the polling interval.

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.11.3

**Comment by rdfurman** [comment]
Not sure what you're looking for here. 

Passwords work the same for honeywell now as they do for most other integrations. If you changed your password in honeywell TCC you will need to remove and re-add the integration, but this has nothing to do with migrating from the old version of the honeywell integration.

Please see this page for onboarding integrations via the user interface: https://www.home-assistant.io/getting-started/onboarding/
