### ISSUE TITLE
Update existing entities with resolvenames

### ISSUE THREAD

**Issue by hieblmedia** [home-assistant/home-assistant.github.io#20313]
### Feedback

Hello,
would be nice if there is a function to trigger resolvenames for all entities without has an name yet.

The problem is, if are new devices in the CCU and not instaltly changed the name, HomeAssistant does not regognice it and i have to change the name and also the entity-id anyways.

Only way i see is to shutdown HomeAssistant before pairing and renaming all new devices.

### URL

https://www.home-assistant.io/integrations/homematic/

### Version

2021.11.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
