### ISSUE TITLE
Use an entity tracking the total costs

### ISSUE THREAD

**Issue by jasontucker** [home-assistant/home-assistant.github.io#20315]
### Feedback

I'm unable to select an entity to track costs even though it's available. I'm using an Eagle-200

More info here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

<img width="730" alt="Screen Shot 2021-11-14 at 1 15 28 PM" src="https://user-images.githubusercontent.com/108426/141698908-2a235fa4-6eca-4e80-a8fe-4fb029f128b3.png">

### URL

https://www.home-assistant.io/integrations/rainforest_eagle/

### Version

2021.11.3

**Comment by jasontucker** [comment]
I'm attempting to use this as values for the Energy intregration new to HA

**Comment by frenck** [comment]
Hi there @jasontucker 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
