### ISSUE TITLE
Windows supports Docker containers

### ISSUE THREAD

**Issue by strarsis** [home-assistant/home-assistant.github.io#20316]
### Feedback

Windows 10+ supports Docker Linux containers, Docker for Desktop implements this very nicely now.
However, the documentation currently doesn't reflect this: home Assistant Container is not listed as an option for Windows and not further hints or instructions for installing the prerequisites for Docker Linux containers on Windows are given.

### URL

https://www.home-assistant.io/installation/

### Version

2021.11.3

### Additional information

[Docker for Desktop](https://docs.docker.com/desktop/)

**Comment by frenck** [comment]
It is not listed as an option, because it is not supported. Docker on Windows behaves a bit different in the networking department, making it unsuitable.
