### ISSUE TITLE
Not working with QTS 5

### ISSUE THREAD

**Issue by danieldur** [home-assistant/home-assistant.github.io#20326]
### Feedback

After upgrading my QNAP TS-231P to QTS 5 the HA integration doesn't seem to be working anymore.
Is this something specific to me or a general issue? 

### URL

https://www.home-assistant.io/integrations/qnap/

### Version

2021.11.4

**Comment by colinodell** [comment]
Hi @danieldur,

It's highly likely that the underlying [qnapstats library](https://github.com/colinodell/python-qnapstats) does not support QTS 5.  I would recommend submitting an issue over there.  When submitting that issue, it would be extremely helpful if you could provide any error messages that you see in HA.  Additionally, if you have some Python experience and would be able to run the `debug.py` script from that repository that would also provide additional data needed to confirm whether this is a compatibility issue.

**Comment by danieldur** [comment]
Before I open an issue for qnapstats, here are some logs I get inside HA (maybe it helps):


Logger: homeassistant.components.qnap.sensor
Source: components/qnap/sensor.py:296
Integration: qnap (documentation, issues)
First occurred: 22:22:39 (3 occurrences)
Last logged: 22:23:50

Failed to fetch QNAP stats from the NAS
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/qnap/sensor.py", line 296, in update
    self.data["system_stats"] = self._api.get_system_stats()
  File "/usr/local/lib/python3.9/site-packages/qnapstats/qnap_stats.py", line 217, in get_system_stats
    resp = self._get_url(
  File "/usr/local/lib/python3.9/site-packages/qnapstats/qnap_stats.py", line 76, in _get_url
    result = self._execute_get_url(url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/qnapstats/qnap_stats.py", line 89, in _execute_get_url
    self._debuglog("Appending access_token (SID: " + self._sid + ") to url")
TypeError: can only concatenate str (not "NoneType") to str

**Comment by colinodell** [comment]
Thanks for that info!  Based on this, it does appear that the issue is _probably_ coming from `qnapstats`.  The only way to know for sure would be to run that `debug.py` script I mentioned earlier and see if you get the same error.

**Comment by danieldur** [comment]
Sadly, when running debug.py (like described here https://www.home-assistant.io/integrations/debugpy/ ), the web interface becomes totally inaccessible. I was lucky that the SMB interface was still up so I reverted back the change in configuration.yaml and brutally restarted the raspberry.

**Comment by colinodell** [comment]
I recommend closing this in favor of https://github.com/home-assistant/core/issues/61789, which is the same issue (but recorded against the HA codebase repo)
