### ISSUE TITLE
"wait template" or "wait for a template" 

### ISSUE THREAD

**Issue by DJF3** [home-assistant/home-assistant.github.io#20327]
### Feedback

On [this page](https://www.home-assistant.io/docs/scripts/#wait-template) I see "WAIT TEMPLATE"

In the HA scripting/automation GUI it says "Wait for a template"

Searching for "Wait for a template" gives you 0 results (HA site, HA community, Duckduckgo, google)

So either the GUI should be updated or the documentation? 
I think that initially the docs should reflect what the GUI shows.

### URL

https://www.home-assistant.io/docs/scripts/

### Version

2021.11.4

**Comment by frenck** [comment]
At this point, the UI script wording has been changed in a recent version, and does not match the documentation anymore indeed.

The UI change was made by de frontend team to add clarity between wait template, wait for action and delay.

Feel free to open up a PR to adjust that! 👍
