### ISSUE TITLE
Total Consumption Query

### ISSUE THREAD

**Issue by JayMcG** [home-assistant/home-assistant.github.io#20336]
### Feedback

Hi there! 

I am using two Efergy sensors in my house. The one is measuring electricity consumption from grid import and the other from my solar generation. Unfortunately, the Efergy integration only shows a single total sensor combining the two Efergy consumption sensors. 

Example:

Grid import = 1kWh for the day
Solar generations = 15kWh for the day

Efergy sensor "Total Grid Consumption" = 16kWh. 

Is there a way to split these values? 

Thanks in advance!

### URL

https://www.home-assistant.io/integrations/efergy/

### Version

2021.11.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
