### ISSUE TITLE
Documentation does not match what I received

### ISSUE THREAD

**Issue by iamaddman** [home-assistant/home-assistant.github.io#20335]
### Feedback

For this section:

>Look for a reference to a URL that starts with com.simplisafe.mobile:// and note the code at the end: com.simplisafe.mobile://auth.simplisafe.com/ios/com.simplisafe.mobile/callback?code=\<CODE\>

When I run through the steps I get the following URL: `https://tsv.prd.platform.simplisafe.com/v1/tsv/confirm?code=`

When I paste the code at the end of this URL into the screen in Home Assistant I get an invalid authentication error and therefore cannot get my Simplisafe integration to work anymore.

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2021.11.4

**Comment by bachya** [comment]
The https://tsv.prd.platform.simplisafe.com URL is not the one to use. Are you following the [instructions](https://www.home-assistant.io/integrations/simplisafe/#getting-an-authorization-code) for your particular browser?

**Comment by iamaddman** [comment]
Thanks!! That worked I missed the browser portion of the instructions.
