### ISSUE TITLE
Apple TV does not connect

### ISSUE THREAD

**Issue by HershyReis** [home-assistant/home-assistant.github.io#20334]
### Feedback

The configuration for this device is incomplete. Please try adding it again.

This is the error that i get. Can anyone help me out please.

Thanks.

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2021.11.4

### Additional information

The configuration for this device is incomplete. Please try adding it again.

This is the error that i get. Can anyone help me out please.

Thanks.

**Comment by frenck** [comment]
Hi there @HershyReis 👋 

I think you meant to report an issue, however, you have submitted documentation feedback instead.

You issue is probably related to this issue report:

<https://github.com/home-assistant/core/issues/51649>

../Frenck
