### ISSUE TITLE
ISY integration not receiving data for z-wave sensors

### ISSUE THREAD

**Issue by kentcalero** [home-assistant/home-assistant.github.io#2034]
This may just be affecting non-binary sensors such as humidity, temperature, etc.

**Comment by fabaff** [comment]
This is the issue tracker for the documentation. Please use https://github.com/home-assistant/home-assistant/issues.

**Comment by robbiet480** [comment]
This issue should be opened in the primary [Home Assistant repository](https://github.com/home-assistant/home-assistant/issues/new), not this one (docs repo).
