### ISSUE TITLE
Missing information which integration work offline

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#20340]
### Feedback

How to list integrations which can work offline please?

### URL

https://www.home-assistant.io/integrations#all

### Version

N/A

**Comment by ghost** [comment]
Any update on this please? Or should I assume that all integrations work offline, except those with clear notice on integration website?

**Comment by frenck** [comment]
All integrations show this on their page:

![image](https://user-images.githubusercontent.com/195327/143774784-ef415d8c-adda-4699-8a15-60e334a64e1b.png)


For example, the Hue integration has the local push IoT class, while, Spotify is listed as Cloud polling:

![image](https://user-images.githubusercontent.com/195327/143774867-ff80c1ac-4ce6-456b-b57e-eefcae4df3a2.png)

The definitions are linked on each of the pages, in case you are in need for more clarity on what that means.

**Comment by ghost** [comment]
Thank you for your comment, I appreciate your help.

Could you also advise what if there is no clear info is it cloud or loca but instead auto discover like here please:

https://www.home-assistant.io/integrations/verisure/

**Comment by frenck** [comment]
That integration has clear info on that? It states cloud polling?

**Comment by ghost** [comment]
Yes, I found it thank you. So if my devices work only offline, then most of the integrations will do not work on HA? Am I right please?

**Comment by buczoprazy** [comment]
I have just found 'Classifying the Internet of Things' is there any tag where I can sort by classifying? the key for automation should be thetime of reaction and privacy. so ot means Home Assistant is useless shit, pretending to be for home automation.

**Comment by ghost** [comment]
> All integrations show this on their page:
> 
> ![image](https://user-images.githubusercontent.com/195327/143774784-ef415d8c-adda-4699-8a15-60e334a64e1b.png)
> 
> For example, the Hue integration has the local push IoT class, while, Spotify is listed as Cloud polling:
> 
> ![image](https://user-images.githubusercontent.com/195327/143774867-ff80c1ac-4ce6-456b-b57e-eefcae4df3a2.png)
> 
> The definitions are linked on each of the pages, in case you are in need for more clarity on what that means.

But how to list only local integrations please? I can not imagine that I have to open one by one integration to check if it is real home automation which work offlina or a toy for kids if the integration getting data from the cloud please.

**Comment by ghost** [comment]
Imagine that you have ring door integration and internet went offline. What then?

**Comment by ghost** [comment]
Is it home automation or cloud devices automation?

**Comment by frenck** [comment]
> Imagine that you have ring door integration and internet went offline. What then?

Then the ring doorbell is offline, as it is a cloud polling integration:

![image](https://user-images.githubusercontent.com/195327/151885753-7a81f513-2dd0-49ff-94f0-b89c0964b62b.png)

> Is it home automation or cloud devices automation?

The automation is running locally in Home Assistant, however, if you have a device that can only be communicated to via the cloud, then well, you'll need an active internet connection. If you don't like that, you'd need to take that into account when buying products. We don't control how Ring works; Home Assistant can only use what has been made available by manufacturers.

In this case, Doorbird (as one of the examples) could have been a local alternative instead.

**Comment by wilfreddijksman** [comment]
@buczoprazy you can find more information about the differenced IoT classes and there meaning at https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/#classifiers
