### ISSUE TITLE
Only loading single device

### ISSUE THREAD

**Issue by andyloree** [home-assistant/home-assistant.github.io#20352]
### Feedback

I have two devices (wave radon and mini), and only the one device is appearing during setup to be pulled into HA.  Below shows call using same client_id the results from postman for /devices, which lists all of the devices:

![2021-11-18 17_38_35-Postman](https://user-images.githubusercontent.com/6370905/142508212-a5fd79c1-33b1-48f8-b8f0-9ab7106de573.png)

### URL

https://www.home-assistant.io/integrations/airthings/

### Version

2021.11.4

**Comment by frenck** [comment]
Hi there @andyloree 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
