### ISSUE TITLE
Problem with Aqara lumi.light.aqcn02

### ISSUE THREAD

**Issue by antomprev** [home-assistant/home-assistant.github.io#20368]
### Feedback

Been using Zigbee lumi.light.aqcn02 with a conbee2 and everything was working fine. After some updates in HA (practically over the last 3months - i waited for this to be repaired with some update) when the relevant switch is se to ff (or when I put my shelly to off in some other switches) the bulb goes unavailable. When I turn the switch to on again, it won't re-pair. Practically it goes dead after electricity has been cut and won't re-pair as it did so far.
Any ideas?

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2021.11.4

**Comment by Adminiuga** [comment]
This is wrong repo and does not provide support for device issues
