### ISSUE TITLE
Package name exception for Raspberry Pi OS

### ISSUE THREAD

**Issue by AirVince** [home-assistant/home-assistant.github.io#20366]
### Feedback

It seems that when installing the dependencies needed for Home Assistant, libturbojpeg shoudl be libturbojpeg-dev when installing on Rasberry PI OS. This should be called out. 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.11.4

**Comment by frenck** [comment]
Package names can differ depending on the operating system used. Installing Home Assistant Core directly in your own Python environment is an advanced installation method. We expect users that use these methods to be familiar with system administration, and being able to set up and maintain their system and Python environments; and thus being able to adapt it to their setup.

If this is not the case, we recommend using a different installation method.
