### ISSUE TITLE
problem to cast spotify on chromecast with this integration

### ISSUE THREAD

**Issue by bosjp** [home-assistant/home-assistant.github.io#20365]
### Feedback

error log 👍 
Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:333
Integration: Google Cast (documentation, issues)
First occurred: 4:53:28 PM (1 occurrences)
Last logged: 4:53:28 PM

Failed to cast media https://open.spotify.com/playlist/65CSGK9uC8Th2kFOdEIyED?si=7f87727799db48ab. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address

the link is working on a browser

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2021.11.4

**Comment by frenck** [comment]
Hi there @bosjp 👋 

It seems like you want to report an issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by bosjp** [comment]
thanks
appologies ...
