### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by quasimodo1427** [home-assistant/home-assistant.github.io#20362]
### Feedback

We need an update on the Home Assistant forum. The DTE integration not working

### URL

https://www.home-assistant.io/integrations/dte_energy_bridge/

### Version

2021.11.4

**Comment by frenck** [comment]
Hi there @quasimodo1427 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations in the Core issue tracker:

<https://github.com/home-assistant/core/issues>


Thanks! 👍 

../Frenck
