### ISSUE TITLE
Tasmota Status Sensors

### ISSUE THREAD

**Issue by MikeNesbitt** [home-assistant/home-assistant.github.io#20373]
### Feedback

The documentation says that"Please note all the Status Sensors are disabled by default." How can I enable some of them?

### URL

https://www.home-assistant.io/integrations/tasmota/

### Version

2021.11.5

**Comment by frenck** [comment]
By clicking on them and toggle the "Enable entity" switch.

**Comment by heisenberg2980** [comment]
@frenck @emontnemery is there any reason for the status sensors to be disabled by default? I keep enable them for each of my tasmota devices, but I would like to know if there is a good reason for them to be disabled

**Comment by frenck** [comment]
There are multiple reasons to do so:
For example, sensors we know are lesser used by people, but update frequently, are good candidates to disable by default

**Comment by heisenberg2980** [comment]
Ok, I am not sure about other sensors, but at least the IP address of the device is really useful and it rarely changes, so it might be a good candidate to be removed from the "disable by default" list (similar for the firmware version sensor)

**Comment by frenck** [comment]
🤷‍♂️ 

I'm not sure what that has to do with documentation feedback though...

**Comment by heisenberg2980** [comment]
Nothing at all, the documentation is correct, I was just wondering if there was any reason for these sensors (i.e. IP address or firmware version) to be disabled by default, but if there isn´t any I might open an issue to change that (before opening a new issue I always try to understand if there is a reason to be that way).

**Comment by frenck** [comment]
It's not an issue, there is no hard rule if they should or should not be enabled/disabled by default. We recommend disabling less common sensors that update frequently. However, that is a recommendation as best. We do ensure the disabling of high-frequency updating sensors, that are non-primary. 

In the end, it is up to the user which ones they enable or disable.

**Comment by heisenberg2980** [comment]
I understand that. I am in the process of migrating all my tasmota devices from MQTT integration to Tasmota integration, and it is a bit painful having to enable the same 5 sensors that are disabled by default for every single device. I agree that the high-frequency-low-used sensors are disable by default, but I think the IP address and firmware version should be enable by default.

Anyway this migration is not something that you do every day, so I guess it is not a big deal.
