### ISSUE TITLE
Dyson is requiring 2-step-signin i think.

### ISSUE THREAD

**Issue by lishan89uc** [home-assistant/home-assistant.github.io#20377]
### Feedback

When ever I sign in on the app it is asking for a code that is emailed to me. I can't find a way to turn that off. I think that is related to what is making this not connecting.

```
Logger: homeassistant.components.dyson
Source: components/dyson/__init__.py:60
Integration: dyson (documentation, issues)
First occurred: 6:47:08 AM (1 occurrences)
Last logged: 6:47:08 AM

Not connected to Dyson account. Unable to add devices
```

### URL

https://www.home-assistant.io/integrations/dyson/

### Version

2021.11.5

**Comment by frenck** [comment]
There are actually more issues with this integration, which has been unresolved for a long time. Therefore this integration is being removed in the next release of Home Assistant Core.
