### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by kifort** [home-assistant/home-assistant.github.io#20375]
### Feedback

I missing an info about the
- current version
- latest version
- current configuration (site ID and API key)
as well as the possibility to
- update the current version to the latest one
- change the configuration (site ID and API key)
If they are already possible, then I am missing its documentation.

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2021.11.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests. These are actually all feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by kifort** [comment]
Thank you @frenck for taking care of this ticket, and sorry to open it in the wrong place. I moved to https://community.home-assistant.io/t/solaredge-integration-update/359266. I hope, it is the right one.
