### ISSUE TITLE
Source selection missing after update core to 2021.11.4

### ISSUE THREAD

**Issue by Nummer17** [home-assistant/home-assistant.github.io#20384]
### Feedback

With core-2021.10.7

![image](https://user-images.githubusercontent.com/91088185/142759705-9aee0377-adb3-4e46-80f6-77fe74dfa38b.png)

With core-2021.11.4

![image](https://user-images.githubusercontent.com/91088185/142759646-ed21ab61-0ef9-474a-a558-a4145583a78b.png)

When i downgrade to 2021.10.7 the souce select is back.
ha core update --version=2021.10.7

### URL

https://www.home-assistant.io/integrations/denonavr/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @Nummer17 👋 

It seems like you want to report an issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
