### ISSUE TITLE
More problems with Sensors

### ISSUE THREAD

**Issue by DravenSA** [home-assistant/home-assistant.github.io#20388]
### Feedback

So if the printer is currently "Offline" and then switched on, the Status changes correctly but not the temperature sensors. I have complained about them reading in the Gauge card as Errors, but that wont get fixed after the last email i received, however the fact that you have to "reload" the integration to get it to read the temperatures is most annoying.

Also the Start time and Finish time Unless you start your print in Octo Print, this helps nothing as both of those will remain as "Unknown" for the duration of the print.

If like me, you sprint straight from the SD card (this is so I can uses the resume function should there be a power failure, and living in South Africa this a regular occurrence)  I only use Octoprint to purely keep an eye on the printer via the camera, and a few other sensors like percentage done and the temperatures of both bed and nozzle, Sensors like Print time elapsed and Tring time remaining are most valuable. I know Home assistant would rather not have the "per Second" update, but at least every 60 seconds or even every 5 minutes would be far more beneficial that "Unknown"

### URL

https://www.home-assistant.io/integrations/octoprint/

### Version

2021.11.5

**Comment by rfleming71** [comment]
The print from SD card should be fixed via this PR https://github.com/home-assistant/core/pull/59663

The temperature sensors coming back online with the printer should be address via. https://github.com/home-assistant/core/pull/59666

**Comment by DravenSA** [comment]
Start time and Finish time Unknown when printing from SD card

The temperature sensors coming back online with the printer should be 
address via. home-assistant/core#59666 
<https://github.com/home-assistant/core/pull/59666>

Does this mean it is still coming?

**Comment by frenck** [comment]
Hi there @DravenSA 👋

It seems like you want to report an issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead. If you want to report an issue with an integration, please raise one here:

https://github.com/home-assistant/core/issues

Thanks! 👍

../Frenck
