### ISSUE TITLE
IoT Core API authorisation expires after 1 month of use. 

### ISSUE THREAD

**Issue by moyuehan** [home-assistant/home-assistant.github.io#20387]
### Feedback

All API show a trial period of one year in  Tuya IoT development Platform Cloud Development for my project, all except one : IoT Core. IoT Core shows a trial period of 1 month. Is it possible to add in the documentation what and when to do any actions to assure continuation of the Tuya V2 integration use in Home Assistant ?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.5

**Comment by smithbill17** [comment]
I just logged into my Tuya IoT account and observed that my 'IoT Core' service had a validity period of 12months. I thought I would try clicking the 'Update Edition' button to see what would happen - I added 'IoT Core' to my basket at $0 and bought it. Now I find that it's changed the validity period of my 'IoT Core' service to be just 1 month! Where have my missing 11months gone!?

It's unacceptable that Home Assistant users of this dreadful integration have to login to the Tuya IoT portal every month just to renew the 'IoT Core' service. All of these 'services' need to have the validity period removed and operate 'in perpetuity' or until the Tuya IoT account is closed.

**Comment by frenck** [comment]
I believe you can extend it in increments of 6 months now. That said, that is not a Home Assistant thing, you might want to ask Tuya about that instead.

**Comment by smithbill17** [comment]
No, doesn't appear to be a 6month option (see attached image taken just now). It's 1month only unless you have $000's to waste on Tuya.
![Screenshot_2021-12-07-07-40-11-762_com android chrome](https://user-images.githubusercontent.com/66825587/144987496-a391a09d-b946-41c3-ae5b-2be8ea369046.jpg)

**Comment by frenck** [comment]
> I believe you can extend it in increments of 6 months now.

I'm pretty sure there is an option somewhere to extend that, however, that said, this is not Home Assistant, but the Tuya platform. Those questions are better asked @ Tuya.

**Comment by moyuehan** [comment]
@Frenck : you are right ; in the application for extension, there is a selection at the top, giving a maximum extension period of 6 months.  Thanks for the information.
