### ISSUE TITLE
Roomba is not updating after cleaning

### ISSUE THREAD

**Issue by hansencorrien** [home-assistant/home-assistant.github.io#20381]
### Feedback

When I start my Roomba it is doing its job. However, when the job is done and the Roomba is docked it is not updating to HA (battery level, charging etc.). It is also not possible to start Roomba again. After reloading the integration it works again fine (for just 1 cleaning operation). Also, after a restart of HA I have to reload the integration before it works properly.
This issue came up after the last update.

### URL

https://www.home-assistant.io/integrations/roomba/

### Version

2021.11.5

**Comment by pschmitt** [comment]
Seems like a duplicate of https://github.com/home-assistant/core/issues/59855#event-5648065145

Fixed by https://github.com/home-assistant/core/pull/60008 btw
