### ISSUE TITLE
Hue Color Chart article not available

### ISSUE THREAD

**Issue by michal-bartak** [home-assistant/home-assistant.github.io#20390]
### Feedback

Hue Color Chart referenced as part of description of xy_color (Light documentation) points to philips pages, requiring log in with own development account.
I suppose the access to the link had not been restricted before, and has changed recently
Obviously docs should not point to pages which requires login.

### URL

https://www.home-assistant.io/integrations/light/

### Version

2021.11.5

**Comment by michal-bartak** [comment]
Issues don't resolve theirselves just by closing them.

Reasoning in automatic message is also off.

No, the documentation hasn't been fixed

**Comment by dannytsang** [comment]
@michalk-k do you know of an alternative site that is not behind a log-in with the same/similar information?

**Comment by michal-bartak** [comment]
Hello,
I don't know how originally  linked diagram looked like. So hard to say what is expected. Google search returns lot of them.

**Comment by michal-bartak** [comment]
Still not fixed

**Comment by michal-bartak** [comment]
Still not fixed.

**Comment by michal-bartak** [comment]
Still not fixed.
