### ISSUE TITLE
Front End toggle switches not holding correct state

### ISSUE THREAD

**Issue by DravenSA** [home-assistant/home-assistant.github.io#20397]
### Feedback

on all my tuya devices if i toggle a light on, the light goes on, but the front end switch toggles off again. the light remains on , so the only way to switch it off is to quickly double click it to make it toggle on and off fast.
I have set up "Device Status Notification" and it was working fine with 2021.11.2  but since  2021.11.3 until now 2021.11.5 it has reverted back to a behaviour like it was if you didnt set up "Device Status Notification"

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.5

**Comment by sjefke09** [comment]
Having the same problem here. It also happens the other way around (state in HA is on, while the light is off).
Sometimes the state works, sometimes it doesn't and sometimes it works after a larger period of time.
I also have a Tuya wall switch (LSP-KG1). This switch seems to have more problems than the smart light bulbs.

**Comment by M1118** [comment]
Also having the same problem.

**Comment by lverlaek** [comment]
Yes, i'm also having this problem.

**Comment by frenck** [comment]
>  Very bad for the wife-approval-factor here..

Please avoid the "WAF" term. It can be offensive to some people. Thanks 👍

**Comment by frenck** [comment]
Hi there @DravenSA 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Please be sure to search if your issues has been reported already, before creating a new one.

Thanks! 👍 

../Frenck
