### ISSUE TITLE
Switchbot integration failure 

### ISSUE THREAD

**Issue by kksligh** [home-assistant/home-assistant.github.io#20396]
### Feedback

My switchbot integration suddenly stopped working. I deleted it and have attempted to re-install several times and get this error every time I try "Aborted. Failed to connect".  Can someone please help. 

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @kksligh 👋 

It seems like you want to report an issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
