### ISSUE TITLE
Documentation does not mention you need to be server owner/admin

### ISSUE THREAD

**Issue by mattiaskagstrom** [home-assistant/home-assistant.github.io#20393]
### Feedback

Adding the plex integration and logging in as a normal user gets you to the next step where you get to chose a server if you have multiple. It then just errors out with a error of "server did not accept token"

After some trial and error i found out that you had to log in as a server administrator. This is not mentioned in the documentation as a prerequisite. 

### URL

https://www.home-assistant.io/integrations/plex/

### Version

2021.11.5

**Comment by jjlawren** [comment]
@mattiaskagstrom would you mind updating the docs to reflect this?

**Comment by frenck** [comment]
Opened PR here: #20526
