### ISSUE TITLE
Ability to see Shopping List items in an entity to cycle through them

### ISSUE THREAD

**Issue by cbhiii** [home-assistant/home-assistant.github.io#20402]
### Feedback

I am looking for a way to cycle through the Shopping List items listed to be able to check for duplicates before I add a new item with the list.

I don't see that there is any entity that could show me this information. It's possible I'm missing it.

Is there a way to provide a list using an entity with attributes? I do not see one if this is already something that exists.

I only discovered the list yesterday after becoming frustrated with external offerings. Its simplicity in its current form is an asset.

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2021.11.5

**Comment by adumicic** [comment]
I’m looking for something similar. I’m wanting to be able to see how many items are in the list to know whether to trigger an automation or not. I haven’t seen a way to examine the list though. If it’s not there, it would be great to add it.

**Comment by frenck** [comment]
This is currently not possible. 

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
