### ISSUE TITLE
Installation guide for Core with many errors on RPI4

### ISSUE THREAD

**Issue by jlssmt** [home-assistant/home-assistant.github.io#20405]
### Feedback

IMHO:
The instructions to install Home Assistant Core on the RaspberryPi4 are unfortunately insufficient.
I get a lot of errors.
For one thing, sqlite3 is missing: https://community.home-assistant.io/t/error-after-installing/21651
On the other hand pip can't find the Rust compiler: https://community.home-assistant.io/t/cannot-update-to-2021-10-0/344695

After I had to reinstall Python3.8 several times (e.g. because of sqlite --enable-loadable-sqlite-extensions), I see that Python3.8 will soon be unsupported. However, Python3.10 had not worked during the installation either.

What is the recommended installation on a RaspberryPi 4 if I don't want to use the image because I want to run other things on my Pi. Docker? Does Docker have all the features the core has?
https://community.home-assistant.io/t/what-features-are-core-users-missing/202509

Furthermore, I have seen that no Linux service is installed. I'll have to take care of that, too.
And the zigbee addon does not work with a fresh install: `Config flow could not be loaded.` I think it's a broken installation.

I find Home Assistant extremely difficult to get started with due to the inadequate installation instructions. The rest of HomeAssistant's documentation seems to be of a much higher standard which I really like.
I have experience with iobroker and there the installation is a single command and I don't have to deal with dependencies: 
`curl -sLf https://iobroker.net/install.sh | bash -`
I'm considering switching to HomeAssistant, but that's unfortunately how I feel for now.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.11.5

**Comment by jlssmt** [comment]
@frenck @ludeeus 
thanks for updating the installation guide.
but I miss the info what is the recommended solution to install HA, if you dont want to use HassOS.

furthermore: isn't it possible to include every dependency that is necessary, if you run a clean raspbian bullseye OS? at least sqlite and rust is missing in default installation guide. and maybe a zigbee bug (see above).

**Comment by frenck** [comment]
> if you dont want to use HassOS. 

See our installation page for other installation method available.

Dependencies and requested packages differ per installation method. For example, I personally prefer And use pyenv, on plain Debian and use a different structure.

The main story: it depends on your distribution used, the version of the distribution used and how you manage and install Python.

As written in the guide and made extra clear now, we expect you can adopt to that, if not, this installation method might not be your cup of tea.

**Comment by jlssmt** [comment]
@frenck 
Thanks for your reply. I know the other installation methods.

Do you understand my intention why I wrote this issue?
We have a OS, that is used by many raspberrypi owners. It's officially and called RaspberryPi OS (earlier Raspbian).
We have a Installation guide for Core on RaspberryPi.
Why is this installation guide not complete and matched for the most used and officially supported RaspberryPi OS (buster and bullseye)? We know, what comes with the OS and what dependency needs to be installed.
I would understand, if it's a guide for Debian, or Linux. But it's for **RaspberryPi**. And it's for all that want to install it on a custom OS. My programming knowledge in python is not far and I'm not expert in linux but I can handle to configure, run and develop a lot of linux software. Except HASS.

I can't manage HASS Core to run on a fresh and clean RaspberryPi OS Bullseye image with this installation guide.
I installed rust manually, i installed sqlite3 manually, i installed python3.9 manually, ... all without notice in the installation guide. and I think I'm not alone, if I see the error reports in HASS forum (I gave examples in my issue description).
Zigbee plugin gives me errors and HASS is not writing any database entries (has to do with sqlite).

**Comment by frenck** [comment]
> Do you understand my intention why I wrote this issue?

Yes. We have updated the documentation to clarify one needs to be able to adopt it to their needs and environment.

> We have a OS, that is used by many raspberrypi owners.

That is great! Many also don't use it (e.g., pi-clones or other single board computers). Anyways, the point remains the same.

> I can't manage HASS Core to run on a fresh and clean RaspberryPi OS Bullseye image with this installation guide.

Then maybe you should consider using one of the other installation methods provided; those might be a better fit for you in that case.
