### ISSUE TITLE
Does not work with IPv6

### ISSUE THREAD

**Issue by JeroenTuinstra** [home-assistant/home-assistant.github.io#20409]
### Feedback

This integration does not work with IPv6 - when IPv6 is enabled on the host (in case of docker or VM) then you cannot authenticate. It will come back with an error "Unknown Error Occurred". No further details in the log.

Found this threat where the solution is effectively disabling IPv6 [https://community.home-assistant.io/t/unknown-error-occurred-when-trying-to-add-apple-icloud-integration/331886]

Its the first integration that I come across that is incompatible with IPv6. Don't know if it is an issue with Apple or HA. 

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @JeroenTuinstra 👋 

It seems like you want to report a possible issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
