### ISSUE TITLE
Connection Errors - At Auth Stage

### ISSUE THREAD

**Issue by joe-raschke** [home-assistant/home-assistant.github.io#20415]
### Feedback

One improvement would be that if you have your device/controller behind a firewall, and don't want to punch a hole in the firewall, be sure to add the integration from the publically available cloud source; and to use that URL to add the integration.  I would get errors if I used homeassistant.local:8123 or the 192.x.y.z:8123.  In my case once I used my Nabu site, all works smoothly.  (with the  the multiple home work around) --Joe

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.11.5

**Comment by allenporter** [comment]
You don't need to do anything with a firewall.

Google doesn't talk to home assistant, just your browser does.

The rules are subtle and hard to explain so `2021.12` has a new nest auth stack that doesn't use urls at all, so consider this obsolete in the next release.
