### ISSUE TITLE
Dsmr integration

### ISSUE THREAD

**Issue by dirksenrdh** [home-assistant/home-assistant.github.io#20429]
### Feedback

If I read the documentation about integrating a P1 meter I get the impression that I need extra hardware like the SlimmeLezer+. However if I install the DSMR integration I get a serial option and if I connect a P1 > usb cable I can choose that option. 
I think the documentation should be extended with the usb option. 

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.11.5

**Comment by frenck** [comment]
> However if I install the DSMR integration I get a serial option and if I connect a P1 > usb cable I can choose that option.

That is also hardware... It just as well contains chips to make a USB serial bridge.

Personally, I would not recommend that option :)

**Comment by terual** [comment]
> Personally, I would not recommend that option :)

Why not? I am just curious, because using a P1 USB cable works without a problem here.

**Comment by frenck** [comment]
Sure, but it requires you to have the machine running it directly next to your meter :)

Anyways, in triggered on:

> If I read the documentation about integrating a P1 meter I get the impression that I need extra hardware like the SlimmeLezer+. However if I install the DSMR integration I get a serial option and if I connect a P1 > usb cable I can choose that option.

Both cases are hardware, that cable isn't just cable...

**Comment by terual** [comment]
I agree though with the OP that the documentation is a bit unclear in this regard and steers heavily towards the SlimmeLezer+. It would be nice to also mention the (Slimme meter) P1-USB cable, such as https://www.robbshop.nl/slimme-meter-kabel-usb-p1-1-meter or https://www.sossolutions.nl/slimme-meter-kabel.

**Comment by frenck** [comment]
> steers heavily towards the SlimmeLezer+

Yes, as we consider that a more versatile solution and better solution. It's detected automatically and works. Regardless of your Home Assistant setup (e.g., no fiddling with VM serial forwarding, drivers, or mapping devices into Docker containers).

Additionally, it doesn't require hardware to be at the location of the meter and runs independently of the system.

You could solder a wire yourself, we don't list that either.

**Comment by terual** [comment]
I understand, and I agree that it is a far more versatile and user friendly solution. Although the USB solution also *just works* if you use Home Assistant OS (thanks for that!).

**Comment by frenck** [comment]
> Although the USB solution also just works if you use Home Assistant OS (thanks for that!).

Depends on how you use Home Assistant OS; that is the whole point :)
When using a VM, that will not be the case...

**Comment by dirksenrdh** [comment]
OK, Frenck,
What you say is correct, and I have a little tunnel vision.
1. A P1 => USB cable also is hardware and however the price is lower you need this hardware
but also this hardware works right out of the box.
2. Yes you ar right. the USB cable forces you to install "a machine" in the vincinity of the P1 meter
3. True the USB cable requires direct access to the hardware and if you run a VM that makes things extra complex
4. I have a raspberry tunnel vision. Everywhere I need "a machine" I throw in a Pi
5. and yes the SlimmeMeter+ might be more versatile. but if I have a Pi hanging next to my P1 meter, and I alredy have the USB cable (becasue I used to run Domoticz) I don't need versatility. I need to know that I also can use the USB cable. Therefore I find it unfair not to mention the USB option no matter your personal opinion on the "quality" of the USB solution.
therefore I agree with @terual that a link to other solutions would be beneficial and helpfull to other HA users even if you state next to the link that you think that a USB cable is a sub-optimal solution.

I really think that the HA documentation is outstanding. easy accessible, good searchable, many interlinks. and you invite readers to contribute to or comment on the documentation. but if you sabre every comment down like the discussion above, people are discouraged to comment. and that would be contra productive. Place yourself in the position of the HA user, the documentation should be also based on the users use cases and not only on your professional opinion however good your opinion is.

**Comment by frenck** [comment]
> but if you sabre every comment down like the discussion above,

I think that is rather an unfair comment; I've been clearly stating this was my opinion on the matter, which I am allowed to have as well. Additionally, no contribution has been made.

Because of your response, I'm no longer interested in discussing this with you. I'm not putting up a fight, I'm trying to add more context/views. If that isn't appreciated, I rather stop responding at all.

**Comment by dirksenrdh** [comment]
apparently we agree to disagree.
see you next time
