### ISSUE TITLE
UI Lovelace

### ISSUE THREAD

**Issue by ilmaino1984** [home-assistant/home-assistant.github.io#20420]
### Feedback

Hi, 
a lot of time the new integration doesn't recognize the change of state.
Maybe It's just my problem but it's annoying.
![Immagine 2021-11-24 094818](https://user-images.githubusercontent.com/58007629/143204903-8395d7d3-719b-4474-a371-eacd59e22f7a.png)

![Immagine 2021-11-24 094935](https://user-images.githubusercontent.com/58007629/143205292-3aeb9062-fbbe-4836-9c52-7448ae5b6f92.png)
In this case the "Monitor laterali" is on.

Any idea?

Thanks a lot

Kind regards

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.5

**Comment by lverlaek** [comment]
Probally the same as issue #20397

**Comment by frenck** [comment]
Closing as a duplicate. Additionally, you have submitted this as documentation feedback, which seems to be incorrect.

../Frenck
