### ISSUE TITLE
Cookie file does not provide session

### ISSUE THREAD

**Issue by tindall21047** [home-assistant/home-assistant.github.io#20434]
### Feedback

Followed steps using 'Export Cookies', maps.google.com redirects to www.google.com/maps, the cookies I download are:

.google.com	TRUE	/gmail	FALSE	1687969338	_ga	\<actual cookie redacted\>
.google.com	TRUE	/	TRUE	1652996971	NID  \<actual cookie redacted\>

Nothing in there about maps.google.com. Did something change on google side here?

In the 'Export Cookies' interface I clicked on 'google.com'. I also tried 'www.google.com', but no cookies were downloaded.

![image](https://user-images.githubusercontent.com/13722856/143321608-40e49027-5c3c-42ec-966f-74b7a6204636.png)

### URL

https://www.home-assistant.io/integrations/google_maps/

### Version

2021.11.5

### Additional information

Using whatever version the Docker command:
_FROM ghcr.io/home-assistant/home-assistant:stable_
gave me as of two days ago.

**Comment by genevera** [comment]
@tindall21047 You want to grab cookies from a session on maps.google.com, I think.
