### ISSUE TITLE
home assistance core install on pi fails

### ISSUE THREAD

**Issue by porrascarlos802018** [home-assistant/home-assistant.github.io#20436]
### Feedback

Install the dependencies:

sudo apt-get install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg tzdata

fails on my pi
pi@pi3b:~ $ sudo apt-get install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg tzdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libturbojpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libturbojpeg0

E: Package 'libturbojpeg' has no installation candidate

I installed python following these steps:
Installing python 3.8
https://itheo.tech/install-python-3-8-on-a-raspberry-pi/

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.11.5

**Comment by frenck** [comment]
> E: Package 'libturbojpeg' has no installation candidate

You need extra packages in your environment.

> However the following packages replace it:
> libturbojpeg0

👆
