### ISSUE TITLE
Additional documentation might be helpful.  Great integration, thanks for creating!!

### ISSUE THREAD

**Issue by BALSwim50W** [home-assistant/home-assistant.github.io#20437]
### Feedback

Requires Airthings hardware and Airthings login required.

Airthings API setup (needed to aquire required ID and Secret for the Home Assistant Airthings Integration)
1. Login to your airthings account
2. Select Integrations from the left side-bar ment (https://dashboard.airthings.com/integrations/api-integration)
3. Click on "Request API Client" in order to set up an api connection.
4. Name your api connection ie. "Home Assistant Integration"
5. Give the connection an accurate description.
6. Select a Resource Scope
7. Select an access Type ie. Confidential
8. Select a flow type
9. Set enable to "on"
10. Save the settings

Upon saving the settings, you will be presented with a generated id and secret.

On your Home Assistant Airthings Integration, you can now enter the generated API id and secret in order to connect Home Assistant to your Airthings API service.

### URL

https://www.home-assistant.io/integrations/airthings/

### Version

2021.11.5

**Comment by Danielhiversen** [comment]
Thanks.
Would be great if you want to add it to the documentation: https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/airthings.markdown

**Comment by BALSwim50W** [comment]
Thanks @Danielhiversen,
sorry for the delay.  I added the proposed documentation, hope it works out ok.  Thanks again for this integration, it's working out really well!

**Comment by Danielhiversen** [comment]
Awesome. Thanks.
Where is the pull request with the changes?

**Comment by BALSwim50W** [comment]
Hi Daniel,
My apologies again, appears that I didn't submit the docs changes properly.  I forked the home-assistant.io proj/repo again and applied the prior changes.  Here is a link to the PR. - https://github.com/home-assistant/home-assistant.io/pull/20531

Hope it helps out.
