### ISSUE TITLE
[BUG] WEBSITE Integration page not working

### ISSUE THREAD

**Issue by mishmanners** [home-assistant/home-assistant.github.io#20438]
### Feedback

The Integrations page is not working. There are no filter results being shown.

I have tested this on Chrome and Brave so far.

None of the filters work, and even if you click "all" the results are not being displayed, thus I can't see what integrations home assistant supports.

### URL

https://www.home-assistant.io/integrations/

### Additional information

Pages are blank:
![Blank page](https://user-images.githubusercontent.com/36594527/143387909-93698030-4a09-41c8-b4b3-7b17a6195f7e.JPG)

**Comment by ludeeus** [comment]
That page is generated with javascript, are you blocking that in your browser?
