### ISSUE TITLE
Changing DB entries while active HA service using it OK?

### ISSUE THREAD

**Issue by copykatze** [home-assistant/home-assistant.github.io#20440]
### Feedback

Hi, I just trimmed my db (strictly) using this instruction. After 
`sqlite> DELETE FROM states WHERE entity_id="sensor.cpu"; `
`sqlite> VACUUM;`
and exiting with .quit, the db was marked corrupt and a fresh one was created.

I was wondering the corruption might have been caused by the HA service using the db while I was making changes to it. Might be obvious to stop the service before this procedure, but maybe the instruction should mention it for noobs like me ;)

Maybe this is also completely unrelated, if the db should be able to handle the procedure while being accessed by HA service, then I suppose it is not worth looking deeper into it.

### URL

https://www.home-assistant.io/docs/backend/database/

### Version

2021.11.5

**Comment by frenck** [comment]
The database isn't meant to be consumed like that.

Use the services provided by the recorder instead: <https://www.home-assistant.io/integrations/recorder/#service-purge_entities>
