### ISSUE TITLE
Player list

### ISSUE THREAD

**Issue by mikixd586** [home-assistant/home-assistant.github.io#20441]
### Feedback

It would be nice if one of the sensors is a list of all players currently on the server.

### URL

https://www.home-assistant.io/integrations/minecraft_server/

### Version

2021.11.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
