### ISSUE TITLE
How to add few thermostats and keep settings after reboot?

### ISSUE THREAD

**Issue by harry2626** [home-assistant/home-assistant.github.io#20453]
### Feedback

Wish to have on this page explanation how to add more than one thermostat and have them set individually. Also would be helpful to find here solution for thermostat losing previous states after reboot. Thank you.

### URL

https://www.home-assistant.io/integrations/climate/

### Version

2021.11.5

**Comment by dannytsang** [comment]
@harry2626 do you have more than one thermostat integration configured and wish to add it to the lovelace dashboard or create a thermostat entity?
