### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by JeeWee65** [home-assistant/home-assistant.github.io#20456]
### Feedback

Since few days I added this integration. It is usefull but often does not refresh data or is unavailable. In my logs I often see the error  as mentioned in the subject.

See below for de logger info.

### URL

https://www.home-assistant.io/integrations/buienradar/

### Version

2021.11.5

### Additional information

Logger: homeassistant
Source: components/buienradar/util.py:147
First occurred: 20:02:40 (2 occurrences)
Last logged: 20:02:40

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/buienradar/util.py", line 147, in async_update
    result = parse_data(
  File "/usr/local/lib/python3.9/site-packages/buienradar/buienradar.py", line 37, in parse_data
    return parse_json_data(content, raincontent,
  File "/usr/local/lib/python3.9/site-packages/buienradar/buienradar_json.py", line 306, in parse_json_data
    data = __parse_precipfc_data(raincontent, timeframe)
  File "/usr/local/lib/python3.9/site-packages/buienradar/buienradar_json.py", line 574, in __parse_precipfc_data
    mmu = 10**(float((int(val) - 109)) / 32)
ValueError: invalid literal for int() with base 10: '105,8988795837422'

**Comment by ties** [comment]
Looks like an issue with the library @mjj4791 @RobBie1221?

**Comment by RobBie1221** [comment]
This is the issue tracker for documentation issues. There is an open issue and PR in HA core, and an issue and PR against library for the same issue. This issue is placed in the wrong repo and duplicate...

**Comment by JeeWee65** [comment]
> This is the issue tracker for documentation issues. There is an open issue and PR in HA core, and an issue and PR against library for the same issue. This issue is placed in the wrong repo and duplicate...

I'm sorry, was not clear for me, I opended the buienradar integration page and got an option to provide feedback. Maybe there should be a link to the right repo to report issues?  Where can I find the PR /repo you are talking about?

It looks like everybody thinks newbies know there way around as well as code owners etc. while it it more like a maze and I feel lost.

**Comment by RobBie1221** [comment]
https://www.home-assistant.io/help/reporting_issues/
