### ISSUE TITLE
Arlo and 2FA

### ISSUE THREAD

**Issue by paulot88** [home-assistant/home-assistant.github.io#20451]
### Feedback

I'm not able to configure this integration since Arlo requires 2FA. Any solution for this?

### URL

https://www.home-assistant.io/integrations/arlo/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @paulot88 👋 

Please follow this issue for progress on this:
<https://github.com/home-assistant/core/issues/39472>

../Frenck
