### ISSUE TITLE
Buienradar does not update its sensors

### ISSUE THREAD

**Issue by hansencorrien** [home-assistant/home-assistant.github.io#20454]
### Feedback

For the last few weeks I have the issue that buienradar does not update its sensor or freezes. When I restart Home Assistant it works for a few hours and then it happens again. Sometimes I have to restart HA 4-5 times a day

### URL

https://www.home-assistant.io/integrations/buienradar/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @hansencorrien 👋 

It sounds like you want to report an issue with an Home Assitant Core integration, however, you have submitted documentation feedback instead. Please report issues with an integration here:

<https://github.com/home-assistant/core/issues>

Please be sure to check and search if the issue isn't reported already.

Thanks!

../Frenck
