### ISSUE TITLE
Could use more info on how to resolve unhealthy due to supervisor not having privileged access to docker

### ISSUE THREAD

**Issue by pmichali** [home-assistant/home-assistant.github.io#20475]
### Feedback

The documentation would be more helpful if it indicated how to resolve the issue. It only mentions about HA OS being old, but in my case, I'm using HAOS agent and running HA in supervisor mode using docker containers (on Ubuntu). I inspected the supervisor container and it IS running in priviledged mode.

### URL

https://www.home-assistant.io/more-info/unsupported/privileged/

### Version

2021.11.5

**Comment by frenck** [comment]
`on Ubuntu`

Ubuntu is not supported. You won't be able to get a supported system on Ubuntu in any case. Please consult our installation documentation.
