### ISSUE TITLE
Instruction updates

### ISSUE THREAD

**Issue by dricair** [home-assistant/home-assistant.github.io#20477]
### Feedback

Hi

Following the installation guide, some parts are not up to date anymore:

- When installing debian packages, `libturbojpeg` does not exist anymore and has been replaced by `libturbojpeg0`
- It may be worth adding pointers for installing a Python3.8 version (Default version for Debian is 3.7). For example this page: https://linuxize.com/post/how-to-install-python-3-8-on-debian-10/

Regards
Cédric

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.11.5

**Comment by frenck** [comment]
It depends on the environment/distribution used.

This is considered (and described as) an advanced installation method, we expected people to be able to deal with the differences in their operating system of choice.
