### ISSUE TITLE
Suggestion for ease of learning

### ISSUE THREAD

**Issue by Tipalo** [home-assistant/home-assistant.github.io#20474]
### Feedback

Please provide an example picture in picture-glance setup that is located in a folder that exists.  I have tried several URLs to find my pictures but still unable to use the pictures I've placed in the /config/www/pics/ folder.  This would give us a foundation to build on.

### URL

https://www.home-assistant.io/lovelace/picture-glance/

### Version

2021.11.5

**Comment by frenck** [comment]
More information can be found here: <https://www.home-assistant.io/integrations/http/#hosting-files>

**Comment by Tipalo** [comment]
Thank you
