### ISSUE TITLE
smart curtain unspported

### ISSUE THREAD

**Issue by mohannadalsharief** [home-assistant/home-assistant.github.io#20476]
### Feedback

my smart curtain switch shows unsupported for some reason

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @mohannadalsharief 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please be sure to check https://www.home-assistant.io/help on where to go.

Thanks 👍 

../Frenck

**Comment by mohannadalsharief** [comment]
my bad
