### ISSUE TITLE
Not all (standard) events are documented

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/home-assistant.github.io#20483]
### Feedback

The developer tools inside Home Assistant show more events and not all are documented in the "Events" documentation,

e.g. user_removed, service_removed, homeassistant_close, homeassistant_stop, homeassistant_start and many more.

I could not find any documentation of most of them, besides some forum posts, so I think it would be good to add them here.

### URL

https://www.home-assistant.io/docs/configuration/events/

### Version

2021.11.5

**Comment by frenck** [comment]
`homeassistant_stop, homeassistant_start` are not complete, as we have more of those with different meanings. If you want to trigger on the starting or stopping, we recommend on using the [Home Assistant trigger](https://www.home-assistant.io/docs/automation/trigger/#home-assistant-trigger) instead, as that one takes into account the timing during startup/shutdown.

In other cases, PRs are definitely welcome to extend the documentation 😄 👍

**Comment by eikowagenknecht** [comment]
Sure, I'm all for creating PRs, just wanted to check with you guys here before spending time on this one ;-)

I'll try to find a complete list in the source somewhere when I'm making myself familiar with it later this year. Don't want to base it on "hearsay" from the forums.
