### ISSUE TITLE
Update to show the new template format

### ISSUE THREAD

**Issue by D-Cox** [home-assistant/home-assistant.github.io#20490]
### Feedback

This needs to be updated to show how to implement statistics using the new template format, since the Platform can no longer be specified.

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2021.11.5

**Comment by frenck** [comment]
> This needs to be updated to show how to implement statistics using the new template format, since the Platform can no longer be specified.

The page you left feedback on, has no templates? Could you please clarify exactly what is wrong on this page according to you?
