### ISSUE TITLE
Current guide and documentation kills ALL HomeAssistant instances

### ISSUE THREAD

**Issue by F1zzyD** [home-assistant/home-assistant.github.io#20494]
### Feedback

Followed this guide twice on new installations on a Pi and HomeAssistant fails to boot every time. I only copy/paste and select what your documentation tells me. I've wasted an hour having to reinstall HomeAssistant.

### URL

https://www.home-assistant.io/integrations/http/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there!

Could you describe what you did to kill it? As the `http` page shows multiple things.

Thanks! 👍 

../Frenck
