### ISSUE TITLE
tplink discovery failing even when using static host

### ISSUE THREAD

**Issue by ebdavison** [home-assistant/home-assistant.github.io#20504]
### Feedback

In the setup of the integration, the "wizard" asks for "Host" and leaving it blank does not discover any devices.  Putting any IP address in it results in nothing found.

The "wizard" requesting "Host":
![image](https://user-images.githubusercontent.com/549431/143892742-8009d740-cfa3-4d73-a09b-e3f75a99930a.png)

After I add a host:
![image](https://user-images.githubusercontent.com/549431/143892839-4f254ae1-ad0f-499a-b085-55aa51b1a6ba.png)

After I leave host blank:
![image](https://user-images.githubusercontent.com/549431/143892964-bb4464e8-f7c0-484d-a5c4-af151d40b35c.png)

The "manual" setup instructions just say to add the integration and "follow the wizard" to finish setup.

For me, my HA box (pi 3B+) is on a LAN and all of the wifi devices are on a different network.  I need to manually add my IP addresses and turn off discovery but have no way to do this by "following the wizard" steps.

What are the actual _manual_ steps to configure this now that it has moved to the UI and the `tplink` option in `configuration.yaml` is no longer available (deprecated)?

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.11.5

**Comment by rytilahti** [comment]
Inserting the IP address of the device to that prompt should work, are you sure it's not working?
