### ISSUE TITLE
Unpossible to add Add-Ons via URL

### ISSUE THREAD

**Issue by pabatribick** [home-assistant/home-assistant.github.io#20502]
### Feedback

I'm running into a problem with the Add-On "Alarmo" on an fresh installed raspberry. Can't find it on the Add-On Store and wanted it to install manually with URL (https://github.com/nielsfaber/alarmo) but is isn't possible because i get always an error if i click "add" (see Screenshot below). The Alarmo-Project on Github used URL is: https://github.com/nielsfaber/alarmo

![image](https://user-images.githubusercontent.com/11978788/143862531-eb2457b1-3697-4f5e-bba0-798f55c128a9.png)

This Add-On should be normally available on the store, I'am right?

### URL

http://homeassistant:8123/hassio/store

### Version

2021.11.5

**Comment by frenck** [comment]
This:

<https://github.com/nielsfaber/alarmo>

Is not an add-on; thus indeed you will not be able to add it as such.

**Comment by pabatribick** [comment]
What's with the integrations? From the author:

https://github.com/nielsfaber/alarmo#installation

"Install files:
Using HACS:
In the HACS panel, go to integrations and click the big orange '+' button. Search for 'Alarmo' and click \'Install this repository in HACS'."

Unpossible to find it there

**Comment by frenck** [comment]
If you need support with a custom integration, please ask it with the custom integration itself.

We do not control or maintain custom integrations, so we cannot provide support for them either.

Thanks 👍
