### ISSUE TITLE
OctoPrint Integration Ask for User Name, Not API Key

### ISSUE THREAD

**Issue by mankyd** [home-assistant/home-assistant.github.io#20506]
### Feedback

Octoprint was autodiscovered for me. Your instructions say it requires an API key, but the UI asks for a username and application path.

### URL

https://www.home-assistant.io/integrations/octoprint/

### Version

2021.11.5

**Comment by rfleming71** [comment]
Configuration parameters are getting better docs with this PR: https://github.com/home-assistant/home-assistant.io/pull/20323

**Comment by frenck** [comment]
With the above notes PR merged, and the current documentation:

![image](https://user-images.githubusercontent.com/195327/151781545-c804e9a0-e573-4e93-8f6e-013d539c0b8b.png)

Which tells it will register itself for an API key, I think this has been resolved.

../Frenck
