### ISSUE TITLE
ONVIF keeps locking up / crashing?

### ISSUE THREAD

**Issue by jimmyz5150** [home-assistant/home-assistant.github.io#20517]
### Feedback

Has integration stopping working / streaming correctly?

### URL

https://www.home-assistant.io/integrations/onvif/

### Version

2021.11.5

### Additional information

Hey I noticed the this integration is only working for 3-5 seconds and seems to stop loading feed. It worked fine as far as I know for past 6 months, has been installed for over a year.
just noticed
I have restarted DVR, ONVIF  integration, and Rasp Pi 4.

Any suggestions?

**Comment by jimmyz5150** [comment]
Still haven't heard any response

**Comment by frenck** [comment]
Hi there @jimmyz5150 👋 

The reason for that, it that this report is in an incorrect issue tracker. This issue tracker is used to track documentation suggestions, however, it seems like you want to report an issue with an Home Assistant integration.

Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
