### ISSUE TITLE
Integration: Onkyo - Allow for Unique ID on entities

### ISSUE THREAD

**Issue by Botched1** [home-assistant/home-assistant.github.io#20511]
### Feedback

Duplicate of this:
https://github.com/home-assistant/home-assistant.io/issues/17554

Would like the wbility to put onkyo receiver entities into areas, which requires a unique id.

### URL

https://www.home-assistant.io/integrations/onkyo/

### Version

2021.11.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
