### ISSUE TITLE
Pricing not available on Rainforest Eagle

### ISSUE THREAD

**Issue by Tipalo** [home-assistant/home-assistant.github.io#20529]
### Feedback

Current cost is provided by my meter but is not shown as an entity of the HA device.
Please notice in these cards HS is a Homeseer plug-in that exposes a couple of entities that HA does not.
Power to the Grid and Price per kWH.  The price per kWH is important as it is tiered and rises after a set amount of consumption. Power to the grid may be useful to those with solar.

Both HA and HS are reading the same Eagle but may have slightly different readings due to when the meter was polled.

Thanks

### URL

https://www.home-assistant.io/integrations/rainforest_eagle/

### Version

2021.11.5

### Additional information

![image](https://user-images.githubusercontent.com/55360416/144159200-f626c114-52fe-4272-ba50-7bedf4cbac2a.png)

**Comment by frenck** [comment]
@Tipalo I'm not sure what the documentation feedback is you want to give? What do you think should be changed on the documentation?

**Comment by Tipalo** [comment]
My apologies... I thought the link was to report an issue with the integration not the documentation.
