### ISSUE TITLE
Growatt lifetime energy not shown correctly in energy dashboard

### ISSUE THREAD

**Issue by AJediIAm** [home-assistant/home-assistant.github.io#20532]
### Feedback

The Growatt lifetime energy does not show up correctly in the energy dashboard. 
At the start of the day, all energy is subtracted (shown as a huge amount of negative solar production which is odd)
When the first solar power is produced, all energy is added again (shown as a huge amount of positive solar production)

I have another set of solar panels which does not show this behavior and properly shows the solar production each hour. 

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2021.11.5

### Additional information

This is what the dashboard looks like with both solar systems added:
![solar](https://user-images.githubusercontent.com/5879533/144229616-86f80285-9584-4e08-a27b-ac2af4c3b23c.JPG)
 
The two lifetime energy entities looks near-identical.
Solaredge behaves correctly:
```
state_class: total
unit_of_measurement: Wh
friendly_name: SolarEdge Energy - Lifetime
icon: mdi:solar-power
device_class: energy
```
The Growatt does not:
```
state_class: total
unit_of_measurement: kWh
friendly_name: Growatt Energy - Lifetime
icon: mdi:solar-power
device_class: energy
```
This is the same dashboard with Growatt removed:
![image](https://user-images.githubusercontent.com/5879533/144230078-82a53324-e9f8-43aa-817c-5965c7d9f8ea.png)

**Comment by frenck** [comment]
Hi there @AJediIAm 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by AJediIAm** [comment]
Woops, sorry, I will create a new issue.
