### ISSUE TITLE
DuckDNS: Service set_txt

### ISSUE THREAD

**Issue by edsil** [home-assistant/home-assistant.github.io#20533]
### Feedback

When configuring DuckDNS, there are no options to to "Set the TXT record of your DuckDNS subdomain." as the last step in the document.

### URL

https://www.home-assistant.io/integrations/duckdns/

### Version

2021.11.5

**Comment by frenck** [comment]
Its a service exposed, I'm not sure what you mean with "last step" could you clarify / provide me reproduction steps to get to what is wrong with the documentation?

**Comment by edsil** [comment]
Thanks Frenck for the quick response.
I've created a DuckDNS domain and I can see it when I log into my DuckDNS account.

In this [document](https://www.home-assistant.io/integrations/duckdns/), the last step says:

> Set the TXT record of your DuckDNS subdomain.
> Service data attribute | Optional | Description
> -- | -- | --
> txt | no | Payload for the TXT record.

However the only things I can configure in DuckDNS are "Current IP" and "IPV6", there is nothing else that I can configure.

Thank you again for your support.

**Comment by frenck** [comment]
I think you are missing the concept of services vs configuration.

Services can be called in e.g., automations or scripts.

You can also test/use the service via the developer tools (this button will bring you there):

[![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistant.io/redirect/developer_call_service/?service=duckdns.set_txt)

**Comment by edsil** [comment]
Thanks frenck! I am very new to Home-Assistant (installed yesterday) and am still trying to configure it (and learning the concepts) - you are right, I need to figure those out. Thanks again!
