### ISSUE TITLE
Page title does not match content

### ISSUE THREAD

**Issue by steverep** [home-assistant/home-assistant.github.io#20536]
### Feedback

I would expect a page titled "Adding devices to Home Assistant" to tell me how to add devices to HA, but instead it spends one sentence saying that integrations handle adding devices and goes on to spend most of the text talking about grouping entities.  I find this very confusing.

### URL

https://www.home-assistant.io/docs/configuration/devices/

### Version

2021.11.5

**Comment by frenck** [comment]
Agreed! Feel free to open up a suggested edit for such cases! 👍
