### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by eprescott** [home-assistant/home-assistant.github.io#20539]
### Feedback

This documentation mentions that the router is expecting a password.
But as far as options shown for configuration variables only host is shown.  
Is there a password or username option for the linksys_smart integration?
 if so what are they?
 if not should mention of a password being expected be removed?

### URL

https://www.home-assistant.io/integrations/linksys_smart/

### Version

2021.11.5

**Comment by frenck** [comment]
> Is there a password or username option for the linksys_smart integration?
> if so what are they?

Glanced at the code, there is no such option.

> if not should mention of a password being expected be removed?

Maybe? If you want to suggest an edit to the page, that is always appreciated.
