### ISSUE TITLE
Tuya: synchronization between the device itself and the home assistant switch status

### ISSUE THREAD

**Issue by Lepelot** [home-assistant/home-assistant.github.io#20537]
### Feedback

Hi, my experience is as follows: I got the IOT account set up and the integration installed in my HA and I can "generally" control the Tuya devices.  I have plugs, switches, a relay board and even the blinds are now working since the November release of HA. 
The issue I have is with the synchronization between the device itself and the home assistant switch status. As an example, when I push a switch, the light comes on, but the switch stays off or comes back to off for 5 or 10 sec and then comes on.  I have seen comments showing that other people have the same issue.  Also, my devices become "unavailable" erratically much more often than they did with the old integration although they are available in the Smart Life APP.  

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.5

**Comment by frenck** [comment]
It generally means step 6 is missed:

![image](https://user-images.githubusercontent.com/195327/144308743-c13ecaf8-9c65-4256-bc9b-02218d8a9fa0.png)

Or the authorization has expired (which happens after a month, which can be extended again for 6 months).

**Comment by Lepelot** [comment]
Thank you Franck. I check and verified that this service is there, I must have another problem.

**Comment by frenck** [comment]
🤷

**Comment by Lepelot** [comment]
Sorry, It looks like your response didn't come through.

**Comment by frenck** [comment]
it did.. I have no idea (expressed by 🤷 )

**Comment by Lepelot** [comment]
OK, I get it thanks. Will there be a revision of this integration in  the the HA December release?

**Comment by frenck** [comment]
yes

**Comment by Lepelot** [comment]
Excellent, thank you for your work.

**Comment by smithbill17** [comment]
This is the same problem reported as issue [#515](https://github.com/tuya/tuya-home-assistant/issues/515) ,  [#694](https://github.com/tuya/tuya-home-assistant/issues/694)  and [#711](https://github.com/tuya/tuya-home-assistant/issues/711) (and probably several other Open issues in that thread).

I'm not aware that there's been any resolution as yet.

**Comment by frenck** [comment]
The best question in this case: Is to ask Tuya, they push (or don't push) data.

**Comment by iotinkognito** [comment]
Started again for me. Less than one month subscription since I restarted after the HA .15 update.

**Comment by fazutan** [comment]
Same for me , not updating

**Comment by whodat** [comment]
Exact same experience as described above for me as well, for the last week or two.  :(
It was rock-solid before....

**Comment by smithbill17** [comment]
Tuya are doing nothing about it.

It needs reverted to the previous 'v1' integration which actually worked reasonably well (the one that didn't require the stupid Tuya developer account).

**Comment by Lepelot** [comment]
The Tuya integration in the HA Nov release was terrible; I re-installed the old Tuya and I was ok for a month. I am currently trying the Dec version; It seems a little better than the November version but still not acceptable (long delay between the action and the HA status)
I am going back to "old" Tuya.

**Comment by Rayeliint** [comment]
This has been working perfectly for me but in the last few weeks it has been doing the same. Can turn on a light but cant turn off and not reporting the state.

**Comment by jmferris** [comment]
I have very similar issues with my implementation.  Everything is setup properly, but all of my Tuya lights will eventually either stop responding, or continue to respond and not report status.  Restarting HA will bring everything back to sorts again.  The general pattern for me is that everything will work just fine for around ten hours, and then I will start to have issues controlling lights.  I'll restart and everything will go back to normal for the rest of the evening, but I will have to restart first thing in the morning.

The entire time that this is happening, I can confirm that the Smart Life app on my phone remains fully responsive and reporting accurately.

**Comment by smithbill17** [comment]
The HomeAssistant developers really need to restore the previous Tuya V1 integration that actually worked. If necessary leave the unreliable Tuya V2 integration as an option, but we've got to have SmartPlug control that is reliable (and given that Tuya SmartPlugs are WAY the most available in the UK and elsewhere, I think it's vital that any home automation platform has reliable Tuya SmartPlug support). The Tuya developers are clearly not interested in providing this except within their own apps.

**Comment by frenck** [comment]
> The HomeAssistant developers really need to restore the previous Tuya V1 integration that actually worked.

That is not an option, as that API is being removed by Tuya. We have no choice.

**Comment by smithbill17** [comment]
> that API is being removed by Tuya.

Well, if they're as inept at removing code as they are at adding it, then it'll still be there in 5years time.

**Comment by frenck** [comment]
I'm sorry to hear you are not liking where it goes, I understand the frustration (believe me, it is frustrating as *** for me too), however, this is what the manufacturer offers, nothing more nothing less. If you don't like that, you should consider buying devices from other manufacturers.

**Comment by Rayeliint** [comment]
Since updating to 2021.12.5 mine is working again?
Not sure if there was anything with the latest update or on Tuya side but happy now.
Hoping it will stay that way.
Appreciate all you do too frenck

**Comment by jmferris** [comment]
> Since updating to 2021.12.5 mine is working again? Not sure if there was anything with the latest update or on Tuya side but happy now. Hoping it will stay that way. Appreciate all you do too frenck

Ditto on the appreciation to frenck, and all involved.  Updating to 2021.12.5, as we speak, and will let it bake in for a day or two and see if I am experiencing any improvements or not.

**Comment by Lepelot** [comment]
It is nice to see some positive comments about Tuya. Personally my mini switches are still not working correctly and I went back to the “old” Tuya. Can you guys tell us which Tuya devices are working properly at this point?

**Comment by fazutan** [comment]
Unfortunatly for me it is still not working, after i reset tuya integration for 30-60 min it works fine and then it gets frozen (as decribed in topics above)
What is most anoying is that 3 week ago it worked fine with no issues at all

**Comment by cpdowsett** [comment]
Just to add that i am also having the issue. All works well then usually for me a plug will switch on but not off. Best fix is to just reload the integration. Bit of a faff but much quicker than a reboot. Again the fix usually holds for between 6 to 8 hours then its reload time again. Not sure but maybe i could get the system to automate the re-load. If i can work this out I will report back.

**Comment by cpdowsett** [comment]
Not quite worked this out. 
action:
  - service:  ??
 
Anyone know how to get a service to reload  the Tuya integration?

**Comment by Lepelot** [comment]
you could try this service : Home Assistant Core Integration: Reload config entry

**Comment by Lepelot** [comment]
> I'm sorry to hear you are not liking where it goes, I understand the frustration (believe me, it is frustrating as *** for me too), however, this is what the manufacturer offers, nothing more nothing less. If you don't like that, you should consider buying devices from other manufacturers.

I came to that same conclusion and started to acquire some Athom devices to replace my tuya mini switches and relay board but now I am runing into problems with those as well: They keep switching on and off as shown on this picture. This is is a different subject, so I will open another discussion. 
![Capture d’écran 2021-12-26 163737](https://user-images.githubusercontent.com/76974827/147412998-53ccd057-b077-407b-96a6-69569becd994.gif)

**Comment by Lepelot** [comment]
> The best question in this case: Is to ask Tuya, they push (or don't push) data.

Hello Frenck, what is the best way to contact Tuya on things like this?

**Comment by smithbill17** [comment]
This integration is still not working & is simply not fit for purpose. Tuya should be 'called out' for their inept development & support of this integration.

The 'Local Tuya'' integration is the only one that works & should be adopted as the official HomeAssistant Tuya integration with some form of tool to enable easier device ID & LocalKey discovery.

**Comment by ElderRing** [comment]
@Lepelot @smithbill17 The Tuya integration is free, you cannot expect too much for a free integration. Currently, it works well on my side. If you don't like it, just give it up and move to another integration, it's that simple.

**Comment by smithbill17** [comment]
The minimum to be expected of a free integration, is that it actually works. This Tuya integration does NOT work (you only have to look at the posts & issues raised to verify that). And the reality is that 'features' such as integration to Alexa, GoogleHome & HomeAssistant are built into the price of the product (ie. Tuya SmartPlugs) - so it's not "free".
It's nothing to do with "liking" the integration, it doesn't work. It's that simple.

**Comment by Lepelot** [comment]
Thank you for the comments and advises. I have now moved away from the Tuya integration and I am using Local Tuya with much better rersults.
