### ISSUE TITLE
Raw IP also needs http:// prefix

### ISSUE THREAD

**Issue by Jamesgt** [home-assistant/home-assistant.github.io#20545]
### Feedback

The hostname or IP address of the Fronius device (e.g., 192.0.2.0 or http://fronius.local)

Raw IP does not work, but with prefix http:// it does.

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2021.11.5

**Comment by farmio** [comment]
Yaml configuration for Fronius will be deprecated next release. 
The config flow will support host without `http://`
