### ISSUE TITLE
App account credentials

### ISSUE THREAD

**Issue by jwildman16** [home-assistant/home-assistant.github.io#20549]
### Feedback

The documentation should be updated to include more information about the app account and password (app credentials). For Account, it should be noted that this is the email address used when creating an account within the Tuya Smart Life app (if it's possible for it to be something other than an email address, that should be noted). For the Password, it should be noted that one will need to be manually created if the user originally created an app account by utilizing the Google login option. In my case, I had to log out of the Tuya Smart Life app and then use the Forgot Password link to create my password again for the Home Assistant integration to recognize and accept my credentials. 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.11.5

**Comment by smithbill17** [comment]
This issue is related to #19640 which is marked as 'stale'

**Comment by jwildman16** [comment]
This is included in the documentation: 

> Enter the correct account and password of the Tuya Smart or Smart Life app in the Account and Password fields (social login, which the Tuya Smart app allows, may not work, and thus should be avoided for use with the Home Assistant integration).

But it doesn't indicate what to do (use Forgot Password) if you've already signed up using social login.
