### ISSUE TITLE
Variable used for ISY994 custom device must be a state variable

### ISSUE THREAD

**Issue by tktf50** [home-assistant/home-assistant.github.io#20558]
### Feedback

The ISY994 Integration provides support for custom devices using programs and variables. There are two types of variables available in the ISY994 and the documentation does not make clear that the variable used for this purpose **must** be a state variable rather than an integer variable.

There is also:
- use of the phrase "Name of entity to send the command" where "Name of target entity for the command" would be more appropriate (the entity is not sending the command, it is receiving it).
- a few other minor grammatical errors

I will submit a pull request with suggested fixes.

### URL

https://www.home-assistant.io/integrations/isy994/

### Additional information

This is related to issue #60804, submitted against the Home Assistant core (but turned out to be just a documentation issue).

**Comment by bdraco** [comment]
Thanks for documenting this.  In the future, there isn't a need to open an issue when there is a PR coming since the opening text in the PR is sufficient to explain the reason for the PR.
