### ISSUE TITLE
Light Group

### ISSUE THREAD

**Issue by DavidRBailey** [home-assistant/home-assistant.github.io#20560]
### Feedback

98.2% of your users use this feature and there's no GUI for it?

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2021.11.5

**Comment by frenck** [comment]
> 98.2% of your users use this feature and there's no GUI for it?

That is correct. It is definitely something we want for the future 👍 

That said, this is a feature request, not documentation feedback, so closing it on this end.

**Comment by DavidRBailey** [comment]
Thanks. Just making sure I didn't miss something.
