### ISSUE TITLE
Hardware requirements?????

### ISSUE THREAD

**Issue by framistat** [home-assistant/home-assistant.github.io#20561]
### Feedback

No hardware requirements are stated.

It seems that there is no version of HA that doesn't require virtualization to be supported for the CPU.  If that's so, then there are a lot of us out here wasting time and energy trying to figure this out.  We have older machines (eg Dell Latitude D610 laptop) that are perfectly fine and we think should run HA, but if the CPU (eg Pentium M) we have doesn't support virtualization, no virtual machine or container will work, therefore HA can't be installed.

Minimum storage space also needs to be stated.  Wifi G needs to be stated.

### URL

https://www.home-assistant.io/getting-started/

### Version

2021.11.5

### Additional information

One can use this site to search for CPU virtualization support:

https://ark.intel.com/content/www/us/en/ark/search.html?_charset_=UTF-8&q=pentium+m+

**Comment by frenck** [comment]
The getting started guide points to all kinds of installation methods. Technically you can run it on all you've listed. Some still use a Raspberry Pi 0 for example; which is even lesser compared to what you've posted.

WiFi isn't a requirement, even more, would personally not recommend it either.

Do you have an issue installing?

**Comment by framistat** [comment]
The getting started guide mentions either containers or virtualization for
EVERY installation method given.  The 32 bit CPU in this machine doesn't
support virtualization, so NONE of those methods will work.

Rpi 0, really?  Because the guide says Rpi 3 or 4, and containers, again.

I have never been so frustrated trying to understand how to install a
software package.  I can't find an "entry point" for understanding.

Point me towards an installation method that doesn't use containers or
virtualization.  I haven't been able to find one.

**Comment by frenck** [comment]
https://www.home-assistant.io/installation/

![image](https://user-images.githubusercontent.com/195327/144704743-6a9bcb86-e2a0-4bd3-85b8-611c69e12780.png)

- <https://www.home-assistant.io/installation/generic-x86-64#install-home-assistant-core>
- <https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core>
- <https://www.home-assistant.io/installation/linux#install-home-assistant-core>

**Comment by framistat** [comment]
Like I said, ALL of these instructions reference virtualization/containers.

It would take you little effort and time to edit the instructions to
include non-virtualization/containers, and would benefit more people and
the project.  Instead you seem to want to argue with me by sending back to
me the same thing I originally posted about.

On Sat, Dec 4, 2021 at 4:34 AM Franck Nijhof ***@***.***>
wrote:

> https://www.home-assistant.io/installation/
>
> [image: image]
> <https://user-images.githubusercontent.com/195327/144704743-6a9bcb86-e2a0-4bd3-85b8-611c69e12780.png>
>
>    -
>    https://www.home-assistant.io/installation/generic-x86-64#install-home-assistant-core
>
>
[image: gen.jpg]
tps://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core
<https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core>
Irrelevant to my question, I don't have or desire an rpi.

**Comment by frenck** [comment]
> ALL of these instructions reference virtualization/containers. It would take you little effort and time to edit the instructions to include non-virtualization/containers,

They do not, I even linked them in my last response. I don't like the tone you put in your message though, I could say the same; please read the linked pages above.

**Comment by framistat** [comment]
They do!   Go look at your own links!!

**Comment by frenck** [comment]
They link to setting up a Python core version, no virtualization is involved in that. 

I am closing this issue.
