### ISSUE TITLE
PiHole instructions fail

### ISSUE THREAD

**Issue by stirls1** [home-assistant/home-assistant.github.io#20577]
### Feedback

When I'm at   https://www.home-assistant.io/integrations/pi_hole/   and click the "My ADD INTEGRATION" button, that takes me to  https://my.home-assistant.io/redirect/config_flow_start?domain=pi_hole, it takes me to log into Home Assistant, log in and "Do you want to set up Pi-hole?" OK.  The next step requires entry of a "Host*".  I tried putting my Pi's IP, I tried 8.8.8.8, I tried Cloudflare and they all fail.  What needs to be put in as the host?  Without it, the whole installation fails.

### URL

https://www.home-assistant.io/integrations/pi_hole/

### Version

2021.11.5

**Comment by andreasbrett** [comment]
In this configuration dialog you're being asked for the host where your Pi Hole instance is running.

**Comment by justaguy79** [comment]
Got the same problem. Pi hole runs under 192.168.0.12 and I’m putting that IP into host, port is 80, and it fails. I have no idea what I’m doing wrong, tried around for an hour now.

**Comment by simonspa** [comment]
Similar question here - I'm running a headless Pi Hole, i.e. I did not install the web interface and the webserver. How exactly is the API accessed? I am running an `nginx` webserver on the same machine, so I could expose anything to a port, but it'd be interesting to understand what. Do you directly query the `pihole-FTL` server?

**Comment by TRusselo** [comment]
![image](https://user-images.githubusercontent.com/1154815/154779207-e883f5b0-9001-4904-98eb-e2db3ea8dc04.png)

![image](https://user-images.githubusercontent.com/1154815/154779184-aab95c01-a824-48b0-8e48-81ccd896abbb.png)

im lost too

**Comment by TRusselo** [comment]
![image](https://user-images.githubusercontent.com/1154815/154781013-c97aa455-98ae-44ec-a196-6b85346944e6.png)
log entry
Can not load data from *hole: 192.168.1.20:53

the *hole has me raising an eyebrow
