### ISSUE TITLE
Roomba j7+

### ISSUE THREAD

**Issue by Eliza1700** [home-assistant/home-assistant.github.io#20579]
### Feedback

Any plans on adding support for J7+?
I was able to retrieve the password using charls, but now the integration throws an error, failed to connect.

### URL

https://www.home-assistant.io/integrations/roomba/

### Version

2021.11.5

**Comment by frenck** [comment]
> Any plans on adding support for J7+?

Hi there @Eliza1700 👋 

Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
