### ISSUE TITLE
KVM/Virt-Manager: Maybe. ProxMox PVE: Installation impossible!

### ISSUE THREAD

**Issue by RubberDucky007** [home-assistant/home-assistant.github.io#20580]
### Feedback

Please provide an Installation ISO File for the complete HomeAssistant OS with all. Reason: It is NOT Possible to import an existing external qcow2 image into an LVM Blockdevice. Nor is it possible to upload an .qcow2 file as .ISO or .IMG or .GZ to any of the storagetypes i have (LVM, LVM-Thin, /dev/sdb as LVM and NFS-Mount as shared storage). So, i can't install HA-OS or anything. Documentation says under virtualmachines KVM with virt-manager; which may have this import option. But in the WebUI of ProxMox VE 6.4.13 you can't import anything to the VM. KVM and Proxmox; as stated there; are NOT the same.

### URL

https://www.home-assistant.io/help/

### Version

2021.11.5

**Comment by frenck** [comment]
The fact Proxmox is not providing a UI to import disk images, is not something we can do anything about. I would suggest asking for such a feature with Proxmox. Nevertheless, as a Proxmox user myself, I can use these type of images without issue.

As noted, Proxmox does not provide a UI for these operations and they need to be done via the command line.

Here is a community guide I've found on Google: <https://community.home-assistant.io/t/installing-home-assistant-os-using-proxmox-7/201835>

And here is a blog post of someone: <https://blog.stefandroid.com/2021/10/01/haos-on-proxmox.html>

**Comment by RubberDucky007** [comment]
Okay. But without an ISO Image no one can install HA on new Hardware with an CD Rom Drive. I've tested the github image but it did not start in a virtual CD drive under PVE. SIX Gigabyte tall? WTF is in there?

Later then, i found out how to "replace" a LVM Disk with 'qm importdisk' and the qcow2 via shell. But almost all systems i am Running virtual or Bare Metal are installed via an ISO. This is the normal way to me. 
Did you tried to upload an qcow2 file or an IMG file to a storage which accepts only Disk-images and ISOs? It worked... but then Stops with an Parameter error.

Anyway. It seemed to me the problem is related to some docker-things i found there in. I'm not a fan of docker. Could it be the reason why no ISO File is provided for the classic-install way?

BTW. Virtualbox-image found all devices after install, the PVE Install found only an UpnP Router. No Kodi's, no Shelly's. No Autoscan. Maybe i'm Going back to OH3. Same there. :-) Case closed.
