### ISSUE TITLE
Configure light group from Lovelace

### ISSUE THREAD

**Issue by Cyberwizzard** [home-assistant/home-assistant.github.io#20581]
### Feedback

Since the Lovelace UI can configure nearly everything, are light groups not configurable from within lovelace (except by editing YAML) or is this missing from the docs?

If it is not possible, a single line to that affect would be very helpful.

Assuming it's not yet supported, where can I submit a feature request? 

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2021.11.5

**Comment by balloob** [comment]
This feature is on our radar but no timeline. 

Feature requests need to go to on the forums https://community.home-assistant.io/c/feature-requests/13
