### ISSUE TITLE
How do you configure an entity to ensure it is recognised in "Configure grid consumption"?

### ISSUE THREAD

**Issue by richardjlyon** [home-assistant/home-assistant.github.io#20582]
### Feedback

I get power from MQTT. I've added an integration sensor, but I can't get it to appear in the "Configure grid consumption" dialogue box - it just displays the message "No matching statistics" found. Supplementing this page with information about how to modify the configuration file to produce an entity that the system recognises is necessary. Thanks.

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.11.5

**Comment by frenck** [comment]
It needs to provide an energy device class (or the device is not considered for energy), needs to provide a matching unit of measurement that can be handled by the Energy dashboard (e.g., `kWh`), and needs to provide entity state classification (e.g., `total_increasing`). These properties are all documented in the MQTT documentation.
