### ISSUE TITLE
generic_hygrostat integration removed

### ISSUE THREAD

**Issue by anoblet** [home-assistant/home-assistant.github.io#20594]
### Feedback

It looks like this integeration was removed in this PR: https://github.com/home-assistant/core/pull/36759

### URL

https://www.home-assistant.io/integrations/generic_hygrostat/

### Version

2021.11.5

**Comment by Shulyaka** [comment]
It has not been removed. Still here:
https://github.com/home-assistant/core/tree/dev/homeassistant/components/generic_hygrostat

That PR adds it, not removes.

**Comment by anoblet** [comment]
My mistake, I read the history incorrectly.

However when I try to use the integration, I receive the following error:

```
Setup failed for generic_hygrostat: No setup or config entry setup function defined.
```

**Comment by Shulyaka** [comment]
Please make sure you are using the core integration (i.e. no integration with this name in `custom_components`) and open an issue in the home-assistant/core repo. This repo is for documentation only.

**Comment by anoblet** [comment]
Got it. Thanks for your help.
