### ISSUE TITLE
Dependency to Cisco8601 does not build

### ISSUE THREAD

**Issue by punnerud** [home-assistant/home-assistant.github.io#20603]
### Feedback

I get this error when trying to install Home Assistant Core:

`fatal error: python.h: no such file or directory 1 | #include <python.h>`

Found that the wheel ciso8601 need libpython3.9-dev to build.

### URL

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core

### Additional information

Added a suggestion for change in the installation guide:
https://github.com/punnerud/home-assistant.io/commit/6db66653b2ce1ee9b6d76b65d561717d6e64b0b8

**Comment by frenck** [comment]
This is related to a note already in our documentation:

![image](https://user-images.githubusercontent.com/195327/145014795-43269c96-2149-4720-a318-8a4f22bd401b.png)

**Comment by punnerud** [comment]
I think first impression is important when onbording new developers. Yes it takes some more time to update the guides, but that is probably time saved in the long run.

The issue (suggestion) should maybe be that there could be a core installation process, with test automation.

**Comment by frenck** [comment]
> I think first impression is important when onbording new developers.

This is not developer documentation? Not sure what this has to do with developers.

> Yes it takes some more time to update the guides, but that is probably time saved in the long run.

This is not there because of time or keeping things updates, this is about slight differences between Linux distributions and the environments created by the end-user. We consider this an advanced installation method, please using this should be able to adopt it to their situation.

If that is not the case, we recommend to take a look to the other installation methods.

> The issue (suggestion) should maybe be that there could be a core installation process, with test automation.

We have that.

**Comment by punnerud** [comment]
Yes, there is test automation of the HA OS and "premade" systems.

What I am looking for is something similar to installing Node.red on Raspberry, where all you need to do is to run one command that both install and update on existing linux:
https://nodered.org/docs/getting-started/raspberrypi

<img width="1185" alt="Skjermbilde 2021-12-20 kl  10 28 48" src="https://user-images.githubusercontent.com/1153515/146744894-819e7f28-ce0b-4f67-b696-25c712517949.png">

**Comment by frenck** [comment]
As for the give Node-RED example, that is security-wise a really bad example, as it instructs the user to run a random piece of shell script from the web... Do you know what it does?

Anyways,

We won't be providing such installation for various reasons. We did in the past; so we are well aware of the implications.

Once you have installed it in such a way, new problems arise: How to upgrade? How to keep my system requirements up to date? And many more... not even to start on things like the difference between distributions and user preferences on managing Python environments. What follows is lots of maintenance to work with that, but even more maintenance to support that towards users in terms of helping them with issues and problems in their installation.

This is considered an advanced installation method, if one needs scripts like these, you should not be using this method, to begin with. If you are looking for a managed installation we have multiple, better, installation alternatives to choose from in our installation guide.

**Comment by leonfunnell** [comment]
Found that gcc was required, which is a dependency for ciso8601. Just type `sudo apt install -y gcc` and then retry `pip3 install homeassistant`.  Can you update the documentation to include gcc please?

**Comment by frenck** [comment]
@leonfunnell See: <https://github.com/home-assistant/home-assistant.io/issues/20603#issuecomment-987796291>
