### ISSUE TITLE
I spent hours trying to figure this out and it's mentioned nowhere

### ISSUE THREAD

**Issue by jatgm1** [home-assistant/home-assistant.github.io#20600]
### Feedback

You cannot use the sensor: thing more than once or only the last one will register. You need to put them all under one sensor: thing or it won't work right. Ita actually really annoying because this wasn't in templates when I checked a while ago and this is something that would have saved me a lot of time randomly shuffling lines around my config file. Seriously can we just be really explicit in explaining how this stuff works? When I see something say to put something in the config for an integration to work I just do it and if it says put sensor: in the config and I already have it there that's really just gonna screw me up a lot. I mean at this point I'm just prepared for it because it's the second time, but maybe just make a mention of that, like add the platform line to the config file, if theirs already a line that says "sensor: add it in like this "  - platform" or whatever. Or "do not add "sensor:" if it already exists in your config file or some of your integrations will not be loaded" I mean I'm not trying to be a jerk but in heighsight I now realize why another sensor I tried to add related to getting the right sensor for a tuya temperature controller wasn't working either and I just replaced it with a modified z wave thermostat connected to some relays. I have no idea what I'm doing half the time and neither does half the world, weather they want to admit it or not. Explicit instructions would be less complicated for someone who doesn't know what their doing, which is exactly who you write instructions for so...yeah.

### URL

https://www.home-assistant.io/integrations/sensor/

### Version

2021.11.5

**Comment by frenck** [comment]
I think the confusion is that "sensor" (the integration page you are linking to), is not to be used manually. It is provided by integrations.

I agree we should that make more clear on the pages that provide entity components, like the sensor.

To set up an integration, please consult the page of the integration you like to integrate. For example, the Hue integration page provides specific information how to integrate with Philips Hue (and the hue integration will in her turn, create sensors).
