### ISSUE TITLE
I'm not sure if this applies to my installation

### ISSUE THREAD

**Issue by justbennett** [home-assistant/home-assistant.github.io#20611]
### Feedback

I'm confused about whether or not this integration is necessary. If it is used by 46.7% of active installations, why would it require this custom tinkering with installing the binary and adding code to the configuration? Does it?

I saw in some forum, I cannot find now that FFMpeg was automatically included in current version of Core, but I don't have it in mine. (core-2021.11.5 / supervisor-2021.10.8 / OS 6.6). Or I don't understand how to look for it.

I'm trying to get a security camera working and I don't really understand if this integration is necessary. Some of the documentation suggests that it is, but I cannot figure out from this page how to install it. APT is not on my system (not super good with Linux here) which seems strange.

### URL

https://www.home-assistant.io/integrations/ffmpeg/

### Version

2021.11.5

**Comment by frenck** [comment]
The note on the top of the page says it:

![image](https://user-images.githubusercontent.com/195327/145183304-4f79a028-2d74-47ec-941a-151eb6a44e4f.png)


You are not running the Home Assistant Core installation type, so nothing needs to be done.

As for the usage, many other integrations depends on the `ffmpeg` integration, so they pull in / activate ffmpeg automatically. That is why you see the high usage in our analytics.

**Comment by justbennett** [comment]
I was thrown off by "Home Assistant Core in a Python environment". I'm not as familiar with all the installation types as I need to be, I guess.

So ffmpeg is needed by a different integration (mostly security cameras and media players, I assume) it will be added automatically. Maybe most people won't be coming at this the way I did. I can't think of a way to make it more clear. 

Thanks for the response!
