### ISSUE TITLE
Available/Unavailable not working

### ISSUE THREAD

**Issue by jscmidt** [home-assistant/home-assistant.github.io#20612]
### Feedback

Hi,
Thanks for this helpful integration! However, I have one problem:
Home Assistant doesn’t recognize if Hyperion gets unavailable (no red exclamation mark on the right side of the the entity view). Could you please fix that?

### URL

https://www.home-assistant.io/integrations/hyperion/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @JSAnyone 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by jscmidt** [comment]
Hi,
Thanks for pointing that out, I thought the `provide feedback` button in the docs refers to the integration itself.
I will open a new issue in the core!
