### ISSUE TITLE
WLED Depecated Service Set Preset

### ISSUE THREAD

**Issue by LewisSpring** [home-assistant/home-assistant.github.io#20627]
### Feedback

There should be a mention about the deprecated Set Preset service, and mention if there's a alternative way to automate starting a preset automatically - there's a dropdox select box to do it manually.

### URL

https://www.home-assistant.io/integrations/wled

### Version

2021.11.5 ?

### Additional information

Out of interest, why is the Set Preset service deprecated?
You can't use Set Effect as an alternative.

Thank you!

**Comment by frenck** [comment]
The documentation has been adjusted and updated for the 2021.12 release.

As for the reasoning of removal: the WLED integration was created at a time some things were only possible using custom services. This is no longer the case.

So the preset service has been replaced with an preset select entity.

Not only can the preset select entity be used from the UI, it also has standardized (and more) automation capabilities compared to the old single preset service.

For 2012.12, WLED has been mentioned in the breaking changes section of the release notes about the removal of all its custom services and attributes.

**Comment by LewisSpring** [comment]
Hi Frenck,thanks for your reply. 
I didn't realise I needed to use the select service - I've never needed to until now. I was thinking about it the wrong way. 

Thank you for your help!
