### ISSUE TITLE
Add instructions on where to find or link to "your platform page"

### ISSUE THREAD

**Issue by ShortPutt** [home-assistant/home-assistant.github.io#20624]
### Feedback

Description for target and data Service Data Attributes says "On platforms who have extended functionality. See your platform page if it is supported.".

It would be helpful to provide a link the platform pages, or at least instructions on how/where to find them. 

### URL

https://www.home-assistant.io/integrations/notify/

### Version

2021.11.5

**Comment by frenck** [comment]
They are listed in the top menu bar, platforms are provided by integrations: <https://www.home-assistant.io/integrations/>

**Comment by ShortPutt** [comment]
The information you stated - "They are listed in the top menu bar, platforms are provided by integrations" is precisely the information I am suggesting we add to the page because its not intuitive to know that "platform pages" refers to platform integrations.

Maybe simply change " See your platform page if it is supported." to "Refer to the integration for your platform to see options supported".

Its a minor issue. I know the answer, just thinking about others in the future.
