### ISSUE TITLE
Refresh token not implemented, causes the app need to be reconfigured every couple of hours

### ISSUE THREAD

**Issue by aed0nis** [home-assistant/home-assistant.github.io#20628]
### Feedback

Okay, I have confirmed now that there is no integration for refreshing the token with the refresh mechanism that Honeywell offers. 

When you are asked to login to reauthorize your account and sent back to your callbackurl (which for me was a blank screen) in the URL the `code` param needs to be used to get your authorization code and refresh token in the next step (which is what's missing)

I am not sure if the access token stored in the db is the access token from the previous request or from this next step since you get a new one for each step of the process.

Anyways, after the code is given, this is the next request that needs to be done:

````
curl -X POST --header "Authorization: Basic YOUR_API_KEY" --header "Accept: application/json" --header "Content-Type: application/x-www-form-urlencoded" -d "grant_type=authorization_code&code=CODE_PARAM_VALUE_FROM_URL_CALLBACK&redirect_uri=CALLBACK_URL_YOU_SETUP_IN_HONEYWELL_ADMIN" "https://api.honeywell.com/oauth2/token"
````

This request will give us a response like:

````
{
  "access_token": "ANOTHER_ACCESS_TOKEN",
  "refresh_token": "THE_REFRESH_TOKEN_WE_NEED_SO_SAVE_IN_DB",
  "expires_in": "1799",
  "token_type": "Bearer"
}
````

After the refresh token is saved we need to send a request before the expiry time `1799`. 

```
curl -X POST --header "YOUR_API_KEY" --header "Content-Type: application/x-www-form-urlencoded" -d "grant_type=refresh_token&refresh_token=SAVED_REFRESH_TOKEN" "https://api.honeywell.com/oauth2/token"
````

Now... if someone can code this implementation for me, I would be appreciative. 

### URL

https://www.home-assistant.io/integrations/lyric/

### Version

2021.11.5

**Comment by frenck** [comment]
Hi there @aed0nis 👋 

It seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
