### ISSUE TITLE
Suggestion for your Home Assistant installation page for Raspberry Pi

### ISSUE THREAD

**Issue by jmporter34** [home-assistant/home-assistant.github.io#20637]
### Feedback

If I'm reading the instructions correctly (and I'm actually not 100% positive that I am), it appears that you only need to perform the steps in ONE of the three sections (Install Home Assistant Operating System, OR Install Home Assistant Container, OR Install Home Assistant Core), and then navigate to the Onboarding link after the selected section and continue from there.  
If that is the case (only ONE section is needed), it would be nice if it said that explicitly near the top of the page.  If that is not the case, having Onboarding links in between sections is quite perplexing, and some clarification of that would be nice.  Thanks!

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.11.5

**Comment by frenck** [comment]
I think these are already explained correctly in the introduction?

<https://www.home-assistant.io/installation/>

**Comment by jmporter34** [comment]
@frenck yes you're correct, it is explained there.  However, when I did a google search for "home assistant raspberry pi", the result took me directly to https://www.home-assistant.io/installation/raspberrypi/.   I never saw the introduction at https://www.home-assistant.io/installation/.  Anyway, it was just a suggestion.
