### ISSUE TITLE
Shopping List Sensor

### ISSUE THREAD

**Issue by GNutma** [home-assistant/home-assistant.github.io#20636]
### Feedback

It would be nice to have a sensor that can read the amount of items (unchecked). So that is can be used in automation.

Like
```
If user is at shopping centre:
  Send Notification
    "There are {amount of items} on shopping list, 
     click here to open it"
```

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2021.11.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
