### ISSUE TITLE
Home assistant - Convert date from YYYY.MM.DD to DD name.DD.MM name.YYYY & Parts of the day - To view the current part of the day (example in the Slovenian language)

### ISSUE THREAD

**Issue by Trzinka** [home-assistant/home-assistant.github.io#20633]
### Feedback

# add to configuration.yaml

sensor:
# Date & Time
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
 # Convert date from YYYY.MM.DD to DD name.DD.MM name.YYYY (example in the Slovenian language)
  - platform: template
    sensors:
      date_long: 
        friendly_name: 'Datum'
        value_template: >
          {% set months = ["Januar", "Februar", "Marec", "April", "Maj", "Junij", "Julij", "Avgust", "September", "Oktober", "November", "December."] %}
          {% set month = months[now().strftime('%m') | int -1] %}
          {% set days = ["Nedelja ", "Ponedeljek ", "Torek ", "Sreda ", "Četrtek ", "Petek ", "Sobota "]  %}
          {% set day = days[now().strftime('%w') | int] %}
          {{ day + ' ' + now().strftime('%d') + ' ' + month + ' '+ now().strftime('%Y') }}
# Parts of the day - To view the current part of the day (example in the Slovenian language)
  - platform: template
    sensors:
      greeting:
        friendly_name: 'Del dneva'
        value_template: >
          {% set state = states('sensor.time') %}
          {% if '22:00' <= state < '06:00' %}
            Noč
          {% elif '06:00' <= state < '08:00' %}
            Jutro
          {% elif '08:00' <= state < '12:00' %}
            Dopoldan
          {% elif '12:00' <= state < '12:00' %}
            Poldne
          {% elif '12:00' <= state < '18:00' %}
            Popoldan
          {% else %}
            Večer
          {% endif %} 

### URL

https://www.home-assistant.io/integrations/time_date/

### Version

2021.11.5

### Additional information

 # Convert date from YYYY.MM.DD to DD name.DD.MM name.YYYY (example in the Slovenian language)
![Datum](https://user-images.githubusercontent.com/40424965/145371638-7104a770-cb58-4b54-a54b-e38aa53f265e.png)

# Parts of the day - To view the current part of the day (example in the Slovenian language)
![Del dneva](https://user-images.githubusercontent.com/40424965/145371763-ebc9c6a5-4793-4543-8fb2-f466206839ff.png)

**Comment by frenck** [comment]
Hi there @Trzinka

I'm not sure what you are trying to tell/explain/suggest; Could you add a bit of story/context to your issue maybe?

../Frenck

**Comment by Trzinka** [comment]
> 

I'm sorry. Because I’m new I don’t even know how to do it properly so the code isn’t copyrighted or something. I was angry because the date was shown to me in the American Forat (2021.12.08) instead of (08.12.2021) the EU. I played around a bit to show me the days and months by name. In Slovenia we know more periods of the day than the rest of the world. At least that's how it seems to me. I also found it nice to see what part of the day it was.

**Comment by Trzinka** [comment]
I was looking at (https://www.home-assistant.io/integrations/time_date/) and it seemed a little too general, so I wanted to make it easier for someone who might be interested.

**Comment by frenck** [comment]
>I was angry because the date was shown to me in the American Forat (2021.12.08) instead of (08.12.2021) the EU.

This is a helper, that provides iso formatted date-times that can be used in many ways; including automations, calculations in templates, or format it as you want in e.g., a sensor for you to show on a Lovelace dashboard.

I'm not sure what you are trying to tell/do with this documentation feedback.

**Comment by Trzinka** [comment]
Sorry Frenck. As I mentioned I am a beginner and didn’t know where to post. I fixed it and hope it’s okay now. https://community.home-assistant.io/t/dashboard-for-date-time-times-of-the-day-season-currently-weather-weather-forecast-weather-card/364941
