### ISSUE TITLE
Ecowitt GW1000 is no longer available.

### ISSUE THREAD

**Issue by joewiatyahoodotcom** [home-assistant/home-assistant.github.io#20640]
### Feedback

In //Ambient Weather Station 
Ecowitt GW1000 is mentioned as an alternative to cloud. It is no longer available.

### URL

https://www.home-assistant.io/integrations/ambient_station/

### Version

2021.11.5

**Comment by bachya** [comment]
I'm not sure what you mean – no longer available in what way?

**Comment by joewiatyahoodotcom** [comment]
No longer available for purchase.Product has been discontinued.
