### ISSUE TITLE
No mention of lat/lon position!

### ISSUE THREAD

**Issue by joewiatyahoodotcom** [home-assistant/home-assistant.github.io#20649]
### Feedback

There is no mention of setting your position (lat/lon) in the Install - Onboarding docs. Nothing even in the "Map" section.
This is a pretty serious omission, since the HA OS needs this info.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2021.11.5

**Comment by frenck** [comment]
One selects their location on the map? I'm not sure what you are trying to suggest.
Could you clarify it?

**Comment by joewiatyahoodotcom** [comment]
When installing HA, I did not see any reference to picking a location on the map. In fact, I thought it was rather odd that Amsterdam showed up on the map!Anyway, I was having trouble with the sun.sun, and did not get it running properly until I added my lat/lon into the config file. Then, of course, the map showed my correct location, and the sun.sun started working properly.Maybe it's just me, but I think there should be some explicit mention of location in the set up/install directions.Thanks.
   On Saturday, December 11, 2021, 03:30:44 AM MST, Franck Nijhof ***@***.***> wrote:  
 
 


One selects their location on the map? I'm not sure what you are trying to suggest.
Could you clarify it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/145677469-b8095912-a05b-4683-b836-ab26ebbe7f36.png)

☝️ What to do at that point, is exactly written in the onboarding guide. Not setting a location during onboarding/skipping that step, will indeed render location-based things (like the sun) useless.

I'm not sure what is wrong with the guide? To me it sounds like you skipped a skip?

**Comment by joewiatyahoodotcom** [comment]
Yes, I'm one of those who "would rather not send your location...".Sorry for the confusion.
    On Saturday, December 11, 2021, 06:04:14 AM MST, Franck Nijhof ***@***.***> wrote:  
 
 




 ☝️ What to do at that point, is exactly written in the onboarding guide. Not setting a location during onboarding/skipping that step, will indeed render location-based things (like the sun) useless.

I'm not sure what is wrong with the guide? To me it sounds like you skipped a skip?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
