### ISSUE TITLE
Template is not working correctly

### ISSUE THREAD

**Issue by ktpx** [home-assistant/home-assistant.github.io#20651]
### Feedback

This template example doesnt seem tow work anymore as the sensors seems to have changed. 

### URL

https://www.home-assistant.io/integrations/seventeentrack/

### Version

2021.11.5

**Comment by nightmare1111** [comment]
i had previuosly used the entities card but it has recently stopped working and now shows the entities as unavailable
'''entities:
  - entity: sensor.seventeentrack_packages_in_transit
  - entity: sensor.seventeentrack_packages_not_found
  - entity: sensor.seventeentrack_packages_undelivered
  - entity: sensor.seventeentrack_packages_returned
  - entity: sensor.seventeentrack_packages_delivered
title: Shipping Overview
type: entities'''

however the tracked parcels do work in the entities card
'''type: custom:auto-entities
card:
  title: Parcels
  type: entities
filter:
  include:
    - entity_id: sensor.*track_package_*
      options:
        type: custom:template-entity-row
        name: >-
          {{ state_attr('this.entity_id','friendly_name') |
          regex_replace(find="Seventeentrack Package: ", replace="",
          ignorecase=True)}}
        secondary: >-
          {% if states[config.entity].location is defined %} {{
          relative_time(states[config.entity].last_changed) }} ago {% else %}
          Undefined {% endif %} - {{ state_attr(config.entity, 'info_text') }}'''

**Comment by nightmare1111** [comment]
all started working again December 2021
