### ISSUE TITLE
Jellyfin configuration is possibly wrong

### ISSUE THREAD

**Issue by boomam** [home-assistant/home-assistant.github.io#20657]
### Feedback

The entire section for Jelly Fin is wrong,
There are no settings within the app that equate to what is asked to be changed/turned on, “Enable this provider for metadata searches on artists and albums.”.

This section needs removing, or changing to specify that container based installs do not have the option - unable to verify non-container installs.

### URL

https://www.home-assistant.io/integrations/jellyfin/

### Version

2021.12.0

### Additional information

Container: ls.io/Jellyfin:latest

**Comment by RunC0deRun** [comment]
Hi there, you are right. It seems this has been removed quite a while back now in https://github.com/jellyfin/jellyfin/pull/4608.
(This integration was already submitted last year and was only recently merged and I didn't check this part of the documentation again). Thanks for the feedback. I'll work on removing this part of the documentation.

**Comment by boomam** [comment]
Hey,
I was just researching some alternatives/where the option is - if i find anything (or not), i'll post back here to update so you have something to work off! :-)

Thanks!

**Comment by RunC0deRun** [comment]
Hi, I've removed the section from the documentation. As far as I can see, artist and album images are now included by default.
