### ISSUE TITLE
No valid information about configuring WiFi on Raspberry

### ISSUE THREAD

**Issue by Apflkuacha** [home-assistant/home-assistant.github.io#20652]
### Feedback

When I flash HASSOS on the SD-Card there is no hassos-boot available to put in the config for the WiFi settings, as described in some help page. On the SD Card are following partitions: hassos-kernel, hassos-system0, hassos-overlay and hassos-data. Where to put the config for WiFi? 
And no, plugging in Ethernet is not an option..

### URL

https://www.home-assistant.io/installation/

### Version

2021.11.5

**Comment by frenck** [comment]
@Apflkuacha

We don't recommend using Wi-Fi for your Home Automation hub. Thus not part of the documentation.

However, you can set it up via the UI, if you want. Supervisor -> System -> There is the option to change your network settings and configure your Wi-Fi.

**Comment by Apflkuacha** [comment]
Because it is a rental flat and the router is locked in a shelf, there is no option to plug in Ethernet. Thus I cant connect to the UI and the System can't load anyway because loading the necessary files failed (no internet). There is just the message it will take 20 minutes to configure and in the background it tries connecting the internet for hours! 
As configuring WiFi over the SD card doesn't work any more I've done it with an USB Stick named CONFIG and in there the network information file.

**Comment by frenck** [comment]
>  Thus I cant connect to the UI and the System can't load anyway because loading the necessary files failed (no internet).

It needs a wired connection to be able to set it up. There is no option to pre-configure Wi-Fi.
