### ISSUE TITLE
homeassistant.turn_on service can't handle color_temp data option for hue lights anymore

### ISSUE THREAD

**Issue by gitviola** [home-assistant/home-assistant.github.io#20658]
First of all: thank you for that amazing update! I’m really happy to have all my Hue Scenes inside HA.

### Feedback

After installing HA 2021.12.0 my sunset automation doesn't work anymore. After some checking I found out that the API call to the philips hue bridge fails when the following service is called (example payload taken from my sunset automation):

```yaml
service: homeassistant.turn_on
target:
  entity_id: light.desk_lamp
data:
  color_temp: 1000
  brightness: 140
  transition: 50
```

### Error:

```
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://192.168.178.3/clip/v2/resource/light/87d3db72-0391-4aea-b268-73a1869aac0c')
```

The error happens no matter if a light group or individual light is provided in the `entity_id` option.

After some playing around I identified that the call works if the `color_temp` option isn't provided. So I conclude that for some reason this option breaks something around the API call to the bridge. I assume that this isn't expected as I haven't read anything related to the color temperate in the release notes and when checking the state of the lamp through the developer tools I can still see `color_mode: color_temp, color_temp: 174`.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2021.12.0

**Comment by marcelveldt** [comment]
Thanks for your report. Just as an advice for next time: create issue reports in the repo for the HA core.
This repo is for the website/documentation. Thanks!

That said: The color temperature of 1000 is invalid.
Try again with 500 or even lower. I think the previous API was not so strict and just converted to the max value the light can handle.

**Comment by gitviola** [comment]
Thanks for the reply @marcelveldt and sorry about the wrong repo.

I’ve tested the same payload with different values and it seems like the light I’m testing with allows values from (including) 253 to 500. So what you pointed out seems to be what is causing my issue.

I’ll try to figure out a way to get a common value for a group of lamps for my sunset automation or target every light separately instead.

Thanks again for your reply and help!
