### ISSUE TITLE
Powerwall error after latest HA update

### ISSUE THREAD

**Issue by robertfgoodworth** [home-assistant/home-assistant.github.io#20662]
### Feedback

My Tesla Powerwall Integration is now broken, was working before I upgraded, looks like this upgrade may have triggered something, I get the following error in the logs, any help will be greatly appreciated.

Config entry 'Home Energy Gateway' for powerwall integration not ready yet: Powerwall is unreachable: HTTPSConnectionPool(host='192.168.30.??', port=443): Max retries exceeded with url: /api/login/Basic (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa5bebe8b50>: Failed to establish a new connection: [Errno 113] Host is unreachable')); Retrying in background.

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2021.12.0

**Comment by jrester** [comment]
Can you access the web UI of your powerwall in the browser using the configured IP?

**Comment by robertfgoodworth** [comment]
Hi jrester,  Yes i can as "customer" however i use a user ID and password to logon to that, the intergration only askes for an IP adddress and password, no entry for a user ID. happy to send screen shots if needed.

**Comment by jrester** [comment]
It probably isn't an auth issue, because than there would be a different error. Could you provide more detailed logs?

**Comment by robertfgoodworth** [comment]
Hi Jrester,

 

Sorry I’m more of a user then a developer, how do I go about getting the logs you need? Happy to provide them.

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

Australia

Rob M: 0428699792

**Comment by robertfgoodworth** [comment]
Hi Jrester,

 

Sorry for wasting your time,  I forced the Powerwall to reconnect to my network and it’s working again.

 

Regards

 

Robert & Anne Goodworth

21 Harcus Close 

Bonython, ACT, 2905

Rob M: 0428699792

Anne M: 0430460855

 

From: ***@***.*** ***@***.***> 
Sent: Monday, December 13, 2021 8:31 PM
To: 'home-assistant/home-assistant.io' ***@***.***>; 'home-assistant/home-assistant.io' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [home-assistant/home-assistant.io] Powerwall error after latest HA update (Issue #20662)

 

Hi Jrester,

 

Sorry I’m more of a user then a developer, how do I go about getting the logs you need? Happy to provide them.

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

Australia

Rob M: 0428699792

**Comment by frenck** [comment]
Hi there @robertfgoodworth :wave:

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
