### ISSUE TITLE
Error after 2021.12 update

### ISSUE THREAD

**Issue by JoeAverge9** [home-assistant/home-assistant.github.io#20661]
### Feedback

After updating to HA 2021.12 I am getting the follow error on the integration page.
Retrying setup: Cannot connect to host maps.geogratis.gc.ca:80 ssl:default [Connect call failed ('192.67.45.111', 80)]

I deleted and re-added the integration and am getting the same

### URL

https://www.home-assistant.io/integrations/environment_canada/

### Version

2021.12.0

**Comment by mrochette01** [comment]
I have the same error. After several uninstallations and reinstallations, the error persists.

**Comment by michaeldavie** [comment]
This is not an issue with the documentation; please see https://github.com/home-assistant/core/issues/61528.

This issue can be closed.

**Comment by JoeAverge9** [comment]
Following https://github.com/home-assistant/core/issues/61528
