### ISSUE TITLE
Tesla Wall Connector integration page is quite sparse

### ISSUE THREAD

**Issue by davidmankin** [home-assistant/home-assistant.github.io#20660]
### Feedback

Would be very helpful if this page (Tesla Wall Connector integration page) described what was actually available from the integration.  

What entities does it create? What attributes do they have? What services does it provide? 

(I ask because I'm considering buying the Tesla Wall Connector, so it would be nice to know how it actually integrates with HA.)

### URL

https://www.home-assistant.io/integrations/tesla_wall_connector/

### Version

2021.12.0

**Comment by chris-in-texas** [comment]
I would like to know what the "states" are?  So far I have seen 0 / 9 /11

**Comment by einarhauks** [comment]
> I would like to know what the "states" are? So far I have seen 0 / 9 /11

The Tesla Wall Connector API is undocumented by Tesla so we don't know what the states mean...

**Comment by dklarsbach** [comment]
Hi
ANd thanks for a nice integration :-)

I do see a problem that I get a spike in KWH. See below with the normal charge and the a sudden shift in KWH.

Anybody else seeing this issue?
![image](https://user-images.githubusercontent.com/97276599/148503383-50c799df-284a-40be-bd4b-784e40f96e82.png)

**Comment by MiRoCZ** [comment]
Hi, thank you for great TWC integration ! 
Does it support charging current setting/adjustment ?
I would like to set Automation to adjust charging current based on photovoltaic energy production.
THX.

**Comment by chris-in-texas** [comment]
So as state numbers go, I would like to add what I know here for others:
1 - Not plugged into car
4 - Plugged in but not charging
9 - Plugged in but not charging
11 - Plugged in and charging

Not sure the exact difference between 4 and 9.

Also the "COST" function does reset from time to time, not sure why but will reset to zero for some reason.
