### ISSUE TITLE
Wish for Helper of Button Type 

### ISSUE THREAD

**Issue by klaus1956** [home-assistant/home-assistant.github.io#20665]
### Feedback

Hello
I would like to use this new type of entity for existinmg dashboard - and havin a helper of this type would be very much appreciated.

Greetings from Germany 
Klaus

### URL

https://www.home-assistant.io/integrations/button/

### Version

2021.12.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
