### ISSUE TITLE
CLA Signup not functioning

### ISSUE THREAD

**Issue by dramamoose** [home-assistant/home-assistant.github.io#2067]
CLA Signup is not functioning. I am able to get to the first page, then authorize access via GitHub. However, at this point I am sent to the "Please wait while we complete authentication and load data from GitHub" page, which then spins forever.

I've tried in both Chrome and Firefox.

**Comment by jdevelvis** [comment]
I get it too. Just spins and spins. I inspected the page, and found this JS error:

```
XMLHttpRequest cannot load https://cla.home-assistant.io/github/exchange. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://home-assistant.io' is therefore not allowed access. The response had HTTP status code 502.
```

Perhaps an issue getting information from a different domain? (cla.home-assistant.io instead of home-assistant.io)

**Comment by robbiet480** [comment]
GitHub seemed to make a breaking change which screwed up the existing regex method of getting the `code` for oAuth2. I have now replaced it with a better method which won't have this issue. It will be deployed in the next 10-30 minutes. Sorry for the delay, been deathly ill the last 48 hours.

**Comment by dramamoose** [comment]
Thank you! And I hope you feel better!
