### ISSUE TITLE
Typo in package

### ISSUE THREAD

**Issue by betpagal** [home-assistant/home-assistant.github.io#20673]
### Feedback

In a step, there is
sudo apt-get install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0 tzdata

libturbojpeg0. The "0" is extraneous.

### URL

https://www.home-assistant.io/installation/linux/

### Version

2021.12.0

**Comment by mrand** [comment]
Looks like it's only extraneous [for Ubuntu](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libturbojpeg&searchon=names).

For Debian, which is what is "officially" supported, it appears to be libturbojpeg0:
https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libturbojpeg

**Comment by betpagal** [comment]
That would explain it! :-)

**Comment by frenck** [comment]
There is a note in this page, that things might different a bit depending on the environment you are using.
