### ISSUE TITLE
No documentation on new area card

### ISSUE THREAD

**Issue by mrand** [home-assistant/home-assistant.github.io#20670]
### Feedback

The 2021.12 release notes mentions "a brand new area Lovelace card," but the card doesn't appear to be mentioned anywhere else on the Home Assistant website. 

It would be nice to have something which described what all it does (and doesn't do?).... i.e. does every single item with an area assigned auto-populate?   https://community.home-assistant.io/t/area-lovelace-card/365782

And YAML config for it? From what I've been able to gather, it's something like:

type: area 
area: 
show_camera: 
navigation_path: 
theme:

### URL

https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/cards/hui-area-card.ts

### Version

2021.12

**Comment by dannytsang** [comment]
@mrand A little bit late but [this](https://www.home-assistant.io/lovelace/area/) was added on December 22.

**Comment by frenck** [comment]
Ah right, this can be closed. Thanks @dannytsang 👍
