### ISSUE TITLE
Example service file would be helpful

### ISSUE THREAD

**Issue by hijackindie** [home-assistant/home-assistant.github.io#20677]
### Feedback

As I do not run many apps in venv it would be helpful to have an example service file to get HA working at boot using systemd in a venv. Thx.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.12.0

**Comment by frenck** [comment]
It depends on which system one is installing Home Assistant on.
Using the Home Assistant Core installation method, is considered an advanced installation method. If this raises questions or problem for you, we recommend you to consider one of the other installation type instead.
