### ISSUE TITLE
no more check config, yet link still in docu.

### ISSUE THREAD

**Issue by Brun059** [home-assistant/home-assistant.github.io#20683]
### Feedback

There is no more a "check configuration" (at least) in  2021.12. The respective link on this docu page points to nowhere

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2021.12.1

**Comment by marcelveldt** [comment]
You've discovered a small issue in the documentation.

The "check configuration" is only visible when "advanced mode" is enabled. 
That way some more advanced controls will be available to configure Home Assistant and addons.

Click on your username at the bottom of the left menu. Enable advanced mode.

Feel free to [submit a change to the documentation](https://github.com/home-assistant/home-assistant.github.io/tree/current/source/_docs/configuration.markdown) to help others running in this same situation.
