### ISSUE TITLE
Unknown error?

### ISSUE THREAD

**Issue by mikesellt** [home-assistant/home-assistant.github.io#20686]
### Feedback

I'm not sure this is the best place to ask this, but this integration isn't working for me.  See attached image. 
![HA-TS-Error](https://user-images.githubusercontent.com/67391933/145908790-85015e47-a207-49ab-8155-a689aa653502.png)

Is there somewhere I can go to see what the "unknown error" is?  I checked HA logs but couldn't find anything there.  I tried changing a character in the key, and I got an authentication error, so I know it's at least trying to do something.  

### URL

https://www.home-assistant.io/integrations/tailscale/

### Version

2021.12.1

**Comment by frenck** [comment]
Hi there @mikesellt 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have provided documentation feedback instead. Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Be sure to include any logs, if available.

Thanks! 👍 

../Frenck
