### ISSUE TITLE
External Access? 

### ISSUE THREAD

**Issue by jerryac** [home-assistant/home-assistant.github.io#20682]
### Feedback

Does this integration require Home Assistant to have external access setup?

### URL

https://www.home-assistant.io/integrations/meraki/

### Version

2021.12.1

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/145894188-766f4560-2adc-475a-b096-6fbaff76ce4a.png)

Yes, it is cloud polling, thus it depends on the cloud to access this information.
