### ISSUE TITLE
Integration does not work with Magic 2 WiFi next

### ISSUE THREAD

**Issue by JeroenTuinstra** [home-assistant/home-assistant.github.io#20697]
### Feedback

The integration does not work with Magic 2 WiFi next - as the documentation claims. 
There is a bug in the current firmware of the Magic 2 WiFi next device.
See discussion here: [https://github.com/home-assistant/core/issues/61628](https://github.com/home-assistant/core/issues/61628)

### URL

https://www.home-assistant.io/integrations/devolo_home_network/

### Version

2021.12.1

**Comment by frenck** [comment]
Issues with integrations are tracked in the core issue tracker, not the documentation feedback.

Lets keep it centralized here: <https://github.com/home-assistant/core/issues/61628>

**Comment by JeroenTuinstra** [comment]
I understand that issues should be discussed there. But if the documentation claims compatibility with a device, which it isn't compatible with, shouldn't the documentation be changed?
