### ISSUE TITLE
Unclear what "set this to the Linux boot cmd" means

### ISSUE THREAD

**Issue by JeffyBeepBoop** [home-assistant/home-assistant.github.io#20691]
### Feedback

The instructions instruct to "set this to the Linux boot cmd." It is unclear to me what "set this to" means in this context. Do you mean enter the command into the command prompt on the host machine? 

Original:
> If the AppArmor is not enabled on your host, set this to the Linux boot cmd: apparmor=1 security=apparmor and reboot your operating system.

Alternate: (something like this might be clearer) 
> If the AppArmor is not enabled on your host, enter the command: `apparmor=1 security=apparmor` into terminal on your host and reboot your operating system.

### URL

https://www.home-assistant.io/more-info/unsupported/apparmor/

### Version

2021.12.1

**Comment by frenck** [comment]
No, you need to set it as the kernel boot parameters
