### ISSUE TITLE
More optios

### ISSUE THREAD

**Issue by ErikSiemens** [home-assistant/home-assistant.github.io#20694]
### Feedback

Hello,

I’m not shure  this is the right place for my question, but would it be possible to ad a clock thermosta in this card ?
Zo I can make a scheme for day/week to overwrite the scheme in the device.
Best would even be to control it by room insted of by device. Ie I got 1 thermostat and several (smart)radiatorvalves in my living room.
If the scheme would put living room to 20 degrees, al devices would be set to 20 degrees.

kind regards,

Erik 

### URL

https://www.home-assistant.io/lovelace/thermostat/

### Version

2021.12.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
