### ISSUE TITLE
Entertainment group does not go up anymore

### ISSUE THREAD

**Issue by Julien-Decoen** [home-assistant/home-assistant.github.io#20695]
### Feedback

Previously, we were able to use and manage light.entertainment_* groups lights. Now, I can't show them in the integration entities.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2021.12.1

**Comment by marcelveldt** [comment]
Entertainment groups are not exposed as lights, these are controlled by the Hue Sync ecosystem. However you can control the lights and zones. Maybe create a zone with those lights in the Hue app?

There is a sensor if the entertainment mode is active. Is that what you mean?

**Comment by Julien-Decoen** [comment]
First of all, thanks a lot for your amazing job on this release. I'm really excited to use Hue scenes from HA scenes.

Previously, I used Hue entertainment group for 2 usecases :
- for Hue sync
- for managing brightness of a sub group

In both cases, it's the same lights group

For example, I've got a **Livingroom** group. Inside I've got scenes with some lights off (celling). A few seconds before auto turning it off, I decrease the brightness of the hue entertainment group to notify people inside the room. But if I used the livingroom group, celling turning on with the same brightness level...

There is some workaround like making another group only for this usecase (so one per room) but I don't care about scenes in this usecase and it adds a lot of things on Hue app homepage and confusing other user in my house.

I think that it's so cool to add some hue light group (no scening or other) from the entertainment Hue page which is hide on the hue homepage and available in HA.

As you disabled Hue groups light by default, is there a way to do the same for entertainment group like it was previously ? :)

**Comment by marcelveldt** [comment]
I understand what you mean but the underlying datamodel changed in the Hue ecosystem.
In fact I'm using the exact same automations in my setup ;-)

Just add another zone (not room) in the Hue app with these lights. No scenes will be created by default.

Controlling the Entertainment area as a light in HA is no longer possible, sorry.
We've added some sensors for the Entertainment mode. One binary sensor to see if it's active or not.
And on lights you now see a "mode" attribute. This will be set to "streaming" if the light is in streaming mode from Entertainment.

If you don't want to add another zone in the Hue app, you can also just create the group in HA and add the lights to it.
https://www.home-assistant.io/integrations/light.group/

**Comment by Julien-Decoen** [comment]
Bad news :/ I'll use HA light group instead :) It could be cool to write it on the release note or doc page as breaking change.

Extra spoiler question ! :) Do you plan / Is there a way to start entertainment feature like spotify sync from HA ?

**Comment by marcelveldt** [comment]
I will look into adding some extra features from the new API like controlling the Entertainment group and managing gradient lights but first all basic stuff must be stable. Maybe something for next HA release...

So yes, the plans are there ;-) No guarantees about the when however.

**Comment by marcelveldt** [comment]
> It could be cool to write it on the release note or doc page as breaking change.

Strictly taken it's not a breaking change. Those lights for entertainment groups shouldn't have existed at all, they actually got created by a bug.

**Comment by Julien-Decoen** [comment]
> So yes, the plans are there ;-) No guarantees about the when however.

So cool ! Take your time !  Good luck :)
