### ISSUE TITLE
LED control for Kasa Smart dimmers (HS220).

### ISSUE THREAD

**Issue by AntBurdin** [home-assistant/home-assistant.github.io#20705]
### Feedback

Thank you for the update!
I always wanted to switch off those glowing rings in my bedroom - finally it is possible. 
However it is not working for dimmer. Is it possible to disable LED ring on Kasa Smart dimmers (HS220)?
Sincerely,
Anton

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2021.12.1

**Comment by rytilahti** [comment]
Is it possible to control this led ring via the kasa app? If yes, support for it could be added as soon as we know how it's being controlled, either by the fact that it uses the same command as strips&plugs, or by doing a network capture and finding the command.

To test if the same command is used on dimmers, you could install [python-kasa](https://github.com/python-kasa/python-kasa#getting-started) and try to execute the led command (`kasa --host <host> --plug led`) to see if you receive a response. `kasa --host <host> --plug led 0` can be used to turn the led off.

**Comment by AntBurdin** [comment]
> Is it possible to control this led ring via the kasa app? If yes, support for it could be added as soon as we know how it's being controlled, either by the fact that it uses the same command as strips&plugs, or by doing a network capture and finding the command.
> 
> To test if the same command is used on dimmers, you could install [python-kasa](https://github.com/python-kasa/python-kasa#getting-started) and try to execute the led command (`kasa --host <host> --plug led`) to see if you receive a response. `kasa --host <host> --plug led 0` can be used to turn the led off.

Hi,
No, there’s no such option in the official App. However the proposed command worked for my dimmer perfectly. It would be grate to get this control in UI for dimmers as we have it for switches. 
Thank you!

**Comment by rytilahti** [comment]
Hi @AntBurdin and thanks for reporting back, glad to hear it's working! The linked PR should fix this by adding the LED switch also to dimmers!
