### ISSUE TITLE
BH1750 instruction clarification/pointers having just set mine up

### ISSUE THREAD

**Issue by simonpickering** [home-assistant/home-assistant.github.io#20706]
### Feedback

With Home Assistant 2021.12.1 on a RPi3

No need to follow the smbus installation instructions if you already know the i2c address - it was confusing to understand whether the smbus stuff was required irrespective. I'm honestly not sure if it's possible to install these things at all (I didn't have root access at this point) and would suggest just trying the two options to see which works.

The instructions to enable i2c didn't really work (https://www.home-assistant.io/common-tasks/os#enable-i2c). Editing the config.txt file in the RPi boot partition worked of course (I used an SD card reader as by that point I'd not worked out how to get root access over SSH, which I needed later). The automatic copying of rpi-i2c.conf didn't work after the reboot, and the file didn't get copied into /etc/modules-load.d/

Therefore I setup SSH (SSH & Web Terminal), set a hard password in the Configuration Tab (which itself took some time to find!) and changed the login username to root. Then logged in (using the embedded terminal), and created the /etc/modules-load.d/rpi-i2c.conf using vi.

After that it all worked, but that all took rather a long time!

I also note that the device appears in Configuration > Entities as "Ambient Light", but if you click it you get what looks like an error message , but from Googling is apparently not actually an error: "This entity ('sensor.ambient_light') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail."

It still works, you just can't place it in a particular room or rename it, I gave up trying to understand if it was possible to set a unique id as it didn't like me trying to add a unique_id field to the configuration.yaml entry.

HTH

### URL

https://www.home-assistant.io/integrations/bh1750/

### Version

2021.12.1

**Comment by mrand** [comment]
Any chance you could be talked into clicking the "Edit" at the bottom of that page, make the changes, and submit a pull request?

**Comment by simonpickering** [comment]
Certainly, I was just reluctant to change things as I'm very new to the system, not sure I (yet) know quite what I'm doing and whether I'd simply missed something that would have made the existing instructions work (having only set the system up a couple of days back).
