### ISSUE TITLE
Most frustrating install experience!

### ISSUE THREAD

**Issue by virgilm** [home-assistant/home-assistant.github.io#20701]
### Feedback

This is coming from a (seasoned) software engineer: Never seen a more confusing installation manual!

Trying to install on RPi4 - probably the most common platform for you. You know, RPi has an OS already! I was able to install it via the "manual" procedure, but no non-engineer would be able to do so. But it has issues: no supervisor for one. How do I install the supervisor? Why there is no supervisor?

The RPi Imager has its own Homeassistant install, which method is that? Shouldn't that be the default, sanctioned method? If not, why it is even present there?

HaOS is what? I can't mount the SD card. I can't apparently set up WiFi without physical access to the RPi. Docs say "Home Assistant can work with Wi-Fi, but an Ethernet connection is more reliable and highly recommended." - that's fine and your opinion, but I need WiFi, and WiFi for IoT is now ubiquitous. The install guide does not mention how do to that. There is already a solution for that, even headless, for RPi.

You guys are re-inventing the wheel, and in particular on your most common platform, RPi. It seems that everything is a container for you, and that is simply not true.

Documentation is non-existent, except for forum questions and 100s of answers. Search on the site is useless, search with Google returns confusing and random results.

Sorry if this comes as too aggressive, but if you want more people to use your software, you *have* to fix the installation docs. 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.12.1

**Comment by 1000dinge** [comment]
Same here! I'm not able to install HA-OS. Stuck on trying to setup the admin account after fist boot. It stays on that screen. Regardless what i do. Raspi got his ip and Internet-Connection, that all i can see. No way to see what happens, no log, no ssh.

**Comment by frenck** [comment]
> Trying to install on RPi4 - probably the most common platform for you. You know, RPi has an OS already! 

Yes, we know, it doesn't fit us and we therefore don't use it.

> I was able to install it via the "manual" procedure, but no non-engineer would be able to do so.

Correct, it isn't for the average user, our documentation warns for that on multiple places. However, we have users that still want to use it that way, which is fine and thus documented as such.

> But it has issues: no supervisor for one. How do I install the supervisor? Why there is no supervisor?

Correct, it is documented as such as well. Didn't you see/read: <https://www.home-assistant.io/installation/#compare-installation-methods> ?

> The RPi Imager has its own Homeassistant install, which method is that? Shouldn't that be the default, sanctioned method? If not, why it is even present there?

That is not our project. The installation provided there would be the Home Assistant Operating System. It isn't the default, as it is not our project; additionally; it would only apply/work for Raspberry Pi's, while we support more devices.

> HaOS is what?

Our embedded operating system.

>  I can't mount the SD card.

Ok 🤷

> . I can't apparently set up WiFi without physical access to the RPi. Docs say "Home Assistant can work with Wi-Fi, but an Ethernet connection is more reliable and highly recommended." - that's fine and your opinion, but I need WiFi, and WiFi for IoT is now ubiquitous. The install guide does not mention how do to that.

That is correct, you can't set it up with Wi-Fi headless. You can set up Wi-Fi when the system has been set up in the network settings. However, we don't recommend using Wi-Fi (as you already stated).

> There is already a solution for that, even headless, for RPi.

I think you are referring to a specific solution for Raspberry OS. Which is not what we use.
Raspberry Pi OS is a derivative of Debian, while Home Assistant OS is an embedded operating system. The documentation of the Raspberry Pi OS project does not apply to our project.

> You guys are re-inventing the wheel, and in particular on your most common platform, RPi. It seems that everything is a container for you, and that is simply not true.

That is an opinion, sorry you don't share our vision. As for the most common platform, RPi, we are not limited to that platform, thus it is not our sole focus or drive. Everything is a container actually, except for the embedded operating system (HAOS).

> Sorry if this comes as too aggressive, but if you want more people to use your software, you have to fix the installation docs.

Don't worry, having feedback is good! However, it does seems like your comments are driven, based on experiences with using the Raspberry Pi OS, which does not apply to any of this.

**Comment by virgilm** [comment]
Hey, appreciate the point by point reply, even if I don’t agree with it.
Hats off to you!

Just a few more points I’ll try to make, again as feedback, take it for
what it is, an opinion.

1. I understand why you want to use containers, because ppl can run on
other servers; all I’m trying to say is RPi should be a special case for
you, even if it does not fit in the grand “vision”

2. I had trouble doing simple things like: enabling SSH, enabling I2C
because of the choices you made. Once again, solved problems on RPi become
a challenge for no reason. The way to solve them is also questionable IMO,
the USB copy route is so prone to random failures and
untraceable/undebuggable.

3. I have a custom component integration and I’m unable to use the
manufacturer driver/sample code - built for RPi  - because of the OS
choice. And that choice is also the most hardcore possible - is it ResinOS?
Makes it very hard to develop, so really considering moving away from HA.

4. The base OS lacks the most fundamental utilities - a decent prompt, git,
countless others. Sure, it needs to be light, I know. But a process to add
packages to it at least would be appreciated - oh wait, we can’t do that,
because it’s embedded. The best part is that if you go into the home
assistant container, you do have git!! :)

5. VScode support. It's super nice you wrote the VScode add-on for HA. It's extremely helpful and I thank you for that! However, every single developer out there uses VScode as a *remote* editor/debugger. That way it would have your own customization/plugins/code style/etc.... The add-on does not, plus it uses precious resources on the RPi.

Think about my use case and you might find some of the above relevant: ship
a completely stand alone controller based on RPi, WiFi only, with an image
created automatically - via terraform or otherwise.

The developer guide is a tad better, with more details about architecture
and  build process, but it took me a while to even find it.

For my use case, I would like to develop easy, without knowing too much
about HA - I’m just building on top of it and using prebuilt integrations,
and then I can run it anywhere. But you make that process unnecessarily
hard IMO.

Most of the people using an RPi already dabble at least in programming RPi
to some level, you are changing everything for them.

The choices you make for an user of HA are probably the right ones, but as
a developer for HA on RPi, you are making it unnecessary hard.

That, combined with the constant breakages in upgrades, the UI-first
approach - never seen that work - may come back to bite this community.

Wishing you luck in your mission/ journey!
