### ISSUE TITLE
Why can't buttons be created manually?

### ISSUE THREAD

**Issue by jerblack** [home-assistant/home-assistant.github.io#20700]
### Feedback

Why can't buttons be created manually? Will we not ever be able to create Template Buttons like we can create Template Switches today? I'd like to be able to create buttons to trigger automations without having to fake a state like I do today with Template Switches.

### URL

https://www.home-assistant.io/integrations/button/

### Version

2021.12.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by emontnemery** [comment]
This will most likely be included in the next release: https://github.com/home-assistant/core/pull/61908
