### ISSUE TITLE
Group definition needs making clearer

### ISSUE THREAD

**Issue by boomam** [home-assistant/home-assistant.github.io#20716]
### Feedback

Hi,
The definition of "groups" in the context of lights needs to be made clearer - 
Other areas of the documentation references groups as in 'groups of devices', whereas the wording here references "groups" in the context of lights only, needing to go to a different config file (if splitting out), than groups.yaml.
Fully understanding the reference to "light:", however for clarity I would suggest adding a note to explicitly state that it cannot go within the "group:" section as its not the same 'type' of group - make it a little more idiot proof effectively.

Thinking wider, this could actually be something worth doing for all documentation variables - link back to the split out doc and specify what can be split out where, in each variables documentation page for clarity.

Thanks!

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2021.12.2

**Comment by boomam** [comment]
This requires response and categorization by the development team. No further activity can be added from my part other than adding this note to keep it alive.

**Comment by 404ClickBait** [comment]
I agree with the feedback.  I see the term "group" appear in the example config but no explanation of it so I don't understand what it's meaning is.  Is it a keyword that is fed to the "platform" term?  Is it a name for this specific instance of the "platform"?  What is "platform"?

**Comment by boomam** [comment]
This requires response and categorization by the development team. No further activity can be added from my part other than adding this note to keep it alive.

**Comment by frenck** [comment]
The group documentation has been revised.

<https://www.home-assistant.io/integrations/group>
