### ISSUE TITLE
vallox.set_profile' is superseded by the 'fan.set_preset_mode' service

### ISSUE THREAD

**Issue by iothub-dev** [home-assistant/home-assistant.github.io#20711]
### Feedback

Logger: homeassistant.components.vallox
Source: components/vallox/__init__.py:206
Integration: Vallox (documentation, issues)

Attention: The service 'vallox.set_profile' is superseded by the 'fan.set_preset_mode' service. It will be removed in the future, please migrate to 'fan.set_preset_mode' to prevent breakage

### URL

https://www.home-assistant.io/integrations/vallox/

### Version

2021.12.2

**Comment by andre-richter** [comment]
This is not a bug.

This is a public service announcement that tells you that you are using a service API (`vallox.set_profile`) that will soon be removed, and that you should start using `fan.set_preset_mode` instead. It will provide the same functionality.

I was hoping this is self-explanatory. How did you understand the message?

**Comment by iothub-dev** [comment]
Hi Andre, I understand it similarly. Just a note that Vallox is updating APIs. Allez gut.  Br, Mika17.12.2021 15.27 Andre Richter ***@***.***> kirjoitti:
This is not a bug.
This is a public service announcement that tells you that you are using a service API (vallox.set_profile) that will soon be removed, and that you should start using fan.set_preset_mode instead. It will provide the same functionality.
I was hoping this is self-explanatory. How did you understand the message?
