### ISSUE TITLE
Device Tracker, known_devices.yaml being replace with?

### ISSUE THREAD

**Issue by ghayes7** [home-assistant/home-assistant.github.io#20715]
### Feedback

The device tracker page mentions:
> As of 0.94 known_devices.yaml is being phased out and no longer used by all trackers. Depending on the integration you use this section may no longer apply. This includes OwnTracks, GeoFency, GPSLogger, Locative and Huawei LTE.

But makes no mention of what known_devices.yaml is being phased out in place of.

### URL

https://www.home-assistant.io/integrations/device_tracker/

### Version

2021.12.2

**Comment by frenck** [comment]
With nothing; hence there is no mention of anything either.
