### ISSUE TITLE
Ikea motion sensor doesn't work / not recognized in ZHA

### ISSUE THREAD

**Issue by vdbosch** [home-assistant/home-assistant.github.io#20727]
### Feedback

There is written: The TRÅDFRI Shortcut button, Remotes and motion sensor only send information about their battery status, no events, to Home Assistant and thus can’t be used to automate with. If you want to automate with these devices, you need to use something like ZHA.

ZHA is according me a wrong example, the Ikea motion sensor is not recognized at all in ZHA.
I would remove ZHA as example!

### URL

https://www.home-assistant.io/integrations/tradfri/

### Version

2021.12.2

**Comment by frenck** [comment]
Every solution can provide pros and cons. This includes device support. I honestly do not agree that this (relatively) recent device missing support, is a reason not the list it.

Nevertheless, thank you for providing feedback, that is always appreciated. 👍

**Comment by vdbosch** [comment]
I just wanted to inform that the IKEA sensor doesn’t work with ZHA  (while the impression is given that it will work with ZHA, this info gives confusion, could be helpful for other users)

That’s all!
