### ISSUE TITLE
Sensor bug. Cant track energy. 

### ISSUE THREAD

**Issue by crackers81** [home-assistant/home-assistant.github.io#20729]
### Feedback

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2021.12.2

**Comment by frenck** [comment]
Hi there @crackers81 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
