### ISSUE TITLE
MAP Card

### ISSUE THREAD

**Issue by onslope** [home-assistant/home-assistant.github.io#20733]
### Feedback

Hey, nice card to get entity positions on.
Is there possibility to get time stamps on the location points being shown on the map?
When a position is taken, an option to show the time at that point would be great. Also address could be optional.
Take care

### URL

https://www.home-assistant.io/lovelace/map/

### Version

2021.12.2

**Comment by frenck** [comment]
Thank you for reaching out. We use this GitHub for tracking documentation feedback/suggestions, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
