### ISSUE TITLE
Xiaomi Integration

### ISSUE THREAD

**Issue by MichaelRV82** [home-assistant/home-assistant.github.io#20736]
### Feedback

Retrying setup: {'code': -9999, 'message': 'user ack timeout'}

receiving above error for the Xiaomi Integration. Did not find anything in the documentation.

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2021.12.2

**Comment by frenck** [comment]
Hi there @MichaelRV82 👋 

It seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix such issues 😉 

Please report integration issues here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
