### ISSUE TITLE
Where

### ISSUE THREAD

**Issue by luxpistol** [home-assistant/home-assistant.github.io#20730]
### Feedback

Where does this information go in Home Assistant?

### URL

https://www.home-assistant.io/integrations/habitica/

### Version

2021.12.2

**Comment by leikoilja** [comment]
@luxpistol, i do not have Habitica integration setup now, but have you checked under `sensors`? You can go into `Dev Tools` and try seeing them there, where all states of sensors are. But please make sure that you HA logs have no error related to `habitica`, that would prevent sensors to be created

**Comment by frenck** [comment]
When you've set it up, you can go to "Devices & Services" in the configuration screen.

[![Open your Home Assistant instance and show your integrations.](https://my.home-assistant.io/badges/integrations.svg)](https://my.home-assistant.io/redirect/integrations/)

From there, you can click on the Habitica card that as links to e.g., the devices and entities it provides.
