### ISSUE TITLE
This example does not work

### ISSUE THREAD

**Issue by d1964b** [home-assistant/home-assistant.github.io#20741]
### Feedback

The example given above for describing how to trigger an event at sunset does not work.

### URL

https://www.home-assistant.io/getting-started/automation/

### Version

2021.12.3

**Comment by frenck** [comment]
Seems to be fine by me? Did you experience some kind of error?

**Comment by d1964b** [comment]
No I did not get an error , it's just the automation was not triggered. In the end I modified the 'state' trigger to check if the 'sun' entity was 'below_horizon' . This does what I needed it to do. I checked my location on the map in 'General Configuration' and that is correct as is my timezone. If there is anything else that I can check or anything the 'sun' trigger needs as a prerequisite for 'sunset' to work then  let me know and I'll check. Thanks

**Comment by frenck** [comment]
The example should work, as in, the example is not incorrect.

If you suspect a bug, please file one with a reproduction scenario.
