### ISSUE TITLE
Simple mqtt provider for 125kHz RFID readers

### ISSUE THREAD

**Issue by weekends** [home-assistant/home-assistant.github.io#20746]
### Feedback

May some one interesting to attach RFID readesr, like R20XD-USB, to HA. I'm wrote simple provider for that.

[rfid2mqtt.py.gz](https://github.com/home-assistant/home-assistant.io/files/7739322/rfid2mqtt.py.gz)

### URL

https://www.home-assistant.io/integrations/tag/

### Version

2021.12.3

**Comment by frenck** [comment]
Thanks for that information, however, that is not really related to the Home Assistant integration provided here.

Nevertheless, thanks for sharing 👍
