### ISSUE TITLE
Please include instructions for adding a device after initial configuration

### ISSUE THREAD

**Issue by JDIacobbo** [home-assistant/home-assistant.github.io#20747]
### Feedback

This documentation does not outline how to add a nest device after the initial setup. After reaching out for support, it appears that the proper method is to delete the integration and readd it to get the new devices to appear. This would be nice to have included in the official documentation.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.12.3

**Comment by frenck** [comment]
> This documentation does not outline how to add a nest device after the initial setup. 

That sounds incorrect and more like a bug. Re-adding an integration is not a correct solution to anything. Please raise an issue on our Core integration instead.

https://github.com/home-assistant/core/issues

Thanks! 👍 

../Frenck

**Comment by JDIacobbo** [comment]
This is what I was told to do by @allenporter in the support Discord. I just want to make sure that this is incorrect before I open another issue.

EDIT: Opened https://github.com/home-assistant/core/issues/62275

**Comment by allenporter** [comment]
@frenck the reason why is during the oauth flow you grant access to specific devices. If you get a new device, you have to also grant access to it explicitly. I need a good way to trigger reauth somewhere.
