### ISSUE TITLE
Nest integration documentation, instructions contain 3 issues that I had to overcome in my environment. 

### ISSUE THREAD

**Issue by mahawana** [home-assistant/home-assistant.github.io#20757]
### Feedback

Hello, from the get go, let me say that this Nest interface was complex for me, since I was not familiar with concepts of creating a project for the API, and to use the flow of authentication, and variety of clients configurations. the biggest struggle I found is keeping the word "project" in perspective. So, my feedback below could be colored by my ignorance of these new subjects. 
However, I could tell you that I was eventually successful in integrating Nest Thermostat, only by doing the modification below. 
(FYI, my environment is using a laptop, with virtual machine running HA on LInux). 

While I committed a couple of mistakes in following the instructions, I fixed those, but the real problems for me were the 3 errors that I found in the documentation (if the document worked for other people as is, then perhaps the document is questionable and did not account for my environment for some reason. So,  I had to deviate from the instructions). Here are the 3 Items in the documents are I had to deviate from: 
    1) In section "configure Oauth Client_id and client_secret"…the document recommends to use "desktop App". I could not get that work and I kept seeing an error message when I tried to configure the integration.  To get it to work, I used the "web App" auth instead. This "web app" auth will give you the option to specify the "uri" (being the external site address of HA).  

  2) The section titled Configuration, The document recommends to NOT include subscriber_id in the configuration.yaml. However, after reboot the HA would clearly report a message in the log file indicating that "subscriber_id is required ". and if you ignore the error, and try to invoke the integrations, you'll get an abort message. So, you have to add the "subscriber_id" in the yaml file.
 
  3) The document does not mention how to create a subscription. Which is now required to be filled (as I mentioned in previous bullet).  To do that I followed the instructions on this site to get a subscription and then use its name as a "subscribor_id" to be used in configuration.yaml file. 
         https://maartendamen.com/ha-nest-sdm/

Thank you for taking my comments into consideration.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.12.3

**Comment by allenporter** [comment]
Your issues are because the documentation is always for the latest version of home assistant and you are running an older version.  Upgrade to `2021.12`.

**Comment by allenporter** [comment]
See https://www.reddit.com/r/homeassistant/comments/qv9ywk/nest_integration_updates/ for context
