### ISSUE TITLE
Weirdly Integration has stopped working. Every time I try to login it says "failed to connect." Any chance you can fix?

### ISSUE THREAD

**Issue by jdisom013** [home-assistant/home-assistant.github.io#20754]
### Feedback

Weirdly Integration has stopped working. Every time I try to login it says "failed to connect." Any chance you can fix?

### URL

https://www.home-assistant.io/integrations/smart_meter_texas/

### Version

2021.12.3

**Comment by Azimuth0r** [comment]
I'm new to Home Assistant, just tried on a new install and got the same message.

**Comment by rmeals** [comment]
Same here. I can login through the SMT website: https://www.smartmetertexas.com/home

**Comment by itsethamphetamine** [comment]
Wanted to bump this up. I also am able to login via the SMT website: https://www.smartmetertexas.com/home. When attempting authentication via the plugin I get a Failed to Connect.

**Comment by frenck** [comment]
Hi there @Azimuth0r and @itsethamphetamine 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. We cannot "fix" things like this by changing documentation :)

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
