### ISSUE TITLE
Does this really work? 

### ISSUE THREAD

**Issue by vyagi** [home-assistant/home-assistant.github.io#20751]
### Feedback

The example provided does not seem to work. The messages send from presentation function work and values show up in the Home Assistant entity state. However, when sent from the loop does not hit Home Assistant or are not processed.
This works
`

    #define LIGHT_CHILD_ID 1
    MyMessage lightLevelMessage(LIGHT_CHILD_ID, V_LIGHT_LEVEL);

    void presentation() {
      sendSketchInfo("Arduino controller", "1.0");

      present(LIGHT_CHILD_ID, S_LIGHT_LEVEL);
      send(lightLevelMessage.set(58), true); //example value, shows up in the Home Assistant
    }`

This does not work:

`  

    void loop() {
      send(lightLevelMessage.set(12), true); //example value to see if changes in Home Assistant but it doesn't
    }`

### URL

https://www.home-assistant.io/integrations/sensor.mysensors/

### Version

2021.12.3

**Comment by MartinHjelmare** [comment]
The code provided doesn't match any of the examples at the linked url. It's hard to know what's wrong without seeing the complete sketch.

Did you try the complete example sketch for your version of gateway as is?
