### ISSUE TITLE
Philips Hue Integration page incorrectly states "Local Push"

### ISSUE THREAD

**Issue by Vorta** [home-assistant/home-assistant.github.io#20750]
### Feedback

Philips Hue integration page states "Its IoT class is **Local Push** and scores **platinum** on our quality scale."
This has been in the documentation for a while but it is still not true. The Hue integration still uses **Local Polling** in intervals of 1 second.

Tested with core-2021.12.3 while listening for a hue_event in Developer Tools. Video attached.
I'm using the Philips hue V2 bridge (BSB002), Firmware: 1.48.1948086000.

Platinum quality scale is also incorrect, as the integration is not super fast and if there is more than one event that happens on a device between pollings, it will be dropped.

The documentation should reflect the actual state, not a possible future state.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2021.12.3

### Additional information

https://user-images.githubusercontent.com/179685/146653245-4f1e6d8c-7158-4dae-9b3f-b050061229ea.mp4

**Comment by frenck** [comment]
Hue uses an event stream and actually is push based... the documentation is correct.

You might experience a bug, for which this is not the correct issue tracker, please file an issue in the core issue tracker instead.
