### ISSUE TITLE
Customizing Entities - Adding actionable information to the warning at the bottom of the page

### ISSUE THREAD

**Issue by h-parks** [home-assistant/home-assistant.github.io#20768]
### Feedback

I recently had an issue where I could not easily update the state of a binary sensor I wanted to customize. 

Adding a sentence to the warning at the bottom of this page may help users. In context, the warning text would display as:

New customize information will be applied the next time the state of the entity gets updated. Use the service [`homeassistant.update_entity`](https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantupdate_entity) to do this manually. 

### URL

https://www.home-assistant.io/docs/configuration/customizing-devices/

### Version

2021.12.3

**Comment by balloob** [comment]
This UI has been removed in 2021.12
