### ISSUE TITLE
Button Example YAML

### ISSUE THREAD

**Issue by bakerbug** [home-assistant/home-assistant.github.io#20767]
### Feedback

I'm trying to implement my first button, but I'm not getting the YAML config right.

I'm assuming the config would look like:
`button:
  battery_monitor:
    name: Battery Monitor`

But the configuration checker does not like it.

Could an example be added to the documentation page?

### URL

https://www.home-assistant.io/integrations/button/

### Version

2021.12.3

**Comment by frenck** [comment]
You can't configure a button entity.

See also the documentation:

![image](https://user-images.githubusercontent.com/195327/146686951-89ac75c8-1d49-4352-8cf2-78b54ee9e9c6.png)

**Comment by emontnemery** [comment]
It's in the works though, and will land in the next Home Assistant Core release:
- Template button: https://github.com/home-assistant/core/pull/61908
- Input button: https://github.com/home-assistant/core/pull/62008
