### ISSUE TITLE
Link device by app account

### ISSUE THREAD

**Issue by jmporter34** [home-assistant/home-assistant.github.io#20761]
### Feedback

The top of the page states "The Tuya integration integrates all Powered by Tuya devices you have added to the Tuya Smart and Tuya Smart Life apps.". 

Step 3 under "LINK DEVICES BY APP ACCOUNT" says "Scan the QR code that appears using the Tuya Smart app or Smart Life app."; it also shows a screenshot from Tuya IoT that mentions both apps.  When I get to step 3 on Tuya IoT, it says "Please scan the QR code with Smart Life App to authorize".  No mention of Tuya there.  Is the Tuya Smart app no longer supported ?  I tried scanning the code with Tuya Smart app but it wouldn't read it.  
Thinking maybe this will only work with the Tuya Smart Life app, I went back to the Apple store to download the Tuya Smart Life app.  There are several apps that include variations of Smart Life in their names, but none of them are by Tuya.  There is no "Tuya Smart Life" app, at least on the Apple store.  I'm thoroughly confused.

Update on QR: I tried scanning the QR from the Tuya Smart app on a different mobile device.  This time it scanned, then a screen popped up with "Logging in xxxxx, please make sure it was you.", where xxxxx was a bunch of characters in what appears to me to be Chinese.  Is this expected ?

BTW, earlier on the same page, step 4 under "CREATE A PROJECT" points to a list of data centers (https://github.com/tuya/tuya-home-assistant/blob/main/docs/regions_dataCenters.md).  When I went there, the entire US is pointed toward "Western America Data Center".  But the Tuya IoT also offers "Eastern America Data Center".  Is that new ?  Should I be using that since I'm in the eastern US ?

Thank you

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.12.3

**Comment by frenck** [comment]
Updated title, as it seemed like your capslock was stuck there @jmporter34 😉

**Comment by jmporter34** [comment]
Sorry, I copy/pasted from the section header of the web page (which is all caps) right into the issue title.  I should have spent 10 extra seconds and re-typed it with normal case :-)
