### ISSUE TITLE
State class for weekly_net_production is incorrect

### ISSUE THREAD

**Issue by dolfs** [home-assistant/home-assistant.github.io#20773]
### Feedback

I get messages in the logs like these: "Entity sensor.weekly_net_production from integration sense has state class total_increasing, but its state is negative."

This sensor, since it tracks "net" production. There are times when solar production is > home_consumption and thus there is excess energy pushed back to the grid, and vice versa. Consequently "sensor.weekly_net_production" can both increase and decrease over time.

Expected: Its device class should be changed to reflect this so that the error disappears from the logs.

### URL

https://www.home-assistant.io/integrations/sense/

### Version

2021.12.3

**Comment by frenck** [comment]
Hi there @dolfs 👋 

It seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with an integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
