### ISSUE TITLE
State still shows as "sunny" at night

### ISSUE THREAD

**Issue by tejasitraj** [home-assistant/home-assistant.github.io#20771]
### Feedback

The state of the smhi weather entity shows as "sunny" even at night. Home Assistant does support the "clear-night" state as well, would it be possible to set the state to that instead, when it is after sunset? 

### URL

https://www.home-assistant.io/integrations/smhi/

### Version

2021.12.3

**Comment by frenck** [comment]
Hi there @tejasitraj,

Not sure, but you have submitted documentation feedback. What is you documentation suggestion in this? Sounds to me like a feature request instead?

If so, please use our community forums instead.

../Frenck

**Comment by tejasitraj** [comment]
Hey @frenck 
My apologies, didn't mean to submit documentation feedback, will close this now. Love the work that you guys do, truly world changing stuff!
