### ISSUE TITLE
Scene: Activate vs scene.turn_on in Dev Tools

### ISSUE THREAD

**Issue by GrizzlyAK** [home-assistant/home-assistant.github.io#20775]
### Feedback

As a new scene user, I found the docs and Services Tab in Dev Tools created some confusion because the scene.turn_on service call is named Scene: Activate in the dropdown (although it _does_ show scene.turn_on beneath it). Initially, I found myself looking for both of them as separate items/commands, before I realized they were the same. There is, I believe, no mention of Scene: Activate on the Scenes Docs page, but only in the Dev Tools Drop-down.

Just an observation.

### URL

https://www.home-assistant.io/integrations/scene/

### Version

2021.12.3

**Comment by emontnemery** [comment]
The documentation which you link to says:
![image](https://user-images.githubusercontent.com/14281572/146895779-8b1ced63-6ec6-4745-a7cf-a10fe48fa417.png)

That seems clear and well aligned with the developer tool.
Closing this, please comment or reopen if you don't agree 👍
