### ISSUE TITLE
Blueprint conventions

### ISSUE THREAD

**Issue by Wagoneermaster007** [home-assistant/home-assistant.github.io#20792]
### Feedback

All variables in the blueprints are called inputs. (!input). But it would be more logical to have inputs and outputs. Inputs will be the triggering part where outputs would represent the action parts.  That would be the output of the automation. (I am used to working with industrial automation PLC's, where the naming convention seems to be more logical. 

### URL

https://www.home-assistant.io/docs/blueprint/tutorial/

### Version

2021.12.4

**Comment by frenck** [comment]
Blueprint have no outputs...
Values are only put in, nothing comes out.

Nevertheless, thanks for your suggestion.
