### ISSUE TITLE
Nuki Integration doesn´t work

### ISSUE THREAD

**Issue by fakorte** [home-assistant/home-assistant.github.io#20796]
### Feedback

I can enter the IP address and the token and it then also says "successful". I then see an empty field in the integrations. It recognizes the correct ID, but no entities are displayed.

### URL

https://www.home-assistant.io/integrations/nuki/

### Version

2021.12.4

**Comment by frenck** [comment]
Hi there @fakorte 👋 

It seems like you want to report an issue with an Home Assistant integration, or are in need of support, either way, you have submitted documentation feedback instead.

Please report issues with integrations here:
<https://github.com/home-assistant/core/issues>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
