### ISSUE TITLE
Feature request: add support for Unifi SmartPower Plug

### ISSUE THREAD

**Issue by kerhbal** [home-assistant/home-assistant.github.io#20814]
### Feedback

UniFi SmartPower Plug can be turned on or off in Unifi settings. It would be wonderful if this integration can control it. Thanks!

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2021.12.4

**Comment by Kane610** [comment]
That can be done, but this is the wrong repo to request this. Please file a request here https://github.com/Kane610/aiounifi, Im gonna need some support with data to send and control the switch as well.

**Comment by Kane610** [comment]
FYI support for outlets have been merged https://github.com/home-assistant/core/pull/64859

If you have the possibility I'd appreciate it if you could try out dev or the beta to flush out any issues

**Comment by kerhbal** [comment]
@Kane610 thanks! yeah I'll try it this week.
