### ISSUE TITLE
Add section about using secrets for add ons configuration

### ISSUE THREAD

**Issue by guillaumemolter** [home-assistant/home-assistant.github.io#20818]
### Feedback

A lot of add-ons (including official ones) require the use of usernames, passwords and other credentials in the configuration tab.

1. The documentation doesn't make it clear if yes or no secrets are supported in add-ons configuration.
2. The regular syntax for secret doesn't seem to work out of the box. After doing some research it seems (according to [this thread](https://community.home-assistant.io/t/secrets-yaml-with-addons/83699/5) ) that you need a different syntax using single quotes.

Please consider adding a section to the secrets documentation that addresses the 2 points above.

### URL

https://www.home-assistant.io/docs/configuration/secrets/

### Version

2021.12.4

**Comment by frenck** [comment]
While it kinda works for some things, the cases in it works are currently limited (and thus not consistent). Which is sort of the main reason for missing it in the documentation.
