### ISSUE TITLE
Sonos Tidal

### ISSUE THREAD

**Issue by r100gs** [home-assistant/home-assistant.github.io#20819]
### Feedback

I tried to get access to tidal via sonos integration, but don't know which link I should use.

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2021.12.4

**Comment by jjlawren** [comment]
You can use the Tidal link as-is, like "https://tidal.com/browse/album/157273956".

**Comment by r100gs** [comment]
OK. Sorry, everything works finde after restart of  automations
--------------------------------
