### ISSUE TITLE
Should be indicated as deprecated !

### ISSUE THREAD

**Issue by vincegre** [home-assistant/home-assistant.github.io#20826]
### Feedback

The platform that integration works with has been for ever putted offline begin of december so it should be putted in deprecated mode with warning of such status on documentation page of the integration !

### URL

https://www.home-assistant.io/integrations/thethingsnetwork/

### Version

2021.12.4

**Comment by frenck** [comment]
Hi there @vincegre 👋 

Thanks for your documentation feedback, however, deprecations are controlled from code, not our documentation. Please check the issue tracker of Home Assistant for things like this.

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
