### ISSUE TITLE
Button confusion

### ISSUE THREAD

**Issue by cunninr2** [home-assistant/home-assistant.github.io#20820]
### Feedback

The  page is confusing as it seems to suggest that one can now define a button entity, which would assume you define it in the config.yaml, but these is no guidance how to define a button so that it shows up as an entity.

### URL

https://www.home-assistant.io/integrations/button/

### Version

2021.12.4

**Comment by frenck** [comment]
> The page is confusing as it seems to suggest that one can now define a button entity

It explicitly states you cannot:

![image](https://user-images.githubusercontent.com/195327/147145158-a77842f7-af96-4e91-bb72-d8710f089ab2.png)

**Comment by cunninr2** [comment]
Thanks. Don't know how I missed that.

**Comment by frenck** [comment]
No problem 👍
