### ISSUE TITLE
Override Home zone

### ISSUE THREAD

**Issue by cthumerelle** [home-assistant/home-assistant.github.io#20833]
### Feedback

Creating a "Home" zone in the config doesn't override the default Home Zone in my HA.
I'm running the french version so Home is called "Maison" here. 
Creating a "Maison" zone doens't override either. I have two zones at the same place but I can't find a way to verride de default "Home" zone

### URL

https://www.home-assistant.io/integrations/zone/

### Version

2021.12.4

**Comment by frenck** [comment]
Hi there @cthumerelle 👋 

It seems like you want to report an issue with Home Assistant, however, you have submitted documentation feedback instead. Please report issues  with Home Assistant here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
