### ISSUE TITLE
Windows Installation links broken/404

### ISSUE THREAD

**Issue by snowmanninja** [home-assistant/home-assistant.github.io#20832]
### Feedback

Hello, 

the vdi and similar links are failing to launch a download. 
https://www.home-assistant.io/installation/windows

Under the section Download the appropriate image 
https://github.com/home-assistant/operating-system/releases/download/7.0/haos_ova-7.0.vdi.zip returns 404
Dev builds are working via https://os-builds.home-assistant.io/7.0.dev20210920/haos_ova-7.0.dev20210920.vdi.zip

### URL

https://www.home-assistant.io/installation/windows

**Comment by ikifar2012** [comment]
They appear to be working for me

**Comment by frenck** [comment]
Download links work for me too 🤷
