### ISSUE TITLE
Need to Reload Tuya integration every 2nd day

### ISSUE THREAD

**Issue by gnlgrim** [home-assistant/home-assistant.github.io#20838]
### Feedback

Good day

I have a issue with the new Tuya integration with home assistant 
I have successfully made a a cloud project and added it to Home assistant.
I was able to successfully add al my Tuya devices.
Everything works 100% for a while, I would say about a day, then I cannot get the correct status update or control devices.

I then just go into Integration and reload Tuya and everything works perfectly after that. 
Could you please indicate what could be the possible issue

Thank you in advance

Home Assistant 2021.12.4

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.12.4

**Comment by frenck** [comment]
Hi there @gnlgrim 👋 

Seems like you want report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. The issue tracker can be found here:

<https://github.com/home-assistant/core/issues>

Please be sure to check if your issue wasn't reported already before creating a new one.

Thanks 👍 

../Frenck
