### ISSUE TITLE
Truenas core - Home assistant - RFXCOM not working

### ISSUE THREAD

**Issue by doum33** [home-assistant/home-assistant.github.io#20830]
### Feedback

I have an RFXCOM that I am trying to integrate into home assistant.
When I choose Serial connexion, then my device appears like that: /dev/cuaU0 - n/a, s/n: n/a
When I submit it, I got an error:
Logger: homeassistant.components.rfxtrx
Source: components/rfxtrx/init.py:76
Integration: RFXCOM RFXtrx (documentation, issues)
First occurred: 16:04:06 (2 occurrences)
Last logged: 17:05:32

Connection timeout: failed to receive response from RFXtrx device

On configuration.yalm, I added these two lines at the end of the file:
rfxtrx:
device: 
   /dev/cuaU0

I tried manual installation, and automatic installation (with Mybutton integration). The result is the same and it's not working.
Can you help me please?

### URL

https://www.home-assistant.io/integrations/rfxtrx/

### Version

2021.12.4

**Comment by elupus** [comment]
This was reported on the wrong issue tracker. Firstly are you really sure that is the correct device path for your rfxcom device. That looks like a modem. The gui will kust list the serial ports it sees, which doesn't need to be the correct ones.

**Comment by doum33** [comment]
Hi @elupus,
Sorry for the wrong issue tracker.
I am not sure of the port but since the GUI offered it to me I thought that was it.
How can I be sure which usb port the rfxcom is plugged into?

**Comment by doum33** [comment]
I did some tests:

when I try to add rfxcom integration through the GUI having the rfxcom unplugged, I see only 1 line:
‘/dev/cuau0 - n/a, s/n: n/a’

when I try to add rfxcom integration through the GUI having the rfxcom plugged, I see2 lines:
‘/dev/cuau0 - n/a, s/n: n/a’ and ‘/dev/cuaU0 - n/a, s/n: n/a’
It’s why I think rfxcom is on /dev/cuaU0.

Morever, there is a configuration file on Truenas which forwards the tty* ports to the cua* ports.
But what I don’t understand is that the result of dmesg | grep -i ftdi is:

‘uftdi0 on uhub2
uftdi0: on usbus1
uftdi0: at uhub2, port 7 addr 5 (disconnected)
uftdi0: detached
uftdi0 on uhub2
uftdi0: on usbus1’

I don’t understand what is usbus1.
On /dev, I don’t have anything called usbus1.
Does this speak to you?

**Comment by doum33** [comment]
Hi @Danielhiversen, @elupus, @RobBie1221,

I found these informations on home-assistant.log.

`2021-12-27 15:19:11 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [34587733440] Sending {"id": 63, "type": "result", "success": true, "result": {"config_entry": {"entry_id": "e43653312a0f354cf58410bc33dfb59a", "domain": "rfxtrx", "title": "RFXTRX", "source": "user", "state": "setup_error", "supports_options": true, "supports_unload": true, "pref_disable_new_entities": false, "pref_disable_polling": false, "disabled_by": null, "reason": null}, "require_restart": false}}
`

`2021-12-27 15:19:48 DEBUG (Thread-7) [RFXtrx] Recv: 0x08 0x50 0x01 0x46 0xd8 0x00 0x00 0x94 0x59`


I don't see any error, I think I can see the rfxcom is well integrated (it receives an ID successfully). Can you confirm it to me?

**Comment by elupus** [comment]
Maybe. That only indicate it is getting data. But it does look correctish.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
