### ISSUE TITLE
Suggestion, document what "command_timeout" is for shell_command

### ISSUE THREAD

**Issue by rocketmonkeys** [home-assistant/home-assistant.github.io#20853]
### Feedback

> With a 0 exit code, the output (stdout) of the command is used as value. In case a command results in a non 0 exit code or is terminated by the command_timeout, the result is only logged to Home Assistant log and the value of the sensor is not updated.

I can't seem to find documentation on what "command_timeout" is, what it's set to, how to modify it.

I'm guessing it's 60 seconds, judging from behavior I'm seeing.  But is that documented somewhere?  And is it changeable?

### URL

https://www.home-assistant.io/integrations/shell_command/

### Version

2021.12.5

**Comment by mrand** [comment]
Appears to be hard coded to 60, as you suspected:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/shell_command/__init__.py#L18

Feel free to submit a change (pull request, aka PR) to the documentation to help others that might have the same question.  There is a link at the bottom of each documentation page.
