### ISSUE TITLE
friendly name versus alias versus name and file structure key/value versus array

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#20854]
### Feedback

Comparing the yaml files for automation, scripts, scenes and groups they have different structures and different names for same kind of data: 

**Structure at top level:**
key/value: script.yaml, group.yaml, rest_command.yaml
array: automation.yaml, scenes.yaml, template.yaml, 

**Naming:** 
"name": group.yaml, scenes.yaml
"alias": automation.yaml, script.yaml
"friendly_name" in some other files. 

The entity ID is sometimes derived from the key, sometimes from alias/friendly name or generated (number) 

In my opinion it would be easier to have the same pattern everywhere for instance arrays on top level, everywhere friendly_name (instead of "name" or "alias"). 

### URL

https://www.home-assistant.io/docs/automation/

### Version

2021.12.5

### Additional information

Just a feedback. It is not a major thing as the documentation is excellent.

**Comment by frenck** [comment]
Thanks for the suggestion, @hklages 👍 

However, that is not a documentation suggestion (which is what you have submitted).
This is more fitting in the feature request section of our community forums.

Merry Christmas 🎄 

../Frenck
