### ISSUE TITLE
Integration NOT Working for long time and multiple tests

### ISSUE THREAD

**Issue by alerosss** [home-assistant/home-assistant.github.io#20863]
### Feedback

Hi,
I tried more time to Delete and integrate again Rachio without success using the API Key from the Rachio Account Settings.

Can someone help?

### URL

https://www.home-assistant.io/integrations/rachio/

### Version

2021.12.5

### Additional information

Read above

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
