### ISSUE TITLE
Method get - for what / how to "get" the data to process it

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#20864]
### Feedback

Concerning **RESTful command**

How can I use method "GET", I mean to access the response. For what is the get option?

I would like to "get" data every 5 minutes in time from 7:00 to 23:00 and tried to use RESTful command in combination with an automation. But - how to access the data. Any other solution? 

### URL

https://www.home-assistant.io/integrations/rest_command/

### Version

2021.12.5

### Additional information

-

**Comment by frenck** [comment]
Looks like you are in need for support, however, you have submitted documentation feedback instead.

Please use our community forums or Discord chat for support questions. 

Thanks!
