### ISSUE TITLE
Add port number

### ISSUE THREAD

**Issue by JohnMoor** [home-assistant/home-assistant.github.io#20876]
### Feedback

Path option may in some cases need a specific port number of the OTGW.  Providing an example may help users that are not so experienced with HA.

e.g. socket://192.168.111:25238

https://www.home-assistant.io/integrations/opentherm_gw/#path

### URL

https://www.home-assistant.io/integrations/opentherm_gw/

### Version

2021.12.5

**Comment by mvn23** [comment]
The relevant link to the PySerial docs is there. It provides a detailed description of all supported formats and has some examples at the bottom.

Feel free to create a PR if you feel that's insufficient.
