### ISSUE TITLE
Device Status fails in HASS

### ISSUE THREAD

**Issue by askthomas** [home-assistant/home-assistant.github.io#20878]
### Feedback

Status on devices on/off not correct in HASS, 

ex. Lamp is on, but shows off in hass, status ok on tuya app.
when click on on hass, it switche to on than back to off, lamp still on.

When using remote button for/on off sometime need to click 2 time to get it working.

it the same for lamp and power outlett, it all startaed with 2021.12.x version.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.12.5

**Comment by frenck** [comment]
Hi there @askthomas 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Please make sure the issue you want to report, isn't reported already (to prevent creating duplicates).

Thanks 👍 

Happy Holidays 🎄 🎆 

../Frenck
