### ISSUE TITLE
Homekit integration: Additional detail for sensor unit_of_measure

### ISSUE THREAD

**Issue by mwiesenhaan** [home-assistant/home-assistant.github.io#20871]
### Feedback

The documentation is not clear on the unit_of_measure for sensors. If the unit_of_measure is not defined correctly, it is not visible in homekit. It took a fair bit of time to find the correct units of measurement as defined in https://github.com/home-assistant/core/blob/d7ac4bd65379e11461c7ce0893d3533d8d8b8cbf/homeassistant/const.py#L384

Suggested additional comment:
For all sensors, make sure the unit_of_measure is correctly defined as per [LINK ABOVE]. Where necessary use the customize functionality to override the unit_of_measure.

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2021.12.5

**Comment by bdraco** [comment]
Here is the link to edit the docs. 

https://github.com/home-assistant/home-assistant.io/edit/current/source/_integrations/homekit.markdown

Improvements to make it easier to understand would be a nice addition.
