### ISSUE TITLE
YAML style guide for quotes and automation.yaml, scene.yaml, script.yaml

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#20873]
### Feedback

The [yaml style guide](https://developers.home-assistant.io/docs/documenting/yaml-style-guide/) says that " should be the standard quote letter (and inside ') 

`# Good
example: "{{ 'some_value' == some_other_value }}" `

In spite of that automation.yaml, script.yaml and scenes.yaml use ' .

### URL

https://www.home-assistant.io/docs/automation/

### Version

2021.12.5

**Comment by frenck** [comment]
The YAML style guide has been introduced quite recently. We apply it to new contributions. There might indeed still be existing code that needs to be adjusted.

Feel free to open up a PR to help with those existing snippets.

Thanks!

**Comment by hklages** [comment]
Understand. I would love to submit a PR but 
a) those files are generated (when using the interface to modify them) and therefore "deep" inside HA core/critical
b) my Python skills are almost non existing

So lets time solve it.

**Comment by frenck** [comment]
Oh right, you mean in the HA instance. That does Not follow our style guide and never will.

This is because that is how pyyaml generates YAML from Python objects.

The style guide applies to our documentation.
