### ISSUE TITLE
slug of a sensor? 

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#20874]
### Feedback

What does "slug of a sensor" mean? Is it a typo?

![slug](https://user-images.githubusercontent.com/17273119/147444263-10824165-7c7e-425d-814c-10361b30c74e.jpg)

### URL

https://www.home-assistant.io/integrations/template/

### Version

2021.12.5

**Comment by tetienne** [comment]
See https://developer.mozilla.org/en-US/docs/Glossary/Slug

**Comment by frenck** [comment]
This is not a typo.

It would be the desired object ID for this entity (ID).
