### ISSUE TITLE
States page 

### ISSUE THREAD

**Issue by JeeWee65** [home-assistant/home-assistant.github.io#20879]
### Feedback

While reading this I thought the states page would be a good way to see in one instant the states and state changes and I really wanted to see "The current number of stored samples". After some google searches and trying I found out it is deprecated: 
https://www.home-assistant.io/blog/2020/02/05/release-105/#the-old-states-ui-is-now-deprecated

Please up-date this page with an alternative way (if any) to find the number of stored samples and to safe the next guy a lot of time. 

### URL

https://www.home-assistant.io/integrations/trend/

### Version

2021.12.5

**Comment by frenck** [comment]
I don't think you understand what the old states UI entails or is... As it isn't related to anything you say...

Anyways, you are looking for the developer tools:

[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Comment by JeeWee65** [comment]
Thank you and sorry. I really appreciate all the work you and others put into this, thank you!
Sometimes it is very clear and obvious for a person who is working with this daily for some time, it still can be confusing for a newbie trying to find all options and understanding the logic behind it all. 
If I read "States page" (without link) it is not immediately clear it means "state dev tools", so I google for more explanation and to find that page etc.....
