### ISSUE TITLE
review changes in python-openzwave 0.30

### ISSUE THREAD

**Issue by kentcalero** [home-assistant/home-assistant.github.io#2088]
please review changes in python-openzave, cython installation may no longer be required.

python-openzwave 0.3.0-alpha3:

    Fix bug in start/stop in network.

    Fix bug in start/stop in pyozwweb app and tests.

    Add map, scenes to PyOzwWeb

    Add new tests

    Fix some tests for controller commands

   * Finish the archive install : the lib is already cythonized. No
     need to install cython anymore.

   Add a dockerfile
  
   Add a branch for dockering with ptyhon 3

**Comment by robbiet480** [comment]
This issue should be opened in the primary [Home Assistant repository](https://github.com/home-assistant/home-assistant/issues/new), not this one (docs repo).
