### ISSUE TITLE
No possibility to control 

### ISSUE THREAD

**Issue by ATLAIT00** [home-assistant/home-assistant.github.io#20885]
### Feedback

Hi home assistant team, unfortunately with the integration it is not possible to control the temperature of the thermostats. this would be a nice feature. 

### URL

https://www.home-assistant.io/integrations/bosch_shc/

### Version

2021.12.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by ATLAIT00** [comment]
@frenck sorry you are right its a feature request; will post it there! Thank! 👍
