### ISSUE TITLE
compatibility with iPadOS 15.2(19C56)

### ISSUE THREAD

**Issue by wowulavega** [home-assistant/home-assistant.github.io#20888]
### Feedback

The card seems to be not compatible with the Apple ipad OS anymore.
The pointer are not positioned and the graphs are moving to the right side.

### URL

https://www.home-assistant.io/lovelace/gauge/

### Version

2021.12.5

**Comment by frenck** [comment]
This is a bug, fixed in https://github.com/home-assistant/frontend/pull/10992

**Comment by wowulavega** [comment]
what is the issue on that ?

**Comment by wowulavega** [comment]
ahh, thanks.
