### ISSUE TITLE
Clarify what "Cloud Polling" means in the context of the Certificate Expiry integration

### ISSUE THREAD

**Issue by kdknigga** [home-assistant/home-assistant.github.io#20883]
### Feedback

I think the class "Cloud Polling" may be misleading, as the integration doesn't appear to rely on any external services.  While I get that it *could* reach out beyond the local network, I imagine most folks are using this to check local certs, so traffic probably isn't leaving the local network.

### URL

https://www.home-assistant.io/integrations/cert_expiry/

### Version

2021.12.5

**Comment by frenck** [comment]
> I imagine most folks are using this to check local certs

That would be a wrong assumption actually.

This integration is correctly classified.

**Comment by kdknigga** [comment]
@frenck, you seem to have glossed past my main point to address what was essentially an aside.

The general understanding of "cloud" [[1](https://www.investopedia.com/terms/c/cloud-computing.asp)][[2](https://azure.microsoft.com/en-us/overview/what-is-cloud-computing/?cdn=disable)][[3](https://en.wikipedia.org/wiki/Cloud_computing)][[4](https://www.ibm.com/cloud/learn/cloud-computing)][[5](https://www.cloudflare.com/learning/cloud/what-is-the-cloud/)] is that it involves using services provided by some remote third party.  This integration uses no such third party services and thus is incongruent with the standard understanding of what "cloud" means.

Now, if Home Assistant wants to have its own definition of what "cloud" means, I guess that's an option.  I'm not necessarily arguing that Home Assistant's definition should match the mainstream, simply that deviating from the mainstream is confusing if that deviation isn't addressed in the documentation.

Perhaps a note in the integration's documentation would be beneficial.  Something like:

> While this integration's IoT class is categorized as "Cloud Polling", note that this integration relies on no third party services.  The classification is simply due to the integration's ability to generate network traffic that leaves your local network.

I had to dig through the integration source code to verify that it wasn't reaching out to [SSL Labs](https://www.ssllabs.com/) or something similar to examine certificates.  A statement like the above would have made my life easier.  And imagine all of the folks out there who can't read source code.

**Comment by frenck** [comment]
> you seem to have glossed past my main point

I did not, it was invalid in my opinion and the integration is classified correctly.

**Comment by kdknigga** [comment]
You continue to miss my point.  Here it is:

> I'm not necessarily arguing that Home Assistant's definition should match the mainstream, simply that deviating from the mainstream is confusing if that deviation isn't addressed in the documentation.

and

> I had to dig through the integration source code to verify that it wasn't reaching out to SSL Labs or something similar to examine certificates. A statement like the above would have made my life easier. And imagine all of the folks out there who can't read source code.

I don't care if the classification is "right" or "wrong".  I care that it's confusing.

**Comment by frenck** [comment]
Right. I do not share your concern; sorry.
