### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by ivanleovitanza** [home-assistant/home-assistant.github.io#20891]
### Feedback

non vedo il dispositivo nelle integrazioni e molte volte va offline 

### URL

https://www.home-assistant.io/integrations/hisense_aehw4a1/

### Version

2021.12.5

**Comment by frenck** [comment]
Hi there @ivanleovitanza 👋 

I'm sorry, I don't understand the language you used. We only use the English language.

Closing this documentation suggestion for that reason.

../Frenck
