### ISSUE TITLE
TUYA integration works, but...

### ISSUE THREAD

**Issue by phacra** [home-assistant/home-assistant.github.io#20893]
### Feedback

I have a floodlight with motion sensor, and two smart plugs bought at the ACTION store (NL).
I followed the HA. instructions, and it works.  It is not that simple. You have to register to the Tuya app. and add your device(s) there.
The devices work. 
Then you have to register at Tuya developers, to create a project.  Key is to know which datacenter applies to you. 
NL connects to the datacenter in Central Europe, NOT West Europe.
The instructions are good.

The floodlight is visible in HA, but I only can turn it on or off, when the mode is set to "manual" in the Tuya app.
As soon as I change the setting from "manual" to "Sensor" in the TUYA app, I cannot control anything in HA, only see that it is turned off.  
The extra options available in the tuya are: 
-- in Manual mode:
[Turn Light ON or OFF] *** This is the only working option in HA!!
--- all the following options are not available in HA
Manage the brightness
Manage the colortone warm white - Cold white
-- In sensor mode: ** again No control at all. in HA
Change distanse motion detection
Change Sensitivity of the sensor: dark - Evening - Day
Change Full light duration in min and seconds
Change Brightness of the light.
Change Duration of dimmed light
-- Futhermore 
You can get device information,
Virtual ID, 
Your home IP (Internet IP of your router)
MAC address
Timezone info
and signal quality.

SO very disapointing for now.

I'm rather new at HA and started reading about TUYA issues...

Does anyone have a full working controlset in Home assistant?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.12.5

### Additional information

What is the current status for the TUYA integration?

**Comment by frenck** [comment]
Hi there @phacra 👋 

Seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please file issues with integration here:

https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
