### ISSUE TITLE
Does it work with Unifi Protect?

### ISSUE THREAD

**Issue by pcjcos** [home-assistant/home-assistant.github.io#20909]
### Feedback

The integration seems to be focused on the deprecated Unifi Video implementation. Unifi Protect has been around for over a year and there is no mention of it on the page. I don't see the API access key anywhere in the Unifi settings, so I am unsure if this is even possible.

### URL

https://www.home-assistant.io/integrations/uvc/

### Version

2021.12.6

**Comment by klaasnicolaas** [comment]
An integration is coming up specifically for Unifi Protect, I think that's what you're looking for: https://github.com/home-assistant/core/pull/62697

**Comment by frenck** [comment]
The above answer is correct, the uvc integration is not compatible with UniFi Protect. A new integration for that is on route for the next release.
