### ISSUE TITLE
need to standardize raspbian and linux guides

### ISSUE THREAD

**Issue by kentcalero** [home-assistant/home-assistant.github.io#2090]
need to standardize raspbian and linux guides so that they follow the same standards

**Comment by fabaff** [comment]
As there are massive changes under way (https://github.com/home-assistant/home-assistant.github.io/pull/2055) which will move the installation docs to a new folder. Thus we should postpone all work on the installation guide till the new structure is online

**Comment by Landrash** [comment]
@kentcalero If you can be more specific I'll try to standardize them.
Some of the HASSbian things are done after how raspbian does it and the linux things are in many cases more generalized to be supported on more distros.
