### ISSUE TITLE
Detail mDNS Android OS limitations on the Web Server Component's documentation

### ISSUE THREAD

**Issue by HoneyBadger100** [home-assistant/home-assistant.github.io#20904]
### Feedback

On the ESPHome's Web Server Component documentation it is stated the following about accessing the ESP node via mDNS:

"To navigate to the web server in your browser, either use the IP address of the node or use <node_name>.local/ (note the trailing forward slash) via mDNS."

Using mDNS to resolve the ".local" address is feasible with Windows and Apple OS, but when trying to resolve this URL with Android OS with Edge or Chrome browsers, it issues a "DNS_PROBE_FINISHED_NXDOMAIN" error message as mDNS is not supported.

This is an open issue/ limitation on Android platform that has been going on since 2014 and detailed in the links below. To access the node in this case, only with the node's IP address.

Since 2019: https://issuetracker.google.com/issues/140786115?pli=1
Since 2014: https://bugs.chromium.org/p/chromium/issues/detail?id=405925

The request is to highlight the Android limitation on the ESPHome's Web Server Component documentation and that only IP addresses can be used in this case.

Thanks

### URL

https://esphome.io/components/web_server.html?fbclid=IwAR07zRIGYQgqNe1tjWC-N4GJg3eSWFkTb6ZZZuOi323PeSeg8FYqedPcif8

### Additional information

![2021-12-28 15_19_22-ESPHome _ Facebook and 9 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/73803481/147539497-53a6b3c4-d3cd-4eb8-ad1a-6b59830312bc.png)

**Comment by frenck** [comment]
I think you are in the wrong place, this is the Home Assistant project, but your documentation feedback is about the ESPHome project website?

**Comment by HoneyBadger100** [comment]
Tks for the heads up

Closed this topic and raised a new one on ESPHome's - https://community.home-assistant.io/t/detail-mdns-android-os-limitations-on-the-web-server-components-documentation/374099 

Cheers
