### ISSUE TITLE
Customize buttons in Area Card

### ISSUE THREAD

**Issue by Marc-Uberstein** [home-assistant/home-assistant.github.io#20903]
### Feedback

It would be great to customize and/or select specific entities for the area card. 

I have a 2 gang sonoff wall switch but my area card only generates 1 button for both light switches. 

* Would be great if we could select and deselect the found entities.
* additional feature would be to carry over the entiry icon
* maybe add on/off state icon selection for any entity

Thanks

### URL

https://www.home-assistant.io/lovelace/area/

### Version

2021.12.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
