### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by vicfalls** [home-assistant/home-assistant.github.io#20919]
### Feedback

hi,

since Core 2021.12.6 update I have a connection error to all my MC20 devices.

HTTPConnectionPool(host='192.168.xxx.xxx', port=80): Max retries exceeded with url: /YamahaExtendedControl/v1/system/getNetworkStatus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7adc41c0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

### URL

https://www.home-assistant.io/integrations/yamaha_musiccast/

### Version

2021.12.6

**Comment by micha91** [comment]
Are you able to open the access the API using a REST client or your browser? Just try to open this page http://192.168.xxx.xxx/YamahaExtendedControl/v1/system/getNetworkStatus and put the IP of the MusicCast device in there.

**Comment by vicfalls** [comment]
Hi @micha91, I'm not sure why but my whole musiccast system lost connection. I unplugged and plugged each device and it works perfect. Thanks for your hint and reply.
