### ISSUE TITLE
Is it possible to add Lux level?

### ISSUE THREAD

**Issue by hobbyboy** [home-assistant/home-assistant.github.io#20914]
### Feedback

Was curious if the Area card could add the lux level of a lux sensor in the area.

Thanks

### URL

https://www.home-assistant.io/lovelace/area/

### Version

2021.12.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
