### ISSUE TITLE
Config page for appdaemon includes deprecated info

### ISSUE THREAD

**Issue by cogneato** [home-assistant/home-assistant.github.io#2091]
https://home-assistant.io/ecosystem/appdaemon/configuration/

These can be removed?
```
latitude = <latitude>
longitude = <longitude>
elevation = <elevation>
timezone = <timezone>
```

as well as the description on the page for each

**Comment by acockburn** [comment]
I am planning to pull the config info back into the AppDaemon repository for this very reason - I want a single place for the docs so this doesn't happen. I'll make a PR for this when I release AppDaemon v2.0.0

**Comment by Landrash** [comment]
@acockburn Can this one be closed?

**Comment by acockburn** [comment]
Yes, this can be closed now as there are pending changes in this area.
