### ISSUE TITLE
Tuya V2 intergrations

### ISSUE THREAD

**Issue by ingmacc65** [home-assistant/home-assistant.github.io#20922]
### Feedback

With the latest update  of the TUYA integration I have issues with all mi light switches.  When I activated with a botton card, or a toggle it works well, but the toggle return to off in less than 20 secunods, but the ligth still on. I want to know how to fix it
 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2021.12.6

**Comment by frenck** [comment]
Hi there @ingmacc65 👋 

It seems like you want to report an issue with an Home Assistant integrations, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Please search/make sure your issue hasn't been reported already (to avoid duplicate issues).

Thanks! 👍 

../Frenck
