### ISSUE TITLE
AirVisual outdoor node Model

### ISSUE THREAD

**Issue by omron111kz** [home-assistant/home-assistant.github.io#20926]
### Feedback

Looking Documentation it seems that must indoro Unit is supported. How to Connect at outdoor modulo? This One has and password to download data… please let me know

### URL

https://www.home-assistant.io/integrations/airvisual/

### Version

2021.12.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
