### ISSUE TITLE
Error in configuration variable in command line switch

### ISSUE THREAD

**Issue by landaisbenj** [home-assistant/home-assistant.github.io#20925]
### Feedback

Configuration variable for icon is describe with "icon" : https://www.home-assistant.io/integrations/switch.command_line/#:~:text=in%20the%20frontend.-,icon,-template%20(optional)

But, in example or in my test, it's "icon_template".

### URL

https://www.home-assistant.io/integrations/switch.command_line/

### Version

2021.12.6

**Comment by frenck** [comment]
Thanks, @landaisbenj 👍 
Opened up a PR to adjust it.
