### ISSUE TITLE
Missing "currency" in advanced configuration

### ISSUE THREAD

**Issue by rawlk** [home-assistant/home-assistant.github.io#20933]
### Feedback

Currency was added some time ago and is currently used in the energy features of HA. By default, it uses EUR. 

It would be great to add a `currency: `entry in the code block along with a note about where to find currency codes, just like the timezone codes. 

### URL

https://www.home-assistant.io/getting-started/configuration/

### Version

2021.12.6

**Comment by frenck** [comment]
This is documented already:

<https://www.home-assistant.io/docs/configuration/basic#currency>
