### ISSUE TITLE
Explain how to connect to home assistant

### ISSUE THREAD

**Issue by edmcman** [home-assistant/home-assistant.github.io#20931]
### Feedback

After installing home assistant from the docker container instructions, it was unclear how to connect to it.  All I needed was HTTP://ip-address:8123 which I found in the raspberry pi docs.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2021.12.6

**Comment by frenck** [comment]
It is explained?

![image](https://user-images.githubusercontent.com/195327/147671596-90a977c7-ee68-42e8-840b-d7f080778af6.png)

**Comment by edmcman** [comment]
Oops!  I was following the docker-compose instructions.  Maybe copy that to that section?

**Comment by frenck** [comment]
Oh, you are right, it is not in the part!

Good suggestion 👍

**Comment by frenck** [comment]
Opened up a PR to adjust the documentation. Thanks @edmcman 👍

**Comment by sicaboy** [comment]
> It is explained?
> 
> ![image](https://user-images.githubusercontent.com/195327/147671596-90a977c7-ee68-42e8-840b-d7f080778af6.png)

I've no idea who deleted this on onboarding page.
