### ISSUE TITLE
Google home and home assistant cloud integration 

### ISSUE THREAD

**Issue by Travsc** [home-assistant/home-assistant.github.io#20948]
### Feedback

Google and the home assistant cloud integration is not working. I chose the home assistant cloud by nabu from Google app. It prompts me to log in and then to allow which choose. It then displays "Linking your Home Assistant Cloud by Nabu Casa account" after a few seconds it displays "Could not reach Home Assistant Cloud by Nabu Casa. Please try again."
Any idea why this is happening? 

### URL

https://www.home-assistant.io/cloud/

### Version

2021.12.7

**Comment by frenck** [comment]
Hi there @Travsc 👋 

Thanks for reaching out, however, it seems like you are searching for getting support setting up Home Assistant Cloud; Yet you have submitted documentation feedback instead.

Nabu Casa support can be found here:

https://www.nabucasa.com/support/

You could also try joining our [Discord chat server](https://discord.gg/c5DvZ4e); there is a #cloud channel in there that might be of help.

Anyways, you are more likely (and quicker) to get the answer you are looking for in those places.

Thanks! 👍
