### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by highincolorado** [home-assistant/home-assistant.github.io#20947]
### Feedback

The Jinja2 documentation link is broken, "http://jinja.pocoo.org/docs/dev/templates/" takes you a page not found link. Sombody know where it should be pointed?

Thanks

### URL

https://www.home-assistant.io/docs/tools/dev-tools/

### Version

2021.12.7

**Comment by frenck** [comment]
Thanks, @highincolorado 👍 

Opened up a PR to fix it.

**Comment by highincolorado** [comment]
Thanks to you
