### ISSUE TITLE
Custom Effects - SERVICE FLUX_LED.SET_CUSTOM_EFFECT (Brightness)

### ISSUE THREAD

**Issue by TheAlphaLaw** [home-assistant/home-assistant.github.io#20955]
### Feedback

Calling a custom effect defaults at 50% brightness, but cannot be adjusted without stopping the custom effect. Is it possible to add a request for brightness when requesting the custom effect? It is possible in the Magic Home app.

### URL

https://www.home-assistant.io/integrations/flux_led/

### Version

2021.12.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
