### ISSUE TITLE
service rainmachine.start_zone not working

### ISSUE THREAD

**Issue by Sambachu** [home-assistant/home-assistant.github.io#20958]
### Feedback

service rainmachine.start_zone not working:

  alias: Test Script
  sequence:
  - service: rainmachine.start_zone
    target:
      entity_id: switch.watermachine_back_bamboo
    data:
      zone_run_time: 600
  mode: single

Click on run script - "Triggered Test Script"
Nothing happens on the Rain Machine

Also tried:

  alias: Test Script
  sequence:
  - service: rainmachine.start_zone
    data:
      zone_run_time: 600
    target:
      device_id: a5436aafc7e4e37b7725b3861036daef
      entity_id: switch.watermachine_back_bamboo
  mode: single

Click on run script - "Failed to call service script/1640957823942. Service not implemented for this entity"

Have also tried calling the zone as a awitch:

  alias: Test Script
  sequence:
  - service: switch.turn_on
    target:
      entity_id: switch.watermachine_back_bamboo
  mode: single

This does work, but with an arbirtrary watering time (10 mins).

Tried adding zone_run_time to the above:

  alias: Test Script
  sequence:
  - service: switch.turn_on
    target:
      entity_id: switch.watermachine_back_bamboo
    data:
      zone_run_time: 600
  mode: single

Click on run script - "Failed to call service script/test. extra keys not allowed @ data['zone_run_time']"

### URL

https://www.home-assistant.io/integrations/rainmachine/

### Version

2021.12.7

**Comment by bachya** [comment]
I just tried this in 2021.12.7 and it worked correctly:

```yaml
service: rainmachine.start_zone
target:
  entity_id: switch.landscaping
data:
  zone_run_time: 100
```

With starting/stopping zones, you provide the zone entity ID to the service call.

Also, indention in YAML matters; I'm unclear if you formatting your service call as you've posted here, so make sure.

**Comment by Sambachu** [comment]
Thanks for that - still not working, though no errors, just doesn't start (I have double checked the indentation etc).
There must be an issue elsewhere,  possibly in my rain machine - I will try to hunt it down.

I really appreciate you testing this for me.

Cheers,
Sam

**Comment by bachya** [comment]
@Sambachu Keep me posted on what you find; happy to keep helping!

**Comment by bachya** [comment]
Fixed via https://github.com/home-assistant/core/pull/64213.
