### ISSUE TITLE
Provide example if YAML is in group.yaml

### ISSUE THREAD

**Issue by UngluedChalice** [home-assistant/home-assistant.github.io#20953]
### Feedback

I'm just getting into Home Assistant so I'm trying to follow the best practice of not putting everything in the `configuration.yaml` file. However, so much of the documentation has only examples for the YAML in the `configuration.yaml` file, so if I try to copy this into the appropriate `.yaml` file, it often does not work without me randomly guessing and testing to see what works. 

### URL

https://www.home-assistant.io/integrations/notify.group/

### Version

2021.12.7

**Comment by frenck** [comment]
> so I'm trying to follow the best practice of not putting everything in the configuration.yaml

Which best practice is that?

Anyways, this does not belong or will work in the default "groups.yaml" file, so the documentation seems correct to me.

Am I missing something?

**Comment by UngluedChalice** [comment]
No, I'm sure I'm the one that is missing something! I just thought while you can put sensors, switches, groups, scenes, and scripts in the main configuration file, you can keep things more organized and neater if you put those things in their own .yaml files. That's what I was referring to as a "best practice." Like I said, I'm just getting starting!

Thanks for all your work with this!
