### ISSUE TITLE
Parsing

### ISSUE THREAD

**Issue by lasseDahl** [home-assistant/home-assistant.github.io#20962]
### Feedback

Information about how to parse the entity object would be valuable. Based on the current information the entity object can only be used directly as a "information-card" and the data cannot be directly be used for automation

### URL

https://www.home-assistant.io/integrations/met/

### Version

2021.12.7

**Comment by frenck** [comment]
As far as I am aware, weather entities can be used directly. Maybe I am not understanding the point you are trying to make?

Could you clarify what you are looking for with an example maybe?

**Comment by lasseDahl** [comment]
Hi Franck, Only one entity is available after adding this integration to HA
and the contents show up like the attached entity information. How can I
access e.g. only the wind strength? (How to access each parameter is what I
mean with parsing information)
[image: met.png]
BR
Lasse



fre. 31. des. 2021 kl. 17:47 skrev Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
Those are entity attributes, most automation options allow you to access to attributes.

That is not specific to this integration

**Comment by lasseDahl** [comment]
OK, thanks. The purpose with my feedback is to add info like you gave me
now to the doc page "https://www.home-assistant.io/integrations/met". E.g.
with a list of attributes and examples on how to access the attributes

BR
Lasse

fre. 31. des. 2021 kl. 17:58 skrev Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
As that is not specific to that integration, I think that is not the right place. If you want to learn/read about how to make automations, please consult that part of the documentation instead
