### ISSUE TITLE
How to update/keep blueprints up to date?

### ISSUE THREAD

**Issue by richardwonka** [home-assistant/home-assistant.github.io#20964]
### Feedback

Hi there,

I’m wondering how I can make sure my blueprints got all the recent fixes/changes from upstream and are up to date. 

I couldn’t find information on this in blueprint docs and suspect, it would be worth mentioning. 

### URL

https://www.home-assistant.io/docs/automation/using_blueprints/

### Version

2021.12.7

**Comment by frenck** [comment]
There is no update mechanism, hence there is no information on it.

**Comment by richardwonka** [comment]
So I’d re-import the blueprint, I guess, Right?
