### ISSUE TITLE
Easyfire not answering on por 23

### ISSUE THREAD

**Issue by reivilob** [home-assistant/home-assistant.github.io#20963]
### Feedback

Hi

I try to do an integration of my new Easyfire with HA but it seems not answering by telnet port 23 (simple telnet in a shell)

(Ping is ok and connection between my Easyfire with comfort-online.com is also ok)

Any idea ?
This access should be allowed by the installer or reserved for WIP ?

### URL

https://www.home-assistant.io/integrations/kwb/

### Version

2021.12.7

**Comment by frenck** [comment]
I am confused, what is your documentation feedback for the linked integration?

That integration seems to do serial communications, not ip based.

**Comment by bimbar** [comment]
Hi,

I wrote the integration.

the Easyfire itself is not IP / telnet capable. It has a RS485 serial console that can be used to connect a serial to telnet converter, then you can use telnet to access it, for example like this one: https://www.amazon.de/usr-tcp232-410S-RS485-seriell-Ethernet-Konverter-Unterst%C3%BCtzung/dp/B07C1TC165/ref=sr_1_5?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1I02F57YG3ID7&keywords=rs485+ip&qid=1643472248&sprefix=rs485+ip%2Caps%2C87&sr=8-5 .

**Comment by reivilob** [comment]
I am now able to retrieve all the necessary informations i need from my Easyfire:
I use modbus TCP directly, without any dongle ... 
Modbus TCP should just be activated on the KWB, and the KWB restarted completelly !
I published my yaml here:
https://github.com/reivilob/HA-KWB-Easyfire
and just add in your configuration.yaml: 
modbus: !include kwb.yaml
