### ISSUE TITLE
Is it possible to integrate multiple icloud accounts with this integration?

### ISSUE THREAD

**Issue by vineetg** [home-assistant/home-assistant.github.io#20977]
### Feedback

I'd like to integrate my phone, along with my wife's iCloud account with this integration. I haven't looked into the source, but is it something possible?

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2021.12.7

**Comment by frenck** [comment]
Yes, most integrations can be added multiple times with different configuration settings.

**Comment by Quentame** [comment]
It is possible, just try it 😉
