### ISSUE TITLE
Possible missleading wind-speed unit

### ISSUE THREAD

**Issue by lasseDahl** [home-assistant/home-assistant.github.io#20989]
### Feedback

I noticed that the wind-speed which show up in home assistant did not match what yr.no says, and it seems that the error factor is 3,6. The "wind_speed" unit seem to be km/hour but home assistant assumes that the unit is m/s 

### URL

https://www.home-assistant.io/integrations/met/

### Version

2021.12.7

**Comment by frenck** [comment]
Hi there @lasseDahl 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here: <https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
