### ISSUE TITLE
Logbook Card capability?

### ISSUE THREAD

**Issue by zala143** [home-assistant/home-assistant.github.io#20980]
### Feedback

Hello HA Devs,

would it be possible to apply filters to the logbook card so it only lists chosen entities when they're in a particular state?

this is a very useful front end card - for example, I'd love to only show events for a particular entity (e.g. motion sensor)  when motion is detected (state of 'on' and ignore when it returns to normal 'off').

Many thanks

### URL

https://www.home-assistant.io/lovelace/logbook/

### Version

2021.12.7

### Additional information

many thanks

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
