### ISSUE TITLE
need explanation of how duration attribute affects a condition

### ISSUE THREAD

**Issue by gokuro** [home-assistant/home-assistant.github.io#20983]
### Feedback

We need an explanation of how the duration attribute of a condition affects its behavior

### URL

https://www.home-assistant.io/docs/automation/condition

### Version

none listed

**Comment by frenck** [comment]
`duration` attribute? 

The term `duration` doesn't occur on the linked page:

![image](https://user-images.githubusercontent.com/195327/147879939-03bfccc4-7bab-4d79-b9b9-75cc89d33d23.png)

I'm not sure what your suggestion is, could you please clarify?
