### ISSUE TITLE
 Ezviz plugin does not log in if 2-step authentication is enabled on the ezviz profile

### ISSUE THREAD

**Issue by Dhy19971** [home-assistant/home-assistant.github.io#20999]
### Feedback

I have tried many times but it is impossible to login if two step login is enabled on the ezviz profile. The code to insert comes from perte di ezviz correctly but the plugin does not give the possibility to do so.

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2021.12.7

**Comment by frenck** [comment]
Hi there @Dhy19971 👋 

It seems like you want to report an issue with an Home Assistant integration, or are looking for support. However, you have submitted documentation feedback instead.

Please see: https://www.home-assistant.io/help 
For information on where to go.

Thanks! 👍 

../Frencl
