### ISSUE TITLE
Binary-Sensor Device Class Tamper is not listed as Available.

### ISSUE THREAD

**Issue by TEfjLONjDON** [home-assistant/home-assistant.github.io#20998]
### Feedback

Binary-Sensor Device Class Tamper is not listed as Available.

I Still receive error/warning in red letters, shown inside the "Studio Code Server" Addon, When editing a binary sensor via the "Studio Code Server" Addon, after supplying "mdi:tamper" as "device_class:".

``` binary_sensor: !include_dir_merge_list includes/binary_sensors ```
### File Name ### "binary_sensors.yaml"
```- platform: template
  sensors:
    someones_not_home:
      device_class: 'tamper'  ### "ERROR/WARNING" IS GIVEN HERE. IN "RED". ###
      value_template: >-
        {{ is_state('person.$$$$$', 'not_home')
          or is_state('person.$$$$$$', 'not_home')
          or is_state('person.$$$$$', 'not_home')
          or is_state('person.$$$_$$$$$', 'not_home')
          or is_state('person.$$$$$$_####', 'not_home') }}
      icon_template: >-
        {% if is_state("binary_sensor.someones_not_home", "on") %}
        mdi:car-traction-control
        {% else %}
        mdi:shield-car
        {% endif %}
```

### URL

https://www.home-assistant.io/integrations/binary_sensor/

### Version

2021.12.7

**Comment by frenck** [comment]
Hi there @TEfjLONjDON 👋 

It seems like you want to report an issue, however, you have submitted documentation feedback instead. Additionally, the issue you seem to report is with the Home Assistant Visual Studio Code extensions, which is not maintained by the Home Assistant project.

You can find the VSCode extension project (and issue tracker) here: https://github.com/keesschollaart81/vscode-home-assistant

Thanks 👍 

../Frenck
