### ISSUE TITLE
mmol for UK

### ISSUE THREAD

**Issue by Icantpickaname** [home-assistant/home-assistant.github.io#21008]
### Feedback

How can I change the setting for mmol? My nightscout is set in the UK as am I. My partner suffers with PTSD since the death of her Dad and this integration would alleviate my disturbed sleep. Help would be appreciated.

### URL

https://www.home-assistant.io/integrations/nightscout/

### Version

2021.12.7

**Comment by frenck** [comment]
> How can I change the setting for mmol?

Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
