### ISSUE TITLE
No example of the actual data given

### ISSUE THREAD

**Issue by swifty99** [home-assistant/home-assistant.github.io#21003]
### Feedback

Hi,
I always struggle to set up the REST sensors. It is not my dayly business. I could be helped if the documumentation would show the REST response to the provided configuration. Would shortcut my try and error a lot.

### URL

https://www.home-assistant.io/integrations/rest/

### Version

2021.12.7

**Comment by frenck** [comment]
I'm not sure how that would help in this case?

**Comment by swifty99** [comment]
Let me try to explain. 
Usually I have a json reply of a given REST api I want to use. To make use of it I need to configure the REST sensor in home assistant. Because my limited knowledge I do not now it from the beginning, I need get up something and iterate on that. In the end the configuration makes perfect sense, I just could not write it down while learning how REST and json work. 
The problem (for me is) when trying to set things up, I do not know where the error is. I have an example with an unknown input and I have my sensor with an unknown configuration. I just cannot link them. Knowing a complete example would help to work on that and iterate to the solution in a much easier way.

**Comment by swifty99** [comment]
I still wish for an example.

**Comment by swifty99** [comment]
As long as only one opinion is given it should not be closed

**Comment by swifty99** [comment]
what a bummer,
a million noobs like me left in the dark.

I thought HA is not for the know-it-all exclusively.
