### ISSUE TITLE
Hunter Douglas PowerView Shade Reporting Open When Closed (And HA Controls Show Closed)

### ISSUE THREAD

**Issue by ziptbm** [home-assistant/home-assistant.github.io#21002]
### Feedback

The Hunter Douglas PowerView integration has been a bit inconsistent on my system.  Some of the shades will randomly report a state that differs from the physical state, what it reports in the PowerView app, and what control options are available in Home Assistant.

e.g. I have one right now that is showing "was opened" 2 hours ago.  It's closed, PowerView app shows it's closed, and Home Assistant shows it at position 0 (closed) with only options to raise it or "stop" it.

Troubleshooting has included reloading the integration, rebooting HA, power cycling the PowerView hubs, checking signal/battery on the device in PowerView app, but it continues to show as opened.   Even if I open it (from open) and then close it (which it actually closes), it closes for a moment and then reverts back to open.

### URL

https://www.home-assistant.io/integrations/hunterdouglas_powerview/

### Version

2021.12.7

### Additional information

I couldn't find anything in my logs related to PowerView, so this leads me to believe it's the integration itself not getting or reporting correct information from PowerView.   Please let me know what else would be helpful in troubleshooting.

**Comment by frenck** [comment]
Hi there @ziptbm 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
