### ISSUE TITLE
LAN Control deleted from Yeelight app

### ISSUE THREAD

**Issue by saintachu** [home-assistant/home-assistant.github.io#21005]
### Feedback

Really as in the title, but I should aslo mention that not for every light. I belive that Yeelight deleted the option from every light that is **branded as "MI"** even it is produced by Y and ie. identifyes as Yeelight in network. 
Cant eneble LAN Control. Tested with: 
- MJDP02YL
- MJDPL01YL - this one is not suported acc. to  your list

PLease have a look at [Yeelight formu thread](https://forum.yeelight.com/t/topic/27747), where you can see its not only my problem.

However YLDD04YL has still option to enable  LAN Control and is working fine with HA. But it's sold under Yeelight brand even if in MI stores.

### URL

https://www.home-assistant.io/integrations/yeelight/

### Version

2021.12.7

**Comment by frenck** [comment]
on the integrations page:

![image](https://user-images.githubusercontent.com/195327/147966541-cff2671d-5f71-4f30-bb92-1b6cd1fd97d9.png)

Links to:

![image](https://user-images.githubusercontent.com/195327/147966582-3c5959b1-7314-400a-9435-e44d24c7c897.png)


I'm not sure, is there something wrong with that alert? What is the suggestion you are trying to make?

**Comment by saintachu** [comment]
Well, first of all I wasn't writing about an alert. But come to think of it, it lacks maybe only one but crucial element.
As you seem to be a really nice person, I'll try to explain it to you in a best way I can. To do it, I'll use an imaginary example, I just thought of.

Picture yourself sitting at home when suddenly you feel hunger. But since the fridge is empty and you are really fed up with the pizza you decide to go to your local supermarket. There on front entrance you see a red sign stating that all MAP packed products are w/o ozone. You get slightly interested, but being hungry, you elect to ignore it. You enter the market and begin shopping. You see a nice package of 4 stakes at really nice price and with a date best used before 2 weeks from now. So you take two. Then you see a package of chicken wings. And as you just about take it an employ approaches you and states that everything in the shop is super fresh and really tasty. So instead of one you take two more. Now, armed with stakes and chicken wings, that will last you for a month, you remain yourself that veggies are important part of a diet you add a frozen pack of fries.
Back home, really hungry, you open first package and faul smell almost knocks you out. Meat is rotten and surelly you cannot eat it. The same is with a chicken, goes straight to the bin. Fries are good though. When you mail a complain to market, you receive a photo of a red sign about a MAP and a question: ""I'm not sure, is there something wrong with that sign? What is the suggestion you are trying to make? " As you dig deeper into a subject you see that MAP means that it means that ie. meat is packaged in modified atmosphere which almost always contains ozone, which is deadly for bacterias thus making a products last a lot longer.

I bet you'd got it, but just to be sure. Red sign is a Alert steaks, chicken and fries are veggis are diffrent lights. MAP for ppl knowing bit more about food indutry is a clear message that packaging contains ozone. So if it doesn't have ozone in it its no good. Just as LAN control is obviouslly critical for yeelight integration.

BTW. As the analogy goes, it is not perfect. I get that you are not an employee of home assistant and you don't get paid. Still, I would assume that you'd rather be interested in getting your work not only to Linux command line warriors but also to ppl who are in the beginning of rather steep learning curve. Just as me.

Let me then tell you how HA, is for beginner. One thing: **I am not complaining nor whinig. It is just how it is**. You get milion of praises for HA all over the net. YT videos, oldschool pages stating how cool solution it is. And thats true. But what they usually fail to show, how difficult it is to use for majority of ppl. 
From my perpective it looks like this. Lets say we talk about some integration and/or configuration or whatever. At first glance it looks easy, almost automatic. Just a bit more complex than iOS use. But it's not. You search for a solution and find one. Let's say it tells that you can deal with issue with a linux command. Just copy paste and done. BUT, how you put linux command in HA? So from tutorial number 1, you go to nr. 2. After a lot of reading you discover that there is not a simple way to that. Specificlly HA is made not to allow that too easy. Ok. Back to beginning. Now you find another solution: powershell command. Cool. So how you do it? Tutorial 2b has answerw. But it does not work. So then you search for tutorial 2bi about tutorial 2b how to execute powershell comand. But tutorial 2bi nad 2bii and 2biii also dont work. You give up on that and search for option 3. And so on.

My point is not difficulty, but the fact that you read about many many many things for the first time. Very soon you get overwhelmed with new information, terms, solutions, opinions, things that worked but work no more etc.

Then we get to Yeelight integration. Sure. There is an alert. But it says that lan control is disabled. Among hundreds of new things, it's just going under a radar. I mean, i'll deal with it later. Maybe I won't have to. The crucial part is almost a fine print. "Rendering Home Assistant unable to communicate with these devices" - I've missed that, I won't lie. But I really don't believe I am the only one. Especially and kind of irony that  I've read a text in details (obviously not an alert part). So anyone can say, it is simply my fault. End of the story. But were I the only one? And really just look at integration text. Let me just give a few examples.

![image](https://user-images.githubusercontent.com/97043394/148246692-0378f90e-8774-4633-8814-f235ef2fb7e8.png)

Come on. This is straight forward wrong. If anyone had bulb with old firmware he just disabled it in HA.

or this:
![image](https://user-images.githubusercontent.com/97043394/148247296-71baa393-de68-420a-bb4c-7ae4eab75d04.png)

Well technically correct. It was tested. Only some/most do not work anymore. So really not correct.

Now think about it. Alert is 9 months old. Which means that I had unprotected sex with a woman, we'd be celebraiting a birth by now. A genuine, fully functional child, with arms, legs, eyes and a brain and so on. Fully capable to make me sleep deprivated for next few years. 

I get that you can have some rules about documentation. But would it hurt to much to write under:
![image](https://user-images.githubusercontent.com/97043394/148250194-f91323da-f8fc-4d51-ad8e-0d27e72b2e70.png)

That below text is outdated and comptibility list should be ignored? For you it could be unnecessary. But for non-programmers not understanding that alert automatically cancels all below the text it would be. Couse it is, right?

Than again, it doesn't seem that this problem will be solved enywhere soon. Maybe even ever. Now, someone might just cut through plastic shell, change wiring and upload custom firmware and then glue it back. Still it's going to be rather niche solution.

So maybe it is time to update supported model list. I don't know, do you test it youselfe or you accept community entries. I'd like to point out that even if my feeedback was annoying (yes i repeted thing you knew for 9 month!), I also provided some info about compability with HA. I read recentlly a TON of entries from HA community and it seems they are ready and eager to contribute. hmm?

As for your anwserw. FIrst of all, you encurage feedback, 

![image](https://user-images.githubusercontent.com/97043394/148248228-b585f667-0c1e-4427-b0fa-b0e9f75dbc5b.png)

but then only to say : 
> I'm not sure, is there something wrong with that alert? What is the suggestion you are trying to make?

Really? You manage one of the most important HA integration of a company that is one of the main manufacturers of smart lights and you kind of avoiding topic and/or bulling me so I wont bother any more? Hmm....
