### ISSUE TITLE
Swatch Internet Time dysfunction

### ISSUE THREAD

**Issue by PatrickGlesner** [home-assistant/home-assistant.github.io#21014]
### Feedback

Hello,

Link to Swatch Internet Time is obsolete (may be http://www.swatchclock.com/) and beat sensor is not functioning.

Best regards,
Patrick.

### URL

https://www.home-assistant.io/integrations/time_date/

### Version

2021.12.7

**Comment by PatrickGlesner** [comment]
Hello,

Sensor beat is now ok.
But link in the doc must be http://www.swatchclock.com/

This issue is still relevant.

Thanks.
Patrick.

**Comment by fabaff** [comment]
> But link in the doc must be http://www.swatchclock.com/

This website is an implementation of beats. http://www.swatchclock.com/ points to Wikipedia for the description.
