### ISSUE TITLE
Asimuth between 0 & 360 or between -180 & 180?

### ISSUE THREAD

**Issue by ddeconin-gh** [home-assistant/home-assistant.github.io#21018]
### Feedback

From  https://doc.forecast.solar/doku.php?id=api:estimate
I read that Azimuth is  : az - plane azimuth, -180 … 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
but the integration mentions:
The azimuth (in degrees on a 360° scale); Is the direction in which the front surface of your solar panels are facing towards. As a full circle is 360°, a value of 0 is facing North, 90 East, 180 South and 270 is facing West (or any value in between).
Is there a translation happening?
My solar panels are located ZW (213°)  figures seem to correspond better to the prediction when I enter 33 for Azimuth?
At least can you clarify the documentation as the difference between the 2 docs will confuse people.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2021.12.7

**Comment by klaasnicolaas** [comment]
We deviate from the documentation because entering a `360` degree compass rose is better to understand than a `-180` to `180` range. The integration adapts your entered value to what the API asks as range.

So if your solar panels are at 213 degrees, the integrations will make a request with the value: 213 - 180 = 33

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/148079837-ab4ae37b-abfb-4584-bd2e-55328483206f.png)

**Comment by ddeconin-gh** [comment]
Hi,
Thx for the quick response! Might be worthwhile to add a small note on this
in the documentation ;-)
D.

**Comment by frenck** [comment]
It is written in the documentation... see screenshot above.
