### ISSUE TITLE
Sensors cannot be added to energy dashboard

### ISSUE THREAD

**Issue by robertjanb** [home-assistant/home-assistant.github.io#21015]
### Feedback

As the title says, I've installed  the P1 monitor integration, and the sensors + data are added to Hass. When I want to add the sensors in the Energy dashboard they don't show up.  Probably because the properties for long term statistics are not set-up properly (https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics). 

### URL

https://www.home-assistant.io/integrations/p1_monitor/

### Version

2021.12.7

**Comment by klaasnicolaas** [comment]
Which entities are we talking about?  because as far as I know it is set correctly.  Also this issue belongs in the core repository and not here in the documentation feedback

**Comment by robertjanb** [comment]
Wow, you're quick :)

I am sorry, I looked yesterday the whole evening and tomorrow, and now, to answer your question, I did find them (turns out it's the *.consumption sensor, I was searching for some others).

Sorry to have bothered you!
