### ISSUE TITLE
Feature request: add activity, signal strength and poe power sensor

### ISSUE THREAD

**Issue by jonasniesner** [home-assistant/home-assistant.github.io#21016]
### Feedback

It would be nice to have a sensor for the current activity in addition to the RX and TX sensor, that only summ up the activity.

It would also be nice to have the signal strength as an attribute of a wirelessly connected device (wold be useful to improve location tracking in conjunction with the ap_mac attribute)

And, for poe switches, a sensor for the poe power per device and per switch would be really nice.

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2021.12.7

**Comment by jonasniesner** [comment]
Also, after now having a switch to play with, it would be nice to have a bandwidth sensor per physical switch port. This would also be useful for the POE power sensor because a physical switch port might be "assigned" to multible mac adresses (or devices). In my use case i have a proxmox server with multible vms connected to a switch port. The bandwidth sensors of the vms are broken(also in unifi) but in unifi it still displays the bandwidth usage of the switch port. 
Thank you for your great work.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
