### ISSUE TITLE
Cover state for group is backwards

### ISSUE THREAD

**Issue by briancbusch** [home-assistant/home-assistant.github.io#21010]
### Feedback

Based on the other domains available in groups (lock, device tracker, etc), the cover domain is backwards. For a lock, it is "on" when it is locked, but for a cover it is "on" when it is open. This seems very backwards. I think the cover on/off states should be reversed to match the others.

### URL

https://www.home-assistant.io/integrations/group/

### Version

2021.12.7

**Comment by emontnemery** [comment]
Lock was recently changed to flag as "on" when unlocked: https://github.com/home-assistant/core/pull/62580

Documentation PR here: https://github.com/home-assistant/home-assistant.io/pull/21011
