### ISSUE TITLE
tailscale integration should make it clear it is not a tailscale client too.

### ISSUE THREAD

**Issue by pie314isi** [home-assistant/home-assistant.github.io#21027]
### Feedback

I think I might be a reasonable assumption that that tailscale integration is also a tailscale client. Since it isn't, it would be good if the documentation stated this.

### URL

https://www.home-assistant.io/integrations/tailscale/

### Version

2021.12.8

**Comment by frenck** [comment]
Hi there @pie314isi 👋 

Thanks for the feedback, looking at the page And the introduction on the page:

> The Tailscale integration integrates the Tailscale API with Home Assistant; giving you the possibility to monitor and automate on the state of the devices in your Tailscale VPN network (Tailnet).

I think it clearly states what it does. What part makes it unclear?

**Comment by pie314isi** [comment]
It's not unclear if you have a sufficient familiarity with HA and the existing tailscale client. I think if it stated, (for example) "Note that this is not the same as a tailscale client. Please see https://github.com/hassio-addons/addon-tailscale", it would be clearer still.

**Comment by pie314isi** [comment]
addendum - specifically, as you are the developer of both bodies of work, it was an (I think) understandable leap of faith that the integration was a subsequent development of the add-on.

**Comment by frenck** [comment]
Don't get me wrong,
I am not trying to be smart ass or annoying. I want to learn how we can word these things better for the future in general, not just this page or occurrence.

> It's not unclear if you have a sufficient familiarity with HA and the existing tailscale client. I think if it stated, (for example) "Note that this is not the same as a tailscale client. 

Right. So, should we also state on the Hue integration page that Home Assistant isn't a Hue hub?

> Please see https://github.com/hassio-addons/addon-tailscale", it would be clearer still.

That is a community add-on, which is not supported by the Home Assistant project and thus will not be part of the official Home Asssitant documentation.

**Comment by pie314isi** [comment]
Well, don't put it in, if you don't want, but I wasted a couple of hours because I saw there was a tailscale integration. 

I'm using tailscale, but I'm not super familiar with the ins and outs and terminology - I followed some instructions and it does what I want.

I saw the newest HA had a tailscale integration, read the documentation, added it and was surprised that my HA didnt appear on my list of tailscale machines.

So I wasted some time trying to understand whether it was a problem with how I generated the API key and whether I needed to update the HA OS as well as the core and posted on the forum to see if I was missing anything. 

A one liner stating that this integration doesn't do literally the main thing that tailscale is for would have been nice.

I mean, you could criticise me for not reading it carefully, but I'd posit that many tailscale users want it to be a simple VPN and wouldn't know or care about monitoring the status of their tailscale network. The "possibility to monitor and automate on the state of the devices in your Tailscale VPN network" could be construed as being sufficiently integrated into the tailscale network as to require an IP. 

Comparing it to a Hue hub is fair, but the Hue page actually does talk about devices connected "to your Hue bridge" as a discrete device. Maybe it should state that the Hue integration can't stand in for a Hue hub. I don't know any anyone has noticed that HA can talk to Hue and gone out to buy bulbs and assumed they don't need a bridge.

Thanks for you time. I just thought that if it tripped me up, it might trip up others.

**Comment by frenck** [comment]
I will make an adjustment for sure, I'm just asking some additional questions to better understand your reasoning and experiences in general, as it would help me write and review future other documentation as well.

Thanks for your insights 👍

**Comment by pie314isi** [comment]
no worries. thanks. Documentation is hard, and non-obvious when you are the author of the product and the doc.

**Comment by frenck** [comment]
Absolutely!

**Comment by frenck** [comment]
Opened up a PR to add more clarification. Thanks again @pie314isi 👍
