### ISSUE TITLE
issues with covers

### ISSUE THREAD

**Issue by witte123** [home-assistant/home-assistant.github.io#21020]
### Feedback

after the upgrade to home assistant 2021.12.7 de state of the covers is always open.
only when I'm closing the covers the state chances to closed but the moment they are fully closed the state changes back to open.

kind regards 
Maarten

### URL

https://www.home-assistant.io/integrations/velbus/

### Version

2021.12.7

**Comment by frenck** [comment]
Hi there @witte123 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
