### ISSUE TITLE
not totally accurate

### ISSUE THREAD

**Issue by JLOrwell** [home-assistant/home-assistant.github.io#21031]
### Feedback

your info isn't totally complete or accurate.  The twinkly app streams the movies while in preview mode but the default scenes built into the controller can be selected with their api, and you can go to and from movie mode.  Supposedly you can have more than one movie on the controller as well but that may only be supported on pro devices.

### URL

https://www.home-assistant.io/integrations/twinkly/

### Version

2021.12.8

**Comment by klaasnicolaas** [comment]
At the bottom of the page you will find an `edit` button so that you can adjust what is incorrect 😉
