### ISSUE TITLE
NUKI V3

### ISSUE THREAD

**Issue by legi1** [home-assistant/home-assistant.github.io#21030]
### Feedback

There is a new Version 3 with a pro variant with own WLAN integrated. Can be managed with the „old“ Nuki bridge.
- What is the status of the HA Integration, couldn’t connect it, either with the bridge or the integrated WLAN, where I can’t find any access token.

### URL

https://www.home-assistant.io/integrations/nuki/

### Version

2021.12.8

**Comment by frenck** [comment]
Is this a question? Or a bug report?

**Comment by legi1** [comment]
I would say a feature request to add the V3 Nuki lock to the integration.

**Comment by klaasnicolaas** [comment]
In that case it belongs more on the [community forum](https://community.home-assistant.io/c/feature-requests/13) than as documentation feedback here.
