### ISSUE TITLE
Sleep number integration needs to have the ability to be assigned to an area.

### ISSUE THREAD

**Issue by Donkendall** [home-assistant/home-assistant.github.io#21046]
### Feedback

Sleep number integration needs to have the ability to be assigned to an area.

### URL

https://www.home-assistant.io/integrations/sleepiq/

### Version

2021.12.7

### Additional information

The Bed needs to be able to be added to the bedroom area where it is located.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
