### ISSUE TITLE
Nothing happened when configured Cloudflare 

### ISSUE THREAD

**Issue by iBobik** [home-assistant/home-assistant.github.io#21048]
### Feedback

I've configured Clouflare integration, but in the end I just see configured integration. No change in DNS, no related messages in logs nor notifications.

Ideally UI should give feedback it what now - how log to wait, what failed or what to configure now. If not easy to write, then add this instructions in a docs.

### URL

https://www.home-assistant.io/integrations/cloudflare/

### Version

2021.12.8

**Comment by ludeeus** [comment]
This is added to the documentation you linked?
> The integration runs every hour, but can also be started manually by using the service `cloudflare.update_records` under services.

**Comment by iBobik** [comment]
Yes, I saw it later when I looked for something useful for some time.
Haven't seen it on first read.


Honza Pobořil


6. 1. 2022 10:33:12, Joakim Sørensen ***@***.***> napsal:
