### ISSUE TITLE
More compatible devices

### ISSUE THREAD

**Issue by AgentSlim** [home-assistant/home-assistant.github.io#21054]
### Feedback

Hi,
i use a QNAP NAS TS-431-P2 with firmware 5.0.0.1891 and this modell is also compatible with the qnap-sensor.

Best regards
Gerd

### URL

https://www.home-assistant.io/integrations/qnap/

### Version

2021.12.8

**Comment by frenck** [comment]
Thanks!

However, the list of compatible devices is not maintained by our documentation, it links to:

<https://github.com/colinodell/python-qnapstats#device-support>

Please report it at that repository.

../Frenck
