### ISSUE TITLE
Honeywell API?

### ISSUE THREAD

**Issue by Ibycus314** [home-assistant/home-assistant.github.io#21069]
### Feedback

From what I can see it doesn’t look like this integration uses the honeywell API. I’ve also noticed the integration doesn’t seem very robust. I wonder if the two facts might be related.

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2021.12.8

**Comment by Ibycus314** [comment]
https://developer.honeywellhome.com/api-methods?field_smart_method_tags_tid=39

**Comment by frenck** [comment]
Hi there @Ibycus314 👋 

I'm not sure what your goal is? Maybe you've missed it, but you have submitted documentation feedback. I'm pretty sure we cannot do anything with that by adjusting the documentation.

../Frenck

**Comment by rdfurman** [comment]
I think you're looking for the Honeywell (EU) integration. This is for legacy systems using the older [mytotalconnectcomfort.com](https://www.mytotalconnectcomfort.com/) honeywell system.

Honeywell (EU) documentation: https://www.home-assistant.io/integrations/evohome/

**Comment by Ibycus314** [comment]
Yeah, wasn’t sure best place, or how to post. Basically I’ve noticed that the honeywell tcc integration doesn’t seem to ever really work like it should, so I went digging for a good thermostat that has a supported API as I didn’t think the honeywells were really supportive of the user community. Anyways, then what should I find but documentation for honeywell apis, but I don’t think this integration is actually using the APIs (requires an API key which I’ve never provided).

**Comment by Ibycus314** [comment]
(I’m currently using the mytotalconnectcomfort.com honeywell system with 6 thermostats on the system…)
