### ISSUE TITLE
How to add a button in first place?

### ISSUE THREAD

**Issue by telmoguerreiro** [home-assistant/home-assistant.github.io#21063]
### Feedback

Hi team,

I am pretty new to HA and this might be trivial but I assume that, like me, others want to use HA and are not experts from day one.
I love the idea of a button, I am excited about the ways HA allows me interact with one. And the documentation is pretty good explaining that but lacks the initial step: How to add a button to HA?
You talk about the entities it creates and how you can interact with it, all great, but I really need to add it to my devices before I can do anything else. 

### URL

https://www.home-assistant.io/integrations/button/

### Version

2021.12.8

**Comment by frenck** [comment]
>  How to add a button to HA?

You don't as written in the documentation:

![image](https://user-images.githubusercontent.com/195327/148414345-8d9cc041-5545-4921-8961-8d3134b64ea6.png)
