### ISSUE TITLE
Described procedure do not work

### ISSUE THREAD

**Issue by MagnusBjelksjo** [home-assistant/home-assistant.github.io#21068]
### Feedback

The described procedure do not work. After restart of HA the DSP-W215 is present i "Entities"-list but it has an error "This entity ('switch.d_link_smart_plug_w215') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.".

Is there any way to solve this?

### URL

https://www.home-assistant.io/integrations/dlink/

### Version

2021.12.8

**Comment by bartfranken1983** [comment]
I found https://www.home-assistant.io/faq/unique_id 
Not sure if it's any help for U, but I haven't tried it yet.

I'm trying to connect a D-LINK  smart plug myself as well. However it's a DSP-W218 and it's not listed as a supported divese, but I thought to give it a try. Is the device available?  Because mine isn't. Not sure if it's a user/ww/configuration issue.

**Comment by frenck** [comment]
Adding a unique ID is not a bug or requirement, but a feature request.

Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by MagnusBjelksjo** [comment]
That was a bit of a surprising answer.

i followed a guide line that did not work as described. 

In the guide the user is asked to report if something is not ok with the guideline. 

I am reporting that the guide did not lead to intended purpose.

**Comment by frenck** [comment]
This page does not describe how to change entities. It described the integration and how to configure it. This you managed to do, otherwise, you won't be seeing the message you are providing about the unique IDs.

Am I missing something? Where on this page does it describe you can change the entity using the UI?

**Comment by MagnusBjelksjo** [comment]
I did not interprete the guide as telling how to set up an INTEGRATION. See attached picture that from my perspective describes how a DEVICE is configured by adding some details into "configuration.yaml".

The result from doing what the guide describe is that a device DO appear in HA but it is in some kind of status unavailable.

But maybe it is me that misunderstood the purpose of the guide.

![image](https://user-images.githubusercontent.com/42750160/149667416-e9cf32fe-af28-4046-8cd9-9b40e8cb726b.png)

**Comment by frenck** [comment]
That is not what you report in the feedback. You said:

>  "This entity ('switch.d_link_smart_plug_w215') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.".

This is answered here: <https://www.home-assistant.io/faq/unique_id>
Unique IDs are not required to be provided, and thus a feature request.

However, you latest comment says:

> The result from doing what the guide describe is that a device DO appear in HA but it is in some kind of status unavailable.

So you have another issue than describe I guess?

**Comment by MagnusBjelksjo** [comment]
I told of the error message ""This entity ('switch.d_link_smart_plug_w215') does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail."." because that is what i see for the devoce in HA.

After following the guide the device has appeared but with a red triangle and when clicking on the device i see the above error message.

So let us go back to the guide. I have followed the guide > The Dlink-device appear in HA but with a red triangle > The guide did not lead to intended result.

Therefor i reported that the guide did not provide expected result.

What shall i do from here?

Am i having wrong expectations from the guide?

**Comment by frenck** [comment]
> Am i having wrong expectations from the guide?

I don't know, it sounds like you are experiencing an configuration error or a bug instead.

>? What shall i do from here?

Anything in the logs?

**Comment by MagnusBjelksjo** [comment]
Yes, actually there were some messages related to Dlink-device in the logs.

From the logs i followed a link "Issues" related to the device and i ended up on issue "https://github.com/home-assistant/core/issues/44489" that described very much the same situation as i had.

On issue 44489 it tells about a user that used incorrect user credentials (DLink cloud credentials instead of the devices local credentials),

I realized that i had done the same thing and corrected the user credentials in "configuration.yaml" and that made it working for me as well.

So all is good now.

Apart from that it is only "on/off" that works on the Dlink-device.

It do not seem like getting access to power consumption details is working.

But that part with power consumption was not specifically promised from the guide. :-)

So i suppose we should close this issue,
