### ISSUE TITLE
Authentication API

### ISSUE THREAD

**Issue by meluvalli** [home-assistant/home-assistant.github.io#21079]
### Feedback

Per https://developers.home-assistant.io/docs/auth_api/

You should be able to access API from CURL.  This works on Linux (Ubuntu specifically), but doesn't work on Windows Curl.

If you run the command, you get a 401 Unauthorized error.  I'm not sure if this is an issue with HA directly or Windows Curl.   Ether way, probably should note that this only works in Linux.

Command being issued: 
curl -X GET http://[My HA IP]:8123/api/error/all -H 'Authorization: Bearer [My Long-Lived Token]'

### URL

https://developers.home-assistant.io/docs/auth_api/

### Version

Not on bottom of page!

**Comment by meluvalli** [comment]
Update:

Figured out in Windows, you have to use quotes.  Not apostrophe around Authorization tag...

So, correct command should be FOR WINDOWS ONLY:
curl -X GET http://[My HA IP]:8123/api/error/all -H "Authorization: Bearer [My Long-Lived Token]"

**Comment by frenck** [comment]
Glad you got it resolved 👍
