### ISSUE TITLE
Denon Heos integration "Command timed out"

### ISSUE THREAD

**Issue by Rakha555** [home-assistant/home-assistant.github.io#21073]
### Feedback

My Denon Heos integration has worked. 
But after updating to "2021.12.8" I now get the error "Command timed out". 
I have tried uninstalling the app, restarting all heos devices and reinstalling it all. 
But the same mistake is made. I also can not find the service heos.sign_in and enter my information. 

### URL

https://www.home-assistant.io/integrations/heos/

### Version

2021.12.8

**Comment by frenck** [comment]
Hi there @Rakha555 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
