### ISSUE TITLE
Device state is `away` and not `not_home`

### ISSUE THREAD

**Issue by UngluedChalice** [home-assistant/home-assistant.github.io#21074]
### Feedback

When I look at the logbook, the device is never showing the state as `not_home`, but instead it shows as `away.` 

So the states I have are:
`home`
`ZONE_NAME` when in another defined zone
`away` when not home and not in a defined zone.

However, the documentation here says the last case should be `not_home`. So unless I'm wrong somehow (which could be a case!) I think something got changed at some point and this documentation needs to be updated? 

### URL

https://www.home-assistant.io/integrations/device_tracker/

### Version

2021.12.8

### Additional information

<img width="1184" alt="Screen Shot 2022-01-06 at 6 11 49 PM" src="https://user-images.githubusercontent.com/46863891/148470217-8daebf7e-8d3c-4fea-9f8e-e18802838b81.png">

**Comment by frenck** [comment]
`not_home` is the state, the translation for that shown in the frontend is `Away` (or something else depending on the language your Home Assistant is in.
