### ISSUE TITLE
BRP069C4x

### ISSUE THREAD

**Issue by colomblanc** [home-assistant/home-assistant.github.io#21084]
### Feedback

Hi!

I have the BRP069C4x and I have tried to set it up- both with and without password and API key. No result. Do you know if this new version of the device is supporter?

Best regards,
Jonas

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2021.12.8

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/148592596-aa9aff98-a72d-40e7-8e4b-5b724e44c035.png)

☝️ So, that isn't supported.
