### ISSUE TITLE
Automation using armed/disarmed alarm state

### ISSUE THREAD

**Issue by karbonato** [home-assistant/home-assistant.github.io#21081]
### Feedback

Hi,thanks in advance por such great integration.

Although the integration is working, I get stucked whilst trying to create an automation for open covers when the alarm is disarmed.

I choose "state" as a trigger for automation, choose "Prosegur" entity but no luck setting up what I am trying to.

I see that I can pick "code format", "changed by", "code arm required", "friendly name" and "supported features". I tried using several of them typing "to: disarmed, state_disarmed and others but nothing works.

I wish I could have more documentation on how to use this integration and setup the integration. Would anyone help onto this?

Thank you

### URL

https://www.home-assistant.io/integrations/prosegur/

### Version

2021.12.8

**Comment by dgomes** [comment]
This is not the proper place to ask for assistance, please use our [community](https://community.home-assistant.io)
