### ISSUE TITLE
Nest Integration Feedback

### ISSUE THREAD

**Issue by atroya** [home-assistant/home-assistant.github.io#21082]
### Feedback

Location: https://www.home-assistant.io/integrations/nest/#device-access-registration
Step 2: If this is your first time here, you likely need to create a new Google Cloud project. Click Create Project then New Project.

Recommend adding a note: "Do not use a hyphen in the name of the Google Cloud project. It will not be able to generate a valid Project ID and the integration will not work."

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2021.12.8

**Comment by allenporter** [comment]
Hi @atroya can you elaborate on the problem you see here when having a hyphen in the project name? I just tried it and was able to create a project.

**Comment by atroya** [comment]
@allenporter Maybe it was a fluke. I just created a new project with a dash in the name and it assigned an ID. You can disregard. Thanks for the follow-up!
