### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by pieterhome** [home-assistant/home-assistant.github.io#21097]
### Feedback

Hi guys,

My Somfy integration does not work anymore.

I already reinstalled, but didn’t change a thing.

TY for your help!

KR,
Pieter

![CAA713B4-8E89-4A11-8860-C695CB7E4443](https://user-images.githubusercontent.com/97331232/148637236-8bab10af-15a6-430d-9c3d-51a7425014de.jpeg)

### URL

https://www.home-assistant.io/integrations/somfy/

### Version

2021.12.8

**Comment by frenck** [comment]
Hi there @pieterhome 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
