### ISSUE TITLE
Detecting devices with Gree in manufacturer's name

### ISSUE THREAD

**Issue by T3of1L** [home-assistant/home-assistant.github.io#21091]
### Feedback

Would be possible to make a small modification in order for the integration to detect all entities that have "Gree" in manufacturer's field. For example I have a Gree device that shows: "Gree Electric Appliances, OF Zhuhai" and it is not detected by the integration for this reason I believe.

Thank you.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.12.8

### Additional information

c

**Comment by cmroche** [comment]
Detection doesn't work on names, if any device on the network responds to the discovery and binding requests then it is a device useable by the integration. If a device does not respond to this, then it likely cannot be used with this integration. Some Gree devices are cloud only, and do not appear to work with the local network protocol used by this integration.

**Comment by T3of1L** [comment]
Thank you very much for the information.

The device it's a Gree Versati III Heat Pump that perhaps it's not
supported.

It causes also an error in the system, perhaps when the integration it's
trying to bind.

This is the error:

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:98
First occurred: 12:10:19 (1 occurrences)
Last logged: 12:10:19

Error doing job: Exception in callback
_SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 1029, in
_read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.9/site-packages/greeclimate/network.py",
line 111, in datagram_received
    self.packet_received(obj, addr)
  File "/usr/local/lib/python3.9/site-packages/greeclimate/discovery.py",
line 156, in packet_received
    self._create_task(self.device_found(DeviceInfo(*device)))
  File "/usr/local/lib/python3.9/site-packages/greeclimate/device.py", line
113, in __init__
    self.name = name if name else self.name
AttributeError: 'DeviceInfo' object has no attribute 'name'

It's there a way to tell the integration to ignore it for the time being?

**Comment by cmroche** [comment]
Hey @T3of1L actually with what you've shown, your device likely is supported. Though it was unexpected for this field to be null I can implement a work around for this corner case.

This isn't HA specific though, as I am at work right now, would you mind opening an issue and pasting this log over here please: https://github.com/cmroche/greeclimate/issues

Thanks for investigating.
