### ISSUE TITLE
Issue TaHoma Integration

### ISSUE THREAD

**Issue by pieterhome** [home-assistant/home-assistant.github.io#21096]
### Feedback

![C78D3036-B849-4931-8A6A-BFD1614AC3F8](https://user-images.githubusercontent.com/97331232/148634846-6a93a6d8-aa8b-40e9-9e44-423b34ae9334.png)

Hi Guys,

My covers from TaHoma/Somfy do not work any more. Seems to be an error with the integration.

thank you for your help :)

KR,
Pieter

### URL

https://www.home-assistant.io/integrations/tahoma/

### Version

2021.12.8

**Comment by frenck** [comment]
Hi there @pieterhome 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Please make sure your issue isn't reported already (to prevent creating duplicates).

Thanks 👍 

../Frenck
