### ISSUE TITLE
Changing the Effects through YAML template

### ISSUE THREAD

**Issue by lathishsundar** [home-assistant/home-assistant.github.io#21106]
### Feedback

Nanoleaf lights support the effects based on sound or standard effects. Is there any way to change the light effects through YAML. It would be helpful to add it in the help page.

Thank you,
Lathish

### URL

https://www.home-assistant.io/integrations/nanoleaf/

### Version

2021.12.8

**Comment by milanmeu** [comment]
Hi @lathishsundar, thanks for your feedback.

The Nanoleaf light entity works just like any other light, so you can use the `light.turn_on` service call to set an effect. Please refer to the light documentation for more information: https://www.home-assistant.io/integrations/light/.

Here is an example service call to set a light effect:
```YAML
service: light.turn_on
target:
  entity_id: light.canvas_adf9
data:
  effect: Color Burst
```
> It would be helpful to add it in the help page.

This service call is not specific to Nanoleaf and works for any light entity, so this information is on the light documentation page instead.

Please don't hesitate to open a new issue or add a comment if you have more feedback. Have a nice day! :smile:

**Comment by lathishsundar** [comment]
Thank you for help.
