### ISSUE TITLE
Request for clarification

### ISSUE THREAD

**Issue by jmporter34** [home-assistant/home-assistant.github.io#21100]
### Feedback

Please clarify what is meant by "use --net=host." in the following statement on the webpage:

"If you are using Home Assistant in Docker, make sure to use --net=host."

Is this a docker setting ?  Is it something to be entered into the dialog in Home Assistant, maybe in the "network interface to use" edit box ?  Something else ?

Thank you

Also, one of the suggestions "Make sure you have enabled LAN access." takes you to a webpage in the domain domoticz.com rather than to a Home Assistant webpage.  What is that ?

### URL

https://www.home-assistant.io/integrations/xiaomi_aqara/#connection-problem

### Version

2021.12.8

### Additional information

[aqara_hub_not_found.pdf](https://github.com/home-assistant/home-assistant.io/files/7833431/aqara_hub_not_found.pdf)

**Comment by frenck** [comment]
> Please clarify what is meant by "use --net=host." in the following statement on the webpage:

> "If you are using Home Assistant in Docker, make sure to use --net=host."

That is a Docker feature. Please consult our installation guides or the Docker documentation for more information on that.

**Comment by jmporter34** [comment]
Thanks for the clarification.

**Comment by jmporter34** [comment]
One other thing please - by V1 and V2 hubs, do you mean the M1 and M1S ?
Any info on the M2 and/or E1 hubs ?  Thanks.
