### ISSUE TITLE
Starting the VM on Synology NAS gives me an error

### ISSUE THREAD

**Issue by WeterPeter** [home-assistant/home-assistant.github.io#21102]
### Feedback

Fetching update data from https://version.home-assistant.io/stable.json
22-01-08 18:40:46 CRITICAL (MainThread) [supervisor.updater] Content-Trust is broken for the version file fetch!

This is repeated every 20 second on the login screen:
<img width="387" alt="Screenshot 2022-01-08 at 19 43 55" src="https://user-images.githubusercontent.com/52879850/148655909-90e18e51-5bb0-4e3b-85e8-b66603dd5f7a.png">

What to do?

Regards,
Peter

### URL

https://www.home-assistant.io/installation/alternative/

### Version

2021.12.8

**Comment by frenck** [comment]
>  Content-Trust is broken for the version file fetch!

Sounds like you are running an outdated Supervisor version.

Anyways, thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
