### ISSUE TITLE
YOUR.DNS.HOSTNAME:PORT

### ISSUE THREAD

**Issue by Mulder1960** [home-assistant/home-assistant.github.io#21109]
### Feedback

I struggle to find the details for "https://YOUR.DNS.HOSTNAME:PORT/".
I only have my (192.168.x.x:8123) ip at local my host. 
I do not have a fixed IP address from my ISP

### URL

https://www.home-assistant.io/integrations/gpslogger/

### Version

2021.12.8

**Comment by frenck** [comment]
> I do not have a fixed IP address from my ISP

In that case, you won't be able to use that as such. If you want to report back from external, you need to have a fixed external address.

You might want to take a look into Home Assistant Cloud, that service can still provide you a way to access your instance in that case.
