### ISSUE TITLE
Not clear how to check for null or empty values. 

### ISSUE THREAD

**Issue by JonLaliberte** [home-assistant/home-assistant.github.io#21117]
### Feedback

I have an automation. 
I want to check if {{ trigger.to_state.context.user_id }} is null/not set. Nothing in docs helps with this. 

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2021.12.8

**Comment by frenck** [comment]
`{{ trigger.to_state.context.user_id is None }}`
`{{ trigger.to_state.context.user_id is not None }}`

or

`{% if trigger.to_state.context.user_id %}....`
`{% if not trigger.to_state.context.user_id %}....`


This is general Jinja2 Syntax.

**Comment by JonLaliberte** [comment]
Thanks, @frenck, that was appreciated!

Seems like maybe it should be an example in the docs?

From [the page I was on](https://www.home-assistant.io/docs/scripts/conditions/), it wasn't clear which syntax I was supposed to be using - I came from a Google search and it's not mentioned on the page. I do see now that it is mentioned on the main Templating doc page, but it doesn't seem to be mentioned anywhere within the Automation section (in fact Jinja is only mentioned in the docs [on one page](https://www.google.com/search?hl=en&q=site%3Ahttps%3A%2F%2Fwww.home%2Dassistant.io%2Fdocs%20jinja)).

Also, from the [Jinja docs](https://jinja.palletsprojects.com/en/2.11.x/templates/):
> The special constants true, false, and none are indeed lowercase. Because that caused confusion in the past, (True used to expand to an undefined variable that was considered false), all three can now also be written in title case (True, False, and None). However, for consistency, (all Jinja identifiers are lowercase) you should use the lowercase versions.

Might be good to always use all lowercase to match their docs for consistency.

Just want to say I appreciate everything you all do, such a great project!

**Comment by frenck** [comment]
> Seems like maybe it should be an example in the docs?

This is generic Jinja syntax for which we direct users to their documentation.

**Comment by JonLaliberte** [comment]
@frenck Understood - in which case it would probably be best to mention and link to the Jinja docs in more locations in the HA Docs.

>  I do see now that it is mentioned on the main Templating doc page, but it doesn't seem to be mentioned anywhere within the Automation section (in fact Jinja is only mentioned in the docs [on one page](https://www.google.com/search?hl=en&q=site%3Ahttps%3A%2F%2Fwww.home%2Dassistant.io%2Fdocs%20jinja)).
