### ISSUE TITLE
How to change cameras resolution?

### ISSUE THREAD

**Issue by santibur06** [home-assistant/home-assistant.github.io#21118]
### Feedback

Hi, I'm using the AgentDVR integration and I see all my cameras just fine. The issue I have is that the image resolution in HA seems to be fixed and it's quite small, even though I see the full sized image in AgentDVR. Is there any way to change this? Is this a bug or is it supposed to be like this? In that case, why?

Thanks!

### URL

https://www.home-assistant.io/integrations/agent_dvr/

### Version

2021.12.8

**Comment by ispysoftware** [comment]
It's using the default mjpeg resolution in Agent DVR - i'll add an option to change that default in server settings in Agent DVR
