### ISSUE TITLE
my tahoma integration require reconfigure everyday!

### ISSUE THREAD

**Issue by p2544** [home-assistant/home-assistant.github.io#21122]
### Feedback

I got 2 somfy motors in my house using tahoma bee and tahoma Overkiz (by Somfy).

the integration is disconnect everyday and I have to re-enter my username and password in order to make my button work as normal.

please help

### URL

-

### Additional information

I got 2 somfy motors in my house using tahoma bee and tahoma Overkiz (by Somfy).

the integration is disconnect everyday and I have to re-enter my username and password in order to make my button work as normal.

please help

**Comment by frenck** [comment]
Hi there @p2544 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
