### ISSUE TITLE
Alert message for Yeelight integration

### ISSUE THREAD

**Issue by FrankDUS69** [home-assistant/home-assistant.github.io#21123]
### Feedback

Hi,

I´ve just added my new Yeelight YLTD001 ti HA only by activating LAN support in the Yeelight Android app.
Firmware of the light is 2.0.8_0017.
It has been recognized in HA automatically, could be easily integrated and works out of the box.
Maybe the alert does only belong to some Yeelight products, or isn´t valid anymore.

Please check if the alert is necessary any longer.

BR
Frank

### URL

https://www.home-assistant.io/integrations/yeelight/

### Version

2021.12.8

**Comment by frenck** [comment]
The alert is still valid. Thanks for thinking along 👍
