### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#21126]
### Feedback

I can't see any info on how to do anything with Control4. Yes I understand this page just tells you how to install the integration but then what? Connected HA and C4 and nothing seems to have changed anywhere, still not even sure what controls what exactly. 

Also the only field marked as mandatory is this box (Feedback) but it needs a title which isn't marked as mandatory. 

### URL

https://www.home-assistant.io/integrations/control4/

### Version

2021.12.8

**Comment by frenck** [comment]
> Also the only field marked as mandatory is this box (Feedback) but it needs a title which isn't marked as mandatory.

That is a GitHub issue, we can't do anything about.

**Comment by frenck** [comment]
> I can't see any info on how to do anything with Control4. Yes I understand this page just tells you how to install the integration but then what?

Then you get entities and devices just like any of the other 1800+ integrations we have?

**Comment by ghost** [comment]
> Then you get entities and devices just like any of the other 1800+ integrations we have?

I'm obviously missing something then as no new entities have shown up. Like I say, there is no info on what should happen or how it should work. Not even anything that says "that's it, you don't need to do anything, all the switches should show up as entities with no further intervention from the user". I would guess that maybe not all lighting devices are supported, or there is something that has to be done in a certain way at the C4 end to make them appear?

**Comment by frenck** [comment]
> that's it, you don't need to do anything, all the switches should show up as entities with no further intervention from the user

It doesn't support switches, as the introductions text says:

> The Control4 integration allows you to control and monitor lights from your local Control4 system. 

It would only show lights.

**Comment by ghost** [comment]
> It doesn't support switches, as the introductions text says:

I think the wording is ambiguous here. It suggests I can use Control4 to turn lights on and off in HA, but tbh it's not really clear either way, I think you can read it both ways if you read it slow enough. I take it it actually does the opposite then, i.e. you can only control lights in a Control4 project from switch entities in HA? 

I think that first sentence needs clarifying. 

> The Control4 integration allows you to use Home Assistant to control lights in Control4 and also provides status feedback to Home Assistant.

Seems to be clearer and more definitively detailed.

**Comment by frenck** [comment]
> lights in a Control4 project from switch entities in HA?

No, this integration does not provide switch entities. It provides lights; as stated in the introduction. I don't see how lights can be read as switches.

**Comment by ghost** [comment]
> No, this integration does not provide switch entities.

I didn't say it did. I think this is another language barrier thing. Maybe the original description made sense to whoever wrote it once translated to their native language but in English, it makes no sense. 

I never said the integration makes switch entities, I asked for clarification on controlling lights in Control4 from switch entities in HA. 

> as stated in the introduction.

As I already said, this isn't stated very clearly. I feel like we're going round in circles here.

**Comment by frenck** [comment]
>  I asked for clarification on controlling lights in Control4 from switch entities in HA.

It doesn't create switch entities in HA.

**Comment by ghost** [comment]
> It doesn't create switch entities in HA.

Is there anyone that speaks English that can help with this as I didn't say it does create switch entities. I asked for clarification on whether the lights in C4 can be controlled from switch entities in HA?

**Comment by frenck** [comment]
> Is there anyone that speaks English that can help with this as I didn't say it does create switch entities.

I speak English... Thank you for the nice compliment.

> as I didn't say it does create switch entities.

You actually did a couple of times, I even took the liberty to quote it above.

**Comment by frenck** [comment]
In the end, the control4 integration provides can control and monitor lights and does create light entities in Home Assistant. As described in the introduction of the integration.

Is the conclusion you have: it doesn't create light entities for your lights in control4?

**Comment by ghost** [comment]
> You actually did a couple of times, I even took the liberty to quote it above.

If you spoke English you would know then that I did not say it creates switch entities. Once, in the very first post I did because of the confusing description of the integration but after that I didn't. 

> As described in the introduction of the integration.

The point of this is that it is not described very well and it is worded poorly. I now understand what it is is supposed to do after reading between the lines. The description is not clear. That is a fact. That's it.

> Is the conclusion you have: it doesn't create light entities for your lights in control4?

I have no lights in Control4, only switches, hence the initial confusion. Again, very little info on exactly what it does or what it is supposed to create. I will add some lights and recheck but I am sure it will work then now we know which way round it works.

**Comment by frenck** [comment]
> I have no lights in Control4, only switches, hence the initial confusion

Sorry, I really don't see how it can be confusing, it clearly states it controls lights. And you are providing feedback that you don't understand why your switches aren't showing up. 🤷

**Comment by ghost** [comment]
> it clearly states it controls lights

It does not. It sort of suggests it that it might do that in a confusing non-coherent garbled way. 

> And you are providing feedback that you don't understand why your switches aren't showing up. 🤷

Yes, because it isn't clear what the integration does. 

Your responses are just arrogant. You are saying I am stupid for not understanding what this is supposed to do even though there is little documentation on it and what there is is unclear. It is clear to you because you know how it works. To anyone that does not know how it works it is unclear. 

Why even ask for feedback if you are just going to tell the person providing the feedback they are an idiot and you are superior so aren't going to listen to any of it? Really can't see the point of using HA if this is the attitude of people involved.

**Comment by lawtancool** [comment]
Hi @vbrl7, 

I am the developer of the Control4 integration. To clarify, this integration only supports devices that are set up as "lights" in Control4. As such, a **Control4 light switch module that is setup to appear as a "switch" instead of a "light" in Control4 would not be detected** by Home Assistant.

Detected lights will be controlled by light entities in Home Assistant (ex. `light.kitchen`). Switch entities (`switch.kitchen`) are not supported and will never be created.

**Comment by ghost** [comment]
> To clarify, this integration only supports devices that are set up as "lights" in Control4. As such, a **Control4 light switch module that is setup to appear as a "switch" instead of a "light" in Control4 would not be detected** by Home Assistant.

Thank you. Not sure what the other fella was going on about, he took this off on a complete tangent. As I was suggesting originally this could do with being clarified as the description of the plugin is not clear and also as mentioned a brief mention of what should happen would be useful as a pointer for getting it working. Basically your comment provides clear info, just something like that on the plugin page would be helpful as the other poster here seems to be of the opinion that the garbled description is not going to be changed.

**Comment by frenck** [comment]
Sorry, "that other fella" doesn't see the issue with the current wording.

**Comment by ghost** [comment]
> Sorry, "that other fella" doesn't see the issue with the current wording.

What an absolute shitshow this community is. Glad I found this out before actually using Home Assistant. I cannot believe one arrogant person who clearly doesn't fully understand or speak English is the one to veto any feedback on the documentation. Why even bother with the feedback button if you're just going to ignore it.
