### ISSUE TITLE
External URL must be set for this integration to work

### ISSUE THREAD

**Issue by hannah52** [home-assistant/home-assistant.github.io#21127]
### Feedback

I've tried recently this integration and noticed that I got error like
`ERROR (SyncWorker_1) [homeassistant.components.fitbit.sensor] Could not find an SSL enabled URL for your Home Assistant instance. Fitbit requires that your Home Assistant instance is accessible via HTTPS`

but my instance of HASSio is behind traefik with https. Then I saw someone mentioned on the forum about base_url and I decided to set External URL in the:
Configuration -> Settings -> General -> External URL.

After that I've got no error and notification to set up my fitbit connection.

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2021.12.8

**Comment by frenck** [comment]
> External URL must be set for this integration to work

That depends on your setup and is generally incorrect. It only happens if your instance is terminated by e.g., a reverse proxy that isn't set up / configured correctly (and thus the external URL isn't properly configured or detected).
