### ISSUE TITLE
ZHA docs needed for usage of LQI and RSSI diagnostics sensors for troubleshooting?

### ISSUE THREAD

**Issue by Hedda** [home-assistant/home-assistant.github.io#21124]
### Feedback

ZHA docs needed for the usage of LQI and RSSI sensors as diagnostic indicators for Zigbee device and router troubleshooting?

LQI and RSSI sensors was just added back to ZHA  -> https://github.com/home-assistant/core/pull/62716

Not yet described in ZHA docs https://github.com/home-assistant/home-assistant.io/blob/next/source/_integrations/zha.markdown

### URL

https://www.home-assistant.io/integrations/zha

### Version

2022.1

**Comment by frenck** [comment]
Entities of ZHA are not described at all, sounds weird to me to describe these as an exception to be honest.

**Comment by Hedda** [comment]
Meant for the troubleshooting section as LQI and RSSI can be used as indicators for troubleshooting device connection issues.

https://www.home-assistant.io/integrations/zha/#troubleshooting

These two indicators of connection and signal strenght can also be used to assess the quality of links/connections of devices in a Zigbee network mesh. Example:

https://docs.hubitat.com/index.php?title=Zigbee_Logs

https://github-wiki-see.page/m/dresden-elektronik/deconz-rest-plugin/wiki/LQI-explained

LQI (Link Quality Indication) is a cumulative value shown as a value between 0-255 with a lower number indicating that it is more likely that messages will be dropped and/or have to be resent (i.e. packet loss). The closer to 255, the more reliable connection to a specific device.

LQI value meanings (example range):
* LQI values close to 255 == excellent (would suggest use green color indicator in a UI)
* LQI values close 200 == ok (would suggest use yellow color indicator in a UI)
* LQI values close 150 == flaky but can work (would suggest use red color indicator in a UI)
* LQI values < 130 problematic (would suggest use flashing red color indicator in a UI)

Note! Note that there is no IEEE standard for LQI: different manufacturers range it and calculate it differently. For example, Silicon Labs uses positive display numbers for LQI where higher is better: they display a zero error rate as a 255 LQI value, but other manufacturers handle this differently and might use totally different ranges for LQI. 

I guess that ZHA or quirks in [ZHA Device Handlers](https://github.com/zigpy/zha-device-handlers) translate LQI values to a standard for Home Assistant?

RSSI (Received Signal Strength) values should be negative numbers as it is a measure of incoherent (raw) RF power in a channel, with the closer to 0 the better as that means less power was used to transmit and is an indication of stronger signal strength. RSSI can also be used as LQI for direct children (i.e. when messages are not going through a Zigbee router, as in single-hop connections).

RSSI value meanings:
* RSSI values at > -60 and above ( meaning -50, -40, etc.) == Very strong signal. (should be green color in UI).
* RSSI values at ~ -75 == OK for ZHA 1.2 devices but maybe not OK for newer Zigbee 3.0 devices (should be yellow color in UI).
* RSSI values at < -80 and below ( meaning -85, -90, etc.) == Noisy so running risk losing messages. (should be red color in UI)

RSSI should however not be used alone for troubleshooting as RF power can come from any source (e.g. other IEEE802.15.4 transmitters, Bluetooth, WiFi, FSK, or background radiation on the same radio frequency), and thus go good RSSI values but bad LQI values can be an indicator of electromagnetic interference.

References:

https://www.diva-portal.org/smash/get/diva2:996558/FULLTEXT01.pdf

PS; Off-topic but FYI; RSSI signal strength could also be used to build an indoor positioning system using Zigbee beacon tags:

https://www.sciencedirect.com/science/article/pii/S1877050919308294

https://www.intechopen.com/chapters/16125

**Comment by frenck** [comment]
Ok 🤷
