### ISSUE TITLE
Netatmo integration and battery entities

### ISSUE THREAD

**Issue by xabaras75** [home-assistant/home-assistant.github.io#21133]
### Feedback

thermo valves imported in my Hassio using the integration. when you made the configuration the integration at the early beginning, all the devices and entities are available. once you make a restart of the hassio, all the batteries entities become unavailable. to get them back, you have to delete the integration and make it again. But again in case of restart of hassio the battery entities become unavailable:

![image](https://user-images.githubusercontent.com/64804254/148770016-7ee2410f-757c-4a94-acbb-85b63800c86b.png)

### URL

https://www.home-assistant.io/integrations/netatmo/

### Version

Home Assistant 2021.12.8

### Additional information

Home Assistant 2021.12.8
Home Assistant OS 7.1
supervisor-2021.12.2

**Comment by frenck** [comment]
Hi there @xabaras75 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
