### ISSUE TITLE
Hypervisor specific configuration for Synology DSM Virtual Machine Manager

### ISSUE THREAD

**Issue by breti** [home-assistant/home-assistant.github.io#21138]
### Feedback

Synology DSM x86 NAS provide their own hypervisor, called "Virtual Machine Manager".  The essential settings for running HA OS on it are the following. Maybe it would be useful to add this in the "Hypervisor specific configuration" section?

Synology DSM Virtual Machine Manager

Download the OVA image above to a NAS volume or your local drive
Click "Import" in the drop-down menu of "Create"
Select "Import from OVA files" and provide the path to the OVA image
Click on the gear icon behind "Virtual Disk 1", select "VirtIO SCSI Controller"
Click on the gear icon behind "Network", change "Model:" to "virtio"
Change "Firmware" to "UEFI"
Change "Autostart" and "Virtual USB Controller" settings as needed

### URL

https://www.home-assistant.io/installation/alternative/

### Version

2021.12.8

### Additional information

Link to synology documentation: https://kb.synology.com/en-ca/DSM/help/Virtualization/virtual_machine

**Comment by frenck** [comment]
Hi there @breti 👋 

We have limited our documentation to a couple of commonly used Hypervisors, which have been decided upon in an architectural discussion. Synology isn't one of those.

If you like to contribute a community guide for these, please do so on our Community Forum.

Thanks 👍 

../Frenck

**Comment by breti** [comment]
OK, that's your choice of course, but in my opinion it makes no sense at all to describe in detail how to run HA with Docker on Synology, which is just not recommended because of the missing supervisor, while omitting the recommended, complete solution.

I had documented this here because the question kept coming up in the Facebook groups about HA.
