### ISSUE TITLE
binary workday sensor cannot call holidays by name if holiday not included or excluded

### ISSUE THREAD

**Issue by rncole** [home-assistant/home-assistant.github.io#21142]
### Feedback

I was implementing the binary workday sensor and found I could not use the add_holidays method by name if "holiday" was not included in the workdays or excludes list.  

I am implementing this with a Time of Use power arrangement and want to be very explicit about what holidays are included.  I would like to implement as follows:

> binary_sensor:
>  - platform: workday
>    country: US
>    workdays: [mon, tue, wed, thu, fri]
>    excludes: [sat, sun]
>    add_holidays:
>      - "New Year's Day"
>      - "Memorial Day"
>      - "Independence Day"
>      - "Labor Day"
>      - "Thanksgiving"
>      - "Christmas Day"

However, doing so results in a "ValueError: Cannot parse date from string" error.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2021.12.9

**Comment by rncole** [comment]
Still relevant.  👍

**Comment by frenck** [comment]
Hi there @rncole 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

https://github.com/home-assistant/core/issues>


Thanks! 👍 

../Frenck
