### ISSUE TITLE
In JSON Message a ','  (Comma) after last element should be removed (Documentation MQTT Discovery)

### ISSUE THREAD

**Issue by pierreverbakel** [home-assistant/home-assistant.github.io#21143]
### Feedback

The last comma in the section **Use object_id to influence the entity id** should be removed 
{
  "name":"My Super Device",
  "object_id":"device1",
  "state_topic": "homeassistant/sensor/device1/state",    <---- The last comma here should be removed
 }

Because this command failed to work for me:
mosquitto_pub -h 192.168.x.y -p 1883 -u myuser -P mypwd -t "homeassistant/sensor/device1/config" -m '{"name":"My Super Device","object_id":"device1","state_topic": "homeassistant/sensor/device1/state",}'

and this one did work for me:
mosquitto_pub -h 192.168.x.y -p 1883 -u myuser -P mypwd -t "homeassistant/sensor/device1/config" -m '{"name":"My Super Device","object_id":"device1","state_topic": "homeassistant/sensor/device1/state"}'

Apart from that I was very much puzzled by the way the _entity_id_ is grabbed from the "name" instead of the _object-id_ in the topic for the configuration. Also in the example above there is already **sensor/device1/config** 
It is stated indeed that the topic in the topic-path is not used in the _entity_id_ but apparently once it is mentioned in the json-message it IS used as the _entity_id_   My remark here is when both are named _object_id_  (The one in the Topic-path and the one in the JSON-Message) . Why does it not suffice to have only the <object_id> defined in the path and use that value also as the _entity_id_ , it is very confusing as it is now and doing it in that way the need to have a separate element in the JSON-Message would no longer exist. The only way I can think of is one uses e.g. two sensors mounted on one device (E.g. Temperature + Humidity) and one wants to use a object_id in the path that is the same.  However the example concerning this in this same page at **SENSORS WITH MULTIPLE VALUES** stipulates that 'sensorBedroomT' and 'sensorBedroomH' are to be used as the <object_id> in the Topic-Path, so one for each sensor on the device.

Long story I know but I think one or the other can be left out OR just rename "object_id" to "entity_id" in the JSON-Message 
or at least have "entity_id" it as an alternative to "object_id" in the JSON-Message, like so:

 {
  "name":"My Super Device",
  "entity_id":"device1",
  "state_topic": "homeassistant/sensor/device1/state"
 }
If the _entity_id_ is already taken then HA-Server should  just not accept the config-message or see as an update of the existing values for "name" and "state_topic" in this case, I would prefer the latter. 

In that light the use of <node_id> could be illuminated with an example like the one of the mentioned. That was extremely helpful to get my mind around that, to see that the Topic for the state is the same in both cases. Now <node_id> seems to be something of olden days and the details of use is left out of this documentation. 
Thanks anyway. I am impressed with the work, just trying to see how to integrate a Mesh-System with Home-Assistant, and thought to start with Discovery to make the first steps with that. Possibly leading to another "Integration" in the Eco-system. 

### URL

https://www.home-assistant.io/docs/mqtt/discovery/

### Version

2021.12.8 ? (It is not stated , but it is the documentation of 11 Jan 2022)

**Comment by pierreverbakel** [comment]
Nitpicking a bit but since I noticed it :
I guess the last comma in the JSON-Message is not allowed here as well  at Climate Control : State-Payload:
_{
  "mode":"off",
  "target_temp":"21.50",
  "current_temp":"23.60",
}_

And there is a double 'the' at the last sentence:

_In the example above, **the the** entity_id will be sensor.device1 instead of sensor.my_super_device._

**Comment by frenck** [comment]
@pierreverbakel It has to be valid JSON 🤷

**Comment by pierreverbakel** [comment]
I used https://jsonlint.com to be sure:  A comma after the last element is not valid. Admitted: some json-readers accept that, in the end, what is an extra ',' going to hurt? , but Home Assistant does not, which I do agree with too, since it looks as something got lost
