### ISSUE TITLE
Can you please add media player supported features to documentation?

### ISSUE THREAD

**Issue by maciekmisko** [home-assistant/home-assistant.github.io#21159]
### Feedback

Hi,
can you please add supported media_player features to the documentation?

I suspect join/unjoin is not working?

Regards,
Maciej

### URL

https://www.home-assistant.io/integrations/dlna_dmr/

### Version

2021.12.9

**Comment by StevenLooman** [comment]
@chishm, can you look at this?

**Comment by chishm** [comment]
Yep, I'll edit the page this weekend.
