### ISSUE TITLE
Secrets for dummies like me 

### ISSUE THREAD

**Issue by Arikshten** [home-assistant/home-assistant.github.io#21157]
### Feedback

Re the instructions for secrets . https://www.home-assistant.io/docs/configuration/secrets

I am new to HA and was looking through the above page in order to use secrets. 
I see there is already a secrets.yaml file on my HA and I see existing includes in my config (but not one for that file. 

Reading the instructions tells me I need to add the file and it hints at being similar to using includes (directs to that page for reference) but does not say if I have to add an include or if there are any limitations on the naming of such an include. As a result I am a little unclear on the exact steps required. (I will look in the forum for clarity). Not sure I should/could update those instructions once I find out but either way they are unclear as to the exact steps at that point .  happy to discuss ..  thanks 

### URL

https://www.home-assistant.io/docs/configuration/secrets/

### Version

2021.12.9

**Comment by frenck** [comment]
You do not need to include or configure anything.
Just put secrets into the secrets file and use them using `!secret secrect_name`.

**Comment by Arikshten** [comment]
Dear frenck .. 
Thank you for the fast reply -- that is what I had guessed from looking around. but I still think it could be clearer in the instructions. Appreciate your assistance thank you. 

A

**Comment by frenck** [comment]
I have read them because of this report, it is not clear to me what your suggest is or what the unclarity might be?

Nothing indicates an include?

**Comment by Arikshten** [comment]
Fair enough - perhaps I am just overthinking things. 
Appreciate your time and help. 
Regards
A
