### ISSUE TITLE
Var integration files location

### ISSUE THREAD

**Issue by davel4wa** [home-assistant/home-assistant.github.io#21150]
### Feedback

The var integration files are downloaded into the custom_components folder of the HA config folder by HACS while other custom components are being downloaded into the www\community folder. Is this the correct folder location for this integration? I have this entry from a while back in my configuration file; customize: !include custom_components, but it was commented out as it seems to break the configuration. Actually, the other integrations in the custom_components work properly without the !include statement. 
HA on Docker ver. 2021.12

### URL

https://www.home-assistant.io/docs/automation/templating/

### Version

2021.12.9

**Comment by frenck** [comment]
> The var integration files are downloaded into the custom_components folder of the HA config folder by HACS while other custom components are being downloaded into the www\community folder. Is this the correct folder location for this integration?

I think you are mixing up integrations and frontend resource/plugins. Those are not the same things and thus use different folders.

> I have this entry from a while back in my configuration file; customize: !include custom_components, but it was commented out as it seems to break the configuration.

Loading customize from a custom component sounds incorrect and wrong. However, that is a third party resource, we cannot help you with that. Please contact the author of that custom integration for support.


> Actually, the other integrations in the custom_components work properly without the !include statement.

Yes, as the above-mentioned construction is not "normal".

../Frenck
