### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#21168]
### Feedback

Great integration, is there a chance to add boiler diagnostic information like system pressure ?

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2021.12.9

**Comment by thecode** [comment]
Hi, @YoykoKoszko 
Please create a feature request here: https://community.home-assistant.io/c/feature-requests/13
We use this GitHub repository for tracking issues with Home Assistant documentation.

Thanks! 👍
