### ISSUE TITLE
Octoprint bed temperature

### ISSUE THREAD

**Issue by Lezcarr** [home-assistant/home-assistant.github.io#21175]
### Feedback

Octoprint

Could we have the bed temperature, as this will be a useful sensor for turning off the printer when job is completeand the bed is below 50

### URL

https://www.home-assistant.io/integrations/octoprint/

### Version

2021.12.9

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
