### ISSUE TITLE
Settings inside your Samsung Printer to get connection to HA

### ISSUE THREAD

**Issue by MikeOfGit** [home-assistant/home-assistant.github.io#21173]
### Feedback

Hey,
in the documentation I was missing the information on what network setting to activate to get the printer properly detected inside HA:

You need to activate SSPD (e.g. uPnP below Network Settings) or else HA won't get a connection to query the status.

Cheers.

### URL

https://www.home-assistant.io/integrations/syncthru/

### Version

2021.12.9

**Comment by nielstron** [comment]
hi @MikeOfGit , sorry for the late response. you can simply update the documentation yourself, there is a "edit" link on the documentation page. Should not be more effort than submitting an issue :)

However, seems to have been resolved already anyways.
