### ISSUE TITLE
Missing Figures

### ISSUE THREAD

**Issue by Bytelink5616** [home-assistant/home-assistant.github.io#21179]
### Feedback

I cannot get the current and the  recovered figures for the US.  I am trying to work out what I am doing wrong.
![Screenshot 2022-01-13 132344](https://user-images.githubusercontent.com/84490871/149387540-dfa36abd-726f-4525-a17d-e0c6fc50cd2c.png)

### URL

https://www.home-assistant.io/integrations/coronavirus/

### Version

2021.12.9

**Comment by barryhaertel** [comment]
I have the same issue, unknowns or 0 which do not reflect what JHH's website shows
![image](https://user-images.githubusercontent.com/5238672/151714637-adf6d025-e506-4244-ae4f-a7f1816e6f4d.png)

**Comment by alexbela** [comment]
Same for Germany: 
![grafik](https://user-images.githubusercontent.com/90026867/151964029-467a81e5-22dd-4810-b173-324746888304.png)

Please advise...
Kind regards!

**Comment by Bytelink5616** [comment]
This still has not been fixed

**Comment by cvicari** [comment]
The bug is still there indeed, verified with Home Assistant 2022.6.1.
This seems to be the same as [#54612](https://github.com/home-assistant/core/issues/54612)
