### ISSUE TITLE
Docker setup does not mention indefinitely growing logs

### ISSUE THREAD

**Issue by foolip** [home-assistant/home-assistant.github.io#21191]
### Feedback

I followed https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-container for a Raspberry Pi 3 with 64 GB of disk (SD card) and it's been working, but eventually I ran out of disk space because `/var/lib/docker/containers/edae0c3bd160114649725c9bae734337f38eb2ed1ee84fd0a7787c9ae0e40ced/edae0c3bd160114649725c9bae734337f38eb2ed1ee84fd0a7787c9ae0e40ced-json.log` grew indefinitely.

https://medium.com/@Quigley_Ja/rotating-docker-logs-keeping-your-overlay-folder-small-40cfa2155412 describes this problem and I'm sure there are many ways of limiting log size. Including this in the documentation would be great, since running out of disk leads to strange failure modes that are hard to understand. In my case, it became impossible to SSH into the server and I had to restart it, but it took a few cycles of this before I realized the problem was disk space, not RAM.

### URL

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-container

### Version

2021.12.9

**Comment by foolip** [comment]
The fix I'm trying is to add `--log-opt max-size=10m` to the `docker run` command.

**Comment by foolip** [comment]
That did fix the problem, but judging by https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver, `--log-driver local` might be a better recommendation. For my own part, I'm trying to fix it with `/etc/docker/daemon.json` so that I don't have to remember to do it for every container.

**Comment by foolip** [comment]
This issue has not been addressed, and I did leave a concrete suggestion for how to update the docs to avoid the problem.

**Comment by frenck** [comment]
We do not document how to set up or manage Docker daemon and system. This is not in our scope to manage?

**Comment by foolip** [comment]
A note or a warning linking out to some other resource would work fine I think. At the top of the page there's a warning about power supply, this would be a similar situation, something that's likely to go wrong if overlooked given the docker defaults.

**Comment by foolip** [comment]
> If this issue is still relevant, please let us know by leaving a comment 👍

"a comment"

**Comment by foolip** [comment]
"a comment"

**Comment by foolip** [comment]
"further activity occurs"

**Comment by ludeeus** [comment]
Docker documents this and that is where it belongs, we should not add this, you are expected to manage that on your own with this installation method.
As an alternative, you can use our OS if you do not want to manage these things yourself.
https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system
