### ISSUE TITLE
The section Install Home Assistant Supervised lists docker among the requirements

### ISSUE THREAD

**Issue by copernico** [home-assistant/home-assistant.github.io#21195]
### Feedback

The section https://www.home-assistant.io/installation/linux#install-home-assistant-supervised
lists docker among the requirements, which is sort of inconsistent with the fact that the primary reason
why one might decide to go for this installation method is precisely because they do not want (or cannot)
run docker.

**EDIT**: if you want to avoid docker, you can install 'core' instead ('supervised' does require docker).

### URL

https://www.home-assistant.io/installation/linux#install-home-assistant-supervised

### Version

2021.12.9

**Comment by frenck** [comment]
I am not sure if I understand your feedback? Could you clarify it maybe a bit?

Supervised uses Docker as part of one of the software dependencies, it's a requirement for this installation type.

**Comment by copernico** [comment]
I now understand that this option too requires docker indeed. Bottom line: home-assistant cannot be run without docker, since docker is a prerequisite for all installation methods. The implication is that, if you intend to run home assistant on an old machine on which docker cannot fun (say, my faithful 32bit Samsung NC10), bad luck! You need to find another piece of hardware (and put the NC10 back into the drawer).

**Comment by copernico** [comment]
Hi @frenck, I misunderstood the organization of the page and assumed that the method at the bottom would be the "lowest level", implying fewer dependencies (and thus allowing an installation without docker). I now understand that 'core' can indeed be installed without docker. 

The reason why I want to avoid docker is because I'm trying to upcycle the 32bit laptop that I have sitting in a drawer.

Unfortunately, as far as I understand, satisfying the requirement on python 3.9 on that 32bit machine will be as big a challenge as docker, unfortunately.

You can ignore my comment (that is why I closed the issue), I am providing this additional content in the hope that it may help someone else who might be trying to do the same as I am.
