### ISSUE TITLE
Missing dependency: ffmpeg

### ISSUE THREAD

**Issue by virgilm** [home-assistant/home-assistant.github.io#21198]
### Feedback

Why would a bare bone HA install need ffmpeg in its default installation, beats me!

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.12.9

**Comment by frenck** [comment]
Ok, thanks for your feedback, however it is not really documentation related.

**Comment by virgilm** [comment]
[doc](https://www.home-assistant.io/installation/raspberrypi/#install-home-assistant-core) says:

`sudo apt-get install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0 tzdata`

should say:

`sudo apt-get install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0 tzdata ffmpeg`

if ffmpeg is really required.
