### ISSUE TITLE
Netgear RAX45 and NetGear Integration

### ISSUE THREAD

**Issue by MollyTheLabrador** [home-assistant/home-assistant.github.io#21199]
### Feedback

Attempting to use this on a RAX45 and setting the ports to 5000 or default doesn't do anything. Set the host address as well as the user account and appropriate password but it still doesn't want to connect.

### URL

https://www.home-assistant.io/integrations/netgear/

### Version

2021.12.9

**Comment by MollyTheLabrador** [comment]
One thing that might be of importance, that I just thought about is that the router is in access point mode. From: probot-home-assistant[bot]Sent: Friday, January 14, 2022 11:40 AMTo: home-assistant/home-assistant.ioCc: MollyTheLabrador; AuthorSubject: Re: [home-assistant/home-assistant.io] Netgear RAX45 and NetGear Integration (Issue #21199) Hey there @hacf-fr, @Quentame, @starkillerOG, mind taking a look at this feedback as it has been labeled with an integration (netgear) you are listed as a code owner for? Thanks!(message by CodeOwnersMention)—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by starkillerOG** [comment]
@MollyTheLabrador 
could you try the following python script (on a PC with python installed and the pynetgear module installed)?

```
import logging
logging.basicConfig(level=logging.DEBUG, format='%(message)s')

from pynetgear import Netgear

netgear = Netgear(password="password", user="user", host="192.168.1.IP", port=5555, ssl=True)

print(netgear.login())
print(netgear.get_info())

for device in netgear.get_attached_devices():
        print(device)
```

off course fill in your password, username and IP.

If it does not work, please try these 4 combinations

- port=5555, ssl=True
- port=443, ssl=True
- port=5000, ssl=False
- port=80, ssl=False

**Comment by MollyTheLabrador** [comment]
Thanks for getting back to me, I ran the script and finally got something back with port 443 and ssl=True   Sent from Mail for Windows From: starkillerOGSent: Saturday, January 15, 2022 6:25 AMTo: home-assistant/home-assistant.ioCc: MollyTheLabrador; MentionSubject: Re: [home-assistant/home-assistant.io] Netgear RAX45 and NetGear Integration (Issue ***@***.*** you try the following python script (on a PC with python installed and the pynetgear module installed)?import logginglogging.basicConfig(level=logging.DEBUG, format='%(message)s') from pynetgear import Netgear netgear = Netgear(password="password", user="user", host="192.168.1.IP", port=5555, ssl=True) print(netgear.login())print(netgear.get_info()) for device in netgear.get_attached_devices():        print(device)off course fill in your password, username and IP.If it does not work, please try these 4 combinationsport=5555, ssl=Trueport=443, ssl=Trueport=5000, ssl=Falseport=80, ssl=False—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by starkillerOG** [comment]
@MollyTheLabrador alright, nice to hear port 443 with SSL works for you.
This PR will fix the integration for you once it is completed: https://github.com/home-assistant/core/pull/64170
(It will try port 443 with SSL as one of the possibilities and then will be able to setup the integration).

**Comment by MollyTheLabrador** [comment]
Thank you for taking are of this. I do have one request, and hopefully you can get it to the right people. Please review content before and after publishing - This process was recomended by the director of software engineering from Netgear.According to him that schould work with all Netgear routers and across firmware upgrades. In the first sentence – recomended is misspelled. It is recommended.In the second sentence, schould is misspelled. It is should Thank you again! A happy user. From: starkillerOGSent: Monday, January 17, 2022 1:58 AMTo: home-assistant/home-assistant.ioCc: MollyTheLabrador; MentionSubject: Re: [home-assistant/home-assistant.io] Netgear RAX45 and NetGear Integration (Issue ***@***.*** alright, nice to hear port 443 with SSL works for you.This PR will fix the integration for you once it is completed: home-assistant/core#64170(It will try port 443 with SSL as one of the possibilities and then will be able to setup the integration).—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by starkillerOG** [comment]
Those sentences are only in the PR discription and not in the actual code, therefore it does not really matter, but thanks for pointing it out!
My spelling is not that greath ;)

**Comment by MollyTheLabrador** [comment]
Ok, lol. Thanks
