### ISSUE TITLE
Combine the mean, min, max into one name

### ISSUE THREAD

**Issue by Wassini** [home-assistant/home-assistant.github.io#21192]
### Feedback

When showing one temperature sensor, but having mean, min and max the legend shows 3 labels. I would like the option to have just one label.
![2022-01-14_10-52-11](https://user-images.githubusercontent.com/17749701/149497626-d176490b-4fff-45f0-8ad8-be351490dba1.jpg)

### URL

https://www.home-assistant.io/lovelace/statistics-graph/

### Version

2021.12.9

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
