### ISSUE TITLE
Allow no destination for bus

### ISSUE THREAD

**Issue by j0hnby** [home-assistant/home-assistant.github.io#21207]
### Feedback

it'd be great if the destination would allow no entry as one stop can serve multiple routes - some with crossover stops which are the same on both destination, but not listed individually.

That way - we could see what bus was next at a particular stop, no matter it's final destination.  For example, three bus routes serve the stop near me, each with different final destinations, but three of them server the next five stops, two of them the next ten (ish) stops, and the then split.

The API doesn't need a destination

### URL

https://www.home-assistant.io/integrations/uk_transport/

### Version

2021.12.9

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
