### ISSUE TITLE
 Nabu Casa/HA Cloud

### ISSUE THREAD

**Issue by MeanderingWanderer** [home-assistant/home-assistant.github.io#21202]
### Feedback

"To be able to receive events from Twilio, your Home Assistant instance needs to be accessible from the web and you need to have the external URL configured in Home Assistant.."

Suggested Edit:
To be able to receive events from Twilio, Home Assistant needs to be accessible from the internet.  You may use Nabu Casa/HA Cloud, or you will need to have your external URL configured in Home Assistant.

Reasoning:   Some users are unable to configure an external URL because their ISP only provides private IP addresses.  The only solution available is to use HA Cloud.  Nabu/Cloud users do not need to configure external URL because it is completed during cloud enroll.   This could be added to all instances within docs that reference "configuring external URL".

### URL

https://www.home-assistant.io/integrations/twilio/

### Version

2021.12.9

**Comment by mrand** [comment]
Howdy, would you be interested in clicking "edit" at the bottom of that documentation page and making a pull request with proposed changes?

**Comment by MeanderingWanderer** [comment]
success!
