### ISSUE TITLE
R7000-V1.0.11.130_10.2.118 firmware doesn't work with this integration

### ISSUE THREAD

**Issue by repiuk** [home-assistant/home-assistant.github.io#21204]
### Feedback

After upgrading to R7000-V1.0.11.130_10.2.118 this integration failed. Downgrading the firmware to R7000-V1.0.11.116_10.2.100 solved this.

### URL

https://www.home-assistant.io/integrations/netgear/

### Version

2021.12.9

**Comment by starkillerOG** [comment]
@repiuk I am aware of this issue, this PR https://github.com/home-assistant/core/pull/64012 will fix the issue with the new firmware.

**Comment by klaasnicolaas** [comment]
Since the PR has been merged, we can close this issue.
