### ISSUE TITLE
GitHub link is wrong

### ISSUE THREAD

**Issue by tofgun** [home-assistant/home-assistant.github.io#21200]
### Feedback

In the documentation page, the github link still point to "https://github.com/home-assistant/core/tree/dev/homeassistant/components/tahoma" which does not exist.
If I am not mistaking it should point now to "https://github.com/home-assistant/core/tree/dev/homeassistant/components/overkiz"

### URL

https://www.home-assistant.io/integrations/tahoma/

### Version

2021.12.9

**Comment by klaasnicolaas** [comment]
The old documentation will be removed with the next release https://github.com/home-assistant/home-assistant.io/pull/20823
