### ISSUE TITLE
Can't make Upnp works !

### ISSUE THREAD

**Issue by jmcollin78** [home-assistant/home-assistant.github.io#21219]
### Feedback

Maybe It should be a good idea to inform what the ports to be used / natted.

The documentation says: "Please note that UPnP or NAT-PMP needs to be enabled on your router for this integration to work." BUt I cannot find (even with google) what ports have to be enabled.

Note that it was working in core mode (manual install) and it is not working now in Docker mode.

### URL

https://www.home-assistant.io/integrations/upnp/

### Version

2021.12.9

**Comment by frenck** [comment]
> Note that it was working in core mode (manual install) and it is not working now in Docker mode.

Sounds like you are not running the container on host networking or missing privileges on your Docker container. How do you run it?

**Comment by jmcollin78** [comment]
Exactly. I'm on docker-compose which instanciate its own network. Is the
network mode host mandatory ?

Le lun. 17 janv. 2022 à 11:38, Franck Nijhof ***@***.***> a
écrit :

**Comment by frenck** [comment]
> Exactly. I'm on docker-compose which instanciate its own network. Is the
network mode host mandatory ?

Yes, as documented in our documentation and our architectural records. Running Home Assistant without that is not supported.

**Comment by jmcollin78** [comment]
ok. Fine thank you for your quick answer
