### ISSUE TITLE
How to install the camera integration in Home assistant ?

### ISSUE THREAD

**Issue by HuguesD** [home-assistant/home-assistant.github.io#21212]
### Feedback

the camera integration is not found in the "search integration" on home assistant. There is no explanation in the documentation how to install the camera integration in home assistant.

### URL

https://www.home-assistant.io/integrations/camera/

### Version

2021.12.9

**Comment by frenck** [comment]
One doesn't. The camera integration is used by other integrations.

I agree this can be made more clear on this page.

**Comment by mrand** [comment]
@frenck, could an obvious distinction be introduced between end-user integrations and developer/helper integrations such as this one?  Maybe not call this an integration at all?  Or move it to the developers docs?  Or ????

**Comment by frenck** [comment]
> could an obvious distinction be introduced between end-user integrations and developer/helper integrations such as this one?

yes, I agreed on that already in my previous comment

> Maybe not call this an integration at all?

But it is an integration?

> Or move it to the developers docs? Or ????

That would be wrong, as it documents the properties of this integration, like service calls.

**Comment by jameshenson** [comment]
How do I integrate my cameras?  The videos reference a "arlo support" integration that must be installed before editing the configuration .yaml.   Where is this integration?  Does is exist?  

Another thread referenced an "aarlo" HAC integration that also no longer exists...   Am I missing something?

Are Arlo cameras supported?

**Comment by frenck** [comment]
> How do I integrate my cameras?

By looking at the integration page of the camera you want to integrate.

>  The videos reference a "arlo support" integration that must be installed before editing the configuration .yaml. Where is this integration? Does is exist?

https://www.home-assistant.io/integrations/arlo

> Another thread referenced an "aarlo" HAC integration that also no longer exists... Am I missing something?

I think you means HACS. HACS is a third-party tool that can be used to install custom integrations. Third-party integrations are not supported by the Home Assistant project; therefore I'm not able to answer that question.

> Are Arlo cameras supported?

See the documentation link above.

**Comment by frenck** [comment]
Closing as there was no follow-up response.
