### ISSUE TITLE
Link to source code

### ISSUE THREAD

**Issue by dcmartin** [home-assistant/home-assistant.github.io#21215]
### Feedback

I was reading the Map card documentation, but there is no link to the source code.

I would like to add `tap_action` and `hold_action` to the map card.

### URL

https://www.home-assistant.io/lovelace/map/

### Version

2021.12.9

**Comment by frenck** [comment]
> I was reading the Map card documentation, but there is no link to the source code.

That is correct, source code links are only created for integrations.

You can find the frontend source code here:

<https://github.com/home-assistant/frontend>

And of course, all this information can be found on our developer portal:

<https://developers.home-assistant.io>

../Frenck
