### ISSUE TITLE
The section on how to dump ZWave JS node ids does not work for me

### ISSUE THREAD

**Issue by hedrickbt** [home-assistant/home-assistant.github.io#21220]
### Feedback

The following from, https://community.home-assistant.io/t/z-wave-js-show-node-id/290154/8 , does work.

Versions
======
Hassio: 2021.12.9
Zwave JS: 0.1.52

Developer Template
=============
Entity ID, Node ID
{% set devices = states 
| map(attribute="entity_id")
| map("device_id")
| unique
| select("string")
| list-%}
{% for device_id in devices -%}
{% set ids = device_attr(device_id, "identifiers") -%}
{% if ids and ids | first | first == "zwave_js" -%}
{{device_entities(device_id) | first}}, {{ ids | first | last  | replace("<HOMEID>-","") }} 
{% endif -%}
{% endfor -%}

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2021.12.9

**Comment by MartinHjelmare** [comment]
The template in the docs is meant to write a dump of all the node ids of the Z-Wave integration, to prepare for a migration, not the Z-Wave JS integration.
