### ISSUE TITLE
Need Detailed instruction in setting up ESPHome manually

### ISSUE THREAD

**Issue by vikasp1000** [home-assistant/home-assistant.github.io#21225]
### Feedback

Need Detailed instruction in setting up ESPHome manually.
I am unable to configure ESPHome. 

The last step mentioned is : Follow the instruction on screen to complete the set up. 
 The steps I followed are : Configuration ->Devices & Services-> Add Integrations -> ESPHome. It asks for Host and Port. What is the host and port to be entered? 

### URL

https://www.home-assistant.io/integrations/esphome/

### Version

2021.12.9

**Comment by frenck** [comment]
I am not sure what your question is?

> What is the host and port to be entered?

That host address of the ESPHome device your are running, the port would be the port number you have exposed the ESPHome API on,
On your created ESPHomr device.

**Comment by vikasp1000** [comment]
Thanks Frenck, I figured out the host name of my ESP. Its ESP-XXXXX where XXXXXX are last 6 characters of Mac address. It would be helpful to provide help in how to find or set host name of ESP.

After giving the host name, It gave an error "Can't connect to ESP. Please make sure your YAML file contains an 'api:' line." Now I am stuck here. Please help.

**Comment by frenck** [comment]
> It would be helpful to provide help in how to find or set host name of ESP.

For that I would have to refer you to the ESPHome project, that is not a Home Assistant concern.

**Comment by vikasp1000** [comment]
I am unable to install the ESPHome Dashboard itself by following instructions given here:
https://www.home-assistant.io/integrations/esphome/#configuration

Can you help in this regard?

**Comment by frenck** [comment]
Please consult the ESPHome documentation for that.

You are linking to the Home Assistant documentation for the ESPHome integration of Home Assistant. The integration integrates an ESPHome device into Home Assistant. It does not provide ESPHome itself.

**Comment by jesserockz** [comment]
Please see https://esphome.io/guides/getting_started_hassio.html

And feel free to find us on discord, or file an [ESPHome issue](https://github.com/esphome/issues) if you have any issues :wink:
