### ISSUE TITLE
Really annoying - Home Assistant

### ISSUE THREAD

**Issue by ScotsDon** [home-assistant/home-assistant.github.io#21229]
### Feedback

I wanted to install Home Assistant to run the zigbee device CC2531.  I am a complete novice as regards this.  I followed instructions to install Docker then Home Assistant in a container (I think).  Now I want to install the Add-on broker MQTT (I think it is), so I watch videos that appear to have a Supervisor with a means to go to an Add-ons page.  I don't have a Supervisor entry, so I google why not, and find out "Add-ons are only available if you've used the Home Assistant Operating System or Home Assistant Supervised installation method. If you installed Home Assistant using any other method then you cannot use add-ons.".  WHAT!!!  This is really not helpfull.

### URL

https://www.home-assistant.io/addons/

### Version

2021.12.9

**Comment by frenck** [comment]
> so I watch videos that appear to have a Supervisor with a means to go to an Add-ons page. 

That is the problem with watching YouTube videos or following third-party tutorials. When things change, they aren't updated. This is not something we can do anything about.

You can find the Mosquitto MQTT broker add-ons (and other add-ons) at:

**Configuration** -> **Add-ons, Backups & Supervisor**. Next on the "Add-ons" tab, there is a button in the bottom right which allows you to add additional add-ons to your system.

For installing third-party add-on, additional instructions are here:

<https://www.home-assistant.io/common-tasks/supervised/#installing-third-party-add-ons>

**Comment by ScotsDon** [comment]
Franck, Thanks for your very quick reply, but it highlights precisely my problem, which is that I am unable to follow the instructions because the option is not present.  You say go to:Configuration -> Add-ons, Backups & Supervisor. Next on the "Add-ons" tab, there is a button in the bottom right which allows you to add additional add-ons to your system.But there is no “Add-ons, Backups and Supervisor” option – see attached screenshot.  Do I have an old version of Home Assistant, or what?? On a Raspberry Pi, after installing Docker and Home Assistant, what I have done  so far is: sudo apt updatesudo apt install -y mosquitto mosquitto-clientssudo systemctl enable mosquitto.serviceREBOOTThen go into Firebox on my PC and into Home Assistant.Configuration/Devices & Services+ Add Integration (bottom right)Select MQTTIt then asks me to enter:              Broker???              Port – 1881              Username????              Password???????? = what do I enter here? Is the above correct? If not, please expand.  If correct, please fill in the ????  Kind regards Donald   From: Franck NijhofSent: 17 January 2022 13:36To: home-assistant/home-assistant.ioCc: ScotsDon; AuthorSubject: Re: [home-assistant/home-assistant.io] Really annoying - Home Assistant (Issue #21229) so I watch videos that appear to have a Supervisor with a means to go to an Add-ons page.That is the problem with watching YouTube videos or following third-party tutorials. When things change, they aren't updated. This is not something we can do anything about.You can find the Mosquitto MQTT broker add-ons (and other add-ons) at:Configuration -> Add-ons, Backups & Supervisor. Next on the "Add-ons" tab, there is a button in the bottom right which allows you to add additional add-ons to your system.For installing third-party add-on, additional instructions are here:https://www.home-assistant.io/common-tasks/supervised/#installing-third-party-add-ons—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ScotsDon** [comment]
Thanks for your very quick reply, but it highlights precisely my problem, which is that I am unable to follow the instructions because the option is not present.  You say go to:
**Configuration -> Add-ons, Backups & Supervisor**. Next on the "Add-ons" tab, there is a button in the bottom right which allows you to add additional add-ons to your system.
But there is no “Add-ons, Backups and Supervisor” option – see screenshot.  

![2022-01-17](https://user-images.githubusercontent.com/67807852/149796157-f122e00a-52e1-4688-88ae-d013d5d5207c.png)

Do I have an old version of Home Assistant, or what??
 
On a Raspberry Pi, after installing Docker and Home Assistant, what I have done  so far is:
 
sudo apt update
sudo apt install -y mosquitto mosquitto-clients
sudo systemctl enable mosquitto.service
REBOOT
Then go into Firebox on my PC and into Home Assistant.
Configuration/Devices & Services
+ Add Integration (bottom right)
Select MQTT
It then asks me to enter:
              Broker???
              Port – 1881
              Username????
              Password????
???? = what do I enter here?
 
Is the above correct? If not, please expand.  If correct, please fill in the ????

**Comment by frenck** [comment]
> On a Raspberry Pi, after installing Docker and Home Assistant, what I have done so far is:

Please consult our documentation:

<https://www.home-assistant.io/installation/#compare-installation-methods>

You have installed a Home Assistant installation type that doesn't have add-ons.

**Comment by ScotsDon** [comment]
I realize that now, but at the time the implictions were unknown  Also, on the Raspberry Pi, the only option for Add-ons, according to that webpage, is the OS version, which I understand to be a cut-down stand-alone system, which I think is unsuitable as I may need to install Jeedom for an RFP1000.  Hence I want the normal Pi OS - Bullseye.  I would be gratefull if you can advise on my above question.

**Comment by ScotsDon** [comment]
I actually used this web page for the installation:

`https://www.home-assistant.io/installation/raspberrypi`

**Comment by frenck** [comment]
If you are in need for support, I suggest to join our community forums or our Discord chat server. You can find those on https://www.home-assistant.io/help.

We like to keep using GitHub for tracking issues and feedback, not for providing support.

You are more likely to get the answer you are looking for in the community places.

Thanks! 👍

**Comment by ScotsDon** [comment]
OK, thanks.
