### ISSUE TITLE
No Wifi setup proposed

### ISSUE THREAD

**Issue by Salamandar** [home-assistant/home-assistant.github.io#21236]
### Feedback

Although I understand the concerns about stability and such, wifi configuration should be proposed.
Not everyone has an ethernet cable / an ethernet port still available on the router. 
Also stability issues aren't always present. I've used wifi for 1.5 years now, with zero issues.

The only fact that wifi configuration isn't available may restrain people who would like to only test Hass for an hour and don't want too much hassle for just a test.

Configuring via wifi doesn't mean they will always use wifi. They may want to configure it, plug the usb dongles, check if everything work, then move the raspberry pi to a less-accessible location near the router where it will be connected via ethernet.

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

2021.12.10

**Comment by frenck** [comment]
We don't recommend using Wi-Fi and is therefore not part of the installation guide and should not be added to the installation guide either.

Feel free to add or open a suggestion to the Home Assistant OS common tasks page:

<https://www.home-assistant.io/common-tasks/os/>
