### ISSUE TITLE
Add HASS.Agent to the 'Support by third-party tools' list

### ISSUE THREAD

**Issue by LAB02-Admin** [home-assistant/home-assistant.github.io#21237]
### Feedback

I'd like to propose **HASS.Agent** to be added to the '[Support by third-party tools](https://www.home-assistant.io/docs/mqtt/discovery/#support-by-third-party-tools)' list on the [MQTT Discovery page](https://www.home-assistant.io/docs/mqtt/discovery/).

URL: https://github.com/LAB02-Research/HASS.Agent

### URL

https://www.home-assistant.io/docs/mqtt/discovery/

### Version

2021.12.10

**Comment by frenck** [comment]
Feel free to open up a PR for such things, especially considering you are the owner of that project...

**Comment by LAB02-Admin** [comment]
Ok 👍
