### ISSUE TITLE
Please add info on what to do or to expect to see after the configuration.yaml has been updated.

### ISSUE THREAD

**Issue by tasranson** [home-assistant/home-assistant.github.io#21247]
### Feedback

Having read all the supplied documentation, something is unclear about how to get to a working Sensibo configuration.  I have a Sensibo account with 4 Sensibo Sky devices configured.  I have created a new API key for Home assistant.

I have added the configuration as exemplified to my configuration.yaml file (at the bottom), saved the file.  
        
climate:
  - platform: sensibo
    api_key: [obscured for privacy]

I have tried this as per above, and with 
id: 
as the next line.
I have not tried to use the specific ids for my devices (since that should not be necessary).

I have Restarted HA Core, Restarted the Host (both repeatedly) and I can find nothing Sensibo related showing up under any of:

Configuration > Devices and Services > Integrations
Configuration > Devices and Services > Integrations > Add Integration
Configuration > Addons, Backups and Supervisor > System etc > Logs
Configuration > Integrations > Devices > Search for Sensibo
Configuration > Settings > Logs

Under Configuration > Settings > Info
I do see Sensibo in the list of Integrations
![image](https://user-images.githubusercontent.com/73720329/150106942-5d6543f9-0174-4807-a8c0-325f0e3c1832.png)

Is there a step I am missing that is not in the documentation?   Can the documentation be improved to tell a new user what to expect after adding the entries to configuration.yaml (ie what they should do, and what they should see) so they have some idea of whether it worked or not?

 

### URL

https://www.home-assistant.io/integrations/sensibo/

### Version

2021.12.10

### Additional information

![image](https://user-images.githubusercontent.com/73720329/150108269-2ac77262-4768-4ef1-96f9-2bb1c916270b.png)

**Comment by frenck** [comment]
All these paths you list:

```
Configuration > Devices and Services > Integrations
Configuration > Devices and Services > Integrations > Add Integration
Configuration > Addons, Backups and Supervisor > System etc > Logs
Configuration > Integrations > Devices > Search for Sensibo
Configuration > Settings > Logs
```

Are not related, as this is a manually configured integration.

You can find the climate entity it creates here here:

[![Open your Home Assistant instance and show your entities.](https://my.home-assistant.io/badges/entities.svg)](https://my.home-assistant.io/redirect/entities/)


Or in de developer tools:

[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)

**Comment by tasranson** [comment]
Franck,

Thanks, what I am asking though is that the documentation simply be updated to help a novice user understand where to look to find the result after adding the lines to the configuration.

It would be as simple as adding the following lines to the documentation after the example configuration.yaml entry.

After saving the change to the configuration.yaml file, then restart Home Assistant core, and you should find each device listed under either:

The list of Entities (Configuration > Devices and Services > Entities), - search for "climate", or

The Developer Tools (search for Sensibo)


Kind Regards,

Tas Ranson
m +61 400 223 502

**Comment by frenck** [comment]
The integration page show how to set it up, it isn't here to learn you about Home Assistant basics.

The configuration is being configured as a entity platform, thus created an entity.

**Comment by tasranson** [comment]
Franck,

I appreciate that I may not be anywhere near as skilled as you are in HA.  However, I would contend that many who want to use this integration are in the same boat, and are not sure where to look once they have made the change.  I am a skilled IT individual with over 40 years ICT experience coding in many languages, and with 6 months or so of using HA, I could not find out what to do easily.  And as it is, the integration has failed, with unavailable entities that are listed as orphans. So, I still have to work out how to sort that out.  I don't expect you to help do this, I was simply asking for a few lines of change to the documentation so that others following behind me would not repeat the same effort.

The way I see it, your response is not a very helpful one when considering the rest of the community.  I appreciate that these are all voluntary contributions, and people don't have time to do everything that everyone wants.  However, in this case, I think the change (to the documentation) would be simple and it would give a user some idea of how to check if the configuration actually worked.  As it is there is no guidance to confirm if it worked or not.  Many other integrations (most of those I have used) provide some guidance to a user as to what to do next.

I will work on figuring out how to submit the change to the documentation myself to help others.

Kind Regards,

Tas Ranson
m +61 400 223 502

**Comment by frenck** [comment]
> However, I would contend that many who want to use this integration are in the same boat, and are not sure where to look once they have made the change. 

This feedback rarely comes in, so I would think the opposite actually.

> I am a skilled IT individual with over 40 years ICT experience coding in many languages

Cool. Not sure how that is relevant 🤷 

> The way I see it, your response is not a very helpful one when considering the rest of the community.  

Sorry to hear you feel that way. We cannot teach about how Home Assistant fundamentally work on every integration page. That is not maintainable or doable. While a good suggestion, it is practically not doable and unrelated to the specific page at hand.

Dismissing my response as not helpful for the community; is IMHO unfair and uncalled for.

../Frenck
