### ISSUE TITLE
What config file

### ISSUE THREAD

**Issue by Ymsetjenesta** [home-assistant/home-assistant.github.io#21246]
### Feedback

I love the work of home assistant. But this article as so many other just assume that you know I whole bunch of stuff in HA. I have absolutley now clue what config file its pointed to here in this article.

### URL

https://www.home-assistant.io/lovelace/views/

### Version

2021.12.10

**Comment by frenck** [comment]
Depend how you manage your configuration. If you solely manage it via the UI, you could e.g., use the raw editor

![image](https://user-images.githubusercontent.com/195327/150099904-64f5b7ba-dd24-4310-8b43-ea8877fe7515.png)

Or when editing a specific card, the "show code editor" is on the button left:

![image](https://user-images.githubusercontent.com/195327/150099987-9c9d3b89-5c7d-4e63-946a-a2f39cc33219.png)

When you use Lovelace in [YAML mode](https://www.home-assistant.io/lovelace/dashboards/#using-yaml-for-the-default-dashboard) it would be the `ui-lovelace.yaml` file in your configuration folder (unless you have configured/customized a different dashboard under a different name).
