### ISSUE TITLE
Please consider adding this option to the Home Energy Management docs

### ISSUE THREAD

**Issue by btehan** [home-assistant/home-assistant.github.io#21240]
### Feedback

https://github.com/allangood/rtlamr2mqtt

I setup the above and it's working great.  Please consider adding it as an option.  Thanks!

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2021.12.10

**Comment by klaasnicolaas** [comment]
This fits more as a topic on the [community forum](https://community.home-assistant.io).
