### ISSUE TITLE
Missing version key in the manifest file

### ISSUE THREAD

**Issue by Moshiker** [home-assistant/home-assistant.github.io#21241]
### Feedback

Hi, I tried to install the component on my Homa Assitant by I got an error message:

2022-01-18 20:32:08 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'home_connect_beta' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

Please fix it

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2021.12.10

**Comment by frenck** [comment]
There is nothing to fix for us. We don't create or maintain custom integrations.

Your custom integration is missing a version.

**Comment by Moshiker** [comment]
Hi @frenck , thanks for your quick reply.
I only followed this guide: https://www.home-assistant.io/integrations/home_connect#prerequisites 
and got the error.
I didn't install a special or custom component.

**Comment by frenck** [comment]
That is the documentation for the core integration, the error you are getting is for a custom integration.

Therefore our documentation does not apply. Please consult the documentation of the custom integration you are using.

Please note that the Home Assistant project does not support custom integrations.

**Comment by frenck** [comment]
> I didn't install a special or custom component.

Apparently, you did:

> The custom integration 'home_connect_beta' does not have a version key in the manifest file and was blocked from loading.

There is no integration in Home Assistant Core that uses the `home_connect_beta` domain.

See the `custom_components` folder inside your Home Assistant configuration folder.
