### ISSUE TITLE
File platform path

### ISSUE THREAD

**Issue by msymms** [home-assistant/home-assistant.github.io#21252]
### Feedback

While examples were provided to implement a sensor with the File platform, the "path" property is a little vague.  While most of us only have the UI to see our files, it would be nice to see how a file sitting in the 'config' file structure would be sourced.  (eg. how would you reference a file in /config/www/json_file.json ?).

### URL

https://www.home-assistant.io/integrations/file/

### Version

2021.12.10

**Comment by frenck** [comment]
> While most of us only have the UI to see our files, it would be nice to see how a file sitting in the 'config' file structure would be sourced. (eg. how would you reference a file in /config/www/json_file.json ?).

I'm not sure if I follow, `/confg/www/json_file.json` is a fine example, depending a bit on the installation type one is using?

Additional this is in the description:

![image](https://user-images.githubusercontent.com/195327/150191962-9a3f1bd3-32c0-49dc-acaa-267f38bd60ce.png)

I think I'm missing the point? Could you help me out here?

**Comment by msymms** [comment]
Thanks for responding.  So, I was specifically looking at the Sensor section.  The description under file_path was a little vague so I looked at the examples.  The values shown for file_path didn't quite match up to the file structure I have so I didn't quite understand what to enter.  I do see that in the Notifications section the filename has a bit more explanation.  It was just unclear for me.

**Comment by frenck** [comment]
>  The values shown for file_path didn't quite match up to the file structure I have so I didn't quite understand what to enter. 

Home Assistant can be run in many ways, so paths will differ based on how you run it.
`/config` is fairly common, but it isn't limited to that at all.

**Comment by msymms** [comment]
Oh ok.  I've only been at this for a couple of months. Thanks Franck

**Comment by frenck** [comment]
No problem! 👍
