### ISSUE TITLE
additional feature request

### ISSUE THREAD

**Issue by mosandlt** [home-assistant/home-assistant.github.io#21267]
### Feedback

can you integrate all the sensorese and climate controll like https://github.com/tschamm/boschshc-hass

### URL

https://www.home-assistant.io/integrations/bosch_shc/

### Version

2021.12.10

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
