### ISSUE TITLE
Docs: Incorrectly Says `August Wi-Fi Smart Lock (Gen 4)` Requires Bridge or Doorbell

### ISSUE THREAD

**Issue by fishcharlie** [home-assistant/home-assistant.github.io#21261]
### Feedback

According to the documentation it says `August Wi-Fi Smart Lock (Gen 4)` Requires Connect Bridge or Doorbell.

I don't believe this is accurate as I have this device and it works fine with Home Assistant without a bridge or doorbell.

This lock connects directly to your WiFi therefore eliminating the need for a bridge.

### URL

https://www.home-assistant.io/integrations/august/

### Version

2021.12.10

**Comment by bdraco** [comment]
Yeah this one is built-in.

Here is the link to edit if you feel up to it:

https://github.com/home-assistant/home-assistant.io/edit/current/source/_integrations/august.markdown
