### ISSUE TITLE
Include the buy price of solar power produced at home

### ISSUE THREAD

**Issue by jorgezazo** [home-assistant/home-assistant.github.io#21263]
### Feedback

First of all, thank you for this integration. Is very useful to many people here in Spain after the mess of our energy tariffs. 

After that, I want to suggest the adding of another functionality at this integration. I own solar panels to produce photovoltaic energy, and I find a company which buys it at market price and not at a fixed price as most of energy companies do. The price is the same that [ESIOS](https://www.esios.ree.es/es/pvpc) shows in its web at self-consumption section. 

![image](https://user-images.githubusercontent.com/6679963/150289938-299694d3-a264-40b8-8954-26256e20ef6e.png)

![image](https://user-images.githubusercontent.com/6679963/150290014-0b6d253f-c017-43d0-bddf-5582cd30925e.png)

It's called spot market. I find out that calling the same endpoint used to get the energy at PVPC integration but without the "geo_limit" param, it returns an array of two elements. First is the Spain energy price data and second one is the Spot Market Price. 

![image](https://user-images.githubusercontent.com/6679963/150289835-98e6a7f0-8eb5-48fd-9d3e-ae6a27be77e4.png)

To get this data you have to invoke the endpoint like this:

```
https://apidatos.ree.es/es/datos/mercados/precios-mercados-tiempo-real?time_trunc=hour&start_date=2021-12-31-00:00&end_date=2021-12-31-23:59
```

Could it be possible to add this functionality to use it in energy section of Home Assistant to get the total of energy sold to power energy companies?

Thank you in advance.

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2021.12.10

### Additional information

I've tried to do it by myself, but my python knowledge is very few.

**Comment by jorgezazo** [comment]
I found the constant where endpoint's url is called to get market price data. It's at "const.py":

URL_APIDATOS_PRICES_RESOURCE = (
    "https://apidatos.ree.es/es/datos/mercados/precios-mercados-tiempo-real"
    "?time_trunc=hour"
    "&geo_ids={geo_id}"
    "&start_date={start:%Y-%m-%dT%H:%M}&end_date={end:%Y-%m-%dT%H:%M}"
)

I think a ternary at "&geo_ids={geo_id}" line similar to this geo_id ? "&geo_ids={geo_id}" : "" would do the trick.

The calling service (get_url_prices) is at "parser.py" and should be modified to return the spot market prices into another structure type. But have not python knowledge.

**Comment by dunemm3** [comment]
I'm interested in this functionality too

**Comment by fcasarramona** [comment]
Here another guy interested. Thanks for your job.

**Comment by Mr-Alicates** [comment]
I'm also interested 👍

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
