### ISSUE TITLE
Note about multiple connections no longer valid after latest firmware release

### ISSUE THREAD

**Issue by jefvlamings** [home-assistant/home-assistant.github.io#21265]
### Feedback

The note below is not longer valid:

> Note that it's not possible to have multiple connection to the bridge at the same time. This integration will keep the connection open, and if you open the app, it will ask you to disconnect Home Assistant. If you close the app again, Home Assistant will reconnect automatically.

Zehnder release a firmware upgrade which makes it possible to have multiple connections to the gateway.

### URL

https://www.home-assistant.io/integrations/comfoconnect/

### Version

2021.12.10

**Comment by michaelarnauts** [comment]
@jefvlamings correct, but I think that a new firmware is only available when you use the beta app, or has this recently been changed?

**Comment by XinoGitHub** [comment]
New firmware is available to ALL
