### ISSUE TITLE
yearly_energy_total returns same value as monthly_energy_total

### ISSUE THREAD

**Issue by keithfrank** [home-assistant/home-assistant.github.io#21273]
### Feedback

When I implement the VeSync Integration.
my EtekCity "Voltson Smart WiFi Outlet" Model # ESW15-USA
returns the following attributes and values:

**current_power_w: 0.98
today_energy_kwh: 0.0227
voltage: 121.48
weekly_energy_total: 0.1412
monthly_energy_total: 0.38
yearly_energy_total: 0.38
icon: mdi:power-socket-us
friendly_name: Laundry Room Dehumidifier**

The "monthly_energy_total" attribute returns the exact same value as "yearly_energy_total"

Additionally the attribute values returned for "monthly_energy_total" and  "yearly_energy_total" are limited to two decimal places when in the VeSync Mobile app all energy values display values to 4 decimal places.

### URL

https://www.home-assistant.io/integrations/vesync/

### Version

2021.12.10

**Comment by frenck** [comment]
Hi there @keithfrank 👋 

Sorry for not seeing this before.

> The "monthly_energy_total" attribute returns the exact same value as "yearly_energy_total"

It seems like you want to report a bug, however, you have submitted documentation feedback. So this is in the wrong place. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
