### ISSUE TITLE
Yale Smart Living

### ISSUE THREAD

**Issue by ZunaidPatel** [home-assistant/home-assistant.github.io#21278]
### Feedback

I have cently been required to reconfigure Yale Smart Living integration Daily,

Is there a means to not have to do this daily

### URL

https://www.home-assistant.io/integrations/yale_smart_alarm/

### Version

2021.12.10

**Comment by gjohansson-ST** [comment]
See here https://github.com/home-assistant/core/issues/62992
This issue is reported in the documents which is the wrong place so this issue should be closed.

**Comment by frenck** [comment]
Closing this, as it is an issue report. See the above listed issue to follow progress.
