### ISSUE TITLE
Consider Population in "Statistics World Map"

### ISSUE THREAD

**Issue by retomarek** [home-assistant/home-assistant.github.io#21271]
### Feedback

Hello all

I would find it very exciting to be able to optionally display the statistics data on the world map in a different way, e.g. to see number of installations per 100,000 inhabitants of the country or number of installations per 100,000 households. The USA would no longer stand out, but rather the Netherlands and Iceland.

https://en.wikipedia.org/wiki/List_of_countries_by_number_of_households

Cheers,
Reto

### URL

https://www.home-assistant.io/integrations/analytics/

### Version

2021.12.10

### Additional information

![HA Installations per Inhabitants and Households](https://user-images.githubusercontent.com/68020526/150422050-dd8e517e-ca09-4eb7-af75-cbdc09456d25.PNG)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
