### ISSUE TITLE
Somfy Integration does not show Terrace Products

### ISSUE THREAD

**Issue by abrocker** [home-assistant/home-assistant.github.io#21286]
### Feedback

Somfy Integration in my Case does not show the Terrace Products. It only shows the "Protect" Products like Window Blinds.

### URL

https://www.home-assistant.io/integrations/somfy/

### Version

2021.12.10

**Comment by tetienne** [comment]
This is the documentation repository.

Anyway, the Somfy API only expose Thermostat and blind. 

Instead, try https://github.com/iMicknl/ha-tahoma

**Comment by abrocker** [comment]
Thank you!
