### ISSUE TITLE
Twitter token secret?

### ISSUE THREAD

**Issue by tnrclkr** [home-assistant/home-assistant.github.io#21280]
### Feedback

Twitter does not give any token secret while creating app. what should be there?

### URL

https://www.home-assistant.io/integrations/twitter/

### Version

2021.12.10

**Comment by tnrclkr** [comment]
![image](https://user-images.githubusercontent.com/48097971/150509000-a3f85e16-ac36-4169-ae35-91b1cf27fc5f.png)

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by klaasnicolaas** [comment]
The documentation could be improved on this because nowadays, you have to do a few additional actions to get those tokens.

**Comment by frenck** [comment]
Are you aware of those @klaasnicolaas? If so, maybe you could add them?
