### ISSUE TITLE
old - can be used 

### ISSUE THREAD

**Issue by FARKIr** [home-assistant/home-assistant.github.io#21298]
### Feedback

please renew it when you become a lite more space 

thy ... you all are great !!

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2021.12.10

**Comment by frenck** [comment]
> please renew it 

I'm not sure what you mean by that? Could you please clarify what your suggestion is?

**Comment by frenck** [comment]
Closing this issue, as there has been no response.
