### ISSUE TITLE
Error in Somfy RTS section

### ISSUE THREAD

**Issue by salsaman** [home-assistant/home-assistant.github.io#21294]
### Feedback

In the Somfy RTS section, there is an error in the example, "04" should be "03".

### URL

https://www.home-assistant.io/integrations/rfxtrx/

### Version

2021.12.10

**Comment by elupus** [comment]
Can you provide a fix in the homeassistant.io repository ?

**Comment by salsaman** [comment]
Yes, if you remind me how to do that.

**Comment by elupus** [comment]
You edit the file here: https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/rfxtrx.markdown

You can probably do it online. Otherwise clone and do locally.

**Comment by salsaman** [comment]
I think it would be good also to add a comment explaining that the device can be added by entering the value described in the Event Code field, and pressing Submit.
