### ISSUE TITLE
Link to breaking changes is not helpful

### ISSUE THREAD

**Issue by mjsambol** [home-assistant/home-assistant.github.io#21306]
### Feedback

Step 2 in the Upgrade section directs users to review breaking changes between releases. Unfortunately the link is to a page which makes no mention of breaking changes. As far as I can tell, there is no one place to review breaking changes between releases. The user must visit the blog post for each release and review the breaking changes there. 

It would be very convenient to have the breaking changes listed together with the new features on the "releases" page.

### URL

https://www.home-assistant.io/common-tasks/core/

### Version

2021.12.10

**Comment by frenck** [comment]
Thanks for the suggestion, however, that is indeed what it is now. The breaking changes sections are also tweaked at times. Maintaining multiple locations of the same thing is not something we want to do.
