### ISSUE TITLE
verify USGS earthquake feed

### ISSUE THREAD

**Issue by stmoose** [home-assistant/home-assistant.github.io#21302]
### Feedback

trying to get working
shows location on map with no earthquakes - tried last month - nothing shown

### URL

https://www.home-assistant.io/integrations/usgs_earthquakes_feed/

### Version

2021.12.10

**Comment by exxamalte** [comment]
I can confirm that this integration still works.
Could you please share the configuration including your rough coordinates (don't need to know where exactly you live, but maybe the coordinates of the nearest town).
And could you please confirm whether or not you see any `geo_location` entities in the Developer Tools?

**Comment by stmoose** [comment]
i have 
geo_location:
 - platform: usgs_earthquake_feed
    feed: past_month_all_earthquakes
    latitude: 61.27
    longitude: -149.9


the earthquake card was showing but centered on Amsterdam with no earthquakes shown so I created a zone as follows
zone: AK
    latitude: 61.27
    longitude: -149.9
    radius: 15000
    passive: false


i also tried with passive as true - still nothing

in the card i have

type: map
geo_location_sources:
  - usgs_earthquakes_feed
entities:
  - zone.AK
title: Nearby Earthquakes - AK


zone.AK does show as a geo_location 

thanks for any help

**Comment by exxamalte** [comment]
Thanks for the additional information.
This integration's default radius is 50 kilometres, i.e. it only shows earthquakes within this radius around the configured coordinates.
I'd recommend trying a larger radius - maybe 500 or 1000km?

**Comment by stmoose** [comment]
SOLVED

poked around at this tonight
discovered that zone.home was Amsterdam (still dont know why, but that is besides the point) updated the coordinates to my coordinates for zone.home and created a zone.home for Anchorage AK and now have earthquakes showing in AK

**Comment by exxamalte** [comment]
Great to hear. 
A suggestion for next time you have trouble with an integration: In general you have a better chance of people helping in the [Home Assistant community forum](https://community.home-assistant.io/). Here on GitHub I guess you were just in luck that I am the registered code owner of this component and got notified, but this may not always be the case.

**Comment by mrand** [comment]
@stmoose, If you feel there are minor improvements that could be made to the documentation, would you be interested in clicking "edit" at the bottom of that documentation page and making a pull request with proposed changes?
Otherwise, please go ahead and close this issue.
