### ISSUE TITLE
Homekit Example YAML does not work

### ISSUE THREAD

**Issue by szaske** [home-assistant/home-assistant.github.io#21301]
### Feedback

It looks like you've moved away from using the "-" character, but if I include ```- filter:``` the HA complains about formatting. 

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2021.12.10

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want help with a setup, you should try our [Community Forum: Configuration](https://community.home-assistant.io/c/configuration/11).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
