### ISSUE TITLE
GPSD Platform does not work due to lack of "sudo" in HassOS

### ISSUE THREAD

**Issue by wreuvers** [home-assistant/home-assistant.github.io#21317]
### Feedback

Hi

The instructions on how to get the GPSD Platform working, by installing with the command
$ sudo systemctl status gpsdctl@ttyUSB0.service
fails due to the key issue that sudo is not available in Hassio

Thanks
Wayne

### URL

https://www.home-assistant.io/integrations/gpsd/

### Version

2021.12.10

**Comment by frenck** [comment]
Well its not the fact "sudo" is missing, but more on  how the platform works.

This integration would only be available on setups running that are running the Home Assistant Core installation type. Other installation types (like Home Assistant Container, Home Assistant OS and Home Assistant Supervised), this integration won't be usable.

The page need to be adjusted to make that clear.

**Comment by wreuvers** [comment]
Hi Frenk

Is it because I am running Home Assistant on a Rasberry Pi4+? How can I access the GPS dongle to be able to use this HA as my yacht assistant?

Thanks
Wayne

**Comment by frenck** [comment]
> Is it because I am running Home Assistant on a Rasberry Pi4+? How can I access the GPS dongle to be able to use this HA as my yacht assistant?

The Rapsberry Pi is not really the deciding factor. The Home Assistant installation method used is the deciding factor (as I wrote above).

**Comment by wreuvers** [comment]
Apologies for my ignorance, but I presumed I am running Home Assistant Core - as I see the "Core" panel in the System Menu. I now see that there is a different installation option called Home Assistant Core.

**Comment by wreuvers** [comment]
Just to confirm: There is no way to use GPSD when running Home Assistant Operating System?

**Comment by fabaff** [comment]
> There is no way to use GPSD when running Home Assistant Operating System?

Not an easy one. Could probably be solved by a "GPS addon" which acts as an intermediary between `gpsd` and Home Assistant OS.

**Comment by frenck** [comment]
> Apologies for my ignorance, but I presumed I am running Home Assistant Core - as I see the "Core" panel in the System Menu. I now see that there is a different installation option called Home Assistant Core.

You are definitely running the Core itself on your system, however, I was not referring to software, but the type of installation used.

<https://www.home-assistant.io/installation/#compare-installation-methods>
