### ISSUE TITLE
Torque now has support for bearer token

### ISSUE THREAD

**Issue by PulsarFX** [home-assistant/home-assistant.github.io#21315]
### Feedback

The documentation describes how to set up the integration with password via GET.
This is now obsolete, as torque provides a field to define a bearer token, when HTTPS is used.
From https://torque-bhp.com/forums/?wpforumaction=viewtopic&t=3.0
```
Changes in 1.10.249 (5-Jan-2022)
...
Add Authorization: Bearer token option for https: connections in web logging
....
```

Furthermore, this field can be any string, it doesn't have to be a valid email address: https://www.home-assistant.io/integrations/torque#email  

### URL

https://www.home-assistant.io/integrations/torque/

### Version

2021.12.10

**Comment by mrand** [comment]
If this doesn't require any change to the integration itself, would you be interested in clicking "edit" at the bottom of that documentation page and making a pull request with proposed change(s)?

**Comment by PulsarFX** [comment]
Will do so. There are still some issues with the bearer token on the torque side in v.  1.12.32 that need to be fixed first to be of any use for HA.

**Comment by okjed** [comment]
> Will do so. There are still some issues with the bearer token on the torque side in v. 1.12.32 that need to be fixed first to be of any use for HA.

Where can this be tracked on the Torque side? I spent some time hoping to leverage the bearer token but didn't get into the weeds debugging.

**Comment by PulsarFX** [comment]
The link is in the first post. 
Torque version 1.12.46 (4-Feb-2022)  has a fix, so the bearer token is actually saved and sent. 
I still have to verify that I can receive data in HA, though. 
At least "Login attempt or request with invalid authentication" is gone from the HA logs. ;)

**Comment by PulsarFX** [comment]
opened PR [21543](https://github.com/home-assistant/home-assistant.io/pull/21543)
