### ISSUE TITLE
documentation not in line with software

### ISSUE THREAD

**Issue by dirksenrdh** [home-assistant/home-assistant.github.io#21327]
### Feedback

Here:

> To create your first automation based on a blueprint, go to Configuration and then Blueprints. Find the blueprint that you want to use and click on **“Create Automation”.** 

the documentation refers to a "button" **Create Automation**.
I am running 2021.12.3 and in the indicated page I only have the button **Import Blueprint**
to me this is a bit confusing.
Of course it can be that in 2021.12.10 this is changed...

### URL

https://www.home-assistant.io/docs/automation/using_blueprints/

### Version

2021.12.10

**Comment by dannytsang** [comment]
@dirksenrdh I believe the documentation is correct. Each automation type blueprint has a "Create Automation" in the 4th column highlighted in orange below. Can you check and confirm you are able to see the same?

![image](https://user-images.githubusercontent.com/567982/151245566-b9b7f984-b264-4e6c-9938-1c26653a72d5.png)

**Comment by dirksenrdh** [comment]
@dannytsang you are absolutely right. I am sorry for my remark. I just looked in the wrong place.
regards
