### ISSUE TITLE
...but why

### ISSUE THREAD

**Issue by stevehurcombe** [home-assistant/home-assistant.github.io#21324]
### Feedback

I couldn't work out why I'd want to do this, so it would be good to link to the original (and may be more) blog entries.

I know I could Google this, but the easier you make adoption then the more users you get. Especially for newbies browsing...

### URL

https://www.home-assistant.io/integrations/cast/

### Version

2021.12.10

**Comment by stevehurcombe** [comment]
I did find this eventually:
https://www.home-assistant.io/blog/2019/07/09/home-assistant-cast-preview/

**Comment by frenck** [comment]
> I couldn't work out why I'd want to do this, so it would be good to link to the original (and may be more) blog entries.

> I know I could Google this, but the easier you make adoption then the more users you get. Especially for newbies browsing...

Yeah, but uh... what is the feedback? What is missing? Which part/functionality are you looking for that you could not find?

Having feedback is great, but some context would help.

Thanks 👍

**Comment by stevehurcombe** [comment]
Some introduction text explaining what it is intended to do. With a link to a blog too ideally. If you're lucky you might be able to link to a query for blog entries with a Cast tag, but we're not often that lucky.

I was thinking "Having a media player in Home Assistant doesn't make any sense. It's a dashboard of my smart things, why is Google Cast there?". 

It's not functionality, it's "marketing"...

**Comment by frenck** [comment]
It that case I'm still not sure what you are trying to say. 🤷 

It allows you to control and integrate Google Cast capable devices into Home Assistant.

**Comment by stevehurcombe** [comment]
I can think of no good reason why I'd want to do that. Lights, switches, sensors, but Google cast? Make no sense. I nearly deleted it because it seemed useless, just something the code found.

However I perservered, the blog says this:

"It will work with any Cast enabled device, and if available, will allow the user to use the touch screen to interact with the interface. The interface is built with Lovelace, so it’s the same powerful features and real-time interaction that you are used to today."

That's the light bulb moment. Now it makes sense. 

I see now that there is the one sentence (quite a long way down the page). "Home Assistant has its own Cast application to show the Home Assistant UI on any Chromecast device.". Then it goes on to talk about casting iPlayer and I'm even more confused. 

It's not a biggie, just trying to boost HA by making these more powerful, but non-obvious, features more discoverable.

**Comment by frenck** [comment]
> I can think of no good reason why I'd want to do that.

That is a personal opinion. The cast integration is actually used by 40%+ of our user base, which makes it one of the most used integrations out there.

Most use cases are actually as a plain media player (for example, to send TTS messages to).

**Comment by stevehurcombe** [comment]
> That is a personal opinion. 

By that I mean that I haven't discovered what those good reasons are, not that I think there really are no good reasons. Clearly there are otherwise the documentation wouldn't be this good. Which is also why I'm today's PITA - I care. 

This is the answer (well one) I'm looking for:
> Most use cases are actually as a plain media player (for example, to send TTS messages to).

So you are saying they set HA up on a tablet just to play a selection of videos and streams? 
I would never have realised that by looking at the HA web site. That's a useful use case...

**Comment by frenck** [comment]
> So you are saying they set HA up on a tablet just to play a selection of videos and streams?

Announcements actually mostly. E.g., playing a doorbell sound or letting Google speakers announce the washing machine is ready, time for bed, or other stuff.

Examples on TTS: <https://www.home-assistant.io/integrations/tts/#service-say>

But those are generic media player features, not specific to cast.
