### ISSUE TITLE
Is there any interest in supporting Ring Alarm and/or its sensors ?

### ISSUE THREAD

**Issue by jmporter34** [home-assistant/home-assistant.github.io#21333]
### Feedback

This is actually a question rather than a comment on the documentation, which says clearly which Ring devices are supported.  But I didn't know where else to ask whether there's any interest in the Ring Alarm and its sensors.  
BTW I've got 30 years of embedded C/C++, but so far I'm only using HA, not developing for it.  I'm willing to pitch in if somebody could show me where to start in this environment.  
Thank you

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2021.12.10

**Comment by frenck** [comment]
Hi there @jmporter34 👋 

Thank you for your interest. This is not really a documentation suggestion for the end-user documentation, as you have submitted feedback for that.

That said, all our development documentation can be found here:

<https://developers.home-assistant.io/>

Specifically how to get started with setting up a development environment: <https://developers.home-assistant.io/docs/development_index>

I could recommend joining our [Discord chat server](https://discord.gg/c5DvZ4e) if you have an additional question on this. We have dedicated channels for developer support there.

Thanks! 👍

../Frenck
