### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MickPBduece** [home-assistant/home-assistant.github.io#21330]
### Feedback

Great integration - I'd like to have ability to see multiple locations.  I understand there is a limit to call to the API but would like to see a couple places at same time each day. 

### URL

https://www.home-assistant.io/integrations/openuv/

### Version

2021.12.10

### Additional information

Thanks for consideration

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
