### ISSUE TITLE
Thanks devs for this integration!

### ISSUE THREAD

**Issue by berkavil** [home-assistant/home-assistant.github.io#21346]
### Feedback

Thanks devs for this Integration !
I can confirm it also works with Klarstein split A/C 

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.12.10

**Comment by berkavil** [comment]
tested here: https://community.home-assistant.io/t/klarstein-air-conditioning-integration-please/305838

**Comment by cmroche** [comment]
I'll update the docs this weekend, thanks for the info.

**Comment by berkavil** [comment]
Hallo did you update the doc ? I dont see Klarstein in the models list below, 
but right - it is working with GREE+ so maybe it is considered under it...
I will not push it further... unsubscribibg here and thanks indeed for the integration.
Bye
W.

=== list of supported models ===
Supported models
Any Gree Smart device working with the Gree+ app should be supported, including non-Gree branded devices such some sold by:

Trane
Innova
Cooper & Hunter
Proklima
Tadiran
