### ISSUE TITLE
Elgato Light Transition not working

### ISSUE THREAD

**Issue by misse** [home-assistant/home-assistant.github.io#21340]
### Feedback

When calling light.on with transition set, the elgato light will instantly change settings to match the desired state, so the transition is always less than 1 second, ignoring the set transition

### URL

https://www.home-assistant.io/integrations/elgato/

### Version

2021.12.10

**Comment by frenck** [comment]
> When calling light.on with transition set, the elgato light will instantly change settings to match the desired state, so the transition is always less than 1 second, ignoring the set transition

That is correct, Elgato lights do not support transitioning. They have a configurable global parameter for it (but not exposed in their app settings), but they don't support passing it in when turning on or off the light.
