### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by MissedLegend** [home-assistant/home-assistant.github.io#21363]
### Feedback

Followed every Single Step to Install the "Home Assistant Operating System". SD Carf only got one tiny 32mb Partition. If the PI startet, i get the same Error Code every time. Tried 3 SD Cards. Adding a partition and the OS won't even start right

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2021.12.10

### Additional information

ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2021.12.10: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2021.12.10&fromImage=ghcr.io%2Fhome-assistant%2Fraspberrypi4-64-homeassistant: Internal Server Error ("Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")
22-01-27 19:06:28 WARNING (MainThread

**Comment by MissedLegend** [comment]
well... forgot to enter the Error
ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2021.12.10: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2021.12.10&fromImage=ghcr.io%2Fhome-assistant%2Fraspberrypi4-64-homeassistant: Internal Server Error ("Get "https://ghcr.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")
22-01-27 19:06:28 WARNING (MainThread)

**Comment by frenck** [comment]
This is not an hardware issue, but an network issue.

> net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

It is unable to connect to `ghcr.io` (which is the GitHub Container Registry to download Home Assistant).
