### ISSUE TITLE
Efergy API Key

### ISSUE THREAD

**Issue by nlpmartins** [home-assistant/home-assistant.github.io#21361]
### Feedback

Get API key from engage. efergy.com - tokens. Try to insert Efergy API Key, but receive the following info: Failed to connect. No Log is visible related with this issue

### URL

https://www.home-assistant.io/integrations/efergy/

### Version

2021.12.10

**Comment by tkdrob** [comment]
Does it fail immediately or does it timeout? If you don't mind, could you please provide the API key for troubleshooting? You can find me on discord if you are not comfortable posting it here.

Another user once had to contact Efergy support about not having their account properly tied to their device. This could be your issue as well.

**Comment by nlpmartins** [comment]
Hi @tkdrob ,
Thank you for your fast answer. it fails immediately. Here it is an activated token: w0kclAXFz4mRnZ8PAM_psiMkiqEhLoCu
Best regards,
Nuno

**Comment by tkdrob** [comment]
It looks like there is something wrong with your efergy setup. I am seeing no real-time statistics. I have some tweaks I'm working on but that will not solve your issue. The issue is with your device.

**Comment by tkdrob** [comment]
Are you setting up the hub for the first time? Any feedback on our documentation is appreciated.

**Comment by nlpmartins** [comment]
Hi Robert,

I have this hub for more than 5 years. Can see values in efergy app... Can
you setup the efergy module in HA? What other documentation you need?

Best regards,
Nuno Martins

**Comment by tkdrob** [comment]
There is nothing more I can do. @Data-Monkey is a user of the integration. He may be able to weight in about how to get help from customer support.

**Comment by Data-Monkey** [comment]
Hi,
you seem to only have a power generated channel, not a consumption one.

if I run these I get some failure on the current consumption for your token.

```
set TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
>curl "https://www.energyhive.com/mobile_proxy/getStatus?token=%TOKEN%"
{"hid":"067a268a371e582de305039753a49293","listOfMacs":[{"listofchannels":[{"assoc":1,"cid":"cid.D8803956CB71","reading":null,"ts":1643675356,"tsDelta":5,"tsHuman":"Tue Feb  1 00:29:16 2022","type":{"battery":5,"falseBattery":0,"id":null,"name":"EFCT"}}],"mac":"D8803956CB71","personality":"E1","status":"on","ts":1643675356,"tsDelta":5,"tsHuman":"Tue Feb  1 00:29:16 2022","type":"EEEHub","version":"3.7.1"}]}
```
this returns almost the same as my token, but you have a newer version.

```
>curl "https://engage.efergy.com/mobile_proxy/getCurrentValuesSummary?token=%TOKEN%"
[{"cid":"PWER_GAC","data":[{"1643675356000":3150}],"sid":"783323","units":"W","age":7}]
```
here I get a cid:"PWER" while you get PWER_GAC that I think represents generated power, rather than consumed.

```
>curl "https://engage.efergy.com/mobile_proxy/getInstant?token=%TOKEN%"
{"status":"error","desc":"Method call failed"}
```
getInstant is looking for the current consumption that is missing from your data

```
>curl "https://engage.efergy.com/mobile_proxy/getEnergy?offset=600&period=day&token=%TOKEN%"
{"sum":"0.00","duration":52140,"units":"kWh"}
>curl "https://engage.efergy.com/mobile_proxy/getBudget?token=%TOKEN%"
{"status":"ok", "monthly_budget":100.0000}
>curl "https://engage.efergy.com/mobile_proxy/getCost?offset=600&period=day&token=%TOKEN%"
{"sum":"0.00","duration":52140,"units":"GBP"}
```

I had some issues before when my hub actually did not send any data to efergy because it disconnected or the battery in the sensor was flat. 
Can you check that the dashboard on the web actually works? 
Maybe you can share a screenshot?

hope this helps

for your reference here are the commands I run (Windows Command Prompt)

```
set TOKEN=xxxxxxxxxxxxxxxxxxxx
curl "https://www.energyhive.com/mobile_proxy/getStatus?token=%TOKEN%"
curl "https://engage.efergy.com/mobile_proxy/getCurrentValuesSummary?token=%TOKEN%"
curl "https://engage.efergy.com/mobile_proxy/getInstant?token=%TOKEN%"
curl "https://engage.efergy.com/mobile_proxy/getEnergy?offset=600&period=day&token=%TOKEN%"
curl "https://engage.efergy.com/mobile_proxy/getBudget?token=%TOKEN%"
curl "https://engage.efergy.com/mobile_proxy/getCost?offset=600&period=day&token=%TOKEN%"
```

**Comment by nlpmartins** [comment]
Hi Roland,

Thank you for your overview on this issue. Actually I had this sensor in a
power generation unit, probably that's the reason for this label. Neverthe
less, I've now removed and created a new sensor, classifying it as
Globak Consumption - the real use - currently.

In HA I keep having errors, now it's the following:
[image: image.png]
Using this token:Kws4XJNx9aRq7VyhQo4_QMZtrNugaOUP

My dashboards are ok:
[image: image.png]
The only thing that isn't working for a long time it's the total
consumption and cost so far...

Mainly I would like to have in HA the instantaneous consumption (note, I've
multiplied Voltage value per 10 - use 2300 instead of 230 to increase the
resolution of the value seen in dashboard).

If you can provide me more guidance to be able to include this in HA would
be fine.

thank you in advance,
Nuno Martins

Roland Beck ***@***.***> escreveu no dia terça, 1/02/2022
à(s) 00:52:

**Comment by Data-Monkey** [comment]
Hi Nuno, the images did not work, could you please try to edit your post and add the pictures?

**Comment by Data-Monkey** [comment]
it seems your sensor in Efergy is still considered GAC
```
curl "https://engage.efergy.com/mobile_proxy/getCurrentValuesSummary?token=%TOKEN%"
[{"cid":"PWER_GAC","data":[{"1644545934000":3380}],"sid":"783323","units":"W","age":8}]
```
and there is no instant reading response
```
curl "https://engage.efergy.com/mobile_proxy/getInstant?token=%TOKEN%"
{"status":"error","desc":"Method call failed"}
```

**Comment by nlpmartins** [comment]
Hi Robert,

After some consultancy with Efergy, I could connect my HUB to HA, the
problem it's the connection its not continuous, although the HUB it's
always connected in Engage:


At the moment I could integrate Efergy in my HA, but after a while it
stopped working. Restarted and it's the same...
As you can see below, for a while I could receive values - on the graph.
But now it's all unavailable.

[image: image.png]

[image: image.png]
[image: image.png]

[image: image.png]
[image: image.png]

Do you have an Idea why this is occurring?

The second problem it's I can't find those items on energy menu:
[image: image.png]

Efergy token: i3ZeZ9Hn65VA7zUsadFRbMLwLITFb8hP

Thank you in advance,
Nuno Martins

Roland Beck ***@***.***> escreveu no dia sexta, 11/02/2022
à(s) 02:21:

**Comment by tkdrob** [comment]
Your images did not go through. At what point does this typically happen? Please confirm that this is power generation? What power units are we talking about here, kWh?

**Comment by nlpmartins** [comment]
Hi Robert,

Thank you for your fast answer.

Do you have a regular email I can send you, so you can receive the images?

I have no power generation.

I have one circuit its the total consumption from my house, and two other
that are sub- circuits.

Total Consumption= circuit 1 + circuit 2
(Should be... But in measurements not always true)

Best regards,
Nuno Martins

A quinta, 17/03/2022, 19:28, Robert Hillis ***@***.***>
escreveu:
