### ISSUE TITLE
Multiple utility meters configuratin

### ISSUE THREAD

**Issue by dominikkaniapl** [home-assistant/home-assistant.github.io#21374]
### Feedback

Hello,

Is it possible have multpile utility meters instances? Like 1 to measure daily energy for fridge, another to measure daily energy for a TV, etc.? 
I was trying to find a way to set it up in HA and it was unsuccessful - every combination ends up with an error message and I have not found any material on how to do it properly.

my example:

"utility_meter:
  daily_energy_serverroom:
    name: Energy_Serwerroom_energy_daily
    source: sensor.serwerroom_socket_energy
    cycle: daily
  daily_energy_moisturizer:
    name: Energy_moisturizer_energy_daily
    source: sensor.moisturizer_socket_energy
    cycle: daily"
. . . and so on.

Thanks,

Dominik

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2021.12.10

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
