### ISSUE TITLE
Question - write error?

### ISSUE THREAD

**Issue by berkavil** [home-assistant/home-assistant.github.io#21373]
### Feedback

Hallo again, sorry for my dumb qiestion, I juste noticed, that since I have added this integration, sometimes the write errors appear in the HA log - the original log in CZ here:
===============
Connection was closed unexpectedly
14:19:09 – (CHYBA) /usr/local/lib/python3.9/site-packages/greeclimate/network.py - zpráva se poprvé objevila v 14:04:09 a zobrazuje se 28 krát
Error doing job: Fatal write error on datagram transport
14:19:09 – (CHYBA) /usr/src/homeassistant/homeassistant/runner.py - zpráva se poprvé objevila v 14:04:09 a zobrazuje se 28 krát
===============

During one day (24 hours) it appears approx 1800 times... 
Do you plz have any clue why this error appears and/or how it can be repaired?
Thank you indeed.
Vilem

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2021.12.10

**Comment by klaasnicolaas** [comment]
Hi there @berkavil 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by berkavil** [comment]
Hallo, OK thank you for the reply, I sent the issue to the HA/core as you wrote, lets see if there is any clue - how to solve it.

 

BR.

Vilem
