### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by gerbenf1** [home-assistant/home-assistant.github.io#21379]
### Feedback

hello,

how can i change the date from year month day to  day month year?
or add this option please

### URL

https://www.home-assistant.io/integrations/twentemilieu/

### Version

2021.12.10

**Comment by frenck** [comment]
All integrations providing dates or dates+time, are using the iso standards. This makes them al the same and predictable.

The frontend of home Assistant will render it based on your settings.

If you want to use is else where, templates can be used to change formats to anything you like.
