### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by kalina-p** [home-assistant/home-assistant.github.io#21370]
### Feedback

Two heaters controlled by an app.
 1. Relatively new - when you enter it, it has a blue background, simple interface - temperature on, off
 2. Bought much earlier (I enclose the screen)

 In case # 1, the integration works great.  In case 2, when the heater is turned off, it switches it to the antifrost mode (there are 3 modes) and it does not turn it on until the comfort mode is set again in the tuya application.  Has anyone come across this?

please help
![C8F3FA1A-1C92-49AE-9A18-19DBA902998A](https://user-images.githubusercontent.com/78249685/151502376-127c1d79-1edc-404c-9874-d79f395afde1.jpeg)

### URL

https://www.home-assistant.io/lovelace/thermostat/

### Version

2021.12.10

**Comment by frenck** [comment]
Hi there @kalina-p 👋 

It seems like you want to report an issue with a Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:
<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
