### ISSUE TITLE
disabled entities

### ISSUE THREAD

**Issue by nightmare1111** [home-assistant/home-assistant.github.io#21382]
### Feedback

this caught me out i could not get the set a preset automation to work because i was copying the yaml, but if i had used the UI i would have not been able to find select.wled_preset because its a disabled entity by default

### URL

https://www.home-assistant.io/integrations/wled/

### Version

2021.12.10

**Comment by frenck** [comment]
The preset select entity is not disabled by default.

<https://github.com/home-assistant/core/blob/956ceb6c684ae16334395a6fc6e5488ea75313fa/homeassistant/components/wled/select.py#L74-L102>
