### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by sblessley** [home-assistant/home-assistant.github.io#21389]
### Feedback

Under "actions" HA presents a potential list of targets, but not the opportunity to enter a free-form entity name "entity_id: all". Also, "blueprint" is an new option when an automation is added. This is not reflected in the documentation.

### URL

https://www.home-assistant.io/getting-started/automation/

### Version

2021.12.10

**Comment by frenck** [comment]
I agree, this part can use some updates.

> but not the opportunity to enter a free-form entity name "entity_id: all".

This is when in YAML mode, which can still be accessed from the tree-dots menu.
