### ISSUE TITLE
How does one create a button entity?

### ISSUE THREAD

**Issue by Qoheleth** [home-assistant/home-assistant.github.io#21385]
### Feedback

While the Button page explains important things like state, services, etc., there is no explanation of how to actually create a button entity.

### URL

https://www.home-assistant.io/integrations/button/

### Version

2021.12.10

**Comment by klaasnicolaas** [comment]
At the moment it is only possible for integrations to create button entities. With the next release it is possible to create a button helper.

**Comment by frenck** [comment]
As listed on this page:

![image](https://user-images.githubusercontent.com/195327/151779325-e4d78f96-86bb-4587-b177-60a874fcf879.png)

The `button` entities cannot be created manually.
