### ISSUE TITLE
remove addon

### ISSUE THREAD

**Issue by jon-bondy** [home-assistant/home-assistant.github.io#21398]
### Feedback

How does one remove an addon that one no longer needs?

### URL

https://www.home-assistant.io/addons/

### Version

2021.12.10

**Comment by frenck** [comment]
Basically, the same way as one installs add-ons. Click on the add-on you desire to install (or uninstall), and click the install button (or uninstall button for removal).

The install button becomes an uninstall button once the add-on is installed.
