### ISSUE TITLE
Why does it not show HI and LOW temp for TODAY?  only shows forecast hi and lows

### ISSUE THREAD

**Issue by terren272** [home-assistant/home-assistant.github.io#21395]
### Feedback

New user to hassio on pi 3B
Why does this card not show HI and LOW temp for TODAY?  
It only shows forecast hi and lows which is not helpful for TODAY.
The example shows this, but not the card that I created on my hassio dashboard. 
 I need the hi and low for TODAY please.  thanks!  how?
can't attach a photo here, so ?

### URL

https://www.home-assistant.io/lovelace/weather-forecast/

### Version

2021.12.10

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
