### ISSUE TITLE
"Check Configuration" no longer available in Config > Server Control

### ISSUE THREAD

**Issue by knwpsk** [home-assistant/home-assistant.github.io#21402]
### Feedback

This page could be improved
https://www.home-assistant.io/docs/configuration/

It tells me I can/should test my config changes using command line, and points to the OS/Supervised/Container/Core pages. Those pages give me a very basic idea how to access the command line... but say nothing about how to test my config. More notes here about how to test config (once in command line) would be helpful.

Then it says you can test changes to your configs in the UI using Configuration > Server Control > "Check Configuration".
Only "restart" exists on that page; there is no "test configs" button. (Yes, restart automatically includes a check; but newbies like me may not know it.) (Also, would be nice if that Control page had a bit of text to explain what happens when you click Restart!)

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2021.12.10

**Comment by mrand** [comment]
Would you be interested in clicking "edit" at the bottom of that documentation page and making a pull request with proposed changes?

**Comment by knwpsk** [comment]
@mrand I would be very happy to do that, but am unfamiliar with how to make a pull request and submit changes. Also I don't know how the command line test works, so need help with that part anyway before I could document it. 
If you want to educate me, I'm willing.

**Comment by mrand** [comment]
The edit process actually leads you through github's PR steps quite well.  If you have to go back and alter things after submitting, it takes a few more steps, but still not bad.  I'm happy to help you through any questions.

As for the command-line-interface, I agree that it's not as obvious as it could be.
The following are the ways I'm aware of accessing the CLI:

1. On setups with supervisor present, install a GUI add-on that provides cli (most common: one of the terminal&ssh add-on's, or visual studio)
2. If the REST API is enabled, looks like a [POST can be issued](https://developers.home-assistant.io/docs/api/rest/)
3. Presumably if enabled and configured properly, you could ssh to the core and do it as well

Anyway, once there, you simply issue the command.

`ha core check 
`
(side note: it takes CONSIDERABLY longer than the GUI-based check).

BTW, there were two ways to figure that command out:
* Using the context sensitive help in the cli (type 'ha help', then 'ha core help')
* this one line mention: https://www.home-assistant.io/common-tasks/os#configuration-check

Building upon this issue you are flagging, my opinion, the common-tasks page is not really laid out well either.
CLI is defined 25% into the page [and it's only defined in the middle of paragraph about add-ons], yet the term is used earlier in the page.  It seemingly randomly uses CLI in some spots, "command line" in others, and "command line interface" in a few others.  It would be better if, early in the document, it was defined and a link was provided which jumps to explictly explaining how to access it.

Here it is being executed on visual studio:
![image](https://user-images.githubusercontent.com/435987/152657936-d80485f5-2339-44e5-9386-1a9a78c96b12.png)
