### ISSUE TITLE
Sense integration not working

### ISSUE THREAD

**Issue by Lippy2929** [home-assistant/home-assistant.github.io#21404]
### Feedback

Trying to install Sense energy monitor integration
Username and password are correct but it fails every time.  Tried manually to setup integration and tried the integration with the button. Failed to connect is what I get?????

### URL

https://www.home-assistant.io/integrations/sense/

### Version

2021.12.10

**Comment by frenck** [comment]
Hi there @Lippy2929 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with Home Assistant integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
