### ISSUE TITLE
Daikin requires port 80 to be open as well

### ISSUE THREAD

**Issue by blanchie42** [home-assistant/home-assistant.github.io#21416]
### Feedback

Documentation improvement reqest for the Daikin AC integration, for the "Configuration" section.

I had an issue getting HA to work with my Daikin AC after opening the required autodiscover ports 30000/30050, I also had to open port 80 so:

From Home Assistant to the Daikin controller: TCP:<random port> => 80
From the Daikin controller to Home Assistant: TCP:80 => <random port>

It’s sorta implied that it’s using a web http protocol, but it’s nice to be explicit if the suggestion to open other ports is present so it's not accidentally overlooked.

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2021.12.10

**Comment by fredrike** [comment]
I've not seen any other integrations that mentions required ports. But feel free to update the docs.
