### ISSUE TITLE
Home page blurb about data staying local is confusing

### ISSUE THREAD

**Issue by nchammas** [home-assistant/home-assistant.github.io#21429]
### Feedback

On the home page there is [a blurb describing how Home Assistant handles data][1]:

> Home Assistant keeps your data local, no need for a cloud.
> 
> Home Assistant communicates with your devices locally, and will fallback to pulling in data from the cloud if there is no other option. No data is stored in the cloud, and everything is processed locally.

It's confusing because "no data is stored in the cloud" is preceded immediately by "will fallback to pulling data from the cloud". These two statements seem contradictory.

It would be great if this blurb could be reworded to eliminate the confusion. In addition, there should be a "Learn More" link immediately underneath the blurb to a page where people can read the details of how Home Assistant keeps their data local, under what circumstances exactly is anything sent to the cloud, etc. This would match the structure of the other blurbs -- short description + link to go deeper -- and give the reader more details on this headline feature of the system.

[1]: https://github.com/home-assistant/home-assistant.io/blob/cb6c892e0f0012f2ed90484cd670f4a00a81eabf/source/_includes/custom/features.html#L60-L68

### URL

https://www.home-assistant.io

### Version

 2021.12.10

**Comment by nchammas** [comment]
This issue is still relevant.

**Comment by frenck** [comment]
> Home Assistant keeps your data local, no need for a cloud.

The intentions are correctly reflected. We keep data local, we are not sending it to the cloud.

You are confusing pulling and storing/processing data.

**Comment by nchammas** [comment]
@frenck - I don't see how your response addresses the concern raised in this issue.

The home page currently says:

> and will fallback to pulling in data from the cloud if there is no other option

How can you pull data from the cloud if it's not stored there? This is an obvious question anyone reading that blurb will ask. When exactly does the system "fallback" to the cloud (e.g. does it happen quietly or does it require explicit human permission)? And if it falls back to the cloud, doesn't that mean the cloud is getting your supposedly-local data? Also, who exactly owns the servers in this "cloud"?

I'm sure there are reasonable answers to these questions. My point is that a newcomer to the project who lands on your homepage will not be able to answer those questions by reading the blurb that is currently there. It raises more questions than it answers. And there is no link from the blurb to read more detail about privacy or data locality.

I am assuming that the intended audience for the homepage is people who do not currently use Home Assistant and are looking to learn the basics about the project. If that is indeed the case, then I believe the data locality blurb needs some improvement.

> You are confusing pulling and storing/processing data.

I don't understand what you mean by this.

**Comment by frenck** [comment]
> How can you pull data from the cloud if it's not stored there? 

That is not our concern or an implementation detail of Home Assistant.
If you want to know how a cloud provider, of your choice, handles your data; please ask them.
