### ISSUE TITLE
components/#all sorting is case sensitive

### ISSUE THREAD

**Issue by danielperna84** [home-assistant/home-assistant.github.io#2142]
If you have a look at the list of [all](https://home-assistant.io/components/#all) components you'll notice, that at the very end (after Z) you'll find some components which should be somewhere up in the list (like aREST, iCould etc). I assume the reason for this is the sorting mechanism, which sorts by the ASCII value, where upper case characters have lower values than lower case characters.
In Python I would do the sorting like this: `sorted(components, key=lambda x: x.lower())`. Don't know how that would be done here though.

**Comment by fabaff** [comment]
The component page is powered by a Javascript that is doing the sorting thing.

**Comment by bdurrer** [comment]
This was solved with #2277 (and solved a second time with #2287)
