### ISSUE TITLE
Detected integration that called async_timeout.timeout

### ISSUE THREAD

**Issue by ton10g** [home-assistant/home-assistant.github.io#21426]
### Feedback

Hi, today I got this warning:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 15:04:05 (1 occurrences)
Last logged: 15:04:05
Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.2. Please report issue for edl21 using this method at homeassistant/components/edl21/sensor.py, line 163: await self._proto.connect(self._hass.loop)

Not sure if I understand this right be maybe someone can look into this? Thank you.

### URL

https://www.home-assistant.io/integrations/edl21/

### Version

2021.12.10

**Comment by mtdcr** [comment]
Duplicate of https://github.com/home-assistant/core/issues/62253, fixed by https://github.com/home-assistant/core/pull/63664

**Comment by frenck** [comment]
Closing as a duplicate :)

Please note, this issue tracker is for tracking documentation feedback, not for reporting issues.

Thanks! 👍

**Comment by ton10g** [comment]
Thank you!
