### ISSUE TITLE
Setup Media for Linux Ubuntu/Debian

### ISSUE THREAD

**Issue by SickProdigy** [home-assistant/home-assistant.github.io#21432]
### Feedback

So to mount external locations or mounting a different media folder, symlinks seem to work.

ln -s /srv/media ~/.homeassistant

This command worked wonders. I have 20 tb of data in a raided drive and leaving a symlink file named media in the .homeassist folder seemed to link the media browser. Figured that'd be worth adding to the documentation. 

### URL

https://www.home-assistant.io/more-info/local-media/setup-media/

### Version

2021.12.10

**Comment by frenck** [comment]
Thanks for the suggestion! However, I'm going to skip on it.
There are many ways to put folders into place in Linux. Alternatively one could mount a drive directly in place, or even use bind mounts.

The point of the documentation here (for the Home Assistant Core part) is to show what the path is. Beyond that, I don't think it is up to us to provide instructions or a manual on Linux system administration.

../Frenck
