### ISSUE TITLE
Implementing Device Tracking after phasing out Known_Devices.yaml

### ISSUE THREAD

**Issue by sudogirl** [home-assistant/home-assistant.github.io#21438]
### Feedback

The page explains that the "known_devices.yaml" has been phased out as of late. However, it does not provide an alternative way of implementing devices to be tracked or a link to a related page. 

### URL

https://www.home-assistant.io/integrations/device_tracker/

### Version

2021.12.10

**Comment by ppeyronnel** [comment]
Still valid. No explanations as to what will replace known_devices.yaml

**Comment by klaasnicolaas** [comment]
The alternative option is to set up via an integration in the UI

**Comment by kryptonitecb3** [comment]
What about services that don't have a UI integration?

I know it's not officially supported, but one of my most used trackers is the iPhone Device Tracker from HACS (https://github.com/mudape/iphonedetect). Without it the other officially supported network trackers would have all my iOS devices as not_home after 5-15 minutes of not being used.

**Comment by klaasnicolaas** [comment]
Then you use the `device_tracker` platform with yaml code, as can be seen in the integration you named from HACS. So yes, alternative methods have certainly been described so it is unknown to me what the feedback was in this issue.

Maybe our page could use an update, but know_devices.yaml has been EOL a long time ago.

**Comment by LordNex** [comment]
Nmap is a good replacement

**Comment by kryptonitecb3** [comment]
> Then you use the `device_tracker` platform with yaml code, as can be seen in the integration you named from HACS. So yes, alternative methods have certainly been described so it is unknown to me what the feedback was in this issue.
> 
> Maybe our page could use an update, but know_devices.yaml has been EOL a long time ago.

I misunderstood and thought device_tracker yaml integration was being removed.

**Comment by mbugert** [comment]
> it is unknown to me what the feedback was in this issue.

One issue is that the page lacks instructions on how to actually get going with tracking devices after one has added an integration that doesn't rely on `known_devices.yaml` anymore.
For example, with nmap tracker: After nmap tracker finds devices, their entities show up disabled by default, and their settings tab says "This entity is unavailable." for each one. It took me a long time of trial & error to figure out how to make it work: one has to click on an entity, unfold "Advanced settings" on the bottom, and manually set the entity status to Enabled.

Currently, neither the device tracking nor the nmap tracker documentation points out why entities appear disabled or how to fix it. The [2022.02 release notes](https://www.home-assistant.io/blog/2022/02/02/release-20222/#improved-handling-of-device-tracker-entities) do hint at this procedure, but it doesn't explain where or how to make the changes, and is unlikely to be found by users setting up their device tracking.
