### ISSUE TITLE
Can't figure out the sendevent from this documentation

### ISSUE THREAD

**Issue by LCMilstein** [home-assistant/home-assistant.github.io#21445]
### Feedback

The yaml snippet for how to use the sendevent is incomplete... When putting that code in a script, there's a malconfiguration error. 

At the same time, putting the command itself into a button using the adb_command service call yields no noticeable response from the TV device.

Finally, putting the yaml on this page into the action of an automation and clicking "run action" also yields no response (and that's using the proper entity that works with the more standard "slow" command configuration.

Can you update to explain better how to use this faster response code via adb?

### URL

https://www.home-assistant.io/integrations/androidtv/

### Version

2022.2.0

**Comment by vingenuity** [comment]
I'm also having issues trying to use `sendevent`, but a different kind. I'm trying to control an NVIDIA Shield TV on the latest 9.0 update (Android TV 11), and I can "successfully" control it somewhat using either `command: RIGHT` or `command: input keyevent KEYCODE_DPAD_RIGHT`. However, I cannot get commands working with `sendevent`.

I can get the correct event sequence using `androidtv.learn_sendevent`: `sendevent /dev/input/event5 4 4 786500 && sendevent /dev/input/event5 1 105 1 && sendevent /dev/input/event5 0 0 0 && sendevent /dev/input/event5 4 4 786500 && sendevent /dev/input/event5 1 105 0 && sendevent /dev/input/event5 0 0 0`. However, putting that sequence in as a command does not seem to do anything.

Interestingly, I also cannot get the command to work via an adb shell either. The response I receive when trying to send any event to `/dev/input/event5` is `sendevent: /dev/input/event5: Permission denied`. Perhaps `sendevent` can no longer be used without superuser access in Android TV 11? Or was root always required and that step is just missing in the documentation?

Thanks for any info y'all can provide!

**Comment by Roei639** [comment]
Joins the issue

**Comment by Roei639** [comment]
is there an update?

**Comment by LCMilstein** [comment]
@JeffLIrion  or @ollo69 any direction/help here?

**Comment by Roei639** [comment]
👍
