### ISSUE TITLE
Add instructions for turning on XMPP in Harmony Hub

### ISSUE THREAD

**Issue by cliffjao** [home-assistant/home-assistant.github.io#21444]
### Feedback

It took me a while to figure out that I need to turn on XMPP developer option in Harmony Hub to get this working. It'd be good to add that into the docs.

### URL

https://www.home-assistant.io/integrations/harmony/

### Version

2022.2.0

**Comment by bdraco** [comment]
Thanks for the edits

We used to recommend XMPP because we were worried about Logitech changing websockets, but now that Logitech has discoed Harmony and websockets is actually a bit more stable, its probably better to use websockets.

**Comment by cliffjao** [comment]
On my setup, websockets never seemed to work. I had to turn on XMPP before I finally got the integration working.

**Comment by bdraco** [comment]
Here is the link to edit the docs if you feel up to it

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/harmony.markdown

**Comment by cliffjao** [comment]
Pull request: https://github.com/home-assistant/home-assistant.io/pull/21484
