### ISSUE TITLE
UDM base does not run Unifi Protect

### ISSUE THREAD

**Issue by ArnoutD** [home-assistant/home-assistant.github.io#21449]
### Feedback

UniFi protect integration documentatiemateriaal: A UDM base is unable to run UniFi Protect

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2022.2.0

**Comment by bdraco** [comment]
Fixes would be appreciated.  Here is the link to edit

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/unifiprotect.markdown

Thanks 👍
