### ISSUE TITLE
No files at stated location

### ISSUE THREAD

**Issue by tabbertmj** [home-assistant/home-assistant.github.io#21446]
### Feedback

This appears to be outdated info as the files do not exist in either location.

### URL

https://www.home-assistant.io/faq/sdcard_files/

### Version

2022.2.0

**Comment by frenck** [comment]
> This appears to be outdated info as the files do not exist in either location.

Just looked at it, the documentation on that page is correct and valid.

**Comment by frenck** [comment]
Closing this issue/suggestion because of the above. Please let me know if you think otherwise and with an alternative suggestion in a response.
