### ISSUE TITLE
august integration

### ISSUE THREAD

**Issue by Oumpa31** [home-assistant/home-assistant.github.io#21450]
### Feedback

August log in no longer works it looks like they force 2 factor login. Wish there was a way to just add it to the HomeKit Controller without an ipad.

### URL

https://www.home-assistant.io/integrations/august/

### Version

2022.2.0

**Comment by frenck** [comment]
Hi there @Oumpa31 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here: <https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
