### ISSUE TITLE
Display values in GB instead of MB

### ISSUE THREAD

**Issue by Motordom** [home-assistant/home-assistant.github.io#21458]
### Feedback

It would be great if we could display values for NBN data in GB rather than MB (or have a switch)

### URL

https://www.home-assistant.io/integrations/aussie_broadband/

### Version

2022.2.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
