### ISSUE TITLE
Possibility to reconfigure Locations / Example for Card / Full warning message content should be delivered !

### ISSUE THREAD

**Issue by chiefmaster81** [home-assistant/home-assistant.github.io#21460]
### Feedback

It would be useful to be able to edit/change the Locations after config is finished isntead of having to delete it and newly integrate it.

Also an example Card to have all necessary information would be a great deal, including the full warning message's content !

### URL

https://www.home-assistant.io/integrations/nina/

### Version

2022.2.0

### Additional information

Tried to build a card on my own with custom:entity-attributes-card:

entity-attributes-card

type: vertical-stack
title: NINA - Warnungen Köln
cards:
  - type: entity
    entity: binary_sensor.warning_koln_stadt_1
  - type: custom:entity-attributes-card
    heading_name: ' '
    heading_state: ' '
    filter:
      include:
        - key: binary_sensor.warning_koln_stadt_1.Sent
        - key: binary_sensor.warning_koln_stadt_1.Headline
          name: Thema
        - key: binary_sensor.warning_koln_stadt_1.ID
        - key: binary_sensor.warning_koln_stadt_1.Start
          name: Beginn
        - key: binary_sensor.warning_koln_stadt_1.Expires
          name: Ende

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
