### ISSUE TITLE
Deprecating rpi gpio - wwwhhhyyyyy :-)

### ISSUE THREAD

**Issue by KTHconsult** [home-assistant/home-assistant.github.io#21467]
### Feedback

Is the support seriously being removed for rpi gpio in home assistant?
I get that the usage count might not be high but the impact for us users can be quite high.
A year ago I rebuild the entire heating system I my house using these io ports and home assistant. It works perfect with 
switch:
  - platform: rpi_gpio
    ports:…

and

climate LivingRoom:
  - platform: generic_thermostat
    name: LivingRoom
    heater: switch.a3_floorheat_livingroom
    target_sensor: sensor.velux_sensor_temperature…

I even sold the idea to one of my colleges so now Im kind of in troubles!
What can I do to keep this working going forward? You usually have very nice alternatives when you deprecates stuff, I very much I doubt thought what to do in this situation?

### URL

https://github.com/home-assistant/architecture/blob/780ea1b180263fce7b08805c019dd580f3db6fe2/adr/0019-GPIO.md

### Version

2022.2.0

**Comment by frenck** [comment]
> Is the support seriously being removed for rpi gpio in home assistant?

Yes, as per announcement in the release notes.

> What can I do to keep this working going forward? You usually have very nice alternatives when you deprecates stuff, I very much I doubt thought what to do in this situation?

Alternative routes have been given in the release notes. As for the `rpi_gpio`, there is already a custom integration available in HACS as a replacement.
