### ISSUE TITLE
20RESC genset_total_energy high

### ISSUE THREAD

**Issue by jonschwenn** [home-assistant/home-assistant.github.io#21468]
### Feedback

Thanks for making this integration available. My 6 month old 20kW Kohler generator has only run for 9.7 total hours (weekly tests). 

The genset_total_energy is reporting as 2,111,688.5 kWh which seems really high.

### URL

https://www.home-assistant.io/integrations/oncue/

### Version

2022.2.0

**Comment by bdraco** [comment]
It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍
