### ISSUE TITLE
Owned repositories available to track by default (like the starred ones currently)

### ISSUE THREAD

**Issue by maxwroc** [home-assistant/home-assistant.github.io#21461]
### Feedback

Currently only the starred repos are on the list. I think it make sense to include, on the list, owned repos too. 

I use this integration mainy to track my repos and TBH I don't want to star my own repos just because of this integration.

There should be a way to add repo url manually. What is the point of having a fixed lits (such limit)?

### URL

https://www.home-assistant.io/integrations/github/

### Version

2022.2.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by maxwroc** [comment]
Created this topic - pasting it for other people who might be interested
https://community.home-assistant.io/t/github-integration-improvements-ha-2020-2/388098
