### ISSUE TITLE
Test scenario

### ISSUE THREAD

**Issue by hansjochensen** [home-assistant/home-assistant.github.io#21463]
### Feedback

Danke  fuer diesen wichtigen Beitrag.
1) Please provide a list of attributes to the sensor, so I can prepare a readout.
2) An example yaml would be even more welcomed.
3) Is there a way to test and verify  the setup, without waiting for a desaster warning

### URL

https://www.home-assistant.io/integrations/nina/

### Version

2022.2.0

**Comment by DeerMaximum** [comment]
> 1. Please provide a list of attributes to the sensor, so I can prepare a readout.

- ATTR_HEADLINE: Headline of the warning
- ATTR_ID: ID of the warning
- ATTR_SENT: Time when the warning was sent
- ATTR_START: Time when the warning became effective
- ATTR_EXPIRES: Time when the warning expires

> 2. An example yaml would be even more welcomed.

There is no example yaml

> 3. Is there a way to test and verify the setup, without waiting for a desaster warning

There is no best way, but currently you can simply use the corona warnings with the corona filter turned off. 
If that's not enough, just select a few cities and regions and see if there are warnings there.


I hope I was able to help you.

And by the way, what kind of readout are you preparing?
