### ISSUE TITLE
Add setup instructions for server

### ISSUE THREAD

**Issue by mclever** [home-assistant/home-assistant.github.io#21475]
### Feedback

Add some text on the integration setup screen about the add-on that is needed for the server

### URL

https://www.home-assistant.io/integrations/rtsp_to_webrtc/

### Version

2022.2.1

**Comment by allenporter** [comment]
My impression is that integrations typically don't explain how to setup add-ons to run the servers they integrate with.  They may work with a standalone server or an add-on.

Am I wrong about that? Is there prior examples of this?

This is what the [community forum post](https://community.home-assistant.io/t/add-on-rtsptoweb-and-rtsptowebrtc/387846) is for that explains how to set up the add-on.

Edit: Added link to community forum post

**Comment by frenck** [comment]
We can, e.g., link to external resources (e.g., the rtsp server project) documentation.

**Comment by allenporter** [comment]
Yeah, ok, that is all linked already and it has setup instructions, though they could always be improved.  Closing.
