### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by koldogut** [home-assistant/home-assistant.github.io#21471]
### Feedback

After upgrading to HA ver 2022.2.0 Unifi Protect integration stoped working and reconfiguration keeps saying invalid authentication. I've tried to change once and again the username and password in Unifi but no luck. No logs or further error information is provided.

I'm running HA core as a docker container and Unifi protect in a UDM-Pro

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2022.2.0

**Comment by AngellusMortis** [comment]
Wrong repo. You want the [core repo](https://github.com/home-assistant/core)

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/issues/65591
