### ISSUE TITLE
Not enough information 

### ISSUE THREAD

**Issue by briangunderson** [home-assistant/home-assistant.github.io#21482]
### Feedback

A walkthrough with screenshots would really help people out here. 

### URL

https://www.home-assistant.io/integrations/roomba/

### Version

2022.2.1

**Comment by frenck** [comment]
Forgive me my ignorance, but it's a single click, select the Roomba to add and done?
Or am I missing something?

**Comment by briangunderson** [comment]
Thanks for the quick response! It appears the integration is designed to be
a single click, but in practice (my experience, anyway) both of my Roombas
(j7+ vacuum and m6 mopping robot) fail at the step where a physical button
is to be pressed on the roomba in order to allow it to accept a new
connection. Upon failure, a link is provided to a page that begins to
describe the manual process that must be followed in the event that the
automatic process is unsuccessful. That page is where I feel the
documentation leaves a bit to be desired. I would happily help to edit the
documentation however I have been unable to figure out how to make it work.
I have acquired keys via the dorita980 process for a previous experiment
(not related to HA) and understand the gist of how it all works but I'm
unclear as to what parameters the HA integration is really requesting since
the documentation doesn't explicitly call it out. When I run the script
from dorita980 I get both a BLID and a password. However neither of them
seem to make the integration work. Do I need to somehow concatenate them?

Thanks!
Brian
