### ISSUE TITLE
Possible to make a script to trigger a pattern seletion?

### ISSUE THREAD

**Issue by SeldomSeen31** [home-assistant/home-assistant.github.io#21480]
### Feedback

I love my Fibonacci 256 and that I can control it from my home assistant dashboard.  I'm new to this so it is entirely possible that I'm missing something.  I have some WLED lighting that I've built and a couple of scripts that I've set to buttons in Lovelace to trigger some WLED presets, I have a red, green, blue, purple and rainbow preset buttons that calls some specific mood lighting effects.  I would love to be able to add the evil genius labs piece to this by calling the patterns, Fire Fibonacci, Snow Twinkles, etc. In the scripting for my devices there are only options for on, off, toggle, and brightness.  Is there a way to make a pattern selection?

### URL

https://www.home-assistant.io/integrations/evil_genius_labs/

### Version

2022.2.1

**Comment by SeldomSeen31** [comment]
I understand that this is not a common integration, but any help with how a command can be written to select a specific preset would be very helpful.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
