### ISSUE TITLE
Where do you put service call code?  How do I apply this?

### ISSUE THREAD

**Issue by terren272** [home-assistant/home-assistant.github.io#21507]
### Feedback

Where do you put service call code?  How do I apply this?  In what context?
I'm sure this is helpful somehow, but it is all useless to us if we don't know where to put it.  
In my hassio configuration.yaml ?  
In my device's sonoffbasic.yaml ?  
In my other device's featherhuzzah.yaml ?

Neither of these pages give usable examples, or say where to put the code, or how, so we spend HOURS trying to figure out the most basic of implementations.  
https://www.home-assistant.io/docs/scripts/service-calls/
https://www.home-assistant.io/integrations/homeassistant#services

This is in my sonoffbasic.yaml file and is the only working attempt I've been able to accomplish.
I would like to find a configuration.yaml solution, so I don't have to go around reprograming all my devices every time I want to change something.  Please help by giving usable examples in this and other pages, thanks.

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"         #  BUTTON   INPUT
    on_press:
      - switch.toggle: relay
      - homeassistant.service:        # THIS IS WORKING, sonoff BUTTON to HUZZAH RED LED
           service: homeassistant.toggle
           data:
             entity_id: switch.red_led_gpio0_huzzah_2

  

### URL

https://www.home-assistant.io/docs/scripts/service-calls/

### Version

2022.2.2

**Comment by dannytsang** [comment]
@terren272 the first paragraph in your first link states it can be used when 

> calling a service when an automation trigger happens. But a service can also be called from a script, a Lovelace dashboard or via voice command devices such as Amazon Echo.

source: https://www.home-assistant.io/docs/scripts/service-calls/

I agree the examples which I don't mind looking into. I can't help you with your sonoffbasic.yaml example because I haven't used gpio integration and you might get a better, more specific help on this if you post on the community site if you haven't done so already.
