### ISSUE TITLE
Does it work in version 2022.2.2?

### ISSUE THREAD

**Issue by mcsidor** [home-assistant/home-assistant.github.io#21509]
### Feedback

how to make it work in version 2022.2.2?

### URL

https://www.home-assistant.io/integrations/shell_command/

### Version

2022.2.2

**Comment by frenck** [comment]
Thank you for reaching out. Sure, this does work, however, we use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
