### ISSUE TITLE
LG Web OS integration fails

### ISSUE THREAD

**Issue by RadekLorenc** [home-assistant/home-assistant.github.io#21502]
### Feedback

After updating HA to 2022.2.2 LG WebOS integration dont work properly. Can't power on the device via WOL service (before update everything works fine).

### URL

https://www.home-assistant.io/help/reporting_issues/

### Version

2022.2.2

**Comment by klaasnicolaas** [comment]
Hi there @RadekLorenc 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
