### ISSUE TITLE
A note here would be very helpful

### ISSUE THREAD

**Issue by bignadad** [home-assistant/home-assistant.github.io#21503]
### Feedback

homeassistant:
  packages: !include_dir_named packages

I have this implementation for my home Assistant.

I then have packages folder with subfolders and yaml files that look like this:
packages
--customize
----media.yaml
----tv.yaml
----lights.yaml
--functions
----media.yaml
--integrations
----lights.yaml

If you have yaml's named the same in multiple folders it won't pick up the second one. 
I went through the packages documentation and didn't see any note about this.
Maybe it's common knowledge but I spent a lot of time trying to figure out why some of my entities and integrations weren't loading and a note would have saved a lot of time.

### URL

https://www.home-assistant.io/docs/configuration/packages/

### Version

2022.2.2

**Comment by frenck** [comment]
It depends a bit on how you set it up. If you use the filename as the key of the mappings, yeah, duplicate filenames would cause them to overwrite each other. That is how YAML works?

**Comment by bignadad** [comment]
k, no problem. I was not familiar with that so did not know. if a note it not needed then disregard.
