### ISSUE TITLE
System monitor for Esp8266 or Esp32 ?  Only works for Raspberry pi ?

### ISSUE THREAD

**Issue by terren272** [home-assistant/home-assistant.github.io#21516]
### Feedback

It there a System monitor for Esp8266 or Esp32 ?  
I'm only able to get system monitor working for Raspberry pi 3b using hassio.
Please advise, thanks.

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2022.2.2

**Comment by frenck** [comment]
For doing stuff with ESP8266 or ESP32, we can recommend looking at our sister project: ESPHome.

<https://www.esphome.io>

ESPHome integrates perfectly with Home Assistant.

../Frenck
