### ISSUE TITLE
Needs more info

### ISSUE THREAD

**Issue by HemiBob** [home-assistant/home-assistant.github.io#21517]
### Feedback

When using a service to force an update of the Restful the syntax looks like this:
**service: rest.reload
data: {}**
But if I don't want to refresh ALL my rest sensors, what goes in the curly brackets, I can't see that documented.
Is it a list of the rest sensors and if so, an example would be useful

### URL

https://www.home-assistant.io/integrations/rest/

### Version

2022.2.2

**Comment by frenck** [comment]
> But if I don't want to refresh ALL my rest sensors

You can't.

> what goes in the curly brackets, I can't see that documented.

Nothing, hence its not documented either.

Sorry, but it isn't documented because your suggested use doesn't exist.

../Frenck

**Comment by HemiBob** [comment]
Thanks for your reply, much appreciated.
Maybe it can be added one day.
