### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by skynan22** [home-assistant/home-assistant.github.io#21513]
### Feedback

I tried to connect PVOutput Integration within Home Assistant with my PVOutput account but I get always an error "connection failed - Verbindung fehlgeschlagen". 
I used both API key and the read only key as u can see below together with the corresponding System ID of my PV - what can I try next? 

### URL

https://www.home-assistant.io/integrations/pvoutput/

### Version

2022.2.2

### Additional information

<img width="541" alt="Bildschirmfoto 2022-02-06 um 13 08 17" src="https://user-images.githubusercontent.com/6624641/152680321-7579dcee-6bb8-4106-bdfd-c0e22d5da5e8.png">

<img width="605" alt="Bildschirmfoto 2022-02-06 um 13 17 37" src="https://user-images.githubusercontent.com/6624641/152680372-21b221b8-97d9-4995-81e4-e43e857e547c.png">

**Comment by jsahoka** [comment]
As far as I know, you only need to use the readkey. So dont combine them.
