### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by grhawk** [home-assistant/home-assistant.github.io#21523]
### Feedback

I am using Home-Assistant installed into k8s. 
I cannot find the open-meteo integration among the other integrations and if I try to install it from the website I get the error:  "Config flow could not be loaded". 

Could you help pls?

### URL

https://www.home-assistant.io/integrations/open_meteo/

### Version

2022.2.2

**Comment by frenck** [comment]
Thank you for reaching out. We use this GitHub issue tracker for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
