### ISSUE TITLE
Add support for password 'for all users on network'

### ISSUE THREAD

**Issue by air720boarder** [home-assistant/home-assistant.github.io#21535]
### Feedback

I share my home wifi network with 9 individuals, and password protect my Airplay settings in my AppleTV app. It would be helpful to add password support, so I can protect others from connecting to my AppleTV, while enabling HomeAssistant to manage my device.

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2022.2.3

### Additional information

Alternatively, if you can make AppleTV recognize HomeAssistant as a HomeKit user, that would be even better!

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
