### ISSUE TITLE
Toon smartplug integration 

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#21546]
### Feedback

I do mis the smartplugs in the integration of Toon. 

### URL

https://www.home-assistant.io/integrations/toon/

### Version

2022.2.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
