### ISSUE TITLE
Please DO NOT REMOVE Raspberry Pi GPIO

### ISSUE THREAD

**Issue by terren272** [home-assistant/home-assistant.github.io#21553]
### Feedback

Please DO NOT REMOVE Raspberry Pi GPIO
I'll be using this for a long as I can.
Please don't remove it.
 
If you do, how will I be able to use the pi IO ???

### URL

https://www.home-assistant.io/integrations/rpi_gpio/

### Version

2022.2.3

**Comment by frenck** [comment]
It is going to be removed in the near future and is now deprecated.

For reasoning and/or alternative suggestions, please see breaking change section of the release notes.

Closing this issue, as this is not a documentation suggestion.

../Frenck
