### ISSUE TITLE
Can not be installed

### ISSUE THREAD

**Issue by ChristianLoacker** [home-assistant/home-assistant.github.io#21563]
### Feedback

Hi there - I am highly interested in getting this integration running! Unfortunately I have not been able to install the integration. I have an account on https://pool.aseko.com

Using that credentials during installation brings "Unexpected Error"

I have changed my password - made it free from special characters and symbols - didnt help.

Any suggestion?

Best regards, Christian 

### URL

https://www.home-assistant.io/integrations/aseko_pool_live/

### Version

2022.2.4

**Comment by frenck** [comment]
Hi there @ChristianLoacker 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
