### ISSUE TITLE
Add lock unlock switch

### ISSUE THREAD

**Issue by Wilkovf** [home-assistant/home-assistant.github.io#21568]
### Feedback

We have our Wallbox always locked. Geofencing is missing in the wallbox app and woud be a nice automation with HA

### URL

https://www.home-assistant.io/integrations/wallbox/

### Version

2022.2.5

**Comment by hesselonline** [comment]
Hi @Wilkovf, this has been on my to do list for a while now, I will see what I can do...

**Comment by Wilkovf** [comment]
It is working. Now have a button by the frontdoor for unlocking the wallbox 👍 

Thanx
