### ISSUE TITLE
Supported Devices

### ISSUE THREAD

**Issue by collinwebb** [home-assistant/home-assistant.github.io#21574]
### Feedback

Is there a list of supported devices for this feature? I have some iHome and iDevice plugs that will track power usage, but there are not specific integrations for those devices, and they don't give their energy use information out with HomeKit. I would love a list of supported devices that can track energy, so I can start tracking energy usage next time I want to buy a smart switch.

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2022.2.5

**Comment by mdegat01** [comment]
Are you asking for a list of all devices that can provide HA with energy usage? That's not really possible... The list would be huge and changes literally every day as new devices come out.

I would recommend searching the forum, reddit and/or discord for a device you're interested in before buying it or asking about it if you don't see anything. Or stick with devices that use an open standard and don't require a vendor-specific integration to integrate. Like devices which use Zigbee or Zwave for communication for example.
