### ISSUE TITLE
Unfortunately, this page contains links to the old Virtualized 7.2 OS

### ISSUE THREAD

**Issue by ericleigh007** [home-assistant/home-assistant.github.io#21579]
### Feedback

Unfortunately, [this page](https://www.home-assistant.io/installation/windows) contains links to the old Virtualized 7.2 OS, which is not the latest (as of this writing, 7.4 is).  Shouldn't the page just point to the /latest/ OS's?

### URL

https://www.home-assistant.io/installation/windows/

### Version

2022.2.5

**Comment by dannytsang** [comment]
@ericleigh007 It looks like they are pointing to 7.4 for me now. Could you check again and see please?

**Comment by frenck** [comment]
Closing this issue, as there as been no response.
