### ISSUE TITLE
owserver?

### ISSUE THREAD

**Issue by A-Kamf** [home-assistant/home-assistant.github.io#21584]
### Feedback

I'm running hass on a Raspberry pi 4, using the hass image. My 1wire USB stick is attached to the pi (with devices attached). 
It is somewhat unclear what steps I need to take to get the 1wire integration running with my 1wire USB. 
Do I need to set up owfs/owserver on my hass? How do I do that? Is there any other integration or addon required?

### URL

https://www.home-assistant.io/integrations/onewire/

### Version

2022.2.5

**Comment by epenet** [comment]
I have OWFS/OWServer installed on a different machine, so I do not have any experience installing it on hass.

There are lots of tutorials on the internet for installing OWFS/OWServer on a Linux box, maybe you can use those to work out how to apply it to HASS?

One thing for sure: once you get it working you should create a PR to adjust the documentation.

**Comment by frenck** [comment]
While Home Assistant can hook up with an OWFS/OWServer, it is up to those projects to provide installation guides for their projects. This is not a Home Assistant documentation responsibility.

We don't want to become documentation for third-party projects. For example, we don't provide instructions on how to install your Philips Hue hub either.

We can always add a link to installation guides of third-party projects of course 👍

**Comment by A-Kamf** [comment]
Thanks for the suggestions.
My point was that it is not clear from reading the instruction what steps the user needs to take in order to get the 1wire USB stick work in HASS. 

From your answers, I now understand that the integration does not communicate directly with the hw, it is dependent on an OWFS/OWServer running somewhere to get communicate with the 1wire devices. I did not understand that by reading the documentation. I got the impression that the 1wire integration, in line with many other integrations as e.g. the Z-Wave JS, took care also of the communication with the hw interface (as a USB stick).

(As that is not the case, I fully understans it is out of the scope for the 1wire integration to provide the instruction of how to set up a OWFS/OWServer. But I do think it could be clarified that you need to provide that yourself somehow.)

Many thanks for you replies and keet up your great work!
