### ISSUE TITLE
Version integration explanation

### ISSUE THREAD

**Issue by Wummeke** [home-assistant/home-assistant.github.io#21595]
### Feedback

Since the version integration is now available through GUI setup, the documentation only tells you how to use the GUI setup, but there's not explanation about the different options.

For example: I used to have a sensor to show me the latest available HA Core version. From the options in the GUI setup, it is not clear to me, which option I should pick. And if I also would like a sensor for the OS version, which option do I need then? 
I tried to figure it out from code in the Github link, but for me that wasn't really helpful either. 

### URL

https://www.home-assistant.io/integrations/version/

### Version

2022.2.5

**Comment by ludeeus** [comment]
It only shows versions for Core.

**Comment by Wummeke** [comment]
Ok that's cool. But still all the different possibilities/choices are not exactly clear to me. For example: this was my configuration.yaml entry:

```
sensor:
  - platform: version
    source: supervisor
    image: raspberrypi4-64
```

But in the GUI configuration I don't see the option for supervisor anymore. I assumed that "Home-Assistant Versions" is the correct substitution for that, because all the other options seemed unlikely. I was hoping the documentation could clear that up for me, but it didn't. That's why I opened this feedback ticket.
