### ISSUE TITLE
Simplisafe re-authorization every 30 days

### ISSUE THREAD

**Issue by tangyue1** [home-assistant/home-assistant.github.io#21596]
### Feedback

Simplisafe web app requires re-authorization every 30 days. I generated a new code, put it in after clicking the "CONFIGURE" on integration page. But it did not work. The integration stopped working. If I press arm, it shows 'Code' below. 

If I delete the integration and added a new one, it works. 

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2022.2.5

**Comment by frenck** [comment]
Hi there @tangyue1 👋 

It seems like you are trying to raise an issue for an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
