### ISSUE TITLE
Energy Dashboard FuelCell

### ISSUE THREAD

**Issue by Homer76** [home-assistant/home-assistant.github.io#21598]
### Feedback

Hi,
my wish is define a fuelcell in energy dashboard like solar. Maybe i am the first, but it would be great if you could do this.

Best Regards

Nils

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2022.2.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
