### ISSUE TITLE
Verisure - Cannot login ' invalid authentication'

### ISSUE THREAD

**Issue by JHGBaouns** [home-assistant/home-assistant.github.io#21609]
### Feedback

I cannot login with my account on the integration Verisure.
I get " invalid authentication" when I try. I use the same name/password as in my old Homey.
I get [homeassistant.components.verisure] Could not log in to Verisure, "name='vid', domain=None, path=None" in DEBUG.

As information, I wont get the Verisure smartbox autodetected.

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2022.2.5

**Comment by JHGBaouns** [comment]
As update. After update I now get my smart box detected but still get p
 2022-02-22 23:32:21 DEBUG (MainThread) [homeassistant.components.verisure] Could not log in to Verisure, "name='vid', domain=None, path=None" 
when I tru to log on.

**Comment by frenck** [comment]
Have you read: <https://www.home-assistant.io/integrations/verisure/#2-factor-authentication-prerequisite> ?

Considering your report, is sounds like you have 2FA enabled on your account.

**Comment by themaninspain** [comment]
I live in Spain, there is no 2FA available and I also get the "authentication failed" message.
Although in my case I'm not sure that you support non-USA Verisure users.
One detail is that we have usernames to identify the user instead of email addresses

**Comment by themaninspain** [comment]
Still unable to login, tried creating another new user. Verisure website forces me to create a username. Integration asks for email address which doesn't work and neither does the username.
As before 2FA is not available.

**Comment by JHGBaouns** [comment]
After logging in again and updated my account to NOT use MFA and set it to administrator I got a successful connection.
Then I logged in with my admin account and changed it to Limited User. Now it works.
