### ISSUE TITLE
maximum has to be "upper limit + 1"

### ISSUE THREAD

**Issue by steffenbanhardt** [home-assistant/home-assistant.github.io#21615]
### Feedback

The ***maximum*** variable in the range is not the highest value that will be returned back by random.
`{{ range( 0, 1 ) | random }}` will always return 0.

This should be made clear in the documentation.

### URL

https://www.home-assistant.io/integrations/random/

### Version

2022.2.6

**Comment by frenck** [comment]
Your example show the use of the random function/filter of the Jinja2 template syntax, while this feedback is linked to the random integration.

As those are not related and not the same things, I am confused about your documentation feedback on this page.

Could you clarify?

**Comment by steffenbanhardt** [comment]
You are totally right. My fault! -> Closing
