### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by Puch-tdi** [home-assistant/home-assistant.github.io#21618]
### Feedback

I was waiting and updating quite a while and never got the energy dashboard. Finally i took another Raspberry for a clean install and right away the dash appear. After testing some time with the config i found the problem, the dash only works in a "default_config". This was the problem in my system, since i use a lot of icons in front of my sensors i started about two years ago on a customize.yaml.
How can we install this if you are not running a default config?

Hope to hear from you.

Kind regards,

Sander

### URL

https://www.home-assistant.io/docs/energy/

### Version

2022.2.6

**Comment by frenck** [comment]
It's documented here:

https://www.home-assistant.io/docs/energy/faq/#the-energy-panel-is-not-visible

**Comment by Puch-tdi** [comment]
Frenck, thanks for the answer. It say add it manually and i did this yesterday but then there will be a totally different dashboard become visible. What i was looking for is an explaination how to add it manually, cant find anything about that. 
But then again, for me it worked on having both "default config" and the "customize.yaml" and so far it runs fine.

Thanks for the quick responce

**Comment by frenck** [comment]
Customize.yaml should not be needed, if you end up needing such a solution you should report it instead of work around things
