### ISSUE TITLE
Please make clear why devices are not shown on map when at home

### ISSUE THREAD

**Issue by Soepgroenten** [home-assistant/home-assistant.github.io#21621]
### Feedback

Actually not an issue, but a request for explanation and a suggestion for improvement on the official documentation page.

Please make clear why devices are not shown on map when at home.

Currently we know that there was made some decision to not show device tracker on the map when the owner of the device is at home, but it could be helpful to understand why it is what it is.

### URL

https://www.home-assistant.io/integrations/map/

### Version

2022.2.6

**Comment by frenck** [comment]
I am not sure what to tell or adjust? What is you adjustment suggestion?

There is no particular reason on "why" their are not shown when home, it just is like that since it was spawned back in the day.

As there is no real reason, I don't see what should be added?

**Comment by Soepgroenten** [comment]
I'm Sorry for my late reply, didn't mention your comment.

On Page: https://www.home-assistant.io/integrations/map/
there's a statement that says: "Devices that are currently at home won't show on the map."
![image](https://user-images.githubusercontent.com/85663848/154250916-531f3ea7-5853-45fe-8fc6-2402b63103e9.png)

But there's no explanation to be found why there was chosen to not show devices to be at home. Is it from a security perspective? Or perhaps a technical limitation?

In my journey looking for an answer to this, I've discovered that I'm not the only one. There are actually a lot of people looking for an answer to this so I did my suggestion to improve the official documentation.  It helps people understand why things are as they are.

Links to topics of people looking for answers:
https://community.home-assistant.io/t/mobile-app-device-tracker-not-shown-on-map/154784
https://community.home-assistant.io/t/wth-we-see-only-device-trackers-on-the-map-and-not-persons/227772/5
https://community.home-assistant.io/t/nobody-showing-on-map/316152/3

**Comment by frenck** [comment]
> But there's no explanation to be found why there was chosen to not show devices to be at home. Is it from a security perspective? Or perhaps a technical limitation?

You are looking for a Why that isn't there.

It has been that way historical.

**Comment by Soepgroenten** [comment]
Ok Thanks, I understand...thanks for your time and answer, I'll close this one ;-)
