### ISSUE TITLE
Feels incomplete

### ISSUE THREAD

**Issue by ouwebaas** [home-assistant/home-assistant.github.io#21622]
### Feedback

Feels like i'm getting send from one page to the other, sometimes it's nice to receive some examples of how to use. 
An example of just (API :) in an configuration.yaml file isn't really an example don't you think?

### URL

https://www.home-assistant.io/integrations/api/

### Version

2022.2.6

**Comment by frenck** [comment]
There is only an example of "api:", as it doesn't have any more configuration capabilities 🤷 

There are no more examples to show as far as configuration goes.

If you are looking for developing against Home Assistant (eg using the API), please check our developers documentation instead.
