### ISSUE TITLE
No directions how to get to the configuration panel?

### ISSUE THREAD

**Issue by jodasm** [home-assistant/home-assistant.github.io#21623]
### Feedback

This documentation does not give any instructions as to how to configure energy.
i.e. where in the configuration should the menu item appear etc.

### URL

https://www.home-assistant.io/docs/energy/

### Version

2022.2.6

**Comment by frenck** [comment]
There are 2 big my Home Assistant buttons on top of that page, bringing you there...

**Comment by jodasm** [comment]
Thanks found it.
Also found that I can configure the energy dashboard by actually configuring the dashboard.

seems straight forward now but for some reason I just assumed that was UI and not actually setup.
