### ISSUE TITLE
Re: Installing pre-requisites on Ubuntu 20.04  - Error and Fix

### ISSUE THREAD

**Issue by lockiegarnett** [home-assistant/home-assistant.github.io#21636]
### Feedback

Re: Installing pre-requisites on Ubuntu 20.04  - Error and Fix

sudo apt-get install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0 tzdata

libturbojpeg0  --> Error:  Unable to locate package
...
libjpeg-turbo8  (this worked instead) or
libjpeg-turbo8-dev (this worked instead)

### URL

https://www.home-assistant.io/installation/linux/

### Version

2022.2.6

**Comment by frenck** [comment]
Yup, things can differ a bit, depending on the Linux distribution used.

Hence this big warning is listed:

![image](https://user-images.githubusercontent.com/195327/153863979-19f55e3c-e0f8-4971-b213-32502241cd45.png)
