### ISSUE TITLE
Bug with AVM FRITZ!Box Tools in combination with NODE-RED

### ISSUE THREAD

**Issue by wickedgalen** [home-assistant/home-assistant.github.io#21634]
### Feedback

Dear AVM FRITZ!Box Tools Creator, / To whom it may concern (as searching brought me here for debug Feedback)

Home Assistant Integration : **AVM FRITZ!Box Tools**
in combination with NODE-RED Integration.

Using the fritzbox value from download_throughput:
There is a typo.

sensor.ROUTERXXX_download_throughput

this value is sent in "**msg.playload**" instead of "**msg.payload**"

![image](https://user-images.githubusercontent.com/81089200/153773033-6e2987fd-9a65-4808-81c5-5ac205bbb896.png)

![image](https://user-images.githubusercontent.com/81089200/153772819-ae0db38d-cf98-437d-9b0a-8ceff9f78e13.png)

Please let me know if I address the proper person/group as I cannot find a more precise contact via Home Assistant.

Thank you for fixing =)

### URL

https://www.home-assistant.io/integrations/fritzbox/

### Version

2022.2.6

### Additional information

If you need more let me know.

**Comment by frenck** [comment]
This is not an Home Assistant issue. As Node-RED is third-party, the Home Assistant project does not support it either.

Please report your issue with the Project creating that node for Node-RED.

Thanks!
