### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by sab0tajue** [home-assistant/home-assistant.github.io#21644]
### Feedback

 
все прописал по инструкции отсюда:
появляется ошибка при попытке включить:

Не удалось вызвать службу vacuum/turn_on. <iq type="error" to="fcef6fld784519bf@ecouser.net/723c1bd68d3ff50fa803230e3523c3cd" from="158cd97b-2f2b-45ab-9a06-de6b1d5359e8@y79a7u.ecorobot.net/atom" id="0d8e85d2-bbf9-45dc-b478-9c23e77ecf13-14"><error type="wait" code="404"><recipient-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></iq>

появляется ошибка при попытке выключить:
Не удалось вызвать службу vacuum/turn_off. <iq type="error" to="fcef6fld784519bf@ecouser.net/723c1bd68d3ff50fa803230e3523c3cd" from="158cd97b-2f2b-45ab-9a06-de6b1d5359e8@y79a7u.ecorobot.net/atom" id="0d8e85d2-bbf9-45dc-b478-9c23e77ecf13-15"><error type="wait" code="404"><recipient-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></iq>

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2022.2.6

**Comment by frenck** [comment]
We cannot process documentation suggestions in other languages. Please use the English language when providing a documentation suggestion.

Thanks! 👍
