### ISSUE TITLE
When making documentation act like who you're writing it for has no clue what's going on.

### ISSUE THREAD

**Issue by seraphx2** [home-assistant/home-assistant.github.io#21647]
### Feedback

It literally does not tell where to put the camera configuration. Just a snippet of properties with no instruction on what file to open. I am a total noob. A block of properties means nothing to me.

### URL

https://www.home-assistant.io/integrations/octoprint/

### Version

2022.2.6

**Comment by frenck** [comment]
@seraphx2 Thanks for the feedback, and you are right.

We are moving towards configuration to the UI for a lot of thing, but we are still in transition and not everything works like that yet.

That said, we have extensive documentation on configuring Home Assistant via its configuration files:

<https://www.home-assistant.io/docs/configuration/>
