### ISSUE TITLE
Add additional instructions for restoring from backup on new install

### ISSUE THREAD

**Issue by overkill32** [home-assistant/home-assistant.github.io#21642]
### Feedback

The process of restoring from backup on new install could be improved to manage user expectations.  The webpage says that HA will restart when completed, but I didn't experience that just now.  I was using a new install of 7.6 and applying a backup from 7.4 and core-2022.2.5.

I started a ping throughout the entire process and it never dropped.  The webpage did not reload at any point after I clicked the final "restore" button.  It sat on /onboarding.html.    The documentation does a good job in setting expectations that it's going to take a while.   However, I waited and waited only to eventually find that my lights were working again, and when I accessed the primary URL again, it was fully restored and functioned as expected.

### URL

https://www.home-assistant.io/common-tasks/os/#restoring-a-backup-on-a-new-install

### Version

unable to locate version

**Comment by frenck** [comment]
This sounds like this is not a documentation suggestion? However, that is what you have submitted.

**Comment by overkill32** [comment]
I guess I was thinking the documentation could be improved to better set user expectations.  If the instructions had said to manually refresh the primary URL, my user experience would have been improved.   As currently stated, I'm just staring at the screen waiting for something to happen, which it does not.

**Comment by frenck** [comment]
I think that it should not rely on manual refreshing and that should be something that should be solved.

**Comment by overkill32** [comment]
I want to be helpful.  Would you prefer that I document my experience in another location?   Would it be Core?
