### ISSUE TITLE
Integrations >> Person missing info about deleting user

### ISSUE THREAD

**Issue by Omcsesz** [home-assistant/home-assistant.github.io#21655]
### Feedback

Hello, team!

I`m not able to find info on page https://www.home-assistant.io/integrations/person/ on how to remove a user. Can you please update this page?

### URL

https://www.home-assistant.io/integrations/person/

**Comment by cliffordwhansen** [comment]
@Omcsesz I see that this page needs a lot of updating.

If you have configured the user via the HomeAssistant interface then you can delete the user by going to:
Configuration > People & Zones > _person_
In the modal that pops up there is a delete button in the bottom left corner

**Comment by Omcsesz** [comment]
@cliffordwhansen Thanks! So you say that this page will be updated in the near future, right?

**Comment by cliffordwhansen** [comment]
@Omcsesz I have added a link to the configuration page which should help a bit

**Comment by Omcsesz** [comment]
Thanks!

**Comment by Omcsesz** [comment]
@cliffordwhansen Do you know when will this edit go online?

**Comment by cliffordwhansen** [comment]
@Omcsesz I don't sorry, looks like it's still waiting for review, so someone will get to it soon.
