### ISSUE TITLE
Unclear how to deal with trial plan, I think

### ISSUE THREAD

**Issue by pensivealbatross** [home-assistant/home-assistant.github.io#21657]
### Feedback

Hello there,  I'm really confused as I've followed this setup and in quite a vanilla way I think, and yet my API key is now getting 

> Authorisation failed for app_key *************************************** and app_id ******* with error 'usage limits are exceeded'. See http://transportapi.com for plans and sign-up.

The doc here says that the integration will calculate all this for me and I won't run out.

Have others got this problem or is it just me?   I see that the plans section on transportapi says my plan is trial (expired), I'm trying not to read too much in to that as it's not mentioned here.

I honestly don't know if this is a problem with the integration, the API, or the doc.

### URL

https://www.home-assistant.io/integrations/uk_transport/

### Version

2022.2.5

**Comment by NineEighty** [comment]
Hi @pensivealbatross,
TransportAPI changed their API in September 2021 (or announced the changes back then atleast)
I've passed on feedback under issue https://github.com/home-assistant/home-assistant.io/issues/21723

You have to completely recreate the application on the transport api side to get it working again, but this will again be limited to 30 days and will need recreating over and over. I'm unsure of any alternative integrations we can use at this stage.
