### ISSUE TITLE
Clarify entity id vs. unique_id

### ISSUE THREAD

**Issue by psteinweber** [home-assistant/home-assistant.github.io#21653]
### Feedback

I would expect more explanation about the entity id that is being generated automatically from the `name` if I understand it correctly, as long as no `unique_id` is set. 

How do those two correlate?

Is it recommended to include a domain in the `unique_id`, for example `light.my_new_id`?

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2022.2.6

**Comment by frenck** [comment]
Entity IDs is always based on the name and not related to unique ID.
A unique ID is an stable identifier that uniquely identifies this entity, now and in the future, regardless if their name, entity ID or anything else changes.

As per documentation:

> An ID that uniquely identifies this light group.

**Comment by psteinweber** [comment]
Got it. By the way, my prespective is obviously that of a beginner.
 
So in those docs I would love to learn what the entity ID of my light group will be, ideally with example. "Kitchen Lights" becomes "light.kitchen_lights". As I need to reference that in other places.

**Comment by frenck** [comment]
That depends, the entity ID is not guaranteed, you can look them up in Home Assistant once created.

Additionally, when a unique ID is set, you can customize the entity ID to your liking in the Home Assistant frontend.
