### ISSUE TITLE
Frontend config: Unclear how filter building works.

### ISSUE THREAD

**Issue by scpotter** [home-assistant/home-assistant.github.io#21663]
### Feedback

Not intuitive how Inclusion Mode selections work and if it applies to domains, entities, or both. Especially confusing how it relates to "Domains to Include"

<img width="585" alt="Screen Shot 2022-02-15 at 6 37 50 PM" src="https://user-images.githubusercontent.com/5929993/154168252-7d2e7283-a462-4ca3-a310-4d5230043c93.png">

Some possible interpretations of "Domains to Include" when Inclusion Mode: Exclusion is selected:
1: Selected domains to include will be "included in the exclusion mode" (ie domains will be excluded). Entities exceptions will be handled later in the flow.
2: Any selected domains to include will be included, and unselected domains will be excluded. Entities exceptions will be handled later in the flow.
3: All domains are excluded by default, there is no need to exclude them, the mode applies to entity exceptions made later in the flow.

Additional Observations
1: Accessory HomeKit Mode requires a domain selection from "Domains to Include", and exclusion mode is ignored. This doesn't seem to match the documentation flow.

Suggestions:
1: Describe the Exclusion Mode operation/flow in documentation, similar to Accessory Mode
2: Relabel "Exclusion Mode" to "Entity Filter Mode" or similar to make it more clear it applies to entities only and the YAML documentation section it relates to
3: Move exclusion mode below the domain selection or to the next step in the flow since it does not apply to all choices.

Exclusion mode flow:
<img width="585" alt="Screen Shot 2022-02-15 at 6 55 56 PM" src="https://user-images.githubusercontent.com/5929993/154178556-f2f59d6d-f1c7-47d6-8b53-a7f3384c8624.png">

Interpretation of guidance:
Exclusion: includes all entities in the domain (existing entities or the domain?) and allows entities to be selected for exclusion
Inclusion: excludes all entities in the domain (existing entities or the domain?) and allows entities to be selected for inclusion

Observations:
1: Mode is named based on secondary/exception behavior, not the primary default action. The title of the flow does match the mode.
2: Unclear if primary action is a domain filter or list of current entities in the domain.
3: Unclear if there are interaction between Inclusion mode and System Options "Enable newly added entities"

Suggestions:
1: Consider naming interaction mode based on primary action 
2: Consider describing functionality in terms of which filter pattern(s) the UI creates. For example "the UI uses selections to build a filter following the '2: includes no excludes' pattern by entity."
3: Document Inclusion mode / new entity interactions.

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2022.2.6

**Comment by bdraco** [comment]
If you feel like taking a shot at improving it, here is the link to edit the strings

https://github.com/home-assistant/core/edit/dev/homeassistant/components/homekit/strings.json
