### ISSUE TITLE
Google Maps redirect

### ISSUE THREAD

**Issue by tkozel70** [home-assistant/home-assistant.github.io#21669]
### Feedback

It appears that all requests to maps.google.com are redirected to www.google.com/maps and resultantly it appears that the cookie file does not work as intended. I tested this via Chrome and Firefox and the behavior appears to be the same on both. In my case, the result was that location tracking does not appear to work.

### URL

https://www.home-assistant.io/integrations/google_maps/

### Version

2022.2.6

Further info: Here are the contents of the HA log file related to this:

2022-02-16 09:22:08 ERROR (SyncWorker_0) [homeassistant.components.google_maps.device_tracker] The cookie file provided does not provide a valid session. Please create another one and try again
2022-02-16 09:22:08 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy google_maps

The cookie file it is referring to was taken from Chrome but the Firefox file generated the same errors. In reviewing the internals of the cookie files, the logs are correct since maps.google.com is not referenced in the cookie file and www.google.com/maps is not explicitly referenced either.

Does anyone have any workarounds for this issue?

**Comment by tkozel70** [comment]
I guess this is a form of presence detection that is being deprecated? Since it appears that it no longer functions since Google changed the way their website works?

**Comment by HBir** [comment]
This is still relevant. 👍  Redirect does not allow you to get a proper cookie. 
Is there any "quick" fix for this, or it is deprecated, like above writer mentioned?

**Comment by HBir** [comment]
The fault was on my end. After properly getting `.google.com` cookies after a fresh login session everything worked as intended. This was on Home Assistant Core 2022.5.1.
The redirect does not matter for this integration and this ticket should be closed.

Steps to reproduce:
1. Open firefox
2. Clear all cookies
3. Go to www.google.com/maps
4. Log in to your tracker account
5. Use the [Export Cookies](https://addons.mozilla.org/sv-SE/firefox/addon/export-cookies-txt/) firefox addon to extract `google.com` cookies with `Prefix HttpOnly cookies` unchecked.
6. Add the file in the same directory as your configuration.yaml according to the naming convention in the docs (Make sure home assistant has permission to the file)
7. Add the configuration.yaml entry as described in the documentation.
8. Restart Home Assistant
