### ISSUE TITLE
Add Integration prompts for fields but does not explain what their values should be

### ISSUE THREAD

**Issue by sblessley** [home-assistant/home-assistant.github.io#21674]
### Feedback

When using the "add integration" button at https://www.home-assistant.io/integrations/nut or the "add integration" from Config/Integrations, the integration prompts for a username and password. There is no indication whether this are the HA login credentials, something info I should know (e.g. a default login) or if its  establishing some authentication for the NUT service. 

### URL

https://www.home-assistant.io/integrations/nut/

### Version

2022.2.7

**Comment by ollo69** [comment]
Because you are configuring NUT integration, this are credentials to connect to NUT service. The right user name and password depend on how you configure NUT service.

**Comment by dannytsang** [comment]
For me, it's using the upsmon.conf user credentials. See **Create a MONITOR directive for upsmon** section in the [NUT user manual](https://networkupstools.org/docs/user-manual.pdf).

**Comment by jwilleke** [comment]
Well of course you know that. But the issue is the end-user doing the setup my know nothing about "NUT" and the prompts do not indicate which credentials.

**Comment by frenck** [comment]
So you add an integration that connects with NUT... it asks for a username & password, what else than the NUT username or password could that be? I'm not sure how that can be conflicting or unclear at any point?

**Comment by jwilleke** [comment]
"_Well of course you know that. But the issue is the end-user doing the setup my know nothing about "NUT" and the prompts do not indicate which credentials._"

There are a ton of usernames and credentials within home assistant all that is being asked is some clarification that these are the NUT Server Credentials.

**Comment by frenck** [comment]
@jwilleke Ok... Sorry, I don't agree with your comment.

You are adding NUT to Home Assistant, I think it makes perfect sense what it is asking. Don't get me wrong, but it surely isn't your Domino's Pizza account login...

I don't feel the need to adjust it. But if anyone wants to take a stab at changing it, feel free to do so.

**Comment by sblessley** [comment]
﻿
Exactly, thank you. It may be obvious for a more HA savvy user; I’m not stupid, I have a graduate degree in computer science. But, for example when I set up zigbee2mqtt, It was clear I was *creating* authentication credentials for a server being established on port 1888, and subsequently I’d need to use these when directing other software to it. 

I’ve set this one aside for a while, the last straw was when I tried to use my Dominoes credentials unsuccessfully.

**Comment by dannytsang** [comment]
> There are a ton of usernames and credentials within home assistant all that is being asked is some clarification that these are the NUT Server Credentials.

@jwilleke I am trying to understand what can be improved so please bear with me. When you add the NUT integration, the dialogue that appears shows the below
![image](https://user-images.githubusercontent.com/567982/159579492-8d05d1ce-6847-4d62-8187-d0623ceae800.png)
The title says it's connecting to the NUT server and then asking for connection details and nothing about Home Assistant credentials. The only thing I can think of is if there some sort of confusion between NUT integration and the NUT add-on or am I missing something?

@sblessley I don't have zigbee2mqtt so is there a screenshot or a link to what it looks like during setup that makes it very clear and hopefully it can be fed back into the documentation?
