### ISSUE TITLE
Lithuanian language is not supported but Google translate it supports

### ISSUE THREAD

**Issue by vilcinskasMidaugas** [home-assistant/home-assistant.github.io#21682]
### Feedback

it says:
Check the [complete list of supported languages](https://translate.google.com/intl/en_ALL/about/languages/) (languages where “Talk” feature is enabled in Google Translate) for allowed values. Use the 2 digit language code which you can find at the end of URL when you click on Language name.

I have chaked  in provided link above Lithuanian  language has "Talk" feature in Google Translate, but  i get an erro after i tried to set it in my HA:
Invalid config for [tts.google_translate]: value must be one of ['af', 'ar', 'bg', 'bn', 'bs', 'ca', 'cs', 'cy', 'da', 'de', 'el', 'en', 'en-au', 'en-ca', 'en-gb', 'en-gh', 'en-ie', 'en-in', 'en-ng', 'en-nz', 'en-ph', 'en-tz', 'en-uk', 'en-us', 'en-za', 'eo', 'es', 'es-es', 'es-us', 'et', 'fi', 'fr', 'fr-ca', 'fr-fr', 'gu', 'hi', 'hr', 'hu', 'hy', 'id', 'is', 'it', 'ja', 'jw', 'km', 'kn', 'ko', 'la', 'lv', 'mk', 'ml', 'mr', 'my', 'ne', 'nl', 'no', 'pl', 'pt', 'pt-br', 'pt-pt', 'ro', 'ru', 'si', 'sk', 'sq', 'sr', 'su', 'sv', 'sw', 'ta', 'te', 'th', 'tl', 'tr', 'uk', 'ur', 'vi', 'zh-CN', 'zh-cn', 'zh-tw'] for dictionary value @ data['language']. Got 'lt'. (See ?, line ?).

I think  Lithuanian languge could be added as it is supported by Google translate
Thanks.

### URL

https://www.home-assistant.io/integrations/google_translate/

### Version

2022.2.8

### Additional information

All info is above

**Comment by andiukas** [comment]
Same problem :(

**Comment by meni123** [comment]
The same problem is also in the Hebrew language, it is supported by Google translate but it can not be added its marking is `iw`

**Comment by andiukas** [comment]
problem not resolved

**Comment by frenck** [comment]
Hi there @vilcinskasMidaugas and @andiukas,

It seems like you have a feature request to extend the supported language for the Google Translate integration, however, this is submitted as documentation feedback.

There is no amount of documentation we can adjust to add new language support to Home Assistant.

Please file feature requests for Home Assistant in the Feature Request section in our Community Forum here:

<https://community.home-assistant.io/c/feature-requests/13>

Thanks! 👍 

../Frenck
