### ISSUE TITLE
Documentation does not state how to enable color and brightness control

### ISSUE THREAD

**Issue by meyca** [home-assistant/home-assistant.github.io#21697]
### Feedback

> Lights
> This integration adds the Key Light device as a light in Home Assistant, and allows you to control the color temperature, brightness, and its on/off state.
> 
> When using the Elgato Light Strip, color support is automatically detected and enabled in Home Assistant.

This part misses the description about how to enable color temperature control and brightness for the other Elgato devices.

### URL

https://www.home-assistant.io/integrations/elgato/

### Version

2022.2.9

### Additional information

What I have done: 

1. My Elgato Key Light Air was automatically detected, Wow! :-)
2. I added the device to my homeassistant config

Now I am able to switch the light on / off. Ok. 

But I do not know, how to enable color temperature control and brightness.

**Comment by frenck** [comment]
Hi @meyca 👋 

I'm a little confused about your documentation suggestion, as there is nothing to enable regarding this?

<img width="1091" alt="CleanShot 2022-02-19 at 12 50 07@2x" src="https://user-images.githubusercontent.com/195327/154799554-a65367a3-9ca2-4360-81bf-9e480187b5ea.png">

../Frenck

**Comment by meyca** [comment]
Sorry, I was confused to, while adding my first device on Homeassistant with a color temperature feature. I had no idea that the additonal control only shows up, when the device is switched on. Additionally I mixed up color temperature and color support...
