### ISSUE TITLE
wrong metrics in fronius energy values

### ISSUE THREAD

**Issue by mastermarkush** [home-assistant/home-assistant.github.io#21706]
### Feedback

Hello, I have discovered that the values provided through the fronius integration have the wrong metrics attached. The "Energy real consumed" is today displayed in kWh, it is however reported in Wh through the integration. The same goes for the "Energy real produced". 

Therefore - as a workaround - I need to take the values which are currently reported in homeassistant (9 Million Watt Hours) and divide them through 1000, so that I receive the correct value (9kWh) in kWh.

The solution to this problem would be to convert the values retrieved from the Fronius API, whilst dividing them through 1000, so that they reflect real kWh.

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2022.2.9

### Additional information

![Screenshot at 2022-02-20 10-49-07](https://user-images.githubusercontent.com/55920311/154837137-6d8bb56f-6a0c-405f-a190-72928a897450.png)

**Comment by farmio** [comment]
Hi 👋!
Do you have anything customized? Your state_class is also not correct. See 
https://github.com/home-assistant/core/blob/833cba71d717509e53e9bfee176e4dd3cd21a00f/homeassistant/components/fronius/sensor.py#L311-L317

PS: this is the documentation repository, bug reports for integrations should go in [homeassistant/core ](https://github.com/home-assistant/core)

**Comment by mastermarkush** [comment]
Found 2 "messes" from my side: customization set, so that Wh were converted to kWh -> solved
Second thing is that I am still using the configuration.yaml integration. Question: would this explain why my state_class is "measurement" instead of total_increasing?

**Comment by farmio** [comment]
No it wouldn't. configuration.yaml fronius setup is just ignored as soon as it was imported. 
Maybe you configured it before and it was saved for some reason. Don't know.

**Comment by mastermarkush** [comment]
in fact, I was still running on a 2021.8.8 version which did not allow Fronius integration via GUI yet. Updating now. Thanks for your support!
