### ISSUE TITLE
Allow self signed certificates by config option

### ISSUE THREAD

**Issue by FreeBSD75** [home-assistant/home-assistant.github.io#21708]
### Feedback

Hi,

please add an option to allow self signed certifcates by an configuration option.
Probably this would be verify_ssl=None from aiohttp. 
Using a none ssl connection is really not state of the art.
Even if I have a own CA where I created the certificate for the VuDuo, python doesen't accept it.
(Hassio 2021 inside a FreeBSD jail)

Thanks

### URL

https://www.home-assistant.io/integrations/enigma2/

### Version

2022.2.9

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
