### ISSUE TITLE
Home assistant supervised only on debian

### ISSUE THREAD

**Issue by EduardoOliveira** [home-assistant/home-assistant.github.io#21715]
### Feedback

Hello, 
I could be clearer from the installers page that the supervised edition only works on Debian.

Thank you,
The guy that just installed ubuntu server and is now reinstalling the OS xD

### URL

https://www.home-assistant.io/installation/linux/

### Version

2022.2.9

**Comment by frenck** [comment]
You literally skipped step one?

<img width="554" alt="CleanShot 2022-02-21 at 03 30 56@2x" src="https://user-images.githubusercontent.com/195327/154879505-300b1163-81d2-4aad-9e40-adb50e678886.png">


The requirements are extensively described and documented. It's not just Debian that is required.
