### ISSUE TITLE
Docs for MQTT Number and MQTT Select's new command_template option need to include the available variables

### ISSUE THREAD

**Issue by melyux** [home-assistant/home-assistant.github.io#21718]
### Feedback

Thanks to @jbouwh for implementing `command_topic` for MQTT Select and MQTT Number back in last November. Today I tried them out, and ran into something: the documentation for these two don't include the actual variables that are available to this template. Usually, like with [MQTT Alarm Control Panel](https://www.home-assistant.io/integrations/alarm_control_panel.mqtt/), the docs include this:

> The template used for the command payload. Available variables: `action` and `code`.

For MQTT Number and MQTT Select, I dug through the PR to find that the variable available to the template is called `value`. This should be noted in the documentation.

### URL

https://www.home-assistant.io/integrations/select.mqtt/

### Version

2022.2.0

### Additional information

The other doc page is https://www.home-assistant.io/integrations/number.mqtt/

**Comment by jbouwh** [comment]
The common variables are documented here:
https://www.home-assistant.io/docs/configuration/templating/#using-value-templates-with-mqtt
