### ISSUE TITLE
Documentation for "AVM FRITZ!Box Tools" misses important prerequisite

### ISSUE THREAD

**Issue by Abdull** [home-assistant/home-assistant.github.io#21729]
### Feedback

The [AVM FRITZ!Box Tools integration](https://www.home-assistant.io/integrations/fritz/) (`integration: fritz`) requires a login. Despite providing the correct credentials, I received errors with setting up the integration.

By coincidence, I found out how to make it work: The Fritz!Box needs to be configured to allow external applications.

To allow external applications, log in via the Fritz!Box web interface (by default http://fritz.box), then select (in the German web interface localization): *Heimnetz* -> *Netzwerk* -> select tab *Netzwerkeinstellungen* -> (expand, if not yet expanded, "*weitere Einstellungen*") -> under *Heimnetzfreigabe*, activate *Zugriff für Anwendungen zulassen*.

After a Fritz!Box reboot, the Home Assistant Fritz!Box Tools integration setup should work with e.g. the default auto-generated admin account credentials (username `fritzWXYZ`, where `WXYZ` is a  random four-digit number, see *System -> Fritz!Box-Benutzer -> Benutzer*).

### URL

https://www.home-assistant.io/integrations/fritz/

**Comment by mib1185** [comment]
Hi @Abdull 
This is already mentioned in the docs:

> TR-064 needs to be enabled in the FRITZ!Box network settings for Home Assistant to login and read device info.

TR-064 is the used protocol for application access ( _is also noted in the FritzBox UI_ )

**Comment by Abdull** [comment]
> Hi @Abdull This is already mentioned in the docs:
> 
> > TR-064 needs to be enabled in the FRITZ!Box network settings for Home Assistant to login and read device info.
> 
> TR-064 is the used protocol for application access ( _is also noted in the FritzBox UI_ )

No one can deduce this.

**Comment by chemelli74** [comment]
Hi @Abdull, please open a PR and suggest a change for the wording.

Simone
