### ISSUE TITLE
5min/30min duration selector

### ISSUE THREAD

**Issue by kcoffau** [home-assistant/home-assistant.github.io#21720]
### Feedback

Hi, the application is pulling in duration of 30mins, but users are billed in 5 min increments.

Can we include an option of selection 5/30 min intervals?

### URL

https://www.home-assistant.io/integrations/amberelectric/

### Version

2022.2.9

**Comment by frenck** [comment]
This is already possible.

First, disable polling for this integration in the integrations dashboard. Click on the three dotted menu and choose "System options"

![image](https://user-images.githubusercontent.com/195327/154922612-df413afe-76b6-4e7e-b2fa-21eba3cd2ba5.png)

Next disable polling:

![image](https://user-images.githubusercontent.com/195327/154922694-dc1fcda2-dab2-4e0a-b5ef-51c7a5b063a2.png)

Now, you can write an automation, that triggers fixed times, time patterns, evens, or in any form you like and call the `homeassistant.update_entity` on one of the Amber Electric entities.

[![Open your Home Assistant instance and show your service developer tools with a specific service selected.](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistant.io/redirect/developer_call_service/?service=homeassistant.update_entity)

This is the generic way how we handle this in Home Assistant (thus not a workaround).

Please note, that we provide defaults to prevent issues. If you poll faster/more often, you might be in violation of the terms of usage for the API used.

Hope it helps!

../Frenck

**Comment by madpilot** [comment]
Hi @kcoffau,

No one is being billed 5-minute increments yet. Once it is enabled the API will automatically show the 5-minute price.

See: https://help.amber.com.au/hc/en-us/articles/4411273786637-Five-minute-settlement-explained-

**Comment by madpilot** [comment]
@frenck this isn't about polling times - it's about price resolution (the API can return the 5-minute or averaged 30-minute price)

**Comment by frenck** [comment]
aah but in that case it would be a feature request (or bug), however, you have submitted documentation feedback.

Please check https://www.home-assistant.io/help
