### ISSUE TITLE
Whats next?

### ISSUE THREAD

**Issue by Scm1001** [home-assistant/home-assistant.github.io#21733]
### Feedback

Once the file is pushed to home assistant, how can you find it? What is the landing directory?

### URL

https://www.home-assistant.io/integrations/push/

### Version

2022.2.9

**Comment by frenck** [comment]
@Scm1001 Use it?

As in, there isn't much more to it, as the first sentence in the documentation states:

![image](https://user-images.githubusercontent.com/195327/155085736-df1ef72b-a606-428f-8bda-cd517861ca96.png)

It will show up a camera in Home Assistant.

The images file isn't stored on disk, but the image is shown in the camera entity created.

**Comment by Scm1001** [comment]
Do you have an example of how to call or access it in home assistant? Looking to pass it to a DOODS server or call it in Node Red as an example.

**Comment by frenck** [comment]
@Scm1001 I'm sorry, your question is a bit unclear. It shows up as a standard camera entity in Home Assistant. Which can be used as input for the DOODS integration? <https://www.home-assistant.io/integrations/doods#configuration>

Or am I missing something?

**Comment by Scm1001** [comment]
Thank you - that helps!
