### ISSUE TITLE
Question / request: maximum number of octoprint devices allowed

### ISSUE THREAD

**Issue by njilk** [home-assistant/home-assistant.github.io#21737]
### Feedback

It seems that I can add only one octoprint instance, however I have multiple 3D printers using octoprint. Did I miss something or is this a limitation of this Integration? 

### URL

https://www.home-assistant.io/integrations/octoprint/

### Version

2022.2.9

**Comment by rfleming71** [comment]
The integration does validation to prevent duplicate Octoprint instances from being added. Try following the steps here on your second instance: https://github.com/home-assistant/core/issues/59216#issuecomment-963224245

**Comment by njilk** [comment]
Thanks for the info. It’s working now :-)

Groeten, Regards,
Ad
