### ISSUE TITLE
Changing Humidity?

### ISSUE THREAD

**Issue by zipzagster** [home-assistant/home-assistant.github.io#21744]
### Feedback

I don't see a choice to change humidity under the Venstar device. Could I get some help on how to make the change? Thanks

### URL

https://www.home-assistant.io/integrations/venstar/

### Version

2022.2.9

**Comment by frenck** [comment]
The Humidity setting would be part of the climate entity in Home Assistant (and can be set using to the UI, or by using the [`climate.set_humidity`](https://www.home-assistant.io/integrations/climate#service-climateset_humidity) service.

Please note, this feature is only available on the ColorTouch T7900, do you meet that requirement?

**Comment by zipzagster** [comment]
Yes, I have the 7900 and the humidity sensor in history. Thanks for the response.

**Comment by frenck** [comment]
So this is solved then?
