### ISSUE TITLE
it is possible to get LongTermStatistik with a Sensor without state_class

### ISSUE THREAD

**Issue by SirRob008** [home-assistant/home-assistant.github.io#21746]
### Feedback

with a Template Sersor is it possible to get longtermstatistic from a sensor without state_class.
My Example:
template:
  - sensor:
      - name: "Luftdruck"
        unique_id: average_pressure
        unit_of_measurement: Pa
        state_class: measurement
        device_class: pressure
        icon: mdi:gauge
        state: >
          {% set temp_press = states('sensor.absolute_pressure') %}
          {{ temp_press }}

the sensor absolut_pressure have no state_class.
with this code you get a new sensor with state_class and you can take longtermstatistic.

regards Peter

### URL

https://www.home-assistant.io/more-info/statistics/

### Version

2022.2.9

### Additional information

I hope this helps somebody ?

**Comment by frenck** [comment]
> the sensor absolut_pressure have no state_class.

So, if an integration or entity is missing support for long-term statistics, we should not document a workaround using templates, we should fix it.

Please report it as an issue in our issue tracker so support can be added for that integration/entity.

The Home Assistant Core issue tracker can be found here: 

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by SirRob008** [comment]
Ok thanksGesendet mit der GMX Mail AppAm 22.02.22 um 18:47 schrieb Franck Nijhof
                
            
            
                
                    Von: "Franck Nijhof" ***@***.***>Datum: 22. Februar 2022An: "home-assistant/home-assistant.io" ***@***.***>Cc: "SirRob008" ***@***.***>,"Author" ***@***.***>Betreff: Re: [home-assistant/home-assistant.io] it is possible to get LongTermStatistik with a Sensor without state_class (Issue #21746)
                
                



the sensor absolut_pressure have no state_class.



So, if an integration or entity is missing support for long-term statistics, we should not document a workaround using templates, we should fix it.

Please report it as an issue in our issue tracker so support can be added for that integration/entity.

The Home Assistant Core issue tracker can be found here:

https://github.com/home-assistant/core/issues

Thanks! 👍

../Frenck
