### ISSUE TITLE
Python Scripts - Needs better instructions

### ISSUE THREAD

**Issue by pebblebed-tech** [home-assistant/home-assistant.github.io#21743]
### Feedback

Do to the lack of clear documentation for a newbie. I have wasted 4 hours.
1. For some reason the name field does not appear in the services gui. Which completely threw me. As I am use to ESPHome services where the fields are displayed. It would be good to show the full YAML. eg service call and name field.
2.  Although there is a note about logs, it could do with being more explicit about which log file. As I was looking in the server logs from the gui. Whereas I should have been looking in the home assistant log in the config directory

### URL

https://www.home-assistant.io/integrations/python_script/

### Version

2022.2.9

**Comment by frenck** [comment]
> For some reason the name field does not appear in the services gui. Which completely threw me. As I am use to ESPHome services where the fields are displayed. It would be good to show the full YAML. eg service call and name field.

This is documented right here:

https://www.home-assistant.io/integrations/python_script/#documenting-your-python-scripts

Did you find it to be incorrect? Could you describe what the issue is?

> Although there is a note about logs, it could do with being more explicit about which log file. As I was looking in the server logs from the gui. Whereas I should have been looking in the home assistant log in the config directory

I'm confused on this note, there is only 1 Home Assistant log file? Which other one are you referring to, and, it is wasn't the Home Assistant log file: Why did you think it would have been written there?

../Frenck

**Comment by pebblebed-tech** [comment]
Hi Frenck,
I have written these comments issue from the perspective of a new user, rather than an experienced user as the page is there to show new users the way
1. To aid new users the example shown in the "writing you first script" section should  have an associated services.yaml extract. 
2.  The newbie user would naturally look in the gui log Configuration| Setting | Logs not the actual log file located in the config folder.
Hope this clarifies

Cheers

Paul

**Comment by frenck** [comment]
> I have written these comments issue from the perspective of a new user

I get that, yet, I try to ask additional question to understand how you got there and what caused you to waste 4 hours.

From your initial message, the core of the issue isn't clear.

> To aid new users the example shown in the "writing you first script" section should have an associated services.yaml extract.

Having a service.yaml file is not needed?

> The newbie user would naturally look in the gui log Configuration| Setting | Logs not the actual log file located in the config folder.

I don't get that comment, as those are the same things?


That said, now you have gained the experience recently, from a new user perspective, it would be great if you would/could contribute to editing the page to improve on it for the next user?

**Comment by pebblebed-tech** [comment]
Hi Frenck,
The core issue was I believed the script was not working, because the log output in the gui did not show messages. But when I looked in the file I found them. Maybe I configuration.yaml is not correct so I dont see all the messages in the gui.
`logger:
  default: info`
This is as per the notes on the page

**Comment by frenck** [comment]
> Maybe I configuration.yaml is not correct so I dont see all the messages in the GUI.

![CleanShot 2022-02-25 at 09 36 47](https://user-images.githubusercontent.com/195327/155682812-87c25ca6-16bd-4d68-8027-14de16fecf07.png)

**Comment by pebblebed-tech** [comment]
Well as a newbie I assumed that loaded older log entries and entries that had been cleared! So that what the root of the issue not understanding the log mechanisms
