### ISSUE TITLE
workday sensor, added working days

### ISSUE THREAD

**Issue by lintaba** [home-assistant/home-assistant.github.io#21748]
### Feedback

Currently `workday` sensor supports workdays/holidays for most of the cases.
Unfortunately I havent found a way to add "extra" workdays to its list, either by date, or by name. 
Not sure how it happens in other countries, but in my country sometimes they move a workday to weekends, so another time it can be "merged together" to have a longer weekend.
ie.: `2022-03-26` (Saturday) counts as a workday.

Is there any way to do it, or any plan to extend it? Or should it be asked on from https://pypi.org/project/holidays/ instead?

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2022.2.9

**Comment by frenck** [comment]
This isn't possible with the integration at this point. So, that makes this a feature request.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
