### ISSUE TITLE
OnCue by Kohler

### ISSUE THREAD

**Issue by lsgv** [home-assistant/home-assistant.github.io#21740]
### Feedback

I can confirm this integration works with model 14RESA https://kohlerpower.com/en/residential/generators/product/14resa
OnCue data fields which are NA (depends on generator model I guess) appear as 0 which has been documented in a closed issue. This is not a problem as it is easy and straightforward to not show those data fields in HA.
Thanks for building this integration, very helpful.

### URL

https://www.home-assistant.io/integrations/oncue/

### Version

2022.2.8

### Additional information

https://kohlerpower.com/en/residential/generators/product/14resa

**Comment by bdraco** [comment]
The api currently doesn't have a way to determine which data should be displayed as `NA` 

https://github.com/home-assistant/core/issues/65628#issuecomment-1040423184
