### ISSUE TITLE
blank       assistant.io/integrations/

### ISSUE THREAD

**Issue by cliffkristensen** [home-assistant/home-assistant.github.io#21755]
### Feedback

there is nothing

### URL

https://www.home-assistant.io/integrations/

### Version

2022.2.9

**Comment by frenck** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/195327/155309070-6cde3208-5042-4de2-9c42-0ec8c25a7a41.png)


Can you provide some more information? Like, used browser, operating system, versions and those kinda things?

../Frenck

**Comment by cliffkristensen** [comment]
sorry it's something with my, Intrusion Detection in my router opnsense.
