### ISSUE TITLE
Uable to add this integrationn

### ISSUE THREAD

**Issue by MiAutomations** [home-assistant/home-assistant.github.io#21778]
### Feedback

I try using the Button   available in this link 

[https://rc.home-assistant.io/integrations/radio_browser ](url)

But I'm receiving a error 

![image](https://user-images.githubusercontent.com/47602733/155549696-07d5225b-9b7c-49e9-9a39-55c24b3972c7.png)

Can you please verify and help me in order to solve this issue ?

Thank you

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2022.3.0

**Comment by frenck** [comment]
Hi there @MiAutomations 👋 

It seems like you are having issues setting up an integration and want to report an issue with it, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks already 👍 

../Frenck
