### ISSUE TITLE
Waqi component documentation missing

### ISSUE THREAD

**Issue by mariniertje** [home-assistant/home-assistant.github.io#2177]
At some point in the last couple of weeks, the documentation for the Waqi component went missing. It is no longer listed under components and also not under Deprecated.

Restoring the documentation might help with some of the issues that are being logged for Waqi...

**Comment by fabaff** [comment]
Docs are still there...https://home-assistant.io/components/sensor.waqi/

**Comment by mariniertje** [comment]
Sorry...my bad... I was searching in the Weather category AND did a find in
the ALL category for "WAQI" and it showed no results.
Didn't realize I had to search for the non abbreviated name.

Thanks, Fabian. (now was able to figure out my WAQI stopped working,
because you suddenly need a token)
