### ISSUE TITLE
Groups have their own .yaml file

### ISSUE THREAD

**Issue by kellyatkinson** [home-assistant/home-assistant.github.io#21799]
### Feedback

This documentation page describes groups as part of `configuration.yaml` but I instead see a groups.yaml file in my (latest) HAOS installation. I'm not sure whether to add some syntax (what syntax?) to the groups.yaml file or to the configuration.yaml file. Can this please be made clearer on the page for people who are encountering groups for the first time?

### URL

https://www.home-assistant.io/integrations/light.group/

### Version

2022.2.9

**Comment by frenck** [comment]
> but I instead see a groups.yaml file in my (latest) HAOS installation.

`groups.yaml` is for general groups: <https://www.home-assistant.io/integrations/group>

Which is not the same as light groups.

`groups.yaml` is btw no longer created/used in new installations (to prevent confusion like this).

**Comment by kellyatkinson** [comment]
Thanks, this makes sense.
But my HA installation is about four weeks old! Should I delete the
groups.yaml file (and automations, scripts, and scenes) and remove the
include statements from the configuration.yaml file then? For a new user
this is awfully confusing.

It would be helpful if the documentation page on Groups referred to the
Light Groups page, and vice versa. These also do not appear on the TOC of
documentation topics which made them very hard to find when I started
trying to figure out the basics.

Thanks!
Kelly Atkinson

**Comment by frenck** [comment]
> But my HA installation is about four weeks old! Should I delete the
> groups.yaml file (and automations, scripts, and scenes) and remove the
> include statements from the configuration.yaml file then? For a new user
> this is awfully confusing.

Yeah, that will do the trick (it has been removed in the previous release, so that was recently done, you just missed that change in your instance :D)

> It would be helpful if the documentation page on Groups referred to the
> Light Groups page, and vice versa.

Actually, we don't agree on that. The older groups more generic groups, had a UI function back in the days. Nowadays, they don't add that much anymore (and are actually almost the wrong choice all the time). Platform-specific groups are the better choice in general. E.g., light groups, cover groups, etc. 

We are working toward bringing this stuff to the UI pretty soon, so this problem would be gone anyway at that point :)

**Comment by kellyatkinson** [comment]
Thanks so much for responding to my issue.

> The older groups more generic groups, had a UI function back in the days. Nowadays, they don't add that much anymore (and are actually almost the wrong choice all the time). Platform-specific groups are the better choice in general. E.g., light groups, cover groups, etc.

THIS was very very helpful - so I have made my light group as such, not as a generic group.
I hope the documentation will start to reflect this and will point users more towards the light groups etc.
