### ISSUE TITLE
just fixed issue with wemo and osram tunable white

### ISSUE THREAD

**Issue by fsundstrom** [home-assistant/home-assistant.github.io#2179]
Hello

I fund a problem and fixed it in bridge.py in ver 0.39.0

when I added my new osram tunable white 60 bulbs to my wemo bridge home assistant did not show any of the bridge devices.  after looking in the log i saw that the error was with reading devices attached to the Wemo bridge.  

after making the xml calls i found that the new bulb added capavilityValues to the soap response and that line  108 in homeassistant/deps/pywemo/ouimeaux_device/bridge.py was the issue as it was now getting a floating value.  

the following is the new line 108 with a float call to fix the issue:

value = tuple(int(float(v)) for v in value.split(':'))

Now it can handle the floating integers and like magic all my lights work in home assistant.

Hope this helps !

Frank Sundstrom
Systems Engineer  ;-)

**Comment by Molodax** [comment]
@fsundstrom, would it be better to post this information as the issue for the component instead of posting it as an issue for web-site? :)

**Comment by robbiet480** [comment]
This issue should be opened in the primary [Home Assistant repository](https://github.com/home-assistant/home-assistant/issues/new), not this one (docs repo).
