### ISSUE TITLE
Excessive recorder records

### ISSUE THREAD

**Issue by dziadeck47** [home-assistant/home-assistant.github.io#21790]
### Feedback

I am just writing to report my finding that the recorded does not recors just entity state, but it adds up e.g. all its attributes 
In effect any change in attribute creates additional record which the database needs to process and store, but which cannot be fairly used in history (or anywhere else I am aware of). 
As an example my switch.zigbeesonoff entity has hundreds of records daily, only because its linkquality changes, even if i dont actually switch it once.
It would be great to be able to outscope the attributes from the recorder to free up space and increase history processing speed (by I presume order of magnitude)

### URL

https://www.home-assistant.io/integrations/recorder/

### Version

2022.2.9

**Comment by balloob** [comment]
We have moved to splitting all data points to individual entities. So in this case your "link quality" data point should have been a seperate sensor and should have been disabled by default.

`zigbeesonoff` doesn't sound like an integration that is part of core and adapted to this new standards. I suggest you report this to the custom component author.
