### ISSUE TITLE
Add how to get BREL API Key

### ISSUE THREAD

**Issue by OmegaX-NL** [home-assistant/home-assistant.github.io#21797]
### Feedback

Hi,

It took me some time to get how to get the API key from the BREL app. Maybe you can put the info somewhere on the page?

**In iOS, you need to multi-tap on the “version x.x.x(xxxx)” grey info, which is showed at the bottom in the ‘me’ tab (4th tab).

For the Android app, Tap 5 times on the rightside of the photo place (4th tab).**

Kind regards,
Eltjo 

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2022.2.9

**Comment by starkillerOG** [comment]
@OmegaX-NL thank you very much for the feedback.
I will update the documentation to include the instructions for Brel.
