### ISSUE TITLE
Unclear when query will be run

### ISSUE THREAD

**Issue by rockymountainnative** [home-assistant/home-assistant.github.io#21793]
### Feedback

It's unclear when the query is run and updated. Unclear on how to trigger the query to be re-run and updated. Currently this appears that it is only run upon server restart.

### URL

https://www.home-assistant.io/integrations/sql/

**Comment by dgomes** [comment]
"Its IoT class is [Local Polling](https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/#classifiers)."

That means that sensor is periodically updated (as with **all** poll based sensors in HA)
