### ISSUE TITLE
Sun offset needs more explanation

### ISSUE THREAD

**Issue by nsolvepaul** [home-assistant/home-assistant.github.io#21806]
### Feedback

 "offset": "-01:00:00"

is that before or after the sunset?

### URL

https://www.home-assistant.io/integrations/sun/

### Version

2022.2.9

**Comment by Swamp-Ig** [comment]
This probably doesn't even belong here, it's [documented here](https://www.home-assistant.io/docs/automation/trigger/#sun-trigger)
