### ISSUE TITLE
lifetime energy output reports zeros

### ISSUE THREAD

**Issue by Rvh91** [home-assistant/home-assistant.github.io#21800]
### Feedback

Hello, 

Thank you for making the integration.

For me the "sensor.fmh0a4802f_lifetime_energy_output" entity is actually reporting a zero value between 12PM and approx 6:30AM. Meaning that in my dashboard, I get a huge minus spike at the start of each day, and then a huge positive spike when the sensor reports a non-zero value.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2022.2.9

**Comment by frenck** [comment]
Hi there @Rvh91 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
