### ISSUE TITLE
clarifications please

### ISSUE THREAD

**Issue by jon-bondy** [home-assistant/home-assistant.github.io#21818]
### Feedback

Under "Entries as JSON" I find "Assuming that the log file contains..."

What log file?

And how would the entry in the configuration.yaml file shown know which file is the source of the data.

A lot of this appears to be magical, which means unfathomable to a new user.

### URL

https://www.home-assistant.io/integrations/file/

### Version

2022.2.9

**Comment by frenck** [comment]
> What log file?

An imaginary one to set add story to the example.

> And how would the entry in the configuration.yaml file shown know which file is the source of the data.

> A lot of this appears to be magical, which means unfathomable to a new user.

I'm not sure what you are trying to say with the above? Could you try explaining your comment in different wording maybe?
