### ISSUE TITLE
Cant set icon and unique_id for derivative 

### ISSUE THREAD

**Issue by otmezger** [home-assistant/home-assistant.github.io#21817]
### Feedback

Why can't we set the icon for the derivative in the config file? it also does not support unique_id, which is strange. 

### URL

https://www.home-assistant.io/integrations/derivative/

### Version

2022.2.9

### Additional information

I expected to be able to set icon and unique_id from the config file for the derivative integration. In my case, I'm using the derivative to calculate kWh/h from kWh. I want the icon to be a "mdi:lightning-bolt" since this represents a power. 

```
- platform: derivative
    name: power_from_s0_template
    # entity_id: sensor.power_from_s0_template
    source: sensor.energy_meter_s0_template_kWh
    time_window: "00:01:00"  # Derivatives in this window will be averaged with a Simple Moving Average algorithm weighted by time
    icon: "mdi:lightning-bolt"
```

**Comment by frenck** [comment]
> Why can't we set the icon for the derivative in the config file? it also does not support unique_id, which is strange.

Because it hasn't been build and contributed 🤷‍♂️ 

Anyways, you have submitted documentation feedback. For requesting features, please use our community forum.

thanks!

../Frenck

**Comment by otmezger** [comment]
Thanks. Makes sense.
