### ISSUE TITLE
update camera documentation

### ISSUE THREAD

**Issue by thekiefs** [home-assistant/home-assistant.github.io#21823]
### Feedback

`rtsp_transport: udp` option created in #46623 is not documented

https://github.com/home-assistant/core/pull/46623

### URL

https://www.home-assistant.io/integrations/camera/

### Version

2022.2.9

**Comment by frenck** [comment]
This documentation linked it the page on high level options of camera entities, and nog implementation specific details?

The PR linked has nothing to do with the page you are giving feedback on?

Maybe I am missing something?

../Frenck

**Comment by thekiefs** [comment]
rtsp_transport: udp is not documented on either the Cameras documentation or the Stream documentation.

Shouldn't all the options & flags be documented somewhere?

**Comment by frenck** [comment]
It is? <https://www.home-assistant.io/integrations/generic/#rtsp_transport>

I think you are mixing up integrations
