### ISSUE TITLE
Rollease integration not reloading after Home assistant reboot...

### ISSUE THREAD

**Issue by randrcomputers** [home-assistant/home-assistant.github.io#21837]
### Feedback

Integration don't seem to restart with Home Assistant. If i reboot Home Assistant i need to Manually reload integration then all blinds work fine again. Any ideas?

### URL

https://www.home-assistant.io/integrations/acmeda/

### Version

2022.2.9

**Comment by klaasnicolaas** [comment]
Hi there @randrcomputers 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
