### ISSUE TITLE
Adding P1 Monitor integrations instructions are insufficient.

### ISSUE THREAD

**Issue by wanderingwonderer** [home-assistant/home-assistant.github.io#21832]
### Feedback

Specify what is expected as "Host" value and in what format. Also what the Host is expected to deliver. The "documentation" of this in it's current state is useless. It says "Follow the instruction on screen to complete the set up.", but there are no instructions.

### URL

https://www.home-assistant.io/integrations/p1_monitor/

### Version

2022.2.9

**Comment by frenck** [comment]
Sorry, maybe a bit blunt to ask, but I really want to understand: What is unclear about "Host" when connecting Home Assistant to a P1 Monitor instance?

**Comment by klaasnicolaas** [comment]
A `host` is the device you want to connect to over a network and a common term. You enter the IP address of the device that runs P1 Monitor.

**Comment by wanderingwonderer** [comment]
Thank you, so no http:, just the hostname/ip then. I still don’t quite understand if ”P1 Monitor” is a specific product or what’s required from the host. I think just a tiny bit of further info, like a link to some product info or specs would be helpful in the documentation.

**Comment by klaasnicolaas** [comment]
At the bottom of the page is an edit button, anyone can update the documentation 😉

**Comment by frenck** [comment]
> Thank you, so no http:, just the hostname/ip then

Yes, if it was `http://` prefixed, it would not be called "Host", those are called "URLs".

>  I still don’t quite understand if ”P1 Monitor” is a specific product or what’s required from the host.

https://www.ztatz.nl/p1-monitor/

To integrate Home Assistant with the P1 Monitor software, it will need a running instance of P1 Monitor, which needs a computer (host) to run on?

>  I think just a tiny bit of further info, like a link to some product info or specs would be helpful in the documentation.

There is a link in the first sentence of the P1 Monitor integration page in our documentation. Please check out their project for information on specifications for things like requirements, installing and running P1 Monitor.

Specifications like those are not in scope for the Home Assistant project.

That said, if you have a suggestion for an edit, please feel free to provide one 👍

**Comment by wanderingwonderer** [comment]
And there it is. I can’t believe I missed the link - in the first sentence as you said. In dutch though, but there’s always Google translate. (I probably missed a link to an english version to!) 
Thank you for your patience guys, and sorry to have bothered you. I’m closing this now.

**Comment by frenck** [comment]
Don't worry @wanderingwonderer 👍

**Comment by klaasnicolaas** [comment]
@wanderingwonderer there is no English version, originally it was made for Dutch / Belgian users.
