### ISSUE TITLE
Aborted: Unexpected error

### ISSUE THREAD

**Issue by Theskyer** [home-assistant/home-assistant.github.io#21839]
### Feedback

I've treid the official home energy wizard intergration for Home Assistant but when I enter the IP adres of my P1 meter I get the following error: 

![image](https://user-images.githubusercontent.com/96866590/155963591-b68a4b86-56e3-4fca-9671-9a561fc675c4.png)

i've verified the IP adres is correct via the MAC Adres and when I call the API using the webbrowser (http://{IP_ADDRESS}/api/v1/data) it does show actual data. 

![image](https://user-images.githubusercontent.com/96866590/155964203-3041fda3-44a1-4df3-ac88-e4b9f0b96e3a.png)

Some details:

Home Assistant OS 7.4
Core Version: core-2022.2.9
Supervisor Version: supervisor-2022.01.1
P1 meter V 2.13
API enabled in app (and callable). 

I've had this issue with both the HACS version as well as the Official integration since the very start. Always this error. 

### URL

https://www.home-assistant.io/integrations/homewizard/

### Version

2022.2.9

**Comment by DCSBL** [comment]
Try to powercycle your P1 meter, If that works it maybe is related to https://github.com/home-assistant/core/issues/66669 and will be fixed in an upcoming firmware-update.

**Comment by Theskyer** [comment]
I've tried the powercycle and even completely setup the device again to no avail.

**Comment by Theskyer** [comment]
It might be good to know that my p1 meter didn't work on the older core version either....

**Comment by DCSBL** [comment]
Is there something to see in the log that maybe helps with debugging? You also can add/update this in `configuration.yml` to see more.

```
logger:
  default: info
  logs:
    homeassistant.components.homewizard: debug
```

**Comment by Theskyer** [comment]
Done, where can I view the log ?

**Comment by DCSBL** [comment]
https://my.home-assistant.io/redirect/logs/

**Comment by DCSBL** [comment]
@frenck, can you move this issue to core?

**Comment by frenck** [comment]
We generally don't move issues from docs to core, as the issues form for core and documentation feedback is totally different.

This issue should have been closed instead of handled as it was submitted as documentation feedback. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by Theskyer** [comment]
Is this helpfull? (the log you directed me to)

_Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homewizard/config_flow.py", line 175, in _async_try_connect_and_fetch
    await energy_api.initialize()
  File "/usr/local/lib/python3.9/site-packages/aiohwenergy/hwenergy.py", line 69, in initialize
    if not await device.update():
  File "/usr/local/lib/python3.9/site-packages/aiohwenergy/device.py", line 62, in update
    response = await self._request("get", "api")
  File "/usr/local/lib/python3.9/site-packages/aiohwenergy/hwenergy.py", line 141, in request
    _LOGGER.debug("%s, %s", resp.status, await resp.text("utf-8"))
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError_

**Comment by DCSBL** [comment]
@Theskyer, as mentioned by Frenck, please close this issue and reopen one in [here](https://github.com/home-assistant/core/issues/new?template=bug_report.yml). You can reference this issue.

**Comment by Theskyer** [comment]
Done as requested: 

https://github.com/home-assistant/core/issues/67388
