### ISSUE TITLE
Tado Smart AC Control V3+ cannot be set to heat/cool/fan

### ISSUE THREAD

**Issue by flosoft** [home-assistant/home-assistant.github.io#21831]
### Feedback

Tado Smart AC Control V3+ cannot be set to heat/cool/fan. The only command that works is turning the AC off.

### URL

https://www.home-assistant.io/integrations/tado/

### Version

2022.2.9

### Additional information

https://community.home-assistant.io/t/tado-smart-ac-control-v3-cannot-be-set-to-heat-cool-fan/390689

**Comment by smnmgn** [comment]
Hi,
the issue is still present in version 2022.4.7
thank you

**Comment by MacrosorcH** [comment]
Hello,
The issue is still present in version 2022.5.1

**Comment by klaasnicolaas** [comment]
An issue about this has already been created in core, so I'm closing it here.
