### ISSUE TITLE
Why is instructions writing so DIFFICULT

### ISSUE THREAD

**Issue by IT-Gipsy** [home-assistant/home-assistant.github.io#21841]
### Feedback

Guys...

it's lovely to find all possibilities and Options.... But I JUST want to be able to see the EVOHOME settings in Home Assistant
(like the temperature etc)
So I can Switch OFF my Heat Pump if the temperature is above 22,5 degrees and On when below 22 degrees

I have to Plow Through Github to find what needs to be loaded where... Why not just write the proper procedure and THEN add the tweaks... this is so damn user unfiendly

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2022.2.9

**Comment by frenck** [comment]
Thanks for the feedback!

> But I JUST want to be able to see the EVOHOME settings in Home Assistant
(like the temperature etc)

That is the climate entity that shows? Which is a generic entity in Home Assistant?

> I have to Plow Through Github to find what needs to be loaded where... Why not just write the proper procedure and THEN add the tweaks... this is so damn user unfriendly

We welcome contributions to the documentation! So, please, help with making it better. Each page has a link to suggest an edit to every page.

👍 

../Frenck

**Comment by IT-Gipsy** [comment]
Thanks Frenck,

But I don't even get to integrate EvoHome in Home assistant yet.
I would like to find Simple and plain instructions

- download xxxxx
- open Hoe Assistent
- go to Settings
- Find and open xxx
- copy and paste the downloade info to xxxx
and so on

just Plain and Simple
because at this moment I don't even know where to start
THANKS

**Comment by IT-Gipsy** [comment]
> Hey there @zxdavb, mind taking a look at this feedback as it has been labeled with an integration (`evohome`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L156) for? Thanks! (message by CodeOwnersMention)

Don't understand
