### ISSUE TITLE
Option missing in thermostat lovelace card

### ISSUE THREAD

**Issue by flight2k** [home-assistant/home-assistant.github.io#21852]
### Feedback

Hi,

The thermostat lovelace card is very good but 1 thing is missing : the min/max limit. If we can but limitation on min max themperature the user can set this card will be perfect.

Thanks

### URL

https://www.home-assistant.io/lovelace/thermostat/

### Version

2022.2.9

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
