### ISSUE TITLE
Messagebird integrations page does not show logo from "brands", message_bird vs. messagebird

### ISSUE THREAD

**Issue by ausserirdischesindgesund** [home-assistant/home-assistant.github.io#21858]
### Feedback

In the brands repository there is a high quality logo/icon for the messagebird integration, but on the web page for this integration, the placeholder "logo not available" is shown. 

Supposedly this is the case, because brands has a "messagebird" directory, but on the website the integration is called "message_bird" with underscore.

### URL

https://www.home-assistant.io/integrations/message_bird/

### Version

2022.2

### Additional information

Sorry for this very low priority issue, but I would love to have no placeholder images on the web page any more. About 10 to go ;)

**Comment by frenck** [comment]
not stale bot... thanks!
