### ISSUE TITLE
No WIFI cable

### ISSUE THREAD

**Issue by mcselede** [home-assistant/home-assistant.github.io#21854]
### Feedback

I followed the instructions and used this etcher program to copy the hass programm. I put the SD card then into to Raspberry Pi 3B+. The next step says I should connect the raspberry to mu router using a Lan Cable.
The problem is I have a ASUS wireless lan router but I don't own a fitting wireless lan cable. I searched all over the interweb: your shop, amzoom, ibay, alibubba, I even called ASUS, but no wireless lan cable.
Could you tell me where I can find a wireless lan cable, or just update you installation manual, so people can use your OS without cable using WIFI?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.2.9

### Additional information

If you insist using a cable you could also implement https://datatracker.ietf.org/doc/html/rfc1149 into your image

**Comment by frenck** [comment]
Home Assistant can only be set up when connected via Ethernet.

> The problem is I have a ASUS wireless lan router but I don't own a fitting wireless lan cable. 

There is no such thing as a wireless LAN cable...

> without cable using WIFI?

That is not possible.

**Comment by mcselede** [comment]
> Home Assistant can only be set up when connected via Ethernet.

But the seller on ebay said the Raspberry Pi 3B+ has Wifi and can connect to my ASUS router. Because he lied to me I gave him only 1 star.

How do I use this ether thingy? I know ether is a solvent used in glue. Do you recommend a special brand of glue? And where do I glue Raspberry Pi 3 B+ to? Do I glue it to the router?

**Comment by ChevySSinSD** [comment]
You can try this method if you don't have an ethernet cable:
https://community.home-assistant.io/t/headless-wifi-setup/291798/7

Or, you can purchase an ethernet cable: 
https://www.amazon.com/AmazonBasics-RJ45-Cat-6-Ethernet-Patch-Cable-5-Feet-1-5-Meters/dp/B00N2VISLW/

@frenck:
> Home Assistant can only be set up when connected via Ethernet.
>
> > without cable using WIFI?
> 
> That is not possible.

In the documentation, it states under suggested hardware:
- Ethernet cable. Home Assistant can work with Wi-Fi, but an Ethernet connection is more reliable and highly recommended.`

Should the documentation be updated to state an ethernet cable is required for initial setup and recommended for ongoing use?
