### ISSUE TITLE
change ip

### ISSUE THREAD

**Issue by th48178** [home-assistant/home-assistant.github.io#21863]
### Feedback

Hi,

I just moved to a UDM pro from my previous network controller setup and I have not found any option to just simply change the ip. It seems like I have to completely delete the integration to change ip, username and or password.

can this be made a simpler option for this plugin.

thanks

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2022.2.9

**Comment by frenck** [comment]
Hi there @th48178 👋 

You don't need to delete it. Just add a new one (add it again); Home Assistant will recognize it's the same as the existing entry and update it.

This applies to almost all integrations/configuration entries Home Assistant has.

**Comment by Kane610** [comment]
It is not recommended to keep using the same entry when moving from one controller to another as the unique id is exclusive to the currently registered controller. It is better to set it up a new as there is no migration logic for doing this.
