### ISSUE TITLE
Add serial forwarder to the network options

### ISSUE THREAD

**Issue by DavyLandman** [home-assistant/home-assistant.github.io#21867]
### Feedback

I've made a small project: https://github.com/DavyLandman/p1-esp8266 that uses a small esp8266 and pipes the serial port to any tcp listener.

So it might be a nice addition to the list of [Serial to network proxies](https://www.home-assistant.io/integrations/dsmr/#serial-to-network-proxies)?

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2022.2.9

### Additional information

My forwarder uses the same schematic as daniel-jong's
[esp8266_p1meter](https://github.com/daniel-jong/esp8266_p1meter) but instead of parsing the messages on the ESP and turning them into mqtt posts, I only forward it to the connected TCP client. The code is smaller, and it lets HA take care of parsing the different dialects.

**Comment by DavyLandman** [comment]
I still think it would help users with a short and easy path towards dsmr integration.

**Comment by frenck** [comment]
Hi there @DavyLandman 👋 

Feel free to open up a PR to suggest an edit to the page.

../Frenck
