### ISSUE TITLE
Need more info on the Documentation

### ISSUE THREAD

**Issue by rjing001** [home-assistant/home-assistant.github.io#21877]
### Feedback

Had to add the Version Integration for to replace Updater in Lovelace.  In the docs you explain how to install (pretty simple, almost overspained it).  But you don't tell us anything about the integration.  What entities does it have? What are their values? Please add those items.

### URL

https://www.home-assistant.io/integrations/version/

### Version

2022.3.0

**Comment by ludeeus** [comment]
> The Version integration can display the current Home Assistant Core versions.
This is at the top of the page?

**Comment by rjing001** [comment]
Ok, but how.  What do I use in my automation or in lovelace to utilize this feature.  DETAILS.

By the way it does more than just "display the current Home Assistant Core versions."

It added two entities (sensor.home_assistant_website & binary_sensor.home_assistant_website_update_available).  The first returns the version number in both the developer tool and in the integration, the second shows Up-to-date or Update available in the integration, but only 'on' or 'off' in the developer tools.  Very Confusing.  Is it to much to ask that you add a little information in the documentation on the entities and how they can be used.
