### ISSUE TITLE
Radio browser automation not working with lage radio libraries

### ISSUE THREAD

**Issue by bikeophilipp** [home-assistant/home-assistant.github.io#21888]
### Feedback

When I want to create an automation with the radio browser to play a certain radio station I cannot create it. 
When selecting a radio station from the Radio Browser it always returns to the Overview of Automations and does not safe the recently created one. 

I was able to limit this problem to large libraries. Tested out several radio stations from US and Germany and this error happens. With stations from smaller countries/libraries it was working. 

However, I was able to play these stations from the Media library.

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2022.3.0

**Comment by stefanuytterhoeven** [comment]
Same problem here.

**Comment by frenck** [comment]
Hi there @bikeophilipp 👋 

It seems like you want to report an issue with an integration, however, you have submitted documentation feedback instead. Please make sure you report things in the right places (when in doubt, see: https://www.home-assistant.io/help)

For this specific problem you are reporting, there is already an issue open here:

https://github.com/home-assistant/frontend/issues/11932

../Frenck
