### ISSUE TITLE
Link to image missing

### ISSUE THREAD

**Issue by Hippe-Lip** [home-assistant/home-assistant.github.io#21883]
### Feedback

Nice page with instructions, but the most essential part is missing. the page states "WRITE THE IMAGE TO YOUR BOOT MEDIA", but I've searched everywhere on the site, but couldn't find any suggestion or link to where to find this image! Why does the page start with step 2 and not with step ONE: where to get this image?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.3.0

**Comment by frenck** [comment]
I'm not sure if I follow your documentation suggestion?

![CleanShot 2022-03-04 at 14 41 29](https://user-images.githubusercontent.com/195327/156773875-40454f29-1f78-4291-9a99-0097bef66f68.png)

It flashes from a URL (marked with `1`), so it downloads it for you.
The download URLs to use are listed (marked with `2`) and can be pasted into Etcher (marked with `3`).


Could you clarify what is incorrect about the current page?
