### ISSUE TITLE
search 

### ISSUE THREAD

**Issue by philou669** [home-assistant/home-assistant.github.io#21882]
### Feedback

It would be great to have a search button. With this ton of radio stations it is hard and long to find a specific station.

thank you for your amazing work

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2022.3.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
