### ISSUE TITLE
Wrong link do PDF

### ISSUE THREAD

**Issue by JaCoLJcL** [home-assistant/home-assistant.github.io#21889]
### Feedback

Hello, link to _DLNA ContentDirectory SearchCriteria_ is actual down (500 serwer error)

### URL

https://www.home-assistant.io/integrations/dlna_dms/

### Version

2022.3.0

**Comment by chishm** [comment]
Thanks for letting me know. It looks like the official server of the UPnP organisation is down. There's not much we can do about that, but if it stays down for more than a week I'll find an alternative source.
