### ISSUE TITLE
No API key can be provided

### ISSUE THREAD

**Issue by Xorfor** [home-assistant/home-assistant.github.io#21890]
### Feedback

During the integration set up, no API key can be provided! Is there a way to add this manually?

### URL

https://www.home-assistant.io/integrations/pi_hole/

### Version

2022.3.0

**Comment by frenck** [comment]
The API key is asked for if it is needed.

If you checked "Statistics Only" during set up:

![CleanShot 2022-03-04 at 13 00 59@2x](https://user-images.githubusercontent.com/195327/156759997-0c94c9f8-80da-438e-b069-072b2ee5b43e.png)

It would not need any API key, thus it would not ask for it either.

../Frenck
