### ISSUE TITLE
MAC Address, name or pairing options

### ISSUE THREAD

**Issue by joaquinvacas** [home-assistant/home-assistant.github.io#21891]
### Feedback

There's no option to set a MAC for the device, not even the name of the emulated bridge.

This causes issues with some apps, for example, Hue Essentials.

(00:00:00:00:00:00 MAC Address + no name)

Also, as the UI doesn't represent a thing about this integration, how can we link this to other devices that request to press a link button?

Other solutions like diyHue use a web UI and has link button, but cannot find anything here.

### URL

https://www.home-assistant.io/integrations/emulated_hue/

### Version

2022.3.0

**Comment by frenck** [comment]
Hi there @joaquinvacas 👋 

Thank you for reaching out. We this GitHub tracker for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
