### ISSUE TITLE
Changes on 2022.3.1

### ISSUE THREAD

**Issue by jello1974** [home-assistant/home-assistant.github.io#21905]
### Feedback

Please change back the look of the alarm panel. Now it looks verry ugly. Previous look was perfect, why change something that looks good (code input text).
Please consider my request.
Thank you

### URL

https://www.home-assistant.io/lovelace/alarm-panel/

### Version

2022.3.1

**Comment by frenck** [comment]
Hi there @jello1974 👋 

Thanks for submitting documentation feedback, however, it seems like it is not documentation-related at all.

For more information about the recent UI changes, please see our release notes:

<https://www.home-assistant.io/blog/2022/03/02/release-20223/#ui-upgrades>

Thanks! 👍 

../Frenck
