### ISSUE TITLE
provide recommended alternative after deprecation

### ISSUE THREAD

**Issue by Lx** [home-assistant/home-assistant.github.io#21902]
### Feedback

I note that this integration is now deprecated and will be removed in 2022.5.

I'm eager to know the reasoning behind the deprecation and whether automatic update checking can be achieved by configuring a different integration, or whether it is expected that future update checking be done manually and externally.

### URL

https://www.home-assistant.io/integrations/updater/

### Version

2022.3.1

**Comment by balloob** [comment]
Updates are now shown in the config menu, and we are working on expanding this feature.
