### ISSUE TITLE
Integration of rademacher into fritz smarthome 

### ISSUE THREAD

**Issue by hubdihubdi** [home-assistant/home-assistant.github.io#21919]
### Feedback

There is a product from Rademacher RolloTron DECT 1213
It works with dect and the fritzbox. It would be awesome if it could be controlled through the integration with homeassistant 
Thanks 

### URL

https://www.home-assistant.io/integrations/fritzbox/

### Version

2022.3.1

**Comment by mib1185** [comment]
Hi @hubdihubdi 
please use the [feature request](https://community.home-assistant.io/c/feature-requests) section of our forum to contribute on existing or create new feature requests.
For sure, contributions are always welcome, so please feel free to create a PR on your own.
