### ISSUE TITLE
How to add a device in whitelist

### ISSUE THREAD

**Issue by GroupPolicy41** [home-assistant/home-assistant.github.io#21926]
### Feedback

Is there any way to add a whitelist? Can we add our notebook in the whitelist ? Because if i close the session, always i have to use mfa code. 

### URL

https://www.home-assistant.io/docs/authentication/multi-factor-auth/

### Version

2022.3.2

**Comment by frenck** [comment]
Hi there @GroupPolicy41 👋 

Unfortunately, that is not a possible option at this point.

../Frenck

**Comment by GroupPolicy41** [comment]
Hi @frenck 

You mean there is a no option for trusted devices? We have to use a code from authentication app each logon? I also tried trusted network config in configurayion.yml file but it's not worked.

**Comment by frenck** [comment]
> You mean there is a no option for trusted devices?

Correct.

> We have to use a code from authentication app each logon?

Yes.

>  I also tried trusted network config in configurayion.yml file but it's not worked.

Correct, that is documented as such as well.

**Comment by GroupPolicy41** [comment]
Hi @frenck 

So you mean, Trusted network yaml code is not working. Will there be a fix for trusted devices in the future? Entering this code every time is annoying because.

**Comment by frenck** [comment]
> So you mean, Trusted network YAML code is not working. 

No, it is working as designed and documented.

**Comment by GroupPolicy41** [comment]
@frenck 

Could you please share worked command? Because it's not working for me . I'm trying to add in configuration.yaml file but still it's needed code. I used this command. What's wrong? I adding this in /config/configuration.yaml

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      trusted_users:
        192.168.1.102: 2gdfdffd...... (username id)
      allow_bypass_login: true

**Comment by frenck** [comment]
You cannot skip MFA when it is enabled.

You are asking for something we don't have.

**Comment by GroupPolicy41** [comment]
@frenck  Please let me clerify. What's the purphose trusted networks? I want to do this; if i'm connected to my home network (local) i should past without mfa key. The trusted networks command I shared above doesn't for this? If we can not skip MFA then why using trusted network command? I mean for what? Also i've homeassistant mobile ap on the iphone, in the past it's asked mfa just one, i can open the software without any mfa code anymore.
