### ISSUE TITLE
RPi.GPIO Failed To Setup - Attempting install of RPi.GPIO==0.6.1

### ISSUE THREAD

**Issue by SabareeshnathHPE** [home-assistant/home-assistant.github.io#2192]
Hi Guys,

I am really stuck at the point , when home assistant starts , in log it shows attempeting install of Rpi.GPIO == 0.6.1 and it fails.

I have RPi.GPIO installed in the system .

Board : Raspberry Pi Model B
OS: Raspbian

Please Find The Log Below

----------------------------------------LOG------------------------------------------------

Feb 26 17:39:24 raspberrypi hass[2280]: 17-02-26 17:39:23 INFO (Thread-8) [homeassistant.util.package] Attempting install of RPi.GPIO==0.6.1
**Feb 26 17:40:58 raspberrypi hass[2280]: Command "/srv/homeassistant/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g_wxab97/RPi.GPIO/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cidw0vgc-record/install-record.txt --single-version-externally-managed --compile --install-headers /srv/homeassistant/include/site/python3.4/RPi.GPIO --home=/tmp/tmptqearu6o" failed with error code 1 in /tmp/pip-build-g_wxab97/RPi.GPIO/
Feb 26 17:41:03 raspberrypi hass[2280]: 17-02-26 17:41:03 ERROR (Thread-8) [homeassistant.bootstrap] Not initializing rpi_gpio because could not install dependency RPi.GPIO==0.6.1**
Feb 26 17:41:03 raspberrypi hass[2280]: 17-02-26 17:41:03 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service_data=notification_id=invalid_config, title=Invalid config, message=The following components and platforms could not be set up:
Feb 26 17:41:03 raspberrypi hass[2280]: * rpi_gpio
Feb 26 17:41:03 raspberrypi hass[2280]: Please check your config, service_call_id=3051888304-1, service=create>
Feb 26 17:41:04 raspberrypi hass[2280]: 17-02-26 17:41:04 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=None, entity_id=persistent_notification.invalid_config, new_state=<state persistent_notification.invalid_config=The following components and platforms could not be set up:
Feb 26 17:41:04 raspberrypi hass[2280]: * rpi_gpio
Feb 26 17:41:04 raspberrypi hass[2280]: Please check your config; title=Invalid config @ 2017-02-26T23:11:04.048981+05:30>>
Feb 26 17:41:04 raspberrypi hass[2280]: 17-02-26 17:41:04 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]: service_call_id=3051888304-1>
Feb 26 17:41:04 raspberrypi hass[2280]: 17-02-26 17:41:04 ERROR (MainThread) [homeassistant.bootstrap] Component rpi_gpio failed to setup
Feb 26 17:41:04 raspberrypi hass[2280]: 17-02-26 17:41:04 ERROR (MainThread) [homeassistant.bootstrap] Unable to prepare setup for platform switch.rpi_gpio because dependency rpi_gpio could not be initialized
Feb 26 17:41:04 raspberrypi hass[2280]: 17-02-26 17:41:04 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service_data=notification_id=invalid_config, title=Invalid config, message=The following components and platforms could not be set up:
Feb 26 17:41:04 raspberrypi hass[2280]: * [rpi-gpio](https://home-assistant.io/components/rpi_gpio/)
Feb 26 17:41:04 raspberrypi hass[2280]: Please check your config, service_call_id=3051888304-2, service=create>
Feb 26 17:41:04 raspberrypi hass[2280]: 17-02-26 17:41:04 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service_data=notification_id=invalid_config, title=Invalid config, message=The following components and platforms could not be set up:
Feb 26 17:41:04 raspberrypi hass[2280]: * [rpi-gpio](https://home-assistant.io/components/rpi_gpio/)
Feb 26 17:41:04 raspberrypi hass[2280]: * [switch.rpi-gpio](https://home-assistant.io/components/switch.rpi_gpio/)
Feb 26 17:41:04 raspberrypi hass[2280]: Please check your config, service_call_id=3051888304-3, service=create>
Feb 26 17:41:04 raspberrypi hass[2280]: 17-02-26 17:41:04 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: old_state=<state persistent_notification.invalid_config=The following components and platforms could not be set up:
Feb 26 17:41:04 raspberrypi hass[2280]: * rpi_gpio
Feb 26 17:41:04 raspberrypi hass[2280]: Please check your config; title=Invalid config @ 2017-02-26T23:11:04.048981+05:30>, entity_id=persistent_notification.invalid_config, new_state=<state persistent_notification.invalid_config=The following components and platforms could not be set up:
Feb 26 17:41:04 raspberrypi hass[2280]: * [rpi-gpio](https://home-assistant.io/components/rpi_gpio/)
Feb 26 17:41:04 raspberrypi hass[2280]: Please check your config; title=Invalid config @ 2017-02-26T23:11:04.533699+05:30>>
Feb 26 17:41:04 raspberrypi hass[2280]: 17-02-26 17:41:04 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_executed[L]: service_call_id=3051888304-2>

**Comment by Landrash** [comment]
Issues for components should not be reported in the documentation repo. 
Have a look at the main repo [here](https://github.com/home-assistant/home-assistant).

Also tested to install this component without fail on a fresh HASSbian install.
Most likely the problem is in your install. Try to install the dependency manually ti get a better view of what fails.
