### ISSUE TITLE
Performance Unifi Protect integration in HA vs Homebridge

### ISSUE THREAD

**Issue by rhvs** [home-assistant/home-assistant.github.io#21931]
### Feedback

After many attempts to get the new integration running fast -near- real time, I switched back to the spare Pi4 and use the main Unifi Protect plugin on Homebridge (https://github.com/hjdhjd/homebridge-unifi-protect). I still wonder if it's possible to have the same performance within HA, or, use the HB version for a better HA integration?

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2022.3.2

**Comment by frenck** [comment]
Hi there @rhvs 👋 

Thank you for reaching out. It seems like you have a question, however, you have submitted documentation feedback instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by AngellusMortis** [comment]
Also, this is outside of the scope of the UniFi Protect integration. 

You will want to post this under the `stream` integration. @allenporter and @uvjustin have been doing a lot to get the latency down lower, but you need to set up HTTP/2 as documented in the [UniFi Protect docs](https://www.home-assistant.io/integrations/unifiprotect/#delay-in-video-feed) to make full use of [LL-HLS from the stream integration](https://www.home-assistant.io/integrations/stream#ll-hls---low-latency-hls). It will commonly fallback to HLS (~15 second delay) without it.

**Comment by rhvs** [comment]
OK - I'll repost somewhere else 👍  Just wanted to share the HB integration is working flawless (no delay (not even 1 s), iCloud+ integration and more), which hopefully can save someone lots of time. Thanks for the quick replies!
