### ISSUE TITLE
WSL venv installation instructions  

### ISSUE THREAD

**Issue by sunishnet** [home-assistant/home-assistant.github.io#21932]
### Feedback

Following WSH install instructions fails in the step homeassistant
@host:/srv/homeassistant$ **python3.9 -m venv .**
with error
Error: Command '['/srv/homeassistant/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

Got it fixed after 
sudo apt install python3.9
sudo apt install python3.9-dev
sudo apt install python3.9-venv

remaining steps from 
sudo chown homeassistant:homeassistant /srv/homeassistant
worked only after above steps

### URL

https://www.home-assistant.io/installation/windows/

### Version

2022.3.2

**Comment by frenck** [comment]
That is possible, as stated on the page:

![image](https://user-images.githubusercontent.com/195327/157078739-24bf70fb-7ece-43a5-b2c3-8ef68a7165ea.png)

Thanks for providing feedback though, that is appreciated 👍

**Comment by sunishissac** [comment]
True, but it's an easy fix or update to add to the documentation for Ubuntu 20.04 which comes as default with Windows WSL

**Comment by frenck** [comment]
Sure, but that will break it for others as these are generic instructions. If we change this for Ubuntu, it will break for e.g., Raspberry Pi OS or Debian (which have a way larger share in our community).

Anyways, these parts can never be complete or correct based on the many distributions out there. Thus the warning and the offered alternatives.

**Comment by sunishnet** [comment]
![image](https://user-images.githubusercontent.com/2966772/157432820-98ca3dd3-8a16-4df1-9630-aa21034ba848.png)
The instructions were for [Windows and WSL where ubuntu is default](url)  and not generic.

**Comment by frenck** [comment]
The instruction themselves are generic (imported/re-used across multiple pages)...

That said, we use Debian as the source of truth. If you are having issues adjusting the instructions to your use case, we recommend looking at one of our other installation methods instead.
