### ISSUE TITLE
Fitbit integration

### ISSUE THREAD

**Issue by 007-DJ** [home-assistant/home-assistant.github.io#21952]
### Feedback

I understand the data rates and updates every 30 minutes.  After monitoring the results, I note that the updates are not consistently timed. Is there a way to set the time (30 Minutes apart) to say 15 and 45 minutes past the hour? That would allow fort time based triggers at 20 ans 50 minutes past the hour to assist meeting hourly goals. Thank you in advance.
RMoore@MyFairPoint.net

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2022.3.3

**Comment by frenck** [comment]
Polling updates are never consistently timed in Home Assistant. This is a feature actually, if all Home Assistant instances out there would query third-party's at a fixed time, they would get big spikes of requests and loads that are hard to handle for any provider.
