### ISSUE TITLE
Broadlink RM PRO IR

### ISSUE THREAD

**Issue by fwgman** [home-assistant/home-assistant.github.io#21959]
### Feedback
RM PRO version  v21

Logger: homeassistant.components.broadlink.remote
Source: components/broadlink/remote.py:301
Integration: Broadlink (documentation, issues)
First occurred: 00:19:38 (1 occurrences)
Last logged: 00:19:38

Failed to learn 'power': [Errno -1] Authentication failed

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2022.3.3

**Comment by felipediel** [comment]
Hi. Your device is locked probably, you can unlock it with the Broadlink app.

**Comment by frenck** [comment]
Hi there @fwgman 👋 


It seems like you want to report an issue with an integration, or are in need of support on setting it up. However, you have submitted documentation feedback instead.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

In case you want to report a bug, please use the Home Assistant Core issue tracker:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
