### ISSUE TITLE
fresh install problem

### ISSUE THREAD

**Issue by jacla242** [home-assistant/home-assistant.github.io#21954]
### Feedback

Hi,
Just flashed Raspberry4 a 2nd time, as system was hanging at preparing home assistant, 
looking at supervisor logs tried the DNS trick just to be sure, but not related. Eventually gave up reflashed the sd card and tried again see below the full log in additional info

22-03-10 12:22:57 WARNING (MainThread) [supervisor.resolution.evaluations.base] System detect unauthorized source code modifications. (more-info: https://www.home-assistant.io/more-info/unsupported/source_mods)

can you please help? no clue to get this operational.  Ran as a test home assistant on hyperv instant and that worked quite well.
but with this install I'm a bit lost.

### URL

https://www.home-assistant.io/more-info/unsupported/source_mods/

### Version

2022.3.3

### Additional information

Home Assistant logo
Preparing Home Assistant
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing...
[11:22:35] INFO: Using udev information from host
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:22:35] INFO: Starting local supervisor watchdog...
22-03-10 11:22:38 INFO (MainThread) [__main__] Initializing Supervisor setup
22-03-10 11:22:38 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
22-03-10 12:22:38 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: raspberrypi4-64
22-03-10 12:22:38 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor homeassistant/aarch64-hassio-supervisor with version 2022.03.2
22-03-10 12:22:38 INFO (SyncWorker_0) [supervisor.docker.supervisor] Connecting Supervisor to hassio-network
22-03-10 12:22:38 INFO (SyncWorker_0) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/aarch64-hassio-supervisor:2022.01.1']
22-03-10 12:22:40 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
22-03-10 12:22:40 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-10 12:22:40 INFO (MainThread) [__main__] Setting up Supervisor
22-03-10 12:22:40 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
22-03-10 12:22:40 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
22-03-10 12:22:40 INFO (MainThread) [supervisor.dbus.manager] Load dbus interface io.hass.os
22-03-10 12:22:40 INFO (MainThread) [supervisor.dbus.manager] Load dbus interface org.freedesktop.systemd1
22-03-10 12:22:40 INFO (MainThread) [supervisor.dbus.manager] Load dbus interface org.freedesktop.login1
22-03-10 12:22:40 INFO (MainThread) [supervisor.dbus.manager] Load dbus interface org.freedesktop.hostname1
22-03-10 12:22:41 INFO (MainThread) [supervisor.dbus.manager] Load dbus interface org.freedesktop.timedate1
22-03-10 12:22:41 INFO (MainThread) [supervisor.dbus.manager] Load dbus interface org.freedesktop.NetworkManager
22-03-10 12:22:41 INFO (MainThread) [supervisor.dbus.manager] Load dbus interface de.pengutronix.rauc
22-03-10 12:22:41 INFO (MainThread) [supervisor.dbus.manager] Load dbus interface org.freedesktop.resolve1
22-03-10 12:22:41 INFO (MainThread) [supervisor.host.info] Updating local host information
22-03-10 12:22:41 INFO (MainThread) [supervisor.host.services] Updating service information
22-03-10 12:22:41 INFO (MainThread) [supervisor.host.network] Updating local network information
22-03-10 12:22:42 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-03-10 12:22:42 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-03-10 12:22:42 INFO (MainThread) [supervisor.host.apparmor] Loading AppArmor Profiles: {'hassio-supervisor'}
22-03-10 12:22:42 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-cli with version 2021.12.0
22-03-10 12:22:42 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-dns with version 2021.06.0
22-03-10 12:22:42 INFO (MainThread) [supervisor.plugins.dns] Updated /etc/resolv.conf
22-03-10 12:22:42 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-audio with version 2021.07.0
22-03-10 12:22:42 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-observer with version 2021.10.0
22-03-10 12:22:42 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/aarch64-hassio-multicast with version 2022.02.0
22-03-10 12:22:42 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-03-10 12:22:44 INFO (MainThread) [supervisor.homeassistant.secrets] Loaded 0 Home Assistant secrets
22-03-10 12:22:44 INFO (SyncWorker_0) [supervisor.docker.interface] Attaching to ghcr.io/home-assistant/raspberrypi4-64-homeassistant with version landingpage
22-03-10 12:22:44 INFO (MainThread) [supervisor.homeassistant.core] Starting HomeAssistant landingpage
22-03-10 12:22:44 INFO (MainThread) [supervisor.os.manager] Detect Home Assistant Operating System 7.4 / BootSlot A
22-03-10 12:22:44 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/a0d7b954 repository
22-03-10 12:22:44 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/core repository
22-03-10 12:22:45 INFO (MainThread) [supervisor.store] Loading add-ons from store: 62 all - 62 new - 0 remove
22-03-10 12:22:45 INFO (MainThread) [supervisor.addons] Found 0 installed add-ons
22-03-10 12:22:45 INFO (MainThread) [supervisor.backups.manager] Found 0 backup files
22-03-10 12:22:45 INFO (MainThread) [supervisor.discovery] Loaded 0 messages
22-03-10 12:22:45 INFO (MainThread) [supervisor.ingress] Loaded 0 ingress sessions
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.SETUP
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-10 12:22:45 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not running - CoreState.SETUP
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.SETUP
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-10 12:22:45 INFO (MainThread) [__main__] Running Supervisor
22-03-10 12:22:45 INFO (MainThread) [supervisor.os.manager] Rauc: A - marked slot kernel.0 as good
22-03-10 12:22:45 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.INITIALIZE' starting 0 add-ons
22-03-10 12:22:45 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SYSTEM' starting 0 add-ons
22-03-10 12:22:45 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 0 add-ons
22-03-10 12:22:45 INFO (MainThread) [supervisor.core] Skiping start of Home Assistant
22-03-10 12:22:45 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 0 add-ons
22-03-10 12:22:45 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
22-03-10 12:22:45 INFO (MainThread) [supervisor.core] Supervisor is up and running
22-03-10 12:22:45 INFO (MainThread) [supervisor.homeassistant.core] Home Assistant setup
22-03-10 12:22:45 INFO (MainThread) [supervisor.host.info] Updating local host information
22-03-10 12:22:45 INFO (SyncWorker_1) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi4-64-homeassistant:landingpage to ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2022.3.3
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-03-10 12:22:45 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi4-64-homeassistant with tag 2022.3.3.
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-03-10 12:22:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-03-10 12:22:45 INFO (MainThread) [supervisor.host.services] Updating service information
22-03-10 12:22:45 INFO (MainThread) [supervisor.host.network] Updating local network information
22-03-10 12:22:45 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-03-10 12:22:46 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.TRUST - ContextType.PLUGIN / cli
22-03-10 12:22:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-03-10 12:22:54 ERROR (MainThread) [supervisor.utils] Can't execute check_trust while a task is in progress
22-03-10 12:22:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-03-10 12:22:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-03-10 12:22:54 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.CREATE_FULL_BACKUP - ContextType.SYSTEM / None
22-03-10 12:22:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-03-10 12:22:56 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-03-10 12:22:56 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-03-10 12:22:57 WARNING (MainThread) [supervisor.resolution.evaluations.base] System detect unauthorized source code modifications. (more-info: https://www.home-assistant.io/more-info/unsupported/source_mods)
22-03-10 12:22:57 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-03-10 12:22:57 INFO (MainThread) [supervisor.jobs] 'ResolutionFixup.run_autofix' blocked from execution, system is not healthy

**Comment by jacla242** [comment]
Also FYI, eventually it goes into some kind of loop: 
22-03-10 12:28:45 WARNING (MainThread) [supervisor.homeassistant.core] Error on Home Assistant installation. Retry in 30sec
22-03-10 12:29:15 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi4-64-homeassistant:landingpage to ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2022.3.3
22-03-10 12:29:15 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image ghcr.io/home-assistant/raspberrypi4-64-homeassistant with tag 2022.3.3.

**Comment by frenck** [comment]
This is the documentation feedback form you have been using, and is not meant to report issue.

The issue you are trying to report though, is known and tracked here: <https://github.com/home-assistant/supervisor/issues/3495#issuecomment-1063909657>

**Comment by jacla242** [comment]
Apologies for wrong place to put the question.  Thanks for showing me the already existing issue and rapid response.
Much appreciated
