### ISSUE TITLE
whats wrong

### ISSUE THREAD

**Issue by Irming1109** [home-assistant/home-assistant.github.io#21955]
### Feedback

im not sure what is meant here.. i have not changed any parts of sourcecode - In fact i dont even know how to do such a thing ? so what is wrong with my installation since it just went unsupported ?

### URL

https://www.home-assistant.io/more-info/unsupported/source_mods/

### Version

2022.3.3

### Additional information

s

**Comment by frenck** [comment]
Hi there @Irming1109 👋 

It seems you want to report an issue, however, you have submitted documentation feedback instead. Please make sure you go to the right places.

see https://www.home-assistant.io/help on where to go.

In this case, the issue you are looking for is here: <https://github.com/home-assistant/supervisor/issues/3495#issuecomment-1063909657>

../Frenck
