### ISSUE TITLE
InfluxDB

### ISSUE THREAD

**Issue by bosshoss16** [home-assistant/home-assistant.github.io#21972]
### Feedback

I have not been able to find a list of tag_attributes or a list of fields/options/etc that can be sent from HA to InfluxDB OSS.

For example, I have Kasa smart plugs and I have only seen how to send over friendly_name.  Each devices has seven entities and I am trying to send the Device Name to InfluxDB so that I can filter/sort on that.

Thank you.

### URL

https://www.home-assistant.io/integrations/influxdb/

**Comment by frenck** [comment]
> I have not been able to find a list of tag_attributes or a list of fields/options/etc that can be sent from HA to InfluxDB OSS.

There is no definitive list for this. Each entity/integration can freely define its own entity attributes.

You could, for example, use the state dev tool to find attributes provided by the entities you are interested in:

[![Open your Home Assistant instance and show your state developer tools.](https://my.home-assistant.io/badges/developer_states.svg)](https://my.home-assistant.io/redirect/developer_states/)
