### ISSUE TITLE
Not Able to reconfigure NUT

### ISSUE THREAD

**Issue by jwilleke** [home-assistant/home-assistant.github.io#21971]
### Feedback

Recently moved NUT server to a different device.

Was not able to reconfigure the NUT Server integration.

Had to remove the NUT Integration and re-add the NUT Integration change the settings.

Would be nice to be able to display the configuration GUI or at least provide the location of a file where the configuration.

### URL

https://www.home-assistant.io/integrations/nut/

### Version

2022.3.3

**Comment by frenck** [comment]
> Had to remove the NUT Integration and re-add the NUT Integration change the settings.

That is the correct procedure, as it is a new device?

> Would be nice to be able to display the configuration GUI

It's a new device? What is there to configure?

> or at least provide the location of a file where the configuration

The storage is not meant to be edited manually, so there is no use in doing that.


I feel like you think editing the exiting entry to adjust the host was the way to go? But actually, that is not. New devices should get new entries, Home Assistant is designed around that.

**Comment by frenck** [comment]
Closing this issue, as there has been no response from the author.
