### ISSUE TITLE
yeelightsunflower light platform is missing or has broken links

### ISSUE THREAD

**Issue by lindsaymarkward** [home-assistant/home-assistant.github.io#2199]
Hi.
I can't find the yeelightsunflower light platform that was merged in 0.39. 
It doesn't show up when I click on "Light" or "Added in 0.39" in Components, and the link to it in the blog post for 0.39 is broken: 
https://home-assistant.io/blog/2017/02/25/config-panel-and-state-restoration/#read-more links to: 
https://home-assistant.io/components/light.yeelight-sunflower

The code in the HA platform points to: 
https://home-assistant.io/components/light.yeelightsunflower 
but this is also 404.

@fabaff edited the link in https://github.com/home-assistant/home-assistant/pull/6219

**Comment by fabaff** [comment]
Shows up on https://home-assistant.io/components/#added_one_version_ago. I copied the wrong link around.
