### ISSUE TITLE
Good start

### ISSUE THREAD

**Issue by RandyAndy1965** [home-assistant/home-assistant.github.io#21994]
### Feedback

Was wondering if the other binairy sensor will also come available, or does Renault not let us grab them. Like door sensors, etc. At least for my Renault they are set as unavailable.

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2022.3.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
