### ISSUE TITLE
youless integration

### ISSUE THREAD

**Issue by jacla242** [home-assistant/home-assistant.github.io#21992]
### Feedback

Got energy dashboard working,  Using youless integration  (youless 120 adapter on p1 port, firmware 1.4.5-EL)

Power high and power low are switched around.  (so graph shows Power low while it should be high and vice versa)
Also setting static price for power high and low doesn't seem to work
for gas it seems to work.

Any ideas how to easily swap high/low ?

### URL

https://www.home-assistant.io/integrations/youless/

### Version

2022.3.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
