### ISSUE TITLE
Add hint to Solar API under Prerequisites

### ISSUE THREAD

**Issue by Olli2807** [home-assistant/home-assistant.github.io#21990]
### Feedback

Hello, this is my first edit request, so I hope this is the correct way to do it...

In the chapter Prerequisites add:
"Make sure the "Solar API" is activated by checking in the Inverters web interface.

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2022.3.4

**Comment by farmio** [comment]
Hi 👋!
Well, why don't you just add it? There is an "edit" link on bottom of every page that links directly to a GitHub editor. 

Keep in mind that this only applies to Gen24 devices *shipped* with firmware 1.14 (see German document http://213.33.117.110/~/downloads/Solar%20Energy/User%20Information/SE_UI_Latest_News_GEN24_DE.pdf ) so it probably affects quite few users. Newer firmwares have it activated by default and other models (Symo etc) don't have an option to deactivate it.

**Comment by Olli2807** [comment]
OK, sorry I´m completeley new to Github. 
You are right regarding the number of users. For me the document is not clear about future SW versions. Looking into the web applications note, for me it seems like deactivated Solar API this is the new standard for Gen24 devices.

```
Hinweis
Die So­lar-API ist eine Ether­net-ba­sier­te, of­fe­ne JSON-Schnitt­stel­le. Wenn die­se Op­ti­on ak­ti­viert ist, kön­nen IOT-Ge­rä­te im lo­ka­len Netz­werk ohne Au­then­ti­fi­zie­rung auf die In­for­ma­tio­nen des Wech­sel­rich­ters zu­grei­fen. Aus Si­cher­heits­grün­den ist die Schnitt­stel­le stan­dard­mä­ßig de­ak­ti­viert und soll­te nicht ak­ti­viert wer­den, falls dies nicht durch eine Dritt­an­bie­ter­an­wen­dung er­for­der­lich ist (z. B. EV-La­de­ge­rät, Smart-Home-Lö­sun­gen usw.).

Zur Über­wa­chung emp­fiehlt Fro­ni­us die Ver­wen­dung von [So­lar.web](https://www.solarweb.com/), das ei­nen si­che­ren Zu­griff auf den Wech­sel­richt­er­sta­tus und die Pro­duk­ti­ons­in­for­ma­tio­nen bie­tet.
```

**Comment by farmio** [comment]
Oh, right 👍. I was misreading this - seems like all new Gen24 models come with deactivated API. 
Then I guess a hint that the integration uses Fronius' `SolarAPI`, which may have to be activated first, would be appropriate.

**Comment by Olli2807** [comment]
I have tried to provide something with the edit-button.
And thanks again for your Help.

**Comment by farmio** [comment]
🤔 this should open a new pull request. I don't see one yet, but since I only have a phone available right now I can't really give you much guidance on how this exactly works, sorry. 

Anyway, thanks for your contribution (or at least the will to 😉)!
