### ISSUE TITLE
Updater component deprecated, what's the replacement?

### ISSUE THREAD

**Issue by SamLeatherdale** [home-assistant/home-assistant.github.io#21991]
### Feedback

The Updater component documentation says that this component is deprecated and will be removed. However there are no suggestions about what's going to replace it. I use the Docker container installation, so I'm not sure how I'll know there are updates available now. I'm not sure why it's being deprecated either, as this seems like important information to have.

### URL

https://www.home-assistant.io/integrations/updater/

### Version

2022.3.4

**Comment by frenck** [comment]
As per release notes and the breaking changes listed in the release notes:

Use the `version` integration.

https://www.home-assistant.io/integrations/version

**Comment by SamLeatherdale** [comment]
Hi there

Thanks for providing this info, would it be worth adding this fact to the Updater documentation, since I completely missed the release notes and that was the first page I checked?

**Comment by frenck** [comment]
The updater integration documentation is pending removal, so adding something to that won't be adding much value.

I cannot help if release notes aren't read 🤷

**Comment by nickidw** [comment]
The new Version component says a new version is available, but nowhere on my instance does it show the new version as available or allow me to update to it.

**Comment by frenck** [comment]
@nickidw That is not related to this documentation feedback.
