### ISSUE TITLE
missing entity for Active or not active 

### ISSUE THREAD

**Issue by Fadoz** [home-assistant/home-assistant.github.io#22002]
### Feedback

I'm missing a entity on this device to enable automations to use the active state of the thermostat. it is shown in the dashboard as a status but would be nice to have as an entity. 

this would allow to use the thermostat to enable other heating devices when heat is requested.

after checking the code I guess it's part of the following:
device.operationStatus.mode,

hope it can be added, the rest works like a charm

### URL

https://www.home-assistant.io/integrations/lyric/

### Version

2022.3.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
