### ISSUE TITLE
Differences in Hassbian 'upgrading' documentation

### ISSUE THREAD

**Issue by m4rkireland** [home-assistant/home-assistant.github.io#2200]
There is a difference in how the home assistant user is named in the documentation:

In this one, the home assistant user is formatted as 'homeassistant': https://home-assistant.io/docs/hassbian/upgrading/ (ie sudo systemctl stop homeassistant@homeassistant.service).

In this one, it's formatted as 'home-assistant': https://home-assistant.io/docs/hassbian/common-tasks/#update-home-assistant (ie sudo systemctl stop home-assistant@homeassistant.service).

Has it been changed in recent builds of hassbian? In my older build, home-assistant is correct.

**Comment by Landrash** [comment]
Fixed in referenced commit. Thanks :cookie:
