### ISSUE TITLE
Sensor "FULL CONFIGURATION FOR 2.XX INSTALLATIONS" missing key parameters

### ISSUE THREAD

**Issue by b-neufeld** [home-assistant/home-assistant.github.io#22013]
### Feedback

Under the sensor configuration for "FULL CONFIGURATION FOR 2.XX INSTALLATIONS", parameters are missing for the full config: host, port, and ssl. 

While configuring a sensor after migrating from influx 1.7 to 2.x, I was getting an error like: influxdb bucket is not accessible due to '(401) reason: unauthorized http response headers

The host, port, and ssl fields are required in sensor.yaml for the sensor to connect to influxdb. 

It is possible I hit this issue due to using different storage buckets for HA data writing to influx, and non-HA data being pulled into HA from influx. 

### URL

https://www.home-assistant.io/integrations/influxdb/

### Version

2022.3.4

**Comment by b-neufeld** [comment]
Ah, shoot. It's possible I didn't have a query string configured correctly, but I wasn't taking detailed enough notes to be sure. Sincere apologies if this is just noise.

**Comment by frenck** [comment]
No problem @b-neufeld 👍
