### ISSUE TITLE
https://www.home-assistant.io/integrations/tasmota - SetOption correction

### ISSUE THREAD

**Issue by peecee69** [home-assistant/home-assistant.github.io#22015]
### Feedback

Good documentation.  However, I think in the Requirements section, where the fourth line says:

Tasmota devices configured for native discovery (SetOption19 0)

Should be:

Tasmota devices configured for auto-discovery (SetOption19 1)

Thank you,
Paul

### URL

https://www.home-assistant.io/integrations/tasmota/

### Version

2022.3.4

**Comment by frenck** [comment]
Your suggestion is incorrect. The current documentation is correct.

SetOption 19 should be 0, as it uses native device discovery (setting option 19 to 1 would be MQTT discovery, which is not what this integration uses or needs).
