### ISSUE TITLE
Details on API?

### ISSUE THREAD

**Issue by danielszilagyi** [home-assistant/home-assistant.github.io#22012]
### Feedback

Hi,

Could some details be shared about the paid API key on the integration page please?
I just signed up for it, set it up in the integration config, and now I'm getting the solar production forecast for the upcoming days nicely, not just for tomorrow.

I would like to get the estimated production in a sensor value also for future days, but couldn't find any information. Is that possible somehow?

thank you

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2022.3.4

**Comment by klaasnicolaas** [comment]
Can you clarify a bit more what exactly you are missing in the documentation?
For integration issues I refer you to the [core repository](https://github.com/home-assistant/core), this issue is for documentation feedback only.
