### ISSUE TITLE
How to create  "your.longlived.token"

### ISSUE THREAD

**Issue by kerryland** [home-assistant/home-assistant.github.io#22016]
### Feedback

This page should mention how to create the mentioned `"your.longlived.token"` and link to https://developers.home-assistant.io/docs/auth_api#long-lived-access-token

### URL

https://www.home-assistant.io/integrations/prometheus/

### Version

2022.3.4

**Comment by knyar** [comment]
Makes sense! Please feel free to submit a PR.
