### ISSUE TITLE
Date Condition

### ISSUE THREAD

**Issue by Trentos-9** [home-assistant/home-assistant.github.io#22014]
### Feedback

It would be nice to have a date condition to block out actions for parts of the year. Seasonal adjustments. 

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2022.3.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
