### ISSUE TITLE
energy-usage-graph by energy-devices

### ISSUE THREAD

**Issue by brembygit** [home-assistant/home-assistant.github.io#22039]
### Feedback

I would like to see the energy usage distribution (24h) by the devices
Today we have 2 different graphs

- the energy-usage-graph where we can see the total consumption by hours and (if configured) the split between the tariffs
- the energy-devices-graph where we can see the overall consumption by devices

If we combine this 2 different information we can see when (in the 24h) a device consumes energy
This can be helpful when we don't have a meter for every device, or when we are able to measure only a subset of devices; 
in this way we can try to figure out what additional devices are drying energy (eg. night lights vs dryer) 
Another use case can be validating the quality of the collected metered data, eg. if we are tracking the dryer with a dedicated meter but the measure is wrong, and we are getting an unexpected amount

In general, this view can help people to digger into what are the different entities that concur to the main energy consumption and try to understand if there is a better way to distribute the load (eg. the dryer usually takes 3h, but in the same time there is also the dishwasher running), today is not clear at first glance if there is any better optimization 

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2022.3.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
