### ISSUE TITLE
host ipaddress

### ISSUE THREAD

**Issue by Hermanfbe** [home-assistant/home-assistant.github.io#22034]
### Feedback

How to change the host ipaddress after installation ?

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2022.3.5

**Comment by rklomp** [comment]
You wil have to remove and readd the integration. I expect after readding the integration the sensor entities will be reused so you wont lose any data. I have not tested this.

**Comment by Hermanfbe** [comment]
> You wil have to remove and readd the integration. I expect after readding the integration the sensor entities will be reused so you wont lose any data. I have not tested this.

That's what I did and it's working :) but there should be another way I hope ?

**Comment by frenck** [comment]
@Hermanfbe Normally one can just add it again (without removing the old), and it should be picked up (Home Assistant will recognize it already knows the device and update the configuration).

However, just peeked at the codebase, the SMA integration doesn't seem to handle that correctly. Which is sorta/kinda a bug actually. 🙈

**Comment by rklomp** [comment]
Thanks for checking @frenck. I will have a look how this is normally done and update the SMA config flow accordingly.
Do you have a good example integration I can use?

**Comment by frenck** [comment]
@rklomp Its really tiny, I've opened up a PR for it, see: https://github.com/home-assistant/core/pull/68179

**Comment by frenck** [comment]
Closing this issue, as is behavior has been changed/fixed in the core codebase.
