### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by TokarevSergey** [home-assistant/home-assistant.github.io#22045]
### Feedback

Hello. Using this card to play mp4 files. Please tell me if it is possible to loop the video, constantly play it again. Thanks.

### URL

https://www.home-assistant.io/dashboards/iframe/

### Version

2022.3.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
