### ISSUE TITLE
Manual Configuration of PLM port in configuration.yaml not working

### ISSUE THREAD

**Issue by shoeboo** [home-assistant/home-assistant.github.io#22042]
### Feedback

I have 2 USB devices (zooz z-wave stick and insteon plm) connected to my raspberry pi running home assistant OS. Occasionally the USB ports switch, like today when I applied a HA OS update. I have tried to add a manual configuration with new usb port address but still receive same error of "modem didn't respond to ID request". Am I missing something? Deleting the configuration and setting up again including renaming devices is getting painful.
Pulled from my configuration.yaml
```
insteon:
  port: /dev/ttyUSB0
```

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.3.5

**Comment by teharris1** [comment]
The manual configuration has been taken out of the documentation. This issue should be closed.. Thanks
