### ISSUE TITLE
YAML examples are incorrect; they show friendly name instead of area id for area:

### ISSUE THREAD

**Issue by rpitera** [home-assistant/home-assistant.github.io#22043]
### Feedback

I was trying out the area card using the YAML examples and I couldn't get them to work.  I realized that instead of the area friendly name for area: it should instead be the Area ID that is shown when you are in the area configuration and click on edit next to the name.

So instead of this:
```
- type: area
  area: bedroom
```
it should be this:
```
- type: area
  area: d90ead402996430dadee5cc39323ab6e

```

### URL

https://www.home-assistant.io/dashboards/area/

### Version

2022.3.5

### Additional information

Along with correcting this, it should be explained how to obtain the Area ID.

> The Area ID is displayed in the edit mode for an area.  Configuration > Devices & Services > Areas.  Click on the area in question, then click on the edit button next to the area's name.  The Area ID will be shown at the top of the dialog box.

Perhaps you can also include a screen shot with the Area ID indicated?

**Comment by frenck** [comment]
Area IDs are by default generated in a friendly format (as a slug of the initial name).  The given examples are therefore thus correct.

**Comment by rpitera** [comment]
@frenck could you possibly take another look at this?  I hate to be a pest but I think that your response is incorrect given the test I just did below.

1. When I use YAML, if I use the friendly name for ANY of my areas with the area card, I get the error message "Area not found".   It only works for me if I use the area id shown in the edit mode card for the area in question.    

2. When I create an area card in the UI, I _can_ pick an area from the drop down list using the friendly name.  But if you show the code editor it is indeed using the area id **NOT** the area friendly name.  
 
So I respectfully disagree that the YAML examples are correct when in fact the UI code editor itself shows the underlying code is using the **area id**.  If I try replacing this with the example shown in the docs, the area card in the UI no longer works and shows the same error as YAML.

![Untitled](https://user-images.githubusercontent.com/19910294/168489894-60039ea6-de93-4c20-b2d5-dfe2283afcb2.png)

Not trying to be argumentative here, just trying to get to the root of the issue.

**Comment by frenck** [comment]
If you have "old" areas (e.g., created over a year ago), yeah that would indeed be the area ID. However, we have stopped using those UUIDs for areas a long long time ago.

Try it: Create a new area, call it "Frenck" and you'll see it will be "frenck" as the area ID

**Comment by rpitera** [comment]
OK, seeing that working now.  But I have to imagine that I am not the only 'long timer' out there with "old" formatted areas.  And until I put in this PR, I never saw anything in a release breaking change that addressed this.  Do you think it's so rare that we should just close this or would you entertain adding some kind of explanation or note?  I'd be willing to take a shot at writing one up if you think it's worth it.

**Comment by frenck** [comment]
> Do you think it's so rare that we should just close this or would you entertain adding some kind of explanation or note? I'd be willing to take a shot at writing one up if you think it's worth it.

Our documentation reflects the current state of our code base; not the history. Thus the current documentation is correct.

**Comment by rpitera** [comment]
OK, I can't _really_ argue that.  And at least now I know so I can answer the question when it comes up in the forums or reddit.
