### ISSUE TITLE
Energy Editing / Errors

### ISSUE THREAD

**Issue by gedger** [home-assistant/home-assistant.github.io#22041]
### Feedback

The energy monitor solution is great but I still get the occasional erroneous entry added into the feed which them effects the resulting weekly/monthly/yearly figures for ever. There needs to be an energy editor to allow easy correction of the data but until that time please add a definitive guide for manually correcting the data, even if that involved SQL, marked as for experts only. Otherwise for me the value of the energy facility is worthless as one wrong data point screws up the results for ever.

E.g.
1. How to correct an erroneous solar reading
2. How to correct an erroneous grid reading.
3. etc. etc.

### URL

https://www.home-assistant.io/docs/configuration/troubleshooting/

### Version

2022.3.5

**Comment by drthanwho** [comment]
There are already posts in the forum with guides on how to do this https://community.home-assistant.io/t/recalculate-statistics-table-sum-to-fix-wrong-energy-data/371334
There is also a PR started on making it possible to adjust them.

These issues tend to happen with manually made sensors such as template sensors so perhaps work out what's wrong in those. If a core integration caused this, you should also open up an issue in the core repository as it shouldn't do that

**Comment by gedger** [comment]
The problem is there are many people who have summited guides, each one is slightly different and suggests a slightly different approach to solving the issue. Deleting data when all that is needed to to add a single missing reading also seems total overkill. Glad there's a PR, I couldn't find it so apologies.

I'm using the Tesla Powerwall integration which has been mainly good but has missed the occasional reading.

**Comment by drthanwho** [comment]
> Deleting data when all that is needed to to add a single missing reading also seems total overkill

It's not that simple since the value is a sum so missing one means every value past that is wrong and all need to be adjusted from the hour the problem accured. It's not as simple as just adding/substracting the wrong vallue from the current value. Then there are also two different tables in the database where the adjusting is necessary.

This is the PR if you want to keep an eye on it :D https://github.com/home-assistant/core/pull/65147
