### ISSUE TITLE
android_ip_webcam doesn't work anymore

### ISSUE THREAD

**Issue by Abdull** [home-assistant/home-assistant.github.io#22052]
### Feedback

As much as I understand the results from https://github.com/home-assistant/core/issues/67523 , _Android IP Webcam_ doesn't fulfill a purpose anymore and is misleading. It doesn't seem to be possible anymore - unfortunately - to access features proclaimed by the _android_ip_webcam_ integration, such as changing front and normal camera, changing settings such as flashlight activation etc.

### URL

https://www.home-assistant.io/integrations/android_ip_webcam/

### Version

2022.3.5

**Comment by frenck** [comment]
The link issue, was a bug, this has been fixed.

**Comment by Abdull** [comment]
I think you misunderstood this issue and closed it too early: this integration does not set up sensors anymore.

**Comment by frenck** [comment]
@Abdull According to the codebase it does. So in that case, it must be a bug. Please report bugs in the core issue tracker, as this is documentation feedback.
