### ISSUE TITLE
Yamaha Network Receiver not available after power off

### ISSUE THREAD

**Issue by klkohl** [home-assistant/home-assistant.github.io#22055]
### Feedback

I've included the receiver in my configuration.yaml as directed here: https://www.home-assistant.io/integrations/yamaha

The Yamaha receiver is connected to a smart plug that powers down the receiver periodically. After powering up the receiver Home Assistant doesn't detect the receiver as available. Is there a way for Home Assistant to automatically detect the receiver as being available when power is restored?

### URL

https://www.home-assistant.io/integrations/yamaha/

### Version

2022.3.5

**Comment by davel4wa** [comment]
I have an older Yamaha RX series receiver that is not network enabled so I am just imagining the problem. The Yamaha integration supports the on/off operation. Are you trying to save energy by powering the receiver off externally? If so you have likely frustrated yourself as there has to be some power available in order for the network interface to operate and this is probably available when the 'power switch' is operated but not when the power is removed. One of the setup parameters of the integration is the IP address of the receiver. Unless you have assigned a fixed IP address in the receiver setup, assuming that is an option, dhcp is going to assign a semi random address and the integration will fail with an address different from your integration setup.
Perhaps you have considered this and I am just bloviating.

**Comment by klkohl** [comment]
Yes, I was trying to save energy. Between the receiver, tv, and some other peripherals, there is approximately a 22 W draw when everything is idle. I ended up leaving it on. Thanks for taking the time to respons.
