### ISSUE TITLE
Growatt Entities do not show up in Energy Dashboard

### ISSUE THREAD

**Issue by ArnevanDelft** [home-assistant/home-assistant.github.io#22064]
### Feedback

In the Energy Dashboard> Solar Panels I cannot add the Growat Production Entity to the Dashboard as the Entity does not show up:
in the dropdown menu a link shows to this page:
https://www.home-assistant.io/more-info/statistics/
with the bug and to post this message to the developer to solve the issue:

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2022.3.5

**Comment by indykoning** [comment]
Long Term Statistics are available for the "Total Lifetime Energy" sensors so they should show up in the dropdown.
If they don't you may have disabled the recorder/history for these entities

Take a look if these sensors show any issue under [Developer Tools > Statistics](https://my.home-assistant.io/redirect/developer_statistics)

**Comment by CloCkWeRX** [comment]
Duplicate of #21659

**Comment by ArnevanDelft** [comment]
> Long Term Statistics are available for the "Total Lifetime Energy" sensors so they should show up in the dropdown. If they don't you may have disabled the recorder/history for these entities
> 
> Take a look if these sensors show any issue under [Developer Tools > Statistics](https://my.home-assistant.io/redirect/developer_statistics)

Thanks! I guess I didn’t expect that I should have added the lifetime energy output! It works fine now!
