### ISSUE TITLE
Missing information?

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#22067]
### Feedback

Video, 17'37" Shows 'content not verified by Google'
Have set up config, rebooted.
Add integration
Link Google account
Authorise your account
![authErr](https://user-images.githubusercontent.com/298535/159034542-41969e6d-bdb1-4ee1-8a26-2cbe58f6e61d.png)

Very complex procedure.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.3.5

**Comment by allenporter** [comment]
Hi, see https://github.com/home-assistant/core/issues/67662 for an ongoing issue. It has some temporary workaround steps

**Comment by allenporter** [comment]
Going to duplicate with Issue #22141
