### ISSUE TITLE
Separate string data for two strings

### ISSUE THREAD

**Issue by gabrielke** [home-assistant/home-assistant.github.io#22078]
### Feedback

I like the integration so far so thank you for the great work!
Question: do you support separated string data? I have two strings set up and would like to see their voltage and current data separately.

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2022.3.5

**Comment by farmio** [comment]
Hi 👋! 
Only the datapoints you see (mind the ones disabled by default) are supported. 
The integration uses Fronius' SolarAPI which doesn't provide separate string data afaik. You may use the `Modbus` integration to fetch additional data over ModbusTCP if your inverter model provides them. 

Please note that this is a bug/issue tracker. For support questions and feature requests use the [community forum](https://community.home-assistant.io).
