### ISSUE TITLE
Directory /mnt/data/supervisor/ not exists

### ISSUE THREAD

**Issue by outofsight** [home-assistant/home-assistant.github.io#22081]
### Feedback

```
➜  ~ cd /mnt/data/supervisor/
cd: no such file or directory: /mnt/data/supervisor/
➜  ~

```

Where is data folder on HassOS?

Where is data folder for all addons?

### URL

https://www.home-assistant.io/faq/sdcard_files/

### Version

2022.3.5

**Comment by frenck** [comment]
By the command prompt it seems you are using the ssh & terminal add-on, which is not what the page states. The page states the path on the OS level, not add-on level.

**Comment by outofsight** [comment]
Sorry, I don't understand. 
But yes, I was trying to access files from terminal or SSH, the same files and the same way I can access on a supervised install at `/user/share/hassio/addons/data`...
I found this page

EDIT: I now understand, maybe

**Comment by outofsight** [comment]
Unstale

**Comment by frenck** [comment]
Closing this issue, as the current page is correct.
