### ISSUE TITLE
Tesla powerwall integration

### ISSUE THREAD

**Issue by Rubenconzels** [home-assistant/home-assistant.github.io#22106]
### Feedback

the integration for tesla powerwall does not seem to work anymore

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2022.3.5

**Comment by jrester** [comment]
Could you please provide us more information like logs so we can identify the issue?

**Comment by bdraco** [comment]
Hi there @Rubenconzels  👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here: <https://github.com/home-assistant/core/issues>

Thanks! 👍
