### ISSUE TITLE
fritzbox credentials 

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#22104]
### Feedback

It would be nice to get some advice on username/password changes on the fritzbox. 

I just changed the username and password on the fritzbox and the integration fails to login (surprise). 
Where can I change the credentials? What about using the secret.yaml for it?

### URL

https://www.home-assistant.io/integrations/fritzbox/

### Version

2022.3.5

**Comment by frenck** [comment]
The integration should ask you to re-authenticate, which allows you to enter a new username/password.

Please check your integrations dashboard if such request is prompted, if not, please raise a bug report here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by hklages** [comment]
#68476
