### ISSUE TITLE
provide link to frenck config github

### ISSUE THREAD

**Issue by spacecabbie** [home-assistant/home-assistant.github.io#22113]
### Feedback

make a link to https://github.com/frenck/home-assistant-config
or make a static copy of that config it explains in 1 eye how linking and including config files work something I had issues with

### URL

https://www.home-assistant.io/integrations/group/

### Version

2022.3.6

**Comment by dannytsang** [comment]
@spacecabbie do you mean the structure of the config folder or how to refer to other configuration files or something else?

**Comment by spacecabbie** [comment]
> @spacecabbie do you mean the structure of the config folder or how to refer to other configuration files or something else?
ok yea created the issue on the go. its actualy for: https://www.home-assistant.io/docs/configuration/splitting_configuration/
But that has already gotten a majoor rewrite I should check there more often. this can be closed sorry.
