### ISSUE TITLE
Warning Message about nest OOB deprecation

### ISSUE THREAD

**Issue by sebyldino** [home-assistant/home-assistant.github.io#22141]
### Feedback

Hello,
For all documentation files
It would be wise to put the warning message at the top of the page. Especially when it comes to a message reporting an outdated integration. I would have saved $5 before realizing that it is no longer supported...

Good day

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.3.7

**Comment by allenporter** [comment]
Hi see https://github.com/home-assistant/core/issues/67662#issuecomment-1065436947 for context on the current state of this.

**Comment by allenporter** [comment]
Would definitely love contributions to improving the documentation for this. I'm focused on resolution of the root cause and hoping a volunteer can pick this up.

**Comment by dpawson** [comment]
If it is any help. Google have closed my query with
"Thanks for your patience while we reviewed your project.

Your app is for personal use, so your project doesn't need to be verified. You can keep using your app with the “unverified app” screen showing.

Apps like yours, that don't need restricted scopes verification, are listed in the [Google Cloud Console](http://console.cloud.google.com/) with a status of ‘Rejected’. This status is meant to be shown for all apps that don't need verification. Your users won't be affected by the ‘Rejected’ status, as long as you have set up your app correctly for your specific use case."

I still don't know how to use this 'feature'

**Comment by allenporter** [comment]
I posted a link above to the current state and temporary workarounds (two choices) or stand by.

My impression is that what support told you is not relevant as this is not about verification.  I'm working with developer relations on a solution.

**Comment by allenporter** [comment]
Alert has been added.
