### ISSUE TITLE
deprecated authentication

### ISSUE THREAD

**Issue by dustin555** [home-assistant/home-assistant.github.io#22149]
### Feedback

This is a fantastically-written tutorial, thank you for taking the time to create it!

Unfortunately,[ as you've pointed out here](https://github.com/home-assistant/core/issues/67662) the authentication method used here is deprecated (redirect_uri: urn:ietf:wg:oauth:2.0:oob) so it looks like this will need to be resolved in a future HA release. 

Until then, this method does not work outside of "Testing" mode which requires weekly re-authentication and is no bueno.
**I think an alert at the top of the article stating this should be added, at least temporarily.** Would've saved me five bucks! ;-) 

Thanks again for all the hard work you put into the project.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.3.7

**Comment by allenporter** [comment]
Agreed it would be nice to update. I'm currently prioritizing putting effort into working on a resolution but would *love* contributions to improve the docs! Duping with issue #22141
