### ISSUE TITLE
Table of supported sensors per interver model

### ISSUE THREAD

**Issue by nathanhaigh** [home-assistant/home-assistant.github.io#22146]
### Feedback

It would be good to provide a table of sensors each inverter model supports (columns as sensors, rows as models/families). Typically most will only have access to a single inverter model, knowing ET/EH families are best supported only helps to make those this ET/EH family inverters all warm-and-fuzzy! :)

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2022.3.7

**Comment by frenck** [comment]
Home Assistant will automatically pick up data that is available/provided by the inverter. This is not really Home Assistant documentation/responsibility IMHO.
