### ISSUE TITLE
Scripts page does not tell you how to add a script

### ISSUE THREAD

**Issue by purdah** [home-assistant/home-assistant.github.io#22154]
### Feedback

I was looking into other documentation and it said I need to add a script.

As a beginner I was not sure how to add a script and google took me to this page: https://www.home-assistant.io/integrations/script/

So this page tells you the syntax but lacks information on HOW to add a script. Note that as a beginner I am relying on other developers scripts and not creating my own, so the syntax is much less useful to me as I have to trust the supplied scripts.

The first paragraph mentions that there is a script 'integration' so I went to the integrations page and searched for scripts but no results.

googling 'how to add a script to home assistant' mostly sent me to the above link.

The next hint were a few videos and other out of date links that state that in my home assistant->configuration I could find a 'scripts' section, but no such option exists in 2022.3.5 (my version)

Searching on that page for the text 'script' has a hit in the blueprints page, but there is no scripts tab on that page either.

The second find on the configuration page led me to automations where I did find the scripts tab.

Please update your documentation page to tell you where the CURRENT place to add a script is, and keep it up to date if the page is moved in a future release.

### URL

https://www.home-assistant.io/integrations/script/

### Version

2022.3.7

**Comment by purdah** [comment]
FYI, I am trying to integrate the broadlink rm4 pro into home assistant: https://www.home-assistant.io/integrations/broadlink/

To learn new commands I am trying to run the 'script' as suggested on that page, but the above mentioned scripts page will not allow me to create a script with the yaml from the broadlink page.

So I am guessing that there is yet another scripts tab somewhere that I am still to find.

**Comment by frenck** [comment]
I have no experience on broadlink, so cannot help you there.

I do agree the scripts needs a hint on where to find them; so let's make that happen.
Although, they are not as hidden as it seems IMHO :)

![CleanShot 2022-03-26 at 12 32 21](https://user-images.githubusercontent.com/195327/160237549-428c3a2d-0c95-4106-b766-d544bd670c76.png)

![2022-03-26 12 34 32](https://user-images.githubusercontent.com/195327/160237577-dffc9aff-7838-49cf-8da2-ac96e7b1c226.gif)

**Comment by purdah** [comment]
Thanks frenck for the quick reply, and on a weekend, much appreciated.

I had not noticed the search function in the configuration section, so thanks for pointing that out.

This request was mostly to address that the documentation is lacking in how to get from the things that a new user will find in one part of the documentation, in my case 'add a script', to the place that I need to go to in order to achieve that.

After a lot of help from other forums I have found that the Broadlink page is referring to an older method of editing the config yaml file directly.

So the out of date docco on the broadlink page is not helping a new user, although in your honest opinion (presumably as a user who has lived through the changes as they happened) it is obvious.

But specifically there is not enough information on the scripts documentation page to get a new user to the correct section in the configuration, that is what I would hope someone could change to help the next new user who finds the scripts page and can not get to the correct place.
