### ISSUE TITLE
Ecobee window and door sensors

### ISSUE THREAD

**Issue by bcjmk** [home-assistant/home-assistant.github.io#22153]
### Feedback

Is there a way to discover the window and door sensors connected to the Ecobee 4? I switch out the builder grade non-smart sensors with Ecobee, but don't see the open/close or motion being activated. These would be a fantastic update, especially if I can create triggers to turn off the A/C when the doors are open for >5 minutes or something.

### URL

https://www.home-assistant.io/integrations/ecobee/

### Version

2022.3.7

**Comment by bcjmk** [comment]
@marthoc - found the door sensors in the DEVICES object however they do NOT show up as a Remote Sensor object. Each one has 3 sensors in the object: 1) temperature (usage indoor), 2) occupancy (usage monitor) and 3) dryContact (usage monitor).
In the ALERT object, unfortunately you can't create custom alerts.
I think Ecobee is hiding access to these sensors behind a different API. Think I might need to look into other solutions.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
