### ISSUE TITLE
No mention of script.turn_off

### ISSUE THREAD

**Issue by jgclark** [home-assistant/home-assistant.github.io#22151]
### Feedback

As far as I can tell, there's no mention of script.turn_off on this page. I only discovered it exists by asking on Discord and Tinkerer knew about it.
On a related note, is there a way to do script.pause?

### URL

https://www.home-assistant.io/docs/scripts/

### Version

2022.3.7

**Comment by frenck** [comment]
> On a related note, is there a way to do script.pause?

Not from outside the script. Inside the script, you can use delays to pause a script momentarily. Or use a `wait_for_trigger` to await an external signal until the script continues.

**Comment by frenck** [comment]
We have now added and documented: `stop`.

<https://www.home-assistant.io/docs/scripts/#stopping-a-script-sequence>

Which is a more universal way to stop a sequence (in both automations and scripts).
