### ISSUE TITLE
Analytics documentation page rocks

### ISSUE THREAD

**Issue by astenger** [home-assistant/home-assistant.github.io#22152]
### Feedback

Just wanted to say think you for providing clear and concise documentation around what analytics you collect and how you use them. Reading the article convinced me to turn on all the analytics on my installation.

To whoever wrote the page: Thank you! It made a difference.

Oh, and storing the link to my install in my browser so documentation pages can link back into my installation is pure genius.

### URL

https://www.home-assistant.io/integrations/analytics/

### Version

2022.3.7

**Comment by frenck** [comment]
Thank you for the positive feedback @astenger ❤️ 

Always good to hear. The message has been passed to the original creator of the content to make sure he is aware of it 👍 

And as for you, turning on analytics: Thank you 🥇 

../Frenck
