### ISSUE TITLE
Issur Melacha Boolean Value

### ISSUE THREAD

**Issue by aniceberg** [home-assistant/home-assistant.github.io#22169]
### Feedback

Per the [jewish_calendar integrations page](https://www.home-assistant.io/integrations/jewish_calendar/), the binary sensor **issur_melacha_in_effect** "The value is true when it is currently Shabbat or Yom Tov and false otherwise." 

When I check the state it uses values of "on" or "off" - is Home Assistant agnostic to whether I use either "on" for "true" and "off" for "false", or do I need to be specific with using "on" and "off". If so, perhaps this page can clarify the states to use.

### URL

https://www.home-assistant.io/integrations/jewish_calendar/

### Version

2022.3.7

**Comment by tsvi** [comment]
Thanks for pointing it out. You're right. I submitted a pull request to fix the docs as HA expects on/off.
