### ISSUE TITLE
code panel

### ISSUE THREAD

**Issue by tekstein** [home-assistant/home-assistant.github.io#22166]
### Feedback

Hello,

Great work on integrating total connect with HA. It would be awesome if you had the option of putting a code panel with this. Is there a way? 

Thanks 
Matt 

### URL

https://www.home-assistant.io/integrations/totalconnect/

### Version

2022.3.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
