### ISSUE TITLE
Add all needed headers for other reverse proxies implementations

### ISSUE THREAD

**Issue by jmalmellones** [home-assistant/home-assistant.github.io#22181]
### Feedback

In order to add home assistant behind an SSL reverse proxy provided by my NAS vendor (Synology) i had to add specific headers that are not mentioned in your configuration page. If you only setup the required configuration in home assistant:
```
http
  use_x_forwarded_for: true
  trusted_proxies:
    - <your proxy ip>
```
 you get the "Unable to connect to Home Assistant." message after login although user and pasword are set correctly.

The headers i had to add were:

```
Upgrade $http_upgrade
Connection $connection_upgrade
X-Real-IP $remote_addr
X-Forwarded-For $proxy_add_x_forwarded_for
X-Forwarded-Proto $proxy_x_forwarded_proto
```

With these added all is working flawlessly using my * certificate installed in my reverse proxy. Maybe all headers are not needed but i tried only with websocket ones (Upgrade, Connection) and it was not working.

I think it would be super helpful for other users to have a little section listing needed headers or maybe a section specific for the Synology platform. 

Thank you.

### URL

https://www.home-assistant.io/integrations/http/

### Version

2022.3.7

**Comment by balloob** [comment]
This is already available as a community guide https://community.home-assistant.io/tags/c/community-guides/51/synology
