### ISSUE TITLE
Integration issue

### ISSUE THREAD

**Issue by robNchris** [home-assistant/home-assistant.github.io#22189]
### Feedback

Where the heck is the Add Integration button? SkyBell doesn't even show up when you search for integrations within home assistant.

### URL

https://www.home-assistant.io/integrations/skybell/

### Version

2022.3.8

**Comment by frenck** [comment]
The Skybell isn't set up via the UI.

See the instructions in the documentation on how to set it up: <https://www.home-assistant.io/integrations/skybell/#configuration>
