### ISSUE TITLE
INSTALL DEPENDENCIES

### ISSUE THREAD

**Issue by davidgrob** [home-assistant/home-assistant.github.io#22198]
### Feedback

In the section "Install Home Assistant Core" package ffmpeg is missing from Install the dependencies,  otherwise hass will fail on startup.

### URL

https://www.home-assistant.io/installation/raspberrypi/#install-dependencies

### Version

2022.3.8

**Comment by frenck** [comment]
Thanks for the feedback, this, however, depends on some factors.
Nevertheless, it is warned on the page itself.

![image](https://user-images.githubusercontent.com/195327/160863807-d86ea099-697d-43c7-83af-cb84e73711ea.png)
