### ISSUE TITLE
doesnt show up ijn energy dashboard

### ISSUE THREAD

**Issue by saqib2050i** [home-assistant/home-assistant.github.io#22209]
### Feedback

i created a sensor baseed on solar power to calcculate daily energy production in energy dashboard but semsor doest show up and i can seem ti edit deevice class and energy as well

### URL

https://www.home-assistant.io/integrations/integration/

### Version

2022.3.8

**Comment by dgomes** [comment]
This repository is for issues related to the documentation, not for general support.

Please use https://community.home-assistant.io
