### ISSUE TITLE
How to make automatisations with profile change?

### ISSUE THREAD

**Issue by pkuiBUKVgbvku** [home-assistant/home-assistant.github.io#22217]
### Feedback

First of all: Great that someone continues to develop the vallox integration!!!

Sice the last update i cannot get my 4 tiles back to work, each of which has started a different profile.

I also find no way to select another profile by an automatisation. How should it work?
I found 3 services related to vallox profiles but none of them is able to actually change the profile. And the fourth is missing at all.

since we are already communicating: would it be possible to make the cell-state changeable?
Or at least the cell-activation temperature in the profiles?

### URL

https://www.home-assistant.io/integrations/vallox/

### Version

2022.3.8

**Comment by andre-richter** [comment]
This needs to be done using the generic service `fan.set_preset_mode` now.

**Comment by pkuiBUKVgbvku** [comment]
Oh, i see. I didn't realize that this service had anything to do with vallox.

So i have to select Service-type / Service and then "Ventilator: Set preset mode (fan.set_preset_mode)"
And then i can choose at Preset mode (/New Vvalue of preset mode) between "At Home", "Away", "Boost" and "Fireplace"?
[https://www.dropbox.com/sh/pdoddw2bcft1rzd/AABwbcgwG69G_tk7IkfhG4rna?dl=0](url)
Sadly that doesnt work for me.
Any other advices?

**Comment by slovdahl** [comment]
No idea if it applies generally, but at least for me it's called `Home`, not `At Home`.

This `input_select` and these automations work fine for me at least. Using them I can switch between modes from HA. Using HA 2022.3.7 with a Vallox 110 MV.

<img width="217" alt="image" src="https://user-images.githubusercontent.com/1417619/161397886-e14bf7ef-b5f4-4920-94cf-355a799041d6.png">

<img width="624" alt="image" src="https://user-images.githubusercontent.com/1417619/161397881-06e64331-1ba3-4b17-a7f7-66af4b097885.png">

**Comment by slovdahl** [comment]
Ah, the `At Home` reference came from the docs 🤔

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1417619/161398124-ebc6c453-b251-4dba-b28a-e1496a473c46.png">

Is the `fan/set_preset_mode` reference misleading? Should it be `fan.set_preset_mode`?

**Comment by pkuiBUKVgbvku** [comment]
I got it to work properly now.
I Had to choose the Entity seperately in the GUI - had to understand the new logic of the service setup first...

For what are these 3 services used now?:
https://www.dropbox.com/s/8dgy1eoczhsh8q5/1.JPG?dl=0

Any chance of interacting with the heat-recovery-cell directly or via switching-temperature-setting?
