### ISSUE TITLE
Utility Meter documentation not updated for Home Assistant 2022.4.0b1

### ISSUE THREAD

**Issue by pimw1** [home-assistant/home-assistant.github.io#22218]
### Feedback

The new UI option for Utility Meter is not described in the documentation: https://rc.home-assistant.io/integrations/utility_meter

Things i would like to add:

1. If a sensor is added via the UI, a restart of Home Assistant is needed to activate the new sensor. This is the same as when configuring a sensor manually via configuration.yaml.

2. Generic clarification about this section: 
_Sensors created with this integration are persistent, so values are retained across restarts of Home Assistant. The first cycle for each sensor will be incomplete; a sensor tracking daily usage will start to be accurate the next day after the integration was activated. A sensor tracking monthly usage will present accurate data starting the first of the next month after being added to Home Assistant._

- _Sensors created with this integration are persistent, so values are retained across restarts of Home Assistant.
- The first cycle for each sensor will be incomplete. That is becasue it will only start tracking the values from the moment the utility sensor is configured; this moment in time is usually not exactly the beginning of a cycle. Example: if you have configured an hourly cycle for a sensor, and that sensor value increased the first half hour with 20 and the second half hour with 30, the total increase for that hour is in reality 50. However, if you activated the utility sensor exactly at the middle of the cycle, the first half our increase of 20 is not captured (i.e. no retro-active updates), but the second half hour increase of 30 will be captured. Tracking hourly usage will start to be accurate the next hour after the sensor was configured. A sensor tracking monthly usage will present accurate data starting the first of the next month after being added to Home Assistant. This principle is the same for all cycles: hourly/daily/monthly/yearly/etc._

3. Addition of a printscreen showin the new UI option and referencing to the config options.
4. Migration path. If you want to move an existing sensor from configuration.yaml to the UI configuration, take the following approach:

- Deactivate your original utiltiy sensor in config.yaml by commenting out the corresponding lines with a # sign
- Reboot home assistant
- Recreate sensors from gui with the same entity names (don't forget to replace underscores with spaces)
- Reboot home assistant again
- Population of the sensors will continue normally from the last known value, it won't start from 0.

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2022.4.0

**Comment by frenck** [comment]
> If a sensor is added via the UI, a restart of Home Assistant is needed to activate the new sensor. This is the same as when configuring a sensor manually via configuration.yaml.

If that the case, its a bug and shout be reported. Not documented as something that is correct (because it is not).

> Addition of a printscreen showin the new UI option and referencing to the config options.

We currently don't do that anywhere, as the UI is in flux a lot. We describe the options instead.

> Migration path. If you want to move an existing sensor from configuration.yaml to the UI configuration, take the following approach:

There is no migration path. As it is a helper, both YAML & UI configuration options are available.

**Comment by klaasnicolaas** [comment]
The PR is still open: https://github.com/home-assistant/home-assistant.io/pull/22180

**Comment by pimw1** [comment]
> > If a sensor is added via the UI, a restart of Home Assistant is needed to activate the new sensor. This is the same as when configuring a sensor manually via configuration.yaml.
> 
> If that the case, its a bug and shout be reported. Not documented as something that is correct (because it is not).
> 
> > Addition of a printscreen showin the new UI option and referencing to the config options.
> 
> We currently don't do that anywhere, as the UI is in flux a lot. We describe the options instead.
> 
> > Migration path. If you want to move an existing sensor from configuration.yaml to the UI configuration, take the following approach:
> 
> There is no migration path. As it is a helper, both YAML & UI configuration options are available.

It's reported here: thanks for moving it to core <https://github.com/home-assistant/core/issues/69062>

As for the " migration path": the wording might be wrong, but the though behind it stays very relevant: this part explains how someone can move their yaml config to ui config. And that is handy to know.
edit: i'll explain the reason why it is handy to know: if you have a monthly/yearly utility sensor, it is kinda super handy that it will continue from the last known value, instead of starting from 0. This method achieves exactly that.

**Comment by frenck** [comment]
> As for the " migration path": the wording might be wrong, but the though behind it stays very relevant: this part explains how someone can move their yaml config to ui config. And that is handy to know.

There is no migration path.

**Comment by pimw1** [comment]
I am either not understanding you, or you are not understanding me. Copy-pasting your previous reply will not solve this unclarity.

**Comment by frenck** [comment]
There is no unclarity. There is no migration path from YAML configuration to UI.

**Comment by emontnemery** [comment]
@frenck is right, there's no migration path; your existing already configured utility meter should still be configured in YAML.

**Comment by pimw1** [comment]
> @frenck is right, there's no migration path; your existing already configured utility meter should still be configured in YAML.

Yes, that works all fine.

> There is no unclarity. There is no migration path from YAML configuration to UI.

Let me try to explain this better.

- My goal is get all existing utlity sensors into a UI config flow. While still retaining the current cycle known value and continue summing from there 
- There  is no paved migration path to do so. You made that clear.
-  That does not invalidate my goal: i would like to get all my existing sensors into a UI flow without loosing the current-cycle value.
- The good news is, that i found a method to exactly achieve my goal
- I think that many users would like to do the same as what i did
- Because there is no migration path to achieve this, i described a way how and end-user can do this him (or her) self.
- I succesfully achieved this, so did another issue on the beta discord channel
- It would add value to share this method with the community

**Comment by pimw1** [comment]
I hope this makes it a little bit more clear. I try to do something positive for the community.

**Comment by frenck** [comment]
> My goal is get all existing utlity sensors into a UI config flow.

Cool, but again, we have no migration path.

> The good news is, that i found a method to exactly achieve my goal

That is good, but we don't support workaround in our documentation.

Again, we have no official migration path.

**Comment by pimw1** [comment]
Ok, that solves the unclarity. The point is that we don't document support for work-arounds in the documentation. That is fair.

Would it be an idea if i write an article about this on the community forums, and that we reference to this in the release notes?

**Comment by frenck** [comment]
You can write in on the community forums if you like. It won't be part of the release notes.
