### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by SomeAssembly** [home-assistant/home-assistant.github.io#22224]
### Feedback

This page indicates:
"If multiple instances of ASUSWRT are configured, choose the instance you want to configure."
Which seems outdated or incorrect. The integration will only allow one instance to be configured. 

I would be happy if there is a way to use it more than once; I would need instruction.

### URL

https://www.home-assistant.io/integrations/asuswrt/

### Version

2022.3.8

**Comment by ollo69** [comment]
You are right, this is not possible at this moment, but I create PR [#69154](https://github.com/home-assistant/core/pull/69154) to allow multiple instance, so this feature could be available again in future releases,
