### ISSUE TITLE
Unique_id on material that does not have unique_id

### ISSUE THREAD

**Issue by ChrigouTav** [home-assistant/home-assistant.github.io#22235]
### Feedback

This page should give an example of how to use unique_id token because there is no other page that explain how to set unique_id or entity_id on material that does not have unique_id.
For example my camera does not have unique_id but I cannot use it because I have no example or no way from the doc how to set it.

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2022.3.8

**Comment by frenck** [comment]
You can't set it; hence it has no documentation on how to set it.
