### ISSUE TITLE
Outdated article

### ISSUE THREAD

**Issue by TomNett** [home-assistant/home-assistant.github.io#22238]
### Feedback

Thanks for that but it's kind of an outdated article. Most things are difficult or even impossible to buy. But on the market, there are smart plug & play relays from e.g. Tuya which fit perfectly in most electrical boxes.
Tomas

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2022.3.8

**Comment by frenck** [comment]
Thanks for the feedback, however, it's not outdated :)

As for Tuya: Those are cloud products that I would not recommend.

../Frenck

**Comment by TomNett** [comment]
if you cant get items in the article then I consider it quite useless for
users. why would you not recommend it? Like Tuya TS0601 is pure Zigbee no
cloud.
Tomas
