### ISSUE TITLE
Water Heater Temperature Range

### ISSUE THREAD

**Issue by davel4wa** [home-assistant/home-assistant.github.io#22233]
### Feedback

The Rheem EcoNet integration covers a range of Rheem products including HVAC equipment, thermostats, and water heaters. It seems that the code for temperature has been made common for all of these devices. The allowable temperature range for water heaters is the same for hvac thermostats and water heaters and that is unworkable. The slider range is 0 - 100. Perhaps this is intended for centigrade settings, if so you are going to be literally freezing on one end and boiling on the other. Now, this is workable for a HVAC thermostat, although the range is,somewhat compressed. It is unworkable for water heaters even if the intended scale is centigrade as the number is not translated and the max of 100° is sent untouched to the water heater.
Interestingly enough the Alexa Rheem EcoNet skill suffers from the same anomaly. 

### URL

https://www.home-assistant.io/integrations/econet/

### Version

2022.3.8

**Comment by w1ll1am23** [comment]
@davel4wa what slider are you speaking of?

The temperature range comes from the econet API in the case of my water heater a min of 110F and a max of 140F

It could be that I'm not looking at the right set point limits for HVAC or the API could just be sending it wrong. 

If you enable debug logs for econet your logs will show what response the API is returning and maybe we can figure out a solution. 

```yaml
logger:
  logs:
    pyeconet: debug
```

**Comment by w1ll1am23** [comment]
@davel4wa just noticed this bug was reported in the home-assistant.io project. Maybe core would be okay, but honestly it should probably be addressed as an issue in the library. Can you move this issue over here. 

https://github.com/w1ll1am23/pyeconet

**Comment by davel4wa** [comment]
I ran into this while creating an automation. The normal setting is 120°F and I wanted to reduce the temperature to 118° over night. I have made this work by simply entering the value directly. The slider is attached to the 'electric water heater' device as shown in the attached screen captures. The first has the slider completely left which indicates 0 (zero) when the slider is completely right the reading is 100. The second image shows my manual entry of 118 and you can see that the underline has turned red.
My comment about the Alexa skill is not actually accurate. The older version of the skill had this same problem. The current version of the skill actually does not work at all. The only functions in this version are on/off.
I realize the Alexa skill is not in your wheelhouse but I mentioned it because there seems to be a root problem with the EcoNet API.



Sent from my Galaxy



-------- Original message --------
From: William Scanlon ***@***.***>
Date: 4/6/22 5:57 PM (GMT-08:00)
To: "home-assistant/home-assistant.io" ***@***.***>
Cc: davel4wa ***@***.***>, Mention ***@***.***>
Subject: Re: [home-assistant/home-assistant.io] Water Heater Temperature Range (Issue #22233)


@davel4wa<https://github.com/davel4wa> what slider are you speaking of?

The temperature range comes from the econet API in the case of my water heater a min of 110F and a max of 140F

It could be that I'm not looking at the right set point limits for HVAC or the API could just be sending it wrong.

If you enable debug logs for econet your logs will show what response the API is returning and maybe we can figure out a solution.

logger:
  logs:
    pyeconet: debug

**Comment by w1ll1am23** [comment]
I don't see your screenshots, but I'm able to recreate the 0-100 issue when trying to set the temperature in an automation. In the ui for the actual entity I don't have that restriction. So I do wonder if this is a UI issue.

**Comment by w1ll1am23** [comment]
I think this is the issue. 

https://github.com/home-assistant/core/blob/dev/homeassistant/components/water_heater/services.yaml

**Comment by davel4wa** [comment]
Yes, that is pretty plain to see. Odd that those values were selected. It doesn't even make sense for an HVAC system. Perhaps they were intended to be place holders only.
Thanks for your help on this. I must imagine that other people are confronting this as well.



Sent from my Galaxy



-------- Original message --------
From: William Scanlon ***@***.***>
Date: 4/6/22 8:31 PM (GMT-08:00)
To: "home-assistant/home-assistant.io" ***@***.***>
Cc: davel4wa ***@***.***>, Mention ***@***.***>
Subject: Re: [home-assistant/home-assistant.io] Water Heater Temperature Range (Issue #22233)


I think this is the issue.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/water_heater/services.yaml

**Comment by davel4wa** [comment]
This is apparently by design, wrong but by design.
