### ISSUE TITLE
integration stopped working

### ISSUE THREAD

**Issue by Chrisvdw00** [home-assistant/home-assistant.github.io#22243]
### Feedback

Integration says 'unknown error occurred' 

### URL

https://www.home-assistant.io/integrations/rdw/

### Version

2022.3.8

### Additional information

it worked a week ago, really don't know what happened

**Comment by frenck** [comment]
Hi there @Chrisvdw00 👋 

It seems like you want to report an issue with integration, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to fix issues.

Please report issues here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
