### ISSUE TITLE
How to synchronize multiple media players in a group?

### ISSUE THREAD

**Issue by 404ClickBait** [home-assistant/home-assistant.github.io#22245]
### Feedback

Good audio streaming platforms have a mechanism for either automatically synchronizing multiple players or manually synchronizing (adding milliseconds delays to account for different delays through different systems).  Is that possible to do for various media players in a group or does it turn out that if a group is out of sync it will just always be out of sync?

### URL

https://www.home-assistant.io/integrations/media_player.group/

### Version

2022.3.8

### Additional information

Even if it's not possible, it seems worth mentioning on this documentation page because it's such a critical aspect of multi-casting media.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by 404ClickBait** [comment]
Hello,

This was not intended to be a request for support.  This was intended to be feedback on the doc as solicited at “URL”.  Sorry, my wording may have been confusing since the feedback is posed like a question.  Please see “Additional information” for perhaps clearer description of the feedback.

Many thanks,
Kyle

**Comment by frenck** [comment]
We don't document what things can't do... That would become endless lists of things people can think of. The answer here is: It can't do that.

Please use the community for such questions. If information is missing about capabilities it can do; please let us know.

../Frenck
