### ISSUE TITLE
Useless entry

### ISSUE THREAD

**Issue by Danifont** [home-assistant/home-assistant.github.io#22248]
### Feedback

Useless ... we need information of the yaml files, structure of the needed input, etc ... This is only a way to sell his product.

### URL

https://www.home-assistant.io/docs/energy/gas/

### Version

2022.3.8

**Comment by klaasnicolaas** [comment]
You are free to create a pull request to add more information 😉 Further information will depend on which integration you use to get your gas data into Home Assistant.
