### ISSUE TITLE
Radio documentation - please help more

### ISSUE THREAD

**Issue by rgrfr** [home-assistant/home-assistant.github.io#22242]
### Feedback

Please give a clue as to what happens / what to do to hear radio

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2022.3.8

**Comment by frenck** [comment]
I'm not sure what to add to this?

![image](https://user-images.githubusercontent.com/195327/161577438-b4a6a339-1fe1-4cf5-adf2-f79263753f56.png)

Could you please explain what you are looking for?

../Frenck

**Comment by rgrfr** [comment]
Thank you Frenck. This link helps to show how people feel something was missing (https://community.home-assistant.io/t/radio-browser-how-to-use/398397). I suggest:

'Be sure to add 'media' or 'media panel' to your configuration'
'Create an automation or script in the UI with the action 'Play Media' then choose a media player, then browse for a radio station....

**Comment by frenck** [comment]
> 'Be sure to add 'media' or 'media panel' to your configuration'

That is not needed, as that is the default configuration. If you removed the default configuration that is your own choice and/or problem. You actively removed parts.

> 'Create an automation or script in the UI with the action 'Play Media' then choose a media player, then browse for a radio station....

This is not a tutorial on how to create automations or how to use the play media actions.

This is the documentation on how to set up the radio browser integration.

**Comment by rgrfr** [comment]
No! One should state any dependencies. 
eg camera integration mentions 'stream'  
eg on various integrations we see "This integration is by default enabled, unless you’ve disabled or removed the default_config: line from your configuration. If that is the case, the following example shows you how to enable this integration manually ... 
eg alternatively as you prefer "If you removed the default configuration that is your problem".

**Comment by frenck** [comment]
It is documented, in the integration that does media: <https://www.home-assistant.io/integrations/media_source#configuration>
