### ISSUE TITLE
Multiple instances indicated to be possible but not supported.

### ISSUE THREAD

**Issue by Nuffe71** [home-assistant/home-assistant.github.io#22249]
### Feedback

The documentation says: "If multiple instances of ASUSWRT are configured, choose the instance you want to configure."
I have never been able to add multiple instances. Every time I try, I receive: Already configured. Only a single configuration possible.

I have been trying this with multiple home assistant versions, the latest one with 2022.3.8 (Core/Container version)

### URL

https://www.home-assistant.io/integrations/asuswrt/

### Version

2022.3.8

**Comment by ollo69** [comment]
Duplicate of #22224

**Comment by frenck** [comment]
closing as duplicate
