### ISSUE TITLE
NGINX and scenegen missing in topics

### ISSUE THREAD

**Issue by danielperna84** [home-assistant/home-assistant.github.io#2224]
When you go to the [Ecosystem](https://home-assistant.io/docs/ecosystem/) site, there are a ton of topics on the right side. Far at the bottom there are the ones for the ecosystem. Looking at the repo, there are markdown-files for NGINX and scenegen. These are however not present in the topic-list. Not knowing much about the internals of all this I assume, it's because those two don't have their own subfolder with further details about the documentation. Directly navigating to the sites (https://home-assistant.io/docs/ecosystem/nginx/, https://home-assistant.io/docs/ecosystem/scenegen/) is working. So I assume this is a bug.

Edit: Synology is missing as well.

Edit: After searching through this I found where this is done: https://github.com/home-assistant/home-assistant.github.io/blob/next/source/_includes/asides/docs_navigation.html
Thought there was some scripting that adds links automatically. But since it's hardcoded I might as well fix it myself.

**Comment by fabaff** [comment]
I missed them when I created the menu.
