### ISSUE TITLE
Service data attribute "source"

### ISSUE THREAD

**Issue by 404ClickBait** [home-assistant/home-assistant.github.io#22251]
### Feedback

In the section _Service media_player.select_source_, for the _Service data attribute_ 'source', there is no indication of what the parameter refers to other "name of the source to switch to" .  There ought to be a description or at a bare minimum some examples of valid values that could be applied to this attribute. All valid options ought to be described.  It says it's platform dependent so it should probably say something about which platforms are supported. It might also be extremely helpful to provide links to relevant doc for supported platforms.  Or if this boils down to an RS232 command that gets sent to an AV receiver, the RS232 interface should either be described or linked to somewhere that describes it.

### URL

https://www.home-assistant.io/integrations/media_player/

### Version

2022.3.8

**Comment by frenck** [comment]
The media player platform provides a base other integration can use.

They are listed here: <https://www.home-assistant.io/integrations/#media-player>

> here is no indication of what the parameter refers to other "name of the source to switch to" . There ought to be a description or at a bare minimum some examples of valid values that could be applied to this attribute.

A source can mean different things, depending on the integration providing the media player platform. For some AV receiver integrations, it can be HDMI ports or audio ports, for Spotify it are Spotify Connect targets, and for some TV it are channels or even Apps. Please consult the documentation of the integration that you are interested in for more information.

From the media player page itself, there is nothing more to document.

../Frenck
