### ISSUE TITLE
See exported to grid in home assistant 

### ISSUE THREAD

**Issue by djsmiddy** [home-assistant/home-assistant.github.io#22256]
### Feedback

HI Is there a way to see the "export to grid" data in home assistant? I cant see that as an entity,  can it be added?

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2022.3.8

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by muppet3000** [comment]
@frenck - This has the potential to be a bug actually as we already support "export to grid" for this plugin.

@djsmiddy - Can you confirm what type of Growatt system you have? Go to the growatt server web page and look at this part:
![image](https://user-images.githubusercontent.com/10612068/162018410-7a48d614-c81d-4667-b0ef-f5cc2aef6129.png)

Can you please tell me what type of system yours is? Then I'll determine whether this is a feature request or a bug.

**Comment by djsmiddy** [comment]
@muppet3000 Thanks for the reply, here is the device type 

is says MIN/MIC/MOD

![image](https://user-images.githubusercontent.com/48715839/162080300-e7d8653a-e489-414d-954d-bc9673712030.png)
