### ISSUE TITLE
Temperature sensor missing

### ISSUE THREAD

**Issue by xwsjfx** [home-assistant/home-assistant.github.io#22255]
### Feedback

I would like to add only the current temperature value on my floorplan. I can see it in the device view but cannot reference it. Please integrate this as a sensor. Thank you.
![AC](https://user-images.githubusercontent.com/97837915/161849694-5ed07725-a0c2-4874-8f45-ad8d8dad3459.jpg)

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2022.3.8

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by xwsjfx** [comment]
Hello @frenck  thanks, i did that feature request, but no response. How can i see that it was taken into consideration?
