### ISSUE TITLE
code: 400 - Device Not Found

### ISSUE THREAD

**Issue by GerbenKwakkel** [home-assistant/home-assistant.github.io#22262]
### Feedback

I have added the Lyric integration and followed the documentation: https://www.home-assistant.io/integrations/lyric.

In my HA installaltion, the thermostat isn't working en getting the following error:

{'request': {'method': 'POST', 'url': 'https://api.honeywell.com/v2/devices/thermostats/LCC-XXX?apikey=XXX&locationId=3002101', 'headers': {'Authorization': 'Bearer XXX', 'Content-Type': 'application/json'}, 'json': {'mode': 'Off', 'heatSetpoint': 18, 'coolSetpoint': 10, 'thermostatSetpointStatus': 'TemporaryHold'}}, 'response': {'code': 400, 'message': 'Device Not Found'}, 'status': 400}

### URL

https://www.home-assistant.io/integrations/lyric/

### Version

2022.3.8

**Comment by frenck** [comment]
Hi there @GerbenKwakkel 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
