### ISSUE TITLE
Sensibo PURE is not visible in HA

### ISSUE THREAD

**Issue by scavengerCZ** [home-assistant/home-assistant.github.io#22264]
### Feedback

I have 3 Sensibo devices at home.
They are 2 SKY (air condition controllers) and 1 year old PURE air purifier.

Both SKY controllers are integrated in my Home Assistant system, but PURE is not, or was there, but its control did not work. 
Sensibo PURE has the same API as Sensibo SKY

### URL

https://www.home-assistant.io/integrations/sensibo/

### Version

2022.3.8

**Comment by gjohansson-ST** [comment]
This is already solved in 2022.4 released today

**Comment by scavengerCZ** [comment]
Hi, great, it's already working, I'll try it out.
Thank you
