### ISSUE TITLE
Samsung tv having more than two sources

### ISSUE THREAD

**Issue by monxas** [home-assistant/home-assistant.github.io#22261]
### Feedback

As per the documentation, the integration can only switch between TV and HDMI source. My Samsung smart tv has a hub with up to four HDMI (HDMI1, HDMI2…) is there a way to access those?

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2022.4.0

**Comment by chemelli74** [comment]
Hi @monxas , this repo is used for tracking issues with the documentation.
Feature requests should be created on our community site: https://community.home-assistant.io/c/feature-requests/

Simone
