### ISSUE TITLE
Onboarding graphics are out of date

### ISSUE THREAD

**Issue by kjnelan** [home-assistant/home-assistant.github.io#22266]
### Feedback

In going through a fresh install (this is my first time working with HA), I noticed many of the pictures (graphics) do not match up with the current release.  For instance, "Supervisor" was moved yet in the graphics it is still there.  Many of the pointers have also moved, so finding things from the instructions has been hunt and peck.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2022.4.0

**Comment by dannytsang** [comment]
I thought I got all of them in #21383 but looks like I missed one. Thanks for spotting and raising this @kjnelan I will see if I can get something together soon.
