### ISSUE TITLE
Threshold helper template value

### ISSUE THREAD

**Issue by BloodyusHellus** [home-assistant/home-assistant.github.io#22276]
### Feedback

Wouldn't it be awesome if you could provide a template value (or value from another helper, such as an input number) as upper/lower limit for threshold helper?

### URL

https://www.home-assistant.io/integrations/threshold/

### Version

2022.4.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
