### ISSUE TITLE
DHTSensors

### ISSUE THREAD

**Issue by manospa** [home-assistant/home-assistant.github.io#22279]
### Feedback

That Update ruined my installation 😢. Please try to add it again. I believe that its a really good feature for installing new staff using gpio, btw thanks for the great job you do

### URL

https://www.home-assistant.io/more-info/removed-integration/

### Version

2022.4.0

**Comment by frenck** [comment]
This feature has been deprecated for 2 release cycles and removed under architecture decision 0019.

<https://github.com/home-assistant/architecture/blob/master/adr/0019-GPIO.md>

../Frenck
