### ISSUE TITLE
doesn't comply with Google's OAuth 2.0 policy

### ISSUE THREAD

**Issue by NotVic** [home-assistant/home-assistant.github.io#22289]
### Feedback

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.4.0

**Comment by allenporter** [comment]
Thank you for the report
Duplicate #22141
