### ISSUE TITLE
pi glow module causing HA to not start in VENV

### ISSUE THREAD

**Issue by slacking42** [home-assistant/home-assistant.github.io#2229]
I have enabled piglow as per the wiki 

```
light:
  platform: piglow
```

upon restart I get the error 

> 17-03-02 21:02:31 INFO (MainThread) [homeassistant.core] Bus:Handling 
17-03-02 21:02:31 INFO (MainThread) [homeassistant.loader] Loaded light.piglow from homeassistant.components.light.piglow
17-03-02 21:02:32 INFO (MainThread) [homeassistant.bootstrap] Setting up light
17-03-02 21:02:32 INFO (MainThread) [homeassistant.components.light] Setting up light.piglow
This library requires python3-smbus
Install with: sudo apt-get install python3-smbus

The OS has the package installed 

>pi@pi:~ $ sudo apt-get install python3-smbus
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-smbus is already the newest version.

and also the VENV has it installed 

>(homeassistant) homeassistant@pi:/home/pi/scripts/ha$ sudo apt-get install python3-smbus
[sudo] password for homeassistant:
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-smbus is already the newest version.

To add piglow works fine called from python3 on the OS

any insight into what the resolution for this is?

**Comment by Landrash** [comment]
@slacking42 This shouldn't be in the documentation repo. Post it in under [issues](https://github.com/home-assistant/home-assistant/issues/) for the home-assistant repo.

Tested it on a fresh hassbian instance and it does not work as you describe.

**Comment by slacking42** [comment]
sorry! will retest with new version and repost if needed
