### ISSUE TITLE
Google Assistant Tutorial - Requires an overhaul

### ISSUE THREAD

**Issue by kittywitch** [home-assistant/home-assistant.github.io#22295]
### Feedback

In reference to my comment on a PR in this repository submitting changes to the Google Assistant tutorial to reflect changes to Google Actions Console requirements: https://github.com/home-assistant/home-assistant.io/pull/22293#issuecomment-1092290475, this issue is a complete duplicate of that comment.

It would be worthwhile to completely redo the tutorial now, considering Google Actions Console has been different from what is shown and stipulated for over a year now. Not to mention poor advice within the tutorial, including hitting "Add Scope" twice, when there is already a default empty field, so you end up with an extra empty field (which, admittedly is removed upon save).

The structure of the tutorial in general is also poor. Talking about the configuration JSON steps but not mentioning that requires the creation of the Service Account Token Creator to begin with, while that stuff is in a completely different section.

The whole matter of steps 2.3 and 2.4 are now completely obsolete:
```
If asked, leave options as they default No, I only want to allow account creation on my website and select Next.
Then if asked, for the Linking type select OAuth and Authorization Code. Click Next
```

Whereas the requirement for doing a new integration involving the Deploy->Directory information likely ultimately replaces said steps, somewhat.

Admittedly, this would require taking new screenshots, which would likely be cumbersome for the poor soul who decides to go about redoing said tutorial.

Dare I say, it would also be worth it to include mobile screenshots involving the initial linking process and the login page, for more transparency of what it looks like when done correctly, and done incorrectly (such as without providing the Deploy->Directory information).

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2022.4.0

**Comment by kittywitch** [comment]
Admittedly, I would do this myself, but I have work tomorrow and it's late. I may do this myself and I hope this issue acts as a reminder for future me after work. :p

**Comment by Omnipius** [comment]
I posed some instructions on the Deploy -> Directory information part on the forum. [See here](https://community.home-assistant.io/t/can-no-longer-link-google-assistant/409495/19?u=omnipius) Feel free to copy some of my verbage or let me know if you'd like some help with this.
