### ISSUE TITLE
Lack of configuration instructions

### ISSUE THREAD

**Issue by ctankep23** [home-assistant/home-assistant.github.io#22292]
### Feedback

I would like to try this integration but there are no guides or steps or hints as to how to setup the configuration.

### URL

https://www.home-assistant.io/integrations/asuswrt/

### Version

2022.4.0

**Comment by ollo69** [comment]
What do you mean? 
Just follow config flow, and instruction are at the link https://www.home-assistant.io/integrations/asuswrt/

**Comment by gmariotti** [comment]
Hey @ctankep23, do you refer to how to set up SSH to connect to the router? I just had to go through that and figure out how to do it, if @ollo69 is fine with it, I could open a PR with a short guide about it

**Comment by ollo69** [comment]
You don't have to ask my permission to open PR, and I will not be the one than will eventually approve the merge. But I 'm not sure that a PR related to instructions how configure the router will be approved. Looks more like information to share in a forum thread.

**Comment by klaasnicolaas** [comment]
Clear instructions I think? 🤷🏻‍♂️ This kind of setup flow applies to most integrations.

![image](https://user-images.githubusercontent.com/20448157/164529157-719ac719-5c89-485d-aba9-665b89676049.png)

**Comment by gmariotti** [comment]
In my case, the tricky part was figuring out the ssh setup. For some reason, the integration didn't like the keys in `/root/.ssh` but was fine when I created them again in `/config/ssh` (quite sure the issue was permissions related)

**Comment by shampto3** [comment]
I'm new to home assistant, so I may just be lost but the configuration document does seem fairly unhelpful. The form the integration pulls up when you add the integration in Home Assistant is the same regardless of whether you're using SSH or Telnet, but those normally require different fields. I'm trying to SSH, but I don't know how to configure my port or SSH key passphrase. Am I supposed to be adding these things to the `configuration.yml` file instead? It's not even clear to me how this integration knows which SSH file to use.

Ultimately I had to enable `Allow Password Login` in my router system settings in order for the ASUSWRT integration to authenticate, which makes the connection less secure.
