### ISSUE TITLE
Prerequisites small edit: reboot HA after saving the configuration.yaml

### ISSUE THREAD

**Issue by rwzdoorn** [home-assistant/home-assistant.github.io#22298]
### Feedback

After applying the CLIENT_ID and CLIENT_SECRET to the configuration.yaml you are required to reboot Home Assistant. If you don't do this, the integration will fail.

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2022.4.0

**Comment by frenck** [comment]
This has been moved to the UI and thus restarting is no longer needed 🎉
