### ISSUE TITLE
Firmware version

### ISSUE THREAD

**Issue by remcomeer89** [home-assistant/home-assistant.github.io#22290]
### Feedback

Used the new update function in homeassistant to update the 13 wled devices that had updates, 6 of them lost functions after the update. The Wled Ethernet boards no longer connected, and the Wled Audio reactive now have firmware without the mic function.
Is there a way to check if the update that is going to be written is the correct version?

### URL

https://www.home-assistant.io/integrations/update/

### Version

2022.4.0

**Comment by frenck** [comment]
Hi there @remcomeer89 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integration here: <https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
