### ISSUE TITLE
Airzone with aidoo

### ISSUE THREAD

**Issue by alrodgir** [home-assistant/home-assistant.github.io#22302]
### Feedback

The aidoo integrations haven't cloud platform, it's all onpremise. Use the Airzone system, but not the cloud one.
Can I connnect my airzone with aidoo in HA??? I'm trying to use it but I get 'Unknown error occurred' 😥

### URL

https://www.home-assistant.io/integrations/airzone/

### Version

2022.4.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
