### ISSUE TITLE
Not working with SolarLog 50

### ISSUE THREAD

**Issue by janbernhardt** [home-assistant/home-assistant.github.io#22305]
### Feedback

The JSON Endpoint that is called is not providing any useful data in the response:

    {"801":{"170":{"100":"ACCESS DENIED","101":"ACCESS DENIED","102":"ACCESS DENIED","103":"ACCESS DENIED","104":"ACCESS
    DENIED","105":"ACCESS DENIED","106":"ACCESS DENIED","107":"ACCESS DENIED","108":"ACCESS DENIED","109":"ACCESS
    DENIED","110":"ACCESS DENIED","111":"ACCESS DENIED","112":"ACCESS DENIED","113":"ACCESS DENIED","114":"ACCESS
    DENIED","115":"ACCESS DENIED","116":"ACCESS DENIED"}}}

As far as I can see there is no option to resolve this problem, as SL50 simply does not support it.

### URL

https://www.home-assistant.io/integrations/solarlog/

### Version

2022.4.1

**Comment by janbernhardt** [comment]
I think it would be good to mention this on the webpage to help people avoid spending hours to try to get it working

**Comment by frenck** [comment]
Hi there @janbernhardt 👋 

Feel free to suggest/edit the page! 👍 

../Frenck

**Comment by frenck** [comment]
Oops, sorry did not mean to close it. Clicked the wrong button. Re-opened again.
