### ISSUE TITLE
Please show how to use in an automation

### ISSUE THREAD

**Issue by mclever** [home-assistant/home-assistant.github.io#22309]
### Feedback

Please show an example of how to use with an automation

### URL

https://www.home-assistant.io/integrations/season/

### Version

2022.4.1

**Comment by frenck** [comment]
Its a sensor? So, it can be used in an automation just like any other sensor.
Is there something special you'd like to see that is out of the ordinary for this integration?

Maybe you can extend your documentation suggestion to provide a suggestion on what you'd like to see or think is missing.

../Frenck
