### ISSUE TITLE
HomeAssistant core run failed due to changes in Jinja

### ISSUE THREAD

**Issue by romanesko** [home-assistant/home-assistant.github.io#22301]
### Feedback

installation according to these instruction:
https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core

On run fails with
`ImportError: cannot import name 'contextfilter' from 'jinja2'`

I checked the Jinja's [documentation](https://jinja.palletsprojects.com/en/3.0.x/api/?highlight=contextfilter#jinja2.evalcontextfilter), it says:

> Deprecated since version 3.0: Will be removed in Jinja 3.1. Use pass_eval_context() instead.

After downgrading Jinja2 to 3.0.0 — everything works fine.
Probably you need to fix the version of Jinja to 3.0.0 in the requirements

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.4.0

**Comment by frenck** [comment]
The version looks correct, we are on the latest Jinja. All Home Assistant instances running Home Assistant 2022.4 use it (which is around 19.4% of the install base according to our analytics at the time of writing).

I cannot find any reference to the use of the `contextfilter` in Home Assistant either:

![image](https://user-images.githubusercontent.com/195327/162461417-06dfea48-852d-484b-91ac-d7a2cdf45b7f.png)

**Comment by frenck** [comment]
Could you provide a more extensive stack trace?

**Comment by romanesko** [comment]
I guess that's a problem.

RPI has Python 3.7 and it gets version 2021.1.5:

https://files.pythonhosted.org/packages/77/1f/9e7281a167292bfec9f46827d031260440f9969337b51fae299648ef3291/homeassistant-2021.1.5-py3-none-any.whl

**Comment by romanesko** [comment]
I confirm that updating python to version 3.9 allowed Home Assistant 2022.4.1 to be installed

**Comment by romanesko** [comment]
BTW It still doesn't work on RPI without libffi7.so
here is workaround: https://community.home-assistant.io/t/python-install-on-raspberry-pi-os/241558/12
maybe it should be added to documentation

**Comment by frenck** [comment]
<img width="723" alt="CleanShot 2022-04-08 at 21 26 14@2x" src="https://user-images.githubusercontent.com/195327/162510869-57a2a232-3a65-4509-ae97-d66732365c65.png">

:) That note is there for a reason. Our documentation is based on Debian, not Raspberry Pi OS.
