### ISSUE TITLE
Home connect integration

### ISSUE THREAD

**Issue by johngreezly** [home-assistant/home-assistant.github.io#22315]
### Feedback

The documentation says to put client_ID and client_secret in configuration file, whilst Home Connect developper portal provides only a client_id key after registration of the app (link : https://developer.home-connect.com/applications).

Could it be that client ID = Account ID and client Secret is Client ID ?

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2022.4.1

**Comment by DavidMStraub** [comment]
> Home Connect developper portal provides only a client_id

That's not true.

<img width="192" alt="image" src="https://user-images.githubusercontent.com/10965193/162562085-11556775-992f-4f96-8c6f-a833a79eb84b.png">
