### ISSUE TITLE
Explain the circles

### ISSUE THREAD

**Issue by richardjlyon** [home-assistant/home-assistant.github.io#22316]
### Feedback

On the map, circles appear with capital letters inside them. These are not explained. What are they? There is one on my device near my home that says "RPG". What is this? Rocket Propelled Grenade? A neighbour who uses your application (security concern).

### URL

https://www.home-assistant.io/dashboards/map/

### Version

2022.4.1

**Comment by klaasnicolaas** [comment]
Have you tried clicking on it to see what device_tracker entity it is?

**Comment by dannytsang** [comment]
I believe it's the initials or acronym of your location name.

I would also throw in Role Playing Game (RPG) 😉

**Comment by frenck** [comment]
Going to close this feedback, as it is listed on the first line of the page; directly above the image (entities).
