### ISSUE TITLE
MQTT Publish service

### ISSUE THREAD

**Issue by DanielPersoonlijk** [home-assistant/home-assistant.github.io#22310]
### Feedback

Missing clear examples.

### URL

https://www.home-assistant.io/docs/mqtt/service/

### Version

2022.4.1

**Comment by frenck** [comment]
I've looked at the page, each service is described with all possible parameters and a couple of examples are shown. Could you maybe explain what is unclear about them? And add an example of what you suggest should be added?

Thanks!

../Frenck

**Comment by DanielPersoonlijk** [comment]
I was looking for an example explaining this:

platform: time_pattern
seconds: /10
service: mqtt.publish
data:
  topic: room/sensor1
  payload: '"{{ states(''sensor.temperature'') }}"'

Maybe it could be useful for more people.

Kind regards,

Daniel

Op vr 8 apr. 2022 om 21:19 schreef Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
I'm not sure what that code snippet you provided is or does? It looks like a mix between an automation trigger and a service call; but not a format or syntax that is accepted in Home Assistant.

Could you maybe try to describe it in word otherwise?

**Comment by DanielPersoonlijk** [comment]
Hello Franck,

What I am doing is sending data of a BLE temperature sensor between two HA
instances with MQTT.
[image: image.png]
Please see photo for reference.

Kind regards,

Daniël







Op vr 8 apr. 2022 om 22:04 schreef Franck Nijhof ***@***.***>:

**Comment by frenck** [comment]
@DanielPersoonlijk Please don't use email to respond on GitHub. Browse to your response on GitHub and see it looks weird and is missing images.
