### ISSUE TITLE
Time issues with triggers

### ISSUE THREAD

**Issue by hlvdzande** [home-assistant/home-assistant.github.io#22317]
### Feedback

Just started converting my current Homey environment to Home Assisstant. But got stuck in the automations part.
Automations are called flows in Homey and easy to define. 
I Started with the simple "time" related automations.
[Set lightX to on at 17:15]. This won't work in my HA. Somehow there is a 2 hour time difference. The automation will fire too late at 7:15 pm (???) 
The same with the sunset trigger, it will fire too late or not at all.

### URL

https://www.home-assistant.io/docs/automation/

### Version

2022.4.1

### Additional information

The server seems to run in the correct time!  my 17:05 is 5.05 pm on the server.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
