### ISSUE TITLE
Additional Rachio Data as Sensors

### ISSUE THREAD

**Issue by chicagoandy** [home-assistant/home-assistant.github.io#22329]
### Feedback

It'd be awesome to pull Rachio data elements like zone-specific Soil Moisture into a sensor.   Then we could build reporting dashboards showing lawn health.

### URL

https://www.home-assistant.io/integrations/rachio/

### Version

2022.4.1

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by chicagoandy** [comment]
Then you may want to update the documentation.  https://www.home-assistant.io/integrations/rachio/    suggests this page as a place for feedback.
