### ISSUE TITLE
Switch as X

### ISSUE THREAD

**Issue by thehounddog** [home-assistant/home-assistant.github.io#22324]
### Feedback

The naming of this functionality was discussed in the home assistant 2022.4 release party.

"Switch as X" is maybe not very descriptive for less technical people (who the UI is aiming at).

What about "Switch Mapper" ?

### URL

https://www.home-assistant.io/integrations/switch_as_x/

### Version

2022.4.1

**Comment by frenck** [comment]
> who the UI is aiming at

The integration itself is rarely exposed, the  UI shows: "Show as" as a selector on the switch. Whatever we call things;  doesn't have to be represented that way in the UI (hence its lesser of an issue).

> What about "Switch Mapper" ?

I've seen that suggestion before, including variants as  transformer, encapsulate, emulate and similar. We currently will stick with this one for a moment and see how it involves in the future.

Thanks for your suggestion though!

../Frenck

PS: Topics like these are more suited for the community forums :) As this is not really a documentation suggestion that can be applied.
