### ISSUE TITLE
Missing Sensor Information

### ISSUE THREAD

**Issue by seraphx2** [home-assistant/home-assistant.github.io#22336]
### Feedback

Needs sensor JSON output values and/or examples to know what to code against

### URL

https://www.home-assistant.io/integrations/version/

### Version

2022.4.1

**Comment by ludeeus** [comment]
What sensor information? It has a state, that state reflects the latest version.
JSON output?

**Comment by seraphx2** [comment]
Ya know what. Ignore me. lol. I've literally been working with APIs all day, it's almost 4am. I don't know what I'm thinking. lol sorry about that.
