### ISSUE TITLE
Confused by an instruction

### ISSUE THREAD

**Issue by richardjlyon** [home-assistant/home-assistant.github.io#22337]
### Feedback

re:

> Often you can achieve the same manually, refer to the documentation by the vendor of the application you'd like to install.

If applications are not visible if you haven't used the Home Assistant Operating System or Home Assistant Supervised installation methods, how do you access the documentation they provide on how to install them?

### URL

https://www.home-assistant.io/addons/

### Version

2022.4.1

**Comment by frenck** [comment]
Add-ons provide existing applications (wrapped up in an easy-to-use package). If your installation type doesn't provide the use of add-ons, it is up to you to install the applications you'd like.

For example, there is a Node-RED add-on. But if you can't use add-ons, you can still use Node-RED, read the documentation provided by Node-RED on how to install and set it up yourself.
