### ISSUE TITLE
Mention connectivity requirements

### ISSUE THREAD

**Issue by sagacis** [home-assistant/home-assistant.github.io#22330]
### Feedback

Does the integration require wifi or internet connectivity to the house? My installer only connected to the enphase cloud via cellular. I'm not local to the system, so I can't change that setting easily. 

Maybe include in the description some minimum settings. Alternatively, I can grant API access to the cloud interface, which is only available with internet, but better than nothing.

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2022.4.1

**Comment by frenck** [comment]
> Does the integration require wifi or internet connectivity to the house?

![CleanShot 2022-04-11 at 15 08 12](https://user-images.githubusercontent.com/195327/162746191-e206e963-7906-4b0a-a720-5f90ba1ed34e.png)

It is a local polling integration (you can click on that text for more information about that), which means its not reliant on the "Cloud" (and thus does not need internet).
