### ISSUE TITLE
Turn on not working for single room

### ISSUE THREAD

**Issue by emirahic** [home-assistant/home-assistant.github.io#22344]
### Feedback

Hello,
turn on is not working on single room. Everything works fine, like set the temp and turn off the rooms. I'm using a AZCE6, previosly i've been dealing with API to get temperatures on HASS, when i saw this i was super happy! It's the first time i'm using github, so i still don't know how it works at all. Is there some way to contribute to the project?
Thanks,
Emir

### URL

https://www.home-assistant.io/integrations/airzone/

### Version

2022.4.2

**Comment by frenck** [comment]
Hi there @emirahic 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by emirahic** [comment]
Hi @frenck ,
thank you for the quick feedback, meanwhile i think i solved it!
Best regards,
Emir
