### ISSUE TITLE
Urgent update of documentation is needed as Google has added new requirements

### ISSUE THREAD

**Issue by new-kirte** [home-assistant/home-assistant.github.io#22346]
### Feedback

As per https://community.home-assistant.io/t/can-no-longer-link-google-assistant/409495/19 Google now needs the “Enter information required for the Actions directory” portion of the Actions setup overview to be completed. This includes:

- A description of your app
- A logo image for your app
- Your name and email
- A link to a privacy policy

The community solution contains all needed steps to update the documentation, so credit goes to Omnipius

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2022.4.2

**Comment by frenck** [comment]
Feel free to suggest an edit!

**Comment by new-kirte** [comment]
> Feel free to suggest an edit!

I actually did. I suggested to use https://community.home-assistant.io/t/can-no-longer-link-google-assistant/409495/19 - the community finding

**Comment by frenck** [comment]
I meant, actually editing it. There is an edit button on the bottom of each page in the documentation too...

**Comment by new-kirte** [comment]
Otherwise add new step 4 and make existing step 4" Add the google_assistant integration configuration to your..." to be a step 5.

4. Enter Deployment details

1. Click on the Overview tab at the top of the page to go back.
2. Click on section "Get ready for deployment" and then click on "Enter information required for the Actions directory".
3. Enter the Description details:

-  Short Description - one line summary for the Action. For example "Connect Google Assistant to a private Home Assistant server"
- Full Description - detailed description of the Action. For example "This Action is intended for personal use. It exposes smart home devices controlled by a local Home Assistant server to Google Assistant and by extension the Google Home mobile app."

3. Click on "Images" and then click on "Small Logo". Upload a logo file. For example, a Home Assistant logo.
4. Click on "Contact Details":

-  Developer email - Enter your email
-  Developer name - Enter your name or your company name

5.  Click on "Privacy and consent". Click on "Learn More" to follow Google instructions to create a policy file:

-  Create an empty Google Doc file and name it "Your Action Private Policy"
-  Fill out the focument with Private Policy terms and conditions. For example:
    - <Action Name> Privacy Policy
    - This application is intended for the private use of its developer. Any unauthorized users which connect to this service should have no expectation of privacy or protection of their data.
    - Save the file.
    - Set file share settings to “Anyone with the link can view” 
    -  Copy the link
-  Paste the link to "Privacy Policy"
6. Click Save

**Comment by new-kirte** [comment]
> I meant, actually editing it. There is an edit button on the bottom of each page in the documentation too...

Ok, I created a PR
