### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kapusticka** [home-assistant/home-assistant.github.io#22350]
### Feedback

please! what does it mean this error? 

duplicated mapping key at line 56, column -713:
    automation:
    ^

### URL

https://www.home-assistant.io/integrations/manual/

### Version

2022.4.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

Feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
