### ISSUE TITLE
logger.set_default_level is deprecated

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/home-assistant.github.io#22352]
### Feedback

Hello,
it seems that the described logger.set_default_level is no longer available.
Please clarify or update the documentation.

### URL

https://www.home-assistant.io/integrations/logger/

### Version

2022.4.2

**Comment by klaasnicolaas** [comment]
It's still present in [the code](https://github.com/home-assistant/core/blob/dev/homeassistant/components/logger/__init__.py), so you can use it too.

**Comment by AleXSR700** [comment]
Since upgrading to 2022.4 it is no longer available.
I cannot select it from 'Call service' in the automations UI and since I have it running as an automation anyway, I am getting error messages.

`Error while executing automation automation.set_logger_default_level_2: Unable to find service logger.set_default_level
06:30:57 – (ERROR) Automation
Set Logger default level: Error executing script. Service not found for call_service at pos 1: Unable to find service logger.set_default_level
06:30:57 – (ERROR) Automation`

So I am sure, that at least on my system, it is no longer working.

Also not showing in available services
![image](https://user-images.githubusercontent.com/57034871/162875138-bd0e6cd7-77c0-4721-9f5f-d9d1a040f664.png)

**Comment by klaasnicolaas** [comment]
Update core to version 2022.4.2, if all goes well it should be visible again

**Comment by klaasnicolaas** [comment]
Anyway it is not deprecated according to the code, so the question is rather what makes you see or not see the named services. Can you check for me if you have set up the [logger integration](https://www.home-assistant.io/integrations/logger/) somewhere? Only when I have placed them in the yaml code, the services are available to me.
