### ISSUE TITLE
Uptime value returns 'last boot time'

### ISSUE THREAD

**Issue by dominicusmento** [home-assistant/home-assistant.github.io#22354]
### Feedback

Not only the docs but the functionality too.

In short, uptime is uptime and should not return datetime of last boot time.
It should be a TimeSpan; hours, minutes, seconds or whatever unit passed from the last boot until the current moment.

### URL

https://www.home-assistant.io/integrations/uptime/

### Version

2022.4.2

**Comment by frenck** [comment]
Thank for the feedback, I agree, but there is added history here. Change that, would be highly breaking, hence we opt for having a slightly lesser fitting name.

(That said, this isn't really documentation feedback 😉 )

Regards,

../Frenck

**Comment by dominicusmento** [comment]
Hi,

I understand the change would be highly breaking and possibly most of the users don't want to change the behavior and it's the reason why I opened issue in docs. As I would expect at least to find an example of how to calculate actual Uptime and use it in template conditions in the docs. 😉

For me it doesn't matter anymore as I've fixed my automation (don't want to trigger the automation on HA restart based on door contact sensor) but for the others may be helpful.

**Comment by frenck** [comment]
> As I would expect at least to find an example of how to calculate actual Uptime and use it in template conditions in the docs.

That is not for this page. If please consult the template documentation for how templates work.

**Comment by dominicusmento** [comment]
No, it is for this page.. because page is about 'uptime' and there is no uptime value available.. you are talking about the last boot time on this page.. and people came here for uptime (in hours, minutes, seconds).. they don't need template and templating.. 
they don't need to know nothing about wrong naming in home assistant etc.. so please fix this

**Comment by frenck** [comment]
I'm sorry, I'm in disagreement, all time-based sensors states are timestamp based, regardless of countdown or not. This is not an error, this is by design.

The frontend handles display them nicely, including relative time since now. If you want to do calculations with time in templates, please consult the template documentation instead.

This sensor is not broken or wrongly described. It sounds odd due to the design Home Assistant handles in its state machine, but it is not wrong.
