### ISSUE TITLE
Fronius integration status codes and error codes

### ISSUE THREAD

**Issue by QbaF** [home-assistant/home-assistant.github.io#22361]
### Feedback

In HA integration Fronius one can find sensors `Error code` and `Status code`.  `Error code` is easy to find, but still, there could be a link to the Fronius errors dictionary, like [e.g. here](https://solaranalytica.com/fronius-inverter-state-codes/. )

But I am unable to find, what is `status code` and where it is possible to be found.

As well it would be nice to find `Led color` sensor values dictionary.

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2022.4.2

**Comment by farmio** [comment]
Hi 👋!
You can find these e.g. here: https://www.fronius.com/~/downloads/Solar%20Energy/Operating%20Instructions/42%2C0410%2C2012.pdf

Feel free to extend pyfronius or the HA Fronius integration to add a sensor holding string representations of these codes.

**Comment by QbaF** [comment]
Thanks.
I will be happy to help but am still too noob in python.

But I think that this link to API could be helpfull in docs.
