### ISSUE TITLE
Please provide an example of what I can do with this.

### ISSUE THREAD

**Issue by skome** [home-assistant/home-assistant.github.io#22376]
### Feedback

Can I get current weather/cloud conditions? How? Is there a link to the API? What is the handhold to start using this, if I don't already know how to use it?

Many thanks!

### URL

https://www.home-assistant.io/integrations/met/

### Version

2022.4.3

**Comment by frenck** [comment]
> Can I get current weather/cloud conditions? 

Sure

> How?

It is an integration that provides entities, just like any other Home Assistant integration. 

> Is there a link to the API?

API? Not sure how this question related to all of this. The information is available in Home Assistant and can be used to put on dashboards, or, for example, automate with.

> What is the handhold to start using this, if I don't already know how to use it?

To start using what? To do what?

Considering your questions, I feel like your question are more related to Home Assistant in general, and not to this specific integration.

../Frenck

**Comment by dannytsang** [comment]
@skome I've got it on my dashboard to show the current and next few days of forecast:
![image](https://user-images.githubusercontent.com/567982/164066577-fc1b4069-81a6-41a7-b523-4652c663fe2a.png)

It provides quite a few sensors(entities) so you could use any of them in an automation.
![image](https://user-images.githubusercontent.com/567982/164066962-9fe7352c-393c-4e60-a752-9d87b73ae103.png)

**Comment by skome** [comment]
> > Can I get current weather/cloud conditions?
> 
> Sure
> 
> > How?
> 
> It is an integration that provides entities, just like any other Home Assistant integration.
> 
> > Is there a link to the API?
> 
> API? Not sure how this question related to all of this. The information is available in Home Assistant and can be used to put on dashboards, or, for example, automate with.
> 
> > What is the handhold to start using this, if I don't already know how to use it?
> 
> To start using what? To do what?
> 
> Considering your questions, I feel like your question are more related to Home Assistant in general, and not to this specific integration.
> 
> ../Frenck

I want to build automations with it and don't see how.  Contrary to this reply, I don't see entities.  I have built automations with Home Assistant using various sensors and other web services. 
When I click the instance under Sensors > Control, I see temperature, air pressure, etc, but not the entity field names that would allow me to use these values. 
When I create a new automation and choose the Forecast service for triggers or condition, there is nothing further to do or choose. The pulldowns are greyed out.  I would write some yaml, but again, don't know what the service field names are.
When I click "Visit service", it goes to a top level web page and after digging a while I don't find a description of the API, which is normally something I look for.

**Comment by skome** [comment]
> @skome I've got it on my dashboard to show the current and next few days of forecast: ![image](https://user-images.githubusercontent.com/567982/164066577-fc1b4069-81a6-41a7-b523-4652c663fe2a.png)
> 
> It provides quite a few sensors(entities) so you could use any of them in an automation. ![image](https://user-images.githubusercontent.com/567982/164066962-9fe7352c-393c-4e60-a752-9d87b73ae103.png)

Thanks for your reply.  Have you used it in an automation, and if so, where do you see the entity information for those values in the dashboard display?

**Comment by dannytsang** [comment]
@skome Your can use the developer tools -> States to view the available information. 
![image](https://user-images.githubusercontent.com/567982/176235668-edda268b-a02c-495f-b39f-454bf2246d9c.png)

You will need to enable advanced mode under your profile (clicking on your picture on the bottom left of the side bar) to see the feature.
![image](https://user-images.githubusercontent.com/567982/176236110-a7118a4e-f0f8-4bc2-91cb-ae8c698f4e0d.png)

Here's a list of attributes on my weather:
![image](https://user-images.githubusercontent.com/567982/176233682-b791a8f2-38c9-4e4c-8b84-81438972a630.png)

Depending on how you want to use the weather entity in an automation (e.g. trigger, condition, action?) you can use the current weather information. Here's an example using weather as a trigger:
![image](https://user-images.githubusercontent.com/567982/176234605-21a9c94e-3b0d-4abc-9527-b2a9246baf1e.png)

Another example using the current temperature which is an attribute of the weather entity:
![image](https://user-images.githubusercontent.com/567982/176235214-d987312c-62e2-4337-a720-7894afcbb38e.png)

**Comment by skome** [comment]
Super helpful! Thanks!
