### ISSUE TITLE
Energy Cards - Real Time Info

### ISSUE THREAD

**Issue by JoseCarlos64** [home-assistant/home-assistant.github.io#22384]
### Feedback

Dear Sirs

First of all I want to thank you for your work and effort in developing these magnificent cards.
I would like to give you the suggestion, which is in energy-distribuition card,  keeping the features that currently exist, but also give you the possibility to show instant production and consumption.

Thanks again
José Carlos Cabral

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2022.4.3

**Comment by tribun83** [comment]
the request is still valid and I second it. Thanks
