### ISSUE TITLE
Unable to authorise account

### ISSUE THREAD

**Issue by Iggy8285** [home-assistant/home-assistant.github.io#22388]
### Feedback

Under section entitled 'OAuth and Device Authorization steps', on step 2. when click 'Authorize your account', I am able to select all the devices I wish to allow Home Assistant to access.  However, when clicking 'Next', it returns:

_Error 400: invalid_request' 

"You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one
![Untitled](https://user-images.githubusercontent.com/69870141/163421645-9e4d9691-aad9-45dd-8d9a-30072157b727.png)
 or more Google validation rules."_

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.4.3

**Comment by frenck** [comment]
Hi there @Iggy8285 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
