### ISSUE TITLE
HA can't see devices

### ISSUE THREAD

**Issue by letrout** [home-assistant/home-assistant.github.io#22416]
### Feedback

I've configured many entities as shown in this example. All show up in my "Entities" list, and I am able to create Lovelace panels for them. However, nothing I do gets them to show up in the "Devices" list. And when I try to use any of the wizards (like Create Automation) I always get "no matching devices found".

So how do I configure "Devices" in HA? Because there must be more to it than what this page says.

### URL

https://www.home-assistant.io/docs/configuration/devices/

### Version

2022.4.5

### Additional information

from configuration.yaml, makes a sensor I can manually monitor but not shown in "Devices":

`binary_sensor:
  - platform: mqtt
    state_topic: "influx/Owens/events/#"
    name: "Garage side door"
    payload_on: 1
    payload_off: 0
    qos: 0
    device_class: door
    value_template: >
      {% if value.split(',')[2].split('=')[1] == 'garage' and value.split(',')[3].split('=')[1] == 'side' %}
        {{ value.split(' ')[1].split('=')[1] }}
      {% endif %}`

**Comment by frenck** [comment]
"devices" in that context is the external physical device, not the Home Assistant Device context.

See the MQTT binary sensor documentation on how to configure this MQTT platform entry to provide Home Assistant device support:

<https://www.home-assistant.io/integrations/binary_sensor.mqtt/#device>

../Frenck
