### ISSUE TITLE
Tuya IoT no longer works, requires paying $25,000 per year

### ISSUE THREAD

**Issue by secbitchris** [home-assistant/home-assistant.github.io#22418]
### Feedback

Beyond the 30 day trial, there is no possibility of using this anymore. It just fails.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2022.4.5

**Comment by frenck** [comment]
According to their documentation:

https://developer.tuya.com/en/docs/iot/Home-assistant-tuya-intergration?id=Kb0eqjig0utdd

![CleanShot 2022-04-18 at 11 21 21](https://user-images.githubusercontent.com/195327/163787394-364c5292-c03d-4bf0-9cba-148d17c5b7ad.png)

If you have any questions about Tuya their services, you could probably better contact Tuya.

../Frenck

**Comment by secbitchris** [comment]
Extending does not work.

**Comment by secbitchris** [comment]
I am considering Tuya completely dead for HA, since there is no way around their $25k per year charge to make their API work anymore.

**Comment by frenck** [comment]
Have you contacted Tuya support? What was their answer?

**Comment by adamlaz** [comment]
I just sent the below question to their support. Will see what they say, expect a reply before Wednesday.

![Screenshot on 2022-04-18 at 10 37 42 of Tuya Developer Product Inquiry Form - Tuya Smart - Global IoT Development Platform in Google Chrome](https://user-images.githubusercontent.com/2012381/163824166-643e0df7-dc1b-4933-a14b-6fd1606ac25a.png)

**Comment by secbitchris** [comment]
@adamlaz Thanks! I had tried to extend but it kept giving me errors saying only 1 trial period ever was allowed.

**Comment by adamlaz** [comment]
Bad news. [I had a live chat with Online Support](https://user-images.githubusercontent.com/2012381/164377019-7ba7a056-aaf4-4dbb-bcdb-98f69f99bab5.png) and **the 'fee needs to be paid' after the trial expires to use the Tuya Developer platform**. 

I was pointed to [this 'purchase' page](https://www.tuya.com/vas/tmpl/apply?code=IOT_CORE ) where there is a link to an [early-access-program application](https://developer.tuya.com/en/early-access-program). It's possible that the support rep was saying I could ask there and that route could grant me access after trial expiration, without needing to purchase the $25k 'Flagship Edition'. I'm going to try asking about it via that form, and see what happens. 

Real bummer if I'm not going to be able to integrate these ceiling lights I just got! But, I guess that's the game  🙃 !

**Comment by frenck** [comment]
Could you share the conversation or a screenshot or the response?

**Comment by frenck** [comment]
Oh you did 🤦

**Comment by balloob** [comment]
I reached out to Tuya and got this response:

>  We confirm that the individual users can extend their Tuya trials past the 6 month trial for free. Users can simply visit the Tuya IoT Core service page, click the“Extend Trial Period”button and fill in application form to apply for extra 6 month trial for free within the last 30 days before the 6 months trial expires.
