### ISSUE TITLE
Insteon hub post factory-reset & death of Insteon company - WORKING

### ISSUE THREAD

**Issue by gdychow** [home-assistant/home-assistant.github.io#22426]
### Feedback

HA can integrate with a factory reset hub (zero config), or add new devices w
- Hub will not have any Insteon device config information
- Each device will need to be reconnected to the hub using the insteon.add_all_link service
- Procedure (required for *each* device)
1. Trigger service (puts hub into "device discovery" mode, confirmed by a beep from the hub)
2. Press the "Set" button on the device to connect
3. Listen for audible confirmation beep from hub
4. Service will confirm device has been added to the hub - you will then need to add device name & relevant details

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.4.5

### Additional information

I've confirmed this is working as I only started using HA after Insteon.com decided to go bankrupt, so quick 2-hour HA primer and it's all up and running!

**Comment by teharris1** [comment]
I am adding your note to the Insteon documentation. Thanks for letting me know. We are all in this together!
