### ISSUE TITLE
Curl example does not work

### ISSUE THREAD

**Issue by githubrdonefun** [home-assistant/home-assistant.github.io#22424]
### Feedback

I reached out to them directly and they provided this an example.  I just tested it and it works, where as the current example does not.  You may want to update the documentation.

curl -H "Content-type: application/json" -d '{"username":"freddo", "password":"the_frog", "email":"[freddo@frog.org](mailto:freddo@frog.org)", "org":"freds world"}' https://api2.watttime.org/v2/register

### URL

https://www.home-assistant.io/integrations/watttime/

### Version

2022.4.5

**Comment by bachya** [comment]
I just tried the example in the docs and it works. What error do you receive?

**Comment by githubrdonefun** [comment]
I get a 400 error.  I ran it on this site:  https://reqbin.com/curl

{
    "error": "Username or password not supplied"
}

**Comment by githubrdonefun** [comment]
Does the example work on that site for you?

**Comment by bachya** [comment]
I use Postman – the query provided in the docs is a direct export from a working example there.

**Comment by githubrdonefun** [comment]
Documentation does not work for me.  I can post examples of how it was fixed from the API developer.  There seems to be disagreement if documentation is correct or not.  It does not work for me and I showed my steps.  No response was given.

**Comment by bachya** [comment]
Feel free to open a PR with your suggested changes.

**Comment by githubrdonefun** [comment]
Sorry, not familiar with how to do that.
