### ISSUE TITLE
Data and Time sensors list have been renamed?

### ISSUE THREAD

**Issue by aniceberg** [home-assistant/home-assistant.github.io#22434]
### Feedback

I noticed that "**omer_count**" is now "**jewish_calendar_day_of_the_omer**", and that "**first_stars**" is now "**jewish_calendar_t_set_hakochavim**". 

I also noticed that the **sensor.jewish_calendar_t_set_hakochavim** state's value is "**2022-04-20T00:08:00+00:00**" which makes no sense to me either. 

Am I doing something wrong with the integration? Am I supposed to take out the entry in my configuration.yaml?

### URL

https://www.home-assistant.io/integrations/jewish_calendar/

### Version

2022.4.5

**Comment by frenck** [comment]
IDs are not guaranteed, so it's better to provide a list of sensors as a description (and without IDs)
