### ISSUE TITLE
insteon scene example

### ISSUE THREAD

**Issue by NathanielB2** [home-assistant/home-assistant.github.io#22437]
### Feedback

Hello, 
It would great if you could include an example of getting a insteon scene to trigger by alexa.  I'm new to home assistant and it hard to get complete examples that I could learn from.  I have made an automation but don't see any way of triggering it. 

Thanks
Nathaniel

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.4.5

**Comment by teharris1** [comment]
The issues section is for problems with the solution. You should use `[community.home-assistant.io](https://community.home-assistant.io/)` site for this type of question. I assume you are likely new to HA like a lot of orphaned Insteon users. The Insteon community is very good here, you will get a lot of support.

**Comment by NathanielB2** [comment]
Thanks for the advice.  It seems there is a lot of forms and areas with limited information and when you ask for more they pass you on.   Maybe you can tell me why the developer-tools/service for Insteon: Scene on might work one time then it seems to stop.   I don't get any errors just the 2022-04-19 14:01:37 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-04-19 14:01:37 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service 

Is there another way in getting a list of scenes set in the hub 2 ? 

Best,
Nathaniel

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues and in this repository only documentation feedback, not for providing support.

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
