### ISSUE TITLE
Add parameter to force keypad or ignore panel code

### ISSUE THREAD

**Issue by ChrisCaho** [home-assistant/home-assistant.github.io#22440]
### Feedback

It would be helpful if there was another parameter on the alarm panel card that would allow a configuration to force the full keypad or ignore the configured code for the panel entity.  I am using the Envisalink integration and would like to use the 'code: !secret envisalink_passcode' parameter on the integration.  I want the code defined in the integration for automation from HA that might arm / disarm my panel based on presence.  However, when I define the code in the integration then when I use an alarm panel card in a dashboard the keypad buttons disappear.  I would like the keypad to stay and I would like the card to force users to use their own alarm codes to arm / disarm the alarm system and call the service with the code given (not use the code I have defined in the integration configuration I want for automation only).  Then I could have an iPad on the counter with a dashboard available to arm / disarm for users and require they use their individual codes.  Not just be open to anyone pressing arm / disarm without a code.  Additionally a configuration like this would cause the alarm system log to have arm / disarm entries by user as well as one recognizable as an automation arm / disarm.  

### URL

https://www.home-assistant.io/dashboards/alarm-panel/

### Version

2022.4.5

### Additional information

![image](https://user-images.githubusercontent.com/20073649/164077782-87dbadaf-0c9f-474d-a9ba-20b760c72e36.png)

I wish it would look like the following regardless of using 'code:' parameter in Envisalink integration.  I am sure not everyone would want the change in behavior which is why I wish there was a parameter to change the default behavior.  

![image](https://user-images.githubusercontent.com/20073649/164080899-26e24172-5698-4562-887e-3826c51ecbda.png)

**Comment by frenck** [comment]
> It would be helpful if there was another parameter on the alarm panel card that would allow a configuration to force the full keypad or ignore the configured code for the panel entity

Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
