### ISSUE TITLE
Give examples of the "simple" rules. The there is less headaches adn frustration by Important Template Rules

### ISSUE THREAD

**Issue by Strikky** [home-assistant/home-assistant.github.io#22448]
### Feedback

Give examples of the "simple" rules. Then there is less headaches and frustration by Important Template Rules

Hours of frustration and didn't find what goes wrong.

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2022.4.5

**Comment by frenck** [comment]
The rules are right above the text? I'm not sure what you mean? Could you give an example of how we could make this more clear?
