### ISSUE TITLE
Kasa Integration documentation out-of-date?

### ISSUE THREAD

**Issue by chicagoandy** [home-assistant/home-assistant.github.io#22458]
### Feedback

From reading the Kasa Integration documentation, and the mentioned Alert.

The Integration documentation does not mention Local vs Cloud access.   It does not mention any procedures for turning on Local Access, which I understand requires resetting devices and controlling them as 'Guest'.

There is a link to a Kasa alert, which has not been updated in 9 months, and it implies the integration does not work.

Yet the integration seems to work.   But there's no way to tell if we have Local Control or Cloud.

Can we get an update on Kasa integration documentation please.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2022.4.6

**Comment by rytilahti** [comment]
Related to https://github.com/home-assistant/home-assistant.io/pull/22517

**Comment by AlohaFlyer** [comment]
Any chance that this integration will also allow connection of Kasa TP-Link Cameras? like KC400 or KC420WS

**Comment by rytilahti** [comment]
I think we can close this as I'm not seeing an alert at https://alerts.home-assistant.io/ nor at https://www.home-assistant.io/integrations/tplink/ .
