### ISSUE TITLE
Some insteon switches are non responsive on home assistant

### ISSUE THREAD

**Issue by toorg55** [home-assistant/home-assistant.github.io#22457]
### Feedback

hi ,
thank you for this project you really saving 100k's insteon users.
after following the guides and installing home assistant on pi 3 64bit i notice that out of 20 wall switches/dimmers 5 gives me issues.
the main issue 
from app or pc web interface i can't control the 5 switches / dimmers using the toggle on bottom but only using the dimmer slider , when trying the voice control it gives the same issue (turn on or off won't work)
what am i doing wrong? another important thing is that i can turn switch off using toggle button but not on .

i tried reset both pi and hub and no success

### URL

https://www.home-assistant.io/integrations/insteon#autodiscovery

**Comment by darikweitzel** [comment]
My insteon thermostat stop responding to HA.  If I change the temp physically, the HA doesnt reflect that and if I change it on the HA, it doesnt reflect on the physical thermostat.  I monitored logs and it doesnt see any changes on the thermostat at all. Soon as I updated to the beta, I went to turn up the stat and nothing. I tried removing and readding the stat in the insteon intergration but did not help.

**Comment by frenck** [comment]
Hi there @toorg55 and @darikweitzel 👋 

I understand you both are  trying to report an issue with the Home Assistant Insteon integration; however, you have submitted documentation feedback instead.

If you want to report an issue, please report it in the issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by darikweitzel** [comment]
Sorry I’ll get it updated today. Thank you for your service!
