### ISSUE TITLE
Wind_chill value missing

### ISSUE THREAD

**Issue by donparlor** [home-assistant/home-assistant.github.io#22459]
### Feedback

It seems the wind_chill value is not updated when temperature is above 0ºc. I live in Saguenay, so the entity sensor.saguenay_wind_chill will not update when in the spring season above 0.
![Capture d’écran, le 2022-04-21 à 12 36 53](https://user-images.githubusercontent.com/97048708/164508875-e8a6b4f9-13e6-4e07-ba5e-f61d673ffb42.png)
 
Can anyone confirm if there is an issue or Environnement Canada simply does not provide values when weather outside gets above 0ºC ??

### URL

https://www.home-assistant.io/integrations/environment_canada/

### Version

2022.4.6

**Comment by michaeldavie** [comment]
There's no fancy logic being applied, the integration just uses the data provided by Environment Canada. Wind chill values are only provided below 0ºC, and humidex values are only provided above 19ºC. See https://weather.gc.ca/windchill/wind_chill_e.html for more information.

This issue can be closed.

**Comment by donparlor** [comment]
@michaeldavie, would it make sense to add an asterisk (*) in the [integration](https://www.home-assistant.io/integrations/environment_canada/) description to avoid confusion?

*Wind chill values are only provided below 0ºC, and humidex values are only provided above 19ºC

Thank you for your answer!

Vincent
