### ISSUE TITLE
Issue with the Integrations on HA web page

### ISSUE THREAD

**Issue by dajomu1** [home-assistant/home-assistant.github.io#22455]
### Feedback

Hi there,

seems like none of the links to the specific integrations are working. I tried two different browsers so I do not think that the issue is on my side. Apart from this the web page works fine.
https://www.home-assistant.io/integrations/

### URL

https://www.home-assistant.io/integrations/

**Comment by frenck** [comment]
Could you provide details on the browser, OS versions and others?
I've not been able to reproduce the issue you are reporting (nor did we get more reports).

**Comment by davet2001** [comment]
I also can't reproduce this.

**Comment by dajomu1** [comment]
Sorry,

I cannot reproduce the issue anymore either. Strange.

Thanks anyway.

D
