### ISSUE TITLE
Extra info

### ISSUE THREAD

**Issue by balintbuzasi** [home-assistant/home-assistant.github.io#22462]
### Feedback

Cool card, I love. 
One thing to add: it would be nice, if you could add secondary (or more) info to the forcast card. Eg. wind speed and rain forcast would come pretty handful.

### URL

https://www.home-assistant.io/dashboards/weather-forecast/

### Version

2022.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
