### ISSUE TITLE
Regional Filter - Feature Request

### ISSUE THREAD

**Issue by oneofthemany** [home-assistant/home-assistant.github.io#22461]
### Feedback

It would be beneficial to have a region filter as scrolling through all regions is not ideal

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2022.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
