### ISSUE TITLE
Cant add Tuya IOT account via QR-Code: CAPP_BINDED_USERID

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/home-assistant.github.io#22470]
### Feedback

Hey guys,

I tried to add my Tuya account to the IOT platform as explained [here](https://www.home-assistant.io/integrations/tuya). But at the step with the QR-Code I get a pop error message with CAPP_BINDED_USERID twice when I want to confirm the link:

![Screenshot_20220422_150159](https://user-images.githubusercontent.com/614929/164719703-b9b47c35-d22b-4e93-922d-6cb0a445c822.png)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2022.4.6

**Comment by sisimomo** [comment]
I had the same problem.

For my part it was simply because I had selected the wrong data center.

**Comment by Birillo71** [comment]
Same problem for me

**Comment by Mr-Alicates** [comment]
Same problem for me. I got it working after selecting a different data center, a different one that I wasn't expecting

**Comment by frenck** [comment]
This is an error @ Tuya, not Home Assistant. Please contact Tuya support instead.

Thanks!

../Frenck
