### ISSUE TITLE
Reinstall python pip in termux

### ISSUE THREAD

**Issue by scottn1972** [home-assistant/home-assistant.github.io#22474]
### Feedback

I see where everybody's saying to install the file path and everything else for reinstalling pip when all you have to do is package uninstall all three python packages and then reinstall them and you have it

### URL

https://www.home-assistant.io/faq/pip3/

### Version

2022.4.6

**Comment by frenck** [comment]
I'm not sure if I follow the suggestion? Could you add an example of what you would change exactly?

**Comment by frenck** [comment]
Why did you close the issue @scottn1972 ?
