### ISSUE TITLE
Also works with Soundavo WS66i

### ISSUE THREAD

**Issue by mazur50** [home-assistant/home-assistant.github.io#22482]
### Feedback

Also works with the Soundavo WS66i.  This amp is based on the Monoprice amp but has networking built in.  Can also be linked to a moprice amp to extend the zones.

### URL

https://www.home-assistant.io/integrations/monoprice/

### Version

2022.4.6

**Comment by frenck** [comment]
As of Home Assistant 2022.6, Home Assistant will provide a dedicated integration for the Soundavo WS66i 6-Zone Amplifier 🎉
