### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by BonesetRanch** [home-assistant/home-assistant.github.io#22480]
### Feedback

Your instructions on how to access my formerly dead Insteon Hub were great.  I can now get into the hub and use my devices with Home Assistant.  It's wonderful to know I can access my Insteon devices on the computer and in an app again.

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.4.6

**Comment by klaasnicolaas** [comment]
Glad to hear you like it 😉 

./Klaas
