### ISSUE TITLE
Not clear where to enter command

### ISSUE THREAD

**Issue by dmaciuca** [home-assistant/home-assistant.github.io#22495]
### Feedback

Instead of "The following services are available:"  I would add "The following services are available under Developer Tools, Services Tab:"  I know right before it says "through [Developer Tools] service calls.", but I didn't think that was clear enough.

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.4.6

**Comment by teharris1** [comment]
Thanks for the Feedback
