### ISSUE TITLE
Raspberry Pi Embedded Server

### ISSUE THREAD

**Issue by dmaciuca** [home-assistant/home-assistant.github.io#22496]
### Feedback

Between here: "With the Home Assistant Operating System installed and accessible you can continue with onboarding." and "Onboarding" it's not clear what is happening.  It's not clear that Raspberry Pi becomes an embedded server and the graphical UI needs to be accessed from another computer on the network.  Maybe some changes between 3. and 4. above.

3. Attach the power cable.
4. Wait for the Raspberry Pi prompt.
5. In the browser of [your Desktop system] **another computer on your network**, within a few minutes you will be able to reach your new Home Assistant on [homeassistant.local:8123](http://homeassistant.local:8123/).

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.4.6

**Comment by klaasnicolaas** [comment]
It seems to me a fairly clear instruction, how else could you approach the local URL? This has to be done via another device. 🤷🏻‍♂️

**Comment by dmaciuca** [comment]
While I agree, I've seen plenty of comments on forums that people expect to be able to launch an GUI from the ha> prompt or from a web browser in the Raspberry Pi.  Anyway, just a suggestion.
