### ISSUE TITLE
Functionality from integration missing.

### ISSUE THREAD

**Issue by dazzyp** [home-assistant/home-assistant.github.io#22491]
### Feedback

Can you provide information on the cruise or how to exposure functionality please?

I've used this plugin to successful context to my Epson tw9400 /5050hub (us model), over LAN. I can fully control the device using the Epson Android app.
But, I can only toggle On/Off from the dashboard. No actions are available when i try to set up a routine for the projector e.g press a smart button to remotely turn on.  I also can access the other functionality such as change input or other settings.

I'm happy to be a guinea pig for testing.

Thanks

### URL

https://www.home-assistant.io/integrations/epson/

### Version

2022.4.6

### Additional information

Na

**Comment by pszafer** [comment]
I don't understand what's the actual bug is in integration? In HA there is no such things as routines.

**Comment by dazzyp** [comment]
Hi
Thanks for responding to my query, and my apologies if i've caused confusion by using the incorrect terms.
Also sorry for the delayed reply. I work in a hospital and don't get much time to tinker with things outside of work.

Basically,  I've used the  HA Epson PJ integration to link my LAN connected Epson TW9400.  The only control that is available on the dashboard is to Turn On /Turn Off which works:

[cid:cec8aa4d-ae59-4e43-bb98-5fe83da5421f]



What i want to do is setup one of my zigbee buttons (connected to HA through Zigbee2mqtt)  to be a wall mounted button for turning the PJ on and off,  but no actions are available for the device when i select the Epson projector in the 'setup automation' template wizard - as below.

Do you know how i can do this?

To me, the fact there is a working power button on the dashboard for the integration, but no functions are exposed is an issue with the integration and not my projector.
there is only a single 'entity' in the device listing for the projector also. See below.

I have uninstalled and reinstalled the integration, plus also tried ona  completely new HA setup but i still get the same results.

The documentation for the integration mentioned the ability to control volume, and image presets which i don't see anywhere but assume this is because my model is different to those used to develop the HA integration.

Any feedback appreciated.

Regards
darren

[cid:6a34e73b-83fd-4ad3-9fad-772f89cd4091]



________________________________

**Comment by frenck** [comment]
Please don't use email to respond to GitHub issues; use GitHub itself instead. If you go to  GitHub you'll see your last response looks weird and it seems that you tried to embed an image too (which is now missing).

../Frenck

**Comment by dazzyp** [comment]
@frenck 
Apologies for replying my email - i know know it's best to reply through GitHub.

As mentioned, i've installed the Epson PJ integration for my Epson TW9400, (called the 6050UB in the US) connected over lan.  

The only control i can see or access  is a power button icon to run the projector on and off (which works) and a volume up and down (which appear when the projector is on. 

I wish to program a zigbee button to control the projector power status, but no actions or entities (correct term) are available when i try and setup an automation in the setup automation' template wizard.

Can you advise on how i can do this? 

On the lovelace dashboard, the auto generated card for the Epson integration only shows one device 'Epson projector' and 1 entity 'media_player.epson_tw9400'.
I assume there should be more entities but maybe they are missing as i'm using an unsupported model?

Any feedback greatly appreciated.

Regards
darren 

![download](https://user-images.githubusercontent.com/28025818/167686111-888e041a-4fef-4a3f-b0d0-bef487389338.png)
![download](https://user-images.githubusercontent.com/28025818/167686136-e229f902-5b82-4fd8-8b7c-2162a3ac56b3.png)

**Comment by pszafer** [comment]
you need to use service `media_player.turn_on/turn_off`

**Comment by dazzyp** [comment]
Thanks for the speedy response! 
I will try that later tonight,

The documentation mentions other functions which i can;t see.
I assume my model doesn't support or expose these  which is why i don't' see an option?

To be honest, controlling the power state is all i need, but i'm curious about the other things
..............................

https://www.home-assistant.io/integrations/epson :
SUPPORTED FEATURES
turn on/off
set input
set/get color mode
increase/decrease volume
mute/unmute audio
send next/previous track

**Comment by frenck** [comment]
> The documentation mentions other functions which i can;t see.

Home Assistant abstracts everything in "generic" entities. Regardless of the integration, everything can be controlled in a universal way. This is the whole goal of Home Assistant; regardless of the device/brand/manufacturer.

In this case, the Epson integration provides standard Media Player entities (as many other integrations provide too). How to use media player entities can be found in the media player documentation:

<https://www.home-assistant.io/integrations/media_player>
