### ISSUE TITLE
Gaviota motors

### ISSUE THREAD

**Issue by rauloraulon** [home-assistant/home-assistant.github.io#22497]
### Feedback

The integración woks for me with spanish Gaviota motors with Connect module 

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2022.4.6

**Comment by klaasnicolaas** [comment]
Then I would say make a pull request and add `Gaviota motors` to the list 😉

**Comment by starkillerOG** [comment]
@rauloraulon thanks for the feedback, I have made a PR to include this brand in the list: https://github.com/home-assistant/home-assistant.io/pull/22555

If you experiance any problems with the integration please let me know.
