### ISSUE TITLE
Nest integration not possible

### ISSUE THREAD

**Issue by michaelsterk** [home-assistant/home-assistant.github.io#22506]
### Feedback

![image](https://user-images.githubusercontent.com/73427969/164982084-602297f3-8115-4086-ac7a-51efa4751351.png)

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.4.6

**Comment by allenporter** [comment]
Duplicate Issue [#67662](https://github.com/home-assistant/core/issues/67662)
