### ISSUE TITLE
Musiccast

### ISSUE THREAD

**Issue by CharlesGitHib** [home-assistant/home-assistant.github.io#22500]
### Feedback

This code works , it will be a good example to help the guys that were like me trying to make this works. Just in case you guys want to share it and add it to the documentation.

entities:
  - type: custom:mini-media-player
    group: true
    entity: media_player.main_device
    toggle_power: false
    artwork: cover
    artwork_border: true
    power_color: true
    show_source: true
    sync_volume: true
    expanded: true
    speaker_group:
      platform: media_player
      show_group_count: true
      entities:
        - entity_id: media_player.kitchen
          name: Link Kitchen
        - entity_id: media_player.master_bedroom
          name: Link Master Bedroom
        - entity_id: media_player.office
          name: Link Office
        - entity_id: media_player.main_device_zone2
          name: Link Patio
  - type: custom:mini-media-player
    entity: media_player.kitchen
    group: true
    toggle_power: false
  - type: custom:mini-media-player
    entity: media_player.master_bedroom
    group: true
    controls: true
    toggle_power: false
  - type: custom:mini-media-player
    entity: media_player.office
    group: true
    toggle_power: false
  - type: custom:mini-media-player
    entity: media_player.main_device_zone2
    name: Patio (Zone 2)
    group: true
    toggle_power: false

### URL

https://www.home-assistant.io/integrations/yamaha_musiccast/

### Version

2022.4.6

**Comment by klaasnicolaas** [comment]
👋🏻 Heey @CharlesGitHib

Thanks for your documentation feedback, these kind of custom code examples belong more in a topic on the [community forum](https://community.home-assistant.io). So please share it there 😄 ❤️

**Comment by micha91** [comment]
As the mini-media-player isn't part of Home Assistant itself (it is a custom component), we do not support it officially - it is more  the mini-media-player that supports our grouping services.
I like the idea to post this to the community forum, but I think it could also be added to the documentation of the [mini-media-player](https://github.com/kalkih/mini-media-player) itself. This way it would be visible whenever someone installs it from HACS.

**Comment by CharlesGitHib** [comment]
Ok , will do. Thanks 👍🏼

**Comment by CharlesGitHib** [comment]
Sounds good to me. Have a good one.  Yes, I forgot that, that I download it ftom HACS. 👍🏼
