### ISSUE TITLE
Difficult to install on Home Assistant OS

### ISSUE THREAD

**Issue by benbunk** [home-assistant/home-assistant.github.io#22515]
### Feedback

This add-on appears to be part of Core Home Assistant but it doesn't seem to be usable using Home Assistant OS it would be good to indicate it's not compatible or update the description with details of how to use it with this common installation type. 

### URL

https://www.home-assistant.io/integrations/pandora/

### Version

2022.4.7

**Comment by frenck** [comment]
You are right, this is not compatible with Home Assistant OS, Container or Supervised installation and would need a note.

Feel free to open up a PR to add it! 👍
