### ISSUE TITLE
Auto discovery of my Insteon devices was not complete

### ISSUE THREAD

**Issue by dsfarkas** [home-assistant/home-assistant.github.io#22511]
### Feedback

My Insteon 2245-222 hub has 30 devices in its database.  I am trying various home automation tools to replace connect.insteon.com now that Insteon has decided to screw their thousands of users.  Home-Assistant only shows 22 devices out of the 30.  Should I remove the integration and re-install it to try and get the other 8 devices to be found?

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.4.7

### Additional information

Other home automation tools like HOOB and openHAB found all 30 devices, but they don't report the type of device, just the last six characters of the MAC address of the devices.

**Comment by dsfarkas** [comment]
I now know what the difference is between HOOBS and Home Assistant Insteon plugins.  HOOBS retrieves all devices in the Insteon database, active or inactive.  Home Assistant only displays the active devices.  My 2245-222 has 31 devices (I did a manual add of a device as a test), but only 23 are currently powered.  I unplugged the one I manually added and there are 7 others that are not presently used (Christmas lights and other devices).  Therefore, the 23 reported by Home Assisstant is accurate, just not a complete reporting of the database within the 2245-222 hub.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation suggestions, not for support questions.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
