### ISSUE TITLE
authentication error no 2fa belgium

### ISSUE THREAD

**Issue by ityzhome** [home-assistant/home-assistant.github.io#22513]
### Feedback

hi just installed for the 1 time ha 
tried the verisure plugin but doesnt recognise my login

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2022.4.7

### Additional information

from belgium hue integration alexa .. work fine only that one give issue

can login on verisure ni issuea

**Comment by klaasnicolaas** [comment]
Hi there @ityzhome 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
