### ISSUE TITLE
Google maps option to choose language

### ISSUE THREAD

**Issue by Aleks130699** [home-assistant/home-assistant.github.io#22520]
### Feedback

I would like to be able to select the language for receiving data when obtaining location data through Google maps so that the address information is not in English, but in the native language for each user

### URL

https://www.home-assistant.io/integrations/google_maps/

### Version

2022.4.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
