### ISSUE TITLE
Clarification on SQLalchemy entry

### ISSUE THREAD

**Issue by bengAThome** [home-assistant/home-assistant.github.io#22529]
### Feedback

The entry currently states:

> 
Although SQLAlchemy supports additional database solutions, it will behave differently on different databases, and features relied on by the recorder may work differently, or not at all, in different databases.

Which I suggest could be changed to:

> 
Although SQLAlchemy supports additional database solutions other than the ones listed here, it will behave differently on different databases, and features relied on by the recorder may work differently, or not at all, in different databases.

This will remove any ambiguity that the "additional database" are referring to the three listed other than the default SQLite. Thanks.

### URL

https://www.home-assistant.io/integrations/recorder/

### Version

2022.4.7

**Comment by frenck** [comment]
> This will remove any ambiguity that the "additional database" are referring to the three listed other than the default SQLite.

Is it an ambiguity? SQLAlchemy can work with many other databases.

**Comment by emontnemery** [comment]
I think the proposed change is good, it can't hurt to be more clear 👍

**Comment by bengAThome** [comment]
Thanks Franck,
When I read it, it made me unsure if all 4 were fully supported, or if I
chose one of the others over SQLite, I might be giving up some
functionality.
I appreciate your time.

Cheers Ben
