### ISSUE TITLE
Art Mode on Samsung TV

### ISSUE THREAD

**Issue by TheBartoMan** [home-assistant/home-assistant.github.io#22523]
### Feedback

Can the integration please identify if the Samsung TV is in Art Mode or not?

Other Systems can do this, but I can find a way to do it in Home Assistant?

example https://github.com/tavicu/homebridge-samsung-tizen#readme

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2022.4.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
