### ISSUE TITLE
DLNA

### ISSUE THREAD

**Issue by xuzuxiong** [home-assistant/home-assistant.github.io#22525]
### Feedback

Why is the latest version of homeassistant DLNA entity unavailable
Why is the latest version of homeassistant DLNA entity unavailable
Why is the latest version of homeassistant DLNA entity unavailable

### URL

https://www.home-assistant.io/integrations/dlna_dmr/

### Version

2022.4.7

### Additional information

Why is the latest version of homeassistant DLNA entity unavailable
Why is the latest version of homeassistant DLNA entity unavailable
Why is the latest version of homeassistant DLNA entity unavailable

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
