### ISSUE TITLE
Example for homeatic.keypress event doesn´t work for me

### ISSUE THREAD

**Issue by MaDtz** [home-assistant/home-assistant.github.io#22522]
### Feedback

I build an automation with the homeatic.keypress-event as a trigger. I had that automation working for month, and suddenly, a few weeks ago, it stopped working, without changing anything. As I made a new HA-installation from the sratch, I tried again to get the automation to work, according to the dokumentation with no success. Thanks to the [help in the community](https://community.home-assistant.io/t/homematic-keypress-event-doesn-t-trigger-my-automation/415535) I solved the problem. The example for event_data in the dokumentation... 

`automation:
   trigger:
     platform: event
     event_type: homematic.keypress
     event_data:
       name: "Kitchen Switch"
       channel: 1
       param: PRESS_SHORT
   action:
     service: switch.turn_on
     target:
       entity_id: switch.Kitchen_Ambience`

... doesn´t work for me (don´t know if it´s a global problem).

So in my case the trigger is only working with this event_data-code:
`event_data:
  address: 00085BE9A3B1BA
  type: press_long
  subtype: 2`

### URL

https://www.home-assistant.io/integrations/homematic/#events

**Comment by danielperna84** [comment]
You did mention in the thread, that you are using the __new__ custom integration. Therefore the documentation for the __old__ integration does not apply for you anymore. This repository holds the _official_ documentation, which is the __old__ integration.

[Here](https://github.com/danielperna84/custom_homematic#devices-with-buttons) is the part that is relevant for you.
