### ISSUE TITLE
integrations nextcloud error

### ISSUE THREAD

**Issue by transcendence-x** [home-assistant/home-assistant.github.io#22536]
### Feedback

Logger: homeassistant.setup
Source: components/nextcloud/__init__.py:105 
First occurred: 17:16:33 (1 occurrences) 
Last logged: 17:16:33

Error during setup of component nextcloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/nextcloud/__init__.py", line 105, in setup
    hass.data[DOMAIN] = get_data_points(ncm.data)
UnboundLocalError: local variable 'ncm' referenced before assignment

Logger: homeassistant.components.nextcloud
Source: components/nextcloud/__init__.py:103 
Integration: nextcloud (documentation, issues) 
First occurred: 17:16:33 (1 occurrences) 
Last logged: 17:16:33

Nextcloud setup failed - Check configuration

### URL

https://www.home-assistant.io/integrations/nextcloud/

### Version

2022.2.3

**Comment by meichthys** [comment]
@chaoqunxie  how did you install the nextcloud integration? Are you running HA core? 

I need a bit more information.

The error odd indicating that the underlying dependency is not installed or working, but we haven't had any reports of this in the past.

**Comment by transcendence-x** [comment]
> @chaoqunxie 你是如何安装 nextcloud 集成的？你在运行 HA 核心吗？
> 
> 我需要更多信息。
> 
> 奇怪的错误表明基础依赖项没有安装或工作，但我们过去没有任何报告。

i used openssl 

i change /usr/local/lib/python3.9/site-packages/nextcloudmonitor.py

response = requests.get(self.api_url, auth=(self.user, self.password)**, verify=False**)

is ok ,thank u reply

**Comment by meichthys** [comment]
OpenSSL shouldn't cause an issue as far as I know. I'm also using ssl and it works fine. Are you running HA core?

**Comment by transcendence-x** [comment]
HA core is running

![Uploading 92C3D37B-59F7-4DEA-AC01-4B6917CC23ED.png…]()

**Comment by meichthys** [comment]
What does 'ha supervisor' show?

Does this package work for you if you follow the QuickStart section?

https://pypi.org/project/nextcloudmonitor/

**Comment by transcendence-x** [comment]
When i am in docker container , curl https://my server  

curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above

when i open in brower ,page show:

Your connection is not private
An attacker may attempt to remove the …… steals your information (e.g. password, communication content or credit card information

**Comment by meichthys** [comment]
It looks like your OpenSSL cert is mos configured for your nextcloud.

**Comment by transcendence-x** [comment]
My OpenSSL config error?

**Comment by transcendence-x** [comment]
i config ssl for nginx

**Comment by meichthys** [comment]
Currently this integration does not support Nextcloud instances that do not run on SSL. I submitted a pull request to enable that option but was denied because this integration does not have a web UI 'config_flow':

https://github.com/home-assistant/core/pull/55433

**Comment by meichthys** [comment]
@ludeeus 
Could we get #55433 merged? Or could we get some help converting the nextcloud integration over to a config flow?

**Comment by transcendence-x** [comment]
i use nginx proxy Nextcloud ,Nextcloud is http, nginx is https 

as u said The problem is Nextcloud not used https

thank u again

**Comment by transcendence-x** [comment]
> @ludeeus
> 我们可以实施#55433吗？或者我们可以得到一些帮助，将下一个云集成转换为配置流？

I will test tomorrow ,i should have dinner with my wife

**Comment by frenck** [comment]
Hi there @chaoqunxie 👋 

It seems like you want to report an issue with an Home Assistant integrations, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix such an issue.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by meichthys** [comment]
Hi @frenck , I'm the maintainer of this integration and there actually is an issue with the integration itself - it is broken for nextcloud instances that don't support ssl. I submitted a fix for it (https://github.com/home-assistant/core/pull/55433) but it was denied since the integration doesn't yet support a ConfigFlow :/

**Comment by frenck** [comment]
> I'm the maintainer of this integration and there actually is an issue with the integration itself 

Cool, but this is not the issue tracker for that. Please use the core issue tracker for tracking issues. Thanks 👍

**Comment by meichthys** [comment]
The merge request was closed based on the following line in: https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md
`Changes to existing YAML configuration for these same existing integrations, will no longer be accepted.`
This makes sens for future `changes`, but does this also include `fixes` like https://github.com/home-assistant/core/pull/55433?

**Comment by meichthys** [comment]
Ah. i see This is on the docs repo. sry.
