### ISSUE TITLE
Docker on a MAC --net=host does not work

### ISSUE THREAD

**Issue by Medicalmusings** [home-assistant/home-assistant.github.io#22534]
### Feedback

There seems to be a major issue with docker on a MAC that host networking ie --net=host DOES NOT WORK on docker for mac. This isnt a home assistant issue per say but might be worth adding a warning of this on this homeassistant page to save people time trying!

For one of many commentaries see https://stackoverflow.com/questions/55851632/docker-compose-network-mode-host-not-working

### URL

https://www.home-assistant.io/integrations/discovery/

### Version

2022.4.7

**Comment by frenck** [comment]
That is correct, it is a limitation of Docker Desktop for Mac.

See also: <https://docs.docker.com/network/host/>

I'm not sure what the suggestion/issue is you are trying to raise?

**Comment by Medicalmusings** [comment]
I accept that it doesn’t work but could that fact PLEASE be added to the DOCUMENTATION to save others (like me) hours of frustration.

Please?
