### ISSUE TITLE
Clarify difference between OS and Core

### ISSUE THREAD

**Issue by jonselin** [home-assistant/home-assistant.github.io#22535]
### Feedback

After finding this page from an external site, it was not clear that there was a difference between Operating System vs Core. Core being different and not having the required functionality was only discovered after going through the lengthy installation process.

### URL

https://www.home-assistant.io/installation/windows/

### Version

2022.4.7

**Comment by frenck** [comment]
This is our main installation page: <https://www.home-assistant.io/installation/>

Which is linked from our main website and the main menu everywhere. It provides a description between the differences and a comparison table:

<https://www.home-assistant.io/installation/#compare-installation-methods>

Could you point me out / provide an example of what is missing on those pages?

**Comment by jonselin** [comment]
You're correct at that this information exist, this is just an issue with people sometimes not going through the intended flow and missing critical information. I ended up on the windows install page either by finding the link on some reddit guide or by googling it (can't remember which), not by going through the flow that you would hope people go through. I did find the pages you linked later when I realized I had a problem. This could be helped by e.g. putting a link to the compare-installation-page at the top of all the platform sup pages (windows, macOS, etc).

**Comment by frenck** [comment]
So, I get the idea, but... I also think anyone can land on any page everywhere. We will never be able to provide full context on every single page. (Well unless we merge ALL or documentation in a single page 😓 )

But this might be a exceptional case indeed 🤔

**Comment by jonselin** [comment]
It's just feedback based on my experience, do with it what you will ;)
