### ISSUE TITLE
Documentation feedback template

### ISSUE THREAD

**Issue by bengAThome** [home-assistant/home-assistant.github.io#22531]
### Feedback

This submission form states:

> Version
Current version of the documentation. This usually matches the Home Assistant Core release version, and can be found at the bottom of the page.

However the current version only seems to be on the home page:

> https://www.home-assistant.io/

If you look at any of the subsequent pages they do not have the version on them.

### URL

https://www.home-assistant.io/

### Version

2022.4.7

**Comment by bengAThome** [comment]
Issue is still exactly as reported.

**Comment by frenck** [comment]
Thanks, @bengAThome 👍 
I've opened up a PR to adjust the feedback template.

../Frenck
