### ISSUE TITLE
Provide example with "retaining state"

### ISSUE THREAD

**Issue by gabrielke** [home-assistant/home-assistant.github.io#22544]
### Feedback

Please provide explanation (and maybe example) how to refer to a sensor's previous value in a value template (if possible?)
This would be extremely useful for "virtual sensors" definition like for "maximum temperature" or "maximum power".

### URL

https://www.home-assistant.io/integrations/template/

**Comment by frenck** [comment]
You can access the state of any entity using templates, for reference see our templating documentation here: <https://www.home-assistant.io/docs/configuration/templating/#states>
