### ISSUE TITLE
delete all option

### ISSUE THREAD

**Issue by stamandr** [home-assistant/home-assistant.github.io#22541]
### Feedback

Integration needs a delete all option at the main page, so that you can delete everything if you need to start over. 

### URL

https://www.home-assistant.io/integrations/generic/

### Version

2022.4.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by davet2001** [comment]
Hi @stamandr, I understand that 'delete all' would save some time if that's what the user wanted to do.

However:
1. You have submitted this to the documentation(/web site) issue tracker.  A change to functionality should be raised as an issue or discussion point on the core or architecture repository.
2. I don't think it is a very common use case.  You can delete them one by one already.
3. If a 'delete all instances of this integration' feature is added to the integrations page, it should be a more general one that would work with other integrations (e.g. esphome), not just the generic (camera) integration.

**Comment by stamandr** [comment]
Hi, Thanks for the response. The "delete all" would be extremely valuable to people that have dozens of cameras (like myself). It takes me almost 20 minutes to delete all and start over. I noticed that the Mobile App, and TP Link Casa Smart are the same. How do you recommend that I proceed to get this considered, and possibly added  in the future ?

**Comment by davet2001** [comment]
As above, [Community forum: Feature requests](https://community.home-assistant.io/c/feature-requests) is the place.

**Comment by stamandr** [comment]
got it... Thanks
