### ISSUE TITLE
slimproto - Misuse of Logitech Media Server Logo

### ISSUE THREAD

**Issue by rosscullen** [home-assistant/home-assistant.github.io#22546]
### Feedback

Integration slimproto uses the Logitech Media Server (LMS) icon/logo. From what I can make out, slimproto is an alternative to LMS, as oppose to compimentary/enhancement. Please consider reviewing.

### URL

https://rc.home-assistant.io/integrations/slimproto

### Version

2022.05b

**Comment by frenck** [comment]
I think it is correct, the slim protocol is developed by/from/for the squeezebox and is not independent. It has been adopted by others, but its origin is slim devices (aka Sqeeuzebox).
