### ISSUE TITLE
Clarify slim_proto cannot be used with squeezebox integration

### ISSUE THREAD

**Issue by nickrout** [home-assistant/home-assistant.github.io#22548]
### Feedback

I think the docs should make it clear that you cannot use slimproto and squeezebox at the same time (per the commit discussion here https://github.com/home-assistant/core/pull/70444#issuecomment-1107436018

And the squeezebox docs should also mirror that.

### URL

https://www.home-assistant.io/integrations/slimproto/

### Version

2022.5.0b0

**Comment by marcelveldt** [comment]
Do you have something in mind ?

**Comment by frenck** [comment]
> I think the docs should make it clear that you cannot use slimproto and squeezebox at the same time

You can actually? What is the limiting factor?

**Comment by marcelveldt** [comment]
Suggestion:

NOTE for existing Squeezebox users
A squeezebox player can only be connected to one server at a time. So, if you already have a Logitech Media Server running in your network, you either need to shutdown that server or instruct the player to connect to the IP of Home Assistant

**Comment by frenck** [comment]
Aah right doh 🤦

**Comment by marcelveldt** [comment]
> You can actually? What is the limiting factor?

You can use both integrations at the same time, no problem. Question is which "server" the player will prefer and connect to
