### ISSUE TITLE
Netlify logo broken in README

### ISSUE THREAD

**Issue by wrt54g** [home-assistant/home-assistant.github.io#22559]
### Feedback

The Netlify logo in the README file is broken. The image does not exist anymore.

### URL

The README file

**Comment by dannytsang** [comment]
It looks ok to me.
![image](https://user-images.githubusercontent.com/567982/166109676-ff7ead63-1dad-472f-8d18-ca18df7969a7.png)

**Comment by frenck** [comment]
Yup same here:

<img width="401" alt="CleanShot 2022-04-30 at 16 57 39@2x" src="https://user-images.githubusercontent.com/195327/166110705-fd74650d-cda5-4bac-9e78-3bad51b8565c.png">
