### ISSUE TITLE
Coinbase no longer seems to supply "secret"

### ISSUE THREAD

**Issue by luxpistol** [home-assistant/home-assistant.github.io#22552]
### Feedback

In following many tutorials & the Coinbase official integration page on the HA website, I cannot get past the point where I'm required to enter a "secret" code from Coinbase.

This doesn't prove to be something that Coinbase supplies now when setting up an API. 

Unless there's a way to activate it which isn't communicated anywhere that I've looked?

Does the Coinbase integration need to be updated to accept only the API key?

### URL

https://www.home-assistant.io/integrations/coinbase/

### Version

2022.4.7

**Comment by TomBrien** [comment]
Hi @luxpistol as best I can tell this is an issue on Coinbase's side with them not showing the modal with the secret at the end of the API key creation. There is no documented change in their docs to suggest the authentication method has been changed, nor does there appear to be a new API version released. I guess it's some error by their web team. I'll keep an eye on it and nudge them if not addressed soon

**Comment by TomBrien** [comment]
I've checked again and it does appear Coinbase have now fixed this and the modal shown after creating the API key includes the secret again.
