### ISSUE TITLE
documentation fix

### ISSUE THREAD

**Issue by SerdarSanri** [home-assistant/home-assistant.github.io#22562]
### Feedback

AWS free tier is only for the first year.

### URL

https://www.home-assistant.io/integrations/alexa/

### Version

2022.4.7

**Comment by dannytsang** [comment]
@SerdarSanri it mentions the Lambda pricing on the third bullet point in the requirements section:
![image](https://user-images.githubusercontent.com/567982/169154964-80aed601-2688-425b-9830-3db851f7cba9.png)

Is there something else you want to see changed to make it clearer?

**Comment by SerdarSanri** [comment]
Ah sorry, yes from last time I used AWS lambda free tier was only for first 12 months then regular pricing but it looks like it is now always free in those limits.
