### ISSUE TITLE
Tropical Season

### ISSUE THREAD

**Issue by AeroV95** [home-assistant/home-assistant.github.io#22577]
### Feedback

Hello, 

I wanted to know if this can be tweaked to show only winter and season for tropical climates?

### URL

https://www.home-assistant.io/integrations/season/

### Version

2022.4.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
