### ISSUE TITLE
PIN code cannot be "0000"

### ISSUE THREAD

**Issue by J-Ubeda** [home-assistant/home-assistant.github.io#22587]
### Feedback

When trying to activate the worxlandroid sensor platform, be sure you have changed the default PIN code on the robot.

The configuration yaml gives the following error if pincode is "0000":

Not valid configuration:
Invalid config for [sensor.worxlandroid]: does not match regular expression \d{4} for dictionary value @ data['pin']. Got 0. (See ?, line ?).

### URL

https://www.home-assistant.io/integrations/worxlandroid/

### Version

2022.4.7

**Comment by frenck** [comment]
Hi there @J-Ubeda 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by J-Ubeda** [comment]
Not exactly, i wanted to add information for manual:

for a correct connection to Home assistant the pin of worx robot cannot be "0000" (default pin when buyed).

I don't know if this is a bug or a security requirement.
________________________________
De: Franck Nijhof ***@***.***>
Enviado: lunes, 2 de mayo de 2022 11:48
Para: home-assistant/home-assistant.io ***@***.***>
Cc: Francisco Javier Ubeda Moret ***@***.***>; Mention ***@***.***>
Asunto: Re: [home-assistant/home-assistant.io] PIN code cannot be "0000" (Issue #22587)


Hi there @J-Ubeda<https://github.com/J-Ubeda> 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

https://github.com/home-assistant/core/issues

Thanks! 👍

../Frenck

**Comment by frenck** [comment]
It's a bug, please report it in the issue tracker linked above.
