### ISSUE TITLE
Struggling with the modern configuration of template sensors

### ISSUE THREAD

**Issue by smarthomejunkie** [home-assistant/home-assistant.github.io#22583]
### Feedback

I migrated all my “old style” sensors to the modern way in a templates.yaml, but really miss the possibility to add a friendly_name.
I created a naming convention for all my entities like

<room>_<domain>_<position in the room>

but that is seldom a friendly name.

For instance, the entity_ID could be “livingroom_light_couch”, but the friendly name would be “Couch lamp”.

I cannot add the friendly name to the entity in the generated entity afterwards, so I am stuck here. 🤷🏼

### URL

https://www.home-assistant.io/integrations/template/

### Version

2022.4.7

**Comment by frenck** [comment]
`name` is the replacement of `friendly_name`: <https://www.home-assistant.io/integrations/template/#name>

It is actually the exact same parameter (just the key changed...)

Code reference: <https://github.com/home-assistant/core/blob/dev/homeassistant/components/template/template_entity.py#L95>

If you want to go the YAML-only route, the way to handle these cases (from back in the day) is using the customize feature of Home Assistant. However, I would recommend setting a unique ID instead (ref: <https://www.home-assistant.io/integrations/template/#unique_id>), which would unlock all these customization capabilities (and more) straight from the frontend.

../Frenck

**Comment by smarthomejunkie** [comment]
Hi @frenck Thanks for responding. What I see in my test is that name is indeed the same as Friendly name, but name is also used to create the Entity-id with underscores instead of spaces. That means that I cannot make a difference between the Friendly Name and the Entity Id and that is exactly what I want. (see my example)

I understand that I can generate a unique id and use this in my template so that I can change it in the UI, but it feels like a workaround to me to do this. It seems odd that I have to go to a site like https://www.uuidgenerator.net/ to generate a unique id and then add that unique id to my template. (I can also use the entity_id as a unique id I guess, but that's not what I think that a unique id should be.)

Or am I seeing this totally wrong?

**Comment by frenck** [comment]
Entity IDs an names are not considered stable factors. Both are customizable and manageable by the end user. Names are used for displaying in the frontend, while entity IDs are used in e.g., YAML automations.

As both are end-user facing and customizable; they are not fit as a stable identifier; this is what unique ID is for. It identifies an object, regardless of its name or entity ID (even when changed).

An entity ID is always generated from the name of an entity the first time. This is not specific to templates, it is how Home Assistant entities work.

**Comment by smarthomejunkie** [comment]
Okay @frenck, thank you for this explanation. It's clear to me. 🙏🏻
