### ISSUE TITLE
How to check if sun is shining then close the slats

### ISSUE THREAD

**Issue by rdrieenh** [home-assistant/home-assistant.github.io#22597]
### Feedback

Now the sun is up very early I want to automate the closure of the slats.
This is only required when the sun is shining. So the local wheater condition must help here.
How can this be done ?

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2022.4.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
