### ISSUE TITLE
Where are the working examples????

### ISSUE THREAD

**Issue by kevintedder** [home-assistant/home-assistant.github.io#22593]
### Feedback

Can you please provide working examples as to how to configure this device in the  Configuration.yaml file.

I've  started with -

number:
    <what's next>  the studio code editor complains about everything else I enter after this.

### URL

https://www.home-assistant.io/integrations/number/

### Version

2022.4.7

**Comment by frenck** [comment]
There is none, `number` is an entity component integration that can be used by other integration to provide. They cannot be created yourself.

If you are looking for a manual alternative, look at the number helper.

<https://www.home-assistant.io/integrations/input_number>

../Frenck
