### ISSUE TITLE
ezviz

### ISSUE THREAD

**Issue by shemtov-m** [home-assistant/home-assistant.github.io#22603]
### Feedback

Hello, it is not possible to register from the integration, there is a situation where the problem is fixed

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2022.4.7

**Comment by frenck** [comment]
Hi there @shemtov-m 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. If you want to report an issue with an integration, please do so here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
