### ISSUE TITLE
Actionable notifications not working on Apple Watch

### ISSUE THREAD

**Issue by refaelsommer** [home-assistant/home-assistant.github.io#22611]
### Feedback

Hello guys,

I created a actionable notification, it works perfect 100% of the times on the iPhone, but when tapping the action on the Apple Watch, it does not work, sometimes it works after like a minute!

I tested a way that the Apple Watch always works, and that’s when opening the iPhone app, if the HA app is open while tapping an actionable notification button, then it fires instantly.

Please try to fix this issue since I have great plans on this feature.

Seems like the Apple Watch actionable notification does not wake up the iPhones app to fire the event or something…

I am an iPhone developer, so feel free to ask more details if needed, I can try to provide anything you need.

Thanks!
Refael.S

Sent from my iPhone

### URL

https://www.home-assistant.io/help/reporting_issues/

### Version

2022.3

**Comment by frenck** [comment]
Hi there @refaelsommer 👋 

It seems like you want to report an issue with our Home Assistant iOS app, however, you have submitted documentation feedback instead. Please report issues with our iOS app here:

<https://github.com/home-assistant/iOS/issues>

Thanks! 👍 

../Frenck

**Comment by refaelsommer** [comment]
ok thanks
