### ISSUE TITLE
Integration installation error

### ISSUE THREAD

**Issue by dgarimoldi** [home-assistant/home-assistant.github.io#22626]
### Feedback

After doing all the described steps, when I click on ADD INTEGRATION and try to add the HOME CONNECT, I get following error:

{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmbG93X2lkIjoiZDU5Y2Y5YzEzM2Q5MzMwZDVkOTM3ZGJhYjlmNzY4YzkiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL3NjcmF0dGVlc2NyYXQuZHVja2Rucy5vcmc6ODEyMy9hdXRoL2V4dGVybmFsL2NhbGxiYWNrIn0.1xipw2Ewx4mtLwD4dz9WYS5uq4nqB0tbX3toAdVeiGw"
}

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2022.4.7

**Comment by frenck** [comment]
> "error_description": "client or redirection URI not authorized",

That means the redirect URI on the application you managed @ Home Connect isn't correctly configured.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
