### ISSUE TITLE
"Unexpected Error"

### ISSUE THREAD

**Issue by PaulJoosten** [home-assistant/home-assistant.github.io#22638]
### Feedback

The integration of my HWE P1 dongle has worked flawlessly for quite some time. Recently there were some problems (maybe to do with some HASS update?) and I decided to delete the integration and set it up again. After a restart, the integration was rediscovered OK but when I tried to set it up I got a popup screen saying "Unexpected Error".

The P1 dongle works OK as the HWE app on my smartphone properly shows the current (no pun intended) situation. What can be the problem and how can I solve this? 

### URL

https://www.home-assistant.io/integrations/homewizard/

### Version

2022.5.0

**Comment by DCSBL** [comment]
I think this is the wrong repo for this issue. You should open an issue in [home-assistant/core](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml).

But I think this is related to https://github.com/home-assistant/core/issues/66669. Try to powercycle your P1 meter.

**Comment by frenck** [comment]
Hi there @PaulJoosten 👋 

DCSBL is right, in his response. It seems like you want to report an issue, but you have submitted documentation feedback instead. Please report issues here:

<https://github.com/home-assistant/core/issues>

(Or it might just be resolved with the suggestion to power cycle the P1 meter).

../Frenck

**Comment by PaulJoosten** [comment]
Sorry guys, I'm not so tech-savvy, more like a monkey looking into the proverbial rusty watch. I did powercycle my modem, my HASS machine but never thought about the dongle itself. Glad to let you know that solved the problem. Feel free to delete inappropriately placed responses. THANKS!!

**Comment by frenck** [comment]
> Sorry guys, I'm not so tech-savvy,

Don't worry! We just try to help you out and redirect you to the right places :)

> Glad to let you know that solved the problem.

Awesome 💪 

> Feel free to delete inappropriately placed responses.

No need to 👍  Nothing bad happened 😄

**Comment by DCSBL** [comment]
@PaulJoosten No worries. I've bumped this issue to the P1 meter developers.
