### ISSUE TITLE
Phanton entities

### ISSUE THREAD

**Issue by ustrucx** [home-assistant/home-assistant.github.io#22632]
### Feedback

Many instructions online say "tryout this sensor, paste this to your config.yaml!" but they never mention that once certain things are pasted in there they will be there forever, example:

```
binary_sensor:
    platform: ping
    host: 192.168.15.65
```
For all I know, even now having removed these lines from my config.yaml I will never be able to get rid of it, ever. Having deleted those lines makes it uneditable now so it is plain useless, taking space and taunting me each time I look at the entities list. 

If it is possible to remove such things without risking damaging the installation I believe it would be beneficial to have that info readily available on this page, if it is not possible to remove, some sort of warning could be given like "if you create a sensor without X (unique Hass-like ID?) you will be long dead and that failed entity will still be there! :D

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2022.5.0

**Comment by frenck** [comment]
> you will be long dead and that failed entity will still be there! :D

When you open the entity that is no longer being provided (orphaned), a delete button is shown on the entity dialog.
