### ISSUE TITLE
Adress unknown

### ISSUE THREAD

**Issue by pfwolbers** [home-assistant/home-assistant.github.io#22633]
### Feedback

My Twente milieu always say "adres unknown".
I've tested my current address and my parents address. 
When I login into the Twente milieu app itself the addresses are known and working.
It has worked before.

### URL

https://www.home-assistant.io/integrations/twentemilieu/

### Version

2022.5.0

**Comment by frenck** [comment]
Hi there @pfwolbers 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
