### ISSUE TITLE
history_stats - No longer works

### ISSUE THREAD

**Issue by neildsb** [home-assistant/home-assistant.github.io#22640]
### Feedback

Integration no longer works in 2022.5.0 code has not changed or been updated , unavailable result
![image](https://user-images.githubusercontent.com/91122872/166887385-ff3c669b-84ed-4ccb-9298-211877327051.png)

### URL

https://www.home-assistant.io/integrations/history_stats/

### Version

2022.5.0

**Comment by frenck** [comment]
Hi there @neildsb 👋 

It seems like you want to report an issue with Home Assistant, however, you have submitted documentation feedback instead. Please report issues here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
