### ISSUE TITLE
Diaz

### ISSUE THREAD

**Issue by XanderXVD** [home-assistant/home-assistant.github.io#22654]
### Feedback

also work with Diaz (app bi by diaz)

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2022.5.1

**Comment by starkillerOG** [comment]
@XVD-XVD thanks for your feedback!
I added Diaz to the supported list on the library and in the HomeAssistant Documentation (https://github.com/home-assistant/home-assistant.io/pull/22666)

If you experiance any problems or have issues, please let me know.
If you appriciate the motion blinds integration, consider sponsoring the library: https://github.com/starkillerOG/motion-blinds
