### ISSUE TITLE
switch: power consumption not avail. anymore

### ISSUE THREAD

**Issue by bsbebbi** [home-assistant/home-assistant.github.io#22659]
### Feedback

the documentation explains how power consumption can be extracted from the mystrom-switch.
This is not working anymore.
My guess is that the reason is
 _Remove energy usage from the switch base class #68821_
[https://github.com/home-assistant/core/pull/68821](https://github.com/home-assistant/core/pull/68821)

### URL

https://www.home-assistant.io/integrations/mystrom/

### Version

2022.5.0

**Comment by eili77** [comment]
facing same issue, as reported by @bsbebbi
