### ISSUE TITLE
Wont connect to account

### ISSUE THREAD

**Issue by Oumpa31** [home-assistant/home-assistant.github.io#22651]
### Feedback

August wont connect to account no matter how you try to log in. 

### URL

https://www.home-assistant.io/integrations/august/

### Version

2022.5.1

**Comment by klaasnicolaas** [comment]
Hi there @Oumpa31 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
