### ISSUE TITLE
Second energy animated graph

### ISSUE THREAD

**Issue by jjtoard** [home-assistant/home-assistant.github.io#22658]
### Feedback

Hi,

I'm bringing part off my electric installation to an off grid setup.  It would be nice if I could also represent this in home assistant to a second animated energy graph (net, solar, home, fossile)

Would it be possible to create such a second graph ?

I can imagine that people having a second home could also benefit from this.

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2022.5.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
