### ISSUE TITLE
Unsupported -> dns server docs not accurate

### ISSUE THREAD

**Issue by jds11111** [home-assistant/home-assistant.github.io#22665]
### Feedback

My hassos installation is showing as unsupported because of dns server. I have disabled the fallback server. I run the check from cli 'ha resolution info'. It says that there are two problems 'dns_server_failed' and 'dns_server_ipv6_error'. The docs say certain things to check. My dns server complies with all of these. I even whitelisted the suggested address in pihole to be sure. I can ping it from hassos cli. 

There is a suggested check for the second error. Both of those return NOERROR. Nonetheless, my setup is still listed as unsupport.

### URL

https://www.home-assistant.io/more-info/unsupported/dns_server/

### Version

2022.5.2

**Comment by frenck** [comment]
Disabling fallback support will render a system in an unsupported state.

Enabling it using `ha dns options --fallback=true` will address that.
