### ISSUE TITLE
Shelly Configuration: Entity Naming Errors

### ISSUE THREAD

**Issue by Richyread** [home-assistant/home-assistant.github.io#22664]
### Feedback

I recently added my first Shelly devices into HA - these are 2 x Shelly 1PM+ models and therefore 'Generation 2' as per the documentation and setup etc.

I had a few issues with my setup so on updating my HA to v2022.5.2 this morning I decided to delete these two switches, reboot my HA instance and go through the (updated) setup etc.

What I'm finding is that there is still a discrepancy/error between what the documentation suggest the Entity Name value should be identified as and what is actually happening;

For the GEN1 devices the documentation has a useful matrix showing the values that it should capture depending upon which fields within the Shelly device itself, have been set etc. 

According to the documentation, GEN2 devices should have the following simplified approach:

```
Entity naming (generation 2)
The integration uses the following strategy to name its entities:

If [Channel Name] is set in the device, the integration will use it to generate the entities’ name, e.g. Kitchen Light
If [Channel Name] is set to the default value, the integration will use the Device ID and default channel name to generate the entities’ name, e.g. ShellyPro4PM-9808D1D8B912 switch_0. 
```

However, from my limited testing on my devices, the key local field that determines the Entity Name is actually **[Device Name]** and not **[Channel Name]** as the documents suggest.
In fact it seems that setting a value for **[Channel Name]** has no obvious effect in terms of the values set into HA upon discovery/integration etc.

So upon initial discovery by HA, the following logic is applied:

> If [Device Name] not empty 
>THEN
>**Entity Name** = [Device Name]
>ELSE
>**Entity Name** = [Device ID]+[Default Channel Name]

Now of course whether this is the intended behaviour or not I can't say- it seems sensible to me to use the [Device Name] over the [Channel Name] value, but obviously there's many different factors and my small install obviously not a very large sample size/testing size etc.

But in summary, assuming that the latest change is the correct approach, then this is just a very minor tweak to the documents:

- On page: https://www.home-assistant.io/integrations/shelly
- Section: https://www.home-assistant.io/integrations/shelly#entity-naming-generation-2
- Replace  **[Channel Name]** with **[Device Name]**

However, if the intended behaviour is in fact that the **[Channel Name]** local field be used as the key for Entity Name (i.e. that the documentation is correct and the code is in error) then obviously this will need to be pushed over to the HA Core issues team.

Hope that makes sense!

### URL

https://www.home-assistant.io/integrations/shelly

### Version

2022.5.2

### Additional information

![2022-05-07 12_07_08-Settings – Home Assistant](https://user-images.githubusercontent.com/7470850/167251857-a504e697-6ed0-413e-a92c-12de7e6ab41d.png)

**Comment by Richyread** [comment]
This is the corresponding Shelly web portal for the example I used above.

![2022-05-07 12_15_39-Shelly Plus1PM](https://user-images.githubusercontent.com/7470850/167252000-6e6b1602-e0e9-4c62-9cf4-0d72e48482c6.png)

As you can hopefully see, even with the [Channel Name] value set, it is only what is listed within the [Device Name] field, that is transposed into HA for the Entity Name upon discovery.

**Comment by thecode** [comment]
Your picture shows the device and not the entities, click on the device to list the entities and add an updated picture.
This is an example from Shelly 2PM, I named the device "Kitchen Shutter" and the channel "Kitchen"
![image](https://user-images.githubusercontent.com/1858925/167252106-069e657f-7011-4ad3-a133-c41ab8ee9f92.png)

![image](https://user-images.githubusercontent.com/1858925/167252128-c90c5fe2-82c4-4057-80d1-d5af1a7b1afc.png)

**Comment by Richyread** [comment]
So in this instance I've set the [Channel Name] field:

![image](https://user-images.githubusercontent.com/7470850/167252408-fd277875-3257-4d4e-87e7-35ef3a8cba0a.png)

Yet upon discovery and integration into HA it uses the default values to register the Entity Name(shellyplus1pm-7c87ce643f3c):

![image](https://user-images.githubusercontent.com/7470850/167252305-e2b4685d-a5bf-49b3-b75e-8a0de73593b2.png)

**Comment by Richyread** [comment]
Actually.....forgive me am I perhaps looking at this the wrong way around? I expected the Entity Name to be driven by the Device Name, but looking at this maybe I have this incorrect?

**Comment by thecode** [comment]
I think you are confusing entities with device, these are entities:
![image](https://user-images.githubusercontent.com/1858925/167252614-77e3d729-0d63-4e6e-877c-287e76655561.png)
And their name match the one you set on the the channel name

This is a device:
![image](https://user-images.githubusercontent.com/1858925/167252629-9970ff45-b486-4bca-bbbb-8cfb1837d422.png)

Your device doesn't have a name set so the default device Shelly ID is used

**Comment by Richyread** [comment]
Ahh so it's my own logic that's wrong! 

Thanks for taking a look and I've clearly some reading up to do on Devices vs Entites.

Appreciate your time.

Richy,
