### ISSUE TITLE
Multiple trigger entities

### ISSUE THREAD

**Issue by nottledim** [home-assistant/home-assistant.github.io#22668]
### Feedback

It's not clear to me (from the docs) what happens when multiple entities are used in a trigger.  Is it triggered when any entity state changes (according to the restrictions) or when all have changed; is it AND or OR?

What's the difference between using multiple triggers or one trigger and multiple entities?

I think in highlighting qualifications (such as "the ID doesn't have to be unique...")  the basic operation  is overlooked.

### URL

https://www.home-assistant.io/docs/automation/trigger/

### Version

2022.5.2

**Comment by frenck** [comment]
> It's not clear to me (from the docs) what happens when multiple entities are used in a trigger. Is it triggered when any entity state changes (according to the restrictions) or when all have changed; is it AND or OR?

It will trigger on any of the entities listed. Triggers are single events. An event cannot happen on multiple entities at once; this can impossibly be `AND`.

I do agree this needs to be mentioned 👍 

> What's the difference between using multiple triggers or one trigger and multiple entities?

None, you just need fewer triggers (and thus less logic).

**Comment by frenck** [comment]
Just was reviewing the docs (to make an adjustment for this), however, the documentation states in the first line:

> Fires when the state of **any** of given entities changes.

Thus this is already present in the existing documentation.

**Comment by nottledim** [comment]
Oh dear, how embarrassing.  Sorry.
