### ISSUE TITLE
I would like to be able to hide the new quick bar on non-admin users or for all users

### ISSUE THREAD

**Issue by kdf743** [home-assistant/home-assistant.github.io#22673]
### Feedback

I use Fully kiosk to show home assistant which means there are entities that I don't want to be available to everyone but the new quick bar allows all entities to be accessible from all dashboards and I am not able to disable this in any way.

### URL

https://www.home-assistant.io/docs/tools/quick-bar/

### Version

2022.5.2

**Comment by thecode** [comment]
Feature requests should be created at https://community.home-assistant.io/c/feature-requests/13
This is used for documentations issues.
Thanks
