### ISSUE TITLE
TLD

### ISSUE THREAD

**Issue by ericbrian** [home-assistant/home-assistant.github.io#22674]
### Feedback

How does one add a new TLD? I am trying to add a domain with the 'app' TLD.

### URL

https://www.home-assistant.io/integrations/whois/

### Version

2022.5.2

**Comment by frenck** [comment]
New TLDs are not provided by Home Assistant.

This integration uses the `whois` Python package to provide this information, which can be found here:

<https://github.com/DannyCork/python-whois/>

If additional TLDs are added to that package, we can update Home Assistant to support them too.

../Frenck
