### ISSUE TITLE
Need a description of the login dialog

### ISSUE THREAD

**Issue by SymmetricDesigns** [home-assistant/home-assistant.github.io#22680]
### Feedback

Please add a description of the log in dialog. It currently only says "Follow the instruction on screen to complete the set up". There aren't any.  I have no idea what "Area ID" is (I'm new to HA if that's an HA term).  It defaults to "1" and the login fails. I can log into the yale site (august.com) and the app.

### URL

https://www.home-assistant.io/integrations/yale_smart_alarm/

### Version

2022.5.2

### Additional information

I managed to get logged in by switching to use my phone #, using the August integration instead of Yale (I don't know what the difference is), and I got a dropdown for the "Area ID" which made me realize the "Area ID" is what HA calls a room.. I thought it wanted a Yale Area ID. I suspect Yale has a bug if you create your account with a mixed case email address.

**Comment by gjohansson-ST** [comment]
Hi. For august use the August integration. This is the wrong one. 
This one is for Yale Smart Living. For newer locks I believe it's all using August but not entirely sure.
