### ISSUE TITLE
Splitting the config for automations

### ISSUE THREAD

**Issue by ntsp00** [home-assistant/home-assistant.github.io#22684]
### Feedback

Attempting to follow the guidance to separate manual automations from those generated using the UI due to Home Assistant purging all spacing and # text lines. 

# My own handmade automations
automation manual: !include_dir_merge_list automations/

# Automations I create in the UI
automation ui: !include automations.yaml

This documentation is either outright wrong or not clear enough to be of actual use. The provided example followed exactly causes manual automations to no longer function. Further, there is no documentation to indicate the requirement to split the configuration if the user chooses to utilize manual automations and those generated using the UI. Other documentation states # text lines are ignored and yet that isn't true for automations.yaml.

### URL

https://www.home-assistant.io/docs/configuration/splitting_configuration/

### Version

2022.5.2

**Comment by frenck** [comment]
Checked the documentation, and it looks correct to me. Could you quote the part of the documentation you think is incorrect?

> Further, there is no documentation to indicate the requirement to split the configuration if the user chooses to utilize manual automations and those generated using the UI

There is no such requirement. This is an advanced feature that allows setting it up as you please. Some don't use the UI at all 🤷
