### ISSUE TITLE
How would I convert these commands to install Pandora on Home Assistant. 

### ISSUE THREAD

**Issue by rdperkins** [home-assistant/home-assistant.github.io#22697]
### Feedback

I'm running Home Assistant on the latest Hassio OS and it doesn't recognize the linux commands on it's terminal window. I'd appreciate your help. Thanks.

### URL

https://www.home-assistant.io/integrations/pandora/

### Version

2022.5.3

**Comment by frenck** [comment]
Unfortunately, that is not possible. This integration is only available for Home Assistant Core installation types.

I'll make a task to update that page to indicate that.

**Comment by rdperkins** [comment]
You're one of my HA heros. Thanks a million for your work on HA. In the meantime, do you think anyone will work on a HACS integration for playing and controlling personal Pandora Radio streams? Best regards,

**Comment by frenck** [comment]
> You're one of my HA heros. Thanks a million for your work on HA.

❤️ 

> In the meantime, do you think anyone will work on a HACS integration for playing and controlling personal Pandora Radio streams

I wish I had an answer for you :(
