### ISSUE TITLE
Energy Dashboard with Enphase Envoy sensor entities

### ISSUE THREAD

**Issue by Cliffh33** [home-assistant/home-assistant.github.io#22696]
### Feedback

I would like to be able to use the Enphase integration for the Energy dashboard.
Not all of the Envoy entities are available. The current production and consumption aren't selectable e.g. sensor.envoy_122027029XXX_current_energy_production 

### URL

https://www.home-assistant.io/docs/energy/solar-panels/

### Version

2022.5.1

### Additional information

.

**Comment by klaasnicolaas** [comment]
Use the lifetime production / consumption entities 😉

**Comment by Cliffh33** [comment]
Hi

 

What am I missing here? A dashboard block titled ‘Energy distribution today’ shouldn’t be using lifetime entities – should it?.

When does it provides no match to actual:

 



 

 

Reality:

 



 

 

 

Cheers

**Comment by klaasnicolaas** [comment]
Please respond via the GitHub platform and not by mail, it looks like you have attached screenshots but they are not shown.

There is a difference between power or energy entities and the energy dashboard is based on entities that show a kilowatt hour (kWh) values.

**Comment by Cliffh33** [comment]
When using the lifetime entities the Energy Dashboard seems to 'work out'. The Energy distribution Today however has an incorrect Solar amount going to Home and the Grid feeding the Home when the Home is actually feeding the Grid. Please find a PDF attached with screenshots
[Energy_screen_shots.pdf](https://github.com/home-assistant/home-assistant.io/files/8665595/Energy_screen_shots.pdf)
.

**Comment by klaasnicolaas** [comment]
The way you've set up the entities now doesn't seem correct to me, maybe it's best to take a look at this forum https://community.home-assistant.io/t/enhpase-envoy-on-2021-8-with-new- energy-feature/328668

Or open a new topic / ask your question in the Discord server.

**Comment by jmatiasGH** [comment]
Hi guys!
I've noticed that the Enphase envoy-s data in Home Assistant only refreshes every minute. Is there a way to refresh them every few seconds, for example every 10 seconds? I understand that the envoy stream sends information every second.
On the other hand, the consumption sensor corresponds to the consumption of panels or the electrical network indifferently, but a sensor/entity is missing that calculates the energy input or output of the electrical network to be able to integrate it correctly with the dasboard of energy and that the data square. This data could be obtained from the information on what is produced in the panels and what is consumed in the house, being a positive or negative value depending on whether energy is being imported or exported.
