### ISSUE TITLE
Order of sections, packages, splitting config.

### ISSUE THREAD

**Issue by sciurius** [home-assistant/home-assistant.github.io#22692]
### Feedback

> With packages we have a way to include different components, or different configuration parts using any of the !include  directives introduced in [splitting the configuration](https://www.home-assistant.io/docs/configuration/splitting_configuration).

I think it is better to reverse the order of these topics. Splitting config first, and then Packages second.

### URL

https://www.home-assistant.io/docs/configuration/packages/

### Version

2022.5.3

**Comment by frenck** [comment]
This page is about packages only? What do you mean by order?

**Comment by sciurius** [comment]
Sorry, I meant the page order in the right sidebar.
![scrot20220509131147](https://user-images.githubusercontent.com/1118804/167398422-b24ee87b-ca2b-42c5-99e4-6d02360f06c0.png)

**Comment by frenck** [comment]
Right, that makes sense I guess 👍
