### ISSUE TITLE
What is sampling_size in statistics

### ISSUE THREAD

**Issue by yelkenli1** [home-assistant/home-assistant.github.io#22703]
### Feedback

I put this in the HA community forum also.  

The Statistics page defines the sampling_size as
    Maximum number of source sensor measurements stored.

The problem with this definition is it does not mention the frequency of samples (every 10 seconds, or 1 minute, or 1 hour, etc). So what time period does the stored data represent if you have a sampling_size of 50 (for example)?
Where do I find the frequency of the sensor? The recorder is the only place I can find a frequency (commit_interval), and I don’t think that’s it.

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2022.5.3

### Additional information

[community forum page](https://community.home-assistant.io/t/what-is-sampling-size-in-statistics/420554)

**Comment by fabaff** [comment]
If not specified then the sensor run with the [default interval](https://www.home-assistant.io/docs/configuration/platform_options#scan-interval).

**Comment by yelkenli1** [comment]
Since the statistics platform has configuration variables that are impacted by the scan interval, adding a note on the statistics page might provide useful support to HA users.  I will update the HA forum thread I started with the above. What I found in the forum were recommendations to pull up history and count the smallest time slices and add a fudge factor. Otherwise no responses, which indicates many do not know how this works.

**Comment by ThomDietrich** [comment]
Hey @yelkenli1,
it's not a clear science. Sensors update at a constant rate or event-driven based on external influences. In addition, home assistant does not propagate new values to the statistics integration when they are equal to the previous value. You need to check the behavior of your specific sensor.

The source sensor sample size is not always most useful. How you configure your sensor depends on the use case. For most use cases you are interested in a given time period (e.g. the minimum value over the last 30min) and sampling size shouldn't interest you too much. In these cases you should set a big enough sampling_size to not run into limits. Check `buffer_usage_ratio`.

Discussions are going on in other threads about the relevance of sampling_size vs max_age and you will see improvements to the statistics component soon. I am working on a change that effectively will make sampling_size obsolete (optional).
