### ISSUE TITLE
Add energy usage 

### ISSUE THREAD

**Issue by soheiladeli** [home-assistant/home-assistant.github.io#22704]
### Feedback

@mdz , thanks for the improvements on the smartthub integration for home assistant. Is it possible to add the energy usage sensors to see total energy usage, e.g daily, monthly? Currently it doesn't show energy usage.
Thanks

### URL

https://www.home-assistant.io/integrations/smarttub/

### Version

2022.5.3

**Comment by mdz** [comment]
I'm glad you're finding the integration useful, thanks for the feedback.

The energy usage API is a bit limited unfortunately. It only exposes daily and monthly usage estimates, so it's really only useful for historical perspective. Can you say more about what you'd want to do with it in Home Assistant? Are you just interested in being able to view the data in the HA interface, or do you imagine creating some automations based on it?

FYI, for my unit at least, the energy usage is completely dominated by the heater. I don't use the jets often enough for the energy usage to be significant, and the circulation pump is a rounding error compared to the heater. So in practice, I just use the heater state to track the usage (you can multiply it by the heater wattage to get an instantaneous reading).

**Comment by soheiladeli** [comment]
Thanks for your prompt reply Matt.
I use HA energy dashboard to monitor my home and solar energy usage and exports and also some individual devices like fridge, air condition which have their own smart plug to send energy usage to HA. It would be great to see the total energy usage by the Spa in HA, so I can add it to my energy dashboard as an individual device to monitor the total daily energy.
So in the SmartTub mobile app I can see the daily and monthly energy but in HA I don't see any energy sensors at all.
 




Jay 

    On Wednesday, 11 May 2022, 11:40:53 am AEST, Matt Zimmerman ***@***.***> wrote:  
 
 


I'm glad you're finding the integration useful, thanks for the feedback.

The energy usage API is a bit limited unfortunately. It only exposes daily and monthly usage estimates, so it's really only useful for historical perspective. Can you say more about what you'd want to do with it in Home Assistant? Are you just interested in being able to view the data in the HA interface, or do you imagine creating some automations based on it?

FYI, for my unit at least, the energy usage is completely dominated by the heater. I don't use the jets often enough for the energy usage to be significant, and the circulation pump is a rounding error compared to the heater. So in practice, I just use the heater state to track the usage (you can multiply it by the heater wattage to get an instantaneous reading).

**Comment by soheiladeli** [comment]
Sorry @mdz , the images didn't attach in my previous post.

<img width="302" alt="image" src="https://user-images.githubusercontent.com/20199950/167757170-58943124-c37d-444f-b961-0ff5b3f3e5a7.png"><img width="766" alt="image" src="https://user-images.githubusercontent.com/20199950/167757405-8b291a63-ac1d-45ec-a71a-00fa9bf4ce55.png">

**Comment by frenck** [comment]
Hi all 👋 

Thanks for contributing and discussing possible improvements to an integration, however, this issue tracker is used for tracking documentation feedback and not for processing feature requests.

For feature requests, please use our community forums:

<https://community.home-assistant.io/c/feature-requests/13>

Thanks! 👍 

../Frenck
