### ISSUE TITLE
// Backup

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#22701]
### Feedback

I am an HA Supervised user and love the fact that I can create backups - I tend to do this when I make a major change (as I am in build/test phase).  I also love that when your software performs an update/upgrade it allows for a backup to be taken.  

It is sometimes difficult to keep with all of these.  :-)  

Is there a way to keep only a specific number of backups?  or cleanup (automated) when 'xx' amount of disk space is used for Backups?  

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2022.5.3

**Comment by frenck** [comment]
> Is there a way to keep only a specific number of backups? or cleanup (automated) when 'xx' amount of disk space is used for Backups?

There is currently no such configuration option.

../Frenck
