### ISSUE TITLE
Side effect of removing 'unit' configuration parameter

### ISSUE THREAD

**Issue by VdR1960** [home-assistant/home-assistant.github.io#22721]
### Feedback

I have an integration to calculate water consumption from water flow.

Water flow is in 'ltr/min.', and the integration is done with 'unit_prefix' 'k' and 'unit_time' 'min' to give m3. Unfortunately the determined unit_of_measurement is 'kltr/minmin' (which as such is correct), but without the 'unit' parameter I can no longer change this to a friendly 'm3'.

So before I _could_ assign the wrong unit wrong myself, now it automatically assigns the wrong unit. Progress?

### URL

https://www.home-assistant.io/integrations/integration/

### Version

2022.5.3

**Comment by dgomes** [comment]
We now have https://www.home-assistant.io/integrations/integration/#unique_id which enables you to configure the unit through the UI as you used to.
