### ISSUE TITLE
Ukraine alarm translation

### ISSUE THREAD

**Issue by HA-Peet** [home-assistant/home-assistant.github.io#22729]
### Feedback

The need for a ukraine state translation into english instead of cyrillic

### URL

https://www.home-assistant.io/integrations/ukraine_alarm/

### Version

2022.5.4

**Comment by frenck** [comment]
If you want to help translating Home Assistant, you can do so. Please read all about it here:

<https://developers.home-assistant.io/docs/translations>

Thanks already for helping out!

../Frenck
