### ISSUE TITLE
Incomfort doesnt work anymore since latest update Home Assistant Core 2022.5.4

### ISSUE THREAD

**Issue by MrKleZe** [home-assistant/home-assistant.github.io#22736]
### Feedback

this component doesnt works anymore since latest update of home assistant

### URL

https://www.home-assistant.io/integrations/incomfort/

### Version

2022.5.4

### Additional information

this component doesnt works anymore since latest update of home assistant

Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.1
Home Assistant OS 7.6
Kernel version 5.10.103-v8
Agent version 1.2.1

**Comment by zxdavb** [comment]
Thank you for your submission.

It will be easier for me to help you if you can include some logs.

**Comment by frenck** [comment]
Hi there @MrKleZe 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
