### ISSUE TITLE
Buttons are now left justified

### ISSUE THREAD

**Issue by WilkyF18** [home-assistant/home-assistant.github.io#22743]
### Feedback

Button card used to be centered.  Now they are left justified.  How do you re-center them?

### URL

https://www.home-assistant.io/dashboards/button/

### Version

2022.5.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
