### ISSUE TITLE
Add link to companion docs for notifications

### ISSUE THREAD

**Issue by RichardUUU** [home-assistant/home-assistant.github.io#22750]
### Feedback

On the notification page: https://www.home-assistant.io/integrations/notify/

I expect notifying the Companion Apps would be a common use case. It would be helpful to include this link to the docs for the Companion Apps:
https://companion.home-assistant.io/docs/notifications/notifications-basic/

FWIW, the docs currently state "To use it you have to setup at least one notification target (notifier), check the [integrations list](https://www.home-assistant.io/integrations/#notifications) for one that fits your use case."

That wording suggests the integrations list is a comprehensive listing of notification targets, yet following that link does not get me to the companion apps (via search for companion or android).

### URL

https://www.home-assistant.io/integrations/notify/

### Version

2022.5.4

**Comment by frenck** [comment]
> I expect notifying the Companion Apps would be a common use case.

This page is not about the mobile apps, but about the notify platform in general. This is not limited to mobile apps.

**Comment by frenck** [comment]
Closing this suggestion for the above reasoning. Nevertheless, thanks for providing feedback 👍
