### ISSUE TITLE
STT - Multiple Language Support

### ISSUE THREAD

**Issue by Quaeft** [home-assistant/home-assistant.github.io#22764]
### Feedback

Hi everyone,

I am trying to get the STT and conversation integrations to work for a different language. Unfortunately it is a topic not many people talk about.
While reading the code I found out that there is at least one "en-us" constant. That on the other hand tells me that the STT api or Home Assistant Cloud api should be able to understand "de-de", "fr-fr", etc. Probably it also does that, but it is unfortunately not documented nor implemented.
Or am I missing something?

Best regards,
Quaeft

### URL

https://www.home-assistant.io/integrations/stt/

### Version

2022.5.4

**Comment by frenck** [comment]
I'm unsure if this is a development question? If so, our developer channels on the Discord chat might be a better place to ask this kind of question.

As in, the `stt` is an integration platform, that is used by other integrations to implement (and not for direct end-user use). 

Yes; it supports multiple languages.

**Comment by Quaeft** [comment]
Hello,
thank you for the quick responding. Yes indeed it will be more of a development question. I will give it a try!
