### ISSUE TITLE
No devices

### ISSUE THREAD

**Issue by RobertKing42** [home-assistant/home-assistant.github.io#22760]
### Feedback

Followed these instructions to the letter.  I can see my devices in the Tuya IoT site, but not in the integration.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2022.5.4

**Comment by siggijarl** [comment]
same here

**Comment by frenck** [comment]
Hi there @RobertKing42, @siggijarl.

It seems like you want to report an issue  with an Home Assistant integration, however, you have reported documentation feedback instead.

Please report issues with integrations here: <https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
