### ISSUE TITLE
Companion Docs followup

### ISSUE THREAD

**Issue by RichardUUU** [home-assistant/home-assistant.github.io#22775]
### Feedback

I previously suggested adding a link here to the Companion Docs which was closed because this page is not about the companion apps.

I think the point was missed. 

This page is not about integrations, yet there is a link to the integrations list for the convenience of the user. 
This page is not about the Persistent Notification integration, yet there is a link for the convenience of the user. 

So what's wrong with adding, say:
You can also send notifications to the Home Assistant [Companion Apps](https://companion.home-assistant.io/docs/notifications/notifications-basic/).

I understand not wanting documentation bloat, but I think docs should provide helpful links for the most common use cases, and sending notifications to the companion apps qualifies.

### URL

https://www.home-assistant.io/integrations/notify/

### Version

2022.5.4

**Comment by frenck** [comment]
> I think the point was missed.

I don't think so. `/integration/notify` page is about the generic entity-component and now about how notification on mobile works.

That is what already was stated as a response to the previous suggestion you provided, which is still the same.

Nevertheless, thank you for your suggestion.
