### ISSUE TITLE
Please link to the custom component for GPIO

### ISSUE THREAD

**Issue by jfbloom22** [home-assistant/home-assistant.github.io#22774]
### Feedback

It would be awesome if the paragraph of text about the deprication, also linked to the custom component:  https://github.com/thecode/ha-rpi_gpio

Yesterday I configured the core component thinking that a custom one was in the works.  Today I found the custom one after reading this forum:  https://community.home-assistant.io/t/gpio-support-deprecation/388401

Thanks!

### URL

https://www.home-assistant.io/integrations/rpi_gpio/

### Version

2022.5.4

**Comment by frenck** [comment]
We don't support custom integrations, there we don't link them either (as we don't want to give the impression we recommend, support or endorse them).

Nevertheless, thanks for providing feedback 👍 

../Frenck

**Comment by jfbloom22** [comment]
Ok thanks for clarifying.  Home Assistant is awesome!  I appreciate yall working hard making it work reliably for most people.   All the integrations I have installed have worked flawlessly.  Every once in a while I get an itch to do something more customized like control my solar panel power inverter.  So much fun to be able to do that through Home Assistant.  I just hope yall don't take it too far and make it really difficult to customize.
