### ISSUE TITLE
Install Home Assistant Core on Raspbian/Raspberry Pi OS Bullseye 11.3 fails due to lack of rustc

### ISSUE THREAD

**Issue by bclaymiles** [home-assistant/home-assistant.github.io#22784]
### Feedback

rust doesn't appear to be part of the default raspbian installation so during the python cryptography package installation, it fails out. Fix for the documentation is easy, just add rustc to the  initial installation string

sudo apt-get install -y python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata rustc

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.5.4

**Comment by frenck** [comment]
![CleanShot 2022-05-16 at 23 15 41](https://user-images.githubusercontent.com/195327/168683793-ac839079-16ba-42a7-b7b9-137779fee3b2.png)

Nevertheless, thanks for providing feedback 👍

**Comment by bclaymiles** [comment]
I'm well aware of that. But since Raspbian/Raspberry Pi OS is pretty much the default OS used on Raspberry Pi devices, and the lack of rust is consistent as it's not a default package, adding it to the string with which one installs the dependencies rather makes sense. I mean, tzdata IS a default, required package in Debian/Rasp*, so having that as part of the string is unnecessary. 

This seems shortsighted. This is not a step that would 'differ' on any installation.

root@ntpVIZ: ~ # apt-cache show tzdata
[...]
Priority: required
[...]

root@ntpVIZ: ~ # apt-cache show rustc
[...]
Priority: optional
[...]

**Comment by frenck** [comment]
Thanks for your feedback, however, we do not aim our guides specifically at Raspberry Pi OS. In the end, it's an advanced installation method. If one is not able to adopt it, we advice again using this installation method.

**Comment by bclaymiles** [comment]
Five characters added to a line is too much effort? Particularly when there is zero harm in adding them, and it makes the instructions better _for the vast majority of people who would use that method_.

Weird attitude.

**Comment by frenck** [comment]
> Five characters added to a line is too much effort? 

No, it's not, however, it does add packages most people like do not need (as pre-build wheels are available for lots of architectures). Thus, it's not added.

> for the vast majority of people who would use that method.

It does not, as your statement is limited to Raspberry Pi with Raspberry Pi OS; the fact is, that most people on that system use Home Assistant OS. Core installations are often found in combination with other systems/setups which these instructions are mainly targeted at.

You may call that a weird attitude, I'm fine with that.

../Frenck

**Comment by bclaymiles** [comment]
> No, it's not, however, it does add packages most people like do not need 

False. You can't build homeassistant without rust, if doing a manual installation. That's the whole point of the dependencies line. If a package already exists, then apt-get (or now on most systems, merely 'apt') just reports that it's already installed and moves on.

> It does not, as your statement is limited to Raspberry Pi with Raspberry Pi OS

No, again, false. Your instructions use apt-get, yet that's used on Debian-based systems (Debian, Rasp*, Ubuntu, many more). That means the existing instructions are tailored to that path, rather than using 'pacman' as the package installer (Arch linux) or 'portage' as the package installer (Gentoo), both of which have builds for ARM-based systems, and specifically for Raspberry Pi's - and many other linuxes out there. The 'advanced' instructions are _already tailored_ to the most commonly used OS on Raspberry Pi's. 

The point of instructions is to be helpful. The instructions already use the default commands most likely to be run on a Raspberry Pi manual installation. Adding rustc to the dependencies line causes no harm, contrary to your claim, since we are talking about DEPENDENCIES.

I've been building and managing unix/linux systems professionally for 27 years. This is a trivial change to the documentation, to avoid an unnecessary build failure. The page says "Help us to improve our documentation". My feedback is helpful to anyone following the advanced instructions. It's a one word change, that does not install anything other than a necessary component.

But hey, I can see that you've dug your heels in and are unwilling to improve the documentation when someone offers an improvement. Yes, it's a weird attitude, and that you're fine with that suggests that maybe you're not well suited to judging the quality of the documentation, and certainly not interested in helping users.

Peace be upon you.

**Comment by frenck** [comment]
> You can't build homeassistant without rust, if doing a manual installation. 

Sorry to hear you don't agree. That said, the current warning in the documentation we consider to be sufficient.

> I've been building and managing unix/linux systems professionally for 27 years. 

Good for you, not sure if that is needed or proves any point. It makes me want to stop this conversation right here.

Have a nice day.

**Comment by bclaymiles** [comment]
It is to suggest that you are likely way out of your depth in judging the validity of matters having to do with installing Home Assistant in the advanced method. Perhaps someone else involved in the Home Assistant project would be better suited to reviewing documentation changes, because the change I've offered is drop-dead obvious to anyone who has even modest experience administrating systems. That you dispute that rust is required in the advanced installation verifies that.

BUT! That said - this conversation has been poisoned by defensive posturing - by both of us, I freely admit to my share in that. So, apologies for my tone. I'm simply frustrated that an obvious improvement to the documentation is being blocked. I'll take the matter up through other avenues, and as before - peace be upon you, brother.

**Comment by frenck** [comment]
> It is to suggest that you are likely way out of your depth in judging the validity of matters having to do with installing Home Assistant in the advanced method. Perhaps someone else involved in the Home Assistant project would be better suited to reviewing documentation changes, because the change I've offered is drop-dead obvious to anyone who has even modest experience administrating systems

Maybe, however, this part is not written or maintained by me, I just agree. So, you see I'm not the only one. I do consider myself knowledgeable enough on the matter. You are just not accepting a no.

>  by both of us

Sorry, not by me. And I thanked you for your feedback (I do appreciate, you and people, in general, taking the time to provide those; it the whole reason I created this form in the first place).

This addition has been suggested before (and others, similar package additions, too). Hence this is not a new occurrence for we have to make up our minds. My answers have been normal in tone and are based on decisions we, as a project, already made before.

>  I'm simply frustrated that an obvious improvement to the documentation is being blocked.

Sorry to hear that, but this is what it is at this point.

../Frenck

**Comment by frenck** [comment]
I went ahead and set up a fresh Debian (11.3, minimal), installed the apt dependencies, created a venv and ran `pip install homeassistant` and it succeeded as normal and in a working state.

I have not installed `rustc` at any point; as a matter of fact `apt -qq list rustc` showed it was not installed, and `dpkg -l | grep rustc` had no results.

In my case, the binary wheel distribution provided by the cryptography project was used by pip and I did not have to build it from source.

../Frenck

**Comment by bclaymiles** [comment]
Welp, that' pretty much nails it I guess. I'm used to just looking for the error in output and acting on it, so when I saw

error: can't find Rust compiler

I ignored the rest, boy is that on me.

So the whole thread was a waste of time - mostly of yours. I think I'll go crawl under a rock, sigh.

**Comment by frenck** [comment]
Don't worry about it, as said, I think submitting these things is good and I do appreciate that  you did 👍

**Comment by bclaymiles** [comment]
I appreciate your diplomacy.  ;)

**Comment by frenck** [comment]
Sorry to disappoint, but it's not diplomacy, it was honesty; a project like this can only become what it is because of everybody stepping in. I really do appreciate you stepping in.
