### ISSUE TITLE
Unclear Sonarr installation feedback

### ISSUE THREAD

**Issue by starman2k01** [home-assistant/home-assistant.github.io#22806]
### Feedback

Sonarr stopped working, so I deleted and re-installed. Filled in URL and API Key, "Failed to connect". Tried dozens of different URL formats. No feedback on what failed. Why not give the user exactly WHAT is failing? Client refused? Wrong API key? Can't ping client? etc. etc.
Latest HASS supervised.

### URL

https://www.home-assistant.io/integrations/sonarr/

### Version

2022.5.4

**Comment by frenck** [comment]
Hi there @starman2k01 👋 

It sounds like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by starman2k01** [comment]
No this is a documentation issue. User needs FEEDBACK either in documentation on what to do or in the code itself.
Getting help with HASS is so difficult...

**Comment by frenck** [comment]
It should not happen as you experienced, thus it should be raised as a bug towards the core integration. Documenting and unexpected error is not productive and doesn't solve anything.

Please raise an issue in the provided issues tracker above.

Thanks! 👍 

../Frenck
