### ISSUE TITLE
RM4 Mini "Device not supported"

### ISSUE THREAD

**Issue by Flea1234** [home-assistant/home-assistant.github.io#22811]
### Feedback

We are using the Broadlink - RM4 Mini with Home Assistant OS.
We recently noticed that when we try to add it via your device via your official integration, we get the error "Device dont support."

Why is there this error? how can we solve? if the device is no longer support we will have to change vendor.

We are looking forward to hearing from you.

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2022.5.5

**Comment by jangoertzen** [comment]
I'm having the same issue.
