### ISSUE TITLE
authentications problem adding the integration

### ISSUE THREAD

**Issue by Carlos197069** [home-assistant/home-assistant.github.io#22810]
### Feedback

hello, 
i download the app that suppose to be https://play.google.com/store/apps/details?id=com.rheem.rheemsmartconnect
and i create the user with password, but when i try o do add the integration i got "Invalid authentication"

### URL

https://www.home-assistant.io/integrations/econet/

### Version

2022.5.5

**Comment by w1ll1am23** [comment]
Wrong app you want this. 

https://play.google.com/store/apps/details?id=com.econet.econetconsumerandroid
