### ISSUE TITLE
Stuck at Preparing Home Assistant

### ISSUE THREAD

**Issue by bdwilson24** [home-assistant/home-assistant.github.io#22839]
### Feedback

https://www.reddit.com/r/homeassistant/comments/uuqlmh/stuck_at_preparing_home_assistant_no_monitor/

I have followed the install instructions over and over and am totally stuck. It seems that a lot of people are having similar issues.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.5.5

**Comment by frenck** [comment]
Hi there @bdwilson24 👋 

Sorry to hear that, however, this is not the place to gain support with that.

You should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
