### ISSUE TITLE
keeps trying to login after removal

### ISSUE THREAD

**Issue by kluner** [home-assistant/home-assistant.github.io#22849]
### Feedback

extension keeps attempting login (successfully) after removal, when adding the integration again, and providing a fake password, it still manages to pass, retrieve information from iCloud.

expected behaviour would be: removal stops any attempt to contact iCloud.

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2022.5.5

**Comment by frenck** [comment]
Hi there @kluner 👋 

It seems like you want to report a issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenkc
