### ISSUE TITLE
Get Built in Codes From Newer Broadlink App

### ISSUE THREAD

**Issue by ifflanb** [home-assistant/home-assistant.github.io#22848]
### Feedback

Hi, I have a remote added to the newer Broadlink app using the built in codes. I want to get the codes for that into HA. I have tried adding my Broadlink RM to the e control app but it shows as an unknown device type for some reason and I can't use it. Is it possible to get the codes from the newer Broadlink app into HA somehow without learning the codes with the remote control?
thanks

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2022.5.5

**Comment by frenck** [comment]
Thank you for reaching out. However, this sounds more like a question for our community.

You should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
