### ISSUE TITLE
"failed to connect" when adding integration on HA

### ISSUE THREAD

**Issue by jessevd** [home-assistant/home-assistant.github.io#22853]
### Feedback

When I try to add switchbot to my home assistant via the official integration page, I get the error "failed to connect" with no further explanation. 

I have to say, I'm quite new to this, so not sure what to do. 
![Screenshot_20220522-191750_Home Assistant](https://user-images.githubusercontent.com/22777222/169707618-11521951-517c-4bc5-a864-e21d32a780cb.jpg)

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2022.5.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
