### ISSUE TITLE
quick bar and quick search

### ISSUE THREAD

**Issue by victorysmarthome0001** [home-assistant/home-assistant.github.io#22851]
### Feedback

it will be great if there's an option to permit or prohibit specific user to access the quick bar or quick search at the dashboard (the magnifier icon). my case, i'm putting tablet at wall at first story. and it will be disastrous if someone tried to turn on or turn off switch they're not meant to access by searching through this new features. for example when you're at bathroom, your kids turn off your lamp.

### URL

https://www.home-assistant.io/docs/tools/quick-bar/

### Version

2022.5.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
