### ISSUE TITLE
Ambiguous requirements for energy sensor

### ISSUE THREAD

**Issue by atkulp** [home-assistant/home-assistant.github.io#22854]
### Feedback

It simply talks about specifying usage. I'm not clear what it needs. Are we trying to real-time instantaneous data (converted to kWh, I know)? Specifically, I'm using the [Emporia Smart Home Energy Monitor](https://smile.amazon.com/Emporia-Monitor-Circuit-Electricity-Metering/dp/B08G37ML2R). Using clamp inductive sensors, it provides information on my mains connection and individual circuits. The values available are either based month or day, increasing until they reset to zero. Does it matter which I select? My worry is that if it's looking for instantaneous readings, then neither of these would work. Can you help me with this and update the documentation to make it more clear?

### URL

https://www.home-assistant.io/docs/energy

### Version

2022.5.3

**Comment by frenck** [comment]
> The values available are either based month or day, increasing until they reset to zero. Does it matter which I select?

No, that doesn't matter. If Home Assistant allows you to select the sensor, it already knows how to handle it (otherwise it wasn't selectable for use).

> Can you help me with this and update the documentation to make it more clear?

About what, I'm not sure if I follow.
