### ISSUE TITLE
Please link to the http config page from the network securing page

### ISSUE THREAD

**Issue by Lotharyx** [home-assistant/home-assistant.github.io#22865]
### Feedback

Configuring HomeAssistant to use TLS/SSL correctly and managing DNS are two _entirely_ separate concepts.  

Please at least link to the http integration documentation page...I had to search the feedback on this page to find that link.

### URL

https://www.home-assistant.io/docs/configuration/securing/

### Version

2022.5.5

**Comment by frenck** [comment]
Honestly, I would not recommend using TLS/SSL directly in Home Assistant, instead, use a reverse proxy.
