### ISSUE TITLE
no simple one-button integration with fibaro

### ISSUE THREAD

**Issue by BBE128** [home-assistant/home-assistant.github.io#22862]
### Feedback

I used the button on HAS to integrate fibaro hub. 
Next I got a question do you want to integrate fibare, but next the message: "Config flow kon niet geladen worden" (= config flow could not be loaded).
Adding it from HAS doesn't seem to work, there I'm suggested to visit the online site and the circle is round...

### URL

https://www.home-assistant.io/integrations/fibaro/

### Version

2022.5.5

**Comment by frenck** [comment]
Hi there @BBE128 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by BBE128** [comment]
okay, i was automaticaly sent to this site

**Comment by frenck** [comment]
We don't have an automated redirect, if you are writing up an documentation suggestion (like you did here) it also has an additional note on that this is not the place to report issues:

![CleanShot 2022-05-23 at 10 44 38](https://user-images.githubusercontent.com/195327/169780467-6d9fba66-a07b-493a-9bb6-cc011de88280.png)
