### ISSUE TITLE
Inches/mile per hour

### ISSUE THREAD

**Issue by wwalcher** [home-assistant/home-assistant.github.io#22863]
### Feedback

It would be nice to be able to select imperial measurements instead of metric. I'd like to be able to look at the wind speed in miles per hour and rainfall in inches.

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2022.5.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
