### ISSUE TITLE
Why is it so hard to find the disk image?

### ISSUE THREAD

**Issue by MillerNerd** [home-assistant/home-assistant.github.io#22869]
### Feedback

I have an Intel laptop I want to run Home Assistant OS. I'm no newcomer to Linux and distro-hopping. But it's been incredibly frustrating finding the disk image. After looking for a while, finding myself on the generic x86-64 page, it tells me to use the disk image but doesn't link it or tell me where to get it. Finally looking in roundabout ways for it, I found the Home Assistant OS Release 6 via external search, but it was old. So I found the Home Assistant OS Release 8 via the home page, and again no link to anything useful. Then realized the image at the top was apparently a link to the GitHub repo with no indication of being such. But there's no readme, just a list of changes. I'm assuming everything I need is in the source code .tar.gz but at the moment I'm too frustrated to think straight and will have to come back to this later.

This has been, no joke, more painful than installing Arch

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2022.5.5

**Comment by MillerNerd** [comment]
I realize afterwards that I let too much of my frustration through here. Maybe this will turn into my first open source contribution XD

**Comment by frenck** [comment]
That one?

![CleanShot 2022-05-23 at 23 02 57](https://user-images.githubusercontent.com/195327/169905700-02798f0c-0635-4afa-9877-3daa0f8d997e.png)

**Comment by MillerNerd** [comment]
Yeah, I definitely let my frustration get the better of me on this, sorry.

I genuinely don't care if this is ignored, especially because I know my use
case isn't common, but I still have a nitpick in case you're interested

I still think things could be made a touch clearer. There were a lot of
very small things that threw me off. Having the BIOS section before the
media creation is weird. I skimmed over the Balena Etcher because I wasn't
interested in some software when I know how to format a drive. I was really
just looking for a "disk image" link or download.

Just putting the words "disk image" in that #4 step would allow people to
more easily find and grab the disk image. They could ctrl+f it on the page.
External search would likely highlight it so can just Google "home
assistant OS disk image" and it would probably pull me straight to that
line.

Also there are several references in other places to the "disk image" that
do not provide the disk image, nor link to the media creation section.
Those are the places external search brought me to, which is insanely
frustrating.

Ultimately I was apparently having an off day and lost my patience way too
soon, but that doesn't mean there's not room for improvement

Best,

Sean Miller
He/They
