### ISSUE TITLE
option select all

### ISSUE THREAD

**Issue by alb147** [home-assistant/home-assistant.github.io#22877]
### Feedback

Hi,
Can you add one botton of "Select all"  for select all files in Media?
Now, we can unselect all but no select all for deleted files.

Thanks

### URL

https://www.home-assistant.io/integrations/media_source/

### Version

2022.5.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
