### ISSUE TITLE
Philips TV inegration: Configuration not documented.

### ISSUE THREAD

**Issue by DigiLive** [home-assistant/home-assistant.github.io#22872]
### Feedback

For the Philips TV integration, there's an option to configure.

I would like to know what the following setting means:
![afbeelding](https://user-images.githubusercontent.com/7613487/170001118-3994e99d-565b-466d-93da-eede5117e989.png)
The language in the image is dutch, but it translates to something like "Allow the use of the data notification service."

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2022.5.5

**Comment by frenck** [comment]
As the text says: Allow the integration to use the notification service of the TV to gather data.

I'm not entirely sure what your question is, maybe you could clarify?

**Comment by DigiLive** [comment]
> As the text says: Allow the integration to use the notification service of the TV to gather data.

Which means?
It's unchecked by default and I would like to know what difference it would make when it's checked.

**Comment by frenck** [comment]
If you enable it, it will try to use the TV's notification service to get informed about a state change of the TV (additional to poll on the default interval).

**Comment by DigiLive** [comment]
Thanks, so I guess I enable it for faster synchronization between HA and the TV.

As far as I see, it's not documented, though.
You can close the issue if I'm wrong. ;)

**Comment by elupus** [comment]
Not all options are documented for integrations. I will look at possibly adding a wording about it or extending the in app description. I don't consider it a bug though.
