### ISSUE TITLE
Enphase login credentials

### ISSUE THREAD

**Issue by gene-vigelis** [home-assistant/home-assistant.github.io#22888]
### Feedback

The current Envoy firmware requires a token to log into the Envoy. How/where do I put the token?

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2022.5.5

### Additional information

I had Enphase email me my token which works if I connect directly via Web Browser.

**Comment by frenck** [comment]
Duplicate of https://github.com/home-assistant/core/issues/61524, please follow progress/status there. Thanks 👍
