### ISSUE TITLE
Clarity between manual set-up & NC set-up

### ISSUE THREAD

**Issue by TMV-NL** [home-assistant/home-assistant.github.io#22884]
### Feedback

Hi, for non-technical users it is not clear what part of the set-up only refers to the manual set-up and what part also applies for the set-up via Nabu Casa. i.e. additional users, etc. Is there a benefit/use case for NC users to create the projects in Google for example.

Also beneficial would be a (link to a) short introduction on how GA and HASS actually work together with automation, naming conventions, etc.

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2022.5.5

**Comment by frenck** [comment]
I'm confused about how this can be confusing in the documentation? The first paragraph tells about the NC option and closes with a link to the documentation for that option. After that the documentation continues with the manual setup.

> Hi, for non-technical users it is not clear what part of the set-up only refers to the manual set-up and what part also applies for the set-up via Nabu Casa. 

![CleanShot 2022-05-25 at 14 37 35](https://user-images.githubusercontent.com/195327/170263615-83481a46-fbd5-4160-be03-e2f9bec04483.png)

None of it is for Nabu Casa, the documentation links to the NC documentation on this.

>  there a benefit/use case for NC users to create the projects in Google for example.

No, there is not.


> Also beneficial would be a (link to a) short introduction on how GA and HASS actually work together with automation

They don't? Google Assistant is generally used for controlling devices with your voice. I'm not sure what you mean by "together with automation"?

> naming conventions, etc.

There are no naming conventions.

I really want to help processing suggestions, but I'm not sure what to do with this one. Could you maybe suggest edits instead?

**Comment by TMV-NL** [comment]
Hello Franck,

Your quick response is much appreciated, and my appologies for the  unclear feedback entry in the first place.

  1.  it is quite astonishing that the HA Cloud does everything automatically, including all allowing other users. So I'm surprised that all the 'manual config' is taken care of.
  2.  I've HA Cloud set-up and I see my devices and some scenes also in Google Home. But I actually do not know how it actually works, so probably I'm more looking for a 'best practise' for using the Google assistant with HASS.

Anyway, I just keep searching.

Regards,
Taco
________________________________
Van: Franck Nijhof ***@***.***>
Verzonden: woensdag 25 mei 2022 14:41
Aan: home-assistant/home-assistant.io ***@***.***>
CC: TMV-NL ***@***.***>; Author ***@***.***>
Onderwerp: Re: [home-assistant/home-assistant.io] Clarity between manual set-up & NC set-up (Issue #22884)


I'm confused about how this can be confusing in the documentation? The first paragraph tells about the NC option and closes with a link to the documentation for that option. After that the documentation continues with the manual setup.

Hi, for non-technical users it is not clear what part of the set-up only refers to the manual set-up and what part also applies for the set-up via Nabu Casa.

[CleanShot 2022-05-25 at 14 37 35]<https://user-images.githubusercontent.com/195327/170263615-83481a46-fbd5-4160-be03-e2f9bec04483.png>

None of it is for Nabu Casa, the documentation links to the NC documentation on this.

there a benefit/use case for NC users to create the projects in Google for example.

No, there is not.

Also beneficial would be a (link to a) short introduction on how GA and HASS actually work together with automation

They don't? Google Assistant is generally used for controlling devices with your voice. I'm not sure what you mean by "together with automation"?

naming conventions, etc.

There are no naming conventions.

I really want to help processing suggestions, but I'm not sure what to do with this one. Could you maybe suggest edits instead?

**Comment by frenck** [comment]
>  it is quite astonishing that the HA Cloud does everything automatically, including all allowing other users. So I'm surprised that all the 'manual config' is taken care of.

Yes, it does. Which is nice and convenient 🤩

> I've HA Cloud set-up and I see my devices and some scenes also in Google Home. But I actually do not know how it actually works, so probably I'm more looking for a 'best practise' for using the Google assistant with HASS

There is no "best practice". If you are using NC, you can go to Settings -> Home Assistant Cloud. There is a card saying: Google Assistant, which has a Manage Entities button that allows you to configure which are exposed and which are not.

Some more information about it can be found here: <https://www.nabucasa.com/config/google_assistant/>

That said, none of the Google Assistant documentation on the Home Assistant documentation applies to you, as that is all taken care of.

If you have questions or want to bounce off some ideas, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

**Comment by TMV-NL** [comment]
Thanks for the help!
________________________________
Van: Franck Nijhof ***@***.***>
Verzonden: woensdag 25 mei 2022 17:52
Aan: home-assistant/home-assistant.io ***@***.***>
CC: TMV-NL ***@***.***>; Author ***@***.***>
Onderwerp: Re: [home-assistant/home-assistant.io] Clarity between manual set-up & NC set-up (Issue #22884)


it is quite astonishing that the HA Cloud does everything automatically, including all allowing other users. So I'm surprised that all the 'manual config' is taken care of.

Yes, it does. Which is nice and convenient 🤩

I've HA Cloud set-up and I see my devices and some scenes also in Google Home. But I actually do not know how it actually works, so probably I'm more looking for a 'best practise' for using the Google assistant with HASS

There is no "best practice". If you are using NC, you can go to Settings -> Home Assistant Cloud. There is a card saying: Google Assistant, which has a Manage Entities button that allows you to configure which are exposed and which are not.

Some more information about it can be found here: https://www.nabucasa.com/config/google_assistant/

That said, none of the Google Assistant documentation on the Home Assistant documentation applies to you, as that is all taken care of.
