### ISSUE TITLE
2022.6 Documentation > New Integrations > Application Credentials has Invalid Link

### ISSUE THREAD

**Issue by SergeantPup** [home-assistant/home-assistant.github.io#22890]
### Feedback

I get a "oh no, this page does not exist" when I try to access the Application Credentials link in the new integrations section of the 2022.6 beta documentation.

### URL

https://rc.home-assistant.io/integrations/application_credentials

### Version

2022.6.0b0

**Comment by frenck** [comment]
This was pending and fixed with the merger of #22847
