### ISSUE TITLE
sensor.saguenay_precipitation_yesterday data missing

### ISSUE THREAD

**Issue by donparlor** [home-assistant/home-assistant.github.io#22897]
### Feedback

It seems sensor.saguenay_precipitation_yesterday is not receiving data anymore. 
<img width="1154" alt="Capture d’écran, le 2022-05-26 à 17 34 23" src="https://user-images.githubusercontent.com/97048708/170584001-f140f149-d4ab-4ec1-b443-96b50a7336a3.png">

And it has been raining in my area this May 2022.
<img width="1008" alt="Capture d’écran, le 2022-05-26 à 17 23 53" src="https://user-images.githubusercontent.com/97048708/170584036-bb86e10b-de07-46e1-bf66-32034d45ee30.png">

I even looked at other station around and it does not provide precipitation data. 

Could it be that there is an issue with data collection on https://weather.gc.ca/ ?

### URL

https://www.home-assistant.io/integrations/environment_canada

**Comment by donparlor** [comment]
This is historical data from https://climate.weather.gc.ca/climate_data/daily_data_e.html?StationID=5911

<img width="622" alt="Capture d’écran, le 2022-05-26 à 17 46 02" src="https://user-images.githubusercontent.com/97048708/170585394-deab1c9f-c710-4bcd-bd61-874bf37e1dd2.png">

**Comment by michaeldavie** [comment]
The climate data page indicates that "M = Missing" so this seems to be a data issue on Environment Canada's side.

**Comment by donparlor** [comment]
Ok, thanks @michaeldavie, I'll wait for Environment Canada to solve that issue. You can close this thread.

**Comment by donparlor** [comment]
@michaeldavie Hello Michael, I wrote to a Weather information specialist from MSC National Inquiry Response at Environment and Climate Change Canada, he said the following about my weather station:

`Thank you for sending your message to Environment and Climate Change Canada.  The precipitation gauge at the Jonquiere station failed on may 2 and needs to be replaced/repaired.  This will be done at the next maintenance inspection of the station, but we don’t have a date yet when this will be done.  Until the problem gets repaired, I suggest you use the data from the Bagotville Airport weather station, about 15 km away:`

Can I change the weather station in my Integration for only one sensor? I would change the precipitation sensor. If so, how can we do it?

**Comment by gwww** [comment]
All sensors for a configured station can only come from that station, so, no you can't change a single sensor.

What you can do is add a second station and use whatever sensors from that station that you need.

**Comment by donparlor** [comment]
Can you point toward a page that explains how to add a second station?

**Comment by gwww** [comment]
Same procedure as adding the first. Add environment Canada integration and fill in the blanks.

**Comment by donparlor** [comment]
Got it! I didn't realize I could add the integration "again". Thanks!
