### ISSUE TITLE
Add "Camera" to "Full Config"

### ISSUE THREAD

**Issue by timalot** [home-assistant/home-assistant.github.io#22906]
### Feedback

I struggled to get zoneminder to show the cameras and found this solution in the forums.  This could be added to the "Full Config" code to save trouble for others: 
camera:
  - platform: zoneminder

### URL

https://www.home-assistant.io/integrations/zoneminder/

### Version

2022.5.5

**Comment by rohankapoorcom** [comment]
This is already in the documentation under the [`camera` section](https://www.home-assistant.io/integrations/zoneminder/#camera). The ZoneMinder integration provides multiple different platforms (camera, switch, binary_sensor, sensor) so the full configuration only shows how to connect to ZoneMinder. The platforms have to be added additionally depending on what you want to do with them.
