### ISSUE TITLE
recongig not possible

### ISSUE THREAD

**Issue by legi1** [home-assistant/home-assistant.github.io#22917]
### Feedback

I can't reauthenticate the integration.
get message: {"errors":[{"message":"redirect_uri_mismatch: The redirect URI provided is missing or does not match partner callback url"}]}.
After going through, Withings website and authentication with Authy app.

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2022.5.5

**Comment by frenck** [comment]
Thank you for reaching out. The issue you are reporting means you have not correctly set up the developer/app account @ Withings (the redirect URL you have entered there doesn't match the one you are actually using to authenticate).

As this is a support question, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
