### ISSUE TITLE
Heater Control Needed

### ISSUE THREAD

**Issue by andersonlyle** [home-assistant/home-assistant.github.io#22930]
### Feedback

It would be great if you could add heater and light control to the Hayward Omnilogic integration.  

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2022.5.5

**Comment by djtimca** [comment]
The light platform has been under review for a long time. All are built. We are considering moving this integration to HACS to allow for more features and faster support for our user base to be available.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
