### ISSUE TITLE
Key missing on keypad

### ISSUE THREAD

**Issue by ukxisle** [home-assistant/home-assistant.github.io#22937]
### Feedback

In order to use keypad with Vista 20p you need to make the # character available

### URL

https://www.home-assistant.io/integrations/manual/

### Version

2022.5.5

**Comment by frenck** [comment]
@ukxisle 👋 

I'm not sure how this relates to the manual alarm control panel documentation, or what it is you are suggesting to change on this specific page.

Could you clarify?

**Comment by ukxisle** [comment]
Hi Franck, thanks for your reply.

Sorry maybe you are not the right person and if so I apologize.

On the manual keypad there are numbers 1-0 and clear. Unfortunately the
Honeywell Vista 20p requires the use of the # key which is ok if you are on
a computer but on a touch screen not workable.

Anyway if you are not the right person maybe you can point me in the right
direction.

Thanks

Terry


___________________________

Terry Keenor
____________________________
"Life is not an academic exercise"

**Comment by frenck** [comment]
Hmm right, this is not a documentation suggestion as it seems. You might want to raise this as an issue on the Home Assistant frontend repository.

Although, honestly, that might not be 100% right either. Nevertheless, I do think that the front is the right place to start bringing up attention to this.

You can find the frontend issues tracker here:

<https://github.com/home-assistant/frontend/issues>

I'm closing this issue on this end, as we cannot fix this by adjusting our documentation.

Thanks 👍 

../Frenck
