### ISSUE TITLE
Feedback //button

### ISSUE THREAD

**Issue by danlun** [home-assistant/home-assistant.github.io#22969]
### Feedback

Hi, as a bit of a newcomer to HA I find it very hard to get starting with the integration //button. Integration normally have a description of installation and more, but I understand of course that //button doesn't need to be installed. In such case maybe some more examples would be a good idea, just to get going on how to create the button from scratch and then implement some services/other things to that button.

### URL

https://www.home-assistant.io/integrations/button/

### Version

2022.6.1

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/172343315-f0b159dd-87ba-4cec-9a04-7fa38be2c774.png)

As per documentation, one does not create button entities. Button entities are provided by other integrations (similar to e.g., a light or switch entity).

../Frenck
