### ISSUE TITLE
No way to just change the password?

### ISSUE THREAD

**Issue by x046866x** [home-assistant/home-assistant.github.io#22961]
### Feedback

I changed my password in OnCue but can't seem to find where to change it again in HomeAssistant.  I could just delete the device and re-discover, but I fear losing the integrations on the pages I have them organized on.

### URL

https://www.home-assistant.io/integrations/oncue/

### Version

2022.6.0

**Comment by bdraco** [comment]
The Reauth feature is not implemented in this integration.  You'll have to delete it and re-add if you change the password until we build that feature (or do some unsupported, backup first edits to `.storage/core.config_entries`)

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
