### ISSUE TITLE
Note how null feeds will cause ingegration to fail to load

### ISSUE THREAD

**Issue by DrFrankReade** [home-assistant/home-assistant.github.io#22965]
### Feedback

If there are null feeds then the integration won't start, except there's no meaningful data in the logs and nothing in the integration. Suggest document or fix / ignore null feeds instead of just "It's broken" error. 

### URL

https://www.home-assistant.io/integrations/emoncms/

### Version

2022.6.0

**Comment by frenck** [comment]
Hi there @DrFrankReade 👋 

Integrations should not be broken, nor should we document it's just broken. Instead, please report issues with Home Assistant integrations in the Core issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
