### ISSUE TITLE
Changing Origin/Destination

### ISSUE THREAD

**Issue by eigenphase** [home-assistant/home-assistant.github.io#22978]
### Feedback

How can the origin/destination of the sensor.waze_travel_time be changed?

I looked everywhere, literally but there is no option!

This was possible when initially adding the extension. But meanwhile origin (=my HA instance) as well as my work destination changed.

### URL

https://www.home-assistant.io/integrations/waze_travel_time/

### Version

2022.6.1

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
