### ISSUE TITLE
Life360 - integration has stopped working

### ISSUE THREAD

**Issue by gamajunior** [home-assistant/home-assistant.github.io#22973]
### Feedback

I use the life360 integration was working normally but since last night (02 June 2022) it stopped and checking the log the error below appears.

Logger: homeassistant.components.life360.config_flow
Source: components/life360/config_flow.py:56
Integration: Life360 (documentation, issues)
First occurred: 15:12:47 (1 occurrences)
Last logged: 15:12:47

Unexpected error communicating with Life360 server: 403 Client Error: Forbidden for url: https://api.life360.com/v3/oauth2/token.json

### URL

https://www.home-assistant.io/integrations/life360/

### Version

2022.6.1

**Comment by pnbruckner** [comment]
I'm confused. If you've been using the Life360 integration successfully, why are you invoking the config flow?

I.e., that error should only occur when you're trying to add a new Life360 account to Home Assistant via the Integrations page in the frontend/GUI.

How did you add the Life360 account(s) to Home Assistant in the first place? Via the Integrations page, or via configuration.yaml? Have you changed anything recently related to Life360 (e.g., entries in configuration.yaml, or your Life360 account itself, such as your password, ...)?

**Comment by gamajunior** [comment]
I use life360 via integration for more than 6 months, but last night he stopped updating, so I removed the integration and am trying to install the integration but gives error "Unexpected error",

On my phone life360 is working normally where I tested to see if it was something in the password, but the password is ok

**Comment by gamajunior** [comment]
![image](https://user-images.githubusercontent.com/78893093/171968190-2cc6363c-b0eb-42f2-a007-aa59ecddcb23.png)

**Comment by gamajunior** [comment]
![image](https://user-images.githubusercontent.com/78893093/171968276-f848dc18-6c16-45ee-bf4e-5b7f7a8646c8.png)

**Comment by pnbruckner** [comment]
I just tried it myself on 2022.6.1 and it works ok. I don't believe I've ever seen that error before. Not sure what to tell you other than to try again.

**Comment by pnbruckner** [comment]
@gamajunior 
Could you try enabling some debug output and trying again? Add the following to configuration.yaml:
```yaml
logger:
  default: info
  logs:
    life360: debug
    homeassistant.components.life360: debug
```
Then restart HA and try adding the account again. Then check the logs for life360 related messages. There should be more detail that might help diagnose the problem. You'll probably have to look in `home-assistant.log`. Thanks!

**Comment by gamajunior** [comment]
2022-06-04 19:25:53 DEBUG (SyncWorker_0) [life360.life360] Error 403 Forbidden. Reauthorize
2022-06-04 19:25:53 WARNING (SyncWorker_0) [homeassistant.components.life360.device_tracker] get_circles: LoginError: Reauthorize

**Comment by frenck** [comment]
Hi there 👋 

This issue is in the wrong place. It seems like you want to report and debug an issue with an Home Assistant integration, however, it has been submitted as documentation feedback instead.

Please re-create and debug the integration issue here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
