### ISSUE TITLE
Issue with "Scene Editor"

### ISSUE THREAD

**Issue by avviano** [home-assistant/home-assistant.github.io#22979]
### Feedback

I have my computer screens and garden watering system integrated in scenes. Everytime I open the scene editor, my computer screens turn off or in another instance, my sprinkler in the garden turn on. Why does this happen, just when trying to make changes in the scenes editor. Why is there a "hot" and live preview of my device states???? How can I turn that off?? Thank you.   

### URL

https://www.home-assistant.io/docs/scene/editor/

### Version

2022.6.1

**Comment by avviano** [comment]
I am aware that I can make changes in the file editor to my scenes file, but I am not sure what the point of the editor is, if I can't use it (without my screens turning off or sprinklers turning on). Is this a bug or was this done on purpose to cause a stir in peoples homes? Just out of curiousity, why would you turn devices on or off when making changes to the scenes in the editor and without any warning? I don't really get the point of that, but maybe I am missing something here?

**Comment by frenck** [comment]
Scenes are snapshots of current states. When you want to edit one, it needs to restore to that state before it can take a snapshot again. There is no way around this.

../Frenck
