### ISSUE TITLE
Denon AVR and Denon network audio player ASD-3W

### ISSUE THREAD

**Issue by baradetsky** [home-assistant/home-assistant.github.io#22971]
### Feedback

Should the denonavr platform work with the specified device? Does anyone have any experience connecting it?
link for device: https://www.denon.com/en-ca/product/network-audio-players/asd-3
![el_asd3w_front](https://user-images.githubusercontent.com/96811123/171879573-db3527fe-1e75-4f00-8246-ba234b588bd1.png)
![el_asd3w_back](https://user-images.githubusercontent.com/96811123/171879582-334f0502-c202-4560-b6c3-bb98d9ff33c0.png)

### URL

https://www.home-assistant.io/integrations/denonavr/

### Version

2022.6.1

**Comment by starkillerOG** [comment]
I don't know it might work, the DenonAvr integration is mainly written and tested with AVR receivers, but this may be using the same API.
Only one way to find out: just test it.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
