### ISSUE TITLE
After the 2022.6 update, the blinds (Fibaro Yubii) have lost their functionality,

### ISSUE THREAD

**Issue by arnoldpronobis** [home-assistant/home-assistant.github.io#22970]
### Feedback

After the 2022.6 update, the blinds (Fibaro Yubii) have lost their functionality, I can only close. Someone help?
![285889101_5715406691820685_4745216787619138486_n](https://user-images.githubusercontent.com/97227546/171876521-a516739c-92e2-4045-976a-32a16d8ab0b0.jpg)
After the 2022.6 update
![285982253_5715400445154643_6242361321479370441_n](https://user-images.githubusercontent.com/97227546/171876710-96fe388a-51da-4133-8bf6-b5d27bd420f2.jpg)

### URL

https://www.home-assistant.io/integrations/fibaro/

### Version

2022.6.1

### Additional information

_No response
_

**Comment by rappenze** [comment]
Please report issues in home-assistant/core repository. Here you can only report documentation issues. Anyway I created a pull request to fix the issue.
