### ISSUE TITLE
Shelly Plug S wird nicht erkannt.

### ISSUE THREAD

**Issue by Haylorin** [home-assistant/home-assistant.github.io#22987]
### Feedback

Hallo, ich schaffe es nicht meine neuen Shelly PlugS in Home-Assistent einzubinden. 
Die Firmware ist aktuell - 20190516-073020/masterea1b23db
Trotzdem wird das Gerät nicht erkannt. Manuelle Einbindung hab ich versucht, Ergebnis: "Firmware wird nicht unterstützt"
ColoT habe ich aktiviert. Es gibt aber kein Feld wo ich die IP von Home-Assistent und Port 5683 eingeben könnte. 
Ach ja, wo und wie aktiviere ich Unicast ?

Bitte um Unterstützung.
Gruß Steffen

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2022.6.1

### Additional information

![image](https://user-images.githubusercontent.com/100344467/172000108-3a876529-8ba6-41bd-9e40-e73dd31f98db.png)

**Comment by chemelli74** [comment]
Please use English as language to report and comment.

Thank you,

Simone

**Comment by Haylorin** [comment]
Das hilft mir leider überhaupt nicht weiter. Gruß Steffen --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 04.06.22, 14:59 schrieb "probot-home-assistant[bot]" ***@***.***>:

   
  Hey there @balloob, @bieniu, @thecode, @chemelli74, mind taking a look at this feedback as it has been labeled with an integration (shelly) you are listed as a code owner for? Thanks! (message by CodeOwnersMention)

**Comment by thecode** [comment]
This issue is not related to documentation, please create a new issue **in English** in the core repository:
https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml
