### ISSUE TITLE
cant log in

### ISSUE THREAD

**Issue by coogan707** [home-assistant/home-assistant.github.io#22982]
### Feedback

why so hard to log in

### URL

https://www.home-assistant.io/installation/windows/

### Version

2022.6.1

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
