### ISSUE TITLE
Telnet is no longer available on this router

### ISSUE THREAD

**Issue by ReleaseTheHounds** [home-assistant/home-assistant.github.io#23002]
### Feedback

Remote Admin https 442/8443
Local Admin SSH 22/8022

These are the only admin ports exposed. Attempts to telnet to the router address fail.

### URL

https://www.home-assistant.io/integrations/actiontec/

### Version

2022.6.2

**Comment by frenck** [comment]
Hi there @ReleaseTheHounds 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
