### ISSUE TITLE
Multiple station_id's

### ISSUE THREAD

**Issue by speedcore369** [home-assistant/home-assistant.github.io#23001]
### Feedback

Hey,
Is it possible to run multiple station_id under a single sensor?

### URL

https://www.home-assistant.io/integrations/nsw_fuel_station/

### Version

2022.6.2

**Comment by frenck** [comment]
No, that is not possible.

**Comment by nickw444** [comment]
@speedcore369 I believe you can [open a feature request](https://community.home-assistant.io/c/feature-requests/13) on the community forum for this.
