### ISSUE TITLE
BRP072A43 Support

### ISSUE THREAD

**Issue by gdeuss** [home-assistant/home-assistant.github.io#23008]
### Feedback

The controller BRP072A43 is not listed as supported hardware. Is it known to work with HA? I just got one of these controllers with my new Daikin indoor unit in California

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2022.6.2

**Comment by fredrike** [comment]
Well, it could be that your model is untested. Please test the integration and report back.

**Comment by gdeuss** [comment]
Will try it tonight, any specific instructions about how to attempt it? The default config screen I get for the Diking integration is asking for Host, API Key and password. Is there any default password or should it be provided by the device to be integrated? I do have the host info and the API key for sure but am not clear on the pw.

Gustav Deuss
GRD Energy, Inc.
1 Avenue of the Palms, Suite 10C
San Francisco, CA 94130
O 415 891 8824
M 650 291 2569

**Comment by gdeuss** [comment]
Ok, I tested it today and I get the following msg with nothing in the error logs. Running OS 8.1 with Core 2022.6.6 Supervisor 2022.05.3

***@***.***


Gustav Deuss
GRD Energy, Inc.
1 Avenue of the Palms, Suite 10C
San Francisco, CA 94130
O 415 891 8824
M 650 291 2569
