### ISSUE TITLE
No installation Guide or reference

### ISSUE THREAD

**Issue by hifihifi** [home-assistant/home-assistant.github.io#23017]
### Feedback

No installation Guide or reference. This integration can I not find in the HACS or else. Also no info is to find how to install this? This VS version is well good documented, but not the Europe version for Honeywell Evo Home system.

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2022.6.2

**Comment by zxdavb** [comment]
This is an official integration - it wont be - it doesn't need to be - in HACS.

It must be configured by editing your **configuration.yaml** file. If you don't know how to do that, please go to the forums for general community support:

https://community.home-assistant.io/t/official-honeywell-evohome-round-thermostat-integration-eu-only/59733/639

Please close this issue.

**Comment by frenck** [comment]
As mentioned above, this integration does require manual configuration as documented:

![image](https://user-images.githubusercontent.com/195327/172353374-ec1ad051-11c8-4d1a-b1ee-c169b91dddf8.png)


https://www.home-assistant.io/integrations/evohome/#configuration
