### ISSUE TITLE
Include info on setting up Groups of Persons

### ISSUE THREAD

**Issue by dunxd** [home-assistant/home-assistant.github.io#23018]
### Feedback

Setting up a group with persons in it requires manual YAML config.  This approach has a nice presence feature of being able to see if anyone in the group is at home. Make it easier to find this by including details on this page.

### URL

https://www.home-assistant.io/integrations/person/

### Version

2022.6.2

**Comment by frenck** [comment]
Information about groups is documented on the groups integration page:

<https://www.home-assistant.io/integrations/group>

The person entity itself cannot group, hence it is it not documented on this page.

Nevertheless, thanks for your feedback 👍 

../Frenck
