### ISSUE TITLE
Melcloud integration : "cool" mode doesn't work. When "cool" selected, turns on the "fan-only" mode

### ISSUE THREAD

**Issue by jymorel** [home-assistant/home-assistant.github.io#23016]
### Feedback

Melcloud integration : "cool" mode doesn't work. 
When "cool" selected, turns on the "fan-only" mode.
![melcloud - cool mode](https://user-images.githubusercontent.com/96637729/172159644-5724d9d3-23d2-4b00-9f3a-911d23910d0c.jpg)

### URL

https://www.home-assistant.io/integrations/melcloud/

### Version

2022.6.2

**Comment by frenck** [comment]
Hi there @jymorel 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by jymorel** [comment]
Finally not an issue with HA Melcloud integration. After calling Mitsubishi support, it was a Mecloud issue with MSZ AP internal devices. Problerm solved quicky by Mitsubishi. Works now correctly.
