### ISSUE TITLE
What is the default recorder?

### ISSUE THREAD

**Issue by sciurius** [home-assistant/home-assistant.github.io#23027]
### Feedback

> The SQL integration will connect to default recorder if Database URL is not specified.

This is slightly misleading. It turns out it connects to the built-in sqlite version while I would interpret this to mean the database specified with the `recorder` integration.

### URL

https://www.home-assistant.io/integrations/sql/

### Version

2022.6.3

### Additional information

This can be solved in the docs, but it would be better solved by using the database of the recorder integration.

**Comment by gjohansson-ST** [comment]
This is underway to fix it to connect to the recorder instead of just the default recorder: https://github.com/home-assistant/core/pull/71867
Should update the documentation to reflect this change.

**Comment by sciurius** [comment]
Great!

**Comment by sciurius** [comment]
Documentation of 2022.8.1 still mentions that

> The SQL integration will connect to the default SQLite if “Database URL” has not been specified.

So either this is still not fixed, or the documentation requires updating.

**Comment by gjohansson-ST** [comment]
It was clarified in the documentation it connects to the default SQLite db. The fix to connect it automatically to any other recorder db is not merged yet.

So actually this issue should be closed as it's clarified now in the documentation the current behavior.

**Comment by sciurius** [comment]
Ok.
