### ISSUE TITLE
No changes after adding data to yaml

### ISSUE THREAD

**Issue by memberxx** [home-assistant/home-assistant.github.io#23024]
### Feedback

Added IP Address of KLF200 as well as Wifipassword to the yaml but still getting no integration, entity or anything working.Running ha on synology docker

### URL

https://www.home-assistant.io/integrations/velux/

### Version

2022.6.2

**Comment by frenck** [comment]
Hi there @memberxx 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
