### ISSUE TITLE
Only Phase 3 power consumption is read

### ISSUE THREAD

**Issue by fransVolmer** [home-assistant/home-assistant.github.io#23022]
### Feedback

I've just had a new power meter installed since I went from a 1 phase to a 3 phase connection. 
The new meter is a Sagemcom t211 ESMR 5
It is connected using a usb serial converter. 

The connection works fine and data is tranfserred.
The problem I'm having is that only the power consumption of phase 3 is reading values. 1 and 2 are always 0. 
Total power consumption is the same as phase 3. 

Current and voltage values are read for all 3 phases. It looks like for some reason power consumption 1 and 2 are not read

I'm not sure if I'm in the right spot with this issue but any help is appreciated. 

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2022.6.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub tracker for tracking documentation feedback, not for providing support or tracking integration issues.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

In case you'd like to report an issue with an Home Assistant integration, please report it here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
