### ISSUE TITLE
Harrasment on Discord server Homeassistant

### ISSUE THREAD

**Issue by Esimacio** [home-assistant/home-assistant.github.io#23030]
### Feedback

We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.

I moderator in the server was harrasing me
User Thinkerer

Best regards
Esim

### URL

https://www.home-assistant.io/help/

### Version

2022.6.3

### Additional information

The harrasment is also reported to Discord

**Comment by frenck** [comment]
Hi there @Esimacio 👋 

I think you are in the wrong place, you have submitted documentation feedback, but the contents of your message clearly is not related to that.

Please talk about what happened the Discord channels.

Thanks 👍 

../Frenck
