### ISSUE TITLE
Supported formats in documentation

### ISSUE THREAD

**Issue by michal-bartak** [home-assistant/home-assistant.github.io#23039]
### Feedback

HA currently supports 2 formats of mqtt entities:
1. New one (ie for mqtt.switch) has been introduced in 2022.6.
2. Old one is going to be removed before the end of year 2022. 

The documentation doesn't mention any of those facts. Especially doesn't mention that the new format is valid from 2022.6. At the same time integration header contain information 

> The MQTT Switch integration was introduced in Home Assistant 0.7

Which all together leaves an impression that the described (new) format is valid for all versions including prior 2022.6 ones.

It obviously leads to unnecessary confusion and errors (especially while copying code from the community sources like forums), being not able to verify the reasons why the code doesn't work. And this finding is valid for the new format used in older HA versions as well as the old format used in new versions.

Expected state:
The documentation should mention old and new formats, including information about versions that are valid until/since.

### URL

https://www.home-assistant.io/integrations/switch.mqtt/

### Version

2022.6.4

**Comment by frenck** [comment]
Our documentation always reflect the latest release of Home Assistant. If you want to know more about the history, please check out the release notes.

For MQTT there is an exception in place, as the old format is still in the documentation:

![CleanShot 2022-06-08 at 12 09 14](https://user-images.githubusercontent.com/195327/172591350-0d44b55e-c057-4ee1-a5e5-5c97f5447a38.png)

Home Assistant itself will warn you about outdated and/or deprecated configurations, including when and in which versions they are going to be removed. Additionally, the release notes also provides these announcements.

Our documentation is not a changelog.

**Comment by michal-bartak** [comment]
Thanks. I obviously missed the "Previous configuration format" part. It's because it's folded and easy to miss while looking for familiar syntax.

Still, information about date or HA version some features are valid from/to would be useful. You probably consider every user is using the most recent version of HA. But it's not true

> Our documentation is not a changelog.
Nobody is asking for that. 
Just for having access to documentation valid for builds other than the most recent one. Living old documents in the document tree is not that hard. But there are several ways how to do that.

**Comment by frenck** [comment]
> But it's not true

We know, yet, we choose to have the documentation to match the latest version.

> Living old documents in the document tree is not that hard.

Unfortunately, it is and can make things harder for a user as well (as they land on older documentation via search, links in blogs/forums, and other places that no longer match and more of those cases). Hence we, at this point, document the latest state of things.

The recommendation is to upgrade.

**Comment by michal-bartak** [comment]
> Unfortunately, it is and can make things harder for a user as well (as they land on older documentation via search, links in blogs/forums, and other places that no longer match and more of those cases). Hence we, at this point, document the latest state of things.

Understand your doubts. But other software provides such kind of documentation, intensively indexed by google, linked in community pages and I never found it might be the problem. It's all about how it is organized and presented to the reader. 
If the version of the software the document is valid for is exposed enough - there should be no problem. or, IMO there would be less problems comparing to having a lot of examples in the net, which are no more reflectied in official docs.

Recommending an upgrade as a solution for missing documentation is a plain workaround. I understand it costs nothing, but at the same time, it doesn't bring value.

Anyway, thank you for the comment on it.

**Comment by frenck** [comment]
> But other software provides such kind of documentation

We are open to pull requests to implement such features in a maintainable matter. So, if you have ideas on how to do that, feel free to contribute 👍 

../Frenck
