### ISSUE TITLE
unclear info: Tuya Smart or Smart Life app account.

### ISSUE THREAD

**Issue by VNRARA** [home-assistant/home-assistant.github.io#23052]
### Feedback

Does this mean the email adress or the username shown in the app in profile tab?

![image](https://user-images.githubusercontent.com/3942672/172728654-a475d6c2-340a-4ae6-9b83-39665a630cda.png)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2022.6.4

**Comment by frenck** [comment]
> Does this mean the email adress or the username shown in the app in profile tab?

The username is used for logging in.

../Frenck
