### ISSUE TITLE
now().timestamp not listed

### ISSUE THREAD

**Issue by richardsg307** [home-assistant/home-assistant.github.io#23051]
### Feedback

Today I learned that now().timestamp() returns the number of seconds since 00:00:00 1 Jan 1970 (ie the UNIX measure). It was just what I needed but I did not find that in the section on now() in this page.
Can I suggest you add it?

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2022.6.4

**Comment by fabaff** [comment]
There is [`as_timestamp`](https://www.home-assistant.io/docs/configuration/templating/#time).

```text
{{ as_timestamp(now()) }}
```

**Comment by frenck** [comment]
![CleanShot 2022-06-10 at 10 54 31](https://user-images.githubusercontent.com/195327/173029730-c965c912-080e-417e-9728-21adbd43d59f.png)

That brings you to the page fully describing the DateTime object returned. It has many more methods and properties you can use.

<https://docs.python.org/3.8/library/datetime.html#datetime-objects>
