### ISSUE TITLE
The Latest Instructions Do Not Apply to the Latest Version 

### ISSUE THREAD

**Issue by Cannonball57** [home-assistant/home-assistant.github.io#23063]
### Feedback

I filled the instructions and installed https://github.com/home-assistant/operating-system/releases/download/8.1/haos_rpi4-64-8.1.img.xz.  When it said to click on “Configuration” in the HA Sidebar, the only fields were “Developer Tools and Settings.  Nor is there any links to “Supervisor” nor “Restore” for those of us that have backups.
I’ve searched the web and found similar “frustrations”, but absolutely NO explanations from anyone as to why these fields are missing.  One explanation was that Supervisor is NOW within “Configuration.  That great, except there’s NO Configuration.
Can anyone at least give a workable explanation as to what to do?
Other than just close this ticket and say I’m assoholic.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2022.6.4

### Additional information

My current version is HA OS 8.1 with an update to 8.2 pending

**Comment by dannytsang** [comment]
Hi @Cannonball57 

The configuration side bar option has been renamed to Settings. I can see the screenshots and step you have mentioned is out of date so I will attempt to update those soon.

I believe the developer tools are only visible when you enabled **[Advanced Mode](https://www.home-assistant.io/blog/2019/07/17/release-96/#advanced-mode)**. You can do this under your [profile](https://www.home-assistant.io/docs/authentication/#your-account-profile) so:
1. click on your name at the bottom of the side bar
2. Enabled Advanced Mode.

You're correct, the supervisor settings have moved into the Settings menu system.

**Comment by Cannonball57** [comment]
Thank you for your reply. I unchecked Advanced Mode, restarted , logged out and re-logged in…………Developer Tools is still there.  Unfortunately, my “Settings” does not contain Supervisor.  On the command line screen Supervisor Core is loaded, but nothing in the GUI.  And “Restore” is nowhere to be found.

Thanks again
Tom

**Comment by dannytsang** [comment]
Sorry @Cannonball57 I gave you bad advice. If you go back to your profile by click on your name again, there's an option to *Change the order and hide items from the sidebar*
![image](https://user-images.githubusercontent.com/567982/173132021-f82973c1-7709-4d1a-b9dd-f5c9d2c21a96.png)

After pressing the **Edit** button, there's a bunch of "X" including the Developer Tools where you click on to hide the menu option.
![image](https://user-images.githubusercontent.com/567982/173132190-04f14370-027c-4c97-bdf9-45998653137b.png)

The Supervisor menu item no longer exists and all the menu options have been merged into settings. I don't see any references to Supervisor or Restore in https://www.home-assistant.io/getting-started/onboarding/

Are you trying to find the restore from backup/snapshot option?

**Comment by Cannonball57** [comment]
Yes, that worked, I just wish there was an “add items” button.
I was trying to restore a backup after formatting and re-installing.  Neither of my installations ended up having “Snapshot” (included with Supervisor that I also don’t have).  Settings……System….only has General, Updates, backups, logs, Analytics, Network, Storage, Hardware and System Health.
I thank you for trying.  I have the outdated HA running on my Synology Docker and the latest version of HA on the infamous Raspberry Pi 4.  The Synology version is able to control all of my Insteon lights/switches plus my outdated X-10 switches.  The latest 8.1 just can’t do much, but I’ll keep trying.
Take care, Tom
