### ISSUE TITLE
TTS Doc Internal / External URL

### ISSUE THREAD

**Issue by Sparty76** [home-assistant/home-assistant.github.io#23078]
### Feedback

In Core release 2022.5, the TTS "base_url" setting was deprecated and an internal and/or external URL are now expected in configuration.yaml. Additionally, Core log entries also warn of this. However, the 2022.5 release notes point to the TTS documentation page which has not been updated to indicate the format of the internal or external URL settings and still reference "base_url".  An invalid configuration results if base_url: is changed to internal_url: 

Please update the TTS documentation page to indicate the required settings as of v2022.5.

### URL

https://www.home-assistant.io/integrations/tts/

### Version

2022.6.5

**Comment by khaisilk1910** [comment]
Please update information page for TTS : TTS base_url option is deprecated. Configure internal/external URL instead.
How to config  internal/external URL in configurations yaml.

**Comment by frenck** [comment]
The documentation page has been updated, the old parameter is removed and a info note to the core config is shown.
