### ISSUE TITLE
Docs for using Z-Wave OTA updates

### ISSUE THREAD

**Issue by Tipalo** [home-assistant/home-assistant.github.io#23073]
### Feedback

Looking for information for the Advanced features such as OTA.  Unable to see any details on this these docs, nor as a search on the forum.

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2022.6.4

**Comment by raman325** [comment]
Home Assistant currently doesn't support firmware updates natively. To update firmware on zwave-js devices, you currently have to use `zwavejs2mqtt`. We're working on native support but that will be for a future release.
