### ISSUE TITLE
there is no way to use I2C now

### ISSUE THREAD

**Issue by Vector-Int13** [home-assistant/home-assistant.github.io#23079]
### Feedback

Hello, 
I have RPI4B in ARGON-ONE-M.2 
One would think it is a todeal platform for Home Assitant.
It is not. It's a nightmare. I am leaving now..

The first attempt is HASSOS, where the addon doesn't work and reports no access to I2C hardware.
Several days of work follow.
Config.txt does enable i2C, but there is no I2C library in 8.1 and it cannot be installed. All documentation is completely useless. There is no solution to the problem.

So i hawe RPI4B and will try the Supervised mod.
1) The section for RIP4 does not describe the operation of supervised mode.
This is only possible for generic linux!  WHY?

It doesn't even say if it is 64 or 32 bit version and which one I should try.
I have tried all of them. WHY?

The only instructions for supervised mode are not correct. None of it works. 
Not working. WHY?

Within 10 minutes you have the latest RAPSBIAN and you have a fan control in it and it works.
curl https://download.argon40.com/argon1.sh | bash
then config and set it up. Boom that's it.
Can someone explain to me why this is not possible on Homeassistant OS?!!

But you'll never get Home Assistant in there.
Yes, you install the base packages, you install docker. (
Then the official documentation fails completely, but you can deal with that. )
So eventually you install and run Home Assistant in Supervised mode.  
But it reports an unsupported configuration and wants 
AppArmor.  But on the latest version of Raspberrz IP OS actual version , you just don't run AppArmor.

So the result? 
Completely missing information on how to install Supervised mode on RPI. 
In HASSOS I2C is not working and there is no way to do it, while as root I could execute one command, but there is no such option.
AppArmor is not working.  Bz the waz there is no GRUB on the RPI.

Oh and on UBUNTU it reports the official installer by the official procedure,, Error 440 not found in setup.sh .. also not very nice.
Again, completely non-functional documentation.
So even the procedure for generic linux just doesn't work.
Setup.sh error 440
Why is there no working procedure in the documentation? 
I haven't seen such poorly done documentation in a long time.

I just wanted to tell you that the documentation is as leaky as an old woman's mouth and that your latest version of this miracle doesn't even support the stupid fan!!!

### URL

https://www.home-assistant.io/installation/

### Version

2022.6.5

**Comment by frenck** [comment]
The Home Assistant project no longer supports integrations with GPIO (including SPI and I2C busses).

For more information see: <https://github.com/home-assistant/architecture/blob/master/adr/0019-GPIO.md>

If you need help with those, you could try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck

**Comment by Vector-Int13** [comment]
Is there any point in getting upset that that wasn't the point of my post and just one small snippet of the problem? 
I guess it doesn't, does it? 
The intelligence of most of the participants in that thing makes it impossible to solve any more complex problem.
So if I list a few flaws in the documentation, you focus on one thing you can easily say it's solved and that's it.

Congratulations.  Once again, the gold standard of open source has been met. 

However, thank you for the information that fan support on RPI is not important for developers. Rapsberry is currently only occasionally used for HASSO. I'm sure no one will mind. 
Just like no one minds the lack of a Supervised installation description on RPI. (thats irony)

So have a nice and easy day.

**Comment by frenck** [comment]
Your tone in your original post and your follow up doesn't encourage me to actually provide more help to you. Sorry.

For the project, an architectural decision has been made not to support these things. You don't have to agree; however, that is what it is.

A nice and easy day to you to 👍

../Frenck

**Comment by Vector-Int13** [comment]
Yes not supporting is convenient. 
If you find missing or broken parts of the documentation, let us know.
I'll let you know, but you don't like the tone. That really motivates me.
I understand the background behind your decision to stop supporting certain add-ons, however I object to the fact that active cooling for RPI is something that should be supported by the system directly by default. Especially if someone bothers to release a distribution directly on RPI.
I further argue that there is a complete lack of documentation to compare in the docker to RPI.
And the information for getting it to work on general linux is incomplete and non-functional.
You don't want to help me, fine, that's to be expected, but why not help the thousands of other people who rely on that documentation?

**Comment by frenck** [comment]
> Yes not supporting is convenient.

This is not about not supporting for convenience, maybe you missed the point in my responses and linked documentation.

> I'll let you know, but you don't like the tone. That really motivates me.

Sorry to hear that.

> to stop supporting certain add-ons

I think you are mixing up add-ons vs integrations.


>  however I object to the fact that active cooling for RPI is something that should be supported by the system directly by default.

We have no such obligation. You are free to build and support such features yourself; however, the Home Assistant project will not. Read more about the reasoning and the architectural decision linked above.

> I further argue that there is a complete lack of documentation to compare in the docker to RPI.

Please tell us what is missing, as this is a loose statement at this point. Even better: Feel free to open a PR to suggest an improvement.

> And the information for getting it to work on general linux is incomplete and non-functional.

To get what working? In case you are referencing anything GPIO related: Yes, as that is not supported.

> You don't want to help me, fine, that's to be expected, but why not help the thousands of other people who rely on that documentation?

Sure they do, however, your original issue is about something we don't support, and thus is not part of the official documentation. The community resources linked above can provide additional information, support, or documentation in such cases.

../Frenck

**Comment by Vector-Int13** [comment]
HaSSOS version for RPI is released and does not support active cooling. 
It doesn't matter what the reason is for it not working.
All that matters is that a very basic thing is not supported on one of the most widely used platforms.
Sure, if there was an easy way to log in as root and just install a standard Linux module, why not. 
But there is no such option.
You've already used the argument that there's no obligation to do so.
I'm just waiting for you to bring up the popular argument that it's provided for free.  Neither of those things are relevant.
So straight up no need to put a driver to the official RPI power supply that's also too much work.

In fact, it will give quite a big effort to get l2C to work on this system.
It can be done, but the official documentation is absolutely not helpful. 
Nevertheless, I finally got this to work. But I didn't get supervised on the RPI.

I've been commenting on the documentation since the beginning.
And I clearly write that the section on the Raspberry does not give instructions for the Supervised mode.
It just isn't. Supervised is described only for general Linux.
That's what's completely missing now. And as I described right at the beginning there are a lot of problems with the eventual commissioning and one of them has no solution as far as I know now.

If I follow the instructions for general linux I get to error 440. This is currently the result according to the official procedure. If you try it you will find there are quite a few things missing. 

What's probably most obvious is that the whole manual doesn't even hint at what the preferred 32/64 bit variant is on which platform and why. 

The consequence of these things is that although I have one of the best platforms (officially) for this system, it is almost impossible to get it to work properly. The official documentation certainly doesn't help me to do that.
And I think the documentation is meant to help.
Do you think this is the feeling that people should take away from their experience with a home assistant?

**Comment by frenck** [comment]
> HaSSOS version for RPI is released and does not support active cooling.

If that cooling is provided by GPIO: That statement is correct, as I already stated above.

> I'm just waiting for you to bring up the popular argument that it's provided for free. 

I've linked you to project resources providing reasoning and project descriptions. Open source does not mean we have to support every use case.

You clearly don't agree with them; which is fine. Since it is an open-source project that allows running custom integration and third-party add-ons: You are free to add the functionality that way.

> It can be done, but the official documentation is absolutely not helpful.

Correct, we don't support it.

Thanks for your documentation feedback, but I'm ending this conversation as there is no path forward. We do allow custom integrations and add-ons, but we don't support them. You can customize the system any way you like. Therefore, I've linked up the community sources above in my initial response, as that is the place to gain support for that.

../Frenck

**Comment by Vector-Int13** [comment]
Of course, nothing will move forward.
Because again, you completely ignored what I wrote about documentation.  It's incredibly disrespectful.
I don't understand how people like you can fake action.
In the 25 years I've been working in IT I can't understand these pseudo-arguments.
The only thing you wrote is that GPIO is not supported.  But that doesn't refer to non-functional documentation.
Even free work like that is expensive.  I'm sorry, but I expected a professional approach. I was naive.

**Comment by frenck** [comment]
> Because again, you completely ignored what I wrote about documentation. It's incredibly disrespectful.

I did not. I wrote about the reasoning it's not in the documentation, where you can find information about the decision and where to gain possibly more information about your general concern.

Everything else you wrote in your last response I would classify as disrespectful towards this project. As this conversation is leading nowhere; and I've provided information around the original concerns, I'm going to lock this issue.

../Frenck
