### ISSUE TITLE
Firewall Help for New Linux Users

### ISSUE THREAD

**Issue by 22seanster** [home-assistant/home-assistant.github.io#23089]
### Feedback

Hi there! I am a new linux user and I was having issues accessing my home assistant after I installed the docker. The issue was that I needed to allow the firewall on port 8123 on my Linux server. Maybe if this was in the instructions it could help other new Linux users.

Thanks!

### URL

https://www.home-assistant.io/installation/linux/

### Version

2022.6.5

**Comment by frenck** [comment]
Hi there @22seanster 👋 

We don't provide information on your system administration. If you are running an installation method that requires you to do that, we assume you have the knowledge to handle the administration of your system. Considering many different setups (firewalls, dependencies, distributions flavor, and many more), it would become endless documentation.

In case this causes problems for you, we highly recommend using one of our other installation methods instead (e.g., the Home Assistant Operating System; which is a managed environment).

Nevertheless, thanks for your feedback 👍 

../Frenck
