### ISSUE TITLE
Wrong address

### ISSUE THREAD

**Issue by marcinbudziak** [home-assistant/home-assistant.github.io#23088]
### Feedback

Hi,
There is an incorrect URI address in the documentation. In my case, this address worked: https://my.home-assistant.io/redirect/oauth

More about this issue: https://community.home-assistant.io/t/new-spotify-integration-error-invalid-client-invalid-redirect-uri/170070/27

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2022.6.5

**Comment by frenck** [comment]
Hi there @marcinbudziak 👋 

That is exactly what IS in the documentation?

![CleanShot 2022-06-12 at 21 40 21](https://user-images.githubusercontent.com/195327/173250409-e831346a-6fb1-41a5-bd28-773c38c544ca.png)

Am I missing something?

../Frenck
