### ISSUE TITLE
mochad in configuration.yaml

### ISSUE THREAD

**Issue by timothybuchanan** [home-assistant/home-assistant.github.io#23085]
### Feedback

I spent days trying to get mochad to work until I learned of a simple change in the configuration.yaml that was needed. instead of host: localhost, it should read host:127.0.0.1.

### URL

https://www.home-assistant.io/integrations/mochad/

### Version

2022.6.5

**Comment by frenck** [comment]
I am not following, localhost is 127.0.0.1; those are equivalent

**Comment by timothybuchanan** [comment]
The effect is reproducible on my HA, running in docker on an Rpi4B Buster OS. Monitoring with nc, mochad set as localhost does not trigger the TCP daemon or send a signal to the X10 device, but mochad set as 127.0.0.1 does. I think a note in the doc, to the effect that 127.0.0.1 may work when localhost does not, would be a good thing.
