### ISSUE TITLE
Option for disable heat function

### ISSUE THREAD

**Issue by hashtagsandro** [home-assistant/home-assistant.github.io#23091]
### Feedback

Can be integrate a string or something like for disable heat function for disable accidentally press

### URL

https://www.home-assistant.io/integrations/melcloud/

### Version

2022.6.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
