### ISSUE TITLE
whois Integration TLD for DK domains

### ISSUE THREAD

**Issue by Puppetmaster91** [home-assistant/home-assistant.github.io#23098]
### Feedback

Feedback
.DK domains does not work with this integration, but whois through terminal does. 
Also support for DK domains are already added in https://github.com/DannyCork/python-whois/blob/master/whois/tld_regexpr.py

URL
https://www.home-assistant.io/integrations/whois/

Version
2022.6.5

Additional information
Steps to reproduce.
Add integration whois
type google.dk
error: The given TLD is unknown or not available to this integration

Am i doing something wrong?

### URL

https://www.home-assistant.io/integrations/whois/

### Version

2022.6.5

**Comment by frenck** [comment]
Hi there @Puppetmaster91 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
