### ISSUE TITLE
Where is this "system health card"?

### ISSUE THREAD

**Issue by kupietools** [home-assistant/home-assistant.github.io#23099]
### Feedback

I can't submit an issue without providing the "system health card". I don't know what or where this card is. Trying to add it to my dashboard seems to indicate that no such card exists. Simple directions for finding and adding this required card, so I can open an issue that is blocking me from using HA at all, would be appreciated. 

EDIT: Scrolling up from the part of the page the URL from the issue tracker send me to shows me there is a "configuration panel" somewhere in HA that will take me to the "System Health Card". A clue as to where the "configuration panel" is would have been appreciated. 

### URL

https://www.home-assistant.io/more-info/system-health/

### Version

2022.6.5

**Comment by frenck** [comment]
You can find it in the Setting menu -> System -> System Health; or use this My Home Assistant button to navigate directly to it:

[![Open your Home Assistant instance and show health information about your system.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)

When creating an issue on our issue tracker, it is also linked there.
