### ISSUE TITLE
How to write the VRV air conditioner controlled in the KNX system to HomeAssistant?

### ISSUE THREAD

**Issue by shenliushuai** [home-assistant/home-assistant.github.io#23101]
### Feedback

I have a set of central air conditioners that are connected to Daikin, but the control of the air conditioner is controlled by the KNX system. Now I want to add it to HomeAssistant, but I find that the mode of the air conditioner cannot be matched, and there is no wind speed. I don’t know how to set it.
Air conditioning mode: cooling, heating, air supply, dehumidification, automatic
Air conditioner fan speed: low speed, medium speed, high speed, automatic
There are also some central fresh air dehumidifiers that cannot be returned.

Is there a way to solve this problem please? If so what should be done? thanks

### URL

https://www.home-assistant.io/integrations/knx/

### Version

2022.6.5

**Comment by farmio** [comment]
This is an issue tracker for the HA documentations. 
Support and feature requests should be filed at the forums - as you already did - no need to duplicate it here.
