### ISSUE TITLE
Useless

### ISSUE THREAD

**Issue by hbabcot** [home-assistant/home-assistant.github.io#23100]
### Feedback

I have just upgraded the home assitant. Now its knocked of all of my one wire sensors and switch.

Using this HELP page has defeently not helped in anyway. 

There is not any clear wortking example on how to load a single sensors letalone multiple. 

What a waste of time in solving a problem that there was never a problem. once this is fixed i will NEVER update hass again. 

May as well just revert back to the backup. Which i will do now such a waste of time for nothing 

### URL

https://www.home-assistant.io/integrations/onewire/

### Version

2022.6.5

**Comment by frenck** [comment]
I'll close this issue as it is a display of frustration rather than providing documentation feedback. Additionally, this is not the right location to report issues with integrations either.

When in doubt about where to go, please check https://www.home-assistant.io/help for guidance.

../Frenck
