### ISSUE TITLE
Old Version

### ISSUE THREAD

**Issue by weehuddy** [home-assistant/home-assistant.github.io#23103]
### Feedback

Provide a link to older version. 

I need the older version as the new version does not have GPIO 

Thanks i think 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.6.5

**Comment by frenck** [comment]
The links provided on that page, are the installers (that will always install the latest version, regardless if you use an older installer).

I think you are looking for installing a specific version of the Home Assistant Core itself. Which is documented here: <https://www.home-assistant.io/common-tasks/os/#run-a-specific-version>

../Frenck
