### ISSUE TITLE
Occupancy/motion sensor

### ISSUE THREAD

**Issue by JoshB123456** [home-assistant/home-assistant.github.io#23102]
### Feedback

Lost Occupancy/motion sensor provided by SenseME
is it possible to add this as a sensor

### URL

https://www.home-assistant.io/integrations/baf/

### Version

2022.6.5

**Comment by bdraco** [comment]
The new fan firmware does not support the occupancy sensors.  BAF has communicated they plan on adding it back to the fans in a future version.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
