### ISSUE TITLE
Getting Withing integrations working 

### ISSUE THREAD

**Issue by cybernard** [home-assistant/home-assistant.github.io#23106]
### Feedback

So here is how the withings integration works.
First you add the withings integration and homeassistant redirects you to the withings website.
Then assuming you have login into withings it will ask you which profile.
Then it will ask for permission.
After "allow this app" withings attemps a callback to https://subdomain.mydomain.com
Part 1 home assistant doesn't listen on port 443 and withings only REALLY accepts port 443
So inside your firewall you redirect https://subdomain.mydomain.com to https://subdomain.mydomain.com:8123

Now if you have pihole you can add a "local DNS" that internally points https://subdomain.mydomain.com to https://homeassistant.local via ip address.  However, due to a change from external to internal traffic https transitions to 443 and port 8123 is lost and failure occurs.

This smooths over some of the problems.

However, the process takes you back to YOUR web browser and home assistant attempts uses your PC as part of the process and this is where things break.  
**I deleted the client_id and state id for privacy reasons, don't delete these codes.**

Your PC's web browser is preforming this action, and NOT homeassistant.
> https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id= <redacted>?redirect_uri=http%3A%2F2Fwww.mydomain.com%3A8123%2Fauth%2Fexternal%2Fcallback&state= <redacted>

This was my first mistake, I included the port number and withings isn't ok with 8123.  So I had to go into networking on home assistant and remove 8123 and use iptables to forward the traffic.  This lost of port 8123 will cause us problems in the future.

You pass withings a callback address and url with codes.

The process then returns on your web browser with a code https://subdomain.mydomain.com?code=<random characters>
It is at this point process breaks because port 8123 is lost.
You need to go into your web browsers URL and change https://subdomain.mydomain.com this to https://subdomain.mydomain.com:8123 leaving the code and everything else untouched.

The process will now complete normally.
You will still get error 293 in your logs for whatever reason.

This is troubleshooting information to help those people unfortunate enough to just have it work.

First check **Settings**-> **System** ->**Network**
Then scroll down here
Home Assistant URL
Then make note of what it says for **Internet**.
![image](https://user-images.githubusercontent.com/15042777/173721324-8f295535-bb26-4d4e-94b0-b66d3e3fa570.png)

This name will be critical in the process and needs to be your external DNS name and because of withings it is needs to be **https** or withings will flag it in restricted mode.  I don't know if this is an actual problem, but if you don't want restricted mode use **https.**

Here letsencrypt can provide you with a valid SSL certificated for **https**.

Next up IP forwarding
If your using linux and have iptables installed on a firewall

`iptables -t nat -I PREROUTING 2  -p tcp -m tcp -m multiport --dports 80,443 -s 89.30.121.150/24 -j DNAT --to-destination 192.168.1.2:8123`

Things that are noteworthy:
The 89.30.121.150/24 represent the sever I got from withings.  
The 192.168.1.2:8123 is the internal IP address of your homeassistant
![image](https://user-images.githubusercontent.com/15042777/173721878-ffa6e54a-78a3-4f5c-9041-433345a9ea0d.png)
Here is the server name.
You need to do a nslookup or ping to obtain the ip address of the withings server.
The **whois** command will give you a range of IP address to forward to your home assistant.

![image](https://user-images.githubusercontent.com/15042777/173722217-668f87fe-41ef-4739-95ae-eeb6ae7a4804.png)

Here you will see the inetnum which will give you the IP range which you can convert to a /24 or whatever it is for you.
Now only the correct traffic will come here, and it won't interfere with you running your web server as only 255 ip address are directed to your home assistant.

Next its time to install the withings component.
You will have to provide it the ClientID, Secret, and callback address from the withings developer website.

This is what I used and eventually got to work for my callback address.

> https://www.mydomain.com/auth/external/callback

Now after clicking OK

You will be directed to withings website to select your profile and then authorize the application.

Right after this I encounted my 1st stumbling block as I got:
The URL mismatch error, and a blank website.

Troubleshooting:
Copy and paste the URL into notepad

Now you can carefully examine the part of the URL after the redirect= value to see what is wrong.
First make sure the domain name is your domain name assigned to your external IP address.  You could use a dynamic DNS service to handle this part.  Make sure it has https and not http.  Also everything is correct with the rest of your callback link.

After you have corrected ALL of these errors you can now try again.
You should be able to next to the next roadblock now.

The next problem I encountered is another blank page, and again we need to examine the URL.
https://www.mydomain.com:8123/auth/external/callback?code= big random code  state= another random code

At this point I had to remove the https, from the web browsers URL, and make it http because your web browser will give you a SSL error message if you don't.  Also you may have to modify your computers host file temporarily to point www.mydomain.com to your Home Assistant's internal IP probably starting with 192.168.x.x or 10.x.x.x

After changing the host file, and changing https to http and hit ENTER I was able to move on to the final step.

I was then redirected to the homeassistant.local:8123 website.  It prompted me to login with the username and password.
Then it asked me what I would like the profile named.
I entered the profile name I wanted and I was done.

I rebooted Home Assistant and everything populated as unavailable.

So I went and weighed my self, and then came back and reload the withing add on.
Then I went to the debug screen and the "State" tab.  I then search for withings and Low and behold my scale had populated the relevant scale values.

Unfortunately my sleep sensors was still unavailable and a bunch of the entities were disabled.
I re-enabled ALL of the entities and reload the withing integration.
Some of the values now had values, but a number of them still said unavailable.

I was also getting this error message in the logs:
Unexpected error fetching subscription_update_coordinator data: Error code 293 8:23:59 AM – (ERROR) Withings

After today's home assistant update it seems to have stopped, but its has ONLY been 1 day so only time will tell if its really gone for good.

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2022.6.6

### Additional information

It took a great deal of effort to troubleshoot my errors.

**Comment by cybernard** [comment]
I have no idea how that happened or how to change it.

**Comment by cybernard** [comment]
I spoke too soon the error returns.
Logger: homeassistant.components.withings
Source: components/withings/common.py:705
Integration: Withings (documentation, issues)
First occurred: 8:44:49 PM (4 occurrences)
Last logged: 8:56:03 PM

Unexpected error fetching subscription_update_coordinator data: Error code 293
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/usr/src/homeassistant/homeassistant/components/withings/common.py", line 663, in async_subscribe_webhook
    return await self._do_retry(self._async_subscribe_webhook)
  File "/usr/src/homeassistant/homeassistant/components/withings/common.py", line 659, in _do_retry
    raise exception
  File "/usr/src/homeassistant/homeassistant/components/withings/common.py", line 648, in _do_retry
    return await func()
  File "/usr/src/homeassistant/homeassistant/components/withings/common.py", line 705, in _async_subscribe_webhook
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/withings_api/__init__.py", line 348, in notify_subscribe
    self.request(path=self.PATH_NOTIFY, params=params)
  File "/usr/local/lib/python3.9/site-packages/withings_api/__init__.py", line 115, in request
    return response_body_or_raise(
  File "/usr/local/lib/python3.9/site-packages/withings_api/common.py", line 830, in response_body_or_raise
    raise InvalidParamsException(status=status)
withings_api.common.InvalidParamsException: Error code 293

**Comment by frenck** [comment]
Hi there @cybernard 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report an issue with an integration here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
