### ISSUE TITLE
Devolo: how to enable disabled sensors

### ISSUE THREAD

**Issue by thomas-svrts** [home-assistant/home-assistant.github.io#23114]
### Feedback

The documentation mentions that some sensors are disabled by default. But it isn’t mentioning how you can enable it. 

Is it via a homeassistant property? Or maybe via the Devolo app?

### URL

https://www.home-assistant.io/integrations/devolo_home_network/

### Version

2022.06.05

**Comment by Shutgun** [comment]
Hi @thomas-svrts , 

you should use the Home Assistant default way to enable entities:

![grafik](https://user-images.githubusercontent.com/20171515/173842342-9c22a341-aa34-4fdc-9de0-e5b11610df91.png)

**Comment by thomas-svrts** [comment]
Thanks, stupid me that I didn’t see that
