### ISSUE TITLE
Allow Input Boolean as an Input

### ISSUE THREAD

**Issue by daelsc** [home-assistant/home-assistant.github.io#23118]
### Feedback

I'd love to use an Input Boolean as an input to convert to a lock entity.

### URL

https://www.home-assistant.io/integrations/switch_as_x/

### Version

2022.6.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
