### ISSUE TITLE
Not sure if this is documentation\feature\bug: Cannot set AutoComfort Temp via automations

### ISSUE THREAD

**Issue by samsonusmc** [home-assistant/home-assistant.github.io#23119]
### Feedback

Cannot set AutoComfort Temp via automations. 

### URL

https://www.home-assistant.io/integrations/baf/

### Version

2022.6.6

**Comment by jfroy** [comment]
You can use the `climate.set_temperature` service. https://www.home-assistant.io/integrations/climate/#service-climateset_temperature

**Comment by samsonusmc** [comment]
Sigh.. sorry... that was too simple. Still learning! Thank you!!
