### ISSUE TITLE
Conditional card OR

### ISSUE THREAD

**Issue by macbrook98** [home-assistant/home-assistant.github.io#23123]
### Feedback

The conditional card currently doesn't have the ability to use the OR operator. This limits its useability. 

### URL

https://www.home-assistant.io/dashboards/conditional/

### Version

2022.6.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
