### ISSUE TITLE
Cant setup Home Connect. Didnt ask anything

### ISSUE THREAD

**Issue by fedottt** [home-assistant/home-assistant.github.io#23126]
### Feedback

hi
i try re-setup (firstly i setup integration in yaml few year ago) via interface (push "add integration", search "home connect"..)
when i finding "Home Connect" in integration list and click on it, browser redirect me to the site **api.home-connect** WITHOUT promt to enter anything. I cant enter clientID or something else.
and link to "api.home-connect" is wrong (i get "error": "unauthorized_client")
so, i use full link, push in it right link to my HA, successfully login to home-connect-api and when i return to my HA from API i get message "Error" without any description or something else((
in logs i cant find any errors
so, i think, problem is that integration didnt ask me for credentials. 
maybe it stored in some files or cache? 

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2022.6.6

**Comment by sandervandegeijn** [comment]
Confirmed, same problem :)

**Comment by frenck** [comment]
Hi there, it seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

As for this specific integration documentation, I set up Home Connect myself yesterday using this documentation (for verification for another report) and it concluded it the existing documentation is correct.

../Frenck
