### ISSUE TITLE
Threshold integration cant use helper as values

### ISSUE THREAD

**Issue by farbefreak** [home-assistant/home-assistant.github.io#23137]
### Feedback

Hello Guys, 

I think it would be nice if the Threshold integration could use helper values (like a number) to compare against.
I tried "{{ states('input_number.test') }}" as an input for upper / lower value but it does not work. So i assume templates also dont work. 

I think this would be quite nice to input helpers directly, this way, the threshold could be set easily.

### URL

https://www.home-assistant.io/integrations/threshold/

### Version

2022.6.6

**Comment by fabaff** [comment]
This is the issue tracker. Please use the forum for [feature requests](https://community.home-assistant.io/c/feature-requests). Thanks

**Comment by farbefreak** [comment]
Thanks for the feedback. I just used the button on the bottom of the documentation page. 
Link: https://www.home-assistant.io/integrations/threshold/
Just now i realized that its for providing feedback for the page itself not the integration.
