### ISSUE TITLE
Energy date picker - compare not working on custom dashboards

### ISSUE THREAD

**Issue by Yardco** [home-assistant/home-assistant.github.io#23136]
### Feedback

The Energy date picker can be used to influence the data shown in all other energy cards. This works in the default energy dashboard as well as custom dashboards. In 2022.6 the compare feature was introduced, but this new functionality only works when used in the default energy dashboard, not in custom created dashboards. 

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2022.6.6

**Comment by Yardco** [comment]
👍

**Comment by ludeeus** [comment]
This section is to provide feedback for the documentation not to request features to be added.
Please raise feature requests on the forums <https://community.home-assistant.io/c/feature-requests/13> 👍
