### ISSUE TITLE
Preset support for c8w pro 2k

### ISSUE THREAD

**Issue by kakarotto185** [home-assistant/home-assistant.github.io#23133]
### Feedback

Hi,
Is there a possibility to controll presets for ezviz cameras? C8w pro 2k has the possibility to assign presets for the camera position in the ptz controls within the app. Is it something that could be integrated to home assistant?

Kind regards,

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2022.6.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
