### ISSUE TITLE
Manuel Station adding

### ISSUE THREAD

**Issue by Leedrag** [home-assistant/home-assistant.github.io#23148]
### Feedback

Why is there any chance to add stations manually?
I have to drive a 150km route twice a week so i need more radius but then the list is too long.

### URL

https://www.home-assistant.io/integrations/tankerkoenig/

### Version

2022.6.6

**Comment by guillempages** [comment]
You can add more than one instance of the integration with a small radius
each time; that way you will achieve the same as before with the
"additional stations", but without having to refer to an extra page to get
the IDs.

Currently there are no plans for manually adding stations by id

probot-home-assistant[bot] ***@***.***> schrieb am Mo., 20.
Juni 2022, 16:20:

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
