### ISSUE TITLE
Integration Backup

### ISSUE THREAD

**Issue by bobmoran00** [home-assistant/home-assistant.github.io#23147]
### Feedback

Full marks for documenting backups but, a total fail for not one mention of restoring said backups.  With all the 'Deprecations' I really need to go back a bit and recover.

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2022.6.6

### Additional information

All my mqtt devices have become unavailable after upgrading.

**Comment by frenck** [comment]
> a total fail for not one mention of restoring said backups

Those backups are compressed archives, extract them? Any major operating system can just do that nowadays (just by clicking on them).

Maybe I'm missing the point though?

../Frenck

**Comment by EffeDEffe** [comment]
On the same page it says: 

> The Backup integration allow you to create and download backups for your Home Assistant Core and Home Assistant Container installations.

but this doesn't seem true at least for Home Assistant Container installations.

Adding `backup: `to the configuration.yaml turns out in a
Component error: backup - Integration 'backup' not found. 

I know that containerized installations are deprecated but on the same page, it says that backup files are useful for migrating to OS installations.

**Comment by reefland** [comment]
@frenck - if that is how restores are to be completed, then the documentation should state such. A supported way to perform a restore should be part of the documentation if you are going to provide a backup facility. 

Have to agree with @bobmoran00, as it is now, you can backup but not restore.  Heck you can't even upload a backup to a new instance.  It seems useless for core or container installations -- unless all you want to due is make a backup and download it for a migration to HA OS. 

For others, if you do extract the backup file, within it you will find another archive `homeassistant.tar.gz` and you will have to extract that file to perform an actual restore.
