### ISSUE TITLE
Unclear integration instructions

### ISSUE THREAD

**Issue by kekonn** [home-assistant/home-assistant.github.io#23146]
### Feedback

When checking out this integration, I noticed that it asks for account credentials. But it is entirely unclear which credentials have to be entered? Those of the selected hub? Overkiz credentials? If the latter, where do I go to create that account?

### URL

https://www.home-assistant.io/integrations/overkiz/#tahoma-switch

### Version

No, it's not at the bottom

**Comment by tetienne** [comment]
Hi, I don’t get what’s unclear. When you want to install the component, you got this message:

> The Overkiz platform is used by various vendors like Somfy (Connexoon / TaHoma), Hitachi (Hi Kumo), Rexel (Energeasy Connect) and Atlantic (Cozytouch). Enter your application credentials and select your hub.

And more specifically:

> Enter your application credentials and select your hub.

It’s pretty clear IMO. If you own a Tahoma, then you have the associated application on your phone. Same for Rexel, Cozytouch, etc. So just use the credentials for *your* dedicated application

**Comment by kekonn** [comment]
I was on the fence if it was more like the Tuya integration. For someone who might not be familiar with all the listed platforms and how they work, it's not entirely clear.

A suggestion for the wording of the second sentence: 
> Enter the credentials of the application you selected in the Hub list:

EDIT:
And perhaps also make the hub selection the first item on the config screen so that it reads:
- hub
- username
- password

**Comment by iMicknl** [comment]
@kekonn we are adding local support for the Somfy TaHoma hubs, which will change the config flow. I will take your concerns into account. For now; the new flow will first ask for the hub, and in a separate prompt it will ask the additional details.
