### ISSUE TITLE
Add section for Windows WoL support

### ISSUE THREAD

**Issue by versionDefect** [home-assistant/home-assistant.github.io#23155]
### Feedback

Hello! I was having alot of trouble trying to figure out why my Windows machine wasn't allowing for state updating with WoL switch. Long story Windows 11 for whatever reason does not allow for pinging of their machines so adding a little note suggesting that there be a firewall change would've been super helpful for other dunces like me lol. 

### URL

https://www.home-assistant.io/integrations/wake_on_lan/

### Version

2022.6.6

### Additional information

if you want to do into detail the way I fixed my issue was in the "Windows Defender Firewall with Advanced Security" then to inbound rules on the left side. "File and Printer Sharing (Echo Request - ICMPv4-In)" Then to properties -> advanced then "Specify profiles to which this rule applies to" Check the box that your current windows network setting is (like private or public)

**Comment by ntilley905** [comment]
Feel free to suggest an edit on the documentation [here!](https://github.com/home-assistant/home-assistant.io/blob/fea80feded23baca2804b279a17d476390aa8df3/source/_integrations/wake_on_lan.markdown) I don't have the requisite knowledge of Windows 11 (all Linux machines) so I would prefer someone who does have that experience add the note.

**Comment by versionDefect** [comment]
as terrible as this sounds. I'm super new to github. Where would I suggest an edit?
