### ISSUE TITLE
Download Diagnostics

### ISSUE THREAD

**Issue by highincolorado** [home-assistant/home-assistant.github.io#23150]
### Feedback

I was looking to get some information on the Tuya integration so I punched download diagnostics. I can not find the download, looking at help for this function doesn’t give a clue where to find the file or what it might be called. 

Thanks!

### URL

https://www.home-assistant.io/integrations/diagnostics/

### Version

2022.6.6

**Comment by frenck** [comment]
Screenshot from the page you left a comment on:

![image](https://user-images.githubusercontent.com/195327/174633673-d8fa774a-8ce1-414f-8f5b-ef7e0b0e67b0.png)

I'm not sure how to make that any clearer, could you provide a suggestion on how you suggest it should be improved?

**Comment by highincolorado** [comment]
Thanks for the reply, maybe I am being dense (not the first time), but I know where to click, touch or tap the download diagnostics option what I don’t know or see is where does the text file appear for me to look at and what is it called?

I have pressed it a few times and can find no diagnostic text file

**Comment by frenck** [comment]
Normally, when you press it, a file download is initiated (as the button suggests, it's a download). Depending on your system of browser setup, it will either ask you where to store it or downloads it into your default file download location.

In case absolutely nothing happens or downloads, you might want to check the Home Assistant log to see if an error occurred.

**Comment by highincolorado** [comment]
OH I was expecting it to be on the local file system of the HA server. I am sitting on the couch with my Apple iPad so it’s using the app not a browser! Perhaps this function needs to be greyed out if not in a internet browser window? I will move to my office and try again from the computer.

Thanks again!
![9DABBD84-926A-4236-B7F8-7E83A186D1B2](https://user-images.githubusercontent.com/60855018/174637465-73703555-1970-45a2-88dd-432f65b87e31.png)

**Comment by frenck** [comment]
> Perhaps this function needs to be greyed out if not in a internet browser window? 

The app is an internet browser window.

I'm not sure, isn't this a bug with the app?

**Comment by highincolorado** [comment]
Certainly not a question I can answer,lol. 

In my ~50 years of computing I have seen the terms upload and download be based upon the perspective of the person using the terms, I normally think of the computer I am at as the place things are downloaded from and the remote device the be uploaded from so I am always a bit cautious due to the problems that arise if I assume incorrectly. This was especially rough with the very many industrial devices I have worked with.

**Comment by frenck** [comment]
> Certainly not a question I can answer,lol.

Hehe, for what it's worth... I don't know either 😝 

I'll ask around 👍

**Comment by frenck** [comment]
This is a known and reported issue upstream (as I've been told).

Please follow the issue here:

<https://github.com/home-assistant/iOS/issues/2058>

../Frenck
