### ISSUE TITLE
description unclear

### ISSUE THREAD

**Issue by dibi73** [home-assistant/home-assistant.github.io#23159]
### Feedback

i have read the description on https://www.home-assistant.io/integrations/local_ip several times. it is still unclear to me what this integration does or under which name the Server should be reachable

### URL

https://www.home-assistant.io/integrations/local_ip/

### Version

2022.6.6

**Comment by hugodejong** [comment]
It creates a sensor entity in Home Assistant that shows the LAN IP address of your Home Assistant server. Like this (example from my server):

![image](https://user-images.githubusercontent.com/53058265/174819310-08096f3d-30d9-44fa-b991-a6f262e99d6a.png)
