### ISSUE TITLE
Switchbot - Thermoter/Hygrometer fails to configure with the Switchbot intergration

### ISSUE THREAD

**Issue by mikeatrothvoicedotcom** [home-assistant/home-assistant.github.io#23158]
### Feedback

The device connects to my phone via blue tooth and the Switchbot app works on my phone.
The switchbot Intergration with Home Assistant fails to configure.  even after I connect the device's bluetooth to either my phone or my PC. 

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2022.6.6

**Comment by mikeatrothvoicedotcom** [comment]
Yes, I left the feedback.
I want to intergrate the Temperature and Humidity from a Switchbot device, but although the device is paired via bluetooth, the switchbot intergartion fails to configure

**Comment by Nardol** [comment]
Is this integration for all Switch Bot products?
I thougth it is only for bots.

**Comment by mikeatrothvoicedotcom** [comment]
It does not work for thermometer



Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: Patrick ZAJDA ***@***.***>
Date: 7/8/22 7:06 AM (GMT-05:00)
To: "home-assistant/home-assistant.io" ***@***.***>
Cc: Mike Roth ***@***.***>, Author ***@***.***>
Subject: Re: [home-assistant/home-assistant.io] Switchbot - Thermoter/Hygrometer fails to configure with the Switchbot intergration (Issue #23158)


Is this integration for all Switch Bot products?
I thougth it is only for bots.

**Comment by marktay** [comment]
I got the meters, motion & contact sensors and humidifier working in yaml using the api and Smart House's guide here: https://www.youtube.com/watch?v=ZLsTgXILabE

**Comment by klaasnicolaas** [comment]
Hi there @mikeatrothvoicedotcom  👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
