### ISSUE TITLE
Note regarding over-polling is not clear enough

### ISSUE THREAD

**Issue by andrewnicols** [home-assistant/home-assistant.github.io#23157]
### Feedback

We have a new GoodWe GW5K-DT inverter, and I've had to reduce the poll time to /5.

I feel that the Note regarding over-polling is understated, and that the poll frequency is not informative enough. I tried with 30 second, 1 minute, and even 2 minute polling, and still lost data sent to the SEMS portal.

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2022.6.6

**Comment by frenck** [comment]
I've read it, and found it pretty clear. Could you provide a textual suggestion on how you would change the text? (e.g., by providing a newer text that you think is better)

**Comment by andrewnicols** [comment]
I've opened a PR to update a few things:

- wording to suggest that this is more common than 'rare'
- suggestions for longer time periods on polling (up to 5 minutes from previously commented 1 minute)
- adding this as a reason to specify the trigger to better link the configuration example with the reasons for doing so
- suggesting multiple entities to make the configuration example more representative of the type of configuration that would be employed
