### ISSUE TITLE
apparamon unsupported please need some help

### ISSUE THREAD

**Issue by noemisanalex** [home-assistant/home-assistant.github.io#23151]
### Feedback

` sudoedit /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT = "apparmor=1 security=apparmor"

 sudo aa-status
apparmor module is loaded.
apparmor filesystem is not mounted `

### URL

https://www.home-assistant.io/more-info/unsupported/apparmor/

### Version

2022.6.6

### Additional information

its wrong pleace?
where I can write apparmor=1 security=apparmor?
please be concret step by step to do this thankyou

**Comment by frenck** [comment]
Thank you for reaching out.  We use this GitHub issue tracker for tracking documentation suggestions, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
