### ISSUE TITLE
Install Home Assistant Core missing PATH configuration

### ISSUE THREAD

**Issue by dfquicazanr** [home-assistant/home-assistant.github.io#23152]
### Feedback

Before running the hass command you should run 
`PATH=$PATH:/home/homeassistant/.local/bin`
If not, hass is not going to be found

### URL

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core

### Version

2022.6.6

**Comment by frenck** [comment]
That should not be needed, if so, you missed creating the virtual environment that is documented as well (which would have contained the full Home Assistant environment in the venv folder and thus not use your home folder at all).

../Frenck
