### ISSUE TITLE
CUL-USB -> HomeMatic Support 

### ISSUE THREAD

**Issue by dominikandreas** [home-assistant/home-assistant.github.io#2316]
FHEM supports controlling HomeMatic Therostats and other devices using a CUL USB Stick (868MHz) instead of using a CCU. I wasn't able to find anything related to this in home-assistant. 

As I'm quite new to this field I wanted to ask if anyone was able to do this or knows how to get this running. Thanks for your support, home-assistant looks like an awesome project and getting support for interfacing HomeMatic devices directly would be great!

Relevant resources: 
- [German Tutoral](https://techblog.one/homematic-mit-der-cul-guenstig-unter-fhem-einbinden/) for adding HomeMatic devices in FHEM using a CUL USB Stick, 
- and [english translation](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Ftechblog.one%2Fhomematic-mit-der-cul-guenstig-unter-fhem-einbinden%2F&edit-text=&act=url) using google translate

**Comment by MartinHjelmare** [comment]
Hi! Please ask this question in the forum or on gitter. We'd like to keep the issue tracker for bug reports and ongoing development tasks only.

https://home-assistant.io/help/

**Comment by dominikandreas** [comment]
will do, thanks!
