### ISSUE TITLE
"Settings" is called "Configuration" in my home assistant.

### ISSUE THREAD

**Issue by hannamand** [home-assistant/home-assistant.github.io#23161]
### Feedback

Name change?  Older version?  Confusing for a beginner.

### URL

https://www.home-assistant.io/docs/automation/editor/

### Version

2022.6.6

**Comment by frenck** [comment]
The name has changed in Home Assistant 2022.5, see: <https://www.home-assistant.io/blog/2022/05/04/release-20225/>

The documentation always reflects the latest stable Home Assistant release. Are you running an older version than 2022.5?
