### ISSUE TITLE
Dating Articles  

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#23160]
### Feedback

Is it possible to put a DATE in the articles (like this one:  https://www.home-assistant.io/integrations/google/)  so that folks know when it was posted (updated)?  

This one in particular with the changes to the HA 2022.6 and Google Calendar integration - as mine are now broken. 

### URL

https://www.home-assistant.io/integrations/google/

### Version

2022.6.6

**Comment by allenporter** [comment]
Not aware of any best practice for this. Not sure about this specific suggestion to add a date.

Generally the release notes contain information about breaking changes.

In particular, https://github.com/home-assistant/home-assistant.io/pull/22980 may have the information you're looking for which has not been reviewed yet.

**Comment by allenporter** [comment]
btw  2022.6 didn't have anything new that broke the integration i'm aware of, though did make adjustments and deprecations, everything should keep working. That is, if you downgrade to 2022.5 i doubt something would be fixed?

**Comment by bearhntr** [comment]
I am just trying to get rid of these 'depreciated' warnings in the logs.   I see them, and it drives me bonkers.  LOL 

I am too anal-retentive I guess, warning and errors are pet-peeves.  

Trying to figure out how to best get rid of them without having to re-do the whole Google Calendar integration (and hoping that the Google Home is not broken too).  


Curtis Norris

---------------------------------------------
☝ Message is being sent via the web version of COMCAST e-mail,
please ignore any formatting issues you may encounter.

**Comment by frenck** [comment]
> Is it possible to put a DATE in the articles (like this one: [home-assistant.io/integrations/google](https://www.home-assistant.io/integrations/google/)) so that folks know when it was posted (updated)?

This is not possible; has been requested before and attempts to do so caused dramatic deployment delays.

Our documentation always reflects the latest stable version of Home Assistant.

> I am just trying to get rid of these 'depreciated' warnings in the logs.   I see them, and it drives me bonkers.  LOL

It sounds like you are in need for support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places. Share the error you have in those locations and I'm sure people will be able to point you in the right direction.

Thanks! 👍


Closing the issue on this end.
