### ISSUE TITLE
Adjusting Colors for Google Calendar

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#23164]
### Feedback

Is it possible to adjust (set the colors) for the various entries which can be pulled into HA from the Google Calendars?  

![Google_Calendar_Colors](https://user-images.githubusercontent.com/100164602/174881447-ff9f1dc0-71eb-4e93-a567-0c4dbcc29ff5.PNG)

### URL

https://www.home-assistant.io/integrations/google/

### Version

2022.6.6

**Comment by allenporter** [comment]
I'm not aware of any way to do this at the moment but you're welcome to discuss or file a feature request at https://community.home-assistant.io/c/feature-requests/13
