### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by djcrawleravp** [home-assistant/home-assistant.github.io#23163]
### Feedback

I have tried everything I could but can't connect my jellyfin docker container to my homeassistant (Same network)

### URL

https://www.home-assistant.io/integrations/jellyfin/

### Version

2022.6.6

**Comment by RunC0deRun** [comment]
Hi there, could you please re-open this issue on the Home Assistant core repository? https://github.com/home-assistant/core/issues This issue tracker is only for documentation issues.

When you re-open can you attach the logging Home Assistant generates when you try to connect? If you don't get any meaningful logging you can enable more detailed debug logging by setting the following in your configuration.yaml:

```
logger:
  default: warning
  logs:
    Jellyfin: debug
```

**Comment by frenck** [comment]
As per above, please file issues in the core repository. If you are in need of support: please use our community forums or Discord chat server.
