### ISSUE TITLE
The form in the integration page has fields with no info

### ISSUE THREAD

**Issue by Pixelalb** [home-assistant/home-assistant.github.io#23179]
### Feedback

What should I write in? Tried my email/pass that I use with my yale app, tried with the phone number... no luck. It wont let me log in. What is that form? What is Area ID??

### URL

https://www.home-assistant.io/integrations/yale_smart_alarm/

### Version

2022.6.7

**Comment by gjohansson-ST** [comment]
Given your questions I think you are looking for the August integration and not this one. 

Also issues off this kind should be opened in the core repository and not here as it's issues on the documentation itself.

**Comment by Pixelalb** [comment]
Thank you

**Comment by frenck** [comment]
Closing this issue, as it seems resolved.
