### ISSUE TITLE
Frontends of some modules do not work on current Brave Browser

### ISSUE THREAD

**Issue by promofu** [home-assistant/home-assistant.github.io#23173]
### Feedback

I am using Brave on Ubuntu Linux and since recently I noticed that at least the Frontends of "Terminal", "File Editor" and "InfluxDB" are not accessible anymore whereas they are in my setup using Firefox.

Of course I am willing to add more to this issue and if necessary I would not mind to regularly check / report / test Brave compatibility if there is such a process.

### URL

https://www.home-assistant.io/docs/frontend/browsers/

### Version

2022.6.6

### Additional information

HASS OS 8.2

Brave 1.40.105 (based on Chrome 103.0.5060.53)

**Comment by promofu** [comment]
Of course I did disable Braves Website security features for my local installation.

Also I checked the Dev Console and found some CORS related rants there when accessing "File Editor":

![image](https://user-images.githubusercontent.com/4403465/175030003-34661f90-5ce2-4efc-8bbf-a1fe2196c272.png)

I do currently NOT access HomeAssistant through HTTPs which might also play a role here.

What are these resources being pulled from Google Drive anyway ?

**Comment by frenck** [comment]
> Frontends of "Terminal", "File Editor" and "InfluxDB" are not accessible anymore whereas they are in my setup using Firefox

These are frontend of external software, not Home Assistant. Additionally, this issue tracker is used to collect feedback for the Home Assistant documentation. For those reasons, this issue is in an incorrect issue tracker.

Please report issues upstream with the authors of the software.

Thanks 👍 

../Frenck

**Comment by promofu** [comment]
So just to make sure:

If I would want to have some Entry for Brave (as mentioned above) on that Page I am ok here ... but the fail of those Apps I shall report in other places... got that.

So please add the Brave Browser to that Compat page if you might

**Comment by frenck** [comment]
> So please add the Brave Browser to that Compat page if you might

That page is about Home Assistant, not the third-party applications that can be iframed. As said, feel free to report those upstream.
