### ISSUE TITLE
SUNSET/SUNRISE CONDITION description contradicts itself

### ISSUE THREAD

**Issue by roabyd** [home-assistant/home-assistant.github.io#23184]
### Feedback

As a home assistant newby (and an experienced developer) I had to learn that the sunset/sunrise trigger had to be used in a specific way in order to achieve 'when dark' condition. This is accurately described in the first screenshot: 
![image](https://user-images.githubusercontent.com/55369460/175175022-c0ecec74-da12-4edb-9dfa-e5dcd97f0a1c.png)
However this is then directly contradicted below with a false statement:
![image](https://user-images.githubusercontent.com/55369460/175175483-fb974801-5d07-4d26-9e94-7e42bdf4224b.png)
This is then followed by a very confusing statement due to the order is which they are presented:
![image](https://user-images.githubusercontent.com/55369460/175176999-7dd3ba6f-454b-429d-8f67-5d3b2e8f20c8.png)

I'm sure you will agree this could be written in a much clearer way, and help newbys get aquiainted with this notation. I would be happy to help here if needed.

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2022.6.7

**Comment by dannytsang** [comment]
As per some of the discussions in the pull requests, this is a bug and raised in the core project which deals with the Home Assistant software.

https://github.com/home-assistant/core/issues/70781
https://github.com/home-assistant/core/issues/71380

**Comment by frenck** [comment]
Yup, so I don't get this change.
The software bug needs to be fixed, not the docs.
