### ISSUE TITLE
Crap instructions for FFMPEG on HA Core Python

### ISSUE THREAD

**Issue by Davorin1994** [home-assistant/home-assistant.github.io#23182]
### Feedback

The instructions given here are absolutely useless. Please explain properly !!!!! as details are actually important no matter how far advanced one is in any given programming language. Here is the problem: (See Image in link)
![image](https://user-images.githubusercontent.com/101947921/175122547-924495bc-570a-4609-b50a-c9f14f6c6998.png)

On this page: https://www.home-assistant.io/integrations/ffmpeg    A note is given basically right at the top as in the image linked above. The text relevant to my problem is: "If you are running Home Assistant Core in a Python environment, you’ll need have the ffmpeg binary in your system path" - This is all good and well but now I ask, WHERE TF DO I GET THE BINARY TO PUT IN MY SYSTEM PATH ???? I mean honestly man. I can guarantee you that someone will respond with a very simple answer, as is usually the case. Why not simply provide the instruction ?? That's the only reason why people struggle so much with YAML related set up. because there is a failure to provide proper instructions. 

anyway I feel better after ranting a bit. can someone please advise me where to get the binary ?

### URL

https://www.home-assistant.io/integrations/ffmpeg

### Version

The FFmpeg integration was introduced in Home Assistant 0.29, and it's used by 55.5% of the active installations.

**Comment by frenck** [comment]
So, please adjust your tone in the above message first. We don't need to use things like "Crap" "TF" and all caps sentences. We don't accept that, it is against our code of conduct.

Don't forget we are also just humans on the other end; the least you can do is communicate politely as you would to any other person in real life.

Thanks.

../Frenck
