### ISSUE TITLE
After update 2022.6.7 still not working

### ISSUE THREAD

**Issue by FranSooS** [home-assistant/home-assistant.github.io#23181]
### Feedback

The problem with the growatt intergration is still after the last update for home assistant 2022.6.7.
Can you please solve this problem?

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2022.6.7

### Additional information

Still no connection to the server

**Comment by frenck** [comment]
Hi there @FranSooS 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Please make sure the issue you want to report isn't already reported (prevent duplicate reports), by searching.

Thanks! 👍 

../Frenck
