### ISSUE TITLE
Option to change the PLM tty?

### ISSUE THREAD

**Issue by friedpenguin** [home-assistant/home-assistant.github.io#23180]
### Feedback

There is no visible way to change the TTY device. Is there any such option?! If there's a hiccup or reboot my PLM ends up at ttyUSB1 instead of ttyUSB0 which requires physically being at the machine unplugged the Zigbee and rebooting. Zigbee is picked up by UUID, why not the PLM?

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.6.7

**Comment by frenck** [comment]
>  Is there any such option?! 

No there is not.

> If there's a hiccup or reboot my PLM ends up at ttyUSB1 instead of ttyUSB0 which requires physically being at the machine unplugged the Zigbee and rebooting. Zigbee is picked up by UUID, why not the PLM?

You can use the serial by ID port? When you use that, it will always work regardless of the ttyUSBx is.

**Comment by friedpenguin** [comment]
HA defaults to /dev/ttyUSB* on the PLM. Zigbee doesn't matter. I've forged a work around in case of a reboot to unbind the devices and bind in the right order. A simple drop down in the UI would be super handy like OpenHAB does but I'll settle for the broader support HA has and deal with little stuff like this.

**Comment by frenck** [comment]
> A simple drop down in the UI would be super handy like

That is possible and available in our framework, but it depends on the integration if they utilize it or not. In this case, it should not matter, it should just find the correct device path (see next part of this response...)

> HA defaults to /dev/ttyUSB* on the PLM

~~Quickly glanced at the Insteon integration code; that seems a bug to me (or better said, simply not implemented). It does indeed discover the USB device but doesn't get the serial by ID to use in place of the device path is discovered.~~

~~That is why it defaults to the resolved dev path. Could you file an issue in our issue tracker for our core & its integrations for this one? I'm happy to chime in from that end.~~

~~<https://github.com/home-assistant/core/issues>~~

Scratch that, it does request the serial by ID path.

![CleanShot 2022-06-22 at 20 39 14](https://user-images.githubusercontent.com/195327/175112089-5a74c745-38d8-48a4-ab53-283f2f2af85f.png)

So it should default to the serial by ID when discovered.

It was added here: <https://github.com/home-assistant/core/pull/70306>

**Comment by friedpenguin** [comment]
"Should". The last several releases have not seen a change to that behavior. If I have to reboot Insteon always fails until the PLM is back on ttyUSB0. If there were an option to change in a config file or UI I would totally just udev it and point to that. 
EDIT: It occurred to me that maybe in HAOS it behaves that way but I'm on the latest Core and Supervisor.

**Comment by frenck** [comment]
Maybe @teharris1 Can jump in on this one and clarify. As I'm not an Insteon user myself.

**Comment by teharris1** [comment]
@frenck is correct, this is not an option today and is a feature I will add. Also, this issue should move to core rather than this channel. The issue with the PLM is many of the Insteon devices use a very generic VID so it is impossible to uniquely identify them as a SmartLabs device. @frenck I am sure I could use your help to figure out how to get the drop down to identify the available ports. I would then be able to at this to the `Configure` flow to allow reconfiguration of the port.

BTW, if you are using the supervisor, I would recommend using the underlying path to the port rather than the `tty` alias. For example, my USB port is:

`/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C0F007A5-if01-port0`

This link never changes and you can find it in the supervisor under `hardware`. I don't know the exact path right now but it is available.

**Comment by perdw** [comment]
I'd like to upvote the issue of HA OS (that's what we run on a Raspberry Pi, right?) frequently losing contact with the Insteon USB PLM. Whenever Home Assistant restarts, there's a good chance it will lose communications with the Insteon USB PLM. Getting the system to find the PLM is like a game of Whack-A-Mole - restart HA multiple times, sometimes in conjunction with moving the PLM to another USB port. Eventually, if you're lucky, the USB port you're currently using will line up with the one HA OS has chosen. Most times it doesn't. Very frustrating and kills the main use of HA for me. I wish I knew of a way to tell HA which port to use, but I can't find such.

**Comment by frenck** [comment]
> this issue should move to core rather than this channel.

Well, if it is an integration issue, it should be (re-)raised in the Core issue tracker, as this is submitted as documentation feedback.

You can find the Core issue tracker here: <https://github.com/home-assistant/core/issues>

That said, if you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests). (That is also the place where upvoting takes place @perdw).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Closing documentation feedback, as there is nothing we can adjust to make this happen in the docs.

Thanks! 👍

../Frenck

**Comment by friedpenguin** [comment]
@perdw what other USB tty devices do you have? I created a little script to unbind the tty devices I have and bind them in the order desired so everything ends up where it belongs. udev rule didn't seem to cut it.

**Comment by perdw** [comment]
The only other USB device is a Nortek HUSBZB-1 ([https://www.nortekcontrol.com/products/2gig/husbzb-1-gocontrol-quickstick-combo/](https://www.nortekcontrol.com/products/2gig/husbzb-1-gocontrol-quickstick-combo/)).

Here's some HA information from _Settings/System/All Hardware_ menu:

Subsystem: tty
Device path: /dev/ttyUSB1
ID: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_715001C8-if00-port0
Attributes:
DEVLINKS: >-
  /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_715001C8-if00-port0
  /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.0-port0
DEVNAME: /dev/ttyUSB1
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.0/ttyUSB1/tty/ttyUSB1
ID_BUS: usb
ID_MODEL: HubZ_Smart_Home_Controller
ID_MODEL_ENC: HubZ\x20Smart\x20Home\x20Controller
ID_MODEL_ID: 8a2a

and

Subsystem: tty
Device path: /dev/ttyUSB2
ID: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_715001C8-if01-port0
Attributes:
DEVLINKS: >-
  /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_715001C8-if01-port0
  /dev/serial/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:1.4:1.1-port0
DEVNAME: /dev/ttyUSB2
DEVPATH: >-
  /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.4/1-1.4:1.1/ttyUSB2/tty/ttyUSB2
ID_BUS: usb
ID_MODEL: HubZ_Smart_Home_Controller
ID_MODEL_ENC: HubZ\x20Smart\x20Home\x20Controller
ID_MODEL_ID: 8a2a

Thanks for all your efforts!
