### ISSUE TITLE
shell_command: explain how to send values from /developer-tools/service to Shell Command: <command>

### ISSUE THREAD

**Issue by MarcDorval** [home-assistant/home-assistant.github.io#23195]
### Feedback

I'm experimenting with shell_command, and to test I use the /developer-tools/service page.
Can you please explain how to set values in the /developer-tools/service interface (both yaml mode and UI mode) and retrieve them in the shell_command ?

My current setup is:

In /config/configuration.yaml:
`shell_command: !include_dir_merge_named shell_command/`

In /config/shell_command/shell_commands.yaml:
`shell_curl: curl -Is http://www.google.com | head -n 1 > curl_test`

This is working, I get the expected content in /config/curl_test.

Now, my questions are: 

- How to replace `-Is http://www.google.com | head -n 1` by any command entered in the /developer-tools/service interface ?
- How to display the result in the '/developer-tools/service' interface?

### URL

https://www.home-assistant.io/integrations/shell_command/

### Version

2022.6.7

### Additional information

![image](https://user-images.githubusercontent.com/26892798/175403710-18a863a3-2bad-443e-b615-e8709cbfb513.png)

**Comment by MarcDorval** [comment]
If there is a page describing this, please point me to it. Once I get it to work, I could propose an edit to the shell_command page.

**Comment by frenck** [comment]
> Can you please explain how to set values in the /developer-tools/service interface (both yaml mode and UI mode) and retrieve them in the shell_command ?

You can't. `shell_command` isn't a service, it is an integration. You can configure entities and call those.

**Comment by MarcDorval** [comment]
Thanks, that's clear.
