### ISSUE TITLE
no date

### ISSUE THREAD

**Issue by WallEx90** [home-assistant/home-assistant.github.io#23197]
### Feedback

Hey, having a not in this article, that says "currently hard to come by" and not having a date provided is not really helpful. Maybe consider adding a "last edited" date or something like that.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.6.7

**Comment by frenck** [comment]
All our documentation matches the current stable release, which is monthly (release is every first Wednesday of the month).

We can't add the date without getting a major performance impact on our existing builds. Thus we won't be adding that any time soon.

The Raspberry Pis are hard to come by, there is a worldwide chip shortage.

Nevertheless, thanks for willing to provide feedback 👍 

../Frenck
