### ISSUE TITLE
How can we use the password provided in the url

### ISSUE THREAD

**Issue by dracoqcca** [home-assistant/home-assistant.github.io#23208]
### Feedback

Hi,

I'm using Fully kiosk browser on a tablet and the url to take picture is like this: http://IP_OF_THE_TABLET:2323/?cmd=getCamshot&password=PASSWORD. How can I hide the password for that I was using the configuration.yaml before and the URL was in my secret but now I do't see a way to hide it. Is there a way to either use the URL store in my secret.yaml or use a variable to use the password that i've configured in the integration?

### URL

https://www.home-assistant.io/integrations/mjpeg/

### Version

2022.6.7

### Additional information

Just updated from 2021.12.02 to the latest version so that's why I'm comming in at that moment.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
