### ISSUE TITLE
Velux integration - more info needed

### ISSUE THREAD

**Issue by SurreyMichael** [home-assistant/home-assistant.github.io#23202]
### Feedback

The Velux integration page does not say if this integration is pre-installed or needs to be installed, and if so where and how.  All that may be obvious to many, but not to me!

### URL

https://www.home-assistant.io/integrations/velux/

### Version

2022.6.7

**Comment by pyrrolizin** [comment]
It is 'preinstalled'. just add to your config.yaml:
```
velux:
  host: IP_ADDRESS
  password: VELUX_PASSWORD
```

**Comment by SurreyMichael** [comment]
Yes I already figured that out but it took me a long time.  I just thought it would be easy to mention this on the HA Velux Integration page to save the next person the same confusion - it's just a few words to add to the page.

**Comment by klaasnicolaas** [comment]
Closing it because there is a mention that you should put the part of yaml code in your `configuration.yaml` file
