### ISSUE TITLE
WiFi setup information is missing (and I know it isn't recommended, please hear me out)

### ISSUE THREAD

**Issue by shrung** [home-assistant/home-assistant.github.io#23204]
### Feedback

Hi, while installing on my Pi 3A+ (No ethernet), I found several instructions on using a "my-network" config file on the SD card or thumb drive with volume label CONFIG in order to connect to wifi from a fresh install image. They all seem to be out of date/don't work. The next info I found was to use nmcli to connect. I did this, it worked and I began setting things up, but then found my install was "unsupported".

I then found the correct method here: https://github.com/home-assistant/operating-system/blob/dev/Documentation/network.md#enabling-wifi

I ended up scrapping everything to start over. It would be good to make the correct information accessible, even if it is not a recommended setup. I saw another user propose this feedback also (https://github.com/home-assistant/home-assistant.io/issues/21236).

I understand that WiFi is not recommended, but some devices do not have ethernet, or users may want to experiment before running things from the rack. The main issue here is that the information on how to CORRECTLY connect using WiFi was much harder to find than information on how to INCORRECTLY connect using WiFi, and so I think it should be mentioned on the installation page for Raspberry Pi. Thanks for your consideration.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.6.7

**Comment by frenck** [comment]
We require setup via Ethernet; I guess we need to clarify/officially decide on devices without it not being officially supported.

**Comment by shrung** [comment]
Even if it is unsupported, I think it's good to have the information present. I can go to the "common tasks" and get instructions on how to install the development version, that isn't a common task and people can expect to find issues, couldn't how to connect to a wifi network be mentioned also? I just think the information on how to connect to a network should be accessible, and right now solutions which outright don't work are easier to find than the actual ha command to connect to a wifi network.

It's a command already built in to the home assistant command line tool, it would be better to point out than have people google it and try editing random files or using nmcli.

**Comment by frenck** [comment]
> Even if it is unsupported

That is a question we need to figure out at this point. 

>  I think it's good to have the information present.

That is the question, we don't document unsupported methods. Hence we need to figure out if we even support this or not.

**Comment by shrung** [comment]
To me it seems arbitrary to suggest that connecting to WiFi only becomes supported (but still not recommended of course) 0AFTER you first connect with Ethernet. Especially since it is possible to do so through the HA CLI, it is just hard to find that documentation, but it is already there. Just suggesting that the information be placed where people can find it.

**Comment by frenck** [comment]
Depends, the CLI is an advanced tool, that should not be needed normally, which has build in documentation.

That said, Wi-Fi can be set up via the UI.
