### ISSUE TITLE
Modbus page missing serial value for type

### ISSUE THREAD

**Issue by krona2k** [home-assistant/home-assistant.github.io#23201]
### Feedback

Should there be ‘serial’ listed in the possible values for ‘type’. That is the value used in the example config in the ‘Configuring serial connection‘ section. 

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2022.6.7

**Comment by janiversen** [comment]
Yes serial is an allowed type, suppose it dropped out by accident.
