### ISSUE TITLE
Verisure Yale door

### ISSUE THREAD

**Issue by hovbjo99** [home-assistant/home-assistant.github.io#23200]
### Feedback

Is it possible to get battery status for the verisure yale door.

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2022.6.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
