### ISSUE TITLE
info on how to use Configuration Variables found lacking

### ISSUE THREAD

**Issue by dajomu1** [home-assistant/home-assistant.github.io#23209]
### Feedback

examples found lacking. The example should contain all Configuration Variables so that noobs like me can understand how to use the variables.

### URL

https://www.home-assistant.io/dashboards/sensor/

### Version

2022.6.7

**Comment by dannytsang** [comment]
Hi @dajomu1 is there an example of a variable that is not documented but exists on the sensor card?

**Comment by dajomu1** [comment]
I cannot find how to add this in the GUI.

limits map (optional)
Limits of the graph Y-axis.

  min float (optional)
  Minimum value of the graph Y-axis.
  Default: The minimum sample among the displayed values.
 
  max float (optional)
  Maximum value of the graph Y-axis.
  Default: The maximum sample among the displayed values.

**Comment by dannytsang** [comment]
@dajomu1 I'm afraid those options are not supported in the visual editor so you will need to add it using the code editor. A similar question and examples can be seen on this [forum thread](https://community.home-assistant.io/t/default-sensor-card-limits/346431/4?u=tuxinator94).
