### ISSUE TITLE
Hello is there a way to get NetCoonsumption for S Metered ?

### ISSUE THREAD

**Issue by multinet33** [home-assistant/home-assistant.github.io#23214]
### Feedback

all in the title

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2022.6.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
