### ISSUE TITLE
Airzone integration error

### ISSUE THREAD

**Issue by EldeGraus** [home-assistant/home-assistant.github.io#23213]
### Feedback

When I try to add the Arizone it give the following message: "Unknown error occurred"
I have static IP, and the port is 3000 by default, somebody know if I should use a different port?
Thank you in advance!

### URL

https://www.home-assistant.io/integrations/airzone/

### Version

2022.6.6

**Comment by Noltari** [comment]
Hi @EldeGraus,

The issue should be opened in the core repository. This repository is for documentation only.
See https://github.com/home-assistant/core/issues/72334
