### ISSUE TITLE
Add example to mqtt camera page to show code for multiple cameras

### ISSUE THREAD

**Issue by mattbruman** [home-assistant/home-assistant.github.io#23227]
### Feedback

When adding more than one camera please show code for more than one device.
Such as...
mqtt:
  camera:
   - topic: ai/patiooutsd/motion
      name: Patio Alerts
   - topic: ai/outsidefronthd/motion
      name: Front Door Alerts

### URL

https://www.home-assistant.io/integrations/camera.mqtt/

### Version

2022.6.7

**Comment by frenck** [comment]
The camera is shown as a list already, which is according to our documentation standards.
The list can be made longer with more entries, as many as you wish.

![CleanShot 2022-06-28 at 16 51 24](https://user-images.githubusercontent.com/195327/176210531-1bd7ab81-2ecf-499c-b5a4-2660530d2550.png)

https://developers.home-assistant.io/docs/documenting/yaml-style-guide#properties-that-accept-a-mapping-or-a-list-of-mappings

Nevertheless, thanks for your suggestion.
