### ISSUE TITLE
Provide example or link to more details on the differences when calling a script from a tap_action

### ISSUE THREAD

**Issue by cbundy** [home-assistant/home-assistant.github.io#23225]
### Feedback

The script documentation [describes here](https://www.home-assistant.io/integrations/script/#passing-variables-to-scripts) that you can pass variable data into the script in one of two ways. 

However it seems if you are calling a script from a UI action (in my case `tap_action` then this will not work with the provided formats, and instead the variables need to be nested under a `service_data` node.

My suggestion is to either include a full sample of this here - or a note/info box that links to the documentation for the UI call.

### URL

https://www.home-assistant.io/integrations/script/

### Version

2022.6.7

**Comment by frenck** [comment]
Scripts are not dashboards? I'm not sure what you mean? The script documentation has nothing to do with the dashboards, there is nothing to add here?

**Comment by cbundy** [comment]
It was a `tap_action` on my dashboard calling a script, but the root cause was the change between `data` and `service_data` and my front end being out of date.
