### ISSUE TITLE
Envisalink Door/Window Sensor Errors

### ISSUE THREAD

**Issue by Hamish1066** [home-assistant/home-assistant.github.io#23229]
### Feedback

When I leave a window or door open, the Home Assistant Log will repeatedly report a fault, such as "Home Alarm Keypad changed to FAULT 23". It will also occasionally show the window/door that is open as being closed than being opened again. 

I tried updating the timeout from 10 to 15 seconds, which fixed other issues with the integration for me, but this issue persists. 

### URL

https://www.home-assistant.io/integrations/envisalink/

### Version

2022.6.7

**Comment by frenck** [comment]
Hi there @Hamish1066 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
