### ISSUE TITLE
Switchbot not integrated with home assistant any more

### ISSUE THREAD

**Issue by saadalhamidi** [home-assistant/home-assistant.github.io#23228]
### Feedback

When i Update the RP4, HA, HACS, Still the Switchbot nor integrated with HA ,, We need solution 

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2022.6.7

**Comment by frenck** [comment]
Hi there @saadalhamidi 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
