### ISSUE TITLE
Linux Capabilities on Nmap makes it impossible to run under Systemd launched HA

### ISSUE THREAD

**Issue by sevenissimo** [home-assistant/home-assistant.github.io#23233]
### Feedback

Further checks on [this issue](https://github.com/home-assistant/core/issues/73702) lead me to understand that Systemd is responsible for preventing Nmap from running within HA CGroup **when Linux capabilities assigned to the Nmap executable** as [per official documentation](https://www.home-assistant.io/integrations/nmap_tracker/#linux-capabilities).

This contrasts with [Systemd Unit](https://github.com/archlinux/svntogit-community/blob/packages/home-assistant/trunk/home-assistant.service) sandboxing policy `CapabilityBoundingSet=`

### URL

https://www.home-assistant.io/integrations/nmap_tracker/#linux-capabilities

### Version

2022.6.7

### Additional information

_Originally posted by @sevenissimo in https://github.com/home-assistant/core/issues/73702#issuecomment-1169739399_

**Comment by frenck** [comment]
> understand that Systemd is responsible

That is possible, however, configuring `systemd` is out of scope for our project. If you create a service there, the correct configuration of that service is your responsibility.

**Comment by sevenissimo** [comment]
> > understand that Systemd is responsible
> 
> That is possible, however, configuring `systemd` is out of scope for our project. If you create a service there, the correct configuration of that service is your responsibility.

I agree.
But IMHO Systemd security enforcing is right and official documentation should not suggest messing with Linux capabilities.
Mainly because they are an advanced feature beyond HA user's understanding and, as demonstrated, they can hide a problem for which the cause is not easy to clarify.

However as long as Systemd Unit (in my case) is provided by Archlinux, best I can do is to warn **not to follow official HA documentation** on ArchWiki.

**Comment by frenck** [comment]
> official documentation should not suggest messing with Linux capabilities

I'm fine with removing that part. It seems to be an inheritance from the old days.
