### ISSUE TITLE
"Failed to Connect"

### ISSUE THREAD

**Issue by masseym** [home-assistant/home-assistant.github.io#23249]
### Feedback

I followed the instructions.  Once installed, I tried to log in and immediately received a "Failed To Connect" error.

### URL

https://www.home-assistant.io/integrations/smart_meter_texas/

### Version

2022.6.7

**Comment by frenck** [comment]
Hi there @masseym 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Please make sure your issue doesn't exist yet (by searching), to prevent duplicate issues from being reported.

Thanks! 👍 

../Frenck

**Comment by masseym** [comment]
Sorry... new here...

**Comment by frenck** [comment]
Don't worry! I rather point you in the right direction 👍 

Oh! And welcome ❤️ 

../Frenck
