### ISSUE TITLE
historical data

### ISSUE THREAD

**Issue by fweijers** [home-assistant/home-assistant.github.io#23248]
### Feedback

Thank you for building this integration with Growatt! I use it all the time.

My question is if it would be possible to retrieve historical data from the Growatt servers? Currently, the integration only retrieves the live data, not the data from yesterday or previous month. 

Thank you in advance!

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2022.6.7

### Additional information

The reason for this question is that I lost my data because the integration failed at some point and I had to updrade HA.
Upgrading failed because of my own fault, and I had to rebuild my setup from scratch (raspberry pi 4 - ubuntu - docker - HA) and lost the previously logged statistical data of the Growatt integration.

I am probably not the only one in this situation :)

I think that being this far: able to retrieve live data, i should be possible to extent the functionality to retrieve older data too.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
