### ISSUE TITLE
Clarify refresh rate of still image

### ISSUE THREAD

**Issue by JotaGreen** [home-assistant/home-assistant.github.io#23258]
### Feedback

I suggest providing information that when using still images in generic camera with a constant URL, it is refreshed every 10 seconds and it is not currently possible to change this interval.

### URL

https://www.home-assistant.io/integrations/generic/

### Version

2022.6.7

**Comment by davet2001** [comment]
@JotaGreen Are you sure?  What happens when you change the frame rate setting?

**Comment by JotaGreen** [comment]
> @JotaGreen Are you sure?  What happens when you change the frame rate setting?

I couldn't test yet. I am using this integration to present highway cameras and weather graphics that don't update often. I intended to set to update every 10 min or less.

I learned from [this post](https://www.reddit.com/r/homeassistant/comments/sxpu2m/change_generic_camera_10_second_still_image/?utm_source=share&utm_medium=mweb3x) that the still images always updates every 10 sec.

The documentation says that the frame rate applies to the stream. If it also apply to the still image, this could be clarified too. (Maybe also clarifying if it would not accept something like 0.001 Hz).

If needed, I can try to test and confirm.

Thanks

**Comment by davet2001** [comment]
I have been using this feed for testing:
http://hencam2.viewnetcam.com:5003/snapshotJPEG?Resolution=640x480&Quality=Clarity
If you manually refresh it in a browser it has a new image at least every second.  Also there's a handy timestamp in the corner.

If I add it to homeassistant with default settings the image updates about every 3 seconds.

If I go to configure and change the frame rate to 0.1Hz, i'd expect every 10 seconds, in reality I get every 12 ish seconds.

It would be helpful if you could test some different options a bit more to see what works and what doesn't.  The docs probably need updating.
