### ISSUE TITLE
iZone Int - Example code is not clear and vague

### ISSUE THREAD

**Issue by Muxxx** [home-assistant/home-assistant.github.io#23254]
### Feedback

This page makes too many assumptions about the skill level of the user attempting to setup this integration’s climate temperature templates. I for one have simply copied the example code into my configuration.yml file and changed the controller ID as stated and it doesn’t return any data. Can the example include how to pull data from more than one zone, using examples and calling out what variables need to be changed if any? Say someone has 7 zones in izone, what would the config file look like for 2 so they can build out the rest? How is the data structured that is returned from this integration? Some more explanation of that would also help - how is each zone and it’s information represented so it’s easily referenced in a sensor?  

### URL

https://www.home-assistant.io/integrations/izone/

### Version

2022.6.7

**Comment by Swamp-Ig** [comment]
The control zone stuff is entirely optional, it's just there for information and only if you want to know which zone was the control zone.

**Comment by Swamp-Ig** [comment]
I'm not entirely sure what you mean here. Each zone has its own `climate` entity. Is that what you're meaning?

**Comment by Muxxx** [comment]
Yes, I would like to query the value of each climate zone’s actual temperature, as individual sensors. Is this automatically done by the integration or do I need to create these sensors manually to get this data?

**Comment by Swamp-Ig** [comment]
It depends on what time of zone they are. Are they automatic zones? (as in, have a thermostat on the wall in each zone?)

If there's no thermostat then there's no data and you can just open and close the zone (open/close zone)

**Comment by Muxxx** [comment]
Yes, they are automatic zones, with thermostats on the wall in each zone. This was the reason for my open issue with the doco - it just wasn't clear how I could interrogate the climate entity information to expose those actual temp values.

**Comment by Swamp-Ig** [comment]
It's a climate entity, there's an attribute on the entity.

![image](https://user-images.githubusercontent.com/6317645/177271638-6dcfae90-579e-4e3a-bbf9-7219d78ce347.png)

If you were trying to get it from a template it would be like:

```
{{ state_attr('climate.bed_1', 'current_temperature') }}
```

This is the same for all climate entitities, so documentation here isn't appropriate.
