### ISSUE TITLE
Firmware update to T-2000 causing issue

### ISSUE THREAD

**Issue by davel4wa** [home-assistant/home-assistant.github.io#23268]
### Feedback

There has been so much chatter about the issue caused by the recent firmware update ( Jun 28 ) to T-2000 thermostats, that I am sure you are aware if the problem with miscalculation of the 'current temperature' attribute. Since the issue is caused, apparently, by a 'patch' to integration code to accommodate the T-2000 API reporting temperature in ⁰C whether or not the 'tempunits' attribute was set the ⁰C or ⁰F. Current firmware converts the 'thermostat, temp' to ⁰F when the 'tempunits' attribute is set to ⁰F (0). This is causing a double conversion in the integration, where 67⁰F is converted and displayed as 153⁰F. 
My only question is, when can we expect the offending code be removed/altered to produce the correct 'thermostat, temp' value.

### URL

https://www.home-assistant.io/integrations/venstar/

### Version

2022.6.7

### Additional information

![Screenshot_20220704-122224_Home Assistant](https://user-images.githubusercontent.com/89482464/177208682-f4de6999-110f-4480-b5bb-31a738d8d8df.jpg)

**Comment by frenck** [comment]
Hi there @davel4wa 👋 

I'm not sure if you have a question or are trying to report a bug with an Home Assistant integration. Either case, you have submitted documentation feedback instead.

If you are in need of support or have questions, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

If you want to report a bug, please do so in the core issue tracker here:

<https://github.com/home-assistant/core/issues>

You are more likely to get the answer you are looking (or fixes) for in those places.

Thanks! 👍

../Frenck

**Comment by davel4wa** [comment]
It appears the code changes have been made to accommodate the firmware v5.28 changes. I assume this will be available in an integration update in the near future. It feels very warm in here at 150⁰F. 😊
