### ISSUE TITLE
RESTFul 

### ISSUE THREAD

**Issue by conwaylw** [home-assistant/home-assistant.github.io#23272]
### Feedback

I was tying to figure out how to make a single RESTFul call and extract results from an array returned from that call.  There has been some confusion in the forums, as there have been some YAML changes.  I think this is partially because the YAML examples on the RESTful Sensor/Binary Sensor pages at [https://www.home-assistant.io/integrations/sensor.rest](url) have not been updated to the new YAML format defined on the RESTFul page at [https://www.home-assistant.io/integrations/rest/](url).  If the sensor and binary sensor docs could be updated with new examples, or at least have a link back to the new integration, then this question would answer itself, leading to less confusion and frustration.

### URL

https://www.home-assistant.io/integrations/sensor.rest/

### Version

2022.6.7

### Additional information

Thanks to Tom_I for his detailed explanations.

**Comment by klaasnicolaas** [comment]
You can also make those adjustments yourself if you want 😉

**Comment by hutchwilco** [comment]
I have to second the general gist of this comment and say that the instructions on this page and the examples provided essentially contradict each other (please excuse the possibility that I misunderstand a concept here, but generally I am fairly competent amateur sys admin):
1. The top of this page says:

> Tip: If you want to create multiple sensors using the same endpoint, use the [RESTful](https://www.home-assistant.io/integrations/rest) configuration instructions.

That linked page (RESTful) contains no examples of that Tip  (how to assign multiple attributes in a JSON reply to separate sensors) - an issue for that page admittedly. However _this_ page goes on to apparently give specific examples of doing this, namely:

> This configuration shows how to extract multiple values from a dictionary with json_attributes and template. This avoids flooding the REST service by only requesting the result once, then creating multiple attributes from that single result using templates. By default, the sensor state would be set to the full JSON — here, that would exceed the 255-character maximum allowed length for the state, so we override that default by using value_template to set a static value of OK.

My suggestion is to move those instructions over to the RESTful page, as that is where users are instructed to go when you want to use multiple attributes from one RESTful call.

I understand that I can do this change myself - I'm refraining from this and instead am writing about it here as I am not confident that I have all the concepts correct in my head to go ahead and change things without consulting.

2. My other point, from frustrations of setting up a few of these sensors, is the Authentication element could do with a step through tutorial (or several examples of different authentication types) showing how to translate a curl-based command to the YAML equivalent). I think a "block level" descriptor of the main YAML sections and their role in the different elements of GET, extract via template, define sensor etc would be helpful for newcomers to understand what is happening in the YAML. Again, I'd write this up but I think my knowledge still has holes.
