### ISSUE TITLE
Add Support For Hanafi sect for ASR prayer time

### ISSUE THREAD

**Issue by RehmanAdeel** [home-assistant/home-assistant.github.io#23275]
### Feedback

Add Support For Hanafi sect for ASR prayer time.
Like https://aladhan.com/prayer-times-api
or use for calculation .
Currently I am using it like http://api.aladhan.com/v1/timings?latitude=xx.xxxxx8&longitude=-xx.xxxxxx&method=2&school=1&timezonestring=America/New_York

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2022.6.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
