### ISSUE TITLE
Ezviz plugin cant login with OTP enabled

### ISSUE THREAD

**Issue by Zapnologica** [home-assistant/home-assistant.github.io#23277]
### Feedback

I am unable to log in to the Ezviz plugin.

I am 100% sure the login details are correct.  However, I noticed that after it failed I got an email from some strange hik connect email address with a one time pin code in it.

I am assuming that the plugin does not cater for this?

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2022.6.7

### Additional information

![image](https://user-images.githubusercontent.com/3656913/177399013-aa76e39c-9777-4883-83cd-56436793716e.png)

_No response_

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by Zapnologica** [comment]
I see, ok well in that case I believe the documentation should say that it will not work with accounts that have 2 factor authentication.  Because it took me ages to realise what my issue was

**Comment by klaasnicolaas** [comment]
First check whether this is not an issue in the integration, before we put these kinds of warnings in the docs.
