### ISSUE TITLE
Incorrect API provider address

### ISSUE THREAD

**Issue by Santanachia** [home-assistant/home-assistant.github.io#23284]
### Feedback

> To generate an Airly API key, go to [Airly for developers](https://developer.airly.eu/register) page.

this address does not lead to a page where you can get an API key

### URL

https://www.home-assistant.io/integrations/airly/

### Version

2022.6.7

**Comment by bieniu** [comment]
I checked and https://developer.airly.eu/register works as usual

![image](https://user-images.githubusercontent.com/478555/177543247-b3e20c79-fb5f-4c53-a58d-a6ece4d8ae59.png)

**Comment by Santanachia** [comment]
https://developer.airly.eu/register redirects me to https://developer.airly.org/en
![image](https://user-images.githubusercontent.com/4628507/177548190-0a16dd0a-bbf1-4ae4-8b0d-f717a1c19d73.png)

**Comment by Santanachia** [comment]
I have to be logged out to get to the registration page
