### ISSUE TITLE
TRACCAR ADDON SERVER

### ISSUE THREAD

**Issue by vgisbert** [home-assistant/home-assistant.github.io#23283]
### Feedback

For the Traccar sever addon to work, you must include the configuration:

device_tracker:
  - platform: traccar
    ...
    host: 127.0.0.1
    port: 18682 

### URL

https://www.home-assistant.io/integrations/traccar/

### Version

2022.6.7

**Comment by ludeeus** [comment]
That is exactly what the documentation already says?

**Comment by frenck** [comment]
Yup, closing this as the documentation show the configuration and all its options.

Nevertheless, thank you for being willing to provide feedback 👍 

../Frenck

**Comment by vgisbert** [comment]
> Yup, closing this as the documentation show the configuration and all its options.
> 
> Nevertheless, thank you for being willing to provide feedback
Not quite.
Following the documentation, nowhere does it indicate that TRACCAR communicates with HA through port 18682. In fact, the documentation indicates that the default port is 8082, and with that it does not work.
I have also found some documentation on the net that to address the local server on the host erroneously indicated http://172.0.0.1
With that nomeglatura you can not access.
That is why it would be good to indicate it as an example in TRACCAR's own official documentation for Home Assistant.
For me it would have been very clarifying and I would not have wasted time doing tests, searching the internet and asking questions on Telegram channels.
Thank you anyway.

**Comment by frenck** [comment]
> Following the documentation, nowhere does it indicate that TRACCAR communicates with HA through port 18682.

That is depending on your Traccar setup; not Home Assistant.

**Comment by vgisbert** [comment]
> > Following the documentation, nowhere does it indicate that TRACCAR communicates with HA through port 18682.
> 
> That is depending on your Traccar setup; not Home Assistant.

Okay. It's clear. Thanks.
