### ISSUE TITLE
Speedtest timestamp

### ISSUE THREAD

**Issue by david-b13** [home-assistant/home-assistant.github.io#23282]
### Feedback

Am relatively to new to HA.  I have recently added this integration to my setup and dashboard, and was looking for a way to simply show the time on the UI that the most recent data displayed was measured ?   So a timestamp of the last run.  Couldn't see anything in the documentation or online, but am sure the data is captured.
Thanks.
David.

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2022.6.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
