### ISSUE TITLE
Users without permissions (only view a panel)

### ISSUE THREAD

**Issue by jmmartinviana** [home-assistant/home-assistant.github.io#23289]
### Feedback

Is it possible to create a user that does not have access to the sidebar? that is, you only have access to the summary panel, not to your own user data.
When creating a user, he has access to the energy panel, history, etc.

### URL

https://www.home-assistant.io/docs/authentication/

### Version

2022.6.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
