### ISSUE TITLE
Issues with "Link Google Account" section

### ISSUE THREAD

**Issue by ocasioj** [home-assistant/home-assistant.github.io#23299]
### Feedback

We need more detailed steps. I get to that "Link Google Account" and I have no idea what to do or where to click. I am fairly new to home assistant and this step is driving me mad because I have no idea where I am supposed to be clicking or what url I need to be in order to link the account. 

I am using the docker image of HA on  a Synology NAS and cannot integrate the Nest. 

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.6.7

### Additional information

Please let me know if you need anything else

**Comment by allenporter** [comment]
I'm not sure what you're looking at or what is not obvious about what to do. Can you give more detail or a screenshot? Thanks.

**Comment by allenporter** [comment]
I see you're running 2022.6.7 however the instructions at https://www.home-assistant.io/integrations/nest/ are always for the latest version of home assistant, so they won't match.  Perhaps if you upgrade the steps would make sense?

2022.7 was released today so i can understand why this would be confusing.

**Comment by ocasioj** [comment]
Thanks!! I really appreciate your patience. I'll see if I can grab the latest docker image! My issues is I get to the part that says "link google account" then it says "1. A new tab opens"..a tab opens from where? would it be from home assistant? Or would it be from google? Is there a specific url I need to enter to generate the token?

**Comment by ocasioj** [comment]
I did the "create a device access project" part if these instructions apply to 2022.7 then I'll wait to try them on there...thanks again for ur quick look at this! Appreciate it!

**Comment by allenporter** [comment]
I think the step you are missing is "Adding Nest to your Home Assistant instance can be done via the user interface, by using this My Button..." which only works in 2022.7

**Comment by ocasioj** [comment]
Thanks again! I'll try running the new version on a raspberry pi tomm! Thanks! U can close this.
