### ISSUE TITLE
SIa integration is not working after upgrade to 2022.7

### ISSUE THREAD

**Issue by aperezva** [home-assistant/home-assistant.github.io#23298]
### Feedback

Please,

could you review why SIa integration fails after upgrade to  2022.7?

To me is the most importa integration in HA.

Thanks

### URL

https://www.home-assistant.io/integrations/sia/

### Version

2022.7.0

### Additional information

Error communication with supervisor center in Ajax  alarms. I test it twice upgrating and downgrating and  when I change the versión to 2022.7 fails. Coud be because a new versión of phyton in the version?

BR

**Comment by aperezva** [comment]
I m a user

**Comment by aperezva** [comment]
this is the error in HA:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 07:05:29 (1 occurrences)
Last logged: 07:05:29

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for sia using this method at custom_components/sia/hub.py, line 95: device_registry = await dr.async_get_registry(self._hass)

**Comment by frenck** [comment]
>  Please report issue to the custom component author for sia using this method at custom_components/sia/hub.py, line 95: device_registry = await dr.async_get_registry(self._hass)

☝️ The error message shows you are using a custom integration for sia; and is thus not maintained by the Home Assistant project.

Please report the issue with the author/project of the custom integration you are using.

Thanks 👍 

../Frenck
