### ISSUE TITLE
Update HAOS version download URL

### ISSUE THREAD

**Issue by vazquezjm** [home-assistant/home-assistant.github.io#23308]
### Feedback

On the doc, the link to HAOS points to 8.2 while the latest is 8.3

![image](https://user-images.githubusercontent.com/5269397/177836386-aa32183b-d299-49bc-b5d4-c175c7817b23.png)

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2022.7.0

**Comment by frenck** [comment]
That is incorrect, 8.3 isn't released as stable yet.

![CleanShot 2022-07-07 at 21 44 29](https://user-images.githubusercontent.com/195327/177859080-725599ef-2e91-4941-a269-81bf04eb82f6.png)

The current documentation is therefore correct at this moment in time.
