### ISSUE TITLE
Venstar T-2000 firmware update to 5.28

### ISSUE THREAD

**Issue by davel4wa** [home-assistant/home-assistant.github.io#23311]
### Feedback

It appears the fix has been made to prevent the double conversion of thermostat temperature. The case has been closed and the new code appears in the integration files.
When will the new version be available for download? 

### URL

https://www.home-assistant.io/integrations/venstar/

### Version

2022.7.0

**Comment by klaasnicolaas** [comment]
Hi there @davel4wa 👋

It seems like you want to ask a question about an Home Assistant integration, however, you have submitted documentation feedback instead. I think a better place to ask this is in the discord server.

Thanks! 👍

./Klaas
