### ISSUE TITLE
IMAP Integration doesn't work since 2022.7.0

### ISSUE THREAD

**Issue by scxs535** [home-assistant/home-assistant.github.io#23315]
### Feedback

IMAP Integration doesn't work since 2022.7.0 even though it worked in 2022.6.5 and before.

Logger:
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:269
Integration: sensor (documentation, issues)
First occurred: 00:17:45 (1 occurrences)
Last logged: 00:17:45

Platform imap not ready yet: None; Retrying in background in 30 seconds

configuration.yaml
sensor:
  - platform: imap
    server: IMAP_SERVER.com
    username: USERNAME
    password: PASSWORD

### URL

https://www.home-assistant.io/integrations/imap/

### Version

2022.7.0

**Comment by frenck** [comment]
Hi there @scxs535 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Be sure to use the search function to see if your issue isn't reported already (to prevent duplicates).

Thanks! 👍 

../Frenck
