### ISSUE TITLE
get_lutron_cert.py not found

### ISSUE THREAD

**Issue by dudley810** [home-assistant/home-assistant.github.io#23318]
### Feedback

file not found This can be accomplished by downloading and executing [get_lutron_cert.py]

### URL

https://www.home-assistant.io/integrations/lutron_caseta/

### Version

2022.7.0

**Comment by frenck** [comment]
Thanks, @dudley810 👍 

That script indeed doesn't exist anymore. I've opened up a PR to replace it in our documentation.

Thanks for reporting that ❤️ 

../Frenck
