### ISSUE TITLE
energy dashboard not aggregating the grid corretly when looking at history

### ISSUE THREAD

**Issue by ripcam21** [home-assistant/home-assistant.github.io#23317]
### Feedback

have started using the energy dashboard after integrating my energy monitor.  Issue experienced is when reviewing history, the grid is showing an abnormally excessive grid consumption aggregate.  This then renders the dashboard insights useless.  Attached is the issue:
![dashboard result](https://user-images.githubusercontent.com/106219466/177897480-a9daf777-e11c-4401-ab40-fd32f26c5f3b.JPG)
![sensor information](https://user-images.githubusercontent.com/106219466/177897754-2db64076-8a22-488b-b9f9-601e5b5f754c.JPG)
Any support would be appreciated.

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2022.7.0

**Comment by frenck** [comment]
Hi there @ripcam21 👋 

It seems like you want to report an issue with the Home Assistant frontend, but you have submitted documentation feedback instead. Please report issues with the frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks! 👍 

../Frenck
