### ISSUE TITLE
List of tariffs for utility meter helper

### ISSUE THREAD

**Issue by scriptengine** [home-assistant/home-assistant.github.io#23320]
### Feedback

The documentation for the utility meter says:
"A list of supported tariffs, leave empty if only a single tariff is needed."
What format should this list be in? 
offpeak, peak
offpeak; peak
[offpeack,peak]

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2022.7.0

**Comment by frenck** [comment]
The format should be a YAML list... as this is a YAML configuration file.

```
tariffs:
  - high
  - low
```
