### ISSUE TITLE
\\Climate

### ISSUE THREAD

**Issue by BednarJan** [home-assistant/home-assistant.github.io#23324]
### Feedback

Hi there.
I programmed an automation, will control the filtering-pump in my hot tube -  see below.
What I want to do is, the hot tube filtering should be daily, periodically,  every 4 hours turned on  (it  ensures another  automation) for one hour.

The  automation below should turn off the filtering 60 minutes after it was turned on, but only, when the thermostat (climate.sonoff_1001200a36) is in the state idle.  

After running the script it looks like the condition  will be ignored.  What I am doing wrong?

alias: HotTube_Filtering_OFF
description: Turning off the filtering  60 min. after last start
trigger:
  - platform: state
    entity_id:
      - switch.sonoff_1001200a36
    to: 'on'
    for:
      hours: 1
      minutes: 0
      seconds: 0
condition:
  - condition: state
    entity_id: climate.sonoff_1001200a36
    attribute: hvac_action
    state: idle
action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.sonoff_1001200a36
mode: single

### URL

https://www.home-assistant.io/integrations/climate/

### Version

2022.7.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
