### ISSUE TITLE
Which configuration file

### ISSUE THREAD

**Issue by scriptengine** [home-assistant/home-assistant.github.io#23321]
### Feedback

The Utility meter docs has some nice Yaml for
utility_meter:
&
template:
However it does not say which configuration file these code samples could/ should be added to and if there is any particular order they need to be added in or any sections they should be before or after.

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2022.7.0

**Comment by frenck** [comment]
Hi there @scriptengine 👋 

It is actually listed on the page you linked:


![CleanShot 2022-07-08 at 14 03 09](https://user-images.githubusercontent.com/195327/177988544-65b43541-e567-4de8-ac4c-39a599dbd410.png)


Links to: https://www.home-assistant.io/docs/configuration/

The provided examples can just be copied and pasted in to the `configuration.yaml` file.
