### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by RichardUUU** [home-assistant/home-assistant.github.io#23325]
### Feedback

getcookies.txt is a dead link, I believe the replacement should be [open_cookies.txt](https://chrome.google.com/webstore/search/open%20cookies%20txt?hl=en-US)

### URL

https://www.home-assistant.io/integrations/google_maps/

### Version

2022.7.1

**Comment by olli-dot-dev** [comment]
The link directs to the meant chrome extension and is therefore working and imho correct:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/8542809/180049932-48a7b022-85a5-4ee3-ae18-cfbed87a95b7.png">

**Comment by RichardUUU** [comment]
Looks like it was revived. At the time I wrote that, it was dead.
