### ISSUE TITLE
battery status

### ISSUE THREAD

**Issue by hovbjo99** [home-assistant/home-assistant.github.io#23333]
### Feedback

Is it possible to get battery status from yaledoors

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2022.7.2

**Comment by frenck** [comment]
I don't know if that information is available. You could take a look at the diagnostic data, as it contains all data returned by Verisure available to us.

To get to that data, go to the device page of your lock, click the kebab menu (the tree dots) and download the diagnostic information, it is a text file that you can view. Is the battery in there?

**Comment by hovbjo99** [comment]
Hi!
To bad:

"locks": {
      "2AXG ZQAG": {
        "deviceLabel": "2AXG ZQAG",
        "area": "**REDACTED**",
        "method": "UNKNOWN",
        "lockedState": "LOCKED",
        "currentLockState": "LOCKED",
        "pendingLockState": "NONE",
        "eventTime": "2022-07-08T15:54:04.000Z",
        "secureModeActive": false,
        "motorJam": false,
        "paired": true
      },

Who can make an influence to Verisure about this request?

Regards BT Hovland

**Comment by xeor** [comment]
I'm a user of verisure and want the same thing. I where going to call them soon and will mention this as well. But as a normal user, I doubt that will help much
