### ISSUE TITLE
Include information of expected entities in cards

### ISSUE THREAD

**Issue by BigFam194** [home-assistant/home-assistant.github.io#23337]
### Feedback

It would help a lot to understand what entities and what those entities are expected to expose for the energy dashboard to work as expected. Most energy related integrations provide many entities e.g. for solar panels there are a different entities for total produced energy since start and produced energy last hour. It would be good to understand what to pick. 

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2022.7.2

**Comment by frenck** [comment]
> Most energy related integrations provide many entities e.g. for solar panels there are a different entities for total produced energy since start and produced energy last hour. It would be good to understand what to pick.

If you can pick them, they work; doesn't matter which one you'd pick the result is the same.
