### ISSUE TITLE
this guide is not working, Unable to link NEST Google since 2022.7

### ISSUE THREAD

**Issue by Vendo232** [home-assistant/home-assistant.github.io#23330]
### Feedback

this guide is not working, Unable to link NEST Google since 2022.7

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.7.1

**Comment by allenporter** [comment]
Hi, that's not enough information can you elaborate?

If it's "can't link" see the troubleshooting section on can't link and the 4 things to check. Read it very carefully. My guess is the application credentials are out of sync and need to be deleted from the "..." overflow menu.

**Comment by Vendo232** [comment]
tell me more about the "..." overflow menu, where can I find it?

**Comment by allenporter** [comment]
Read the can't link instructions which links to application credentials

**Comment by Vendo232** [comment]
will do, would you be able to point me to the instructions?

**Comment by Vendo232** [comment]
where can I find the " can't link instructions "

**Comment by Vendo232** [comment]
![image](https://user-images.githubusercontent.com/44098230/178088280-622382fb-c7af-4d3c-a174-10d5033f0ea9.png)

**Comment by Vendo232** [comment]
I`m missing something :-(

**Comment by Vendo232** [comment]
this is what I was missing the "https://www.home-assistant.io/integrations/application_credentials/" 

had to remove the old credentials
