### ISSUE TITLE
Dublin Bus integration is dead?

### ISSUE THREAD

**Issue by evnvc** [home-assistant/home-assistant.github.io#23349]
### Feedback

Hi,
followed the outlined steps for the Dublin Bus integration but sensors aren’t showing up? Some of the links in there are dead as well.

Update: saw this: https://data.smartdublin.ie/dataset/real-time-passenger-information-rtpi-for-dublin-bus-bus-eireann-luas-and-irish-rail

### URL

https://www.home-assistant.io/integrations/dublin_bus_transport/

### Version

2022.7.3

**Comment by frenck** [comment]
Hi there @evnvc 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
