### ISSUE TITLE
Bug in minecraft_server integration MOTD.

### ISSUE THREAD

**Issue by wolfswolke** [home-assistant/home-assistant.github.io#23343]
### Feedback

Hello!
I just installed the minecraft_server integration.
After adding my Servers I got an error that the MOTD doesn't have the Attribute .get("text")
Its a 1.7.10 Server so maby the MOTD worked different back then? 
For the 1.12.2 and above servers there was no problem.
My "fix" is going to line 183 and adding this:
```
try:                                                                               
   self.motd = (status_response.description).get("text")                          
except(AttributeError, TypeError):                                                 
   self.motd = (status_response.description) 
```
Now everything works and maby this helps someone ^^

### URL

https://www.home-assistant.io/integrations/minecraft_server/

### Version

2022.7.2

### Additional information

![image](https://user-images.githubusercontent.com/34097612/178147579-7aca0ffc-bd71-4a26-8ef1-e92862c7d298.png)

**Comment by frenck** [comment]
Hi there @wolfswolke 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
