### ISSUE TITLE
Yurzeit

### ISSUE THREAD

**Issue by kj4qyf** [home-assistant/home-assistant.github.io#23344]
### Feedback

How can I set an Automation whereby a light goes ON for a Yurzeit. In other words, an Automation using a specific Hebrew calendar date (assuming that such date would go from sunset to sunset) ?

### URL

https://www.home-assistant.io/integrations/jewish_calendar/

### Version

2022.7.2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by tsvi** [comment]
Hi @kj4qyf, unfortunately this is currently unsupported. I really hope to introduce this at some point.

**Comment by kj4qyf** [comment]
Tsvi, that would be great if you can find the time. The Melacha entity is spectacular !  Thanks for this amazing integration.
