### ISSUE TITLE
Text to speech on Sonos with examples including Node Red.

### ISSUE THREAD

**Issue by AgingTechNerd** [home-assistant/home-assistant.github.io#23350]
### Feedback

Would be nice to cover using text to speech on Sonos with some examples. Node Red examples would help as well. 

ie. How do I get it to play "Garage Door Open" when my Shelly 1 sends a garage door "ON" string. 

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2022.7.3

**Comment by frenck** [comment]
> Would be nice to cover using text to speech on Sonos with some examples. 

For instructions on how to use TTS, please check out the documentation of the integration that provides the TTS in your case (e.g., Google Translate, Amazon Polly, ...).

These instructions are not part of, or specific to, Sonos.

> Node Red examples would help as well.

Node-RED is a third-party software application, not supported by the Home Assistant project and thus not part of our documentation for that reason.

> ie. How do I get it to play "Garage Door Open" when my Shelly 1 sends a garage door "ON" string.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
