### ISSUE TITLE
Could do with more documentation when using multiple network interfaces

### ISSUE THREAD

**Issue by athornblom** [home-assistant/home-assistant.github.io#23360]
### Feedback

I feel like there would be nice with more documentation how to use multiple network interfaces, say you have a vlan for devices that do not have access to internet etc. It would be nice to know what home assistant uses the different interfaces for, cause currently I feel like it's a black hole.

<img width="596" alt="image" src="https://user-images.githubusercontent.com/22910146/178321424-52aaaa66-97d3-467f-b374-36d5eba078c7.png">

Disclaimer, I have tried to find information about this. But could not find anny.

### URL

https://www.home-assistant.io/integrations/network/

### Version

2022.7.3

**Comment by frenck** [comment]
What would you like to see documented about that? Could you clarify that?

**Comment by athornblom** [comment]
Yes absolutely, I will try to be as clear as possible just ask if you have any more questions.

So, say you have a segregated network at home which is divided into for the simplicity say two vlans. LAN and IOT. Since manny  diy smart devices are very cheap and bought off untrusted vendors such as (aliexpress etc), it can be nice to put them on an isolated vlan, which say does not have access to the internet. Or say if you have cameras this becomes even more important since you don't want the camera itself being able to aces the internet so you put them on a separate vlan.

For home assistant to be able to discover some devices or vice versa, home assistant requires to be on the same subnet (I'm talking about devices that does not use mdns). After some trial and error I managed to add a vlan network interface to my raspberry (running homeassistant os) A result of doing so I saw that I could in the UI select both network interfaces and now my home assistant works on both interfaces. However I'm running unifi controller on my home assistant which for example I don't want to expose on the IOT network since thats considered as an insecure network with not trusted devices.

I would like to have more documentation how home assistant uses multiple interfaces and if you can lock down home assistant so for example one of the network interfaces is only used for talking with sensors. (almost like home assistant is a firewall)
The only information I can see now about this is the text "Configure which network adapters integrations will use. Currently this setting only affects multicast traffic. A restart is required for these settings to apply." Which I don't think provides enough information about what happens if you enable multiple interfaces.

Sorry for the wall of text, but thought an example would make you understand what I'm trying to come at. Hope this clarifies it and keep up the good work with Home Assistant!

**Comment by frenck** [comment]
> I would like to have more documentation how home assistant uses multiple interfaces and if you can lock down home assistant so for example one of the network interfaces is only used for talking with sensors.

Home Assistant doesn't actually. Its up to you to bridge the network correctly and set up routing for specific protocols/broadcasts for your devices. If you choose to run such network setups, we assume you hold the knowledge and are capable of setting it (suiting your devices).

Configuring networking and how that works with devices is out of scope for Home Assistant (at such a level, that we don't do anything with it).

It is not more/less than that.

**Comment by athornblom** [comment]
To clarify, you mean that Home assistant only uses one interface? Even tho multiple are configured? If i'm not mistaken my setup of home assistant does, cause my firewall says otherwise when looking at traffic by IP

Some info about my instance. 
![image](https://user-images.githubusercontent.com/22910146/178493696-a2a11685-c842-488e-ad7a-ea8579df1d2f.png)

And these are the current traffic from each IP, both screenshots were taken directly after each other. 

![Screenshot 2022-07-12 at 14 45 35](https://user-images.githubusercontent.com/22910146/178493206-9dfbbe23-841c-494a-8dd3-fb610349489c.png)
![Screenshot 2022-07-12 at 14 45 09](https://user-images.githubusercontent.com/22910146/178493277-787d5330-6a0c-4ca0-9280-5b5d68282b07.png)

**Comment by frenck** [comment]
Oh sure you can configure multiple interfaces on your system and since HA listens on 0.0.0.0, it will listen on all interfaces. There is nothing "special" done.

**Comment by athornblom** [comment]
Okey, thanks for the explanation, this stuff you explained to me is exactly what I would like to see in the documentation.

**Comment by frenck** [comment]
?

It is: <https://www.home-assistant.io/integrations/http#server_host>

**Comment by athornblom** [comment]
Maybe I'm out on deep water, I'm not quite sure but don't devices talk to/with home assistant through the backend? So when reading:

 _The http integration serves all files and data required for the Home Assistant frontend._ 

I did not give a thought that this integration applies to how devices talk with home assistant, thus my understanding was that I can specify IP's in the http integration and home assistant will only serve the frontend (UI) to these IP's and by default to all IP's. And these settings won't affect the backend in any way. But from your answers my conclusion is that the backend of home assistant will use all configured network interfaces and use the corresponding network interface when talking/listening to devices on a specific subnet. Do I understand this correctly? If so I think this could be made more clear in the documentation, maybe it is but I haven't found it at least. But that's just my cup of tea!
