### ISSUE TITLE
Re-configure integration with updated credentials?

### ISSUE THREAD

**Issue by BigFam194** [home-assistant/home-assistant.github.io#23372]
### Feedback

After having changed the credentials for the account used to access the UniFi Network the HA integration will fail. There's no apparent way of reconfigure the integration using the updated credentials but rather you have to delete and add the integration again. Unless there's a way to upgrade the credentials that is not documented?

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2022.7.3

**Comment by frenck** [comment]
The integration will / should ask to re-authenticate on the integrations page.

If not, that would be a bug and should be reported on the Home Assistant core issue tracker.
The issue tracker can be found here:

<https://github.com/home-assistant/core/issues>

../Frenck
