### ISSUE TITLE
How to remove old sensor?

### ISSUE THREAD

**Issue by dmmedia** [home-assistant/home-assistant.github.io#23386]
### Feedback

Old sensor is stuck in the read-only mode and is displayed in lovelace dashboard. Cannot find any ways to remove it from devices or objects or integrations. Instuctions to remove old sensors could be very useful.

### URL

https://www.home-assistant.io/integrations/mitemp_bt/

### Version

2022.7.4

**Comment by frenck** [comment]
It's the installation/configuration instructions of the page you listed, in reverse.

Remove it from your YAML configuration (as you added it there to add it), and restart Home Assistant.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by dmmedia** [comment]
Hi @frenck !
I did exactly that. Removed from YAML configuration and then restarted Home Assistant.
The sensor data disappeared and is now not available, but objects are still there in read-only mode and sensors are listed in the area card.
If that'd be that easy, I would not post a feedback about completeness of instructions here.

**Comment by frenck** [comment]
That is a generic usage question, not related or specific to this integration. As per above, please use our community forums or Discord chat for general support on Home Assistant.

You are more likely to get the answer you are looking for in those places.

../Frenck
