### ISSUE TITLE
MIFlora non funziona con HA 2022,7

### ISSUE THREAD

**Issue by mcgnai** [home-assistant/home-assistant.github.io#23389]
### Feedback

Con la versione 2022.7 H.A ha aggiornando a Python 3.10. Con questa versione alcune librerie che utilizzano il bluethoot non funzionano più e pertanto l'integrazione con Miflora non funziona più. Abìvete pensato ad una soluzione per farlo tornare a funzionare?
Grazie

### URL

https://www.home-assistant.io/dashboards/plant-status/

### Version

2022.7.4

**Comment by frenck** [comment]
Sorry, we only communicate in English in the Home Assistant community.

../Frenck
