### ISSUE TITLE
Traccar integration: Improve variables description

### ISSUE THREAD

**Issue by AndreKR** [home-assistant/home-assistant.github.io#23387]
### Feedback

I just finished setting up the Traccar integration and I want to propose two documentation changes that would have saved me some headaches:

https://www.home-assistant.io/integrations/traccar/

Configuration variable `username` currently says:
> The username for the Traccar server.

I propose to change it to:
> The email address of the Traccar user.

This is because the field must be set to the email adress and *not* to the *name* of the user in Traccar:

![image](https://user-images.githubusercontent.com/1188538/178969232-6110f526-c35f-4c46-86d1-61e7ab7d8859.png)

Configuration variable `ssl` currently says:

> Use HTTPS to connect to Traccar server. NOTE A host cannot be an IP address when this option is enabled.

I propose to **add** another note:

> Note that this does not automatically set the port to 443.

This is because usually when you have an "SSL" option the port will be set based on that but here you have to set the port manually.

Also, if you *don't* set the port correctly, you will not get an error message. Only if you enable debug logging you will simply see repeated "DEBUG (MainThread) [homeassistant.components.traccar.device_tracker] Testing connection to Traccar" log entries.

### URL

https://www.home-assistant.io/integrations/traccar/

### Version

I cannot find the version number

**Comment by AndreKR** [comment]
> github-actions bot closed this as completed

That is a bit... misleading.

I could prepare a PR if there's a chance it'll get merged?

**Comment by ludeeus** [comment]
IMO I do not think these should be changed.
The integration should get a config flow instead.

**Comment by AndreKR** [comment]
> The integration should get a config flow instead.

Ah, I see. That's a bit beyond my current Python skills unfortunately.
