### ISSUE TITLE
Predicción solar para un inversor con 2 strings de diferente orientación 

### ISSUE THREAD

**Issue by Vicente-Ch** [home-assistant/home-assistant.github.io#23395]
### Feedback

Hola. Dispongo de un inversor huawei sun2000-6ktl-l1 de 6000w y tiene dos strings uno orientado al Sur Este de4850wp y otro orientado al Sur Oeste de 3880wp.
Juntos suman un potencia de 8.730wp pero el inversor nunca va generar mas de 6000w.
De esta forma debo crear 2 predicciones para el panel de energia de Home assistant, una con cada orientacion, y en cada una de ellas tengo que falsear la potencia del inversor, a la baja, porque sino me da un resultado de produccion muy elevado en las horas centrales.
Esta es la forma correcta? 
Gracias 

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2022.7.4

**Comment by frenck** [comment]
Sorry, the Home Assistant project is communicating solely in English.

Thanks 👍 

../Frenck
