### ISSUE TITLE
MIFLORA don't work with HA 2022.7

### ISSUE THREAD

**Issue by mcgnai** [home-assistant/home-assistant.github.io#23391]
### Feedback

Hi, With version 2022.7 HA we have updating a Python 3.10. With this version some libraries that use bluethoot no longer consume and therefore the integration with Miflora no longer works. Have you thought of a solution to make it work again? Thank you

### URL

https://www.home-assistant.io/dashboards/plant-status/

### Version

2022.7.4

**Comment by frenck** [comment]
Hi there @mcgnai 👋 

This is not the issue tracker for Home Assistant integration. You have submitted documentation feedback.

Your issue is already reported and can be tracked here:

<https://github.com/home-assistant/core/issues/74585>

../Frenck
