### ISSUE TITLE
Miflora

### ISSUE THREAD

**Issue by Pipitapi** [home-assistant/home-assistant.github.io#23409]
### Feedback

Help me! It hasn't been working properly for weeks. It was working fine before, no problem.

### URL

https://www.home-assistant.io/integrations/miflora/

### Version

2022.7.5

### Additional information

Help me! It hasn't been working properly for weeks. It was working fine before, no problem.

Error log:
The system cannot restart because the configuration is not valid:
 Integration error: miflora - Requirements for miflora not found: ['bluepy==1.3.0'].

configuration.yaml :
sensor:
  - platform: miflora
    mac: "C4:7C:8D:6C:79:21"
    name: Flower 1
    force_update: true
    median: 3
    go_unavailable_timeout: 43200
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery

**Comment by dannytsang** [comment]
@Pipitapi I think this is part of a known issue in 2022.7 and the removal of bluetooth library: https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes

**Comment by frenck** [comment]
As per above, this is a documented limitation/breaking change of this release.
