### ISSUE TITLE
How to update API key

### ISSUE THREAD

**Issue by branchm** [home-assistant/home-assistant.github.io#23414]
### Feedback

It would be great if the page could explain how to "update your configuration with the new key".  I'm poking around but I am not finding where to enter a newly-generated API key.  I'm sure it's right under my nose, but I'm not seeing it.
Thanks!

### URL

https://www.home-assistant.io/integrations/airvisual/

### Version

2022.7.5

**Comment by frenck** [comment]
Hi there @branchm 👋 

If Home Assistant encounters connections issues caused by an API key that is no longer accepted, it will show up in the integrations dashboard, asking for re-authentication (asking for a new API key).

../Frenck

**Comment by branchm** [comment]
Hmmm...  it's not asking me for a new key.
![image](https://user-images.githubusercontent.com/44331334/179361311-f12242f3-6fb6-4658-9a81-5c3558228a46.png)

**Comment by bachya** [comment]
@branchm Do you see a different AirVisual entry with a blue border in the upper left?

**Comment by branchm** [comment]
No, I don't.  I also searched the Integrations page for "AirVisual" - only the one match from the one shown above.  
And if I hit the AirVisual CONFIGURE button, I only get:
![image](https://user-images.githubusercontent.com/44331334/179361800-c0aee1cf-b694-4290-bee9-099b1a9ed548.png)

**Comment by bachya** [comment]
You may have run into a bug with the reauthentication logic. Please open up a code issue and make sure to fill out as much of the template as you can. Thanks!

https://github.com/home-assistant/core/issues
