### ISSUE TITLE
SSH to Cisco Router Broken

### ISSUE THREAD

**Issue by lozzriot** [home-assistant/home-assistant.github.io#23411]
### Feedback

When SSH'ing to Cisco Router - unable to connect and get the following message:

Unable to negotiate with 192.168.1.1 port 22: no matching host key type found. Their offer: ssh-rsa

Sounds similar to the issues with Ruckus Unleashed Integration 

https://github.com/home-assistant/core/pull/75032

### URL

https://www.home-assistant.io/integrations/cisco_ios/

### Version

2022.7.5

**Comment by frenck** [comment]
Hi there @lozzriot 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
