### ISSUE TITLE
Required libseccomp version wrong?

### ISSUE THREAD

**Issue by FabianSchwartau** [home-assistant/home-assistant.github.io#23413]
### Feedback

Hi,
the documentation says that `libseccomp 2.42 or newer` is required. However, the current version is only 2.5 (2.5.4 to be precise). I guess you meant version 2.4.2 is required? Or am I missing something here?

### URL

https://www.home-assistant.io/installation/linux/

### Version

2022.7.5

**Comment by frenck** [comment]
That is indeed a typo. I've opened up a PR to adjust it.

Thanks for reporting 👍 

../Frenck
