### ISSUE TITLE
can't connect Toon

### ISSUE THREAD

**Issue by csfolmer** [home-assistant/home-assistant.github.io#23429]
### Feedback

Hi, can't make a connection with the Toon (not rooted)

when add in the configuration.yaml the client id and secret Homeassistant reconize there is a new device (the Toon)
So that's oké!

when try to setup I get: 
![image](https://user-images.githubusercontent.com/75448794/179420474-f3787042-7207-4871-be4c-596bb118b4b8.png)

I see in the URL this ".....redirect_uri=**https://my.home-assistant.io/redirect/oauth**&state...." but that must be my own extrenal IP 77...45:8123. I think.

So there's something going wrong.
At the delevoper website of toon I did add my external ip "http://77......45:8123/redirect/oauth"

when add Toon intergation i'm using my extrenal IP for acces my home assistant.

what i'm doing wrong??
and how to solve it ;-)

### URL

https://www.home-assistant.io/integrations/toon/

### Version

2022.7.5

**Comment by frenck** [comment]
As per documentation of the Toon integration, you need to enter/configure/use this exact URL to be configured in your Toon developer account/application:

`https://my.home-assistant.io/redirect/oauth`

The error message you share, indicates you haven't done that, but used something else.

**Comment by csfolmer** [comment]
> As per documentation of the Toon integration, you need to enter/configure/use this exact URL to be configured in your Toon developer account/application:
> 
> `https://my.home-assistant.io/redirect/oauth`
> 
> The error message you share, indicates you haven't done that, but used something else.

aha that's it!
Thanks

**Comment by frenck** [comment]
Nice! Glad you've figured it out 👍
