### ISSUE TITLE
Documentation page not beginner-friendly

### ISSUE THREAD

**Issue by JeroenHaringman** [home-assistant/home-assistant.github.io#23424]
### Feedback

For me, as a beginner with HA, this documentation does not contain enough "sub steps" to successfully setup a DSMR reader integration in HA.

Either a more detailed description of the process, that assumes less knowledge by the reader, or a link to a more beginner-friendly documentation page would be much appreciated. 

I fully realise my lack of knowledge is the problem, but without more information I can't make progress.

### URL

https://www.home-assistant.io/integrations/dsmr_reader/

### Version

2022.7.5

**Comment by frenck** [comment]
Configuring Home Assistant is literally only this:

![image](https://user-images.githubusercontent.com/195327/179403911-876bbfd4-dcbf-47ef-afe0-e488473f1fa2.png)

The above is a screenshot from our documentation. Adding those two lines to your Home Assistant configuration is all there is. 

I'm not sure how that can be simplified or described more extensively? Could you elaborate?

../Frenck

**Comment by JeroenHaringman** [comment]
Yeah, I did that, but I can find no documentation on what to do next. The measurement data does not come up in the Energy section (the data from the SolarEdge integration does come up there).

I have checked the MQTT messages with the listener in HA, and they arrived there just fine, so that part works.

Again, my problem is that I am a beginner with HA, but I simply can't find any hint about what to do next.

**Comment by frenck** [comment]
> Yeah, I did that, but I can find no documentation on what to do next

That is not the point of the integration pages. They provide documentation on integrating, not on using it.

If you want to learn more about, for example, automations or the energy dashboard: we have dedicated pages for that. Those things are not specific to this (or other) integration(s).

> The measurement data does not come up in the Energy section

It should, if not, please create an issue in our issue tracker to report a problem with this integration.

**Comment by JeroenHaringman** [comment]
Well, after much googling, asking around, I found the energy dashboard config page and under Electricity grid, set or connected the Power usage total and Power return total values and now it works.

Thank you for your help and patience, I'm happy that it works - but I do wonder how many newbies can complete this process in one go.
