### ISSUE TITLE
Maria DB database size example is not working

### ISSUE THREAD

**Issue by bschollnick** [home-assistant/home-assistant.github.io#23425]
### Feedback

Running:
- Version | core-2022.7.5
- Installation Type | Home Assistant OS
- Development | false
- Supervisor | true
- Docker | true
- User | root
- Virtual Environment | false
- Python Version | 3.10.5
- Operating System Family | Linux
- Operating System Version | 5.15.32-v8
- CPU Architecture | aarch64
- Timezone | America/New_York
- Configuration Directory | /config

 The "Mariadb" example is stating "Invalid SQL" when I attempt to copy and paste into the SQL Query integration and submit it.
![image](https://user-images.githubusercontent.com/979558/179416235-9eed6709-8436-4383-b5f3-abcd061f7467.png)

![image](https://user-images.githubusercontent.com/979558/179416255-36c72552-b5a1-4994-b1d8-1ac137837f61.png)

I am using a Mariadb database on port 3306, I am able to get the exact same query to work via SQLPro studio.

![image](https://user-images.githubusercontent.com/979558/179416286-ba01c6b5-39c4-4744-8853-acc3ff57e2b7.png)

### URL

https://www.home-assistant.io/integrations/sql/

### Version

2022.7.5

**Comment by gjohansson-ST** [comment]
You need to specify the Database URL.

**Comment by bschollnick** [comment]
It says, to leave empty if I'm using the default database.  

The default database is the one that's currently in use...  Which would be the MariaDb....
....
....
....
Okay after another few rounds of trying different configurations.  I have it working.  
But it was very counter intuitive.
