### ISSUE TITLE
Alarm status (Armed, Home, Night mode) are not exposed to HomeKit - always "OFF" 

### ISSUE THREAD

**Issue by OwlBawl** [home-assistant/home-assistant.github.io#23422]
### Feedback

Alarm status (Armed, Home, Night mode) are not exposed to HomeKit - always "OFF" 
Used core SIA to integrate Ajax Systems alarm status.
Can see the state in HA, but when exposed to HomeKit - shows always "OFF" state.

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2022.7.5

**Comment by frenck** [comment]
Hi there @OwlBawl 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
