### ISSUE TITLE
SIA alarm status (Armed, Home, Night mode) are not exposed to HomeKit - always "OFF"

### ISSUE THREAD

**Issue by OwlBawl** [home-assistant/home-assistant.github.io#23421]
### Feedback

SIA alarm status (Armed, Home, Night mode) are not exposed to HomeKit - always "OFF"

### URL

https://www.home-assistant.io/integrations/sia/

### Version

2022.7.5

**Comment by eavanvalkenburg** [comment]
If the state of the alarm in HA is correct then it has to be a Homekit issue!

**Comment by OwlBawl** [comment]
> 

Ok, thank you. Would report in HomeKit core

**Comment by frenck** [comment]
Hi there @OwlBawl 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
