### ISSUE TITLE
Somfy connection kit support

### ISSUE THREAD

**Issue by Aspers** [home-assistant/home-assistant.github.io#23436]
### Feedback

Somfy recently released a new device to control their blinds, the 'Somfy Connection Kit'. I was able to integrate this hub with both the Overkiz and the Homekit integration in Home Assistant. Could be useful for other users if this get's added to the list of supported hubs since it's a great and cheaper alternative to the Tahoma Switch.

### URL

https://www.home-assistant.io/integrations/overkiz/

### Version

2022.7.5

**Comment by tetienne** [comment]
Any contribution is welcome :)

**Comment by Aspers** [comment]
Hehe 😅 I've updated the docs and created a PR! My first open source contribution 🎉
