### ISSUE TITLE
New python blocks homeassistant in pi3B+

### ISSUE THREAD

**Issue by nickolasemp** [home-assistant/home-assistant.github.io#23433]
### Feedback

While trying to install the Core, I could do everything but start hass. Could it be an issue with python3.7?

(homeassistant) homeassistant@rpi:/srv/homeassistant $ hass
Traceback (most recent call last):
  File "/srv/homeassistant/bin/hass", line 10, in <module>
    sys.exit(main())
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/__main__.py", line 278, in main
    args = get_arguments()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/__main__.py", line 60, in get_arguments
    import homeassistant.config as config_util
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 52, in <module>
    import homeassistant.helpers.config_validation as cv
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/config_validation.py", line 85, in <module>
    from homeassistant.helpers import (
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/script_variables.py", line 6, in <module>
    from . import template
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/template.py", line 19, in <module>
    from jinja2 import contextfilter, contextfunction
ImportError: cannot import name 'contextfilter' from 'jinja2' (/srv/homeassistant/lib/python3.7/site-packages/jinja2/__init__.py)

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.7.5

**Comment by frenck** [comment]
Python 3.7 is not supported, Home Assistant requires at least 3.9 (and we currently recommend 3.10).

**Comment by nickolasemp** [comment]
Alright I have updated 

 ```
        Python: 3.10.5
          platform: Linux-5.10.103-v7+-armv7l-with-glibc2.28
          pip: n/a
          setuptools: 63.2.0
          setuptools_rust: 1.4.1
          =============================DEBUG ASSISTANCE=============================
      
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      
      This package requires Rust >=1.41.0.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography

```

As for pip, it is weird cause I run:
(homeassistant) homeassistant@rpi:/srv/homeassistant $ pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in ./lib/python3.10/site-packages (22.1.2)
(homeassistant) homeassistant@rpi:/srv/homeassistant $

**Comment by frenck** [comment]
The things missing for your system are in the error description:

> error: can't find Rust compiler

**Comment by nickolasemp** [comment]
I think I found it. From the normal account (i.e. pi) I installed the following:
sudo apt-get install build-essential libssl-dev libffi-dev python3-dev cargo

and then from the homeassistant environment I did: 
pip install cryptography --no-binary cryptography

Link: https://cryptography.io/en/latest/installation/#building

**Comment by nickolasemp** [comment]
Fixed numpy by installing it before starting  hass  too

homeassistant@rpi:/srv/homeassistant $ source bin/activate
(homeassistant) homeassistant@rpi:/srv/homeassistant $ pip3 install numpy

same for sqlite:

```
wget https://sqlite.org/2021/sqlite-autoconf-3360000.tar.gz
tar -xvf sqlite-autoconf-3360000.tar.gz
cd sqlite-autoconf-3360000
./configure
make
sudo make install
```

hass still complained. It turned out to be where the libraries were installed.
The old libraries were in /usr/lib/arm-linux-gnueabihf/, whereas the new ones were in /usr/local/lib.
At that point I took the easy option (hass is the only application running, so no risk to other apps)…

```
sudo cp /usr/local/lib/*sql* /usr/lib/arm-linux-gnueabihf/
sudo chmod a+x /usr/lib/arm-linux-gnueabihf/*sql*
```

**Comment by frenck** [comment]
I'm not sure why you keep adding to this issue? The original issue created has been resolved right?

For all other cases report, our documentation is clear about it:

![CleanShot 2022-07-18 at 15 06 19](https://user-images.githubusercontent.com/195327/179517725-d31f4582-9693-4afb-8ca5-7441f4e3d8e6.png)

**Comment by nickolasemp** [comment]
agreed; just keeping it for anyone else who encounters something similar in rpi
