### ISSUE TITLE
Insteon is under new management

### ISSUE THREAD

**Issue by blue-hound** [home-assistant/home-assistant.github.io#23445]
### Feedback

The Insteon documentation should be updated to reflect that the company is back under new management. The cloud is active again but as of August 1st, 2022 they will require a subscription to access the cloud service.

The cloud is currently free and they are offering refurbishment of broken hubs at cost. 

The Smart Home name is no longer associated with Insteon but the insteon.com site is up and running. 

### URL

https://www.home-assistant.io/integrations/insteon/

**Comment by klaasnicolaas** [comment]
In the meantime, I think the current warning is sufficient with regard to the current status of Insteon.

**Comment by blue-hound** [comment]
Well, the current status of Insteon is open and accepting new subscriptions. So the warning isn't correct. It says they HAVE shutdown their cloud service but it has reopened.
