### ISSUE TITLE
Moving cards

### ISSUE THREAD

**Issue by randomhammer** [home-assistant/home-assistant.github.io#23447]
### Feedback

I am new to Home Assistant and am starting my first dashboard. It would be really great if the documentation mentioned how to move a card once created, or if that is not possible how to create it where I want it. I am about 30 minutes into this journey and cannot find anything that tells me how to move a card. It seems like a really basic function of a dashboard generator to allow me to place cards where I want them. 

Also, I tried the "instructions for getting support" on the right-hand side of this page as I was typing this feedback, and it leads to a 404 error.

Thanks for all of the hard work, but the documentation should really explain something as basic as moving dashboard cards into the position I want them in. 

### URL

https://www.home-assistant.io/dashboards/masonry/

### Version

2022.7.5

**Comment by dannytsang** [comment]
Hi @randomhammer

You can't set the position of the cards exactly to the pixel / cm / inches. It's controlled using [dashboard views](https://www.home-assistant.io/dashboards/masonry/) and then you can add (what I call layout) cards to position them within the dashboard views such as [grids](https://www.home-assistant.io/dashboards/grid/).

You can have cards within a card e.g. a grid within a grid to try and get the layout you want.

I can't comment the error 404.

I hope that helps.

**Comment by randomhammer** [comment]
Thanks for the help dannytsang! It’s really hard to figure this out if the documentation doesn’t say something, and as soon as I google I get all kinds of outdated posts and tutorials that make it even harder. I wish there was a guide, for 2022, that explained concepts like this. These things are obvious to many, but baffling if you are new.
