### ISSUE TITLE
Update documentation to mention that this integration is currently broken

### ISSUE THREAD

**Issue by kekonn** [home-assistant/home-assistant.github.io#23453]
### Feedback

As per https://github.com/home-assistant/core/issues/74564 , this integration is currently broken. It would be best to mention this at the top and link to the issue in question for updates.

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2022.7.5

**Comment by frenck** [comment]
We don't document issues, issue can be reported and should be fixed instead.

Nevertheless, thanks for your feedback 👍 

../Frenck
