### ISSUE TITLE
Missing option to reset/restart configuration

### ISSUE THREAD

**Issue by CharlPels** [home-assistant/home-assistant.github.io#23464]
### Feedback

When adding home connect is giving an issue, you will not see the intergation in integrations.
However the wrong settings are stored somewhere and you are unable to restart config in any way.
When you add the home connect again it stil ussing the old/wrong values and no way to change this.

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2022.7.5

**Comment by frenck** [comment]
I think you are looking for the application credentials? And not integration settings? (And mixing those things up as it seems?)

![CleanShot 2022-07-20 at 13 20 53](https://user-images.githubusercontent.com/195327/179969824-4913b5f4-c593-48ff-85b5-f381b00c71e6.png)

**Comment by CharlPels** [comment]
Thanks, did not know about this to “hidden” option

**Comment by frenck** [comment]
No problem, glad you got it figured out 👍
