### ISSUE TITLE
Opentherm Gateway install

### ISSUE THREAD

**Issue by Frank-Bemelman** [home-assistant/home-assistant.github.io#23461]
### Feedback

It is quite unclear what to fill in for name, address and ID.

Ok, name seems to be used as a prefix for namingto the various entities -> please eplain that.

Address - what adress? filling in an IP address does not work. Antoher guess http:\\192.168.1.40 does not work. Adding a port number, does not work. After hours of searching, it seems that you have to type socket:\\192.168.1.40 or whatever the IP address is and NO port number. 

Otgw unit needs to be set at 23. Nobody tells you that. You to dig through tons of google searches to find out.

And what is ID? my social security number? What is is used for? Explain!!!

The integration self lacks clarifcation as well. Absolutely no hint what to fill in. Is it really that difficult to give some hints, pointers or is it the idea to keep everbody in the dark.

And then, it does not work. An unknown error has occurred. Brilliant.

### URL

https://www.home-assistant.io/integrations/opentherm_gw/

### Version

2022.7.5

**Comment by mvn23** [comment]
Thank you for your feedback. Unfortunately you have tried to add the integration at a bad time, as we had some breakage with the update to python 3.10. This is likely causing your config flow to fail with the unknown error and will be fixed in 2022.7.6. If you are not running python 3.10, please file a bug report with associated debug logs and I will look into it.

As for the configure options, they are all explained in the integrations documentation page you already [linked to](https://www.home-assistant.io/integrations/opentherm_gw/#configuration). There you will also find a reference to the PySerial docs regarding the format of the Path parameter, which is quite a bit more extensive than just `socket://[ip address]` and does actually support a port and several other connection methods as well.
Could you please elaborate on where exactly you find the documentation lacking?

**Comment by Frank-Bemelman** [comment]
Apollogies for my harsh comments. It starts with the first dialog when you add the integration. There is no informative introduction. Just the fields 'name', 'path or url' and 'ID'. It would already help if there was a text something like this:

Give your gateway a preferably short name, this name will be used as a prefix for the mountain of entities your gateway will produce. For path or url, type socket://<ipaddress>:port and for ID type in (yes what, I don't know).

The documentation tells that ID is explained as: The gateway_id for this OpenTherm Gateway’s entity IDs and services. The entered value will be slugified. I have no idea what that is. Or is it that 'name' is not the prefix for the entities? Ok, then the introduction text of the add integration dialog could be perhaps something like this:

Give your gateway a name, just for the purpose of labeling it, just like you would give your dog a name. For path or url, type socket://ipaddress:port you got  during the physical install and test of your gateway. And for ID type in  a preferably short name, as this name will be used as a prefix for the mountain of entities your gateway will produce. Enjoy!

Yes, you are right, in the documentation it is also written down, but it is a bit overwhelming for a first encounter for someone who has (yet) no clue at all. The path is explained by a link to pyserial and for a novice that is another overwhelming resource:

rfc2217://<host>:<port>[?<option>[&<option>...]]
socket://<host>:<port>[?logging={debug|info|warning|error}]
loop://[?logging={debug|info|warning|error}]
hwgrep://<regexp>[&skip_busy][&n=N]
spy://port[?option[=value][&option[=value]]]

Most folks and certainly me, don't know how quickly they have to hit the back button in the browser.

So, perhaps for explanation of path this might suit better:
Path: Fill in socket://<ipadress>:<port> For the actuall ip adress consult the installation of your gateway hardware.  More sophisticated paths can be found at  [PySerial](https://pythonhosted.org/pyserial/url_handlers.html).

That path/url thing really need a better explanation. I can't be the only one that tries http://ipadress without port on such invitation. 

Ok, my timing was unfortunate, with the integration being broke for the moment. I'll wait for 2022.7.6 and see what happens.
Thank you for your time and kind repy.

**Comment by mvn23** [comment]
Ok, I see what you mean but I'm not sure if a long explanation in the config flow is the way to go. It's just too much information to put in a dialog like that. Adding some examples to the docs might be a good idea though.

Either way I may reconsider the options given in the config flow. They were all relevant when configuration was done in yaml, but now we have other techniques available as well.
The name can be set through the `Devices` page after adding and the id could be removed if we switch to entity services for the integration. Then only the path would have to be filled in the config flow and we could give a short explanation in the dialog.
This may take some time, so in the short term I may add some examples in the docs only.

**Comment by Frank-Bemelman** [comment]
The other day I got it working, with the 2022.7.6 release. That is good news. If the add integration dialog box can be simplified, all the better of course. You know better what can be left out ;-) 
Thanks again!
