### ISSUE TITLE
Clarify Calendar integration documentation

### ISSUE THREAD

**Issue by lindhe** [home-assistant/home-assistant.github.io#23466]
### Feedback

In the docs for the Calendar integration, it says "The calendar integration allows you to integrate your calendars into Home Assistant" but not how to add a calendar. It uses `calendar.personal` in the examples, but no mention of how it got there. I think that should be added.

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2022.7.5

**Comment by frenck** [comment]
The calendar is an base entity, that is provided by other integrations (you can't create one yourself) and describes the base functionality of the calendars (regardless of which integration provides them).

You can find integrations providing calendars here:

https://www.home-assistant.io/integrations/#calendar

**Comment by lindhe** [comment]
Cool. That's impossible to gather purely from the documentation... :)
