### ISSUE TITLE
Cannot seem to use the Forecast.Solar free API (without API Key

### ISSUE THREAD

**Issue by dabeetle** [home-assistant/home-assistant.github.io#23463]
### Feedback

Hi,

I tried to change the WP settings for the integration as I have a new set of solar panels. But the configuration now requires a value in the API Key field (which is labeled as being optional) so I cannot save my update. The error message I get when I try to save without entering an API key is "User input malformed: expected str for dictionary value @ data['api_key']"

Documentation also states that you can use the Free version of forecast.solar.

Can you please remove the mandatory setting for the API field?

Thanks,
Maarten

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2022.7.5

**Comment by klaasnicolaas** [comment]
Hi there @dabeetle 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by klaasnicolaas** [comment]
For your information, there is now a bug fix in 2022.7.6 that should solve this problem.

**Comment by dabeetle** [comment]
Sorry for using the wrong feedback page and thanks for the pro-active attitude and fix!
