### ISSUE TITLE
Templating examples would be nice to have

### ISSUE THREAD

**Issue by DavidJegust** [home-assistant/home-assistant.github.io#23475]
### Feedback

Templating examples would be nice to have, eg.
{{ (is_state('input_boolean.alarm_on','on')) }}
{{ (states('input_boolean.alarm_on')) }}

### URL

https://www.home-assistant.io/integrations/input_boolean/

### Version

2022.7.6

**Comment by frenck** [comment]
This page isn't about templates, it is about setting up input booleans.

If you want to learn more about templates, check out our templating documentation here:

<https://www.home-assistant.io/docs/configuration/templating/>

../Frenck
