### ISSUE TITLE
Instructions are unclear

### ISSUE THREAD

**Issue by turtlelips** [home-assistant/home-assistant.github.io#23474]
### Feedback

Totally new user here of home assistant... 

None of this works for me. 
There doesn't seem to be a reference that shows how to put something in a "configuration.yaml" file. Don't even know where to start there... 

Why aren't there entities in the sun integration like everything else? 

### URL

https://www.home-assistant.io/integrations/tod/

### Version

2022.7.6

### Additional information

What do I do with this? 

binary_sensor:
  - platform: tod
    name: Early Morning
    after: sunrise
    after_offset: "-02:00"
    before: "07:00"

  - platform: tod
    name: Late Morning
    after: "10:00"
    before: "12:00"

**Comment by frenck** [comment]
![CleanShot 2022-07-21 at 08 45 58](https://user-images.githubusercontent.com/195327/180147793-8c3faba2-6e42-4d85-b90d-da24a8ebb2bc.png)

Which will bring you to: <https://www.home-assistant.io/docs/configuration/>

> Why aren't there entities in the sun integration like everything else

There are?

**Comment by Neekster** [comment]
The time of day integration can be set up through the UI, though you won't be able to use Sunset as a time. Also, make sure you restart HA after editing the config file to make the changes actually happen.
