### ISSUE TITLE
great, easy to follow

### ISSUE THREAD

**Issue by Kleed3000** [home-assistant/home-assistant.github.io#23482]
### Feedback

just some positive feedback.
easy to read also for the not so tech savvy user.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.7.6

**Comment by Kleed3000** [comment]
Apologies, I did not now this would great an issue.
I will close the ticket from now.

**Comment by Kleed3000** [comment]
Apologies, I did not now this would great an issue.
I will close the ticket from now.

**Comment by frenck** [comment]
> just some positive feedback.
> easy to read also for the not so tech savvy user.

Don't worry! Thank you for sharing this! ❤️ 

@allenporter the message above if for you 👆

**Comment by allenporter** [comment]
Thank you for the kind words! You made my day.
