### ISSUE TITLE
Change Units of data from KiB/S to Mbs

### ISSUE THREAD

**Issue by plandregan** [home-assistant/home-assistant.github.io#23497]
### Feedback

How can we alter the WAN usage from the KiB/s unit, which is KiloBytes per second. To something more useful, such as Mb/s Megabits per Second. Which is more usual to see

### URL

https://www.home-assistant.io/integrations/upnp/

### Version

2022.7.6

**Comment by StevenLooman** [comment]
At this moment you cannot.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
