### ISSUE TITLE
Scan interval missing

### ISSUE THREAD

**Issue by jhallenb** [home-assistant/home-assistant.github.io#23496]
### Feedback

When adding a tellstick net as an (auto discover) integration I see no way of changing the scan_interval?

### URL

https://www.home-assistant.io/integrations/tellduslive/

### Version

2022.7.6

**Comment by frenck** [comment]
> When adding a tellstick net as an (auto discover) integration I see no way of changing the scan_interval?

That is correct. YAML can sometimes allow for more advanced configuration options not available via the UI.

In general, `scan_interval` settings are considered legacy and slowly being removed from everywhere in Home Assistant.
