### ISSUE TITLE
Modbus Instructions 

### ISSUE THREAD

**Issue by poratnir1** [home-assistant/home-assistant.github.io#23499]
### Feedback

Examples are not clear enough, no instructions how to combine two modbus channels.
 

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2022.7.6

### Additional information

modbus is not working properly - status is not being updated

**Comment by janiversen** [comment]
???? You just add 2 comm configurations (e.g. - name: ....) within the same modbus configuration.

This is normal yaml configuration.

But if you want it spelled out, patches are welcome.

**Comment by janiversen** [comment]
and while you are at it, why not read https://www.home-assistant.io/integrations/modbus/#configuring-multiple-connections
that should cover the topic.

**Comment by poratnir1** [comment]
Modbus under the following simply does not update the coil status ...
modbus:
  - type: rtuovertcp
    host: 192.168.1.7
    port: 501
    timeout: 2
    switches:
      - name: Switch1
        slave: 3
        address: 0
        write_type: coil
      - name: Switch2
        slave: 3
        address: 1
        write_type: coil
      - name: Switch3
        slave: 3
        address: 2
        write_type: coil
      - name: Switch4
        slave: 3
        address: 3
        write_type: coil
      - name: Switch5
        slave: 3
        address: 4
        write_type: coil
      - name: Switch6
        slave: 3
        address: 5
        write_type: coil
      - name: Switch7
        slave: 3
        address: 6
        write_type: coil
      - name: Switch8
        slave: 3
        address: 7
        write_type: coil


Moreover , it is still not clear how to combine two adapters into one YAMAL FILE .

Only one"modbus:" is allowed

**Comment by janiversen** [comment]
You only need one "modbus" statement, and below it 2 "-", please see the documentation link I gave you it shows how to add 2 connections.

**Comment by janiversen** [comment]
I cannot tell you why a coil is not being updated, without a debug log, it might be that you simply are using the wrong addresses. 

Please refer to the docs.

**Comment by poratnir1** [comment]
As I mentioned before in older version everything is wroking .0114 without any other settings...100% fine
in the new version even indents are causing troubles , how can i retentive the verify function from the working version?

I never added any address to the code..so what changed? 
Why now instead of having a simple address and coil number which was working great, need to add verify section per each coil?,
Manual does not indicate the relation between coil to its register, per my understanding...code did something before...



this is the only error I get ...

Pymodbus: modbus_hub: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 2 bytes (0 received)
7:09:58 AM – (ERROR) Modbus - message first occurred at July 23, 2022 at 11:27:49 PM and shows up 7609 times

I am not a modbus expert .. but i assume the purpose of coil setup is to have a direct and simple function...

Any idea how to help me here?...

this is upsetting that functions are not working as they worked before... and need to provide data which is not intuitive..

**Comment by janiversen** [comment]
You cannot make a configuration without adding an address, that is and was never legal.

the error you get normally means you try to read a non-existing register.

It might be upsetting to you, but the wast majority of users wants more functionality which means changes in the configuration, if you do not like that, feel free to use the old version.

**Comment by janiversen** [comment]
Closing as not relevant.

**Comment by poratnir1** [comment]
Hey there..

I am tying to get help to resolve this matter...
i have read the instructions several times without success to get this to work..

regard the version , old version is working but some new integrations are not working, so updated is needed for my end and i will apricate if can assist to partially resolve it or point out what am I doing wrong..

**Comment by janiversen** [comment]
You might have misunderstood something, this is not a support forum. There are an active HA community who can help you.

Issues in here are error reports.

**Comment by poratnir1** [comment]
Well, I have been trying for the last few months few times to use the forum without any input regard this matter... I will try again..

All in all 
I think the documentation in the website is far from being clear ... and in the website I found this link for errors or bugs needs reporting ...
and the purpose here is to report a suspected bug .. which according to my understanding now , issue subjected to settings which are not so clear in terms of the settings.

Moreover .. as setup was fully working in the older version I assume default values for the registers were predefined somewhere therefore it should be the right place to retrieve the default settings ...

**Comment by janiversen** [comment]
It seems to me, it is less a question of the documentation not being clear, as to understanding the documentation. When you configure modbus we expect you understand modbus. Your problems might be even more basic, considering the problems you wrote about combining 2 adapters (for which there are an example).

There are 3 switch examples, covering the 3 forms to use a switch, what do you want more...of course you cannot copy/paste these examples you need to read the documentation of your device and adapt them (like e.g. not use holding unless your doc says so).

The old setup was severely limited in functionality, but as I said if you want to stay with that, copy the version of the modbus integration you want as a custom component and use it. The changes is setup is because users want new features.

**Comment by poratnir1** [comment]
Perhaps you are right...iI am not a modubs expect...
So there are two separate issues that are coming from different sources..
Regarding combining two modbus systems it does not work on the old version, and i think the example is partial.

Regarding switch examples, I did not find a gap between light to switch,so basically I am using switch for all items.

Regarding verifying feature I simply think this is a must-have part that is not working and in that case, the example for people without the proper experience is simply misleading.


moreover, if I am even reading the spec which is using the common modbus function I cannot link the registers of the coils into the HA syntax..

I am only trying to get some help to debug... and correct me if I am wrong .. the purpose of the system is to be accessible also for people who do not have all knowledge in specific protocols.
