### ISSUE TITLE
Hyperion integration is unstable and unusable with the RPi implementation

### ISSUE THREAD

**Issue by zaneclaes** [home-assistant/home-assistant.github.io#23494]
### Feedback

I have 5 different Raspberry Pis running Hyperion (latest, installed per Hyperion documentation for RPi). Each one of them exhibit the same problems that render them effectively unusable with home assistant. None of these problems are present with the native Hyperion interface. Rather, all of them appear to be issues with the HA/Hyperion communication, as I can try the same operations from the Hyperion web interface and they reliably succeed.

I first noticed that turning on/off a Hyperion instance is incredibly inconsistent. About 1/5 times, my simple `light.turn_on` or `light.turn_off` automation fails. There is no error message, but about 1-2 seconds after triggering, it reverts to the old state. Thus, my time-based automations fail silently, and remain in the old state. I can see the same thing happening occasionally even without the automation; simply pressing the toggle (switch) in HA will sometimes inexplicably revert itself. Note that all the hardware is hard-wired (not WiFi), running on a Raspberry Pi 4 — so there's effectively zero chance of resource/bandwidth bottlenecks being the root cause. 

Similarly, I cannot get any automation to work for gracefully resuming the light state. For example, I tried adding an automation for when the light leaves the `disabled` state. However, there are many bugs here: 
- Home Assistant doesn't always update the devices into the `disabled` state, instead seeing them as `off` despite the fact that they are unreachable on the network.
- If I trigger an automation to turn the light on when the state changes, it does not work at all. I can run the automation normally and see the light turn on, but if I trigger the automation when the instance leaves the `disabled` state, it does not turn on the light ever. I have also tried adding a 30 second delay to the automation, in case it has to do with boot up lag.
- If I manually trigger the same automation again (`light.turn_on` with an effect specified while the light is already on) it in fact turns off the light instead of turning it on.

### URL

https://www.home-assistant.io/integrations/hyperion/

### Version

2022.7.6

**Comment by dermotduffy** [comment]
Please open a bug against hass-core, this is the repo for documentation changes:

Go here and re-paste the bug: https://github.com/home-assistant/core/issues

**Comment by zaneclaes** [comment]
Oops, thanks. I saw the link was from the docs, but the GitHub repo name appeared to be a generic product repo ;)
