### ISSUE TITLE
Please add Synology DVA functions (face recognition, license plate recognition)

### ISSUE THREAD

**Issue by dimadusk** [home-assistant/home-assistant.github.io#23502]
### Feedback

Hello, I want to thank you for hard work. Is it possible to add DVA features of Synology surveillance station to home assistant so automations and scenes will be triggered upon face recognition or license plate from cameras?

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2022.7.6

**Comment by mib1185** [comment]
Hi 

please use the [feature request](https://community.home-assistant.io/c/feature-requests) section of our forum to contribute on existing or create new feature requests.
For sure, contributions are always welcome, so please feel free to create a PR on your own.

Thanks! 👍
