### ISSUE TITLE
Use correct grammar and punctuation

### ISSUE THREAD

**Issue by OldSurferDude** [home-assistant/home-assistant.github.io#23513]
### Feedback

The purpose of documentation is to instruct the reader.  The reader should not have to guess at the meaning of a sentence.  For example, on this page is written: "Services can be passed parameters to for example tell which device to turn on or what color to use."  The concept would be clearer if it were written "Parameters can be passed to services, for example, to command which device to activate or which color to use.  While your uses of the term "service" is correct, for computer savvy people, "service" has a different meaning.   "Utility", even "Helper", would make the concept clearer.

### URL

https://www.home-assistant.io/docs/automation/basics/

### Version

2022.7.6

**Comment by frenck** [comment]
👋 @OldSurferDude!

Feel free to open up a PR to adjust the documentation 👍 

../Frenck

**Comment by OldSurferDude** [comment]
Feeling free, I believe I did just submit a PR.

OSD
