### ISSUE TITLE
Support needed for "Water Exhausted  Monitor" mode on YoLink YS7904 (Leak Sensor w/ Probe)

### ISSUE THREAD

**Issue by SemoTech** [home-assistant/home-assistant.github.io#23527]
### Feedback

Hello,

While the YoLink Leak Sensor w/ Probe (YS7904) works currently, the HA integration does not seem to properly support the new "Water Exhausted Monitor" mode, whereby the water probe/sensor is [submerged](https://www.youtube.com/watch?v=9GXtrSy23Fc) by default, and will only alert when dry (water level drops below the probe). This is the reverse of the normal leak functionality, and fully supported by the YoLink system. 

![image](https://user-images.githubusercontent.com/1452100/180873485-e3e97fb6-6956-40d2-920c-4b21ca24e2a2.png)

Currently and while the sensor is in the "Water Exhausted Monitor" mode, Home Assistant reports it as "Dry" instead of "Wet" or "Water Present" or similar, to signify that it is a normal condition for this mode.  Can that be changed/adjusted based on the mode set in the YoLink cloud?

Also, while the overall YoLink integration seem to work, after adding sensors on the YoLink app/side one has to force a "Refresh" of the integration in HA for the new sensors to be loaded.   Not sure if this is normal.

Thank you.

### URL

https://www.home-assistant.io/integrations/yolink/

### Version

2022.7.6

### Additional information

YoLink Hub (YS1603) firmware version: 0352
YoLink Leak Sensor w/ Probe (YS7904) firmware version: 0469

**Comment by SemoTech** [comment]
@matrixd2 Can you or anyone help with this?
Thank you.

**Comment by SemoTech** [comment]
@matrixd2 Sorry to bug you, but can you or anyone else help with this?
Thank you.

**Comment by klaasnicolaas** [comment]
Hi there @SemoTech 👋

It seems like you want to report an issue with an Home Assistant integration or ask for a feature request, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Or in case you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

./Klaas
