### ISSUE TITLE
Unique ID error for D-Link integration (DSP-W320)

### ISSUE THREAD

**Issue by mmccool** [home-assistant/home-assistant.github.io#23523]
### Feedback

Followed instructions, but got a "no unique id" error and while the entity shows up, it does not allow control of the switch.  Attempting to add a unique id via the configuration.yaml file results in an incorrect configuration.  To be fair, however, I am attempting to integrate a D-Link 320, which is not one of the supported devices.  It also only shows up as one switch but this device has two.  Device has been confirmed working via the D-Link app on an iPhone.

### URL

https://www.home-assistant.io/integrations/dlink/

### Version

2022.7.6

**Comment by frenck** [comment]
Hi there @mmccool 👋 

It sounds like you are trying to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
