### ISSUE TITLE
Unexpected error while trying add Switch bot integration

### ISSUE THREAD

**Issue by ArunHA2022** [home-assistant/home-assistant.github.io#23539]
### Feedback

Hi There, I am new to HA , recently got 2 switchbot curtain rods and trying for HA integration. Every time I try I get the Unexpected error message. Could you please advice on how to make it work.

Thanks 
Arun

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2022.7.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
