### ISSUE TITLE
OpenUV Automation example will exceed request limit

### ISSUE THREAD

**Issue by TheNr1Guest** [home-assistant/home-assistant.github.io#23538]
### Feedback

It is stated that when you execute `openuv.update_data` every 30 minutes that you will have plenty of requests left. This is not true for countries where the time difference between sun rise and sun set is more than 12 hours during the summer (countries above the equator). Since `openuv.update_data` performs 2 calls every 30 minutes, you would hit more than 50 calls after 12,5 hours.

With only 32 countries being below the equator I think this example is not representative for the majority of users.

### URL

https://www.home-assistant.io/integrations/openuv/

**Comment by bachya** [comment]
The API warnings are clearly listed at the top of the docs:

![image](https://user-images.githubusercontent.com/47216/181054268-d50f77fc-0d9b-4b64-99cf-ac6cc1e4dc7f.png)

Given that the example automation in question is fairly self-descriptive, I would anticipate that users would adjust based on their own locales. That said, if you think there is a better, more universal way to describe this, I'm very open – feel free to submit a PR.

**Comment by TheNr1Guest** [comment]
The reason why I bring it up is that you cannot in the example extend the `/30` time pattern to let's say `/40` since this would not give the expected behavior of an interval of 40 minutes so a more elaborate automation is required.

`/40` will still trigger twice per hour: once on the whole hour and once on the whole hour + 40 minutes.
