### ISSUE TITLE
Self-Consumption

### ISSUE THREAD

**Issue by flipcom** [home-assistant/home-assistant.github.io#23536]
### Feedback

I set up my PV system from SMA. Unfortunately, I'm missing the entity ID for self-consumption.
Does it even exist or can I possibly calculate the value from 2 different entity IDs?

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2022.7.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
