### ISSUE TITLE
Adding ifttt example for sending fees data and events to HA

### ISSUE THREAD

**Issue by robhellstrom** [home-assistant/home-assistant.github.io#23548]
### Feedback

Hi I have spent many hours trying to work through and debug the IFTTT/HA integration.

my scenario was to send data from Adafruit IO via its ifttt integration into HA. There is hardly any info and lots of unanswered questions.

 It seems it would be very useful for the community to improve the documentation especially to include automation triggers which is what I had to use.

### URL

https://www.home-assistant.io/integrations/ifttt/

### Version

2022.7.7

**Comment by dannytsang** [comment]
There's a section on receiving events from IFTTT. Do you have any specifics on what could be improved?
