### ISSUE TITLE
Correct OpenWrt spelling

### ISSUE THREAD

**Issue by tmo26** [home-assistant/home-assistant.github.io#23554]
### Feedback

Please mind the correct spelling: OpenWrt
Capital "O"
Capital "W"
No other capitals.

In case you are unsure about the correct spelling: See the OpenWrt logo on the same page.

![grafik](https://user-images.githubusercontent.com/12309103/181368440-f51dc9d6-56b2-4b5c-bbd6-11e6fb1834e4.png)

Would be great if you could correct this on the whole Home Assistant website.

Thanks in advance!

### URL

https://www.home-assistant.io/integrations/luci/

### Version

2022.7.7

**Comment by frenck** [comment]
Thanks, @tmo26 👍 
I opened up PRs to fix that.

../Frenck
