### ISSUE TITLE
GREAT instructions for this integration

### ISSUE THREAD

**Issue by knwpsk** [home-assistant/home-assistant.github.io#23558]
### Feedback

I don't need anything.
Just want to give a shout out to the author for giving such great, detailed, thorough installation instructions.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2022.7.7

**Comment by frenck** [comment]
Hey, @allenporter this one is for you! ☝️ 

Thanks for sharing a bit of love there @knwpsk ❤️ 

../Frenck
