### ISSUE TITLE
Unable to re-authenticate

### ISSUE THREAD

**Issue by hvoerman** [home-assistant/home-assistant.github.io#23553]
### Feedback

HA notified me that I needed to re-authenticate. Doing so results in 

```
// 20220727220049
// https://api.honeywell.com/oauth2/app/acl?apikey=[REDACTED]&app=[REDACTED]&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmbG93X2lkIjoiOGQ2NGI3ZTdkNDM2MjE5YzA4MzllZGZmNGYyMWZkNmYiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL215LmhvbWUtYXNzaXN0YW50LmlvL3JlZGlyZWN0L29hdXRoIn0.Jx9smcHhIiU50PGdd0Rfhnzpkl8KnD1BzgOz5BiQRQo&redirect_uri=https%3A%2F%2Fmy.home-assistant.io%2Fredirect%2Foauth&source=3A426CA91B8EC4173FA7A5D79E33E97A&lnsReg=true&futureDevices=null

{
  "status": 401,
  "message": "Error getting user devices: Unauthorized",
  "type": "internal"
}

```
Please provide some guidance on what to do.

### URL

https://www.home-assistant.io/integrations/lyric/

### Version

2022.7.7

**Comment by timmo001** [comment]
This issue is for the home-assistant/core repository, however I have got this today. Maybe their server is having issues

**Comment by AFumi39** [comment]
Same here.
Yesterday the Honeywell server gone offline for few hours (even the Resideo app didn't work). Today HassOS says the integration need to reauthenticate, but when I click on "Reconfigure" button, the page (https://api.honeywell.com/oauth2/authorize?response_type=code&client_id=XXX&redirect_uri=https://my.home-assistant.io/redirect/oauth&state=YYY) says:
{"code":400, "message":"The redirect URL provided does not match the redirect URL registered for the app."}

Please, can you fix this?

**Comment by AFumi39** [comment]
Finally I managed to complete the procedure (I removed integration and trying to add again), but at the end a popup on HA web page simply says "Error". Even if the procedure now seems go well.

This is the error:
`2022-07-28 12:17:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 168, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 95, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 303, in async_step_creation
    token = await self.flow_impl.async_resolve_external_data(self.external_data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 169, in async_resolve_external_data
    return await self._token_request(
  File "/usr/src/homeassistant/homeassistant/components/lyric/api.py", line 64, in _token_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.honeywell.com/oauth2/token')`

**Comment by navigat0** [comment]
I am having a similar issue (I am running hass local only (no cloud)), when adding the integration, the redirect takes me to the resideo login page, and I log in with my Honeywell Home credentials I get an Internal Server Error 500 
`500 Internal Server Error
Server got itself in trouble `
which seems to indicate some issue on the Honeywell side or with the request the integration is sending and is very similar or the same issue as @AFumi39.

**Comment by AFumi39** [comment]
> I am having a similar issue (I am running hass local only (no cloud)), when adding the integration, the redirect takes me to the resideo login page, and I log in with my Honeywell Home credentials I get an Internal Server Error 500 `500 Internal Server Error Server got itself in trouble ` which seems to indicate some issue on the Honeywell side or with the request the integration is sending and is very similar or the same issue as @AFumi39.

I managed to get it works.
Unlike what official page https://www.home-assistant.io/integrations/lyric says, you cannot use <HOME_ASSISTANT_URL>/auth/external/callback as callback url, because the integration fails afterward.
You have to use https://my.home-assistant.io/redirect/oauth and try more and more, until it works till the end.

**Comment by hvoerman** [comment]
I can report that another attempt this evening (UTC+0200) was successful. I just pressed configure of the lyric integration, was redirected to the website, logged in and approved the access and done. Of course I already had my client_id/secret provided in earlier attempts.

So, it looks like Resideo had something broken that seems to be fixed again.

**Comment by navigat0** [comment]
Since my integration has never been successfully installed (and thus I have nothing to uninstall) and I have seen evidence of it using prior application client ID and key, how can I clean up any prior Lyric integration data in HASS and start fresh?

**Comment by hvoerman** [comment]
remove the lyric related data from config\.storage\application_credentials on the HA box. I have samba installed to access the HA filesystem.

**Comment by navigat0** [comment]
Thanks for the responses all.  Like most everyone else things don’t work and then they suddenly do.  I didn’t end up clearing my creds (but I’ve noted the new knowledge) and the integration is installed and working.  I think doing it in a private browser window helped too.   I gotta give some props to the Honeywell developer site designers for including the interactive API calls.  It allowed me to better understand the capabilities (and limitations) of the T6 and Resideo/Honeywell/Lyric platform.  Y’all are awesome!
