### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by bigemme** [home-assistant/home-assistant.github.io#23556]
### Feedback

Error during configuration:

"This integration does not support configuration through the user interface. If you followed this link from the Home Assistant website, make sure you have the latest version of Home Assistant."

:(

### URL

https://www.home-assistant.io/integrations/tractive/

### Version

2022.7.7

**Comment by bieniu** [comment]
Please explain what is a problem. You opened an issue in the documentation repository and it seems to me that your problem is related to the integration, not the documentation.

**Comment by frenck** [comment]
Hi there @bigemme 👋 

bieniu above is right, it seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by bigemme** [comment]
Ok, sorry.
Thanks!
