### ISSUE TITLE
Bluetooth integration new page has typo

### ISSUE THREAD

**Issue by IainPHay** [home-assistant/home-assistant.github.io#23562]
### Feedback

First line under title has a typo:

"The Bluetooth Monitoring and Discovery integration will detect nearby **bluetoth**"

bluetoth should be bluetooth

### URL

https://rc.home-assistant.io/integrations/bluetooth

### Version

2022.7.7

**Comment by frenck** [comment]
This typo has been fixed. Thanks for reporting! 👍 

../Frenck
