### ISSUE TITLE
bad link in configuration doc page

### ISSUE THREAD

**Issue by exnazirite** [home-assistant/home-assistant.github.io#23563]
### Feedback

https://www.home-assistant.io/docs/configuration/
suggests 

> The easiest option to edit configuration.yaml is to use the [Studio Code Server add-on](https://my.home-assistant.io/redirect/supervisor_addon?addon=a0d7b954_vscode). ...

This link gets me "Add-on not found"

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2022.7.7

**Comment by dannytsang** [comment]
The link works for my install. Can you see the **Studio Code Server** from the Add-on store because if not, you need need to turn on *Advanced Mode* in your profile.

**Comment by frenck** [comment]
Tested it as well, the link works and is correct.

../Frenck
