### ISSUE TITLE
List compatible HW models

### ISSUE THREAD

**Issue by iBobik** [home-assistant/home-assistant.github.io#23576]
### Feedback

Currently there is only one Tinker board listed, but there are many models.

Could you maintain tested or theoretically compatible list of boards what will work with this image and guide? Or at least how we can evaluate it, e.g. the same CPU family.

(I am specifically interested in compatibility with Tinker Edge T.)

### URL

https://www.home-assistant.io/installation/tinkerboard/

### Version

2022.7.7

**Comment by frenck** [comment]
Only the Asus Tinkerboard S is supported. The list is up to date.
