### ISSUE TITLE
Switch as X => Change device type of a switch

### ISSUE THREAD

**Issue by hareeshmu** [home-assistant/home-assistant.github.io#23575]
### Feedback

There is no "Switch as X" under create helper options.
- From the list, search and select “Switch as X”. - This should be Change device type of a switch

### URL

https://www.home-assistant.io/integrations/switch_as_x/

### Version

2022.7.7

**Comment by dannytsang** [comment]
It's missing *(helper)* but it's in my integrations list:
![image](https://user-images.githubusercontent.com/567982/182209488-d66f9477-ea89-4d19-b494-b3c813a42dea.png)

**Comment by frenck** [comment]
Its named differently under Helpers.

![CleanShot 2022-08-16 at 16 28 16](https://user-images.githubusercontent.com/195327/184905115-69fce318-4ca9-4eb0-a5ff-fb1d17d9b681.png)
