### ISSUE TITLE
Error message: cannot resolve Mac Adress

### ISSUE THREAD

**Issue by loec01** [home-assistant/home-assistant.github.io#23577]
### Feedback

Hi, 
I have a Java Minecraft server running in the cloud, and it works for gaming.
However, I cannot configure the HomeAssistant integration, I just keep an error message that the IP is invalid (can’t resolve MAC address). Actually, the error message is in German so it may be translated Differently…
Any ideas?
Thx
Tobias 

### URL

https://www.home-assistant.io/integrations/minecraft_server/

### Version

2022.7.7

**Comment by elmurato** [comment]
Moin Tobias 😉
Did you try to enter your host name and port (myserver.example.com:25565) instead of the IP address?

**Comment by frenck** [comment]
Hi there @loec01 👋 

It seems like you want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by loec01** [comment]
That worked!Gesendet mit der mobilen Mail AppAm 29.07.22 um 21:31 schrieb elmurato
                
            
            
                
                    Von: "elmurato" ***@***.***>Datum: 29. Juli 2022An: "home-assistant/home-assistant.io" ***@***.***>Cc: "Author" ***@***.***>,"loec01" ***@***.***>Betreff: Re: [home-assistant/home-assistant.io] Error message: cannot resolve Mac Adress (Issue #23577)
                
                

Moin Tobias 😉

Did you try to enter your host name and port (myserver.example.com:25565) instead of the IP address?
