### ISSUE TITLE
Intesishome Not appearing in integrations list?

### ISSUE THREAD

**Issue by Andrewpl007** [home-assistant/home-assistant.github.io#23585]
### Feedback

Its getting late and I'm setting a lot up so maybe my brain has broke.. but it seems this integration is not appearing when you search it and it also didn't detect the device on my wifi

### URL

https://www.home-assistant.io/integrations/intesishome/

### Version

2022.7.7

**Comment by frenck** [comment]
> but it seems this integration is not appearing when you search it and it also didn't detect the device on my wifi

That is correct, this integration is only available for manual configuration in YAML (as documented).

![CleanShot 2022-07-31 at 13 57 02](https://user-images.githubusercontent.com/195327/182025240-08d95762-f678-459e-97a7-690d58103252.png)

<https://www.home-assistant.io/integrations/intesishome#configuration>
