### ISSUE TITLE
Kinivo BTD-400 USB Bluetooth adapter

### ISSUE THREAD

**Issue by spry-salt** [home-assistant/home-assistant.github.io#23581]
### Feedback

Hi, I can't currently get this adapter to work. It's being recognised by the new Bluetooth integration but doesn't seem to see anything. In case this feedback is useful to you. Thank you.

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2022.8.0

**Comment by spry-salt** [comment]
It's working under Home Assistant 2022.8.0b6.

**Comment by dannytsang** [comment]
@frenck do we submit pull requests for these types of feedback as usual or is there some other (vetting/consensus?) process for compatible hardware?

**Comment by frenck** [comment]
@dannytsang sorry, missed that comment, noticed it now due to the closing notification.

We do accept such reports 👍
