### ISSUE TITLE
More information about Profile Switches needed

### ISSUE THREAD

**Issue by itspuia** [home-assistant/home-assistant.github.io#23590]
### Feedback

The original [FritzBoxTools HASS Plugin](https://github.com/mammuth/ha-fritzbox-tools) GitHub Page shows the option to switch Profiles. I can't find any information about this in the official Integration. 
The [switch.py file](https://github.com/home-assistant/core/blob/dev/homeassistant/components/fritz/switch.py#L485) shows information about profiles tho. I cannot change profiles unfortunately, since the entities do not show up in my Installation. Since there is no information about this in the Documentation, I would suggest to add that, if that feature is still included and working.
Thanks! :)

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2022.7.7

**Comment by chemelli74** [comment]
HI @itspuia, current implementation of the Fritz integration has a switch to enable or disable profile.
They are under the diagnostic category and disabled by default.

If you cannot find them, please open a bug report in the core repository.

Thx,

Simone

**Comment by itspuia** [comment]
Hello @chemelli74,
thank you for your reply. I have been searching there for a while and unfortunately I can't find it. I will open a bug report for this.

Thanks a lot for your support! :)
Puia

**Comment by mib1185** [comment]
the former HACS addon does also "only" provide switches to turn on or off the internet access/profil for a device.
So it is exactly the same behaviour.

If you still think, it is a missing feature, please don't hesitate to use the [feature request](https://community.home-assistant.io/c/feature-requests) section of our forum.


Thanks! 👍
