### ISSUE TITLE
Usage Example creates a HOME sensor which cannot be selected to use because of the already defined HOME zone sensor

### ISSUE THREAD

**Issue by StormyKnight17** [home-assistant/home-assistant.github.io#23597]
### Feedback

When trying to use the proximity sensor in an automation, when you type HOME & choose the proximity.home it reverts to HOME which is the HOME zone sensor.

The example should perhaps not use home: but perhaps home_proximity: to allow the proximity sensor to be selectable.
Same would go for WORK I think.

### URL

https://www.home-assistant.io/integrations/proximity/

**Comment by dannytsang** [comment]
Are you using a text editor to create the proximities and is it the text editor that is overriding the name?

**Comment by StormyKnight17** [comment]
No, I just enter it in as a trigger for example in an automation.

I type proximity & it autofills with Home & below it says home. proximity which is what I want.

The Home it uses is Home zone.
My guess is because they are both Home, it chooses the first one it comes across in the list it works through.

You can see that when you want to choose an attribute, it lists the zone attributes not the proximity attributes.

**Comment by dannytsang** [comment]
I see. You can also check it if you set the trigger up as per normal and then switch to the YAML view to verify it's selected the zone rather than proximity. Given what you have said, it sounds like a bug and I'm afraid you will need to raise an issue in https://github.com/home-assistant/core.

**Comment by StormyKnight17** [comment]
Ok, yes it sounds like a selection issue. I have summarized the steps to replicate. I will post in core.
 
Basically the documentation is defining a second friendly_name HOME
So we already have zone.home with friendly name "Home" (Capitalised)
With this documentation, we add proximity.home also with a friendly name "home" (lowercase)

When I type proximity into the Automation trigger under Entity for a state, 
I can select the item below which shows it's friendly name & full entity name

home
proximity.home

upon selection, the correct home is displayed, but when I click away, it is changed to "Home" & becomes the zone.home

Cheers
