### ISSUE TITLE
Improve documentation for service google.create_event to help with migration to new service

### ISSUE THREAD

**Issue by jane-t** [home-assistant/home-assistant.github.io#23608]
### Feedback

The fact it needs an entity_id in the data section is not mentioned.  As the older service called needed a calendar_id it is not immediately obvious what line is needed.

### URL

https://www.home-assistant.io/integrations/google/

### Version

2022.7.7

**Comment by frenck** [comment]
It doesn't require an entity ID?

**Comment by jane-t** [comment]
This works

```
service: google.create_event
data:
  entity_id: calendar.work_days
  summary: Working
  start_date_time: >-
    {{state_attr('input_datetime.set_working_day','timestamp')|
    timestamp_custom('%Y-%m-%d 09:00:00')}}
  end_date_time: >-
    {{state_attr('input_datetime.set_working_day','timestamp')|
    timestamp_custom('%Y-%m-%d 09:01:00')}}
```

The following errors stating a Device, Entity ID is required, which makes sense, but is not mentioned on the documentation,

```
service: google.create_event
data:
  summary: Working
  start_date_time: >-
    {{state_attr('input_datetime.set_working_day','timestamp')|
    timestamp_custom('%Y-%m-%d 09:00:00')}}
  end_date_time: >-
    {{state_attr('input_datetime.set_working_day','timestamp')|
    timestamp_custom('%Y-%m-%d 09:01:00')}}
```

**Comment by frenck** [comment]
It needs a target, you can also target an area or device directly, no need for entities IDs for that.

Please note, that putting entity_ids in the `data` section is considered "old-school" it still works, but we don't use such syntax anymore.

**Comment by jane-t** [comment]
Sorry,   I am not making myself clear,  the function is fine.  It was just I found the documentation unclear, as there was no mention in the documentation of needing to set a target and as I was working in YAML as the script used templates the visual editor was switched off.

I have adjusted my script to 

```
service: google.create_event
target:
  entity_id: calendar.work_days
data:
  summary: Working
  start_date_time: >-
    {{state_attr('input_datetime.set_working_day','timestamp')|
    timestamp_custom('%Y-%m-%d 09:00:00')}}
  end_date_time: >-
    {{state_attr('input_datetime.set_working_day','timestamp')|
    timestamp_custom('%Y-%m-%d 09:01:00')}}
```

**Comment by allenporter** [comment]
So maybe we want to include a link to https://www.home-assistant.io/docs/blueprint/selectors/#target-selector plus a full example to copy/paste?
