### ISSUE TITLE
Integrate power on blueprint

### ISSUE THREAD

**Issue by Garfius** [home-assistant/home-assistant.github.io#23600]
### Feedback

Just detect wether "wake_on_lan:" is already configured and offer the option.
MAC address is already easy to find in the menus.

Thank you.

Link to blueprint:
  https://gist.github.com/cvroque/6780ca0869ef781e9de3b506fd501f78#file-webostv_turn_on-yaml
Link to forum-related thread:
  https://community.home-assistant.io/t/lg-webos-smart-tv-enable-turn-on-action-for-ha-2022-2/388153

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2022.7.7

**Comment by thecode** [comment]
This repository is used for documentation issues, please create a feature request here: https://community.home-assistant.io/c/feature-requests/13
