### ISSUE TITLE
Missing in Glossary

### ISSUE THREAD

**Issue by helgiborg** [home-assistant/home-assistant.github.io#23616]
### Feedback

I find these things missing in the Glossary:
- Selectors
- Variables

### URL

https://www.home-assistant.io/docs/glossary/

### Version

2022.7.7

### Additional information

Thanks for the hard work!

**Comment by frenck** [comment]
Feel free to open up a PR to add they 👍 

../Frenck

**Comment by frenck** [comment]
Re-opening this for now, as I think the PR that resolved this issue is not fully correct.

**Comment by jbouwh** [comment]
> Re-opening this for now, as I think the PR that resolved this issue is not fully correct.

Okay, I tested it, and that looked okay.

**Comment by frenck** [comment]
It's not about testing it... it's about the content that is not correct.

Left review comments on #23719
