### ISSUE TITLE
Spotify Unsupported Devices

### ISSUE THREAD

**Issue by NeuzNL** [home-assistant/home-assistant.github.io#23618]
### Feedback

On the integration page of Spotify you tell Sonos is an unsupported device. But on the integration page of Sonos there is an example on how to integrate spotify into Hass and play on Sonos (see: [example 2 & 3](https://www.home-assistant.io/integrations/sonos/#playing-media)).

I use it myself and it works perfect. So please update Spotify integration page.

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2022.7.7

**Comment by frenck** [comment]
> I use it myself and it works perfect. So please update Spotify integration page.

That is a feature of the Sonos integration, not the Spotify integration.
The Spotify integration itself cannot control it, so the documentation is correct.

../Frenck

**Comment by NeuzNL** [comment]
@frenck 
Thanks for the fast response.

Clear story, thanks for explaining.
