### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by stephanvk10** [home-assistant/home-assistant.github.io#23623]
### Feedback

Navigate to APIs & Services (left sidebar) > [Credentials](https://console.cloud.google.com/apis/credentials)
Click on the field on the **right** of the screen, OAuth Consent Screen.

It should say on the left of the screen.

### URL

https://www.home-assistant.io/integrations/google/

### Version

2022.7.7

**Comment by pyrrolizin** [comment]
Hello @stephanvk10, thank you. PR incoming.
