### ISSUE TITLE
Error in install instructions?

### ISSUE THREAD

**Issue by cecat** [home-assistant/home-assistant.github.io#23628]
### Feedback

Hello!  

System Details: Fresh HA OS 8.4 (released 20220723) on a RPi 3).  Addons installed: (Studio Code Server, Terminal & SSH).  Integrations installed: (many auto-discovered/un_configured, only Supervisor, Meterorologisk Inst (Met.no), Radio Browser, RPI Power Supply Checker, and Sun are installed).

Issue: Following above instructions failed.  Add-on (Z-Wave JS) does NOT auto-install.  Must be installed before the integration.

Side note, "search for and select "Z-Wave" instruction is outdated, as the search results in two hits - "Z-Wave.Me" and "Z-Wave JS" - I selected the latter.)

This note is also incorrect: "Install the Z-Wave JS Server of your choice. If you run the supervisor and you’d like to run the standard add-on, you can skip this step if you want. The add-on is installed automatically for you when you choose so in the integration set-up. Remember to fill in the network key you’ve saved before."

Add-on install has two options - uncheck or leave checked "Use the Z-Wave JS Supervisor add-on." If left checked, error is "Failed to get Z-Wave JS add-on info."  If unchecked, a URL is requested and the default (ws://localhost:3000) results in "failed to connect."

Solution: "Option 1" of the "advanced instructions" (first install the add-on, then the integration) worked fine.

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2022.8.0

**Comment by MartinHjelmare** [comment]
We're aware of the issue and working on fixing it. Thanks!

**Comment by MartinHjelmare** [comment]
Core 2022.8.1 has a fix that makes the flow for setting up the integration with the add-on work again.

Supervisor 2022.08.1 has a fix that makes the flow work again in older Core versions.
