### ISSUE TITLE
Explain what 'discovery prefix' is

### ISSUE THREAD

**Issue by chris-hatton** [home-assistant/home-assistant.github.io#23638]
### Feedback

Doubtless this is _obvious_ to Home Assistant experts, but to fresh eyes (mine) the documentation's failure to explain what `<discovery_prefix>` should be is most frustrating, when all other elements in the string are explained.  A line such as 'this is `homeassistant` by default but can be customised' would sort it.

### URL

https://www.home-assistant.io/docs/mqtt/discovery/

### Version

2022.8.0

**Comment by frenck** [comment]
Its listed here: <https://www.home-assistant.io/docs/mqtt/discovery/#discovery_prefix>

It defaults to `homeassistant` as listed there and, because it's a config option, can be configured and thus customized.

../Frenck
