### ISSUE TITLE
Laird BT851 working

### ISSUE THREAD

**Issue by fwedler** [home-assistant/home-assistant.github.io#23644]
### Feedback

I can confirm that a USB Laird BT851 module (based on Cypress CYW20704 A2 chipset) is recognized and will find HomeKit devices.

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2022.8.0

### Additional information

https://www.lairdconnect.com/wireless-modules/bluetooth-modules/bluetooth-5-modules/bt850-series-bluetooth-module

**Comment by fwedler** [comment]
And since i have them on hand as well, it appears the Laird models 451-00003 and 451-00004 aka BL654 **do not** work.

https://www.lairdconnect.com/wireless-modules/bluetooth-modules/bluetooth-5-modules/bl654-series-bluetooth-module-nfc

**Comment by bdraco** [comment]
Here is the link to edit the page if you want to update the adapter list

https://github.com/home-assistant/home-assistant.io/edit/next/source/_integrations/bluetooth.markdown
