### ISSUE TITLE
Other Supported - Bluetooth Adapters

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#23653]
### Feedback

Is there any way to find out 'more specifics' on Bluetooth installations?  I have an INTEL NUC NUC5i5RYK and it appears that the BT is working (I guess - still not sure what I can do with this).  

![image](https://user-images.githubusercontent.com/100164602/182933702-59bce13e-a294-493f-84e1-362e9fffece3.png)

Its BT is built into the board - apparently and cannot be removed, only disabled in BIOS.  

I have an HP ThinClient with HASS OS as well - with a USB BT which also appears to be working (EDIMAX BT-8500).  I have another one also QGOO BT-502, and has shown promise. 

I'd like to help you add some of these to your supported list - if you let me know how I can help.  

![image](https://user-images.githubusercontent.com/100164602/182934256-effa968c-0795-4d4a-993c-e6245115d810.png)

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2022.8.0

**Comment by bdraco** [comment]
Here is the link to edit the page if you want to update the adapter list

https://github.com/home-assistant/home-assistant.io/edit/next/source/_integrations/bluetooth.markdown
