### ISSUE TITLE
Integraton with Arduino type boards?

### ISSUE THREAD

**Issue by JR51** [home-assistant/home-assistant.github.io#23651]
### Feedback

I am (obviously) a newbie here.   I was hoping to use Home Assistant with  Wemos or NodeMcu boards but don't find them in the Integrations list.   If they are compatible with Home Assistant, an explanation of how to connect them would be helpful.  

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2022.8.0

**Comment by frenck** [comment]
You might want to check out our sister project: ESPHome

<https://esphome.io>  ❤️ 

(Which integrates absolutely amazingly with Home Assistant btw).

../Frenck
