### ISSUE TITLE
Thank you so much!

### ISSUE THREAD

**Issue by jschinke1067** [home-assistant/home-assistant.github.io#23654]
### Feedback

Thank you very much for this great intergration! It was so easy to add all my 10 Sensors into HA with the new BLE Integration...
If the Battery Sensor also would come back it would be really highly appreciated!

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/

### Version

2022.8.0

**Comment by Jc2k** [comment]
Thanks!

Don't worry, I have MiFlora myself, so it's high up my list to get batteries working.

Cheers
