### ISSUE TITLE
Add Light Support

### ISSUE THREAD

**Issue by dleggen** [home-assistant/home-assistant.github.io#23669]
### Feedback

Could you possibly add support for the string lights like model H7010?

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2022.8.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
