### ISSUE TITLE
Link to bluez and dbus configuration instructions

### ISSUE THREAD

**Issue by LCMilstein** [home-assistant/home-assistant.github.io#23665]
### Feedback

I run Home Assistant Container in Docker on Synology NAS. This page states:

> Home Assistant Container: The host system must run BlueZ, and the D-Bus socket must be accessible to Home Assistant inside the container

No idea where to begin to understand how to run BlueZ on the host, nor how to figure out what the D-Bus socket is... and no, it's NOT a simple Google search to figure it out.

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2022.8.0

**Comment by frenck** [comment]
> No idea where to begin to understand how to run BlueZ on the host, nor how to figure out what the D-Bus socket is... and no, it's NOT a simple Google search to figure it out.

If you decide to manage your own system and containers, we expect you know what you are doing on that level. If not, we recommend looking at one of our other installation methods that might be a better fit for you.

We have no intention of writing system administration guides for every possible system out there.

Sorry!

../Frenck

**Comment by LCMilstein** [comment]
Totally appreciate that, and would never expect you to, but these are brand new concepts that aren't being used anywhere else in Home Assistant. Can you at least link to something that explains what these things are and where to start? 

Is BlueZ something we need to install like zwavejs? There's nothing to go on here. I don't think most people running Home Assistant will be familiar with these concepts.
