### ISSUE TITLE
Flu Near You documentation doesn't indicate the integration is deprecated

### ISSUE THREAD

**Issue by jsuelwald** [home-assistant/home-assistant.github.io#23661]
### Feedback

Home Assistant "Repair" wants to remove the integration, documentation does not mention any problems.

### URL

https://www.home-assistant.io/integrations/flunearyou/

### Version

2022.8.1

**Comment by jatgm1** [comment]
Oh I didn't see this before I made a thing on here saying basically the same thing. Data source not available or something.

**Comment by bachya** [comment]
The repair is correct. I'll work on a PR to remove the docs.
