### ISSUE TITLE
Not enough information on the command service

### ISSUE THREAD

**Issue by fantandrea** [home-assistant/home-assistant.github.io#23679]
### Feedback

I had some hard time to find information to create some simple automation (e.g. changing input source)

I was able to find the list of available commands but:
1. I found the `tv/getExternalInputList` command but I wasn't able to use it (I had to manually call it with a custom program)
2. I found the `tv/switchInput` command but I had to figure out by my self that the parameter name was `inputId` and what type of input the tv was expecting (`AV_1`, `COMP_1`, `HDMI_1`, `HDMI_2`, `HDMI_3`
3. I had to figure out by myself that the TV is not an input but an app and I can switch back to it with the command `system.launcher/open` and payload `id: com.webos.app.livetv`

All the above was possible by figuring out the used library was [aiowebostv](https://pypi.org/project/aiowebostv/) and doing some external test

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2022.8.1

**Comment by thecode** [comment]
You should not use the `command` for standard media player actions (**and in general should avoid using it unless you know what you are doing**), This is a low level control command and not all commands are supported by every device.

There is a build in HA service for changing sources:
![image](https://user-images.githubusercontent.com/1858925/183263120-029aae11-84cf-4bed-9d26-fe4d6fdb5553.png)

The integration already simply the sources so you don't need to know if something is an app or an input. 

These options are documented under the `media player` component as they are common to most media players:
https://www.home-assistant.io/integrations/media_player/

In general I suggest to first search for something in the developer tools as it makes it simple to know what is supported.

**Comment by fantandrea** [comment]
Thanks @thecode indeed it worked and has been much easier. I tried to look for something in the developer tools but only for your module, I didn't though about the device one. Thanks for your suggestion.
