### ISSUE TITLE
IP address of what?

### ISSUE THREAD

**Issue by SymmetricDesigns** [home-assistant/home-assistant.github.io#23676]
### Feedback

I'm being asked for an IP address.  Of what? Where do I find it?

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2022.8.1

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you want help with a setup, you should try our [Community Forum: Configuration](https://community.home-assistant.io/c/configuration/11).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
