### ISSUE TITLE
Icloud

### ISSUE THREAD

**Issue by Seifon** [home-assistant/home-assistant.github.io#23681]
### Feedback

我在中国

登录时总是提示：
Unknown error occurred

中国的配置文件地址应该是：

/usr/lib/python3.10/site-packages/pyicloud/base.py:188
```
AUTH_ENDPOINT = "https://idmsa.apple.com/appleauth/auth"       
HOME_ENDPOINT = "https://www.icloud.com.cn"             
SETUP_ENDPOINT = "https://setup.icloud.com.cn/setup/ws/1"
```

HA日志：

Source: components/icloud/config_flow.py:113
First occurred: 00:17:03 (4 occurrences)
Last logged: 00:22:09

Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request

Logger: pyicloud.base
Source: /usr/lib/python3.10/site-packages/pyicloud/base.py:188
First occurred: 00:16:59 (3 occurrences)
Last logged: 00:22:05

Authentication required for Account. (421)

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2022.8.1

**Comment by frenck** [comment]
Hi there @Seifon 👋 

It seems like you want to report a bug with an Home Assistant integration, however, you have submitted documentation feedback. Please submit an issue in our Core issue tracker instead. Additionally, you used a foreign language. We only accept reports that use the English language.

../Frenck
