### ISSUE TITLE
missing information for supervised installation

### ISSUE THREAD

**Issue by ceinmart** [home-assistant/home-assistant.github.io#23682]
### Feedback

Hi ,

I'm installing the Home Assistance , over a fresh new Debian . 
Folow the steps , all works ok , however after the end of the instalation, there is no mention how to access it! 
which url , which port... 

### URL

https://www.home-assistant.io/installation/linux/

### Version

2022.8.1

**Comment by frenck** [comment]
The supervised documentation should provide you with that information during setup.

The documentation offloads the installation procedure towards our Supervised installation. 

That said, honestly, if you have to ask... You might want to choose a different installation method. I don't mean this bad or mean though, but Supervised is the most complex installation type we have, which requires lots of knowledge about Linux system administration, Docker configuration and handling, and above all, knowledge about the architecture of the Home Assistant eco system.

I would only recommend it if you are more into Home Assistant and are absolutely sure what you are doing.

We currently have no intention on extending the Supervised installation documentation from the main documentation end.

../Frenck
