### ISSUE TITLE
integration: Follow instructions on the screen 

### ISSUE THREAD

**Issue by Bart56** [home-assistant/home-assistant.github.io#23685]
### Feedback

Hi,
After trying to integrate Shelly, it asks for "Host:" but it doesn't accept an ip address of the homeassistant server and there is no instruction as to what goes in there. It would help if this page contained a description and example of how to fill in the "host" field. 
The sentence on this page says to follow the on screen instructions but I can't make it past the first field. Hitting the "?" help icon brings me here which does not help me figure out what is expected.
Thanks.

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2022.8.1

### Additional information

I simply get a "Failed to connect" error no matter what I put in there. I tried an IP address, a url, a hostname, no luck.

**Comment by klaasnicolaas** [comment]
Host is the ip address of the shelly you want to connect to, not that of your HA instance.

**Comment by Bart56** [comment]
Thank you Klaas.
I have several Shelly's. How do I handle more than one?
Thanks
Bart

**Comment by klaasnicolaas** [comment]
You then repeat the same steps as you added the first shelly.

**Comment by Bart56** [comment]
Ok. Thanks for making that clearer for me. Should I try to edit the doc
page?

**Comment by klaasnicolaas** [comment]
I don't think it's necessary to adjust the documentation for that
