### ISSUE TITLE
Powering down unit, or rebooting it. 

### ISSUE THREAD

**Issue by simplyliving4** [home-assistant/home-assistant.github.io#23686]
### Feedback

I do not see how to turn off my Raspberry Pi 3b+ with HA running on it. I know powering off by pulling the plug is bad if unit is writing, but I suppose it would have other conditional effects too. But I cannot find the magic mix to shut it off or reboot it. It says system is not healthy? But I cannot find it. Might be a good idea to put startup and how to shut down upfront and first. So people can know how to without powering down hard. I will go back and check, forgive me if it is there. But I was cruising on 100 gallons of caffeine. Next thing I know I am here writing this, so there is that. I am learning too as fast a possible. Wait, I found it in a different location. SETTINGS, HARDWARE, RASPBERRY PI > UPPER 3DOT MENU HAS REBOOT, SHUT DOWN, AND ANOTHER BUT IT IS REBOOTING RIGHT NOW. Please update / insert / and provide this information for safe shut down. It is delayed, I turned my head and the script started running stopping everything. Took 4 minutes to shut down cold. Thanks, X-Alliance

### URL

https://www.home-assistant.io/dashboards/

### Version

2022.8.1

### Additional information

About to update, but was getting a System Unhealthy and it wouldn't do it.

**Comment by frenck** [comment]
Thank you for reaching out.

It sounds like you are of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
