### ISSUE TITLE
Extension Cable

### ISSUE THREAD

**Issue by rlust** [home-assistant/home-assistant.github.io#23680]
### Feedback

Please provide suggested extension cable suggestions.

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2022.8.1

**Comment by frenck** [comment]
The documentation already provides a suggestion to use an extension cable:

![CleanShot 2022-08-07 at 15 24 44](https://user-images.githubusercontent.com/195327/183292956-ab9ff0b9-974e-43b4-b325-ac0fd73e6fb6.png)


../Frenck
