### ISSUE TITLE
Link to be corrected

### ISSUE THREAD

**Issue by wip58** [home-assistant/home-assistant.github.io#23690]
### Feedback

Nothing so serious: the link for "variance" in NUMERIC SOURCE SENSOR part in the "Description" column is wrong , while should be this one: https://en.wikipedia.org/wiki/Variance 

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2022.8.1

### Additional information

<img width="790" alt="Screenshot 2022-08-07 at 11 45 41" src="https://user-images.githubusercontent.com/72023798/183285083-3cecb0ca-9075-4c48-8a22-ba3ef238ecdf.png">

**Comment by ThomDietrich** [comment]
Thanks @wip58,
will fix that with one of the next edits :)
