### ISSUE TITLE
Is this integration broken? I'm getting a failed to logon to gateway

### ISSUE THREAD

**Issue by gnvdude** [home-assistant/home-assistant.github.io#23704]
### Feedback

wanted to check in and see if there have been issues reported with this integration?

I've deleted and reinstalled but no go..still reports failed to logon to gateway 

started two updates ago with home assistant 

### URL

https://www.home-assistant.io/integrations/screenlogic/

### Version

2022.8.2

**Comment by frenck** [comment]
Hi there @gnvdude 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
