### ISSUE TITLE
sonoff zigbee2mqtt 

### ISSUE THREAD

**Issue by unchuck** [home-assistant/home-assistant.github.io#23700]
### Feedback

sonoff zigbee2mqtt  stop working after enable bluetooth, when disable bluetooth , zigbee start works fine.

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2022.8.2

**Comment by frenck** [comment]
Hi there @unchuck 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by unchuck** [comment]
sry, thx
