### ISSUE TITLE
Energy panel translation

### ISSUE THREAD

**Issue by asiviero76** [home-assistant/home-assistant.github.io#23707]
### Feedback

Dear All
on the energy panel, "solar total" are not translated in Italian, and I cant find it in the translation module... can you please add it in order to have "Totale Solare"?

### URL

https://www.home-assistant.io/getting-started/join-the-community/

### Version

2022.8.2

**Comment by frenck** [comment]
Hi there @asiviero76 👋 

You are not exactly in the right place, as you have submitted documentation feedback for the "Join the community" page 😄 

Anyways, you can find more information about helping out with translating Home Assistant here:

<https://developers.home-assistant.io/docs/translations>

Thanks for your contributions already! 👍 

../Frenck

**Comment by asiviero76** [comment]
Hello Franck

Sorry to post in the wrong place.

Anyway I can’t find the “Solar Total” string to translate…

How to find it?



Da: Franck Nijhof ***@***.***>
Data: martedì, 9 agosto 2022, 10:23
A: home-assistant/home-assistant.io ***@***.***>
Cc: asiviero76 ***@***.***>, Mention ***@***.***>
Oggetto: Re: [home-assistant/home-assistant.io] Energy panel translation (Issue #23707)

Hi there @asiviero76<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fasiviero76&data=05%7C01%7C%7C6d38de89c2294862d98308da79e07fab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637956302358109298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AKg3eJBTmJANPaediyIrPTptTWB6WLd2iyTRN4W7Z8I%3D&reserved=0> 👋

You are not exactly in the right place, as you have submitted documentation feedback for the "Join the community" page 😄

Anyways, you can find more information about helping out with translating Home Assistant here:

https://developers.home-assistant.io/docs/translations<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevelopers.home-assistant.io%2Fdocs%2Ftranslations&data=05%7C01%7C%7C6d38de89c2294862d98308da79e07fab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637956302358109298%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bpaZ9pagRPSnKxlPNgdKdXaKJVxnaBOcwwXEg%2BNKTLI%3D&reserved=0>

Thanks for your contributions already! 👍

../Frenck
