### ISSUE TITLE
Update needed

### ISSUE THREAD

**Issue by yds0yds** [home-assistant/home-assistant.github.io#23703]
### Feedback

Changes to opensky API limits I believe make this integration inoperable, if I understand the changes correctly.  Perhaps someone could add something to the description indicating this?

### URL

https://www.home-assistant.io/integrations/opensky/

### Version

2022.8.2

**Comment by frenck** [comment]
> Changes to opensky API limits I believe make this integration inoperable

Could you elaborate on that? Can you point me to (or share) a resource that provides that insight?

**Comment by yds0yds** [comment]
It's probably best described ( with links to opensky documentation) at the
known issue.

https://github.com/home-assistant/core/issues/74935

**Comment by frenck** [comment]
Right, so this is an issue with the integration at this point, not incorrect documentation.

Please keep track of that in the issue you linked instead.

../Frenck
