### ISSUE TITLE
Growatt no longer works after the latest Home Assistant update

### ISSUE THREAD

**Issue by rtrinks** [home-assistant/home-assistant.github.io#23705]
### Feedback

Growatt no longer works after the latest Home Assistant update

Growatt application is back to old server settings server.growatt.com when updating Home Assistant.
The correct settings are server-api.growatt.com
If you want to solve this you can run the following command in SSH

Go to:

Settings
Add-ons
Install SSH & Web Terminal

Open SSH terminal and run the following command:

sed -i 's/server.growatt.com/server-api.growatt.com/g' /config/.storage/core.config_entries

Restart your Home Assistant and Growatt is working again.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2022.8.2

**Comment by dannytsang** [comment]
Mine seems ok. I'm also on 2022.8.3.
![image](https://user-images.githubusercontent.com/567982/184030297-dcf056d1-2cdb-4867-b046-47279786de35.png)

**Comment by dannytsang** [comment]
@rtrinks I think you will need to raise this in the [Home Assistant Core repository](https://github.com/home-assistant/core) because this repository is for documentation.

Also your issue might be covered in [Growatt integration fail with 2022.8.2](https://github.com/home-assistant/core/issues/76451)

**Comment by dannytsang** [comment]
I take it back. I've switched to the server-api address and it's so much more reliable. Thanks @rtrinks

**Comment by JesperThorup** [comment]
The /config/.storage/core.config_entries folder does not seem to exist on my installation:

![image](https://user-images.githubusercontent.com/104192830/184628241-4ef33d6d-77ad-4af6-9806-64411049f143.png)

I have just upgraded to the 2022.8.4 version, and as the rest, the Growatt integration stopped working.

The sugested workaround does not seem to work, as the config file can't be found.

**Comment by JesperThorup** [comment]
I can confirm this change fixes the issue..

**Comment by woolf0007** [comment]
i cant find "server.growatt.com" line in my core.config_entries
i only have this:
      {
        "entry_id": "******",
        "version": 1,
        "domain": "growatt_server",
        "title": "*******",
        "data": {
          "platform": "growatt_server",
          "username": "*******",
          "password": "********",
          "plant_id": "*******",
          "name": "********"
        },
is any idea what can i change in this?

**Comment by dannytsang** [comment]
@woolf0007 not sure about changing it. Maybe make a backup and try changing it to see if it works.

For reference this is what mine looks like:
```
{
        "entry_id": "abc123",
        "version": 1,
        "domain": "growatt_server",
        "title": "Growatt Hybrid",
        "data": {
          "username": "danny",
          "password": "password",
          "url": "https://server-api.growatt.com/",
          "plant_id": "1",
          "name": "Growatt Hybrid"
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "1407311",
        "disabled_by": null
},

**Comment by woolf0007** [comment]
thx , i will try

**Comment by woolf0007** [comment]
looks like it works, thanks for the help
(I had to delete this line: "platform": "growatt_server", and enter the"url": "https://server-api.growatt.com/")

**Comment by rtrinks** [comment]
> 

Have you installed the Growatt integration?

**Comment by woolf0007** [comment]
Yes, 2 years ago...😀

**Comment by muppet3000** [comment]
See here: https://github.com/home-assistant/core/issues/76453
More importantly my comment here: https://github.com/home-assistant/core/issues/76453#issuecomment-1216203161
