### ISSUE TITLE
Not existing integration anymore

### ISSUE THREAD

**Issue by Ludn** [home-assistant/home-assistant.github.io#23711]
### Feedback

From the list, search and select “Xiaomi BLE”, 
Does not exist
Ideas?

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/

### Version

2022.8.2

**Comment by Jc2k** [comment]
Hi! This is where problems with the documentation (https://www.home-assistant.io/integrations/xiaomi_ble/) are tracked. This doesn't sound like a problem with the documentation, but like a problem with your installation.

You might have more luck here: https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml

**Comment by Ludn** [comment]
Hmm, quite functional, this is what i get
<img width="524" alt="PNG-Bild" src="https://user-images.githubusercontent.com/11378494/183688897-920d13a5-a1ce-4fa5-97fc-47ffab6ce46d.png">

**Comment by Jc2k** [comment]
Dies ist der falsche Ort, um dieses Problem zu melden. Es tut mir leid, dass ich dir nicht helfen kann.

https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml
