### ISSUE TITLE
Missing documentation related to configuring individual devices

### ISSUE THREAD

**Issue by Staggeble** [home-assistant/home-assistant.github.io#23717]
### Feedback

Hi HA,

I am trying to integrate a current sensor (made with a CT clamp and a wemos D1 mini) in the energy tab to see the energy consumption of my heat-pump. Integrating power plugs works very well, but integrating a home build solution is a pain in the ass. I already made a topic in the HA facebook group, I read a lot of topics on the HA community side, but still I am not able to get the configuration right. Could you support by improving the documentation? I would like to now what the "device_class", "state_class", "last_reset" yes/no, ... should be to get my device in the energy tab.

Kind regards,
Berten

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2022.8.3

**Comment by homeassistant** [comment]
Hey there @home-assistant/core, mind taking a look at this feedback as it has been labeled with an integration (`energy`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L172) for? Thanks!
