### ISSUE TITLE
Suggest a section for docker install on raspberry pi

### ISSUE THREAD

**Issue by braddo99** [home-assistant/home-assistant.github.io#2371]
There are directions to run home-assistant on raspberry pi, and to run on docker, but not on raspberry pi and docker :-)

If you run the linux example, it downloads the image properly and builds the container, but the image isn't compatible with ARM

I think it's just a matter of changing the docker repo image name in your example. Haven't myself picked one to try but there are several that look promising e.g.

homeassistant/rpi2-home-assistant

**Comment by Landrash** [comment]
Resolved with https://home-assistant.io/blog/2017/07/25/introducing-hassio/ :champagne:
