### ISSUE TITLE
Can the need to configure sensors in app before entities appear in HA be made explicit in the docs?

### ISSUE THREAD

**Issue by bifurcated** [home-assistant/home-assistant.github.io#23712]
### Feedback

Hi,

According to [this issue](https://github.com/home-assistant/core/issues/76517), it is necessary to configure SensorPush sensors in the app before entities will appear in HA.  That's perfectly fine, but think it may help others to have the documentation reflect this dependency.  LOVE this integration, and am very grateful to you for developing it.  Thanks.

### URL

https://www.home-assistant.io/integrations/sensorpush/

### Version

2022.8.2

**Comment by bdraco** [comment]
Here is the link to edit the docs

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/sensorpush.markdown
