### ISSUE TITLE
Area card should let entity be ignored if irrelevant

### ISSUE THREAD

**Issue by esenterre** [home-assistant/home-assistant.github.io#23713]
### Feedback

I really love Area Cards! 
However sometimes, it's missing some customization. 

For example in my office I have no temperature sensor per se, but I have an OctoPrint server for my 3D printer. 
So the area card reports 104C. (I don't even know if that temp comes from my 3D Printer for sure (it's more at 200C)). Anyhow, that number is, of course, not true or not the temperature of the "Area". 

I also saw a switch that was shown on the card, but it was a "switch" inside Frigate to enable/disable recordings (or the like). Not an actual switch. While the real switch was not available. (But that one seems to be fixed).

I don't know how this could be implemented. I imagine a list of ignored entities maybe. Or the other way around force an entity for a specific Button type (Switch/Fan/Light/Temperature/Humidity/etc.). If set to none, nothing shows up. 

### URL

https://www.home-assistant.io/dashboards/area/

### Version

2022.8.2

### Additional information

![image](https://user-images.githubusercontent.com/1243447/183749286-dee8cf4b-390c-4182-aa83-86287c6a5e4f.png)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
