### ISSUE TITLE
Can’t connect to a FRITZ!Box with changed IP

### ISSUE THREAD

**Issue by gimmel** [home-assistant/home-assistant.github.io#23729]
### Feedback

I had to to change my whole network to get more IP adresses. So all device have new IP addresses now.
All the FRITZ!Box Integrations want to be reconfigured now, but I only can change username and password. I can’t change the IP address. And I can’t delete the integration to try a new auto detect.

Is it possible to edit the config files directly? Where can I find them?

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2022.8.3

### Additional information

<img width="357" alt="Bildschirmfoto 2022-08-11 um 14 12 36" src="https://user-images.githubusercontent.com/135626/184130756-60d2c5ed-e5e0-44e9-8fe2-aeb53f8ea1c1.png">

**Comment by mib1185** [comment]
HI @gimmel 
just to be sure - your screenshot shows a re-configuration box for the [AVM FRITZ!Smarthome](https://www.home-assistant.io/integrations/fritzbox) integration, but you mentioned the [AVM FRITZ!Tools](https://www.home-assistant.io/integrations/fritz) on your initial post. So do you have this issue with both integrations or only with the AVM FRITZ!Smarthome?
