### ISSUE TITLE
inputing time from other entities

### ISSUE THREAD

**Issue by newbuilder22** [home-assistant/home-assistant.github.io#23726]
### Feedback

It would be useful to give advice on how to input time from say an entitie colled number.xxxx.yyyy 

### URL

https://www.home-assistant.io/integrations/input_datetime/

### Version

2022.8.3

**Comment by frenck** [comment]
> It would be useful to give advice on how to input time from say an entitie colled number.xxxx.yyyy

That isn't related? `number` entities do not represent time.

../Frenck

**Comment by newbuilder22** [comment]
My inverter inputs unix time as number identity so how can I convert this to time?
