### ISSUE TITLE
transmission

### ISSUE THREAD

**Issue by kyme32** [home-assistant/home-assistant.github.io#23747]
### Feedback

I didn't saw the posibility to get the stats, is there a way?i mean total upload/download size, current run up/down and all the details from stats?
It would be really nice to have the posibility to check this out

### URL

https://www.home-assistant.io/integrations/transmission/

### Version

2022.8.4

**Comment by engrbm87** [comment]
I think you opened the issue in the wrong repo as this is for documentation. Correct repo is https://github.com/home-assistant/core.
This will be available once [this PR ](https://github.com/home-assistant/core/pull/74438) is merged.

**Comment by frenck** [comment]
Closing this ticket as it doesn't contain documentation feedback.
