### ISSUE TITLE
Median option for MiFlora

### ISSUE THREAD

**Issue by einarijunter** [home-assistant/home-assistant.github.io#23744]
### Feedback

Hey, awesome work with getting the integration up and running!

One option that used to exist in the old version was setting a median value to smooth out the sensor measures. Suffering from some spikey behavior on some of my MiFlora sensors and was wondering if similar functionality could be added also directly into this new integration, without the need of me doing this somehow manually outside it 😊

Thanks! 

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/

### Version

2022.8.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
