### ISSUE TITLE
What is Host*

### ISSUE THREAD

**Issue by KevinKTM** [home-assistant/home-assistant.github.io#23748]
### Feedback

Could we clarify what Host* is on installation. Is this the ip of my tv and what format is expected?

### URL

https://www.home-assistant.io/integrations/nfandroidtv/

### Version

2022.8.4

**Comment by tkdrob** [comment]
Host is any IP address, computer name, or even an FQDN. IP address is easiest but is not covered or supported here. Set a static one in your router for the device.

**Comment by KevinKTM** [comment]
For my tv right? My tv is at 192.168.1.106 but this doesn't work

**Comment by tkdrob** [comment]
When you only say it doesn't work, I can't help you much. Have you followed the instructions in the docs? The app needs to be installed first. If you are using a fire stick, you want the IP of the firestick, not the TV.

**Comment by KevinKTM** [comment]
Was getting a couldn't connect error. Changed to static ip and it worked. Worth tweaking the docs to clarify what host is for the noobs out there as its not actually stated anywhere.
All good! Thanks, this is awesome.

**Comment by tkdrob** [comment]
It could be done but that still requires some under the hood work in the user's router. DHCP auto discovery was on my list of things to get done to make it an easier process with automatic IP updates, no static needed. It got shot down bc we don't want to be advertising a third-party app for every single fire stick out there. So this is the best we have.
