### ISSUE TITLE
Device tracking fails to reload after UniFi controller update

### ISSUE THREAD

**Issue by tjkcc** [home-assistant/home-assistant.github.io#23745]
### Feedback

Hey. I have UniFi controller running in docker while HA is running separately on a VM on my NAS.
The UniFi controller's container gets updated automatically with Watchtower and I noticed that when it happens HA loses device presence tracking. All I need to do to fix it is to reload UniFi integration. Is there a way to overcome this?

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2022.8.3

**Comment by frenck** [comment]
Hi there @tjkcc 👋 

It sounds like you are trying to report a bug, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
