### ISSUE TITLE
Remove https://www.home-assistant.io/integrations/ecovacs/

### ISSUE THREAD

**Issue by MeanderingWanderer** [home-assistant/home-assistant.github.io#23742]
### Feedback

Abandoned integration, no longer working/updated.   
Should be removed, error returned by HA: Component error: ecovacs - Exception importing homeassistant.components.ecovacs
Other forks are available.

From git page: (https://github.com/wpietri/sucks)
As of March 2020, this is no longer an active project. My Ecovacs robot died and has since been replaced with a Roomba. That means I can't see if code changes work, so I can't even usefully approve patches. As of yet, nobody has agreed to take it over. If you are interested in doing so, please join the [mailing list](https://groups.google.com/forum/#!forum/sucks-users) and discuss it there.

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2022.8.3

**Comment by frenck** [comment]
Please follow: https://github.com/home-assistant/core/issues/74564

If that issue is resolved by removing the integration, it will remove the documentation too.

../Frenck
