### ISSUE TITLE
sqlalchemy missing in dependencies 

### ISSUE THREAD

**Issue by TobiasDassler** [home-assistant/home-assistant.github.io#23741]
### Feedback

I installed Home Assistant Core in an Python venv on ubunutu. 
When running hass I get 'ModuleNotFoundError: No module named 'sqlalchemy''

The easy fix is to `pip install sqlalchemy` .

This should be fixed ideally fixed in the pip package but could for now also be added to the documentation.

### URL

https://www.home-assistant.io/installation/linux#install-home-assistant-core

### Version

2022.8.3

**Comment by TobiasDassler** [comment]
I also needed to `pip install fnvhash` to get it finally running.

**Comment by JimmyHoke** [comment]
I had this exact same issue.

Installing sqlalchemy and fnvhash fixed it.

**Comment by GrandMoff100** [comment]
Had the same thing happen today to me too.


Installing sqlalchemy and fnvhash also fixed it for me.

**Comment by ocalvo** [comment]
These components are missing from [requiriments.txt](https://github.com/home-assistant/core/blob/dev/requirements.txt)

**Comment by frenck** [comment]
This was an issue, that has been fixed in the latest stable releases of Home Assistant.
