### ISSUE TITLE
No section called "system health"

### ISSUE THREAD

**Issue by buteomont** [home-assistant/home-assistant.github.io#23756]
### Feedback

The documentation at https://www.home-assistant.io/docs/configuration/ states:
_**The path to your configuration directory can be found in the Home Assistant frontend by going to Settings > System > System Health**_
but I can find no section called _System Health_.

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2022.8.4

**Comment by klaasnicolaas** [comment]
This has now been moved to `Settings -> System -> Repairs -> 3 dots -> System Information`, so this is something that needs to be adjusted.
