### ISSUE TITLE
Sort automations in folders

### ISSUE THREAD

**Issue by Shogun1978** [home-assistant/home-assistant.github.io#23759]
### Feedback

I use a lot of automations around the house. To keep an overview, I start group automations with numbers or descriptions followed by a - to separate them and create some kind of a structure.

It would be great to sort the automations in the UI into different folders.

### URL

https://www.home-assistant.io/docs/automation/editor/

### Version

2022.8.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
