### ISSUE TITLE
Feature Request status light switch for Synology 

### ISSUE THREAD

**Issue by linwanxiaoyehua** [home-assistant/home-assistant.github.io#23758]
### Feedback

Is there any chance you can add Synology and status and power light switch, I usually don’t notice them at all, but when I try to watch a dark film with all room lights off, those Synology lights kind of distract 

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2022.8.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
