### ISSUE TITLE
wrong efibootmgr command

### ISSUE THREAD

**Issue by erolcum** [home-assistant/home-assistant.github.io#23752]
### Feedback

commad in this page is wrong, correct one is : 
`sudo efibootmgr --create --disk=/dev/sda --part=1 --label="HAOS" --loader='EFI\BOOT\bootx64.efi'`
for the efi file path, there should be single quotes..

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2022.8.4

### Additional information

is there a solution about overlay folders that occupy hdd incredibly ?

**Comment by erolcum** [comment]
I wrote an article about installation to pc in turkish here : https://akademi.robolinkmarket.com/home-assistant-pc-kurulumu/

I also saw issue below on my pc. is there a solution about ?
https://community.home-assistant.io/t/hassio-docker-overlay2-folder-consuming-all-disk-space/174278/11

**Comment by agners** [comment]
@erolcum I see, other documentation pages about `efibootmgr` use single quote too. I guess single quote avoids \ to be interpreted as an escape sequence.

**Comment by erolcum** [comment]
Yes you are right @agners
