### ISSUE TITLE
Category component pages are missing from components list

### ISSUE THREAD

**Issue by bdurrer** [home-assistant/home-assistant.github.io#2376]
Component/category pages like [Binary sensor](https://home-assistant.io/components/binary_sensor/) or [Camera](https://home-assistant.io/components/camera/) are excluded from filters and search on the components overview.

What's the reason behind this? Is it on purpose?

Some of those pages hold valuable information and are an useful starting point for exploring an category.

* Is there a reason that those pages do not have the ha_category set?
* Why exclude them from their own category filter?
* Shouldn't we at least include them in the search results?

I could change all three things, but advice is appreciated.

@balloob and @robbiet480 seem to have worked on that page before, so you might be able to provide input

**Comment by fabaff** [comment]
> Is there a reason that those pages do not have the ha_category set?

That they don't show up. I don't really recall why we made those pages but now some contains further details.

> Why exclude them from their own category filter?

Because not all every component overview is useful.

> Shouldn't we at least include them in the search results?

I don't think that's needed. Those overview pages are linked from every platform page.

**Comment by balloob** [comment]
Yeah I agree with Fabaff here. Most of the times they are pretty useless. I guess they can be helpful to explain the services offered maybe?

**Comment by MartinHjelmare** [comment]
I would like to have them more visible. At least some of them hold useful and today they are hard to find.

**Comment by bdurrer** [comment]
Provocative statement: the top nav menu "components" is a misnomer, it should be "platforms".
Which leads my to the question: Where the heck is the list of components?

That mix of component and platform bugs me. They are not clearly separated (in the docs, from a readers perspective). 
- If it's important to have separate: there should be a separate page for both platforms and components (and someone shall explain the difference to me), 
- If it's not: the docs should uniformly use the same word for both of them.

The binary sensor page explains 90% of what you need to know about any binary sensor, but it's hidden and you cannot find it on the component overview.
TTS and Climate are very useful pages too, but until 5 seconds ago I didn't even know about them.

How about adding a page similar to the [Demo component](https://home-assistant.io/components/demo/) page, which lists all those categories (which actually are components)?

**Comment by balloob** [comment]
So the issue here is that there are different types of components:

 - A component can offer an abstraction of a type, for example Climate, Light, Switch. These components will offer an abstracted version that is implemented by platforms. For example `light.tradfri` or `light.hue`. Platforms do not interact directly with Home Assistant but only implement the abstraction offered by their component.
 - A component can also be for automation triggers or to offer actions inside Home Assistant. Examples are `notify`, `automation`, `script`, `scene`, `tts`, `device_sun_light_triggger`. Note that some automation components still have the notion of platforms, like `tts`, which offers different providers.

Probably a good start would be to separate between integration component and automation components.

**Comment by balloob** [comment]
More info on the difference in the docs btw https://home-assistant.io/developers/architecture_components/

**Comment by bdurrer** [comment]
I shouldn't think about such stuff so early in the morning 😁 You are right of course, the mix just does not feel ... clean to me. However I like the fact that the component search kinda lists anything I need, so mixing everything into one page is useful.

My initial point still stands though. I don't see why those abstract components, which build the core of all the components, are totally invisible, while a few dozen [e.g. all binary sensors] platform pages are just marker pages (eg homematic binary sensor). Maybe it's just a layout thing, the platform link is not all too obvious to me (I overlooked it for ages because my brain automatically registered it as "nav sidebar, not relevant for current page").

**Comment by balloob** [comment]
We're all open for it if you can come up with an improvement.

**Comment by DubhAd** [comment]
Appreciate this is a slightly old one, but _some_ of these contain useful, if not critical, information, and that having the link "hidden" in the sidebar makes them easy to overlook. Good examples of these would be the light component and the media player component. This makes it harder for people new to the platform to understand how to use it.

While the correct approach may well be to re-work the documentation, until that happens can these please be shown again.

**Comment by bdurrer** [comment]
I see three solutions for this issue:

1. add a category to the pages, that actually are useful (e.g. the Binary Sensor page).
1. Apply a tag to the useful ones and use it in the exclusion filter. This could work well with an improved searchbox #2310
1. close the issue

**Comment by tinloaf** [comment]
With the risk of being late to the party: I think that some (at least the climate) component pages contain important information for developers implementing a platform for that component. If you implement such a thing, a clear reference of how which service should behave etc. is useful.

So maybe we should put a link to all the component documentation pages in the Developers section?
