### ISSUE TITLE
And where do I start?

### ISSUE THREAD

**Issue by ManfredBartz** [home-assistant/home-assistant.github.io#23763]
### Feedback

Nice to kown that zone detection **can** be done.  But **how**?
So now I have to go back to Google to find a tutorial or howto.

### URL

https://www.home-assistant.io/getting-started/presence-detection/

### Version

2022.8.4

**Comment by dannytsang** [comment]
Does this page help? https://www.home-assistant.io/integrations/zone/

**Comment by ManfredBartz** [comment]
Thanks for your help, manual zone definition and especially the home zone
override is good info.

Here is a screenshot of entity "" history.
[image: Screenshot from 2022-08-17 09-22-21.png]
The Geocoded location* is correct *and inside the home zone.
In "config/person", I am linked with tracking device "Pixel 3 M Manfred".
The person dialog does not show any "entity" information so I cannot check
if there is some mismatch somewhere.
However, "Pixel 3 M Manfred" location is "unknown" and entity
"person.manfred_bartz" location is "unknown".
Nothing is intuitive about all this.

Best regards,
--
Manfred

**Comment by dannytsang** [comment]
I can look to add a link from the getting started page you have provided to the zone integration so others can go there for more details.

I'm afraid I can't see your screenshot so could you try uploading again please?
