### ISSUE TITLE
Motion Blinds Integration - ScreenAway Blinds  also compatible 

### ISSUE THREAD

**Issue by Goatlips** [home-assistant/home-assistant.github.io#23770]
### Feedback

I have recently integrated into home assistant blinds manufactured by ScreenAway Blinds Australia using the motion blinds integration.  It was a very easy installation as I had determined thru lots of research and contacting the company directly that they used dooya motors in the manufacture.

Hopefuuly you can add this manufacturer to the list to save the next guy the struggle.

Manufacturer Website - www.screenaway.com.au 

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2022.8.4

**Comment by starkillerOG** [comment]
@Goatlips thanks for reporting the working brand.
I have added it to the list of working brands in HomeAssistant and the upstream library.
See PR: https://github.com/home-assistant/home-assistant.io/pull/23814

If you appreciate the motionblinds integration, please consider sponsering the integration: https://github.com/sponsors/starkillerOG
