### ISSUE TITLE
Wrong link to backups

### ISSUE THREAD

**Issue by ahutchinson** [home-assistant/home-assistant.github.io#23798]
### Feedback

The link to backups no longer works.  It is now found in Supervisor -> Backups Tab (http://homeassistant.local:8123/hassio/backups).  Please update the doc.  Thanks

### URL

https://www.home-assistant.io/more-info/free-space/

### Version

2022.8.5

**Comment by dannytsang** [comment]
Are you referring to this link?
![image](https://user-images.githubusercontent.com/567982/185234367-87bfa9d8-e48b-45dd-9eaf-61d3854c17a4.png)

**Comment by ahutchinson** [comment]
Yes, that is it.  That link does not work, nor is there any menu structure
like that.

**Comment by dannytsang** [comment]
I can't seem to replicate the issue. The link takes me to the backup page and the navigation on my install is correct

![image](https://user-images.githubusercontent.com/567982/185243722-baf0160d-4f5c-4e0c-a418-65aa620cda7c.png)

**Comment by frenck** [comment]
Check the links and paths as well, they are correct and match the latest version of Home Assistant.

Please make sure you are running the latest version of Home Assistant, as the documentation always provides information matching our latest stable version.

../Frenck
