### ISSUE TITLE
P1 Monitor Configuration

### ISSUE THREAD

**Issue by WimGo** [home-assistant/home-assistant.github.io#23793]
### Feedback

The "P1 Monitor" Integration Configuration setup requests a Name and a Host. But I miss clear details for these two fields.
I image Name can be any name I think of for this monitor.
But it's not clear to me what Host should refer to. I tried the IP address of my Home Assistant as well as the IP address of the SlimmeMeter. But both failed. So I would request instructions for both fields and perhaps, preconditions for the installation to succeed.
![Screenshot 2022-08-17 130902](https://user-images.githubusercontent.com/84475561/185104355-1094baa3-faec-467a-8a0c-f56355a22d3f.png)

### URL

https://www.home-assistant.io/integrations/p1_monitor#smartmeter

### Version

2022.8.3

**Comment by frenck** [comment]
>  image Name can be any name I think of for this monitor.

Name is any name your like, however, we generally don't ask for that and assume a default name (that can be changed from the UI later on).

@klaasnicolaas You might want to consider removing that field from the configuration flows.

>  tried the IP address of my Home Assistant as well as the IP address of the SlimmeMeter. But both failed

It's the IP address or hostname (generally referred to as "host") of the P1 monitor. As this integration integrates the P1 monitor with Home Assistant (as any integration in Home Assistant integrate other devices or services with Home Assistant).

**Comment by WimGo** [comment]
Thanks for answering, @frenck . I understand I wasn't on the right track. I need to read up on P1 Monitor itself before continuing with its integration with Home Assistant.

**Comment by klaasnicolaas** [comment]
@frenck Seems like a good plan to omit the name value in the config_flow, would also like to see if we could add something of auto discovery 😄
