### ISSUE TITLE
with new solaredge-firmware it works again

### ISSUE THREAD

**Issue by Harald-P** [home-assistant/home-assistant.github.io#23803]
### Feedback

Hi,

on my SE5000H-inverter i had the same problem, that after a automatic firmware update modbus TCP over Wifi don't works anymore.
I contacted the solaredge support and they started an other firmware update to version 4.16.19 and now it works again.

On the firmware update page solaredge writes in the release notes:

Modbus TCP over secured Wi-Fi is now officially supported for residential inverters

-     Modbus TCP over unsecured Wi-Fi is blocked
-     Modbus TCP over Wi-Fi for commercial inverters is blocked
-     Note: Modbus TCP over Ethernet and Modbus TCP over RS485 for all inverters are supported

### URL

https://www.home-assistant.io/integrations/solaredge_local/

### Version

2022.8.5

**Comment by scheric** [comment]
Hello,
This integration uses protobuf. 
Are you sure you are talking about Modbus TCP or local protobuf.
More info why the protobuf does not work is here: https://github.com/home-assistant/core/issues/73215 

This is the SolarEdge Modbus TCP: https://github.com/binsentsu/home-assistant-solaredge-modbus

**Comment by Harald-P** [comment]
yes, i am talking about modbus TCP over Wifi.
