### ISSUE TITLE
What does the rhasspy integration do?

### ISSUE THREAD

**Issue by renarena** [home-assistant/home-assistant.github.io#23816]
### Feedback

I already use the rhasspy addon, 
I am not sure, what exactly the integration is about.
Predefined sentences? But they are in rhasspy junior?

### URL

https://www.home-assistant.io/integrations/rhasspy/

### Version

2022.8.6

**Comment by balloob** [comment]
Rhasspy integration makes sure the intent integration is set up, which is used by the Rhasspy (Junior) add-on.
