### ISSUE TITLE
energy in home assisant

### ISSUE THREAD

**Issue by 66schoollane** [home-assistant/home-assistant.github.io#23823]
### Feedback

hi guys
could you add another device to the dashboard
solar divert to immersion 
solar divert to ev car

thanks

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2022.8.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
