### ISSUE TITLE
Hive time period glitch

### ISSUE THREAD

**Issue by doctorphilt** [home-assistant/home-assistant.github.io#23821]
### Feedback

Thank you for this integration with Hive. I just wish to mention one issue I have come across which is preventing me completing an automation (I try to always use the GUI). If I "call service" for Hive: Boost Hot Water with entity ID as Hive water heater then I am only offered "time period" as a time of day rather than a time period e.g. 01.00hrs rather 1 hour. Is there something I'm not understanding or is this a bug. Many thanks, Phil, Cheshire, UK.

### URL

https://www.home-assistant.io/integrations/hive/

### Version

2022.8.6

### Additional information

alias: Hive water boost dependent on temperature and solar
description: ""
trigger:
  - platform: time
    at: "05:00:00"
condition:
  - condition: numeric_state
    entity_id: sensor.total_solar_energy_forecast_today
    below: "10"
  - condition: numeric_state
    entity_id: sensor.water_base_temperature
    below: "34"
action:
  - service: hive.boost_hot_water
    data:
      time_period: "05:01:00"
      on_off: "on"
      entity_id: water_heater.hive_stat
mode: single

**Comment by KJonline** [comment]
@doctorphilt time period is the amount of time you want the boost to last for?

see here in the docs https://www.home-assistant.io/integrations/hive/

**Comment by doctorphilt** [comment]
Yes it is, e.g. 01:00:00

**Comment by doctorphilt** [comment]
It looks like the problem is with the GUI.

It offers you a.m. or p.m. whereas when you look in yaml it appears as just a standard time period.

Maybe this happens throughout Home Assistant and, being new to it, I have not realised that… ??

**Comment by KJonline** [comment]
@doctorphilt 

ok this is strange I don’t have hot water so I cannot exactly see what you are seeing but when I look at the gui for boosting the heating, time period isn’t offering am/pm just the hh:mm:ss

![1022075B-13F0-4AD8-A007-F6843BA80355](https://user-images.githubusercontent.com/29937485/185783396-4b72f987-794f-43df-99e0-c38bc24656a9.png)

**Comment by doctorphilt** [comment]
Yes it is! Maybe it will work fine if I just take it as what yaml says?? I'll test it over next week or so...![image](https://user-images.githubusercontent.com/105046333/185785163-26496fcd-7206-4999-819b-96c68e78ad26.png)
