### ISSUE TITLE
Is there a way to configure Switcher to show consumption on the Energy dashboard

### ISSUE THREAD

**Issue by itaipreisv2** [home-assistant/home-assistant.github.io#23820]
### Feedback

While trying to add the device. it is missing.
This is the link to what needs to be added:
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

### URL

https://www.home-assistant.io/integrations/switcher_kis/

### Version

2022.8.6

**Comment by thecode** [comment]
Switcher devices doesn't report Energy, they report power. You can read about it and a solution how to make an energy sensor here: https://github.com/home-assistant/core/issues/54627#issuecomment-914367709

Please note that this repository is used only for documentation issues.
