### ISSUE TITLE
Integration fails

### ISSUE THREAD

**Issue by ktpx** [home-assistant/home-assistant.github.io#23838]
### Feedback

The Alpha Vantage API call now seems to be premium only for this use, the documenation should reflect that.

### URL

https://www.home-assistant.io/integrations/alpha_vantage/

### Version

2022.8.6

**Comment by frenck** [comment]
Could you point me to a resource that describes this?

**Comment by ktpx** [comment]
https://www.alphavantage.co/documentation/

The exchange calls are flagged Premium

The integration fails now without it.
