### ISSUE TITLE
How to add Gas

### ISSUE THREAD

**Issue by knarfje** [home-assistant/home-assistant.github.io#23833]
### Feedback

You state; Note that by default, the gas consumption entities are disabled, so if you want to use them, you need to enable them manually.
But can you please explain how to accomplish that?

### URL

https://www.home-assistant.io/integrations/p1_monitor/

### Version

2022.8.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

In general, you are more likely to get the answer you are looking for in those places.

That said: If you go the device page, you will be presented by all entities provided by your device (including disabled & hidden entities). By clicking on any entity in Home Assistant, you can configure for them to be enabled, hidden, or disabled.

../Frenck
