### ISSUE TITLE
How to sensor if the current washing programe of my dish washer is finished?

### ISSUE THREAD

**Issue by JulianPSLearner** [home-assistant/home-assistant.github.io#23837]
### Feedback

HI guys,

Iam searching for an switch or entity change, to know when my dishwasher is finished to trigger certain actions.
But there seems no entity that says "Program finished".

Am i missing something?

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2022.8.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
