### ISSUE TITLE
Thank you! Additional device request.

### ISSUE THREAD

**Issue by AntBurdin** [home-assistant/home-assistant.github.io#23841]
### Feedback

Thank you!
It was easy to set up. It picked up all of my MI Home BLE devices.
It was difficult to identify devises, however with the help of https://github.com/AlexxIT/XiaomiGateway3 I was able to figure it out.
Would you consider support of other MI Home BLE devises?
These devises were picked up and fully functional:
•	Mi Temperature and Humidity Monitor Digital Clock (LYWSD02)
•	BT Thermometer Hygrometer (MHO-C401)
My water leak detectors (SJWS01LM) were picked up but not functional – I can see battery voltage, battery % and signal strength, but there is no water leak or action sensors available.
It would be nice to have differentiation between “Sensors” and “Diagnostic” in general.
Is it possible to include support for Mi Bands in the future? I would like to use them for presence detection and sleep/awake detection of my family members.
Sincerely,
Anton

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/

### Version

2022.8.6

**Comment by Jc2k** [comment]
Hi this is where we track work on the home assistant documentation, so I'm going to have to close this ticket.

The next major release of HA will have better device naming to make it easier to tell the devices apart.

Binary sensors are not currently supported, see the documentation for a list of supported types. The first binary sensors will be available from September. I don't having any binary sensors so it's hard to work on this.

We use the forums for feature request tracking.

MiBand - probably not any time soon.
