### ISSUE TITLE
Damping Factor - Value?

### ISSUE THREAD

**Issue by jgatringer** [home-assistant/home-assistant.github.io#23849]
### Feedback

How do i have to input the damping-factor? Integer oder procentage? A bit more info would be great.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2022.8.6

**Comment by frenck** [comment]
As per documentation, there is a link proving more detailed information about the damping factor:

![CleanShot 2022-08-22 at 12 56 44](https://user-images.githubusercontent.com/195327/185905328-963f12ae-54b4-464d-804f-b32b948d2cc9.png)

It's a value between 0 and 1.
