### ISSUE TITLE
Statistics as a helper entity 

### ISSUE THREAD

**Issue by BenBrcl** [home-assistant/home-assistant.github.io#23840]
### Feedback

Hi guys, 
Just sharing my opinion, I feel like statistics sensor could be integrated to the helper page within the UI.
Thanks for reading me.
Bye from France.

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2022.8.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by ThomDietrich** [comment]
@BenBrcl thanks for your feedback. I had the same thought and agree. It's on my todo list but I won't get to this within the next couple of weeks. Pull Request welcome. Cheers
