### ISSUE TITLE
Airthings integration should list compatible hardware (or some hardware requirements)

### ISSUE THREAD

**Issue by pheuer** [home-assistant/home-assistant.github.io#23853]
### Feedback

Airthings makes a number of air quality sensors that use various connection technologies (bluetooth, wifi, or no networking at all). The integration page should provide some information about which airthings devices are compatible with home assistant. Model numbers would be ideal, but at a bare minimum it should be stated whether a wifi device is required (presumably it is?).

### URL

https://www.home-assistant.io/integrations/airthings/

### Version

2022.8.6

**Comment by Danielhiversen** [comment]
I am not sure there exists any such list.

Bluetooth devices will also work. If you have the Airthings hub they will update regularly otherwise only when a phone with the airthings app is nearby.
