### ISSUE TITLE
How much Instances (strings) are calculated

### ISSUE THREAD

**Issue by proasnet** [home-assistant/home-assistant.github.io#23860]
### Feedback

Hello, I have configured three strings, and calculated to Energy panel is only first two, the third is not.
I have free use, is this limited for two strings?
Thank you

JV String and JZ String is two working string that **are calculated**
JV String 2 **is not calculated**
![forecast1](https://user-images.githubusercontent.com/76579362/186145233-9322f752-9f7c-4ed5-9e74-930ba7e240e7.jpg)
Dark yellow is from the first inverter = the first and the second strings
Light yellow is from the second inverter = third string
![forecast2](https://user-images.githubusercontent.com/76579362/186145267-90681284-6811-46a0-85da-f46e22048924.jpg)
.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2022.8.6

**Comment by klaasnicolaas** [comment]
Hi there @proasnet 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍
