### ISSUE TITLE
Array of targets

### ISSUE THREAD

**Issue by xerxel** [home-assistant/home-assistant.github.io#23866]
### Feedback

Please could  you show an example of how to supply an array of targets. It's not obvious from the documentation or platform.
Thanks

### URL

https://www.home-assistant.io/integrations/notify/

### Version

2022.8.6

**Comment by dannytsang** [comment]
There are examples on some of the notify integrations. For example for [Discord](https://www.home-assistant.io/integrations/discord/#example-embed-service-call).

Here's a YAML example of supplying a list of targets for Discord:
```
- service: notify.discord
  data:
    message: "hello world"
    target:
      - "456789"
      - "12345"
```

Where:
*  *456789* = user ID
*  *12345* = channel ID

This will post the message to the channel 12345 and the user will get a direct message at the same time.

Discord example in channel:
![image](https://user-images.githubusercontent.com/567982/186647287-0fb0af67-c7a3-4ad1-ae06-41d11c8323cf.png)

Discord example in DM:
![image](https://user-images.githubusercontent.com/567982/186647977-08b53502-5b5b-4f12-ba9f-b31d9e7ce123.png)
