### ISSUE TITLE
Add 20 RESA to list of tested devices for Oncue by Kohler integration

### ISSUE THREAD

**Issue by rssalerno** [home-assistant/home-assistant.github.io#23862]
### Feedback

The Oncue by Kohler integration works with Kohler's 20 RESA generator so it should be added to the list of tested devices.  

### URL

https://www.home-assistant.io/integrations/oncue/

### Version

2022.8.6

**Comment by bdraco** [comment]
Hi @rssalerno 👋 

Here is the link to edit the page:

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/oncue.markdown
