### ISSUE TITLE
MySQL through an SSL connection

### ISSUE THREAD

**Issue by Ahlswede** [home-assistant/home-assistant.github.io#23877]
### Feedback

The documentation suggests that you use the following config line for an SSL protected database:
mysql://user:password@SERVER_IP/DB_NAME?charset=utf8mb4;ssl=true

However this seemed to constantly fail thinking that ";ssl=true" was part of the charset:

Error during connection setup: (MySQLdb.OperationalError) (2019, "Can't initialize character set utf8mb4;ssl=true (path: compiled_in)") (Background on this error at: https://sqlalche.me/e/14/e3q8) (retrying in 3 seconds)

On a hunch I replaced the semicolon with an ampersand to match more common url parameters and also set the MySQL server to only allow SSL connections. This format seems to work:
mysql://user:password@SERVER_IP/DB_NAME?charset=utf8mb4&ssl=true

When I remove the "&ssl=true" section I also get the expected failure result (confirming that this parameter isn't just being ignored):
Error during connection setup: (MySQLdb.OperationalError) (3159, 'Connections using insecure transport are prohibited while --require_secure_transport=ON.') (Background on this error at: https://sqlalche.me/e/14/e3q8) (retrying in 3 seconds)

This might also apply to other connection settings like MariaDB but I didn't test those scenarios.

### URL

https://www.home-assistant.io/integrations/recorder/

### Version

2022.8.6

**Comment by fl0x53** [comment]
I can confirm the issue. As @ahlswede mentioned and documented in [1] you must use "&" to separate arguments.

Even more important for me was the information on [1] of how to encode special chars in the `db_url`, especially for the password: URL encode everything!
I think this crucial info should go into some kind of info box.

[1] https://docs.sqlalchemy.org/en/14/core/engines.html#database-urls

**Comment by fl0x53** [comment]
👍 Still relevant
