### ISSUE TITLE
power monitor no longer supported

### ISSUE THREAD

**Issue by Sjoerd02** [home-assistant/home-assistant.github.io#23870]
### Feedback

Include a note indicating powermonitoring is no longer supported.
https://www.home-assistant.io/blog/2022/04/06/release-20224/#breaking-changes

### URL

https://www.home-assistant.io/integrations/vera/

### Version

2022.8.6

**Comment by frenck** [comment]
The page doesn't list such a feature, so the current page looks correct.

Thanks for sharing feedback 👍 

../Frenck
