### ISSUE TITLE
Where to add cost/energy

### ISSUE THREAD

**Issue by yann1420** [home-assistant/home-assistant.github.io#23879]
### Feedback

It is probably me , but I cannot find what I can alter to provide gas and various electricity prices. 

### URL

https://www.home-assistant.io/docs/energy/faq/

### Version

2022.8.6

**Comment by frenck** [comment]
Well, prices of energy are coupled with their source (e.g., Solar vs consume from grid during the day), it reflects the real world for that matter.

Go to Setting -> Dashboards -> Energy dashboard to configure your energy setting. 

Edit each energy source to set the details on their pricing.

![CleanShot 2022-08-24 at 23 06 33](https://user-images.githubusercontent.com/195327/186523558-a5c638dc-9bfb-4cfd-9d00-9733fec98060.gif)

../Frenck
