### ISSUE TITLE
Unable to login in the callback to Engie (Boxx)

### ISSUE THREAD

**Issue by Cagiva-Raptor** [home-assistant/home-assistant.github.io#23883]
### Feedback

Hi I was able to set up the callback to the Engie login portal, but it does not allow me to log on.\
If I use the same user and password on the engie website they do work.

Can I setup some debugging?

Screenshot: [https://photos.app.goo.gl/YheGjg89d7jSY8ka6](https://photos.app.goo.gl/YheGjg89d7jSY8ka6)

### URL

https://www.home-assistant.io/integrations/toon/

### Version

2022.8.6

**Comment by klaasnicolaas** [comment]
What exactly does this have to do with the Toon integration? I don't see anywhere in our documentation that you have to do anything with the Engie portal?

**Comment by Cagiva-Raptor** [comment]
Hello Klaas

When installing the Toon Integration it asks at the start if the Toon integration is for boxx users from Engie (Belgium) previously called Electrabel,  it uses the same platform as Eneco Toon (NL)

when I lookup the issue it seems that others experience the same since HA 2021.6.2

[https://community.home-assistant.io/t/toon-integration-for-belgian-engie-electrabel-boxx/313616/2](url)
[https://github.com/home-assistant/core/issues/66797](url)
[https://github.com/home-assistant/core/issues/52708](url)

**Comment by frenck** [comment]
This is an integration issue, and belong in the issue tracker of core. This tracker tracks documentation feedback, not integration issues.

../Frenck
