### ISSUE TITLE
reconfigure the energy panel

### ISSUE THREAD

**Issue by yann1420** [home-assistant/home-assistant.github.io#23881]
### Feedback

In order to reconfigure the energy panel take the following action:
**Home Assistant** -> **Settings** -> **Dashboards** -> Click **Energy** 

### URL

https://www.home-assistant.io/docs/energy/faq/

### Version

2022.8.6

### Additional information

This is one of the many well kept secrets that make that HA is notorious about  a steep learning curve.

I am convinced that if these if these quirks are better documented, HA will become more accessible to a larger audience.

**Comment by frenck** [comment]
> This is one of the many well kept secrets that make that HA is notorious about a steep learning curve.

It's not IMHO, there is a prominent dashboard icon in the setting menu. All dashboards can be edited there, including the energy dashboard.

**Comment by yann1420** [comment]
I can see why this is your opinion as you are in the middle of this all.
But I can assure that a tiny little remark in e.g. the energy FAQ can change the world for NOOBs

**Comment by frenck** [comment]
> I can see why this is your opinion as you are in the middle of this all.

It was not the based on my personal opinion, its based on not hearing that confusion or question in general.

**Comment by audunmg** [comment]
I came here to figure out how to reconfigure the energy dashboard.
