### ISSUE TITLE
Always getting invalid API Key

### ISSUE THREAD

**Issue by apktp** [home-assistant/home-assistant.github.io#23893]
### Feedback

HI,

I'm always getting the invalid API key . I waited far more than the 2 advised hours, but no success.

Also created new keys and waited 24 hours ... again no success.

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2022.8.7

**Comment by frenck** [comment]
Hi there @apktp 👋 

It seems like you want to report an issue with an Home Assistant Core integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by apktp** [comment]
Sorry.

Thank you!
