### ISSUE TITLE
Shelly password protection is not supported

### ISSUE THREAD

**Issue by ss89** [home-assistant/home-assistant.github.io#23898]
### Feedback

I would like to see under "known issues" that password protecting your access to the shell device is currently not supported. 

When support is added, i would like to see a small section how to set it up, so that home assistant still handles it.

Bonus points for migrating from password-less to password-protected 😉 

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2022.8.7

**Comment by thecode** [comment]
Home assistant core Shelly integration support password protection for devices, so there is no need to write anything in the documentation.

If it does not work for you please create an issue at https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml

**Comment by ss89** [comment]
Well i don't see any statement of this in the docs. So why do you insta-close the issue? 🤔
