### ISSUE TITLE
Energy production cost without having energy produced

### ISSUE THREAD

**Issue by trvrcr** [home-assistant/home-assistant.github.io#23896]
### Feedback

![image](https://user-images.githubusercontent.com/64335794/186939918-c5e4a20b-ffe6-4c09-a03a-fd852fb6d18f.png)
In the picture above you see for tarif2 no energy production, yet there is an energy cost calculated.
Is there any way I can remove the cost?

And can I provide any help to remove this bug?
It occurred on the 23 August.

The version I was running was 2022.8.4

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2022.8.7

**Comment by dannytsang** [comment]
Is tarif2 set as a sensor in the **Return to grid**? If it is, how is the money being tracked? e.g.
![image](https://user-images.githubusercontent.com/567982/188211070-b0182c6e-b2f8-4e64-831a-ffdc0a8fd3b1.png)

**Comment by trvrcr** [comment]
![image](https://user-images.githubusercontent.com/64335794/188268206-282217fa-d7f3-4233-bd5a-f8ad4dd9e286.png)

**Comment by dannytsang** [comment]
That is odd. I can only suggest going into *developer tools > Statistics* and see if you can find the value for tarif 2 or the Injectievergoeding to see if it's recorded a value on that day so small that it's rounded it to 0.

**Comment by klaasnicolaas** [comment]
This is an issue for the [core](https://github.com/home-assistant/core) or [frontend](https://github.com/home-assistant/frontend) repository, not the documentation
