### ISSUE TITLE
Can someone add the authenticated integration?

### ISSUE THREAD

**Issue by jatgm1** [home-assistant/home-assistant.github.io#23902]
### Feedback

The authenticated Integration is super useful. It still mainly works, it sends persistent notifications that tell you who logged in last and what time and what ip address. Their is an entity called sensor.last_authenticated_user that had the last user that authenticated as an attribute so I could use that to trigger automations. It was amazingly useful. Not it just has an ip address and is no longer maintained. Can someone just add this as a normal feature of home assistant? This is how I prevented intrusion because I have a ZigBee switch that cuts all outside access if it seems like something is amiss after sending notifications through pushover. I cannot use it now though because authenticated doesn't work and hasn't for some time, at least the last_user_authenticated entity doesn't show the user, just the ip address. Can this just be added to the core?

### URL

https://www.home-assistant.io/docs/authentication/

### Version

2022.8.7

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests). If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
