### ISSUE TITLE
404 link from > unsupported > learn more link

### ISSUE THREAD

**Issue by habuild** [home-assistant/home-assistant.github.io#23905]
### Feedback

https://www.home-assistant.io/more-info/unsupported/cgroup_version

The above is the link in HA unsupported link. 
Settings > system > repair > unsupported >> learn more. It goes to a 404 link. 

It doesn't lead to the docker cgroup
https://www.home-assistant.io/more-info/unsupported/docker_configuration/

It seems it would make sense if the link was updated. 

### URL

https://www.home-assistant.io/more-info/unsupported/docker_configuration/

### Version

2022.8.7

### Additional information

404 link from HA learn more unsupported button.

**Comment by cookiestheone** [comment]
same here 2022.9.1

**Comment by frenck** [comment]
This has been fixed.
