### ISSUE TITLE
Support number of decimals and round of the value

### ISSUE THREAD

**Issue by laithsaid** [home-assistant/home-assistant.github.io#23901]
### Feedback

In some cases, the sensor value have too many decimals. You want to save that data in the database with the original received value but present it with 2 decimals. Therefore it would be great if you provide a configuration for the max. numver of decimals where the value is rounded to show only that number of decimals

### URL

https://www.home-assistant.io/dashboards/glance/

### Version

2022.8.7

**Comment by ludeeus** [comment]
Please open an issue in the core repository against the integration that provides that entity. 👍
