### ISSUE TITLE
What are the configuration options for the map history?

### ISSUE THREAD

**Issue by tfoote** [home-assistant/home-assistant.github.io#23918]
### Feedback

The release notes announced the ability to render history of objects a while ago but there's no mention of what the parameters are to set the number of hours. https://www.home-assistant.io/blog/2020/04/08/release-108/

What are those parameters and can they please be documented here? I'd like to be able to use this feature.

### URL

https://www.home-assistant.io/integrations/map/

### Version

2022.8.7

**Comment by frenck** [comment]
Hi there @tfoote 👋 

Sorry for the late reply. The feature you are looking for, is not part of the `map` integration. The path feature is part of the `map` card you can place on your dashboards.

Documentation about that one can be found here: <https://www.home-assistant.io/dashboards/map/#hours_to_show>

../Frenck

**Comment by tfoote** [comment]
The Map Card appears to provide a super set of the capabilities of the Map capability. Might it make sense to switch to use the Map Card and deprecate the use of the Map in the default installation?
