### ISSUE TITLE
YoLink Devices Tested

### ISSUE THREAD

**Issue by 007-DJ** [home-assistant/home-assistant.github.io#23931]
### Feedback

YoLink YS-7707 Contact Sensor
The above device integrates flawlessly to HA and should be added to the tested device listing

### URL

https://www.home-assistant.io/integrations/yolink/

### Version

2022.8.7

**Comment by matrixd2** [comment]
@007-DJ  Thank you,Here is HA document update
https://github.com/home-assistant/home-assistant.io/pull/24018
