### ISSUE TITLE
add examples for YOUR_APPRISE_CONFIG_URLS and YOUR_APPRISE_URLS

### ISSUE THREAD

**Issue by renarena** [home-assistant/home-assistant.github.io#23932]
### Feedback

It would be very helpful to know, how to replace YOUR_APPRISE_CONFIG_URLS and YOUR_APPRISE_URLS.
Ormaybe  link to this tutorial? http://nuxref.com/2020/12/15/setup-apprise-notifications-on-home-assistant/

```
  # Example:
  url: "hassio://user@hostname/accesstoken"

  # local configuration file:
  config: /config/apprise.yaml
```

### URL

https://www.home-assistant.io/integrations/apprise/

### Version

2022.8.7

**Comment by caronc** [comment]
I can try see if i can update it in the next few weeks. The blog referenced is actually my own. Will try...

**Comment by frenck** [comment]
Please note, that our documentation is not here to teach you about Apprise itself.
So, what URLs could be used, seems more of a tasks for the Apprise documentation, not Home Assistant.

**Comment by renarena** [comment]
I think the yaml syntax to use or how to reference files is.
Whats wrong with giving ONE example for a placeholder?
At least i find integration (and other) docs often not very helpful because such things are missing. 
F.e. if there are a lot of options and there is an example with the minimal config, but no one with the maximal one. So you need to read big option tables and put together the needed lines yourself rather then having an example with mostly self explanatory  lines.

**Comment by frenck** [comment]
> Whats wrong with giving ONE example for a placeholder?

I didn't say that that was not allowed, I do think we should watch out not to replace or mimic upstream documentation :)
