### ISSUE TITLE
OpenWeatherMap integration not accepting active API key

### ISSUE THREAD

**Issue by michealespinola** [home-assistant/home-assistant.github.io#23933]
### Feedback

I followed the directions, and after several days of confirming that my API key is indeed active, the OWM integration is still not accepting my API key as valid.

Web page form response: "Invalid API key"

I have tried the default key as well as an additionally generated key.

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2022.8.7

**Comment by DeaneWheresItAt** [comment]
I'm having the same issue, have tested to ensure the API key works using https://api.openweathermap.org/data/2.5/weather?q=London&units=metric&appid=APIKEY - and it works.

**Comment by DaHype** [comment]
Also the Same Problem here. My Api Key is active and its working but the integration don´t accept it. :-(

Someone have an Solution?
I use newest Home Assistant on RPi3+

**Comment by ricoroodenburg** [comment]
Same issue.

Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by michealespinola** [comment]
Apologies

**Comment by DaHype** [comment]
@michealespinola @ricoroodenburg @DeaneWheresItAt 

May please you can comment here also:

https://github.com/home-assistant/core/issues/77914#issuecomment-1239156312

Thanks
