### ISSUE TITLE
Information about trigger duration can not be found on the trigger page

### ISSUE THREAD

**Issue by echo-lalia** [home-assistant/home-assistant.github.io#23937]
### Feedback

adding a trigger to an automation in the home assistant UI, you are given a field labeled "Duration (optional)"

I clicked the "learn more about triggers" link to figure out what that meant, but could not find anything relevant on the linked page. I'm sure i could try hunting with google, but it would be much more accessible to just have help about that field on the linked page.

Thank you :)

### URL

https://www.home-assistant.io/docs/automation/trigger/

### Version

2022.8.7

### Additional information

![Screenshot 2022-08-29 113059](https://user-images.githubusercontent.com/108598670/187272916-860525a8-6e78-4021-95f8-50133f203d5d.png)

**Comment by dannytsang** [comment]
It's mentioned in the [numeric state trigger](https://www.home-assistant.io/docs/automation/trigger/#numeric-state-trigger) but not in all triggers where the duration appears so I will add a similar example.
