### ISSUE TITLE
Switch  for pause/resume 

### ISSUE THREAD

**Issue by DMDatak** [home-assistant/home-assistant.github.io#23936]
### Feedback

I'm use a Copper Business and HA integration but I can't see Switch for pause/resume, I need to do something ?
<img width="764" alt="Capture d’écran 2022-08-29 à 19 10 36" src="https://user-images.githubusercontent.com/99891554/187256272-51314d68-7456-46f5-a4ab-f6f6b11a199b.png">

### URL

https://www.home-assistant.io/integrations/wallbox/

### Version

2022.8.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
