### ISSUE TITLE
Slow mode sensor and toggle

### ISSUE THREAD

**Issue by GuntranHoet** [home-assistant/home-assistant.github.io#23959]
### Feedback

It'd be beneficial to have the ability to see if QbitTorrent is running in slow mode or not and have the ability to toggle the slow mode on or off. For example, when I leave the house, disable slow mode, but enable slow mode when I get back so my network isn't slowed down while I'm at home.

I'm not sure if that's possible with the QbitTorrent API. If possible I'd love to see it.
Great integration so far regardless!

### URL

https://www.home-assistant.io/integrations/qbittorrent/

### Version

2022.8.7

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
