### ISSUE TITLE
Debug Logging - where to see the logs

### ISSUE THREAD

**Issue by apadua** [home-assistant/home-assistant.github.io#23951]
### Feedback

The documentation is very clear on how to enable debug logging. However, it doesn't show where the user can find the debug log files. This is important as it will be the obvious next step after enabling debugging.

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2022.8.7

**Comment by frenck** [comment]
The logs are in the menu: Settings -> System -> Logs
