### ISSUE TITLE
Is this one supporting Argon Radio 2i?

### ISSUE THREAD

**Issue by larhedse** [home-assistant/home-assistant.github.io#23968]
### Feedback

Well I am new to this, and from what I understand my Argon Radio 2i is UNDOK and therefor Frontiers based or something. This looks all good, except I only get a volume slider nowdays - nothing else? Or am I missing something?

### URL

https://www.home-assistant.io/integrations/frontier_silicon/

### Version

2022.8.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
