### ISSUE TITLE
Setcap on python executable

### ISSUE THREAD

**Issue by xanderificnl** [home-assistant/home-assistant.github.io#23969]
### Feedback

Assuming we follow the advice and assign `net_bind_service` capabilities to `/srv/homeassistant/homeassistant_venv/bin/python3` we're now left with a rather large security issue. 

Anyone that can execute `/srv/homeassistant/homeassistant_venv/bin/python3` is now capable of running *any* service on *any* free port, i.e. `ssh-mitm`. 

A firewall (iptables, ufw) rule doing port forwarding might be better suited. 

### URL

https://www.home-assistant.io/integrations/emulated_hue/

### Version

2022.8.7

**Comment by klaasnicolaas** [comment]
You are free to add that information to the documentation yourself. But I do believe that someone who follows this Linux route is an advanced user and therefore also knows what to do to better secure his system.
