### ISSUE TITLE
Functionality to ignore unreasonable values

### ISSUE THREAD

**Issue by gforschi** [home-assistant/home-assistant.github.io#23973]
### Feedback

It would be great if the utility meter had some sort of functionality to ignore unreasonable values.

When this is used with for example electric energy my main inlet and fuses makes it impossible that I have a consumption of lets say 8000 kWh between state updating.
Assuming most entities reporting energy will do this "live", but even if values were throttled to once every hour, or even once per day I believe the majority of households would be below 100 kWh/daily consumption even for a house.

With a (example) limit of 100kWh/daily set, a logic could allow around 4kWh change per hour or 0,07 kWh/minute. Any value above this would be ignored.
This could maybe use now() vs last_changed and new state vs previous state to validate?

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2022.8.7

**Comment by dgomes** [comment]
This is not the place for feature requests (please use https://community.home-assistant.io/c/feature-requests/13)

That being said, you can use https://www.home-assistant.io/integrations/filter/#outlier as the source of the utility_meter

**Comment by gforschi** [comment]
Ah, sorry about that.
Yeah, I tried the outlier filter. Maybe it could work with some tweaking, but my initial test with it kinda failed.
