### ISSUE TITLE
How can we expose the prayer time values for automations

### ISSUE THREAD

**Issue by slimatic** [home-assistant/home-assistant.github.io#23979]
### Feedback

How can we expose the prayer time values for automations ? The information it provides on the UI is very helpful, however, the sensor values i.e. the times cannot be easily used for automations. Is there a way to update this?

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2022.8.7

**Comment by engrbm87** [comment]
Hello @slimatic , this is a question for https://github.com/home-assistant/core/issues.
To answer you, the sensor value is a timestamp, so you can easily use it as a time trigger.
```yaml
trigger:
  - platform: time
    at: sensor.fajer_prayer
```
