### ISSUE TITLE
Roku Integration as no information on how to use literals

### ISSUE THREAD

**Issue by kekegt** [home-assistant/home-assistant.github.io#23978]
### Feedback

I saw it was possible to send literals to the Roku API.

service: remote.send_command
data:
  command:  
    - Lit_a
target:
  entity_id: remote.55_tcl_roku_tv

Would that be the way to send the letter "a" ?

### URL

https://www.home-assistant.io/integrations/roku/

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
