### ISSUE TITLE
Problem installing CORE on Ubuntu 22.04 Python 3.10.4

### ISSUE THREAD

**Issue by fuzzznet** [home-assistant/home-assistant.github.io#23970]
### Feedback

After installation, it does not start on the "hass" command. Error: ModuleNotFoundError: No module named 'sqlalchemy'

Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-47-generic x86_64)
Phyton 3.10.4

### URL

https://www.home-assistant.io/installation/linux/

### Version

2022.8.7

**Comment by frenck** [comment]
This issue is fixed in the next Home Assistant release 2022.9, you can  work around it by temporary manually installing the sqlalchemy package using pip.
