### ISSUE TITLE
References to 'object_id' and 'entity_id' are confusing

### ISSUE THREAD

**Issue by kpfleming** [home-assistant/home-assistant.github.io#23983]
### Feedback

The top-level Discovery page has multiple references to `object_id` and `entity_id` which appear to contradict each other.

First, at https://github.com/home-assistant/home-assistant.io/blob/24005816ed33ab094593d7a3ff1f92ed0d04664e/source/_docs/mqtt/discovery.markdown?plain=1#L59 there is a statement that the `object_id` portion of the discovery topic for the entity is *not* used to construct the `entity_id`.

Second, at https://github.com/home-assistant/home-assistant.io/blob/24005816ed33ab094593d7a3ff1f92ed0d04664e/source/_docs/mqtt/discovery.markdown?plain=1#L435 there is a section which demonstrates how to use the `object_id` configuration variable (which is distinct from the same-named field in the discovery topic) to override the automatic usage of the topic's `object_id` ('device1') to generate the `entity_id`. To add to the confusion, the first sentence of this section states that "the entity id is automatically generated from the entity's name". Since the example refers to avoiding the entity id being 'device1', and 'device1' does not appear in the `name` configuration variable but does appear in the discovery topic, this statement seems to contradict the others.

As someone who is building a new MQTT-based integration, I'd like to be able to fully understand how `object_id` (in the topic), `object_id` (in the payload), `unique_id` (in the payload), and `entity_id` (internal to HA) are related to each other, and which ones should or should not be used for a new integration.

I'd be happy to submit a PR to improve this, but I suspect that may require diving into the discovery code in HA and I haven't quite had time to do that yet :-) If anyone can point to authoritative docs which more clearly describe the situation, I'll definitely use them as a resource.

### URL

https://www.home-assistant.io/docs/mqtt/discovery/

### Version

2022.8.7

**Comment by homeassistant** [comment]
Hey there @emontnemery, mind taking a look at this feedback as it has been labeled with an integration (`mqtt`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L390) for? Thanks!
