### ISSUE TITLE
Ubiwizz Integration is possible ?

### ISSUE THREAD

**Issue by SepuLeVrai** [home-assistant/home-assistant.github.io#23982]
### Feedback

Hi  

In advance excuse my wording  i'm french.

I have an overkiz at home, but managed by Ubiwizz platform. Have you a roadmap to manage it with HA ?

Https://ubiwizz.com

Thank you

### URL

https://www.home-assistant.io/integrations/overkiz/

### Version

2022.8.7

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
