### ISSUE TITLE
No information

### ISSUE THREAD

**Issue by raymentj** [home-assistant/home-assistant.github.io#23989]
### Feedback

No instructions covering smart plugs here...

Much love to Home Assistant creators ❤️

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2022.8.7

**Comment by klaasnicolaas** [comment]
What would you like to see in the docs? Since it is not difficult to add an individual device to the energy dashboard 🤷🏻‍♂️

**Comment by audunmg** [comment]
Choice of words matter.

> What would you like to see in the docs? Since it is not difficult to add an individual device to the energy dashboard 🤷🏻‍♂️

I'm sure it's not difficult for you vs someone who never did it before.

It would be much more accessible if it was explained that the energy dashboard measures energy in kWh, and need sensors to be converted to that, and a list:

* Sensors which provide power usage in Watts, can be used like this (with yaml example)
* Sensors with voltage and ampere only can be adapted with example.

**Comment by frenck** [comment]
> Sensors which provide power usage in Watts, can be used like this (with yaml example)

That will not work, as it is an energy dashboard (e.g., kWh) and not a power (e.g., W) dashboard. Power and Energy are not the same things (which is also explained in the FAQ).

> Sensors with voltage and ampere only can be adapted with example.

Those are also not energy values.

If a device doesn't report energy, it isn't supported by the energy dashboard. I'm not entirely following the documentation suggestion you are trying to make?


../Frenck
