### ISSUE TITLE
Track multiple station departures

### ISSUE THREAD

**Issue by Arosuto9308** [home-assistant/home-assistant.github.io#23991]
### Feedback

How can I track departures in multiple stations nearby without having to track a fixed destination? 

### URL

https://www.home-assistant.io/integrations/nmbs/

### Version

2022.8.7

**Comment by thibmaek** [comment]
The recommended way is to just create additional sensors I think. 

Auto-creating sensors based on proximity is not yet supported.

**Comment by Arosuto9308** [comment]
> The recommended way is to just create additional sensors I think.
> 
> Auto-creating sensors based on proximity is not yet supported.

But I always have to enter at least 1 fixed destination? I tried without it and I got an error.

**Comment by frenck** [comment]
You can't create dynamic entries for integrations. Each has to be added fixed.

../Frenck
