### ISSUE TITLE
Huawei Technologies Co., Ltd. E220 HSDPA Modem

### ISSUE THREAD

**Issue by LukaszP2** [home-assistant/home-assistant.github.io#23992]
### Feedback

Hi,

From over the year I'm using Huawei Technologies Co., Ltd. E220 HSDPA Modem and everythinks it's ok.

### URL

https://www.home-assistant.io/integrations/sms/

### Version

2022.9.0

**Comment by ocalvo** [comment]
What is the ask here?
Do we need to update the list of tested hardware?

**Comment by LukaszP2** [comment]
Yes, I think we could add E220 as tested hardware.

**Comment by ocalvo** [comment]
Please edit the file sms.markdown and add the entry in the listed hardware.

**Comment by ocalvo** [comment]
Could you also add the link to where to buy this device?
