### ISSUE TITLE
CLA privacy 

### ISSUE THREAD

**Issue by FutureTense** [home-assistant/home-assistant.github.io#23997]
### Feedback

I want to sign the CLA, but I don’t want my name/email publicly attached to Home Assistant.  I don’t mind if the big guns of HA have this information, as long as my privacy is protected.  Is this possible?

### URL

https://www.home-assistant.io/developers/cla_sign/

### Version

2022.8.7

**Comment by klaasnicolaas** [comment]
For all your public activities on GitHub, your name/email will be visible to others, for example in every commit (body) you make. Unless you've shielded this, by following [these steps](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github).

I also close the issue as the issue tracker is used here for documentation feedback.
