### ISSUE TITLE
First Example for Workday Sensor is Wrong

### ISSUE THREAD

**Issue by pkscout** [home-assistant/home-assistant.github.io#24007]
### Feedback

According to this post:

https://community.home-assistant.io/t/workday-add-holidays-not-working/359953/11

To exclude holidays you must put it in the exclude section.  Simply adding holidays doesn't do anything.  The custom holidays are **added** to the full holiday list, so there is no way to have just custom holidays (without excluding every built in one anyway).  So the first example is just flat out wrong.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2022.8.7

**Comment by pkscout** [comment]
Still wrong. The fact that nobody is fixing it doesn't make it less of an issue. If you want to clean up your GitHub issues, maybe fix them instead of having a bot close the ones you are ignoring.

**Comment by pkscout** [comment]
Still wrong. The only reason this issue is stale is because nobody on the HA team has bothered to look at it.

**Comment by frenck** [comment]
This is actually a bug and not a documentation issue.

There are issues in the main core issue tracker and even contribution PRs open to fix the issue. So yeah, people have looked at it, however, this issue is in the wrong place.

Closing the feedback, as it originates from an issue.

../Frenck
