### ISSUE TITLE
PostMarketOS and Termux guides

### ISSUE THREAD

**Issue by upintheairsheep** [home-assistant/home-assistant.github.io#24001]
### Feedback

Please put a guide to install home assistant core on postmarketos (for iOS devices) and Termux (for android devices) if possible.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.8.7

**Comment by frenck** [comment]
The Home Assistant project does not support or recommend running on these operating systems. Therefore they will most like not work (or break in the future). We will not provide documentation either.

Please use a different installation method.

../Frenck
