### ISSUE TITLE
Put a note that scenes cannot be nested inside of scenes.

### ISSUE THREAD

**Issue by evanpierre** [home-assistant/home-assistant.github.io#24015]
### Feedback

Hello,

I think it would be useful for new users to note somewhere on the Scene page in the official documentation that Scenes nested inside of Scenes will not trigger as discussed here: https://github.com/home-assistant/core/issues/28991

Cheers

### URL

https://www.home-assistant.io/docs/scene/

### Version

2022.8.7

**Comment by frenck** [comment]
Scenes themself do not have a state that can be a controller (or be restored using a scene). It is not just scenes, but applies to anything that doesn't have a user-settable state.

For example, weather entities. You can't change the weather by including it in a scene.
