### ISSUE TITLE
Dynamic Segment Values

### ISSUE THREAD

**Issue by Joddie108** [home-assistant/home-assistant.github.io#24025]
### Feedback

Currently the severity specification requires a fixed integer for beginning and end.
If it would allow use of a variable integer, I could show a dynamic relationship.
For example a power system might show solar supply on the gauge with the severity range for green being defined by the load being demanded.
In this case the severity would show green when the solar exceeds load or otherwise be red or orange.

### URL

https://www.home-assistant.io/dashboards/gauge/

### Version

2022.8.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
