### ISSUE TITLE
HIK killed CGI

### ISSUE THREAD

**Issue by PanPompa** [home-assistant/home-assistant.github.io#24024]
### Feedback

Hello Hikvisioncam Developer,

I was using your plugin with success until I have upgraded my camera firmware.... It turns out that HIK no longer supports CGI:
https://www.hikvision.com/content/dam/hikvision/en/support/notice/Hikvision-discontinues-CGI-support-in-IP-cameras.pdf

Is there a chance you could rewrite this plugin using their new API ?

Thank You :)

### URL

https://www.home-assistant.io/integrations/hikvisioncam/

### Version

2022.8.7

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
