### ISSUE TITLE
Can't configure mqtt sensor.

### ISSUE THREAD

**Issue by cliffchen** [home-assistant/home-assistant.github.io#24037]
### Feedback

I've followed the updated 2022.9.0 document to change the MQTT sensor configuration, but the following error message showed when checking the configuration. 

Invalid config for [mqtt]: [sensors] is an invalid option for [mqtt]. Check: mqtt->mqtt->sensors. (See /config/configuration.yaml, line XXX).

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2022.9.0

**Comment by frenck** [comment]
Which version of Home Assistant are you running?

**Comment by cliffchen** [comment]
The Home Assistant version is  2022.9.0, same as the document version. Thanks.

**Comment by cliffchen** [comment]
Same error on version 2022.9.1.

**Comment by cliffchen** [comment]
rechecked, the issue still exists on version 2022.9.1

**Comment by cliffchen** [comment]
rechecked, the issue still exists on version 2022.9.1

**Comment by emontnemery** [comment]
Please share your MQTT configuration before you updated to 2022.9 as well as after you updated.

**Comment by cliffchen** [comment]
Just realized I used "sensors" instead of "sensor" in the configuration. Sorry for the confusion caused.
