### ISSUE TITLE
Great integration!

### ISSUE THREAD

**Issue by Daali** [home-assistant/home-assistant.github.io#24036]
### Feedback

This is a clean install for a great integration.  Ecowitt is sending uptime in seconds in a field called "runtime"
, can we get that added to a sensor to track the uptime and trigger off its state changes?

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2022.9.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
