### ISSUE TITLE
SERVICE ELKM1.SENSOR_ZONE_TRIGGER does not work

### ISSUE THREAD

**Issue by Farleykri** [home-assistant/home-assistant.github.io#24035]
### Feedback

i've setup a simple service to call a zone trigger and tested it on a known good zone and i've not heard the chime nor seen a notification that the zone was triggered.

manually opening the zone (aka just opening the door) produced a chime and was confirmed on HA as being open

### URL

https://www.home-assistant.io/integrations/elkm1/

### Version

2022.9.0

### Additional information

service: ELKM1.SENSOR_ZONE_TRIGGER
  entity_id: sensor.garage_window_do
  
  this is the code i used per the description 
  https://www.home-assistant.io/integrations/elkm1/#service-elkm1sensor_zone_trigger

**Comment by gwww** [comment]
Logs please. Works as expected when I try it -- I get the chime from the keypad; I did not check the zone state.

**Comment by Farleykri** [comment]
2022-09-07 19:18:58.445 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139922927031424] Error handling message: must contain at least one of entity_id, device_id, area_id.. Got {'type': 'execute_script', 'sequence': [{'service': 'elkm1.sensor_zone_trigger', 'data': {}}], 'id': 37} (invalid_format)
2022-09-07 19:20:05.606 WARNING (MainThread) [elkm1_lib.connection] ElkM1 at elk://192.168.1.25 disconnected
2022-09-07 19:22:52.222 WARNING (MainThread) [elkm1_lib.connection] ElkM1 at elk://192.168.1.25 disconnected
2022-09-07 19:27:58.624 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: No ElkM1 with prefix '1' found
2022-09-07 19:27:58.625 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139922927031424] Error handling message: No ElkM1 with prefix '1' found (unknown_error)



nothing on my side that i can figure out. i see the first call i made errored out obvi cuz i forgot to put in entity ID but maybe it's a syntaxing issue on my part?

service: ELKM1.SENSOR_ZONE_TRIGGER
  entity_id: sensor.living_room_wind


![image](https://user-images.githubusercontent.com/12490327/189009747-bc89c919-7de8-4c07-9889-ce19925a40ad.png)

**Comment by gwww** [comment]
`handling message: must contain at least one of entity_id, device_id, area_id.. Got {'type': 'execute_script', 'sequence': [{'service': 'elkm1.sensor_zone_trigger', 'data': {}}], 'id': 37} (invalid_format)`

Seems that the entity_id was not supplied. data is empty.

**Comment by Farleykri** [comment]
correct that was the first call i made errored out obvi cuz i forgot to put in entity ID

but no other service calls are making any logs
unless i'm searching for the wrong thing.

I have ELKM1 in the search bar

**Comment by gwww** [comment]
Can you try calling the service with correct parameters using Services on the developers menu.

**Comment by Farleykri** [comment]
you bet, 
this is my code and i've been running everything on the services tab
![image](https://user-images.githubusercontent.com/12490327/189012196-872f6312-fbef-44de-97e6-e287004f85c8.png)

**Comment by gwww** [comment]
I’m confused by the No ElkM1 with prefix '1' found (unknown_error) message. 

Do you have more than one Elk?

Im guessing not. If not did you configure your instance with 1 as the prefix? The prefix is usually empty if you have a single Elk.

**Comment by Farleykri** [comment]
that was me messing around with the voice application, trying different numbers, not pertinent to what is going on with trigger. it was me just making sure other services work. i put prefix 1 jus to see what happened

**Comment by gwww** [comment]
In the developer tools try using the gui instead of YAML

**Comment by Farleykri** [comment]
![image](https://user-images.githubusercontent.com/12490327/189013358-4947ec73-65b4-4dce-a113-e4c7a6684625.png)


don't seem to be able to edit the targets for some reason which is why i went to YAML mode

**Comment by gwww** [comment]
The correct YAML is:
```
service: elkm1.sensor_zone_trigger
data: {}
target:
  entity_id: sensor.living_room_wind
```
My service call:
<img width="874" alt="Screen Shot 2022-09-07 at 21 33 15" src="https://user-images.githubusercontent.com/3060128/189013973-aec03631-39f6-4887-8bcd-2376d25e93fe.png">

**Comment by Farleykri** [comment]
weird, i wonder why mine isn't showing any targets or giving me the ability to see then.

trying the fixed syntax yielded the same results (no logs but no violating either) but i think we might be narrowing down.

still nothing to show for in the logs though which kinda sucks.

all other services seem to be functioning however, like display text, speak etc. just this one is blanking out

**Comment by gwww** [comment]
Latest logs would help.

**Comment by Farleykri** [comment]
Good morning, so after updating to latest HA version i now get the GUI for the targets but am still unable to trigger a zone when i call service.

here's a full printout of logs
https://pastebin.com/BkSanBsB


and here's full logs
https://pastebin.com/t25HXmAh

**Comment by frenck** [comment]
Hi, there all 👋 

It seems like you are trying to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
