### ISSUE TITLE
How the proxy should work?

### ISSUE THREAD

**Issue by evlo** [home-assistant/home-assistant.github.io#24049]
### Feedback

I don't understand how to esphome bluetooth proxy_should work.

i have added
```
esp32_ble_tracker:
  scan_parameters:
    active: true
bluetooth_proxy:
```

to one of my existing esphome devices (climate)
I have tried removing it and adding it into home assistant, but no new entries in esphome integration, bluetooth integration says there are no unconfigured adapters. 

Also maybe add link to the https://www.home-assistant.io/integrations/homekit_controller/#bluetooth-device-support somewhere on the bluetooth integration page. 

Currently, at least for me it is hugely confusing.

Obviously it might just be issue with me.

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2022.9.0

**Comment by codyc1515** [comment]
I agree. It’s not clear when or if the ESPHome Bluetooth Proxy integration is working.

**Comment by evlo** [comment]
@codyc1515 you can use verbose logging and see what is going on on the device side at least
