### ISSUE TITLE
Suggestion: Add "Tope de Gas" data.

### ISSUE THREAD

**Issue by dsz79** [home-assistant/home-assistant.github.io#24042]
### Feedback

It would be interesting to add at an informative level the price of the "Tope de Gas" (EXCEDENTE O DÉFICIT DE LA LIQUIDACIÓN DEL MECANISMO DE AJUSTE DE COSTES DE PRODUCCIÓN) as an attribute

It can be obtained e.g. from : "https://www.esios.ree.es/es/analisis/1900?vis=1&start_date=06-09-2022T00%3A00&end_date=06-09-2022T23%3A00&compare_start_date=05-09-2022T00%3A00&groupby=hour"

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2022.9.0

### Additional information

Thanks

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
