### ISSUE TITLE
Pushover GUI Edit Config

### ISSUE THREAD

**Issue by momoz** [home-assistant/home-assistant.github.io#24044]
### Feedback

How do you edit the configuration of pushover in the GUI?   Since I've removed the API keys etc from YAML, if I need to change this how/where do you edit it?   Under integrations there is no option to edit any of it.

### URL

https://www.home-assistant.io/integrations/pushover/

### Version

2022.9.0

**Comment by engrbm87** [comment]
If the api key is not valid a reauthentication flow is initiated where you can enter the new api key to fix this. As for configuring a new user_key or new api_key then means recreating the integration entry.

**Comment by frenck** [comment]
If integrations have authentication issues, they should ask for a new key / start a reauthorization process of which a notification will be raised.

If they don't, you can raise an issue for that.

../Frenck


Edit: oh! Wonders of mobile apps :) the right answer was already above 👍
