### ISSUE TITLE
Home Assistant Repairs

### ISSUE THREAD

**Issue by XcOM987** [home-assistant/home-assistant.github.io#24041]
### Feedback

Would be nice if there is an option within repairs to check for repairs, IE I've fixed an issue, can I then click a button to get HA to check the issue has been mitigated? 

### URL

https://www.home-assistant.io/integrations/repairs/

### Version

2022.9.0

**Comment by frenck** [comment]
Repairs should resolve or provide a way to resolve them. There is no way to "check" for them.

If you have an repairs issue you seem not to be able to get rid off or resolve, that would be a bug and should be reported as such in our Core issue tracker.

../Frenck
