### ISSUE TITLE
Intrusion detection

### ISSUE THREAD

**Issue by nocturnalit** [home-assistant/home-assistant.github.io#24054]
### Feedback

Could you please add smart event intrusion detection? 
The basic motion detection is very basic and gets a lot of false triggers and most people use intrusion detection instead, however I cannot add that type of event in home assistant and think it might have just been overlooked.

### URL

https://www.home-assistant.io/integrations/hikvision/

### Version

2022.9.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
