### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by DeanK2022** [home-assistant/home-assistant.github.io#24051]
### Feedback

The help is really clear on how to set up a schedule, but how can I tie that in to _doing_ something?  Like  - living room light on, heating on / off and so on?
That'd be a useful addition to this page

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2022.9.0

**Comment by frenck** [comment]
It works like any other helper.

Helpers (and any other integration in Home Assistant, of which everything in Home Assistant exists), provide entities. Entities can be used in automations to act or trigger on. E.g., when a switch entity turns on, a climate entity registers a different temperature, or when a schedule changes its state.

None of that is specific to the schedule integration.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck

**Comment by DeanK2022** [comment]
Thanks Frenck!
