### ISSUE TITLE
More information about SensorPush system or ecosystem, please

### ISSUE THREAD

**Issue by alderete** [home-assistant/home-assistant.github.io#24055]
### Feedback

SensorPush devices are listed, but it's not clear if you need (for example) the SensorPush hub to connect them, or how the SensorPush ecosystem works. 

No, it's not the job of the HA docs to cover the full details. But it does seem pretty basic to explain what the minimal SensorPush install that can work with Home Assistant would consist of. If nothing else, a short "Note: SensorPush devices require a SensorPush hub to ..." (or whatever it actually needs).

Or, even better, reassurance that it works without a hub: "Note: Once activated in the SensorPush app, supported SensorPush devices can be used with Home Assistant without dependencies on other SensorPush infrastructure." (Or, again, whatever.)

### URL

https://www.home-assistant.io/integrations/sensorpush/

### Version

2022.9.0

**Comment by alderete** [comment]
After doing a bit of research on the SensorPush site, I believe the following things are (a) true, and (b) worth adding to the doc. If someone can verify/falsify these assertions, I'm happy to create a PR for the doc changes.

**Assertion**: Supported SensorPush devices use a local Bluetooth connection to communicate with Home Assistant. (This probably implies a minimum version of Home Assistant, due to needing the Bluetooth integration, but since the SensorPush integration is an official one, added in a specific (and supported) HA release, it's safe for that to be implicit.)

**Assertion**: Supported SensorPush devices can _only_ use the local Bluetooth connection to communicate with Home Assistant. That is, the SensorPush G1 WiFi Gateway is not only unnecessary, but _can't_ be used. It does not extend reception range via Wi-Fi, or otherwise make supported devices more accessible to Home Assistant.

**Assertion**: There is (currently) no support for the SensorPush cloud service. Devices must direct connect to Home Assistant. (via Bluetooth)

**Comment by bdraco** [comment]
The link to edit the docs is https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/sensorpush.markdown if you feel like taking a stab at updating them
