### ISSUE TITLE
Here Travel Time not working

### ISSUE THREAD

**Issue by JBoye** [home-assistant/home-assistant.github.io#24069]
### Feedback

I think somewhere on the documentation page, it should be mentioned that is currently does not work and people shouldn't waste time on it until its fixed

### URL

https://www.home-assistant.io/integrations/here_travel_time/

### Version

2022.9.1

**Comment by eifinger** [comment]
Thank you for contributing to this open source project.
If you want to help the issue along you can weigh in on the discussion [here](https://github.com/home-assistant/core/pull/76553) and [here](https://github.com/home-assistant/core/pull/74348).

You can also open a PR with your suggested changes to the [documentation file](https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/here_travel_time.markdown) directly.

**Comment by eifinger** [comment]
@home-assistant close
