### ISSUE TITLE
Nuki not in device list for automations

### ISSUE THREAD

**Issue by DUC750** [home-assistant/home-assistant.github.io#24068]
### Feedback

I wanted to create an automation that unlocks the lock as soon as the first movement is detected in the morning. 
But unfortunately my Nuki is not shown in the device selection of the automations.

### URL

https://www.home-assistant.io/integrations/nuki/

### Version

2022.9.1

**Comment by Superkikim** [comment]
What type of Nuki do you have ? 

I have Nuki 3 Pro (integrated Wifi) and it works well. 

I just setup an automation to auto-lock after one minute if my shelly door/window 2 detect the door has been closed:

```alias: Auto verrouillage local vélo
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.cerbere_velos_door
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition:
  - condition: state
    entity_id: binary_sensor.nuki_local_velo_locked
    state: "on"
action:
  - device_id: 73a59ccac38c129e821b796dda1d857a
    domain: lock
    entity_id: lock.nuki_local_velo_lock
    type: lock
  - service: notify.telegram
    data:
      message: Le local vélo a été verrouillé automatiquement
      title: Local vélo verrouillé
mode: single
```

**Comment by pree** [comment]
I've created the PR https://github.com/home-assistant/core/pull/79806 to register the entities as devices.

**Comment by DUC750** [comment]
> What type of Nuki do you have ? 
> 
> I have Nuki 3 Pro (integrated Wifi) and it works well. 
> 
> I just setup an automation to auto-lock after one minute if my shelly door/window 2 detect the door has been closed:
> 
> ```alias: Auto verrouillage local vélo
> description: ""
> trigger:
>   - platform: state
>     entity_id:
>       - binary_sensor.cerbere_velos_door
>     from: "on"
>     to: "off"
>     for:
>       hours: 0
>       minutes: 1
>       seconds: 0
> condition:
>   - condition: state
>     entity_id: binary_sensor.nuki_local_velo_locked
>     state: "on"
> action:
>   - device_id: 73a59ccac38c129e821b796dda1d857a
>     domain: lock
>     entity_id: lock.nuki_local_velo_lock
>     type: lock
>   - service: notify.telegram
>     data:
>       message: Le local vélo a été verrouillé automatiquement
>       title: Local vélo verrouillé
> mode: single
> ```

Sorry I didn't reply. I'm on the road for several months and can't deal with it at the moment. But thank you for your answer.
