### ISSUE TITLE
What is meant to happen after setting up Ecowitt Integration? - here nothing happens

### ISSUE THREAD

**Issue by totti4ever** [home-assistant/home-assistant.github.io#24064]
### Feedback

So, I set up the integration (Core/Container) and configured my Froggit DP-1500 to send the data to a custom server in ecowitt format with my Home Assistant's IP (working fine e.g. for shellies in the same network, different port of course).

But I cannot see anything besides the new entry "Ecowitt" on the integration site. No Devices, no entitites, no log lines containing ecowitt.

What am I doing or expecting wrong?

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2022.9.1

**Comment by rodw-au** [comment]
i get the same issue here. Nothing happens
