### ISSUE TITLE
How to use this Scheduler component ?

### ISSUE THREAD

**Issue by jmcollin78** [home-assistant/home-assistant.github.io#24077]
### Feedback

The page explains how to create and configure the Scheduler component. That's great but no explanation on how to use the scheduler.
I try to schedule something with automation but my scheduler is not visible.

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2022.9.1

**Comment by balloob** [comment]
Scheduler entities are created as `schedule.<name>` and have a state of `on` or `off`. You need to use state triggers to test when they are on/off.
