### ISSUE TITLE
Please fix this thermostat card problem.

### ISSUE THREAD

**Issue by rhaymg** [home-assistant/home-assistant.github.io#24071]
### Feedback

https://www.reddit.com/r/homeassistant/comments/x9ifl7/lost_ability_to_change_thermostat_temp/

### URL

https://www.reddit.com/r/homeassistant/comments/x9ifl7/lost_ability_to_change_thermostat_temp/

### Version

2022.9.1

**Comment by frenck** [comment]
Hi there @rhaymg 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
