### ISSUE TITLE
ClearGrass Air Monitor is not supported

### ISSUE THREAD

**Issue by petron1e** [home-assistant/home-assistant.github.io#24074]
### Feedback

Hello,
would be possible add support also for Qingping Air Monitor (https://www.qingping.co/air-monitor/specifications)? I have this type have but unfortunately is missing on your list of supported devices. Seems to be quite popular device. Thank you. BR, Pavel

### URL

https://www.home-assistant.io/integrations/qingping/

### Version

2022.9.1

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
