### ISSUE TITLE
Configurable time increments for schedule

### ISSUE THREAD

**Issue by boardyuk** [home-assistant/home-assistant.github.io#24078]
### Feedback

Absolutely love the new schedule helper, it's got rid around 6-8 other helpers used in automations already and still going.

What would be really nice is to have a configurable time increment for the schedules instead of just incrementing in 30min intervals, whether this is global or per helper I'm not sure, global would certainly work if individual overrides isn't possible.

Example - I have automations for switching on or off my kids TVs on school days to ensure they don't just sit around watching when they should be getting ready, or when they should be doing homework, etc. I'd like to be able to set maybe a 15min or 10min increment for these instead of 30min as the eldest is currently allowed to watch TV before bed for 10min longer than the youngest. I can't set that with the 30min intervals presently.

I may be missing something and this is already possible, however, I couldn't find it in the documentation or within the system.

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2022.9.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
