### ISSUE TITLE
BTHome request: Change number of digits

### ISSUE THREAD

**Issue by Mopfus** [home-assistant/home-assistant.github.io#24089]
### Feedback

BTHome does a great job! It works perfectly with my ATCs from Xiaomi. :

One Option is missing for me. If I use the [TelelinkMiFlasher.html of pvvx](https://github.com/pvvx/ATC_MiThermometer), the ATC is sending always two digits. This is not neccesary to show them (especially for relative humidity).
It is possible with the old way of using [passive BLE monitor](https://github.com/custom-components/ble_monitor), to change the shown number of digits. See here: https://custom-components.github.io/ble_monitor/configuration_params#decimals

It would be great to have such an option also with [BTHome](https://bthome.io). I could not find a way to do it there.
As BTHome is awesome, I want to switch from passiveBLEmonitor to BLHome for my setup.

Thank you in advance :-)

### URL

https://www.home-assistant.io/integrations/bthome/

### Version

2022.9.1

**Comment by Ernst79** [comment]
I've discussed it with the HA devs, but it is not common to add configurable precision in integrations. Sensor data should be reported as accurate as the sensor is, and can only be changed in the underlying library (for everybody). So I wont implement this request, unfortunately. 

As a workaround, you can use a template sensor, if you want less precision in the UI. 

BTW, you are addressing this issue to the documentation repository, normally you should address issues to the core repository.
