### ISSUE TITLE
Question about MQTT dimming value

### ISSUE THREAD

**Issue by jhbl** [home-assistant/home-assistant.github.io#24084]
### Feedback

I have set up a mqtt dimmer, but when I move the slider to the far left, the value shows "1" instead of "0". The switch status still shows the "on" state.
When I use the switch to turn off the light, the slider moves to the far left also, the value is also shown as "1", not "0".

```
 - name: "light_01"
   unique_id: living_room_light_01
   state_topic: "living_room/light_01/state"
   command_topic: "living_room/light_01/set"
   state_value_template: "{{ value_json.state }}"
   brightness_state_topic: "living_room/light_01/brightness/state"
   brightness_command_topic: "living_room/light_01/brightness/set"
   brightness_scale: 100
   payload_on: "on"
   payload_off: "off"
   icon: mdi:ceiling-light
   optimistic: false
   qos: 1
   retain: true
```

### URL

https://www.home-assistant.io/integrations/light.mqtt/

### Version

2022.8.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
