### ISSUE TITLE
LEDBLE failed to connect

### ISSUE THREAD

**Issue by Automot360** [home-assistant/home-assistant.github.io#24095]
### Feedback

2 Error Messages coming up:
No.1
LEDBLE-00BCD9 (BCD9)
Logger: led_ble.led_ble
Source: /usr/local/lib/python3.10/site-packages/led_ble/led_ble.py:649

LEDBLE-00BCD9: characteristic missing: Read characteristic missing; Stopping trying; RSSI: -60
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/led_ble/led_ble.py", line 637, in _send_command_while_connected
    await self._send_command_locked(commands)
  File "/usr/local/lib/python3.10/site-packages/led_ble/led_ble.py", line 585, in _send_command_locked
    await self._execute_command_locked(commands)
  File "/usr/local/lib/python3.10/site-packages/led_ble/led_ble.py", line 685, in _execute_command_locked
    raise CharacteristicMissingError("Read characteristic missing")
led_ble.exceptions.CharacteristicMissingError: Read characteristic missing

No.2
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 18:50:24 (1 occurrences)
Last logged: 18:50:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/led_ble/led_ble.py", line 567, in _execute_timed_disconnect
    await self._execute_disconnect()
  File "/usr/local/lib/python3.10/site-packages/led_ble/led_ble.py", line 579, in _execute_disconnect
    await client.stop_notify(read_char)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 851, in stop_notify
    raise BleakError("Characteristic {} not found!".format(char_specifier))
bleak.exc.BleakError: Characteristic None not found!

### URL

https://www.home-assistant.io/integrations/led_ble/

### Version

2022.9.2

### Additional information

LED Device Pairs with IOS App without any Problem.
It is unpaired for pairing with Home Assistant.

**Comment by bdraco** [comment]
Which device is this?  It doesn’t look like a supported one

**Comment by Automot360** [comment]
Thank you for answering.
I board this one for testing purpose:
Brand | LKELEC
Indoor/Outdoor Usage | Outdoor, Indoor
Light Source Type | LED
Power Source | Corded Electric
Product Site
https://www.amazon.com/dp/B08RS5CPYN?psc=1&ref=ppx_yo2ov_dt_b_product_details

**Comment by bdraco** [comment]
Looks like this one speaks a different protocol unfortunately so it won’t work

**Comment by Automot360** [comment]
OK thank you, will try another one, 
due you have a recommendation for a small device like this one?

**Comment by bdraco** [comment]
If you want a wifi one this will
Work with magic home Comoyda WiFi Led String Lights with Remote Control, RGB Color Changing Sliver Wire Starry USB Fairy Lights 33 Ft 100 Led, Waterproof Fairy Lights for Bedroom Party, Works with Alexa, Google Home https://a.co/d/1zaBJjj


Anything labeled happy lighting or tritones will likely work with led Ble if you want Bluetooth

**Comment by Automot360** [comment]
Alright thank you will try this one.

Thank you you for all your work on Home Assistant!
