### ISSUE TITLE
More detailed instruction of input fields "valid input" required

### ISSUE THREAD

**Issue by kohekohebigsky** [home-assistant/home-assistant.github.io#24119]
### Feedback

The instructions here state the obvious.
Then when you get to the last instruction
"Follow the instruction on screen to complete the set up."
This is why people have navigated to the help!
they need more explanation or examples of what is expected in the required fields!
there should be some rules or schema provided to show what qualifies as a valid input.
As a code writer, always put yourself in the shoes of your user!  Assume they know nothing, then your instructions will be helpful.

### URL

https://www.home-assistant.io/integrations/esphome/

### Version

2022.9.2

**Comment by frenck** [comment]
> they need more explanation or examples of what is expected in the required fields!

That is asked? Could you be more specific on what fields exactly causes confusion for you?

../Frenck

**Comment by kohekohebigsky** [comment]
HA-OS, bare metal install on HP290.  Integrations, Add Device, After the name is added, HOST* ?  Is this: Name given to device? Machine running ESP? (host), IP V4 address? Where do I find the "host" name?
In the ESP Help for this it does not give any examples,  Just says "Follow the instruction on screen to complete the set up."
This is not helpful.  Now I'm lost.
