### ISSUE TITLE
Update to say that this integration is broken as of 2022.7.x

### ISSUE THREAD

**Issue by Duke-Box** [home-assistant/home-assistant.github.io#24115]
### Feedback

This integration was broken by 2022.7.x and there is no solution as of 2022.9.x

### URL

https://www.home-assistant.io/integrations/bluetooth_tracker/

### Version

2022.6.7

**Comment by frenck** [comment]
This is not an documentation issue, issues with integrations can be reported in the Core issue tracker.

Thanks 👍 

../Frenck

**Comment by Duke-Box** [comment]
Hi Frank

So I think there is a misunderstanding.
I thought the documentation should reflect the fact that this integration
doesn't work since 2022.7.x
I think a user should know from the documentation that the integration is
broken.

I was not trying to report an issue.

Thanks Mike

**Comment by frenck** [comment]
An integration listed should work, if not, it should be reported and fixed.

**Comment by Duke-Box** [comment]
Franck,

But you know it doesn't work!
It is in your release notes for 2022.7.x that it is broken.
It is already reported
bluetooth_tracker doesn't work in 2022.7.x (not compatible with python
3.10) · Issue #75049 · home-assistant/core (github.com)
<https://github.com/home-assistant/core/issues/75049>
as an issue with bdraco saying this is caused by the adoption of python 3.10

I fail to understand why the documentation doesn't reflect this so I was
suggesting an update.
Why is this a problem?

Mike

**Comment by frenck** [comment]
We don't document issues, we have an issue tracker to track issues.

See my first response.

**Comment by Duke-Box** [comment]
This isn't a request to document an issue, it is a response to the "help us
to improve our documentation"

And to that end it would be helpful to document that the integration
doesn't work anymore, at the moment.

If I was a new user looking for classic bluetooth tracking and saw the
current documentation I would think it would work.
Isn't this request the same as your warning boxes that a certain part will
be depreciated ( i am thinking of the warning on known_devices.yaml that
has been there for years). I think a warning that this doesn't work as of
2022.7.x would be useful.
So i seem to disagree with you on what should be in the documentation
Mike

**Comment by buhito81** [comment]
> An integration listed should work, if not, it should be reported and fixed.

Clearly, it doesn't work as @Duke-Box writes. I second his motivation that as a new user one gets the impression that this is part of what HA offers - whereas this is clearly not working as of 2022.7.*

All the work that @bdraco is doing currently on Bleak is on/for BL**E** There currently isn't any supported bluethooth_tracker in HA as of 2022.7 and the **documentation doesn't reflect that**.

Respectfully @frenck , I _really don't understand_ what you are aiming at in this response. Some of us in this community might not be coding, but still putting in efforts to make it better - by suggesting changes to documentation and/or submitting issues.

**Comment by frenck** [comment]
I am not repeating myself. The issue can be reported. Please do so.

As a matter of fact, the integration will actually work on on a core installation type in a Python 3.9 venv (which is a supported official installation type).

If you have an issue, use the issue tracker. That is what is for.

**Comment by buhito81** [comment]
https://github.com/home-assistant/core/issues/75049#issuecomment-1181688762
Your own words: "We can't mitigate this issue. If you are using one of these integrations, these will no longer work. "

But since you seem to be aware of the issues; "the integration will actually work on on a core installation type in a Python 3.9 venv (which is a supported official installation type)" maybe you would be so considerate to take this issue/request as to update the documentation to reflect on which installation types it works and doesn't work.

As for the issue tracker; there are several issues registered for it: https://github.com/home-assistant/core/labels/integration%3A%20bluetooth_tracker

**Comment by frenck** [comment]
> We can't mitigate this issue

We can now.

> maybe you would be so considerate to take this issue/request as to update the documentation to reflect on which installation types it works and doesn't work.

> As for the issue tracker; there are several issues registered for I

Cool, please track those issues and feel free to contribute a fix.

../Frenck
