### ISSUE TITLE
Air demand

### ISSUE THREAD

**Issue by Beefycakerson** [home-assistant/home-assistant.github.io#24112]
### Feedback

Is there any way of force starting the "air demad"?

i.e. starting or running the fan without the the setpoint on thermostat being reached?

### URL

https://www.home-assistant.io/integrations/airzone/

### Version

2022.9.2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
