### ISSUE TITLE
Wake_on_lan switch not working anymore

### ISSUE THREAD

**Issue by teocannata** [home-assistant/home-assistant.github.io#24110]
### Feedback

I've a switch with wake_on_lan platform that is not working anymore.
How should I configure home assistant in order to have it back?

Thanks!
Matteo 

### URL

https://www.home-assistant.io/integrations/wake_on_lan/

### Version

2022.9.2

**Comment by teocannata** [comment]
Don't know why but HA renamed my entity, everything is working fine after a rename back to the old name.
Thanks!

**Comment by jktikka** [comment]
I still have this issue. The error on two WOL switches was "entity not provided by wake_on_lan" or something similar.

I tried completely removing the entity, restarting, then readding, but no luck.

Old WOL switches are just unavailable with nothing in the log, code under switch: in configuration.yaml below:
(This code has been working for nearly 3 years with no fuss)

`  - platform: wake_on_lan
    mac: A8-E3-59-65-1D-EA
    name: My PC
    host: 192.168.0.101
    broadcast_address: 192.168.0.255
    turn_off:
      service: script.turn_on
      entity_id: script.my_pc_shutdown`
