### ISSUE TITLE
Possible for scripts to update .yaml files?

### ISSUE THREAD

**Issue by loopy321** [home-assistant/home-assistant.github.io#24133]
### Feedback

Thanks for the updates and hard work! 

I was curious if it would be possible to have a script propose updates to the .yaml files that user could accept or amend accordingly to stay current with the changes.  

I have a lot of mqtt sensors and a couple of climates and this would be very helpful!

Thanks for considering!

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2022.9.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
