### ISSUE TITLE
Cannot find grid consumption entity

### ISSUE THREAD

**Issue by AdamWoodward22** [home-assistant/home-assistant.github.io#24138]
### Feedback

Hi, I’m trying to set up the Energy tab in my home assistant. When I click on the drop down tab for grid consumption or grid return the only entity that appears is ‘inverter daily generation’. I have a Sungrow SG5K-D inverter which is currently displaying all values in the ‘Sensor’ section of my main overview through the ModbusTCP2MQTT add on. Sensors available are inverter import, export, load and power meter. 

### URL

https://www.home-assistant.io/more-info/statistics/

### Version

2022.9.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue about a third-party add-on (ModbusTCP2MQTT), however, you have submitted documentation feedback instead. It's best to open an issue on the add-on repository, you may already find your answer in the old issues there 😉 

Thanks! 👍

./Klaas
