### ISSUE TITLE
Enhancement proposal

### ISSUE THREAD

**Issue by mmick08** [home-assistant/home-assistant.github.io#24139]
### Feedback

Hi Guys,
as the Gas part in general can be used for different fuels would it be possible to grant some more units like f.e. kg, lb, liters, ...
The section than can be used also for example for Wood Pellets, Wood, Oil and many more... 
This would satisfy the needs of many users I think, several Feature requests went into the community already.

To round this up it would maybe be an idea to rename Gas to Fuel.

Regards

### URL

https://www.home-assistant.io/docs/energy/gas/

### Version

2022.9.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
