### ISSUE TITLE
HOME ASSISTANT AUTOMATION DOCUMENTATION IS NOT GOOD

### ISSUE THREAD

**Issue by RabidWombatz** [home-assistant/home-assistant.github.io#24145]
### Feedback

I have tried to develop a bunch of basic automations for when my solar power generation exceeds certain values. the information around numeric is utterly misleading and no good example exists. 
I am using the in-app, not YAML or code, just the "easy" method. why? because I can't work out where to put code and blueprints didnt work easily and no blueprints on the linked forum were close anyway.

Such a basic thing!!! if a numercail value is exceeded, do something. no, after 10 attempts and variations and reading for HOURS nothing. 

very disappointed.
Id ask for my money back but its all blood sweat and my tears.

### URL

https://www.home-assistant.io/docs/automation/

### Version

2022.9.4

**Comment by frenck** [comment]
This sounds more like frustration than actual constructive feedback. Especially witnessing the all-caps title (which is considered shouting).

Therefore closing this feedback.

Please note, we have quite a big community (forums, Discord chat, Facebook groups, Subredits) that can help you out and for asking questions. If you figured out what is actually wrong, we are happy to receive a concrete suggestion on how to improve documentation (feel free to edit the documentation, everybody can edit and improve it).

../Frenck
