### ISSUE TITLE
Mention Zuidwijk's Slimmelezer

### ISSUE THREAD

**Issue by thibaultmol** [home-assistant/home-assistant.github.io#24152]
### Feedback

There are a bunch of diy solutions listed on the documenation page, yet the device from Zijdwijk seems like the best one yet it's not even mentioned

https://www.zuidwijk.com/product/slimmelezer-plus/

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2022.9.4

**Comment by thibaultmol** [comment]
It's still relevant, and probably just one line of text on documentation.

**Comment by frenck** [comment]
It is mentioned, we promote it from another part of the website here:

<https://www.home-assistant.io/docs/energy/electricity-grid/#hardware>

The reason it is no in this specific list is that we recommend using it with ESPHome (which does not use the integration you left a comment on).

../Frenck
