### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by circlotron** [home-assistant/home-assistant.github.io#24157]
### Feedback

In Install Home Assistant Core, there is a missing dependency for rustc (python crypto needs it)

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.9.4

**Comment by frenck** [comment]
That depends on the OS and setup you are using. As per warning on the installation method you are using:

![CleanShot 2022-09-17 at 10 27 38](https://user-images.githubusercontent.com/195327/190847852-60de7b8f-416c-426a-84bd-74ca075fb72e.png)
