### ISSUE TITLE
Adding a little bit more information about tags

### ISSUE THREAD

**Issue by SeraphicRav** [home-assistant/home-assistant.github.io#24168]
### Feedback

Hello!

I think rhat the documentation should mention that when using a phone as a **NFC** tag reader, it needs Home Assistant installed (from what I understood). Also mentioning if an account in Home Assistant is necessary or not.

What do you think?

Best regards 

### URL

https://www.home-assistant.io/integrations/tag/

### Version

2022.9.4

**Comment by frenck** [comment]
> I think rhat the documentation should mention that when using a phone as a tag reader, it needs Home Assistant installed (from what I understood). 

No?

> Also mentioning if an account in Home Assistant is necessary or not.

No, should not be needed.

I feel like you are suggesting X by are struggling with Y (something different). That causes this feedback to be raised.

../Frenck

**Comment by SeraphicRav** [comment]
Sorry, let me detail.

I made an NFC tag using the Tag feature from the companion app from a Google Pixel 3.
I asked a friend with the same phone model to scan the NFC to trigger a dumb automation I wanted him to trigger. Instead, it prompted to install the companion app. I believe that people using Home Assistant in their daily life might accept to install it, but not people just passing by. This is the reason I asked to add the fact that the app is necessary as a pre requisite.

I removed Home Assistant companion app to check what was needed and as @frenck said, no account is needed for the NFC tag but the companion app seems necessary.

**Comment by frenck** [comment]
> This is the reason I asked to add the fact that the app is necessary as a pre requisite.

It depends on that tag used I guess. Or maybe a limitation of the phone? I can make a QR code as a tag that is just scannable by anybody without apps.

Maybe it is an issue of the companion app?

**Comment by SeraphicRav** [comment]
> It depends on that tag used I guess. Or maybe a limitation of the phone? I can make a QR code as a tag that is just scannable by anybody without apps.

Cannot really tell, I could make another NFC to share wifi settings using another app, that one does not need an application to be usable. 

> Maybe it is an issue of the companion app?

No idea.

I hope that someone can provide more information about this.

**Comment by SeraphicRav** [comment]
I mentioned NFC in the description of the request as QR seems to not have problems.

**Comment by frenck** [comment]
Both are just "tags". Anyways, in all cases you end up on:

https://www.home-assistant.io/tag/

Which describes your cases already?

**Comment by SeraphicRav** [comment]
"For NFC tag readers on Android, the companion app is necessary" is worth mentioning in the documentation, I believe.

The current documentation says
> Our mobile apps work out of the box with NFC tags, but anything that can read IDs from something can be used.

**Comment by frenck** [comment]
That is what it states?

Sorry, I really don't want to troll (I feel that it might come across as such at this point). But it literally states:

![CleanShot 2022-09-19 at 09 27 16](https://user-images.githubusercontent.com/195327/190968803-e8586959-0854-4856-83c2-11c9fd0ddacf.png)

**Comment by SeraphicRav** [comment]
@frenck I think, we just keep on misunderstanding each other.

The page you linked is shown when a tag is already set up and when using it (am I correct?).

I am talking about https://www.home-assistant.io/integrations/tag/. This page is describing the tag feature and is accessible from the list of integrations (so usually at the ideation level). I think it would be better for people to know the limitations about tags (the need to install the application) BEFORE using the feature, not discovering the limitation after setting it up and then testing with someone else phone.

**Comment by SeraphicRav** [comment]
Sorry for insisting but if my issue does not seem pertinent, it is OK to close it.
