### ISSUE TITLE
QVR Pro integration is not working

### ISSUE THREAD

**Issue by Milan1989** [home-assistant/home-assistant.github.io#24160]
### Feedback

My QVR Pro integration is not working.

QTS version: QTS 5.0.1.2145
QVR Pro version: v.2.2.0.0

Home Assitant LOG:
Logger: homeassistant.components.qvr_pro.camera
Source: components/qvr_pro/camera.py:108
Integration: QVR Pro (documentation, issues)
First occurred: 2022. szeptember 16. 09:19:49 (4 occurrences)
Last logged: 10:02:47

Error getting image: {'{\n"success":false,\n"error_code":-1325400063\n"error_message":"Authorization failed"\n}\n': '{\n"success":false,\n"error_code":-1325400063\n"error_message":"Authorization failed"\n}\n'}

### URL

https://www.home-assistant.io/integrations/qvr_pro/

### Version

2022.9.4

### Additional information

If you need any further information please contact me.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
