### ISSUE TITLE
pushover broken, "Failed to connect"

### ISSUE THREAD

**Issue by bmcgair** [home-assistant/home-assistant.github.io#24164]
### Feedback

Hmm... pushover worked for years, but now its broken inin  configuration.yaml, with some cryptic message saying that my configuration has been imported automatically, when it hasn't, and then the pushover integration doesn't work with the same values. All I get when I enter my api and user keys are "Failed to connect".

### URL

https://www.home-assistant.io/integrations/pushover/

### Version

2022.9.4

**Comment by bmcgair** [comment]
<img width="610" alt="Screen Shot 2022-09-17 at 10 21 03 PM" src="https://user-images.githubusercontent.com/468193/190886995-4d0ad45d-59a3-4fe3-91c7-793059991db2.png">

**Comment by bmcgair** [comment]
<img width="401" alt="Screen Shot 2022-09-17 at 10 22 03 PM" src="https://user-images.githubusercontent.com/468193/190887022-48b3cbf3-9989-4eda-a01b-e19b5459923c.png">

**Comment by frenck** [comment]
Hi there @bmcgair 👋 

It seems like you wanted to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
