### ISSUE TITLE
Impossible to change IP socket address of ZHA zigbee bridge?

### ISSUE THREAD

**Issue by avviano** [home-assistant/home-assistant.github.io#24182]
### Feedback

Why is it not possible to change the IP Socket address of my Zigbee Bridge within ZHA? I got a new router and now I am stuck with a bridge and 20 zigbee devices not being recognized. This is a real nightmare!!!!

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2022.9.5

**Comment by frenck** [comment]
Thank you for reaching out.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
