### ISSUE TITLE
system resources

### ISSUE THREAD

**Issue by vijghph** [home-assistant/home-assistant.github.io#24180]
### Feedback

I think it would be worth indicating what is the recommended system resources to run Home Assistant in a Docker container.

I have a Synology 412+ equipped with only 1Gb of RAM in hardware and I suspect it is insufficient to preserve decent NAS performance, isn't it?

### URL

https://www.home-assistant.io/installation/alternative/

### Version

2022.9.5

**Comment by frenck** [comment]
It all depends on what you run with it / on it / do with it.
Home Assistant will run fine on a Raspberry Pi3 even, and some still run it on a Raspberry Pi2.
Your system sounds more than capable.

../Frenck
