### ISSUE TITLE
The first 'easy' option disables your existing PI OS!

### ISSUE THREAD

**Issue by CJerard** [home-assistant/home-assistant.github.io#24198]
### Feedback

I tried the "if you have little to no Linux experience" option - at least that one will automatically install dependencies etc I thought (Install Home Assistant Core in a py venv gave me a couple of headaches and no working HA). It turns out after starting the pi with HA added, I can't use my original PI OS anymore. Is it gone? No idea, it seems I do need Linux experience to figure that one out.
"installing home assistant" sounds like adding it to the PI OS, which is probably a misinterpretation on my part.
Experience or not, why doesn't the page tell us the current OS will be removed/disabled? One could argue the title clearly contains 'Operating System', but it doesn't say you'll replace the current OS, it doesn't tell us to NOT use an SD you still need or contains the PI OS. For a section 'for dummies' this type of info should be there at least once.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2022.9.5

**Comment by klaasnicolaas** [comment]
When you flash the Home Assistant OS to your SD card, you will get a message in Balena Etcher that existing files on the SD card will be deleted. So you overwrite everything that was on your SD card with the new OS and that is more than logical 🤷🏻

**Comment by CJerard** [comment]
Sure, but it doesn't hurt telling novices what will happen, right? Similar to the powersupply warning for example, special box on top of the section. After all, that novice section is for people who are most likely not 100% sure what they are doing.

The page asks for feedback to improve info. Well, here is some feedback. My PI is just a playground, all I lost is some time.

**Comment by klaasnicolaas** [comment]
Of course we are very happy with your feedback, it also shows us what users encounter. Maybe we can indicate in step 4 that users will get a popup and if they agree, the SD card will be erased and HA OS will be installed 🤔
