### ISSUE TITLE
VZlogger in Home Assistant

### ISSUE THREAD

**Issue by domerich** [home-assistant/home-assistant.github.io#24192]
### Feedback

Hi guys, this all works well but how can I get the current power readings out of my volkszähler?

monitored_conditions:
- current power? 

### URL

https://www.home-assistant.io/integrations/volkszaehler/

### Version

2022.9.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or check the [Community forum](https://community.home-assistant.io/) whether your answer may be found there.

Thanks! 👍
