### ISSUE TITLE
KNX climate preset mode - docs unclear how to set a mode using a service/automation

### ISSUE THREAD

**Issue by dotsoltecti** [home-assistant/home-assistant.github.io#24190]
### Feedback

The docs indicate that 5 preset modes are available:

- Auto (maps internally to PRESET_NONE within Home Assistant)
- Comfort (maps internally to PRESET_COMFORT within Home Assistant)
- Standby (maps internally to PRESET_AWAY within Home Assistant)
- Night (maps internally to PRESET_SLEEP within Home Assistant)
- Frost Protection (maps internally to PRESET_ECO within Home Assistant)

The documentation however fails to indicate what the right value is to set the value when using the service 'climate.set_preset_mode'. The errors in the log-files are not helpful. The only acceptable **lowercase values** seem to be: 'none', 'comfort', 'away', 'sleep' and 'eco'. It might be helpful to indicate these values in the documentation.

### URL

https://www.home-assistant.io/integrations/knx/#climate

**Comment by marvin-w** [comment]
Good point. Do you maybe want to update the docs and open 
a PR?

**Comment by farmio** [comment]
Imho using a climate entities `set_preset_mode` service is not specific to the Knx climate integration and should thus be documented here <https://www.home-assistant.io/integrations/climate/#service-climateset_preset_mode>. 
The mapping is just a hint because of the different naming in Knx and HA for users to find the correct preset mode (in UI or for automation).

**Comment by dotsoltecti** [comment]
I've created a pull request. I get your point that the climate.preset_mode could use some clarification as well. Since the mapping within HA differs from what is expected within KNX, in my opinion the docs should contain rather clear instructions (instead of just a hint) how this works in HA.

**Comment by farmio** [comment]
Great, thanks! 👍
