### ISSUE TITLE
Instruction incorrect

### ISSUE THREAD

**Issue by hnkmlndks** [home-assistant/home-assistant.github.io#24194]
### Feedback

Under configuration it reads
The preferred way to configure input boolean helpers is via the user interface, in which they are known as Toggle Helpers. To add one, go to [Settings -> Devices & Services -> Helpers](https://my.home-assistant.io/redirect/helpers)

 -> Devices & Services ->
should be replaced with 
->  Automation & Scenes ->

### URL

https://www.home-assistant.io/integrations/input_boolean/

### Version

2022.9.5

**Comment by N1co93** [comment]
Why should "Devices & Services" replaced by "Automation & Scenes"?
The documentation seems to be correct for me, you will find the helpers under "Settings -> Devices & Services -> Helpers"

![image](https://user-images.githubusercontent.com/59510296/193430959-4f956c65-6ab6-4633-94f1-d2aba4eefbc2.png)
