### ISSUE TITLE
S3 Hub Support

### ISSUE THREAD

**Issue by Lordeds** [home-assistant/home-assistant.github.io#24205]
### Feedback

When will this support S3 hub?

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2022.9.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
