### ISSUE TITLE
Cannot read Celsius and Fahrenheit properly 

### ISSUE THREAD

**Issue by DaiZack** [home-assistant/home-assistant.github.io#24217]
### Feedback

It reads Fahrenheit from my thermostats but shows Celsius. And I don't have a way to convert it.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/45176371/191863845-fd8711da-1edf-4723-88c7-30f26cdd1d30.png">
<img width="317" alt="image" src="https://user-images.githubusercontent.com/45176371/191864001-046b4161-1a4a-4c5a-800f-b990dd044431.png">

### URL

https://www.home-assistant.io/dashboards/thermostat/

### Version

2022.9.6

**Comment by ikifar2012** [comment]
Should we add a note to this page?
The thermostat uses the unit system defined in your configuration
![image](https://user-images.githubusercontent.com/20800434/194778994-d71ddf58-c848-4691-8ee3-8a17e1245257.png)
