### ISSUE TITLE
Unable to configure or obtain local access key as described.

### ISSUE THREAD

**Issue by imthefrizzlefry** [home-assistant/home-assistant.github.io#24218]
### Feedback

Regarding the configuration, I think it is important to note that Home Assistant MUST detect the bluetooth device before the user is able to add the integration manually.  This threw me off for the first couple of days because I would repeatedly get a message indicating `No unconfigured devices found.` However, after Home Assistant notified me that it found the bluetooth device, I was able to open the add integration flow.

I believe there must be something missing from the section on Obtaining the offline key.  It is unclear how I could get the key from the Yale/August cloud steps, the iPhone steps don't indicate the file I am looking for, and on a rooted Android device I have not been able to get the com.august.luna folder to be created.

At this point, I have spent a couple days working on each of the listed methods to get the offline key, but I have not been able to find it.  Any help would be greatly appreciated!

### URL

https://www.home-assistant.io/integrations/yalexs_ble/

### Version

2022.9.6

**Comment by homeassistant** [comment]
Hey there @bdraco, mind taking a look at this feedback as it has been labeled with an integration (`yalexs_ble`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L716) for? Thanks!
