### ISSUE TITLE
Error in Insteon scene YAML example

### ISSUE THREAD

**Issue by casamtl** [home-assistant/home-assistant.github.io#24227]
### Feedback

Your example for triggering an Insteon scene needs to be corrected (missing 'data:' line). Took me a while to figure out the problem.

automation:
  # Trigger an INSTEON scene 25
  - id: trigger_scene_25_on
    alias: "Turn on scene 25"
    action:
      - service: insteon.scene_on
        **data:
          group: 25**

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2022.9.6

**Comment by homeassistant** [comment]
Hey there @teharris1, mind taking a look at this feedback as it has been labeled with an integration (`insteon`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L297) for? Thanks!
