### ISSUE TITLE
Rename docs for "ZHA" / "Zigbee Home Automation" integration to read just "Zigbee"?

### ISSUE THREAD

**Issue by Hedda** [home-assistant/home-assistant.github.io#24224]
### Feedback

For reference, similar integration rename was recently done by zsarnett for Z-Wave JS -> https://github.com/home-assistant/home-assistant.io/pull/23382 and https://github.com/home-assistant/core/pull/75136

Now suggest renaming "ZHA" / "Zigbee Home Automation" integration in the docs to read just "Zigbee" (preferably also UI too).

https://www.home-assistant.io/integrations/zha

![image](https://user-images.githubusercontent.com/6320001/191931791-4ab15cbf-c963-4eb8-8a71-7235aeef65c7.png)

The name "Zigbee" only name should also be reflected in the analytics listing:

https://analytics.home-assistant.io/#integrations

That would be similar to how the "Z-Wave JS" integration was recently renamed/rebranded in Home Assistant to just "Z-Wave":

https://www.home-assistant.io/integrations/zwave_js/

![image](https://user-images.githubusercontent.com/6320001/191929862-420c8a61-497e-4826-a7bb-e226b62e93ea.png)

PS: For reference, the history behind the name "ZHA" and "Zigbee Home Automation" actually came from the old Zigbee 1.2 specification which had/have a specification standard called "Zigbee Home Automation" which is/was abbreviated to "ZHA" and was taken up by the Home Assistant's ZHA integration as a name when it only supported that specific Zigbee specification standard, but that is not really valid any longer as Home Assistant's ZHA integration now also support other specification standards included in Zigbee 3.0

### URL

https://www.home-assistant.io/integrations/zha

### Additional information

Also see similar name change https://github.com/home-assistant/home-assistant.io/pull/23382 and https://github.com/home-assistant/core/pull/75136 by @zsarnett

**Comment by Hedda** [comment]
Also see matching suggestion to change name of `Zigbee Home Automation` to be called `Zigbee` in zha for Home Assistant core:

https://github.com/home-assistant/core/issues/78992

**Comment by frenck** [comment]
Docs reflect integration changes. The integration is called ZHA at this point.

Closing the issue, as it is not documentation related.
