### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by eddiex666** [home-assistant/home-assistant.github.io#24233]
### Feedback

Logger: bimmer_connected.api.authentication
Source: components/bmw_connected_drive/config_flow.py:42
First occurred: 23. september 2022, 19:42:04 (4 occurrences)
Last logged: 10:44:46

Authentication error (invalid_client): Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2022.9.6

**Comment by eddiex666** [comment]
tryed to reset password many times, the MyBMW app is now working.
Hass, Homey and OpenHAB is NOT working..

has BMW done something to awoid smarhouse integrations?

**Comment by klaasnicolaas** [comment]
Hi there @eddiex666 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
