### ISSUE TITLE
Working example of counter incrementing using an if statement

### ISSUE THREAD

**Issue by darazi** [home-assistant/home-assistant.github.io#24230]
### Feedback

There is currently a non-working example of incrementing a variable outside its scope using an if statement. 
There is no example of how one would define a default value then increment it using an if statement. 

Thanks!

### URL

https://www.home-assistant.io/docs/scripts/

### Version

2022.9.6

**Comment by homeassistant** [comment]
Hey there @home-assistant/core, mind taking a look at this feedback as it has been labeled with an integration (`script`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L531) for? Thanks!
