### ISSUE TITLE
Installation of missing packages in Home Assistant Supervised

### ISSUE THREAD

**Issue by garbast** [home-assistant/home-assistant.github.io#24238]
### Feedback

For supervised the installation of missing packages is not

`sudo apt-get install libxml2-dev libxslt1-dev zlib1g-dev`

but instead you need to use

`apk add libxml2-dev libxslt-dev zlib-dev`

### URL

https://www.home-assistant.io/integrations/caldav/

### Version

2022.9.6

**Comment by ludeeus** [comment]
The only supported Supervised OS is Debian, `apk` does not exist there.

**Comment by garbast** [comment]
I dont want to be rude, but what version do i have here? I have to use apk to install packages.

`
| |  | |                          /\           (_)   | |            | |
| |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
|  __  |/ _ \| '_ \ _ \ / _ \   / /\ \ / __/ __| / __| __/ _\ | '_ \| __|
| |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_
|_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|

Welcome to the Home Assistant command line.

System information
  IPv4 addresses for enp0s3: 192.#######/24
  IPv6 addresses for enp0s3: fe80:######/64

  OS Version:               Home Assistant OS 9.0
  Home Assistant Core:      2022.9.6

  Home Assistant URL:       http://homeassistant.local:8123
  Observer URL:             http://homeassistant.local:4357
`

**Comment by ludeeus** [comment]
That is Home Assistant Operating System (not Supervised).
That OS does not have a package manager at all, so if you used APK you installed something I a container.
That will not be kept and is not how you add packages, and not something we should document.

If you have an issue with this integration using the OS, open an issue here <https://github.com/home-assistant/core/issues/new?labels=integration:%20caldav&template=bug_report.yml>

**Comment by garbast** [comment]
Thanks for clarifying that. I will change my installation to supervised, to be more flexible.

**Comment by frenck** [comment]
> I will change my installation to supervised, to be more flexible.

Those commands and instructions would still not apply to Supervised installation methods. The OS, Supervised & Container installation methods all use the same Docker containers to run Home Assistant.

Please be sure to dive into the difference in installation methods and be sure you know what you are doing before choosing one. Supervised is by far the most complicated installation method we have.

If the above package managers stuff already didn't ring a bell (and don't get me wrong, I'm not trying to be mean), I'm pretty sure running and maintaining a Supervised installation will become a pain for you in that case.
