### ISSUE TITLE
Lyric Integration Hard Coded URL

### ISSUE THREAD

**Issue by boriken72** [home-assistant/home-assistant.github.io#24244]
### Feedback

Spend many hours trying to figure this out -docs should be updated unless the integration is fixed

The app is hardcoded to use "https://my.home-assistant.io/redirect/oauth "

<img width="601" alt="image" src="https://user-images.githubusercontent.com/24843834/192170764-cd227984-3453-4959-bdff-f3dd763d14da.png">

so this is what you must use when you configure it in the "app" at the Honeywell developer page.

In home assistant when you go to add the integration it will take you to the home assistant login page:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/24843834/192170804-8b4129e7-a745-4ecc-b109-dd2dd78ba764.png">

Changing the URL to be your local url (http://your-local-home-assistant-url:8123/) and it will continue to do the auth. You then log into the page with your phone app credentials and it will connect.

### URL

https://www.home-assistant.io/integrations/lyric/

### Version

2022.9.6

**Comment by homeassistant** [comment]
Hey there @timmo001, mind taking a look at this feedback as it has been labeled with an integration (`lyric`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L356) for? Thanks!

**Comment by timmo001** [comment]
This is part of Home Assistant's default oauth strategy

https://www.home-assistant.io/integrations/lyric/#setup

**Comment by frenck** [comment]
> docs should be updated unless the integration is fixed

> The app is hardcoded to use "[my.home-assistant.io/redirect/oauth](https://my.home-assistant.io/redirect/oauth) "

Well, that is exactly what is written in the docs:

![CleanShot 2022-09-26 at 16 53 36](https://user-images.githubusercontent.com/195327/192309666-3341dacb-7cf3-48c4-99f1-8af9335becfe.png)

**Comment by boriken72** [comment]
I fall under “I have manually disabled my home assistant” 

 
![image](https://user-images.githubusercontent.com/24843834/192312494-a57a518f-987b-4caf-a94b-dc826d7353ab.png)



 

and those instructions DO NOT WORK – it only works with  "my.home-assistant.io/redirect/oauth <https://my.home-assistant.io/redirect/oauth>  "

**Comment by boriken72** [comment]
Yes but issue is there are two ways to provision “automatic” if you have “My Home Assistant” enabled and manual if you have this disabled:

 



 

The latter doesn’t work – it is hard coded to the "my.home-assistant.io/redirect/oauth <https://my.home-assistant.io/redirect/oauth>  "

**Comment by frenck** [comment]
> it is hard coded to the "my.home-assistant.io/redirect/oauth

Only when the My Home Assistant integration is active, otherwise it falls back to what is described in the documentation. This is tested and confirmed working.

For more information on the My integration, see: <https://www.home-assistant.io/integrations/my>

You can check if the integration is active on your instance, by going to:

Settings -> System -> Repairs, next in the top right click the three dots and click on "Integration startup time" from the menu.

You will be presented with all internals loaded by Home Assistant (sorted by startup time). If your system redirects you to `https://my.home-assistant.io/redirect/oauth`, "My Home Assistant" will be your list of integrations loaded and thus active.

../Frenck

**Comment by boriken72** [comment]
I struggled with this for 2 days and can most definitely tell you that it’s not working as I disabled “My Home Assistant” when I built my server.  

 

When I go to Settings -> System -> Repairs, next in the top right click the three dots and click on "Integration startup time" from the menu I am not redirected it stays at my local url.

 

The reason I had to follow the path I documented was because I kept getting a ‘{"code":400, "message":"The redirect URL provided does not match the redirect URL registered for the app."}

 

When I looked at the URL on the error page it had the  “https://my.home-assistant.io/redirect/oauth” embedded in the url not the one I had actually configured on the Honeywell lyric page app page which was set to the internal url for my home assistant installation.  

 

It was not until I changed it to be the hardcoded url (https://my.home-assistant.io/redirect/oauth) on the Honeywell Lyric page that it tried to redirect me to the local “My HomeAssistant” login page, which of course does not work because I have this disabled, where I manually changed the login url to be that of my local instance IP and then the integration finally took.

 

 

--Juan

**Comment by frenck** [comment]
> When I go to Settings -> System -> Repairs, next in the top right click the three dots and click on "Integration startup time" from the menu I am not redirected it stays at my local URL

? I think you are not reading what I wrote. Therefore I cannot help you any further.

**Comment by boriken72** [comment]
My Home assistant is not loaded – I simply misread what you were implying. 

 

This integration is working but you are by far the most unprofessional person I’ve ever had the displeasure of working with.  

 

While I am appreciative of the work you are doing it doesn’t give you the right to talk down to people who are simply seeking your assistance, or even trying to help improve the user experience so others do not go through the same pain.

 

You can close this as I will not need any further assistance from you since I figured out how to work around the incorrectly hard coded address in the app.

 

--Juan

**Comment by frenck** [comment]
> My Home assistant is not loaded – I simply misread what you were implying.

Sorry, the integration doesn't handle this, but Home Assistant handles that. It only does this behavior when the `my` integration is loaded. This is a tested scenario (covered by automated tests).

> You can close this as I will not need any further assistance from you since I figured out how to work around the incorrectly hard coded address in the app.

It isn't hardcoded, if the `my` integration is not loaded. See:

https://github.com/home-assistant/core/blob/c777e8592cdd1957da85f6d41b7a283add834cff/homeassistant/helpers/config_entry_oauth2_flow.py#L133-L134

> While I am appreciative of the work you are doing it doesn’t give you the right to talk down to people who are simply seeking your assistance,

You might mistake the place you are, you have submitted feedback on our documentation. If you are looking for support, please try our community forums or our Discord chat. Despite you being in the wrong place, I still tried to give pointers. Responses like yours taught me not to do that again and just close the issue without help next time. As it can only bite me.

> This integration is working but you are by far the most unprofessional person I’ve ever had the displeasure of working with.

Wow, ok. Good luck in that case.

../Frenck
