### ISSUE TITLE
docker[minus]compose up -d

### ISSUE THREAD

**Issue by stefanfrena** [home-assistant/home-assistant.github.io#24240]
### Feedback

shouldnt it be "docker-compose up -d" instead of "docker compose up -d" in the documentation?

### URL

https://www.home-assistant.io/installation/alternative/

### Version

2022.9.6

**Comment by klaasnicolaas** [comment]
`docker-compose` comes from v1.0 and `docker compose` works from v2.0 and higher.

See also: https://www.docker.com/blog/announcing-compose-v2-general-availability/
