### ISSUE TITLE
Webex Notify does not work

### ISSUE THREAD

**Issue by 404frank** [home-assistant/home-assistant.github.io#24242]
### Feedback

Hi, I'm trying to get the webex integration implemented but do always receive "Unable to find service notify.webex"

Should it work in general? 

I'm using the same credentials from the FHEM integration, which works. A bit wondering that the BOT-ID is not used here. 

Here my integration:
    notify:
  - name: webex
    platform: cisco_webex_teams
    token: N2E1Y2Q5NDItOWRmNy00ODhiLThiYWUtZTdjN2RmMzlmMmZjY2MzOTI5YmYtMzYx_PF84_2c70dfba-2017-4ac8-xxxxxxxxxxxx
    room_id: 5de3c28c-f33f-473d-14ee-d8f22211xxxxxxxx

******
action:
  - service: notify.webex
    data:
      message: Hallo World

Thanks,
Frank

### URL

https://www.home-assistant.io/integrations/cisco_webex_teams/

### Version

2022.9.6

**Comment by klaasnicolaas** [comment]
Hi there @404frank 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by 404frank** [comment]
Many thanks Klaas. I opened an issue. But may we can also adjust the
manuell to be more precise. A bit confused as I describe in the opened
issue. Thanks for your help.

Regards,
Frank

Am So., 25. Sept. 2022 um 21:07 Uhr schrieb Klaas Schoute <
***@***.***>:

**Comment by klaasnicolaas** [comment]
Depends on what you mean with 
> adjust the manuell to be more precise

As far as I can judge now, this issue belongs in the core repository 🤷🏻‍♂️
