### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Lordakis** [home-assistant/home-assistant.github.io#24252]
### Feedback

Although I have the latest version of HA the below message appears 

 Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @cmroche, mind taking a look at this feedback as it has been labeled with an integration (`gree`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L243) for? Thanks!

**Comment by frenck** [comment]
I cannot reproduce this, when I click the link, it actually works and tries to set up the Gree integration.

Are you using a custom integration for Gree?

../Frenck
