### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by AndySymons** [home-assistant/home-assistant.github.io#24254]
### Feedback

Usually there is a section on installing an integration, but not here. 'proximity' is not found in the standard integrations 

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2022.9.7

**Comment by frenck** [comment]
See: <https://www.home-assistant.io/integrations/proximity/#configuration-variables>

![CleanShot 2022-09-27 at 00 21 20](https://user-images.githubusercontent.com/195327/192390892-c4fe82fb-2e34-4038-9f97-0597240fcbd5.png)

This is a manual integration, that you need to configure by adjusting the YAML configuration.

../Frenck
