### ISSUE TITLE
SMTP notify not visible in Developer Tools

### ISSUE THREAD

**Issue by Lahim26** [home-assistant/home-assistant.github.io#24258]
### Feedback

I made  two configs but none of them is visible in DevTools.
There is just notify.notify
notify:
  - name: tes
    platform: smtp
    server: ********
    port: 465
    timeout: 15
    sender: ********
    #encryption: starttls
    username: ********
    password:********
    recipient: ********
    sender_name: test
    verify_ssl: true
    
  - name: "test2"
    platform: smtp
    server: ********"
    port: 465
    timeout: 15
    sender: "********"
    #encryption: starttls
    username: "********"
    password: "********"
    recipient: "********"
    sender_name: "test2"
    verify_ssl: true

### URL

https://www.home-assistant.io/integrations/smtp/

### Version

2022.9.7

**Comment by frenck** [comment]
Hi there @Lahim26 👋 

It seems like you want to report an issue with a Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
