### ISSUE TITLE
Could you clarify a bit on the -- backup on the downgrade, please

### ISSUE THREAD

**Issue by greyhound3** [home-assistant/home-assistant.github.io#24253]
### Feedback

I downgraded to 2022.9.6 but what does this sentence mean, i think, i can read it but i do not understand it:
"The --backup flag here ensures that you have a partial backup of your current setup incase you need to downgrade." ?
does this mean
"The --backup flag here makes a partial backup of your current setup before you install another version. It may work on another version or not, but just do be (a little more) save" ??

### URL

https://www.home-assistant.io/common-tasks/os/

### Version

2022.9.7

**Comment by frenck** [comment]
> I downgraded to 2022.9.6 but what does this sentence mean

You should not downgrade using that CLI. The command examples are meant for upgrading (`--backup` creates a backup before upgrading).

If you need to downgrade, please restore a previously created backup.

../Frenck

**Comment by greyhound3** [comment]
Your info 
" (--backup creates a partial backup before upgrading)." is more explorative than 
"The --backup flag here ensures that you have a partial backup of your current setup incase you need to downgrade."
"creates/makes" >better than>  "ensures that you have"
OK, can be closed, thank you. My lights are working again.
And thank you very much for answering to quickly :)
