### ISSUE TITLE
weak search engine

### ISSUE THREAD

**Issue by Reynders1** [home-assistant/home-assistant.github.io#24259]
### Feedback

Since the beginning, I have been struggling finding information in the documentation. Although I know it is available, many things cannot be found from the search function. Unless you spend time surfing the website or get the direct link, you won't find it. The last example I got was with the keyword "schedule". This is what you find:
<img width="504" alt="Screenshot 2022-09-27 at 17 18 32" src="https://user-images.githubusercontent.com/44923513/192566940-d1f9b237-043f-401b-a7a4-032b4de5ef94.png">
I was lucky enough to see find the shortcut in the community: [https://www.home-assistant.io/integrations/schedule/](url)
There are a many more examples like that one.

Am I missing something to make best use of your very comprehensive documentation?

Kind regards.

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @home-assistant/core, mind taking a look at this feedback as it has been labeled with an integration (`schedule`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L527) for? Thanks!

**Comment by homeassistant** [comment]
Hey there @epenet, mind taking a look at this feedback as it has been labeled with an integration (`renault`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L503) for? Thanks!

**Comment by Reynders1** [comment]
This has nothing to do with the renault integration. Instead, this is a more generic issue for the documentation.
Sorry for the confusion;
