### ISSUE TITLE
MQTT integration documentation feedback

### ISSUE THREAD

**Issue by cmoore42** [home-assistant/home-assistant.github.io#24263]
### Feedback

Under "Manual configuration steps" it just says to use the UI and add the integration.
The next paragraph says that some options require changes to configuration.yaml.  
What options?  There is no mention anywhere of how to configure MQTT in the configuration.yaml file, it just says you might have to do it.

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @emontnemery, mind taking a look at this feedback as it has been labeled with an integration (`mqtt`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L390) for? Thanks!
