### ISSUE TITLE
No value for gas

### ISSUE THREAD

**Issue by fjbosscha** [home-assistant/home-assistant.github.io#24262]
### Feedback

I have installed the /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AQ4MI46Y-if00-port0
DSMR Slimme Meter integration in Home Assistant (latest version). I do get values for power and gas, but I cannot graph the gas value. It is not available. 

The values I get are:

2022-09-27 21:11:11.727 DEBUG (MainThread) [dsmr_parser.clients.protocol] got telegram: /ISK5\2M550T-1013

1-3:0.2.8(50)
0-0:1.0.0(220927211205S)
0-0:96.1.1(4530303534303037343837363735333139)
1-0:1.8.1(001127.636*kWh)
1-0:1.8.2(000919.967*kWh)
1-0:2.8.1(001049.184*kWh)
1-0:2.8.2(002489.950*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.098*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00008)
0-0:96.7.9(00005)
1-0:99.97.0(1)(0-0:96.7.19)(190917133248S)(0000000696*s)
1-0:32.32.0(00006)
1-0:52.32.0(00007)
1-0:72.32.0(00011)
1-0:32.36.0(00002)
1-0:52.36.0(00002)
1-0:72.36.0(00002)
0-0:96.13.0()
1-0:32.7.0(225.1*V)
1-0:52.7.0(225.0*V)
1-0:72.7.0(226.6*V)
1-0:31.7.0(000*A)
1-0:51.7.0(000*A)
1-0:71.7.0(000*A)
1-0:21.7.0(00.057*kW)
1-0:41.7.0(00.014*kW)
1-0:61.7.0(00.027*kW)
1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
0-1:24.1.0(003)
0-1:96.1.0(4730303634303031393436353933323139)
0-1:24.2.1(220927211002S)(002965.33*m3)
!A0E4

Main difference is the 1-0: for power en 0-1: for gas. Although this is correct for the Dutch DSMR standard.

Also I cannot, as shown in the Documentation, select a version in de configuration. I can only change "the time between updates".

Home Assistant:
 Home Assistant 2022.9.7 Supervisor 2022.09.1 Operating System 9.0 Frontend-versie: 20220907.2 - latest 

I hope you can help me a bit with this if I have done something wrong.

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @robbie1221, @frenck, mind taking a look at this feedback as it has been labeled with an integration (`dsmr`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L150) for? Thanks!

**Comment by frenck** [comment]
Hi there @fjbosscha 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
