### ISSUE TITLE
Failed to verify your verification code, try again

### ISSUE THREAD

**Issue by Server131** [home-assistant/home-assistant.github.io#24269]
### Feedback

I get this message over and over 

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @quentame, @nzapponi, mind taking a look at this feedback as it has been labeled with an integration (`icloud`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L284) for? Thanks!

**Comment by frenck** [comment]
Hi there @Server131 👋 

Cool, but it seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
