### ISSUE TITLE
Scheduler helper visual

### ISSUE THREAD

**Issue by iwojima1** [home-assistant/home-assistant.github.io#24267]
### Feedback

hello i found that if I set schediler visually to 8:30 and save it, it will show number and also visual bar from 8:00.
In atributes to next change is correct 8:30. I thing it is bug that it shows 8:00

is it possible to edit it in yaml for exaple to 8:12??
I have HA core 2022.9.4

Thanks
Ivan
![1664349494669](https://user-images.githubusercontent.com/58654060/192714118-7e5f8682-b28c-4298-8fe1-aa299271fdfe.jpg)
![1664349494682](https://user-images.githubusercontent.com/58654060/192714127-e68e188a-674f-4bcc-89bc-4e48bec61f24.jpg)

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @home-assistant/core, mind taking a look at this feedback as it has been labeled with an integration (`schedule`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L527) for? Thanks!

**Comment by frenck** [comment]
Hi there @iwojima1 👋 

It seems like you want to report a bug with the Home Assistant frontend; however, you have submitted documentation feedback instead. 

Please report issues with the Home Assistant frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck

**Comment by iwojima1** [comment]
THX
