### ISSUE TITLE
There is no documentation item for lacrosse authentication

### ISSUE THREAD

**Issue by rameister** [home-assistant/home-assistant.github.io#24279]
### Feedback

There is no documentation item for lacrosse authentication. Whe I config the lacrosse integration an window appears and ask me for a username and password. What does this Application need, which password? I need this Integration for finding out the ID's from my Temperture-Sensors after renewing the batteries.

![Home Assistant – lacrosse](https://user-images.githubusercontent.com/59337072/193036304-3dd5d989-f6fb-455a-af22-3d53551e31ca.png)

### URL

https://www.home-assistant.io/integrations/lacrosse_view/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @icebotyt, mind taking a look at this feedback as it has been labeled with an integration (`lacrosse_view`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L329) for? Thanks!

**Comment by IceBotYT** [comment]
Hi there! Are your devices La Crosse View-enabled? A list of supported devices can be viewed [here](https://www.lacrossetechnology.com/collections/lacrosse-view-connected). The username is the email you use to sign in to LaCrosse View. The password is the password for LaCrosse View. They must be added to the app beforehand.

**Comment by rameister** [comment]
Hi, I have 4 Temperatur-Sensors TX29IT standalone coupled with a Jeelink Stick via USB. Is there any chance to get the ID's whit my equipment? Otherwise I think that my issue is personal item.

**Comment by IceBotYT** [comment]
Hi. As noted in the documentation, this integration is _not_ for the Jeelink sensors. Please use [this](https://home-assistant.io/integrations/lacrosse) instead.

**Comment by rameister** [comment]
Hi, I have tried this command: sudo pylacrosse -d /dev/ttyUSB0 scan with my ttyPort (it's ttyAMA0) then I get: bash: pylacrosse: command not found  . Is there a missing Integration of py software?

**Comment by IceBotYT** [comment]
Hi, do you have container or OS?

If container:
`docker exec -it <containername> pylacrosse -d /dev/<tty port> scan`
If OS:
`sudo pylacrosse -d /dev/ttyUSB0 scan`

If you get an error that it wasn't found:
Container:
`docker exec -it <containername> pip install pylacrosse`
OS:
`pip install pylacrosse`

And try again.

**Comment by rameister** [comment]
Hi, I have OS on an Raspi, no docker. When I try pip install pylacrosse I get the same message bash: pip: command not found.

**Comment by IceBotYT** [comment]
Okay, I don't have any experience with OS. Please add the line `pylacrosse:` to your `configuration.yaml` and restart then try the command again. Then update your `pylacrosse:` config as necessary.

**Comment by rameister** [comment]
Hi, then I get a message and cannot reboot:
**The system cannot restart because the configuration is not valid: Integration error: pylacrosse - Integration 'pylacrosse' not found.** 
Below you can see a short cut from my configuration.yaml until the lacrosse sensors. The pylacrosse entry on this position is correct?

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

pylacrosse:
logger:
  default: warning
  logs:
    frontend: debug
    homeassistant.components.frontend: debug
    custom_components.bosch: debug
    bosch_thermostat_http: debug

tankerkoenig:
  api_key:?????????????
  fuel_types:
    - "e10"
  latitude: xx.xxxxx
  longitude: x.xxxxx
  radius: 3.5
  scan_interval: '00:12:23'
  stations:
    - 57f5ba74-0cc6-c340-56ad-94?????
    - 005056ba-7cb6-1ed2-bceb-xxxxxxx
    - f29362be-cd78-4e8e-axxxxxxx
  show_on_map: true

zone:
  - name: home
    latitude: xx.xxxxx 
    longitude: x.xxxxxxx
    radius: 5
    icon: mdi:castle

sensor:
  - platform: lacrosse
    device: /dev/ttyUSB0
    baud: 57600
    sensors:      
      balk_temperature:
        name: Balkon
        type: temperature
        id: 2

**Comment by IceBotYT** [comment]
Ahhh sorry, I mean `lacrosse` instead of `pylacrosse` in the config

**Comment by rameister** [comment]
Hi, you can see in my config that lacrosse: is anounced. My question is why I cannot start any python commands, where is python installed and how I can set python commands. There is another issue open about pylacrosse and no user is working at this issue. Is there a way to solve this?

**Comment by IceBotYT** [comment]
I'm sorry. I'm not the code owner of the `lacrosse` integration. Please create a new issue for that integration. Thanks!

**Comment by IceBotYT** [comment]
Please close this issue unless you have problems with the `lacrosse_view` integration, thank you!

**Comment by IceBotYT** [comment]
@balloob Sorry for the mention. Please close this issue at your earliest convenience. Thank you!
