### ISSUE TITLE
Update uhealthy system loop

### ISSUE THREAD

**Issue by rmikke** [home-assistant/home-assistant.github.io#24272]
### Feedback

I got here because I could not update the Home Assistant. The message was that the system is unhealthy, so I have checked and the problem was that Supervisor is not privileged. So I got to this document and it says "update your Home Assistant OS". But that's exactly what I cannot do while the Supervisor is not privleged.

### URL

https://www.home-assistant.io/more-info/unsupported/privileged/

### Version

2022.9.7

**Comment by frenck** [comment]
>  So I got to this document and it says "update your Home Assistant OS". But that's exactly what I cannot do while the Supervisor is not privleged.

Second paragraph:

![image](https://user-images.githubusercontent.com/195327/192804134-14810080-b4d6-4c37-be51-d60dc957017c.png)

../Frenck
