### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by alessiovalvano** [home-assistant/home-assistant.github.io#24270]
### Feedback

Always receive this error, it's not working anymore.
URL is correct from application to my.home-assistant.io
{
  "error": "invalid_request",
  "error_description": "The reply url host my.home-assistant.io doesn't match with the ones configured on the application"
}

### URL

https://www.home-assistant.io/integrations/home_plus_control/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @chemaaa, mind taking a look at this feedback as it has been labeled with an integration (`home_plus_control`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L263) for? Thanks!

**Comment by frenck** [comment]
Hi there @alessiovalvano 👋 

Thank you for reaching out. You have submitted documentation feedback, this tracker is not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

That said, considering the error message you shared:

> The reply url host my.home-assistant.io doesn't match with the ones configured on the application

It possibly sounds like a misconfigured developer account @ `https://developer.legrand.com/`.

But, the community are better places to get more information on this subject.

../Frenck
