### ISSUE TITLE
HOW do I start D-bus daemon? There should be a link in this document

### ISSUE THREAD

**Issue by rmikke** [home-assistant/home-assistant.github.io#24271]
### Feedback

HOW do I start D-bus daemon? There should be a link in this document

### URL

https://www.home-assistant.io/more-info/unsupported/dbus/

### Version

2022.9.7

**Comment by frenck** [comment]
The Home Assistant Supervised installation method is the most advanced installation method we have. As warned for, is that it requires advanced knowledge of Linux system administration.

Don't get me wrong, but if you have to ask this question, it might be that this installation method is not a good fit for you. You'd probably have a much better experience by running a different installation method.

I'm going to close this suggestion, as this question/suggestion is not about running Home Assistant itself, but about general Linux.

../Frenck
