### ISSUE TITLE
Watermeter does not show the water items

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#24286]
### Feedback

After several attempts the outcome is the same every time. The water meter integrates fine, but does not have the entities "total_liter_m3" and "active_liter_lpm".
The only entities that the watermeter is showing are "wifi_ssid" and "wifi_strength", which is very anoying.

### URL

https://www.home-assistant.io/integrations/homewizard/

### Version

2022.9.7

### Additional information

When I run the diagnostics for the watermeter, it looks like this:
    "data": {
      "device": {
        "product_name": "Watermeter",
        "product_type": "HWE-WTR",
        "serial": "**REDACTED**",
        "api_version": "v1",
        "firmware_version": "1.16"
      },
      "data": {
        "smr_version": null,
        "meter_model": null,
        "wifi_ssid": "**REDACTED**",
        "wifi_strength": 80,
        "total_power_import_t1_kwh": null,
        "total_power_import_t2_kwh": null,
        "total_power_export_t1_kwh": null,
        "total_power_export_t2_kwh": null,
        "active_power_w": null,
        "active_power_l1_w": null,
        "active_power_l2_w": null,
        "active_power_l3_w": null,
        "total_gas_m3": null,
        "gas_timestamp": null
      },

Which looks exactly like the information for the P1 meter, and explains why I see only the wifi entities.

**Comment by homeassistant** [comment]
Hey there @dcsbl, mind taking a look at this feedback as it has been labeled with an integration (`homewizard`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L269) for? Thanks!

**Comment by klaasnicolaas** [comment]
Hi there @DockerBee 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by DCSBL** [comment]
Hey! First of all, this is issue page for documentation on the website, not for issues about the integration. No problem, it is a bit confusing. Can you recreate this issue here → https://github.com/home-assistant/core/issues/new/choose ?
