### ISSUE TITLE
device_id: how to get it for a device

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#24280]
### Feedback

I suggest adding a hint how to get the device_id for the "cleanup" services. I found the device_id in integration -> devices -> (searching for the device fritzbox) -> selecting device -> extract it from the url. 

Maybe it would make sense to add the "device_id" to the device info.

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2022.9.7

### Additional information

just an information. Everytime when I see the "device_id" I have to ask dr. google how to get it :(

**Comment by homeassistant** [comment]
Hey there @mammuth, @aarondavidschneider, @chemelli74, @mib1185, mind taking a look at this feedback as it has been labeled with an integration (`fritz`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L212) for? Thanks!

**Comment by mib1185** [comment]
the UI supports the user by providing so called selectors - in this case the [device selector](https://www.home-assistant.io/docs/blueprint/selectors/#device-selector) is used - example screenshot

![image](https://user-images.githubusercontent.com/35783820/193417254-b9129e9d-ec69-4e80-a95b-bd17e1c125ca.png)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
