### ISSUE TITLE
Link Dashboard docu with dedicated Feature Requests post /area in the community forum

### ISSUE THREAD

**Issue by dgtal1** [home-assistant/home-assistant.github.io#24292]
### Feedback

Today I wanted to file a feature request regarding the UI / dashboard, but first I thought I'm gonna search if something like this already exists in the community forum. The forum is huge and it's easy to miss some similar post. 

I thought it may be a great idea to create sections in the community forum Feature Requests area and link these sections with each UI/Dashboard type. Eg. dedicated feature request area would exist for Entities card, another one for Entity, Calendar etc.

This way devs could see what features users would like to see regarding each aspect of the UI / dashboard type.

### URL

https://www.home-assistant.io/dashboards/entities/

### Version

2022.9.7

**Comment by ludeeus** [comment]
What you are requesting is already possible, all post authors can add tags to their posts
