### ISSUE TITLE
How to use please?

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#24291]
### Feedback

Looking at CPU temperature , no indication of how this might be used?
I'd find that interesting. 

### URL

https://www.home-assistant.io/integrations/sensor.command_line/

### Version

2022.9.7

**Comment by frenck** [comment]
> Looking at CPU temperature , no indication of how this might be used?

I'm not sure if I follow. This is the documentation on how to use command line commands and turn their results into a sensor. Your question seems to be about: "How to use a sensor in Home Assistant"? Is that correct?

../Frenck

**Comment by dpawson** [comment]
Yes, that's correct. I have the command line version working, how to use the sensor script please?

**Comment by frenck** [comment]
> how to use the sensor script please?

There is no sensor script? It creates a sensor entity in Home Assistant. It works just like every other sensor that Home Assistant provides.

An average HA installation has dozens (and more often hundreds) of those, they all work the same.

So, that is not anything specific to this integration or documentation page?

../Frenck

**Comment by dpawson** [comment]
If it is so common, please provide a link to a page where they are described, in general perhaps with an example?
