### ISSUE TITLE
Unclear how to specify list of tariffs

### ISSUE THREAD

**Issue by realflash** [home-assistant/home-assistant.github.io#24290]
### Feedback

The page says:

>Supported tariffs
>A list of supported tariffs, leave empty if only a single tariff is needed.

It does not give an example of how one formats a list in the UI. Am I supposed to enter 
`tariff1,tariff2`
or
`["tariff1","tariff2"]`

or something else?

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @dgomes, mind taking a look at this feedback as it has been labeled with an integration (`utility_meter`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L666) for? Thanks!

**Comment by dgomes** [comment]
Have you tried typing the tariff and pressing enter :) ?

**Comment by realflash** [comment]
I hadn't. Now that I have, I can see how it works (and of course it seems obvious with hindsight). Having run HA for nearly two years, this is the first time encountering a list through the UI. Could you add a sentence explaining this? Like "Enter values one at a time and press enter"

I realise now that the issue is that it is a text entry field surrounded by other text entry fields, with nothing to indicate that it's a multivalue field and how it is supposed to work. I guess this is a higher up HA UI design issue affecting multiple places.

**Comment by dgomes** [comment]
Yes this is not specific to utility_meter...
