### ISSUE TITLE
700 series controllers incompatible

### ISSUE THREAD

**Issue by stepscout** [home-assistant/home-assistant.github.io#24301]
### Feedback

Last weeks I tried to get a Razberry 7 controller working. Updated to latest firmware. 

After many hours investigating issues in Z-Way Expert UI and Home Assistant I can only conclude that the 700 chip is not a consumer product. The last year several fixes and upgrades have been published, but the product is Beta!

I strongly recommend to exclude 700 series controllers from the documentation, and advice Home Assistant user to not use 700 series controllers. 

### URL

https://www.home-assistant.io/docs/z-wave/controllers/

### Version

2022.9.7

### Additional information

Razberry 7 firmware 7.28.

**Comment by frenck** [comment]
We currently support and test with the 700 series. They should just work.
If you are experiencing issues with it, please report an issue so it can be investigated.

../Frenck
