### ISSUE TITLE
Why switch and not button?

### ISSUE THREAD

**Issue by hklages** [home-assistant/home-assistant.github.io#24300]
### Feedback

Wouldn't it make more sense to implement that as a "button"? 

If you use a switch, then everyone expects that it shows the right status but after turning on/off the device manually the switch does not show it. 

### URL

https://www.home-assistant.io/integrations/wake_on_lan/

### Version

2022.9.7

**Comment by homeassistant** [comment]
Hey there @ntilley905, mind taking a look at this feedback as it has been labeled with an integration (`wake_on_lan`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L684) for? Thanks!

**Comment by frenck** [comment]
This is part of history, buttons are fairly new.

Closing this documentation feedback, as it does not contain documentation feedback 😉 

../Frenck
