### ISSUE TITLE
Other remote access method

### ISSUE THREAD

**Issue by ingoau** [home-assistant/home-assistant.github.io#24304]
### Feedback

There is another remote access method for ha using a cloudflare tunnel with the cloudflared addon.
Please see video
https://www.youtube.com/watch?v=xXAwT9N-7Hw
You could add this to the docs

### URL

https://www.home-assistant.io/docs/configuration/remote/

### Version

2022.9.7

**Comment by frenck** [comment]
There are many more possibilities on doing this. However, we don't want to list or maintain them all. Therefore we list the most common cases at this point.

Feel free to share additional community guides on our community forums (in the special Community Guides section, which acts as a Wiki).

Thanks 👍 

../Frenck
