### ISSUE TITLE
Please update docs to suggest  iotawatt's integrator sensors 

### ISSUE THREAD

**Issue by lyricnz** [home-assistant/home-assistant.github.io#24330]
### Feedback

As discussed in #68445 and #67698 please update the docs at https://www.home-assistant.io/integrations/iotawatt/ to describe this way of getting data for the Energy Dashboard.  Without that, new people will continue to have problems with the iotawatt accumulated sensors

### URL

https://www.home-assistant.io/integrations/iotawatt/

**Comment by homeassistant** [comment]
Hey there @gtdiehl, @jyavenard, mind taking a look at this feedback as it has been labeled with an integration (`iotawatt`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L302) for? Thanks!

**Comment by frenck** [comment]
I'm not sure what your suggestion is based on the text above?

Could you provide a suggested edit? Or describe what is actual wrong with the page? This feedback does not contain or does not point out anything specific.

../Frenck

**Comment by lyricnz** [comment]
Sorry - I assumed quoting the issue IDs would have linked, but that's in home-assistant/core project, not this one.

https://github.com/home-assistant/core/issues/68445
https://github.com/home-assistant/core/issues/67698

The instructions on the [iotawatt page](https://www.home-assistant.io/integrations/iotawatt/) describe using two new outputs on iotawatt MainsConsumption and MainsExport which are based directly on summing the three phases (+abs etc), and then using the Accumulated versions of these in HA.

However, this doesn't work well. As described in https://github.com/home-assistant/core/issues/68445

> The issue with accumulated sensor is that their reset value changes all the time following a recent regression that is confusing the energy dashboard.
> You need to switch to the iotawatt's integrator sensors.
> See https://docs.iotawatt.com/en/master/integrators.html
> And stop using the "accumulated" sensor for import / export.

This issue asks for the instructions to be updated to follow the advice quoted from the issue above.  FWIW, the second approach "worked for me", while the first had problems with the reset time/value.

**Comment by lyricnz** [comment]
Not stale. Docs still describe a method which doesn't work with the energy dashboard.

**Comment by jyavenard** [comment]
accumulated sensors should be removed from the python library, they are no longer necessary as the iotawatt now supports it natively
