### ISSUE TITLE
Picture elements - allow setting of static titles and sensor precision

### ISSUE THREAD

**Issue by joriws** [home-assistant/home-assistant.github.io#24335]
### Feedback

First request: allow setting static titles with sensor or document it better that I can understand how to do it. For example using condition if number of alarms > 0, show text "ALARM!". It would be also nice to be able to set color of text on every item type. So documentation missing for conditinal text only.

Second request: sensor precision. Sometimes sensor provides like 2 digit value of f.ex. outdoor temperature. But for picture-element I'd like to display it with 1 digit or even 0 digits. If it is already doable, it is not documented. Nor I really would hate going via templates etc but if that templating is the possibility, please document it how to do it without storing additional entry to DB.

### URL

https://www.home-assistant.io/dashboards/picture-elements/

### Version

2022.9.7

### Additional information

Normal: ![image](https://user-images.githubusercontent.com/5603060/193445723-a07150dc-ea10-4621-8880-cfa76ada527f.png)

Sensor giving weird value which precision or similar would help too:
![image](https://user-images.githubusercontent.com/5603060/193449665-0d9449da-0755-4196-a2c8-51d280d29a67.png)

- I used to have several ruuvi tag pressure reports with 10+ digits. From above picture with hPa imagine the 3 integer digits + 10 fraction digits that it is nice readable. Minor problem but still existing.

![image](https://user-images.githubusercontent.com/5603060/193450470-4c1e3a4e-3fbf-4260-9d0a-8482bad842b4.png)

**Comment by ludeeus** [comment]
This section is to provide feedback for the documentation not to request features to be added.
Please raise feature requests on the forums <https://community.home-assistant.io/c/feature-requests/13> 👍
