### ISSUE TITLE
Complete instructions of making an HAOS image via Ubuntu / BalenaEtcher

### ISSUE THREAD

**Issue by piek768** [home-assistant/home-assistant.github.io#24351]
### Feedback

I was unable to perform the tutorial for installing HAOS on a x86 system, by using method 2 (using a live operating system)

This guide points to an ubuntu USB bootable stick, in my case version 22.04
Downloading and extracting BalenaEtcher was easy
Exectuting however was not. Double clicking resulted in nothing

After a LOT of troubleshooting and help, i found that on the Ubuntu USB loader, the (right version of?) fuse was missing. I resolved it by performing this method: 

1. download and extract balenaetcher as described in the guide
2. open terminal (ctrl-alt-T)
3. Install fuse by executing the following commands:
sudo add-apt-repository universe
sudo apt install libfuse2
4. change to the directory to where BalenaEchter is extracted using "CD" commands to change directory and "LS" to list the files and folders (standard is Downloads folders)
5. Run the appimage as root by executing the following command:
sudo ./balenaEtcher-1.7.9-x64.AppImage
(or the litteral filename of the extracted appimage if the version is different)
6. Flash the boot disk of the system with HAOS as per the existing tutorial

As this was performed (and repeated) with a 'standard' ubuntu live OS 22.04 and the standard balenaetcher, I think everybody will encounter this issue the same (safe assumption?) and it may be worth to update the guide with this info. It cost me 5 hours to resolve (because it is hard to google and understand which steps of all possible solutions asre most feasible in linux if you have little to no experiece) 

### URL

https://www.home-assistant.io/installation/generic-x86-64

### Version

Ubuntu 22.04, Balena Etcher 1.7.9-x64

**Comment by frenck** [comment]
That would be a very specific exception, isn't it the job of BelenaEtcher to document that?

**Comment by piek768** [comment]
yeah I agree. An easier solution for end users would be the possibility to make a bootable HAOS installer on a USB stick to install HAOS on an intel system. This is currrently not the case. If you cannot attach the new boot media to the PC, flashing Ubuntu 22.04 on a bootable USP stick and then flashing the HAOS boot media in the new pc with HAOS is the most prominent route to do this. And this route doesn't work without extra handling that is not discribed in the (linked) guide(s). Easy to make the guide a few lines longer I would say.

I don't know who decides this, but the problem looks to be a standard problem and this is a standard solution (now I know what to google for, I find MANY people desperate and then happy when they figured it out, in the "oerwoud" of non working solutions :D. 

Maybe a link to this topic could help people a lot: https://community.home-assistant.io/t/how-to-balena-etcher-on-ubuntu-22-04/443092

**Comment by frenck** [comment]
> Easy to make the guide a few lines longer I would say.

That is not easy, as it is specific for Ubuntu, which is used by just a very small percentage of our users. That makes it a weird exception that most people do not need. Adding it adds the risk to complicate and overwhelm. Additionally, users of Linux are generally considered more than capable of handling things like this.

> I don't know who decides this

Well, I'm one of the peeps that decide on things like these.

**Comment by piek768** [comment]
Haha ok, I'm dicussing directly with the maker :). Thanks for the awesome product!

I;m not sure I get the message along. I do not run home assistant using ubuntu. I run HAOS directly on a NUC. But to get HAOS on the NUC, you either have to take the boot disk out of this system, connect it to a current pc and flash HAOS on that disc directly with Balenaetcher (in windows in my case). 

OR you have to boot your NUC that you want HAOS to run from with a bootbable OS usb stick, to then temporary download and install BalenaEtcher in order to flash the HAOS image on the NUC HD.

I dont mean using Ubuntu to run HA on, ubuntu is just the tool to get HAOS on your NUC. The guide on this site points towards using Balena and Ubuntu live OS on a USB stick for this purpose, but this combination does not work without these extra instructions. That's why I;m proposing to clarifiy it in the guide on this site.

**Comment by frenck** [comment]
> I dont mean using Ubuntu to run HA on, ubuntu is just the tool to get HAOS on your NUC. The guide on this site points towards using Balena and Ubuntu live OS on a USB stick for this purpose, but this combination does not work without these extra instructions. That's why I;m proposing to clarifiy it in the guide on this site.

Aah, now I get it! Thanks for clarifying. Good point 🤔

**Comment by ikifar2012** [comment]
Could this be accomplished by a note or should we make a separate section?

**Comment by piek768** [comment]
An instruction as a second bullit under the section “ Copying a live operating system (e.g. Ubuntu) onto a USB device” explaining you need to install fuse when using the Ubuntu live OS, via the cli and what commands to use (like I triestig do  in my start post) , would be perfect. 

But a link to the solution and explanation that this is a known issue would also be nice. 

That would have saved me hours. :)
