### ISSUE TITLE
Change the way individual devices is reported in Energy Management

### ISSUE THREAD

**Issue by PatricDahl** [home-assistant/home-assistant.github.io#24350]
### Feedback

Today it's possible to have individual power sources reported in system. Unfortunately they don't report cost as Grid consumption do, Would it we possible to change  this to be more easily to overview how much cost is for those individual ones?

Maybe it could be a mixture of they presenting?   

### URL

https://www.home-assistant.io/docs/energy/

### Version

2022.9.7

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests) or the [What the heck](https://community.home-assistant.io/c/what-the-heck) topic

Thanks! 👍
