### ISSUE TITLE
MQTT HVAC documentation is missing information on command templates

### ISSUE THREAD

**Issue by EuleMitKeule** [home-assistant/home-assistant.github.io#24369]
### Feedback

The `command_template` feature of the MQTT HVAC component is missing the crucial information on how to access the target command value from within the template.
```yaml
temperature_command_template: >
  00:11:22:33:44:55 settemp {{value}}
```
This would be an example of a command template accessing the temperature target value by using the template variable `value`.

### URL

https://www.home-assistant.io/integrations/climate.mqtt

**Comment by homeassistant** [comment]
Hey there @emontnemery, mind taking a look at this feedback as it has been labeled with an integration (`mqtt`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L390) for? Thanks!

**Comment by EuleMitKeule** [comment]
I still think this is unclear and could be added to the documentation. Maybe this is not specific to this integration, but comes from the way templating works in Home Assistant, but still it would be helpful for beginners to include a notice in the docs about this.
