### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by euhkah** [home-assistant/home-assistant.github.io#24362]
### Feedback

the method has evolved and the page is not up to date

### URL

https://www.home-assistant.io/integrations/slack#bot-posting-as-its-own-user

**Comment by homeassistant** [comment]
Hey there @bachya, @tkdrob, mind taking a look at this feedback as it has been labeled with an integration (`slack`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L560) for? Thanks!

**Comment by bachya** [comment]
Please provide more detail.

**Comment by euhkah** [comment]
the "BOT POSTING AS YOU" section is apparently the new method. the "POSTING AS ITS OWN USER" section is deprecated. But that's not the only problem, because when I apply the complete procedure, I never get the notify service (on some points the guide is not very detailed, example: default channel, with or without #?). Something is missing to make it simple. Also, applications can now be created with a YAML or JSON manifest, an example configuration would make integration easier.

2022-10-04 06:35:13.417 INFO (MainThread) [homeassistant.components.notify] Setting up notify.slack
2022-10-04 07:06:43.229 INFO (MainThread) [homeassistant.components.notify] Setting up notify.slack
2022-10-04 07:33:28.525 INFO (MainThread) [homeassistant.components.notify] Setting up notify.slack

**Comment by tkdrob** [comment]
Post your HA version. Configuration from Yaml is deprecated.

**Comment by euhkah** [comment]
Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Interface utilisateur : 20220907.2 - latest

**Comment by tkdrob** [comment]
Looks like something has changed a bit. I'm thinking that the manifest option will not be supported rn as it is still in beta on Slack's end.

**Comment by euhkah** [comment]
yes, there are many things that have changed a bit, and the sum of all these little things has created a big problem for me. for example, we cannot send photos directly with the only chat:write, another scopes is necessary
