### ISSUE TITLE
Why is 64-bit recommended for rpi 3?

### ISSUE THREAD

**Issue by HarvsG** [home-assistant/home-assistant.github.io#24374]
### Feedback

https://github.com/home-assistant/home-assistant.io/blame/current/source/_includes/installation/operating_system.md#L120-L121

rpi3 is a significantly memory limited board and 32 bit consumes less of it

https://github.com/home-assistant/operating-system/issues/1999#issuecomment-1261006397

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

2022.9.7

**Comment by frenck** [comment]
> rpi3 is a significantly memory limited board and 32 bit consumes less of it

Sure! But there are also many other downsides to it. For example, most of the world is abandoning 32-bits (Ubuntu is a great example). More and more issues arise keeping things rolling and working for 32-bits. It has no future.

Besides that, there are more known add-ons/integrations to work on 64-bits.

Thus we recommend 64-bits. Feel free to choose differently if you feel like it better matches your situation.

../Frenck

**Comment by HarvsG** [comment]
Makes sense. Thanks for the explanation
