### ISSUE TITLE
Documentation does not cover schedules that overlap from one day to another

### ISSUE THREAD

**Issue by raypanggh** [home-assistant/home-assistant.github.io#24385]
### Feedback

What happens if I want a schedule to be from 23:00 to 07:00? It appears that I have to create two separate schedules 23:00-00:00 and 00:00-07:00. Will that cause an on-off-on event at midnight?

### URL

https://www.home-assistant.io/integrations/schedule/

**Comment by homeassistant** [comment]
Hey there @home-assistant/core, mind taking a look at this feedback as it has been labeled with an integration (`schedule`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L527) for? Thanks!
