### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alpe66** [home-assistant/home-assistant.github.io#24382]
### Feedback

Hi the switchbot Team,
In the step of configurating an switchbot on HomeAssistant it would be nice to specify that before configuring the switchbot, the calibration of the switchbot must be before whith the phone. Because if no calibration unable to got switchbot working in Home Assistant.
Thank a lot

### URL

http://home-assistant.io

### Additional information

Thanks

**Comment by homeassistant** [comment]
Hey there @bdraco, @danielhiversen, @renierm26, @murtas, @eloston, mind taking a look at this feedback as it has been labeled with an integration (`switchbot`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L609) for? Thanks!
