### ISSUE TITLE
Scan_interval for EDL21 integration?

### ISSUE THREAD

**Issue by CommanderROR9** [home-assistant/home-assistant.github.io#24384]
### Feedback

It seems that the current edl21 integration only updates it's entities ever 60+ Seconds. This is a problem for the current power display that I use for many automations.
Can we get a way to update this data every 5 Seconds?
Thanks!

### URL

https://www.home-assistant.io/integrations/edl21

### Version

2022.9.07

**Comment by homeassistant** [comment]
Hey there @mtdcr, mind taking a look at this feedback as it has been labeled with an integration (`edl21`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L159) for? Thanks!

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
