### ISSUE TITLE
Logger output for shell commands doesn't work for me

### ISSUE THREAD

**Issue by pjdubya** [home-assistant/home-assistant.github.io#24390]
### Feedback

I'm following the guidance at https://www.home-assistant.io/integrations/shell_command and subsequently linked page https://www.home-assistant.io/integrations/logger/ to try to capture logs of the output of my shell scripts. It says:

stdout and stderr output from the command are both captured and will be logged by setting the [log level](https://www.home-assistant.io/integrations/logger/) to debug.

The logger page doesn't actually tell you how to enable logging for shell commands, so I tried various permutations like this:

logger:
  default: debug
  logs:
    shell_command.my_shell_command: debug
    homeassistant.components.shell_command.my_shell_command: debug

None of those seem to be doing the trick though because there are still no logbook entries associated with running this shell command from an automation. I see a logbook entry for the automation itself, and I see that my steps were executed, but there's no logging captured even when I'm certain that the shell command had output. I tested this by adding shell commands that perform a simple "ls" and another to "ls > writetest.txt". I know that there was output of the ls command because I see the writetest.txt appear in my file system with the output of the config directory's ls command. So I would have expected that same output to appear in the logbook entry for the step where I executed the shell command that performed the ls.

I'm not sure if this is a problem with the logger or automations or shell commands, but for now I'm assuming it's the logger.

If I open the home-assistant.log and search through the results, I was able to find cases where my initial shell command actually failed with ERROR status while this logging config was enabled, and even that didn't show up in the logbook. I was able to fix that problem and eventually have clean executions according to home-assistant.log .

### URL

https://www.home-assistant.io/integrations/logger/

### Version

2022.9.2

**Comment by homeassistant** [comment]
Hey there @home-assistant/core, mind taking a look at this feedback as it has been labeled with an integration (`shell_command`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L547) for? Thanks!

**Comment by homeassistant** [comment]
Hey there @home-assistant/core, mind taking a look at this feedback as it has been labeled with an integration (`logger`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L347) for? Thanks!

**Comment by pjdubya** [comment]
Looking over things again, it's possible I have misunderstood how logger works and whether there's actually any linkage to "logbook entries" in the UI. For more context, I navigated to Logbook in the left panel of the UI, then to the most recent automation execution (which does appear as a line item in Logbook), then it takes me to some options to view the automation results. Here's what it looks like on the Trace Timeline view:

![image](https://user-images.githubusercontent.com/8021041/194126412-b018d9ac-edf2-45b4-acd9-219e46811673.png)

I was expecting to see the output of my shell commands displayed next to each shell command execution line. The "related logbook entries" tab in that view also shows only the single line for the automation execution itself, not the details of this step. Same for if I look at the individual step's related logbook entries tab. 

If I'm mistaken about there being a link between logger and logbook entries, I apologize (though I do think this would be the right place to display such output). I do see now that the home-assistant.log **does** contain the debug-level output from the command that would have generated some, so that's at least working. I will try some additional permutations to figure out what the right syntax is for enabling that at the shell command level vs enabling debug logging for all of HA.

**Comment by cdytoby** [comment]
+1 here. I'm exactly looking for this. And I also posted a thread for help in reddit, but only get downvotes.

https://www.reddit.com/r/homeassistant/comments/yheino/how_to_set_log_level_for_shell_command/

**Comment by gjohansson-ST** [comment]
`logger` and `logbook` is not the same thing. The integration refers to the log which is the text-file in your config directory which you can also find/see in settings in your HA instance.
Also you need to use the proper syntax:
```yaml
logger:
  default: info # Set your default
  logs:
    homeassistant.components.shell_command: debug
```

This issue should be closed and any feature request should go to community forum
