### ISSUE TITLE
HA Restart required after adding picture to /config/www

### ISSUE THREAD

**Issue by RobertGetzner** [home-assistant/home-assistant.github.io#24392]
### Feedback

Hi, 
it looks like a HA Restart is required after adding picture to /config/www and using the in a Picture card on the lovelace dashboard. Maybe this is general knowledge with HA, but I didn´t know. So pls kindly add this info to the picture card doc. 
Thanks!
Robert 

### URL

https://www.home-assistant.io/dashboards/picture

### Version

2022.4.7

**Comment by N1co93** [comment]
Hi Robert.

just tested your described issue. For me, the images are available immediately, after I moved them to the folder `/config/www`
So I don't see there any issue.

**Comment by pyrrolizin** [comment]
Have you cleared the browser cache or tried a hard reload (ctrl+F5 or similar)?

**Comment by ludeeus** [comment]
You do not have to restart after adding images to `/config/www`.
You do have to restart when you create the `/config/www` folder as described in the hosting documentation that is linked from that page in the description for the `image` key <https://www.home-assistant.io/dashboards/picture#image>

<https://www.home-assistant.io/integrations/http/#hosting-files>

**Comment by RobertGetzner** [comment]
Hi,  @ludeeus thank you, I missed the step with restart after creating the /config/www folder. My bad, sorry....
Best, Robert
