### ISSUE TITLE
Wrong Flage while sort by Language.

### ISSUE THREAD

**Issue by cheakheang** [home-assistant/home-assistant.github.io#24407]
### Feedback

on the new function with radio browser.  it was setting wrong flag image for **Khmer** language. but sort by country is correct,

Country Name : **Cambodia**
Language : **Khmer**
Nationality : Cambodian ( also call Khmer)
Flag:  https://en.wikipedia.org/wiki/Flag_of_Cambodia

![image](https://user-images.githubusercontent.com/48879063/194205707-3c19a7e3-7dbd-4c1b-bb53-e2589cdd2db6.png)

![image](https://user-images.githubusercontent.com/48879063/194207687-f295332f-19ba-4f25-9c93-85c000df7087.png)

please find and correct , thank you.

### URL

Media => Radio function of HA

### Version

2022.10.0

**Comment by pattyland** [comment]
That seems like a problem with in the core, not the homepage
