### ISSUE TITLE
Radarr integration add Queue 

### ISSUE THREAD

**Issue by encor50** [home-assistant/home-assistant.github.io#24408]
### Feedback

Hello,

can you add queue sensor to Radarr integration please same like we have on sonarr integration 

Thank you very much for all the hard work 

### URL

https://www.home-assistant.io/integrations/radarr/

### Version

2022.10.0

**Comment by homeassistant** [comment]
Hey there @tkdrob, mind taking a look at this feedback as it has been labeled with an integration (`radarr`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L504) for? Thanks!
