### ISSUE TITLE
Open an issue with the author of the integration

### ISSUE THREAD

**Issue by JL-EU** [home-assistant/home-assistant.github.io#24412]
### Feedback

This page states "Open an issue with the author of the integration". Yes, but how do I see who is the author. In this situation I am using a vibration detector (DJT11LM) via zigbee2mqtt. Who is then the author, would that be zigbee2mqtt?

### URL

https://www.home-assistant.io/more-info/statistics/

**Comment by klaasnicolaas** [comment]
This happens automatically when you create an issue for an integration in the core repository of Home Assistant: https://github.com/home-assistant/core

However, Zigbee2MQTT is not part of core, so if you have problems with that you should create an issues in [their repository](https://github.com/Koenkk/zigbee2mqtt)
