### ISSUE TITLE
New Home Assistant MQTT config for lights

### ISSUE THREAD

**Issue by eckolaw** [home-assistant/home-assistant.github.io#24428]
### Feedback

No matter how I add a second mqtt light the new way in the config file shows duplicate key used for light. The old way with `light:  -platform: mqtt'` still works

`mqtt:
   light:
    name: "Office"
   ....
  light:
    name: "Hallway"`

### URL

https://www.home-assistant.io/integrations/light.mqtt/#new_format

### Version

2022.10.1

### Additional information

`mqtt:  
  light:
    - schema: template
      name: "Hallway Light"
      command_topic: "shellies/ShellyBulbDuo-1/light/0/set"
      state_topic: "shellies/ShellyBulbDuo-1/light/0/status"
      availability_topic: "shellies/ShellyBulbDuo-1/online"
      command_on_template: >
        {"turn": "on", "mode": "white"
        {%- if brightness is defined -%}
        , "brightness": {{brightness | float | multiply(0.39215686) | round(0)}}
        {%- endif -%}
        {%- if color_temp is defined -%}
        , "temp": {{ [[(1000000 / color_temp | float) | round(0), 3000] | max, 6500] | min }}
        {%- endif -%}
        }
      command_off_template: '{"turn":"off", "mode": "white"}'
      state_template: "{% if value_json.ison and value_json.mode == 'white' %}on{% else %}off{% endif %}"
      brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
      color_temp_template: "{{ (1000000 / value_json.temp | float) | round(0) }}"
      payload_available: "true"
      payload_not_available: "false"
      max_mireds: 334
      min_mireds: 153
      qos: 1
      retain: false
      optimistic: false
      
  light:
    - schema: template
      name: "Office Light"
      command_topic: "shellies/ShellyBulbDuo-2/light/0/set"
      state_topic: "shellies/ShellyBulbDuo-2/light/0/status"
      availability_topic: "shellies/ShellyBulbDuo-2/online"
      command_on_template: >
        {"turn": "on", "mode": "white"
        {%- if brightness is defined -%}
        , "brightness": {{brightness | float | multiply(0.39215686) | round(0)}}
        {%- endif -%}
        {%- if color_temp is defined -%}
        , "temp": {{ [[(1000000 / color_temp | float) | round(0), 3000] | max, 6500] | min }}
        {%- endif -%}
        }
      command_off_template: '{"turn":"off", "mode": "white"}'
      state_template: "{% if value_json.ison and value_json.mode == 'white' %}on{% else %}off{% endif %}"
      brightness_template: "{{ value_json.brightness | float | multiply(2.55) | round(0) }}"
      color_temp_template: "{{ (1000000 / value_json.temp | float) | round(0) }}"
      payload_available: "true"
      payload_not_available: "false"
      max_mireds: 334
      min_mireds: 153
      qos: 1
      retain: false
      optimistic: false`

**Comment by homeassistant** [comment]
Hey there @emontnemery, mind taking a look at this feedback as it has been labeled with an integration (`mqtt`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L402) for? Thanks!

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
