### ISSUE TITLE
Setup Z-Wave.Me RaZberry 7 Pro (700 series) on Yellow With HAOS 9.01

### ISSUE THREAD

**Issue by bert269** [home-assistant/home-assistant.github.io#24437]
### Feedback

I followed the instructions on: https://www.home-assistant.io/docs/z-wave/controllers/#supported-z-wave-usb-sticks--hardware-modules for CM4 module.
In coot/config.txt disabled BT and enabled UART.
First rebooted without Razberry 7 module installed (BT still shows up) and then added module and rebooted again.
BT still shows up. Tried to install Z-Wave JS, but got "Unknown error occurred"
Still module does not show in devices.

### URL

https://www.home-assistant.io/docs/z-wave/controllers/#supported-z-wave-usb-sticks--hardware-modules

### Version

9.01

**Comment by jwaldrip** [comment]
Having the same issue here. The boot/config.txt doesn't seem to do anything.

**Comment by bert269** [comment]
I did get mine eventually to work.
I disabled BT and wifi, and reboot

Then the Zwave device came up.
