### ISSUE TITLE
Track AP

### ISSUE THREAD

**Issue by goofv** [home-assistant/home-assistant.github.io#24443]
### Feedback

Hi,

is it maybe possible to add the last 3 digits of the host to the dev_id?
So every time a device connect to a different AP it has a different id.
Then it is possible to track a device in different zones in the house.

### URL

https://www.home-assistant.io/integrations/device_tracker/#device_trackersee-service

**Comment by homeassistant** [comment]
Hey there @home-assistant/core, mind taking a look at this feedback as it has been labeled with an integration (`device_tracker`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L139) for? Thanks!
