### ISSUE TITLE
Mac doesn't have apt

### ISSUE THREAD

**Issue by kupietools** [home-assistant/home-assistant.github.io#24459]
### Feedback

You specify to install HA core on Mac using apt-get. Mac doesn't have apt and doesn't understand .deb files. Also, you specify to use the "useradd" command, which doesn't exist on Mac. Overall it seems like these are Linux instructions, not Mac instructions, just with a MacOS title added at the top of the page. 

### URL

https://www.home-assistant.io/installation/macos

**Comment by ikifar2012** [comment]
It seems it is supposed to be that way 
![image](https://user-images.githubusercontent.com/20800434/194777616-4e1610ef-85d9-4773-8c40-faa7a7c92249.png)
I really think we should direct the user to home assistant container on this page
