### ISSUE TITLE
Missing commands in case of reboot

### ISSUE THREAD

**Issue by ChrigouTav** [home-assistant/home-assistant.github.io#24451]
### Feedback

I think it miss the commands to launch HASS after a reboot of the pi comparing to the commands to install it.
I will suggest theses commands, am I right ?

- sudo -u homeassistant -H -s
- cd /srv/homeassistant
- python3.9 -m venv .
- source bin/activate
- hass

### URL

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core

### Version

2022.10.1

**Comment by frenck** [comment]
It depends on your setup and how you wish to start it. Some people create a service e.g., systems or whatever init system they use.

Please note, this is a very advanced installation method, and as the documentation described, we expect people to have knowledge about these things. If this raises a question for you, you might be better of picking a different installation method (don't get me wrong, I mean this in a helpful and friendly way).

../Frenck
