### ISSUE TITLE
Add new model to Synology SRM platform documentation

### ISSUE THREAD

**Issue by westfa** [home-assistant/home-assistant.github.io#24463]
### Feedback

This integration also works for the latest Synology RT6600ax router with SRM 1.3. 

### URL

https://www.home-assistant.io/integrations/synology_srm/

### Version

2022.10.1

**Comment by homeassistant** [comment]
Hey there @aerialls, mind taking a look at this feedback as it has been labeled with an integration (`synology_srm`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L632) for? Thanks!
