### ISSUE TITLE
Amazon Alexa Smart Home Skill cloudflare issue

### ISSUE THREAD

**Issue by Alethio36** [home-assistant/home-assistant.github.io#24489]
### Feedback

after following the instructions to a letter, i absolutely couldn't not get the lambda function to properly test. my issue was in cloudflare (its always dns isn't it?). I had "bot fight mode" (Security->Bots in cloudflare) turned on, and it was blocking any attempt at connecting the app, as well as the lambda test. as a work around under WAF -> Tools, i added
AS16509 (make sure to hit enter after you type it in) as a ip access rule to allow access. seems to work, but be kinda hacky.

I know yall aren't cloudflare, or AWS, but maybe a note in the documentation wouldn't hurt?

I'm also open to a resolution that's more elegant then a broad ANS whitelist like that. 

-edit
the website documentation was spot on, very well done.
it took me forever to even find the issue, I wouldn't have ever thought cloudflare would be the culprit. that's the only reason i want to bring it up, a small note in the documentation would have saved me hours.

### URL

https://www.home-assistant.io/integrations/alexa.smart_home/

### Version

2022.10.2

**Comment by homeassistant** [comment]
Hey there @starkillerog, mind taking a look at this feedback as it has been labeled with an integration (`smart_home`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L582) for? Thanks!

**Comment by homeassistant** [comment]
Hey there @starkillerog, mind taking a look at this feedback as it has been labeled with an integration (`smart_home`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L582) for? Thanks!

**Comment by starkillerOG** [comment]
HomeAssistant bot is tagging me wrong, I am not a code owner of alexa.smart_home, only of the smart_home documentation, which is about smart window blinds, not alexa. smart_home is a supported brand of the motion_blinds integration.
Link to the smart_home website of the brand: https://smart-home.hu/en/

**Comment by Alethio36** [comment]
that seems like a small oversight. ironically, sounds like a issue needs to be raised :/

**Comment by homeassistant** [comment]
Hey there @home-assistant/cloud, @ochlocracy, mind taking a look at this feedback as it has been labeled with an integration (`alexa`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L30) for? Thanks!

**Comment by homeassistant** [comment]
Hey there @home-assistant/cloud, @ochlocracy, mind taking a look at this feedback as it has been labeled with an integration (`alexa`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L30) for? Thanks!

**Comment by Alethio36** [comment]
is it rude to bump this?
