### ISSUE TITLE
How to tell what days count as holidays for Workday Sensor

### ISSUE THREAD

**Issue by Yowaishi** [home-assistant/home-assistant.github.io#24507]
### Feedback

I want to check what days the workday sensor is going to already count as holidays so that I don't need to bother adding/excluding holidays unnecessarily. My work holidays might not match just based on the country etc. I tried reading all the provided documentation but couldn't find a list to check or anything.

### URL

https://www.home-assistant.io/integrations/workday

**Comment by homeassistant** [comment]
Hey there @fabaff, mind taking a look at this feedback as it has been labeled with an integration (`workday`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L723) for? Thanks!

**Comment by stefanroelofs** [comment]
It is usually based on a Wikipedia entry. For example: [UK Bank holidays](https://en.wikipedia.org/wiki/Public_holidays_in_the_United_Kingdom)

Search for your country in this list and check the code to see your holidays:
https://github.com/dr-prodigy/python-holidays/tree/master/holidays/countries

**Comment by Yowaishi** [comment]
Thank you stefanroelofs!
