### ISSUE TITLE
Switchbot Remote not supported

### ISSUE THREAD

**Issue by mkatwijk** [home-assistant/home-assistant.github.io#24519]
### Feedback

I bought the W0301700 Switchbot Remote but it seems it is not supported by the Switchbot integration. I was looking for a mention of this on the integration page but could not find any.

It seems more people are wondering about the support of the remote: https://community.home-assistant.io/t/switchbot-remote-the-buttons-that-control-the-curtains/365098/4

### URL

https://www.home-assistant.io/integrations/switchbot/#supported-devices

### Version

2022.10.3

**Comment by homeassistant** [comment]
Hey there @bdraco, @danielhiversen, @renierm26, @murtas, @eloston, mind taking a look at this feedback as it has been labeled with an integration (`switchbot`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L626) for? Thanks!

**Comment by bdraco** [comment]
It isn't possible to support the remote as it doesn't connect to Home Assistant, only switchbot devices.
