### ISSUE TITLE
Offset in CALDAV event title/message not working

### ISSUE THREAD

**Issue by pmffromspace** [home-assistant/home-assistant.github.io#24517]
### Feedback

I added my **nextcloud calender via CalDAV** in configuration.yaml. The events are shown properly. 
Problem is, the calender events have start time 2 hours later than shown in my nextcloud calender. I configured timezone in nextcloud and in homeassistant to be same. Tried to offset the timezone  in nextcloud, now difference, changed back to my location. 

My solution now would be to use the **offset_reached** to add "-02:00" to the event title to have it triggered at the time its shown in my calendar. Problem is, the offset_reached apparently doesnt work. Neither "-120" (minutes) nor "-02:00".
[ In the docu its quoted ](https://www.home-assistant.io/integrations/caldav/#sensor-attributes) "If set in the event title". I only see following fields of the event entity: (only message, not title. Maybe thats the reason?)

message: Heizen WZ -02:00 
all_day: false 
start_time: 2022-10-11 14:15:00 
end_time: 2022-10-11 15:15:00 
location:  
description:  
offset_reached: 
false friendly_name:
-- | --

How can I get the **offset_reached** to be recognised or alternativly get the calDAV to be displayed in the right timezone?

### URL

https://www.home-assistant.io/integrations/caldav/

### Version

2022.10.1

**Comment by frenck** [comment]
Hi there @pmffromspace 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
