### ISSUE TITLE
Unclear how to use the UI for adding MQTT sensor

### ISSUE THREAD

**Issue by JL-EU** [home-assistant/home-assistant.github.io#24518]
### Feedback

I want to add a mqtt sensor, however reading the page: https://www.home-assistant.io/integrations/sensor.mqtt/
it only describe how to do this manually via the configuration.yaml. Maybe this means that it is only possible to do manually but then it would be good if it is stated on the page. As more and more configurations becomes available via the UI it would be good if the documentation states whether it is supported or not via the UI.

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

**Comment by homeassistant** [comment]
Hey there @emontnemery, mind taking a look at this feedback as it has been labeled with an integration (`mqtt`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L402) for? Thanks!

**Comment by frenck** [comment]
It explicitly states how to configure it:

![image](https://user-images.githubusercontent.com/195327/195077691-ada0ef8d-6727-4f23-8b73-96aae6992a86.png)

I'm not sure how that is ambiguous?

**Comment by JL-EU** [comment]
So this means only manually configuration I assume? I understand that for you working with the system everthing is obvious, but for me it is not.

**Comment by frenck** [comment]
That is what it says, yes. It explicitly tells you that if you want to use your MQTT sensor, you have to add things to the `configuration.yaml` file...
