### ISSUE TITLE
\config is missing to connect properly to samba server (from windows)

### ISSUE THREAD

**Issue by BoMaDB** [home-assistant/home-assistant.github.io#24513]
### Feedback

Description in HA is atm: If you are on Windows you use \\<IP_ADDRESS>\, if you are on MacOS you use smb://<IP_ADDRESS> to connect to the shares.

Please add: \\<IP_ADDRESS>\config

I wasn't able to connect with my credentials from windows without \config. Now it works!

### URL

local home assistant info

### Version

2022.10.3

**Comment by frenck** [comment]
Which page is this feedback for?
