### ISSUE TITLE
Paste icon returns error

### ISSUE THREAD

**Issue by jhbl** [home-assistant/home-assistant.github.io#24520]
### Feedback

In the Chinese language interface, whenever you want to create a numer helper element, go through the following steps: Settings -> Devices & Services -> Helpers -> + CREATE HELPERS -> Create Number.When you want to use the icon that has been copied on the pasteboard, use ctrl+v to paste, and the webpage will be stuck and report an error without response. Finally, an error code will be returned: Out of Memory.
For example, if you have already copied the mdi:led-strip-variant icon with ctrl+c, and you want to paste the icon into the icon option of the newly created helper element with ctrl+v, this situation will occur. 
The English interface has been tested and it happens, but not every time, it happens occasionally.
![icon-1](https://user-images.githubusercontent.com/69311221/195088293-14e287fc-b41f-4b8b-9f7c-b93ded062f3e.png)
![icon-2](https://user-images.githubusercontent.com/69311221/195088306-862ece15-dcb1-4130-97a3-7bf7927453d8.png)
![icon-3](https://user-images.githubusercontent.com/69311221/195088318-ce5d9e8f-4ea7-4faa-8239-9518d855aebf.png)

### URL

https://www.home-assistant.io/docs/configuration/devices/

### Version

2022.10.*

**Comment by frenck** [comment]
Hi there @jhbl!

It seems like you want to report an issue with the Home Assistant frontend, however, you have submitted documentation feedback instead.

Please report issues with the Home Assistant frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
