### ISSUE TITLE
how to reconfig from scract with the google nest

### ISSUE THREAD

**Issue by droneman83** [home-assistant/home-assistant.github.io#24528]
### Feedback

how to get stateded from scratch need a new setup after changes 

### URL

https://www.home-assistant.io/integrations/nest/#configuration

### Version

lates

**Comment by homeassistant** [comment]
Hey there @allenporter, mind taking a look at this feedback as it has been labeled with an integration (`nest`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L415) for? Thanks!

**Comment by droneman83** [comment]
i have figurede it out under intergration and the 3 dot i top corner

**Comment by droneman83** [comment]
but i can still not conect to the project i just say i have to contact my device-access console when i look at the list all files have been created pub sub

**Comment by allenporter** [comment]
ok glad you found the application credentials.  i am having trouble understanding your issue now with device access console. Are you getting a specific error?

**Comment by droneman83** [comment]
this is in danish, i have removede my 2 steps from my google account and redo all of the steps and it still come up with fault
![Skærmbillede 2022-10-12 203652](https://user-images.githubusercontent.com/51987690/195421920-68d26884-629c-4774-841d-55ff2af715a0.jpg)

**Comment by allenporter** [comment]
The common reasons for this "no access to partner" are:
- different accounts used in google cloud console or device access console (check login bar)
- not using a google account but instead using a legacy nest account
- not having any devices on the google account

**Comment by TimB87** [comment]
~~I am having the same issue and been at it for days now.~~
 - I have no different accounts in the cloud console
 - I have never had a legacy nest account
 - my devices show to be linked to my account from within the google home app on my mobile
 - production state of my oauth consent screen is testing

~~What can I do? How do I get logs? It doesn't seem that it even touches the oauth api yet.~~

~~@allenporter can you please give a hint? I have redone the project 2 times already with no other result~~

I think I have been trying to set up the wrong integration.. nevermind.

Edit 2: Definately the wrong integration, I don't own "nest devices", I wanted google assistant which works flawlessly. Sorry for the noise!
