### ISSUE TITLE
Update Hayward Omnilogic integration page to point to HACS version

### ISSUE THREAD

**Issue by knwpsk** [home-assistant/home-assistant.github.io#24525]
### Feedback

If I understand the community chat correctly, this Hayward Omnilogic integration has been abandoned in favor of a newer version on HACS. If that's correct, then it seems like the documentation page should say that.
 

### URL

https://www.home-assistant.io/integrations/omnilogic/

**Comment by homeassistant** [comment]
Hey there @oliver84, @djtimca, @gentoosu, mind taking a look at this feedback as it has been labeled with an integration (`omnilogic`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L450) for? Thanks!

**Comment by knwpsk** [comment]
For example:
https://community.home-assistant.io/t/hayward-omnilogic/122522/170

**Comment by djtimca** [comment]
The core integration still exists, just the developers who worked on the initial version of that have moved on to working on a HACS version and are no longer active in expanding on the core integration. 

That doesn't mean someone else won't pick up the torch on the core, just that we had to point our limited free cycles in a different direction.

**Comment by frenck** [comment]
We don't support custom integrations. PRs to improve and update the core integration are welcome 👍

**Comment by knwpsk** [comment]
@djtimca I can't find the HACS version. I searched for "hayward" and for "omnilogic" in the HACS front end, and it finds nothing. Any help?

**Comment by djtimca** [comment]
It is a custom repository. Add https://GitHub.com/djtimca/haomnilogic to your HACS and you can install from there.

**Comment by knwpsk** [comment]
Found the instructions in your github, thanks. Installing it now.

**Comment by knwpsk** [comment]
OK @djtimca I got it installed.
So... in the Hayward app, I have saved "themes". I click one to shift my system from pool mode to spa mode, and it automatically shifts a couple of valves, turns on the pump (if it's not on), starts the heater, etc. 

How would I replicate that in HA? I don't see Themes represented in the integration (right?).
I assume I can create an Automation for this. But I don't see any entities/devices for my valve controls, either. 
If I click the "on" switch for Spa Filter Pump (which the integration found), will that trigger Omnilogic's routine? or am I too hopeful on that one? :)

p.s. Sorry, I know this ticket may not be the place for this... but don't know how to contact you otherwise. Lead me if you like!

**Comment by djtimca** [comment]
Best is to ask on the add-on GitHub repo rather than here. Themes are not supported. 

Valves should be found as switches generally but the one thing with OmniLogic is that it is extremely flexible and we have found several things that don't necessarily show up the way we would think they should.

**Comment by knwpsk** [comment]
Thanks @djtimca 
https://github.com/djtimca/haomnilogic/issues/37
