### ISSUE TITLE
UNABLE TO SELECT HDMI PORT SOURCE

### ISSUE THREAD

**Issue by antimix** [home-assistant/home-assistant.github.io#24537]
### Feedback

Using:
 Home Assistant 2022.10.3 Supervisor 2022.10.0 Operating System 8.2 Frontend 20221010.0 - latest 

KD-55X8507C
Sony Bravia TV

The source combo list selection only contains TV channels and not the HDMI input ports. So the video source from an external HDMI port can't be selected. However clicking on the Sony Bravia Playing text and getting the details, it is possible to see in the white dialog:

Sony Bravia TV                                             HDMI 4 / ARC
4 minutes ago

-> Source: _the combo area is completely empty and do not contains HDMI 4 / ARC_

so the 4 ports HDMI 1, HDMI2 MHL, HDMI 3, HDMI 4 / ARC are not displayed inside the combo list and can't be selected from the combo.

On the old Sony Bravia integration from the HACS repo, this was working perfectly.

### URL

https://www.home-assistant.io/integrations/braviatv/

### Version

2022.10.3

**Comment by homeassistant** [comment]
Hey there @bieniu, @drafteed, mind taking a look at this feedback as it has been labeled with an integration (`braviatv`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L87) for? Thanks!

**Comment by bieniu** [comment]
You have opened an issue in the documentation repository.  If you have problems with the integration, open an issue in the core repository.

**Comment by antimix** [comment]
ooops :(

**Comment by klaasnicolaas** [comment]
Small side note, avoid text in all capital letters. This comes across as aggressive and you don't want a maintainer to close your issue for those reasons 😉
