### ISSUE TITLE
Data Center <-> Country mapping

### ISSUE THREAD

**Issue by osmeest** [home-assistant/home-assistant.github.io#24545]
### Feedback

In the "Invalid skill id" section, it is referred to some file from the Tuya integration on github.
It might be worth to refer to that file only as a backup since the real source should be in tuya's documentation:
https://developer.tuya.com/en/docs/iot/oem-app-data-center-distributed

### URL

https://www.home-assistant.io/integrations/tuya

**Comment by homeassistant** [comment]
Hey there @tuya, @zlinoliver, @frenck, mind taking a look at this feedback as it has been labeled with an integration (`tuya`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L667) for? Thanks!
