### ISSUE TITLE
Tibber integration suddenly decided to go full error and make 1 cpu core go 100% all the time.

### ISSUE THREAD

**Issue by DuckersMcQuack** [home-assistant/home-assistant.github.io#24571]
### Feedback

"python3 -m homeassistant --config /config" was the process that constantly used 100% of any core at all times.

Could it be because i switched power company a few days ago? that when they turn off the pulse, the HA config will freak out?

![firefox_fQQsOXswV1](https://user-images.githubusercontent.com/9039370/195969134-5a11beeb-9261-4b66-b192-36f54b8f6012.png)

### URL

https://www.home-assistant.io/integrations/tibber

**Comment by Jaeensson** [comment]
I'd like to mention I have a similar issue although I don't see the same warning messages in the log. 
After a while after starting HA the CPU usage shoots through the roof and stays at 100% until I disable the polling or the entire integration on my Intel NUC.

I'm still a paying Tibber customer.

**Comment by enricojonas** [comment]
I have the same issue. After some time CPU goes up to 100% usage. Restarting the Tibber integration fixes it...

Running HA 2022.10.5 on HA OS 9.2 (latest versions).

I am also a paying Tibber customer.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by DuckersMcQuack** [comment]
Alrighty, but i've deactivated it as tibber did a bad on their decision on how they do bills as well by "estimating", essentially "guessing" how much power we use to charge us for 1.5 months, essentially "borrowing money", so moved over to another power company that doesn't screw over the customers. So i do not need it anymore.
