### ISSUE TITLE
Missing Error Message SmartThings Integration: Unable to setup the SmartApp.

### ISSUE THREAD

**Issue by orandasoft** [home-assistant/home-assistant.github.io#24573]
### Feedback

While entering the Personal Access Token for the SmartThings integration, I am getting this error: "Unable to setup the SmartApp. Please try again." This error is not documented.

### URL

https://www.home-assistant.io/integrations/smartthings/

### Version

2022.10.3

**Comment by Skyline-23** [comment]
I also get same problem.

**Comment by geovass1976** [comment]
I am having the same issue as well. This error message appears a few time i got "Unknown error occured".

**Comment by jmajerus** [comment]
Same issue. 
"Please try again": such classic line. ;-)
