### ISSUE TITLE
Integration with Home connect documentation

### ISSUE THREAD

**Issue by vitormcbarros** [home-assistant/home-assistant.github.io#24598]
### Feedback

I had a lot of back and forth until getting the to the right solution, suggesting some fixes on documentation:

Replace link 
https://my.home-assistant.io/redirect/oauth
with:
https://my.home-assistant.io/auth/external/callback 

Second:
On the "I have manually disabled the My Home Assistant" section.
By default the installation came with it disabled I guess...
I had to activate and configure and then the registration process worked flawlessly.

### URL

https://my.home-assistant.io/redirect/oauth

### Version

2022.10.4

**Comment by frenck** [comment]
> Replace link
> https://my.home-assistant.io/redirect/oauth
> with:
> https://my.home-assistant.io/auth/external/callback

That suggestion is incorrect, it must be exactly `https://my.home-assistant.io/redirect/oauth`.


> By default the installation came with it disabled I guess...

No, it is enabled by default and part of the default configuration. See also: <https://www.home-assistant.io/integrations/default_config>
