### ISSUE TITLE
Code to add image of game being played

### ISSUE THREAD

**Issue by kmanan** [home-assistant/home-assistant.github.io#24608]
### Feedback

Would it be possible to add the code to show currently being played / last played game?

### URL

https://www.home-assistant.io/integrations/steam_online#examples

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
