### ISSUE TITLE
Please provide more information about restarting dbus

### ISSUE THREAD

**Issue by sibay** [home-assistant/home-assistant.github.io#24623]
### Feedback

on the dbus issue page is only a short help:

"If the D-Bus daemon is not running, start it."  

But how? PLease provide a link, bash command, ....

Thanks

### URL

https://www.home-assistant.io/more-info/unsupported/dbus

**Comment by frenck** [comment]
This is regarding a supervised installation, right?

**Comment by sibay** [comment]
i installed this way: https://www.home-assistant.io/installation/raspberrypi

**Comment by frenck** [comment]
@sibay There are three ways listed on that page. Which installation type are you using that needs this?

**Comment by sibay** [comment]
sorry, i didnt scrolled down.
i used the "Install Home Assistant Operating System" path.

**Comment by frenck** [comment]
This should not be able to happen on a system running the Home Assistant operating system.

Please consider opening an issue on the Supervisor project instead.

../Frenck
