### ISSUE TITLE
Energy integration: Missing information energy configuration

### ISSUE THREAD

**Issue by degrashopper** [home-assistant/home-assistant.github.io#24640]
### Feedback

On the energy integration page the following text is missing.

Configured by default
This dashboard is by default configured and installed, and you don’t need to configure it yourself, unless you’ve disabled or removed the [default_config:](https://www.home-assistant.io/integrations/default_config/) line from your YAML configuration.

If that is the case, you will need to add the energy: integration manually.

### URL

https://www.home-assistant.io/docs/energy

### Version

2022.10.4

**Comment by klaasnicolaas** [comment]
This information is included in the FAQ:

https://www.home-assistant.io/docs/energy/faq/#the-energy-panel-is-not-visible
