### ISSUE TITLE
Axis M3206-LVE enteties

### ISSUE THREAD

**Issue by renaatdb** [home-assistant/home-assistant.github.io#24655]
### Feedback

Hello
I have 2 Axis camera's M3206-LVE 
One camera give me 11 entities, the other one gives me only 1 entity.
Both camera's have same firmware  version: 10.12.114 (latest).
The 2 camera's have the same settings.
Both camera's are connected with same router Netgear.
Home Assistant:
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend-versie: 20221010.0 - latest

![Axis1](https://user-images.githubusercontent.com/5012211/197340915-1c71e5e4-2fbb-4812-8260-066473ed4744.jpg)
![Axis2](https://user-images.githubusercontent.com/5012211/197340926-530453d5-e32f-477e-b8bf-069645e598e8.jpg)

What can be the issue?
Regards
renaatdb

### URL

https://www.home-assistant.io/integrations/axis

### Version

2022.10.5

### Additional information

Camera LVE 0: 
I see no sensors and no infraled light and output 1 control
![Axis3](https://user-images.githubusercontent.com/5012211/197341516-9424c6b4-b7d4-4f57-857d-abfca8079cc5.jpg)
Camera LVE 1:
I see 8 sensors and 2 controls  (infraled light and output 1)
![Axis4](https://user-images.githubusercontent.com/5012211/197341537-c8f7147b-e524-4957-95eb-7f8b1da9eecd.jpg)

**Comment by frenck** [comment]
Hi there @renaatdb 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
