### ISSUE TITLE
iBeacon Integration, Known working devices.

### ISSUE THREAD

**Issue by ledhed-jgh** [home-assistant/home-assistant.github.io#24650]
### Feedback

I can confirm the following iBeacons also work with the integration:
- Bluecharm BC063B (Water Resistant)
- Tesla Model 3 (and probably S,X,Y)

### URL

https://www.home-assistant.io/integrations/ibeacon

### Version

2022.10.5

### Additional information

Sorry if this is the wrong place to report this, I wasn't sure where else I could provide the information.

**Comment by bdraco** [comment]
Here is the link to edit the docs:

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/ibeacon.markdown

**Comment by ledhed-jgh** [comment]
Thanks.  Changes proposed.
