### ISSUE TITLE
Tesla Powerwall Integration Broken

### ISSUE THREAD

**Issue by TechnicallyBob202** [home-assistant/home-assistant.github.io#24664]
### Feedback

The Tesla Powerwall integration broke yesterday.  I noticed that the integration was not working when the entity on my dashboard was not reporting.

I tried to reload the integration, and that did not work.  I deleted the integration and tried to add it again, and that did not work.  I browsed to the login for my Powerwall, and noticed that it now asks for a username as well as the password, so I suspect that is the change that Tesla implemented which broke the integration.

### URL

https://www.home-assistant.io/integrations/powerwall/

**Comment by klaasnicolaas** [comment]
Hi there @rlyons20  👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
