### ISSUE TITLE
Problem with special characters in dashboard

### ISSUE THREAD

**Issue by dxfoxd** [home-assistant/home-assistant.github.io#24665]
### Feedback

When experience problems with login the device, try to change the special characters in a password with the hex code. For example, # becomes %23 (don't forget the %). I managed to continue the integration.

### URL

https://www.home-assistant.io/integrations/foscam

### Additional information

Just to help other users experiencing the same issue.

**Comment by frenck** [comment]
Hi there @dxfoxd 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
