### ISSUE TITLE
Manual configuration needs update

### ISSUE THREAD

**Issue by aamoroso** [home-assistant/home-assistant.github.io#24661]
### Feedback

The page mentions to use the "manual configuration above" if the LIFX devices are on a different subnet.  But the section above only shows how to manually add the integration - not how to manually specify the broadcast addresses.  Is the configuration.yaml lifx section still relevant?

### URL

https://www.home-assistant.io/integrations/lifx/

**Comment by Djelibeybi** [comment]
When you start the config flow in the Web UI, it'll ask you for the IP address of the bulb. Configuration via `configuration.yaml` should be migrated to UI config automatically though.

**Comment by aamoroso** [comment]
Thanks for getting back.  I'm unsure what you mean, though.  I don't see any options in the Integrations page - no '...' menu or 'CONFIGURATION' button.  I only see the bulbs it knows about.

(Long story short: some bulbs factory reset themselves after a power outage.  Im having to re-add them and whilst at it I am putting them on an IOT VLAN.)

**Comment by Djelibeybi** [comment]
Click "add integration" and select LIFX. Each bulb is configured as a unique config entry. If you do this manually, it'll prompt for an IP address for the bulb.

**Comment by aamoroso** [comment]
Ah!  Thank you so much!  I thought adding an integration added the LIFX integration itself.  Many thanks once again!!

**Comment by Djelibeybi** [comment]
You're welcome.
