### ISSUE TITLE
Google Sheets Troubleshooting

### ISSUE THREAD

**Issue by pegasy** [home-assistant/home-assistant.github.io#24677]
### Feedback

The Troubleshooting section is quite short and doesn't contain any info on how to actually trubleshoot. 
When I try to add the integration it just tells me to check "the logs", what logs am I supposed to check? Nothing shows up in the HA Core Logs.

I have tried the Prerequisites steps twice now with same result, when I add the integration everything looks great until I click Link Account (on my.home-assistant.io), after that it takes me back to my HA instance, "Loading next step for Google Sheets" for a few seconds and then it just says 'Error while creating spreadsheet, see error log for details'. 
When checking google drive a new sheet is there (or multiple after trying this 5+ times). 

Tried chrome on 2 different pc's and edge, same result everywhere. 

### URL

https://www.home-assistant.io/integrations/google_sheets

### Version

2022.10.5

**Comment by tkdrob** [comment]
The troubleshooting section is short because most of the points where people can get stuck are the instructions during setup. First time I have seen this error reported. Logs are available in the Home Assistant UI. Find the log and post it here. Nothing can be done without it.

**Comment by pegasy** [comment]
After enabling a lower (higher?) log level in HA (usually just log critical) it gave me some help, it seems I also needed to enable the Google Sheets API, not just google drive ~~like the documentation mentions~~ like my dumb eyes read, completly skipping the 2nd line that clearly says "and Google Sheets API".
I think I went wrong click the "Google Developers Console" link and thinking I had enabled everything I needed... Sorry, about wasting your time and thanks for this very useful integration, will be a great way to store statistics long term :)
