### ISSUE TITLE
"Manual configuration steps" macro is missing information

### ISSUE THREAD

**Issue by nickdos** [home-assistant/home-assistant.github.io#24673]
### Feedback

I was trying to install the[`iBeacon tracker` integration](https://www.home-assistant.io/integrations/ibeacon) and attempted to follow the manual installation steps to add it via the UI, as shown here:

![image](https://user-images.githubusercontent.com/532845/197439369-bec8f750-bda7-4fef-8019-da695ac1315a.png)

When I searched for `iBeacon tracker` in the `Add integration` step, I only got a result for `Apple`, not the expected `iBeacon tracker` as the docs described, see screenshot:

![image](https://user-images.githubusercontent.com/532845/197439234-042fd4a9-4749-4e84-873d-ece1ea2fe9e4.png)

There was zero mention of "Apple" on the "iBeacon tracker" documentation page, so I dismissed it as being the wrong thing. After searching a bit more and finally just clicking on the Apple integration for the hell of it, I found there was a **second screen** that showed the integration I was looking for. See: 

![image](https://user-images.githubusercontent.com/532845/197439532-5e205214-afe1-47af-8f92-87b90459845e.png)

I attempted to "improve" the "iBeacon tracker" documentation page but it appears the "manual configuration steps" are added to the page via a dynamic insertion (like a macro).

Therefore I suggest that this "dynamic insertion" (where ever it lives) needs to be updated to be smart enough to know when a given integration is hiding behind a "manufacturer" top-level section and to indicate the user needs to first select the manufacturer and then the integration.

### URL

https://www.home-assistant.io/integrations/ibeacon

**Comment by nickdos** [comment]
While looking at this issue, could the maintainer provide some more information about this line:

> iBeacon devices will be automatically detected and added as they are discovered once the integration has been added via the UI and the [Bluetooth](https://www.home-assistant.io/integrations/bluetooth) integration is enabled and functional.

Where are they added? Please provide explicit instruction about where the devices will appear - will they be associated with the iBeacon integration or the Bluetooth integration, or nether?

**Comment by dannytsang** [comment]
@nickdos it will be added as device on the iBeacon Tracker integration card. Here's an example:
![image](https://user-images.githubusercontent.com/567982/200095468-6065c91c-27e8-45e6-bf11-9df3aca27840.png)

I see your point about being under Apple.
