### ISSUE TITLE
.markdown postfix on all integration names

### ISSUE THREAD

**Issue by mvdwetering** [home-assistant/home-assistant.github.io#24681]
### Feedback

On all integrations (or at least the 5 or so I looked at) there is a ".markdown" postfix on the integration name which seems unintended.

e.g. from https://www.home-assistant.io/integrations/octoprint/
> The octoprint.*markdown* integration was introduced in Home Assistant 0.19, and...

![image](https://user-images.githubusercontent.com/732514/197619217-7b624d5f-df39-4a8e-a0a6-7d73fa633939.png)

I expect that it should be without ".markdown":
> The octoprint integration was introduced in Home Assistant 0.19, and...

I tried to figure out the templates, but can't find where it gets added :/ 

### URL

https://www.home-assistant.io/integrations/octoprint/

### Version

2202.10.5

**Comment by mvdwetering** [comment]
Ow, I did not intend to mark this as an issue with octoprint that was just an example. How do I fix that?

**Comment by frenck** [comment]
It's ok! Don't worry

**Comment by mvdwetering** [comment]
It is fine now
![image](https://user-images.githubusercontent.com/732514/209436007-f01d8b75-b4f7-4bd1-ae47-a4eea0aa4d41.png)
