### ISSUE TITLE
RFID example not working anymore

### ISSUE THREAD

**Issue by RoelHermus** [home-assistant/home-assistant.github.io#24690]
### Feedback

I try this example, but it gives an error in the 2022.10.5 error. The example is 2 years old and I think I needs un update. May be there was an update in YAML.

### URL

https://www.home-assistant.io/integrations/tag/

### Version

2022.10.5

**Comment by frenck** [comment]
It looks valid to me? What is the error you are experiencing?

**Comment by RoelHermus** [comment]
Message malformed: extra keys not allowed @ data['automation']
But lets close this topic.
