### ISSUE TITLE
devicetracker.see

### ISSUE THREAD

**Issue by simatao** [home-assistant/home-assistant.github.io#24699]
### Feedback

Hi, where shall I enter or call the devicetracker.see service? it doesnt show up in the developer tools services section.

### URL

https://www.home-assistant.io/integrations/device_tracker/

**Comment by frenck** [comment]
> Hi, where shall I enter or call the devicetracker.see service? it doesnt show up in the developer tools services section.

That is the right location. It will also show up in automation editors.

However, the service will only be available if actual device trackers are present in the system. If there is no device tracker, the device tracker integration will not be loaded.

../Frenck
