### ISSUE TITLE
Tuya devices are useless in home assistant without the tuya cloud subscription

### ISSUE THREAD

**Issue by antonsfed** [home-assistant/home-assistant.github.io#24693]
### Feedback

all good but after a month your trial on the tuya cloud platform expires and you can't do much apart from getting trial extended for 6 more months. After that they offer you to purchase a yearly subscription of 25.000$ or 50.000$ and that costs much much more than it should. They provide no options to pay for requests as it would be with normal platforms such as AWS - which should be totally fine. 

### URL

https://www.home-assistant.io/integrations/tuya

**Comment by frenck** [comment]
As per documentation, the needed subscriptions can be extended in increments of 6 months as the time.

![image](https://user-images.githubusercontent.com/195327/197782231-933a0519-6f9d-491d-9f27-f1229a4a366b.png)

https://www.home-assistant.io/integrations/tuya#28841002-no-permissions-your-subscription-to-cloud-development-plan-has-expired

From the Home Assistant perspective, there is not much we can do. Feel free to contact Tuya support and let them know you don't agree. (I, for one, wish they made this all unneeded).

../Frenck

**Comment by antonsfed** [comment]
yeah, already did that. Both, extended and contacted support... really sad
that tuya doesn't have proper options for developing small apps

BR
Antons
