### ISSUE TITLE
MQTT: Device tracker with gps coords should set location based on areas in home assistant

### ISSUE THREAD

**Issue by yusijs** [home-assistant/home-assistant.github.io#24703]
### Feedback

See #23398 - issue was never looked into it seems, and it still makes no sense. I have an OVMS module in my car that sends the gps coordinates via an api. I use this api to send the coordinates to mqtt/home assistant, which knows about my zones. I dont have just home/not home, but I have multiple zones defined (i.e home, work, gym etc), and it would be great if it could be documented how this could be achieved in home assistant. 

I assume this is possible and the documentation is just missing, as #23398 mentions it being possible previously.

Thanks :)

### URL

https://www.home-assistant.io/integrations/device_tracker.mqtt/

### Version

2022.10.4

**Comment by ShadowJonathan** [comment]
I have this same issue, I currently [setup my airtags](https://community.home-assistant.io/t/is-there-any-way-to-track-apple-airtags-via-home-assistant/389049/8) to be tracked, and I wanted to display or add automations wrt what zones they would exist in.

However, I found that after I removed the `/state`-setting bit of that script (that publishes to MQTT), it would not update based on zone, no matter how much I would tweak the coordinates.

However, at the same time, I also want to publish `unavailable` if the airtag information becomes too old, so the `/state`-setting has to be used in some way.

Maybe, for MQTT, it should allow a magical value `auto`/`.auto`/`_auto` to derive its location from the coordinates, like a regular device tracker?

**Comment by ShadowJonathan** [comment]
According to the `TrackerEntity` class, in [these lines](https://github.com/home-assistant/core/blob/b7b7cdcfcf7e2838a4f4442e2e5ace594113a51c/homeassistant/components/device_tracker/config_entry.py#L247-L264), it seems that the tracker entity itself will try to extract the zone name if `location_name` is none...?

Looking at the code, this looks like a simple-enough fix and pull request.

**Comment by ShadowJonathan** [comment]
Narrator: "It was a simple-enough fix and pull request"

:)
