### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by theailer** [home-assistant/home-assistant.github.io#24701]
### Feedback

Hi.
Would it be possible to add a blacklist in order to not get notifications for certain stuff like specific automations ?

### URL

https://www.home-assistant.io/integrations/repairs/

**Comment by frenck** [comment]
That is not possible. Raised repairs should only be raised if they are an actual issue, if they are not, you should file an issue in our issue tracker instead so it can be fixed.

**Comment by theailer** [comment]
Ok, I might have phrased it wrong. Is it possible to add an ignore option to a specific repair notification in order for it to not appear again?

Med vänlig hälsning
Joakim

**Comment by frenck** [comment]
Repairs can be ignored if version bound (an ignore button will show up), which will ignore the raised issue until the next version. For generic (non-version bound) issues, those can be solved/go away by fixing the issue.

../Frenck
