### ISSUE TITLE
How to get to the first screen ( create account ) ???

### ISSUE THREAD

**Issue by gsarider** [home-assistant/home-assistant.github.io#24707]
### Feedback

Would be great if you explained how to get to the create account screen. Browser ?  telnet ?   local app ? Command line ?? 

### URL

https://www.home-assistant.io/getting-started/onboarding/

**Comment by frenck** [comment]
Hi there @gsarider 👋 

This is the getting started / onboarding documentation. During onboarding / first time set up, Home Assistant will ask for that. There is no specific action needed for that.

Maybe I am misunderstanding your question?

../Frenck

**Comment by gsarider** [comment]
Nope, but I am on Mac  :-) - had to tweak docker-compose file a bit.  On macOS you need to have explicit port translation listed,  doing host mode does not present 8123 to outside. That is Mac limitation.. so thanks for the answer. 


  \#    network_mode: host

    ports:
      - 8123:8123


Take care and thanks !
_zjt

**Comment by frenck** [comment]
Please note, running Home Assistant requires to be run on the host network. The set up you are using now is not supported.

Closing the issue on this end 👍 

../Frenck
