### ISSUE TITLE
Sensor Card shows multiplied values for Power (W)

### ISSUE THREAD

**Issue by alexovy** [home-assistant/home-assistant.github.io#24719]
### Feedback

Hi, on on HA, the Sensor Card shows the Power multiplied by 10.
So, instead of 120 W, it shows 1200 W.
The entity comes from a Smart Plug connected with HA through TUYA integration.
In the TUYA app, the values are correct.

### URL

https://www.home-assistant.io/dashboards/sensor/

### Version

Home Assistant 2022.10.4

**Comment by frenck** [comment]
Hi there @alexovy 👋 

It seems like you want to report an issue, however, you have submitted documentation feedback instead. Please check out help page on where to report your issue:

https://www.home-assistant.io/help

Thanks! 👍 

../Frenc
