### ISSUE TITLE
Chipolo ONE also works

### ISSUE THREAD

**Issue by AvdH** [home-assistant/home-assistant.github.io#24713]
### Feedback

The Chipolo ONE also works

### URL

https://www.home-assistant.io/integrations/ibeacon

### Version

2022.10.5

**Comment by bdraco** [comment]
Hi @AvdH 

Here is the link to edit the page: https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/ibeacon.markdown

Cheers

**Comment by pattyland** [comment]
@AvdH I've added your beacon, I hope you don't mind!

**Comment by bdraco** [comment]
Thanks @pattyland
