### ISSUE TITLE
O container docker vem sem o supervisor 

### ISSUE THREAD

**Issue by Mrmichelerocha** [home-assistant/home-assistant.github.io#24717]
### Feedback

alem do container vir sem o supervisor, a minha tentativa usando a virtual box no ubuntu 22.04 não mostra o IPV4 que estou conecatada pra acessar. 

### URL

http://localhost:8123/config/integrations

### Version

não sei 

### Additional information

seria legal melhorar isso ai

**Comment by pattyland** [comment]
Please put all tickets on GitHub, including this project, in English.
This repository is also for the home-assistant.io website and what little I can make out from your text sounds like problems with Home Assistant Core!

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for providing support. In addition, English is the default language and we cannot help you further in another language. If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or the [Community forum](https://community.home-assistant.io).

Thanks! 👍
