### ISSUE TITLE
Growatt

### ISSUE THREAD

**Issue by jeandredebeer** [home-assistant/home-assistant.github.io#24722]
### Feedback

Im getting an unknown error when connecting my Growatt inverters to home assistant. It always worked but stopped a couply of days ago.

I have tried it on 2 HA servers with different HA versions and they both get the same error message.
![image](https://user-images.githubusercontent.com/52071425/198551570-0dc27b37-be54-480f-869c-5541ca7c8469.png)
 

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

Home Assistant 2022.10.5 Supervisor 2022.10.0 Operating System 9.3 Frontend 20221010.0 - latest

**Comment by muppet3000** [comment]
I'm almost certain that this is as a result of the issues being experienced & detailed over here: https://github.com/home-assistant/core/issues/80950
If you apply the fix suggested in the comments here: https://github.com/home-assistant/core/issues/80950#issuecomment-1294065153

Then try again you should be able to get it to work, alternatively, wait a few days and the fix should be released for everyone via the correct channel.

**Comment by jeandredebeer** [comment]
> I'm almost certain that this is as a result of the issues being experienced & detailed over here: [home-assistant/core#80950](https://github.com/home-assistant/core/issues/80950) If you apply the fix suggested in the comments here: [home-assistant/core#80950 (comment)](https://github.com/home-assistant/core/issues/80950#issuecomment-1294065153)
> 
> Then try again you should be able to get it to work, alternatively, wait a few days and the fix should be released for everyone via the correct channel.

Sorry I dont have a lot of linux / terminal experience.  When I open terminal and type pip show growattServer I get the following error - can you please assist me?

![image](https://user-images.githubusercontent.com/52071425/198558762-dbc0a3a3-d936-4ab0-8a97-c5ea4d787db6.png)

**Comment by JasperPlant** [comment]
If you run the following command you might have more luck.

`docker exec -it homeassistant /bin/bash`

you can test if this works by executing the `pip show growattServer` command again.

**Comment by frenck** [comment]
@JasperPlant That is not a recommended or supported method.


Anyways, closing this issue on this end, as it was submitted as documentation feedback (which this isn't 😄 ) Please track the linked issue above instead.

../Frenck

**Comment by jeandredebeer** [comment]
Thanks for the assistance – but I get this error when typing your command

**Comment by muppet3000** [comment]
The fix had been merged for this so should be available in the next release or the nightly Dev build, so you shouldn't need to be trying to get the workaround to work.

**Comment by jeandredebeer** [comment]
Hi – What must I do to get the integration to work again?

**Comment by muppet3000** [comment]
Look at the other thread that was linked to from this one.

**Comment by jeandredebeer** [comment]
Hi- When will the new version be released where the integration is fixed?

 

 

 

 

From: muppet3000 ***@***.***>
Reply to: "home-assistant/home-assistant.io" ***@***.***>
Date: Saturday, 29 October 2022 at 09:50
To: "home-assistant/home-assistant.io" ***@***.***>
Cc: jeandredebeer ***@***.***>, Author ***@***.***>
Subject: Re: [home-assistant/home-assistant.io] Growatt (Issue #24722)

 

The fix had been merged for this so should be available in the next release or the nightly Dev build, so you shouldn't need to be trying to get the workaround to work.

**Comment by muppet3000** [comment]
It's already available in the latest beta.

**Comment by jeandredebeer** [comment]
Thanks – how do I get the beta?

 

I installed the growatt service from settings / devices and integrations.  I uninstalled and reinstalled but it did not fix it – probably because Im on main and not beta service?

 

 

 

 

 

 ***@***.***> 

 <http://itexperts.dyndns.org:8040/>  <http://www.itexperts.co.za/>

**Comment by muppet3000** [comment]
I don't know, it depends on what version of HA you're running and how you're running it. I think there's something in the settings to help you to do it.

However, looking at the developer site the next release is available tomorrow: https://www.home-assistant.io/faq/release/

So if you're finding it difficult/wasting time on it it might just make sense to wait 1 more day

**Comment by jeandredebeer** [comment]
Thanks will wait for tomorrow :)

 

 

 

 

 

 ***@***.***> 

 <http://itexperts.dyndns.org:8040/>  <http://www.itexperts.co.za/>

**Comment by jeandredebeer** [comment]
Hi – it seems like the integration is not working again?

 

 

 

 

 

 ***@***.***> 

 <http://itexperts.dyndns.org:8040/>  <http://www.itexperts.co.za/>

**Comment by muppet3000** [comment]
That's because there was a change on the server (similar to last time) and the fix is still not released in the up-stream library.
You can follow the progress, just like last time here: https://github.com/home-assistant/core/issues/81951

This ticket is closed and is also in the wrong repo, this repo is for the documentation, not Home Assistant Core or it's integrations.
