### ISSUE TITLE
Shelly integration documentation

### ISSUE THREAD

**Issue by VdR1960** [home-assistant/home-assistant.github.io#24724]
### Feedback

Last bullet on manual install says "Follow the instruction on screen to complete the set up". There are no instructions, have to fill in a field titled "host" no indication as to what that might be, a name, an IP address, ... The "?" button circles back to the Shelly integration page.

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2022.10.5

**Comment by dannytsang** [comment]
It should be the network address of your shelly device. Whether that is an IP address e.g. 192.168.1.1 or domain name shelly1234.local

**Comment by VdR1960** [comment]
Thank you. Of course eventually I got it working. Just thought a more helpful help would been of help. :-)

**Comment by chemelli74** [comment]
> Thank you. Of course eventually I got it working. Just thought a more helpful help would been of help. :-)

Please feel free to update the documentation.

Simone
