### ISSUE TITLE
Home assistant basis setup, Philips TV 

### ISSUE THREAD

**Issue by GGBMLC** [home-assistant/home-assistant.github.io#24731]
### Feedback

Hi.
I have now connection to my TV. 
But is not able to use the "user guide" at Home Assisant.
https://www.home-assistant.io/integrations/philips_js/

Please add a  basis example of how to:
Send one "Features" to the TV. Like Volume up or down.

Step by step guide. 

Do I need to add info to Configuration. yaml?
Other setting ?
What GUI in HA do I need to use?

Same for the remote control.

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2022.10.05

**Comment by elupus** [comment]
There is a big button on that page on how to add the integration. No yaml required. For remote control, check the services of the remote integration. But usually not needed

**Comment by GGBMLC** [comment]
Yes.  but still missing info. 

How to create a Home assistant "scene" for the TV
Like: 

- TV on
- Set volume to 15
- Set HDMI to 2

**Comment by elupus** [comment]
That has nothing to do with this integration. That is standard home assistant features. Look for standard scenes om home assistant info.
