### ISSUE TITLE
Telegram Polling website bad link

### ISSUE THREAD

**Issue by Hadjimina** [home-assistant/home-assistant.github.io#2474]
Heyo
So the link on the bottom of [this page](https://home-assistant.io/components/telegram_bot.polling/) this page redirects to [https://home-assistant.io/components.notify.telegram](https://home-assistant.io/components.notify.telegram) however it should be [https://home-assistant.io/components/notify.telegram](https://home-assistant.io/components/notify.telegram)

Cheers

**Comment by fabaff** [comment]
Looks like that this was fixed.
