### ISSUE TITLE
Issues with VirtualBox

### ISSUE THREAD

**Issue by Dirk68** [home-assistant/home-assistant.github.io#24758]
### Feedback

It seems like the VirtualBox VM must have exactly 2048MB of RAM assigned. 
The documentation says "minimum of 2048MB", so in the first attempt I configured it to 4096 MB. I never got this machine booting up, it always stopped in the EFI console. 
When I started again from scatch with 2048 MB, everything worked as expected.

### URL

https://www.home-assistant.io/installation/windows

### Additional information

VirtualBox 7.0.2

**Comment by frenck** [comment]
Hi there @Dirk68 👋 

It seems like you want to report an issue with the Home Assistant operating system, however, you have submitted documentation feedback instead.

Please report issues with our operating system here:

<https://github.com/home-assistant/operating-system/issues>

Thanks! 👍 

../Frenck
