### ISSUE TITLE
Tesla Powerwall documentation sensor descriptions are not useful

### ISSUE THREAD

**Issue by dnschnur** [home-assistant/home-assistant.github.io#24765]
### Feedback

The Tesla Powerwall sensor descriptions in the docs simply mirror the entity names, without making it clear what the values actually mean. For example, "Powerwall Load Import - Load energy imported in kWh": is this the amount imported from the grid? The amount used by the house? The amount transferred from the panels to the battery?

Someone new to this integration can't understand what any of these mean without spending time looking at each values and correlating them with what's shown in the Tesla app.

### URL

https://www.home-assistant.io/integrations/powerwall

**Comment by bdraco** [comment]
Here is the link to edit the docs:
https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/powerwall.markdown

**Comment by dnschnur** [comment]
I filed a bug because I don't know what the correct descriptions are. I can
figure out some of them, but the rest require someone familiar with the
code.

**Comment by dnschnur** [comment]
E.g. see
https://community.home-assistant.io/t/tesla-powerwall-and-home-energy-management/335228,
where lots of people are confused about which values to use.

**Comment by dnschnur** [comment]
Still relevant.
