### ISSUE TITLE
Not documented how to obtain nVent authentication credentials

### ISSUE THREAD

**Issue by mansson** [home-assistant/home-assistant.github.io#24768]
### Feedback

The instructions on the integration page refers to HA and vice versa. There is nowhere any hints to how to obtain the OAUTH parameters for nVent RAYCHEM SENZ 
I managed to do it before, but the integration was broken in 2022.10.0 and I am trying to reinstall the integration in 2022.10.5
I just need to know where to go to find the Application Credentials. It's probably somewhere near https://api.senzthermostat.nvent.com or
https://id.senzthermostat.nvent.com/Account/

### URL

https://www.home-assistant.io/integrations/senz

### Version

2022.10.1

**Comment by mansson** [comment]
On https://api.senzthermostat.nvent.com/ it says: "To gain access to the API, first you must contact our support department to get access to a ClientID".
That can't be right. Are they going to send out an email to every single person in the world that wants to control a thermostat?

**Comment by Klench** [comment]
I have exactly the same experience. @milanmeu it would be great if you can address this issue as the electricity price is so high nowadays. Thank you for your awesome work!

**Comment by timjackson** [comment]
I'm just another user, but I haven't needed to sign up for API credentials. When adding the Senz integration to HA, I'm sent (via Account Link) to a page on the nVent website (id.senzthermostat.nvent.com) where I log in with the _credentials I set up when installing the thermostats_.

That said, I experience the issue that after each HA upgrade, I have to remove and re-add the Senz integration (see [issue #83274](https://github.com/home-assistant/core/issues/83274))
