### ISSUE TITLE
Android TV Custom State Detection Rules Documentation

### ISSUE THREAD

**Issue by StephaneM60** [home-assistant/home-assistant.github.io#24777]
### Feedback

Hi,

I'm currently trying to create some custom dection rules for a new Google TV and I can't figure how to create the rules and the documentation doesn't explain how to input the rules in the UI.

for instance, I want that whenever the "com.tcl.tv" app is running the state of the media player is "playing"

In the UI, I add a new rule and there is two fields : I type com.tcl.tv in the first one and playing in the second one, press on the save button and the UI complains that the rule is not valid in the second field (without providing a sample)

I tried : 'playing' / - 'playing' /  ['playing'] / 'playing':

I can't figure what is needed to create the rule...

### URL

https://www.home-assistant.io/integrations/androidtv/

**Comment by PremiumUsername** [comment]
I'd like to know this too. All the documentation is about altering the yaml-config. Just one example of how to use the UI would do a lot of good.

**Comment by ollo69** [comment]
When PR [#84412](https://github.com/home-assistant/core/pull/84412) will be merged you will be able to enter detection rules in Yaml format as explained in documentation.

**Comment by PremiumUsername** [comment]
I managed to get it working in the meantime using:
`[{"idle": {"wake_lock_size": 0}}, {"idle": {"wake_lock_size": 1}}, {"idle": {"wake_lock_size": 2}}, {"idle": {"wake_lock_size": 3}}, "playing"]`

@ollo69  It's a bit tangential to the question at hand but I think CPU utilisation could be another useful way to detect state. You could examine the CPU utilisation either for the application itself or for `media.codec`. If you could filter for a threshold cpu value, you could at least help detect the playing state with a high degree of certainty for many applications. I was trying to detect the states of GeforceNow, but I wasn't able to detect the states with the exiting types of filtering. CPU utilisation is what could have done the trick for me.
