### ISSUE TITLE
Automations.yaml

### ISSUE THREAD

**Issue by Strikky** [home-assistant/home-assistant.github.io#24770]
### Feedback

My file automation.yaml more then 2.000 lines!!!

Even no empty line between the automations.

Can this not better?
Split the automation.yaml file in separate automations!!

### URL

https://www.home-assistant.io/docs/automation/

**Comment by frenck** [comment]
> My file automation.yaml more then 2.000 lines!!!

> Can this not better?

It is managed by UI, so it doesn't matter that much.

> Split the automation.yaml file in separate automation!!

You can do that if you like. For more information about that see:

<https://www.home-assistant.io/docs/configuration/splitting_configuration/>


Closing this issue, as it isn't documentation feedback.

../Frenck
