### ISSUE TITLE
Energy page

### ISSUE THREAD

**Issue by tech9cal** [home-assistant/home-assistant.github.io#24789]
### Feedback

Gas has gradually become a swear word in Europe.
Therefore, it is less relevant with the heading "Gas consumption" on Energy page, can it be made so that we ourselves can rename the heading to "Heat pump"
![Skærmbillede 2022-11-02 kl  18 38 58](https://user-images.githubusercontent.com/65071779/199562345-94ec31cc-6507-44c9-98d2-3354b2301647.png)

**Comment by frenck** [comment]
> Gas has gradually become a swear word in Europe.

Never heard of that one before, and I live in Europe too.
The heat pump would not be accurate. While it does support heat pumps, its primary use case is tracking gas usage.

Anyways, you have submitted documentation feedback. There is no amount of documentation I can adjust to change something in the Home Assistant UI. Therefore, closing the issue on this end.

../Frenck

**Comment by tech9cal** [comment]
Dear Frank,
Thank you for taking the time to reply.
Gas will certainly be phased out in Europe within a short number of years, so I don't quite know which country you live in?

But why cut off all of us the opportunity to show a heat pump instead of a gas boiler on the energy page?

Best regards Ole

TECH9CAL
Ole Finn Sørensen
M af I Stærkstrømsingeniør
Lindevej 5
DK-4340 Tølløse
[Facebook]<https://www.facebook.com/TECH9CAL>  [LinkedIn] <https://www.linkedin.com/in/ole-finn-sørensen-299a8410?trk=nav_responsive_tab_profile>   [WebSite] <http://www.tech9cal.dk/>   [Adresse] <https://goo.gl/maps/d8chUurfEER2>   [CallMe] <tel:+4570227744>
tel: +45 7022 7744


Fra: Franck Nijhof ***@***.***>
Dato: onsdag, 2. november 2022 kl. 19.05
Til: home-assistant/home-assistant.io ***@***.***>
Cc: Ole Finn Sørensen ***@***.***>, Author ***@***.***>
Emne: Re: [home-assistant/home-assistant.io] Energy page (Issue #24789)

Gas has gradually become a swear word in Europe.

Never heard of that one before, and I live in Europe too.
The heat pump would not be accurate. While it does support heat pumps, its primary use case is tracking gas usage.

Anyways, you have submitted documentation feedback. There is no amount of documentation I can adjust to change something in the Home Assistant UI. Therefore, closing the issue on this end.

../Frenck

**Comment by frenck** [comment]
> But why cut off all of us the opportunity to show a heat pump instead of a gas boiler on the energy page?

I didn't say that. Please read my response. Also, you might not consider replying using email, but use the GitHub web interface instead. You might want to take a look how your response looks like on GitHub.

**Comment by tech9cal** [comment]
Sorry I'm not an experienced user of GitHub.
I simply came up with a suggestion to be able to change a heading on your energy page.
Please forget that I contacted you.
enjoy your evening, best regards Ole

TECH9CAL
Ole Finn Sørensen
M af I Stærkstrømsingeniør
Lindevej 5
DK-4340 Tølløse
[Facebook]<https://www.facebook.com/TECH9CAL>  [LinkedIn] <https://www.linkedin.com/in/ole-finn-sørensen-299a8410?trk=nav_responsive_tab_profile>   [WebSite] <http://www.tech9cal.dk/>   [Adresse] <https://goo.gl/maps/d8chUurfEER2>   [CallMe] <tel:+4570227744>
tel: +45 7022 7744


Fra: Franck Nijhof ***@***.***>
Dato: onsdag, 2. november 2022 kl. 19.52
Til: home-assistant/home-assistant.io ***@***.***>
Cc: Ole Finn Sørensen ***@***.***>, Author ***@***.***>
Emne: Re: [home-assistant/home-assistant.io] Energy page (Issue #24789)

But why cut off all of us the opportunity to show a heat pump instead of a gas boiler on the energy page?

I didn't say that. Please read my response. Also, you might not consider replying using email, but use the GitHub web interface instead. You might want to take a look how your response looks like on GitHub.

**Comment by frenck** [comment]
> I simply came up with a suggestion to be able to change a heading on your energy pag

I get that, but you submitted documentation feedback instead. Please submit feature requests to our community forums.

If you are unsure where to go, please check https://www.home-assistant.io/help

../Frenck

**Comment by tech9cal** [comment]
Dear Franck,
My whole challenge started with me clicking on a link (Home Assistant), with help on the energy page - I think must have ended up with the wrong recipient - I'm very sorry.
Best regards Ole

TECH9CAL
Ole Finn Sørensen
M af I Stærkstrømsingeniør
Lindevej 5
DK-4340 Tølløse
[Facebook]<https://www.facebook.com/TECH9CAL>  [LinkedIn] <https://www.linkedin.com/in/ole-finn-sørensen-299a8410?trk=nav_responsive_tab_profile>   [WebSite] <http://www.tech9cal.dk/>   [Adresse] <https://goo.gl/maps/d8chUurfEER2>   [CallMe] <tel:+4570227744>
tel: +45 7022 7744


Fra: Franck Nijhof ***@***.***>
Dato: onsdag, 2. november 2022 kl. 20.08
Til: home-assistant/home-assistant.io ***@***.***>
Cc: Ole Finn Sørensen ***@***.***>, Author ***@***.***>
Emne: Re: [home-assistant/home-assistant.io] Energy page (Issue #24789)

I simply came up with a suggestion to be able to change a heading on your energy pag

I get that, but you submitted documentation feedback instead. Please submit feature requests to our community forums.

If you are unsure where to go, please check https://www.home-assistant.io/help

../Frenck
