### ISSUE TITLE
New Zealand Daylight Saving Not working

### ISSUE THREAD

**Issue by ifflanb** [home-assistant/home-assistant.github.io#24784]
### Feedback

I am using the Google Calendar integration and if I log into the actual Google Calendar, my event is set to for example 8:00pm NZT but in Home Assistant Calendar view it shows as 9:00pm. Home Assistant is set to NZ Time Zone.

### URL

https://rc.home-assistant.io/integrations/google

**Comment by allenporter** [comment]
Hi can you instead file the issue against core and complete the issue template information?

**Comment by allenporter** [comment]
@ifflanb please file against https://github.com/home-assistant/core/issues and fill out the template (or see https://www.home-assistant.io/help/reporting_issues/ for more context)
