### ISSUE TITLE
Unable to view Garage Door Opener Camera Model #B4643T on HA

### ISSUE THREAD

**Issue by TonyMontuna** [home-assistant/home-assistant.github.io#24793]
### Feedback

Hi there I am unable to find the camera which is connected to my B4643T garage door opener from Chamberlin SECURE VIEW™ CAMERA ULTRA-QUIET WI-FI GARAGE DOOR OPENER

### URL

https://www.home-assistant.io/integrations/myq/

**Comment by bdraco** [comment]
This integration doesn't have support for MyQ cameras.  Only the platforms listed on the documentation have an implementation:

https://www.home-assistant.io/integrations/myq/

**Comment by TonyMontuna** [comment]
Hi what does that mean? There is no plan to get the cameras running or I did something incorrect On Nov 2, 2022, at 2:49 PM, J. Nick Koston ***@***.***> wrote:﻿
Closed #24793 as not planned.

**Comment by TonyMontuna** [comment]
Oh okay got it. On Nov 2, 2022, at 3:02 PM, Anthony Maffei ***@***.***> wrote:﻿Hi what does that mean? There is no plan to get the cameras running or I did something incorrect On Nov 2, 2022, at 2:49 PM, J. Nick Koston ***@***.***> wrote:﻿
Closed #24793 as not planned.

**Comment by bdraco** [comment]
There is no plan to add camera support to this integration.
