### ISSUE TITLE
Counter - Related to Entity

### ISSUE THREAD

**Issue by jprasm** [home-assistant/home-assistant.github.io#24799]
### Feedback

I would love to see us be able to have a counter show up as related to an entity (right now I believe it is blank/not possible). For example, I have a counter related to my laundry machine which counts cycles. When I go to the 'related' tab within the entity window, there is no relationship shown.
![Screen Shot 2022-11-03 at 08 02 48](https://user-images.githubusercontent.com/80229993/199715865-c773cc14-be73-43d2-b78b-d87db6947281.png)

### URL

https://www.home-assistant.io/integrations/counter/

### Version

Latest

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
