### ISSUE TITLE
iBeacon: source attribute will not change

### ISSUE THREAD

**Issue by multigcs** [home-assistant/home-assistant.github.io#24796]
### Feedback

iBeacon source attribute will not change/updated if i move the iBeacon into another room with another 'esp32_ble_tracker/bluetooth_proxy'

Feature-Request: an attribute with a list of all proxy's and distance that seen the beacon 

### URL

https://www.home-assistant.io/integrations/ibeacon/

### Version

2022.10.5

### Additional information

 Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend 20221010.0 - latest 
esphome: 2022.10.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by multigcs** [comment]
Please ignore 'Feature-Request' line ...

I think this is a bug, the source attribute is not updated !
I see a distance of X meter, but to another source, not to the active one

It is impossible to create an automation depends on the distance, because you don't know the active soure

**Comment by ledhed-jgh** [comment]
I'm having the same issue,  was there a resolution?

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/pull/81740
