### ISSUE TITLE
Watermeter on energy dashboard: entity specs ?

### ISSUE THREAD

**Issue by jjvandenberg** [home-assistant/home-assistant.github.io#24801]
### Feedback

Hi, can you add to the docs, the necessary entity definition for the watermeter, like 
- state_class
- unit_of_measurement
-device_class

Thanks !

### URL

https://www.home-assistant.io/docs/energy/water/

### Version

2022.11

**Comment by fvschie** [comment]
I have issues where my water meter sensors (of type 'total', both in liters and m3) aren't showing up. It's possible it needs a total_increasing, which would be annoying, as that's harder to fabricate.

So I second a list of requirements for the sensor.

**Comment by helmuto-maker** [comment]
I have these settings - but doesn't work and does not show up as possible entity to choose in water - energy dashboard. My gas-meter does show up as possible entity in the water-section:
state_class: total_increasing
unit_of_measurement: m³
icon: mdi:chart-line
friendly_name: Total Water Use Daily
last_reset: '1970-01-01T00:00:00+00:00'
device_class: water

**Comment by helmuto-maker** [comment]
I figured this out. My sensor had two different units in the long term statistics. After fixing this (in developer tools -> statistics), the sensor is available to choose.

**Comment by neuhausf** [comment]
I had that too, but removing the old statistics didn‘t help. My sensor is a restful, total_increasing with unit m3. Additionally I have setup utility_meters for different periods (hourly, daily, weekly, monthly and yearly). Statistics are generating fine. What am I missing?
![884605E0-05B4-4F5E-88ED-2D7AE25559A1](https://user-images.githubusercontent.com/7963239/199894249-bb258a38-6ac3-4e77-a88d-f7b0fbf76214.jpeg)

**Comment by frenck** [comment]
That sounds backwards? You don't adjust entities to make them work with the energy dashboard... instead configure entities correct according to the data they provide. If they provide the right data, they become available for the energy dashboard.

**Comment by jjvandenberg** [comment]
So if the question was "how do i need to configure my entities so the energy dashboard can use them for the water meter", it would have been answered? 
why so unfriendly?

for all that had the same qustion: 
unit_of_measurement: m³ (use an uppercase 3, not a regular 3, that's where I went wrong)
device_class: water

seems more people have this question , like #24813

**Comment by jjvandenberg** [comment]
solved it
unit_of_measurement: m³ 
device_class: water

**Comment by mrandt** [comment]
I had to fiddle with this, too. My watermeter integrates via MQTT.

Eventually I figured out I had to configure the following for my sensor in configuration.yaml:

```
      unit_of_measurement: "m³"
      device_class: water
      state_class: total_increasing
```

With this config, I could integrate the sensor into the Energy Dashboad.

I also had to change the unit of my helper variable to track the costs to "EUR/m³" as "€/m³" did not work ;-)

**Comment by helmuto-maker** [comment]
I find it a bit frustrating that is so difficult to find information on exactly how the sensors should be configured to comply with the energy-dashboard. The dashboard is really excellent, so would be nice with some clear guidance on the sensors (including the cost sensors).

**Comment by helmuto-maker** [comment]
> That sounds backwards? You don't adjust entities to make them work with the energy dashboard... instead configure entities correct according to the data they provide. If they provide the right data, they become available for the energy dashboard.

It is just very difficult to figure out what is "the right data"
