### ISSUE TITLE
Textbox helper: the last text field has an incomprehensible translation

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/home-assistant.github.io#24804]
### Feedback

In Italian language the translation does not even mention the regex scheme.
The text is cut off and ends with the three dots, which, by the way, is not recommended in the MD3 online help:
https://m3.material.io/components/text-fields/guidelines#becfff8e-6128-4f98-8a3c-cf5a5ee1ce72
Imo a reference to the manual would be preferable.

P.s. This is my first time here. If this report is not in the right place please point it out to me

![Img2](https://user-images.githubusercontent.com/74879713/199775568-eb6b61bc-f721-40c9-864e-f9dd17a0d86f.png)

### URL
Helper does not provide a page to the manual

### Version

2022.11.0

**Comment by WRoss7** [comment]
Persistent in 2022.12.8

**Comment by frenck** [comment]
Hi there @WRoss7 👋 

This is the feedback tracker for the documentation. However, it seems like you want to report an issue with the Home Assistant frontend. Please report those issues here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
