### ISSUE TITLE
// Ignored job conditions

### ISSUE THREAD

**Issue by raforo** [home-assistant/home-assistant.github.io#24817]
### Feedback

After a Fix appears "Unsupported system - Protections disabled"  I've read and comply with [https://www.home-assistant.io/more-info/unsupported/job_conditions](url) 
I've made the solution for four times, I've also restarted the Raspberry Pi .
I've deleted all container and software not supported,  but the solution doesn't worked .
It continue as unsupported by   job conditions 

~ ha res info
checks:
- enabled: true
  slug: free_space
- enabled: true
  slug: dns_server
- enabled: true
  slug: backups
- enabled: true
  slug: core_security
- enabled: true
  slug: addon_pwned
- enabled: true
  slug: dns_server_ipv6
- enabled: true
  slug: supervisor_trust
- enabled: true
  slug: network_interface_ipv4
issues: []
suggestions: []
unhealthy: []
unsupported:
- job_conditions

### URL

https://www.home-assistant.io/more-info/unsupported/job_conditions

### Version

Home Assistant 2022.11.1 Supervisor 2022.10.2 Operating System 9.2 Frontend 20221102.1 - latest

### Additional information

Supervisor Log

22-11-04 15:37:34 INFO (MainThread) [supervisor.hardware.monitor] Stopped Supervisor hardware monitor
22-11-04 15:37:34 INFO (MainThread) [supervisor.dbus.manager] Closed conection to system D-Bus.
22-11-04 15:37:34 INFO (MainThread) [supervisor.core] Supervisor is down - 100
22-11-04 15:37:34 INFO (MainThread) [__main__] Closing Supervisor
[14:37:35] INFO: Supervisor restart after closing
22-11-04 14:37:38 INFO (MainThread) [__main__] Initializing Supervisor setup
22-11-04 14:37:39 INFO (MainThread) [supervisor.bootstrap] Initializing Supervisor Sentry
22-11-04 15:37:39 INFO (MainThread) [supervisor.bootstrap] Seting up coresys for machine: raspberrypi4-64
22-11-04 15:37:39 INFO (SyncWorker_0) [supervisor.docker.supervisor] Attaching to Supervisor ghcr.io/home-assistant/aarch64-hassio-supervisor with version 2022.10.2
22-11-04 15:37:39 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-11-04 15:37:39 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.INITIALIZE
22-11-04 15:37:39 WARNING (MainThread) [supervisor.resolution.evaluations.base] Found unsupported job conditions settings. (more-info: https://www.home-assistant.io/more-info/unsupported/job_conditions)
22-11-04 15:37:39 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-11-04 15:37:39 INFO (MainThread) [__main__] Setting up Supervisor
22-11-04 15:37:39 INFO (MainThread) [supervisor.api] Starting API on 172.30.32.2
22-11-04 15:37:40 INFO (MainThread) [supervisor.hardware.monitor] Started Supervisor hardware monitor
22-11-04 15:37:40 INFO (MainThread) [supervisor.dbus.manager] Connected to system D-Bus.
22-11-04 15:37:40 INFO (MainThread) [supervisor.dbus.agent] Load dbus interface io.hass.os
15:37:49 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running

**Comment by frenck** [comment]
Hi there @raforo 👋 

It seems like you want to report a bug, however, you have submitted documentation feedback instead. Please report issues, in this case, in the Supervisor issue tracker:

https://github.com/home-assistant/supervisor/issues

Thanks! 👍 

../Frenck
