### ISSUE TITLE
missing description of how to change units

### ISSUE THREAD

**Issue by Santanachia** [home-assistant/home-assistant.github.io#24812]
### Feedback

My sensor reports consumption in `m³` with an accuracy of 1.0, and on the dashboard appear `L` with an accuracy of 1000.
Such a large number of zeros is completely unnecessary here.

### URL

https://www.home-assistant.io/docs/energy/water/

### Version

2022.10.1

**Comment by frenck** [comment]
Hi there @Santanachia 👋 

Thanks for your comment, however, your comment isn't documentation feedback. Even if we adjusted the documentation, it would still remain the same in Home Assistant. Please use our community forums to provide feedback like this.

Thanks 👍 

../Frenck
