### ISSUE TITLE
Need to provide more details on how to add a MQTT water meter

### ISSUE THREAD

**Issue by mcsquared88** [home-assistant/home-assistant.github.io#24810]
### Feedback

The documentation at https://www.home-assistant.io/docs/energy/water/ shouldn't just point to some commercial off-the-shelf products. It should explain how all of us tinkerers can get this set up. Here's what I suggest be added to the page:

If you already have a sensor configured for your water meter, go to Settings > Dashboards > Energy and then click Add Water Source.

If your water meter sensor isn't listed, be sure your sensor has the following parameters:
* unit_of_measurement: "gal" [NOTE: The Configure water consumption window in the Settings > Dashboards > Energy screen has what I assume is a typo. It states "Water usage (m3 or gl)" but "gl" should be "gal" as that's the correct unit of measurement.]
* device_class: water
* state_class: total_increasing

If your water meter sensor still isn't listed, check that there isn't an issue with there being multiple units of measurement in the statistics history. Go to Developer Tools > Statistics, search for your sensor, and see if there's a reported issue like "The unit of this entity changed from 'Gallons' to 'gal'." If you see that, click Fix Issue and follow the instructions. Then try adding your sensor in Settings > Dashboards > Energy again.

------------------

NOTE: You should also update the page at https://www.home-assistant.io/integrations/utility_meter/ to point to these instructions, as I'm sure a lot of people will think that if they use the Settings > Devices & Services > Helpers GUI to create a utility meter sensor, it should then automatically appear on the Energy dashboard.

Suggested future enhancement: Update the GUI helper for creating a utility meter sensor (Settings > Devices & Services > Helpers > Create Helper > Utility Meter) with some options to add the newly-created sensor to the Energy dashboard.

### URL

https://www.home-assistant.io/docs/energy/water/

**Comment by dgomes** [comment]
Thank @mcsquared88 for the feedback :) But why don't you go ahead and provide this feedback as an actual pull request towards the documentation :) ?

**Comment by mcsquared88** [comment]
Excellent suggestion. I didn't realize I could do that. I've submitted the page change as https://github.com/home-assistant/home-assistant.io/pull/24815#issue-1436073194
