### ISSUE TITLE
cosori

### ISSUE THREAD

**Issue by Ciccio1234567** [home-assistant/home-assistant.github.io#24814]
### Feedback

can you add the cosori wifi air fryer?

### URL

https://www.home-assistant.io/integrations/vesync

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
