### ISSUE TITLE
Can't figure out how to format the text in "message" field of SMTP Notify

### ISSUE THREAD

**Issue by knwpsk** [home-assistant/home-assistant.github.io#24821]
### Feedback

Trying to do very simple formatting of the email body, in the "message" field. Documentation doesn't say how to insert a return character (newline). 
I tried 
\n
and 
`n
And neither of those works.
Any help?
Thanks

### URL

https://www.home-assistant.io/integrations/smtp/

**Comment by buffswinger** [comment]
I'm not sure how to resolve this issue but in reference to another issue you had [here](https://github.com/home-assistant/core/issues/74242), I was able to add the current battery level and other fields on Tank_Utility. Sorry for posting on this thread, I couldn't add to the original thread. If you are interested, send me an email and I can walk you through it
