### ISSUE TITLE
Getting error on backup.create. I think it's hassio.backup_full now?

### ISSUE THREAD

**Issue by sandervandenberg** [home-assistant/home-assistant.github.io#24820]
### Feedback

This is the error I get:

The automation "Backup Home Assistant" (automation.backup_home_assistant) has an action that calls an unknown service: backup.create.

This is in version 2022.10.5

And if you update the example yaml: It would be really nice (for a novice user like me) if I could just copy paste everything in the code box and that it then works. Now I have to remove "automation:" and change the indentation.

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2022.11.1

**Comment by frenck** [comment]
The note on the page probably applies to you:

![CleanShot 2023-01-03 at 18 11 29](https://user-images.githubusercontent.com/195327/210406505-4034bdf1-a2a8-46e9-aaa8-2ecb5a05318c.png)

https://www.home-assistant.io/common-tasks/os/#backups

Meaning the contents of this page will not work for your setup. Please consult the linked page instead.

../Frenck
