### ISSUE TITLE
"the Home Assistant flow"?

### ISSUE THREAD

**Issue by pfurrie** [home-assistant/home-assistant.github.io#24839]
### Feedback

I'm trying to fix the Google Nest authentication in Home Assistant due to Google's recent changes.  Home Assistant has this page of documentation on the subject:
https://www.home-assistant.io/integrations/nest/#deprecated-app-auth-credentials

Because I already had Nest working with Home Assistant, the current challenge is to fix the authentication problem.  I scroll down the Home Assistant documentation to the next titled "Deprecated App Auth Credentials."  

The section part of this section has the heading "Create new Web Auth Application Credentials" and this is where the trouble is.  The first sentence of that section is as follows:

> 1. In the Home Assistant flow confirm your Google Cloud Project ID and proceed to the next step.

And this is where I'm stuck.  What is the world is "the Home Assistant flow"?  The only "flow" I've heard of is in Node Red, but that's an option for people to install and can't be assumed to be what is being referred. 

In the settings section I click the search button and enter "flow" but only get "Nothing found!"  This is not helpful.
Then I go to Google and search "what is a home assistant flow" and the first result is this page:
[https://developers.home-assistant.io/docs/data_entry_flow_index](url)
Well, can that be right?  That appears to be documentation in the developer's section of the Home Assistant site, and why would all the normal Nest users need developer info?  Regardless, the info on that page starts off with this:

> Data Entry Flow is a data entry framework that is part of Home Assistant. Data entry is done via data entry flows. A flow can represent a simple login form or a multi-step setup wizard for a component. A Flow Manager manages all flows that are in progress and handles creation of new flows.

The word "flow" shows up six times within four sentences.  The closest we get to a definition is that a flow is a data entry framework.  That doesn't help, and only gets worse when we find out that data entry frameworks are flows.  The definitions are circular.  To make matters worse, the rest of the documentation on that page goes downhill from there.  And none of this explains anything about "**THE** Home Assistant flow" specifically.  I don't know what it is, the search can't find it, and I can't find it manually by slogging through various pages of system settings.

I would ask "Am I missing something?," but obviously I am.  This is like a ladder you're asking me to climb, though rungs have been left missing.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

Home Assistant 2022.11.1

### Additional information

ALSO... on the Home Assistant documentation webpage-in-question, I used the link at the bottom of the page that says "provide feedback" which ended up getting me to this web form to leave this feedback.  However, one of the required fields I'm asked to enter is the URL for the particular page of documentation.  I wonder: why isn't that field automatically populated by the process that sent me here?  The URL should have been passed as a value to this page and then filled-in by default.

**Comment by allenporter** [comment]
This is referring to the last step on the previous section. It's calling the flow the the screen shown in the UI that walks you through reconfiguration.

**Comment by allenporter** [comment]
To be more specific, see the "Reconfigure" section right above
