### ISSUE TITLE
Setup flow chart

### ISSUE THREAD

**Issue by alanleu** [home-assistant/home-assistant.github.io#24833]
### Feedback

I'm new here. Try to setup HA. I was able to do the followings:
(1) Installed HA in Windows on a laptop.
(2) Connected to HA from a different Windows PC.
(3) Follow the steps to see all discovered devices

I'm lost at this point. I'm not ready to do automation yet. At this point I want to able to see something on a dashboard. I don't know what to do next.

I think some kind of flowchart can help.

Thanks.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2022.11.1

**Comment by dannytsang** [comment]
Hi @alanleu 

I would like to try and understand your feedback better so please bear with me.

I look at the chapters under the **Getting Started** as an ordered list to go through as a good starting point so I am not sure what a flow chart would add.
![image](https://user-images.githubusercontent.com/567982/201338871-7358a153-c70c-4b34-9c44-3ec98b9c4703.png)

However, I think potentially a missing chapter is customising your dashboard. If that was added as a chapter after Onboarding and Automation would that help?
