### ISSUE TITLE
Repetition in Templating page

### ISSUE THREAD

**Issue by RASBR** [home-assistant/home-assistant.github.io#24836]
### Feedback

Hi,
I think the [templating page](https://www.home-assistant.io/docs/configuration/templating/) needs some revision. some texts portions are repeated.
![Templating Repeated Text](https://user-images.githubusercontent.com/63133627/200155262-69e4ead2-4767-4f01-913d-9a38a442f32f.jpg)

Regards,
Rami

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2022.11.1

**Comment by frenck** [comment]
This has been fixed, thanks for reporting! 👍
