### ISSUE TITLE
MQTT Changes to 'discovery_prefix' unclear or undocumented.

### ISSUE THREAD

**Issue by Kementh** [home-assistant/home-assistant.github.io#24848]
### Feedback

Home assistant is now reporting that the 'discovery_prefix' setting in configuration.yaml will be depreciated by 2023.4.0, the documentation directs you to this configuration page, but there is NO documentation on what changes need to made, there are only circular linked anchors referring back to each other. #configure-mqtt-options points to #mqtt-discovery and vice versa.

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2022.11.1

**Comment by dansarginson** [comment]
For the record I found this issue while seeking clarity on what action is required. +1 from me.

**Comment by xmirakulix** [comment]
> For the record I found this issue while seeking clarity on what action is required. +1 from me.

Same for me, no hint in the documentation, nor am I able to find a general description of the planned changes in the mentioned release 2023.4.0

**Comment by Kementh** [comment]
Note to anyone With this issue, 
The relevant configuration has been moved into the Home Assistant UI, 

if you go to the MQTT intergration, click Reconfigure MQTT, Then click Next, the Discovery Prefix is now displayed here in the UI.

Documentation still needs to be updated, but this should at least get people updated.

**Comment by xmirakulix** [comment]
Thank you! 
Even better, reconfiguration was not required, the custom setting was already there, I just had to remove the discovery_prefix line from my configuration.yaml.

**Comment by frenck** [comment]
Closing this issue, move to the UI has been completed.
