### ISSUE TITLE
This page needs updates

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#24844]
### Feedback

  Is serious lacking in updates.  

I was following this -- and I got this:

![image](https://user-images.githubusercontent.com/100164602/200188869-148a95b8-6f0d-4634-9e58-74a4953c3a02.png)

### URL

https://www.home-assistant.io/docs/configuration/basic

**Comment by frenck** [comment]
Hi there @bearhntr 👋 

The issue you are reporting is actually invalid. Our documentation is correct. However, the error you are experiencing is from a third-party VSCode extension: The Home Assistant Config Helper.

Please report hat issue upstream here:

<https://github.com/keesschollaart81/vscode-home-assistant/issues>

Thanks! 👍 

../Frenck
