### ISSUE TITLE
When was the highest temperature reached?

### ISSUE THREAD

**Issue by Pittermaennchen** [home-assistant/home-assistant.github.io#24852]
### Feedback

Additionaly I would like to see in that max-temperature-card WHEN the maximum temperature was reached.

### URL

https://www.home-assistant.io/dashboards/statistic/

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
