### ISSUE TITLE
Litter-Robot - many Entities are missing data

### ISSUE THREAD

**Issue by talormanda** [home-assistant/home-assistant.github.io#24859]
### Feedback

Trying to use Entities such as `Litter-Robot Status code`, and based on the page, it should give me options such as: Clean Cycle in Progress, Ready, Drawer Full, etc

What I am seeing is:

![image](https://user-images.githubusercontent.com/10092964/200411660-d579f2ed-e780-45f1-9846-0163af0f7e3e.png)

### URL

https://www.home-assistant.io/integrations/litterrobot/

### Version

2022.11.1

**Comment by tkdrob** [comment]
Those are just the known suggestions. You can still set them to whatever text you want.

**Comment by natekspencer** [comment]
Those are just pre-populated helpers. You have to manually enter the status codes on the automations page to match what you want. If you want to see what the available codes are, you can refer to this file: https://github.com/home-assistant/core/blob/dev/homeassistant/components/litterrobot/strings.sensor.json

**Comment by talormanda** [comment]
> Those are just pre-populated helpers. You have to manually enter the status codes on the automations page to match what you want. If you want to see what the available codes are, you can refer to this file: https://github.com/home-assistant/core/blob/dev/homeassistant/components/litterrobot/strings.sensor.json

Oh perfect! that's what I was looking for! this really needs to be on the home assistant help page! thanks for the quick reply!

**Comment by tkdrob** [comment]
@home-assistant close
