### ISSUE TITLE
Android TV/Fire Stick ADB

### ISSUE THREAD

**Issue by XcOM987** [home-assistant/home-assistant.github.io#24861]
### Feedback

It might be good to add a known issue which is if you have an ADB connection to an Android TV device then Home Assistant will refuse to connect due to only one connection being allowed at any one time.

### URL

https://www.home-assistant.io/integrations/androidtv/

**Comment by JeffLIrion** [comment]
There's already a mention of this. 

https://www.home-assistant.io/integrations/androidtv/#adb-troubleshooting

> 3. You are already connected to the Android TV / Fire TV via ADB from another device. Only one device can be connected, so disconnect the other device, restart the Android TV / Fire TV (for good measure), and then restart Home Assistant.
