### ISSUE TITLE
Home assistant core install ----Dependencies

### ISSUE THREAD

**Issue by jamesc2151** [home-assistant/home-assistant.github.io#24863]
### Feedback

Just want to let you guys know.. That as I was adding this to my RB 4 the install failed at configuring the certificates..  Seems for some reason rust was not installed and was required..

Could be just my setup    P4 running Raspberry -bullseye

### URL

https://www.home-assistant.io/installation/raspberrypi

**Comment by erpel** [comment]
There's a number of issues related to the need for a rust compiler during installation of dependencies via pip:
https://github.com/home-assistant/home-assistant.io/issues?q=is%3Aissue+rust+is%3Aclosed

I think this pull request https://github.com/home-assistant/home-assistant.io/pull/22499 to add documentation about this points to a likely cause: platforms without prebuilt python packages need rustc while others do not. An example of such a platform would be Raspbian GNU/Linux 11 (bullseye) armv6l (aka the very old raspberry pi I'm currently playing with)

I can understand the desire not to blow the documentation up by adding additional notes and conditionals so I guess we users of certain platforms need to live with issues like this to figure out and the maintainers of the docs need to live with people trying to help by adding these dependencies (which are true for their situation).

**Comment by klaasnicolaas** [comment]
That is also why we have this warning note.
![image](https://user-images.githubusercontent.com/20448157/203072536-8178e9ea-a45d-4342-a4f3-f9cb6bfbf809.png)
