### ISSUE TITLE
Create automation with device dialog issue

### ISSUE THREAD

**Issue by jeremykeen** [home-assistant/home-assistant.github.io#24875]
### Feedback

I am presented with a dialog with suggested triggers when I choose to create an automation from a device page. I choose "<device> turned on" under "Do something when..." In the automation that is subsequently created, the trigger is not "device turned on" but instead is "Value change on a Z-wave JS Value."  Screenshots below for the issue.

![Screen Shot 2022-11-09 at 3 07 09 PM](https://user-images.githubusercontent.com/10226529/200932178-94b99121-a08f-4399-9357-ecb6b591fc5f.png)
![Screen Shot 2022-11-09 at 3 12 58 PM](https://user-images.githubusercontent.com/10226529/200932245-8fa255dd-e745-4b15-9cd9-b48781e1900a.png)

> 

### URL

https://www.home-assistant.io/docs/automation/basics/

### Version

2022.11.2

**Comment by dannytsang** [comment]
Hi @jeremykeen 

I'm struggling to see the information you have provide and how it relates to the https://www.home-assistant.io/docs/automation/basics/

Is there something specific you want changing on https://www.home-assistant.io/docs/automation/basics/ ?

**Comment by jeremykeen** [comment]
Maybe it should go under automation editor. I could not find a relevant
category. Regardless the picker that I show in the screenshots does not
lead to a correct automation config.
