### ISSUE TITLE
Update to Can’t link to [Project Name]: Please contact [Project Name] if the issue persists

### ISSUE THREAD

**Issue by adamsteveng** [home-assistant/home-assistant.github.io#24887]
### Feedback

After a while of troubleshooting and trying to figure out what was wrong with my Nest install, I've discovered that there is something missing in the troubleshooting documentation (and possibly a bug in the Nest integration):

When you set it up once, your OAuth credentials become permanently stored in .storage/application_credentials, and after an unsuccessfule (or successful) attempt, if you try to re-add the Nest integration, it skips this step and never again gives you the opportunity to specify your OAuth client ID.

After an update and a change on my Google cloud, I had new OAuth credentials, but was unable to change them in the UI.  I think it would be beneficial to edit the section that begins with "Can’t link to [Project Name]: Please contact [Project Name] if the issue persists":

This typically means that the OAuth Client ID used is mismatched.  To verify the OAuth Client ID you're using or change it, view/edit the .storage/application_credentials file located under the Home Assistant configuration store.

Thanks

### URL

https://www.home-assistant.io/integrations/nest/#troubleshooting

### Version

2022.7.0

**Comment by allenporter** [comment]
This is explained under "Resolving mismatched OAuth Client ID" with a screenshot of where to go in the UI. Let me know if you have suggestions for how to clarify or even better feel free to send an edit to clarify.

**Comment by allenporter** [comment]
Btw the troubleshooting says exactly what you said:

```
Can’t link to [Project Name]: Please contact [Project Name] if the issue persists: This typically means that the OAuth Client ID used is mismatched
```
Is what is written in the troubleshooting

**Comment by allenporter** [comment]
The other thing I would add is in newer home assistant versions you are prompted when removing the integration if you would like to keep or delete application credentials explicitly, so this is less likely to happen in the first place.

I'm marking as closed given the documentation already has what you said but using UI controls and not low level filesystem details.
