### ISSUE TITLE
Power reading type unclear

### ISSUE THREAD

**Issue by realflash** [home-assistant/home-assistant.github.io#24880]
### Feedback

I've been trying to understand the difference between my Shelly EM's readings and those of my smart meter. Shelly pointed out that they provide two endpoints providing data on reactive power and apparent power. I looked in the integration code but couldn't see where/how the endpoints that are called are defined. I would like to add a description of what power the integration reports to the documentation. 

Could someone either tell me which it is, or point me to the relevant code? Additionally, power factor is provided as a sensor but this isn't an endpoint that I can see. Is it calculated from the two endpoints that are available? Where does that happen?

Once I understand I am happy to generate a pull request describing these things. 

### URL

https://www.home-assistant.io/integrations/shelly

### Version

2022.11?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by realflash** [comment]
This isn't a support request. it's either a documentation bug or a documentation enhancement request. There are three types of power that could be reported:

1. Active power (true power, real power)
2. Apparent power
3. Reactive power

Since the Shelly device provides [two different API end points](https://shelly-api-docs.shelly.cloud/gen1/#shelly-em) and neither of them are the power factor, but the integration provides it, I presume the integration is calculating it. So the integration is manipulating the data. That is fine, but it should be clear in the documentation what manipulation is done, and which power reading is being provided. 

Without knowledge of what the data provided represents, the data is useless. Please could you advise which of the above three is provided by the sensor, **so that I may assist by proposing documentation changes.**

**Comment by thecode** [comment]
I agree with Frenck that this doesn't fit here. The integration doesn't use the API endpoints you refer to and is using COIOT, the best place to discuss this is Discord to help you understand how the integration works if you need to.
We don't manipulate any data, if a power factor sensor is created it is provided by the device.
