### ISSUE TITLE
Change supported CGroup 

### ISSUE THREAD

**Issue by TheArtizan** [home-assistant/home-assistant.github.io#24885]
### Feedback

After hours of trying to fix CGroup version, I found this worked.
Using terminal connected via ssh to your machine, work as root.
su 
sudo nano /boot/cmdline.txt
Then add to the end of the first line - systemd.unified_cgroup_hierarchy=false systemd.legacy_systemd_cgroup_controller=false 
Then save and reboot

### URL

https://www.home-assistant.io/more-info/unsupported/cgroup_version

### Version

2022.11.1

**Comment by frenck** [comment]
Hi there @TheArtizan, good to hear you have figured out a way that works for you 👍 

../Frenck

**Comment by tigrrr** [comment]
Worked for me as well.. Artizan, thanks.
