### ISSUE TITLE
Forum not working in Firefox

### ISSUE THREAD

**Issue by keizeralbert** [home-assistant/home-assistant.github.io#24896]
### Feedback

The forum layout is messed up in Firefox. Maybe this can be fixed.
In Chrome it is working
![homeassistant forum](https://user-images.githubusercontent.com/84508650/201318246-95ecd298-cfaf-43a9-b7d2-1b6c51169119.jpg)

### URL

https://community.home-assistant.io/

**Comment by dannytsang** [comment]
I'm not seeing any issues from my side. Maybe it's a caching issue?
![image](https://user-images.githubusercontent.com/567982/201336983-a384dedf-f7c3-4528-ba5d-cde7acb04e12.png)

**Comment by keizeralbert** [comment]
Thanks, removed all cache it's fixed now. Sorry for the issue
