### ISSUE TITLE
SMA Solar Integration: selecting group "installer" during installation

### ISSUE THREAD

**Issue by TMGFlyer** [home-assistant/home-assistant.github.io#24892]
### Feedback

From the logic of the SMA it seems to be reasonable to select "user"within the Manual Configuration Steps. But this does not work. Doing so, you will get an "invalid authentication" failure message from the SMA unit.
Therefore, it would be helpful to mention  that the "installer" group should be selected. 

### URL

https://www.home-assistant.io/integrations/sma

### Version

2022.11.1

**Comment by rklomp** [comment]
In my installation "user" is working perfectly without any issues.

**Comment by TMGFlyer** [comment]
The issue still exists but cannot be reproduced by others. Consequently it shall be closed
