### ISSUE TITLE
Weather template attributes

### ISSUE THREAD

**Issue by haaino** [home-assistant/home-assistant.github.io#24893]
### Feedback

In configuration variables there is an attribute precipitation_unit mentioned.

unfortunately this attribute is not excepted as a valid option.

### URL

https://www.home-assistant.io/integrations/weather.template/

**Comment by frenck** [comment]
I've just checked the source code, it is a valid option.


![image](https://user-images.githubusercontent.com/195327/202150628-21fb422c-1a91-4200-a7c9-89dc73c53e6a.png)

And thus documented correctly. If you think it is a bug, please report it on our Core issue tracker.

Thanks 👍 

../Frenck
