### ISSUE TITLE
Statistic Card

### ISSUE THREAD

**Issue by Chrspie50** [home-assistant/home-assistant.github.io#24890]
### Feedback

I started using the Statistic Card and like it.
However I would prefer a smaller font or even better, an adjustable font as it appears large on a small mobile screen.
Please find attached table with small font and below that the Statistic Card with (too) large font.
<img width="1067" alt="Screenshot 2022-11-10 at 19 42 21" src="https://user-images.githubusercontent.com/25831876/201179941-03dc49b2-1e9f-4680-b42f-e6c4a8bc56f5.png">

### URL

http://192.168.1.58:8123/lovelace-mushroom/electrical-energy

### Version

2022.11.2

**Comment by dannytsang** [comment]
Hi @Chrspie50 
I'm afraid you should raise this in documentation part of the Home Assistant. If you could log it in the ["front end" repository](https://github.com/home-assistant/frontend), go to the issues > new issues there will be an option called **Request a feature for UI / Dashboards**.

![image](https://user-images.githubusercontent.com/567982/201337848-c075179e-cfc6-4974-8a51-3d685deb686d.png)

Also it might be useful to give a bit more detail such as is the the card title, the sensor value itself, both, etc?
