### ISSUE TITLE
Websocket configuration is not available by default

### ISSUE THREAD

**Issue by sandyscott** [home-assistant/home-assistant.github.io#24891]
### Feedback

I've just set up a Shelly Plus H&T, and there's a step missing from the documentation on https://www.home-assistant.io/integrations/shelly/

Before you can enter the websocket address on the device, it needs to be enabled

Go to Device [Settings] -> Debug.

Enable Websocket Debug.

Then you can enter the websocket url as instructed.

![image](https://user-images.githubusercontent.com/2547618/201209491-a8bcb02a-a96f-4a71-8156-dacfe7949ec4.png)

Device Information

- Device ID: C049EF871438
- Firmware version: 0.11.4
- Firmware build ID: 20221024-142431/0.11.4-ga1906a2
- Web build ID: 1.5.5-8e98823

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2022.11.2

**Comment by thecode** [comment]
`Websocket debug` is a different function of the device and you do not need to enable it.
The `Outbound websocket` is under networks (as explained in the docs) and is available without enabling `Websocket debug` (I have never enabled it for any of my devices.
Here are some pictures from Shelly 2PM Plus:
Debug is disabled:
![image](https://user-images.githubusercontent.com/1858925/201224754-27b55884-91c3-4e28-906a-a5ee1fe8f451.png)
Outbound weboscket is avaialble:
![image](https://user-images.githubusercontent.com/1858925/201224835-d4e5e985-5e53-4c6f-8c8a-f0694cf67e46.png)

Please recheck your configuration

**Comment by sandyscott** [comment]
I assure that I spent half an hour hunting for that menu entry last night and there was nothing in between "Mqtt" and "Connectivity" until I turned on that setting. However, I can't reliably reproduce the issue this morning - it was missing once, but reappeared on a refresh, so I'll put this down to some kind of web tech glitch.
