### ISSUE TITLE
Missing Entities, not all list from a integration in energy dashboard

### ISSUE THREAD

**Issue by Zeus8879** [home-assistant/home-assistant.github.io#24894]
### Feedback

Hello,
i have an issue, not all provided entities are listed in the energy dashboard. So is not a correct energy caclulation possible. The integration module is from Kostal plenticore solar. 

Following entities ID missing:
sensor.pv_anlage_burglengenfeld_solar_power
sensor.pv_anlage_burglengenfeld_grid_power
....

### URL

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

### Version

Home Assistant 2022.11.2

**Comment by klaasnicolaas** [comment]
Based on the entity names, these are power values in Watts and that is not what the Energy dashboard uses and therefore does not show in the list. You need the Energy entities with a value in kWh.
