### ISSUE TITLE
What does 'enable physics' do?

### ISSUE THREAD

**Issue by fluxsmith** [home-assistant/home-assistant.github.io#24905]
### Feedback

This isn't even mentioned on the documentation page, it's just a mystery checkbox in the UI that I can see no effect from.

### URL

https://www.home-assistant.io/integrations/zha

**Comment by puddly** [comment]
If you click and drag a node to some new location, it will shove nearby nodes out of the way and slowly drift back to its original position. Disabling physics disables this behavior.
