### ISSUE TITLE
Water consumption is far to high

### ISSUE THREAD

**Issue by HobbitBluelabel** [home-assistant/home-assistant.github.io#24908]
### Feedback

I was so glad that my water consumption is now available in de energy dashboard. But after a few days of testing i can not get the right values in the overview. Sometimes it looks right but sometimesi have strange high values. I use the esphome s0tool and the values that i see there are perfect. The source: sensor.watermeter_totaal value is 100% right....

My utility_meter values are:
 waterverbruik_kwartier:
    source: sensor.watermeter_totaal
    cycle: quarter-hourly
  waterverbruik_per_uur:
    source: sensor.watermeter_totaal
    cycle: hourly
  waterverbruik_per_dag:
    source: sensor.watermeter_totaal
    cycle: daily    
  waterverbruik_per_week:
    source: sensor.watermeter_totaal
    cycle: weekly
  waterverbruik_per_maand:
    source: sensor.watermeter_totaal
    cycle: monthly
  waterverbruik_per_kwartaal:
    source: sensor.watermeter_totaal
    cycle: quarterly
  waterverbruik_per_jaar:
    source: sensor.watermeter_totaal
    cycle: yearly   
  water_per_altijd:  
    source: sensor.watermeter_totaal

in the attachment you can see an example of my investigation and how it looks like.
[Watermeting probleem - Blad1.pdf](https://github.com/home-assistant/home-assistant.io/files/9994724/Watermeting.probleem.-.Blad1.pdf)

What goes wrong?

### URL

https://home.vdhoek.nl/energy

### Version

 2022.11.2

**Comment by klaasnicolaas** [comment]
Hi there @HobbitBluelabel 👋

It seems like you want to report an issue with an third party ESPHome device, however, you have submitted documentation feedback instead. Please raise an issue in the s0tool repository.

https://github.com/huizebruin/s0tool

Thanks! 👍

./Klaas

**Comment by huizebruin** [comment]
Hello [HobbitBluelabel](https://github.com/HobbitBluelabel)

i found the problem , and made a fix .
Please update to S0tool version v22.11.24
https://github.com/huizebruin/s0tool/releases

**Comment by HobbitBluelabel** [comment]
Hi Klaas,

The issue is not the s0 tool but de dashboard integration...
So i think it belongs here?

Hartelijke groet,
Jan-Willem van den Hoek

Op za 12 nov. 2022 16:14 schreef Klaas Schoute ***@***.***>:

**Comment by klaasnicolaas** [comment]
You are not in the right place for that (this repository is for documentation feedback of Home Assistant), I refer you again to the repository of the s0tool and the advice which @huizebruin also gives here.

**Comment by HobbitBluelabel** [comment]
Hi klaas,

Thank you for your reply.
Sorry, I will do that...

Hartelijke groet,
Jan-Willem van den Hoek


Op za 12 nov. 2022 om 16:59 schreef Klaas Schoute ***@***.***
