### ISSUE TITLE
Alexa integration

### ISSUE THREAD

**Issue by IlGiock** [home-assistant/home-assistant.github.io#24907]
### Feedback

Absolutely useless  documentation, there are inly requirements, i find a step by step solution in the web

### URL

https://www.home-assistant.io/integrations/alexa/#manual-setup

**Comment by klaasnicolaas** [comment]
You are free to modify the documentation so that it is useful for everyone 😉

**Comment by frenck** [comment]
So, Home Assistant is an open source project. This means documentation is written by and corrected by, users. Just like you.

Just saying it is useless, doesn't help anybody, nor is it constructive feedback. There is nothing I can do with the comment provided.

Going to close this feedback for that reason. Please, feel free to provide meaningful, constructive feedback; or, even better, provide suggestions on what to improve. You can even suggest and edit yourself 🤘


../Frenck
