### ISSUE TITLE
Discovered LEDBLE-01-026B (026B)

### ISSUE THREAD

**Issue by maceace** [home-assistant/home-assistant.github.io#24903]
### Feedback

Device discovered LEDBLE-01-026B (026B)
But the integration reports - Failed to connect.
Is there hope for repair? 
Thank you. 

### URL

https://www.home-assistant.io/integrations/led_ble

### Version

2022.11.2

### Additional information

![IMG_20221111_125141](https://user-images.githubusercontent.com/66499150/201436822-7b166146-4d68-4660-bff4-3f798177ff65.jpg)

**Comment by huizebruin** [comment]
i saw the here also LEDBLE-01195F (195F) LED BLE.
and does the same u cannot ad it to Home Assistant.
![image](https://user-images.githubusercontent.com/62996429/201513763-68369e42-a163-4377-b511-ce9b7d2c4223.png)
I don't own that one, that way i don't no witch type it is but u cannot put it into Home Assistant.

I'm using: 
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend-versie: 20221108.0 - latest

**Comment by frenck** [comment]
Hi there 👋 

It seems like you want to report an issue with the LED BLE integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
