### ISSUE TITLE
SmartmeterTexas not connecting

### ISSUE THREAD

**Issue by TGSnedecor** [home-assistant/home-assistant.github.io#24914]
### Feedback

I have an account on smartmetertexas.com, and successfully logged in and saw my data from a browser.  I entered these same credentials into the dialog box for the integration (username and password) and it reported "Failed to connect".  I have checked and re-entered the username and password, and it still fails to connect.  I logged into smartmetertexas.com with the same credentials and was logged in just fine.

### URL

https://www.home-assistant.io/integrations/smart_meter_texas

### Version

2022.4.7

**Comment by klaasnicolaas** [comment]
Hi there @TGSnedecor 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
