### ISSUE TITLE
cannot scan QR code in tuya smart

### ISSUE THREAD

**Issue by marcpouliot** [home-assistant/home-assistant.github.io#24912]
### Feedback

in section "LINK DEVICES BY APP ACCOUNT"
1.
Scan the QR code that appears using the Tuya Smart app or Smart life app.

The QR code appears but, **it is not obvious how to scan the QR with the Tuya Smart app.** (cannot find where to perform the scan..

(I am stock) I already have 2 devices in the tuya application.)
thank you

### URL

https://www.home-assistant.io/integrations/tuya/

**Comment by Leeroy-J** [comment]
marc, hope you got it by now, but for anyone else, it's: Me (bottom right) --> Scan Logo (top right, 'line-in-square' icon)
