### ISSUE TITLE
Fully Kiosk Browser Integration

### ISSUE THREAD

**Issue by AndySymons** [home-assistant/home-assistant.github.io#24922]
### Feedback

The instruction "Follow the instruction on screen to complete the set up" is not sufficient. The screen asks for a 'Host' and a 'Password'. What do they mean? I tried a user id and password but that does not work ... 
My dashboard is running on Fully Kiosk on an Android tablet. 

### URL

https://www.home-assistant.io/integrations/fully_kiosk/

**Comment by chpego** [comment]
Hi @AndySymons 
The Host is the IP adresse or DNS name. For the password, is set in the setup of FKB in your tablet. There is no user .
