### ISSUE TITLE
Revisit #18313 - Conditions: vs Condition

### ISSUE THREAD

**Issue by guardianbs** [home-assistant/home-assistant.github.io#24928]
### Feedback

Feedback #18313 raised a typo point. Response was 'This is not a typo, both are common occurances' (sic).

However, 'conditions:' is reported as an error when used in an automation 'action' clause ('condition:' is accepted).

If there are cases where 'conditions' is correct and cases where 'condition:' is correct shouldn't this be specified more clearly ?

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2022.11.1

**Comment by frenck** [comment]
I do not understand the comments? Isn’t the automation documentation explaining the use? 

This page describes/explains individual conditions, not the thing that sits around it (automations)

../Frenck

**Comment by guardianbs** [comment]
Hi, I think the problem is self evident. If the documentation was adequately explaining the USE of the Template condition shorthand notation then there would not have been 2 feedbacks.

The documentation does not explain , for example, where it iwuld be valid to use 
   condition: "{{ (state_attr('device_tracker.iphone', 'battery_level')|int) > 50 }}"
and where it would  be valid to use
   conditions: "{{ (state_attr('device_tracker.iphone', 'battery_level')|int) > 50 }}"

They are obviously not interchangeable as incorrect use results in an error.

**Comment by frenck** [comment]
Sorry, what does that have to do with the conditions themselves?
It sounds like you are talking about of the use of conditions in specific places (which is not what this documentation is about?)

**Comment by guardianbs** [comment]
Oh really ? So when you are looking up the correct syntax for the Condition statement you don't want to know the correct syntax for a particular USE of the Condition statement. So what documentation would describe the different syntax for the Condition statement for example when used as a Trigger Condition as opposed to being used as an Action Condition ?
As to why the syntax is different is another matter entirely.
I know you are very busy, and your work is much appreciated, so I apologise for wasting your time.

**Comment by guardianbs** [comment]
Close it if you like, but it was never resolved. All comments made are still pertinent.
