### ISSUE TITLE
Supported model

### ISSUE THREAD

**Issue by bodrych** [home-assistant/home-assistant.github.io#24923]
### Feedback

This model works too
| `lamp9` | YLCT03YL | Yeelight Staria Bedside Lamp Pro |

### URL

https://www.home-assistant.io/integrations/yeelight#supported-models

### Version

2022.11.2

**Comment by frenck** [comment]
Thanks for reporting that @bodrych 👍 
I've opened up a pull request to adjust the documentation accordingly.

../Frenck
