### ISSUE TITLE
Air Quality documentation page links to wrong anchor on Integrations page

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/home-assistant.github.io#24935]
### Feedback

Air Quality documentation page links to Integrations --> Health. Despite the link being correct in the markdown file, the anchor seems to be ignored resulting in going just to the direct Integrations page. I think this may be a bug in whatever system is doing the markdown rendering of links.

https://www.home-assistant.io/integrations/air_quality/ links to /integrations#health (in markdown) but renders as /integrations

### URL

https://www.home-assistant.io/integrations/air_quality/

**Comment by codyc1515** [comment]
Still relevant

**Comment by frenck** [comment]
I can't reproduce the issue you are reporting. If I click that link, I get the integrations page filtered by that category.

../Frenck
