### ISSUE TITLE
Monthly view with offset

### ISSUE THREAD

**Issue by Chrspie50** [home-assistant/home-assistant.github.io#24939]
### Feedback

My energy supplier (gas/electricity) provides me an overview of used gas and electricity on every 18th day of the month (runs from 18th to 17th in the next month).
Is it possible to capture a monthly overview of used gas and electricity which resets every 18th?

### URL

http://192.168.1.58:8123/lovelace-mushroom/electrical-energy

### Version

2022.11.2

**Comment by frenck** [comment]
No that is not possible
