### ISSUE TITLE
Feedback URL arguments are not collected into template

### ISSUE THREAD

**Issue by clemens-tolboom** [home-assistant/home-assistant.github.io#24941]
### Feedback

The  arguments of
```
https://github.com/home-assistant/home-assistant.io/issues/new?template=feedback.yml&url=https%3A%2F%2Fwww.home-assistant.io%2Fdocs%2Fconfiguration%2Ftroubleshooting%2F&version=2022.11.2&labels=current
```
are not used for the fields below. Disecting these they are
```
?url=https://www.home-assistant.io/docs/configuration/troubleshooting
&version=2022.11.2
&labels=current
```

### URL

https://www.home-assistant.io/docs/configuration/troubleshooting

### Version

2022.11.2

### Additional information

Checking with https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query 

Is this due to **beta** status of https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms ?

**Comment by frenck** [comment]
Thanks, @clemens-tolboom 👍 

There seems to be a slight change in the syntax of issue forms. Made a PR to adjust it.

../Frenck

**Comment by clemens-tolboom** [comment]
Thanks!
