### ISSUE TITLE
Multiple lists

### ISSUE THREAD

**Issue by Chrisvdw00** [home-assistant/home-assistant.github.io#24942]
### Feedback

Just an idea but it could be nice to make multiple lists

### URL

https://www.home-assistant.io/integrations/shopping_list

### Additional information

I'd envision the integration to show a dashboard in which you can have multiple lists (and name the lists). These lists could also be to do lists and not just shopping so maybe rename the integration to 'to do list' or sth similar

**Comment by jschinke1067** [comment]
It would really great to have separate shopping lists. An alternative would be some kind of todo-list...

**Comment by Chrisvdw00** [comment]
Yes, to me the shopping list has more or less functioned as a to do list, maybe a shopping list is also a specific type of to do list.

**Comment by jschinke1067** [comment]
Yes it is still relevant…

**Comment by MagoPoza** [comment]
It would be a nice feature to also have a task list

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
