### ISSUE TITLE
eufy doesn't do anything

### ISSUE THREAD

**Issue by crpeck** [home-assistant/home-assistant.github.io#24944]
### Feedback

I'm attempting to implement this following the directions, I get a token fine, but when I run this:
$ curl -H token:TOKEN -H category:Home \
   https://home-api.eufylife.com/v1/device/list/devices-and-groups

I get this as a result:
{"res_code":1,"message":"","items":[],"global_config":{"enabled_multi_color_modes":[0,1,2,3]}}%

### URL

https://www.home-assistant.io/integrations/eufy/

### Additional information

I have added the section to configuration.yaml using the email & password I got a token with, & restarted.  I don't see any devices.
# Example configuration.yaml entry
eufy:
  username: EMAIL_ADDRESS
  password: PASSWORD

**Comment by niektenhoopen** [comment]
Same here. I am wondering if you need a Eufy Homebase maybe? I have a doorbell + chime, no homebase

**Comment by Howie1972** [comment]
I am also getting the same responce - {"res_code":1,"message":"","items":[],"global_config":{"enabled_multi_color_modes":[0,1,2,3]}}
Has there been any development on this?

**Comment by mikewren** [comment]
I generally don't like to make "me too" posts, but here we are - I'm also experiencing the same behavior as above in a home environment with a couple doorbells, flood lights, and a door lock, and no homebase.

My speculation is that Eufy may have modified their backend ("cloud") systems in response to this: https://www.zdnet.com/home-and-office/smart-home/eufy-responds-to-security-concerns - and it may have borked this method of obtaining per-device tokens.

Hopefully a secure workaround can be identified so the Eufy ecosystem of devices can be viewed and manipulated in Home Assistant.

**Comment by martinhanes** [comment]
issue is still present! :-)

**Comment by mikewren** [comment]
This issue persists, still receiving the following:

{"res_code":1,"message":"","items":[],"global_config":{"enabled_multi_color_modes":[0,1,2,3]}}

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Note, however, that no one has committed to this integration as a code owner. 

Thanks! 👍

./Klaas
