### ISSUE TITLE
device_id and device_name Authorisation Error

### ISSUE THREAD

**Issue by richjhart** [home-assistant/home-assistant.github.io#24951]
### Feedback

I have got an error at the final step which I cannot find any info about on here:

Authorisation Error
Error 400: invalid_request
device_id and device_name are required for private IP: http://<ip>:<port>/auth/external/callback

(Hidden my local IP address and port to give myself a sense of security)

### URL

https://www.home-assistant.io/integrations/nest/#troubleshooting

### Version

2022.11.2

### Additional information

I think it might be related to the redirect converting to a local IP address - but I can't work out how I'm meant to fix it as a result

**Comment by allenporter** [comment]
Hi. That is not the correct oauth callback url described in the docs under "Configure OAuth Application Credentials [Cloud Console]" as you should be using my home assistant. Is my home assistant is disabled?

**Comment by allenporter** [comment]
What is the url serving that error? Google or your own server?

**Comment by richjhart** [comment]
I know it's not the correct URL - but it's the URL that Google is ending up at when it tries to authorise.

In the "Authorised redirect URIs" section of the "Client ID for Web Application", I put the defined URI as per the instructions: "https://my.home-assistant.io/redirect/oauth"

Then when I added the Google Nest integration and put in the required details, it gets as far as step 3 of "Link Google Account". But after I enable the permission and hit next, Google returns that Authorisation error.

I actually got it working by accessing Home Assistant remotely (through the Cloud), and adding the following as an authorised URI in the console (in addition to /redirect/oauth):
"https://[my_id].ui.nabu.casa/auth/external/callback"
I may have been able to do it locally by adding the local IP URL as well.

I'm not sure what you mean by "Is my home assistant is disabled?" Where could it be disabled?

**Comment by allenporter** [comment]
If you disable `default_config` for example it disables "my home assistant" which handles the oauth redirect urls.  This means you are on your own for meeting the redirect urls requirements for google (e.g. public dns name, ssl, etc -- also satisfied by nabu casa)

**Comment by richjhart** [comment]
I'm using Home Assistant Core in Qnap Container Station - Apart from manually enabling "mobile_app:", I haven't touched the default configuration (in configuration.yaml).

Do I need to add "default_config"?

**Comment by richjhart** [comment]
As per https://www.home-assistant.io/integrations/my/, I've added "my" to the config. I'll see if that works.

**Comment by richjhart** [comment]
That seems to have worked (I did remove the integration first, and it seemed to go through the full authorisation process - but I can't be 100% sure that the previous authorisation made a difference).

Might want to update the documentation to ensure that "my home assistant" is enabled - I didn't see anything mentioned about it, and on docker in container station it is not enabled by default.

**Comment by allenporter** [comment]
It is mentioned in the documentation.

**Comment by allenporter** [comment]
You are welcome to send further edits to the documentation! Thanks 👍
