### ISSUE TITLE
An example for time on in the last X days, but only between the hours of 9AM to 5AM

### ISSUE THREAD

**Issue by UncleLeoTheDad** [home-assistant/home-assistant.github.io#24954]
### Feedback

I'm not even sure if it's possible, but I was hoping to use this to report the amount of time my Apple TV is playing, but only in a certain set of hours.  The use case is I don't care if there's streaming during the evening hours, but want to track how much during daytime hours. 

### URL

https://www.home-assistant.io/integrations/history_stats/

**Comment by frenck** [comment]
Thank you for reaching out.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
