### ISSUE TITLE
Integration not signing in with Australian OVO Energy account credentials

### ISSUE THREAD

**Issue by diliff79** [home-assistant/home-assistant.github.io#24969]
### The problem

Sorry if not the right place to highlight this issue, it's not a code issue per-se, but it seems that OVO Energy is a UK Company but has an Australian subsidiary operating separately (from an account integration point of view). 

I was struggling to sign into the ovo_energy integration with my Australian account username and password before EVENTUALLY discovering that the integration was probably only ever intended for UK accounts, not Australian accounts. There's no documentation that explains that the integration is UK only and is likely confusing a few Aussies out there. Or maybe I'm the first. :) Either way, I thought the documentation should be a bit more specific.

### What version of Home Assistant Core has the issue?

n/a

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

ovo_energy

### Link to integration documentation on our website

home-assistant.io/integrations/ovo_energy

**Comment by thecode** [comment]
Thanks for reporting, I have transferred it to the docs site, as this should be documented that it only supports UK accounts.
