### ISSUE TITLE
QNAP NAS - The current page size of the system is changed to 32K - homeassistant/armhf-homeassistant container doesn't work

### ISSUE THREAD

**Issue by rfaccioni** [home-assistant/home-assistant.github.io#24965]
### Feedback

QNAP updated the system page size from 4K to 32K for better performance and user experience on the following 32-bit ARM devices. This change in the compute environment could limit the container’s access to memory.  homeassistant/armhf-homeassistant container not run successfully:

s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/udev.sh
[11:37:11] INFO: Setup udev backend inside container
starting version 3.2.11
[11:37:11] INFO: Update udev information
cont-init: info: /etc/cont-init.d/udev.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun supervisor (no readiness notification)
services-up: info: copying legacy longrun watchdog (no readiness notification)
s6-rc: info: service legacy-services successfully started
[11:37:11] INFO: Starting local supervisor watchdog...
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
Fatal Python error: _PyRuntimeState_Init_impl: memory allocation failed
Python runtime state: unknown

[11:37:11] WARNING: Halt Supervisor
[11:37:11] INFO: Supervisor restart after closing
s6-rc: info: service legacy-services: stopping
[11:37:11] INFO: Watchdog restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### URL

https://www.home-assistant.io/installation/alternative

**Comment by joshuisken** [comment]
Anyone? The help of QNAP on the issue is not very helpful. How to check page size compatibility, and how to fix it would be more helpful.

**Comment by John-Titor** [comment]
The error is from jemalloc, which compiles-in the system page size at build time (unless overridden). This is jemalloc/jemalloc#467. 

It looks like you can disable the use of jemalloc, see https://www.home-assistant.io/installation/alternative
