### ISSUE TITLE
Install Home Assistant Core, additional dependencies

### ISSUE THREAD

**Issue by tenchman** [home-assistant/home-assistant.github.io#24977]
### Feedback

python cryptography requires rustc and cargo to build

### URL

https://www.home-assistant.io/installation/linux#install-home-assistant-core

### Version

2022.11.3

**Comment by frenck** [comment]
That all depends on your environment. 

As per documentation, it is expected:

![image](https://user-images.githubusercontent.com/195327/202452799-7a05c1cf-8a6b-4575-843c-f53f4dbb0c24.png)

../Frenck
