### ISSUE TITLE
regarding new mqtt format

### ISSUE THREAD

**Issue by geertn444** [home-assistant/home-assistant.github.io#24972]
### Feedback

what if you have subfiles of type "switches"

<configuration.yaml>
switch switches: !include nhc1.yaml

does this become:

mqtt mqtt: !include nhc1.yaml

### URL

https://www.home-assistant.io/integrations/switch.mqtt/#new_format

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
