### ISSUE TITLE
Raspberry Pi Remote GPIO 

### ISSUE THREAD

**Issue by fnx2k** [home-assistant/home-assistant.github.io#24984]
### Feedback

I am struggling with this issue of connecting HA instance to the GPIO of the Raspberry Pi on which it is installed. This documentation page is not helping me.

The preparation of the hardware should be detailed or at least 
in § Preparation of the raspberry on which the GPIO is installed, the link provided (  [here](https://gpiozero.readthedocs.io/en/stable/remote_gpio.html) ) is confusing and not usable for Home Assistant since HA does not provide apt commande for instance.

Regards

### URL

https://www.home-assistant.io/integrations/remote_rpi_gpio/

### Version

2022.11.2

### Additional information

Beginner with HA

**Comment by frenck** [comment]
> The preparation of the hardware should be detailed or at least
in § Preparation of the raspberry on which the GPIO is installed, the link provided ( [here](https://gpiozero.readthedocs.io/en/stable/remote_gpio.html) ) 

Installing remote GPIO is out of scope for the Home Assistant documentation. If you think the remote GPIO documentation is incomplete, please drop a suggestion at the upstream project. It is best if they document their software.

> is confusing and not usable for Home Assistant since HA does not provide apt commande for instance.

That makes sense, it is not local GPIO, it is remote GPIO. It is not meant to be run on the Home Assistant device itself. Home Assistant doesn't support GPIO locally.

If you are in need of more support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
