### ISSUE TITLE
easy name change

### ISSUE THREAD

**Issue by Fabianosch** [home-assistant/home-assistant.github.io#24980]
### Feedback

Hi there,
I love your work! (and sorry for the bad English)

I like to suggest to integrate an easy way change the names for the energy entities.
I am using the smartplugs also as universal and temporary solutions, and don want to change the name in the regulary way, all the time.
So if it would be possible to change the name, just on the Energy dash, would be great :)
I hope it was possible to understand what i mean.
(i am currently using V 2022.10.5, maybe you included this already, i will have a look ;-)
Thanks for everything, it wonderful software :-)
Greetz Fabian

### URL

192.168.XXX.XXX/energy

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
