### ISSUE TITLE
summery of Individual device energy consumption

### ISSUE THREAD

**Issue by lynntryanderror** [home-assistant/home-assistant.github.io#24983]
### Feedback

Hello all,

first of all i love the energy dashboard and like to see more and more improvments. Thats why i writing this feedback.
I spend time to integrate 27 individual devices into the dashboard. Now it would be really great to see how much of the overall consumption do i cover with the individual devices. So for me its around 70% but it would be good to have a nice chart where you can see the sum of all devices.

**Calculated sum of all individual energy consumptions in kWh and as percentage from the overall**

Thanks a lot
Lynn

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Additional information

![image](https://user-images.githubusercontent.com/101171559/202559375-84fa93e6-e75a-45c1-b8a9-a39026fafead.png)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
