### ISSUE TITLE
How can I install 2 copies of 1 addon?

### ISSUE THREAD

**Issue by ful4n1t0c0sme** [home-assistant/home-assistant.github.io#24982]
### Feedback

I Use Octoprint addon. But I have 2 printers. I need to install 2 Octoprint instances.

### URL

https://www.home-assistant.io/addons/

### Version

2022.11.2

**Comment by frenck** [comment]
That is an external add-on, not provided by the Home Assistant project (which we do not document or support).

Please ask your question with the third-party project instead.

In general, it isn't possible to run multiple instances of add-ons.

../Frenck
