### ISSUE TITLE
Access to HA via tailscale over internet

### ISSUE THREAD

**Issue by computermaster0101** [home-assistant/home-assistant.github.io#25006]
### Feedback

https://www.home-assistant.io/integrations/tailscale/ states 

"This integration DOES NOT make your Home Assistant accessible via Tailscale VPN remotely!"

However I can use it to access HA remotely. 

### URL

https://www.home-assistant.io/integrations/tailscale/

### Version

2022.11.3

**Comment by frenck** [comment]
> However I can use it to access HA remotely.

It is not the integration that provides such functionality.

../Frenck

**Comment by computermaster0101** [comment]
If i connect tailscale on my ha and my cellphone I can access ha on the tailscale ip from my cellphone web browser. My ha is not available to the web but I can reach it remotely through tailscale ip address  contradictory to the documentation

**Comment by klaasnicolaas** [comment]
You are probably confusing the add-on and the integration.

The add-on is the Tailscale client and makes it possible to access your HA instance inside the VPN network, the integration connects to your Tailscale account and provides statistical information about all your nodes within your VPN network.

**Comment by computermaster0101** [comment]
Thank you! You are 100% correct! I'm using the add-on
