### ISSUE TITLE
Samsung Family Hub

### ISSUE THREAD

**Issue by nelsonpita** [home-assistant/home-assistant.github.io#25004]
### Feedback

I tried adding my fridge and opening up the settings from the UI and I see the following message:

This entity ('camera.familyhub_camera') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

### URL

https://www.home-assistant.io/integrations/familyhub/

### Version

2022.11.3

### Additional information

I tried adding my fridge and opening up the settings from the UI and I see the following message:

This entity ('camera.familyhub_camera') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

**Comment by tvcastilho** [comment]
Same Here

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
