### ISSUE TITLE
seriously terrible instructions for a beginner

### ISSUE THREAD

**Issue by fredphoesh** [home-assistant/home-assistant.github.io#25007]
### Feedback

Hello,
All I want from Home Assistant is to be able to turn on a device using my phone. That's it.
I know it can be done due to the device in question being capable of being controlled by Home Assistant... but there is where useful info ends for me.
Your instruction pages are starting at a point way beyond what would be "the next step" for me... 
It would be very useful, particularly for entry level people, to have a very basic step by step. Even the fact the app for android is called odroid or something... these instructions make loads of assumptions that a newbie does not have knowledge about.
Opening the app it asks for "an instance i would like to be connected to" - instance of what? how? ... ???

### URL

https://www.home-assistant.io/installation/odroid

### Version

latest odroid

**Comment by dannytsang** [comment]
Hi @fredphoesh 

Home Assistant needs to run on a computer and then the mobile app connects to the computer running Home Assistant. I agree, it's not very clear this is how to run it and I am waiting for a documentation change to go through before looking adding more to the getting started pages.

[Odroid](https://www.hardkernel.com/) is a computer (for all intense purposes) so the installation page is for installing Home Assistant on the Odroid computer.

When it says *an instance*, it means your Home Assistant. You can technically run multiple  copies of Home Assistants at the same time e.g. for testing purposes and each copy of Home Assistant is referred to an instance.

If you need further assistance on your install, I would suggest going to places listed [here](https://www.home-assistant.io/installation/).

I hope this helps.

-- Danny
