### ISSUE TITLE
feed back

### ISSUE THREAD

**Issue by jimwoodworth** [home-assistant/home-assistant.github.io#25017]
### Feedback

https://www.home-assistant.io/integrations/linksys_smart

After editing configuration.yaml, do you need to restart things?  Do the changes kick in automatically?

Include this in the docs.

### URL

https://www.home-assistant.io/integrations/linksys_smart

**Comment by frenck** [comment]
Hi there @jimwoodworth 👋 

That is generic information about Home Assistant and not specific to the linksys integration you left a comment on.

For more information about the Home Assistant configuration files, see this part of the documentation:

<https://www.home-assistant.io/docs/configuration/>

More specifically related to your comment, here: <https://www.home-assistant.io/docs/configuration/#reloading-changes>

../Frenck
