### ISSUE TITLE
Water usage integrating

### ISSUE THREAD

**Issue by uefik** [home-assistant/home-assistant.github.io#25016]
### Feedback

Very lacking in diy integrations of the Valve object, with open-closed states and corresponding icons.

### URL

https://www.home-assistant.io/docs/energy/water

### Version

2022.11.4

**Comment by frenck** [comment]
> with open-closed states and corresponding icons.

Open & closing states/icons have nothing to do with the Energy dashboard.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
