### ISSUE TITLE
minimum needed information are missing

### ISSUE THREAD

**Issue by laithsaid** [home-assistant/home-assistant.github.io#25027]
### Feedback

The page is missing minimum needed information, e.g. when the integration is installed, the first pop up you get is asking for the host ... what does that mean? what shall we fill in here?

### URL

https://www.home-assistant.io/integrations/p1_monitor/

**Comment by klaasnicolaas** [comment]
![image](https://user-images.githubusercontent.com/20448157/203429240-b31196ac-c5a8-4594-802f-83044f83db08.png)

That is already explained exactly under the input field. 🤷🏻

**Comment by laithsaid** [comment]
Hi,Thanks for reply. For a user that does not know anything about how this integration is supposed  to work, like me, I do not understand what it is for. I thought that I can use this integration to read my el. meter using USB to P1 cable, there have we no host. Best regardsLaith…On 22 Nov 2022, at 22.56, Klaas Schoute ***@***.***> wrote:﻿

That is already explained exactly under the input field. 🤷🏻

**Comment by frenck** [comment]
From the integration documentation:

![image](https://user-images.githubusercontent.com/195327/203547033-381a2719-3b18-4c4b-a6e4-1162110462fc.png)


It tels that the integration uses the P1 Monitor platform, which is actually linked to P1 Monitor website. Please consult their website and documentation on how to use your cable.

We integrate with devices and services, but Home Assistant isn't a manual for those devices and services. For example, we also don't tell you how to install your Philips Hue hub. These kind of things are (or at least should be and is assumed) perfectly documented by the third party.

../Frenck
