### ISSUE TITLE
Include more info about syntax for target etc.

### ISSUE THREAD

**Issue by nawwman** [home-assistant/home-assistant.github.io#25022]
### Feedback

Please provide further info about the proper syntax how to configure target, data etc. for the notify.notify service call, or directly link to the appropriate sections where that information can be read up. Otherwise it's not clear how to configure this service call

### URL

https://www.home-assistant.io/integrations/notify/

**Comment by frenck** [comment]
This part of the documentation documents that bare basics around the generic capabilities of the notify platform.

Integration can extend and provide the details on their use of the notify service. Please consult the documentation of the integration you are using for more details on how those parameters work.

../Frenck
