### ISSUE TITLE
Add information for "path" field

### ISSUE THREAD

**Issue by war4peace** [home-assistant/home-assistant.github.io#25037]
### Feedback

"Path" field requires this value: "/sabnzbd" 
I had to google-fu to obtain this piece of information, which should have been in the documentation page directly.

### URL

https://www.home-assistant.io/integrations/sabnzbd/

**Comment by shaiu** [comment]
@war4peace Thanks
I will work on it

**Comment by frenck** [comment]
This should ideally be added to the config flow as a field description, not the docs.

**Comment by shaiu** [comment]
> This should ideally be added to the config flow as a field description, not the docs.

Yes. That was my direction. Thanks!

**Comment by war4peace** [comment]
Sure thing, any place which is readily visible would work. The point was to have it readily available when configuring.
As long as it won't require searching various forums to figure out what to put in that field, it would work :)

**Comment by shaiu** [comment]
@war4peace actually it looks like the "Path" is redundant and it works without it (also when changing base_url in Sabnzbd server)
Can you try without it?

**Comment by war4peace** [comment]
I had tried without it, and was receiving errors, then I looked up online which value should I put, stumbled upon a forum thread mentioning the value from the first post, added it and then it worked.
FWIW I am using a docker sabnzbd (it shouldn't matter, but maybe it does) and docker HA, both hosted on the same server.

**Comment by shaiu** [comment]
@war4peace what is the error you get in the logs?
Also, what is the url path when you browse the Sabnzbd server?

**Comment by war4peace** [comment]
The error appeared during configuration, when I filled all the fields in the integration pop-up.
The URL path is the server's IP address (in my case, http://192.168.2.10:8282).
With the Path field empty, there was an error which I don't quite recall, however it was on the pop-up itself.
Interestingly, I can no longer replicate the error when adding another integration with the same settings, but an empty path field.

**Comment by shaiu** [comment]
@war4peace So what I think happened is that at the time of the configuration there was a network error of some sort and because of that the setup failed and because of the "Path"
So what I'm going to do is remove the "Path" entirely from the configuration.
We can see here in the Sabnzbd server code that both "/api" and "/%s/api" are mounted for API calls:
https://github.com/sabnzbd/sabnzbd/blob/9a4d56e4e11fcf97985c27474b53babd7cd77d03/sabnzbd/interface.py#L322

FYI @frenck

**Comment by war4peace** [comment]
That's fine, one less thing to worry about :)
