### ISSUE TITLE
Say more about WHY on the information pages 

### ISSUE THREAD

**Issue by AndySymons** [home-assistant/home-assistant.github.io#25038]
### Feedback

Home Assistant documentation is generally long on HOW to do something but short on WHY you would want to do it in the first place. That makes it difficult for a beginner to navigate and make the best choices. We are confronted ultimately with days of frustrating trial and error before we get the hang of it.    

An example is the "Switch as X" page, which describes clearly how to use the integration but not why one would want to. I stumbled upon it by chance and assumed it must be best practice to call a light a light and not a switch. But there is nothing in the documentation that says this. What would be the consequences down the road of not using this? Are there alternatives? 

An introductory paragraph about the benefits, consequences of the choice to use it or not and an indication of the alternatives would be welcome on this and many other Home Assistant pages. 

### URL

https://www.home-assistant.io/integrations/switch_as_x/#:~:text=Adding%20Change%20device%20type%20of%20a%20switch%20to,become.%20Switch%20as%20X%20from%20the%20existing%20entity

### Additional information

FYI my aim was to migrate from a system based on Alexa and Smart Life to one that uses Home Assistant. I realised fairly quicly that I had to detach Smart Life from Alexa and pass the devices and scenes 'through' Home Assistant, which converts switches and plugs to lights using 'Switch as X' where applicable (almost everything in my case) then exposes them (and not the switches) to Alexa.

**Comment by frenck** [comment]
> An example is the "Switch as X" page, which describes clearly how to use the integration but not why one would want to. 

![image](https://user-images.githubusercontent.com/195327/203749927-f9e71407-213b-44d5-8c1a-d47be84a8503.png)

It clearly describes the why?

> Are there alternatives?

Not using it 🤷 

> An introductory paragraph about the benefits, consequences of the choice to use it or not and an indication of the alternatives would be welcome on this and many other Home Assistant pages.

I'm not following the point you are trying to make?

This integration allows you to morph an switch entity into other entity types in case that is appropriate / matches your use case better.

../Frenck
