### ISSUE TITLE
Multiple conditions - default is AND or OR?

### ISSUE THREAD

**Issue by surfingbytes** [home-assistant/home-assistant.github.io#25034]
### Feedback

Please add information whether default is AND or OR when there is multiple conditions. It's really not clear from frontend nor docs.
Example of 2 conditions:

`condition:
  - condition: state
    entity_id: input_select.mode
    state:
      - Day
      - Evening
  - condition: state
    entity_id: switch.hall_switch_main_door_l1
    state: "on"
`

![image](https://user-images.githubusercontent.com/94438335/203662545-0b2e1052-b235-4ad0-aaff-75a5def8a9a4.png)

### URL

https://www.home-assistant.io/docs/automation/condition/

**Comment by frenck** [comment]
The page you left a comment on, links to the definitions of the conditions, that page shows in the introduction:

![image](https://user-images.githubusercontent.com/195327/203719385-ed3c0727-1e35-4884-ac83-78ee96aebc69.png)

ref: <https://www.home-assistant.io/docs/scripts/conditions/>
