### ISSUE TITLE
dependencies HA Core: Starting with 2022.11.1++ rustc has to be installed 

### ISSUE THREAD

**Issue by 00lex** [home-assistant/home-assistant.github.io#25039]
### Feedback

add rustc to the pre installed dependencies for Home Assistant Core RPi, VIRTUAL ENVIRONMENT

`sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata
`

### URL

https://www.home-assistant.io/installation/raspberrypi

**Comment by frenck** [comment]
As per documentation:

![image](https://user-images.githubusercontent.com/195327/203749109-1d9496b3-3d83-4e95-95b7-62dfcc9c699b.png)

Closing this issue for that reason.

../Frenck

**Comment by 00lex** [comment]
its ok for me but the described installation works 100% on a RPi (virtual environment) until 2022.10.5. 
starting with 2022.11.0 rustc is missing. from time to time someone will ask unnecessarily in the forum for help.
bye
