### ISSUE TITLE
Indicate more clearly if a device will work without the Cloud/Internet

### ISSUE THREAD

**Issue by MagnavoxTG** [home-assistant/home-assistant.github.io#25048]
### Feedback

Problem: If I look at the documentation for any integration I can see its IoT class. If that class is "Local Polling" or "Local Push" I would assume that the device works fine even without the cloud. However, this is not the case. HA can still talk to these devices even if the cloud is down but the device may not work at all. This confusion is further amplified by cloud icon on the HA frontend. As a user I would assume any integration and device that does not have that cloud icon to still work even if there is no internet available.

Example: If you block the Nuki bridge (https://www.home-assistant.io/integrations/nuki/) from the internet it works fine for a couple of hours but if you restart home assistant after a given time period and it tries to re-authenticate with the bridge the bridge rejects any authentication until cloud access is restored. Meaning I would be unable to unlock the door which could lead to serious problems.

Proposed Solution: Add an additional indicator or/and a list of devices for each integration that communicates clearly if a device will work in an internet free environment.

### URL

https://www.home-assistant.io/integrations

### Version

2022.11.4

**Comment by pschmitt** [comment]
Erm, the nuki component does not rely on the cloud at all. The underlying library (pynuki) doesn't even support talking to the nuki cloud.

**Comment by MagnavoxTG** [comment]
@pschmitt I think you misunderstood. The problem is that you cannot re-auth to the bridge (when you restart home assistant for example) when the bridge is blocked from the cloud. Meaning: Its all well and good that the integration talks to the bridge locally but that does not do me any good if the bridge does not work without the cloud.
This post was intended to change the way "local" integrations are displayed in the docs and in the GUI. Local does not mean it will work if the device does not have access to its cloud. I find that to be very confusing and I do not think I am alone in this. 
However, some people pointed out, that this is not the right place to make such a request so I created one in the HA forums (https://community.home-assistant.io/t/indicate-more-clearly-if-an-device-will-work-without-the-cloud-internet/493917). So I guess this issue can be closed.
