### ISSUE TITLE
Card Type Light; Different Layout

### ISSUE THREAD

**Issue by 1Reed** [home-assistant/home-assistant.github.io#25044]
### Feedback

Would be nice to have the Layout of the card match the layout of other cards, like the one of tiles or entities..

Something like icon on the left and just a horizontal slider on the left of that.

Maybe have some  configuration variable like: layout: central (for the now standard) and horizontal

### URL

https://www.home-assistant.io/dashboards/light/

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
