### ISSUE TITLE
add instructions how to add python library to home-assistant

### ISSUE THREAD

**Issue by fluxpiada** [home-assistant/home-assistant.github.io#25055]
### Feedback

I cannot execute this code because there are no instructions on how to add python library to home-assistant. please expound or link to instruction pages. I have searched discord and community pages to no avail. 

### URL

https://www.home-assistant.io/integrations/evohome#useful-jinja-templates

**Comment by frenck** [comment]
> cannot execute this code because there are no instructions on how to add python library to home-assistant

There is no Python library to add, all of you are looking at on that page, is built-in.

Jinja templates can be used in many places in Home Assistant, for example: automations, scripts, template entities, service calls, and many more places.

If you like to play with them, the best place to go (in my opinion) is the template tool in the developer tools:

[![Open your Home Assistant instance and show your template developer tools.](https://my.home-assistant.io/badges/developer_template.svg)](https://my.home-assistant.io/redirect/developer_template/)

../Frenck
