### ISSUE TITLE
Wi-Fi warning about bridged adapter too definitive

### ISSUE THREAD

**Issue by ber-ro** [home-assistant/home-assistant.github.io#25053]
### Feedback

source/_includes/installation/operating_system.md contains a warning:
> Please keep in mind that the bridged adapter only functions over a hardwired ethernet connection. Using Wi-Fi on your VirtualBox host is unsupported.

I almost wanted to stop trying Home Assistant, but as I had created the VM already, I finished my trial. I was surprised that everything was working (only controlling a Wiz Wi-Fi light bulb).

I would suggest to weaken the warning:
> Using Wi-Fi on your VirtualBox host is unsupported but may work. Depending on your use case a hardwired ethernet connection is required for your bridged adapter.

### URL

https://www.home-assistant.io/installation/windows

**Comment by ber-ro** [comment]
I still find the text misleading.

**Comment by frenck** [comment]
We generally don't recommend or support running Home Assistant on Wi-Fi itself.
Considering it being a central part/hub of the home, we cannot stress enough to not use it.

It is for the same reason, nothing on Wi-Fi is documented on setting up Wi-Fi for other devices.

Nevertheless, thanks for your suggestion. If it works for your case, then you can surely keep using it as you wish 👍 

../Frenck
