### ISSUE TITLE
Fibaro integration doesn't bring MCO MH5-2A thermostats to Home Assistant

### ISSUE THREAD

**Issue by maxfok** [home-assistant/home-assistant.github.io#25065]
![Screenshot 2022-11-27 at 12 57 27 PM](https://user-images.githubusercontent.com/301562/204131730-f0c6b14a-5d16-4c14-ab70-6f8af54190e8.png)

### Feedback

hello, It would be great if you could add MCO MH5-2A thermostats to fibaro integration. Those thermostats are not currently controllable by Home Assistant via the Fibaro Integration as it shows only the sensors (temperature & humidity). It would be great if you could add Fibaro profiles (Home, Away, Vacation, Night)  as well so to run fibaro scenes scenes by pressing one button.

### URL

https://www.home-assistant.io/integrations/fibaro/

### Version

2022.11.4

**Comment by rappenze** [comment]
Please report bugs to home-assistant/core and not to the documentation repository.
For feature requests I think the community forums should be used.

Anyway the support for the thermostat should come with release 2022.12, see https://github.com/home-assistant/core/issues/70017.

To fibaro profiles unfortunately I cannot say anything as I have a Home center 2 and I think they where introduces with Home Center 3.

Starting a scene is working for HC2 but not for HC3. There is an open bug report for that: https://github.com/home-assistant/core/issues/80805

**Comment by riemers** [comment]
It was just merged, and my hvac components are working and are visible in home assistant, thanks for the great work @rappenze!
