### ISSUE TITLE
New Soma Connect USB Hardware

### ISSUE THREAD

**Issue by Xiondewah** [home-assistant/home-assistant.github.io#25067]
### Feedback

Any chance we can have an update on the soma integration for the new USB hardware?  It seems to be a big improvement over the old RPi version.

### URL

https://www.home-assistant.io/integrations/soma/

**Comment by sebfortier2288** [comment]
Hey there!
I personnally don't have this new hardware so I can't answer for sure. 
But from my understanding, this new hardware seems to host the same software as the old rPi model. If that is the case and it is still exposing the same api, I'm pretty sure the integration should work.

@ratsept can you confirm if that is really the case? Is there any updates that should be done in the integration to support it?

**Comment by Xiondewah** [comment]
Hi

I do have the hardware and the integration does connect but none of the covers are shown - so I’m not sue whether the software etc is exactly the same.

On 28 Nov 2022, at 01:14, sebfortier2288 ***@***.***> wrote:



Hey there!
I personnally don't have this new hardware so I can't answer for sure.
But from my understanding, this new hardware seems to host the same software as the old rPi model. If that is the case and it is still exposing the same api, I'm pretty sure the integration should work.

@ratsept<https://github.com/ratsept> can you confirm if that is really the case? Is there any updates that should be done in the integration to support it?

**Comment by frenck** [comment]
Hi there 👋 

This seems to be a feature request, and not end-user documentation feedback; therefore, closing this documentation feedback issue. If you want to request new features or support for new devices, please use our community forums.

Thanks! 👍 

../Frenck

**Comment by Xiondewah** [comment]
Yes, sorry, but I can’t see how to submit anything relating specifically to the integration!

On 28 Nov 2022, at 07:31, Franck Nijhof ***@***.***> wrote:



Hi there 👋

This seems to be a feature request, and not end-user documentation feedback; therefore, closing this documentation feedback issue. If you want to request new features or support for new devices, please use our community forums.

Thanks! 👍

../Frenck

**Comment by ratsept** [comment]
I think you can just start a new topic there and my username should be the same on the forums as well. 

The new hardware is based on completely different hardware so the code is definitely not the same. I have the HA integration update planned for as soon as possible. It is only a small change that is required and the Python library has already been updated to work with the new hardware (but HA still uses the old one). I have been using the new hardware in my own home with HA (2022.8.5 version) for a few months already and it seems to work. I just need to set up a development environment for HA again to make this update public (I just patched the changes in manually in my HA instance).
