### ISSUE TITLE
Honeywell integration doesn't describe sensors/actions in detail

### ISSUE THREAD

**Issue by garyo** [home-assistant/home-assistant.github.io#25077]
### Feedback

The Honeywell integration page (https://www.home-assistant.io/integrations/honeywell/) doesn't list the sensors or actions available once you integrate it. I can see a few sensors in the history (current temp, humidity, heat on/off) but they are not listed anywhere.

Also it would be nice to show an example of adding a Lovelace card to show current temp, set point, etc.

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2022.11.4

**Comment by rdfurman** [comment]
Not sure I follow on your comment about sensors not being listed. I can see them:

![Screenshot_20221128-084955.jpg](https://user-images.githubusercontent.com/2547448/204321604-0cca1f0c-8e48-4af3-83c9-9f0e541a034a.jpg)

As for the Lovelace example, I certainly could add a screenshot of the thermostat card. Is that what you're looking for? It doesn't look any different than adding any other thermostat though.

**Comment by garyo** [comment]
That screenshot only shows outdoor temp & humidity. I assume it also adds a number of "standard" thermostat sensors & actions like set point, actual temp, actual humidity, heat on/off? Those aren't listed anywhere I can see. (I don't have any other thermostats; this is my first one in HA -- so if I'm missing something feel free to point me to where those sensors/actions are listed.)

**Comment by rdfurman** [comment]
The only other entity that the honeywell integration will add is the thermostat. Thermostats will show all the attributes you listed (set point, actual temp, etc.). I can add that to the table if you think that will help.

**Comment by garyo** [comment]
I may just be confused -- I can't find that entity. I know the attributes exist because I can see them in the history. Maybe they're just called something I can't figure out.
![image](https://user-images.githubusercontent.com/139975/204329836-c70bd3ee-da98-4d39-840f-2c0d7ef7bc1c.png)

**Comment by garyo** [comment]
I figured it out -- those are "attributes" of the thermostat entity, not sensors themselves (confusing to me because I have some BLE temp monitors where the current temp is a sensor). I added a custom card that can show history of entity attributes and that works well. Thanks for helping out a newbie!

**Comment by rdfurman** [comment]
@homeassistant close
