### ISSUE TITLE
KNX Climate misstype

### ISSUE THREAD

**Issue by Barry-Ricoh** [home-assistant/home-assistant.github.io#25071]
### Feedback

In the documentation is written under „climate“ that there are 2 „setpoint_shift_modes“ DPT9002 and DPT6002.
Later under explaining „Configuration Variables“ there is written DPT9002 and DPT6010 ( instead of 6002).
And i think that correct will be 6001 ?

### URL

https://www.home-assistant.io/integrations/knx/#climate

**Comment by farmio** [comment]
Oh, thank you! Do you want to also open a PR to fix it?
The correct one is `6010` (since DPT 6.001 is percent and 6.002 is not specified).

**Comment by Barry-Ricoh** [comment]
Hello,I dont know what a PR is and how to open one.I think i do not need it if you know how to fix it.But as you wrote 6.001 is percent but 6.010 is counter pulse.That for me makes no sense in combination with temperature!Sorry for asking.Your Name sounds a Little bit German?If so for me it was a little bit easier to answer in German!😬Greetings Von meinem iPhone gesendetAm 28.11.2022 um 08:09 schrieb Matthias Alphart ***@***.***>:﻿
Oh, thank you! Do you want to also open a PR to fix it?
The correct one is 6010 (since DPT 6.001 is percent and 6.002 is not specified).

**Comment by farmio** [comment]
Don't worry, I'll take care of it.

Yes, you are right, `counter pulse` also doesn't make sense... but it's closer to the thing than percent and that's what's being used by the actuators I've seen 🤷
