### ISSUE TITLE
Restart required

### ISSUE THREAD

**Issue by dmsims** [home-assistant/home-assistant.github.io#25081]
### Feedback

After adding the lines to configuration.yaml a Home Assitant restart is required

This step is missing from the documentaion

### URL

https://www.home-assistant.io/integrations/evohome

**Comment by frenck** [comment]
This is generic to Home Assistant and not specific to this documentation.
To learn more about the Home Assistant configuration, check out the documentation on it here:

<https://www.home-assistant.io/docs/configuration/>

This documentation is also linked on the Honeywell Total Connect Comfort page.

../Frenck
