### ISSUE TITLE
Integrating WLED Sound reactive 13.3 effects not working

### ISSUE THREAD

**Issue by whateverxz** [home-assistant/home-assistant.github.io#25087]
### Feedback

currently, right now the effects of WLED sound reactive(13.3) are shown
![image](https://user-images.githubusercontent.com/113348394/204428441-7c30cda2-ece0-4d89-aea5-88bcbff9199c.png)
and I am unable to use it in any automation but when using normal WLED (13.3)
![image](https://user-images.githubusercontent.com/113348394/204428645-fe879805-b8ef-4164-bd71-fdccb40e3178.png)
effects usable

### URL

https://homeassistant.local:8123

### Version

2022.11.0

**Comment by frenck** [comment]
This is a sound reactive issue. They misuse the effects field. Feel free to report it upstream.

../Frenck

**Comment by whateverxz** [comment]
Where can I report it too?
