### ISSUE TITLE
Is Timer always a count-down timer?

### ISSUE THREAD

**Issue by Bart56** [home-assistant/home-assistant.github.io#25086]
### Feedback

All the exampls initialize the timer to a starting quantity of time. It implies that it only counts down, but it is not stated here. If there is a way to allow the timer to count up (increasing so as to time an event duration) it is not clear here.

### URL

https://www.home-assistant.io/integrations/timer/

### Version

2022.11.2

### Additional information

After reading the page, it is unclear whether this is only a count-down timer and if it is, should b labelled as such? If it will count up, then let the documentation show it in an example maybe?

**Comment by frenck** [comment]
> If there is a way to allow the timer to count up (increasing so as to time an event duration

As the introduction describes, it fires an invent as a timer finishes.

It is an equivalent of a kitchen timer.

../Frenck

**Comment by Bart56** [comment]
Hi
Thanks for the quick response.
Since it only counts down, I decided to set it for 23:59:59 then do some
math subtracting the stop time but the timer starts at 24:01:06. So I tried
11:59:59 and it starts at 12:01:06. Is this a bug?
I'm trying to do this because History_stats does not seem to work on a
binary sensor defined in ESPHome so I was looking for a work-around.
Cheers,
Bart

**Comment by frenck** [comment]
If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by Bart56** [comment]
Yes - thank you Franck
