### ISSUE TITLE
Energy card and KNX

### ISSUE THREAD

**Issue by Ives25** [home-assistant/home-assistant.github.io#25088]
![HA-template3](https://user-images.githubusercontent.com/50076025/204492790-e9113647-8c4c-456d-9dc5-b6d15cb94a5f.jpg)
### Feedback

I can't seem to create an entity that appears in its "add a source for water consumption" list (works for gas and electricity).

### URL

Home Assistant 2022.11.4 Supervisor 2022.11.2 Operating System 9.3 Interface utilisateur : 20221108.0 - latest

### Version

A URL with a link to the page you are providing feedback for.

### Additional information

knx_sensor.yaml
#Compteur eau (m3)
  - name: eau_m3
    state_address: "9/7/3"
    type: "volume"
    sync_state: every 30

sensors.yaml
- platform: template
  sensors:
    compteur_eau_home:
      friendly_name: 'Eau home'
      value_template: "{{ (states('sensor.eau_m3') |float *1000 )|round(2) }}"
      unit_of_measurement: 'L'
      icon_template: mdi:water
      device_class: water
      attribute_templates: 
        state_class: total_increasing

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for providing support. If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or the [Community forum](https://community.home-assistant.io).

Thanks! 👍
