### ISSUE TITLE
Update install instructions for Linux

### ISSUE THREAD

**Issue by Schlue** [home-assistant/home-assistant.github.io#25098]
### Feedback

Hi,

thanks for home-assistant and the good installation documentation.

I just updated to version 2022.11.4 and git an error, that rustc is not installed to build the cryptography package. So you can maybe add rustc to Code block "Install the dependencies":

sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata rustc

 BR
Michael

### URL

https://www.home-assistant.io/installation/linux

### Version

2022.11.4

**Comment by frenck** [comment]
As per the big warning sign above, the installation instructions:

![image](https://user-images.githubusercontent.com/195327/204730615-04339705-47c4-4113-add9-143f61a3a20f.png)

../Frenck
