### ISSUE TITLE
Heyu X10 integration doesn't work when Home Assistant runs in a docker container

### ISSUE THREAD

**Issue by eil047** [home-assistant/home-assistant.github.io#25106]
### Feedback

See also in this post on the forum: https://community.home-assistant.io/t/x10-automation/209086
This should be mentioned in the Heyu X10 documentation to prevent waste of time

### URL

https://www.home-assistant.io/integrations/x10/

**Comment by frenck** [comment]
Hi there @eil047 👋 

It seems like you want to report an issue with an Home Assistant integration, instead you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by eil047** [comment]
Hi Frenck
Yes, this was a documentation feedback in the first place. In the Heyu X10 documentation it should be mentioned that X10 only works in a Core implementation, to prevent waste of time and frustration.
Make X10 also work in a docker container could be nice also but I don't know if there is enough intrest to justify the required resources.

**Comment by frenck** [comment]
I guess we don't agree on it being a bug.

Let's make sure we raise an issue first and trying to address it. Addressing it should be preferred over documenting limitations.

../Frenck
