### ISSUE TITLE
TS000F Aubess Power Monitoring Switch showing wrong

### ISSUE THREAD

**Issue by hedevej41** [home-assistant/home-assistant.github.io#25108]
### Feedback

Power Monitoring Switch

Model AP-SMT-Breaker02-1CH manufactured by Aubess
Zigbee ID: TS0001 | _TZ3000_xkap8wtb

Showing wrong/to high amps and KWh

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2022.11.5

**Comment by frenck** [comment]
Hi there @hedevej41 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
