### ISSUE TITLE
SolarEdge integration doesn't set Long-term Statistics

### ISSUE THREAD

**Issue by iruoy** [home-assistant/home-assistant.github.io#25114]
### Feedback

[SolarEdge integration](https://www.home-assistant.io/integrations/solaredge/) doesn't set [Long-term Statistics ](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

### URL

https://www.home-assistant.io/integrations/solaredge/

**Comment by frenck** [comment]
Hi there @iruoy 👋 
 
It seems like you wanted to report an issue, however, you have submitted documentation feedback instead. Please check our help page on where to go:

https://www.home-assistant.io/help

Thanks! 👍 

../Frenck
