### ISSUE TITLE
Add additional guidance for hassio.backup_full

### ISSUE THREAD

**Issue by 7kXr** [home-assistant/home-assistant.github.io#25119]
### Feedback

I found this page in hopes to add an automation for a backup and the service name was incorrect for my HA OS instance. I ended up using `hassio.backup_full` after resulting in a failed automation. 

### URL

https://www.home-assistant.io/integrations/backup

**Comment by frenck** [comment]
Hi there @7kXr 👋 

The page you are leaving a suggestion on, does not match the service call you are mentioning.

As per the top of that page:

![CleanShot 2022-12-02 at 09 17 33](https://user-images.githubusercontent.com/195327/205247634-c03c1a6e-cc4f-4d2e-bb9f-a34a4fdb3c38.png)

The `backup` integration is for Home Assistant Core and Container installation types. 

You seem to be running either the Home Assistant OS or Supervised installation type, which is mentioned in the information box in the above screenshot too. It links here:

https://www.home-assistant.io/integrations/hassio

That page contains information on the `hassio.backup_full` service.

../Frenck
