### ISSUE TITLE
Where to find config_entry_id

### ISSUE THREAD

**Issue by EvertJob** [home-assistant/home-assistant.github.io#25122]
### Feedback

Where can I find the "config_entry_id" for the Picnic add product service?

### URL

https://rc.home-assistant.io/integrations/picnic

### Version

2202.11

**Comment by frenck** [comment]
It is an internal identifier, which is not directly exposed.

All parts in the Home Assistant UI (developer tools, automations editor, scripts editors, Dashboards, Blueprints), will provide an input for it, in which you can select your PicNic account in this case. No direct interaction with the config entry ID is there.

In case you want to figure it out manually, that is possible (but not that common I guess). If you click on integration in your integration dashboard, it will be visible as part of the URL you'll be visiting.

../Frenck
