### ISSUE TITLE
Xiaomi miio integration (Xiaomi Miio) I do not see this model (zhimi.airp.cpa4)

### ISSUE THREAD

**Issue by hscrystal** [home-assistant/home-assistant.github.io#25124]
### Feedback

Hi.

I can  connected xiaomi air purifier 4 COMPACT (not simple 4, not 4 PRO) into Hassio?
I would be happy if I can get any directions.

In the Xiaomi miio integration (Xiaomi Miio) I do not see this model (zhimi.airp.cpa4)

Thanks in advance

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2022.11.5

**Comment by rytilahti** [comment]
This is not a documentation issue so I'm closing this, but if the device is not autodetected or listed, it is not unfortunately currently supported.
