### ISSUE TITLE
Need instructions on how to restore

### ISSUE THREAD

**Issue by OldSurferDude** [home-assistant/home-assistant.github.io#25135]
### Feedback

Backups are great, but not if you can't restore.

What's the difference between "reload" and "upload backup"?

### URL

http://192.168.1.140:8123/hassio/backups

### Version

2022.11.4

**Comment by dannytsang** [comment]
This page *should* explain it: https://www.home-assistant.io/common-tasks/supervised/#restoring-a-backup-on-a-new-install

Feedback welcome if it's not very clear.

**Comment by OldSurferDude** [comment]
Thanks!  

What was not clear was the one  clicks on (+ CREATE BACKUP) which is obvious, but where to click to restore was in a completely different place, which turns out to be clicking on the backup itself.  To copy the backup to another place one has to install the samba add-on.  Then one connects to location of the HA files as if it were a samba network drive.  The file name of the back is a random hex number.  Therefore, one must sort the directory by "date modified, descending" to find it.

While the backup process works, it's not intuitive and a cookbook example that goes through the process would be of much use.

thanks again!

OSD

**Comment by OldSurferDude** [comment]
Actually, this was a request to improve the documentation and the page.  Alas, I am too inexperienced to figure out how to do that.
