### ISSUE TITLE
Growatt integration

### ISSUE THREAD

**Issue by SrekerGER** [home-assistant/home-assistant.github.io#25132]
### Feedback

Hi,

i am trying to install the Growatt integration. As soon as i enterd my credentials for the Growatt server (https://server-api.growatt.com/) an error occurs. (Entering the credentials on the website works)

The Error message is "Unknown error occurred"

 I have no idea what to do or where to search, maybe someone can help?

Thanks a lot for your help

### URL

https://github.com/home-assistant/home-assistant.io

**Comment by frenck** [comment]
Hi there @SrekerGER,

Is seems like you wanted to report an issue with an Home Assistant integrations, however, you have submitted documentation feedback instead. Please report issues with Home Assistant integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
