### ISSUE TITLE
Support for multiple devices

### ISSUE THREAD

**Issue by ddelmont** [home-assistant/home-assistant.github.io#25130]
### Feedback

Not sure this is the correct location for a request.  Would it be possible to add a drop down to select which home assistant to connect to?  As great as zero tier support is it's a real pain to change the IP every time to switch between my home and vacation home!  Ty.  

### URL

https://play.google.com/store/apps/details?id=io.homeassistant.companion.android

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
