### ISSUE TITLE
Aftership integration now requires pro or higher

### ISSUE THREAD

**Issue by bvierra** [home-assistant/home-assistant.github.io#25138]
### Feedback

Aftership apparently has updated their plans again and have removed the API integration from the essentials plan and added it to only pro and up. The pro plan is $120 USD a month.

Confirmed that trying to create an API key with the essentials plan will not work (gives a link to upgrade).

The pricing page is at: https://www.aftership.com/pricing

### URL

https://www.home-assistant.io/integrations/aftership/

### Version

2022.11.5

**Comment by balloob** [comment]
Can you open a PR for the docs to mention this?
