### ISSUE TITLE
Solax integration proxy

### ISSUE THREAD

**Issue by quetzal** [home-assistant/home-assistant.github.io#25151]
### Feedback

Hello,

You don't need wifi proxy as described in the solax documentation ("Inverter models with newer firmware (and also those using devices like PocketWifi) no longer expose an API when connected to your wireless network, they do however continue to expose it on their own broadcasted SSID.").

It depend on the ip you try to access.
For example, the pocketwifi ip on my network is 192.168.88.10. I can't access on it. 
But if on my home assistant I add the route: "route add -host 5.8.8.8 gw 192.168.88.10", now I can access to my solax data on 5.8.8.8 without connecting to it wifi directly and without proxy, but directly on the ip 5.8.8.8

### URL

https://www.home-assistant.io/integrations/solax/

**Comment by fxstein** [comment]
@quetzal Thanks for posting! Will be testing this in January with a set of new Solax Inverters and batteries.

**Comment by nazar-pc** [comment]
There is also https://community.home-assistant.io/t/solax-x3-hybrid-g4-wifi-firmware-solax-module-fw-version-3-003-02-home-assistant-integration/490181 that says it is possible to get data (I tried with X1 Hybrid G4, it does return something) even through client IP.

**Comment by nazar-pc** [comment]
I found that https://github.com/squishykid/solax/issues/107 is the reason it wasn't connecting, had to patch `discovery.py` in `solax` package manually and it worked. Though I'd like it to be possible to use DNS name there in addition to IP address.

**Comment by msbealo** [comment]
I'm still trying to get my Solax X1-Fit and Solax X1-Boost to work. Both with Pocket Wifi. There appears to be some extra information above but I'm still struggling.
