### ISSUE TITLE
Eight Sleep: Error 429 (Too Many Requests) & 403 (Forbidden)

### ISSUE THREAD

**Issue by jrmfreitas88** [home-assistant/home-assistant.github.io#25165]
### Feedback

I am unable to setup the Eight Sleep Integration with Home Assistant version "2022.11.5" (docker). Adding the integration either via the Web-Interface or via the configuration file ("configuration.yaml") results into the errors 429 (Too Many Requests) and 403 (Forbidden). Enclosing the username and password in double quotes results into the same problem.

Logs are posted bellow under "Additional information", however user id replaced by "xxx" for privacy reasons.

### URL

https://www.home-assistant.io/integrations/eight_sleep/

### Version

2022.11.5

### Additional information

Logger: pyeight.eight
Source: components/eight_sleep/__init__.py:103 
First occurred: 22:43:53 (2 occurrences) 
Last logged: 22:44:04

Error posting Eight data. 429, message='Too Many Requests', url=URL('https://client-api.8slp.net/v1/login')
Error geting Eight data. 403, message='Forbidden', url=URL('https://client-api.8slp.net/v1/users/xxx')

**Comment by klaasnicolaas** [comment]
Hi there @jrmfreitas88 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
