### ISSUE TITLE
//Homekit

### ISSUE THREAD

**Issue by meistermolli** [home-assistant/home-assistant.github.io#25166]
### Feedback

1. is there more configuration possible for climate thermostat?
I use to set up my HmIP Heating groups and they show an Humidity Sensor in HomeKit.
I want to set the Humidity Sensor to false inside the configuration. So I don't see an empty Humidity sensor inside HomeKit.

2. I know from an Integration for Raspberrymatic "HAP Homematic" 
https://github.com/thkl/hap-homematic/issues/294#issuecomment-751490985

that it is possible to show multiple switches inside one card like this:
![](https://user-images.githubusercontent.com/55836556/144437611-2973ec9d-2191-4d9b-a8e3-cf762c005f41.png)

is it possible to make an instruction for HASS Homekit how to do this?

Thank you

### URL

https://www.home-assistant.io/integrations/homekit/#specific-entity-doesnt-work

**Comment by meistermolli** [comment]
Hi @bdraco no idea? have some different views with an 0-100% line and a button on top for toggle. Is this possible to make something like this in my configuration? 
![IMG_4093](https://user-images.githubusercontent.com/55836556/211271392-6907afd3-2496-41f5-8f9e-ee1b01cba56e.jpeg)

**Comment by frenck** [comment]
> is there more configuration possible for climate thermostat?

Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
