### ISSUE TITLE
Yamaha MusicCast is not managing general volume

### ISSUE THREAD

**Issue by jjindrich** [home-assistant/home-assistant.github.io#25161]
### Feedback

I'm using this inegration https://www.home-assistant.io/integrations/yamaha_musiccast
I need to be able control general volume on device. I cannot find it how.

### URL

https://www.home-assistant.io/integrations/yamaha_musiccast

**Comment by micha91** [comment]
If I get your question right, you want to set the volume of your musiccast device. We extend the media_player entity platform, which provides a service called `volume_set` (documentation is located [here](https://www.home-assistant.io/integrations/media_player/#service-media_playervolume_set)). In addition the volume can also be set by using the media player widget in the UI.
If this does not work for you, provide more information about your device please.

**Comment by jjindrich** [comment]
I have media-control card. If I click on card details I see volume control. Can I add this volume control on dashboard directly - to see it and manage it from dashboard directly ?
