### ISSUE TITLE
Actual Reading

### ISSUE THREAD

**Issue by chpyoung** [home-assistant/home-assistant.github.io#25164]
### Feedback

Hi,
I´m using the graph and is very nice and useful.. and this is just a suggestion. Is possible to have the actual reading (the number) inside the graph?
I use it to have the reading of the soil humidity in my house, and have the exact number as well as the histogram will give me a better understanding of this data

Regards

### URL

no page

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
