### ISSUE TITLE
No way to change password of Tado in Home assistant

### ISSUE THREAD

**Issue by formadelfo** [home-assistant/home-assistant.github.io#25175]
### Feedback

Would be really helpfull if you can change the password in home assistant when you change the password of Tado. 

### URL

https://www.home-assistant.io/integrations/tado

### Version

all

**Comment by frenck** [comment]
Hi there @formadelfo 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix an issue in the integration.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
