### ISSUE TITLE
Automation Trigger Variables - Device and Event have same variables

### ISSUE THREAD

**Issue by SeSeicht** [home-assistant/home-assistant.github.io#25178]
### Feedback

Template variables of `Device` and `Event` are the same. 
I guess they should be different for `Device` 

![image](https://user-images.githubusercontent.com/48480298/206283219-c3651e4d-ab53-4dcd-b73d-cfd510011fd6.png)

### URL

https://www.home-assistant.io/docs/automation/templating/#device

**Comment by dannytsang** [comment]
@SeSeicht The trigger variables only exists depending if the automation was triggered by an event or a device.

 I suspect (and hope) it's intentional because you can refer to the same variables regardless if the automation was triggered by a device or an event.
