### ISSUE TITLE
Obtain your personal token: error in syntax?

### ISSUE THREAD

**Issue by Farleykri** [home-assistant/home-assistant.github.io#25186]
### Feedback

just thought i would let you know that running the line

curl --user <my_username>:<my_password> https://data.tankutility.com/api/getToken`

will result in an error on my side

curl --user <my_username>:<my_password> https://data.tankutility.com/api/getToken 

works

removing the single quote may be more user friendly!

### URL

https://www.home-assistant.io/integrations/tank_utility/

**Comment by frenck** [comment]
Thanks for reporting! I've opened up a PR to adjust the documentation!

../Frenck
