### ISSUE TITLE
history-graph names no longer show

### ISSUE THREAD

**Issue by 3ative** [home-assistant/home-assistant.github.io#25188]
### Feedback

Setting the:
show_names boolean (optional, default: true) either "True" or "False" makes no difference. 

![image](https://user-images.githubusercontent.com/51385971/206328705-4f18dc99-f295-46dc-8b98-42cca560433e.png)

### URL

https://www.home-assistant.io/dashboards/history-graph/#show_names

### Version

2022.11.x

**Comment by 3ative** [comment]
Opps
Already referenced in:
https://github.com/home-assistant/frontend/issues/14610
https://github.com/home-assistant/home-assistant.io/pull/25157

**Comment by frenck** [comment]
I am closing this as a duplicate in that case.

Please track the issue in the frontend for updates @3ative 👍 

../Frenck

**Comment by mamo-nick** [comment]
Workaround - add to History Graph Card yaml:
`show_names: true`

**Comment by 3ative** [comment]
@frenck Will do, thanks.

**Comment by 3ative** [comment]
@mamo-nick 
As mentioned in OP, that's the first thing I tried.
