### ISSUE TITLE
hvac_action not described in Generic Thermostat documentation

### ISSUE THREAD

**Issue by thecreaser** [home-assistant/home-assistant.github.io#25209]
### Feedback

I'm noob, forgive me if I'm not understanding correctly.
I understand Generic Thermostat entities have attribute: hvac_action
I don't see a reference to this attribute in the documentation.

Also:
The documentation describes "Configuration Variables".  From my perspective as a noob does this mean the same thing as "attributes"?  If yes, perhaps the text could be expanded slightly to clarify?

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

**Comment by frenck** [comment]
> The documentation describes "Configuration Variables". From my perspective as a noob does this mean the same thing as "attributes"?

Those are not the same. Configuration variables is for configuring an integration, while state attributes are additional values that provide more information on an entity state.

In this case, the configuration allows you to create an `climate` entity, `hvac_action` is a possible state attribute of such `climate` entity.

> I understand Generic Thermostat entities have attribute: hvac_action
> I don't see a reference to this attribute in the documentation.

Correct. Not all `climate` entities are equal. For example, some have a single setpoint, and others have a setpoint range with a min/max. Some report their current HVAC action, while others don't.

It depends on the capabilities of the device and integration. In this case, the generic thermostat does not have an HVAC action.

../Frenck
