### ISSUE TITLE
More guidance on 'country' code setting

### ISSUE THREAD

**Issue by jgclark** [home-assistant/home-assistant.github.io#25200]
### Feedback

With 2022.12 I get a warning that my country code is not set.
I try and set it and I'm told I have to do it in YAML.
I assume this is configuration.yaml so head to https://www.home-assistant.io/docs/configuration/basic/, which confirms it should be `country: "<code>"`. However, I can't get it to be accepted as top-level settings, or under `homeassistant:`. 
Please could this page be updated to make it clearer how to add this?

### URL

https://www.home-assistant.io/docs/configuration/basic/

### Version

2022.12.0

**Comment by jgclark** [comment]
On the Discord Tediore helped me, by saying simply "ignore VSCode's warnings".
So I did so, and it then worked.
So could the documentation be clarified to say this? Otherwise I won't be the only one to believe the Studio Code Server for HA ...

**Comment by frenck** [comment]
> So could the documentation be clarified to say this? Otherwise I won't be the only one to believe the Studio Code Server for HA ...

That is not a documentation issue, but an issue with the vscode extension. Please report the issue with that extension instead. We can't document what third-party validators can't or can do.

../Frenck
