### ISSUE TITLE
Add custom "features" on tile card

### ISSUE THREAD

**Issue by rluvaton** [home-assistant/home-assistant.github.io#25206]
### Feedback

It would be great if we could add custom "features" on the tile card, custom icons, and our own action.

Usage example:
Let's say I have some Tile cover for my bedroom shades, additional icon next to up/down/stop would be favorite positions so I could set Night position for example

### URL

https://www.home-assistant.io/dashboards/tile/#tile-features

### Version

2022.12

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks!
