### ISSUE TITLE
Names for the new HeatPumps

### ISSUE THREAD

**Issue by virusczz** [home-assistant/home-assistant.github.io#25208]
### Feedback

The ones to support ModBus TCP are not wroten :( so will be hard for users to understand that supported are also that models:

S2125-8, S2125-12
VMM S320
SMO S40

Also in the menu of integration is not there is only S320, not the full name. 

### URL

https://www.home-assistant.io/integrations/nibe_heatpump/?fbclid=IwAR3q-f6yzky3DeH7ODgIi8ySuHY-IOsLvXmAXizgl04D4qOS5_7tSvgB7V0#udp-gateway-using-nibegw

**Comment by virusczz** [comment]
why is this closed ? 
for the integration is not changed the name, and a lot of people are confused about the names ... That in the integration is not there the VMM S320 ...
also on the webpage is not there ... only the old VMM320 thisis without modbus TCP/IP, the new one VMM S320 has modbus ...

Same for the SMO 40 vs SMO S40 
the S is the new models, the new line, like the new HeatPump S2125 the upgrade from F2140 and so on ... 

see the new lineup: 
https://www.nibe.eu/en-eu/products/heat-pumps-s-series

Thank you

**Comment by elupus** [comment]
Lack of updates (partially from me). If we lack support for pumps it needs to be added with exports from pumps to https://github.com/yozik04/nibe

But I dont fully understand what you are saying. Feature requests are not tracked here. Only bugs.

**Comment by virusczz** [comment]
That the names what are supported now is confusingThere are 2 types of main unit Old 320 and New 320Old is not supporting direct modbus and name is VMM320The New one is supporting modbus TCP and is named VMM S320 For this is already made the support with my exports, but in the integration is named only S320 …So is needed to be corected in inter integration and webpage ;) Odesláno z iPhonu14. 2. 2023 v 11:39, Joakim Plate ***@***.***>:﻿
Lack of updates (partially from me). If we lack support for pumps it needs to be added with exports from pumps to https://github.com/yozik04/nibe
But I dont fully understand what you are saying. Feature requests are not tracked here. Only bugs.

**Comment by elupus** [comment]
Old 320 is not supported, i dont think we list it as supported?

**Comment by elupus** [comment]
Never mind it is. But seems the new one was named just S320 instead of VVM S320. Okey yes that is somewhat confising.

**Comment by virusczz** [comment]
see picture:
[image: image.png]

**Comment by virusczz** [comment]
yes :)
