### ISSUE TITLE
Switchbot - Please add power usage

### ISSUE THREAD

**Issue by Nbr1Sniper** [home-assistant/home-assistant.github.io#25211]
### Feedback

Hi Switchbot team,
Please add power usage to the integration. I can see it in the app but not in Home Assistant.

### URL

https://www.home-assistant.io/integrations/switchbot

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
