### ISSUE TITLE
Is there support for the Neo stats?

### ISSUE THREAD

**Issue by swinster** [home-assistant/home-assistant.github.io#25210]
### Feedback

You have stated that the integrations support the [Heatmiser DT/DT-E/PRT/PRT-E](https://www.heatmisershop.co.uk/room-thermostats/) stats, although it is difficult to determine precisely what stats these are from the Heatmiser page. Searching Heatmiser for "DT" or "PRT" (for example) yields 0 product results, and "DE-E" and "PRT-E" shows the same four stats, which I believe are simply matched on the "-e" portion). Can this be a more specific link to the supported stats and/or use the product names rather than model references?

Ultimately, are the Neo smart stats (https://heatmisershop.co.uk/neo-smart-thermostats/) supported? If not, is it likely they ever will?

### URL

https://www.home-assistant.io/integrations/heatmiser/

### Version

2022.12

**Comment by swinster** [comment]
Still relevant

**Comment by thegit** [comment]
This project is for Heatmiser V3 protocol.
Heatmiser Neo use a different protocol.  An active project can be found here: https://github.com/MindrustUK/Heatmiser-for-home-assistant
This old Heatmiser catalogue from June 2015 might help clarify model naming conventions: http://www.heatmiser.com/downloads/datasheets/UKJune15.pdf
