### ISSUE TITLE
Local calendar feature requests

### ISSUE THREAD

**Issue by edzards** [home-assistant/home-assistant.github.io#25220]
### Feedback

Thanks for this nice local calendar! It would be awesome, if the following features could be implemented:
- After having added an event, it is not editable any longer (one needs to delete it and create a new event). Would be great if this could be fixed.
- When an event lasts for several days, it is only indicated on the starting day. Would be very convenient to have a e.g. a bar spanning over the relevant days of the event.
- When clicking on a particular day, it would be great if one could directly add an event (instead of clicking the "Add event" button).

### URL

https://www.home-assistant.io/integrations/local_calendar/

### Version

2022.12.1

**Comment by allenporter** [comment]
Hi, feature requests to the forums and not in GitHub.

However the good news is I am aware of all these things already... One has a pending PR by @spacegaier , one is planned, and one I also noticed and thought about too.
