### ISSUE TITLE
How to add event in the Calendar ?

### ISSUE THREAD

**Issue by jmcollin78** [home-assistant/home-assistant.github.io#25221]
### Feedback

The documentation explains how to create a calendar and it works great. But there is no information on how to insert event on the Calendar and I cannot found any information on this.

Any help would be greatly appreciated.

### URL

https://www.home-assistant.io/integrations/local_calendar/

### Version

2022.12.1

**Comment by allenporter** [comment]
You view calendars with the calendar tab on the right bar, and create an event on the calendar with the add event button:
<img width="1101" alt="Screen Shot 2022-12-09 at 6 05 58 PM" src="https://user-images.githubusercontent.com/6026418/206823571-800317e0-06bf-4e7a-95d5-21b5682dbbec.png">

**Comment by MikelMirror** [comment]
I am agree to this issue.

**Comment by frenck** [comment]
I think this belongs in the documentation of the `calendar` integration, not the `local_calendar` integration as the suggestion in this PR shows.

Reasoning: We don't write how to use a light entity in Home Assistant on each integration documentation page that may produce a light either.

**Comment by allenporter** [comment]
Yes, agreed. I'll move the labels to make it explicit.

(I wasn't honestly really even sure how much I was going to do anything here, given I think the actual issue is just not knowing where to find the calendar at all (the icon in the right bar) which has been there for multiple years. Once you know where that is, adding an event has an easy to find button. So, this applies to all existing calendar integrations (google, caldav, etc))

**Comment by jmcollin78** [comment]
Agree. When you known where it is, it is obvious but when you come in Calendar for the first time it is really not obvious. I made some search, post a question on Hacf (french blog) and no one knowns how to do.

A simple explaination on Calendar and a link in local calendar doc should do the job.

**Comment by allenporter** [comment]
Yes, I totally would welcome someone adding this.

(Just to clarify, I was speaking to my personal priority list)

**Comment by MikelMirror** [comment]
Is there any service similar to google.create_event?

**Comment by allenporter** [comment]
Not yet, but have been thinking about adding it at some point. (I maintain the Google calendar integration too). The APIs are designed to support being able to add that easily.
