### ISSUE TITLE
Short Feedback

### ISSUE THREAD

**Issue by fnx2k** [home-assistant/home-assistant.github.io#25223]
### Feedback

Help page is very useful, however for the installation it should emphase that there are 3 methods of installation.
Not all 3 are to be done.
The succession of chapters is misleading for this aspect.

Some story for the container installation, it should be explained you can use docker command line OR docker-compose
Disturbing for people not familiar with docker.

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

2022.11.2

#### [Install Home Assistant Operating System](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system) 
- [ ]       [Suggested Hardware](https://www.home-assistant.io/installation/raspberrypi#suggested-hardware)
- [ ]         [Write the image to your boot media](https://www.home-assistant.io/installation/raspberrypi#write-the-image-to-your-boot-media)
- [ ]      [Start up your Raspberry Pi](https://www.home-assistant.io/installation/raspberrypi#start-up-your-raspberry-pi)

#### [Install Home Assistant Container](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-container)
- [ ]         [Platform Installation](https://www.home-assistant.io/installation/raspberrypi#platform-installation)
- [ ]         [Restart Home Assistant](https://www.home-assistant.io/installation/raspberrypi#restart-home-assistant)
- [ ]         [Docker Compose](https://www.home-assistant.io/installation/raspberrypi#docker-compose)
               ---> this part is an alternate install, not a set of additionnal commands_

- [ ]         [Exposing Devices](https://www.home-assistant.io/installation/raspberrypi#exposing-devices)
- [ ]         [Optimizations](https://www.home-assistant.io/installation/raspberrypi#optimizations)

#### [Install Home Assistant Core](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core)
 - [ ]        [Install dependencies](https://www.home-assistant.io/installation/raspberrypi#install-dependencies)
- [ ]         [Create an account](https://www.home-assistant.io/installation/raspberrypi#create-an-account)
- [ ]         [Create the virtual environment](https://www.home-assistant.io/installation/raspberrypi#create-the-virtual-environment)

**Comment by dannytsang** [comment]
It does describe this in the top level installation page: https://www.home-assistant.io/installation/

The document has a linear assumption starting with the [Getting Started page](https://www.home-assistant.io/getting-started/) and expects people to go through the pages in order. I think the problem arises when people skip or land on page midway through the getting started pages.

I could be wrong and happy to take any feedback if there is a better way to highlight but striking a balance between repeating things on all the pages.
