### ISSUE TITLE
I don't think the not equal filter is working.

### ISSUE THREAD

**Issue by pauljrich1** [home-assistant/home-assistant.github.io#25226]
### Feedback

I attempted to use the following filter but it doesn't appear to be working.  It still shows values that are equal to 0.  If I change the operator to '=', it does filter for just the zero values.
state_filter:
  - operator: '!='
  - value: '0'

### URL

https://www.home-assistant.io/dashboards/entity-filter/

### Version

2022.12.0

**Comment by frenck** [comment]
Hi there @pauljrich1 👋 

It seems like you want to report an issue with the Home Assistant frontend, however, you have submitted documentation feedback instead. Please report issues with the Home Assistant frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
