### ISSUE TITLE
Exception for Frigate Standalone?

### ISSUE THREAD

**Issue by r3wt** [home-assistant/home-assistant.github.io#25239]
### Feedback

https://docs.frigate.video/installation#home-assistant-supervised

I am running frigate standalone with network attached storage for storing the videos/images from frigate. this is not possible to do with frigate hass add on. I wrote a customer docker compose for managing frigate, it is careful not to have any conflict with supervisor. i am not having any issues with home assistant, other than these annoying messages. Would the fine people of home assistant maintainers consider an exception for frigate? 

### URL

https://www.home-assistant.io/more-info/unsupported/software

### Version

2022.12.1

**Comment by frenck** [comment]
Sorry, the case you are describing us not supported by the Home Assistant Project.

We don’t plan on making exceptions.

../Frenck
