### ISSUE TITLE
Example for set_fan_mode is misleading

### ISSUE THREAD

**Issue by cscashby** [home-assistant/home-assistant.github.io#25235]
### Feedback

Per https://community.home-assistant.io/t/climate-set-fan-mode-automation-help/91242 the fan_mode: parameter is 'low' etc, not 'On Low' as the documentation suggests. A list of supported modes would be prudent here.

### URL

https://www.home-assistant.io/integrations/climate/#service-climateset_fan_mode

**Comment by frenck** [comment]
> Per [community.home-assistant.io/t/climate-set-fan-mode-automation-help/91242](https://community.home-assistant.io/t/climate-set-fan-mode-automation-help/91242) the fan_mode: parameter is 'low' etc, not 'On Low' as the documentation suggests.

That is correct, it is listed as an "example" for that reason.

> A list of supported modes would be prudent here.

We can't. It depends on what your device provides, it isn't a predefined list. If your device has an "On Low" mode, the example will work. If your device would supply an "Turbo wind hurricane"-mode, that would work.

../Frenck
