### ISSUE TITLE
Fronius feedback, feature request: update interval, inverter temperature, string power

### ISSUE THREAD

**Issue by christschnman** [home-assistant/home-assistant.github.io#25249]
### Feedback
Great integration, works well. But: why pv-power stays above zero over night?

Would be great, if the update Interval is adjustable.

Also another feature request would be the temperature of the inverter and the power (voltage and current) from each module string. Iobroker adapter solved this with the archive api, "just" picked the newest value:

http://xxx.xxx.x.x/solar_api/v1/GetArchiveData.cgi?Scope=System&StartDate=11.12.2022&EndDate=12.12.2022&Channel=Current_DC_String_1&Channel=Current_DC_String_2&Channel=Temperature_Powerstage&Channel=Voltage_DC_String_1&Channel=Voltage_DC_String_2

### URL

https://github.com/home-assistant/core/tree/dev/homeassistant/components/fronius

**Comment by farmio** [comment]
Hi 👋! 
Please don't use the issue tracker for feature requests. Especially not the one for the documentation repo - it is very unlikely that it will be seen.
Use the forums instead. See eg. https://community.home-assistant.io/t/add-scan-interval-to-fronius-integration/296872/11
