### ISSUE TITLE
Exception for Debian 11 derivatives, like Ubuntu or Linux Mint?

### ISSUE THREAD

**Issue by r3wt** [home-assistant/home-assistant.github.io#25240]
### Feedback

https://www.home-assistant.io/more-info/unsupported/os

I installed it on linux mint, because i had trouble with debian and ubuntu installations. linux mint worked perfectly fine, so i installed HA on it and have been running it ever since. Since april 2022 i haven't had any issues, other than the unhealthy message from home assistant which is somewhat easily bypassed. 

### URL

https://www.home-assistant.io/more-info/unsupported/os

### Version

2022.12.1

**Comment by frenck** [comment]
There is no exception for derivatives; this had been explicitly not supported by the project.

It had been part of an architectural decision made by the project members and documented in an architectural decision record.

Running Home Assistant Supervised on a derivative of Debian 11, is therefore now supported.


../Frenck
