### ISSUE TITLE
local integration

### ISSUE THREAD

**Issue by willemvanderkraan** [home-assistant/home-assistant.github.io#25255]
### Feedback

In what way can i  connect to my jusnimbus data in my local network? I understand there is an API/MQTT available.
Kind regards Willem van der Kraan

### URL

https://www.home-assistant.io/integrations/justnimbus

**Comment by frenck** [comment]
> In what way can i connect to my jusnimbus data in my local network? 

You can't, see documentation:

![CleanShot 2022-12-12 at 16 44 20](https://user-images.githubusercontent.com/195327/207089073-0e75bd43-bbc5-4c48-8bb8-bf1c290e0cbb.png)

It polls the cloud APIs. The local network isn't used.

../Frenck
