### ISSUE TITLE
It mentions Logger but does not tell you where the logs can be found.

### ISSUE THREAD

**Issue by SkyLined** [home-assistant/home-assistant.github.io#25259]
### Feedback

> Running this script show absolutely no output on the screen, but it logs with level info. You must have the [Logger](https://www.home-assistant.io/integrations/logger/) enabled at least for level info.
> 
> Your confiuration.yaml should include something like this.
> ```
> logger:
>   default: info
> ```
The above should inform the user where the logs can be found, so they can see that it is working as intended.

### URL

https://www.home-assistant.io/integrations/python_script/

### Version

N/A

**Comment by dannytsang** [comment]
The location of the log is mentioned in the logger integration page: https://www.home-assistant.io/integrations/logger/#viewing-logs

There is a link to the logger integration in the *Note* section so I believe it strikes a balance between repeating information v.s. referencing information on a different page unless you think there is a reason that's not the case.

**Comment by frenck** [comment]
Thanks for the feedback! I've looked at it as well, the Logger documentation is linked and referenced in the note box on the Python script page.

The logger documentation indeed, as pointed out by Danny, provides all details on the Logger, including the file locations.

I think, for now, the current references are sufficient. If this suggestion pops up more often in the future we can reconsider.

../Frenck

**Comment by SkyLined** [comment]
I disagree. People do not intuitively know that they need to read the Logger documentation to find out where the logs can be found. They also should not have to read through the entire Logger documentation page in order to find out how to read the log (it is literally at the very end of that page!).

I expect most people will scan the page and then search online rather than opening the link to Logger and reading its entire documentation. A single line here explaining where the logs can be found would help.

**Comment by frenck** [comment]
> I disagree. People do not intuitively know that they need to read the Logger documentation

Sorry to hear that, however, this part is showing how to use the logger integration, which is documented in its own specific place. Providing all context to our loggers needed.

It has been linked from this page to point to the right information.

Adding the information on the log file here would be incomplete, and bare bone copies of other pages (duplicate content isn't maintainable).

As per above, we keep it like this for now.

../Frenck

**Comment by SkyLined** [comment]
> this part is showing how to use the logger integration

Strictly speaking, it only tells you that you have to turn it on and how to do that:

> You must have the [Logger](https://www.home-assistant.io/integrations/logger/) enabled at least for level `info`.

It does not tell you where the logs are, how to use Logger, or that you need to read the Logger docs to find out that the logs are in a file and not accessible through the UI. Sure, most people will figure that out, but would it not be much easier for them if the docs include this sentence:

> You cannot read the logs through the UI: these logs are stored in a file. The location of the log file can be found in the Logger documentation [here](https://www.home-assistant.io/integrations/logger/#viewing-logs).

**Comment by frenck** [comment]
Sorry, but I'm at the point I am at a point I'm no longer take this seriously. Let me point out why:

![CleanShot 2023-01-10 at 17 50 43](https://user-images.githubusercontent.com/195327/211613087-8cea9517-f411-4bb1-bc14-ede139f10a8a.png)

It is listed on the relevant python script page, is in an alert box to put extra emphasis on the matter, and the logger integration is linked and noted as being a prerequisite. It **must** be enabled and configured for at least the `info` log level. The linked page (in this quite of a big note box) provides all data on the logger one would ever need.

../Frenck

**Comment by SkyLined** [comment]
Yes, you have made it quite clear that you expect that link to explain everything because if people follow it and read the entire page, they have all the information they need. I am not disputing that.

My point is that most of the info on the Logger documentation is irrelevant to the task at hand (which is to enable logs for scripts and read those logs). There is no index at the top to quickly find the relevant information, and it is at the very end of the page. Having to read the entire doc on Logger simply to find out where the logs are is a waste of time.

I am suggesting that we add one or two sentences to the page to explain not just how to enable the log but also how to read them, since that is what most people will want to do anyway.

**Comment by frenck** [comment]
> My point is that most of the info on the Logger documentation is irrelevant to the task at hand

> Having to read the entire doc on Logger simply to find out where the logs are is a waste of time.

It isn't as it needs to be set up. Please note documentation is here for reading, not for those not willing to read them.

**Comment by SkyLined** [comment]
In that case I think the documentation should read:
> You must set up [Logger](https://www.home-assistant.io/integrations/logger/) and enable at least level `info`. The documentation explains how to do this and where you can find the logs once you've set it up.

However, adding the lines to `configuration.yaml` as explained seems to be enough to set it up. I was only interested in finding a way to write some output from my script for debugging. I am pretty sure I did not read the entire Logger documentation or go through any additional setup process in order to get that working.

**Comment by frenck** [comment]
OK, well, read that page.

Going to end this discussion here.

Thanks 👍 

../Frenck
