### ISSUE TITLE
confusing terminology for MQTT discovery

### ISSUE THREAD

**Issue by yann1420** [home-assistant/home-assistant.github.io#25252]
### Feedback

On page https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery there is this section 

`"Platforms supported by MQTT discovery"`   which is a list of items MQTT will recognize. 
A couple of lines below there is this example

 `<discovery_prefix>/<component>/[<node_id>/]<object_id>/config`

And the explanation of the line `<component>: One of the supported MQTT components, eg. binary_sensor.`
I do interpret this as the concept `component` is the same as the concept `platform` .
If I am correct I would like to propose to use the terminology that is most applicable but at least unambiguous. 

### URL

https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery

### Version

2022.12.1

**Comment by jbouwh** [comment]
You are right that the term `component` and `platform` is not use consistently. Sometimes `component` is used, sometime platform, while same is meant.

**Comment by yann1420** [comment]
It would be good for me ( and as I assume for many others) if there would a list of these concepts in HA and how they relate to one another. Thinking of devices, add-on, ( versus ) integration , lovelace, frontend , etc . Let me know if I can help.
