### ISSUE TITLE
Mobile number instead of email for integration with TUYA

### ISSUE THREAD

**Issue by PZSW** [home-assistant/home-assistant.github.io#25268]
### Feedback

Note that TUYA allows users to login on the TUYA SMART app with their mobile phone number.
(in addition to email and federated login from Google).

Users may get a permission deny warning if they use the email instead of the required mobile number (account number in the mobile app). 

Perhaps this can be mentioned. 

### URL

https://www.home-assistant.io/integrations/tuya/#1106-permission-deny

**Comment by frenck** [comment]
Unfortunately, it ain't simple. Most people will just be able to login with their phone number, account ID (which may differ from the mobile number), username, and/or email. Nor is there a recommendation or generic solution or order of things.

You should be able to log in with the same credentials as you use with the app. If that is not possible, please contact Tuya for this specific occurrence.

../Frenck
