### ISSUE TITLE
No coding examples

### ISSUE THREAD

**Issue by TRusselo** [home-assistant/home-assistant.github.io#25265]
### Feedback

send command? ok. HOW?
you give a list of commands, a way to get a list of commands for your TV,
but no examples of how to use them.

you show
![image](https://user-images.githubusercontent.com/1154815/207232005-b5766b2c-89ea-4192-8ef0-4fafd9e2dba1.png)

i get
![image](https://user-images.githubusercontent.com/1154815/207231676-ccab4452-ddf5-431e-b208-ecaad2d115b4.png)

i'm guessing add the following?

data: down, down, ok, exit

who knows....

### URL

https://www.home-assistant.io/integrations/braviatv/

### Version

2022.12.3

**Comment by Drafteed** [comment]
Hello to you, too!

Docs says quite clearly that you need to use a standard service `remote.send_command`:

<img width="500" src="https://user-images.githubusercontent.com/11841379/207235258-e43d43e3-e764-48c4-a6bd-fcd9a19ed245.png">

See [using service calls](https://www.home-assistant.io/docs/scripts/service-calls/).

**Also make sure you are using [native core integration](https://www.home-assistant.io/integrations/braviatv/) and [not a custom one](https://github.com/custom-components/media_player.braviatv_psk).**

**Comment by Drafteed** [comment]
@home-assistant close
