### ISSUE TITLE
Scrape: Forced to stop using yaml file: Cannot change Scan interval

### ISSUE THREAD

**Issue by trvrcr** [home-assistant/home-assistant.github.io#25269]
### Feedback

in Yaml you could put: scan_interval: 86400 to only scan the website once a day.
In the integration you cannot do this,
Therefore you congest a website you scrape from without need.

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2022.12.0

**Comment by frenck** [comment]
Hi there @trvrcr 👋 

It seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
