### ISSUE TITLE
CREATE THE VIRTUAL ENVIRONMENT on a Raspberry pi missing and incorrect steps

### ISSUE THREAD

**Issue by trentjw** [home-assistant/home-assistant.github.io#25261]
### Feedback

Missing important steps to successfully install Home assistant on a Raspberry pi and clumping some steps make it try to install off path. suggest updated instructions unless the goal is to have people fail at installing via Venv  link to steps [https://community.home-assistant.io/t/installing-home-assistant-on-raspberry-pi-with-touchscreen-kiosk-mode/501957](url)

```
sudo apt update

sudo apt upgrade -y

sudo apt autoremove -y

```
" INSTALL DEPENDENCIES."

```
sudo apt-get install python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 -y libturbojpeg0 tzdata

```

```

sudo apt install libbluetooth-dev -y

```
```

sudo pip3 install PyBluez

```
"STEPS BELOW INSTALLS HOME ASSISTANT."

```
sudo useradd -rm homeassistant -G dialout,gpio,i2c

sudo mkdir /srv/homeassistant

sudo chown homeassistant:homeassistant /srv/homeassistant

```
```
sudo -u homeassistant -H -s

```
```
cd /srv/homeassistant

```
```
curl https://sh.rustup.rs -sSf | sh

```
"WAIT FOR PROMPT PRESS 1 WHEN ASKED AT THE PROMPT"
```
source "$HOME/.cargo/env"
```

"COPY AND PASTE THE VERSION OF PYTHON YOU UPDATED TO BY CHANGING THE NUMBER BEFORE PRESSING ENTER ON BELOW COPY."
```
version=3.10
```
```
python$version -m venv .

```
```
python3 -m pip install wheel

```
```
source bin/activate

```
```
pip3 install homeassistant

```

### URL

https://www.home-assistant.io/installation/raspberrypi

### Additional information

```
sudo apt update

sudo apt upgrade -y

sudo apt autoremove -y

```
" INSTALL DEPENDENCIES."

```
sudo apt-get install python3 python3-dev python3-venv python3-pip libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 -y libturbojpeg0 tzdata

```

```

sudo apt install libbluetooth-dev -y

```
```

sudo pip3 install PyBluez

```
"STEPS BELOW INSTALLS HOME ASSISTANT."

```
sudo useradd -rm homeassistant -G dialout,gpio,i2c

sudo mkdir /srv/homeassistant

sudo chown homeassistant:homeassistant /srv/homeassistant

```
```
sudo -u homeassistant -H -s

```
```
cd /srv/homeassistant

```
```
curl https://sh.rustup.rs -sSf | sh

```
"WAIT FOR PROMPT PRESS 1 WHEN ASKED AT THE PROMPT"
```
source "$HOME/.cargo/env"
```

"COPY AND PASTE THE VERSION OF PYTHON YOU UPDATED TO BY CHANGING THE NUMBER BEFORE PRESSING ENTER ON BELOW COPY."
```
version=3.10
```
```
python$version -m venv .

```
```
python3 -m pip install wheel

```
```
source bin/activate

```
```
pip3 install homeassistant

```

**Comment by frenck** [comment]
The installation steps provided are providing a lot specific that are for your environment/system (for example, installing rust). This will not apply to everybody. It depends on your architecture, distribution of choice, used Python installation and versions, used Python package indexes, and many more.

As noted on the top of the instructions for this installation method:

<img width="685" alt="CleanShot 2022-12-13 at 00 01 02@2x" src="https://user-images.githubusercontent.com/195327/207174655-004013e9-583e-42cc-88e9-c27edcb8a1de.png">

../Frenck

**Comment by trentjw** [comment]
It straight up will not install on a base raspberry pi setup without rust
installed first and it dumps it in the wrong directory because this is clumped 

sudo -u homeassistant -H -s
cd /srv/homeassistant


run of the mill pi4 with stock unaltered PI image following your instructions fails every time 

 try it yourself  the step by step on your site

**Comment by frenck** [comment]
These venv instructions are generic and applied to any generic setup, regardless of the image used. Armbian, Debian, Raspberry Pi OS, or any other flavor, irrespective of the source of the Python interpreter (from a package manager, manual install, pyenv, etc).

There is no way there is a single instruction possible that covers all cases. The general basic gist is written out here.

As said and warned, this is an advanced installation method, and we expect you to know how to adopt it for your environment. If not, we recommend looking into a different installation method.

Thanks 👍

../Frenck

**Comment by trentjw** [comment]
I understand that and have used this method for a long time and the raspberry core part instructions used to work like it should till around 2022.7 then it was broken, I guess I figured since it was directly name raspberry pi core venv that it had all the needed steps to install it on a stock unaltered image for the raspberry pi since that what it use to do, my mistake on thinking what use to work should still work like that, no worries I built a proper tutorial on installing home assistant core on a stock raspberry Pi that works as it should. Just thought you might want to update your tutorial to the current method I won't make that mistake again have a good one
