### ISSUE TITLE
.one dns record not updated

### ISSUE THREAD

**Issue by jaccodominicus** [home-assistant/home-assistant.github.io#25275]
### Feedback

Hello, I am a noob regarding home assistant config. Started recently.
I have a .one domain registration.
When the cloudflare plug-in is setup first is creates the configured hostname in the .one zone of my registered domain.
When the plug-in restarts or home assistent is restarted it states in the logging that the record cannot be created because it already exists.
What am I doing wrong or didn’t configure correctly ?

Edit
Forgot to mention, i have to delete the record created by the plug-in, restart cloudflare plug-in and than the record is created again.

Kind regards Jacco dominicus

### URL

https://www.home-assistant.io/integrations/cloudflare/

### Version

2022.12.4

**Comment by ludeeus** [comment]
It seems like you are trying to report a bug, if so please do that on https://github.com/home-assistant/core, this repository is strictly for the documentation.
