### ISSUE TITLE
August docs, incorrectly lists Yale Dorman L3 as not supported

### ISSUE THREAD

**Issue by Kilill** [home-assistant/home-assistant.github.io#25272]
### Feedback

The Yale Dorman L3 is, according to docs, supposedly not supported.
But i have one since at least 6 month, and i works wonderfully with HA.

### URL

https://www.home-assistant.io/integrations/august#known-unsupported-devices

**Comment by bdraco** [comment]
It's not supported because the devs don't have access to one to validate changes.  It may work but other users have reported issues so we can't mark it as supported.

**Comment by Kilill** [comment]
Maybe just put that there as a comment ?

**Comment by SrOne** [comment]
I have use it also over six months. Working great,  Only doorbell sensor is missing.

**Comment by bdraco** [comment]
If someone knowledgable on the topic wants to sign up to be codeowner for the integration and maintain support for the device, we could add it to the docs.

**Comment by bdraco** [comment]
https://github.com/home-assistant/architecture/blob/master/adr/0008-code-owners.md#rules
