### ISSUE TITLE
Not working with tplink Archer MR600

### ISSUE THREAD

**Issue by htitze** [home-assistant/home-assistant.github.io#25297]
### Feedback

This integration is not working with Tp-Link Archer MR600 LTE Router.

### URL

https://www.home-assistant.io/integrations/tplink_lte

**Comment by frenck** [comment]
Hi there @htitze 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
