### ISSUE TITLE
Add extra installation instructions for installing on TrueNAS and TrueNAS Scale as virtual machines. 

### ISSUE THREAD

**Issue by chrisbie77** [home-assistant/home-assistant.github.io#25294]
### Feedback

Home Assistant can be installed and run perfectly on both TrueNAS, based on FreeBSD, and the newer Linux based TrueNAS Scale as a full virtual machine image, without the limitations of the Docker image, but there are no instructions for it yet in the documentation. 

 It just  needs some extra steps on both to convert the virtual disk image from qcow2 format to a raw image and then write it to the zvol allocated to the HA virtual machine as its boot disk image, or, in the case of TrueNAS Scale, to add the raw disk image as a raw file disk device when configuring the VM in the TrueNAS web interface. They both still require the disk image to be a ZFS zvol, and don't (yet) accept a disk image directly as a file. 

 These could be added in the "alternative" option for installations  [in the documentation](https://www.home-assistant.io/installation/alternative) (?).

After creating the virtual machine for Home Assistant in the TrueNAS web interface: 

For TrueNAS (FreeBSD based)  - the steps are:

Download the qcow2 image, then convert it to a raw image with qemu, from the TrueNAS shell ->  

`qemu-img convert -f qcow2 -O raw hass_image.qcow2 hass_image.raw`

Then write it to the vm's zvol, has to be created first, from the gui or cli on the TrueNAS host. 

`dd if=hass_image.raw of=/mnt/pool/vm_zvol bs=1m`

For TrueNAS Scale (Linux based) - the steps are: 

Download the qcow2 image and convert it, as above - >

`qemu-img convert -f qcow2 -O raw hass_image.qcow2 hass_image.raw`

Copy or move it to a dataset in the ZFS pool you are using to store VM disk images. 
Then, add the  raw image to the VM as a "raw file" device in the VM configuration dialog in the TrueNAS Scale web interface. 

You can then start the virtual machine and connect to the Home Assistant web interface to begin setup as normal. 

### URL

https://www.home-assistant.io/installation/alternative

### Additional information

Information originally from [this forum post at the TrueNas forums](https://www.truenas.com/community/threads/vm-add-existing-disk.98140/)

**Comment by tprelog** [comment]
I've used slightly different steps the with the same end result on TrueNAS SCALE (Linux version)

First create a zvol at least 32 GiB using the TrueNAS UI and take note of the zvol path.

Then from the TrueNAS shell run the following commands

- replace `nvme/vm/home-assistant-os` with your own

```bash
wget https://github.com/home-assistant/operating-system/releases/download/9.4/haos_ova-9.4.qcow2.xz
unxz haos_ova-9.4.qcow2.xz
qemu-img convert -O raw haos_ova-9.4.qcow2 /dev/zvol/nvme/vm/home-assistant-os
```

When creating the VM in TrueNAS,  use existing disk image and select the HAOS ZVOL you created

Maybe an updated community wiki guide would be a better option? - Then we might also cover more TrueNAS related topics as well, such as setting up a bridge so your VM can connect to TrueNAS (I also needed a bridge to get multicast working correctly) or setting up recurring snapshots of the zvol. Basically a complete guide to running Home Assistant OS virtualized on TrueNAS - Not just an installation guide

**Comment by tprelog** [comment]
FWIW - I started a community guide

https://community.home-assistant.io/t/wip-installing-haos-in-a-vm-on-truenas-scale-bluefin-edition/511393?u=troy

**Comment by frenck** [comment]
Hi there @chrisbie77 👋 

We do not include a manual for every possible platform in our documentation deliberately. The platforms currently included in our official documentation have been determined and limited in an architectural decision. The suggested platforms are not part of those.

The community wiki/guides are the right places for other community-driven instructions.

I am going to close the issue on this end for the above reasoning.

Nevertheless, Happy New Year 🥂 

../Frenck
