### ISSUE TITLE
"Add Event" bouton on "Calendar card".

### ISSUE THREAD

**Issue by olivier1091** [home-assistant/home-assistant.github.io#25299]
### Feedback

Bonjour,
When using an HA local calendar, It would be cool to have "Add Event" bouton on "Calendar card".
Best regards and seasons greetings
Olivier

### URL

https://www.home-assistant.io/dashboards/calendar/

### Version

2022.12.6

**Comment by dannytsang** [comment]
This sounds like a feature request. If it is please raise in https://community.home-assistant.io/c/feature-requests/13
