### ISSUE TITLE
oncue integration does not explain polling interval or give guidance

### ISSUE THREAD

**Issue by gdt** [home-assistant/home-assistant.github.io#25300]
### Feedback

The oncue integration page does not explain how often it checks.  From reading the sources, it turns out to be 10 minutes.  That's pretty long for noticing a power failure.    So the docs should say that.   (Maybe it should be configurable, but that's out of scope for this tracker.)

A related question is the relationship of the integration to Kohler, in terms of whether it is using a documented API that people are welcome to use, or a reverse-engineered API, and if polling at 1 minute is likely to be ok or not.   Basically, I see 10m polling as a mild bug, and I wonder if it's a workaround or not.

### URL

https://www.home-assistant.io/integrations/oncue/

### Version

2022.12.6

**Comment by bdraco** [comment]
There is no official api.  If you need faster polling disable automatic polling in the ui and setup an automation. Please don't do it too frequently as you could get yourself banned by the server

**Comment by gdt** [comment]
I realize I could change the code.    Is there evidence that 1min polling leads to bans?   Obviously every 1s would be nuts.  I was suggesting basically to give the reason why 10m was chosen, as faster is better for functionality and slower is better for avoiding the server getting upset and resource usage.    I am proxying this query for a friend, and may help him see how the offiicial app behaves.

I realize some of this comment should perhaps be directed at aiooncue.
Feel free to close if you've decided you don't want to address this.

**Comment by bdraco** [comment]
> Is there evidence that 1min polling leads to bans?

Another user reported being banned at a faster polling interval a few months ago.  Unfortunately they didn't give any information on what the interval was.

**Comment by gdt** [comment]
I would put what is known in the docs, and hope we accumulate wisdom over time.  It's unfortunate that people don't give the obviously-relevant specifics :-(

**Comment by bdraco** [comment]
Here is the link to edit it if you feel up to it
https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/oncue.markdown

**Comment by gdt** [comment]
Thanks.  See https://github.com/home-assistant/home-assistant.io/pull/25301

**Comment by rssalerno** [comment]
The Kohler web app polled the server at 5s intervals when the api was originally reverse-engineered in 2017, lately it's in the 15s range.  I imagine the mobile apps poll at similar rate.  So Kohler will tolerate a 5-15s poll rate for some length of time.  However it's probably not too common that OnCue users stay logged into the website 24/7.   At some point the auth key may time out, which I believe is handled by the integration by requesting a new auth key.

I've played around with a 1m polling interval and it works just fine, although about once a week all generator parameter values go unavailable.  This is fixed by reloading the integration and it's good for another week.  So it seems Kohler will tolerate a 1m interval for an extended length of time.

**Comment by PeteRager** [comment]
>  although about once a week all generator parameter values go unavailable. This is fixed by reloading the integration and it's good for another week. So it seems Kohler will tolerate a 1m interval for an extended length of time.

Are there errors logged when this happens?

**Comment by rssalerno** [comment]
To change polling rate I copied the source into /config/custom_components/oncue/ and modified __init__.py by changing update_interval=timedelta(minutes=10) to update_interval=timedelta(minutes=1).  When it goes unavailable the logs show this:

```
2022-12-18 21:51:21.114 ERROR (MainThread) [custom_components.oncue] Unexpected error fetching Oncue my_username data: Invalid username specified (1202)
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 162, in async_fetch_all
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 198, in async_list_devices_with_params
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 144, in _get_authenticated
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 156, in async_login
aiooncue.LoginFailedException: Invalid username specified (1202)
2022-12-18 21:52:21.001 ERROR (MainThread) [custom_components.oncue] Unexpected error fetching Oncue my_username data: Invalid username specified (1202)
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 162, in async_fetch_all
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 198, in async_list_devices_with_params
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 138, in _get_authenticated
aiooncue.LoginFailedException: Invalid username specified (1202)
2022-12-18 21:53:21.002 ERROR (MainThread) [custom_components.oncue] Unexpected error fetching Oncue my_username data: Invalid username specified (1202)
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 162, in async_fetch_all
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 198, in async_list_devices_with_params
File "/usr/local/lib/python3.10/site-packages/aiooncue/__init__.py", line 138, in _get_authenticated
aiooncue.LoginFailedException: Invalid username specified (1202)
```

**Comment by PeteRager** [comment]
I get the exact same error periodically,   I believe the fix is to close the session and recreate.  I will create a separate issue to track this.  For me if happens about once a month. Is your copied source up to date?

Regarding faster polling, you can do that without changing the source 

```

- id: generator slow poll
  alias: generator slow poll
  description: ""
  trigger:
    - platform: time_pattern
      minutes: "/10"
  action:
    - service: homeassistant.update_entity
      data: {}
      target:
        entity_id: sensor.xxxxx_generator_state

```

**Comment by rssalerno** [comment]
My copied source is from August 15, 2022.

In the above example, is the interval still 10 minutes?  So for one minute intervals would I use `minutes: "/1" `?

**Comment by PeteRager** [comment]
> My copied source is from August 15, 2022.
> 
> In the above example, is the interval still 10 minutes? So for one minute intervals would I use `minutes: "/1" `?

Apologies, pasted the wrong example.  Yes /1 would poll at 1 minute.  I have a CT sensor that tells when I’ve lost utility power, so when I’m in an outage I poll the generator /1 otherwise /10.

I was running 2022.8.6 up until a few days ago.   Sounds like you are on a similar version.  I wanted to see if I still get this error on 2022.12.6 before opening an issue.
