### ISSUE TITLE
Found a known issue with shelly devices

### ISSUE THREAD

**Issue by epiecs** [home-assistant/home-assistant.github.io#25307]
### Feedback

Hi,

My current stack:
- Home assistant in a proxmox vm, vlan 60
- Shelly iot devices in vlan 180
- Unifi AP/Switch/Router

I recently migrated from esxi to proxmox. When restoring a backup everything worked fine except for all my Shelly devices. When searching online it seems that I am not the only one experiencing this problem:

https://community.home-assistant.io/t/shelly-unavailable/471833
https://community.home-assistant.io/t/shelly-integration/227781/31

The last thread put me in the right direction on how to fix this. I just had to enable IGMP snooping.

Maybe this could be a good addendum to the integration page under "known issues"?

### URL

https://www.home-assistant.io/integrations/shelly/

### Additional information

![image](https://user-images.githubusercontent.com/124507/208067077-14b9ea8d-6401-4f69-95f4-ffee82e844a8.png)

**Comment by frenck** [comment]
Network setups like you are using there, are something we consider an advanced use case.
IGMP snooping is not just for Shelly, but for many more things (and you probably will need even more than just IGMP snooping when doing multiple VLANs like that).

We consider that users making such setups have knowledge of advanced networking. We, therefore, do not document these on purpose. Besides many permutations and setups being possible, it also doesn't apply to 99% of our user base, and adding such documentation more often causes more confusion.

Nevertheless, thanks for your feedback 👍 

../Frenck

**Comment by thecode** [comment]
If you follow the [documentation](https://www.home-assistant.io/integrations/shelly/#shelly-device-configuration-generation-1) and setup unicast you don't need IGMP snooping.

**Comment by epiecs** [comment]
Hi,

I tried this already but this unfortunately did not fix my issue.

Kr, Gregory
