### ISSUE TITLE
Open uv automation docs

### ISSUE THREAD

**Issue by StDannyDan** [home-assistant/home-assistant.github.io#25302]
### Feedback

In Examples of Updating Data, automation scripts use some sensor.LATITUDE_LONGITUDE_current_uv_index, and that doesn't work.

### URL

https://www.home-assistant.io/integrations/openuv/

**Comment by bachya** [comment]
Those are not literal entity names; you need to determine the correct entity name in your installation.

If you find changes to the docs that could help, a PR is welcome.

**Comment by filikun** [comment]
@StDannyDan You can find what your entities names are by going to the integration panel, find your OpenUV and click on the entities link. 

![image](https://user-images.githubusercontent.com/9947929/213141289-7bebbfc6-010d-45f5-b250-c5d24cac4bc7.png)

**Comment by frenck** [comment]
Going to close this issue. All entity IDs in all of Home Assistant documentation as examples. Just like names, they can be changed, customized, or differ from examples. You'd need to adopt them to your use case.

../Frenck
