### ISSUE TITLE
BSH Wall Thermostate II

### ISSUE THREAD

**Issue by gejomo** [home-assistant/home-assistant.github.io#25316]
### Feedback

Today I‘ve received my new BSH wall thermostat II and I miss the integration into HomeAssistent.

### URL

Www.home-Assistent.io

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
