### ISSUE TITLE
Why do you do this?

### ISSUE THREAD

**Issue by bhoyle** [home-assistant/home-assistant.github.io#25317]
### Feedback

I ordered this lock and could not get it to pair. Then I find the details on your page and it shows ZERO integrations. Why do you keep a product on the integrations list that no one has ever been able to successfully pair? You even state on there it is fully functional! I love HA and I'm an expert at it, but you have to quit letting trash products attach themselves to you until they are ready to fly. So damn frustrating.

### URL

https://www.home-assistant.io/integrations/ultraloq/

**Comment by frenck** [comment]
> Then I find the details on your page and it shows ZERO integrations. 

That is actually a bug in our documentation. In this case, it uses the Z-Wave integration and does not have its own integration usage; hence it showing 0. I'll ensure that gets addressed in our documentation codebase.

> Why do you keep a product on the integrations list that no one has ever been able to pair successfully?

You can pair them using Z-Wave in Home Assistant; these specific devices have been provided by Ultraloq to the Home Assistant team and tested. If you have issues using a device with an Home Assistant integration, please open up an issue here:

<https://github.com/home-assistant/core/issues>

The above link is to our main Core issue tracker.

../Frenck

**Comment by bhoyle** [comment]
Very impressed with the response. Thank you! I sent it back because I could
not get it to pair. Thanks for the response and sorry for the vent. HA is
awesome.

**Comment by frenck** [comment]
No problem! I understand the frustration it can bring.

Happy Holidays 🎄 

../Frenck
