### ISSUE TITLE
Problem with proxy configuration

### ISSUE THREAD

**Issue by jjindrich** [home-assistant/home-assistant.github.io#25312]
### Feedback

I'm using reverse proxy which sends IP and port.
Based on this link https://www.home-assistant.io/integrations/http/ I configured use_x_forwarded_for: true and listed trusted_proxies.
But still getting this error:
2022-12-16 13:32:24.008 ERROR (MainThread) [homeassistant.components.http.forwarded] Invalid IP address in X-Forwarded-For: (my_ip):52383

Please how to modify trusted_proxies ?

### URL

https://www.home-assistant.io/integrations/http/

**Comment by dannytsang** [comment]
are you able to post snappit of your configuration.yaml with the ```http``` section?

**Comment by jjindrich** [comment]
There is my config

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.10.0/24

I cannot add there something like (my_ip):52383 becasuse is not valid format.

**Comment by dannytsang** [comment]
Try adding the IP address with the port e.g. 
`trusted_proxies:
  - 192.168.10.2`

**Comment by dannytsang** [comment]
Try adding the IP address with the port e.g. 
```
trusted_proxies:
  - 192.168.10.2
```

**Comment by jjindrich** [comment]
This is I did it exactly. But still getting error message.

**Comment by frenck** [comment]
The issue is a misconfigured / bad proxy.

> 2022-12-16 13:32:24.008 ERROR (MainThread) [homeassistant.components.http.forwarded] Invalid IP address in X-Forwarded-For: (my_ip):52383

The port should not be part of the `X-Forwarded-For` header. Hence it raises it got something it didn't expect. This is not a Home Assistant Core or Documentation issue.

Ref: <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For>

../Frenck
