### ISSUE TITLE
Docker option not obvious

### ISSUE THREAD

**Issue by damobrisbane** [home-assistant/home-assistant.github.io#25328]
### Feedback

After clicking into this page, it is not obvious there is a docker option. It presents as legacy software, vmdk, virtualbox, kvm. Right menu not first choice. The two headings (Operating System, Docker) should precede the first section.

### URL

https://www.home-assistant.io/installation/linux#install-home-assistant-container

### Version

latest

**Comment by hanscees** [comment]
I very much agree. and the graphic showing container where core iscrossed out is outright mysterious.
