### ISSUE TITLE
default_config page...

### ISSUE THREAD

**Issue by greyhound3** [home-assistant/home-assistant.github.io#25322]
### Feedback

...lists "stream:" as a part of the default config, although it doesn't seem to be in the list:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/default_config/manifest.json

I have got the feeling that it should either be removed from the documentation page or added in the manifest.json , but what do I know? :)

### URL

https://www.home-assistant.io/integrations/default_config

**Comment by frenck** [comment]
> ...lists "stream:" as a part of the default config, although it doesn't seem to be in the list:

Not all are loaded via the manifest, `stream` is loaded programmatically:

See: <https://github.com/home-assistant/core/blob/292294fb96f90fc7d99af81a23f28cb925c0a973/homeassistant/components/default_config/__init__.py#L24>

The current documentation is thus correct.

../Frenck
