### ISSUE TITLE
Shelly Door Window 2 manual config needed to work with HA

### ISSUE THREAD

**Issue by AnthonyBe** [home-assistant/home-assistant.github.io#25321]
### Feedback

Please see this thread - https://community.home-assistant.io/t/shelly-door-window-2-not-changing-status/503374/5

The Shelly Door Window 2 sensor, while detected by the Shelly integration, needs additional manual configuration which is not listed in the integration documentation for the device and entities to exist.

Specifically;
1. Open web browser and connect to the Shelly Door Window 2 sensor
2. Go to Internet & Security → Advanced-Developer Settings → check Enable CoIoT
3. Enter the IP address of your HA and port 5683 (for example: 192.168.10.5:5683)
4. Save and Reboot device

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2022.12.6

**Comment by bieniu** [comment]
There is information about CoIoT configuration in the documentation:

![image](https://user-images.githubusercontent.com/478555/208239909-b1fca4f9-c8df-4755-9132-4199c811621d.png)
