### ISSUE TITLE
How can I add an action using the ARCAM integration?

### ISSUE THREAD

**Issue by ghilainm** [home-assistant/home-assistant.github.io#25337]
### Feedback

Currently, there is no action listed in the possible action on my ARCAM. I am wondering why it is not supported as there seems to be everything needed in the control dashboard.

Sorry, if it was not the right place to ask this :). Quite new to the project!

### URL

https://www.home-assistant.io/integrations/arcam_fmj/

### Additional information

![image](https://user-images.githubusercontent.com/661772/208304182-1e2c4528-0b6d-411f-8fd6-daa197db3e6e.png)

**Comment by elupus** [comment]
This is not specific to arcam. Seems no actions are defined for media players in general.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
