### ISSUE TITLE
Map resets itself

### ISSUE THREAD

**Issue by Bart-van-Gorp** [home-assistant/home-assistant.github.io#25335]
### Feedback

Hi,

I'm trying to get some flight data of my location in my dashboard. But somehow the map resets itself when I go to another dashboard. The location is not on the same location when I go back to the dashboard with the site.

### URL

https://globe.adsbexchange.com/?icao=405457

**Comment by frenck** [comment]
Hi there @Bart-van-Gorp 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
