### ISSUE TITLE
Doesnt work with current version of Zabbix and its worth noting that the Zabbix server address defaults to port 80 (443 for ssl)

### ISSUE THREAD

**Issue by ripnetuk** [home-assistant/home-assistant.github.io#25333]
### Feedback

Hi,
First issue, its not documented that this plugin will default to hitting port 80/443 (not 10541) for the zabbix server API (it assumes it behind a proxy I guess). This caused a lot of head scratching.

Secondly, once thats sorted out, it doesnt work with current versions of Zabbix - ZAbbix server returns an error about missing headers, which a quick google implies is caused by using the old API.

### URL

https://www.home-assistant.io/integrations/zabbix/

### Version

latest

**Comment by incama** [comment]
Second this. Using Zabbix 6.4 beta5.

**Comment by frenck** [comment]
Hi there 👋 

It seems like you want to report an issue with an integration. If an integration isn't working as expected with e.g., newer versions, please make sure to raise an issue instead:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
