### ISSUE TITLE
Link on https://home-assistant.io/docs/ecosystem/notebooks/graph/ not working but is correct

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/home-assistant.github.io#2533]
When I click on the link for the jupyter notebook on on [https://home-assistant.io/docs/ecosystem/notebooks/graph/](https://home-assistant.io/docs/ecosystem/notebooks/graph/) I get a 404 Not found. However following the link via Github source is successful. 

Other links (e.g. on [https://home-assistant.io/docs/ecosystem/notebooks/stats/](https://home-assistant.io/docs/ecosystem/notebooks/stats/)) ARE successful

**Comment by fabaff** [comment]
Thanks
