### ISSUE TITLE
Raspberry Pi link to Amazon leads to 3x prices

### ISSUE THREAD

**Issue by RememberTilman** [home-assistant/home-assistant.github.io#25338]
### Feedback

Amazon is not an approved reseller of Raspberry Pi, and the price on the link is 3x the approved price. 
MicroCenter price is $55, this Amazon price is $177
You should also note the supply chain issue which is causing this (expected to resolve shortly). 

### URL

https://www.home-assistant.io/installation/raspberrypi/

**Comment by frenck** [comment]
Thanks for the feedback; unfortunately, there is indeed a supply chain issue. This is not just a Raspberry PI issue, it applies to tons of electronics. It is not our place or goal to report on that.

Nevertheless, thanks for your feedback 👍 

Happy Holidays! 🎄 

../Frenck
