### ISSUE TITLE
Dont get compressor usage stats and missing power mode

### ISSUE THREAD

**Issue by PrimaryInc** [home-assistant/home-assistant.github.io#25345]
### Feedback

Hi,

Thanks for a awesome plugin. I've been using with successfully to control my  Synergi R-32+ 7,2 kW.
One thing that I dont get stats on is the compressor usage (Watts), total consumption seems to be there (Kwh).
Not sure if it is something in my setup, I've only installed plugin and configured it. No yaml file edits.

Plugin is also missing power mode, that put fan in high level for a period of time. Only applicable for some models i believe.
I used to use HomeSeer that had this function.

All devices se pic bellow.

![Screenshot 2022-12-19 at 08 34 21](https://user-images.githubusercontent.com/45151934/208371796-3c54a601-330f-4062-a46c-4512213ba4ef.png)

### URL

https://homeassistant/lovelace

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by PrimaryInc** [comment]
Sure, I looked at missing consumption as an issue. But anyways :)
