### ISSUE TITLE
Tilt pro

### ISSUE THREAD

**Issue by topherslater** [home-assistant/home-assistant.github.io#25355]
### Feedback

The tilt pro might have an additional decimal place of  accuracy. I don't have a normal one to comparer. It would be nice if it would recognize pro or not and move the decimal accordingly 

### URL

https://www.home-assistant.io/integrations/tilt_ble

### Version

Home Assistant 2022.12.7

**Comment by apt-itude** [comment]
Hi @topherslater, thanks for the request. Is your Tilt Pro being recognized by the integration, but not showing the correct value? I don't have one myself to test with, and I'm not sure if the data format or device IDs are different.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by topherslater** [comment]
Since @apt-itude replied here. I will reply.
the pro is being recognized by the integration but it offers one more decimal point of accuracy compared to the base model tilt. (1.0345 not 1.35) causing it to show up in the integration as 10.345 and the temperature to show up as 690.5 not 69.05[ I used a template](https://www.home-assistant.io/integrations/template) to compensate on my HA, but it would be nice to have it detect a pro and shift the decimal. 
<img width="552" alt="Screenshot 2022-12-29 at 8 46 29 AM" src="https://user-images.githubusercontent.com/29428861/209962503-9e84fb34-854f-4c3b-8339-8a480f2377b9.png">
