### ISSUE TITLE
Cool card, how can I create different lists?

### ISSUE THREAD

**Issue by ferdinandSoethe** [home-assistant/home-assistant.github.io#25352]
### Feedback

I love this card. But we have a few more lists to run the familiy and I'd like to understand how to create more than one list.

Regards,
Ferdinand

### URL

https://www.home-assistant.io/dashboards/shopping-list/

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
