### ISSUE TITLE
Control4 integration broken in recent HASS revs?

### ISSUE THREAD

**Issue by k1n6b0b** [home-assistant/home-assistant.github.io#25357]
### Feedback

My Control4 integration appears to have stopped working.

I see reference (closed/no answer) here: https://github.com/home-assistant/home-assistant.io/issues/22392

Device info
EA5
by Control4
Firmware: 3.3.1.639488-res

I'm able to discover, and add the 'device', but no lights/etc entities populate any more.

There's this as an alternative, but its much older and manual https://github.com/itsfrosty/control4-2way-web-driver

### URL

https://www.home-assistant.io/integrations/control4/

### Version

2022.12.7

**Comment by frenck** [comment]
Hi there @k1n6b0b 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
