### ISSUE TITLE
instructions not updated

### ISSUE THREAD

**Issue by dannyb78** [home-assistant/home-assistant.github.io#25360]
### Feedback

Instructions ar not updated as suggested settings are not avalaible where described:
no local or remote address can be set via settings->system->network menu
![Immagine 2022-12-20 090538](https://user-images.githubusercontent.com/7735128/208615193-e07c5a14-a2da-4e3f-af06-4f6dce571de2.png)

### URL

https://www.home-assistant.io/more-info/no-url-available/

### Version

2022.12.7

**Comment by frenck** [comment]
From the docs:

> Please note, you’ll need to enable advanced mode in your user profile in order to set this up.

Judging by your screenshot, haven't done that. 😉 

Happy Holidays! 🎄 

../Frenck

**Comment by dannyb78** [comment]
thank you, that solved
