### ISSUE TITLE
Missing package information 17track

### ISSUE THREAD

**Issue by Hadatko** [home-assistant/home-assistant.github.io#25368]
### Feedback

My package info looks like: 
 ```json
{'friendly_name': None, 'info_text': 'Receipt of data about consignment before posting.', 'timestamp': datetime.datetime(2022, 12, 17, 23, 0, tzinfo=<UTC>), 'status': 'In Transit', 'location': '', 'tracking_number': 'LF8563095805F'}
```
![image](https://user-images.githubusercontent.com/13130700/208709459-910845ea-fd7f-415b-9147-1cd7751f2aab.png)

it looks like i am missing some attributes like package_type

### URL

https://www.home-assistant.io/integrations/seventeentrack/

### Version

2022.12.x

**Comment by Hadatko** [comment]
I would expect UNKNOWN/None for attributes which will be set later.

**Comment by frenck** [comment]
Hi there @Hadatko 👋 

It seems like you want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by Hadatko** [comment]
Depends on if it is issue in documentation or implementation :D ok i will rise ticket to core
