### ISSUE TITLE
Workday Binary Sensor

### ISSUE THREAD

**Issue by MikeMcGlinch** [home-assistant/home-assistant.github.io#25379]
### Feedback

The description does not indicate whether the "holidays" module is pre-installed, or do we have to custom install it from the Python?
(Using HAOS Core Supervised and not Python), or what about Docker container handling of this issue?

Perhaps indicate that "holidays" module is pre-installed, or confirm that it does need to be installed as well as the configuration shown.

### URL

https://www.home-assistant.io/integrations/workday/#configuration

### Additional information

// Workday is at the top of the page.

**Comment by frenck** [comment]
> The description does not indicate whether the "holidays" module is pre-installed, or do we have to custom install it from the Python?

Home Assistant always manages dependencies; you don't need to install packages manually.

../Frenck
