### ISSUE TITLE
Ability to organize automations

### ISSUE THREAD

**Issue by Purplehazezzzz** [home-assistant/home-assistant.github.io#25388]
### Feedback

Would be nice if we have the ability to organize our automations, for example the ability to create folders for different type of automations. (Maybe make it possible to switch on or off all automations in one folder?)

Love the work you put in to this, I've been using the node red plugin To automate my home for the last couple of years. But the automations within ha are much more mature these days, so I'm switching over.  The only issue with this is that it's one big list of automations.( In node red you got the ability to use tabs and such)

Kind regards

### URL

https://www.home-assistant.io/docs/automation/editor/

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by Purplehazezzzz** [comment]
Will do, thanks 👍

Op do 22 dec. 2022 19:49 schreef Franck Nijhof ***@***.***>:
