### ISSUE TITLE
Identify the ZHA channel in use.

### ISSUE THREAD

**Issue by IanAber** [home-assistant/home-assistant.github.io#25380]
### Feedback

If you have an existing system with ZHA running and a network formed already, how can you identify which channel is being used? What are you looking for in the log and at which point do you see the channel number that the radio has been configured to use.

### URL

https://www.home-assistant.io/integrations/zha/

**Comment by puddly** [comment]
The current channel, along with all other network settings, is shown in the ZHA integration configuration page.

**Comment by IanAber** [comment]
Many thanks. I was not sure if that was the actual channel setting or just the preferred on set in the config.yaml file.
Ian Abercrombie


￼

***@***.*** ***@***.***>
Phone: +1 (352) 281-6286
www.CedarTechnology.com <http://www.cedartechnology.com/>
