### ISSUE TITLE
ZENGGE Bluetooth mesh integration issue

### ISSUE THREAD

**Issue by mcles011** [home-assistant/home-assistant.github.io#25397]
### Feedback

Trying to setup a set of hao deng lights that use the ZENGGE protocol, the provided example configuration entry throws 2 errors, "missing property 'lights' "
And "bad indentation of a mapping entry" over the Mac address 

### URL

https://www.home-assistant.io/integrations/zengge/

### Version

2022.11.2

**Comment by mcles011** [comment]
have gotten past those errors now, im getting this when validating the config file:
"Platform error light.zengge - Requirements for zengge not found: ['bluepy==1.3.0']."

using the config entry as follows;

`light:
  - platform: zengge
    devices:
      - name: Test Light
        mac address: 08:65:F0:03:7C:59`

**Comment by mcles011** [comment]
light:
  - platform: zengge
    devices:
      - name: Test Light
        mac address: 08:65:F0:03:7C:59

**Comment by frenck** [comment]
Hit here @mcles011 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
