### ISSUE TITLE
Configuration.yalm

### ISSUE THREAD

**Issue by FroggyTest** [home-assistant/home-assistant.github.io#25398]
### Feedback

It would be nice to find easily the list of configuration commands available

For example I am trying to set the keyboard with CLI to be Azerty. I finally can make the file editor work, but cannot figure out what to put in configuration.yalm

All the help pages seem to lack a crucial bit of info that takes forever to find.

Man this is hard.... lol

### URL

https://www.home-assistant.io/docs/configuration/

### Version

Home Assistant 2022.12.8 Supervisor 2022.11.2 Operating System 9.4 Frontend 20221213.1

**Comment by frenck** [comment]
> It would be nice to find easily the list of configuration commands available

All options are documented, each in their relative integration page.

> For example I am trying to set the keyboard with CLI to be Azerty. I finally can make the file editor work, but cannot figure out what to put in configuration.yalm

That is not related to configuration.yaml at all, therefore you won't find such option. This is related to your system settings, not Home Assistant.

../Frenck
