### ISSUE TITLE
Feature request for Statistics Graph Card: add support to show delta values in graph

### ISSUE THREAD

**Issue by oakedcorn** [home-assistant/home-assistant.github.io#25394]
### Feedback

Is it possible to add an option that shows delta values over the selected period, rather than absolute values. This would allow to create hourly, daily, monthly,... (bar) graphs for ever increasing sensor values (like an energy meter) without the need for a Utility Meter.

### URL

https://www.home-assistant.io/dashboards/statistics-graph/

### Version

2022.12.8

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
