### ISSUE TITLE
Disable condition inside OR statement

### ISSUE THREAD

**Issue by tobox** [home-assistant/home-assistant.github.io#25393]
### Feedback

Conditions are usually ANDed by default, so disabling a condition seems to evaluate it to "true". 

But if conditions are used inside an "OR" block, shouldn't disabling a condition evaluate it to "false" (otherwise the whole OR block becomes useless)?

### URL

https://www.home-assistant.io/docs/scripts/conditions/#disabling-a-condition

### Version

2022.12

**Comment by frenck** [comment]
This is a duplicate of: https://github.com/home-assistant/core/issues/79076

Please follow that one for progress and update.

Thanks! And a Happy New Year 🥂 

../Frenck

**Comment by tobox** [comment]
I was sure someone else must have run into this before, and searched thoroughly. I just didn't find the other thread. Thanks for pointing me there.
