### ISSUE TITLE
no remove button for ESPHome in integration menu

### ISSUE THREAD

**Issue by JazekerXX** [home-assistant/home-assistant.github.io#25402]
### Feedback

i've always used own firmware on my ESP's to connect over MQTT, but i wanted to try ESPHome's native api connection. so i've uploaded an ESPHome instance via the demo website and connected a sensor and later programmed it in the ESPHome add-on. so later i found out this was not correct because it was missing an api key etc. because i had to programm it via the add-on. so that's what i did. so i started over on a new ESP with more flash size, named it the same and programmed it. the only thing now is HA expects a different sensor and askes for the api key. when i enter the api key it says cannot connect to the ESP, make sure it contains api key etc. well it does and the ESP is online.
so i thought the best way is to remove this ESPHome sensor in the integration menu and start over fresh. BUT there is no option to remove this

### URL

https://www.home-assistant.io/integrations/esphome/

### Version

2022.12.8

**Comment by frenck** [comment]
You can remove any integration entry (regardless ESPHome or anything other one) from the integrations dashboard.

Go to Settings -> Device and services. The removal option for an entry is in the three-dotted menu on the integration card.

**Comment by JazekerXX** [comment]
hi Frenck, the weird thing was this one had not. in the three dotted menu the only option was to go to the documentation.
but later i saw there was a second ESPHome entry with the same name. when i removed that one they both disappeared. and after that i just added the ESPHome device again and it worked perfectly.
anyway thx for the reply
