### ISSUE TITLE
How to add power consuming devices to the Energy Usage Graph

### ISSUE THREAD

**Issue by skyemoor** [home-assistant/home-assistant.github.io#25405]
### Feedback

I'm able to add the energy-usage-graph to a view, though have no idea how to populate it. I've taken a number of stabs in the dark without success. Is it possible to give an example of how to populate it?

For example, since it does not have a visual configuration, I added the following (ignore the first line);

type: energy-usage-graph
entities:
  - sensor.kitchen_ceiling_dimmer_2_energy
  - sensor.front_porch_lights_energy
  - sensor.studio_musician_lights_energy

I've used the above in other cards, though said cards have visual configurations that populate any additional fields. I don't know what additional fields are available or optional

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

 Home Assistant 2022.12.8 Supervisor 2022.11.2 Operating System 9.4 Frontend 20221213.1 - latest

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by skyemoor** [comment]
This was a request to add an (or link to an existing)  example of how to populate the Energy-usage-graph. I'll assume by the response that this is not the level of documentation envisioned. I've tried the Community Forum, though will now try the Discord chat server.

Thanks!
