### ISSUE TITLE
Missing rustc dependency

### ISSUE THREAD

**Issue by xgrzechu** [home-assistant/home-assistant.github.io#25411]
### Feedback

Hi, please add "rustc" as dependency 

It should be listed as it is required since cryptography v3.5 ( https://github.com/pyca/cryptography/issues/5771#issuecomment-775016788 )

It is not on the list now:
`
sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata`

Thanks!

### URL

https://www.home-assistant.io/installation/raspberrypi

**Comment by frenck** [comment]
> Hi, please add "rustc" as dependency

![image](https://user-images.githubusercontent.com/195327/209630823-c6191482-68e9-44c8-a7ec-c40fbc881642.png)

It isn't needed on all systems/architectures/setups. As per documentation, we assume you know how to adopt it to your situation.

../Frenck
