### ISSUE TITLE
https://www.home-assistant.io/more-info/unsupported/systemd_journal omits a step

### ISSUE THREAD

**Issue by rotoiti** [home-assistant/home-assistant.github.io#25426]
### Feedback

The instructions at
https://www.home-assistant.io/more-info/unsupported/systemd_journal
omit a step to enable systemd-journal-gatewayd, as it is installed and disabled by default on some systems.

After "sudo apt install systemd-journal-remote -y" command I'd suggest to add:
sudo systemctl enable systemd-journal-gatewayd.service
sudo systemctl start systemd-journal-gatewayd.service

Which should fix the issue.

### URL

https://www.home-assistant.io/more-info/unsupported/systemd_journal

**Comment by frenck** [comment]
By default, it is not disabled for the systems we support.

Please note that this is an advanced installation method; we assume people know how to handle these things.

Nevertheless, thanks for your feedback, we will take it into account if we receive multiple of these reports. 👍 

../Frenck
