### ISSUE TITLE
what is the password for the user "homeassistant"?

### ISSUE THREAD

**Issue by detlefbinder** [home-assistant/home-assistant.github.io#25425]
### Feedback

what is the password for the user "homeassistant"?

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

2022.12

### Additional information

what is the password for the user "homeassistant"?

**Comment by frenck** [comment]
The one you created during this step:

![CleanShot 2022-12-28 at 12 09 06](https://user-images.githubusercontent.com/195327/209803058-6a8ce25c-4fbb-42f8-b1ea-705fe12d2426.png)

../Frenck
