### ISSUE TITLE
I have bluetooth enabled on rpi4 still unable to integrate switchbot with home assistant

### ISSUE THREAD

**Issue by vicky1631** [home-assistant/home-assistant.github.io#25423]
### Feedback

I have bluetooth enabled on rpi4 and a bluetooth dongle attached to it yet I am unable to integrate switchbot with my home assistant. I happen to have hub mini, multiple bots, curtain and remotes from switchbot. Pls help me with the integration

### URL

https://www.home-assistant.io/integrations/switchbot

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
