### ISSUE TITLE
Missing “Options”

### ISSUE THREAD

**Issue by wwwouter** [home-assistant/home-assistant.github.io#25427]
### Feedback

<img width="808" alt="image" src="https://user-images.githubusercontent.com/997207/209822352-337d09b9-76e3-456e-9771-039a696c2207.png">

I don't see "Options", only "System options"

<img width="482" alt="image" src="https://user-images.githubusercontent.com/997207/209822240-95b3f7e6-b3d6-4c86-b56c-e173e0945cec.png">

### URL

https://www.home-assistant.io/integrations/shelly

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/209823580-4d20d651-1258-47dc-a9fa-b4d64ca68f7b.png)

Looking at your screenshot, however, it seems like your device is an first-generation Shelly device.

**Comment by wwwouter** [comment]
So "Options" is only relevant for the Bluetooth settings? Maybe "Options" can be made a smaller header, placing it beneath "Bluetooth Support"?

**Comment by thecode** [comment]
I moved bluetooth upper in https://github.com/home-assistant/home-assistant.io/pull/25825 feel free to edit the page and suggest changes if it is still not clear. Thanks.
