### ISSUE TITLE
ADS not working from version 2022.2.7

### ISSUE THREAD

**Issue by gibii88** [home-assistant/home-assistant.github.io#25424]
### Feedback

Good morning,
I write to report that the integration with the ADS protocol (beckhoff) has apparently stopped working since version 2022.2.7. I am currently using version 2022.2.5, but if I try to update the ADS integration it stops working.
Are there any fixes on this?

Thank you

### URL

https://www.home-assistant.io/integrations/ads/

### Version

2022.2.6

### Additional information

Here an issue already open from other people:
https://github.com/home-assistant/core/issues/74952

**Comment by frenck** [comment]
Hi there @gibii88 👋 

It seems like you want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
