### ISSUE TITLE
Rainforest-200 is discontinued, should be removed from this page

### ISSUE THREAD

**Issue by knwpsk** [home-assistant/home-assistant.github.io#25431]
### Feedback

The Rainforest Eagle-200 has been discontinued. The ref to it on this page should be removed.
Rainforest is now producing the "Eagle 3" (but it's currently out of stock).

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

**Comment by frenck** [comment]
Thanks, @knwpsk! Do you happen to know if the "Eagle 3" works with the existing Home Assistant integration?

**Comment by knwpsk** [comment]
Hi Frenck, no I'm sorry, I don't know.
I haven't used any of those devices yet. I'm just doing initial research.




> Thanks, @knwpsk <https://github.com/knwpsk>! Do you happen to know if the
> "Eagle 3" works with the existing Home Assistant integration?

**Comment by balloob** [comment]
From looking at their [support docs](https://support.rainforestautomation.com/support/home), they document the EAGLE-200 API, but have no documentation for the Eagle 3. We will remove the recommendation. Thanks for letting us know. Also meh what a pity.

**Comment by balloob** [comment]
Opened a PR to remove the recommendation #25533

**Comment by melbournefan** [comment]
The EAGLE 3's are back in stock. Just ordered one and will report back when I've set it up!

afaik the only change was the chipset and the design to make it smaller though i'll see how it works when I get it
