### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by uKev** [home-assistant/home-assistant.github.io#25439]
### Feedback

sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata

=> rustc is missing as a dependency.

pip3 install homeassistant will fail because of this on a clean os

### URL

https://www.home-assistant.io/installation/raspberrypi/#install-home-assistant-core

**Comment by frenck** [comment]
This depends on your system. As per the big warning on top of that page:

![image](https://user-images.githubusercontent.com/195327/209886608-7514f96f-0a10-49f5-be02-04cbe27673c7.png)


../Frenck

**Comment by uKev** [comment]
Yes I know this warning, and as a developer I know howto handle system differences. I just thought the documentation should be completed for a default raspberry pi debian system.

So why not just add "rustc" in the documentation?

Speaking about missing dependencies, "libatlas-base-dev" is also a requirement. Otherwise hass won't start and the following error accurs during numpy import:


> 2022-12-29 11:04:50.217 ERROR (MainThread) [homeassistant.setup] Setup failed for cloud: Unable to import component:                                                      
>                                                                                                                                                                           
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!                                                                                                        
>                                                                                                                                                                           
> Importing the numpy C-extensions failed. This error can happen for       
> many reasons, often due to issues with your setup or how NumPy was                                                                                                        
> installed.                                                                                                                                                                
>                                                                                                                                                                           
> We have compiled some common reasons and troubleshooting tips at:                                                                                                         
>                                                                                                                                                                           
>  https://numpy.org/devdocs/user/troubleshooting-importerror.html                                                                                                       
>                                                                                      
> Please note and check the following:                                                                                                                                      
>                                                                                      
>   * The Python version is: Python3.9 from "/srv/homeassistant/bin/python3"                                                                                                
>   * The NumPy version is: "1.23.2"                                
>                                                                                                                                                                           
> and make sure that they are the versions you expect.                                 
> Please carefully study the documentation linked above for further help.                                                                                                   
>                                                                                      
> Original error was: libcblas.so.3: cannot open shared object file: No such file or directory 


Otherwise the documentation is completed.
