### ISSUE TITLE
Most documentation need documentation.

### ISSUE THREAD

**Issue by Strikky** [home-assistant/home-assistant.github.io#25443]
### Feedback

The documentation is in general is very poor.
The most is suitable for users who don't need that documentation.

E.g.
The power flow card
inverted_entities: 
Comma seperated list of entities that should be inverted (negative for consumption and positive for production). See example usage

The example:  _inverted_entities: battery, grid_
This example is useless. Everyone knows what comma seperated is.

But.....
What is the use of inverted entities???
Then the negative and positive???

Btw this is an example, in general.
Most documentation need docuThe documentation is in general is very poor.
The most is suitable for users who don't need that documentation.

E.g.
The power flow card
inverted_entities: 
Comma seperated list of entities that should be inverted (negative for consumption and positive for production). See example usage

The example:  _inverted_entities: battery, grid_
This example is useless. Everyone knows what comma seperated is.

But.....
What is the use of inverted entities???
Then the negative and positive???

Btw this is an example, in general.
Most documentation need documentation.

As I wrote, for the most, only for those who don't need the documentation.

How to improve: Give examples the newbie understand!!
Ask a newbie before publication if he/she understand what's written..
mentation.

As I wrote, for the most, only for those who don't need the documentation.

How to improve: Give examples the newbie understand!!
Ask a newbie before publication if he/she understand what's written..

### URL

https://github.com/ulic75/power-flow-card#inverted-entities-example

### Version

2022.12.1

**Comment by frenck** [comment]
> The power flow card

That is not a card provided by the Home Assistant project?

**Comment by Strikky** [comment]
Look at:
https://www.home-assistant.io/integrations/dsmr_reader
Enable the following data sources in the DSMR Reader administration pages with the default mappings:

    Day consumption: Split topic
    Gas consumption: Split topic
    Meter Statistics: Split topic
    Telegram: Split topic

Starting with: _Enable the following data sources in the DSMR Reader administration pages with the default mappings:_

As Newbie....Very clear???
For me it could be written in Chinese. 

Split topic???
Telegram ???

E.G. Day consumption is: _**sensor.dsmr_day_consumption_electricity**_??
Or am I here totally on the wrong way?

**Comment by frenck** [comment]
> Look at:
> [home-assistant.io/integrations/dsmr_reader](https://www.home-> assistant.io/integrations/dsmr_reader)
> Enable the following data sources in the DSMR Reader administration pages with the default mappings:

I'm confused, what does that have to do with your initial feedback you posted? Could you also respond to my question above?

**Comment by frenck** [comment]
>  Starting with: Enable the following data sources in the DSMR Reader administration pages with the default mappings:

> As Newbie....Very clear???
> For me it could be written in Chinese.

That is related to configuring the DSMR Reader software. That is terminology they use, please consult the documentation of DSMR Reader for more information.

I'm not sure what you'd expect to change on our end. Could you clarify the documentation feedback suggestion you have? What can we change to improve it?

**Comment by Strikky** [comment]
The answer on your question:
_That is not a card provided by the Home Assistant project?_
Is that your conclusion or your question?


Exact what I mean.
_That is related to configuring the DSMR Reader software. That is terminology they use, please consult the documentation of DSMR Reader for more information._

You mean:
https://www.home-assistant.io/integrations/dsmr
https://www.home-assistant.io/integrations/dsmr_reader
or .........

_Enable the following data sources in the DSMR Reader administration pages with the default mappings_
There I will find the explanation what you mean?

I think you don't want to understand.

**Comment by frenck** [comment]
> Author
> [Strikky](https://github.com/Strikky) [1 minute ago](https://github.com/home-assistant/home-assistant.io/issues/25443#issuecomment-1367267302)
> The answer on your question:
> That is not a card provided by the Home Assistant project?
> Is that your conclusion or your question?

That was a question. Your feedback was provided on the Home Assistant automation page, which is clearly not related. Additionally, I'm not familiar with the "The power flow card". Hence my question.

> That is related to configuring the DSMR Reader software. That is terminology they use, please consult the documentation of DSMR Reader for more information.

> You mean:
> [home-assistant.io/integrations/dsmr](https://www.home-assistant.io/integrations/dsmr)
> [home-assistant.io/integrations/dsmr_reader](https://www.home- assistant.io/integrations/dsmr_reader)
> or .........

> Enable the following data sources in the DSMR Reader administration pages with the default mappings
> There I will find the explanation what you mean?

Your comment was about DSMR Reader, not sure why you now link DSMR as well?

> I think you don't want to understand.

I think you are not communicating clearly, dumping quite a bit of different/mixed things in a single topic that has, above all, been provided as documentation feedback on the automation page?

In general, it seems you are looking for support and not actually trying to provide documentation feedback at all. Once you have a solid suggestion on how to improve things, I'm more than happy to hear that.

You should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
