### ISSUE TITLE
Where is the port of the ha website, please 

### ISSUE THREAD

**Issue by hanscees** [home-assistant/home-assistant.github.io#25449]
### Feedback

It's very hard to find the right port where you do the on boarding. Please add the port to the on boarding documentation. If you find that via Google it's hard to find that info 

### URL

https://www.home-assistant.io/installation/

### Version

2022-12

**Comment by frenck** [comment]
Hi there @hanscees 👋 

I'm not following your comment/feedback. As far as I can see, every single installation method described provides the port. Could you clarify what you mean or what you are suggesting to change?

../Frenck

**Comment by hanscees** [comment]
Hi,
If you have just set up the docker part you go to:
https://www.home-assistant.io/getting-started/onboarding

It would ne nice if before saying "Enter a name, username, password and click on “create account”.
It would say 
Go to "https://yourinstance:8123 
Thats all I missed. And yes it is somewhere else but I had to really search to find it.

And of course the docker part being a part of Raspberrypi is strange. I run it now on my vmware homelab for instance. I will make documentation for setting up docker and then add a mosquitto docker instance beside it, since that's what I am doing right now. 

I do love home assistant, just trying to make it a tiny bit more easy. 

Greetings Hans-Cees

**Comment by frenck** [comment]
> Go to "[yourinstance:8123](https://yourinstance:8123/)
> Thats all I missed. And yes it is somewhere else but I had to really search to find it.

That is how the installation page ends... before one goes to onboarding.
This applies to **every** installation method.

![CleanShot 2022-12-29 at 21 21 09@2x](https://user-images.githubusercontent.com/195327/210007493-734b8160-fdb4-409e-929d-4bb1462c96e9.png)

> And of course the docker part being a part of Raspberrypi is strange. I run it now on my vmware homelab for instance. I will make documentation for setting up docker and then add a mosquitto docker instance beside it, since that's what I am doing right now.

Sounds to me like you looked at the Raspberry Pi installation manual instead of the one that fitted your environment. Our installation page has many different routes.

> I do love home assistant, just trying to make it a tiny bit more easy.

Understood, however, I do not follow your reasoning at this point.

../Frenck

**Comment by hanscees** [comment]
As you said there are many ways to come into the documentation.
One is going to onboarding somewhere in your journey. 
And there you have to go back to another subject to the end to find what you need. And that's poor documentation: it should give the info exactly where you need it.

**Comment by frenck** [comment]
> As you said there are many ways to come into the documentation.

I didn't say that.

> One is going to onboarding somewhere in your journey.

Yes, after the installation as per screenshot above, which applies to every installation journey.

> it should give the info exactly where you need it.

That I don't follow as pointed out above, and therefore don't agree.
The onboarding page doesn't provide installation instructions either 🤷 

../Frenck.
