### ISSUE TITLE
 Hue API limitation

### ISSUE THREAD

**Issue by simabr** [home-assistant/home-assistant.github.io#25454]
### Feedback

The documentation states:
"At the time of writing, there’s a limitation on the Hue API that each device can only send one event per second. This means that button events are rate-limited to 1 per second. This is brought to the attention of Signify and it will hopefully be fixed soon."

Is this still true and is there a way to support the request to Signify?

### URL

https://www.home-assistant.io/integrations/hue/

**Comment by balloob** [comment]
This is not a place to ask for status updates.
