### ISSUE TITLE
TFA Dostmann Sensors also supported

### ISSUE THREAD

**Issue by PAINKILLER0928** [home-assistant/home-assistant.github.io#25452]
### Feedback

Hello,

I know these sensors are old and of a dying kind, but I migrated them from an old FHEM instance , and they work like a charm. 

I've got a bunch of TFA Dostmann LaCrosse sensors of the type [30.3147.IT](https://www.tfa-dostmann.de/en/product/temperature-transmitter-30-3147/) running fine with the LaCrosse extension.

Maybe you want to add this information.

Greetings from germany

### URL

https://www.home-assistant.io/integrations/lacrosse/#tested-devices

### Version

2022.12.8

**Comment by frenck** [comment]
Thanks, @PAINKILLER0928 👍 

I've opened up a PR to add it to the page.

../Frenck
