### ISSUE TITLE
Magicseaweed API

### ISSUE THREAD

**Issue by pslavickas** [home-assistant/home-assistant.github.io#25455]
### Feedback

The Magicseaweed integration no longer provides API keys to users as mentioned in the documentation (I can verified this via emailing their general@ email address)

### URL

https://www.home-assistant.io/integrations/magicseaweed/

### Version

All versions

**Comment by frenck** [comment]
I've raised the question on an issue report in our core repository. It seems like there is still activity, so I'm not sure how it would work in that case?

../Frenck

**Comment by pslavickas** [comment]
Yeah I’d imagine they still support previously issued API tokens for now. Either way I’d still likely categorize the integration as legacy if new integrations are no longer supported by the vendor

**Comment by frenck** [comment]
We have no such categorization.

**Comment by jcconnell** [comment]
That's correct. They aren't providing new API keys at the moment (and haven't been for some time I suppose) but they may offer them again in the future. There are many users who still have API keys though (myself included). I'm slowly working to update the integration to use the config flow. ~~I would be fine categorizing it as legacy.~~

**Comment by frenck** [comment]
We have discussed this integration with some Core members, and decided to remove this integration from our Core codebase as it is not functioning and no new API keys can't be obtained either.

Even if future refactoring would make this integration back into a modern and working state, API keys would still be a problem. Therefore, we don't see a future for this integration maintained in Core. One is still free to release a refactored version as a custom integration of course.

../Frenck

**Comment by jcconnell** [comment]
Understood. I'll continue as a custom integration.

**Comment by jcconnell** [comment]
For those who are interested, I'll be developing the custom integration in this repo: https://github.com/jcconnell/magicseaweed-for-home-assistant
