### ISSUE TITLE
There is still no way to integrate Senz-Wifi

### ISSUE THREAD

**Issue by mansson** [home-assistant/home-assistant.github.io#25467]
### Feedback

"Obtain an OAuth Client ID and Client Secret from the cloud provider. The integration should have specific instructions for this"
There are no such instructions. Clicking on "Add Integration" just brings you back to your own HA page. 
Going to https://api.senzthermostat.nvent.com/ just provides information for registered 3d party developers, not end users trying to obtain OAuth2 and secret for HA. It used to work about a year ago, but then the manufacturer seems to have closed the service. It would be nice if the documentation clarified this.
Or if the service is still available, please provide a link to it.
Or ask nvent if they really intended to alienate all the HA users of the world by disabling the once-working integration.

### URL

https://www.home-assistant.io/integrations/senz

### Version

2022.12.8

**Comment by milanmeu** [comment]
You should be able to use Home Assistant Cloud Account Linking, so you don't need to get your own OAuth2 tokens.

Follow these steps and let me know where things go wrong:
1. Browse to your Home Assistant instance.
2. In the sidebar click on [Settings](https://my.home-assistant.io/redirect/config).
3. From the configuration menu select: [Devices & Services](https://my.home-assistant.io/redirect/integrations).
4. In the bottom right, click on the [Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=senz) button.
5. From the list, search and select “nVent RAYCHEM SENZ”.
6. A new browser tab should open, login with your SENZ account and follow the instructions.
7. You should be redirected to a page saying "Done! Your account is now linked, you can close this window."
8. Go back to you Home Assistant tab and there should be a "Successfully authenticated" pop-up.
