### ISSUE TITLE
Google Home Automations start

### ISSUE THREAD

**Issue by stibe881** [home-assistant/home-assistant.github.io#25463]
### Feedback

Is it also possible to start Google Home automations? I tried it, but the automation doesn't start. Lights or similar work.

### URL

https://rc.home-assistant.io/integrations/google_assistant_sdk/

### Version

2023.01b2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
