### ISSUE TITLE
CGroup Version: add note to reboot if supervised install just completed

### ISSUE THREAD

**Issue by PotatoOfDestiny** [home-assistant/home-assistant.github.io#25473]
### Feedback

The CGroup version warning appears on a supervised install if the system hasn't been rebooted since the installer completed. I think this is because the default install of docker is using the newer CGroup, and the change to grub.conf to switch it back to the older one needs a reboot to take effect. I'd suggest a note to the effect of "if you've just completed a supervised install and are getting this message, do a full reboot of the system" could save some minor headaches. 

### URL

https://www.home-assistant.io/more-info/unsupported/cgroup_version/

**Comment by henningms** [comment]
Second this. I got so many warnings after updating in December regarding the Supervisor and CGroup not supported. The "read more" information suggested that this would never happen on Home Assistant OS, but after doing a full system reboot the messages disappeared.
