### ISSUE TITLE
The LeGrand page shows the Netatmo logo and some links on the right sidebar point to the netatmo pages

### ISSUE THREAD

**Issue by teranex** [home-assistant/home-assistant.github.io#25474]
### Feedback

The LeGrand page shows the Netatmo logo and some links on the right sidebar point to the netatmo pages

### URL

https://www.home-assistant.io/integrations/legrand/

**Comment by frenck** [comment]
That is correct.

As per the first line in the documentation of the LeGrand documentation page:

<img width="1093" alt="CleanShot 2022-12-31 at 13 26 55@2x" src="https://user-images.githubusercontent.com/195327/210136733-4f223b92-48dc-4b3e-a487-277a8889bfb3.png">


../Frenck

**Comment by teranex** [comment]
Oh sorry about that!

**Comment by frenck** [comment]
No problem!

Happy New Year! 🥂 

../Frenck

**Comment by teranex** [comment]
For you also a Happy New Year :)
