### ISSUE TITLE
The "color icon based on state" is not working on helper schedule...

### ISSUE THREAD

**Issue by jschinke1067** [home-assistant/home-assistant.github.io#25478]
### Feedback

If an item is active, the icon show's an active state. This work's great everywhere except on Helper Schedules. If an schedule get's active (on) the state still show's inactive state visually...

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2022.12.8

### Additional information

This is i minor problem, but it would be great if it could be fixed...

**Comment by frenck** [comment]
Hi there @jschinke1067 👋 

It seems like you want to report an issue or provide a suggestion for the Home Assistant frontend, however, you have submitted documentation feedback instead. There is no amount of  documentation we can adjust to make that happen 😉 

Please check out https://www.home-assistant.io/help on where to go.

Thanks! 👍 

Happy New Year 🥂 

../Frenck
