### ISSUE TITLE
Google or Local Calendar

### ISSUE THREAD

**Issue by stepnage** [home-assistant/home-assistant.github.io#25475]
### Feedback

Please add ability to import calendars. You can just export Google calendars to a file without having to sign up or generate AUTH codes. But please add therse options in upcoming release.

### URL

https://www.home-assistant.io/integrations/google/#:~:text=From%20the%20configuration%20menu%20select,to%20complete%20the%20set%20up.

### Version

Latest

**Comment by allenporter** [comment]
Hi, feature requests can go in the [community forums](https://community.home-assistant.io/c/feature-requests/13) and not github
