### ISSUE TITLE
Page missing steps for Google assistant configuration

### ISSUE THREAD

**Issue by Doneven2012** [home-assistant/home-assistant.github.io#25481]
### Feedback

I could not get this to work until I realized that there were no steps on how to configure a service account for the app. 
I had to follow another tutorial, https://djajafer.medium.com/integrate-home-assistant-with-google-home-4736718fbfc7, which gave the necessary steps. 

Maybe I'm slow and missed it, I did do that late in the day, but I don't remember seeing anything.

Thank you :)

### URL

https://www.home-assistant.io/integrations/google_assistant/#yaml-configuration

### Version

2022.12.8

**Comment by Mettchen** [comment]
I've attempted to rectify this in [#25899](https://github.com/home-assistant/home-assistant.io/pull/25899)
