### ISSUE TITLE
Additional redirect URIs

### ISSUE THREAD

**Issue by erdnuesse** [home-assistant/home-assistant.github.io#25487]
### Feedback

Hi, 
it may be beneficial to add the solution to the problem
"INVALID_CLIENT: Invalid redirect URI"

as seen here:
https://community.home-assistant.io/t/spotify-error-invalid-client-invalid-redirect-uri/428208/9

to this howto of the integration.
tl;dr: the second URI; which may be necessary, if you didn't expose your home assistant to be available from the internet. 

Best regards.

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

Home Assistant 2022.12.8

### Additional information

Supervisor 2022.12.1 
Frontend 20221213.1 - latest

**Comment by frenck** [comment]
> it may be beneficial to add the solution to the problem

The provided solution doesn't seem correct. There is no need to expose your HA instance to the internet either.

The only needed URL is the URL exactly as documented in the existing documentation. The provided link to the community forums, provides two unrelated links, which is not right either.

Closing as the current documentation is correct.

../Frenck
