### ISSUE TITLE
Workday for Spain January 2 is off but should be on

### ISSUE THREAD

**Issue by AlbertORoura** [home-assistant/home-assistant.github.io#25499]
### Feedback

Just in some localities in Spain the 2th of January is bank holiday.

### URL

http://www.home-assistant.io

**Comment by frenck** [comment]
Hi there @AlbertORoura 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
