### ISSUE TITLE
Tile: deleted trackers do not go away

### ISSUE THREAD

**Issue by MarkAtwood** [home-assistant/home-assistant.github.io#25492]
### Feedback

I had Tile Inc delete a bunch of old and lost tile trackers from my account. They no longer appear in the Tile mobile app, and they are not "hidden", they are gone.  But they still show up in the Tile  Hassio integration.  They should disappear, or disappear on reload.

### URL

https://www.home-assistant.io/integrations/tile/

### Version

2022.12.8

**Comment by bachya** [comment]
Hi @MarkAtwood,

This particular repo is for the Home Assistant website, not for the core app itself. Also, our issue trackers are for bug reports, not feature requests; feature requests should be suggested in the "Features" section of the community forums: https://community.home-assistant.io/c/feature-requests/13

Thank you for your participation in the project!
