### ISSUE TITLE
More Details Needed for Locative Geofence Integration

### ISSUE THREAD

**Issue by matapan** [home-assistant/home-assistant.github.io#25494]
### Feedback

Can the documentation for this integration describe how to create the association between a person entity and the location tracker?

### URL

https://www.home-assistant.io/integrations/locative

### Version

2022.12.8

**Comment by frenck** [comment]
Hi there @matapan 👋 

That is not a feature of the locative integration. This integration provides device trackers. For more information on how to use "Persons" in Home Assistant, please consult the persons documentation:

<https://www.home-assistant.io/integrations/person>

Happy New Year 🥂 

../Frenck
