### ISSUE TITLE
Proximity Integration page text specifies a list should be used but the example is a map

### ISSUE THREAD

**Issue by tomkessler** [home-assistant/home-assistant.github.io#25490]
### Feedback

At the bottom of the page.  Text specifies "To add multiple proximity components, simply use a list in your configuration.yaml file:" but the example shown is a map not a list.

![image](https://user-images.githubusercontent.com/20233788/210181682-16c5d735-3d08-43e4-8a86-807b3351872a.png)

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2022.12.8

**Comment by frenck** [comment]
Hi there @tomkessler 👋 

I agree, it is an odd one. I've opened up a PR to adjust the wording.
Thanks for sharing your feedback ❤️ 


../Frenck
