### ISSUE TITLE
Tile: renaming a tile in the app does not change the name in the integration

### ISSUE THREAD

**Issue by MarkAtwood** [home-assistant/home-assistant.github.io#25493]
### Feedback

As I move tiles from item to item, i rename them in the Tile app.  However, the name does not update in the Tile hassio integration.  Also, I notice that the tile name gets put in the entity id.

The entity id should be instead something like tile_<uuid>, as each tile has a uuid.  And the name should update as they get updated in the Tile app.

### URL

https://www.home-assistant.io/integrations/tile/

### Version

2022.12.8

**Comment by bachya** [comment]
Hi @MarkAtwood,

This particular repo is for the Home Assistant website, not for the core app itself. Also, our issue trackers are for bug reports, not feature requests; feature requests should be suggested in the "Features" section of the community forums: https://community.home-assistant.io/c/feature-requests/13

Thank you for your participation in the project!
