### ISSUE TITLE
Change 'Reboot Host' label in docs to 'Reboot system'

### ISSUE THREAD

**Issue by theNailz** [home-assistant/home-assistant.github.io#25500]
### Feedback

On the following page a label should be changed:
https://www.home-assistant.io/more-info/unhealthy/setup

> If this does not help or you do not have any way to access the CLI, you can try to reboot the host. This can be done by going to [Settings -> System -> Hardware](https://my.home-assistant.io/redirect/hardware), opening the menu in the top right corner, and selecting “**Reboot Host**”.

The menu option is called "**Reboot system**" (exact capitalization), not "Reboot Host".

### URL

https://www.home-assistant.io/more-info/unhealthy/setup

### Version

2022.12.8

**Comment by frenck** [comment]
Thanks, @theNailz 👍 

I've opened a PR to adjust the documentation.

Happy New Year 🥂 


../Frenck
