### ISSUE TITLE
Need basic direction

### ISSUE THREAD

**Issue by aszona** [home-assistant/home-assistant.github.io#25518]
### Feedback

Good day,

I started yet again in you links for beginners to try to learn.

I try to understand the structure of home assistant, but the terms are bewildering. I have a decent computer background, yet I’m compelled to tell you your basics are absolutely bewildering.

You present "helpful" links, to triggers, for example. They immediately result completely in a fog of undecipherable terms. 

Your basic instructions turn to jibberish instead of being helpful and teaching.

I sincerely want to use home assistant, but your instructions are absurdly difficult. 

I have managed to add a camera, and a weather feature or two, but I have no solid understanding of what I’m doing.

If anybody cares or even reads this, where can you suggest I go for elementary help?

Tony Zona
Waterford, PA USA

### URL

https://www.home-assistant.io/docs/automation/trigger/#trigger-id

**Comment by frenck** [comment]
> If anybody cares or even reads this, where can you suggest I go for elementary help?

We have a big community that can help you out getting started and helping you understand any questions you might have.

For example, you could try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). We also have communities on Facebook and Reddit, in case those are preferred by you more.

You can find all these sources and links on our help page:

https://www.home-assistant.io/help

../Frenck
