### ISSUE TITLE
energy docs:  no info about default_config

### ISSUE THREAD

**Issue by Blacksli** [home-assistant/home-assistant.github.io#25512]
### Feedback

Configuration
This integration is by default enabled, unless you’ve disabled or removed the [default_config:](https://www.home-assistant.io/integrations/default_config/) line from your configuration. If that is the case, the following example shows you how to enable this integration manually:

```
# Example configuration.yaml entry
energy:
```

### URL

https://www.home-assistant.io/docs/energy

### Version

2022.12.8

### Additional information

energy docs:  no info about default_config

**Comment by frenck** [comment]
It is documented:

https://www.home-assistant.io/docs/energy/faq/#the-energy-panel-is-not-visible

![image](https://user-images.githubusercontent.com/195327/210275413-6bf5e72a-304e-4a2c-9725-ae57b6207544.png)

../Frenck
