### ISSUE TITLE
Tuya integration: Is there more?

### ISSUE THREAD

**Issue by joeinaustin** [home-assistant/home-assistant.github.io#25516]
### Feedback

I followed this integration and it seems to have installed and recognized my "multifunction alarm".  However, I cannot see the status of the 5 door sensors that are connected to the Tuya hub.  Everything works fine in the tuya app and I can see the sensors there.  I just don't see the sensors in HA.  Only the "multifunction alarm" with no drill down ability.  Am I missing something?

### URL

austinlakes.ml

### Version

Home Assistant 2022.12.8

**Comment by joeinaustin** [comment]
I expected more devices and entities here

![tuyaHAone](https://user-images.githubusercontent.com/11775403/210287679-f5714180-720c-4577-b882-b7ebe0c92bc8.PNG)

**Comment by frenck** [comment]
Hi there @joeinaustin 👋 

It seems like you are experiencing an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
