### ISSUE TITLE
The provided bindkey did not work, sensor data could not be decrypted. Please check it and try again.

### ISSUE THREAD

**Issue by bheinek** [home-assistant/home-assistant.github.io#25520]
### Feedback

No matter what I try I always get this message in HA The provided bindkey did not work, sensor data could not be decrypted. Please check it and try again.

### URL

https://www.home-assistant.io/integrations/xiaomi_ble

**Comment by Jc2k** [comment]
Hi - this particular GitHub repository is for issues with the documentation, not for for support using HA.

You can get support from other users on the forums or discord.

If you think this is a bug, you can file an issue directly on the development github using [this template](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml).

If you file a bug, you'll need to provide more information about the problem, including the exact model of sensor that you are trying to use. You'll also need to describe exactly what you did, in what order, how long you waited, etc.
