### ISSUE TITLE
How to Fix CGroup version manually?

### ISSUE THREAD

**Issue by Niptoc** [home-assistant/home-assistant.github.io#25521]
### Feedback

Hi, 

Thank you for this proposed solution. 
But in my case the solution does not fix the CGroup Version.

Can you add in this section how to update the CGroup version manually?

### URL

https://www.home-assistant.io/more-info/unsupported/cgroup_version

### Version

2022.12

**Comment by frenck** [comment]
> Can you add in this section how to update the CGroup version manually?

We are not planning on doing that. This installation method is highly advanced; we assume users of this installation method to have a high level of knowledge in Linux administration, Docker, and networking in general. This is also warned for when using this installation method and documented as such.

If things like these bring you into problems, we would highly recommend looking into a different installation method that might better suit you.

../Frenck

**Comment by Niptoc** [comment]
Hi, Thank you for taking the time to answer my request. 

Have a good day.

Niptoc

**Comment by spattinson** [comment]
Changing cgroup version🔗
Changing cgroup version requires rebooting the entire system.

On systemd-based systems, cgroup v2 can be enabled by adding systemd.unified_cgroup_hierarchy=1 to the kernel cmdline. To revert the cgroup version to v1, you need to set systemd.unified_cgroup_hierarchy=0 instead.

Source: https://docs.docker.com/config/containers/runmetrics/#:~:text=Changing%20cgroup%20version&text=To%20revert%20the%20cgroup%20version,unified_cgroup_hierarchy%3D0%20instead.&text=If%20grubby%20command%20is%20not,and%20run%20sudo%20update%2Dgrub%20.
