### ISSUE TITLE
missing instructions

### ISSUE THREAD

**Issue by leonvet** [home-assistant/home-assistant.github.io#25526]
### Feedback

Following these instructions to install home assistant on a pi zero w running raspberry os lite i ran into a few issues.

rust is not available and is required when compiling hass
- solved by running curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
- run this in the virtual homeassistant shell
- on a pi zero it takes 15 hours !!!! to compile. A warning in the docs would be nice

hass command is not found
- the installation instructions only mention to run hass
- as a first time user of hassio i was not aware its located in /home/homeassistant/.local/bin
- please add instructions to add this to the path

running hass for the first time it did not start because aiohttp_core was missing
- solved by running: pip3 install aiohttp_cors

Please also add instructions how to start hass after the pi has booted

Regards,

Leon

### URL

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core

### Version

2022.12.8

**Comment by frenck** [comment]
Hi there @leonvet 👋 

There is a warning in the docs that covers all these cases:

> rust is not available and is required when compiling hass

![image](https://user-images.githubusercontent.com/195327/210415448-28ac09e4-c00f-47f0-81d0-c670d25fb994.png)

> hass command is not found

> as a first time user of hassio i was not aware its located in /home/homeassistant/.local/bin

This actually means you didn't follow the documentation right, as Home Assistant should be installed in an virtual environment. Considering the path it ended up in your case, it seems like you didn't do that.

> Please also add instructions how to start hass after the pi has booted

That is system dependent, considering the advanced use case of the installation method, we 
assume a user has the knowledge to do so themselves for the init system of choice.

../Frenck

**Comment by leonvet** [comment]
Thanks Frenck for responding to my feedback but i'm not the only one following the instructions to a tee and ending up googling for hours judging by lots of forum posts.

I'm well aware everybody's system is different but there are some vital instructions missing that would make it a bit easier. In fact just ran into another one that pops up on the console after selecting a location in the web ui and clicking next

libcblas.so.3: cannot open shared object file: No such file or directory

- solved by quitting hass and running

	sudo apt-get install libatlas-base-dev


Don't take this criticism the wrong way, as a software developer and system admin i know how much effort goes into installation instructions and they change all the time.

Regards,

Leon

**Comment by frenck** [comment]
> Don't take this criticism the wrong way

We don't take it the wrong way, but also, please don't take it the wrong way that these instructions are bare bone, and we expect people to know how to handle the difference. Some of the suggestions you gave, for example, don't apply to others. Anyways, if this is not your cup of tea, please use a different and more suitable installation method. We have multiple available, some might better fit you than others.

../Frenck
