### ISSUE TITLE
myq Door sensor is reporting open when closed.

### ISSUE THREAD

**Issue by ebmarquez** [home-assistant/home-assistant.github.io#25532]
### Feedback

Door sensor is reporting to HA that the door is Open when it is really closed.  This was previously working correctly, but broke redently.

### URL

https://www.home-assistant.io/integrations/myq/

### Version

2022.12.9

### Additional information

Device info
Chamberlain Smart Garage Hub
by The Chamberlain Group Inc.
Firmware: 3.14

**Comment by frenck** [comment]
Hi there @ebmarquez 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
