### ISSUE TITLE
Nice image

### ISSUE THREAD

**Issue by AndyinHawick** [home-assistant/home-assistant.github.io#25550]
### Feedback

How does one get all of the data to appear on a Card?

The only variable that seems to be available is whether the sun is above or below the horizon but the image and the attributes list suggests that there are many other useful data that should be available. How does one get, for example, the sunset time to appear on the card?

Thanks

### URL

https://www.home-assistant.io/integrations/sun

### Version

2022.12.9

**Comment by frenck** [comment]
That is a screenshot of the more information dialog of entities, a really old one! Home Assistant has evolved over time, so the UI updated and that screenshot needs a replacement.


>  How does one get, for example, the sunset time to appear on the card?

This is not the right place for support.  We use GitHub for tracking issues and documentation feedback.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
