### ISSUE TITLE
How to play media on lovelace UI

### ISSUE THREAD

**Issue by simatao** [home-assistant/home-assistant.github.io#25552]
### Feedback

HI, how is it possible to play local mp4 files on the lovelace UI?

### URL

https://www.home-assistant.io/integrations/media_source/#playing-media-from-a-media-source

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
