### ISSUE TITLE
Reolink Intergration

### ISSUE THREAD

**Issue by unf0rg0tt3n** [home-assistant/home-assistant.github.io#25568]
### Feedback

Hi,

I've tested the Reolink doorbell POE; it only shows camera streams.
doorbell press, lights etc. not working.

Camera which does work:
Reolink RLC-820A

### URL

https://www.home-assistant.io/integrations/reolink

### Version

2023.1.0

**Comment by frenck** [comment]
> I've tested the Reolink doorbell POE; it only shows camera streams.
doorbell press, lights etc. not working.

That is correct, the current version of the integration only does camera's. Support for other things are expected to be added in future releases.

I've added the RCL-820A to the documentation and is now pending in this PR #25567

../Frenck

**Comment by unf0rg0tt3n** [comment]
> That is correct, the current version of the integration only does camera's. Support for other things are expected to be added in future releases.

Thanks for the feedback, JimStar got a working intergration within HACS: https://github.com/JimStar/reolink_cctv

Cheers,
Dennis

**Comment by frenck** [comment]
> JimStar got a working intergration within HACS: [JimStar/reolink_cctv](https://github.com/JimStar/reolink_cctv)

Cool, feel free to use that one instead 🤷  Custom integrations are not maintained or supported by the Home Assistant project, nor is it related to our documentation.

../Frenck

**Comment by unf0rg0tt3n** [comment]
> > JimStar got a working intergration within HACS: [JimStar/reolink_cctv](https://github.com/JimStar/reolink_cctv)
> 
> Cool, feel free to use that one instead 🤷 Custom integrations are not maintained or supported by the Home Assistant project, nor is it related to our documentation.
> 
> ../Frenck

I know. Just was referring to the custom integration because someone already invented the wheel. maybe it makes it easier to port or something. Not a developer so I don't really know.
Didn't want to post a rude reaction or something. Sorry if I was

**Comment by frenck** [comment]
Things are being added to core, but that stuff takes time. As said, more features are expected in the upcoming releases.

Rome wasn't build in a day either 😉 

../Frenck

**Comment by unf0rg0tt3n** [comment]
Love how far home assistant has come! I'm a long time user from the version 0.60 era lol.
Still a big fan

**Comment by Kepro** [comment]
Hello, thanks for this integration, I have same "issue" that doorbell is doesn't have any sensors... but in the documentation there is 
> Reolink doorbell presses only generate ONVIF event notifications when the doorbell is directly connected to your network. The doorbell visitor binary sensor will not work when connecting the Reolink doorbell to an NVR.

so that is little bit misleading :-) as it's not supported right now... I had a working version of ONVIF of node.js version so I would love to help but this is python so :(

**Comment by netweaver1970** [comment]
> ### Feedback
> Hi,
> 
> I've tested the Reolink doorbell POE; it only shows camera streams. doorbell press, lights etc. not working.
> 
> Camera which does work: Reolink RLC-820A
> 
> ### URL
> https://www.home-assistant.io/integrations/reolink
> 
> ### Version
> 2023.1.0
> 
> ### Additional information
> _No response_

I also have the RLC-820A.

The RTSP main stream can't be used in the Picture Glance Card: at the start I get a single updated picture but no moving video afterwards. When I use the RTMP Sub and RTMP extra for the Picture glance card, I do get moving video, but at a (too) low resolution. 
This is the default setup of the camera by the Integration:
![image](https://user-images.githubusercontent.com/18028618/210923467-f4aa3143-bcb7-449b-a5c4-432f4abbd2cc.png)

What did you use/setup/configure to get the HighDef moving video in HA?
