### ISSUE TITLE
Reolink Integration 

### ISSUE THREAD

**Issue by Johnnyyr** [home-assistant/home-assistant.github.io#25566]
### Feedback

Hi, 

i have testet the follow cams:

works well and quickly:
RLC-520
RLC-410W

does not work
E1 Pro

### URL

https://www.home-assistant.io/integrations/reolink#reolink-firmware-limitations

### Version

2023.1.0

**Comment by frenck** [comment]
Thanks for reporting this @Johnnyyr 👍 

I've opened up a PR to adjust the documentation.

Happy New Year 🥂 

../Frenck
