### ISSUE TITLE
Reolink Intergration

### ISSUE THREAD

**Issue by Bob-Murphy** [home-assistant/home-assistant.github.io#25574]
### Feedback

Hey,

The integration of my Reolink `RLC-511W` worked flawless - should be good to add it to the list of compatible products..

Thank you for the integration

### URL

https://www.home-assistant.io/integrations/reolink

### Version

2023.1.0

**Comment by frenck** [comment]
Thanks, @Bob-Murphy!

Will be added in #25567

Happy New Year 🥂 

../Frenck

**Comment by Bob-Murphy** [comment]
No problem.
Happy New Year to you as well.
