### ISSUE TITLE
Hide Mold Indicator Integration in Dashboard

### ISSUE THREAD

**Issue by stheid** [home-assistant/home-assistant.github.io#25570]
### Feedback

To my knowledge there is currently no way to mark the mold indicator as "hidden" in HA.

According to the [documentation the mold indicator](https://www.home-assistant.io/integrations/mold_indicator/) does not support the "unique_id" and can therefore not be managed in the UI. 

I have tried to add and "entity_id" and "device_id" because the [the documentation mentions those fields too](https://www.home-assistant.io/faq/unique_id)

### URL

https://www.home-assistant.io/integrations/mold_indicator/

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
