### ISSUE TITLE
using multiple accounts for google assistant sdk

### ISSUE THREAD

**Issue by GiladShoham** [home-assistant/home-assistant.github.io#25579]
### Feedback

right now the docs don't mention if you can use multiple accounts for google assistant SDK. 
if yes, how to configure it and send the command to the specific account.
If not, worth mentioning it.

### URL

https://www.home-assistant.io/integrations/google_assistant_sdk/

### Version

2023.1

### Additional information

I want to use it with a different account to call the find my phone service for my phone and my wife's phone. and these are bound to the google account.

**Comment by frenck** [comment]
It isn't possible, documentation has been adjusted in https://github.com/home-assistant/home-assistant.io/pull/25581

../Frenck
