### ISSUE TITLE
notify.google_assistant_sdk only Broadcast to all speakers 

### ISSUE THREAD

**Issue by michaeltryl** [home-assistant/home-assistant.github.io#25577]
### Feedback

service: notify.google_assistant_sdk
data:
  message: hej med dig
  target:
    - Køkken

This code sends to all my speakers, not only "køkken"
It also says
2 køkken. Hej med dig
Instead of only 
Hej med dig.

### URL

My home assistant

### Version

2023.01

**Comment by FredericESH** [comment]
I tried, and you need to use the exact name of the google home you want to broadcast to (case sensitive)

**Comment by michaeltryl** [comment]
Thanks i have found out. It do not work in Denmark yet
