### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by swalsh11** [home-assistant/home-assistant.github.io#25586]
### Feedback

I think you you need to mention:
 
sudo apt install rustc

before : 

pip3 install homeassistant

Or install fails.

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

curent

### Additional information

I think you you need to mention:
 
sudo apt install rustc

before : 

pip3 install homeassistant

Or install fails.

**Comment by frenck** [comment]
It depends on your system and setup, as in many cases, a pre-build wheel package is available. Installing rust would be a waste of time and space in such cases; hence the warning:

![image](https://user-images.githubusercontent.com/195327/210959670-f7fd6262-de7e-4970-9e3a-e68b16bc6750.png)

../Frenck
