### ISSUE TITLE
explain how to get the config entry for the google sheets service

### ISSUE THREAD

**Issue by GiladShoham** [home-assistant/home-assistant.github.io#25580]
### Feedback

The config entry is a mandatory key, but it's unclear how to get it. 
Later on when creating automation from the UI, I didn't have to put it (as it's added internally by the system). 
but when testing the service via call service directly (like in dev tools), I had to use it, and couldn't find it easily.

### URL

https://www.home-assistant.io/integrations/google_sheets/

### Version

2023.1

### Additional information

I was able eventually to get it by following this - https://community.home-assistant.io/t/how-do-i-select-the-sheet-or-find-the-config-entry-for-my-google-sheets-integration/488572/4?u=giladshoham

- open /config/.storage/core.config_entries
- search for “Google Sheets” and find your config_entry under “entry_id” name

**Comment by tkdrob** [comment]
When using the dev tools, use the UI mode, not yaml to get it. Then go back to yaml after you have selected the desired config entry. It's that simple.

**Comment by tkdrob** [comment]
@home-assistant close
