### ISSUE TITLE
Reolink Integration

### ISSUE THREAD

**Issue by pjwhitby** [home-assistant/home-assistant.github.io#25593]
### Feedback

I am running Reolink RLC-820A cameras on a RLN16-410 NVR and I can confirm they work on the new Reolink Integration

Thank you for the integration

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

Home Assistant 2023.1.0

### Additional information

Home Assistant 2023.1.0
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

**Comment by frenck** [comment]
Thanks, @pjwhitby 👍 

It has been added to the documentation sources.

../Frenck
