### ISSUE TITLE
Recommend 32-bit OS for Pi3

### ISSUE THREAD

**Issue by NeilRickards** [home-assistant/home-assistant.github.io#25598]
### Feedback

The Raspberry Pi 3 has 1GB of memory which is not enough to reliably run the 64-bit HAOS.  It becomes unstable and prone to silently crashing.  We should recommend 32-bit OS on this device.

### URL

https://www.home-assistant.io/installation/raspberrypi

**Comment by frenck** [comment]
Closing as per https://github.com/home-assistant/home-assistant.io/pull/25599#issuecomment-1373458046
