### ISSUE TITLE
understandable instruction

### ISSUE THREAD

**Issue by Cdhock** [home-assistant/home-assistant.github.io#25606]
### Feedback

you assume too much. from line one about a yaml file im lost. dont know where it is or how to edit it. until I can get past step 1 I cant comment on the rest but so far very dissapointed that this is so difficult with nor real direction.

### URL

https://www.home-assistant.io/docs/configuration/basic/

**Comment by frenck** [comment]
More information on editting configuration files and YAML, can be found in our configuration documentation here:

<https://www.home-assistant.io/docs/configuration/>

More information about YAML can be found here:

<https://www.home-assistant.io/docs/configuration/yaml/>

Please note, that YAML is a generic and common method to write down configuration. You can find tons of resources on how YAML works across the internet too.

../Frenck
