### ISSUE TITLE
support theme with tile features

### ISSUE THREAD

**Issue by AlainRob** [home-assistant/home-assistant.github.io#25615]
### Feedback

Love the new tile features it is very convenient for lights in particular. It would be great if we could set a theme to this tile though.

### URL

https://www.home-assistant.io/dashboards/tile/

### Version

2023.1.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
