### ISSUE TITLE
rustc package is missing in core installation docs

### ISSUE THREAD

**Issue by dPeS** [home-assistant/home-assistant.github.io#25612]
### Feedback

rustc package is missing here:

"sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata"

without that pkg cryptography is failing when pip is building wheel.

### URL

https://www.home-assistant.io/installation/raspberrypi#install-dependencies

**Comment by frenck** [comment]
Not all systems need rust, as there are also pre-build wheels available. It is possible your setup needs it... but that is warned in the installation instructions. It seems like you have missed the warning stated on top of the instructions:


![CleanShot 2023-01-07 at 14 28 01](https://user-images.githubusercontent.com/195327/211153134-dd6b8562-c396-43a2-89d9-335d0dfe40e6.png)

../Frenck
