### ISSUE TITLE
Which API scopes are necessary / needed for the integration?

### ISSUE THREAD

**Issue by phrozen77** [home-assistant/home-assistant.github.io#25619]
### Feedback

The docs don't tell you which API scopes you need to request when registering for the API key.

Possible values:

<img width="225" alt="Bildschirm­foto 2023-01-07 um 06 59 36" src="https://user-images.githubusercontent.com/1218594/211133689-8c97769d-3661-4449-bdeb-f64e15a6f5dc.png">

Especially "write_access" stands out and maybe could be left out?

As it is, and especially as someone new to the integration, i don't know which are strictly necessary and which aren't.

### URL

https://www.home-assistant.io/integrations/tibber

**Comment by phrozen77** [comment]
Still unresolved - @Danielhiversen can you help out? I'd also submit a PR for the documentation :)

**Comment by Danielhiversen** [comment]
I do not know. You could test and see what is required to make it work.

**Comment by phrozen77** [comment]
a comment 👍

**Comment by mtdcr** [comment]
Disabling `full` and `write_access` works for me. I haven't tried to disable anything else, yet.

**Comment by phrozen77** [comment]
> Disabling `full` and `write_access` works for me. I haven't tried to disable anything else, yet.

Thank you - i would've expected an answer from someone who apparently works for Tibber, but seems i expected too much ☹️

**Comment by phrozen77** [comment]
🤷‍♂️

**Comment by phrozen77** [comment]
🤷‍♂️🤷‍♂️

**Comment by Danielhiversen** [comment]
I do not know.
You are welcome to test and improve the documentation if you want.
