### ISSUE TITLE
Failed to connect when entering password for Roomba j7+

### ISSUE THREAD

**Issue by Techgeekster** [home-assistant/home-assistant.github.io#25617]
### Feedback

I've been using the Home Assistant instructions for iRobot to connect my Roomba j7+: [IRobot Instructions](https://www.home-assistant.io/integrations/roomba/#manually-retrieving-your-credentials)

I used the library [dorita980](https://github.com/koalazak/dorita980) to retrieve the password for my iRobot Roomba j7+. However, when I entered the password between the '=>' and '<=' not including the whitespace I received a 'Failed to connect' error on the Home Assistant integration.

Password retreived through dorita980:
![image](https://user-images.githubusercontent.com/16390046/211119120-9aa7ae3c-9c32-499e-8f28-e544067acde6.png)

Error on Home Assistant:
![image](https://user-images.githubusercontent.com/16390046/211119191-870b4d58-a933-40fd-9494-16b8eef1c8a1.png)

Any help is appreciated

### URL

https://www.home-assistant.io/integrations/roomba/#manually-retrieving-your-credentials

### Version

2023.1.1

### Additional information

**Home Assistant Version**
Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

**"Jeff" Roomba j7+ Version**
Product Software 22.29.3

**Comment by nutriOn** [comment]
Same issue, did you find a solution yet?

**Comment by frenck** [comment]
Hi there @Techgeekster 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
