### ISSUE TITLE
Very complex

### ISSUE THREAD

**Issue by jotakar** [home-assistant/home-assistant.github.io#25620]
### Feedback

I would lie to test Home Assistant (now I'm using Domoticz). Then my first step was read about Installation process.... this is like a hieroglyph. It looks like documentation is for very, very, experimented technicians. I cannot see clearly how is the process for installing the software. Example, It talks about core supervised, where is these concepts explained? All methods are mixed, so you see a big and dark labyrinth. 
I think there is a fault in documentation of the software.

### URL

https://www.home-assistant.io/getting-started/

**Comment by frenck** [comment]
Thos concepts are explained on our installation documentation, which you can find here:

<https://www.home-assistant.io/installation/>

../Frenck
