### ISSUE TITLE
Speedtest Integration Lack Of Examples

### ISSUE THREAD

**Issue by big-ted** [home-assistant/home-assistant.github.io#25622]
### Feedback

Not that the developers have forced the integration to run every 60 minutes  an example needs to be provided how to disable polling and using the update_entity service to update at a time interval of our timing, how is a new starter going to manage this without an example

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2023.1.1

**Comment by frenck** [comment]
That feature is not a speedtestdotnet-specific feature, but a generic Home Assistant feature. It, therefore, doesn't belong on this page. The feature you are referring to applies to virtually all integrations. Documenting those on each integration page makes no sense and would, above all, be unmaintainable.

Nevertheless, thanks for your suggestion.

../Frenck
