### ISSUE TITLE
It might be useful to provide an alternative approach

### ISSUE THREAD

**Issue by jblsd** [home-assistant/home-assistant.github.io#25626]
### Feedback

I used this integration for a while, but recently found a far simpler approach by using the Starling Home Hub (https://www.starlinghome.io/), though this requires hardware ($99). Starling provides a bridge from Nest to HomeKit. Then, the standard Home Assistant Home Kit integration works great for Nest thermostats, protects, and cameras. 

It would be useful to highlight this approach as an alternative (or using Home Bridge as an alternative to Starling) since it is much less complex to configure and, from my perspective at least, is much more stable.

### URL

https://www.home-assistant.io/integrations/nest/

**Comment by frenck** [comment]
The integration is about integrating with the nest itself, not HomeKit. 
Many devices can be integrated with bridges in different ways via several bridges that expose another protocol (e.g., MQTT, HomeKit, or any other platform).

That is out of the scope of this specific integration documentation in general.

../Frenck

**Comment by jblsd** [comment]
Hi French -As an engineer, I agree that documentation should be limited to the topic at hand. As a user and smart home hobbiest, it would be useful to have a place for them to understand that there are multiple approaches possible especially when some are much less complex to set up. Is there a place on the HA site to help provide these alternatives?JoelOn Jan 7, 2023, at 13:36, Franck Nijhof ***@***.***> wrote:﻿
The integration is about integrating with the nest itself, not HomeKit.
Many devices can be integrated with bridges in different ways via several bridges that expose another protocol (e.g., MQTT, HomeKit, or any other platform).
That is out of the scope of this specific integration documentation in general.
../Frenck

**Comment by frenck** [comment]
> Is there a place on the HA site to help provide these alternatives?J

You are free to discuss those subjects, and even provide additional guides in our guides wiki on the Home Assistant community forums.

../Frenck
