### ISSUE TITLE
Need to add rustc as a dependancy for RPi 

### ISSUE THREAD

**Issue by bmwhitetx** [home-assistant/home-assistant.github.io#25627]
### Feedback

Under **Install Home Assistant Core instructions**
When doing this step:
pip3 install homeassistant==2023.1.1

I get errors about updating pip, no rust compiler etc. I updated pip but still error. Eventually worked when installing rustc. So I think you need to add rustc to this list:

**Install the dependencies:**
sudo apt-get install -y python3 python3-dev python3-venv python3-pip bluez libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf build-essential libopenjp2-7 libtiff5 libturbojpeg0-dev tzdata

### URL

https://www.home-assistant.io/installation/raspberrypi

**Comment by klaasnicolaas** [comment]
If you search for "rustc" among the old [issues](https://github.com/home-assistant/home-assistant.io/issues?q=is%3Aissue+rustc+is%3Aclosed) / pull requests you can see why we didn't add it to the list of packs to install 😉 

./Klaas

**Comment by bmwhitetx** [comment]
Ok I get it that it is advanced and depends on system but this page is is specifically for the Raspberry Pi and the standard image from them does not include it. Seems like others have the same issue. Maybe add a step that says check to see if rustc is already installed and if not install it.

**Comment by klaasnicolaas** [comment]
Some of the information is specific on that page, but installation instructions are defined elsewhere and are included on this page.

https://github.com/home-assistant/home-assistant.io/blob/current/source/installation/raspberrypi.markdown

**Comment by frenck** [comment]
> Ok I get it that it is advanced and depends on system but this page is is specifically for the Raspberry Pi and the standard image from them does not include it. 

It are generic instruction, that apply to any Python installation, including (but not limited too), the Pi.

Please note, there are many distributions available for the Pi as well, that may have different requirements.

As per documentation, if you don't know what to do, we suggest looking at an another installation method.

Thanks!

../Frenck
