### ISSUE TITLE
Is it possible to add another selection for Ecobee Integration

### ISSUE THREAD

**Issue by lapara1** [home-assistant/home-assistant.github.io#25628]
### Feedback

Currently I have been trying out the ecobee weather readings for blinds automation and was looking at the ecobee thermostat this morning and saw it was stating Mostly Cloudy on the thermostat and wanted to see if it was possible to add this on the home assistant integration, basically becoming like sunny in order to make the blinds open 100% 

Mostly Cloudy is not available in the automation menu, its either Cloudy, Partly Cloudy 

Thank you.

### URL

https://www.home-assistant.io/integrations/ecobee/

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
