### ISSUE TITLE
Shelly docs lacking

### ISSUE THREAD

**Issue by NewfD90** [home-assistant/home-assistant.github.io#25639]
### Feedback

The following info from the bluetooth integration page should be added to the Shelly Integration documentation page:

Bluetooth advertisement listening: Shelly v2 device with firmware 12.0 or later
Single active connection: not supported
Multiple active connections: not supported

### URL

https://www.home-assistant.io/integrations/shelly/

**Comment by frenck** [comment]
Does it already state that?

<img width="813" alt="CleanShot 2023-01-08 at 17 18 32@2x" src="https://user-images.githubusercontent.com/195327/211207424-e6410d1d-63ad-42eb-981a-e88c4ceaed62.png">

Maybe you missed it? Or your suggestion is not clear, in that case, your suggestion is not entirely clear to me. Could you clarify in that case?

../Frenck

**Comment by NewfD90** [comment]
This is what needs to be there:

Single active connection: not supported
Multiple active connections: not supported

**Comment by frenck** [comment]
@NewfD90 It already states it can act as a proxy for advertisements?

**Comment by thecode** [comment]
@NewfD90 it states "Active or passive listening can be enabled in the options flow", it would be complicated to detail every feature which is not supported, do you have an example another integration which states that it doesn't support active connections?

**Comment by thecode** [comment]
I do however suggest to move Bluetooth to be more up in the page so it is before advanced options

**Comment by NewfD90** [comment]
https://www.home-assistant.io/integrations/bluetooth

States that active connections are not supported, and from experience, that is true.  It'd be nice if the Shelly integration stated as such.

**Comment by thecode** [comment]
@NewfD90 I have moved the bluetooth section higher in the document. If you want to add something to the docs please edit the page and add your suggestions. Thanks 👍 

![image](https://user-images.githubusercontent.com/1858925/213264207-f184518f-9662-41b6-af07-93b10707e35b.png)
