### ISSUE TITLE
Reolink Intergration (RLC-511 & RLC-411)

### ISSUE THREAD

**Issue by B48D81EFCC** [home-assistant/home-assistant.github.io#25634]
### Feedback

Hello,

I was able to add multiple cameras of Reolink models 
- RLC-511 and
- RLC-411

I was able to watch all provides streams (main, sub, snapshot).

Best regards
Andreas

### URL

https://www.home-assistant.io/integrations/reolink#tested-models

### Version

2023.1.1

**Comment by pszypowicz** [comment]
I was able to add Reolink Duo Floodlight PoE (IPC_529B17B8MP)

**Comment by frenck** [comment]
Thanks for the reports!

I've opened up a PR to adjust the documentation 👍 

../Frenck
