### ISSUE TITLE
Dashboard cards - header|footer types?

### ISSUE THREAD

**Issue by wkearney99** [home-assistant/home-assistant.github.io#25630]
### Feedback

It'd help if the type section for a header defined what kinds of types it supports.  Picture and Button are mentioned elsewhere, but are there others?  Or just those two?

And what of the footer types?  Just graph?

I came looking there because I wanted to change how the Entities card handled the header toggle.  I wanted a toggle that didn't toggle "everything" on the card.  I managed to get to this page and then wondered if there was a toggle type for a header or just the button and picture.

Love the amazing amount of work and information that's available here, just trying to do my part to help.

### URL

https://www.home-assistant.io/dashboards/header-footer/

**Comment by balthisar** [comment]
Still relevant documentation issue.
