### ISSUE TITLE
Blueprint selectors for color temp should be using kelvin, not mireds.

### ISSUE THREAD

**Issue by themanieldaniel** [home-assistant/home-assistant.github.io#25644]
### Feedback

Home assistant has changed to using Kelvin as stated [here](https://www.home-assistant.io/blog/2022/11/02/release-202211/#color-temperatures-in-kelvin). So, the blueprint selector should also be using Kelvin, not mireds.

### URL

https://www.home-assistant.io/docs/blueprint/selectors/#color-temperature-selector

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
