### ISSUE TITLE
Now works with self-monitored plan

### ISSUE THREAD

**Issue by jimsngc** [home-assistant/home-assistant.github.io#25648]
### Feedback

I have the self-monitored plan with Simplisafe and was able to add this integration without any issues.

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2023.1.1

**Comment by jimsngc** [comment]
Might have spoken to soon.   I have all my devices showing but not getting any usage back.   As in, it's not telling me when any sensors activate...

**Comment by bachya** [comment]
@jimsngc Let me know if you get a confirmed result and if your plan is supported, I'll update the docs.
