### ISSUE TITLE
Indicate that speaker groups are not supported

### ISSUE THREAD

**Issue by fishhead2567** [home-assistant/home-assistant.github.io#25649]
### Feedback

I have tested with my speaker groups and they do not seem to be supported currently. 

Group was "common area", result was broadcast to all speakers
if I use the speakers by room, I get expected results. So "living room" and "kitchen" as targets work, but not the group with both of them.

I can file an issue against the integration, but I looked through the code and it appears to be a limitation on the google side.

### URL

https://www.home-assistant.io/integrations/google_assistant_sdk/#limitationsknown-issues

### Version

2023.1.1 os 9.4

### Additional information

I have been playing around with this in Node Red.  My old use of the cloud engine from Nabu Casa, stopped my music which was annoying. So, I switched to this. My music doesn't stop now, but my devices aren't synced, so the broadcast plays at different times in different rooms. I also can't use my groups. But.. .tradeoff is worth it for now.

**Comment by tronikos** [comment]
Not sure it's worh mentioning it in the known issues. Per the documentation, only rooms (in Google Assistant) can be set at target.

**Comment by tronikos** [comment]
@home-assistant close
