### ISSUE TITLE
DHW boiler with rs485 to ETH converter 

### ISSUE THREAD

**Issue by spikerm** [home-assistant/home-assistant.github.io#25651]
### Feedback

Hello 

i have a DHW boiler NIBE MT-WH 21
and connected a rs485 to ethernet converter to it 
is it possible to put this one in the add on 

i provided the modus list for this device 
many thnx 
 
[Modbus Tables DHWHP P607 14.04.2020.xlsx](https://github.com/home-assistant/home-assistant.io/files/10369344/Modbus.Tables.DHWHP.P607.14.04.2020.xlsx)

### URL

https://www.home-assistant.io/integrations/nibe_heatpump/

**Comment by elupus** [comment]
This need to be added as a json file here: https://github.com/yozik04/nibe/tree/master/nibe/data

**Comment by elupus** [comment]
Its not a frontend issue. So ill close this issue. Feel free to open an in issue in the linked repo. But i think you need to create the json file yourself.

**Comment by spikerm** [comment]
I will give it a try to create a json for this device
