### ISSUE TITLE
The Conditions page does not explain the "for:" attribute at all.

### ISSUE THREAD

**Issue by SkyLined** [home-assistant/home-assistant.github.io#25668]
### Feedback

I am trying to determine if `for:` matches _exactly_ or _at least_ but the documentation provides no information at all.

Say I create an automation that triggers when an event happens, but I want the action to take place only if this happens when the state of "B" has been `on` for _at least_ 5 minutes. Can I use `for:`? Or is that only true if it the state has been `on` _exactly_ 5 minutes?

### URL

https://www.home-assistant.io/docs/scripts/conditions/#state-condition

### Version

N/A

**Comment by frenck** [comment]
Hi there @SkyLined 👋 

It is: "at least". "Exactly" would be impossible as Home Assistant in an async system.

../Frenck

**Comment by SkyLined** [comment]
Thanks ../Frenck! Can the documentation be update to explain this to others as well?

**Comment by frenck** [comment]
Feel free to submit an improvement, but for what it is worth, IMHO it is logical. It is the fist time I hear this question in 5 years.

**Comment by SkyLined** [comment]
I expect an expert like you to know this and consider it logical. But I that may not be the case for new users like me. In my experience, new users tend to assume it is their inexperience that is the issue, not the lack of documentation. They will try things until it works and move on, so it is no surprise to me that you haven't had this question before: once people figure it out for themselves, they no longer have the need for it to be added to the docs.

I would like to help improve HA where possible. Because I am new to HA, the best way I can help is by pointing out where the documentation is not clear to a n00b like me, so it can be improved. If you can explain to me where the documentation lives and what the process is for suggesting an improvement, that would help me file more actionable issues in the future.

**Comment by frenck** [comment]
> I expect an expert like you to know this and consider it logical.

I don't mean it bad. I'm dead serious that this was the first time I've seen this question. From my point of view it makes sense, as a conditional check can happen at any time. Similar as one observes a state of anything in the real world at any time.

> not the lack of documentation.

> I would like to help improve HA where possible.

You did by submitting, thank you for the feedback. If this occurs more often we'll reconsider adjusting this part.

../Frenck

**Comment by SkyLined** [comment]
If you want to make it easier to get started with HA, step-by-step documentation goes a long way. Even if something seems obvious to you, it may not to somebody new to the system. If this is obvious, it makes sense to explain why so people new to HA can learn and understand more about how it works.

The way I see it, adding a few lines explaining this to the documentation should not be a large task and since it would have helped me, I assume it will help others as well (unless I am exceptionally dumb or nobody else uses this). I see no obvious reason not to do so: have you ever heard of an over-documentation system? :)

**Comment by frenck** [comment]
I understand your concerns and read your responses and posted the conclusion above.

> have you ever heard of an over-documentation system? :)

Yes. They end up being hard to main and become largely outdated. It is in general a pretty serious problem when documenting. Hence everything is a balance all the time. 

Anyways, re-raising the case won't help or change it.

As said, if this occurs more often we'll reconsider adjusting this part.

Thanks for understanding 👍 

../Frenck

**Comment by SkyLined** [comment]
I'll shut up :) But I am quite surprised that you consider it sufficiently documented, given that there is absolutely NO documentation on `for:` on that page at all.
