### ISSUE TITLE
Перестала работать интеграция на НА. В чем проблема? 

### ISSUE THREAD

**Issue by Ivan19720** [home-assistant/home-assistant.github.io#25679]
### Feedback

_edit: redacted email address_

### URL

_edit: redacted email address_

### Additional information

перестала работать интеграция

**Comment by frenck** [comment]
Sorry, we are an English-only community. If you want to report something, you have to use the English language so we can actually understand.

Thanks 👍 

../Frenck

**Comment by Ivan19720** [comment]
The integration has stopped working. Home assistant has been updated. Absolutely everything works except Gree. Can't see CooperHunter air conditioner. So far for 1 year everything has worked well
