### ISSUE TITLE
Add template config

### ISSUE THREAD

**Issue by natbesh** [home-assistant/home-assistant.github.io#25674]
### Feedback

A big issue with Amber Electric is that the price information does NOT include the network costs.
Can you please add some documentation to help users to write a template to include network prices to be able to get actual total costs.

Here's the template work done:
Between 0:00 & 14:00 general price is +3.31c, between 14:00 & 20:00 the general price is +27.8c, after 20:00 the general price is +3.31c

Template:
  - sensor:
      - name: "General_Price_C"
        unit_of_measurement: "$"
        state: >
           {% set hour= now().hour  %}
           {% if hour >= 0 and hour < 14 %}
              state: {{ states('sensor.general_price') | float + 0.0331 | round(4) }}
           {% elif hour >= 14 and hour < 20 %}
              state: {{ states('sensor.general_price') | float + 0.278  | round(4) }}
           {% elif hour >= 20 %}
              state: {{ states('sensor.general_price') | float + 0.031  | round(4) }}
           {% endif %}

### URL

https://www.home-assistant.io/integrations/amberelectric/

**Comment by madpilot** [comment]
The general price does include network costs. As you can see in this screen shot (This is my house, but yours will show similar)

![image](https://user-images.githubusercontent.com/19585/211434554-49e58ad3-8993-4054-b6ec-531fe97d9120.png)

The Spot per kwh is the current AEMO market price. Per kwh is the price you pay, including network and market fees.

**Comment by madpilot** [comment]
@home-assistant close
