### ISSUE TITLE
Template buttons do not work with trigger but this is not explained.

### ISSUE THREAD

**Issue by SkyLined** [home-assistant/home-assistant.github.io#25670]
### Feedback

When creating a `button`, you should not use the `trigger` argument. If you do, the button will not be created. There is not warning or error message and it took me a long time to figure this out. I'd like to request you explain this in the documentation to help others avoid wasting their time.

### URL

https://www.home-assistant.io/integrations/template/

### Version

N/A

**Comment by frenck** [comment]
> . There is not warning or error message and it took me a long time to figure this out. I'd like to request you explain this in the documentation to help others avoid wasting their time.

That is a bug, bugs should be fixed and not documented. In this case, the configuration should not have passed validation. Please report your issue in our core issue tracker here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by SkyLined** [comment]
Thanks ../Frenck, I've opened up [a bug there](https://github.com/home-assistant/core/issues/85622).
