### ISSUE TITLE
Support for HN8255Ws

### ISSUE THREAD

**Issue by tomasenskede** [home-assistant/home-assistant.github.io#25682]
### Feedback

Will HN8255Ws be supported in future releases?

### URL

https://www.home-assistant.io/integrations/huawei_lte

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by scop** [comment]
Anyway, device support for this integration comes directly from https://github.com/Salamek/huawei-lte-api.
