### ISSUE TITLE
Units of device class 'duration'

### ISSUE THREAD

**Issue by rgerbranda** [home-assistant/home-assistant.github.io#25681]
### Feedback

In the documentation the symbols for duration are missing. Listed are the full names only.

Please check the following thread: https://github.com/home-assistant/core/issues/85606#issuecomment-1377275594 for mapping the symbols.

### URL

https://www.home-assistant.io/integrations/sensor#device-class

**Comment by frenck** [comment]
The documentation has been adjusted (it could take a few hours before it shows up).

../Frenck
