### ISSUE TITLE
gpio group does not exist error

### ISSUE THREAD

**Issue by janbur** [home-assistant/home-assistant.github.io#25689]
### Feedback

Running 
`sudo useradd -rm homeassistant -G dialout,gpio,i2c`
returns error -group "gpio" does not exist.
Installing HA core on Orange Pi Zero.

### URL

https://www.home-assistant.io/installation/raspberrypi/#install-home-assistant-core

**Comment by frenck** [comment]
As per documentation:

![image](https://user-images.githubusercontent.com/195327/212270621-aee543c1-7c66-49dc-b182-8af525be97b0.png)
