### ISSUE TITLE
Setup of Rhasspy done without any configuration

### ISSUE THREAD

**Issue by guerda** [home-assistant/home-assistant.github.io#25683]
### Feedback

I recently tried to install Rhasspy as a new integration into my HA instance.
When I added the integration, the documentation says I should expect configuration parameters. I only got the confirmation message that I am done with installation Rhasspy. The device is shown in the device list but completely empty.

Setup of Rhasspy via Integrations:
![Screenshot of HA asking me in German if I want to setup Rhasspy](https://user-images.githubusercontent.com/230782/211605905-34197d0d-7ba2-42a5-bf1a-6a312fcbdf2f.png)

Confirmation message of "success"
![Screenshot of HA confirming me that I set up Rhasspy successfully](https://user-images.githubusercontent.com/230782/211605950-4cf4270d-e98d-40b4-8023-22daef255b2f.png)

You can see that the device does not have anything to configure.
![Screenshot of Rhasspy device in the device manager without any information or option](https://user-images.githubusercontent.com/230782/211605812-d25e6f48-0202-4bce-bf6f-735470b2fa4b.png)

Is this a documentation error? Did I miss any step? Or is this an error during the setup.

### URL

https://www.home-assistant.io/integrations/rhasspy/

### Version

 2023.1.1

### Additional information

Running on Docker with HACS, no supervisor mode.

**Comment by frenck** [comment]
> When I added the integration, the documentation says I should expect configuration parameters.

Not that is it. It sets up the HA environment for Rhasspy. It does not provide entities to control or read out.

Closing this issue, as it is not an bug.

../Frenck

**Comment by guerda** [comment]
Thank you for your quick feedback!
I was confused by the advanced setup then.

Is there any documentation for the next steps after you set up the integration? I'm somehow not sure how to proceed. 

Thanks again

Best, Philip

**Comment by frenck** [comment]
> Is there any documentation for the next steps after you set up the integration?

There is nothing to set up on the end of Home Assistant. Please consult the documentation of Rhasspy for more information on how to set up and configure Rhasspy.

../Frenck
