### ISSUE TITLE
State-badge title element does not behave as described

### ISSUE THREAD

**Issue by ggonmar** [home-assistant/home-assistant.github.io#25700]
### Feedback

as per documentation:

> **title** string (optional)
> State badge tooltip. Set to null to hide.

Setting title on my yaml as null, the tooltip does not dissapear.

### URL

https://www.home-assistant.io/dashboards/picture-elements/#state-badge

**Comment by frenck** [comment]
Hi there @ggonmar 👋 

It seems like you want to report an issue with the Home Assistant Frontend, however, you have submitted documentation feedback instead. Please report frontend issues here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck

**Comment by ggonmar** [comment]
Hey @frenck !
Partially true - it's an issue (or not developed yet?) of the code itself - but documentation should commit to actual behavior of the system, I believe...? Thus I would argue if the "Set to null to hide" should be on the documentation as for now :P

**Comment by frenck** [comment]
@ggonmar It does matter. We don't document bugs, instead we should fix those.
