### ISSUE TITLE
Add protocol and port details

### ISSUE THREAD

**Issue by pelaxa** [home-assistant/home-assistant.github.io#25702]
### Feedback

What would be great for some of these pages, would be the protocol and port being used by the integration.

I’m sure I am not alone in segregating my network, and in my case my Denon is on a different VLAN than my home assistant.  The protocol/port information would help me make sure I have the right firewall rules in place.

for example, this particular integration can use auto discovery, which would lead me to believe bonjour would be used, and I can see my denon advertising it’s http port and that port is accessible over TCP, yet HA is not auto discovering  my denon. This info would help debug as well.

thanks for all the hard work and great documentation.

### URL

https://www.home-assistant.io/integrations/denonavr/

### Version

2023.1

**Comment by frenck** [comment]
> I’m sure I am not alone in segregating my network, and in my case my Denon is on a different VLAN than my home assistant.

Home Assistant considers those advanced/non-standard use cases; out of scope for our documentation. Please consult the documentation of the device or service you are using for more information on their networking capabilities.

../Frenck

**Comment by pelaxa** [comment]
sure, but your use base are advanced users though right?  

Don't mean to drag this but someone has put in good work to support these devices and they know all of these details.  I was only suggesting to note some of these items on the documentation to help others.  Most device vendors don't make such information readily available.

For this particular example, I have seen telnet and http be mentioned as two ways that Denon AVRs are supported but I cannot tell which one `denonavr` is using.

Thanks for looking at it anyways
