### ISSUE TITLE
Some Roku Features was disabled

### ISSUE THREAD

**Issue by setterlee** [home-assistant/home-assistant.github.io#25707]
### Feedback

Apparently the Roku Developer Team said that the Build in app Play on Roku dont support play videos from third party apps anymore..

### URL

 https://community.home-assistant.io/t/play-on-roku-functionality-now-broken-devastating/480436

### Version

2022.11.0

**Comment by frenck** [comment]
Hi there @setterlee 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenc
