### ISSUE TITLE
Previous month example provides invalid template code

### ISSUE THREAD

**Issue by tmttn** [home-assistant/home-assistant.github.io#25701]
### Feedback

For the 'previous month' example, the following template code is provided: `month=now().month-1`. This doesn't work for January however, as the month value must be in 1..12, so 0 is an invalid value.

### URL

https://www.home-assistant.io/integrations/history_stats/

### Version

2023.1.2

**Comment by davel4wa** [comment]
There does not seem to be a date function available within HA that will correctly compute correctly a previous date when the date rolls over the year end. The dateutil function available in Python does this correctly, I believe. In the end I setup variables for the year and month and computed the correct year and month with a script and used those variables within the start: definition template.

**Comment by tmttn** [comment]
I made this sensor for example to figure out the number of days of last month:
```
    n_days_last_month:
      unique_id: n_days_last_month
      value_template: >
        {% set start_of_month = now().replace(day=1) %}
        {% set last_month = now().month - 1 %}
        {% set last_month_year = now().year %}
        {% if last_month == 0 %}
          {% set last_month = 12 %}
          {% set last_month_year = now().year - 1 %}
        {% endif %}
        {% set start_of_last_month = start_of_month.replace(month=last_month, year=last_month_year) %}
        {{ ((start_of_month - start_of_last_month).total_seconds() / 86400) | round }}
```

But the point of my bug report was not really to get a solution for this issue. It's just no fun to go look at some example code in the documentation, only to figure out that it doesn't work as implied. So it would be better to use another example in this case.

**Comment by davel4wa** [comment]
This is similar to what I have done. It is frustrating that HA does not currently handle this calendar operation correctly. Calendar functions to do this have been around since Hector was a pup.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
