### ISSUE TITLE
Very wrong duration given in documentation

### ISSUE THREAD

**Issue by wora55** [home-assistant/home-assistant.github.io#25715]
### Feedback

This statement is wrong:
"In the browser of your Desktop system, within a few minutes you will be able to reach your new Home Assistant on [homeassistant.local:8123](http://homeassistant.local:8123/)."
Instead of 'within a few minutes' you should write 'after about twenty minutes'

Actually it seems to be even more time. I gave up waiting and did something else instead for an hour. This error is very confusing, the first time I spent quite some time in reflashing the SDCard because I assumed something went wrong there. My wife's call to lunch finally saved me. When I came back, HA had started

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

2023.1

**Comment by frenck** [comment]
> Instead of 'within a few minutes' you should write 'after about twenty minutes'

The statement is actually correct. It will take around 2-3 minutes for port to be up and showing the installation progress.

../Frenck

**Comment by wora55** [comment]
Let me answer to this as a user not as a developer:


The time I mentioned is the time I experienced on several tries. If you open a port (as you wrote) that does not automatically allow me to address this port and get real information about the installation progress, because that information is not displayed.


The first information I was able to access was a webpage that told me, it could be up to twenty minutes before the installation was done and recommended I do something else until then. And this page was static and never changed. I only found out about the current state ('onboading'-Page) when I tried to load the same address (in another window) again after more than twenty minutes.

Seems some developer agrees with me and tried to make it easier to get a new version running for a simple user


Your answer seems to imply you did not try to check my findings for the PI4 by testing but only by looking into source code.

Wolfgang

Franck Nijhof schrieb am Donnerstag, 12. Januar 2023 19:32:33 (+01:00):



Instead of 'within a few minutes' you should write 'after about twenty minutes'

The statement is actually correct. It will take around 2-3 minutes for port to be up and showing the installation progress.

../Frenck

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Wolfgang Radke
Schubertstr. 6f
76344 Eggenstein
