### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by jaspov** [home-assistant/home-assistant.github.io#25714]
### Feedback

Had to change Ring Password. Now the integration no longer works, but can't seem to find out how to update the password?

### URL

https://www.home-assistant.io/integrations/ring

**Comment by frenck** [comment]
Hi there @jaspov 👋 

It seems like you need support or are wanting to report an issue with an Home Assistant integration.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

In case you want to report an issue with an integration, please report it here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
