### ISSUE TITLE
HASS command not found

### ISSUE THREAD

**Issue by Caztroll** [home-assistant/home-assistant.github.io#25713]
### Feedback

I am following install of HA in Ubuntu on windows WSL as per https://www.home-assistant.io/installation/windows 
All working great, until I get to the command : "HASS"  

(homeassistant) hoas@Drainspout:/srv/homeassistant$ hass
Command 'hass' not found, did you mean:
  command 'ass' from deb irpas (0.10-9)
  command 'pass' from deb pass (1.7.4-5)
  command 'sass' from deb ruby-sass (3.7.4-5)
Try: sudo apt install <deb name>
(homeassistant) hoas@Drainspout:/srv/homeassistant$ sudo hass
sudo: hass: command not found

I have dabbled in linux, but certainly very much a beginner .  check error in screen dump below. (additional info)
Also Sudo password was changed?? or doesn't seem to work in the virtual environment. 

thanks in advance for any assistance.
Jim

### URL

https://www.home-assistant.io/installation/windows

### Version

2023.1.3

### Additional information

Actually got an error on re install see end
(homeassistant) hoas@Drainspout:/srv/homeassistant$ pip3 install homeassistant==2023.1.3
Collecting homeassistant==2023.1.3
  Using cached homeassistant-2023.1.3-py3-none-any.whl (21.1 MB)
Collecting pyyaml==6.0
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
Collecting attrs==22.1.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting python-slugify==4.0.1
  Using cached python-slugify-4.0.1.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.28.1
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting yarl==1.8.1
  Using cached yarl-1.8.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (263 kB)
Collecting lru-dict==1.1.8
  Using cached lru_dict-1.1.8-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
Collecting PyJWT==2.5.0
  Using cached PyJWT-2.5.0-py3-none-any.whl (20 kB)
Collecting certifi>=2021.5.30
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting ifaddr==0.1.7
  Using cached ifaddr-0.1.7-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: pip<22.4,>=21.0 in ./lib/python3.10/site-packages (from homeassistant==2023.1.3) (22.0.2)
Collecting typing-extensions<5.0,>=4.4.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting ciso8601==2.3.0
  Using cached ciso8601-2.3.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38 kB)
Collecting bcrypt==3.1.7
  Using cached bcrypt-3.1.7-cp34-abi3-manylinux1_x86_64.whl (56 kB)
Collecting voluptuous==0.13.1
  Using cached voluptuous-0.13.1-py3-none-any.whl (29 kB)
Collecting orjson==3.8.1
  Using cached orjson-3.8.1-cp310-cp310-manylinux_2_28_x86_64.whl (143 kB)
Collecting jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting home-assistant-bluetooth==1.9.2
  Using cached home_assistant_bluetooth-1.9.2-cp310-cp310-manylinux_2_35_x86_64.whl
Collecting astral==2.2
  Using cached astral-2.2-py2.py3-none-any.whl (30 kB)
Collecting cryptography==38.0.3
  Using cached cryptography-38.0.3-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
Collecting aiohttp==3.8.1
  Using cached aiohttp-3.8.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.2 MB)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting httpx==0.23.2
  Using cached httpx-0.23.2-py3-none-any.whl (86 kB)
Collecting atomicwrites-homeassistant==1.4.1
  Using cached atomicwrites_homeassistant-1.4.1-py2.py3-none-any.whl (7.1 kB)
Collecting awesomeversion==22.9.0
  Using cached awesomeversion-22.9.0-py3-none-any.whl (12 kB)
Collecting voluptuous-serialize==2.5.0
  Using cached voluptuous_serialize-2.5.0-py3-none-any.whl (6.8 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (149 kB)
Collecting charset-normalizer<3.0,>=2.0
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting pytz
  Using cached pytz-2022.7-py2.py3-none-any.whl (499 kB)
Collecting six>=1.4.1
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cffi>=1.1
  Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting httpcore<0.17.0,>=0.15.0
  Using cached httpcore-0.16.3-py3-none-any.whl (69 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting text-unidecode>=1.3
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting h11<0.15,>=0.13
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting anyio<5.0,>=3.0
  Using cached anyio-3.6.2-py3-none-any.whl (80 kB)
Using legacy 'setup.py install' for python-slugify, since package 'wheel' is not installed.
Installing collected packages: voluptuous, text-unidecode, rfc3986, pytz, lru-dict, ifaddr, ciso8601, voluptuous-serialize, urllib3, typing-extensions, sniffio, six, pyyaml, python-slugify, PyJWT, pycparser, orjson, multidict, MarkupSafe, idna, home-assistant-bluetooth, h11, frozenlist, charset-normalizer, certifi, awesomeversion, attrs, atomicwrites-homeassistant, async-timeout, astral, yarl, requests, jinja2, cffi, anyio, aiosignal, httpcore, cryptography, bcrypt, aiohttp, httpx, homeassistant
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/srv/homeassistant/lib/python3.10/site-packages/voluptuous'
Check the permissions.

**Comment by frenck** [comment]
> Using legacy 'setup.py install' for python-slugify, since package 'wheel' is not installed.

Your Python environment is missing the Python Wheels. Please make sure that is installed.

../Frenck
