### ISSUE TITLE
Put a warning that ADS integration is not working on docker installation

### ISSUE THREAD

**Issue by birdie60** [home-assistant/home-assistant.github.io#25727]
### Feedback

Running HA in docker, the ADS integration is broken due to a problem with pyads / adslib compilation. At least for the raspberry pi version of docker image - did not test other docker environments.

Let people know that the last working image for this environment is HA 2022.6.7.

### URL

https://www.home-assistant.io/integrations/ads/

### Version

2022.6.7

### Additional information

See https://github.com/home-assistant/core/issues/74952 for a description of the glitch and a possible workaround.
Documentation should mention broken components to prevent disappointments.

**Comment by frenck** [comment]
It is a bug, which should be solved, not documented.

Please follow the issue you've linked for updates.

Thanks  👍 

../Frenck
