### ISSUE TITLE
Tell people about docker images for other platforms like Raspberry Pi

### ISSUE THREAD

**Issue by birdie60** [home-assistant/home-assistant.github.io#25726]
### Feedback

On this page, see below, there is not a single mentioning of the platform. Therefore, many Raspberry Pi users will download the wrong docker image. Please, insert a info box at the beginning of this page with links to other platforms.

### URL

https://www.home-assistant.io/common-tasks/container/

### Additional information

My docker command is for e.g.:
`docker pull homeassistant/raspberrypi3-homeassistant:stable`

and not the one mentioned on the webpage:
`docker pull ghcr.io/home-assistant/home-assistant:stable`

I came to the webpage via Google search for HA update, did not mention my platform raspberry pi there.

**Comment by frenck** [comment]
`ghcr.io/home-assistant/home-assistant:stable` is a multi-arch manifest.

The use of the other isn't needed anymore. The documentation is, therefore, correct.

../Frenck
