### ISSUE TITLE
Clickatell documentation missing password

### ISSUE THREAD

**Issue by casperse** [home-assistant/home-assistant.github.io#25736]
### Feedback

# Example configuration.yaml entry
notify:
  - platform: clickatell_central
    username: !secret clickatellcentralusername
    password: !secret clickatellcentralpassword
    api_key: !secret clickatellcentralapikey
    recipient: !secret phonenumber

### URL

https://www.home-assistant.io/integrations/clickatell/

**Comment by frenck** [comment]
I've looked at the codebase as well, but there is no password in the Clickatell integration.
Adding it doesn't have any effect, as it isn't used by this integration.

Could you clarify?

../Frenck

**Comment by casperse** [comment]
I just did a test, and I think the integration is broken, clickatell have updated their SMS gateway and requires more information.
(My comment was based on a old support thread)

My testing shows that the current documentation & integration is broken.
Seems Clicksend is the preferred solution today.
