### ISSUE TITLE
How do I create an event in Local Calendar?

### ISSUE THREAD

**Issue by sidleach** [home-assistant/home-assistant.github.io#25743]
### Feedback

I have installed Local Calendar.  I have added a "calendar" card to my UI (Lovelace).  But I do not see any documentation on how to create an event in the calendar.

### URL

https://www.home-assistant.io/integrations/local_calendar/

### Version

2023.1.4

**Comment by allenporter** [comment]
Local calendar is a type of calendar, so check out the docs for the main calendar integration

**Comment by allenporter** [comment]
See https://www.home-assistant.io/integrations/calendar/

**Comment by sidleach** [comment]
Allen:

I would like to make it clear that I very much appreciate your efforts in connection with Home Assistant.  Thank you.

Best regards,

Sid Leach



On Jan 13, 2023, at 2:22 PM, Allen Porter ***@***.***> wrote:


See https://www.home-assistant.io/integrations/calendar/ <https://www.home-assistant.io/integrations/calendar/>

**Comment by allenporter** [comment]
Thank you!
