### ISSUE TITLE
modbus page logger example should set default to avoid excess logging

### ISSUE THREAD

**Issue by davidbbs** [home-assistant/home-assistant.github.io#25747]
### Feedback

At: https://www.home-assistant.io/integrations/modbus/#opening-an-issue

The example should be changed to include "default:warning" to avoid all components being switched from the default "warning" to "info" when "logger" is added. If this is not done, the log will be filled with info level messages from every other component, making it difficult to find the desired messages

logger:
  default: warning <--add this
  logs:
    homeassistant.components.modbus: debug
    pymodbus.client: debug

### URL

https://www.home-assistant.io/integrations/modbus/#opening-an-issue

### Version

2023.1.3

**Comment by janiversen** [comment]
Pull requests are welcome.
