### ISSUE TITLE
Quotas

### ISSUE THREAD

**Issue by chrisschoonens** [home-assistant/home-assistant.github.io#25744]
### Feedback

Hi! I've been trying the new Google Assistant SDK. I am thererfor new to the Google Cloud Console and found out it has paid quotas. I can't really find out if the Google Assistant SDK uses paid quotas. Could you update the documentation with (a link to) this information?

Thank you in advance.

Kind regards,
Chris

### URL

https://www.home-assistant.io/integrations/google_assistant_sdk/

**Comment by tronikos** [comment]
I'm not familiar with paid quotas. I've been using other Google integrations (Google Assistant, Calendar, and Sheets), that also need a Google Cloud project, for months, and I haven't had any charges. None of the other Google integrations seem to bother mentioning quotas in their documentation. Not sure what I could write in the documentation anyway. Closing this.

**Comment by tronikos** [comment]
@home-assistant close
