### ISSUE TITLE
Hyper-V missing steps to enable connection to mobile app

### ISSUE THREAD

**Issue by darrinm81** [home-assistant/home-assistant.github.io#25745]
### Feedback

Once the Hyper-V virtual machine is setup, it cannot be accessed outside your machine such as mobile phone on the same network. The below steps allow users to access HA virtual machine instance.

Create new external virtual switch:
Start > Hyper-V Manager
Virtual Switch Manager
New Virtual Network Switch > External
Connection Type = External Network (Your Network Connection)

Change your Virtual Machine to External Network adapater:
Virtual Machine settings > Network Adapter
Network Adapter = External

### URL

https://www.home-assistant.io/installation/windows

**Comment by frenck** [comment]
That sounds odd? That should not be needed when using a bridged virtual switch as the current documentation/instructions state.

Are you sure you did that?

../Frenck

**Comment by darrinm81** [comment]
Which instructions?

The 'HYPERVISOR SPECIFIC CONFIGURATION' instructions don't mention anything about 'Configure Networking' where Hyper-V asks you to specify your connection. 'Default Switch' didn't work in my instance. I needed to create an external adapter.

**Comment by frenck** [comment]
> The 'HYPERVISOR SPECIFIC CONFIGURATION' instructions don't mention anything about 'Configure Networking

It does, screenshot from our current documentation:

![image](https://user-images.githubusercontent.com/195327/212543899-ace14bbf-ad3c-499f-91fd-781d63e302cc.png)

../Frenck

**Comment by darrinm81** [comment]
[](url)I see. I found that step unclear.

I used the New Virtual Machine Wizard in Hyper-V manager.

I only had a choice of 'Not Connected' or 'Default Switch'.

The 'Default Switch' configuration is greyed out in the Virtual Switch Manager - set to Internal Network.

It worked on the local desktop but not on connected devices until I created a new Virtual Switch with External Network set.

I would suggest making it clear that without setting 'External Network' it will not work via the mobile app.

![1](https://user-images.githubusercontent.com/122655651/212544595-1400a168-80b4-4680-a638-de62ebb2da9e.PNG)

![2](https://user-images.githubusercontent.com/122655651/212544598-9e4a5c38-e566-4d2c-8339-8d7099056e3c.PNG)

**Comment by frenck** [comment]
> I would suggest making it clear that without setting 'External Network' it will not work via the mobile app.

That comment make not a lot of sense to me, as a bridge network should be used (in such cases, all your comments do not apply).

../Frenck

**Comment by darrinm81** [comment]
Of all the initial setup, this one took me the longest to solve. And it wasn't easily solved via main HA forums. If someone is playing with virtual machines for the first time, this felt unclear.

Agreed bridged make sense. But it doesn't align to the default setting in Hyper V.

**Comment by frenck** [comment]
>  But it doesn't align to the default setting in Hyper V.

Hence it is in the instructions. 🤷
