### ISSUE TITLE
Several products have limitations in use of specific Function codes. 

### ISSUE THREAD

**Issue by SalifTraoure** [home-assistant/home-assistant.github.io#25750]
### Feedback

For instance, my device has only support for FC16 and not FC6 or FC10 when writing command. Googling this I am not the only one dealing with such constraint. So that the information at least is clear on how this works when using the write commands is useful to avoid having to debug to reverse engineer. 

That said, to be able to pass an optional argument on which Function Code to use for modbus seem like a good idea. 

### URL

https://www.home-assistant.io/integrations/modbus/#configuring-data_type-and-struct

### Version

2023.1.4

**Comment by SalifTraoure** [comment]
( I would like to use the modbus climate to pass the single holding register back using FC16 )

**Comment by janiversen** [comment]
This is not a documentation problem (this is a repo for documentation).

That being said the modbus integration do support FC16, just call with a list of int then it will use FC16

**Comment by janiversen** [comment]
I am not sure if modbus climate supports it, but you can always do the call directly.

**Comment by SalifTraoure** [comment]
I guess my comment was including both a feature request as well as requesting more detailed documentation for the existing features.  Doc markup suggestions: 
" Modbus write documentation - Control over function code when writing
By default the write_modbus function uses FC6 when handed a single value. If multiple  (or single) values are passed with a list it will use FC16. 
--- for the documentation of modbus climate--- 
Modbus climate will use FC6 when writing back to the holding register. There is no option to force FC16 "

If you also are responsible for the features, consider it a feature request to add the option to use FC16 in modbus climate for single register ( there is no documentation to demonstrate how if it is supported) . Happy to receive tips for workarounds to use modbus climate with FC16 although I know this isn´t a support channel.

**Comment by janiversen** [comment]
Please raise a feature request in the home assistant repo, this repo is for documentation only.

If you think the documentation should be amended for the write_modbus call, then please make a pull request.

I already gave you the tip use the write_modbus call to write directly.

**Comment by janiversen** [comment]
Closing as it seems to be a non-issue (FC-16 is supported and documented for write_modbus). FC16 is currently not supported for the climate entity, so the documentation is correct.
