### ISSUE TITLE
Add example to documentation

### ISSUE THREAD

**Issue by airmaxx** [home-assistant/home-assistant.github.io#25764]
### Feedback

Hi,
I'm new to home assistant (switching from openhab), so I might not know very well general handling.

I'd like to switch to an HDWI Input via an automation. I can see in developer view, that there is the property "source_list", yet I do not know how to set this property in an automation. Would be great to add this as an example to the documentation. I am probably also spoiled by the many examples in the Openhab documentation.

### URL

https://www.home-assistant.io/integrations/yamaha_musiccast/

### Version

2023.1.4

**Comment by frenck** [comment]
Hi @airmaxx 👋 

The Yamaha MusicCast integration provides a media player entity (which has the source list property). Home Assistant standardizes data points, and capabilities using generic/standard entity types, like the light, switch, sensor, and media player entities.

Those work the same, regardless of the integration used. The documentation of Yamaha MusicCast provides documentation on the integration specifics, for specific and details of media players entities in general, please check this page:

<https://www.home-assistant.io/integrations/media_player>

../Frenck
