### ISSUE TITLE
Schedule - more granularity

### ISSUE THREAD

**Issue by drirwin** [home-assistant/home-assistant.github.io#25769]
### Feedback

I am new to Home Assistant and am impressed with the power and flexibility I have seen so far.  My goal is to **move from Homeseer to HA**.  I have several key automations that exist in Homeseer that I cannot do without.  Many of them use a construct similar to schedule.  However, Homeseer's implementation uses five minute time devisions alowing for much finer event timing.  I am assuming the same could be accomplished by implementing schedules in yaml.  It would be nice having control over this level of granularity in the Schedule helper UI.  Perhaps this is already in development as I understand the Schedule helper is realitively new.  Thanks in advance for considering this enhancement...  Don Irwin

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2023.1.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
