### ISSUE TITLE
ISS integration installation Notes

### ISSUE THREAD

**Issue by Whiteheat1000** [home-assistant/home-assistant.github.io#25778]
### Feedback

as per the documentation I have added the map option, but there is no indication on what to do next. How do I add it to lovelace, does it appear as an entity? I am unable to find anything about the ISS to add to a lovelace card.
Also it is not apparent where youi are supposed to enter the latitude and longitude details.
More explanation is required please.

### URL

https://www.home-assistant.io/integrations/iss/

### Version

2023.1.4

**Comment by frenck** [comment]
> s per the documentation I have added the map option, but there is no indication on what to do next.

Nothing?

> How do I add it to lovelace, does it appear as an entity? I am unable to find anything about the ISS to add to a lovelace card.

The map option, makes it show up on the Map. None of these questions apply?

> More explanation is required please.

I don't think so to be honest. "Show on map" means... it will show up on the map 🤷 
It ain't more complicated than that.


![CleanShot 2023-01-16 at 08 51 50](https://user-images.githubusercontent.com/195327/212625238-e9453dc6-ebd8-4e6a-9fd0-fabc15da1eab.png)

**Comment by Whiteheat1000** [comment]
![image](https://user-images.githubusercontent.com/101639100/214486301-e5393a5f-5d4c-4b5f-ac06-4da2b97b1e6c.png)

I selected Map option - doesnt seem to appear on the map.
![image](https://user-images.githubusercontent.com/101639100/214485804-323cc0e9-6101-44a5-a992-d386fafeafaa.png)
Also you didnt answer about where the lat and long appear.
Please help

**Comment by DurgNomis-drol** [comment]
@Whiteheat1000 you can find lat and long if you click on it and then click on attributes

**Comment by Whiteheat1000** [comment]
And this would be by clicking on the icon on the map?  The non existant
icon? I did send a pic about that.
Regards.
Murray

**Comment by DurgNomis-drol** [comment]
Please follow the instructions as described on [this](https://www.home-assistant.io/integrations/iss) page. If you want it to show up on the map, read the instruction in the yellow box.
