### ISSUE TITLE
None of the examples work

### ISSUE THREAD

**Issue by elmesito** [home-assistant/home-assistant.github.io#25771]
### Feedback

None of the examples provided in the scripts documentation can be saved into a script when copied and pasted into the editor in yaml mode.
The error given is: "Message malformed: extra keys not allowed @ data['script']"

Sadly this kind of documentation failure is very common in the HA documentation.

### URL

https://www.home-assistant.io/docs/scripts/

### Version

2023.1.4

**Comment by frenck** [comment]
The examples are part of scripts; have you incorporated them into your script?

I've looked at the page but didn't spot an incorrect one. Could you provide an example that isn't correct? Or, even better, suggest a more concrete improvement.

../Frenck

**Comment by elmesito** [comment]
As new user I am trying to understand how things work, and so far the documentation has been more of a hinder than helpful. thank fully there is a large community of users that provide a large amount of functioning examples, or examples requiring minor adaptation.
When it comes to scripts all I have found is very vague, so I have to use the official documentation, but that is even less clear.

One example that doesn't work is the one marked as [Full-configuration](https://www.home-assistant.io/integrations/script/#full-configuration). My expectation that the page should have as a bare minimum an example that I can copy and paste as a yaml. and should not at least be correct in syntax so that it can at least be saved before I break it with my inexperience, but that is not the case.
Are my expectations set too high? Can't this yaml just be pasted in the UI?

Thank you for your and the team's great work. HA Rocks!

**Comment by tmttn** [comment]
The example you mention seems to work for me @elmesito.

As described at the top of the documentation page, the examples are written for YAML file configuration. Hence there's some additional headings like `script:` and `wakeup:`. If you are getting started, I strongly suggest trying to create your script with the UI first, and then go see what the YAML editor result is. This is a great way to start learning the YAML syntax for scripts and automations.

I just created a new script from the UI, went into YAML mode and pasted the script as following and this works as expected:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/1706040/215054285-13343dc3-fe8a-4d9e-a561-f323e6fae986.png">

**Comment by elmesito** [comment]
> As described at the top of the documentation page, the examples are written for YAML file configuration. Hence there's some additional headings like script: and wakeup:.

Thanks, that is helpful. Maybe this should be added as a note in the script documentation, as a novice will not know this.
