### ISSUE TITLE
I don't get what to do. I miss proper Use cases. Instead I see only generic settings/setups. If i try something myself it doesnt work as shown in the examples

### ISSUE THREAD

**Issue by Geertseb** [home-assistant/home-assistant.github.io#25783]
### Feedback

I don't get what to do. I miss proper Use cases. Instead I see only generic settings/setups. If i try something myself it doesnt work as shown in the examples

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2023.1.4

**Comment by frenck** [comment]
Hi there @Geertseb 👋 

Your feedback description is very generic, and therefore, I'm not able to understand what it is you are trying to say. Could you clarify your feedback to be a little more concrete?

Thanks 👍 

../Frenck

**Comment by RoisinDubh79** [comment]
Basically, he has the same issue I do.

The Calendar Event Light Schedule example provided on the page is incomplete.

If you copy the YAML and paste it into your setup, making adjustments for your own specific lights and calendar, it throws an error and doesn't give any clue to which line is the offending line of YAML.
