### ISSUE TITLE
"With family" setting during initial login/setup

### ISSUE THREAD

**Issue by jamiepentland** [home-assistant/home-assistant.github.io#25792]
### Feedback

It's unclear what the "With family" checkbox does in the initial setup.

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2023.1.4

**Comment by frenck** [comment]
If you want to include family from your iCloud account 🤷 

I'm not really sure how I could better explain it...

**Comment by jamiepentland** [comment]
Having now played with this and understanding the feature, consider adjusting the verbiage of this tickbox to use Apple's terminology:

"Include members of iCloud Family Sharing group."

I think this would also benefit from a link to a page explaining this feature, such as: https://www.apple.com/family-sharing/

Hope this is helpful feedback.

**Comment by frenck** [comment]
> Having now played with this and understanding the feature, consider adjusting the verbiage of this tickbox to use Apple's terminology:

That is not a documentation change, but an change to the integration. For which this is not the issue tracker.

../Frenck

**Comment by jamiepentland** [comment]
Ah, ok. Not quite sure how to approach this, since this is my first time using github, so grateful for any guidance on how I can share this feedback with the right people, so that others may find this clearer in the future. Thank you in advance

**Comment by frenck** [comment]
I think the best options are to raise an issue on our Core repository (where our integrations are maintained).

https://github.com/home-assistant/core/issues

I will close the issue on this end in the mean time.

../Frenck
