### ISSUE TITLE
Missing Login Credentials for SSH on Homeassistant OS 9.4 - Raspberry Pi Release

### ISSUE THREAD

**Issue by SaschaMuehl** [home-assistant/home-assistant.github.io#25802]
### Feedback

Can sbd. tell me the SSH-Login credentials for the Raspberry Pi instance? I need a direct connection via WINSCP and Putty (don't want to use the online SSH-Terminal provided by hassio).

This is the release:
https://github.com/home-assistant/operating-system/releases/download/9.4/haos_rpi4-64-9.4.img.xz

Expected (but not working): 
Username: pi
Passwort: raspberry
Port: 22

### URL

https://github.com/home-assistant/operating-system/releases/download/9.4/haos_rpi4-64-9.4.img.xz

### Version

OS 9.4.

**Comment by frenck** [comment]
> SSH-Login credentials for the Raspberry Pi instance? 

There is none.

For more information on development of the OS, check out our developer docs:

<https://developers.home-assistant.io/docs/operating-system>

../Frenck
