### ISSUE TITLE
How do I remove the sensor from my Map page?

### ISSUE THREAD

**Issue by geokscott** [home-assistant/home-assistant.github.io#25809]
### Feedback

The Purpleair sensor I'm monitoring is showing up on my Map page. I cannot figure out a way to hide it from the Map???

### URL

https://www.home-assistant.io/integrations/purpleair/

### Version

2023.1.5

**Comment by bachya** [comment]
This feature is not currently implemented; it's on my todo list.

**Comment by frenck** [comment]
Alright, this thus ends up not being a documentation issue.
For that reason, I'll go ahead and close this issue on this end.

../Frenck
