### ISSUE TITLE
Issues with login

### ISSUE THREAD

**Issue by mobilejray** [home-assistant/home-assistant.github.io#25818]
### Feedback

At this point, I've gone in to my SwitchBot app and reset the password.  My known user name and verified working password does not work in the initial configuration, receiving this message; "Authentication failed: Failed to authenticate: An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Incorrect username or password."

Not, I admit, it wasn't clear if I should use my full email address but I tried both ways, same error.

Of course I've tried completely removing the plugin, rebooting the pi, reinstalling and get the same error.  I then configured a different reaspberry pi and microsd and in the end, the same issue.

Help.

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.1.5

### Additional information

I'm not a standard user, and I'm happy to test anything you'd like me to.  Thanks.

**Comment by dsypniewski** [comment]
Have you tried with the first letter of your email capitalized? I've seen reports from some people that it was the case for them.

**Comment by mobilejray** [comment]
I don't know why that worked, but yes, using a capital letter on the first letter of my email address did the trick.  Thank you!!!

**Comment by dsypniewski** [comment]
I'm starting to suspect that it's something to do with auto-correct on phones wanting to capitalize the first letter of most text inputs and then SwitchBot doing lowercase on the emails when displaying them.
