### ISSUE TITLE
Supervisor add-on documentation

### ISSUE THREAD

**Issue by sergeant82d** [home-assistant/home-assistant.github.io#25828]
### Feedback

The documentation page for the Supervisor add-on which you get when clicking the link from the "add integration" from "settings" lists a series of items.

*************
You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information.
*************

 There is *NO* documentation there on *WHAT* to enter into configuration.yaml. Do I just copy/paste the different services list?

*************
[Services](https://www.home-assistant.io/integrations/hassio#services)
[Service hassio.addon_start](https://www.home-assistant.io/integrations/hassio#service-hassioaddon_start)
[Service hassio.addon_stop](https://www.home-assistant.io/integrations/hassio#service-hassioaddon_stop)
[Service hassio.addon_restart](https://www.home-assistant.io/integrations/hassio#service-hassioaddon_restart)
[Service hassio.addon_stdin](https://www.home-assistant.io/integrations/hassio#service-hassioaddon_stdin)
[Service hassio.addon_update](https://www.home-assistant.io/integrations/hassio#service-hassioaddon_update)
[Service hassio.host_reboot](https://www.home-assistant.io/integrations/hassio#service-hassiohost_reboot)
[Service hassio.host_shutdown](https://www.home-assistant.io/integrations/hassio#service-hassiohost_shutdown)
[Service hassio.backup_full](https://www.home-assistant.io/integrations/hassio#service-hassiobackup_full)
[Service hassio.backup_partial](https://www.home-assistant.io/integrations/hassio#service-hassiobackup_partial)
[Service hassio.restore_full](https://www.home-assistant.io/integrations/hassio#service-hassiorestore_full)
[Service hassio.restore_partial](https://www.home-assistant.io/integrations/hassio#service-hassiorestore_partial)
*************

Or what? Pretty much all the different documentaion pages are much the same - there is a list of different things, but no explanation of what to do with them, how to configure them, etc.

Thanks for your time.
Brad Hedges
Stratford, Oklahoma, USA

### URL

https://www.home-assistant.io/integrations/hassio/

### Version

2023.1.5

**Comment by dannytsang** [comment]
@sergeant82d are you looking to install supervisor which gives you things like Add-ons in settings?
