### ISSUE TITLE
Withings Sleep Mat not working

### ISSUE THREAD

**Issue by crewmate1st** [home-assistant/home-assistant.github.io#25839]
### Feedback

I found that there is an issue with the way the External URL is setup for withings to work properly.  I had to manually change the "Home Assistant URL" in the Settings->System->Network.  Before I had the internet checked to use Home Assistant Cloud as I subscribe to NabuCasa.  However, this wasn't allowing withings to work.  So I unchecked the box and manually entered the webaddress for my NabuCasa account.  I rebooted and withings started working properly.  It now reports the in_bed sensor data correclty.

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2023.1.5

### Additional information

I'm currently using 2023.1.4 Core but will update to the latest and retest

**Comment by frenck** [comment]
Hi there @crewmate1st 👋 

It seems like you want to report an issue with an Home Assistant integration, but you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
