### ISSUE TITLE
delete entities

### ISSUE THREAD

**Issue by samtrois** [home-assistant/home-assistant.github.io#25832]
### Feedback

I would relly appreciate a way to remove these doubled up 'read-only' entities

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2023.1.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
