### ISSUE TITLE
How to edit in yaml switchbot entities ?

### ISSUE THREAD

**Issue by Sergio1616** [home-assistant/home-assistant.github.io#25838]
### Feedback

Hello,
Can you explain me where is the hub to enter the yaml for the entities ?
Thank you.
Cordially

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.1.5

**Comment by frenck** [comment]
> enter the yaml for the entities ?

This integration cannot be set up or managed via YAML. Please use the UI instead.

../Frenck
