### ISSUE TITLE
how to disable media on the left menu for all users

### ISSUE THREAD

**Issue by augustose** [home-assistant/home-assistant.github.io#25840]
### Feedback

By reading the manual, I can't tell how to disable the media option in the left menu for all the users.
It would be great if it's possible to disable it to make it clear in the documentation.
Thank you guys so much for this amazing project

### URL

https://www.home-assistant.io/integrations/media_source/

### Version

2023.1.5

**Comment by augustose** [comment]
problem of everybody having access to all the cameras, which is not what I wanted, and I solved it by configuring that in Unifi protect
https://docs.google.com/document/d/1HMuBrnpzmKnBPGRvxYg32z8fE9bEcscURbTi4TAw-Uo/edit?usp=sharing

**Comment by frenck** [comment]
> By reading the manual, I can't tell how to disable the media option in the left menu for all the users.

It isn't documented, because you can't.
