### ISSUE TITLE
need to add this to documentation, or reopen the bug

### ISSUE THREAD

**Issue by dima-nixx** [home-assistant/home-assistant.github.io#25842]
### Feedback

[simse](https://github.com/simse) commented [on Dec 9, 2022](https://github.com/home-assistant/core/issues/81158#issuecomment-1344586029)
The Xiaomi TV integration only supports Xiaomi TVs running MIUI. I'm sorry, I thought it said that in the documentation.

### URL

https://www.home-assistant.io/integrations/xiaomi_tv/

### Version

2023.1.5

**Comment by simse** [comment]
You are free to open a PR adding the detail to the documentation. The file is here: https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/xiaomi_tv.markdown.

However, I would like to make it crystal clear that **there is no bug to fix**, so reopening the issue does not make any sense.

**Comment by simse** [comment]
@home-assistant close
