### ISSUE TITLE
Switchbot Lock stuck on "locking" status

### ISSUE THREAD

**Issue by federicotravaini** [home-assistant/home-assistant.github.io#25859]
### Feedback

I successfully configured a Switchbot Lock through the native integration using an ESP32 as a Bluetooth proxy. The device is working properly, allowing me to open and close the door, but often after giving the lock command, the door closes but the status on Home Assistant remains fixed at "locking". If I try to give the lock command again, nothing happens, but if I first do an unlock and then a lock, it fixes the problem.
I am available to provide additional useful data to resolve this issue.

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.1.6

**Comment by federicotravaini** [comment]
I did some test and here's what I found out: if I manually lock/unlock the door, the entity status is not updated to reflect the real state of the lock, while in the switchbot app the status is correct.
Might be that via BT there's no "pull" to read the status?

**Comment by federicotravaini** [comment]
After more tests I can confirm that the issue is related to the BT comunication not pulling the status. Reloading the integration fixes the issue, so for now I have an automation that gets triggered when the door is closed and it just reloads the integration using `homeassistant.reload_config_entry`

**Comment by frenck** [comment]
Hi there @federicotravaini 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix an integration issue.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
