### ISSUE TITLE
disable / enable via HA

### ISSUE THREAD

**Issue by ffssam** [home-assistant/home-assistant.github.io#25854]
### Feedback

If i disable adguard in home assistant, then enable it, the parental control stays disabled.

Even if i manually toggle it, it stays disabled.

I have to go into adguard itself and enable it from General Settings to stick.

Apart from that it works as expected.

### URL

https://www.home-assistant.io/integrations/adguard/

### Version

2023.1.5

**Comment by frenck** [comment]
Hi there @ffssam 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
