### ISSUE TITLE
insufficient instructions

### ISSUE THREAD

**Issue by Domingato** [home-assistant/home-assistant.github.io#25855]
### Feedback

It says "Follow the instruction on screen to complete the set up". But there's no instruction at all. 
There are spots to put host, port, username and password.
Once you look in the app you can find pretty easily what username and password is, because you must set them up yourself. But one has to guess. What is disturbing though is "host". How can I find this? What should I put there? I have no clue. But I'm told to "follow the instructions". That is not cool.

### URL

https://www.home-assistant.io/integrations/android_ip_webcam/

### Version

2023.1.6

**Comment by frenck** [comment]
> What is disturbing though is "host".

"Host" is a really general computer term used since the 70s. It refers to the device, or machine that provides the service you are trying to integrate Home Assistant with. A more technical explanation could be: the IP-Address, hostname, or FQDN pointing to the device running the Android IP Webcam application.

../Frenck

**Comment by Domingato** [comment]
Thank you. I figured it out but I tried by putting the IP address as it
shows on the phone screen with the http or https prefix. Which doesn't
work. I just didn't know that I should start right away with the numbers.
It would have helped if it was explicitly mentioned in the docs, since all
the HA users have not studied programming.

Thank you for your quick response.


Le ven. 20 janv. 2023 05 h 18, Franck Nijhof ***@***.***> a
écrit :

**Comment by frenck** [comment]
>  I figured it out but I tried by putting the IP address as it
shows on the phone screen with the http or https prefix.

http or https prefixes are URLs (of which host is part of, but that is not what the field asks for... it asks for an host, not an URL).

> It would have helped if it was explicitly mentioned in the docs

It already does: Host.

> since all the HA users have not studied programming.

That is why "Host" is used, and not terms like FQDN. It is a universal, generally accepted, normal term. It is non-technical already. It is just as normal as, for example, Wi-Fi network (which SSID would be the more technical description).

../Frenck
