### ISSUE TITLE
Juice Pass

### ISSUE THREAD

**Issue by AnnoniFaustoOutlook** [home-assistant/home-assistant.github.io#25860]
### Feedback

Hi, i'have a new wallbox enel-x juice but is not possible to use it in juice net . Enel say that is deprecated in a new model of wallbox suggest to use instead  new portal enel-x juice pass. The box id is not compatible with juicenet and this doesn't work in home assistant.
Is possible to integrate new portal juice pass?
Thanks 
Best regards 
Annoni Fausto
Italy

### URL

https://www.home-assistant.io/integrations/juicenet/

### Version

2023.1.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
