### ISSUE TITLE
New images Haspbian not working

### ISSUE THREAD

**Issue by tureq80** [home-assistant/home-assistant.github.io#2586]
After launching my new haspbian downloaded from the site. New installation and such flowers? Nobody checked it out.

```
Traceback (most recent call last):
  File "/srv/homeassistant/bin/hass", line 7, in <module>
    from homeassistant.__main__ import main
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/__main__.py", line 11, in <module>
    from typing import Optional, List
ImportError: No module named 'typing'
```

Why ? Please help me...

**Comment by DavidDeSloovere** [comment]
This is the issues for the website (home-assistant.io). Your question is about home assistant itself. Please post it in the appropiate repo (https://github.com/home-assistant/home-assistant) or on the forum https://home-assistant.io/help/
