### ISSUE TITLE
Missing Functionality \ configuration

### ISSUE THREAD

**Issue by shairevivo** [home-assistant/home-assistant.github.io#25877]
### Feedback

I added all the configuration listed on HA documentation.
I do not see any binary sensor only zones.
The scenario that i need this integration is to be able to put the system in suspend for all zones and resume.
I have a rain and moist sensor so when it rains == suspend 
when no moist == resume.

### URL

https://www.home-assistant.io/integrations/hydrawise/

### Version

2023.1.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
