### ISSUE TITLE
Shopping list search through the list

### ISSUE THREAD

**Issue by jesushidalgo** [home-assistant/home-assistant.github.io#25873]
### Feedback

Hello,

I am starting to use the shopping list, but I have a list of more than a hundred items, so it is difficult to find the item I want to mark as done. In the PC I can do it using the search of the browser, but in the mobile phone, with the app, it is not possible.

Would it be possible to add somehow a search functionality?

Thank you very much,

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2023.1.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
