### ISSUE TITLE
Import data from list

### ISSUE THREAD

**Issue by jesushidalgo** [home-assistant/home-assistant.github.io#25872]
### Feedback

Hello,

I am using the shopping list on my phone, but I wanted to integrate it in Home Assistant. I have installed it easily, but then I haven´t found the way to import my existing list (I have exported it in a file in text format)

I tried via the configuration, but I see it is a json file including the id, so I´d better not edit it.

I also tried using the Service, but it only allows one item at a time.

Would it be possible to add the functionality to add several items to the list at once?

Thank you very much

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2023.1.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
