### ISSUE TITLE
Gauches

### ISSUE THREAD

**Issue by F8VPE** [home-assistant/home-assistant.github.io#25874]
### Feedback

Why can't I start a gauche with a negative value, example : Temperature 'freezing' starting with -20 untill 0° and from 0 to 19 'cold' and so on.

### URL

https://www.home-assistant.io/dashboards/gauge/

### Version

2023.1.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
