### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by digdilem** [home-assistant/home-assistant.github.io#25886]
### Feedback

Just wanted to say thank you for providing this extension. Even though I've been using HA for years, I don't think I've come across another that "just works" so easily. I know that to provide that sort of user experience can take a lot of work behind the scenes, so genuinely thankful that this works so well. 

### URL

https://www.home-assistant.io/integrations/life360/

### Version

2023.1.6

**Comment by frenck** [comment]
Thanks for your kind words!

The codeowner (@pnbruckner) has been notified of your thank you note by the mention above.

👍 

../Frenck
