### ISSUE TITLE
Plant Monitor seems to be addable from the UI. 

### ISSUE THREAD

**Issue by make-all** [home-assistant/home-assistant.github.io#25883]
### Feedback

 Is the documentation, which talks exclusively about yaml config, out of date?  When I go to Settings / Devices & Services, Plant Monitor shows up in the Add Integration options, so it seems to also be configurable from the UI.  Is yaml config deprecated, as it is for many other integrations? Should this be mentioned in the docs?

### URL

https://www.home-assistant.io/integrations/plant/

### Version

2023.1.6

**Comment by frenck** [comment]
It isn't configurable from the UI.

Also confirmed by source: <https://github.com/home-assistant/core/tree/dev/homeassistant/components/plant>, `config_flow.py` is missing (which is the UI part).

The existing documentation is correct.

../Frenck
