### ISSUE TITLE
Youtube Video casting Guide incomplete

### ISSUE THREAD

**Issue by Ryu945** [home-assistant/home-assistant.github.io#25892]
### Feedback

Currently, the only documentation on how to play Youtube videos is with Chromecast.  There isn't any documentation on how to do this with WebOS or Android TVs.  The documentation on how to do this on Chromecast isn't sufficient for figuring this out on these other two platforms.

edit:  There also isn't any documentation on how to play Youtube videos on Roku.

### URL

https://www.home-assistant.io/integrations/cast/#example

**Comment by frenck** [comment]
> There isn't any documentation on how to do this with WebOS or Android TVs

This page is about chromecast using the cast integration. Android TV support chromecast, the examples are exactly the same in those cases.

WebOS is something else and not related to the cast integration (thus not listed on this page).

../Frenck

**Comment by Ryu945** [comment]
> This page is about chromecast using the cast integration. Android TV support chromecast, the examples are exactly the same in those cases.

It was the closest relevant thing I could find in the documentation.

> WebOS is something else and not related to the cast integration (thus not listed on this page).

Is HomeAssist not capable of playing a particlar Youtube video on the WebOS Youtube app.   This wasn't about casting but playing Youtube videos in the Youtube app on different platforms.  I also noticed I forgot to add Roku to the list of devices so fixing the original post.

**Comment by frenck** [comment]
> It was the closest relevant thing I could find in the documentation.

Ok, I don't see how something that is "closest" to any functionality you want should list non-relevant information that is not actually related.

> This wasn't about casting but playing Youtube videos in the Youtube app on different platforms.

Yet, your comment is made on the Google Cast page...

> Is HomeAssist not capable of playing a particlar Youtube video on the WebOS Youtube app.

🤷  If you need support or have questions in general, please use our community forums or discord chat server. You are more likely to get an answer to your questions in those places.

../Frenck

**Comment by Ryu945** [comment]
> Ok, I don't see how something that is "closest" to any functionality you want should list non-relevant information that is not actually related.

I guess I thought that since internally, the Chromecast works the same as a Roku or Smart TV, it was relevant (aka Gets told what to play, uses the internal app to play it and uses its own internet connection "seperate from the device that requested it" to play it).


> Yet, your comment is made on the Google Cast page...

I'll have to remember you want documentation request that precise for now on.


> shrug If you need support or have questions in general, please use our community forums or discord chat server. You are more likely to get an answer to your questions in those places.

There is still the subject of the original ticket at hand.   There is a lack of documentation of how to play videos on Youtube between the different devices.

**Comment by frenck** [comment]
> There is a lack of documentation of how to play videos on Youtube between the different devices.

Where is it missing? Which functionality does exists and isn't documented?

../Frenck

**Comment by Ryu945** [comment]
> Where is it missing? Which functionality does exists and isn't documented?

Playing a specific Youtube video on WebOS and Roku.

**Comment by frenck** [comment]
WebOS is documented here, and doesn't seem to be able to:

<https://www.home-assistant.io/integrations/webostv/>

If that is missing in the docs, but existing functionality, I can add that. How does it work?

Roku can do it and is documented, including many other sources:

<https://www.home-assistant.io/integrations/roku#play-on-roku>

../Frenck

**Comment by Ryu945** [comment]
> WebOS is documented here, and doesn't seem to be able to:
> 
> https://www.home-assistant.io/integrations/webostv/
> 
> If that is missing in the docs, but existing functionality, I can add that. How does it work?
> 
> Roku can do it and is documented, including many other sources:
> 
> https://www.home-assistant.io/integrations/roku#play-on-roku
> 
> ../Frenck

Thankyou.  It seems the search engine for the documentation does not work the way I thought it did.  I thought typing in Youtube would bring up pages with Youtube related features.  Appaerntly, the Roku page does not come up with with the search parameter Youtube.
