### ISSUE TITLE
Unable to login to IQ Gateway following he given password instructions

### ISSUE THREAD

**Issue by bobjoylove** [home-assistant/home-assistant.github.io#25904]
### Feedback

Hi Team!

I have an IQ Gateway from Enphase. Using the password instructions given in the Documentation I'm unable to log in, including when I try the last 6 digits of the hardware serial number, and the app login [hint found online].  Is there some suggestions for folks who have the Enphase IQ Gateway? 

Thank you!

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.1.7

**Comment by frenck** [comment]
Hi there @bobjoylove 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
