### ISSUE TITLE
Cannot get Temperature in History

### ISSUE THREAD

**Issue by 55solotsopa** [home-assistant/home-assistant.github.io#25903]
### Feedback

I cannot get the **Temperature** only in the entities. In fact I Added Open-Meteo integration, pin-pointed it to the area I wanted and it gets all the data alright!
But when I want to get Temperature only, for historical charts, I only get "sunny"

Is it possible to get the Open-Meteo streams as different entities?

Thanks
Apostolos

### URL

https://www.home-assistant.io/integrations/open_meteo/

### Version

2023.1.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by 55solotsopa** [comment]
ok, thanks
