### ISSUE TITLE
Bad web Link (Configuration)

### ISSUE THREAD

**Issue by GeoffState** [home-assistant/home-assistant.github.io#25909]
### Feedback

**On Page:** https://www.home-assistant.io/more-info/unsupported/docker_version

**Paragraph:** 
_If you are running an older version of our Home Assistant OS, update it the [Configuration](https://my.home-assistant.io/redirect/configuration) panel._

Lands On: **Page Not Found**

### URL

https://www.home-assistant.io/more-info/unsupported/docker_version/

### Version

2023.1.7

**Comment by GeoffState** [comment]
**Issue is still relevant**

**Comment by GeoffState** [comment]
Close, thanks

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @GeoffState :+1:
