### ISSUE TITLE
IAQN-058

### ISSUE THREAD

**Issue by btrebor** [home-assistant/home-assistant.github.io#25918]
### Feedback

Is there any way the Inkbird IAQN-058 can be added to the list of approved devices in Home Assistant?

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2023.1.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
