### ISSUE TITLE
Offset is documented wrong

### ISSUE THREAD

**Issue by eugsmiley** [home-assistant/home-assistant.github.io#25926]
### Feedback

I'm following the documentation to create an automation to have a light go out 30 minutes after sunrise (offset: "30:00"), but it's not acting right. I take the offset out, it works fine. I set the offset to "10:00" and it turns the light out 10 HOURS later, not 10 MINUTES.

DOCUMENTATION SHOULD READ:

automation:
  trigger:
    - platform: sun
      # Possible values: sunset, sunrise
      event: sunset
      # Optional time offset. This example will trigger 45 minutes before sunset.
      offset: "-00:00:45"

### URL

https://www.home-assistant.io/docs/automation/trigger/#sun-trigger

### Version

2023.1.7

**Comment by dannytsang** [comment]
@eugsmiley I believe the documentation is correct. The format Home Assistant expects is Hours:Minutes:Seconds so 45 minutes would be the middle value.

In your example, I would suggest try adding the other fields e.g **00:30:00** or **00:10:00**

**Comment by eugsmiley** [comment]
While, I understand what it is SUPPOSED to be, I spent hours unhappily trying to debug an issue with an offset. The result was that I found the docs don't match the results I was getting. I am now noticing that I do have offsets that work as documented, so now I need to go back and recreate my earlier issue to narrow down the specific bug.

**Comment by eugsmiley** [comment]
Here is an interim report. I made two automations with triggers of +/-1 and +/- 10.

alias: Sunrise Offset Test Automation
description: ""
trigger:
  - platform: sun
    event: sunrise
  - platform: sun
    event: sunrise
    offset: "-1:00"
  - platform: sun
    event: sunrise
    offset: "-10:00"
  - platform: sun
    event: sunrise
    offset: "1:00"
  - platform: sun
    event: sunrise
    offset: "10:00"
condition: []
action:
  - service: notify.statusbot
    data:
      message: Sunrise Offset Test Automation
mode: single

alias: Sunset Offset Test Automation
description: ""
trigger:
  - platform: sun
    event: sunset
  - platform: sun
    event: sunset
    offset: "-1:00"
  - platform: sun
    event: sunset
    offset: "-10:00"
  - platform: sun
    event: sunset
    offset: "1:00"
  - platform: sun
    event: sunset
    offset: "10:00"
condition: []
action:
  - service: notify.statusbot
    data:
      message: Sunset Offset Test Automation
mode: single

My sunrise and sunset times for today.
SunRise: 6:48 AM
SunSet: 5:36 PM

The result from my Telegram statusbot is:

StatusBot, [2/10/23 4:37 PM]  (~1 hour before Sunset)
Sunset Offset Test Automation

StatusBot, [2/10/23 4:45 PM] (~10 hours after Sunrise)
Sunrise Offset Test Automation

StatusBot, [2/10/23 5:07 PM] (actual working -30:00 offset)
Pre-Sunset LR Lights On

StatusBot, [2/10/23 5:37 PM]   (Sunset)
Sunset Offset Test Automation

Note that as of 5:52PM, there should be 2 notifications in the 10 minutes before sunset and 2 notifications in the 10 minutes after. THERE ARE NOT.

So... Yes, my format is incorrect. I am not using the 00:00:00 form and it is giving incorrect results. The documentation is not clear about this.  I also believe this points out a programming error. The time format should be validated in code.

**Comment by dannytsang** [comment]
That's a fair point. I will look to add something about the offset format in the documentation.

As for validation, that would be new issue > Feature request and it will go under a different repository (project).

**Comment by dannytsang** [comment]
I just re-read the documentation and it does mention the offset format so unless there's anything else on the documentation side I think it's covered.

![image](https://user-images.githubusercontent.com/567982/218256113-50fcc72c-5b73-4e79-9c53-82c4f33ee9f7.png)
