### ISSUE TITLE
Les funciona BMW connected? llevo meses que me ha dejado de funcionar

### ISSUE THREAD

**Issue by manuelcarvajal** [home-assistant/home-assistant.github.io#25930]
### Feedback

Les funciona BMW connected? llevo meses que me ha dejado de funcionar

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2023.1.7

### Additional information

Les funciona BMW connected? llevo meses que me ha dejado de funcionar

**Comment by rikroe** [comment]
Please ask your question in english and include some logs from Home assistant (Settings > System > Logs).

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
