### ISSUE TITLE
floodlight contrôle missing

### ISSUE THREAD

**Issue by bobdivx** [home-assistant/home-assistant.github.io#25938]
### Feedback

hello, I am under the latest version of HA and the plugin.  All my devices are well recognized.

however for floodlights the control entity is not available, only sensors and diagnostics are used.

thanks 

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2023.1.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
