### ISSUE TITLE
HA is great : but

### ISSUE THREAD

**Issue by FARKIr** [home-assistant/home-assistant.github.io#25944]
### Feedback

 "how long need to be back from backup. 3,5gb. no DB there, on proxmox 2cpu 4gb ram" 

is this normal ? 

![image](https://user-images.githubusercontent.com/17362421/214590265-64b70077-67d4-4f02-8f7c-7ea03a31ec9a.png)

![image](https://user-images.githubusercontent.com/17362421/214590766-d7c1e14a-cff0-4a5e-9e1b-48b58dd4a653.png)

### URL

https://www.home-assistant.io/common-tasks/os/

### Version

2023.1.7

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by FARKIr** [comment]
discord cant use at all 

![image](https://user-images.githubusercontent.com/17362421/214595385-3c68fe69-d0f1-4d69-8458-80e4c03c0e6c.png)
