### ISSUE TITLE
Please include Tapo l530b

### ISSUE THREAD

**Issue by Ehteshxm** [home-assistant/home-assistant.github.io#25941]
### Feedback

I have seen many people asking for the support for l530b Tapo bulb support. Please integrate it.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2023.1.7

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
