### ISSUE TITLE
Options for Spider in automation

### ISSUE THREAD

**Issue by trouble2** [home-assistant/home-assistant.github.io#25948]
### Feedback

So, the thing is I tried to create an automation for this. However the only action I can do is change the HVAC mode to Cool or Heat.
I would like to be able to:
- change the speed of the HVAC 
- change the temperature settings of the thermostat

### URL

https://www.home-assistant.io/integrations/spider/

### Version

2023.1.7

### Additional information

-

**Comment by peternijssen** [comment]
Duplicate of https://github.com/peternijssen/spiderpy/issues/85#issuecomment-1404139442
