### ISSUE TITLE
PI Directions for Onboarding 

### ISSUE THREAD

**Issue by schellem** [home-assistant/home-assistant.github.io#25940]
### Feedback

I'd like to know how HA installed on a PI is going to find my ZWave and Zigbee devices? I'm pretty sure some the PI will need some more hardware to communicate with my devices. Now where do I see mentioned in the PI install directions/hardware that I need anything else. 

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2023.1.7

**Comment by frenck** [comment]
> I'd like to know how HA installed on a PI is going to find my ZWave and Zigbee devices?

You can find information on the requirements of integrations on the respective integration pages. As Home Assistant supports over a thousand ecosystems (and even more devices), we can't list all those specific things on the integration pages.

For example, for Zigbee you can find information here:

https://www.home-assistant.io/integrations/zha#compatible-hardware

and for Z-Wave:

https://www.home-assistant.io/integrations/zwave_js#installation-and-configuration

../Frenck

**Comment by schellem** [comment]
These directions make you think that all your existing automation devices will show up. Not a single device I have will show up in HA at this point. I understand this may not be the place to explain zwave or zigbee but it certainly would be a place to mention how you go about including various hardware or explaining that only a certain kind of device(s) will show up.

**Comment by frenck** [comment]
> These directions make you think that all your existing automation devices will show up

I'm not sure why one would think that? From our documentation:

> Once you are done, click Next. In this screen, Home Assistant will show any devices that it has discovered on your network. Don’t be alarmed if you see fewer items than what is shown below; you can always manually add devices later.

That doesn't imply that at all, it even explains not to panic if something now shows up?

../Frenck

**Comment by schellem** [comment]
How would I manually add my zwave or zigbee devices it did not find? I can't it will never find them.
A much more user friendly\understandable text would be along the lines of....

HA should have found all devices of this 'type'. (I have no idea what types of devices would be found OOB (out of the box) by HA) If you have other device type such as say ....Zwave or Zigbee, probably the most common devices in home automation, You need to see this section and add additional hardware.

I'm a 30+ year developer and started with home automation many years ago with X10 stuff. I've heard so much good about HA but I feel the documentation needs so much.

**Comment by frenck** [comment]
> How would I manually add my zwave or zigbee devices it did not find? 

This page is about onboarding, it is not a place where we want to lay out full of Home Assistant. You can add, and remove manage anything in the settings screen (just like it wrote) later.

> HA should have found all devices of this 'type'

It can't and it won't. Nor do other home automation systems, as they can't be just "detected".

> Zwave or Zigbee, probably the most common devices in home automation

Probably, many others as well, we have lots of integrations.

> I'm a 30+ year developer and started with home automation many years ago with X10 stuff. 

Cool! Me too 🤷 

Really honest, in the five years I've been active in our community, this is about the first time I've seen this comment on the onboarding procedure.

I think the current wording is pretty much up to par, especially considering this part if to get Home Assistant up and running first, not managing it.

../Frenck

**Comment by schellem** [comment]
You just don't get it do you.
