### ISSUE TITLE
Add lock a switch option

### ISSUE THREAD

**Issue by FPF92** [home-assistant/home-assistant.github.io#25961]
### Feedback

Hey Folks,

lots of KNX devices especially switch Relais offer the opportunity to lock them. 
the problem is, that if you do that on KNX perspective a user of HA does not see that and will be able to use the switch in the dashboard, however the displayed switch won’t change the state of the KNX device…

mit would be nice to add lock status address to the switches. So in the dashboard the switch could become greyed out or an icon could show that.

### URL

https://www.home-assistant.io/integrations/knx/

### Version

2023.1.7

**Comment by farmio** [comment]
Hi 👋! 
Please don't use the documentation repository issue tracker for feature requests. Head to the community forums instead.
