### ISSUE TITLE
Link Enphase documentation is changed.

### ISSUE THREAD

**Issue by Rogg3X** [home-assistant/home-assistant.github.io#25977]
### Feedback

Link to the Enphase documentation should be: https://support.enphase.com/s/article/What-is-the-Username-and-Password-for-the-Administration-page-of-the-Envoy-local-interface

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.1.7

**Comment by frenck** [comment]
Thanks, @Rogg3X 👍 

I've opened up a PR to adjust the documentation.

../Frenck
