### ISSUE TITLE
Installing third-party add-ons

### ISSUE THREAD

**Issue by GeoffState** [home-assistant/home-assistant.github.io#25970]
### Feedback

I can't find/see/launch the [**Manage add-on repositories**](https://www.home-assistant.io/images/hassio/screenshots/adding_repositories.png) window shown on this doco page.
Add the URL of the repository and then press "Add". A new card for the repository will appear.

### URL

https://www.home-assistant.io/common-tasks/os/

### Version

2023.1.7

### Additional information

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.4
Frontend 20230110.0 - latest

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
