### ISSUE TITLE
WLED Brightness control in Automations

### ISSUE THREAD

**Issue by Simple-Smarts** [home-assistant/home-assistant.github.io#25978]
### Feedback

The WLED integration documentation is good but lack any info on brightness control which is important to "newbies".
Simple actions and automations to use WLED in Hass will be the the first steps in developing a more complex HASS using WLED.

My goal is to get to a fairly complex script for sunrise effect. I got quite a few pieces already but still struggle to control basic brightness which is basic..

### URL

https://www.home-assistant.io/integrations/wled/

### Version

2023.1.7

### Additional information

I should add the Automation GUI for the integration does not appear to directly support brightness control which would probably be the ultimate fix but I understand should be submitted somewhere else.
Thanks.

**Comment by frenck** [comment]
> The WLED integration documentation is good but lack any info on brightness control which is important to "newbies".

Just like any other light. Home Assistant makes universal controls (entities) for several domains, like switches, lights, climate, and many more. Those are not specific to an integration, but generic for Home Assistant.

This way, Home Assistant is universal usable when using different brands/integrations. A Hue blub is there, controlled in the same way as an WLED strip in Home Assistant.

For more information on light entities and their capabilities, check out the light documentation at: https://www.home-assistant.io/integrations/light

I will not be adding it to the WLED documentation, for the simple reason: Not every integration should have to fully explain how a light in Home Assistant works, that would be a major duplication of instructions across our documentation.

Nevertheless, thanks for your suggestion ❤️ 

../Frenck
