### ISSUE TITLE
Integration is no longer working since Enphase includes an access token

### ISSUE THREAD

**Issue by mruizdia** [home-assistant/home-assistant.github.io#25975]
### Feedback

Hi,
Enphase has added to target the envoy device a Token, therefore the simple user and password method to connect is not working anymore.
has this already been reported? or is there any way we can help?

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.2.0b2

**Comment by frenck** [comment]
Hi there @mruizdia 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
