### ISSUE TITLE
Whats the point?

### ISSUE THREAD

**Issue by Zarox666** [home-assistant/home-assistant.github.io#25988]
### Feedback

Sorry, I dont want to make your integration useless, but I wonder what the purpose of it is, and why none of this is mentioned in the documentation:

As any other bandwidth testing tool (ctstraffic, ntttcp, iperf) speedtest is designed to saturate your connection.
Depeneding which other loads (your DFSR-Sync, VPN Tunnels, Porn Download) are currently using your WAN Connection, you will not even measure the Bandwidth Values your ISP is providing to you nominaly. And as allways: Increased load on the line increases response times. Throughput is the Bandwidth-Delay-Product afterall.
So what do I measure there? What conclusions can I derive from the measurement?

Asuming my Provider is rock solid in terms of WAN Speed, I could calculate what bandwith usage I had at the point in time Speedtest was runing... what do I do whith that knowledge?
Asuming my ISP is not so rock solid... what do I do with the meausred values unless I can put the "other" Bandwidth usages next to it.... 
No matter how you spin it... in order to detect or diagnose a Bandwidth problem, a classic Networktrace is a lot more usefull.

It is not reasonable to give anyone a rundown on how TCP works in some Integration documentation, but IMHO these severe limitations of Speedtest.net should be clearly mentioned in the Documentation so people do not get wrong expectations what it can or should do and what will happen once per hour.

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2023.1.7

**Comment by frenck** [comment]
Hi there @Zarox666 👋 

The discussion you want to raise, is about the general correctness/usefulness of services like speedtest.net (and similar). That is fine, but not really a thing for our documentation. Home Assistant provides integrations with devices and services. How useful the implemented devices and services are for your use case (or those of others) is a different discussion.

For things like that, please use our community forums or discord chat 👍 

Thanks!

../Frenck
