### ISSUE TITLE
iO6 also working in HA

### ISSUE THREAD

**Issue by daaf84** [home-assistant/home-assistant.github.io#25984]
### Feedback

I can confirm that the Oral B iO6 model is working as well.

### URL

https://www.home-assistant.io/integrations/oralb/

### Version

2023.1.7

**Comment by bdraco** [comment]
This one will be supported in 2023.2

The docs are already updated pending the release
https://github.com/home-assistant/home-assistant.io/blob/next/source/_integrations/oralb.markdown
