### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by jmarty32** [home-assistant/home-assistant.github.io#25989]
### Feedback

Not sure how to integrate alram decoder ad2serial adapter into home assistant

### URL

https://www.home-assistant.io/integrations/alarmdecoder/

### Version

2023.1.7

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
