### ISSUE TITLE
Example turn_off will not work with Home Assistant Operating System

### ISSUE THREAD

**Issue by jagibson** [home-assistant/home-assistant.github.io#25990]
### Feedback

As noted under [Shell Command](https://www.home-assistant.io/integrations/shell_command), with HAOS you are running the homeassistant container.  You can't simply use the ssh keys in the default place `/root/.ssh`.  They have to be within the configuration directory (`/config` or `~/config` in the "Teminal & SSH" add-on).  What I did as a workaround was copy my .`ssh/id_ed25519` and `.ssh/known_hosts` files to a new `.ssh` directory inside of `config`.  I was then able to run the ssh power-down script by supplying -i and -o flags to ssh.  Example:

```yaml
shell_command:
    turn_off_TARGET: "ssh -oUserKnownHostsFile=./.ssh/known_hosts -i ./.ssh/id_ed25519 hass@mytarget.local sudo pm-suspend"
```

### URL

https://www.home-assistant.io/integrations/wake_on_lan/

### Version

2023.1.7

**Comment by ghost** [comment]
if you do ls -lsa on the /root directory, you'll see that .ssh is a symlink for /data/.ssh. 
I agree that either the docs need to address this issue or the symlink for .ssh needs to be changed. 

btw, thanks @jagibson, your solution works perfectly.
