### ISSUE TITLE
notification feature not working

### ISSUE THREAD

**Issue by ashmitjain** [home-assistant/home-assistant.github.io#25995]
### Feedback

the commands work but the notifications fail to deliver

### URL

https://www.home-assistant.io/integrations/google_assistant_sdk/

### Version

2023.1.7

**Comment by klaasnicolaas** [comment]
Hi there @ashmitjain 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
