### ISSUE TITLE
Riemann sum integral with huge overestimation for Kasa switch

### ISSUE THREAD

**Issue by ubaldb** [home-assistant/home-assistant.github.io#26008]
### Feedback

I own a Kasa HS110 plug, which I regularly toggle off after work and toggle on in the morning. I also use the [Riemann integration](https://www.home-assistant.io/integrations/integration/) with the default method ("Trapezoidal") to track cumulative power consumption and see a huge peak everyday in the first hour after turning on my Kasa plug. In the attached screenshot, consumption jumps up 0.5 kWh at 08:30 AM. [1]

After looking at the code for the Riemann integral, I realized that the computation always considers the entire timeframe between the last and next update. Turns out, my Kasa plug does not send any updates when it is turned off and therefore, the timeframe can be multiple hours. This leads to huge error rates.

I was able to fix the issue by switching to the "left" method. This still considers the same time period, but the "left" data point always seems to be 0W and therefore no jumps appear.

I think it would make sense to omit the computation whenever the timeframe between two updates is too large to avoid computation errors of such scale. Otherwise this could definitely lead to a lot of confusion.

Not sure, what might be a meaningful threshold. Maybe anything above 1 minute?

[1]
![Screenshot from 2023-01-29 22-34-23](https://user-images.githubusercontent.com/67583712/215356899-b00aedab-03e9-47c3-b6eb-d23a9bea9660.png)

### URL

https://www.home-assistant.io/integrations/integration/

### Version

2023.1.7

**Comment by dgomes** [comment]
This repository is for documentation issues (not issues with the component) and therefore I'm closing this issue

That being said, the component is event driven and does not sample the sensor, so your proposed change is not feasible.
