### ISSUE TITLE
Google Assistant SDK

### ISSUE THREAD

**Issue by nasked** [home-assistant/home-assistant.github.io#26006]
### Feedback

I tried to configure Google Assistant SDK but autentification page show me this:

home-assistant.io no ha completado el proceso de verificación de Google. En estos momentos, la aplicación se está probando y solo pueden acceder a ella los testers aprobados por el desarrollador. Si crees que deberías tener acceso, ponte en contacto con el [desarrollador](https://accounts.google.com/).
Si eres desarrollador de home-assistant.io, consulta los [detalles del error](https://accounts.google.com/).
Error 403: access_denied

### URL

https://www.home-assistant.io/integrations/google_assistant_sdk/

### Version

2023.1.7

**Comment by frenck** [comment]
Hi there @nasked 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
