### ISSUE TITLE
Add PLM model number to Insteon Documentation

### ISSUE THREAD

**Issue by mattrix31** [home-assistant/home-assistant.github.io#26017]
### Feedback

The first paragraph mentions PLM model numbers - I wanted to report that I was successful in connecting an Insteon 2413S PLM in addition to the models that are currently listed.

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2023.1.7

**Comment by teharris1** [comment]
Great to hear. Thanks for the update.

**Comment by teharris1** [comment]
Docs updated. Thanks.
