### ISSUE TITLE
"Use the update_entity service" how?

### ISSUE THREAD

**Issue by ggonmar** [home-assistant/home-assistant.github.io#26021]
### Feedback

I've tried to implement this integration and change the update timing from the default of every hour to every 15 minutes.

I've come to hope the action passes by setting _somehow_, _somewhere_, the `update_entity` element to 15, but... where? how? it's not really explained there at all - nor pointing out to elsewhere on how to do so.

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2023.1.7

**Comment by frenck** [comment]
The `homeassistant.update_entity` is an default service call provided by core. A call is immediately executed (once).

It is documented here:

https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantupdate_entity

> action passes by setting somehow, somewhere, the update_entity element to

No, that is not how service calls in Home Assistant work in general (Just like you don't pass a "15 minutes" to a "light turn on" action to turn it on every 15 minutes).

What you need to do is to call it whenever you want it to update. E.g., using a time pattern trigger (or any other trigger you like). That way, you can set the frequency of updating, either additional or conditional, just like in any other automation in Home Assistant.

../Frenck
