### ISSUE TITLE
Adding Events to Calendar

### ISSUE THREAD

**Issue by seeder** [home-assistant/home-assistant.github.io#26029]
### Feedback

There is no documented way of adding events to local calendars beyond GUI.
It would be amazing to be able to add events to calendars using automation/scripts, calls to service and having it documented.

### URL

https://www.home-assistant.io/integrations/local_calendar/

### Version

2023.1.7

**Comment by frenck** [comment]
The documentation is correct, there is no other way, hence not documented.

For the 2023.2 release a first service will be added (which at that point will be documented).

But in general, for feature requests, please use our community forums 👍 

../Frenck
