### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by ajsarni** [home-assistant/home-assistant.github.io#26028]
### Feedback

Under description for target, it should include how to specify multiple targets.  I could not find anywhere that documented this.  I figured it out by experimentation.

### URL

https://www.home-assistant.io/integrations/notify/

### Version

2023.1.7

**Comment by frenck** [comment]
> Under description for target, it should include how to specify multiple targets.

What the receiving integration supports, is not documented on this page. Please consult the pages of the specific integrations for information on that.

The notify integration itself only provides the abstract services, the detailed implementations of it, and its capabilities are part of the integration that uses it.

../Frenck
