### ISSUE TITLE
Energy Dashboard - Adding individual devices

### ISSUE THREAD

**Issue by hokfujow** [home-assistant/home-assistant.github.io#26022]
### Feedback

HI - I have many devices brought in via the HACS- Hubitat integration.  They are energy metering devices and appear on the HA dashboard appropriately, showing the power and energy values.  In the Hubitat integration I see all the appropriate entities for power and energy and they are enabled.  However, none of these are available to add to as individual devices on the Energy dashboard.  The image below is an example.  This is how it appears on the overview dashboard in HA, but it is not available on the Energy dashboard to add. 

![image](https://user-images.githubusercontent.com/216010/215599302-7e745be2-0c92-49bd-8591-fee09955ad58.png)

### URL

https://www.home-assistant.io/docs/energy/

### Version

2023.1.7

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support. This issue is better addressed in the repository of the Hubitat integration 😉 

Thanks! 👍
