### ISSUE TITLE
Selecting output source

### ISSUE THREAD

**Issue by shelldor** [home-assistant/home-assistant.github.io#26031]
### Feedback

It is not obious to everyone where to put this config
service: media_player.select_source
entity_id: media_player.spotify
data:
  source: "Denon AVR-X2000"

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2023.1.7

**Comment by frenck** [comment]
In an automation, or script. It is an service call.

For more information on, for example, automations: <https://www.home-assistant.io/docs/automation/basics/>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

../Frenck
