### ISSUE TITLE
BLE Sensors are not added to Home Assistant with Tasmota Auto Discover

### ISSUE THREAD

**Issue by andiohn** [home-assistant/home-assistant.github.io#26032]
### Feedback

After following the Tasmota integration, this statement is not accurate with BLE Mibeacons. I have 3 eink Xiaomi clocks with humidity and temperature and they were never auto discovered. I had to learn about processing json in the configuration.yaml to get them into home assistant and I had to turn MiOption6 to 1 as well.

"Tasmota Sensors will be added as Home Assistant sensor entities."

Tasmota immediately saw the BLE sensors and forwarded it on to Home Assistant's MQTT broker. I was able to see the json packets, but auto discover didn't do anything with it. Entering them all manually was painful but at least now I know more about json...

Here's the link to the information that I adapted. This was quite difficult to do, and I was a sysadmin with 15 years experience with Jira/Tomcat/etc experience. Also, because MiOption6 defaults off, I'll now have to learn about setting it on bootup. I'm not complaining, I actually think Tasmota is really good, just this was painful. 

https://community.home-assistant.io/t/tasmota-xaomi-ble-temp-sensors/311314/3
"[IOT_Ninja](https://community.home-assistant.io/u/IOT_Ninja)

1
[Aug '21](https://community.home-assistant.io/t/tasmota-xaomi-ble-temp-sensors/311314/4)
I noticed that I was receiving a flood of log errors like yours. If you run [MI32Option6 178](https://tasmota.github.io/docs/Commands/#ble-mi-sensors) Tasmota will create individual topics for each connected BT sensor, ie tele/tasmota_ble/ATC*****1 and tele/tasmota_ble/ATC*****2 instead of everything published on tele/tasmota_ble/SENSOR

You can then simplify your json to something like

- platform: mqtt
  name: "Laundry Temperature"
  state_topic: "tele/tasmota_ble/ATC******"
  unit_of_measurement: "°C"
  value_template: "{{ value_json.Temperature }}"
which should stop HA from complaining about missing json attributes."

### URL

https://www.home-assistant.io/integrations/tasmota/

### Version

2023.1.7

### Additional information

There is no easy way to import BLE sensors from Tasmota into Home Assistant, including with the Tasmota Integration plugin. I'm happy to test to help out. I know enough to give good information back here if there's interest in finding a path forward.

**Comment by andiohn** [comment]
My mistake home assistant repo, I meant to post this on the Tasmota Integration repo.

**Comment by frenck** [comment]
> I meant to post this on the Tasmota Integration repo.

No problem! Going to close it on this end.
