### ISSUE TITLE
Upadte Interval

### ISSUE THREAD

**Issue by stubersa** [home-assistant/home-assistant.github.io#26030]
### Feedback

I would like to have a faster update interval is there an option to do this?

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.1.7

**Comment by frenck** [comment]
Yes, any entity can be updated on demand using the `home_assistant.update_entity` service. This is not specific to this integration, but use at your own risk.

Please note, Home Assistant comes with sane values out of the box. If all right, current polling frequencies have been set to prevent issues upstream, in general using higher rates will lead to issues. If they are not correct or sane, feel free to submit an issue instead.

../Frenck
