### ISSUE TITLE
HOST required for Home Assistant integrating Shelly

### ISSUE THREAD

**Issue by stirls1** [home-assistant/home-assistant.github.io#26044]
### Feedback

Hi, when I browse to Home Assistant on my PC, it gets to the Pi fine. I try to add Integration for Shelly but it requires a 'Host*'. Nothing in the instructions explains what I should enter for the Shelly 'Host*'. The 'help' basically says 'just enter whatever you need'.   What should I enter as the 'Host*' please?

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2023.1.7

**Comment by thecode** [comment]
Usually you don't need to reach this stage, this is for advanced users who are using isolated networks and add devices manually. The device should be automatically detected. 
Host is the IP of the Shelly. If your devices are not automatically detected, please open an issue at https://github.com/home-assistant/core/issues/new/choose

**Comment by stirls1** [comment]
Thanks Shay,

 

That hasn’t answered my question (about what Host I must use to integrate Shelly into HA).

When I follow the link you sent to GitHub, and click ‘I have a question or need support’, it redirects me to https://www.home-assistant.io/help which goes to Forum, Discord Chart, Twitter or Facebook which are not what I want.

 

Please re-open this request and assign it to someone who might be able to provide an answer about the Host.

 

Thanks,
Stirling

**Comment by bieniu** [comment]
> That hasn’t answered my question (about what Host I must use to integrate Shelly into HA).

🤔
![obraz](https://user-images.githubusercontent.com/478555/216013864-8e5fcf40-8ec7-499f-8980-52f80710c290.png)

**Comment by stirls1** [comment]
Thanks.  Sorry, I’d already tried that but it doesn’t work.

Also, I set this all up about a year ago on another system and it didn’t need a Host.

I’ve also searched forums, and a number of people have been given flippant responses that don’t solve the problem, and the consensus is that the integration should work smoothly and should not need the ‘Host*’ to be entered by the user unless something very strange is going on.

 

I think the problem might be that my Pi and PC are on network 192.168.1.* but the Shellys are on 192.168.0.*.

Both networks are in my home setup and physically connected by ethernet cables, but somehow devices are unable to detect each other across the divide.

**Comment by bieniu** [comment]
Sorry, but this is not the place to discuss the issue. This is a documentation repository. As @thecode wrote, if you need help with the integration, please open an issue in the core repository. Thanks.
