### ISSUE TITLE
D-Link Plugs Supported

### ISSUE THREAD

**Issue by richsc** [home-assistant/home-assistant.github.io#26057]
### Feedback

Will support be added for the DSP-W118 plug?  I have 4 and would very much like to integrate them.

### URL

https://www.home-assistant.io/integrations/dlink/

### Version

2023.2.0

**Comment by tkdrob** [comment]
Have you tried it? I don't have them so I am currently not planning on it. This is however an open source project so PRs are welcome.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or the [Community forum](https://community.home-assistant.io).

Thanks! 👍
