### ISSUE TITLE
Where are Helpers defined?

### ISSUE THREAD

**Issue by vb7445** [home-assistant/home-assistant.github.io#26059]
### Feedback

I've used the search bar, glossary and just about everything but can't find a description or topic on what Helpers are.

### URL

https://www.home-assistant.io/docs/tools/

### Version

2023.2.0

**Comment by aidbish** [comment]
https://www.home-assistant.io/integrations/#helper

**Comment by frenck** [comment]
Good point, this isn't defined.

To answer the question: An helper is an integration that doesn't interact with other devices, services, or protocols. They either provide user input or consume other entities to calculate a result.

[Groups](https://www.home-assistant.io/integrations/group) are good examples of this. The group integration by itself can't do much. It doesn't integrate a device or service by itself. However, it can consume, for example, multiple temperature sensor entities and calculate the average temperature out of those. Next, you can use that resulting average sensor entity from this group helper in your automation, and scripts or display it on your dashboards.

Helpers "help" you with automation, scripts, or showing calculated/aggregated values on your dashboards.

../Frenck

**Comment by vb7445** [comment]
Thanks for the reply. I found a YouTube video showing how to use them. I’d call them variables used to store different data types.

-Phil
***@***.***

On Feb 2, 2023, at 5:39 AM, Franck Nijhof ***@***.***> wrote:

﻿

Good point, this isn't defined.

To answer the question: An helper is an integration that doesn't interact with other devices, services, or protocols. They either provide user input or consume other entities to calculate a result.

Helpers "help" you with automation, scripts, or showing calculated/aggregated values on your dashboards.

../Frenck

**Comment by frenck** [comment]
> I’d call them variables used to store different data types.

That is highly inaccurate, as a matter of fact, all entities and their states have the same data type 😉 

../Frenck
