### ISSUE TITLE
Blink Mini Pan Tilt Movement?

### ISSUE THREAD

**Issue by erit1566** [home-assistant/home-assistant.github.io#26058]
### Feedback

Hello, this integration looks awesome, but I was wondering if you will ever add movement options for the Blink mini pan tilt camera? It would be awesome to be able to setup camera angles and with a click of a button(or automation) the camera would move to the desired location.

Thanks,
Eric

### URL

https://www.home-assistant.io/integrations/blink/

### Version

2023.2.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
