### ISSUE TITLE
How to create a service

### ISSUE THREAD

**Issue by twixbob** [home-assistant/home-assistant.github.io#26054]
### Feedback

I am a beginner of Home Assistant and YAML. What I can't find explained anywhere in the documentation is how to define a service. I would like to create a service but I don't understand where I can do that. First I thought this could be done in the "Developer Tools/Service" page, but that only seems to be a place to test a service. 

### URL

https://www.home-assistant.io/integrations/homeassistant/

### Version

2023.2.0

**Comment by frenck** [comment]
> What I can't find explained anywhere in the documentation is how to define a service.

One doesn't. Services are provided by integrations, not user-defined.

../Frenck
