### ISSUE TITLE
wiffi also suitable for LAN devices

### ISSUE THREAD

**Issue by heinrich2808** [home-assistant/home-assistant.github.io#26089]
### Feedback

The software developper of the wiffi add-on is using a weatherman device - a kit purchased fm stall.buiz and an interesting 
solution. But it is also important to note: data transmission fm the weatherman to the homeassistant is done via WLAN.
When I installed the Pulsecounter-LAN2 (also fm stall.buiz) to be connected to the homeassistant my idea was to use this
wiffi add-on - but it doesn't work`` with the following error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/wiffi/__init__.py", line 224, in __call__
    await self.parse_msg(peername, data[:-1])  # omit separator with [:-1]
  File "/usr/local/lib/python3.10/site-packages/wiffi/__init__.py", line 240, in parse_msg
    metrics.append(WiffiMetricFromSystemInfo("rssi", "dBm", "number", data["Systeminfo"]["WLAN_Signal_dBm"]))
KeyError: 'WLAN_Signal_dBm'

Pls note: I am a newbie as homeassistant as well as software dev. is concerned, but my idea is:

The pulsecounter is connected to my network/homeassistant via LAN (and not via WLAN as the weatherman).
As the wiffi add-on is concerned: the add-on is waiting for an information as the WLAN signal strengh is concerned
- and as long as this info is missing the wiffi addon will not work with with the pulscounter. It is a pity

It would be great if mampfes could append a "switch" in his wiffi addon to make it suitable also for wiffi LAN devices

### URL

https://www.home-assistant.io/integrations/wiffi/

### Version

2023.2.1

### Additional information

used homeassistant version
![HASS](https://user-images.githubusercontent.com/123395161/216572728-5a4208bc-d554-4894-a4f1-073832d7b313.jpg)

**Comment by heinrich2808** [comment]
Hi,
is my idea ok: I deactivate + delete the wiffi integration which I have downloaded two weeks ago and I reinstalled
the wiffi fim the github in order to get the wiffi 1.1.2 ?

Because this is exactly what I did and still I face the same error log as before:

` Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/wiffi/__init__.py", line 224, in __call__
await self.parse_msg(peername, data[:-1]) # omit separator with [:-1]
File "/usr/local/lib/python3.10/site-packages/wiffi/__init__.py", line 240, in parse_msg
metrics.append(WiffiMetricFromSystemInfo("rssi", "dBm", "number", data["Systeminfo"]["WLAN_Signal_dBm"]))
KeyError: 'WLAN_Signal_dBm'`

Also I would have anticipated a kind of switch to select wiffi via WLAN - LAN ? 

Almost useless to say I am absolutely unexperienced as python and yaml is conecerned, hence I appreciate
your efforts in context with wiffi....

**Comment by mampfes** [comment]
I think this will not work, because HA always uses the configured package version. This also corresponds to what you can see in the log: In version 1.1.2 this line from the log is in [line 241](https://github.com/mampfes/python-wiffi/blob/5afa869a1e97a1f5ead62999e899b4c51f1387aa/wiffi/__init__.py#L241).

There are some advices in the HA developer docu how to use different version for packages like wiffi: https://developers.home-assistant.io/docs/creating_integration_manifest#custom-requirements-during-development--testing

It would be great if you could test this before I (re)open the PR in the HA main repo.
