### ISSUE TITLE
Dual use

### ISSUE THREAD

**Issue by tim000x3** [home-assistant/home-assistant.github.io#26084]
### Feedback

I love that openai can be access in HA but it overwrites the assist function. As it cannot control my home then there needs to be a way to chose which I am talking to GPT or assist. Whether it's two icons at the top or down where it says OpenAI at the bottom right of the chat window having a drop down to chose.

### URL

https://www.home-assistant.io/integrations/openai_conversation/

### Version

2023.2.1

**Comment by balloob** [comment]
This is a feature request and should be posted @ https://community.home-assistant.io/c/feature-requests/13

It's also something that is in progress.
