### ISSUE TITLE
To which file do I have to add schedule yaml code?

### ISSUE THREAD

**Issue by sbogun** [home-assistant/home-assistant.github.io#26099]
### Feedback

Very nice example, but it is not clear to me to which config file the schedule yaml snippet would have to be added.
I have created schedules using the UI and the only file where code for the schedules can be found is 
`.storage/schedule`
and that one doesn't have the syntax 
```
schedule:
  thermostat_schedule:
    name: "Thermostat schedule"
...
```

instead it looks like this:

```
{
  "version": 1,
  "minor_version": 1,
  "key": "schedule",
  "data": {
    "items": [
      {
        "name": "schedule bedroom",
...
```
(JSON code).

So where does the yaml code on this page have to go?
Awesome application and documentation, anyway! Thank you so much!
Stefan

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2023.2.1

**Comment by frenck** [comment]
`.storage` is an hidden folder and used by Home Assistant internally. Anything in that folder should **never** be edited by you as an user.

All configurations for integrations are done in the `configuration.yaml` file.

See also:

![CleanShot 2023-02-03 at 20 13 22](https://user-images.githubusercontent.com/195327/216687796-a0c4d18c-2240-4e33-aa04-3fd41a2b726f.png)

../Frenck

**Comment by sbogun** [comment]
> `.storage` is an hidden folder and used by Home Assistant internally. Anything in that folder should **never** be edited by you as an user.
> 
> All configurations for integrations are done in the `configuration.yaml` file.
> 
> See also:
> 
> ![CleanShot 2023-02-03 at 20 13 22](https://user-images.githubusercontent.com/195327/216687796-a0c4d18c-2240-4e33-aa04-3fd41a2b726f.png)
> 
> ../Frenck

Thanks Frenck, and yes, I didn't intend to edit a file in the `.storage` folder, it's just that `configuration.yaml` doesn't contain any schedule that had been created previously, nor any of the yaml files included in `configuration.yaml`.

**Comment by frenck** [comment]
>  it's just that configuration.yaml doesn't contain any schedule that had been created previously

UI-managed items are not stored in YAML. You can add manually managed ones in YAML (those you can't be managed in the UI at that point). The exception to these are automations, scripts and scenes. Otherwise, that applies to everything.

So, you can mix and match them, but each one is either manually in YAML or managed by the UI.

../Frenck

**Comment by sbogun** [comment]
> > it's just that configuration.yaml doesn't contain any schedule that had been created previously
> 
> UI-managed items are not stored in YAML. You can add manually managed ones in YAML (those you can't be managed in the UI at that point).
> 
> So, you can mix and match them, but each one is either manually in YAML or managed by the UI.
> 
> ../Frenck

I see! Thanks for the clarification!
