### ISSUE TITLE
Change password on existing Dexcom device

### ISSUE THREAD

**Issue by zivgin** [home-assistant/home-assistant.github.io#26095]
### Feedback

This is great.
But my wife (it's her dexcom) change the password and now  i get an error.
I couldn't find anyplace in home assistant where i can change the password.

### URL

https://www.home-assistant.io/integrations/dexcom/

### Version

2023.2.1

### Additional information

It's impobisble to use the old password since dexcom doesn't allow this.
So i need an option to change the password since i don't want to uninstall and reinstall this as i have many integrations already linked to this entity.

**Comment by gagebenne** [comment]
Hi, I'll have to look into seeing whether this is a feature that Home Assistant supports. For now, I think you should be fine deleting the entity and adding it back. I'd expect the entity names to stay the same, but if they change, you can manually change them back pretty easily. All automations, scrips, scenes, etc that depend on the named entity shouldn't break once they find an entity with the old name.

**Comment by gagebenne** [comment]
@home-assistant rename Change password on existing Dexcom device

**Comment by gagebenne** [comment]
@home-assistant close

**Comment by zivgin** [comment]
OK, i'll have a look, but i would say this is important feature to enable (changing password instead of deleting and reinstalling).
Thanks for the response!
