### ISSUE TITLE
Can confirm this works on RLC-510A

### ISSUE THREAD

**Issue by CrashM85** [home-assistant/home-assistant.github.io#26090]
### Feedback

Can confirm this works on RLC-510A

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.2.1

**Comment by starkillerOG** [comment]
@CrashM85 thanks for the feedback, I added it to the list of supported devices in the documentation here: https://github.com/home-assistant/home-assistant.io/pull/26077

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by starkillerOG** [comment]
@home-assistant close
