### ISSUE TITLE
Home assistant Assistant

### ISSUE THREAD

**Issue by lonnie776** [home-assistant/home-assistant.github.io#26094]
### Feedback

in the assistant I asked it multiple questions but the answer it kept giving me was " Sorry, I couldn't understand that " Not sure what this is about.
This essentially make this feature completely useless.

### URL

https://www.home-assistant.io/docs/assist/

### Version

2023.2.0

### Additional information

ask question,

**Comment by frenck** [comment]
Hi there @lonnie776 👋 

It seems like you want to report an issue with Home Assistant, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Be sure to check if your issue isn't reported already (before creating a new one).

Thanks! 👍 

../Frenck
