### ISSUE TITLE
Lights randomly turn on

### ISSUE THREAD

**Issue by moritzbindewald** [home-assistant/home-assistant.github.io#26107]
### Feedback

Hey,

for some reason my lights turn on in the middle pf the night. Homeassistant claims the trigger to be HomeKit. I know for certain, that no one activated the light via home, since I am running it restricted to my icloud. I am using a raspberry pi 4 with haas os. 

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2023.2.1

**Comment by frenck** [comment]
Hi there @moritzbindewald 👋 

Thank you for reaching out.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

If you do want to report an issue, please note, that right now, you have submitted documentation feedback. Please report issues here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍

../Frenck
