### ISSUE TITLE
greyed out gauge in case of unavailablility

### ISSUE THREAD

**Issue by jmoed** [home-assistant/home-assistant.github.io#26109]
### Feedback

In case of sensors disappearing from time to time the gauge shows an error message, which hurts the layout of the whole page. Would there be a chance to have it instead greyed out?

### URL

https://www.home-assistant.io/dashboards/gauge/

### Version

2023.2.1

**Comment by dannytsang** [comment]
@jmoed I'd suggest raising this as a feature request. It has ended up in documentation feedback.
