### ISSUE TITLE
Does not understand lights - Assist 

### ISSUE THREAD

**Issue by mantis64** [home-assistant/home-assistant.github.io#26112]
### Feedback

If I ask it to turn on office light it does not turn on my entity 'office light' but says it has turned it on when it hasn't.  

However if I ask to turn the office lights on, it works.  

What am I doing wrong?

### URL

https://www.home-assistant.io/docs/assist/

### Version

2023.2.1

### Additional information

My device is a ikea bulb connected via Zigbee2mqtt.  

The same happens for other lights, for example if I say 'turn on the living room light' it says it has turned it on but hasn't.  But if I say turn on the lights in the living room, it works.

**Comment by klaasnicolaas** [comment]
Hi there @mantis64 👋

It seems like you want to report an issue for te Home Assistant Intents, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant Intents issue tracker instead:

https://github.com/home-assistant/intents/issues

Thanks! 👍

./Klaas
