### ISSUE TITLE
How much history is saved?

### ISSUE THREAD

**Issue by vb7445** [home-assistant/home-assistant.github.io#26115]
### Feedback

Was looking for how stored history data is managed in the database? Is there a size restriction, just how does that work?
I think this information should be included in this section on History.

### URL

https://www.home-assistant.io/integrations/history/

### Version

2023.2.1

**Comment by klaasnicolaas** [comment]
This depends on what is set as purge in the recorder integration 😉

**Comment by vb7445** [comment]
Thanks for that. I’m a newbie, didn’t know about the recorder integration.
-phil
