### ISSUE TITLE
Pull request #18864 is locked so no one including myself can comment or make changes to it

### ISSUE THREAD

**Issue by Hedda** [home-assistant/home-assistant.github.io#26119]
### Feedback

This was originally posted by @frenck in https://github.com/home-assistant/home-assistant.io/issues/18864#issuecomment-1416492142 :

>             I've marked this PR, as changes are requested that need to be processed.
>Please un-draft it once it is ready for review again by clicking the "Ready for review" button.
>
>Thanks! 👍 
>
>../Frenck
>

@frenck https://github.com/home-assistant/home-assistant.io/pull/18864 pull request is still locked so no one including myself can comment or make changes to it. Can you unlock PR?

I have tried to inform you about the fact that it is locked before via a related issue https://github.com/home-assistant/home-assistant.io/issues/21565 so I will not be able to un-draft it, etc.

![image](https://user-images.githubusercontent.com/6320001/216129808-5a853ffa-1f99-4c7f-88b3-ea6cb51d5e60.png)

            

### URL

https://www.home-assistant.io/integrations/zha

**Comment by frenck** [comment]
odd, unlocked it 👍 

../Frenck
