### ISSUE TITLE
Problems following the AdGuard Home "integration" website, while the AdGuard Home "Add-On" works fine...

### ISSUE THREAD

**Issue by gymshoe** [home-assistant/home-assistant.github.io#26117]
### Feedback

I tried the link on this website to "Add Integration" for AdGuard Home.  The link appeared to "work": it took me to what appeared to be an initial configuration page, however, I was never able to provide a configuration ("host", "port", username, password) that worked.  I kept receiving an error "Unknown error occurred".  (FYI: When I entered a wrong host, I would get a different "failed to login" error, instead of the "Unknown error".)
Subsequently, I just used the AdGuard Add-On (which is available in the Add-On store) which installed without problems and AdGuard is functioning properly for me.
I am wondering if this weblink for the AdGuard Home Integration is out of date and should be replaced with instructions for the AdGuard Home Add-On instead....

### URL

https://www.home-assistant.io/integrations/adguard/#:~:text=From%20the%20configuration%20menu%20select,to%20complete%20the%20set%20up.

### Version

2023.2.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
