### ISSUE TITLE
Log file size >52GB

### ISSUE THREAD

**Issue by Rien7777** [home-assistant/home-assistant.github.io#26124]
### Feedback

Hey, my HA crashed and gave a docker error (wouldn’t start). Turns out my logger clogged up to 52gb in size. It’s repeating the same error: During handling of the above exception, another exception occurred: …… (some file not found). 

It says there is an entry limit but that doesn’t seem to have worked with me.

### URL

https://www.home-assistant.io/integrations/system_log/

### Version

2023.2.2

**Comment by dannytsang** [comment]
@Wolf777777 would the max entries work? It's not by file size but at least you can force overwrite older entries.

**Comment by Rien7777** [comment]
@dannytsang hey! Yeah its suppose to default on 50. I tried setting it to 10, but that didn't help. Its some kind of Traceback that keeps repeating itself. I think my Zigbee installation is the one that started it.

- Traceback (most recent call last):
- Python3.10 FileNotFoundError: [Errno 2] No such file or directory: .......
- During handling of the above exception, another exception occurred:
- Traceback (most recent call last):
- ...
aaaand so on

**Comment by dannytsang** [comment]
Good point on the default. Beyond the docs, maybe submitting it as a feature request but I'm afraid that's all I have to offer.

Good luck.

**Comment by Rien7777** [comment]
As far as I know this is still a relevant issue
