### ISSUE TITLE
Somfy needing Restart to start working again...

### ISSUE THREAD

**Issue by c3systems** [home-assistant/home-assistant.github.io#26120]
### Feedback

Noticed a theme over the past couple months.  I can't seem to get anything Somfy working unless I restart the integration.  

It seems to have gone from once a month, to once a week, to now daily - Should I look for something in the logs?  (And where should I look in the logs? Or where to find the logs?  haha I have not a clue where to start)

Now that daily restarts of HA are required (and not any other restarts of the network, Somfy integration nub, or anything else) is this an HA bug?  

Plz lmk if this is the wrong forum for this sort of thing - thank you so much in advance!

### URL

https://www.home-assistant.io/integrations/somfy/

### Version

2023.2.2

**Comment by klaasnicolaas** [comment]
Hi there @c3systems 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
