### ISSUE TITLE
Bad redirect link?

### ISSUE THREAD

**Issue by addboy58** [home-assistant/home-assistant.github.io#26123]
### Feedback

I keep getting a error of a bad redirect link. I have redone it several times. This is what I have in the Neto page:
![Capture](https://user-images.githubusercontent.com/23740927/216835899-0c31269d-c7c9-4e4b-8459-3b047f7d3794.JPG)

### URL

https://www.home-assistant.io/integrations/neato/

### Version

2023.2.2

**Comment by WiredWonder** [comment]
Same issue here, token has expired and I can't reauth so Neato integration is broken.

**Comment by addboy58** [comment]
I have been trying to find someone that can help for the last two months.

**Comment by dshokouhi** [comment]
Did you guys all make sure to update Neato with the latest URL as per teh updated docs?

`https://my.home-assistant.io/redirect/oauth`

Just like the note: https://www.home-assistant.io/integrations/neato/#prerequisites

**Comment by addboy58** [comment]
Yes. I created a new app and updated in my config.yaml.

**Comment by dshokouhi** [comment]
did you make sure to visit https://my.home-assistant.io and make sure to fill in your server details so the link is active?

**Comment by addboy58** [comment]
This what I have in my

**Comment by dshokouhi** [comment]
That is not correct, you need to use the URL I mentioned up above and its also mentioned in the docs.

![image](https://user-images.githubusercontent.com/1634145/220698040-3dcc79b8-5131-4797-a906-64f97efc8831.png)

**Comment by dshokouhi** [comment]
also you may want to delete the screenshots exposing your actual URL :)

**Comment by addboy58** [comment]
Where do I find this?

**Comment by dshokouhi** [comment]
Go to https://developers.neatorobotics.com/applications edit your application and change the URL. Same place as described in the documentation.

**Comment by addboy58** [comment]
Not to be slow but wear do I get the link? Thx

**Comment by WiredWonder** [comment]
> Did you guys all make sure to update Neato with the latest URL as per teh updated docs?

@dshokouhi it's supposed to with without my home assistant. Due to a bug in the plug it's stopped working.

**Comment by dshokouhi** [comment]
> Not to be slow but wear do I get the link? Thx

start with the official HA documentation that you included in the original issue

https://www.home-assistant.io/integrations/neato/



> @dshokouhi it's supposed to with without my home assistant. Due to a bug in the plug it's stopped working.

only if you have the proper setup as per the instructions in the docs about those who have disabled My Home Assistant. If its not working that is not a documentation bug but a HA core bug. This issue is specifically about the documentation that needs to be followed.


![image](https://user-images.githubusercontent.com/1634145/220757929-094b5457-ba91-4bf4-9809-beb2f69e3f4e.png)

**Comment by WiredWonder** [comment]
> only if you have the proper setup as per the instructions in the docs about those who have disabled My Home Assistant.

Multiple people are saying that they had working setups that broke with an update to this integration, including me.

**Comment by dshokouhi** [comment]
> > only if you have the proper setup as per the instructions in the docs about those who have disabled My Home Assistant.
> 
> Multiple people are saying that they had working setups that broke with an update to this integration, including me.

yes there was a breaking change to a lot of Oauth platforms, not every user was hit by the breaking change at the same time. Mine needed to be updated a few months ago.

**Comment by WiredWonder** [comment]
Was this the change? If so a mention in the doco may aid those like me

FROM:
https://[instance fqdn]/redirect/oauth

TO:
https://[instance fqdn]/auth/external/callback


edit: not certain it was as I overwrote the URL with the My Home Assistant one to get back up and running.

**Comment by dshokouhi** [comment]
Documentation is always meant to be the latest which is why there is a breaking change section in the release notes. In this case I think several different integrations were updated in the same fashion so it doesn't make sense to make this one change here. If the docs are up to date I think that is enough personally.

**Comment by WiredWonder** [comment]
The problem with HA releases is that there are so many each month it's basically impossible to read all the release notes in a real world production use case. With things breaking every other release people using it to run their house can't afford to update ~fortnightly.

**Comment by frenck** [comment]
> The problem with HA releases is that there are so many each month

One. One each month containing breaking changes.

**Comment by WiredWonder** [comment]
> One. One each month containing breaking changes.

My point remains! I don't know about you, but I'm too busy living life to refactor broken things every month.

**Comment by frenck** [comment]
> but I'm too busy living life to refactor broken things every month.

Sorry to hear that. If you update once every three months, you have to check 3 chapters. We can't do anything about that. Sorry.

**Comment by frenck** [comment]
Looking at the whole thread here, it is a known documented breaking change (which solved tons of problems moving forward, so we are definitely happy with the result at the price of talking the breaking change hit).

The current documentation is correct and contains the right information.

Therefore, I'm going to close this documentation feedback issue, as there is no documentation change to the process.

../Frenck

**Comment by addboy58** [comment]
Wear do I get the server details?
