### ISSUE TITLE
Feature request: add possibility to add time frames to energy tariffs

### ISSUE THREAD

**Issue by climbernl** [home-assistant/home-assistant.github.io#26121]
### Feedback

Within the energy dashboard there is the possibility to add the current tariffs for energy (electricity and gas).
But as soon as the tariff changes and you adjust the tariff values, it is fixed and also applied to past usage (or production).
It would be good to be able to set a start (and end) date from which date the tariff is valid, so you'll get a more realistic overview of the costs.
Similar like you can do in the SolarEdge dashboard

F.e. Jan 01 2022 the tariff for Peak is €0.24 and Off Peak is €0.22, but from June 1 2022 it is €0.39 for Peak and €0.31 for Off Peak and from Jan 1 2022 Peak is €0.75 and Off Peak is €0.57

![printscreen multiple energy tariffs](https://user-images.githubusercontent.com/90702135/216816847-7e981c71-dd65-4b96-bf2c-7c2c5536033d.jpg)

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2023.2.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by climbernl** [comment]
Thank you.
Created a new feature request.
This post can be removed
