### ISSUE TITLE
Emulated Hue with Google Home

### ISSUE THREAD

**Issue by jakeblat** [home-assistant/home-assistant.github.io#2613]
While running through the instructions for the Emulated Hue Component (https://home-assistant.io/components/emulated_hue/) I've run into a few issues.

The example configuration for Google Home notes that Google Home doesn't work on different ports (it only works on port 80), however it doesn't override the default port of 8300. Looking at the component code setting ```type: google_home``` does not set the port to 80 although it does throw a warning, maybe this should be changed?

I suggest that this:

```
# Google Home example configuration.yaml entry
emulated_hue:
  # Google Home does not work on different ports.
```

is changed to this:

```
# Google Home example configuration.yaml entry
emulated_hue:
  listen_port: 80
  # Google Home does not work on different ports.
```
The Amazon Echo example has ```listen_port: 80```, maybe this was mistakenly added in the wrong section?

I've also discovered that adding the Emulated Hue to Google Home may be difficult if you already have a  Hue Bridge. I believe that due to the way Hue Bridge discovery works existing bridge's may be prioritised. There is some documentation available - https://developers.meethue.com/documentation/hue-bridge-discovery (requires registration) and mirrored here https://github.com/probonopd/ESP8266HueEmulator/wiki/Discovery

I believe the upnp discovery may be broken in my network setup which prevents the emulated hue from being discovered. The IP scan will not normally take place if methods 1 or 2 of discovery have returned any results.

I'd be interested to see if anyone else has run into this problem? And if it's worth adding some additional notes about discovery to the component instructions?

**Comment by riker09** [comment]
I think I'm facing the same issue. I have a physical Hue bridge in my network and when I try to configure Hue in Google Assistant on my smartphone I'm immediately redirected to the meethue.com website.

**Comment by DubhAd** [comment]
This was broken by changes made by Google/Philips, and instead can be done with the new [Google Assistant component](https://home-assistant.io/components/google_assistant/).
