### ISSUE TITLE
Minor color error.

### ISSUE THREAD

**Issue by KentGitIvar** [home-assistant/home-assistant.github.io#26139]
### Feedback

When there is a lamp that don't have any change of color only brightness, the card icon get black.

The other lamps that at least have some kind of chnage in color or temperature will light up in color near the lamp color.

The more info icon is yellow as before only the card icon itself have changed.

This have come after upade to  Home Assistant 2023.2.1.

No change after update to  Home Assistant 2023.2.2.

Mvh Kent

### URL

https://www.home-assistant.io/dashboards/light/

### Version

2023.2.2

**Comment by frenck** [comment]
Hi there @KentGitIvar 👋 

It seems like you want to report an issue with the Home Assistant frontend, however, you have submitted documentation feedback instead. Please report issues with the frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
