### ISSUE TITLE
Example for usage of "in" with calendar.create_event

### ISSUE THREAD

**Issue by bozzoyann** [home-assistant/home-assistant.github.io#26137]
### Feedback

Hello,

Thanks a lot for this new service that I am very happy to use.

I cannot figure how to use the "in" yaml mode.
Is it possible to publish an example using "in" in the documentation, thank you.

Reading the doc, I try the following within, but none of them work;

`data:
  summary: "blabla"
  in: "days: 2"`

or
`data:
  summary: "blabla"
  in: ""days": 2"`
or 
`data:
  summary: "blabla"
  in_days: 2`

sorry, for the lack of formalism in the message, It is the first time I whrite  github message and I do not how to use the "code" mode

Thanks a lot

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2023.2.2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
