### ISSUE TITLE
Assist: recording speech not working in iOS app

### ISSUE THREAD

**Issue by OlafKocanda** [home-assistant/home-assistant.github.io#26146]
### Feedback

When pressing the microphone button in the iOS app, it instantly answers with "Home Assistant did not hear anything"
![Bildschirmfoto 2023-02-06 um 19 37 59](https://user-images.githubusercontent.com/58265203/217057307-52d2ebb8-bfa1-461c-a024-bc2fbf59b9de.png)

Pressing the button for long, it tries to select the microphone as text.

Using the latest Home Assistant version (2023.2.2) and tried on different iPhones (13 and SE 2022) with iOS 16.3

### URL

https://www.home-assistant.io/docs/assist/

### Version

2023.2.2

**Comment by OlafKocanda** [comment]
sorry wrong repo

**Comment by frenck** [comment]
Hi there @OlafKocanda 👋 

It seems like you want to report an issue with Home Assistant functionality itself, however, you have submitted documentation feedback instead. Please report bugs here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
