### ISSUE TITLE
Please mention that login email can not have Capital letters in it or linking fails.

### ISSUE THREAD

**Issue by KrickGregory** [home-assistant/home-assistant.github.io#26144]
### Feedback

Please mention that login email can not have Capital letters in it or linking fails. This cost me several of hours. Now it works fine. 

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2023.2.2

**Comment by fmms** [comment]
This issue can be closed in my opinion the page contains:
_"The provided Home Connect User Account email address must be all lowercase otherwise it will result in authentication failures."_

**Comment by fmms** [comment]
It was fixed as part of #26421 two weeks ago
