### ISSUE TITLE
Bluetooth Adapter Verified Working

### ISSUE THREAD

**Issue by LordNex** [home-assistant/home-assistant.github.io#26141]
### Feedback

I’m not sure the model number of this one as I can’t seem to find anything that corresponds to what you have listed on your website but I can verify that this ZEXMTE Bluetooth Adapter with dual external antennas that are supposed to reach 150m, works great and is currently on sale. It’s using Realtek Chipset. I’ve included the hardware info in the additional info section. 

USB Bluetooth Adapter for PC 5.1, Long Range Bluetooth USB Adapter for Windows 11/10,492FT/150M Bluetooth Dongle 5.1 EDR,Plug & Play for Desktop, Laptop, Printers, Keyboard, Mouse, Headsets, Speakers https://a.co/d/5mK7zuL

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2023.2.2

### Additional information

'''
BUSNUM: '002'
DEVNAME: /dev/bus/usb/002/004
DEVNUM: '004'
DEVPATH: /devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.1
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_MODEL: Bluetooth_Radio
ID_MODEL_ENC: Bluetooth\x20Radio
ID_MODEL_ID: 877b
ID_PATH: pci-0000:02:00.0-usb-0:2.1
ID_PATH_TAG: pci-0000_02_00_0-usb-0_2_1
ID_REVISION: '0200'
ID_SERIAL: Realtek_Bluetooth_Radio_00E04C239987
ID_SERIAL_SHORT: 00E04C239987
ID_USB_INTERFACES: ':e00101:'
ID_VENDOR: Realtek
ID_VENDOR_ENC: Realtek
ID_VENDOR_ID: 0bda
MAJOR: '189'
MINOR: '131'
PRODUCT: bda/877b/200
SUBSYSTEM: usb
TYPE: 224/1/1
USEC_INITIALIZED: '7162146'
'''

**Comment by bdraco** [comment]
Can you post the dmesg as well?
