### ISSUE TITLE
invalid clientid

### ISSUE THREAD

**Issue by AndrzejKaminski74** [home-assistant/home-assistant.github.io#26159]
### Feedback

if i try to use this integration I am redirected to withings site to select a user (a few are defined on my account). I select the user - and the error message appears: "invalid clientid"
![Zrzut ekranu 2023-02-7 o 13 46 07](https://user-images.githubusercontent.com/103813316/217248706-22e28dbd-f615-4fd1-9567-da74a80922d9.png)
do you know how to solve this issue?

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2023.2.2

**Comment by AndrzejKaminski74** [comment]
Something has changed. Previous error disappeared but new one started. After clicking "allow this app" following message appears: "{"errors":[{"message":"redirect_uri_mismatch: The redirect URI provided is missing or does not match partner callback url"}]}"

![Zrzut ekranu 2023-02-7 o 19 56 58](https://user-images.githubusercontent.com/103813316/217340109-33e225a0-cff6-422f-a81e-05a2af0eb089.png)

**Comment by mad5307** [comment]
I'm getting the same error with invalid client ID, is there a way to restart the setup process?

**Comment by AndrzejKaminski74** [comment]
Well I have not found any working solution :-(

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
