### ISSUE TITLE
Missing steps to set up Shelly to HA

### ISSUE THREAD

**Issue by ShellyHA** [home-assistant/home-assistant.github.io#26157]
### Feedback

Hi,
I'm new user of HA and trying to integrate Shelly units. When reading your "how to" I just miss out the important part how to get the Shelly units to connect to an existing network. I can see the unit as a network on Windows, but it do not connect to my WiFi. = can't se the unit on my router.
/Jack 

### URL

https://www.home-assistant.io/getting-started/join-the-community/

### Version

2023.2.2

**Comment by dannytsang** [comment]
@ShellyHA you have put https://www.home-assistant.io/getting-started/join-the-community/ but is this the right page you're feeding back on because I can't see Shelly on there...
