### ISSUE TITLE
Documentation for Renault integration is missing details of current integration

### ISSUE THREAD

**Issue by MS-HACS** [home-assistant/home-assistant.github.io#26150]
### Feedback

Having a look at the documentation and checking what features the integration shows up in my HAss installation I see some documentation gaps and perhaps some more examples.
Perhaps the documentation is some steps behind implementation?

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2023.2.2

**Comment by epenet** [comment]
Feel free to create a PR
