### ISSUE TITLE
Docker compose section is missing useful info

### ISSUE THREAD

**Issue by SkyLined** [home-assistant/home-assistant.github.io#26156]
### Feedback

The Docker compose section could use a bit more details for people not familiar with docker.

>Create a `compose.yml` file:

Where should this file be stored? If not a specific path, a general description of the type of location where you'd want to store this file would be useful.

> docker compose up -d

* If you run this command in a different folder than where you created the `compose.yml` file, you get an error message `no configuration file provided: not found`.
* If you run the above command (in the right folder) without first removing the home assistant container that was created during installation, you will get an error: `Error response from daemon: Conflict. The container name "/homeassistant" is already in use by container "[....]". You have to remove (or rename) that container to be able to reuse that name.`

Here's my suggested changes:

As the Docker command becomes more complex, switching to docker compose can be preferable and support automatically restarting on failure or system restart. To do this, you must create a `compose.yml` file. You can create this file anywhere you want but you may want to store it in a folder that is associated with home-assistant, so it is easy to find.
[...]
Next, you must inform docker that it should stop and remove the current home assistant container. Then tell it to use this file to start the home assistant container from now on. In the folder where you created the `compose.yml` file, run these three commands:
```
> docker stop /homeassistant
> docker rm /homeassistant
> docker compose up -d
```

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.2.2

**Comment by frenck** [comment]
>  The Docker compose section could use a bit more details for people not familiar with docker.

We are not here to teach you about Docker. If you need help using Docker, the official documentation and resources of Docker themselves are a much better place to look for such information.

> support automatically restarting on failure or system restart.

Side note: That is not a docker compose-specific feature.

> If you run the above command (in the right folder) without first removing the home assistant container that was created during installation, you will get an error

> Next, you must inform docker that it should stop and remove the current home assistant container

Your suggestion is dangerous, as it may lead to deleting something unintended, I would strongly disagree with adding such a command for that reason (it is also the reason Docker doesn't just do it for you). The warning raised by Docker is caused by creating a conflicting naming in your setup, which needs careful resolution manually.

Please also note, this is an installation guide, not a migration guide.

I do understand your suggestion, but going to friendly decline this suggestion. Simply because they distract from the actual installation and the above-given reasons.

Thanks!

../Frenck

**Comment by SkyLined** [comment]
Understood. I strongly believe most of the HA documentation is not friendly enough to beginners and would benefit greatly from a bit more details. But given that all my suggestions have been rejected so far, I feel that I am wasting both our time. Should I stop making suggestions or is there value in me continuing to try and help improve the docs?

**Comment by SkyLined** [comment]
> >  support automatically restarting on failure or system restart.
> Side note: That is not a docker compose-specific feature.

That is copy+pasted from the current documentation. If it is not correct, the documentation should be fixed.

**Comment by SkyLined** [comment]
>  The warning raised by Docker is caused by creating a conflicting naming in your setup, which needs careful resolution manually.

If you follow the current steps, you will end up in this situation: In the [Platform Installation](https://www.home-assistant.io/installation/raspberrypi/#platform-installation) section, a container is created with the name `homeassistant`. In the following [Docker Compose](https://www.home-assistant.io/installation/raspberrypi/#docker-compose) section, you are told to create it again with the same name using compose. This leads to an error as you cannot create it twice without deleting the old one first, hence my suggestion to improve the documentation.
