### ISSUE TITLE
Control4 integration not pulling devices

### ISSUE THREAD

**Issue by josueluly** [home-assistant/home-assistant.github.io#26161]
### Feedback

Home Assistant is able see the controller, but doesn’t pull any device within Control4. 

### URL

https://www.home-assistant.io/integrations/control4/

### Version

2023.2.2

**Comment by klaasnicolaas** [comment]
Hi there @josueluly 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
