### ISSUE TITLE
Prometheus endpoint address?

### ISSUE THREAD

**Issue by SpangleLabs** [home-assistant/home-assistant.github.io#26178]
### Feedback

Maybe this is a silly question, but whereabouts is the prometheus endpoint when you add the prometheus integration? I can't find it at `/metrics` which is where I would expect it.
I've added the following to the bottom of my configuration.yaml:
```
prometheus:
  namespace: homeassistant
```

but I can't see the prometheus integration listed in the UI, and I can't find a metrics endpoint to point my prometheus agent at

### URL

https://www.home-assistant.io/integrations/prometheus/

### Version

2023.2.3

**Comment by frenck** [comment]
Interesting, that is indeed not documented.

It is `/api/prometheus`

**Comment by knyar** [comment]
Yeah, I think the only place it's currently documented is in the Prometheus server config snippet in the [Full Example](https://www.home-assistant.io/integrations/prometheus/#full-example) section.

**Comment by SpangleLabs** [comment]
Ah, I hadn't spotted it down there actually. I guess the auth makes it a bit tricky to check in browser (to double check metric series names before adding it to my prometheus config). I'll have to spin up Postman to check that.

If I'm running this on a local network with some assumption of inherent security in that, is there some way I can just disable the authentication on the prometheus metrics endpoint?
