### ISSUE TITLE
Growatt plugin has stopped working 02/09/23

### ISSUE THREAD

**Issue by bschofield425** [home-assistant/home-assistant.github.io#26189]
### Feedback

I cannot get the plugin to work today, there was a HA update yesterday but all still worked afterword. 
I can access the data from the shinephone app, but cannot get it to update on HA. 
I deleted the plugin and it would not let me reinstall it as it continued to fail on username  / password. 
I ended up restoring backup from yesterday to at least get the plug in back, but it still will not import data for today. 

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.2.3

**Comment by muppet3000** [comment]
This is the repo used for the documentation site.
However, I believe you're reporting this bug: https://github.com/home-assistant/core/issues/87696, so I recommend taking a read of that, especially my most recent comment there.

**Comment by muppet3000** [comment]
@home-assistant close

**Comment by muppet3000** [comment]
Closed as a duplicate/incorrect repo.
