### ISSUE TITLE
OpenWeatherMap Forecast data (for hourly - 5 day/3 hour data)

### ISSUE THREAD

**Issue by koreywithak** [home-assistant/home-assistant.github.io#26188]
### Feedback

As I understand it, new registrations on OpenWeatherMap require the "hourly" selection. That works fine with me. I'm hoping to get information about temperatures during the next 24-hour period. It looks like the payload from the API call should contain temperatures every 3 hours for the upcoming 5 days. I do not understand how to access this additional data. I can only see the current and the upcoming 3-hour forecast. Could this helpful information be added to the website?

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2023.2.3

**Comment by dannytsang** [comment]
@koreywithak The information should be stored as an attribute as a list. You can check this using the developer tools. Below is what I see.

If you're question is about getting those values out, I think you will need to use [Templates](https://www.home-assistant.io/docs/configuration/templating/) in your automation/scripts.

![image](https://user-images.githubusercontent.com/567982/218171551-7ea134a5-6733-4ab9-a09e-35dd00b92eda.png)

**Comment by koreywithak** [comment]
I think I can see how to go about this now--I have some learning to do about templates... It would be good to mention these items on the associated wepage to help steer folks like me onto the right path. I appreciate it.
