### ISSUE TITLE
Documentation is lacking information on how to properly setup gas readings in the energy module.

### ISSUE THREAD

**Issue by jandamf** [home-assistant/home-assistant.github.io#26185]
### Feedback

I have been struggling on figuring out how to interface my gas meter readings into Home Assistant. Looking throughout the forums, I find many people with similar problems, but not many solutions.

It would be helpful if this page could provide some insite on what the requirements are for the data values necessary for them to show up in the dropdown list for Gas Consumption.

I was able to setup my Emporia Energy Electric using an Add On that created 1 Minute, 1 Day and 1 Hour readings.
It seems that on the Electric side, you setup consumption using 1 Day readings, and can add additional 1 day readings.

The best information that I could find from the Home Assistant on the dropdown that states:
- Gas consumption is measured either as the volume of gas that flows to your home or as the amount of energy contained in the gas.
- Pick a sensor which measures gas consumption in either of CCF, ft³, m³, kWh, MWh, MJ, GJ, Wh.
- Note: It is not possible to add both sensors measuring a volume of gas and sensors measuring the amount of energy contained in the gas.

Next best information that I could find from the Home Assistant stating to check with the integrator to fix the problem.

### URL

https://www.home-assistant.io/docs/energy/gas/

### Version

2023.2.3

**Comment by frenck** [comment]
If an integration doesn't show up but should, it is a bug that should be reported.
There is no control for a user to "change" the sensor provided by integration.

Please open up an issue in our core issue tracker instead, or, in case it is provided by a third-party integration, please report it to the author of that integration.

../Frenck
