### ISSUE TITLE
Instructions on how to disable automated polling

### ISSUE THREAD

**Issue by philipmjones** [home-assistant/home-assistant.github.io#26198]
### Feedback

Thanks for providing the advice in the documentation about setting a quota on the Google API. The example you give for a manual polling automation is also very helpful.

In the documentation, you mention the idea of disabling automated polling:
> To use more granular polling, disable automated polling in your config entry’s System Options.

Please can you give a few more details about how/where this is done. There doesn't seem to be anything in the integration's configuration page, and the general HA documentation doesn't seem to help with this. Is there a specific line that needs to go into configuration.yaml that disables automated polling for some or all routes?

Thanks again!

Phil

### URL

https://www.home-assistant.io/integrations/google_travel_time/

### Version

2023.2.3

**Comment by eifinger** [comment]
Hi, the general documentation is indeed missing information on System Options or I could not find it as well.
Every Integration (which is configured via the UI, not configuration.yaml) does have System Options.

You can access them if you click on the three dots of the entry as shown below
<img width="437" alt="Screenshot 2023-02-10 at 11 08 42" src="https://user-images.githubusercontent.com/1481961/218064945-a3a06548-85a6-4a83-87e8-c7834daf80f4.png">

**Comment by philipmjones** [comment]
Ah, perfect, thanks.

How does the updating of documentation work with HA? Is it like Wikipedia where members of the public can propose edits? If so I would be happy to tweak the documentation to add this information (and the other point which has been discussed), for you or another to review.

**Comment by eifinger** [comment]
Currently on my phone. At the very bottom of the page there is an edit button. This will let you open a pull request against this repo.
[![image](https://user-images.githubusercontent.com/1481961/218251916-e37d26a5-d9df-46d2-a940-db02e9b0fa18.png)]()
