### ISSUE TITLE
Tank Level Unit of Measurement

### ISSUE THREAD

**Issue by rjaquez** [home-assistant/home-assistant.github.io#26193]
### Feedback

The tank level entity defaulted to a unit of measure of _in_ - which I assume is inches. 
Would that be correct? Should it be called out in the documentation what the correct unit should be?

### URL

https://www.home-assistant.io/integrations/mopeka/

### Version

2023.2.3

**Comment by frenck** [comment]
`in` and `"` are indeed the official symbols for inches as defined by SI standards.

The units used depend on your own settings. Depending on the unit system used, it can be different. You can also select and change units to your liking in the entity settings (and Home Assistant will convert it). This is not specific to this integration.

../Frenck

**Comment by rjaquez-interloop** [comment]
@frenck i do understand that. My concern is whether or not the sensor itself is actually transmitting a unit of linear measure (in, cm, etc). 
On the Mopeka app the measurement is a percentage. I think what I am asking is - shouldn't it be a percentage coming into HA and not a linear measure?

**Comment by rjaquez** [comment]
@frenck<https://github.com/frenck> i do understand that. My concern is whether or not the sensor itself is actually transmitting a unit of linear measure (in, cm, etc).
On the Mopeka app the measurement is a percentage. I think what I am asking is - shouldn't it be a percentage coming into HA and not a linear measure?

Sent from my Mobile Device

On Feb 12, 2023, at 2:11 PM, Franck Nijhof ***@***.***> wrote:

﻿

in and " are indeed the official symbols for inches as defined by SI standards.

The units used depend on your own settings. Depending on the unit system used, it can be different. You can also select and change units to your liking in the entity settings (and Home Assistant will convert it). This is not specific to this integration.

../Frenck

**Comment by frenck** [comment]
If you think there is a bug, then please open up a bug in our issue tracker:

<https://github.com/home-assistant/core/issues>

../Frenck

**Comment by rjaquez** [comment]
My mistake. I thought that’s what I was doing.
Sorry about that.

**Comment by frenck** [comment]
Don't worry about it.

PS: Consider using GitHub's web interface for typing replies in the future. Responses via email look horrible 😢 (Can't believe they still haven't fixed that after all those years).
