### ISSUE TITLE
How to edit the destination and origin that were entered through the UI during initial setup

### ISSUE THREAD

**Issue by philipmjones** [home-assistant/home-assistant.github.io#26197]
### Feedback

First off, thanks for creating and maintaining this integration. It is really useful. The documentation allowed me to set it up initially, but then I struggled to find out how to make changes:

When you add the Google Maps Travel Time integration by clicking the button in this article, there is a straight-forward setup screen in Home Assistant which allow you to enter a name, your API, a destination and origin. 

If you want to subsequently change any of those details, other than the name, there is no obvious place where you can do so through the UI. Also, I could not find any reference to those details in configuration.yaml.

Please can you add instructions for changing the origin and destination, and perhaps also the API key, of an existing travel time integration/device/entity.

If this can only be done by editing a YAML file, please can you state where that file can be found. If it is not possible to edit these details then please can you make a note to that effect, and give an alternative. If the alternative is to delete the entity and re-add the integration with the new details, please can you make a note to say that.

### URL

https://www.home-assistant.io/integrations/google_travel_time/

### Version

2023.2.3

**Comment by eifinger** [comment]
Hi @philipmjones.
The information you provide when configuring any integration cannot be changed later.

You have to create a new entry for Google Travel Time (click the button again and input the information) with lat/lon/apikey as desired.

**Comment by dannytsang** [comment]
@philipmjones I can't remember exactly how I set this up but try this:

1. Create 2 *Text* helpers from Settings > Devices & Services > Helpers (tab), 1 for origin and another for destination.
![image](https://user-images.githubusercontent.com/567982/218168944-66ed7f1f-3df9-40bc-906c-1f608a2967ae.png)
2. Note the entity ID's for each of them. E.g:
![image](https://user-images.githubusercontent.com/567982/218169836-fcd80027-e4bf-44e8-b575-3abb48a3f55c.png)
3. Setup the integration again but this time, type in the Text helper entity IDs into the destination and origin.
![image](https://user-images.githubusercontent.com/567982/218170089-676553c1-cd28-48bd-a1a4-1767e37486c8.png)

You can now change the text helpers with your co-ordinates, address, etc (use developer tools to test or automations and scripts) and update the entity to get the travel time from Google.

**Comment by eifinger** [comment]
Why would you do that instead of creating a new entry? Doesn't changing the origin/destination change the meaning of the whole travel time entities? Or do you look at it in a way of "sensor.google_travel_time_duration currently shows home to work and maybe I will use it as something else tomorrow"?

I am trying to understand your usecases, I am debating whether origin/destination should be optional/changeable

**Comment by dannytsang** [comment]
@eifinger Mainly laziness for me rather than setting up multiple integrations. I would set the text helpers and then read the updated value within my script / automations.

One use case I have not yet fully implemented is using calendar event location and calculating the travel time. You could make say the origin static based on a device tracker but the destination would change. Calendar event location is stored as attributes on the calendar entity or more likely from a calendar event which I don't think you can set during the setup on the integration.

**Comment by eifinger** [comment]
It will be in the future. I am working with Allen Porter on that

**Comment by philipmjones** [comment]
Actually my use case for updating the origin and destination is a bit more mundane than that. As I am not a real expert in Home Assistant I do a lot by trial and error, which means that I need to be able to go back and change things when they don't work! So for example, I wasn't clear which entity to use as the current location of my phone. I got it wrong first time around, so had to delete the integration completely and re-add it in order to correct the configuration. The use of helpers is a really useful tip, though; thanks.

**Comment by magiva** [comment]
Having a dynamically changing origin and destination is very useful for calendar entries where I get travel time for the next calendar entry where it has a location.

**Comment by keithellis74** [comment]
I would like to be able to edit the origin and destinations.  When setting this up in YAML it was possible to enter the co-ordinates, if the route does not work correctly, then the co-ordinates can be updated. In the UI, a new entity has to be created and you have no record of the original co-ordinates, so you have to keep a record of them in a pad or something.  this seems like a backwards step. It would be far easier to have the ability to edit them in the UI.
