### ISSUE TITLE
What data where?

### ISSUE THREAD

**Issue by dereinst** [home-assistant/home-assistant.github.io#26206]
### Feedback

There is a single input field and it is not described what data is expected: "Host".
I am a newbie and have no idea what they mean by host or what is expected. IP address? Device Name? Other name or number?

"-From the list, search and select "Shelly".
-Follow the instruction on screen to complete the set up."

What instructions? There is nothing here except "Host".... ?
Unfortunately my Shelly1 is not recognized or found and I have no idea why not, since the IP address is addressable, Shelly can be switched via browser and smartphone app. All in the same network...
For this then more detailed info would be important, what data is expected where. Especially for newcomers.

Translated with www.DeepL.com/Translator (free version)

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2023.2.3

**Comment by thecode** [comment]
Please create an issue in the [core repository](https://github.com/home-assistant/core/issues/new/choose), this repo is used for documentation issues.
