### ISSUE TITLE
scan_interval on doods integration not explicite

### ISSUE THREAD

**Issue by landaisbenj** [home-assistant/home-assistant.github.io#26211]
### Feedback

I think it's was some issue with CONFIGURATION VARIABLES "scan_interval". 

It was not listed, and showed in exemple. 

What is the fonctionnality of this, and how it work ?

### URL

https://www.home-assistant.io/integrations/doods/

### Version

2023.2.3

**Comment by frenck** [comment]
It is not listed on the doods configuration, as it is not part of that integration. `scan_interval` is a platform option, documented here:

<https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval>

The existing documentation of `doods` seems to be correct.

../Frenck
