### ISSUE TITLE
UniFi OS no longer allows creation of local accounts

### ISSUE THREAD

**Issue by snowboardjoe** [home-assistant/home-assistant.github.io#26219]
### Feedback

I can't find anywhere in the interface on how to create just a local user. I'm using the direct IP to my console and logged in. However, when I create a new user, it insists on sending an email invite to them and having them login. That goes to ui.com and the login will not work.

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2023.2.3

### Additional information

UCK G2 Plus
UniFi OS UCK G2 Plus 3.0.13

**Comment by JATD2020** [comment]
You should uncheck "Allow Remote Access". Then it still creates a local user.

**Comment by AngellusMortis** [comment]
@home-assistant close
