### ISSUE TITLE
How to disable it

### ISSUE THREAD

**Issue by PiotrWawryniuk** [home-assistant/home-assistant.github.io#26212]
### Feedback

I can't find the way of disabling the assistant (Help icon with command). I do not want it. I would like to have it disappeared in the interface. How?

### URL

https://www.home-assistant.io/docs/assist/

### Version

2023.2.3

**Comment by frenck** [comment]
The `assist` integration is part of Home Assistant's default configuration, which you can find here:

<https://www.home-assistant.io/integrations/default_config>

If you are not happy with it, you can remove the default configuration from the Home Assistant configuration you have and manage and maintain your own instead.

../Frenck
