### ISSUE TITLE
A listing of acronyms is missing

### ISSUE THREAD

**Issue by pop-ch** [home-assistant/home-assistant.github.io#26214]
### Feedback

Being a new user, I find much of the documentation very difficult to understand, and this is not due to the subject matter but because of the liberal use of acronyms in both the docs and the forum.

For instance, I post a query in the forum. I am advised to try a 'custom HACS integration'. As I am unable to find any reference to HACS, I ask what a HACS might be. That query is ignored.

May I suggest to add a list of abbrevations and acronyms either to the glossary or as a separate resource to the top level of the doc?

### URL

https://www.home-assistant.io/docs/glossary/

### Version

2023.2.3

**Comment by frenck** [comment]
Hi!

If there is a term missing, I would be happy to add it.

HACS is, however, a third-party thing and not something Home Assistant has, maintains or provide, and thus is not part of our documentation.

../Frenck
