### ISSUE TITLE
Additional sensors import export annual

### ISSUE THREAD

**Issue by sved-SI** [home-assistant/home-assistant.github.io#26229]
### Feedback

I'm missing a sensor:
1. Annual/month consumption from grid (Purchased in solaredge api)
2. Annual/month export to grid ( FeedIn in solaredge api )

We have annual consumption statement, so this information is very important to compare consumed and emitted energy

3. Option to set refresh interval.
   I use addional python script API in my RPI3 for monitoring export and import and calculate difference between import and export energy to grid and have 30min interval.
  Here is 15min interval, Use the full limit of api call

Thankyou for for the realization

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2023.2.3

**Comment by frenck** [comment]
Thank you for reaching out. We use this GitHub issue tracker for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by sved-SI** [comment]
Agreed, I apologize for the confusion
