### ISSUE TITLE
tmb integration stops working

### ISSUE THREAD

**Issue by izotop510** [home-assistant/home-assistant.github.io#26220]
### Feedback

Since four days ago the integration stops working, information says : Tmb no longer provides this integration. I tried with two tmb developer accounts, I've created a new tmb developer user but I haven't any result.

### URL

https://www.home-assistant.io/integrations/tmb/

### Version

2023.2.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
