### ISSUE TITLE
Philips TV Integration outdated?

### ISSUE THREAD

**Issue by oywino** [home-assistant/home-assistant.github.io#26238]
### Feedback

Jointspace was only valid up to about the 2011 generation of Philips TV's, so it will never work with models based on Android TV.
Should't this be mentioned in the docs? As it is now, HA users are easily mislead to think that an up-to-date working Philips TV integration is actually available, while in reality is is outdated since more than 10 years!

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2023.2.0

**Comment by elupus** [comment]
Eh? It works fine on Android TV's. SOURCE listing does not. But everything else does.

**Comment by oywino** [comment]
I can see that my post was a bit unclear. What I meant was that according to Philips, they stopped implementing JointSPACE sometime around 2011.  Of course, if you have an old TV with JointSpace, it probably still works. But new TV's don't support it anymore.

**Comment by elupus** [comment]
Depends on what you mean by new. It was supported on TVs from just a year or two ago. We cater to many. If you know of versions of TV's where its not supported feel free to update the docs about that.

So far ive not found out at what version it was no longer supported.

**Comment by elupus** [comment]
Ps. My TV is from 2019 and it support it. Ive seen saphi TVs from 2021 that support it. Likely newer as well.

**Comment by oywino** [comment]
That's very interesting. I specifically asked Philips support to confirm this with reference to the 65" OLED936 model. They said it did support Android ADB but not JointSPACE API.  Sadly, this type of information is never included in any available end user documentation.

**Comment by elupus** [comment]
I would not be surprised if they did remove it. So it might not be in the OLED936. If you have one its easy to check if you can connect to http://hostip:1925 or https://hostip:1926

**Comment by oywino** [comment]
I do not have on (yet). Thanks for the advise. What should a positive output from https://hostip:1926/ look like?

**Comment by elupus** [comment]
If you get any response (even 404 error) on those ports its likely active.

**Comment by oywino** [comment]
Ok, thanks for the advise. 👍

**Comment by elupus** [comment]
Will close this for now until we have actual cases that doesn't work.
