### ISSUE TITLE
No information on how to refresh checks

### ISSUE THREAD

**Issue by p0wertiger** [home-assistant/home-assistant.github.io#26235]
### Feedback

There is no information on how to refresh the checks after fixing them eg. manually.

### URL

https://www.home-assistant.io/integrations/repairs/

### Version

2023.2.3

**Comment by frenck** [comment]
The check should provide that information, or disappear when fixed.

If neither is the case, that would be a bug and should be reported in our issue tracker.

It is thus correct it isn't documented, as there is no universal handling on this.

../Frenck
