### ISSUE TITLE
Derivative Integration page lists Time_Window attribute not present in Config Flow UI

### ISSUE THREAD

**Issue by teleksterling** [home-assistant/home-assistant.github.io#26249]
### Feedback

The time window settings doesn't exist, so I guess should be removed from this documentation page? 

### URL

https://www.home-assistant.io/integrations/derivative/

### Version

2023.2.4

**Comment by wlangstraat** [comment]
I have the same problem with version 2023.2.1 and newer
On a installation with version 2023.2.0 it is still exist

edit:
On version 2023.2.5 the time_window is back.

**Comment by Motik68** [comment]
Still not present for me in 2023.2.5:

![image](https://user-images.githubusercontent.com/22507182/221685302-e42f5562-5c8d-428e-bc61-393664059142.png)
