### ISSUE TITLE
Raspberry install Home Assistant core

### ISSUE THREAD

**Issue by Raimo57** [home-assistant/home-assistant.github.io#26241]
### Feedback

Hi, tried to install Home Assistant core following docoment. Everything was perfectly OK without any errors, until version 2023.2.3 install command (see below). I there  a contribution available for Raspberrypi 3 ?

homeassistant@raspberrypiRN:/home/piRaimo $ pip3 install homeassistant==2023.2.3
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement homeassistant==20          23.2.3
ERROR: No matching distribution found for homeassistant==2023.2.3

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.2.3

### Additional information

homeassistant@raspberrypiRN:/home/piRaimo $ pip3 install homeassistant==2023.2.3
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement homeassistant==20          23.2.3
ERROR: No matching distribution found for homeassistant==2023.2.3

**Comment by frenck** [comment]
> ERROR: Could not find a version that satisfies the requirement homeassistant==20 23.2.3
> ERROR: No matching distribution found for homeassistant==2023.2.3

This will happen when you are using an older Python version. As per the documentation you linked, you'll need Python 3.10 at least. Ensure you are using that.

../Frenck
