### ISSUE TITLE
Problem configuring

### ISSUE THREAD

**Issue by XBano** [home-assistant/home-assistant.github.io#26247]
### Feedback

Hello i had a problem configuring the ip webcam always i try to configure it, appears an error that says failed to connect when i put the camera ip adress can someone help me?
![Captura](https://user-images.githubusercontent.com/121093312/218684762-6d74e18e-e8d7-4693-a8e9-6332af367b94.PNG)

### URL

https://www.home-assistant.io/integrations/android_ip_webcam/

### Version

2023.2.4

**Comment by engrbm87** [comment]
make sure you have pressed start server on the app and that you are using the correct username and password.
Lastly, ensure that port 8080 is allowed on your machine.
