### ISSUE TITLE
Will "energy today" work vs "energy total" for Battery?

### ISSUE THREAD

**Issue by alexespencer** [home-assistant/home-assistant.github.io#26252]
### Feedback

It's not quite clear whether the energy dashboard can handle a sensor that resets each day like "Battery Charge Today" vs "Battery Charge Total" - can this be clarified here?

### URL

https://www.home-assistant.io/docs/energy/battery/

### Version

2023.2.4

**Comment by frenck** [comment]
If the sensor is selectable on the energy dashboard, it will work. This may include sensors that daily reset (depending if the integration provides information when they reset).

There is nothing to write about it. We can't write  "Battery Charge Today" will work, we can't even say: "Battery Charge Total" will work either, as the same applies. The integration needs to provide statistical hints for sensors. These are internals and not user-configurable.

../Frenck
