### ISSUE TITLE
Add more information to indicate a common use case - monitoring the Home Assistant database size

### ISSUE THREAD

**Issue by 500Foods** [home-assistant/home-assistant.github.io#26256]
### Feedback

I think this is what is needed to add a sensor to track the size of the Home Assistant database.  Perhaps this should be included in the documentation directly.

homeassistant:
  whitelist_external_dirs:
    - /config
sensor:
  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db

### URL

https://www.home-assistant.io/integrations/filesize/

### Version

2023.2.4

**Comment by gjohansson-ST** [comment]
`filesize` is conifgured using UI so example would not be valid.
How to document for `whitelist_external_dirs` is already provided as a link.

**Comment by gjohansson-ST** [comment]
@home-assistant close
