### ISSUE TITLE
KISS principle Please

### ISSUE THREAD

**Issue by ScottBourquin** [home-assistant/home-assistant.github.io#26255]
### Feedback

Just got a Pi4 and a 10" touchscreen to go with it.  Reading through threads and trying to follow the path only work if you are already familiar with Hassio and Pi and programming languages.  I see the same questions on dozens of threads and forums.
I figured out how to Get the new PiOS with a GUI running.  Then I pulled that SD card and got the Hassio running on another chip and accesed remotely from a PC.  Then I found threads that say "follow the instructions".  I did, and I have no GUI for HA on my Pi.  You "assume" I have docker, but where on my PC, Mac, desktop or Pi?  

What I want to do is use my Pi touchscreen as a home assistant GUI interface.  It looks like I need to go back, install the Pi OS and then the Hassoi with some kind of docker.  Programming in Xcode is easier.

### URL

https://www.home-assistant.io/getting-started/

### Version

2023.2.4

### Additional information

If I don't run out of patience ad get this working, maybe I'll write the easy guide to a raspberry pi with Home Assistant GUI.

**Comment by frenck** [comment]
> What I want to do is use my Pi touchscreen as a home assistant GUI interface.

We don't support such a setup, you are looking on our getting started page for something we are not designed for doing.

If you like to make different setups, you are welcome to do so, but you are on your own creating such hybrid devices.

> Programming in Xcode is easier.

Well, yeah, makes sense considering the above 😉 

../Frenck
