### ISSUE TITLE
Suggestions not enough to fix unhealthy setup

### ISSUE THREAD

**Issue by HumanGear322** [home-assistant/home-assistant.github.io#26261]
### Feedback

I've tried all the suggestions on this help page, but HA still reports an "unhealthy setup" error. Only problem in the list is "setup":

![image](https://user-images.githubusercontent.com/111016327/219032423-7e8a8e03-c6de-428c-add5-6893b9bc7807.png)

![image](https://user-images.githubusercontent.com/111016327/219032555-04b6f78c-25bb-4282-b5d2-fafb1e47253e.png)

### URL

https://www.home-assistant.io/more-info/unhealthy/setup/

### Version

2023.2.4

**Comment by frenck** [comment]
This should not happen on an installation with the Home Assistant Operating System (and thus not a documentation issue).

Please report your issue in the Supervisor issue tracker here:

<https://github.com/home-assistant/supervisor/issues>

../Frenck
