### ISSUE TITLE
Possible feature merge?

### ISSUE THREAD

**Issue by thegit** [home-assistant/home-assistant.github.io#26273]
### Feedback

A lot of work has been done by @NigelCoxon [here](https://github.com/NigelCoxon/Hass-heatmiser) to fix bugs and add features. Would it be possible/a lot of work to merge featuers into the default integration?

Kind regards

### URL

https://www.home-assistant.io/integrations/heatmiser/

### Version

2023.2.5

### Additional information

https://github.com/NigelCoxon/Hass-heatmiser

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
