### ISSUE TITLE
backup.create is no longer a service on HA OS

### ISSUE THREAD

**Issue by plembo** [home-assistant/home-assistant.github.io#26270]
### Feedback

At least on HA OS, "backup.create" is no longer a service. Instead, you must use "hassio.backup_full" or "hassio.backup_partial". Documentation is wrong.

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2023.2.5

**Comment by frenck** [comment]
It never was. See also the note on that page:

![image](https://user-images.githubusercontent.com/195327/219310154-3db02c19-47ec-43b2-84ba-ad1b9bc2038b.png)

As this documentation doesn't apply to HA OS.

../Frenck
