### ISSUE TITLE
Tuya IoT Core renew

### ISSUE THREAD

**Issue by Thijxx** [home-assistant/home-assistant.github.io#26294]
### Feedback

There is only a monthly trial and you need to renew it every month, a person will review this request and this will take time, may be good to put this at the top of the page to warn potential new users so they can choose something else. 
For us stuck with these products it seems the only option is a monthly renewal or pay $25.000 for a one year license.

https://www.home-assistant.io/integrations/tuya/#28841002-no-permissions-your-subscription-to-cloud-development-plan-has-expired

The steps above should be:
Cloud > Cloud Services > IoT Core > View Details > My Subscriptions tab > Subscribed Resources > IoT Core > Extend Trial Period.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.2.5

**Comment by macflyhub** [comment]
I agree. Do NOT buy any TUYA related products. Their API system is really complex and a pure nightmare to use/setup.
Never mind their mix of data centres and other issues.
Even if their $25'000 to $50'000 costs are not required the entire system and reliability is just madness.
No other smart devices solution is like this.

**Comment by tpickle-py** [comment]
I dont see this as a feasible option, if you have to renew monthly, let alone yearly.  I understand there is a cost to host an API in the cloud. but we need LOCAL, is Tuya in the works with matter or thread?  I have spent money on light bulbs that can not be flashed to local control .  Side note, this integration doesn't allow for the mix of using Smart Life and Tuya Smart, which in some cases is a problem.
