### ISSUE TITLE
Incorrect and potentially confusing note about Matter's use of IPv6 and mDNS 

### ISSUE THREAD

**Issue by jaylogue** [home-assistant/home-assistant.github.io#26299]
### Feedback

A note on this page states "Matter devices (and any Thread Border routers) must be on the same LAN/VLAN as Home Assistant. " I think I understand the intent of the statement, but in a strict technical sense this is incorrect, because Thread-only Matter devices by their nature cannot exist on a WiFi/Ethernet LAN.  Indeed, many Ethernet-based concepts such as VLANs simply do not apply to Thread-only devices.

This may be a small discrepancy in concept, but I fear that this sort of thing can cause confusion in people trying to come to grips with how Matter and Thread work, and how they relate to existing technologies such as WiFi.

I would suggest the following text as a replacement:

_Matter devices that use WiFi (including Thread Border routers) must be on the same LAN/VAN as Home Assistant.  Matter devices that only use Thread must be joined to Thread networks for which there is at least one border router connected to the Home Assistant LAN._

Also, as a minor point, the note goes on to say "Implementations like mDNS reflectors usually do more harm than good."  While this is probably true in many cases, I will note that, in order for a Thread Border router to properly support Matter it must do mDNS caching and forwarding between the connected WiFi/Ethernet network and the associated Thread network.  So in some sense mDNS "reflection" is essential to a properly functioning Matter fabric.

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2023.2.5

**Comment by marcelveldt** [comment]
I'm not sure if adding even more technical terms will make the documentation more clear but point taken that we should address it. Maybe we can come up with a mix of your proposal and some links to explanations of the various terms, starting with the difference between Thread and Matter (as people tend to mix the two all the time)

**Comment by marcelveldt** [comment]
addressed in https://github.com/home-assistant/home-assistant.io/pull/27136

thanks @jaylogue !
