### ISSUE TITLE
mDNS

### ISSUE THREAD

**Issue by Jarou3ek** [home-assistant/home-assistant.github.io#26297]
### Feedback

Hello,
how do i change mDNS Bonjour HAP to Ciao

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2023.2.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
