### ISSUE TITLE
Where to use these commands?

### ISSUE THREAD

**Issue by jasongabler** [home-assistant/home-assistant.github.io#26318]
### Feedback

On the one hand, this page give such small details as how to perform a search in a browser ("Use the search function in your browser (CTRL + f / CMD + f)"), but it doesn't provide more necessary details as to the context on where or how to run the commands. I suppose they are to be executed outside the container in which Home Assistant is running?  Please expand.

### URL

https://www.home-assistant.io/common-tasks/core/

### Version

2023.2.5

**Comment by frenck** [comment]
> I suppose they are to be executed outside the container in which Home Assistant is running? 

The page you linked is for when using the Home Assistant Core installation method, which does not use containers. Considering your message, I assume you are running the Home Assistant Container installation methods, which have instructions here:

<https://www.home-assistant.io/common-tasks/container/>

../Frenck

**Comment by jasongabler** [comment]
Hi Franck,

Thank you for explaining. Though I'm running supervised
<https://www.home-assistant.io/common-tasks/supervised/#run-a-specific-version>,
not container, your reply helped me see my misunderstanding. I found the
core instructions from a google search, but did not readily understand that
there are specific methods for each installation .

Jason Gabler
