### ISSUE TITLE
Could not get external IPv4 address

### ISSUE THREAD

**Issue by busaku** [home-assistant/home-assistant.github.io#26319]
### Feedback

Hey Guys,

currently the cloudflare integration seems not to work.
"Fehler beim Aufrufen des Diensts cloudflare.update_records. Could not get external IPv4 address"

ISP: Dual-Stack (Vodafone Germany)

### URL

https://www.home-assistant.io/integrations/cloudflare/

### Version

2023.2.5

**Comment by ludeeus** [comment]
If your system has v4 and v6, v6 is prefered, you need to disable that.
Or use something that can use v6, this integration only support v4 as stated in the documentation.

**Comment by busaku** [comment]
v6 is not prefered.

yh, i know. should only set the A Record.

**Comment by ludeeus** [comment]
> v6 is not prefered.

It is, by the transport in the code.

**Comment by busaku** [comment]
hm.. okay, but how can i change this? :D
