### ISSUE TITLE
Privacy?

### ISSUE THREAD

**Issue by stefanuytterhoeven** [home-assistant/home-assistant.github.io#26315]
### Feedback

I just wanted  to try "assist". At the bottom of the screen "powered by google assistant sdk" ????
That's what you call "privacy" ? Can I uninstall "assist"?

Who is your data protection officer ? (GDPR)?

### URL

https://www.home-assistant.io/privacy/

### Version

2023.2.5

### Additional information

![image](https://user-images.githubusercontent.com/11261032/220167425-17228f10-d8a1-4ffc-b52d-847120b01687.png)

**Comment by frenck** [comment]
It is an example, you can configure Google Assistant SDK, OpenAI. By default it uses a fully local solution (as documented).

> That's what you call "privacy" ?

Yes, it is local by default, but we give you the option to use what you please. We are agnostic in that regard.

>  Can I uninstall "assist"?

Yes, feel free to not use the assist integration.

> Who is your data protection officer ? (GDPR)?

You are. You decide what if you set up Google Assistant SDK. It can't be set up by us.

../Frenck

**Comment by stefanuytterhoeven** [comment]
ok, thanks. Uninstalling GA sdk then...
