### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by MortyFleem** [home-assistant/home-assistant.github.io#26314]
### Feedback

Wd really like to know how I can restore a backup using VirtualBox Linux on a Windows host machine after having uninstalled and reinstalled Virtual Box.

Where is the backup file very specifically stored?

Is it even stored in my computer somewhere. Very time consuming trying to find.

If no real, downloadable version of a Home Assistant backup exists, maybe it should??

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2023.2.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
