### ISSUE TITLE
Según log la integración fallará en version 2023.3

### ISSUE THREAD

**Issue by tergontor** [home-assistant/home-assistant.github.io#26322]
### Feedback

Hola, en el log de HA me sale el siguiente mensaje:
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for pvpc_hourly_pricing using this method at custom_components/pvpc_hourly_pricing/__init__.py, line 102: hass.config_entries.async_setup_platforms(entry, PLATFORMS

Tal como solicita os informo por si es necesario actuar.
Saludos y muchas gracias.

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2023.2.5

**Comment by klaasnicolaas** [comment]
It looks like you are using a custom integration and not the core integration, so you should raise this with the author of the custom integration.
