### ISSUE TITLE
Incorrect installation documentation in docker sections (- DISABLE_JEMALLOC: true)

### ISSUE THREAD

**Issue by Art-Shpiller** [home-assistant/home-assistant.github.io#26328]
### Feedback

In the optimization section, where the Docker Compose tab says `- DISABLE_JEMALLOC: true` 
This is not true it should be like this `- DISABLE_JEMALLOC=true`

### URL

https://www.home-assistant.io/installation/linux

**Comment by frenck** [comment]
Unfortunately, your comment is incorrect. Both are correct, depending if you using a mapping or array approach. We use the mapping approach, which is just as valid.

For the Docker compose file specification details, see here:

<https://docs.docker.com/compose/compose-file/#environment>

Thanks 👍 

../Frenck
