### ISSUE TITLE
i believe the code is wrong in the doc

### ISSUE THREAD

**Issue by Peacem4kr** [home-assistant/home-assistant.github.io#26336]
### Feedback

Hi, 

tbh.. so new to HA that i dont even know if i am sure of what i am saying.
I can only say that 2w ago i installed HA, tried to add Niko Home control and failed.
I removed a "dash" / "-" that is visible in the code presented by the doc.
And suddenly it all worked.

I did change some other stuff in the config.yaml, + i am new to this and i am no coder :), therefor i am not 100% sure

![image](https://user-images.githubusercontent.com/78316232/220646006-3a292bf8-0ea9-45b6-ad10-4f6802e857b1.png)

And i feel that this person is going to have the same issue, but waiting for feedback:
https://community.home-assistant.io/t/anyone-has-niko-home-control-working/508634/3

### URL

https://www.home-assistant.io/integrations/niko_home_control/

### Version

2023.2.5

**Comment by diothar** [comment]
Removing the dash isn’t what fixed the issue for you. Must have been something else you fixed. And the most common culprit for people new to YAML is incorrect spacing in front of each line.

**Comment by frenck** [comment]
Yup, diothar is most likely correct.

Anyways, the provided example in the documentation is correct.

../Frenck
