### ISSUE TITLE
consider "not home" time

### ISSUE THREAD

**Issue by do851her** [home-assistant/home-assistant.github.io#26345]
### Feedback

in the documentation following is noted

Consider home: Number of seconds that must elapse before considering a disconnected device “not at home”.

In the Integration however its noted that the setting for the seconds is "Seconds to consider a device at home".

From my experience it seams that the second statement is true since when my device disconnects even for a seconds the state of my device toggles to "not home" even after setting "10" in the settings.

Is this behaviour intended?
Kind regards

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2023.2.5

**Comment by mib1185** [comment]
both sentences mean the same - assume we have set this to 30 seconds

---

> Consider home: Number of seconds that must elapse before considering a disconnected device “not at home”.

after 30 seconds the device is not seen, it is considered as "not at home"

> In the Integration however its noted that the setting for the seconds is "Seconds to consider a device at home".

during first 30 seconds the device is not seen, it is considered as "at home"

---

in both cases, for the first 30s the device is "at home", afterwards it is "not at home"

---

> when my device disconnects even for a seconds the state of my device toggles to "not home"

if this means, your device is immediately "not at home", than this is a bug. If so, please report an issue at the HomeAssistant Core repository ([_here_](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml))

**Comment by do851her** [comment]
Thank you for the clarification Under "consider home" i understood the time it takes( after a device has been connected) to switch the status from "not home" -> "home". That would have been the exact opposite --Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 2/25/23, 13:08 Michael ***@***.***> wrote:

   
  both sentences mean the same - assume we have set this to 30 seconds 
   
   
   Consider home: Number of seconds that must elapse before considering a disconnected device “not at home”. 
   
  after 30 seconds the device is not seen, it is considered as "not at home" 
   
   In the Integration however its noted that the setting for the seconds is "Seconds to consider a device at home". 
   
  during first 30 seconds the device is not seen it is considered as "at home" 
   
  in both cases, for the first 30s the device is "at home", afterwards it is "not at home" 
   
   
   when my device disconnects even for a seconds the state of my device toggles to "not home" 
   
  if this means, your device is immediately "not at home", than this is a bug. If so, please report an issue at the HomeAssistant Core repository (here)
