### ISSUE TITLE
Debug Calendar

### ISSUE THREAD

**Issue by simatao** [home-assistant/home-assistant.github.io#26344]
### Feedback

I messed up my calendar with the service (trying to use {{now() | timezone_local()}}, now it no longer loads. How can I access the calendar database to manually delete the last couple of entries?

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2023.2.5

**Comment by frenck** [comment]
Thank you for reaching out. We use this GitHub tracker for documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
