### ISSUE TITLE
Presence and motion sensors too slow in camera 510A

### ISSUE THREAD

**Issue by Roni9011** [home-assistant/home-assistant.github.io#26357]
### Feedback

hello,
the integration works in general on my Reolink 510A but the update of the motion and people sensors are too slow. They take about 60 seconds to change state giving time to miss the presence of people and HA not seeing the sensor state change.
I understand that it should work as an interruption.

Thank you for taking my comment into account

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.2.5

**Comment by starkillerOG** [comment]
@Roni9011 probably your local homeassistant adress is not properly set under settings-->system-->network.
A HTTP not HTTP(S) local adress needs to be set in order for the reolink camera to sucesfully push motion events to HomeAssistant.

Could you try out HomeAssistant 2023.3 (beta or wait for the release on wednesday march 1st)?
This should auto detect this kind of issue and provide you with instructions on how to solve it.

Please let me know if HomeAssistant 2023.3 detected the issue correctly and if you were able to solve it.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by sycophantic** [comment]
Would there be a way to configure the non https url within the integration instead of changing the home assistant wide configuration?

**Comment by starkillerOG** [comment]
@sycophantic also requested and discussed here: https://github.com/starkillerOG/home-assistant/commit/1f21a9b1ce0863659d27f461b323b4bcfb0fad42#commitcomment-99826069

I will probably add that at some point, but it is not a priority right now.

**Comment by starkillerOG** [comment]
@sycophantic this PR https://github.com/home-assistant/core/pull/89625 will add the option to specify a HA URL used by the reolink integration (not global setting).

Edit: The PR was rejected, so this will not be added, for more info see https://github.com/home-assistant/core/pull/89625.

**Comment by frenck** [comment]
Hi there @sycophantic 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by sycophantic** [comment]
Hi @frenck 

How are we supposed to use this integration if we have the HA host behind a reverse proxy that has SSL? The PR should have been approved for advanced use cases. https://github.com/home-assistant/core/pull/89625
