### ISSUE TITLE
Support for Mopeka Pro Check-Water Sensor

### ISSUE THREAD

**Issue by stroodle96** [home-assistant/home-assistant.github.io#26359]
### Feedback

Mopeka also makes a lesser known water tank sensor. It looks very similar to the propane sensors so I would think adding support would just be a matter of getting units correct. 

I will be getting mine in today and can test. 

Here is a link to the page they sell them. 
https://www.mopekaiot.com/product/mopeka-pro-check-water-sensor-bottom-mount-w-collar

### URL

https://www.home-assistant.io/integrations/mopeka/

### Version

2023.2.5

### Additional information

https://www.mopekaiot.com/product/mopeka-pro-check-water-sensor-bottom-mount-w-collar

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
