### ISSUE TITLE
Luftdaten does not honor local DNS Settings

### ISSUE THREAD

**Issue by Xeroxxx** [home-assistant/home-assistant.github.io#26364]
### Feedback

I can see in my firewall and hassio_dns logs, that data.sensor.community is trying to call DOH 1.0.0.1 and 1.1.1.1 853. This is blocked and results in time to time "unavaliable" sensor data. 

In my network I do not allow any DNS traffic execpt to the configured ones via DHCP or Static. The configured ones are local DNS served by Unbound.

Why does the plugin trys to dodge or use DOH and does not honor local DNS Settings? Any need for this behavior?

Logs attached.

Cheers

### URL

https://www.home-assistant.io/integrations/luftdaten/

### Version

2023.2.5

### Additional information

hassio_dns

[INFO] 127.0.0.1:41592 - 43379 "AAAA IN data.sensor.community. udp 50 true 2048" NOERROR - 0 5.634183299s
[ERROR] plugin/errors: 2 data.sensor.community. AAAA: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:56076 - 42985 "A IN data.sensor.community. udp 50 true 2048" NOERROR - 0 5.634784385s
[ERROR] plugin/errors: 2 data.sensor.community. A: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 172.30.32.1:51935 - 42985 "A IN data.sensor.community. udp 39 false 512" NOERROR - 0 12.003319151s
[ERROR] plugin/errors: 2 data.sensor.community. A: read udp 127.0.0.1:38643->127.0.0.1:5553: i/o timeout
[INFO] 172.30.32.1:51935 - 43379 "AAAA IN data.sensor.community. udp 39 false 512" NOERROR - 0 12.003838072s
[ERROR] plugin/errors: 2 data.sensor.community. AAAA: read udp 127.0.0.1:41455->127.0.0.1:5553: i/o timeout
[INFO] 127.0.0.1:53305 - 42985 "A IN data.sensor.community. udp 50 true 2048" NOERROR - 0 5.054648916s
[ERROR] plugin/errors: 2 data.sensor.community. A: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:51348 - 43379 "AAAA IN data.sensor.community. udp 50 true 2048" NOERROR - 0 5.055651424s
[ERROR] plugin/errors: 2 data.sensor.community. AAAA: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:32938 - 5007 "NS IN . udp 17 false 512" NOERROR - 0 5.056403189s
[ERROR] plugin/errors: 2 . NS: dial tcp 1.0.0.1:853: i/o timeout

**Comment by Xeroxxx** [comment]
I cant find anything within the code of luftdaten. Is this related to hassio_dns?

https://github.com/home-assistant-ecosystem/python-luftdaten/

**Comment by Xeroxxx** [comment]
I checked hassio_dns. There is a fallback function that triggers when local dns cannot be reached. I cannot verfiy as there are not timestamps, however this maybe related to failed internet connection last 48 hours.

I think dev can close if they share the analysis.

**Comment by fabaff** [comment]
The module `luftdaten` is not doing anything fancy for the [requests](https://github.com/home-assistant-ecosystem/python-luftdaten/blob/master/luftdaten/__init__.py#L27-L30).
