### ISSUE TITLE
Optimizer data

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#26367]
### Feedback

Hi,

Are there any plans to include optimizer data in the future like https://github.com/ProudElm/solaredgeoptimizers

Regards,

Bart Janssens

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2023.2.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
