### ISSUE TITLE
Instructions on switching from z-wavejs to z-wavejsui don't work

### ISSUE THREAD

**Issue by jayph** [home-assistant/home-assistant.github.io#26366]
### Feedback

First step is to "disable", not remove, the z-wavejs integration. Second step is to get the network key from the integration. Unfortunately, disabling the integration removes it and the network key is no longer accessible. Fortunately I had made a backup just before and I was able to recover without rebuilding my entire z-wave network.

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2023.2.5

**Comment by MartinHjelmare** [comment]
The second step is to get the network keys from the official Z-Wave JS add-on, not from the integration.

https://www.home-assistant.io/integrations/zwave_js/#how-do-i-switch-between-the-official-z-wave-js-add-on-and-the-z-wave-js-ui-add-on
