### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by greck65** [home-assistant/home-assistant.github.io#26372]
### Feedback

Здравствуйте. Я подключил Smart TV Dexp h32h8001c через интеграцию Android tv. В HA работает громкость +/—, mute, power. Но при подключении к Yandex, работает только Power, mute. Как сделать чтоб яндекс делал громче на smart tv, и переключал каналы. Спасибо.

### URL

https://www.home-assistant.io/integrations/androidtv/

### Version

2023.2.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support. Please also communicate in English as we do not understand Russian 😉 

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
