### ISSUE TITLE
Need instruction on how to manually add device

### ISSUE THREAD

**Issue by IamGimli** [home-assistant/home-assistant.github.io#26370]
### Feedback

The Gree Climate plugin automatically scans for devices on the local network but it needs a way to manually add a device that's on a different subnet when the automatic scan doesn't return any devices.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2023.2.5

**Comment by frenck** [comment]
We can't add instructions for that, as it isn't able to add devices manually. So there is nothing to write.

../Frenck
