### ISSUE TITLE
Error on unsupported value

### ISSUE THREAD

**Issue by Voileux78** [home-assistant/home-assistant.github.io#26374]
### Feedback

Hi, 
I regulaly have this error poping-up in my HA Overkiz integration.
Below are the details
Many in advance

### URL

https://www.home-assistant.io/integrations/overkiz/

### Version

2023.2.5

### Additional information

Logger: pyoverkiz.enums.general
Source: components/overkiz/coordinator.py:71
First occurred: 08:01:27 (8 occurrences)
Last logged: 08:03:27

Unsupported value 20002 has been returned for <enum 'FailureType'>
Unsupported value 20001 has been returned for <enum 'FailureType'>

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
