### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Eigeman** [home-assistant/home-assistant.github.io#26373]
### Feedback

Hi, I've used your add on in the past, and modified it a bit to show me delays (that is more useful than the actual train departures). So, could you add a sensor that shows the delays (or severity of delays, like trains not running at all, delays > 10 minutes, something like that).

### URL

https://www.home-assistant.io/integrations/nederlandse_spoorwegen/

### Version

2023.2.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
