### ISSUE TITLE
LaCrosse Sensors stopped updating in Home Assistant

### ISSUE THREAD

**Issue by CabbageSmell** [home-assistant/home-assistant.github.io#26371]
### Feedback

I noticed today that my Lacrosse clock no long updates any of its sensors in Home Assistant.  I reinstalled the integration and all I get for data is "Unavailable" and a red exclamation point.

The integration does seem to connect to Lacrosse's web server to login but it just isnt giving any sensor data.  My clock is updating its own face display just fine from Lacrosse but the home assistant Lacrosse View integration is no longer getting any sensor data.

I use the data from the humidity sensor in Node Red to control when my humidifier turns on and off, based on both the outdoor temp and the indoor temp.  I used to use a DHT22 sensor with a wemos esp board but those kept dying on me, it was a very nice reliability upgrade when the lacrosse integration came out but now I am missing the essential data again to keep my house comfortable and healthy with the humidity.  When Home Assistant is getting the data it is able to keep the humidity in my house at its maximum in winter without the windows frosting up and allowing mold to grow.  Too little humidity and it is hard to sleep because of nose/throat dryness, and wood can crack.

### URL

https://www.home-assistant.io/integrations/lacrosse_view/

### Version

2023.2.5

### Additional information

Latest Home Assistant running on RPi 4 and unifi networking.

**Comment by IceBotYT** [comment]
Hi there.
I deeply apologize for this issue.
Could you please provide some logs from [here](https://my.home-assistant.io/redirect/logs/) so I can get a better understanding of the issue?

Thank you!

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
