### ISSUE TITLE
Setting an entity id

### ISSUE THREAD

**Issue by davs2rt** [home-assistant/home-assistant.github.io#26378]
### Feedback

I'm trying to set a unique entity id and about halfway down the page,I encounter this line:

> If your entity is not supported, or you cannot customize what you need via this method, please see below for more options.

But nothing below this line helps to set an entity id.  It's all icons and warnings for other features.

### URL

https://www.home-assistant.io/docs/configuration/customizing-devices/

### Version

2023.2.5

**Comment by frenck** [comment]
> But nothing below this line helps to set an entity id.

That is correct, that can't be changed in that case.

../Frenck
