### ISSUE TITLE
Assist

### ISSUE THREAD

**Issue by sewershagger** [home-assistant/home-assistant.github.io#26388]
### Feedback

The Assist has a flaw.

It provided temperature in Fahrenheit.

I told it to only provide temperature in Celsius from now on.

Now it provides Fahrenheit values as Celsius. For example, it states 68 Celsius instead of 20 Celsius or 68 Fahrenheit. So it has only corrected the unit, but hasn't converted the value.

The value is converted correctly when I specifically ask it to give the value in Celsius in each command. 

### URL

https://www.home-assistant.io/docs/assist/

### Version

2023.2.5

**Comment by sewershagger** [comment]
I have found a solution. I told it to convert Fahrenheit to Celsius from now on. Assist then responds to all temperature queries with both the Fahrenheit and Celsius value. 
I then told Assist to not provide the Fahrenheit value, now it only provides results in Celsius using correct conversion.

**Comment by frenck** [comment]
Hi there @sewershagger 👋 

> The Assist has a flaw.

It sounds like you want to report an issue with an Home Assistant feature, however, you have submitted documentation feedback instead. Please report bugs here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
