### ISSUE TITLE
Add PIN to the integration to arm and disarm the alarm.

### ISSUE THREAD

**Issue by NoCodeMaster** [home-assistant/home-assistant.github.io#26382]
### Feedback

I haven't been able to find a way to add a PIN to the arming and disarming action from Home Assistant. Is that possible?

### URL

https://www.home-assistant.io/integrations/prosegur/

### Version

2023.2.5

**Comment by dgomes** [comment]
Hi it is not possible, and this is not the right place for asking support :)
