### ISSUE TITLE
Instructions are really not instructions

### ISSUE THREAD

**Issue by minttumaa** [home-assistant/home-assistant.github.io#26395]
### Feedback

"If the systemd-resolved service is not running or disabled, enable and start it."

Is not very useful. Please, tell how to install, enable and start it instead. Most of these pages are missing actual help, they are just stating what I already know (=I have problem). Maybe even start with how to check if you have it or not.

This same problem is on many of your pages :/

### URL

https://www.home-assistant.io/more-info/unsupported/systemd_resolved/

### Version

2023.2.5

**Comment by frenck** [comment]
> Is not very useful. Please, tell how to install, enable and start it instead. 

Hi there! As per our documentation and specifications, the installation method that is affected by this (Home Assistant Supervised), is expected to be used by users with extensive knowledge and depth of Docker, Networking, and Linux system administration. 

For more information on that see: <https://www.home-assistant.io/installation/linux#install-home-assistant-supervised>

Which link to the requirements in the first step (after the warning), here:  <https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>

The latter has clearly outlined both system and what is expected to be supported and what is not. In this case, this is an issue with the operating system you are managing, not us. Please consult the documentation of your operating system.

If this answer doesn't ring a bell for you, we'd strongly recommend considering using a different installation method (please don't take this the wrong way, it is honest advise).

../Frenck
