### ISSUE TITLE
Tractive: Potential Battery drain by Home Assistant?

### ISSUE THREAD

**Issue by EpicLPer** [home-assistant/home-assistant.github.io#26393]
### Feedback

I'm seeing unusually high battery usage on my tracker, and I'm wondering if Home Assistant could be the cause of this. How exactly does the Home Assistant integration gather its infos from the tracker? Does it start the live tracking every so often by itself to get the current position or does it only grab the info that the tracker last sent? Sometimes the battery percentage updates as fast as under 10 minutes, while other times it gathers it every ~30 minutes or so.

![image](https://user-images.githubusercontent.com/8442196/221908164-66a3c5f0-8ced-416a-bdb9-d0ab56ebb45a.png)

The tracker barely survives for 2 days on a charge, a 3rd day without charging is very unusal. I can't use the energy saving zone since my WiFi is so strong it actually still works 2 streets over and never tracks my cat then.

### URL

https://www.home-assistant.io/integrations/tractive/

### Version

2023.2.5

**Comment by zhulik** [comment]
The integration cannot cause these issues. It only consumes events coming from tractive's servers. It also doesn't implicitly enable live tracking.

**Comment by EpicLPer** [comment]
> The integration cannot cause these issues. It only consumes events coming from tractive's servers. It also doesn't implicitly enable live tracking.

Thanks for that info :) Guess I'll contact Tractive support then why the tracker sends events so often.
