### ISSUE TITLE
LED light only controllable on 1 of 2 3way switches

### ISSUE THREAD

**Issue by ifuchs** [home-assistant/home-assistant.github.io#26392]
### Feedback

I have a pair of HS210 wall switches. These are 3 way switches that control one light. If I turn off the LED, only the LED on one of the switches (the slave) is affected. This seems to be what happens if I use the Kasa iOS app as well. Is there a way to control both LEDs?

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2023.2.5

**Comment by rytilahti** [comment]
If the official app does not support it, I don't think that's possible.
