### ISSUE TITLE
Home Assistant SkyConnect website and Home Assistant SkyConnect webpage has no links or redirects to each other

### ISSUE THREAD

**Issue by Hedda** [home-assistant/home-assistant.github.io#26406]
### Feedback

FYI,  noticed Home Assistant SkyConnect website and Home Assistant SkyConnect webpage has no links or redirects to each other:

https://www.home-assistant.io/skyconnect/

and

https://skyconnect.home-assistant.io/

At this time that website and the webpage do not look to share any information or link to each other as they probably should.

Maybe consider merging https://www.home-assistant.io/skyconnect/ into https://skyconnect.home-assistant.io/ or vice versa?

### URL

https://www.home-assistant.io/skyconnect/

### Additional information

Also noticed that almost the same goes for Home Assistant Yellow -> https://github.com/home-assistant/home-assistant.io/issues/26407

i.e.

https://www.home-assistant.io/yellow/

and

https://yellow.home-assistant.io/

**Comment by c0ffeeca7** [comment]
Closed by #26859
