### ISSUE TITLE
Home Assistant Yellow website and Home Assistant Yellow webpage has no links or redirects to each other

### ISSUE THREAD

**Issue by Hedda** [home-assistant/home-assistant.github.io#26407]
### Feedback

FYI,  noticed Home Assistant Yellow website and Home Assistant Yellow webpage have no links or redirects to each other:

https://www.home-assistant.io/yellow/

and

https://yellow.home-assistant.io/

At this time that website and the webpage do not look to share any information or link to each other as they probably should.

Maybe consider merging https://www.home-assistant.io/yellow/ into https://yellow.home-assistant.io or vice versa?

### URL

https://www.home-assistant.io/yellow/

### Additional information

Also noticed that almost the same goes for Home Assistant SkyConnect -> https://github.com/home-assistant/home-assistant.io/issues/26406

i.e.

https://www.home-assistant.io/skyconnect/

and

https://skyconnect.home-assistant.io/

**Comment by c0ffeeca7** [comment]
Thank you, @Hedda.
Closed by #26859
