### ISSUE TITLE
iCloud account connection

### ISSUE THREAD

**Issue by larry404** [home-assistant/home-assistant.github.io#26412]
### Feedback

Hi, the Apple iCloud service connection requires that we provide our iCloud email address (fair enough) with our actual iCloud password. Note that I do not provide my iCloud password to anyone. For me this is higher risk that providing my bank password. Apple have a option called App-Specific Passwords. You're probably aware of it and haven't implemented for a specific reason. However, if by any chance you are not aware I am providing you the URL for more information. https://support.apple.com/en-us/HT204397

I hope you will be able to implement this as the icloud integration feature would be great.

Thanks.

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2023.2.5

**Comment by dlasher** [comment]
This issue is still relevant. I have to re-auth at least every 7 days, and the integration doesn't realize it's "lost" awareness. Application passwords (which apple supports) is the right way to do this.

**Comment by linust** [comment]
Still a major issue.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
