### ISSUE TITLE
not able to do integration

### ISSUE THREAD

**Issue by ankitirse** [home-assistant/home-assistant.github.io#26419]
### Feedback

i am using a pfsense router. I am trying to connect am esp32 to homeassistant. in the home assistant the esp32 is automatically discovered  but when i try to integrate it says "Can't connect to ESP. Please make sure your YAML file contains an 'api:' line." the HA is running as a OS. if i complete this part everythintg will be sorted

### URL

https://www.home-assistant.io/integrations/esphome/

### Version

2023.3.0

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
