### ISSUE TITLE
How do I change the god-awful choice of colours of red and green?

### ISSUE THREAD

**Issue by derekcfoley** [home-assistant/home-assistant.github.io#26414]
### Feedback

feedback? what do I put here?

### URL

https://www.home-assistant.io/dashboards/history-graph/

### Version

2023.2.5

### Additional information

How do I change the god-awful choice of colours of red and green?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by derekcfoley** [comment]
The issue is with not being able to read this being colour blind and home assistant not having a built in method to change it without mucking about with complex add-ons and code

That IS an issue!

**Comment by frenck** [comment]
Sure, but you have submitted documentation feedback which contained a question not documentation feedback and not a bug report.

If you are unsure where to go, check:

http://www.home-assistant.io/help

../Frenck
