### ISSUE TITLE
TP-Link Omada Integration - Unexpected error

### ISSUE THREAD

**Issue by WNTLtd** [home-assistant/home-assistant.github.io#26420]
### Feedback

I know this is a brand new integration - one I've been waiting for tbh.

I enter the IP addr of my OC200, and I enter my username and password - but on clicking submit, I get Unexpected error come up above the ip addr - and all fields are cleared.

I enabled the remote management within the OC200 too. but to no avail.
I don't use ssl to access the OC200 interface - so I unticked the Verify Cert checkbox.
Does it HAVE to have an SSL cert for this integration to work?

What could I be possibly doing wrong?

### URL

https://www.home-assistant.io/integrations/tplink_omada/

### Version

2023.3.0

### Additional information

Controller Version 5.7.6
Model OC200 1.0
Firmware Version 1.21.7 Build 20221206 Rel.58608

**Comment by MarkGodwin** [comment]
This is the repo for documentation issues. The same problem has been reported over here… [#88934](https://github.com/home-assistant/core/issues/88934) 

Currently, it will only work if you use a DNS name for your controller, not an IP address. Sorry, you’ll have to wait a few days more.

@home-assistant close

**Comment by MarkGodwin** [comment]
@home-assistant close
