### ISSUE TITLE
 Integration is not starting properly after last HA update

### ISSUE THREAD

**Issue by tlewandster** [home-assistant/home-assistant.github.io#26424]
### Feedback

After the recent HA update to version 2023.3.0, the Vulcan integration is not starting properly. There is the following entry in the logs: 
```
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 08:06:41 (3 occurrences)
Last logged: 08:07:11

Unable to install package vulcan-api==2.2.1: ERROR: Cannot install vulcan-api==2.2.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
```

### URL

https://www.home-assistant.io/integrations/vulcan/

### Version

2023.3.0

**Comment by frenck** [comment]
Hi there @tlewandster 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
