### ISSUE TITLE
Please rename the "Assist" feature

### ISSUE THREAD

**Issue by brintal** [home-assistant/home-assistant.github.io#26426]
### Feedback

Please think about renaming the "Assist" feature NOW as long it is still new and not used very much.
This is an awesome feature which will certainly grow and become more important in the future.

But calling everything in the smart home world "assistant" or some variation of it is just confusing and will probably become a serious issue in the future.

E.g. I just tried to find if there is already some way to connect Google Assistant to the new "Assist" feature and as expected, searching for
"Connect Google Assistant to Home Assistant Assist" 
was not very successful. 
Same with "Home Assistant Assist API" to see if there is any way to programmatically call the Assist feature.

I'm not very creative in this regard but I would go for something like
"Home Assistant Speak", "Home Assistant Mate" or something along those lines.

### URL

https://www.home-assistant.io/docs/assist/

### Version

2023.3.0

**Comment by frenck** [comment]
Thank you for reaching out. We track documentation feedback here, not providing support or tracking feature requests. What you are suggesting, is not just a documentation change.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
