### ISSUE TITLE
Possible incomplete install instructions

### ISSUE THREAD

**Issue by sciurius** [home-assistant/home-assistant.github.io#26425]
### Feedback

When installing HA Core on Fedora 37 (either python 3.10 and 3.11) I need some additional packages:

dateutils : probably only for the caldav integration
psycopg2 : for recording with a PostgreSQL database
numpy :  no idea why

### URL

https://www.home-assistant.io/installation/linux/

### Version

2023.3.0

### Additional information

FYI.

**Comment by frenck** [comment]
It depends on your setup (system, environment, usage). Hence the warning on the page that covers this.

../Frenck
