### ISSUE TITLE
Automations - How are multiple conditions handled?

### ISSUE THREAD

**Issue by W0GER** [home-assistant/home-assistant.github.io#26432]
### Feedback

For Automations, If I have 2 or more conditions in the Conditions section of the UI how are those conditions handled? 

In other words, will the trigger happen when at least 1 condition is evaluated to be true, or do ALL conditions have to evaluate to true? 

### URL

https://www.home-assistant.io/docs/automation/basics/

### Version

2023.3.0

**Comment by frenck** [comment]
<img width="700" alt="CleanShot 2023-03-02 at 23 55 09@2x" src="https://user-images.githubusercontent.com/195327/222578549-c7c71a7f-ad0a-45be-b717-0f71020a3bd2.png">

<https://www.home-assistant.io/docs/scripts/conditions/>

../Frenck
