### ISSUE TITLE
Page needs to be renamed

### ISSUE THREAD

**Issue by AJediIAm** [home-assistant/home-assistant.github.io#26433]
### Feedback

Please consider changing the helper me to something like "Arithmetic", "Calculator" or "Combined state".

After that, this page should be renamed accordingly.

### URL

https://www.home-assistant.io/integrations/min_max/

### Version

2023.3.0

**Comment by frenck** [comment]
This specific integration is a candidate for removal. We are working on a migration path. Changing the name would therefore be a loss of time. Please use sensor groups instead.

https://www.home-assistant.io/integration/group

Thanks 👍 

../Frenck

**Comment by AJediIAm** [comment]
Thanks!
