### ISSUE TITLE
IR lamp not triggering black and white modes

### ISSUE THREAD

**Issue by danielhassio** [home-assistant/home-assistant.github.io#26431]
### Feedback

Using the IR lamp on/off switch will not trigger the black and white exposure mode.
As color camara modes dont pick up the IR illumination either black and white should be enabled or a switch should be added.

### URL

https://www.home-assistant.io/integrations/onvif/

### Version

2023.3.0

**Comment by frenck** [comment]
Hi there @danielhassio 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
