### ISSUE TITLE
yallo home box compatibility?

### ISSUE THREAD

**Issue by tazztone** [home-assistant/home-assistant.github.io#26446]
### Feedback

doesnt seem to work with yallo box (ARRIS TG3492LG-YL) (which looks identical to upc giga connect box i owned before)

my config:
device_tracker:
  - platform: upc_connect
    password: xxxxx
    host: 192.168.1.1
    interval_seconds: 10
    consider_home: 180
    new_device_defaults:
      track_new_devices: true

can't find any entities or devices after multiple restarts. i am noob tho

### URL

https://www.home-assistant.io/integrations/upc_connect/

### Version

2023.3.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by tazztone** [comment]
well you are not upc_connect dev are you?
didn't ask for support either

**Comment by frenck** [comment]
@tazztone No, I'm actually the Home Assistant project maintainer and core dev, and I really suggest you quickly adjust the tone in that response.

You have submitted documentation feedback, which is not the place for getting questions answered, I friendly redirected you to the place where you can get support and are more likely to get an answer.

../Frenck

**Comment by tazztone** [comment]
not sure where u find "tone" in a written response. also i didn't ask a question - rather wanted to give specific feedback to the upc_connect guys that the "yallo home box" router which is built identical to "giga connect box" router of this integration does not work as far as i can tell.

**Comment by frenck** [comment]
> not sure where u find "tone" in a written response

I'm happy to point out:

> well you are not upc_connect dev are you?

☝️ There.

Anyways, cool, please use the community forums for that. Thanks 👍 

../Frenck

**Comment by tazztone** [comment]
well then sorry 
but u see this may be what baited me to post here: 
![image](https://user-images.githubusercontent.com/62671577/222772324-8299f70e-57e3-46f7-8c81-f1edbf9e4c75.png)

**Comment by frenck** [comment]
Alright, thanks, please use the forums 👍 

../Frenck

**Comment by fabaff** [comment]
@tazztone, see https://community.home-assistant.io/t/integration-for-arris-tg3492lg-zg-ziggo-connectbox-giga/456610
