### ISSUE TITLE
Nod On SIN-2-RS-01 EnOcean

### ISSUE THREAD

**Issue by rentenz** [home-assistant/home-assistant.github.io#26445]
### Feedback

Hello Guys,
thank you for your great work! 
Is it possible to integrate the Nod On SIN-2-RS-01 EnOcean modules. I have them in the hole House integrated with Openhab.  I changed now complete to Home Assistant just this peace is missing. And that is the part why I started automation.
If I can help you anything or test something. I am happy to do that.
Cheers

### URL

https://www.home-assistant.io/integrations/enocean/

### Version

2023.3.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
