### ISSUE TITLE
Doesn't search for issues with tags

### ISSUE THREAD

**Issue by IgorGlebovGIS** [home-assistant/home-assistant.github.io#26443]
### Feedback

 calendar: #Добавляемый компонент Календарь 
  - platform: todoist
    token: !secret todoist_api_token
    custom_projects:
     - name: Задачи Святослава
       labels:
        - Homework
       include_projects:
        - Домашние дела всем

### URL

https://www.home-assistant.io/integrations/todoist/

### Version

2023.2.5

### Additional information

Good afternoon. I can't set up a calendar with labels.
When I add labels: to the config file, I get the state of the calendar off.

I removed the include_projects: line from the code, so that I would search for all projects with a label, but I also get the calendar status turned off.

    custom_projects:
     - name: Задачи Святослава
       labels:
        - Homework
       include_projects:
        - Домашние дела всем
![01](https://user-images.githubusercontent.com/46665328/222690779-54f63b4d-2f24-4145-8727-a15c88e68788.jpg)
![02](https://user-images.githubusercontent.com/46665328/222690786-d246f498-1fe3-452e-9577-f327495fe0de.jpg)
![03](https://user-images.githubusercontent.com/46665328/222690791-cef09b32-f703-40bc-97d5-f74f1b3bdf33.jpg)

**Comment by boralyl** [comment]
@IgorGlebovGIS Thank you for opening an issue.

I ran a few tests and was only able to reproduce this immediately after a restart, after the entity is updated the calendar will be `on` as expected.

For clarity, I created a project named `Test`.  I added 2 tasks, one in the `Test` project and one in the `Inbox` project.  Both were given the `hatest` label. One had a due date and the other did not.

My custom project for this test (I also tested without using `include_projects`):
```yaml
    custom_projects:
      name: HA Test
      labels:
        - hatest
      include_projects:
        - Test
```

![image](https://user-images.githubusercontent.com/109865/222925303-e19ec1a5-b77c-48d0-9375-8d5520fb4510.png)

After the calendar entity is updated it shows as `on` in the developer tools:
![image](https://user-images.githubusercontent.com/109865/222925368-ac1dd45e-4e59-44d9-b656-02913ee9a8b3.png)

Let me know if I misinterpreted the issue you are experiencing or if there are additional steps I need to take to reproduce it.

**Comment by frenck** [comment]
Hi there @IgorGlebovGIS 👋 

It seems like you wanted to report an issue with an Home Assistant integration, however,  you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by IgorGlebovGIS** [comment]
> @IgorGlebovGISСпасибо, что открыли тему.
> 
> Я провел несколько тестов и смог воспроизвести это только сразу после перезапуска, после обновления объекта календарь будет `on`таким, как ожидалось.
> 
> Для ясности я создал проект с именем `Test`. Я добавил 2 задачи, одну в проекте `Test`и одну в `Inbox`проекте. Оба получили `hatest`ярлык. У одного был срок, а у другого нет.
> 
> Мой собственный проект для этого теста (я также тестировал без использования `include_projects`):
> 
> ```yaml
>     custom_projects:
>       name: HA Test
>       labels:
>         - hatest
>       include_projects:
>         - Test
> ```
> 
> ![изображение](https://user-images.githubusercontent.com/109865/222925303-e19ec1a5-b77c-48d0-9375-8d5520fb4510.png)
> 
> После обновления объекта календаря он отображается так же, как `on`в инструментах разработчика: ![изображение](https://user-images.githubusercontent.com/109865/222925368-ac1dd45e-4e59-44d9-b656-02913ee9a8b3.png)
> 
> Дайте мне знать, если я неправильно истолковал проблему, с которой вы столкнулись, или если мне нужно предпринять дополнительные шаги, чтобы воспроизвести ее.

Hello dear friend. Thank you for sending me your example from HA.
Unfortunately, I never got the desired result.
I followed your path: I created a new project: testXA, added a task to it and gave it a label, after which I changed the configuration file. Restarted HA, waited more than 1 hour, but the calendar status is still inactive.

calendar: #Добавляемый компонент Календарь 
  - platform: todoist
    token: !secret todoist_api_token
    custom_projects:
     name: Ha TEST
     labels:
        - homework
![01](https://user-images.githubusercontent.com/46665328/222959797-e20ecebb-2e04-44fc-81d4-848fb454155a.jpg)
![02](https://user-images.githubusercontent.com/46665328/222959798-90492cea-48cb-441e-b86e-9ff8bf122261.jpg)

**Comment by frenck** [comment]
Please seem my comment above, this is taking place in the wrong place.

../Frenck

**Comment by IgorGlebovGIS** [comment]
Hello dear friend. Thank you for sending me your example from HA.
Unfortunately, I never got the desired result.
I followed your path: I created a new project: testXA, added a task to it and gave it a label, after which I changed the configuration file. Restarted HA, waited more than 1 hour, but the calendar status is still inactive.

calendar: #Добавляемый компонент Календарь

platform: todoist
token: !secret todoist_api_token
custom_projects:
name: Ha TEST
labels:
- homework

![01](https://user-images.githubusercontent.com/46665328/222960285-8382f915-fc5c-41ca-9734-fdf33562c316.jpg)
![02](https://user-images.githubusercontent.com/46665328/222960286-2d8c8564-8bf3-4cf4-aea5-12d2177e1810.jpg)
