### ISSUE TITLE
Invisible card takes up space

### ISSUE THREAD

**Issue by Seva44** [home-assistant/home-assistant.github.io#26452]
### Feedback

[https://drive.google.com/file/d/1HBpJ7-HE6r2tXVrgczFPJ_jsWKfNd46S/view?usp=share_link](url)
video link

### URL

https://www.home-assistant.io/dashboards/conditional/

**Comment by frenck** [comment]
Hi there @Seva44 👋 

It seems like you want to report an issue with the Home Assistant frontend, however, you have submitted documentation feedback instead. Please report issues with the Home Assistant frontend here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
