### ISSUE TITLE
A simple question is not answered.

### ISSUE THREAD

**Issue by PD202010** [home-assistant/home-assistant.github.io#26456]
### Feedback

If you add multiple conditions to an automation, do they all need to pass (AND)  or is a single one (OR) sufficient.  Of course you can always start your condition-set with an AND or OR option, but it would be better if the documentation directly states what happens when multiple conditions are true. 

Also, as long as it is not documented, people should implicitly use an AND or OR as the undocumented behaviour can be subject to change. So why not make it clear for once and for all and document it properly.

### URL

https://www.home-assistant.io/docs/automation/condition/

### Version

2023.3.1

**Comment by frenck** [comment]
<img width="724" alt="CleanShot 2023-03-04 at 22 48 13@2x" src="https://user-images.githubusercontent.com/195327/222930103-7f002703-d064-41ea-98d5-bfec8b06e133.png">

Ref: <https://www.home-assistant.io/docs/scripts/conditions/>

../Frenck

**Comment by PD202010** [comment]
What is clear to a developer or advanced user doesn't necessarily have to be clear to a beginner. And is the documentation not meant to be read by beginners? 

Closing this issue because the answer can be found elsewhere is a bit too easy. I could also use a search engine, apply trial and error, etc. 

Something as trivial as this, should be listed on the documentation-page where you were sent to if you click the question-mark near the 'conditions' heading in the automations pane. There is it where you land, that is the place where you would expect to find an proper explanation. Otherwise you could just as well remove most documentation-pages and replace them by a text similar to: "Try uncle google!"

**Comment by frenck** [comment]
> What is clear to a developer or advanced user doesn't necessarily have to be clear to a beginner. And is the documentation not meant to be read by beginners?

Sorry, I'm confused, you originally wrote:

_"do they all need to pass (AND) or is a single one (OR) sufficient."_

and

_So why not make it clear for once and for all and document it properly._


Your latest response is not the questions you raised in your original posting.

Nevetheless, that part doesn't look developer approach at all.

> Closing this issue because the answer can be found elsewhere is a bit too easy.

? The page you comment on, is clearly referring to the page I linked, which explicitly states it in the introduction. If you are saying it is hidden, thank I'm sorry, but I don't agree.

I think the rest of your response is a bit pulling things out of context to make your point, and therefore I will not respond to that.

Nevertheless, thanks for your feedback 👍 

../Frenck
