### ISSUE TITLE
Z-Wave.me connet by Ip but no Devices shown

### ISSUE THREAD

**Issue by DerGrafausB** [home-assistant/home-assistant.github.io#26459]
### Feedback

No Device or state is shown.

Any Idea?

### URL

https://www.home-assistant.io/integrations/zwave_me/

### Version

2023.3.1

**Comment by PoltoS** [comment]
Hello! Please provide more info: logs on HA side, logs on Z-Way side during the connection (maybe there is an error?). Sure the user the token belongs to has access to devices?

**Comment by DerGrafausB** [comment]
I tried 2 Token, the admin and an user with access to all devices.
I don't find anything in the logs with "z-way"
It is the same with the debug log.
Can I send you my logs by wetransfer?

**Comment by PoltoS** [comment]
Sure, you can send the log via any transfer system or write us at https://help.z-wave.me. You can also provide a token with only one device granted to the support team and we will check it. Sure there are no errors in the HA log?

**Comment by PoltoS** [comment]
Have you checked with the new HA? We fixed the roller shutter support that lead to no devices shown.
