### ISSUE TITLE
Great Job with redirects from the My Home Assistant service.

### ISSUE THREAD

**Issue by greystone813** [home-assistant/home-assistant.github.io#26453]
### Feedback

thank you for this piece of information:  https://www.home-assistant.io/integrations/my/

I was having an issue with my HA and couldn't use any of the My assisted links. Only after googling, reading and trying a bunch of stuff, i stumbled upon the above link.  Once i completed the steps outline (with a reboot of HA), i could finally link to things using the assisted linkage apps and get things properly integrated into Home Assistant.

### URL

https://www.home-assistant.io/integrations/my/

### Version

2023.3.1

**Comment by balloob** [comment]
You're welcome!
