### ISSUE TITLE
Atributtes

### ISSUE THREAD

**Issue by Vicente-Ch** [home-assistant/home-assistant.github.io#26451]
### Feedback

Hello, I would like to show the position history of the blind.  "Cover.persiana_salon.current_position"

![Screenshot_2023-03-04-09-02-14-172_io homeassistant companion android](https://user-images.githubusercontent.com/79970700/222884705-01152804-bf59-4eeb-8cd7-91b328f490dd.jpg)

 But this card does not give the option to show the attributes of the entity.  Only if it is open or closed

![Screenshot_2023-03-04-09-16-58-015-edit_io homeassistant companion android](https://user-images.githubusercontent.com/79970700/222885175-ba8074bd-3348-4345-a9ee-27ca558c642b.jpg)

### URL

https://www.home-assistant.io/dashboards/history-graph/

### Version

2023.3.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
