### ISSUE TITLE
Missing "set_preset_mode" in Humidifier services

### ISSUE THREAD

**Issue by kissiel7** [home-assistant/home-assistant.github.io#26457]
### Feedback

It's impossible to set Home/Away mode for Humidifier. This is problematic especially for Generic_Hygrometer, where presence mode exists and can be set manually, but there is no way to set it using automation.
I would expect that it should be similar like for "Climate" integration, where such service exists.

### URL

https://www.home-assistant.io/integrations/humidifier/

### Version

2023.3.1

**Comment by Shulyaka** [comment]
Hi @kissiel7, the service is called `humidifier.set_mode`

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by kissiel7** [comment]
It doesn't seem to work with Generic Hygrostat integration.
Using set_mode to "home" or "away" on Generic Hygrostat does nothing, therefore there is no standard way to automate this mode for Generic Hygrostat.

**Comment by frenck** [comment]
If you want to report a bug, please open a bug in our issue tracker (as you have submitted documentation feedback here). You can find our issue tracker here:

<https://github.com/home-assistant/core/issues>

../Frenck

**Comment by Shulyaka** [comment]
@kissiel7 For generic_hygrostat it switches the target humidity to a different 'away' humidity. If that does not work, please raise the issue as Frenck suggested.
