### ISSUE TITLE
Add info according communication protocol

### ISSUE THREAD

**Issue by Palo47** [home-assistant/home-assistant.github.io#26467]
### Feedback

I think it would be useful to add a short note that it communicates on the basis of UDP but the actual communication with the inverter is done by MODBUS protocol (I hope I'm right).

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2023.3.1

**Comment by frenck** [comment]
Why does that matter?

**Comment by starkillerOG** [comment]
@Palo47 you are right, and I could add a note in the documentation, but indeed why does that matter?

**Comment by Palo47** [comment]
I didn't write that it's important but that it COULD be useful. I was thinking of more technically oriented usersPavol Dňa 6. 3. 2023 o 12:53 užívateľ Franck Nijhof ***@***.***> napísal:﻿
Why does that matter?

**Comment by starkillerOG** [comment]
@Palo47 here is the PR https://github.com/home-assistant/home-assistant.io/pull/26468 to add the info.
@frenck feel free to reject and close the PR if you feel like mentioning the protocol it is too much information.

**Comment by Palo47** [comment]
For me it is enough to confirm that it is Modbus over UDP

**Comment by Palo47** [comment]
Hi.I found some hours ago maybe some small issue in the GW integration.The entity “ Today energy export/importt” use has not correct value in comparison with Shelly 3EM. See attachment.Thank you PavolDňa 6. 3. 2023 o 13:02 užívateľ starkillerOG ***@***.***> napísal:﻿
@Palo47 you are right, and I could add a note in the documentation, but indeed why does that matter?

**Comment by starkillerOG** [comment]
@Palo47 attachements do not come through over e-mail.
Please go to github.com and upload there.

**Comment by frenck** [comment]
@Palo47 If you have issues, please report them in the Core issue tracker. This is not the right place for that. Thanks 👍

**Comment by frenck** [comment]
> I didn't write that it's important but that it COULD be useful.

I think it is an implementation detail that shouldn't matter. Just like we don't write how Hue works over the HTTP protocol, or how WLED uses both HTTP requests and WebSockets.

It only adds technical jibberish, which isn't relevant and only can confuse less technical people.

For that reason, I don't think we should add stuff like that.

../Frenck

**Comment by mletenay** [comment]
1) The statement that it communicates by MODBUS is not even 100% correct. 
Yes, some inverters do use modbus encoding and addressing over UDP, but there are inverter types which do not.
2) Any explicit mention to modbus may confuse users with the real https://www.home-assistant.io/integrations/modbus/ integration (or even encourage them to mess with their devices, which may be dangerous to brave but stupid ones ...).
3) It is extremely low-level technical detail the end users should not be bothered at all.

I am going to close this ticket as invalid.

**Comment by mletenay** [comment]
@home-assistant close

**Comment by Palo47** [comment]
Hi.Apparently, you have a guilty conscience.But thank you for the useful information for me in this email of yoursPavol Dňa 6. 3. 2023 o 14:30 užívateľ mletenay ***@***.***> napísal:﻿

The statement that it communicates by MODBUS is not even 100% correct.
Yes, some inverters do use modbus encoding and addressing over UDP, but there are inverter types which do not.
Any explicit mention to modbus may confuse users with the real https://www.home-assistant.io/integrations/modbus/ integration (or even encourage them to mess with their devices, which may be dangerous to brave but stupid ones ...).
It is extremely low-level technical detail the end users should not be bothered at all.

I am going to close this ticket as invalid.
