### ISSUE TITLE
Phase voltage and currents as sensors to Keba Charging Station integration

### ISSUE THREAD

**Issue by jouniaaltonen** [home-assistant/home-assistant.github.io#26461]
### Feedback

Hello

Keba Charging Station HA-integration is almost perfect but would it be possible to add phase voltages and currents as sensors? Report 3 U1, U2, U3, I1, I2 and I3.

Thank you :)

### URL

https://www.home-assistant.io/integrations/keba/

### Version

2023.3.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by dannerph** [comment]
@jouniaaltonen I am already working on it, please have a look on the beta version (custom integration) https://github.com/dannerph/homeassistant-keba
