### ISSUE TITLE
Unable to reach website in Egypt

### ISSUE THREAD

**Issue by ihabmurad** [home-assistant/home-assistant.github.io#26462]
### Feedback

**As a user of Home Assistant,** I have been trying to access the website for some time now, but unfortunately, I have been unable to do so. I have checked with my internet service provider, and they have confirmed that the website is not blocked on their end.

I wanted to bring this issue to your attention in case there is an underlying technical problem that is preventing users in Egypt from accessing the website. I would appreciate it if you could investigate the issue and provide a solution as soon as possible.
This problem will prevent users from installing the system, the Preparing Home Assistant process will take infinite time, and there will be no access to the documentation and forums.

Thank you for your attention to this matter.

### URL

https://www.home-assistant.io/

### Additional information

DNS i use: 8.8.8.8, 8.8.4.4
ISP: Vodafone Egypt
AS number and name:  AS24835 Vodafone Data
Country: Egypt

**Comment by amfdlhe** [comment]
DNS i use: 1.1.1.1, 8.8.8.8
ISP: WE egypt
WE Data
Country: Egypt

**Comment by jimmygad** [comment]
I do too have the same issue 
ISP: WE EGYPT (Telecom Egypt - TEData)
DNS: 8.8.8.8, 8.8.4.4
Country Egypt

**Comment by hossamefia** [comment]
It's not a DNS problem, it looks like this site is blocked in Egypt.

Most likely it is a false positive, I hope it will be released soon.

**Comment by ihabmurad** [comment]
> It's not a DNS problem, it looks like this site is blocked in Egypt.
> 
> Most likely it is a false positive, I hope it will be released soon.

Who is responsible for that? The National Telecom Regulatory Authority!
Maybe we can speed up the process by contacting them, but the strange thing is why it was banned if it was already banned

**Comment by ihabmurad** [comment]
https://explorer.ooni.org/measurement/20230309T172702Z_webconnectivity_EG_24835_n1_yDlNlNqA8fiJxjBO?input=https://home-assistant.io/

**Comment by tawagny** [comment]
I confirm this is also over Etidalat HomeDSL services , How is that possible ?

**Comment by ihabmurad** [comment]
@pvizeli We need urgent help regarding this issue. ISP in Egypt tell me that the problem is with the site and not with them. This problem is constantly repeated in Egypt
home-assistant.io is always unavailable
nabucasa works well
We can't install the system or update it, Stuck with no solutions
Thanks

**Comment by MuhammadYacoub** [comment]
Me too have the same issue
ISP: WE EGYPT (Telecom Egypt - TEData)
DNS: 8.8.8.8, 8.8.4.4
Country Egypt

I've contacted the ISP, thy have no idea
Also i tried with etisalat to open the link, and it failed to update,
think out loud: 
What to do with cloud base services? 
Should i flash all Tuya devices? 
It's a real problem 
What about 
1- reinstalling the server on ubuntu server with OpenVPN.
2- Upload to cloud server, do the updates, install add-ons and clone it back
3-  install updates manually from github

**Comment by MuhammadYacoub** [comment]
> Me too have the same issue
> ISP: WE EGYPT (Telecom Egypt - TEData)
> DNS: 8.8.8.8, 8.8.4.4
> Country Egypt
> 
> I've contacted the ISP, thy have no idea
> Also i tried with etisalat to open the link, and it failed to update,
> think out loud: 
> What to do with cloud base services? 
> Should i flash all Tuya devices? 
> It's a real problem 
> What about 
> 1- reinstalling the server on ubuntu server with OpenVPN.
> 2- Upload to cloud server, do the updates, install add-ons and clone it back
> 3-  install updates manually from github
> 

This issue forced me to order a new 40 item to avoid depreciating the system, extra cost for nothing

**Comment by ZeroOmar** [comment]
We should all file complaints about this block but not to the ISP to the NTRA [National Telecom Regulatory Authority](https://www.tra.gov.eg/en/)

Name:	home-assistant.io
Address:	104.26.4.238
Address:	104.26.5.238
Address:	172.67.68.90
Address:	2606:4700:20::681a:4ee
Address:	2606:4700:20::681a:5ee
Address:	2606:4700:20::ac43:445a

**Comment by Ahmed-farag36** [comment]
Hello and Ramadan Kareem,
I am from Egypt too and have the same problem that my Home Assistant running on Virtualbox on win11 halted on on-boarding screen with error **manager.update blocked from execution** but found a workaround (by try and error) and here is what I do:

1. Setup a VPN (I am using PaladinVPN) and connect to any country
2. while your VM powered off use **NAT** as network adapter from Vritualbox settings
3. Run your VM and once Home Assistant CLI is ready type `network info` and you should get host_internet and supervisor_internet is **true**
5. Now you can update the supervisor or core from CLI using commands like `su update` but you can't access the Lovelace dashboard.
6. Now change the network adapter back to **bridged while VM is running**, host_internet and sometimes supervisor_internet should remain **true**
7. Now you can access the Lovelace dashboard and download addons or update as usual

Note: if you got hassio error or addons setting doesn't load successfully restart Home Assistant.

**Comment by ihabmurad** [comment]
@Ahmed-farag36 Allah Akram, Ramadan Kareem thank u for trying to help find a stable solution, also I wrote a solution in Arabic for myself, and I tried it, and now I am using it on proxmox stably, I put it here https://weeecreate.com/t/home-assistant/19 to archive it and help Arabs who have trouble with English like me. Thanks

**Comment by Ahmed-farag36** [comment]
Thanks @Hobiano
I will try your method with Proxmox, and if somebody has Raspberry pi please tell us if network blocked also and we may try to find a solution
Another thing I am participating in translating the voice intents in Arabic if somebody wants to help

**Comment by ihabmurad** [comment]
> 
@Ahmed-farag36 
Yes i see that, thank u, i will contact you to know more details about that If you don't mind i ‏will be grateful to you

**Comment by PierreBebawy** [comment]
now its working

**Comment by ZeroOmar** [comment]
> now its working

Yes, I can also confirm it is working

**Comment by frenck** [comment]
Good to hear it is working again 👍 

../Frenck
