### ISSUE TITLE
Packages configuration

### ISSUE THREAD

**Issue by samip5** [home-assistant/home-assistant.github.io#26465]
### Feedback

The documentation doesn't make it clear that it's not supported in Home-Assistant Core.

### URL

https://www.home-assistant.io/docs/configuration/packages/

### Version

2023.3.1

### Additional information

If one tries to use it on Home-Assistant Core, you're greeted with configuration invalid errors.

`Integration error: packages - Integration 'packages' not found.`

**Comment by frenck** [comment]
> The documentation doesn't make it clear that it's not supported in Home-Assistant Core.

Well, that is because it is supported and tested on Home Assistant Core.
Your statement is incorrect.

../Frenck
