### ISSUE TITLE
FYI: Dead link

### ISSUE THREAD

**Issue by Nick4-1** [home-assistant/home-assistant.github.io#26477]
### Feedback

Guys, from the 'Developer Tools' -> 'Services' -> 'Browser mod: notification', clicking on the question mark opens up the non-existing page https://www.home-assistant.io/integrations/browser_mod

### URL

https://www.home-assistant.io/integrations/browser_mod

**Comment by fabaff** [comment]
`browser_mod` is a third-party integration. I guess that the link is created by the frontend.

**Comment by frenck** [comment]
Hi there @Nick4-1 👋 

Fabaff is right, `browser_mode` is not maintained or created by the Home Assistant project. Therefore, we cannot correct the issue. Please report this with the custom integration author instead.

Thanks! 👍 

../Frenck
