### ISSUE TITLE
Google maps instructions link to a malware

### ISSUE THREAD

**Issue by Fearlessss** [home-assistant/home-assistant.github.io#26482]
### Feedback

get_cookies.txt was marked as malware by google as it was sending cookies to the developer. So better remove it as a suggestion. :)

### URL

https://www.home-assistant.io/integrations/google_maps/

### Version

2023.3.1

**Comment by dannytsang** [comment]
I am not seeing the same on Edge and Firefox. Which browser are you using and are you able to provide a screenshot please?

**Comment by Fearlessss** [comment]
Hey Danny,

I am using Google Chrome. I cannot provide screenshot anymore, because I deleted the extension, sorry..!

Here you can find more discussion about this issue: https://www.reddit.com/r/youtubedl/comments/11i5vyq/psa_the_get_cookiestxt_extension_is_now_actively/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by dannytsang** [comment]
I believe it is safe. The link on the page goes to [Get cookies.txt LOCALLY](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) which is also the alternative one mentioned in the Reddit post.

**Comment by Fearlessss** [comment]
Sorry for the trouble, I should have been more careful.

**Comment by dannytsang** [comment]
No trouble at all and have a great day 👍
