### ISSUE TITLE
Neato have removed the customer portal

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#26498]
### Feedback

> THERE IS A WARNING ABOUT A BAD RESPONSE BUT EVERYTHING WORKS AS EXPECTED
Do you have a stale robot in your configuration? Try to [look into your account](https://neatorobotics.com/) and delete any stale robots. If these warnings are about actively used robots, please report an issue to help us solving this problem.

This is no longer possible to do due to that Neato have removed the costumer portal.

### URL

https://www.home-assistant.io/integrations/neato/

### Version

2023.3.1

**Comment by ghost** [comment]
Still not solved.

**Comment by ghost** [comment]
Still relevant.

**Comment by dshokouhi** [comment]
try this URL

https://developers.neatorobotics.com/login
