### ISSUE TITLE
Provide details of concrete actions you can take to fix the problem

### ISSUE THREAD

**Issue by alderete** [home-assistant/home-assistant.github.io#26490]
### Feedback

This documentation page doesn't provide any details of how you can _fix_ the issue that it's flagging.

In my case, the entity is a "dead" entity. I'm not sure what it was I did to cause it, but it wasn't deleted when I attempted to delete the device/integration for this item (a light bulb).

But now I can't rename the replacement to use the "right" entity name, I'm stuck with this lingering garbage item, and it's frustrating that clicking the "documentation" link in the error message takes me to a doc page that gives me absolutely no information on what I can actually do to resolve the problem.

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2023.3.1

### Additional information

Using the latest version 2023.3.1. Integration is the Yeelight integration.

The entity has no associated device, which I would have thought impossible. There's no **Device info** item in the three dots menu, and no device listed when I select **Related**. Hovering over the red looping arrow with exclamation mark icon displays "Restored".

**Comment by frenck** [comment]
> This documentation page doesn't provide any details of how you can fix the issue that it's flagging.

It cannot be fixed, nor is it considered an issue.

Integration can provide unique IDs if possible, in those cases; more UI controls become available. Some integration have not offered a unique ID yet, or simply can't provide one. In those cases, those entities will lack UI features.

> In my case, the entity is a "dead" entity. I'm not sure what it was I did to cause it, but it wasn't deleted when I attempted to delete the device/integration for this item (a light bulb).

That, however, does sound like a bug, for which you should report an issue for that specific integration.

../Frenck
