### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by netzweg** [home-assistant/home-assistant.github.io#26502]
### Feedback

A stack option would be nice!

### URL

https://www.home-assistant.io/dashboards/statistics-graph/

### Version

2023.3.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
