### ISSUE TITLE
Error registering URL for webhook reolink

### ISSUE THREAD

**Issue by madeiratiago** [home-assistant/home-assistant.github.io#26516]
### Feedback

Hello

I have a NVR RLN8-410E version H3MB16 Hardware Version updated and it worked fine untill the 2023.2 home assistant uptade.
After that update the integration stopped working and when trying to put the integration back this error message appears:

"Error registering URL for webhook reolink_ec71db453382_ONVIF: HomeAssistant URL is not available"

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.1

**Comment by starkillerOG** [comment]
@madeiratiago please go to settings->general->Network->HomeAssistant URL and provide the local HTTP adress of your homeassistant instance.
Something like "http://192.168.1.IP:8123" with IP the IP of the device running HomeAssistant.

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by frenck** [comment]
Thank you for reaching out.  We do not use GitHub for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
