### ISSUE TITLE
no specs for Limited Templates

### ISSUE THREAD

**Issue by Morriz** [home-assistant/home-assistant.github.io#26511]
### Feedback

You only mention this bit without saying what the limited subset is:
> Templates for some triggers as well as trigger_variables only support a subset of the Home Assistant template extensions. This subset is referred to as “Limited Templates”.

### URL

https://www.home-assistant.io/docs/configuration/templating#home-assistant-template-extensions

**Comment by frenck** [comment]
Good point, that should be extended in telling how to know what is limited and what is not.

Throughout the documented is it explicitly documented if something isn't available (but it doesn't say that).

For example:

![image](https://user-images.githubusercontent.com/195327/223991208-047152a7-5198-4479-beb9-23acac1a4a8d.png)
