### ISSUE TITLE
tuya plant sensor unsuported

### ISSUE THREAD

**Issue by mortenx** [home-assistant/home-assistant.github.io#26536]
### Feedback

tuya plant sensor unsuported
Product Category
zwjcy

https://www.aliexpress.com/item/1005005086034692.html

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.3.3

**Comment by frenck** [comment]
Hi there @mortenx 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
