### ISSUE TITLE
tuya zigbee unsuported

### ISSUE THREAD

**Issue by mortenx** [home-assistant/home-assistant.github.io#26534]
### Feedback

tuya zigbee gateway device unsuported
Product Category
wfcon

https://www.aliexpress.com/item/4000852553535.html

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.3.3

**Comment by frenck** [comment]
Hi there @mortenx 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
