### ISSUE TITLE
Tahoma with Oerkiz integration

### ISSUE THREAD

**Issue by rhassold** [home-assistant/home-assistant.github.io#26537]
### Feedback

Hi guys, I am new to Github but I have been using Home Assistant happyly for a while. I am interested in integrating into Home Assistant my Somfy blinds using a Tahoma hub and the Overkiz Integration. 
Why the Tahoma Hub and not the Somfy Connection Kit? Because I could the do away with my Raspberry Pie and the Deconz integration looking after Zigbee Light sensors and controlling my Zigbee lights. I understand the limitations of the Overkiz Integration regarding Z Wave, Hue and Sonos.
There was no mention of Zigbee.
Does anyone know if it is possible to integrate Zigbee devices into Home Assistant via Tahoma and Overkiz?

Thanks for any advice
Rainer 

### URL

https://www.home-assistant.io/integrations/overkiz

### Version

2023.3.3

**Comment by iMicknl** [comment]
Same for Zigbee. Zigbee is supported by Home Assistant in a much better way with ZHA (or other flavours). Some Zigbee devices are mapped to general Light / Switch / Cover devices in the Overkiz platform, thus they will work in Home Assistant via Overkiz as well. We don't know which Zigbee devices we already support out of the box, and we don't plan on supporting new ones.

Just give it a try and otherwise you can use ZHA.

@home-assistant rename Zigbee support in Overkiz integration
@home-assistant close

**Comment by rhassold** [comment]
Hi Mick, thanks for the info. But in order to use Zigbee devices one always needs a hub of some sort. Presently I use Deconz running on a Raspberry. The Tahoma Hub supports Zigbee as well as the Somfy blinds. These blinds are my biggest issue since the Somfy world is totally closed. But I need to control the Somfy blinds in Home Assistant and that works with the Overkiz Integration.

I try to put my question a little more precise: If I connect my Zigbee sensors and lights to the Tahoma and integrate the Tahoma in HA using the Overkiz integration. Will I then be able to use the sensors and lights through the Overkiz Integration?

I have my doubts that ZHA can connect to the Tahoma in order to get connection with the Zigbee sensors.

Thanks for the support

Have a good evening and weekend

Cheers for now Rainer

Von: Mick Vleeshouwer ***@***.***>
Gesendet: Freitag, 10. März 2023 17:48
An: home-assistant/home-assistant.io ***@***.***>
Cc: Hassold, Rainer ***@***.***>; Author ***@***.***>
Betreff: Re: [home-assistant/home-assistant.io] Tahoma with Oerkiz integration (Issue #26537)


Same for Zigbee. Zigbee is supported by Home Assistant in a much better way with ZHA (or other flavours). Some Zigbee devices are mapped to general Light / Switch / Cover devices in the Overkiz platform, thus they will work in Home Assistant via Overkiz as well. We don't know which Zigbee devices we already support out of the box, and we don't plan on supporting new ones.

Just give it a try and otherwise you can use ZHA.

@home-assistant<https://github.com/home-assistant> rename Zigbee support in Overkiz integration
@home-assistant<https://github.com/home-assistant> close

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by rhassold** [comment]
Thanks Klaas, I opened a new topic in the forum. I have been a member for quite a while already.

Have a good weekend
Rainer

Von: Klaas Schoute ***@***.***>
Gesendet: Samstag, 11. März 2023 01:20
An: home-assistant/home-assistant.io ***@***.***>
Cc: Hassold, Rainer ***@***.***>; Author ***@***.***>
Betreff: Re: [home-assistant/home-assistant.io] Tahoma with Oerkiz integration (Issue #26537)


Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our Community Forum<https://community.home-assistant.io> or join our Discord chat server<https://discord.gg/c5DvZ4e>.

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
