### ISSUE TITLE
Systemd Journal Issue

### ISSUE THREAD

**Issue by gittan443** [home-assistant/home-assistant.github.io#26538]
### Feedback

I'm running an unsupported installation of Supervised (on Ubuntu - which is why it is unsupported).

I'm getting the 

Unsupported system - Systemd Journal issues
System is unsupported because Systemd Journal and/or the gateway service is missing, inactive or misconfigured . Use the link to learn more and how to fix this.

message. Trying to track down the issue, all actions suggested on 

https://www.home-assistant.io/more-info/unsupported/systemd_journal

have been tried at no avail.

Found a small issue with the supervised installer

The line  

--- 10-hassio-supervisor.conf ---
ListenStream=/run/systemd-journal-gatewayd.sock

is supposedly correct but on my system, that was a directory. Don't know where/when the directory was created (or even if it is supposed to be a directory). Anyhow, this seems to be an inconsistence.

### URL

https://www.home-assistant.io/more-info/unsupported/systemd_journal/

### Version

2023.3.3

**Comment by gittan443** [comment]
https://github.com/home-assistant/supervised-installer/pull/277/commits/4a11e0c6c0d0429365e38be66f66ea529357e734

Seems to be this....

**Comment by frenck** [comment]
As you know... you installation is unsupported. So not an issue for the Home Assistant project.

If you run an unsupported installation, the issues resulting are yours to solve.

../Frenck
