### ISSUE TITLE
DTE remove from integration listing?

### ISSUE THREAD

**Issue by dualtronic** [home-assistant/home-assistant.github.io#26541]
### Feedback

It has been three years since the DTE integration was disabled from the DTE energy bridge when they removed the endpoint from its firmware. Without a resolution expected, this integration should be removed from the published HA integration list. 

### URL

https://www.home-assistant.io/integrations/dte_energy_bridge/

### Version

2023.3.3

**Comment by frenck** [comment]
As per documentation:

![CleanShot 2023-03-13 at 18 26 03](https://user-images.githubusercontent.com/195327/224779794-145c937d-4ecf-4a20-846a-16aee42096d4.png)

As far as I am aware, the integration is still usable by v1 bridges?

../Frenck

**Comment by dualtronic** [comment]
> As far as I am aware, the integration is still usable by v1 bridges? 

@frenck: The v1 bridges were recalled and/or replaced by DTE well before they disabled the integration by closing the endpoint.  There should not be any v1 hubs out "in the wild", that can operate with an activated zigbee home energy (HE) binding to a smart meter.   To my knowledge, the only way to integrate the energy bridge today is via MQTT. It works in Hubitat, but I'm not sure how to port over to HA.  There was topic in the HA community but didn't seem to go too far: https://community.home-assistant.io/t/help-with-dte-energy-bridge-powerley-energy-meter-and-mqtt/514488
