### ISSUE TITLE
Integration also tested with RLC-833A & RLC-1224A

### ISSUE THREAD

**Issue by TheRealAvise** [home-assistant/home-assistant.github.io#26546]
### Feedback

Just to let you know that the integration also works with RLC-833A and RLC-1224A cameras.

Thank you for all the hard work.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.3.3

**Comment by starkillerOG** [comment]
@TheRealAvise thank you for your feedback!
I added the 2 models to the list of supported devices in this PR: https://github.com/home-assistant/home-assistant.io/pull/26547

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by starkillerOG** [comment]
@home-assistant close
