### ISSUE TITLE
Integrate zha groups to work with Homeassistants "own" goups

### ISSUE THREAD

**Issue by Jese44** [home-assistant/home-assistant.github.io#26559]
### Feedback

Hey! Title pretty much says it all, could it be possible to sync groups somehow to let there be one place to hsndle all groups (HA groups)?

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2023.3.3

**Comment by Hedda** [comment]
@Jese44  That is currently not possible, (nor I believe planned, so that would be a feature request and feature requests should be posted as a thread in Home Assistant's community forum instead -> https://community.home-assistant.io/c/feature-requests/13
