### ISSUE TITLE
Rust Compiler required

### ISSUE THREAD

**Issue by leviathan009** [home-assistant/home-assistant.github.io#26566]
### Feedback

The installation of homeassistant 2023.3.3 failed, because cryptography and bcrypt required a rust compiler in order to build wheel. After installing the compiler, the installation proceeded. I did previously install wheel with 'python3 -m pip install wheel' and installed Python 3.10.7 manually. 

This was done on a Raspberry Pi 4b using vanilla Raspberry OS.

I suggest to add the rust compiler to the dependencies/requirements for the installation.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.3.3

**Comment by frenck** [comment]
>  suggest to add the rust compiler to the dependencies/requirements for the installation.

This is not needed in most cases, adding it will cause people to install it without needing it, for most users (as the projects you mentioned provide pre-builds Wheels).

Please note the big warning on the installation method, which you might have missed.

../Frenck
