### ISSUE TITLE
Aliases page is confusing and incomplete

### ISSUE THREAD

**Issue by hnykda** [home-assistant/home-assistant.github.io#26570]
### Feedback

Hi,

I was trying to add some aliases to my instance of HA so I could use it with Assist, but the screenshot of the page https://www.home-assistant.io/docs/assist/aliases doesn't exist anywhere in my instance (or I couldn't find it), says "Google Assistant" on the picture, and doesn't show how it works via YAML configuration. I suspect it's from some Nabu Casa Cloud thingie and therefore should be at least labeled as such.

### URL

https://www.home-assistant.io/docs/assist/aliases/

### Version

2023.3.3

**Comment by dannytsang** [comment]
I believe the screenshot is part of Settings > Home Assistant Cloud > Google Assistant > Manage Entities.

You can add aliases by selecting an entity (e.g. Settings > Devices & Services > Entities) > Settings (cog icon) in the top right > Advanced settings > Aliases.

![image](https://user-images.githubusercontent.com/567982/233179249-f63463c1-a333-450d-b179-114e571c86c3.png)

![image](https://user-images.githubusercontent.com/567982/233179403-bfba234a-c745-4402-b6ac-a49b4ea058ee.png)
