### ISSUE TITLE
Radio Browser - Switzerland - Radio 24 - URL will be disabled soon

### ISSUE THREAD

**Issue by SchalteggerFelix** [home-assistant/home-assistant.github.io#26572]
### Feedback

Hi, 
the URL which is being used for Radio 24 in Switzerland will change soon. The new URL is:

https://stream.streambase.ch/radio24/mp3-192/direct/

based on the information provided by Radio 24:

https://www.radio24.ch/about/so-kannst-du-radio-24-uebers-internet-hoeren-133916458

Could you please change the URL in the Radio Browser?

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2023.3.3

**Comment by frenck** [comment]
We don't provide links/URLs/stream for that, Radio Browser does that.

Please report your issue @ https://www.radio-browser.info/

../Frenck
