### ISSUE TITLE
Add Docker CLI Entry

### ISSUE THREAD

**Issue by beans-are-gross** [home-assistant/home-assistant.github.io#26573]
### Feedback

You have Docker compose code on your website but not Docker CLI code, which in my and possibly someone elses opinion as well, is eaiser. It does the same thing as the compose file as I coppied the information, but changed the config file to be in an auto generated volume called "homeassistant-data". 

Instructions:

1. Copy the code below.
2. Open the terminal of your Docker server and paste this in.
3. Open your preferred brower and enter "http://<docker-server-ip-here>:8123" but replace from the "<" to the ">" with your servers IP address (it looks like 192.168.1.255).
4. You're done, happy automating!

`docker run -d --name homeassistant -v homeassistant-data:/config -v /etc/localtime:/etc/localtime:ro --restart unless-stopped --privileged --network=host ghcr.io/home-assistant/home-assistant:stable`

### URL

https://www.home-assistant.io/installation/alternative/

### Version

2023.3.3

**Comment by frenck** [comment]
These instructions are available here: <https://www.home-assistant.io/installation/linux#install-home-assistant-container>

We don't use volumes, but feel free to do so.

../Frenck

**Comment by beans-are-gross** [comment]
Sorry, I was looking at the alternative section. Thanks!
