### ISSUE TITLE
It just doesn't work.

### ISSUE THREAD

**Issue by scaglar78** [home-assistant/home-assistant.github.io#26574]
### Feedback

I have spent many hours trying to install this integration without success.
I have used all possible combinations of redirect urls and the url I used to access my HA. It just doesn't work.
I have read many post about similar issues but no fix has helped so far.

I either get an unauthorized or a "bad request" error.

aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.home-connect.com/security/oauth/token') 

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2023.3.3

**Comment by klaasnicolaas** [comment]
Hi there @scaglar78 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
