### ISSUE TITLE
Chipolo One , Chipolo One Spot doesn't work.

### ISSUE THREAD

**Issue by mrIngrid** [home-assistant/home-assistant.github.io#26581]
### Feedback

Hi, I want to report that Chipolo One device and Chipolo One Spot are not detected by Home Assistant, instead on the official documentation it is supported.  I have all 2 versions of Chipolo and neither of them are detected by Home Assistant.  I hope you solve.  Thank you

### URL

https://www.home-assistant.io/integrations/ibeacon/

### Version

2023.3.3

### Additional information

HassOS 9.5
Raspberry Pi4 4GB
Integrated Bluetooth

**Comment by cipnt** [comment]
> Chipolo One device and Chipolo One Spot are not detected by Home Assistant

I can confirm this to be true with [bluetooth_le_tracker](https://www.home-assistant.io/integrations/bluetooth_le_tracker/), the [iBeacon](https://www.home-assistant.io/integrations/ibeacon/) integrations as well as the unofficial [Passive BLE Monitor in HACS](https://github.com/custom-components/ble_monitor). I wish I'd know before ordering them

**Comment by rananna** [comment]
Still not working

**Comment by exentio** [comment]
My Chipolo One just arrived and it gets detected by Home Assistant, when not contacted to my phone. I'm pretty sure this is intended behavior, although I'd prefer it to be always detected by HA, but I can't complain (maybe I'll play around with [this](https://github.com/sandeepmistry/node-chipolo) if I really care)  
Have you all tried tracking it without a phone connection?

**Comment by cipnt** [comment]
> it gets detected by Home Assistant, when not contacted to my phone

This is interesting. Could you please give us more details? 
First of all, are you using the Chipolo [ONE or ONE Spot](https://chipolo.net/en/blogs/whats-the-difference-between-chipolo-one-and-chipolo-one-spot)?
By "not contacted to my phone" do you mean not in range of your phone or not paired to any phone?
Was this using the official [iBeacon](https://www.home-assistant.io/integrations/ibeacon/) integration?

**Comment by exentio** [comment]
> are you using the Chipolo [ONE or ONE Spot](https://chipolo.net/en/blogs/whats-the-difference-between-chipolo-one-and-chipolo-one-spot)?

I'm using the classic One, not the Spot  

> do you mean not in range of your phone or not paired to any phone?

First one, I disable the bluetooth from my phone, but after the initial pairing in the app

> Was this using the official [iBeacon](https://www.home-assistant.io/integrations/ibeacon/) integration?

No, I'm using the [Bluetooth LE Tracker](https://www.home-assistant.io/integrations/bluetooth_le_tracker) integration and this is my current config:
```yaml
device_tracker:
  - platform: bluetooth_le_tracker
    track_new_devices: false # was true before it was found
    track_battery: true
    # added after it was found
    new_device_defaults:
      track_new_devices: false
```
I do not use the iBeacon integration, however after I added the Chipolo One with the Bluetooth LE Tracker integration, Home Assistant found an iBeacon device by itself. I'm not able to confirm that it was caused by it because the integration didn't add any entity after being added, but it's very likely  
Small note: `track_battery` doesn't seem to work, but it's probably a device limitation

**Comment by stephenjsweeney** [comment]
I'm not using Home Assistant, but I recently bought a Chipolo One for my own little project. My device is currently advertising, and I'm able to scan for it using Bluetooth on my laptop / Raspberry Pi. Some might find this information helpful.

When I got it, I narrowed down the Bluetooth address by pressing the button to pair, and watching for new Bluetooth addresses that appeared (the broadcast stops after about a minute, so you need to press the button again).

Once I was sure I had the correct one, I paired the device with my phone, via the Chipolo app.

I then left the device at home, and went for walk (basically, moving out of range). The app warned me about having left the device behind. At this point, I went into the app and removed the Chipolo registered (I first marked it as being Lost, but I'm not sure this made any difference). The app warned me I should remove the registration when the device is connected to the phone, to ensure the Chipolo One moves into power saving mode. I ignored this warning.

Upon returning home, the Chipolo One continue to advertise itself, without anything more needing doing. It has done so for the past 5 days.

The mac address has so far remained static. I'm not sure how much of an impact this is having on the battery, but with any luck it should last several months (at least 12, with a good battery, I hope..!).

**Comment by quantum-fc101** [comment]
I’ve just managed to get a Chipolo working by following the above comments.
If you are struggling to get the MAC address, then once the Chipolo is added to the App. The MAC address is exactly the same as the serial number found in the app.

**Comment by Fonsohome** [comment]
I have managed to discover the chipolo, how can eliminate the rest of the discovered trackers?

**Comment by quantum-fc101** [comment]
Inside configuration.yaml set newly discovered devices to not be tracked.

```
device_tracker:
    platform: bluetooth_le_tracker
    track_new_devices: false # was true before it was found
    new_device_defaults:
      track_new_devices: false
```

Once this has been configured, you can then remove any unwanted devices from known_devices.yaml file.

**Comment by Fonsohome** [comment]
Thanks
