### ISSUE TITLE
platform: statistics state_characteristic choices not documented

### ISSUE THREAD

**Issue by YogoGit** [home-assistant/home-assistant.github.io#26586]
### Feedback

per the docs:

`state_characteristic` _string_ **REQUIRED**
The characteristic that should be used as the state of the statistics sensor (see table above).

Unfortunately, the table only documents 3 choices ('mean', 'count_on', 'change'), and there are other choices, none of them documented.

I know at least value_max is a valid choice, so listing the choices and/or increasing the number of examples would be useful.

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2023.3.3

**Comment by ThomDietrich** [comment]
Hey @YogoGit,

are you sure you are looking at the right page? The link posted by you above explains all characteristics in detail:

![image](https://user-images.githubusercontent.com/2870104/224853406-37e44300-d109-47b0-bc71-9706cb6c2a25.png)

**Comment by YogoGit** [comment]
I was looking for the 'state_characteristic', which is the name of the field, and it's only referenced a few times on the page.  The images describes something named 'State Characteristic', which means it's not properly named in a manner that makes it usable by search engines or other automated tools (or human beings looking through the dozens of pages and links that describe the behavior of the system).

My suggestion would be to update the text in the above section to reference the name 'state_characteristic' to more closely match the actual field name in the specific documentation.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/12058007/224854071-1fdc85ed-c0ca-40b0-b86f-57344a37df6a.png">

**Comment by ThomDietrich** [comment]
Understood. I don't quite see why you think this is an issue but would this change make it clearer for you?

> The following statistical measures are permitted as `state_characteristic` setting of a statistics sensor. Pay close attention to the right configuration of `sampling_size` and/or `max_age`, as most characteristics are directly influenced by these settings.

If so, please create a PR

**Comment by YogoGit** [comment]
Thanks @ThomDietrich .  I considered your changes, and made a slight change to them in PR https://github.com/home-assistant/home-assistant.io/pull/26596

**Comment by YogoGit** [comment]
Closed after docs PR merged
