### ISSUE TITLE
HA restart prevented when subnet mask included in trusted proxies.

### ISSUE THREAD

**Issue by Wiredhome** [home-assistant/home-assistant.github.io#26587]
### Feedback

I applied the /24 in the trusted proxies, because my external IP was in the same class - thinking I understood the comments on the two lines.

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.200      # Add the IP address of the proxy server
    - 172.30.33.0/24  # You may also provide the subnet mask

When I clicked on HA's restart, it would not, citing an error on that line. I removed the /24 and when I tried again it restarted.

### URL

https://www.home-assistant.io/integrations/http/

### Version

2023.3.3

### Additional information

I have core-2022.5.5, running in docker, on a Synology NAS.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
