### ISSUE TITLE
Malfunction "Media Player: Play"

### ISSUE THREAD

**Issue by darthklaus59** [home-assistant/home-assistant.github.io#26582]
### Feedback

Malfunction "Media Player: Play"
"Error performing an action
extra keys not allowed @ data['edia_content_id']. Got None extra keys not allowed @ data['media_content_type']. Got None"
configuration:
service: media_player.media_play
data:
   edia_content_id: http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3
   media_content_type: music
![image](https://user-images.githubusercontent.com/49557587/224776421-f97d8624-a2ad-4eec-ac71-58fa3292ddc8.png)

### URL

https://www.home-assistant.io/integrations/media_player/

### Version

2023.3.3

**Comment by frenck** [comment]
Hi there @darthklaus59 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by darthklaus59** [comment]
oh sorry
I made a mistake there. But the problem is not. The fault was mine.
Thanks
