### ISSUE TITLE
Ecobee integration

### ISSUE THREAD

**Issue by mfest** [home-assistant/home-assistant.github.io#26589]
### Feedback

In the first section of the document as copied below, the link (https://www.ecobee.com/developers/) does not have a sign in that will set up the user as a developer and get an API key. Signing in from the link on that page just logs the user into their ecobee portal without developer option if they have not set it up yet. It's a bit confusing.

Preliminary Steps
You will need to obtain an API key from ecobee’s [developer site](https://www.ecobee.com/developers/) to use this integration. To get the key, your thermostat must be registered on ecobee’s website (which you likely would have already done while installing your thermostat). Once you have done that, perform the following steps.

The next part of the document-
1. Click on the Become a developer link on the [developer site](https://www.ecobee.com/home/developer/loginDeveloper.jsp).

This is the correct link to allow user to become a developer and give them the developer option when they log into the ecobee portal.

In the configuration section of the document, step 3 says "you will be presented with a unique four-character PIN code which you will need to authorize in the [ecobee consumer portal](https://www.ecobee.com/consumerportal/index.html)."

The pin code presented is an 8 character code separated by a dash in this format-    XXXX-XXXX

### URL

https://www.home-assistant.io/integrations/ecobee/

### Version

2023.3.3

**Comment by marcolivierarsenault** [comment]
Just to be clear, 
Your feedback is to:
1. Fix the first link pointing to the developer program page, having it point towards login directly
2. Change the `with a unique four-character PIN code` to `8 character code separated by a dash in this format- XXXX-XXXX`

**Comment by marcolivierarsenault** [comment]
@mfest can you confirm ☝️

**Comment by mfest** [comment]
Yes

**Comment by marcolivierarsenault** [comment]
For #1 I disagree, the second link is the login link. I do think it is a good idea to have the first link points toward the overall program of developper so people can understand what they register to. 

FOr #2 I will take a look at it
