### ISSUE TITLE
can this be updated to include using the new IMAP gui integration. I dont see a way to edit that

### ISSUE THREAD

**Issue by womp666** [home-assistant/home-assistant.github.io#26599]
### Feedback

can this be updated to include using the new IMAP gui integration. I dont see a way to edit that under settings, devices, integrations

### URL

https://www.home-assistant.io/integrations/imap_email_content/

### Version

2023.3.4

**Comment by frenck** [comment]
Hi @womp666 👋 

Sorry, this integration can, at the moment, only be configured using YAML.

../Frenck
