### ISSUE TITLE
habitica addon not working 

### ISSUE THREAD

**Issue by henzard** [home-assistant/home-assistant.github.io#26593]
### Feedback

I installed the habitica addon with the correct api key and secret. I expected to see devices and entities but I am not seeing anything 

Home Assistant 2023.3.4
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.0 - latest

![image](https://user-images.githubusercontent.com/5329395/224951847-c71a358f-94fe-429d-acf6-02a801a2f4f9.png)

### URL

https://www.home-assistant.io/integrations/habitica/

### Version

2023.3.4

### Additional information

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:597
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 11:08:22 (2 occurrences)
Last logged: 11:08:22

Sensor sensor.habitica_henzard_kruger_name has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: Henzard Kruger (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+habitica%22
Sensor sensor.habitica_henzard_kruger_class has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: healer (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+habitica%22

**Comment by henzard** [comment]
I have tried with my user name 
![image](https://user-images.githubusercontent.com/5329395/224952836-4304d074-f0a9-428c-be5a-08ca340c1393.png)

**Comment by henzard** [comment]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:597
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 11:08:22 (4 occurrences)
Last logged: 11:13:20

Sensor sensor.habitica_henzard_kruger_name has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: Henzard Kruger (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+habitica%22
Sensor sensor.habitica_henzard_kruger_class has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: healer (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+habitica%22
Sensor sensor.habitica_hb_2eu5g8l7y4q6fl6d8_name has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: Henzard Kruger (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+habitica%22
Sensor sensor.habitica_hb_2eu5g8l7y4q6fl6d8_class has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: healer (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+habitica%22

**Comment by frenck** [comment]
Hi there @henzard 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
