### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by blackie333** [home-assistant/home-assistant.github.io#26607]
### Feedback

Hello,
I am using Google Calendar integration and it's sensor with automation which notifies me every morning about my next calendar event via TTS. It's working fine and proved it's purpose.
Some days I have multiple events in my calendar and I would like to be notified about all of my upcoming event for the day.
Would it be possible to set a parameter(index) for NEXT event sensor to be able to check events in a cycle if more of them apply for today?  Index parameter value could be 1,2,3 to read details about upcoming event #1, #2, #3, ...
Thanks in advance

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2023.3.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by blackie333** [comment]
Thanks, I'm very sorry, used a button for "Provide feedback" without checking where the thread is created...
