### ISSUE TITLE
Modbus integration documentation error

### ISSUE THREAD

**Issue by piotrtobolski** [home-assistant/home-assistant.github.io#26615]
### Feedback

Documentation states that `scan_interval` has default value of `10`:
```
scan_interval integer (optional, default: 10)
```

In the source I see that [it was always been](https://github.com/home-assistant/core/blame/4d3799a9de1116de8ac202ef970dcbcdba330a97/homeassistant/components/modbus/const.py#LL131C3-L131C3) `15`:
``` 
DEFAULT_SCAN_INTERVAL = 15
```

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2023.3.4

**Comment by janiversen** [comment]
Good catch. to be changed.

**Comment by piotrtobolski** [comment]
I wanted to create this simple PR myself but it took me too long to read how to do it correctly in this project. Thanks for the quick update.
