### ISSUE TITLE
Add some more help and a useful official Google link for the 'Matter is currently unavailable' issues in Matter docs.

### ISSUE THREAD

**Issue by goldfoxo** [home-assistant/home-assistant.github.io#26618]
### Feedback

I'd been facing issues testing out HA Matter support for some time now, as all my Android phones and tablet were giving me the 'Matter is currently unavailable' error, despite having all the requirements met per the Matter integration page.

After a bit of digging around, I came across this Google support page: https://developers.home.google.com/matter/verify-services
This was super helpful in giving the precise troubleshooting steps needed to fix the issue - in my case, the 'Play services Matter module' was missing on all devices, and a quick uninstall and reinstall of the Home app forced it to download and got everything working.

It would be super helpful to add some extra notes on the end of that troubleshooting step on the HA docs, maybe along the lines of "... If this still does not appear with all requirements met, try uninstalling and reinstalling the Google Home app, this can sometimes force missing system modules to be installed. For detailed troubleshooting steps see [this Google Troubleshooting page]."

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2023.3.4

**Comment by marcelveldt** [comment]
Fixed in https://github.com/home-assistant/home-assistant.io/pull/27136

Thanks @goldfoxo !
