### ISSUE TITLE
Integration Inkbird IHT-2pb

### ISSUE THREAD

**Issue by herden-system** [home-assistant/home-assistant.github.io#26622]
### Feedback

Is there any chance to integrate th IHT-2PB BBQ thermometer?
Thank you very much!
Best Regards
Thomas

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2023.3.4

### Additional information

It is no issue!

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
