### ISSUE TITLE
I had to change device to DP instruction

### ISSUE THREAD

**Issue by Ilan80** [home-assistant/home-assistant.github.io#26620]
### Feedback

Hi, I have Tuya garage door controller. 
I followed the instruction to add it to the LocalTuya integration in HA.. I had to go to Cloud -> Development -> Devices (tab) , and change the device from  "Standard instruction" to "DP Instruction".
Now I can add the device manually.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.3.4

**Comment by frenck** [comment]
Cool, but the local Tuya integration is not part of Home Assistant, but a custom integration.

The documentation thus, doesn't apply to that.

../Frenck

**Comment by Ilan80** [comment]
Thank you. It's my first feedback, I love HA!
