### ISSUE TITLE
Additional configuration in configuration.yaml required

### ISSUE THREAD

**Issue by geoffreys** [home-assistant/home-assistant.github.io#26627]
### Feedback

The page lacks information about adding the twilio authentication token information into configuration.yaml like below. Without this config added the twilio notifier plugin fails to initialize and logs errors into the homeassistant logs about missing keys (slightly cryptic).

Missing parts that also need to be in configuration.yaml:

twilio:
  account_sid: yyyyyyyyyy
  auth_token: xxxxxxxxxxx

The values for both of these placeholders can be found in the twillio account.

### URL

https://www.home-assistant.io/integrations/twilio_sms/

### Version

2023.3.4

**Comment by frenck** [comment]
Hi there @geoffreys 👋 

It seems like you have missed the second line on the documentation page:

![CleanShot 2023-03-16 at 08 06 13](https://user-images.githubusercontent.com/195327/225540554-296e0a06-7971-4e9e-9b29-693f01fb2b94.png)

Which provides the information you've been looking for.

../Frenck
