### ISSUE TITLE
'Networks >> Outbound websocket' ?

### ISSUE THREAD

**Issue by MortyFleem** [home-assistant/home-assistant.github.io#26638]
### Feedback

Can connect to device locally using it's IP address but absolutely cannot find 'Networks >> Outbound websocket' (as suggested) option anywhere. I just can't get temperature values over to my Home Assistant form my Shelly Motion 2. Wd be great if you could update/instructions/make them clearer for frustrated newbs.

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2023.3.5

**Comment by bieniu** [comment]
@MortyFleem I updated the documentation but... Motion 2 is a Gen1 device and Outbound websocket is not related to it.
