### ISSUE TITLE
Add a little clarity that the sensors are configured In the IotaWatt Web UI

### ISSUE THREAD

**Issue by philgituser** [home-assistant/home-assistant.github.io#26645]
### Feedback

Just spent too long trying to work out where these sensors where supposed to be created for the absolute values. Thinking they had to be made in the HA configuration.yaml for too long.

Would propose a minor edit - and avoid the naming overlap with sensors being defined in Home Assistant configuration:

CONFIGURE IOTAWATT
You will need to configure two new IoTaWatt "Outputs" ~sensors~ on the IotaWatt configuration:

I only worked it out when I saw this:
https://community.home-assistant.io/t/custom-component-iotawatt-energy-monitor-integration/254110/183

### URL

https://www.home-assistant.io/integrations/iotawatt/

### Version

2023.3.5

**Comment by haveyougotanypets** [comment]
I agree with the poster above. The docs on the integration are incorrect.

Ideally a link could be added to the project's own docs which has a section on how to integrate with home assistant 

https://docs.iotawatt.com/en/master/integrators.html?highlight=home%20assistant#

Alternately updating the docs on the page to add the notion that the outputs need to use IoTa integrators to function correctly.
