### ISSUE TITLE
Xiaomi tv - compatible tv models

### ISSUE THREAD

**Issue by Extreme79** [home-assistant/home-assistant.github.io#26656]
### Feedback

Documentation need to specify that integration is compatible only 3rd series TV.
Newest TV not working anymore with it (😢) due to pymitv support lack. 

### URL

https://www.home-assistant.io/integrations/xiaomi_tv/

### Version

2023.3.5

**Comment by simse** [comment]
Feel free to submit a PR to update the docs: https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/xiaomi_tv.markdown

**Comment by simse** [comment]
home-assistant close

**Comment by simse** [comment]
@home-assistant close
