### ISSUE TITLE
Hub not usable ?

### ISSUE THREAD

**Issue by sylvain-hazera** [home-assistant/home-assistant.github.io#26653]
### Feedback

Hello.
I Just have New AC from atlantic with zigbee usb key and sauter cozytouch hub.

All my ac work Witherspoon hub and.cozytouch sauter app.

Is there.anyway to make.them.working Witherspoon homeassistant  ?

Tanks

### URL

Intégration-overkiz

### Version

Latest

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
