### ISSUE TITLE
Are secret passwords string format? There is mismatching info about it.

### ISSUE THREAD

**Issue by dansity** [home-assistant/home-assistant.github.io#26664]
### Feedback

The documentation says: `http_password: "YOUR_PASSWORD"`
The secrets.yaml file in HA provides this example: `some_password: welcome`

Which one is correct?

### URL

https://www.home-assistant.io/docs/configuration/secrets/

### Version

2023.3.5

**Comment by frenck** [comment]
> The secrets.yaml file in HA provides this example: some_password: welcome

![image](https://user-images.githubusercontent.com/195327/226346744-dde05323-d68c-463d-ae89-2304445b6cb6.png)

I'm confused. I don't see that on the page you linked/left the comment on, could you clarify?

../Frenck

**Comment by dansity** [comment]
The documentation shows the password is in string format which is contradicting the info in secrets.yaml

![2023-03-20 14_06_47-Storing secrets - Home Assistant – Mozilla Firefox](https://user-images.githubusercontent.com/31413689/226347866-e67cba7e-ed2b-4fd7-bacf-6553d6f7ebb5.png)

example in secrets.yaml

![2023-03-20 14_08_54-Studio Code Server – Home Assistant – Mozilla Firefox](https://user-images.githubusercontent.com/31413689/226348130-7276cfef-0c37-41dd-9447-82fa7111793e.png)

**Comment by frenck** [comment]
> The documentation shows the password is in string format which is contradicting the info in secrets.yaml

> example in secrets.yaml

Those are two different / not connected things? The documentation page seems to provide a correct and full example. I'm not understanding the relation with the configuration files you are trying to make?

../Frenck

**Comment by dansity** [comment]
Both example shows how to write a password in the secrets.yaml file but both shows it in a different way.
So how do I add my password?
Do I add it like the doc says: `some_password: "welcome"` or do I add it
like the secrets.yaml example says `some_password: welcome` ?

**Comment by frenck** [comment]
> Both example shows how to write a password in the secrets.yaml file but both shows it in a different way.

They don't. You can write as many passwords to that file as you like. 🤷 

> Do I add it like the doc says: some_password: "welcome" or do I add it
> like the secrets.yaml example says some_password: welcome ?

That sounds more like a support question, for which we have our community forums or Discord chat.

../Frenck

**Comment by dansity** [comment]
I have opened the issue to verify if the content of the docs page is correct as it is not matching the example in the secrets.yaml. The issue is not about a specific password or how the function works. This is about the documentation and if the example in the documentation page is correct or the example in the secrets.yaml header is correct.
Right now I see two versions and it is not clear which one to use:
some_password: "welcome"   <--- this is how the documentation defines passwords should be written
some_password: welcome     <--- this is how the secrets.yaml defines how passwords should be written

**Comment by frenck** [comment]
> I have opened the issue to verify if the content of the docs page is correct as it is not matching the example in the secrets.yaml.

Sorry, they are correct. It are examples, you can add as many or as many variants as you like.

> Right now I see two versions and it is not clear which one to use:
some_password: "welcome" <--- this is how the documentation defines passwords should be written
some_password: welcome <--- this is how the secrets.yaml defines how passwords should be written

Both are the same.

**Comment by dansity** [comment]
Ok, so doesn't matter it is processed both ways.
Thank you
