### ISSUE TITLE
switchbot blind tilt connect to wifi

### ISSUE THREAD

**Issue by swonge** [home-assistant/home-assistant.github.io#26666]
### Feedback

does it require switchbot hub to connect to wi-fi?

The switchbot integration mentioned the hub is not required, but I don't see any connectivity option to wi-fi that is required for the switchbot integration to discover the device

"In order to use this integration, it is required to have working Bluetooth set up on the device running Home Assistant. A [SwitchBot Hub](https://switch-bot.com/pages/switchbot-hub-mini) is not required for this integration."

Thanks in advance

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.3.5

**Comment by frenck** [comment]
>  but I don't see any connectivity option to wi-fi that is required for the switchbot integration to discover the device

That is correct, as this integration doesn't use Wi-Fi/IP networks. It uses Bluetooth to talk  to the devices directly (without an hub).

../Frenck
