### ISSUE TITLE
Where to find Rest API URL

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#26675]
### Feedback

Hi, can you please explain, where to find the Rest API URL that the integration requires to work? 

In my case I would like to set up an Apple TV as thread border router. The integrations seems to detect and config UI displays automatically my Apple TV, but then UI asks for the API URL.

Neither [devicename].local or the IP address work. What is the URL scheme? And where do I find the one of my devices?

### URL

https://www.home-assistant.io/integrations/otbr/

### Version

2023.3.5

**Comment by rlust** [comment]
Trying to find the url for my Apple TV to enter into the Tread integration. Where do I find the TBR url?
