### ISSUE TITLE
which file?

### ISSUE THREAD

**Issue by kmanan** [home-assistant/home-assistant.github.io#26682]
### Feedback

Hi, n00b here. Would be helpful to know which file I have to edit / create and enter all these various commands.

### URL

https://www.home-assistant.io/docs/scripts/

### Version

2023.3.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by kmanan** [comment]
The page says to post on Github on how to improve documentation. Should update the footer if a user is not expected to post "ideas to improve documentation" on Github.

**Comment by klaasnicolaas** [comment]
Sorry, I have judged your issue as a request for help and not so much as feedback on the documentation.

The page you provided is purely about the syntax you can use in scripts. On [this page](https://www.home-assistant.io/integrations/script/) you will find more information about the use of script and how you can create it in YAML or in the UI.
