### ISSUE TITLE
Bad indentation error in config.yaml following the instructions

### ISSUE THREAD

**Issue by kmanan** [home-assistant/home-assistant.github.io#26681]
### Feedback

I was following the steps here and keep getting a bad indentation of a mapping entry

![image](https://user-images.githubusercontent.com/17659155/226736585-a31d330b-0092-4de6-a1d0-de596137aa64.png)

### URL

https://www.home-assistant.io/integrations/conversation/

### Version

2023.3.5

**Comment by synesthesiam** [comment]
Can you please provide the complete YAML?
