### ISSUE TITLE
Silly

### ISSUE THREAD

**Issue by virtuallytrivial** [home-assistant/home-assistant.github.io#26692]
### Feedback

I have to cameras. On a G4 4K and one is a G3. Why, when I add motion and do an action the G4 is the only one that does that  action. Seriously., If you aren't actually testing the products why even have an add on to home assistant. It just creates frustration with the user base. 

Scenario: Turn on flood lights with the G4 and G3 cameras when either detect motion. I have 3 flood lights. I want them on no matter what camera detects motion. But on the G4 does. The G3 bullet does not.

Why even put out an extension if it doesn't work for all products?

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2023.3.5

**Comment by frenck** [comment]
Hi there @virtuallytrivial 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix the issue you mentioned. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
