### ISSUE TITLE
request

### ISSUE THREAD

**Issue by greck65** [home-assistant/home-assistant.github.io#26693]
### Feedback

hello. You can add Yandex maps to your home assistant, as they are more suitable for Russia (there are more objects in Yandex maps.....). Thank you.

### URL

https://www.home-assistant.io/integrations/google_maps/

### Version

2023.3.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
