### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by Thijxx** [home-assistant/home-assistant.github.io#26698]
### Feedback

Bu default this integration adds 11 broken sensors and 1 working sensor to the list. The broken sensors do not have a unique ID and the documentation about that is lacking (https://www.home-assistant.io/faq/unique_id), it explains the problem but not the solution and from here there is a link to another piece of documentation but it does not say anything about adding an ID (https://www.home-assistant.io/docs/configuration/customizing-devices).

### URL

https://www.home-assistant.io/integrations/waqi/

### Version

2023.3.6

**Comment by frenck** [comment]
Hi there @Thijxx 👋 

> Bu default this integration adds 11 broken sensors and 1 working sensor to the list.

Seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

> it explains the problem but not the solution and from here there is a link to another piece of documentation but it does not say anything about adding an ID

It is not a problem. Not all entities have unique IDs. Entities without unique ID are possible, fairly common, potentially not providable, and not a bug. It simply means the entity is not UI-modifiable via the UI. 🤷 The documentation doesn't say anything about adding one, as you can't add one.

../Frenck
