### ISSUE TITLE
Support for IBT-24S

### ISSUE THREAD

**Issue by nhuynhdo** [home-assistant/home-assistant.github.io#26701]
### Feedback

Please add support for IBT-24S which was released Dec 21, 2021.  Thank you very much.

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2023.3.6

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
