### ISSUE TITLE
Rounding values for gauges

### ISSUE THREAD

**Issue by SgtFoose** [home-assistant/home-assistant.github.io#26719]
### Feedback

Please add an option to round values. E.g 43.333333% to show 43.33%.

### URL

https://www.home-assistant.io/dashboards/gauge/

### Version

2023.3.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
