### ISSUE TITLE
put switchbot hyrgrometers back 

### ISSUE THREAD

**Issue by shayclark** [home-assistant/home-assistant.github.io#26720]
### Feedback

ffs i just bought 5. had them working and then you remove them from the integration with no replacement and for no discernable reason.

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.3.6

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
