### ISSUE TITLE
YoLink Speaker Hub YS1604-UC not intragating into Home Assistent.

### ISSUE THREAD

**Issue by normgr00** [home-assistant/home-assistant.github.io#26725]
### Feedback

Hoping for YoLink Speaker Hub YS1604-UC to be interrogated into Home Assistant.

### URL

https://www.home-assistant.io/integrations/yolink/

### Version

2023.3.6

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
