### ISSUE TITLE
add configuration reference

### ISSUE THREAD

**Issue by selfisekai** [home-assistant/home-assistant.github.io#26721]
### Feedback

I'm trying to run hass for the first time and I'm struggling with some configuration problems such as:
```
2023-03-25 16:03:07.308 ERROR (MainThread) [homeassistant.components.http.forwarded] A request from a reverse proxy was received from 127.0.0.1, but your HTTP integration is not set-up for reverse proxies
```

this is a very clear error message to me, but I can't find documentation on how to set it in my configuration.yaml

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2023.3.6

**Comment by frenck** [comment]
Configuring reverse proxies is part of the `http` configuration, for which the documentation can be found here:

<https://www.home-assistant.io/integrations/http>

../Frenck
