### ISSUE TITLE
The template trigger example does not seem to be correct

### ISSUE THREAD

**Issue by ivanovd** [home-assistant/home-assistant.github.io#26745]
### Feedback

I have followed the example for an event summary trigger in my calendar.

It was supposed to turn off one automation and turn on another one when an event with a certain summary started. Here is my automation config:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/4889583/227988635-393c5234-0775-4ced-8423-b65630ec7dd7.png">

which is per the example on the page, however, that automation did not pass the condition, although I checked it for correctness:

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/4889583/227989223-959e6d8f-d8e6-4047-bfd5-9d13cd7521a6.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/4889583/227989320-7726ad31-5620-44ad-a172-c715e31ecb07.png">

When testing the condition in the UI I also get an error, although that might be expected:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/4889583/227989635-b3fb50cc-b0aa-46ea-812c-e8f950574074.png">

Not sure what went wrong. Everything seems correct to me. Any assistance would be appreciated.

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2023.3.6

**Comment by ivanovd** [comment]
I figured it out ... editing the template in the Visual editor adds some extra escape characters. If you edit the automation in YAML then everything works. I am not sure if it is a bug or intended behaviour.

**Comment by frenck** [comment]
The example is correct, as it is an YAML example :)

../Frenck
