### ISSUE TITLE
Freebox pop doesn't seems to work :-(

### ISSUE THREAD

**Issue by greee-fr** [home-assistant/home-assistant.github.io#26749]
### Feedback

In "freebox" integration, when I use host and port provided by my freebox pop (aka v8) on page [here](http://mafreebox.freebox.fr/api_version) I got a message "unattend erroe" ("Erreur inattendue")

### URL

https://www.home-assistant.io/integrations/freebox/

### Version

2023.3.6

### Additional information

box_model_name | "Freebox v8 (r1)"
-- | --
api_base_url | "/api/"
device_name | "Freebox Server"
https_available | true
box_model | "fbxgw8-r1"
api_version | "10.2"
device_type | "FreeboxServer8,1"

**Comment by klaasnicolaas** [comment]
Hi there @greee-fr 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
