### ISSUE TITLE
you can add my uuid: 00001812-0000-1000-8000-00805f9b34fb

### ISSUE THREAD

**Issue by Eliteevg** [home-assistant/home-assistant.github.io#26758]
### Feedback

I did it according to the instructions 
https://github.com/dave-code-ruiz/elkbledom 
My device is not in the list,
the program for managing "lotus lantern"

you can add my uuid? 
my uuid: 00001812-0000-1000-8000-00805f9b34fb

Device be:59:4a:00:c6:0f (public), RSSI=-90 dB
  Flags = 06
  Incomplete 16b Services = 00001812-0000-1000-8000-00805f9b34fb
  Complete Local Name = ELK-BLEDOM
Device 58:b6:23:67:c4:4e (public), RSSI=-83 dB
  Flags = 06
  Manufacturer = 8f030a10a00c004cc46723b658d8

### URL

https://www.home-assistant.io/integrations/led_ble/

### Version

2023.3.6

### Additional information

you can add my uuid? 
my uuid: 00001812-0000-1000-8000-00805f9b34fb

**Comment by Eliteevg** [comment]
you can add my uuid?
my uuid: 00001812-0000-1000-8000-00805f9b34fb

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by frenck** [comment]
This: [dave-code-ruiz/elkbledom](https://github.com/dave-code-ruiz/elkbledom)

It is a third-party integration, not supported by the Home Assistant project. Please contact the author of that integration for support.

../Frenck
