### ISSUE TITLE
Integration Configuration incorrect

### ISSUE THREAD

**Issue by rkilcourse** [home-assistant/home-assistant.github.io#26764]
### Feedback

The site suggests adding the Rainbird Integration from Settings/Integrations. Doing this pops a message stating:
This device can not be added from the UI
You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information.

I was able to install by adding these lines to configuration.yaml:
rainbird:
  host:<IP ADDRESS>
  password:<RAINBIRD ACCOUNT PASSWORD>

Optionally also added:
  zones:
    1:
      friendly_name: My Zone 1
    2:
      friendly_name: My Zone 2

### URL

https://www.home-assistant.io/integrations/rainbird/

### Version

2023.3.6

### Additional information

Researched answer here:
https://community.home-assistant.io/t/rainbird-integration/226243/2

**Comment by allenporter** [comment]
Are you sure you are on the right version of home assistant? That would be what an older version would say

**Comment by rkilcourse** [comment]
You're absolutely right. Pulling the new image automatically moved the manual config to the rainbird integration like the website suggested.

Thanks for the surprisingly speedy support Allen!
