### ISSUE TITLE
Additional Hints for ODROID-N2+

### ISSUE THREAD

**Issue by gebhard73** [home-assistant/home-assistant.github.io#26765]
### Feedback

Hi,

after trying to install HA on a stock ODROID-N2+ for some hours I've finally solved my problems and like to add a few hints to these two pages:

https://www.home-assistant.io/installation/odroid/
https://www.home-assistant.io/common-tasks/os#flashing-an-odroid-n2

- General hint: the device should get an IP address by DHCP which - at least for the installation process - is allowed to access the Internet without any restriction.
- The pulsing blue dot on the web installation page can be clicked to show detailed messages.
- To make sure an installed mass storage device on the ODROID board can be accessed via SPI / OTG smoothly, its start should be zeroed before using `ums` to make it accessible to a host system for writing, e.g. by running the following commands in petit OS / terminal:
`dd if=/dev/zero of=/dev/mmcblk0 bs=1024 count=2`
- While in petit OS / terminal the correct date should be checked:
`date`
- If the time and date is not correct, **it must be set and written to the RTC**, e.g.:
```
date -s YYYY-MM-DD
date -s hh:mm
date
hwclock -w
```
To make sure this worked the ODROID should be powered of and on again, rebooted into petit OS / terminal, and the system clock should be checked again using `date` command. If the system clock isn't set nearly correctly, the certificate validations will fail and the setup will break (loop endlessly).

Obeying the above and serving the storage to the host computer using ums, writing the image to it and installing Home Assistant has better chance to succeed :-)

HTH, Gebhard

### URL

https://www.home-assistant.io/common-tasks/os/

### Version

2023.3.6

**Comment by gebhard73** [comment]
IMHO this is still relevant and may be helpful to others.

**Comment by pezlin** [comment]
I have the problem with the eMMC not being visible as storage in Windows. I have followed @gebhard73 instructions above but without any luck. Any other suggestions on what to try would be appreciated.
