### ISSUE TITLE
Link to "Flower Care" App is broken

### ISSUE THREAD

**Issue by brintal** [home-assistant/home-assistant.github.io#26762]
### Feedback

Apparently the "Flower Care" App was deleted from Google Play Store. The Link in the Home Assistant Documentation (https://play.google.com/store/apps/details?id=com.huahuacaocao.flowercare) is dead.

I found the following workaround to update the firmware of the sensors:
Installing "Mi Home" and setting the region to "China Mainland" when starting the app for the first time. Then the flower sensors can be added to Mi Home and the firmware updated there.

### URL

https://www.home-assistant.io/integrations/xiaomi_ble/

### Version

2023.3.6

**Comment by sargonas** [comment]
I am able to access and download the Flower Care app on both Google play and on the iOS store. 

It is clear, however, the app has not been updated in two years and the developer may possibly have abandoned their "global" version of app and support, but it does still seem to be available on both platforms, including the link you pasted above works for me as well.

**CORRECTION**: the iOS version has not been updated in two years, but the Google play version was updated on March 29th. I suspect this has something to do with the fact you were unable to find it and I currently am today. It looks like it may have fallen off the Google play store, or something, and the developers relisted it this week sometime after you filed this issue.

**Comment by brintal** [comment]
weird. a few days ago the link was dead. Working now for me as well. 
Closing the issue.
