### ISSUE TITLE
Bad advice on configuration.yaml path

### ISSUE THREAD

**Issue by Lotharyx** [home-assistant/home-assistant.github.io#26772]
### Feedback

The page reads:

> The path to your configuration directory can be found in the Home Assistant frontend by going to [Settings > System > Repairs > System information from the top right menu](https://my.home-assistant.io/redirect/system_health)

but this is not true.  As of Home Assistant Core 2022.5.5, there is no "Repairs" section under Settings > System.

The configuration.yaml path is in fact visible by going to Settings > System > About.

(Note: Apparently I'm on an old version, but the documentation could still stand to say "find it here for older versions")

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2023.3.6

**Comment by klaasnicolaas** [comment]
The documentation is always reflecting the current version of Home Assistant, the documentation becomes unmanageable if we also putting notes everywhere on how it is with an older version of Home Assistant.

Maybe it's time to catch up on some updates 😉

**Comment by Lotharyx** [comment]
That's fair.
