### ISSUE TITLE
please add some addtional info on this page regarding supervisor and addons for the container install method

### ISSUE THREAD

**Issue by coolpontiac** [home-assistant/home-assistant.github.io#26805]
### Feedback

this doc does show the X (not included) for supervisor and add-on features when doing continainer install

BUT

for those of us who are starting out... its not clear at all , do we need to then add this items seperately and if so... how do we do this

PLEASE

add some addiitnal clarificaitno here, with links and possibly trade-offs /options

### URL

https://www.home-assistant.io/installation/

### Version

2023.3.6

**Comment by frenck** [comment]
> do we need to then add this items seperately and if so... how do we do this

That is up to you and not a concern of our project. We just provide Home Assistant in those cases as those other features are not available. You are free to install additional software to your liking; consult the documentation of the other software you'd like to install.

../Frenck

**Comment by coolpontiac** [comment]
i dont understand your response?   your site implies its ok to install HA in a container, you show that Addons and Supervisor are NOT installed. if the purpose of documentation is to help users... than you should have some notes that explain  how a user who choses the container method can then address the lack of  supervisor and addons.

**Comment by pbowyer** [comment]
@coolpontiac I agree. It's not clear why addons won't work with the container method - is it a hardware limitation? A software limitation? Why should using the operating system be different to a container for _addons_?
