### ISSUE TITLE
Integrating your gas usage page doesn't describe how to configure home assistant

### ISSUE THREAD

**Issue by terryspitz** [home-assistant/home-assistant.github.io#26815]
### Feedback

For example I've added Octopus energy as an integration which provides gas meter readings, but I don't know for sure which sensor to add to the energy dashboard configuration. This could go on this page.

### URL

https://www.home-assistant.io/docs/energy/gas/

### Version

2023.3.6

**Comment by dannytsang** [comment]
Do you have the octopus home mini hub? If not, I suspect it wouldn't give you the hourly gas usage needed for the energy dashboard. If you do 🎉

When you go to add a gas sensor, it filters the list to what is acceptable and I feel the documentation on the gas setup page is sufficient and in the right place unless you have more detail on what's missing/needed.

![Screenshot_20230421-080047.png](https://user-images.githubusercontent.com/567982/233564548-64310717-8bbf-4894-ab03-ee743797340d.png)

**Comment by terryspitz** [comment]
I don't have the mini. So I'm probably only getting yesterday's readings.
