### ISSUE TITLE
Cannot change led status: Shelly Plus Plug S

### ISSUE THREAD

**Issue by atallo** [home-assistant/home-assistant.github.io#26810]
### Feedback

I have:

Shelly Plus Plug S
Firmware: 20230308-091544/0.14.1-g22a4cb7
Hardware: gen2 (SNPL-00112EU)

It does not allow turning on/off the led included in this device.

Thanks!

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2023.3.6

**Comment by thecode** [comment]
Please create a feature request here: https://community.home-assistant.io/c/feature-requests/13
This is repository is used for documentation issues.
Thanks 👍
