### ISSUE TITLE
Google Calendar keeps timing out when trying to install

### ISSUE THREAD

**Issue by NeoFax75** [home-assistant/home-assistant.github.io#26829]
### Feedback

It was working previously, then broke, re-installed, then broke like 4 more times and 4 more installs and now it just times out.  However from the same PC, I can ping the website fine.

### URL

https://www.home-assistant.io/integrations/google

### Version

2023.03.3

**Comment by allenporter** [comment]
Hi, can you add more detail about the symptoms?

**Comment by NeoFax75** [comment]
So I have had a works then breaks relationship with this integration for Google Calendar. It broke again for like the fifth time like a week and a half ago and today I had time to try and fix it.  So, I deleted the integration and then proceeded to click on +Add Integration-->google-->Google Calendar, it then spins for like 2-3 minutes and then says "Timeout establishing connection" and the only button is close.  I can go into terminal and ping calendar.google.com fine.

**Comment by allenporter** [comment]
What kind of home assistant installation? This is the documentation component, and the core issue component asks for more details.

There was a report from someone else who said translation files were not installed and they were using a non standard installation method

**Comment by NeoFax75** [comment]
I have a normal HAos install on Proxmox.

Home Assistant 2023.3.6
Supervisor 2023.03.3
Operating System 9.5
Frontend 20230309.1 - latest

**Comment by allenporter** [comment]
Thanks. Can you provide error and info logs?

Can you elaborate on what's not working that is causing you to uninstall?

**Comment by capsel22** [comment]
Experiancing same issue. Integration was working for past year. Today stopped. I deleted the integration and tried re-add, however it gets stuck on "Timeout establishing connection".

The only logs I can see are below, please let me know where to find any other logs

Logger: homeassistant.components.google.config_flow
Source: components/google/config_flow.py:95
Integration: Google Calendar ([documentation](https://www.home-assistant.io/integrations/google), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+google%22))
First occurred: 16:10:17 (3 occurrences)
Last logged: 16:24:58
Timeout initializing device flow: [Errno 110] Operation timed out

I've tried removing application credentials, rebooting the HA but nothing worked.

I am running HA in KVM on Ubuntu. Eveything updated to latest.

**Comment by allenporter** [comment]
Perhaps see https://github.com/home-assistant/core/issues/90665 given your error message is similar. The error indicates a problem with talking over the network.

**Comment by allenporter** [comment]
Closing this issue since #90665 is in core and this is in the documentation component.
