### ISSUE TITLE
Account with google login

### ISSUE THREAD

**Issue by Watever44** [home-assistant/home-assistant.github.io#26826]
### Feedback

I have a tractive account but it's linked to my google account for sign in. Meaning, I don't have a dedicated login and password for tractive. 

How should I be able to add my account to tractive integration in that case ?

### URL

https://www.home-assistant.io/integrations/tractive/

### Version

2023.3.6

**Comment by zhulik** [comment]
Hey, @Watever44 they may support setting password for accounts created with Google ouath. You can try the reset password feature or there may be a form for setting the password somewhere under account setting

**Comment by bieniu** [comment]
This is a documentation repository and your problem is not related to it.

**Comment by Watever44** [comment]
> Hey, @Watever44 they may support setting password for accounts created with Google ouath. You can try the reset password feature or there may be a form for setting the password somewhere under account setting

True, I realized you can "change" your password even if you didn't create an account with a password for tractive and then you can log with it
