### ISSUE TITLE
Viessmann API Keys how?

### ISSUE THREAD

**Issue by mxcxpx** [home-assistant/home-assistant.github.io#26836]
### Feedback

it is not clear for me how to get the Viessmann API Key.

i read the steps how to do it, i tryed to understand but i need more detail with this steps.
or an youtube video. 

thanks

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2023.3.6

**Comment by high-home** [comment]
I also have this issue. Instruction is too vague. Differently from the instructions: Viessmann appears to allow creation of developer account and has a Generate Access Token section in the Developer portal but then when you paste that into Home Assistant you repeatedly get   "Invalid Authentication".

**Comment by madaraszg** [comment]
I have a same issue myself, trying to add a Viessmann gas boiler.

**Comment by fabian727** [comment]
go to [Developer Viessmann](https://developer.viessmann.com/start.html)
![image](https://github.com/home-assistant/home-assistant.io/assets/11717140/325a3fae-4ddb-4f0b-8fa0-ef0c8a0fd07d)
open "My Dashboard" and login
You have to create a client
Afterwards you can create a token.

Hope it helps.

If I reload the page 2 times, the token is gone...
If I copy&paste the token to my homeassistant installation and click "Submit" it takes a while, then the token is gone...

I don't know if my slow web-access is a problem or my fresh generated acount...

**Comment by fabian727** [comment]
Edit:
got one step further: read the hass manual very carefully!

create the client
name it PyViCare
disable recaptcha
set the URI: vicare://oauth-callback/everest
store it, copy the **CLIENT ID** to hass as API

Now I get the error, that I do not possess any devices (physical installation of the device has not been completed yet ... )

**Comment by fabian727** [comment]
after downloading the ViCare App and entering my account and device details. Hass does find the device and entities.

**Comment by rhoerbe** [comment]
Using the GUI to the Vicare integration, I named the client PyViCare, disabled recaptcha, added vicare://oauth-callback/everest and filled in the Access Token. There is no filed to enter the client ID.

And the error message is still "invalid authentication". It is not clear which authentication .userid and password, or the API's access code.

**Comment by privatecoder** [comment]
`API Key` should be called `Client ID` as its value is the one that you need to enter in the `API Key` field. No need to generate an `Access Token`.

I had to enter it twice though, i.e. I would get invalid authentication on the first try with `E-Mail` + `Password` + `Client ID` on the first try while it worked trying again right afterwards.

This is also documented [here](https://www.home-assistant.io/integrations/vicare/) under step 4: _"Copy the Client ID from the Viessmann portal and enter this in the API Key field in Home Assistant."_
