### ISSUE TITLE
How search with ignore word

### ISSUE THREAD

**Issue by Felixlechatt** [home-assistant/home-assistant.github.io#26847]
### Feedback

Hi, i'm french

So, how in caldav "search" all include with ignore "trash" because i'have already calandar trash.

SQL exemple:
/CalDAV/calendar_home_set/username/calendar_name/?query=SELECT * FROM VEVENT WHERE SUMMARY REGEXP '.*' AND NOT (SUMMARY REGEXP 'poubelle')

calendar:
  - platform: caldav
    username: !secret idcalendar_caldav_syno
    password: !secret passcalendar_caldav_syno
    url: !secret urlcalendar_caldav_syno
    #calendars:
    #   - 'AgendaMQ'
    days: 16
    custom_calendars:
      - name: 'Anniversaire'
        calendar: 'AgendaMQ'
        search: '.+Anniversaire'
      - name: 'All' #all but not the Anniversaire + Poubelle
        calendar: 'AgendaMQ'
        search: '.*-.+Poubelle$'
      - name: 'Poubelle'
        calendar: 'AgendaMQ'
        search: 'Poubelle'

### URL

https://www.home-assistant.io/integrations/caldav/

### Version

2023.3.6

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
