### ISSUE TITLE
Iaqua for Zodiac eXO IQ Dual Link

### ISSUE THREAD

**Issue by helgedk** [home-assistant/home-assistant.github.io#26840]
### Feedback

Hi, will iaqua Link for Zodiac eXO IQ Dual Link be supported in the future?

### URL

https://www.home-assistant.io/integrations/iaqualink/

### Version

2023.3.6

**Comment by flz** [comment]
There is some experimental support. Have a look at the iaqualink repository.

This isn't a home assistant issue.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
