### ISSUE TITLE
Integration does not work

### ISSUE THREAD

**Issue by pwo108** [home-assistant/home-assistant.github.io#26841]
### Feedback

The integration ends with an error message:
No systems detected or supported
19:04:15 – (ERROR) Jandy iAqualink
vr is not a supported system type.
19:04:15 – (WARNING) components/iaqualink/__init__.py - 

The iaqualink app works properly and communicates with my devices.

### URL

https://www.home-assistant.io/integrations/iaqualink/

### Version

2023.3.6

### Additional information

I suspect a problem with API keys blocking the access.

**Comment by flz** [comment]
It's not an API issue, it says pretty clearly that your system isn't supported.

You can put in a feature request in the iaqualink repository but i won't be adding support unless somebody sends a pull request for it.
