### ISSUE TITLE
Please extend the instructions for the core installation

### ISSUE THREAD

**Issue by Zjokke** [home-assistant/home-assistant.github.io#26864]
### Feedback

The instructions are clear for now, but do not include what to do in order to start Home Assistant automatically after a reboot of the Raspberry PI.
Can you please extend the instructions?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.3.6

**Comment by frenck** [comment]
Not listing those has been an explicit choice.

The installation method is aimed at advanced users, who should know their way around these things. There are many different choices of distributions and init systems around, so a single instruction isn't doable.

In case you don't know your way around Linux administration, we highly suggest looking at one of our other installation methods that might be a better fit for you.

../Frenck
