### ISSUE TITLE
Cannot access the desktop site from mobile

### ISSUE THREAD

**Issue by petersohn** [home-assistant/home-assistant.github.io#26860]
### Feedback

The website looks like this on desktop.

![Screenshot_20230404_115207](https://user-images.githubusercontent.com/2822847/229755646-89e1d246-ed11-4691-a4a3-73273ae07bca.png)

On mobile, it looks like this.

![2023-04-04 11 52 52](https://user-images.githubusercontent.com/2822847/229755994-924818d0-7959-46c4-b2e4-e73c4677a7e4.png)

So far, this is fine. However, if I ask for the desktop site via my browser on mobile, I expect to get the same result as on desktop. But instead, I get this:

![2023-04-04 11 53 11](https://user-images.githubusercontent.com/2822847/229756254-c554cc57-ad0c-44e1-9014-c1a9b2d701ba.png)

Turning to landscape orientation doesn't help either.

### URL

https://www.home-assistant.io/

### Version

2023.03

**Comment by frenck** [comment]
I'm not seeing the issue you are trying to raise, maybe I'm missing the obvious, but could you describe / point me to the issue in words?

../Frenck
