### ISSUE TITLE
i need license that allows coolmaster net to connect directly to the VRV system

### ISSUE THREAD

**Issue by duyminhhaui** [home-assistant/home-assistant.github.io#26863]
### Feedback

Hello.My name is Minh. i come from Viet Nam . i'm technician of a smart home company in Vietnam. I have been using your CoolMaster Net device for a long time, but recently in Vietnam, Daikin Vietnam does not allow us to directly connect CoolMaster Net to the VRV system. We need you to provide us with a license that can demonstrate permission from Daikin to allow CoolMaster Net to connect directly.Thanks

### URL

https://www.home-assistant.io/integrations/coolmaster/

### Version

2023.3.6

### Additional information

I am in great need need your supply. hope you can reply me soon

**Comment by duyminhhaui** [comment]
you can contact me on viber at my phone: +84 32 9898 312

**Comment by OnFreund** [comment]
This is an open source project and is not affiliated with the company. I suggest you reach out to them on their support channels.

**Comment by OnFreund** [comment]
@home-assistant close
