### ISSUE TITLE
Minimum required AppleTV version missing

### ISSUE THREAD

**Issue by phisparks** [home-assistant/home-assistant.github.io#26876]
### Feedback

What is the minimum required version of AppleTV and OS supported by this integration?

Is AppleTv 2 supported and if so, how do you configure it?

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2023.3.6

**Comment by postlund** [comment]
All versions should work out of the box, assuming it is discovered. Otherwise manually add it.

**Comment by phisparks** [comment]
Sounds great and works fine on my atv3 and atv 4k but not on my atv2.

It is discovered automatically but when I select configure I either get a pairing message to enter the pin on my atv2, but I have nowhere to enter it, or a pin is displayed on the atv2 but then the integration doesn't provide an input for the pin. 

Whichever alternative of the above scenarios depends on if the airplay setting "on screen code" is set to off or on.

Do you have any idea on how to get them connected?

Many thanks in advance. 

/J
