### ISSUE TITLE
An example would be useful

### ISSUE THREAD

**Issue by smbunn** [home-assistant/home-assistant.github.io#26888]
### Feedback

I have never understood what a cover is.  I don't know how to create one and now there are new tiles for covers I would love to use them.  It would be extremely useful if the documentation page actually had an example of a cover.  At them moment it documents how to add an automation to a cover but not how to actually create a cover.  I have 6 curtains with position control, no idea how I make covers from these devices.  

### URL

https://www.home-assistant.io/integrations/cover/

### Version

2023.4.0

**Comment by captshadab** [comment]
Hi which smart curtains are you using 

I have switchbot so have 2 methods of configuring them. One via direct Bluetooth connection
Another by manual yaml configuration 

Does your smart curtain brand have official integration in home assistant?

**Comment by captshadab** [comment]
Trying going to curtain entity setting and you will find an option to SHOW AS

Make sure curtain is selected in there 

![image](https://user-images.githubusercontent.com/110346999/230320780-24d3bc61-f1b5-4072-b19f-383d074a1bcf.jpeg)

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

---

But to answer your question anyway: an integration for your curtains creates the cover entities for you, then you can adjust in the entity settings how Home Assistant should show it in terms of device type (like above screenshot).

Thanks! 👍
