### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by PhaseAngle** [home-assistant/home-assistant.github.io#26891]
### Feedback

I get this error when I try to set up my camera
why so helpful?

### URL

https://www.home-assistant.io/integrations/onvif/

### Version

2023.4.0

**Comment by frenck** [comment]
Hi there @PhaseAngle 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by PhaseAngle** [comment]
sorry had both pages open

**Comment by frenck** [comment]
Don't worry about it 👍
