### ISSUE TITLE
switch.turn_on does the service still send a on command if the switch already has state on?

### ISSUE THREAD

**Issue by rrozema** [home-assistant/home-assistant.github.io#26896]
### Feedback

As an automation builder I would like to know if the services that set an explicit state -like f.e. switch.turn_on and switch.turn_off- still send a command if the state for this switch already matches the requested state. If they do send such repeated commands, it could be beneficiary to the network speed & overall responsiveness to add conditions to some scripts/automations that could potentially get called often. If they don't re-send commands i would however be overcomplicating my scripts/automations by adding unneeded conditions. The documentation for switch does not answer this question, so I can not tell what would be the best approach. Can you please add this information?

### URL

https://www.home-assistant.io/integrations/switch/

### Version

2023.4.0

**Comment by rrozema** [comment]
My question has not been answered and I have not yet seen any alterations
in the documentation explaining the behavior of the services in the
situation when the existing state already matches the requested state.

I personally think it would be best to make an addition in the
documentation so that everyone will know what behavior to expect, but my
issue will be solved too by an answer in here.

Op ma 5 jun. 2023 15:05 schreef github-actions[bot] <
***@***.***>:

**Comment by rrozema** [comment]
I still do not know if the command is still sent.

Op vr 4 aug. 2023 18:03 schreef github-actions[bot] <
***@***.***>:

**Comment by balloob** [comment]
It is
