### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by v8schlumpf** [home-assistant/home-assistant.github.io#26892]
### Feedback

The documentation is outdated

### URL

https://www.home-assistant.io/integrations/edl21/

### Version

2023.4.0

**Comment by l3d00m** [comment]
Hi, I'm not a contributor here, but it might be helpful if you at least point to the section that's outdated.

**Comment by stefanhirt** [comment]
I think v8schlumpf refers to the warning in 2023.4.0 that says that EDL21 via YAML will not be supported in version 2023.6.0+ and has to be removed from configuration.yaml or a sensor.yaml.
![EDL21](https://user-images.githubusercontent.com/14818988/230391186-f0d5ad19-75ac-49d2-90ce-323ea1b73983.png)

**Comment by devployment** [comment]
Just got trapped by the same thing. The docs linked above still refer to the yaml configuration. The "repair" talks about it deprecated. 

Additional note from my side. I tried to change the USB device path **after** disabling the config section. This seems not to be possible. Adding a new EDL21 integration shows the path config as the first step. 

Eventually changing existing config is not supported yet/planned. Mildly confusing somehow. :)
