### ISSUE TITLE
Known issues in matter documentation are probably outdated

### ISSUE THREAD

**Issue by l3d00m** [home-assistant/home-assistant.github.io#26895]
### Feedback

The "Known issues" section below "Current state of the integration" contains the following sentence "Both issues will be fixed in Home Assistant 2023.3."

I'm not sure if it's fixed already, since 2023.4 is now out, but in any case that text should probably be updated.

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2023.4.0

**Comment by marcelveldt** [comment]
thanks for the reminder, we'll address this!

**Comment by marcelveldt** [comment]
Fixed in https://github.com/home-assistant/home-assistant.io/pull/27136
