### ISSUE TITLE
Workday sensor example(s) incorrect

### ISSUE THREAD

**Issue by Symbiot78** [home-assistant/home-assistant.github.io#26904]
### Feedback

Example 1 does not seem correct.
I I create the exact same setup it will NOT exclude the add_holidays dates.
only when I add 'holiday' to excludes it will recognize the dates I've added under add_holidays.
It is easily replicable.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2023.4.1

### Additional information

not much. 

see this thread from 2021 for more info/discussion

https://community.home-assistant.io/t/workday-add-holidays-not-working/359953/11

**Comment by gjohansson-ST** [comment]
That should be a bug in core instead as it should work to add manual exclusions without having the default holiday-list. 

Can you please open an issue in core instead for this. 

Thanks

**Comment by gjohansson-ST** [comment]
@home-assistant close
