### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sandman4050** [home-assistant/home-assistant.github.io#26902]
### Feedback

I am able to follow all the steps possible, I receive the "code" from developer options F12. When I put in the "code" it accepts it but says failed to configure. I logs show the following error (put stars for safety):

2023-04-06 21:41:26.298 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 506*** for simplisafe
File "/usr/src/homeassistant/homeassistant/components/simplisafe/__init__.py", line 357, in async_setup_entry

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2023.4.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
