### ISSUE TITLE
Error 400 thru this platform

### ISSUE THREAD

**Issue by Philippe59710fr** [home-assistant/home-assistant.github.io#26906]
### Feedback

Hi there,

I tried first a french voice in francecentral datacenter, but error 400
I then created a eastus and copied/pasted the sample : same problem
I tried the microsoft curl and python samples on my azure ressource : fine
I then directly tried the python library : fine. I tried to force the endpoint, but no way with the integration.

A pitty because the voices are nice.
This problem seems old, but I found no other ressources to fix it sorry

I suppose this platform has to be updated in order to use the newest pycsspeechtts code.

### URL

https://www.home-assistant.io/integrations/microsoft/

### Version

2023.4.1

### Additional information

Maximum debug info : 
logger:
  default: warn
  #critical, fatal, error, warning, warn, info, debug
  logs:
    homeassistant.components.tts: debug

Contents of the logs : 
2023-04-07 10:31:15.283 ERROR (SyncWorker_4) [pycsspeechtts.pycsspeechtts] Text synthesis failed, statuscode 400, reason: 

Conf of the TTS : 
tts:
  - platform: microsoft
    #isCustom: true
    #customEndpoint: https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken
    api_key: c084228311034246a448095d4debea-- ( modified )
    language: en-gb
    gender: Male
    type: RyanNeural
    rate: 20
    volume: -50
    pitch: high
    contour: (0, 0) (100, 100)
    region: eastus

With cognitive test console ( fine ) : 

Query : 
POST https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0/projects HTTP/1.1
Host: eastus.api.cognitive.microsoft.com
Content-Type: application/json
Ocp-Apim-Subscription-Key: ••••••••••••••••••••••••••••••••
{
  "locale": "en-US",
  "displayName": "My speech project"
}

Response :
Transfer-Encoding: chunked
api-supported-versions: 2.0,3.0
api-deprecated-versions: 2.0
apim-request-id: 0a93931b-8c9f-4f8b-a219-561b07eb090e
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
x-ms-region: East US
Cache-Control: no-store
Date: Fri, 07 Apr 2023 08:35:12 GMT
Location: https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0/projects/6bbaea00-635c-48b2-b826-bfdf28fc08ff
Content-Type: application/json; charset=utf-8

{
  "self": "https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0/projects/6bbaea00-635c-48b2-b826-bfdf28fc08ff",
  "links": {
    "evaluations": "https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0/projects/6bbaea00-635c-48b2-b826-bfdf28fc08ff/evaluations",
    "datasets": "https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0/projects/6bbaea00-635c-48b2-b826-bfdf28fc08ff/datasets",
    "models": "https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0/projects/6bbaea00-635c-48b2-b826-bfdf28fc08ff/models",
    "endpoints": "https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0/projects/6bbaea00-635c-48b2-b826-bfdf28fc08ff/endpoints",
    "transcriptions": "https://eastus.api.cognitive.microsoft.com/speechtotext/v3.0/projects/6bbaea00-635c-48b2-b826-bfdf28fc08ff/transcriptions"
  },
  "properties": {
    "datasetCount": 0,
    "evaluationCount": 0,
    "modelCount": 0,
    "transcriptionCount": 0,
    "endpointCount": 0
  },
  "createdDateTime": "2023-04-07T08:35:12Z",
  "locale": "en-US",
  "displayName": "My speech project"
}

Fine also using curl : 
curl --location --request POST "https://${SPEECH_REGION}.tts.speech.microsoft.com/cognitiveservices/v1" ^
--header "Ocp-Apim-Subscription-Key: ${SPEECH_KEY}" ^
--header 'Content-Type: application/ssml+xml' ^
--header 'X-Microsoft-OutputFormat: audio-16khz-128kbitrate-mono-mp3' ^
--header 'User-Agent: curl' ^
--data-raw '<speak version='\''1.0'\'' xml:lang='\''en-US'\''>
    <voice xml:lang='\''en-US'\'' xml:gender='\''Female'\'' name='\''en-US-JennyNeural'\''>
        my voice is my passport verify me
    </voice>
</speak>' > output.mp3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
