### ISSUE TITLE
Better compatibility than advertised - Reolink

### ISSUE THREAD

**Issue by gh69** [home-assistant/home-assistant.github.io#26903]
### Feedback

No issue here...just feedback...

The ReoLink documentation reads:

The following models are lacking the HTTP webserver API and can therfore not work with this integration:
    E1 Pro
    E1

But this isn't 100% true...  I have 3 E1 Pro's that each get more and more integrated with HA after each release of your ReoLink integration.  The trick is, these cameras have to be connected to the ReoLink NVR, and the NVR connected to HomeAssistant via the integration.  This provides HA with devices for all cameras on the NVR including the E1's, and they all get the entities appropriate for that device.  I'm very happy to see that most of the latest and greatest additions, including the dynamically populated PTZ preset entities, are available for the E1 Pros's connected to HA via the NVR, even though these cams can't be accessed directly via web interface.  Thank you!

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.4.1

**Comment by starkillerOG** [comment]
@gh69 thanks for pointing this out!
I have adjusted the documentation in this PR: https://github.com/home-assistant/home-assistant.io/pull/26909

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.

**Comment by starkillerOG** [comment]
@home-assistant close
