### ISSUE TITLE
Energy Cards - Self-coverage gauge

### ISSUE THREAD

**Issue by jdelwig** [home-assistant/home-assistant.github.io#26912]
### Feedback

In addition to the existing solar consumed gauge, it would be helpful, if there would be a gauge of the self-coverage ratio. By this I mean the percentage of the energy consumed in the house, that was covered by solar power.

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2023.4.1

**Comment by dannytsang** [comment]
This sounds like a feature request however it's ended up in the documentation feedback.

I would suggest going to New Issue > Feature Request and raising it there.
