### ISSUE TITLE
Service GOOGLE.CREATE_EVENT now requires location param to be set

### ISSUE THREAD

**Issue by istvandocsa** [home-assistant/home-assistant.github.io#26915]
### Feedback

According to https://www.home-assistant.io/integrations/google/#service-googlecreate_event the location param is optional.
There was a recent breaking change to the integration: https://github.com/home-assistant/core/pull/89533 but it does not mention the location param in the description.
After upgrading to Home Assistant 2023.4.1 I will get the following error if location is not provided:
```
Google Calendar: Create event ---
Stopped because an error was encountered at April 7, 2023 at 19:29:21 (runtime: 0.03 seconds)

'location'
```

### URL

https://www.home-assistant.io/integrations/google/#service-googlecreate_event

### Version

2023.4.1

**Comment by allenporter** [comment]
Thanks for the report. Seems like this is a bug in PR #90098 since it always gets the location expecting it to be there.

**Comment by allenporter** [comment]
To clarify, this is not a documentation issue but a bug in that PR

**Comment by allenporter** [comment]
Fixing in #91061

I am closing since this issue is in the documentation component, but it's a home-assistant core issue.  This will be tagged for an upcoming patch release.
