### ISSUE TITLE
Vague Language

### ISSUE THREAD

**Issue by RichardUUU** [home-assistant/home-assistant.github.io#26910]
### Feedback

From the page: "A Reolink user account with admin privileges is needed for the proper operation of this integration."

Does that mean a user account on the cameras? Or a user account with something like reolink.com?

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.4.1

**Comment by starkillerOG** [comment]
@RichardUUU it means the user account on the camera, you also need to use the username and password of the user account on the camera. The whole integration is local, no communication with the cloud.

Please refrase in a manner you think is more clear and make a PR to adjust the documentation, in that way you help all future users.
