### ISSUE TITLE
Etcher didnt like pulling image from URL

### ISSUE THREAD

**Issue by itcsburnett** [home-assistant/home-assistant.github.io#26916]
### Feedback

I was following the instructions to use a USB Ubuntu * Etcher to write the HAOS to the M2 drive in a NUC.
I tried several times but kept getting an error as it started complaining that the image may be compressed.
I downloaded the image directly and then used the burn from file option and that worked.  Dont know why.  the speed of my internet is 200/200 but it did seem rather slow downloading.

So might just want to add a caveat that if the URL option doesn't work go to github and download directly and use that

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2023.3.6

**Comment by c0ffeeca7** [comment]
colved by #27022. Added step instruction to decompress image after downloading.
