### ISSUE TITLE
Workday sensor integration documentation

### ISSUE THREAD

**Issue by Symbiot78** [home-assistant/home-assistant.github.io#26911]
### Feedback

Example 1 does not seem correct.
I I create the exact same setup it will NOT exclude the add_holidays dates.
only when I add 'holiday' to excludes it will recognize the dates I've added under add_holidays.
It is easily replicable.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2023.4.1

### Additional information

not much. 

see this thread from 2021 for more info/discussion

https://community.home-assistant.io/t/workday-add-holidays-not-working/359953/11

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2023.4.1

**Comment by gjohansson-ST** [comment]
Why do you open another issue here?
It's not a documentation problem but instead would be a bug in the implementation.
Please open an issue in core instead --> [here](https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml)

**Comment by gjohansson-ST** [comment]
@home-assistant close
