### ISSUE TITLE
Service call missing in docs

### ISSUE THREAD

**Issue by gigatexel** [home-assistant/home-assistant.github.io#26919]
### Feedback

I just added my first Unifi Protect device (G4 Doorbell Pro).
I noticed the service `unifiprotect.set_doorbell_message` was created, but this service is not documented in the docs.

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2023.4.1

**Comment by bdraco** [comment]
It was removed from the docs when it was deprecated in December

https://github.com/home-assistant/core/pull/83675

**Comment by bdraco** [comment]
https://github.com/home-assistant/home-assistant.io/pull/25218

**Comment by bdraco** [comment]
Use the text entity that was added in https://github.com/home-assistant/core/pull/83674 instead
