### ISSUE TITLE
After install: "This site can’t be reached"

### ISSUE THREAD

**Issue by sachaweb** [home-assistant/home-assistant.github.io#26929]
### Feedback

I bought an Intel NUC with HA pre-installed. When started, with LAN cable in, LEDs on, trying to reach HA from my usual machines fails, with or without VPN turned on. I tried these:
    	- http://192.168.2.183/
	- http://homeassistant.local:8123/
    	- http://localhost:8123

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2023.4.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
