### ISSUE TITLE
Battery level not working anymore. 

### ISSUE THREAD

**Issue by jandirk39** [home-assistant/home-assistant.github.io#26920]
### Feedback

Ever since the HA upgrade the battery entity is not working anymore. I re-added the toothbrush and now the battery entity is not even present anymore. I used it for quite sometime to send messages when the battery was low. Is this is issue already under investigation?

### URL

https://www.home-assistant.io/integrations/oralb/

### Version

2023.4.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
