### ISSUE TITLE
Can't make a standard account

### ISSUE THREAD

**Issue by Billabongodysee** [home-assistant/home-assistant.github.io#26932]
### Feedback

There doesn't seem to be a way to make an account like the integration doc says.

### URL

https://www.home-assistant.io/integrations/totalconnect/

### Version

2023.4.2

**Comment by austinmroczek** [comment]
It's possible to use an Admin account if that is all your alarm company lets you do.  You'll get a warning message in the logs.

I was just able to create a new standard user under my account.  Guessing it's something to do with your alarm company settings/permissions
