### ISSUE TITLE
The example configuration for worxlandroid pincode is missing quotes

### ISSUE THREAD

**Issue by billerby** [home-assistant/home-assistant.github.io#26935]
### Feedback

Recently added this sensor and the regular expression match for the pin failed when using the example config.yml snippet. It seems to be due to missing quotes, thus not treating it as a String. Got the following error without quoting the pincode:

`vol.Match(r"\d{4}") an exception is thrown: Invalid config for [sensor.worxlandroid]: does not match regular expression \d{4} for dictionary value @ data['pin']. Got 0. (See ?, line ?). `

However quoting it make the configuration pass. 

### URL

https://www.home-assistant.io/integrations/worxlandroid/#pin

### Version

2023.4.2

**Comment by barosan909** [comment]
I have done the following and still the same error pops up:

  
sensor:
  - platform: worxlandroid
    host: 192.168.0.12
    pin: "AAAA"
    
    also tried with single quotes and still no change:
    
    `The system cannot restart because the configuration is not valid: Invalid config for [sensor.worxlandroid]: does not match regular expression \d{4} for dictionary value @ data['pin']. Got 'AAAA'. (See ?, line ?).`

**Comment by Goldohrack** [comment]
I think it doesn't take into account the digital alpha pin cdes
