### ISSUE TITLE
Ask user to veryfy python3 --version returns correct version.

### ISSUE THREAD

**Issue by InnerBushman** [home-assistant/home-assistant.github.io#26938]
### Feedback

In the note under the `Install Home Assistant Core` section header:

> Prerequisites
> This guide assumes that you already have an operating system setup and have installed Python 3.10 (including the package
> python3-dev) or newer.

please add a mention to verify before proceeding that  `python3 --version`  returns 3.10. The installation instructions for Python I used only told me to update the alternatives for `python` and not `python3`. Took me way to long to figure that the newly created virtual environment was copying 3.9.x and not the freshly installed 3.10.0, because all the commands are `python3` and not `python` or `python3.10`.
Let's save people like me some headaches.
Thanks.

### URL

https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core

### Version

2023.4.2

**Comment by frenck** [comment]
Hi there @InnerBushman 👋 

Thanks for the suggestion; however, considering how advanced the installation method is and considering the text clearly states the required versions; we will assume these things are known to the user.

If not, we strongly recommend using a different installation method.

../Frenck
