### ISSUE TITLE
No possibility to add home connect account after filling in wrong credentials

### ISSUE THREAD

**Issue by Arkie1978** [home-assistant/home-assistant.github.io#26937]
### Feedback

No possibility to add home connect account after filling in wrong credentials:

i'll get this message: {
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmbG93X2lkIjoiOGExZWIyYzYxNTdlMTZjM2FlNzc2ZDhiMjdhNjYyYzYiLCJyZWRpcmVjdF91cmkiOiJodHRwczovL215LmhvbWUtYXNzaXN0YW50LmlvL3JlZGlyZWN0L29hdXRoIn0.k9NtRV_bDVfgKcjvOrfZA5XmInEbJlaTnHEUNuho5jk"
}

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2023.4.2

**Comment by DavidMStraub** [comment]
You can remove the integration and add it again.
