### ISSUE TITLE
Switches are not created

### ISSUE THREAD

**Issue by michaelmadsen72** [home-assistant/home-assistant.github.io#26945]
### Feedback

When using the "Block Network Access For Clients" feature and selecting a few wireless devices, no switches are created to block/unblock network access.
I have reloaded the integration and even restarted HA.

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2023.4.2

**Comment by frenck** [comment]
Hi there @michaelmadsen72 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
