### ISSUE TITLE
Describe where this label can be found

### ISSUE THREAD

**Issue by groofyke** [home-assistant/home-assistant.github.io#26965]
### Feedback

Hi,
would be good to also describe where a user can find this quality label.

Thanks,
Mikaël

### URL

https://www.home-assistant.io/docs/quality_scale/

### Version

2023.4.2

**Comment by frenck** [comment]
This is a landing page, this is where you get when click on the quality scale on the places it is being used:

![image](https://user-images.githubusercontent.com/195327/231452008-acd39cff-43be-4464-b68b-df1c04f2d2b6.png)

**Comment by diegov00** [comment]
Is it possible to add a filter on the Integrations page to show the list of integrations with a selected quality score? 
https://www.home-assistant.io/integrations/
