### ISSUE TITLE
Adding itunes in configuration.yaml, makes MA crash

### ISSUE THREAD

**Issue by rvandet** [home-assistant/home-assistant.github.io#26969]
### Feedback

The latest BETA Music Assistant crashed (502) after adding the YAML configuration for itunes as described on "https://www.home-assistant.io/integrations/itunes/". I did not specify a port. I have installed the latenst HA on a HP thin client.

### URL

https://www.home-assistant.io/integrations/itunes/

### Version

2023.4.2

**Comment by frenck** [comment]
Music assistant is not provided, supported, or maintained by the Home Assistant project. If you have issues with it, please report it with the author of that project.

../Frenck
