### ISSUE TITLE
Binary sensor reference should be "co" not "co2"

### ISSUE THREAD

**Issue by stevem405** [home-assistant/home-assistant.github.io#26967]
### Feedback

Carbon monoxide is a poisonous gas while carbon dioxide is not.
Mapping in type_sensor.py is correct, only the docs are wrong. 

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2023.4.2

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/231468495-d6e9ab87-aca7-4e20-bd7b-3e5377e27c9a.png)


I'm not sure what is wrong here? Could you clarify?

**Comment by stevem405** [comment]
I believe for the binary sensor in homekit_controller binary_sensors.py, only CO is supported
_attr_device_class = BinarySensorDeviceClass.CO

While there is a CO2 sensor, there is no CO2 binary sensor, as far as I can tell.  (BTW, the filename in my first post was incorrect.)

**Comment by frenck** [comment]
Aah now I see it, thanks!

![image](https://user-images.githubusercontent.com/195327/231475832-061b90a3-10ed-49ce-a3bc-b21f4f26a489.png)


`co2` should have been `co` in that particular case.

../Frenck
