### ISSUE TITLE
Link to scripting language?

### ISSUE THREAD

**Issue by jpravetz** [home-assistant/home-assistant.github.io#26974]
### Feedback

Would this be a good page to provide a link to how to customize dashboard yaml, including scripts/templates that run inside the yaml? If it's not here, where is that link (ie. is it easy for users to find?). 

### URL

https://www.home-assistant.io/dashboards/

### Version

2023.4.2

**Comment by dannytsang** [comment]
When you say customize, do you have an example of what you mean by this?

There are YAML examples on the right hand side from multiple dashboards to the cards themselves.

**Comment by jpravetz** [comment]
Customize with code, for example:

```
        custom_fields:
          temp: |
            [[[
              return `${states["sensor.atrium_temperature"]?(Math.round(10*states["sensor.atrium_temperature"].state)/10)+'˚C':'?'}`
            ]]]
          humidity: |
            [[[
              return `${states["sensor.atrium_humidity"]?states["sensor.atrium_humidity"].state+'%':'?'}`
```

Is this the same as templates, lambda functions, or where do I go to learn the syntax and functions available? I don't see a link in the body of this page or the right sidebar, and it would be helpful?

**Comment by dannytsang** [comment]
It looks more like Javascript and not a template and would suggest something outside of the core functionality Home Assistant such as custom component/HACS.

At this time, I think the documentation and the links on the right should cover customising the dashboard unless you have more specific information/questions on what you like to see.

**Comment by jpravetz** [comment]
Links in the sidebar make sense to me.
