### ISSUE TITLE
please be more precise on your doc ...

### ISSUE THREAD

**Issue by vevere** [home-assistant/home-assistant.github.io#26971]
### Feedback

please,
be smart with newbees, please write on your docs WHICH and WHERE are the config files.
I never (NEVER !!!!!!!!!!!!!) see in which config file I must write what is explained on the doc

I never know if I have to create a config file or if I have to put some lines on an existing files

and on each forum topic it is the same, youcan read billions of exemples ... but you don't know where to put it

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2023.4.2

**Comment by frenck** [comment]
The templating language is used across most of Home Assistant config files (including the ones you create yourself). It does not limit to any specific file or location (we also accept our templating languages in many places in our UI).

For more generic information about our configuration formats and locations, see: <https://www.home-assistant.io/docs/configuration/>  (Top menu -> Documentation -> Configuration on the website).


../Frenck

**Comment by olejessien** [comment]
Hey Frenck, your comment is extremely valuable information for anyone trying to get started. Could it perhaps be added ad verbatim to the start of the docs? I have spent the best of two hours trying to progress before I accidentally landed on “feedback from others” and saw this.
Thanks

**Comment by frenck** [comment]
> Could it perhaps be added ad verbatim to the start of the docs?

It is, it is part of the getting started manuals as well.
