### ISSUE TITLE
Energy Usage card could be improved

### ISSUE THREAD

**Issue by andrzej-r** [home-assistant/home-assistant.github.io#26996]
### Feedback

While I like the general concept with break down of energy usage by source and energy export by destination, I find it quite confusing and not at all easy to read.

First of all, a chart named "Energy usage" implies details of energy consumption (total consumption broken down by home, battery, individual devices), not total consumption split by source of this energy. Similarly, negative usage implies total energy export to grid - again I would assume it to be split into PV generation, battery discharge etc.

Also, most of the time I am interested in import or export, rarely both of them together. I would be nice to have an option to separate the two to reduce clutter.

Having said that, a split of energy consumption by source, as currently implemented, is useful as well. Perhaps we should have a separate card or an option to control what is being shown?

Another issue I have with the cards is the sort order and colors of bars. It would be nice if colors were related to each other by category (that is energy import having similar color to energy export, battery charge to battery discharge) and sorted in order of importance. While the importance is subjective, I would suggest grid import/export to be the placed closest to X axis, then generation, then battery charge/discharge (away from X axis).

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2023.4.2

**Comment by dannytsang** [comment]
Hi @andrzej-r

This looks to be feedback related to enhancements in Home Assistant and unfortunately it has been logged in the documentation feedback. If I could ask you to go to New issue > Feature Request, check and post your suggestion there please.
