### ISSUE TITLE
Break down generation into home/grid/battery

### ISSUE THREAD

**Issue by andrzej-r** [home-assistant/home-assistant.github.io#26995]
### Feedback

It would be useful to know a bit more about what happens with the generated energy. A chart with breakdown similar to an Energy Usage card would be very handy.

### URL

https://www.home-assistant.io/docs/energy/solar-panels/

### Version

2023.4.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
