### ISSUE TITLE
Does this integration support Apple TV 4K 2022 (3 gen)?

### ISSUE THREAD

**Issue by avenom** [home-assistant/home-assistant.github.io#26990]
### Feedback

Does this integration support Apple TV 4K 2022 (3 gen)?

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2023.4.2

**Comment by frenck** [comment]
As per linked documentation:

![image](https://user-images.githubusercontent.com/195327/231730170-d753665f-a69a-4741-ac42-c3add6504665.png)

So: yes.

../Frenck
