### ISSUE TITLE
State of charge not included

### ISSUE THREAD

**Issue by andrzej-r** [home-assistant/home-assistant.github.io#26994]
### Feedback

I find the lack of battery State of Charge information severely limiting usefulness of the Energy Dashboard.

Also, it would be useful to have a card dedicated to the battery, with a history of energy flow, ideally broken down into contributors (grid, house, generation) like in Energy Consumption card) and SoC (in % or kWh).

### URL

https://www.home-assistant.io/docs/energy/battery/

### Version

2023.4.2

**Comment by dannytsang** [comment]
Hi @andrzej-r 

This looks like a feature request rather than a documentation feedback. Can you raise this by going to **New issue > Feature request** please.
