### ISSUE TITLE
Instructions are unclear when adding integration

### ISSUE THREAD

**Issue by reslip1** [home-assistant/home-assistant.github.io#27002]
### Feedback

Instructions are unclear when adding integration. It asks for host, port, name, and location, but no API key. Whenever I attempt to connect it says unable to connect. 

### URL

https://www.home-assistant.io/integrations/pi_hole/

### Version

2023.4.4

**Comment by SaintPaddy** [comment]
Agreed, instructions [posted](https://www.home-assistant.io/integrations/pi_hole) are not clear. 
What am I supposed to enter for "Host" and "Port" ?
Which DNS name and port I want to run the Admin interface as?
Same goes for "Name" and "Location"...
