### ISSUE TITLE
Powerview Gen3 support

### ISSUE THREAD

**Issue by bg0ldman** [home-assistant/home-assistant.github.io#27003]
### Feedback

I have a Powerview Gen3 hub and am not able to get the integration to work.  It fails when trying to connect to the hub.  Are there any suggestions?

### URL

https://www.home-assistant.io/integrations/hunterdouglas_powerview/

### Version

2023.4.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by kingy444** [comment]
@bg0ldman there is a request for feature support over on the Home Assistant forum you can add to or support - that’s the correct way to request the support for gen3

this is on my radar but have not had much time to commit to this of late with my actual job taking most of my time and unfortunately requires a rewrite of the integration and the upstream api
