### ISSUE TITLE
"Duration info (optional)" in automated trigger

### ISSUE THREAD

**Issue by Melectro1** [home-assistant/home-assistant.github.io#27021]
### Feedback

Please insert text and explain this function incl. example.

### URL

https://www.home-assistant.io/docs/automation/trigger/

### Version

2023.4.4

**Comment by frenck** [comment]
Hi there @Melectro1 👋 

Could you add some more context / explanation? Because, based on the current feedback, I am not able to understand what your suggestion is.

Thanks 👍 

../Frenck

**Comment by Melectro1** [comment]
In both Triggers and Conditions there is a setting called duration. I don't know what effect it has, so it would be nice to get a text that explains the logic.
I'm testing but it doesn't quite work the way I thought it would.
![image](https://user-images.githubusercontent.com/84949550/232359342-fe818740-37d7-4d05-b29b-36782885f287.png)

![image](https://user-images.githubusercontent.com/84949550/232358943-7c615125-bbca-46fc-b2ca-eb177017d2c5.png)

**Comment by dannytsang** [comment]
There is details on the duration on the trigger page [here](https://www.home-assistant.io/docs/automation/trigger/#holding-a-state-or-attribute) with example as well.

The same concept applies to conditions where a state needs to be held for x amount of time to pass. This is not on the [conditions page](https://www.home-assistant.io/docs/automation/condition/) so happy to add if you think this is what's needed?

**Comment by Melectro1** [comment]
@dannytsang

It is not entirely clear either. For those who are new, a description of the "Duration" function is needed in the places where you can set a time. 
I wonder what the difference is between having a "Duration" and setting a wait time in the "Actions".

The answer should appear in the text when you click on the question marks.
