### ISSUE TITLE
Proposed edit to Calendar documentation to include an 2nd example 

### ISSUE THREAD

**Issue by BGFHA** [home-assistant/home-assistant.github.io#27029]
### Feedback

Following the changes to Calendars, to disallow 0 duration events, I found it difficult to find Automation documentation showing how to create an event with a correctly formatted end_date_time equivalent to "now() plus one minute". This example would help.

service: calendar.create_event
target:
  entity_id: calendar.device_automation_schedules
data:
  start_date_time: "{{ now() }}"
  end_date_time: "{{ now() + timedelta(minutes=1) }}"
  summary: "Example"

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2023.4.4

**Comment by jack5mikemotown** [comment]
If you want to propose an edit to the documentation, head in there and do it yourself and submit a pr. More likely to get approved than it is for someone to see this here and decide to go do it

**Comment by BGFHA** [comment]
I made a PR and the additional example has been added.
