### ISSUE TITLE
Error connecting znvoy on vs 7 and above

### ISSUE THREAD

**Issue by PeterDemuynck** [home-assistant/home-assistant.github.io#27034]
### Feedback

In built in version is nit working.  Therefore we had to try five HACS solutions. In contrast of the plug and play thing of course a lig more difficult.
I presume it should work by integrating the new connection? 

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.4.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
