### ISSUE TITLE
Using reverse proxy with ssl

### ISSUE THREAD

**Issue by ShlomiPorush** [home-assistant/home-assistant.github.io#27046]
### Feedback

Hi, I tried to add fully which is behind reverse proxy for example: kiock.domain.com but it doesn't work.
I was only able to add with an IP address and without specifying port 2323 it seems that IP:2323 is hard coded so any order port cant be used. 

https://github.com/home-assistant/core/blob/2ec135906315eb075e0c2dec42e675bc07360862/homeassistant/components/fully_kiosk/entity.py#L26
            configuration_url=f"http://{coordinator.data['ip4']}:2323",

### URL

https://www.home-assistant.io/integrations/fully_kiosk/

### Version

2023.4.5

**Comment by frenck** [comment]
That is correct, it is intended for use with the device, not a reverse proxy. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
