### ISSUE TITLE
what should be entered for host?

### ISSUE THREAD

**Issue by ArtBIT** [home-assistant/home-assistant.github.io#27044]
### Feedback

It is unclear what should be entered for host. None of these work.

- 192.168.87.115:1925
- http://192.168.87.115
- http://192.168.87.115:1925/
- http://192.168.87.115:1925/system

Accessing http://192.168.87.115:1925/system works from browser in my local network

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2023.4.5

**Comment by frenck** [comment]
> It is unclear what should be entered for host. None of these work.

None of those you listed are host addresses. The first one is... dunno? The others are URLs.

A host can be either a hostname address or IP address of the device providing the service (the host).

E.g., `my-tv-hostname.local` or `192.168.2.34` as an IP-address


../Frenck

**Comment by ArtBIT** [comment]
In the docs you mention `http://<tv ip>:9125/system` but that does not work
when entered in the host field.

It is not clear that only a hostname should be entered, without a protocol
or port, please clarify in the docs or in the input field placeholder what
format does it accept.

**Comment by frenck** [comment]
The doc mentions:

![image](https://user-images.githubusercontent.com/195327/232752048-8a4be88b-5198-4042-a6ad-3f45cec1c1fa.png)


Which is an URL, which you can visit to manually check if your TV is suitable for this integration.

> It is not clear that only a hostname should be entered, without a protocol
or port

It asks for host... not protocol, not port, not URL, not for any combined format. Just host.
I don't see how that is ambiguous at all?

> please clarify in the docs or in the input field placeholder what
format does it accept.

It accepts a host... 🤷 I really don't see how that can be clarified. It cannot be more concrete.

../Frenck
