### ISSUE TITLE
max_age without sampling_size behaviour unclear

### ISSUE THREAD

**Issue by grumble0** [home-assistant/home-assistant.github.io#27045]
### Feedback

sampling_size help says "omit if the samples should be driven by max_age instead" implying the sampling_size will be however many samples there are within the max_age timeframe.

The "important note" at the end states "The max_age option is only valid within the measured samples specified by sampling_size (default 20)."  

Does omitting sampling_size set the size to 20 or does it let max_age "drive" the number of samples?

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2023.4.2

**Comment by ThomDietrich** [comment]
Hello,
thanks for pointing out this mistake. The default of 20 was removed half a year ago and its mentioning down there should be removed!

You need to define either or both settings. If only `sampling_size` is given, no time limit is applied, if only `max_age` is given, the considered number of samples is unlimited. In case both settings are given, considered samples are within the the `max_age` time window but limited to the number of `sample_size` newest samples.

Would you like to draft a PR for the relevant change(s)?

**Comment by grumble0** [comment]
PR here: https://github.com/home-assistant/home-assistant.io/pull/27110
