### ISSUE TITLE
Just a big thanks!

### ISSUE THREAD

**Issue by walter-ve** [home-assistant/home-assistant.github.io#27054]
### Feedback

Just a big thanks.  Installed Home Assistant for a first time and there was my device.  I wasn't even thinking about that this device would pop up...
What else can one wish for ;-).

### URL

https://www.home-assistant.io/integrations/aranet/

### Version

2023.4.5

**Comment by walter-ve** [comment]
Of course I close this 'issue' with pleasure ;-)

**Comment by frenck** [comment]
Thanks for the nice words @walter-ve ❤️ 

Hope we can amaze you a couple of times more in your journey 😉 

../Frenck

**Comment by aschmitz** [comment]
Sorry - I hadn't gotten to logging in to GitHub for a while, but on the plus side this made my day twice now! :blush: Glad it's working well for you!
