### ISSUE TITLE
Failed to connect to Enphase IQ Gateway with username/password

### ISSUE THREAD

**Issue by perryvvliet** [home-assistant/home-assistant.github.io#27057]
### Feedback

My Enphase IQ Gateway runs version D7.6.114 (43769e) and I cannot login with a username/password, but needs to go via local API. I have the access token. How do I connect with home assistant using the API?

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.4.5

**Comment by klaasnicolaas** [comment]
Hi there @perryvvliet 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
