### ISSUE TITLE
Failed to connect as of yesterday

### ISSUE THREAD

**Issue by BarryS83** [home-assistant/home-assistant.github.io#27055]
### Feedback

The integration seems to be no longer functioning. It fails to connect. I suspect that Rituals have changed their API.

### URL

https://www.home-assistant.io/integrations/rituals_perfume_genie/

### Version

2023.4.5

**Comment by frenck** [comment]
Hi there @BarryS83 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations in the Core issue tracker.

When in doubt about where to go, please see: https://www.home-assistant.io/help

In this case, this is a known issue, see: https://github.com/home-assistant/core/issue/91623

Thanks 👍 

../Frenck
