### ISSUE TITLE
Rflink group aliases documentation

### ISSUE THREAD

**Issue by aequitas** [home-assistant/home-assistant.github.io#2707]
https://github.com/home-assistant/home-assistant/pull/7577#issuecomment-303866568

**Comment by Landrash** [comment]
No information about what lacking with exception of a link.
Your welcome to add the information your lacking but the link in question is of no help without context.

**Comment by aequitas** [comment]
Sorry, I created it as a todo for myself, should have added more context indeed.

**Comment by Landrash** [comment]
In that case no problem :)
