### ISSUE TITLE
RLN36 Support ?

### ISSUE THREAD

**Issue by bruce607** [home-assistant/home-assistant.github.io#27076]
### Feedback

Any chance of support for the RLN36 NVR ?

Am currently running 

Model      RLN36
build No. 23031612 GA 3.1
Hw No.    N5MB01
Cfg Version v3.0.0.0
Fw Version  v3.3.0.226_23031612

Integration tries to connect but fails.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.4.5

### Additional information

Willing to help troubleshoot... Bought this nvr because it was a good deal & I already had some drives... That being said, we love home assistant & really want the reolink nvr working. so much so that I'll buy the 16 channel model if there are no plans to include support for the 36.

**Comment by starkillerOG** [comment]
@bruce607 First of all, thanks for reporting this issue!
I would not know any reason why the RLN36 NVR, would not work.
That beeing sad, I have only programmed and tested with the RLN8 NVR, and have not gotten comformation from anyone yet that it works with RLN36 NVR, so I think this is a good oppertunity to get it working.

I might need to do some code changes to get it supported, we will see.

First of all, do you see any errors in the log when you try to set it up, and what error does the form show when you try to set it up?
Please post those in this issue.

If it is not a standard error, I will guide you through the steps of making a debug log.

I will be on vacation for a week starting tommorow, so after today I will not be able to respond, but rest assured that I will pick this up after my vacation.

**Comment by starkillerOG** [comment]
If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

PS: @starkillerOG Please close these instead of starting a conversation on them. This is not the right place.

**Comment by starkillerOG** [comment]
@frenck I will do that for future issues.
Is it possible to get notifications when new feature requests are beeing made in the [Community Forum](https://community.home-assistant.io/c/feature-requests) for a specific integration (of which I am code-owner)?
