### ISSUE TITLE
What if you see this issue while running "Home Assistant OS"?

### ISSUE THREAD

**Issue by Jo-Highness** [home-assistant/home-assistant.github.io#27073]
### Feedback

The article states that one should not see this error when running Home Assistant OS. I am running HAOS and still get the error :-(. What can I do?

### URL

https://www.home-assistant.io/more-info/unsupported/cgroup_version/

### Version

2023.4.5

**Comment by frenck** [comment]
You should have that error when running Home Assistant OS, so that would be a bug (as Home Assistant OS is supported).

Please report an issue here:

<https://github.com/home-assistant/supervisor/issues>

Thanks 👍 

../Frenck
