### ISSUE TITLE
Pls add EU-Server

### ISSUE THREAD

**Issue by angewood** [home-assistant/home-assistant.github.io#27080]
### Feedback

Hi, the serveraddress 
https://server-api.growatt.com/
don't work.

Pls add 
http://server.growatt.com/

for EU / Germany

Thx

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.4.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
