### ISSUE TITLE
Does the "restart" automation mode consider automation conditions?

### ISSUE THREAD

**Issue by JacobSnyder** [home-assistant/home-assistant.github.io#27084]
### Feedback

The documentation for the `queued` mode states:

> Start a new run after all previous runs complete. Runs are guaranteed to execute in the order they were queued. Note that subsequent queued automations will only join the queue if any conditions it may have are met at the time it is triggered.

However, the documentation is vague as to how conditions are handled for the `restart` mode.  One would assume that an existing run of an automation would only be interrupted if the incoming trigger satisfies the conditions, but it'd be good for the documentation to explicitly clarify this.  

I'd be happy to submit the PR myself to address this, but I wanted to verify that this is actually the behavior first.

Thank you!

### URL

https://www.home-assistant.io/docs/automation/modes/

### Version

2023.4.5

**Comment by frenck** [comment]
Run modes only apply on when the automation "runs" its script.

From the documentation:

> The automation’s mode configuration option controls what happens when the automation is triggered while the actions are still running from a previous trigger.

Automation only triggers when their condition passes. Otherwise, the trigger is aborted.

../Frenck
