### ISSUE TITLE
Mopeka TD40

### ISSUE THREAD

**Issue by Marpanet** [home-assistant/home-assistant.github.io#27092]
### Feedback

Mopeka has also a Water Level Sensor that works the same way as the gas sensors suported. It would be great if you could add that to the integration. 

### URL

https://www.home-assistant.io/integrations/mopeka/

### Version

2023.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
