### ISSUE TITLE
Energy total from Switchbot Smart Plug Mini?

### ISSUE THREAD

**Issue by kchiem** [home-assistant/home-assistant.github.io#27090]
### Feedback

Hello, the Switchbot app shows an energy total for these plugs.  Can that be made available in HA?

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.4.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
