### ISSUE TITLE
More information required.

### ISSUE THREAD

**Issue by thecreaser** [home-assistant/home-assistant.github.io#27096]
### Feedback

Context for feedback:  I'm considering buying a Sure Petcare cat flap and looking for information.
Suggested improvement.  Page could do with more background information:
Is the Sure Petcare hub required (or is HA providing the service?)
Is a Sure Petcare online account required?

### URL

https://www.home-assistant.io/integrations/surepetcare/

### Version

2023.4.6

**Comment by Laho812** [comment]
> ### Feedback
> 
> Context for feedback: I'm considering buying a Sure Petcare cat flap and looking for information. Suggested improvement. Page could do with more background information: Is the Sure Petcare hub required (or is HA providing the service?) Is a Sure Petcare online account required?
> ### URL
> 
> https://www.home-assistant.io/integrations/surepetcare/
> ### Version
> 
> 2023.4.6
> ### Additional information
> 
> _No response_

Hi,
you need buy the hub and a online account is required. The flap will be controlled via web, not local based.
In HomeAssistant you can set and see the inside/outside value of each pet and you can control the lock state of the flap.
