### ISSUE TITLE
Telldus API

### ISSUE THREAD

**Issue by speedy50098** [home-assistant/home-assistant.github.io#27108]
### Feedback

<p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Kära kund,<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">Tack för att du är en del av Telldus-familjen.<br style="box-sizing: border-box;">Vi har alltid varit stolta över att ha kunnat underhålla och erbjuda tjänster utan kostnad till alla våra kunder. Vi har gjort det i tron på att ett smartare och säkrare hem är ett grundläggande behov för alla, och därför har vi gjort vårt bästa för att kunna erbjuda denna komfort till alla våra de senaste 10+ åren.</p><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Vi har nu kommit till den punkt att det inte håller ekonomiskt längre att kunna utveckla och upprätthålla den funktion, stabiliteten och framtidssäkerhet som krävs, så kan vi inte längre erbjuda tjänster kostnadsfritt.</p><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Det är ett svårt beslut att ta, men vi behöver göra denna förändring för att kunna finnas kvar för er.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">Detta innebär att vi kommer göra en förändring för Basic-användare (gratis-versionen av vår tjänst), Vill man kunna använda Telldus tjänster till fullo behöver välja en Premium-prenumeration.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">Detta innebär att från och med den<span class="Apple-converted-space"> </span><strong style="box-sizing: border-box; font-weight: 400;">24 april 2023</strong>kommer alla Basic-användare fortsätt kunna använda/lägga till nya enheter, kontrollera dem på distans och lokalt. Däremot kommer API-åtkomst och automationer (både Händelser och Scheman) att inaktiveras, och du kommer att bli ombedd att uppgradera till Premium-prenumerationen. Kundsupport kommer även att begränsas till tre ärenden per år.</p><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Om du redan är en premium-användare – Oroa dig inte, denna förändring påverkar inte dig.</p><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Telldus Premium prenumerationen täcker följande:</p><ul style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; list-style: outside none disc; margin: 0px 0px 1em; padding-left: 2em; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;"><li style="box-sizing: border-box;">Övervaka din TellStick och få en notis om den är offline*.</li><li style="box-sizing: border-box; padding-top: 0.25em;">Händelser och Scheman.</li><li style="box-sizing: border-box; padding-top: 0.25em;">IFTTT- integration.</li><li style="box-sizing: border-box; padding-top: 0.25em;">Kortare intervalltid för automationer.</li><li style="box-sizing: border-box; padding-top: 0.25em;">Sensorhistorik.</li><li style="box-sizing: border-box; padding-top: 0.25em;">Stöd för Google Home och Alexa.</li><li style="box-sizing: border-box; padding-top: 0.25em;">Geofence-automationer baserade på din plats.</li><li style="box-sizing: border-box; padding-top: 0.25em;">API-åtkomst.</li><li style="box-sizing: border-box; padding-top: 0.25em;">Medlemsrabatter.</li><li style="box-sizing: border-box; padding-top: 0.25em;">Prioriterad kundsupport.</li></ul><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Telldus Premium prenumeration:</p><div class="wp-block-wmco-row  wp-block-wmco-row--container wp-block-wmco-row--align-col-stretch wp-block-wmco-row--pad-col-1 wp-block-wmco-row--pad-top-1 wp-block-wmco-row--pad-bottom-1" style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; position: relative; padding-top: 12px; padding-bottom: 12px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;"><div class="wp-block-wmco-row__wrapper" style="box-sizing: border-box; position: relative; margin-right: auto; margin-left: auto; padding-left: 16px; padding-right: 16px;"><div class="wp-block-wmco-row__content" style="box-sizing: border-box; display: flex; -webkit-box-lines: multiple; flex-wrap: wrap; align-content: flex-start; -webkit-box-align: stretch; align-items: stretch; margin: -12px;"><div class="wp-block-wmco-column  col-lg-6 col-md-6 col-sm-6 col-xs-12 col-xxs-12" style="box-sizing: border-box; position: relative; min-height: 1px; padding: 12px; float: left; width: 374px; display: block;"><figure class="wp-block-table" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; display: block; overflow-x: auto;">

1 månad | €3/månad
-- | --
6 månader | €2,5/månad
12 månader | €2,1/månad

<figcaption style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; outline: 0px; display: block;">Alla priser inkluderar 25% moms.</figcaption></figure></div><div class="wp-block-wmco-column  col-lg-6 col-md-6 col-sm-6 col-xs-12 col-xxs-12" style="box-sizing: border-box; position: relative; min-height: 1px; padding: 12px; float: left; width: 374px; display: block;"></div></div></div></div><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Prenumerationsintäkterna kommer att ge oss fortsatt möjlighet att upprätthålla vår verksamhet och kundsupport, och även stödja ny produktutveckling, som ny TellStick och avancerade Automationer. </p><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Telldus jobbar hårt för att kunna erbjuda dig kvalitativa hemautomations-tjänster. Vi har ägnat mycket resurser på att förbättra våra backend-system för att göra dem mer pålitliga och framtidssäkra. Dessutom utvecklar vi en ny TellStick som stöder MQTT, Z-Wave och Zigbee som kommer att utöka vårt utbud av prisvärda hemautomations-enheter.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;">Vi värdesätter ditt stöd och ditt förtroende för oss, och hoppas på förståelse och att ni kommer att fortsätta att använda vår plattform.</p><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 0px 0px 13px; caret-color: rgb(10, 10, 10); color: rgb(10, 10, 10); font-family: &quot;Suisse Intl&quot;, sans-serif; font-weight: 300; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); -webkit-text-size-adjust: 100%;">Vi förstår att du kanske har frågor om denna förändring, och du kan alltid kontakta oss. Vi är glada över att kunna svara på eventuella frågor.<br style="box-sizing: border-box;"><br style="box-sizing: border-box;"><br style="box-sizing: border-box;">Vänliga hälsningar,<br style="box-sizing: border-box;">Telldus-Teamet</p>

### URL

https://www.home-assistant.io/integrations/tellduslive/

### Version

2023.4.6

**Comment by fredrike** [comment]
@speedy50098 So, what do you want us to do about that? Perhaps you can contribute with a warning on in the documentation, https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/tellduslive.markdown.

If you have a Znet Lite you can run the mqtt plugin directly on your Znet https://github.com/quazzie/tellstick-plugin-mqtt-hass

**Comment by frenck** [comment]
Closing this feedback, as it is written in a foreign language. 

We only allow the use of the English language in our community, please recreate this feedback as such.

Thanks 👍 

../Frenck
