### ISSUE TITLE
Add additional url link to 

### ISSUE THREAD

**Issue by MeanderingWanderer** [home-assistant/home-assistant.github.io#27106]
### Feedback

_See also:_  [IMAP Integration](https://www.home-assistant.io/integrations/imap/)

It would be very helpful if at the bottom of the imap_email_content integrations page, a See Also link to imap page. https://www.home-assistant.io/integrations/imap/
(Each page contains duplicate information, and merging the pages should also be considered?)

### URL

https://www.home-assistant.io/integrations/imap_email_content/

### Version

2023.4.6

### Additional information

when searching HA imap via google.com, the HA documentation pages are inter-mixed with community posts. 
If you land on the imap_email_content page, the documentation doesn't mention adding/configuring imap integration via the integrations UI.   (i spent a considerable amount of time troubleshooting before I realized the imap server settings can not be set via configuration.yaml and must be set using the integrations UI page)

Many thanks!

**Comment by frenck** [comment]
Thanks for the feedback @MeanderingWanderer 👍 

However, the `imap_email_content` integration is pending deletion, so this problem will resolve itself very soon.

../Frenck
