### ISSUE TITLE
Nice addon - but auto sorting would be nice.

### ISSUE THREAD

**Issue by EasyGoin12000** [home-assistant/home-assistant.github.io#27124]
### Feedback

It would be nice to add an alfa sort ability.  That way the user could use store codes to keep items in the list more organized by the store (for example) or the priority.  Just a thought.

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2023.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
