### ISSUE TITLE
Adding a station doesn't work

### ISSUE THREAD

**Issue by artgru** [home-assistant/home-assistant.github.io#27149]
### Feedback

I'm trying to add a new station  to my HA installation
(https://powietrze.gios.gov.pl/pjp/current/station_details/info/208)
Typing 208 in the dialog returns "Uknown error occured"

### URL

https://www.home-assistant.io/integrations/gios/

### Version

2023.4.6

**Comment by bieniu** [comment]
This is a documentation repository. Please open an issue here https://github.com/home-assistant/core/issues
