### ISSUE TITLE
Reading?

### ISSUE THREAD

**Issue by MortyFleem** [home-assistant/home-assistant.github.io#27152]
### Feedback

What about reading from ThinkSpeak and not just writing to it?

In other words - get data from Thinkspeak into Home Assistant?

Thank you.

### URL

https://www.home-assistant.io/integrations/thingspeak/

### Version

2023.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
