### ISSUE TITLE
[Feedback] Zooz Z-Wave Antenna Documentation Update

### ISSUE THREAD

**Issue by Ryu945** [home-assistant/home-assistant.github.io#27162]
### Feedback

This is for updating this section of the page:

https://www.home-assistant.io/integrations/zwave_js/

`The following devices have been tested with discovery, and offer a quick setup experience; however, these are not all of the devices supported by Z-Wave:`

I have tested the Z-Wave antenna ZST39 LR.  This is the 800 series USB dongle from Zooz.  It works fine  with the docker container with no issues.

Also the setup instructions needs to mention this command as it took quite a while to find how to get the correct name to pass a hardware device to a docker container.

`ls -l /dev/serial/by-id`

It is used to fill out this line in a docker image using docker compose:

`- '/dev/serial/by-id/insert_stick_reference_here:/dev/zwave'`

Or this line if done with terminal:

`--device=/dev/serial/by-id/insert_stick_reference_here:/dev/zwave`

### URL

https://www.home-assistant.io/integrations/zwave_js/

**Comment by mnl1121** [comment]
Thanks for sharing that the 800 series Zooz stick works. I may upgrade sometime in the future.

**Comment by raman325** [comment]
we're not going to add instructions on mapping the stick to a new path in a docker container as that's outside the scope of the integration
