### ISSUE TITLE
Link does not work on year of the voice chapter 2

### ISSUE THREAD

**Issue by crafty184** [home-assistant/home-assistant.github.io#27187]
### Feedback

The link here

If you haven’t done so yet, [expose your devices to Assist](https://next.home-assistant.io/projects/private-voice-assistant/voice_remote_expose_devices/#exposing-your-devices).

Does not work.

It returns "Oh no! This page does not exist 😞"

### URL

https://www.home-assistant.io/docs/assist/voice_remote_local_assistant/

### Version

2023.4.6

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @crafty184 :+1: 
Closed by #27201
