### ISSUE TITLE
Location for the Withings integration configuration

### ISSUE THREAD

**Issue by hughbussell** [home-assistant/home-assistant.github.io#27183]
### Feedback

The document says (https://www.home-assistant.io/integrations/withings#bonus-template-sensors-to-convert-kilograms-to-pounds):
```
In a text editor, replace USER_PROFILE_NAME in the template sensors below with your Withings User Profile Name defined in the Withings integration configuration.
```

I have successfully created the integration, and I can see my data on my dashboard, but I can't seem to find a configuration file for the integration. Probably my fault. 

I poked around for a while and found this file with an entry for Withings, but that's not quite what I want:
`/root/config/.storage/core.config_entries`

Maybe we could add a pointer to where the file is, or maybe have a generic topic on how to find config files?
I feel like once I know where it is, I'll feel silly, but I thought I should raise the issue.

Thanks!

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2023.4.6

**Comment by frenck** [comment]
Withings doesn't have its own configuration file. You can find more information on configuring Home Assistant here:

<https://www.home-assistant.io/docs/configuration/>

../Frenck
