### ISSUE TITLE
RPI imager menu option shown in screenshot not available

### ISSUE THREAD

**Issue by realflash** [home-assistant/home-assistant.github.io#27197]
### Feedback

Installed imager 1.7.4 (latest available). It has no option to select HassOS as shown in the screenshot. Updated instructions are needed.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.4.6

**Comment by dannytsang** [comment]
I can confirm this as well.

I went through the different OS menus and cannot see Home Assistant.

![image](https://user-images.githubusercontent.com/567982/235311707-b05076d7-af32-4369-8601-5cf73d8b981c.png)

**Comment by c0ffeeca7** [comment]
Thank you for reporting this, @realflash!
Could you take a look at the updated instructions and let me know if it works on your system?
https://github.com/home-assistant/home-assistant.io/pull/27361
