### ISSUE TITLE
Request for information on what to put in the Port field when using a serial connection

### ISSUE THREAD

**Issue by domdoran** [home-assistant/home-assistant.github.io#27205]
### Feedback

It's unclear what to put into the Port field when using a usb to serial adapter.

### URL

https://www.home-assistant.io/integrations/monoprice/

### Version

2023.4.6

**Comment by OnFreund** [comment]
You can find guidance here: https://pyserial.readthedocs.io/en/latest/url_handlers.html

A github issue is not the right medium for this - please use the community forums or discord.

**Comment by OnFreund** [comment]
@home-assistant close
