### ISSUE TITLE
documentation not clear

### ISSUE THREAD

**Issue by neottil** [home-assistant/home-assistant.github.io#27213]
### Feedback

In the System Health integration page is no clear what is the provided API for the health check. What is the endpoint?

### URL

https://www.home-assistant.io/integrations/system_health/

### Version

2023.4.6

**Comment by frenck** [comment]
> no clear what is the provided API for the health check. What is the endpoint?

None. Hence none documented.

It is an internal component, for which other integration can provide data (if they want/can).

../Frenck
