### ISSUE TITLE
Process script output

### ISSUE THREAD

**Issue by aik** [home-assistant/home-assistant.github.io#27219]
### Feedback

Is there a way to assign the script's output (say, an URL) to a variable in HA for later use in let's say notifications?

### URL

https://www.home-assistant.io/integrations/shell_command/

### Version

2023.4.6

**Comment by frenck** [comment]
No, that is not possible. Output is only logged.

**Comment by ccdunder** [comment]
Output can be sent back to home assistant: https://community.home-assistant.io/t/return-shell-command-output-to-caller/477632

This would be useful to include in this documentation IMHO.
