### ISSUE TITLE
INKBIRD Smart Sprinkler Controller IIC-600-WIFI and Smart Sprinkler Controller IIC-800-WIFI

### ISSUE THREAD

**Issue by Dgigie** [home-assistant/home-assistant.github.io#27220]
### Feedback

Hello,
 Would it be possible to integrate this equipment and by the way a big thank you to the whole team and to all the participants !!!

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2023.4.6

### Additional information

https://inkbird.com/products/smart-sprinkler-controller-iic-600-wifi

**Comment by purpleraven** [comment]
I'm also interested in integration of that controller to ha

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
