### ISSUE TITLE
adding entity for a relay for HomeKit 

### ISSUE THREAD

**Issue by nisnu** [home-assistant/home-assistant.github.io#27235]
### Feedback

Thanks for the documentation.
I am not sure how I can add a entity for the status of one of the two relais. Specifically I want to add a device in HomeKit that indicates when the door opener (relay 2) has been activated. Without further configuration I have that relay available as entity in HA, but it is not changing the status when it got activated physically. So I guess some configuration is needed. It would be excellent if this could be added to the documentation with a small example.

### URL

https://www.home-assistant.io/integrations/doorbird/

### Version

2023.4.6

**Comment by disyn** [comment]
Also waiting for the solution as i’m in the same position
