### ISSUE TITLE
Integration broken?

### ISSUE THREAD

**Issue by bloemkool001** [home-assistant/home-assistant.github.io#27237]
### Feedback

The integration broke down as of today?

Client error '401 Unauthorized' for url 'https://customer.bmwgroup.com/gcdm/oauth/authenticate' For more information check: https://httpstatuses.com/401

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2023.4.6

**Comment by frenck** [comment]
Hi there @bloemkool001 👋 

It seems like you want to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
