### ISSUE TITLE
browser_mod popup and alarm keyboard

### ISSUE THREAD

**Issue by DAMIGUI** [home-assistant/home-assistant.github.io#27231]
### Feedback

Hello, I'm trying to use alarm-control-panel into a browser_mod popup.
The pop up works well but it's impossible to display the alarm keyboard there.

Can someone help me please?
My code is just bellow.

Many thanks

### URL

https://www.home-assistant.io/dashboards/alarm-panel/

### Version

2023.4.6

### Additional information

action: fire-dom-event
browser_mod:
  service: browser_mod.popup
  data:
    title: Alarme
    card_mod:
      style:
        #popup header
        .:
        height: 100%
    content:
      - type: custom:mushroom-alarm-control-panel-card
        entity: alarm_control_panel.alarmo
        states:
          - armed_home
          - armed_away
        name: Alarme
        fill_container: false
        show_keypad: true

**Comment by frenck** [comment]
`browser_mod` is a third-party card/plugin for Home Assistant, not supported by the Home Assistant project.

../Frenck
