### ISSUE TITLE
System Pressure Entity

### ISSUE THREAD

**Issue by Triggs88** [home-assistant/home-assistant.github.io#27245]
### Feedback

For the Viessmann home assistant integration, it would be really good if the system pressure sensor be added as an entity that is viewable.

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2023.4.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
