### ISSUE TITLE
M5stack ATOM ECHO is nice, but... not available...

### ISSUE THREAD

**Issue by HWiese1980** [home-assistant/home-assistant.github.io#27250]
### Feedback

I suggest you seek out alternatives to the M5stack ATOM ECHO as it does not seem available at present. It's out of stock almost everywhere. 

### URL

https://www.home-assistant.io/projects/thirteen-usd-voice-remote/

### Version

2023.5.0

**Comment by frenck** [comment]
That is unfortunate, it seems like they sold out quickly with the recent announcements.

Many, many stores sell them (I bought one locally myself). We just link the manufacturer.

../Frenck
