### ISSUE TITLE
Which host and port for configuration

### ISSUE THREAD

**Issue by Pittermaennchen** [home-assistant/home-assistant.github.io#27252]
### Feedback

When installing this Addon, I get the question which host and wich port? What should I enter there?

It would be good to enter this in the manual.

### URL

https://www.home-assistant.io/integrations/wyoming/

### Version

2023.5.0

**Comment by frenck** [comment]
For the add-on you don’t need to enter anything, it should be automatically discovered.

This is documented in the add-on documentation.

Which addon are you trying to use?

**Comment by rehanson** [comment]
This is the dialogue box that pops up when I try to install the Wyoming integration. I don't know what to enter for the host and port.

![image](https://user-images.githubusercontent.com/4173375/236072115-a45a4720-4f50-489a-88da-d3f4d62f2a6c.png)

**Comment by rehanson** [comment]
I figured it out. I had installed the Piper and Whisper add-ons, but I hadn't started them yet. I had to go into the Add-ons menu and click Start for both of them. After that, they showed up as "Discovered" in the Integrations menu.

**Comment by Pittermaennchen** [comment]
The same for me. So it is solved. Thank you @frenck !

But still: maybe there would be a hint helpful when clicking on the question mark in the dialogue box?

Something like: "you do not need to configure it here. Install the addons Piper and Whisper first, then go to integrations? Both will automatically discovered?"

**Comment by carlesfernandez** [comment]
My five cents:

If you install Piper and Whisper as docker containers, you need to set the `Host` to the IP of the machine running the container, and then `Port` to 10200 (or whatever you have set for Piper) to add Piper. Then repeat the operation but setting `Port` to 10300 for Whisper.  Mine looks like this:

<img width="280" alt="Captura de pantalla 2023-05-04 a las 13 52 32" src="https://user-images.githubusercontent.com/4881484/236196182-66b98537-d815-482f-8b17-23eca8dacbc3.png">

**Comment by TomHutter** [comment]
@carlesfernandez 

Thank, this helped me more than: "For the add-on you don’t need to enter anything, it should be automatically discovered." ;-)
