### ISSUE TITLE
AJax alarm becomes unavailable in 2023.5

### ISSUE THREAD

**Issue by aperezva** [home-assistant/home-assistant.github.io#27258]
### Feedback

After upgrade to 2023.5 my alarm becomes unavailable after minutes. 

I have restored last backup and in 2023.4.x is working fine. 

Any change or bug?

### URL

https://www.home-assistant.io/integrations/sia/

### Version

2023.5.0

**Comment by eavanvalkenburg** [comment]
Please add logs because otherwise I can't say anything...

**Comment by aperezva** [comment]
Hi

updated again to 2023.5 and as you see this are the logs with errors.
Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 09:39:13 (12 occurrences)
Last logged: 09:41:13

Exception in async_handle_event when dispatching 'sia_event_4040_0327EC': (SIAEvent(full_message='"SIA-DCS"0551L0#0327EC[#0327EC|Nri0/RP0000]_07:39:13,05-04-2023', msg_crc='D75B', length='003F', encrypted=False, message_type=<MessageTypes.SIADCS: 'SIA-DCS'>, receiver=None, line='L0', account='0327EC', sequence='0551', content='#0327EC|Nri0/RP0000]_07:39:13,05-04-2023', encrypted_content=None, ti=None, id=None, ri='0', code='RP', message='0000', x_data=None, timestamp=datetime.datetime(2023, 5, 4, 7, 39, 13, tzinfo=datetime.timezone.utc), event_qualifier=None, event_type=None, partition=None, calc_crc='D75B', extended_data=None),) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sia/sia_entity_base.py", line 132, in async_handle_event relevant_event = self.update_state(sia_event) File "/usr/src/homeassistant/homeassistant/components/sia/alarm_control_panel.py", line 126, in update_state new_state = self.entity_description.code_consequences[sia_event.code] KeyError: 'RP'
Exception in async_handle_event when dispatching 'sia_event_4040_0327EC': (SIAEvent(full_message='"SIA-DCS"0552L0#0327EC[#0327EC|Nri0/RP0000]_07:40:13,05-04-2023', msg_crc='35B7', length='003F', encrypted=False, message_type=<MessageTypes.SIADCS: 'SIA-DCS'>, receiver=None, line='L0', account='0327EC', sequence='0552', content='#0327EC|Nri0/RP0000]_07:40:13,05-04-2023', encrypted_content=None, ti=None, id=None, ri='0', code='RP', message='0000', x_data=None, timestamp=datetime.datetime(2023, 5, 4, 7, 40, 13, tzinfo=datetime.timezone.utc), event_qualifier=None, event_type=None, partition=None, calc_crc='35B7', extended_data=None),) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sia/sia_entity_base.py", line 132, in async_handle_event relevant_event = self.update_state(sia_event) File "/usr/src/homeassistant/homeassistant/components/sia/binary_sensor.py", line 135, in update_state new_state = self.entity_description.code_consequences[sia_event.code] KeyError: 'RP'
Exception in async_handle_event when dispatching 'sia_event_4040_0327EC': (SIAEvent(full_message='"SIA-DCS"0552L0#0327EC[#0327EC|Nri0/RP0000]_07:40:13,05-04-2023', msg_crc='35B7', length='003F', encrypted=False, message_type=<MessageTypes.SIADCS: 'SIA-DCS'>, receiver=None, line='L0', account='0327EC', sequence='0552', content='#0327EC|Nri0/RP0000]_07:40:13,05-04-2023', encrypted_content=None, ti=None, id=None, ri='0', code='RP', message='0000', x_data=None, timestamp=datetime.datetime(2023, 5, 4, 7, 40, 13, tzinfo=datetime.timezone.utc), event_qualifier=None, event_type=None, partition=None, calc_crc='35B7', extended_data=None),) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sia/sia_entity_base.py", line 132, in async_handle_event relevant_event = self.update_state(sia_event) File "/usr/src/homeassistant/homeassistant/components/sia/alarm_control_panel.py", line 126, in update_state new_state = self.entity_description.code_consequences[sia_event.code] KeyError: 'RP'
Exception in async_handle_event when dispatching 'sia_event_4040_0327EC': (SIAEvent(full_message='"SIA-DCS"0553L0#0327EC[#0327EC|Nri0/RP0000]_07:41:13,05-04-2023', msg_crc='B8AA', length='003F', encrypted=False, message_type=<MessageTypes.SIADCS: 'SIA-DCS'>, receiver=None, line='L0', account='0327EC', sequence='0553', content='#0327EC|Nri0/RP0000]_07:41:13,05-04-2023', encrypted_content=None, ti=None, id=None, ri='0', code='RP', message='0000', x_data=None, timestamp=datetime.datetime(2023, 5, 4, 7, 41, 13, tzinfo=datetime.timezone.utc), event_qualifier=None, event_type=None, partition=None, calc_crc='B8AA', extended_data=None),) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sia/sia_entity_base.py", line 132, in async_handle_event relevant_event = self.update_state(sia_event) File "/usr/src/homeassistant/homeassistant/components/sia/binary_sensor.py", line 135, in update_state new_state = self.entity_description.code_consequences[sia_event.code] KeyError: 'RP'
Exception in async_handle_event when dispatching 'sia_event_4040_0327EC': (SIAEvent(full_message='"SIA-DCS"0553L0#0327EC[#0327EC|Nri0/RP0000]_07:41:13,05-04-2023', msg_crc='B8AA', length='003F', encrypted=False, message_type=<MessageTypes.SIADCS: 'SIA-DCS'>, receiver=None, line='L0', account='0327EC', sequence='0553', content='#0327EC|Nri0/RP0000]_07:41:13,05-04-2023', encrypted_content=None, ti=None, id=None, ri='0', code='RP', message='0000', x_data=None, timestamp=datetime.datetime(2023, 5, 4, 7, 41, 13, tzinfo=datetime.timezone.utc), event_qualifier=None, event_type=None, partition=None, calc_crc='B8AA', extended_data=None),) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/sia/sia_entity_base.py", line 132, in async_handle_event relevant_event = self.update_state(sia_event) File "/usr/src/homeassistant/homeassistant/components/sia/alarm_control_panel.py", line 126, in update_state new_state = self.entity_description.code_consequences[sia_event.code] KeyError: 'RP'

**Comment by aperezva** [comment]
It seems problemas with RP status , 

You have another exemple in this link with another user
(https://github.com/home-assistant/core/issues/92442)

**Comment by eavanvalkenburg** [comment]
I already put in a fix.

**Comment by aperezva** [comment]
How can I fix it?

And thanks a lot for your time

**Comment by DaN66O** [comment]
After update home assistant  to 2023.5.1, SIA  integration still doesn't work

**Comment by eavanvalkenburg** [comment]
fix is in [#92469](https://github.com/home-assistant/core/pull/92469), should come 5.2.

**Comment by adrz95** [comment]
Still not working on my side. More info [here ](https://github.com/home-assistant/core/issues/92489)

**Comment by frenck** [comment]
Hi there @aperezva @adrz95 👋 

It seems like you wanted report an issue, however, please note: You've submitted documentation feedback instead. There is no amount of documentation that can be adjusted to fix an bug.

That said, in this case, the issue has been fixed in [#92469](https://github.com/home-assistant/core/pull/92469), which is pending for the Home Assistant Core 2023.5.2 release.

Once that version is available, please update your system and the issue should be solved. If it remains a problem after that, please open an nieuw issue in our Core issue tracker to be found here:

<https://github.com/home-assistant/core/issues>

In the mean time, I'll go ahead and close the issue on this end.

Thanks 👍 

../Frenck
