### ISSUE TITLE
Great, an Intergration for HW you can't buy (all out of stock)

### ISSUE THREAD

**Issue by robertfgoodworth** [home-assistant/home-assistant.github.io#27251]
### Feedback

Great, an Intergration for HW you can't buy (all out of stock), is there other HW that will work we can buy?

### URL

https://www.home-assistant.io/projects/thirteen-usd-voice-remote/

### Version

2023.5.0

**Comment by frenck** [comment]
That is unfortunate, it seems like they sold out quickly with the recent announcements.

Many, many stores sell them (I bought one locally myself). We just link the manufacturer.

../Frenck

**Comment by FredericESH** [comment]
It's impossible to find it. They are out of stock everywhere. Some website announce ... October.

**Comment by robertfgoodworth** [comment]
Please advise, "is there other HW that will work with assist we can buy? I found a few more expensive Atom5 dev kits but I don't know the HW requirements like type of mic & speaker.
