### ISSUE TITLE
Microphone?

### ISSUE THREAD

**Issue by cowboysdude** [home-assistant/home-assistant.github.io#27265]
### Feedback

The section also needs to cover how to actually install a microphone... 
After searching the internet, the docs, the forum.... there is little to NO information.
So having this assistant is not a good thing because many of us do NOT want to use alexa or google device.

### URL

https://www.home-assistant.io/docs/assist/

### Version

2023.5.0

**Comment by frenck** [comment]
This under development and not there yet. This is Home Assistant year of the voice. I recommend reading the latest blogs for the updates.

please note, Assist isn’t voice only.
