### ISSUE TITLE
Custom Ecowitt integration is broken, but not mentioned in full log.

### ISSUE THREAD

**Issue by bitlisz1** [home-assistant/home-assistant.github.io#27261]
### Feedback

Custom Ecowitt integration is clearly broken, but not mentioned in full log.

### URL

https://www.home-assistant.io/changelogs/core-2023.5/

### Version

2023.5.0

**Comment by frenck** [comment]
Custom integrations are not supported or maintained by the Home Assistant project.

Please report issues with the custom integration author instead.

../Frenck
