### ISSUE TITLE
I'm considering buying it one of the Atom Voice assistant kits.  But...

### ISSUE THREAD

**Issue by Doni49** [home-assistant/home-assistant.github.io#27266]
### Feedback

.....I realize that right now, wake words aren't possible and the only way to use this feature is to press the button.

But when wake words are added, will the Atom still work?

### URL

https://www.home-assistant.io/projects/thirteen-usd-voice-remote/

### Version

2023.5.0

**Comment by frenck** [comment]
> But when wake words are added, will the Atom still work?

Unlikely, as it has almost processing power. If you have general questions, please use our community forums.

../Frenck
