### ISSUE TITLE
More Examples to open Apps

### ISSUE THREAD

**Issue by DravenSA** [home-assistant/home-assistant.github.io#27267]
### Feedback

Love this new integration, and the 4 examples that were given are great, Netflix, Disney+, Prime and Youtube, but not all apps work like that, 
2 i know i want to refer to is Plex and NBA
Is there maybe a way that we can "learn" what  "Activity ID or Activity Name to start." or how we can find out what to use in that section when adding a app to launch?
Spent the last few hours trying several options and the result is a message on my android TV that says "you don't have an app that can do this"
Any insight is much appreciated.

### URL

https://www.home-assistant.io/integrations/androidtv_remote/

### Version

2023.5.0

**Comment by PhillySports** [comment]
Second! This is great have the D-pad and the 4 "suggested" apps up and running, but would love to learn how to set up other apps as well!

**Comment by tronikos** [comment]
I started a Guide/wiki at https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921
I also have a PR to link to it in the documentation.

**Comment by Xa4-J** [comment]
Can't find my device, even if I manually enter the IP address. Philips 55POS901F (AndroidTV)

**Comment by DravenSA** [comment]
still cant find the NBA one

https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921/4?u=dravensa

EDIT: I worked it out, Here is how i did it

https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921/13?u=dravensa
