### ISSUE TITLE
pvpc

### ISSUE THREAD

**Issue by Santos-m** [home-assistant/home-assistant.github.io#27276]
### Feedback

As of version 2023.5.de home assistant no longer supports the integration
Este error se originó a partir de una integración personalizada.

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2023.5.1

### Additional information

Logger: homeassistant.config_entries
Source: custom_components/pvpc_hourly_pricing/__init__.py:102
Integration: Spain electricity hourly pricing (PVPC)
First occurred: 08:48:29 (3 occurrences)
Last logged: 14:39:14

Error setting up entry PVPC for pvpc_hourly_pricing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pvpc_hourly_pricing/__init__.py", line 102, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by emilianogetino** [comment]
The same happens to me

**Comment by joanpere1965** [comment]
El mismo problema

**Comment by frenck** [comment]
> Source: custom_components/pvpc_hourly_pricing/init.py:102

☝️ You are running pvpc as a custom integration (hence `custom_components`). Custom integrations are not supported by the Home Assistant project.

Please report the issue with the custom integration author.

Closing the issue on this end.

../Frenck
