### ISSUE TITLE
media_source

### ISSUE THREAD

**Issue by narrcom** [home-assistant/home-assistant.github.io#27271]
### Feedback

please indicate that media_source: or default_config: are required in your configuration.yaml file a full reboot will be required if you add them. it solves the following errors.
Unexpected error during text to speech (tts-failed)
or
Media Source not loaded

### URL

https://www.home-assistant.io/integrations/wyoming/

### Version

2023.5.1

**Comment by frenck** [comment]
I cannot find any dependencies on `media_source` in the Wyoming integration.

![image](https://user-images.githubusercontent.com/195327/236675400-bd389ec1-17cb-49d8-988c-174735174cf9.png)

This might be related to the media player you are sending data too?
It doesn't look like a Wyoming limitation.

If you think it is a bug with the media player you are using, please report an issue here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by narrcom** [comment]
My mistake, after further research I believe `media_source` is required for the `tts` to play local audio files. as stated here.
[media_source](https://www.home-assistant.io/integrations/media_source/)
