### ISSUE TITLE
Roborock Integration Local / Cloud Clarity

### ISSUE THREAD

**Issue by jspanitz** [home-assistant/home-assistant.github.io#27270]
### Feedback

It's unclear if this integration requires cloud services after the initial setup.  This should be spelled out. IoT class tagged as "Local Polling" which seems clear to some extent.  

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.5.1

**Comment by frenck** [comment]
> This should be spelled out. 

It is spelled out, it is local polling. You can click on it even to get more information about it.

../Frenck

**Comment by jspanitz** [comment]
Obviously it's not spelled out if I submitted the issue. Especially when you look at the Xiaomi integration details.  Just trying to help novice users, but hey, thanks for looking I guess.

**Comment by frenck** [comment]
We added this not to have to address it in each integration documentation repeatedly. 

Additionally, we also label cloud-based integrations in Home Assistant itself (you'll notice when the cloud icon when adding integrations and the cloud icons on the integration cards).

Was the linked documentation to "Local polling" not clear?

../Frenck

**Comment by jspanitz** [comment]
Appreciate you sticking with me here.  Not sure if we're looking at this the same way.

I'm 100% with you the local polling icon / linked description is very clear in that cloud is not needed for device polling.  My only suggestion was to add a line in the description that said something along the lines of:

"In contrast to [Xiaomi Miio](https://www.home-assistant.io/integrations/xiaomi_miio/) integration, this integration provides more complete support but requires cloud access **_during the initial set up_** and device configuration is done using the Roborock app."

**Comment by frenck** [comment]
That line is currently pending complete removal in a PR.
