### ISSUE TITLE
Path have to match WHAT exactly

### ISSUE THREAD

**Issue by omayhemo** [home-assistant/home-assistant.github.io#27278]
### Feedback

![image](https://user-images.githubusercontent.com/2934415/236462890-9282f6d4-e125-4746-a07d-6b52eab6475b.png)

These instructions are not intuitive.

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2023.5.1

**Comment by HGupta2018** [comment]
I agree.  these instructions don't make sense and the ecowitt integration picks my wrong home assistant instance and doesn't let me change it.  Is there no way to adjust the IP/hostname that the integration selects?
