### ISSUE TITLE
Missing lot of condition into the documentation

### ISSUE THREAD

**Issue by ceinmart** [home-assistant/home-assistant.github.io#27282]
### Feedback

The condition for device , there is no documentation. 
Where I'm trying to identify when the device_id is required... 

### URL

https://www.home-assistant.io/docs/scripts/conditions/

### Version

2023.5.1

**Comment by dannytsang** [comment]
I can't find references to device ID on the page. Could you be more specific on the documentation where it's got *device_id* or explain what you are trying to do please?
