### ISSUE TITLE
Si conversion error

### ISSUE THREAD

**Issue by jonbosche** [home-assistant/home-assistant.github.io#27288]
### Feedback

Output of the Radon readings is off by three orders of magnitude.
Recommend either changing the units to mBq/M^3 on the sensor.py file or keeping the units but dividing the output from the API call by 1000 then displaying the data.

for context - the actionable level in the united states is 4 pCi/L or approximately .15 Bq. My first reading was 18 Bq off of a .5 pCi/L reading on the device.

### URL

https://www.home-assistant.io/integrations/airthings/

### Version

2023.5.2

**Comment by frenck** [comment]
Hi there @jonbosche 👋 

It seems like you want to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
