### ISSUE TITLE
Notify.Events Integration does not install for first time on HA 2023.4.6

### ISSUE THREAD

**Issue by wes-warner** [home-assistant/home-assistant.github.io#27287]
### Feedback

Installed in configuration.yaml per install doc, restarted  HA, no errors logged at default log level.  Using Developers Tools saw that notify.events not a choice.  Types it in anyway and got  "unable to find notify.events" error.

Perhaps it installed ok to an earlier release and stays but the path for a new install was recently broken, and not reported yet as usage is low?

### URL

https://www.home-assistant.io/integrations/notify_events/

### Version

2023.5.1

**Comment by papajojo** [comment]
Hello @wes-warner,

Thanks four your report! Our team will check this problem and I'll get back to you 😉

**Comment by papajojo** [comment]
@wes-warner could you please share your configuration.yaml (at least **notify_events:** and **notify:** sections) to support@notify.events so we could check that configuration is correct?
