### ISSUE TITLE
Rasberry Pi image per instructions. Does not seem to work :)

### ISSUE THREAD

**Issue by pinnace0** [home-assistant/home-assistant.github.io#27284]
### Feedback

When I try to use the preferred system installation of home assistant using the suggested site: 

"https://www.raspberrypi.com/software/"

The Rasberry imager installs and appears to start normally. However, the Home Assistant operating system is not available to download.  it just is not there among the available operating systems offered by the Raspberry site. 

I tried  the alternative Balena Etcher, it did not work as. Balena was able to find the image and start the flash. it stopped soon thereafter and provided a humongus set of errors

Please advise

Craig

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.54

### Additional information

I have used the Balena Etcher to make  HA images for awhile. This is my first issue. My existing HA system is corrupted. 

I followed backup rules and  I have a backup. 

All I need to do is burn an image. 

Please help

**Comment by dannytsang** [comment]
The Raspberry Pi imager has been reported in #27197. A potentail workaround would be to download the Raspberry Pi image from the [Balena Etcher section](https://www.home-assistant.io/installation/raspberrypi#writing-the-image-with-balena-etcher), uncompress the file so it should go from .xz to .img and use the Raspberry Pi Imager and flash the SD Card using the uncompressed .img file.

Can you provide details of the error you are encounting with Balena Etcher please like what's the error message and a screenshot would be preferable.

**Comment by pinnace0** [comment]
Thanks  for pointing out the Rasberry PI imager  an issue. 

Balena Etcher Pics.

1st screen shows the selected Home Assistant image.
2nd screen shows the start of the error message.
3rd screen is my guest at the failure.


![Balena Error 0](https://user-images.githubusercontent.com/62956782/236591561-d8821e82-77b8-4c99-9b21-e8eb56e9ba3c.jpg)
![Balena Error 1](https://user-images.githubusercontent.com/62956782/236591562-9f7770b0-6b66-4fda-bca1-87dfded19e1a.jpg)
![Balena Error 2](https://user-images.githubusercontent.com/62956782/236591563-c31a8313-bc57-4fe3-af20-cca2709050e1.jpg)

**Comment by pinnace0** [comment]
Thanks for the workround idea. I was able to burn the image onto SD.  I will mark this one as closed an solved as the underlying issue is already being tracked.

BTW, I read your posts on Input Booleans. They were very helpful as well

**Comment by c0ffeeca7** [comment]
Hopefully, rpi works for you now.
About the Balena Ether issue: There is now an issue open for the latest version (v1.18).: https://github.com/balena-io/etcher/issues/4064.
For me, version 1.10.4 works on Ubuntu: https://github.com/balena-io/etcher/releases/tag/v1.10.4

**Comment by pinnace0** [comment]
Thanks for fixing Balena. It was my goto methodology.  I twiddle with and break home assistant frequently. Restore is a frequent occurrence
