### ISSUE TITLE
Help with Cisco SPA112

### ISSUE THREAD

**Issue by pumatrax** [home-assistant/home-assistant.github.io#27296]
### Feedback

Hi, I am trying to get the Voice over IP working with a Cisco SPA112. Basically I am tying to do the same with putting the direct IP call in the dialplan for a autodial solution.  When I take the phone off hook and it tried to connect I get a fast busy but the integration does see the inbound call and sets up the voice over IP integration I added so I know the device is talking to HA. 

I turned on debugging and went into HA core logs but dont see much so I can determine why the call is not completing successfully.

Any help would be greatly appreciated. 
![IMG_6332](https://user-images.githubusercontent.com/20867218/236636512-4bf65402-ac7f-4a7b-a583-47701f96158c.jpg)
![IMG_6333](https://user-images.githubusercontent.com/20867218/236636515-d54ee996-ecd2-4018-a1dd-b43119c631fd.jpg)

### URL

https://www.home-assistant.io/integrations/voip/

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by pumatrax** [comment]
Thank you, will do!
