### ISSUE TITLE
Additional model support

### ISSUE THREAD

**Issue by chrismaki** [home-assistant/home-assistant.github.io#27292]
### Feedback

I was able to pick up the Grandstream HT802 yesterday which is the same has the HT801 but with an additional FXS port. I'm sure you can guess that it works fine as well if you wished to add it as a "known working" model.

### URL

https://www.home-assistant.io/integrations/voip/

### Version

2023.5.1

**Comment by frenck** [comment]
I think that is fine, as a matter of fact, the author of the integration used the HT802 during development.

Will open a PR to adjust the docs on this.

../Frenck
