### ISSUE TITLE
Where is it says it support only english language?

### ISSUE THREAD

**Issue by emonfejm** [home-assistant/home-assistant.github.io#27297]
### Feedback

Where is it says it support only english language?
 Whisper or the Piper add-on
### URL

https://www.home-assistant.io/docs/assist/voice_remote_local_assistant/

### Version

latest 

### Additional information

no

**Comment by frenck** [comment]
> Where is it says it support only english language?

Nowhere, as they both support many languages. For more information, check out the add-on documentation of each of those add-ons.

../Frenck

**Comment by emonfejm** [comment]
> > Where is it says it support only english language?
> 
> Nowhere, as they both support many languages. For more information, check out the add-on documentation of each of those add-ons.
> 
> ../Frenck

Are you sure?! 
https://github.com/home-assistant/core/issues/92655

**Comment by jaymunro** [comment]
Hi @frenck 
We’ve been trying to get your attention on #92655. It seems there is a bug in Whisper that is restricting the language selectable to just one, English by default.

**Comment by ronmichel** [comment]
> 

Dear @frenck: There seems to be an issue with Whisper or Wyoming TTS in general. Please have a look at https://github.com/home-assistant/core/issues/92655

**Comment by frenck** [comment]
This is not the right place for issues on integrations, nor will pinging me have any effect. Please follow the linked issue for updates, or, feel free to contribute fixes for issue to the upstream repositories.

../Frenck
