### ISSUE TITLE
Path has to match

### ISSUE THREAD

**Issue by Girbie** [home-assistant/home-assistant.github.io#27303]
### Feedback

Which path has to match with what?

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2023.5.2

**Comment by feardriven** [comment]
Hey! 

If you include the integration, then you have already "configured" an Ecowitt device without realizing it. Simply press "Add entry" again, then you will be presented with the name and path. After that you can remove the first "Ecowitt" device.

Contrary to what the instructions say, I had to leave the / at the front and not do it at the back. So copy/paste exactly as it is displayed in the configuration.

/api/webhook/##GUID##

<img width="1034" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/81412138/cea24b98-4567-49b6-ba2a-38fcb50603e1">

**Comment by JasonBSteele** [comment]
Thanks for this, just to add that after clicking ADD ENTRY, you will be shown a empty dialog box that you then need to click SUBMIT on, and _then_ you will be shown what needs to go in the Server IP, Port and Path parameters in the Ecowitt/Misol web app.

**Comment by JasonBSteele** [comment]
@pvizeli , can the text be updated with feardriven's response? The reference to the Path is very confusing.

**Comment by JasonBSteele** [comment]
@pvizeli , the text referred to in this issue is:

5. Path has to match! If using the Ecowitt App, remove the first forward slash from the API token, as the app will prepend one.

It is not clear when following these instructions what Path is being referred to.

@feardriven points out that you have to press Add Entry again,

**Comment by Xrlwyzz** [comment]
I am having the same issue. After clicking "add entry (and also when configunring the integration for the first time), I see this informational text - which by the way seems to be outdated. In the WS View app, I could not find the "next" button, nor the screen "customized". But I managed to change the settings in the web interface of my GW1100:
![image](https://github.com/home-assistant/home-assistant.io/assets/93951207/1bf4f610-0890-47e1-8ec0-496d1d9bffc4)
After clicking "Submit", this is all I get:
![image](https://github.com/home-assistant/home-assistant.io/assets/93951207/d6ea4ae0-9b24-4731-8c3a-e98dbe7a714f)
There is no path shown. Leaving the default path in the app or configuration webpage does not seem to work. No sensors are being added to Home Assistant, even after waiting a few minutes.
In the Ecowitt configuration I tried both the default port 80 (of course in use on Home Assistant) and the recommended 4199 (not in use). Nothing seems to work.

**Comment by Meyer3** [comment]
The instructions seem to be from an older version of the integration. (Maybe even not the newer core variant, but an earlier HACS install? Recommending Port 4199 may indicate that. For me port 8123 works fine.) 

Try to completely uninstall the integration by deleting all Integration Entries, then restart HA. 

You need the path to be shown during installation as it includes the toke from HA.
Setting the path for me works much better when using the Ecowitt web interface (calling its IP address) than the apps.

**Comment by snotiger** [comment]
> You need the path to be shown during installation as it includes the toke from HA. Setting the path for me works much better when using the Ecowitt web interface (calling its IP address) than the apps.
@Meyer3 could you please explain what you mean by the last sentence. Which web interface, and what does "works much better" mean?

**Comment by Meyer3** [comment]
My Ecowitt GW1100 gets his IP address from my router. When I type this address (192.168.178.**) into my browser it opens a login page for the device.
![image](https://github.com/home-assistant/home-assistant.io/assets/87723174/7cc6b123-bd6b-4ea9-9389-84e740e8e18c)
When I log in it shows a web page with live data and several options.
![image](https://github.com/home-assistant/home-assistant.io/assets/87723174/9a449fa0-268f-4b59-abe0-a769fb38e589)

Under 'Weather Services', Customized I can configure the connection to HA. For me this worked. Same procedure in app did not work.
![image](https://github.com/home-assistant/home-assistant.io/assets/87723174/cbcbf848-2c37-4c17-87f7-82da2a64cb98)

**Comment by snotiger** [comment]
@Meyer3 thank you, this is very helpful. I don't see the path/token during installation, I see the same screen as @Xrlwyzz , would you be so kind as to show me where you got the integration from? I just searched in settings > Integrations > ecowitt and added it that way, and got the identical screen as Xrlwyzz above. 
Another interesting data point, I setup debugging and in the logs I see the following:
2024-01-30 10:04:20.953 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyecowitt/ecowitt.py", line 329, in listen
    await self.site.start()

**Comment by snotiger** [comment]
@Meyer3 never mind :) I figured it out , you were right the first time. I had added it via HACS and had to remove it and add the official one from https://www.home-assistant.io/integrations/ecowitt , all good now. Thank you for the help!
