### ISSUE TITLE
Error logged re Insteon Leak Sensor Heartbeat message

### ISSUE THREAD

**Issue by wes-warner** [home-assistant/home-assistant.github.io#27309]
### Feedback

Logged the following recently:

Logger: pyinsteon.utils
Source: runner.py:179
First occurred: 10:59:18 AM (9 occurrences)
Last logged: 11:04:18 AM

SenderMissingReqdMsgDataError
Some required args missing in call to sendMessage('event_4a7454_4_heartbeat_event', name,address,group): button
Topic listener: async_fire_group_on_off_event
-----------------------------
I am using rel 2023.4.6 on a pi4b debian supervised

What to do?

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2023.5.2

**Comment by teharris1** [comment]
This is the wrong repository to put this issue. THere is a duplicate message in the core repo: 
https://github.com/home-assistant/core/issues/94427
