### ISSUE TITLE
Multiple problems on page

### ISSUE THREAD

**Issue by sheyman1** [home-assistant/home-assistant.github.io#27311]
### Feedback

-  The "add integration" button only works for me if I install the repository via HACS first.  (manual steps same result)
-  The "view source on Github" link returns a 404 not found

I'm on v 2023.5.2 of Home Assistant

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2023.3.6

**Comment by frenck** [comment]
We have no "opower" integration @ Home Assistant. 

I think you are confusing a custom integration provided by a third-party as official?

Anyways, third-party custom integrations are not supported by the Home Assistant project. If you experience issues with one of them, please report it with the custom integration author.

Thanks 👍 

../Frenck
