### ISSUE TITLE
Need to add timedelay when turning off automations from other automations

### ISSUE THREAD

**Issue by LutzFassl** [home-assistant/home-assistant.github.io#27322]
### Feedback

In order to avoid interference between two automations I need to turn automation A off when running automation B.
(e.g. automation A turns on light based on physical button input and automation B turns on light based on movement detection. They are different enought so that I don't want to merge them into one automation.)

This works fine, but **ONLY** if I set a **time delay**. What works for me for example is this:

Within Automation B:
_1. Disable Automation A_
**2. Wait 100ms**
3. Perform Actions _(--> This would trigger Automation A in my case)_
**4. Wait 100ms**
_5. Enable Automation A_

- This works successful
**- If I don't use any waittimes the Automation A will trigger unintendedly**

I feel like this point should somehow be reflected in the documentation. Probably it's a very common issue, if I just stumbled upon this first try as a new user.
Otherwise: Awesome experience - lovely! Keep it up.

PS: 
Further Improvement potential for my case:
- I'm not sure if I need both waittimes.
- ..Maybe 1 of them will suffice. 
- Maybe 100ms is more than 1 need.

### URL

https://www.home-assistant.io/docs/automation/services/

### Version

2023.5.2

**Comment by dannytsang** [comment]
This looks very complicated and I can't tell if it's related to your hardware setup, how the automations are constructed or both.

Maybe the [Home Assistant community](https://community.home-assistant.io/) is better place to share this if you haven't done so already.
