### ISSUE TITLE
Supported Linux versions description is ambiguous.

### ISSUE THREAD

**Issue by jasonbrowne44** [home-assistant/home-assistant.github.io#27324]
### Feedback

This installation method has very strict requirements, for example, it only supports Debian (and Ubuntu, Armbian, Raspberry Pi OS are not supported).

I believe that the above statement is ambiguous.   Is Ubuntu (which is a Debian release) supported?  If you didn't know beforehand, it would be very difficult to figure this out.  If just Debian and Ubuntu are supported then please write (or something similar):

This installation method has very strict requirements, for example, it only supports Debian and Ubuntu. The following Linux distributions are not supported:
Armbian
Raspberry Pi OS

If Ubuntu isn't supported please write (or something similar):

This installation method has very strict requirements, for example, it only supports Debian.  The following Linux distributions are not supported:
Ubuntu
Armbian
Raspberry Pi OS

Please note that this text is used multiple places in your online documentation.

Thanks,

Jason

### URL

https://www.home-assistant.io/installation/linux/

### Version

2023.5.2

**Comment by frenck** [comment]
> I believe that the above statement is ambiguous. Is Ubuntu (which is a Debian release) supported? 

Did you actually read the first step listed and linked, which says to read and make sure you understand the requirements?

![CleanShot 2023-05-08 at 11 29 15](https://user-images.githubusercontent.com/195327/236788956-aaa5f38e-d25f-49c4-b152-9d8f843ef269.png)

The second step writes:

![CleanShot 2023-05-08 at 11 33 17](https://user-images.githubusercontent.com/195327/236789853-bb26449f-0549-47f0-96a8-ea46f4e40258.png)

However, you respond to this suggestion/issue:

> I believe that the above statement is ambiguous. Is Ubuntu (which is a Debian release) supported?

The line in the screenshot above clearly states Ubuntu is not supported? How did you end up with the question I wonder?

Please note, unlike you said in your comment, Ubuntu is not a Debian release.
