### ISSUE TITLE
Homeworks event description is wrong

### ISSUE THREAD

**Issue by fresnoboy** [home-assistant/home-assistant.github.io#27321]
### Feedback

The documentation for this plugin says:Homeworks keypad buttons are momentary switches. The button is pressed and released, meaning that there is no “state”. Buttons generate homeworks_button_press and homeworks_button_release events. These events contain the “id”, “name”, and “button” of the button that was pressed. “id” is derived from “name”, and “button” is the number of the button on the keypad (starting at 1).

This is not true, at least for the QS system.  The proper event type is lutron_event.

### URL

https://www.home-assistant.io/integrations/homeworks/

### Version

2023.4.6

### Additional information

This documentation also needs some updating, again at least for QS, the plugin updates all the keypads and lights without any manual enumeration.

**Comment by frenck** [comment]
> This is not true, at least for the QS system. The proper event type is lutron_event.

Are you sure you are not mixing it up with the [Lutron](https://www.home-assistant.io/integrations/lutron) integration?

As the `lutron_event` isn't used by the [Lutron Homeworks](https://www.home-assistant.io/integrations/homeworks) integration.

This is confirmed by a search query in our code base:

![CleanShot 2023-05-09 at 13 21 25](https://github.com/home-assistant/home-assistant.io/assets/195327/e63f0a9f-547d-4ef4-b412-82b95f90a912)

Only shows a match for `lutron_event` in our `lutron` integration (not `homeworks`).

../Frenck
