### ISSUE TITLE
User may have trouble due to incorrect saved credentials

### ISSUE THREAD

**Issue by Troy-K** [home-assistant/home-assistant.github.io#27336]
### Feedback

I was having a lot of trouble getting the Nest integration to work even though I was carefully following your guide. 
I kept getting stuck at the stage where the HomeAssistant Nest configuration wizard tries to configure application credentials, it seemed to be skipping it.  

I think it would be a great improvement to the "Link Google Account" section to mention that if you've tried to add a Nest integration before you may need to delete any old/incorrect Nest application credentials that may have been previously saved in HomeAssistant.
Settings > Devices > [menu] > Application Credentials > [Delete incorrect Nest credentials]

This integration obviously saves the credentials in the background, but skips that step if credentials are already saved.  Less experienced users like me may not realise that it could be the cause of authentication problems. And there is no indication that saved credentials are being used, nor is there instruction to check if there are saved credentials.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2023.5.2

**Comment by allenporter** [comment]
Hi,

The Link Account step says:

> See [Troubleshooting](https://www.home-assistant.io/integrations/nest/#troubleshooting) below for steps to resolve the common misconfigurations

The troubleshooting steps has examples for all of the error messages.  I think the error message you see when this happens is listed there:
> Can’t link to [Project Name]: Please contact [Project Name] if the issue persists: This typically means that the OAuth Client ID used is mismatched

and that has a whole section that tells you how to resolve a mismatched OAuth Client ID with screenshots.

If you have other suggestions, you are welcome to send edits to clarify what you found confusing or missing.

Closing respectfully.
