### ISSUE TITLE
This doesn't work right now

### ISSUE THREAD

**Issue by BobiderBob** [home-assistant/home-assistant.github.io#27332]
### Feedback

In homeassistant it tells me to manually add it via configuration.yaml, but here there is no documentation on how to do this, much rather a button to "just add it" which also doesn't work

### URL

https://www.home-assistant.io/integrations/snapcast/

### Version

2023.5.2

**Comment by frenck** [comment]
It means your Home Assistant is outdated. Snapcast moved to the UI in the Home Assistant Core 2023.5.0 release.

The instruction in our documentation reflects the current stable release of Home Assistant. After updating your system, the My Home Assistant button to add the integration should work as expected.

../Frenck
