### ISSUE TITLE
Waiting on integrations to complete setup: hassio

### ISSUE THREAD

**Issue by aperezva** [home-assistant/home-assistant.github.io#27331]
### Feedback

Since one week ago, My HA takes about 3 minuts to restart when one week ago was only 30 seconds

I can see this error in the logs
Logger: homeassistant.bootstrap
Source: bootstrap.py:499
First occurred: 18:34:16 (2 occurrences)
Last logged: 18:35:17

Waiting on integrations to complete setup: hassio

### URL

https://www.home-assistant.io/integrations/hassio/

### Version

2023.5.2

**Comment by dannytsang** [comment]
Hi @aperezva

You have raised this in a documentation part of the project. Please go to *New issues > Report a bug/issue with Home Assistant Core itself*
