### ISSUE TITLE
Examples please

### ISSUE THREAD

**Issue by bobbeims** [home-assistant/home-assistant.github.io#27348]
### Feedback

I've enabled Pico TTS as directed here, but can't get it to work. Could you please provide some YAML code examples of calling the service.

### URL

https://www.home-assistant.io/integrations/picotts/

### Version

2023.5.2

**Comment by quemart** [comment]
Good luck!
Pico TTS has been broken for me since version 2023.5.1.  It sounds like it's trying to read a line of code.
