### ISSUE TITLE
Netflix string isn't accurate, missing Spotify string

### ISSUE THREAD

**Issue by mcanteri** [home-assistant/home-assistant.github.io#27346]
### Feedback

The suggested string for Netflix doesn't run and goes in error and I wasn't able to find which is the correct string to use, neither for a very popular service like Spotify. I am stuck with ADB and media_player commands and would like to change versus remote.send_command.
Thank you in advance for the good work,
M.

### URL

https://www.home-assistant.io/integrations/androidtv_remote/

### Version

2023.5.2

**Comment by tronikos** [comment]
See https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921
Closing because adding this in the documentation is tracked in #27267

**Comment by tronikos** [comment]
@home-assistant close
