### ISSUE TITLE
Wyoming/whisper/piper requires https for local only HA?

### ISSUE THREAD

**Issue by Chrusciki** [home-assistant/home-assistant.github.io#27342]
### Feedback

![image](https://github.com/home-assistant/home-assistant.io/assets/29787339/5a3babeb-86cc-4346-8252-869bffe69c42)

my HA is not exposed to the internet and i have zero intention in making it internet facing just to activate these features. 
My browser does allow microphone access for the webpage, but regardless it looks like this error is just thrown regardless of the actually browser settings. 

how can we configure whisper/piper without exposing HA to the internet?

### URL

https://www.home-assistant.io/docs/configuration/securing/

### Version

2023.5.2

**Comment by Chrusciki** [comment]
![image](https://github.com/home-assistant/home-assistant.io/assets/29787339/acedeafa-c091-4c32-b8ba-d1b1a3a41d59)

allowed access to microphone...

**Comment by frenck** [comment]
Your browser requires access over HTTPS (with SSL) to allow access the webpage (Home Assistant) access to the microphone.

> how can we configure whisper/piper without exposing HA to the internet?

You can't configure whisper/piper for this issue, as mentioned in the error message in Home Assistant; this is your browser doing this, not Home Assistant.

../Frenck

**Comment by Chrusciki** [comment]
my browser clearly shows it allows access to the microphone.

**Comment by frenck** [comment]
> my browser clearly shows it allows access to the microphone.

Sure, but that is not the only limitation/security measure your browser sets/has.
