### ISSUE TITLE
Python Script link is dead

### ISSUE THREAD

**Issue by craigs66** [home-assistant/home-assistant.github.io#27362]
### Feedback

The link in this section is dead:

Clear the example code, and copy the Python script from: https://gist.github.com/matt2005/744b5ef548cc13d88d0569eea65f5e5b (modified code to support Alexa’s proactive mode, see details below)

### URL

https://www.home-assistant.io/integrations/alexa.smart_home/

### Version

2023.5.2

**Comment by agners** [comment]
The link seems to work here, this was most likely a GitHub outage earlier today: https://www.githubstatus.com/history.
