### ISSUE TITLE
New voice assist piper text to speech

### ISSUE THREAD

**Issue by carlosamus123** [home-assistant/home-assistant.github.io#27389]
### Feedback

I love the new year of the voice updates!

However if you have the voice assist speak sentences with line breaks like below

This sentence

Next sentence

The voice will only speak the first sentence

But it has the additional sentence stored in the pipeline

But it won't speak the second sentence until she speaks again ( from anything else or even using the try voice)

But this time she won't say the new speech she will continue from the last command do speak whatever the second sentence is.  This creates a response lag of 1 per each sentence broken up by spaces. 

And it will then forever affect that voice . 

### URL

https://www.home-assistant.io/docs/assist/

### Version

2023.5.2

**Comment by frenck** [comment]
Hi there @carlosamus123 👋 

It seems like you want to report an issue with an Home Assistant functionality, however, you have submitted documentation feedback instead.

Please report your issue here: <https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
