### ISSUE TITLE
Viessmann Vicare : "Unknown error occured" during configuration

### ISSUE THREAD

**Issue by WW2101** [home-assistant/home-assistant.github.io#27394]
### Feedback

There was a problem with the integration in HA. Reloading did not work, so I wanted to re-install the integration.

However, everytime I want to configure the integration (by filling in my details) I get "Unknown error occured" and I cannot add the integration.

Does anyone else have this problem?

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2023.5.2

**Comment by vpahud65** [comment]
The integration also stop working for me since few days.

Error setting up entry ViCare for vicare
May 12, 2023 at 21:15:37 – (ERROR) components/vicare/__init__.py
Missing 'data' property when fetching installations
May 12, 2023 at 21:15:37 – (ERROR) components/vicare

I don't know if it's the same issue.

**Comment by apfeil1** [comment]
For me the error occured the exact same way like the initial poster described it. No solution yet.

**Comment by podbiker** [comment]
Same here with version 2023.5.3

**Comment by Adandu** [comment]
Same here also with versions 2023.5.3

**Comment by ZipHH81** [comment]
Same here with Version 2023.5.3

**Comment by ZipHH81** [comment]
Herr you can find a possible solution for this problem:

https://github.com/home-assistant/core/issues/92864

**Comment by podbiker** [comment]
> Herr you can find a possible solution for this problem:
> 
> [home-assistant/core#92864](https://github.com/home-assistant/core/issues/92864)

Deleting /config/.storage/vicare_token.save resolved the issue for me.

**Comment by klaasnicolaas** [comment]
Hi there👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
