### ISSUE TITLE
Sensor for negative price energy for automation triggers

### ISSUE THREAD

**Issue by SgtFoose** [home-assistant/home-assistant.github.io#27397]
### Feedback

Can you add a sensor that goes high when the energy price is negative so we can hookup a relay to switch off our solar panels? Please note negative price will only cause you to pay for return delivery above a certain limit due to transport cost and stuff like taxes. Top of my head it will be around -€0.19 cents before we will be charged for returns.

### URL

https://www.home-assistant.io/integrations/energyzero/

### Version

2023.5.2

**Comment by klaasnicolaas** [comment]
What do you mean with "goes high"? Feature requests belong in the community forum, not here in a github issue.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
