### ISSUE TITLE
Adding new entity “ISO” to GW integration?

### ISSUE THREAD

**Issue by Palo47** [home-assistant/home-assistant.github.io#27398]
### Feedback

A new parameter ISO ( PV Isolation to ground) has appeared in the GW app Solar Go.
ISO is an important parameter in PV system maintenance.
Would it be possible to add the ISO entity to the GW integration?

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2023.5.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
