### ISSUE TITLE
Improved documentation (DOCKER)

### ISSUE THREAD

**Issue by emir-husic** [home-assistant/home-assistant.github.io#27405]
### Feedback

I have figured it out but I was thinking it would be nice for other users to know the following information when setting up HA with docker.

1. What port is ut running on? Defining port 8123 as the container port would help.
2. Which volume to set up for it to work during "restart". For e.g, in my case, It worked to set a host volume pointing to "/config" in the container. Now I restart the container without losing all of my settings.

### URL

https://www.home-assistant.io/getting-started/

### Version

2023.5.3

**Comment by dannytsang** [comment]
Is there a specific page where you see this as an issue?

For example, I looked at https://www.home-assistant.io/installation/linux#platform-installation and it has a volume defined and it uses host networking so it doesn't need a port parameter.

**Comment by emir-husic** [comment]
@dannytsang I think the page you sent is good. However, I could not "easily" find it going from the docker hub page.

By going to
https://hub.docker.com/r/homeassistant/home-assistant

I believe it would be nice if either that information was available directly in the docker hub, see mySql for example:

https://hub.docker.com/_/mysql

I do understand this may add overhead to having to maintain the documentation in multiple places, but what about having a simple link to directly link to a docker-installation page?

**Comment by frenck** [comment]
We don't maintain documentation on Dockerhub, as a matter of fact, we don't even use Dockerhub anymore.

Images to Dockerhub are uploaded for legacy reasons (backward compatibility), we recommend and document the use of the GitHub Container Registry. Please consult or official documentation for more information on how to install Home Assistant, which can be found on www.home-assistant.io.

../Frenck
