### ISSUE TITLE
integration with yeelink.light.color5

### ISSUE THREAD

**Issue by escdarck** [home-assistant/home-assistant.github.io#27416]
### Feedback

just boght couple of this beasts in Greese store 
NAME: Mi Smart LED Bulb Essential (White and Color)
MODEL: yeelink.light.color5

couldn't find with Yeelink app, integration with Xiaomi Home coldn't detect type of this lamp. Tried Philips — nothing helps

### URL

https://www.home-assistant.io/integrations/yeelight/

### Version

2023.5.3

**Comment by frenck** [comment]
That is expected, `color5` is not in the list of supported devices/models:

<https://www.home-assistant.io/integrations/yeelight/#supported-models>

../Frenck
