### ISSUE TITLE
Full ReoLink DUO 2 WIFI camera support seems to have snuck in

### ISSUE THREAD

**Issue by gh69** [home-assistant/home-assistant.github.io#27418]
### Feedback

No issue to report, just more positive feedback...though not documented, the latest release of the integration seems to have added full Person/Pet/Vehicle Smart Detection support for the new-ish "ReoLink DUO 2 WIFI" camera.  I only have 1 of these cameras and I'd been considering replacing it as the ReoLink native NVR compatibility was wonky when it first came out and it's HA compatibility was initially limited to a squashed-ratio stream and no smart detection (only motion detection events seemed to make it to HA even though the smart detection entities were created by the integration).  The squashed-ratio streaming issue was fixed pretty early on but this latest version of the integration, to my surprise, has fixed the missing smart detection issue as well.  This camera isn't listed on the compatibility list, but as of this latest release it looks like all functions of this camera are now supported via the integration.  Thanks again!  

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.5.3

**Comment by starkillerOG** [comment]
@gh69 thank you for your feedback and glad to hear it working nicely for you.
I added the Reolink DUO 2 WiFi to the list of supported devices here: https://github.com/home-assistant/home-assistant.io/pull/27421

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
