### ISSUE TITLE
need to remove section "USING WINDOWS TO OBTAIN CODES WITH BROADLINK MANAGER" or update to reflect it only works with older devices/firmware

### ISSUE THREAD

**Issue by eric10k93** [home-assistant/home-assistant.github.io#27419]
### Feedback

Downloading Broadlink Manager via the link and running "Scan" indicates that my device was found by IP, but then it shows an error "Writing compatible device not detected!"

I have a Broadlink RM4 Pro device.  The software finds it but it simply doesn't work.

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2023.5.3

**Comment by felipediel** [comment]
We don't want to go too deep documenting external applications and their supported devices, the idea is just to provide links so that users can do their own research

**Comment by eric10k93** [comment]
I understand, and I agree that makes sense, but the existing documentation already has a lot of details for external tools, and the existing information is now out of date.  Like you pointed out, these details don't really belong in the HA docs... I am new to using the Broadlink integration and tried out most of the methods listed for getting codes and most of them no longer work...

I personally found a lot of out of date information in the HA docs, which made it more difficult to find something that actually worked.  So I was simply suggesting some cleanup and clarification on what tools still work, and which ones
