### ISSUE TITLE
Run an app on androidtv

### ISSUE THREAD

**Issue by aik** [home-assistant/home-assistant.github.io#27432]
### Feedback

I am looking for a way to add a button to HA to start Kodi (or some other app, say, Firefox) on the TV, or even add automation to do so when the TV goes on, is that possible at all?

### URL

https://www.home-assistant.io/integrations/androidtv_remote/

### Version

2023.5.3

**Comment by tronikos** [comment]
This is for reporting issues and providing feedback not for asking such questions. Please use the community forum or discord.

For launching apps see https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921 (there is a pending PR that links to it in the documentation).
Yes you can create an automation in Home Assistant to launch an app when the state of the TV switches to on. Use the community forum or discord for help.

**Comment by tronikos** [comment]
@home-assistant close

**Comment by aik** [comment]
Thanks for the link. The link explains how to open URLs but not running apps. If an android decides that a certain URL opens a specific app - then the app starts. This should probably be reflected in the documentation as it is not obvious at all and sounds really as a bug (of android, I am guessing) because there is no such URL for Kodi so it cannot be run this way.
upd: seems "smb://" does it for my tv (although I do not have vlc installed). oh well. Thanks for the help.
upd2: nah it does not :(
