### ISSUE TITLE
Tag name should be referencable in templates

### ISSUE THREAD

**Issue by iamnikv** [home-assistant/home-assistant.github.io#27438]
### Feedback

At the moment only tag_id and device_id are available for use, however the tag name would be useful in situations where you have a lot of tags and an automation or command that needs only the name of the tag to function. For example using nfc tags to add items to a grocerie list could be achieved with one single automation based on the name of the tag. Now I have to make an automation for each tag I create..

### URL

https://www.home-assistant.io/integrations/tag/

### Version

2023.5.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
