### ISSUE TITLE
Documentation doesn't explain how to add unique_id to Onkyo integration

### ISSUE THREAD

**Issue by DaveStLou** [home-assistant/home-assistant.github.io#27447]
### Feedback

When I attempt to edit my Onkyo entity in the UI, I get the error: "This entity ('media_player.living_room_onkyo') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail."

When I attempt to add a unique_id to the integration in the configuration.yaml I get the error "Invalid config for [media_player.onkyo]: [unique_id] is an invalid option for [media_player.onkyo]. Check: media_player.onkyo->unique_id." from the configuration checker.

Neither the FAQ for unique ID or the Onkyo documentation are of any help. Please update and/or advise.

### URL

https://www.home-assistant.io/integrations/onkyo/

### Version

2023.5.3

### Additional information

configuration.yaml entry:

media_player:
  - platform: onkyo
    host: 10.42.8.66
    name: Living Room Onkyo
    sources:
      bd-dvd: "Blu-ray"
      cbl-sat: "Roku"
      stb-dvr: "FireTV"

**Comment by frenck** [comment]
As per documentation linked in that error message:

> This however is not an error, but just a limitation of the integration you use.

You can't add one yourself.

../Frenck
