### ISSUE TITLE
Area could/should be able to provide energy/power usage

### ISSUE THREAD

**Issue by q20** [home-assistant/home-assistant.github.io#27444]
### Feedback

As per title... an area card should be able to collect energy info together for all devices assigned to the given area, allowing for a quick, relevant look at what's up, energy-wise.
 👍

### URL

https://www.home-assistant.io/dashboards/area/

### Version

2023.5.3

**Comment by dannytsang** [comment]
@q20 I like this idea. Unfortunately, it's been raised in the documentation repository. If I could ask you to go to **New issue** > **Feature Request**, check and post your suggestion there please.
