### ISSUE TITLE
Livisi Switch position wrong

### ISSUE THREAD

**Issue by marcel51090** [home-assistant/home-assistant.github.io#27441]
### Feedback

Hello,

Unfortunately, HA still shows the livisi switch position only "off".

When switching, it jumps over but after a short time the switch jumps back to "off".

Can you tell me how to fix this?

Greetings, Marcel

### URL

https://www.home-assistant.io/integrations/livisi/

### Version

2023.5.3

**Comment by marcel51090** [comment]
Hello, is there any more feedback here? I saw through the whole Internet and unfortunately didn't find a solution.

Greetings, Marcel

**Comment by planbnet** [comment]
Hi Marcel,

sorry, but without any specific information it is simply not possible to help you at all here. We don't even know what kind of device you're talking.

Please add all the information (what kind of switch, logs, ...) you can gather and we'll see if we can identify the problem, but at first please ensure that the information in the local Livisi web interface is correct.

**Comment by marcel51090** [comment]
Thanks for the feedback, these are various adapter plugs from livisi / RWE / Innogy which jump back into the off state in Home assistant even though they are still on in the web interface of livisi.

The problem is also described in thread #84940 but unfortunately not solved.

Since I'm not a programmer, I can't say much about the protocols. If further information is needed, please let me know.

Greetings, Marcel

PS: My texts are translated by Google from German to English!

**Comment by planbnet** [comment]
Sorry, this issue has been posted to the wrong repo - this one is only for documentation. The correct issue tracker is https://github.com/home-assistant/core/issues

Besides that, you need to provide log data from the integration - without that there is no way that anyone could figure out the problem.

@home-assistant close
