### ISSUE TITLE
Home assistant updates suggestion.

### ISSUE THREAD

**Issue by Stormlord1973** [home-assistant/home-assistant.github.io#27449]
### Feedback

Today i had Node-Red and also Adblock to update, had to update both one-by-one... would like to suggest to add a *UPDATE ALL* button of somekind, the system already knows when update are needed..  could be helpfull no?

### URL

https://www.home-assistant.io/help/

### Version

2023.5.3

**Comment by c0ffeeca7** [comment]
Hi there, @Stormlord1973 

It seems like you want to suggest a feature. However, you have used the GitHub tracker for documentation issues.

To suggest a feature, please try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).
