### ISSUE TITLE
Nuki Smart Lock 3.0 Pro MQTT support

### ISSUE THREAD

**Issue by usicro** [home-assistant/home-assistant.github.io#27457]
### Feedback

As firmware version 3.5.11 for the Nuki Smart Lock 3.0 Pro introduced MQTT support (including auto-discovery via MQTT for Home Assistant), no additional integration besides MQTT is required. As this information seems not very visible when searching via Google or other sources (there is one german blog post about the added support), I suggest to add this information to the Nuki integration page, for example something like that:

Nuki Smart Lock 3.0 Pro
Starting from firmware version 3.5.11 the Nuki Smart Lock 3.0 Pro (which has WiFi integrated) can be integrated directly via the [MQTT](https://www.home-assistant.io/integrations/mqtt/) integration. The lock also supports MQTT Discovery (if not disabled in the Nuki app, default "homeassistant" discovery topic), therefore only setting up WiFI and MQTT in the Nuki app is required to integrate the lock.

### URL

https://www.home-assistant.io/integrations/nuki/

**Comment by usicro** [comment]
For further information also links to the Nuki Support pages could be added:
[Nuki Support page](https://support.nuki.io/hc/en-us/articles/12947926779409-MQTT-support)
And the forum post with the MQTT API description: [MQTT API](https://developer.nuki.io/t/mqtt-api-specification-v1-3/17626)

**Comment by jbouwh** [comment]
For MQTT the first link was already added. The post the API description could be added.

**Comment by jbouwh** [comment]
I added a PR, please check if the added information is correct.
