### ISSUE TITLE
Ecowitt integration

### ISSUE THREAD

**Issue by jotzaile** [home-assistant/home-assistant.github.io#27452]
### Feedback

Integration added as instructed, but no entities being created, i guess no comunication between the device and the server. Maybe some port forwarding is needed?

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2023.5.3

**Comment by klaasnicolaas** [comment]
Hi there @jotzaile 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by jotzaile** [comment]
Sorry about that, thank you.
