### ISSUE TITLE
Incorrectly describing the "current price"

### ISSUE THREAD

**Issue by nbesh-apptio** [home-assistant/home-assistant.github.io#27451]
### Feedback

The documentation/main page states:  "Price - Your current electricity price in $/kWh"

This is not technically correct - the integration provides the "forecasted current price" which may be significantly different during times of price spikes.

I'd suggest a rather pedantic but important change to specify something similar to:
"All prices are forecasts, as such may differ from the final prices for each period as displayed in the Amber app."

### URL

https://www.home-assistant.io/integrations/amberelectric/

### Version

2023.5.3

**Comment by madpilot** [comment]
Not all prices are forecasts - they are actuals in the last 5 minutes of the 30 minute interval. And technically they are made up of a mixture of actuals and forecasts.

But I will add a note pointing at an explainer of how 30-minutes prices are calculated.
