### ISSUE TITLE
missing details

### ISSUE THREAD

**Issue by typxxi** [home-assistant/home-assistant.github.io#27454]
### Feedback

If you want to have success with a documentation that it has to be step by step, precise and understandable.

Here you simply forgot to explain, where I can find and start these editors. I have installed this Visual Code thing which took quite a while on a raspberry pi and I also got in trouble cause the installation seemed to be broken and so I tried it again - and again till 20 or 30 minutes later I got a message, that the installation had been successfull followed by 2 warning that the VS has been already installed.

Anyway: Where can find the editor ? 
Do I need a restart no one had mentioned? 

If I have those quesstions many more will struggle too.

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2023.5.3

**Comment by dannytsang** [comment]
I have added further links to the area you're comment relates to. This won't 100% address your point but may help slightly.

Given the multitude of ways to get to the configuration file, I don't feel up to the task of re-writing it and leave it up to you / others.
