### ISSUE TITLE
Date & Time Field

### ISSUE THREAD

**Issue by EG-John** [home-assistant/home-assistant.github.io#27459]
### Feedback

Hello, thank you for creating this this integration.  I have a request, is it possible to add a date and time field?  I am actually hoping to use this to track my food intake to match it against my blood sugar level, which I am currently tracking using the Dexcom integration.   My hope is that when I eat something I could use this integration (shopping list) to enter the date, time and food that I ate, then pull the data and compare it to my blood sugar level. 

Thank you very much for your consideration, 
John

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2023.5.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
