### ISSUE TITLE
Need more clear usable documentation

### ISSUE THREAD

**Issue by vhillaire** [home-assistant/home-assistant.github.io#27468]
### Feedback

Following the instruction on this page don't yield usable results or provide enough insight to figure out how to apply this to my specific need. After taking several stabs in the dark I end up with the text of the GPS coordinates in json format appearing below my user rather than GPS coordinates usable by the system to identify where my user is located. It seems like there are 2 scenarios one with json and one without. The one without works ok to create a tracker in yaml and the other with json only works updating something on the user that is not seen as a GPS location but rather as text for what location the user is in? It might be best to clearly separate the scenarios with a clear Titles like "Create a tracker without GPS"  or "Create a tracker with GPS and JSON". It would also be nice to know where these are being stored so I can delete or correct the mistakes without having to start over with a new instance of home assistant. I will present my specific problem here to the community to see if they can help me resolve the issue I am having, I'm only suggesting here that the help page could use some work.
![SoClose-screen-2023-05-20-13-35-44](https://github.com/home-assistant/home-assistant.io/assets/3893881/48a0a986-e196-4fc0-98c9-eb47be50e0d8)

### URL

https://www.home-assistant.io/integrations/device_tracker.mqtt/

### Version

2023.5.3

**Comment by jbouwh** [comment]
When I try the example from the documentation I get something like:
![afbeelding](https://github.com/home-assistant/home-assistant.io/assets/7188918/15e73dfe-abb8-4777-a940-b4c47ff0447d)
It looks like you published the GPS attributes to the state topic instate of the json attributes topic.

The idea is that by setting the GPS coordinates via the `json_attribute_topic` the state can be derived from the `zones` configured. 
When configuring a zone you need to set a radius. If the device tracker is within range, it can get the state of zone.
A message at the state topic can override the the automatic state. Sensing a `None` payload will reset the override.
I agree this could use a better example. There are tests though that demonstrate this:

```python
async def test_setting_device_tracker_location_via_reset_message(
    hass: HomeAssistant,
    mqtt_mock_entry: MqttMockHAClientGenerator,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """Test the automatic inference of zones via MQTT via reset."""
    await mqtt_mock_entry()
    async_fire_mqtt_message(
        hass,
        "homeassistant/device_tracker/bla/config",
        "{ "
        '"name": "test", '
        '"state_topic": "test-topic", '
        '"json_attributes_topic": "attributes-topic" '
        "}",
    )

    hass.states.async_set(
        "zone.school",
        "zoning",
        {
            "latitude": 30.0,
            "longitude": -100.0,
            "radius": 100,
            "friendly_name": "School",
        },
    )

    await hass.async_block_till_done()

    state = hass.states.get("device_tracker.test")
    assert state.attributes["source_type"] == "gps"

    assert state.state == STATE_UNKNOWN

    hass.config.latitude = 32.87336
    hass.config.longitude = -117.22743

    # test reset and gps attributes
    async_fire_mqtt_message(
        hass,
        "attributes-topic",
        '{"latitude":32.87336,"longitude": -117.22743, "gps_accuracy":1.5}',
    )
    async_fire_mqtt_message(hass, "test-topic", "None")

    state = hass.states.get("device_tracker.test")
    assert state.attributes["latitude"] == 32.87336
    assert state.attributes["longitude"] == -117.22743
    assert state.attributes["gps_accuracy"] == 1.5
    assert state.attributes["source_type"] == "gps"
    assert state.state == STATE_HOME

    # test manual state override
    async_fire_mqtt_message(hass, "test-topic", "Work")

    state = hass.states.get("device_tracker.test")
    assert state.state == "Work"

    # test reset
    async_fire_mqtt_message(hass, "test-topic", "None")

    state = hass.states.get("device_tracker.test")
    assert state.state == STATE_HOME

    # test reset inferring correct school area
    async_fire_mqtt_message(
        hass,
        "attributes-topic",
        '{"latitude":30.0,"longitude":-100.0,"gps_accuracy":1.5}',
    )

    state = hass.states.get("device_tracker.test")
    assert state.state == "School"
```

The example also proves an MQTT `device_tracker` could work without `state_topic` when the state die derived from the GPS coordinates.

**Comment by jbouwh** [comment]
I'll add an extra example using the `json` to set the state. A `state_topic` should not be needed.
This PR will make `state_topic` optional if `json_attributes_topic` is configured.

**Comment by jbouwh** [comment]
[#93322](https://github.com/home-assistant/core/pull/93322) I'll open the docs PR later.

**Comment by vhillaire** [comment]
Thank you I understand better now. I look forward to the new example. I will keep scouring the forum for a way to recreate the following in home assistant: 
![DroneIDDashscreen-2023-05-15-12-16-00](https://github.com/home-assistant/home-assistant.io/assets/3893881/d665cd83-fa9a-400b-9ad4-997582ee682a)

**Comment by jbouwh** [comment]
You could have a look at the linked PR with the updated documentation. The only thing that does not work yet is leaving `state_topic` away as this is still required.

**Comment by vhillaire** [comment]
Thank you
