### ISSUE TITLE
How can I get an indication of how much money the boiler spends per day?

### ISSUE THREAD

**Issue by man55** [home-assistant/home-assistant.github.io#27461]
### Feedback

It's very complicated and not clear at all.
I have several appliances that I would like to track consumption. 

For example:
I have a boiler for which there is a sensor in the HA that shows the current consumption.
I have two tariffs, at night from 23:00 to 7:00 one tariff, during the day another tariff.
There is a price of each fares in currency.

How can I get an indication of how much money the boiler spends per day?
Who can explain it step by step?
This article, Google and chatgpt did not help.

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2023.5.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
