### ISSUE TITLE
Cannot add 2nd HS210

### ISSUE THREAD

**Issue by ifuchs** [home-assistant/home-assistant.github.io#27469]
### Feedback

I have 2 Kasa Smart 3 way switches installed (2 pairs). They show up and work correctly via the Kasa Smart ios app. If I add the integration to HA, it searches and finds one of the 2 switches and I can add it and it works. However, I am not able to add the second one. Can anyone help me get this working? The 1st switch was configured earlier (before I added the second), so it is possible that there is something still there, but I cannot find it and I have deleted and re-added the integration to no avail.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2023.5.3

**Comment by rytilahti** [comment]
Alas, I cannot help you much besides saying that you could try to add the device by its IP address to skip the discovery process.

But please use [the community forums](https://community.home-assistant.io/) for support requests, this repository is designated for the documentation issues so I'm closing it.

**Comment by ifuchs** [comment]
I tried using the IP address and it said the device was already there but it is not. When you say use the Community Forums, to what are you referring? The link above just took me to the list of categories in this forum. Do I need to repost this under a different category?

**Comment by rytilahti** [comment]
Okay, that sounds like a bug, so the proper place would be to report it here: https://github.com/home-assistant/core/issues/new/choose - I'm not sure what could be causing that, besides if the device exists already using a different IP address? But please create a separate issue for that as it shouldn't happen.
