### ISSUE TITLE
Switchbot blind tilt wrong light level in HA

### ISSUE THREAD

**Issue by stofakiller** [home-assistant/home-assistant.github.io#27464]
### Feedback

I had the switchbot blid tilt (3 pcs) for a while, and even the app says eg 8 or 10 in intensity, the level for all 3 is always light level = 2, even in the night

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.5.3

**Comment by bnystrom** [comment]
Still an issue

**Comment by starfleetk** [comment]
All an issue,  I have 5 blinds and are all stuck at light level 2
