### ISSUE TITLE
Inkbird Dosnt work 

### ISSUE THREAD

**Issue by marcel51090** [home-assistant/home-assistant.github.io#27465]
### Feedback

Unfortunately, the Inkbird integration does not work with my IBS-M1

When setting up, she does not find any devices on the network

Too bad

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2023.5.3

**Comment by frenck** [comment]
Thanks for your message. However, looking at the list in the documentation, the model you mentioned is not listed as supported. So that is expected.

../Frenck

**Comment by marcel51090** [comment]
I‘m sorry

**Comment by frenck** [comment]
Don't worry about it 👍 

../Frenck

**Comment by marcel51090** [comment]
Do you know if or how it is possible to integrate the device?
