### ISSUE TITLE
disable the “Wait for push” option (disabled by default).

### ISSUE THREAD

**Issue by pimw1** [home-assistant/home-assistant.github.io#27477]
### Feedback

Hi,

The option is called "Wait for multicast push on update" , but is refered to in the documentation as “Wait for push”. Nothing big, but for completeness/clearness it's imo best to literally name the option in the documentation.

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2023.5.3

**Comment by starkillerOG** [comment]
Thanks @pimw1 for pointing this out, I have adjusted it here: https://github.com/home-assistant/home-assistant.io/pull/27508

**Comment by pimw1** [comment]
Thanks starkillerOG!
