### ISSUE TITLE
Missing documentation how to group sonos speakers

### ISSUE THREAD

**Issue by ManuelNRW** [home-assistant/home-assistant.github.io#27479]
### Feedback

Hello all,
is there a way to group the Sonos speakers like in the Sonos app to be able to play music in this group. Unfortunately I could not find anything in the forum and in the documentation. If the possibility exists, I would appreciate an entry in the documentation.
Thank you and best regards :-)

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2023.5.3

**Comment by jjlawren** [comment]
Those services are described in the base [media player](https://www.home-assistant.io/integrations/media_player/#services) integration as described here: https://www.home-assistant.io/integrations/sonos/#services
