### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by vwests** [home-assistant/home-assistant.github.io#27478]
### Feedback

I'm using HA on Asustor NAS and when installing the integration I get this error message. I have the server and robot on the same network. Not a pro at all, but am I missing something simple?

Logger: homeassistant.config_entries
Source: components/roborock/__init__.py:32
First occurred: 19:47:17 (3 occurrences)
Last logged: 19:51:49

Error setting up entry *****.*****@gmail.com for roborock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/roborock/__init__.py", line 32, in async_setup_entry
    home_data = await api_client.get_home_data(user_data)
  File "/usr/local/lib/python3.10/site-packages/roborock/api.py", line 510, in get_home_data
    raise RoborockException(home_response)
roborock.exceptions.RoborockException: {'code': 'auth.err', 'msg': 'auth.err.invalid.token', 'status': 'UNAUTHORIZED', 'timestamp': '2023-05-21T16:52:09.163+00:00'}

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.5.3

**Comment by klaasnicolaas** [comment]
Hi there @vwests 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by vwests** [comment]
Whoops, I’m so sorry. Thank you for the kindly pointed finger, I’ve submitted the issue in the proper location now.

regards
