### ISSUE TITLE
Additional information on the registration process

### ISSUE THREAD

**Issue by doug987** [home-assistant/home-assistant.github.io#27487]
### Feedback

The documentation has the following instructions "You can get an API key by registering for a Met Office [account](https://register.metoffice.gov.uk/WaveRegistrationClient/public/register.do?service=datapoint). As their website is not as straightforward, after registration and verifying your account you can login [here](https://register.metoffice.gov.uk/MyAccountClient/account/view) to retrieve your API key."

Can I suggest that this is amended to 
"You can get an API key by registering for a Met Office [account](https://register.metoffice.gov.uk/WaveRegistrationClient/public/register.do?service=datapoint). Details of the registration process can be found on the Met Office web site [here.](https://www.metoffice.gov.uk/services/data/datapoint/getting-started) As their website is not as straightforward, after registration and verifying your account you can login [here](https://register.metoffice.gov.uk/MyAccountClient/account/view) to retrieve your API key."

The new link clarifies that you need to register with the Met Office web site, click on the link received by email, scroll down to Met Office DataPoint section, click on that link and then using that new account register it with the Met Office DataPoint

### URL

https://www.home-assistant.io/integrations/metoffice/

### Version

2023.5.3

**Comment by frenck** [comment]
If you are up to it, feel free to open up a PR! 🙏 

../Frenck
