### ISSUE TITLE
Twitter Integration doesn't work

### ISSUE THREAD

**Issue by cryptooth** [home-assistant/home-assistant.github.io#27481]
### Feedback

I think, last weekend Twitter blocked my v1.0 API an need to regenerate APIv2 key. Is it possible to renew your documents?

Error:

Error 403: [{'message': 'You currently have access to Twitter API v2 endpoints and limited v1.1 endpoints only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453}]

thanks 

### URL

https://www.home-assistant.io/integrations/twitter/

### Version

2023.5.3

**Comment by Thrasher2020** [comment]
I am also encountering this issue. I hope we can get it resolved quickly.

**Comment by klaasnicolaas** [comment]
Hi there @cryptooth 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
