### ISSUE TITLE
Missing URL

### ISSUE THREAD

**Issue by olgru** [home-assistant/home-assistant.github.io#27486]
### Feedback

I tried to get my SkyConnect stick working. I already have Zigbee2MQTT with a deconn stick and would like to run the skyconnect with ZHA/Matter etc is parallel.
I followed installation instructions on siliconlab multiprotocol, where it is stated that OTBR will also be installed. However, it does not.
And I usually get this kind of configuration message:
"Provide URL for the Open Thread Border Router's REST API"

I have no idea about this URL, this is hassio image with brilliant docker playground setup - but I'm not speaking docker.
The documentation does not provide any help here.
And adding the skyconnect through ZHA results in another error - while the stick is correctly be found and can be selected, when it comes to connection I got an unknown error.

### URL

https://www.home-assistant.io/integrations/otbr/

### Version

2023.5.3

**Comment by c0ffeeca7** [comment]
> I followed installation instructions on siliconlab multiprotocol, where it is stated that OTBR will also be installed. However, it does not.

Which instructions are you referring to? The procedure on [enabling multiprotocol support](https://skyconnect.home-assistant.io/procedures/enable-multiprotocol/)? If so: 
   * Did you see the success message mentioned in Step 3? 
   * When selecting the add-on in Step 4, did you check the add-on logs? Maybe it contains a hint what went wrong?

**Comment by olgru** [comment]
Sorry, that I've been a bit confusing.

Initially I wanted to have the stick running as secondary Zigbee device with the new experimental features (multi protocolsupport) too. But I'm not able to add the stick to ZHA - I got an error in this step already. It's found, I can select the stick on /dev/ttyUSB0, I can select the protocol EZSB but after the serial port dialog I got an error to connect.

Regarding your questions:
Multiprotocol for the stick is already enabled, I saw the success message on step 3.
But I have no ZHS connection as defined as pre-req in the enabling procedure you referer to.

Step 4 fails - I think because the service did not start.

So I tried to start the Silicon Labs Multiprotocol AddOn which results in:
```
[07:45:37] INFO: The otbr-web is disabled.
s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
[07:45:37] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (May 15 2023 13:39:01) starting
Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting
-----------------------------------------------------------
 Add-on: Silicon Labs Multiprotocol
 Zigbee and OpenThread multiprotocol add-on
-----------------------------------------------------------
 Add-on version: 1.1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.5.4
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[07:45:38] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[07:45:38] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0
2023-05-26 07:45:38 has universal_silabs_flasher.flash[181] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.2.3', ezsp_version=None, ot_rcp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>, baudrate=460800)
2023-05-26 07:45:38 has universal_silabs_flasher.flasher[181] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-05-26 07:45:40 has universal_silabs_flasher.flasher[181] INFO Probing ApplicationType.CPC at 460800 baud
2023-05-26 07:45:44 has universal_silabs_flasher.flasher[181] INFO Probing ApplicationType.CPC at 115200 baud
2023-05-26 07:45:49 has universal_silabs_flasher.flasher[181] INFO Probing ApplicationType.CPC at 230400 baud
2023-05-26 07:45:53 has universal_silabs_flasher.flasher[181] INFO Probing ApplicationType.EZSP at 115200 baud
2023-05-26 07:45:58 has universal_silabs_flasher.flasher[181] INFO Probing ApplicationType.SPINEL at 460800 baud
Error: Failed to probe running application type
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service mdns: stopping
s6-rc: info: service banner: stopping
Default: mDNSResponder (Engineering Build) (May 15 2023 13:39:01) stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[07:46:02] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped
```

I've looked for the Integration "Threat" and found the message "No border router found". - OK, where is the border router comming from. So I check the OTBR which is automatically installed when the SiliconLab Multiprotocol is installed...

At the end - this is about this "missing URL" statement:
When I tried to configure/install the OTBR the dialog is requesting an URL. I have no idea what this URL is about...  

Reading everything above, I think I should focus on the question why the stick is not connecting for ZHA first. Maybe a bad cable...

**Comment by agners** [comment]
@olgru most likely you have some serial port conflict. I also noticed that the firmware sometimes crashes when that happens. So my suggestion is to:

1. Remove any active ZHA connection
2. Remove the SilLabs Multiprotocol add-on
3. Make sure there is also no other add-on which accesses the serial port (e.g. disable/stop Z2M)
4. Unplug the SkyConnect
5. Restart Home Assistant
6. Plug the SkyConnect back in
7. Use System -> Hardware to configure the stick for Multiprotcol operation.
