### ISSUE TITLE
How to change picture on area card

### ISSUE THREAD

**Issue by skome** [home-assistant/home-assistant.github.io#27489]
### Feedback

How to change picture on area card?
How to remove picture on area card?

### URL

https://www.home-assistant.io/dashboards/area/

### Version

2023.5.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
