### ISSUE TITLE
Is it planned to include. The new Netatmo “Smart AC Controller” ?

### ISSUE THREAD

**Issue by Palo47** [home-assistant/home-assistant.github.io#27495]
### Feedback

Is it planned to include to the Home Kit Controller  the new Netatmo “Smart AC Controller” ?
Is it possible to to give the aproximate date?

### URL

https://www.home-assistant.io/integrations/homekit_controller/

### Version

2023.5.3

**Comment by Jc2k** [comment]
Hi I think you've accidentally filed this in the wrong place, this is where we work on documentation. If you do think there is a mistake with the documentation can you please be more specific.

It sounds like you are making a feature request, those belong in the feature request part of the forum.

Right now I'm not aware of anybody working on that device in the context of homekit. Not am I aware of any problems with that device.

HomeKit in general does not have device specific code for basic device support. For any supported class (like a heating or cooling device) I'd expect it to work out of the box with any version of HA in the past few years. Sometimes there are extra features we can reverse engineer, but the core basic features are the same for any HomeKit device in the same class.

**Comment by Palo47** [comment]
I apologize for misdirecting my post.
Just adding. HA finds a Netatmo Smart AC Controller device for the Home Kit Controller but after trying to configure this integration HA freezes.
The Netatmo Smart AC Controller is a brand new product and allows you to control the cooling and heating performance of any room AC device that is equipped with an IR remote controller. I see great potential of this device for comfort and energy saving.

**Comment by Jc2k** [comment]
Ok, that sounds like a bug report, if you file a report on the "core" repository and include debug logs we might be able to help you.

**Comment by Palo47** [comment]
Thank you
