### ISSUE TITLE
Contradiction?

### ISSUE THREAD

**Issue by bennop** [home-assistant/home-assistant.github.io#27504]
### Feedback

I'm puzzled by the example using "~" while the description states that such expansion is not allowed in the more secure environment the command is executed in ... do I misunderstand something?

### URL

https://www.home-assistant.io/integrations/shell_command/

### Version

2023.5.4

**Comment by MartinHjelmare** [comment]
Using `~` is not allowed when using a template. The examples that have `~` are not using templates.

**Comment by bennop** [comment]
Thank you for the clarification!

Benno
