### ISSUE TITLE
Browsers support very out of date

### ISSUE THREAD

**Issue by steverep** [home-assistant/home-assistant.github.io#27509]
### Feedback

The data on this page is mostly out of date, and could be written less confusingly towards users.  It should meld better with the [developers frontend page](https://developers.home-assistant.io/docs/frontend/), and incorporate recent changes to supported browsers:

- https://github.com/home-assistant/frontend/pull/16506 (for latest builds)
- https://github.com/home-assistant/frontend/pull/16384 (for ES5 builds)

### URL

https://www.home-assistant.io/docs/frontend/browsers/

### Version

2023.5.4

**Comment by steverep** [comment]
Still an issue

**Comment by steverep** [comment]
Still in work

**Comment by frenck** [comment]
Closing this, as the page no longer exists.

../Frenck

**Comment by steverep** [comment]
> Closing this, as the page no longer exists.

So where are browser requirements documented then?
