### ISSUE TITLE
What type is backup

### ISSUE THREAD

**Issue by PitHerm** [home-assistant/home-assistant.github.io#27513]
### Feedback

Within the documentation there is not information provided what kind of backup this service  does, Full or core or ?

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2023.5.4

**Comment by dannytsang** [comment]
I'm running 2023.6.1 and the services are a lot clearer (see below). Looks like this documentation could also do with updating.

![image](https://github.com/home-assistant/home-assistant.io/assets/567982/3274405f-dd23-480c-b8d4-75cfc938441b)

**Comment by ludeeus** [comment]
That is not the same, the `backup` integration (linked here) is only for core/container.
And as that only have core, I fail to understand what is missing, full / core should mean the same on those, can you elaborate @PitHerm ?

<https://www.home-assistant.io/common-tasks/os/#backups> is for HAOS.

**Comment by dannytsang** [comment]
Thanks for correcting @ludeeus .
