### ISSUE TITLE
Bad link in Groups page

### ISSUE THREAD

**Issue by Didgeridrew** [home-assistant/home-assistant.github.io#27525]
### Feedback

https://www.home-assistant.io/integrations/group/#services links too high in the page.  Specifically it links to https://www.home-assistant.io/integrations/group/#service which is part of the Notify group section not the section covering the services that can act on the group domain.

### URL

https://www.home-assistant.io/integrations/group/#services

### Version

2023.5.4

**Comment by frenck** [comment]
I see the point, unfortunately, we do not have a solution for this.

That said, the services that is linked are the ones we recommend on using 😉 

../Frenck
