### ISSUE TITLE
How to select hdmi

### ISSUE THREAD

**Issue by hotmonitor** [home-assistant/home-assistant.github.io#27530]
### Feedback

Hello , 
Integration change Chanel but how to select hdmi sourses hdmi1 hdmi2 .... .? How to chose app YouTubegoogle meet? My tv is samsung 65q70b can you show me example?
Best regards

### URL

Http

### Additional information

No

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
