### ISSUE TITLE
Grandstream HT812 confirmed working for VOIP with HA

### ISSUE THREAD

**Issue by hubikj** [home-assistant/home-assistant.github.io#27534]
### Feedback

I can confirm Grandstream HT812 works with Home Assistant too, so it can be added to the VOIP page which currently only mentions compatibility with HT801 and HT802.

### URL

https://www.home-assistant.io/integrations/voip/

### Version

2023.5.4

**Comment by c0ffeeca7** [comment]
Good to hear. Thank you for letting us know, @hubikj :+1:
