### ISSUE TITLE
Is it possible to do a DOCSIS resync? 

### ISSUE THREAD

**Issue by Botschafter** [home-assistant/home-assistant.github.io#27545]
### Feedback

Is it possible to do a DOCSS resync? Because the Restart does the same but takes much more time. 
DOCSIS resync is a feature with Cable Boxes and can be found inside the Support Menu in Firmware 7.50.
The Box will start a quick new resyncronisation an Cable Connection. This will take about 20 sekonds. A Restart can be up to 4 Minutes.

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2023.5.4

**Comment by mib1185** [comment]
You can try the reconnect button (_trigges [ForceTermination (see 1.7)](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wanipconnSCPD.pdf)_), but i'm not sure if it will also resync the physical line, but only the IP connection itself.

**Comment by Botschafter** [comment]
Yes this will only renew IP. No resync.

27.05.2023 12:24:35 Michael ***@***.***>:

**Comment by mib1185** [comment]
Than it is not possible with the current implementation, and it is unsure if the FritzBox API does provide such feature.

**Comment by frenck** [comment]
Thanks for clearing that up @mib1185 👍 

Going to close the documentation feedback issue on this end for that reason.

../Frenck
