### ISSUE TITLE
Chipolo not working

### ISSUE THREAD

**Issue by duesseldorferjung** [home-assistant/home-assistant.github.io#27547]
### Feedback

The recommended chipolo does not work

### URL

https://www.home-assistant.io/integrations/ibeacon/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by duesseldorferjung** [comment]
The issue is reported and it is mentioned it should be removed from the documentation.
https://github.com/home-assistant/core/issues/88434

**Comment by klaasnicolaas** [comment]
In that case someone can make a pull request to remove it from the list.
