### ISSUE TITLE
Region IT

### ISSUE THREAD

**Issue by dvdmaz** [home-assistant/home-assistant.github.io#27559]
### Feedback

I'm trying to connect to my Xiaomi Miio account to set up Roborock integration in HA, but I've discovered that my account is registered in the Italian region (should be "IT").
I've also tried the token extractor for the IT region, even if it's not listed, but it doesn't work... it says "Invalid server provided". I suppose that to implement this the program needs to be aware of the correct address for the Xiaomi server for Italy.
Also, in HA, even in manual configuration, using the token, Home assistant doesn't list the IT region... so I wouldn't be able to use it in the manual setup. Is it difficult to you to add the Italian region? I'm a programmer, so if I can help with my device I'll be pleased to help you in this in my spare time.
Thank you, and thanks for sharing your work!

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.5.4

**Comment by humbertogontijo** [comment]
You mentioned Xiaomi and token extractor. Are you using Roborock account? Not Mi home account
The same account used in Roborock app

**Comment by dvdmaz** [comment]
Last update solved the problem. Thanks!
