### ISSUE TITLE
MQTT: Is it the default topic "home-assistant" or "homeassistant"? The doku uses both.

### ISSUE THREAD

**Issue by Olaf65** [home-assistant/home-assistant.github.io#27550]
### Feedback

The examples in the doku use both topics. So what is the default auto discovery topic?

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2023.5.4

**Comment by jbouwh** [comment]
Should be `homeassistant`.

**Comment by jbouwh** [comment]
Attached PR should solve the confusion as it improves the documentation and updates the examples.
