### ISSUE TITLE
invisible barrier

### ISSUE THREAD

**Issue by Seva44** [home-assistant/home-assistant.github.io#27566]
### Feedback

I was creating a dashboard for a tablet, and I came across such a problem:
All the cards I created ended up in an invisible barrier. This barrier prevented the cards from expanding horizontally
![Снимок](https://github.com/home-assistant/home-assistant.io/assets/96764780/5712ab25-7d78-4f00-90fd-77643082f9d2)

### URL

https://www.home-assistant.io/dashboards/masonry/

### Version

2023.5.4

**Comment by frenck** [comment]
Thanks for submitting feedback @Seva44 👍 

However, you have submitted documentation feedback. There is no amount of documentation we can change to make software behave differently.

If you wanted to submit a feature request, please use the "Feature request" section in our community forums instead.


Thanks! 👍 

../Frenck
