### ISSUE TITLE
Imap documentation is not clear it does not support insecure connections

### ISSUE THREAD

**Issue by emanteuf** [home-assistant/home-assistant.github.io#27576]
### Feedback

Migrating from the depreciated imap integration fails, manual configuration fails with an error "failed to connect".  The previous integration supported "verify_ssl: false", however the new integration has no such option and the documentation hints at the ability to select ciphers, however it only says you must have "advanced mode" enabled in "user settings".  Before you disable the depreciated implementation, the new implementation should include all functionality of the previous one.

### URL

https://www.home-assistant.io/integrations/imap/

### Version

2023.5.4

**Comment by emanteuf** [comment]
After looking at previously closed issues, I see #83568 issue was closed without resolving the certificate mismatch error.  I use an internal IMAP server and the SSL cert should not be verified.

**Comment by jbouwh** [comment]
> After looking at previously closed issues, I see #83568 issue was closed without resolving the certificate mismatch error. I use an internal IMAP server and the SSL cert should not be verified.

I am sorry your configuration (without SSL) does not work at the moment. #83568 was opened before I became code owner. In most cases an IMAP server supports secure connection. Recently we added support for older ciphers.

What you ask is technically a feature request, but since `imap_content_sensor` is deprecated this was not announced. I do not agree that the documentation is incomplete, but it could be better.

**Comment by emanteuf** [comment]
Thanks.  One other observation is that the depreciation notification now shows that my configuration was already migrated even though the migration failed.  I'm not sure if the settings were migrated to somewhere new or if it's just marked as being migrated.  I feel like this should allow you to do the migration again once verify_ssl option is implemented.

**Comment by jbouwh** [comment]
The config entries where migrated. With this disabling verify ssl was not supported. If has failed, the user can remove the config entries and recreate them manually.

**Comment by jbouwh** [comment]
Closing this issue as support is clear now. The imap client will support for insecure connections from HA Core 2023.6.0
