### ISSUE TITLE
Setup: failed connection

### ISSUE THREAD

**Issue by dutch-kay** [home-assistant/home-assistant.github.io#27573]
### Feedback

My Roborock : S7 maxV
Roborock App 4.0.16

i get a connection to my Roborock account but not to the device. 
Do I have to reconnect the device?

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.5.4

**Comment by Lash-L** [comment]
Are you using the Roborock account?

Is the device reachable from home assistant? Is it in the same network?

**Comment by dutch-kay** [comment]
Hi Lash,
I use the Roborock account. 
Strangely, the integration shows a completely different Ip than the device has in the mink. 192.168.178.x instead of 192.168.179.x
I use two Wi-Fi Networks (2,4 & 5 GHz) withe the same Wi-Fi Name.

**Comment by dutch-kay** [comment]
I now know what the mistake is. The IP belongs to my mother's released Roborock. But it is in a completely different house and is released for remote maintenance. The app takes the first Roborock it finds.

**Comment by Lash-L** [comment]
Yeah - right now it tries to set up all devices and if any device fails to setup, then the whole thing fails.

That should be changed in the next release.

**Comment by Lash-L** [comment]
@home-assistant close
