### ISSUE TITLE
ZWave SmartStart incorrect documentation

### ISSUE THREAD

**Issue by mnl1121** [home-assistant/home-assistant.github.io#27570]
### Feedback

In the ZWave JS documentation under adding a device, it suggests using SmartStart and selecting "Scan QR code". Scan QR code is no where on my Home Assistant UI. I have the latest HA version (2023.5.4) installed.

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2023.5.4

**Comment by MartinHjelmare** [comment]
Scanning a QR code will only be available if you're accessing Home Assistant via https due to webbrowser restrictions.

**Comment by mnl1121** [comment]
Oh! That's helpful to know. Documentation should reflect that. Thank you!
________________________________

**Comment by MartinHjelmare** [comment]
We chose not to explain this detail but rely on the UI to guide the user:
https://github.com/home-assistant/home-assistant.io/pull/26873#discussion_r1163754666

**Comment by mnl1121** [comment]
@MartinHjelmare, the UI guides the user to include a device, but it does not explain anything about why SmartStart is not an available option. You should absolutely explain that you need to use HTTPS to access your HA in order for the SmartStart option to display. The comment you linked is maybe due to a lack of understanding between regularly including a device and to use SmartStart to include a device? Either way, it needs to be explained, please add to the documentation.

**Comment by MartinHjelmare** [comment]
If you added the device successfully, why do you need to know about SmartStart?

**Comment by mnl1121** [comment]
I don't understand the pushback here. It's not explained in the documentation why an option is being advertised, in the documentation, but not all users will have the option. I will inevitably include more Zwave devices in my network too. I'm sure others have come across it and figured that HA doesn't support SmartStart. SmartStart is a very convenient feature of Zwave 700 series that most new devices are compatible with.

**Comment by MartinHjelmare** [comment]
Adding details to the documentation is not free, it has a cost. While some users may appreciate the details, other users will find it less easy to read, follow and understand the documentation.

I'll ask for a second opinion.

**Comment by mnl1121** [comment]
By cost you mean readability, not financial I presume. Please do get a second opinion, it's an important piece of information and can be easily explained in a single bullet point. The documentation will still be very readable.

**Comment by MartinHjelmare** [comment]
We've discussed the topic and came to the conclusion that it should be the controller that is limiting here, since we do show the QR code option also on non https, just not with camera scan option.

SmartStart requires a 700 series controller.

We're adding this to the docs:
https://github.com/home-assistant/home-assistant.io/pull/27589

**Comment by mnl1121** [comment]
Makes sense, glad this is being added to the docs, thank you!
________________________________
