### ISSUE TITLE
Can I use a custom icon?

### ISSUE THREAD

**Issue by poldim** [home-assistant/home-assistant.github.io#27597]
### Feedback

The documentation for icons only elaborates of use of and contribution to MDI.  There is no mention of how to use an SVG file in my local directory.

### URL

https://www.home-assistant.io/docs/frontend/icons/

### Version

2023.5.4

**Comment by frenck** [comment]
> There is no mention of how to use an SVG file in my local directory.

It is correctly not documented, as there is no such option. 😀 

There is no native support for custom icons.

../Frenck
