### ISSUE TITLE
Glitch on integrations detail page with new design

### ISSUE THREAD

**Issue by mib1185** [home-assistant/home-assistant.github.io#27595]
### Feedback

With the new design, there is a glitch on the integration detail view in portrait orientation on a mobile (_Samsung Galaxy S22 in my case_)

![Screenshot_20230530_235243_Chrome](https://github.com/home-assistant/home-assistant.io/assets/35783820/b9ccf662-d32d-44d4-9e34-1ab1addbc126)

### URL

https://new.home-assistant.io/integrations/smartthings

**Comment by mib1185** [comment]
issue still persists

**Comment by klaasnicolaas** [comment]
@c0ffeeca7

**Comment by mib1185** [comment]
issue still persists

**Comment by mib1185** [comment]
Issue still persists. Just to note, it seems to only affects integration pages which have no square brand icons

**Comment by mib1185** [comment]
nope, nor stale

**Comment by frenck** [comment]
We are currently not proceeding with the new design yet. So closing this one for now. Maybe it becomes relevant again later (but I doubt that).

../Frenck
