### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by Wim-Zoeteman** [home-assistant/home-assistant.github.io#27594]
### Feedback

Installation went easy about a year ago, okay.
After I have changed the password on Growatt (shine), for safety matters. I can't find information how to change the password in the HomeAssistant Integration.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.5.4

**Comment by frenck** [comment]
>  I can't find information how to change the password in the HomeAssistant Integration.

There is no such thing documented indeed, glancing at the codebase for this integration learned me that it doesn't support changing passwords.

../Frenck
