### ISSUE TITLE
Unused speaker?

### ISSUE THREAD

**Issue by hidden0** [home-assistant/home-assistant.github.io#27609]
### Feedback

The M5 Stack atom echo has a speaker, and I see "responses" in the logs, but there is no audio output or media player exposed to home assistant.

### URL

https://www.home-assistant.io/projects/thirteen-usd-voice-remote/

### Version

2023.5.4

**Comment by 2m** [comment]
Yup, noticed that same issue. I am using Home Assisant Cloud for the voice assistant.

If I use Voice Assistant from the Assist pop-up, then I can hear the responses.

**Comment by jason-curtis** [comment]
This seems similar to https://github.com/home-assistant/core/issues/93280 . I'm getting inconsistent/choppy voice responses from the Echo.

**Comment by 2m** [comment]
The Voice Assistant firmware was recently changed to not play the TTS response through the speaker: https://github.com/esphome/firmware/pull/30/files#r1243234201
