### ISSUE TITLE
Zehnder ComfoAir Q - not all functions available

### ISSUE THREAD

**Issue by JeePee1981** [home-assistant/home-assistant.github.io#27600]
### Feedback

When using the ComfoAir Q integration, I noticed that not all functions provided by the Zehnder app are available via the home assistant integration. I don't think I configured anything wrong.

I found this module that can do more and I was wondering if those features can be added to this integration?
https://github.com/michaelarnauts/aiocomfoconnect

I would like to be able to set bypass, boost, away mode, speed, ... on a schedule based on different sensors around the house.

### URL

https://www.home-assistant.io/integrations/comfoconnect/

### Version

2023.5.4

**Comment by JeePee1981** [comment]
The issue is still relevant, can it be looked at?

**Comment by michaelarnauts** [comment]
This custom component (https://github.com/michaelarnauts/home-assistant-comfoconnect) uses the aiocomfoconnect library and supports more control and sensors.

There still is an issue I would like to fix that the entity id's are different, but I didn't find the time to do this yet.

I also would like to have this component replace my old one in Home Assistant, but I'm not sure how to proceed with this.

**Comment by JeePee1981** [comment]
That was what I was looking for a way to integrate the new one into HA.
Thanks for the update, I'll try it out.
