### ISSUE TITLE
Add Brazil as a country

### ISSUE THREAD

**Issue by pipowww** [home-assistant/home-assistant.github.io#27610]
### Feedback

Hello friends, do we have any idea when this will be available to Brasil ?

Thank you. 

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2023.5.4

**Comment by fredrike** [comment]
No, it depends on Daikin and the type of module you have. Perhaps it already is supported.

**Comment by fredrike** [comment]
@home-assistant close
