### ISSUE TITLE
Device tracking in iCloud integration

### ISSUE THREAD

**Issue by ifuchs** [home-assistant/home-assistant.github.io#27620]
### Feedback

I installed the iCloud integration and it finds the 3 devices in my account but it does not show other devices that I can see in Find My iPhone that are shared from my wife's account. Is there a way to add these to the iCloud integration?

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
