### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by humusking** [home-assistant/home-assistant.github.io#27624]
### Feedback

Thankyou so much for the timer info. I am very new to ha and not particularly savvy. What would the script look like if I wanted to set a timer to turn off on my bathroom light after being on for 10min, but only during certain hours. For example between 10pm and 6am everyday. Currently the bathroom light gets triggered by a sonoff sensor when my wife walks out of the bedroom but sometimes if she stays longer than 5 min, turns off the light manually, it turns on again when she returns to the bedroom. If that happens I need the light to turn off if it has been on for more than 10 min.
Also given I was this timer to execute all the time which config file should I use? Much appreciated. Jonathan 

### URL

https://www.home-assistant.io/integrations/timer/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
