### ISSUE TITLE
Hayward Aqualogic - Integration Request

### ISSUE THREAD

**Issue by BakerLabs** [home-assistant/home-assistant.github.io#27632]
### Feedback

First the I really appreciate the work that went into this integration. I have been using it for a couple years now. I have an RS-485 to Ethernet adapter. In addition to the data coming form the integration I have build additional sensors that monitor solar panel temp, solar panel out put temp, air temp and water temp.

REQUEST
Is it possible to get the VALVE 3 status into the integration?  Valve three is typically configured for Solar Heat. It would be nice to know when the solar heat is active.

I'm happy to help in anyway I can. I you need me to test something or collect any voltage readings.

### URL

https://www.home-assistant.io/integrations/aqualogic/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
