### ISSUE TITLE
Display as Sprinkler?

### ISSUE THREAD

**Issue by mitchfle** [home-assistant/home-assistant.github.io#27630]
### Feedback

HI, Thank you so much for your work.  Would it be possible to add a sprinkler to this list?

### URL

https://www.home-assistant.io/integrations/switch_as_x/

### Version

2023.5.4

### Additional information

HI, Thank you so much for your work.  Would it be possible to add a sprinkler to this list?

**Comment by frenck** [comment]
Home Assistant doesn't have sprinkler entities, so no :)

../Frenck
