### ISSUE TITLE
Please enter connection settings of your ESPHome node.

### ISSUE THREAD

**Issue by yltsa** [home-assistant/home-assistant.github.io#27638]
### Feedback

Hi, I cannot go through this instruction.  It stops in the ESPHome integration.

_`Please enter connection settings of your node.... Can't connect to ESP. Please make sure your YAML file contains an 'api:' line.`_

I have tried the ip address of the home assistant, but it does not work-..

### URL

https://www.home-assistant.io/projects/thirteen-usd-voice-remote/

### Version

2023.5.5

**Comment by c0ffeeca7** [comment]
Thank you for reaching out. 
We use this GitHub issue tracker specifically for documentation issues, not for providing support.
For support, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).
