### ISSUE TITLE
VOIP Integration. Link to promised tutorial is dead

### ISSUE THREAD

**Issue by dierochade** [home-assistant/home-assistant.github.io#27641]
### Feedback

on the documenation page (https://www.home-assistant.io/integrations/voip/) is written:

See [the tutorial](https://www.home-assistant.io/projects/worlds-most-private-voice-assistant) for detailed instructions.

The link is dead, though...

### URL

https://www.home-assistant.io/integrations/voip/

### Additional information

hope the tutorial exists... :-D

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @dierochade :+1:
