### ISSUE TITLE
Tibber Integration doesn´t work.

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#27645]
### Feedback

Fehler
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

newest Dietpi
newest Home Assistant

### URL

https://www.home-assistant.io/integrations/tibber/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Hi there @postfach-gebraeunt 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
