### ISSUE TITLE
Unclear instructions: Port, Path, API Token

### ISSUE THREAD

**Issue by creckord** [home-assistant/home-assistant.github.io#27646]
### Feedback

> Path has to match!

Others have already commented on the path, but to reiterate: Path has to match what, exactly?

> remove the first forward slash from the API token, as the app will prepend one

Which API token? There are no API tokens involved that I can see

> Pick the protocol Ecowitt, and put in the ip/hostname of your Home Assistant server.

Especially for those coming from the HACS integration, it should be mentioned that the HA port is needed here as well (8123 usually). The previously configured port (e.g. 4199) won't work.

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2023.5.4

**Comment by creckord** [comment]
FWIW, this popup didn't appear the first time I set up the integration:

![image](https://github.com/home-assistant/home-assistant.io/assets/393429/de4fb44f-4314-40fb-91b4-237e49481730)

Maybe because I migrated from the HACS integration? I did this:

1. Fixed the HACS integration with the line 21 code fix, so it could start
2. Restarted
3. Removed my station in Settings / Devices and Services
4. Deleted the integration in HACS
5. Restarted
6. Added the new integration

At that point, I got a popup with the general setup instructions, and after confirming it, the integration just appeared.

After removing and re-adding it, I got a confirmation dialog instead (Are you sure you want to add...) and then the popup from this screenshot.

**Comment by penright** [comment]
I did finally get it to work. 
Couple of lessons I learned through experimenting. 
I was using the Windows PC app.
I will include a from the Ecowitt setup program screenshot of it that finally did work. 
The instruction said to leave off the leading '/'. Maybe that depends on the app you use to set up the gw1000. For the windows version, you have to leave it on.



![image](https://github.com/home-assistant/home-assistant.io/assets/21042538/d3b72a9e-4dce-4f1b-8a05-ad7638668022)

**Comment by Entropy512** [comment]
Similarly, if you're using WSView Plus it should be left on.

Only showing the webhook endpoint during initial setup is horrible UI design.  The webhook endpoint should be displayable from an existing entry in the event of, for example, a hardware replacement or a device reset (my GW1100 was acting extremely strangely and I was forced to reset it)
