### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by cciitt1** [home-assistant/home-assistant.github.io#27659]
### Feedback

Is it possible for you to update to V4?

### URL

https://www.home-assistant.io/integrations/vasttrafik/

### Version

2023.5.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by martinklintefelt** [comment]
The V2 vasttrafik API will be shut down on November 30, 2023. Migration to the V4 vasttrafik API is necessary to continue operation of the vasttrafik integration. It will be an issue on December 1th.
https://github.com/vasttrafik/api-pr-docs/blob/main/docs/MIGRATION.md
