### ISSUE TITLE
Is is possible to set inverter power limit of STP inverter from Home Assistant?

### ISSUE THREAD

**Issue by stigkildegaard** [home-assistant/home-assistant.github.io#27650]
### Feedback

Hello,

I would like to ask if it is possible to dynamically set the inverter power limit for an SMA-STP8.0-3AV-40 from Home Assistant?

I live in Denmark where the power cost changes every hour according to the prices on Nordpool. In the summer time we routinely have hours with negative power price where we are charged money for supplying power to the grid. During these hours I would like to limit the production from my SMA-STP8.0-3AV-40 so that it exports little or no power to the grid. I got as far as calculating the setpoint for the power limit based on power prices and measured power consumption in my home before I realized that the stp...inverter_power_limit in the SMA integration is a sensor and not a number that can be set.

I use a similar approach to dynamically control the charging current of my ABB Terra ev charger, but in the OCPP integration that I use with the charger the current limit is a "number" and not a sensor. 

Thank you in advance for any feedback.

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
