### ISSUE TITLE
Philips 65OLED807 not responding

### ISSUE THREAD

**Issue by sossienl** [home-assistant/home-assistant.github.io#27657]
### Feedback

I have my HOST as my IP address (local, same netwrok: 192.168.x.x) and selected version 6, but it gives an error. "Failed to Connect".

When I go through my browser, I'm able to connect and see some data:
https://192.168.x.xxx:1926/system

It only connects through HTTPS (although my browser warns me, but HTTP is not giving a response).
I see in the system response it's indeed version 6. I tried all other options as well, no luck.

### URL

https://www.home-assistant.io/integrations/philips_js/

### Version

2023.5.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
