### ISSUE TITLE
SEASON Integration no longer works after OS and Core Updates

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#27658]
### Feedback

https://github.com/home-assistant/home-assistant.io/issues/27503

@
THIS IS NOT A CUSTOM INTEGRATION  --  It is found under ADD INTEGRATION

![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/a5f0f9d7-3d06-438f-9318-bfbddd2d3bb6)

### URL

https://github.com/home-assistant/home-assistant.io/issues/27503

### Version

2023.5.4

### Additional information

After applying the latest OS and CORE updates -- this integration which has worked for MONTHS - no longer works.

**Comment by ludeeus** [comment]
That IS a custom integration.
You have it in your `custom_conponents` directory.
