### ISSUE TITLE
Great integration, could be upgraded!

### ISSUE THREAD

**Issue by SgtFoose** [home-assistant/home-assistant.github.io#27669]
### Feedback

I love this little integration. I have a dynamic energy contract and use the info to determine my power consumption during the day. Dynamic prices mean I have to pay when the price is negative (I have solar panels). I'd love to see an automation added so I can do "if energy price below zero, turn on Relay/Unit X". In my mind I would buy an electric boiler and power it with a relay when the prices are negative. This way, my solar panels do not need to be switched off during peek solar-power hours.

### URL

https://www.home-assistant.io/integrations/energyzero/

### Version

2023.5.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by klaasnicolaas** [comment]
The community forum is the place to share automations that meet your needs 😉
