### ISSUE TITLE
Trying to get working since it stopped in March 2023

### ISSUE THREAD

**Issue by Dave-Jones-1963** [home-assistant/home-assistant.github.io#27668]
### Feedback

I have tried to remove and re-install this but it fails to even register when I put in my details, just sits spinning away - Having logged onto the OVO web site I can get both daily and half-hourly (electricity only) data using the links https://smartpaymapi.ovoenergy.com/usage/api/daily/{account number in here}?date=2023-06
https://smartpaymapi.ovoenergy.com/usage/api/half-hourly/{account number in here}?date=2023-06-05
So I know that the data is available but the OVO integration just doesn't seem to be working currently

It all was working - I had data in HA until back in March but now I have removed it I guess the data is lost - no matter but I would like the integration to work - especially if we can get the half hourly electricity data - seems there is no half hourly Gas though!

Kindest regards

Dave

### URL

https://www.home-assistant.io/integrations/ovo_energy/

### Version

2023.5.4

**Comment by timmo001** [comment]
It looks like OVO have changed their API.

I will try and find time to look into this

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by Dave-Jones-1963** [comment]
Many thanks, this is now working and can close
