### ISSUE TITLE
Change request

### ISSUE THREAD

**Issue by pa1okz** [home-assistant/home-assistant.github.io#27665]
### Feedback

The current Home Assistant implementation to fetch data from the Growatt Servers implies a practical but véry limiting effect:

Apparently, HA fetches the Growatt server each 10 minutes to which acces has to be granted. Such logins at the Growatt servers are limited to 200 logins maximum per 24 hours. The following message was received from Growatt support, as I was excluded from my account daily:

_Dear Mischa,
 
Our monitoring group checked your account, we found that your account was logged in every 10 minutes. Our app can only be logged in a maximum of 200 times per day. Please don't log in more than 200 times.
Please see the attached figure for your account information.
 

Met vriendelijke groet/Kind regards,

Yalin Wang

Growatt New Energy B.V.

P: +31(0) 85 040 9967
E: [service.nl@ginverter.com](mailto:service.nl@ginverter.com)_
W: [www.ginverter.com](http://www.ginverter.com/)_

Request: Please include a flexible fetch period in the configurationto obtain data from Growatt.

Other people experiencing the same:
https://community.home-assistant.io/t/locked-out-of-shinephone-account/566039

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.5.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
