### ISSUE TITLE
addon container capabilities problems

### ISSUE THREAD

**Issue by lfarkas** [home-assistant/home-assistant.github.io#27666]
### Feedback

in the addon configuration the [docs](https://developers.home-assistant.io/docs/add-ons/configuration) said:
```
privileged	list		
Privilege for access to hardware/system. Available access: BPF, DAC_READ_SEARCH, IPC_LOCK, NET_ADMIN, NET_RAW, PERFMON, SYS_ADMIN, SYS_MODULE, SYS_NICE, SYS_PTRACE, SYS_RAWIO, SYS_RESOURCE or SYS_TIME.
```
while in my uptodate supervisor i see this in the log:
```
23-06-06 14:13:09 WARNING (SyncWorker_4) [supervisor.store.data] Can't read /data/addons/git/a3656363/netbird/config.yaml: expected Capabilities or one of 'DAC_READ_SEARCH', 'IPC_LOCK', 'NET_ADMIN', 'NET_RAW', 'SYS_ADMIN', 'SYS_MODULE', 'SYS_NICE', 'SYS_PTRACE', 'SYS_RAWIO', 'SYS_RESOURCE', 'SYS_TIME' @ data['privileged'][2]. Got 'BPF'
```
so it seems docs list:
- BPF
- PERFMON

but addon config do not except this while these docker capabilities are valid ones. so which is the valid the docs or what is the supervisor said?

### URL

https://developers.home-assistant.io/docs/add-ons/configuration

### Version

2023.5.4

**Comment by frenck** [comment]
It seems like you want to report an issue whoever you have submitted end-user documentation feedback instead. Please report issues with the Supervisor in the Supervisor issue tracker.

Thanks 👍 

../Frenck
