### ISSUE TITLE
Similar to #26395 - Instructions are really not instructions

### ISSUE THREAD

**Issue by t9001** [home-assistant/home-assistant.github.io#27687]
### Feedback

I am NOT running a "supervised" install. 
afaik I'm running a vnailla install on an rPI 64. 

All of a sudden I see 
<img width="583" alt="Screenshot 2023-06-07 at 07 10 17" src="https://github.com/home-assistant/home-assistant.io/assets/28175857/de7ef289-12db-4df6-bcd8-dd40b076a4b3">

Clicking "Learn More" takes me to a page which has no useful information for me.

Just like #26395
> "If the systemd-resolved service is not running or disabled, enable and start it."
Is not very useful. Please, tell how to install, enable and start it instead. Most of these pages are missing actual help, they are just stating what I already know (=I have problem). Maybe even start with how to check if you have it or not.

The answer given there about a supervised install isn't relevant because I'm not running a supervised install.

A link to how to fix this on a regular install would be very useful.

### URL

https://www.home-assistant.io/more-info/unsupported/systemd_resolved/

**Comment by agners** [comment]
I think this can show up when an HAOS update fails. That is not really an intended outcome, so it is not documented as such.

What Home Assistant OS are you running (according to Settings > About)? Did you try to upgrade recently?

**Comment by t9001** [comment]
> I think this can show up when an HAOS update fails. That is not really an intended outcome, so it is not documented as such.
> 
> What Home Assistant OS are you running (according to Settings > About)? Did you try to upgrade recently?

Thank you.
Currently 2023.5.4 
Looks like I had upgraded from 2023.5.2 a couple of weeks ago. I think it went ok, I only saw this error today.

**Comment by agners** [comment]
I meanr the operating system specifically.

**Comment by t9001** [comment]
My bad, I read it too quickly.
OS 10.2
I don't remember whan I updated, probably about two weeks ago when it was released.
