### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by dbuggz** [home-assistant/home-assistant.github.io#27699]
### Feedback

I'm using DB Browser to look at the database, hoping to find a way to delete the multiple 'binary_sensor.motion_xxx' (etc) that I'm getting from OpenMQTTGateway.
The database tables seem to have many more columns than documented.

### URL

https://www.home-assistant.io/docs/backend/database/

### Version

2023.5.4

### Additional information

Documented in HA docs:
CREATE TABLE states (
	state_id INTEGER NOT NULL,
	domain VARCHAR(64),
	entity_id VARCHAR(255),
	state VARCHAR(255),
	attributes TEXT,
	event_id INTEGER,
	last_changed DATETIME,
	last_updated DATETIME,
	created DATETIME,
	context_id VARCHAR(36),
	context_user_id VARCHAR(36), context_parent_id CHARACTER(36), old_state_id INTEGER,
	PRIMARY KEY (state_id),
	FOREIGN KEY(event_id) REFERENCES events (event_id)
)

DB Browser finds:
CREATE TABLE states (
	state_id INTEGER NOT NULL, 
	entity_id VARCHAR(255), 
	state VARCHAR(255), 
	attributes TEXT, 
	event_id INTEGER, 
	last_changed DATETIME, 
	last_updated DATETIME, 
	old_state_id INTEGER, 
	attributes_id INTEGER, 
	context_id VARCHAR(36), 
	context_user_id VARCHAR(36), 
	context_parent_id VARCHAR(36), 
	origin_idx SMALLINT, last_updated_ts FLOAT, last_changed_ts FLOAT, context_id_bin BLOB, context_user_id_bin BLOB, context_parent_id_bin BLOB, metadata_id INTEGER, 
	PRIMARY KEY (state_id), 
	FOREIGN KEY(event_id) REFERENCES events (event_id) ON DELETE CASCADE, 
	FOREIGN KEY(old_state_id) REFERENCES states (state_id), 
	FOREIGN KEY(attributes_id) REFERENCES state_attributes (attributes_id)
)

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by dbuggz** [comment]
I was not asking for support, just noting that the documentation for the database is out of date, since there are numerous extra fields.

**Comment by marcelhoogantink** [comment]
I can confirm that the documentation is old, and NOT updated.
So this is an issu for the database documentation!!

**Comment by fliespl** [comment]
@klaasnicolaas can you reconsider opening this one? Database documention is months away from current structure, so it's indeed an issue.

**Comment by fliespl** [comment]
Still relevant :)

**Comment by dbuggz** [comment]
still needs action.
