### ISSUE TITLE
Intent Clarification Required

### ISSUE THREAD

**Issue by User873902** [home-assistant/home-assistant.github.io#27698]
### Feedback

It was not immediately clear to me from the documentation that this integration is exclusively for use in the conversational "Assist" function in Home Assistant as a Voice Assistant. 

I was hoping to use this integration as a call service in an automation to pass a daily briefing from home assistant to Palm2, with a prompt requesting textual variance/styling. I would then pass the response to the Google Cloud Say TTS service and cast the mp3 to home speakers.

Please provide clarity in documentation.

### URL

https://www.home-assistant.io/integrations/google_generative_ai_conversation/

### Version

2023.6.0

**Comment by tronikos** [comment]
With 2023.7 it's possible to do what you described. Not sure how to improve the documentation. I basically copied the one from https://www.home-assistant.io/integrations/openai_conversation/. Do you want to edit both pages? Maybe link to https://www.home-assistant.io/integrations/conversation/ in both of these pages?

**Comment by User873902** [comment]
Yes agree. I had submitted the request before 2023.7, but now that it is possible, I don’t think the clarity is required. Sorry for the trouble.

**Comment by tronikos** [comment]
@home-assistant close
