### ISSUE TITLE
Feature request: allow "state_not" in the alert integration

### ISSUE THREAD

**Issue by lymanbuttler** [home-assistant/home-assistant.github.io#27700]
### Feedback

Currently, the Alert integration lets you set a state which, if true, causes the alert to trigger. Suppose I have a Z-Wave device that has a bunch of entities and one of them is something like "Hardware status: OK". I can't know what it will say when it's not OK. Maybe it will be "Problem", or "Fault", or "Not OK", or "On Fire". I'd like to be able to set an alert that triggers if the entity status is anything other than "OK".

### URL

https://www.home-assistant.io/integrations/alert/

### Version

2023.5.4

**Comment by lymanbuttler** [comment]
I know the currently recommended way to do this is by creating template sensors, but this is not ideal and can result in a great deal of YAML clutter

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
