### ISSUE TITLE
How to setup the map feature

### ISSUE THREAD

**Issue by drkui** [home-assistant/home-assistant.github.io#27705]
### Feedback

I'm trying to figure out how to setup a map dashboard component and I'm not able to do it.

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.6.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
