### ISSUE TITLE
problem with header

### ISSUE THREAD

**Issue by skallis** [home-assistant/home-assistant.github.io#27709]
### Feedback

the problem is that  in my code i have the header of one of my catrs that in vertical stack card and dont appear

### URL

https://www.home-assistant.io/dashboards/vertical-stack/

### Version

2023.6.0

### Additional information

type: vertical-stack
cards:
  - type: custom:swipe-card
    parameters:
      spaceBetween: 8
      scrollbar:
        hide: false
        draggable: true
        snapOnRelease: true
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.t_offset_room_a
            name: Κουζίνα
          - entity: sensor.compensation_climate_thermostat_current_temperature
            name: Διάδρομος
          - entity: sensor.thermometer_living_room_temperature
            name: Σαλόνι
        name: Θερμοκρασία
        hours_to_show: 12
        points_per_hour: 60
        average: true
        show:
          name: true
          legend: true
          icon: true
          labels: true
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.thermometer_living_room_humidity
            name: Σαλόνι
        name: Υγρασία
        hours_to_show: 12
        points_per_hour: 10
        average: true
        show:
          name: true
          legend: true
          icon: true
          labels: true
  - type: custom:tabbed-card
    style: |
      :host {
        --mdc-theme-primary: black;
        --mdc-tab-text-label-color-default: white;
        --mdc-typography-button-font-size: 10px;
      }
    tabs:
      - label: Mitsubishi
        icon: mdi:thermostat
        card:
          type: custom:simple-thermostat
          entity: climate.mitsubishi
          show_header: true
      - label: Dehumidifier
        icon: mdi:air-humidifier
        card:
          type: vertical-stack
          cards:
            - type: humidifier
              entity: humidifier.41781441858546_humidifier
              show_header: true
            - type: entities
              entities:
                - entity: select.41781441858546_fan_speed
                - entity: switch.41781441858546_power
                - entity: select.41781441858546_water_level_set

**Comment by frenck** [comment]
Hi there @skallis 👋 

It seems like you want to report an issue with an Home Assistant dashboard, however, you have submitted documentation feedback instead. Please report issues with dashboards here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
