### ISSUE TITLE
Wrong city

### ISSUE THREAD

**Issue by bey0099** [home-assistant/home-assistant.github.io#27712]
### Feedback

hello, i live in Braga  (portugal) 

but there is another place called "bragança" also in portugal.
then i receive unsafe state from braganca if there is no alarm to Braga...
also receiveid alternate state between the two.
Can it be corrected? can we use a city code instead a name to prevent this kind of issues?

thanks

Best regards

### URL

https://www.home-assistant.io/integrations/meteoalarm/

### Version

2023.6.0

### Additional information

my config in home assistant is:
platform: meteoalarm
country: "portugal"
province: "braga"
language: "pt"

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
