### ISSUE TITLE
Speedtest page doesn't describe what entity to update to change speed check intervals

### ISSUE THREAD

**Issue by iamkarlson** [home-assistant/home-assistant.github.io#27725]
### Feedback

I was looking for a service to manually trigger speed test and I found nothing (HA doesn't show any services starting with speedtest or anything related). Looking in the documentation for check intervals it says to use `update_entity` to change frequency interval - but doesn't say what entity.

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2023.6.0

**Comment by frenck** [comment]
> but doesn't say what entity.

Any entity provided by the speedtest integration...

../Frenck

**Comment by jason-curtis** [comment]
Sorry if we're being daft, but can you provide step by step instructions here @frenck ? I'm looking at the entities and it's not clear how I would disable the hourly test or change the interval.
![image](https://github.com/home-assistant/home-assistant.io/assets/3341011/10e512a3-f863-4356-b021-29cc042cf904)

The docs say: 

> By default, a speed test will be run every hour. You can disable polling using system options and use the update_entity service to automate the speed test frequency.

I'm not sure what "system options" refers to. HASS has quite a lot of options, and none of them that I can find are for disabling polling. I have been able to trigger speed tests on demand using `update_entity`, but I haven't been able to disable the hourly test.

**Comment by rohankapoorcom** [comment]
Here's an example: https://github.com/home-assistant/core/issues/85831#issuecomment-1406306717
