### ISSUE TITLE
Service for backup seems documented different from actual implementation

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/home-assistant.github.io#27727]
### Feedback

Documentation says the service is `backup.create`

But the actual developer UI says `hassio.backup_full` or similar for partial 

Confusing

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2023.6.0

**Comment by KennethLavrsen** [comment]
Ping the bot

**Comment by KennethLavrsen** [comment]
Still wrong

**Comment by KennethLavrsen** [comment]
Ping

**Comment by KennethLavrsen** [comment]
Ping

**Comment by frenck** [comment]
You are mixing up integrations.

The page you are linking too is from the `backup` integration, which isn't available/used on Supervised or HAOS installations.

You are looking for: https://www.home-assistant.io/integrations/hassio

../Frenck
