### ISSUE TITLE
Pip installation is not compatible

### ISSUE THREAD

**Issue by Routhgen** [home-assistant/home-assistant.github.io#27735]
### Feedback

The newest Rasbian, latest default Python is 3.9.2 -> means that 2023.6.0 cannot be even found.
Installation of older hass is fine but still complains about Python version.

In the case of self-compaling newer Python 3.10.12 is the installation not possible.
Dependicies are not resolvable even pip is upgraded.
libbz2 - not found, rust outdated
updating RUST is not possible due to other dependencies.

Conclusion: 2023.6.0 version is not compatible with Rasbian witout major manual changes.
Docker is out of the discussion at all.

Can you cover prereq. for installation on Rasbian and also update the pip installation so its working? Thanks

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.6.0

**Comment by frenck** [comment]
> Can you cover prereq. for installation on Rasbian and also update the pip installation so its working? Thanks

The documentation is pretty clear about this:

![CleanShot 2023-07-08 at 11 58 44](https://github.com/home-assistant/home-assistant.io/assets/195327/b9c45bdb-962c-44da-8287-9bf710505b8d)

We have no intent to add specific instructions for Raspbian.

../Frenck
