### ISSUE TITLE
Important info about api for free acoubts missing

### ISSUE THREAD

**Issue by Darkyputz** [home-assistant/home-assistant.github.io#27733]
### Feedback

Hello...

I was fighting with this integration for some time now and the documentation is missing the dateil, that as a free account at tomorrow,  your data fields are restricted to the core section, meaning that ait quality is unavailbale und other values.
Also important to mention would ve the fact that the sensors get created in HA but as disabled items and that they need to be enabled to be seen/executed in HA.

Hope you will find time to add this info, i was nit permitted to do so.

Thx 

### URL

https://www.home-assistant.io/integrations/tomorrowio/

### Version

2023.6.1

**Comment by lymanepp** [comment]
Please write proposed doc changes and I'll create a PR.

**Comment by Darkyputz** [comment]
Hello...Was the mail directed to me, the requester?Will sure do...was just not sure by looking at the list of people in the header
-------- Original message --------From: lymanepp ***@***.***> Date: 6/9/23  13:52  (GMT-05:00) To: "home-assistant/home-assistant.io" ***@***.***> Cc: Darkyputz ***@***.***>, Author ***@***.***> Subject: Re: [home-assistant/home-assistant.io] Important info about api for
  free acoubts missing (Issue #27733) 
Please write proposed doc changes and I'll create a PR.

**Comment by lymanepp** [comment]
Yes

**Comment by Darkyputz** [comment]
Hello and sorry for the wait...

 

Life got inbetween.

The Climacell/tomorrow info page states:

 

The integration currently assumes you are using a free account so the max requests per day is 100 (the refresh interval is calculated such that you should only use up around 90% of the quota).

 

This info is fine dandy but is leading user into the assumption, that they just get the full load of info tomorrow could provide.

The free account is limited to the core weather info which excludes the air quality, UV info, road risk and so on.

We should def include that into the disclaimer/info section

On top of that, it should be mention, that the integration does download, nowcast, hourly and daily by default.

The page AND the integration config page in HA do sound like, this would be an option.

Very misleading.

So my suggestion would be this:

“

The integration currently assumes that you are using a free account which limits the max requests per day to 100 (the refresh interval is calculated such that you should only use up around 90% of the quota).

While using the free account(determined by the api key provided in the config screen), the weather information offered from tomorrow is limited to the CORE components and does not include air quality or other detail info.

“

And instead of: Supported Forecast Types

Please do: Automatically provided forecast types

 

Thx a lot and let me know if you think it should be phrased different

**Comment by lymanepp** [comment]
I incorporated your suggestions into the docs and submitted PR https://github.com/home-assistant/home-assistant.io/pull/27768
