### ISSUE TITLE
Event Creation is a Little Unclear

### ISSUE THREAD

**Issue by splineGear** [home-assistant/home-assistant.github.io#27748]
### Feedback

1. The process of creating a new event in the Homeseer settings is a little vague. For example, it's not clear exactly which words to use on the HA plugin configuration when requesting an event for a doorbell press. For motion this seems to be clear, i.e. just use the word 'motion'.
2. In the Doorbird app itself, there seems to be a somewhat common issue where the HTTP callback is not enabled because the schedule for it is by default set to never. Enabling this requires some specific keypresses on the Doorbird app and is not captured in the documentation.

### URL

https://www.home-assistant.io/integrations/doorbird/

### Version

2023.6.1

**Comment by mnl1121** [comment]
I'm also very confused as to how to use events. What are the event names? Are they predefined or do we name them? It says "somebody_pressed_the_button" is one, where do we define this? In the app I've defined it but then the URL would be Home Assistant's username:password and URL path? 

Documentation needs to be fully fleshed out.

**Comment by mnl1121** [comment]
This issue is still relevant.

**Comment by nisnu** [comment]
Is there any update on this issue?

**Comment by mnl1121** [comment]
This is still a relevant issue, need an update.
