### ISSUE TITLE
Intent script docs update

### ISSUE THREAD

**Issue by carryonrewardless** [home-assistant/home-assistant.github.io#27745]
### Feedback

Change
text: We have {{ states.sensor.temperature }} degrees
to

text: We have {{ states('sensor.temperature') }} degrees

### URL

https://www.home-assistant.io/integrations/intent_script/

### Version

2023.6.1

**Comment by carryonrewardless** [comment]
Bump. Small update needed.

**Comment by frenck** [comment]
This was adjusted in #27871
