### ISSUE TITLE
Dashboard - History Graph Card - sum of data points per time interval

### ISSUE THREAD

**Issue by aurorus86** [home-assistant/home-assistant.github.io#27746]
### Feedback

Hello There!

Would like to request an ability to sum multiple data sources please, if not already available.

I’ve been using this dashboard to report my electricity solar power and use over a 24 hour period. Aim is to manage my power use to be within my solar power. My IoT power switches/meters I have can only report wattage (W) and not wattage-hours (Wh) so I can’t use the default Energy dashboard.

I’ve attached a screenshot of what my card looks like now.

Let me know if any questions.

Thanks!

### URL

https://www.home-assistant.io/dashboards/history-graph/

### Version

2023.6.1

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/55990167/5e5d3f63-067b-426a-986a-4d196847c5f9)

**Comment by c0ffeeca7** [comment]
Thank you for reaching out!
This GitHub issue tracker is used specifically to track documentation issues, not to provide support or tracking feature requests.

- To suggest a feature, try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
- For support, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Maybe this integration is of interest to you: [Riemann sum integral](https://www.home-assistant.io/integrations/integration/)
