### ISSUE TITLE
No options on "instalación" dropdown

### ISSUE THREAD

**Issue by AlbertORoura** [home-assistant/home-assistant.github.io#27744]
### Feedback

I wasn't able to install airzon cloud integration on my home assistant because, after introducing my credentials, the second step don't show me any option in dropdown.
![Screenshot_2023-06-10-23-32-19-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/home-assistant/home-assistant.io/assets/34156077/52d9f2c3-420f-4d72-8135-c39a55b3577d)

### URL

https://www.home-assistant.io/integrations/airzone_cloud/

### Version

2023.6.1

**Comment by Noltari** [comment]
Hi @AlbertORoura,

Can you provide more information about your specific Airzone device?
I suspect that it's neither an Aidoo nor a Flexa...

**Comment by frenck** [comment]
Hi there @AlbertORoura 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by AlbertORoura** [comment]
Hi @frenck thank you very much for your time.

Sorry for the mistake. I followed the question mark link to create this issue. Maybe It is wrong.
