### ISSUE TITLE
Does not seem to cover flow rate

### ISSUE THREAD

**Issue by bashers222** [home-assistant/home-assistant.github.io#27763]
### Feedback

This wiki entry covers water **consumption**, but not **rate of usage**. similar to the age old argument confusion between Power (Watts) and Total Energy (kWh)
In the device class page it lists WATER and VOLUME, but not FLOWRATE
<html>
<body>

SensorDeviceClass.WATER | L, gal, m³, ft³, CCF | Water consumption
-- | -- | --

</body>
</html>

<html>
<body>

SensorDeviceClass.VOLUME | L, mL, gal, fl. oz., m³, ft³, CCF
-- | --

</body>
</html>

My current entity is using litres per minute, as derived from the very popular [blog](https://www.pieterbrinkman.com/2022/02/02/build-a-cheap-water-usage-sensor-using-esphome-home-assistant-and-a-proximity-sensor/) mentioned in your wiki.

This is currently erroring as **flow rate** is not defined from what i can see and flow rate seems to be mentioned plenty of times in the feature request.
Is this planned to be added?

### URL

https://www.home-assistant.io/docs/energy/water

### Version

2023.4.1

**Comment by karwosts** [comment]
There is not currently any real support for water flow rate. There is a current architectural discusson about adding it:

https://github.com/home-assistant/architecture/discussions/915

I don't know what specifically is erroring? You should be able to make water tracking work even without this.
