### ISSUE TITLE
Dashboard casting scale

### ISSUE THREAD

**Issue by programista4** [home-assistant/home-assistant.github.io#27779]
### Feedback

Hello,

would be great if we could set scale of dashboard casting. If I want cast just temperature in my bedroom to Google Hub fonts are too small. I've tried "card mod" addon and changed font size but still casting is fixed and Google Hub shows temperature but very small digits. The rest of screen is empty.

Kind Regards
Lucas

### URL

https://www.home-assistant.io/integrations/cast/

### Version

2023.6.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
