### ISSUE TITLE
prusalink integration connection failing

### ISSUE THREAD

**Issue by fabianmuehlberger** [home-assistant/home-assistant.github.io#27797]
### Feedback

When adding PrusaLink integration and providing Host name API-Key, the connection fails

* Prusa Mini FW version 4.4.1 
* HA 2023.6.1, OS 10.2
* Prusa Link web works correctly with the same API-Key
* There is no additional message besides "connection failed"

![image](https://github.com/home-assistant/home-assistant.io/assets/56475821/5061fb3c-cb7a-4e1a-948f-12c3e4cf0293)
****

In the [documentation](https://www.home-assistant.io/integrations/prusalink/) I can not find any additional information regarding host naming or how to make it work.

### URL

https://www.home-assistant.io/integrations/prusalink/

### Version

2023.6.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
