### ISSUE TITLE
Wrong configuration linked / installed

### ISSUE THREAD

**Issue by telepath** [home-assistant/home-assistant.github.io#27798]
### Feedback

The link to github in the article (https://github.com/esphome/media-players/blob/main/m5stack-atom-echo.yaml) does not seem to be the configuration that's actually installed, instead https://github.com/esphome/firmware/blob/main/voice-assistant/m5stack-atom-echo.yaml seems to be installed.

I'd really like to know how to install https://github.com/esphome/media-players/blob/main/m5stack-atom-echo.yaml with the media player support, but could find no information on that and had no luck with the esphome addon, since that mostly creates error messages and has abysmal documentation.

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2023.6.1

**Comment by jesserockz** [comment]
https://esphome.github.io/media-players/

**Comment by c0ffeeca7** [comment]
Thank you for the catch! @telepath

**Comment by frenck** [comment]
fixed in #27832
