### ISSUE TITLE
Where to add the QNAP / Where to see the sensor Data

### ISSUE THREAD

**Issue by skorpion1298** [home-assistant/home-assistant.github.io#27800]
### Feedback

Hello :)
I´ve ran through your setup process but I cant figure out how to see the sensor on my Integrations / Panel. Where do I add this Sensor to see the Graphs etc.? Would be nice if you´d add this to your Documentation.

### URL

https://www.home-assistant.io/integrations/qnap/

### Version

2023.6.1

**Comment by frenck** [comment]
Thank you for reaching out. The question you ask are general questions, not specific related to this integration. Integrations create devices & entities that can be used.

Integration set up manually in YAML is not showing up on the integrations dashboard; only UI-managed ones do.

If you are in need of more support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
