### ISSUE TITLE
Unclear Documentation 

### ISSUE THREAD

**Issue by scripter13** [home-assistant/home-assistant.github.io#27809]
### Feedback

Please update the Motion Blinds documentation to clearly show that the API key needs to be pulled from the ORIGINAL app, and not the Motion Blinds app, unless using a motion blinds hub. 

I created a motion blinds account and attempted to follow the provided documentation, but kept receiving "AccessToken error". On a wim, I decided to try similar steps in the 3 Day Blinds app, and was able to get a functional API key. 

Documentation needs to be updated to direct the user BACK to the original app to get an API key. I work in IT and this took me over 24 hours of fiddling and googling to figure out. 

### URL

https://www.home-assistant.io/integrations/motion_blinds

**Comment by starkillerOG** [comment]
Documentation has been adjusted in the mean time.
Thanks for the feedback.

If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.
