### ISSUE TITLE
Controlling Home Assistant over the ATOM Echo

### ISSUE THREAD

**Issue by zipzagster** [home-assistant/home-assistant.github.io#27825]
### Feedback

1) The Atom Echo has two buttons, not one.  'Press and hold the button" needs to be clarified.  
2) Holding the large button does nothing. It must be released to get the flashing blue light. 
Never seen a green light, only received errors so far. Perhaps you have linked to the wrong github

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2023.6.1

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @zipzagster :+1:
