### ISSUE TITLE
Can't link to ... Contact ... error

### ISSUE THREAD

**Issue by randysaz928** [home-assistant/home-assistant.github.io#27823]
### Feedback

It should be added to check the OAUTH credentials in the Application Credential store.  Setup-Devices and Entities- 3dot menu-application credentials.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2023.6.1

### Additional information

found answer at [https://community.home-assistant.io/t/keep-getting-can-t-link-to-myproject-error-setting-up-nest-integration/492348/9]

**Comment by allenporter** [comment]
It is in the trouble shooting with a screenshot

**Comment by allenporter** [comment]
See "Resolving mismatched OAuth Client ID". I'm going to close since this is there.
