### ISSUE TITLE
Add unique_id option to ping sensors

### ISSUE THREAD

**Issue by fgonza2** [home-assistant/home-assistant.github.io#27821]
### Feedback

Hi, i need a ping sensor with aunique_id so i can modify it through UI and for consistency with other binary sensors.   any reason this is not supported yet?

### URL

https://www.home-assistant.io/integrations/ping/

### Version

2023.6.1

**Comment by gjohansson-ST** [comment]
Probably no one has added it yet. 
Please submit to the core repository and not here as it's only issues in the documentation which this isn't.
