### ISSUE TITLE
Set custom theme as the default in configuration.yaml for all users

### ISSUE THREAD

**Issue by nagtegaal** [home-assistant/home-assistant.github.io#27849]
### Feedback

Could someone please write a how to set your default custom theme from within configuration.yaml? So HA starts with that, instead of the other default one?

I am trying this for a couple of months now, but it doesn't seem to work.

### URL

https://www.home-assistant.io/integrations/frontend/

### Version

2023.6.2

**Comment by frenck** [comment]
> Could someone please write a how to set your default custom theme from within configuration.yaml? So HA starts with that, instead of the other default one?

There is no such setting, hence you could find it. You can set one in the Home Assistant UI in the Configuration menu.

../Frenck
