### ISSUE TITLE
Document usage/implications/problems of large coiot_update_period

### ISSUE THREAD

**Issue by DaniEll-AT** [home-assistant/home-assistant.github.io#27840]
### Feedback

To reduce network activity and data-points in HA Recorder, i want to set [coiot_update_period](https://shelly-api-docs.shelly.cloud/gen1/#settings) of all my Gen1 Shelly Devices to 60.
The documentation of the shelly integration does not state, if there are any negative consequences caused by this change.

Please enhance the documentation:
- What is the maximum value allowed, for the device not to become unavailable in Home Assistant?
- Anything else to consider?

### URL

https://www.home-assistant.io/integrations/shelly

### Version

2023.06.2

**Comment by thecode** [comment]
There is no limitation by Home Assistant. Any value that will work with the device will work in Home Assistant.
We are not documenting options that are only to be used by advanced users, the place for this is our [Community Forum](https://community.home-assistant.io) or our [Discord chat server](https://discord.gg/c5DvZ4e).
