### ISSUE TITLE
Request to expand groups to multiple entity types within 1 group

### ISSUE THREAD

**Issue by LCMilstein** [home-assistant/home-assistant.github.io#27846]
### Feedback

The new Helper UI for groups is great, but too limited compared to the old style groups, specifically because new groups only allow for grouping the same entity types together (not 2 different entity types into 1 group). 

Examples of Groups Home Assistant Users now have more difficulty setting up (or can't):

1. Exterior Doors - In setting up alerts and other automations when any exterior doors are open becomes more challenging with new style groups as exterior doors being open may contain concepts from binary sensors (contact sensors), locks (smart locks), and covers (garage doors), but can now not exist within a single group.
2. Lights - In setting up a group to simplify things like turning off all lights, we would now first need to use "switch as x" to reallocate all switches that control lights to become "light" entities and then set up the group, whereas before we could just add both switches and lights to a single group.
3. Zigbee Extenders - Zigbee Extenders can take the form of switches, lights, and more, but having a group to see if any are offline (which creates havoc in the system) has been very helpful. Unfortunately, it can't be set up in the helper UI.

This could all be solved for by either allowing multiple entity types, supporting CERTAIN combinations of entity types within a single group, or creating a new type of helper group structure for these purposes.

### URL

https://www.home-assistant.io/integrations/group/

### Version

2023.6.2

**Comment by MartinHjelmare** [comment]
You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum. Thanks!
