### ISSUE TITLE
Searching for documentation

### ISSUE THREAD

**Issue by madebywitteveen** [home-assistant/home-assistant.github.io#27859]
### Feedback

Hi,

it is hard to find all the possible keywords and commands and options to be used in the code editor in the horizontal stack button card.
Where can I find that ?

thanks

### URL

https://www.home-assistant.io/dashboards/horizontal-stack/

### Version

2023.6.2

**Comment by c0ffeeca7** [comment]
Thank you for reaching out! 

All the card types are listed in the side-TOC.
When you select the one you are interested in, you can see it's name in the YAML example.
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/d5fa1706-c28f-41d0-bf2b-f2def8fd84d5)

![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/d951fe1f-fd56-4a87-93fd-ceb9de14c3ed)

**Comment by madebywitteveen** [comment]
Hi Thanks,

I'm not looking for the type of cards, I'm looking for all the programming keywords and options which can be used INSIDE one card (horizontal stack)

How to customize the horizontal stack?

Can't find the right page?!

where is a list of all commands which can be used in side the card ?
how do you call those words before the ':' ?? 

**type:** horizontal-stack
**title:** Lights
cards:
  **- type:** picture-entity
    image: /local/bed_1.png
    entity: light.ceiling_lights
  **- type:** picture-entity
    image: /local/bed_2.png
    entity: light.bed_light

**Comment by c0ffeeca7** [comment]
Inside the horizontal stack card you can show other cards. The horizontal stack card keeps cards next to each other on the dashboard. "The words before the :" as you call it, depend on the type of cards you want to stack.
 
For example: 
If you want to show a map, then you can specify a value for the configuration variable _geo_location_sources_. 
But if you want to show a shopping list, _geo_location_sources_ would not apply. Which configuration variables you can use is specified in the documentation of each card type.  

Screenshot showing the configuration variable documentation of the [map card](https://www.home-assistant.io/dashboards/map/).

![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/19b273a0-a2d0-4ff4-bd25-6982199cb447)

**Comment by madebywitteveen** [comment]
starting to get it; all the cards (types) are nested and each one has it's own specific configuration variables ? check ?

thus; what I was trying to do;
inside a horizontal-stack use the button card, that worked.
after that I was trying to do: give the buttons a solid color (for the off and on state)
green, red, blue & white corresponding with my led lights.

but the 'button' card does not have a off-state color option.

conclusion: what I was trying to do is not going to work ?!

thanks

H

**Comment by c0ffeeca7** [comment]
Correct, you can only configure the variables that are available for a specific card.

But this GitHub issue tracker is used specifically to track documentation issues, not to provide support.
For support, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or checkout the [forum](https://community.home-assistant.io/).

**Comment by madebywitteveen** [comment]
thanks, will do !
