### ISSUE TITLE
Flux Documentation references 'sunset_time' though the variable used is 'stop_time'

### ISSUE THREAD

**Issue by TheRealBernie** [home-assistant/home-assistant.github.io#27854]
### Feedback

While looking over the documentation, the variable 'sunset_time' is referenced, though now listed in the Configuration Variables section nor in the Example Configuration. The document should be updated to 'stop_time' instead of 'sunset_time'.

### URL

https://www.home-assistant.io/integrations/flux/

### Version

2023.6.2

**Comment by dyfrgi** [comment]
This should be re-opened as it is still a problem.
https://github.com/home-assistant/core/blob/c17f08a3f543e63da66d5a10156776ee150c5f11/homeassistant/components/flux/switch.py#L53 shows that the flux switch is using `stop_time`.
