### ISSUE TITLE
Developer Tools

### ISSUE THREAD

**Issue by Moosbrugger** [home-assistant/home-assistant.github.io#27864]
### Feedback

Perhaps I'm looking in the wrong place but I don't see any mention of Statistics anywhere in the Developer Tools documentation.

Also, there are what seem to me to be twp bugs on the Developer Tools/Statistics page: the search field is wildly inaccurate: it will show some entities some times & not others.  It won't consistently search for a substring in an entity_id.  Often refreshing the page will change the output the results of a search.

And in my experience the alphabetization of Issues is never accurate.  It's as though there were hidden characters or some unobvious pre-search going on. Blocks of one issue will be broken by a few mentions of another issue & then continue & then be broken again.

### URL

https://www.home-assistant.io/docs/tools/dev-tools/

### Version

2023.6.2

### Additional information

This problem preceded 2023.6.

**Comment by dannytsang** [comment]
Good point on the statistics docs. I will take a look into that.

I don't know the answer to the inconsistent searches.

**Comment by c0ffeeca7** [comment]
Thank you for fixing the documentation, @dannytsang!

@Moosbrugger: Thank you for bringing this up!
Regarding the issue with the search field: please open an issue in the [frontend issue tracker](https://github.com/home-assistant/frontend/issues/new/choose).

**Comment by Moosbrugger** [comment]
Thanks,  [dannytsang](https://github.com/dannytsang) & [c0ffeeca7](https://github.com/c0ffeeca7)
