### ISSUE TITLE
Most of the documentation is so badly written

### ISSUE THREAD

**Issue by IT-Gipsy** [home-assistant/home-assistant.github.io#27861]
### Feedback

I understand that Home Assistant is an (almost) free platform for "home automation" and that maintaining proper documentation is somewhat of a Pain... 

A Proper "manual" does not just describe but adds SAMPLES that are NOT using all kinds of information that needs to be changed, but ACTUAL samples. 

I am absolutely not a "technically challenged person (I work in IT) but 80% of the "explanations in the docs are bullocks to me.

I am looking for a (possibly paid) alternative for Home assistant, that I use mainly for monitoring anyway.
The "automations" are so badly designed and so needlesly made complex that I rather use "the software that came with the devices" 

### URL

https://www.home-assistant.io/integrations/notify_events/

### Version

2023.6.2

**Comment by papajojo** [comment]
Hello @IT-Gipsy. I'm sorry, but I'm a little confused: is your message targets specifically at the Notify.Events plugin or at the whole HomeAssistant?

If it's about the Notify.Events plugin, please accept our apologies for poor description and let me help you with your configuration issues.

**Comment by IT-Gipsy** [comment]
HiMy name is Harpert and thanks for the prompt reply.In this case it's about the notify service.I don't quite understand why there is no notification that is done using the app.That would be by far the easiest way (just send a message using the Android app) But as that is in fact only a "web page" this might be a little challenge.I have added the "notify" and "token" to my configuration.yamlNow I would like to be able to create a notification if certain criteria are met.PIR sensor (Zigbee)activatedOnly if door is closed (Zigbee)And if time is between 07.00 and 22.00And if my phone is not present.(The latter is not that much important)Preferably I receive a notification on my Phone.Other issueMy Reolink Video Doorbell needs a firmware upgrade according to Home Assistant.However... In the Reolink software it says that my doorbell is "up to date" and I can't even manually override.Last issue.I keep on have issues with GroWatt.I have 2 inverters that both report via the cloud. However, the one I installed last is no longer populated in Home Assistant, but in the shine phone app and when logging in via my laptop the extra plant is visible.The "api" does not work, due to the number of requests, i get blockedThanksHarpert+31653188100--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 18/06/2023, 16:56 Alexey Kustov ***@***.***> wrote:

   
  Hello @IT-Gipsy. I'm sorry, but I'm a little confused: is your message targets specifically at the Notify.Events plugin or at the whole HomeAssistant? 
  If it's about the Notify.Events plugin, please accept our apologies for poor description and let me help you with your configuration issues.

**Comment by papajojo** [comment]
Yep, seems like a lot of issues :\

I'm not sure I can help you with all of them, but let's try to start with "notifications". As I understand you're saying that you've set up your configuration.yaml as it was described on plugin installation page but haven't receive any notifications. 

Let's try to handle it:
1. Could you please tell me your Notify.Events login?
2. Could you also send me your configuration.yaml file to [support@notify.events](mailto:support@notify.events) (please make sure there's no sensitive information) so I could check that configuration is correct.
3. Have you tried to run your automation manually? (to check there's no new notifications appeared at the Notify.Events side)
4. Have you checked the Home Assistant system logs? Is there some error reports when you're initiating your instance or trying to run automation)
