### ISSUE TITLE
Copy and Paste NEVER NEVER NEVER works on ANY scripts provided. 

### ISSUE THREAD

**Issue by outawhack** [home-assistant/home-assistant.github.io#27865]
### Feedback

 No matter what, when you try to run the code provided, you get "Message malformed: extra keys not allowed @ data['service']". Can't ANYONE EVER provide a bullet proof example that actually works. How can you learn this if even the examples don't work?

### URL

https://www.home-assistant.io/voice_control/using_tts_in_automation/

### Version

2023.6.2

**Comment by c0ffeeca7** [comment]
For me, this works when I add this under **Actions**.

Where exactly are you trying to paste this? Could you specify?

In any case, you can do the entire setup in the UI, as described in steps 1-8.  The YAML shown is the outcome of the changes done in the UI.
