### ISSUE TITLE
Tesla Powerwall Integration Password

### ISSUE THREAD

**Issue by mac252381** [home-assistant/home-assistant.github.io#27873]
### Feedback

I just added the Tesla Powerwall Integration.  When signing in, it gives help information that the password is on the gateway for newer powerwalls and for older powerwalls it is the last 5 digits of the serial code.  I have a newer powerwall and the password to use for the integration is the last five characters of the Gateway password, rather than the entire password.  If you can make this addition to the integration documentation it will hopefully be helpful to the next person.  Thanks for all of your efforts with Home Assistant!

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2023.6.2

**Comment by michaelsargent** [comment]
I second the motion.
![image](https://github.com/home-assistant/home-assistant.io/assets/11484460/09165eb7-8b24-46d6-ae4b-30c007ffaba2)
