### ISSUE TITLE
what configuration file?

### ISSUE THREAD

**Issue by RichBrew** [home-assistant/home-assistant.github.io#27872]
### Feedback

at the beginning of the page... 'You only need to add this to your configuration file...'
what file? where is it? it does no good to know what to put in this magic file if i have no clue what file it is or where to find it.

### URL

https://www.home-assistant.io/integrations/http/

### Version

2023.6.2

**Comment by frenck** [comment]
It is linked on the page you are commenting on:

![CleanShot 2023-06-19 at 12 03 08](https://github.com/home-assistant/home-assistant.io/assets/195327/441958ff-e34f-4e2c-a3f7-0d552e8c0f57)

That link will bring you to a dedicated page about our configuration files.

../Frenck
