### ISSUE TITLE
Plans to support Switcher Light?

### ISSUE THREAD

**Issue by Kili4ka** [home-assistant/home-assistant.github.io#27880]
### Feedback

Hi Guys,

Are there any plans to support the Switcher Light series?
https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/switcher-light-sl01/

### URL

https://www.home-assistant.io/integrations/switcher_kis/

### Version

2023.6.2

**Comment by thecode** [comment]
This repository is used for documentation issues, not for providing support.  The underling package https://github.com/TomerFi/aioswitcher doesn't support these devices.
