### ISSUE TITLE
Multiple sensors with one REST request: fail!

### ISSUE THREAD

**Issue by damib** [home-assistant/home-assistant.github.io#27889]
### Feedback

The configuration example showing how to extract multiple values from a dictionary without flooding the REST service is not working. It still execute a request for each sensor, flooding the service. I'm using version 2023.1.7

![image](https://github.com/home-assistant/home-assistant.io/assets/11184250/93e9c5d7-7651-4666-89b7-93c4276b3ffc)

The workaround I'm trying to implement is this one: https://community.home-assistant.io/t/multiple-sensors-in-one-rest-call/101842

### URL

https://www.home-assistant.io/integrations/sensor.rest/

**Comment by epenet** [comment]
> I'm using version 2023.1.7
Did you try to upgrade?

**Comment by frenck** [comment]
Hi there @damib 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by damib** [comment]
Yes I know, the problem is that the documentation is currently WRONG and it is misleading users.
Non existent features should not be documented.

**Comment by epenet** [comment]
> Non existent features should not be documented.

It is not a non-existent feature. AFAIK it works fine on the latest version.
