### ISSUE TITLE
NWS Wind Direction

### ISSUE THREAD

**Issue by WedHumpDay** [home-assistant/home-assistant.github.io#27893]
### Feedback

Low priority and probably designed this way. 

Would be great to show a compass style or direction by N/NE/E/SE/S, etc.

The NWS integration only shows number values.

### URL

https://www.home-assistant.io/integrations/nws/

### Version

2023.6.2

**Comment by MatthewFlamm** [comment]
This is probably a better issue for the core repo, but I'm not sure if it can be moved across repos by an admin.

Are you talking about the weather entity or a sensor entity?  If the latter, the integration gives the values as NWS provides them.  One benefit here is that you can more easily track the wind direction over time using a chart with a numerical value.  If a string based value is common from other weather integrations, it might makes sense to add this sensor to NWS integration as well.

If it isn't added, you could use a template sensor to transform the value into a string based direction.

**Comment by kamiyo** [comment]
Yes, in addition, there are Lovelace cards that also display it in cardinal
terms if you feed it the degrees.

My vote is for keeping it in degrees.

**Comment by WedHumpDay** [comment]
Thanks for the feedback everyone.. We can close the ticket.
Now, on to the hunt for the Lovelace card.
