### ISSUE TITLE
sensor.solaredge_lifetime_energy has no data

### ISSUE THREAD

**Issue by ryklebaron** [home-assistant/home-assistant.github.io#27895]
### Feedback

I connected my solaredge to HomeAssistant trough the use of the api. I get two entities (out of 21) that are not disabled by the integration, or so it says on the integration if I navigate to the entities of the integration.

The two entities are:
   1. sensor.solaredge_lifetime_energy
   2. sensor.solaredge_current_power

Where the second one, sensor.solaredge_current_power is getting data as expected, the first one has no data at all. No errors in the logs, just no data (status unknown).

I provided 2 screenshots of both entities. and 1 screenshot of all the disabled entities (the other 19) which are disabled by the integration it self (not know the reason) 

Please help me get this working again. Dont know where to look for more intensive logs. 
 
![opera_xNZU0VLuB8](https://github.com/home-assistant/home-assistant.io/assets/19972280/594836b0-1a51-422a-899a-a9e43c31de9a)
![opera_NJ037mDH7R](https://github.com/home-assistant/home-assistant.io/assets/19972280/13b38d2d-e421-440f-ae83-c9b7e32ed1e0)
![opera_8Sex6QMN20](https://github.com/home-assistant/home-assistant.io/assets/19972280/c5794030-d853-41e9-9fd6-0c622ad370b1)

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2023.6.2

**Comment by frenck** [comment]
Hi there @ryklebaron 👋 

It seems like you want to report an issue with an Home Assistant integration or are seeking for support; however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
