### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by psmoros** [home-assistant/home-assistant.github.io#27898]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@deepakkuma24) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by frenck** [comment]
We have a security.txt file in place in our main `.github` repo, which is checked by GitHub as well:

![CleanShot 2023-06-20 at 21 16 47](https://github.com/home-assistant/home-assistant.io/assets/195327/4d2deeb4-dd95-487e-8cbf-990433b00305)

Anyways, that will link to our main website, which has the contact information where you can reach out for things like this:

<https://www.home-assistant.io/security>

Please use that to responsible disclose a security issue.

Thanks 👍 

../Frenck
