### ISSUE TITLE
Update Switch as 'x' to represent current UI

### ISSUE THREAD

**Issue by andrewf6** [home-assistant/home-assistant.github.io#27904]
### Feedback

The Helper is not called "Switch as X" (any longer?) but "Change Device type of a switch". Can this be updated along with the Manual configuration steps. (I've never used git before and tried, to put in some suggest changes but not sure how to submit these...

### URL

https://www.home-assistant.io/integrations/switch_as_x/

### Version

2023.6.2

**Comment by dannytsang** [comment]
I'm running 2023.7 and when I go to *Settings* > *Devices & Services* > *Helpers* it's still showing as Switch as X.
![image](https://github.com/home-assistant/home-assistant.io/assets/567982/d1a39fae-c684-4aa6-8c46-f9cef7d44994)

**Comment by c0ffeeca7** [comment]
closed by #28128
