### ISSUE TITLE
Multiple gateways

### ISSUE THREAD

**Issue by tnagels** [home-assistant/home-assistant.github.io#27909]
### Feedback

I am considering a setup with multiple Adams as I have two opentherm circuits. From the documentation it is no clear if multiple gateways are supported. Can you add this information?

### URL

https://www.home-assistant.io/integrations/plugwise/

### Version

2023.6.2

**Comment by bouwew** [comment]
@tnagels have you read the documentation: https://www.home-assistant.io/integrations/plugwise/
There is states: Repeat the above procedure for each Smile gateway (i.e., if you have an Adam setup and a P1 DSMR you’ll have to add two integrations). This process is the same when you have two Adams.

**Comment by tnagels** [comment]
Ok, that clarifies things. I read the documentation, but the phrasing did not make it clear to me that two identical units could be added. It may just be me so I'll close this issue. Thanks for the reply.
