### ISSUE TITLE
PrusaLink integration works with MK4

### ISSUE THREAD

**Issue by ksheyman** [home-assistant/home-assistant.github.io#27916]
### Feedback

The PrusaLink integration documentation states that it only works with the Prusa Mini. However I've tested it and it appears to work just fine with the new Prusa MK4.

### URL

https://www.home-assistant.io/integrations/prusalink/

### Version

2023.6.2

**Comment by c0ffeeca7** [comment]
Thank you, @ksheyman :+1:
