### ISSUE TITLE
Documentation of System Monitor outdated

### ISSUE THREAD

**Issue by Burn-In** [home-assistant/home-assistant.github.io#27910]
### Feedback

As the handling of customized sensors in configuration.yaml has changed, the documentation (e.g. examples) is outdated and don't work anymore.
Keyword: command_line

### URL

https://www.home-assistant.io/integrations/systemmonitor

### Version

2023.5.4

**Comment by frenck** [comment]
`command_line` is not `systemmonitor`. You are mixing up integrations.

You can find the documentation of the command line here:

<https://www.home-assistant.io/integrations/command_line>

../Frenck
