### ISSUE TITLE
Failed to restart HA, 'Sunsungtv' from  2023.06.2

### ISSUE THREAD

**Issue by fireblade70** [home-assistant/home-assistant.github.io#27924]
### Feedback

When attempting to restart HA, I get Failed to restart HA, 'Sunsungtv' dialog. I assume its something to do with recent changed in 2023.06.2 with what can be placed in configuration.yaml (as per instructions on samsungtv intergration). Does this need updating to reflect recent changes? How do I get rid of failure?

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2023.6.2

### Additional information

configuration.yaml consists of:
samsungtv:
  - host: #.#.#.#

# being IP address.

**Comment by epenet** [comment]
Indeed YAML configuration has been dropped in https://github.com/home-assistant/core/pull/93392
It would be nice if you could open a PR on "current" branch to resolved this.

**Comment by fireblade70** [comment]
> 

Any update on progress to resolve this issue? I still cannot do quick reboot\restart of Home Assistant.

**Comment by joostlek** [comment]
Last week someone else had this aswell and we figured the problem out (https://github.com/home-assistant/core/issues/96061). Some integrations have registered a schema that shouldn't throw an error, but it still does. Made a fix for it but hasn't been merged yet.

The solution for you is to remove the

```yaml
samsungtv:
   ....
```
from the configuration.yaml, and everything should work as expected. The YAML should be already imported, so you don't lose your device.

**Comment by joostlek** [comment]
Closing since this bug is now fixed in the next release and there is a workaround available for now.
