### ISSUE TITLE
How to turn off Voice Assistant (Assist)?

### ISSUE THREAD

**Issue by luiscampiz** [home-assistant/home-assistant.github.io#27926]
### Feedback

The native Voice Assistant (Assist) can't be turned off, like Alexa and Google Assistant. In this Doc should be the how-to on how to turn off all Voice Assistants.

Thks,

Luis.

### URL

https://www.home-assistant.io/voice_control/troubleshooting/

### Version

2023.6.2

**Comment by frenck** [comment]
We don't have a feature to turn it off. Meaning the documentation is complete at that point.

../Frenck

**Comment by Santanachia** [comment]
![image](https://github.com/home-assistant/home-assistant.io/assets/4628507/8604ad01-6a62-4037-8d73-7a52fac5c3a5)

**Comment by frenck** [comment]
@Santanachia I don't see how that is related to this issue, which has been closed as well.

If you want to report an issue, please open an issue at the right place. For information on where to go see: <https://www.home-assistant.io/help>

Thanks 👍 

../Frenck

**Comment by Santanachia** [comment]
@frenck relation: reason why there should be a possibility to turn it off.

**Comment by frenck** [comment]
Sorry, that makes no sense in terms of documentation feedback. Feel free to raise an feature request in the appropriate places for that.

../Frenck
