### ISSUE TITLE
Shorter intervall for schedule

### ISSUE THREAD

**Issue by rgliese** [home-assistant/home-assistant.github.io#27937]
### Feedback

At the gui configuration there should be a posibility to insert shorter items, then 30 minutes. I think 5 minutes should be perfect

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2023.6.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
