### ISSUE TITLE
Atom Echo button does not capture commands

### ISSUE THREAD

**Issue by bozzobrain** [home-assistant/home-assistant.github.io#27932]
### Feedback

Pressing and holding the button on the Atom Echo does not show any activity. Only after releasing the button, the LED inside flashes blue as a steady pace.

Home Assistant registers the assist in progress and then immediately shows that it is no longer in progress. These records come back to back before the button is released. Trigger for the event occurs on button press. Blue light continues flashing before button press, during hold and after release.

Resetting the device shows no LED lit once booted, then on button press, still no LED until the button is released after first press.

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2023.6.2

**Comment by bozzobrain** [comment]
This was in the logs for button press and holds. 
![image](https://github.com/home-assistant/home-assistant.io/assets/161101/b4168f2f-535c-4ddc-b475-b42a2e273d07)


Tried to program using the ESPHome add device method, full compile was successful.

Here is the history for Assist In Progress.
![image](https://github.com/home-assistant/home-assistant.io/assets/161101/8b3f8464-2954-4c83-989b-b476310db70f)

**Comment by CumpsD** [comment]
Same issue here, newly bought M5, installed via web button. Only flashes blue forever after pressing the button. It also turns on and off instantly in HA

**Comment by CumpsD** [comment]
I can confirm the button itself signals correctly. Pressing it toggles the binary sensor to `on` and it stays on while pressed. Releasing it turns it `off` again. There seems to be something going on with the voice_assistant.starting part

**Comment by CumpsD** [comment]
With VERBOSE logging:

![image](https://github.com/home-assistant/home-assistant.io/assets/1201644/9ab17295-0237-4fd0-8c19-291c9b9e6610)

So the multi_click is doing it's work correctly.

It's just never getting into this part:

```yaml
voice_assistant:
  microphone: echo_microphone
  speaker: echo_speaker
  on_start:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: none
```

**Comment by CumpsD** [comment]
Solved it! My Voice Assistant did not have a text-to-speech and speech-to-text, since I don't have HA cloud. I installed Piper and Whisper as separate docker containers and configured them and now it works.

![image](https://github.com/home-assistant/home-assistant.io/assets/1201644/d5534c50-13b0-487c-817b-f51df73b7f3c)

**Comment by CumpsD** [comment]
Solved it! My Voice Assistant did not have a text-to-speech and speech-to-text, since I don't have HA cloud. I installed Piper and Whisper as separate docker containers and configured them and now it works.

**Comment by bozzobrain** [comment]
Can confirm that after having both Piper AND Whisper installed, and configuring the HA voice assistant to use these services, the issue is resolved. 

Note that when I had Whisper installed and configured but used the text-to-speech engine of Google Translate, I was experiencing the issue.

Original Config
![image](https://github.com/home-assistant/home-assistant.io/assets/161101/469c5fb3-5426-4d24-a8b7-ee7eb07bc6a5)

Functional Config
![image](https://github.com/home-assistant/home-assistant.io/assets/161101/2cf9e463-260a-4cad-9c65-083c7c1f3d5d)

**Comment by bozzobrain** [comment]
To summarize, make sure that both Whisper and Piper are installed and configured to be used by the Voice Assistant service in Home Assistant.
