### ISSUE TITLE
Which version of Debian for supervised install?

### ISSUE THREAD

**Issue by madsdyd** [home-assistant/home-assistant.github.io#27957]
### Feedback

On this page: https://www.home-assistant.io/more-info/unsupported/os it says Debian 11, but this page: https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md says Debian 12.

HA 2023.6.3 complains about 12. Maybe I just upgaded too soon?

BTW: Thanks for providing an excellent project. I am amazed daily!

### URL

https://www.home-assistant.io/more-info/unsupported/os/

### Version

2023.6.3

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/993332/0b110f3d-5e79-405c-8d1d-dfa4bba20a76)

**Comment by frenck** [comment]
We are in the process of upgrading/rolling out Debian 12 support, but that isn't fully completed yet. Last bits are expected to ship the upcoming days.

../Frenck
