### ISSUE TITLE
Initial should be a string

### ISSUE THREAD

**Issue by ric-k** [home-assistant/home-assistant.github.io#27952]
### Feedback

The format for initial is actually a string containing a datetime | time | date. 

### URL

https://www.home-assistant.io/integrations/input_datetime/

### Version

2023.6.2

**Comment by frenck** [comment]
Yes, I am sure what your feedback is?

Looking at the page you commented on, it seem correctly displayed?

../Frenck

**Comment by ric-k** [comment]
Hi Franck,It statesinitial datetime | time | date (optional)I tried initial:  16:30 but this didn't work. I had to make it a string containing a timeinitial: "16:30"So shouldn't it be initial string (optional)string contains the initial value of this input, datetime | time | date depending on has_time and has_date.ThanksRickOn 25 Jun 2023 18:31, Franck Nijhof ***@***.***> wrote:
Yes, I am sure what your feedback is?
Looking at the page you commented on, it seem correctly displayed?
../Frenck

**Comment by frenck** [comment]
> tried initial:  16:30 but this didn't work

That is because of YAML, as in, the YAML boundaries and syntax still apply.

../Frenck
