### ISSUE TITLE
Application Credentials

### ISSUE THREAD

**Issue by ElanHasson** [home-assistant/home-assistant.github.io#27951]
### Feedback

There are no 3 dots nor overflow menu.

### URL

https://www.home-assistant.io/integrations/application_credentials/

### Version

2023.6.2

**Comment by MartinHjelmare** [comment]
Do you have `default_config:` in your configuration.yaml file?

**Comment by ElanHasson** [comment]
@MartinHjelmare 
> Do you have `default_config:` in your configuration.yaml file?

Yes I have that in there. Says do not remove..

**Comment by MartinHjelmare** [comment]
Please post a screenshot of the top of your "Devices & Services" page.
