### ISSUE TITLE
Reporting phenomenon: The waiting time for creating a user after the initial installation is too long

### ISSUE THREAD

**Issue by dell1985** [home-assistant/home-assistant.github.io#27963]
### Feedback

Reporting phenomenon: The waiting time for creating a user after the initial installation is too long, 120 minutes have passed and we are still waiting.
Please help me see where the problem is
Configure nuc memory 16m m.2 1T
thanks

### URL

https://www.home-assistant.io/installation/

### Version

2023.6.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation feedback/suggestions.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
