### ISSUE TITLE
Updating the host IP for the existing integrations

### ISSUE THREAD

**Issue by lathishsundar** [home-assistant/home-assistant.github.io#27961]
### Feedback

It does not have the details to update the host IP for the existing devices. Is there any option ?

### URL

https://www.home-assistant.io/integrations/nfandroidtv/

### Version

2023.6.3

**Comment by tkdrob** [comment]
Devices should be set with DHCP reservation. If they are not, it just won't work after a while. The docs don't speak of how to change the IP because of the first point. Remove the entry and set it up again and set up DHCP for that device. Problem solved.
