### ISSUE TITLE
UniFi Protect local user docs are out of date

### ISSUE THREAD

**Issue by PieyrotToo** [home-assistant/home-assistant.github.io#27964]
### Feedback

I'm in UniFi OS UDM Pro v3.0.20

and there is no option to add a "user" on top right... I guess there is a change in UniFi OS latest version but where can I add that user?

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2023.6.3

**Comment by AngellusMortis** [comment]
@home-assistant close

**Comment by AngellusMortis** [comment]
3.0.20 is an early access version of UniFi OS. Early Access is not supported.

**Comment by AngellusMortis** [comment]
I believe they also have been making it harder to make local users. If the Home Assistant docs are out of date on how to create a user, you should reach out the Ubiquiti community to learn how to make one and then feel free to update the docs on how to do it.

**Comment by AngellusMortis** [comment]
My mistake, 3.0.20 is the latest stable. I just could not find it is the list of stable patch notes. Too many people ask for help with Early Access

**Comment by AngellusMortis** [comment]
@home-assistant reopen

**Comment by AngellusMortis** [comment]
@home-assistant rename UniFi Protect local user docs are out of date

**Comment by PieyrotToo** [comment]
Just found how.
On the left, click "_Admins_", then "_Add New Admin_", then uncheck "_Allow remote control_" therefor it becomes a local user :-)
