### ISSUE TITLE
bmw connected drive, entities become unavailable

### ISSUE THREAD

**Issue by dengke80622** [home-assistant/home-assistant.github.io#27962]
### Feedback

HACS custom integration V20230608.1: https://github.com/bimmerconnected/ha_custom_component/releases/
Update: remove custom integration and issue still exists

Description: 
All BMW entities become unavailable, and become normal after a while. 
Reload integration can temporarily solve this issue but will be "unavailable" again after a while.
Seems there is some update interval for this, 5 or 10 minutes in the screenshot
![image](https://github.com/home-assistant/home-assistant.io/assets/16779356/76a59d61-7b70-403f-ae32-8ad9f003a7e9)
![image](https://github.com/home-assistant/home-assistant.io/assets/16779356/215ebf9d-6d79-4f67-8627-ebe839d536e6)
![image](https://github.com/home-assistant/home-assistant.io/assets/16779356/3a297098-31f2-415a-b970-f43ff7a9a19f)

LOG:
This error originated from a custom integration.

Logger: custom_components.bmw_connected_drive.coordinator
Source: custom_components/bmw_connected_drive/coordinator.py:61
Integration: BMW Connected Drive
First occurred: 14:24:13 (3 occurrences)
Last logged: 14:49:17

Unexpected error fetching bmw_connected_drive-86[PHONE#] data: 'capabilities'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bmw_connected_drive/coordinator.py", line 61, in _async_update_data
    await self.account.get_vehicles()
  File "/usr/local/lib/python3.11/site-packages/bimmer_connected/account.py", line 113, in get_vehicles
    if vehicle_state[ATTR_CAPABILITIES].get("isChargingPlanSupported", False) or vehicle_state[
       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'capabilities'


### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2023.6.3

### Additional information

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest

**Comment by rikroe** [comment]
You posted in the wrong repository - this is the repo for documentation on home-assistant.io.

Usually you would open in home-assistant/core. As you are using the custom component, you cannot do that and have to open in https://github.com/bimmerconnected/ha_custom_component. 
But you can also remove the custom component, there is no difference between it and whats shipped directly with Home Assistant.

**Comment by rikroe** [comment]
@home-assistant close
