### ISSUE TITLE
The "device" section is required for discovery but it is not obvious from the documentation

### ISSUE THREAD

**Issue by lboclboc** [home-assistant/home-assistant.github.io#27989]
### Feedback

The "device" section is needed for config-messages, otherwise home-assistant does not discover the device. I think this information is not very obvious in the documentation.

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2023.6.3

**Comment by raythefourth** [comment]
I recently attempted to follow the configuration documentation, and ultimately posted to the forum to get further help configuring a device with multiple sensor entities. A forum user was very helpful providing the correct syntax and suggesting the use of a script to easily configure multiple sensors for one device. Here's the post with detailed solution:
https://community.home-assistant.io/t/creating-a-device-with-multiple-sensor-entities-via-mqtt-discovery/584372/5

**Comment by jbouwh** [comment]
@reggleston4 Infact, this was corrected in one way that device config can be used for yaml config too.
See: https://github.com/home-assistant/home-assistant.io/pull/27927
Also it is not strictly needed to have a device mapping for discovery.

**Comment by jbouwh** [comment]
If then incorrectly is documented that a `device` mapping is needed for discovery, then let me known so that I can adjust it.

**Comment by lboclboc** [comment]
I have not figured out how it must be done. By adding a "device" to the config message the device shows up, but not the sensor even though I send meassurements. Only the device shows up. In fact if you try the exact examples in the document (https://www.home-assistant.io/integrations/mqtt#mqtt-discovery) , it does not work either - at least not for me. My ESPhome-device also uses mqtt and it shows up ok with all sensors.

**Comment by jbouwh** [comment]
Example config payload:

```json
{
  "~": "homeassistant/sensor/DSMR_electicity_meter",
  "uniq_id": "4530xxxxxxxxxxxxxxxxxxxxxxxxx_energy_used_net",
  "name": "Verbruikt (net)",
  "stat_t": "~/dsmr_state",
  "json_attr_t": "~/attr",
  "val_tpl": "{{(value_json.energy_used_net|round(3))}}",
  "dev": {
    "identifiers": [
      "4530xxxxxxxxxxxxxxxxxxxxxxxxx_dsmr"
    ],
    "name": "DSMR_electicity_meter",
    "mdl": "DSMR electicity meter",
    "mf": "Netbeheer Nederland"
  },
  "dev_cla": "energy",
  "stat_cla": "total_increasing",
  "ic": "mdi:counter",
  "unit_of_meas": "kWh"
}
```

**Comment by jbouwh** [comment]
The documentation was updated to make sure discovery is not required to use the `device` mapping.
