### ISSUE TITLE
Ecowitt Leaf Wetness sensor info dont go to homeassistant

### ISSUE THREAD

**Issue by mortenx** [home-assistant/home-assistant.github.io#27983]
### Feedback

Ecowitt Leaf Wetness sensor info dont go to homeassistant

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2023.6.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
