### ISSUE TITLE
Incorrect type. Expected "array"

### ISSUE THREAD

**Issue by SpaceCowboyLive** [home-assistant/home-assistant.github.io#27981]
### Feedback

Got an error message while attempting to apply this integration as follows:
- Incorrect type. Expected "array"
Suspect this integration no longer works as expected or the configuration YAML is confused by the HEX value of the Sensor ID.

### URL

https://www.home-assistant.io/integrations/neurio_energy/

### Version

2023.6.3

### Additional information

![2023-06-26 20_20_15-Home Assistant — LibreWolf](https://github.com/home-assistant/home-assistant.io/assets/5692712/bbde1e33-16f9-466c-9eb0-a533dbc6c181)

**Comment by mong00se007** [comment]
should be formated:

```yaml
sensor:
  - platform: dsefsffsefe
    api_key: fsdfdsf
  ```

  try that. funny was looking for a sollution to a problem but found a solution to yours :)
