### ISSUE TITLE
Configuration is not clear

### ISSUE THREAD

**Issue by laithsaid** [home-assistant/home-assistant.github.io#27980]
### Feedback

It would be very helpful if the documentation includes an example that shows the JSON reply and how to extract single keys of from the reply as sensors.
The documentation mentions json_attributes_path in the example, but there is no information about what it means and how it could be used.

Please read this as asking for help. I wouldn't write to you if I could improve it myself. I would have sent a pull request instead.

### URL

https://www.home-assistant.io/integrations/rest/

### Version

2023.6.3

**Comment by BenoitAnastay** [comment]
Indeed, there is some exemple missing I guess.

The question was asked on the forum 
https://community.home-assistant.io/t/restful-sensor-state-attr-unknow-and-json-attributes-path-solved/373285/2
