### ISSUE TITLE
Relè interni alla centrale

### ISSUE THREAD

**Issue by teamsolutions-github** [home-assistant/home-assistant.github.io#27988]
### Feedback

Ciao a tutti, sono settimane che provo e riprovo ma non trovo un metodo per poter inviare comandi alla centrale da homeasssitant eccitando le uscite relè all'interno della centrale. Qualcuno può aiutarmi ? 
Grazie Ivan

### URL

https://www.home-assistant.io/integrations/risco/

### Version

2023.6.3

**Comment by frenck** [comment]
Sorry, we don't speak this language; If you want to create documentation feedback, please use the English language.

Thanks 👍 

../Frenck
