### ISSUE TITLE
Linking HA with Withings fails

### ISSUE THREAD

**Issue by mrbostad** [home-assistant/home-assistant.github.io#27993]
### Feedback

I have tested some times to add withings into home assistant, and when i try to add, it is stuck on a previous clientid, so when i try to connect, i get "Invalid clientid" how do i reset the "cached" information so i can try with the newly generated clientid and secret (i have saved the information this time, so i will get it right now) i also get "Our servers couldn't reach this URL:
Partner error: Host Unreachable" and i have tried the direct hostname and the nabu casa hostname, none of them works. I have no filtering activated on the NAT`ed port (443)

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2023.6.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
