### ISSUE TITLE
Storing Secrets (secrets.yaml)

### ISSUE THREAD

**Issue by CarlNightingale** [home-assistant/home-assistant.github.io#27996]
### Feedback

Should the secret value be enclosed in quotes? the example given shows them but doesn't mention specifically. It would be a good idea to add a note.

### URL

https://www.home-assistant.io/docs/configuration/secrets/

### Version

2023.6.3

**Comment by frenck** [comment]
That depends on the value. It is a YAML file, and all rules/guides for general YAML use apply.
This is not specific to this page or secrets.

../Frenck

**Comment by CarlNightingale** [comment]
Thanks. Your reply did not answer my  initial question and suggests that any user that wants to make use of the !secret function should also have a good understanding of the YAML rules. In reality, many will not want to get into coding but will be concerned about including private information in their config. A simple statement of when to use quotation marks and when not to in the secrets documentation (that maybe references the YAML rules) would been a real improvement.

**Comment by frenck** [comment]
> Your reply did not answer my initial question and suggests that any user that wants to make use of the !secret function should also have a good understanding of the YAML rules.

We have different guides on that.

> many will not want to get into coding

This isn't code?

> concerned about including private information in their config.

This is not a security or privacy feature in that sense. You are still including private information in your config (regardless if you use secrets.yaml or not).

> A simple statement of when to use quotation marks and when not to in the secrets documentation (that maybe references the YAML rules) would been a real improvement.

That statement makes no sense. It depends on the data type you write down. If it is a string, sure. A boolean or numeric value? Then your suggestion would be harmful.

Please read up on how YAML works, in case you want to work with YAML.

../Frenck
