### ISSUE TITLE
Is there a way to tell if there is a speed test currently running?

### ISSUE THREAD

**Issue by jason-curtis** [home-assistant/home-assistant.github.io#28007]
### Feedback

I've added a button which runs the speed test on-demand but I'm not sure if there's any attribute that I can look at to see whether the test is still running.
I could hack something based on whether `(time button last pressed) > (time of last speed test)` but I'd prefer something explicit.

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2023.6.3

**Comment by frenck** [comment]
Hi!

There is no such thing. You could create it yourself in a way, by using an helper. First set the state of the helper, run the Speedtest, unset the state of the helper. That way the helper becomes your indicator.

../Frenck

**Comment by jason-curtis** [comment]
Ok, is there any way to find out if the speed test has failed or should I just set an arbitrarily high timeout and/or look for transitions to “unavailable”?
