### ISSUE TITLE
ssh access to my router

### ISSUE THREAD

**Issue by SuperCrishna** [home-assistant/home-assistant.github.io#28006]
### Feedback

for security purpose, in my router settings, i have enabled ssh keys only and disabled password. so with the integration of asus router, i cannot put the option to upload my public ssh keys and also i am using a different port number other than 22. is there a way for me to specify my ssh public key and a port number 2022 ? best regards.

### URL

https://www.home-assistant.io/integrations/asuswrt/

### Version

2023.6.3

**Comment by frenck** [comment]
No, that is not possible.

If you want to suggest it as a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
