### ISSUE TITLE
Link for "Configuration" panel is not valid

### ISSUE THREAD

**Issue by FluxCapacitor123** [home-assistant/home-assistant.github.io#28011]
### Feedback

LInk in textl is not valid:
This can be done from the [Configuration](https://my.home-assistant.io/redirect/configuration) panel

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2023.6.3

**Comment by frenck** [comment]
Thanks for reporting this one @FluxCapacitor123 👍 

I've opened up a PR to adjust the documentation to match the current UI.

../Frenck
