### ISSUE TITLE
What type of sensor exactly?

### ISSUE THREAD

**Issue by metawops** [home-assistant/home-assistant.github.io#28018]
### Feedback

I want to configure my energy dashboard as I have a new solar roof.
However, from this documentation page I cannot learn what type of sensor I should select for the PV production.
I have an inverter by SunGrow (very large, worldwide brand – too bad it's not natively supported by HA, btw; but there is a community integration I use). The integration supplies several sensors that report kWh. They differ by their accumulation kind. There's a daily, weekly, monthly, yearly sum.
Or should I select a sensor that return Watt, maybe the current value? Because in the doc page at one point it says "Home Assistant will need to know the amount of **energy** ..." and a bit later you talk about power (W): "To translate this into electrical **power (W)** ..."
So, do I need to select a kWh sensor or a W (or kW) sensor? 
The right answer is given in the dialog that appears when you actually add a sensor. There it says "Pick a sensor which measures solar energy production in either of GJ, kWh, MJ, MWh, Wh." – so why not be that specific on the doc page?
However, that dialog still doesn't say if I have to add a daily, weekly, ... sum or what kind.
It's a bit of a mess ... #sigh 

### URL

https://www.home-assistant.io/docs/energy/solar-panels/

### Version

2023.6.3

**Comment by frenck** [comment]
> So, do I need to select a kWh sensor or a W (or kW) sensor?

`W` makes no sense (and you can't select it). `W` is a unit of power, not a unit of energy. As this is the energy dashboard, you need to select an energy sensor, not a power one.

> The right answer is given in the dialog that appears when you actually add a sensor. There it says "Pick a sensor which measures solar energy production in either of GJ, kWh, MJ, MWh, Wh." – so why not be that specific on the doc page

Is already is? It is an energy dashboard, those are energy sensors.

> However, that dialog still doesn't say if I have to add a daily, weekly, ... sum or what kind.

Any. If it is available to select, it is a viable selection. The energy dashboard will only allow you to select sensors it can use.

> It's a bit of a mess ... #sigh

I'm not agreeing on that part. What part is the messy here? To me it sounds like you are not fully understanding the difference between power and energy.

../Frenck

**Comment by SG-O** [comment]
I fully understand the difference between power and energy and to me this is also confusing and I have the same dilemma. My Deye inverter provides both kWh per Day and kWh total . I'll select the kWh per day for now and see what the dashboard does.

**Comment by frenck** [comment]
> My Deye inverter provides both kWh per Day and kWh total . I'll select the kWh per day for now and see what the dashboard does.

If both are available to select in the energy dashboard, either will work.

../Frenck

**Comment by metawops** [comment]
I see these strange graphs every day/week/month and don't know why. 🤷‍♂️ 
<img width="1347" alt="Screenshot 2023-07-06 at 12 34 04" src="https://github.com/home-assistant/home-assistant.io/assets/376090/1f316d3f-d99b-4b3d-8b00-cf2f0a85ef30">
<img width="1345" alt="Screenshot 2023-07-06 at 12 33 51" src="https://github.com/home-assistant/home-assistant.io/assets/376090/958aaf24-14f3-4546-a525-b42780aa7c4f">
<img width="1344" alt="Screenshot 2023-07-06 at 12 08 50" src="https://github.com/home-assistant/home-assistant.io/assets/376090/19258f82-3fd8-47ee-9f3e-fbc59d4f980d">

A "Solar production" is a solar production, right? So it shouldn't be negative at any time, imho. Maybe the sensor I have for my inverter does weird things. => Some graph/screenshot of how it should look when everything is configured correctly would help, too, in the docs.

**Comment by klaasnicolaas** [comment]
Probably because you set up the wrong entity, which integration is this from?

**Comment by metawops** [comment]
I have a system from SunGrow, "the world’s most bankable inverter brand with over 340GW installed worldwide as of December 2022" (according to their own words). 
Unfortunately, there's no native integration for SunGrow in HA and even more unfortunately they don't seem to offer an API. But fortunately there's MickMake and hier GoSunGrow addon [here](https://github.com/MickMake/HomeAssistantAddons/tree/main/GoSungrow) which I use.

**Comment by klaasnicolaas** [comment]
Then it might be better to create an issue in that project repository, you are in any case not in the right place here.

**Comment by metawops** [comment]
> Then it might be better to create an issue in that project repository, you are in any case not in the right place here.

I know. You asked. 😉
