### ISSUE TITLE
Please enter connection settings of your ESPHome node

### ISSUE THREAD

**Issue by nickshew** [home-assistant/home-assistant.github.io#28016]
### Feedback

When attempting to install ESPHome on Home Assistant vis Settings/Devices & Services - Add Integration - ESPHome, a dialogue box is presented requiring a Host And Port.

The documentation gives no information about how to fill this information out.

Background:
Sonoff NSPanel running Tasmota.  I would like to integrate this into Home Assistant using ESPHome.  Google/Youtube etc lead me to the above issue without explaining how to move forward.

### URL

https://www.home-assistant.io/integrations/esphome/

### Version

2023.6.3

**Comment by frenck** [comment]
> The documentation gives no information about how to fill this information out.

And the host address of your ESPHome device? 🤷 

Maybe I'm not understanding the issue you are experiencing/trying to raise?

../Frenck
