### ISSUE TITLE
MQTT Image url_topic incorrectly marked as boolean

### ISSUE THREAD

**Issue by W-Floyd** [home-assistant/home-assistant.github.io#28012]
### Feedback

The url_topic should be a string.

### URL

https://rc.home-assistant.io/integrations/image.mqtt/

### Version

2023.07

**Comment by jbouwh** [comment]
https://github.com/home-assistant/home-assistant.io/pull/28015 should correct this. It was a left over of an early implementation.
Thnx for reporting !
