### ISSUE TITLE
Installaton does not work for me

### ISSUE THREAD

**Issue by fred-clement-91** [home-assistant/home-assistant.github.io#28013]
### Feedback

Hi,
When installing the module, it asks for serial number, login and password and just replies OK.
But nothing installed

### URL

https://www.home-assistant.io/integrations/wallbox/

### Version

2023.6.3

**Comment by joostlek** [comment]
This repo is for documentation, issues here are meant for feedback and issues with the documentation. So for issues like these please create a ticket over at https://github.com/home-assistant/core.

Thank you!
