### ISSUE TITLE
Please explain more

### ISSUE THREAD

**Issue by doming50** [home-assistant/home-assistant.github.io#28014]
### Feedback

I don't know how to set the configuration described in the guide in a homeassistant installation on raspberry pi.

### URL

https://www.home-assistant.io/more-info/unsupported/apparmor/

### Version

2023.6.3

**Comment by frenck** [comment]
> I don't know how to set the configuration described in the guide in a homeassistant installation on raspberry pi.


With all respect, this installation method targets advanced users and requires advanced knowledge of Linux system administration. This is documented as such as well. 

If this causes a problem for you, we strongly recommend looking at one of the different installation methods.

../Frenck

**Comment by doming50** [comment]
Hi Frenck,

Appreciate your prompt response. I may not be the most advanced Linux user but this is the only instruction in the homeassistant site I've been unable to follow. And after a few Google searches, the most I can find are people with the same struggle as I have.

My question here is simple, would you be kind enough to be more descriptive on how to configure apparmor in a homeassistant installation on a RaspberryPi? Unless he only alternative is to use a different installation method.

**Comment by BenoitAnastay** [comment]
I've just read the documentation, AppArmor is a linux kernel functionality, the documentation only refer to a boot flag, as a sys admin I've no strugle to understand this page. 

But you may have a specific issue and if you want to get help, you will need to explain your issue.

Do you have an error, a warning of any kind, what do you try to do, for short what is the issue you encounter and what do you expect ? 

We cannot help you to solve an issue if you just say that the documentation is unclear.

If you refer to an RPI kernel issue, there is an answer here : 
https://forums.raspberrypi.com/viewtopic.php?t=66748#p1834603

**Comment by doming50** [comment]
Hi Benoit,

Thanks for your response. I do have an issues with my installation of homeassistant. As already described, I'm using a raspberry pi (model 3b to be more specific). I'm unable to update the OS as the installation is never finished. I get the following warning "Unsupported system - AppArmor issues. System is unsupported because AppArmor is working incorrectly and add-ons are running in an unprotected and insecure way.", and a link to the documentation which I cannot resolve (after weeks of research).

I've seen the link you shared but my struggle is that I cannot reach the boot folder via the TerminalSSH. Do you have any suggestion?

**Comment by BenoitAnastay** [comment]
Do you use raspdebian or HA OS ? 

sometimes boot folder is readonly and only readable by root user, did you try `sudo vi /boot/cmdline.txt` and `sudo mount -o remount,rw /boot` ? 

NB : I'm not using RPi, so I don't know its normal behaviour

**Comment by doming50** [comment]
I am using HA OS. 
When I try `sudo vi /boot/cmdline.txt` I open an new file. When I try `sudo mount -o remount,rw /boot` it says "can't find /boot in /proc/mounts.

**Comment by BenoitAnastay** [comment]
Ok then you are not concerned by the unsupported setup documentation,

It may be an issue with RPI HAOS 

There is a related issue, please check it.

https://github.com/home-assistant/operating-system/issues/2522

NB : It's at first glance not an issue with HA Core since you are using HA Os so you may need to close this issue and create a new one for HA OS, but please give all your error logs, screenshot or anything that help understand where's the issue

**Comment by BenoitAnastay** [comment]
@frenck I guess he was directed to this documentation by the error thrown by HA when it's run on an unsupported OS, but he does use the Home Assistant Operating System.

Thus it was misleading.

Therefore the real issue is the presence of this error on a RPI HAOS setup

**Comment by doming50** [comment]
@BenoitAnastay this thread describes exactly my issue, but i see no solution. I've been stuck in this for months trying to update HAOS 8.5. any suggestion?

**Comment by BenoitAnastay** [comment]
Since I don't have a RPI I can't help.

It's specific to this hardware because it depends on the kernel.

**Comment by BenoitAnastay** [comment]
But because this issue is a duplication of another one opened earlier you should close it.

Merging a specific issue to one unique thread helps improve the visibility, the tracking and understanding of issues.

If the discussion about an issue is spread across multiple threads the people who are working on its resolution may miss important information.

**Comment by doming50** [comment]
Closing to merge threads
