### ISSUE TITLE
Documentation of "Battery Strategy" and "Battery Smart Control"

### ISSUE THREAD

**Issue by mzurhorst** [home-assistant/home-assistant.github.io#28020]
### Feedback

I am struggeling with the "Battery Strategy" and "Battery Smart Control" settings in the Kostal integration.
What is the particular purpose, and how do they interact? -- Is there a documentation available.

Also, I see "Battery Charging / Usage mode".  Which roles does this play?

### URL

https://www.home-assistant.io/integrations/kostal_plenticore/

### Version

2023.6.3

**Comment by mzurhorst** [comment]
I actually do not agree with closing this.  The documentation of those settings would be helpful.

**Comment by stegm** [comment]
Battery strategy: See https://www.kostal-solar-electric.com/de-de/download/download/-/media/document-library-folder---kse/2020/12/15/13/28/plenticore-plus_ba_en.pdf page 140.

Battery Smart Control: page 142

**Comment by mzurhorst** [comment]
Thank you very much for the explanation.

**Comment by mzurhorst** [comment]
Issue closed; documentation has been amended with more information.
