### ISSUE TITLE
Input range of holidays

### ISSUE THREAD

**Issue by rasskjo** [home-assistant/home-assistant.github.io#28032]
### Feedback

Would be great if the Documentation had some examples on how to input a range of holidays. I.e. when the kids are on sommer vacation for multiple weeks.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2023.6.3

**Comment by gjohansson-ST** [comment]
It's currently not part of `workday` to be able to specify ranges of dates, only single dates are allowed.
Feature requests goes into [community forum](https://community.home-assistant.io/), only issues are tracked on github.
