### ISSUE TITLE
A waiting animation would be useful

### ISSUE THREAD

**Issue by Solarbytes** [home-assistant/home-assistant.github.io#28034]
### Feedback

The documentation is generally very good and easy to follow. On a couple occasions in the onboarding process however, I completed all fields and clicked the submit button (Create account, Next Button for the location) and but nothing was happening. I wasn't sure where I missed a field or whether the system was stuck. Either an animation showing the the button was been pushed but the result is still being processed, or a message telling the user that this may take a minute or two would help.

Also, once I connected to the system on a browser, I went into settings-devices ands services-Sun, and the data appearing there was incorrect. It said that the next dawn was in 15 hours while it would have been around 8 hours (I looked at it at 10pm, and I am located in Brisbane, so the next dawn was at around 6am, i.e. only 8 hours later)

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2023.6.3

### URL for the Sun service is http://homeassistant:8123/config/devices/device/a6747f6c11e0cf25daeed9b40c658d42

To be honest, I don't know what that device is, it is not a device I am aware I have, so perhaps it is a public service?

**Comment by dannytsang** [comment]
Hi @Solarbytes 

Thank you for the feedback on the getting started documentation.

The 2 points you have raised, please raise those separately in **New Issue** > **Feature Request**
and **New Issue** > **Report a bug/issue with Home Assistant Core itself** respectively because this repository deals with documentation only.
