### ISSUE TITLE
Author Contact

### ISSUE THREAD

**Issue by virgil53** [home-assistant/home-assistant.github.io#28040]
### Feedback

There is no link to request updates or improvements on the page from the original author of the integration.

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2023.6.3

### Additional information

Hayward has released updates for Alexa and Google Assistant that are missing from this integrating, that I would benefit from to build scenes especially for the lighting. This would include lights, landscape lights controlled by the Omnilogic, snd automated valves.

**Comment by frenck** [comment]
Thank you for reaching out. We don't contact authors in general, please use our community forums for feature requests and improvements.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
