### ISSUE TITLE
Confirm Brel HUB-03 is working with this integration

### ISSUE THREAD

**Issue by RvanderZ** [home-assistant/home-assistant.github.io#28050]
### Feedback

I can confirm that the following bridge is also working with this integration:
Brel HUB-03

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2023.6.3

**Comment by starkillerOG** [comment]
@RvanderZ thank you for the feedback, I have updated the documentation here: https://github.com/home-assistant/home-assistant.io/pull/28059

If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.
