### ISSUE TITLE
Logitech have ceased providing API access in 2023.

### ISSUE THREAD

**Issue by douginoz** [home-assistant/home-assistant.github.io#28058]
### Feedback

Logitech have ceased providing API access in 2023.  That should be mentioned before instructing installers to go to their website to obtain an API.  They can't any more.

### URL

https://www.home-assistant.io/integrations/logi_circle/

### Version

2023.6.3

**Comment by evanjd** [comment]
@douginoz That was intention behind raising [this alert](https://github.com/home-assistant/alerts.home-assistant.io/pull/528), which is visible on the header of the page you linked
<img width="729" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/4055224/b252bc77-5b23-48ca-80ea-f56a3b08b233">
