### ISSUE TITLE
more information

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/home-assistant.github.io#28051]
### Feedback

Can you provide some pictures of the interface and more information about what is provided for a home generator?

### URL

https://www.home-assistant.io/integrations/oncue/

### Version

2023.6.3

**Comment by PeteRager** [comment]
There have been some attempts at updating the documentation.  A challenge is each generator model / generator options has a different data set and none of us have multiple generators.  As a general guideline what you see in the OnCue App is the dataset you will get in HASS. 

That said, if you'd like to help updating the documentation - that would be greatly appreciated.

**Comment by turboc1208** [comment]
Mine comes in, in a few weeks. Lol. I’ll take a shot at some docs for it then.
