### ISSUE TITLE
Chicken-and-egg problem setting up a Z-Wave JS server

### ISSUE THREAD

**Issue by gleversluis** [home-assistant/home-assistant.github.io#28062]
### Feedback

Just after the "Getting Started" part, the documentation says this:
_SETTING UP A Z-WAVE JS SERVER
The easiest way to get started is by using the built-in Z-Wave JS add-on in Home Assistant._

This seems to indicate that I can set up a Z-Wave JS server by opening the HA User interface and inserting the USB Z-Wave stick. This doesn't show anything so I go to the Manual setup steps: 
Go to [Settings > Devices & Services](https://my.home-assistant.io/redirect/integrations).
In the bottom right, select the  [Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=zwave_js) button.

The first thing that shows up is a dialog box asking me to enter the URL. However, as stated, this should be the procedure to _install_ the Z-Wave JS server, not connect to it. With the current situation, I have to connect to a Z-Wave JS server to install that same Z-Wave JS server - which makes it a chicken-and-egg issue.

The easiest fix IMO would be to rename the paragraph to something like "setting up a Z-Wave JS _integration_ with a runnning Z-Wave JS server" or something.

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2023.6.3

**Comment by MartinHjelmare** [comment]
The Getting started section assumes you're running Home Assistant OS or Supervisor which can install add-ons. If you are not using one of those methods to run Home Assistant you need to follow the advanced installation instructions.

**Comment by gleversluis** [comment]
In that case, may I suggest not assuming but including that this page is only for those running HA OS or Supervisor? I run HA on Linux (bare-metal, no docker or anything). Just to make things clear for those of us that actually read documentation ;)

**Comment by MartinHjelmare** [comment]
It would be enough to add a clause or note saying that in the Getting started section, I think. The page is still relevant for all users.

A PR is welcome. :+1:
