### ISSUE TITLE
Using the HDMI-CEC integration on Home Assistant OS... Is it possible? And if how?

### ISSUE THREAD

**Issue by ChewyFudge** [home-assistant/home-assistant.github.io#28066]
### Feedback

Using the HDMI-CEC integration on Home Assistant OS... Is it possible? And if how?

### URL

https://www.home-assistant.io/integrations/hdmi_cec/

### Version

2023.6.3

### Additional information

I can't find any kind of documentation on installing Using HDMI-CEC on Home Assistant OS...
If it isn't possible, you should write so on the integration page :-)

**Comment by inytar** [comment]
Hi!

It really depends on the hardware, Home Assistant OS has the right libraries installed. I'll look at updating the documentation to make this clearer. 

If you have questions about your specific installation I'd suggest just trying or asking in the HA forum.

**Comment by ChewyFudge** [comment]
Thx for the reply :-)
  

  

  

  
  
  
  
>

**Comment by c0ffeeca7** [comment]
Thank you for adding this to the docs, @inytar!
Thank you for bringing it up, @ChewyFudge :+1: 

Will close this as completed by #28143
