### ISSUE TITLE
adding Day name to the day over

### ISSUE THREAD

**Issue by xtrmenl** [home-assistant/home-assistant.github.io#28060]
### Feedback

could you add the name of the day to the date 

so like this
https://i.imgur.com/ALuNZQL.png

### URL

https://www.home-assistant.io/docs/energy/

### Version

2023.6.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
