### ISSUE TITLE
Downloaded virtual box image requires login

### ISSUE THREAD

**Issue by brampeirs** [home-assistant/home-assistant.github.io#28076]
### Feedback

Download virtual box image requires login, the login is `root` but this is not documented in the docs.
<img width="643" alt="Screenshot 2023-07-05 at 10 28 26" src="https://github.com/home-assistant/home-assistant.io/assets/2495032/52f10760-8250-486c-88bc-5a6a74dd4f6e">

### URL

https://www.home-assistant.io/installation/windows/

### Version

2023.6.3

**Comment by frenck** [comment]
It is documented in our common tasks documentation. However, there is general no use in accessing that part (unless you need to change/enable things like i2c).

All Home Assistant is managed and controlled in other ways. This terminal is only used for very, very specific use-cases (and documented in those cases).

../Frenck
