### ISSUE TITLE
Examples/Solutions Needed for Propane (LPG)

### ISSUE THREAD

**Issue by joelevi** [home-assistant/home-assistant.github.io#28082]
### Feedback

While Natural Gas (LNG) may be more widely used than Propane (LPG), it's arguably more important for Propane users to be able to monitor their consumption (since their supply is limited to a physical tank typically located on or near to the Home Assistant implementation. Natural Gas is typically supplied via buried pipeline by a far-distant supplier.

The analog to this is electricity, where power from your solar and/or battery is arguably more important than power from the grid. 

We need some solutions to monitor usage of Propane provided in the documentation (or a call to action requesting solutions to do so).

### URL

https://www.home-assistant.io/docs/energy/gas/

### Version

2023.6.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
