### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by stiltjack** [home-assistant/home-assistant.github.io#28084]
### Feedback

A search for zigbee2mqtt using the Docs searchbox gives this link https://www.home-assistant.io/docs/mqtt/discovery#support-by-third-party-tools but the page does not exist.

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2023.7.0

**Comment by jbouwh** [comment]
I found an incorrect redirect. A PR to fix this is linked and will automatically close this issue once merged.
Thanx for reporting @stiltjack 👍
