### ISSUE TITLE
Apple iOS watch shortcut bug fixed?

### ISSUE THREAD

**Issue by magicmega** [home-assistant/home-assistant.github.io#28087]
### Feedback

For the Troubleshooting section on this page (https://www.home-assistant.io/voice_control/apple/#troubleshooting)

WatchOS 9.5.2 update does not appear to have this issue. 
I can run the shortcut multiple times from the watch and only had to provide authorisation to allow Siri to control home assistant once, the first time.

Suggest language be changed to 'Update to at least WatchOS 9.5.2 to solve this issue'

### URL

https://www.home-assistant.io/voice_control/apple/

### Version

2023.7.0

**Comment by ghost** [comment]
I‘ve tested multiple versions and right now i am at WatchOS 9.6. None of the versions fixed the bug, for me it is still present.
