### ISSUE TITLE
set_mop_mode and waterflow 

### ISSUE THREAD

**Issue by naudor** [home-assistant/home-assistant.github.io#28106]
### Feedback

Would be so interesting to implement set_mop_mode  and waterflow like params when you do a send_command request

Thanks a lot ;-)

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.7.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
