### ISSUE TITLE
Need some more information how to use this entity and how to config it in the yaml

### ISSUE THREAD

**Issue by gielk** [home-assistant/home-assistant.github.io#28103]
### Feedback

Can you please provide examples of how to implement this component into the configuration file? Additionally, it would be helpful to know how to use it and what options are available. Thank you.

### URL

https://www.home-assistant.io/integrations/image/

### Version

2023.7.0

**Comment by klaasnicolaas** [comment]
`The image integration allows other integrations to display a static image.`

So it is not a standalone entity that you can use or configuration for, only through other integrations 😉
