### ISSUE TITLE
Correction to reflect helper name change from "Switch as X" to "Change device type of a switch".

### ISSUE THREAD

**Issue by granvidleg** [home-assistant/home-assistant.github.io#28101]
### Feedback

The helper referenced several times as "Switch as X" as denoted in the web page is now named differently in Home Assistant.  The new name is "Change device type of a switch'

### URL

https://www.home-assistant.io/integrations/switch_as_x/

### Version

2023.7.0

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @granvidleg :+1:
