### ISSUE TITLE
Cannot install pip3 on HAOS

### ISSUE THREAD

**Issue by bert269** [home-assistant/home-assistant.github.io#28105]
### Feedback

I am trying to setup SkyConnect matter (https://github.com/NabuCasa/silabs-firmware/wiki/Flash-Silicon-Labs-radio-firmware-flasher) 
HAOS does not have python installed. I manged to get it installed with "**apk add python3**"
I also managed to get two pre-reqs for pip3 installed: python3-dev, libffi-dev but it does not locate: libssl-dev
![image](https://github.com/home-assistant/home-assistant.io/assets/18601216/7cdc343d-f1ed-43c6-8129-3df3fd380be9)

It does the same for pip3:
![image](https://github.com/home-assistant/home-assistant.io/assets/18601216/ba3526ea-35cb-4058-acca-0a9884e899cd)

See: https://www.home-assistant.io/faq/pip3/

How do I install pip3 to be able to install the silicon-labs software to flash the device? I do not want to install another version oh Home Assistant, I just need pip3.

### URL

https://www.home-assistant.io/faq/pip3/

### Version

2023.7.0

**Comment by agners** [comment]
@bert269 note that you are not connecting to HAOS, but the SSH add-on container instead.

You most likely use the "Terrminal & SSH" from the Official add-on section. You have to use the one from the community section as noted here: https://github.com/NabuCasa/silabs-firmware/wiki/Flash-Silicon-Labs-radio-firmware-manually.

**Comment by agners** [comment]
Also note that the OpenThread Border Router add-on installs the correct firmware automatically.
