### ISSUE TITLE
Room/Zone Cleaning

### ISSUE THREAD

**Issue by commiepinko** [home-assistant/home-assistant.github.io#28117]
### Feedback

Being able to specify which rooms or zones should be cleaned would be a great help.

### URL

https://www.home-assistant.io/integrations/roomba/

### Version

2023.7.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
