### ISSUE TITLE
Air Quality

### ISSUE THREAD

**Issue by AirSearcher** [home-assistant/home-assistant.github.io#28118]
### Feedback

I noticed that the app does not get the air quality of the local city. It does display the local air quality but the external air quality, temperature are not detected. Can these items be added?

### URL

https://www.home-assistant.io/integrations/airvisual_pro/

### Version

2023.7.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
