### ISSUE TITLE
Switch Actor is not working

### ISSUE THREAD

**Issue by guentherparth** [home-assistant/home-assistant.github.io#28120]
### Feedback

Every enocean-Actor must be teached in. At the Moment its not possible to send Teach-In Telegrams to the Actor (The Actor must be set to Learn-Modus).
In the /config/configuration.yaml the sender_id must be setable for EVERY Actor (Thats like the ID of a Wall switches).
Why is it not possible to set the sender_id for the the Switch-Actor (for example Nod On SIN-2-1-01)?
When i can not set the sender_id, the actor can not know what it should do and musst be teached in with the sender_id.
sender_id is like a virtual Wall switch.
When you teach in a actor (set the actor into Learning Mode), you need to push a Button on the Wall switch.
The Actor receives the ID of the Wall switch and stores the ID of the Wall switch internal.
So it MUST be possible to set the sender_id for the Switch-Actor.
When i set the sender_id for the switch-actor, i get an error. :-(

### URL

https://www.home-assistant.io/integrations/enocean/

### Version

2023.7.1

### Additional information

![configuration_yaml](https://github.com/home-assistant/home-assistant.io/assets/73226103/d01cdfaf-d1ed-4f31-a771-597465fc09ed)
![error](https://github.com/home-assistant/home-assistant.io/assets/73226103/d0393515-a019-4daa-8793-25cf28b0cc36)

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
