### ISSUE TITLE
Unit for time_constant

### ISSUE THREAD

**Issue by danka621** [home-assistant/home-assistant.github.io#28137]
### Feedback

Documentation is unclear on what unit time_constant should have. Is it seconds, minutes or maybe same as window_size, ie.. HH:MM?

### URL

https://www.home-assistant.io/integrations/filter/

### Version

2023.7.1

**Comment by dgomes** [comment]
it is void of unit, it is the number used to scale the last received state. see the formula in https://www.home-assistant.io/integrations/filter/#low-pass
