### ISSUE TITLE
use of double quotes within text string throws error.   Script offered is misleading to users not familiar with yaml.

### ISSUE THREAD

**Issue by flyangler** [home-assistant/home-assistant.github.io#28133]
### Feedback

automation:
  - alias: "Create notifications for "service" errors"

### URL

https://www.home-assistant.io/integrations/system_log/

### Version

2023.7.1

### Additional information

The script intended as an automation contains multiple opening and closing double quotes.   When the user selects the copy button and inserts the script into automations.yaml or configuration.yaml the script throws an error. 

Suggest eliminating the use of double quotes to simply emphasize text within .yaml files to prevent broken lines of code.   Option: single quotes are acceptable but really there is no need to emphasize the word in the first place.

**Comment by frenck** [comment]
Thanks for the report @flyangler 👍 

I've opened up a pull request to fix the mentioned issue.

../Frenck
