### ISSUE TITLE
Add units to Offset in GUI

### ISSUE THREAD

**Issue by Master-Osiris** [home-assistant/home-assistant.github.io#28146]
### Feedback

When creating an automation in HA with a sunset trigger it would be nice if the unit of the Offset would be displayed.
s.th like "Offset in minutes" (in german "Versatz in Minuten") 

### URL

https://www.home-assistant.io/docs/automation/trigger/

### Version

2023.7.1

**Comment by dannytsang** [comment]
Hi @Master-Osiris 

Can you provide this useful feedback to the front end repository please: https://github.com/home-assistant/frontend/issues
