### ISSUE TITLE
How to remove

### ISSUE THREAD

**Issue by cjramseyer** [home-assistant/home-assistant.github.io#28141]
### Feedback

The documentation shows how to add a local calendar, however, does not explain the steps necessary to remove an unneeded local calendar.

When attempting to remove this unneeded local calendar in HA from the Settings, Integrations page, and error shown below is generated: 

![image](https://github.com/home-assistant/home-assistant.io/assets/48690692/a3d76a40-24c8-4604-8462-e2df632073b0)

This doesn't lead to additional information of the steps necessary to remove the local calendar leaving an unused and unneeded integration.

### URL

https://www.home-assistant.io/integrations/local_calendar/

### Version

2023.7.1

**Comment by allenporter** [comment]
Hi, can you tell me the steps you took to get that in more detail?
