### ISSUE TITLE
Make sure that MQTT broker and integration are configured and running 

### ISSUE THREAD

**Issue by edarsey** [home-assistant/home-assistant.github.io#28142]
### Feedback

Before configuring the (WoIOSensorTH) the MQTT broker and integration need to be configured and running, otherwise the Temp and Humidity dat won't be passed to HA. The Sensor appeared as WoIOPlug before the MQTT broker was configured.

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.7.1

**Comment by asucrews** [comment]
Hello @edarsey.

I have MQTT setup and I am not seeing any message being passed to MQTT.  Do you have error message or logs?

**Comment by edarsey** [comment]
> Hello @edarsey.
> 
> I have MQTT setup and I am not seeing any message being passed to MQTT. Do you have error message or logs?

I don't have any logs, I did restart HA, the MQTT broker and the WoIOSensorTH  after getting the MQTT broker(Mosquito) up and adding the MQTT integration. I checked again a couple hours later and was receiving data.
