### ISSUE TITLE
My HA doesn't know what my Insteon devices are doing

### ISSUE THREAD

**Issue by NJBILLT** [home-assistant/home-assistant.github.io#28150]
### Feedback

Using a 2314U modem, I can control everything from HA.  But when I use a switch, HA doesn't know.  It's like none of my devices are reporting their status to the modem.  It just goes one way.  What could be the problem?  TIA 

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2023.7.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
