### ISSUE TITLE
Jewish Calendar became "unavailable"

### ISSUE THREAD

**Issue by kj4qyf** [home-assistant/home-assistant.github.io#28151]
### Feedback

The Jewish Calendar suddenly became "unavailable" and is greyed out in my Dashboard.  In Yaml there were no changes made and the Jewish Calendar still appears as before.

### URL

https://www.home-assistant.io/integrations/jewish_calendar/

### Version

2023.7.1

**Comment by c0ffeeca7** [comment]
Hi there, @kj4qyf 

It seems like you want to report an issue with a Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:
https://github.com/home-assistant/core/issues

Thanks!
