### ISSUE TITLE
Example is not accepted in configuration.yaml

### ISSUE THREAD

**Issue by todool** [home-assistant/home-assistant.github.io#28163]
### Feedback

mqtt:
#Dylan Hot Tube PureSpa SB-H20
  text: 
    - name: "model"
      unique_id: "4738345125"
      state_topic: pool/model

I used this example but got an error " Property text is not allowd"

![2023-07-10_19-37](https://github.com/home-assistant/home-assistant.io/assets/22204418/905a083f-38c9-4535-ba66-dae0c31b09c0)

### URL

https://www.home-assistant.io/integrations/text.mqtt/

### Version

2023.7.1

**Comment by frenck** [comment]
This is not an Home Assistant documentation issue (for which you have provided a suggest for using this issue), but an issue with the VSCode Helper extension for Home Assistant. Please submit an issue with the author of that (third-party) VSCode extension instead.

../Frenck
