### ISSUE TITLE
Smart Event - Intrusion Detection

### ISSUE THREAD

**Issue by bigjhp** [home-assistant/home-assistant.github.io#28175]
### Feedback

Are you able to support the intrusion detection smart event, and any other newer event created since this was published? Would be great to use the events from the nvr to trigger automations (ie lights on for 5 min). Thank you!

### URL

https://www.home-assistant.io/integrations/hikvision/

### Version

2023.7.1

### Additional information

NVR is [DS-7616NI-I2/16P] with 4K acsense Color by and darkfighter isu cameras

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by bigjhp** [comment]
Apologies, the Home Assistant Hikvision page led me to raise it this way.

Unrelated when I tried this last year and setting traditional motion detection in cameras and nvr, it didn’t actually trigger reliably, so I uninstalled it.

Shame hikvision don’t offer an in house option!

Thank for all the work you’ve done on this regardless.


Cheers

John

On 11 Jul 2023, at 11:06 pm, Klaas Schoute ***@***.***> wrote:

﻿

Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our Community Forum: Feature Requests<https://community.home-assistant.io/c/feature-requests>.

Thanks! 👍
