### ISSUE TITLE
Enphase integration no longer works

### ISSUE THREAD

**Issue by perikillo70** [home-assistant/home-assistant.github.io#28178]
### Feedback

This integration no longer works. Enphase has made a firmware update that requires a token. Do you have a solution to keep it working locally?. Thanks.

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.7.1

**Comment by joostlek** [comment]
Hey there,

This repository is for issues about the documentation. For issues like these, please checkout home-assistant/core. I'm going to close this issue for this reason.

But to further help you, last couple of days I've seen some enphase issues coming in regarding this firmware update. Please checkout https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+enphase_envoy%22 to find the issue that reflects your problem. I've seen some workarounds in the comments so maybe that can be helpful!
