### ISSUE TITLE
cannot find Python virtual environment based installation instructions

### ISSUE THREAD

**Issue by attila-lendvai** [home-assistant/home-assistant.github.io#28186]
### Feedback

this page:

https://www.home-assistant.io/installation/

mentions this:

> Manual installation using Python virtual environment.

which i cannot find.

### URL

https://www.home-assistant.io/installation/

### Version

2023.7.1

**Comment by frenck** [comment]
You can find it here:

https://www.home-assistant.io/installation/linux#install-home-assistant-core

../Frenck
