### ISSUE TITLE
"Number of milliseconds"?

### ISSUE THREAD

**Issue by ccristal** [home-assistant/home-assistant.github.io#28188]
### Feedback

Hi!
The docs read:
```
emulate_key_hold_delay float (optional, default: **0.25**)
Number of **milliseconds** to wait before sending first emulated key hold event

emulate_key_hold_repeat float (optional, default: **0.033**)
Number of **milliseconds** to wait before sending subsequent emulated key hold event
```
Are those really milliseconds? 0.25 milliseconds? That's a quarter of a millisecond. Is that really what you meant? Or did you mean a quarter of a second, i.e. 250 milliseconds? If so, shouldn't the documentation read:

```
Number of **seconds**...
```
?

### URL

https://www.home-assistant.io/integrations/keyboard_remote/

### Version

2023.7.1

**Comment by lanrat** [comment]
@ccristal tanks for the bug report.

You are correct, this should be in seconds.
