### ISSUE TITLE
Conflicting information on THIRDREALITY device compatibility for OTA updates

### ISSUE THREAD

**Issue by JGiubardo** [home-assistant/home-assistant.github.io#28198]
### Feedback

THIRDREALITY isn't listed as compatible for OTA updates:
> Online OTA providers for firmware updates are currently only available for IKEA, LEDVANCE/OSRAM, SALUS/Computime, and INOVELLI devices.

but is listed as a provider with the example config for OTA updates:
> You can choose if the IKEA, LEDVANCE, SALUS, INOVELLI or THIRDREALITY provider should be set to enabled...

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2023.7.2

**Comment by Hedda** [comment]
Will this PR fix this? -> https://github.com/home-assistant/home-assistant.io/pull/28895

**Comment by JGiubardo** [comment]
Yes, I think that fixes the issue.
