### ISSUE TITLE
Suggestion, password change

### ISSUE THREAD

**Issue by digdilem** [home-assistant/home-assistant.github.io#28190]
### Feedback

Twice in a short period, Spotify has locked my account and sent me an email forcing me to change my password for "suspicious activity" - but they won't explain what or what, or respond to questions. It is vexing and googling suggests it's a known issue affecting many users.

Doing so breaks the trust between this integration and spotify, and this must be regained. So can I suggest an addition  to the documentation for others affected as I couldn't find any existing documentation on how to do this.

The process is fairly simple once you know what's happening - this is what I did. It's possible there's a better way, or perhaps a button could be added to trigger the trust page again?  (I appreciate this might be hard to test!)

1. Integrations -> Add new -> Spotify. 
2. "Link account"
3. This then loads a Spotify page asking you to accept the link. Do so. 
4. You'll then be returned to HA asking which location the device is in. You can either click "Finish" or "X" to cancel the setup on this dialog - it doesn't matter as the trust has been regained above and the Spotify integration works again.

(Oddly, the Amazon Alexa integration for Spotify seems to work as soon as you change your password and unlock the spotify account, but they may have a special relationship with Spotify's api)

Thanks for a very useful integration that I use daily. I have a zigbee button that plays the next song, or toggles play. Very useful when the phone rings!

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2023.7.1

**Comment by digdilem** [comment]
Bumping to keep alive - hoping @frenck can add to the documentation as this issue is still a problem and it will help others affected.

**Comment by jrdwiz** [comment]
I'm having the same issue. I get an email stating that I have to change my password. "To protect your Spotify account, we've reset your password due to detected suspicious activity."

**Comment by digdilem** [comment]
Bumping issue to keep it open as I believe this is still a problem for some people - not just myself, and should be fairly easy to resolve by simply extending the documentation to include a paragraph to help others.  

Perhaps something like the following?


`Occasionally Spotify may remove the association between third party apps and themselves. If this integration stops working, it can be re-authenticated by revisiting the Spotify Integration in Home Assistant. Click "Add Service" and you will be promted again to "Link account to Home Assistant". You may also be prompted to log into Spotify's account directly if you're not already logged into them on your browser.  Click "Link Account" here and the link should be recreated without affecting your existing entities. 
`
