### ISSUE TITLE
light turn on. Attribute color_temp_kelvin or kelvin

### ISSUE THREAD

**Issue by stefanuytterhoeven** [home-assistant/home-assistant.github.io#28193]
### Feedback

when looking at the documentation. I see "color_temp_kelvin" and another time "kelvin".
when calling the service "turn on ", (developer tools) , it says Kelvin
but when i change the attribute in the "data:' part, it also seems to work with color_temp_kelvin....
Will HA change the name in the future or so? Why these two attribute name for the same attribute?

Btw; neither color_temp_kelvin or kelvin is available for my hue lightbulb connected through matter. Although, there is a max_color_temp_kelvin, and a min_color_temp_kelvin. So, there's only a color_temp attribute....

### URL

https://www.home-assistant.io/integrations/light/

### Version

2023.7.1

**Comment by stefanuytterhoeven** [comment]
Status?

**Comment by stefanuytterhoeven** [comment]
it's not the Light integration in Ha Core as far as I can see. It's the Matter integration which has also a light.py source.
@marcelveldt

**Comment by marcelveldt** [comment]
I'm having my holidays, I will take a look at this in a few weeks. I assume nothing is broken and this is just a minor annoyance ?

**Comment by stefanuytterhoeven** [comment]
Great! No problem. I use in pyscript mostly color_temp_kelvin by default. But, as I only have one light connected through matter, it's a minor annoyance.
thanks for you quick reply!

Have a great holiday!

**Comment by stefanuytterhoeven** [comment]
did you have the time yet to look at it?
