### ISSUE TITLE
Switchbot - Thermoter/Hygrometer temporary loss of connection and re-download

### ISSUE THREAD

**Issue by fnordson** [home-assistant/home-assistant.github.io#28209]
### Feedback

Due to my massive shades, HA loses connection to the meter at night when shades are down. 
The meter seems to save data, though. 
Is there a way to trigger a download for the missing time frames? 

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2023.7.2

### Additional information

Switchbot is connected through a ZEXMTE BT-505 Bluetooth adapter.
HA runs on a RasPi:

Supervisor 2023.07.1 
Operating System 10.3 
Frontend 20230705.1 - latest

**Comment by klaasnicolaas** [comment]
Hi there @fnordson 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
