### ISSUE TITLE
Description of QNAP integration

### ISSUE THREAD

**Issue by jarekt70** [home-assistant/home-assistant.github.io#28203]
### Feedback

It would be good to describe what privileges the qnap user needs to have in order to make it work. If there any specific configuration on QTS side is required it would be helpful do describe. I've tried this integration and I got "Unknown error occurred" so I don't know where to start the investigation.   

### URL

https://www.home-assistant.io/integrations/qnap/

### Version

2023.7.2

**Comment by disforw** [comment]
Have you resolved this? What was the outcome?

**Comment by jarekt70** [comment]
I haven't found any solution yet. I was hoping for some tips.
