### ISSUE TITLE
CGS1 Model

### ISSUE THREAD

**Issue by markgandalf** [home-assistant/home-assistant.github.io#28208]
### Feedback

hi,

I would like to know if you plan to integrate the CGS1 WiFi model into the support

thx
Marco

### URL

https://www.home-assistant.io/integrations/qingping/

### Version

2023.7.1

**Comment by skgsergio** [comment]
This integration uses Bluetooth LE to receive the information from the devices and the one you mentioned looks like it's WiFi only so it would require to develop the full communication with Quinping API (if there is one, or doing reverse engineering to use the same one as the APP which probably means doing nasty stuff to get tokens).

As reference: https://github.com/custom-components/ble_monitor/issues/1148#issuecomment-1488548646

**Comment by markgandalf** [comment]
![image](https://github.com/home-assistant/home-assistant.io/assets/77160339/e7ccb2ed-a454-4279-aab3-5d45cbedd168)

as you can see they say the device support full support open API to third party

i hope someone can do something in this way because it is a very good device

**Comment by skgsergio** [comment]
That's a good start but a new integration would be required as it is not just adding a device to the existing one that is BLE based. And doing that usually requires someone having the device for testing.

**Comment by markgandalf** [comment]
Sure, please let me know if someone is willing to try, i am absolutely available to carry out tests with my device, in case it is needed I can also try to capture the traffic with wireshark

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
