### ISSUE TITLE
Astablish connection does not work

### ISSUE THREAD

**Issue by Edteli** [home-assistant/home-assistant.github.io#28211]
### Feedback

Connecting with the integrated module to Enphase gateway does not work.
Msg: "Cannot make a connection"

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.7.2

**Comment by joostlek** [comment]
Hey!

This is already an existing issue over at https://github.com/home-assistant/core/issues/88983. This repo is for issues and feedback on the documentation!

So please checkout that issue and I'll close the issue.
