### ISSUE TITLE
Fixed vertical axis

### ISSUE THREAD

**Issue by fenris28** [home-assistant/home-assistant.github.io#28221]
### Feedback

For the Energy Cards, energy-solar-graph:

Is it possible to add some configuration options to make the vertical axis fixed. Like adding a min / max value.

Currently I have problems misinterpreting the solar PV production on sunny versus cloudy days, because the scale varies dynamically.  

Then decisions on starting the washing machine is wrong because the solar production looks like it is high. 

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2023.7.2

**Comment by c0ffeeca7** [comment]
Thank you for reaching out!
This GitHub issue tracker is used specifically to track documentation issues.
To suggest a feature, try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
For support, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).
