### ISSUE TITLE
Note on Nest Accounts

### ISSUE THREAD

**Issue by RiantUK** [home-assistant/home-assistant.github.io#28224]
### Feedback

It may be worth noting near the top of this page that this only works where you have Nest products linked to your Google account and not still using the older Nest accounts. Google don't let you use a G-suite account, so anyone that had Nest before 2019 and has a Google account using the free G-Suite services for personal use cannot migrate withouth using separate non G-suite Google Account. 

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2023.7.2

**Comment by allenporter** [comment]
Would welcome contributions to improve the documentation. This is mentioned somewhere and agree it can be highlighted. My assumption is Nest should be sending you emails about API shutting down, is that not happening?

**Comment by RiantUK** [comment]
I think it is more around if you are using a Nest account to login then
flagging this at the beginning of the article. I've not used the Nest API
for anything, but was looking to get our thermostant into HA so came across
this integration. As far as I can tell Google is not forcing anyone still
using legacy Nest accounts to move to a Google account, but they did stop
anyone signing up via it quite a while ago.

**Comment by allenporter** [comment]
You're welcome to propose changes to the documentation by sending a PR -- you can even  edit in the github UI. I don't plan to add details on old legacy account setups myself. IMO i'd recommend everyone switch off legacy accounts and move to something supported.

**Comment by RiantUK** [comment]
OK thanks. I wasn't aware Nest accounts were considered legacy. As my
Google account is a family g-suite account I can't migrate any Nest
services across due to them not allowing it.
