### ISSUE TITLE
Could this functionality be added for water?

### ISSUE THREAD

**Issue by Flov-v** [home-assistant/home-assistant.github.io#28227]
### Feedback

Hello,
I was wondering if there's a lot of work required to add this functionality to the water usage part of the energy dashboard.
Where I'm living we get a second water meter to track "outside water" that  is excempt from sewage cost. 
It still get's tracked by the main water meter though. So it's basically a meter to track the "outside water" consumption.
In its current state I'm not able to track this properly in HA because adding this as a water meter gets me wrong values, because the main meter already contains the outside water...

I hope this is understandable (english is not my main language) and can be added easily in the future. I would appreciate that.

Best regards, Florian

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2023.7.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by Flov-v** [comment]
Sorry about that, I put it in the proper place now =)
