### ISSUE TITLE
Missing control of Ventilation system

### ISSUE THREAD

**Issue by pduchnovsky** [home-assistant/home-assistant.github.io#28231]
### Feedback

I am missing feature related to ventilation system connected via heat pump, such as Vitocal devices.
Basic features such as enabling 'intensive' ventilation mode would be awesome.

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2023.7.2

**Comment by c0ffeeca7** [comment]
Thank you for reaching out!
This GitHub issue tracker is used specifically to track documentation issues.
To suggest a feature, try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
For support, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).
