### ISSUE TITLE
Wifi module AEHW4G1/AEHW4G2

### ISSUE THREAD

**Issue by barkas18** [home-assistant/home-assistant.github.io#28238]
### Feedback

Hi! Does it have any ways to connect my wifi module (ic:20778-AEHW4G1/AEHW4G2)to this integration?

### URL

https://www.home-assistant.io/integrations/hisense_aehw4a1/

### Version

2023.7.2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
