### ISSUE TITLE
Docu for update maybe not up2date

### ISSUE THREAD

**Issue by UserTotheMoon2** [home-assistant/home-assistant.github.io#28232]
### Feedback

hi guys,
I've just created a automation for nightly backups with the ui and compared the yaml with your code. The service is a different one. Maybe there was change?

alias: full backup every night
description: ""
trigger:
  - platform: time
    at: "03:00:00"
condition: []
action:
  - service: hassio.backup_full
    data:
      compressed: true
mode: single

### URL

https://www.home-assistant.io/integrations/backup/

### Version

2023.7.2

**Comment by frenck** [comment]
> I've just created a automation for nightly backups with the ui and compared the yaml with your code. The service is a different one

You are responding on the backup integration page, which is for Docker/Core installation types. However, you are using Home Assistant OS or Supervised installation type. Whic uses the `hassio` integration to communicate with the Supervisor.

That documentation can be found here: https://www.home-assistant.io/integrations/hassio

../Frenck
