### ISSUE TITLE
Change forecast_solar power production value names

### ISSUE THREAD

**Issue by a1bert01** [home-assistant/home-assistant.github.io#28247]
2 years after closing original PR, but forecast.solar still using misleading entities names

             Thanks for your PR, but I actually want to suggest closing this PR.  I'm working on some updates with the integration and that includes this issue / PR.

_Originally posted by @klaasnicolaas in https://github.com/home-assistant/core/issues/52789#issuecomment-877102894_

**Comment by frenck** [comment]
This is not our issue tracker, you have submitted documentation feedback, for which your post makes no sense.

Please check our help page on where to go: https://www.home-assistant.io/help

../Frenck
