### ISSUE TITLE
Add some problem solving tips to KVM documentation

### ISSUE THREAD

**Issue by burner-** [home-assistant/home-assistant.github.io#28240]
### Feedback

Because some mupped thinked that it is some how good idea to publish kvm image with UEFI I also recommend to add proper documentation to resolve problems with it brings. 
Here is one good atricle what helped after 3 hours of mashing head to wall. 
https://jhartman.pl/2021/11/08/proxmox-7-cant-boot-to-uefi-home-assistant-and-other-uefi-images/

### URL

https://www.home-assistant.io/installation/linux/

### Version

2023.7.2

**Comment by frenck** [comment]
> Because some mupped

Closing this feedback because of that. Please note, we have a Code of Conduct, which also applies to our GitHub repositories. The comment is pretty disrespectful towards the contributors who made that, and does not add anything besides punching someone in the face.

https://www.home-assistant.io/code_of_conduct/

Please do consider this an official warning.

../Frenck

**Comment by burner-** [comment]
Yes it is always better to focus defend position that even try understand real problem. But another hand this also explain why it is designed how it is. 
I may stand my point snappish but another hand with fast googling you see hundreds people with strugling with that image because of UEFI. And usually when you see that 3th party do multi page documentation to get something work (what have designed to have easy at theory) it mean that something is designed wrong. Also that home assistant community by it self had done own configurator script to configure kvm it show that instead of trying fix real problem (image it self had done disregarding best practices) it is fixed by giving painkillers. It should had rise alarms that something went wrong it design. 
But we can agree that we disagree what will software development need critical feedback.

**Comment by frenck** [comment]
I'm not declining the validity of your feedback; however, we do not tolerate violations of our code of conduct. There is no intention to communicate in such a tone with anyone. The contents of the feedback are not a justification for using such a tone/language.

This is not about agreeing to disagree, this is about you violating our CoC.

../Frenck
