### ISSUE TITLE
Swedish translation of "continue_on_timeout"

### ISSUE THREAD

**Issue by danka621** [home-assistant/home-assistant.github.io#28261]
### Feedback

Swedish translation of continue_on_timeout "Fortsätt vid paus" in gui for "Wait for trigger" condition is difficult to understand. 
Literally it means "when pause occurs, continue" (as soon as the pause occurs) which makes the concept of a trigger invalid. 

A better wording would be "Fortsätt efter paus" (continue after pause) or if the logic was inversed: "Stoppa/avbryt om tiden går ut" (Stop/abort if timeout).

### URL

https://www.home-assistant.io/docs/scripts/

### Version

2023.7.2

**Comment by frenck** [comment]
Thanks, it seems like you want to help out with our translations. However, you have submitted documentation feedback instead. We can't change our translations by updating our documentation...

If you want to help out with Home Assistant translations, you can do so, straight from your browser (no programming knowledge required). For more information see:

<https://developers.home-assistant.io/docs/translations>


../Frenck
