### ISSUE TITLE
Adding only bridge

### ISSUE THREAD

**Issue by Teleclovek** [home-assistant/home-assistant.github.io#28278]
### Feedback

I have problem. Integration added only bridge itself, but not lock or sensor. What can i do with it?

### URL

https://www.home-assistant.io/integrations/nuki/

### Version

2023.7.3

**Comment by pree** [comment]
Can you check in your integrations tab after adding if the lock and sensors were added? Sometimes, if the bridge is slow, it's not directly shown.

**Comment by Teleclovek** [comment]
No, there is still just bridge. 
![image](https://github.com/home-assistant/home-assistant.io/assets/75423722/8b900c55-cdb5-463f-9e27-944fcc2744fc)

**Comment by pree** [comment]
Any logs?
Please also try to do the request manually `curl HTTP://<bridge-ip>:8080/list?token=<token>`

**Comment by Teleclovek** [comment]
I tried to restart everything/remove battery for 10th time and now it appeared. Thanks for help.
