### ISSUE TITLE
Sonos Connect and a TV Box

### ISSUE THREAD

**Issue by PeterDemuynck** [home-assistant/home-assistant.github.io#28272]
### Feedback

I am searching for the right sensor that can indicate that some sound is getting through. The idea: I have a sonos Connect, that is 'constantly' waiting for some noise, when the television is switched on.  But I can also turn the Sonos into a player from Spotify.  
But mostly, the sonos Connect is on, waiting for the TV Box to send the signal.  
The Sonos connect is connected to some heavy amplifiers, that consume quite some energy. 
Therefore, when the Sonos Connect is sending some noise, I should be able to automate the detection of the signal, and automate the switch-on of the amplifiers. 
The same way, when there is NO sound for some minutes,  the automation should automatically be able to switch off the amplifiers.  Any suggestions? 

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2023.7.2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
