### ISSUE TITLE
Unable to figure out any Location / Station combinations that work

### ISSUE THREAD

**Issue by terren272** [home-assistant/home-assistant.github.io#28280]
### Feedback

Please provide working examples of how to format / look up Location and Station combinations that work.  My understanding is that the WAQI API does not require location, only station, so why does this integration?  Looking up a station and making a list would make this worlds easier to use.  So far, no luck.  Location does not give a complete list of nearby stations, if any.  Formatting is just guesswork. etc

### URL

https://www.home-assistant.io/integrations/waqi/

### Version

2023.7.3

**Comment by rommess** [comment]
up

**Comment by rommess** [comment]
any news ?

**Comment by jschinke1067** [comment]
How to figure out the Location Number? I don't see this information at all... This information is needed to add a another WAQI-Location into HA since version 2023.10 ...
