### ISSUE TITLE
Can we get both Hourly and daily Forcast ?

### ISSUE THREAD

**Issue by Flapoly** [home-assistant/home-assistant.github.io#28285]
### Feedback

-Do we have any technical reason to not been able to get both forecast Daily AND Hourly for the same location ?
It can be usefull to have both information.

-We can not create 2 instances (one Daily and the second Hourly) for the same location.

Cordialement

### URL

https://www.home-assistant.io/integrations/meteo_france/

### Version

2023.7.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by Quentame** [comment]
With `2023.9.0`+ it is possible to get both daily & hourly forcast types for one city with only one weather entity, see https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service

EDIT: You can also join the @hacf-fr [Discord](https://discord.hacf.fr/) or [forum](https://forum.hacf.fr/) to talk about HA in French
