### ISSUE TITLE
Number of samples as part of attributes

### ISSUE THREAD

**Issue by Flapoly** [home-assistant/home-assistant.github.io#28283]
### Feedback

Will it be possible to provide the number of samples used as part of the calculation with the statistics sensor attributes ?

### URL

https://www.home-assistant.io/integrations/statistics/

### Version

2023.7.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by ThomDietrich** [comment]
Hey @Flapoly check `buffer_usage_ratio` here: https://www.home-assistant.io/integrations/statistics/#attributes
Does that help your use case?

**Comment by Flapoly** [comment]
Hey ThomDietrich,
You are fully correct, by reading carefully the doc this does answer to my question
Thks for the quick answer.

**Comment by Flapoly** [comment]
Can be closed
