### ISSUE TITLE
Different values in HA compare to SMA web application

### ISSUE THREAD

**Issue by tobiasneumann42** [home-assistant/home-assistant.github.io#28294]
### Feedback

Hi, 

first of all a big thank you for providing the integration between HA and SMA products, much appreciated. Would not consider myself an expert (yet) when it comes to HA. Lately did some tinkering with HA and my SMA pv system. Strange thing, I ran into is that via the SMA HomeServer I can use the SMA iOS App to see monitoring data "almost" real time and historic. I added certain sensor values to HA. When I compare values from the App/web portal to data recorded by HA there are some sig. differences. HA shows about approximately 2kWh less than the SMA web portal for a particular day (see attached picture) July 19th.
<img width="101" alt="Bildschirmfoto 2023-07-23 um 21 06 10" src="https://github.com/home-assistant/home-assistant.io/assets/22684101/e27e37ad-8469-47ec-8918-542585372ae8">
<img width="215" alt="Bildschirmfoto 2023-07-23 um 21 00 35" src="https://github.com/home-assistant/home-assistant.io/assets/22684101/e97693d1-45bd-4d20-8cd7-67f1f1b03cd7">

Any guidance or explanation where this might come from? Not saying it could not be a problem between keyboard and chair ;) 

Thanks in adv.

Tobi

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2023.7.3

**Comment by frenck** [comment]
Hi there @tobiasneumann42 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here: <https://github.com/hoem-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by tobiasneumann42** [comment]
Hi Franck, 

apologies for my  mistake, will raise this through the proper link 

Thanks for the speedy response and advice 

Tobi
***@***.***

CCIE, CCIE Voice #1662

**Comment by frenck** [comment]
No problem! Glad I could point you into the right direction 👍 

../Frenck

**Comment by tobiasneumann42** [comment]
Hi French,

link from your email  https://github.com/hoem-assistant/core/issues> <https://github.com/hoem-assistant/core/issues%3E> I suppose should read https://github.com/home-assistant/core/issues

Regards

Tobi
***@***.***

CCIE, CCIE Voice #1662

**Comment by frenck** [comment]
Sorry! Yes, that was an honest typo. For full clarity, here it is again:

<https://github.com/hoem-assistant/core/issues>

../Frenck

**Comment by joostlek** [comment]
https://github.com/home-assistant/core/issues ;)
