### ISSUE TITLE
area card image not appears some times

### ISSUE THREAD

**Issue by kiloptero** [home-assistant/home-assistant.github.io#28296]
### Feedback

some times the images doesnt appear and need to refresh the dashboard to appears
![IMG_7380](https://github.com/home-assistant/home-assistant.io/assets/35468634/22b4a0f6-8580-4363-9026-c51a637a5593)
![IMG_7379](https://github.com/home-assistant/home-assistant.io/assets/35468634/cf696e07-06c6-4eac-8348-ca389a3fd969)
![IMG_7378](https://github.com/home-assistant/home-assistant.io/assets/35468634/587543a3-d539-46cc-915d-fead51d6abd2)
![IMG_7377](https://github.com/home-assistant/home-assistant.io/assets/35468634/75ff7405-44e8-417e-a2a6-b2aa6609f5a9)

### URL

none

### Version

2023.7

### Additional information

n/a

**Comment by dannytsang** [comment]
Please raise this in https://github.com/home-assistant/frontend because this repository is for the Home Assistant documentation.

**Comment by frenck** [comment]
As per above, use the frontend issue tracker to report issues.

Closing the issue on this end.

../Frenck
