### ISSUE TITLE
Changes to configuration.yaml file

### ISSUE THREAD

**Issue by sinemaker** [home-assistant/home-assistant.github.io#28290]
### Feedback

First, thanks for the integration.  
I have purchased an Ambient 2902 station and have added this integration to my Rasberry Pi HA instance using Settings/Devices & Services/Integrations and then I chose to [+ Add Integration], found the Ambient Weather Station integration, and added it.  That process asked me to enter my API_Key and Project_Key -- which I did.  It seems to be working fine.

In the instructions here it talks about adding lines to the configuration.yaml file that will set these same parameters.  I have not added these lines to the configuration.yaml file yet the integration seems to be working fine.

Perhaps the instructions are outdated and this is no longer necessary.  Please clarify.

### URL

https://www.home-assistant.io/integrations/ambient_station/

### Version

2023.7.3

**Comment by bachya** [comment]
This was fixed in https://github.com/home-assistant/home-assistant.io/pull/28349.
