### ISSUE TITLE
Viessmann ViCare does not work anymore

### ISSUE THREAD

**Issue by laatzu** [home-assistant/home-assistant.github.io#28302]
### Feedback

Getting followed error when try to re-add API-key: Unknown error occurred

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2023.7.3

**Comment by laatzu** [comment]
Deleting /config/.storage/vicare_token.save resolved the issue for me.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
