### ISSUE TITLE
Add state_attr( <entity>, "max") to Templating documentation

### ISSUE THREAD

**Issue by fhteagle** [home-assistant/home-assistant.github.io#28324]
### Feedback

https://www.home-assistant.io/docs/configuration/templating/

Looking at this page, I cannot find a mention of how to use the "max" attribute. This is useful to automate setting the highest possible value of an entity that has a dynamic maximum value. For example, the charging amps of the Tesla integration changes depending on what EVSE the car is plugged into. Setting an arbitrary high value fails, but using 

```
value: >- 
  {{ state_attr("number.charging_amps","max") }}

```

 in the service YAML successfully gets / sets the highest possible value.

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2023.7.3

**Comment by frenck** [comment]
This is all part of the Jinja2 syntax and engine, as linked in the introduction:

![CleanShot 2023-07-25 at 16 03 30](https://github.com/home-assistant/home-assistant.io/assets/195327/48a07e4e-fd43-4503-8b54-5dc3223619cf)


Ref: <https://jinja.palletsprojects.com/en/latest/templates/#jinja-filters.max>

**Comment by fhteagle** [comment]
@frenck - I looked at the link you provided. It covers the use of the |max filter, which is not what I was talking about. The link does NOT reference what I was talking about, which is how to get the maximum possible value of an entity that HA will accept.

**Comment by frenck** [comment]
There is no such thing, the example you provided:

> `state_attr("number.charging_amps","max")`

Is referring to fetching state attributes, which is documented here (on the same page):

![CleanShot 2023-07-25 at 18 31 03](https://github.com/home-assistant/home-assistant.io/assets/195327/b014b1e6-96be-43be-80b0-b8b43234e354)

State attributes differ per entity, entity type and can even be extended/differ per integration or device.

**Comment by fhteagle** [comment]
I disagree that state_attr() is sufficiently documented on that page. To wit, there is no description of the fact that you can use state_attr("some.entity", "max") in the way that I described. You might know it from having worked with HA, but most of us don't. "iterate over the states object" makes sense to people with a lot of programming experience, but is pretty cryptic to those who do not.

Think about it from a relatively new user's perspective. Try searching for how to solve the "setting the maximum value of a homeassistant entity in an automation" problem in the search engine of your choice, using whatever combination of search terms you like, and see if that link makes it into the top 10 pages of results.

Users like myself and others are running into situations where this knowledge would be useful, and the documentation does not provide it. Therefore, my suggestion to expand that section. If it's an "I don't want to put effort into it", fine, I happily volunteer to write the improvement if it will be included. But point blank saying, "it's there!" when it clearly is not and declaring won't fix does not help anyone.
