### ISSUE TITLE
Service Accounts role doesn't exist

### ISSUE THREAD

**Issue by skartknet** [home-assistant/home-assistant.github.io#28334]
### Feedback

On point 4.4.3 (Go to Google Cloud Platform), it says 'Select a role: Service Accounts and Service Account Token Creator.' but I can;t find Service Accounts. I can see Service Account Admin, Create Service Accounts, View Service Accounts, Delete Service Accounts. Should I enable all of them? That;s not clear. Thanks.

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2023.7.3

**Comment by jsprklst** [comment]
It is available by first selecting Service Accounts and then Service Account Token Creator, or by filtering on Service Account Token Creator:

![image](https://github.com/home-assistant/home-assistant.io/assets/1721525/9daf7bf9-a53d-43a8-ad5b-334c05930bf5)

**Comment by skartknet** [comment]
ah right, to me it sounds like we need 2 roles Service Accounts AND Service Account Token Creator. I didn't realise Service Accounts is the parent, and not a role on itself.

**Comment by c0ffeeca7** [comment]
Thank you for bringing this up, @skartknet :+1: 
And thank you for providing the screenshot, @jsprklst :pray:  That was very helpful.
