### ISSUE TITLE
Example for loading demo for specific integrations not valid.

### ISSUE THREAD

**Issue by mdeweerd** [home-assistant/home-assistant.github.io#28339]
### Feedback

```yaml
# Added to onfiguration.yaml entry

light:
  - platform: demo
```

results in error:

![image](https://github.com/home-assistant/home-assistant.io/assets/1504752/6d5167c3-4899-4c2f-b2b1-552e8537897f)

```plaintext
2023-07-26 17:19:35.767 ERROR (MainThread) [homeassistant.components.light] The demo platform for the light integration does not support platform setup. Please remove it from your config.
```

The same is true for the other domains/integrations.

Maybe the proper way to do so has changed.

### URL

https://www.home-assistant.io/integrations/demo/

### Version

2023.7.3

**Comment by gjohansson-ST** [comment]
Given [#94601](https://github.com/home-assistant/core/pull/94601) I think documentation should change
@emontnemery input?

**Comment by karwosts** [comment]
unstale. I still don't know what the correct way to load demo is anymore. A documentation update would be much appreciated.

**Comment by gjohansson-ST** [comment]
There is a mix in the demo platforms how they are loaded ~~so it needs to be fixed so it matches the documentation~~, update the documentation is needed once fixed.
It was on my todo list but then lost, will try to fix that.

**Comment by Napoleon-BlownApart** [comment]
Though I don't get the error the OP referred to, using `- platform: demo` doesn't work, but if I use `- platform: random` instead, I get an entity that I can use in my dash.

What is the status of this change?  The documentation still says it's valid to use `- platform: demo`.

**Comment by karwosts** [comment]
I believe the doc update will be released with 2023.11

If you see in the release candidate page, the `platform: demo` is gone:

https://rc.home-assistant.io/integrations/demo/

**Comment by gjohansson-ST** [comment]
Closing this as the ability to load single platforms has been removed with the 2023.11 release.

**Comment by mdeweerd** [comment]
With this evolution I think the wording should change on the documentation page.

It's now a single demo platform, not "Available demo platforms" an not "... to integrate a demo platform", but a single demo platform with emulated entities.
