### ISSUE TITLE
Camera name / sensors not matching name on Bonjour/UPnP

### ISSUE THREAD

**Issue by evercape** [home-assistant/home-assistant.github.io#28346]
### Feedback

I have given all my cameras unique names on Bonjour, UPnP, network host name.

When importing/activating new Axis cameras via the Axis integration, the camera name/sensors all start with the camera model/type and if more than one of the same in the network they get added a 0, 1, 2, ... and so on.

Is there any way to change this and if a UPnP name is given to rather use that instead?

Thanks
Martin

### URL

https://www.home-assistant.io/integrations/axis/

### Version

2023.7.3

**Comment by evercape** [comment]
See here the preview of the integration - the devices prior integration show the correct UPnP name, after integration they resort to the model number and mac address/serial number.

![Settings_–_Home_Assistant](https://github.com/home-assistant/home-assistant.io/assets/4627761/6af596db-1168-4f9d-b46a-2cae5194246a)

**Comment by Kane610** [comment]
There is no specific reason behind it, that's the way I chose to implement it at that point in time.
Since you have them paired you can rename the devices in Home Assistant.
