### ISSUE TITLE
Error when setting up PECO Outage Counter

### ISSUE THREAD

**Issue by julianrinaldi** [home-assistant/home-assistant.github.io#28354]
### Feedback

Setting up the PECO Outage Counter fails and displays this error:

```
401, message='Unauthorized',
url=URL(https://kubra.io/stormcenter/api/v1/stormcenters/39e6d9f3-fdea-4539-848f-b8631945da6f/views/74de8a50-3f45-4f6a-9483-fd618bb9165d/currentState?preview=false')
```

### URL

https://www.home-assistant.io/integrations/peco/

### Version

2023.7.3

**Comment by IceBotYT** [comment]
Good morning, are you still experiencing this error?

**Comment by julianrinaldi** [comment]
No, it seems to be working now.

**Comment by IceBotYT** [comment]
Great! I'll close the issue then :)

**Comment by IceBotYT** [comment]
@home-assistant close
