### ISSUE TITLE
Yolink Fobs stop working until I reload integration

### ISSUE THREAD

**Issue by stefanzierpersonal** [home-assistant/home-assistant.github.io#28355]
### Feedback

I have multiple Yolink fobs used as remotes for gates and garage doors in several vehicles. Two hubs. Every few days, HA stops receiving the remote button events until I reload the Yolink integration. This has happened for several months. Wondering if there is a way to make this more reliable. 

### URL

https://www.home-assistant.io/integrations/yolink/

### Version

2023.7.3

**Comment by joostlek** [comment]
Hey!

We use this repository for issues and feedback with our documentation. For bugs like these, please create a new one at https://github.com/home-assistant/core/issues. Thanks!
