### ISSUE TITLE
Login error (1013): request time is invalid

### ISSUE THREAD

**Issue by ricmendonca** [home-assistant/home-assistant.github.io#28367]
### Feedback

When installing the integration I try to configure it and I get a login error, could you help me?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.7.3

**Comment by ricmendonca** [comment]
the time zone of home assistant and tuya iot are the same

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
