### ISSUE TITLE
Invalid Authentication

### ISSUE THREAD

**Issue by sycko** [home-assistant/home-assistant.github.io#28374]
### Feedback

I know Life360 was having some issues earlier today, but they seem to be resolved now. However I removed my integration in the hopes of being able to reset it, but now I am unable to authenticate.

I have confirmed that I'm using the right credentials, and have tried from multiple devices. I cant seem to locate any additional information beyond "Invalid Authentication"

### URL

https://www.home-assistant.io/integrations/life360/

### Version

2023.7.3

**Comment by IIV-NATHAN-VII** [comment]
Same issue here.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
