### ISSUE TITLE
Undocumented commands for Viera are incorrect

### ISSUE THREAD

**Issue by peteS-UK** [home-assistant/home-assistant.github.io#28371]
### Feedback

The Viera doc lists 2 undocumented commands

Two further undocumented commands are "NRC_CHG_HDMI1-ONOFF" and "NRC_CHG_HDMI1-ONOFF" for selecting HDMI inputs.

This is incorrect.  The commands are NRC_HDMI1-ONOFF and NRC_HDMI2-ONOFF.  In fact, there are 4 of them, NRC_HDMI1-ONOFF, NRC_HDMI2-ONOFF, NRC_HDMI3-ONOFF & NRC_HDMI4-ONOFF

### URL

https://www.home-assistant.io/integrations/panasonic_viera/

### Version

2023.7.3

**Comment by peteS-UK** [comment]
Actually, there's a couple more - NRC_NETFLIX-ONOFF, NRC_APPS-ONOFF, NRC_MYAPP-ONOFF

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @peteS-UK :+1:
