### ISSUE TITLE
How to change HA configuration is absent

### ISSUE THREAD

**Issue by jtrumpio** [home-assistant/home-assistant.github.io#28373]
### Feedback

There is no documentation on how to edit a configuration once it's created.

Really it should be a simple paragraph on where the NUT configuration is stored in Home Assistant and how to make changes to it.  Deleting and re-creating a device isn't a good solution.  

It's also less than ideal that the password is stored in _plain text_ in core.config_entries under the /config/.storage directory.

### URL

https://www.home-assistant.io/integrations/nut/

### Version

2023.7.3

**Comment by jtrumpio** [comment]
I believe this to still be relevant.

**Comment by jtrumpio** [comment]
bueller?

**Comment by frenck** [comment]
Just checked the code, the documentation is correct. There is no method to reconfigure this integration (which is not a requirement).

../Frenck
