### ISSUE TITLE
Documentation is incorrect, refers to deprecated syntax.

### ISSUE THREAD

**Issue by erik3rik** [home-assistant/home-assistant.github.io#28370]
### Feedback

It has happened again.
The syntax/format has changed in .yaml for blueprints. But the documentation has not changed, and thus if simply copying a basic example from homeassistant.io then you immediately get deprecation warnings.

E.g. https://www.home-assistant.io/docs/blueprint/tutorial/
![Screenshot 2023-07-29 at 12 10 27](https://github.com/home-assistant/home-assistant.io/assets/46067475/3d7018ff-0ea2-482b-ba80-40d4fbb41f32)

When using that, you get:
![Screenshot 2023-07-29 at 12 11 02](https://github.com/home-assistant/home-assistant.io/assets/46067475/11607225-79d0-4415-8c3d-ae332c381763)

Please, stop changing the yaml-format all the time (it has happened like 5 times for template sensors!). At least without also updating the documentation.

### URL

https://www.home-assistant.io/docs/blueprint/tutorial/

### Version

2023.7.3

**Comment by kronos-next** [comment]
I have the same issue, do you know the correct format now valid?
