### ISSUE TITLE
Garage Door Opener (switch + binary-sensor), switch is just toggle !

### ISSUE THREAD

**Issue by SalsaGael** [home-assistant/home-assistant.github.io#28378]
### Feedback

- On your documentation (template cover), for the Garage Door example => you use "switch.turn_on" to open "switch.turn_off" to close and "switch.turn_on" to stop. But The garage opener switch is juste a toogle to change / stop direction, it will be better to use "switch.toggle" for the 3 case ?

### URL

https://www.home-assistant.io/integrations/cover.template/#garage-door

### Version

Latest

### Additional information

And it will be better to create the possibility to use cover.toggle in the template cover ? 

it will done : 

cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garage Door"
        position_template: "{{ states('sensor.garage_door') }}"
        toggle:
          service: switch.toggle
          target:
            entity_id: switch.garage_door
        icon_template: >-
          {% if states('sensor.garage_door')|float > 0 %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

**Comment by frenck** [comment]
> But The garage opener switch is juste a toogle to change / stop direction, it will be better to use "switch.toggle" for the 3 case ?

No, as it toggles relies on the current known state. If the device supports setting the state non-optimistic, it is better to use the actual intended intention.

../Frenck

**Comment by SalsaGael** [comment]
OK, thanks, i just found funny to turn on a Switch which is already on (or maybe off it's a random state) ... and for the possibility to use cover.toggle in template ?
