### ISSUE TITLE
Add option to enable showing all lights in a group

### ISSUE THREAD

**Issue by Kodemikkel** [home-assistant/home-assistant.github.io#28385]
### Feedback

An option to enable showing each and all individual lights in a group.
This would enable quickly setting the color/temp/brightness of each individual light within that group.

Another option would be to enable adding multiple entities, instead of only 1.

### URL

https://www.home-assistant.io/dashboards/light/

### Version

2023.7.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by Kodemikkel** [comment]
Ah, my bad. Will post it over there instead then :)

**Comment by frenck** [comment]
Don't worry about it 👍 

../Frenck
