### ISSUE TITLE
power_outage_memory

### ISSUE THREAD

**Issue by manlimbu** [home-assistant/home-assistant.github.io#28388]
### Feedback

it will be good if Recover previous state after power outage. every time my sony tv turn on it self after power outage even my tv status is off status before power outage.

### URL

https://www.home-assistant.io/integrations/braviatv/

### Version

2023.7.3

**Comment by bieniu** [comment]
This is a documentation repository, you should not open issues here that are not related to the documentation.

What’s more, IMO your feature request is related to the TV firmware, not the Bravia TV integration.
