### ISSUE TITLE
Needs more information about the inputs

### ISSUE THREAD

**Issue by Krispkiwi** [home-assistant/home-assistant.github.io#28380]
### Feedback

For height it doesn't state the relevance of this, for example do you want to just track flights at a height or is it your current height from sea level 

### URL

https://www.home-assistant.io/integrations/opensky/

### Version

2023.8.0

**Comment by joostlek** [comment]
Good point, I'll take a look at this tomorrow!

**Comment by joostlek** [comment]
Oh and for now, radius is in kilometers, and altitude (iirc in meters, but unsure about this one)

**Comment by Krispkiwi** [comment]
Apologies, misread the docs, presumably the integration is switching altitude for height in terms of its terminology and works the same way? I just had a air NZ flight go over my head and opensky missed it so figured I had done something wrong with the height.

**Comment by joostlek** [comment]
If height is set to 0 or unset it will just track everything

**Comment by Krispkiwi** [comment]
Is there any set up time it requires? Just checking as I've set it to 20km about 5 minutes ago and It's missed two flights that have entered the area

**Comment by ghost** [comment]
Are you sure about radius in kilometers? I have set it to 10 and am 7 kilometers away from an airport - no air traffic. When i set it to 10000, 2 aircraft have been registered. Just the number I have expected from looking at the Opensky map, but obviously way too low for a radius of 10000 kilometers.
Units of measurement in the config flow and in the documentation would be a bless.

**Comment by joostlek** [comment]
You are completely right, it got changed to meters. I will check on in on how to add more context to the numbers, I mean even I was confused so that's the perfect reason to get this straight
