### ISSUE TITLE
Regarding roborock battery life?

### ISSUE THREAD

**Issue by cybernard** [home-assistant/home-assistant.github.io#28408]
### Feedback

Thanks for all your hard work.

Can we get the battery percentage also for roborock?

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.7.3

**Comment by Lash-L** [comment]
It's is on the actual vacuum entity. If you click on the vacuum entity, you should see the battery life

**Comment by frenck** [comment]
> It's is on the actual vacuum entity. If you click on the vacuum entity, you should see the battery life

@Lash-L Actually, that is being removed from the vacuum entity... And a separate sensor entity should be created instead.

Anyways, I'm going to close the documentation feedback issue, as this is not documentation feedback, but a feature request. Please use our community forums for submitting feature requests.

../Frenck

**Comment by Lash-L** [comment]
@frenck good to know, thank you! I'll get a PR up for that today

**Comment by cybernard** [comment]
So the problem is, it is physically located in the diagnostic data from the roborock, but it is not listing in home assistant anywhere.
I checked all 19 entities exposed by roborock and none of them are the battery.

I download the diagnostic data and it was present there, but that does me no good.

**Comment by Lash-L** [comment]
There is a merged in PR to add it as a sensor and you should see it in the 2023.09 release
