### ISSUE TITLE
cannot login - missing details

### ISSUE THREAD

**Issue by tcurdt** [home-assistant/home-assistant.github.io#28401]
### Feedback

The docs are missing some essential information.

- What fritzbox permissions are required for the user?
- Does it have to be the `admin` or `fritz*` user?
- What about the password for `fritz*` user password? How can I find that if it's an automated user?
- The default port is 49000. Should it always be kept like that? I am not aware that my fritzbox is listening on 49000.
- Using the same username/password that works with [fritzsmart](https://www.home-assistant.io/integrations/fritzbox/) gives an "unknown error"

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2023.7.3

### Additional information

<img width="379" alt="Screenshot 2023-08-02 at 00 40 25" src="https://github.com/home-assistant/home-assistant.io/assets/13697/e5fd5263-97a3-425c-9173-ce200872d95c">

This is with a 7530 with the latest firmware (7.56)

**Comment by mib1185** [comment]
die you already read the [username](https://www.home-assistant.io/integrations/fritz/#username) section in the docs?

**Comment by tcurdt** [comment]
> die you already read the username section in the docs?

It's what made me open the ticket. Here is the text:

> The configuration in the UI asks for a username. 

Indeed it does.

> Starting from FRITZ!OS 7.24 the FRITZ!Box creates a random username for the admin user if you didn’t set one yourself. This can be found after logging into the FRITZ!Box and visiting System -> FRITZ!Box Users -> Users. The username starts with fritz followed by four random numbers. Under properties on the right it says created automatically. 

Yes, there is the `fritz*` user as it says.

But is it required for me to use that `fritz*` user? Why? Or can I setup a new user for HA?

I don't know the password of the `fritz*` user. So how can I provide the password to HA?

> Prior to FRITZ!OS 7.24 the default username was admin.

True - and what does that mean for the HA integration?
I somewhat hints that it needs to be a user with admin permissions.
Although it's not quite clear what means in details either.

<img width="1232" alt="Screenshot 2023-08-02 at 09 42 28" src="https://github.com/home-assistant/home-assistant.io/assets/13697/438beada-1d00-4dfe-b396-b270b33c1b76">

I would guess it needs the permissions to change settings?


And the port number is not mentioned in the docs.

**Comment by tcurdt** [comment]
Any input on the questions?

I don't mind making a PR for the docs - but I first need to understand what's needed here.

**Comment by tcurdt** [comment]
Or is this integration abandoned?

@mammuth, @AaronDavidSchneider, @chemelli74, @mib1185

**Comment by chemelli74** [comment]
Hi @tcurdt , the integration is maintained and works fine for most users.

Take care that the documentation in HomeAssistant won't be a substitution of the documentation from the vendor or a course on how thing works in the device.

That said, you need a username and a password to login via API.
If you don't change the default config yourself, then the default port is 49000 and is always active.
Same goes for the username: old firmware has "admin" new one has "fritzXXXX".
The password for both users is the one you use to login on the Fritz web page.

Simone

**Comment by tcurdt** [comment]
> Take care that the documentation in HomeAssistant won't be a substitution of the documentation from the vendor or a course on how thing works in the device.

Certainly. My only concern is UI of the integration.

What is a bit odd: When using the discovered device the UI seems to be different 🤔 It no longer asks for the port.

<img width="416" alt="Screenshot 2023-08-31 at 13 18 22" src="https://github.com/home-assistant/home-assistant.io/assets/13697/898d2279-3bf3-40e2-8a14-38649c06bb12">

But I now managed to login with the "fritzXXXX" username and the admin password.
I will see if I can break down the required permissions to use a separate account.

Would you be willing to merge PR for a documentation change?
It would be nice to make these things a bit more clear.

And it would also be good have a better error message than "Unknown error occurred".
For that I could open a real ticket.

**Comment by chemelli74** [comment]
> What is a bit odd: When using the discovered device the UI seems to be different 🤔 It no longer asks for the port.

Obviously, because the info in this case is in the zeroconf packet ;-)

> But I now managed to login with the "fritzXXXX" username and the admin password. I will see if I can break down the required permissions to use a separate account.

Depends on what you do with the integration, as you don't need only read rights but also write ( for example in order to change the internet switch status ).

> Would you be willing to merge PR for a documentation change? It would be nice to make these things a bit more clear.

Of course yes, but it also highly depends on the approach. Please don't write a too much technical description.

> And it would also be good have a better error message than "Unknown error occurred". For that I could open a real ticket.

AFAIK the library, https://github.com/kbr/fritzconnection, maps all known errors. If it's possible to better fine grade, please open a ticket there.

Simone
