### ISSUE TITLE
Values of energy dashboard gauges not available as entities

### ISSUE THREAD

**Issue by heikone** [home-assistant/home-assistant.github.io#28414]
### Feedback

Hello,
generally, I like the energy dashboard and the way it show the data. Really nice work!
But I would really appreciate, if there is any way to get the sensor values of the gauges like the grid neutrality gauge and solar consumed gauge as entities.
It would be helpful to describe the way in the documentation.
If there is no possibility to find them, I would like to request this feature.
Greetings,
Heiko

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2023.8.0

**Comment by dannytsang** [comment]
Hi @heikone 

I'm afraid it would be a feature request.
