### ISSUE TITLE
legrand home+ control

### ISSUE THREAD

**Issue by sjarmaking** [home-assistant/home-assistant.github.io#28413]
### Feedback

I'm having issues to connect to the legrand home+ connect app.

I'm getting the following alarm:
![image](https://github.com/home-assistant/home-assistant.io/assets/141273668/339d9902-ed21-4e39-b480-9f9899649abe)

I've followed the steps in the post where I attached the url from.

For the replys url I have https://xxx.xxx.xxx.xxx:8123
x's is the IP adres where I go to my home assistant. Is there something I'm doing wrong?

### URL

https://github.com/home-assistant/home-assistant.io/issues/17337

### Version

2023.8.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
