### ISSUE TITLE
Request: Add detection alarm delay sliders

### ISSUE THREAD

**Issue by AstonishingAston** [home-assistant/home-assistant.github.io#28418]
### Feedback

I've been using this integration for past few months and absolutely love it, thanks for the work this far!

I like it so much so, I just donated $20 to @starkillerOG as a thank you and also possibly as a part bribe to hopefully looki nto my suggestion/request.. please! 😅

I would love to have access to the time delay settings for the Ai person and Ai vehicle detect within HA for each camera individualy.
 (Setting in Reolink app are under alarm setting, detection alarm, alarm delay)

I'm using the ai person/vehicle to trigger lights and notifications (works an absolute treat!) But, when it rains, I've got 2 cameras that get rain on the lense and then causes the Ai triggers to go off randomly thinking the drops are people/cars.

Currently when it rains at night, I have to go into reoling app and change the time delay settings for Ai person/vehicle (normal at 0sec) and change them out to 3 or so seconds while it's raining to avoid faulse triggers.
If the delay settings were exposed to HA then I could make a simple dashboard button to press when it rains (extending timers) and press when it stops raining (set timers back to 0) or better yet, use local weather to trigger the button automatically!

(2 cameras I do this to are specifically a PoE Duo 2 and PoE RLC-820a)

Hopefully the above all makes sense as to what and why, otherwise I'll be happy to provide more info. 

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.8.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
