### ISSUE TITLE
Support for Enphase IQ Gateway

### ISSUE THREAD

**Issue by MustangMan** [home-assistant/home-assistant.github.io#28412]
### Feedback

Any thought to providing support for the Enphase IQ Gateway?

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.8.0

### Additional information

Just installed a new solar panel array using Enphase IQ8+ Microcontroller and the Enphase IQ Gateway

**Comment by klaasnicolaas** [comment]
Thank you for reaching out, there are people working on support newer hardware of enphase

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
