### ISSUE TITLE
Update HASS MQTT Discovery documentation for 2023.8 changes

### ISSUE THREAD

**Issue by FloatingBoater** [home-assistant/home-assistant.github.io#28427]
### Feedback

Hi,
With the 2023.8 changes to the [Entity Naming Standards](https://developers.home-assistant.io/docs/core/entity/#entity-naming) and recent [dev blog post on MQTT naming](https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/), it would help developers a if the [MQTT Discovery documentation](https://www.home-assistant.io/integrations/mqtt#mqtt-discovery) were updated to include these new resources, and the (now defunct) example test code updated.

1. Add a link to the recent [dev blog post on MQTT naming](https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/)
1. Add a link to the [Entity Naming Standards](https://developers.home-assistant.io/docs/core/entity/#entity-naming), and how this impacts MQTT Discovery.
1. Update the `mosquitto_pub`j examples as they currently include are one character off triggering the discovered entities Repair message (`Garden` and `garden` which were valid, but now are confusing).

A possible updated developer MQTT Discovery test example is:
```
# Send a MQTT Discovery message to create a motion sensor
# Note the difference between the DEVICE name and the motion ENTITY (of which there could be several)
# Note the motion ENTITY name is not required, or can be set to`None` - see the HASS Developer Blog
mosquitto_pub -r -h 127.0.0.1 -p 1883 -t "homeassistant/binary_sensor/garden/config" -m '{"name": "Motion ENTITY", "device_class": "motion", "state_topic": "homeassistant/binary_sensor/garden/state", "unique_id": "motion01ad", "device": {"identifiers": ["01ad"], "name": "Garden Sensor DEVICE" }}'
```
A screenshot of the result which you can freely use is in this post:
https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099/61

All the best,

James

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2023.8.0

### Additional information

This docs update started from this post:
https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099/61

**Comment by FloatingBoater** [comment]
Can I also suggest a more comprehensive example is added:

* The example Device is configured with optional extra information such as manufacturer, version, and the 'suggested_location' which can be used to set the Area.
* The example Entity adds optional extra values such as an icon, the device class and unit of measurement which both allow long-term logging to give the user data graphs.

```
# Send a MQTT Discovery message to create a soil moisture sensor
# Note the difference between the DEVICE name and the moisture ENTITY (allowing several sensor channels)
# Note the additional DEVICE parameters such as manufacturer, version, and the 'suggested_location' which can be used to set the Area
# Note the additional ENTITY  parameters such as an icon, the device class and unit of measurement which both allow long-term logging to give the user data graphs.
mosquitto_pub -r -h 127.0.0.1 -p 1883 -t 'homeassistant/sensor/grow-1_chan1/config' --retain -m '{"name":"Channel 1 ENTITY", "stat_t":"tele/grow-1/SENSOR", "val_tpl":"{{value_json.Channel1}}", "avty_t":"tele/grow-1/LWT", "pl_avail":"Online", "pl_not_avail":"Offline", "uniq_id":"grow-1_chan1", "dev": {"ids":["grow-1"], "name":"Grow 1 DEVICE", "mf":"Great Devices", "mdl":"Grow Sensor", "sw":"0.2", "sa":"Conservatory"}, "icon":"mdi:sprout", "dev_cla":"humidity", "unit_of_meas":"%", "expire_after":"1200", "frc_upd": true}'
```

**Comment by jbouwh** [comment]
In fact there was an update to the documentation. https://github.com/home-assistant/home-assistant.io/pull/27954. Further the recommend format for YAML configured items changed and all examples were updated as well.
In fact de options did not change, it is the behavior of the entity name that changes.
There is one discovery example on the main page that could use some improvements.
I'll parse through your suggestions to see what I can do with it to make things more clear.

**Comment by jbouwh** [comment]
See linked PR. I understand you want more examples, there is some more room for examples at the platform specific MQTT pages. It will become a bit fuzzy to include it all at the integration page. I hope I have explained the entity, device and friendly name relation better. Also with an example where the device class determines the entity name. I set it to draft so you can comment on it (or do suggestions).

I limited the changes to the existing examples.

**Comment by jbouwh** [comment]
@FloatingBoater Can you give some feedback on the proposed documentation changes in the linked pr? P.S. I'll set the PR ready for review, which means it might get merged.

**Comment by tommyjlong** [comment]
My only comment, is that I can't find any documentation for what the guidelines are for a Device name.
Seems there are a couple of choices:
1) is provided by the device provider (ex.  "name": "Acurite-986-1R-51778")
2) is it provided by the user (somehow) (ex. "name": "Bathroom")

I noticed the proposed documentation changed actually changed the Device name from 1) to 2).  Why was that?
In my way of thinking, a device may have a hardwired MQTT Discovery, and the user has no way to tell the device what its Device name is.  Given a user will want to give a device a name, I would think this is something they could edit in HA itself, but as far as I know, this is currently not possible.

**Comment by jbouwh** [comment]
> I changed the device_name to make the example more readable. Of course it is possible to do hardwired discovery, but in most cases the user has the option to make changes. The hard-wired device still needs a setup to be able to connect to the network en to the MQTT broker, and it needs to known security details.
In HA the device and entity name can be adjusted too if needed.
