### ISSUE TITLE
Hours to best price

### ISSUE THREAD

**Issue by thor9898** [home-assistant/home-assistant.github.io#28436]
### Feedback

The same way we have an attribute for hours to better price I think we should have an attribute for hours for best price

### URL

https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

### Version

2023.8.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
