### ISSUE TITLE
Timer Integration Documentation Out of Date.

### ISSUE THREAD

**Issue by TomMonk** [home-assistant/home-assistant.github.io#28435]
### Feedback

I was trying to use the documented feature "timer.change" and the code passed the syntax check and loaded, but when the automation fired off, things broke. After looking for "my bug"...

### URL

https://www.home-assistant.io/integrations/timer/

**Comment by frenck** [comment]
>  After looking for "my bug"...

Could you clarify what you mean by that? Could you provide logs, or reproduction of what is not working?

../Frenck
