### ISSUE TITLE
Syncthing install - impossible to obtain API Key

### ISSUE THREAD

**Issue by howiehowie93** [home-assistant/home-assistant.github.io#28438]
### Feedback

You cannot add the Syncthing integration as you need an API Key to proceed but can't get the key 'cos it's not installed ! 

### URL

https://www.home-assistant.io/integrations/syncthing/

### Version

2023.8.0

**Comment by zhulik** [comment]
What did you expect? You need to install and configure syncthing first, and only then setup the integration.
