### ISSUE TITLE
The Limited Trial max calls per hour

### ISSUE THREAD

**Issue by dbpage** [home-assistant/home-assistant.github.io#28430]
### Feedback

I suggest stating in the document that the Limited Trial is limited to 50 calls per day.  I suggest no faster than one call per half hour.

### URL

https://www.home-assistant.io/integrations/accuweather/

### Version

2023.8.0

**Comment by bieniu** [comment]
Is this information not enough?

![obraz](https://github.com/home-assistant/home-assistant.io/assets/478555/d014d954-fa68-49d1-8095-f5849dd820f6)


The integration changes the frequency of data updates depending on whether the forecast is turned on.

**Comment by frenck** [comment]
Closing, as it is documented.

../Frenck
