### ISSUE TITLE
What password?

### ISSUE THREAD

**Issue by unaffiliated** [home-assistant/home-assistant.github.io#28443]
### Feedback

The instructions say to “Follow the instructions on screen to complete the setup.” There are no instructions. Some instructions in one location or the other would be helpful.

What username and password is being requested? There is no information here..

### URL

https://www.home-assistant.io/integrations/nexia/

### Version

2023.8.0

**Comment by frenck** [comment]
> What username and password is being requested?

The username & password of your Nexia (Trane/American Standard) Home account.

**Comment by unaffiliated** [comment]
Thanks!  There is no indication a separate/external wifi accessed account is required from the home assistant perspective, esp. since this thermostat has zwave.  This appears to be assumed, and never discussed.

Thank you for the quick response.

**Comment by frenck** [comment]
> There is no indication a separate/external wifi accessed account is required from the home assistant perspective

The integration is classified as Cloud Polling.

../Frenck

**Comment by unaffiliated** [comment]
“Invalid authentication” using both nexia/trane radial options.
