### ISSUE TITLE
Why is generic camera being removed?

### ISSUE THREAD

**Issue by terren272** [home-assistant/home-assistant.github.io#28441]
### Feedback

Why is generic camera being removed?
Home assistant is telling me this is going away soon in a future update. Why would you do that if 7% of users are using it?
This is an important part of my dashboard

### URL

https://www.home-assistant.io/integrations/generic/

### Version

2023.8.0

### Additional information

![Screenshot_20230803_205614_Home Assistant](https://github.com/home-assistant/home-assistant.io/assets/98667860/b5031413-54d7-4b6c-a698-b251ebd817c1)

**Comment by frenck** [comment]
> Why is generic camera being removed?

It isn't removed. It is moving to UI configuration. As the message states, your existing YAML configuration has been imported and you can now safely remove the old YAML configuration from your configuration files.

../Frenck

**Comment by klaasnicolaas** [comment]
Home Assistant does not tell you that the integration will removed, but that the yaml support will disappear and that from 2024.2 you can set up the integration only via the UI config flow
