### ISSUE TITLE
Blink Doorbell support

### ISSUE THREAD

**Issue by trace4000** [home-assistant/home-assistant.github.io#28454]
### Feedback

Hi, will there be support for the Blink doorbell?  Looking to trigger automations from the doorbell button push.  Thanks.

### URL

https://www.home-assistant.io/integrations/blink/

### Version

2023.8.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
