### ISSUE TITLE
History Stats droping down time counting

### ISSUE THREAD

**Issue by fredejavite** [home-assistant/home-assistant.github.io#28458]
### Feedback

Hello, how are you ?
I'm trying to do a sensor that counts the time of a switch "on" since a specific date determinated by a input_datetime.

After every update, or if the switch is unavailable and without change the start, the totalizer does not continue totalizing the quantity and drop down the counting.
![image](https://github.com/home-assistant/home-assistant.io/assets/61960094/d87c4e37-d7c0-44f8-bcb8-fd13a5a8e6e0)

Here is my code:

Sensor 1
- platform: history_stats
  unique_id: tempo_refil_repelente
  name: Tempo Refil Repelente
  entity_id: switch.tomada_repelente
  state: "on"
  type: time
  start: "{{ as_timestamp(states('input_datetime.data_troca_refil')) }}"
  end: '{{ now() }}'
  
Sensor 2 (trying other way)
- platform: history_stats
  unique_id: tempo_refil_repelente_troca
  name: Tempo Refil Repelente Troca
  entity_id: switch.tomada_repelente
  state: "on"
  type: time
  start: "{{ states('input_datetime.data_troca_refil') | as_timestamp() }}"
  end: '{{ now() }}'
  
 Both does not work.
 
 And the template works fine:
 
![image](https://github.com/home-assistant/home-assistant.io/assets/61960094/35e4aa20-779e-44e1-9ef9-a45c4cba1259)

If anyone can help me. Thanks.
 

### URL

https://www.home-assistant.io/integrations/history_stats/

### Version

2023.8.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
