### ISSUE TITLE
ohmconnect change

### ISSUE THREAD

**Issue by chasemixon** [home-assistant/home-assistant.github.io#28455]
### Feedback

I have looked all over for the ohmconnect ID and I haven't been able to find it? could it be that ohmconnect has changed the website and no longer supports the ID, I found the device ID but that's the only thing I have found... Sure would love to get this device working if you can help me I'd really appreciate it!

### URL

https://www.home-assistant.io/integrations/ohmconnect/

### Version

2023.8.1

**Comment by robbiet480** [comment]
[As per the docs:](https://www.home-assistant.io/integrations/ohmconnect/#configuration)

> You can find your OhmConnect ID on the [OhmConnect API settings page](https://login.ohmconnect.com/api/v2/settings). It's the string after the last `/` in the URL, e.g., for the URL `https://login.ohmconnect.com/verify-ohm-hour/AbCd1e` your ID is `AbCd1e`.

It just worked for me so it should be working for you
