### ISSUE TITLE
Unifi Configuration examples

### ISSUE THREAD

**Issue by Paktas** [home-assistant/home-assistant.github.io#28463]
### Feedback

It would be great to include **configuration examples** or a link to it from the [main document](https://www.home-assistant.io/integrations/unifi/).
I am coming in for the first time and there is nothing helping me to understand how to configure Unifi information/sensors on Home Assistant dashboard.

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2023.8.1

**Comment by j4n-e4t** [comment]
What kind of configuration examples are you looking for? The Unify integration can be setup through the UI, you don't need any YAML-configuration. It's just your host, username and password:
![SCR-20230806-nond](https://github.com/home-assistant/home-assistant.io/assets/130256240/a0d3296f-788c-4e2f-8b6f-6a15bfa5ba15)

**Comment by Paktas** [comment]
Documentation says there are 3 sensor entities:
![image](https://github.com/home-assistant/home-assistant.io/assets/6200695/c3dcebe0-9040-410b-8e5a-f666656c21d5)

It's not clear what these sensors are and how should they show up (because they don't). I do not understand if these sensors should be returning one of:
- client entities (network clients) data
- Unifi devices (APs, switches etc) data

What format should the data be? Is it supposed to return a list of entities only or entities and their network data?
It's just not clear.

**Comment by j4n-e4t** [comment]
Ok, so after setting up the Unifi Integration, you will see all the network clients that are already configured as devices in HomeAssistant. (eg. If you previously configured a wifi light, you will now also see it added by the Unifi Integration.) That way, Unifi adds some new entities to your existing devices. (Like the current WIFI connection state.)

The 3 sensors you mentioned need to be enabled seperately:

1. Click on the UNIFI Integration
2. On your connected controller, you should find a button "Configure"
![SCR-20230806-qovq](https://github.com/home-assistant/home-assistant.io/assets/130256240/04a9e258-52cb-487f-8cbf-66d868e82a13)
3. Proceed to page 3/3 on the config page that just opened
![image](https://github.com/home-assistant/home-assistant.io/assets/130256240/c3d4a8c8-6836-4202-92e8-bf7d52b56456)
4. Here you can enable the Bandwith and Uptime Sensor

> Disclaimer: Doing so will add every device that is currently connected to your network or has an active DHCP lease as a device in HomeAssistant. So, if you have a lot of Network clients, this will get very messy in HA.

Now, you have an RX and TX sensor for each device, that indicates the used Bandwith (Recieve/Transmit) and an uptime sensor per device.

I hope this helps.

**Comment by j4n-e4t** [comment]
If this helps, I would open a PR against this repo to add this to the docs. 😉
If you want, you can take a look at my draft: [j4n-e4t/home-assistant.io](https://github.com/j4n-e4t/home-assistant.io/blob/c7a90f14a5fa559cb8b5eca7d5d1661470535b0d/source/_integrations/unifi.markdown?plain=1#L113C1-L116C164)

**Comment by Paktas** [comment]
Thanks, this clarifies things.
I was looking for Unifi device sensors (rather than dozens of network clients).
Are sensors for Unifi devices part of enabling all network clients?
Specifically I am looking at fetching current states from Unifi UDR router - get TX & RX values and plot them on chart.
From how it's written on docs - it's not clear if the 3 sensors are also unavailable for Unifi entities/devices unless enabled with a bunch of other clients?

**Comment by j4n-e4t** [comment]
I've benn playing arround with the setting a little bit but I clould find an option that allows me to see the Bandwith used by the Unifi APs. The RX/TX sensors only appear on the clients, not on the Unifi devices. Therefore, I'd say that the docs are incomplete here as well. 
From what [I've seen online](https://community.home-assistant.io/t/unifi-global-bandwidth-monitoring/361634), it is not possible to get a global RX/TX for your home network with a Unifi Router. 😔 (I probably should make this clear in the docs as well...)
However, such a feature cloud be really usefull... So, you cloud consider opening an Issue on the [home-assistant/core](https://github.com/home-assistant/core/) repo or maybe there is someone in the Discord, who already has a solution. 😉
I will update the unifi docs, so that it's easier to understand what sensors are available for which device.
