### ISSUE TITLE
Search for Discovery gives 404 error

### ISSUE THREAD

**Issue by stiltjack** [home-assistant/home-assistant.github.io#28461]
### Feedback

In the documentation, a search for "discovery" gives https://www.home-assistant.io/integrations/discovery/, which does not exist.

### URL

https://www.home-assistant.io/integrations/discovery/

**Comment by joostlek** [comment]
Yes, this integration has been removed in 2023.8. It was only used for Yamaha, bluesound, enigma2, sabnzb and Bose sound touch.

**Comment by stiltjack** [comment]
Ah yes, sorry. Normally, though, you get "No results found for xxxxx". Search for discovery gives "Oops page does not exist".

**Comment by joostlek** [comment]
As far as I know the search works with Algolia which is a third party who stores a copy of the data in their database for fast indexing. Maybe they haven't updated yet or something along those lines. Not sure how that process works

**Comment by stiltjack** [comment]
OK, thanks - sorry to disturb your Saturday!

**Comment by joostlek** [comment]
Don't worry, I also do this for fun :)

**Comment by witmannmark** [comment]
I also have same issue Integration error: discovery - Integration 'discovery' not found. But line discovery: is not in confuguration.yaml file. And still same error.
