### ISSUE TITLE
Unable to add OPPLE light

### ISSUE THREAD

**Issue by LancerTZ** [home-assistant/home-assistant.github.io#28471]
### Feedback

model: OP-DY160-300/300CC-W

nothing works after i updated my configuration.yaml file according the link below and restarted several times.

No error logs. There is a OPPLE light entity in entity list but its status is unavailable.

### URL

https://www.home-assistant.io/integrations/opple/

### Version

2023.8.1

### Additional information

Light works fine with remote and Mijia app and xiaomi_miot_auto cloud integration.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
