### ISSUE TITLE
MQTT Switch  example

### ISSUE THREAD

**Issue by Evgen2** [home-assistant/home-assistant.github.io#28480]
### Feedback

There is some inaccuracy on example text
Instead of 
_For a check, you can use the command line tools mosquitto_pub shipped with mosquitto to send MQTT messages. This allows you to operate your switch manually:

mosquitto_pub -h 127.0.0.1 -t home/bedroom/switch1 -m "ON"_

Worth writing something like:
_For a check, you can use the command line tools mosquitto_pub shipped with mosquitto to send MQTT messages. This allows you to operate your switch manually:

mosquitto_pub -h 127.0.0.1 -t home/bedroom/switch1/available -m online
mosquitto_pub -h 127.0.0.1 -t home/bedroom/switch1/set -m "ON"
mosquitto_pub -h 127.0.0.1 -t home/bedroom/switch1 -m "ON"_

### URL

https://www.home-assistant.io/integrations/switch.mqtt/

**Comment by j4n-e4t** [comment]
Why exactly would you want to change this? I'm not that deep into mqtt, so forgive me... But where is the issue with the given command example?

**Comment by Evgen2** [comment]
example with one command example leads to misunderstanding

1. One command example simply not working (in User Interface) without  "...available -m online"
2. Without home/bedroom/switch1 -m "ON" switch on user interface does'nt change its state and color

**Comment by j4n-e4t** [comment]
Ok, I understand. I can make this change and open a PR tomorrow if you want, so let me know. 😉

**Comment by jbouwh** [comment]
See linked PR. Hope it is more clear now.
