### ISSUE TITLE
Zeversolar Power off and Power on button?

### ISSUE THREAD

**Issue by wleusden** [home-assistant/home-assistant.github.io#28482]
### Feedback

Hi, thanks for the great integration, I previously used a similar integration called zeversolar-local and this one had also "buttons" as entities with which I was able to stop or start the inverter providing solar electricity. Quite useful when you have a dynamic energy contract. Would it be possible to add these buttons as entities to this integration?
(Somehow my other integration stopped showing devices and entities, so that one is now useless..)

### URL

https://www.home-assistant.io/integrations/zeversolar/

### Version

2023.8.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
