### ISSUE TITLE
Extra note for missing error message

### ISSUE THREAD

**Issue by pinpoint87** [home-assistant/home-assistant.github.io#28485]
### Feedback

A note for users who have not migrated their Nest account to a google account and try to get their device(s) back into HomeAssistant.

When your Nest account is not yet migrated to a google account you may receive the error message **No access to partner**.
Opening the Nest App on your phone, login and migrate your account under settings resolved this issue for me.

![image](https://github.com/home-assistant/home-assistant.io/assets/10941020/74a9c1d9-46c8-4907-b8ac-747e9b3e56fe)

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2023.8.1

**Comment by genestealer** [comment]
@pinpoint87 / @allenporter Please close issue, as I have I have raised a PR to update the official documentation.
https://github.com/home-assistant/home-assistant.io/pull/29085

History:
After spending hours, creating new projects, new users, new certs, I found a comment post on the bottom of website, of the video creator for the youtube video which is embedded in the Home Assistant Google Nest page.


I had not migrated my old Nest account to a Google account. Doing this migration via the Nest app fixed everything and allowed me to link my account without the "No access to partner" error message.

**Comment by allenporter** [comment]
Closing given https://github.com/home-assistant/home-assistant.io/pull/29085

**Comment by allenporter** [comment]
Thank you @genestealer 👍🏼
