### ISSUE TITLE
Missing list of sensor / switch

### ISSUE THREAD

**Issue by holblin** [home-assistant/home-assistant.github.io#28496]
### Feedback

It would be great to have the list of sensor, switch and capability of the integration for EV charger comparison.

### URL

https://www.home-assistant.io/integrations/tesla_wall_connector/

### Version

2023.8.1

**Comment by nortonsk** [comment]
Extend the sensors from device URL: http://$hostname/api/1/wifi_status might be good to add.

Thanks.
I have created a FR for that.
https://community.home-assistant.io/t/add-reading-wifi-status-data-and-write-it-as-sensors-for-tesla-wall-connector/607780
