### ISSUE TITLE
Image.Mqtt: Docs reference a `from_url_topic` that isn't defined.

### ISSUE THREAD

**Issue by LordMike** [home-assistant/home-assistant.github.io#28493]
### Feedback

In two places, the docs reference: `from_url_topic`.

* `content_type`: "This option cannot be used with the `from_url_topic` because the content type is derived when downloading the image." - probably should have been `url_topic`.
* Example configuration entry: "- from_url_topic: mynas/status/url"

### URL

https://www.home-assistant.io/integrations/image.mqtt/

### Version

2023.8.1

**Comment by jbouwh** [comment]
De MQTT image docs were a mess.It was cause because of some changes in the core PR. Hop it is okay now.
