### ISSUE TITLE
Mqtt.Climate: Initial temp cannot be "69.8F" as it is an integer

### ISSUE THREAD

**Issue by LordMike** [home-assistant/home-assistant.github.io#28491]
### Feedback

I was following along on the discovery docs for the Climate entity, and noticed that the default value for `initial` was 69.8F, but that's odd as the type is noted to be `integer`.

Should it have been a float?

### URL

https://www.home-assistant.io/integrations/climate.mqtt/

### Version

2023.8.1

**Comment by jbouwh** [comment]
It is an `int` as it was created with degrees Celsius in mind

**Comment by jbouwh** [comment]
I have opened a PR to allow a float value for the initial temperature. The documentation will also be updated.
That should solve your needs.

**Comment by jbouwh** [comment]
BTW, the documentation was correct about the initial temperature.

**Comment by LordMike** [comment]
That makes sense. It also then, makes sense to change it to float for consistency.

Luckily, integers are valid floats :)
