### ISSUE TITLE
url

### ISSUE THREAD

**Issue by aaafred** [home-assistant/home-assistant.github.io#28497]
### Feedback

I cannot login to one of the url's that are provided in the addon

I am using: https://server.growatt.com/

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.8.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
