### ISSUE TITLE
Sensor name defined by template 

### ISSUE THREAD

**Issue by HndrkDrs** [home-assistant/home-assistant.github.io#28500]
### Feedback

The good documentation made it easy for me as a novice to learn quickly and to venture into more complex tasks.
While experimenting with the scrape sensor, I came across the possibility of creating the name as a template in the documentation. This seems to distinguish the scrape sensor from others.
However, all my attempts were unsuccessful.
Here I would like to have a further hint in the documentation (e.g. whether I can use 'value' to represent the content of the target argument. Maybe it would then also make sense to adjust the order of the sub-items).

Also a practical example would be helpful and would improve the documentation at this point.

Best regards and thanks for your good work.
Hendrik

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2023.8.1

**Comment by gjohansson-ST** [comment]
I'm not sure I follow here as name is a template like all other fields you can use with template and use value, this etc. according to the documentation.
Not sure what adding examples would bring as context?

Perhaps it would be better if you try and if it fails for some reason post an issue with your example instead so we can look into it and fix it.

Thanks
