### ISSUE TITLE
Gardena bluetooth integration description is misleading

### ISSUE THREAD

**Issue by EmPeWe** [home-assistant/home-assistant.github.io#28515]
### Feedback

"The Gardena Bluetooth integration allows users to integrate their [Gardena Smart](https://www.gardena.com/int/products/smart/) devices using Bluetooth into Home Assistant."

This is misleading, because Gardena SMART devices and Gardena Bluetooth devices are totally different. For the SMART devices a Gardena SMART gateway is required and you can control these devices with the Gardena SMART App, a web browser or the API. However, Gardena bluetooth devices can be controlled only by the Gardena bluetooth app.

So the documentation should start like "The Gardena Bluetooth integration allows users to integrate their [Gardena Bluetooth devices](https://www.gardena.com/int/products/bluetooth-app/) into Home Assistant. It will **not** work with the [Gardena Smart](https://www.gardena.com/int/products/smart/) system. If you're looking for an integration for these devices, have a look at the [custom component integration](https://github.com/py-smart-gardena/hass-gardena-smart-system)"

Known Gardena Bluetooth devices are:
- Water Control: [01889-20](https://www.gardena.com/int/products/watering/water-controls/water-control-bluetooth/970481101/)
- Irrigation Valve: [1285-20](https://www.gardena.com/int/products/watering/sprinklersystem/irrigation-valve-9-v-bluetooth/970480401/)
- Mower (Sileno Minimo, City, Life) **not** SMART and **not** LONA:
  - Minimo: [15201-20](https://www.gardena.com/int/products/lawn-care/robotic-mower/robotic-mower-sileno-minimo-250-m2/970462803/), [15202-20](https://www.gardena.com/int/products/lawn-care/robotic-mower/robotic-mower-sileno-minimo-500-m2/970462903/)
  - City: [15010-20](https://www.gardena.com/de/produkte/rasenpflege/mahroboter/mahroboter-sileno-city-600-m2/970450603/)
  - Life: [15101-20](https://www.gardena.com/de/produkte/rasenpflege/mahroboter/mahroboter-sileno-life-750-m2/967845303/)
- Garden Pump: [9058-61](https://www.gardena.com/de/produkte/bewasserung/pumpen/gartenpumpe-6300-silentcomfort/970645401/), [9059-61](https://www.gardena.com/de/produkte/bewasserung/pumpen/gartenpumpe-6500-silentcomfort/970645601/)

### URL

https://www.home-assistant.io/integrations/gardena_bluetooth/

### Version

2023.8.1

**Comment by elupus** [comment]
It's confusing i know, but they are part of the smart series. https://www.gardena.com/int/products/smart/ is linking to supported products.

I will however reduce the mentioning of Smart in the docs. Since I agree it's missleading.
