### ISSUE TITLE
enable switching inputs

### ISSUE THREAD

**Issue by siobhanellis** [home-assistant/home-assistant.github.io#28514]
### Feedback

I have a FoxESS system and it can have multiple sets of solar panels, Mine has 2 sets. Initially I had been using the Total Solar output as the feed into the Energy dashboard, but I wanted to seperate them out. I could provide both... however, I now had to delete teh Total Solar and that meant I lost the history.

It should be possible to use one value to a certain date/time and then have another take over. That way you do not loose history.

### URL

https://www.home-assistant.io/docs/energy/solar-panels/

### Version

2023.8.1

**Comment by dannytsang** [comment]
Hi @siobhanellis 

This is a documentation repository so please open a feature request by going to New issue >Feature Request.
