### ISSUE TITLE
Add info on how to change the default polling rate from 2x per hour to 1x per hour or something else. 

### ISSUE THREAD

**Issue by ncd7** [home-assistant/home-assistant.github.io#28525]
### Feedback

The page has a note saying
"The AirNow API allows 500 data updates per hour, but since observations are only updated hourly, the default update rate is set to 2 per hour and should not trigger rate limiting. If you use this API key for other purposes, ensure the total request rate does not exceed 500 per hour."
But it doesn't explain how to change that default. It would be useful if the method of changing the default was indicated on the page. Thanks.

### URL

https://www.home-assistant.io/integrations/airnow/

### Version

2023.8.1

**Comment by asymworks** [comment]
The polling rate cannot currently be changed by the user (it is hard-coded), but I see your point that "default" implies that another value can be chosen.  I will clarify that on the documentation.
