### ISSUE TITLE
Roborock integration

### ISSUE THREAD

**Issue by Montaneste** [home-assistant/home-assistant.github.io#28535]
### Feedback

Currently i only have 6 entities available... :(
The commands are gone...

Already unninstalled / re-installed the integration :(

![image](https://github.com/home-assistant/home-assistant.io/assets/98612997/2ebcea3a-1fd1-4881-9623-f6ac781c70c2)

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.8.1

**Comment by joostlek** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍
