### ISSUE TITLE
Irrigation valves untested

### ISSUE THREAD

**Issue by EmPeWe** [home-assistant/home-assistant.github.io#28539]
### Feedback

> Irrigation valves are currently untested, but expected to work.

Valves have basically the same hardware as water controls and they share the same firmware according to the app.
I own both products and could help testing them

/EmPeWe

### URL

https://www.home-assistant.io/integrations/gardena_bluetooth/

### Version

2023.8.1

**Comment by elupus** [comment]
Give them a try then we can change rhe docs.
