### ISSUE TITLE
IPv6 issue may harm many users

### ISSUE THREAD

**Issue by ofirshw** [home-assistant/home-assistant.github.io#28547]
### Feedback

Integrating Nest to HA will fail if HA uses IPv6, which is the default configuration.
I propose to either add a description about this in the doc, or change the HA OS image.
(I'm using R-pi 4)

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2023.8.2

**Comment by allenporter** [comment]
I know that many users have trouble getting ipv6 to work but isn't it just if ipv6 is configured incorrectly on your network? There isn't anything special happening in nest and it's using all standard libraries.

**Comment by allenporter** [comment]
(Like, Google uses ipv6 so often nest is one of the first integrations that has a problem.)

I can see that home assistant detecting that ipv6 is misconfigured could help.

**Comment by ofirshw** [comment]
Hi Allan,

I'm not sure what's special or not about IPv6, but I'm sure that internet
connection should work out of the box. If this is a common cause of issues,
then it should either be disabled by the HA package originally, or at least
should be flagged as an integration step.

Thanks

**Comment by allenporter** [comment]
I don't know how common it is, but it comes up occasionally. I'm not sure I agree home assistant should stop supporting ipv6 -- my impression is it uses ipv6 if your network supports it but is not configured fully -- I'm not sure home assistant should stop supporting ipv6 because your network is misconfigured though. Seems like it would be nice to help you work through it in some way though.

Given this is the documentation component: I don't plan to change anything on the nest documentation here but welcome contributions.

**Comment by ofirshw** [comment]
Generally speaking, I completely agree with the saying that HA should support IPv6. As long as it's not a limiter of any important feature or integration.

I'm not sure I even know what "configuring IPv6 in my home network" means, and I believe that vast majority of users do not know. I never configured my IPv4 in any particular way, it just works. 

I come from vast and deep technical background, and I was able to find this cause in the community forms and to work around it. Moreover, the phenomenon as described in HA is a blank box saying "Error", not quite informative. I believe that 99% of the people will just give up, and that's a shame. In seeking for large audience for HA and for the Nest integration, I would strive to ease the flow as much as possible. Seemingly you did ~98% of the way with the actual integration code support and the really good documentation and video. I'm trying to help and make that last 2% :-)

**Comment by allenporter** [comment]
I welcome contributions to the documentation.

**Comment by ofirshw** [comment]
Will do, thank you!
