### ISSUE TITLE
Where do I enter this command?

### ISSUE THREAD

**Issue by buteomont** [home-assistant/home-assistant.github.io#28543]
### Feedback

There is a note that says: 

**By default, VirtualBox does not free up unused disk space. To automatically shrink the vdi disk image the discard option must be enabled:**

_**VBoxManage storageattach <VM name> --storagectl "SATA" --port 0 --device 0 --nonrotational on --discard on**_

Where do I enter this command?

### URL

https://www.home-assistant.io/installation/linux/

### Version

2023.8.1

### Additional information

Also, what are the consequences of not entering it?

**Comment by dannytsang** [comment]
You would run it in the terminal on your host operating system.

**Comment by buteomont** [comment]
Thanks, that's not clear on the installation instructions page. Does it matter if the VM is running or not?  It mentions that the command is to "shrink the VDI image"... can you elaborate?

**Comment by dannytsang** [comment]
Fair point. I will see if I can add to the note document around the terminal.

I'm not sure if it matters if the VM is running or not.

The --discard option is for hosts using SSDs and reduces the file size for unused virtual disk used by the VM. Criteria for this to work and more details can be found on https://www.virtualbox.org/manual/ch08.html
