### ISSUE TITLE
Google Home Event configuration affects triggers on HA

### ISSUE THREAD

**Issue by ofirshw** [home-assistant/home-assistant.github.io#28548]
### Feedback

Succeeding the integration, people may not be able to use triggers if they are not configured to work in Google Home.
This is counter intuitive, as Google Home app seem to only manage the notification in the app, but that's not the case.
I think it's important to say a word about this in the integration guide.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2023.8.2

**Comment by allenporter** [comment]
I'm not sure I understand. Are you saying Google home app settings allow triggers to work? This is mentioned in the docs under eash section I believe. I'd welcome contributions to further clarify.

**Comment by ofirshw** [comment]
I might have missed that in the docs, but only found it in the community
comments as a result of a frustrated google search. :-)

My point is that most people will go through the extremely detailed and
helpful integration guide, but will not browse much more once Nest
integration appears to show. Then I propose to clearly specify that in the
integration guide.

Adding to that, previous comments about times where these events did work
due to google side, causes great confusion. So a final up to date
clarification how to make that work, in the main door, is highly required.

Thanks

**Comment by allenporter** [comment]
I welcome contributions to further clarify the existing documentation.

**Comment by allenporter** [comment]
```
This feature is enabled by the following permissions:

...
- Other permissions in the Nest or Google Home apps.
```

**Comment by ofirshw** [comment]
The current writing is accurate, but is somehow vague (it may be new or not, didn't catch my eyes originally). 
The reason is that it's not really "permissions" (I'm not allowing or disallowing anything), but it's the actual configuration of which events are collected.

Since this is just where you talk about the actual triggers supported, I would write instead, outside the blue box:
"To receive the above mentioned events, make sure to enable them on Nest or Google Home apps."

I'm not sure where or how to contribute to the documentation directly, so I'm happy if you'll take this proposal into the document.

**Comment by allenporter** [comment]
At the very bottom of the page you can click the `Edit` button -- there is a little more detail about the process here:
https://developers.home-assistant.io/docs/documenting/#small-changes

**Comment by ofirshw** [comment]
Thanks. I'm trying to avoid creating a fork (as explained in the "small changes" section, but github insists on forking. :-/
