### ISSUE TITLE
db size query for postgres is wrong

### ISSUE THREAD

**Issue by ktpx** [home-assistant/home-assistant.github.io#28554]
### Feedback

The query to get db size for psql gives syntax error.  The below works, 

select pg_database_size('dbname')/1024/1024 as_dbsize;

### URL

https://www.home-assistant.io/integrations/sql/

### Version

2023.8.2

**Comment by gjohansson-ST** [comment]
Is the difference only the additional `()` in the example on the docs page?

**Comment by ktpx** [comment]
> Is the difference only the additional `()` in the example on the docs page?

Yeah, psql complained about those, so i removed and it worked ok.  The db name given there should probably indicate it has to be changed for whatever is being used.
