### ISSUE TITLE
Tuya requires identity verification to view secret key

### ISSUE THREAD

**Issue by LeeNeighoff** [home-assistant/home-assistant.github.io#28556]
### Feedback

Secret key now requires identity verification, which requires a vague "ID number" which is not the account UID for the linked Tuya account nor the "user code" listed in the Tuya app. Tuya has zero documentation on this, so it is unclear how to properly verify to view the secret key. This is mostly a Tuya issue it appears, but the setup documentation does not mention this requirement.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.8.2

**Comment by laurisb** [comment]
After trial and error, I found the workaround. In fact, you don't need to do the verification. Go to the account settings page at https://myaccount.tuya.com/account, change country (China was selected by default), and select Individual Developer for the Account Type. Now the Access Secret/Client Secret can be revealed.

**Comment by LeeNeighoff** [comment]
> After trial and error, I found the workaround. In fact, you don't need to do the verification. Go to the account settings page at https://myaccount.tuya.com/account, change country (China was selected by default), and select Individual Developer for the Account Type. Now the Access Secret/Client Secret can be revealed.

I'll give this a shot. Thanks!

**Comment by JasonBSteele** [comment]
I got the message 

> According to the Cybersecurity Law of the People's Republic of China, related laws, and the requirements of regulators, the identity of a user in mainland China must be verified before the user proceeds with cloud development services. If you are not from mainland China, submit a ticket to change the location of your account. Your account is not yet available for the Cloud Development Platform.


when I tried to reveal the Client/Access Secret, but I followed the advice above and changed my region in https://myaccount.tuya.com/account and  was then able to see my secret.

The documentation should be updated to add this step.

**Comment by frenck** [comment]
All solved in Home Assistant 2024.2, which introduced new authentication methods 👍 

../Frenck
