### ISSUE TITLE
Displays "kkWh"

### ISSUE THREAD

**Issue by dbpage** [home-assistant/home-assistant.github.io#28557]
### Feedback

I added this code to my configuration.yaml file. The display shows "kkWh".  I removed "unit_prefix: k," but this does not change the display, it only affects the calculation. Is there a fix or override to change ithe display to "kWh?"

### URL

https://www.home-assistant.io/integrations/integration/

### Version

2023.8.2

**Comment by dgomes** [comment]
as soon as the source get a new value the issue should fix itself

**Comment by dbpage** [comment]
Ok. It's not getting new values; typo in sensor reference. I can't modify or delete the integration thru the UI.  I'm trying to learn how to fix the sensor reference from lots of confusing info out there. You may close the ticket.
-------- Original message --------From: Diogo Gomes ***@***.***> Date: 8/13/23  2:16 PM  (GMT-05:00) To: "home-assistant/home-assistant.io" ***@***.***> Cc: Dennis Page ***@***.***>, Author ***@***.***> Subject: Re: [home-assistant/home-assistant.io] Displays "kkWh" (Issue #28557) 
as soon as the source get a new value the issue should fix itself
