### ISSUE TITLE
Add KP125M as partially supported Matter Device

### ISSUE THREAD

**Issue by sidens** [home-assistant/home-assistant.github.io#28558]
### Feedback

I have a few TP-Link Kasa [KP125M](https://www.amazon.com/Kasa-Smart-Monitoring-Compact-Certified/dp/B0BYGRLRS1) in use with my HA setup. It doesn't yet support energy monitoring (possible via the Kasa app), but does provide basic on/off switch functions.

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2023.8.2

### Additional information

<img width="1322" alt="Screenshot 2023-08-12 at 9 52 06 PM" src="https://github.com/home-assistant/home-assistant.io/assets/419871/47ad8fda-4036-414e-a52f-b1ead7cf763a">

Would recommend a new entry under supported matter devices like:
TP-LINK KASA KP125M (POWER PLUG) - PARTIAL SUPPORT
- Only on/off switch is supported. (No power monitoring available)
- Look for the M addition in the model name. A device without the M (regular KP125) is not Matter compliant.
- This device is available in the US only.

**Comment by jburgess777** [comment]
I recently purchased a Tapo P110M from Amazon UK. Similar to the P125M, it was added successfully as a Matter device on HA but fails to provide energy readings. 

The device declares itself as a Matter “On/Off Plug-in Unit”, device type 0x010a. I looked through the Matter 1.1 device and cluster specifications and I cannot find any mention of electrical measurements. This might explain why the Eve power plug also does not send power information via Matter.

**Comment by marcelveldt** [comment]
Matter does not support Energy measurements (yet), it will come in a later revision of the spec but I highly doubt these devices will be updated to support the new version.

Some vendors have implemented it in. custom way which is only accessible in their own vendor specific app.
No way we can show the data in HA unless the vendor wants to work with us to decrypt the custom data.

As for extending our documentation, we're actually going to remove the whole section with supported devices as it is outdated and not complete. there are better sources to get that information.
