### ISSUE TITLE
DTE Energy oPower Home Assistant Integration 

### ISSUE THREAD

**Issue by dbpage** [home-assistant/home-assistant.github.io#28552]
### Feedback

FYI: I requested DTE Energy to join other oPower-enabled companies to facilitate integration with Home Assistant.
Customer service 800-947-4747
www.dteenergy.com
energyreport@dteenergy.com

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2023.8.2

**Comment by tronikos** [comment]
@home-assistant close thanks but this is to track issues

**Comment by klaasnicolaas** [comment]
No integration issues, only documentation feedback 😉

**Comment by dbpage** [comment]
Where do I report integration issues?



On Aug 12, 2023, at 10:22 AM, Klaas Schoute ***@***.***> wrote:


Not integration issues, only documentation feedback 😉

**Comment by tronikos** [comment]
Here for documentation issues. https://github.com/home-assistant/core/issues/ for integration issues. https://github.com/tronikos/opower/issues/ for issues with the library.
