### ISSUE TITLE
No longer works since July 23rd

### ISSUE THREAD

**Issue by eerstebasdeboer** [home-assistant/home-assistant.github.io#28551]
### Feedback

I'm very sorry for being unable to reproduce the 'why' I'm merely user and no programmer. Will find my way around, but now found myself in a loophole. ever since July the reporting of production is no longer working, entities have gone, tried multiple reinstalls but can no longer activate the plugin anymore. paswords etc. are correct because Enphase lets me log in using those, can login locally to the envoy machine too. 
Just now after holidays updated both hass OS and the core, deleted the integration, restarted, reinstalled integration; no results.
btw; also tried the HACS (DEV) integration; also no luck, very frustrating, yet nothing I can do so it seems

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.8.2

**Comment by joostlek** [comment]
Hey there,

Your firmware probably got updated to v7.x. This started somewhere in January or march, and you're not the only one. In 2023.9 (released the first Wednesday of September) a new version of the integration will be included which will probably fix the issues.

If after you install 2023.9 and still encounter issues, please report them at home-assistant/core. 

Thanks!

**Comment by eerstebasdeboer** [comment]
Dear Joost, 
Thanks, sounds good, can't wait.
Any idea on how to re-activate the plugin in the time spent waiting for the update?

**Comment by joostlek** [comment]
If you contact me on discord @joostlek I can help you with that
