### ISSUE TITLE
Integration With Hisense AEH-W4E1

### ISSUE THREAD

**Issue by Phoenix2201** [home-assistant/home-assistant.github.io#28550]
### Feedback

Hi,
I have 4 devices with Hisense AEH-W4E1 Wifi module.
I tried the procedure for Hisense AEH-W4A1 WiFi device, but he didn't find the module on the network. We should wait for some new release? Thanks.

### URL

https://www.home-assistant.io/integrations/hisense_aehw4a1/

### Version

2023.8.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
