### ISSUE TITLE
bad link

### ISSUE THREAD

**Issue by mconverse** [home-assistant/home-assistant.github.io#28566]
### Feedback

The link to get the authorization code does not work

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2023.8.2

**Comment by dannytsang** [comment]
The link works for me ![Screenshot_20230814-221318.png](https://github.com/home-assistant/home-assistant.io/assets/567982/69dcee29-8086-41f3-afb1-83822a9cea35)

**Comment by mconverse** [comment]
You are correct, I ran the process again and got it this time, not sure why it was not working before.  Thanks!
