### ISSUE TITLE
homeassistant account and homedir on Linux / WSL

### ISSUE THREAD

**Issue by Gabbelebab** [home-assistant/home-assistant.github.io#28568]
### Feedback

Why not do something like:
sudo useradd -rm homeassistant -d /opt/homeassistant # why use a separate folder for home?

#Folllowed by:
sudo -u homeassistant -H -s
cd /opt/homeassistant    # or just cd as that will bring one to $HOME
python3.11 -m venv .      # x is important here as hass 2023.3.8 requires >= python 3.11         
source bin/activate

### URL

https://www.home-assistant.io/installation/windows/

### Version

2023.8.2

**Comment by frenck** [comment]
This is pretty much covered by:

![CleanShot 2023-08-14 at 13 23 18](https://github.com/home-assistant/home-assistant.io/assets/195327/e68c3584-eb82-4ca8-ae0e-009d88bee187)

This installation method is an advanced use case, in which we consider the users to be aware and knowledgeable to adjust these instructions to their own environments and needs.

../Frenck

**Comment by Gabbelebab** [comment]
I mostly agree. The text does cover it.
It sort of depends on whether having a separate home folder in general is advisable or not. As such I'm not necessarily convinced it is a subtle difference. Should one ever create a folder that is not used?
Could be just a matter of personal taste but I would say if there is no usage for or advantage of having a separate home folder instead of setting the homefolder to the installation folder, then don't include it in your documentation. But sure advanced users should be able to decide on their own how to implement it and why.
