### ISSUE TITLE
Gauge card

### ISSUE THREAD

**Issue by Herculezz55** [home-assistant/home-assistant.github.io#28572]
### Feedback

Any way to add click and hold options to the gauge card?

### URL

https://www.home-assistant.io/dashboards/gauge/

### Version

2023.8.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
