### ISSUE TITLE
Does this work for AirVisual Pro indoor, outdoor or both?

### ISSUE THREAD

**Issue by robertsearle** [home-assistant/home-assistant.github.io#28571]
### Feedback

Which hardware device does it work with?  Does this work for AirVisual Pro indoor, outdoor or both?

### URL

https://www.home-assistant.io/integrations/airvisual_pro/

### Version

2023.8.2

**Comment by bachya** [comment]
I developed it for the Indoor. I don't own an Outdoor, so unfortunately, I can't speak to whether the integration works there.
