### ISSUE TITLE
Opower - PGE electrical consumption data  stops at 2020

### ISSUE THREAD

**Issue by atharayanil** [home-assistant/home-assistant.github.io#28578]
### Feedback

Hi all, great integration; I was able to see gas usage data to present however my electrical consumption data for PGE stops at 2020. I’ve tried disabling and re-entering my PGE credentials but not change. Any way to force the more recent data to download?

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2023.8.2

**Comment by tronikos** [comment]
This is for documentation issues/feedback. Please create a new issue in https://github.com/home-assistant/core/issues

**Comment by tronikos** [comment]
@home-assistant close
