### ISSUE TITLE
Enable debug logging: three dots menu no longer appears in "Settings -> Devices & Services"

### ISSUE THREAD

**Issue by cbw** [home-assistant/home-assistant.github.io#28570]
### Feedback

With the refactor of the "Settings -> Devices & Services" page, the three dots menu no longer appears on integrations. To enable debug logging, you now much click through into the integration.

### URL

https://www.home-assistant.io/docs/configuration/troubleshooting/

### Version

2023.8.2

**Comment by CataCluj** [comment]
Most of my integrations suddenly have Debug Logging enabled and I see no way to disable it. The "Disable debug logging" only downloads the log and leaves it enabled.
