### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Kfrard** [home-assistant/home-assistant.github.io#28581]
### Feedback

The link given in the sentence "An access token for REST API configuration. Can be acquired from http[s]://your.server.org/integrations/tokens (please add at least Channel's Read and Action Execution permissions)." is wrong.

### URL

https://www.home-assistant.io/integrations/supla/

### Version

2023.8.2

**Comment by reedy** [comment]
What is the correct URL?

https://github.com/SUPLA/api-client-php#personal-access-token suggests

>Generate a Personal Access Token for you in the Integrations section on https://cloud.supla.org/ or your server instance.

**Comment by Kfrard** [comment]
https://cloud.supla.org/security/personal-access-tokens or your server instance
