### ISSUE TITLE
Add Wind Energy Production as a separate section as well as Solar Production

### ISSUE THREAD

**Issue by craigrallen** [home-assistant/home-assistant.github.io#28594]
### Feedback

Could you provide a dedicated Wind Energy section as well as Solar please?

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2023.8.2

**Comment by dannytsang** [comment]
Hi @craigrallen 

Can you raise this as a feature request using the **New issues** button please. This repository is for documentation feedback.
