### ISSUE TITLE
Missing step in KVM installation guide

### ISSUE THREAD

**Issue by jiiins** [home-assistant/home-assistant.github.io#28595]
### Feedback

The step illustrated in this post is missing but fundamental for the installation:
https://community.home-assistant.io/t/ha-os-installation-fails-on-uefi-in-qemu-kvm/435509/3

Without decompressing the image on Ubuntu and other distros, the VM is installed but will never work. I (and many others I saw) lost several hours figuring out the problem...

### URL

https://www.home-assistant.io/installation/linux/

### Version

2023.8.2

**Comment by reedy** [comment]
There seems to be a few variants of this, including more recently #28961

**Comment by c0ffeeca7** [comment]
Thank you for your feedback, @jiiins 

I think, in the meantime, this issue has been addressed by #27330, where a step was added to decompress the image after download.
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/d73b5529-729c-4db5-afc7-6745610cd075)
