### ISSUE TITLE
Confusing sentence in z-wave installation doc

### ISSUE THREAD

**Issue by Vansmak** [home-assistant/home-assistant.github.io#28605]
### Feedback

"You must uncheck this box if you are running the Z-Wave JS server in any manner other than the official Z-Wave JS add-on, including using Z-Wave JS UI add-on."  can be You must uncheck this box if you are running the  Z-Wave JS server with the Z-Wave JS UI add-on or any manner other than the official Z-Wave JS add-on."

This rephrasing makes it clear that the box should be unchecked if you're using either the Z-Wave JS UI add-on or any other method aside from the official Z-Wave JS add-on. It should help reduce confusion and ensure that users make the appropriate selection during the setup process.

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2023.8.2

**Comment by raman325** [comment]
Can you submit a PR for this? It's the same amount of work as opening a ticket but reduces the work for someone else 🙂

**Comment by Vansmak** [comment]
no, i dont know how. im sure most people were not confused by it like me anyway.
