### ISSUE TITLE
The sample automation from the OpenAI Conversation integration doesn't work

### ISSUE THREAD

**Issue by revolter** [home-assistant/home-assistant.github.io#28615]
### Feedback

![IMG_5060](https://github.com/home-assistant/home-assistant.io/assets/5748627/b3fbd0c6-9ebb-48e4-adb9-1502dd29e2b3)

![IMG_5059](https://github.com/home-assistant/home-assistant.io/assets/5748627/5fcfbf66-7a25-467b-882b-5de1568d1405)

### URL

https://www.home-assistant.io/integrations/openai_conversation/

### Version

2023.8.2

**Comment by dannytsang** [comment]
Are you able to provide the full text for the **Update image when weather changes** please?

**Comment by revolter** [comment]
This one?

![image](https://github.com/home-assistant/home-assistant.io/assets/5748627/9587d8ab-a831-489e-9933-2db796d85efb)

**Comment by dannytsang** [comment]
The text still goes off the screenshot but I suspect it could be your syntax.

Try replacing
```
{{ state(
```

with
```
{{ states(
```

**Comment by dannytsang** [comment]
I say your syntax, it looks like the documentation is wrong too. If that works then I can get that corrected.

**Comment by revolter** [comment]
Oh, I thought that it's clear from the title that I just copied the sample from the documentation, so that is the one that is incorrect.

**Comment by revolter** [comment]
It went a bit farther, but it didn't detect the actual weather:

![image](https://github.com/home-assistant/home-assistant.io/assets/5748627/5f04b24f-29cd-4b68-b218-2627f8583957)

And the automatic image entity that got added to my managed dashboard doesn't work:

![image](https://github.com/home-assistant/home-assistant.io/assets/5748627/67809310-7257-460b-993e-168eed7d55d0)

**Comment by dannytsang** [comment]
Sorry, that was my fault for checking against the docs.

Do you know if you have a weather.home entity? You can look it up in Settings > Devices & Services > Entities

**Comment by revolter** [comment]
I actually have `weather.forecast_home`, but most probably that's the default one. If it changed in a HA version, then maybe the docs should be updated accordingly.

But the image still doesn't work. Is it caused by the error in the template?

**Comment by revolter** [comment]
Hmm

![image](https://github.com/home-assistant/home-assistant.io/assets/5748627/affac59f-8aff-4de1-b8ac-0d361ac0070e)

**Comment by revolter** [comment]
I changed `512` to `"512"`, and now I get this:

![image](https://github.com/home-assistant/home-assistant.io/assets/5748627/fc96458b-5fd1-4936-a951-a88c2634d6de)

**Comment by dannytsang** [comment]
> I actually have `weather.forecast_home`, but most probably that's the default one. If it changed in a HA version, then maybe the docs should be updated accordingly.

It's been a while since I setup my Home Assistant so I'm not sure if or what the weather entity is setup.

I tried going through the tutorial and got it to work.
```
config_entry: f29e6b8696a15e107b4bd843de722249
```
was different in my setup. To find out what it is, I went to **Developer Tools** > **Services** and set this up in UI mode:
![image](https://github.com/home-assistant/home-assistant.io/assets/567982/011c46cf-3de7-4db9-9f97-5794d6c52b89)

Then switch to YAML mode and got the config entry value. Put that in your automation, reload and try again. I hope this works for you because on top your changes like putting 512 in quotes was also needed. Here's the image it generated for me:
![image](https://github.com/home-assistant/home-assistant.io/assets/567982/295d288b-18fd-4c30-a0da-6391c534362a)

**Comment by revolter** [comment]
After setting the correct entry ID, it worked. And, even if it's documented above the sample code, I would still explicitly state that you need to change that value.

**Comment by dannytsang** [comment]
Thanks for confirming. I agree and I'll update the docs with what you have found so that the next person wont have these issue.

**Comment by revolter** [comment]
Actually, what about the `image` error from the very first screenshot?

**Comment by dannytsang** [comment]
If you're using the VSCode add-on, it uses an extension so you'll need to report it to the [add-on](https://github.com/hassio-addons/addon-vscode) itself or the [extension](https://github.com/keesschollaart81/vscode-home-assistant). I'm not 100% sure which one is right and if I had to guess, i'd start with the extension.
