### ISSUE TITLE
Additional steps needed for google assistant linking

### ISSUE THREAD

**Issue by tux2000** [home-assistant/home-assistant.github.io#28623]
### Feedback

From https://community.home-assistant.io/t/can-no-longer-link-google-assistant/409495/19

Apparently Google has added a little splash screen to the flow that happens before it calls https://[YOUR _DOMIAN]/auth/authorize. In order for this info screen to work correctly, you now must complete the “Enter information required for the Actions directory” portion of the Actions setup overview. This requires you to provide:

    A description of your app
    A logo image for your app
    Your name and email
    A link to a privacy policy

Without this information the linking of the google account to the app is not possible, as e.g. documented here: https://community.home-assistant.io/t/google-home-could-not-reach-test-myapp-please-try-again/409356/2

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2023.8.2

**Comment by motphimtivi** [comment]
good
