### ISSUE TITLE
Very usefull

### ISSUE THREAD

**Issue by SocrateMobile** [home-assistant/home-assistant.github.io#28628]
### Feedback

Hello everyone,
In addition to the Flipr integration, I suggest you visualize your data in real-time on an LCD screen using the following code:

https://github.com/SocrateMobile/Affichage-Flipr-HomeAssistant/tree/main

### URL

https://www.home-assistant.io/integrations/flipr/

### Version

2023.8.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
