### ISSUE TITLE
Incorrect solar production reporting in energy dashbord

### ISSUE THREAD

**Issue by AkinysSurf** [home-assistant/home-assistant.github.io#28633]
### Feedback

Today my inverter production reached 500kWh mark and energy dashboard gone crazy - reported one hour solar production over 500kWh.
Meanwhile statistics table shows correct values.

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2023.8.3

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/115831177/aff554db-9040-43c2-a794-70687c35f62c)
[statistics-export.csv](https://github.com/home-assistant/home-assistant.io/files/12385487/statistics-export.csv)

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). Also indicate which integration your solar data comes from and screenshots of the history of the entity you use in the energy dashboard.

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
