### ISSUE TITLE
Improve UPB Documentation to handle external changes

### ISSUE THREAD

**Issue by jc508** [home-assistant/home-assistant.github.io#28638]
### Feedback

Documentation improvement suggestion....
At the end of 'Prerequisites'
"Note: the file name specified for the UPE file cannot be changed in the future. If you make alterations with UpStart and re-export make sure you use the same file name for the UPE file in the config folder" 

### URL

https://www.home-assistant.io/integrations/upb/

### Version

2023.8.3

### Additional information

If the intention was to allow a different file then that bit is broken. If you choose ADD ENTRY a second time it always comes back with  'Device is already configured'

**Comment by gwww** [comment]
@home-assistant complete

**Comment by gwww** [comment]
@home-assistant close
