### ISSUE TITLE
Documentation change

### ISSUE THREAD

**Issue by jackb007** [home-assistant/home-assistant.github.io#28630]
### Feedback

I think it would be helpful to mention Home Assistant needs restarting completely after any changes to alerts or to the alarm control panel for the changes to take effect. It even needs restarting for an alert or alarm entity to be created. This is in contrast to automations, for which a reload of the automations yaml file is enough for changes to take effect or for a new automation to be created. I spent a full day trying to figure this out. In my opinion, this information should be at the top of the page.

### URL

https://www.home-assistant.io/integrations/manual/

### Version

2023.8.3

**Comment by klaasnicolaas** [comment]
This is explained here: https://www.home-assistant.io/docs/configuration/#reloading-changes

**Comment by jackb007** [comment]
Nobody reads the full documentation before trying to set up an alarm or an alert. We normies go to Google, put "alarm home assistant," and then look at the code examples. It would cost nothing to add one line and would save a lot of people a lot of frustration

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by klaasnicolaas** [comment]
If you add it to one integration, you should actually adjust it at all integrations (where it still uses yaml for config). A quick search on "home assistant configuration.yaml" also brings you to that same page 😉

**Comment by jackb007** [comment]
I don't even know what you mean by "it," and I don't see why people would search for "home assistant configuration.yaml" when trying to set up an alarm. Most people don't even know what a yaml file is. I think you're assuming most people who use Home Assistant are experts, but I don't think they are. People just want a message sent to their phone when sensor x does y, or a light to switch on, or an alarm to go off. One shouldn't even have to code an alarm or an alert. One shouldn't have to install HACS through a command line and then Alarmo just to get basic alarm functionality on an automation program that requires its own computer to run. Do you read your full car's maintenance manual before you start driving it when you buy a brand new car? Do you expect somebody to have read the full manual before they can change the windshield wiper speed or the heating temperature? Do you expect them to have a basic knowledge of the laws of thermodynamics? But hey, I haven't done any coding on this, so I have no right to complain. I just thought a tiny change would save a lot of people a lot of trouble in the future.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
