### ISSUE TITLE
Add collection of SNMP OIDs

### ISSUE THREAD

**Issue by ptersilie** [home-assistant/home-assistant.github.io#2863]
I just tried to setup a device tracker with SNMP, however I didn't know the OID for my router (Archer VR600). Only through some trial-and-error using `snmpwalk` I managed to figure out that the OID for connected devices is `1.3.6.1.2.1.3.1.1.2`.

I'd like to write that information down somewhere, but I feel if we start adding more examples to https://home-assistant.io/components/device_tracker.snmp/ this page gets long really quick.

Should we add a new wiki page collecting device OIDs to people can find them easier in the future? I'm happy to create a PR for this. Thoughts?

**Comment by fabaff** [comment]
Just add it to the "OID examples:" list. I don't see the need to create an addition page just for the OIDs as there are only so many router which support SNMP. 

Perhaps we could think about switching to a table instead of a list.
