### ISSUE TITLE
growatt integration broken

### ISSUE THREAD

**Issue by pixelcatcher** [home-assistant/home-assistant.github.io#28651]
### Feedback

Unknown error occurred
during login

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.8.3

**Comment by joostlek** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍
