### ISSUE TITLE
The provided info here does not work on HassIO.

### ISSUE THREAD

**Issue by JorisZzz** [home-assistant/home-assistant.github.io#28669]
### Feedback

It took me a while to find it, but someone made a decent addon for HassIO integration. 
I think it's worth a mention:
https://github.com/FloridaMan7588/mochad-ha-addon

### URL

https://www.home-assistant.io/integrations/mochad/

### Version

2023.8.3

**Comment by frenck** [comment]
Hi there @JorisZzz 👋 

Thanks for the suggestion, however, custom add-ons and integrations are not supported by the Home Assistant project.

../Frenck
