### ISSUE TITLE
Why is there no Local MAC address version of this?

### ISSUE THREAD

**Issue by terren272** [home-assistant/home-assistant.github.io#28666]
### Feedback

Why is there no Local MAC address entity, when Local IP address exists?
Please create one that exposes the local MAC address, same as the local IP address, thanks.

Please also create a way to expose the IP and MAC address of other devices on the LAN.  
This would be VERY useful.
THANKS

### URL

https://www.home-assistant.io/integrations/local_ip/

### Version

2023.8.3

**Comment by motphimtivi** [comment]
waiting

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
