### ISSUE TITLE
Should Walmart's Merkury products be added?

### ISSUE THREAD

**Issue by cadcoke5** [home-assistant/home-assistant.github.io#28660]
### Feedback

For many years Walmart sold the cheapest smart devices, under the Merkury brand. But a search for Merkury, on the integrations list, did not bring anything up. Later, in a forum,  I was told by two people that this was a sub-brand of Tuya.  Though, there seem to be a similar number of people who couldn't get a Merkury product to connect.  So, I am unsure if listing Merkury here is a help or not.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.8.3

**Comment by frenck** [comment]
Tuya sells compatible products under thousands of brands around the world, it would be an impossible list to maintain and look at. At this point, we decided not to keep such a thing.

../Frenck
