### ISSUE TITLE
Integration not working on a RLC-423 with Hardware-Version IPC_3816M

### ISSUE THREAD

**Issue by tzippy84** [home-assistant/home-assistant.github.io#28668]
### Feedback

Since the device can not be updated to the latest firmware (It's only available to Hardware-Versions IPC_51516M), the integration is not able to log in:
"Host 192.168.0.112:80: failed to subscribe push: subscription_send: failed to retrieve subscribe_url from 192.168.0.112:80

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.8.3

**Comment by starkillerOG** [comment]
@tzippy84 I took a look and it seems like the RLC-423 does not support ONVIF and therefore the integration fails to setup.
I looked at the reolink specs and indeed the RLC-423 is not listed as supporting ONVIF: https://support.reolink.com/hc/en-us/articles/900000617826/
Note that the RLC-423 is a discontinued model, so firmware updates from reolink are unlikely at this point.

However not all hope is lost: it does seem like the rest of the HTTP API is working perfectly fine.
ONVIF is only used to receive push updates for the motion/AI events, but the integration already has fallback to fast polling every 5 seconds for these events in case ONVIF is failing. So basically everything should be able to work even withouth ONVIF.

I am willing to adjust the code such that the RLC-423 is supported and will work, but I will need some debug logs from you.
Please enable debug logging of the reolink integration and then try to setup the RLC-423 and post the .txt debug log here.

Specifically I need to know the response to the `GetAbility` command and then the version of the `onvif`
And I need to know the response to the `GetNetPort` command.

**Comment by starkillerOG** [comment]
@tzippy84 since this is not a documentation but a code issue, I will close the issue here and open a new issue in the core repository.
I will tag you in the new issue, please respond there.

**Comment by starkillerOG** [comment]
Please continue the discussion here: https://github.com/home-assistant/core/issues/98879
