### ISSUE TITLE
Integrating WeEnergies

### ISSUE THREAD

**Issue by capritzl** [home-assistant/home-assistant.github.io#28679]
### Feedback

Any plans for adding we-energies.com to the list of available electric & gas companies?

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2023.8.4

### Additional information

Any plans for adding we-energies.com to the list of available electric & gas companies?

**Comment by tronikos** [comment]
No such plans from me. It's up to the community to add support for more utilities. I'll be happy to review and merge any PRs in the underlying library https://github.com/tronikos/opower

**Comment by tronikos** [comment]
@home-assistant close
