### ISSUE TITLE
Explains problem, but not how to resolve it

### ISSUE THREAD

**Issue by ithinkihaveacat** [home-assistant/home-assistant.github.io#28675]
### Feedback

This page explains that the reason an expected data source is not listed is because of a mismatch between the expected and actual types. However, it does not provide any information on how to find either the expected *or* actual types. (The suggested resolution is to contact the developer of the integration.)

So for example in a given dropdown perhaps I am expecting to see entity `A`. However, I see `B` instead. How can I compare `A` and `B`, to see how they differ? What are some ways to configuring `A` (or creating a derived value, via a template) to make it available?

### URL

https://www.home-assistant.io/more-info/statistics/

### Version

2023.8.3

**Comment by frenck** [comment]
This page explains this is a bug, bugs should be reported so they can be fixed.
If you encounter this, and think an entity isn't listed that should have been listed, please open up an issue in our issue Core issue tracker.

![CleanShot 2023-08-24 at 01 08 20](https://github.com/home-assistant/home-assistant.io/assets/195327/33d11748-068e-43be-b625-f61ae06095bd)

> However, it does not provide any information on how to find either the expected or actual types. (The suggested resolution is to contact the developer of the integration.)

Correct, that is not the scope of this page. Even if it would provide this information (technical) information in some way, it would not be helpful, as this cannot be addressed by an end-user, as it is a bug.


../Frenck

**Comment by ithinkihaveacat** [comment]
I'm not sure this is always a bug.

I ran into this because the integration of my [Shelly Pro 3EM](https://kb.shelly.cloud/knowledge-base/shelly-pro-3em) [disabled](https://github.com/home-assistant/core/blob/d8f0c090cf6ce10c061311885b2e116058342c00/homeassistant/components/shelly/sensor.py#L618C33-L618C33) three entities I wanted to make use of. The developer probably disabled them by default because there's another entity that is the sum of these three, and typically you only care about the sum, not the individual components.

However, when I found the source code for the entities, by comparing the code I was able to see why one was available in the UI, but the three other entities where not, and (in this case) was able to enable it via the UI.

Ideally, this information would've been exposed in the UI (maybe it is? I don't know how to find it) and this error page would have told me how to compare the two.

**Comment by frenck** [comment]
> I ran into this because the integration of my [Shelly Pro 3EM](https://kb.shelly.cloud/knowledge-base/shelly-pro-3em) [disabled](https://github.com/home-assistant/core/blob/d8f0c090cf6ce10c061311885b2e116058342c00/homeassistant/components/shelly/sensor.py#L618C33-L618C33) three entities I wanted to make use of. The developer probably disabled them by default because there's another entity that is the sum of these three, and typically you only care about the sum, not the individual components.

That is not related to any of this. Disabling/enabling entities is a general feature of Home Assistant and not associated with the energy dashboard or long-term statistics.

Documentation on enabling entities can be found here: <https://www.home-assistant.io/common-tasks/general/#enabling-entities>

> Ideally, this information would've been exposed in the UI (maybe it is? I don't know how to find it)

Those disabled entities are shown on the device pages.
