### ISSUE TITLE
2 Commissioned chargers and only 1 shows up in Home Assistant 

### ISSUE THREAD

**Issue by jubens** [home-assistant/home-assistant.github.io#28674]
### Feedback

I have 2 Tesla Wall Connectors that are interconnected in what they call "Commissioning". One of the chargers works as the main unit and that one will show in Home Assistant. The other one works as a child unit and together, when "Commissioned, they will adjust how the power is shared between the two connected cars, but the "child" unit won't show in Home Assistant. If I connect to the "Main Unit", using the Tesla instructions, then I can see both chargers and I'm able to see the different stats for both chargers individually. I'm specifically looking to be able to know when each charger is individually unplugged from the cars so I can use that in my  Home / Away Automations. This is the first time I use Github and I hope that all that makes sense.  If I'm posting this in the wrong place, please excuse that. 

### URL

https://www.home-assistant.io/integrations/tesla_wall_connector/

### Version

2023.8.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
