### ISSUE TITLE
major issue -- unable to install

### ISSUE THREAD

**Issue by thetoasta** [home-assistant/home-assistant.github.io#28681]
### Feedback

you **cannot** as virtualbox has discontinued the M1 option. also, how would I do it on UTM _(i own utm)_

### URL

https://www.home-assistant.io/installation/macos/

### Version

2023.8.4

**Comment by frenck** [comment]
We currently have not set out to support UTM in our documentation. You could try looking at our community forums for alternative community-supported installation instructions: [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck

**Comment by thetoasta** [comment]
thanks.
