### ISSUE TITLE
Could not access the Web UI 

### ISSUE THREAD

**Issue by guussprokkereef** [home-assistant/home-assistant.github.io#28685]
### Feedback

I installed HA in Docker on my MacBook, because I wanted to test the installation before buying a Pi. Everything went very smooth, except that I could not access the Web UI through my browser. A small tweak in the compose.yaml fixed it. Maybe this is helpful for other users.
`version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123`

### URL

https://www.home-assistant.io/installation/raspberrypi#docker-compose

### Version

2023.8.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Please note, that running Home Assistant in Docker is not supported on MacOS.

Thanks! 👍

../Frenck
