### ISSUE TITLE
Integration status

### ISSUE THREAD

**Issue by TracyP** [home-assistant/home-assistant.github.io#28686]
### Feedback

As far as I can tell, this integration no longer works

### URL

https://www.home-assistant.io/integrations/flick_electric/

### Version

2023.8.4

**Comment by frenck** [comment]
Hi there @TracyP 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please submit issues with integrations here: 

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
