### ISSUE TITLE
Rust dependency required

### ISSUE THREAD

**Issue by jakpor** [home-assistant/home-assistant.github.io#28690]
### Feedback

I am specifically referring to the part of the installation for [RaspberryPi](https://www.home-assistant.io/installation/raspberrypi).

Recently, I tried to install HASS using docker-compose and with manual core installation. In both cases, installation failed due to missing rustc for bcrypt and cryptography python packages. 
In both cases, the solution was to install rust using the official [website](https://www.rust-lang.org/tools/install). 

However, when I copied the error message and searched that problem solutions I found some unfortunate approaches, which forced me to reinstall the system after applying them. I know, my fault was to follow them blindly, but I really missed just a word, that rust is needed in every case of manual installation and in docker-compose cases.

I understand that rust is in fact a requirement of dependency of dependency of HASS, and it doesn't have to be added in the HASS installation guide. But for Rasbian installation it is always a required step, because rustc is not installed by default or it is outdated, and rust installation fixes it. 

Considering that there exists some bad solutions to that problem, I would suggest adding a note with something like: 
>  Info:
Some dependencies of HASS depend on installation of rust, which might be outdated on many Raspberry Pi operating systems. In that case, it has to be installed [manually](https://www.rust-lang.org/tools/install).

This dependency information is relevant for both docker-compose and core installation (in linked docker-compose manual, rust isn't mentioned as well). I know, that it is an advanced installation procedure, but if there is a prerequisite for python 3.11, there might be also a note about rust. 

Also, here is the link to cryptography package [dependency](https://cryptography.io/en/latest/installation/), which has multiple warnings that rust is usually outdated for example for Debian before Bookworm - and Bookwork was released [10.06.2023](https://www.debian.org/releases/bookworm/)!. 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.8.4

**Comment by webturner** [comment]
Similar issues installing on Raspberry Pi following the [Install Home Assistant Core](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core) instructions. 

`This package requires Rust >=1.56.0.`
