### ISSUE TITLE
Feature Request: Remembering which torrents were already paused so it doesn't un-pause them

### ISSUE THREAD

**Issue by ltctceplrm** [home-assistant/home-assistant.github.io#28693]
### Feedback

Would it be possible to have the Deluge integration remember which torrents were already paused before pressing the pause button so that when you press un-pause  in the integration it only un-pauses torrents that were active originally?

Or perhaps rather than pause and un-pause it could set deluge to throttled like with the scheduler add-on that Deluge has? That way they're not paused but they are set to queued instead
![](https://i.imgur.com/727VtQm.png)

### URL

https://www.home-assistant.io/integrations/deluge/

### Version

2023.8.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
