### ISSUE TITLE
Unable to log in to China account

### ISSUE THREAD

**Issue by mac6600** [home-assistant/home-assistant.github.io#28694]
### Feedback

hi 

Since August 20, 2023, the BMW China account has been unable to log in to HA , as it displays "Connection Failed" regardless of whether the correct account has been entered (86 has already been entered). I have checked the account and password and they are completely correct.

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2023.8.4

**Comment by rikroe** [comment]
There were API changes to the login, see https://github.com/bimmerconnected/bimmer_connected/pull/561

Also, this is the wrong repositorty for bugs. This is for documentation only, it should have been created in https://github.com/home-assistant/core/

**Comment by rikroe** [comment]
@home-assistant close
