### ISSUE TITLE
Missing attributes in entry event 

### ISSUE THREAD

**Issue by coutadeurf** [home-assistant/home-assistant.github.io#28700]
### Feedback

Hi,
The entry event has 2 attributes that can be interesting and that are not mentioned in the doc: latitude and longitude.
Also, the only attribute that has value in the exit event is callsign: the other ones have a value of 0.
This is worth updating the doc, I think.
Thanks again for your work :)

### URL

https://www.home-assistant.io/integrations/opensky/

### Version

2023.8.4

**Comment by coutadeurf** [comment]
This was supposed to be a doc issue ...

**Comment by joostlek** [comment]
This is a doc issue :P

**Comment by joostlek** [comment]
Wait can you send an example event?

**Comment by coutadeurf** [comment]
![Screenshot_2023-08-27-12-48-21-58_c3a231c25ed346e59462e84656a70e50](https://github.com/home-assistant/home-assistant.io/assets/40169798/e53cffb3-7189-4e1e-9173-a8529cdf69fb)
This is what I get when I use templates in the entry and exit event:
service: notify.persistent_notification
data:
  message: >-
    Vol {{ trigger.event.data.callsign }} à {{ trigger.event.data.altitude }} m,
    vu {{ trigger.event.data.latitude }}:{{ trigger.event.data.longitude
        }}

**Comment by joostlek** [comment]
afaik, the exit event only shows you that a plane exited, since we didn't receive any new data for it. So since we don't have new data, we also don't know it's altitude or location, thus it's 0 and None.

Does that make sense?

**Comment by coutadeurf** [comment]
Yes, it perfectly makes sense and this is why I opened a doc issue (or tried to) as the documentation let the reader think that both events have relevant values in those attributes

**Comment by joostlek** [comment]
You can also make a proposal if you have a good idea for it :)
