### ISSUE TITLE
Data sensors "energy discharge to grid" don't provide any data

### ISSUE THREAD

**Issue by herbie62** [home-assistant/home-assistant.github.io#28716]
### Feedback

I integrated Kostal Plenticore Solar Inverter into Home Assistant. 
I am missing process data values for the data sensors "Energy discharge to grid". The sensors don't provide any data.

### URL

https://www.home-assistant.io/integrations/kostal_plenticore/

### Version

2023.8.4

**Comment by stegm** [comment]
The name of the entity might be a bit misleading. Discharge to grid mean discharging the battery to the grid. This value is normally very small and might be 0 if you have no battery.

I try to update the documentation to clarify the situation.
