### ISSUE TITLE
Enphase Envoy reports erroneous data for daily production

### ISSUE THREAD

**Issue by Nattle** [home-assistant/home-assistant.github.io#28715]
### Feedback

Twice in the past several months the integration has reported the wrong value for daily energy production. It supplied the total energy produced for the array up to that date . So for example, my array produces around 40kwh per day but on Aug 25th it reports generating 11,500 kwh for that day alone. 

<img width="1114" alt="Screenshot 2023-08-28 at 2 32 44 PM" src="https://github.com/home-assistant/home-assistant.io/assets/2287972/adb73eaa-ed51-417f-bc15-f28b3ea996dd">

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2023.8.4

**Comment by frenck** [comment]
Hi there @Nattle 👋 

It seems like you wanted to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
