### ISSUE TITLE
UK OVO Energy only.  Not Australia

### ISSUE THREAD

**Issue by kyemacdonald** [home-assistant/home-assistant.github.io#28729]
### Feedback

UK OVO Energy only.  Not Australia

### URL

https://www.home-assistant.io/integrations/ovo_energy/

### Version

2023.8.4

**Comment by simongis** [comment]
https://github.com/home-assistant/home-assistant.io/issues/24969

Would love to see it support Australian accounts.  Has been a surge in users to them since they setup over here.

**Comment by DanAE111** [comment]
That would be good i may have just fallen victim to this given the integration page neglects to mention it's UK only. Doh! Still better rates which is the main reason i was shopping around.

I'm no python guru but i believe the HA integration uses this library to query the provider so it's likely the changes that need to happen are outside of HA. https://github.com/timmo001/ovoenergy
