### ISSUE TITLE
Security issue in example in docs - "stop cover" does not check condition, can unlock door

### ISSUE THREAD

**Issue by MBarti** [home-assistant/home-assistant.github.io#28752]
### Feedback

Re: Garage door code example:

If you have a voice assistant and a burglar shouts through your window "Stop garage cover", the proposed example script will just click the switch and open your garage door, provided that you have a standard open/stop/close switch.

The example should include a condition check (if contact sensor is open) for "stop cover" action, just as it does for "close" and "open" actions.

### URL

https://www.home-assistant.io/integrations/cover.template/

### Version

2023.8.4

**Comment by SN-git-stack** [comment]
I find the same as issue, as the function stop_cover dows not validate any state codition.
Cover can be "stopped" when condition is "off".

Can you let us know if this will be considered as a feature request?
