### ISSUE TITLE
Additional button controls.

### ISSUE THREAD

**Issue by guy-BW** [home-assistant/home-assistant.github.io#28765]
### Feedback

Love the integration with HA for the powerwall it's going to be very useful.

Can you  add button and selector controls to the integration? I would like to be able to set 

- Charge from Grid
- Setting Backup reserve level
- Self-powered or Time-Based Control

These appear to already be provided for in the API.

I'm specifically interested in being able to turn Grid charging off and on so when I know the next day will be a good solar day, I can which grid charging off when the battery reaches a recharge level over night. Ie charge to 70% and then stop and the sun will do the rest.

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2023.8.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
