### ISSUE TITLE
Integration won't install

### ISSUE THREAD

**Issue by braithm** [home-assistant/home-assistant.github.io#28771]
### Feedback

When adding integration I receive the following on start up of wizard.

Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2023.8.4

### Additional information

<img width="697" alt="Screenshot 2023-09-03 at 18 31 15" src="https://github.com/home-assistant/home-assistant.io/assets/58206561/4f8c5da8-56e2-4bdb-ab66-869eed10d2c8">

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
