### ISSUE TITLE
Missing Instruction w.r.t. "You can add an assistant with the conversation agent set to “Google Assistant SDK”."

### ISSUE THREAD

**Issue by yetsea** [home-assistant/home-assistant.github.io#28789]
### Feedback

The document says "You can add an assistant with the conversation agent set to “Google Assistant SDK”."

However there's no instruction in this doc to show how to do it, and there's no link to a related documents. A Google search attempt failed to find any related info either.

Can you please update the doc? Thanks!

### URL

https://www.home-assistant.io/integrations/google_assistant_sdk/

### Version

2023.8.4

**Comment by tronikos** [comment]
See setup your assistant section [here](https://www.home-assistant.io/voice_control/voice_remote_local_assistant/)
