### ISSUE TITLE
different total energy in fronius-app and home-assistant

### ISSUE THREAD

**Issue by at-andreas** [home-assistant/home-assistant.github.io#28803]
### Feedback

Fronius Solar.Web App shows a overall total produced value of 4761,25 kWh
Home-Assistant shows 4638,05 kWh

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2023.8.4

**Comment by farmio** [comment]
Hi 👋! 

This is the issue tracker for HAs **documentation**. 
For bugs in core integrations head to https://github.com/home-assistant/core/issues
For support questions visit https://community.home-assistant.io

That said, there is no information provided on where these values come from, and we don't have any insight on how Fronius' Solar.Web processes its data or if it had an additional data source previously.
