### ISSUE TITLE
Missing hint for discovery: Only working when in same subnet

### ISSUE THREAD

**Issue by viseradius** [home-assistant/home-assistant.github.io#28810]
### Feedback

Hi,
I noticed that the discovery of the hue bridge only worked, when HA (Docker) and the hue bridge are on the same subnet. 

A small change to the readme would be good but a change in the discovery even better.

Thanks

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2023.8.4

**Comment by marcelveldt** [comment]
If you are technical enough to split up your network into different subnets, you should also know about all the downsides of that and the implication that things such as discovery will not work unless you implement some sort of mdns responder in your network (which comes with a load of issues on its own).

You would have this issue with any integration that relies on mdns for discovery so I don't really see the point of adjusting the documentation. TIP: Just make sure that HA is on the same (v)LAN as your IoT devices, you can even make it multi homed if you really insist to have this additional layer of complexity.

**Comment by viseradius** [comment]
Nevertheless I was wondering, because I wasn't even able to add the hue bridge manually. 
The integration immediately stated that there is no bridge.

**Comment by marcelveldt** [comment]
Yes, because it is meant to be used on the same subnet. This is consumer grade gear, that does not play well with enterprise network setups ;-) 

Nevertheless I believe there should be a possibility to manual enter an IP in the setup flow ?

**Comment by viseradius** [comment]
I thought so too. In my previous setup using Home Assistant OS I could enter the IP. 
Now, using Docker, it didn't work.
