### ISSUE TITLE
Airthings View Plus Support?

### ISSUE THREAD

**Issue by Kevster75** [home-assistant/home-assistant.github.io#28815]
### Feedback

Is it possible for the integration to support Airthings View Plus? I have a few of these models, which are currently unsupported.

### URL

https://www.home-assistant.io/integrations/airthings_ble/

### Version

2023.9.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
