### ISSUE TITLE
Support for ITC 306A

### ISSUE THREAD

**Issue by federicokeen** [home-assistant/home-assistant.github.io#28818]
### Feedback

Hello, any chance to add support for ITC 306A? 

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2023.9.0

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
