### ISSUE TITLE
Additional information about config needed

### ISSUE THREAD

**Issue by NoviceOtter** [home-assistant/home-assistant.github.io#28816]
### Feedback

The config dialog for this device has an ambiguous case. The Host refers to the devices IP address on your network.

Some additional information on the integration page to match the information up to the devices multiple configuration strings would be helpful.

### URL

https://www.home-assistant.io/integrations/rainforest_eagle/

### Version

2023.9.0

**Comment by noahm** [comment]
I just got my own rainforest device this week and I've been staring at the configuration page and corresponding documentation fruitlessly trying to figure out what on earth "Host" was supposed to mean. Thanks for clarifying that @NoviceOtter!

**Comment by klaasnicolaas** [comment]
It is described here: https://www.home-assistant.io/docs/glossary/#host
