### ISSUE TITLE
Yardian access Token - It's coming

### ISSUE THREAD

**Issue by iGageit** [home-assistant/home-assistant.github.io#28825]
### Feedback

With the latest updated as of September 7th 2023 The access Token is not visible in the app (6.19.0). I emailed them and they said this: 

Aeon Matrix (Aeon Matrix Support Center) Sep 7, 2023, 07:47 PDT Hi, Thanks for your inquiry! We will release an in-app update tomorrow then you can find the access token in the app.
--

So the Access token issue should be resolved with the next update. 

### URL

https://www.home-assistant.io/integrations/yardian/

### Version

2023.9.0

**Comment by h3l1o5** [comment]
A new Yardian App version is released. Please make sure your app version is v4.8.2 or higher and device's firmware version is 6.18.0 or higher. And the access token functionality should be working fine.

**Comment by h3l1o5** [comment]
@home-assistant close
