### ISSUE TITLE
Details about what feature the intregration provides

### ISSUE THREAD

**Issue by nickh66** [home-assistant/home-assistant.github.io#28836]
### Feedback

Hi, I'm curious what sensors, binary sensors, switches and/or other features/other controls this integration might provide.  For example, i'm trying to make an EVSE purchasing decision & i'm leaning towards the Telsla device but i don't know if i will have features like charge start/stop control from within home-assistant.
It would be great if someone that has this integration could clarify what features are available.  Similar to what is listed for the Wallbox integration would be super helpful.
Cheers
Nick

### URL

https://www.home-assistant.io/integrations/tesla_wall_connector/

### Version

2023.9.0

**Comment by antonio-fiol** [comment]
Still valid
