### ISSUE TITLE
KNX Number no work

### ISSUE THREAD

**Issue by marioJR1979** [home-assistant/home-assistant.github.io#28832]
### Feedback

Hello. 
I'm trying to configure a KNX value type number and it doesn't work. The rest of the KNX configurations seem to work correctly. I have tried several installations and they work the same, I think it must be a fault.
I copy what was used:
  number:
    - name: "KNX-Temperatura minima Termo ACS Verano"
      address: "7/3/20"
      type: temperature
      min: 30
      max: 50
      step: 1.0
      mode: slider

The configuration appears correctly, but then it does not transmit the information to KNX. I have verified that it does not send the KNX telegram.

Please take a look at it.
Thank you.

### URL

https://www.home-assistant.io/integrations/knx/

### Version

2023.9.0

**Comment by farmio** [comment]
Hi 👋! 

This is the issue tracker for HAs **documentation**. 
For bugs in core integrations head to https://github.com/home-assistant/core/issues
For support questions visit https://community.home-assistant.io

That said, the configuration seems fine. Please have a look at the group monitor and HAs logs and add that information to your issue.

**Comment by marioJR1979** [comment]
Okay. But I'm not quite sure where to post this, since I can't find the appropriate place where you indicate me.

I don't know where to report this bug.

**Comment by klaasnicolaas** [comment]
It is a core issue, so that is where you need to be 😉
