### ISSUE TITLE
Add sensors for additional wall connectors when using Tesla's Power Sharing Feature 

### ISSUE THREAD

**Issue by kbreudi** [home-assistant/home-assistant.github.io#28854]
### Feedback

I recently added a second Gen 3 wall connector to my garage for our second Tesla. I am using the built in "power sharing" feature that Tesla offers in order to not overload my sub panel. In order to do this, one unit must be the "leader" , which requires the single follower in my case to be directly connected to the main unit's SSID wifi network, removing it from my home wifi network. Wondering if there is a way to poll the data from any of the connected follower units, as the main "leader" still connects to my wifi and the HomeAssistant integration still shows all data from that one unit. 

### URL

https://www.home-assistant.io/integrations/tesla_wall_connector/

### Version

2023.9.1

**Comment by einarhauks** [comment]
Hi @kbreudi 

I only have a single Wall Connector so I haven't seen data from a system consisting of more than one and I'm not aware of an API endpoint where data from the second wall connector is exposed. I suggest you search forums for information and have a look at the data exposed by your main wall connector at: http://<IP>/api/1/vitals (also look at /lifetime, /version, /wifi_status). Please report back if you find an API endpoint with data from your second unit
