### ISSUE TITLE
add Ambient weather forecast to HA integration

### ISSUE THREAD

**Issue by Bromaynard** [home-assistant/home-assistant.github.io#28851]
### Feedback

just curious if there are plans to add forecast information for the forecast card?  It looks like the info is available in the json.  🤔

### URL

https://www.home-assistant.io/integrations/ambient_station/

### Version

2023.9.1

**Comment by bachya** [comment]
This is the documentation website repo and not for feature requests. I currently have no plans to add forecast capabilities to this integration because the data returned by the API is real-time data, not forecasted data.
