### ISSUE TITLE
Login with IP Adress not possible

### ISSUE THREAD

**Issue by m-art-in-hof** [home-assistant/home-assistant.github.io#28867]
### Feedback

hi
unfortunetly it is not possible to login to the powerwall integration. I choose the ip adress which is listed in my fritzbox and password tried both: last 5 letters an the whole one from the gateway: no connection possible.
Can someone help me?

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2023.9.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
