### ISSUE TITLE
lawnmower

### ISSUE THREAD

**Issue by dpawson** [home-assistant/home-assistant.github.io#28860]
### Feedback

Please tell us what make of lawnmower it works with,
what (if anything) we need to do at the lawnmower end.
How to 'connect' to the mower?

### URL

https://www.home-assistant.io/integrations/lawn_mower/

### Version

2023.9.1

**Comment by MartinHjelmare** [comment]
From the linked page:

> Please note, the lawn mower integration cannot be directly used; you cannot create your own lawn mower entities using this integration. This integration is a building block for other integrations to use, enabling them to create lawn mower entities for you.

**Comment by dpawson** [comment]
Not what I was asking.
You provide a 'vague' lawnmower task, then leave it blank?
If it is not linked to any brand of lawnmower, expecting further work,  please say so.

**Comment by MartinHjelmare** [comment]
As for any other entity category you can search for supported integrations on the integrations page:

https://www.home-assistant.io/integrations/#lawn-mower
