### ISSUE TITLE
is there a way to send a ZW_SetDefault to the UZB controller to completely reset the network and remove all nodes?

### ISSUE THREAD

**Issue by drzwave** [home-assistant/home-assistant.github.io#28872]
### Feedback

I don't see any menu item to send a ZW_SetDefault to a UZB controller.
I had to put the UZB stick into another computer and use the PC Controller to reset it since it already had an obsolete network configured.
This is always a good feature (and required for certification) to help diagnose problems.
But it should be protected behind at least 1 screen of "Are you certain you realize you are permanently deleting the entire Z-Wave network and will have to rebuild it?".

Thanks,
Eric

### URL

https://www.home-assistant.io/integrations/zwave_js/

### Version

2023.9.1

**Comment by raman325** [comment]
we have not added support for this into the integration. This is available through Z-Wave JS UI for anyone who needs to do this but I think the risk of someone accidentally wiping their network as a result of making this action available in the integration is worse than the benefit of having it for use cases like this

**Comment by raman325** [comment]
we have not added support for this into the integration. This is available through Z-Wave JS UI for anyone who needs to do this but I think the risk of someone accidentally wiping their network as a result of this action in the integration is worse than the benefit of having it for use cases like this
