### ISSUE TITLE
Schedule helper card

### ISSUE THREAD

**Issue by patrickgmail** [home-assistant/home-assistant.github.io#28877]
### Feedback

Hi. Should be nice to get a Lovelace card to modiy schedule-helper events.

### URL

https://www.home-assistant.io/integrations/schedule/

### Version

2023.9.1

**Comment by MartinHjelmare** [comment]
Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum. Thanks!
