### ISSUE TITLE
Template Weather "forecast_daily_template" Missing Detailed Example

### ISSUE THREAD

**Issue by roderik-maker** [home-assistant/home-assistant.github.io#28884]
### Feedback

[This page](https://www.home-assistant.io/integrations/weather.template/) would benefit from an example of the required data structure for the "forecast_xxx_template" parameters especially since the "forecast" attribute used in the current example is being deprecated if I am not mistaken.

Background: I spent hours trying a range of templates to figure out the format that the "forecast_daily_template" data should have. I believe more people would benefit from a clear example of the required data structure for the "forecast_xxxx_template" parameters of the template weather entity.

Something like this (or even more basic) would have really helped me :

```
weather:
  - platform: template
    name: "My Custom Weather Entity"
    condition_template: "{{ states('weather.some_weather_provider') }}"
    temperature_template: "{{ states('sensor.outside_temperature') | float }}"
    temperature_unit: "°C"
    humidity_template: "{{ states('sensor.outside_humidity') | float }}"
    forecast_hourly_template: |
      [
      {% for datetime_list in state_attr('entity', 'datetime_attribute') %} 
        {% set temperature_list = state_attr('entity', 'temperature_attribute') [loop.index0] %}
        {% set humidity_list = state_attr('entity', 'humidity_attribute') [loop.index0] %}
        {
        "datetime": "{{ datetime_list | as_datetime }}", 
        "temperature": {{ temperature_list | float }} ,
        "humidity": {{ humidity_list | float }}
        } 
        {% if not loop.last %}
          , 
        {% endif %}
      {% endfor %}
      ]
```

Hopefully, an extra (or updated) example can be added to this page.

### URL

https://www.home-assistant.io/integrations/weather.template/

### Version

2023.9.1

**Comment by derMicro** [comment]
Hello, I am also stuck on this problem and have tried with the help of the forum some approaches how to really use the practically undocumented parameter forcecast_xxx_template. So far it has not succeeded because the documentation seems to be simply incomplete.
https://community.home-assistant.io/t/new-forecast-service-how-i-can-create-a-forecast-entity/613507/7

forecast_daily_template: "{{ state_attr('weather.my_region', 'forecast') }}" does not work at all, because we do not know how the structure or syntax of the data must look like.

in any case not like this:
![image](https://github.com/home-assistant/home-assistant.io/assets/125592865/5a6a1e4f-8078-4c44-8c87-4392259a1708)
(RestFul Sensor, because i request forecastdata via REST API)

**Comment by roderik-maker** [comment]
(@derMicro Hope this helps you)

The code at the bottom of this post is the custom weather entity I ended up making (and is working) for myself. It uses a restful sensor, a Dutch weather platform "buienradar", and sensor values from an ESP with a temperature and humidity sensor.

**But first some tips and an attempt at an explanation**
When you are setting up any of the forcecast_xxx_template parameters for yourself be very careful with adding too many parameters to the forecast at once. The processing of the data the template provides doesn't seem very robust, any formatting mistakes will make the forecast "unknown". I would start with just a list of DateTime objects `| as-datetime` and a list of forecast temperatures for each date time as float `| float`.

**Here is an example of the basic setup**
```
forecast_hourly_template: |
  [
  {% for datetime_list in state_attr('sensor.openmeteoapi_weather', 'time') %}  # Loop through every point in time for which you want to provide forecast data and set the value of "datetime_list" to that datetime

    {% if loop.index > (now().hour|int)+1 %}  # Ensure that you only add future data to your forecast, without this your forecast will contain data from the morning, at least that was the case with my input data

      {% set temperature_list = state_attr('sensor.openmeteoapi_weather', 'temperature_2m')[loop.index0] %}.  # set the value of "temperature_list" to be the forecasted temperature at the datetime being evaluated
  
      # Put the datetime and temperature values in the correct format
      {"datetime": "{{datetime_list | as_datetime}}", "temperature": {{temperature_list | float}}}{% if not loop.last %},{% endif %}

    {% endif %}
  {% endfor %}
  ]
```
_(@derMicro I'm guessing the comments I added are probably not necessary for you if you are using a restful sensor to pull your data, but maybe someone else will benefit from them)_

**The output should have this structure**
`[{"datetime": "2023-09-15 00:00:00", "temperature": 19.8}, {"datetime": "2023-09-15 01:00:00", "temperature": 19.8}, {"datetime": "2023-09-15 02:00:00", "temperature": 19.8},...]`

If any formatting is wrong in any part, the forecast becomes "unknown" so start with getting the bare basics (datetime and temp) to be read correctly by Home Assistant (HA). Then I would slowly start adding parameters (don't be arrogant like me and try to add all forecast parameters in one go, this was impossible to debug and I wasted hours). Add one at a time and make sure the forecast loads correctly in HA before adding more parameters to the forecast. Again if there is any issue the whole forecast becomes "unknown" and it's very hard to troubleshoot when you've added too many things at once.

**Required data types of the different forecast parameters**
Have a look [here](https://www.home-assistant.io/integrations/weather/#service-weatherget_forecast). This gives info on all the possible parameters you can add to a forecast and an example of their data structure. Some are harder than others, I myself never managed to figure out the format that the "apparent_temperature" parameter required.

**My configuration.yaml code for my custom weather entity**
The code is probably not the easiest to follow (as I did not make it with the intention to share it). If anyone wants, I can add further comments explaining what I'm doing. 
```
rest:  # If anyone is directly copy pasting this, change "latitude=00.0000&longitude=0.0000" to your own coordinates.
  - resource: https://api.open-meteo.com/v1/forecast?latitude=00.0000&longitude=0.0000&hourly=temperature_2m,relativehumidity_2m,apparent_temperature,rain,weathercode,visibility,windspeed_10m,precipitation_probability,precipitation,winddirection_10m&daily=sunrise,sunset&timezone=Europe%2FBerlin
    method: GET
    scan_interval: 900 # Update data every 15min.
    sensor:
      - name: "OpenMeteoAPI Weather"
        json_attributes_path: "hourly"
        json_attributes:
          - "temperature_2m"
          - "time"
          - "relativehumidity_2m"
          - "apparent_temperature"
          - "rain"
          - "weathercode"
          - "visibility"
          - "windspeed_10m"
          - "precipitation_probability"
          - "precipitation"
          - "winddirection_10m"
        value_template: "{{ value_json['hourly']['temperature_2m'][0] }}"
      - name: "OpenMeteoAPI Weather Daily"
        json_attributes_path: "daily"
        json_attributes:
          - "sunrise"
          - "sunset"
        value_template: "{{ value_json['daily']['sunrise'][0] }}"

weather:
  - platform: template
    name: "Combined Weather"
    condition_template: "{{ states('weather.buienradar') }}"
    temperature_template: "{{ states('sensor.outside_climate_outside_temperature') | float }}" # This is a simple float value obtained from an esp sensor, but any source that provides a float variable should work
    temperature_unit: "°C"
    humidity_template: "{{ states('sensor.outside_climate_outside_humidity') | float }}"  # This is a simple float value obtained from an esp sensor, but any source that provides float variable should work
    visibility_template: "{{state_attr('weather.buienradar','visibility')}}"
    forecast_hourly_template: |
      {% set weather_code_to_description_day = {
          0: "sunny",
          1: "partlycloudy",
          2: "partlycloudy",
          3: "cloudy",
          45: "fog",
          48: "fog",
          51: "rainy",
          53: "rainy",
          55: "pouring",
          56: "rainy",
          57: "pouring",
          61: "rainy",
          63: "rainy",
          65: "pouring",
          66: "rainy",
          67: "pouring",
          71: "snowy",
          73: "snowy",
          75: "snowy",
          77: "snowy",
          80: "rainy",
          81: "rainy",
          82: "pouring",
          85: "snowy",
          86: "snowy",
          95: "lightning",
          96: "hail",
          99: "hail"
      } %}
      
      {% set weather_code_to_description_night = {
          0: "clear-night",
          1: "partlycloudy",
          2: "partlycloudy",
          3: "cloudy",
          45: "fog",
          48: "fog",
          51: "rainy",
          53: "rainy",
          55: "pouring",
          56: "rainy",
          57: "pouring",
          61: "rainy",
          63: "rainy",
          65: "pouring",
          66: "rainy",
          67: "pouring",
          71: "snowy",
          73: "snowy",
          75: "snowy",
          77: "snowy",
          80: "rainy",
          81: "rainy",
          82: "pouring",
          85: "snowy",
          86: "snowy",
          95: "lightning",
          96: "hail",
          99: "hail"
      } %}
      
      {% set sunset = state_attr('sensor.openmeteoapi_weather_daily', 'sunset') %}
      {% set sunrise = state_attr('sensor.openmeteoapi_weather_daily', 'sunrise') %}
      
      [
      {% for datetime_list in state_attr('sensor.openmeteoapi_weather', 'time') %}
        {% if loop.index > (now().hour|int)+1 %}
          {% set temperature_list = state_attr('sensor.openmeteoapi_weather', 'temperature_2m')[loop.index0] %}
          {% set humidity_list = state_attr('sensor.openmeteoapi_weather', 'relativehumidity_2m')[loop.index0] %}
          {% set precipitation_list = state_attr('sensor.openmeteoapi_weather', 'precipitation')[loop.index0] %}
          {% set precipitation_probability_list = state_attr('sensor.openmeteoapi_weather', 'precipitation_probability')[loop.index0] %}
          {% set wind_bearing_list = state_attr('sensor.openmeteoapi_weather', 'winddirection_10m')[loop.index0] %}
          {% set wind_speed_list = state_attr('sensor.openmeteoapi_weather', 'windspeed_10m')[loop.index0] %}
          {% set daytime = ("day" if ((datetime_list|as_datetime) > (sunrise[((loop.index-1)//24)]|as_datetime) and (datetime_list|as_datetime) < (sunset[((loop.index-1)//24)]|as_datetime)) else "night") %}
          {% set condition_list = state_attr('sensor.openmeteoapi_weather', 'weathercode')[loop.index0] %}
          
           {"datetime": "{{datetime_list | as_datetime}}",
           "temperature": {{temperature_list | float}},
           "humidity": {{humidity_list | float}},
           "precipitation": {{precipitation_list | float}},
           "precipitation_probability": {{precipitation_probability_list | int}},
           "wind_bearing": {{wind_bearing_list | int}},
           "wind_speed": {{wind_speed_list | float}},
           "condition": "{{weather_code_to_description_day[condition_list|int] if daytime=="day" else weather_code_to_description_night[condition_list|int]}}"}{% if not loop.last %},{% endif %}
        {% endif %}
      {% endfor %}
      ]
  ```
*The "weather_code_to_description_day" and "weather_code_to_description_night" tables were mapped by chat GPT so are maybe not the best transformation from weather condition number to HA weather state string. (The list was too long for me to bother doing it manually haha.)

Hope something in this post is helpful to someone. If anyone (ever reads this and) has any questions I'll do my best to help :)

**Comment by roderik-maker** [comment]
Sorry! I didn't mean to close the issue. I clicked "Close with comment" to turn it off as I DIDN'T want my comment to close the issue, but apparently, that did exactly what I didn't want it to do. I'm still not very familiar with GitHub controls, won't happen again!

**Comment by derMicro** [comment]
I was able to solve it, the day before yesterday 2023.9.2 appeared and all of a sudden I had the Daily checkbox in the Weather entity, when I checked that again the Forecast was there.
![image](https://github.com/home-assistant/home-assistant.io/assets/125592865/8365bf1b-5674-42f4-9e81-050d5119f17f)
