### ISSUE TITLE
Access to other settings?

### ISSUE THREAD

**Issue by Mehrtens** [home-assistant/home-assistant.github.io#28887]
### Feedback

Hi, is it possible to access things like the auto-lock delay? I can imagine wanting to automate from HA to leave auto lock off until bedtime so that if we want to go in and out of our back patio during the day, we could setup automation so that if we are home, turn off autolock. 
Or are we limited by Schlage API, I have not seen this yet.

### URL

https://www.home-assistant.io/integrations/schlage/

### Version

2023.9.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation issues or handling feature requests.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by dknowles2** [comment]
This is possible through the Schlage api. Please open a feature request in the main HA repo and we can track progress there.

**Comment by frenck** [comment]
Unlike above listed; Please do not open feature requests on the main HA repo. We use issue trackers in our repositories to track issues, not features. Feature requests belong in our forums. 

Such issues will be closed.

../Frenck
