### ISSUE TITLE
Home Assistant home page has 2023.9.1 but 2023.9.2 is out

### ISSUE THREAD

**Issue by pbulteel** [home-assistant/home-assistant.github.io#28897]
### Feedback

The home page for Home Assistant shows the latest version 2023.9.1 but once you go into the 2023.9 release page you see that version 2023.9.2 is out.

### URL

https://www.home-assistant.io/

### Version

2023.9.2

**Comment by frenck** [comment]
Thanks for spotting, I opened up https://github.com/home-assistant/home-assistant.io/pull/28898 to fix it 👍 

../Frenck
