### ISSUE TITLE
How to Change Docker Network from Bridge Mode to Host Mode？

### ISSUE THREAD

**Issue by Wolonglong** [home-assistant/home-assistant.github.io#28903]
### Feedback

May I ask if the Home Assistant Docker network can be set to host mode? The default network is bridging mode, “hassio_supervisor” container can be implemented through “Docker run -- network=host”, but “hassio_ Cli”, “hassio_ Audio” “hassio_supervisor” container is automatically pulled and started. By default, it is in bridging mode and enters hassio_ After the supervisor container modified the cli. py script to host mode, the restart script was restored and cannot be modified

### URL

https://www.home-assistant.io/getting-started/join-the-community/

### Version

2023.9.2

### Additional information

May I ask if the Home Assistant Docker network can be set to host mode? The default network is bridging mode, “hassio_supervisor” container can be implemented through “Docker run -- network=host”, but “hassio_ Cli”, “hassio_ Audio” “hassio_supervisor” container is automatically pulled and started. By default, it is in bridging mode and enters hassio_ After the supervisor container modified the cli. py script to host mode, the restart script was restored and cannot be modified

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
