### ISSUE TITLE
Use case for Rhasspy integration documentation - existing external Rhasspy

### ISSUE THREAD

**Issue by Nebby** [home-assistant/home-assistant.github.io#28919]
### Feedback

I have an existing standalone Rhasspy server, and the Rhasspy integration doesn't seem to detect it. I'm not sure what to do about this or if my use case is even supported by the integration. It would be helpful to address this in the documentation if possible.

EDIT: After reading a similar issue, it seems the integration should be configured on the Rhasspy side? If so it would be helpful to note that on the page. A link to the Rhasspy docs (eg. https://rhasspy.readthedocs.io/en/latest/intent-handling/#home-assistant) would be even better, if appropriate.

### URL

https://www.home-assistant.io/integrations/rhasspy/

### Version

2023.9.2

**Comment by synesthesiam** [comment]
The Rhasspy integration is currently a placeholder. It will be extended in the future to connect to a Rhasspy server.
