### ISSUE TITLE
Option to enable weeknumber

### ISSUE THREAD

**Issue by Kevin-Kusters** [home-assistant/home-assistant.github.io#28929]
### Feedback

I would like to have the option to see the week number.

### URL

https://www.home-assistant.io/dashboards/calendar/

### Version

2023.9.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
