### ISSUE TITLE
Where to find the configurtion.yaml....

### ISSUE THREAD

**Issue by AntonKremer** [home-assistant/home-assistant.github.io#28924]
### Feedback

Would be great if it would be mentioned were the configuration.yaml is located / stored if there is e.g. a build in tool to edit the file , e.g. via the web front end...

### URL

https://www.home-assistant.io/docs/configuration/yaml/

### Version

2023.9.2

**Comment by tjorim** [comment]
Check the documentation here: https://www.home-assistant.io/docs/configuration/#editing-configurationyaml.
It gives options how to edit the config, where to find the path and some common locations.
