### ISSUE TITLE
Diagnostics and logs for integrations having problems.

### ISSUE THREAD

**Issue by rdperkins** [home-assistant/home-assistant.github.io#28920]
### Feedback

May I suggest that after enabling debugging for an integration, you automatically create a separate log file for the integration, perhaps in a logs subdirectory, with the filename including the integration name and date the debugging log was started. Also, make it easy to download the log from the integration entries elipsis menu. I have no idea where to find the debug log(s). The file should also include the diagnostics, if any were created. Seems like that would make it easier for the engineers to have everything together to review. Thanks for considering.

### URL

https://www.home-assistant.io/docs/configuration/troubleshooting/

### Version

2023.9.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
