### ISSUE TITLE
No method to remove the integration if no longer wanted.

### ISSUE THREAD

**Issue by Phrede** [home-assistant/home-assistant.github.io#28939]
### Feedback

No method to remove the integration if no longer wanted.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2023.9.2

**Comment by starkillerOG** [comment]
@Phrede there is: in HomeAssistant -> settings -> Devices and services -> Click the reolink integration -> Next to configure, click the three vertical dots -> Click the red "remove".

After removing, restart HomeAsstant and it will be fully gone from your setup.

_Edit: removed sponsoring_

**Comment by klaasnicolaas** [comment]
@starkillerOG I have removed your sponsor talk, we don't allow this and I think you know this very well yourself 😉

**Comment by Phrede** [comment]
@stakiller OG that does not work.
