### ISSUE TITLE
Renson healthbox 3.0 OS version 1.5.0

### ISSUE THREAD

**Issue by mberetvas** [home-assistant/home-assistant.github.io#28932]
### Feedback

Hello,

When I try to ad an renson integration it ask for the host* but when i give it the ip adress it can't find my device.
ip is on local network (same network of the home assistant)

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend-versie: 20230911.0 - latest

### URL

https://www.home-assistant.io/integrations/renson/

### Version

2023.9.2

**Comment by jimmyd-be** [comment]
The Renson integration only supports the Endura Delta devices. Healthbox is currently not supported. You can try to use https://github.com/rmassch/healthbox-hacs for adding Healthbox support to Hass.

**Comment by jimmyd-be** [comment]
@home-assistant close
