### ISSUE TITLE
Xiaomi Roborock S12 (model id B106GL) 

### ISSUE THREAD

**Issue by casamanco** [home-assistant/home-assistant.github.io#28958]
### Feedback

The Xiaomi Roborock S12 is not currently compatible. It will be? How should I integrate it into home assistant? Thanks

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2023.9.2

**Comment by JigmetAvinash** [comment]
### Issue #28958 Xiaomi Robrock integration

Xiaomi Robrock is **not compatible** with Home Assistant; As per the website the following are listed 
[Xiaomi Gateway](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-gateway)
[Xiaomi device tracker (Xiaomi Mi WiFi Repeater 2)](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-device-tracker-xiaomi-mi-wifi-repeater-2)
[Xiaomi Air Purifier, Air Humidifier and Standing Fan](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-air-purifier-air-humidifier-and-standing-fan)
[Xiaomi Air Quality Monitor](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-air-quality-monitor)
[Xiaomi IR Remote](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-ir-remote)
[Xiaomi Mi Robot Vacuum](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-mi-robot-vacuum)
[Xiaomi Philips Light](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-philips-light)
[Xiaomi Smart WiFi Socket and Smart Power Strip](https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-smart-wifi-socket-and-smart-power-strip)

**However**, if you want to integrate it, do it with IFTT or other 3rd party integrations; if you still can't find any resolution, mail me at chopcodes@gmail.com and I will guide you about it a little

**Comment by nineteen0815** [comment]
The Xiaomi Roborock S12 is not currently compatible. It will be?

**Comment by JigmetAvinash** [comment]
@nineteen0815 Its deffinietly not supported with Home Assistant as the Xiaomi Miio integration does not support it; however, I know a 3rd party way which can make it happen. If you need more help; reply to this comment with tagging me

**Comment by phil-schneider** [comment]
@ChopCodes I would like to know. This Model is currently in sale.

**Comment by JigmetAvinash** [comment]
Sure, all about my research I found some github repo. I don't own any
xiaomi product so couldn't test it but request you to give feedback on it
(if it works)

You can check the home assistant forum coms here
https://community.home-assistant.io/t/support-for-xiaomi-s12-roborock-in-xiaomi-miio-integration/616567

And the github repo here
https://github.com/al-one/hass-xiaomi-miot

**Comment by JigmetAvinash** [comment]
@phil-schneider look at the comment above
