### ISSUE TITLE
For installation to hard disk of generic x86 suggest manual decompression

### ISSUE THREAD

**Issue by pmjordan** [home-assistant/home-assistant.github.io#28961]
### Feedback

I followed the instructions at https://www.home-assistant.io/installation/generic-x86-64 to use a live OS to write the HAOS file to the hard disk of my machine so that it can boot from there. I used Balena Etcher for this task as instructed.
The Etcher operation failed with a message 'something has gone wrong'.
I was able to overcome this by using the xz command on my downloaded image file to manually decompress it thus
`xz -dv ./haos_generic-x86-64-10.5.img.xz`
I then made the resultant decompressed file the source in Etcher and then image was then correctly written to the hard disk and I could subsequently boot into HA from there.

I suggest that the documentation suggests decompressing using xz if Etcher complains.

BTW, in a separate experiment I did not have to manually decompress when using Etcher to write HAOS to a boootable USB.

### URL

https://www.home-assistant.io/installation/generic-x86-64

### Version

2023.9.2

**Comment by c0ffeeca7** [comment]
Thank you for reaching out, @pmjordan.
Added a procedure describing how to do this using Ubuntu's Disk utility, so that Balena Etcher does not have to be used at all.
