### ISSUE TITLE
no tank level

### ISSUE THREAD

**Issue by aero77** [home-assistant/home-assistant.github.io#28960]
### Feedback

It won't read my tank level at all. None of the entities are giving me any kind of data

### URL

https://www.home-assistant.io/integrations/mopeka/

### Version

2023.9.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
