### ISSUE TITLE
airthing integration

### ISSUE THREAD

**Issue by fpow1** [home-assistant/home-assistant.github.io#28962]
### Feedback

Airthing integration have to be deleted and reinstalled after the home assistant is restarted. this create frustration. Its working untill next restart again. losing connection each restart and needed to be deleted and reintalled.

### URL

https://www.home-assistant.io/integrations/airthings_ble/

### Version

2023.9.2

**Comment by frenck** [comment]
Hi there @fpow1 👋 

It seems like you want to report an issue with a Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix this.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
