### ISSUE TITLE
Pushbullet notification is not working on HA 0.47.1

### ISSUE THREAD

**Issue by ctripodi** [home-assistant/home-assistant.github.io#2897]
Hi, since the version 0.47 the Pushbullet notification is not working on my HA. Was working before upgrade to 0.47. I could not see any error in the standard Logbook. I will appreciate some help from the team.
Thanks.

**Comment by fabaff** [comment]
This is the bug/issue tracker for Home Assistant documentation. Please use the [forum](https://community.home-assistant.io/) for questions about installation, setup, and configuration.
