### ISSUE TITLE
New skybell platform

### ISSUE THREAD

**Issue by Dinges28** [home-assistant/home-assistant.github.io#28987]
### Feedback

There is a new sky bell platform on the way; Gen5 (now in Beta). 
will the integration also support this? Or will there be an adjustment needed?

If so, I will not update to Beta

### URL

https://www.home-assistant.io/integrations/skybell/

### Additional information

https://support.skybell.com/hc/en-us/sections/7602561165325-SkyBell-Gen5-BETA

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
