### ISSUE TITLE
Then what?

### ISSUE THREAD

**Issue by nirvine** [home-assistant/home-assistant.github.io#28984]
### Feedback

I have added the NSW fuel check with my preferred station to the configuration.yaml file. But I cannot work out how to add it to a card on my dashboard. An explanation here would be great.

### URL

https://www.home-assistant.io/integrations/nsw_fuel_station/

### Version

2023.9.2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by nirvine** [comment]
It was feedback, not a request for support.

Thanks anyway,
Narelle

**Comment by frenck** [comment]
Right, however, that feedback doesn't match this page. The integrations pages providing information on how to set up the integration. Your question/suggestion was about using entities on dashboards; which is not related to this page and not specific to this integration.

../Frenck
