### ISSUE TITLE
Unable to setup iAqualink integration into Home Assistant

### ISSUE THREAD

**Issue by HunterBFontenot** [home-assistant/home-assistant.github.io#28996]
### Feedback

I'm unable to get the iAqualink integration to connect to my system. I've tried multiple iterations of updates, re-installs, and password changes. I'm sure I'm missing something simple, but I would appreciate any help I can get. 

Jandy IQPUMP01

> Logger: homeassistant.components.iaqualink
> Source: components/iaqualink/__init__.py:98 
> Integration: Jandy iAqualink ([documentation](https://www.home-assistant.io/integrations/iaqualink), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+iaqualink%22)) 
> First occurred: 9:09:51 AM (2 occurrences) 
> Last logged: 9:17:08 AM
> 
> No systems detected or supported

### URL

https://www.home-assistant.io/integrations/iaqualink/

### Version

2023.9.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
