### ISSUE TITLE
Missing Attributes from the carrier infinity integration (thru Homebridge)

### ISSUE THREAD

**Issue by FSFirenze** [home-assistant/home-assistant.github.io#29005]
### Feedback

Good morning, 

i am importing the Carrier Infinity Thermostat parameters thru an integration available on HomeBridge, which is then pushed to HomeAutomation.
In homebridge I have the following attributes available which I can't find on the climate entity in home assistant.
Can you help me figuring out how to access them?

Current Heating Cooling State
Model
Current Heating Cooling State
Current Fan State 

Thank you

### URL

https://www.home-assistant.io/integrations/climate/

### Version

2023.9.2

**Comment by MartinHjelmare** [comment]
If you need help please use our help channels:
https://home-assistant.io/help/#communication-channels
