### ISSUE TITLE
Slide integration stopped working with HA 2023.9.3

### ISSUE THREAD

**Issue by DeHeraut** [home-assistant/home-assistant.github.io#29027]
### Feedback

After installing HA 2023.9.3 the cover entity of my Slide stopped functioning. Release notes state nothing concerning the Slide API as far as I could see.

### URL

https://www.home-assistant.io/integrations/slide/

### Version

2023.9.3

### Additional information

Logger: homeassistant.components.slide
Source: components/slide/__init__.py:62
Integration: Slide (documentation, issues)
First occurred: September 25, 2023 at 21:21:38 (1452 occurrences)
Last logged: 10:46:42

Slide API does not work or returned an error

**Comment by frenck** [comment]
Hi there @Woutoud 👋 

It seems like you want to report an issue with a Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with an integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
