### ISSUE TITLE
read active_climate_profile

### ISSUE THREAD

**Issue by Schneidoa** [home-assistant/home-assistant.github.io#29022]
### Feedback

How can i read/get the current active_climate_profile? which i can set with the service homematicip_cloud.set_active_climate_profile. 

I want to create an automation with a trigger on change of active_climate_profile

### URL

https://www.home-assistant.io/integrations/homematicip_cloud/

### Version

2023.9.3

**Comment by frenck** [comment]
Currently, there is no such method available. 

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
