### ISSUE TITLE
unintuitive error message "Unexpected exception" could be more descriptive (aiovodafone.exceptions.ModelNotSupported)

### ISSUE THREAD

**Issue by zsawyer** [home-assistant/home-assistant.github.io#29029]
### Feedback

The integration's setup dialog gives "Unexpected exception" as the error message when it could have said that the device is not supported. One has to dig into the logs to get this information. 

![image](https://github.com/home-assistant/home-assistant.io/assets/897208/4f88a458-f2d0-4ad9-853e-221bf4fe0951)

Another minor issue is that the form resets and previously entered Host, Username and Password are reset. 

### URL

https://www.home-assistant.io/integrations/vodafone_station/

### Version

2023.9.3

### Additional information

Appearently the German Vodafone Station is not supported: 

![docsis3 1](https://github.com/home-assistant/home-assistant.io/assets/897208/5dbab209-5c05-4eee-8b97-846699205eca)

Firmware-Version:          01.04.046.25.EURO.PC20
Produkt name:                 Vodafone Docsis 3.1

```
Logger: homeassistant.components.vodafone_station
Source: components/vodafone_station/config_flow.py:41
Integration: Vodafone Station ([documentation](https://www.home-assistant.io/integrations/vodafone_station), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+vodafone_station%22))
First occurred: 14:05:12 (1 occurrences)
Last logged: 14:05:12
Unexpected exception

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/vodafone_station/config_flow.py", line 70, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/vodafone_station/config_flow.py", line 41, in validate_input
    await api.login()
  File "/usr/local/lib/python3.11/site-packages/aiovodafone/api.py", line 299, in login
    html_page = await self._find_login_url()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiovodafone/api.py", line 82, in _find_login_url
    raise ModelNotSupported
aiovodafone.exceptions.ModelNotSupported
```

**Comment by chemelli74** [comment]
HI @zsawyer, thx for reporting.
Will fix the message.

At the same time, I want to inform you that we are working on adding [Technicolor firmware support](https://github.com/chemelli74/aiovodafone/pull/34) to `aiovodafone` library and then to HomeAssistant.

Simone

**Comment by chemelli74** [comment]
Closed via https://github.com/home-assistant/core/pull/100937
