### ISSUE TITLE
Is the HUE TAP Switch compatible with ZHA

### ISSUE THREAD

**Issue by 0neV1s10n** [home-assistant/home-assistant.github.io#29030]
### Feedback

Hello,

Do you have any info about ZHA compatibility with HUE Tap Switch ?

According to this page, the switch is confirmed working only with DECONZ and Z2MQTT:
https://zigbee.blakadder.com/Philips_9290011152X.html

On my dockerized installation on raspberry pi4, looking for new devices doesn't succeed in finding the Philips Hue Tap Switch (SN: TAP01130).

Thanks !

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2023.9.3

### Additional information

Home Assistant 2023.7.3
User interface : 20230705.1 - latest

**Comment by marcelveldt** [comment]
Hi, you've created an issue on our documentation repository. May I kindly remind you that this issue tracker is not for support and/or feature requests but just to report issues with our documentation pages ?

**Comment by 0neV1s10n** [comment]
Thanks for the fast answer.

Actually, I'm not sure this is an issue, or just something that should be documented ("kinetic switches not supported by ZHA").
I went through few issues like this one (https://github.com/zigpy/zha-device-handlers/issues/477) and the status is a bit unclear to me.

**Comment by puddly** [comment]
Zigbee Green Power devices like the Hue tap switch aren't currently supported by ZHA. It's on the roadmap, though!
