### ISSUE TITLE
Leading flume link is unhelpful

### ISSUE THREAD

**Issue by reedy** [home-assistant/home-assistant.github.io#29040]
### Feedback

The leading link to https://portal.flumewater.com/ would be better pointing to something like https://flumewater.com/ as the "product" page, rather than a login screen that might not help someone looking for more information on the devices (for example, if they'd browsed through from https://www.home-assistant.io/docs/energy/water/).

This would be similar to https://www.home-assistant.io/integrations/flo and https://www.home-assistant.io/integrations/homewizard

I don't have a Flume device, so can't check, but it seems like all the `https://portal.flumewater.com/` urls redirect to `https://api.flumewater.com/`; I'm not sure if we "care" about avoiding redirects, but may be worth updating too

### URL

https://www.home-assistant.io/integrations/flume/

### Version

2023.9.3

**Comment by jeeftor** [comment]
Here is the link in question (in my case).

![image](https://github.com/home-assistant/home-assistant.io/assets/6491743/7cf30569-be8a-417e-9d9b-0c3124075b5a)

I'm open to changes ...

**Comment by jeeftor** [comment]
If you want to make a PR I think you are correct the docs should point to Flume purchase page not individual log in page.

**Comment by reedy** [comment]
Thanks!

FWIW, without a login, I literally just got to see, hence this feedback :)

![Screenshot 2023-09-29 at 16 13 12](https://github.com/home-assistant/home-assistant.io/assets/67615/de282779-4c9b-43d0-aba9-23b2464e3c67)
