### ISSUE TITLE
Values in Energy Dashboard are one power of ten too large

### ISSUE THREAD

**Issue by wobeco** [home-assistant/home-assistant.github.io#29057]
### Feedback

The values in the energy dashboard are one power of ten higher than the real values from the inverter / grid meter. 

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2023.9.3

### Additional information

![dummy](https://github.com/home-assistant/home-assistant.io/assets/83753522/3de920c4-7c17-4aeb-9822-ed1e77898629)

**Comment by frenck** [comment]
Hi there @wobeco 👋 

It seems like you want to report a bug with a specific Home Assistant integration. However, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
