### ISSUE TITLE
Plus de RGB CCT

### ISSUE THREAD

**Issue by romufk** [home-assistant/home-assistant.github.io#29055]
### Feedback

Depuis la dernière version de home hassistant, les RGB CCT ne sont plus pris en charge alors que c'est le futur des led. Je ne comprend pas la prolitique de Home Assistant sur les LED.

Cet appareil WLED utilise des canaux CCT, qui ne sont pas pris en charge par cette intégration

### URL

https://www.home-assistant.io/integrations/wled/

### Version

2023.9.3

**Comment by frenck** [comment]
Sorry, we don't speak different languages and are thus not able to handle non-English GitHub issues.

../Frenck
