### ISSUE TITLE
Quotes required or not?

### ISSUE THREAD

**Issue by landolfi-us** [home-assistant/home-assistant.github.io#29054]
### Feedback

Examples show quotes around server name and others, but I have had it working without quotes. Are they required?

### URL

https://www.home-assistant.io/integrations/smtp/

### Version

2023.9.3

**Comment by frenck** [comment]
Quotes are not required in YAML to denote a string; however, it is a best practice to prevent a string from being interpreted as, for example, a boolean or integer.

../Frenck
