### ISSUE TITLE
"At Home" wrong as preset value in the documentation for the Vallox integration

### ISSUE THREAD

**Issue by KlausHans** [home-assistant/home-assistant.github.io#29053]
### Feedback

If i set "At Home" as suggested in the documentation via the service fan.set_preset_mode i get an unknown error. The correct value is "Home" (i found out via try n error).

### URL

https://www.home-assistant.io/integrations/vallox/

### Version

2023.9.3

**Comment by slovdahl** [comment]
Thanks @KlausHans! Fixing it in #29080.
