### ISSUE TITLE
Set Cover Up and Down (open and close) Limits

### ISSUE THREAD

**Issue by neminat** [home-assistant/home-assistant.github.io#29062]
### Feedback

I have Ikea blinds that are longer than my window is tall (they arent cut / made to size).  I would like to add these to the dashboard and leverage the up and down arrows in the UI, but down would not be 0 as that is too long.  I would want it to be 25.  

We should have a way to set what open and close positions are set to so that UI will use those vs 0 and 100.  

### URL

https://www.home-assistant.io/integrations/cover/

### Version

2023.9.3

**Comment by MartinHjelmare** [comment]
My Ikea blinds can be calibrated to remember where the lowest position should be. Is that not the case for your blinds?

**Comment by neminat** [comment]
Interesting!  I purchased them and immediately synced them with HA and never touched any of the Ikea settings, remote etc.

**Comment by MartinHjelmare** [comment]
My blinds can be calibrated directly on the blind using the two up/down buttons located next to the battery hatch. I double click the down button to set the bottom position. It's described in the manual from Ikea.
