### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by matped1810** [home-assistant/home-assistant.github.io#29068]
### Feedback

Hi,
I entered the Serial Number and the credentials to access but I get an unknown error. Could you please provide me support?

Thanks

### URL

https://www.home-assistant.io/integrations/wallbox/

### Version

2023.9.3

**Comment by hesselonline** [comment]
Hi, there is an active group for this integration on the home assistant forum. They might be able to help you out. In general I always advise checking credentials and possibly trying on a fresh install. Some people have reported that they needed to restart the wallbox after a recent update, haven't had that issue myself.

**Comment by matped1810** [comment]
Hi,
Thanks for the answer. I tried to remove and add the wallbox back into my account, restart it but still nothing. I have this log. Would you be so kind to support me? Thanks
[home-assistant_2023-09-29T16-09-35.161Z.log](https://github.com/home-assistant/home-assistant.io/files/12768716/home-assistant_2023-09-29T16-09-35.161Z.log)

**Comment by hesselonline** [comment]
You seem to have a lot of ssl issues in general, one of these prevents the wallbox integration from working. Something is wrong with your Home Assistant system in general. The error mentions that the certificate is not yet valid; is the date and time of your system correct? Incorrect date and time can cause these issues. When stuck, please try a fresh Home Assistant install.

**Comment by matped1810** [comment]
> You seem to have a lot of ssl issues in general, one of these prevents the wallbox integration from working. Something is wrong with your Home Assistant system in general. The error mentions that the certificate is not yet valid; is the date and time of your system correct? Incorrect date and time can cause these issues. When stuck, please try a fresh Home Assistant install.

I run HA on a HAOSS VM. You suggest to remove and re-install the VM? Thanks for the answer

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
