### ISSUE TITLE
Traccar dispositivos

### ISSUE THREAD

**Issue by sobrarbe** [home-assistant/home-assistant.github.io#29067]
### Feedback

Hello, I'm looking at the fact that I have 3 devices with different names in traccar in home assistant and if I see 1, I can't see the other 2.  How do I see the 3 tracks with Traccar?  thank you

### URL

https://www.home-assistant.io/integrations/traccar/

### Version

2023.9.3

### Additional information

Hello, I'm looking at the fact that I have 3 devices with different names in traccar in home assistant and if I see 1, I can't see the other 2.  How do I see the 3 tracks with Traccar?  thank you

**Comment by ludeeus** [comment]
Please open an issue here <https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+traccar%22>, thanks 👍
