### ISSUE TITLE
Home Assistant Overall

### ISSUE THREAD

**Issue by dtbarn** [home-assistant/home-assistant.github.io#29075]
### Feedback

After getting through the "Onboarding' , I got really confused by the HA display and the instructions.  

It seemed that everything I tried to do led me to search for more knowledge.  For example - what is iTracker' and why should I enable it -- is it a virus -- .etc?  I did configure 2 printers, but only the second one gave me an option to enter a location.  In the process of searching out information, HA logged me out.  

Since I have forgotten my password, I followed the forgotten password instructions and used my monitor to enter the command "auth reset --usename <name> --password <pwd>"
and got the error "Error: Unknown error. see supervisor"

So, it looks like I have to start over and redo everything whole I still do not know what to do.

It seems that I do not know enough to use this product, so I'll have to delete it and maybe start over some later date.
By the way  -- I'm a retired software engineer with experience in multiple programing languages.

### URL

https://www.home-assistant.io/docs/locked_out/

### Version

2023.9.3

**Comment by frenck** [comment]
Hi there @dtbarn 👋 

I am sorry to hear you are having problems. Agreed, Home Assistant can still have quite the learning curve at times. We've worked hard to reduce that, but we are certainly not there yet.

However, there is an absolutely awesome community out there that can almost instantly help and guide you with anything you throw at it. If you need support or have questions, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). Especially the latter can be really helpful in getting answers fast.

../Frenck
