### ISSUE TITLE
Energy widget - not all sensors can be selected

### ISSUE THREAD

**Issue by AntonKremer** [home-assistant/home-assistant.github.io#29074]
### Feedback

The energey dashboard is great ... but unfortunatly I only can select certain sensors (starting with pv_"). This means not all sensors are avialable for grid import/export, pv generation, etc...

Why is there a restriction like this?

Best
Anton

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2023.9.3

**Comment by reedy** [comment]
Are the sensors you can select all of a certain unit? Are the ones you want to select of a different unit?

**Comment by klaasnicolaas** [comment]
You may find your answer here: https://www.home-assistant.io/docs/energy/faq/

./Klaas
