### ISSUE TITLE
pip3 install homeassistant==2023.9.3 not working

### ISSUE THREAD

**Issue by darf53** [home-assistant/home-assistant.github.io#29076]
### Feedback

seems only version [homeassistant-2023.9.2-py3-none-any.whl] (https://www.piwheels.org/simple/homeassistant/homeassistant-2023.9.2-py3-none-any.whl#sha256=c71ada73cf877221339642b3023b56a127555049ced511fe962c623f200862dd) is available...

and most recent installable version is pip3 install homeassistant==2023.7.3
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting homeassistant==2023.7.3
  Downloading https://www.piwheels.org/simple/homeassistant/homeassistant-2023.7.3-py3-none-any.whl (27.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.4/27.4 MB 4.7 MB/s eta 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.9.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
