### ISSUE TITLE
API Key for the web feed or device?

### ISSUE THREAD

**Issue by robertsearle** [home-assistant/home-assistant.github.io#29078]
### Feedback

I am unclear on a couple of points.   

1. Is the API key only needed for the web feed or do I need it for a local purple air device?
1. The device needs a cloud account and the device must be public for it to work, right?
1. Does the `1 million free points` reset every month or does _the device stops integrating_ with Home Assistant after a month-ish?

### URL

https://www.home-assistant.io/integrations/purpleair/

### Version

2023.9.3

**Comment by bachya** [comment]
> Is the API key only needed for the web feed or do I need it for a local purple air device?

This integration is for the PurpleAir cloud API.

> The device needs a cloud account and the device must be public for it to work, right?

Correct.

> Does the 1 million free points reset every month or does the device stops integrating with Home Assistant after a month-ish?

The API will reset each month.
