### ISSUE TITLE
Instructions Incorrect

### ISSUE THREAD

**Issue by TechnicallyBob202** [home-assistant/home-assistant.github.io#29089]
### Feedback

in the section for adding a homekit device to homeassistant, it says to add a "HomeKit Controller", but that is not an option.

### URL

https://www.home-assistant.io/integrations/myq/

### Version

2023.9.3

**Comment by reedy** [comment]
Where on https://www.home-assistant.io/integrations/myq/ does it say to add a "HomeKit Controller"?

It is not an option where?

**Comment by TechnicallyBob202** [comment]
The documentation says:
PAIRING WITH HOME ASSISTANT
Go to Settings >> Devices & Services in the Home Assistant UI.
Click the button with + sign, and from the list of integrations, select HomeKit Controller.
Select the MyQ-... bridge.
Enter the pairing code that is physically printed on a sticker on the bridge.
Complete the remaining steps.

for the step **Click the button with + sign, and from the list of integrations, select HomeKit Controller.**, there is no option for HomeKit Controller in the Home Assistant integrations.  Here is what you see when you go there:
<img width="489" alt="Screenshot 2023-10-10 at 10 19 07 AM" src="https://github.com/home-assistant/home-assistant.io/assets/16807837/41eaff54-0d5e-43b7-b282-729283cc9e8b">

**Comment by reedy** [comment]
Based on #29288 it would seem this language has been changed relatively recently.

**Comment by klaasnicolaas** [comment]
@rlyons20 Which version of Home Assistant - frontend are you running? I still see Homekit Controller instead of Homekit Device.
