### ISSUE TITLE
Alexa Setup

### ISSUE THREAD

**Issue by andiaa734** [home-assistant/home-assistant.github.io#29095]
### Feedback

Authorization URI: https://[YOUR HOME ASSISTANT URL]/auth/authorize

Access Token URI: https://[YOUR HOME ASSISTANT URL]/auth/token

Documentation states that custom ports cannot be used.
That's (no longer?) correct.

You can use  https://[YOUR HOME ASSISTANT URL]:1443/auth/authorize and Access Token URI: https://[YOUR HOME ASSISTANT URL]:1443/auth/token to specify a specific port. 

The only important thing is, that it needs to be SSL with a valid SSL Ceritificate.

### URL

https://www.home-assistant.io/integrations/alexa.smart_home/

### Version

2023.9.3

### Additional information

,

**Comment by jbouwh** [comment]
Did you test this yourself?

**Comment by andiaa734** [comment]
Yes. I tried this before i had to change my Ports in my Setup. And it worked.

**Comment by jbouwh** [comment]
May be you can check the attached Pull Request?
