### ISSUE TITLE
Onboarding Home Assistant

### ISSUE THREAD

**Issue by alexbk66** [home-assistant/home-assistant.github.io#29096]
### Feedback

https://www.home-assistant.io/getting-started/onboarding/ says "After entering the Home Assistant device’s address in your browser’s address bar, the welcome screen is shown" but the part "entering the Home Assistant device’s address" is incorrect.

It should either mention the default port (8123) or mDNS address homeassistant.local:8123 

Little mistake which causes some time wasted Googling.

Thank you.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2023.9.3

**Comment by c0ffeeca7** [comment]
Thank you for your feedback, @alexbk66 

Out of curiosity, how did you land on the onboarding page? What documentation page were you looking at before you got there?

**Comment by alexbk66** [comment]
> Out of curiosity, how did you land on the onboarding page? What documentation page were you looking at before you got there?

From https://www.home-assistant.io/installation#compare-installation-methods

**Comment by c0ffeeca7** [comment]
> > Out of curiosity, how did you land on the onboarding page? What documentation page were you looking at before you got there?
> 
> From https://www.home-assistant.io/installation#compare-installation-methods

I see. Thank you for pointing that out. That link is a bit misplaced there. Let me remove it.
So you did not follow any of the installation procedures that are listed on this page? What kind of installation did you do? What device are you on?

**Comment by alexbk66** [comment]
Sure, I followed both RPi and Windows instructions

https://www.home-assistant.io/installation/raspberrypi
https://www.home-assistant.io/installation/windows


They all point to the same "onboarding" page.

That's the reasonable question - after you finish the installation - how do you access the instance?  And that's when I had to waste time googling to find that I need to append the port (8123) to the instance IP.


Regards,

Alex


________________________________

**Comment by alexbk66** [comment]
> That link is a bit misplaced there. Let me remove it.

The link is required - as I explained above - but the "onboarding" page should mention the port 8123.

**Comment by c0ffeeca7** [comment]
> Sure, I followed both RPi and Windows instructions https://www.home-assistant.io/installation/raspberrypi https://www.home-assistant.io/installation/windows They all point to the same "onboarding" page. That's the reasonable question - after you finish the installation - how do you access the instance? And that's when I had to waste time googling to find that I need to append the port (8123) to the instance IP. Regards, Alex

I see. I'm sorry to hear you had to spend time googling this.

At the end of the installation instructions, there is a last step explaining how to enter the URL, including the port number. In case of the Raspberry Pi instructions, this is the step:

![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/2ab0ea87-ed21-45af-8e82-fe6ac1d938a4)

In the installation instruction for Windows, there is a similar step at the end.
