### ISSUE TITLE
Could you please add another enOcean-Device (Window-Sensor) to the enOcean Integration

### ISSUE THREAD

**Issue by UliGit** [home-assistant/home-assistant.github.io#29104]
### Feedback

Hi,
I was a FHEM user using Z-Wave and enOcean since 12 years and switched to HA now. 
I migrated all my Z-Wave components without any problems and also my enOcean Temperature-Sensors.
Unfortunately I cannot use my 10 enOcean Window Sensors with HA. I do not want to replace them by Z-Wave components because they work really great, because they do not need batteries.

Would it maybe be possible to integrate the following sensor: 
EnOcean Door and Window Sensor - "NodOn SDO-2-1-05"
EEP: D5-00-01

The enOcean log of the usb-stick shows me:

Windows is CLOSED:
2023-10-02 18:17:11.756 DEBUG (Thread-2) [homeassistant.components.enocean.dongle] 
   Received radio packet: 05:8F:52:..->FF:FF:FF:FF (-68 dBm): 0x01 
   ['0xd5', '0x9', '0x5', '0x8f', '0x52', '0x75', '0x0'] 
   ['0x0', '0xff', '0xff', '0xff', '0xff', '0x44', '0x0'] OrderedDict()
2023-10-02 18:17:11.756 DEBUG (Thread-2) [enocean.communicators.SerialCommunicator] 
   05:8F:52:..->FF:FF:FF:FF (-68 dBm): 0x01 
   ['0xd5', '0x9', '0x5', '0x8f', '0x52', '0x75', '0x0'] 
   ['0x0', '0xff', '0xff', '0xff', '0xff', '0x44', '0x0'] OrderedDict()
   
Windows is OPEN:
OPEN:
2023-10-02 18:16:41.418 DEBUG (Thread-2) [homeassistant.components.enocean.dongle] 
   Received radio packet: 05:8F:52:..->FF:FF:FF:FF (-68 dBm): 0x01 
   ['0xd5', '0x8', '0x5', '0x8f', '0x52', '0x75', '0x0'] 
   ['0x0', '0xff', '0xff', '0xff', '0xff', '0x44', '0x0'] OrderedDict()
2023-10-02 18:16:41.419 DEBUG (Thread-2) [enocean.communicators.SerialCommunicator] 
   05:8F:52:..->FF:FF:FF:FF (-68 dBm): 0x01 
   ['0xd5', '0x8', '0x5', '0x8f', '0x52', '0x75', '0x0'] 
   ['0x0', '0xff', '0xff', '0xff', '0xff', '0x44', '0x0'] OrderedDict()

That means, if the second byte of the array is '0x8' the window is open.
If the second byte of the array is '0x9' the window is open.
  
   

### URL

https://www.home-assistant.io/integrations/enocean/

### Version

2023.9.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by UliGit** [comment]
sorry, it's the wrong place. I will delete/close it
