### ISSUE TITLE
Not detecting reciever

### ISSUE THREAD

**Issue by Greg0125** [home-assistant/home-assistant.github.io#29117]
### Feedback

hi. I've tried to integrate my avr5 receiver but it just says 'failed to connect'.

I enter the IP address and leave port as 50,000 when prompted but then receive the error message. 

'Control' is enabled on the receiver itself and it is powered on.

Please can you advise what might be going wrong?

### URL

https://www.home-assistant.io/integrations/arcam_fmj/

### Version

2023.9.3

**Comment by frenck** [comment]
Hi there @Greg0125 👋 

It seems like you wanted to report an issue with a Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
