### ISSUE TITLE
HP7 2K 

### ISSUE THREAD

**Issue by guihom83** [home-assistant/home-assistant.github.io#29110]
### Feedback

hello, I would like to integrate the new EZVIZ HP7 2K intercom, but I cannot do it for the video stream.
I would also like to be able to use the ability to open the gate

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2023.9.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
