### ISSUE TITLE
missing the possibility to use the tilt or favorite position

### ISSUE THREAD

**Issue by Fistacho** [home-assistant/home-assistant.github.io#29112]
### Feedback

I have used your implementation of Netatmo integration successfully but I’m only missing the possibility to use the tilt or preferred position which I can select with my remote control. This can be activated by sending a value of -2 as position but this is not accepted by HA.

### URL

https://www.home-assistant.io/integrations/netatmo/

### Version

2023.9.3

**Comment by Fistacho** [comment]
I think many people are waiting for this

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
