### ISSUE TITLE
Missing data in the integration (gas)

### ISSUE THREAD

**Issue by fromNL** [home-assistant/home-assistant.github.io#29126]
### Feedback

I received a brand new meter, the Landis+Gyr E360 (DMSR 5)
sensor.gas_meter_gas_consumption
Gas Meter Gas consumption | unknown | state_class: total_increasing device_class: gas friendly_name: Gas Meter Gas consumption

It should update every 15 minutes, but it has been monitored almost a week now, but there still not one event/value.

Did the protocol for DMSR 5 change? Is the gas information missing or have they changed the layout of the datagrams?

Later on I get to hear it is submitted on the wrong page, sorry. 
It is now here: https://github.com/home-assistant/core/issues/101342#issue-1924859686

**Comment by frenck** [comment]
Hi there @fromNL 👋 

It seems like you wanted to report an issue with a Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
