### ISSUE TITLE
User rights

### ISSUE THREAD

**Issue by RoomRiver** [home-assistant/home-assistant.github.io#29146]
### Feedback

Documentation says about synology user: When creating the user, it is possible to deny access to all locations and applications.

But when I do that it's not working: 'Insufficient application privilege'

Logger: homeassistant.components.synology_dsm.coordinator
Source: components/synology_dsm/coordinator.py:73
Integration: Synology DSM ([documentation](https://www.home-assistant.io/integrations/synology_dsm), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+synology_dsm%22))
First occurred: 11:45:19 (9 occurrences)
Last logged: 11:52:56

Unexpected error fetching hostname.synology.me SynologyDSMSwitchUpdateCoordinator data: {'api': 'SYNO.SurveillanceStation.HomeMode', 'code': 160, 'reason': 'Insufficient application privilege', 'details': None}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/coordinator.py", line 73, in _async_update_data
    "switches": {"home_mode": await surveillance_station.get_home_mode_status()}
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synology_dsm/api/surveillance_station/__init__.py", line 153, in get_home_mode_status
    raw_data = await self._dsm.get(self.HOME_MODE_API_KEY, "GetInfo")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synology_dsm/synology_dsm.py", line 207, in get
    return await self._request("GET", api, method, params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synology_dsm/synology_dsm.py", line 296, in _request
    raise SynologyDSMAPIErrorException(
synology_dsm.exceptions.SynologyDSMAPIErrorException: {'api': 'SYNO.SurveillanceStation.HomeMode', 'code': 160, 'reason': 'Insufficient application privilege', 'details': None}

After giving the user SurveillanceStation rights all the entities popup. Now I only want volume information etc... 

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2023.9.3

**Comment by Quentame** [comment]
Hey !

It's either a documentation issue if it's not possible to fix the core code issue.
But for now, it's a core issue.

This issue should be created in the "core" repository, you can keep the same description while filling the issue template.

You can link the new issue to this one.

Thanks

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
