### ISSUE TITLE
Issue with another QSW swith device

### ISSUE THREAD

**Issue by knebb** [home-assistant/home-assistant.github.io#29148]
### Feedback

Hi,

for most of my switches the discover or manually added devices works fine.

There is one PoE switch (Series 2000, QSW-M2115P-2T2S where it does not work. Tryping to add by the default way always tells me "Connection failed".

As I was able to add other three QNAP switches I assume this switch is not properly tested?

I tried to get the logfiles in debug mode but do not know where they are stored and how I can get access of it.

Greetings

/KNEBB

### URL

https://www.home-assistant.io/integrations/qnap_qsw/

### Version

2023.9.3

**Comment by Noltari** [comment]
> ### Feedback
> Hi,
> 
> for most of my switches the discover or manually added devices works fine.
> 
> There is one PoE switch (Series 2000, QSW-M2115P-2T2S where it does not work. Tryping to add by the default way always tells me "Connection failed".
> 
> As I was able to add other three QNAP switches I assume this switch is not properly tested?
> 
> I tried to get the logfiles in debug mode but do not know where they are stored and how I can get access of it.
> 
> Greetings
> 
> /KNEBB
> 
> ### URL
> https://www.home-assistant.io/integrations/qnap_qsw/
> 
> ### Version
> 2023.9.3
> 
> ### Additional information
> _No response_

Hi @knebb,

As stated in https://github.com/Noltari/aioqsw/issues/2 that switch uses a different local API which isn't supported in aioqsw.

I don't have any of those, so I won't add support for it myself.
If anyone with that switch wants to add support in aioqsw I'd be happy to review and accept it.

Best regards,
Álvaro.

**Comment by knebb** [comment]
I guess adding support is a little bit more complicated compared to writing scripts?

I am willing to offer my device to get the needed information but I doubt I am able to put it into your code. I do not even know where to start :(

/KNEBB

**Comment by Noltari** [comment]
@knebb unfortunately only issues should be reported here.
New functionality or requests should be done in the Home Assistant community forum.
Maybe someone else with that switch is willing to add support...

**Comment by Noltari** [comment]
@home-assistant close
