### ISSUE TITLE
Possible to add Kasa Thermostatic ?

### ISSUE THREAD

**Issue by Notpek** [home-assistant/home-assistant.github.io#29158]
### Feedback

Hey is it possible to add the Thermostatic devices to the plugin ?

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2023.9.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
