### ISSUE TITLE
I cannot get this to work

### ISSUE THREAD

**Issue by johnradford49** [home-assistant/home-assistant.github.io#29159]
### Feedback

The documentation is so poor, it gives no indication of how to get it to work. 
I have searched for example configuration code but cannot find anyone who has got this to work.

### URL

https://www.home-assistant.io/integrations/water_heater/

### Version

2023.9.3

**Comment by frenck** [comment]
The page you linked is a building block for other integrations to use. You can not create/add those yourself. Water heaters are provided by other integrations.

This is similar to, e.g., the light integration, which is a building block for other integrations that want to provide lights. (For example, the Philips Hue integration provides light entities for each light bulb it is connected to).

Please consult the integration documentation for your brand/type of water heater for information on how to hook it up. If, as a result, you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).


../Frenck
