### ISSUE TITLE
App don't work

### ISSUE THREAD

**Issue by Oscarbin001** [home-assistant/home-assistant.github.io#29155]
### Feedback

There is no URL https://server.growatt.com/ among the possible choices

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.9.3

**Comment by Oscarbin001** [comment]
Thanks but  @muppet3000 have a login problem

**Comment by muppet3000** [comment]
Closing as duplicate of [#100874](https://github.com/home-assistant/core/issues/100874)

**Comment by muppet3000** [comment]
@home-assistant close

**Comment by Oscarbin001** [comment]
![image](https://github.com/home-assistant/home-assistant.io/assets/146742260/351585fa-0cd6-4509-83c3-646a19fb7545)


Excuse me for delay time of responce; I Try all but the error is the same; Can you help me? I  Try all described in #100874
Thanks in advance

**Comment by muppet3000** [comment]
Please see the final comment in #100874
