### ISSUE TITLE
Play On Roku no longer works - remove documentation

### ISSUE THREAD

**Issue by dnikles** [home-assistant/home-assistant.github.io#29165]
### Feedback

As the playon Roku functionality no longer exists [see here](https://community.roku.com/t5/Solving-playback-issues/OS-11-5-Roku-11-5-broke-Play-on-Roku-video-playback/m-p/827302 ) the Play on Roku and Camera Stream sections should be removed.

### URL

https://www.home-assistant.io/integrations/roku/

### Version

2023.10.0

**Comment by ctalkington** [comment]
I'm OK removing this until I'm able to attempt to restore functionality
