### ISSUE TITLE
Which password goes in the dialog box?

### ISSUE THREAD

**Issue by Uluen** [home-assistant/home-assistant.github.io#29175]
### Feedback

The Adax account password?
The access token created?
The Wi-Fi password..?

Tried all 3, still "failed to connect".

### URL

https://www.home-assistant.io/integrations/adax/

### Version

2023.10.0

**Comment by klaasnicolaas** [comment]
This is already described in the docs, so I'm closing this issue.

> In the configuration popup you will need the Account ID, and the generated API password (not the account password)
