### ISSUE TITLE
Please add sensors for heatpump Versati III

### ISSUE THREAD

**Issue by hldijks** [home-assistant/home-assistant.github.io#29189]
### Feedback

Hi , first of all thanks for this lovely integration , i am using it allready with my Gree airconditioners

Now i am also using this integration with my Gree monoblock heatpump. ( versati iii )
it would be great to have the sensors and modes that are also available in the android app

modes: 
priority
cool
heat
hot water
cool+ hot water
heat + hot water

temperature sensors : 
T-water in PE
T-water out PE
T-optional water sens
T-tank ctrl
T-remote-room

staus view sensors :
Tank heater
defrost
HP-heater 1
HP-heater 2
HP-antifree

Cheers !

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2023.10.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
