### ISSUE TITLE
Information missing

### ISSUE THREAD

**Issue by el-Presi** [home-assistant/home-assistant.github.io#29188]
### Feedback

Hi there !

Nice cool feature (https://www.home-assistant.io/integrations/private_ble_device)!!
But I would like to understand, which devices are actually tracking my IRKs?
I do not have BT plugged or built into my HA Hardware. I am using: ESPHome as BT Relay and I have some Shelly Plus device around here. How do I know, which device/s are tracking here? :) 

Thanks!

### URL

https://www.home-assistant.io/integrations/private_ble_device

**Comment by Jc2k** [comment]
This isn't the place for support (so will be closing this), but fwiw I will be extending the docs to explain this.

For now, the device tracker has an extra attribute that shows the source MAC address. That's the MAC address of the proxy that can see it. Hope to show the name of the proxy in the future as well.

Note that for various reasons you might get unexpected behaviour if you try to do room presence detection with this. When there are multiple proxies spotting your phone, we pick one based on signal quality, not physical distance. Sometimes these happen to align. If you have different proxies with different antenna they are less likely to align.

Hope that helps.

**Comment by el-Presi** [comment]
ok thanks! Github asked be to provide feedback to the article here :)
