### ISSUE TITLE
New Shelly Mini

### ISSUE THREAD

**Issue by Tom-Germany** [home-assistant/home-assistant.github.io#29180]
### Feedback

Hey there,
I have integrated one of the new mini appliencies to my Network but so far it is not possible to implement it to Homeassistant (HACS).
Has anybody already

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```
 faced the same issue and was it possible to add it to Homeassistant?
Thanks for your Support

<img width="1194" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/36127912/a961d72f-1344-4742-a9e3-f270086bb4ba">

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2023.10.0

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
