### ISSUE TITLE
Reference to unmaintained add-on

### ISSUE THREAD

**Issue by jbestt** [home-assistant/home-assistant.github.io#29193]
### Feedback

Please delete the link to the unmaintained influxdb add-on

### URL

https://www.home-assistant.io/integrations/influxdb/

### Version

2023.10.0

**Comment by frenck** [comment]
I think it can be removed, as we should not put this in the docs (it is thirty party) the community add-ons project, is however alive, kicking and in maintained (the last commits to that specific add-on was actually last week).

The reasoning behind this feedback is thus incorrect.

../Frenck
