### ISSUE TITLE
Strange behavior using integration 

### ISSUE THREAD

**Issue by IlyaChaban** [home-assistant/home-assistant.github.io#29192]
### Feedback

After successfully setting everything up I have following error

`2023-10-05 17:21:32.843 WARNING (MainThread) [homeassistant.components.withings] Webhook not registered - https and port 443 is required to register the webhook`

During setup it wants to use https protocol but my homeasssitant uses http

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2023.10.0

**Comment by joostlek** [comment]
This just means it's now using polling to get your data, and you're not able to use the sleeping sensor

**Comment by IlyaChaban** [comment]
So, how can i get older data that is already on the withings service. Is is collection only new data? Only new measurements appearing in dataset.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
