### ISSUE TITLE
Wrong Data = Loop and unable to fix

### ISSUE THREAD

**Issue by coasttech** [home-assistant/home-assistant.github.io#29191]
### Feedback

If you put in the incorrect data there is no way out of this loop. It would be nice to add some documentation on how to get out of this loop. I have not deep dived into fixing this and I can add more data on how to fix this if I am able to remove the failed integration add. 

`{"errors":[{"message":"redirect_uri_mismatch: The redirect URI provided is missing or does not match partner callback url"}]}`

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2023.10.0

**Comment by joostlek** [comment]
Euh I am not sure what you are exactly experiencing, can you describe that?

**Comment by coasttech** [comment]
> Euh I am not sure what you are exactly experiencing, can you describe that?

When setting up the integration, and obviously putting in the incorrect information I am sent to a page with the following error above. After this has happened, there is no way to correct this. If I go to reset up the integration, it does not ask me for any new information. It just instantly goes to the old data that was it was put in. There is nowhere for me to correct this. I've done the basic troubleshooting steps, but I believe in order to fix this I'm gonna have to go in via SMB and try to find any data that's been stored to delete it to re-initiate the integration addin.

Euh, I hope that better explains it.

**Comment by joostlek** [comment]
Oooh, you're talking about application credentials. Checkout the integration tab and then the 3 dots at the top right, you can find all your application credentials there

**Comment by coasttech** [comment]
> Oooh, you're talking about application credentials. Checkout the integration tab and then the 3 dots at the top right, you can find all your application credentials there

The issue is once you enter the wrong credentials it's too late there's no three dots. There's only the ability to reset up the integration and then have it fail afterwards.

**Comment by Tischi86** [comment]
@coasttech can you check https://developer.withings.com/dashboard/ that the callback URL of the app is `https://my.home-assistant.io/redirect/oauth`, in my case the endpoint was `https://xxxxxxxxui.nabu.casa/auth/external/callback`. This was my problem and solution for this problem.

**Comment by joostlek** [comment]
Oh right, I responded to issues about this on the core repo. If you have the "my" integration enabled, the callback URL is always the my link found in the docs.

**Comment by frenck** [comment]
Just checked the docs, it contains the correct data; therefore closing the issue on this end.

If you are in need for support, please join our Discord chat, or check out our community forum.

../Frenck

**Comment by coasttech** [comment]
Is the fact that incorrectly setting up the integration breaks setting it up at all not an issue? Support is not needed, im just looking to point out something that breaks if your trying to setup the integration.  @frenck @joostlek

**Comment by joostlek** [comment]
I mean, the docs explain pretty clearly which steps you need to do, and if you have my home assistant disabled, it also shows steps on what to do in that case.

**Comment by coasttech** [comment]
Are you saying follow the instructions, get it correct, and don't mess anything up? Is that the idea?

**Comment by joostlek** [comment]
In theory, yes. Like I've seen more issues like this on the core repo and in all cases it was because of having a wrong callback url set. So I am really suspecting your case is the same. And it all got fixed by following the instructions.

If you feel that this is a different case, feel free to reach out on Discord and I we can take a look together.
