### ISSUE TITLE
Switchbot hub

### ISSUE THREAD

**Issue by siulass** [home-assistant/home-assistant.github.io#29203]
### Feedback

Hello,

It seems that switchbot hub integration does not discover any devices. is that known issue?

### URL

https://www.home-assistant.io/integrations/switchbot_cloud/

### Version

2023.10.0

**Comment by frenck** [comment]
Thank you for reaching out, this is the issue tracker in which we collect documentation feedback.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
