### ISSUE TITLE
libopenblas-dev required for Home Assistant Core 2023.10.0

### ISSUE THREAD

**Issue by jbfolkerts** [home-assistant/home-assistant.github.io#29212]
### Feedback

after upgrading to 2023.10.0 numpy fails to install and portions of HA don't start.  It complains about not finding BLAS library.  Adding this library to the set of required packages fixed the problem.  

sudo apt-get install libopenblas-dev -y

Suggest updating the set of required apt packages at 

https://www.home-assistant.io/installation/linux#install-home-assistant-core

### URL

https://www.home-assistant.io/installation/linux#install-home-assistant-core

### Version

2023.10.0

### Additional information

**What type of installation are you running?**

Home Assistant Core on Raspberry Pi 3B running Bookworm distro

**Integration causing the issue**

pyTurboJPEG and numpy

**Diagnostics information**

pip install pyturbojpeg
Collecting pyturbojpeg
  Using cached PyTurboJPEG-1.7.2.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from pyturbojpeg)
  Using cached numpy-1.26.0.tar.gz (15.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      + /srv/homeassistant/bin/python3 /tmp/pip-install-gefd7m1v/numpy_47cd944402f04b9f839362423d7aca21/vendored-meson/meson/meson.py setup /tmp/pip-install-gefd7m1v/numpy_47cd944402f04b9f839362423d7aca21 /tmp/pip-install-gefd7m1v/numpy_47cd944402f04b9f839362423d7aca21/.mesonpy-07vpsia0/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-gefd7m1v/numpy_47cd944402f04b9f839362423d7aca21/.mesonpy-07vpsia0/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: /tmp/pip-install-gefd7m1v/numpy_47cd944402f04b9f839362423d7aca21
      Build dir: /tmp/pip-install-gefd7m1v/numpy_47cd944402f04b9f839362423d7aca21/.mesonpy-07vpsia0/build
      Build type: native build
      Project name: NumPy
      Project version: 1.26.0
      C compiler for the host machine: cc (gcc 12.2.0 "cc (Raspbian 12.2.0-14+rpi1) 12.2.0")
      C linker for the host machine: cc ld.bfd 2.40
      C++ compiler for the host machine: c++ (gcc 12.2.0 "c++ (Raspbian 12.2.0-14+rpi1) 12.2.0")
      C++ linker for the host machine: c++ ld.bfd 2.40
      Cython compiler for the host machine: cython (cython 3.0.3)
      Host machine cpu family: arm
      Host machine cpu: armv7l
      Program python found: YES (/srv/homeassistant/bin/python3)
      Found pkg-config: /usr/bin/pkg-config (1.8.1)
      Run-time dependency python found: YES 3.11
      Has header "Python.h" with dependency python-3.11: YES
      Compiler for C supports arguments -fno-strict-aliasing: YES
      Message: During parsing cpu-dispatch: The following CPU features were ignored due to platform incompatibility or lack of support:
      "XOP FMA4"
      Test features "NEON" : Supported
      Test features "NEON_FP16" : Supported
      Test features "NEON_VFPV4" : Supported
      Test features "ASIMD" : Unsupported due to Compiler fails against the test code of "ASIMD"
      Test features "ASIMDHP" : Unsupported due to Implied feature "ASIMD" is not supported
      Test features "ASIMDFHM" : Unsupported due to Implied feature "ASIMD" is not supported
      Configuring npy_cpu_dispatch_config.h using configuration
      Message:
      CPU Optimization Options
        baseline:
          Requested : min
          Enabled   :
        dispatch:
          Requested : max -xop -fma4
          Enabled   : NEON NEON_FP16 NEON_VFPV4
      
      Library m found: YES
      Found CMake: /usr/bin/cmake (3.25.1)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      
      ../../numpy/meson.build:207:4: ERROR: Problem encountered: No BLAS library detected! Install one, or use the `allow-noblas` build option (note, this may be up to 100x slower for some linear algebra operations).
      
      A full log can be found at /tmp/pip-install-gefd7m1v/numpy_47cd944402f04b9f839362423d7aca21/.mesonpy-07vpsia0/build/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by frenck** [comment]
This depends on your system and setup. As stated on that page:

![CleanShot 2023-10-06 at 18 13 46](https://github.com/home-assistant/home-assistant.io/assets/195327/4d149162-2560-47b1-8262-d27d876c5198)

You are running into exactly such a thing.

../Frenck
