### ISSUE TITLE
Switch measurement data

### ISSUE THREAD

**Issue by deepc2020** [home-assistant/home-assistant.github.io#29216]
### Feedback

It would be helpful if you could use MYSTROM switch consumption measurement in HA for energy dashboard

### URL

https://www.home-assistant.io/integrations/mystrom/

### Version

2023.10.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
