### ISSUE TITLE
example of multiple notify groups

### ISSUE THREAD

**Issue by solstyce9** [home-assistant/home-assistant.github.io#29215]
### Feedback

Most people use multiple notify groups.  I spent a lot of time searching for the correct syntax for that and saw lots of people struggling with the same thing.  It would be helpful if the notify group example showed how to configure more than one notify group in your configuration.yaml.
e.g.

# notification groups
notify:
  - name: "john_phone"
    platform: group
    services:
      - service: mobile_app_john_s_pixel_7
  - name: "all_devices"
    platform: group
    services:
      - service: mobile_app_john_s_pixel_7
      - service: mobile_app_mobile_app_sm_t760

### URL

https://www.home-assistant.io/integrations/group/

### Version

2023.10.1

**Comment by frenck** [comment]
>  It would be helpful if the notify group example showed how to configure more than one notify group in your configuration.yaml.

It is shown as a YAML list. Lists in YAML can be added to and thus expanded with as many occurrences as you like. The example correctly matches our guidelines at this point.

Thanks for your feedback that is appreciated 👍 

../Frenck
