### ISSUE TITLE
MQTT Discovery is confusing

### ISSUE THREAD

**Issue by buteomont** [home-assistant/home-assistant.github.io#29218]
### Feedback

I have read and re-read the section on _MQTT discovery_ and cannot understand how to take advantage of it.  My mental image of "discovery" is where HA "finds" devices and creates entities for them.  Does MQTT discovery do this?  The documentation doesn't really say.

I have many devices that report their status via MQTT, mostly through **rtl_433**.  I can go to _Settings-->Devices & services-->MQTT-->Configure_ and publish or listen to topics all day, and that works fine. But I can't seem to understand from reading the documentation how to use **_MQTT discovery_**.

### URL

https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery

### Version

2023.10.1

**Comment by jbouwh** [comment]
MQTT discovery does not discover or find devices directly. Instead it listens to published configurations. This information could either be published by a device, service or script. Anyone with access to the shared MQTT broker van publish these configurations. The documentation describes how these configuration payloads should be published.
When a valid configuration is published, HA `mqtt` will process this configuration immediately and add the entity to Home Assistant. From there `mqtt` will use the command topics from the configuration to control the device, assuming the device listens to the commands. Further `mqtt` subscribes to the state topics to listen for any state changes from the device, assuming the device will publish them are the state topics mentioned in the configuration.
So in fact the Home Assistant `mqtt` integration does not know who is communicating the config or state updates.
Fur devices that seems MQTT updates or but listen to certain topics, but do not publish a configuration, a manual MQTT item/entity can be configured in YAML, this skips the discovery phase.
Some solutions like Zigbee2MQTT or Zwave2MQTT use Home Assistant `mqtt` discovery as a bridge to Home Assistant. In these cases the Zigbee or Z-wave controlled devices do not support MQTT directly.
Hope I made it more clear now.

**Comment by buteomont** [comment]
Thanks, that helps.  I think I understand:

In summary, MQTT "Discovery" is a way to install and configure MQTT devices in Home Assistant by publishing the configuration of these devices using JSON to the MQTT broker instead of writing it directly to the configuration file in YAML. 

My main difficulty was understanding that MQTT devices aren't really discovered in the same sense as other devices, you have to publish the configuration of them to the broker.  Perhaps this could be made more clear in the documentation.

I also figured out that this is not really necessary for many of my devices, as their MQTT is generated by rtl_433 and used in automations which can access the MQTT messages directly.

Thanks!
