### ISSUE TITLE
No mention of a supervised install

### ISSUE THREAD

**Issue by antamy** [home-assistant/home-assistant.github.io#29228]
### Feedback

This is extremely frustrating.  All I wanted was to install a test environment to try out some esphome functionality.  So I followed the instructions to install on WSL, which then involved a lot of work to upgrade Python.  And once I finally got this working, I could not install the addons because I need a supervised installation!!   And nowhere is this mentioned.  Why on earth is there a need for a core (reduced functionality) version and a supervised version, yet the instructions don't mention this.

### URL

https://www.home-assistant.io/installation/windows/

### Version

2023.10.1

**Comment by frenck** [comment]
> I could not install the addons because I need a supervised installation!

Those are not available on Windows. Hence, it isn't listed as a Windows installation method.

The comparison of the installation methods is listed on the installation page:

<https://www.home-assistant.io/installation/#compare-installation-methods>
