### ISSUE TITLE
Add support for D-Link DSP-W320

### ISSUE THREAD

**Issue by chalcids** [home-assistant/home-assistant.github.io#29229]
### Feedback

Would we be able to expand the functionality of this integration to also include the D-Link DSP-W320 Outdoor Switch? If its possible is this something I can do?

### URL

https://www.home-assistant.io/integrations/dlink/

### Version

2023.10.1

### Additional information

https://shop.dlink.ca/products/mydlink-outdoor-wi-fi-smart-plug-dsp-w320

**Comment by tkdrob** [comment]
Hi. Thanks for you interest. We use Github to track issues. Feature requests are for the forums. Please go there to start a thread if one does not already exist. Thanks

**Comment by tkdrob** [comment]
@home-assistant close
