### ISSUE TITLE
Add OREin Matter Smart Light Bulbs OS0100811267 as supported

### ISSUE THREAD

**Issue by lk229** [home-assistant/home-assistant.github.io#29226]
### Feedback

These are from the AIDot product group and are also sold under the Linkind name. Manufacturer shows as Leedarson in device table. I'm seeing full on/off, color, and white temperature control working correctly. Was able to add first to HA Matter controller and then also to AIDot's app for firmware update.
![2023-10-07](https://github.com/home-assistant/home-assistant.io/assets/36109757/0501c132-dfb2-4658-ac6a-7fa04b333ee1)

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2023.10.1

**Comment by 715Steve** [comment]
I can also agree, I have added to HA, then to AiDot app without issue.

**Comment by marcelveldt** [comment]
Good to hear the devices are working fine within the HA Matter implementation.

As for extending our documentation, we're actually going to remove the whole section with supported devices as it is outdated and not complete. There are better sources to get that information.

Thanks for the suggestion anyway!
