### ISSUE TITLE
Please can anyone help me get the Powerwall Intergration working

### ISSUE THREAD

**Issue by Toolroom1** [home-assistant/home-assistant.github.io#29227]
### Feedback

On my mobile phone I have logged into the TEG-XXX network, although cannot log into a browser once connected. Once the WiFi is connected I then looked up the IP Address shown, I then used this IP when asked trying to get into the HA app followed by the password which I use the last 5 characters of my Powerwall Serial Number, but it fails every time. Any help much appreciated.

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2023.10.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
