### ISSUE TITLE
SUBSTRATION

### ISSUE THREAD

**Issue by lmahave** [home-assistant/home-assistant.github.io#29220]
### Feedback

Could you add the subtraction to the +/- helper?
Sometimes I need to subtract and not add.
It would be enough to add a check where it is stated which entities add and which subtract.
Thank you.

### URL

https://www.home-assistant.io/integrations/min_max/

### Version

2023.10.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
