### ISSUE TITLE
Not True

### ISSUE THREAD

**Issue by jtt77** [home-assistant/home-assistant.github.io#29238]
### Feedback

https://www.home-assistant.io/integrations/ffmpeg/

It is not in this version of https://github.com/home-assistant/operating-system/releases/download/10.5/haos_ova-10.5.ova

### URL

https://www.home-assistant.io/integrations/ffmpeg/

### Version

2023.10.1

**Comment by frenck** [comment]
> It is not in this version of [home-assistant/operating-system@10.5 haos_ova-10.5.ova (download)](https://github.com/home-assistant/operating-system/releases/download/10.5/haos_ova-10.5.ova)

Correct. Home Assistant is distributed as a container running on that OS, meaning ffmpeg distributed inside the container, not the OS.

../Frenck

**Comment by jtt77** [comment]
Thanks, can you tell me what I have to install to be able to use Ffmpeg?

________________________________

**Comment by frenck** [comment]
> Thanks, can you tell me what I have to install to be able to use Ffmpeg?

If you run the Home Assistant Operating System, Supervised or Container installation methods, there is nothing you have to do. It is installed and shipped with our containers by default.

../Frenck

**Comment by jtt77** [comment]
I'm sorry, I thought that was what I was doing? Can you provide me with the link please? Am super confused.

________________________________

**Comment by frenck** [comment]
> I'm sorry, I thought that was what I was doing? Can you provide me with the link please? Am super confused.

There is no link: as there is nothing to do.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck

**Comment by jtt77** [comment]
I think understand sorry for being dumb, basically I need to run it on dedicated hardware (so nothing with VM at the end of listing on the download page)

________________________________

**Comment by frenck** [comment]
>  basically I need to run it on dedicated hardware

No. You don't need to run it like that. All installation methods support ffmpeg. In case you run it on bare metal (Home Assistant Core in your own Python environment), you need to install and configure ffmpeg yourself. In all other cases, we ship ffmpeg for you and there is nothing you need to do to make it work. It will just work out of the box in those cases.

But again, if you need help, I would strongly recommend joining our Discord chat server. There are many people there that can help you guide :)

../Frenck

**Comment by jtt77** [comment]
I see, there is no FFMPEG in /use/bin/ in either installations I've tried and there are discussions online suggesting this https://community.home-assistant.io/t/how-to-get-ffmpeg/418594

I will try Discord, nothing is ever easy.

Thanks



________________________________
