### ISSUE TITLE
I can't tell if I have Tuya v2 or not

### ISSUE THREAD

**Issue by dbpage** [home-assistant/home-assistant.github.io#29246]
### Feedback

I followed the Tuya Integration instructions but get stuck at "1106: permission deny."  I don't know if this is a documentation or integration issue.

My first difficulty is with the 1106 error description, "App account not linked with cloud project: On the [Tuya IoT Platform](https://iot.tuya.com/cloud/), **you have linked devices by using Tuya Smart or Smart Life app** in your cloud project."

I have a linked device, a Smart Socket Model WP3, in my Tuya Smart Life app.  
The first sentence says, "App account not linked with cloud project."  The second sentence says, "you have linked devices by using Tuya Smart or Smart Life app." 
 The "not" shouldn't be there in the first sentence, or a "not" is missing in the second sentence.  I don't know which.  Does the device have to be linked in the app?  I have a device linked in the app (see screenshot).  Maybe I shouldn't.

My second difficult is finding the data center.  I am in the Eastern US.  My device is listed in the Tuya Smart Life app as "United States of America/Can..."  On the Tuya IOT Platform website my device is listed as "Western America Data Center."  My device is clearly shown on the app and website (see screnshots).  I still get the 1106 error.

My third difficulty is that the app FAQ states "Since we no longer support Home Assistant at this time, products that previously support Hove Assistant will continue to support it.  Previously unsupported products and new products will no longer support Home Assistant" (see screenshot).

My Home Assistant is new, my device is new and the integration is new.  If this means I'm out of luck, it sure would be good to know this.  I suggest adding into the Documentation something that tells me if I can use it or not.  There are no dates, version numbers or anything else to tell me that the Tuya Integration is not for me.

My fourth difficulty is that I see a confusing discussion about Tuya v2 integration.   Some say it works, some don't.

Your advice will be appreciated.

Thanks!
Dennis

![Tuya Smart Life app - Account and Security](https://github.com/home-assistant/home-assistant.io/assets/25377544/16c1b48a-6896-4ade-bc95-ebfe853d8f02)
![Tuya Smart Life app - Home Assistant Not Supported](https://github.com/home-assistant/home-assistant.io/assets/25377544/c0619abc-b1b5-4acb-bdf8-d7f42e77904d)
![Tuya IOT Platform - Cloud - Device](https://github.com/home-assistant/home-assistant.io/assets/25377544/20487794-44cc-47a4-8985-cfe28b0a9e64)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.10.1

**Comment by dbpage** [comment]
I get 1106 error description, "App account not linked with cloud project: On the [Tuya IoT Platform](https://iot.tuya.com/cloud/), you have linked devices by using Tuya Smart or Smart Life app in your cloud project."

I would still like a response to my questions:
1. I have a device linked in the app. Does the device have to be linked in the app?
2. My device is listed in the Tuya Smart Life app as "United States of America/Can..." On the Tuya IOT Platform website my device is listed as "Western America Data Center."  Is this an error?
3. Does the integration support my new Home Assistant, new device and new integration?
4. How can I tell if my device is Tuya V2?

**Comment by codyc1515** [comment]
This should be resolved in 2024.2.

**Comment by frenck** [comment]
All solved in Home Assistant 2024.2 indeed 👍 

../Frenck
