### ISSUE TITLE
Mopeka Pro Check Universal

### ISSUE THREAD

**Issue by ak68-hub** [home-assistant/home-assistant.github.io#29249]
### Feedback

The new Mopeka Pro Universal is nor yet supported, it would be very fine to intergrate it, because the old Pro-Plus and Pro-Check versions are not produced any more

### URL

https://www.home-assistant.io/integrations/mopeka/

### Version

2023.10.1

### Additional information

https://www.mopekaiot.com/product/mopeka-pro-check-universal-aluminum-plastic-composite-and-poly-tanks

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
