### ISSUE TITLE
NWS Documentation Mentions Multiple Entities

### ISSUE THREAD

**Issue by The00Dustin** [home-assistant/home-assistant.github.io#29256]
### Feedback

With Home Assistant 2023.9, the move away from multiple entities has been initiated.  The documentation for NWS says this:

> Two weather entities are created for each entry in the configuration: one for day and night forecasts and one for hourly forecasts. The hourly forecast entity is disabled after configuration but can be enabled by the user.

### URL

https://www.home-assistant.io/integrations/nws/

### Version

2023.10.1

### Additional information

This outdated information lead to extra effort on my part and on the part of those assisting me in the forum, so I tried to correct it with #29134.  However, that PR was closed for the very reason I created it.  Given this, it seems safe to assume that my correction wasn't as clear as I thought it was.

**Comment by The00Dustin** [comment]
To the best of my knowledge, this documentation is still wrong, and since I my PR was rejected, I still don't know how to correct it.

**Comment by The00Dustin** [comment]
This (still incorrect) documentation was linked in the 2024.4 "Backward-incompatible changes" section.  I reviewed my rejected PR and don't really see how I could improve it.

**Comment by kamiyo** [comment]
I know I'm marked as code owner but I don't have much knowledge of what is
acceptable or not for doc PRs... Hopefully someone else from the team can
clarify.

**Comment by The00Dustin** [comment]
My PR wasn't rejected because it was unacceptable, it was rejected because it was incorrect.  If it had been rejected due to acceptability, I would correct it and resubmit, but I can't figure out why it was deemed incorrect, so I can't correct it.  It is possible that it was misread, but I don't want to be an annoyance by resubmitting it as is.

**Comment by MatthewFlamm** [comment]
It was incorrect at the time of opening, but it is now correct.

**Comment by The00Dustin** [comment]
I can't understand that, either, as I only opened it after I had that experience with that integration and verified it was the expected new experience on the community forums.  Regardless, as it is apparently correct, do I need to take further steps like submitting it again and linking it to this issue or can it be re-opened and merged as is?

**Comment by MatthewFlamm** [comment]
Sorry I didn't read the PR that was closed. The reasoning given is confusing to me too, as you were implementing the change.


In reality, your changes were submitted at a time when HA was moving away from multiple entities, but NWS had not yet implemented this. In my opinion your PR was incorrect at the time but for different reasons than stated. I would reopen some version of the PR, I can chime in as the code owner.

Feel free to cc me if I don't get automatically ccd

**Comment by The00Dustin** [comment]
I think I figured it out after submitting the PR.  `weather.get_forecast` has been deprecated, so I should have used `weather.get_forecasts` and my PR would have been fine if I didn't mention the service at all.  Luckily, I used `weather.get_forecasts` in my new PR even though I didn't yet understand that was the problem with my original PR.

**Comment by rct** [comment]
https://github.com/home-assistant/core/pull/112503 got merged 2024-03 and got mentioned in the 2024.4 release notes,  but yet the documentation hasn't been updated.
