### ISSUE TITLE
Not possible to get keys for facebox anymore

### ISSUE THREAD

**Issue by jornare** [home-assistant/home-assistant.github.io#29265]
### Feedback

I was intrigued by the facebox integration, but it seems like they are not issuing keys anymore and hence it is not possible to get it up and running for new users.

### URL

https://www.home-assistant.io/integrations/facebox/

### Version

2023.10.1

**Comment by reedy** [comment]
Amusingly their own documentation doesn't mention that you can't get a key currently - https://machinebox.io/docs/setup/box-key

**Comment by jornare** [comment]
No. It just seems not maintained. Try and follow the links to creating an
account, and the LinkedIn webpage does not give youbthe option.

man. 9. okt. 2023, 21:44 skrev Sam Reed ***@***.***>:

**Comment by reedy** [comment]
Helpful...

https://machinebox.io/login?return_url=%2Faccount says "Create a Veritone Developer account or login below", click "Create new Veritone account" takes you to https://www.veritone.com/#/signUp?type=developer&source=machinebox which is not a sign up page, nor does it have any sign of one...

I wonder if this makes it in scope to be removing the integration.

https://github.com/home-assistant/core/blob/dev/CODEOWNERS doesn't list a specific maintainer

**Comment by reedy** [comment]
Their signup workflow seems to still be broken (no way to create an account and get an API key).

@frenck Would this be good enough reasoning to request removal of the integration from HA?

https://www.home-assistant.io/integrations/facebox/ also suggests it's only used by 2 users.

**Comment by reedy** [comment]
Integration is being dropped, so task can be closed...

**Comment by frenck** [comment]
The integration has been removed for 2024.2
