### ISSUE TITLE
Torque (OBD2) Logging Not Secure

### ISSUE THREAD

**Issue by dapug** [home-assistant/home-assistant.github.io#2927]
https://home-assistant.io/components/sensor.torque/

Paste your username and password in the URL, without HTTPS? Seriously?

**Comment by fabaff** [comment]
We already mention on several location in the documentation that protection is needed but it's doesn't harm to add it one more time.

**Comment by TRusselo** [comment]
documentation instructions no longer work.
https://www.home-assistant.io/integrations/torque/

**Comment by frenck** [comment]
@TRusselo This is an closed issue from 2017, please don't bump stuff that old. Thanks 👍
