### ISSUE TITLE
Backticks unparsed in <div class='note'>

### ISSUE THREAD

**Issue by reedy** [home-assistant/home-assistant.github.io#29278]
### Feedback

Seen on https://www.home-assistant.io/integrations/openweathermap/

![Screenshot 2023-10-09 at 23 24 50](https://github.com/home-assistant/home-assistant.io/assets/67615/c84d648d-cffb-4cde-a5ce-5970f6d01ea1)

```html
<div class='note'>
If you register an new API key with OpenWeatherMap, it will be activated automatically, this typically takes between 10 minutes and 2 hours
after your successful registration. Keep in mind when configuring this integration, that you new API key might
not be activated yet. Recent policy changes limit the API access for new registered users with a free plan, they should select the `hourly` mode. The other modes require a paid subscription plan. Invalid API-key errors might occur if your API key is used with the other modes.
</div>
```

### URL

https://www.home-assistant.io/integrations/openweathermap/

**Comment by frenck** [comment]
It needs an empty line after opening and before closing HTML tags to allow the parser used by Jekyll to switch language context between HTML & Markdown.
