### ISSUE TITLE
Create own favorite radio stations list and ability to use multiple fillers

### ISSUE THREAD

**Issue by BhavinD99** [home-assistant/home-assistant.github.io#29284]
### Feedback

1) Need to be able to create a favorite radio station list for quick access. 

2) Browsing through the long list of available stations, even with the limited filtering is quite hard. Please add ability to select multiple filters- example: country and language together, which will help narrow down the list

thanks

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2023.10.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
