### ISSUE TITLE
Generic Thermostat

### ISSUE THREAD

**Issue by ChrisHayes31** [home-assistant/home-assistant.github.io#29285]
### Feedback

Thank you for the Generic Thermostat I love it. I also am fully committed to HA have been for many years.
I have an idea which is above my pay grade.
Using the same operational techniques I have been using the generic thermostat to measure voltages and current on my smart energy management system.
Press a start button (Heater On) set the Voltage (temp) to 14.4 and the charger turns on and when voltage reaches 14.4 turns off. Brilliant.
Except I cannot change the word Heat or cool to voltage mins and max etc.
This could be for anything Voltage, wind speed, watts, air quality - anything.
So with a very simple adjustment to the generic thermostat allowing the user to from a drop down box or just text can change the name of form (Heat or Cool to Voltage or power etc.)
Just an idea. Love it the generic thermostat looks awesome inside my battery HA GUI. thank you.

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

### Version

2023.10.1

### Additional information

Happy to help test and communicate better my idea.
cjshayes@gmail.com

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
