### ISSUE TITLE
Bond Local Access Token now in APP

### ISSUE THREAD

**Issue by girkers** [home-assistant/home-assistant.github.io#29286]
### Feedback

I have just finished setting up a Bond Bridge Pro and the access token is now accessible from within the app. To get the token:

1. Open App
2. Open your Bridge
3. Open Advanced
4. Local Token is what you are after.

Perhaps these instructions could be added to the Pre-requisite instructions for the intergration.

Cheers

### URL

https://www.home-assistant.io/integrations/bond/

### Version

2023.10.1

**Comment by bdraco** [comment]
The docs can be edited via this link: https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/bond.markdown
