### ISSUE TITLE
User

### ISSUE THREAD

**Issue by djsyl** [home-assistant/home-assistant.github.io#29295]
### Feedback

hello,
i like 
user_connect
user_disconnect
if you can add this
thank

### URL

https://www.home-assistant.io/docs/configuration/events/

### Version

2023.10.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
