### ISSUE TITLE
Better instructions on how to set up please.

### ISSUE THREAD

**Issue by MortyFleem** [home-assistant/home-assistant.github.io#29308]
### Feedback

That is all, thank you.
Would save newbs so much headache to have 3 lines of steps to get this thing up and running,

### URL

https://www.home-assistant.io/integrations/worldclock/

### Version

2023.10.1

**Comment by reedy** [comment]
> Would save newbs so much headache to have 3 lines of steps to get this thing up and running,

What sort of steps? What isn't currently in https://www.home-assistant.io/integrations/worldclock/#configuration ?

**Comment by frenck** [comment]
This is fixed by #33702
