### ISSUE TITLE
Air Quality Monitor

### ISSUE THREAD

**Issue by swaxxiii** [home-assistant/home-assistant.github.io#29306]
### Feedback

I would be nice if you supported your Air Quality Monitor instead of just the lower-end Air Quality Lite.

### URL

https://www.home-assistant.io/integrations/qingping/

### Version

2023.10.1

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
