### ISSUE TITLE
Outdoor meter not recognized

### ISSUE THREAD

**Issue by fontainechristophe** [home-assistant/home-assistant.github.io#29301]
### Feedback

I have added the Switchbot Cloud integration. This works.
I have only one Switchbot device for the moment, the Outdoor Meter. It is not yet recognized in the integration.
Is it going to happen in the future?
Thank you

### URL

https://www.home-assistant.io/integrations/switchbot_cloud/

### Version

2023.10.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
