### ISSUE TITLE
if you want annual rain from your ambient weather station

### ISSUE THREAD

**Issue by timlitw** [home-assistant/home-assistant.github.io#29312]
### Feedback

My ambient weather station does not provide annual rain,
to get this
add a utility meter
in the utility meter settings set the input sensor to the daily rain sensor from your ambient weather station
name it ambient annual rain or something to match the other rain sensors
now you can add annual rain to your dashboard or automation as it will get updated and store the value 

### URL

https://www.home-assistant.io/integrations/ambient_station/

### Version

2023.10.1

**Comment by timlitw** [comment]
I forgot to say - no defect with the integrations - but it might be nice to say this on the description page - I tried many other ways to do this until I figured this out.

**Comment by bachya** [comment]
Thanks for sharing your feedback. This is a forum for submitting issues with Home Assistant itself. Contributions to our documentation are always welcome: https://developers.home-assistant.io/docs/documenting/
