### ISSUE TITLE
Wrong Link (URI Fragment)

### ISSUE THREAD

**Issue by jannemannX** [home-assistant/home-assistant.github.io#29315]
### Feedback

The Link to Manual Setup under Troubleshooting links to https://www.home-assistant.io/integrations/google_assistant#manual-setup instead of https://www.home-assistant.io/integrations/google_assistant#manual-setup-if-you-dont-have-home-assistant-cloud

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2023.10.1

**Comment by FletcherAU** [comment]
Good catch @jannemannX :)
