### ISSUE TITLE
Error when adding integration

### ISSUE THREAD

**Issue by sgreenstein1970** [home-assistant/home-assistant.github.io#29320]
### Feedback

Getting error trying to add the integration in the 10.1 release 

- I Click on add integration devices and integrations section and select roborock
- I enter my email and copy and paste the integration code.
- when I cllick on submit I get an "Unexpected error message"

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.10.1

**Comment by Lash-L** [comment]
You should open this in the homeassistant/core repository instead.

check your logs and look at the open issues there as well, this is more than likely one of the others such as the rriot issue with dacite/govee or timeout issues.

**Comment by Lash-L** [comment]
@home-assistant close
