### ISSUE TITLE
Server changengrowatt

### ISSUE THREAD

**Issue by Willianvanpanhuis** [home-assistant/home-assistant.github.io#29327]
### Feedback

My Growatt integration worked until august, then the data stopped showing in my Homeassistant Dashboard.
I removed the integration and tried to login again, but the server-api.growatt.com website is no longer accessible.

I'm not sure where the add-on is trying to login, but when I login to https://server.growatt.com in my browser with the exact same credentials, the login is successful.

The other two options don't work for me as I have not installed my PV setup on those servers. (they seem to be for other continents)

![image](https://github.com/home-assistant/home-assistant.io/assets/129110463/c6b56c44-8aba-461f-8a2e-640333eb7544)

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.10.2

**Comment by frenck** [comment]
Hi there @Willianvanpanhuis 👋 ,

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by muppet3000** [comment]
If it's any help @Willianvanpanhuis this is a duplicate/mis-location of: https://github.com/home-assistant/core/issues/100874
