### ISSUE TITLE
No instructions for Shelly integration

### ISSUE THREAD

**Issue by montekay1** [home-assistant/home-assistant.github.io#29321]
### Feedback

Go to [Settings > Devices & Services](https://my.home-assistant.io/redirect/integrations).
In the bottom right corner, select the [Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=shelly) button.
From the list, select Shelly.

**Follow the instructions on screen to complete the setup.**

There are no instructions on the screen, it just ask for, "Host".   

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2023.10.2

**Comment by bieniu** [comment]
> There are no instructions on the screen, it just ask for, "Host".

If config flow asks for `host` you have to provide a `host`, what additional instructions do you need?

**Comment by dannytsang** [comment]
@montekay1 it's the network address to your Shelly. This is usually the IP address or hostname. If you have the Shelly app, it will be on the **device** > **Settings** > **Device information**
