### ISSUE TITLE
Precipitation now showing

### ISSUE THREAD

**Issue by mikeym2m** [home-assistant/home-assistant.github.io#29349]
### Feedback

Precipitation for neither of 2 sensors is showing. Precipitation type and intensity are showing correctly. The precipitation sensor are both showing correctly just no values. 

### URL

https://www.home-assistant.io/integrations/weatherflow/

### Version

2023.10.3

**Comment by mikeym2m** [comment]
Should be ":Precipitation NOT showing. My bad!

**Comment by frenck** [comment]
Hi there @mikeym2m 👋 

It seems like you wanted to report an issue with a Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with our documentation here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by mikeym2m** [comment]
Thank you and sorry about reporting in the wrong place. MikeyM
