### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by JoeStoner49** [home-assistant/home-assistant.github.io#29351]
### Feedback

I'm deserting MacOSX and moving to Linux Fedora and a Murena Fairphone 5 /e/OS.
Will your system run on them?
ATB
Joe

### URL

https://www.home-assistant.io/help/

### Version

2023.10.3

**Comment by frenck** [comment]
Not sure which part you mean. That said, it seems like you are in need of support, however, we use GitHub for tracking issues.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
