### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by adam5532** [home-assistant/home-assistant.github.io#29355]
### Feedback

In step #7, "set up" is misspelled. It is one word when used as a noun. Otherwise, as a compound verb or past participle (like in step #7 here), it should be two words.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2023.10.3

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @adam5532 :+1: 

Not sure if you've seen it. There is an edit functionality on the website. When you know the solution, you don't have to file an issue. You can just go and fix it yourself if you like.

![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/ee38569d-83e5-4bd1-a371-f79635b37eae)

The **Edit** button is located on the bottom of the page.
