### ISSUE TITLE
Change password functionality

### ISSUE THREAD

**Issue by bromnl** [home-assistant/home-assistant.github.io#29357]
### Feedback

Please provide a way to change the userid and/or password that is used to connect to the growatt server.

I had to reset the password because the account was locked out. I lost the password I had used before.
I do not want to make a met integration.

If there is a way to change the password please let me know.

Best regards Rob

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.10.3

**Comment by joekob** [comment]
Totally agree to @bromnl and suggest to also include the URL in a potential configuration functionality.
Quick workaround might be to change the credentials in /config/.storage/core.config_entries

**Comment by dannytsang** [comment]
Your feedback has come to the documentation part of the project. Please raise this in **New Issue** > **Feature Request**.
