### ISSUE TITLE
Clarification - Tesla Powerwall

### ISSUE THREAD

**Issue by ejbatts** [home-assistant/home-assistant.github.io#29352]
### Feedback

For clarification, the sensors provide data for each Powerwall Gateway. They do not provide data for each Powerwall battery where multiple batteries are connected to a single gateway.

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2023.10.3

### Additional information

I have submitted a feature request to expose extra data for each Powerwall Battery in a multiple battery scenario. If this data is exposed then the documentation would be less ambiguous.

**Comment by purcell-lab** [comment]
> submitted a feature request to expose extra data for each Powerwall Battery in a multiple battery scenario.

Can you include a link to your feature request?

**Comment by purcell-lab** [comment]
With the 2024.2 release this integration now reports on each battery individually as well as the combined view from the gateway.

I believe this issue can be closed as the documentation correctly covers the powerwall gateway sensors and each powerwall battery sensors.
