### ISSUE TITLE
Install Home Assistant Core: libtiff5 not available on Bookworm

### ISSUE THREAD

**Issue by introt** [home-assistant/home-assistant.github.io#29359]
### Feedback

The snippet in `source/_includes/installation/core.md` lists the package `libtiff5` which is no longer available on Debian(-based) systems since Bookworm. Substituting it with `libtiff5-dev` containing the static version of the library seems to let the installation continue, though it is unclear to me what would fail without it.

Since older Debian releases don't ship the required Python version, it feels appropriate to update the instruction, regardless of the installation method being advanced - besides, the `-dev` package is present on both Buster and Bullseye.

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

2023.10.3

### Additional information

https://packages.debian.org/search?keywords=libtiff5

I also hit #95192 prior to getting HASS running.

**Comment by thijstriemstra** [comment]
this can closed i think, it now lists 'libtiff6' instead.
