### ISSUE TITLE
Integration Setup for Slack Notifier

### ISSUE THREAD

**Issue by myanaros** [home-assistant/home-assistant.github.io#29368]
### Feedback

It would be helpful if a **note** was added to remind users to ensure their Bot is added to a private channel (using /invite in the private slack channel) in case they are trying to notify to a private channel. 

I was able to determine this was my issue by looking at the debug logs when trying to run the test script provided in the docs and seeing 

```
ERROR (MainThread) [homeassistant.components.slack.notify] There was a Slack API error while sending to homeassistant: SlackApiError("The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'channel_not_found'}")
```

I inferred that my bot user has not been added since it could not find the channel, since it is private. Took me a little bit to realize that was the issue, could be helpful to point this out to newcomers or seasoned users that haven't had to reset up their slack integration in a while.

### URL

https://www.home-assistant.io/integrations/slack/

### Version

2023.10.3

**Comment by FletcherAU** [comment]
This seems like it would be covered by the line:
> Ensure that the bot user is added to the channel in which you want it to post. In Slack, tag the bot user in a message, then add it to the channel.

Would a screenshot like this make it a bit clearer?
![image](https://github.com/home-assistant/home-assistant.io/assets/20990280/358cce72-20a9-46e0-89a0-1ef4a6ee162c)
