### ISSUE TITLE
rtsp CS-EB3

### ISSUE THREAD

**Issue by jebeke65** [home-assistant/home-assistant.github.io#29376]
### Feedback

When following the process to enable RTSP, the camera is not detected (although everything else is working, both on the ezviz app as on home assistant). Other ways to enable RTSP on the CS-EB3 ?

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2023.10.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
