### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by stevegroom** [home-assistant/home-assistant.github.io#29371]
### Feedback

Hello, 
I have an issue with sensors becoming unavailable - https://github.com/home-assistant/core/issues/89311. 
That issue suggests setting zippy_config > ezsp_policies > TRUST_CENTER_POLICY. 
This setting does not appear in your documentation.

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2023.10.3

**Comment by Hedda** [comment]
@TheJulianJES @MattWestb Do you guys have more information about this and maybe care to add it to ZHA and zigpy docs?

**Comment by MattWestb** [comment]
I have 2 of this and they is going the black box for bad Zigbee devices then i getting 2 better light sensors.
Its no need changing the security policy only having many routers so they can jumping around  and finding one very bad parent and and then they is not leaving the network.
Our @puddly have sniffing the devices in HUE hub and they is doing the same but the hub is not complaining.
For the second is not recommended changing the security policy then its braking the network and need reforming it every time and can also getting more strange problems that the user is not knowing how to manager. Look in the Silabs papers of the host protocol (EZSP) and all is in it.

**Comment by Hedda** [comment]
Can this be closed?

**Comment by puddly** [comment]
Advanced configuration for EmberZNet internals is out of scope for Home Assistant and will not be added to the ZHA documentation.

You can find what these parameters do in the Gecko SDK source code or the relevant Silicon Labs document (e.g. UG100).
