### ISSUE TITLE
Can't get custom sentences working

### ISSUE THREAD

**Issue by julia-r** [home-assistant/home-assistant.github.io#29379]
### Feedback

When I put custom intents in my configuration.yaml it is working, but when I put them in a .yaml file in configuration/custom_sentences/[language] the custom intents are not found. When i try to execute them I get "Sorry, I couldn't understand that" from the voice assistant and the Assist Sentences parser returns "No intent matched". I tried restarting HomeAssistant to make sure the files are found. I tried German and English as languages and I checked for typos.
Do I need to include the files somehow with an !include ? Or are they supposed to be found automatically? 

### URL

https://www.home-assistant.io/voice_control/custom_sentences/

### Version

2023.10.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation issue, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
