### ISSUE TITLE
The existence of the add-on menu under anything called "settings" is a lie.

### ISSUE THREAD

**Issue by gundw** [home-assistant/home-assistant.github.io#29383]
### Feedback

I started to watch a tutorial, it said, go to configurations menu.
I found out recently this is moved to settings.
I also don't have settings.
I tried to find add-ons, I was told to press 'c' as that is now the new "intuitive" way to handle this.
"c" also has no settings, no configuration and no add-ons and no store.
Now I find the official documentation on the official site that very clearly states, with diagrams so stupid people like me can also play, that add-ons is under settings.

Bruh, there is no settings. 

Either we are all stupid (by all, I mean the thousands of search results showing the exact same misunderstanding by thousands of other users - there is no configuration, there is no settings, there is no add-on store and the search does not find these terms either so clearly the same idiot designed that) or your devs aren't using the product.

### URL

https://www.home-assistant.io/addons/

### Version

2023.10.3

**Comment by stefanroelofs** [comment]
Or maybe, just maybe the problem lies with you sir. 

In my HA instance I have clearly marked buttons for Settings and Add-ons:
![image](https://github.com/home-assistant/home-assistant.io/assets/37924749/c24ebaf2-7db8-4fce-a34a-2d28ec83bb4d)

Maybe you have the sidebar collapsed, and you only see the cog-wheel icon?

**Comment by gundw** [comment]
![image](https://github.com/home-assistant/home-assistant.io/assets/52160888/55001692-6168-4c13-8f62-f4229fbdae7e)

If only it was just me, if only this could be explained by my stupidity....

![image](https://github.com/home-assistant/home-assistant.io/assets/52160888/d099a08c-877f-4407-8000-1b51906185ce)

Seems like it is by design and to be sure nobody gets confused, a really uniquely different name has been used for this different product so that nobody else gets lost... *sigh*. 94.5k views since October '20.

Thank you for the helpful tip, ma'am.

**Comment by gundw** [comment]
Ok, for all the other people who come here...

I did not fully comprehend the install instructions or installation options.

What I wanted was a Docker install with all the benefits of Docker - portable, lightweight, etc...

This is not possible as some other software is needed, supervisord or something which I have no interest in. I want my platform to be 100% "clean".

For me, it was trivial to setup Virtualbox on Ubuntu and use the VDI deployment which "just worked" and has the features I wanted and is also somewhat portable in that I can just relocate the VDI when I want to. Not as easily as Docker but still, possible.

This is an easy tutorial for installing a headless Virtualbox on Ubuntu:

https://aardvark.systems/2023/10/02/create-a-headless-virtualbox-service-on-ubuntu/

The next step is to download the VDI, unzip it, place it somewhere vbox user has RW and it "just works".

Thank you all for the time, sorry for my rant-y headline. I would love to see a 100% docker deployment one day.
