### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by deechte** [home-assistant/home-assistant.github.io#29407]
### Feedback

Hello, excuse me for asking, but does this still work nowadays? I've added the instructed lines to my configuration.yaml, restarted my HA, but no new binary sensor appears. I've also tried specifying the "name" parameter in configuration.yaml, but that doesn't make any sensor with that name appear. 

Do I need to copy the files in this repo manually maybe?

Thank you dearly for your help!

### URL

https://www.home-assistant.io/integrations/hikvision/

### Version

2023.10.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
