### ISSUE TITLE
FAQ text is a bit misleading 

### ISSUE THREAD

**Issue by adejordan1972** [home-assistant/home-assistant.github.io#29405]
### Feedback

“If you can add your device to the Roborock app - it is supported. However, some older vacuums like the Roborock S5 must be connected using the Mi Home app and can be set up in Home Assistant through the [Xiaomi Miio](https://www.home-assistant.io/integrations/xiaomi_miio/) integration.”

I use an S5 Max through the Roborock app, but this doesn’t support it - you might want to reword that first line as it obviously isn’t correct -  it may save a lot of unnecessary frustration and searching.

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.10.3

**Comment by Lash-L** [comment]
If you use the device in the Roborock app - then it is supported by this integration. If for some reason it is not setting up - then you are having a problem and you should open an issue on ha core. This line is accurate.

**Comment by Lash-L** [comment]
Closing this issue as there has not been a response in a while and the problem description is not accurate.

**Comment by Lash-L** [comment]
@home-assistant close
