### ISSUE TITLE
Can't do the tutorial

### ISSUE THREAD

**Issue by jaharkema** [home-assistant/home-assistant.github.io#29417]
### Feedback

> 1: Go to [Settings > Add-ons > openWakeWord](https://my.home-assistant.io/redirect/supervisor_addon?addon=openwakeword) and select Install.

What does Home Assistant say?

> This redirect is not supported by your Home Assistant installation. It needs either the Home Assistant Operating System or Home Assistant Supervised installation method.

This could have been mentioned in the 'Required materials'.  
I'll one again have to wait and see if something will be hacked together for the Docker users.

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2023.10.3

**Comment by c0ffeeca7** [comment]
Thank you for pointing this out, @jaharkema.
I've added a note to the Prerequisites section.
