### ISSUE TITLE
GitHub "Report a vulnerability" includes CVSS calculator

### ISSUE THREAD

**Issue by reedy** [home-assistant/home-assistant.github.io#29422]
### Feedback

Following up #29291

![Screenshot 2023-10-19 at 12 19 50](https://github.com/home-assistant/home-assistant.io/assets/67615/d5abebac-d84f-4d99-b187-b484bc563fd0)

We probably don't need to link to an external/third party CVSS calc...

### URL

https://www.home-assistant.io/security/

**Comment by frenck** [comment]
> We probably don't need to link to an external/third party CVSS calc...

It is better to link to the source. We are happy with the current linked information and documentation. Especially considering the GitHub one isn't fully covering everything.

../Frenck
