### ISSUE TITLE
Fritz Dect 302 - Display not updated

### ISSUE THREAD

**Issue by shreblov** [home-assistant/home-assistant.github.io#29447]
### Feedback

When I set a new target temperature value from Home Assistant, the display on the Fritz Dect 302 shows the old value. But the temperature is set correctly. E.g. old temperature as displayed 18°, new temperature set to 20°, display still shows 18°. If I press the + button once on the device, displayed temperature is 20.5° then. So the temperature was changed on the device.
If I change the temperature from the FRITZ!Box, changed value is displayed immediately.

### URL

https://www.home-assistant.io/integrations/fritzbox/

### Version

2023.10.3

**Comment by mib1185** [comment]
Hi @shreblov 
you have reported a feedback to the documentation, but not the integration.
Nevertheless, all battery powered DECT devices are not permanent online (_to save energy_), they wake-up every 15 minutes and "ask" the FritzBox for updates. With pushing some button on the FritzDECT, it wake-up immediately and checks for updates.

**Comment by shreblov** [comment]
Thanks for the response. As mentioned, when I change the temperature from the Fritzbox the update is done immediately. And when from Home Assistant with the Integration there is never an update.

Best regards
Reiner

**Comment by mib1185** [comment]
mhhh ... than please open a new issue report to the core repository https://github.com/home-assistant/core/issues and provide as much details as possible
