### ISSUE TITLE
Growatt integration can't login

### ISSUE THREAD

**Issue by opolczer** [home-assistant/home-assistant.github.io#29458]
### Feedback

Hello

Int the growatt server list not found my registered site: https://server.growatt.com
Only these below:
![image](https://github.com/home-assistant/home-assistant.io/assets/17346560/1bdec289-d437-4cbf-ad6f-06a885bf56b4)

Can you check it?

Thanks,
Daniel

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.10.3

**Comment by frenck** [comment]
Hi there @opolczer 👋 

It seems like you wanted to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integration here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
