### ISSUE TITLE
Example polling automation incorrect

### ISSUE THREAD

**Issue by atlflyer** [home-assistant/home-assistant.github.io#29457]
### Feedback

This page shows an example of disabling the automatic polling for the speedtest.com integration and replacing it with the automation, but the example automation shows using the `homeassistant.update_entity` service to update an entity in the `weather` domain. Users who want to follow this example are unable to know what the correct entity is to call the service on in order to trigger a speedtest on demand.

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2023.10.3

**Comment by dannytsang** [comment]
@atlflyer the documentation is reusing a common page and not specific to speedtest.net integration. You can see this on the [Waze integration page](https://www.home-assistant.io/integrations/waze_travel_time/) as well.

@c0ffeeca7 what do you think about removing the **Example in YAML** bit in *define_custom_polling.md*?

**Comment by c0ffeeca7** [comment]
Good point.
Thank you for bringing this up, @atlflyer.
Thank you for proposing a solution, @dannytsang.
