### ISSUE TITLE
Request to add another Growatt server URL

### ISSUE THREAD

**Issue by jelicano** [home-assistant/home-assistant.github.io#29468]
### Feedback

adding Growatt information using https://server-api.growatt.com/ no longer works. Perhaps add https://server.growatt.com as another option 

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.10.3

### Additional information

adding Growatt information using https://server-api.growatt.com/ no longer works. Perhaps add https://server.growatt.com as another option

**Comment by messagedj** [comment]
I just wanted to add the same suggestion! I can't use the integration now as neither of the options work for me.  

https://server.growatt.com/ does allow me login.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by messagedj** [comment]
Hey Freck, 

This IS an issue. 
The API from https://server-api.growatt.com/ is no longer working for European users.

**Comment by frenck** [comment]
Cool, but this is the documentation issue tracker. There is no amount of documentation we adjust to "fix" this on this end.

**Comment by messagedj** [comment]
ahhh.. okay.. sorry.. misunderstood that... take care m8!

**Comment by muppet3000** [comment]
This is actually a duplicate of https://github.com/home-assistant/core/issues/100874
