### ISSUE TITLE
training colab is currently broken

### ISSUE THREAD

**Issue by ThreepE0** [home-assistant/home-assistant.github.io#29464]
### Feedback

Colab errors out because of openwakeword requirements.  I've made some edits that appear to work, here is a link to my edited colab.  Essentially openwakeword has a requirement of torch version that breaks compatibility with the installed version of pytorchvision.  Installing the original intended versions of both don't work.  My fix was to manually remove the specified versions of pytorch and associated packages from setup.py.  There was also a locale issue that I addressed in the first block

https://colab.research.google.com/drive/1d0Q22-TX7i0IAQ4n7nuB0fGDclQEHpl1

I know this isn't a home-assistant issue, but sharing quickly before I forget.  Will research the proper venue for reporting the issue.

EDIT:  I'm not sure who owns the colab, so not sure where to report.

### URL

https://www.home-assistant.io/voice_control/create_wake_word/

### Version

2023.10.4

**Comment by synesthesiam** [comment]
Let's track this over in the openWakeWord repo
