### ISSUE TITLE
MyQ Gateway Not working

### ISSUE THREAD

**Issue by bjr6544** [home-assistant/home-assistant.github.io#29470]
### Feedback

This looks to not be able to load correctly with no entities coming in. And has been broken for many iterations of HA updates. 

### URL

https://www.home-assistant.io/integrations/myq/

### Version

2023.10.4

**Comment by brenletheninja** [comment]
it's not working for me either. I tried to delete, re-install, but it doesn't authenticate now

**Comment by spock99** [comment]
Known issue MyQ Chamberlain block API access and will no longer support API access to their product. Basicly home assistant should remove this integration as it not going work any more.

**Comment by tadaschi** [comment]
same here, iphone myq app work normally. already try to change password and no luck.
unfortunately i can see many home management software, no mention of home assistant

**Comment by frenck** [comment]
For more information see: <https://www.home-assistant.io/blog/2023/11/06/removal-of-myq-integration/>
