### ISSUE TITLE
Use an Ubuntu Live USB stick to install HAOS on a dedicated x86-64 machine

### ISSUE THREAD

**Issue by michaelsidenius** [home-assistant/home-assistant.github.io#29480]
### Feedback

I have briefly descibed a very simple, no extra HW, pure GUI method to install HAOS on a dedicated x86-64 PC type machine here: https://community.home-assistant.io/t/installing-haos-on-a-dedicated-x86-64-pc/443011/11?u=michaelsidenius
and further augmented the descriptiopn here:
https://community.home-assistant.io/t/how-to-install-home-assistant-on-generic-x86-64-using-live-os/567210/5?u=michaelsidenius
This method further has the benefit of testing your HW (CPU, RAM, disk, network, USB, etc) before your install HAOS. 
I believe this could be beneficial for many others with a spare PC lying around, or as me, simply needing some more beefy metal to run HAOS than a Raspi with an SD card. 
I hope it can be included in the official HAOS x86-64 install guide.
Thanks for all the effort!

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2023.10.5

**Comment by c0ffeeca7** [comment]
Thank you for reaching out and providing this procedure, @michaelsidenius :+1: 
I saw this issue a bit late. Closing this as I think it has been covered in the meantime by https://github.com/home-assistant/home-assistant.io/pull/29997
