### ISSUE TITLE
Logbook card for entity-filer

### ISSUE THREAD

**Issue by jshep321** [home-assistant/home-assistant.github.io#29485]
### Feedback

The doc mentions the card types shown in the examples, but doesn't seem to work for logbook.  I was hoping to filter a log of sensors to include the event (true), but exclude clearing of the event (false).  

Is that feasible or perhaps a feature request?

### URL

https://www.home-assistant.io/dashboards/entity-filter/

### Version

2023.10.5

**Comment by dannytsang** [comment]
It's not possible with the built in logbook card in Home Assistant. However, you maybe able to achieve this using the [Logbook card available in HACS](https://github.com/royto/logbook-card). Installing and getting this setup is not part of the Home Assistant and beyond the scope documentation.
