### ISSUE TITLE
will the functionality be expanded

### ISSUE THREAD

**Issue by tonyfitzs** [home-assistant/home-assistant.github.io#29494]
### Feedback

Hi, you have done a brillient job with this, but for me the functionality is a little limited, so I am wondering if there are plans to increase functionality in the future, for example add a binary sensor for the light (that way I could use the lights in the spa to turn on other lights when I am in the spa) it would also be great to be able to turn the pumps on and off, because I can do that in the Balboa app and would like to be able to do that from the one place as I do with all my other integrations. i.e use the Home Assitant app. 

### URL

https://www.home-assistant.io/integrations/balboa/

### Version

2023.10.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
