### ISSUE TITLE
Tasmota feedback: How to enable Status sensors?

### ISSUE THREAD

**Issue by jtagcat** [home-assistant/home-assistant.github.io#29492]
### Feedback

> Please note all the Status Sensors are disabled by default.

How do you enable?

### URL

https://www.home-assistant.io/integrations/tasmota/

### Version

2023.10.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by jtagcat** [comment]
Was not seeking for support. Rather this is meh docs if you state something and don't provide a pointer.
