### ISSUE TITLE
HA Install using RPI 4 B immage

### ISSUE THREAD

**Issue by PeterSek** [home-assistant/home-assistant.github.io#29508]
### Feedback

I followed this install https://www.home-assistant.io/installation/raspberrypi
using 1st option on above page 'Install Home Assistant Operating System'

however it is not clear what installation method above represents looking at this page
Above implies Operating System Install
But after installation i got a feeling the install is Docker Installation (not what I wanted)
https://www.home-assistant.io/installation#compare-installation-methods

hope thi smakes sense
Peter

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.10.5

**Comment by c0ffeeca7** [comment]
Hi there, @PeterSek 
Do I understant correctly, you followed the procedure step-by-step, and selected Home Assistant Operating system in this step here
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/16627ab4-e557-40a9-9d21-12011badd7ce)

You ended it here, with starting up your Raspberry Pi, and continued with onboarding?
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/130452a9-c5d4-4e23-afa2-16c7a047332a)

**Comment by c0ffeeca7** [comment]
On a different note: there is no need to publish your phone number or email address. We can continue this conversation right here.

**Comment by PeterSek** [comment]
Thanks for your response
Yes I followed the instructions as per page in your response
what I am trying to understand is what type install is this? 
Install options are described in a link 'compare installation methods'. The install page does not make this very clear which one it is
-OS, Container, Core, Supervised
I am guessing it is Docker based on how this install auto boots into HA > prompt, I did not have LAN cable so it was bit of challenge connecting to my LAN using HA> command prompt

Yeah, my email and mobile got included by accident, removed now, thanks for pointing that
Peter

**Comment by PeterSek** [comment]
after install i started my RPI with monitor, kbd, mouse. BTW at the time I did not have LAN cable 
RPI booted to HA> prompt rather that Raspberry Desktop. I tried at command prompt HA>exit, quite etc but it always re-started to HA>
Of this is OS install rhather than Docker, how can I get to RPI Prompt or RPI Desktop
thank you
Peter

**Comment by agners** [comment]
Home Assistant OS is not the same as Raspberry Pi OS, which would give you a desktop. It is a operating system dedicated to run Home Assistant, and uses containers under the hood (for technical details, see also the readme in the operating system GitHub repository at https://github.com/home-assistant/operating-system/).

Since Home Assistant is mostly controlled through the web interface, the console really only is meant as a debugging environment.

If you want to avoid using containers at all, the only option is using the [Home Assistant Core](https://www.home-assistant.io/installation/linux#install-home-assistant-core) installation option a Python virtual environment installation. But I recommend strongly against that, unless you have the necessary expertise and time to maintain such an environment.

**Comment by agners** [comment]
> however it is not clear what installation method above represents looking at this page

In the end, using Docker/containers is an implementation detail of the operating system. Why do you think this is relevant/what would you expect exactly? (from the documentation, to make it clear)

**Comment by PeterSek** [comment]
Thank you for detailed explanation
My thank you goes to you and others who maintain and support this great product, Home Assistant

To answer your question, Perhaps adding some of the details you mention above to docs would make it more clear
Egt 'note to advanced users...'. Of course changes depend how many enquiries do you get in this section of docs...
I am happy to help or review updates if that helps, I do have some IT background

PS I also struggled a bit setting up wifi using HA> command. happy to provide feedback, via new github post?!

**Comment by PeterSek** [comment]
https://www.home-assistant.io/installation#compare-installation-methods
perhaps HA-OS instead of just OS on the above page

**Comment by PeterSek** [comment]
thank you, the update to docs looks good
Peter

**Comment by c0ffeeca7** [comment]
Thank you for the suggestion, @PeterSek
