### ISSUE TITLE
Integration does Not work

### ISSUE THREAD

**Issue by paddy-superbrain** [home-assistant/home-assistant.github.io#29511]
### Feedback

This Integration does not work correctly. By setting the hostname and password you only get an error message. Are there additional settings in the inverter to set?

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2023.10.5

**Comment by frenck** [comment]
Hi there @paddy-superbrain 👋 

It seems like you want to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
