### ISSUE TITLE
The Discovery component page does not list Harmony Hub Remote as a discoverable component

### ISSUE THREAD

**Issue by oadevs** [home-assistant/home-assistant.github.io#2952]
This is my first time ever reporting an issue on GitHub, so bear with me if I am not doing it right.

I just noticed that my HA (v 0.48.1) automatically discovered my Harmony Hub. When checking on the [Harmony Hub Component Page](https://home-assistant.io/components/remote.harmony/), it says "The preferred way to setup the Harmony remote is by enabling the discovery component.".

Then when on the [Discovery](https://home-assistant.io/components/discovery/) page, I can't find any information about the Harmony Hub Remote component.

I know this is not a big deal, but just in case, to save time from others next time when researching this topic.

**Comment by Landrash** [comment]
Closing with #3079
