### ISSUE TITLE
YouTube Integration Configuration Instructions Outdated

### ISSUE THREAD

**Issue by DaveAuld** [home-assistant/home-assistant.github.io#29521]
### Feedback

The YouTube Integration section **"Generate Client ID and Client Secret"** setup steps do not match how Google have changed the Developer console layout for this setup step.

This makes it confusing to know what steps to take to setup the necessary keys, as the page structure, steps, are different.

### URL

https://www.home-assistant.io/integrations/youtube/

**Comment by DaveAuld** [comment]
Sorry, I should have said it is Step 11 that needs amendment.
![image](https://github.com/home-assistant/home-assistant.io/assets/4674288/1412ac24-bbc8-42f2-a6c8-ab6bdd90b46a)

There is an addition tab add for "Test Users" this should also be skipped by just hitting **"Save and Continue"**.

**Comment by joostlek** [comment]
cc @tkdrob

Right, guess I'll need to find some time to resetup stuff and write new steps

**Comment by FletcherAU** [comment]
Looks like this was corrected in #29539.

**Comment by joostlek** [comment]
Ah yes, there has been some work done on the google auth setup to also make it reusable with the other google integrations. I think this can be closed now
