### ISSUE TITLE
Wolflink: Possible enhancements?

### ISSUE THREAD

**Issue by AnathosN** [home-assistant/home-assistant.github.io#29529]
### Feedback

Dear all,

first of all thank you for this very useful integration, which allows to track the status of the Wolf heating systems, a CHA heatpump in my case, in Home Assistant.

As this uses the cloud functionality I'd like to ask, if it is possible to add the active components, which the cloud functionality should allow, e.g. setting the water temperatur or activation of the 1h Force Load. These are available in the Wolf Smart Set app, but not in the integration, where I can only include the passive sensors.

Thanks a lot.

BR,
Anathos

### URL

https://www.home-assistant.io/integrations/wolflink/

### Version

2023.10.5

**Comment by FelixArndt** [comment]
+1
Would love that feature too!

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
