### ISSUE TITLE
Generic thermostat schedule 

### ISSUE THREAD

**Issue by pegaz988** [home-assistant/home-assistant.github.io#29533]
### Feedback

For improvement of generic thermostat could be add time schedule to setting temperature due to time, day etc.

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

### Version

2023.10.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
