### ISSUE TITLE
Device is not supported

### ISSUE THREAD

**Issue by BjoernKoe** [home-assistant/home-assistant.github.io#29530]
### Feedback

Unfortunately I was not able to connect the vodafone station into my HA.
There is always the error : "The device model is currently not supported."
Since I have the latest wifi 6 router which is a listed supported device on your website I guess its a bug.

### URL

https://www.home-assistant.io/integrations/vodafone_station/

### Version

2023.10.5

**Comment by chemelli74** [comment]
hi @BjoernKoe, can you please share model and firmware of your Vodafone Station ?

**Comment by BjoernKoe** [comment]
Hi @chemelli74 thanks for the quick response.
The model is: CGA6444VF
The firmware is: 19.3B70-1.2.49

**Comment by chemelli74** [comment]
Hi, browsing internet I can clearly identify the model as a Technicolor router. Those are not supported so far in the integration.

**Comment by BjoernKoe** [comment]
Ah okay good to know. I thought since "Vodafone WiFi 6 Station" is mentioned as a tested device - mine is included. 
Looking forward when my router is included aswell. Thanks so far
