### ISSUE TITLE
aggiotnamento

### ISSUE THREAD

**Issue by EdisonACDC** [home-assistant/home-assistant.github.io#29535]
### Feedback

le automazioni non sono più disponibili

### URL

https://www.home-assistant.io/docs/automation/

### Version

2023.10.5

### Additional information

le automazioni non funzionano e non sono più visibili

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). Our default language within the community is English.

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
