### ISSUE TITLE
Utilization

### ISSUE THREAD

**Issue by cfogarty1964** [home-assistant/home-assistant.github.io#29544]
### Feedback

I have the tuya smartplugs wiith energy monitoring, and HA sees these sensors, but the entity is not available. Is there a way to pull this information into HA?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.10.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
