### ISSUE TITLE
Feature Request - Proximity sensor / Face ID / CAM / Automation / Screensaver 

### ISSUE THREAD

**Issue by Paddy3911** [home-assistant/home-assistant.github.io#29549]
### Feedback

Please add this Features:

- Awake Device if CAM detect a known face or proximity 
- Awake Device with Automation from HA
- Screensaver (Clock or else)
- Unlock with PIN

### URL

https://www.home-assistant.io/integrations/mobile_app/

### Version

2023.10.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
