### ISSUE TITLE
Great start.  Looks very nice

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/home-assistant.github.io#29548]
### Feedback

It would be nice if it would allow the same features as Google tasks.  I.e a time and date that the task is due. Also when setting up a new task the same time and date and setup recurring tasks.

### URL

https://www.home-assistant.io/integrations/google_tasks/

### Version

2023.11.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
