### ISSUE TITLE
Please explain how to enable this in docker environment

### ISSUE THREAD

**Issue by emembeka** [home-assistant/home-assistant.github.io#29542]
### Feedback

The document says:

> Supervisor integration allows you to monitor and control Supervisor add-ons and operating system from Home Assistant. This integration is already installed if you run Home Assistant OS or Supervised.

but it is not explained how to enable it when using the dockered installation.

When trying to enable the inegration from the my installation, an errormessage 

>  You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information. 

The documentation link leads to this document, but the information is missing. 

All forum threads concerning this issue I found, did not enlighten me :-(

Thanks a lot
MM

### URL

https://www.home-assistant.io/integrations/hassio/

### Version

2023.10.5

### Additional information

![Bildschirmfoto vom 2023-10-25 19-29-43](https://github.com/home-assistant/home-assistant.io/assets/21238197/59790d5f-a2e6-4a15-b838-abee3d0c6959)

**Comment by dannytsang** [comment]
Supervisor is not available on container install. Please see this [chart](https://www.home-assistant.io/installation/#compare-installation-methods).

**Comment by emembeka** [comment]
:-( OK, in this case I think, this fact should be mentioned in the [documentation](https://www.home-assistant.io/integrations/hassio/) or even better users should not be able to select the `hassio` integration in their installation.
