### ISSUE TITLE
Fachmann-Ebene

### ISSUE THREAD

**Issue by Hafenmeister31** [home-assistant/home-assistant.github.io#29545]
### Feedback

Hi there, the plugin is very nice, but it misses a lot of potential cause the access to "Fachmann" is not possible which would provide many more entities and features. Is there any plan to provide access to it with a future update ?

### URL

https://www.home-assistant.io/integrations/wolflink/

### Version

2023.10.5

**Comment by FelixArndt** [comment]
+1
That would be an awesome addition!

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
