### ISSUE TITLE
On the CLA form, the United Kingdom option only includes English regions.

### ISSUE THREAD

**Issue by d0ugal** [home-assistant/home-assistant.github.io#2957]
The quickest, and easiest fix, for this is to change "United Kingdom" to England. Scotland, Wales and Northern Ireland are already included under their own countries.

Usually Scotland (which is where I live, so the only one I can speak for) is included under United Kingdom, but if that isn't present then I would look for Scotland.

I'll propose a fix to rename it to England, which seems easier than merging them all.

**Comment by d0ugal** [comment]
Actually, it might be more tricky than I first thought - if the database, where the result is stored, has United Kingdom entries already? Also, changing to to England would mean it isn't in the correct place but the order seems important for the states/regions...

So, I'm not sure how you would like to fix this?

I hope you are only keeping one form completion, otherwise there will be a couple from me. Sorry. Initially I just chose an English region.

**Comment by Landrash** [comment]
@robbiet480 when possible can you have a look a this?

**Comment by d0ugal** [comment]
FWIW, I would be happy to help - but I need guidance on how you would like to fix it. The technical part is fairly easy if it is just a JavaScript change.

**Comment by robbiet480** [comment]
It is just a Javascript change. Your suggestion to rename to England sounds fine, go ahead and do it at your leisure. Sorry for the response delay, was on vacation.
