### ISSUE TITLE
Changing scene's on the Anna / Jip

### ISSUE THREAD

**Issue by EduardWitteveen** [home-assistant/home-assistant.github.io#29578]
### Feedback

Hello, 

In my office, i want to change the plugwise scene from "Afwezig" to "Aanwezig" based upon the consumption of power.
This way the office will only be heated when somebody is in the office.

In nodered i programmed the logica, but i dont know how to set the value on the Jip. 
There could be a climate.set_preset_mode as mentioned on: https://www.home-assistant.io/integrations/plugwise/ 
I cannot find it on my Jip thermostat.

A - I also see an "schedule" / "schema", is this the same as the "scene" from plugwise?
B - Which values should i use to set to "Afwezig" / "Aanwezig"?
C - Is this usecase possible with a Jip or should i replace it with an Anna? 

### URL

https://www.home-assistant.io/integrations/plugwise/

### Version

2023.10.5

**Comment by bouwew** [comment]
In Developer Tools --> STATES, find the climate-device for the Jip, there is shown what is supported.
![image](https://github.com/home-assistant/home-assistant.io/assets/11290930/ac273cab-1421-4aca-8e2b-79195ebba8af)

Also in the Plugwise App you can find more details, also you can configure the Presets in the App (mainly the temperature setpoint).

When you have a Jip, you have an Adam. You can, as an option, set the Adam to (regulation_mode) `off` when you leave, and turn in back to `heating` when you arrive. But using this option means you will turn the heating off/on for all the connected thermostats.

A: in a schedule you can define, for every day in a week, at what time you want to have which temperature. For instance, 15 degr during night, 18 in the morning, 19 in the late afternoon. Try it in the Plugwise App.
B: Afwezig can be Preset = Away, Aanwezig can be Preset = Home. Or Afwezig is regulation_mode = off Aanwezig is regulation_mode = heating.
C: Yes definitely possible with a Jip.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by bouwew** [comment]
@EduardWitteveen please take your question here: https://community.home-assistant.io/t/plugwise-core-and-custom-component/236250
