### ISSUE TITLE
There is no example for history integration usage

### ISSUE THREAD

**Issue by MikkoUEF** [home-assistant/home-assistant.github.io#29570]
### Feedback

I think the history integration page would need to have a clear example how to use history integration in yaml-code. I have not been able to find any example anywhere else either.
Thanks,
Mikko

### URL

https://www.home-assistant.io/integrations/history/

### Version

2023.10.5

**Comment by j4n-e4t** [comment]
@MikkoUEF I see, the docs for the history integration aren't very detailed. But what do you expect? Isn't `history:` the only config option that's currently available?

**Comment by MikkoUEF** [comment]
> @MikkoUEF I see, the docs for the history integration aren't very detailed. But what do you expect? Isn't `history:` the only config option that's currently available?

@j4n-e4t I was expecting to see similar use example as in history_stats where you define time interval, name and entity to get statistical descriptors for that entity for given time interval. That integration mention that it uses history-integration so I assumed that I would get the corresponding time-series and then use it in rest api call as input vector for ML model in the cloud. It could be that history-integration was not designed to be used like this but I have not found any other integration either for this purpose. So I would like to set up sensor in configuration.yaml and use it to get e.g. 24 last hourly values of energy usage hopefully in json-format with timestamps for each data value.

**Comment by j4n-e4t** [comment]
Ok, now i understand. You can actually use the RESTful API to access the history data of any entity. However, as far as I know, there is no "time-series" feature for the history integration. When I tried out your scenario, I got a huge json object with all state changes of a sensor in HA. I'll give you the curl command I used. Maybe it helps you. 

```bash
curl -X GET \
-H "Authorization: Bearer <YOUR_AUTH_TOKEN>" \
-H "Content-Type: application/json" \
"http://<YOUR_HA_URL>:8123/api/history/period/2023-10-28T00:00:00Z?filter_entity_id=<YOUR_ENTITY_ID>"
```

Another way of getting time series data out of HA would probably be [InfluxDB](https://www.influxdata.com/).

**Comment by frenck** [comment]
> I was expecting to see similar use example as in history_stats where you define time interval, name and entity to get statistical descriptors for that entity for given time interval. 

That is incorrect expectation.

The only option is: `history:`

The documentation page is correct and fully up-to-date.

../Frenck

**Comment by MikkoUEF** [comment]
@j4n-e4t thanks for the curl-code above; I am currently working on it. In more detail, the curl works in command prompt but not as sensor yet. All in all, I still think that the history-integration should have easy to use documented interface for this kind of usage that is more and more common in the world with ML applications. Where should I suggest this more formarly?

**Comment by j4n-e4t** [comment]
I actually found the API documentation for the history endpoint. Here it describes everything, including the curl command. (https://developers.home-assistant.io/docs/api/rest/). Therefore, I wouldn’t suggest a change on the history integration‘s documentation. And regarding the topic of ML and data analysis, isn't this too specific for the general documentation?

**Comment by MikkoUEF** [comment]
Replying your last questions first, I think ML is just an example case and it would be good to have easy way of accessing the history of sensors in general. I have read the page you reference and it is basically a good document about forming the curl-command and that works just fine in the command-prompt. However, wrapping that into sensor is not that easy. I have tried the code below using command-line according to some examples found in some other pages mainly in discussion forum. It does not work i.e. no sensor is created. I know this is easy for experienced users but not for newbie like me. That's why I am after documentation on this issue to save future generations of HA users from the same frustration of trying to put together pieces while a proper and whole usage example is missing.
sensor:
  - platform: command_line
    command: "curl -X GET -H 'Authorization: Bearer <TOKEN>' -H 'Content-Type: application/json' http://homeassistant.local:8123/api/history/period?filter_entity_id=sensor.pnt_quarter_energy_last"
    name: quarterly_energies
    unit_of_measurement: 'kWh'

**Comment by j4n-e4t** [comment]
I'm sorry if I was moving too fast. 😬 I know what it's like to start working with a new technology. I always feel as if I know nothing again. 😅 

So, back to the sensor... Your config looks good so far, but could you explain once more, what exactly this sensor should have as its value? As far as i know, you can't store the entire JSON output, because HA has a limit on how big this value can be. I'm sorry, if I misunderstood you... 😔. 

One more thing, since you have a very specific use case, you might want to start a new discussion in the HA Community forum or ask on their Discord. There, more people that probably know the answer will find that question.

**Comment by MikkoUEF** [comment]
@j4n-e4t Thanks for your kind reply. I am sorry for outputting my frustration here! I know this is not the right place for larger discussion. Concerning the json-values, I would need the state and timestamp which would be last_updated or last_changed. This particular variable with history request is already filtered by creating a sensor that saves the last value for each quarter or hour of a variable that is a counter reset at the end of the cycle, so that there are not that many lines in the database for the last 24 hours.
