### ISSUE TITLE
Instructions do not work

### ISSUE THREAD

**Issue by traviskorth** [home-assistant/home-assistant.github.io#29581]
### Feedback

The instructions in step 13 on this page for adding a Google Calendar integration indicate we have to select "Web Application".  This does not work for adding the integration.  It needs to be "TV and Limited Input".

12. In the left sidebar, select Credentials, then select Create credentials (at the top of the screen), then select OAuth client ID.
13. Set the Application type to Web application and give this credential set a name (like “Home Assistant Credentials”).

### URL

https://www.home-assistant.io/integrations/google/

### Version

2023.10.5

**Comment by allenporter** [comment]
This is addressed in https://github.com/home-assistant/home-assistant.io/pull/29577

**Comment by allenporter** [comment]
I merged that PR, so this should be fixed now. Thank you for the report.
