### ISSUE TITLE
change in formula

### ISSUE THREAD

**Issue by S7Bul** [home-assistant/home-assistant.github.io#29589]
### Feedback

Hi guys,

There has been an update for Energyzero which now uses the following:

Marketprice+21%+€0,0212+€0,1524.

Will there be a change or is this something for users to edit themselves accordingly?
![IMG_20231029_110552](https://github.com/home-assistant/home-assistant.io/assets/143347349/59a95818-d225-488a-b05d-3fd797683121)

Have a nice day.

### URL

https://www.home-assistant.io/integrations/energyzero/

### Version

2023.10.5

**Comment by klaasnicolaas** [comment]
You have to add these values ​​yourself, the integration only gives the basic price including VAT
