### ISSUE TITLE
example format incorrect

### ISSUE THREAD

**Issue by koos147** [home-assistant/home-assistant.github.io#29599]
### Feedback

the example isn't complete. 
can't simply add it to configuration.yaml

Please check the format

### URL

https://www.home-assistant.io/dashboards/iframe/

### Version

2023.10.5

**Comment by dannytsang** [comment]
@koos147 the example looks like it's using a non public URL so I have pushed a change to the example YAML to correct this.

Thanks for your feedback.

~Danny
