### ISSUE TITLE
SSOCR version update request

### ISSUE THREAD

**Issue by Jacman777** [home-assistant/home-assistant.github.io#29593]
### Feedback

Could you please update version of SSOCR to Version 2.23.0 or newer?
There are some good options, which I would like to use:
Version 2.23.0 (2023-05-01):
----------------------------
 * New option -N, --min-segment to specify the minimum width and height of
   a segment, for both scanline based and ratio based character recognition
 * New option -M, --min-char-dims to specify minimum character dimensions
 * The option -d, --number-digits now also accepts a range description

### URL

https://www.home-assistant.io/integrations/seven_segments/

### Version

2023.10.5

**Comment by fabaff** [comment]
The `ssocr` release depends on the release which is installed. This is integration was written to be used with Home Assistant Core. Additional argument could into [`extra_arguments`](https://www.home-assistant.io/integrations/seven_segments/#extra_arguments)

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
