### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Bench-01** [home-assistant/home-assistant.github.io#29592]
### Feedback

It would be great to have instruction how to integrate it into an existing Home Assistant configuration. I am running it in a docker solution. Via UI it is not possible to integrate it. Thanks.

### URL

https://www.home-assistant.io/integrations/swiss_public_transport/

### Version

2023.10.5

**Comment by frenck** [comment]
Hi there, @Bench-01 👋 

> It would be great to have instruction how to integrate it into an existing Home Assistant configuration

From the documentation:

![CleanShot 2023-10-29 at 16 24 53@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/b5fd7f22-a609-4e0b-b5f5-61309a8e8a98)

That is exactly what your suggestion is?

../Frenck

**Comment by Bench-01** [comment]
Hi Frenck

thanks for your swift reply. 

I am running home assistant locally in a docker container. It would be great to have an integration for a local solution. If I add the sensor as stated, it doesn’t work :-(…

Thanks for your help & best
Ben

**Comment by frenck** [comment]
> I am running home assistant locally in a docker container. 

They way you run Home Assistant is not relevant.

>  It would be great to have an integration for a local solution.

It is there, as per screenshot above.

>  If I add the sensor as stated, it doesn’t work :-(…

Seems like you are more looking for support, which is not what we are using this issue tracker for.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck

**Comment by Bench-01** [comment]
Hi Frenck

Thanks for your fast replies - even on a weekend 👍. 

I will check the source. Have a nice one & best regards
Ben
