### ISSUE TITLE
entity_id in automation services goes under "target:" not "data:"

### ISSUE THREAD

**Issue by toxikman** [home-assistant/home-assistant.github.io#29618]
### Feedback

The documentation lists entity_id and other data attributes like stop_actions, but the entity_id is not allowed under the data attribute. It goes under the target object of the service call. The heading of the tables are misleading because they say "Service data attribute"

### URL

https://www.home-assistant.io/docs/automation/services/

### Version

2023.10.5

**Comment by frenck** [comment]
> but the entity_id is not allowed under the data attribute. 

That is incorrect. Both are allowed.

../Frenck
