### ISSUE TITLE
Entity wrong

### ISSUE THREAD

**Issue by PiMaV** [home-assistant/home-assistant.github.io#29627]
### Feedback

in 3. "Example in YAML."

it says:
...
      action:
         - service: homeassistant.update_entity
           target:
             entity_id: weather.home

but the entity should be : "sensor.speedtest_download"

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2023.10.5

**Comment by rohankapoorcom** [comment]
This is a generic example of how an automation to poll can work. The generic example is shared between multiple integrations and that's why it doesn't reference the entity name specific to the integration.
