### ISSUE TITLE
None of the links at the bottom of the page work

### ISSUE THREAD

**Issue by askpatrickw** [home-assistant/home-assistant.github.io#29633]
### Feedback

The links at the bottom go nowhere. I'd submit a PR, but I have no idea where it was they were intended to go. Maybe to the individual integrations?

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2023.10.5

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/4002194/e78512f0-2e3f-4ac7-8847-27c29f6b6fe0)

**Comment by janiversen** [comment]
hmmm seems to be a problem.
