### ISSUE TITLE
The docs need to provide more guidance when setting up modbus the first time

### ISSUE THREAD

**Issue by askpatrickw** [home-assistant/home-assistant.github.io#29635]
### Feedback

The docs assume a LOT of knowledge from the reader. Some things I found confusing\missing:

- When making changes to the modbus connection and entity configurations, when do you need to restart HA vs Reload the YAML?
- Entity Names -- Maybe there is someplace to link to about this, but a description of what is a valid name, acceptable characters and how those names turn into entity IDs is needed (ex: a Sensor with name "My Name" becomes sensor.my_name)
- unique_id
  1. A better description of why this is helpful is needed. EX: If you want to track this data over time, you need specify a unique id.
  1. A recommended value (like a GUID) is needed, or whatever the community suggests using. I don't think anyone ever sees these, so a GUID seems great. Maybe if you're consuming the data in other ways though another strategy would be better.
- Where can you see the entity values once configured so you know they are working
  - I would add a note here that there is no "Modbus Device" going to appear in your HA Settings, Devices and Services page. (why not?)
  - Go into Entities and search for "modbus" which will be the value in the Integration column.
- binary sensors: Describe these are booleans (0 or 1) and I totally do not understand the whole thing about coils, it feels very specific to one use case. https://www.home-assistant.io/integrations/modbus#configuring-binary-sensor-entities

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2023.10.5

**Comment by janiversen** [comment]
Feedback are welcomed but Pull requests even more so. Most of us are developers not technical writers.

We do what we can to make configuration easier, but e.g. why to use unique-id is not something that an each integration should document that would simply not be maintainable. 

Thanks for the feedback, but please do not expect big changes in the documentation unless you decide to help out.

Closing issue, as it is feedback and not an issue.

**Comment by askpatrickw** [comment]
@janiversen maybe remove the "Provide Feedback" link from the docs if feedback is not wanted.

![image](https://github.com/home-assistant/home-assistant.io/assets/4002194/8ec480a2-c20d-405c-aba4-d3b690e19e04)

**Comment by janiversen** [comment]
- When making changes to the modbus connection and entity configurations, when do you need to restart HA vs Reload the YAML?
you only need to restart the integration, that is documented.

Entity Names -- Maybe there is someplace to link to about this, but a description of what is a valid name, acceptable characters and how those names turn into entity IDs is needed (ex: a Sensor with name "My Name" becomes sensor.my_name)
- the integration allows you to define them, how to use them is part of the general HA documentation (in order not to repeat it),
unique_id
A better description of why this is helpful is needed. EX: If you want to track this data over time, you need specify a unique id.
- This is documented in the general HA documentation.
A recommended value (like a GUID) is needed, or whatever the community suggests using. I don't think anyone ever sees these, so a GUID seems great. Maybe if you're consuming the data in other ways though another strategy would be better.
- There are no recommended values, some use 1 2 3 it's up to you.
Where can you see the entity values once configured so you know they are working
- general documentation.
I would add a note here that there is no "Modbus Device" going to appear in your HA Settings, Devices and Services page. (why not?)
- general documentation.
Go into Entities and search for "modbus" which will be the value in the Integration column.
binary sensors: Describe these are booleans (0 or 1) and I totally do not understand the whole thing about coils, it feels very specific to one use case. https://www.home-assistant.io/integrations/modbus#configuring-binary-sensor-entities
- what would a binary sensor be but true/false ? coils are part of the modbus terminology which you will find in the manual if your modbus device,


I think you expect everything to be documented in the modbus integration, but that is not how HA works or are documented. The integrations are data suppliers more or less, the rest is in HA core.

**Comment by janiversen** [comment]
> @janiversen maybe remove the "Provide Feedback" link from the docs if feedback is not wanted.
> 
> 
> 
> ![image](https://github.com/home-assistant/home-assistant.io/assets/4002194/8ec480a2-c20d-405c-aba4-d3b690e19e04)
> 
> 

Pardon me, who said feedback was unwanted, I believe I wrote the contrary and even with a thanks !

That said, feedback does not automatically mean we start writing what you want, please do not forget we are volunteers.

Apart from that I gave you an answer to each of your questions so what do you expect more.

Please note the priority in the image, make a suggestion is first priority.
