### ISSUE TITLE
Using StreamLabs Control as water source for Consumption dashboard

### ISSUE THREAD

**Issue by twitchnln** [home-assistant/home-assistant.github.io#29649]
### Feedback

Has anyone given any thought to pulling usage stats from API to update energy dashboard water consumption? I know we can pull daily, monthly & yearly usage from API, if it was only tied to the device...

### URL

https://www.home-assistant.io/integrations/streamlabswater/

### Version

2023.10.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
