### ISSUE TITLE
Adding Fritz!DECT 302 Thermostat and Fritz!Box 7590 AX to supported devices?

### ISSUE THREAD

**Issue by malexmave** [home-assistant/home-assistant.github.io#29643]
### Feedback

The Fritz Smart Home integration lists the Fritz!DECT 301 Thermostat, but not the 302 Thermostat, as supported. I just set up a 302 Thermostat and so far, everything seems to work quite fine. The same is true for my Fritz!Box 7590 AX, which is also not explicitly listed as compatible, but works well for me.

If there is a defined set of tests that should be performed to "certify" the device as compatible with the integration, I'd be happy to perform them with my device and report back, so that it can be listed as compatible.

### URL

https://www.home-assistant.io/integrations/fritzbox/

### Version

2023.10.1

**Comment by klaasnicolaas** [comment]
If it works, it works. You could create pull requests to add these devices to the list.

**Comment by mib1185** [comment]
the docs do not contain a compatibility list, but a list about tested devices. as @klaasnicolaas wrote, feel free to open an PR to update the list of tested devices in docs - contributions are always highly welcome 🙂

**Comment by malexmave** [comment]
Great - I will check another two or three things and create a pull request with the devices afterwards. Thank you!
