### ISSUE TITLE
Fitbit configuration issue

### ISSUE THREAD

**Issue by Santory2** [home-assistant/home-assistant.github.io#29654]
### Feedback

Hi

When i try to configure my fitbit, i made a mistake in the key. So fit bit reply there is an error. But now i dont know how change the key as when a try to confugure my fitbit, the config page is bypass.

is there a way to change the config ?

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2023.11.0

**Comment by allenporter** [comment]
See https://www.home-assistant.io/integrations/application_credentials/ for how to remove the credentials. Thanks!
