### ISSUE TITLE
unable to retrieve the bus prediction.

### ISSUE THREAD

**Issue by tazrut** [home-assistant/home-assistant.github.io#29655]
### Feedback

Hi There,
I have my Prediction working when using the YAML configuration. 
this is my previous configuration:
- platform: nextbus
  agency: stl
  route: 76O
  stop: 41467

- platform: nextbus
  agency: stl
  route: 76E
  stop: 42958

Since it was moved to the UI with revision 2023.10 it's not working anymore I get the following error:
! unknown Error Occured ! whenever route I select. 
I am using the latest HA version 2023.11

### URL

https://www.home-assistant.io/integrations/nextbus/

### Version

2023.11.0

**Comment by ViViDboarder** [comment]
Could you share the log as well?

**Comment by ViViDboarder** [comment]
Oh also, this should be reported on home-assistant/core. This is the documentation site.

**Comment by tazrut** [comment]
Hi Attached the debug log and the screenshot of the error
[home-assistant_nextbus_2023-11-02T18-25-13.029Z.log](https://github.com/home-assistant/home-assistant.io/files/13243305/home-assistant_nextbus_2023-11-02T18-25-13.029Z.log)
![2023-11-02_14-25-06](https://github.com/home-assistant/home-assistant.io/assets/97889332/88d91f90-8f4e-46a3-8cf6-0d34419f4b87)

**Comment by ViViDboarder** [comment]
This should be closed since I created an issue in the proper repo.

**Comment by ViViDboarder** [comment]
@home-assistant close
