### ISSUE TITLE
Multiple accounts for family

### ISSUE THREAD

**Issue by timebreak** [home-assistant/home-assistant.github.io#29650]
### Feedback

Is it there a way to create multiple instances of fitbit? with different client ID and token?

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2023.11.0

**Comment by allenporter** [comment]
Yes, see https://www.home-assistant.io/integrations/application_credentials/ -- go into the "..." menu and pick application credentials then add your additional fitbit credentials. Then you go back to add the integration and it should give you the option to select a credential and add that account. Let me know if that covers it.
