### ISSUE TITLE
install & onboarding raspberry Pi

### ISSUE THREAD

**Issue by seanmaskey** [home-assistant/home-assistant.github.io#29668]
### Feedback

Hi
instructions & download are brilliant. BUT, having got too the end & its up & running, how do I turn off the Pi? that's not explained for a setup un by iPhone ( or laptop).
lots of complicated explanations available, but nothing clear from HA dash itself. 

Thanks

S

### URL

https://www.home-assistant.io/getting-started/concepts-terminology/

### Version

2023.11.0

**Comment by frenck** [comment]
>  how do I turn off the Pi?

One doesn't? This system is not designed to be turned off and it is not common to have it not running either.

But, there is a power button in the top right in Setting -> System.

../Frenck
