### ISSUE TITLE
Battery data from a combined (in+out) data source

### ISSUE THREAD

**Issue by Womble-1** [home-assistant/home-assistant.github.io#29665]
### Feedback

Current Template for batteries requires a sensor for input and a sensor for output.   The data I have, tracks this as a positive number for input and negative for output.  
Request that there is a 3rd box for a combined data source. 
Source is Victron Cerbo GX
---
Further to this, it could be further improved by tracking live power (kW) and summerising kWh rather than summerising before input. 

Tx

### URL

https://www.home-assistant.io/docs/energy/battery/

### Version

2023.11.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
