### ISSUE TITLE
Please rectify Type to follow menu 

### ISSUE THREAD

**Issue by thorrrr** [home-assistant/home-assistant.github.io#29667]
### Feedback

Please see [here](https://i.imgur.com/X7JYut3.png) 

### URL

https://www.home-assistant.io/integrations/todo/

### Version

2023.11.0

### Additional information

Noting major just house keeping looks rushed

**Comment by frenck** [comment]
I'm not sure if I understand what your feedback is about. What is the exact wording suggestion you think we should change?

../Frenck

**Comment by thorrrr** [comment]
Hi Frenk
If you see my link the image shows😀
It's not change the name it's make it same format as the rest
Currently To-do lists
Change To-Do Lists
Hope that helps

**Comment by frenck** [comment]
Aah check 👍 

Ps: the way it is shown in your screenshot is the correct way to write it.

**Comment by thorrrr** [comment]
Yes it then fits in with rest of sidebar menu
