### ISSUE TITLE
To Do List needs to be added via Shopping List

### ISSUE THREAD

**Issue by OlafKocanda** [home-assistant/home-assistant.github.io#29666]
### Feedback

The new topic in the sidebar called todo list is only added to the sidebar if a previous shopping list was added.
Please add the link to add to do lists integration (same link as in shopping list integration can be used for that):

https://www.home-assistant.io/integrations/shopping_list/

Here I was missing it:
![grafik](https://github.com/home-assistant/home-assistant.io/assets/58265203/614a578c-f8d6-41cf-84a0-d8dda8b72689)
But in the to do list documentation the link to add it is missing:
![grafik](https://github.com/home-assistant/home-assistant.io/assets/58265203/aed11649-890b-45a3-ad8d-82dc68fdd9e3)

So I added Shopping list integration:
![grafik](https://github.com/home-assistant/home-assistant.io/assets/58265203/618818c6-fbd1-4e9e-bb35-955854160a43)
Then it is shown:
![grafik](https://github.com/home-assistant/home-assistant.io/assets/58265203/c181b644-93ed-4ec5-97b0-6a85b1a75eb1)

### URL

https://www.home-assistant.io/integrations/todo/

### Version

2023.11.0

**Comment by BrainStone** [comment]
Also interesting is that if the todo integration is *not* installed, I still get several todo lists, but keep my old shopping list.

Now the old `shopping_list_updated` even still works, however I was not able to find the even for the todo list. This seems very inconsistent!

**Comment by MartinHjelmare** [comment]
As noted in the docs page for the To-do List integration, it's a building block and not an integration that can be directly set up by users. Other integrations are required to make use of the To-do List integration.

https://www.home-assistant.io/integrations/todo/

Regarding events, the To-do List integration is a new integration with its own framing of architecture design. It's not the intention to copy the Shopping List integration features 1:1 to the To-do List integration. As the To-do List integration is an Entity integration that allows other integrations to create entities in Home Assistant, State change events and Service Call events are fired as for all other integrations that provide entities.
