### ISSUE TITLE
Home assistant can't find the curtains

### ISSUE THREAD

**Issue by GlennHa1** [home-assistant/home-assistant.github.io#29664]
### Feedback

If home assistant cant find the cover entity add  scan_interval: 600 to the configuration.yaml folder below your login credentials. 

slide: #example of my slide config.
  username: !secret username
  password: !secret password
  scan_interval: 600

### URL

https://www.home-assistant.io/integrations/slide/

### Version

2023.11.0

**Comment by ualex73** [comment]
You can only configure the scan internal per account, it is not possible to do it per slide (or cover). The slide information is pulled with 1 request for all slides.
