### ISSUE TITLE
WeatherStation API deprecated

### ISSUE THREAD

**Issue by Kicken66** [home-assistant/home-assistant.github.io#29662]
### Feedback

Since the WeatherStation api will be deprecated by the end of this year are there any plans to use the two new options WeatherMeasurePoint or WeatherObservation?

### URL

https://www.home-assistant.io/integrations/trafikverket_weatherstation/

### Version

2023.11.0

**Comment by gjohansson-ST** [comment]
There is already an open issue on this and it will be migrated to the new endpoints before it stops working.
https://github.com/home-assistant/core/issues/101753
