### ISSUE TITLE
Changed site

### ISSUE THREAD

**Issue by One35SEven** [home-assistant/home-assistant.github.io#29679]
### Feedback

It seems the stookwijzer site has changed. Wondering if this integration is still working as it should?

### URL

https://www.home-assistant.io/integrations/stookwijzer/

### Version

2023.11.0

**Comment by One35SEven** [comment]
Site is now: https://www.atlasleefomgeving.nl/stookwijzer

**Comment by fwestenberg** [comment]
Thanks for the heads up! I will update the API this weekend!
