### ISSUE TITLE
ZigBee / Z-wave

### ISSUE THREAD

**Issue by mcclumpherty** [home-assistant/home-assistant.github.io#29676]
### Feedback

While this is an excellent article it also makes me worry.

Like masses of other people I have significant investment in ZigBee devices and this article pretty much ignores this fact as it focuses more on a future end-state.

It would be very much appreciated if more space was dedicated to explaining how Matter will incorporate these networks and how the various controllers for them will be supported by HA.

Otherwise I am left with the feeling that all the time and money I have put into setting up my existing devices is wasted and I may be led to unnecessarily ditch them in the hope that Thread based replacements will come along.

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2023.11.0

**Comment by Hedda** [comment]
Not sure exactly what you mean but check out this PR https://github.com/home-assistant/home-assistant.io/pull/29744

**Comment by marcelveldt** [comment]
I'm not getting the clue here. I'm assuming you switched from VHS to DVD to BlueRay to streaming services or harddisks ?
Your VHS is still working but a streaming service is more convenient.

Matter is just another technical evolution. It does not make your Zigbee devices stop working or whatever.
I foresee that Matter (and Thread as radio transport) is going to need a few years to mature and in the meanwhile Z-Wave Zigbee devices will still be sold. It will just coexist.

I'm the maintainer of Matter within HA and I have my house full of Zigbee devices that work perfectly fine, I'm really not going to dump that, unless a device maybe reaches its lifetime I could potentially replace it with something else, like Matter.

If you ask what protocol to choose when you are going to jump into the smart home market, you may want to consider Matter.
