### ISSUE TITLE
Weekday settings: holidays and offset

### ISSUE THREAD

**Issue by kraaidelft** [home-assistant/home-assistant.github.io#29688]
### Feedback

Where can I see the list of holiday for my country? And the English names use? Or the Dutch?
Why should I use an offset in the settings page?

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2023.11.0

**Comment by dannytsang** [comment]
There is no way to see a list of holidays from what I can see. It creates an entity with states *on* for a working day and *off* for non working day including public holidays. If you want this, I'd suggest raising a new feature request and it will be dependent on the library it uses having a list.

There's an example in [Specific field information](https://www.home-assistant.io/integrations/workday/#specific-field-information) why you may want to use the offset.

**Comment by gjohansson-ST** [comment]
I would assume as a resident of a country and possible province you would know how to get your public holidays. Any removal or additions of holiday days you can always see in the options as they are added by yourself.

As already mentioned the use of offset is covered in the doc's.
Will close this issue.
