### ISSUE TITLE
Datetime

### ISSUE THREAD

**Issue by euhkah** [home-assistant/home-assistant.github.io#29689]
### Feedback

Hello !

An option should be added to add a datetime to the todo ! In google tasks if the todo as a date, it activates a notification.

Thanks

### URL

https://www.home-assistant.io/integrations/todo/

### Version

2023.11.0

**Comment by MartinHjelmare** [comment]
Feature requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum. Thanks!
