### ISSUE TITLE
Smart Meter 63A sensors Unavailable

### ISSUE THREAD

**Issue by lakusz1github** [home-assistant/home-assistant.github.io#29687]
### Feedback

from yesterday all sensors for Smart Meter 63A are unavailable :(

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2023.11.0

**Comment by farmio** [comment]
Hi 👋! 
This is the issue tracker for the **documentation** repo, not HA core. The bug introduced in 2023.11.0 should be fixed by https://github.com/home-assistant/core/pull/103211 in 2023.11.1
