### ISSUE TITLE
Please remove obsolete "restore from backup" instructions

### ISSUE THREAD

**Issue by kupietools** [home-assistant/home-assistant.github.io#29691]
### Feedback

Your "restore" instructions refer to features which appear to have been completely removed from Home Assistant, which caused me to spend several hours on something that is apparently no longer possible. 

My Welcome screen does not have a "restore" option. My Settings->System->Backups screen gives options to download or delete a backup but not to restore from one. There is no way to "select a backup", as you suggest, and clicking anywhere but the "delete" or "download" buttons selects the text in my browser window and that's it. You can see these in the screenshots below. 

Please, people waste time trying to follow incorrect instructions if you leave them up. If you have removed the ability to restore from a backup you should immediately update the documentation and save your users potentially hours of unproductive lost time.

### URL

https://www.home-assistant.io/common-tasks/os/

### Version

2023.11.0

### Additional information

![Screen Shot 2023-11-03 at 4 50 58 PM](https://github.com/home-assistant/home-assistant.io/assets/26891995/8d5c6e18-6f46-44ac-87a0-b99e3b26f784)
![Screen Shot 2023-11-03 at 4 29 04 PM](https://github.com/home-assistant/home-assistant.io/assets/26891995/95f736cc-25a3-43a5-a768-237d0701cde6)

**Comment by frenck** [comment]
Hi there @kupietools 👋 

You have provided feedback on the documentation for common tasks when using the Home Assistant Operating System, however, your screenshots indicate you are not using that.

This specific page thus does not apply to your installation method.

../Frenck
