### ISSUE TITLE
Restore to earlier version of Protect not possible from backup file

### ISSUE THREAD

**Issue by Swallowtail23** [home-assistant/home-assistant.github.io#29702]
### Feedback

The suggestion here that you can restore to an earlier version of Protect doesn't work - you can only restore settings, not the Protect application this way.

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2023.11.1

**Comment by AngellusMortis** [comment]
https://help.ui.com/hc/en-us/articles/360008976393

> Dedicated UniFi Consoles (Dream Machines, Cloud Keys, Network Video Recorders, etc) offer System Config Backups, which include all OS, Application, and Device configurations.

If backups are not working right for you, you should contact UniFi support. This is not a UniFi Protect support forum.

**Comment by AngellusMortis** [comment]
@home-assistant close

**Comment by Swallowtail23** [comment]
Thanks for the advice :) 

Backups and restores are working fine for me, I have validated that. The issue here is that the HA page says:
![image](https://github.com/home-assistant/home-assistant.io/assets/8214128/df7d1396-305a-4cac-8a1f-c620f5716340)


**That is not correct.** The hyperlinked suggestion leads to absolutely correct instructions on how to restore from a backup, and that works OK - for config and settings.

However restoring to a backup made under a previous version *does not* change your installed version of Protect, and so will not "downgrade to a stable version".

The manual downgrade suggestion does work (although as noted comes with its own risks).

(For context, my NVR is set to Official releases only. UI pushed a release as Official and then changed it to EA the next day, so anyone who had auto updates configured to official will now be running EA until UI come up with a new release).
