### ISSUE TITLE
Bots are no possible to be controled by cloud

### ISSUE THREAD

**Issue by rfernalu** [home-assistant/home-assistant.github.io#29707]
### Feedback

I have two bots at home (switch) and these works fine with the SwitchBot app, are connected and works fine at cloud. But, the Home Assistant integration (SwitchBot Cloud) don't recognise the bots and shows me empty of devices. It would be nice to control the bots by the SwitchBot Cloud API.

### URL

https://www.home-assistant.io/integrations/switchbot_cloud/

### Version

2023.11.1

**Comment by SeraphicRav** [comment]
Thank you for reaching out. GitHub is used for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our Community Forum: [Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks!

**Comment by SeraphicRav** [comment]
@home-assistant close
