### ISSUE TITLE
Following the Enphase Envoy polling interval documentation results in errors

### ISSUE THREAD

**Issue by foggy-stakes** [home-assistant/home-assistant.github.io#29703]
### Feedback

The Enphase Envoy documentation has a section on [modifying the polling interval](https://www.home-assistant.io/integrations/enphase_envoy#polling-interval), which is great, but I think it might be incorrect.

It says 
> Specify the envoy device as a target of the service using the `+ choose device` button. Updating the envoy will also update the related devices like the inverters; there is no need to split them into separate entities or add all inverter devices.

However, when I did this, I saw errors like this:
```
2023-11-05 18:27:10.092 ERROR (MainThread) [homeassistant.components.automation.high_frequency_enphase_envoy_polling] High-Frequency Enphase Envoy Polling: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['device_id']
2023-11-05 18:27:10.097 ERROR (MainThread) [homeassistant.components.automation.high_frequency_enphase_envoy_polling] Error while executing automation automation.high_frequency_enphase_envoy_polling: extra keys not allowed @ data['device_id']
```
In my case I had to specify the entities rather than the envoy device.

I got the clue to try this from issue [76455](https://github.com/home-assistant/core/issues/76455#issuecomment-1208061433).

### URL

https://www.home-assistant.io/integrations/enphase_envoy#polling-interval

### Version

2023.11.1

**Comment by arkpoah** [comment]
I confirm I get the same error when creating an automation which updates envoy device

**Comment by catsmanac** [comment]
Hi @foggy-stakes and @arkpoah,  yes you are right, I tried it as well. One needs to specify an entity from the Enphase Envoy and not the device. I'll update the docs and change this part:

Specify _the envoy device_ as a target of the service using the + choose device button.

to

Specify _a single entity from envoy device_ as a target of the service using the + choose device button.

**Comment by arkpoah** [comment]
Thanks for your answer @catsmanac 
I can confirm it works when I select an entity.
All entities of this device are also updated (perfect), but it is strange according to the automation which targets only one entity, can you confirm this is the normal behavior ?

**Comment by catsmanac** [comment]
@arkpoah, it's what I would expect for the Enphase Envoy integration yes. I'm not into internals of the automations, but a when the Envoy integration is triggered for an update, it requests the full data set from the Envoy and returns it to HA. Enphase Envoy has no option to return just a single value. 

It seems that HA updates each entity returned if time and/or value was changed.
