### ISSUE TITLE
Salda Smarty integration do not work on version 2023.11.1

### ISSUE THREAD

**Issue by mehdi-38** [home-assistant/home-assistant.github.io#29722]
### Feedback

Hello,
i tried the integration of smarty on HA to contole my Salda system trough MB-Gateway, but the integration didn't work; i got the following error message : "setup failed for smarty: dependency is disabled - dependencies not compatible with the new pip resolver"
However, the integration worked fine when i downgraded the core to version 2023.3.1.
 is there a known issue related to this ? is there a workaround to make it work?

Thank you for your suport

### URL

https://www.home-assistant.io/integrations/smarty/

### Version

2023.11.1

**Comment by atub** [comment]
Same problem here...

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
