### ISSUE TITLE
No Luck setting up Harmony remote Hub

### ISSUE THREAD

**Issue by montekay1** [home-assistant/home-assistant.github.io#29737]
### Feedback

I don't think this was written for newbies and I'm a newbie at this stuff...

It seems to understand all the devices programmed into the Harmony remote but getting it to do anything with any of them is another story.  The device just says activities, "Power OFF"  There is a switch in the off position, if set to on, it automatically changes to off a few seconds later.

Ideally I could create a dashboard with for example volume up/down controlling the Marantz, play/pause etc controlling the Panasonic, Anamorphic A... Off controlling the JVC and so on.  No idea where to start!  

Thanks,
mk

![harmony](https://github.com/home-assistant/home-assistant.io/assets/147576705/70cc7d51-d5fc-422b-b1de-bfeb33f3f115)
{
    "Activities": {
        "-1": "PowerOff"
    },
    "Devices": {
        "JVC Projector": {
            "commands": [
                "PowerOff",
                "PowerOn",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "OK",
                "Return",
                "Menu",
                "PictureMode",
                "Info",
                "PictureMode",
                "AdvancedMenu",
                "Anamorphic(A)",
                "Anamorphic(B)",
                "Anamorphic(C)",
                "Anamorphic(D)",
                "AnamorphicOff",
                "C.M.D.",
                "ColorProfile",
                "GammaSettings",
                "HDRLevel+1",
                "HDRLevel+2",
                "HDRLevel0",
                "HDRLevel-1",
                "HDRLevel-2",
                "HDRLevelAuto",
                "HDRLevelAutoWide",
                "Hide",
                "Input",
                "LensControl",
                "LensMemory1",
                "LensMemory10",
                "LensMemory2",
                "LensMemory3",
                "LensMemory4",
                "LensMemory5",
                "LensMemory6",
                "LensMemory7",
                "LensMemory8",
                "LensMemory9",
                "MPC",
                "SettingsMemory"
            ],
            "id": "80317271"
        },
        "Marantz AV Receiver": {
            "commands": [
                "PowerOff",
                "PowerOn",
                "PowerToggle",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "Mute",
                "VolumeDown",
                "VolumeUp",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "Enter",
                "Play",
                "Pause",
                "SkipBack",
                "SkipForward",
                "Back",
                "PresetPrev",
                "TuneDown",
                "TuneUp",
                "PresetNext",
                "Setup",
                "Sleep",
                "Info",
                "PageDown",
                "PageUp",
                "AllZoneStereoOn/Off",
                "AudysseyDynamicVolumeMode",
                "AudysseyLFCOn/Off",
                "AudysseyMultEqMode",
                "Auto",
                "CenterDown",
                "CenterUp",
                "DirectMode",
                "DolbyAtmosOn/Off",
                "DTS",
                "GraphicEQOn/Off",
                "InputAux1",
                "InputAux2",
                "InputBluetooth",
                "InputBlu-ray",
                "InputCbl/Sat",
                "InputCd",
                "InputDvd",
                "InputGame",
                "InputHeos",
                "InputInternetRadio",
                "InputMediaPlayer",
                "InputModeAnalog",
                "InputModeAuto",
                "InputModeDigital",
                "InputModeHdmi",
                "InputModeSelect",
                "InputNapstar",
                "InputPandora",
                "InputPhono",
                "InputRhapsody",
                "InputSiriusXM",
                "InputSpotify",
                "InputTuner",
                "InputTvAudio",
                "InputUsb",
                "M-DAXToggle",
                "ModeGame",
                "ModeMovie",
                "ModeMusic",
                "ModePure",
                "MultiCh",
                "Option",
                "PureDirect",
                "PureDirect(Toggle)",
                "SmartSelect1",
                "SmartSelect2",
                "SmartSelect3",
                "SmartSelect4",
                "Stereo",
                "SubWoofer2Down",
                "SubWoofer2Up",
                "SubWooferDown",
                "SubWooferUp",
                "Surround",
                "SurroundMode(Back)",
                "Virtual"
            ],
            "id": "80317269"
        },
        "Panasonic DVD/Blu-ray Player": {
            "commands": [
                "PowerOff",
                "PowerOn",
                "PowerToggle",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "DirectionDown",
                "DirectionLeft",
                "DirectionRight",
                "DirectionUp",
                "OK",
                "Stop",
                "Play",
                "Rewind",
                "Open/Close",
                "Pause",
                "FastForward",
                "FrameAdvance",
                "SkipBack",
                "SkipForward",
                "Return",
                "TopMenu",
                "PopUpMenu",
                "Subtitle",
                "Audio",
                "PictureMode",
                "Green",
                "Red",
                "Blue",
                "Yellow",
                "Cancel",
                "PictureMode",
                "Netflix",
                "HDRSetting",
                "Home",
                "Internet",
                "Option",
                "PlaybackInfo",
                "Status"
            ],
            "id": "80317270"
        }
    }
}

### URL

https://www.home-assistant.io/integrations/harmony/

### Version

2023.11.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
