### ISSUE TITLE
Odroid XU4 IMG Download link.

### ISSUE THREAD

**Issue by mafator-mz** [home-assistant/home-assistant.github.io#29747]
### Feedback

https://www.home-assistant.io/installation/odroid

In the selection (Download the image to your computer) table the XU4 tab is missing. It would be nice to add the corresponding Tab or link to it.

My Quick fix : ( I discovered that you have the development build for XU4 on https://os-artifacts.home-assistant.io/index.html so i just tried the luck with https://github.com/home-assistant/operating-system/releases/download/11.1/haos_odroid-xu4-11.1.img.xz as the directory listing is not allowed for https://github.com/home-assistant/operating-system/releases/download/11.1  .. it worked ;))

thanks for the fantastic app/platform ! ( HA )

### URL

https://www.home-assistant.io/installation/odroid/

### Version

2023.11.1

**Comment by c0ffeeca7** [comment]
Hi @mafator-mz. Thank you for reaching out. 

There is no documentation on Odroid XU4 as we don't actively promote ARMv7 /  32-bit ARM boards. 
I will therefore close this issue as not planned. Happy to hear it worked for you :tada:
