### ISSUE TITLE
shopping list automation has a problem

### ISSUE THREAD

**Issue by FedeL16** [home-assistant/home-assistant.github.io#29749]
### Feedback

alias: Lista Spesa aggiunge Fede
description: ""
trigger:
  - platform: event
    event_type: shopping_list_updated
    event_data:
      action: add
    context:
      user_id:
        - 88e6bf576f9e460db175a265ebc2122f
before last update does not problem to activate the trigger, but now this trigger is activated only without context and user id.

Please solve this because if i add an item on shopping list i need not a notification on my phone but only on my girlfriend phone

thank a lot

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2023.11.1

**Comment by dannytsang** [comment]
This sounds like a potential bug and I'm afraid you have raised your issue in the documentation repository. Please go to **New Issue** > **Report a bug/issue with Home Assistant Core itself** and report this please.
