### ISSUE TITLE
wollt ihr nicht das homeassistent genutzt wird

### ISSUE THREAD

**Issue by SonnyGermany** [home-assistant/home-assistant.github.io#29755]
### Feedback

warumm schreibt ihr ein prog was man nicht laden kann ohne raspi kake

### URL

https://www.home-assistant.io/integrations/downloader/

### Version

2023.11.1

**Comment by SonnyGermany** [comment]
coll hir auch nicht

**Comment by SonnyGermany** [comment]
immer noch nicht

**Comment by frenck** [comment]
Hi there @SonnyGermany 👋 

We are an English-only community. I have no idea what this means.

Closing this issue for that reason.

../Frenck

**Comment by SonnyGermany** [comment]
wie schön das ich hir nichts linde

**Comment by SonnyGermany** [comment]
Hm dann sollte man deutsch lernen oder die Software loschenGesendet mit der mobilen Mail AppAm 08.11.23 um 13:16 schrieb Franck Nijhof
                
            
            
                
                    Von: "Franck Nijhof" ***@***.***>Datum: 8. November 2023An: "home-assistant/home-assistant.io" ***@***.***>Cc: "Mention" ***@***.***>,"SonnyGermany" ***@***.***>Betreff: Re: [home-assistant/home-assistant.io] wollt ihr nicht das homeassistent genutzt wird (Issue #29755)
                
                
Hi there @SonnyGermany 👋
We are an English-only community. I have no idea what this means.
Closing this issue for that reason.
../Frenck
