### ISSUE TITLE
wo kann man das laden

### ISSUE THREAD

**Issue by SonnyGermany** [home-assistant/home-assistant.github.io#29754]
### Feedback

wo kann man das prog laden ohne ds man 25 zusatzprograme installieren muss

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.11.1

**Comment by klaasnicolaas** [comment]
I don't quite understand what you mean exactly, could you please clarify.

**Comment by frenck** [comment]
Hi there @SonnyGermany 👋 

Sorry, we are an English community. I have no idea what this means.

Going to close this issue for that reason.

../Frenck
