### ISSUE TITLE
Outdated MQTT documentation

### ISSUE THREAD

**Issue by orcaman98** [home-assistant/home-assistant.github.io#29767]
### Feedback

Section "Support by third-party tools" refers to [Zwave2Mqtt](https://github.com/OpenZWave/Zwave2Mqtt), which has been unmaintained for two years, and apparently replaced. I do not know if any of the replacements implement relevant functionality. 

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2023.11.1

**Comment by jbouwh** [comment]
Thanx, the linked PR will remove the zwave2mqtt references from the mqtt docs
