### ISSUE TITLE
CONDITION MAPPING shows ‘clear-night’ as an icon for MDI - but it doesn't exist

### ISSUE THREAD

**Issue by chunkysteveo** [home-assistant/home-assistant.github.io#29769]
### Feedback

The Conditional Mapping (https://www.home-assistant.io/integrations/weather/#condition-mapping) states all the available states are set to allow for the MDI icon sets to be used on the frontend, but the state "clear-night" does not exist within MDI - it's "(weather)-night". MDI should ideally update or allow alias for "weather-clear-night" as that is more accurate.

Maybe a note added to this section to highlight for at least 'clear-night', that there is not a 1:1 mapping for the MDI icons?

### URL

https://www.home-assistant.io/integrations/weather/

### Version

2023.11.1

**Comment by frenck** [comment]
Thanks, @chunkysteveo 👍 

I've opened up a PR to adjust the documentation.

../Frenck

**Comment by chunkysteveo** [comment]
Awesome, thanks!
