### ISSUE TITLE
To do list items

### ISSUE THREAD

**Issue by omakoti** [home-assistant/home-assistant.github.io#29778]
### Feedback

Can't remove items from to do list. I can list them as checked items but no way to remove them in HA.

### URL

https://www.home-assistant.io/integrations/google_tasks/

### Version

2023.11.1

**Comment by allenporter** [comment]
Hi, this feature did not make the initial release, but good news -- this has already been added and will be part of the next major home assistant release 2023.12 (https://github.com/home-assistant/core/pull/102967)

You are encouraged to post feature requests in the [Feature Requests](https://community.home-assistant.io/c/feature-requests/13) community forum.

Closing.
