### ISSUE TITLE
Incorrect details for service calendar.list_events

### ISSUE THREAD

**Issue by controlaltnerd** [home-assistant/home-assistant.github.io#29787]
### Feedback

While working with calendar.list_events recently, I found that Home Assistant expects a value for either `end_date_time` or `duration` when a call is made to the service. However, the documentation for the Calendar integration has all attributes for the service marked as optional:

![list_events](https://github.com/home-assistant/home-assistant.io/assets/112291773/89062f0d-83f0-44c4-94e9-bfb62c9d70fe)

This was the error returned by HA:

```
Error Message: must contain at least one of end_date_time, duration.. Got
{
    'type': 'execute_script',
    'sequence': [
        {
            'service': 'calendar.list_events',
            'target': {
                'entity_id': [
                    calendar.my_calendar
                ]             
            },
            'response_variable': 'agenda'
        },
        {
            'stop': 'done',
            'response_variable': 'agenda'
        }     
    ],
    'id': 34
}
```

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2023.11.1

**Comment by FletcherAU** [comment]
`end_date_time` notes in the description that it cannot be used with `duration`. The PR above adds the same note to `duration` to hopefully increase readability.

**Comment by controlaltnerd** [comment]
The problem I'm seeing here isn't that the documentation is unclear on the incompatibility between `end_date_time` and `duration`, but rather that the documentation states that both of them are optional, when the error message returned by HA when a call to `calendar.list_events` does not include either indicates that HA is definitely expecting one or the other. If the documentation reflects the intention of the integration, then perhaps I should open an issue over in the core repo to discuss that instead?

**Comment by FletcherAU** [comment]
I suspect that the issue may just be that the convention for the Optional column seems to be yes/no which doesn't really cover the above case.

May be worth sitting tight until more experienced swings by :)

**Comment by c0ffeeca7** [comment]
Thank you for bringing this up and updating the documentation, @controlaltnerd and @FletcherAU.

You are correct, one of the options `duration` or `end_date_time` must be specified. They are mutually exclusive.
https://github.com/home-assistant/core/blob/dev/homeassistant/components/calendar/__init__.py#L266-L267
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/778c9463-caf8-401a-b3e7-ed6a6a006dd8)
