### ISSUE TITLE
secret.yaml - where is the advantage?

### ISSUE THREAD

**Issue by MMannheim** [home-assistant/home-assistant.github.io#29798]
### Feedback

While reading documentation and threads regarding the use of secrets.yaml, I wonder where the advantage in security aspect is? The password is still stored in a file and not encrypted in any way.  Or am I wrong with this?

### URL

https://www.home-assistant.io/docs/configuration/secrets/

### Version

2023.11.2

**Comment by klaasnicolaas** [comment]
A) you can more easily keep all your secrets in one place
B) many people also publish their config on GitHub and then you want to prevent your secrets from being there.

./Klaas

**Comment by frenck** [comment]
As per above, there is no advantage in security aspect. I don't know how you came to that conclusion, as the page you linked doesn't say anything about that.

It as per the answer of Klaas, it allows you to centralize your secrets. This can be an advantage when sharing snippets or maintaining your configuration in, e.g., a git repository.

../Frenck

**Comment by MMannheim** [comment]
@frenck , @klaasnicolaas : OK - thanks for the feedback.

**Comment by steve5053872** [comment]
Would it be possible to change the file permissions for secrets.yaml so only Supervisor has read permissions?
