### ISSUE TITLE
Electric car and heatpump

### ISSUE THREAD

**Issue by bartluyckx** [home-assistant/home-assistant.github.io#29794]
### Feedback

An electric car and heatpump consumes much more energy than otter devices.
Therefore it would be nice when you could ad those to a separate graph.
Using different Axes in the graph would also be an option.
Adding the option to charge the name,of the gas staving graph to sommering else would also be an option. I know misuse the gasconsumption graph for the carcharger. 

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2023.11.2

**Comment by dannytsang** [comment]
Please raise this as a feature request by going to **New issues** > **Feature Request**.

This repository's scope is documentation.
