### ISSUE TITLE
Wyoming protocol installation

### ISSUE THREAD

**Issue by tbrummel** [home-assistant/home-assistant.github.io#29807]
### Feedback

Well, I get that I need to configure it - but there is no information about what to enter for the Host and Port settings.  Would I be entering my HomeAssistant IP?  Am I supposed to pick a free port?  Is there a default?  I'm not sure - I went to the Wyoming integration page to find out :-) 

### URL

https://www.home-assistant.io/integrations/wyoming/

### Version

2023.11.2

**Comment by c0ffeeca7** [comment]
Going to close this as a duplicate of #28889.
If you have HAOS installed: how to create a local voice pipeline is explained in the procedure on [installing a local voice pipeline](https://www.home-assistant.io/voice_control/voice_remote_local_assistant/).
