### ISSUE TITLE
TTS URL Being Truncated

### ISSUE THREAD

**Issue by WeatherWitch** [home-assistant/home-assistant.github.io#2981]
TTS not working with Google Home/LetsEncrypt.
After some investigation, I can see the domain name being truncated.

`2017-07-14 22:16:54 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: new_state=<state media_player.living_room_home=off; friendly_name=Living room Home, supported_features=21437 @ 2017-07-14T23:16:54.172914+01:00>, old_state=<state media_player.living_room_home=idle; media_content_id=https://mydomain.ddns:8123/api/tts_proxy/bac9388d0498fb378e528d35abd05792291af182_en_-_google.mp3, media_position_updated_at=2017-07-14T23:11:52.502595+01:00, supported_features=21437, volume_level=0.7300000190734863, app_name=Default Media Receiver, app_id=CC1AD845, is_volume_muted=False, friendly_name=Living room Home, media_position=0 @ 2017-07-14T23:11:52.506981+01:00>, entity_id=media_player.living_room_home>`

Log shows https://mydomain.ddns:8123 actual domain is https://mydomain.ddns.net:8123

**Comment by fabaff** [comment]
This is the issue tracker for the doucmentation. 

Please report issues at https://github.com/home-assistant/home-assistant/issues/new
