### ISSUE TITLE
Add sensor to make graphing electricity prices day ahead possible

### ISSUE THREAD

**Issue by jpduhen** [home-assistant/home-assistant.github.io#29823]
### Feedback

In my search to make a graph showing the electricity prices upto a day ahead (to plan my usage of the washing machine/dryer etc) I came upon this tutorial: 
[https://www.twoenter.nl/blog/home-assistant-nl/dynamische-energieprijzen-in-home-assistant/](url)

Here the HACS-integration of Frank-energie is used: 
[https://github.com/bajansen/home-assistant-frank_energie](url)

This integration has a sensor that provides the price-data (all-in) for the comming hours, not only the next hour as in the Energy-zero integration. As far as I can see, Energy-Zero integration does not provide such a sensor.

Is there a way to achieve the same result with the Energy-Zero integration? 
If no, I would like to ask if a simmilar sensor could be added to this Energy-Zero integration.

### URL

https://www.home-assistant.io/integrations/energyzero/

### Version

2023.11.2

### Additional information

All sensors in the Frank-energie HACS integration, the "sensor.current_electricity_price_all_in" is the sensor used to graph the hourly pricelevels in my HA dashboard.

![image](https://github.com/home-assistant/home-assistant.io/assets/45515609/1e83314d-fd8b-443f-a75b-39f3040bd93d)

Sample of the graph I have made with the sensor from Frank-Energie HACS integration:

![image](https://github.com/home-assistant/home-assistant.io/assets/45515609/f5c1bfbd-653a-483b-8b85-a72be845da59)

and the code to graph the prices in HA with the Apex Charts (also from HACS):

![image](https://github.com/home-assistant/home-assistant.io/assets/45515609/bca4f11b-86e5-4107-9b4c-8fdfaf5499f7)

**Comment by klaasnicolaas** [comment]
We use this issue tracker for documentation feedback, not for feature requests.

The Frank energie HACS integration provides this data via attributes and that is something that is not accepted as core integration, which is why this feature is not yet included in the energyzero integration. I think another method is being worked on, such as in this pull request: https://github.com/home-assistant/core/pull/101374

./Klaas
