### ISSUE TITLE
Switcher_KIS: No devices found on the network

### ISSUE THREAD

**Issue by devilion999** [home-assistant/home-assistant.github.io#29830]
### Feedback

getting error: No devices found on the network

 all ports are open from the server  and my home router

### URL

https://www.home-assistant.io/integrations/switcher_kis/

### Version

2023.11.2

**Comment by thecode** [comment]
"all ports are open from the server and my home router" what do you mean by "my home router"? Switcher devices and home assistant should be on the same network.
Please also list which devices you have that are not detected.

**Comment by thecode** [comment]
Please create the issue at the core repository since it is missing details, thanks
https://github.com/home-assistant/core/issues/new?assignees=&labels=&projects=&template=bug_report.yml
