### ISSUE TITLE
iCloud verification

### ISSUE THREAD

**Issue by norwestie** [home-assistant/home-assistant.github.io#29833]
### Feedback

I can't reconfigure my iCloud integration due to the 2FA code not being accepted. I can't locate the .storage folder to delete the iCloud info. The troubleshooting says "Go into your Home Assistant configuration .storage folder and delete the icloudfolder, then retry."
There is no storage folder listed in the config. The only icloud folder I can find is in Custom_components. Is that what I need to remove?

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2023.11.2

**Comment by norwestie** [comment]
Hello?

**Comment by norwestie** [comment]
Anybody?Sent from my iPhone Galactic MCXLIIOn Nov 13, 2023, at 11:46 AM, home-assistant[bot] ***@***.***> wrote:﻿
Hey there @Quentame, @nzapponi, mind taking a look at this feedback as it has been labeled with an integration (icloud) you are listed as a code owner for? Thanks!

Code owner commands
Code owners of icloud can trigger bot actions by commenting:

@home-assistant close Closes the feedback.
@home-assistant rename Awesome new title Renames the feedback.
@home-assistant reopen Reopen the feedback.
@home-assistant unassign icloud Removes the current integration label and assignees on the feedback, add the integration domain after the command.

**Comment by HebeROF** [comment]
For now the verification seems to be broken. 

even if you delete the iCloud folder and you try to reinstall, the verification code is not accepted. 

anoying AF.
