### ISSUE TITLE
Need instructions to share a device from Home Assistant

### ISSUE THREAD

**Issue by bobbeims** [home-assistant/home-assistant.github.io#29843]
### Feedback

The ability to commission a device into multiple fabrics is a key advantage of Matter. Is that feature not yet supported in the Home Assistant integration? If it is, we need documentation on how to use it.

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2023.11.2

**Comment by marcelveldt** [comment]
Unfortunately it is not supported yet but we're building some great new UI that includes this amongst others commands and info. Should be available within the next few months, keep an eye on our announcements.

**Comment by marcelveldt** [comment]
This has been added to HA in the previous release (including the instructions how) so I'm closing this report.
