### ISSUE TITLE
Missing Info on ensuring the host allows the mutesync app to communicate through the firewall

### ISSUE THREAD

**Issue by JoernBerkefeld** [home-assistant/home-assistant.github.io#29841]
### Feedback

given that other apps make their ports available it would be great to suggest that if the integration cannot find the host (as in, your computer), you as a user have to jump to your respective firewall's settings and allow the mutesync app to go around it.

you don't need to explain that step by step for each system, given that HA users tend to be techy, but obviously users would appreciate the hint that the installed software didn't take care of this on its own and you might wanna check.

in my case, I'm on win 11 and the standard windows firewall blocked mutesync from finding the app on my PC. by adding an exception it started working immediately. 

### URL

https://www.home-assistant.io/integrations/mutesync/

### Version

2023.11.2

**Comment by frenck** [comment]
We consider that out of scope for our project. If you decide to set up complex network structures, that is up to you and we expect you'd be able to deal with that.

If anything, this would be more fitting in the Mutesync upstream documentation.


../Frenck

**Comment by JoernBerkefeld** [comment]
looks like im less of a "sourcerer" than you are. The lack of instruction certainly cost me 20 minutes to figure out whats wrong when a single sentence in the install docs could have reduced that to 2 minutes.
