### ISSUE TITLE
Door Open 

### ISSUE THREAD

**Issue by Sir-Udo** [home-assistant/home-assistant.github.io#29851]
### Feedback

Hi,
I try to filter my door / window to show only the state if there are open. 

i try this: (or)
  - sensor.tf2_balkontuer_tur
  - binary_sensor.tf12_buero_fenster_tur
  - entity: binary_sensor.tf15_schlafzimmer_rechts_tur
 state_filter:
  - Offen (or   - Nicht Verfügbar)
 
![image](https://github.com/home-assistant/home-assistant.io/assets/143514625/07117cd7-6e70-4cbe-bde2-1e902615fb5a)

nothing works. 
can you help me please?

### URL

https://www.home-assistant.io/dashboards/entity-filter/

### Version

2023.11.2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
