### ISSUE TITLE
This documentation is only useful to the developers?

### ISSUE THREAD

**Issue by brettonw** [home-assistant/home-assistant.github.io#29850]
### Feedback

There is a circular documentation dependency where the ESPresence website refers to this documentation to add a device, but this documentation is out of date compared to their functionality.
specifically, how do I get auto-discovery to work instead of having to do this, and how do I figure out what id to use when using bluetooth LE and apple devices with irk:... ids? Can I get a real example? How do I know what room to use, etc.

### URL

https://www.home-assistant.io/integrations/mqtt_room/

### Version

2023.11.2

**Comment by frenck** [comment]
> This documentation is only useful to the developers?

Not really? This page shows the configuration parameter on how to set it up in your configuration.yaml on the end-user end.

> specifically, how do I get auto-discovery to work instead of having to do this

This integration doesn't support auto-discovery. For auto-discovery, please check the MQTT documentation: https://www.home-assistant.io/integrations/mqtt#mqtt-discovery

> and how do I figure out what id to use when using bluetooth LE and apple devices with irk:... ids?

That is not really a thing for this end. This only provides device_trackers based on the MQTT topic that is made available by an external application.


> Can I get a real example?

There is a valid and complete example listed on that page?

> How do I know what room to use, etc.

That sounds like an upstream question about the data available/provided by the application you are using.

**Comment by brettonw** [comment]
Out of date:

- away_timeout reports as an invalid parameter and prevents HA from restarting if I use it.

> Not really? This page shows the configuration parameter on how to set it up in your configuration.yaml on the end-user end.

I expected, based on the other half of the documentation and a variety of outdated youtube videos that are part of that record, that I would see a device show up under the MQTT integration. You might want to make clear that the entity will only show up under entities, and there will be no other outward indication of success.

> > specifically, how do I get auto-discovery to work instead of having to do this
> 
> This integration doesn't support auto-discovery. For auto-discovery, please check the MQTT documentation: https://www.home-assistant.io/integrations/mqtt#mqtt-discovery

The other half of the docs consistently refer to "if you have auto discovery enabled"... but never make clear what they are talking about or where to check to see if it is enabled.

> > and how do I figure out what id to use when using bluetooth LE and apple devices with irk:... ids?
> 
> That is not really a thing for this end. This only provides device_trackers based on the MQTT topic that is made available by an external application.

Except it is, because the directions about where to get the id are wrong in the case of the undocumented irk handling. You use the alias instead of the id.

> > Can I get a real example?
> 
> There is a valid and complete example listed on that page?

yes, if you know what id to use. 
Also, why do I have to specify the id and repeat that id in the room?

> > How do I know what room to use, etc.
> 
> That sounds like an upstream question about the data available/provided by the application you are using.

exactly my point, you each refer to the other half of the documentation, but neither contains a clear indicator. Once I figured out how to get this working, by looking at the source code, I was able to get something going. but outside of that, nothing worked by just following the docs.
