### ISSUE TITLE
london_underground docs not found

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/home-assistant.github.io#2985]
The link to https://home-assistant.io/components/sensor.london_underground/ on the [0.49](https://home-assistant.io/blog/2017/07/15/release-49/) blog post displays `404 file not found`.
Source [@](https://github.com/home-assistant/home-assistant.github.io/blob/next/source/_components/sensor.london_underground.markdown)

**Comment by GreenTurtwig** [comment]
Fixed via: https://github.com/home-assistant/home-assistant.github.io/commit/95fac389858a3e81b5321e01cdaefd8b34a575f5
