### ISSUE TITLE
Can't change password

### ISSUE THREAD

**Issue by kwagnitz** [home-assistant/home-assistant.github.io#29868]
### Feedback

"To reset a user’s password, as an administrator via the web interface
1. In the bottom left, select your user to go to the [Profile](https://my.home-assistant.io/redirect/profile) page and make sure Advanced Mode is activated.
2. Go to [Settings > People] and select the person for which you want to change the password.
3. At the bottom of the dialog box, select Change Password."

No can do.  From both the web interface and the Android app, no "Change Password" option appears.
(Accessing HA via nabu.casa.)

### URL

https://www.home-assistant.io/docs/locked_out/

### Version

2023.11.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by kwagnitz** [comment]
What a useless response to a report that the HA documentation is INCORRECT.
Why bother to have the "[Help us to improve our documentation]" section at the bottom of the page, if you are going to treat documentation feedback like this?  I won't bother in future.

**Comment by klaasnicolaas** [comment]
Sorry to hear that you think it is a useless answer, because we are really trying to help you on your way.

However, the steps in the documentation are correct and therefore I see no reason to make adjustments. Have you checked that Advanced Mode is active and that the account you have is an administrator account?

./Klaas
