### ISSUE TITLE
Away mode

### ISSUE THREAD

**Issue by shaggywolfhound** [home-assistant/home-assistant.github.io#29872]
### Feedback

Is there a way to switch between scheduled mode and off, via an automation?

### URL

https://www.home-assistant.io/integrations/tado/

### Version

2023.11.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
