### ISSUE TITLE
Linksys Smart WiFi documentation out of date?

### ISSUE THREAD

**Issue by bobbeims** [home-assistant/home-assistant.github.io#29871]
### Feedback

It looks like the documentation page has not been updated to reflect changes to the code.

### URL

https://www.home-assistant.io/integrations/linksys_smart/

### Version

2023.11.2

### Additional information

See https://github.com/home-assistant/home-assistant.io/pull/24906

**Comment by frenck** [comment]
Just checked, it does match.

The PR you linked, has been closed (not merged).

../Frenck
