### ISSUE TITLE
How to uninstall Apple iCloud integration? 

### ISSUE THREAD

**Issue by AndySymons** [home-assistant/home-assistant.github.io#29878]
### Feedback

The documentation does not say how to uninstall Apple iCloud integration, and there is no obvious option in the UI

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2023.11.2

**Comment by Quentame** [comment]
Just like any other integration : delete or deactivate the integration config.

![image](https://github.com/home-assistant/home-assistant.io/assets/14821482/9ceaac30-432b-4887-bdac-3653010e3cb3)

**Comment by AndySymons** [comment]
There is no such option for Apple iCloud; that is precisely my point. 
By experiment I found that deleting all the devices makes the integration disappear, but it would be better if it did have the same option as most other integrations (like ESPHome)

**Comment by skotl** [comment]
Agree with Andy. When the integration breaks (which is often) it just shows a "Reconfigure" button and the ... menu has no option to delete.

![image](https://github.com/home-assistant/home-assistant.io/assets/128320/d7da3253-1d40-4196-a004-28aec884203e)

**Comment by Jollyro** [comment]
There is only the documentation option and that is very limited in how to remove the Icloud intergration
<img width="546" alt="Scherm­afbeelding 2024-10-21 om 11 25 40" src="https://github.com/user-attachments/assets/cb518500-d1c5-4de7-a3cc-f4555bbdcadc">

**Comment by mxr** [comment]
You can delete the integration from the 3-dot menu. This is standard across integrations

<img width="1088" alt="image" src="https://github.com/user-attachments/assets/ac1096b5-43ba-4eda-b29f-e56f629e7257">
