### ISSUE TITLE
entity not available

### ISSUE THREAD

**Issue by pc4u** [home-assistant/home-assistant.github.io#29887]
### Feedback

Since a couple of days, the switch.incident_response isn't availble. My automations doesn't work anymore about that issue. I've delete and add it again the fireservicerota integration to my home assistant but it doesn't solved the problem

### URL

https://www.home-assistant.io/integrations/fireservicerota/

### Version

2023.11.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
