### ISSUE TITLE
How to trigger an automation upon a timer finishing

### ISSUE THREAD

**Issue by Fons34** [home-assistant/home-assistant.github.io#29897]
### Feedback

Hi,

Trying to find how to trigger an automation upon a timer  finishing. The GUI does not seem to provide an option for this.

How can one subscribe to the timer finished event? Is it so that the GUI only provides limited functionality and that one needs to code this in yaml? 

Thanks,
Fons.

### URL

https://www.home-assistant.io/integrations/timer/

### Version

2023.11.2

**Comment by frenck** [comment]
This is only available in YAML indeed and is documented on the page you linked/provided feedback on:

![CleanShot 2023-11-20 at 13 27 43@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/f677a820-4289-4046-94a1-fb7607f2844d)

![CleanShot 2023-11-20 at 13 27 50@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/af56280c-775a-4b99-94c4-40b8eb38a8c1)

../Frenck
