### ISSUE TITLE
Other HACS integration for Stiebel Eltron heat pumps needs no MODBUS hardware

### ISSUE THREAD

**Issue by Meyer3** [home-assistant/home-assistant.github.io#29895]
### Feedback

Hi,

I think it might be be worth mentioning that there is another integration that requires no MODBUS hardware. Just use the ISGweb modem (that btw works as MODBUS client now without extra cost software). 
"Stiebel Eltron ISG integration" by @pail23 needs HACs however.

Works great for me.

Regards,
C

### URL

https://www.home-assistant.io/integrations/stiebel_eltron/

### Version

2023.11.2

**Comment by fucm** [comment]
I looks like, the integration of @pail23 needs modbus as well. It does integrate it directly in the component and is not using a library inbetween. As I am not able to maintain my component anymore (modbus can not be active at the same time as the SMA module on the ISG), I would propose, that my component gets replaced in HA with the one of @pail23.

**Comment by Meyer3** [comment]
Stiebel Eltron's ISG web 'LAN modem' now has modbus TCP/IP Slave firmware installed from the factory. (See https://www.stiebel-eltron.de/de/home/service/smart-home/modbus.html)
Older ISG web units can get it with a free firmware update.

I am running @pail23's integration without any modbus hardware on my system. As far as I can see it can read all 85 entities and write all that can be modified.

**Comment by fucm** [comment]
There is no modbus hardware required, but only the software module in the ISG. HA does use modbus over TCP/IP to talk with the ISG. So, at the end of the day, the integration of @pail23 does the same as the current integration.

@home-assistant close

**Comment by frenck** [comment]
Thanks for opening an issue @Meyer3, however, this isn't documentation feedback we can process.

The Home Assistant project does not support, recommend, or endorse the use of custom integrations.

Closing the feedback on this end, as at this point, this isn't actionable for us.

Thanks 👍 

../Frenck
