### ISSUE TITLE
How do I tell if hot water boost has turned on in the hive integration? 

### ISSUE THREAD

**Issue by f1wade** [home-assistant/home-assistant.github.io#29910]
### Feedback

How do I tell if hot water boost has turned on in the hive integration?

I want to pick up if hot water is boosted, but cannot find a sensor or attribute that tells me?

Is there something I can use? 

### URL

https://www.home-assistant.io/integrations/hive/

### Version

2023.11.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
