### ISSUE TITLE
Description of myStrom buttons integration is deprecated

### ISSUE THREAD

**Issue by mschaeuble** [home-assistant/home-assistant.github.io#29911]
### Feedback

The solution described to setup MyStrom buttons using the HA API does not work anymore like this and is therefore deprecated. The reason why this is not working anymore is, that all API call must be accompanied by an authorization header. The MyStrom buttons do not support custom headers.

However, it's possible to integrate MyStrom buttons using HA webhooks. I am able to provide more details how this works if needed.

### URL

https://www.home-assistant.io/integrations/mystrom/

### Version

2023.11.2

**Comment by molofsso** [comment]
Hi!

I am not an expert in these matters. Do you mind giving me a quick walk-through on how you managed to use the webhooks with the myStrom Buttons? I'm guessing you have to disable the actions in the mystrom app once you've configured the webhook right?

Thanks in advance!
