### ISSUE TITLE
Not showing group in HA

### ISSUE THREAD

**Issue by jlogo99** [home-assistant/home-assistant.github.io#29922]
### Feedback

I have two sets of twinkly lights that are grouped together in the twinkly app. 

In HA, the integration makes me add a device set by the IP address so it only add set 1. I have to then add set 2 as a separate device. 

The become independent. How do I add the twinkly group so all my lights act as one device? 

Twinkly firmware is at latest as of Nov 19 2023

### URL

https://www.home-assistant.io/integrations/twinkly/

### Version

2023.11.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
