### ISSUE TITLE
Page content does not match its title ("clickbait")

### ISSUE THREAD

**Issue by sbochnak** [home-assistant/home-assistant.github.io#29935]
### Feedback

I want to see the exact grammar of the sentences in my language (Polish), that should be recognised. Majority is not, and I am not sure if I malform the names of devices or make any other errors. As there is no error reporting whatsoever, I need to consult a definitive source on what should work.

But I am not sure where to find the answer.
The section of the page entitled "View existing sentences", which I hoped answers the question, actually directs me to the test folder. Does it mean that all the cases (sentences) from the test folder should be supported?
Does it mean that no other sentence (and response) is properly formed?

I believe in neither (having looked into the test folder content). But where to look for the currently supported grammar?

### URL

https://www.home-assistant.io/voice_control/builtin_sentences/

### Version

2023.11.2

**Comment by c0ffeeca7** [comment]
Hi @sbochnak. Thank you for reaching out.

- The link there was indeed hidden, and also not pointing to that folder directly, but to a higher level in the project directory. 
- Added a link to the [sentence definitions folder](https://github.com/home-assistant/intents/tree/main/sentences), which also contains a folder for the sentences in Polish.
- The general syntax definitions are described in the [developer docs](https://developers.home-assistant.io/docs/voice/intent-recognition/template-sentence-syntax/)

To answer your question: 

Yes, the sentences in the test folder should be supported. The reason the procedure points to the test folder is that it shows actual examples, and should therefore be easy to read. The variables need to match what you have in your installation of course. So for example, when you use "living room" in your sentence, it needs to be exactly as defined in your areas. 
The sentence definition uses a more technical syntax and might be a bit harder to read.

Hope this helps.
