### ISSUE TITLE
Home Assistant reponds with "You must enable the Google Calendar API in the Google Cloud Console" when adding Google Calendar

### ISSUE THREAD

**Issue by pauldsmyth** [home-assistant/home-assistant.github.io#29945]
### Feedback

After enabling the calendar api on Google and getting the success response on Google, Home Assistant reponds with: 
"You must enable the Google Calendar API in the Google Cloud Console"

### URL

https://www.home-assistant.io/integrations/google/

### Version

2023.11.2

**Comment by allenporter** [comment]
Please follow the integration instructions on the web site to enable Google calendar in the cloud console.

**Comment by judetf** [comment]
I'm having this issue as well. I had the Google calendar integration working perfectly. Then about 2 weeks ago I started getting an error in HA saying "Google Calendars has become Unavailable]" and my calendar stopped showing up. I've been trying to troubleshoot it and eventually went so far as to completely delete the integration and start completely over, generating a new ClientID and private key, but now I get the exact same issue as reported on this thread - I complete the authorization process and then the HA integration reports "You must enable the Google Calendar API in the Google Cloud Console" and I can't get any further. There's nothing else to enable, either in HA or in Google.

Please help! Thanks in advance!
jtf

**Comment by allenporter** [comment]
That is different symptoms from we are discussing here I believe.

Probably your issue is the common one from 2023.11.3 fixed in 2023.12 (released tomorrow)
