### ISSUE TITLE
Heating pump cascade

### ISSUE THREAD

**Issue by wwredeker** [home-assistant/home-assistant.github.io#29943]
### Feedback

The current integration does not allow to monitor and control heating pump cascades (2 or more heating pumps working together). I would love to have this option

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2023.11.2

**Comment by CFenner** [comment]
Meanwhile multiple devices are now supported.

**Comment by CFenner** [comment]
@home-assistant close
