### ISSUE TITLE
When using 2 maps, I have 2 rooms with same id

### ISSUE THREAD

**Issue by driek12** [home-assistant/home-assistant.github.io#29946]
### Feedback

When i have 2 maps, fi down and upstairs, I end up with 2 rooms with the same id, so 2 times 16. 
And 16 means something different based on the chosen map. 

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.11.2

**Comment by tinkerberlin** [comment]
I think this is similar to what I described in another comment.  #27715

**Comment by Lash-L** [comment]
Something I recently found out is that room mapping is actually map specific. You need to change which map you have selected ( easiest to just do it in the app), then call getroom mapping.

**Comment by tinkerberlin** [comment]
Yup. That's how I solved my "problem". It would be great - though potentially impossible - to have HA select the map. But (and that was the point with my earlier "issue") I think there should be a disclaimer to this effect in the documentation. :-)

**Comment by Lash-L** [comment]
I have a selector entity coming hopefully 2024.1 - 2023.12 was already packed with roborock changes. But the entity will allow you to select maps.


> I think there should be a disclaimer to this effect in the documentation. :-)

The change was made as of earlier this week when I figured it out 

>  5. Make sure the map you want the room IDs for is selected in your app. Room IDs are non-unique and will repeat if you have multiple maps.

**Comment by Lash-L** [comment]
Going to close this as it has already been address in documentation and better feature support is coming down the line!

**Comment by Lash-L** [comment]
@home-assistant close

**Comment by tinkerberlin** [comment]
Amazing! thank you @Lash-L !

**Comment by Lash-L** [comment]
And sorry for not seeing your original post @tinkerberlin I get a lot of notifications and I sometimes miss things

**Comment by tinkerberlin** [comment]
No worries. :-)

**Comment by driek12** [comment]
Great, looking forward to the solution, and offcourse currently using the map selection option in roborock app first.

And offcourse thanks for the integration!
