### ISSUE TITLE
integrazione Alexa con Home Assistant

### ISSUE THREAD

**Issue by diegomartoglio77** [home-assistant/home-assistant.github.io#29957]
### Feedback

Buongiorno a tutti,
ho provato ad integrare Alexa a Home Assistant, seguendo in maniera dettagliata la procedura ma, purtroppo non ci sono riuscito.
E' possibile ricevere un aiuto?

Grazie

### URL

http://homeassistant.local:8123/

### Version

2023.11.2

### Additional information

nessuna info aggiuntiva

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). Note that the default language within our community is English 😉 

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
