### ISSUE TITLE
Modify eth0 by end0

### ISSUE THREAD

**Issue by jalejandro0211** [home-assistant/home-assistant.github.io#29969]
### Feedback

Breaking Change: On Arm based boards network names are enumerated based on device tree. This means that the first Ethernet devices will no longer be named eth0 but end0. The network configuration is automatically applied to the new network interface.

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2023.11.3

**Comment by frenck** [comment]
As you pointed out, this indeed is different based on your use board and system.
The example is correct, but like all examples, you need to adjust this to your situation.

../Frenck
