### ISSUE TITLE
Surepet suddenly requires a password

### ISSUE THREAD

**Issue by Zappes** [home-assistant/home-assistant.github.io#29963]
### Feedback

The integration ran nicely for months, but with some upgrade it suddently wanted me to reconfigure it and then asked for some sort of password. Neither the dialog box for that nor the documentation describe what password that might be or how I could configure it in the Surepet hardware.

Please provide some guidance what the integration wants me to enter there.
![grafik](https://github.com/home-assistant/home-assistant.io/assets/6427402/85ba8612-a102-42e7-aa24-256e38c0cd1f)

### URL

https://www.home-assistant.io/integrations/surepetcare/

### Version

2023.11.2

**Comment by klaasnicolaas** [comment]
It should be the password, the fact that there is nothing here now is because something is missing in the integration code

**Comment by Zappes** [comment]
Yes, but _which_ password? My situation is as follows: Both my wife and me have Surepet accounts. Our devices are registered to her account, but she has invited me as a second owner so that I can see the devices in my mobile app. Will I have to ask her for her Surepet account password and enter that? Entering mine didn't work.

**Comment by klaasnicolaas** [comment]
> Yes, but which password?

That will probably be your girlfriend's account if your own account doesn't work 🤷🏻‍♂️ When setting up the integration, you entered a username and password, so you now have to enter the password again for the same username you set earlier.

I have created a PR that adds text to the config flow for re-auth, which also shows which username you used when setting up the integration.

**Comment by Zappes** [comment]
Ah, great, that will definitely help. :)
