### ISSUE TITLE
needs more info

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/home-assistant.github.io#29962]
### Feedback

given URI cannot be reached. Is an user supposed to give their own domain URL? If so, it's not stated in the documentation. Also the flow to register an app has changed, and the documentation doesn't reflect that.

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2023.11.2

**Comment by joostlek** [comment]
Euh, I'm not sure what issue you have, can you maybe explain more?

**Comment by Stooovie** [comment]
Entering the stated callback URI (https://my.home-assistant.io/redirect/oauth) on Withings dev portal returns "Our servers couldn't reach this URL:Partner error: Host Unreachable"

I tried changing the URI to my domain (https://ha.MYDOMAIN.cz/redirect/oauth), getting the same error. Using Nabu casa id, same issue. 

https://ha.MYDOMAIN.cz/auth/external/callback same error. My HA subdomain is publicly reachable, is on HTTPS, has valid cert

**Comment by joostlek** [comment]
If you have the "my" integration enabled you should use the first one. If you don't know what the "my" integration is, you don't have it disabled.

I think you can add that callback URL without clicking on "Test"

**Comment by Stooovie** [comment]
No, while adding the integration and Allowing the app then I get "{"errors":[{"message":"redirect_uri_mismatch: The redirect URI provided is missing or does not match partner callback url"}]}"

**Comment by Stooovie** [comment]
With the default stated URI (https://my.home-assistant.io/redirect/oauth)it does work. That the Test is unsuccesfull but it still works threw me off. Maybe add that to the documentation :) Thanks!
