### ISSUE TITLE
Issue in Growat solar inverter integration.

### ISSUE THREAD

**Issue by aamirfsd** [home-assistant/home-assistant.github.io#29974]
### Feedback

I live in Pakistan and my user name only authenticates on the following location, which is not available in your integration servers.

https://server.growatt.com/

So, please add this server to your integration. becuase all other servers my user authintication gives me errors.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.11.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
