### ISSUE TITLE
Newbie installation

### ISSUE THREAD

**Issue by IanCormack** [home-assistant/home-assistant.github.io#29976]
### Feedback

Maybe you should consider adding the following for first time installers: When the image has been created on the Raspberry PI, insert SD card and startup. The PI will startup to a CLI line, then go to another Computer with a web browser and enter http://homeassistant.local:8123. Make sure the raspberry pi is connect to the same network as the computer browser with and Ethernet cable. Just a thought.

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.11.3

**Comment by c0ffeeca7** [comment]
Thank you for the suggestion, @IanCormack :+1:
