### ISSUE TITLE
Varta pulse neo

### ISSUE THREAD

**Issue by Telemanni** [home-assistant/home-assistant.github.io#29972]
### Feedback

Kann man den VARTA pulse neo per modbus in den homeassistant einbinden?

### URL

https://www.home-assistant.io/docs/energy/faq/

### Version

2023.11.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
