### ISSUE TITLE
Install process could use some clarification

### ISSUE THREAD

**Issue by owendelong** [home-assistant/home-assistant.github.io#29989]
### Feedback

I went through the recommended process using the R.Pi installer for a brand new Pi4B on a SanDisk Extreme 32GB SD card. Wrote the SD card using R.Pi Installer for MacOS using the recommended Home Assistant image.

Am using PoE Hat and have plenty of power available on PoE port of switch (Juniper EX4200-48PX, port is configured to deliver up to 30W (default)). Pi is currently pulling about 4W according to the Juniper.

Took 20+ minutes after enabling PoE before the ethernet port was enabled and system obtained an address.

(PoE Commit on switch was UTC 04:01:51, First ping response 04:22:15)

Even though I can ping it, I'm now at T+40 minutes and the system still shows RPC Portmapper as the only open port (via NMAP from another system). The system has not opened port 8123 yet.

I don't think this is necessarily a problem (though I can't tell yet), but it would be nice to add a note to the documentation explaining how long one should expect to wait for the system to be reachable with an IP address, and then how long it should take before it becomes reachable on port 8123.

I realize that this could likely be different on different hardware and there may be some network dependencies as well, but surely there is some maximum time beyond which one should start troubleshooting and it would be nice if the documentation provided some clue about this.

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

HOME ASSISTANT OS 11.1 (RPI 4/400)

### Additional information

Developers are welcome to reach out to me for further information.

I'm not looking to get this question answered for myself right now so much as looking to have the answers added to the documentation. I realize this isn't the place to ask the question. This is intended as Documentation feedback only.

**Comment by agners** [comment]
There are some initialization done on first start (swap file creation) and the system tries to synchronize the time (and waits up to 90s). But after that, Home Assistant OS ships with a landing page, so even without internet, this should be up and running and respond on port 8123.

In a quick (worst case) test using a Raspberry Pi 4 with 8GB of RAM with HAOS 11.1, connected to a network without Internet, this took exactly 4 minutes for 8123 to be ready and respond.

I think it make sense to document this indeed. If the system doesn't respond by then, I'd try to flash the SD card again, check power supply and maybe also check HDMI output for any clue what could go wrong.

**Comment by c0ffeeca7** [comment]
Thank you for the feedback, @owendelong, and for the details, @agners 
Added a substep to the proceudre

**Comment by owendelong** [comment]
Oddly, a reflash didn't help, but moving it to a network that used NAT instead of my normal (non-NAT) network seems to have resolved the problem.

**Comment by agners** [comment]
Did your non-NAT network had IPv6 only? That would explain it. Otherwise it should work normally, I'd say :thinking:

**Comment by owendelong** [comment]
My non-NAT network is dual-stack... It has IPv4 and IPv6. The IPv6 is from ARIN and the IPv4 is legacy space currently registered as non-contract in the RIPE NCC.
