### ISSUE TITLE
Add wait time to first network and WebPage available to install documentation for Pi.

### ISSUE THREAD

**Issue by owendelong** [home-assistant/home-assistant.github.io#29990]
### Feedback

I went through the recommended process using the R.Pi installer for a brand new Pi4B on a SanDisk Extreme 32GB SD card. Wrote the SD card using R.Pi Installer for MacOS using the recommended Home Assistant image.

Am using PoE Hat and have plenty of power available on PoE port of switch (Juniper EX4200-48PX, port is configured to deliver up to 30W (default)). Pi is currently pulling about 4W according to the Juniper.

Took 20+ minutes after enabling PoE before the ethernet port was enabled and system obtained an address.

(PoE Commit on switch was UTC 04:01:51, First ping response 04:22:15)

Even though I can ping it, I'm now at T+40 minutes and the system still shows RPC Portmapper as the only open port (via NMAP from another system). The system has not opened port 8123 yet.

I don't think this is necessarily a problem (though I can't tell yet), but it would be nice to add a note to the documentation explaining how long one should expect to wait for the system to be reachable with an IP address, and then how long it should take before it becomes reachable on port 8123.

I realize that this could likely be different on different hardware and there may be some network dependencies as well, but surely there is some maximum time beyond which one should start troubleshooting and it would be nice if the documentation provided some clue about this.

### URL

https://www.home-assistant.io/installation/raspberrypi

### Version

HOME ASSISTANT OS 11.1 (RPI 4/400)

### Additional information

Developers are welcome to reach out to me for further information.

I'm not looking to get this question answered for myself right now so much as looking to have the answers added to the documentation. I realize this isn't the place to ask the question. This is intended as Documentation feedback only.

**Comment by c0ffeeca7** [comment]
closing this as it is a duplicate of #29989.
