### ISSUE TITLE
8 speaker system (2x4) missing speakers 5 and 6?

### ISSUE THREAD

**Issue by aussiebish** [home-assistant/home-assistant.github.io#30001]
### Feedback

I have 2xCA4's (linked),and for some reason speakers 5 and 6 are not found. The rest work brilliantly (great code by the way :))

my YAML is as follows:
# Russound Speakers
media_player:
  - platform: russound_rnet
    host: 192.168.1.104
    port: 2401
    name: Russound
    zones:
      1:
        name: Study Speaker
      2:
        name: Laundry Speaker
      3:
        name: Rumpus Speaker
      4:
        name: Bedroom 1 Speaker
      # controller 2 - zone 1 (connected via RNET link ports)
      5:
        name: Living Room Speaker
      6:
        name: Kitchen Speaker
      7:
        name: Patio Right Speaker
      8:
        name: Patio Left Speaker
    sources:
      - name: Ipod
      - name: Radio
      - name: CD
      - name: XM1

### URL

https://www.home-assistant.io/integrations/russound_rnet/

### Version

2023.11.3

**Comment by frenck** [comment]
Hi there @aussiebish 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix an issue in an integration. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
