### ISSUE TITLE
Works well for CHA07 and Wolf Link Pro / # of compressor starts possible to add as entitiy ?

### ISSUE THREAD

**Issue by cray9000** [home-assistant/home-assistant.github.io#30003]
### Feedback

Hi,
Works very well and stable, as stable as the WOLF Cloud solution is ;-)

I ´ve just one enhancement request if it´s may possible to add the two parameters
"# of compressor starts = Verdichterstarts"
and maybe also
the "# of power on / off = Anzahl Netz ein".
available on the WolfCloud Portal (like on the screenshot)

![Wolf_Verdichterstarts](https://github.com/home-assistant/home-assistant.io/assets/65761829/777b0694-509f-4f6c-9a19-b0e484058f19)

### URL

https://www.home-assistant.io/integrations/wolflink/

### Version

2023.11.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
