### ISSUE TITLE
Is there a possibility to place a button on the Todo page that brings it pack to the main page?

### ISSUE THREAD

**Issue by Harrie62** [home-assistant/home-assistant.github.io#30011]
### Feedback

I know that to go back to the main page is to click on the left side menu.
But wouldn't it be nice to bring it back to the main page with a button
![Mainpage](https://github.com/home-assistant/home-assistant.io/assets/77080350/43fa6715-e037-41bf-9a76-bdf7d62ab155)

### URL

https://www.home-assistant.io/integrations/local_todo/

### Version

2023.11.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
