### ISSUE TITLE
include this in the tutorial for Tasmota Integration?

### ISSUE THREAD

**Issue by moswald14** [home-assistant/home-assistant.github.io#30015]
### Feedback

chat-GPT helped me through this so I'm not sure if its appropriate for everyone or its just something I messed up and its makes a vulnerability, but adding these lines to mosquitto.conf /etc/mosquitto/mosquitto.conf got my tasmota devices to start reporting successfully through MTTQ integration to the tasmota integration. It may help other pi noobs out like me.

listener 1883
allow_anonymous true

### URL

https://www.home-assistant.io/integrations/tasmota/

### Version

2023.11.3

**Comment by frenck** [comment]
Hi there @moswald14 👋 

Your feedback is related to Tasmota itself, not the integration. Setting up Mosquitto and Tasmota itself, is considered out of our scope and should be part of the Mosquitto and Tasmota documentation itself.

That said, looking at your solution, I would strongly recommend against using `allow_anonymous true`, you basically disable logins / security with that, opening up your MQTT broker for anyone to connect without authentication.

../Frenck
