### ISSUE TITLE
not valid anymore

### ISSUE THREAD

**Issue by garrathbond** [home-assistant/home-assistant.github.io#30022]
### Feedback

this does not seem to work

### URL

https://www.home-assistant.io/integrations/eufy/

### Version

2023.11.3

**Comment by frenck** [comment]
Hi there @garrathbond 👋 

It seems like you want to report an issue with a Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck

**Comment by garrathbond** [comment]
no the document takes you to invalid links

**Comment by garrathbond** [comment]
Not the case the document takes you to invalid links so doesn’t make any sense

**Comment by frenck** [comment]
> Not the case the document takes you to invalid links so doesn’t make any sense

Right, but you wrote: "this does not seem to work"

Please report what doesn't work, providing error information and steps to reproduce by filing in issue in the linked repository. An integration won't start magically working if we adjust documentation.

Thanks for understanding 👍 

../Frenck
