### ISSUE TITLE
EP25 is no longer supported

### ISSUE THREAD

**Issue by hsrthe4th** [home-assistant/home-assistant.github.io#30027]
### Feedback

Based on [https://github.com/python-kasa/python-kasa#plugs](https://github.com/python-kasa/python-kasa#plugs) and [https://github.com/python-kasa/python-kasa/discussions/548](https://github.com/python-kasa/python-kasa/discussions/548) new version of EP25 aren't compatible with this lib

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2023.11.3

**Comment by detail9** [comment]
Hardware version 2.6 of EP25's still aren't supported and the Home Assistant integration page is causing a lot of confusion. Might be a good idea to update the page until the new EP25's are supported.

**Comment by rytilahti** [comment]
Feel free to create a PR to update the documentation with a mention about that it works only on earlier hw versions. 

The new protocol that is used by the newer devices will be supported in the near future, hopefully by latest in the 2024.2 release.

**Comment by hsrthe4th** [comment]
The doc has been updated with a note about the HW version limits
