### ISSUE TITLE
Probably wrong URL in documentation

### ISSUE THREAD

**Issue by B1ooop** [home-assistant/home-assistant.github.io#30041]
### Feedback

There is probably wrong URL in documentation. There is written https://hooks.nabuca.casa instead of https://hooks.nabu.casa
![image](https://github.com/home-assistant/home-assistant.io/assets/47740064/62ab68af-69d2-4e33-a0ff-ecd3c3d63387)

In configs by URL https://www.nabucasa.com/config/webhooks/ set correct URL https://hooks.nabu.casa
![image](https://github.com/home-assistant/home-assistant.io/assets/47740064/173bbc78-41e8-4378-bd73-6b3df909fb37)

### URL

https://www.home-assistant.io/integrations/smartthings/

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @B1ooop :+1: 
Thank you also for the detailed description. Made it easy to find.
