### ISSUE TITLE
from api.telldus.com to pa-api.telldus.com

### ISSUE THREAD

**Issue by PeterWis** [home-assistant/home-assistant.github.io#30049]
### Feedback

Please take a look at
https://telldus.com/driftinformation/
Are you experiencing disturbances?
For those of you who use api.telldus.com
For some time we have switched from api.telldus.com to using pa-api.telldus.com to improve functionality.

You who have a connection to api.telldus.com through e.g. HomeAssistant or your own solution must redirect to pa-api.telldus.com as soon as possible.

All traffic to api.telldus.com will be shut down shortly.
You who only use Telldus Live! (and Google Home) do not need to do anything.

28/11: Due to very high load on our servers, some users experience problems with Telldus Live! right now. Our technicians are working hard to solve this.

Update: due to continued high load, problems occur again. Our technicians are working hard to solve this. Keep in mind that if you try to connect, for example, HomeAssistant to api.telldus.com, we unfortunately have to block your IP address.

29/11: due to continued high load on our servers during the night, our services continue to go up and down. We are doing everything we can to block the users who cause it and hope everything can work as usual again soon.
Regards Peter

### URL

https://www.home-assistant.io/integrations/tellduslive/

### Version

2023.11.3

**Comment by mase03** [comment]
Seems like there is a DNS error with pa-api.telldus.com

I get this error in the log when I try to add the integration to a new system 

Logger: tellduslive
Source: components/tellduslive/config_flow.py:50
First occurred: 28 november 2023 18:44:14 (4 occurrences)
Last logged: 17:33:45

Failed to retrieve authorization URL: HTTPSConnectionPool(host='pa-api.telldus.com', port=443): Max retries exceeded with url: /oauth/requestToken (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1006)')))

I get this error when I try to access pa-api.telldus.com

Error 1001
Ray ID: 82ddaba4ebd51d1e •
2023-11-29 20:41:16 UTC
DNS resolution error

**Comment by PeterWis** [comment]
It seems they are done troubleshooting, and the issue remains when I try to add telldus I get
Unknown error generating an authorized URL.
https://telldus.com/driftinformation/

You who have a connection to api.telldus.com through e.g. HomeAssistant or your own solution must redirect to pa-api.telldus.com as soon as possible.

Dns point,s to
C:\Windows\System32>ping -t pa-api.telldus.com
https://telldus.com/driftinformation/
Pinging telldus.com [141.193.213.11] with 32 bytes of data:
Reply from 141.193.213.11: bytes=32 time=9ms TTL=56
Reply from 141.193.213.11: bytes=32 time=9ms TTL=56
Reply from 141.193.213.11: bytes=32 time=7ms TTL=56
Regards PeterW
________________________________

**Comment by fredrike** [comment]
This is not the integrations fault..

**Comment by fredrike** [comment]
@home-assistant close

**Comment by jonasbjurel** [comment]
It appears that Telldus have disabled support for TLS 1.0, this is likely the cause that the SSL negotiation fails. Any way to configure TLS 1.2 as the default version?

**Comment by jonasbjurel** [comment]
Im attaching a pcap trace:
[telldus2.zip](https://github.com/home-assistant/home-assistant.io/files/13562224/telldus2.zip)

**Comment by jonasbjurel** [comment]
@ ssllabs.com you will find out what telldus supports in terms of protocol versions and Ciphers.
