### ISSUE TITLE
Link to the software for LiteJet is bad

### ISSUE THREAD

**Issue by TopoTop1** [home-assistant/home-assistant.github.io#30044]
### Feedback

Hello,

I noticed that this link to the software isn't any good anymore. I have found a new link:
https://centralitelegacylighting.com/wp-content/uploads/2022/12/LiteJet_Programming_Software_v2.01.02.zip

Hope this helps!

### URL

https://www.home-assistant.io/integrations/litejet/

### Version

2023.11.3

**Comment by joncar** [comment]
Definitely worth updating that link. But we should update it to link to the programs on this site: https://www.dragontechinc.com. That is run by the original founders of Centralite and they bought the remains of the LiteJet business.

**Comment by TopoTop1** [comment]
This is great news, thank you!

I am trying to get this connected to my litejet 48 but can't get the serial
connection to work.

I am using a Global Cache GC100 to connect.

I'm using this code in the "port" field in your integration one intake on
HA: 'socket://<host>:<port>'

This integration fails to connect, however. Suggestions?

**Comment by TopoTop1** [comment]
Hi John, Any Idea why I am getting this error?  Sent from Mail for Windows From: Jon CaruanaSent: Tuesday, November 28, 2023 10:49 PMTo: home-assistant/home-assistant.ioCc: TopoTop1; AuthorSubject: Re: [home-assistant/home-assistant.io] Link to the software for LiteJet is bad (Issue #30044) Definitely worth updating that link. But we should update it to link to the programs on this site: https://www.dragontechinc.com. That is run by the original founders of Centralite and they bought the remains of the LiteJet business.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by TopoTop1** [comment]
Hi John, Any Idea why I am getting this error? 

![Screenshot_20231129_040035](https://github.com/home-assistant/home-assistant.io/assets/152359027/0b337630-3a73-4bd1-af7b-1c6e43ccd232)

**Comment by klaasnicolaas** [comment]
Because what you entered is incorrect, it asks for a port not a full URL

**Comment by joncar** [comment]
No, that's fine. pyserial (which is what this is ultimately going into) accepts that. I use it the same way with the MCP connected to a Pi and Home Assistant running in a VM.

@TopoTop1 First thing I'd do is check that your serial setup and the serial to network setup is working right. If you connect to it via telnet/putty/etc, does it work? Typing "^L001" (without the quotes) should respond with the first load's name. Does that work?

Second thing we need to consider is you have the 48 load model, but the integration has only been developed/tested with the 24 load model. IIRC the protocol is identical for the first 24 loads so it should be connecting okay. But you won't be able to access the second 24 unless we add support for that to pylitejet and Home Assistant.

**Comment by TopoTop1** [comment]
That's awesome news Jon.

What are the chances of you updating it for the 48? My lights are all over
the place abs runs span different panels. Having only support for 24 would
make it hard to integrate.

Also, I do get a response from the global cache test app and it did return
load 1 in the test app.

I have the monoprice 6 channel amp on the other serial port wth home
assistant wiring well.

**Comment by joncar** [comment]
Yes, I can add that support if you can help by testing it. Can you create an issue in the https://github.com/joncar/pylitejet project? Let's start by figuring out why it doesn't like to show the first 24 loads which should be working as-is.

Please include the output of test:
```
git clone https://github.com/joncar/pylitejet
cd pylitejet
python3 ./test.py -v --path socket://<host>:<port> list -l -s -b
```
