### ISSUE TITLE
V2C website link is broken

### ISSUE THREAD

**Issue by codyc1515** [home-assistant/home-assistant.github.io#30057]
### Feedback

> The V2C integration allows monitoring and control of a local [V2C](https://v2c.com/) Trydan EVSE in Home Assistant.

The V2C website link does not load for me (get an HTTPS error).

### URL

https://www.home-assistant.io/integrations/v2c/

### Version

2023.12.0

**Comment by c0ffeeca7** [comment]
V2C is in beta. In te meantime (until the release next week), you can view the page here: https://rc.home-assistant.io/integrations/v2c

**Comment by codyc1515** [comment]
I’m well aware of that and not talking about HA. I’m talking about the link in the documentation. It does not work.

![IMG_1398](https://github.com/home-assistant/home-assistant.io/assets/50791984/6cdd8380-a08f-4d11-9f6c-5a14748eef46)

**Comment by c0ffeeca7** [comment]
oh dear, my bad. Thank you for the catch. Let me fix that.
