### ISSUE TITLE
Request support for Node sensors

### ISSUE THREAD

**Issue by pjrish** [home-assistant/home-assistant.github.io#30075]
### Feedback

Requesting support for the Thermoworks Node line, probe3, humidity, and ambient conditions.  Thanks!

### URL

https://www.home-assistant.io/integrations/thermoworks_smoke/

### Version

2023.11.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
