### ISSUE TITLE
Humidity would be nice

### ISSUE THREAD

**Issue by EyalBenisty82** [home-assistant/home-assistant.github.io#30071]
### Feedback

I love the layout of the thermostat. I use it with Tado integration.
Would be nice to be able to also see the humidity of the room insite or underneath
![image](https://github.com/home-assistant/home-assistant.io/assets/151018397/e32e1936-4e35-469d-a9d2-40823a3a029f)

### URL

https://www.home-assistant.io/dashboards/thermostat/

### Version

2023.11.3

**Comment by dannytsang** [comment]
Thanks for your suggestion. Please raise this in **New issue** > **Feature Request**.
