### ISSUE TITLE
vdi file isn't accepted as an ISO image.

### ISSUE THREAD

**Issue by SKelem** [home-assistant/home-assistant.github.io#30085]
### Feedback

I'm working off the instructions at https://www.home-assistant.io/installation/linux/, under the section for VirtualBox. The 1st & 2nd steps say to create a virtual machine. When I start Virtualbox 7.0, I get a window shown in the first attachment. It wants a .iso file. Your step 3 says to use the vdi file, but it's not accepted in the ISO image field.

If I click on Expert Mode, I can set the Hardware to use 2048MB and 2 CPUs. (see image)

If I then click on Hard Disk, and then "Use an Existing Virtual Hard Disk File". (see image) Then I selected the haos_ova-11.1.vdi file

The virtual machine is then "created". However, when I try to start it, I get a popup saying "No bootable medium found! Please insert a bootable medium and reboot."

No bootable media found! Please insert a bootable medium and reboot.

Any idea of how to install home-automation in virtualbox?

Machine info:
```
% cat /proc/info (showing info for only one of the 4 cores)
processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 61
model name	: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
stepping	: 4
microcode	: 0x2f
cpu MHz		: 500.000
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap intel_pt xsaveopt dtherm ida arat pln pts vnmi md_clear flush_l1d
vmx flags	: vnmi preemption_timer invvpid ept_x_only ept_ad ept_1gb flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest ple
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds mmio_unknown
bogomips	: 6185.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```

### URL

https://www.home-assistant.io/installation/linux/

### Version

11.1

### Additional information

![HA-vb-01](https://github.com/home-assistant/home-assistant.io/assets/599385/d3b20f05-1c04-4fdb-a784-71d6cc3a4b04)
![HA-vb-02](https://github.com/home-assistant/home-assistant.io/assets/599385/797b56c5-9a28-48e2-a4d0-b22369847bf6)
![HA-vb-03](https://github.com/home-assistant/home-assistant.io/assets/599385/8ff9c7f2-7900-4c94-a94b-368348f1e7eb)
![HA-vb-04](https://github.com/home-assistant/home-assistant.io/assets/599385/77fd5172-1075-4dac-9406-1b1692fbf733)

**Comment by agners** [comment]
@SKelem the guide looks outdated indeed 😢 The problem can be explained when step 4 has been skipped. Not sure if you can select EFI boot maybe in the Hardware of the dialog? 🤔

**Comment by c0ffeeca7** [comment]
Hi, @SKelem
Thank you for reaching out and providing these detailed step descriptions and screenshots. They are very helpful.
I will update the procedure to work with Version 7.0.

About your issue:
1. when you check under the **System** settings, is **enable EFI** selected?
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/7c91b01d-74f1-4844-9e69-c33608ffd775)

I can reproduce your issue when this is deselected.
2. If it was deselected in your setup: Could you select it and try again?
