### ISSUE TITLE
中国区appleID无法添加集成

### ISSUE THREAD

**Issue by wskuiy** [home-assistant/home-assistant.github.io#30087]
### Feedback

中国区appleID无法添加集成，可以接收到来自手机的登录请求和验证码，但是homeassistant端报错，无法成功该集成

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2023.11.3

**Comment by Quentame** [comment]
Hi !
You have to speak English on all HA repositories.
If you don't at least use a translator.
Thanks

**Comment by Quentame** [comment]
Translation:

Apple ID in China cannot add integration. It can receive the login request and verification code from the mobile phone, but the homeassistant side reports an error and the integration cannot be successful.

**Comment by Quentame** [comment]
So you have to create the issue in the core repo and provide related logs.
