### ISSUE TITLE
Growatt and other solarpanels visible in homewizard > port to home assisant

### ISSUE THREAD

**Issue by dagoosemusic** [home-assistant/home-assistant.github.io#30093]
### Feedback

would it be possible to also integrate the solarpanels like Growatt, enphase etc which can be added as a meter in Homewizard to be also visble in home assistant? 

### URL

https://www.home-assistant.io/integrations/homewizard/

### Version

2023.11.3

**Comment by DCSBL** [comment]
Hey @dagoosemusic, thanks for the idea! The issue tracker is not for feature request, please ask this question at https://community.home-assistant.io/

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
