### ISSUE TITLE
Weatherflow Forecast

### ISSUE THREAD

**Issue by designedcustom** [home-assistant/home-assistant.github.io#30105]
### Feedback

Can we work to combine the HACS version and this so that we have a core version that has forecast?
Topic on this: https://github.com/briis/hass-weatherflow/issues/87#issuecomment-1738955349
Forecast: https://github.com/briis/weatherflow_forecast

### URL

https://www.home-assistant.io/integrations/weatherflow/

### Version

2023.11.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
