### ISSUE TITLE
Fan speed in an automation

### ISSUE THREAD

**Issue by Cingar01** [home-assistant/home-assistant.github.io#30102]
### Feedback

Is there a way to set the fan speed in an automation. As it is right now its only on or off at the lowest speed.

### URL

https://www.home-assistant.io/integrations/fjaraskupan/

### Version

2023.11.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
