### ISSUE TITLE
Recovering username

### ISSUE THREAD

**Issue by paul71219** [home-assistant/home-assistant.github.io#30116]
### Feedback

When I onboarded to my Home Assistant Green, I created a login, and then nearly immediately applied the pending update. Then when I tried to log in again, I couldn't. I tried using the console/terminal to recover (by connecting a keyboard & monitor), but `auth reset` told me it didn't recognize the username. My best guess is I mistyped my username, but I couldn't find any way to learn what users HA knew about, so I'm having to reset & onboard again! It would be nice if there were a way to list the known users from the terminal.

### URL

https://www.home-assistant.io/docs/locked_out/

### Version

2023.11.3

**Comment by cogneato** [comment]
While there is not a custom command for listing users, you can find those by using entering `login` to get to the host console, and then using
 `cat /mnt/data/supervisor/homeassistant/.storage/auth_provider.homeassistant`

This file contains the users for HA, then you can make note of the username that you found, and use `ha auth reset`

**Comment by c0ffeeca7** [comment]
For Home Assistant Operating System, there is now a new command that lets you list all the users.
<https://github.com/home-assistant/home-assistant.io/pull/31932>
