### ISSUE TITLE
outdated installation steps

### ISSUE THREAD

**Issue by ctodor** [home-assistant/home-assistant.github.io#30128]
### Feedback

outdated installation steps. for a new user is very frustrating to follow your steps (or try to, because it is not possible) just from the begining and after that he must search for solution
https://community.home-assistant.io/t/installing-home-assistant-on-vmware-player-17/570428
these are correct steps to install HA on win10. at leaset add this link on your "how to" page

### URL

https://www.home-assistant.io/installation/windows/

### Version

2023.11.3

**Comment by c0ffeeca7** [comment]
Thank you for reaching out and providing the link to the updated procedure, @ctodor :+1:
