### ISSUE TITLE
suggestion for improved error message

### ISSUE THREAD

**Issue by steve1066d** [home-assistant/home-assistant.github.io#30125]
### Feedback

I had my bluetooth adapter disabled, and the error message when I tried to install was "no devices found".  It would be helpful to indicate what the issue was.

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2023.11.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
