### ISSUE TITLE
Switchbot Lock

### ISSUE THREAD

**Issue by grzestel** [home-assistant/home-assistant.github.io#30126]
### Feedback

Is there any  chance to add Cloud integration with Switchbot lock conneected by minihub?

### URL

https://www.home-assistant.io/integrations/switchbot_cloud/

### Version

2023.11.3

**Comment by SeraphicRav** [comment]
@grzestel 
Thank you for reaching out. GitHub is used for tracking issues, not for providing support or tracking feature requests. There is a chance that it becomes supported if someone is interested in implementing this feature.

If you want to suggest a feature, you should try our Community Forum: [Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks!

**Comment by SeraphicRav** [comment]
@home-assistant close
