### ISSUE TITLE
Aftership affiliation disclaimer query

### ISSUE THREAD

**Issue by FletcherAU** [home-assistant/home-assistant.github.io#30141]
### Feedback

It seems odd to include this disclaimer in the docs for AfterShip when it's not present on every other unaffiliated integration. (Happy to PR if it seems like this should be removed)
https://github.com/home-assistant/home-assistant.io/blob/9b200cc14e8258c2fecfa0b1293cd661d7f87162/source/_integrations/aftership.markdown?plain=1#L49

### URL

https://www.home-assistant.io/integrations/aftership/

**Comment by frenck** [comment]
Some external parties require such things. We can remove it, if that isn't the case.

Closing the issue on this end, as it is a question and not an issue. Please use our Discord channels for such purposes 👍 


../Frenck
