### ISSUE TITLE
Switchbot sensors? hub 2 scenes triggers? Hub 2 temperature and humidity? other temperature sensors?

### ISSUE THREAD

**Issue by sebastienbo** [home-assistant/home-assistant.github.io#30158]
### Feedback

I'm  missing al the devices of my switchbot installation (hubs/thermometers, motion sensor, door sensor,blinds, curtain 3 etc..)

### URL

https://www.home-assistant.io/integrations/switchbot_cloud/

### Version

2023.11.3

**Comment by SeraphicRav** [comment]
@sebastienbo
Thank you for reaching out. GitHub is used for tracking issues, not for providing support or tracking feature requests. As written in the documentation, the mentioned devices are not supported for the moment.

If you want to suggest a feature, you should try our Community Forum: [Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks!

**Comment by SeraphicRav** [comment]
@home-assitant close

**Comment by SeraphicRav** [comment]
@home-assistant close
