### ISSUE TITLE
Home assistant for raspi5

### ISSUE THREAD

**Issue by kiukiun** [home-assistant/home-assistant.github.io#30157]
### Feedback

Hi, 

at the home assistant setup for raspi5 there is not yet available documentation or instructions for raspi5. While I tried to make the raspi5 images there was not an option for selecting: Other specific-purpose OS > Home assistants and home automation > Home Assistant..

what would be the workaround for that situation or eatimation when to get it working also for raspi5 and not only 4&3?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2023.11.3

### Additional information

Images for raspi5 that works with HA

**Comment by frenck** [comment]
More information here: <https://www.home-assistant.io/blog/2023/10/17/expected-support-for-raspberry-pi-5/>


../Frenck
