### ISSUE TITLE
Help file doesnt include UI version, only YAML

### ISSUE THREAD

**Issue by shallowal** [home-assistant/home-assistant.github.io#30162]
### Feedback

Trying to create a helper template for a sensor. The UI asks for a "State Template*" but I dont know what it expects there. The help page doesnt show any examples of a UI, only YAML, yet the HA configuration doesnt have an option to create it with a YAML file. 

### URL

https://www.home-assistant.io/integrations/template/

### Version

Version 2023.11.3

**Comment by frenck** [comment]
> The UI asks for a "State Template*" but I dont know what it expects there.

It expects a template, as documented here (and linked from the page you commented on):

https://www.home-assistant.io/docs/configuration/templating/

../Frenck

**Comment by shallowal** [comment]
Thanks for the answer Franck,
I'm accessing the templates (I think) by going to
Settings/Integration/Helpers/Create Helper/Template/Template A Sensor
But I still have no idea what I'm supposed to put there. The page you
linked to is all to do with YAML configuration files, not the UI. Is there
an example anywhere of what a completed UI page is supposed to look like?.
I've ended up following a video on creating the templates as a YAML script

rgds
Allan
