### ISSUE TITLE
License plate detection not detected

### ISSUE THREAD

**Issue by davey400** [home-assistant/home-assistant.github.io#30168]
### Feedback

I am using an AI Theta in an external case. It is therefore capable of recognizing vehicles (don't have many of them indoors) and license plates. 
License plate detection is far from perfect, but it works sometimes. 
The detections are shown in Protect, but most of the times they do not show up in the HA integration.

I do not know if this is because of the length of the detection itself, but are willing to change things if needed. 

Best regards,
Dave

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2023.11.3

**Comment by klaasnicolaas** [comment]
Hi there👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
