### ISSUE TITLE
Add option to delete tasks from list.

### ISSUE THREAD

**Issue by omakoti** [home-assistant/home-assistant.github.io#30175]
### Feedback

Add option to delete tasks from list.

### URL

https://www.home-assistant.io/integrations/google_tasks/

### Version

2023.11.3

**Comment by allenporter** [comment]
Hi, GitHub issues are not the right place for feature requests. Those belong in the community forum.

However, you are in luck as this feature is landing in 2023.12 releasing tomorrow
