### ISSUE TITLE
adding working time

### ISSUE THREAD

**Issue by strzegus** [home-assistant/home-assistant.github.io#30179]
### Feedback

How to add working time so that the thermostat allows it to be turned on only between 10 p.m. - 6 a.m. and 12 p.m. - 4 p.m.

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

### Version

2023.11.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
