### ISSUE TITLE
This card needs to be updated as todo-list card or a new entry added for todo-list card

### ISSUE THREAD

**Issue by scstraus** [home-assistant/home-assistant.github.io#30186]
### Feedback

Hi there, it seems in the latest version, you have switched to todo-list card, but there's no documentation for this card which made it very hard to figure out why my shopping list card stopped working and what to do to fix it (especially since I use YAML mode)..

It seems that you either need to replace this page with to-do list card or make a new one for to-do list card.

### URL

https://www.home-assistant.io/dashboards/shopping-list/

### Version

2023.12.0

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @scstraus :+1: 
Closing this as addressed by https://github.com/home-assistant/home-assistant.io/pull/31985.
