### ISSUE TITLE
No documentation for new get_forecasts service

### ISSUE THREAD

**Issue by mikeodr** [home-assistant/home-assistant.github.io#30184]
### Feedback

Got a `repair` notification in home assistant to migrate to the new `get_forecasts` service call but no documentation for the new service exists.

### URL

https://www.home-assistant.io/integrations/weather

### Version

2023.12.0

### Additional information

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/weather.markdown?plain=1#L73-L92

Seems to not be updated.

**Comment by mikeodr** [comment]
Link in the `Backwards incompatible changes` takes one to the old service example:
https://www.home-assistant.io/blog/2023/12/06/release-202312/#backward-incompatible-changes

**Comment by c0ffeeca7** [comment]
Thank you for picking this up @mikeodr :+1:
