### ISSUE TITLE
Older Axis camera

### ISSUE THREAD

**Issue by stwm** [home-assistant/home-assistant.github.io#30180]
### Feedback

Hello,
I have an older Axis 215 PTZ network camera.
Is there any change to intergrate this into a repository?
there is no current firmware by the manucatorer.
Thank you very much.
The camera was found, thats all.

### URL

https://www.home-assistant.io/integrations/axis/

### Version

2023.11.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
