### ISSUE TITLE
Combine entities in one Tile

### ISSUE THREAD

**Issue by quangbach0299** [home-assistant/home-assistant.github.io#30191]
### Feedback

Can you provide a code to describe how to combine entities in one Tile. Because when i use xiaomi intergration it can combine moving button fanspeed and normal mode in my homekit app. When i use zigbee2mqtt to add 4 gang switch it just have 4 seperate button in home app and i really dont like it. It take many space in home app. When 4 have 100 gang switch it will have 400 button to many to control.

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2023.12.0

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
