### ISSUE TITLE
Redirect URI instructions incorrect

### ISSUE THREAD

**Issue by sneakinhysteria** [home-assistant/home-assistant.github.io#30198]
### Feedback

The instructions for users who don't use the Nabu Casa service are incorrect. The redirect URI that needs entering into the Neato Developer integration has to be https://my.home-assistant.io/redirect/oauth no atter what your actual public, SSL enabled HA URL is. Your own URL then needs updating in the appearing redirect screen. 

### URL

https://www.home-assistant.io/integrations/neato/

### Version

2023.12.0

### Additional information

n/a

**Comment by frenck** [comment]
Hi there @sneakinhysteria 👋 

I've reviewed the instructions and concluded they are correctly documented.

> The instructions for users who don't use the Nabu Casa service are incorrect

This feature is not related if you are a user/client of the services provided by Nabu Casa.
As the page tells in those settings, it is related to enabling/disable the My Home Asisstant integration. That section thus only applies to users we have disabled it.

../Frenck
