### ISSUE TITLE
attempting to change user password with auth in the terminal does not succeed

### ISSUE THREAD

**Issue by CaptClaude** [home-assistant/home-assistant.github.io#30190]
### Feedback

We are advised to use the command 
``auth reset --username existing_user --password new_password``
This fails with the error ``zsh: command not found: auth``

### URL

https://www.home-assistant.io/docs/locked_out/

### Version

2023.12.0

### Additional information

I am not experienced enough to know whether the HA updates made the command obsolete or whether there was something else I was supposed to do first.

**Comment by CaptClaude** [comment]
Hi @c0ffeeca7 
I'm not used to getting responses so quickly.
Yes, I have seen an Enigma machine - in fact, I've seen two different ones.
Be warned: I am a "new" user but familiar with *inux & stuff like that. In case it matters, my HA instance is running inside Proxmox on a repurposed thin client.
The auth command was entered using the Terminal that is in the sidebar of my Overview. I have the "Advanced SSH & Web Terminal" installed so that's what I used.
Now that I review what I did (it's still in the terminal window), I also typed ``man auth`` and was rewarded with ``zsh: command not found: man`` which seems to be symptomatic of something related to how my terminal is working rather than some fundamental issue inside of HA.

**Comment by c0ffeeca7** [comment]
so you are still logged in? then you could add yourself as a [new admin](https://www.home-assistant.io/docs/locked_out/#home-assistant-including-supervised)?

**Comment by CaptClaude** [comment]
@frenck I do not consider this completed because the question was not whether I could add an additional user. The question, as stated in the original post was that the guide advises us to use a command in the terminal which returns an error of `command not found` - my issue is _**why**_ does the guide tell us to do this?  If the guide is correct and there is something wrong with my setup, the question becomes _**how do I fix it?**_. If the advice is to open a new issue, that's fine, but marking it finished does not strike me as correct.

**Comment by c0ffeeca7** [comment]
I didn't realize you wanted to reset the PW for the owner, hence my question about the admin.
the `zsh` in the error indicates that one is using the terminal from WITHIN Home Assistant. 
But you need to use the terminal from the device itself. In your case the virtual machine console.

I've updated the procedure to indicate this more clearly.

![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/04c596c3-5045-4de2-880b-08d2ce2cfb63)

**Comment by CaptClaude** [comment]
@c0ffeeca7 I appreciate your following up and giving me a hand with this.
Following your instructions to log in from the HA CLI (accessible in the HA VM in Proxmox - hassos 11.1), I am told that the syntax is slightly different:
`authentication reset --username "existing_username" --password "new_password"`
The quotes are apparently required.
Thanks again.
