### ISSUE TITLE
Link not valid and no info on how to add integration to configuration.yaml

### ISSUE THREAD

**Issue by ticstyle** [home-assistant/home-assistant.github.io#30207]
### Feedback

When trying to add integration in HA one is provided with the option to open documentation. The problem is that the link doesnt work (https://www.home-assistant.io/integrations/our-groceries) and the integration info page doesnt explain how to install the integration.

### URL

https://www.home-assistant.io/integrations/ourgroceries/

### Version

2023.12.0

**Comment by OnFreund** [comment]
Did you set up mylinks to point to your HA instance?
https://www.home-assistant.io/integrations/my

**Comment by frenck** [comment]
@ticstyle Which version of Home Assistant are you running?

**Comment by ticstyle** [comment]
> Did you set up mylinks to point to your HA instance? https://www.home-assistant.io/integrations/my

Yes

**Comment by ticstyle** [comment]
> @ticstyle Which version of Home Assistant are you running?

2023.12.0

**Comment by OnFreund** [comment]
And do other my links work?

**Comment by ticstyle** [comment]
> And do other my links work?

Yes, they do, ill do a test right now and get back to you

**Comment by ticstyle** [comment]
> > And do other my links work?
> 
> Yes, they do, ill do a test right now and get back to you

Yep, https://www.home-assistant.io/integrations/cast/ works fine with the add to my home assistant button

**Comment by ticstyle** [comment]
I remembered that i had added the Our Groceries integration available in HACS, removed that and restarted home assistant. Now I can add tis integration 👍
Sorry that I didnt think to check that first

**Comment by OnFreund** [comment]
Thanks for the update!

**Comment by OnFreund** [comment]
@home-assistant close
