### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by gitjoob** [home-assistant/home-assistant.github.io#30201]
### Feedback

After updating to 2023.12.0 I can only login via phone app, web page sys "Something went wrong"

### URL

https://www.home-assistant.io/docs/authentication/

### Version

2023.12.0

**Comment by frenck** [comment]
Hi there @gitjoob 👋 

It seems like you are experiencing an issue with Home Assistant, however, you have submitted documentation feedback instead.

If you like to report an issue, please report one here: <https://github.com/home-assistant/core/issues>

In case you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
