### ISSUE TITLE
Add Mikrotik tg_bt5_out to the list of working iBeacons

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#30209]
### Feedback

Well this Mikrotik TG-BT5-OUT heavy-duty tag is also being detected by HA. Too bad that also with this quality device (like the other Mikrotik and Teltonika) for a nice prize that the readings (temperature, accelerometer) don't work. But what does work is:
-Tracker (home/away)
-Estimated distance
-Signal strength

### URL

https://www.home-assistant.io/integrations/ibeacon/

### Version

2023.12.0

### Additional information

https://mikrotik.com/product/tg_bt5_out

**Comment by wrt80** [comment]
Also works with IN version: https://mikrotik.com/product/tg_bt5_in
