### ISSUE TITLE
Problème accès Google

### ISSUE THREAD

**Issue by Fred-Lube** [home-assistant/home-assistant.github.io#30216]
### Feedback

Accès bloqué : Home assistant n'a pas terminé la procédure de validation de Google
Home assistant n'a pas terminé la procédure de validation de Google. L'appli est en cours de test, et seuls les testeurs approuvés par le développeur y ont accès. Si vous pensez que vous devriez y avoir accès, contactez le [développeur](https://accounts.google.com/).
Si vous êtes un développeur de Home assistant, consultez les [détails de l'erreur](https://accounts.google.com/).
Erreur 403 : access_denied

### URL

https://www.home-assistant.io/integrations/google/

### Version

2023.12.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
