### ISSUE TITLE
Formovie s5 support 

### ISSUE THREAD

**Issue by rhuanrlima** [home-assistant/home-assistant.github.io#30219]
### Feedback

The integration is amazing, super useful, the only way I found to integrate my formovie s5 to home assistant, but unfortunately it's not on compatible list, I tried various options but none seems to work, this would be such a great improvement as chineses mijia products can't barely integrate with Alexa and Google home 

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2023.12.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
