### ISSUE TITLE
yeelink.light.ceiling5

### ISSUE THREAD

**Issue by darovskikhav** [home-assistant/home-assistant.github.io#30223]
### Feedback

Please add support yeelink.light.ceiling5

### URL

https://www.home-assistant.io/integrations/yeelight/

### Version

2023.12.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
