### ISSUE TITLE
Should "Application Type" be set to "Web Application" or "TVs and Limited Input devices"

### ISSUE THREAD

**Issue by ConnorBrockbank** [home-assistant/home-assistant.github.io#30224]
### Feedback

Hi, I have noticed that the official guide says to set the application type of the OAuth client ID to web application but many other guides say to use TVs and Limited Input devices.

I'm sure there is something else I am doing wrong but when I used web application, Home Assistant give me an error "Received invalid token data."

But when I use TVs and Limited Input devices I can make the connection as expected but my main calendar doesn't work. Only the Family calendar and Holiday calendars get brought in to Home Assistant. My main calendar shows "Unavailable" and never makes a connection.

I'm wondering if one of these methods are more correct or if they do slightly different things and it just isn't clear what they do.

Thanks for the input,
Connor

### URL

https://www.home-assistant.io/integrations/google/

### Version

2023.12.0

**Comment by allenporter** [comment]
@ConnorBrockbank in this release, I changed the default to support web like all other google integrations (only calendar previously supported the TV input thing).  

This sounds like a bug. Can you file an issue in the core and fill out the full issue template?  Both should work fine, so we really have two separate issues here (with different setups to setup and re-create -- we should track them separately and work with you to diagnose). If you are switching credentials make sure they are also switched here in application credentials: https://www.home-assistant.io/integrations/application_credentials/

**Comment by ConnorBrockbank** [comment]
Thanks Allan, I'll submit those two issues in the next few days.

-Connor
