### ISSUE TITLE
Suggestion:  add supported devices to documentation

### ISSUE THREAD

**Issue by msladen** [home-assistant/home-assistant.github.io#30232]
### Feedback

There seem to be a lot of models of Yardian Pro Smart Sprinkler Controllers available.
It would help users to know what model numbers this automation was tested with and which are believed to work with the automation.  

### URL

https://www.home-assistant.io/integrations/yardian/

### Version

2023.12.1

### Additional information

Thanks, Marty Sun, for your contribution to Home Assistant.

I am working on putting together an irrigation system this coming spring, and would like to start pulling together the pieces I need.
I see several of the newer Aeon Matrix Yardian sprinkler controllers have the HA logo on them.  Is this required, or is it possible to user on any Yardian Pro (e.g, PRO1902)?  I assume you developed on a device that did not have the HA logo on it... what did you use?  I see a lot of value-priced controllers on ebay, but I am afraid of buying them if they are not supported.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by h3l1o5** [comment]
Hi @msladen 

Technically the yardian integration supports all YardianPro model (**PRO1600, PRO1602, PRO1900, PRO1902, PRO1906**), but only few of them are tested.

I will test the rest of them and update the documentation as soon as there is enough resource for me.
Thanks for the suggestion.

Marty.
