### ISSUE TITLE
Lightwave integration document tweak

### ISSUE THREAD

**Issue by FredsterCode** [home-assistant/home-assistant.github.io#30235]
### Feedback

Re the lightwave integration documentation. https://www.home-assistant.io/integrations/lightwave
It’s proving difficult to translate the example yaml file edit to a user situation. 
There is a reference to the ID of items. 
“ The id takes the form R#D# where R# is the room number and D# is the device number.” 
This needs expanding on or a couple of real world examples given. Room number and Device number are not self evident identifiers in the Lightwave app. I have string type room names and similar location names for switches etc.  As yet I haven’t managed to find/create an ID that works. 
Eg “Downstairs zone Under stairs lamp1“
Possibly the white space is an issue or integers are a requirement. ? 

Looking for possible short term easy solutions, could the needed IDs be exposed in some work around such that they can be manually copied into the yaml?  This could be with a process of initially editing the yaml and adding the example. Saving, restarting to apply changes, finding a LightwaveDiscovery device or entity and copying from a discovery list back into the yaml with correct IDs.   My very crude understanding of the code suggest it is doing such a discovery. So it just needs to be exposed.

Thanks for your time on this. 

### URL

https://www.home-assistant.io/integrations/lightwave/

### Version

2023.12.1

**Comment by stiltjack** [comment]
> This needs expanding on or a couple of real world examples given. Room number and Device number are not self evident identifiers in the Lightwave app. I have string type room names and similar location names for switches etc. As yet I haven’t managed to find/create an ID that works.

"Not self evident" is putting it mildly. 

I don't think the names you have given to the rooms/devices in the Lightwave app are relevant. As I remember from my Lightwave days (moved to Zigbee now) the numbers refer simply to the order in which rooms and devices were originally added to the app. So the first room was named R1 and the first device in that room D1. 

Ideally one would create devices in the Lightwave app and in Home Assistant at the same time, one by one. But (having set up Lightwave some time before I started with HA) I can remember creating device R1D1 in HA, then wandering round the house to see which light turned on and off when I toggled it, and naming the device in HA accordingly. You can establish which room is which quite quickly, but identifying devices depends on how systematic you were in installing them.
