### ISSUE TITLE
Energy dashboard time periods

### ISSUE THREAD

**Issue by craigsbits** [home-assistant/home-assistant.github.io#30237]
### Feedback

Is there a way we could have 30 minute energy settlement slots.  I am sure this is the most common settlement period (it is in europe).  The problem being that the 1 hour slot can cover 2 different price tariffs so costs are usually wrong.

### URL

https://www.home-assistant.io/docs/energy/

### Version

2023.12.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
