### ISSUE TITLE
Add an effect automation suggestion

### ISSUE THREAD

**Issue by TheLogan** [home-assistant/home-assistant.github.io#30244]
### Feedback

Currently the integration can do turn on/off/toggle and increase/decrease brightness. I'd love to see one for changing or perhaps even incrementing the current effect chosen. I am pretty new to HA and trying to use it specifically change scenes on my Twinkly Yule tree and wreath, but quite unsure how to do it xD

### URL

https://www.home-assistant.io/integrations/twinkly/

### Version

2023.12.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by TheLogan** [comment]
Ah, sorry. The feedback button links to the github issue creater though
https://www.home-assistant.io/integrations/twinkly/
I figured feature request was a type of feedback, but I'll post in the feature request instead then :)
