### ISSUE TITLE
"source_list" is non-existent

### ISSUE THREAD

**Issue by rwelsh09** [home-assistant/home-assistant.github.io#30243]
### Feedback

I find this integration works well for getting setup but provides too little information on how to actually use it. 

My "source_list" (as mentioned below) does not exist and it is unclear how to create one.

Quote from integration documentation:

> "The source list of available devices can be found in the Details section of the Spotify Media Player Control and the source_ist attribute in the [Developer Tools States](https://my.home-assistant.io/redirect/developer_states)."

This integrations documentation needs to be updated so more people can benefit from it.

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2023.12.1

**Comment by joostlek** [comment]
The source list is automatically created by devices Spotify can connect to from their API

**Comment by rwelsh09** [comment]
I now understand that's what this sentence, in the documentation, was trying to convey:

> The Spotify API cannot initiate playback to a device not already known to the Spotify API.

Unfortunately, knowing this does not help someone to understand how to generate the source_list for use in Home Assistant. Anyone setting this up would likely have at least one device that Spotify can connect to, yet there may not be a source_list in Home Assistant.

**Comment by 4homeassistant** [comment]
I am struggeling with the same detail. Although we have a Chromecast Audio, a Denon CEOL and 3 Chromecast Video devices that show up in the Spotify iOS App and as a media player in HA my Spotify integration isn't working. Authentication works, no errors in the logs, the Spotify App shows some usage on the endpoint

![image](https://github.com/home-assistant/home-assistant.io/assets/117555636/b8a0aae9-cb03-4b58-a141-8e77cea4d563)

The Spotify integration still looks like this:
![image](https://github.com/home-assistant/home-assistant.io/assets/117555636/f0f67dbb-56a1-4f23-a960-60a38b764863)
And I really went through all proposed steps from this thread: https://github.com/home-assistant/core/issues/95055

**Comment by joostlek** [comment]
That's a different issue. Please open a new issue in the core repo, fill out the form and also include debug logging

**Comment by 4homeassistant** [comment]
@joostlek I felt it would just be a lack of understanding of how to configure the integration correctly.

**Comment by joostlek** [comment]
You setup the integration correctly, you have something else going on

**Comment by joostlek** [comment]
Oh wait, never mind. I thought you meant you were playing music and it was still idle. I get what you mean now.

**Comment by joostlek** [comment]
Can you maybe go to https://developer.spotify.com/documentation/web-api/reference/get-a-users-available-devices

At the right side you can press a button saying "Try it". You will have to authenticate with them. I'm curious what will come out of it

**Comment by 4homeassistant** [comment]
Looks pretty empty (already saw that in the debug logging).
```
{
  "devices": []
}
```

**Comment by joostlek** [comment]
Right, so yes you have the same problem. I mean if you think there could be improvement in the wording, feel free to propose something and I'm happy to take a look at it. For me it says that it lists all the available devices. But if there are no available devices, the list is empty. So in my head it's correct and when I think about rewording this I think I'm only going to make it more complex

**Comment by 4homeassistant** [comment]
You are right. Doesn't seem to be a documentation issue. Maybe adding this as an FAQ (I see no devices. What can I do?) would help users when it comes to debugging.
Anyway - thank you @joostlek. Now I know where I have to dig.

**Comment by joostlek** [comment]
I mean, I like input from the users. I'm looking at stuff from the perspective of a developer while the docs should be understandable for normal users.

**Comment by 4homeassistant** [comment]
By the way - just learned that this is an issue with the Spotify API: https://community.spotify.com/t5/Spotify-for-Developers/v1-me-player-devices-returns-empty-array/m-p/5224904
When you actively play a song on your iOS Spotify app and connect it to any device on your networks the APIs player array returns these active devices AND if I reload the HA integration it shows them up as well. If you disconnect the active device and wait a couple of minutes the player array is empty again.
