### ISSUE TITLE
Mopeka Tank Check - Wifi Bridge

### ISSUE THREAD

**Issue by GHuser1598** [home-assistant/home-assistant.github.io#30246]
### Feedback

Would like to see if someone can make integration for the Mopeka Wifi Bridge to work with Home Assistant.  The sensor integrations work, but once you move the tanks away from the HA server, the Bluetooth goes out of range and makes the integration useless.  Integrating the Wifi bridge would be much more useful. 

### URL

https://www.home-assistant.io/integrations/mopeka/

### Version

2023.12.1

### Additional information

Would like to see if someone can make integration for the Mopeka Wifi Bridge to work with Home Assistant.  The sensor integrations work, but once you move the tanks away from the HA server, the Bluetooth goes out of range and makes the integration useless.  Integrating the Wifi bridge would be much more useful.

**Comment by bdraco** [comment]
This integration only works over Bluetooth.  You can add a proxy if you need to extend the range https://esphome.io/projects/index.html

A wifi bridge would be a new integration: If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
