### ISSUE TITLE
COPYING YOUR BACKUPS TO ANOTHER LOCATION Option 1 confusing

### ISSUE THREAD

**Issue by wittelw** [home-assistant/home-assistant.github.io#30252]
### Feedback

Current docs:
Option 1: Under [Settings > System > Backups](https://my.home-assistant.io/redirect/supervisor_backups), select the backup from the list.

This is confusing because clicking the checkbox shows "1 selected" but does NOT open the dialog, and the three dots on the Backups main page does NOT contain a "Download backup" option.

Suggestion:
Option 1: Under [Settings > System > Backups](https://my.home-assistant.io/redirect/supervisor_backups), single click the backup from the list to open the backup's dialog.

Note: currently there is an unassigned bug in home-assistant / frontend to make this option more discoverable which could change this behavior: https://github.com/home-assistant/frontend/issues/18342

### URL

https://www.home-assistant.io/common-tasks/os/#copying-your-backups-to-another-location

### Version

2023.12.1

**Comment by ShadowRep** [comment]
> Suggestion:
> Option 1: Under [Settings > System > Backups](https://my.home-assistant.io/redirect/supervisor_backups), double-click the backup

Single click. No double click required.

**Comment by wittelw** [comment]
Ping. If someone must be assigned prior to submitting a PR please let me know. I have family visiting for a week and this will be my first PR, but I will be reading the docs etc. for proper procedures for this repository and should have a PR submitted in the first week of March.

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @wittelw :+1:

**Comment by c0ffeeca7** [comment]
Not sure if you've seen it, @wittelw 

at the bottom of the page, there is an **Edit** button. It lets you edit the page, if you like.
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/61ec27dc-ad9d-4f40-814c-f5ab3d75d71b)

**Comment by wittelw** [comment]
@c0ffeeca7 I had not noticed that but will be aware for future simple doc changes. Many thanks to you and @klaasnicolaas for pushing this through and improving on my original suggestion!
