### ISSUE TITLE
Feature request: calculation of cost

### ISSUE THREAD

**Issue by xanderphillips** [home-assistant/home-assistant.github.io#30253]
### Feedback

Would love to be able to give the cost of my electricity per kWh and have the dash show estimated cost for the power being displayed.

### URL

https://www.home-assistant.io/integrations/tesla_wall_connector/

### Version

2023.12.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
