### ISSUE TITLE
Missing sensor

### ISSUE THREAD

**Issue by rwelsh09** [home-assistant/home-assistant.github.io#30263]
### Feedback

I don't know how/where to properly suggest an edit to the code for this integration so I thought I'd write it here and someone can correct me.

According to the SmartThings devices page my oven has a meat probe sensor:
![image](https://github.com/home-assistant/home-assistant.io/assets/19652238/268557a3-f985-470f-9e9f-02fdfd58b0f7)
But, this integration does not show this sensor.

Thanks

### URL

https://www.home-assistant.io/integrations/smartthings/

### Version

2023.12.1

### Additional information

Added as Feature Request after [klaasnicolaas](https://github.com/klaasnicolaas) suggested.
[https://community.home-assistant.io/t/update-smartthings-integration/653711](url)

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
