### ISSUE TITLE
Govee Bluetooth - listing of incompatible devices

### ISSUE THREAD

**Issue by martinvana** [home-assistant/home-assistant.github.io#30261]
### Feedback

I appreciate the page
[](https://www.home-assistant.io/integrations/govee_ble/)
listing "compatible products". It would be nice to have a list of known incompatible devices as well.
When trying to buy a BLE hass compatible thermometer (December 2023) the Govee product I see available are for the most of it not listed. That begs for question whether Govee changed the technology (protocol) or whether the list is outdated. 
As an example H5105 is not listed. I might just buy, test and update the page but I am wondering if the (non)compatibility might already be known
If unknown I am willing to help.
Thanks - M.

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2023.12.1

**Comment by bdraco** [comment]
If it's not listed, it means somebody hasn't reported it as working, or bought it yet, or they changed the protocol. 

We don't know anymore than what's on the page.

**Comment by bdraco** [comment]
If you do buy one, and it works fine, please do open a pull request to add it to the page

**Comment by martinvana** [comment]
> If you do buy one, and it works fine, please do open a pull request to add it to the page

I probably will. 
However, I strongly believe that a "negative result is also a result" and will submit a PR even if it won't work.
Thanks. M.
