### ISSUE TITLE
Are there any plans to fix Twitter/X integration or is it dead?

### ISSUE THREAD

**Issue by jrb80** [home-assistant/home-assistant.github.io#30266]
### Feedback

Integration currently non functional.

### URL

https://www.home-assistant.io/integrations/twitter/

### Version

2023.12.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
