### ISSUE TITLE
Unable to update/delete input datetime

### ISSUE THREAD

**Issue by LennardPlay** [home-assistant/home-assistant.github.io#30262]
### Feedback

Its not possible to update or delete this helper via UI. Not a huge deal, but it's not the behavior I expected.
Clicking on the settings cog only brings up an empty box.
![grafik](https://github.com/home-assistant/home-assistant.io/assets/60149904/9cc054f9-5e52-464f-a78e-408f2de28af3)

### URL

https://www.home-assistant.io/integrations/input_datetime/

### Version

2023.12.1

**Comment by dannytsang** [comment]
That doesn't sound right. Maybe try clearing your browser cache to see if it loads.
