### ISSUE TITLE
Broadlink thermostat HY02B05H.

### ISSUE THREAD

**Issue by Grenault76** [home-assistant/home-assistant.github.io#30281]
### Feedback

Hi i have integrated this broadlink to a thermostat HY02B05H. 
But there are two temperature sensor (internal / external) seem that only the internal is displayed now. 
 Is there a possibility to select the external sensor ?

### URL

https://www.home-assistant.io/integrations/broadlink/

### Version

2023.12.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
