### ISSUE TITLE
BGE integration non-functional

### ISSUE THREAD

**Issue by 7uAip6** [home-assistant/home-assistant.github.io#30291]
### Feedback

Baltimore Gas & Electric integration with Opower provides no data.

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2023.12.1

**Comment by tronikos** [comment]
Duplicate of https://github.com/home-assistant/home-assistant.io/issues/29674

**Comment by tronikos** [comment]
@home-assistant close

**Comment by tronikos** [comment]
I meant to say duplicate of https://github.com/home-assistant/core/issues/105381
