### ISSUE TITLE
Please add the option of hiding the (-) & (+) buttons in the UI 

### ISSUE THREAD

**Issue by mikesn31** [home-assistant/home-assistant.github.io#30308]
### Feedback

Please add the option of hiding the (-) & (+) buttons in the UI 

### URL

https://www.home-assistant.io/dashboards/thermostat/

### Version

2023.12.1

### Additional information

Please add the option of hiding the (-) & (+) buttons in the UI

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
