### ISSUE TITLE
integrations   webostv

### ISSUE THREAD

**Issue by janosikcs** [home-assistant/home-assistant.github.io#30307]
### Feedback

hi.

Volume up is not working.
Volume down is working.

'scriptnamezx':
  alias: Volume Up
  sequence:
  - service: webostv.button
    data:
      entity_id: mmedia_player.lg_webos_smart_tv
      button: VOLUMEUP
  mode: single
  icon: mdi:television
'scriptnamexy':
  alias: Volume Down
  sequence:
  - service: webostv.button
    data:
      entity_id: media_player.lg_webos_smart_tv
      button: VOLUMEDOWN
  mode: single
  icon: mdi:television

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2023.12.1

### Additional information

hi.

Volume up is not working.
Volume down is working.

'scriptnamezx':
  alias: Volume Up
  sequence:
  - service: webostv.button
    data:
      entity_id: mmedia_player.lg_webos_smart_tv
      button: VOLUMEUP
  mode: single
  icon: mdi:television
'scriptnamexy':
  alias: Volume Down
  sequence:
  - service: webostv.button
    data:
      entity_id: media_player.lg_webos_smart_tv
      button: VOLUMEDOWN
  mode: single
  icon: mdi:television

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
