### ISSUE TITLE
Volumeup is not working.

### ISSUE THREAD

**Issue by janosikcs** [home-assistant/home-assistant.github.io#30305]
### Feedback

'Xxxx':
  alias: Volume Up
  sequence:
  - service: webostv.button
    data:
      entity_id: mmedia_player.lg_webos_smart_tv
      button: VOLUMEUP
  mode: single
  icon: mdi:television
  
  Volumen down is work.
  

### URL

https://www.home-assistant.io/integrations/webostv/

### Version

2023.12.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
