### ISSUE TITLE
No useful info heree

### ISSUE THREAD

**Issue by granvillebarker** [home-assistant/home-assistant.github.io#30303]
### Feedback

You try to add the wyoming protocol, a box pops up asking for a host and port yet the docs do nothing to explain what host or what port.

### URL

https://www.home-assistant.io/integrations/wyoming/

### Version

2023.12.1

**Comment by c0ffeeca7** [comment]
Thank you for reaching out, @granvillebarker 
Added a reference to the tutorial on setting up a local pipeline. This should provide more context on how this integration is used.
