### ISSUE TITLE
it can not be continue clean after i choose pause

### ISSUE THREAD

**Issue by bmwcar** [home-assistant/home-assistant.github.io#30304]
### Feedback

 i click the ‘pause ’, then i want it continue previous work , but i found that the ‘start ’ function is the new begin work , so i hope it can be add new function as my mind.

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2023.12.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
