### ISSUE TITLE
Changing icon for device tracker depending of the state

### ISSUE THREAD

**Issue by sybri** [home-assistant/home-assistant.github.io#30313]
### Feedback

It could be greate to change the device_tracker icon from mdi:network to mdi:help-network for example depending if device is connected or not.

### URL

https://www.home-assistant.io/integrations/freebox/

### Version

2023.12.1

**Comment by Quentame** [comment]
Hi !

First, you are reporting the issue on the documentation repo not on core.

Then, not sure if it will be accepted by core members, I don't see other integration changing icon based on state.

Plus, what you are saying only works for types of devices that are unknown so it uses mdi:network, but how to handle other device types ?


Closing as wrong repo, you create a new one in the core repo if you want.
Thanks 😊
