### ISSUE TITLE
Vodafone Cable Box Support

### ISSUE THREAD

**Issue by qryhub** [home-assistant/home-assistant.github.io#30324]
### Feedback

Since I use my vodafone station (cable internet), and its not yet supported, i'd like to test this integration for it.

### URL

https://www.home-assistant.io/integrations/vodafone_station/

### Version

2023.12.2

**Comment by chemelli74** [comment]
Hi @qryhub, this is not the place for feature requests.
On top of that, I need at least the exact model and firmware.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
