### ISSUE TITLE
Maximum Number of Entries

### ISSUE THREAD

**Issue by Wild-Bird** [home-assistant/home-assistant.github.io#30353]
### Feedback

A "max_entries_to_show" option would be nice if you e.g. just want to see the last 1 or 2 logbook entries of a entity. 

### URL

https://www.home-assistant.io/dashboards/logbook/

### Version

2023.12.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
