### ISSUE TITLE
Ok, now it is setup, now what? Where's my devices?

### ISSUE THREAD

**Issue by sovamind** [home-assistant/home-assistant.github.io#30366]
### Feedback

Now that I have this installed, how do I use it?  I don't see it detecting or adding any devices to the system.  This documentation is pretty much useless!

### URL

https://www.home-assistant.io/integrations/fortios/

### Version

2023.12.3

**Comment by kimfrellsen** [comment]
Hi there,
The fortios integration is based on the device_tracker see https://www.home-assistant.io/integrations/device_tracker/

Hope this helps

/Kim
