### ISSUE TITLE
Page is missing "openwakeword" pre-requisite

### ISSUE THREAD

**Issue by kerryland** [home-assistant/home-assistant.github.io#30364]
### Feedback

This page says to 'Install the [Whisper](https://my.home-assistant.io/redirect/supervisor_addon?addon=core_whisper) and the [Piper](https://my.home-assistant.io/redirect/supervisor_addon?addon=core_piper) add-ons.' but goes on to assume you have also installed a [wake word](https://www.home-assistant.io/voice_control/install_wake_word_add_on/).

The page should also list 'openwakeword' addon as a pre-requisite.

This also explains why the tutorial claims that there are 3 Wyoming Entities, when, if you follow the tutorial as given, there are only two:

![piper-whisper-install-new-03](https://github.com/home-assistant/home-assistant.io/assets/398113/aeb218ae-3aae-4b16-a78b-da561f8098ff)

### URL

https://www.home-assistant.io/voice_control/voice_remote_local_assistant/

### Version

2023.12.3

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @kerryland :+1:
