### ISSUE TITLE
integration installation failed

### ISSUE THREAD

**Issue by 10051402** [home-assistant/home-assistant.github.io#30370]
### Feedback

Good evening, I can't install the integration because when I enter the IP and port number it gives me an unexpected error (yet the data is correct) can you help me? Thank you

### URL

https://www.home-assistant.io/integrations/progettihwsw/

### Version

2023.12.3

### Additional information

Good evening, I can't install the integration because when I enter the IP and port number it gives me an unexpected error (yet the data is correct) can you help me? Thank you

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
