### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by anpfu123** [home-assistant/home-assistant.github.io#30373]
### Feedback

no information is provided on this page

### URL

https://www.home-assistant.io/integrations/radio_browser

**Comment by klaasnicolaas** [comment]
Can you also indicate what information you are missing? Otherwise we can't do much with an issue like this 😉 

./Klaas

**Comment by blasbike** [comment]
@frenck  @klaasnicolaas 
I had to spend couple of minutes to figureout what to do next after installing integration. Finally I have found the frontend for it is under Media menu --> Radio Browser.
Would also be nice to give more info how to get content id at (by going to automations UI etc.)
I had to check out forums https://community.home-assistant.io/t/radio-browser-how-to-use/398397/12
