### ISSUE TITLE
projectshwsw plugin installation error

### ISSUE THREAD

**Issue by 10051402** [home-assistant/home-assistant.github.io#30371]
### Feedback

I have a problem installing theprojecthwsw plugin
when I go to settings, devices and services, add integration and search for hwsw projects it finds it, but when I enter ip and port i.e. 192.168.1.236 port 8087, it gives me the error "unexpected error".
can you help me solve the problem? I am also willing to connect with any desk if you can give me support. Thank you

### URL

https://www.home-assistant.io/integrations/progettihwsw/

### Version

2023.12.3

### Additional information

I have a problem installing theprojecthwsw plugin
when I go to settings, devices and services, add integration and search for hwsw projects it finds it, but when I enter ip and port i.e. 192.168.1.236 port 8087, it gives me the error "unexpected error".
can you help me solve the problem? I am also willing to connect with any desk if you can give me support. Thank you

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
