### ISSUE TITLE
Please add example how to configure "consider_home" setting from yaml in new UI configuration

### ISSUE THREAD

**Issue by ICEbAIR82** [home-assistant/home-assistant.github.io#30376]
### Feedback

I was using "consider_home" value to get around issue with sleeping mobiles that did not respond to all PING requests.
Since integration was updated most of my people are considered as absent regularly and I need to add this setting again somehow.

### URL

https://www.home-assistant.io/integrations/ping

**Comment by jpbede** [comment]
Hey, thanks for your report. The `consider_home` option is currently not available, there is already a PR (https://github.com/home-assistant/core/pull/104881) for to add this back.
