### ISSUE TITLE
Nattsikringspanel

### ISSUE THREAD

**Issue by OttarNOR** [home-assistant/home-assistant.github.io#30383]
### Feedback

Is it possible to use Verisure-Nattsikringspanel Day & Night button, to trigger automations in Home Assistant?
![medium-240](https://github.com/home-assistant/home-assistant.io/assets/87257784/42df1c35-534c-47d6-b1d6-004afb3ee515)

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2023.12.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
