### ISSUE TITLE
"Event" entity: clarify a state

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/home-assistant.github.io#30380]
### Feedback

Here two sentences contradict each other:

![изображение](https://github.com/home-assistant/home-assistant.io/assets/71872483/65b91edf-7180-4a28-a2a8-e00fb3a19a66)

### URL

https://www.home-assistant.io/integrations/event/#the-state-of-an-event-entity

### Version

2023.12.1

**Comment by ildar170975** [comment]
up

**Comment by c0ffeeca7** [comment]
I see your point there, @ildar170975. 
Thank you for pointing this out.

Tried to rephrase it a bit to make it clearer and added a screenshot.
