### ISSUE TITLE
No info where is frontend for the integration

### ISSUE THREAD

**Issue by blasbike** [home-assistant/home-assistant.github.io#30390]
### Feedback

I had to spend couple of minutes to figureout what to do next after installing integration. Finally I have found the frontend for it is under Media menu --> Radio Browser.

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2023.12.3

**Comment by c0ffeeca7** [comment]
duplicate of #30373

**Comment by c0ffeeca7** [comment]
Added step on how to start the radio browser. Closing this as fixed by #30389
