### ISSUE TITLE
Can't find Helpers in Integrations

### ISSUE THREAD

**Issue by txwindsurfer** [home-assistant/home-assistant.github.io#30402]
### Feedback

Helpers are an important part of Home Assistant but when you do to Integrations and look for them you don't find the listing.  This is just a lookup issue because if I enter
    https://www.home-assistant.io/integrations/#helper
I can see all of the helpers.  Please add a link to this page when you start typing helpers in the integration search section.

### URL

https://www.home-assistant.io/integrations/#helper

### Version

2023.12.3

**Comment by klaasnicolaas** [comment]
You can't find helpers under integrations because they have a separate place: https://my.home-assistant.io/redirect/helpers/

./Klaas

**Comment by txwindsurfer** [comment]
Hi Klaas,
I must not have communicated correctly.  I can find helpers just fine in my homeassistant.  This was about documentation.  When you go to homeassistant.io you should be able to get find all the helpers when you type "help.." after selecting integrations.  This is about fixing documentation to easily find information on all the available helpers.
Please let me know if I am still not communicating correctly,
Reagan

________________________________

**Comment by dannytsang** [comment]
Hi Reagan,

I'm not sure I follow what you're asking for. The helper filter on the integrations page lists all the helpers available but helper itself is not an integration so it won't appear in the search.

Can you clarify what you're looking to change?

**Comment by txwindsurfer** [comment]
Well, that was exactly what I was suggesting. Technically it isn't an integration but a meta integration. Since helpers are so useful and many people will not be aware of the many helpers, I am suggesting a helper page within integrations with links to all helpers. If it doesn't fall under integrations technically then IMHO HA needs an additional search function like integrations, or just a broader interpretation of what is listed within integrations.
