### ISSUE TITLE
Backend-selected theme option is not available

### ISSUE THREAD

**Issue by and7ey** [home-assistant/home-assistant.github.io#30407]
### Feedback

`When themes are enabled in the configuration.yaml file, a new option will show up in the user profile page`
there is no such option in 2023.12.3

### URL

https://www.home-assistant.io/integrations/frontend/

### Version

2023.12.3

**Comment by piitaya** [comment]
The screenshot on the documentation is an old one and should be updated with this one : 
![CleanShot 2023-12-19 at 11 48 38](https://github.com/home-assistant/home-assistant.io/assets/5878303/6ab6203f-1b67-4c9e-98c9-cc159b505ad6)

It's not "backend theme" anymore but "use default theme".

**Comment by and7ey** [comment]
the doc is not updated
