### ISSUE TITLE
Anleitung um einen Verlauf darzustellen

### ISSUE THREAD

**Issue by Damrak2022** [home-assistant/home-assistant.github.io#30409]
### Feedback

Hallo,
ich würde mir wünschen das ich die Gauge in einem Farbverlauf darstellen kann. Vielleicht könnt Ihr das noch in der Doku erklären.

Liebe Grüße
Andy

### URL

https://www.home-assistant.io/dashboards/gauge/

### Version

2023.12.3

**Comment by c0ffeeca7** [comment]
Thank you for reaching out, @Damrak2022 

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
