### ISSUE TITLE
Fast.com underreporting speed 

### ISSUE THREAD

**Issue by MAPLibraryIT** [home-assistant/home-assistant.github.io#30401]
### Feedback

![Screenshot 2023-12-18 152701](https://github.com/home-assistant/home-assistant.io/assets/124637149/276b5d0f-34c9-4ea0-b600-177687661a93)

Yet the SpeedTest is giving my my full speed, the Fast.com integration seems for reliable for reporting outages.  We are using Ethernet with brand new CAT6 cable.  I tried running HA without the Speedtest.net running and got the same slower results in Fast.com System is an Intel NUC Kit NUC5i3RYH

I check and our system is not running on wifi, only ethernet

Any ideas why the differences?

Thanks

Thomas Sargent
IT Specialist, Morris Area Public Library
it.tech@morrislibrary.com
(815) 942-6880

### URL

https://www.home-assistant.io/integrations/fastdotcom/

### Version

2023.12.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
