### ISSUE TITLE
WiFi Difficulties

### ISSUE THREAD

**Issue by roeberp** [home-assistant/home-assistant.github.io#30418]
### Feedback

Apparently the Box-3 will NOT connect to a network with a hidden SSID. I do not know why this is the case... All of my 5-year old light bulbs connected easily. Anyway. I hope it gets fixed, but the solution in the meantime is to un-hide the SSID.

### URL

https://www.home-assistant.io/voice_control/troubleshooting_the_s3_box/

### Version

2023.12.3

**Comment by jesserockz** [comment]
Hi @roeberp, at this point in time, [improv](https://improv-wifi.com) does not support provisioning to hidden networks but it is definitely something that is on our list to do very soon.

Jesse
