### ISSUE TITLE
Kategories

### ISSUE THREAD

**Issue by falcon10001** [home-assistant/home-assistant.github.io#30411]
### Feedback

Hi all,
I looks quite good and simple. The only thing I miss is creating some categories. As we are grouping our shopping list related to supermarkets, it would be great to have the ability to just drag and drop them to specific sub categories.
At the moment we use Out-of-Milk, where this is implemented. It´s a feature I haven´t seen anywhere, so this would be great here.

### URL

https://www.home-assistant.io/integrations/todo/

### Version

2023.12.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
