### ISSUE TITLE
Public API does not work

### ISSUE THREAD

**Issue by Chris909090** [home-assistant/home-assistant.github.io#30422]
### Feedback

Hello everyone,

I have created a public API on Forecast.Solar and wanted to use it now.

However, when I enter it, I get the message that the API key is invalid.

What could be the reason for this?

When I enter it in the browser, everything works.
https://api.forecast.solar/estimate/40.508509/19.750910/27.5/10/7.29

Many thanks for your help!
Regards

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2023.12.3

**Comment by klaasnicolaas** [comment]
If you use the public plan, you do not need an API key. So leave that input field empty when you adjust settings in the options config flow.

./Klaas

**Comment by Chris909090** [comment]
> If you use the public plan, you do not need an API key. So leave that input field empty when you adjust settings in the options config flow.
> 
> ./Klaas

Ah ok thanks for your help! :)
