### ISSUE TITLE
Failing login

### ISSUE THREAD

**Issue by Ivanomovil** [home-assistant/home-assistant.github.io#30437]
### Feedback

Keeps saying password is wrong, I'm sure about the password, even reset password and removed plugin and still doesn't work

### URL

https://www.home-assistant.io/integrations/life360/

### Version

2023.12.3

**Comment by pnbruckner** [comment]
Duplicate of issue #105816 in home-assistant/core. Also, this is not a documentation issue, so it should have been added to home-assistant/core. And a fix has been submitted.

**Comment by MrMxyzptlk** [comment]
Still not working for me since a couple of months now. Just tried added the integration again; login failed.

"invalid authentication"

**Comment by pnbruckner** [comment]
Again, wrong repo. Life360 has actively started to block unauthorized usage of their API, such as Home Assistant, Hubitat, etc. It is very likely HA's Life360 integration will be removed soon.
