### ISSUE TITLE
ESP32-S3-BOX voice assistant recommendation - animated idle screen

### ISSUE THREAD

**Issue by mukul-k** [home-assistant/home-assistant.github.io#30434]
### Feedback

Please forgive me if this is not the right place for this, but it might be good to have some sort of animated idle screen graphics or sleep mode for the display for burn in issues or backlight issues rather than the static image currently in use. 

### URL

https://www.home-assistant.io/voice_control/s3_box_voice_assistant/

### Version

2023.12.3

**Comment by c0ffeeca7** [comment]
Thank you for reaching out, @mukul-k 

This is the issue tracker for documentation.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
