### ISSUE TITLE
Cannot integrate into the newest HA

### ISSUE THREAD

**Issue by ivandemec** [home-assistant/home-assistant.github.io#30440]
### Feedback

I get a confirmation window, but it doesn't appear in the integrations.
![image](https://github.com/home-assistant/home-assistant.io/assets/7983448/8ede6ba4-5852-4fc5-a26a-00749ec23c36)

### URL

https://www.home-assistant.io/integrations/sensirion_ble/

### Version

2023.12.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
