### ISSUE TITLE
The Documentation is Vague and Inconsistent with Actual User Experience

### ISSUE THREAD

**Issue by LeMathochist** [home-assistant/home-assistant.github.io#30467]
### Feedback

So, I'm setting up the Spotify Integration and following along with this set of steps and in the configuration section it refers to some YAML snippets that seem to suggest this goes in the configurations.yaml file. 
Going ahead and adding this to the file, under 'spotify' section, and I get a warning in the notifications area that  the integration doesn't support configuration by YAML. 

Can we clean this up to reflect the actual process from the devs? This whole thing was super confusing.

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2023.12.3

### Additional information

Created Oauth appiclication
Added extra users
Add Integration to HA
Add client ID and Secret

Click Player Card
Select Output Device from List
Error: Failed to call service media_player/select_source. Spotify error: PREMIUM_REQUIRED
I have a premium account, and am logged in on the device in question and everything is on same subnet

**Comment by joostlek** [comment]
Are you now giving feedback or filing a bug?

I just checked the docs and there are only some example services you can you in your integrations, not configuration YAML stuff.

**Comment by LeMathochist** [comment]
Feedback. It's just not a clear document to follow as I've still not got this set up correctly and based on what is in that document, it's inaccurate: Premium account not required but recommended as you can only control a premium account. Great. I have a premium account. Says I have to select the output device and it has to be one in the list on the player. When I select, it tells me I need a premium account. So what gives? So I'm sure it's not a bug, and that I just have to do things in a certain order. And nowhere does it say to restart HA but I had to restart HA to be able to get a token from the OAuth app. I've logged in and out of Spotify, removed and re-added credentials I've refreshed HA, restated HA. So, I am convinced it's something missing from the doc or the doc is inaccurate (it definitely is because the dialogs and interface options on the OAuth app creation page aren't the same any more. You need to select an API to use and there are many choices.).
