### ISSUE TITLE
Retrieving the API Key for Connector APP

### ISSUE THREAD

**Issue by I-am-OK-86** [home-assistant/home-assistant.github.io#30462]
### Feedback

Hello,
Unfortunately it is not clear to me how to click the about page of the connector app 5 times to get the key. There is nothing I can click 5 times so I can't make the whole installation work. Does anyone have an advice?
Thanks and best
OK

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2023.12.3

**Comment by starkillerOG** [comment]
@I-am-OK-86 just hit the screen 5 times quickley after eachother on the about page. there is no button, you just need to press the screen.

If it does not work, please send a screenshot of the about page of the connector app.

**Comment by I-am-OK-86** [comment]
I tried but it is not working.Maybe I am on the wrong page. Herr are the screenshots:Do you mean this  or a different one?Thanks and bestAm 23.12.2023 um 10:11 schrieb starkillerOG ***@***.***>:﻿
@I-am-OK-86 just hit the screen 5 times quickley after eachother on the about page. there is no button, you just need to press the screen.
If it does not work, please send a screenshot of the about page of the connector app.

**Comment by I-am-OK-86** [comment]
I tried but it is not working.Maybe I am on the wrong page. Here are the screenshots:

![IMG_1068](https://github.com/home-assistant/home-assistant.io/assets/121457876/3bd37cc2-c937-4a3f-96b8-bd6eb7d288a1)
![IMG_1067](https://github.com/home-assistant/home-assistant.io/assets/121457876/1e705e41-aa71-429d-9c7b-8f736f037350)

Do you mean this or a different one?

Thanks and best

**Comment by starkillerOG** [comment]
@I-am-OK-86 Yes it is that app, but it is the wrong page, you have to open the app and inside the app go to the about page.

Please send a new screenshot of the about page inside the app (when you open the app).
It probably is under the settings menu inside the app.
If you cannot find it, please send a screenshot of the first screen you see when you open the app

**Comment by I-am-OK-86** [comment]
Many thanks, it worked out.

**Comment by starkillerOG** [comment]
If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library
