### ISSUE TITLE
apple icloud app specific password

### ISSUE THREAD

**Issue by ruudvdhouw** [home-assistant/home-assistant.github.io#30463]
### Feedback

in Apple icloud you can create an application specific password. to avoid login warnings from icloud

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2023.12.3

### Additional information

1) Log in bij [appleid.apple.com](https://appleid.apple.com/account/home).
2) klik under 'Login en security' op 'App-specifieke passwords'.

**Comment by rudibarani** [comment]
Would be very much appreciated!!!

**Comment by MC-r15ti4n** [comment]
Application-specific passwords are better than going the 2FA route.
