### ISSUE TITLE
this feature does not work anymore and you should remove the documentation for it.

### ISSUE THREAD

**Issue by arianecastonguay** [home-assistant/home-assistant.github.io#30479]
### Feedback

this feature does not work anymore and you should remove the documentation for it.

### URL

https://www.home-assistant.io/integrations/familyhub/

### Version

2023.12.3

**Comment by frenck** [comment]
The documentation matches the software currently, just removing documentation is therefore not a good idea.

It sounds like you experience an issue with an integration, please open up an issue in the Core issue tracker instead.

Thanks 🙏 

../Frenck
