### ISSUE TITLE
[TUYA] New IoT Core commercial rules from October 31, 2023

### ISSUE THREAD

**Issue by ESP4Ever** [home-assistant/home-assistant.github.io#30471]
### Feedback

Hello!

I just solved some issues with Tuya integration caused by subj.
First of all, if there is more than one data center is assigned to a project, no devices will be shown in the project tab.
Another point is there is a monthly limit for API calls/messages, so at some point the integration just stops working till end of the month...

More details here: `https://developer.tuya.com/en/docs/iot/membership-service?id=K9m8k45jwvg9j`

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2023.12.3

**Comment by codyc1515** [comment]
This should be resolved in 2024.2.

**Comment by tonyviljoen** [comment]
Just loaded 2024.2. When it comes to re-authenticating Tuya, it wont open the QR code, get an invalid hex color code error.

**Comment by frenck** [comment]
All solved in Home Assistant 2024.2 indeed 👍 

../Frenck
