### ISSUE TITLE
Extend supported vendors

### ISSUE THREAD

**Issue by svenkoehler** [home-assistant/home-assistant.github.io#30485]
### Feedback

Hi,

I wanted to let you know, that I was able to get this integration working with my acomax gateway: https://www.acomax.de/produkte/smart-home/fx-i-620-bridge-maxi/ so maybe you'd like to extend the list of supported vendors.

Unfortunately it doesn't show me any kind of position attribute, but that may be due to my blinds being just oneway operated ones.

Regards,
Sven

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2023.12.3

**Comment by starkillerOG** [comment]
@svenkoehler thank you for the feedback!
I have added Acomax in the list of supported brands with this PR: https://github.com/home-assistant/home-assistant.io/pull/30486

If you do not see the postion in the vendor app, then the blind just does not support position and will not be shown in HomeAssistant.

**Comment by klaasnicolaas** [comment]
@starkillerOG Could you stop asking for sponsorship in issues or PRs, I think it has already been clearly indicated in the past that we do not want that here. Thank you 😉

./Klaas
