### ISSUE TITLE
Remove a Device

### ISSUE THREAD

**Issue by WildWex** [home-assistant/home-assistant.github.io#30492]
### Feedback

I'd like to see a feature that allows me to remove an Insteon device from the interface when it's no longer in use.  For example, I have an ApplianceLinc (#2456S3) which I no longer use and replaced with a Kasa plug.  I can't seem to figure out where the DELETE or REMOVE option is to remove it from the Insteon database of devices.

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2023.12.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
