### ISSUE TITLE
Workday, 4 hour offset (fractional offset)?

### ISSUE THREAD

**Issue by semikor** [home-assistant/home-assistant.github.io#30491]
### Feedback

Greetings!
How can you receive a notification at 20 o'clock that tomorrow is a working day?
The "Workday" integration does not allow you to set an offset in hours and I cannot enter 0.2 into the days offset.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2023.12.3

**Comment by gjohansson-ST** [comment]
You make the offset to 1 for tomorrow and run an automation at 8pm checking if that sensor is on. In that case it's a working day.

**Comment by semikor** [comment]
In this option, automation will not work on Friday morning, since with an offset of 1 day, Friday will be a “workday” == false

**Comment by gjohansson-ST** [comment]
You wrote "tomorrow" so if Saturday is not a working day it will obviously come back as off. 
Also you can limit which days the automation runs on.
