### ISSUE TITLE
Map Card

### ISSUE THREAD

**Issue by ComplexEngineer** [home-assistant/home-assistant.github.io#30495]
### Feedback

İyi Çalışmalar

![Konum](https://github.com/home-assistant/home-assistant.io/assets/137332505/cefd5aa7-bb30-4b6a-b3b8-46a48c4bd1d7)

Enlem ve Boylam bilgilerini kullanarak bir takip sistemi oluşturmak istiyorum. Bir çok farklı yolu yaptım olmadı.  

![Map Kart](https://github.com/home-assistant/home-assistant.io/assets/137332505/708d5894-3e06-45f0-b6ba-4b6ff97b6421)

Map Kart özelliklerine enlem ve boylam eklenmelidir.

sensörden gelen enlem ve boylam bilgilerini kullanarak kolayca bu iş yapılabilir.

### URL

https://www.home-assistant.io/help/

### Version

2023.12.3

**Comment by c0ffeeca7** [comment]
Thank you for reaching out, @ComplexEngineer 

I'm going to repeat your message here in English, via Google Translate:

> I want to create a tracking system using Latitude and Longitude information. I tried many different ways but it didn't work. Latitude and longitude must be added to the Map Card properties.
> This can be easily done by using the latitude and longitude information from the sensor.

Now, please help me understand what the goal is for this issue:

1. Are you trying to give feedback to the [map card](https://www.home-assistant.io/dashboards/map/) documentation page?
2. Are you requesting a feature? To display lat and long also on the map card?
