### ISSUE TITLE
Does not support login to server.growatt.com

### ISSUE THREAD

**Issue by CarstenG2** [home-assistant/home-assistant.github.io#30490]
### Feedback

The integration does nt allow to connect to the default server server.growatt.com.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.12.3

**Comment by marcovanree** [comment]
Same problem for me :(

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
