### ISSUE TITLE
New Shelly 1 PM Mini Gen 3 not supported under Shelly Integration

### ISSUE THREAD

**Issue by DJMAXIZA** [home-assistant/home-assistant.github.io#30493]
### Feedback

The new Shelly Mini Gen 3 released this month (Dec 2023), is not supported in the existing Shelly integration. It does not even show up, when trying to add manually with IP address. Please can these devices be added as a supported integration?

Thank you

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2023.12.3

### Additional information

Link to product page: https://www.shelly.com/en/products/shop/shelly-1-pm-mini-gen3

**Comment by bieniu** [comment]
Duplicate https://github.com/home-assistant/core/issues/106084
