### ISSUE TITLE
Heating/Cooling Schedule

### ISSUE THREAD

**Issue by Bliickie** [home-assistant/home-assistant.github.io#30494]
### Feedback

This thermostat has both a Heat and Cool Schedule Capability.  These are significant for this stat and would be great to access, change and then save to the stat.

According to the API, these are the commands:

2.2.3.2 Thermostat Program for a week
The programs for the entire week are also available at the following URI’s:
· http://<ip-address>/tstat/program/heat
· http://<ip-address>/tstat/program/cool

Each of the heat or cool programs consists of one program for each day of the week. The data
format of the response consists of all the attributes corresponding to the days of the week, from 0
to 6.

How could we add the Schedule Display/Edit/Save Functions to Home Assistant?

Thank you...

### URL

https://www.home-assistant.io/integrations/radiotherm/

### Version

2023.12.3

### Additional information

![Scheduling Functions](https://github.com/home-assistant/home-assistant.io/assets/37019339/566a481e-09d4-42e0-bc3f-27ae04da2188)

**Comment by vinnyfuria** [comment]
I imagine that this could work by adding new attributes to the integration for the two schedules. The attributes would need to be polled to get any updates entered at the thermostat and updated on change within home assistant.

It'd be interesting to know if any of the other climate modules have solved this in a similar (or different way).

No promises that I'll have time to work on it. But I'd be happy to review a PR if you want to dig in.

**Comment by Bliickie** [comment]
Hi  Vinny,

 

Thx for the reply.

 

I’ve decided the Green Home Assistant isn’t going to work for me and am returning it.  I got it for the Radio Thermostat interface so that I could access the thermostat remotely.  There are too many hoops and obstacles for remote access on the HA and there some features missing from the thermostat itself as mentioned.

 

Again, thanks for the reply.

 

Best!

 

Bliickie…
