### ISSUE TITLE
Anydesk at Home Assistant Green

### ISSUE THREAD

**Issue by hooonza** [home-assistant/home-assistant.github.io#30504]
### Feedback

Hallo, please, can I get Anydesk (https://anydesk.com/en/downloads/raspberry-pi) to the Home Assistant Green and use it to manage HA? Thanks!

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2023.12.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
