### ISSUE TITLE
Reference to Error Log

### ISSUE THREAD

**Issue by rocket-plane** [home-assistant/home-assistant.github.io#30500]
### Feedback

I struggled quite a lot trying to get the examples working. Especially to create a single device witch two sensors based on two topics. It was quite hard, until I looked at the error log config/logs. Then I realised, that I missed some colons. I think a reference to the log would have saved me some hours.

### URL

https://www.home-assistant.io/integrations/fan.mqtt/

### Version

2023.12.3

**Comment by jbouwh** [comment]
Sorry, I try to understand your issue, not sure what it is.

**Comment by jbouwh** [comment]
@rocket-plane can you elaborate?

**Comment by red-black-bonsai** [comment]
Not being @rocket-plane , I'd assume they mean something like:

> If your custom MQTT devices don't work, go to Settings -> System -> Logs to check for error messages.
> 
> If this doesn't yield enough information, try raising the log level as described in <https://www.home-assistant.io/integrations/logger/> for the mqtt logger like this (and don't forget to restart HA)
> 
>     logger:
>       default: info
>       logs:
>         homeassistant.components.mqtt: debug

(Not sure that's the correct way to change the logger, just an example text to point people in the right direction.)

**Comment by jbouwh** [comment]
And example can be found here: https://www.home-assistant.io/integrations/mqtt/#discovery-examples

If multiple sensors share the same device, they must have a shared identifier. It is not needed that all config payloads for all sensors have all attributes, one is enough.
