### ISSUE TITLE
Terrible description on how to use WOL service

### ISSUE THREAD

**Issue by pixartist** [home-assistant/home-assistant.github.io#30501]
### Feedback

The instructions for this setup are less then clear. There is no concise example file that includes a full working setup. 

### URL

https://www.home-assistant.io/integrations/wake_on_lan/

### Version

2023.12.3

**Comment by hvandonge** [comment]
Hi @pixartist, have you already figured out how to use the WOL integration?

**Comment by pixartist** [comment]
> Hi @pixartist, have you already figured out how to use the WOL integration?

I think I understood how it is supposed to work but it neither shows the status of the target machine which it is supposed to do, nor does it actually work which might also be a problem with the target machine though, I am not sure. It does not really tell which parameters are required to make it work either.

**Comment by elmosnotfrommexico** [comment]
Any update on a much clearer explaination on the Wol topic? i really think, as many others do, that the manual and the documentation should be revisioned and modified for a much clearer understading on how to use the service.
