### ISSUE TITLE
Additional solution to "This entity does not have a unique ID"

### ISSUE THREAD

**Issue by tuxick** [home-assistant/home-assistant.github.io#30503]
### Feedback

In some cases this problem can be fixed by simply clearing browser cache. Maybe add this to documentation?

### URL

https://www.home-assistant.io/faq/unique_id/

### Version

2023.12.3

**Comment by frenck** [comment]
That sounds like a bug an not a solution?

**Comment by tuxick** [comment]
Bug in code or in browser?  In either case it can be a huge timesaver if you remember/know to force reload browser.

**Comment by frenck** [comment]
Force reload isn't a solution, it is a workaround / mitigation.
