### ISSUE TITLE
Pool light and heater 

### ISSUE THREAD

**Issue by jemerson18** [home-assistant/home-assistant.github.io#30533]
### Feedback

Is there an update when pool light control and heater control will be added? Thank you. 

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2023.12.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
