### ISSUE TITLE
Cannot integrate Growatt

### ISSUE THREAD

**Issue by petersmids** [home-assistant/home-assistant.github.io#30531]
### Feedback

https://server-api.growatt.com/
https://server-us.growatt.com/
http://server.smten.com/
Waar kun je zelf de juiste URL opgeven

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2023.12.4

**Comment by petersmids** [comment]
These 3 do not work in the Netherlands
Where can you enter the correct URL yourself

**Comment by dannytsang** [comment]
> These 3 do not work in the Netherlands Where can you enter the correct URL yourself

I'm afraid this would be a feature request. Please raise it by going to **New issue** > **Feature Request**

**Comment by petersmids** [comment]
Hello Danny,
In the Discord I read these kinds of stories about GROWATT: Hello PeetHome,
I have been trying for a while to get that integration working. But without
success. It seems that Growatt is doing everything it can to keep closing
everything down so that everything has to run through their own app and
cannot be integrated into Home Assistant, for example.

This is bad advertising for the Growatt inverters
*Met een vriendelijke groet uit ARNHEM,*
*PH (Peter) Smids*




Op ma 1 jan 2024 om 13:16 schreef Danny Tsang ***@***.***>:

**Comment by dannytsang** [comment]
It's not a great situation. If you want to read more, there's a giant thread in the forums: https://community.home-assistant.io/t/anyone-experience-with-connecting-a-growatt-solar-inverter/60430/275
