### ISSUE TITLE
Activating debug logging for custom integrations

### ISSUE THREAD

**Issue by HAEdwin** [home-assistant/home-assistant.github.io#30549]
### Feedback

The documentation is not clear on how to activate this option for custom integrations. https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging

Say if I added LOGGER.debug lines to my Custom Integration is seems that this can be made visible by adding “loggers”: [“custom_components.YOUR_DOMAIN”] to the manifest.yaml of the custom_component. Only then the lines with LOGGER.debug will show in the log.

### URL

https://www.home-assistant.io/docs/configuration/troubleshooting/

### Version

2023.12.4

### Additional information

For a reference see: https://community.home-assistant.io/t/enable-debug-logging-for-integrations-am-i-missing-something/500256/1

Thanks for all the good work!

**Comment by frenck** [comment]
There is no difference?

**Comment by HAEdwin** [comment]
Just added a reference to the part of the documentation where this topc could be added.

Enabling and disabling debug logging works fine, but in order to make it work for a custom integration it's not specified that you should add "loggers": ["custom_components.[name]"] to the manifest file.

I use .debug lines to analyze the data that users may receive. But I now realize that this may be an undocumented or incorrect way of using the UI function of "Enable debug logging". Though it has 2.7k views so it's a pretty hot topic.
