### ISSUE TITLE
HA doesn't run

### ISSUE THREAD

**Issue by chengidesk** [home-assistant/home-assistant.github.io#30543]
### Feedback

[logs.txt](https://github.com/home-assistant/home-assistant.io/files/13788051/logs.txt)

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2023.12.4

### Additional information

I have no idea what happened. Tried several machine but all are having the same issue.

Thanks for looking into this

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
