### ISSUE TITLE
Missing solar entity

### ISSUE THREAD

**Issue by mitcheld** [home-assistant/home-assistant.github.io#30541]
### Feedback

I am using the HomeWizard p1 meter with home assistant, but when configuring the energy dashboard, I can't find an entity for solar. Al I see is import/export. However in the Energy android app, solar is shown. How do I set up solar?
![Screenshot 2023-12-28 140840](https://github.com/home-assistant/home-assistant.io/assets/22025122/35c56ea5-df23-4b81-b7b6-de39fbd0478d)

### URL

https://www.home-assistant.io/integrations/homewizard/

### Version

2023.12.4

**Comment by DCSBL** [comment]
Hi! Thank you for reaching out. You have opened an issue for the documentation (typos, missing/invalid info etc).

Can you open this issue at https://github.com/home-assistant/core/issues/new/choose and fill in all the details? I think the 'diagnostics' file will help us the most!

**Comment by DCSBL** [comment]
@home-assistant close
