### ISSUE TITLE
Is BMW Connected Drive login unavailable again in China?

### ISSUE THREAD

**Issue by cat007cat** [home-assistant/home-assistant.github.io#30551]
### Feedback

Using Integrations -> BMW Connected Drive cannot login to BMW

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2023.12.3

### Additional information

Additionally, testing the official 0.14.6 version in Docker, still unable to log in to BMW China.

https://github.com/bimmerconnected/bimmer_connected/releases

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
