### ISSUE TITLE
Very bad docu

### ISSUE THREAD

**Issue by albertusQuelle** [home-assistant/home-assistant.github.io#30560]
### Feedback

Hi, 
i wanted to free space, especially with "clean database!". 

Unfortunately the linked page "https://www.home-assistant.io/integrations/recorder/#service-purge" is so extremely bad, i have absolutely 0 idea what the author wants to tell us... 

Cant there be a how to and not just a list of words?

Can definately be improved. 

### URL

https://www.home-assistant.io/more-info/free-space/

### Version

2023.12.4

**Comment by dannytsang** [comment]
Could you provide more details about what is not clear please?
