### ISSUE TITLE
This page takes me in a circle? Completely failed to tell me how to setup my DSMR Slimme Meter

### ISSUE THREAD

**Issue by squishysdomain** [home-assistant/home-assistant.github.io#30562]
### Feedback

The Key Phrase in the article is:

"Follow the instructions on screen to complete the setup"

There are no onscreen instructions!

It asks for Host - what format is this?  Is it an IP address, or a name or ... NO IDEA!!!
It asks for a PORT - I know what this is but I have no idea which one to choose - It suggests port 0 but I doubt if this is correct.

When I click on help it takes me back to this page.

### URL

https://www.home-assistant.io/integrations/dsmr/

### Version

2023.12.4

### Additional information

The integration is no longer auto-discovered as it used to be.  I tried to use this article to install it manually.  I failed.

**Comment by frenck** [comment]
> The integration is no longer auto-discovered as it used to be.

This integration was never auto-discovered.

Are you confusing this integration with something else maybe?

**Comment by klaasnicolaas** [comment]
The onscreen instructions are the config flow that you start when you want to add the integration, perhaps you can indicate which device you are using for the P1.

./Klaas

**Comment by squishysdomain** [comment]
Thanks for the comments.  The device is Smartgateways.nl  Slimme meter WiFi gateway.  It was working up until about 3 weeks ago when I guess there was a Home Assistant update.  I read in their information that it should be auto discovered but perhaps I am wrong?  This integration was installed and was not working so I deleted it and tried to reinstalling it.

When I install the integration it asks for some information as I mentioned in the original Issue report.  These fields are not clear to me which is why I reached out.  The Smartgateways instructions are also very poor so I am stuck.

**Comment by squishysdomain** [comment]
In the meantime I managed to make it work.  I found the following page:

https://smartgateways.nl/slimme-meter-uitlezen-met-home-assistant/

It was under Home Assistant (Telnet) on their support page.

**Comment by squishysdomain** [comment]
I was not asking for a change to the code but a change to the documentation.  The statement "follow the on-screen instructions" does not help users making the whole page a waste of time.  I do hope that Home assistant will not be seen as written by geeks only for geeks?
