### ISSUE TITLE
Consider using a MediaWiki for dokumentation.

### ISSUE THREAD

**Issue by mhgue** [home-assistant/home-assistant.github.io#30568]
### Feedback

I was searching for a list of all helpers and a short overview what can be done with them. I ended with writing this list in my personal wiki because I failed finding what I needed. But community is sharing, so I started searching for a place to put this list on.
- https://www.home-assistant.io/docs/tools/ seems to be such a place with the note:
   "Help us to improve our documentation"

Ok, so let's try. Click on `Edit` in expectation of an editor to open. But all I get is the markdown file on Github. Ok, let's try to change this. Click on `edit in place` with the message:
  "You need to fork this repository to propose changes."

Really? I shall fork the complete project just to add a table in one side of the documentation. Now I know, why this page is almost empty and why "blame" shows it was made this way 6 years ago. Asking Google for a Wiki about Home Assistant shows only some Wiki with HA as a side aspect and some who are just trying to create content for their advertising.

What makes the situation even more worse for the HA beginner is the inconsistent wording. As an example the helper called "Dropdown" in the GUI can not be found as
- https://www.home-assistant.io/integrations/dropdown/

An AI tool gave me the hint, that in the documentation and in the YAML code it is called `input_select`.
- https://www.home-assistant.io/integrations/input_select/

Using a different language than English makes the situation even more worse. Absolutely great in my humble opinion, would be a MediaWiki that is linked from within the HAss-GUI. Click on `Help` and get a community edited documentation in the way hundreds of MediaWikis around the world do this job.

### URL

https://www.home-assistant.io/docs/tools/

### Version

2023.12.4

**Comment by thibaultmol** [comment]
And the thing is that the documentation actually says that it should be able to edit in place, yet that is not enabled for some reason: https://developers.home-assistant.io/docs/documenting/
![image](https://github.com/home-assistant/home-assistant.io/assets/1010226/eaba6aae-e011-4d64-a1b8-a0466a40e268)

**Comment by frenck** [comment]
MediaWiki can't handle the branching we need, unfortunately. Making it unsuitable, nevertheless, thanks for your suggestion 👍

Every page that can be edited, has an edit link at the bottom of the page. (Same place where this feedback was also provided).

**Comment by thibaultmol** [comment]
> Every page that can be edited, has an edit link at the bottom of the page. (Same place where this feedback was also provided).

Which works but if you don't already have a fork of the proejct, you can't edit. You need to create a fork. Feel free to try using a github account that doesn't have a fork of the repo

**Comment by frenck** [comment]
You can, GitHub will allow creating a fork. Additionally we have full blown codespaces enabled as well.

We receive tons of edits each month using both methods.

**Comment by thibaultmol** [comment]
Aren't you always making a fork, even if it's using codespaces?

I'm just confused about the wording on the page "without creating a fork". shouldn't it be "you don't need to manually create a fork, it happens automatically" or something?

**Comment by frenck** [comment]
You always need a fork, unless one is an org member. This is how GitHub works
