### ISSUE TITLE
The requested url is not given by default and no hint?

### ISSUE THREAD

**Issue by guffedk** [home-assistant/home-assistant.github.io#30573]
### Feedback

The requested url is not given by default and no hint - I found this on reddit and hope it is correct? http://core-silabs-multiprotocol:8081

### URL

https://www.home-assistant.io/integrations/otbr/

### Version

2023.12.4

**Comment by cadamini** [comment]
Interesting. I found [instructions for the mentioned add-on](https://github.com/home-assistant/addons/blob/master/silabs-multiprotocol/DOCS.md) and an [active community discussion](https://community.home-assistant.io/t/find-rest-api-url-of-apple-thread-border-routers-apple-tv-homepods/550362/20). 

This recent [community discussion ](https://community.home-assistant.io/t/openthread-border-router-support/540715/29 )seems to confirm the URL you have found (scroll at least down to the middle to the answers from francispFrancis and wmaker in October 2023).
