### ISSUE TITLE
Problème de connexion a la box

### ISSUE THREAD

**Issue by DocJackson** [home-assistant/home-assistant.github.io#30579]
### Feedback

Bonjour à tous !
Je viens à vous aujourd'hui car j'ai un problème avec l'intégration SFR Box. Lorsque je tape l'adresse IP de ma mox (l'adresse hôte) cela ne fonctionne pas ! Je sais pas comment faire si quelqu'un peut m'aider..

### URL

https://www.home-assistant.io/integrations/sfr_box/

### Version

2023.12.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
