### ISSUE TITLE
Documentation is inadequate

### ISSUE THREAD

**Issue by alpual** [home-assistant/home-assistant.github.io#30586]
### Feedback

The documentation says `Follow the instructions on screen to complete the setup`. How? It want's me to put in a host. I tried the address my router assigned the wall charger, but that doesn't work. 

Also, the documentation doesn't describe the features that this provides. What info can I get? 

### URL

https://www.home-assistant.io/integrations/tesla_wall_connector/

### Version

2023.12.4

**Comment by cadamini** [comment]
"Follow the instructions on the screen to complete the setup." comes from an \_include file that contains generic repeatable steps and which is used about 500 times in the code:
- [Include file](https://github.com/home-assistant/home-assistant.io/blob/94d6678e25f51ec45e131bf55bdfa305dcfcb03e/source/_includes/integrations/config_flow.md?plain=1#L35).
- Include file [usage across the code base](https://github.com/search?q=repo%3Ahome-assistant%2Fhome-assistant.io+%22%7B%25+include+integrations%2Fconfig_flow.md+%25%7D%22&type=code)

Sometimes, writers assume that on-screen instructions are clear and do not need more details.

The [Gen 3 Tesla docs PDF file](https://www.tesla.com/sites/default/files/support/charging/Gen3_WallConnector_Installation_Manual.pdf) mentions **a web
browser commissioning interface**, contains screenshots and says this on page 28, step 2 to 4: 

> -  Use a Wi-Fi-enabled device such as a smart phone to connect to the SSID Wi-Fi signal broadcasted by
the Wall Connector. Joining the Wall Connector network can be done by scanning the sticker QR code
on the Quickstart Guide cover page, or by manually selecting the network and typing in the WPA2
password (found on the sticker on the Quickstart Guide cover page).
> - Scan the QR code below with the device that is connected to the Wall Connector to access the web
browser commissioning interface. Alternatively, manually type the URL address (http://192.168.92.1)
into the web browser.
> - Follow the onscreen commissioning steps on the web browser to assign Wall Connector to its own
circuit breaker and connect it to the local site Wi-Fi network.

For this Tesla case, I would (directly) link to the PDF or at least refer to it.
