### ISSUE TITLE
Workday Integration doesn't specify Holidays in the list

### ISSUE THREAD

**Issue by exeljb** [home-assistant/home-assistant.github.io#30588]
### Feedback

There's a warning on the page with the following sentence: "But it is meant to exclude the days in the holiday list from the workdays.", but there's no list of holidays on the page that Home Assistant considers holidays.  This should be clarified so automations run as expected when setup as excluding certain days.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2023.12.4

**Comment by gjohansson-ST** [comment]
Can you elaborate what you mean?
Or perhaps give an example as it's pretty difficult to understand what issue is here.

**Comment by exeljb** [comment]
There's mention on that page as well about public holidays identified by the holidays module.  I guess I'm looking for an explanation of what's in that holiday module?  

I'm assuming days like Thanksgiving, Christmas and New Years are considered holidays but what about days like Veterans Day, Columbus Day, or Valentines day...are those days also considered holidays to HA?  

I've been using yaml in the past where I'd just paste holiday dates from my work calendar into the config and this is the first time having to use the integration through the UI which has been a bit clunkier than years past.  I miss those days of just plopping the new dates in the config or just changing the year digit to the new year.

**Comment by gjohansson-ST** [comment]
We won't add that to the documentation page as it obviously differ from country to country and in some cases sub-region. 
You will have to check that library for your country to see what it adds as a holiday or possibly not. 

The intention is of course that what you need to configure is the additional holidays you might have or if you need to remove some.

**Comment by gjohansson-ST** [comment]
Btw; In the next release (2024.1) there is a `holiday` integration coming in based on the same library so then you get a calendar with all those public holidays which is perhaps also an easier way to see which dates are considered (or not).

**Comment by exeljb** [comment]
Yea that makes sense about all the different regions and such.  That holiday integration sounds interesting.  That’ll be one of the first things I’ll checkout when it releases.  What it comes down to for me is I wish there was an option to edit in yaml, similar to how Lovelace cards have the option to edit in yaml.  Best of both worlds…
I’ll close this since it was for feedback on the documentation. Thanks for looking into it.
