### ISSUE TITLE
Configuration problem "dew_point"

### ISSUE THREAD

**Issue by davcolme** [home-assistant/home-assistant.github.io#30581]
### Feedback

I'm having problems adding the Aemet integration. After entering the APY KEY and leaving the longitude and latitude values when creating the integration and synchronizing, it gives me an error:

(MainThread) [homeassistant.components.aemet.weather_update_coordinator] Unexpected error fetching aemet data: 'Station' object has no attribute 'dew_point'

What can I do to solve it?

Thanks.

### URL

https://www.home-assistant.io/integrations/aemet/

### Version

2023.12.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
