### ISSUE TITLE
Epson LS12000B

### ISSUE THREAD

**Issue by bsoener** [home-assistant/home-assistant.github.io#30591]
### Feedback

Hello, I have an Epson LS12000B Projector. I would like to integrate it into the Home Assisstent so that I can control it. When adding the projector, I get the following error message in the Ip assignment setting: Unknown error ocurred. I would appreciate some help.

### URL

https://www.home-assistant.io/integrations/epson/

**Comment by pszafer** [comment]
Do you have projector turned on during initialization?

**Comment by bsoener** [comment]
Yes, of course. The Ip is also listed on my Fritzbox

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
