### ISSUE TITLE
Failed setup, will retry

### ISSUE THREAD

**Issue by Aresitoo** [home-assistant/home-assistant.github.io#30596]
### Feedback

The integration works, but often for unknown reason stops working a while and gives the error Failed setup, will retry. Resulting in the entities being unavailable, saying it's not possible to retrieve information from meteoclimatic
I'm using station ESMAD2800000028341B

### URL

https://www.home-assistant.io/integrations/meteoclimatic/

### Version

2023.12.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
