### ISSUE TITLE
Support for TP902

### ISSUE THREAD

**Issue by cybernard** [home-assistant/home-assistant.github.io#30606]
### Feedback

anyway we can add support for the TP902?

### URL

https://www.home-assistant.io/integrations/thermopro/

### Version

2023.12.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
