### ISSUE TITLE
Goodwe Wallbox support

### ISSUE THREAD

**Issue by Patoche86** [home-assistant/home-assistant.github.io#30602]
### Feedback

While integration of Goodwe inverter return many information and sensors are collected there is no integration or data available for GoodWe Wallbox (model GW22K-HCA in my case).
This Wallbox is available in SEMS app already.

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2023.12.4

### Additional information

Wallbox support in SEMS is visible at the bottom of the screen
![Screenshot_20240102_180835_SEMS Portal](https://github.com/home-assistant/home-assistant.io/assets/132708240/70e096b4-ae7d-4760-b3d2-c26e6ccff10a)

**Comment by mletenay** [comment]
First of all, this repo is for the documentation/web page, not the code itself.
Second, the scope of the goodwe integration is the inverter and it is unlikely other goodwe products like wallboxes will be supported any time soon, if ever.

**Comment by mletenay** [comment]
@home-assistant close
