### ISSUE TITLE
securing - documentation issue

### ISSUE THREAD

**Issue by pit-pitek** [home-assistant/home-assistant.github.io#30600]
### Feedback

I'm using Duckdns.org for DDNS.
I would like to have https for my HA. 
I use subdomen and access token that is mention in this documentation. 
Next step is:  Service set_txt

What is it? 
Where to set it up? 
How to do it? 

I was looking for any place where it can be putted but wans't able to find it. 
Please, provide a little more information about that step. 

### URL

https://www.home-assistant.io/integrations/duckdns/

### Version

2023.12.4

**Comment by LalaDK** [comment]
I'm agree with you @pit-pitek - what to do from here ...
Did you ever find a solution? 

I'm currently in the same boat.

**Comment by pit-pitek** [comment]
Hi,

I set it up. But it was long time ago. 

I remember that I spend some time in duckdns configuration file. and my YAML looks like that:

domains:
  - subdomain.duckdns.org
token: ********-****-****-****-************
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 600


As I found with this set_TXT - you don't have to do anything as it is about DNS record in DNS server. 
I don't remember if I needed to set up certificate or it was automaticly. 

Hope it will help you.
