### ISSUE TITLE
The back button command is BACK

### ISSUE THREAD

**Issue by Gankenz** [home-assistant/home-assistant.github.io#30604]
### Feedback

in the examples, the back button isnt included, but its command is back

### URL

https://www.home-assistant.io/integrations/androidtv_remote/

### Version

2023.12.4

**Comment by tronikos** [comment]
Fixing this in https://github.com/home-assistant/home-assistant.io/pull/30605
I'm adding POWER that was also missing
We missed copying these from https://github.com/tronikos/androidtvremote2/blob/main/TvKeys.txt
