### ISSUE TITLE
Add SMUD (Sacramento Municipal Utility District) to Opower Virtual Integration

### ISSUE THREAD

**Issue by nebhead** [home-assistant/home-assistant.github.io#30624]
### Feedback

As the title suggests, SMUD (Sacramento Municipal Utility District) uses Opower to track energy usage for their users and thus it would be wonderful if we could extend Home Assistant to list this provider as well.  (https://SMUD.org)

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2024.1.0

**Comment by nebhead** [comment]
SMUD uses https://smud.opower.com to access customer data.

**Comment by tronikos** [comment]
I don't have SMUD so I can't be of any help. Core maintainers also don't like using github for feature requests. You can follow along https://github.com/tronikos/opower/issues/54

**Comment by tronikos** [comment]
@home-assistant close
