### ISSUE TITLE
Drop Firmware Requirement?

### ISSUE THREAD

**Issue by efaden** [home-assistant/home-assistant.github.io#30627]
### Feedback

I have a drop and don't see the mqtt options at all.  Is there a minimum firmware that's required?  Would be nice to include details like that or which products or works with because it's not clear 

### URL

https://www.home-assistant.io/integrations/drop_connect/

### Version

2024.1.0

**Comment by pfrazer** [comment]
Hi, @efaden - You are correct that the controls for MQTT connection are not yet available in the DROP Connect app.  The DROP firmware and app updates that will enable MQTT integration with Home Assistant should start beta testing sometime next week.

The minimum hub firmware versions to connect with Home Assistant are 1.84 (Hub 1) and 2.14 (Hub 2).  These firmware versions will be carried by app versions 1.1.32 (Android) and 1.0.53 (iOS).

I will leave this issue open until the new apps and firmware are fully available to all users, and I will also update the issue with information about getting beta versions of the DROP Connect apps once the apps have begun beta testing.

**Comment by efaden** [comment]
Thanks!

**Comment by pfrazer** [comment]
The DROP Connect app and firmware versions mentioned above are now available in the DROP beta test programs.  If you install these app and firmware versions, you will find the 'Configure MQTT' button on the DROP Connect app **System > Advanced** page.

For Android devices, go to the [DROP Connect](https://play.google.com/store/apps/details?id=com.chandlersystemsinc.dropconnect) Google Play Store listing and find the 'Join the beta' section of the store listing.

For iOS devices, use the DROP Connect [Testflight invitation](https://testflight.apple.com/join/2HLdpc8H).  This link will provide instructions for installing TestFlight and joining the DROP beta program.

**Comment by efaden** [comment]
Little bit closer.  Installed the firmware, but configuring mqtt doesn't seem to work.

I see the attempted connection in the mqtt log, but then nothing ... eventually I see Client DROP-XXXX has exceeded timeout, disconnecting.

**Comment by klaasnicolaas** [comment]
Please note that we use the github issue tracker in this repository for documentation issues.

Integration issues should be in core 😉

./Klaas

**Comment by pfrazer** [comment]
@home-assistant close
