### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by Harvsch** [home-assistant/home-assistant.github.io#30622]
### Feedback

The documentation instructs to define a hygrostat through a configuration.yaml entry. The system the balks at its presence and instructs me that hygrostats have to be added through the integration. When I try to enter the hygrostat through the integration, I get a dialog box instructing me that hygrostats have to be entered through the yaml configuration.

### URL

https://www.home-assistant.io/integrations/generic_hygrostat/

### Version

2024.1.0

**Comment by Harvsch** [comment]
The functionality of a hygrostat and a thermostat is so similar that it amazes me that they aren't handled in the same way. Perhaps the best improvement would be to merge these functions and at the same time allow more control over labels that appear on the user interface. This is after all the basis of all simple bang-bang control systems.

**Comment by photomatix18** [comment]
I'm finding the same issue to be true for me.

**Comment by photomatix18** [comment]
@Harvsch, i just discovered I had a HACS integration installed called Generic Hygrostat that was causing the problem. Uninstalled that and it fixed it right away.
