### ISSUE TITLE
unifiprotect: Admin url example out of date?

### ISSUE THREAD

**Issue by reedy** [home-assistant/home-assistant.github.io#30626]
### Feedback

On https://www.home-assistant.io/integrations/unifiprotect#local-user

>2. Go to **Admins** from the left hand side menu or [IP address]/admins/users e.g. 192.168.1.1/admins/users.
>3. Click on **Add New Admin**.
>4. Select **Full Management** for the role. Uncheck **Allow Remote Access** and fill out the fields for your user.

At `https://udm/admins/users` I only see "Add user" which goes to `https://udm/admins/users/add`

If I go to `https://udm/admins/` I do see a "Add Admin" which goes to `https://udm/admins/add-admin`

UDMPRO UniFi OS 3.2.7

Not sure if this workflow has recently changed slightly in an update, or it's just different on my device?

![Screenshot 2024-01-04 at 00 41 35](https://github.com/home-assistant/home-assistant.io/assets/67615/7e26d923-7c41-4a8c-b8d2-2107ae8b5bcf)
![Screenshot 2024-01-04 at 00 41 49](https://github.com/home-assistant/home-assistant.io/assets/67615/69f36b2b-66a2-4cc6-b630-c984a3e26f02)
![Screenshot 2024-01-04 at 00 41 44](https://github.com/home-assistant/home-assistant.io/assets/67615/9e831eac-fb8f-4ba7-a877-193e771381e5)

![Screenshot 2024-01-04 at 00 43 26](https://github.com/home-assistant/home-assistant.io/assets/67615/e93d9b7f-ffc1-48a2-aee4-6970842fb618)

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2024.1.0

**Comment by AngellusMortis** [comment]
It literally changes every release. Someone probably just has to update it again.

**Comment by reedy** [comment]
Haha, fair enough. Happy to do a PR to do it

**Comment by AngellusMortis** [comment]
It is also generally different if you have remote access enabled or disabled and/or if you set up your console originally with a UI Cloud account.

**Comment by thibaultmol** [comment]
also about this documenation: you can perfectly do it from the unifi cloud page. You just need to make sure you're creating an 'admin' account (which you can give read only permissions so it can't actually do anything, for example) and not a 'user'
![annotely_image(19)](https://github.com/home-assistant/home-assistant.io/assets/1010226/b62dc0c2-576e-4961-a630-f699b49943f5)

**Comment by thibaultmol** [comment]
still relevant

**Comment by thibaultmol** [comment]
please reopen 

It's still relevant and will be until it's fixed. https://fvsch.com/stale-bots
