### ISSUE TITLE
The steps need more information

### ISSUE THREAD

**Issue by Shwamp** [home-assistant/home-assistant.github.io#30637]
### Feedback

Copuld not get this to work for a long time, a Year, now I found this blog post and followed the instructions, so now its working again.

I followd the guide by [CinRyan][Ryan Williamson] [Aug '23] and now it works again!
https://community.home-assistant.io/t/withings-intgration-doesnt-work/514398/21

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2024.1.0

**Comment by joostlek** [comment]
When did you follow the instructions? They are outdated since November :)

**Comment by Shwamp** [comment]
Hello!About 30 minutes ago I follows the blog post :)4 jan. 2024 kl. 11:51 skrev Joost Lekkerkerker ***@***.***>:﻿
When did you follow the instructions? They are outdated since November :)

**Comment by joostlek** [comment]
Right, I'll try to find some time to check the difference, but it will take some time till I have time for it

**Comment by Shwamp** [comment]
Thanks! Great work with the integration btw :)
