### ISSUE TITLE
Pair a speaker to an Assist device to send audio output to

### ISSUE THREAD

**Issue by motoridersd** [home-assistant/home-assistant.github.io#30644]
### Feedback

Most of the entry level (ie cheaper) devices to trigger voice commands in Home Assistant have pretty small and tinny speakers. I can create an Assist automation that will listen to sentences and perform actions, while also having it play tts audio on a different speaker. Say I have a Sonos speaker in the same room, the response can be played on the Sonos speaker instead of the tiny Atom Echo.

This works with Assist automations, but for all existing Assist commands, it would be nice to set up an output speaker for each Assist device. For example, the "Bedroom Atom Echo" will send its output to the Sonos Bedroom Media Player.

### URL

https://www.home-assistant.io/voice_control/

### Version

2024.1.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
