### ISSUE TITLE
Missing the Pmd in zakken option

### ISSUE THREAD

**Issue by Nelus2311** [home-assistant/home-assistant.github.io#30643]
### Feedback

Hello,

Thank you for creating the Rova integration. After i checked out the intergration i am missing the option "pmd in zakken"
Where i live we don't use use the plastic option only pmd in zakken (plastic in a bag).

my  question: can you implement the option pmd in zakken.

Picture of the calendar of January 
![rova](https://github.com/home-assistant/home-assistant.io/assets/78924552/c0e7a67a-18ee-47ed-a7c9-f3b3b1a6f4df)

Thanks Niels

### URL

https://www.home-assistant.io/integrations/rova/

### Version

2024.1.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
