### ISSUE TITLE
inkbird wifi temperature  sensor 

### ISSUE THREAD

**Issue by giuseppe072000** [home-assistant/home-assistant.github.io#30657]
### Feedback

is possible to read data over wifi from Inkbird IBS-TH3 ?

what other options are to read data from IBS-TH3 ?

### URL

ne.net.org

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
