### ISSUE TITLE
How do I reset a device running on Raspi after losing the username/password?

### ISSUE THREAD

**Issue by MikeJ67** [home-assistant/home-assistant.github.io#30654]
### Feedback

The online documentation tells me 

"If you do not have a backup, resetting the device will erase all data."

But I don't find info about how to do that.

I can access a "ha" cli, but I can't manage to stop a "running dmesg log", therefore I can' log in as root.
But even if I could, what are the commands to reset the device?

I am a complete newbie to HASS, please help me with this! G**gle didn't give me a clear route...

### URL

https://www.home-assistant.io/docs/locked_out/

### Version

2024.1.0

**Comment by c0ffeeca7** [comment]
For Home Assistant Operating System, there are now 2 new commands: 
- listing all users from the command line: #31932 
- wiping the data disk: #31932
