### ISSUE TITLE
Ambiguous description of `Precision` and `round` for Integration (Riemann sums)

### ISSUE THREAD

**Issue by DDvO** [home-assistant/home-assistant.github.io#30658]
### Feedback

In both places, the text says:
> Round the calculated integration value to at most N decimal places.

I misinterpreted this as the number of factional digits (after the comma), 
but then noticed from the output that this is not meant, but the number of significant digits.
~For instance, a sum of 123 is output as 120.~

Moreover, it is not clear when the rounding takes place: for each addition or at (final) output reading only?

### URL

https://www.home-assistant.io/integrations/integration/

**Comment by dgomes** [comment]
It's exactly the samething, and it is a round() function:

https://github.com/home-assistant/core/blob/6033a7c3d44e6bd452c3442ea59154bebfaa8f1d/homeassistant/components/integration/sensor.py#L398C16-L398C16

**Comment by DDvO** [comment]
Thank you for pointing to the code, where I was able to verify that 
* the rounding is done on output only, which is good
* it indeed rounds to the given number of digits after the comma - 
I had been confused by a computation that I was doing after getting the integration output.

Anyway, please expand the text to prevent misunderstandings, e.g., to:

> Round the output of the calculated integration value to at most N decimal places (fractional digits).

**Comment by dgomes** [comment]
feel free to open a PR :)
