### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by sdavie-dev** [home-assistant/home-assistant.github.io#30664]
### Feedback

I have had this up and running for a long time and a handy way to show me the next buses and trains:

If I remove the first part I no longer have any updated info for the next 3 buses. How can I get this running again. I have the next bus time in an unreadable format but i need to know the next few buses. This is an exerpt from my old configuration.yaml: 

`  - platform: swiss_public_transport
    from: Bern, Länggasse
    to: Bern, Bahnhof
    name: bernmobil_l2b
  - platform: template
    sensors:
      next_bus:
        friendly_name: "Next Bus:"
        icon_template: mdi:bus-side
        value_template: '{{ as_timestamp(states.sensor.bernmobil_l2b.state)| timestamp_custom("%H:%M", True) }}'
      2nd_bus:
        friendly_name: "2nd Bus:"
        icon_template: mdi:bus-side
        value_template: '{{ as_timestamp(states.sensor.bernmobil_l2b.attributes.next_departure)| timestamp_custom("%H:%M", True) }}'
      3rd_bus:
        friendly_name: "3rd Bus:"
        icon_template: mdi:bus-side
        value_template: '{{ as_timestamp(states.sensor.bernmobil_l2b.attributes.next_on_departure)| timestamp_custom("%H:%M", True) }}'`

### URL

https://www.home-assistant.io/integrations/swiss_public_transport/

### Version

2024.1.0

**Comment by miaucl** [comment]
Duplicate https://github.com/home-assistant/core/issues/107073#issuecomment-1877701312

**Comment by miaucl** [comment]
There is currently a problem with the `unique_ids`, therefore once you have more than one entry, it fails. Revert back to the previous version or wait for this [PR](https://github.com/home-assistant/core/pull/107087#discussion_r1441729928) to be patched.
