### ISSUE TITLE
Definition of previous month

### ISSUE THREAD

**Issue by bialeta** [home-assistant/home-assistant.github.io#30667]
### Feedback

Current template provided on website:

Previous month: starts the first day of the previous month at 00:00, ends the first day of the current month.
_start: "{{ now().replace(day=1, **month=now().month-1**, hour=0, minute=0, second=0, microsecond=0) }}"
end: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"_

Template is valid except january. If you subtract 1 from 1 you will get 0. There are only months from 1 to 12, no others, espeially 0. There should be an exception for january - if month is 1 then set 12 for previous month.

### URL

https://www.home-assistant.io/integrations/history_stats/

### Version

2024.1.1

**Comment by brooqlyn** [comment]
start: "{{ now().replace(year=now().year-1 if now().month==1 else now().year,day=1, month=12 if now().month==1 else now().month-1, hour=0, minute=0, second=0, microsecond=0) }}"
