### ISSUE TITLE
FAQ missing

### ISSUE THREAD

**Issue by catalineacsu** [home-assistant/home-assistant.github.io#30674]
### Feedback

it would be nice to include basic fail cases and how to check/debug them. I for example can't see the device in the list after following the steps. What should I do next???

### URL

https://www.home-assistant.io/integrations/openhardwaremonitor/

### Version

2024.1.1

**Comment by felipedsouza** [comment]
Also stuck here. Not sure what to do after including openhardwaremonitor to the config.yaml

**Comment by catalineacsu** [comment]
I finally made it work. So, one thing you need to do is reload yaml configuration by going to Developer Tools->YAML->Restart (see image). "Check configuration" will prevent restarting with a bad yaml file.
In my case the windows firewall setting was useless, since I had an antivirus whose firewall also needed an update.
![image](https://github.com/home-assistant/home-assistant.io/assets/78691750/f2f541e1-bef0-4917-ac65-368223f35f4b)
