### ISSUE TITLE
Developer Tools: Combined service and templating area

### ISSUE THREAD

**Issue by freddeh** [home-assistant/home-assistant.github.io#30675]
### Feedback

Dear all,
With response_variables getting more and more and rather complex feedback e.g. on calendar events for newbies like me it would just make everything so much easier and within one flow if I could somehow use the response variables from service calls directly within templating. Either through ‘tranfer sample data to templating’ or a combined tab that allows users to first enter service calls and use the data in a templating section below in ‘live mode’. 

Maybe it would already be interesting to understand how more advanced users achieve their goals with more complex topics without constantly switching from automations, scripts to developer tools.

Best regards
freddeh

### URL

https://www.home-assistant.io/docs/tools/dev-tools/

### Version

2024.1.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by freddeh** [comment]
Thanks for the explanation. I then misunderstood the "feedback" button from the Developer Tools Documentation, I guess.
