### ISSUE TITLE
Ecowitt brack problem

### ISSUE THREAD

**Issue by Upsurfer1** [home-assistant/home-assistant.github.io#30670]
### Feedback

I have a previous integration of ecowitt  (no hack). It should be nice to make it possible to remove this old version. Because I can not install the new version. A good explenation could als help, because I have not such an old backup version.

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2024.1.1

**Comment by Meyer3** [comment]
Make sure you have deleted all Integration Entries (shown on the right side of the Ecowitt integration). 
Then restart HA. 
If there is one invalid Integration Entry left, HA will not uninstall Ecowitt and you cannot install a newer version.

**Comment by frenck** [comment]
> I have a previous integration of ecowitt (no hack). It should be nice to make it possible to remove this old version

There is no previous version in Home Assistant. I guess you have a custom integration. Please note, that we don't manage, recommend or support the use of custom integration. This is up to you to manage/decide and not something in our control.

../Frenck
