### ISSUE TITLE
Link takes you to the page you are on.

### ISSUE THREAD

**Issue by GOTAZ** [home-assistant/home-assistant.github.io#30671]
### Feedback

Step 5 tells you to open a browser and open this procedure which is hyperlinked, however it takes you to the page you are on.

In Ubuntu, open a browser and open [this procedure](https://www.home-assistant.io/installation/generic-x86-64).
From there, [download the image](https://github.com/home-assistant/operating-system/releases/download/11.3/haos_generic-x86-64-11.3.img.xz).

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2024.1.1

**Comment by c0ffeeca7** [comment]
That is correct. The idea was that you open this procedure (the page you are on) in Ubuntu, so you can follow the procedure there.  But I can see how this can be confusing and make you think that there is a broken link.
