### ISSUE TITLE
province should have human readable names

### ISSUE THREAD

**Issue by nerdoc** [home-assistant/home-assistant.github.io#30680]
### Feedback

When using e.g. "Austria" as country, the "provinces" should be named accordingly, not just only numbers...
![grafik](https://github.com/home-assistant/home-assistant.io/assets/2955584/e716dee1-cfcd-4056-994e-8a20ef0376a3)

### URL

https://www.home-assistant.io/integrations/holiday/

### Version

2024.1.2

**Comment by JohnSabol55** [comment]
additional Info to Austrian Holidays - the Provinces in Austria have some Holidays that other doesnt.
https://www.feiertage-oesterreich.at/

**Comment by jrieger** [comment]
It seems you want to report an issue with the Home Assistant integration. You have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

If you think there are holidays missing for specific regions in Austria, please consider contributing to [python-holidays](https://github.com/vacanza/python-holidays). Home Assistant does not provide holiday data by itself; instead, it relies on this library.

Thanks!

**Comment by jrieger** [comment]
@home-assistant close
