### ISSUE TITLE
System monitor documentation is lacking

### ISSUE THREAD

**Issue by wioxjk** [home-assistant/home-assistant.github.io#30683]
### Feedback

Hi,
There is no clear path in how to set up system monitor.
The documentation claims it should be installable in HA, but when I click on install - I am just looped back to the documentation

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2024.1.2

**Comment by frenck** [comment]
Which version of Home Assistant are you using @wioxjk?

../Frenck

**Comment by greenreader9** [comment]
Hello

Experiencing the same issue.

Core: 2023.12.4
OS: 11.2

I'll try updating and trying again

EDIT: Updated and it works now.

**Comment by gjohansson-ST** [comment]
@wioxjk still an issue?

**Comment by gjohansson-ST** [comment]
Closing as resolved after update
