### ISSUE TITLE
Nest troubleshooting doc uplift

### ISSUE THREAD

**Issue by nayfield** [home-assistant/home-assistant.github.io#30685]
### Feedback

Using a new HA yellow device, the one missing part in the documentation was that I needed to (at the very last step connected to home-assistant.io) modify my URL to be http and include the port number (it was https without a port number, eg 443).  

Once I did that, it gave me a blank screen ... *but* when going back to the original HA window it said auth completed.

### URL

https://www.home-assistant.io/integrations/nest/#troubleshooting

**Comment by allenporter** [comment]
I am not sure what you're referring to. You shouldn't need to modify any urls, unless you're saying your `my home assistnat` configuration was incorrect already for some reason?

**Comment by nayfield** [comment]
Steps to reproduce:

1. buy a yellow device and set it up per the instructions
2. after install, but before it boots the first time, give it's mac a
static DHCP mapping with domain name ha.my-domain.com
3. boot system  ... you can access it at http://ha.my-domain.com:8123/
4, follow guide exactly
5. Last step, after confirming granular device access, then account access,
you are sent to the home-assistant.io redirect uri
6. On that page, it tells that it will redirect you to
https://ha.my-domain.com/ if you hit the button.


if you don't click the pencil while on home-assistant.io and change to http
and add the port, it won't work, because the yellow is not listening on
port 443.

If you do change, you get a blank white screen.  (it actually worked, but
there's no sign of that until you close the empty tab and go back to where
you started)

I can reproduce this all day long

**Comment by allenporter** [comment]
Adding `my` label. I think the issue is not specific to the nest instructions, but more about initial my home assistant setup. It should give you the right url from the start.

**Comment by allenporter** [comment]
(Perhaps this is not a documentation issue though)

**Comment by MartinHjelmare** [comment]
Did you configure My Home Assistant before setting up the nest integration?

https://my.home-assistant.io/

**Comment by nayfield** [comment]
I did not.  The docs for my seemed to say it doesn't need configuration,
and it's not mentioned in the nest instructions.

Maybe the fix for this ticket is :

1. Link to a pre req doc that shows you how to verify my is set up
correctly and you can link back to my from .io

2. Explain the blank page after oauth dance and that you should close it
(or have the local my oauth endpoint print a success message)

**Comment by MartinHjelmare** [comment]
Normally there shouldn't be any blank page if the oauth2 flow works correctly. I don't know if the nest integration has some peculiar behavior here but I'm guessing it was a result from the missing config for My Home Assistant.

It is mentioned in the nest instructions that My Home Assistant is used. It should link more clearly to it up front and be explicit that it's need to be configured correctly, though.

**Comment by nayfield** [comment]
>  It should link more clearly to it up front and be explicit that it's
need to be configured correctly, though.

agreed.  https://www.home-assistant.io/integrations/my/ seems to imply
there's no configuration (just add my: ) ...

It could be as simple as:

* Ensure that the link at My (https://my.home-assistant.io/) takes you to
the correct URL to reach your HA instance.

**Comment by allenporter** [comment]
To be fair, it starts with "To add the Nest integration to your Home Assistant, use this My Button" so that step should mean things are setup properly. Though I realize you can just start the integration install without going through the docs.

The change to use my home assistant happened to update how oauth works across all integrations, not specific to nest really.  Perhaps we want to change an include file or doc template for all oauth integrations if this isn't clear?

**Comment by MartinHjelmare** [comment]
Yes, a template that we can include for these integrations sounds good. 👍
