### ISSUE TITLE
sonnof energy meter wrong divece class

### ISSUE THREAD

**Issue by sot1964** [home-assistant/home-assistant.github.io#30694]
### Feedback

state_class: total
unit_of_measurement: kWh
friendly_name: Meterkast Energy Day

must be *state_class: total
unit_of_measurement: kWh
**device_class: power**
friendly_name: Meterkast Energy Day
**

### URL

https://www.home-assistant.io/docs/energy/faq/

### Version

2024.1.2

**Comment by frenck** [comment]
Hi there @sot1964 👋 

It seems like you want to report an issue with an integration, but you have submitted feedback instead. Please report issues with Core integrations in our Core issue tracker. In case this is a custom integration, please report the issue with the custom integration author.

Thanks! 👍 

../Frenck
