### ISSUE TITLE
'Got home data' not appearing

### ISSUE THREAD

**Issue by 2xmy** [home-assistant/home-assistant.github.io#30699]
### Feedback

The 'Got home data' does not appear in the logs after reloading.
Roborock S6 in this case.

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2024.1.2

### Additional information

**
![Udklip](https://github.com/home-assistant/home-assistant.io/assets/155847673/ecb0a25c-6a7b-44a0-a83b-7ec2a3ac39e6)
**

**Comment by Lash-L** [comment]
You are looking in the wrong logs. Go to settings->system -> logs instead

**Comment by Lash-L** [comment]
@home-assistant close
