### ISSUE TITLE
Mill local integration

### ISSUE THREAD

**Issue by ThomasThomsen01** [home-assistant/home-assistant.github.io#30697]
### Feedback

When using local integrations (gen3) it is not possible to set or control the temperature, would be nice to control the device without cloud access

### URL

https://www.home-assistant.io/integrations/mill/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
