### ISSUE TITLE
Error growatt server

### ISSUE THREAD

**Issue by fredbaltus** [home-assistant/home-assistant.github.io#30692]
### Feedback

Hi, the connection to server-api.growatt.com gives an error … unknown error command. If I typed it in a browser I go also an error ..405 Sorry, your request has been blocked as it may cause potential threats to the server's security.
Your request ID is : 0bc1a08817045874964697617e3107…

When I go to server.growatt.com it works fine.. Can you change const.py?

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.2

### Additional information

See Abordnung

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
