### ISSUE TITLE
Only legacy service examples

### ISSUE THREAD

**Issue by kshunterco** [home-assistant/home-assistant.github.io#30691]
### Feedback

The documentation states "We recommend new users to instead set up the integration in the UI and use the tts.speak service with the corresponding Google Translate text-to-speech entity as target." but there are no examples of how to do this, only examples using google_translate_say, which is described as a legacy platform. 

### URL

https://www.home-assistant.io/integrations/google_translate/

### Version

2024.1.2

**Comment by sotpotatis** [comment]
Second this! Would love to have some examples.
