### ISSUE TITLE
Running with privileged: true

### ISSUE THREAD

**Issue by bardahlm** [home-assistant/home-assistant.github.io#30707]
### Feedback

According to https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-3-limit-capabilities-grant-only-specific-capabilities-needed-by-a-container one should never run a container with the --privileged flag.

The documentation should provide a rationale for setting the privileged flag and maybe also a warning. The best solution would be documenting what's needed to run the container without that flag.

### URL

https://www.home-assistant.io/installation/alternative/

### Version

2024.1.2

**Comment by frenck** [comment]
It all depends on the integrations used and thus cannot be determined up front.

You are free to harden your system if you like that.

👍 

../Frenck
