### ISSUE TITLE
Additional models A.O. Smith works with

### ISSUE THREAD

**Issue by MediaArtsDad** [home-assistant/home-assistant.github.io#30704]
### Feedback

This also works with the HPS10-50, HPS10-80, HPV10-50, HPV10-80 models of the AO Smith water heaters

### URL

https://www.home-assistant.io/integrations/aosmith

**Comment by bdr99** [comment]
Thanks for the info! By the way, do you have a link to the HPV10-50 on A. O. Smith's website? I was able to find the [HPV10-66](https://www.aosmithatlowes.com/products/water-heaters/electric-water-heaters/hpv10-66h01dv/) and [HPV10-80](https://www.aosmithatlowes.com/products/water-heaters/electric-water-heaters/hpv10-80h01dv/) but not the HPV10-50.

**Comment by MediaArtsDad** [comment]
It may be a Lowe's Home Improvement special, I have only seen it here:
https://www.aosmithatlowes.com/products/water-heaters/electric-water-heaters/hp10-50h45dv/

Jeff
Essentric*
Sent with [ProtonMail](http://protonmail.com) Secure Email
