### ISSUE TITLE
Possible to add more configurations

### ISSUE THREAD

**Issue by alexderosa** [home-assistant/home-assistant.github.io#30700]
### Feedback

Hey! Astonishing work with this, I have been waiting over a year and it is so nice that it is now implemented, very easy install as well! I would like to be able to change the part showing the temperature on the front, i.e "current temperature" I do not know what value that is, but it should be the same as the one in the temperature control. Mine also says "cooling down to 18 degrees" it is actually just trying to keep 18 degrees in my apartment, so som config for that would be even better! Please see my image for reference.
<img width="544" alt="Skärmavbild 2024-01-07 kl  14 13 41" src="https://github.com/home-assistant/home-assistant.io/assets/60313558/75ac15e2-cc21-426a-bab8-39e4ea03ef4a">

### URL

https://www.home-assistant.io/integrations/flexit_bacnet/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
