### ISSUE TITLE
Example how to use MQTT events in automations in docs

### ISSUE THREAD

**Issue by red-black-bonsai** [home-assistant/home-assistant.github.io#30708]
### Feedback

It would be super helpful if there was an example in the MQTT event docs on how to use the events as triggers in an automation, including the yaml of the automation. Currently, the docs have an example with a "Desk Button" that can have event types `single` and `double`. How could I trigger an automation if (and only if) event type `single` is sent? What would need to be set in the following yaml code?

    alias: Example MQTT automation
    description: "Example MQTT automation"
    trigger:
      - platform: event???
        event_type: ???
        ???
    condition: []
    action:
        ...

### URL

https://www.home-assistant.io/integrations/event.mqtt/

### Version

2024.1.1

**Comment by jbouwh** [comment]
You are referring to an MQTT event entity. As an MQTT event entity is an entity you can just trigger on the entity's state.

**Comment by jbouwh** [comment]
https://www.home-assistant.io/docs/automation/trigger/#state-trigger

Closing this as I do not think a further example is needed.

**Comment by red-black-bonsai** [comment]
So there is no MQTT event `platform` but platform `state` should be used? Something like this?
    
    trigger:
      - platform: state
        from: "button_on"
        to: "button_on"
        entity_id: event.remote1_event

But how would I use the `event_type` defined in the MQTT event? I.e. how do I do something every time the 'on' button is pressed on the remote?
I'm guessing what I don't understand is: the remote doesn't have a state (the 'on' button doesn't stay on), how can I use it with something that assumes a state?

**Comment by jbouwh** [comment]
The `event_type` attribute will be set, so you can filter on that. Alternative is using MQTT device triggers.

**Comment by red-black-bonsai** [comment]
> The `event_type` attribute will be set, so you can filter on that. Alternative is using MQTT device triggers.

Thanks, I'll try to play around with it and report back. :)

Device triggers seem much easier to use once set up but afaiu they can only be set up through retained MQTT config messages and I'd rather have manually created config in files and not on MQTT.

**Comment by red-black-bonsai** [comment]
OK, so an automation trigger that would go with the example here <https://www.home-assistant.io/integrations/event.mqtt/#example-processing-event-data-using-a-value-template> would be this?

    trigger:
      - platform: state
        entity_id:
          - event.desk_button
        attribute: event_type
        to: single

TBH, I'd find it quite helpful to add that to the example.

What I still find unintuitive in the context of MQTT events is that this automation will trigger only once but I guess that comes with using `platform: state` because that assumes that the button has a state.
