### ISSUE TITLE
TTS Rest API parameter "engine_id"

### ISSUE THREAD

**Issue by cburn11** [home-assistant/home-assistant.github.io#30706]
### Feedback

The documentation refers to the parameter "engine_id" for the rest parameter. I think it is actually "entity_id".

### URL

https://www.home-assistant.io/integrations/tts/

### Version

2024.1.2

**Comment by MartinHjelmare** [comment]
The documentation is correct.

**Comment by cburn11** [comment]
But is it really? Passing "engine_id" in a json about results in 400 error. Passing "entity_id" succeeds.

**Comment by MartinHjelmare** [comment]
Here's the code:
https://github.com/home-assistant/core/blob/75d591593db8ca4a4ca0551272de7a5c34a67655/homeassistant/components/tts/__init__.py#L947-L973
