### ISSUE TITLE
Shelly Bluetooth proxy active/passive connection support need clarification

### ISSUE THREAD

**Issue by Nardol** [home-assistant/home-assistant.github.io#30705]
### Feedback

The Bluetooth integration documentation states the following:
> Shelly
> * Bluetooth advertisement listening: Shelly v2 device with firmware 12.0 or later
> * Bluetooth advertisement bundling: not supported
> * Single active connection: not supported
> * Multiple active connections: not supported

But the [Shelly integration documentation](https://www.home-assistant.io/integrations/shelly/#bluetooth-support) states the following about Bluetooth proxy support:
> Active or passive listening can be enabled in the options flow.

Does "Bluetooth advertisement listening" refers to both active and passive modes and Shelly devices only cannot establish connection to a device?
I understood listening was only passive but maybe I miss something about Bluetooth.

The Bluetooth documentation only specifies passive when there is explicitly the word active in the Shelly documentation.

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2024.1.2

### Additional information

I am aware this question can be only a confusion because of my knowledge (or lack of knowledge) about Bluetooth but even when searching I did not find precise information about this feature.

**Comment by wrt80** [comment]
Hi,
There is a big expectation from this integration to make:
- Single active connection
- Multiple active connections
this supported :)
