### ISSUE TITLE
My Country Ghana is not in the list of countries

### ISSUE THREAD

**Issue by eoaddai** [home-assistant/home-assistant.github.io#30713]
### Feedback

Hi, I have been enjoying the use of HA and the least i expected was to see my country Listed in this integration. Was that an oversight? 

### URL

https://www.home-assistant.io/integrations/holiday/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by jrieger** [comment]
@eoaddai it seems there is active work on adding Ghana to python-holidays: https://github.com/vacanza/python-holidays/issues/1191
