### ISSUE TITLE
Climate sensors

### ISSUE THREAD

**Issue by egrojyos** [home-assistant/home-assistant.github.io#30712]
### Feedback

Hello.  I have a vitocal 222-s with ViCare Floor Heating tThermostat and six Vicare Climate Sensors (humidity and temperature), one sensor per room.  I can't get the data from those sensors, it doesn't appear in the list of entities or devices

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2024.1.2

**Comment by CFenner** [comment]
Hi, please post the debug information of your setup (ViCare device > ... > download debug information).

**Comment by egrojyos** [comment]
Hi, here it is:
[config_entry-vicare-b835f00c3a62d0d7aecbb31be463cc30.json](https://github.com/home-assistant/home-assistant.io/files/13863805/config_entry-vicare-b835f00c3a62d0d7aecbb31be463cc30.json)

**Comment by CFenner** [comment]
The API response for the Zigbee devices is empty. So there are no datapoints available to use as of now.

**Comment by egrojyos** [comment]
So, I need to add a Zigbee radio module?

**Comment by Hedda** [comment]
This repository is not meant for support. Please instead post to the Forum (or ask for help on the Discord Chat Server), read:

https://www.home-assistant.io/help/reporting_issues/

and

https://www.home-assistant.io/help/

If want to report what you think is a bug then should post an issue to the Home Assistant core repo for tracking there:

https://github.com/home-assistant/core/issues
