### ISSUE TITLE
The new light devices do not support yet

### ISSUE THREAD

**Issue by baksimha** [home-assistant/home-assistant.github.io#30716]
### Feedback

Hi the new light switches of the company do not yet support home assistant can you look into it please cuz I just install 16 light switches in my home so I have control of the of them only from the app not from the home assistant thank you

### URL

https://www.home-assistant.io/integrations/switcher_kis/

### Version

2024.1.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
