### ISSUE TITLE
Unknown error has occured when I try to login

### ISSUE THREAD

**Issue by AditaNi** [home-assistant/home-assistant.github.io#30729]
### Feedback

When I'm trying to log in to https://server-api.growatt.com/ then i enter my credentials...and then come Unknown error.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by AditaNi** [comment]
Thank you.

Regards
Adrian
