### ISSUE TITLE
Cannot delete unused calendar entities

### ISSUE THREAD

**Issue by philipgo** [home-assistant/home-assistant.github.io#30721]
### Feedback

I created multiple CalDAV calendar entities using configuration.yaml. I would like to delete some of them. I removed them from configuration.yaml and restarted Home Assistant, yet they are still there and receive updates. I cannot delete them through the GUI since the have no unique ID. 

How do I get rid of these unused calendar entities?

### URL

https://www.home-assistant.io/integrations/caldav/

### Version

2024.1.2

**Comment by frenck** [comment]
The CalDAV integration moved to the UI two releases back. Meaning your YAML was imported and removing it; thus has no effect.

Remove your calendars via the integration dashboard in the UI instead.

../Frenck

**Comment by philipgo** [comment]
> Remove your calendars via the integration dashboard in the UI instead.
> 
> ../Frenck

Thank you for your quick response! Unfortunately this does not work for me (or I am doing it wrong). There was no CalDAV or Calendar entry in the UI in the integration dashboard. After your response I manually installed the CalDAV integration through the UI, but still I cannot delete any of the old entries.

Update: After several restarts and waiting for a day, the calendars have disappeared, thank you!
