### ISSUE TITLE
Opentherm gateway integration floor temp reference

### ISSUE THREAD

**Issue by chezlong** [home-assistant/home-assistant.github.io#30725]
### Feedback

Hi, in the opentherm gateway integration documentation page, there is a reference to floor temperature, which rounds temperature values down. 
In the context of home heating, floor temp is generally used to describe an underfloor heating sensor.
A better term for what the integration is doing is "temperature rounding control"

### URL

https://www.home-assistant.io/integrations/opentherm_gw/

### Version

2024.1.2

**Comment by mvn23** [comment]
While I agree that the terminology may be confusing, the solution is probably not a change in the wording.
There has been some discussion in core about removing the feature altogether, after which it will be removed from the docs as well.
