### ISSUE TITLE
Data privacy -  Can I block internet access for this device?

### ISSUE THREAD

**Issue by ch1988** [home-assistant/home-assistant.github.io#30728]
### Feedback

This is a bit funny and in techncal terms wrong in your FAQ. Certainly the roborocks work without internet connection; Valetudo shows, that they can work without [a ...] cloud. 

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2024.1.2

**Comment by Lash-L** [comment]
Yes of course they work without internet if you flash an entirely different firmware on them. However, the firmware on the roborock vacuums as is does not support it from what we can tell. 

I do not plan to add information about valetudo as it 
A) is not simple to flash
B) does not work on all devices
C) will no longer work with this integration or the Roborock app, which is what most people are looking for.
D) not something I do so I am not comfortable trying to guide others through doing it.

there is plenty online about it that users are able to find if they are interested

**Comment by Lash-L** [comment]
@home-assistant close
