### ISSUE TITLE
Move depreciated warning

### ISSUE THREAD

**Issue by dirtycoffee** [home-assistant/home-assistant.github.io#30734]
### Feedback

I would strongly suggest moving the warning at the end of the article to the beginning. I followed along and paid the $5 to find that the Legacy API is deprecated.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.1.2

**Comment by allenporter** [comment]
Sorry to hear that. Why did you think the legacy API would work since it was turned down by Google and doesn't exist anymore?

**Comment by allenporter** [comment]
The integration docs say which API it is using at the top as well as all the features you get with it. I respectfully disagree, and don't plan to do this.

**Comment by frenck** [comment]
The confusion is, is that the docs do not talk about the legacy API.

The last warning does, and there is no context on what it means. I think @dirtycoffee is under the impression all the above is about the legacy api and he now wasted money on getting access to it, but that ain't the case. The content of the docs is about the newer method.

**Comment by allenporter** [comment]
Does removing all mention of it (since it does not exist) clarify things?

**Comment by dirtycoffee** [comment]
I think removing all mention of it would help. I was confused because I followed the article and was not able to connect my account to HA and thought the depreciation was the cause. I had more time today and was able to get it to work using a browser with no extensions installed.
