### ISSUE TITLE
Add A. O. Smith water heater model to supported list

### ISSUE THREAD

**Issue by brandoad** [home-assistant/home-assistant.github.io#30743]
### Feedback

My A. O. Smith water heater, model HPS10-50H45DV, was successfully added using the integration. 

https://www.aosmithatlowes.com/products/water-heaters/electric-water-heaters/hps10-50h45dv/

### URL

https://www.home-assistant.io/integrations/aosmith

### Version

2024.1

### Additional information

![Screenshot 2024-01-09 at 09 38 49](https://github.com/home-assistant/home-assistant.io/assets/13102157/ae639631-64a7-4e43-b99f-ab729a0a921d)

**Comment by bdr99** [comment]
Thanks for letting me know! I'll get it added to the list.
