### ISSUE TITLE
Add RAW decode to use card with service send

### ISSUE THREAD

**Issue by Le-Syl21** [home-assistant/home-assistant.github.io#30741]
### Feedback

Hi you can inspire yourself from: https://github.com/Le-Syl21/rfxcom_get_hex

To dev a RAW discovery integrate on HA

It help to create Button Card using RFXCom:Send with Hex output

### URL

https://www.home-assistant.io/integrations/rfxtrx/

### Version

2024.1.2

### Additional information

Can help new users

**Comment by elupus** [comment]
We dont handle feature requests here. If you code it up yourself, please provide a pull request here. Also rfx does not have any really active maintainer. So unlikely to get new features unless someone steps up.
