### ISSUE TITLE
//workday sensor to include holiday+1

### ISSUE THREAD

**Issue by JDMBIRD83** [home-assistant/home-assistant.github.io#30769]
### Feedback

My local government job gives me the day after Thanksgiving off, instead of Columbus day. I have been able to exclude Columbus day in order to make it a workday, but I would like to be able to add a holiday+1 so that I can remove the day after Thanksgiving as a workday. It could be even better to be able to specify the #, and make it + or -if I were to plan on taking the day before or after a holiday every year.

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
