### ISSUE TITLE
Stopped getting temperature values after core_2023.12.4 update

### ISSUE THREAD

**Issue by 3vdo** [home-assistant/home-assistant.github.io#30768]
### Feedback

For some reason stats-graph stopped getting latest temperature values from all Shelly HT devices after core_2023.12.4 or first core_2024 update. Data is show up to 5.1.2024, but no later data shown in graph even the temperature values are recorded normally from sensor. This issue seem to relate only Shelly HT devices. It worked well before 5.1.2024.
![Screenshot_20240110_223134_Home Assistant](https://github.com/home-assistant/home-assistant.io/assets/116862765/db5d9a67-34a5-4c1c-8d08-45a2ef918408)

### URL

https://www.home-assistant.io/dashboards/statistics-graph/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
