### ISSUE TITLE
Cannot add Integration

### ISSUE THREAD

**Issue by nidd13** [home-assistant/home-assistant.github.io#30760]
### Feedback

Hello,

I've tried various times the explanation of this site: https://www.home-assistant.io/integrations/google_tasks
but always I am getting the following error:

> Access blocked: This app’s request is invalid
> 
> my mail address
> You can’t sign in because this app sent an invalid request. You can try again later, or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
> If you are a developer of this app, see [error details](https://accounts.google.com/).
> Error 400: redirect_uri_mismatch

Error details:

> Error 400: redirect_uri_mismatch
> 
> Sie können sich nicht in dieser App anmelden, weil sie nicht den Google-Richtlinien für OAuth 2.0 entspricht.
> 
> Wenn Sie der App-Entwickler sind, registrieren Sie den Weiterleitungs-URI in der Google Cloud Console.
> Request details: redirect_uri=https://my.home-assistant.io/redirect/oauth
> 

What is the reason?

Best regards

### URL

https://www.home-assistant.io/integrations/google_tasks/

### Version

2024.1.2

**Comment by allenporter** [comment]
On the integration instructions steps under `Generate Client ID and Secret` see step #16 where you need to enter that url `https://my.home-assistant.io/redirect/oauth` as an authorized redirect url. It needs to be that exact url for "My Home Assistant" though sometimes people interpret it to mean their my assistant redirect url.

**Comment by nidd13** [comment]
Hey @allenporter 

It looks like this in my configuration:
![image](https://github.com/home-assistant/home-assistant.io/assets/80405299/b0ced9a7-9b2a-47e1-b4c6-ed693bcb2f75)
or am I totally wrong?

Thank you in advance!

**Comment by nidd13** [comment]
Hi @allenporter 

it looks like this in my configuration:
![image](https://github.com/home-assistant/home-assistant.io/assets/80405299/35d97202-1c6a-41ce-84e3-037c39234dfd)

or am I totally wrong?

Thank you in advance!

**Comment by nidd13** [comment]
Hi @allenporter 

it looks like this in my configuration:
![image](https://github.com/home-assistant/home-assistant.io/assets/80405299/35d97202-1c6a-41ce-84e3-037c39234dfd)

or am I totally wrong?

Thank you in advance!

**Comment by allenporter** [comment]
That screenshot looks correct. Is that the same credential and cloud project id? If any of that changed, you may need to delete from application credentials on the home assistant side. (See documentation for application credentials integration)

**Comment by allenporter** [comment]
(I'm now at a desktop computer) See https://www.home-assistant.io/integrations/application_credentials/

**Comment by nidd13** [comment]
> (I'm now at a desktop computer) See https://www.home-assistant.io/integrations/application_credentials/

That's it! I had some old credential stored in HA, thus it didn't asked me for the new ones.
I deleted the old ones and were able to use the latest ones. Now it is working. Thanks a lot for your help!
