### ISSUE TITLE
Avantree BTDG-40S (CSR8510A10) does not work

### ISSUE THREAD

**Issue by andrezstar2** [home-assistant/home-assistant.github.io#30766]
### Feedback

Hi. 
Dongle Avantree BTDG-40S (CSR8510A10) does not work with HA

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2024.1.2

### Additional information

Avantree BTDG-40S (CSR8510A10) does not work

**Comment by tathamoddie** [comment]
Can you define "does not work"? What's the symptom?

Can you share any logs?
