### ISSUE TITLE
Out of date and confusing.

### ISSUE THREAD

**Issue by jgbreezer** [home-assistant/home-assistant.github.io#30764]
### Feedback

I keep bumping into out of date pages here and elsewhere. There is no "add card" button I've found. Running an HA Core from late 2023. Maybe pages should have a version no. associated with them and default template should either know what version users have (or may have multiple installs of different versions, so the one they're looking at then) by profile/by chosen version and a link back to changelog page and each change should link to something helping you understand how to work with the newer one...

### URL

https://www.home-assistant.io/dashboards/

### Version

2024.1.2

**Comment by tathamoddie** [comment]
Hello 👋

I can't see anything out of date on that page.

When you put your dashboards into edit mode, there is an "Add Card" button shown bottom right, as described in the doco.

Here's a screenshot from my instance, on HA 2024.1.1:

![image](https://github.com/home-assistant/home-assistant.io/assets/45753/9b509a0c-2cee-4089-915e-f984302dc348)

What are you seeing instead?

There is one label which is out of date in the embedded YouTube video -- the video has "Configure UI", when the latest label is "Edit Dashboard".
