### ISSUE TITLE
Athentication not valid

### ISSUE THREAD

**Issue by maxtkirk** [home-assistant/home-assistant.github.io#30776]
### Feedback

Verisure do not accept email login 

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2024.1.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
