### ISSUE TITLE
Says "Path has to match", but what?

### ISSUE THREAD

**Issue by shallowal** [home-assistant/home-assistant.github.io#30777]
### Feedback

I dont understand what path it is trying to match?

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2024.1.2

**Comment by Meyer3** [comment]
> I dont understand what path it is trying to match?

During installation the integration shows a window with the required data that you have to copy to the Ecowitt app (or better the web interface, open the local IP address of the device).
It contains your local HA server address, **delivery path** in HA including token, HA port.

Ecowitt app(s) and web interface handle the path differently. The app always adds a '/' at the beginning. 
So make sure the final path has one but only one '/' at the beginning.
