### ISSUE TITLE
Not clear if the default 'away' timeout is a Unifi or HA thing

### ISSUE THREAD

**Issue by thibaultmol** [home-assistant/home-assistant.github.io#30783]
### Feedback

When you're on the page looking at the Presence Detection section.
it says
>  By default devices are marked as away 300 seconds after they were last seen.

But nothing there says if this is something that's changable through Unifi or HA

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.1.2

**Comment by thibaultmol** [comment]
Apparently it is indeed in the integration itself, but maybe this should be made clear in the documentation
https://community.home-assistant.io/t/setting-the-unifi-network-detection-time/655626/5
i'm not the only person having trouble finding this.

**Comment by tathamoddie** [comment]
This is controlled by the integration, and can be overridden as part of the integration's config flow.

![image](https://github.com/home-assistant/home-assistant.io/assets/45753/09a1a05e-204a-4163-812b-c70608eae160)

Relevant integration source:

https://github.com/home-assistant/core/blob/e71304580df6e945fc0a3e594b6294a4976bd9da/homeassistant/components/unifi/controller.py#L133-L135

https://github.com/home-assistant/core/blob/e71304580df6e945fc0a3e594b6294a4976bd9da/homeassistant/components/unifi/const.py#L44
