### ISSUE TITLE
Unifi Network page doesn't like to explanation on how to create a user

### ISSUE THREAD

**Issue by thibaultmol** [home-assistant/home-assistant.github.io#30781]
### Feedback

If you're on https://www.home-assistant.io/integrations/unifi/
there is no link to for example https://www.home-assistant.io/integrations/unifiprotect#local-user
that explains how to make a local user.
This can be quite confusing with the recent change with 'unifi identity' because now there is a tab for 'admins' and a tab for 'users'.
But in the case of Home Assisant you always want to create an 'admin' even though you don't have to give the actual admin privileges. a 'user' in Unifi is now meant for giving wifi access or door acces for example, not giving access to viewing network/protect data.
https://github.com/home-assistant/home-assistant.io/issues/30626#issuecomment-1887535664

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.1.2

**Comment by AngellusMortis** [comment]
@home-assistant unassign unifiprotect

**Comment by AngellusMortis** [comment]
This issue can be for unifi (if we want to keep it open). UniFi Protect docs being out of date are covered by #30626

**Comment by AngellusMortis** [comment]
It is worth nothing that (at least for the UniFi Protect integration, but I assume @Kane610 has the UniFi integration set up the same way), that **only local accounts are supported**. 

We do not want users to use accounts connected to the cloud that requires a cloud connection for running the integrations. You _absolutely_ should have MFA enabled on any cloud accounts as well.

**Comment by thibaultmol** [comment]
Oh yeah, I'm aware, but there is no reason this local account creation HAS to happen on the local url itself. https://unifi.ui.com/dashboard also allows you to create local only accounts. 
But I was saying this cause it can be confusing with the new 'unifi identity' system they introduced. 

On the unifi cloud dashboard they have two tabs, 'admins' and 'users'.
unifi 'user' are for employees (to give access to VPN, wifi, ev charger, door access)
unifi 'admin' accounts are for anything to do with actually managing or viewing Unifi Network/protect/talk etc management stuff.
And it's only those last accounts that you want for the HA integrations. But this isn't clear in the documentation.
