### ISSUE TITLE
islamic date with month and year

### ISSUE THREAD

**Issue by smkhurram487** [home-assistant/home-assistant.github.io#30794]
### Feedback

please add islamic date with month and year

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2024.1.2

**Comment by engrbm87** [comment]
Thanks for your request. Unfortunately, this is the not the correct repository for feature requests. I will look into adding this in a future version of HA.

**Comment by engrbm87** [comment]
@home-assistant close
