### ISSUE TITLE
Prosegur alarmas - German translation weird 

### ISSUE THREAD

**Issue by hartmood** [home-assistant/home-assistant.github.io#30808]
### Feedback

I'm probably one of the few who is using the German translation of this plug-in. The two switch options are kind of strange. 

Connect Partially alarm is translated to "Zuhause" and and Connect  to abwesend. 

I suggest that Zuhause should be renamed to Partiell and Abwesens to Voll. 

![IMG_0141](https://github.com/home-assistant/home-assistant.io/assets/50808701/295ef554-0145-418c-bcd1-00284083a016)

### URL

https://www.home-assistant.io/integrations/prosegur/

### Version

2024.1.3

**Comment by dgomes** [comment]
Well this is not specific to Prosegur, it affects all Alarms ... 

I suggest you contribute to the project: https://developers.home-assistant.io/docs/translations/

As I do not speak German and can't therefore provide a "fix"
