### ISSUE TITLE
We have Problems with the Wifi Controller BRP069C4x and BRP069A78. 

### ISSUE THREAD

**Issue by shc-privat** [home-assistant/home-assistant.github.io#30805]
### Feedback

We get no connection. 

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2024.1.2

### Additional information

The first one is the integrated Wifi Controller of the FTXJ-XXX Devices and the second one ist the Watertank EKHWET120BAV3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
