### ISSUE TITLE
slow updating or not at all

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/home-assistant.github.io#30813]
### Feedback

I'm not sure if this is slow updating or not updating at all.  It seems like I have to reload the integration to get it to update.  How long should it be between updates?  I'm assuming you are polling the cloud for the updates.

### URL

https://www.home-assistant.io/integrations/oncue/

### Version

2024.1.3

**Comment by PeteRager** [comment]
Updates every 10 minutes

**Comment by turboc1208** [comment]
Is that set in the integration and can it be configured?  I’ve noticed the Kohler app is slow too. Is it a feature of the generator and onque system?

**Comment by PeteRager** [comment]
It is not configurable.

**Comment by PeteRager** [comment]
@home-assistant close
