### ISSUE TITLE
Dashboard Hyperlink 

### ISSUE THREAD

**Issue by fabian-venegas17** [home-assistant/home-assistant.github.io#30819]
### Feedback

The Dashboard hyperlink is not working when you press on it. If you right click and press open in a new tab it works. I am using chrome. 

### URL

https://www.home-assistant.io/getting-started/concepts-terminology/

### Version

2024.1.3

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @fabian-venegas17 :+1:
