### ISSUE TITLE
Core installation failed

### ISSUE THREAD

**Issue by imatech** [home-assistant/home-assistant.github.io#30817]
### Feedback

homeassistant@has:/home/smacktalk$ pip3 install homeassistant==2024.1.3
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement homeassistant==2024.1.3 (from versions: 0.7.0rc1, 0.7.0, 0.7.0.1, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.18.2, 0.19, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.21.2, 0.22.0, 0.22.1, 0.23.0, 0.23.1, 0.24.0, 0.24.1, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.27.0, 0.27.1, 0.27.2, 0.28.0, 0.28.1, 0.28.2, 0.29.0, 0.29.1, 0.29.2, 0.29.3, 0.29.4, 0.29.5, 0.29.6, 0.29.7, 0.30.0, 
<truncated>
ERROR: No matching distribution found for homeassistant==2024.1.3

### URL

https://www.home-assistant.io/installation/linux/

### Version

2024.1.3

### Additional information

installed on ubuntu 22.04.3//Core I5 processor

**Comment by frenck** [comment]
It seems like you missed the pre-requisite about the required Python version that is listed in that same documentation?

Make sure you have Python 3.11 or newer. Considering the versions is offers, I almost feel like you are using Python 2 to try to install Home Assistant?

Anyways, please use Python 3.11 (or even better, go straight to Python 3.12) and the installation will succeed on this point.

../Frenck

**Comment by imatech** [comment]
I upgraded to python 3.12 and same issue. 
ERROR: No matching distribution found for homeassistant==2024.1.3
homeassistant@has:/home/smacktalk$ python3.12 --version
Python 3.12.0
homeassistant@has:/home/smacktalk$ pip3.12 --version
pip 23.2.1 from /usr/local/lib/python3.12/site-packages/pip (python 3.12)
homeassistant@has:/home/smacktalk$

**Comment by frenck** [comment]
Please paste the exact error logs whe using Python 3.12

**Comment by imatech** [comment]
Thanks, I'm going to use the container version.
