### ISSUE TITLE
Making the "Docker means limitations" more proeminent on the installation page

### ISSUE THREAD

**Issue by vdeconinck** [home-assistant/home-assistant.github.io#30814]
### Feedback

Hi,
My first experience with HA was disappointing because I hadn't read the installation page in detail (My mistake, I know ;-)).
Being in the IT, I went straight to the container way, and immediately after setup, I wanted to install ESPHome and struggled quite a bit before discovering ESPHome was an AddOn, and AddOns were not supported on Docker (I reinstalled HAOS since and all is good).

To avoid that pitfall, my suggestion would be:
**In the "expert" section, move the comparison table (which currently sits at the bottom of the page) just after the 3 methods (Container/Supervised/Core) and the Note. Then only show the "Linux/MacOS/Windows/etc" details.**

Additionally, I would also reword the note as follows :
_Important: unless you are experienced with Home Assistant and have a very specific reason to choose one of the above, we do not recommend to use these installation methods because the installed version may show major limitations. For example, Add-ons and other important Home Assistant features may not be available, as indicated below._

(btw, the last word of the current note is "_here_" but it doesn't seem to refer or link to anything.)

Keep on the good work.
Vincent

### URL

https://www.home-assistant.io/installation/

### Version

2024.1.3

**Comment by c0ffeeca7** [comment]
Thank you for the hint, @vdeconinck :pray:

**Comment by vdeconinck** [comment]
Wow, kudos for the impressive response time! :-)

My suggestion was to move the comparison table just before the Linux/Mac/Win details.

Moving it to the very top of the page obviously makes it the most visible, but the Easiest/Easy/Intermediate/Hard paragraphs that follow don't explicitely indicate that they use the "HAOS method". 
Don't you fear that new users will be puzzled, as the method comparison comes first but is not related to those 4 paragraphs ? Just swapping the comparison and the Linux/Mac/Win could help the Experts without disturbing the "Easy route".

Just my 2 cents,
Vincent
