### ISSUE TITLE
Growatt Server for Europe not available

### ISSUE THREAD

**Issue by Bodyworksgi** [home-assistant/home-assistant.github.io#30815]
### Feedback

Hi folks,
i would like to get access to my SPH and MOD converter via Homeassistant, but the server with the url server.growatt.com is missing. Are you willing to add it?
Best regards,
Franky

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
