### ISSUE TITLE
possibility to turn off heating

### ISSUE THREAD

**Issue by Vekolb** [home-assistant/home-assistant.github.io#30830]
### Feedback

Is there a way to turn off the heating on demand? This is to be used for load balancing, right now I am turning the whole device off, but this means it also has to boot back up once turned on again.

### URL

https://www.home-assistant.io/integrations/osoenergy/

### Version

2024.1.3

**Comment by WebSpider** [comment]
Looking at the integration, this integration has the ability to set the target temperature. Maybe this is a solution to your issue?

**Comment by osohotwateriot** [comment]
Hello,

You can currently use the water heater services for turn on and turn off to control the heating of the water heater.
Turn off will prevent the heater from heating the water until the minimum temperature is reached. After that happens the heater will start heating the water again, according to the current target temperature.
You can also set the temperature of the heater as @WebSpider has mentioned to as low as 10 degrees to prevent the heating, but the water heaters have a minimum of hotwater to be available at all times which is similar to the minimum temperature and will start heating if that limit is reached.

Controlling that limit will be added as a feature in the future of this integration as it will be a custom service.
Hope that answers your question.
