### ISSUE TITLE
esphome/your-device-name-wake-word.yaml doesn't exist

### ISSUE THREAD

**Issue by foltz61** [home-assistant/home-assistant.github.io#30839]
### Feedback

The file esphome/your-device-name-wake-word.yaml doesn't exist.

### URL

https://www.home-assistant.io/voice_control/troubleshooting/

### Version

2024.1.3

**Comment by klaasnicolaas** [comment]
This does not literally mean the file, but your own esphome device with a `voice_assistant` section in the yaml config.

./Klaas

**Comment by foltz61** [comment]
I know. There's no such XXXX--wake-word.yaml file.

![Screenshot_20240114-211554](https://github.com/home-assistant/home-assistant.io/assets/1285465/ed67ef53-71cb-43ba-9dfd-1ad9c0fa0b83)

**Comment by klaasnicolaas** [comment]
So it's your M5Stack Atom Echo 😉

**Comment by foltz61** [comment]
![Screenshot_20240114-225808](https://github.com/home-assistant/home-assistant.io/assets/1285465/6ed79da5-741f-45d1-abdc-df57f9334879)
I assumed the yaml file name would include "-wake-word". Also, there is no "voice_assistant" section in that yaml file.
