### ISSUE TITLE
The yandex_tranport sensor does not work.

### ISSUE THREAD

**Issue by mrartifact** [home-assistant/home-assistant.github.io#30848]
### Feedback

Hello.

After adding data to configuration.yaml, the sensor does not appear in the system.

`sensor:
  - platform: yandex_transport
    name: Bus_to_subway
    stop_id: stop_10061283
    routes:
        -10`

### URL

https://www.home-assistant.io/integrations/yandex_transport/

### Version

2024.1.3

**Comment by devbis** [comment]
@mrartifact Please, check your logs. If there is a captcha error ('NoneType' object has no attribute 'group') you should either wait for some time (yandex API is unstable and blocks clients) or just avoid using this sensor.
