### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by jbrauner85** [home-assistant/home-assistant.github.io#30858]
### Feedback

Does this still work?  I can't seem to get it working.  I'm pretty new at yaml.... but would like to see if this works or not.  Any help would be appreciated.

### URL

https://www.home-assistant.io/integrations/thermoworks_smoke/

### Version

2024.1.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
