### ISSUE TITLE
Nice integration, could be a bit better !!!

### ISSUE THREAD

**Issue by bentouspam** [home-assistant/home-assistant.github.io#30852]
### Feedback

Nothing bat about this integration, but the default page would be better with less entries... 
just 10 ou 20 entries with the user(s) selected entries.
220 different langages is a nice thing, but maybe not every day in the default browsing interface. or in an "other" thumbnail.
may-be a user default stations lists selected in the main panel, by selecting entries in an easy way ? everybody is not a vs-code master or even cannot handle properly a simple copy/paste for an URI.

Best regards,
Benoit.

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2024.1.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
