### ISSUE TITLE
Small typo in cursive part about knowing more

### ISSUE THREAD

**Issue by mhoogenbosch** [home-assistant/home-assistant.github.io#30864]
### Feedback

The current sentence:

_Want to **now** more about how this all works? Check out the [openWakeWord](https://github.com/dscripka/openWakeWord) project by David Scripka.)_

Should be 'know'

### URL

https://www.home-assistant.io/voice_control/create_wake_word/

### Version

2024.1.3

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @mhoogenbosch :+1:
