### ISSUE TITLE
blink camera_snapshot

### ISSUE THREAD

**Issue by pedwin-sparc** [home-assistant/home-assistant.github.io#30861]
### Feedback

when i use the service camera_snapshot provided in the link https://www.home-assistant.io/integrations/blink/#snap-picture-and-save-locally, I am getting an error. 
![image](https://github.com/home-assistant/home-assistant.io/assets/69444139/a09cc5af-6a32-4ea6-831f-3872d4d79664)
![image](https://github.com/home-assistant/home-assistant.io/assets/69444139/627c7be7-d618-4f24-b93e-36c489ac6342)

### URL

https://www.home-assistant.io/integrations/blink/

### Version

2024.1.3

**Comment by mkmer** [comment]
Use the example:
https://www.home-assistant.io/integrations/blink/#snap-picture-and-save-locally

**Comment by mkmer** [comment]
@home-assistant close

**Comment by mkmer** [comment]
@home-assistant close
