### ISSUE TITLE
Holidays Missing

### ISSUE THREAD

**Issue by guarddog13** [home-assistant/home-assistant.github.io#30879]
### Feedback

Several Holidays are missing. Valentine's Day (02/14), St. Patrick's Day (03/17), Halloween (10/31) and Election Day (First Tues every 4 years ((this year is 11/05)) ). Could you please add these to the US Holiday Calendar? 

### URL

https://www.home-assistant.io/integrations/holiday/

### Version

2024.1.3

**Comment by jrieger** [comment]
Home Assistant does not provide holiday data by itself; instead, it relies on the [python-holidays](https://github.com/vacanza/python-holidays) library. If you think that library is missing holidays, please open an issue at the python-holidays repository.

**Comment by jrieger** [comment]
@home-assistant close
