### ISSUE TITLE
Open an issue with the author of the integration ...

### ISSUE THREAD

**Issue by theBig-E** [home-assistant/home-assistant.github.io#30871]
### Feedback

Regarding the instruction to, "Open an issue with the author of the integration..."
...but there is no author listed for the integration.   A spot check of several of the integrations shows no indication of author.  

### URL

https://www.home-assistant.io/more-info/statistics/

### Version

2024.1.3

### Additional information

This is regarding the Whirlpool 6th Sense integration. 

While the controls are find, none of the sensors are registered for long term collection.

**Comment by klaasnicolaas** [comment]
There are 2 maintainers for that integration 

https://github.com/home-assistant/core/blob/dev/homeassistant%2Fcomponents%2Fwhirlpool%2Fmanifest.json#L4

**Comment by theBig-E** [comment]
Thanks.
