### ISSUE TITLE
Last update time

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/home-assistant.github.io#30874]
### Feedback

Please expose the last date time the kohler web site was checked.  At least that way I know about how long I'm going to have to wait for the system to show the correct status.

### URL

https://www.home-assistant.io/integrations/oncue/

### Version

2024.1.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by PeteRager** [comment]
You can do this in a template, as this value updates everytime a poll is done. 

`
{{ states.sensor.trudigen_generator_controller_total_operation_time.last_updated }}
`

You can also force an update, this will update all the parameters.  It's not recommended to do this continuously as Kohler may lock your account.  I use this to poll at a 1 minute rate when there is a power failure, to get more detailed engine data while it is running. 

```
    - service: homeassistant.update_entity
      data: {}
      target:
        entity_id: sensor.trudigen_generator_state
```

**Comment by turboc1208** [comment]
It didn’t seem to work.  I’m trying to setup a helper template sensor as date& time.  I tried each of the items below with the shown result.

{{ states.sensor.genny_generator_controller_total_operation_time.last_updated }} -- unknown
{{ states(sensor.genny_generator_controller_total_operation_time.last_updated) }} – unavailable
{{ states("sensor.genny_generator_controller_total_operation_time.last_updated") }} – unknown

It’s probably something I’m doing wrong.  I’m fairly new to templates.

From: PeteRager ***@***.***>
Date: Tuesday, January 16, 2024 at 4:07 PM
To: home-assistant/home-assistant.io ***@***.***>
Cc: turboc1208 ***@***.***>, Author ***@***.***>
Subject: Re: [home-assistant/home-assistant.io] Last update time (Issue #30874)

You can do this.

{{ states.sensor.trudigen_generator_controller_total_operation_time.last_updated }}
