### ISSUE TITLE
Lamba Function Testing

### ISSUE THREAD

**Issue by andrewbpark** [home-assistant/home-assistant.github.io#30880]
### Feedback

I tried to test the lambda function but I'm getting: the following in the AWS console.
The area below shows the last 4 KB of the execution log.
```
{
  "event": {
    "payload": {
      "type": "INTERNAL_ERROR",
      "message": "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    }
  }
}
```
is there anything I can do to debug this issue?

### URL

https://www.home-assistant.io/integrations/alexa.smart_home/

### Version

2024.1.3

**Comment by jbouwh** [comment]
Note that this is not the place to ask for support.

You can turn on debug logging:

https://www.home-assistant.io/integrations/logger/
