### ISSUE TITLE
Set up multiple devices

### ISSUE THREAD

**Issue by ac-speedy** [home-assistant/home-assistant.github.io#30897]
### Feedback

Hello
I have 3 Velux KLF 200 gateways and would like to set them all up. Unfortunately, setup is only possible from one device. When can I set up several devices?

### URL

https://www.home-assistant.io/integrations/velux/

### Version

2024.1.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
