### ISSUE TITLE
Default value "None" may not be set

### ISSUE THREAD

**Issue by Dirk68** [home-assistant/home-assistant.github.io#30899]
### Feedback

This documentation states: "None: Generic number. This is the default and doesn’t need to be set."
but the interpreter even reports an error when setting "Device_class: None" on mqtt number entities.

`Validation error: Invalid config for 'number' at configuration.yaml, line 217: expected NumberDeviceClass or one of 'apparent_power', 'aqi', 'atmospheric_pressure', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'data_rate', 'data_size', 'distance', 'duration', 'energy', 'energy_storage', 'frequency', 'gas', 'humidity', 'illuminance', 'irradiance', 'moisture', 'monetary', 'nitrogen_dioxide', 'nitrogen_monoxide', 'nitrous_oxide', 'ozone', 'ph', 'pm1', 'pm10', 'pm25', 'power_factor', 'power', 'precipitation', 'precipitation_intensity', 'pressure', 'reactive_power', 'signal_strength', 'sound_pressure', 'speed', 'sulphur_dioxide', 'temperature', 'volatile_organic_compounds', 'volatile_organic_compounds_parts', 'voltage', 'volume', 'volume_storage', 'water', 'weight', 'wind_speed' for dictionary value 'device_class', got 'None', please check the docs at https://www.home-assistant.io/integrations/mqtt`

The proposal is to replace "This is the default and doesn’t need to be set." by "This is the default and may to be set."

### URL

https://www.home-assistant.io/integrations/number/

### Version

2024.1.3

**Comment by jbouwh** [comment]
The string `None` is not a valid device class. In YAML and json `null` should be used.

**Comment by jbouwh** [comment]
I suggest we remove the defaults for the options that now have a `None` default. The same applies to `state_class`, `entity_category`, and `unit_of_measurement`.
If `null` is accepted, this should be mentioned in the description.
