### ISSUE TITLE
Speed display option for KM and MPH

### ISSUE THREAD

**Issue by itolson** [home-assistant/home-assistant.github.io#30905]
### Feedback

Hi, can the speed limits and odometer have an option to display in mph as well as kmh ?

### URL

https://www.home-assistant.io/integrations/tessie/

### Version

2024.1.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by Bre77** [comment]
Frenck is right, but to answer your question you can change the **unit of measurement** for any sensor entity in Home Assistant, which includes km to miles and kmph to mph.
