### ISSUE TITLE
add other login servers

### ISSUE THREAD

**Issue by Leecher89** [home-assistant/home-assistant.github.io#30906]
### Feedback

Hi wanted to ask if you can change the login pages. I cannot log in to the site. I can only log in here https://server.growatt.com thanks in advance.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
