### ISSUE TITLE
Push notification when armed and detecting moviment

### ISSUE THREAD

**Issue by machadojon** [home-assistant/home-assistant.github.io#30916]
### Feedback

Hi team,
Great work with the Blink integration, I would like to know if the system is armed, and a moviment is detected, there is a way to push a notification to HA and to Homekit if we do the Bridget?

Regards,

Jonathan Machado

### URL

https://www.home-assistant.io/integrations/blink/

### Version

2024.1.3

### Additional information

No

**Comment by mkmer** [comment]
Details I have discovered are detailed here:
https://github.com/fronzbot/blinkpy/discussions/770

Need help getting the FCM stuff to work.
