### ISSUE TITLE
Does it support the Temp & Humidity sensor Thread version yet? (CGG1T)

### ISSUE THREAD

**Issue by edmondss** [home-assistant/home-assistant.github.io#30911]
### Feedback

It said no devices were found. Thanks.

### URL

https://www.home-assistant.io/integrations/qingping/

### Version

2024.1.3

**Comment by c0ffeeca7** [comment]
Could you provide a bit more context?

- If it is a HomeKit device,  did you follow the procedure to [onboard the HomeKit device via Thread](https://www.home-assistant.io/integrations/homekit_controller/)?

**Comment by edmondss** [comment]
> Could you provide a bit more context?
> 
> * If it is a HomeKit device,  did you follow the procedure to [onboard the HomeKit device via Thread](https://www.home-assistant.io/integrations/homekit_controller/)?

I am using the new Qingping Temp & Humidity Sensor Thread version (CGG1T) but I cannot be found using the 'Qingping' Integration and that's why I asked. 

I will try your onboard homekit device via Thread procedure then. 

Thanks.

**Comment by edmondss** [comment]
I have followed the above procedure but the Thread sensor only connect via bluetooth but not Thread. Any idea why this happen? Thanks.
![Screenshot 2024-01-24 181836](https://github.com/home-assistant/home-assistant.io/assets/157027452/6f465fdc-2949-44e0-a3b0-d46cac950cb4)

**Comment by c0ffeeca7** [comment]
I think this is beyond the scope of this issue tracker. This issue tracker is used for tracking documentation issues.

Feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) and find the Thread channel.
