### ISSUE TITLE
Please note that the username is case-sensitive

### ISSUE THREAD

**Issue by DaveDurant** [home-assistant/home-assistant.github.io#30922]
### Feedback

No error is returned if you use the wrong case when you specify the username - it just spins. 

Fixing it to provide an error would be great but just mentioning it in the doc would prevent people from getting stuck there. 

### URL

https://www.home-assistant.io/integrations/octoprint/

### Version

2024.1.3

**Comment by ming879** [comment]
> ### 反馈
> 没有错误的返回，如果你使用了错误的情况下，当指定用户名-这只是旋转。
> 
> 固定它提供一种错误将是巨大的，但只是提及它在医生会防止人们陷入那里。
> 
> ### URL
> https://www.home-assistant.io/integrations/octoprint/
> 
> ### 版本
> 2024.1.3
>###URL
>https://your.home-assisstant.url
>Your-long-access-token
>light.happy_lights
>%state
>%attributes
The time is {{states(''sensor.time'')}}
 >%hatime

>%

**Comment by DaveDurant** [comment]
👍
