### ISSUE TITLE
Initial connect on port 80 required

### ISSUE THREAD

**Issue by pefmeister** [home-assistant/home-assistant.github.io#30928]
### Feedback

At least for the setup this plugin makes a connection to port to get details about the device. If this is not possible due to a firewall between HA and the device, setup fails with a hint to wrong credentials, which is misleading. Maybe a hint in the setup document would be helpful.

### URL

https://www.home-assistant.io/integrations/fritzbox_callmonitor/

### Version

2024.1.3

**Comment by cdce8p** [comment]
Yeah that is correct. The initial request during the config flow is used to get the serial number. This was changed in https://github.com/home-assistant/core/pull/87089. Previously the broad `FRITZ!Box Settings` permission was required for that.

Feel free to open a PR and update the documentation.

Some more background:
- https://github.com/home-assistant/home-assistant.io/pull/26048
- https://github.com/kbr/fritzconnection/pull/168
