### ISSUE TITLE
Minor typo correction

### ISSUE THREAD

**Issue by PenKlad** [home-assistant/home-assistant.github.io#30929]
### Feedback

```<> mean an expansion rule. The view these rules, search for expansion_rules in the [_common.yaml](https://github.com/home-assistant/intents/blob/main/sentences/en/_common.yaml) file.```

"The view these rules, search..." should be "To view these rules, search..."

### URL

https://www.home-assistant.io/voice_control/builtin_sentences/

### Version

2024.1.3

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @PenKlad :+1: 

Not sure if you've seen it. But at the bottom of the page, there is an edit button. 
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/42a26e76-5081-4780-9bc0-5c1e13020ab0)

When you select it, it lets you edit the page.

**Comment by PenKlad** [comment]
Good info. I hadn't seen it.
________________________________
