### ISSUE TITLE
Ansteuerung der reduzierten Heizungstemperatur

### ISSUE THREAD

**Issue by JuergenBahrdt** [home-assistant/home-assistant.github.io#30938]
### Feedback

Hallo,
ich suche eine Möglichkeit die Einstellung der reduzierten Heizungstemperatur über HA zu verändern

Gruß
JUBD

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2024.1.3

**Comment by CFenner** [comment]
Moin @JuergenBahrdt, 

Du solltest du Temperatur bereits über das Climate entity verändern können, wenn das betreffende Programm aktiv ist. Mittlerweile gibt es aber bereits number entities für die Programme `reduced` und `heatingReduced`.

**Comment by CFenner** [comment]
Implemented with https://github.com/home-assistant/core/pull/109315

**Comment by CFenner** [comment]
@home-assistant close
