### ISSUE TITLE
Affichage de la température actuelle

### ISSUE THREAD

**Issue by kentin62** [home-assistant/home-assistant.github.io#30934]
### Feedback

Bonjour,

Je n'arrives pas à faire afficher la température actuelle 👍 
show_current_as_primary

show_current_as_primary boolean ( facultatif , par défaut : false )
Afficher la température actuelle comme information principale au lieu de la température cible. La température cible sera affichée comme information secondaire.

pouvez vous donner un exemple de configuration YAML ?

Merci :)

### URL

https://www.home-assistant.io/dashboards/thermostat/

### Version

2024.1.3

### Additional information

Bonjour,

Je n'arrives pas à faire afficher la température actuelle 👍 
show_current_as_primary

show_current_as_primary boolean ( facultatif , par défaut : false )
Afficher la température actuelle comme information principale au lieu de la température cible. La température cible sera affichée comme information secondaire.

pouvez vous donner un exemple de configuration YAML ?

Merci :)

**Comment by frenck** [comment]
Hi there @kentin62 👋 

Unfortunately, we don't speak that language. Home Assistant is an English-only speaking community.

Going to close this documentation feedback for now. Feel free to open a new one using the English language.

Thanks 👍 

../Frenck
