### ISSUE TITLE
Current temperature display

### ISSUE THREAD

**Issue by kentin62** [home-assistant/home-assistant.github.io#30935]
### Feedback

Good morning,

I can't get the current temperature to display 👍
show_current_as_primary

show_current_as_primary boolean (optional, default: false)
Show current temperature as main information instead of target temperature. The target temperature will be displayed as secondary information.

can you give an example of YAML configuration?

THANKS :)

### URL

https://www.home-assistant.io/dashboards/thermostat/

### Version

2024.1.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
