### ISSUE TITLE
missing description for port speed

### ISSUE THREAD

**Issue by Santanachia** [home-assistant/home-assistant.github.io#30936]
### Feedback

Like many others, I struggled with getting RaspBee II up and running. It turned out that there is an misleading entry in the documentation.
`port speed (not applicable for all radios)`.
It turns out that this is a crucial setting. The value displayed there by default makes you get a connection error, and all you have to do is change it to `38400`.

### URL

https://www.home-assistant.io/integrations/zha

**Comment by Hedda** [comment]
Suggest that you submit this should instead just be baudrate feature request issue to zigpy-deconz -> https://github.com/zigpy/zigpy-deconz/issues/249

There are loads of different Zigbee Coordinator adapters on the market now and users do not need to enter port speed for all as the probe already does test 57600 and 115200 baudrates so wondering if it would help to extend the ZHA documentation on this?

If so how? -> https://www.home-assistant.io/integrations/zha#configuration---gui
