### ISSUE TITLE
Add Timezone example to **compose.yml** example 

### ISSUE THREAD

**Issue by simon-lewis** [home-assistant/home-assistant.github.io#30944]
### Feedback

Add Timezone example to **compose.yml** example on this page. 
Worth including the `- TZ=MY_TIME_ZONE` as an example `environment:` line is the compose file.

### URL

https://www.home-assistant.io/installation/linux/

### Version

2024.1.4

### Additional information

.

**Comment by frenck** [comment]
This ain't needed?

Home Assistant handles time zones itself.

**Comment by simon-lewis** [comment]
Good news. Probably worth removing it from the docker run instructions then. Closing this one
