### ISSUE TITLE
"Take Control" step on dashboard onboarding page doesn't specify where to take control

### ISSUE THREAD

**Issue by Jtav1** [home-assistant/home-assistant.github.io#30942]
### Feedback

The text "You may be asked to Take control of your dashboard. Read and accept this before continuing" is unclear.

Prior to being able to edit the dashboard and continue following along with the steps listed on the page, the user needs to click the three dot button in the top right corner of the page to edit the dashboard. Then click the three dot button in the top right corner of the "edit dashboard" popup message in order to access the "Take Control" option. The text should clarify this process; currently, that part of the instructions references the three dot menu on the device itself, not the dashboard.

This needs to be done before the user can continue with step 4 and add a card to the dashboard, otherwise they receive an error message stating they have no lovelace views and one must be created. 

### URL

https://www.home-assistant.io/getting-started/onboarding_dashboard/

### Version

2024.1.4

### Additional information

Related to https://github.com/home-assistant/home-assistant.io/issues/29690

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @Jtav1 :+1:
