### ISSUE TITLE
SIA provides integration with several alarm systems 

### ISSUE THREAD

**Issue by jnathalia** [home-assistant/home-assistant.github.io#30947]
### Feedback

The documentation says the SIA Alarm Systems integration provides integration with several alarm systems. This is a broad description ("several"), while in practice the Ajax system is supported and in some articles I can read about ATS Advanced.

However, the Aritech ATS Classic is not being supported, while it supports the standard SIA and XSIA as well. Although the ATS Classic alarm panel has been set correctly (as well to an external PAC), the add-on is not parsing any signal. Even not the heartbeat. This might be a slight difference in text that's being put through the port, but bottomline it's not working. While the external control room is able to parse the codes being sent.

### URL

https://www.home-assistant.io/integrations/sia/

### Version

2024.1.4

**Comment by eavanvalkenburg** [comment]
Hi @jnathalia could you share logs from some of this, as with any standardized protocol there are slight differences between implementations and since I only have one I can't do much without people sharing so the more you can the better!

**Comment by jnathalia** [comment]
Great @eavanvalkenburg to spend some effort into this! I really want to receive SIA messages as this is the only way to get my alarm hooked into HA...

I have been playing around with the add-on while debug logging was on. I have attached the log... (please tell me if this is what you are looking for... if there is another way to receive everything being sent to this port, I'm happy to catch the SIA messages)

I want to make a note about my ATS alarm system. I can choose for 4 options how it should communicate to a PAC:

1. SIA Small
2. SIA Large
3. XSIA Small
4. XSIA Large

As this isn't mentioned at the integration, there must be some distinction. I actually think it's just truncating some description of zones and areas.

Of course, I have tried them all but it is something to consider...

[home-assistant_sia_2024-01-20T10-59-20.503Z.log](https://github.com/home-assistant/home-assistant.io/files/13997766/home-assistant_sia_2024-01-20T10-59-20.503Z.log)

Thanks in advance.

PS I have enabled the heartbeat at my ATS-IP-KIT and I have also made the changes to my alarm system so messages should be pushed to the assigned IP address and appropriate port (I know quite some things about this alarm system)
