### ISSUE TITLE
Conflicting description of the `restore` option

### ISSUE THREAD

**Issue by maxosprojects** [home-assistant/home-assistant.github.io#30958]
### Feedback

The note on the page states:

> Timers will be restored to their correct state and time on Home Assistant startup and restarts when configured with the `restore` option.
> However, automations using the `timer.finished` event **will not trigger** if the timer expires when Home Assistant is not running.

However, docs on both the `restore` option and the `timer.finished` event state the opposite.

On the `restore` option:
> When true, active and paused timers will be restored to the correct state and time on Home Assistant startup and restarts. If an active timer was supposed to end while Home Assistant is stopped, the timer.finished event will fire on startup for that timer.

On the `timer.finished` event:
> but if the restore property is true, finished_at may be further in the past since this event will fire on startup for any timers that would have ended while Home Assistant was stopped.

This sounds like at least one of the above statements is wrong.
There is also a slight possibility of me reading it wrong.

### URL

https://www.home-assistant.io/integrations/timer/

### Version

2024.1.5

**Comment by brainhig** [comment]
I concur. Oddly, I was just reading this page and am also confused. One of the statements you highlighted has to be incorrect. According to Smart Home Junkie, as of the last time he created a post regarding timers, timers were still broken with regards to surviving restarts of Home Assistant. 

I just tested this to be sure, and the more unfortunate of the two statements is still true. Timers do not survive restarts. At least, in my test, an automation that is triggered by a timer.finished event will not be triggered on startup if the timer expired while Home Assistant was down. I suppose that it's possible the timer.finished event is fired before the automation listener is started, but that wouldn't make much sense as far as order of execution, IMHO. 

The upshot of the timer.finished event not triggering an automation on startup is that it obviates the use of the finished_at property in an automation to check if the timer finished within the last few minutes for example. Unless I'm missing something!
