### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by elrobertocarlos** [home-assistant/home-assistant.github.io#30963]
### Feedback

How about providing an username and password to login before issuing the command.

### URL

https://www.home-assistant.io/integrations/telnet/

### Version

2024.1.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
