### ISSUE TITLE
Ort nicht auf der Auswahlliste

### ISSUE THREAD

**Issue by joachimwussow** [home-assistant/home-assistant.github.io#30967]
### Feedback

Gibt es eine Möglichkeit weitere Orte dem Auswahlmenue hinzuzufügen? Kann ich es selbst? Ich würde gerne Sylt oder Westerland abrufen. 

### URL

https://www.home-assistant.io/integrations/nina/

### Version

2024.1.5

**Comment by DeerMaximum** [comment]
No, you cannot add any new locations, as all German municipalities for which warnings exist are already included.
However, Sylt also appears in the selection menu, under R-U, simply select it and you should see warnings for Sylt.
