### ISSUE TITLE
fail to conect

### ISSUE THREAD

**Issue by PauloPC** [home-assistant/home-assistant.github.io#30972]
### Feedback

Hi.
No matter which IP I use (HA or AC) I receive the connection failure message

![Capture](https://github.com/home-assistant/home-assistant.io/assets/18357509/0c876e17-29d1-4f68-b592-b9e11d8a65e1)

### URL

https://www.home-assistant.io/integrations/ccm15/

### Version

2024.1.5

**Comment by ocalvo** [comment]
Can you open the ip in a browser? What do you see?

**Comment by PauloPC** [comment]
Hi Oscar,

If I try to open the IP  for de AC it is denied to access  the site.

*Paulo César*
Celular/ WhatsApp
*11  95 702 4707  *




Em dom., 21 de jan. de 2024 às 15:42, Oscar Calvo ***@***.***>
escreveu:

**Comment by ocalvo** [comment]
The integration won't work if you cannot open with ip the browser. Please ensure that the ip address corresponds to the ccm15 data converter module and your browser and the data converter are in the same LAN.

What ip is your home assistant instance? What ip is the data converter?

**Comment by PauloPC** [comment]
"What ip is your home assistant instance? What ip is the data converter?"

My Ip for HA works  well!

"the ccm15 data converter module"  What is this?
Everything is in the same  LAN.


*Paulo César*
Celular/ WhatsApp
*11  95 702 4707  *




Em dom., 21 de jan. de 2024 às 16:21, Oscar Calvo ***@***.***>
escreveu:

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
