### ISSUE TITLE
Feature Protect: Hayward Omnipool Freeze Protect

### ISSUE THREAD

**Issue by soupman98** [home-assistant/home-assistant.github.io#30988]
### Feedback

I'd like to propose the following FREEZE PROTECT features for OmniPool controllers

1. Display status of freeze protected equipment (all)
2. Display freeze protect status of pump equipment (Body of Water)
3. Display freeze protect status of other equipment (water features)
4. Display freeze protect setting/level of any freeze-protected items (e.g. 34 degrees). There could be multiple settings. At least 3 I think)

Happy to do any testing on SmarThings, HomeAssistant, Hubitat, ActionTiles.

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2024.1.5

**Comment by djtimca** [comment]
@soupman98 I don't believe there is anything available in the Hayward APIs specific to freeze protection. You may need to use other sensors to do something similar.

**Comment by soupman98** [comment]
Is there somewhere I can go read and look on this? Just getting into H/A and missing hayward automation a guy had done for S/Things. He's moved over to Hubitat. It's displayed on the display panel, I'd be surprised if it's not surfaced somewhere some how.

**Comment by djtimca** [comment]
The Omnilogic API documentation is under NDA with Hayward unfortunately so it can't be shared here.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by soupman98** [comment]
Thanks. My bad. Lessons learned!
