### ISSUE TITLE
Feature Request: Hayward Omnipool Heater Status

### ISSUE THREAD

**Issue by soupman98** [home-assistant/home-assistant.github.io#30986]
### Feedback

I'd like to propose adding features to enable Heater features and status:

1. Heater on or off (status)
2. Heater control (turn on/off)
3. Heater high limit
4. Heater low limit set
5. Heater timer set

I have Hayward Ominpool equipment, Smarthings, Home Assistant, Hubitat and ActionTiles capabilities to test.

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2024.1.5

**Comment by djtimca** [comment]
Thanks @soupman98 these (or most of these) features are already available in the Omnilogic custom integration. The devs who built this original Home Assistant core integration aren't developing it any further at this point in the core.

**Comment by soupman98** [comment]
Thanks @djtimca  but if these heater entities are there, I sure don't have them or see them. (heater). I *think* I'm completely up-to-date on updates and such. 

What are the options around extending or forking?

**Comment by djtimca** [comment]
@soupman98 you will not find any of the features you're asking for in the core integration in Home Assistant. You will need to add one of the custom integrations through HACS. Do a search on the forums and you'll find two there - one is cloud based and one is local.

**Comment by soupman98** [comment]
thanks @djtimca. I'll go hunt.

**Comment by soupman98** [comment]
Thanks. I'm kinda new in the space, but I like to think IOT competent.
Where could a guy learn to code in this space? I'm not super conversant in Git/VSC, but making headway.
I could probably copy/munge my way into what I want to do or need, but trying to skip the basics and jump in the real world deep end.

Thanks for you response and guidance!
________________________________

**Comment by djtimca** [comment]
There are lots of good developer documents on the Home Assistant website to help you get started. You'll need to get proficient in Python to start. I found it helpful to go through the docs and also spend time going through existing integrations to better understand how things are implemented. Good luck!

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
