### ISSUE TITLE
Feature Request: Hayward Omnipool Chlorinator

### ISSUE THREAD

**Issue by soupman98** [home-assistant/home-assistant.github.io#30987]
### Feedback

I'd like to propose adding features to enable CHLORINATOR features and status:

1. Chlorinator on or off (status)
2. Chlorinator on/off (control)
3. Chlorinator % output configuration (set)
4. 3: Chlorinator timer set

I have Hayward Omnipool equipment, Smartthings, HomeAssistant, Hubitat and ActionTiles capabilities to test.

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2024.1.5

**Comment by djtimca** [comment]
Thanks @soupman98 - these are on the backlog for the custom integration, but the developers who originally implemented the core integration are no longer developing this integration in the Home Assistant core install and are focused only on the custom integration.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by soupman98** [comment]
Thanks. My bad. I realized that after my 3rd one..
Mea Culpa
________________________________
