### ISSUE TITLE
Feature Request: Hayward Omnipool Relay status

### ISSUE THREAD

**Issue by soupman98** [home-assistant/home-assistant.github.io#30989]
### Feedback

Hayward Omnipool controllers (at least mine) have two sets of four (4) relays for controlling things. 
4 High voltage relays 
4 Low voltage relays

I'd like to be able to see and display the status of those relays.

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2024.1.5

**Comment by djtimca** [comment]
@soupman98 all relays are surfaced in the custom integration for Omnilogic already. (Will not be added by the original devs to the core Home Assistant integration).

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
