### ISSUE TITLE
Leak state is not reported.

### ISSUE THREAD

**Issue by apronk1971** [home-assistant/home-assistant.github.io#31009]
### Feedback

After testing, I can't see any change when I force a leak alert with my sensor.

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2024.1.5

**Comment by AngellusMortis** [comment]
@home-assistant close

**Comment by AngellusMortis** [comment]
Wrong repo

**Comment by apronk1971** [comment]
And the right repo is?
