### ISSUE TITLE
Problems to see integration

### ISSUE THREAD

**Issue by oscherer** [home-assistant/home-assistant.github.io#31006]
### Feedback

I followed your instruction do modify config - but I can not see the integration in HA - here my config:
from the homematic line I add it to the original

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homematic:
  interfaces:
    rf:
      host: 192.168.127.224
      resolvenames: "json"
      username: "homeassist"
      password: "oskar1602"
    IP:
       host: 192.168.127.224
       port: 2010
       resolvenames: "json"
       username: "homeassist"
       password: "oskar1602" 
  hosts:
     CCU3:
       host: 192.168.127.224
       port: 2001
       username: "homeassist"
       password: "oskar1602"

### URL

https://www.home-assistant.io/integrations/homematic/

### Version

2024.1.5

### Additional information

Core
2024.1.5
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

**Comment by danielperna84** [comment]
The core integration is not being maintained anymore. Please switch to the new integration. You can find detailed instructions here: https://github.com/jens-maus/RaspberryMatic/wiki/HomeAssistant-Integration
