### ISSUE TITLE
Add English Language support to response data from DWD. 

### ISSUE THREAD

**Issue by FS1961** [home-assistant/home-assistant.github.io#31013]
### Feedback

Apparently the api is also available in English.  There are json data specifically in English. 

### URL

https://www.home-assistant.io/integrations/dwd_weather_warnings/

### Version

2024.1.5

### Additional information

DWD Warnwetter app is based on this so there must be a way. 

Here is what their app provides. Looking for similar text, not necessarily the graphics:

![IMG_1751](https://github.com/home-assistant/home-assistant.io/assets/98458806/dccbcb9c-142f-432a-8e64-17ee950f9fbb)

**Comment by stephan192** [comment]
Hi @FS1961 
first of all this is not an issue (and in addition this is the wrong repository, [core](https://github.com/home-assistant/core) would be the right one), it is a feature request which should be placed in the [forum](https://community.home-assistant.io/c/feature-requests).

But never the less i did some research but i could not retrieve any English warnings. Appending "&language=eng" should do the trick but didn't work for me. Even the DWD homepage set to English gives me only German warnings.

The [underlaying api](https://github.com/stephan192/dwdwfsapi) performes queries like:
https://maps.dwd.de/geoserver/dwd/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=dwd%3AWarnungen_Gemeinden&CQL_FILTER=WARNCELLID%3D%27801002000%27&OutputFormat=application/json
English data should be reported by
https://maps.dwd.de/geoserver/dwd/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=dwd%3AWarnungen_Gemeinden&CQL_FILTER=WARNCELLID%3D%27801002000%27&OutputFormat=application/json&Language=eng
but this doesn't work for me

> Apparently the api is also available in English. There are json data specifically in English.

Can you please tell me where i can find the English json data?

**Comment by FS1961** [comment]
@stephan192 - thanks for replying. I'm not sure if this helps, but the app and website are here:
https://www.dwd.de/EN/ourservices/warnwetteapp/warnwetterapp.html

I've emailed them and asked the question.  

I can only assume since they are doing it in their own app, it must be possible?

**Comment by FS1961** [comment]
It’s still relevant for me but if no one is going to work on it …

**Comment by andarotajo** [comment]
@FS1961 did you get a response to your email? I've looked into it a bit and to me it seems that it's not possible as stephan stated. The app you linked also has the following disclaimer:

>To use the english version, the language setting of the device or of the WarnWetter App must be in English. You will receive severe weather warnings in English, but all text reports are in German

**Comment by FS1961** [comment]
It’s interesting because it looks like Apple weather, Alexa weather both use the German weather reports and translate them to English. I will close the issue and pursue this via a different avenue.
