### ISSUE TITLE
this outdated form of authentication will soon stop working

### ISSUE THREAD

**Issue by nzangel** [home-assistant/home-assistant.github.io#31027]
### Feedback

For Tado integration :
Please note that this outdated form of authentication will soon stop working. We plan to deactivate it on February 12, 2024.

### URL

https://www.home-assistant.io/integrations/tado/

### Version

2024.1.5

**Comment by frenck** [comment]
Hi there @nzangel 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
