### ISSUE TITLE
Ports as to be opened

### ISSUE THREAD

**Issue by bmo-v** [home-assistant/home-assistant.github.io#31028]
### Feedback

Hello,
I followed several tutorials to get my raspberry running, in French or in English, and ended up with failures.
Finally someone mentioned port issues.
I think that like me you have a box interfacing ADSL or optical fiber with LAN and provides the router function.
None of the creators mention that you have to open ports 80 and 443 for homeassistant and even less how to do it.
Between the creation phase of the (SD or SSD) and the start of HA, there is a real gap.
Although this procedure may be difficult to describe, point out that this operation is mandatory with a router.
thank you for your attention. Bernard

### URL

home-assistant/home-assistant.io/

### Version

any versions

**Comment by klaasnicolaas** [comment]
Home Assistant runs locally and you do not have to open a port in your router to use it, therefore not included in the installation instructions. If you would like to access Home Assistant outside your own home network, there are many ways to do this and everyone will advise you differently 😉 

./Klaas
