### ISSUE TITLE
Soft Radyo To Add !

### ISSUE THREAD

**Issue by djcuneyt** [home-assistant/home-assistant.github.io#31032]
### Feedback

Hello. We would be happy if you add our radio to your application.
Our radio broadcasts 24 hours a day with high sound quality.
is doing.
Soft Radyo launched in the last months of 2019 with the slogan 'The Oldest Form of Love'.
started its publishing life. The unforgettable, unforgettable memories of the 80's and 90's
the best and most special Turkish slow music of today
Playing internet radio.

Name of Our Radio: Soft Radyo
Our website: www.softradyo.com.tr
Publication Style: Turkish Slow, Nostalgia
E-Mail: info@softradyo.com.tr
Whatsapp: 0850 - 441 44 74
Our Broadcast Link: https://radyo.softradyo.com/1140/stream
Our Radio Logos:
https://www.softradyo.com/wp-content/uploads/2021/11/SoftRadyoRenkli.png
https://www.softradyo.com/wp-content/uploads/2023/02/WhatsApp-Image-2023-02-07-at-13.55.15-1.jpeg
https://www.softradyo.com/wp-content/uploads/2023/02/SoftRadyo_Logo-2.jpg

regards

Merhabalar. Radyomuzu uygulamanıza eklerseniz seviniriz.
Radyomuz yüksek ses kalitesi ile kesintisiz olarak 24 saat yayın
yapmaktadır.
Soft Radyo, 2019 Yılının son aylarında ‘Aşkın En Eski Hali’ sloganıyla
yayın hayatına başlamıştır. 80’lerin ve 90’ların unutulmayan, unutulmaya
yüz tutmuş, günümüzün ise en iyi ve en özel Türkçe slow müziklerini
çalan internet radyosudur.

Radyomuzun Adı: Soft Radyo
Web sitemiz: www.softradyo.com
Yayın Tarzı: Türkçe Slow, Nostalji
E-Mail: info@softradyo.com
Whatsapp: 0850 - 441 44 74
Yayın Linkimiz: https://radyo.softradyo.com/1140/stream
Radyo Logolarımız: 
https://www.softradyo.com/wp-content/uploads/2021/11/SoftRadyoRenkli.png
https://www.softradyo.com/wp-content/uploads/2023/02/WhatsApp-Image-2023-02-07-at-13.55.15-1.jpeg
https://www.softradyo.com/wp-content/uploads/2023/02/SoftRadyo_Logo-2.jpg

Saygılarımızla

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2024.1.5

**Comment by klaasnicolaas** [comment]
Your are on the wrong place, the integration is using the api from radio browser and there you can add new stations to the database 😉

https://www.radio-browser.info/

./Klaas
