### ISSUE TITLE
Only works very close by

### ISSUE THREAD

**Issue by PrestonMcAfee** [home-assistant/home-assistant.github.io#31030]
### Feedback

First, I enjoyed the project and it works.  Definitely the price is impressively low.   I'm a newbie to HA and had never used ESPhome or Samba before.  It was more complicated that I expected but I got through it with a little searching.  (One thing that is great about HA is the extensive documentation online.)  

Things I wished I had known: the installation takes a very long time to process, 1300 seconds.  I kept thinking that something was hanging.  You have to be very close to the $13 device for it to hear you.  My thought had been that it could be at the corner of the desk and still hear me; in fact if it is half a meter away, it won't hear the wake phrase.  So in the end I use assist on the phone rather than these devices.  

The devices work best if you create some short phrases that run automations.  Otherwise, you have to be too precise in language (name of device, what you want to do) to make it faster than pulling out your phone.  I appreciate that it is private; we don't use Alexa or similar in our house for privacy reasons.

I wish the documentation had more information about setting up Samba, e.g. I didn't have SMB running on my PC and it took me a while to figure out that this is why moving my voice file to HA wasn't working.

I came here to provide feedback rather than create an issue, so feel encouraged to mark it resolved.

### URL

https://www.home-assistant.io/voice_control/troubleshooting/

### Version

2024.1.3

**Comment by synesthesiam** [comment]
Hi @PrestonMcAfee, thanks for giving voice a try! I'm the "voice guy" from Nabu Casa.

Can you provide a few details to help me try and guess what's going on? Specifically:
* Some components of your voice assistant pipeline (wake word, speech-to-text)
* The ESPHome YAML that is on the Atom Echo

The Atom Echo requires boosting the mic volume significantly for it to work from across the room (which also requires increasing the noise suppression). It's sometimes necessary to use settings like this in the ESPHome YAML:

```yaml
voice_assistant:
  noise_suppression_level: 3
  auto_gain: 31dBFS
  volume_multiplier: 10.0
  # ...
```

**Comment by PrestonMcAfee** [comment]
Sure, my wake word is O_kay_zimmer, which is pronounced reasonably well.  I get 90% recognition if I hold the device 5cm from my mouth, zero at 50cm.  

Here is the ESPHome code:
substitutions:
  name: m5stack-atom-echo-23d044
  friendly_name: Voice1
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ci69PesvbfZ0GRu6f2MIrJXF3oEW3McBmaqnptvKD1M=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

I'm adding the code you supplied to that YAML now.

**Comment by PrestonMcAfee** [comment]
Well, that (adding the code to the YAML in ESPHome) didn't work so I rolled back.  Where does that code go?

**Comment by PrestonMcAfee** [comment]
When I added that code to the ESPHome, the voice assistant quit responding, even up close.  I bought four of these but only tested the code on two of them.  Is it normal that these tests take over half an hour each?  ESPHome writes a lot of code to the device.

**Comment by c0ffeeca7** [comment]
Hi, @PrestonMcAfee. Thank you for your feedback.

About Samba: in the procedure [on tweaking the config](https://www.home-assistant.io/voice_control/troubleshooting/#tweaking-the-assist-audio-configuration-for-your-device), there is a link to the instructions on [setting up Samba](https://www.home-assistant.io/common-tasks/os/#installing-and-using-the-samba-add-on).
My question: did you not see that link or did you find those instructions unclear?

**Comment by PrestonMcAfee** [comment]
This is on me -- even though I read the instructions several times prior to the devices arriving, I definitely encountered instruction fatigue during the process.  It would have been helpful to have a heads-up that the samba installation process takes 20 minutes (at least it did for me), which I wasn't expecting.  The other thing that flummoxed me was that I turned SMB off on my windows PC, based on security warnings years ago, and of course there wasn't a mechanism to alert me that the reason I couldn't get samba to connect was that it was turned off in the PC.  

I'll follow the instructions in the link and report back

**Comment by PrestonMcAfee** [comment]
Okay, I tried to follow the instruction.  I connected to Samba, added 

assist_pipeline:
   debug_recording_dir: /share/assist_pipeline

to configuration.yaml, which I could have done with studio code server, and then tried to follow instruction 7:
![instruction](https://github.com/home-assistant/home-assistant.io/assets/41998813/fa479bab-bc3f-4865-8ba9-75ad6a76cbe4)
![edit](https://github.com/home-assistant/home-assistant.io/assets/41998813/c5197566-9a89-46a0-9524-fa36ce7a26d2)

 but the voice assistant section didn't appear in the file.  Now what I had done originally was add the code you suggested to that file (reached through ESPHome, where clicking on edit brings up the yaml file).  That seemed to disable the device, though, so I rolled back and removed it.  

It is likely that I have some basic misunderstanding and that others wouldn't have this trouble.  I appreciate your patience and your contributions to this awesome community and product!

**Comment by c0ffeeca7** [comment]
`but the voice assistant section didn't appear in the file. `
- right, if you're doing it for the first time, that section won't be there. The guide needs to be adjusted there. Thank you for pointing that out.

`That seemed to disable the device,`
- what do you mean, this disables the device? Can you try adding the lines again and save?

**Comment by PrestonMcAfee** [comment]
Sorry, it quit responding to voice commands.  However, I have repeated the effort and it now responds to voice commands, although still only up close.  I suspect I failed to let the write process (which compiles a lot of files!) finish properly.  Here are the settings I have now and I still have to be very close before it recognizes the keyword:
voice_assistant:
  noise_suppression_level: 4
  auto_gain: 31dBFS
  volume_multiplier: 15.0

However, the problem seems to be with my wake word, which I established by saying the wakeword up close, seeing the blue flashing lights, and then speaking the command from a much greater distance.  I tried turning off the wake word in ESPHome, restarting HA, but when I push the button on top (with a half circle attached, not the reset button) I either get nothing (short press) or a red flash (longer press).

I'm sorry to be dense and am wondering if it is time to reset and reinstall.

**Comment by PrestonMcAfee** [comment]
Here is my configuration file:

substitutions:
  name: m5stack-atom-echo-23d044
  friendly_name: Office Mic
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: ci69PesvbfZ0GRu6f2MIrJXF3oEW3McBmaqnptvKD1M=

voice_assistant:
  noise_suppression_level: 4
  auto_gain: 31dBFS
  volume_multiplier: 15.0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

I tried "validate" from ESPHome, which came back Validated!, and also clean, which deleted two files.

**Comment by c0ffeeca7** [comment]
I am sorry to hear that this troubleshooting is causing you so many issues.
Thank you for all your feedback. I'm updating the procedure to add the add-on and use File Editor instead of SMB. This should address some of the issues you have encountered. #31133

**Comment by c0ffeeca7** [comment]
`However, the problem seems to be with my wake word, which I established by saying the wakeword up close, seeing the blue flashing lights, and then speaking the command from a much greater distance. I tried turning off the wake word in ESPHome, restarting HA, but when I push the button on top (with a half circle attached, not the reset button) I either get nothing (short press) or a red flash (longer press).`

- When you check under **Voice assistant** > **Expose**
  - Are there any devices exposed to Assist?
  - I can reproduce this behavior when no devices are exposed. 
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/7195a6dd-6abd-4b2f-bd82-8aa1f7e5a287)

**Comment by PrestonMcAfee** [comment]
That seems to fix it -- I had 209 devices entities (which is itself a weird number because i have over 400 entities) and when I unexposed all of them, the voice assistant began working.  This is pretty much a fix since I was only using them for some programmed phrases, which still work, and I can expose a few other frequent entitites.  Thank you!

**Comment by c0ffeeca7** [comment]
Glad to hear this works now. Regarding the wake word: does it work better when you use the default (OK Nabu), rather than your custom wake word?
