### ISSUE TITLE
Add H5104 Hygrometer Thermometer to Supported Devices

### ISSUE THREAD

**Issue by mtdern** [home-assistant/home-assistant.github.io#31053]
### Feedback

Just went ahead and ordered the H5104 and they seem to work perfectly fine. Auto-discover and connection, data, everything's there - seems to be a direct clone of the 5102 and similar units. Cheers!

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2024.1.5

**Comment by bdraco** [comment]
https://next.home-assistant.io/integrations/govee_ble/

Officially supported in 2024.2.x
