### ISSUE TITLE
Add H5108 Temp Sensor support

### ISSUE THREAD

**Issue by newcxcw** [home-assistant/home-assistant.github.io#31079]
### Feedback

I recently purchased two H5108 remote temp bluetooth sensors, then learned that they are not supported like my other Govee sensors.  Please add support for these sensors.

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2024.1.5

**Comment by bdraco** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by bdraco** [comment]
The underlying library accepts feature requests via https://github.com/Bluetooth-Devices/govee-ble/issues/new?assignees=&labels=enhancement&projects=&template=2-feature-request.md as well
