### ISSUE TITLE
Ebusd on same computer as HA

### ISSUE THREAD

**Issue by eerke2021** [home-assistant/home-assistant.github.io#31073]
### Feedback

Given ebusd website recommends the Lukas Grebbe Home Assistant Add On the instructions should include what to do if ebusd is running on same HA instance. 

### URL

https://www.home-assistant.io/integrations/ebusd/

### Version

2024.1.5

**Comment by frenck** [comment]
Hi there @eerke2021 👋 

Thanks for the suggestion, however, Home Assistant doesn't support the use of third-party add-on. Please refer to the documentation of the third-party add-on for instructions on how to use it.

../Frenck

**Comment by eerke2021** [comment]
Even if the third party add on is recommended on the official ebusd site?
