### ISSUE TITLE
Outdated Tado authentication request?

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#31085]
### Feedback

Tado have contacted me regarding outdated authentication requests (i.e. pasing username and password in the URL rather than using OATH2).  Which method is the HA TADO integration using?

### URL

https://www.home-assistant.io/integrations/tado/

### Version

2024.1.5

**Comment by erwindouna** [comment]
You're mentioning you're using version 2024.1.5. This has already been patched since version 2024.1.1. No need to worry. :)

**Comment by erwindouna** [comment]
@home-assistant close
