### ISSUE TITLE
Add Yale Unity Entrance Lock (YUR/DEL/1/SIL) to supported devices list

### ISSUE THREAD

**Issue by bazzadazza72** [home-assistant/home-assistant.github.io#31083]
### Feedback

I have this lock in my home and it works reliably, supporting lock states, battery levels and the action of locking and unlocking the lock.
If it's not important to add as a device, that's okay! 😅

Screenshot evidence:

![Screenshot 2024-01-27 140722](https://github.com/home-assistant/home-assistant.io/assets/39453825/71bd38a2-9940-4a1f-8ba9-e0abc5f21581)

### URL

https://www.home-assistant.io/integrations/yalexs_ble/

### Version

2024.1.5

**Comment by cloudbr34k84** [comment]
What other entities does this lock expose?
