### ISSUE TITLE
https://server.growatt.com this link is not integrated!!!!

### ISSUE THREAD

**Issue by IInQuII** [home-assistant/home-assistant.github.io#31090]
### Feedback

https://server.growatt.com this link is not integrated!!!!

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Ps. Several issues have already arisen about this, so take a look at the issue overview beforehand.

Thanks! 👍

./Klaas
