### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by mobile26** [home-assistant/home-assistant.github.io#31094]
### Feedback

Cannot find the following:

Charging: Time to completion

Wake/Asleep: Status

Sunroof open/closed: Operation and status

### URL

https://www.home-assistant.io/integrations/tessie/

### Version

2024.1.5

**Comment by Bre77** [comment]
Time to charge should be added in 2024.2
https://github.com/home-assistant/core/pull/108342

Awake/Asleep is binary_sensor.name_status

Sunroof hasn't been implemented, so you can either raise a PR or I'll add it when I can.
