### ISSUE TITLE
Make It aso it Can Be added From Ui.

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#31097]
### Feedback

Hi, I Am Trying To Set Up Transport NSW On My Home Assistant But I Can Not. It Would Be Better If i Could Add It From The Ui.

### URL

https://www.home-assistant.io/integrations/transport_nsw/

### Version

2024.1.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
