### ISSUE TITLE
Describe process for adding new opower-enabled utilities

### ISSUE THREAD

**Issue by phipolis** [home-assistant/home-assistant.github.io#31102]
### Feedback

I haven't been able to track down any information on the process for adding or requesting a new opower-enabled utility, either from a user or a developer's perspective. It [seems](https://github.com/home-assistant/core/pull/106146/files) to be a virtual integration requiring only a domain name and display name... But are there any other criteria? Should users open an issue requesting their provider be added to the list, or is it more work than that?

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2024.1.5

**Comment by tronikos** [comment]
You first need to write code to parse the login page see https://github.com/tronikos/opower specifically all the different implementations at https://github.com/tronikos/opower/tree/main/src/opower/utilities

**Comment by tronikos** [comment]
@home-assistant close
