### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by rcperkinsjr** [home-assistant/home-assistant.github.io#31105]
### Feedback

the links provided in the directions did not work. 

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2024.1.5

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation, not for providing support or tracking integration issues.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

If you are suspecting a bug, please file an issue in our Core issue tracker instead. You can find that one here:

https://github.com/home-assistant/core/issues

Thanks! 👍

../Frenck
