### ISSUE TITLE
SMA is not working for the Energy Dasbord

### ISSUE THREAD

**Issue by chrkraus** [home-assistant/home-assistant.github.io#31117]
### Feedback

SN: 301********* PV Power is missing for the solar production
SN: 301********* Metering Power Supplied is missing for the Netzeinspeisung

### URL

https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities

### Version

2024.1.5

**Comment by klaasnicolaas** [comment]
This is explained here: https://www.home-assistant.io/docs/energy/faq/#energy-vs-power
