### ISSUE TITLE
QNAP QSW Documentation page should reflect that the integration old supports older devices 

### ISSUE THREAD

**Issue by peng1can** [home-assistant/home-assistant.github.io#31112]
### Feedback

Per the closed ticket at https://github.com/home-assistant/core/issues/82511, I believe it is worth noting in the documentation for QNAP QSW that model QSW-M2116P-2T2S and others use a different API that is not supported and not planned to be.  This is particularly important because the switch is auto-detected by HA and it suggests logging in without providing any hint to the user that these models are not supported.

### URL

https://www.home-assistant.io/integrations/qnap_qsw/

### Version

2024.1.5

**Comment by dalto12593** [comment]
@peng1can  thank you for posting this. I've been trying for days to get the integration working with my QSW-M2116P-2T2S. I agree that an advisory is needed for the switches that aren't compatible.

**Comment by Noltari** [comment]
> @peng1can  thank you for posting this. I've been trying for days to get the integration working with my QSW-M2116P-2T2S. I agree that an advisory is needed for the switches that aren't compatible.

@peng1can @dalto12593 feel free to create a Pull Request clarifying that.
