### ISSUE TITLE
missing server (https://server.growatt.com/)

### ISSUE THREAD

**Issue by rogeliomartin** [home-assistant/home-assistant.github.io#31129]
### Feedback

Hi! if you please could add the server (https://server.growatt.com/) to the list it would greatly appreciated!

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.4

### Additional information

Hi! if you please could add the server (https://server.growatt.com/) to the list it would greatly appreciated!

**Comment by klaasnicolaas** [comment]
Duplicate of #31090

Always check existing issues before creating a new one. There has been a lot of talk about growatt lately, but this is not the right repository for that.

./Klaas
