### ISSUE TITLE
Growatt UK website missing from configuration choices

### ISSUE THREAD

**Issue by ececconi99** [home-assistant/home-assistant.github.io#31120]
### Feedback

When trying to configure the HA Growtt integration login details the URL choice is:
https://server-api.growatt.com/
https://server-us.growatt.com/
http://server.smten.com/

UK users trying to register an account in these are redirected instead to get an account here:
https://server.growatt.com/
but this is not available in HA.
Can it be added, please?

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by ececconi99** [comment]
Ok I'll try to find the right place
