### ISSUE TITLE
Multiple shoppint lists

### ISSUE THREAD

**Issue by anthony1849** [home-assistant/home-assistant.github.io#31146]
### Feedback

Perhaps I have not figured it out, or maybe it is not supported, but I see no instructions regarding setting up multiple shopping lists i.e. different stores etc.   A discussion of this either way would be helpful in the documentation.   
Thank you, 
Anthony

### URL

https://www.home-assistant.io/integrations/shopping_list/

### Version

2024.1.5

**Comment by R999UK** [comment]
Perhaps I have misunderstood your question but I can create multiple lists by clicking 'Create list' at the bottom of the "list of lists".
![shoppingList](https://github.com/home-assistant/home-assistant.io/assets/117030476/8b0fc43a-6c67-4d44-9101-0465dee2083e)

The problem I have is that only the first list I created will generate a notification. 
I have posted a question about this here
[https://community.home-assistant.io/t/shopping-list-notification-not-working-properly/681498](url)

**Comment by jonathanathe** [comment]
> Perhaps I have misunderstood your question but I can create multiple lists by clicking 'Create list' at the bottom of the "list of lists". ![shoppingList](https://private-user-images.githubusercontent.com/117030476/301223519-8b0fc43a-6c67-4d44-9101-0465dee2083e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzMwNTcsIm5iZiI6MTcxMjIzMjc1NywicGF0aCI6Ii8xMTcwMzA0NzYvMzAxMjIzNTE5LThiMGZjNDNhLTZjNjctNGQ0NC05MTAxLTA0NjVkZWUyMDgzZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQxMjEyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjE0ODlkYmMyN2ZkNmQ1NTQ5YmI0NjU3OTE0MWE2Nzg2MDUyODE4NWY1M2FiNWUwY2IzMTdjMmUyMjFmNmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ZQsGIQTiW9nzh3xA6RFLtVqiv1NYMqTKeT1oGfDaGE)
> 
> The problem I have is that only the first list I created will generate a notification. I have posted a question about this here [https://community.home-assistant.io/t/shopping-list-notification-not-working-properly/681498](url)

Hello, what I understand @anthony1849 to be saying is that it doesn't allow creating more than one shopping list. What you show in your photo is for creating a to-do list. If you enter the "Shopping List" integration, it won't let you create another one; you'll get an error indicating that a shopping list has already been created.

I think we should be able to have multiple shopping lists because we don't always shop at a single supermarket.

Thank you!

**Comment by frenck** [comment]
Home Assistant doesn't support multiple shopping lists. Alternatively, you could create multiple todo-lists. Please note, a shopping list == a todo list under the hood.

../Frenck
