### ISSUE TITLE
Virtualbox 7 on Mac OS X virtualbox on late 2012 mac mini did not work

### ISSUE THREAD

**Issue by achterluikje** [home-assistant/home-assistant.github.io#31141]
### Feedback

Hi HA team,

After following your instructions I was able to get HA running once in virtual box 7.0 on my late 2012 mac mini. After rebooting the Mac Mini I could not get HA running again even after recreating the virtual machine and using the clean vdi file. Other users complained about the Virtual Box 7 breaking things. So I removed Virtual Box 7.0 and installed Virtual Box 6.1 after this I was able to start Home Assistant :-) I hope this can help other users as well and maybe it can be found out what Virtual Box 7.0 breaks as I couldn't find anything in the logs that pointed me in the right direction.

Kind regards,

Diederik  

### URL

https://www.home-assistant.io/installation/macos/

### Version

2024.1.5

**Comment by fluxpiada** [comment]
I was unable to install the .vdi on MacOS 10.15.7 (Catalina) Mac mini Late 2012 using VirtualBox. The .vdi was grayed out. 
Please allow for VMWare install also.
