### ISSUE TITLE
When I try to add the integration, it says "invalid_location"

### ISSUE THREAD

**Issue by master4g** [home-assistant/home-assistant.github.io#31154]
### Feedback

I tried to change my location on the popup, in the settings, in the Yaml but nothing seems to work

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2024.1.6

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
