### ISSUE TITLE
Add H5105 Hygrometer Thermometer to Supported Devices

### ISSUE THREAD

**Issue by Norrodar** [home-assistant/home-assistant.github.io#31151]
### Feedback

I just ordered 6 times the Govee H5105 and they seem to work fine. Putted in the battery and the appeared in Auto-Discover and sending data:

![grafik](https://github.com/home-assistant/home-assistant.io/assets/551636/b43c9a1e-5247-424d-96ed-299559214baa)

Don't know what's up with signal strength, if I missed a setting or something like that

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2024.1.5

**Comment by bdraco** [comment]
This device is not officially supported.  When we have tests for it, we will add it to the page.

**Comment by bdraco** [comment]
Please open a feature request at https://github.com/Bluetooth-Devices/govee-ble/issues/new?assignees=&labels=enhancement&projects=&template=2-feature-request.md

If you provide `AdvertismentData` as done in previous issues on that repo, we can add tests for it and add proper support

**Comment by bdraco** [comment]
Previous examples

https://github.com/Bluetooth-Devices/govee-ble/issues/70
https://github.com/Bluetooth-Devices/govee-ble/issues/42
