### ISSUE TITLE
Phantom kwh every day at 0:00

### ISSUE THREAD

**Issue by ceditou** [home-assistant/home-assistant.github.io#31152]
### Feedback

On daily view the energie Dashboard i get Solar production that rise day by day at 0:00 am. With the total one it doesn’t
Thanks
![IMG_0611](https://github.com/home-assistant/home-assistant.io/assets/142503922/bd40edab-7e3e-4a04-8658-aceee05d9947)
![IMG_0612](https://github.com/home-assistant/home-assistant.io/assets/142503922/2ce41351-450c-46f1-a1d8-7e76d026b1b9)
![IMG_0610](https://github.com/home-assistant/home-assistant.io/assets/142503922/b798a426-ae5b-4a75-beed-8b04965dbb3d)
![IMG_0613](https://github.com/home-assistant/home-assistant.io/assets/142503922/968c16f8-d104-4157-bebd-2e6e2407250d)
![IMG_0614](https://github.com/home-assistant/home-assistant.io/assets/142503922/ac25fed9-9440-4889-96ba-79c6e4fe7b65)

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2024.1.6

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
