### ISSUE TITLE
Refoss Integration issue adding MTS200

### ISSUE THREAD

**Issue by sandalf90** [home-assistant/home-assistant.github.io#31164]
### Feedback

Hi, when I try to add Refoss MTS200 through Refoss Integration, the integration show message "No device found on your network"

### URL

https://www.home-assistant.io/integrations/refoss/

### Version

2024.1.6

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
