### ISSUE TITLE
2 service accounts?

### ISSUE THREAD

**Issue by talormanda** [home-assistant/home-assistant.github.io#31175]
### Feedback

Under "GOOGLE CLOUD PLATFORM CONFIGURATION" it instructs you to create a service account and add it to your configuration.yaml.

At the bottom under the "ENABLE DEVICE SYNC" section it says to create another service account but not how to add this 2nd account. Is this duplicate info and we only need 1 service account?

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2024.1.6

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/10092964/ac2933a6-0d4e-443d-8104-b7d945c2cfe4)

**Comment by darthklaus59** [comment]
Hello,
Somehow it doesn't make sense with 2 service accounts. You refer to the Homegraph API, how is that supposed to work?

**Comment by talormanda** [comment]
> Hello, Somehow it doesn't make sense with 2 service accounts. You refer to the Homegraph API, how is that supposed to work?

I am pretty sure you only need one service account because I deleted the second and everything still functions the same.
