### ISSUE TITLE
Response to rest_command service

### ISSUE THREAD

**Issue by chmtc94** [home-assistant/home-assistant.github.io#31188]
### Feedback

Hi,

1) As this rest_command is able to send GET requests, could you provide in the documentation an example where a GET service is called and the response used for chaining other action(s) for example.
(I know it is possible to create a restful sensor to do that but it creates a potentially not needed sensor and a perpetual polling at a polling interval...)

2) Calling the rest_command service via the developer tool UI should also display the response data and status.

### URL

https://www.home-assistant.io/integrations/rest_command/

### Version

2024.1.6

**Comment by jpbede** [comment]
> 1. As this rest_command is able to send GET requests, could you provide in the documentation an example where a GET service is called and the response used for chaining other action(s) for example.

Do you have a good example? Otherwise I need to think of one

> 2. Calling the rest_command service via the developer tool UI should also display the response data and status.

This feature will be shipped with the 2024.2 release

**Comment by chmtc94** [comment]
1) Great example added in
https://www.home-assistant.io/integrations/rest_command/
Exactly what I (and also many others 😉) needed 👍👍

👉 USING REST COMMAND RESPONSE IN AUTOMATIONS

REST commands provide a service response in a dictionary containing status (containing the HTTP response code), and content containing the response body as text or JSON. This response can be accessed in automations using [response_variable](https://www.home-assistant.io/docs/scripts/service-calls#use-templates-to-handle-response-data).

The following example shows how the REST command response may be used in automations. In this case, checking the [Traefik API](https://doc.traefik.io/traefik/operations/api/) for errors.

# Create a ToDo notification based on file contents
automation:
  - alias: "Check API response"
    trigger:
      - ...
    action:
      - service: rest_command.traefik_get_rawdata
        response_variable: traefik_response
      - if: "{{ traefik_response['status'] == 200 }}"
        then:
          - alias: "Parse data"
            variables:
              routers: "{{ traefik_response['content']['routers'] }}"
              router_errors: >
                {%- for router in routers -%}
                  {%- if 'error' in routers[router] -%}
                    {{router}}: {{ routers[router]['error'] }}
                  {% endif -%}
                {%- endfor -%}
              got_errors: "{{ router_errors|length > 0 }}"
          - if: "{{ got_errors }}"
            then:
              - service: notify.mobile_app_iphone
                data:
                  title: "Traefik errors"
                  message: "{{ router_errors }}"
        else:
          - service: notify.mobile_app_iphone
            data:
              title: "Could not reach Traefik"
              message: "HTTP code: {{ traefik_response['returncode'] }}"

rest_command:
  traefik_get_rawdata:
    url: http://127.0.0.1:8080/api/rawdata
    method: GET

2) 2024.2 update UI developer tools.

Calling a rest_command service using the UI developer tools, now display the response message and status 👍👍
Works perfectly 

Thanks a lot for this very quick and good job🙏

Close perfectly the issue 😉
