### ISSUE TITLE
Siri doesn't do her job

### ISSUE THREAD

**Issue by Ewoodster** [home-assistant/home-assistant.github.io#31187]
### Feedback

There are several people, me included, where the voice control via Siri doesn't work.
Saying "Siri, Assist" activates her. Then, telling her to do whatever she is supposed to do is ansered by "done", but she does nothing.

No one has found a solution so far. Problem exists since the start of year of the voice.

### URL

https://www.home-assistant.io/voice_control/apple/

### Version

2024.1.6

**Comment by B0rax** [comment]
It is not Siri’s fault. The provided shortcut is missing the output.

**Comment by carmen54321** [comment]
what can i do bout it?
doesnt work for me, only if i write text.

**Comment by Ewoodster** [comment]
Same here. It seems to be a problem with Siri for non English speakers. See also here: https://community.home-assistant.io/t/siri-shortcut-doesn-t-work/567816/8

No solution so far
