### ISSUE TITLE
I can't install it on the Raspberry Pi.

### ISSUE THREAD

**Issue by nzz196** [home-assistant/home-assistant.github.io#31182]
### Feedback

I can't install it on the Raspberry Pi.
[logs.txt](https://github.com/home-assistant/home-assistant.io/files/14123976/logs.txt)

### URL

https://www.home-assistant.io/help/reporting_issues/

### Version

2024.1.6

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
