### ISSUE TITLE
TP LInk

### ISSUE THREAD

**Issue by infinitejest** [home-assistant/home-assistant.github.io#31195]
### Feedback

THis integration does not work well. I can see the controller as an entity but non of the wifi devices I can see in home assistant ; so for the purpouse of tracking devices is not useful. 

### URL

https://www.home-assistant.io/integrations/tplink_omada/

### Version

2024.1.6

**Comment by MarkGodwin** [comment]
This was reported already in issue #109205.

It has been fixed in the next release.
