### ISSUE TITLE
Add code to unlock alarm 

### ISSUE THREAD

**Issue by chaletweb** [home-assistant/home-assistant.github.io#31199]
### Feedback

Thanks for all your work on freebox integration.
I have a special request : Could you please add a code/pin (that we can define in configuration.yaml or secret.yaml) in order to unlock the freebox alarm because without this config, everybody can unlock my alarm if i add the feature on my home assistant on a tablet on the wall 

Lock the alarm without code : OK (or have the choice to lock without code)
Unlock the alarm without code : Impossible (by default)

### URL

https://www.home-assistant.io/integrations/freebox/

### Version

2024.1.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by chaletweb** [comment]
i agree it's a feature request but providing from a security issue. So we are not really in a new feature, but to a feature to fix a big security issue.

**Comment by frenck** [comment]
Still a feature request, please use the right place for those.

You've submitted documentation feedback, there is no amount of documentation we can adjust to make this happen... 🤷 

../Frenck
