### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by jjtoard** [home-assistant/home-assistant.github.io#31205]
### Feedback

This integration doesn't work for two weeks and i'm not alone.
https://community.home-assistant.io/t/forecast-solar-stopped-working-and-became-unvailable/676535/3

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2024.1.6

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Ps. There are already issues open about this, best way to solve it is to disable the integration and turn back on after 1,5 hour.

Thanks! 👍

./Klaas
