### ISSUE TITLE
Key with same name

### ISSUE THREAD

**Issue by ProtossBlaster** [home-assistant/home-assistant.github.io#31204]
### Feedback

Hi to all in the file sensor I have find name name in 2 different kay
  RenaultSensorEntityDescription(
        # For vehicles that DO NOT report charging power in watts, this seems to
        # correspond to the maximum power that would be admissible by the car based
        # on the battery state, regardless of the type of charger.
        **### key="charging_power",**
        condition_lambda=lambda a: not a.details.reports_charging_power_in_watts(),
        coordinator="battery",
        data_key="chargingInstantaneousPower",
        device_class=SensorDeviceClass.POWER,
        entity_class=RenaultSensor[KamereonVehicleBatteryStatusData],
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        translation_key="admissible_charging_power",
    ),
    RenaultSensorEntityDescription(
        # For vehicles that DO report charging power in watts, this is the power
        # effectively being transferred to the car.
        **_### key="charging_power",_**
        condition_lambda=lambda a: a.details.reports_charging_power_in_watts(),
        coordinator="battery",
        data_key="chargingInstantaneousPower",
        device_class=SensorDeviceClass.POWER,
        entity_class=RenaultSensor[KamereonVehicleBatteryStatusData],
        native_unit_of_measurement=UnitOfPower.KILO_WATT,
        state_class=SensorStateClass.MEASUREMENT,
        value_lambda=_get_charging_power,
        translation_key="charging_power",

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2024.1.6

**Comment by epenet** [comment]
The `condition_lambda` is different for the two sensors, so this should not be a problem.

Each car should have EITHER the first sensor OR the second sensor.

**Comment by epenet** [comment]
Also

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. If you still feel that it is an issue worth reporting, please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍
