### ISSUE TITLE
Unable to connect via IP

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#31211]
### Feedback

I haven't been able to get this Netgear integration working at all. Not even by the IP, which is the only recommended troubleshooting step. I have 5 access points. Three different models. WAX630E (x3), WAX610Y (x1) &, WAX620 (x1). These are on a separate VLAN, however, there's no reason they should be prevented from talking. Also, access points seem to be supported but only in "router" mode?? This doesn't make much sense to me. Can this be changed? Does Insight Management affect this capability at all? I don't think my access points even have a router mode. 

### URL

https://www.home-assistant.io/integrations/netgear/

### Version

2024.1.6

### Additional information

WAPs are connected to five switches, GS108s mostly, but the main backbone switch is a MS510TXM, which is behind a Firewalla Gold Plus. WAPs and switches are currently all in local mode due to the lack of ability to manage certain advanced features within the Insight Management cloud portal.

**Comment by starkillerOG** [comment]
Not all acces points have the SOAP API needed to communicate with them.
So it might not be possible to set them up using the netgear integration.

What kind of errors do you see in the log?
