### ISSUE TITLE
Webhooks now require a Pro licence

### ISSUE THREAD

**Issue by EspeeFunsail** [home-assistant/home-assistant.github.io#31235]
### Feedback

IFTTT now requires a Pro Licence to create and receive web hooks. Makes it unusable for using in HA for people without a pro licence.

### URL

https://www.home-assistant.io/integrations/ifttt/

### Version

2024.1.6

**Comment by dannytsang** [comment]
Is there something in the Home Assistant documentation that is missing, incorrect or improvement as a result of this?

**Comment by EspeeFunsail** [comment]
Yes, the following link explains how to send and receive webhooks between HA and IFTTT, but does not mention that it requires a Pro license.

https://www.home-assistant.io/integrations/ifttt/

**Comment by MistressPlague** [comment]
+1, same issue.
