### ISSUE TITLE
File "/usr/src/homeassistant/homeassistant/components/remote_rpi_gpio/switch.py", line 82

### ISSUE THREAD

**Issue by mardm99** [home-assistant/home-assistant.github.io#31233]
### Feedback

Hello,
I installed Configuring Remote GPIO on a Raspberry Pi Zero 2 W.

In /homeassistant/configuration.yaml I added:
switch:
  - platform: remote_rpi_gpio
    host: 192.168.1.205
    ports:
      23: Grzejnik 1
      24: Grzejnik 2   
    invert_logic: true  

Integration works fine until I restart Raspberry Pi Zero 2 W.

When the Raspberry Pi Zero 2 W restarts, the integration fails

2024-02-04 17:49:16.059 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547235385792] unpack requires a buffer of 16 bytes
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
response = await hass.services.async_call(

The only way to solve the problem is to restart HA.
After an HA restart, the integration works correctly until another restart Raspberry Pi Zero 2 W.
The problem has been described by other users on the HA forum.

My HA works on Raspberry Pi 4 4GB RAM.
 Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

[home-assistant_2024-02-04T16-49-49.157Z.log](https://github.com/home-assistant/home-assistant.io/files/14157631/home-assistant_2024-02-04T16-49-49.157Z.log)

Regards,
Mariusz

### URL

https://www.home-assistant.io/integrations/remote_rpi_gpio/

### Version

2024.1.6

**Comment by frenck** [comment]
Hi there @mardm99 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>


Thanks 👍 

../Frenck
