### ISSUE TITLE
I cannot authenticate with my Growatt account

### ISSUE THREAD

**Issue by Vennis** [home-assistant/home-assistant.github.io#31245]
### Feedback

After starting the integration i cannot authenticatie on my GroWatt account. I'm using another server url for my account then the ones provided. I use server.growatt.com. If I use server-api.growatt.com I get error "Unknown error occurred". On the other urls I get unvalid authentication.
Regards, Henk Vennis

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.6

### Additional information

I'm running HA as a virtual server on my Synology DS220+. I'm running multiple integratios. I hope you have a solution for me. Regards, Henk Vennis

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
