### ISSUE TITLE
Suggestion regarding recent Valve Integration

### ISSUE THREAD

**Issue by LoznOz** [home-assistant/home-assistant.github.io#31257]
### Feedback

Hello
I'd like to suggest a small additional optional parameter to this integration to enable reversing the indicated valve state for those situations where, for whatever reason, a valve that is actually closed (or partly) but detected as open (or partly) (and visa versa) ie: reversed. I see that various users have suggested ways to get around this by (each user) creating custom template switches or like however my current thinking is fix at source (assuming one cannot readily change the Valve sensor data being derived from the source device).

### URL

https://www.home-assistant.io/integrations/valve/

### Version

2024.1.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by LoznOz** [comment]
Thanks for polite clear reply 
Understood 
Cheers
