### ISSUE TITLE
Installing HAOS to laptop with arch preinstalled possible after swapoffing swap partition

### ISSUE THREAD

**Issue by Nyyhaus** [home-assistant/home-assistant.github.io#31268]
### Feedback

Hi!

Thank you for great and detailed installation instructions and of course for providing Home Assistant in the first place! 

I followed the instructions and succesfully installed HAOS to old laptop with arch preinstalled on it. I did the installation with ubuntu live from usb stick. However when I tried to restore the disk image the system complained that the /dev/sda was busy. I had everything unmounted so I asked chatgpt what could be problem and it suggested to swapoff swap partition and it worked after that. So I would suggest you add a line to the instructions that sometimes swap partition can cause problems and it can be solved with swapoff command from the terminal. :)

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2024.1.6

**Comment by hermannbach** [comment]
Seems to be a problem as soon as a swap partition is available on the target device.

**Comment by Nyyhaus** [comment]
Hi

Can be closed. It was just a suggestion to add to the installation guide just in case someone gets stuck. :)

Greetings,
Ville Uusitalo

Sent with [Proton Mail](https://proton.me/) secure email.
