### ISSUE TITLE
History with MQTT sensors

### ISSUE THREAD

**Issue by wallacepa** [home-assistant/home-assistant.github.io#31266]
### Feedback

My MQTT sensors work well but the history graph, which works for temperature sensors on a Wemos D1 mini, does not show history longer than 10 days for the MQTT sensors.  I have tried adding a unique id but that does not seem to help.

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2024.1.6

**Comment by jbouwh** [comment]
May be the sensor misses a `state_class` setting?

https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes

**Comment by wallacepa** [comment]
I have added state_class: 'measurement' and will monitor the output

**Comment by jbouwh** [comment]
You can check here:

https://my.home-assistant.io/create-link/?redirect=developer_statistics

If your entity supports long term statistics now. As this is not an issue with the documentation, I'll close this ticket.

**Comment by wallacepa** [comment]
It does not!  I don't know if I need to wait 10 days to test it but currently the mqqt sensors do not show history over 10 days, even with state_class: 'measurement'

**Comment by wallacepa** [comment]
It has not worked so I still cannot see history but do I have to wait another 10 days?

**Comment by jbouwh** [comment]
> It has not worked so I still cannot see history but do I have to wait another 10 days?

If the sensor is listed, then history should be retained

**Comment by wallacepa** [comment]
Now, after 10 days, history is showing beyond 10 days.
Thanks for your help.  it would be good to flag this is needed for history to show.
You can close the ticket
