### ISSUE TITLE
Can't integrate Flexit bacnet

### ISSUE THREAD

**Issue by laphen81** [home-assistant/home-assistant.github.io#31261]
### Feedback

Hi, I'm trying to integrate Flexit bacnet, but I can't make it to work.

### URL

https://www.home-assistant.io/integrations/flexit_bacnet/#configuration

### Version

Core 2024.1.6

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/51716048/a247083a-e2c3-49e2-95a5-fb0ac5d4314b)

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
