### ISSUE TITLE
Growatt doesn't work

### ISSUE THREAD

**Issue by Tonipolo** [home-assistant/home-assistant.github.io#31264]
### Feedback

The registered server of Growatt is incorrect. It must be "https://server.growatt.com/".

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.1.6

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
