### ISSUE TITLE
Question about the distance

### ISSUE THREAD

**Issue by smarthomejunkie** [home-assistant/home-assistant.github.io#31260]
### Feedback

Hey there @mib1185, what is the distance value? Is it meters if my configuration is metric? In that case, a maximum of 100 is too low IMHO. I would like to have the distance work in a radius of several kilometers to make sure that I can for instance trigger my heating when I am approaching my home at about 5 kilometers.

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2024.2.0

**Comment by frenck** [comment]
Hi there @smarthomejunkie 👋 

Just to note, this integration will change in the upcoming 2024.2 release.

You can find the beta documentation for this integration here:

<https://rc.home-assistant.io/integrations/proximity>

> Hey there @mib1185, what is the distance value? Is it meters if my configuration is metric?

Yes, it uses the configured unit system in Home Assistant by default.

![CleanShot 2024-02-06 at 09 32 23@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/80447c71-52cb-4a0e-942f-df6c69bf6d74)

As the new entities will be sensors, the unit shows on the sensor:

![CleanShot 2024-02-06 at 09 35 10@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/dc6fa563-bca6-4a33-9eb1-3d2e27f1d085)

And can be adjusted to your liking, like any other sensor:

![CleanShot 2024-02-06 at 09 35 45@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/71433e68-9c59-45c8-877e-c75059487c72)

../Frenck

**Comment by smarthomejunkie** [comment]
Ah yes, now I see! Thank you.

**Comment by mib1185** [comment]
> a maximum of 100 is too low IMHO

just to make it clear - there is no limit/maximum for the distance, only the tolerance is limited

**Comment by smarthomejunkie** [comment]
> > a maximum of 100 is too low IMHO
> 
> just to make it clear - there is no limit/maximum for the distance, only the tolerance is limited

Thank you @mib1185. Is the tolerance also in the units that you define on the distance, or is it standard in meters?

**Comment by mib1185** [comment]
the tolerance is in meter, since under the hood all distance calculations are done in meters (_those the native sensor values are in meters_) and only the representation is converted to the defined unit system.

**Comment by smarthomejunkie** [comment]
> the tolerance is in meter, since under the hood all distance calculations are done in meters (_those the native sensor values are in meters_) and only the representation is converted to the defined unit system.

Superb, thank you. Working on a script for a video about your integration atm. ;)

**Comment by mib1185** [comment]
if you have any further question or feedback on the new proximity integration, don't hesitate to contact me on discord :)
