### ISSUE TITLE
Add a warning box for the add-ons not available with docker install *and* explains why add-ons are important

### ISSUE THREAD

**Issue by olignyf** [home-assistant/home-assistant.github.io#31272]
### Feedback

A bigger warning sign on the top of this page https://www.home-assistant.io/installation/raspberrypi/ should be put, in its own warning box instead of regular text explaining that the resulting installation is half useless without add-ons. Beginners have no idea what add-ons are at this point and why they are important. Explaining that they wont be able to flash ESPHome devices with yaml configurations. And maybe other limitations that I'm not aware of. What a waste of time !

Currently it just says in plain text without warning box :
```Before installing Home Assistant, you might want to [compare installation methods](https://www.home-assistant.io/installation#compare-installation-methods). Most notably, [add-ons](https://www.home-assistant.io/addons) are only available with the Home Assistant Operating System.```

Thanks

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.1.6

**Comment by vii33** [comment]
+1 
I went through all the troubles of docker installation only to find out that most features require add-ons.
