### ISSUE TITLE
Onboarding page (initial setup) missing a step

### ISSUE THREAD

**Issue by genterminl** [home-assistant/home-assistant.github.io#31277]
### Feedback

On the onboarding page near the end of the initial setup, the instructions do not actually say anywhere to press the button "CREATE MY SMART HOME."  This had me scratching my head.  Not for very long, but I did wonder for a moment if I had missed something or done something wrong.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2024.1.6

**Comment by genterminl** [comment]
You ask for feedback on the docs, and then apparently don't have the manpower to act on such suggestions.  Perhaps such suggestions can be accumulated in a doc which can be referred to and worked through if/when someone has the time.  Simply making them github issues and then closing them because there are too many is not really helpful to the project.  Feel free to close.

**Comment by genterminl** [comment]
Again, you ask for feedback on the docs, and then apparently don't have the manpower to act on such suggestions. Perhaps such suggestions can be accumulated in a doc which can be referred to and worked through if/when someone has the time. Simply making them github issues and then closing them because there are too many is not really helpful to the project.

**Comment by frenck** [comment]
This is an open source project, which means we rely on community contributions; feel free to help out and contribute!

The bot here, tries to keep everything that is recent here. Just a comment and it will back of. Without it, we will end up with a huge backlog of irrelevant and outdated feedback and issues, which also not helpful.

Thanks for understanding 👍 

../Frenck

**Comment by genterminl** [comment]
Thanks for the response.  I do maintain the documentation for a different open source project, and so I accept the difficulty of getting folks to work on documentation.  I'm still new enough with HA that I would not be comfortable mucking with the docs, but I'll try to keep it in mind for my copious (not) free time :-)

**Comment by c0ffeeca7** [comment]
Thank you for your feedback, @genterminl. 
I added a screenshot now so that this step becomes a bit more obvious.

**Comment by genterminl** [comment]
Thanks.  It really is appreciated.
