### ISSUE TITLE
Templating: Jinja 2 vs Jinja 3 vs HomeAssistant

### ISSUE THREAD

**Issue by MacDada** [home-assistant/home-assistant.github.io#31276]
### Feedback

# The problem

[According to the docs](https://www.home-assistant.io/docs/configuration/templating/#building-templates), the templating engine is based upon Jinja 2:

> Templating in Home Assistant is powered by the [Jinja2](https://palletsprojects.com/p/jinja) templating engine.

The problem is, that the links target the latest Jinja docs, which currently describe Jinja v3 (not v2), for example:

> While the [float](https://jinja.palletsprojects.com/en/latest/templates/#float) and [int](https://jinja.palletsprojects.com/en/latest/templates/#int) filters do allow a default fallback value if the conversion is unsuccessful, they do not provide the ability to catch undefined variables.

The link to v3 docs, while erroneously labeled as for v2, is also provided by `the Developer Tools -> Template` panel of HA:

![Screenshot 2024-02-06 at 19 31 58](https://github.com/home-assistant/home-assistant.io/assets/136261/d5c826c7-34fa-4b2c-b8ee-78ed13f12a9c)

# Possible solutions

a.) Easier: change links to the latest 2.x branch of docs: `https://jinja.palletsprojects.com/en/latest/templates/#float -> https://jinja.palletsprojects.com/en/2.11.x/templates/`
b.) Harder: upgrade HA's Jinja engine to be based upon v3

I can help with option `a.)`.

### URL

https://www.home-assistant.io/docs/configuration/templating

### Version

2024.1.6

**Comment by frenck** [comment]
> Harder: upgrade HA's Jinja engine to be based upon v3

We use Jinja2 v3 (please note, it is Jinja2 engine, which is currently at version 3; there is no Jinja3 engine).

So nothing to upgrade there.

**Comment by MacDada** [comment]
> please note, it is Jinja2 engine, which is currently at version 3; there is no Jinja3 engine

wow, that's a mess xD
[1](https://github.com/pallets/jinja/issues/752) [2](https://github.com/pallets/jinja/issues/1131)

**Comment by frenck** [comment]
Haha lol xD
