### ISSUE TITLE
lamp and bulb identification

### ISSUE THREAD

**Issue by Yuriel81** [home-assistant/home-assistant.github.io#31279]
### Feedback

The Web Page could do with a better supported devices section. Specifically identifying which Product skews are Lamps or Bulbs.  possibly just a sub header addition to the page. But as it sits now it is very difficult to find the products based on skews alone.

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.2.0

**Comment by turboc1208** [comment]
or at least alphabetize them.
