### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by Waterbrain** [home-assistant/home-assistant.github.io#31288]
### Feedback

It is a great integration, although it would be even better if in addition to the switch for the heater parameter and sensor for the target_sensor parameter, you could add schedule type helpers for programming.

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

### Version

2024.1.6

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
