### ISSUE TITLE
AXIS 225FD cameras autodicovered, but configuration fails

### ISSUE THREAD

**Issue by NaatuMik** [home-assistant/home-assistant.github.io#31290]
### Feedback

I have 3 pcs of old AXIS 225FD cameras in my network. The Axis integration autodiscovers the cameras in the network and offers them to configure. Configuration fails saying "Invalid authentication". I have tried ports 80 and 554, which both sould be ok. The cameras are running firmware version 4.49 which is the latest available for this model.

Finally I was able to connect the cameras with limited functionality using another integration "MJPEG IP Camera" entering MJPEG url in format http://username:password@172.31.200.5/mjpg/video.mjpg.

Is it still possible to get the cameras connected using the Axis integration?

### URL

https://www.home-assistant.io/integrations/axis/

### Version

2024.1.6

**Comment by Kane610** [comment]
Sorry, the integration more or less supports devices from 5.50 and upwards. I will probably never implement support them. 

Its nice that you can use the generic integrations to retrieve the video at least!
