### ISSUE TITLE
Zone mode not correct - showing fan only

### ISSUE THREAD

**Issue by TarkMarman** [home-assistant/home-assistant.github.io#31298]
### Feedback

Mode settings on zone only show fan only and off, despite being set to cool, dry etc. would be ideal if this was Able to control the mode of the unit or turn off the zone

### URL

https://www.home-assistant.io/integrations/airtouch5/

### Version

2024.2.0

**Comment by danzel** [comment]
You will have a climate entity for each zone, and one for the AC unit.
The AC entity controls those settings, each zone just controls if the zone is on or off.
This is how ducted systems work in HA.

@home-assistant close

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by TarkMarman** [comment]
@danzel I have another instance where it appears in this way, hence why I was surprised it was like this upon setting up. This button definitely appears like it's a mode button, otherwise wouldn't it be on/off rather than fan only? This is how it is in other integrations I've used anyway.

**Comment by danzel** [comment]
What integration works that way?
The ones I've seen work the same as this.
