### ISSUE TITLE
No Getting the qr in new tuya authentication 

### ISSUE THREAD

**Issue by Talixme** [home-assistant/home-assistant.github.io#31295]
### Feedback

Im getting a error after put my user, and doesn't show the qr code to log in.

Teh error is: 

Invalid hex color: rgba(25, 25, 25, 0.9)

![215059](https://github.com/home-assistant/home-assistant.io/assets/36339528/5900441c-a801-46f8-abfd-d949af615b0f)

Thanks.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.2.0

**Comment by yshrik** [comment]
I have the same problem! I had to roll back to the previous release. Why was it necessary to switch to user code? Please return the old login option to tuya!

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
