### ISSUE TITLE
Since Google AI Studio is not available in various locations in Europe - add Vertex AI API based integration

### ISSUE THREAD

**Issue by mkotek** [home-assistant/home-assistant.github.io#31297]
### Feedback

Google AI studio is currently not available in Europe (https://ai.google.dev/available_regions), so it would be great if we could get the integration with Gemini Pro model via Vertex AI API - https://cloud.google.com/vertex-ai?hl=pl#build-with-gemini

### URL

https://www.home-assistant.io/integrations/google_generative_ai_conversation/

### Version

2024.2.0

### Additional information

I am happy to provide test project on GCP if needed.

**Comment by tronikos** [comment]
I don't have plans supporting Vertex AI API. You are welcome to send PRs. This feels like a feature request that I believe maintainers want them in the community forum and not in github.

**Comment by tronikos** [comment]
@home-assistant close
