### ISSUE TITLE
City of Austin Utilities Not Providing Any Entities

### ISSUE THREAD

**Issue by Zoriontsu** [home-assistant/home-assistant.github.io#31301]
### Feedback

After adding the Opower integration and successfully login in to my City of Austin Utilities account , the integration simply shows the name of the integration without any entities. 

### URL

https://www.home-assistant.io/integrations/coautilities/

### Version

2024.2.0

### Additional information

![opower](https://github.com/home-assistant/home-assistant.io/assets/22824068/26b2cb99-f57c-4316-8692-1d9c865a5192)

**Comment by tronikos** [comment]
Only utilities that provide forecast data add sensors. You need to be using the statistics, see https://www.home-assistant.io/integrations/opower#energy
