### ISSUE TITLE
Language option missing

### ISSUE THREAD

**Issue by TitoTB** [home-assistant/home-assistant.github.io#31309]
### Feedback

First, thank you for including this integration that we have been waiting for so long.

Bring requires that we select the correct language, otherwise the products appear in German (which should be the default language).

Please include this option in the configuration.

### URL

https://www.home-assistant.io/integrations/bring/

### Version

2024.2.0

**Comment by miaucl** [comment]
Thanks for your feedback, have a look at this issue: https://github.com/home-assistant/core/issues/109866

**Comment by miaucl** [comment]
@home-assistant close
