### ISSUE TITLE
No device or entities

### ISSUE THREAD

**Issue by Bdehaas** [home-assistant/home-assistant.github.io#31304]
### Feedback

I have installed the Volvo on Call, logged in with my Volvo app credentials,live in the Netherlands.
Butt I can’t see the car in Home Assistant , what I,m doing wrong?

### URL

https://www.home-assistant.io/integrations/volvooncall/

### Version

2024.2.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
