### ISSUE TITLE
Language display

### ISSUE THREAD

**Issue by damienthoos** [home-assistant/home-assistant.github.io#31306]
### Feedback

Hi,
I've just tested the integration, and here are 2 things I've noticed:
- I speak French and the list on my iPhone is in French.
In Home Assistant, it's in German, so I'd have to enter the items in German and I don't know German.
- In addition, when I enter items, they are not recognized, they are added with the 1st letter capitalized and they are not sorted (only recognized items are sorted).

Thank you for your work

### URL

https://www.home-assistant.io/integrations/bring/

### Version

2024.2.0

**Comment by frenck** [comment]
Hi there @damienthoos 👋 

It seems like you want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by miaucl** [comment]
Thanks for your feedback, have a look at this issue: https://github.com/home-assistant/core/issues/109866
