### ISSUE TITLE
No units given and no proper explanation of tollerance

### ISSUE THREAD

**Issue by Beenay25** [home-assistant/home-assistant.github.io#31312]
### Feedback

Firstly the documentation doesn't give info on units used. It just says it depends on your settings in the "home assistant unit system". It should state if it uses km or metres (miles or yards if imperial)
Secondly, there is no mention on the page about "tolerance" one of the settings when installing the integration.

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2024.2.0

**Comment by frenck** [comment]
> Firstly the documentation doesn't give info on units used. It just says it depends on your settings in the "home assistant unit system". It should state if it uses km or metres (miles or yards if imperial)

Sensors show the units in the UI...

![image](https://github.com/home-assistant/home-assistant.io/assets/195327/1cb0ed33-1a03-483b-af0c-06a9018dcd59)

You can even change units of sensors in Home Assistant, so, you can config an entity with the unit you prefer. If you would prefer miles on the above sensor, you can do just that.

This is not specific to this integration; this is a generic feature of Home Assistant.

**Comment by Beenay25** [comment]
> > Firstly the documentation doesn't give info on units used. It just says it depends on your settings in the "home assistant unit system". It should state if it uses km or metres (miles or yards if imperial)
> 
> Sensors show the units in the UI...
> 
> ![image](https://private-user-images.githubusercontent.com/195327/303303924-1cb0ed33-1a03-483b-af0c-06a9018dcd59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTA3NjAsIm5iZiI6MTcwNzM5MDQ2MCwicGF0aCI6Ii8xOTUzMjcvMzAzMzAzOTI0LTFjYjBlZDMzLTFhMDMtNDgzYi1hZjBjLTA2YTkwMThkY2Q1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMTA3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTdmOTJiNjFlMTQ1MGYxOTEwMTI5MTQxOTM4NDcxNWJkYjZhNjJlMzllNzU4NTIxZmM5NjY1ZjA3ZDVmNDI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n3XjKagq4p1jD7XYAroo9dprrIdSP9GGXZ2NMBWlEYE)
> 
> You can even change units of sensors in Home Assistant, so, you can config an entity with the unit you prefer. If you would prefer miles on the above sensor, you can do just that.
> 
> This is not specific to this integration; this is a generic feature of Home Assistant.

But it's not shown when you install the integration... when it'd be the most useful.

![image](https://github.com/home-assistant/home-assistant.io/assets/33177033/f05cb02b-f309-4988-bc50-600594d335a4)

And I reiterate that the documentation should show this (as well as details on the tolerance setting.)

**Comment by mib1185** [comment]
The tolerance is in meters (_since under the hood all calculations are done in meters_) and only considered for the calculation of the direction, so if your movement distance (_the distance between two gps measurements_) is lower than the tolerance, it will be ignored.
Means - when you have set a tolerance of 50m and your gps tracker is such sensitive that it updates every 40m, you will never get a direction calculated. An update of the docs will follow soon

**Comment by rjroch** [comment]
> Means - when you have set a tolerance of 50m and your gps tracker is such sensitive that it updates every 40m, you will never get a direction calculated. An update of the docs will follow soon

So, for tolerance, one single distance measurement between two tracker location updates must exceed the tolerance variable for any proximity calculation to be performed? 

Given that multiple trackers with potentially varying update rates can be configured on a single proximity entry, if it's possible might it be useful to consider cumulative movement updates between two stationary states?

For example, consider a single proximity setting including both a mobile phone and a vehicle. The distance moved between updates could vary wildly between these two trackers. In the case of the phone, it should update regularly but each movement may be either a small or large distance depending on whether its user is on foot or in a vehicle. The vehicle might be the same depending on the available tracker and/or traffic flow/speed in its location, or it might be considerably less frequent if the cloud provider rate limits our integrations (like BMW).

**Comment by slovdahl** [comment]
> You can even change units of sensors in Home Assistant, so, you can config an entity with the unit you prefer. If you would prefer miles on the above sensor, you can do just that.

Does this affect automations too? Or will the state of the sensor in automations always be the same (meters) regardless of what unit is configured?

**Comment by slovdahl** [comment]
> The tolerance is in meters (since under the hood all calculations are done in meters) and only considered for the calculation of the direction, so if your movement distance (the distance between two gps measurements) is lower than the tolerance, it will be ignored.
Means - when you have set a tolerance of 50m and your gps tracker is such sensitive that it updates every 40m, you will never get a direction calculated. An update of the docs will follow soon

Getting this added to https://www.home-assistant.io/integrations/proximity or in the HA UI would be really great 🙇

**Comment by ghbaud** [comment]
> You can even change units of sensors in Home Assistant, so, you can config an entity with the unit you prefer. If you would prefer miles on the above sensor, you can do just that.

Just spent 10 minutes trying to figure out how to do that. The only way I was able to figure it out was watching the new video by smart home junkie that just came out this morning. (you need to click on "<_your name_> Distance") Definitely need better documentation for this.
