### ISSUE TITLE
Erratic solar forecasts  

### ISSUE THREAD

**Issue by DominicMcCann** [home-assistant/home-assistant.github.io#31310]
### Feedback

Is there any way to make the solar forecast less "erratic". For example yesterday the forecast for me at 1748h was 9kWh then at 1848h this was reduced to 2.9kWh. But by this time in the afternoon the sun has already set so any forecast is pretty much a totting up of the days PV production.
![image](https://github.com/home-assistant/home-assistant.io/assets/19385803/0707f5ac-1b89-4d0f-a46f-207db338dd30)

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2024.2.0

**Comment by klaasnicolaas** [comment]
This question is better asked in the discord of Forecast.solar or the creator of the API. The integration is nothing more than a conduit for the data it receives.

./Klaas
