### ISSUE TITLE
DataPoint Sunset at The Met Office

### ISSUE THREAD

**Issue by Squelch** [home-assistant/home-assistant.github.io#31328]
### Feedback

The Met Office will be "sunsetting" DataPoint in April. New API registrations for DataPoint are now no longer being accepted. A new service, DataHub, will be its replacement which possibly needs a new registration, and as of recent, a new and different API Key.

The current documentation is therefore out of date. However, changes/re-write of the integration may be required to work with the new services provided by DataHub. A note in the documentation concerning the disruption may be prudent. 

### URL

https://www.home-assistant.io/integrations/metoffice/

### Version

2024.2.0

**Comment by dannytsang** [comment]
This was noted in the [Backward-incompatible changes](https://www.home-assistant.io/blog/2024/02/07/release-20242/#backward-incompatible-changes) in the 2024.2 release notes. It has been reported to the library and requires an update to work.

**Comment by dannytsang** [comment]
Sorry I got that wrong. It's Python compatibility. The issue has been logged with the upstream library: https://github.com/EJEP/datapoint-python/issues/155
