### ISSUE TITLE
Juicenet integration should be marked deprecated

### ISSUE THREAD

**Issue by emilecantin** [home-assistant/home-assistant.github.io#31325]
### Feedback

As seen [here](https://github.com/home-assistant/core/issues/86588), the JuiceNet cloud has been migrated to a new platform which isn't compatible with the integration.

There is a workaround involving running a proxy, but potential buyers should stay away from this EVSE and the integration's page should clearly mention this.

### URL

https://www.home-assistant.io/integrations/juicenet/

### Version

2024.2.0

**Comment by paulcarlucci** [comment]
I was migrated back and the juicenet integration still works for me.  Please don't remove this.

**Comment by niharmehta** [comment]
Also working for me. Please do not remove as it seems for many users, the API is still working.

**Comment by rtw819** [comment]
FYI - Not everyone was converted to the new JuicePass platform, in fact some units/accounts were reverted back to the original JuiceNet interface.

This integration has been working fine for my JuiceBox 40 units for the past couple of years.  Please **do not** remove the integration for those whom which it works!!!

**Comment by emilecantin** [comment]
I've changed the title of the issue. Juicenet seems to have made a comeback so things started working again, but I don't think we can trust it to stay for good as there has been no communication from the company on this. People should certainly not make purchasing decisions based on the existence of this integration (as I did) because Enel proved they can and did break the integration.

**Comment by emilecantin** [comment]
Integration removed in #31631

**Comment by ivanfmartinez** [comment]
> I've changed the title of the issue. Juicenet seems to have made a comeback so things started working again, but I don't think we can trust it to stay for good as there has been no communication from the company on this. People should certainly not make purchasing decisions based on the existence of this integration (as I did) because Enel proved they can and did break the integration.

@emilecantin 

I agree that people should not purchase new devices trusting in this integration, but removing without giving option for the ones that have integration working is not fair.

The information about being deprecated should be put in integration documentation and the removal should be done when it really does not work.

Actually this is the only way to control the current on the juicebox from homeassistant, the proxy that are available only allow to get information from the device without any control option.

**Comment by ivanfmartinez** [comment]
@thecode and @jesserockz that merged the removal on #31631 please consider reverting that until the integration really stop working or we have an alternative to control the  device.

**Comment by klaasnicolaas** [comment]
It will be added again: https://github.com/home-assistant/core/pull/112578

./Klaas
