### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by ipodsync** [home-assistant/home-assistant.github.io#31320]
### Feedback

During setup I'm prompted to scan a QR code, but no QR code is displayed.
![image](https://github.com/home-assistant/home-assistant.io/assets/201184/471358c2-d635-439c-b34c-29a40fca605d)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.2.0

**Comment by frenck** [comment]
Hi there @ipodsync 👋 

It seems like you wanted to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
