### ISSUE TITLE
Thanks and suggestion

### ISSUE THREAD

**Issue by dheijden** [home-assistant/home-assistant.github.io#31321]
### Feedback

First of all, thank you very much for programming the code. Is there a possibility that the lighting switch will also be added to the card? 

### URL

https://www.home-assistant.io/integrations/huum/

### Version

2024.2.0

**Comment by frwickst** [comment]
I will look into this next week (on vacation atm). I don't have a light hooked up myself so might need to do some electrical work first as well to make sure thing work as they should 😊

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
