### ISSUE TITLE
Select room for ecovac to clean

### ISSUE THREAD

**Issue by noelfrost** [home-assistant/home-assistant.github.io#31334]
### Feedback

The instructions does not explain how I tell the vacuum to clean just the lounge room instead of the whole house.  The older installation that used HACS let you select room to clean.

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.2.1

**Comment by cowboysdude** [comment]
Thank you for the migration.  I changed my post because all the sensors created are all still there as are the scripts I wrote and they all work......

**Comment by cowboysdude** [comment]
> ### Feedback
> The instructions does not explain how I tell the vacuum to clean just the lounge room instead of the whole house. The older installation that used HACS let you select room to clean.
> 
> ### URL
> https://www.home-assistant.io/integrations/ecovacs/
> 
> ### Version
> 2024.2.1
> 
> ### Additional information
> _No response_

All of the old sensors should be there and scripts if you have them, if not I may be able to help you....  
Perhaps this will help you...

https://github.com/cowboysdude/Ecovacs-Scripts

**Comment by noelfrost** [comment]
Thankyou.  I managed to get it working again after updating some sensor/entity names.
I now have it working great with the old Deebot advanced UI found https://deebot.readthedocs.io/integrations/home-assistant/examples/ui/advanced/
