### ISSUE TITLE
Current Power

### ISSUE THREAD

**Issue by nublet** [home-assistant/home-assistant.github.io#31337]
### Feedback

It would be useful to have access to the Current Power for plugs (P110 as an example) for automation purposes.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.2.1

### Additional information

This information is available in some of the integrations available via HACS, but would prefer to use this one.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
