### ISSUE TITLE
BMW Connected Drive reporting range and mileage in KM

### ISSUE THREAD

**Issue by mlgboy** [home-assistant/home-assistant.github.io#31336]
### Feedback

isit possible to configure sensors to display in miles rather than KM?

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2024.2.1

**Comment by rikroe** [comment]
Unfortunately, this is not possible at the moment. It is tracked in https://github.com/home-assistant/core/issues/106195.

Also, this repository (home-assistant/home-assistant.io) is only for issues on the documentation. For actual functionality, you have to open issues in home-assistant/core.

**Comment by rikroe** [comment]
@home-assistant close
