### ISSUE TITLE
Govee Light Local Integration not found

### ISSUE THREAD

**Issue by YanisKyr** [home-assistant/home-assistant.github.io#31335]
### Feedback

After following the link from the integration's page, I am getting this error:
![image](https://github.com/home-assistant/home-assistant.io/assets/35373257/eae97dce-4ce0-4a36-8099-f80c8d9cc6a5)

But I am running the latest version:
![image](https://github.com/home-assistant/home-assistant.io/assets/35373257/0ad050d2-5cc5-4d46-8786-50e520fb0a42)

Even searching for it, it;s not there:
![image](https://github.com/home-assistant/home-assistant.io/assets/35373257/4e85dcff-7aef-40ca-b090-7a7ea12ffa7a)

Any ideas 

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.2.0

**Comment by klaasnicolaas** [comment]
Click on Govee then you will see it 😉 

@frenck maybe we should do something in the brands repo with Govee

**Comment by YanisKyr** [comment]
> Click on Govee then you will see it 😉

This is what I see after clicking on Govee from my last screenshot:
![image](https://github.com/home-assistant/home-assistant.io/assets/35373257/fd35de4d-7298-49a7-8cd2-9ad8592731ad)

**Comment by Galorhallen** [comment]
That looks like a custom integration. I think you have to remove the custom govee integration

**Comment by Galorhallen** [comment]
> @frenck maybe we should do something in the brands repo with Govee

I was going to open a PR for that. I should be able to do it tomorrow.

**Comment by YanisKyr** [comment]
> That looks like a custom integration. I think you have to remove the custom govee integration

That was it actually.. I had to **remove the device, restart, remove the HACS integration**, and then it worked.

Thanks for pointing me in the right direction!

**Comment by jaegerschnitzel** [comment]
Thanks, had the same problem :)
