### ISSUE TITLE
Checking/ editing call frequency Accuweather-API

### ISSUE THREAD

**Issue by frederikvoGIT** [home-assistant/home-assistant.github.io#31344]
### Feedback

The number of calls of a limited trial account is 50 calls per day. 
Where can i check and edit the call frequency? In order to stay under this number of 50 calls? (I plan to set this frequency 15minutes so it calls 48 times per day) 

### URL

https://www.home-assistant.io/integrations/accuweather/

### Version

2024.2.1

**Comment by bieniu** [comment]
When the weather forecast is not enabled, the data is updated every 40 minutes, with the forecast enabled every 80 minutes. If you want to enable the weather forecast, information about it will be displayed.
You cannot change the frequency of data updates. You can only disable completely automatic data updating and update the data using `update_entity` service.

**Comment by frederikvoGIT** [comment]
Ok, thanks.
Maybe usefull info to include on the [Accuweatherpage](https://www.home-assistant.io/integrations/accuweather/) ?

**Comment by bieniu** [comment]
As always, PR is most welcome.
