### ISSUE TITLE
ZHA file provider ota changes

### ISSUE THREAD

**Issue by paoloach** [home-assistant/home-assistant.github.io#31349]
### Feedback

From the version 2024.2.x the zigpy library version used (the 0.62.3) disabled the file provider OTA as
https://github.com/zigpy/zigpy/pull/1337
The only way to re-enable is to add the key
` allow_file_providers: "I understand I can *destroy* my devices by enabling OTA updates from files. Some OTA updates can be mistakenly applied to the wrong device, breaking it. I am consciously using this at my own risk."`

under
zha:
  zigpy_config:
    ota:

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2024.2.x

**Comment by puddly** [comment]
This is correct and not a bug.

**Comment by paoloach** [comment]
I don't understand: it is correct that the documentation do not report how to enable the OTA for this case ?

**Comment by puddly** [comment]
Yes. The file provider is dangerous, as per the message, and people have permanently destroyed multiple devices by using it. It will be re-enabled in the next release in a different form.
