### ISSUE TITLE
where do you actually put the templates?

### ISSUE THREAD

**Issue by wjcarpenter** [home-assistant/home-assistant.github.io#31342]
### Feedback

The docs for templating say that there is a template editor in the GUI. That's just for local testing. But I could not find a place that says how/where you actually create a template. I happen to know that you need to do it via file editing. That should be spelled out, and this is the natural page for that description.

### URL

https://www.home-assistant.io/docs/configuration/templating/

### Version

2024.2.1

**Comment by klaasnicolaas** [comment]
https://my.home-assistant.io/redirect/developer_template/

./Klaas

**Comment by wjcarpenter** [comment]
I don't understand what you are trying to tell me, @klaasnicolaas. I know about the template editor page in the GUI, but that page doesn't let you save the template anywhere. If you actually want to create a template and use it somewhere, you have to edit a YAML file. Or have I missed something in the GUI?

**Comment by klaasnicolaas** [comment]
Sorry, I assumed you couldn't find the template editor. But you don't have the option to save this from developer tools, because you can use "templating" in different ways and places. In automations, scripts, template sensors (and covers, fan, switch etc.) etc.

I will reopen the issue and ask @c0ffeeca7 what she thinks about it.

./Klaas

**Comment by wjcarpenter** [comment]
(No problem about the misunderstanding.)

I'm not necessarily suggesting that the template editor page should have a "save" button. I'm just saying that it's not clear from the documentation how you actually do save a template and have HA know about it. I think I originally found out about it in some forum posting. So, this is feedback about the docs rather than the GUI.

**Comment by klaasnicolaas** [comment]
As I mentioned earlier, we are talking about "templating" on this page and there are several places where you can apply this and depending on what you are doing, the place where you want to save it may be different.

./Klaas

**Comment by frenck** [comment]
> But I could not find a place that says how/where you actually create a template.

There are tons of places. It is a concept that can be used across the board (when it is indicated an text field can accept a template).

Your question is thus best answered as: Anywhere templates are accepted.

**Comment by wjcarpenter** [comment]
I think my question was a little unclear, but in getting ready to clarify it I learned something new about HA today. 

Until now, I had never noticed that there was a Helper type "Template" for creating templated sensors and binary sensors. The page https://www.home-assistant.io/integrations/template/ mentions the "template" integration, but it's a peculiar selection from the "Add integration" menu since it doesn't then show up on the integrations page. Instead, it takes you to the helpers page. Except for that oddness, that page is pretty clear on how to create one of those sensor templates by going directly to the helpers page.

I'm not sure if I ever read that particular documentation page before, though I have been using templated sensors, including some triggered sensors, for a year or two. I was mostly following examples and advice from community forum  postings. I've been to the page https://www.home-assistant.io/docs/configuration/templating/ many times. I still think it's helpful to add a sentence to the effect of what you've said ("how to create a template depends on how the template is being used, for example...."). But I leave that judgment to the HA team.
