### ISSUE TITLE
The Lutron RadioRA 2 integration also support Lutron Homeworks QS

### ISSUE THREAD

**Issue by txwindsurfer** [home-assistant/home-assistant.github.io#31340]
### Feedback

I have been using this integration for my Homeworks QS system for many years.  It works correctly for lights, but I cannot say what other device types will work.  I suspect that HW QS and RadioRA 2 have similar protocols and most devices working in the RadioRA 2 integration will work on HW QS systems.  The other Lutron Homeworks integration only supports the older 4 & 8 Homeworks systems and not QS so if there are other people like me who own a QS system, this addition to the documentation could be very useful.

### URL

https://www.home-assistant.io/integrations/lutron/

### Version

2024.2.1

**Comment by wilburCforce** [comment]
Seems like a reasonable mention to add to the docs.  I'll include it in the next update I do.
