### ISSUE TITLE
docker network host does not work for hosts other than linux

### ISSUE THREAD

**Issue by Aeonos** [home-assistant/home-assistant.github.io#31347]
### Feedback

In the script to run the docker image there is the part
`--network=host`
which only works for linux hosts https://docs.docker.com/network/drivers/host/
Therefore it is necessary to use the line
`-p 8123:8123`

This applies for the docker run section as well as to the docker compose.yml section

### URL

https://www.home-assistant.io/installation/linux/

### Version

2024.2.1

**Comment by frenck** [comment]
We don't support other operating systems for running the container for that reason.

Home Assistant must run on the host network to function as designed.

The documentation you linked applies to Linux, we don't have documentation on how to use our containers for other operating systems (as they aren't supported).

../Frenck
