### ISSUE TITLE
Areas with multiple channels and joins. State sync issues

### ISSUE THREAD

**Issue by aphilgr1** [home-assistant/home-assistant.github.io#31345]
### Feedback

I spent around 30 hours testing the Home Assistant integration for compatibility with my 2009-2010 Philips Dynalite system. This testing is part of a hotel system revamp project, where HA will replace the 15-year-old AMX automation. I run HAOS centrally on a virtual server and utilize a PDEG per room, creating separate hosts for each room.

**Observations:**

**Single Channel Performance:** Areas controlled by a single channel operate smoothly, supporting both ramping and preset functionalities without issues.

**Multi-Channel Complexities:** Challenges arise in multi-channel areas, especially when issuing command to those areas for all channels with joins. While dimming through Home Assistant (HA) executes flawlessly, issues manifest when using Dynalite controls for dimming and ramping. Specifically: 
- Initiating a change from 0 to 100% brightness with a one-second ramp results in a Dynet command that checks and replies with each channel’s status within the area. Unfortunately, during ramp-up, the 
brightness level is inaccurately registered at approximately 15-20%, causing the HA dimmer to display a nearly empty state, despite the lights being fully on. A similar discrepancy occurs when dimming, with the lights off but the dimmer indicating nearly full brightness. This reverse synchronization persists even when the ramp duration is reduced to 150 milliseconds, albeit with slight improvements.
- At times, Dynalite button presses fail to elicit any response. Repeated pressing can overwhelm the system with commands, leading to significant operational delays and instability.

**Zero Ramping for Accurate State Feedback:** Setting the area preset ramping to zero, essentially turning it into a switch, ensures accurate state feedback to HA.

**Adaptations and Solutions:**

**1. Adjusting Button Ramping:** By programming all preset to all channels buttons to zero ramping, I eliminated the smooth lighting transition triggered by button presses, which, in turn, ensured accurate state representation in HA, despite slight delays between channel responses.

**2. Area Division for Efficiency:** Dividing larger areas into smaller segments significantly reduced the volume of simultaneous commands, enhancing system responsiveness and synchronization. I found that limiting areas to four or five channels minimized delays and improved overall system stability.

**3. Channel Ordering:** The sequence in which channels are organized within an area plays a crucial role in system performance. Strategically positioning a few switch channels at the beginning of the sequence allows their commands to be processed first, thereby enabling dimmers to achieve their final state before their status is reported. Although shorter ramping times can yield better accuracy, I opted for zero ramping to ensure complete reliability.

**4. Channel Reordering Limitations:** Modifying the sequence of channels after their creation does not influence their operational order within the system; it remembers the initial configuration and processes commands accordingly. For example, if dimmers initially assigned to Channels 1 and 2 are moved to Channels 3 and 4, with switches taking their place, the system still processes commands in the order of C3, C4, C1, and C2. To effectively reorganize channels, one must recreate the area from scratch, ensuring channels are added in the desired sequence from the outset. Tip: Place the all related channels to unassigned area C1 first, to make sure they go to the correct order

**Suggestion for Developers:** Implement a solution where Home Assistant dimmers populate based on the target level, followed by a brief polling command to confirm the actual level, ensuring synchronization and accurate state representation.

### URL

https://www.home-assistant.io/integrations/dynalite/

### Version

2024.2.1

**Comment by frenck** [comment]
Hi there @aphilgr1 👋 

Thanks for your extensive post, but I feel like it is in the wrong place. You have submitted documentation feedback, but I don't see how this fits in there?

../Frenck

**Comment by aphilgr1** [comment]
I thought that levels not populating correctly in HA, is an issue. How about the last paragraph? If the state of the lights in HA are presented by the Target level instead of the actual level? That would have been a nice workaround. Maybe, a polling command could follow for verification. Is this possible to implement?

**Comment by ziv1234** [comment]
Hi. I will take a look this week

**Comment by ziv1234** [comment]
Ok. I now understand frenck’s comment. This thread is for documentation issues. You have to open this issue in home assistant core in GitHub.  I will take a look anyway, but can you please reopen so the discussion will be in the correct place?

**Comment by aphilgr1** [comment]
Sure! I ll try to figure it out! ;) Is this the right link?

https://github.com/home-assistant/core/issues/new/choose

**Comment by aphilgr1** [comment]
Dear ziv1234,

Did you take a look at it? In about one month, the hotel opens, and I must decide which way to go with my Dynalite installation. It would be great to see something functioning properly, according to our special needs

Cheers,

**Comment by klaasnicolaas** [comment]
Please continue this conversation in a core issue if there are problems with the integration, otherwise the community forum is the appropriate place to discuss the integration.

./Klaas

**Comment by ziv1234** [comment]
agree. please open it in the core and i will continue the discussion there.
