### ISSUE TITLE
Wolf Plugin geht nach HA Core Update nun garnicht mehr.

### ISSUE THREAD

**Issue by wartungsmonteur** [home-assistant/home-assistant.github.io#31354]
### Feedback

Wolf Plugin nach HA Update nicht mehr installierbar

### URL

https://www.home-assistant.io/integrations/wolflink/

### Version

2024.2.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
