### ISSUE TITLE
Blank QR code screen

### ISSUE THREAD

**Issue by Daytona3522** [home-assistant/home-assistant.github.io#31356]
### Feedback

When I enter the code from the app into the TUYA integration, I get a blank square instead of a QR code. 
It's a bit hard to scan.
![2024-02-11_03-22-33](https://github.com/home-assistant/home-assistant.io/assets/109828862/1ff65654-3ef3-4543-872b-756b5fffda12)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.2.1

**Comment by klaasnicolaas** [comment]
Please set the default theme and try again.

./Klaas

**Comment by Daytona3522** [comment]
Default Theme??
Can you elaborate on that??
How, where, what?

Thank you,

**Comment by Daytona3522** [comment]
I got it to work Klaas,

Thank you!!
