### ISSUE TITLE
Add support for H6088 which has LAN Control + scene and segment control?

### ISSUE THREAD

**Issue by talormanda** [home-assistant/home-assistant.github.io#31359]
### Feedback

H6088 is the next version of H6087 which IS supported. It has LAN Control and when I add it to `govee lights local`, all I get are the basic on/off.

https://us.govee.com/products/govee-rgbic-cube-wall-sconces

Also - are there any plans for scene support and segment support? The `Govee to MQTT Bridge` add-on has control over all the segments of my H6088 and H6047, but I can't use that with `govee lights local` because it doesn't allow both to run at the same time.

![image](https://github.com/home-assistant/home-assistant.io/assets/10092964/025b7ebf-3ac3-42a7-8d10-5acf88e8a238)

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.2.1

**Comment by Galorhallen** [comment]
Hi @talormanda,
 do you mind opening here https://github.com/Galorhallen/govee-local-api/issues the request to support the H6088?

> Also - are there any plans for scene support and segment support?

My understanding of Govee2Mqtt is that it uses both local api and ble to connect to devices, while this integration only leverages local APIs that don't support neither scenes nor segments.
So I can't make any promises on their support in the near future.

**Comment by talormanda** [comment]
> H6088 is the next version of H6087 which IS supported. It has LAN Control and when I add it to `govee lights local`, all I get are the basic on/off.
> 
> https://us.govee.com/products/govee-rgbic-cube-wall-sconces

Got it for you: https://github.com/Galorhallen/govee-local-api/issues/8

Also, thanks for the detailed explanation. It's too bad we can't use all the add-ons and have to pick one or the other.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests. Please continue the conversation in the upstream pypi package repository 😉 

Thanks! 👍
