### ISSUE TITLE
Unable to find / use when 

### ISSUE THREAD

**Issue by talormanda** [home-assistant/home-assistant.github.io#31358]
### Feedback

1. I was unable to find `govee lights local` when I had the `hacs-govee` integration installed - https://github.com/LaggAt/hacs-govee

2. After removing `hacs-govee`, I finally was able to find `govee lights local` in the integration list, but I was presented with an error when trying to add it: `Unknown error occurred`. So I went and disabled my `Govee to MQTT Bridge` add-on, and then it let me add `govee lights local`. - https://github.com/wez/govee2mqtt

My question is, is this intentional that we must remove all of these things before we can use this official integration? Some of these other integrations have way better features, like govee2mqtt can control the segments of my lights.

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.2.1

### Additional information

https://github.com/LaggAt/hacs-govee
https://github.com/wez/govee2mqtt

**Comment by Galorhallen** [comment]
Hi @talormanda ,

> I was unable to find govee lights local when I had the hacs-govee integration installed

This has been addressed here https://github.com/home-assistant/core/issues/109921. The issue is not strictly related to Govee Light local.

> After removing hacs-govee, I finally was able to find govee lights local in the integration list, but I was presented with an error when trying to add it: Unknown error occurred. So I went and disabled my Govee to MQTT Bridge add-on, and then it let me add govee lights local. - https://github.com/wez/govee2mqtt

Both integrations require to bind to port 4002 to receive status update from Govee lights, that's how the Govee protocol works and the port can't be changed. 

> My question is, is this intentional

If by intentional you mean to prevent the use of another integration (HACS or not) the answer is obviously no.
Usually only one software can bind to a specific port on a specific protocol, in this case UDP port 4002 (There are exceptions to this, but this is not the case).

**Comment by talormanda** [comment]
> Hi @talormanda ,
> 
> > I was unable to find govee lights local when I had the hacs-govee integration installed
> 
> This has been addressed here [home-assistant/core#109921](https://github.com/home-assistant/core/issues/109921). The issue is not strictly related to Govee Light local.
> 
> > After removing hacs-govee, I finally was able to find govee lights local in the integration list, but I was presented with an error when trying to add it: Unknown error occurred. So I went and disabled my Govee to MQTT Bridge add-on, and then it let me add govee lights local. - https://github.com/wez/govee2mqtt
> 
> Both integrations require to bind to port 4002 to receive status update from Govee lights, that's how the Govee protocol works and the port can't be changed.
> 
> > My question is, is this intentional
> 
> If by intentional you mean to prevent the use of another integration (HACS or not) the answer is obviously no. Usually only one software can bind to a specific port on a specific protocol, in this case UDP port 4002 (There are exceptions to this, but this is not the case).

Thanks for the detailed answer. Is it possible we could get something like this added to the official documentation so users are aware that adding third party add-ons for govee will cause problems like the one I am facing? Might save you some time / posts on this github page.

**Comment by Galorhallen** [comment]
> Is it possible we could get something like this added to the official documentation so users are aware that adding third party add-ons for govee will cause problems like the one I am facing?

It make sense
