### ISSUE TITLE
Cannot choose mode Fan only for my Midea CCM15

### ISSUE THREAD

**Issue by arturyak** [home-assistant/home-assistant.github.io#31362]
### Feedback

Since I switched from ccm15 module to internal CCM15 integration I cannot choose mode "Fan Only". If I try to just switch on the fan speed to "low" - Main mode always goes to "Cool". All my previuos Automations went to hell since they were switching between "Cool" and "Fan only".
If "Dry" is the "Fan Only" - please change the name in accordance with Original name from Midea/MDV
I have MDV/Midea V5x system MDV5-X500W with CCM15 module.
I attached screenshots from my HA and CCM15 web Interface.

### URL

https://www.home-assistant.io/integrations/ccm15/

### Version

2024.1.3

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/109509698/5d6ce460-0cc7-49d8-b8cd-45c75b6dca4b)
![image](https://github.com/home-assistant/home-assistant.io/assets/109509698/0e151a44-e677-4a7b-b0d2-641545cc8c7b)

**Comment by arturyak** [comment]
If I choose "Dry" anyway it goes to "Cool"
![image](https://github.com/home-assistant/home-assistant.io/assets/109509698/9228ef6c-6b1e-4413-89d7-b92786bf8a1c)

**Comment by arturyak** [comment]
[climate.py.txt](https://github.com/home-assistant/home-assistant.io/files/14231810/climate.py.txt)
This side integration was working perfectly for me.

**Comment by arturyak** [comment]
In my old integration I found a list of modes:
CONST_STATE_CMD_MAP = {HVAC_MODE_COOL:0, HVAC_MODE_HEAT:1, HVAC_MODE_DRY:2, HVAC_MODE_FAN_ONLY:3, HVAC_MODE_OFF:4, HVAC_MODE_AUTO:5}

In the new one - FAN_ONLY mode is apsent in climate.py:
    _attr_hvac_modes = [
        HVACMode.OFF,
        HVACMode.HEAT,
        HVACMode.COOL,
        HVACMode.DRY,
        HVACMode.AUTO,
    ]
But I see that constants are defined well in const.py:

CONST_STATE_CMD_MAP = {
    HVACMode.COOL: 0,
    HVACMode.HEAT: 1,
    HVACMode.DRY: 2,
    HVACMode.FAN_ONLY: 3,
    HVACMode.OFF: 4,
    HVACMode.AUTO: 5,
}

**Comment by arturyak** [comment]
Great. I fixes that. But please incorporate that in main stream as well. Just add the missed mode to the list of modes in climate.py like below:
    _attr_hvac_modes = [
        HVACMode.OFF,
        HVACMode.HEAT,
        HVACMode.COOL,
        HVACMode.DRY,
        **HVACMode.FAN_ONLY,**
        HVACMode.AUTO,
    ]

**Comment by klaasnicolaas** [comment]
Please note that this repository is for documentation, this issue is something for core.

./Klaas

**Comment by arturyak** [comment]
ok, can you pls forward that to maintainer? or guide me where to open this ticket for issue to be fixed?

**Comment by arturyak** [comment]
Ok, I will open the ticket in the Core section. I didn't get it properly. My mistake. Thank you.
