### ISSUE TITLE
After logging in you get the message “Connection failed”.

### ISSUE THREAD

**Issue by JS-DE-Tech** [home-assistant/home-assistant.github.io#31364]
### Feedback

After logging in you get the message “Connection failed”. I tried deleting the device in the web portal and then adding it again, but without success.

### URL

https://www.home-assistant.io/integrations/aseko_pool_live/

### Version

2024.2.1

### Additional information

<img width="216" alt="Screenshot 2024-02-11 132635" src="https://github.com/home-assistant/home-assistant.io/assets/159697570/cbfc7c97-e581-4c2f-9210-def85a8b22c2">

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
