### ISSUE TITLE
Ip address of inverter is changed

### ISSUE THREAD

**Issue by bertarends** [home-assistant/home-assistant.github.io#31361]
### Feedback

When the IP-address of the inverter is changed, which can happen after a reconfiguration in your network, the integration doesn't work anymore. It can be simple repaired by going to the integration page, remove the device and add it again with the new IP-address. I think it is good to add this to the documentation.

### URL

https://www.home-assistant.io/integrations/zeversolar/

### Version

2024.2.1

**Comment by klaasnicolaas** [comment]
This applies not only to this integration, but to many integrations. I personally believe that we do not need to explicitly mention this in the docs.

./Klaas
