### ISSUE TITLE
Suggesting an addition paragraph to documentation

### ISSUE THREAD

**Issue by basetoad** [home-assistant/home-assistant.github.io#31378]
### Feedback

_After ...._
Prerequisites
You need to have the Tuya Smart or Smart Life app installed, with an account created and at least one device added to that account.

You will need your User Code. You can find this code in the Smart Life app or Tuya Smart app in Settings > Account and Security screen, and enter the code shown on the User Code field.

Please note, that the user code is case sensitive, please be sure to enter it exactly as shown in the app.

_Add ..._

You will be presented with a QR code to scan with the Tuya app. In the app, use the '+' icon on the 'all devices' page to get the option to 'scan'

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.2.1

**Comment by sahmeepee** [comment]
This instruction helps a bit because I struggled to find the scan option, but it doesn't explain how you can scan a qrcode in the app when it's  within the home assistant app and not on a physical object. Does this really need two devices? 

Also, on the bit about the user code, you can hold down your user code in the Tuya app and it will copy it to your clipboard to save needing to do case-sensitive typing.

**Comment by basetoad** [comment]
Yes sahmeepee. Rather than tagging the extra sentence to the end of that section, I should have requested the following wording change
----------------------
You need to have the Tuya Smart or Smart Life app installed, with an account created and at least one device added to that account.

You will need your User Code. 
HA will provide a QR code that you need to scan either with the Smart Life app or Tuya Smart app 
Open the app and use the '+' icon on the 'all devices' page to get the option to 'scan' and then enter the code shown on the User Code field.

Please note, that the user code is case sensitive, please be sure to enter it exactly as shown in the app. 
If you are using HA and Tuya on the same device you can copy and paste the User Code.

**Comment by akirad0e** [comment]
Where is everyone getting this prompt for QR codes? I had it all working for years then it stopped, now when I've removed the integration and add it again, it just asks me for the same IoT access codes etc, nothing about a QR code, and of course, it doesn't work.

**Comment by basetoad** [comment]
> Where is everyone getting this prompt for QR codes? I had it all working for years then it stopped, now when I've removed the integration and add it again, it just asks me for the same IoT access codes etc, nothing about a QR code, and of course, it doesn't work.

Since the original request to update the documentation, the Tuya app has changed and now provides the user code in the app directly. Previously there was a need to link the Integration and the app and the QR code did that. The request to update the document has been met, and the updated document accurately reflects the prerequisites of the integration.

**Comment by basetoad** [comment]
This request for update has been completed. Changes in the Prerequisites now reflect the process that is needed with the latest version of the Tuya app. 
Thanks

**Comment by akirad0e** [comment]
> > Where is everyone getting this prompt for QR codes? I had it all working for years then it stopped, now when I've removed the integration and add it again, it just asks me for the same IoT access codes etc, nothing about a QR code, and of course, it doesn't work.
> 
> Since the original request to update the documentation, the Tuya app has changed and now provides the user code in the app directly. Previously there was a need to link the Integration and the app and the QR code did that. The request to update the document has been met, and the updated document accurately reflects the prerequisites of the integration.

My HA was horribly out of date.  After updating it, removing and reinstalling the integration, it prompted me for the User ID etc.

Everything is back up and running, thank you!

**Comment by basetoad** [comment]
Glad to hear you have been successful.
