### ISSUE TITLE
Failed to load.

### ISSUE THREAD

**Issue by videojedi** [home-assistant/home-assistant.github.io#31374]
### Feedback

I get this error when trying to add the integration

> Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

### URL

https://www.home-assistant.io/integrations/metoffice/

### Version

2024.2.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
