### ISSUE TITLE
no lights found

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/home-assistant.github.io#31376]
### Feedback

I have a H6061 Hexa and two H6076 floor lamps on my primary wireless network.  When I try installing the integration, it prompts me to start the setup.  It spins for a couple of seconds before returning with an error "No devices found on the network". The lights are on the primary wireless network, and are turned on with LAN control enabled.  

The only thing possibly unique about this is I have home assistant running in a proxmox VM under the standard HAOS install with the latest updates as of FEB 11 2024.

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.2.1

### Additional information

![7C8AAC39-104F-412D-BBD2-2A5A17C5F45E_4_5005_c](https://github.com/home-assistant/home-assistant.io/assets/1900627/6561fb8c-2cb6-44e7-864b-8efc5d9867a9)

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
