### ISSUE TITLE
Home Assistant is running in recovery mode

### ISSUE THREAD

**Issue by jake5253** [home-assistant/home-assistant.github.io#31387]
### Feedback

Please, add something to the [Configuration/Troubleshooting](https://www.home-assistant.io/docs/configuration/troubleshooting/) section that demonstrates how to access the *actual* system.
I was working on configuration.yaml changes and something came up and I had to leave, immediately, when I came back almost a day later, i found that my HA had reset due to a power disruption and, because of a configuration.yaml change that went unfixed (but saved). I was stuck in "recovery mode" -- the worst part, recovery mode was using a fallback configuration.yaml. At this point, I thought was entire setup would have to be redone since my last backup, which, admittedly was many changes ago. After searching and searching and more searching, I FINALLY found [I'm Locked Out](https://www.home-assistant.io/docs/locked_out/) which doesn't even seem to mention anything about Recovery Mode (nor does Configuration/Troubleshooting in fairness).  As I was scrolling the Locked Out page, a command there caught my attention.  There in the section "TO RESET A USER’S PASSWORD, VIA THE CONTAINER COMMAND LINE", the golden ticket.

docker exec -it homeassistant bash

Once in bash inside the docker container, in /config -- which is what all the error messages say -- configuration.yaml.  I forgot a freakin double quote.  I spent probably 5 hours trying to fix a missing double quote. Please, for dumbasses like me, add a section to Configuration/Troubleshooting about Recovery Mode, with a special note about that docker command.  Please!!!

Thanks.

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2024.2.1

**Comment by c0ffeeca7** [comment]
`I was working on configuration.yaml changes and something came up `
- How do you edit configuration files? What did you use, where do you access those? I don't quite understand that from the description above.

The reason I'm asking: When I'm in recovery mode, I can still open and edit the file using VSCode
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/1a38a3a0-049b-42c9-83bd-abe959dccc2f)

**Comment by klaasnicolaas** [comment]
Home Assistant being in recovery mode and being locked out of Home Assistant are 2 different things 🤔 

It is a bit unclear to us what exactly happened, one moment you are apparently in recovery mode. Then it should (as already indicated by @c0ffeeca7) be possible to adjust your configuration.yaml and thus recover from errors. But apparently you were also locked out of Home Assistant and had to reset your password? Or you could no longer access the frontend?

**Comment by jake5253** [comment]
> `I was working on configuration.yaml changes and something came up `
> 
> * How do you edit configuration files? What did you use, where do you access those? I don't quite understand that from the description above.
> 
> The reason I'm asking: When I'm in recovery mode, I can still open and edit the file using VSCode ![image](https://private-user-images.githubusercontent.com/38767475/304743227-1a38a3a0-049b-42c9-83bd-abe959dccc2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MzA2NDYsIm5iZiI6MTcwNzkzMDM0NiwicGF0aCI6Ii8zODc2NzQ3NS8zMDQ3NDMyMjctMWEzOGEzYTAtMDQ5Yi00MmM5LTgzYmQtYWJlOTU5ZGNjYzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE3MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNGZkNTUyNzA3ZmJiODFiNGMyYzBkZTM3YzQ1MzJlMjhjZTVkNWQ0N2ZlZjNjZmI4NzdiNGEwZTM2ZTRjZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-9eXRsp325YzN7m7WAMZDgCQc48Ra8LVZyxR_2wdrg)

I was using File Editor add-on.

> Home Assistant being in recovery mode and being locked out of Home Assistant are 2 different things 🤔
> 
> It is a bit unclear to us what exactly happened, one moment you are apparently in recovery mode. Then it should (as already indicated by @c0ffeeca7) be possible to adjust your configuration.yaml and thus recover from errors. But apparently you were also locked out of Home Assistant and had to reset your password? Or you could no longer access the frontend?

I could access the front-end, but it seemed to be some sort of a fallback configuration? I'm not sure. I was in recovery mode, according to the front-end -- i had exactly the same error as show in the screenshot above by @c0ffeeca7. I found the solution, finally, in the documentation section about being locked out. There wasn't anything in the configuration section about "recovery mode" or this fallback configuration that seems to have manifested, so i went searching elsewhere -- in an attempt to locate *my* configuration.yaml, instead of the fallback yaml which was now being displayed in File Editor.  I did not need to change my password, and did not change my password. The literal topic heading "I'm locked out" vaguely described by situation, so i went there.  Sorry for being unclear.

**Comment by jake5253** [comment]
I feel like i'm possibly still being unclear. When I accessed the dashboard, which at the time was stating I was in recovery mode, I was able to access configuration.yaml through the File Editor add-on, but it was not the same configuration.yaml I was expecting. The one shown there was essentially the boilerplate -- the "I just installed Home Assistant", "blank" configuration.yaml.  I'm not sure why it decided to use an empty config; the instance is fairly new but it has most definitely been started, and restarted, many times successfully with configuration changes present.

**Comment by c0ffeeca7** [comment]
don't be sorry, describing an issue is hard.
Now I understand. Thank you for the clarification!

**Comment by jake5253** [comment]
> Thank you for the clarification!

Thank you!  I looked at the proposed changes, and that's definitely better.  I'm not sure what happened to my installation. I perhaps should have mentioned I'm using a debian installation (armbian on a Banana Pi M5, to be specific) with a "supervised installation", so I'm probably a corner-case for what happened, and that possibly also is the reason for the odd, empty configuration.yaml in the File Editor add-on, so I'm not sure if it's truly necessary (or appropriate) to add the "docker exec -it homeassistant bash" part to the recommended methods of repair, but in my case, that was ultimately THE command that allowed me to access my broken configuration.yaml.
Thanks again.

**Comment by c0ffeeca7** [comment]
closing this as fixed by #31427
