### ISSUE TITLE
Not working with Bring! integrated Google authentication

### ISSUE THREAD

**Issue by intuitiv-de** [home-assistant/home-assistant.github.io#31384]
### Feedback

I'm using Bring! with integrated Google authentication. The integration authentication fails using my Google account credentials.

### URL

https://www.home-assistant.io/integrations/bring/

### Version

2024.2.1

**Comment by miaucl** [comment]
Hello @intuitiv-de ,

That is unfortunate, but as this integration is based on a reversed engineered unofficial library, not all features are available the present day. for the time being it is not planned to integrated anything else besides `email` / `password` login.

Anyway, if you want to use the full potential of the integration, I recommend **not** using your personal account but a bot account, allowing you to get notifications on your personal account on changes as mentioned here: https://www.home-assistant.io/integrations/bring/.

**Comment by intuitiv-de** [comment]
Thanks a lot. A Bot-Account is great having just one list of Bring! on the display.
Adding items is working great in both directions (HA <-> Bring!).
Great stuff! Thank you!
