### ISSUE TITLE
Welcome new integration

### ISSUE THREAD

**Issue by pisabell2** [home-assistant/home-assistant.github.io#31395]
### Feedback

As the ownner of a TechnoVE 48 amp charging station, I salute the arrival of the TechnoVE integration.

I see that for the moment, only sensors are bein provided. Is there any plan to extend the integration so as to allow some control feature from the HA side?

The one functionality I am y=thinking about is the ability to automatically deactivate the TechnoVE station during the winter Hydro-Quebec "peak" periods. Since these peak time are already available to HA through the HydroQC addon, all would be really needed is making available a turn-off switch.

### URL

https://www.home-assistant.io/integrations/technove/

### Version

2024.2.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck

**Comment by Moustachauve** [comment]
As Frenck mentioned, this is not the right place for this kind of question but yes, more features including controlling the charge are coming up!

**Comment by pisabell2** [comment]
OK, I will be following, thanks a lot!
