### ISSUE TITLE
Not obvious what binary sensor to use for doorbell button presses

### ISSUE THREAD

**Issue by alexschneider** [home-assistant/home-assistant.github.io#31392]
### Feedback

I had to [search through the issues](https://github.com/home-assistant/core/issues/97458) to find out that the Visitor Sensor is supposed to be used to register doorbell button presses. It's not mentioned anywhere on the documentation page and is not intuitive to me. Ideally the documentation should be updated to indicate that "visitor" means the button is pressed. 

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.2.1

**Comment by starkillerOG** [comment]
I made a PR to clearify the docs: https://github.com/home-assistant/home-assistant.io/pull/31493
Thanks for the feedback!

**Comment by starkillerOG** [comment]
This was done because the Reolink app/client uses "Visitor" to indicate a doorbell press and look through the recordings.
