### ISSUE TITLE
How to make it work for docker installation ?

### ISSUE THREAD

**Issue by nicolascornet** [home-assistant/home-assistant.github.io#31403]
### Feedback

Hi
I'm using HA v2024.2.1 in a docker container.
I would like to know if I can use this integration to get information on the host.
Can I forward some intel in the docker config to make it work ?
If not, any suggestion to monitor cpu/memory/disk/network ?

Cheers

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2024.2.1

**Comment by gjohansson-ST** [comment]
This isn't an issue so I'm going to close this but in general almost all HA installations are docker based so shouldn't be a problem.
Why not just install it and give it a go?

**Comment by nicolascornet** [comment]
Sorry I wasn't explicit, I did give it a go and didn't get any information on the sensors.
I found out that all the sensors were desactived by default.
You have to activate all the sensors that you want one by one. To do that you have to go to the entity and find the activate checkbox.
Maybe this can be added to the documentation ?

**Comment by gjohansson-ST** [comment]
It is in the docs that all entities are disabled by default and you have to enable them.

**Comment by nicolascornet** [comment]
That's my bad, thanks for answering
