### ISSUE TITLE
Need more Tibber Accounts

### ISSUE THREAD

**Issue by sasquaatch** [home-assistant/home-assistant.github.io#31404]
### Feedback

Hello, I need more Tibber accounts because I run several accounts with the Tibber Pulse and want to read them out. Is it possible to add more entries?
Unfortunately it doesn't work at the moment :(

### URL

https://www.home-assistant.io/integrations/tibber/

### Version

2024.2.1

**Comment by Danielhiversen** [comment]
Feature Request
Please use our Community Forum for doing feature requests.
