### ISSUE TITLE
Could we add "speed" sensor to this integration?

### ISSUE THREAD

**Issue by foltymat** [home-assistant/home-assistant.github.io#31407]
### Feedback

First of all - love the revamp of the Proximity!

I imagine a scenario where the calculated speed between two points would be useful - like distinguishing a moving vehicle, compared to walking.

I do understand that it's not as simple and that the value will tell you almost nothing with a lot of curves and turns in the road, but with the high-accuracy mode enabled, I could see if I'm arriving in a car.

Just a thought, might help people like me to not create new template sensors :)

### URL

https://www.home-assistant.io/integrations/proximity/

### Version

2024.2.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
