### ISSUE TITLE
Page mentiones "advnaces options", which don't exist

### ISSUE THREAD

**Issue by ctron** [home-assistant/home-assistant.github.io#31412]
### Feedback

The page mentions to use "advanced options":

![image](https://github.com/home-assistant/home-assistant.io/assets/202474/1e9ef3fd-62df-452d-a704-7af9c8bd2a2b)

However, those don't exist:

![image](https://github.com/home-assistant/home-assistant.io/assets/202474/5c25bec1-cebd-4262-90c7-7d98280eb948)

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2024.2.1

**Comment by jbouwh** [comment]
Enable advanced options in your user settings (see the note a little lower on the page).

![afbeelding](https://github.com/home-assistant/home-assistant.io/assets/7188918/02154e71-f230-4b57-9425-11f5b2d776f7)

**Comment by ctron** [comment]
Yes, that indeed worked. And yes, there's a note in the docs about that too.

Still, I feels a bit weird not having that option right away.
