### ISSUE TITLE
Will not accept any IATA codes- KIAD, IAD, iad, DCA, KDCA, washington dulles, reagan national, etc.

### ISSUE THREAD

**Issue by bryansisk** [home-assistant/home-assistant.github.io#31417]
### Feedback

Not sure what happened, but doesn't seem to accept any identifiers.??

### URL

https://www.home-assistant.io/integrations/faa_delays/

### Version

2024.2.1

### Additional information

[FAA delays Home Assistant.pdf](https://github.com/home-assistant/home-assistant.io/files/14272252/FAA.delays.Home.Assistant.pdf)

**Comment by ntilley905** [comment]
The integration should work with the IATA code (eg. IAD or DCA). Can you provide the log data from the error when you try to add the integration? There should be an entry in your log that has more details.

**Comment by bryansisk** [comment]
I sure will  how can I find that. (new to home assistant). Thanks. I'll be
looking, but if you know a quick way thanks.

**Comment by ntilley905** [comment]
No problem. Select the sidebar menu (the three lines on the top left) and then Settings. On the Settings page select System and then Logs. You can search the logs page using the integration name `faa_delays` to find any errors there. The logs do reset at any reboot so make sure you've experienced the error since the last reboot.

**Comment by bryansisk** [comment]
Finally, sorry it took so long.

Logger: homeassistant.components.faa_delays.config_flow
Source: components/faa_delays/config_flow.py:40
Integration: FAA Delays (documentation, issues)
First occurred: 3:11:56 PM (27 occurrences)
Last logged: 4:15:54 PM

Unexpected exception: 0, message='', url=URL('
https://nasstatus.faa.gov/api/airport-events')
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/components/faa_delays/config_flow.py",
line 40, in async_step_user
    await data.update()
  File "/usr/local/lib/python3.12/site-packages/faadelays/__init__.py",
line 94, in update
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 0, message='', url=URL('
https://nasstatus.faa.gov/api/airport-events')

**Comment by ntilley905** [comment]
Thanks for that. It looks like there's a network issue affecting the device that's running your Home Assistant instance. The FAA API has issues for some reason with certain DNS servers. Are you able and willing to attempt setting the DNS server to 9.9.9.9 to see if that resolved it?

You can also try opening that link in your browser to see if you're having an issue on other devices. It'll just show as a big string of text.

**Comment by bryansisk** [comment]
I tried a quick attempt at every North american airport.  K's   Nothing
would go through.  Not sure if it's my side, or not.

Thanks much,

Bryan Sisk


Logger: homeassistant.components.faa_delays.config_flow
Source: components/faa_delays/config_flow.py:40
Integration: FAA Delays (documentation, issues)
First occurred: 3:11:56 PM (35 occurrences)
Last logged: 5:48:20 PM

Unexpected exception: 0, message='', url=URL('
https://nasstatus.faa.gov/api/airport-events')
Traceback (most recent call last):
  File
"/usr/src/homeassistant/homeassistant/components/faa_delays/config_flow.py",
line 40, in async_step_user
    await data.update()
  File "/usr/local/lib/python3.12/site-packages/faadelays/__init__.py",
line 94, in update
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 0, message='', url=URL('
https://nasstatus.faa.gov/api/airport-events')

**Comment by ntilley905** [comment]
The airport codes with a preceedjng Ks (the ICAO codes) will not work. Only the three digit identifier will work, such as BOS or IAD or ORD or LAX. This is a limitation of the API itself.

**Comment by bryansisk** [comment]
Got it.  I'll try the DNS change and IAD. Thanks.

**Comment by ntilley905** [comment]
Let me know if that resolves it. Sometimes changing the DNS server and changing it right back works, in case you have a specific DNS server you prefer.

**Comment by bryansisk** [comment]
That was the issue,  perfect fix.  Thank you.  Have a nice evening.

**Comment by klaasnicolaas** [comment]
Closing the issue, please note that this repository (and this issue tracker) is for documentation.

./Klaas
