### ISSUE TITLE
prusalink - docs says mk3s not supported, not true

### ISSUE THREAD

**Issue by rastislavpapp** [home-assistant/home-assistant.github.io#31414]
### Feedback

documentation says:

"This integration works with Prusa MINI/MINI+, Prusa MK3.9/MK4 and Prusa XL. It does not work with the older Raspberry Pi based Prusa Link printers."

This was true, but latest code changes (around december 2023) made it work with my MK3S with raspberry pi based prusa link:

![image](https://github.com/home-assistant/home-assistant.io/assets/7340256/491566a9-3a2a-4260-a877-29dbc918fe58)

### URL

https://www.home-assistant.io/integrations/prusalink/

### Version

2024.2.1

**Comment by rooquu** [comment]
> ### Feedback
> 
> documentation says:
> 
> "This integration works with Prusa MINI/MINI+, Prusa MK3.9/MK4 and Prusa XL. It does not work with the older Raspberry Pi based Prusa Link printers."
> 
> This was true, but latest code changes (around december 2023) made it work with my MK3S with raspberry pi based prusa link:
> 
> ![image](https://private-user-images.githubusercontent.com/7340256/304531387-491566a9-3a2a-4260-a877-29dbc918fe58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwOTA1OTUsIm5iZiI6MTcwODA5MDI5NSwicGF0aCI6Ii83MzQwMjU2LzMwNDUzMTM4Ny00OTE1NjZhOS0zYTJhLTQyNjAtYTg3Ny0yOWRiYzkxOGZlNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMTMzMTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGEwNTQ5MDU0NTc2OTI5NmM1ZTUwYmQ3NmMyZmIzYzM1ZGE0YWIzNTI5NWUwZTdiZTMyOTYxMTA4MDI5NDQ1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aK6skQ9RcXXUFFM8XfceM7Taqbux8NNSarkznsNeb64)
> ### URL
> 
> https://www.home-assistant.io/integrations/prusalink/
> ### Version
> 
> 2024.2.1
> ### Additional information
> 
> _No response_

For me it does not work
![grafik](https://github.com/home-assistant/home-assistant.io/assets/1035797/dfd6fbc4-f0b3-4afb-99ab-aa08db3f03d0)

I have it running on a pi zero with the rambo board connectors

**Comment by Skaronator** [comment]
There is currently a bug in the dependency that is already fixed but not yet implemented in home assistant: https://github.com/home-assistant-libs/pyprusalink/issues/77

Probably the reason it doesn't work for now.

**Comment by Skaronator** [comment]
This has been fixed with https://github.com/home-assistant/home-assistant.io/pull/32031

**Comment by Skaronator** [comment]
@home-assistant remove-label stale
@home-assistant close

**Comment by Skaronator** [comment]
@home-assistant close
