### ISSUE TITLE
Integration goes unavailable and does recover 

### ISSUE THREAD

**Issue by FFatHome** [home-assistant/home-assistant.github.io#31422]
### Feedback

See this thread: https://github.com/home-assistant/core/issues/100001

This is exactly what is happening to me as well. The integration goes unavailable and does not recover. Sometimes you can reload, often you have to reinstall. 

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2024.2.1

**Comment by rohankapoorcom** [comment]
This is not a documentation issue. You've already linked and commented on the correct issue. Please avoid duplication.
