### ISSUE TITLE
Information missing from reolink troubleshooting section

### ISSUE THREAD

**Issue by jeffc** [home-assistant/home-assistant.github.io#31421]
### Feedback

Back in April, I reported an [issue](https://github.com/home-assistant/core/issues/92047) that I was having with the reolink integration, where some callbacks from the camera weren't being received by home assistant. After going back and forth with the amazing @starkillerOG (the maintainer of the reolink integration), I thought I had found a solution but it ultimately still wasn't reliable for me.

Months later, I finally discovered what was causing my issues, and it was a subtle problem that I haven't seen described anywhere else. I'm running Home Assistant behind nginx acting as a reverse proxy, and the LAN URL I provided to home assistant in the settings pointed to that proxied host. My nginx was configured to set the HTTP `Upgrade` and `Connection` headers (as described in many tutorials out on the internet). I discovered this was interfering with my reolink doorbell's ONVIF callbacks; my theory is that the server was holding the connection open as if it was a websocket, and the doorbell started struggling with the open connections and ultimately wouldn't make any more. I added these directives to my nginx configuration, scoped to `/api/webhook/reolink.*`:

```
proxy_set_header Connection close;
proxy_set_header Upgrade "";
```

Connections came through much faster, but the log started showing frequent HTTP 499 errors and the connections weren't making it to home assistant. Enabling debug logging in nginx showed me that the doorbell was sending its pushes and now immediately closing the connection (`epoll_wait() reported that client prematurely closed connection`, then `shutdown() failed (107: Transport endpoint is not connected) while sending to client`) -- nginx was closing the connection it made to home assistant before it could actually transmit the data. I added the `proxy_ignore_client_abort on;` directive to that stanza and it seems to have solved the problem; I no longer see any errors in my log, and pushes come through faster than they ever did.

I'd recommend adding a bullet to the troubleshooting steps for the Reolink integration advising users who use nginx as a reverse proxy who are having trouble to add the following stanza to their nginx configuration file:

```
  # force reolink webhooks to be proxied without upgrade and close when
  # complete.
  location ~* /api/webhook/reolink.* {
    proxy_bind 127.0.0.1 transparent;
    proxy_pass http://127.0.0.1:8123;
    proxy_set_header Connection close;
    proxy_set_header Upgrade "";
    proxy_ignore_client_abort on;
  }
```

That would have saved me months of frustration. Even if you ultimately end up not adding it to the documentation, hopefully someone having trouble in the future finds this bug and it helps them out.

Thanks for all your hard work!

### URL

https://www.home-assistant.io/integrations/reolink/#troubleshooting

### Version

2024.2.1

**Comment by starkillerOG** [comment]
@jeffc thank you very much for the feedback and additional info!

I discussed this with the core team, but these NGINX proxy settings are too advanced to put in the general docs.
It may pussel and confuse the basic users.

Thank you anyway for making this issue!
Hopefully people that are also struggeling with this issue will find this!

**Comment by jeffc** [comment]
That absolutely makes sense. Really I just wanted to get my findings out
somewhere that a future me could find them if they were having mysterious
failures, and I suspect anyone else who has their own nginx setup will be
able to find this bug. Hopefully it saves someone some frustration.

Thanks again for your hard work on this integration!
