### ISSUE TITLE
Adding yale doorman v2n

### ISSUE THREAD

**Issue by robinmandt** [home-assistant/home-assistant.github.io#31432]
### Feedback

Hey. Is it possible to make yale doorman v2n lock with the Yale Home app, work in the august intergration? The lock is very common in my country, but I am not able to find a way to make it work wirh home assistant. 

### URL

https://www.home-assistant.io/integrations/august/

### Version

2024.2.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
