### ISSUE TITLE
Cannot find power consumption in home assistant integration

### ISSUE THREAD

**Issue by jrfalou** [home-assistant/home-assistant.github.io#31436]
### Feedback

Hi,
I don't seem to be able to add my airzone system to the energy panel in home assistant. I also am not able to read my energy consumption in there. I was hoping to be able to read the data collected by the airzone energy consumption component (https://www.airzonecontrol.com/ff/en/support/technical-details/airzone-consumption-meter/), which I have installed at home and which makes it possible to monitor power usage in my airzone cloud application (both on phone and computer) as can be seen in the attached picture of the app. Am I missing that feature or is it planned to be implemented sometime in the future?
Thank you.
![Screenshot 2024-02-14 220944](https://github.com/home-assistant/home-assistant.io/assets/56695857/04262a39-bd3a-46bd-b580-3381b576c241)

### URL

https://www.home-assistant.io/integrations/airzone/

### Version

2024.2.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
