### ISSUE TITLE
Cant connect to LUPUSEC XT3

### ISSUE THREAD

**Issue by xStardust1x** [home-assistant/home-assistant.github.io#31434]
### Feedback

Hopefully i can get information to solve the problem.

Iam filling the 3 fields of the integration but cant get a connection

I tried many different versions of the host address and i think this is my problem.

Can someone tell me with an example how to type it correctly.

### URL

https://www.home-assistant.io/integrations/lupusec

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
