### ISSUE TITLE
Unable to add KS240

### ISSUE THREAD

**Issue by mal7887** [home-assistant/home-assistant.github.io#31431]
### Feedback

Hello,

The Kasa KS240 switch was recently released. It is able to control the ceiling fan and ceiling fan light independently. The fan has 4 speeds, the dimmer functions like a normal dimmer switch. 

When I attempt to add the device I am promoted for credentials (like with the matter switches) If I enter proper credentials I get a Failed to connect message. I'm guessing since these switches are new, they aren't supported yet. If there is anything I can do to help, I am happy to do so :-)

![image](https://github.com/home-assistant/home-assistant.io/assets/47305194/b71ab70f-bfc8-457f-84d6-396ca7770ecf)

https://www.tp-link.com/us/home-networking/smart-switch/ks240/v1%20(1-pack)/

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.2.1

**Comment by sdb9696** [comment]
Hi, this issue is also raised against the python-kasa library here https://github.com/python-kasa/python-kasa/issues/749.

We understand the issue and should have a fix in the library out shortly.

**Comment by sdb9696** [comment]
> If there is anything I can do to help, I am happy to do so :-)

@mal7887 if we prepare a fix in the python-kasa library will you be able to test it by checking out the PR and running the cli? Are you comfortable with git/ptython venvs etc?

**Comment by mal7887** [comment]
Hi there,

I have no problem to test. If you give me specific instructions/commands to do I will follow them no problem.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by sdb9696** [comment]
Hi @mal7887, Klaas is right, I didn't realise this issue was on the wrong repo.  I will ping you from the python-kasa project issue https://github.com/python-kasa/python-kasa/issues/749 and close this issue.

**Comment by sdb9696** [comment]
@home-assistant close
