### ISSUE TITLE
include_only_feed_id should be recommended

### ISSUE THREAD

**Issue by nobbyneb** [home-assistant/home-assistant.github.io#31439]
### Feedback

include_only_feed_id should be highly recommended or required.
After trying with a local emoncms instance with ~70 feeds, the integration failed continuously until specific feeds were declared. Specifying Feed ID's resolved the problem. Suggest making this a requirement (or recommend over a certain number of feeds) vs. labelling optional.

https://community.openenergymonitor.org/t/emoncms-to-homeassstant-not-updating/25496/4

### URL

https://www.home-assistant.io/integrations/emoncms/

### Version

2024.2.1

### Additional information

https://community.openenergymonitor.org/t/emoncms-to-homeassstant-not-updating/25496/4

**Comment by alexandrecuer** [comment]
@home-assistant close
