### ISSUE TITLE
Polling interval "Pegel online" integration

### ISSUE THREAD

**Issue by TGM3D** [home-assistant/home-assistant.github.io#31460]
### Feedback

Hello.
With this service, the water level is queried every 5 minutes according to the log. No river changes that quickly.
Even the provider only updates every 15 minutes. A period of 30 minutes or more is sufficient. I have the effect that my IP is blocked there several times a day and the integration stops with errors. Only with Relaod does it continue for a few hours. I found out the whole thing by partially blocking the queries on the router and thus reducing the number.
​

### URL

https://www.home-assistant.io/integrations/pegel_online/

### Version

2024.2.1

**Comment by mib1185** [comment]
Hi @TGM3D 
this is the repository for out documentation, not for the code.
Nevertheless, i thought about your comment and with the updated `aiopegelonline` we will use the official [cache](https://www.pegelonline.wsv.de/webservice/dokuRestapi#caching) mechanism.
