### ISSUE TITLE
After update  2024.2.2 motion blinds fail

### ISSUE THREAD

**Issue by sbrunslev** [home-assistant/home-assistant.github.io#31477]
### Feedback

After update to 2024.2.2 
Motion blinds entries gone, went form 40 to 22, all of them now is only sensors.
can't control the blinds anymore.

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2024.2.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by starkillerOG** [comment]
see issue: https://github.com/home-assistant/core/issues/110755
