### ISSUE TITLE
Please add support for "powerstation" class devices. 

### ISSUE THREAD

**Issue by jhagenk** [home-assistant/home-assistant.github.io#31483]
### Feedback

Please add support for "powerstation" class devices. 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.2.2

### Additional information

It would be really useful to be able to script new "powerstation" class devices from within Home Assistant. 

This class of device covers the type of device called a "Solar Generator", which is a battery, a solar charger, a AC charger, and typically AC and DC outputs all in the same box. The latest generation of these devices have Bluetooth/Wifi remote command ability and at least one manufacturer is using Tuya's protocol in order to do this. 

It would be really useful to be able to use a physical wall switch to turn the outputs on and off and also be able to show the charging state on dashboards. 

I can pair the device with Home Assistant, but it shows as "unsupported". 
<img width="980" alt="Screenshot 2024-02-17 at 4 41 15 PM" src="https://github.com/home-assistant/home-assistant.io/assets/148917533/d5f73523-54d3-4652-bd55-775e627b3141">

The same device can be read/written via Tuya's developer APIs using the "Standard instruction set", so perhaps adding support is easy? I've confirmed that changing settings on the API page does result in physical setting changes. 

Screenshots attached. 

<img width="1320" alt="Screenshot 2024-02-17 at 4 49 22 PM" src="https://github.com/home-assistant/home-assistant.io/assets/148917533/d9903244-ba5f-49b9-a342-abc67038e3db">

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
