### ISSUE TITLE
CO2 sensors and optionbox

### ISSUE THREAD

**Issue by Bello2023** [home-assistant/home-assistant.github.io#31486]
### Feedback

"I have the option box connected to it with 3 CO2 sensors. Are the values of these also readable into Home Assistant?"

### URL

https://www.home-assistant.io/integrations/comfoconnect/

### Version

2024.2.2

**Comment by michaelarnauts** [comment]
No, they are not supported unfortunately afaik. There is no documented API, everything is done by reverse engineering, and I don't have an Option Box, so I can't check myself.

If you want to dedicate some time on this, you might want to find out the required sensors yourself. You can find the library with some example code here: https://github.com/michaelarnauts/aiocomfoconnect

I do recommend looking at https://github.com/michaelarnauts/home-assistant-comfoconnect though, it has a bit more features.

**Comment by michaelarnauts** [comment]
@home-assistant close
