### ISSUE TITLE
Old Shelly Website

### ISSUE THREAD

**Issue by benniju** [home-assistant/home-assistant.github.io#31490]
### Feedback

The link on the Shelly Integration page points to the old website (https://shelly.cloud), which no longer has an up to date SSL-Cerificate. The URL should be changed to their new website (https://shelly.com).

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2024.2.2

**Comment by chemelli74** [comment]
Hi @benniju, I just checked and indeed one of the 2 IPs of the main site has an expired certificate.
I already informed Shelly.

Note: Here the report if you are interested: [SSL Report: shelly.cloud](https://www.ssllabs.com/ssltest/analyze.html?d=shelly.cloud)

**Comment by benniju** [comment]
Oh that's interesting that they are using a different server for IPv6, I just assumed that the gave up that domain and switched to the new one, because shelly.cloud just redirects to shelly.com anyways.
