### ISSUE TITLE
To-Do-List improvements.

### ISSUE THREAD

**Issue by freddiemare** [home-assistant/home-assistant.github.io#31498]
### Feedback

I believe the to-Do-List is a fantastic tool but it would be even so much more powerful to have the To-Do-List as multiple instances for example configure the To-Do-List for each user so that each user can have their own todo configuration  
Another use case is to have the To-Do-List visible only for certain users.

At the moment To-Do-List is visible on all devices for all users on the system. Let me know what you think.

### URL

https://www.home-assistant.io/integrations/todo/

### Version

2024.2.2

### Additional information

You are welcome to ask any questions I have a lot of very good ideas.

Kind regards
Freddie

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
