### ISSUE TITLE
The method of authenticating changed, don't know how to set it up

### ISSUE THREAD

**Issue by jotheman0303** [home-assistant/home-assistant.github.io#31507]
### Feedback

It simply says "Enter your user code" but I have no idea how or where to find it. It's not in my app, and in addition previously your didn't even need the app. Please provide more info

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.2.2

**Comment by jotheman0303** [comment]
Found it, the Settings-icon wasn't there until after I updated the app. Thanks tho!

**Comment by frenck** [comment]
Glad you found a solution 👍 

../Frenck
