### ISSUE TITLE
Edit The Dashboard

### ISSUE THREAD

**Issue by Space-Cadet-Neil** [home-assistant/home-assistant.github.io#31504]
### Feedback

The edit the dashboard instructions are wrong at item 4.
The instructions say to click on the three dots - that is not correct. Instead it is necessary to click on the pencil icon to enter edit mode.
Please correct.

### URL

https://www.home-assistant.io/getting-started/onboarding_dashboard/

### Version

2024.2.2

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @Space-Cadet-Neil :+1: 

Not sure if you've seen it. On the bottom of the page, there is an edit button. When you select it, it let's you edit the page. In case you would like that.
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/8b4d40e1-1d3e-4bb7-a76a-75c032053ff1)
