### ISSUE TITLE
Simplisafe works without a paid plan

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#31512]
### Feedback

> SimpliSafe offers several [monitoring plans](https://support.simplisafe.com/articles/alarm-events-monitoring/what-are-the-service-plan-options/6344794a013ba90af0bce6a4). Currently, only the Standard and Fast Protect are known to work with this integration; if you find otherwise, please consider updating this documentation.

This no longer seems to be true.  Setting up an account without a paid plan now seems to work as expected (been using for around 24 hours now without issues).  

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2024.2.2

**Comment by bachya** [comment]
Would you be willing to submit an update to the docs?
