### ISSUE TITLE
Can we have a device_class for resistance?

### ISSUE THREAD

**Issue by kj4dxk** [home-assistant/home-assistant.github.io#31539]
### Feedback

Can we have a device_class for resistance?

### URL

https://www.home-assistant.io/integrations/sensor/#device-class

### Version

2024.2.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
