### ISSUE TITLE
it says me This entity is no longer provided by the wake_on_lan integration

### ISSUE THREAD

**Issue by merlino1975** [home-assistant/home-assistant.github.io#31537]
### Feedback

it says me This entity is no longer provided by the wake_on_lan integration

### URL

https://www.home-assistant.io/integrations/wake_on_lan/

### Version

2024.2.2

**Comment by ntilley905** [comment]
This is the code repository for the documentation, not for the actual integration. Please open an issue [here](https://github.com/home-assistant/core) and provide more details when you do, including what steps caused this and any error messages in the log. 

If you are actually talking about a documentation issue feel free to reopen this issue with additional details including what page on the Home Assistant website you are seeing this. 

@home-assistant close

**Comment by ntilley905** [comment]
@home-assistant close
