### ISSUE TITLE
Good integration but

### ISSUE THREAD

**Issue by chaletweb** [home-assistant/home-assistant.github.io#31557]
### Feedback

Hello, as it is a french integration, i continue in french.
Serait il possible d'ajouter la possibilité de mettre un code pour déverrouiller l'alarme (par exemple par une entrée dans le configuration.yaml) et même peut être pour la verrouiller (moins important) .
En effet, j'ai un tablette au mur et si je mets le panel alors n'importe qui peut déverrouiller l'alarme sans sécurité.
Sinon cette intégration est super utile. 

### URL

https://www.home-assistant.io/integrations/freebox/

### Version

2024.2.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests and the main language here is English.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
