### ISSUE TITLE
Cannot log into QNAP Integration

### ISSUE THREAD

**Issue by Roachforlife** [home-assistant/home-assistant.github.io#31572]
### Feedback

I use an authenticator app and guessing this is not compatible? Can you confirm? Thanks

### URL

https://www.home-assistant.io/integrations/qnap/

### Version

2024.2.3

**Comment by yanky79** [comment]
This same issue is impacting me.  Not sure if this is a permissions issue, or an authentication issue.

**Comment by Sebastian-Voigt** [comment]
Same here. I've add a new user without 2fa, but the same issue.
Can't connect to NAS.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
