### ISSUE TITLE
Govee light local

### ISSUE THREAD

**Issue by bisquit2003** [home-assistant/home-assistant.github.io#31585]
### Feedback

For a long time I used cloud integration from HACS govee (link below) 
after updating to version haos 24.2.3, I hoped to get local control, but the integration is not installed, reports that the yaml setting is not available and it is not in the list of integrations. 
what should I do in this situation? 
govee HACS cloud integration is configured from the GUI without yaml settings by the user

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.2.3

### Additional information

https://github.com/LaggAt/hacs-govee/blob/master/README.md

**Comment by klaasnicolaas** [comment]
Is this about the core integration or the HACS integration?

**Comment by bisquit2003** [comment]
> Is this about the core integration or the HACS integration?

Off course core

**Comment by klaasnicolaas** [comment]
You have to remove the HACS integration completely, only then will the core integration be visible in the list (so far I know). But it is better to ask this question in the community forum or Discord, we use this issue tracker for documentation issues.

./Klaas

**Comment by bisquit2003** [comment]
> You have to remove the HACS integration completely, only then will the core integration be visible in the list (so far I know). But it is better to ask this question in the community forum or Discord, we use this issue tracker for documentation issues.
> 
> ./Klaas

I deleted the govee hacs integration, rebooted the system, but nothing has changed.
Or should I also delete the integration in the hacs tab?

**Comment by klaasnicolaas** [comment]
Also from HACS 😉
