### ISSUE TITLE
Sensor request fan rpm (fan speed) (since the raspberry pi5 has a onboard fan connector.)

### ISSUE THREAD

**Issue by Genesis1969** [home-assistant/home-assistant.github.io#31586]
### Feedback

If possible, please add a sensor to read the fan rpm of the raspberry pi5, this device have special socket to plug in a fan to cool the system. It seems kinda controlled by the bios somehow, starts running at 50dec C at low speed.
I know there integrations to add a fan as a lamp dimmer, however thats a pi4 solution, also that integration is not reading the fan speed.

Found some information here [https://forums.raspberrypi.com/viewtopic.php?t=358188](url) about how.

Information what my pi give from:
>ls -l /sys/class/hwmon/

total 0
lrwxrwxrwx    1 root     root             0 Apr  4  2023 hwmon0 -> ../../devices/virtual/thermal/thermal_zone0/hwmon0
lrwxrwxrwx    1 root     root             0 Apr  4  2023 hwmon1 -> ../../devices/platform/axi/1000120000.pcie/1f000c8000.adc/hwmon/hwmon1
lrwxrwxrwx    1 root     root             0 Apr  4  2023 hwmon2 -> ../../devices/platform/cooling_fan/hwmon/hwmon2
lrwxrwxrwx    1 root     root             0 Apr  4  2023 hwmon3 -> ../../devices/platform/soc/soc:firmware/raspberrypi-hwmon/hwmon/hwmon3

>cat /sys/devices/platform/cooling_fan/hwmon/hwmon2/fan1_input
1468

tnx

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2024.2.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
