### ISSUE TITLE
why remove old compability in prusalink

### ISSUE THREAD

**Issue by TheDiverM** [home-assistant/home-assistant.github.io#31582]
### Feedback

why did you take away the complability for the printers utilizing the old prusalink, which was working great until you f*****ed it up., and since I cant get it to work unless i downgrade everything  to old enough homeassistant or spend 400 euro to upgrade my prusa.

what i (and other) think of this smart move isn't suitable for print

### URL

https://www.home-assistant.io/integrations/prusalink/

### Version

2024.2.3

**Comment by balloob** [comment]
Why can't you update the firmware on your printer?

**Comment by frenck** [comment]
As there was no response to the above, I'll go ahead and close up this PR.

../Frenck

**Comment by TheDiverM** [comment]
Then I need to replace the motherboard of the printer, this only works on prusa 3.5 , 39, and 4.0

 

All prusa before tah is unsupported, read the case

 

Fra: Paulus Schoutsen ***@***.***> 
Sendt: fredag 23. februar 2024 19:32
Til: home-assistant/home-assistant.io ***@***.***>
Kopi: Morten ***@***.***>; Author ***@***.***>
Emne: Re: [home-assistant/home-assistant.io] why remove old compability in prusalink (Issue #31582)

 

Why can't you update the firmware on your printer?

**Comment by frenck** [comment]
As far as I am aware, they where never supported? Our documentation has always been clear on which printers and firmware versions where supported by the integration. This has not changed, only extended.

../Frenck

**Comment by TheDiverM** [comment]
It was working until the update of the integration, it even said in release
notes the support for older printers was removed, and I had it working, but
since I can't get back the old integration since its internal in main
release of homeassistant without downgrade everything.

Alternative is to pay 450 euro for the new upgraded printer, and this is a
little excessive

man. 11. mars 2024, 18:39 skrev Franck Nijhof ***@***.***>:

**Comment by Skaronator** [comment]
Home-Assistant only officially supports PrusaLink that runs directly on the printer and not the old Prusa Connect Local, which has been renamed to Prusa-Link, as @frenck mentioned previously. However, it looks like the latest alpha builds added support for the [newer APIs](https://github.com/prusa3d/Prusa-Link/blob/573e379b9cf9f371ff8a86b1e8caa05e93dbf3c1/ChangeLog#L22), but they are still alpha.

Prusa Connect Local, the Raspberry Pi PrusaLink, [handles Digest Auth differently](https://github.com/home-assistant-libs/pyprusalink/issues/77) than the PrusaLink for Mini/MK4/XL, which is the reason these new alpha builds don't work yet. @the-ress did some work on fixing that in https://github.com/home-assistant-libs/pyprusalink/pull/78, but It's not yet in home-assistant.

I don't have a MK3, but you're welcome to contribute so we can officially support the older Prusa i3 printer as well.
