### ISSUE TITLE
Adding Views (aka Tabs) to a dashboard

### ISSUE THREAD

**Issue by slade-cj** [home-assistant/home-assistant.github.io#31589]
### Feedback

With recent changes to the Lovelace interface, the instructions at:
[https://www.home-assistant.io/dashboards/views/](url)
 have fallen behind.

The new method is as follows (revised from what's currently posted):

To add views to a dashboard, you have to take control of it.  With that in mind, you may want to create a new dashboard rather than taking control of the default / system managed Overview dashboard.

To add a view to your user interface, click the pencil icon in the upper right hand corner of the dashboard:
![1](https://github.com/home-assistant/home-assistant.io/assets/104589866/b1364107-1aa1-43e5-bd81-9efe1aee1c8a)

This will open the following overlay.  Click on the 3 dots:
![2](https://github.com/home-assistant/home-assistant.io/assets/104589866/a99715d1-d19b-4228-9dbe-86cbc43bb6c6)

This will open the following overlay.  Click on the Take Control option:
![3](https://github.com/home-assistant/home-assistant.io/assets/104589866/17cb9fd5-21a0-43eb-9cc4-6ef9a2c302da)

The following overlay will appear:
![4](https://github.com/home-assistant/home-assistant.io/assets/104589866/b7d287d4-03f1-4019-b818-5535098bdb5b)

Decide whether or not you want to start with an empty dashboard, and click Take Control.

The top ribbon will now look like this:
![5](https://github.com/home-assistant/home-assistant.io/assets/104589866/358b6ccd-3cf4-4a4c-823a-b44dfebf636e)

Add Views (tabs) by clicking the '+' sign, adjust the names and order as desired and click Done.

### URL

https://www.home-assistant.io/dashboards/views/

### Version

2024.2.3

### Additional information

Hope this helps ...

**Comment by slade-cj** [comment]
Once these steps are completed on a particular dashboard, clicking the pencil icon in the future will take the user directly to the gray ribbon (last screenshot above) where the Views (tabs) can be easily modified.

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @slade-cj :+1:

**Comment by c0ffeeca7** [comment]
Closing this as fixed by #31674
