### ISSUE TITLE
Override the climate entity's temperature unit

### ISSUE THREAD

**Issue by norburban** [home-assistant/home-assistant.github.io#31602]
### Feedback

HA system is setup to use Metric by default.  I would, however, like to report indoor temperatures for the climate.x entities in degrees Fahrenheit.  I haven't been able to find where I might be able to override it.  Is it possible? If yes, where can I make that change?

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2024.2.3

**Comment by mkmer** [comment]
IT doesn't appear that it is possible to override units on the climate entity (in the general case).
The sensor can be overridden, but I don't see it in the climate sensor.
Maybe a more experience core developer knows?

**Comment by kc2zgu** [comment]
Just ran into this trying to do the opposite with an ESPhome climate control (I live in a Fahrenheit-speaking place but want the temperature for a water heater controller to show in Celsius). I can expose the sensor as a separate entity and customize its units, but it seems climate entities in HA do not support showing in units other than the global default.

**Comment by frenck** [comment]
The climate platform doesn't support changing the unit of measurement (and will automatically adapt to the preference set in the system settings).

../Frenck
