### ISSUE TITLE
examples desired

### ISSUE THREAD

**Issue by lbosnjak** [home-assistant/home-assistant.github.io#31616]
### Feedback

Hello. I'm trying to use my first number.mqtt integration. 
IMHO a simple example and a full configuration example (similar to the ones for switch.mqtt and button.mqtt) would make the task easier for noobs like me.

### URL

https://www.home-assistant.io/integrations/number.mqtt/

### Version

2024.2.3

**Comment by jbouwh** [comment]
It depends on what you want to do. For every `mqtt` platform there is at least a basic config set up shown on top of the page. We want the example to reflect an actual use case if that is possible. So the suggestion is to supply such a sample config, of even open a PR to suggest it.

**Comment by jbouwh** [comment]
Closing this issue as not planned
