### ISSUE TITLE
Could Todoist be a candidate for Works With Home Assistant?

### ISSUE THREAD

**Issue by mr-ransel** [home-assistant/home-assistant.github.io#31617]
### Feedback

Todoist provides a detailed, but fairly lightweight process for listing integration on their own site. 

https://developer.todoist.com/guides/#marketing-your-app

It could be a nice touch to have Todoist list Home Assistant as an integration under their Automation category, just to get HA on the radar of more people that don't self define necessarily as hobbyists. 

### URL

https://www.home-assistant.io/integrations/todoist/

### Version

2024.2.3

**Comment by mr-ransel** [comment]
Oops, closed this by accident 😬

**Comment by mr-ransel** [comment]
Well it's closed, but figure I'll raise it to @balloob and @GuySie in case the Open Home Foundation has an interest in submitting HA to be listed on the [Todoist website](https://developer.todoist.com/guides/#marketing-your-app) as having a Todoist integration, since it's a fairly popular service and amounts to free marketing for home assistant to a less "hobbyist" crowd which is a direction they seem to be interested in moving

**Comment by frenck** [comment]
As this is a cloud service, it cannot join the Works with Home Assistant program.

../Frenck

**Comment by mr-ransel** [comment]
Yeah, I realized that after posting it, and you're absolutely right.

I still thought it might be worthwhile to get Home Assistant listed on the todoist website as a compatible integration, but I can't apply myself as I'm not a representative of HA in any capacity other than a user and community member.
--
Robert Ansel

-
Sent from my Pixel 6, using FairEmail

Sep 17, 2024 3:41:19 PM Franck Nijhof ***@***.***>:
