### ISSUE TITLE
PING QUESTIONS

### ISSUE THREAD

**Issue by lorcott** [home-assistant/home-assistant.github.io#31614]
### Feedback

I need to call a URL every 15 minutes to keep a health check alive. My automation looks like this...

alias: Healthcheck
description: Pings Healthcheck.io once every 15
trigger:
  - platform: time_pattern
    minutes: /15
    seconds: 0
condition: []
action:
  - service: homeassistant.update_entity
    data: {}
mode: single

The URL is https://hc-ping.com/5007c2c2-39d2-4d27-aff4-6a174252979c

System Options set for enable newly added entities and disabled for enable polling for updates. Can't seem to make this work. Did I misunderstand the usage of the integration???

### URL

https://www.home-assistant.io/integrations/ping/

### Version

2024.2.3

**Comment by jpbede** [comment]
This integration is used to ping devices on your network. [RESTful command](https://www.home-assistant.io/integrations/rest_command/) is what you're looking for. You can use this as a service in your automation.

**Comment by lorcott** [comment]
Thanks…I’ve added integration into config MANUALLY. However, the only CLOSE automation example was this….

automation:
- alias: "Arrive at Work"
  trigger:
    platform: zone
    entity_id: device_tracker.my_device
    zone: zone.work
    event: enter
  action:
    - service: rest_command.my_request
      data:
        status: "At Work"
        emoji: ":calendar:"


I just don’t know how to add my URL https://hc-ping.com/5007c2c2-39d2-4d27-aff4-6a174252979c and the time delay of 15 minutes.


Any help GREATLY appreciated.

S


From: Jan-Philipp Benecke ***@***.***>
Date: Sunday, February 25, 2024 at 2:16 PM
To: home-assistant/home-assistant.io ***@***.***>
Cc: Scott Levine ***@***.***>, Author ***@***.***>
Subject: Re: [home-assistant/home-assistant.io] PING QUESTIONS (Issue #31614)

This integration is used to ping devices on your network. RESTful command<https://www.home-assistant.io/integrations/rest_command/> is what you're looking for. You can use this as a service in your automation.

**Comment by jpbede** [comment]
We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you have additional questions or need help configuring a automation, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e) or use our [community forum](https://community.home-assistant.io/).

Thanks! 👍 Therefor I'm closing this.

**Comment by lorcott** [comment]
Understood. Thank again.

S

On Feb 25, 2024, at 2:56 PM, Jan-Philipp Benecke ***@***.***> wrote:

﻿

We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you have additional questions or need help configuring a automation, feel free to join our Discord chat server<https://discord.gg/c5DvZ4e> or use our community forum<https://community.home-assistant.io/>.

Thanks! 👍 Therefor I'm closing this.
