### ISSUE TITLE
StreamLabs water API no longer supports setting home/away mode

### ISSUE THREAD

**Issue by jcsfny** [home-assistant/home-assistant.github.io#31639]
### Feedback

I noticed recently with the new mobile app update, that my HA instance no longer can set StreamLabs water to home/away mode.  Emailed StreamLabs, and support seems to confirm it:

Hello,
 
Thank you for reaching out to StreamLabs support.  I am happy to assist. I do apologize, API is no longer supported with the new app update. However, within the app, there is an option to toggle on away mode on the launch page. 
 
Thank you 
-Michelle 
StreamLabs Support, a Chubb Company
support.streamlabswater.com

### URL

https://www.home-assistant.io/integrations/streamlabswater/

### Version

2024.2.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
