### ISSUE TITLE
Can you add support for DHE Connect (water heater / Durchlauferhitzer) please? 🙂 

### ISSUE THREAD

**Issue by MoFa85** [home-assistant/home-assistant.github.io#31633]
### Feedback

Hi,
I just got a brand new Stiebel Eltron DHE Connect water heater and was wondering why this hasn't been integrated anywhere by now 🙂 Do you see a chance to make this unit accessible via the existing integration? I will be happy to provide any needed information to make it happen.
Thanks in advance, Mo

### URL

https://www.home-assistant.io/integrations/stiebel_eltron/

### Version

2024.2.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
