### ISSUE TITLE
Unable to choose templated sensor values for "Home battery storage" Energy card?

### ISSUE THREAD

**Issue by rtw819** [home-assistant/home-assistant.github.io#31638]
### Feedback

There seems to be no way to pick corrected values generated by manually created template sensor entities (using the proper units) for the Energy Card configuration under the Home battery storage section where there are limited selections for these two values:
"Energy going in to the battery"
"Energy coming out of the battery"

In this case, the SolarEdge integration module battery entities are not reporting measured battery Energy Import and Energy Export values as expected, so I created template sensor values which should work as alternatives, however, I cannot use them nor add them to the "Home battery storage" configuration.

This seemed to be the best place I could determine for this request outside of the nebulous feature request section.  However, if this is not the right section for this issue/comment, please accept apologies in advance and feel free to let me know in the comments and I will recreate the issue there.

Thank you for all you do!

### URL

https://www.home-assistant.io/docs/energy/battery/

### Version

2024.2.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
