### ISSUE TITLE
have 150 leds, but cannot select them individually with this plugin

### ISSUE THREAD

**Issue by kiam001** [home-assistant/home-assistant.github.io#31630]
### Feedback

unfortunately it is not possible to control the leds individually in homeassitend, such a possibility would be cool because you could use them for status boards with led colors

### URL

https://www.home-assistant.io/integrations/wled/

### Version

2024.2.3

**Comment by frenck** [comment]
That is correct; you can create sections in WLED to control individual LEDs or sections of LEDs.

../Frenmck

**Comment by kiam001** [comment]
No, Segments only 10 Support, Software Limit, but via Json/http api its possible change LEDs separate.

**Comment by kiam001** [comment]
https://kno.wled.ge/features/segments/

Currently you can create a maximum of 10 segments.

**Comment by frenck** [comment]
Yes, that is correct. I'm aware.

I sketch the possibilities with this integration available to you. 

../Frenck
