### ISSUE TITLE
Add SMUD as a provider

### ISSUE THREAD

**Issue by fgonza2** [home-assistant/home-assistant.github.io#31640]
### Feedback

not sure how this works but, would it be possible to add SMUD (Sacramento Municipal Utility District) as a provider? i know they are in opower.    I can potentially help if there is a pointer to get started.  Is there a special API access that needs to be granted by SMUD? or is it a developer capacity/bandwidth situation?

thanks

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2024.2.4

**Comment by fgonza2** [comment]
closing as duplicate

**Comment by tronikos** [comment]
Not sure why this was closed as duplicate. Anyway this isn't a place for feature requests. The good news is this is being added in https://github.com/tronikos/opower/pull/70
