### ISSUE TITLE
Even after latest 2024.2.4, the BRING TODO list show up in German

### ISSUE THREAD

**Issue by Zoriontsu** [home-assistant/home-assistant.github.io#31655]
### Feedback

I was expecting 2024.2.3 or 2024.2.4 to address the language localization issue, but it is this showing all list entries in German.

### URL

https://www.home-assistant.io/integrations/bring/

### Version

2024.2.4

**Comment by miaucl** [comment]
Hello, this fix will not be taken into account by a patch release as it is too big and introduces new functionality. You have to wait for `2024.3.0`.

The master currently still uses `0.3.0` of the bring-api and the translation was introduced by `0.4.1` https://github.com/home-assistant/core/pull/111149 and will get improved again on `0.5.2` https://github.com/home-assistant/core/pull/111654.

https://github.com/home-assistant/core/blob/master/homeassistant/components/bring/manifest.json

**Comment by klaasnicolaas** [comment]
Core issue and therefore closing it here.

./Klaas
