### ISSUE TITLE
*_last_seen filling the logbook with hundreds of lines a minute. 

### ISSUE THREAD

**Issue by JML30** [home-assistant/home-assistant.github.io#31668]
### Feedback

How can we turn off logging of Zwave devices? Last seen messages filling the log and make it useless.
I have 20 devices.

### URL

https://www.home-assistant.io/dashboards/logbook/

### Version

2024.2.5

**Comment by c0ffeeca7** [comment]
When you edit the card on the dashboard, or add the card new to the dashboard, you can select which entities to show:

![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/90c48364-0734-4ef2-8419-f5a29aadcb6c)

**Comment by JML30** [comment]
Hi. It is not the logbook CARD, it is the logbook over History on the left sidepanel.

BR

 

Fra: c0ffeeca7 ***@***.*** 
Sendt: torsdag 29. februar 2024 17:07
Til: home-assistant/home-assistant.io
Kopi: JML30; Author
Emne: Re: [home-assistant/home-assistant.io] *_last_seen filling the logbook with hundreds of lines a minute. (Issue #31668)

 

When you edit the card on the dashboard, or add the card new to the dashboard, you can select which entities to show:

image.png (view on web) <https://github.com/home-assistant/home-assistant.io/assets/38767475/90c48364-0734-4ef2-8419-f5a29aadcb6c>

**Comment by c0ffeeca7** [comment]
Ah, I see. I think you are looking for this:

<https://www.home-assistant.io/integrations/logbook/#configure-filter>



```
logbook:
  exclude:
    entity_globs:
      - sensor.*_last_seen
```

**Comment by JML30** [comment]
Yes thanks. It worked J

 

Fra: c0ffeeca7 ***@***.*** 
Sendt: torsdag 29. februar 2024 17:51
Til: home-assistant/home-assistant.io
Kopi: JML30; Author
Emne: Re: [home-assistant/home-assistant.io] *_last_seen filling the logbook with hundreds of lines a minute. (Issue #31668)

 

Ah, I see. I think you are looking for this:

https://www.home-assistant.io/integrations/logbook/#configure-filter

logbook:
  exclude:
    entity_globs:
      - sensor.*_last_seen

**Comment by c0ffeeca7** [comment]
Closing this issue as resolved by <https://www.home-assistant.io/integrations/logbook/#configure-filter>
