### ISSUE TITLE
Synology SRM Administrator Accounts

### ISSUE THREAD

**Issue by JYoukers73** [home-assistant/home-assistant.github.io#31670]
### Feedback

The Synology SRM Instructions incorrectly state " It’s not possible to create another account in SRM with admin permissions. "  It is now possible to assign admin permissions to any user account.

### URL

https://www.home-assistant.io/integrations/synology_srm/

### Version

2024.2.5

**Comment by hexEF** [comment]
Thanks for providing feedback on this! 

I was curious about the historical reasons here. The docs from Synology suggest it depends on the SRM version (plus some additional caveats): https://kb.synology.com/en-id/SRM/tutorial/Create_multiple_administrator_accounts_on_Synology_Router

Rephrasing the wording of our docs slightly and referring to theirs should be a good middle-ground to cover all these scenarios.
