### ISSUE TITLE
Camera failed to log

### ISSUE THREAD

**Issue by Likaybai** [home-assistant/home-assistant.github.io#31671]
### Feedback

Could not authenticate: HTTP Error: 401 Unauthorized (code:SOAP-ENV:Sender) (subcodes:)

### URL

https://www.home-assistant.io/integrations/onvif/

### Version

2024.2.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
