### ISSUE TITLE
Error while try to install using the button.

### ISSUE THREAD

**Issue by varbanov-v** [home-assistant/home-assistant.github.io#31676]
### Feedback

Im getting error on my home assistant green that says I need latest update while trying to install it with the "my" button. and I'm running the latest update on home assistant

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2024.2.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
