### ISSUE TITLE
Missing word in getting started documentation

### ISSUE THREAD

**Issue by scooby52** [home-assistant/home-assistant.github.io#31679]
### Feedback

In the section called Automations, bullet item 2 says: "Conditions - optional tests that must be met an action
can be run. For example, if someone is home."
I suggest the word "before" should be added between "met" and "an" so that it would become: "Conditions - optional tests that must be met before an action can be run. For example, if someone is home. "

### URL

https://www.home-assistant.io/getting-started/concepts-terminology/

### Version

2024.2.5

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @scooby52 :heart: 

For another time, if you want to make a tiny tweak to the docs:

![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/9af0cf49-d9e1-481d-b108-118efad34f7d)

There is an **Edit** button at the bottom of the page. It lets you edit the page yourself, if you like.

**Comment by scooby52** [comment]
Hi c0ffeeca7, I did see the edit button, and did try it, but it took me to screens that I was not familiar with, and not wanting to mess anything up as I am a newbie I decided to play safe, and use the feedback option. Hopefully I will have time to learn more about how documentation is managed in Github, but that's a job for anotherday !
