### ISSUE TITLE
Mode (Home, Not Home, Disabled) missing from integration

### ISSUE THREAD

**Issue by robitsrl** [home-assistant/home-assistant.github.io#31688]
### Feedback

Hi, It would be nice as Homebridge does, to have the switch to set the house mode (Home, not Home and disabled)

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2024.2.5

**Comment by sdb9696** [comment]
This should be raised as a feature request in the home assistant [core repo](https://github.com/home-assistant/core).

**Comment by sdb9696** [comment]
@homeassistant close

**Comment by sdb9696** [comment]
@home-assistant close
