### ISSUE TITLE
Easier step

### ISSUE THREAD

**Issue by knebb** [home-assistant/home-assistant.github.io#31689]
### Feedback

The existing tip leads into a direction which is not helpful.

The simple way to fix this issue is a simple:
`docker restart hassio_supervisor
`

Please add to doc. I tried but have to create a fork (which I do not want as I am not a coder....)

Greetings

### URL

https://www.home-assistant.io/more-info/unhealthy/privileged/

### Version

2024.2.5

**Comment by frenck** [comment]
> The simple way to fix this issue is a simple:
> docker restart hassio_supervisor 

That is not a fix. 

See the solution section for the correct and possible fixes:

<https://www.home-assistant.io/more-info/unhealthy/privileged/#the-solution>

../Frenck
