### ISSUE TITLE
Define by track?

### ISSUE THREAD

**Issue by Dizzler71** [home-assistant/home-assistant.github.io#31702]
### Feedback

I like this integration, but i have a problem. Specifying a bus stop works, but i only want the bus times in one direction. Though i use "heading" i get the next time in both directions. I think is's because the bus returns from a endstop, and  timetable includes the heading bus stop in the return trip. Therefore my heading bus stops is included in all travels from my bus stop. Is it possible to define track instead of heading? I think hat would solve my problem 

### URL

https://www.home-assistant.io/integrations/vasttrafik/

### Version

2024.2.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
