### ISSUE TITLE
Not working... V60 CC 2023

### ISSUE THREAD

**Issue by ahlburg** [home-assistant/home-assistant.github.io#31709]
### Feedback

No entities presented...

### URL

https://www.home-assistant.io/integrations/volvooncall/

### Version

2024.2.5

**Comment by ahlburg** [comment]
.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
