### ISSUE TITLE
Google Home app needs to be installed in order to add matter device via Android phone

### ISSUE THREAD

**Issue by jonasgeyer** [home-assistant/home-assistant.github.io#31700]
### Feedback

I am an iPhone user, but I wanted to use a SkyConnect to turn Home Assistant into a Thread border router.

I followed the instructions "Turning Home Assistant into a Thread border router", bought a cheap Android 10 phone (just to be able to add a Matter over Thread device) but got stuck at point 4. "To add Matter-based Thread devices, follow ....".

It was necessary to install "Google Home" on that Android phone - that should be clearly described somewhere, that the Google Home App is a requirement.
I eventually found this out from this page: https://www.home-assistant.io/integrations/matter/
Under "WHEN I’M TRYING TO COMMISSION USING THE ANDROID APP, I GET AN ERROR STATING “MATTER IS CURRENTLY UNAVAILABLE”
" it says:
Some users have reported that uninstalling and reinstalling the Google Home app fixed this issue for them. Also see this [extended troubleshooting guide](https://developers.home.google.com/matter/verify-services) from Google.

After I installed (it wasn't on the phone before) Google Home - I was able to add my first Matter over Thread device.

### URL

https://www.home-assistant.io/integrations/thread/

### Version

2024.2.5

**Comment by agners** [comment]
Did you install the Home Assistant App from the Google Play store?

The manifest of the full Android App clearly states that the Matter commissioning services are required, see: https://github.com/home-assistant/android/blob/648fa9acc0cc166c196cde6fa5636871ffae1dcf/app/src/full/AndroidManifest.xml#L51-L53

This sounds like a bug in Android/on that particular phone maybe? :thinking: 

/cc @jpelgrom

**Comment by agners** [comment]
Maybe this was just a race condition? :thinking:  The troubleshooting guide mentions this:

> The Matter modules have not been downloaded yet. Wait at least 24 hours for them to download. Ensure your device is powered on and charging during this time, so the download isn't delayed. If you haven't received the modules within 24 hours, you can try a factory data reset of the device to force the modules to download.

**Comment by jonasgeyer** [comment]
Yes, I did install it directly from the Google Play store, and I gave it about 1 day of time.

Only after I read about that some need to uninstall/reinstall Google Home, did I realized that Google Home wasn't installed on my phone. After then installing it, everything worked.
I use a Samsung Galaxy A11 (A115U) with Android version 10 (A115USQS8AWC1), One UI 2.1.

I just thought it may be helpful to add to the instructions to install Google Home.
________________________________
