### ISSUE TITLE
A little love for CAD?

### ISSUE THREAD

**Issue by Ottawaman69** [home-assistant/home-assistant.github.io#31711]
### Feedback

Hi can you add CAD pairs to the coins?  ie:   BCH/CAD, SOL/CAD 

### URL

https://www.home-assistant.io/integrations/kraken/

### Version

2024.2.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
