### ISSUE TITLE
Feedback: Can you please add "scripts" to this card?

### ISSUE THREAD

**Issue by HuisAutomatisering** [home-assistant/home-assistant.github.io#31716]
### Feedback

Feedback. If it would be possible to trigger a script-entity (as button) on this card it would be even more useful.
Hiding the title or make it smaller would be nice, it's so big when using the card in a horizontal stack in the dashboard.

### URL

https://www.home-assistant.io/dashboards/area/

### Version

2024.2.5

### Additional information
I set the area of my script script. But i seem not to make it possible to make it appear here. I added "script" to the "sensor" area. But it doesn't show the script on the card.

**Comment by dannytsang** [comment]
Hi @HuisAutomatisering 

You've come to the documentation repository. Can you raise this as a new feature by going to **New issue** > **Feature Request** please.
