### ISSUE TITLE
NMBS-integration

### ISSUE THREAD

**Issue by frederikvoGIT** [home-assistant/home-assistant.github.io#31720]
### Feedback

I don't understand how i can get from the configuration.yaml-text to input in a Dashboard card.
The tutorial in https://github.com/custom-cards/entity-attributes-card is with a completely other example.
So for a noob for me it is not understandable.

### URL

https://www.home-assistant.io/integrations/nmbs/

### Version

2024.2.5

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas

**Comment by frederikvoGIT** [comment]
Ok, thanks for the Quick respons. 

Op 3 mrt. 2024 om 19:36, schreef Klaas Schoute ***@***.***>:

Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our Community Forum or join our Discord chat server.

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
