### ISSUE TITLE
ZHA firmware update from file

### ISSUE THREAD

**Issue by torge70** [home-assistant/home-assistant.github.io#31727]
### Feedback

The requirement to add a new option in configuration.yaml to get ZigBee firmware update to work is not mentioned. I think this was introduced in the 2024.01 release.
I cannot find this in the documentation or release notes for 2024.01.

      allow_file_providers: "I understand I can *destroy* my devices by enabling OTA updates from files. Some OTA updates can be mistakenly applied to the wrong device, breaking it. I am consciously using this at my own risk."

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2024.2.5

**Comment by Hedda** [comment]
FYI, ZHA developers have said that they do not want details about that feature, only mentioning that it exists, see -> https://github.com/home-assistant/home-assistant.io/pull/28895
