### ISSUE TITLE
Documentation is difficult to understand

### ISSUE THREAD

**Issue by djh42** [home-assistant/home-assistant.github.io#31733]
### Feedback

I've just bought a HA Green and started it yesterday. I want to install the emoncms integration so I went to https://www.home-assistant.io/integrations/emoncms/ and clicked on the [Looking for your configuration file?](https://www.home-assistant.io/docs/configuration/) link. From there I followed the See [here](https://www.home-assistant.io/common-tasks/supervised/#installing-and-using-the-visual-studio-code-vsc-add-on) for details link but it doesn't describe how to install or use the VSC add-on at all!

So what I see is a rabbit warren of links that haven't been thought through to make sense to somebody who is just starting to learn how to use HA. And I've formed that opinion elsewhere in the documentation too. It's all very confusing and difficult to follow.

### URL

https://www.home-assistant.io/common-tasks/supervised/

### Version

2024.2.5

**Comment by c0ffeeca7** [comment]
Sorry to hear the documentation caused confusion.

Some integrations cannot be added via user interface, but have to be added by adding an entry into the configuration.yaml file.

Added #32472, #32619, #32635 to make it easier to find the information on how to edit the configuration.yaml file for integrations that do not support setup via user interface.

The documentation on Getting started with Home Assistant Green can be found on its own [website](https://green.home-assistant.io/)
