### ISSUE TITLE
specific port instead of 80 doesn't

### ISSUE THREAD

**Issue by Enjoy-Combi** [home-assistant/home-assistant.github.io#31744]
### Feedback

From the documention it seems that we can use the port we want for the connection to ha instead of 80:
![image](https://github.com/home-assistant/home-assistant.io/assets/63100556/10833d88-a048-4258-8ad9-c113cf379cfb)

But this ends up to unable to connect. As soon as I change the port to 80, no issue.

### URL

https://www.home-assistant.io/integrations/alexa.smart_home/

### Version

2024.2.5

**Comment by jbouwh** [comment]
It must be a public URL to your Home Assistant instance. If you used a custom port external, you can use that port. If you select another port the the actual port, or when you Home Assistant installation is not exposed outside, then this will not work.
Furher the connection must be secure. Port 80 is reserved for non secure connections.

**Comment by Enjoy-Combi** [comment]
It was a public address https://ha.address.fr:8223 working good for the ha application, google assistant & webbrowser access.
I had before the port 80 for octroprint instance. I have changed this and it works. Before only the access with the token was OK, impossible to connect the app.
Might it be that during the connection with the alexa app, the app looks first at port 80 and if failed to the specific port ? In that case it would have ended up to octoprint instance instead ha instance.

**Comment by jbouwh** [comment]
I am not sure on this. If you are sure this is an issue, then consider opening a ticket on our core repository, as I can not see what the issue is on the documentation without being able to verify it myself.
