### ISSUE TITLE
Verisure integration doesn't work in Italy - confirm

### ISSUE THREAD

**Issue by TeoLinuX** [home-assistant/home-assistant.github.io#31749]
### Feedback

I confirm that it doesn't work in Italy
Mainly because the login form requires the email and password, but the Verisure service has been setup with a username (not email) and password

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2024.2.5

**Comment by frenck** [comment]
Thanks! That has been documented recently:

![CleanShot 2024-03-05 at 16 10 19@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/4e06a122-f222-4c80-9391-a39db821ddb1)


../Frenck
