### ISSUE TITLE
when will HA support Inkbird wifi devices?

### ISSUE THREAD

**Issue by madh** [home-assistant/home-assistant.github.io#31765]
### Feedback

I have an inkbird IBS-TH5 WIFI

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
