### ISSUE TITLE
Full daily overview of hourly prices in integration?

### ISSUE THREAD

**Issue by jvdburgt** [home-assistant/home-assistant.github.io#31762]
### Feedback

As far as I can make up from the information page, the integration provides min and max hourly rates per day, but can the hourly prices for the entire day also be extracted somehow? 

For context: if my car needs to charge for 3 hours, it's nice to know what the cheapest 3 hours of the day are.

### URL

https://www.home-assistant.io/integrations/tibber/

### Version

2024.2.5

**Comment by Danielhiversen** [comment]
Currently not possible, https://github.com/home-assistant/core/pull/111164

You could take a look at https://github.com/Danielhiversen/home_assistant_tibber_data
