### ISSUE TITLE
Show automation description in automation list page

### ISSUE THREAD

**Issue by Borty97** [home-assistant/home-assistant.github.io#31766]
### Feedback

It should be great to show the description in the automations page list

### URL

https://www.home-assistant.io/docs/automation/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
