### ISSUE TITLE
No Support for H6199

### ISSUE THREAD

**Issue by CooperBoy** [home-assistant/home-assistant.github.io#31784]
### Feedback

Any chance you could code support for the Govee TV lights H6199 and H6171..

Thanks for what you have done so far...

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
