### ISSUE TITLE
API for AEMET Open Data

### ISSUE THREAD

**Issue by Rudi2905** [home-assistant/home-assistant.github.io#31786]
### Feedback

have received the API from AEMET
in Home Assistant integration I always get the message API not valid

### URL

https://www.home-assistant.io/integrations/aemet/

### Version

2024.3.0

**Comment by Noltari** [comment]
> ### Feedback
> 
> have received the API from AEMET
> 
> in Home Assistant integration I always get the message API not valid
> 
> ### URL
> 
> https://www.home-assistant.io/integrations/aemet/
> 
> ### Version
> 
> 2024.3.0
> 
> ### Additional information
> 
> _No response_

@Rudi2905 is there anything in the logs?

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
