### ISSUE TITLE
SMA Integration

### ISSUE THREAD

**Issue by littleyoda** [home-assistant/home-assistant.github.io#31791]
### Feedback

It should be mentioned that not all series are supported by SMA. For example, the SMA Tripower X is not supported. 

Suggested wording:

Restrictions:
Not all SMA inverters and storage systems are supported. The use of SunSpec is possible for the SMA Tripower X series.

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2024.3.0

### Additional information

https://github.com/home-assistant/core/issues/67953#issuecomment-1869796442

Not sure if linking to a custom component is allowed.
if yes, a link to https://github.com/CJNE/ha-sunspec would be helpful

See also the issue in the underlying python library.
https://github.com/kellerza/pysma/issues/119

**Comment by rklomp** [comment]
Feel free to provide a pull request with a change.

**Comment by littleyoda** [comment]
done
