### ISSUE TITLE
Fireplace mode

### ISSUE THREAD

**Issue by Antonmanssoon** [home-assistant/home-assistant.github.io#31806]
### Feedback

Hey! is there by any chanse possible to add fireplace mode to the presets for extra functionality.

### URL

https://www.home-assistant.io/integrations/flexit_bacnet/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by lellky** [comment]
Please report feedback and post feature requests here: https://community.home-assistant.io/t/flexit-nordic-bacnet-roadmap-ideas/675223
