### ISSUE TITLE
workday integration

### ISSUE THREAD

**Issue by tammeryousef1006** [home-assistant/home-assistant.github.io#31807]
### Feedback

i couldnt find country jordan at the list , can you please add it 

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
