### ISSUE TITLE
Option for select Transport vehicle, Bus or Train 

### ISSUE THREAD

**Issue by MarioImhof** [home-assistant/home-assistant.github.io#31804]
### Feedback

Is it possible to add the Functionallity, to select the art of Transportation? Like Bus or Train, or Ship? Thanks for your answer.

### URL

https://www.home-assistant.io/integrations/swiss_public_transport/

### Version

2024.3.0

**Comment by miaucl** [comment]
Hey, I am currently working on the integration and we nees to clean up some stuff before adding more to it. But it is on the roadmap👍

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
