### ISSUE TITLE
Broken Ring intercom integration with 2024.3 update

### ISSUE THREAD

**Issue by danieleangeli** [home-assistant/home-assistant.github.io#31811]
### Feedback

Hi there, I am writing to notify that after having upgraded my HASS system to 2024.3 it broke the Ring intercom integration with the device intercom_handset_audio

the device is not being shown within the account in the integration panel as It was previously. 

Here i am adding the full diagnostics just downloaded 

[config_entry-ring-9d74f58aeacb9dd796562840adab3f56.json](https://github.com/home-assistant/home-assistant.io/files/14547231/config_entry-ring-9d74f58aeacb9dd796562840adab3f56.json)

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
