### ISSUE TITLE
The Name option for entities in the History Graph card is editable in the GUI

### ISSUE THREAD

**Issue by bleakcomb** [home-assistant/home-assistant.github.io#31817]
### Feedback

This could a user error, though the documentation for the History Graph card says, "All options for this card can be configured via the user interface." 

As far as I can work out, the Name option for Entities is not accessible from the GUI. It would be nice if the option was accessible from there, but until it is, the docs probably reflect that. I spent some time looking :-) Again, I might be driving the GUI editor incorrectly, but someone might be able to check.

### URL

https://www.home-assistant.io/dashboards/history-graph/

### Version

2024.3.0

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @bleakcomb. You are right, not all settings can be changed from the UI.

**Comment by c0ffeeca7** [comment]
Closing this issue as fixed by #32963
