### ISSUE TITLE
This new feature is GREAT!

### ISSUE THREAD

**Issue by IIIdefconIII** [home-assistant/home-assistant.github.io#31812]
### Feedback

Thanks alot devs, this would really be nice!!!! love home assistant, still trying to setup my last few devices including a google nest is kinda painly to get working.

### URL

https://www.home-assistant.io/dashboards/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Great to hear that you like the (experimental) new sections dashboard 😃 But I will close your issue because we only use the issue tracker here for documentation issue.

./Klaas
