### ISSUE TITLE
Individual device vs full consumption

### ISSUE THREAD

**Issue by midstar** [home-assistant/home-assistant.github.io#31825]
### Feedback

The new Individual device energy consumption is great. However, if you cannot measure all individual devices it is hard to see the relation of the individual devices compared to the full energy consumption. Currently you must compare the two different graphs.

Would it be possible to have to full energy consumption visible in the individual device graph? Maybe fill upp the bars with an area called "Other consumers" or similar?

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
