### ISSUE TITLE
What is ESPHome configuration.yaml?

### ISSUE THREAD

**Issue by joba-1** [home-assistant/home-assistant.github.io#31826]
### Feedback

The file ESPHome configuration.yaml is mentioned, but I cannot find it.
I use the Home Assistant docker container, added the ESPHome integration and use Atom Echos as voice assistant devices.
I did all this by following Home Assistant documentation. But here you loose me. I'd like to access this file because I think I can configure mic parameters there but where? Is this the same as the home assistant configuration.yaml? I can find that... 

### URL

https://www.home-assistant.io/integrations/esphome/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
I suspect we are talking about the YAML file of your ESPHome device, the docs could indeed do better on this point.

./Klaas

**Comment by joba-1** [comment]
yes, ESPHome. I described what helped here: https://community.home-assistant.io/t/need-help-on-tweaking-the-assist-audio-configuration/701977/3 . Maybe not the best way to do it, feel free to suggest improvements :)
