### ISSUE TITLE
Change of predefined parameter limitation - grid export limit

### ISSUE THREAD

**Issue by peroutka76** [home-assistant/home-assistant.github.io#31833]
### Feedback

Hello,
I have the 25kW version of GW ET converter. The integration does not allow me to set the grid export limit over 10,000. Can this limit be changed (increased), e.g. to 20,000? Thank you for the help.

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2024.3.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
