### ISSUE TITLE
Need new function

### ISSUE THREAD

**Issue by Arketech13** [home-assistant/home-assistant.github.io#31865]
### Feedback

The themrometer sends too much data, about every 20sec.
Is it possible to add a parameter to set the data transmission interval for each entity in minutes?
To monitor the temperature of a room, it's not necessary to be so precise. Every hour is enough.

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2024.3.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
