### ISSUE TITLE
WeatherFlow Fail REST

### ISSUE THREAD

**Issue by gbarrena** [home-assistant/home-assistant.github.io#31862]
### Feedback

The integration fail I attach the debug file
[home-assistant_weatherflow_cloud_2024-03-09T21-06-30.573Z.log](https://github.com/home-assistant/home-assistant.io/files/14583690/home-assistant_weatherflow_cloud_2024-03-09T21-06-30.573Z.log)

### URL

https://www.home-assistant.io/integrations/weatherflow_cloud/

### Version

2024.3.0

**Comment by gbarrena** [comment]
> Hey there @jeeftor, mind taking a look at this feedback as it has been labeled with an integration (`weatherflow_cloud`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L880) for? Thanks!
> 
> Code owner commands
> Code owners of `weatherflow_cloud` can trigger bot actions by commenting:
> 
> * `@home-assistant close` Closes the feedback.
> * `@home-assistant rename Awesome new title` Renames the feedback.
> * `@home-assistant reopen` Reopen the feedback.
> * `@home-assistant unassign weatherflow_cloud` Removes the current integration label and assignees on the feedback, add the integration domain after the command.
> * `@home-assistant add-label needs-more-information` Add a label (needs-more-information) to the feedback.
> * `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information) on the feedback.

I don't understand what you mean

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
