### ISSUE TITLE
Apple TV Integration states stays at idle even ATV put to sleep

### ISSUE THREAD

**Issue by edmondss** [home-assistant/home-assistant.github.io#31863]
### Feedback

The states of ATV stays at idle even the apple TV 4k gen 3 is at sleep. The states does not change.

It works when the ATV is 'playing' or 'paused' for media playing but it won't change to 'standby' if it's at sleep.
Already tried to remove the integration and re-added it back. Restarting/rebooting HA + ATV.

### URL

https://www.home-assistant.io/integrations/apple_tv/

### Version

2024.3.0

### Additional information

Core
2024.3.0
Operating System
12.0
tvOS 17.4

_No response_

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by edmondss** [comment]
> Hi there 👋
> 
> It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:
> 
> https://github.com/home-assistant/core/issues
> 
> Thanks! 👍
> 
> ./Klaas

My apologies, will submit again.
