### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by s6a6n6d6m6a6n** [home-assistant/home-assistant.github.io#31871]
### Feedback

HA finds Obi as possible integration, but when i go to add credentials, it's says invalid authentication. Using the same user/pass and logged into Obi's frontend UI and i know credentials are good. 
What gives?

### URL

https://www.home-assistant.io/integrations/obihai/

### Version

2024.3.0

**Comment by ejpenney** [comment]
Are you specifying the devices IP address or hostname?  It's frequently difficult/impossible to get Home Assistant to reliably resolve hostnames, and (static) IP addresses are always safest.

Is it possible the Home Assistant and Obihai are on different subnets/VLANs that might make it difficult for them to communicate?

And you said you used the same credentials as the front-end, I _assume_ you meant the local device's web portal (logging in via something like http://192.168.1.45 or http://obi200.lan), as opposed to ObiTalk credentials (obitalk.com), correct?  The integration requires the former and cannot use the latter credentials.

If those items don't help:
- What is the device model number?
- Can you enable debug logging* for _homeassistant.components.obihai_ and _pyobihai_ and provide logs from System -> Logs?

To enable debug for a component before it has been configured you will need to add something like this to configuration.yaml then restart Home Assistant:
```
logger:
  logs:
    homeassistant.components.obihai: debug
    pyobihai: debug
```

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by s6a6n6d6m6a6n** [comment]
> Are you specifying the devices IP address or hostname? It's frequently difficult/impossible to get Home Assistant to reliably resolve hostnames, and (static) IP addresses are always safest.
> 
> Is it possible the Home Assistant and Obihai are on different subnets/VLANs that might make it difficult for them to communicate?
> 
> And you said you used the same credentials as the front-end, I _assume_ you meant the local device's web portal (logging in via something like http://192.168.1.45 or http://obi200.lan), as opposed to ObiTalk credentials (obitalk.com), correct? The integration requires the former and cannot use the latter credentials.
> 
> If those items don't help:
> 
> * What is the device model number?
> * Can you enable debug logging* for _homeassistant.components.obihai_ and _pyobihai_ and provide logs from System -> Logs?
> 
> To enable debug for a component before it has been configured you will need to add something like this to configuration.yaml then restart Home Assistant:
> 
> ```
> logger:
>   logs:
>     homeassistant.components.obihai: debug
>     pyobihai: debug
> ```

Your response made me have a lightbulb aha and i think you solved it. Thank you!. I was using the front end credentials instead of the admin panel which is only now open to local access as Expert Mode is no longer available from the UI as Obi 202 is after EOL.  Cheers.
