### ISSUE TITLE
Commands, not a real issue

### ISSUE THREAD

**Issue by janicektrnecka** [home-assistant/home-assistant.github.io#31899]
### Feedback

Hello,
this works over UDP and its not the modbus, Can you direct me where to find a set of commands to get responses (eg in some file on HA, where there is a description which commands return values into entities)

sorry for dull question

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2024.3.1

**Comment by mletenay** [comment]
This is bug repository for the HA web site/documentation.
Please do not file questions here.
And, no there are no "commands" there.

**Comment by mletenay** [comment]
@home-assistant close
