### ISSUE TITLE
New device model released - Kasa KS240

### ISSUE THREAD

**Issue by daveck86** [home-assistant/home-assistant.github.io#31908]
### Feedback

The integration for this recently released wall switch does not work yet. It should be added to the integration and documentation. 
### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.3.1

### Additional information

It keeps asking for Authentication, but my Kasa/TP-Link credentials do not seem to work.  It is a Dual Fan and Light Dimmer.

**Comment by rytilahti** [comment]
This model is not yet supported, you can follow https://github.com/home-assistant/core/issues/111238 for updates. I'll close this as it's not a documentation issue (i.e., we don't document which models and features are _not_ supported).
