### ISSUE TITLE
Auto-charge mode functionality - TechnoVE integration

### ISSUE THREAD

**Issue by velcro22** [home-assistant/home-assistant.github.io#31903]
### Feedback

I love the addition of the integration and its features. The new switch Auto-charge mode is not well documented (other the fact that it exists) and it is not to clear what its functionality is. I was expecting a "soft-switch" to control the ability to allow charging or not from the vehicle but the switch seems to have no effect. Could you provide a bit more details on its functionality and potential use? Tks in advance.

### URL

https://www.home-assistant.io/integrations/technove/

### Version

2024.3.1

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/51928377/98c52e0d-00cb-440d-b4ea-5eff67bfd75a)

You can see on the included image the direct charge is demanded from the vehicle, the auto charge switch is off but the vehicle is still charging (charging status and current display)

**Comment by Moustachauve** [comment]
Hey! It's the same features as in the TechnoVE app for "Recharge automatique". there's no way with the integration yet to stop the charge, so if it's already started it won't stop it.
