### ISSUE TITLE
Awesome! Love IT! + feedback

### ISSUE THREAD

**Issue by IIIdefconIII** [home-assistant/home-assistant.github.io#31909]
### Feedback

Migrated my full homeassistant today the sections mode: So much better now, wondering if we can get iframes working in a section so i can migrate even further.

![image](https://github.com/home-assistant/home-assistant.io/assets/9917659/3ad1a38a-e205-4e29-b876-4befe4eb0cd9)
 

### URL

https://hassist.iiidefconiii.info

### Version

2024.3.1

**Comment by IIIdefconIII** [comment]
Feedback: Would really, nah nevermind, iframes would be very lovely.
Also sometimes it bug a little bitt showing the names and/or icon on the top. would be nice we can also put the name in the center of the top div/banner
like:

                 <ATTIC> center div
ICON1 ICON2 ICON3 ICON4

**Comment by IIIdefconIII** [comment]
would also be very nice to add support for a 5fth colums for ulte widescreen users like me

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by IIIdefconIII** [comment]
> Thank you for reaching out.
> 
> We use GitHub for tracking issues, not for tracking feature requests.
> 
> If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
> 
> Thanks! 👍

- done that this top ic can be closed,

EDITl nevermind its closed xD
