### ISSUE TITLE
Onkyo

### ISSUE THREAD

**Issue by anthony4813** [home-assistant/home-assistant.github.io#31904]
### Feedback

Wondering if there can be a update to the Onkyo intergration to add a unique ID. cant add to a room to have on automatic dash boards 

### URL

https://www.home-assistant.io/integrations/onkyo/

### Version

2024.3.1

**Comment by c0ffeeca7** [comment]
Thank you for reaching out. This GitHub issues tracker is used specifically for tracking documentation issues.

It looks like you want to suggest a feature. For this, please refer to uur [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).
