### ISSUE TITLE
Govee lights local requires HACS afaik

### ISSUE THREAD

**Issue by aafaber** [home-assistant/home-assistant.github.io#31918]
### Feedback

Trying to add this without HACS because it isn’t mentioned in this article but Govee lights local isn’t in the list of integrations. 

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.3.1

**Comment by klaasnicolaas** [comment]
First remove all govee integrations that you installed via HACS.

./Klaas

**Comment by aafaber** [comment]
Thanks, that solved it indeed! Perhaps good to add to the documentation?
