### ISSUE TITLE
Car is not there

### ISSUE THREAD

**Issue by hbothmer** [home-assistant/home-assistant.github.io#31911]
### Feedback

Hi! I am in Germany and have a Volvo XC60 Recharge.
I am using the App but Home Assistant Is not showing anything. Login is succesfull. I am in Germany.

### URL

https://www.home-assistant.io/integrations/volvooncall/

### Version

2024.3.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
