### ISSUE TITLE
cannot_connect

### ISSUE THREAD

**Issue by danfinlay** [home-assistant/home-assistant.github.io#31917]
### Feedback

I get an opaque "cannot connect" error despite the logs showing a successful bearer token being returned from Aladdin.

### URL

https://www.home-assistant.io/integrations/aladdin_connect/

### Version

2024.3.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
