### ISSUE TITLE
Harmony Hub 4.15.330 ?

### ISSUE THREAD

**Issue by DeanAHoule** [home-assistant/home-assistant.github.io#31914]
### Feedback

Is Harmony Hub 4.15.330 supported by this integration?  I enter the Hub IP and Hub Name.... and it immediately fails.  Thanks for any assistant you can offer

### URL

https://www.home-assistant.io/integrations/harmony/

### Version

2024.3.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
