### ISSUE TITLE
[tedee] tedee locks won't lock/unlock together in the same service call

### ISSUE THREAD

**Issue by zarqeon** [home-assistant/home-assistant.github.io#31950]
### Feedback

I have two tedee lock installed on my front door: one of them is a PRO and the other one is a GO, both locks have a device area called "lobby". If I call the lock.lock (or lock.unlock) service with the area "lobby" then I get an error message:
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:1805
First occurred: 9:47:17 PM (12 occurrences)
Last logged: 10:11:48 PM

websocket_api script: Error executing script. Error for call_service at pos 1: Failed to lock the door. Lock <device ID>
```
According to my experimentation, it does not matter which state the locks are in: both locked, one locked - one unlocked, one locked - one semi-locked.

The same behavior happens if I include both lock entities, instead of the area.
Though if I have only one lock in a service call it will work as expected: will lock if unlocked, will unlock if locked, will lock if semi-locked, and won't throw an error message if asked to lock when is in a locked state.

### URL

https://www.home-assistant.io/integrations/tedee/

### Version

2024.3.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
