### ISSUE TITLE
Added Light Support

### ISSUE THREAD

**Issue by pjk33** [home-assistant/home-assistant.github.io#31951]
### Feedback

Please add support for the Govee H706C lights. I would like to be able to set states and run them with triggers. Currently I can only turn it on and off. 

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.3.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
