### ISSUE TITLE
RAIN BIRD RC2 Wi-Fi Controller

### ISSUE THREAD

**Issue by Magnoliowa** [home-assistant/home-assistant.github.io#31969]
### Feedback

Hello, I am trying to choose a rain bird controller for my garden.  Please let me know if the RAIN BIRD RC2 Wi-Fi controller will also integrate with Home Assistant?
does integration only work with the wifi link module and will not work with this controller model?

### URL

https://www.home-assistant.io/integrations/rainbird/

### Version

2024.3.1

**Comment by allenporter** [comment]
I do not have the RC2, but I have heard users reported success with this device e.g. 
https://community.home-assistant.io/t/rainbird-integration/226243/28?u=allenporter

If you run in trouble we can try to diagnose with your help to collect debug data.

If you have further questions i recommend discussing in the community forum e.g. https://community.home-assistant.io/t/rainbird-integration-confirm-working-with-rc2-controller/688759
