### ISSUE TITLE
No device or Entity after successfully installing Opower HA integration

### ISSUE THREAD

**Issue by askarsat** [home-assistant/home-assistant.github.io#31978]
### Feedback

Had Opower integration working fine with PGE login. After backing up Home Assistant config and restoring it, Opower integration no longer initializes PGE entities with "Failed setup, will retry" message (see attached screenshot). From logs, there appears to be a Traceback:

```2024-03-20 08:32:10.641 ERROR (MainThread) [homeassistant.components.opower.coordinator] Unexpected error fetching Opower data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/opower/coordinator.py", line 87, in _async_update_data
    await self._insert_statistics()
  File "/usr/src/homeassistant/homeassistant/components/opower/coordinator.py", line 136, in _insert_statistics
    cost_sum = cast(float, stats[cost_statistic_id][0]["sum"])
                           ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

![image](https://github.com/home-assistant/home-assistant.io/assets/14207230/bef7aec9-28e0-47f6-a872-8d242e44f9ea)

Removing and re-adding Opower intergration in Home Assistant did not help.

Please advise on what troubleshooting steps I can take or provide more information.

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2024.3.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by askarsat** [comment]
@klaasnicolaas Hi Klaas, I did, https://github.com/home-assistant/core/issues/113916. No action on it yet.
