### ISSUE TITLE
Specify Update Interval on the DNS Server

### ISSUE THREAD

**Issue by hauard** [home-assistant/home-assistant.github.io#31976]
### Feedback

The server used for dns lookup, doesn't seems to be updated too often. Specify in the docs how often these servers are updated against main DNS-servers on the internet. Seems like an hour or so

### URL

https://www.home-assistant.io/integrations/dnsip/

### Version

2024.3.1

**Comment by gjohansson-ST** [comment]
That's typically not something we do and also anyone can define their own update frequency by using an automation and calling the `homeassistant.update_entity` service.

**Comment by hauard** [comment]
Hi
Thanks for the quick response !

Just to clarify, updating the entity doesn't make the NS-server to update quicker.

But this is my mistake! I didn't notice the possibility to choose which nameserver to do the lookup-request to when adding a new NS-record to the DNS IP-integration.

Using Google's servers did a lot to improve the time from a NS-record was edited, to the Google DNS-servers being updated.

An improvement to the integration would be to use eg. Google NS (8.8.8.8 / 8.8.4.4) as default lookup-server. because the OpenDNS-servers seems to have up to an hour update interval.

**Comment by gjohansson-ST** [comment]
I didn't understand your issue but now I do.
We don't control the refresh rate of dns-servers and also ttl on dns records should be what is defining this.

We won't change the NS servers as they are special to use the `myip` dns entry but it's good to hear your particular issue is solved by using other NS servers.
