### ISSUE TITLE
How change the google nest password in HA

### ISSUE THREAD

**Issue by MHBradley** [home-assistant/home-assistant.github.io#31991]
### Feedback

I am looking for information on how to update my Google Nest password.  I needed to change my Nest password I was thinking I could just update the password in the HA Yaml but I do not know how too... Thanks for any advise.

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.3.1

**Comment by MHBradley** [comment]
Sorry I am new to this... not sure what a code owner command is, sorry if I posted in the wrong place. sure I reenter?

**Comment by allenporter** [comment]
Hi, this is not a support forum. I recommend moving to the community forum or look up Google support. Home assistant has nothing related to your nest password.
