### ISSUE TITLE
Improvements to the integration

### ISSUE THREAD

**Issue by AreolaGrande** [home-assistant/home-assistant.github.io#31997]
### Feedback

It would be great if we could add in the following values to be able to monitor and control:
1) Maintenance - Have an element we can track to alert us of filter replacements
2) Alerts - entity to track alert codes.

### URL

https://www.home-assistant.io/integrations/izone/

### Version

2024.3.1

**Comment by Swamp-Ig** [comment]
I haven't really been maintaining the integration much of late. It's quite hard to get stuff changed in HA. I started work on pulling it out of HA as a HACS plugin but never got very far with it.

In any case, this is the wrong location for feature requests.
