### ISSUE TITLE
some sensors are not pick up

### ISSUE THREAD

**Issue by svenduerinckx** [home-assistant/home-assistant.github.io#32005]
### Feedback

below sensors for Belgium are not picked up via MQTT :

highest_peak_pwr_ts
peak_pwr_last_q
highest_peak_pwr

Eth-Dongle-Pro is sending the values via MQTT.

### URL

https://www.home-assistant.io/integrations/dsmr_reader/

### Version

2024.3.2

**Comment by klaasnicolaas** [comment]
Hi there  👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
