### ISSUE TITLE
ZHA "OTA firmware updates" section is outdated

### ISSUE THREAD

**Issue by cremor** [home-assistant/home-assistant.github.io#32003]
### Feedback

The section "OTA firmware updates" should be updated to mention the updates via the HA UI which are available since HA 2024.2

### URL

https://www.home-assistant.io/integrations/zha/

### Version

2024.3.2

### Additional information

Please also update which manufacturer are supported - and which of those are enabled by default. See https://github.com/zigpy/zigpy/blob/dev/zigpy/config/defaults.py#L26

**Comment by cremor** [comment]
Looks like there is already a PR for this: #28895

**Comment by Hedda** [comment]
> Looks like there is already a PR for this: #28895

Yes, but review(s) with feedback/input is needed as originally submited 12th of September 2023 -> https://github.com/home-assistant/home-assistant.io/pull/28895

**Comment by erkr** [comment]
Please spent some time updating the OTA documentation. I really like to know what are the correct usage in 2024.5+.

**Comment by Hedda** [comment]
@erkr You can review and post feedback in this open pull request here which aims to at least try to update OTA documentation:

- https://github.com/home-assistant/home-assistant.io/pull/28895

Again, that PR was originally submitted in the beginning of September 2023 but I did update/rewrite it a couple of months ago.

So I did already spend time updating the OTA documentation but it does get outdated when new PRs are not quickly reviewed.

Note that PR reviews can be done by anyone, everybody can help out reviewing PRs and it is encouraged that you do so too, see:

https://developers.home-assistant.io/docs/review-process/

FYI, GitHub has instructions here on how-to comment on a pull request:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request

**Comment by erkr** [comment]
@Hedda 
As I'm not knowledgeable on the new OTA implementation, my review only covers if the new OTA description is understandable. Yes it looks good for me. It answered several of my questions 😊

**Comment by cremor** [comment]
Fixed by #28895
