### ISSUE TITLE
AOSmith HPSX-50-DHPT 200 water heater works with integration

### ISSUE THREAD

**Issue by fghorow** [home-assistant/home-assistant.github.io#32002]
### Feedback

I'm unsure if the listed working model HPSX-50-DHPT is meant to cover my model with a "200" suffix, so I thought I'd file this documentation feedback to let the integration author decide.

### URL

https://www.home-assistant.io/integrations/aosmith

**Comment by bdr99** [comment]
Thanks for opening this issue. Yes, the HPSX-50-DHPT is meant to cover that model.

**Comment by bdr99** [comment]
@home-assistant close
