### ISSUE TITLE
DNSMasq hassio Add-on config is unclear

### ISSUE THREAD

**Issue by naveci** [home-assistant/home-assistant.github.io#3200]
The DNSMasq add-on has unclear documentation in case you want to add multiple hosts. I would've liked updating the documentation but after puzzling with this (and googling) for almost 45 minutes, I still haven't figured out why the config is accepted, but then reduced to one host. Is this an user-error or would this be a bug?

**Comment by fabaff** [comment]
> hosts (Optional): A list of hosts to resolve it static.

What unclear here?

**Comment by Landrash** [comment]
Closing since there's been no response to this issue.

**Comment by naveci** [comment]
My apologies guys,

I've been so busy with work and study, that I've had no time for any of the fun stuff lately such a Hass ;)

anyway, the documentation doesn't clearly specify how to add multiple hosts. The following config seems to be accepted, but then after saving, it's reduced to one host. Therefor my question whether it's an config error or bug in the add-on.

`{
  "defaults": [
    "8.8.8.8",
    "8.8.4.4"
  ],
  "forwards": [
    {
      "domain": "te.st",
      "server": "172.16.2.22"
    }
  ],
  "hosts": [
    {
      "host": "unifi.te.st",
      "ip": "172.16.200.1",
      "host": "db01.te.st",
      "ip": "172.16.200.3",
      "host": "plex01.te.st",
      "ip": "172.16.200.4"
    }
  ],
  "interface": "eth0"
}`

Kind regards.
