### ISSUE TITLE
Tuya docs wrong 

### ISSUE THREAD

**Issue by TimMensch** [home-assistant/home-assistant.github.io#32009]
### Feedback

The Tuya docs page says all you need is a user code. The actual "add device" page for Tuya asks for an access ID and secret.

I managed to figure out how to do this at one point, but I can't for the life of me find it again. So now I can't add a new device and I have no idea how to add a device! 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.3.3

### Additional information

I'm on 2024.1.2/Docker.

**Comment by TimMensch** [comment]
Fun times. The Tuya site doesn't let you see the access ID/Client ID if you're on a mobile browser (!!!).

Found the codes, but the instructions are still wrong. And the Tuya login doesn't work either. Maybe it's the Smartlife login!?

**Comment by TimMensch** [comment]
Yes, the Smartlife login. It really should be more clear.

**Comment by frenck** [comment]
> Tuya asks for an access ID and secret.

This can mean either of two things:

- You are running an older version of Home Assistant. Please upgrade, as this changed a few months ago.
- You are not using the built-in version of the Tuya integration but installed it as a custom integration. In that case, this documentation doesn't apply. Please consult the custom integration documentation.

../Frenck
