### ISSUE TITLE
Preferent stations

### ISSUE THREAD

**Issue by CapadY** [home-assistant/home-assistant.github.io#32013]
### Feedback

I would like to see an option to have about 10 preferent stations so I haven't to scroll dosens of pages to find the station I want.

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2024.3.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
