### ISSUE TITLE
Does  not work properly 

### ISSUE THREAD

**Issue by mcintoi** [home-assistant/home-assistant.github.io#32014]
### Feedback

Installed this integration over a year ago., Straight away it was reporting power issues for a couple of seconds before rectifying itself.,   Based on this information I bought a UPS Battery for my Pi 4.  still same issues???   I've even changed the power socket and cable and still get regular power issues reported in HA.,  but why?  I have an inline battery UPS on the PI itself in between the raw power supply and the PI.,   its up and down like a yo yo     but i have a UPS in between the pi and the power supply ? 

### URL

https://www.home-assistant.io/integrations/rpi_power/

### Version

2024.3.3

### Additional information

![pi power](https://github.com/home-assistant/home-assistant.io/assets/71784782/0e639b1c-4714-4416-96be-955fcd12305d)

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
