### ISSUE TITLE
Dashboard Sections

### ISSUE THREAD

**Issue by megantereon** [home-assistant/home-assistant.github.io#32022]
### Feedback

Add an option to arrange Sections by columns instead of by rows.   Sections have constant width but variable height so it would be better to add actions with the same width in columns instead of rows to fill the space on a  dashboard. A Section with large height next to a Section with small height in the same row isn't the right way to arrange them. 

### URL

https://www.home-assistant.io/dashboards/sections/

### Version

2024.3.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by Ixitxachitl** [comment]
You realize the "Provide Feedback" link on the documentation page leads here, if you don't want feature suggestions on github you may want to remove that link.
