### ISSUE TITLE
Raspberry Pi Power Supply Checker

### ISSUE THREAD

**Issue by mcintoi** [home-assistant/home-assistant.github.io#32029]
### Feedback

this only works with one PI?   I have 3.,      how do i monitor all three when I can only have one instance of Raspberry Pi Power Supply Checker running ???

### URL

https://www.home-assistant.io/integrations/rpi_power/

### Version

2024.3.3

### Additional information

why does this integration only work with one PI ?

**Comment by frenck** [comment]
Closing as a duplicate of #32015

**Comment by mcintoi** [comment]
great support there.,  not .,    integration deleted.,    thanks for you help/. 

you closed # 32015 as its a duplicate of #32029
and then closed #32029 as its duplicate of ##32015 

like I said fantastic customer support .,

**Comment by frenck** [comment]
> you closed # 32015 as its a duplicate of https://github.com/home-assistant/home-assistant.io/issues/32029
and then closed https://github.com/home-assistant/home-assistant.io/issues/32029 as its duplicate of #https://github.com/home-assistant/home-assistant.io/issues/32015

I did not, I think you didn't look correctly. #32015 is open, and can be picked up by any contributor that wants to contribute to our open source project.

> like I said fantastic customer support .,

This ain't a support channel. You have submitted documentation feedback.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
