### ISSUE TITLE
Dont bother with this integration

### ISSUE THREAD

**Issue by mcintoi** [home-assistant/home-assistant.github.io#32030]
### Feedback

it doesnt work.,   and when you try and raise a ticket you get fobbed off.,    dont bother., 

### URL

https://www.home-assistant.io/integrations/rpi_power/

### Version

2024.3.3

### Additional information

Meh

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by swetoast** [comment]
Hello thnx for your feedback, its important to know your way around github, so hey try again and raise a ticket where it belongs 

if you want something you can run on every raspberrypi etc 

https://github.com/swetoast/Raspberry-Pi-Power-Usage-Monitor

however save the attitude in that case
