### ISSUE TITLE
Fault 2: XML::Parser Perl module is not installed

### ISSUE THREAD

**Issue by dfrye** [home-assistant/home-assistant.github.io#32066]
### Feedback

Got error:
Fault 2: XML::Parser Perl module is not installed

Is this something I need to have installed in HomeAssistant?

### URL

https://www.home-assistant.io/integrations/webmin/

### Version

2024.3.3

**Comment by autinerd** [comment]
Hello, the Perl module has to be installed on the server where Webmin is running, either via the system package manager or via CPAN.

**Comment by dfrye** [comment]
I had the "Perl Modules" Webmin package already installed. Finally figured out I had to use it to install XML::Parser. Then this worked. FYI for others, once installed all of the sensors (loads and memory) are disabled and you will have to enable them one by one in the Webmin device settings. They may take awhile to actually show up with data.

My biggest issue was not knowing about "Perl Modules" since I have never used it before.
