### ISSUE TITLE
Auth for Shelly PM Mini Gen 3 not working

### ISSUE THREAD

**Issue by ThomasCr** [home-assistant/home-assistant.github.io#32072]
### Feedback

I cant add my Shelly PM Mini Gen 3 with a password set - I get every time access denied and need to reenter the password.
I verified the password I enter - it is correct.

![grafik](https://github.com/home-assistant/home-assistant.io/assets/226670/be8fd2dd-d2fb-49a5-a67d-df6fea232724)

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2024.3.3

### Additional information

Current Firmware 1.2.2 is installed

**Comment by bieniu** [comment]
This is a documentation repository, you should open an issue here https://github.com/home-assistant/core/issues Thanks!
