### ISSUE TITLE
Manual setup using console.actions.google.com is no longer working

### ISSUE THREAD

**Issue by markusmauch** [home-assistant/home-assistant.github.io#32073]
### Feedback

Manual setup using console.actions.google.com is no longer working. When clicking the 'New Project' button nothing happens.

### URL

https://www.home-assistant.io/integrations/google_assistant/

### Version

2024.3.3

**Comment by TheRealSimon42** [comment]
Confirming, not possible anymore to create projects as it seems…. See here for a German Blog-Post describing the problem (no solution): https://www.simon42.com/home-assistant-google-home/#moeglicher-fehler-500-beim-erstellen-des-projektes-actions-console

**Comment by garnbleiche** [comment]
Is the instructions for manual setting up Google Assistant still correct? Can anyone confirm that?

**Comment by markusmauch** [comment]
Found out that my country of residence was not set in the Google console settings. With that everything works as expected...
