### ISSUE TITLE
This page doesn't work for adjusting "views" as far as I can tell

### ISSUE THREAD

**Issue by dkuchay** [home-assistant/home-assistant.github.io#32094]
### Feedback

Bought home assistant yellow on crowd supply campaign and I am still trying to figure out how to adjust the gui. Devices.are in and mostly accounted for. 

This page suggests I click a pencil in the upper right and select a "Add view" button. When I click the pencil I get a dialog pop up box that asks me about rooms to display. I can't seem to find a button that deals with adding a view. I am trying to make "Tabs" at the top of the dashboard. Looking into this and I see these are called "views". Please let me know what I am doing wrong. Spent time on the interactive demo and the linked pages but they don't really show the context I am looking for. Showing the visual editor on that pop up dialog really shows markdown or json or code. 

### URL

https://www.home-assistant.io/dashboards/views/

### Version

2024.3.3

**Comment by dannytsang** [comment]
@dkuchay would you be able to attach a screenshot of what you're seeing?

**Comment by dkuchay** [comment]
After restarting the app I was able to follow the example and it worked as expected. Please disregard.
