### ISSUE TITLE
Please add this help work

### ISSUE THREAD

**Issue by tju79** [home-assistant/home-assistant.github.io#32098]
### Feedback

https://github.com/jeremywillans/ha-rest980-roomba

### URL

https://www.home-assistant.io/integrations/roomba/

### Version

2024.3.3

**Comment by tju79** [comment]
https://community.home-assistant.io/t/irobot-roomba-i7-configuration-using-rest980/161175

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
