### ISSUE TITLE
Add mac address for devices registry

### ISSUE THREAD

**Issue by Sebdomsan** [home-assistant/home-assistant.github.io#32090]
### Feedback
Add mac address for devices registry for IPP integration
I am trying to cut down on the number of duplicate entries in my HA panel
I have a Omada network controller that pulls the devices in and lets me monitor uptime and data throughput
A few devices have merged with other integrations due to them having the mac address in the device registry.
it would be nice to have this so instead of having
"Printer" & "Printer connection" as separate devices they would show as one entity.

### URL

https://www.home-assistant.io/integrations/ipp/

### Version

2024.3.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
