### ISSUE TITLE
Not that clear how to use

### ISSUE THREAD

**Issue by GerhardKreuzer** [home-assistant/home-assistant.github.io#32100]
### Feedback

Hi,
sorry, but it isn't clear, how to use a notification in an automation.
I add the lines in configuration.yaml, but I never found a thing I can use in a automation. Is it an Entity, Service ??

A nice sample will be, 'Seend a mail at a dedicated time, easy to test and universal enough  to start from.

With best regards
Gerhard

### URL

https://www.home-assistant.io/integrations/smtp/

### Version

2024.3.3

### Additional information

???

**Comment by dannytsang** [comment]
It's a service call. In the example, it created the SMTP with name
```
notify:
  - name: "NOTIFIER_NAME"
```

This should create a notify "service" with the same name and which you can use in a service call e.g `- service: notify.NOTIFIER_NAME`

The first example is not the simplest example to show this off so I will have a think about your suggestion.
