### ISSUE TITLE
Adding Devices

### ISSUE THREAD

**Issue by ZadvornOff** [home-assistant/home-assistant.github.io#32103]
### Feedback

Is it possible to add a Xiaomi smart humidifier2 device to xiaomi miio. Now my device is being detected, but it says that: there are no devices or objects. And also writes: Failed to configure.

### URL

https://www.home-assistant.io/integrations/xiaomi_miio/

### Version

2024.3.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
