### ISSUE TITLE
WIFI Dual Meter Total energy

### ISSUE THREAD

**Issue by Automatic-Bob** [home-assistant/home-assistant.github.io#32104]
### Feedback

The Tuya WIFI Dual Meter Total energy meter does not pick up on the correct output. It needs to pick up total power, but it picks up Forward Energy. Please advise if this can be corrected as there is only one entity listed.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.3.3

**Comment by Automatic-Bob** [comment]
Hi! All,

Please advise if there is any news regarding this query ?

Regards
Bob.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
