### ISSUE TITLE
Documentation should include that this is a Paid app

### ISSUE THREAD

**Issue by XxInvictus** [home-assistant/home-assistant.github.io#32115]
### Feedback

It would be useful for the documentation to include that this Notifications for Android TV app is a paid app which has a hard paywall where the notifications become unusable through the "**premium**" popup. 

Review of the Google Play Store reviews shows the developer has even been shown to be actively hostile towards people who criticise that the free version of the app is unusable.

### URL

https://www.home-assistant.io/integrations/nfandroidtv/

### Version

2024.3.3

### Additional information

- Based on the reviews this app is unusable in the free state anymore.
![image](https://github.com/home-assistant/home-assistant.io/assets/3955293/4969b3be-0f95-42b5-b8b8-89c73aa48f90)
![image](https://github.com/home-assistant/home-assistant.io/assets/3955293/e4d1269e-698b-4c8d-8f14-4c1c84e98185)
![image](https://github.com/home-assistant/home-assistant.io/assets/3955293/68a69e5c-69ee-4e80-b2f0-2736adab404b)

**Comment by tkdrob** [comment]
I took a look to see if anything changed on the Android TV or Fire TV apps. From reading this, I was led to believe that the dev switched it to being paid from free. It turns out it is still free for those devices from my findings. The phone app was always paid. This is already mentioned in the 3rd paragraph of the docs from the link you provided. What exactly is not clear about it?

**Comment by XxInvictus** [comment]
My apologies, my understanding of the complaints was that the banner was TV side, I did not fully understand that the banner on the TV being contested was instantiated from the Phone app side despite displaying on the TV. Particularly the complaint of "banner every hour" led me to believe that this was baked into the TV app. That is entirely my mistake and I apologise for wasting your time!
