### ISSUE TITLE
Authentication broken

### ISSUE THREAD

**Issue by tamaswallner** [home-assistant/home-assistant.github.io#32111]
### Feedback

Since the latest update the authentication stopped working with invalid credentials error (the credentials are correct and works in the hotpoint app)

### URL

https://www.home-assistant.io/integrations/whirlpool/

### Version

2024.4.0

**Comment by mkmer** [comment]
Dup: https://github.com/home-assistant/core/issues/114463

**Comment by mkmer** [comment]
@home-assistant close
