### ISSUE TITLE
Provide warning that you cannot edit origin/destination Waze Travel Time after creation.

### ISSUE THREAD

**Issue by Taomyn** [home-assistant/home-assistant.github.io#32123]
### Feedback

Provide a warning that you cannot edit origin/destination Waze Travel Time after its creation. This is a huge shortcoming especially with an integration that can be added through HA directly now i.e. no manual file editing. For those of us that maybe have a destination that regularly changes, this means having to delete then recreate it each time we want to make a change.

### URL

https://www.home-assistant.io/integrations/waze_travel_time/

### Version

2024.3.3

**Comment by eifinger** [comment]
Will be obsolete when https://github.com/home-assistant/core/pull/114885 is merged

**Comment by eifinger** [comment]
@home-assistant close
