### ISSUE TITLE
Add hourly electricity prices in Tibber integraton

### ISSUE THREAD

**Issue by kees-jans** [home-assistant/home-assistant.github.io#32145]
### Feedback

I am using the Tibber integration in Home Assistant to use energy, where possible, at the most favorable hours.
At this moment the Tibber integration (among other things) provides the lowest price at the current day without specifying the specific hour(s).
The disadvantage of this is that the usability of this price becomes increasingly lower throughout the day. If the lowest price is in the past, it isn't of much value if you want to start using devices on low-price hours. If the lowest price is in the evening and, based on this information, you i.e. charge your car in the evening, it might well be that a few hours later (the first hours of the next day) prices are even lower.
It would be very useful imho if an attribute can be added to the Tibber integration that showed the lowest price for the NEXT 12 hours. Automation is all about looking ahead, right?😏
It would be even better if the Tibber integration provides the hourly rates for the next 12 hours.
Then you can calculate (or automate) yourself the best hours for using/charging your devices.
I hope that this  feedback will help you improve even further.
Please keep up the good work!

### URL

https://www.home-assistant.io/integrations/tibber/

### Version

2024.3.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
