### ISSUE TITLE
 Images for Traccar objects

### ISSUE THREAD

**Issue by fuzzznet** [home-assistant/home-assistant.github.io#32140]
### Feedback

Previously, I specified images of the monitored objects in the Known_devices.yaml file. How can I assign my images to objects after updating?

![image](https://github.com/home-assistant/home-assistant.io/assets/73440947/d02bd0c0-44f6-4f75-9b89-cef4ea60abbb)

### URL

https://www.home-assistant.io/integrations/traccar_server/

### Version

2024.3.3

**Comment by ludeeus** [comment]
You can use the customize section of your configuration like with all other integrations 👍 
https://www.home-assistant.io/docs/configuration/customizing-devices/
