### ISSUE TITLE
Home Assistant demands Python 3.12

### ISSUE THREAD

**Issue by MatsA** [home-assistant/home-assistant.github.io#32159]
### Feedback

Hi !
Did an install to a RPi following these instructions 
https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-core
but had to upgrade to Python 3.12 to match HA 2024.4.0
/Mats

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.4.0

**Comment by klaasnicolaas** [comment]
Fixed with #32150

**Comment by MatsA** [comment]
Hi ! 
The thing is that the post refers to an install on a RPi and the command  "sudo apt-get install -y python3 ......." which will install Python 3.11 **not** 3.12..... couldn't find a better way then compiling Python 3.12 myself, but that didn't work......
