### ISSUE TITLE
panel_iframe YAML configuration is deprecated.

### ISSUE THREAD

**Issue by nromyn** [home-assistant/home-assistant.github.io#32162]
### Feedback

Documentation should be updated to direct users to UI config 

As of Core version 2024.4.0, a warning is displayed:
> Configuring iframe Panel using YAML is being removed.
> Your existing YAML configuration has been imported into the UI automatically as a regular dashboard.
> Remove the panel_iframe configuration from your configuration.yaml file and restart Home Assistant to fix this issue.

### URL

https://www.home-assistant.io/integrations/panel_iframe/

### Version

2024.4.0

### Additional information

As a slight complaint, the warning in home assistant doesn’t really help me; `cat *.yaml | grep iframe ` doesn’t return anything; my dash boards are all automatic, no YAML; and I have deleted the File Editor dashboard, which is all I could find that’s got an iframe but it still is present.

**Comment by neomvll** [comment]
Same here. Now we need to follow this guide: https://www.home-assistant.io/dashboards/iframe/

"type: iframe
url: https://www.home-assistant.io
aspect_ratio: 75%"

But I dont know where to put this code :/

**Comment by piitaya** [comment]
You must go to dashboard settings (https://my.home-assistant.io/redirect/lovelace_dashboards/) and create a new "webpage" dashboard.
I agree, the documentation must be updated to better explain the migration steps 🙂

**Comment by neomvll** [comment]
> You must go to dashboard settings (https://my.home-assistant.io/redirect/lovelace_dashboards/) and create a new "webpage" dashboard. I agree, the documentation must be updated to better explain the migration steps 🙂

Thanks, but I'm using YAML config, so I can't configure dashboards by lovelace interface

**Comment by neomvll** [comment]
solved!! thanks for the help!

**Comment by c0ffeeca7** [comment]
Thank you for the issue, @nromyn, and for jumping in, @neomvll and @piitaya 
Closing this as addressed by #32221.

**Comment by TrevisGordan** [comment]
@neomvll hey - how did you solve it (via config configuration.yaml)?

**Comment by neomvll** [comment]
> @neomvll hey - how did you solve it (via config configuration.yaml)?

After the last major update(2024.4), all panel_iframe was moved to new place: Configuration -> dashboards
If you not found your webpages in config -> dashboards, just add the webpages you need clicking on "add dashboard" -> webpage
Even if your config is all by YAML, like I did, the webpages will be added by this way too.

After you configure all your webpages/dashboards, you can delete/comment the panel_iframes lines in yaml configuration
