### ISSUE TITLE
Fyta hub requirement instead of just sensors. Docs improvement opportunity

### ISSUE THREAD

**Issue by dimitrieh** [home-assistant/home-assistant.github.io#32174]
### Feedback

The docs could be improved to state whether the Fyta hub is required or not. See the following excerpt from the website of Fyta:

> What is the FYTA Hub? And do I need it? | It depends on your needs. You can easily connect the FYTA Beams via Bluetooth. However, a large number Beams in a Bluetooth-only configuration affects the user experience. To access the data without a hub, you need to open the app near the Beams. The more Beams you have, and the less often you open the app, the longer the data download will take. With a Wi-Fi hub, data is being synchronised every hour.

https://fyta.de/en

Looking at the code it seems it needs to authenticate with the fyta API service through the internet. Assumption is that the data from the sensors first need to be uploaded to the Fyta cloud through either the Fyta hub or the Fyta app on your phone. Something that could perhaps also be done in the future through home assistant (in that way removing the need for the Fyta hub)?

### URL

https://www.home-assistant.io/integrations/fyta/

### Version

2024.4.0

**Comment by dontinelli** [comment]
Hi @dimitrieh 
Thank you for your comment. It indeed could make sense to amend the documentation with regards to the hub-requirement. As a matter of fact, the data is uploaded from the beam via hub to the server, where it is aggregated for the app (e.g. plant status). The beam itself only provides raw measurement data, the hub only the wifi credentials (https://discord.com/channels/1052218149489094676/1052218150193725452/1225774568061407312). Insofar I do not think that it will ever be possible to replace hub by HA. A direct reading of the beam current measurements similar to the live mode in the app maybe.

**Comment by dimitrieh** [comment]
@dontinelli created a quick PR https://github.com/home-assistant/home-assistant.io/pull/32176

**Comment by dontinelli** [comment]
> @dontinelli created a quick PR #32176

We both had the same idea at the same time...
