### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by Denox78** [home-assistant/home-assistant.github.io#32188]
### Feedback

Hi

My rituals integration stopped working since few days.

I tried to remove / re add it but can’t login

Can someone help ?
Thanks

### URL

https://www.home-assistant.io/integrations/rituals_perfume_genie/

### Version

2024.4.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
