### ISSUE TITLE
Add note about host name if using Add-On

### ISSUE THREAD

**Issue by daelsc** [home-assistant/home-assistant.github.io#32187]
### Feedback

I imagine most people are configuring this with the NUT server as a Home Assistant add-on.  It would be great to include a note about setting the host name, as is done in the Add-On documentation.  I stumbled with this for a while.  As written in the add on documentation:

    The host a0d7b954-nut can be used to allow Home Assistant to communicate directly with the addon.

Link to the addon: https://github.com/hassio-addons/addon-nut

### URL

https://www.home-assistant.io/integrations/nut/

### Version

2024.4.1

**Comment by frenck** [comment]
The add-on you refer to, is a third-party add-on, which is not supported by the Home Assistant project.

This belong in the add-on documentation of the particular add-on, and not the Home Assistant docs.

../Frenck
