### ISSUE TITLE
Islamic_prayer_times

### ISSUE THREAD

**Issue by Salimphotography** [home-assistant/home-assistant.github.io#32180]
### Feedback

Thanks this integration, Would like to get Dubai Dubai-based calculation

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2024.4.1

**Comment by SD1971** [comment]
Dear friend, there is an error with Diyanet, only isha prayer time, according to the Diyanet Netherlands site, there is normally a difference of 11 minutes in Utrecht City (https://namazvakitleri.diyanet.gov.tr/tr-TR/13975/utrecht-icin-namaz-vakti) , can this be corrected?

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
