### ISSUE TITLE
update documentation for SQL integration about "state of entity X ago" for mariaDB

### ISSUE THREAD

**Issue by felixmxr** [home-assistant/home-assistant.github.io#32198]
### Feedback

in the section "state of entity X ago" the SQL code is only valid for mysql installations. the "strftime" function only exists for mysql databases.

for maria db the following should be used
`SELECT
        states.state
      FROM
        states
        INNER JOIN states_meta ON
          states.metadata_id = states_meta.metadata_id
      WHERE
        states_meta.entity_id = 'sensor.watermeter_value'
        AND last_updated_ts <= (UNIX_TIMESTAMP() - 24*3600)
      ORDER BY
        last_updated_ts DESC
      LIMIT
        1;`

### URL

https://www.home-assistant.io/integrations/sql/

### Version

2024.4.1

**Comment by felixmxr** [comment]
pull request
#32199

**Comment by gjohansson-ST** [comment]
Just open a PR next time if you intend to fix it. No need to open an issue first. 
Thanks 👍
