### ISSUE TITLE
Access to door unlock API on Ezviz HP7 

### ISSUE THREAD

**Issue by tajw662719** [home-assistant/home-assistant.github.io#32207]
### Feedback

New Ezviv HP7 ( and Sd7 ancillary Screen) both enable unlocking of doors via electronic latch. Would be good to access via HA,  even though firmware doesn't support RTSP for video

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2024.4.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
