### ISSUE TITLE
Controlling chime volume

### ISSUE THREAD

**Issue by shadow7412** [home-assistant/home-assistant.github.io#32203]
### Feedback

I'd love to write an automation that muted the chime linked with the doorbell. Is it possible to add the chime setting to this integration?

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.4.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by starkillerOG** [comment]
Currently not possible because their is no such API command.
You could request Reolink to add such an API command to their firmware by contating reolink support.

**Comment by shadow7412** [comment]
> Thanks for coming back. Sincerely sorry for the inconvenience caused to you.
> 
> I appreciate you sharing open feedback with us. We'd feed back your valuable experience of the setup automation mute chime our product team, so we can continually improve our products.We have been diligently working on implementing some selected user requests. And I’m honored to have yours added to the list. Please kindly understand that bug fixes are our top priority and then user requests or feature requests. So it may take some time to see yours become true. Please stay tuned!

Sounds like they agree it's a worthy feature. I'll keep you posted.
