### ISSUE TITLE
Shelly Wall display not showing thermostat (Climate) details in HA

### ISSUE THREAD

**Issue by marcalanbaker** [home-assistant/home-assistant.github.io#32201]
### Feedback

Hi, I have a Shelly wall display, one of the features is being able to enable a thermostat on the display, i had this pulling into HA since the recent 2 updates I am no longer able to see the associated climate entity in HA, not sure if it was the Shelly display firmware update or the HA update, I can still see all the other updates associated with the device.

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2024.4.1

**Comment by bieniu** [comment]
This is a documentation repository and your problem is not related to the documentation. Please open an issue [here](https://github.com/home-assistant/core/issues) and attach [diagnostics](https://www.home-assistant.io/integrations/diagnostics/) file and a debug log file for Shelly integration.
