### ISSUE TITLE
AVM Repeater 2400 not working

### ISSUE THREAD

**Issue by Wildvirus** [home-assistant/home-assistant.github.io#32224]
### Feedback

Fritz!Box tools have to be reconfigured after every HA restart

I use a Fritz!Box 7590 with three repeaters
- Repeater 1750E, Fritz!OS 07.32
- Repeater 6000, Fritz!OS 7.57
- Repeater 2400, Fritz!OS 7.58

All three only know the login with a password. It is not possible to log in with a user ID, despite Mesh with the 7590. 
HA recognizes the 1750E and 6000 without any problems after a restart. Only the 2400 requires a reconfiguration after every HA reboot. 
How can I also permanently configure the 2400 repeater?

HA-Environment:
Core 2024.4.2
Supervisor 2024.04.0
Operating System 12.1
Frontend 20240404.1

### URL

https://www.home-assistant.io/integrations/fritzbox/

### Version

2024.4.2

**Comment by mib1185** [comment]
You've opened a feedback report for the documentation, please open an issue report to the [core repository](https://github.com/home-assistant/core/issues) and include there the [debug logging](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics) and the [diagnostics](https://www.home-assistant.io/integrations/diagnostics) data for this integration.

Further please mention the correct integration in this report (_AVM Fritz!Tools `fritz`, not AVM Fritz!SmartHome `fritzbox`_)

Note: it is better to drag the log into the comment (_which will add it as an attachment_) and not copy paste as it is hard to read logs in GitHub.

thx 👍
