### ISSUE TITLE
can not add tailscale to homeassistant (run on docker)

### ISSUE THREAD

**Issue by duycop** [home-assistant/home-assistant.github.io#32237]
### Feedback

tailnet* ok
api key ok
but result is: Invalid authentication

### URL

https://www.home-assistant.io/integrations/tailscale/

### Version

2024.4.2

### Additional information
mydocker: homeassistant/home-assistant
_No response_

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
