### ISSUE TITLE
Floors are a great addition - Can we please have ability to EDIT them after creation?

### ISSUE THREAD

**Issue by NickInManchester** [home-assistant/home-assistant.github.io#32256]
### Feedback

My very first floor, I forgot to assign it a level. No way currently to edit the floor information after creation. Chnage the name or assigned level etc. ?

### URL

https://www.home-assistant.io/docs/organizing/floors/

### Version

2024.4.2

**Comment by klaasnicolaas** [comment]
You can edit floors with the 3 dots on the right side.

./Klaas

**Comment by NickInManchester** [comment]
Thx. I've missed that.
