### ISSUE TITLE
Non relative times

### ISSUE THREAD

**Issue by dales** [home-assistant/home-assistant.github.io#32276]
### Feedback

Is it possible to show exact times, like 23 minutes until Shkia or candles lighting in 30 minutes....it would also help that way to check the configuration to see that my definition of halachik time actually matches the calculation

### URL

https://www.home-assistant.io/integrations/jewish_calendar/

### Version

2024.4.2

### Additional information

This is an amazing addon btw

**Comment by tsvi** [comment]
Please see the home assistant docs for how timestamp sensors are displayed.

https://www.home-assistant.io/dashboards/entities/#format

**Comment by tsvi** [comment]
@homeassistant close

**Comment by tsvi** [comment]
@home-assistant close

**Comment by dales** [comment]
@tsvi thank you. I'm relatively new on HA and just didn't see this in visual editor but added it to my yaml and it works. Shkoach
