### ISSUE TITLE
Verisure Integration does not work in Spain

### ISSUE THREAD

**Issue by tomeurp** [home-assistant/home-assistant.github.io#32270]
### Feedback

Verisure integration does not work in Spain, it returns invalid credentials error when I know for sure they are correct (I can log into the web interface)

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2024.4.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
