### ISSUE TITLE
Missing information in the Husqvarna documentation

### ISSUE THREAD

**Issue by gimmel** [home-assistant/home-assistant.github.io#32295]
### Feedback

I used to use the HACS implementation and have now switched to HA's own version. Unfortunately, basic information on how to start the mower and send it back to the dock is missing.
In the meantime I have found the services in Homeassistant, but unfortunately they do not work and/or report a 404 error. Example calls would be helpful.

### URL

https://www.home-assistant.io/integrations/husqvarna_automower/

### Version

2024.4.3

**Comment by Thomas55555** [comment]
This is not part of the integration documentation. Infos can be found here: 
https://www.home-assistant.io/integrations/lawn_mower/

**Comment by Thomas55555** [comment]
@home-assistant close

**Comment by gimmel** [comment]
> This is not part of the integration documentation. Infos can be found here: https://www.home-assistant.io/integrations/lawn_mower/

Oh sorry, I thought that is a part of the integration. Didn’t know that mowers are part of the home assistant structure. There are still documentations out there that use vacuums to control mowers.
My fault.
