### ISSUE TITLE
How to select language for sensor names

### ISSUE THREAD

**Issue by Darsma** [home-assistant/home-assistant.github.io#32301]
### Feedback

In description there are sensors named in English but when I add Fronius integration all sensors are in local language. How should I add this integration if I want to have english sensor names?

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2024.4.3

**Comment by klaasnicolaas** [comment]
Change the language of Home Assistant to English and then add the integration?

./Klaas

**Comment by Darsma** [comment]
Exactly. I was changing language just for user, but when changed in Settings -> System -> General -> Language it worked. Thanks!
