### ISSUE TITLE
//Aussie Broadband metrics that relate to your service

### ISSUE THREAD

**Issue by EQUALIT-CG** [home-assistant/home-assistant.github.io#32338]
### Feedback

Hi //Aussie Broadband

I would like to inquire about a single feature as I'm not sure how to any other way
Is there a to add upcoming / plan maintenance this is the only thing I need from Aussie Broadband

### URL

https://www.home-assistant.io/integrations/aussie_broadband/

### Version

2024.4.3

### Additional information

some additional information 

I would just love to know where then plan maintenance

**Comment by Bre77** [comment]
You want upcoming maintenance events? It's probably possible to build such a feature but the integration cannot do that right now. 

Feature requests should be raised in the home assistant forum.

**Comment by Bre77** [comment]
@home-assistant close

**Comment by EQUALIT-CG** [comment]
Hi @Bre77 
Thanks for the info hum... iv never done that I thought this was more of an Aussie Broadband thing same as the Aussie Broadband app you can see when there is planed maintenance going on around your home as for plan maintenance on the internet.

I have 0 clue as to help to "Feature requests should be raised in the home assistant forum." may I kidney ask you to do it on my 
behalf please.

I have no idea as you can tell.

anyways thank for replying to my suggestion

**Comment by Bre77** [comment]
This is where you're meant to request new features: https://community.home-assistant.io/c/feature-requests/13
