### ISSUE TITLE
Confused on valid parameters for Prometheus and other History components

### ISSUE THREAD

**Issue by alexbarcelo** [home-assistant/home-assistant.github.io#3234]
In #2913 documentation was added for the Prometheus component. The final merge of Prometheus component was home-assistant/home-assistant#8211

However, in the example entry of the home-assistant PR there was an example with an `exclude` directive, just like in some others History components. But the documentation for Prometheus says 

> The Prometheus component has no configuration variables.

And now I don't know if those directives can be used or are not accepted. For example, InfluxDB has explicit documentation for the `exclude` and `include` parameters, but Graphite has no mention of them.

I have not tested whether Graphite, Prometheus or other History components accept them or not.

**Comment by fabaff** [comment]
According to the code `exclude` and `include` are valid configuration variables.

**Comment by alexbarcelo** [comment]
Nice #3240!

I planned to dig a little bit more, but you beat me to it :)
