### ISSUE TITLE
Feature request: Credit marker trigger

### ISSUE THREAD

**Issue by mixmastrbrock** [home-assistant/home-assistant.github.io#32341]
### Feature request

I am working to try and receive the "Credit Marker" trigger into Home Assistant from Tautulli. Actively, I am using a webhook in the HA automation and the Tautulli notification agent to POST to accomplish this. 

Having this available as an entity would be cleaner and ideally less prone to breaking and manual updating.

### URL

https://www.home-assistant.io/integrations/tautulli/

### Version

2024.4.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
