### ISSUE TITLE
Thoughtwork promoted 'CLOUDEVENTS'  - This will become a standard. IT seams beneficial in the long term to comply to this standard. 

### ISSUE THREAD

**Issue by FL100** [home-assistant/home-assistant.github.io#32350]
### Feedback

This will become a event message standard. It seams beneficial in the long term to comply to this standard. 

See https://www.thoughtworks.com/radar/platforms/summary/cloudevents
See https://cloudevents.io/

### URL

https://www.home-assistant.io/docs/configuration/events/

### Version

2024.4.3

**Comment by dannytsang** [comment]
Please review and raise this as an architecture discussion: https://github.com/home-assistant/architecture?tab=readme-ov-file
