### ISSUE TITLE
Poorly implemented

### ISSUE THREAD

**Issue by Witchdoc59** [home-assistant/home-assistant.github.io#32379]
### Feedback

Need to be able to add events that occur every 2 weeks, or every 21 days.  Or an event that occurs on the 1st monday of every month.

### URL

https://www.home-assistant.io/integrations/local_calendar/

### Version

2024.4.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
