### ISSUE TITLE
Auto Scaling for the Energy Dashboard and cards

### ISSUE THREAD

**Issue by Waz-Cpt** [home-assistant/home-assistant.github.io#32374]
### Feedback

Would be great to have the energy dashboard employ auto scaling. See below screen shot of energy dashboard looking at the month of April.
![image](https://github.com/home-assistant/home-assistant.io/assets/34164294/e5aed72b-82cc-40c4-a378-27d7fca08308)

With the Slipx card it has auto scaling of from W to kW to MW and same for Wh to kWh to MWh.
![image](https://github.com/home-assistant/home-assistant.io/assets/34164294/a9b0dd37-49a1-467e-aab2-2c6da5830f6b)

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2024.4.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
