### ISSUE TITLE
Errata in docs?

### ISSUE THREAD

**Issue by BlackRockCity** [home-assistant/home-assistant.github.io#32389]
### Feedback

"Controller notes
800 SERIES CONTROLLERS
Z-Wave JS does not support Z-Wave Long Range yet."

I am a beginner, but based on my reading, it sounds like it does support 800 series LR as of 12.5.0

### URL

https://www.home-assistant.io/docs/z-wave/controllers/

### Version

2024.4.3

**Comment by frenck** [comment]
The driver has some support for it, Home Assistant however, has not yet.

The documentation is correct here.

../Frenck
