### ISSUE TITLE
Discord Support Server unreackable

### ISSUE THREAD

**Issue by IIIdefconIII** [home-assistant/home-assistant.github.io#32396]
### Feedback

Hi, i got some question about setting up Discord in homeassistant, there is even an intergration but i cant put the full question somewhere because i followed the official links and im unable to join the discord server.

### URL

In order to use this integration, it is required to have working Bluetooth set up on the device running Home Assistant. A SwitchBot Hub is not required for this integration.

**Comment by klaasnicolaas** [comment]
What is your full Discord name? Maybe you got banned for some reason?

./klaas

**Comment by IIIdefconIII** [comment]
Got now clue, my disc namr is IIIdefconIII

**Comment by IIIdefconIII** [comment]
Hey klaar, it seems I talking to the offical moderator that helps me out

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
