### ISSUE TITLE
Access to parental control ticket list 

### ISSUE THREAD

**Issue by Rudolf1986** [home-assistant/home-assistant.github.io#32393]
### Feedback

Hey, very cool integration.
I am missing the parental control ticket list.

Will it be integrated in the future? 

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2024.4.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
