### ISSUE TITLE
URL M12676EN not working

### ISSUE THREAD

**Issue by RayRent** [home-assistant/home-assistant.github.io#32390]
### Feedback

The URL M12676EN on this page is not working
https://assetstore.nibe.se/hcms/v2.4/entity/document/34499/storage/MDM0NDk5LzAvbWFzdGVy

It gives as result: {"error":"No such entity: 34499"}

### URL

https://www.home-assistant.io/integrations/nibe_heatpump/

### Version

2024.4.3

**Comment by realzoulou** [comment]
Noticed the same just now.
Found the document at
https://www.nibe.eu/download/18.3db69dc1795e0d992c5722/1622634529178/Modbus%20S-series%20EN%20M12676EN-1.pdf
