### ISSUE TITLE
Unexpected error Freebox mini 4k

### ISSUE THREAD

**Issue by JacFr033** [home-assistant/home-assistant.github.io#32404]
### Feedback

Hi
When i valid : 
Unexpected error ??
Freebox mini 4k

### URL

https://www.home-assistant.io/integrations/freebox/

### Version

2024.4.3

### Additional information

Unexpected error

![Screenshot_20240422_100419](https://github.com/home-assistant/home-assistant.io/assets/167751711/28078803-8136-40fc-ab30-0ceff5b35609)

**Comment by frenck** [comment]
Hi there @JacFr033 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
