### ISSUE TITLE
LED Strip added but missing options

### ISSUE THREAD

**Issue by rxritalin** [home-assistant/home-assistant.github.io#32400]
### Feedback

I added my Govee H6144 LED light strip via the Govee Local API and it was added to Home Assistant, but it only show up as a light switch with no options for the color, brightness or scenes. 
The local API option is enabled in the Govee app. 

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.4.3

### Additional information

Govee info
Firmware Version 2.06.15
Hardware version 2.01.02  1.0010/1.02.11
Product Model H6144

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
