### ISSUE TITLE
Adding IO Series 10

### ISSUE THREAD

**Issue by learnlinuxnow** [home-assistant/home-assistant.github.io#32416]
### Feedback

Unfortunatly my new tooth brush isn't supported. 

Using OralB IO Series 10 device including the Wifi connected Charging Dock.

From HA the Doch is pingable, and providing a WIFI BT Adaptor by itself 

When will be the suff added?
Shall i support with testing?

### URL

https://www.home-assistant.io/integrations/oralb/

### Version

2024.4.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
