### ISSUE TITLE
What are your 'qualifying' testing for "Known/Approved" adapters?

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#32451]
### Feedback

I would simply like to offer myself to test and know what qualifications are needed to make an entry to your list?  I have the Intel AX210 (WiFi 6E/BT 5.3) adapter in my machine (2 separate machines - one is a ThinClient using the Mini-PCIe card natively in m.2 slot, the other is a VM in Proxmox using passthrough).  

Both systems appear to recognize and see (allow setup) of both WiFi and Bluetooth.  If you wish to have some logs or images, please let me know what (and possibly how) to collect those for you.  

This image is from the ThinClient:
![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/8ce8bf81-428e-4279-a563-b931df82bb72)

This image is from the Virtual Machine:
![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/5e1e6a74-145e-48f7-b7c8-a85211b55042)

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2024.4.3

**Comment by bdraco** [comment]
It looks like it could be added to the known working adapters list based on the above

For the high performance list, the testing that is described in the docs would need to be conducted before adding it to that list
