### ISSUE TITLE
einen bestimmten Raum reinigen

### ISSUE THREAD

**Issue by Dieter1965** [home-assistant/home-assistant.github.io#32458]
### Feedback

was muss man tun um einen bestimmten Raum zu reinigen

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.4.4

**Comment by mib1185** [comment]
Hi @Dieter1965 

This sounds like a request for support?
We use GitHub for tracking issues with Home Assistant Core itself, not for providing support.
If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://www.home-assistant.io/join-chat).

Thanks! 👍

**Comment by edenhaus** [comment]
Closing it as this is a request for support and my colleague already pointed you to the correct places.
