### ISSUE TITLE
Inconsistent attribute values for http.strict_connection 

### ISSUE THREAD

**Issue by ReneNulschDE** [home-assistant/home-assistant.github.io#32459]
### Feedback

The attribute strict-connection shows "static_page" as possible value. Should be "guard_page" from my perspective.

### URL

https://rc.home-assistant.io/integrations/http

### Version

2024.5.0b0

**Comment by c0ffeeca7** [comment]
Thank you for the report, @ReneNulschDE :+1: 

It's a duplicate of https://github.com/home-assistant/home-assistant.io/issues/32452.
Closing this as fixed by https://github.com/home-assistant/home-assistant.io/pull/32454
