### ISSUE TITLE
Strict Connection documentation is inconsistent

### ISSUE THREAD

**Issue by Bre77** [home-assistant/home-assistant.github.io#32452]
### Feedback

The strict connection beta documentation says the guard page is configured in YAML with `guard_page` in one spot and `static_page` in another.

### URL

https://rc.home-assistant.io/integrations/http/#strict_connection

### Version

2024.5

**Comment by frenck** [comment]
fixed in https://github.com/home-assistant/home-assistant.io/pull/32454
