### ISSUE TITLE
No documentation on deleting categories

### ISSUE THREAD

**Issue by eight-vrnd** [home-assistant/home-assistant.github.io#32464]
### Feedback

There currently doesn't appear to be a way to delete the newly added categories, so creating one will cause it to always show in the assign menu.

### URL

https://www.home-assistant.io/docs/organizing/categories/

### Version

2024.4.4

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @e87131 :+1:

**Comment by eight-vrnd** [comment]
Thanks for your addition!
