### ISSUE TITLE
device_class information missing

### ISSUE THREAD

**Issue by HenryLoenwind** [home-assistant/home-assistant.github.io#32480]
### Feedback

There are links in the documentation to https://www.home-assistant.io/docs/configuration/customizing-devices/#device-class (e.g. from https://www.home-assistant.io/docs/blueprint/selectors/#device_class) but there's absolutely nothing about device classes on this page.

### URL

https://www.home-assistant.io/docs/configuration/customizing-devices/

### Version

2024.4.4

### Additional information

(Semi-unrelated rant: It really feels like someone purged all information on what to use for values in the yaml from the documentation. On the one hand, the UI kicks you into yaml every time you want to do anything more complicated than "press button, turn on light", on the other hand, the documentation does its best to not give you anything but "click here, click there".)

**Comment by c0ffeeca7** [comment]
haha, :smile:  Thank you for the semi-unrelated rant. Love the term.

The YAML configuration section was moved to the Home Assistant Core integration documentation section

The device class info is here:
https://www.home-assistant.io/integrations/homeassistant/#device-class

I will look into making it clearer that the info was moved (and add a redirect)

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @HenryLoenwind :+1:

**Comment by HenryLoenwind** [comment]
Thanks, but..."Device class is currently supported by the following platforms:" isn't really that helpful when trying to find out what one can write after "- device_class:" in the yaml. Or if "device_class even is the right thing one needs to use---in my case, it turned out (after two hours of googling and reading countless forum posts) that I needed "- domain: climate" for my blueprint.

In my opinion, those small links next to yaml keys should link to something that either lists all possible values or gives information on how to find the value one needs.
