### ISSUE TITLE
Backup Page's infomation is out of date

### ISSUE THREAD

**Issue by GarethBlain** [home-assistant/home-assistant.github.io#32494]
### Feedback

The [backup page](https://www.home-assistant.io/integrations/backup/) refers to a service to trigger the backups called [BACKUP.CREATE](https://my.home-assistant.io/redirect/developer_call_service?service=backup.create) but this doesn't exist in my system (See end for versions).
Upon searching for "backup" I found a few others like:

- `hassio.backup_full`
- `hassio.backup_partial`
- `hassio.restore_full`
- `hassio.restore_partial`

I suspect at some point there has been a change that hasn't been documented.

These are the versions of HA I have installed:

Core: `2024.4.4`
Supervisor: `2024.04.0`
Operating System: `12.2`
Frontend: `20240404.2`

### URL

https://www.home-assistant.io/integrations/backup/

**Comment by klaasnicolaas** [comment]
Please read the note on the page you mentioned 😉 These services are not for your installation type.

./Klaas

**Comment by GarethBlain** [comment]
OK I see you're correct. I did read that, went there, couldn't see anything for automated backup, serached and ended up on that page again further down! LOL

So how do you setup automated backups in HAOS? Mine went a week without backing up before I thought to check it worked. Maybe this ticket needs to be adding more info to the other page about automated backups!

**Comment by klaasnicolaas** [comment]
> So how do you setup automated backups in HAOS?

You can create an automation ([my own example](https://github.com/klaasnicolaas/Student-homeassistant-config/blob/master/automations%2Fsystem%2Fha_backup.yaml)) and use one of the hassio services you mentioned.

https://www.home-assistant.io/integrations/hassio/#service-hassiobackup_full


./Klaas
