### ISSUE TITLE
Siwtchbot S10 Support

### ISSUE THREAD

**Issue by MarcW22** [home-assistant/home-assistant.github.io#32490]
### Feedback

I am one of the first S10 owners and i hoped the S10 would be working with HA already. 
Would there be a chance to get this developed? 

Thanks in advance. 

### URL

https://www.home-assistant.io/integrations/switchbot_cloud/

### Version

2024.4.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
