### ISSUE TITLE
OpenWeather One Call API 3.0

### ISSUE THREAD

**Issue by jjroysdon** [home-assistant/home-assistant.github.io#32493]
### Feedback

OpenWeather One Call API 3.0 requires a subscription, which now requires a credit card to be on file to bill for transactions greater than free tier of 1,000 calls per day. It is my understanding that this credit card should never be billed provided the API key is not used greater than 1,000 calls per day. Users who have API keys should have received an email regarding switching from One Call API 2.5 to 3.0. Also, users should be instructed to edit their One Call API 3.0 Base Plan "Calls Per Day" from the default of 2,000 to 1,000, which should block going over 1,000 calls and thus never cause a credit card transaction.

Please review the One Call API 3.0 changes for the Home Assistant OpenWeather integration. At a minimum their are API URL changes.

From the webpage linked in details:

"We would like to inform you about our plans to complete the migration from One Call API 2.5 to One Call API 3.0 that has started 2 years ago. In line with this, access to One Call API 2.5 will be finally closed in June 2024.

All One Call API 2.5 users are invited to the One Call API 3.0, which replicates the 2.5 version's functionality and includes several useful upgrades.

One Call API 3.0 now offers advanced features demanded by businesses, such as minute-by-minute forecast for the next 1 hour, 4-day forecast for any timestamp, 8-day daily forecast, human-readable summaries, historical 45-year archive (data both for specific timestamp and with daily aggregation), daily long-term forecast for the next 1,5 years and others.

One Call API 3.0 works in exactly the same way as the One Call API 2.5, but includes several useful upgrades. For seamless transfer from One Call API 2.5 to the One Call API 3.0 please carefully read the following sections"

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2024.4.4

### Additional information

More info:
[https://openweathermap.org/one-call-transfer](https://openweathermap.org/one-call-transfer)

**Comment by Sjors** [comment]
> Users who have API keys should have received an email regarding switching from One Call API 2.5 to 3.0. 

I never got an email about this. Only today Home Assistant started showing a warning that you need the switch to the v3.0 API.

> requires a credit card to be on file to bill for transactions greater than free tier of 1,000 calls per day.

I don't plan to enter personal info beyond an email address, let alone a creditcard number.

I don't understand why the free usage requires such info, for now I'll just disable the integration, but that's unfortunate.

**Comment by Sjors** [comment]
Oh, I just realised I haven't used this weather feed in a while :-)

**Comment by frenck** [comment]
The integration has been adjusted in the latest release.

../Frenck
