### ISSUE TITLE
Missing allowlist_external_urls/#allowlist_external_dirs

### ISSUE THREAD

**Issue by jameyc** [home-assistant/home-assistant.github.io#32500]
### Feedback

Some of the recent GUI updates to config have resulted in the config help page no longer documenting the config parameters. There's a _really_ large number of integration docs on the site that point to the old anchors  `/docs/configuration/basic/#allowlist_external_urls` or `#allowlist_external_dirs`.

Searching within the site for for either key will turn up the pages for the extensions that link to the now missing section, but not any config documentation about it.

Making matters worse, Google's top results for the key are mostly threads from a few years ago when `whitelist_external_dirs` removed.

I think these are currently only documented on developers.home-assistant.io. Due to the large number of old links, the basic config could probably use a link out to here for "advanced" or for details on more of the keys, so that users sent here will have some clue where to find the right documentation these days.

### URL

https://www.home-assistant.io/docs/configuration/basic/

### Version

2024.4.4

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @jameyc :+1:
