### ISSUE TITLE
I can't add a working day to a calendar Saturday

### ISSUE THREAD

**Issue by bisquit2003** [home-assistant/home-assistant.github.io#32508]
### Feedback

I have selected working days from Monday to Friday and weekends from Saturday to Sunday in the integration settings (this corresponds to 95% of working days and weekends per year). Sometimes in the production calendar, Saturday is a working day (then Monday becomes a day off, for example, the so-called "postponement of the day off"). It is possible to add a day off (holiday) in the integration for, for example, Monday without problems, but it is impossible to exclude several working Saturdays per year, a configuration error. Please add this functionality

### URL

https://www.home-assistant.io/integrations/workday/

### Version

2024.4.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
