### ISSUE TITLE
give toggle for speaker a, b, and a+b for denon pma-900hne model!

### ISSUE THREAD

**Issue by xamos1** [home-assistant/home-assistant.github.io#32506]
### Feedback

give toggle for speaker a, b, and a+b for denon pma-900hne model!

### URL

https://www.home-assistant.io/integrations/heos/

### Version

2024.4.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
