### ISSUE TITLE
Homematic - Motion Sensor with switching actuator

### ISSUE THREAD

**Issue by NBO85** [home-assistant/home-assistant.github.io#32507]
### Feedback

Hi, can you support the Motion Sensor with switch actuator?

This is an new one from Homematic, acutally HA don´t find the new device. My CCU3 has the actually firmware and my devices, too. HA ist uptodate.
 This is the new device:
https://de.elv.com/homematic-ip-smart-home-bewegungsmelder-mit-schaltaktor-aussen-230-v-weiss-156737

### URL

https://www.home-assistant.io/integrations/homematic/

### Version

2024.4.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
