### ISSUE TITLE
Add support for the dehumidifer

### ISSUE THREAD

**Issue by ajmulcahy** [home-assistant/home-assistant.github.io#32517]
### Feedback

Are you able to add support for the dehumidifier?  Specifically reporting the current humidity value would be appreciated.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2024.4.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
