### ISSUE TITLE
Add optional basic authentication

### ISSUE THREAD

**Issue by StevenKRT** [home-assistant/home-assistant.github.io#32527]
### Feedback

I suggest adding an optional basic authentication to the Ollama integration. This function would enable additional security settings that are particularly beneficial in security-sensitive network environments.

- Enables simple and effective control of access to the integration.
- Provides additional security for installations in insecure networks or hosted instances.

### URL

https://www.home-assistant.io/integrations/ollama/

### Version

2024.4.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
