### ISSUE TITLE
After update to 2024.4.4, started to get errors, "Unsupported system - Operating System", "Unsupported system - Systemd issues", and "Unsupported system - CGroup version"

### ISSUE THREAD

**Issue by ftbboy2115** [home-assistant/home-assistant.github.io#32529]
### Feedback

Prior to the update, I didn't get these errors. After update to 2024.4.4, I started to get errors, "Unsupported system - Operating System", "Unsupported system - Systemd issues", and "Unsupported system - CGroup version".
Does that mean this version suddenly was sensitive to something it previosuly was not? Or is there another explination as to why I'm suddenly seeing such errors after update?

### URL

https://www.home-assistant.io/more-info/unsupported/os/

### Version

2024.4.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
