### ISSUE TITLE
Broken endpoint for Dublin bus integration

### ISSUE THREAD

**Issue by arkalon76** [home-assistant/home-assistant.github.io#32521]
### Feedback

The API that the integration relies on has been removed, thus, integration is broken.

### URL

https://www.home-assistant.io/integrations/dublin_bus_transport/

### Version

2024.4.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
