### ISSUE TITLE
Please Support Solax Cloud API

### ISSUE THREAD

**Issue by MBadberg** [home-assistant/home-assistant.github.io#32524]
### Feedback

Solax inverters with newer firmware don't expose their rest api. But it could be accessed over solax cload. so please support that

### URL

https://www.home-assistant.io/integrations/solax/

### Version

2024.4.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
