### ISSUE TITLE
Incorrect url and text in external link

### ISSUE THREAD

**Issue by David-Woodthorpe** [home-assistant/home-assistant.github.io#32530]
### Feedback

![image](https://github.com/home-assistant/home-assistant.io/assets/4370376/fc667f5a-6796-40a6-9d76-66c962addf10)
There is a typo in the external link to the ambient weather website (missing an 'a' in 'weather')

### URL

https://www.home-assistant.io/integrations/ambient_network/

### Version

2024.5.0

**Comment by frenck** [comment]
Was fixed in #32497
