### ISSUE TITLE
Failled to setup

### ISSUE THREAD

**Issue by augustose** [home-assistant/home-assistant.github.io#32542]
### Feedback

 After adding the Control4 integration, all devices and entities were added correctly. I was able to create a Dashboard in Home Assistant and use the Dimmers. However, after about 20 minutes everything stopped working on Home Assistant. On the page with the integration details I see an error that says "failed to setup".

### URL

https://www.home-assistant.io/integrations/control4/

### Version

2024.4.4

**Comment by augustose** [comment]
Hi guys, I'm gonna need help on this cause I don't understand what you're saying

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
