### ISSUE TITLE
Epson Workfoce Integration seems not to be available anymore

### ISSUE THREAD

**Issue by DirkHBo** [home-assistant/home-assistant.github.io#32543]
### Feedback

The Epson Workforce Github page is not available anymore. I assume it has been dumped from the core. Maybe that should be pointed out on the documentation page.
Thank you.

### URL

https://www.home-assistant.io/integrations/epsonworkforce/

### Version

2024.4.4

**Comment by klaasnicolaas** [comment]
The integration will be removed and these changes are in the May release that comes out today.

./Klaas

**Comment by dwd1** [comment]
Why is the integration removed? Its working fine before removal. Please re-add the intergration! @klaasnicolaas @frenck
https://community.home-assistant.io/t/monitor-ink-levels-of-a-epson-printer/134936
