### ISSUE TITLE
Add support to Ring's door and window sensors

### ISSUE THREAD

**Issue by fcy** [home-assistant/home-assistant.github.io#32554]
### Feedback

I have a Ring Alarm system with a bunch of door and window sensors that I'd love to have access to in Home Assistant. Without having to remove them from the Ring Alarm hub.

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2024.4.4

### Additional information

FWIW this project seems to do it but I haven't tried it: https://github.com/dgreif/ring

**Comment by fcy** [comment]
Issue has not being addressed.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
