### ISSUE TITLE
Update Ecobee Homekit Integration to support new Thermostat Card Updates

### ISSUE THREAD

**Issue by creedda** [home-assistant/home-assistant.github.io#32557]
### Feedback

Would love to see the select_input entity that is currently created when connecting Ecobee via homekit be upgraded/added to the new feature of the climate entity to change presets so that we can leverage all the new card updates for climate entities!
Homekit (local)
<img width="356" alt="Screenshot 2024-05-01 at 5 10 25 PM" src="https://github.com/home-assistant/home-assistant.io/assets/1697679/2315e990-2e4c-46c4-8d83-6cb126c99ed0">
<img width="574" alt="Screenshot 2024-05-01 at 5 10 08 PM" src="https://github.com/home-assistant/home-assistant.io/assets/1697679/18e100c6-0716-4ed2-afa7-81ecf5c58b06">

Ecobee Integration (via cloud)
<img width="577" alt="Screenshot 2024-05-01 at 5 09 56 PM" src="https://github.com/home-assistant/home-assistant.io/assets/1697679/1411a05e-161d-4cc0-b909-3fd95d5667cc">

https://community.home-assistant.io/t/update-ecobee-homekit-integration-to-support-new-thermostat-card-updates/724191

### URL

https://www.home-assistant.io/integrations/homekit_controller/

### Version

2024.5.0

**Comment by Jc2k** [comment]
Feature requests belong on the forum not the documentation issue tracker.

But there's no plan to do this currently.

The main climate entity has to work for all homekit thermostats, and ecobee is the only one that has the concept of presets in anyway exposed via the homekit protocol.

That said, if it did a good job at it we'd try. But the select entity uses an unstable, undocumented, unsupported "backdoor" API in the ecobees homekit implementation. It's unusably broken for some people, glitchy for most, and works as intended for a small group. And even for those it's incomplete, stopping working under some conditions and not supporting all presets in the ecobee ecosystem.

Honestly for all the trouble it causes, I'm more likely to remove it entirely than integrate into deeper into the core climate entity.
