### ISSUE TITLE
1 GB/s Fiber WAN

### ISSUE THREAD

**Issue by argually** [home-assistant/home-assistant.github.io#32568]
### Feedback

Since Tuesday I have a new Fiber Internet-Connection. My german provider 1&1 is delivering a datarate of 1 GB/s down and 200 MB/s up. It seems whether the suggested Test Servers don´t offer such high data rates. How can I find suitable servers?

### URL

https://www.home-assistant.io/integrations/speedtestdotnet/

### Version

2024.5.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
