### ISSUE TITLE
Utility Meter Documentation request to add specific input sensor entity parameters

### ISSUE THREAD

**Issue by P3TACCO** [home-assistant/home-assistant.github.io#32569]
### Feedback

Hello

I am using totality Meter integration and FINALLY got it set up correctly.

I made some incorrect conclusions regarding how this works and the docs are not specific.  I suggest adding a few sentences underneath the "input sensor" section to specify the required sensors to get this to work.

When I looked at the entities in my smart plug one was the instantaneous power in Watts and the other was the total energy delivery to the device for the entire life of the plug in kWh.

I assumed the Utility Meter tracked the power consumption (in Watts) and calculated the total energy consumed by integrating those instantaneous measurements over each time period a sample was taken.

I also assumed since the energy delivered entity was ever increasing that the Utility Meter would take a reading, and add it to the previous, and since the energy entity is an ever increasing number, the total energy would be off by orders of magnitude and get more inaccurate over time.

I now understand how the Utility Meter is working and how the periodic sampling of the energy delivered entity in kWh works.

I'd recommend calling this out with a note under the input sensor.  A warning "Do Not use an input sensor for instantaneous power (in Watts), it must be an energy entity in kWh, Wh, etc."
The same call out is probably needed for gas if there is a conversion between cuft, therms, BTUs...etc.

Thanks

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2024.5.0

**Comment by dgomes** [comment]
Why don't you open a PR proposing changes :) ?

**Comment by P3TACCO** [comment]
OK, I can do that

It was suggested to provide feedback to the docs.


Jeff Caulk
425-293-5608
***@***.***

     On Thursday, May 2, 2024 at 10:03:00 AM MDT, Diogo Gomes ***@***.***> wrote:  
 
 


Why don't you open a PR proposing changes :) ?

**Comment by P3TACCO** [comment]
What's a PR?

I only see "Edit", "Provide feedback" and "View pending feedback"

https://www.home-assistant.io/integrations/utility_meter/

"Help us to improve our documentation
Suggest an edit to this page, or provide/view feedback for this page.
Edit Provide feedback View pending feedback"



Jeff Caulk
425-293-5608
***@***.***

     On Thursday, May 2, 2024 at 10:03:00 AM MDT, Diogo Gomes ***@***.***> wrote:  
 
 


Why don't you open a PR proposing changes :) ?

**Comment by dgomes** [comment]
when you click edit you are redirect to a GitHub webpage where you can edit text.

But editions don't go directly to the website, they are proposed of inclusion. The mechanism is a Pull Request (PR)

A HA documentation maintainer will then review your proposal (the PR) and if accepted will then make it into official documentation.
