### ISSUE TITLE
UDP port number is 50222 not 5022

### ISSUE THREAD

**Issue by masjoelin** [home-assistant/home-assistant.github.io#32592]
### Feedback

UDP port number is 50222 not 5022 for weatherflow udp port. See doc at https://weatherflow.github.io/Tempest/api/udp/v171/)

### URL

https://www.home-assistant.io/integrations/weatherflow/

### Version

2024.5.1

**Comment by jeeftor** [comment]
This is a documentation issue right?Sent from my iPhoneOn May 5, 2024, at 7:45 AM, home-assistant[bot] ***@***.***> wrote:﻿
Hey there @natekspencer, @jeeftor, mind taking a look at this feedback as it has been labeled with an integration (weatherflow) you are listed as a code owner for? Thanks!

Code owner commands
Code owners of weatherflow can trigger bot actions by commenting:

@home-assistant close Closes the feedback.
@home-assistant rename Awesome new title Renames the feedback.
@home-assistant reopen Reopen the feedback.
@home-assistant unassign weatherflow Removes the current integration label and assignees on the feedback, add the integration domain after the command.
@home-assistant add-label needs-more-information Add a label (needs-more-information) to the feedback.
@home-assistant remove-label needs-more-information Remove a label (needs-more-information) on the feedback.

**Comment by masjoelin** [comment]
Yeah, doc list 5022 instead of 50222. Noticed when I setup by udp relay
today

Den sön 5 maj 2024 15:48Jeef ***@***.***> skrev:

**Comment by natekspencer** [comment]
I'm seeing `50222` in both places:
![Screenshot_20240505_134806_Chrome](https://github.com/home-assistant/home-assistant.io/assets/3792831/7644cd56-ecaf-4e4a-98b2-8a670b40a77a)
![Screenshot_20240505_134839_Chrome](https://github.com/home-assistant/home-assistant.io/assets/3792831/e751d7d3-da6e-48c7-933d-5f9b77a1d9f2)

**Comment by jeeftor** [comment]
I’m confused :)Sent from my iPhoneOn May 5, 2024, at 1:50 PM, Nathan Spencer ***@***.***> wrote:﻿
I'm seeing 50222 in both places:
Screenshot_20240505_134806_Chrome.jpg (view on web)
Screenshot_20240505_134839_Chrome.jpg (view on web)

**Comment by masjoelin** [comment]
Close this issue. Will check tomorrow where I thought I saw 5022.

Den sön 5 maj 2024 21:53Jeef ***@***.***> skrev:

**Comment by natekspencer** [comment]
@home-assistant close

**Comment by jeeftor** [comment]
Also feel free to make a pr if you want. Always good to get more contributions and doc fixes are easy :)
