### ISSUE TITLE
systemmonitor processor units

### ISSUE THREAD

**Issue by billpribyl** [home-assistant/home-assistant.github.io#32599]
### Feedback

It would be super helpful if the documentation for system monitor gave an indication of what units are displayed for the processor load metrics. I'm seeing numbers like 0.07 for 1m and I don't know if that's 7% or...?

Thanks!

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2024.5.1

**Comment by gjohansson-ST** [comment]
Well, I wonder why you use them if you don't know what they are.

But as such they don't have a unit but you can read more here (from the library which is used for getting the information).
As such I'm going to close this issue.

**Comment by billpribyl** [comment]
Well, I'm ignorant, but hopefully not too stupid, and I'm trying to educate myself. My goal is to understand whether my Pi is compute-bound, since my HA is slower than it seems like it ought to be. 

Was there a link in your comment at the word "here"?  If so, I'm not able to see it now.

**Comment by gjohansson-ST** [comment]
I would never claim that and also good that you want to learn and understand why things are like they are or what they mean.
In the future I would refer you to our forums for such questions and you can probably compare your values against others as `systemmonitor` is a popular integration which many are using.

I did indeed not include the link, here it is: https://psutil.readthedocs.io/en/latest/#psutil.getloadavg
