### ISSUE TITLE
Fitbit Integration - data input?

### ISSUE THREAD

**Issue by meestermole-gpt** [home-assistant/home-assistant.github.io#32607]
### Feedback

There are a few items in the Fitbit app that require the user to enter some information, i.e. Calorie tracking and Water intake.
I am wondering if it is possible for the integration to allow the user to enter the information for these values, rather than having to enter them into the app, then view them in the integration. 
What I am hoping to accomplish is to create an NFC tag that will add 16oz (or other amount) of water at each scan.
If this is possible, I would like to do something similar with meal prep, and set NFC tags with certain calorie counts.
Thanks!

### URL

https://www.home-assistant.io/integrations/fitbit/

### Version

2024.5.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
