### ISSUE TITLE
Daikin AC Integration

### ISSUE THREAD

**Issue by Pythoneer31** [home-assistant/home-assistant.github.io#32604]
### Feedback

The Following statement is uncorrect : 
"The European versions of the Wifi Controller Unit (BRP069A41, 42, 43, 45), which is powered by the [Daikin Online Controller](https://play.google.com/store/apps/details?id=eu.daikin.remoapp) application. The new version of WiFi Controller Unit BRP069Bxx is also confirmed to work, tested and working devices are the BRP069B41 and BRP069B45."

I have 2 Daikin AC with 2 different WIFI Module BRP069B41 (reference in attached file). 
Since the Daikin update, one is still working with HA and the other not is not anymore .
I will be really interested to udnerstand why this is not working anymore and what is the fix.
![2024-05-06_08h30_07](https://github.com/home-assistant/home-assistant.io/assets/138614762/3a789f3e-01d4-41e3-a72a-be180b672922)

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2024.5.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
