### ISSUE TITLE
Pasue/Resume functionality

### ISSUE THREAD

**Issue by storacm** [home-assistant/home-assistant.github.io#32608]
### Feedback

Hi,
I have been usign your Wallbox since begginngin of 2023. It seems it operates differently since some time back. THe Pause/Resume function is unavailabel unless one has unlocked the wallbox first. This screws up the the function with automatic charging thru EV Smart Charging integration as the automatic charging of the Wallbox starts as soon as one unlocks the Wallbox. It would be better if one could get the functionallity like before that you can pause/resume the charging once the car is connected without havin to unlock first.
As your integration needs the credentials for the Wallbox to log in, this means the one who can use the rpause/resume button is Admin anyway. Therefor it makes no sense in my opinion to first have to unlock.

If I first have to unlock the Wallbox it will automatically start chargin even if the EV Smart Charging integration does not require charging for the moment.

It would be great if we could have the old functionality your Wallbox Integration back again :-)

### URL

https://www.home-assistant.io/integrations/wallbox/

### Version

2024.5.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
