### ISSUE TITLE
Not connecting after enabling MFA on Unifi network

### ISSUE THREAD

**Issue by hassan-khalid24** [home-assistant/home-assistant.github.io#32612]
### Feedback

Since enabling MFA on unifi network, I have lost all my devices from this integration and not able to add them again. 

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.5.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
