### ISSUE TITLE
docs: Configuration -> YAML section could use info on include files support

### ISSUE THREAD

**Issue by pfalcon** [home-assistant/home-assistant.github.io#3261]
I'm reading docs in the order of ToC as seen on the right of https://home-assistant.io/docs/ . https://home-assistant.io/docs/configuration/yaml/ gives a good enough intro into YAML, and even mentions how envvars can be referenced. But then https://home-assistant.io/docs/configuration/troubleshooting/#multiple-files talks about multiple files and includes, which weren't so far introduced. The YAML section,  https://home-assistant.io/docs/configuration/yaml/ , would be the best place to mention the includes support.

**Comment by pfalcon** [comment]
Ah, ok, this is considered "Advanced Configuration" and is available at https://home-assistant.io/docs/configuration/splitting_configuration/ . Still, the above report is from reading the manual (that's the manual, not a random mix of notes, right?) top to bottom. So, at least linking to https://home-assistant.io/docs/configuration/splitting_configuration/ from YAML section would be helpful.

**Comment by pfalcon** [comment]
Salvaged from https://github.com/home-assistant/home-assistant/issues/9166

**Comment by jhoepken** [comment]
I've already started to put more information into the [configuration](https://home-assistant.io/docs/configuration/yaml/) part. This is especially regarding reading external files and environmental variables.

**Comment by Maxr1998** [comment]
On it.
