### ISSUE TITLE
IMGW-PIB integration page doesn't exist

### ISSUE THREAD

**Issue by Misiu** [home-assistant/home-assistant.github.io#32618]
### Feedback

While looking at https://github.com/home-assistant/core/pull/116912 I noticed that imgw_pib integration page doesn't exist:
![image](https://github.com/home-assistant/home-assistant.io/assets/1741838/6359d839-b1ff-4bac-abbc-865c5691144f)

The quality scale will be platinum, so it should work.
FYI @bieniu 

### URL

https://www.home-assistant.io/integrations/imgw_pib

**Comment by frenck** [comment]
That integration hasn't been released yet, it is thus correct that the documentation page doesn't exists for our stable documentation.

../Frenck
