### ISSUE TITLE
Instructions for Restart, Reboot and Shut down are out of date

### ISSUE THREAD

**Issue by virtualian** [home-assistant/home-assistant.github.io#32625]
### Feedback

The Settings > System > Shutdown menu option has been replaced with an On/Off Icon in the top right. The document still refers to the menu option.

### URL

https://green.home-assistant.io/guides/shutdown/

### Version

2024.5.2

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @virtualian :+1:

**Comment by c0ffeeca7** [comment]
Closing this as fixed by https://github.com/home-assistant/green.home-assistant.io/pull/52
