### ISSUE TITLE
can add china whirlpool account?

### ISSUE THREAD

**Issue by powjie** [home-assistant/home-assistant.github.io#32620]
### Feedback

only have en us

### URL

https://www.home-assistant.io/integrations/whirlpool/

### Version

2024.5.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
