### ISSUE TITLE
Docs direly need a glossary

### ISSUE THREAD

**Issue by pfalcon** [home-assistant/home-assistant.github.io#3263]
HA docs are full of confusing buzzwords, like "entity", "component", "platform", "service", etc. It direly needs an visible/very accessible glossary explaining these terms, ideally linked to thru at least few first doc chapters, to let novices grasp them well enough.

**Comment by pfalcon** [comment]
Here's an example of terminology confusion: https://github.com/home-assistant/home-assistant/issues/9163#issuecomment-325192343

**Comment by pfalcon** [comment]
A great example of buzzwordness is the beginning of https://home-assistant.io/docs/configuration/platform_options/ :

> Any component that is based on the entity component allows various extra options to be set per platform.

LOLWAT?

**Comment by pfalcon** [comment]
Another case:

https://home-assistant.io/docs/configuration/events/#event-platform_discovered

> Event platform_discovered is fired when a new platform has been discovered by the discovery component.

> service | The service that is discovered. Example: zwave.

So, is it *platform* or *service* what's being discovered?

**Comment by Landrash** [comment]
I suggest you clean up this issue and put it all in the issue and not spread over 4 separate posts in the issue.

**Comment by pfalcon** [comment]
> Initial glossary #3568

Thanks!
