### ISSUE TITLE
HA and SimpliSafe Setup - Obtaining Authorization Code

### ISSUE THREAD

**Issue by jmduemes** [home-assistant/home-assistant.github.io#32655]
### Feedback

I'm trying to set up HA with SimpliSafe and not having any luck. I have an MFA setup. I'm using a V2 system. When I try to obtain the authorization code using the link here I get nothing in Chrome. I tried a non-chromium browser (Safari) and I got "Safari cannot open the page because the address is invalid. Any help would be appreciated 

![2024-05-08_13-12-06](https://github.com/home-assistant/home-assistant.io/assets/169195305/1e24c5d3-9434-4d84-a4b8-ae22bc658de7)

### URL

https://www.home-assistant.io/integrations/simplisafe/

### Version

2024.5.2

**Comment by bachya** [comment]
> I get nothing in Chrome

Can you clarify? I assume you're following the linked documentation?

**Comment by jmduemes** [comment]
yes here -->https://www.home-assistant.io/integrations/simplisafe#configuration

**Comment by bachya** [comment]
That's where I need clarification. When you say you "get nothing in Chrome," what do you mean? Does the code never appear in the Network Tab of your Dev Tools?

**Comment by jmduemes** [comment]
Sorry about being vague

When I copy the link or even when I click the link, it opens another browser and calls SimpliSafe nothing is returned - just a blank window. 

Now as far as the Network Tab in Dev Tools - I don't get an error/failed to launch where I can copy the code from the console  - here's is what my screenshot looks like
![image](https://github.com/home-assistant/home-assistant.io/assets/169195305/d35e6e87-4294-437b-8f43-2ba2c2806864)

**Comment by bachya** [comment]
One thing to ensure: the Dev Tools/Console window needs to be open _before_ you attempt to log in (so it can capture the traffic).

**Comment by jmduemes** [comment]
it is and thats the only thing that is returned in the console window - here is what is in the network window 
![image](https://github.com/home-assistant/home-assistant.io/assets/169195305/973c42c9-6de7-4eb0-b1f9-f0747392ea27)

**Comment by bachya** [comment]
The background looks like you're already logged into SimpliSafe. Can you confirm the URL format you're entering (i.e., what you copy/paste out of HA)? That shouldn't ever actually log you into the web app.

**Comment by jmduemes** [comment]
I got it working, I opened the Dev Tools window in Chrome, took the link from this window and then I saw the error and then was able to copy the code. Thank you very much!!!
![image](https://github.com/home-assistant/home-assistant.io/assets/169195305/5a20c32f-aea4-4125-aeef-8e2f8f90b560)
