### ISSUE TITLE
Article needs 'clarity' - specifically "Configuration Variables"

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/home-assistant.github.io#32666]
### Feedback

I am trying to use this to keep an eye on the DB size.  Your variable **_unit_of_measurement_** does not indicate what choices are available B, KB, MB, GB, etc. (and if they are case sensitive).  I have put in B, KB, MB and GB as choices - saved and restarted.  I get the same value for each (I have it set to show 3 decimal places) and it never changes.

Also, I am using the DB which installs with HomeAssistant (I am going to assume that it is SQLite) - but might be helpful if this was specifically called out (rather than this):  

**SQLite**
If you are using the `recorder` integration then you don’t need to specify the location of the database. For all other cases, add `sqlite:////path/to/database.db` as Database URL.

Just think it makes it a little easier, as not everyone is HA 'genius' level.  

### URL

https://www.home-assistant.io/integrations/sql/

### Version

2024.5.2

**Comment by gjohansson-ST** [comment]
I think on point 2 I think we can make that clearer that if you haven't done anything it uses the recorder db. So I think that's good feedback.

On point 1 I'm not sure I get it. It gives a user an opportuniy to collect whatever info they want directly from the DB. Then the user needs to know what he's collecting and thereby setting the right UoM.
To use conversions you also need to set an appropriate device class and then you can change the UoM on the entity it creates. On the `sql` config you need to set the native UoM from whatever you're collecting.

It is a bit of an advanced integration so one needs to know what he's doing to use it.
If you want to monitor a db size perhaps `filesize` is a better option.

**Comment by bearhntr** [comment]
I agree that UoM (should make sense) but as I stated I have put in B, KB, MB and GB - and the value never seems to change.  Always shows 126.##  (even after setting to 3 decimal points).  Once place it shows 2 places, the other it shows 3.   

![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/233d48a6-e2a3-48ff-a168-bc2053a503e6)

![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/64dca9a2-f721-4ac4-81c0-2507444a9bf2)

Notice I have it set to B (bytes) and the DB is way larger than 126.84 bytes.

**Comment by bearhntr** [comment]
![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/216ac11b-4241-470c-87b2-6913357d3d64)

**Comment by bearhntr** [comment]
I currently have 2 HA instances.  The one which is shown above is my working one that has been up for 2+ years.  I am building out a new one - which is currently using the 'pre-built-in' DB.

**Comment by gjohansson-ST** [comment]
But as that query returns `MB` why do you write `B` as UoM?

You need to set the UoM that the query returns. Not what you maybe want to see in the UI. 
Also if you don't set an appropriate device class it's not possible to convert (which is an UI option on the entity). The integration itself doesn't do conversions.

**Comment by bearhntr** [comment]
> But as that query returns `MB` why do you write `B` as UoM?
> 
> You need to set the UoM that the query returns. Not what you maybe want to see in the UI. Also if you don't set an appropriate device class it's not possible to convert (which is an UI option on the entity). The integration itself doesn't do conversions.

I am looking at that query - how/where does it 'specify' MB as the value?  I am not tying to 'thick'.  But also looking at the other one on my new HA (which uses the SQLite built-in DB - which in the documentation also does not "State" it is MB (one could deduce that perhaps looking at the formula used). 

![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/ceeea700-786d-4687-8bda-56dffeb0377a)

My quandary which lead to the query is....on my brand new HA installation which has been up about a month.  Has had 1.000 as the DB Size value since day 3 when I added the SQL Integration.  It has never changed at all (no matter if it is B, KB, MB, GB) it just shows 1.000 (and the measurement after that changes to what I have put in, B, KB, MB, GB).  

![image](https://github.com/home-assistant/home-assistant.io/assets/100164602/86be80e1-c0f6-46ce-ba1a-225aa740c56f)

**Comment by dougiteixeira** [comment]
Note was added about the unit of measurement and the correct device class in the documentation: #33642

Soon this can be closed (I forgot to link...)

**Comment by dougiteixeira** [comment]
@home-assistant close
