### ISSUE TITLE
Motion blinds - confirmed working with lxhubmini bridge

### ISSUE THREAD

**Issue by scotta1725** [home-assistant/home-assistant.github.io#32660]
### Feedback

Ref motion blinds integration. I wanted to confirm that the integration works with Linx Automation - Linx hub mini - LXHUBMINI from 
https://linxautomation.com.au/hubs/

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2024.01

**Comment by starkillerOG** [comment]
@scotta1725 thanks for letting us know that it works with Linx, I added Linx as a supported brand here: https://github.com/home-assistant/home-assistant.io/pull/33366

If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.
