### ISSUE TITLE
Tutorial code is broken in blueprint tutorial

### ISSUE THREAD

**Issue by JasperHorn** [home-assistant/home-assistant.github.io#32671]
### Feedback

This is the problematic bit:

      selector:
        target:
          entity:
            filter:
              - domain: light

It should be:

      selector:
        target:
          entity:
            - domain: light

It is both there in the final yaml section and in the "Describe the inputs" section.

### URL

https://www.home-assistant.io/docs/blueprint/tutorial/

### Version

2024.5.2

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @JasperHorn :+1:

**Comment by frenck** [comment]
Which version of Home Assistant are you running @JasperHorn?

As this look like the older syntax

**Comment by JasperHorn** [comment]
@frenck 2024.4.4 right now. I think I was on 2024.4.3 or 2024.4.2 when I submitted the issue. The issue was about the website, though, not my install.

**Comment by frenck** [comment]
Target selector configuration (from source)

![CleanShot 2024-05-17 at 08 17 42@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/a7276b8a-bcf6-4cb6-9775-aa2918de702f)

![CleanShot 2024-05-17 at 08 18 14@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/16af085a-eb71-47b4-b19f-1fd497d8ce2d)

Yup you are right 👍 

My bad, sorry for the noise.

../Frenck
