### ISSUE TITLE
unexpected error when trying to log in to discovergy

### ISSUE THREAD

**Issue by seikodad** [home-assistant/home-assistant.github.io#32684]
### Feedback

Hello, unfortunately I cannot log in to discovergy integrity. This used to work, but unfortunately it no longer works. I have now stored two counters in my discovergy account. Is that why it doesn't work? Thanks

### URL

https://www.home-assistant.io/integrations/discovergy/

### Version

2024.5.2

**Comment by jpbede** [comment]
Anything in the logs? 

Besides, I don't know when you've tried it but the API had a issue today.

**Comment by seikodad** [comment]
Hi,
i dont know where to find the logs. Ich deleted the integreation and what to install it again, but know i doesnt work.

**Comment by jpbede** [comment]
Could you create a [new issue in the core repo](https://github.com/home-assistant/core/issues/new/choose) as this repository is for tracking issues with the documentation and not with integrations? Therefore I'm going to close this here

The log (`home-assistant.log`)can be found in your config folder or by following the link: https://my.home-assistant.io/redirect/logs/
