### ISSUE TITLE
AWN Forecast

### ISSUE THREAD

**Issue by Truf** [home-assistant/home-assistant.github.io#32688]
### Feedback

Currently the forecast is not able in Homeassistant, but I do see it on the AWN website of a specific station. Can you get the forecast into homeassistant?
(To be honest, not sure this is the right spot for this feedback)

### URL

https://www.home-assistant.io/integrations/ambient_network/

### Version

2024.5.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
