### ISSUE TITLE
Wrong energy graphs

### ISSUE THREAD

**Issue by iskil4** [home-assistant/home-assistant.github.io#32681]
### Feedback

It's been approximately three days since the generation and consumption graphs have had a problem, I couldn't identify the cause, maybe it was after the update, if anyone could give me an idea on how to debug it, I'd be grateful.
![Screenshot_20240510_132830_Home Assistant](https://github.com/home-assistant/home-assistant.io/assets/96750811/28165d95-7002-4831-937b-fe0b95b0a55e)
![Screenshot_20240510_132825_Home Assistant](https://github.com/home-assistant/home-assistant.io/assets/96750811/a8ad76e3-a3d5-428e-ac67-a02c08881b26)
![Screenshot_20240510_132808_Home Assistant](https://github.com/home-assistant/home-assistant.io/assets/96750811/b11aa143-ef3c-4bea-a92a-5cecba92bd8d)
![Screenshot_20240510_132820_Home Assistant](https://github.com/home-assistant/home-assistant.io/assets/96750811/060d3465-0596-4a42-85b3-c1a29ec757bd)

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2024.5.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
