### ISSUE TITLE
The documentation does not list where to put the offset information.

### ISSUE THREAD

**Issue by swa72** [home-assistant/home-assistant.github.io#32710]
### Feedback

The documentation does not list where to put the offset information.

### URL

https://www.home-assistant.io/integrations/workday/

**Comment by swa72** [comment]
I have to add that I now have realised that you can create more then one sensor ;-). I suggest to add this prominently to the top of the docs.

**Comment by gjohansson-ST** [comment]
Hi
Sorry but I don't get the comment. There is a field for offset in the config flow and I think that's pretty straight forward as with any other field?

We don't typically state that one can create more than one config entry as that's with most integrations that you can have several configs. That wouldn't be an exclusive comment for `workday` alone.

**Comment by gjohansson-ST** [comment]
As the description about offset is in the [documentation](https://www.home-assistant.io/integrations/workday/#specific-field-information) I'm going to close this issue.
