### ISSUE TITLE
Ezviz Integration support for Vacuum Cleaner

### ISSUE THREAD

**Issue by alintuca** [home-assistant/home-assistant.github.io#32714]
### Feedback

Ezviz integration do not offer support for Vacuum Cleaner

### URL

https://www.home-assistant.io/integrations/ezviz/

### Version

2024.5.3

**Comment by Vangreen** [comment]
+1

**Comment by SmTo81** [comment]
+1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
