### ISSUE TITLE
Motionblinds BLE controls inverted

### ISSUE THREAD

**Issue by GLSSoftware** [home-assistant/home-assistant.github.io#32748]
### Feedback

Motionblinds BLE controls are inverted (up is down, down is up). This affects also the position information (percentage).

### URL

https://www.home-assistant.io/integrations/motionblinds_ble/

### Version

2024.5.3

### Additional information

The roller motor can be mounted on the left or on the right side of the roller. 
This may be the reason that it is inverted (mine is mounted on the left side).

Suggestion:
Add an option "mounting position" or add an option "invert controls".

**Comment by LennP** [comment]
Hi GLSSoftware,

The Motionblinds BLE integration works exactly in the same way as the mobile application does, so if the direction of rotation is inverted in Home Assistant it should be in the mobile application as well. To change the direction of rotation of your blind, you can press the End Position button twice within a second. 

See page 8 of the manual:
https://publications.motionblinds.com/manual_setupguide_motion_cm-03-cm-05-cm-45-cmd-03-bluetooth/page/8-9

**Comment by GLSSoftware** [comment]
@LennP thank you very much for your fast response!
This issue can be closed.

kind regards

**Comment by LennP** [comment]
@home-assistant close
