### ISSUE TITLE
No control for Run Mode

### ISSUE THREAD

**Issue by vAFaLgCevpk3j6** [home-assistant/home-assistant.github.io#32766]
### Feedback

I have an American Standard HVAC.  In addition to "System Mode" and "Fan Mode", it has a "Run Mode".  The Run Mode has 2 settings: "Permanent Hold" and "Run Schedule".  The issue with the Thermostat Card is when I change a temperature setting, it overrides my programmed schedules.  It does not allow the programmed schedules to reactivate later in the day or at night.  I must use my phone app to "Run Schedule" to activate my programmed schedules.  My hope would be to add a further feature that allows me to execute the HVAC "Run Mode" and to select the existing options like "Permanent Hold" or "Run Schedule" through the Temperature card.

### URL

https://www.home-assistant.io/dashboards/thermostat/

### Version

2024.5.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
