### ISSUE TITLE
Can a daily production sensor be added

### ISSUE THREAD

**Issue by Chemist2** [home-assistant/home-assistant.github.io#32765]
### Feedback

http://www.curtronics.com/Solar/AuroraData.html has a daily production reading as well, can that be added as well?

### URL

https://www.home-assistant.io/integrations/aurora_abb_powerone/

### Version

2024.5.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
