### ISSUE TITLE
User Documentation needs updating

### ISSUE THREAD

**Issue by ronjtaylor** [home-assistant/home-assistant.github.io#32776]
### Feedback

I had to tick the SSL box even though I don't use HTTPS
![image](https://github.com/home-assistant/home-assistant.io/assets/46874942/ebe62e96-d1cf-45c9-a13f-4d03c86570ad)

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2024.5.3

**Comment by bieniu** [comment]
Please describe the problem thoroughly. It's hard to understand the configuration of the Shelly device and the configuration of your HA server based on one screenshot. Thanks.

**Comment by ronjtaylor** [comment]
I am running
![image](https://github.com/home-assistant/home-assistant.io/assets/46874942/cb3b892d-a2fa-4535-9e75-fb3c8c67a733)
![image](https://github.com/home-assistant/home-assistant.io/assets/46874942/baeb466a-c126-4ca0-a0ec-d8f5a24a0ca5)

**I followed this documentation**

Generation 2 and 3 devices use the RPC protocol to communicate with the integration. Battery operated devices (even if USB connected) need manual outbound WebSocket configuration, Navigate to the local IP address of your Shelly device, Settings >> Connectivity >> Outbound WebSocket and check the box Enable Outbound WebSocket, under server enter the following address:

_**ws:// + Home_Assistant_local_ip_address:Port + /api/shelly/ws (for example: ws://192.168.1.100:8123/api/shelly/ws), click Apply to save the settings. In case your installation is set up to use SSL encryption (HTTPS with certificate), an additional s needs to be added to the WebSocket protocol, too, so that it reads wss:// (for example: wss://192.168.1.100:8123/api/shelly/ws).**_

It did not work as I expected as I had no entities.

I viewed this [YouTube](https://youtu.be/0kWFxef2oyo?si=D6PcF5rXSf4lb9KE) and it gave me a few ideas so I did some googling and in one forum it suggested ticking the SSL box.
 I had not ticked this because my HA installation is only HTTP (not HTTPS) and I use Nabu Casa.
 
 Once I ticked the SSL Box as per screenshot, saved an rebooted I had Entities

I hope that describes the documentation issue problem

**Comment by bieniu** [comment]
If your HA instance does not use SSL, you should use `ws://`. There is no `SSL connectivity` option in the Shelly device webpanel. Integration with Shelly is based on local communication, so what is important is what is available in the device's webpanel, not in the Shelly cloud application.

![obraz](https://github.com/home-assistant/home-assistant.io/assets/478555/d0abed77-0b6d-4043-b88f-ca8a09a6d7c0)

**Comment by ronjtaylor** [comment]
Well that is exactly what I tried first (as per the video) but still no entities?
I did not get any entities until I ticked the ssl box.
I don't get it.  The device is now in my shed and because its asleep I can't get at it at the moment.

**Comment by chemelli74** [comment]
@ronjtaylor as suggested by Bieniu, please use device Web interface when configuring and not Shelly Mobile App.
