### ISSUE TITLE
New Aux Heat Switch Does Not Work

### ISSUE THREAD

**Issue by xinde1989** [home-assistant/home-assistant.github.io#32773]
### Feedback

The latest Aux Heat Switch doesn't work. The old Climate Aux Heat service works fine. 

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2024.5.3

**Comment by frenck** [comment]
Hi there @xinde1989 👋 

It seems like you want to report an issue with an Home Assistant integration; However, you have submitted documentation feedback instead. There is no amount of documentation we can adjust to fix a bug in our codebase. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
