### ISSUE TITLE
Slide (Innovation in Motion) discontinued

### ISSUE THREAD

**Issue by PierreLevres** [home-assistant/home-assistant.github.io#32796]
### Feedback

Innovation in Motion, supplier of Slide, ceases to deliver services within a short while. People should move to the local API. Yet the local API is not yet implemented in Home Assistant.
There is a custom component available at the moment, but modifying this integration would be better?

### URL

https://www.home-assistant.io/integrations/slide/

### Version

2024.5.3

**Comment by ualex73** [comment]
Yes, there is a custom integration available: https://github.com/ualex73/slide. I agree it should be nicer to include it into Home-Assistant, but I did not the time to do that (currently it is still using yaml, which is not allowed anymore).

**Comment by PierreLevres** [comment]
> Yes, there is a custom integration available: https://github.com/ualex73/slide. I agree it should be nicer to include it into Home-Assistant, but I did not the time to do that (currently it is still using yaml, which is not allowed anymore).

I understand, it would be a breaking change to implement just the local API, and cumbersome to have two seperate configuration flows..

**Comment by MrBlue90** [comment]
I've been in touch with Kaj Beetstra, the owner/developer of Slide.

Besides the local API (documents can be found [here](https://kxbx.stackstorage.com/s/jYOGsnnGoltKzTZY/nl)), you can also use the following Homekit code to connect to your Slide: `385-84-883`

**Comment by ualex73** [comment]
There is a PR for it: https://github.com/home-assistant/core/pull/117872

**Comment by frenck** [comment]
As we have a PR open to address this in the Core repository, I'll go ahead and close up this documentation feedback (as there is no actionable part for us on this end).

../Frenck
