### ISSUE TITLE
how to probe state of insteon device?

### ISSUE THREAD

**Issue by dduff617** [home-assistant/home-assistant.github.io#32795]
### Feedback

in the process of setting up, managing, and troubleshooting a network of insteon devices, there are multiple ways that states of devices and entities for insteon devices can become out of sync with the states of corresponding devices in the network.     obviously insteon packets (in either direction between PLM and device) can be lost or dropped.   devices can sometimes not be set up correctly so as to cause them to report their state changes to the PLM.    also devices can also have responder links to other devices (including some possibly unknown to HA) that cause their state to be out of sync with HA.   

i propose that within the device view of an insteon device in HA that there should be a way for the user to request that HA bring its state into sync with the actual device.   at present afaik, the integration provides no such command/mechanism.   it  makes sense to me that this could be called "synchronize" or "reinterview" or something.    if such a command already exists, it would be good if it would be included in the docs.

i could also see benefits of possibly splitting this into two different commands - one that syncs _basic state_ info (on/off state for a switch, button states for a keypad, etc.) and would generally be assumed to be fast/reliable.    There could be another one that does _complete_ sync including device properties and links and understandably (given limits of Insteon protocol) might require multiple round-trip communications between PLM and device and therefore would take longer. 

i would further suggest that if in the process of doing a "sync" that the HA state is found to not be in sync with the device, that the discrepancy be noted so that it can be seen in the "logbook" pane that appears in the device view.  This would assist the user in identifying where there are recurring problems in their HA configuration/setup w.r.t. insteon - including detecting areas of their insteon network where comms are unreliable, failing devices, incorrect setup, missing links, etc.   I suggest also  that it would be useful to have be a command (possibly invoked as a service?) that does a sweep of all devices in the insteon network updating states, recording detected discrepancies in the logs.   ideally this sweep would be limited by default to non-sleeping devices (which for Insteon means non-battery-powered).

I realize that the concept described here has overlap with "read from device" and "write to device" operations that are already present in the three-dots menu available from the configuration view of a device.   afaik, those commands operate on properties/links but not the basic status (e.g. on-state of a switch).    

### URL

https://www.home-assistant.io/integrations/insteon/

### Version

2024.5.3

### Additional information

sorry, this started out as a documentation question then morphed more into a feature request for the insteon integration...    if it is more appropriate to post elsewhere, let me know.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
