### ISSUE TITLE
Get Samsung TV Device ID

### ISSUE THREAD

**Issue by Bashewa** [home-assistant/home-assistant.github.io#32811]
### Feedback

It seems it is issue to find , can one not list this with device info ? 

As needed below:

service: remote.send_command
target:
  device_id: **_72953f9b4c9863e28ddd52c87dcebe05_**
data:
  command:
    - KEY_MENU
    - KEY_RIGHT
    - KEY

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2024.5.3

**Comment by njpeterman** [comment]
Per https://community.home-assistant.io/t/device-id-entity-id-where-to-find/289230/4 , I was able to find this in the URL when opening the device in the UI.

**Comment by chemelli74** [comment]
Hi,

you should just:

-  go to Developer Tools -> Services
 - select `remote.send_command` as service
 - pick-up the device from the UI (if in yaml mode then "GO TO UI MODE")

If you want to see the value, just "GO TO YAML MODE".
