### ISSUE TITLE
Impossible to follow tutorial: Wi-Fi scan spinner spins indefinitely

### ISSUE THREAD

**Issue by java-devil** [home-assistant/home-assistant.github.io#32818]
### Feedback

Tutorial impossible to follow... M5 ATOM Echo flash process finishes successfully, however wi-fi network scan never finishes (spinner "pop-up" spins indefinitely). Both if I initiate the network scan immediately after the successful flash AND if I initiate it some other time by simply clicking "Connect".

I tested this behavior on:
- TWO Echos
- Several PCs
- Two different OSes
- Two different browsers
- Three different apartments with different networks

I see no other likely culprit other than the connection process itself (or my personal inability to somehow comprehend the full "complexity" of the tutorial :P)

Please advice if there is some more proper "technical" repository where I could submit this ticket to.

Cheers,
Adam

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2024.5.0

**Comment by gorcsev71** [comment]
happens to me as well ...

**Comment by rgbiernat** [comment]
Same here. It used to work previously.

**Comment by Dreadmond** [comment]
Me too. Any idea how to troubleshoot this?

**Comment by cerme0** [comment]
same here. so I'm not crazy. really waiting for help on this

**Comment by lkonings87** [comment]
same here.

**Comment by Edwintenhaaf** [comment]
same here

**Comment by lkonings87** [comment]
i flashed the atom echo with a wifi test and it with no problem found my wifi, so the issue is somehow imbedded in the flash from the url.

**Comment by rgbiernat** [comment]
> i flashed the atom echo with a wifi test and it with no problem found my wifi, so the issue is somehow imbedded in the flash from the url. 

Correct. I was also able to flash another image without problems.

**Comment by jesserockz** [comment]
Unfortunately there is an issue with the current firmware we released and I will have an updated firmware out in the next hour or so. 

Jesse

**Comment by jesserockz** [comment]
If you reinstall the firmware now from the website it is working.

**Comment by lkonings87** [comment]
i did yesterday. now when i booted up my computer the mouse cursor is moving around uncontrolably when thhe atom echo is connected to the usb port...

**Comment by PatrickSteiner** [comment]
Installation and WiFi scan works now ... but after boot this is all I get in the Logs

```ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6652
ho 0 tail 12 room 4
load:0x40078000,len:15052
load:0x40080400,len:3836
entry 0x4008069c
I (29) boot: ESP-IDF 4.4.7 2nd stage bootloader
I (29) boot: compile time 05:19:16
I (29) boot: Multicore bootloader
I (32) boot: chip revision: v1.1
I (36) boot.esp32: SPI Speed      : 40MHz
I (41) boot.esp32: SPI Mode       : DIO
I (45) boot.esp32: SPI Flash Size : 4MB
I (50) boot: Enabling RNG early entropy source...
I (55) boot: Partition Table:
I (59) boot: ## Label            Usage          Type ST Offset   Length
I (66) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (73) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (81) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (88) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (96) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (103) boot: End of partition table
I (108) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=40c80h (265344) map
I (212) esp_image: segment 1: paddr=00050ca8 vaddr=3ffbdb60 size=0513ch ( 20796) load
I (220) esp_image: segment 2: paddr=00055dec vaddr=40080000 size=0a22ch ( 41516) load
I (238) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=116c74h (1141876) map
I (651) esp_image: segment 4: paddr=00176c9c vaddr=4008a22c size=14d58h ( 85336) load
I (702) boot: Loaded app from partition at offset 0x10000
I (702) boot: Disabling RNG early entropy source...
I (713) cpu_start: Multicore app
I (713) cpu_start: Pro cpu up.
I (714) cpu_start: Starting app cpu, entry point is 0x40082c94
I (0) cpu_start: App cpu up.
I (734) cpu_start: Pro cpu start user code
I (734) cpu_start: cpu freq: 160000000
I (734) cpu_start: Application information:
I (738) cpu_start: Project name:     m5stack-atom-echo
I (744) cpu_start: App version:      2024.5.3
I (749) cpu_start: Compile time:     May 27 2024 05:18:01
I (755) cpu_start: ELF file SHA256:  ef10bb27159e5c44...
I (761) cpu_start: ESP-IDF:          4.4.7
I (766) cpu_start: Min chip rev:     v0.0
I (771) cpu_start: Max chip rev:     v3.99 
I (775) cpu_start: Chip rev:         v1.1
I (780) heap_init: Initializing. RAM available for dynamic allocation:
I (787) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (793) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (799) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (806) heap_init: At 3FFCCC20 len 000133E0 (76 KiB): DRAM
I (812) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (818) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (825) heap_init: At 4009EF84 len 0000107C (4 KiB): IRAM
I (832) spi_flash: detected chip: gd
I (835) spi_flash: flash io: dio
I (843) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.```

**Comment by lkonings87** [comment]
something is very wrong with this update. every time i reboot my computer something new happens when the atom echo is connected through usb. my mouse went haywire last time, this time it opened documents and did not let me change them. all works fine when i disconnect the atom echo from the usb.
