### ISSUE TITLE
Please allow to specfic network address for the climate

### ISSUE THREAD

**Issue by Muska-Ami** [home-assistant/home-assistant.github.io#32828]
### Feedback

In my network environment, I use a TL-SG1016DT switch, and a TP-LINK device in AP mode is connected downstream. In this case, Gree integration cannot scan the Gree connected to the TP-LINK router Wi-Fi. Air conditioning equipment. At this time, I cannot manually configure the IP address of the air conditioner through YAML or GUI, so I cannot use this integration. In addition, my IPP protocol device does not work properly, even if the IP address is specified.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2024.5.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
