### ISSUE TITLE
MFA not working

### ISSUE THREAD

**Issue by MichaelBuczek** [home-assistant/home-assistant.github.io#32820]
### Feedback

![image](https://github.com/home-assistant/home-assistant.io/assets/27769195/7714f449-baac-4302-bf3a-05cc5b1a3a01)

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2024.5.4

### Additional information

Just used the same user ID and password to log on to the web site. So nothing wrong there. But there is no option to enter the MFA details that Verisure requires for login.

**Comment by Gaafgeel** [comment]
Hi @MichaelBuczek I had the same issue a few days ago but got it working just a few minutes ago without any problems. Please try again?

**Comment by MichaelBuczek** [comment]
Seems to work for mew too now. Thank you!

**Comment by jginternational** [comment]
This is still a problem
