### ISSUE TITLE
Too new version of invertor?

### ISSUE THREAD

**Issue by frederikvoGIT** [home-assistant/home-assistant.github.io#32837]
### Feedback

After i reached out in https://github.com/home-assistant/core/issues/67953 for not being able to connect. I tought by myself that maybe the invertor is a too new version? (the new Sunnyboy Smart Energy 5.0 white with the black circle in the middle)

https://www.sma-benelux.com/producten/hybride-omvormers/sunny-boy-smart-energy

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2024.5.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
