### ISSUE TITLE
HomeKit Script Error

### ISSUE THREAD

**Issue by korsanmehmet** [home-assistant/home-assistant.github.io#32843]
### Feedback

Hello friends, I solved many of my problems in the homeassistant application.
But I have a problem with the brodlink in the scripts section.
For example, I have a brodlink pro device.
1-Samsung TV.
2-VuSolo2.
3-Lg Amp.

I combined them all in a single script, so;
When you say "Turn on living room television", it sends signals to 1-2-3 devices and turns them on.
When you say "Turn off living room television", it sends signals to 1-2-3 devices and turns them off.

I transfer the scripts I created as HomeKit scripts.
The switches and scripts that I transferred to the Home Kit appear on my iPhone.
I use the button (On living room TV, Off living room TV) to turn these three devices on and off.

I also have Apple HomePod Mini Speakers in my house, so even though it is a phone, Siri is on it.

As a Home Kit, all my devices on the phone have switches and scripts. HomePod Mini responds to my requests via Siri.
Switch devices such as Sonof Tuya are fine.

But when it comes to scripted content, it asks me this.

When I call the living room TV to turn it on, it asks (SHOULD IT BE TURNED ON? - SHOULD IT BE OFF). If I say open, the HUNGRY one opens.

When I call the living room TV to turn it off, it asks (SHALL IT TURN ON? - SHOULD IT BE OFF). Even if I tell it to close, it doesn't close.

When I call the living room TV to turn it off, it asks (SHALL IT TURN ON? - SHOULD IT BE OFF). If I say open, he TURNS IT OFF.

### URL

https://www.home-assistant.io/integrations/homekit/

### Version

2024.5.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
