### ISSUE TITLE
circuit ?

### ISSUE THREAD

**Issue by GregorB54321** [home-assistant/home-assistant.github.io#32865]
### Feedback

Where to get a complete list with all possibilities for ebusd.circuit for HA's configuration.yaml?

### URL

https://www.home-assistant.io/integrations/ebusd/

### Version

2024.5.4

### Additional information

I want to connect my Wolf heater but can not find any HowTo or if even possible...

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
