### ISSUE TITLE
Glances failing for Ubuntu 22.04.4 LTS workstation

### ISSUE THREAD

**Issue by christcb03** [home-assistant/home-assistant.github.io#32862]
### Feedback

I think the newest updates for the workstation upgraded glances to 4.0.5 and after this HA was unable to connect to the glances service. I have verified the website is up and running on port 61208 just as before but HA just won't connect anymore. Do I have to downgrade it or will this be supported in future releases?

### URL

https://www.home-assistant.io/integrations/glances/

### Version

2024.5.4

**Comment by engrbm87** [comment]
Hi, such issues should be reported under the core repository. 
https://github.com/home-assistant/core/pull/117664 has been raised to fix this.

**Comment by engrbm87** [comment]
@home-assistant close
