### ISSUE TITLE
there is no country Yugoslavia

### ISSUE THREAD

**Issue by tanchu** [home-assistant/home-assistant.github.io#32860]
### Feedback

Dear sirs, unfortunately there is no more country called Yugoslavia. Now we have few independent countries Montenegro, Serbia and Kosovo
Please change the cla_sign page countries list 

### URL

https://www.home-assistant.io/developers/cla_sign/

### Version

2024.5.4

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @tanchu :+1:

**Comment by c0ffeeca7** [comment]
Closing this issue as addressed by #32910, #32911, and #32912
