### ISSUE TITLE
Internet access in Integrations

### ISSUE THREAD

**Issue by johnmcd88** [home-assistant/home-assistant.github.io#32876]
### Feedback

Hi,

Would it be possible to add a section to each integration to provide information relating to whether or not Internet access is required during the setup or operation of each? Some of them have some basic information like whether a vendor account is required, but it's hard to determine if any given integration requires external network access to function.

Thanks

John

### URL

https://www.home-assistant.io/integrations/#all

### Version

2024.5.4

**Comment by klaasnicolaas** [comment]
You could see this based on the [IoT class](https://www.home-assistant.io/blog/2016/02/12/classifying-the-internet-of-things/#classifiers) which is in the description (right sidebar) of each integration. You can assume that all integrations with a cloud classifier require internet access.

./klaas

**Comment by johnmcd88** [comment]
Thank you. Is it safe to assume that any integration that has 'Cloud' in its IoT Class requires you to set up an account to make it work?

**Comment by frenck** [comment]
>  Is it safe to assume that any integration that has 'Cloud' in its IoT Class requires you to set up an account to make it work?

That is not a correct assumption. It indicates it uses the internet to gather information. If authentication is needed, and how the authentication process works, depends on the service that is being integrated. Information about the specific service, can best be obtained from the service itself.

../Frenck

**Comment by johnmcd88** [comment]
Thank you.
