### ISSUE TITLE
"Now Playing"

### ISSUE THREAD

**Issue by G8YTZ** [home-assistant/home-assistant.github.io#32887]
### Feedback

Is there a way of extracting the track/artist metadate in a text form so that I'm able to send to an WS LED Matrix? Current automation that displays only "Playing", "Paused", "Idle" etc. shown below to show the use case. 

`alias: Linn Media Player
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.openhome_uuid_4c494e4e_0026_0f21_c4be_01311712013f
      - media_player.linn_dining_room_upnp_av
    not_to:
      - unknown
      - unavailable
condition: []
action:
  - service: rest_command.wled_text
    metadata: {}
    data:
      text: >-
        {{states['media_player.openhome_uuid_4c494e4e_0026_0f21_c4be_01311712013f'].state}}
        #{{states['media_title.openhome_uuid_4c494e4e_0026_0f21_c4be_01311712013f'].string}}
mode: single`

### URL

https://www.home-assistant.io/integrations/openhome/

### Version

2024.5.4

**Comment by bazwilliams** [comment]
Hi, you should be able to extract the artist and title from the media player attributes. For example:

```
{{ state_attr('media_player.openhome_uuid_4c494e4e_0026_0f21_e768_01357060013f', 'media_title' ) }}
{{ state_attr('media_player.openhome_uuid_4c494e4e_0026_0f21_e768_01357060013f', 'media_artist' ) }}
```

**Comment by G8YTZ** [comment]
Many thanks Baz, I'll have a go with that.

**Comment by G8YTZ** [comment]
Baz, Susssed it - a typo in my yaml! Many thanks!
