### ISSUE TITLE
Energy consumption not shown since last HA update

### ISSUE THREAD

**Issue by x4N70pHyLL** [home-assistant/home-assistant.github.io#32895]
### Feedback

It seems my Vicare Integration does not show my energy consumption anymore since about 2 days - I suppose since the update to HA 2024.5.4

You can see it in the daily that is just 0 since then, however the history of the weekly (shown over a month) does not make sense anyways either.

Monthly seems okay but did not change since about a week. See the pictures below.

The values shown in the Vicare App seem to make sense, more specifically, I do have a consumption for today and yesterday there.

<img width="1428" alt="Bildschirmfoto 2024-05-22 um 21 29 43" src="https://github.com/home-assistant/home-assistant.io/assets/81616315/670e3294-7454-49af-905d-1f5abec75638">
<img width="1421" alt="Bildschirmfoto 2024-05-22 um 21 26 59" src="https://github.com/home-assistant/home-assistant.io/assets/81616315/0e921578-32d9-42c8-ae06-9e36806411d0">
<img width="1422" alt="Bildschirmfoto 2024-05-22 um 21 33 19" src="https://github.com/home-assistant/home-assistant.io/assets/81616315/4fb5d840-ca6a-40c4-bf10-42437333e4c3">

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2024.5.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by x4N70pHyLL** [comment]
Sorry thanks for the hint, that explains why I did not find the other issues I expected to be listet there...
