### ISSUE TITLE
插座无法完全找到所有实体。

### ISSUE THREAD

**Issue by yang197788** [home-assistant/home-assistant.github.io#32904]
### Feedback

插座或者开关设备里面超过6个以上的实体无法查找出来，16个组合只能搜索到6个.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.5.4

**Comment by klaasnicolaas** [comment]
The main language used by Home Assistant is English, we now have no idea what you are trying to say.

./Klaas
