### ISSUE TITLE
Inkbird

### ISSUE THREAD

**Issue by pcechak123** [home-assistant/home-assistant.github.io#32908]
### Feedback

During adding process for Inkbird I didn't get any Inkbird devices list. Can you help ?

### URL

https://www.home-assistant.io/integrations/inkbird/

### Version

2024.5.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
