### ISSUE TITLE
Z-Wave JS now supports 800

### ISSUE THREAD

**Issue by jmwhite5** [home-assistant/home-assistant.github.io#32918]
### Feedback

The following note needs to be removed (as of April 2024, it is now supported, see https://github.com/zwave-js/node-zwave-js/issues/5257 )

Controller notes

800 SERIES CONTROLLERS

**Z-Wave JS does not support Z-Wave Long Range yet.**

### URL

https://www.home-assistant.io/docs/z-wave/controllers/

### Version

2024.5.4

**Comment by frenck** [comment]
Z-Wave JS does support it, Home Assistant doesn't handle this yet (no way of adding a device using LR).

This is expected to land in a future release of Home Assistant.

../Frenck
