### ISSUE TITLE
A local UniFi user is needed

### ISSUE THREAD

**Issue by jiiins** [home-assistant/home-assistant.github.io#32942]
### Feedback

I think that after enabling the MFA (mandatory from july 2024), it's necessary to create a local user in UniFi OS to be used in the integration's config wizard. Or at least this is what happened to me and other users.

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.5.5

**Comment by Kane610** [comment]
The documentation has always stated you need to create a local user.
