### ISSUE TITLE
vicare authentification fails with Umlauts in the password

### ISSUE THREAD

**Issue by S-Weigel** [home-assistant/home-assistant.github.io#32943]
### Feedback

**Thank you very much for providing and mainting this integration!!!**

Finaly I was able to pass the authentification. Nearly I gave up trying to get this integration to run. I really tried everything recommended and and many combinations. Beside others I removed all special characters from my password altough few wrote they didn't have problems with special characters.

After many tries and after even my login to the viessmann account was blocked I gave up. (Fortunatly they seem to unlock the account atomatically after a short time.)

Today I gave it two last tries finally removing an "ü" from the password which I as German do not even consider as special character. 
BINGO!

Could you please add a hint to the docu. That might help others.

By the way: I could not imagine that it makes a difference from which device I use the browser to setup the integration since every logic happens on the home assistant os anyway. Nevertheless I also tried this due to the note on the help page. But finally this was not necessary. Maybe think about removing this.

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2024.5.5

**Comment by CFenner** [comment]
I think no one did the effort to update the docs, but this is still valid.

**Comment by CFenner** [comment]
> By the way: I could not imagine that it makes a difference from which device I use the browser to setup the integration since every logic happens on the home assistant os anyway. Nevertheless I also tried this due to the note on the help page. But finally this was not necessary. Maybe think about removing this.

I think you need to allow the clientID to access your user, this is a once in a lifetime (of the user account) action. I think I did something about 2 year ago, but as I cannot unlink the client I cannot validate that.
