### ISSUE TITLE
Bond Pro Hub - Not Working Suddenly

### ISSUE THREAD

**Issue by JPDFW** [home-assistant/home-assistant.github.io#32946]
### Feedback

The past two updates seem to cause problems with Bond Pro Hub. Eventually after the last round the hub came back on line. This kills a major need in my home automate beacause of using it to control my electric blinds. Is there any known issues that are being raise? I am just getting failed to load. 

### URL

https://www.home-assistant.io/integrations/bond/

### Version

2024.5.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
