### ISSUE TITLE
How to control the Growatt inverter

### ISSUE THREAD

**Issue by rowanbradley** [home-assistant/home-assistant.github.io#32944]
### Feedback

Your existing instructions do not explain at all how to change the settings of the Growatt hybrid inverter from within Home Assistant. This would be a worthwhile addition you your instructions.

Thank you - Rowan

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.5.5

**Comment by frenck** [comment]
Hi there @rowanbradley 👋 

There are no controls; hence, there are none documented.

../Frenck
