### ISSUE TITLE
Change unit of measurement

### ISSUE THREAD

**Issue by siperdudeuk** [home-assistant/home-assistant.github.io#32958]
### Feedback

Please add the function to air conditioner controller to set the temperature in both Celsius and Fahrenheit as currently only shows the option for Fahrenheit 

### URL

https://www.home-assistant.io/integrations/melcloud/

### Version

2024.5.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
