### ISSUE TITLE
"Set up development environment" vs code dev container "open" button not working

### ISSUE THREAD

**Issue by joedzado** [home-assistant/home-assistant.github.io#32955]
### Feedback

https://developers.home-assistant.io/docs/development_environment/ has a button to open up VS code and magically create the development environment. It doesn't work.  In Safari it says "Safari cannot open the page because the address is invalid.",  in Firefox it says "The address wasn’t understood", in Chrome it just opens the tab and never resolves. 

In digging, it seems the url prefix to open things with vs code may not work anymore? But this dev container is still a great idea.

The request here is to update the documentation to instruct the user to do what the link was doing, namely: 

1. Open VS Code
2. Ctrl-Shift-P "Dev Containers: Clone Repository in Container Volume"
3. Paste in your forked repo URL
4.  Let it build. 
<img width="751" alt="Screenshot 2024-05-26 at 1 28 23 PM" src="https://github.com/home-assistant/home-assistant.io/assets/550564/edf63416-fe40-4770-9fa1-d7c3bd4e667e">

<img width="722" alt="Screenshot 2024-05-26 at 1 26 58 PM" src="https://github.com/home-assistant/home-assistant.io/assets/550564/5f02fff0-b60d-4dca-9ae0-baa5d01cb73d">

<img width="1278" alt="Screenshot 2024-05-26 at 1 26 06 PM" src="https://github.com/home-assistant/home-assistant.io/assets/550564/f5efd105-83c4-4abf-94c2-81ccfda3424b">

<img width="859" alt="Screenshot 2024-05-26 at 1 25 30 PM" src="https://github.com/home-assistant/home-assistant.io/assets/550564/979011b7-0f55-4f52-9ee7-bf8e8b309523">

### URL

https://developers.home-assistant.io/docs/development_environment/

**Comment by klaasnicolaas** [comment]
This belongs in the developers repository.

./Klaas
