### ISSUE TITLE
Media Title content does not display correctly

### ISSUE THREAD

**Issue by G8YTZ** [home-assistant/home-assistant.github.io#32951]
### Feedback

Media Title content does not display correctly; special characters do not display correctly. (I assume it is the way YAML handles text strings).

For example: (Artist/Track) Nora Jones - Sinkin' Soon is displayed incorrectly (see pictures)

Linn front panel display shows correct syntax.

Same source playing on Apple TV Media Player is ok , see pictures below.

<img width="354" alt="Screenshot 2024-05-26 at 11 52 44" src="https://github.com/home-assistant/home-assistant.io/assets/35895759/c8bc16ae-c107-43cf-9b2a-a583afe100d0">

<img width="349" alt="Screenshot 2024-05-26 at 11 58 17" src="https://github.com/home-assistant/home-assistant.io/assets/35895759/3229bf93-5da6-4d50-bdf1-061e919978be">

### URL

https://www.home-assistant.io/integrations/openhome/

### Version

2024.5.5

**Comment by bazwilliams** [comment]
I've seen this. It looks like a double escaping bug in the library I've written, I'll need to investigate why it's doing that.

**Comment by G8YTZ** [comment]
Thanks Barry,

It would be great to get that resolved, it's still a great integration though. I really appreciate you taking the time to write it.

Justin

**Comment by bazwilliams** [comment]
Quick update on this - the upstream library has a fix for this https://github.com/bazwilliams/openhomedevice/releases/tag/2.3 this week I'll test it within Home Assistant and get a PR up for it.

**Comment by G8YTZ** [comment]
Barry, that's great news. I'm looking forward to trying it out. As a matter of interest do you work for Linn? 
Justin.

**Comment by G8YTZ** [comment]
Please can you reopen this as a fix is being worked on
