### ISSUE TITLE
Bosch SHC Integration

### ISSUE THREAD

**Issue by barthel-eu** [home-assistant/home-assistant.github.io#32979]
### Feedback

It would be _**very**_ nice to add a note to the Bosch SHC integration information, that Bosch Cameras are **_not_** integrated. They use an island-solution that even with the Bosch Apps work insufficient.

### URL

https://www.home-assistant.io/integrations/bosch_shc/

### Version

2024.5.5

### Additional information

Detail: **Bosch Smart Camera App** (part of installation) shows full screen and allows zooming. It does not even integrate with the Bosch-branded Yale Linus door opener (August integration). The **Bosch Smart Home App** shows only in portrait mode the full camera image, but does not allow zooming. Here you can trigger the Yale door opener, though with a major delay.
The delay results (2-3 seconds usually, I also had more than 5 seconds) from the Bosch Cameras not being local push, they require a "SingleKey ID", all pictures are stored on Bosch servers and in case of update on those, the cameras become unusable.
Interesting side effect. Having the Bosch Smart Home App on one and the Bosch Camera App on another phone, the Camera App beats the Smart Home one clearly in reaction speed.

But it boils all down to: The Bosch Cameras are not compatible and not part of the Bosch SHC integration.

**Comment by tschamm** [comment]
Support for the camera platform is not mentioned in the official integration, right?

The custom component has some support, but you're right that the Bosch camera app provides more functionality than what is available via the official API.

Still, as nothing can be changed here, that issue is invalid.

**Comment by barthel-eu** [comment]
I think it will avoid frustrations like the one I encountered, as Bosch markets the camera as "Smart Home" and refers that it will be usable with the smart home controller (Bosch SHC) which then is crippled even on the Bosch Apps. So a short line saying the Bosch Cameras are not supported (yet) will help to avoid wrong expectations. Yes, I know, it says what is included and camera is not mentioned, but that's different from saying that the camera is not supported.
And very clearly: Yes, this is a Bosch problem. But one that Home Assistant users might want to be better aware before buying incompatible hardware? A helpful note in the page would such be valuable.
