### ISSUE TITLE
Quiero añadir impresora

### ISSUE THREAD

**Issue by EA1APG** [home-assistant/home-assistant.github.io#32974]
### Feedback

Quiero añadir mi impresora Laser Brother a mí Home Assistant, pero me pide Host*, pero no sé lo que es, alguien me puede ayudar.
Gracias y un saludo ERNESTO

### URL

https://www.home-assistant.io/integrations/brother/

### Version

2024.5.5

**Comment by bieniu** [comment]
Please write the title and description of the issue in English or the issue will be closed.

**Comment by klaasnicolaas** [comment]
a host is the hostname or IP address of the device you want to connect to.

./Klaas
