### ISSUE TITLE
Dynamic prices

### ISSUE THREAD

**Issue by mgmooij** [home-assistant/home-assistant.github.io#32980]
### Feedback

I have dynamic prices in my Homewizard Energy app setup, why not make them available in Home Assistant?

### URL

https://www.home-assistant.io/integrations/homewizard/

### Version

2024.5.5

**Comment by DCSBL** [comment]
Hi! This is a feature that is available in the HomeWizard app. The HomeWizard integration only adds sensors for your P1 meter (or other HomeWizard devices) and does not know anything about prices or your energy contract.

You can, for example, use the [EnergyZero integration](https://www.home-assistant.io/integrations/energyzero/) that tracks the dynamic prices.

I recommend to ask about this on the [Home Assistant forum or on Discord](https://www.home-assistant.io/help/), as this issuetracker is intended for issues regarding the documentation, not for questions _about_ the documentation 😉.

**Comment by DCSBL** [comment]
@home-assistant close
