### ISSUE TITLE
Support for non-numeric pin codes

### ISSUE THREAD

**Issue by dybzon** [home-assistant/home-assistant.github.io#32990]
### Feedback

The current configuration for worxlandroid requires a numeric pin code.

Not all Worx Landroid mowers use numeric pin codes. See their [docs here](https://wiki.worx.com/en/how-to-change-pin-code). 

I have a model WR142E myself. This one uses a pin code consisting of four characters from A to D. For example DCBA or ABCD.

I've tried adding my non-numeric pincode to `configuration.yaml`:

```yml
# Add Worx Landroid lawn mower
sensor:
  platform: worxlandroid
  host: 192.168.12.34
  pin: ABCD
```

When I test my configuration afterwards I get this message, indicating that all four characters in the pincode must be numeric:
`Invalid config for 'worxlandroid' from integration 'sensor' at configuration.yaml, line 17: does not match regular expression \d{4} for dictionary value 'pin', got 'ABCD'`

Are there any plans of supporting the range of models that use non numeric pin codes? Or is this simply an oversight in the implementation?

### URL

https://www.home-assistant.io/integrations/worxlandroid/

### Version

2024.5.5

**Comment by Jabol86** [comment]
Why it was closed as problem still exists for many landroid models?
