### ISSUE TITLE
Growatt integration not complete

### ISSUE THREAD

**Issue by ErHaahr** [home-assistant/home-assistant.github.io#32998]
### Feedback

The Growatt Solar Inverter integration does not allow you to select the relevant values for the Energy view in Home Assistant.

You can only select the total lifetime energy production and not the daily production, though they have the same measurement unit (kWh).

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.5.5

**Comment by klaasnicolaas** [comment]
Hi there @ 👋

It doesn't matter whether you use a day or lifetime entity in the energy dashboard, the result will be the same.

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
