### ISSUE TITLE
missing opower providers

### ISSUE THREAD

**Issue by bluedog1967** [home-assistant/home-assistant.github.io#33002]
### Feedback

The home assistant integration page shows compatibility with AEP but it is currently missing from the integration when you go to set it up.

### URL

https://www.home-assistant.io/integrations/aep_texas/

### Version

2024.5.5

**Comment by tronikos** [comment]
It's there on my end. See:
![image](https://github.com/home-assistant/home-assistant.io/assets/9987465/5e304fa2-8e99-4b5d-8d08-ee2698efe070)
Can you post a screenshot?

**Comment by bluedog1967** [comment]
![IMG_5708](https://github.com/home-assistant/home-assistant.io/assets/106817125/3b15aa11-446f-4a80-8d45-45e1d78faf7e)

**Comment by tronikos** [comment]
What's your installation method of HA?
Home Assistant Operating System
Home Assistant Container
Home Assistant Core
Home Assistant Supervised

**Comment by bluedog1967** [comment]
It was installed on proxmox using Proxmox VE Helper-Scripts for the Home assistant container

**Comment by tronikos** [comment]
My guess is you are using the core installation and you haven't updated opower. Run `pip show opower` to show you the version installed. You will have to install the latest version with: `pip install opower==0.4.6`

**Comment by tronikos** [comment]
Then you must be using Home Assistant Operating System
Install the Advanced SSH & Web Terminal addon, uncheck Protection mode, start it, open web ui and run:

```
docker exec -it $(docker ps -f name=homeassistant -q) bash
pip show opower
```

It should return `0.4.4`. If not, pip install it.

**Comment by bluedog1967** [comment]
Is there any config I need to change after updating? When I launch opower in the gui it downgrades it back to version 0.0.39

**Comment by bluedog1967** [comment]
Was able to get it working by updating the entire container in proxmox instead of the gui thanks for the help

**Comment by tronikos** [comment]
@home-assistant close
