### ISSUE TITLE
Gardena moisture sensor

### ISSUE THREAD

**Issue by sergiosimone** [home-assistant/home-assistant.github.io#33007]
### Feedback

Hi!

This page states that the Gardena Bluetooth integration is compatible with Gardena's 1867-20 Soil Moisture Sensor, which doesn't seem to support bluetooth based on Gardena specs (wired only). Do you mean 19040-20 Smart Sensor instead?

A huge thank you!

### URL

https://www.home-assistant.io/integrations/gardena_bluetooth/

### Version

2024.5.5

**Comment by elupus** [comment]
Un clear. The water valve can support a hooked up sensor
