### ISSUE TITLE
Unknown error occurred with Unifi network integration

### ISSUE THREAD

**Issue by adam-jones-net** [home-assistant/home-assistant.github.io#33012]
### Feedback

Something that isn't 100% clear to me is what the host should be. Is the it the IP of my Unifi controller device ? Or the USG ?  Or even a cloud url for the cloud service ?

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.5.5

### Additional information

I've uploaded a log that I believe is related to issues connecting when I am trying to connect to my Unifi controller IP, which I am assuming is the correct host.

[log.txt](https://github.com/home-assistant/home-assistant.io/files/15505636/log.txt)

**Comment by Kane610** [comment]
You have unauthorized and forbidden errors in youe log. Check your account for proper access to the network application.

In the future report issues in the core repo
