### ISSUE TITLE
Is it possible to add talk commands via compatible Sonos speakers (like possible in Smartthings) ?

### ISSUE THREAD

**Issue by adam-jones-net** [home-assistant/home-assistant.github.io#33013]
### Feedback

The title says it all really. From playing around and reading the help it doesn't seem that the integration supports this currently ?

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2024.5.5

**Comment by jjlawren** [comment]
No, it's not currently possible to access the microphones or trigger events based on voice.

**Comment by adam-jones-net** [comment]
To clarify, those two functions are not what I requested.    Apologies, I see how my title could have been missinterpreted.

What I'm referring to is the audioClip API which is really powerful.    Smartthings is compatible with audioClip endpoints in the Sonos API so you can configure notifications to be spoken to any Sonos speaker you have.    

It seems that behind the scenes SmartThings is generating the spoken voice file and then sending to the sonos.  That's my crude understanding at least.   It does happen very fast but I think that is how it works.

**Comment by PeteRager** [comment]
That's what the announce option is for on the play media service call

**Comment by adam-jones-net** [comment]
> That's what the announce option is for on the play media service call

Ahh OK thanks that's clear. I'd suggest still that the sonos documentation is slightly updated to make this great feature even clear by adding to the controllable features list.

**Comment by PeteRager** [comment]
> > That's what the announce option is for on the play media service call
> 
> Ahh OK thanks that's clear. I'd suggest still that the sonos documentation is slightly updated to make this great feature even clear by adding to the controllable features list.

submit a PR with your suggested documentation change.
