### ISSUE TITLE
Probably not a good idea to have coderabbitai bot enabled in home-assistant.io repository?

### ISSUE THREAD

**Issue by Hedda** [home-assistant/home-assistant.github.io#33020]
### Feedback

This home-assistant.io repository is meant to contain documentation and not code, so probably a good to disable the coderabbitai bot in this home-assistant.io repository as it is primarily a large language model that is designed to comment on code, not docs, or?

https://github.com/apps/coderabbitai

Right now the coderabbitai bot seems to be reviewing each commit and each time replying with a comment on that section.

### URL

https://github.com/home-assistant/home-assistant.io

**Comment by frenck** [comment]
We are currently testing the tool on our repositories. We see mixed results, both good and some lesser ideal. But in general, pretty good.

CodeRabbit contains language tools (and they are extending that in the near future with tooling to enforce language writing guides like the Microsoft styling guide we use).

If you see anything weird, please do report it with CodeRabbit. I've provided multiple feedback and issues at this point, almost all have been addressed by them in a fast pace.

In the end, please keep in mind these are LLMs. They can be helpful, but not always right.

../Frenck
