### ISSUE TITLE
Reolink Camera discovery

### ISSUE THREAD

**Issue by SinghForceOne** [home-assistant/home-assistant.github.io#33029]
### Feedback

Just a tip worth noting in the documentation;- that for the HA Reolink Integration discovery, some Reolink IP Cameras like the RLC-423, require their device Configuration from the Reolink app to ensure you enable UPnP >  

- **Network/Advanced/UPnP**  is enabled. 
- This ensures the the camera using a DHCP IP connection is not lost on a camera reboot and is re-discoverable by HA.

Screenshot taken from the: Windows Reolink Client Application.
![ReoLink UPnP Win Client](https://github.com/home-assistant/home-assistant.io/assets/112807121/b5434656-a912-4cc7-b435-4272d8b61a93)
 

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.5.5

**Comment by starkillerOG** [comment]
@SinghForceOne intresting suggestions, I will also look into added SSDP discovery based on this UPnP if I can get that to work.

Will keep you posted if I manage to get this to work.

**Comment by starkillerOG** [comment]
I tried this out, but I was unable to find any Reolink camera using SSDP discovery, even when UPNP setting was turend on.
