### ISSUE TITLE
Info about cleaning a specific room is wrong

### ISSUE THREAD

**Issue by ScuttleSE** [home-assistant/home-assistant.github.io#33038]
### Feedback

"Go to Developer Tools > Services > Roborock: Get maps."

1. the links points to https://my.home-assistant.io/redirect/developer_call_service?service=vacuum.send_command, not get maps
2. There is no service called "Get maps"

### URL

https://www.home-assistant.io/integrations/roborock/

### Version

2024.5.5

**Comment by Lash-L** [comment]
You're right I do need to fix the link. But the get maps service does exist. You need to update your home assistant instance though

**Comment by ScuttleSE** [comment]
Correct, seems like my HASS installation was outdated. After updating the get maps service popped up
