### ISSUE TITLE
Incomplete information in "Flash Silicon Labs radio firmware manually"

### ISSUE THREAD

**Issue by SavanFlou** [home-assistant/home-assistant.github.io#33030]
### Feedback

Hello,
I bought the Yellow Home Assistant some months ago and discovered this morning I have to flash the driver of the Zigbee part.
Ok, why not, let's try.

> SSH & Web Terminal (from the Community Add-ons section, make sure to disable "Protection mode" to get direct hardware access)

Small but important mistake, we need the "ADVANCED" version, otherwise there is no "Protection mode" available.

OK so I installed the advanced one, config it, started to follow the process and...

> flash --allow-cross-flashing --firmware <firmware-file>

Ok but where can I find this firmware file name for my Home Assistant Yellow?

### URL

https://github.com/NabuCasa/silabs-firmware/wiki/Flash-Silicon-Labs-radio-firmware-manually

### Version

2024.5.5

### Additional information

You indicate we have to disable ZHA, but it should be the same with MQTT, right?

**Comment by SavanFlou** [comment]
So to complete,
the code should be (I think)

```
$ cd silabs-firmware
$ universal-silabs-flasher --device /dev/ttyAMA1 \
    flash --allow-cross-flashing --firmware EmberZNet/NabuCasa_Yellow_EZSP_v6.10.3.0_PA32_ncp-uart-hw_115200.gbl
```
The flash worked but that does not fix the problem, Z2M still does not work.

**Comment by c0ffeeca7** [comment]
Thank you for reaching out. 
We use this GitHub issue tracker specifically for documentation issues, not for providing support.
For support, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).
