### ISSUE TITLE
Add event when opening : who's PIN code was used to open the door

### ISSUE THREAD

**Issue by HansVanEylen** [home-assistant/home-assistant.github.io#33034]
### Feedback

Would it be possible to add an event/sensor when the lock is opened which contains the username who's PIN code was used to open the door? This would allow to automate actions based on the person who opened the door.

### URL

https://www.home-assistant.io/integrations/tedee/

### Version

2024.5.5

**Comment by HansVanEylen** [comment]
This information is available in the Tedee app in the history, so it might also be possible to include this as an extra sensor?

**Comment by zweckj** [comment]
This information is unfortunately (at this moment) not available via the local only endpoints, which this integration uses. If you want that feature it's best to ask tedee first to add support. 
Closing this for now then.

**Comment by zweckj** [comment]
@home-assistant close

**Comment by HansVanEylen** [comment]
ok, thanks for the quick feedback. A support request has been raised with Tedee.
