### ISSUE TITLE
Can't add P100 or P110 plugs

### ISSUE THREAD

**Issue by GitSlinger** [home-assistant/home-assistant.github.io#33049]
### Feedback

I have around 20 P100 and P110 smart plugs in my home. Every time I try and add one, it finds them all automatically, but when I enter my TP Link cloud login details (which I've checked several times, is correct), I just get the following error:
`Invalid authentication: Server response doesn't match our challenge on ip 192.168.68.67`

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.5.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
