### ISSUE TITLE
SleepNumber integration docs

### ISSUE THREAD

**Issue by ehcloninger** [home-assistant/home-assistant.github.io#33047]
### Feedback

Wasn't sure of the protocol for submitting docs changes. I didn't want to clone and go thru the PR process for a 1 line docs change. 

I had issues getting the configuration to work and it had me stumped for a while. Then, I remember I have specific rules in my pihole to keep the bed from phoning home so much. I suggest adding a line such as

_If you are using a DNS-based ad-blocker, you may need to disable it temporarily while configuring this item in Home Assistant._

### URL

https://www.home-assistant.io/integrations/sleepiq/

### Version

2024.5.5

**Comment by kbickar** [comment]
It's gonna need a pr if you do it or we do. Which address was being blocked?

**Comment by ehcloninger** [comment]
@kbickar I had a regex block for (.|^)sleepnumber.com$ and an allowlist for svcsleepiq.sleepnumber.com. The problem with their bed is it sends something like 100,000 requests per day to firehose.us-east-1.amazonaws.com and I was trying to contain that a bit. 

As a rule, I don't like giving any company that much access to data without knowing what it is. Especially that sleep data is medical data.

I don't mind doing a PR. I'm a developer in my other life. I'm just starting out with HA and trying to understand the culture.

**Comment by kbickar** [comment]
Interesting, it's probably the bed itself making those requests as the integration only connects to the one endpoint once a minute

**Comment by ehcloninger** [comment]
@kbickar My first PR to home-assistant, so I hope I followed the process correctly.

https://github.com/home-assistant/home-assistant.io/pull/33061
