### ISSUE TITLE
Will not accept API token

### ISSUE THREAD

**Issue by KB8DOA** [home-assistant/home-assistant.github.io#33046]
### Feedback

Tried to add this integration.
But it clearly will not accept my API token:
![image](https://github.com/home-assistant/home-assistant.io/assets/51223218/8e4582fd-a2f5-431f-8c9c-0c8b9bbd3170)

### URL

https://www.home-assistant.io/integrations/weatherflow_cloud/

### Version

2024.5.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
