### ISSUE TITLE
in version 2024.6 that stop work

### ISSUE THREAD

**Issue by etamarsar** [home-assistant/home-assistant.github.io#33044]
### Feedback

after update to 2024.6 version i receive message that it's not work .
![Screenshot_5](https://github.com/home-assistant/home-assistant.io/assets/74599483/d3311099-6bbc-4b83-ac0b-2d57cbb27c5a)

### URL

https://www.home-assistant.io/integrations/jewish_calendar/

### Version

2024.6.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by tsvi** [comment]
The Jewish calendar integration has moved in 2024.6 from YAML configuration to UI configuration.
This message tells you to remove the YAML  configuration. The integration should have been imported automatically into the UI.
