### ISSUE TITLE
Add notice to Loqed on cessation of company

### ISSUE THREAD

**Issue by LordMike** [home-assistant/home-assistant.github.io#33055]
### Feedback

https://loqed.com/en/important-announcement-from-loqed/

Loqed announced a short while ago, 2024-05-22, that they had declared bankruptcy. They will therefore at some point stop their services - they mentioned a `LOQED Online Foundation`, which may continue the serverside operations, but I think it should at least be considered:

* A notice on the integration about this - I know I usually find out if a product is future proofed by viewing the HA docs on the integration of it.
* A once-over of the code, to ensure that there isn't any place where the integration might stop working, if any serverside component of Loqed stopped working.

### URL

https://www.home-assistant.io/integrations/loqed/

### Version

2024.5.5

**Comment by mikewoudenberg** [comment]
Hey, thanks for reaching out.

The bankruptcy of Loqed is still being handled and as soon as there is clarity on the future, this integration will be adjusted. With regars to the points you mentioned:

- I would rely on the website of the actual vendor to decide the future-proofness, not on some integration in a piece of home automation software. The homepage of Loqed.com clearly states their current situation.
-  The integration only relies on the cloud part of Loqed for the initial setup. Once that is done it will use the locally stored key material and connect directly to your local bridge.

Once the future for Loqed is clear this integration will be adjusted as needed. Until then it is fine as is.

**Comment by LordMike** [comment]
Great.

Here's to hoping that should Loqed disappear completely, the setup can be made to work locally.

Should this issue be closed until more is known?

**Comment by mikewoudenberg** [comment]
Yeah I'll close it for now.

**Comment by mikewoudenberg** [comment]
@home-assistant close
