### ISSUE TITLE
Unable to add j7+

### ISSUE THREAD

**Issue by GitSlinger** [home-assistant/home-assistant.github.io#33050]
### Feedback

I'm guessing there's still no fix for this? 
I've ensured the app is closed and completely stopped on my phone but it never finds the password. 

### URL

https://www.home-assistant.io/integrations/roomba/

### Version

2024.5.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
