### ISSUE TITLE
Integration Tami4 - stopped working

### ISSUE THREAD

**Issue by NiiiYaa** [home-assistant/home-assistant.github.io#33067]
### Feedback

The integration stopped working (generated an error when boiled water button was clicked).
I removed (delete) it and tried to re-install but the SMS verification  is now generating "Unexpected error" (screenshot attached)
![2024-06-04 08_12_14-Settings – Home Assistant](https://github.com/home-assistant/home-assistant.io/assets/113662601/4cab75cf-ff02-4f84-b61b-c30346468ab3)
 "Unexpected error"

### URL

https://www.home-assistant.io/integrations/tami4/

### Version

2024.5.5

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by Guy293** [comment]
Hi, I've answered here: https://github.com/Guy293/Tami4EdgeAPI/issues/7
