### ISSUE TITLE
Not an issue per'se, but a observation

### ISSUE THREAD

**Issue by wannabuy** [home-assistant/home-assistant.github.io#33066]
### Feedback

Hi
I haven't found much info on if a zigbee receiver can be used with home assistant and yield near real time energy usage... can it actually do that?  ...currently using the low end emporia device but they don't give me more than 20min at a time to view and no external data output...  so constantly refreshing the app just to view data... i'd like to get pg&e data local and process it to manage my GTI power back on the grid to lower my bill during the peak... thanks, Bryan 

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2024.5.5

**Comment by tronikos** [comment]
This has nothing to do with opower. emporia or a similar device is the way to connect to the encrypted zigbee smart meter. I know you can flash ESPHome to emporia that will give you local access and faster data. You are on your own finding it.

**Comment by tronikos** [comment]
@home-assistant close
