### ISSUE TITLE
 ERROR: No matching distribution found for homeassistant==2024.5.5

### ISSUE THREAD

**Issue by German-Chris** [home-assistant/home-assistant.github.io#33076]
### Feedback

using the provided command: python3 -m pip install homeassistant==2024.5.5
gives error: **No matching distribution found for homeassistant==2024.5.5**
plus a list of available distribution versions.  And the latest supported seems to be 2024.3.3
I'm on a raspberry-4 64bit with debian bookworm and a supervised homeassistant 2024.5.5 installation.
It works (almost) fine; but the homeassistant service is constantly restarting.  journalctl shows error regarding python 3 and PEP668 And I have no idea where exactly to add the --break-system-packages  option.

### URL

https://www.home-assistant.io/faq/pip3/

### Version

2024.5.5

**Comment by frenck** [comment]
Home Assistant requires Python 3.12 to run as of Home Assistant 2024.4.0

See also: <https://www.home-assistant.io/blog/2024/04/03/release-20244/#backward-incompatible-changes>

../Frenck
