### ISSUE TITLE
Homewizard P1 Peak demand current month missing

### ISSUE THREAD

**Issue by wmachiel** [home-assistant/home-assistant.github.io#33086]
### Feedback

Getting this value in Belgium is part of the opening of the P1 port by Fluvius and your aggreement to provide the value to others.
This aggreement is time limited and has to be renewed (1 year lifetime).
If you don't renew it, only the Peak demand current month seems to be missing, currents, voltages are still available in HA.
- Go to MyFluvius app.
- open 3 bar menu
- Go to Mijn digitale meter
- Go to P1 poort openen/sluiten
- Poortbeheer aanvragen or vernieuwen.

### URL

https://www.home-assistant.io/integrations/homewizard/

### Version

2024.5.5

**Comment by DCSBL** [comment]
Hi, thanks for your feedback. Please help me understand what you would like to clarify, as I do not completely understand you.

Do you have issues or unexpected behavior with your smart meter, P1 Meter, or the integration? Or do you just want to clarify the 'Peak demand' topic?

**Comment by wmachiel** [comment]
I just want to inform you that when the P1 meter is used, after a year or
so, in Belgium, you have to renew the opening in Fluvius.
As only the Peak value seems to be affected and that at the start of a new
month, It was not clear to me what was wrong with the integration.
Maybe you can inform users in the installation manual or provide some kind
of reminder to renew the P1 opening in Fluvius when the availability of the
Peak is unavailable.

Groetjes Walter
