### ISSUE TITLE
How to add matter devices?

### ISSUE THREAD

**Issue by HuisAutomatisering** [home-assistant/home-assistant.github.io#33083]
### Feedback

Hi, I see a month ago there was a matter update. Devices should be availible via Matter now?
https://www.bosch-smarthome.com/nl/nl/release-notes/bosch-smart-home-systeem/2024-05-14.html

Can we make this work in HA? If i add matter device I see only Homekit, Google are mentioned as bridges. And if you can click "other bridges" for maybe bosch SHC, it asks for a code. But unclear how to get that code. Also getting a code via homekit doesn't seem possible.
https://www.home-assistant.io/integrations/matter/

### URL

https://www.home-assistant.io/integrations/bosch_shc/

### Version

2024.5.5

### Additional information

Can you add some information to the documentation or add this matter option to HA?

**Comment by marcelveldt** [comment]
This is not a support forum. This is for reporting issues with the documentation.
Please read the documentation and for help, seek support on the forums or our discord server (we have a matter channel there).

Thanks!

**Comment by HuisAutomatisering** [comment]
Sorry i was misguided by Bosch. It seems the old bridge doesnt support matter, this is why i got stuck with the documentation. Bosch clearified the situation in their marketing stratigy and Matter now works fine with the Bosch SHC integration (besides it passes on useless entitites that were allready there, so no useful gain and duplicate entities. Was hoping to get all entities, who are only availible in the HACS version of Bosch SHC, not the official one :-( ).
