### ISSUE TITLE
 No QR is prodiusing only o white pictur without code

### ISSUE THREAD

**Issue by Frankymuc** [home-assistant/home-assistant.github.io#33108]
### Feedback

 No QR is prodiusing only o white pictur without code...Since 1 Year from time to time i test ist...never it is working here.... only wheite as snow is visible...why so stupid identification with only one chois...i dont understand...

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.6.0

**Comment by frenck** [comment]
This is probably caused by your custom theme. Please try again using the built-in theme of Home Assistant.

../Frenck
