### ISSUE TITLE
Additional entities

### ISSUE THREAD

**Issue by timparker71** [home-assistant/home-assistant.github.io#33101]
### Feedback

Hi guys.
Thanks for providing this sensor. I can only pick up six entities from the Growatt Cloud server, mainly the solar generation and total costs. 
Is there a way I can get the battery information? Current state of charge and charge/discharge rates etc?
Would love to tap into those.

Thanks

Tim

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.6.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
