### ISSUE TITLE
Time of manual watering

### ISSUE THREAD

**Issue by jezierski** [home-assistant/home-assistant.github.io#33100]
### Feedback

Would be great if there will be a possibility of setting time of manual watering instead of fixed time 15 mins.

### URL

https://www.home-assistant.io/integrations/hydrawise/

### Version

2024.6.0

**Comment by jezierski** [comment]
Regargind my first question, I saw there was already a ticket and even it was in the documentation before "watering_minutes". Is there any chance to add it to the integration?

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
