### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by ZviSteinOpt** [home-assistant/home-assistant.github.io#33113]
### Feedback

Socsesfuly connected with browser with host address and with a mobile app, but Failed to connect with home assistance. 

### URL

https://www.home-assistant.io/integrations/ccm15/

### Version

2024.6.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
