### ISSUE TITLE
Missing Pegel Online Locations

### ISSUE THREAD

**Issue by mpdenver** [home-assistant/home-assistant.github.io#33118]
### Feedback

Oddly e.g. https://www.pegelonline.nlwkn.niedersachsen.de/Pegel/Karte/Binnenpegel/ID/378 cannot be found via HA Pegelonline integration.

### URL

https://www.home-assistant.io/integrations/pegel_online/

### Version

2024.6.0

**Comment by mib1185** [comment]
Hi @mpdenver 
the [pegel_online](https://www.home-assistant.io/integrations/pegel_online/) integration relies on the data of the German Federal Waterways and Shipping Administration (_Wasserstraßen- und Schifffahrtsverwaltung des Bundes_) called [PEGELONLINE](https://www.pegelonline.wsv.de/) (_see also the documentation of this integration_).

It might be possible to integrate also the NLWKN stations into the [aiopegelonline](https://github.com/mib1185/aiopegelonline) lib (_which is used by the pegel_online integration_), but this has some requirements like they need to provide an open and documented api. Contributions are always highly welcome 😉
