### ISSUE TITLE
BMW API - too many requests - what is the request limit?

### ISSUE THREAD

**Issue by crazyelk** [home-assistant/home-assistant.github.io#33114]
### Feedback

I often get "too many requests" - would be good to know the request limit to tune the Automation rules

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2024.6.0

**Comment by rikroe** [comment]
We don't know what the request limits are, as BMW does not disclose them and the integration is not officially approved by BMW.

The default intervals are 5min for rest of world and 10min for North America.

I understand you have additional refreshs if you control it via automations?

For remote services, it is even more unclear.

For state retrieval we only figured out that the rate limit used to reset at 0:00 UTC. 

Closing this here as we cannot improve the documentation. If there are issues with the default intervals, please open an issue with the home-assistant/core repository.

**Comment by rikroe** [comment]
@home-assistant close
