### ISSUE TITLE
Empty records for domain

### ISSUE THREAD

**Issue by emilleszczak2** [home-assistant/home-assistant.github.io#33122]
### Feedback

I tried to configure Cloudflared Add-On. When I put token and confirmed, I received the domain but on the next page records were missing.

**Steps to reproduce the issue**
1. Run Cloudflared configuration
2. Put a token and confirm
3. Select a domain
4. Got empty records list

![Screenshot 2024-06-06 at 15 23 40](https://github.com/home-assistant/home-assistant.io/assets/2837751/8092d4a5-ed91-4e91-9459-396cd531df19)
![Screenshot 2024-06-06 at 15 24 25](https://github.com/home-assistant/home-assistant.io/assets/2837751/153988d9-daf1-449e-b4c1-8be3e5a310ab)

Translations:

Choose the zone to update
Choose records to update
There is no error message, just an empty list of records.

I used a guide to configure the Zero Trust tunnel. Now I have no configuration in the portal, clear it.

### URL

https://www.home-assistant.io/integrations/cloudflare/

### Version

2024.6.0

**Comment by ludeeus** [comment]
And how many "A" records are there in your portal?

**Comment by emilleszczak2** [comment]
@ludeeus You mean the DNS zone provider portal?

**Comment by ludeeus** [comment]
Yes, how many "A" records are defined for the `****.xyz` domain in the cloudflare portal?

**Comment by emilleszczak2** [comment]
I put A record manually and I've got in progress message. It's OK? I guess need wait to propagation manually added record ?
![Screenshot 2024-06-07 at 09 38 39](https://github.com/home-assistant/home-assistant.io/assets/2837751/fb68112b-dd3e-472f-87e1-ac6706b5c9e7)

**Comment by ludeeus** [comment]
Close your browser, you are already doing it in a different tab.
But from you r message, you had 0, which means there was nothing to show.
Closing this.

**Comment by emilleszczak2** [comment]
I have only one tab opened with HomeAssistant :(

**Comment by emilleszczak2** [comment]
@ludeeus Already in progress gone, but empty list returned. Help?!
