### ISSUE TITLE
Feedback issue with integration.

### ISSUE THREAD

**Issue by krishpherwaniweb** [home-assistant/home-assistant.github.io#33131]
### Feedback

Whenever I send a command through a different device, the change is not reflected on the UI of this integration.

### URL

https://www.home-assistant.io/integrations/coolmaster/

### Version

2024.6.0

**Comment by frenck** [comment]
Hi there @krishpherwaniweb 👋 

It seems like you want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
