### ISSUE TITLE
Cancel button issue on popup editing section

### ISSUE THREAD

**Issue by rafasanz** [home-assistant/home-assistant.github.io#33133]
### Feedback

There is an issue on "CANCEL" button while editing a section. The button is not working and not closing the popup windows.

![image](https://github.com/home-assistant/home-assistant.io/assets/102509029/387fc9aa-f0c9-495f-a983-8872f36f1eff)

<img width="862" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/102509029/b2a3dc44-e3c3-40a6-984b-f244862541db">

### URL

https://www.home-assistant.io/dashboards/

### Version

2024.6.0

### Additional information

"X" it's working.

**Comment by frenck** [comment]
Hi there @rafasanz 👋 

It seems like you wanted to report an issue with the Home Assistant frontend; however, you submitted documentation feedback instead. Please report issues with the Home Assistant frontend in the frontend issue tracker here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
