### ISSUE TITLE
"already_in_progress"

### ISSUE THREAD

**Issue by Kaaremi** [home-assistant/home-assistant.github.io#33135]
### Feedback

I subscribed to the Free service plan and set the maximum number of calls = 999. I received the confirmation e-mail over 18 hours ago, but the OpenWeatherMap integration keeps giving the message "already_in_progress". 

Have I missed something?

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2024.6.0

### Additional information

I contacted OpenWeatherMap on this and they replied as follows:
 
"While third-party applications may indeed be built upon our products, it's important to note that we do not oversee or control the development process of these applications. Therefore, for any inquiries or issues related to the integration of our API key into a third-party application, we recommend reaching out to their support team or directly contacting the developer of the application you are using."

**Comment by Kaaremi** [comment]
Looks like I'm not alone with this issue:
![image](https://github.com/home-assistant/home-assistant.io/assets/153614398/f205c247-0f70-4623-b760-39e6f4e1a33f)

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by Kaaremi** [comment]
Hi,

Thanks for educating me. I followed your advice.



Parhain terveisin / Best Regards / Mit freundlichen Grüßen

Mikko Kaarela ***@***.***)
