### ISSUE TITLE
To 14:  Authorised JavaScript origins:

### ISSUE THREAD

**Issue by stlas** [home-assistant/home-assistant.github.io#33141]
### Feedback

Hi!
Under Scenario 2:
![image](https://github.com/home-assistant/home-assistant.io/assets/35530959/2638f21c-90ea-4b0d-ae3e-53b438300d6b)
If I put this string into the fileld, i get this:
![image](https://github.com/home-assistant/home-assistant.io/assets/35530959/728aaf89-1edb-406b-9771-45d777fed862)
What is wrong?
Best regads StLas

### URL

https://www.home-assistant.io/integrations/google_assistant_sdk/

### Version

2024.6.0

**Comment by frenck** [comment]
You are using an incorrect field. As per instructions, you need to add an redirect URI, while your screenshot shows an Javascript origin. Those are not the same things and are indeed not compatible.

../Frenck
