### ISSUE TITLE
Goodwe Reboot, now not Connected to HA

### ISSUE THREAD

**Issue by BrantRocky** [home-assistant/home-assistant.github.io#33149]
### Feedback

I've got 2 Goodwe inverters and had them connected and reporting really well through HA.
One of the inverters had to be rebooted and it won't be connect back to HA; HA hasn't 'found it'.
I tried to force it to recognize it through it's IP address.. no luck.

Any recommendations?

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2024.6.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
