### ISSUE TITLE
Add Login information for Mesh connected repeaters

### ISSUE THREAD

**Issue by fnordson** [home-assistant/home-assistant.github.io#33147]
### Feedback

The Documentation of the AVM FRITZ!Box Tools should in the Username paragraph have additional information for adding Fritz Repeaters if they're connected within Mesh:

`If the Fritz Repeater is connected within a Mesh network, the username is the same as the one used for the FritzBox, but the password is the one set on the repeater itself.
`

I've struggled with that for a while since I tried the fritz user and password but didn't even have the repeater password anymore. 

### URL

https://www.home-assistant.io/integrations/fritz/

**Comment by chemelli74** [comment]
Can you please create a PR for that ?
