### ISSUE TITLE
What does set_txt do?

### ISSUE THREAD

**Issue by tescher** [home-assistant/home-assistant.github.io#33142]
### Feedback

It says the set_text attribute is required but gives no help on what to do

### URL

https://www.home-assistant.io/integrations/duckdns/

### Version

2024.6.0

**Comment by frenck** [comment]
I'm not sure what is unclear or what you are asking for in this feedback.

![CleanShot 2024-06-08 at 16 38 58@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/f59e9723-d2c3-473e-bf49-dcbb86f809d6)

This service sets the contents of the txt record of your DuckDNS domain 🤷 

Could you clarify or reword your issues with the current wording?

Thanks! 👍 

../Frenck

**Comment by tescher** [comment]
Optional=No implies this is needed for successful DuckDNS setup. It isn't.
It also gives no reason why this would be needed

**Comment by frenck** [comment]
> Optional=No implies this is needed for successful DuckDNS setup. It isn't.

I'm not following. This is not in de configuration section at all:

![CleanShot 2024-06-09 at 12 07 49@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/06437593-dce5-4b65-95da-0b5add34d1c4)

There is an additional section about a service this integration exposes. To call this service in, for example, automation or script, would require the parameter.

I do not understand the relation between the setup and services you are trying to make.

../Frenck

**Comment by tescher** [comment]
See below. Set_Txt looks like it is listed under Configuration variables, and is listed as Not Optional.

I suggest changing the text "Set the TXT record of your DuckDNS subdomain." to "This is an optional service to set the TXT record of your DuckDNS subdomain." And maybe give an example of why someone would want to do this

You need to look at this as someone who is not an expert in Home Assistant or domain setup. 

![Capture](https://github.com/home-assistant/home-assistant.io/assets/2557404/a7883b0b-a1a1-433c-b752-9693a00c8ce1)

**Comment by frenck** [comment]
I'm not seeing the conflict, the service is a different chapter, and not related to the configuration chapter. Many integrations provide additional services? This is the first time I hear about this being an issue?

Are you unfamiliar with the concept of services in Home Assistant?
If so, you might want to read more about services and other terminology in our getting started guides and glossary.

../Frenck

**Comment by tescher** [comment]
Not much more I can say. I gave you feedback, but apparently you are unable
to see or accept it.

Again, you need to look at this from the perspective of someone who doesn't
do this every day.

Have a good day.

**Comment by frenck** [comment]
THanks, I do agree we can improve how we list services, but that is a generic issue, and not something specific to this page.

That said, this is not a concern I've seen raised before in the last 7 years 🤷 

../Frenck

**Comment by apwebber** [comment]
> You need to look at this as someone who is not an expert in Home Assistant or domain setup.

I am such a person and trying to debug a problem with DuckDNS. This section is is so cryptic. I don't know what "Service set_txt" is, where to find it, how to set it, or why I would want to do that. But some clues in my logs suggest this could be my problem. No idea what to do and this page doesn't help at all.
