### ISSUE TITLE
Damping factor unclear

### ISSUE THREAD

**Issue by nowak-mariusz** [home-assistant/home-assistant.github.io#33150]
### Feedback

I am unsure how to setup the damping - this documentation needs an example.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2024.6.1

**Comment by frenck** [comment]
> I am unsure how to setup the damping 

![CleanShot 2024-06-08 at 15 59 37@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/2527d7a9-e71f-4b89-8705-4fd913fb579e)

I'm not sure how that is unclear, what do you suggest?

../Frenck

**Comment by nowak-mariusz** [comment]
I was refering to the damping - I don't understand what number do i have to type - whether some percentage or in Watts? How exactly would the damping affect the estimation, at what hours and what is the formula? Even a brief example would be helpful, right now the explanation is very vague.

**Comment by frenck** [comment]
@nowak-mariusz It is a feature of Forecast.Solar; for device or service-specific, please consult the documentation of the device or service being used.

In this case: <https://doc.forecast.solar/damping>

**Comment by nowak-mariusz** [comment]
Thanks for the link, indeed it is helpful. It would be good to refer to that documentation.

**Comment by frenck** [comment]
Agreed!
