### ISSUE TITLE
Addon DHCP for HA yellow should mention or just set the interface to end0 rather than eth0.

### ISSUE THREAD

**Issue by toddhutch** [home-assistant/home-assistant.github.io#33154]
### Feedback

Addon DHCP for HA yellow should mention or just set the interface to end0 rather than eth0.

/hassio/addon/core_dhcp_server/documentation

### URL

https://github.com/home-assistant/addons/blob/master/dhcp_server/DOCS.md

### Version

1.4.0

**Comment by frenck** [comment]
Hi there @toddhutch 👋 

Thanks for opening up a documentation feedback issue, however, this is the feedback issue tracker for our website. Unfortunately, you didn't provide feedback on our website, but on an add-on. 

If you think there is an issue with an add-on or the documentation that is shipped with it, please raise an issue in the add-on issue tracker. In this case:

<https://github.com/home-assistant/addons/issues>

Thanks 👍 

../Frenck

**Comment by toddhutch** [comment]
In new to reprint issues, i thought the dhcp addon is an official addon.  Could you point me to where to report this type of issue?

Best regards,
Todd Hutchinson
503-481-5267

________________________________

**Comment by frenck** [comment]
My last message point to the issue tracker for reporting this one.

../Frenck
