### ISSUE TITLE
Missing parameters to configure the inverter output as in the HACS Version bevor

### ISSUE THREAD

**Issue by uTZFu** [home-assistant/home-assistant.github.io#33160]
### Feedback

Thanks first of all for adding the apsys integration into core! I switched from the HACS Version to the „standard“ version in HA Core by deleting the old and configuring the new. Afterwards I updated the entities/ Names of the sensor data to match my old sensor names. So my reports are again up and working. What I realized is the missing possibility to configure the maximum output (that was one of the best features).  I had an automation up and running that reduced the max output in case we did not consume enough to reduce the overall burden on the public energy network. Without this field that feature is gone. Any plans to add it again? Would also be worth to mention this in the last update, so users relying on it do not need to switch back again. 

Thanks in advance! 

### URL

https://www.home-assistant.io/integrations/apsystems/

### Version

2024.6.1

**Comment by mawoka-myblock** [comment]
I'm just waiting for the merge of that feature: https://github.com/home-assistant/core/pull/118825

So it could be available in the next patch or next month. I don't know and can't change that. I'd have also loved to see it in the initial release.

**Comment by uTZFu** [comment]
Great and thanks for the headsup!

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
