### ISSUE TITLE
Update todo tasks via todo.update_item

### ISSUE THREAD

**Issue by einord** [home-assistant/home-assistant.github.io#33165]
### Feedback

According to the documentation the only way to update a task via the todo.update_item service is to update the item using its name which is the same as the summary field on the todo task.

But it should be possible to use the uid field instead, since it doesn't work properly if two items share the exact same summary.

### URL

https://www.home-assistant.io/integrations/todo/

### Version

2024.6.1

**Comment by dannytsang** [comment]
@einord I'm afraid you have raised this as feedback for the Home Assistant documentation. Feel free to raise it in **New Issue** > **Feature Request**.
