### ISSUE TITLE
Please explain in more detail how to call the heos.sign_in service

### ISSUE THREAD

**Issue by jploonstra** [home-assistant/home-assistant.github.io#33176]
### Feedback

I have tried a lot of ways to get the heos.sign_in service to work, but every time I get some kind of error message.

service: heos.sign_in
data: 
username: "username@gmail.com"
password: "password" 

results in:
Kan service heos.sign_in niet aanroepen. extra keys not allowed @ data['sequence'][0]['password']. Got 'password' extra keys not allowed @ data['sequence'][0]['username']. Got 'username@gmail.com' template value is None for dictionary value @ data['sequence'][0]['data']. Got None

service: heos.sign_in ( "username@gmail.com", "password" )
results in the same thing

service: heos.sign_in 
username: "username@gmail.com"
password: "password" 
results in
Kan service heos.sign_in niet aanroepen. extra keys not allowed @ data['sequence'][0]['password']. Got 'password' extra keys not allowed @ data['sequence'][0]['username']. Got 'username@gmail.com

So what is the right way to do it?

### URL

https://www.home-assistant.io/integrations/heos/

### Version

2024.6.1

**Comment by jploonstra** [comment]
Any progress?

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by jploonstra** [comment]
Beste Klaas,De manier van aanroepen van de HEOS.sign_in service staat niet goed in de documentatie. Daarom is de vraag om de documentatie aan te passen. Ik snap deze manier van redeneren helemaal niet, tenzij het een manier is om git “ schoon te houden”. Ik ga geen bug aanmaken voor het oplossen van documentatie. Te gek voor woorden. Op deze manier onderscheidt HomeAssistant zich negatief van concurrenten.Groet,Jan-PierVerstuurd vanaf mijn iPhoneOp 5 jul 2024 om 23:58 heeft Klaas Schoute ***@***.***> het volgende geschreven:﻿
Closed #33176 as not planned.

**Comment by klaasnicolaas** [comment]
Apologies, a quick review leads me to the conclusion that it should be a core issue, but now I see that you have made a syntax error.  I will edit the docs.

./Klaas
