### ISSUE TITLE
Settings missing

### ISSUE THREAD

**Issue by tomei64** [home-assistant/home-assistant.github.io#33214]
### Feedback

Seems the integration is only allowing data polling at the moment, but not the setting of the output power. Is that planned with a later release?

### URL

https://www.home-assistant.io/integrations/apsystems/

### Version

2024.6.2

**Comment by mawoka-myblock** [comment]
There's an open PR for that and I am waiting for the merge.

**Comment by uTZFu** [comment]
Any chance to indicate the expected timeframe? Sorry - dont wanna push - just dont know how long such a merge takes and i wonder if its worth switching back to the HACS version :-) Thanks for your efforts!!

**Comment by mawoka-myblock** [comment]
The max output has been merged 2 weeks ago and it seems like it will be shipped with the next major release.

**Comment by mawoka-myblock** [comment]
@home-assistant close
