### ISSUE TITLE
On Ubuntu are the commands with python3 -m <something> working right? Cause they do not execute Python 3.12

### ISSUE THREAD

**Issue by ncarandini** [home-assistant/home-assistant.github.io#33213]
### Feedback

We know that a prerequisite of installing Home Assistant Core is to have Python 3.12.x installed on the Ubuntu WSL Windows machine. I've followed the nice guide [Upgrade Python to latest version (3.12) on Ubuntu Linux or WSL2](https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux).

The issue is that following your documentation I see python3 commands, but these do not execute the Python 3.12 because on Ubuntu, python3 must not refer to the 3.12 version for compatibility. It can (and should) be done only on Python virtual environments.

Following your documentation, after creating the venv, we can see it with a tree command:

![image](https://github.com/home-assistant/home-assistant.io/assets/139274/2766d169-2db7-458b-835c-b29b8636cd74)

So, IMHO there should be a command to change it on the homeassistant virtual enviroment so that subsequent python3 commands execute the latest Python version.

### URL

https://www.home-assistant.io/installation/windows/

### Version

2024.6.1

**Comment by frenck** [comment]
Python environment can be set up in many different ways and flavors.

Using this installation method, we assume you are an advanced user and know your way around.

As denoted by:

![CleanShot 2024-06-11 at 18 24 02@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/92ab2d4d-ccea-4696-bd49-2229b9eae9dd)

I, as a personal example, prefer using pyenv and handle my Python executables & virtual environments that ways 🤷 

../Frenck

**Comment by ncarandini** [comment]
Yes, and no.
"Yes" because even if I'm a senior developer but I did know about the idiosyncrasy of Python 3.12 on Ubuntu.
So, doing my tests I've messed up creating two venv on the same `svr/homeassistant` directory.

"No" because if the documentation bother to add simple instruction as
```
sudo apt-get update
sudo apt-get upgrade -y
```
and then all the commands needed to create the venv from scratch, I respectfully think that the venv creation command should be:
```
python3.12 -m venv .
```
That way the python and python3 commands execute the Python 3.12 version as we can see here:

![image](https://github.com/home-assistant/home-assistant.io/assets/139274/afc3e069-2217-4fea-ae49-7efb5a982fc4)

Thanks for your patience.

**Comment by frenck** [comment]
These instructions are not specific to WSL or the setup you are using 🤷‍♂️

I think the warning is very fitting and correct in this case. I'm sorry to hear the instruction weren't fitting for your specific setup, but nevertheless happy you've managed to get it working.

We do plan on revamping these installation docs in the near future; for now, this part will remain as is.


../Frenck

**Comment by ncarandini** [comment]
sorry for your time, I did another test and now also the 

python3 -m venv .

works fine.
I do think the mess was caused because my first attempt was to set the venv when I was still with the old Python version.
Too bad I've messed it up and wasted your time.
Now back to work... 😄

**Comment by frenck** [comment]
No worries! That stuff happens 👍 

../Frenck
