### ISSUE TITLE
Used from grid

### ISSUE THREAD

**Issue by xs2erwin** [home-assistant/home-assistant.github.io#33226]
### Feedback

Is it posibles  to get the power that is used from grid. Now I can't use the energy in home assistant because I miss this entity. 

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.6.2

**Comment by dannytsang** [comment]
@xs2erwin from memory it had both power and energy from the grid so it should be possible however I don't use the integration anymore to verify.

**Comment by xs2erwin** [comment]
Hi dannytsang. If the converter doesn't get solar power the grid false off line. 
But I allready use a other add-on that provide me with the right info.
Thank you for the response.
