### ISSUE TITLE
Note does not describe how to set the "hourly" mode for the API calls.

### ISSUE THREAD

**Issue by gdavidpatterson** [home-assistant/home-assistant.github.io#33234]
### Feedback

Under the Note section with "Important Deprecation Notice", it mentions:

Recent policy changes limit the API access for new registered users with a free plan, they should select the hourly mode.

But it does not describe how to select the "hourly" mode. I have configured my HA to use the new 3.0 API last night, less than 12 hours have elapsed and a total of 58 API calls have occurred, which x 31 days > 1000 calls. Where can we configure the frequency of API calls?

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2024.6.2

**Comment by AndrStnz** [comment]
As of now it is a 1000 calls a DAY for free.
So you are totally fine with the default value of 10 Minute Polling.

But yes, the configuration of the Polling interval is nowhere documented, but should be in my opinion.

Is it enough to set a custom Polling Interval via the HA Automations?

**Comment by AndrStnz** [comment]
![image](https://github.com/home-assistant/home-assistant.io/assets/28625365/9c1e634d-04e4-465e-b50d-ccfc719b073d)
Currently trying this automation...

**Comment by AndrStnz** [comment]
So this does not seem to work, API Calls in the OpenWeatherMap Dashboard go up, but in the Integration everything stalls...

**Comment by AndrStnz** [comment]
So, just for peace of mind, this is how it works with everything default under API 3.0
![image](https://github.com/home-assistant/home-assistant.io/assets/28625365/e92f70ae-e990-4949-b8ac-4a9c5398dbcd)
So no worries. Very very far away from the 1000 calls a day threshold :)

**Comment by gdavidpatterson** [comment]
Yeah, somehow in my mind I thought it was 1K per month, sorry for the confusion. I am having no issues with it currently.
