### ISSUE TITLE
Les données des micro-onduleurs de panneaux photovoltaïques TUYA restent à 0 

### ISSUE THREAD

**Issue by grunchy99** [home-assistant/home-assistant.github.io#33252]
### Feedback

Les données des micro-onduleurs de panneaux photovoltaïques TUYA apparaissent bien après la configuration de l'intégration, mais les valeurs restent constamment à 0.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.6.2

**Comment by grunchy99** [comment]
<img width="408" alt="ScreenShot 2024-06-13 à 16 01 53" src="https://github.com/home-assistant/home-assistant.io/assets/78148828/9da7e227-2733-4007-9a05-2d7fa5758f46">

**Comment by grunchy99** [comment]
Data from TUYA PV panel microinverters appears well after the integration is configured, but the values ​​remain constantly at 0.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by grunchy99** [comment]
Thanks, new issue opened here : https://github.com/home-assistant/core/issues/119844
