### ISSUE TITLE
Alexa instructions don't work at all

### ISSUE THREAD

**Issue by paul-kline** [home-assistant/home-assistant.github.io#3326]
Title says it all. Followed to a T and every time the Service respose is: "The remote endpoint could not be called, or the response it returned was invalid."

**Comment by arsaboo** [comment]
Please provide details of what you are doing and your setup for others to help. Saying that it is not working is unlikely to get you much help. Also, please file a bug https://github.com/home-assistant/home-assistant This repository is only for documentation.

**Comment by fabaff** [comment]
https://github.com/home-assistant/home-assistant.github.io/pull/3331
