### ISSUE TITLE
Blower not availeble

### ISSUE THREAD

**Issue by StaffordBully** [home-assistant/home-assistant.github.io#33265]
### Feedback

Hi,
Like the Balboa on HA,
All is working great, only my Jacuzzi has 2 jets and 1 blower.
I can see and use the 2 jets pumps but the blower i don't have.

Is it possible to add that option?

Greetings

### URL

https://www.home-assistant.io/integrations/balboa/

### Version

2024.6.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
