### ISSUE TITLE
Lock error when entering pin

### ISSUE THREAD

**Issue by StaffordBully** [home-assistant/home-assistant.github.io#33267]
### Feedback

When i try to open/close my lock and i enter a pin i get the next error:
The code for lock.voordeur doesn't match patern ^\d{0}$.

I tried several pins but all the same error.

### URL

https://www.home-assistant.io/integrations/verisure/

### Version

2024.6.2

**Comment by c0ffeeca7** [comment]
I do not have this lock. But the pattern says it expects something that has 0 digits.

1. On the integration page, select **Configure**
<img width="561" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/38767475/6cbf210c-6697-4f58-8bbc-92e805773422">

2. then there should be a field where you can define the number of lock code digits.

3. this number needs to match the number of digits of your code.
