### ISSUE TITLE
Not working MFI in Home Assistant

### ISSUE THREAD

**Issue by eullin4K** [home-assistant/home-assistant.github.io#33273]
### Feedback

Not working....

### URL

https://www.home-assistant.io/integrations/mfi/

### Version

2024.6.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by wwwFINKcz** [comment]
[klaasnicolaas](https://github.com/klaasnicolaas) .. I did it /I hope/ - reported an issue - provided feedback here https://www.home-assistant.io/integrations/mfi/
Because, I have the same issue :(
