### ISSUE TITLE
There is now a cheaper alternative to having routers and VPNs to remotey connect to your Home Assistant

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#33271]
### Feedback

S-IMSY provides a SIM and a portal (you can also develop your own service using APIs) which when connected to your HA device via an integrated cellular modem or a USB cellular dongle allows you to remotely connect to your device.  
![HA_RPi5_ZTE](https://github.com/home-assistant/home-assistant.io/assets/172797980/c035b5b5-3526-4fea-a9c1-8ebbb8a61cd9)

https://github.com/home-assistant/home-assistant.io/assets/172797980/d61b1e44-e3c3-4582-b382-3070741fea60

### URL

https://www.home-assistant.io/docs/configuration/remote/

### Version

2024.6.2

**Comment by klaasnicolaas** [comment]
This fits better on the [community forum](https://community.home-assistant.io/)

./Klaas
