### ISSUE TITLE
Add Default in addition to Initial

### ISSUE THREAD

**Issue by almighty059** [home-assistant/home-assistant.github.io#33279]
### Feedback

I'm not sure this is the correct way to submit this but I don't see anything that says it's not for feature requests and falls under something that "can be improved" so I'm submitting this here. The `input_text` feature currently has an `initial` feature which resets the field every time HA restarts. I think it would be advantageous to users to also have a "default" feature which is used when nothing has been initially entered into the `input_text` field. Currently any `input_text` field that has never received any input shows a state of `unknown`, however, it would be nice to have control over that and have an initial default state of choosing that only displays when there has never been any input into that field. This would be unlike `initial` which resets at every HA restart. The "default" would display in place of `unknown` and would show only for `input_text` that has never received any user input.

### URL

https://www.home-assistant.io/integrations/input_text/

### Version

2024.6.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
