### ISSUE TITLE
Request: Synology Router

### ISSUE THREAD

**Issue by NullVelocity** [home-assistant/home-assistant.github.io#33278]
### Feedback

Requested that Synology routers get support for this module of Home Assistant. 

### URL

https://www.home-assistant.io/integrations/synology_dsm/

### Version

2024.6.2

**Comment by mib1185** [comment]
Hi

Please use the [feature request](https://community.home-assistant.io/c/feature-requests) section of our forum to contribute on existing or create new feature requests.
For sure, contributions are always welcome, so please feel free to create a PR on your own.

Thanks! 👍
