### ISSUE TITLE
"icon changes by state" lost after selecting a new icon for an entity

### ISSUE THREAD

**Issue by HelgeGitHub** [home-assistant/home-assistant.github.io#33274]
### Feedback

The history: I did add two "external cover roller shutter" to HA. I thought there should be a different icon-set for all states of the cover and did select one. But no there is stable only this (or any other) icon. I did not found the place where this change was stored.

I'm not sure if this a bug or a feature but did not find any way to revert. So I thing, there should be at least a warning in the documentation and a link how to revert.

### URL

https://www.home-assistant.io/docs/frontend/icons/

### Version

2024.6.2

**Comment by c0ffeeca7** [comment]
I think these might be the instructions you are looking for?
<https://www.home-assistant.io/docs/configuration/customizing-devices/>

**Comment by HelgeGitHub** [comment]
> I think these might be the instructions you are looking for? https://www.home-assistant.io/docs/configuration/customizing-devices/

Yes, there is no information, that one looses the original icons changed by state if one defines any other icon. And also no information to revert.

**Comment by HelgeGitHub** [comment]
> #33346

I#m fare away to understand, how #33346 meets my comment. I assume, thats my problem.
But I see in the code the hint, that there is for every object a "default icon" (icon set for several states). So may be, I miss the information in the documentation 'how to get the default icon (set) back'.
