### ISSUE TITLE
how to get "up/down" instead of "on/off"?

### ISSUE THREAD

**Issue by zolldi** [home-assistant/home-assistant.github.io#33282]
### Feedback

I am watching humidity changes with this trend. I get the result humidity change: "on" or "off".
Is it possible to get as a result humidity change: "up/down" or "rising/falling"?

### URL

https://www.home-assistant.io/integrations/trend/

### Version

2024.6.2

**Comment by cloudbr34k84** [comment]
agree, be good to have a new class introduced
