### ISSUE TITLE
Getting an authentification issue with MFA

### ISSUE THREAD

**Issue by cptwajo** [home-assistant/home-assistant.github.io#33280]
### Feedback

Dear community,
I recently setup my Unifi network using a docker controller. I used my unifi account, it’s not a local user account and I have the multi factor authentication (MFA) activated, which will become mandatory in July 2024.

When I try to add the integration, I get an „invalid authentification“ error. I see the prompt in my Unifi Verify App, but doesn’t help to approve there.
![IMG_7653](https://github.com/home-assistant/home-assistant.io/assets/130223556/a5f1e402-9b27-4fc2-a865-c1ed9717c65e)

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.6.2

### Additional information

Verify App shows a prompt and I approve
![IMG_7654](https://github.com/home-assistant/home-assistant.io/assets/130223556/ad87b882-db6a-4eb5-8b32-ac62d36430e0)

**Comment by Kane610** [comment]
Hello. Cloud accounts are not supported. Local accounts will still be allowed without MFA.

See https://community.home-assistant.io/t/ubiquiti-unifi-network-add-on-integration/678411/17?u=robban

**Comment by cptwajo** [comment]
Thanks and sorry that I did not look enough for a solution!

**Comment by Kane610** [comment]
No worries. You're not alone
