### ISSUE TITLE
Notification/recommendation 

### ISSUE THREAD

**Issue by StaffordBully** [home-assistant/home-assistant.github.io#33287]
### Feedback

Is it also possible to add when there is a recommendation for example add hp... to receive that in home assistant? 

So we can display it on the dash or send it to telegram for example.

### URL

https://www.home-assistant.io/integrations/ondilo_ico/

### Version

2024.6.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
