### ISSUE TITLE
'No such file or directory' error on mosquitto_pub due to bad example

### ISSUE THREAD

**Issue by digiater** [home-assistant/home-assistant.github.io#33301]
### Feedback

There's an example in this page which mentions 'mosquitto_pub -h 127.0.0.1 -u username -p some_password '

It took me some time to figure out why I got a 'No such file or directory' error on this command. '-p' mean the port number, it should be '-P' for password.

Very confusing!

### URL

https://www.home-assistant.io/integrations/sensor.mqtt/

### Version

2024.6.2

**Comment by jbouwh** [comment]
Thanks, the linked PR should correct that.
