### ISSUE TITLE
Support editing the configuration 

### ISSUE THREAD

**Issue by kmahelona** [home-assistant/home-assistant.github.io#33309]
### Feedback

If someone's UniFi Protect IP address changes you're unable to edit the configuration for this integration without deleting the integration and reinstalling it. What if I have automations etc. Will those all be deleted? Will I have to recreate everything because I'm unable to edit the IP address for this integration? How do we manually change the IP through the config.yaml?

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2024.6.3

**Comment by frenck** [comment]
> Support editing the configuration

That would be a feature request. 

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

> How do we manually change the IP through the config.yaml?

This integration has no YAML configuration, so that is not possible.

../Frenck
