### ISSUE TITLE
Conditions in automations lack "equals", "equals or higher", "equals or lower"

### ISSUE THREAD

**Issue by frederikvoGIT** [home-assistant/home-assistant.github.io#33303]
### Feedback

I would like to trigger an automation when a certain value is matched. But only "above" or "below" is possible to select.

### URL

https://www.home-assistant.io/docs/automation/action/

### Version

2024.6.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
