### ISSUE TITLE
THIS CONFIGURATION IS NOT WORKING, REPORTED BY MANY USERS

### ISSUE THREAD

**Issue by wwwFINKcz** [home-assistant/home-assistant.github.io#33328]
### Feedback

starting from core-2022.7 (till today) mfi has been unable to connect with the following error for both switch and sensor.

Unable to connect to mFi: HTTPSConnectionPool(host='10.1.10.15', port=6443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:997)')))

EVEN SETTINGS:
    ssl: false
    verify_ssl: false
DOES NOT HELP IT.
The same with ports (changing ports to 80 does not help)

### URL

https://www.home-assistant.io/integrations/mfi/

### Version

2024.6.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by wwwFINKcz** [comment]
Hi Klaas, nope, it IS CLEARLY A DOCUMENTATION FEEDBACK, because it is not working at all /for all the users with the latest version of HomeAssistant/.

**Comment by frenck** [comment]
@wwwFINKcz There is no amount of documentation we can adjust to fix the issue. The root cause of the issue is not documentation.

Please use the right place to report the issue as instructed above. Please note, Home Assistant is an open source project. We rely on contributions from volunteers for our integrations. Feel free to jump into development to help out as well.

Lastly, small note on the tone of voice. In general, on the internet, the full caps writing style is considered shouting. This isn't needed (nor acceptable). Refrain from doing that.

Thanks for understanding! 👍 

../Frenck

**Comment by wwwFINKcz** [comment]
[frenck](https://github.com/frenck) Hello, dear Frenck. In my very humble opinion, documentation IS a PROBLEM because it doesn't solve or help just anything. So I'm just shouting it out and you're right about that. This documentation should not be here, or should be clearly marked as no longer working. And users have been looking for a solution for years and it's not being addressed at all. I'm just making it clear. Btw. this problem is mentioned in many, many places, from many users and still no solution (and not just for Ubiquity stuff, it's the same for many other devices that have a self-protocol (old) system. I've found about 50 different threads about it, same thing over and over. So as of core 2022.7 it's just NOT FUNCTIONING documentation (yes, I'm just shouting that, I'm not insulting anyone, just clearly stating, this documentatnion is completely useless and should be deleted or marked as obsolete).

with a big love to HomeAssistant and all the users and programmers.

**Comment by frenck** [comment]
>  This documentation should not be here, or should be clearly marked as no longer working.

Tracking bugs is not the goal of our documentation, or issue tracker is.

> And users have been looking for a solution for years and it's not being addressed at all. I'm just making it clear. 

Well, do something about it! This is an open source project, feel free to jump into the development. As said, this project relies on code contributions, we are an open source project.

So, again, if there is an issue with an integration, please use the issue tracker as pointed out above by Klaas.

Thanks! 👍 

../Frenck

**Comment by wwwFINKcz** [comment]
[frenck](https://github.com/frenck)
firist, I am not programmer at all, I do not understand these things. If I knew a single person (who can fix this), you can be absolutely sure, I will be the first, who will post it here.
And I am helping to the other users, saying this documentation is totally obsolete. (and saving anyones precious time too)

Thx for understanding!  👍Petr.

**Comment by frenck** [comment]
> And I am helping to the other users, saying this documentation is totally obsolete. 

This documentation match the current codebase.

Again, please use the above appointed issue tracker for this case.

Thanks 👍 

../Frenck
