### ISSUE TITLE
TNN Sensors entities as History Graph not a Line Graph

### ISSUE THREAD

**Issue by Saad-Imtiaz** [home-assistant/home-assistant.github.io#33329]
### Feedback

In the documentation of the integration it should be motioned how to declare the unit of measurement for each sensor, right now I am getting this history graph, as shown in the picture below. 
![history graph](https://github.com/home-assistant/home-assistant.io/assets/53612215/21647824-489d-489c-bd8c-cecbf8448f53)

What I want is the line graph which I get on all my other sensors.
![CO2 Line Graph](https://github.com/home-assistant/home-assistant.io/assets/53612215/d4e0284e-97bb-4dca-9f6a-ec8fd4f7dbcf)

I know that unit of measurement needs to be defined for each entity but there is no information how to do so. 

Please help me in this regard,

Thank you.

### URL

https://www.home-assistant.io/integrations/thethingsnetwork/

### Version

2024.6.3

**Comment by frenck** [comment]
Hi there @Saad-Imtiaz 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by Saad-Imtiaz** [comment]
Hi @frenck , 
Actually, there is also a problem with documentation in this issue, as the procedure of doing this is not mentioned in the documentation.

**Comment by angelnu** [comment]
Yes, until we re-add the capability to define the units in the integration itself as the custom integration, the manual process is needed.

**Comment by Saad-Imtiaz** [comment]
Can you kindly let me know how to set it up manually as I am having a hard time figuring out how to get this done. 
Thank you.

**Comment by angelnu** [comment]
You might use customize: https://community.home-assistant.io/t/unit-of-measurement/208905

It might need you to go the yaml way. Not great but it will have to do for a few weeks until we complete the features from the new integration.
