### ISSUE TITLE
Utility Meter Documentation

### ISSUE THREAD

**Issue by Marty56** [home-assistant/home-assistant.github.io#33323]
### Feedback

After reading the documentation several times, still I do not understand how "Tarif" is working.

Also it seems that the configuration of utility meters via the WebUI is buggy.
Utility meters once defined via WebUI cannot be changed anymore.
Workaround: Delete the utitliy meter and recreate it once again. 
But this workaround seems also not to be working always.
Documentation should hint that the configuration via helper WebUI is still experimental and should direct user to the Yaml approach.

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2024.6.3

**Comment by dgomes** [comment]
If you find a bug in the WebUI please open an issue at https://github.com/home-assistant/frontend

But you are correct when saying editing tariffs is not supported through the UI.
