### ISSUE TITLE
This blueprint no longer works

### ISSUE THREAD

**Issue by rvdv01** [home-assistant/home-assistant.github.io#33338]
### Feedback

Unfortunately, this blueprint no longer works with the current version of HA. 
I just installed in on version 2024.6 but it may have stopped working earlier, probably because of the changed (deprecated and removed) weather forecase-entitities.
Same issue as the other reporters.

It would be really nice if the blueprint could be updated! I would do it if I could, but is just a little bit beyond my scope of knowledge.

### URL

https://www.home-assistant.io/voice_control/assist_daily_summary/

### Version

2024.6.3

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @rvdv01 !
Thank you for the awesome blueprint, @allenporter, and pointing me to the updated version!
Thank you for helping with the docs config to make this work with liquid, @ludeeus.

**Comment by rvdv01** [comment]
Thank your for fixing this!
I added the new blueprint from your pull request and it works.

**Comment by c0ffeeca7** [comment]
Nice! Thank you for letting me know it works on your end.
