### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by starman2k01** [home-assistant/home-assistant.github.io#33337]
### Feedback

The page lists parameters, but HOW DO YOU ADD THESE? There is no configuration tab, no yaml info, absolutely nothing to tell you how to update/add/change parameters, like lat/long? Polling? etc. etc. Where is this information stored???

### URL

https://www.home-assistant.io/integrations/openweathermap

### Version

2024.6.3

**Comment by c0ffeeca7** [comment]
You can either add the integration manually by choosing the **Add integration**, or select the my button in the documentation to install the integration.
<img width="566" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/38767475/dc972740-a51f-4c07-80be-feed1dcdc009">

The integration then brings up a dialog, asking you to enter this information
<img width="382" alt="image" src="https://github.com/home-assistant/home-assistant.io/assets/38767475/63ded72d-8789-4137-9afa-08ac63158617">

**Comment by starman2k01** [comment]
So I have to delete the integration to modify. What about polling? To avoid
api 3 charges?

**Comment by c0ffeeca7** [comment]
defining a custom polling interval:
<https://www.home-assistant.io/common-tasks/general/#defining-a-custom-polling-interval>
