### ISSUE TITLE
cmake as a dependency for Home Assistant Core

### ISSUE THREAD

**Issue by vladkozlov69** [home-assistant/home-assistant.github.io#33347]
### Feedback

Hello,

looks like build of numpy wheel requires cmake, and it could be missing on some linux environments. I suggest adding it to "INSTALL DEPENDENCIES" section.

### URL

https://www.home-assistant.io/installation/linux/

### Version

2024.6.3

**Comment by frenck** [comment]
As per this section:

![CleanShot 2024-06-21 at 14 37 32@2x](https://github.com/home-assistant/home-assistant.io/assets/195327/3298cdd7-faba-404c-bd3e-63dc14c63dbb)

That depends on your setup and environment. Most won't need it, as there are pre-build wheels available.

Nevertheless, thanks for your suggestion.

../Frenck
