### ISSUE TITLE
Removing a Holiday with Workday

### ISSUE THREAD

**Issue by Dystaxia** [home-assistant/home-assistant.github.io#33349]
### Feedback

I currently have my sensor set for Monday-Thursday as "workdays".   I'm excluding Holidays.  

This week, I have to work on Friday, so I tried to make it a workday by "removing a holiday" using 2024-06-21, but I get the following error:

Configured holiday date 2024-06-21 for Workday Sensor does not exist
Remove holiday date 2024-06-21 as it can't be found in country US.

Is there any way to add back a workday, without actually changing the workdays temporarily?

### URL

https://www.home-assistant.io/integrations/workday/

**Comment by gjohansson-ST** [comment]
No, Fridays needs to be included first and then you can remove those that isn't needed. In your case this might be a bit troublesome as you would have to exclude a lot of Friday's but it's how it works.
