### ISSUE TITLE
Ring Doorbell entity cam dont exist

### ISSUE THREAD

**Issue by Phrana** [home-assistant/home-assistant.github.io#33371]
### Feedback

Hello, I have a Ring doorbell and I changed the password in the mobile app, and now when I reinstall the integration the camera entity does not appear
![5221211ad0ed592f2bdb7d6b84dd281a153a212c_2_690x380](https://github.com/home-assistant/home-assistant.io/assets/118558930/74587344-1083-48e0-a441-5e3bc5eb4810)

### URL

https://www.home-assistant.io/integrations/ring/

### Version

2024.6.4

**Comment by frenck** [comment]
Hi there @Phrana 👋 

It seems like you want to report an issue with an Home Assitant integration, or, you are looking for support (I'm not sure). Either way, you are not in the right place for either of those, as you have submitted documentation feedback.

If you want to report an issue with an Home Assistant integration, please submit an issue here:

<https://github.com/home-assistant/core/issues>

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
