### ISSUE TITLE
The documentation needs also to add VA as power.

### ISSUE THREAD

**Issue by xbeaudouin** [home-assistant/home-assistant.github.io#33392]
### Feedback

Hello,
As electrician power is not ONLY mesured with Watt (or kW). It is also mesured in VA or kVA (Volt - Amperes). 
Usualy on resistive load (on AC) 1 W = 1 VA, but if you have other kinds of mesures it should be better to mesure VA instead of W.
So the following message (I dunno yet where in the code we can fix it) :
```
[homeassistant.components.sensor] Entity sensor.teleinfo_1 (<class 'custom_components.ecodevices.sensor.TeleinfoInputEdDevice'>) is using native unit of measurement 'VA' which is not a valid unit for the device class ('power') it is using; expected one of ['W', 'kW']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/Aohzan/ecodevices/issues
```

Should NOT exists.

Also notice there is kVAr also that it the resultante of the other kind of measure of non cos(phi)=1 on AC.

Kind regards

### URL

https://www.home-assistant.io/docs/energy/faq/

### Version

2024.6.4

### Additional information

See following Wikipedia doc: https://fr.wikipedia.org/wiki/Voltamp%C3%A8re_r%C3%A9actif

(Sorry for the French).

**Comment by frenck** [comment]
Within the scope of Home Assistant, the `power` device class isn't supporting `VA`.
The message is thus correct, the sensor needs to be adjusted.

> Also notice there is kVAr also that it the resultante of the other kind of measure of non cos(phi)=1 on AC.

Support for kVAr, there is an architectural discussion open; there is currently no support for that in Home Assistant.

Going to close this feedback, while correct on a technical perspective, the current documentation does correctly reflect the behavior of the Home Assistant software.

../Frenck
