### ISSUE TITLE
context not clear, too technical

### ISSUE THREAD

**Issue by bee8bit** [home-assistant/home-assistant.github.io#33402]
### Feedback

Hi!
I am new to home assistant and I have some trouble understanding what this integration is, at least from the docs without installing it and tinkering around.
I do understand what this does, but I cannot see where I would extract such a stream from. From web radio stations? From YouTube? From a network capable satellite receiver in my home or a locally installed camera?
It would be really helpful if the docs for this integration had a few non-technical introductory sentences what this is about and possibly a few example scanarios. If you feel that those do not belong there, because those integration docs are intentionally trchnucal, perhaps you could link to another page that describes media with Home Assistant in general.

Thank you.

### URL

https://www.home-assistant.io/integrations/media_extractor/

### Version

2024.6.4

**Comment by joostlek** [comment]
I kinda have that a bit on purpose because if you go to the yt-dlp repository and check what services are supported - that's a lot. And I don't want to create the idea that HA has an integration mainly used for downloading things you should not
