### ISSUE TITLE
Good instructions but for which device?

### ISSUE THREAD

**Issue by UnmitigatedAudacity** [home-assistant/home-assistant.github.io#33405]
### Feedback

In the section "INSTALLING THE OPENWAKEWORD ADD-ON" there's no mention of what device. I'm looking for something for my watch .. does it apply? I'm guessing it's instructions for an Android phone, but article should say.

### URL

https://www.home-assistant.io/voice_control/install_wake_word_add_on/

### Version

2024.6.4

**Comment by UnmitigatedAudacity** [comment]
Ok, just realised it's a link to an HA page, which works. But still, arriving on this page from a Google search is a bit disorienting and I still don't know how the wake word is related to my phone or watch. Needs a bit of an intro.

**Comment by UnmitigatedAudacity** [comment]
So after spending some time wasted while reading it all, I find it's not what I want.
Suggested edit, opening paragraph: "Wake word currently does not support listening on devices such as mobile phones or watches.  
Under INSTALLING THE OPENWAKEWORD ADD-ON: 
1. _In Home Assistant_, go to Settings > ...

**Comment by c0ffeeca7** [comment]
On https://www.home-assistant.io/voice_control/install_wake_word_add_on/, The introduction states that it requires extra hardware (The S3-Box should be added there):
![image](https://github.com/home-assistant/home-assistant.io/assets/38767475/7f0874c9-2cd1-4d8a-b07d-31e723fcd604)
