### ISSUE TITLE
Why is the connection so intermittent? 

### ISSUE THREAD

**Issue by Obioban** [home-assistant/home-assistant.github.io#33411]
### Feedback

I really want to use this integration, as I _always_ try to use the local, not cloud based option... but it seems to not be connected 1/4 of the time, breaking automations that depend on it. 

Is there any way to make the connection more reliable/consistent? 

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2024.6.4

The error I'm getting is,
"Failed setup, will retry: Powerwall is unreachable: Cannot connect to host 192.168.1.195:443 ssl:False [Connect call failed ('192.168.1.195', 443)]"

Later it'll be connected, and fine, with no input from me. . 

_No response_

**Comment by bdraco** [comment]
I had the same problem until I hard wired it. The wifi range seems to be severely limited.

**Comment by bdraco** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍
