### ISSUE TITLE
Aladdin Connect integration stopped working

### ISSUE THREAD

**Issue by t1890bb** [home-assistant/home-assistant.github.io#33433]
### Feedback

The error code is "Invalid Config", with the following my log file ...

Logger: homeassistant.setup
Source: setup.py:271
First occurred: 1:34:03 PM (1 occurrences)
Last logged: 1:34:03 PM

Setup failed for 'aladdin_connect': Dependency is disabled - This integration is disabled because it uses non-open source code to operate.

![image](https://github.com/home-assistant/home-assistant.io/assets/171505953/fe7b932b-c6c4-4141-860c-a0e3481f07b0)

### URL

https://www.home-assistant.io/integrations/aladdin_connect/

### Version

2024.6.4

**Comment by frenck** [comment]
As the current error message says: 

> This integration is disabled because it uses non-open source code to operate.

We have notified them of the issue and are awaiting their response. Unfortunately, at this point, we are not able to fix this issue, the ball is currently @ Aladdin Connect upstream.

../Frenck

**Comment by frenck** [comment]
Tracking this one @ https://github.com/home-assistant/core/issues/120623 instead.
Closing it on the documentation end.

../Frenck
