### ISSUE TITLE
Using external data disk

### ISSUE THREAD

**Issue by garyjohnwalker** [home-assistant/home-assistant.github.io#33431]
### Feedback

In the section "Using external data disk", it states: -

"Home Assistant Operating System supports storing most data on an external storage medium, such as an USB attached SSD or HDD."

Please can this be amended to something like: -

"Home Assistant Operating System supports storing most data on a secondary storage medium. For example, this can be a second internal SSD or HDD or a USB attached SSD or HDD.

There maybe bits of the text further down the section that will also need updating to reflect this change.

### URL

https://www.home-assistant.io/common-tasks/os/

### Version

2024.6.4

### Additional information

I tested the above and it does work. I don't want someone discounting this as an option if it is possible.

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @garyjohnwalker :+1:
