### ISSUE TITLE
solarEdge insufficien log

### ISSUE THREAD

**Issue by thomaskilian** [home-assistant/home-assistant.github.io#33438]
### Feedback

I regularly get this message on startup

>  Logger: homeassistant.components.solaredge_local.sensor
> Source: components/solaredge_local/sensor.py:227
> integration: solaredge_local (documentation, issues)
> First occurred: 21:12:18 (1 occurrences)
> Last logged: 21:12:18
> 
> Could not retrieve details from SolarEdge API

It's running though it's not possible to determine the cause of this log. Something is wrong, but what?

### URL

https://www.home-assistant.io/integrations/solaredge_local/

### Version

2024.6.4

**Comment by drobtravels** [comment]
Did this work for you in a previous version? 

You likely want the cloud based integration: https://www.home-assistant.io/integrations/solaredge/

The local integration you are utilizing has not worked with most inverters for years due to firmware changes.

**Comment by drobtravels** [comment]
@home-assistant add-label needs-more-information

**Comment by thomaskilian** [comment]
Sort of. I see the Energy dashboard with all relevant data, so it basically does the job. I would rather stay local than going over some obscure cloud (which did NOT work in the first try).

**Comment by thomaskilian** [comment]
This is still an issue, though not that pressing. I still get thst error when rebooting HA, but aside of that the connection works. I would have a look if I'd have a pointer where...
