### ISSUE TITLE
Missing Control Features "Max. Output Power"

### ISSUE THREAD

**Issue by MatthiasTeichert** [home-assistant/home-assistant.github.io#33446]
### Feedback

Hi, in the previous version "APsystemsAPI_Local" there was the option to set the "Max. Output power". Is it possible to get this feature back soon?
![image](https://github.com/home-assistant/home-assistant.io/assets/101704930/188e776b-becf-44b9-9aa4-fa763f696286)
thx & cheers, matthias

### URL

https://www.home-assistant.io/integrations/apsystems/

### Version

2024.6.4

**Comment by mawoka-myblock** [comment]
Max output will be part of the next major release

**Comment by mawoka-myblock** [comment]
@home-assistant close
