### ISSUE TITLE
Honeywell Total Connect Comfort Emergy Heat Switch Doesn't work

### ISSUE THREAD

**Issue by xinde1989** [home-assistant/home-assistant.github.io#33451]
### Feedback

With the recent change, the emergency heat is changed to a switch. However, I can use the switch to turn off emergency heat, but can't use the switch to turn it on. 

### URL

https://www.home-assistant.io/integrations/honeywell/

### Version

2024.6.4

**Comment by mkmer** [comment]
You should put this issue in on the core rather than documentation code base.
The EM heat switch requires the system be in heat mode to enable emergency heat.  
https://github.com/home-assistant/core/blob/629dab238fcc942af761eb20033837d540104ed6/homeassistant/components/honeywell/switch.py#L74-L80
Did you have heat enabled?

**Comment by xinde1989** [comment]
> You should put this issue in on the core rather than documentation code base. The EM heat switch requires the system be in heat mode to enable emergency heat. https://github.com/home-assistant/core/blob/629dab238fcc942af761eb20033837d540104ed6/homeassistant/components/honeywell/switch.py#L74-L80 Did you have heat enabled?

Ok, didn't know that was a requirement. Why not including "auto" or "heat/cool" mode in that too?

**Comment by mkmer** [comment]
EM mode is really only for HEAT... but your suggestion may make more sense.  I was sharing how it's currently programmed to work not saying it's "right".  It's not to difficult to remove the test and allow it to go into EM mode whenever.

**Comment by xinde1989** [comment]
> EM mode is really only for HEAT... but your suggestion may make more sense. I was sharing how it's currently programmed to work not saying it's "right". It's not to difficult to remove the test and allow it to go into EM mode whenever.

Thanks. Anywhere I should post to make a suggestion? I should be able to work around this for now but would be good to have it work in "auto" mode as well. Thanks.
