### ISSUE TITLE
Rendering of top bar (with version) overlaps content on Safari mobile

### ISSUE THREAD

**Issue by code-in-progress-ha** [home-assistant/home-assistant.github.io#33477]
### Feedback

On iOS 17.5.1, using mobile Safari, the top bar with the HA version information has a transparent background and allows the first header to bleed through and causes an overlap effect as seen below. Scrolling the page further causes the bar’s background to fix itself. 

![image](https://github.com/home-assistant/home-assistant.io/assets/173382193/666c9573-5906-4cfa-9241-38b614c3bcb9)

### URL

https://home-assistant.io

**Comment by frenck** [comment]
Fixed #33477
