### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by gimmel** [home-assistant/home-assistant.github.io#33485]
### Feedback

I love the grid card, but can we please have more parameters? I’d like to change the alignment (left, center, right), the margin between grid elements and the background color.

### URL

https://www.home-assistant.io/dashboards/grid/

### Version

2024.6.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
