### ISSUE TITLE
How do I update the Dexcom credentials?

### ISSUE THREAD

**Issue by BStrauss3** [home-assistant/home-assistant.github.io#33487]
### Feedback

The document doesn't say how my Dexcom credentials are stored, nor how to update them if I have to - say - change my Dexcom password.

### URL

https://www.home-assistant.io/integrations/dexcom/

### Version

2024.6.4

**Comment by BStrauss3** [comment]
Yes it is still a valid question.

I had to work-around by deleting the integration and then recreating it.

Being able to change credentials is a necessary function.

**Comment by klaasnicolaas** [comment]
By adding the integration again and that applies to many more integrations 😉 

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

./Klaas
