### ISSUE TITLE
Getting Started > Advanced Configuration: configuration.yaml example seems out of date

### ISSUE THREAD

**Issue by SeanI-Git** [home-assistant/home-assistant.github.io#33492]
### Feedback

I'm running the full HAOS install on my RPi 4b with OS Version 12.4, Home Assistant Core 2024.6.4.

I'm new to HA, so I was following the trail of tutorials through the Getting Started section. When I got to Advanced Configuration, it sent me into a bit of a panicked wild goose chase because the tutorial says to use the File Editor add-on to change the name, location, time zone, etc. in the configuration.yaml file. It also said that the configuration.yaml file is in the /config/ folder. My configuration.yaml file is in /homeassistant/, and it contains only 11 lines of code that I don't recognize, and they all say they should not be edited.

If I am indeed on the right track with everything I've said here (and maybe I'm not since I'm still new), it would be helpful if the page was updated with new examples of some kind. I read in a few places that many developers in the community are moving away from having to use the configuration.yaml file in favor of config entry, so an explainer on this would be very helpful too.

I really appreciate all the hard work that goes into this amazing ecosystem!

### URL

https://www.home-assistant.io/getting-started/configuration/

### Version

2024.6.4

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/97849324/2c81f526-5484-4de0-8e5b-55a0fdbf02bc)

**Comment by c0ffeeca7** [comment]
Thank you for your feedback, @SeanI-Git. This page was out of date. When getting started, there should be no need to edit the [configuration.yaml](https://www.home-assistant.io/docs/configuration/) file. These settings can now be done via the UI.
The `/config/` folder is correct, but it is not shown correctly in the file editor.

**Comment by SeanI-Git** [comment]
Thank you for the fast response, and I appreciate the clarification of the configuration.yaml file location as well. Thanks for all you do!
