### ISSUE TITLE
8920W

### ISSUE THREAD

**Issue by bdesch** [home-assistant/home-assistant.github.io#33511]
### Feedback

Anyone available to provide an integration for the 8920W Wi-fi thermostat?

### URL

https://www.home-assistant.io/integrations/aprilaire/

### Version

2024.6.4

**Comment by chamberlain2007** [comment]
@bdesch The 8920W should be supported by the AprilAire integration.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
