### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by FredrikVaaland** [home-assistant/home-assistant.github.io#33519]
### Feedback

The Skybell integration does not work anymore, fix asap or remove it

### URL

https://www.home-assistant.io/integrations/skybell/

### Version

2024.6.4

**Comment by frenck** [comment]
Hi there @FredrikVaaland 👋 

It seems like you want to report an issue, but you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by tkdrob** [comment]
One already exists here: https://github.com/home-assistant/core/issues/105177
