### ISSUE TITLE
Can import credientals

### ISSUE THREAD

**Issue by tom4oc** [home-assistant/home-assistant.github.io#33530]
### Feedback

I tried to add the Zemismart M1 threads border router and I can't import the credientals. I get an error when trying to import it via the HA app. Any help would be great.

### URL

https://www.home-assistant.io/integrations/thread/

### Version

2024.6.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
