### ISSUE TITLE
Information about currently running Alarm / Sleep Timer

### ISSUE THREAD

**Issue by GuraxUbrax** [home-assistant/home-assistant.github.io#33545]
### Feedback

Is there an attribute or entity showing weather a media_player has an alarm or the sleep_timer running at the moment? 
Would be helpful in automation. 

### URL

https://www.home-assistant.io/integrations/sonos/

### Version

2024.6.4

**Comment by PeteRager** [comment]
I believe that data is available from Sonos; however it is not exposed in the integration.  This is a feature request and belongs here

https://community.home-assistant.io/c/feature-requests/13?order=votes&page=24

**Comment by PeteRager** [comment]
@home-assistant close
