### ISSUE TITLE
Engie Boxx - Electrabel 

### ISSUE THREAD

**Issue by jerre78** [home-assistant/home-assistant.github.io#33546]
### Feedback

I have an Engie Boxx and as of 01/07/24 there is no support anymore from Electrabel. The app is offline and the thermostat can only be controlled locally via the display. The integration no longer works with Home assistant either. Perhaps useful to mention in the info page.

### URL

https://www.home-assistant.io/integrations/toon/

### Version

2024.6.4

**Comment by JordyThery** [comment]
Hoping there would be an easier way of getting this back to work that doesn’t mean rooting the device. 🤞🏻
