### ISSUE TITLE
Mealie Shopping and Todo List Integration 

### ISSUE THREAD

**Issue by jacobkaad01** [home-assistant/home-assistant.github.io#33551]
### Feedback

The ability to integrate shopping and todo lists from mealie to Home Assistant much like the calendars.

### URL

https://www.home-assistant.io/integrations/mealie/

### Version

2024.7.0

**Comment by joostlek** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by joostlek** [comment]
We're working on it btw

**Comment by joostlek** [comment]
But not here
