### ISSUE TITLE
I would like to do it . but I don't undestand what I must buy

### ISSUE THREAD

**Issue by merlino1975** [home-assistant/home-assistant.github.io#33563]
### Feedback

I've this inverter it got usb port and other kind, I've near inverter a router wich ethernet ports free...

I can connect it to home assistnat?.. how?

### URL

https://www.home-assistant.io/integrations/aurora_abb_powerone/

### Version

2024.7.0

**Comment by davet2001** [comment]
Hi @merlino1975 

Please could you ask this question on the community forum?

The github issue system here is used for bug reports. Sorry that it is not for technical support.

Many thanks!
