### ISSUE TITLE
documentation is unclear

### ISSUE THREAD

**Issue by avidricaire** [home-assistant/home-assistant.github.io#33569]
### Feedback

I have added the integration, set up my Knocki account and device, and have created a triple tap trigger. no matter what I do, I can not get any devices or entities to appear in the home assistant integration

### URL

https://www.home-assistant.io/integrations/knocki/

### Version

2024.7.0

**Comment by jgatto1** [comment]
Hey @avidricaire! Sorry for the late reply. Is this still happening? If so, could you reload the integration? We are fixing a related bug. Thanks!
