### ISSUE TITLE
hard to understand explanation

### ISSUE THREAD

**Issue by MHBraun** [home-assistant/home-assistant.github.io#33568]
### Feedback

missing examples. 
Eg is 'precision' the amount of digits or the modulo or the integer remainder?
Is 'radius' the total amount of previous data points or is it the deviation of the new data point relative to the last datapoint?
Is there a quick way to determine the effect of the filter like a demo?

### URL

https://www.home-assistant.io/integrations/filter/

### Version

2024.7.0

**Comment by dgomes** [comment]
I don't understand the comment... you find all descriptions in the documentation

Precision:
You can read in the documentation: "Defines the precision of the filtered state, through the argument of round()."

Radius:
"radius float (optional, default: 2.0)
... Band radius from median of previous states."

You can use https://www.home-assistant.io/integrations/simulated/ to test/validate filter (it was actually used during development)

**Comment by MHBraun** [comment]
I try to make it clearer:

Precision: 

was not a good example, agreed. You have to understand the mathematical function of round() to understand precision first.

Radius:

Radius float (2.0)

*	Is the radius the maximum value

*	+/- integer value of the medium value (= 1000) meaning the radius allows +/- 2 which is 998 to 1002
*	+/- percentage tolerance of the medium value (=1000) meaning the radius allows 2% which is 980 to 1020

Of the medium value ( how many data points to calculate the medium value?) or is 2.0 the amount of data points to calculate the medium value?

 

Hope this helps.

 

Thank you for the very helpful link below. I was not aware of it. Should be referenced in filters.

 

Markus

**Comment by dgomes** [comment]
Please don't reply through email (it adds unnecessary text to the issue)

Band radius by definition is defined using the same units as the underlying source sensor. So it's your 1st example.

If you feel more information is necessary, you can edit the page proposing new changes (a Pull Request will be created that will be reviewed before acceptance)
