### ISSUE TITLE
The Tuya integration in home assistant does not ask me for the user code and instead asks for Tuya credentials which the docs don’t show how to find

### ISSUE THREAD

**Issue by Bilalm354** [home-assistant/home-assistant.github.io#33565]
### Feedback

The Tuya integration in home assistant does not ask me for the user code and instead asks for Tuya credentials which the docs don’t show how to find

![IMG_1131](https://github.com/home-assistant/home-assistant.io/assets/53113053/4f6d9ef2-66b9-4221-aeb0-d45d92a829cd)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.7.0

**Comment by kurtjcu** [comment]
Same login here as well

**Comment by KEMBL** [comment]
Users who have an old version of Home assistant (from 2023 year) also will see that 'Tuya IoT Access ID', if so - try to update HA version
