### ISSUE TITLE
No layout tab for resizing

### ISSUE THREAD

**Issue by vogtmh** [home-assistant/home-assistant.github.io#33582]
### Feedback

To be honest, I was excited when I heard about the resizing feature and wanted to apply it to many of my dashboards, but.. it only works on sections and only on some items, not on others. This is super disappointing. 

But the biggest problem I face: no matter what I try, I do not get any layout tab. I have already added a new section, added three different cards. But still, there is no Layout tab. 

It feels like a random decision to add a headline feature to an unfinished, experimental feature. 

<img width="1058" alt="Screenshot 2024-07-05 at 21 17 43" src="https://github.com/home-assistant/home-assistant.io/assets/37808063/705b8bec-f622-46e9-afaa-34db158791f5">
<img width="711" alt="Screenshot 2024-07-05 at 21 17 31" src="https://github.com/home-assistant/home-assistant.io/assets/37808063/4840a145-326d-4379-bc19-ff8b79ea1cc3">

### URL

https://www.home-assistant.io/dashboards/cards/

### Version

2024.7.1

**Comment by frenck** [comment]
> It feels like a random decision to add a headline feature to an unfinished, experimental feature.

To be clear on this: the sections dashboard is an experimental feature. It is clearly marked as such in all communications, documentation and even in the UI itself.

If you experience an issue with it, please report an issue in the frontend issue tracker:

<https://github.com/home-assistant/frontend/issues>

You've now submitted documentation feedback and there is no amount of documentation we can adjust to fix a bug in the source code.

../Frenck

**Comment by vogtmh** [comment]
Okay, so I could fix the issue and maybe this should be added to the documentation: After the upgrade, a full page reload was required. The layout tab then appeared as  expected.
