### ISSUE TITLE
gdacs cannot be setup via configuration.yaml anymore

### ISSUE THREAD

**Issue by DanDixon** [home-assistant/home-assistant.github.io#33581]
### Feedback on the Documentation

1
This is no longer supported:

# Example configuration.yaml entry
gdacs:
  categories:
    - Drought
    - Earthquake
  radius: 1000
  latitude: -41.2
  longitude: 174.7
  
2
It's also unclear how to change the radius.
What worked for me was to delete the integration and re-add it to change the radius.

### URL

https://www.home-assistant.io/integrations/gdacs/

### Version

2024.6.4

**Comment by exxamalte** [comment]
Yes, the YAML configuration option was removed back in January (https://github.com/home-assistant/core/pull/107962), but unfortunately the documentation wasn't updated back then. I'll get onto that.

And, at this point in time, the only option to change the radius is indeed to remove and re-add the integration. I can add this feature onto my todo list.
