### ISSUE TITLE
HOME ASSISTANT COMMAND LINE INTERFACE 

### ISSUE THREAD

**Issue by stevegroom** [home-assistant/home-assistant.github.io#33595]
### Feedback

Where is the doc? 

I think I need ```ha network .....``` to add a vlan, but need to read the docs first...

### URL

https://www.home-assistant.io/getting-started/

### Version

2024.7.1

**Comment by frenck** [comment]
The command line is considered an advanced feature; it seems like you left feedback from the getting started page. However, the CLI feature would not be suitable for beginners who get started with Home Assistant.

The basic documentation around using the command line can be found here:

https://www.home-assistant.io/common-tasks/os/#home-assistant-via-the-command-line

Furthermore, you can always call up the internal help of the CLI by running the `ha help` command.

../Frenck

**Comment by stevegroom** [comment]
Hello Frenck, 
thanks for the quick reply. I'm not exactly a beginner, but am sometimes frustrated to find documentation. 

I started out trying to connect a Thread blind to HA, eventually got a message from Ubiquiti stating that matter does not play well with vlans (My only thread radio was in my Apple TV on the main vlan, vs HA on the IoT vlan). Someone suggested I used nmcli which I had not heard of. Eventually found that does not work on HA Yellow and found ha network is the command I am looking for. 

The command ha network vlan --help shows syntax but I want to read more about it before I risk breaking my HA instance.

Starting at https://home-assistant.io, search 'command line' , click on the Home Assistant via the Command Line link and end up at https://www.home-assistant.io/common-tasks/supervised/   :-( 

Plan B is now to plug in a SONOFF Zigbee dongle to the HA and see if Thread will recognise it..

**Comment by frenck** [comment]
In general, in a home network (especially when using Matter), the flatter the better (I ditched all my VLANs for example, with the compromise of some extra firewall rules).

About UniFi and Matter over Wi-Fi: be sure to disable any optimizations UniFi offers; UniFi turns out to be a source of issues a lot in this department.

**Comment by stevegroom** [comment]
Hi, 
flattening the network will be a major project, so I'll try to add a thread radio to HA Yellow instead - I tested Multiprotocol some time ago and that caused major performance problems. I have an unused SONOFF ZB Dongle-E - Can I add that as a border router to HA Yellow and drop the Apple TV?

**Comment by frenck** [comment]
> I tested Multiprotocol some time ago and that caused major performance problems. 

It is highly experimental and not recommended for use. As a matter of fact, we have frozen our development at this point.

> I have an unused SONOFF ZB Dongle-E - Can I add that as a border router to HA Yellow and drop the Apple TV?

These questions currently fit better in our Discord chat & community forums, there are more people there that can answer you that correct and swiftly.

../Frenck

**Comment by stevegroom** [comment]
Thank you for the pointers Frenck your input is greatly appreciated :-)

**Comment by frenck** [comment]
<img src="https://media1.giphy.com/media/kmQREsvNQrhrHdkN7G/giphy.gif"/>
