### ISSUE TITLE
Support for Govee H5109 Bluetooth Pool Temperature Monitor

### ISSUE THREAD

**Issue by cszatkowski** [home-assistant/home-assistant.github.io#33597]
### Feedback

Is there any chance that the Govee  H5109 Bluetooth Pool Temperatire Monitor can be added to the list of supported devices?  The currently working Home Assistant integration is not detecting this new unit via the ESP32 Bluetooth Proxy setup.

Thanks for your code.

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2024.7.1

**Comment by Watso4183** [comment]
Looking at the manual on page 6, I believe the probe communicates to the smart gateway over 433MHz based on the network connectivity specification. I do not believe this device provides data via BLE between that and the smart gateways specifications listing network connectivity: 433MHz, Bluetooth 4.2, Wi-Fi IEEE 802.11b/g/n 2.4GHz

**Comment by cszatkowski** [comment]
You are correct.  That was a good observation.  I wonder why they went with the 433 MHz frequency and a custom "Gateway" unlike their other sensors that use BLE 2.4 GHz. BLE supports the same 100 meter radio range. Thanks for the reply.
