### ISSUE TITLE
Adding Tilt Open and Tilt Close functions

### ISSUE THREAD

**Issue by markyeew** [home-assistant/home-assistant.github.io#33592]
### Feedback

Hi, I was wondering if the tilt open and tilt close functions can be added to this integration.
I am currently using Bond as a work around for the tilt function to work but would prefer if it could be done directly from the Somfy integration with my Somfy RTS Connexoon directly.
Thanks!

### URL

https://www.home-assistant.io/integrations/overkiz/

### Version

2024.7.1

**Comment by iMicknl** [comment]
This is not a documentation question. Please check if your issue is already described on https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+overkiz%22, and otherwise you can create a new issue.
