### ISSUE TITLE
Uknown error occured

### ISSUE THREAD

**Issue by dutchronnie** [home-assistant/home-assistant.github.io#33613]
### Feedback

When i install the integration GPSlogger in home assistant i get the error "Unknown error occured"
![image](https://github.com/home-assistant/home-assistant.io/assets/16868762/c9c30172-09ca-4ea9-99f9-fa57eadac8a6)

### URL

https://www.home-assistant.io/integrations/gpslogger/

### Version

2024.7.1

**Comment by frenck** [comment]
Hi there @dutchronnie 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
