### ISSUE TITLE
Can we add the date the page was modified?

### ISSUE THREAD

**Issue by HomeAssistant-Steve** [home-assistant/home-assistant.github.io#33610]
### Feedback

adding a date to the page would help the reader how up to date the information is.

### URL

https://www.home-assistant.io/dashboards/cards/

### Version

2024.7.1

**Comment by frenck** [comment]
We have got asked that quite a lot over the past years, unfortunately, it is to intensive to add (causes issues with deploying).

The pages always reflect the latest stable release of Home Assistant, in this case, the page is up to date for Home Assistant 2024.7.

../Frenck
