### ISSUE TITLE
Tapo l530 not working since few days

### ISSUE THREAD

**Issue by waellomari** [home-assistant/home-assistant.github.io#33647]
### Feedback

Connection error: get_device_info not found in {'component_nego': {'component_list': [{'id': 'device', 'ver_code': 2}, {'id': 'firmware', 'ver_code': 1}, {'id': 'quick_setup', 'ver_code': 3}, {'id': 'inherit', 'ver_code': 1}, {'id': 'time', 'ver_code': 1}, {'id': 'wireless', 'ver_code': 1}, {'id': 'schedule', 'ver_code': 2}, {'id': 'countdown', 'ver_code': 2}, {'id': 'antitheft', 'ver_code': 1}, {'id': 'account', 'ver_code': 1}, {'id': 'synchronize', 'ver_code': 1}, {'id': 'sunrise_sunset', 'ver_code': 1}, {'id': 'brightness', 'ver_code': 1}, {'id': 'color', 'ver_code': 1}, {'id': 'color_temperature', 'ver_code': 1}, {'id': 'auto_light', 'ver_code': 1}, {'id': 'light_effect', 'ver_code': 1}, {'id': 'on_off_gradually', 'ver_code': 1}, {'id': 'cloud_connect', 'ver_code': 1}, {'id': 'default_states', 'ver_code': 1}, {'id': 'preset', 'ver_code': 1}]}, 'get_device_info': <SmartErrorCode.JSON_ENCODE_FAIL_ERROR: -1004>, 'get_connect_cloud_state': {'status': 0}} for device 192.168.178.27

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.7.1

**Comment by sdb9696** [comment]
Hi, this is the wrong repository for opening issues, you want the core repository.  There is already an open issue for the problem you describe here: https://github.com/home-assistant/core/issues/121362

**Comment by sdb9696** [comment]
@home-assistant close
