### ISSUE TITLE
Incorrect Documentation on mqtt.publish Service Attributes

### ISSUE THREAD

**Issue by sthomsen1** [home-assistant/home-assistant.github.io#33653]
### Feedback

I noticed an inconsistency in the documentation for the mqtt.publish service. The documentation currently lists topic_template as a service data attribute with the description "Template to render as topic to publish payload to." However, topic_template is no longer supported. Instead, the functionality to use templates in topics can be achieved using the topic attribute directly.

Additionally, when attempting to use topic_template with the mqtt.publish service, I receive an error stating that the topic attribute must be set. Furthermore, in the core/homeassistant/components/mqtt/services.yaml file, topic is marked as a required field and topic_template is not present.

Thank you for your attention to this matter.

### URL

https://www.home-assistant.io/integrations/mqtt/

### Version

2024.7.1

**Comment by jbouwh** [comment]
In fact the topic_template code works. The issue is in the service yaml as the option is not available there.
But the option is stale as in the UI it is possible to use a template as well. It is not needed to have an option for this.

**Comment by jbouwh** [comment]
Reopening because parent PR is about to be reverted.
A new PR is to be opened to add the `topic_template` option to `services.yaml`
