### ISSUE TITLE
Missing Information on fixing authentication errors

### ISSUE THREAD

**Issue by sovamind** [home-assistant/home-assistant.github.io#33687]
### Feedback

I changed my email address on my Opower connected electricity account. Now the service is failing with a 403 access denied (expected) but I cannot figure out how to update the email address / authentication.  I'm assuming I'll have to delete the integration and add it back but that will likely screw up my integration for the natural gas company.

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2024.7.2

**Comment by tronikos** [comment]
What's your utility provider?

**Comment by tronikos** [comment]
And can you provide logs of the 403 error?
