### ISSUE TITLE
The documentation is not applicable and erroneous for GW1100A_V2.3.2

### ISSUE THREAD

**Issue by ognacy** [home-assistant/home-assistant.github.io#33690]
### Feedback

There is no "menu others" in the WebUI of GW1100A_V2.3.2. I did not try the app. 

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2024.7.2

**Comment by fsedarkalex** [comment]
Want to add, I just saw #27303 which partially covers this issue

**Comment by fsedarkalex** [comment]
And doing the whole process in HA several times, once I got the correc tdialog with all the information.

I would suggest adding to the docs that HA should display the settings while setting up the addon. For me for some reason it showed the "old" instructions (as stated in #27303) even though I didn't have the HACS variant installed. After that it never shoed the server/port/path information.

However afte 3 or 4 tries the correct dialog has been shown and now it works.
