### ISSUE TITLE
Timeout establishing connection

### ISSUE THREAD

**Issue by ajcorrea** [home-assistant/home-assistant.github.io#33703]
### Feedback

Integration stops working here.

Getting Timeout establishing connection and no log´s what´s happening.

### URL

https://www.home-assistant.io/integrations/sunweg/

### Version

2024.7.2

### Additional information

![image](https://github.com/home-assistant/home-assistant.io/assets/2067756/5386e854-581a-4f45-9825-3e87ec66fe83)

**Comment by rokam** [comment]
This should be fixed on 2024.7.3
https://github.com/home-assistant/core/pull/121684

**Comment by rokam** [comment]
@homeassistant close

**Comment by rokam** [comment]
@home-assistant close
