### ISSUE TITLE
Please add button to power on or off 

### ISSUE THREAD

**Issue by gurusystem** [home-assistant/home-assistant.github.io#33718]
### Feedback

Hello in Apsystems integrate on HACS there is the option to power on or off the inverter, can you add this feature on this project ?

I have switched on this new integration and for now working. 

thanks for your job.

### URL

https://www.home-assistant.io/integrations/apsystems/

### Version

2024.7.2

**Comment by mawoka-myblock** [comment]
Not an issue, but I've got that on my agenda, don't worry.

**Comment by mawoka-myblock** [comment]
@home-assistant close

**Comment by gurusystem** [comment]
Thanks for All .......

Good work
