### ISSUE TITLE
How often are Monzo balances refreshed?

### ISSUE THREAD

**Issue by paulwakeford** [home-assistant/home-assistant.github.io#33717]
### Feedback

I'm writing an automation for the Monzo integration to notify me when the balance of an account (one of my sensors) exceeds a certain number. I want the notification as soon as possible. How often are Monzo sensors/balances updated? Thanks.

### URL

https://www.home-assistant.io/integrations/monzo/

### Version

2024.7.2

**Comment by frenck** [comment]
It seems like it is polling using a coordinator every minute.

../Frenck

**Comment by JakeMartin-ICL** [comment]
Yep, thanks! Also, assuming #119214 is merged in time for the next release, you'll soon have the option of device triggers to trigger automations at the instant a transaction occurs too
