### ISSUE TITLE
Sample template "agenda"

### ISSUE THREAD

**Issue by stovedoctor** [home-assistant/home-assistant.github.io#33711]
### Feedback

Can someone please explain a little?
what is "for event in agenda" in the template ?
```service: notify.nina
data:
  title: Daily agenda for {{ now().date() }}
  message: >-
    Your school calendar for today:
    {% for event in agenda["calendar.school_calendar"]["events"] %}
    {{ event.start}}: {{ event.summary }}<br>
    {% endfor %}
    Your work calendar for today:
    {% for event in agenda["calendar.work_calendar"]["events"] %}
    {{ event.start}}: {{ event.summary }}<br>
    {% endfor %}```

### URL

https://www.home-assistant.io/integrations/calendar/

### Version

2024.7.2

### Additional information

_No response_

**Comment by tjbenator** [comment]
It's a two part example. One to fetch calender events, and another to send a notification of those events.


You would need this code snippet from further up on the page:
```
action: calendar.get_events
target:
  entity_id:
    - calendar.school
    - calendar.work
data:
  duration:
    hours: 24
response_variable: agenda
```

Which fetches 24 hours of calendar events and stores them in `agenda`

After that action you could then use the newly created `agenda` variable to send the notification:
```
action: notify.nina
data:
  title: Daily agenda for {{ now().date() }}
  message: >-
    Your school calendar for today:
    {% for event in agenda["calendar.school_calendar"]["events"] %}
    {{ event.start}}: {{ event.summary }}<br>
    {% endfor %}
    Your work calendar for today:
    {% for event in agenda["calendar.work_calendar"]["events"] %}
    {{ event.start}}: {{ event.summary }}<br>
    {% endfor %}
```

**Comment by tjbenator** [comment]
Created an example automation via the UI to demonstrate.

Trigger is every morning at 7am:
![01-agenda_automation_when](https://github.com/user-attachments/assets/bccc3fed-f705-4f57-833e-24ed617d76c8)

It will use get_events to pull all calendar events for the next 24 hours and send a notification to my phone:
![02-agenda_automation_then_do](https://github.com/user-attachments/assets/b00c83b8-deca-457e-b0a5-6ec1d19380a7)

Example of the notification:
![03-agenda_notification](https://github.com/user-attachments/assets/7945c881-8d96-477c-882f-d04f3eaf7480)

**Comment by stovedoctor** [comment]
Thank you
