### ISSUE TITLE
[help] Jabber notifier not working because different Xmpp server port 

### ISSUE THREAD

**Issue by maxbarmet** [home-assistant/home-assistant.github.io#33729]
### Feedback

Hello,
I've tested the jabber integration in HA to send notification on my xmpp servers
on the first server the xmpp port is 5220 and on the second one the xmpp port is the classical port 5222
The notification failed on the first server and successfully run on the second one.
It is due to the xmpp port
So question : is there an entry in the configuration.yaml to indicate the port number for the target xmpp server ?
I tried to add port: 5220 and restart HA but when testing a send notif nothing happened !

### URL

https://www.home-assistant.io/integrations/xmpp/

### Version

2024.7.2

**Comment by black-roland** [comment]
As far as I know, XMPP retrieves server's host and port from the SRV record. I'd suggest setting up the port by updating [DNS records](https://prosody.im/doc/dns).
