### ISSUE TITLE
Control4 - Version 2.9.1

### ISSUE THREAD

**Issue by Rodrigoccoelho** [home-assistant/home-assistant.github.io#33727]
### Feedback

Good afternoon! Home Assistant only has integration with Control4 for versions above 3.0. My control4 is in version 2.9.1 and I really miss being able to integrate my control4 with the Home assistant. Is there any possibility of an integration that meets my version (2.9.1)?

### URL

https://www.home-assistant.io/integrations/control4/

### Version

2024.7.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
