### ISSUE TITLE
How do you automatically log in to HA

### ISSUE THREAD

**Issue by sud0n1m** [home-assistant/home-assistant.github.io#33722]
### Feedback

It would be great if this document gave an example of how to use fully kiosk to automatically log in to home assistant which seems like the most common use-case.  I ended up here researching how to do that. 

### URL

https://www.home-assistant.io/integrations/fully_kiosk/

### Version

2024.7.2

**Comment by frenck** [comment]
Sorry, Home Assistant doesn't support that.

../Frenck
