### ISSUE TITLE
Mismatch with docs and the default install of home assistant

### ISSUE THREAD

**Issue by BurkenDev** [home-assistant/home-assistant.github.io#33734]
### Feedback

the docs state that there should be a hue integration, but there's not. Not even when you've double checked twice that the repository is correctly added. No hue integration at all.
The docs should state how to add it so it shows up in the repository list.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2024.7.2

**Comment by marcelveldt** [comment]
You need to add it to Home Assistant by pressing the button or it will be automatically discovered. Not sure what you mean here?
