### ISSUE TITLE
Removal of integration

### ISSUE THREAD

**Issue by edwin-2023** [home-assistant/home-assistant.github.io#33732]
### Feedback

There is nowhere documantated how to remove the plugwise integration.

### URL

https://www.home-assistant.io/integrations/plugwise/

### Version

2024.7.2

**Comment by CoMPaTech** [comment]
I don't think there are any specifics regarding removal, for generic removal of integrations one can just go the the integrations dashboard en remove it? Can you specify what you deem missing exactly?

**Comment by edwin-2023** [comment]
Hi. I think the removal part of the intergration could be an HA issue bet let me explain.
I've got a plugwise Adam gateway and a P1 gateway. Some weeks ago the Adam went out and got replaced. I put disabled the defective Adam and added a new Adam (and moed the zigbee stick from old to new adam), so far good. Eveything seemed to be working ok, but....
Today i needed a hidden entity (lisa thermostat) and discoverd i was unable unhide it. When i try i get "unabl to change status. Disabled by device" When i click on "open device settings" i get a blank.
My guess is that some how, something got screwed up by having 2 Adams in the integration so i decided to remove the Plugwise integration and start all over since is did not have to many Atomation relying on the plugwise integration.
That's when i dicovered tha i really don't have a clue how to remove the integration, so a bit lost how to continue.

I must say i installed the HACS beta plugwise yesterday since i als got a old usb stick with 30 or so connected circles tha i would like to control (are now controlled by HomeSeer)

Thanks in advance for your time!

**Comment by CoMPaTech** [comment]
Maybe indeed remove - reinstall; if you go to https://my.home-assistant.io/redirect/integration/?domain=plugwise you should be able to use the 3 dots behind 'Adam' to remove it. Not sure if you'd still need to restart HA afterwards (might be a good idea anyway) and then re-add it.

**Comment by edwin-2023** [comment]
will try and report back.

**Comment by bouwew** [comment]
I don't think you can hide a Lisa because it's climate-entity in HA.

Also, in the future just google your problem :)

**Comment by bouwew** [comment]
@home-assistant close

**Comment by bouwew** [comment]
@edwin-2023 Closing this topic, it doesn't belong here. 
You can still reply and we will see the replies.
