### ISSUE TITLE
Switches lights

### ISSUE THREAD

**Issue by baksimha** [home-assistant/home-assistant.github.io#33738]
### Feedback

Can you please update the light Switcher  to home assistant thank you

### URL

https://www.home-assistant.io/integrations/switcher_kis/

### Version

2024.7.2

**Comment by thecode** [comment]
Feature requests should be created in the community forum: https://community.home-assistant.io/c/feature-requests/13
There is a developer working on it, I don't have a timeline, when it will be ready it will be updated in the docs.
