### ISSUE TITLE
Variable filnames

### ISSUE THREAD

**Issue by Boebes-Gr** [home-assistant/home-assistant.github.io#33747]
### Feedback

It would be nice if You integrate an example with variable filenames of the camera snapshots, so that the snapshots can be saved in HomeAssistant with a time stamp and sent to the email address.

### URL

https://www.home-assistant.io/integrations/smtp/

### Version

2024.7.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
