### ISSUE TITLE
Rain sensor

### ISSUE THREAD

**Issue by GolfRBravo** [home-assistant/home-assistant.github.io#33758]
### Feedback

Is it possible to integrate the rain sensor of velux with the simpel “Limitation min” and “Limitation max”?
It is not my idea but it would be a big add to the integration. Take a look:
https://community.home-assistant.io/t/velux-rain-sensor/624850/7
https://github.com/home-assistant/core/pull/64628

### URL

https://www.home-assistant.io/integrations/velux/

### Version

2024.7.2

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
