### ISSUE TITLE
How to set "Preset mode Away represents Gree’s “8°C heating mode.”"

### ISSUE THREAD

**Issue by PleasecallmeF** [home-assistant/home-assistant.github.io#33756]
### Feedback

I added all of my Gree AC into homekit via home bridge. However, it showed the current temperature is 8'c in Home Kit. How to fix it?

And I found this quote in Gree Climent add-on
"Preset mode Away represents Gree’s “8°C heating mode.”
Can I change it and display the current temperature?

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2024.7.2

**Comment by cmroche** [comment]
Probably this is what your unit is returning, attach debug logs though and I will look and confirm.
