### ISSUE TITLE
This feature should be listed as deprecated, since it depends on pybluez, which breaks under newer python

### ISSUE THREAD

**Issue by owldown** [home-assistant/home-assistant.github.io#33755]
### Feedback

I wasted time trying to get this to work because the documentation is so out of date: 

https://community.home-assistant.io/t/how-do-i-fix-unable-to-install-package-pybluez-0-22-error/579478/88

### URL

https://www.home-assistant.io/integrations/bluetooth_tracker/

### Version

2024.7.2

**Comment by frenck** [comment]
But it isn't deprecated...

I do agree it needs a note to explain on which installation types this integration can be used.

../Frenck

**Comment by owldown** [comment]
Seems to be many reports of it not working under HA OS (my experience) for multiple releases, and not under Core with Python 3.11. Not sure in which situations it might work, but it seems to not currently work with many standard installation methods. I agree there should be clarity in the docs, and maybe a check to not even allow setup on unsupported configuration.

**Comment by frenck** [comment]
A direct core installation on Python works (given you have set up bluez on your system)

**Comment by owldown** [comment]
The installation docs for Core say that Python 3.12 is a prerequisite (not sure if that's a best-practices suggestion or a requirement), but bluez is broken in 3.12. 

Maybe I'm not looking in the right place, but I'm not able to find documentation that states which versions of Python work with Core (to deduce a version that would be compatible with Core and bluez).

This page https://www.home-assistant.io/installation/macos suggests installing bluez and then making a venv for Core, but would that require different versions of Python for bluez and for Core?

I'm not asking to be walked through installing this, but it seems that if I were to follow that suggestion, I'd still end up with a version of Core and bluez that don't work together.
