### ISSUE TITLE
API Key Workaround ?

### ISSUE THREAD

**Issue by jasoncooke** [home-assistant/home-assistant.github.io#33766]
### Feedback

The warning states that API key disctribution was halted on March 28, 2024.
Is there another new way to access the Ecobee thermostat from Home Assistant ?

### URL

https://www.home-assistant.io/integrations/ecobee/

### Version

2024.7.2

### Additional information

I've seen online a way to integrate the Ecobee using Apple Homekit. 
What does one do if they are using the Android ecosystem instead ?

**Comment by frenck** [comment]
> Is there another new way to access the Ecobee thermostat from Home Assistant

As long as they are not handing out new API tokens, this integration cannot be picked up by new users. There is no workaround for that.

> I've seen online a way to integrate the Ecobee using Apple Homekit.
> What does one do if they are using the Android ecosystem instead ?

The Apple HomeKit connection isn't related to the Android Ecosystem (you don't need Apple devices to use that). Home Assistant has support for HomeKit devices built-in, see also: 

<https://www.home-assistant.io/integrations/homekit_controller/>

If you need more support, please try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

../Frenck
