### ISSUE TITLE
Details on shutterBox

### ISSUE THREAD

**Issue by wobeco** [home-assistant/home-assistant.github.io#33812]
### Feedback

Hi, I have switched from SIMU to the ShutterBox for shutter control via HA; according to the description of the integration (https://www.home-assistant.io/integrations/blebox#shutterbox), the functions 
    Open
    Close
    Position
    Tilt regulation
are supported.

About developer tools - I can see states
Status: open - closing - closed - opening
Attributes: current_position: 100 or 0 (no intermediate values!)
15 are displayed as supported_features

My questions:
- in the integration I only see one entity cover.roll_<location>_shutterbox_position; what's with the other 14 'features'?
- how can I read out the current position for use in automations?
- how can I define a favourite/my position (somewhere between 0% and 100%)?
Thanks for your support.

### URL

https://www.home-assistant.io/integrations/blebox/

### Version

2024.7.2

**Comment by swistakm** [comment]
Hi @wobeco

**Re: "15 features"**
I think the value `15` for the supported_features you are referring to is simply a bit mask storing information on supported values as individual bits in single integer number:

```
15 = 0b1111
```

It means that this integration supports features mapped by individual bit flags as follows:

```
0b0001 = 1 = OPEN
0b0010 = 2 = CLOSE
0b0100 = 4 = SET_POSITION
0b1000 = 8 = STOP
```

You can compare that with actual code for [CoverEntityFeature flag definition](https://github.com/home-assistant/core/blob/fa0a5451b9dc3b86e21f8c2f58e9fcf05b5ac230/homeassistant/components/cover/__init__.py#L106-L116)

**Re: controlling cover position in automations**
Unfortunately I don't have any experience regarding building automations. However, shutterbox integration in home-assistant implements typical cover component and properly advertises the `SET_POSITION` feature. If I understand correctly how such integrations work, it means you should be able to set desired position using `cover.set_cover_position` as [documented here](https://www.home-assistant.io/integrations/cover/#service-coverset_cover_position).

**Re: current_position: 100 or 0 (no intermediate values!)**
Shutterbox has a several control modes intended for different installation types (e.g. awning, window shutter, rolling shutter etc.). If I recall correctly these can be configured using dedicated app and may affect how device's API reports position. It may be that device requires connecting some kind of limit switch and/or calibration for it to be able to reliably report/accept position between 100-0. It would be best to consult manufacturer's manual for that device (I think [this](https://blebox.eu/wp-content/uploads/shutterBox_Manual_EN.pdf) is the one).

**Comment by wobeco** [comment]
Thank you very much for the quick and detailed answer - that helps me a lot. 👍
