### ISSUE TITLE
800 LR support?

### ISSUE THREAD

**Issue by EarlCrane** [home-assistant/home-assistant.github.io#33837]
### Feedback

https://www.home-assistant.io/docs/z-wave/controllers/#800-series-controllers
however:
https://community.home-assistant.io/t/z-wave-long-range-now-working-in-z-wave-js-ui-v9-10-0/712507

I'm confused in it now supports 800 LR and the doc in home-assistant just needs to be updated?

### URL

https://www.home-assistant.io/docs/z-wave/controllers/

### Version

2024.7.2

**Comment by frenck** [comment]
Long-range support for Home Assistant itself isn't available yet.

Underlying Z-Wave JS (and Z-Wave JS UI) support it, but native Home Assistant is not yet.

../Frenck
