### ISSUE TITLE
Ambient Weather Integration Broken

### ISSUE THREAD

**Issue by n1mie** [home-assistant/home-assistant.github.io#33839]
### Feedback

There is supposed to be an integration with the Ambient Weather station data. I've tried sixteen ways from Sunday to create and it flat out does not work. I've created the app and api codes and tried putting them where they belong, tried reversing them, tried everything. This feature is broken.

### URL

https://www.home-assistant.io/integrations/ambient_station/

### Version

2024.7.2

### Additional information

...

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
