### ISSUE TITLE
Troubleshoot steps

### ISSUE THREAD

**Issue by jenildesai25** [home-assistant/home-assistant.github.io#33838]
### Feedback

Try including steps to troubleshoot common issues. it's very hard to configure home assistant for first time. I have been banging my head to install HA in raspberry PI for a day now and some how DNS is not able to work and I have no idea on how to troubleshoot

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.7.2

**Comment by c0ffeeca7** [comment]
Thank you for the nudge, @jenildesai25 :+1: 
This one has been on my list for a while.

Closing this issue as addressed by #33947 and #33956
