### ISSUE TITLE
"home power from own" / Energy dashboard config "feed in" sensor

### ISSUE THREAD

**Issue by Karaswa** [home-assistant/home-assistant.github.io#33836]
### Feedback

Hi !
Can you add a description for "home power from own" in the _**Process Data Sensors**_ table ?

Additionally, can you add which sensor is best for grid feed in at **_Configuration of the energy dashboard_** ?

### URL

https://www.home-assistant.io/integrations/kostal_plenticore/

### Version

2024.7.2

**Comment by stegm** [comment]
This seems to be the sum of "home power from pv" and "home power from battery".
