### ISSUE TITLE
Denon AVR-X2500H is also working

### ISSUE THREAD

**Issue by edwin-2023** [home-assistant/home-assistant.github.io#33842]
### Feedback

title says it all ;)
Would be nici if I could also select the 4 quick select buttons

### URL

https://www.home-assistant.io/integrations/denonavr/

### Version

2024.7.2

### Additional information

title says it all ;)
Would be nice if I could also select the 4 quick select buttons

**Comment by starkillerOG** [comment]
The "Denon AVR-X2500H" has been listed on the documentation as supported: https://www.home-assistant.io/integrations/denonavr/
Therefore I will close this issue.
