### ISSUE TITLE
Suggest warning about automated polling issues

### ISSUE THREAD

**Issue by BenoitVH** [home-assistant/home-assistant.github.io#33861]
### Feedback

Hi, I'm very glad with the possibilities this BMW integration offers.
However, the default polling frequency will lead to BMW Connected Drive Cloud locking you out of your account after 2 days of working.
I found this out at my expense and had to dig into the solved issues pages to find the solution (issue #78792 ; bmw_connected_drive - 403 Quota Exceeded)
This (and other issues) also suggest good workarounds which basically mean going to manual polling for state changes.

Perhaps a warning in the documentation would be appropriate and would remove quite some frustrations... 

Kind regards,
Benoit

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2024.7.2

**Comment by rikroe** [comment]
Hi, we sometimes get quota issues, but in general the general feedback is that 5 minutes is fine for rest_of_world and 10 minutes for north_america. In which region are you located?

Do you use a lot of remote services to change vehicle state?

Also generally we have observed that quota issues come and go as BMW adjusts their configs as well.
Usually, it also resets at 12am UTC and everything continues to work. The MyBMW app continues to work from experience/feedback.

However some notes regarding best practices might be a good idea nonetheless.

**Comment by BenoitVH** [comment]
Hi,
Thanks for the reply, to your first question, I live in Europe.
When I got the problem there was hardly any other polling than the automated one the integration was doing to update an HA dashboard.
When it stopped, the car would be completely disconnected from the Internet : no updates in the My BMW app, no traffic info updates or changes to the BMW Id... It stopped working at 11am and automatically restored at 11am the next day (24h later)

I changed the dashboard polling to once every 20 minutes during the day and once per hour at night and had no issues since.

KR,

Benoit
________________________________

**Comment by rikroe** [comment]
To be honest, I would assume that this was a one time issue.

My car was polling status updates every 5 minutes between 2024-07-14 and 2024-07-20 (until HA restart due to update) and I didn't see the quota issue (also located in Europe).

Can you please try again using the default polling settings?

**Comment by BenoitVH** [comment]
The integration has been working like a breeze with the lower update frequency. 

So I’m quite happy as it stands; and I can always force a refresh by touching a control.

 

Thanks for your coding work!
