### ISSUE TITLE
Invalid Authentication

### ISSUE THREAD

**Issue by ajcorrea** [home-assistant/home-assistant.github.io#33881]
### Feedback

Integration not working since HA update. Today i upgraded to 2024.7.3 but not working.

The integration returns "Invalid authentication" but the credentials are correct (i have been logged in to web).

How i can debug this to see the real error ?

Thanks.

### URL

https://www.home-assistant.io/integrations/sunweg/

### Version

2024.7.3

**Comment by rokam** [comment]
Today Sunweg added recaptcha in the website, I'm trying to contact them. 
https://github.com/rokam/sunweg/issues/13

**Comment by rokam** [comment]
@ajcorrea this issue should be created at https://github.com/home-assistant/core/issues

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
