### ISSUE TITLE
Is it possible to add an extra service to kill a background process on the wall tablet?

### ISSUE THREAD

**Issue by Boppie1976** [home-assistant/home-assistant.github.io#33888]
### Feedback

Hello,

I was wondering if it is possible to add an extra service to kill a background process on the wall tablet. In the REST API there is a command to do this (/?cmd=killBackgroundProcesses&package=[package]&password=[pass]) but I realy dont know how to use a REST API in Home Assistant. 

I have created an automation in HA where I am using a service that allready exists to start a third party app on my tablet, and it would be great if I can use the requested service to close that app after a period of time.

Greetings, Bob.

### URL

https://www.home-assistant.io/integrations/fully_kiosk/

### Version

2024.7.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
