### ISSUE TITLE
Station ID

### ISSUE THREAD

**Issue by AShGloom** [home-assistant/home-assistant.github.io#33885]
### Feedback

It would be great to add directions on how to get necessary station ID which is used in “media_content_id: media-source://radio_browser/963ccae5-0601-11e8-ae97-52543be04c81”

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2024.7.3

**Comment by flubshi** [comment]
@AShGloom You can search for the channels here: https://www.radio-browser.info/
The station ID can be obtained from the URL, when opened a channel.

I agree, it would be great to add this information to the docs or to provide a easier way in HA to choose a channel.
