### ISSUE TITLE
Govee lights local not available as per the manual

### ISSUE THREAD

**Issue by srpablillo** [home-assistant/home-assistant.github.io#33898]
### Feedback

This integration s Govee lights local is not appearing in home assistant app on the iPhone. At least not as the manuals on the url provided 

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.7.2

### Additional information

I am running latest HA version available on Rapsberry Pi 4.

**Comment by Galorhallen** [comment]
Hi,
 I'm not sure, but if iirc the doc link can misbehave if you have installed a custom integration for (This is not strictly related to the Govee integration).
Have you tried to install the integration directly from home assistant UI (Settings -> Device and Services -> New Integration)?

**Comment by Manzabar** [comment]
I'm seeing the same issue. I'm running Home Assistant in a VM on a Synology NAS:

- Core 2024.7.3
- Supervisor 2024.06.2
- Operating System 12.4
- Frontend 20240710.0

Clicking the Add Integration to my HA from https://www.home-assistant.io/integrations/govee_light_local/ brings up this error in HA:

> This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant

I do have [HACS Govee](https://github.com/LaggAt/hacs-govee) installed and if I try to install the Govee Light Local integration directly from the home assistant UI (Settings -> Device and Services -> New Integration); then when I search the new integrations for Govee only HACS Govee shows up.

**Comment by Galorhallen** [comment]
> I do have [HACS Govee](https://github.com/LaggAt/hacs-govee) installed and if I try to install the Govee Light Local integration directly from the home assistant UI (Settings -> Device and Services -> New Integration); then when I search the new integrations for Govee only HACS Govee shows up.

Hi,
 I think that to make it work you have to remove the custom integration. See  https://github.com/home-assistant/frontend/issues/19720 and https://github.com/home-assistant/core/issues/109921

**Comment by Manzabar** [comment]
> Hi, I think that to make it work you have to remove the custom integration. See [home-assistant/frontend#19720](https://github.com/home-assistant/frontend/issues/19720) and [home-assistant/core#109921](https://github.com/home-assistant/core/issues/109921)

That's a might unfortunate, as most of my Govee products don't include support for the local API. So I need to keep using alternate means to control them, but  I was hoping to test the local lights integration out with a new light strip I got recently. Thanks for the info, I'll keep an eye on those issues you mentioned in case things change in the future.

**Comment by Galorhallen** [comment]
@home-assistant close
