### ISSUE TITLE
How do I get supervised mode to work on my Linux installation?

### ISSUE THREAD

**Issue by SKelem** [home-assistant/home-assistant.github.io#33897]
### Feedback

I installed via docker, but don't have access to the Addons. Why is this so difficult? Why isn't there a step-by-step set of instructions for getting to where I am (no Addons) to having addons?

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2024.7.3

### Additional information

I think I have a VM installed too, but only God knows how to get access to it, or if it's the right thing to do!

**Comment by c0ffeeca7** [comment]
If I understand correctly, you are using the container installation type? Home Assistant Container and Home Assistant Core installation types do not support add-ons.
<https://www.home-assistant.io/installation/#advanced-installation-methods>
![image](https://github.com/user-attachments/assets/3542f867-3ecf-471e-8573-bb20348a329b)

There is a note indicating this in the Installation instructions for Container:
<https://www.home-assistant.io/installation/linux#install-home-assistant-container>
![image](https://github.com/user-attachments/assets/7a0bb2fc-1466-498c-abe0-432c639f23f9)
