### ISSUE TITLE
This entity is no longer being provided by the weatherflow integration

### ISSUE THREAD

**Issue by drirwin** [home-assistant/home-assistant.github.io#33907]
### Feedback

Day before yesterday (7/19), at around 6:58 CDT, I applied core update 2024.7.2.  I noticed later that evening, that Weatherflow sensors I use in multiple automations, went to "unknown" state, affecting triggers and conditions they were featured in.  Is this a problem that will be resolved, or have these sensors been depricated?  I do notice there are another set of sensors that reflect the same data that are being updated as the ones I have been using successfully in the past, but no longer work.  

### URL

https://www.home-assistant.io/integrations/weatherflow/

### Version

2024.7.3

**Comment by natekspencer** [comment]
The code for this integration hasn't changed for a few months, were you previously on core 2024.7.1? Have you had to swap out your Weatherflow station or any other recent changes?

**Comment by drirwin** [comment]
Yes, I was at 2024.7.1.  No recent changes to my Weatherflow unit.
This is the first time I have really studied the Weatherflow integration since I set it up last year.  It appears there are two sets of entities.  One set associated with the station ID (JCMO-WEST) and the other set associated with the tempest device (ST-00020009).  The HA WF entities I have been using in my automations since it was installed are those associated with the station ID.  These are showing unavailable.  However, the entities associated with the tempest device are reflecting and updating current weather data.   I am in the process of switching out entitiy ids to those associated with the tempest device.  I will report back my results soon.  Thanks...Don

**Comment by natekspencer** [comment]
Ahh, it sounds like you are using weatherflow_cloud instead of UDP.

**Comment by jeeftor** [comment]
Are you using the hacs integration? The official cloud integration doesn't have device support until next release - and then its only a subset for now

**Comment by drirwin** [comment]
The Weatherflow integration I am using is not the cloud version.  I believe
I obtained it through the normal integration method (not HACS).  It exposes
20+ entities (see images) that I use some of in several automations .  It
also exposed 20+ entities whose state says “undefined”.  Prior to the other
day, I was using these in my integrations.  After changing to the other set
of entities, all is operating normal.   I am debating deleting these
entities to remove future confusion.

**Comment by natekspencer** [comment]
Apologies if there is some confusion. Station ID is not part of the core integration which is what lead me to think you might be using a cloud integration. You're picture was not included (likely from trying to respond via email).

This is the wrong repo (Home Assistant website) for this issue, however, so I'm going to close it. Please re-open in https://github.com/home-assistant/core/issues if you need further assistance and include debug logs/photos there.

**Comment by natekspencer** [comment]
@home-assistant close
