### ISSUE TITLE
Cutting Zones

### ISSUE THREAD

**Issue by plasterer41** [home-assistant/home-assistant.github.io#33905]
### Feedback

Hi, I have a 435x mower that supports zones. I cannot find how to set a zone active using the integration. (the husqvarna app supports it). Is the service built into the integration (and I just can't find it) or does it not support it?

Many thanks,

### URL

https://www.home-assistant.io/integrations/husqvarna_automower/

### Version

2024.7.3

**Comment by Thomas55555** [comment]
Alls supported functions are in the documentation.

**Comment by plasterer41** [comment]
Hi, thanks for replying. Is it possible to develop this function?

**Comment by frenck** [comment]
> Hi, thanks for replying. Is it possible to develop this function?


Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
