### ISSUE TITLE
Update for non-homeassistant.io users

### ISSUE THREAD

**Issue by laemen** [home-assistant/home-assistant.github.io#33915]
### Feedback

If you have your own local install not connected to home-assistant.io you can use the https://mydomainname.com/auth/external/callback URL. ([more](https://community.home-assistant.io/t/application-credentials-support-local-oauth-redirect-endpoints/490533
))

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2024.7.3

**Comment by frenck** [comment]
@laemen Hi there 👋 

Yes, you are correct, and that is documented.

![CleanShot 2024-07-22 at 11 19 06@2x](https://github.com/user-attachments/assets/79886583-8fb3-48b4-b276-a44077742d26)

I'm not sure what your suggestion is, can you clarify?

../Frenck

**Comment by laemen** [comment]
Ah, wasn't looking at the right place. The dropdown is closed and My Home Assistant doesn't ring a bell for me as non user.
![image](https://github.com/user-attachments/assets/9fb3ecf3-7223-4770-adae-fd7452f5a51c)
Thanks, this can be closed.
