### ISSUE TITLE
Refresh time of 30 Seconds is too long 

### ISSUE THREAD

**Issue by AlexJacu** [home-assistant/home-assistant.github.io#33913]
### Feedback

Refresh time of 30 Seconds is too long to have a accurate energy metering using photovoltaik or management of energy with battery. 
It would be good, if the user could reduce the refresh time to 1 second ore any other betweet 1 an 30 seconds

### URL

https://www.home-assistant.io/integrations/discovergy/

### Version

2024.7.3

**Comment by jpbede** [comment]
To update your entities on a custom pace, you can use the `homeassistant.update_entity` service, please checkout the [documentation](https://www.home-assistant.io/common-tasks/general/#defining-a-custom-polling-interval).

Please keep in mind, if you reduce the update interval you may be subject to rate limiting and thus a not working integration.
