### ISSUE TITLE
password reset process is awful

### ISSUE THREAD

**Issue by rbedger** [home-assistant/home-assistant.github.io#33921]
### Feedback

what the heck?  i'm about 95% certain that bitwarden didn't "forget" my pasword, but i go to boot up a relatively fresh install and i'm unable to log in.   wifi is giving some garbage cryptic error (even though nothing about the environment has changed since install), so i jack directly into my switch, which is currently actively serving internet to my laptop a few feet away.  still refuses to work, continuing to spam whatever "-52" message is that i can't login in order to diagnose.  are you telling me that I am required to have an "active" internet connection in order to even log in to my own device?  if that's the case that's gonna be a no for me, dawg.

### URL

https://www.home-assistant.io/docs/locked_out/

### Version

2024.7.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation issues, not for providing support or feature requests.

If you want to suggest a feature or improvement to our software, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
