### ISSUE TITLE
Create Account (Create User) screen should state username must be lowercase 

### ISSUE THREAD

**Issue by jksmurf** [home-assistant/home-assistant.github.io#33951]
### Feedback

Referring to the issue I raised [here](https://github.com/home-assistant/core/issues/122356#issuecomment-2247809668), which has more detail, the Create User form would benefit greatly from either explanatory text under the username field and/or a function associated with that field which automatically changes the username to lowercase.

Currently you can type in a username with Uppercase/Lowercase combinations, the button (to proceed) goes blue (assuming all other fields are filled in) but **nothing happens** and there is no error message at all so you’re left in the dark.

I would very much appreciate you considering this minor update which will help others.

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2024.7.3

### Additional information

Refer details in the link above.

**Comment by c0ffeeca7** [comment]
Thank you for the catch :fishing_pole_and_fish: , @jksmurf :+1:
