### ISSUE TITLE
Sensor time remaining - change to timer

### ISSUE THREAD

**Issue by pepsonEL** [home-assistant/home-assistant.github.io#33959]
### Feedback

Hi
Integration provide from section sensors which show time remaining to finish irrigation. In my opinion and also to good standard in Home Assistant this sensor should be change from sensor to timer because it works as timer.

![image](https://github.com/user-attachments/assets/33861139-fa28-489e-ace7-852d0ef0fc53)

### URL

https://www.home-assistant.io/integrations/hydrawise/

### Version

2024.7.3

**Comment by dknowles2** [comment]
Integrations cannot add timer entities, as a timer is an integration itself.

See:
* https://www.home-assistant.io/integrations/timer/
* https://developers.home-assistant.io/docs/core/entity

**Comment by dknowles2** [comment]
@home-assistant close
