### ISSUE TITLE
APSystems is missing documentation of sensors

### ISSUE THREAD

**Issue by c0ffeeca7** [home-assistant/home-assistant.github.io#33972]
### Feedback

The APsystems integration is missing documentation of some of the sensors. A separate section "sensors" listing all the names together with a description

### URL

https://www.home-assistant.io/integrations/apsystems/

### Version

2024.07

**Comment by mawoka-myblock** [comment]
Thanks!

**Comment by c0ffeeca7** [comment]
Fixed by https://github.com/home-assistant/home-assistant.io/pull/34200
