### ISSUE TITLE
Code owner for modbus is not updated

### ISSUE THREAD

**Issue by janiversen** [home-assistant/home-assistant.github.io#33987]
### Feedback

https://www.home-assistant.io/integrations/modbus/

Seems I cannot submit a PR that changes the code owner, so instead I open this issue,

I have for a while now, not been code owner for modbus, but the documentation still claims I am. This makes users write me which is quite annoying.

Please synchronize codeowners with the actual codeowners in core.

thanks in advance

### URL

https://www.home-assistant.io/integrations/modbus/

### Version

2024.7.3

**Comment by frenck** [comment]
It is correct, current stable reflects 2024.7, not 2024.8 which contains the code owner change.

Closing this, as it is correct handled and will change with the next plannend release.

../Frenck
