### ISSUE TITLE
errei na digitação de senha do spotify

### ISSUE THREAD

**Issue by Gaio-Christiano** [home-assistant/home-assistant.github.io#33984]
### Feedback

eu erreiu quando fui digitar a senha e não consigo digitar novamente meu login e senha e fica abrindo a pagina que não me deixa editar nada, como eu resolvo isso?
![image](https://github.com/user-attachments/assets/3a20ece5-2a8c-4b58-9d79-6a10a266aa20)

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2024.7.3

### Additional information

Eu digittei minha senha errada.
![image](https://github.com/user-attachments/assets/095eeb86-8db9-4a60-a804-5e9cdb238bde)

**Comment by joostlek** [comment]
Hello 👋,

Our communication language is English. Please recreate your issue in English.
