### ISSUE TITLE
Rainmachine request

### ISSUE THREAD

**Issue by mikemlodg** [home-assistant/home-assistant.github.io#34012]
### Feedback

First off, this homeassistant device work great!  I have recently setup an automation for a program to run when it gets passed a certain temperature to help cool the grass and stop it from "burning up".  Would it be possible to have this automation not get logged for watering history?

Thank you
Mike

### URL

https://www.home-assistant.io/integrations/rainmachine/

### Version

2024.7.3

**Comment by bachya** [comment]
Hi there! This GitHub repo is for issue reporting and tracking. Please share feature requests in the [Home Assistant Community Forum](https://community.home-assistant.io/).

**Comment by mikemlodg** [comment]
Got it, sorry
