### ISSUE TITLE
Icloud loop

### ISSUE THREAD

**Issue by jscherry** [home-assistant/home-assistant.github.io#34017]
### Feedback

I've been using icloud integration for a long time. All the sudden it keeps saying reauthentication required. Doesn't work, even went so far as to delete the app, restart ha, deleted old app-specific password and created a new one. It accepts the user id and app sprecific password but doesn't trigger the authentication code? 

### URL

https://www.home-assistant.io/integrations/icloud

### Version

2024.7.2

### Additional information

running home assistant os on home assistant blue. was working on last version of home assistant but doesn't work with 2024.7.3

**Comment by frenck** [comment]
Hi there @jscherry 👋 

It seems like you want to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
