### ISSUE TITLE
Home assistant on proxmox

### ISSUE THREAD

**Issue by edwin-2023** [home-assistant/home-assistant.github.io#34029]
### Feedback

There is a procedure for hyper-v and VMware but I'm missing one for proxmox. Now that VMware is taking another road I guess proxmox will fill in the space. 

### URL

https://www.home-assistant.io/installation/windows/

### Version

2024.7.4

**Comment by tjbenator** [comment]
I believe this would need to be added to https://www.home-assistant.io/installation/alternative

I'll work on instructions for Proxmox specifically since that's what I run as well. 🤓

**Comment by edwin-2023** [comment]
Thnx!
