### ISSUE TITLE
How to surface the Light Effects and change speed?

### ISSUE THREAD

**Issue by soupman98** [home-assistant/home-assistant.github.io#34031]
### Feedback

I can see the Effect and Speed in a switch card/control but can't figure out how to surface that otherwise in HA
![Pool light hayward issue](https://github.com/user-attachments/assets/1a7b092a-5878-4dec-9ee7-ae226e777b0c)

### URL

https://www.home-assistant.io/integrations/omnilogic/

### Version

2024.7.4

**Comment by neehhaa06** [comment]
Hello!! @soupman98 :)
# I think this answer might be helpful for this bug:

> Check Integration Setup: Confirm OmniLogic setup in Integrations.
> Inspect Entity: Look at attributes in Developer Tools > States.
> Edit UI: Add Light or Entities card in Edit Dashboard.
> Use Custom Cards: Try custom Lovelace cards if needed.
> Update: Ensure Home Assistant and OmniLogic are updated.
> Review Documentation: Check OmniLogic docs and community forums.
> Reconfigure/Report: Reconfigure or report on GitHub if unresolved.

**Comment by frenck** [comment]
@neehhaa06 This ain't a bug, and your answer makes 0 sense. Are you a bot or what?

**Comment by neehhaa06** [comment]
Hello @frenck :)
Okay, I got it, would you be able to explain this to me?
No, I am not a bot.

Thankyou!!
