### ISSUE TITLE
My HomeAssistant says No Devices or Entities

### ISSUE THREAD

**Issue by IIIdefconIII** [home-assistant/home-assistant.github.io#34048]
### Feedback

This while all devices does work from the mobile app home assistant report there now devices.
I Enabled all devices -> Cloud Services
No Devices or Entities
![image](https://github.com/user-attachments/assets/bfbe1eb4-9fd5-478d-8352-c4c73e47cb2c)

### URL

https://www.home-assistant.io/integrations/switchbot_cloud/

### Version

2024.7.4

### Additional information

I would love to get feedback, i did the proper setup with the Token and Secret Key. and i believe it was working 2/3 months ago

**Comment by IIIdefconIII** [comment]
> Hey there @SeraphicRav, @laurence-presland, mind taking a look at this feedback as it has been labeled with an integration (`switchbot_cloud`) you are listed as a [code owner](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L794) for? Thanks!
> 
> Code owner commands
> Code owners of `switchbot_cloud` can trigger bot actions by commenting:
> 
> * `@home-assistant close` Closes the feedback.
> * `@home-assistant rename Awesome new title` Renames the feedback.
> * `@home-assistant reopen` Reopen the feedback.
> * `@home-assistant unassign switchbot_cloud` Removes the current integration label and assignees on the feedback, add the integration domain after the command.
> * `@home-assistant add-label needs-more-information` Add a label (needs-more-information) to the feedback.
> * `@home-assistant remove-label needs-more-information` Remove a label (needs-more-information) on the feedback.

Thanks you so much for the quick follow up as i want to buy alot more stuff for switchbot

**Comment by SeraphicRav** [comment]
@IIIdefconIII Hi!
I am sorry, the issue lacks information. Can you share the logs from switchbot_cloud from the moment Home Assistant starts? In debug mode, there should be a log with all the detected SwitchBot devices or error logs.

The integration also does not support all Switchbot devices, only those listed in the documentation, which devices are you using?

**Comment by SeraphicRav** [comment]
@home-assistant add-label needs-more-information

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by IIIdefconIII** [comment]
i reported it to  the devs itself but i didnt got any straight answerr so this ticked can be close
