### ISSUE TITLE
Custom tts voices/services

### ISSUE THREAD

**Issue by DrToxic** [home-assistant/home-assistant.github.io#34057]
### Feedback

I am looking for a way to integrate a custom tts / voice into home assistant. Namely GLaDOS from portal. I have a tts engine downloaded, but I'll be a monkeys uncle if I can figure out how to make it a part of the assist flow.

### URL

https://www.home-assistant.io/integrations/tts/

### Version

2024.7.4

### Additional information

https://www.nerdaxic.com/glados-voice-generator/
This is downloadable from GitHub. It would be awesome to see it integrated, or maybe documentation on DIY TTS?

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
