### ISSUE TITLE
Feature and Support Request

### ISSUE THREAD

**Issue by NoahB2000** [home-assistant/home-assistant.github.io#34058]
### Feedback

Im submitting this on here because it appears I keep getting directed to the support page for Home Assistant itself, not the API.

Please add support for Govee H6000 series bulbs such as H6009 and H6004. Also, I added the integration and, according to the current list of supported devices, my LED strip is compatible, but the integration cant find it on my network and says startup failed.

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.7.4

### Additional information

Im submitting this on here because it appears I keep getting directed to the support page for Home Assistant itself, not the API.

Please add support for Govee H6000 series bulbs such as H6009 and H6004. Also, I added the integration and, according to the current list of supported devices, my LED strip is compatible, but the integration cant find it on my network and says startup failed.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
