### ISSUE TITLE
resize section size

### ISSUE THREAD

**Issue by Johnnytrapano** [home-assistant/home-assistant.github.io#34065]
### Feedback

Hi, i love the new section view and how is being developed.
I would love to have the possibility to resize the columns (in the same way is possible to resize the cards in the sections), or at least i would love that the size of the section is automatically adapted to the screen i'm using. 
For example if i use a single column, on the smartphone is ok, but in the computer only a small column is used.

### URL

https://www.home-assistant.io/dashboards/sections/

### Version

2024.7.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
