### ISSUE TITLE
Database upgrade not mentioned

### ISSUE THREAD

**Issue by pjannink** [home-assistant/home-assistant.github.io#34075]
### Feedback

I noticed after installing the 2024.8 beta that a database upgrade was performed.I did not read that in the concept release notes

### URL

https://rc.home-assistant.io/blog/2024/07/31/release-20248/

**Comment by frenck** [comment]
It is actually explained and put up as the main upgrade notice (the first one listed)

![CleanShot 2024-08-02 at 12 38 02@2x](https://github.com/user-attachments/assets/67cac5ea-64c4-4b6a-9f4b-85b5c3f4561d)

../Frenck
