### ISSUE TITLE
homeassistant.appapi vs appdaemon.appapi

### ISSUE THREAD

**Issue by n8henrie** [home-assistant/home-assistant.github.io#3407]
I'm getting an import error with `import homeassistant.appapi`, and I don't see that module in the HA source, but documentation in both https://github.com/home-assistant/appdaemon and https://github.com/home-assistant/home-assistant.github.io refers to `homeassistant.appapi` at least once. I'm wondering if this is an error and references to `homeassistant.appapi` should actually be to `appdaemon.appapi`.

Because both repos contain at least one reference in question, I'm starting (identical) issues in both repos: 
- https://github.com/home-assistant/appdaemon/issues/141
- https://github.com/home-assistant/home-assistant.github.io/issues/3407

Should be a simple fix, but before I make a PR I wanted to make sure this wasn't intentional, i.e. preparation for an upcoming merge of appdaemon into HA (to avoid having to do separate installs) or something. Searching existing issues for `homeassistant.appapi` doesn't yield any results.

**Comment by acockburn** [comment]
Should be appdaemon.appapi.

I fixed the ones I could find.
