### ISSUE TITLE
Marantz Cinema 60 (Australian) is working!

### ISSUE THREAD

**Issue by lordmortis** [home-assistant/home-assistant.github.io#34078]
### Feedback

I am currently using a Marantz Cinema 60 with this integration (with both the firmware it came with and the latest) and it's working perfectly. 

HA detected the device. The one setting that needs to be set is the one in the docs below:
> To remotely power on Marantz receivers with Home Assistant, the Auto-Standby feature must be enabled in the receiver’s settings.

Can power on/off - have other devices tracking the power state and working well. Source switching and volume control also working. Thank you for the integration!

### URL

https://www.home-assistant.io/integrations/denonavr/

### Version

2024.7.4

**Comment by starkillerOG** [comment]
Thanks for the feedback, I added the CINEMA 60 to the list of supported models in the docs.
