### ISSUE TITLE
ID: Number

### ISSUE THREAD

**Issue by Marc19550831** [home-assistant/home-assistant.github.io#34073]
### Feedback

Really do I just create the ID:number, or do you need to generate it from some place

### URL

https://www.home-assistant.io/docs/automation/yaml/

### Version

2024.7.4

**Comment by frenck** [comment]
You can make it anything you like, as long as it is unique. Some people have a strategy for naming the ID, others use a UUID generator or something like a password generator kinda thing.

Please note, using them, is also completely optional.

../Frenck
