### ISSUE TITLE
Remove deleted devices

### ISSUE THREAD

**Issue by TEdvardS** [home-assistant/home-assistant.github.io#34088]
### Feedback

It would be nice to be able to delete devices that has bee deleted fro the Fibaro platform without have to reset the entire integration.

### URL

https://www.home-assistant.io/integrations/fibaro/

### Version

2024.7.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck

**Comment by rappenze** [comment]
This feature should be available in 2024.8.
Implemented in https://github.com/home-assistant/core/pull/121427
