### ISSUE TITLE
Please add some explanation how to use this

### ISSUE THREAD

**Issue by snuf72** [home-assistant/home-assistant.github.io#34086]
### Feedback

Added this in the configuration but doesn’t know what to do next

### URL

https://www.home-assistant.io/integrations/pjlink/

### Version

2024.7.4

**Comment by frenck** [comment]
What do you mean, what to do next?

Integrations integrate devices and services into Home Assistant. What you want to do next, is up to you? Automate, make dashboards, monitor? It is not specific to this integration, but applies to everything you already can do with Home Assistant in general?

../Frenck

**Comment by snuf72** [comment]
Can’t get the PJLink plugin working

Added this in the config



And created automation



But it doesn’t work
Also when selecting the player it is grayed out



Is there a manual how to use pjlink?

Best Regards,

Sylvain van Uffelen

**Comment by frenck** [comment]
I think you are trying to show me thing (maybe screenshots?) but You've used email to respond. Please note, GitHub responses to emails are pretty limited and badly formatted by GitHub. Please use GitHub itself to reply.

../Frenck
