### ISSUE TITLE
This entity doesn’t have a unique id

### ISSUE THREAD

**Issue by snuf72** [home-assistant/home-assistant.github.io#34087]
### Feedback

How to solve this?
This entity ('media_player.awol3500') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

### URL

https://www.home-assistant.io/integrations/pjlink/

### Version

2024.7.4

**Comment by frenck** [comment]
> How to solve this?

You can't solve this. It is perfectly valid for an integration/entity not being able to provide a unique ID.

../Frenck

**Comment by snuf72** [comment]
Ok,
But it’s not working either.

Can you give additional info how to use this player

Tried with adding automation:

- id: '1721645711611'
  alias: beamer aan
  description: ''
  trigger: []
  condition: []
  action:
  - service: media_player.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: media_player.awol3500
  mode: single

Best Regards,

Sylvain van Uffelen
