### ISSUE TITLE
Error on adding a local Uptime robot API

### ISSUE THREAD

**Issue by abdulghanitech** [home-assistant/home-assistant.github.io#34092]
### Feedback

I'm having trouble adding the API key of Uptime Robot in Home Assistant. I keep getting an error that says "Invalid API key." I have added Uptime Robot as an add-on using Home Assistant, and both are working properly locally. However, when I try to add it to the dashboard, I encounter this API error.

<img width="431" alt="image" src="https://github.com/user-attachments/assets/eecb88bf-d166-4b93-82d8-e1455cf6db20">

### URL

https://www.home-assistant.io/integrations/uptimerobot/

### Version

2024.7.4

**Comment by chemelli74** [comment]
Can you post the screenshot of the uptime page from witch you grab the key ?

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
