### ISSUE TITLE
Love it - thank you

### ISSUE THREAD

**Issue by commking** [home-assistant/home-assistant.github.io#34109]
### Feedback

I'm not a coder - I wish I had the ability to do what I ask here

'd like the ability to have a button on my dashboard for the Scenes I have set up for my Intesis A/C?

### URL

https://www.home-assistant.io/integrations/intesishome/

### Version

2024.7.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
