### ISSUE TITLE
Not enough instructions to set it up

### ISSUE THREAD

**Issue by tingdahl** [home-assistant/home-assistant.github.io#34124]
### Feedback

I have a few Tapo P110 and P115 devices I wish to connect to home assistant. All plugs are available on the network, and accessible in TP-Link's tapo app.

When I enable the tplink integration it asks for a host. If I leave it empty, it fails do discover the plugs. If I fill in the IP number of one of the plugs, it gives a "failed to connect". I wonder if the documentation could be filled in with some info on what type of host is thought of? Is it a central service that I should run, or a service of tp-link in the cloud? Or the host of the plug? The plugs have port 80 open, and replies a 200 OK.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.7.4

**Comment by palros** [comment]
Just to add to this, i am getting exactly this issue. I even bought a Tapo hub in the hope that that would fix it, but it has not. 
This is the only device that I have been unable to get connected to my setup.

**Comment by rytilahti** [comment]
The discovery uses UDP broadcast to detect the devices, so they have to be in the same network (/broadcast domain) as your homeassistant instance. Is that the case?

The host is indeed the host of the device, so inputting the IP address (or hostname) of your device in the field should also work as long as you are not blocking connectivity between the homeassistant host and the device.

For testing, you can also use [python-kasa and it's `kasa` cli tool](https://github.com/python-kasa/python-kasa/) to verify that the communications are working as expected.

**Comment by MurrayEatonKWX** [comment]
I have the HS103 which HA discovers fine. Problem is when adding I get a "cannot_connect" error and that's it. I assume its an authentication problem but no idea how to resolve it as theres no further interface.

**Comment by MurrayEatonKWX** [comment]
Here is what it auto discovers
![Screen Shot 2024-09-17 at 5 13 01 PM](https://github.com/user-attachments/assets/0c141258-86c7-4d2e-94c7-995e3caafa10)

Then I click submit

![Screen Shot 2024-09-17 at 11 09 22 AM](https://github.com/user-attachments/assets/d70dfb97-400b-4cf5-8dca-553c6b57ceb6)

and I dont get an option to enter authentication credentials.

**Comment by rytilahti** [comment]
@MurrayEatonKWX that's a different issue, please report it at https://github.com/home-assistant/core/issues/new/choose
