### ISSUE TITLE
Non working example provided

### ISSUE THREAD

**Issue by idkpmiller** [home-assistant/home-assistant.github.io#34120]
### Feedback

The initial yaml example on this page provided for this hard to grasp integration is incorrect. the way it is currently set up it will never show the kitchen light as on.
Having a non working simple example will make users walk away completely baffled.

### URL

https://www.home-assistant.io/integrations/bayesian/

### Version

2024.7.4

**Comment by HarvsG** [comment]
I think this is a fair point, I will open a pr  to raise the prior
