### ISSUE TITLE
Documentation around Matter implies it is a local standard, when it actually requires cloud services to function

### ISSUE THREAD

**Issue by Whistlerone** [home-assistant/home-assistant.github.io#34135]
### Feedback

All the documentation I can find around Matter in Home Assistant states

> Matter products run locally and always allow local control, with device control done without the need for any internet connection or cloud services. From a technical perspective, you can use a Matter-compatible device with Home Assistant without connecting to a vendor-specific cloud. However, some vendors may require you to set up an account before you can enable Matter support for some products, (especially for commercial manufacturer’s own branded gateways/bridges/hubs/controllers sold as appliances).

but in reality connection to Google servers is actually required to use any matter devices.  If you try to add any device while connected to a wifi network with no internet, you are immediately met with this error
![image](https://github.com/user-attachments/assets/a01b4dd9-601b-48a3-a87b-6c516c53b9c6)

the documentation needs to be more upfront about the requirement for not only internet access to function, but also the requirement to depend on Google owned cloud servers.

### URL

https://www.home-assistant.io/integrations/matter

**Comment by marcelveldt** [comment]
I'm afraid this is a weird limitation of the Android framework - it has no impact on the commissioning of matter devices to HA, that is fully local and nothing depends on cloud servers. Internet access is required to grab the root certificates for the attestation request (= security!).

**Comment by Whistlerone** [comment]
and **I'm** afraid you're missing the point.  Documentation states an internet connection is not required.  I make hardware purchases based off of this information. you yourself admit internet access **IS** required. money and time wasted. 
so, the documentation needs to be updated to emphasize that Matter **requires** an internet connection.

**Comment by marcelveldt** [comment]
OK, I shall rephrase then.

The device does NOT need internet access at all!
Your phone needs internet access
Your HA server needs internet access

**Comment by Whistlerone** [comment]
I understand.  what I don't understand is the unwillingness to be honest about that fact in the documentation

**Comment by marcelveldt** [comment]
> I understand. what I don't understand is the unwillingness to be honest about that fact in the documentation

You are yet again mixing things up. Your phone is having that dependency to internet, not Matter devices.
That dependency exists on the Android ecosystem and has literaly nothing to do with Matter.

Maybe Apple does not have this dependency, maybe try an Apple phone ?

I'm closing this conversation as its not getting us anywhere.
