### ISSUE TITLE
Trying to build the $13 voice assistant doesn't work

### ISSUE THREAD

**Issue by mhalano** [home-assistant/home-assistant.github.io#34140]
### Feedback

This is a bug report, but for the website itself. I'm trying to configure my ATOM Echo to be a voice assistant for Home Assistant but I can't do that because the link to write the firmware is unrepairable broken.
You click in Connect, it shows you the list of devices, you select the correct one but get the error "Failed to download manifest". I checked using the Chrome's console and it's the file missing.

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Additional information

The file https://firmware.esphome.io/voice-assistant/m5stack-atom-echo/manifest.json can't be found.

**Comment by tjbenator** [comment]
Doing some digging it looks like the build github actions were changed (which generate/upload that file) and the voice assistant code was moved:
esphome/firmware#253 

The new URI for the manifest.json file is https://firmware.esphome.io/wake-word-voice-assistant/m5stack-atom-echo/manifest.json
