### ISSUE TITLE
TUYA HUB is trying to connect to DEAD "apigw.tuyaeu.com" address ... TUYA is not working at all.

### ISSUE THREAD

**Issue by AnunnakiNibiru** [home-assistant/home-assistant.github.io#34141]
### Feedback

Few weeks ago, installed new "Home Assistant Green" device, and tried to add TUYA integration.
I was not working and I was not having time to solve that then, so I was not using it at all.
But yesterday I tried it again, but with the same negative result as before.
I even performed "factory recovery" via SD card to start "fresh".

I think you are using non-functional API FQDN address:
apigw.tuyaeu.com
instead correct one:
openapi.tuyaeu.com

What I did/tested so far:
After factory reset I started fresh.
I immediately as first step tried add TUYA integration (the one already available via GUI).
I added user code (from mobile app), via mobile app QR scan I confirmed "Home Assistant" user.
In my "Tuya app" on mobile phone > settings > account and security > and under "Third-Party Authorization Management" I have now "Home Assistant" with 2 permissions:
"Access your account information"
"Access the control of your device"
So, I assume, "authorization" steps are done correctly.

But ... inside Home Assistant, integration never finished correctly, even after few minutes of waiting it show "succesfully" but window does not contain any other information like it should (according other Youtube videos I have seen).
In Home Assistant under Tuya integration I see:
Needs attention
No devices or entities
Failed to set up:
Check the logs
...and...
Hubs
No entires

I tried "Enable debug logging" and it seems to me that it tries to connect to:
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apigw.tuyaeu.com', port=443): Max retries exceeded with url: /v1.0/m/life/users/homes (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff65a5b080>, 'Connection to apigw.tuyaeu.com timed out. (connect timeout=None)'))

I investigated, that for my location (Czech Republic) I am at "Central Europe Data Center".
That FQDN apigw.tuyaeu.com is translated to IPs: 3.123.196.97 and 18.193.166.37 .
I even tried "tcpdump" communication from HA, my router (home&work), from laptop (my work), and even from my mobile phone (5G) ... (note that all 3 devices are using different ISP operator, and communicating out via different public addresses, so it is no connection issue on my side), but in every case:
That packet is send (with SYN tcp flag) to one of those two IP addresses (under FQDN apigw.tuyaeu.com), but reply is never received. There should be at least TCP SA or R packet received. But no response at all.

In some documentation on TUYA is mentioned, that "Central Europe Data Center" should use different API FQDN:
openapi.tuyaeu.com (that one is responding to wget and ping correctly).
(see here documentation with all API FQDNs for all regions:
https://developer.tuya.com/en/docs/iot/api-request?id=Ka4a8uuo1j4t4 )

So my question is ... are you 100% sure, that you are using correct API address?
And if so, why that address is not responding for users in Czech Republic around Prague at least?

Thank you for reply.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.7.4

### Additional information

If you wish, I can share my desktop with access to home assistant green and even share my phone app, if you wish investigate/test something further.

If you need more info, just let me know.

**Comment by AnunnakiNibiru** [comment]
Hi.

Sorry, but 2 days are gone, and still no response for such important discovery?

Can you at least test connection to that FQDN from your deployment to confirm, if at least IPs for "apigw.tuyaeu.com" ( 3.123.196.97 and 18.193.166.37 ) are replying for TCP SYN packet ?
If not, that means official TUYA integration is not working for all those users, where this FQDN is used (probably from all from "central" EU states).
Or ... why is my official TUYA integration is trying to connect to FQDN, which is not alive anymore, and how/where can I change that address to function one?

Thanks.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by AnunnakiNibiru** [comment]
Thanks, you are right.
I created new ticket in propriet section:
https://github.com/home-assistant/core/issues/123375
