### ISSUE TITLE
Home Assistant Yellow - Documentation Correction - Not Zero Setup.

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [home-assistant/home-assistant.github.io#34148]
### Feedback

Incorrect marketing on yellow page.

This image, needs to be removed-

![image](https://github.com/user-attachments/assets/1792a876-baf8-4670-9644-d86475fd1f17)

Reason-

Zero Setup, is not compatible with, "Some assembly required". Compute module is also not included now.

![image](https://github.com/user-attachments/assets/6b41b0e5-52e9-4d37-9a41-b2b14a1eb78f)

If- someone were to purchase home assistant yellow, upon reason "Zero Setup Required, Comes Preinstalled with Home Assistant", and received it, without a M.2, or a CM4, they would be awfully disappointed.... since, home assistant is not preinstalled (as there is no storage), and cannot be installed (as- there is still no storage!), without adding the correct CM4 and/or M.2

### URL

https://www.home-assistant.io/yellow/

### Additional information

https://github.com/home-assistant/home-assistant.io/edit/current/source/yellow/index.html

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @XtremeOwnageDotCom :+1:
