### ISSUE TITLE
Govee lights local not working

### ISSUE THREAD

**Issue by telstir** [home-assistant/home-assistant.github.io#34158]
### Feedback

Failing repeatedly showing error msg ... ! Failed setup, will retry.

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.7.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
