### ISSUE TITLE
Something to add

### ISSUE THREAD

**Issue by caitotheonlypotato** [home-assistant/home-assistant.github.io#34185]
### Feedback

This is something superficial, however it might be worthwhile mentioning on the integration's info page that in addition to this integration requiring a Tessie account, that there are no free Tessie accounts.  There's a short try for free, and beyond that it requires a paid subscription..

Whilst it becomes obvious part way through setup, really that'd be something worthwhile knowing before starting.

### URL

https://www.home-assistant.io/integrations/tessie/

### Version

2024.8.0

**Comment by Bre77** [comment]
Yeah we can probably do that. FYI Teslemetry is a cheaper alternative with more functionality, but if you do want a free integration `tesla_fleet` just got added in 2024.8 but its **much** more limited.
