### ISSUE TITLE
Tesla Fleet Integration - Commands

### ISSUE THREAD

**Issue by kj4qyf** [home-assistant/home-assistant.github.io#34182]
### Feedback

Thanks for this new Integration. Is it planned for the integration to be able to send commands to the car ?

### URL

https://www.home-assistant.io/integrations/tesla_fleet/

### Version

2024.8.0

**Comment by Bre77** [comment]
Yes, I expect most of the remaining platforms will be added for 2024.9, however there is a significant amount of engineering effort required to support command signing, so they will not work for all vehicles.

**Comment by Bre77** [comment]
@home-assistant close

**Comment by kj4qyf** [comment]
Thanks
