### ISSUE TITLE
Unable to setup Minut Point

### ISSUE THREAD

**Issue by andrewlaery** [home-assistant/home-assistant.github.io#34184]
### Feedback

Hi Team, I have followed the installation instructions word-by-word. Ive updated my Minut Account, then Added my Minut to the config file. I then get the option to 'Configure' my Minut in Home Assistant.

"Authenticate Point - Please follow the link below and Accept access to your Minut account, then come back and press Submit below."

Once I do this, I get an 'OK' response. But then when I click Submit, i get the response 'Please follow the link and authenticate before pressing Submit'.

Any idea's on how to resolve?

### URL

https://www.home-assistant.io/integrations/point/

### Version

2024.8.0

**Comment by fredrike** [comment]
This is all resolved in https://github.com/home-assistant/core/pull/118243 I will try to get it merged as soon as possible.

**Comment by fredrike** [comment]
@home-assistant rename Unable to setup authentication with Minut Point

**Comment by fredrike** [comment]
@home-assistant rename Unable to setup Minut Point

**Comment by fredrike** [comment]
@home-assistant close
