### ISSUE TITLE
% symbol not allowed as a valid character in a Reolink Camera device password.

### ISSUE THREAD

**Issue by leewilko** [home-assistant/home-assistant.github.io#34199]
### Feedback

Since the latest update to Home Assistant the Reolink integration is now asking me to re-authenticate to all my Reolink Cameras. I have tried to re-authenticate but am being prevented as my password for my cameras includes a valid % character within the password. This is a valid password character that can be used within the device password but it not allowed to be used within the integration when re-authenticating. Screenshot below showing the issue

<img width="789" alt="image" src="https://github.com/user-attachments/assets/08fbe847-9d49-48ca-a1b2-00eda51acf05">

I now cannot re-authenticate my Cameras due to this problem making the integration fail.

Please can this be investigated. 

Regards

Lee Wilkinson

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.8.0

### Additional information

<img width="789" alt="image" src="https://github.com/user-attachments/assets/8416b9c5-abed-4998-bad7-b36406191719">

**Comment by starkillerOG** [comment]
see my explanation here: https://github.com/home-assistant/core/issues/123302#issuecomment-2274337355
this is a duplicate issue so will close it now.

**Comment by starkillerOG** [comment]
Sorry for the inconveniance of having to make a new user/change the password.

**Comment by leewilko** [comment]
No problem, I understand and having read the duplicate issue this makes sense for the other streams and features to work correctly. Maybe Reolink should actually limit their ability to allow invalid characters in their device passwords. So appreciate the update and reasons behind it. I have created dedicated user account for homeassistant on each camera and re-authenticated all fine now. Thanks for the update and great work, appreciated.
