### ISSUE TITLE
says recorder database is in /config, isn't it in /homeassistant?

### ISSUE THREAD

**Issue by mikelward** [home-assistant/home-assistant.github.io#34203]
### Feedback

https://www.home-assistant.io/integrations/recorder says

> The database is stored in your Home Assistant configuration directory (’/config/’)

When I use File editor, it appears to be in /homeassistant/, not /config/.

### URL

https://www.home-assistant.io/integrations/recorder/

### Version

2024.8.0

**Comment by frenck** [comment]
The file edit other uses a different internal path. `/config` is the native and correct path.

../Frenck
