### ISSUE TITLE
Style not working in badges after updating to 2024.8

### ISSUE THREAD

**Issue by cvasantrao** [home-assistant/home-assistant.github.io#34205]
### Feedback

Earlier I was able to change the appearance of the badge using CSS. But after updating to 2024.8 it does not work. Any reason why this has been deprecated or is there another way of doing it?

### URL

https://www.home-assistant.io/dashboards/badges/

### Version

2024.8.0

**Comment by traveler2100** [comment]
Same problem here.  I have used custom badges to change color based on state of things like door locks, etc. for years.  I reverted back to 2024.7.4 due to this and Alexa issues.  I hope a fix to 2024.8 issues is down the road.
