### ISSUE TITLE
l'integrazione non funziona. 

### ISSUE THREAD

**Issue by Perrymason199** [home-assistant/home-assistant.github.io#34207]
### Feedback

l'integrazione non funziona.  Riporta questo errore:
errore:richiesta non valida
error_description:Il 'redirect_uri' specificato non è valido per questa applicazione client.
errore_uri:https://documentation.openiddict.com/errors/ID2043

### URL

https://www.home-assistant.io/integrations/iotty/

### Version

2024.8.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Ps. We use English as our language.

Thanks! 👍

./Klaas

**Comment by shapournemati-iotty** [comment]
Hi, I think this is the same as [this issue](https://github.com/home-assistant/core/issues/123398).

There was a misconfiguration of auth flow. Could you please try again now?
