### ISSUE TITLE
Home Assistant iOS failure to install

### ISSUE THREAD

**Issue by CWSites** [home-assistant/home-assistant.github.io#34215]
### Feedback

I get an unknown error with no additional information on how to fix it.

<img width="502" alt="Screenshot 2024-08-08 at 11 28 30 PM" src="https://github.com/user-attachments/assets/31bdd80e-ccb3-4e96-abe5-b98eecc52d22">
<img width="417" alt="Screenshot 2024-08-08 at 11 28 37 PM" src="https://github.com/user-attachments/assets/24ec1272-ec09-4061-acdb-235b3798844e">
<img width="412" alt="Screenshot 2024-08-08 at 11 28 43 PM" src="https://github.com/user-attachments/assets/fec541ea-dac4-4c33-b56f-01ae0d8b927a">

### URL

https://www.home-assistant.io/integrations/ios/

### Version

2024.8.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
