### ISSUE TITLE
impostare il condizionatore attraverso un sensore esterno alla macchina

### ISSUE THREAD

**Issue by coreduo94** [home-assistant/home-assistant.github.io#34210]
### Feedback

buongiorno 
secondo me sarebbe utile poter trattare tra gli esempi anche il fatto di poter controllare la temperatura del condizionatore attraverso un sensore installato in una stanza diversa dallo splitter. questo consetirebbe di controllare meglio la macchina quando si dispone di un solo splitter per piu stanze e la temperatura target non è mai precisa

### URL

https://www.home-assistant.io/integrations/climate/

### Version

2024.8.0

**Comment by frenck** [comment]
Hi there @coreduo94 👋 

I'm sorry to say, we don't speak that language you have been using. We are an English speaking community. If you have documentation feedback, please submit it in the English language.

Thanks! 👍 

../Frenck
