### ISSUE TITLE
Supported Devices

### ISSUE THREAD

**Issue by easyhoo** [home-assistant/home-assistant.github.io#34226]
### Feedback

Hi, I would like to ask weather we can help to add missing devices?
i.E. H7065 is supported, H7066 not (seems same hardware with 2 more spots).

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.8.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
