### ISSUE TITLE
Linkplay integration not working

### ISSUE THREAD

**Issue by greeferd** [home-assistant/home-assistant.github.io#34225]
### Feedback

I tried to add my Wiim Pro to home assistant with new linkpay integration. After typing the ip address of my device I get "Failed to connection" .

### URL

https://www.home-assistant.io/integrations/linkplay/

### Version

2024.8.0

**Comment by josephnfoley** [comment]
Same issue here. I was using a the hacs linkplay integration which I modified to better suit the Wiim however now this no longer works and the new native integration fails to connect.

I have removed the old integration folders from custom_components and i have removed the reference to it in my configuration yaml. I can now see the new integration in the add integration window in settings - integrations however when i select it and input the ip address for my Wiim Pro i receive the "Failed to Connect" error.

I believe I read somewhere that the Wiim Pro needs https to connect however I can no longer find that post and I can't find any solutions. Help Please.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
