### ISSUE TITLE
"Use wake word" option is missing

### ISSUE THREAD

**Issue by TobbeJ** [home-assistant/home-assistant.github.io#34227]
### Feedback

the firmware link have recently changed in pr: https://github.com/home-assistant/home-assistant.io/pull/34188
but the new firmware does not have the same functionality, namely the "User wake word" option is now missing so pictures in the article no longer matches.

I like to have the choice to turn off wake word and instead use button to trigger listening by the device.

### URL

https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/

### Version

2024.8.0

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @TobbeJ :+1:

**Comment by TobbeJ** [comment]
just so i understand, push to talk is not going to work any more?

**Comment by c0ffeeca7** [comment]
Not in this version. But I think the function will come back.
