### ISSUE TITLE
Template broken example

### ISSUE THREAD

**Issue by firtzba** [home-assistant/home-assistant.github.io#34242]
### Feedback

Hi,
i’ve tried to use your example for templates. I pasted it in and it gave me a "Translation error: MALFORMED_ARGUMENT" I followed the link given. On the site the error is not mentioned.
Please give a working example and a link that explains the error.

### URL

https://www.home-assistant.io/integrations/template/

### Version

2024.8.1

**Comment by frenck** [comment]
Hi there @firtzba 👋 

Could you be so kind to explain what example you pasted where? As in, providing us a reproduction scenario of your issue?

It is quite unclear from your report to what you did.

Thanks! 👍 

../Frenck
