### ISSUE TITLE
lack of response to bugs is worrying

### ISSUE THREAD

**Issue by djh42** [home-assistant/home-assistant.github.io#34240]
### Feedback

I asked about a problem in the forum. Several people said they had the same problem. Nobody appeared to 'own' the problem or offer any solutions. So I made a bug report. Your bots assigned it to somebody but that person has not responded at all. So what impression does that leave me with???

### URL

https://www.home-assistant.io/help/

### Version

2024.8.1

**Comment by frenck** [comment]
Hi there @djh42 👋 

> So what impression does that leave me with???

I think the impression you have with an open source project is incorrect maybe? As in, this feedback sounds like you have the expectations of a commercial product and support; however, Home Assistant is an open source project.

Open source projects rely on voluntary contributions from community developers. It is quite literally by and for the community. Feel free to jump into development if you would like to help out, fix issues, and develop new features.

This also means, that is you look for timely handling of fixes, features and require timely support; an open source project might not be the thing you are looking for.

../Frenck
