### ISSUE TITLE
Wrong home consumption

### ISSUE THREAD

**Issue by JHAvB** [home-assistant/home-assistant.github.io#34267]
### Feedback

The home's self-consumption seems to be incorrect. There appears to be an issue with the setup calculation. The consumption of the home should be 2.1 kWh.

![Afbeelding1](https://github.com/user-attachments/assets/27f4651b-7e4a-4782-a6c8-35a6eb8b8290)

### URL

https://www.home-assistant.io/docs/energy/battery/

### Version

2024.8.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas

**Comment by JHAvB** [comment]
Hello Klaas,
I wasn’t looking for support. The calculation of the energy flows within Home Assistant is incorrect. The energy drawn to the battery (2.5 kWh) is not being deducted from the home's usage. This is not an issue from my end; in short, it’s a issues.

**Comment by klaasnicolaas** [comment]
If it is an issue then you are still in the wrong repository, we use the issue tracker here for documentation feedback. 

This would rather be something for the frontend repository: https://github.com/home-assistant/frontend

./Klaas
