### ISSUE TITLE
duct air conditioning

### ISSUE THREAD

**Issue by adamszy** [home-assistant/home-assistant.github.io#34270]
### Feedback

I have two air conditioners. Up until now everything worked without a problem. After updating HA to version 2024.8.1 the integration does not see the status of the duct air conditioner. I still have the status disabled and does not read the temperature.

### URL

https://www.home-assistant.io/integrations/gree/

### Version

2024.8.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
