### ISSUE TITLE
Formatting values

### ISSUE THREAD

**Issue by Dieter-GitHub** [home-assistant/home-assistant.github.io#34278]
### Feedback

Would it be an idea to support value formatting right here? I know one can add a helper or someting else. Attached is my example for a solar grid for which I would prefer displaying MWh.
![image](https://github.com/user-attachments/assets/e2ccddf5-c4f2-4746-bf00-2a2239999a88)
By the way: really GREAT upgrade of the badge functionallity. Thanks

### URL

https://www.home-assistant.io/dashboards/badges/

### Version

2024.8.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
