### ISSUE TITLE
Govee Integration cant find my device

### ISSUE THREAD

**Issue by TNFlyboy2** [home-assistant/home-assistant.github.io#34286]
### Feedback

I recently installed Govee permanent outdoor lights H705A.  I turned on the option to manage by LAN.
Home Assistant still can find them when I try to set up the integration.
I do have my lights on a separate subnet, but the traffic should be passing back and forth between the HA network and my IoT network without any restrictions.

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.8.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
