### ISSUE TITLE
Withings Integrations Received invalid token data.

### ISSUE THREAD

**Issue by kali-777** [home-assistant/home-assistant.github.io#34285]
### Feedback

I followed all the steps, i run the app i selected my self as User then give my HA IP to Link Account then i got "Received invalid token data."

### URL

https://www.home-assistant.io/integrations/withings/

### Version

2024.8.1

**Comment by kali-777** [comment]
Invalid token: {'status': 503, 'error': 'Invalid Params: invalid code'}
Logger: homeassistant.helpers.config_entry_oauth2_flow
Source: helpers/config_entry_oauth2_flow.py:348
First occurred: 00:33:16 (2 occurrences)
Last logged: 00:34:07

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
