### ISSUE TITLE
Utility sensor has unit "W", but I want it to show "Wh" or "kWh"

### ISSUE THREAD

**Issue by balconissimo** [home-assistant/home-assistant.github.io#34291]
### Feedback

I just created a utility sensor that integrates a power sensor of my Tibber electricity counter.
Source entity is measured in W and tells how much energy is inserted right now into the grid.
The utility sensor creates a daily sum of how much energy I have "donated" into the grid, so it is a mathematical integral of the wattage.

The utility sensor is wrongly shown in Watts, but it should be shown in Wh or kWh.
There is no field for defining its unit... Can I change this? I couldn't find a yaml editor for this.

![HA-utilitysensor-unitselector](https://github.com/user-attachments/assets/5b97bb90-dbe5-4ff8-8d03-6ea1d91e2a38)

Besides of that wrong unit I am able to select this sensor in the energy dashboard setting, so it is treated as if it had the unit Wh.

I don't know if it is possible to change the unit, but it is at least undocumented. Then it's a documentation issue. If changing the unit is not possible, then it's a feature request. I hope I have posted this under the right tags in the right section...

### URL

https://www.home-assistant.io/integrations/utility_meter/

**Comment by frenck** [comment]
I think you are confused between Energy vs Power. You have a power sensor; but you said you want to measure energy...

You are probably looking for the Integral helper, you can find it here: <https://www.home-assistant.io/integrations/integration>

If you want to build an utility meter out of that, you can use that power sensor wrapped in an Integral helper to feed into the utility helper.

../Frenck
