### ISSUE TITLE
conversation: appears hardcoded now.

### ISSUE THREAD

**Issue by MoHf7f4** [home-assistant/home-assistant.github.io#34297]
### Feedback

Default_config: is removed, but conversation: seems enabled even if both are removed from the yaml.

### URL

https://www.home-assistant.io/integrations/default_config/

### Version

2024.8.1

**Comment by frenck** [comment]
I've checked the sources of Home Assistant to make sure: It isn't hardcoded.

Integration can, however, depend on each other. Some of the integrations in core that pull in the conversation integration in Core include the assist pipeline, Anthropic, OpenAI, Demo, mobile app, Ollama, and Wyoming integration. Third-party custom integration can of course also create dependencies.

../Frenck

**Comment by MoHf7f4** [comment]
Thanks, that helps me a lot.  I'll check my 3rd party integrations and see
what they are pulling in.
