### ISSUE TITLE
conversation:

### ISSUE THREAD

**Issue by MoHf7f4** [home-assistant/home-assistant.github.io#34298]
### Feedback

![conversation](https://github.com/user-attachments/assets/bb964c88-d1db-48df-9c3c-17389f20635d)
removing from config doesn't do anything.  It's in the default

### URL

https://www.home-assistant.io/integrations/conversation/

### Version

2024.8.1

**Comment by frenck** [comment]
Correct, not following your feedback in this case. Could you clarify?

../Frenck

**Comment by MoHf7f4** [comment]
Based on what you said in another reply, a 3rd party integration could be pulling in conversation: even if it's not in any of the config yaml.  I've got one HA instance I can't get rid of the conversation integration on.  I can't figure out what's loading it.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
