### ISSUE TITLE
Thanks, @dknowles2 👍

### ISSUE THREAD

**Issue by fippsy33** [home-assistant/home-assistant.github.io#34296]
Thanks, @dknowles2 👍 

../Frenck

_Originally posted by @frenck in https://github.com/home-assistant/home-assistant.io/pull/32823#pullrequestreview-2064718744_

**Comment by fippsy33** [comment]
Hello, can you give an example how I can set the Manuel watering time in HA?

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
