### ISSUE TITLE
Unable to connect with credentials

### ISSUE THREAD

**Issue by gilshahar7** [home-assistant/home-assistant.github.io#34300]
### Feedback

I am getting "Unexpected error" after entering my credentials. The email and password work fine on rym-pro.com

![3491ABB2-03B4-4A30-880F-3D936E6302B5](https://github.com/user-attachments/assets/29efd780-74b0-4338-b10b-fecbc945dee8)

### URL

https://www.home-assistant.io/integrations/rympro/

### Version

2024.8.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
