### ISSUE TITLE
No 'Show as'

### ISSUE THREAD

**Issue by kwagnitz** [home-assistant/home-assistant.github.io#34309]
### Feedback

There is no "Show as" entry for a temperature sensor.

### URL

https://www.home-assistant.io/docs/configuration/customizing-devices/

### Version

2024.8.1

### Additional information

As common with most "help" pages, there are no concrete YAML examples.
https://www.home-assistant.io/integrations/sensor/ talks about device classes.
"This can be modified in the [customize section](https://www.home-assistant.io/docs/configuration/customizing-devices/)."
That page doesn't even mention classes or indicate how or where to set them.

**Comment by frenck** [comment]
> There is no "Show as" entry for a temperature sensor.

That is correct, the options and capabilities offered depend on the properties of an entity.

../Frenck
