### ISSUE TITLE
unique_id sample

### ISSUE THREAD

**Issue by pavelkryl** [home-assistant/home-assistant.github.io#34308]
### Feedback

It's unclear whether the `unique_id` should include `sensor.` prefix or not. It would be helpful to have a `unique_id` specified in the sample provided.

### URL

https://www.home-assistant.io/integrations/filter/

### Version

2024.8.1

**Comment by frenck** [comment]
The unique ID is free-form and isn't part of anything else besides uniquely identifying the sensor in the internal registries.

../Frenck
