### ISSUE TITLE
Subject: API Endpoint Not Found - https://home-api.eufylife.com/v1/user/email/login

### ISSUE THREAD

**Issue by Zmyric** [home-assistant/home-assistant.github.io#34303]
### Feedback

Dear Home Assistant/Eufy Support Team,

I hope this message finds you well. I am writing to report an issue I've encountered while attempting to integrate my Eufy devices with Home Assistant.

Issue Summary:
While trying to obtain an access_token via the Eufy API at https://home-api.eufylife.com/v1/user/email/login, I encountered a 404 Not Found error. The specific error message displayed on the page was:

Not Found

The page you have requested has flown the coop.
Perhaps you are here because:

- The page has moved
- The page no longer exists
- You were looking for your puppy and got lost
- You like 404 pages

The page also mentioned it was powered by beego 1.7.1.

Steps to Reproduce:
Ran the following curl command to obtain the access_token:

curl -H "Content-Type: application/json" \
-d '{"client_id":"eufyhome-app", "client_Secret":"GQCpr9dSp3uQpsOMgJ4xQ", "email":"[my email]", "password":"[my password]"}' \
https://home-api.eufylife.com/v1/user/email/login
Instead of receiving the expected JSON response with the access_token, the API returned a 404 error, indicating that the requested page could not be found.
Impact:
This issue prevents me from obtaining the necessary access_token to integrate my Eufy devices with Home Assistant, disrupting the intended functionality and automation of these devices.

Request:
Could you please investigate this issue or provide guidance on an alternative method to obtain the access_token required for integration? If the endpoint has changed or there is a new process, an update in the documentation would be highly appreciated.

Thank you for your attention to this matter. I look forward to your prompt response.

### URL

https://www.home-assistant.io/integrations/eufy/

### Version

2024.8.1

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
