### ISSUE TITLE
Suddenly no access to the aussie device (uses airbase) 

### ISSUE THREAD

**Issue by coolnetworks** [home-assistant/home-assistant.github.io#34318]
### Feedback

I get "! Unexpected error" when trying to configure the device.

any access to the API is responding with ```ret=PARAM NG,msg=404 Not Found```

I assume the local api is now disabled?

### URL

https://www.home-assistant.io/integrations/daikin/

### Version

2024.8.1

**Comment by fredrike** [comment]
Terrible sorry but this have been the status for Daikin :

- 2024.8.0 broke it for people who had a controller that supported SSL but they were using SSL. This one also identified that headers were a requirement for those models
- 2024.8.1 fixed it for the above people, but broke it for the ones that were still working in 2024.8.0 (those that use http only, with no headers)
- 2024.8.2 should (fingers crossed and from current testing) have it working for all models again


Open a new issue if the problem persist after 2024.8.2.

**Comment by fredrike** [comment]
@home-assistant close
