### ISSUE TITLE
Google Domains have been discontinued by Google

### ISSUE THREAD

**Issue by jmwhite5** [home-assistant/home-assistant.github.io#34315]
### Feedback

Shouldn't this feature be removed from the code and documentation? 

### URL

https://www.home-assistant.io/integrations/google_domains/

### Version

2024.8.1

**Comment by frenck** [comment]
Hi there @jmwhite5 👋 

Thanks for the report. This specific integration is pending removal for the upcoming Home Assistant release.

../Frenck
