### ISSUE TITLE
Documentation lacking for media_dirs stanza

### ISSUE THREAD

**Issue by tfischer4765** [home-assistant/home-assistant.github.io#34316]
### Feedback

The section on how to use custom folders for media is incomplete. It does not have a list of properties that can be put below the `media_dirs` stanza, nor what effect they have. In various places I have found `local`, `video` and`recording`, but no explanation what effect they have.

### URL

https://www.home-assistant.io/more-info/local-media/setup-media/#using-custom-folders

### Version

2024.8.1

**Comment by frenck** [comment]
Thanks for the feedback, @tfischer4765 👍 

I've opened up a PR to add a little clarity there.

So the keys, are actually free to choose the way you see fit.

../Frenck
