### ISSUE TITLE
Getting started is impossible

### ISSUE THREAD

**Issue by matellis** [home-assistant/home-assistant.github.io#34338]
### Feedback

I wanted a TTS to Piper as the default voices sounded unnatural. I installed the Piper add-on, which prompted me to setup the Wyoming Protocol. Huh? So I check out the docs for Piper. The part of the Home Assistant repo for piper has a readme that simply says:
```
Home Assistant add-on that uses [piper](https://github.com/rhasspy/piper/) for text-to-speech.

Part of the [Year of Voice](https://www.home-assistant.io/blog/2022/12/20/year-of-voice/).
```
So you click on the link for Piper which takes you to the project where you can get the binary and includes a list of people who are using Pipe, including Home Assistant. When you click on that link it takes you back to the aforementioned README.

So you google "How to add piper to your home assistant" and find [this link](https://www.home-assistant.io/integrations/piper/) to Home Assistant's documentation on Piper. Promising. However this page states:
```
Support for devices by Piper in Home Assistant is provided by the [Wyoming Protocol](https://www.home-assistant.io/integrations/wyoming) integration.

Piper devices are either rebranded devices or devices that share a common communication protocol, making it possible to use them with the [Wyoming Protocol](https://www.home-assistant.io/integrations/wyoming) integration.
```
Below this is something I can press:
```
To add the Piper integration to your Home Assistant instance, use this My button: [BUTTON]

Piper can be auto-discovered by Home Assistant. If an instance was found, it will be shown as Discovered. You can then set it up right away.
```
Ok, so I press the button. This adds the Wyoming Protocol to my Home Assistant, and demands of me 'host' and 'port'  No idea what to put here. When I click on the help button it takes me to the [Home Assistant docs on the Wyoming protocol](https://www.home-assistant.io/integrations/wyoming). This starts with:
```
[The Wyoming integration](https://github.com/rhasspy/rhasspy3/blob/master/docs/wyoming.md) connects external voice services to Home Assistant using a [small protocol](https://github.com/rhasspy/rhasspy3/blob/master/docs/wyoming.md). This enables [Assist](https://www.home-assistant.io/voice_control/) to use a variety of local [speech-to-text](https://www.home-assistant.io/integrations/stt/), [text-to-speech](https://www.home-assistant.io/integrations/tts/), and [wake-word-detection](https://www.home-assistant.io/integrations/wake_word/) systems, such as:
```
Clicking on Piper takes me back, so I keep reading. Further down I see:
```
INSTALLING A LOCAL VOICE PIPELINE

The Wyoming, Piper, and Whisper add-ons are used to create a fully local voice pipeline. To learn how to do this, follow the procedure on [installing a local voice pipeline](https://www.home-assistant.io/voice_control/voice_remote_local_assistant/).
``` 
OK, so I click on *this* link which tells me I need to go into devices and press configure. Ah, now this works!

Can we just change the README to give new users a simple way to get Piper working as follows:

* Install Piper Add-on
* Go to Devices
* Press configure for Piper device discovered
* Done!

### URL

https://www.home-assistant.io/integrations/piper/

### Version

2024.8.2

**Comment by synesthesiam** [comment]
Documentation improvements are in progress.
