### ISSUE TITLE
Platform error 'light' from integration 'zengge' - Requirements for zengge not found: ['bluepy==1.3.0']

### ISSUE THREAD

**Issue by MNeubauer72** [home-assistant/home-assistant.github.io#34334]
### Feedback

Adding the configuration in the configuration.yaml file according to the https://www.home-assistant.io/integrations/zengge documentation, I get a warning when trying to run Home Assistant:
Platform error 'light' from integration 'zengge' - Requirements for zengge not found: ['bluepy==1.3.0'].
It seems that the component 'bluepy==1.3.0' is missing. How to install it?
Unfortunately, despite searching various groups where I have encountered the same problem I have not found a solution.

### URL

https://www.home-assistant.io/integrations/zengge/

### Version

2024.8.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by MNeubauer72** [comment]
Hi Klass,
ok, I'll report it there. Yet Zengge has been in Home Assistant for a long time, there is documentation that says nothing about the prerequisite requirements, which are currently not available in HA.

Best Regards,
Mariusz Neubauer
________________________________
Od: Klaas Schoute ***@***.***>
Wysłane: piątek, 16 sierpnia 2024 23:46
Do: home-assistant/home-assistant.io ***@***.***>
DW: MNeubauer72 ***@***.***>; Author ***@***.***>
Temat: Re: [home-assistant/home-assistant.io] Platform error 'light' from integration 'zengge' - Requirements for zengge not found: ['bluepy==1.3.0'] (Issue #34334)


Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
