### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Nick4-1** [home-assistant/home-assistant.github.io#34339]
### Feedback

The link in step 5:
"In Ubuntu, open a browser and open the current documentation page, so you can follow the steps.

    From there, download the image."
gives a 404, it still refers to 12.4 instead of v13

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2024.8.2

**Comment by AvishkaChavi** [comment]
I am encountering the same issue. Could you please help resolve it?

**Comment by Nick4-1** [comment]
> I am encountering the same issue. Could you please help resolve it?

There  you go: https://github.com/home-assistant/operating-system/releases/

**Comment by AvishkaChavi** [comment]
thank you 🙏🏻

**Comment by frenck** [comment]
This issue has been addressed. Thanks for the feedback on it @Nick4-1 👍 

../Frenck
