### ISSUE TITLE
Unable to Start / Stop EV Charging from the Integration

### ISSUE THREAD

**Issue by AlohaFlyer** [home-assistant/home-assistant.github.io#34359]
### Feedback

I need to be able to control the EV Charge contactor directly from the integration. I want to automate when charging is started and stopped with HA, based on my Solar Panel production. Please add this feature. Great work

### URL

https://www.home-assistant.io/integrations/tesla_wall_connector/

### Version

2024.8.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
