### ISSUE TITLE
Username/Email must be in lowercase

### ISSUE THREAD

**Issue by kernalbin** [home-assistant/home-assistant.github.io#34356]
### Feedback

Login fails unless the username is entered in all lowercase. On iOS entering an email with an initial capital letter is (annoyingly) the default.

Anyway, thinking a small note may help others avoid some confusion. Or it could just be fixed.

### URL

https://www.home-assistant.io/integrations/schlage/

### Version

2024.8.2

**Comment by frenck** [comment]
Thanks for the feedback @kernalbin 👍 

A quick search learned me that more people have struggled with this. I've opened up a code change in Home Assistant to let the integration just deal with it (so I'm avoiding documentation change in this case).

https://github.com/home-assistant/core/pull/128730

../Frenck
