### ISSUE TITLE
S1255 

### ISSUE THREAD

**Issue by rgr101** [home-assistant/home-assistant.github.io#34366]
### Feedback

Hi, 

I have a S1255 heatpump and the integration works very well! Great job, many thanks!!
So I assume you could add this model to the list (and maybe even more, as there are more new models like the S1256 etc..)

Cheers! Renato.

### URL

https://www.home-assistant.io/integrations/nibe_heatpump/

**Comment by frenck** [comment]
Thanks, @rgr101 👍 

I've opened up a pull request to add it to our documentation pages here: <https://github.com/home-assistant/home-assistant.io/pull/35288>

../Frenck
