### ISSUE TITLE
Noob setup seems wrong

### ISSUE THREAD

**Issue by eiger3970** [home-assistant/home-assistant.github.io#34377]
### Feedback

Hello, I followed https://www.home-assistant.io/integrations/fronius, however HA shows Energy distribution as solar and grid in at exactly the same amount, which seems wrong?
![Screenshot from 2024-08-20 17-39-23](https://github.com/user-attachments/assets/289833d1-7011-4b37-b9b3-8b8dd4593e8c)

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2024.8.2

**Comment by farmio** [comment]
Hi 👋! 
Please use the community forum or the discord server for support questions. The issue tracker here is meant for actual bugs / errors in documentation.

You probably did mix up some entity or have chosen the wrong meter path configuration. Check your entities values to see which would fit for the individual energy panel configs.

**Comment by eiger3970** [comment]
Sorry, I just saw the Feedback button and it took me there.
