### ISSUE TITLE
Reduce update frequency to seconds instead of 30 sec. 

### ISSUE THREAD

**Issue by AlexJacu** [home-assistant/home-assistant.github.io#34378]
### Feedback

It would be very help full if we could change the update frequency for the integration from thirty seconds to one, two or three seconds as the user need for realise control functions as control usage and photovoltaic export.
The api alows to update every second. 

### URL

https://www.home-assistant.io/integrations/discovergy/

### Version

2024.8.2

**Comment by AlexJacu** [comment]
in https://github.com/home-assistant/core/blob/dev/homeassistant/components/discovergy/coordinator.py

subject to change seconds=30 to seconds=1
  super().__init__(
            hass,
            _LOGGER,
            name=f"Discovergy meter {meter.meter_id}",
            update_interval=timedelta(seconds=30),

Best would be to allow User to decide the update Intervall.

**Comment by jpbede** [comment]
To update your entities on a custom pace, you can use the `homeassistant.update_entity service`, please checkout the [documentation](https://www.home-assistant.io/common-tasks/general/#defining-a-custom-polling-interval).

Please keep in mind, if you reduce the update interval you may be subject to rate limiting and thus a not working integration.

Besides that, we don't allow integrations to have a configurable update interval.
