### ISSUE TITLE
Shelley Dimmer 2 (Gen 1) is a single channel dimmer. However, its configuration in HA only allows on/off.

### ISSUE THREAD

**Issue by gaitskell** [home-assistant/home-assistant.github.io#34387]
### Feedback

The Shelley Dimmer 2 (Gen 1) is a single channel dimmer. However, its configuration in HA only allows on/off. Could you provide guidance on the page concerning what to do in a situation like this?

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2024.8.2

**Comment by bieniu** [comment]
Please show me a screenshot of the light entity's "More Info" window.
