### ISSUE TITLE
Problème après détection

### ISSUE THREAD

**Issue by HoYoHoYo82** [home-assistant/home-assistant.github.io#34380]
### Feedback

Bonjour,

Les thermostats et volets roulants d'Exaconnect sont bien détectés. Cependant, il semble qu'Exaconnect se mette en veille, ce qui empêche Home Assistant de détecter les appareils. Je suis obligé de lancer l'application Exaconnect pour que Home Assistant détecte à nouveau les appareils, mais après quelques minutes, ils ne sont plus détectés.

Par exemple, lors de l'installation de Home Assistant, Exaconnect n'est pas détecté, rendant impossible la synchronisation entre Home Assistant et Exaconnect. Cependant, dès que l'application Exaconnect est lancée, tout devient détectable sur Home Assistant.

J'ai quatre voisins qui utilisent également Exaconnect, et après avoir effectué les mêmes tests, ils rencontrent tous le même problème que moi.

Avez-vous une solution pour que l'Exaconnect reste toujours en fonction avec Home Assistant ?
Merci

### URL

https://www.home-assistant.io/integrations/hexaom/

### Version

2024.8.2

**Comment by c0ffeeca7** [comment]
Thank you for your feedback, @HoYoHoYo82. 
This is an English speaking community. Please provide the content in English.
