### ISSUE TITLE
Aliases and some devices do not work in voice assistant 

### ISSUE THREAD

**Issue by jatgm1** [home-assistant/home-assistant.github.io#34418]
### Feedback

Aliases and some devices just don't work in the assist. Aliases don't work at all actually 

### URL

https://www.home-assistant.io/voice_control/aliases/

### Version

2024.8.2

**Comment by frenck** [comment]
Hi there @jatgm1 👋 

It seems like you want to report an issue with Home Assistant itself, however, you have submitted documentation feedback instead. Please report issues with Home Assistant here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
