### ISSUE TITLE
Monzo INtegration into HAOS - Authentication keeps expiring rapidly

### ISSUE THREAD

**Issue by Mithias-uk** [home-assistant/home-assistant.github.io#34416]
### Feedback

I keep getting the mesage "Authentication Expired for Monzo" in HAOS. Its only been recent this and happens mostly daily. I've re-installed the intragtion and de-done the authneitcation which resolve the issue temporarily. I've also just left it alone and the authentication DOES come back - but breaks again shoirtly after that.

### URL

https://www.home-assistant.io/integrations/monzo/

### Version

2024.8.2

### Additional information

Running latest HAOS publicly available and latest integration version

**Comment by JakeMartin-ICL** [comment]
Next time it occurs, could you please check your Monzo mobile app as soon as possible to see if there's another access approval there? I'm wondering if it sometimes requires reapproval for HA to refresh its token. If so, I'll need to figure out how long the app gives you to approve and how best to convey this. Thanks!

**Comment by Mithias-uk** [comment]
The only time the approval comes on my mobile is is if I request re-auth and thats almost instant - theres not been a random one appearing (which I think is what you mean?)
________________________________

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
