### ISSUE TITLE
Device_tracker "tracker_interfaces" option example

### ISSUE THREAD

**Issue by gijs007** [home-assistant/home-assistant.github.io#34417]
### Feedback

The OPNsense device_tracker has an optional feature to only track devices on specific interfaces. The option "tracker_interfaces".
However it does not explain how these can be configured / what valid values are, or provide guidance on where these values can be found in OPNsense.

After some testing, I found that only the interface description worked. 
Using the interface "Identifier" or "Device Name" from OPNsense did not work, oddly enough.

I now set the interface description, although this works fine, it is a user adjustable description. Which means it may accidentally be edited in OPNsense, breaking the integration.

e.g. of a valid config, which can be extended with more listed items:
```yaml
tracker_interfaces: 
  - "Home_WiFi"
```

### URL

https://www.home-assistant.io/integrations/opnsense/

### Version

2024.8.2

**Comment by fermulator** [comment]
This needs to be re-opened. @mtreinish
