### ISSUE TITLE
Need details on getting Tyua IoT Access Secret

### ISSUE THREAD

**Issue by mathan416** [home-assistant/home-assistant.github.io#34425]
### Feedback

The instruction pages tell us how to get the User Code but doesn't tell us how to get the Tuya IoT Access Secret, and it's not clear.  Also it would be good to get details for companies that use Tuya tech such as Globe Suite.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.8.2

**Comment by klaasnicolaas** [comment]
Could it be that you are using a custom Tuya integration via HACS?

./Klaas

**Comment by mathan416** [comment]
Not that I'm aware of  When I go to the UI > Integrations > + Add Integration, I enter Tuya to search and this is what I get:
![tempImagefpJ4vx](https://github.com/user-attachments/assets/8be4339d-ac3e-44b4-b609-fce0bf6ea116)

Clicking the question mark, I get this page link:
https://www.home-assistant.io/integrations/tuya

**Comment by mathan416** [comment]
This page here seems to give the proper details if you have Tuya devices setup - https://developer.tuya.com/en/docs/iot/Home-assistant-tuya-intergration?id=Kb0eqjig0utdd

Nothing about Globe, which leverages Tuya's platform, but it's a start.

**Comment by klaasnicolaas** [comment]
The page you are referring to is outdated, please check if you do not have a `tuya` folder in your `custom_integrations` folder. Or running an outdated version of Home Assistant. 

./Klaas

**Comment by mathan416** [comment]
Confirming I needed to upgrade HA.  Thanks!!
