### ISSUE TITLE
Button card no tile color

### ISSUE THREAD

**Issue by Stephan-4711** [home-assistant/home-assistant.github.io#34430]
### Feedback

Why there is no option to Change to icon color in the button card
?

### URL

https://www.home-assistant.io/dashboards/button/

### Version

2024.8.2

**Comment by frenck** [comment]
Hi there @Stephan-4711 👋 

Thank you for reaching out. Good question... I think? It sounds to me like you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

../Frenck
