### ISSUE TITLE
Access blocked when setting up Google Nest

### ISSUE THREAD

**Issue by mathan416** [home-assistant/home-assistant.github.io#34434]
### Feedback

I'm getting the following error when setting up Google integration with my Home Assistant, implying the integration hasn't completed the verification process.  

Is there a way of signing up for access, or is it possible I've done something wrong in my steps setting this up on the Google side?

![tempImage3GJSft](https://github.com/user-attachments/assets/5917c5e8-0f63-4cec-a6d3-69f34d5863d8)

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.8.2

**Comment by allenporter** [comment]
Hello,
I believe this means you filled out extra data in the `App Information` as mentioned in the [instructions](https://www.home-assistant.io/integrations/nest/) under the section "Configure OAuth Consent screen". The docs say *Omit unnecessary information (e.g. logo) to avoid additional review by Google* which I think may be happening here

**Comment by mathan416** [comment]
I figure it out - I had it in testing mode rather than production.  Once I fixed that I got it all connected (literally 2 minutes ago).

Thanks!
-Iain

**Comment by allenporter** [comment]
Great! 👍
