### ISSUE TITLE
Govee Integration not finding multiple local Wi-Fi connected  lights

### ISSUE THREAD

**Issue by telstir** [home-assistant/home-assistant.github.io#34464]
### Feedback

Govee Integration reports that it doesn't not find any lightrs. I have multiple lGovee lights connected to my the same Wi-Fi as my ISG. 

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.8.3

**Comment by telstir** [comment]
Oh btw - I have tried adding finding the Govee lights both when turned on & turned off but same result.

**Comment by tomofdarkness** [comment]
I just got a set of H7021 hanging string lights and they are not discovered by the integration, even after moving their IP to the same /24 as Home Assistant.  They're discovered by the iOS app just fine, the LAN Control switch is On in the app, but they're not found by HA and the lack of any way to manually specify the IP/etc is frustrating.

Logger: homeassistant.components.govee_light_local.config_flow
Source: components/govee_light_local/config_flow.py:46
integration: Govee lights local (documentation, issues)
First occurred: 8:53:07 AM (7 occurrences)
Last logged: 9:07:29 AM

Start failed, errno: 98

**Comment by PanicIsReal** [comment]
I too am having issues detecting my H6176, RBGIC Outdoor LED Light Strip. Same as Tomofdarkness, everything checked off, but just not detected when the integration is ran. Local Lan turned on.

For now I will continue to use the Govee MQTT integration.

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
