### ISSUE TITLE
Possible to add "first raindrop detection functionality" GW2000 and WS90

### ISSUE THREAD

**Issue by Naraic88** [home-assistant/home-assistant.github.io#34463]
### Feedback

Hi, 
dokumentation here: https://meshka.eu/Ecowitt/dokuwiki/doku.php?id=start#b_console_-_sensor_-_maximum_number_and_display_tables
says that they have added support for first raindrop feature "start of rainfall detection

with an upcoming firmware upgrade (August 2024) a “first raindrop detection functionality” will be introduced."
see attached image from forum.

Could this please be added to the integration so one can get a trigger for when it starts to rain from the sensor. 
thanks

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2024.8.3

### Additional information

![image](https://github.com/user-attachments/assets/c9464390-f88e-4d93-b565-5507a986e09f)

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
