### ISSUE TITLE
Cancelation info

### ISSUE THREAD

**Issue by Thapingu** [home-assistant/home-assistant.github.io#34470]
### Feedback

If possible it would be great to get information if a train is canceled! Currently it seems like the next train info just skips these records, and show next available? Would be great to see if first-next train is canceled, then next that actually arrives. OR separate canceled on serter stop sensor. Often this indicates if there is problems in general.

Since vy, entur, ruter do not  provide push service on cancelations in their app, we could easily implement this in HA to mobile clients if we had this information. (Workaround atm: Currently I've hardcoded depature times (+5min) and check given times if it's listed in api, if not I create push notification to clients to check for possible cancelation)

### URL

https://www.home-assistant.io/integrations/entur_public_transport/

### Version

2024.8.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
