### ISSUE TITLE
Troubleshooting missing entities

### ISSUE THREAD

**Issue by Fabian201584** [home-assistant/home-assistant.github.io#34473]
### Feedback

Hi guys,

I wanted to integrate my Enphase solar system into the Default Energy Dashboard of Home Assistant. The problem is that I can't see some sensors (e.g. friendly_name: Envoy current net power consumption) in the selection drop-down. My research has shown that it could be because the integration did not request the correct "States" under "Developer Tools".

The reference (https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities) says the following:

Requested:
"device_class" = "energy"
"state_class" = "total" or "total_increasing" (I think "total_increasing" should be fine)

But the actual setting is the following:
"device_class" = "power"
"state_class" = "measurement"

Can you please change that? I would like to use the dashboard and fully integrate Enphase into Home Assistant.

Regard Fabian

### URL

https://www.home-assistant.io/integrations/enphase_envoy/

### Version

2024.8.3

**Comment by catsmanac** [comment]
Hi @Fabian201584, `current net power consumption` is a power entity, not an energy entity and you can't use it with the energy dashboard. For the Energy dashboard you need to use the `Lifetime net energy consumption` and `Lifetime net energy production`  entities which are setup as:

"device_class" = "energy"
"state_class" = "total_increasing"

Also see: https://www.home-assistant.io/integrations/enphase_envoy/#energy-dashboard

If you can't find these then please share the diagnostic file here

![afbeelding](https://github.com/user-attachments/assets/68ea1638-4b6a-4fb7-b06c-dc465cb2f9da)
