### ISSUE TITLE
Support for Powerwall 3

### ISSUE THREAD

**Issue by ndehling** [home-assistant/home-assistant.github.io#34485]
### Feedback

Hi guys !
First of all, let me thank you for the great work you are doing for the HA community ! I am immensely grateful of all the free work you are doing ! As the new owner of a Powerwall 3, i was excited to try the integration. It seems like the integration is not yet working with Powerwall 3. I was wondering if you were planning on adapting the current integration for Powerwall 3 or if this was not in the plans. Thanks again for all your work !
Nic

### URL

https://www.home-assistant.io/integrations/powerwall/

### Version

2024.8.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
