### ISSUE TITLE
In all ver HA after 2024.7.0 don't working tuya cover (curtains) and thermostats (head) from MQTT (Z2M) 

### ISSUE THREAD

**Issue by diemon24** [home-assistant/home-assistant.github.io#34492]
### Feedback

After updated Core 2024.7.0 and  2024.8.3 my covers and thermostats don't working. In MQTT this devices unavailable. But it's working in Z2M and if downgrade HA ver to 2024.5.5. 
I deleted this device from MQTT integration, renamed in Z2M i see don't working device in ver after 2024.7.0. 
I don't think what this problem with MQTT integration or Z2M, this problem I see only after update HA ver. 

My other 100 devices working in all ver HA. Problem only this 2 type devices. 

Zigbee2MQTT [1.39.1]
zStack3x0

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/a3dce2ba-db25-4154-8678-06ae080f647a">
<img width="935" alt="image" src="https://github.com/user-attachments/assets/cb4e3db0-e6e9-41d3-8c42-bc555d2ad812">

### URL

home-assistant / home-assistant.io

### Version

all ver after 2024.7.0

### Additional information

this device in HA 2024.8.3 
![IMG_7819](https://github.com/user-attachments/assets/84edf35f-019b-4889-8cf5-87faf1fb451f)

![IMG_7820](https://github.com/user-attachments/assets/7757e052-e196-4610-aa59-99e6be4a4c4e)

this device in HA 2024.5.5

<img width="583" alt="image" src="https://github.com/user-attachments/assets/a7a8e726-401e-401d-a266-e6473bf45df2">

<img width="576" alt="image" src="https://github.com/user-attachments/assets/b36f7179-dd8e-4ba7-a58b-32aca3db73ae">
<img width="582" alt="image" src="https://github.com/user-attachments/assets/87de1dab-0c66-4d06-b58c-50768d729a90">
<img width="590" alt="image" src="https://github.com/user-attachments/assets/86a0740f-2cb8-46f3-a503-4e14b8281843">

its working
<img width="775" alt="image" src="https://github.com/user-attachments/assets/8d649643-20bf-4f99-8424-42c5e081e288">

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by diemon24** [comment]
> Hi there 👋
> 
> It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:
> 
> https://github.com/home-assistant/core/issues
> 
> Thanks! 👍
> 
> ./Klaas

sorry, thx
