### ISSUE TITLE
Openweathermap modes not documented completely

### ISSUE THREAD

**Issue by N3rdix** [home-assistant/home-assistant.github.io#34498]
### Feedback

Since a few releases we can choose 4 options in the config flow for OWM, but those are not documented. It's not clear what the modes `forecast` & `current` are doing, especially current seems to do the same as 3.0 (at least what I can see as a user).

Could those 2 modes be explained? I am happy to fill a PR to enhance the docs once it's clear...

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2024.8.3

**Comment by freekode** [comment]
this is docs for other two modes
https://openweathermap.org/forecast5
https://openweathermap.org/current

**Comment by N3rdix** [comment]
> this is docs for other two modes https://openweathermap.org/forecast5 https://openweathermap.org/current

thanks for the hint, I've created a PR for the docs and the config-flow to align them...
