### ISSUE TITLE
Which Matter version?

### ISSUE THREAD

**Issue by kraaidelft** [home-assistant/home-assistant.github.io#34491]
### Feedback

It doesn't tell which version of Matter is implemented. Is it the most recent 1.3 ?

### URL

https://www.home-assistant.io/integrations/matter/

### Version

2024.8.3

**Comment by marcelveldt** [comment]
Home Assistant is always based on the most recent version of Matter. Within 1 month after a new specification is released we update our base implementation.

However, this does not mean we have full coverage for all clusters within the latest spec. That is often added on a per-device base, as soon as we can get our hands on a testdevice or a state dump.

At time of writing I'd say we cover about 75% of all Matter 1.3 clusters
