### ISSUE TITLE
LED BLE dont Connect 

### ISSUE THREAD

**Issue by schitzo92** [home-assistant/home-assistant.github.io#34495]
### Feedback

![IMG_9353](https://github.com/user-attachments/assets/624da5e6-a570-430f-b485-85d6d8a9330d)

cant Connect with BLE led 
I think i Must use LEDBLE Led Lamp 
But i cant use it becouse HA automatic find BLE led device and Connection faile 

### URL

https://www.home-assistant.io/integrations/led_ble/

### Version

2024.8.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
