### ISSUE TITLE
Doesn’t work

### ISSUE THREAD

**Issue by nutsofamily** [home-assistant/home-assistant.github.io#34516]
### Feedback

States to get current version Hassio which I do. I cannot add it nor does it show up

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2024.8.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
