### ISSUE TITLE
Does command accept templates?

### ISSUE THREAD

**Issue by akloeckner** [home-assistant/home-assistant.github.io#34517]
### Feedback

The parameter descriptions say `string`, but below it says that `command` accepts templates. I don't know (yet) which is true. It would help, if the docs were consistent.

### URL

https://www.home-assistant.io/integrations/command_line/

### Version

2024.8.3

**Comment by gjohansson-ST** [comment]
You need to be a bit more specific. Which part are you referring to as I seem to not be able to find your reference.

**Comment by akloeckner** [comment]
Sorry. Specifically, I was trying to send a command line notification passing the title. And for notify, the configuration table says "command string Required". But later in the text, it reads "Usage of templating in command:
[Templates](https://www.home-assistant.io/docs/configuration/templating/) are supported in the command configuration variable". 

I now dug through the sources to learn, templates are not supported by the notify component. So, the table is correct. The later reference might just want to hint on the feature being available for sensors (and possibly other platforms?) only. That was not clear to me when just reading the docs.

**Comment by gjohansson-ST** [comment]
While I do think it can make sense to make the notify part also to allow a template as the command it's not currently.
I'll take a look at the reference you mention and try to clarify it.
