### ISSUE TITLE
AccuWeather integration precipitation value, precipitation past 6 hours and different language

### ISSUE THREAD

**Issue by jmfargas** [home-assistant/home-assistant.github.io#34513]
### Feedback

It would be nice to have the precipitation value in the weather info. Right now there is the precipitation unit, but not the value. It might be useful to include has_precipitation boolean to check, if true, the precipitation value, type and unit. AccuWeather does not provide the value if there is no precipitation.
It might be also very useful, for garden watering systems, to provide the precipitation past 6 hours value.
Finally, it would be nice to provide the texts in different languages.
Many thanks.

### URL

https://www.home-assistant.io/integrations/accuweather/

### Version

2024.8.3

**Comment by bieniu** [comment]
This is a documentation repository and is not the right place to open feature requests for integration.

You should open a feature request here https://community.home-assistant.io/c/feature-requests/13

Thanks
