### ISSUE TITLE
I seen Devolo integration HIJACKING non-devolo integrations. How do i disable the Devolo integration?

### ISSUE THREAD

**Issue by prmfeddema** [home-assistant/home-assistant.github.io#34523]
### Feedback

I see the devolo integration hijacking 1 tasmota device + Home energy device - both have nothig to do with Devolo.

How can i remove items from Devolo/disable the devolo integration altogether?

### URL

https://www.home-assistant.io/integrations/devolo_home_network/

### Version

2024.8.3

**Comment by prmfeddema** [comment]
I have a number of devices that are hijacked by the Devolo integration - how can i remove these from the devolo integration or disable devolo altogether?

**Comment by Shutgun** [comment]
Let's concentrate discussion in one issue: https://github.com/home-assistant/core/issues/123437

**Comment by Shutgun** [comment]
@home-assistant close
