### ISSUE TITLE
Trying to figure out what this bluetooth integration can do..

### ISSUE THREAD

**Issue by 172pilot** [home-assistant/home-assistant.github.io#34526]
### Feedback

From the docs, it says how to configure it, but it doesn't explain what it does, or how I might use it.  I am wondering if I can pair a BT speaker and use it as a HA audio output, or if it is for monitoring BT devices being nearby for presence?  

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2024.8.3

**Comment by bugensui2022** [comment]
I also want to know, I have a Bluetooth speaker,
