### ISSUE TITLE
Outdated documentation???

### ISSUE THREAD

**Issue by Umpie** [home-assistant/home-assistant.github.io#34538]
### Feedback

The documentation for Scrape integration seems very outdated to me. Nothing matches the Interface for the installing.

### URL

https://www.home-assistant.io/integrations/scrape/

### Version

2024.8.3

### Additional information

The documentation seem to assume you use configuration.yaml to use scrape. While the interface seems to focus on GUI. Not sure what to do next.

**Comment by gjohansson-ST** [comment]
It's not outdated but the configuration fields and all examples refer to when using the YAML setup rather than configuring via GUI.

So I'm not sure if this is a matter of you thinking the GUI setup is not easy enough without supporting documentation or if the documentation needs a better segmentation e.g. Configuration vs. YAML configuration?

**Comment by kixtarter** [comment]
> It's not outdated but the configuration fields and all examples refer to when using the YAML setup rather than configuring via GUI.

I think that at least one example is outdated: the one that should give the current [Release version of Home Assistant](https://www.home-assistant.io/integrations/scrape/#home-assistant).
This Scrape example points to the Home Assistant home page, but this page has been revised completely months ago, breaking this example.

**Comment by gjohansson-ST** [comment]
> I think that at least one example is outdated: the one that should give the current [Release version of Home Assistant](https://www.home-assistant.io/integrations/scrape/#home-assistant). This Scrape example points to the Home Assistant home page, but this page has been revised completely months ago, breaking this example.

A PR was opened and merged so I'm now closing this
