### ISSUE TITLE
GeoSphere API Changes

### ISSUE THREAD

**Issue by max-at** [home-assistant/home-assistant.github.io#34549]
### Feedback

GeoSphere has stopped data updates to the API klima-v1 - now klima-v2 should be used :-)

https://dataset.api.hub.geosphere.at/v1/docs/changelog.html#changelog-2024-09-02

### URL

https://www.home-assistant.io/integrations/zamg/

### Version

2024.8.3

**Comment by bzelch** [comment]
duplicate: https://github.com/home-assistant/core/issues/125137
