### ISSUE TITLE
@home-assistant add-label needs-more-information set mikrotik bad help

### ISSUE THREAD

**Issue by praca2021** [home-assistant/home-assistant.github.io#34545]
### Feedback

po použití tohto cmd
/user group add name=homeassistant policy=read,api,test,!local,!telnet,!ssh,!ftp,!reboot,!write,!policy,!winbox,!password,!web,!sniff,!sensitive ,!romon,!kámo,!tikapp

"input does not match any value of policy"

URL

https://www.home-assistant.io/integrations/mikrotik/
Verzia

2024.8.3
Ďalšie informácie

Žiadna odozva 

### URL

https://www.home-assistant.io/integrations/mikrotik/

### Version

2024.8.3

**Comment by praca2021** [comment]
163 / 5 000
you have a mistake there and you are writing nonsense to me
please reply or fix your code
you will help a lot of people
don't get in the way
your code doesn't work
check
please
help a lot of people

**Comment by praca2021** [comment]
you have no possibility to correct your mistakes
if I comment on your reaction, you automatically close it
are you ok

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by praca2021** [comment]
> Ahoj @engrbm87, nezabudnite sa pozrieť na túto spätnú väzbu, pretože bola označená integráciou ( `mikrotik`) ste uvedený ako [ vlastník kódu ](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L508) pre? Ďakujem!
> Príkazy vlastníka kódu

I don't understand what you write

**Comment by praca2021** [comment]
> > Ahoj  @engrbm87, nezabudnite sa pozrieť na túto spätnú väzbu, pretože bola označená integráciou (  `mikrotik`) ste uvedený ako  [ vlastník kódu  ](https://github.com/home-assistant/home-assistant.io/blob/current/CODEOWNERS#L508) pre? Ďakujem! 
> > Príkazy vlastníka kódu
> 
> nerozumiem co pises

this is the problem documentation
https://www.home-assistant.io/integrations/mikrotik/

**Comment by praca2021** [comment]
I already figured it out
you cannot use commands with "!"
correct the instruction in the helpdesk
from
/user group add name=homeassistant policy=read,api,test,!local,!telnet,!ssh,!ftp,!reboot,!write,!policy,!winbox,!password,!web,!sniff,!sensitive ,!romon,!kámo,!tikapp
on
/user group add name=homeassistant policy=read,api,test

**Comment by praca2021** [comment]
auto_awesome
Mali ste na mysli: stale ste to opravili, citajte pozorne, to je u vas chyba v dokumentacii https://www.home-assistant.io/integrations/mikrotik/
128 / 5 000
you still haven't fixed it, read carefully, that's a mistake in your documentation
https://www.home-assistant.io/integrations/mikrotik/

**Comment by praca2021** [comment]
why did you close it when it is not fixed?
why do you keep writing nonsense?
you have a mistake there, correct it and don't write that it belongs to
mikrotik, it's in your documentation
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
*auto_awesome*
You meant: you still fixed it, read carefully, that's a mistake in your documentation
https://www.home-assistant.io/integrations/mikrotik/
128 / 5 000
you still haven't fixed it, read carefully, that's a mistake in your
documentation https://www.home-assistant.io/integrations/mikrotik/

ut 3. 9. 2024 o 20:32 Klaas Schoute ***@***.***> napísal(a):
