### ISSUE TITLE
No scan_interval configuration variable?

### ISSUE THREAD

**Issue by Kagey-cmd** [home-assistant/home-assistant.github.io#34556]
### Feedback

Is scan_interval an available configuration variable? If so, it doesn't appear in the documentation.

### URL

https://www.home-assistant.io/integrations/sensor.rest/

### Version

2024.8.3

**Comment by chrisgilldc** [comment]
Was coming to post this!
It's not in the list of supported variables and the integration will refused to load if you include it.
HOWEVER.
One of the examples uses it.
I suspect it was supported at one point but isn't any longer.

**Comment by frenck** [comment]
Hi there @Kagey-cmd & @chrisgilldc 👋 

This is correct. This is not an integration option, but an option from the entity integration platform. You can find them here:

<https://www.home-assistant.io/docs/configuration/platform_options/>

../Frenck
