### ISSUE TITLE
FAQ on how to set POE schedule?

### ISSUE THREAD

**Issue by taxi01** [home-assistant/home-assistant.github.io#34558]
### Feedback

I set up HA and Unifi integration because i wanted to be able to power off POE port from 8pm to 8am. I can power cycle via HA, Unifi port, but i do not know how to set a schedule. are you able to add how to do that? Thanks heaps!

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.8.3

**Comment by Kane610** [comment]
You need to enable the PoE switch entities you want to control. As most automations are done in the GUI now and its a simple time schedule you want to setup its not something fitting with the integration documentation.

**Comment by taxi01** [comment]
Hi Rob, POE switch entities are enabled.
In Automation > I can add action to Press switch-name Power cycle button and confirmed that works.
But that only restarts POE. I would like to turn off poe (e.g. on switch, port 8) during non-business hours.
Is that possible?

________________________________

**Comment by Kane610** [comment]
If you can only restart poe then its the button entity cycle poe you have enabled. Not the poe switch entity

**Comment by taxi01** [comment]
My goodness... There's a switch.sw_es08_cc2_port_8_poe and a sensor.sw_es08_cc2_port_8_poe

Thanks! And apologies. I've taken a lot of your time with my silliness. Thanks again.

Kind regards.
________________________________

**Comment by Kane610** [comment]
No worries, happy you figured it out!
