### ISSUE TITLE
Support for Axis Companion cameras

### ISSUE THREAD

**Issue by electrocamuk** [home-assistant/home-assistant.github.io#34588]
### Feedback

I've a bunch of Companion cameras, and you can get RTSP streams out of them in almost the same way, but for some reason you need an extra URL parameter, "Axis-Orig-Sw=true".  Quite annoying and unsure why Axis did this,  URL Tested working with VLC.
Example:-
Debug logs shows HA is requesting:-
rtsp://****:****@192.168.10.80/axis-media/media.amp?videocodec=h264&streamprofile=ha&camera=1
I need HA to request:-
rtsp://****:****@192.168.10.80/axis-media/media.amp?videocodec=h264&streamprofile=ha&camera=1&Axis-Orig-Sw=true
Perhaps we could have a tick-box for "Axis Companion camera support" that would append that parameter onto the RTSP request URL.  Many thanks!

### URL

https://www.home-assistant.io/integrations/axis/

### Version

2024.9.0

**Comment by electrocamuk** [comment]
Issue still relevant.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
