### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by avviano** [home-assistant/home-assistant.github.io#34590]
### Feedback

Wow, this is probably the most complicated "Reset Password" help page on the entire internet and I have seen a lot. Homeassistant is the official winner of the worst "reset password" link I have ever come across. Terrible.   

### URL

https://www.home-assistant.io/docs/locked_out/

### Version

2024.9.0

**Comment by klaasnicolaas** [comment]
Providing well-founded feedback about what you are missing or what should be done differently will help us and the community more than what you currently provide as feedback. 

You can also make adjustments yourself and offer them via a pull request 😉 

./Klaas
