### ISSUE TITLE
4ever49radio 

### ISSUE THREAD

**Issue by Airmaxx014** [home-assistant/home-assistant.github.io#34598]
### Feedback

Can you please add 4Ever49radio to the list.

### URL

https://www.home-assistant.io/integrations/radio_browser/

### Version

2024.9.0

### Additional information

https://4ever49radio.nl/

**Comment by klaasnicolaas** [comment]
You are in the wrong place for that.

The integration only fetches radio stations, if you want a station to be added you have to do this at [Radio Browser](https://www.radio-browser.info/add) itself.

./Klaas

**Comment by Airmaxx014** [comment]
Thanks for the reply. and correct link.
