### ISSUE TITLE
Yale Account Not Working

### ISSUE THREAD

**Issue by devedsmith** [home-assistant/home-assistant.github.io#34605]
### Feedback

My verified Yale Account is not recognized in this new integration. I keep getting the error "Invalid password or email"

### URL

https://oauth.aaecosystem.com/login?next_url=%2Fauthorization%3Fclient_id%3Db3cd3f0b-fb97-4d6c-bee9-af7ab04758c7%26response_type%3Dcode%26state%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlIjoieWFsZSIsImlkIjoiZDk3NmNmN2ItYTAyMy00ZTQ5LWE3NmUtZWY1NjlkZGM1MWE1IiwiaWF0IjoxNzI1NTkwOTkzfQ.heHfSEmY0ODP7V-ZHyyED0cxT_tEv1vXlpxOdR4-yVQ%26redirect_uri%3Dhttps%253A%252F%252Faccount-link.nabucasa.com%252Fauthorize_callback

### Version

2024.9.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by devedsmith** [comment]
Oh jeez... thank you! And I see the issue is already listed by someone else. Thank you for your kindness.
