### ISSUE TITLE
Old API keys

### ISSUE THREAD

**Issue by bed428** [home-assistant/home-assistant.github.io#34600]
### Feedback

I had this setup > 1 year ago and it broke - it took me forever to figure out that an old api key was preventing everything. If you don't remove it - the guided setup skips the first step. 

Could we add a step such as the Spotify documentation has?

`If Spotify was previously integrated with your Home Assistant with outdated credentials, it might be required to remove these old Spotify account credentials using the [Home Assistant Application Credentials dashboard](https://my.home-assistant.io/redirect/application_credentials).`

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.9.0

### Additional information

Reference: https://www.home-assistant.io/integrations/spotify

**Comment by allenporter** [comment]
It says right now *See [Troubleshooting](https://www.home-assistant.io/integrations/nest/#troubleshooting) below for steps to resolve the common misconfigurations that result in errors such as Can’t link… or Error 400 from Google.*
 and the troubleshooting section has "Resolving mismatched OAuth Client ID" with instructions on how to do this. (It's not just as simple as removing from home assistant as you also have to ensure it is correct in the device access console too).


Agree it could be helpful to either clarify the wording so you are welcome to propose an update by clicking the "Edit" button to provide a suggestion!
