### ISSUE TITLE
Installing software on headless pi

### ISSUE THREAD

**Issue by 82Jetta** [home-assistant/home-assistant.github.io#34606]
### Feedback

If using a headless raspberry pi is there a way to install it directly?

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.9.0

### Additional information

098664

**Comment by frenck** [comment]
Hi there @82Jetta 👋 

Yes, the installation instructions linked on the page you left this comment on, is about installing Home Assistant on a headless Raspberry Pi.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

../Frenck
