### ISSUE TITLE
Instructions no longer current for HA 2024.9.1

### ISSUE THREAD

**Issue by fvoicu** [home-assistant/home-assistant.github.io#34627]
### Feedback

This page is no longer accurate for the current version of HA/Discord (2024.9.1)

### URL

https://www.home-assistant.io/integrations/discord/

### Version

2024.9.1

**Comment by tkdrob** [comment]
Provide some details in your post about what is no longer accurate and what you would like to see in the instructions. Not doing so means there is nothing to be fixed.
