### ISSUE TITLE
How do I find my hostname to add Nettigo air monitor integration?  Home Assistant documentation is world-class horrible

### ISSUE THREAD

**Issue by Johnny-Sweat** [home-assistant/home-assistant.github.io#34641]
### Feedback

Home Assistant documentation is world-class horrible,  Right up there with GE and Schneider Electric.  

### URL

https://www.home-assistant.io/integrations/nam/

### Version

2024.9.1

**Comment by klaasnicolaas** [comment]
A host is the address of a device you want to connect to, for example this could be an IP address.

This is also made clear in the config flow:
![image](https://github.com/user-attachments/assets/35c5faf6-9c09-432e-97f9-7b11212fc556)

./Klaas
