### ISSUE TITLE
Anthropic Conversation invalid_request_error

### ISSUE THREAD

**Issue by joshualamorie** [home-assistant/home-assistant.github.io#34642]
### Feedback

I have a professional plan for Claude.ai Sonnet, but not for the API.  I created an evaluation account and created a key.

I clicked the copy button in the console.anthropic.com page and pasted into the home assistant dialog.  I was then presented with the `invalid_request_error`.

I'm new to home assistant, so I'm not sure where to get more logs that will show more details about the error.

### URL

https://www.home-assistant.io/integrations/anthropic/

### Version

2024.9.1

### Additional information

API view at anthropic

![image](https://github.com/user-attachments/assets/47a19aff-c5d6-428f-846d-a5f41bd7d58c)

Error from home assistant

![image](https://github.com/user-attachments/assets/eb41b93c-7066-4b82-8230-0208b84100ca)

**Comment by joshualamorie** [comment]
I upgraded homeassistant from 2024.9.0 to 2024.9.1, tried again and saw the same behaviour

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
