### ISSUE TITLE
The installation instructions are circular

### ISSUE THREAD

**Issue by WillThompson** [home-assistant/home-assistant.github.io#34643]
### Feedback

If I try to add the system monitor from the UI, it links me to open the documentation from HA. When I open it and look at the manual installation instructions, this is what I see:

![image](https://github.com/user-attachments/assets/6146fed0-9738-437a-a97d-479673466d49)

Am I wrong to think that this is circular? Can this be made more clear?

### URL

https://www.home-assistant.io/integrations/systemmonitor/

### Version

2024.9.1

**Comment by gjohansson-ST** [comment]
There are no further details on how to install it as it can't be much more simpler than what it is.
I'm not sure what you're missing as either you click on the "Add the integration" button on that page and it will start the installation for you, or you follow the instructions from the page which will tell you to follow the instructions on screen in HA.

**Comment by WillThompson** [comment]
Sorry, this is my bad. I'm actually not running the most recent version of home assistant.. I thought I was, but I'm only running 2023.12.3

![image](https://github.com/user-attachments/assets/328f95fe-1691-4afb-8c1d-a6f9f61c6853)

Not an issue.
