### ISSUE TITLE
Nibe Premium MyUplink needed?

### ISSUE THREAD

**Issue by madsaarup** [home-assistant/home-assistant.github.io#34677]
### Feedback

To change Nibe Heatpump settings requires the paid Premium subscription to Nibe MyUplink.
I hoped to see here if this is also required with the HomeAssistant integration.

### URL

https://www.home-assistant.io/integrations/nibe_heatpump/

### Version

2024.9.1

### Additional information

Ref: Chapter 7 myUplink - Range of services, on page 34 of
https://www.nibe.eu/assets/documents/28142/531210-1.pdf

**Comment by elupus** [comment]
With the myuplink integration, yes. With direct modbus to S series, or nibegw devices to F series now.
