### ISSUE TITLE
Missing instructions on what to fill out for req. field "Account type" for creating a developer account.

### ISSUE THREAD

**Issue by dtlokey** [home-assistant/home-assistant.github.io#34671]
### Feedback

in the prerequisites section of the instructions there are no instructions on what option to select for the required field "Account Type" on the develop.home-connection.com/user/register page for signing up for a home connect developer account.
![Screenshot 2024-09-10 222503](https://github.com/user-attachments/assets/2a61f134-ce30-4394-b6b2-32bd61054653)
the option that seems most likely is individual, but there are three subsequent required fields when selecting that. they are:

![image](https://github.com/user-attachments/assets/542a9439-a871-46a5-a997-300178bfca57)

please advise.

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2024.9.1

**Comment by paulo-serrao** [comment]
"Open Source (Community)" works, just fill in with the home assistant official website, etc
