### ISSUE TITLE
I am looking for scripts in the core repository that are used to generate specific configurations for the IO repository, such as CODEOWNERS files and textLintrc.json, but I have not yet found the relevant scripts.

### ISSUE THREAD

**Issue by Ledgerbiggg** [home-assistant/home-assistant.github.io#34697]
### Feedback

I am writing a markdown for an IO repository and it has been completed. While reviewing other integration documents, I found that there are some default configurations because I use certain instructions in the core repository to generate specific configurations, such as python3-m script.Hassfest, python3 -m script.gen_requirements_all

I think some of the configurations in the io document are also modified through related scripts, such as the CODEOWNERS file. textlintrc.json file, but I couldn't find where the relevant scripts are. Can you give me some hints?? Thank you.

![image](https://github.com/user-attachments/assets/fbc3e4de-2a99-4e54-bdf0-412146414ea4)

### URL

http://localhost:4000/integrations

**Comment by frenck** [comment]
`CODEOWNERS` is derived from the code owners in the Core repository (I manually sync that during release).
`.textlintrc.json` is a configuration file for text lint RC, nothing is generated about that.

../Frenck
