### ISSUE TITLE
Link to webpage card is broken

### ISSUE THREAD

**Issue by Lackmake** [home-assistant/home-assistant.github.io#34705]
### Feedback

The link in the section "Card categories" > Display generic data > webpage is broken and leads to https://www.home-assistant.io/dashboards/webpage/
Which gives a 404
Should probably link to https://www.home-assistant.io/dashboards/iframe/

### URL

https://www.home-assistant.io/dashboards/cards/

### Version

2024.9.1

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @Lackmake :+1:
