### ISSUE TITLE
oven temperature

### ISSUE THREAD

**Issue by nkainc** [home-assistant/home-assistant.github.io#34720]
### Feedback

Great Integration, I personally own a BOSCH HNG6764B6 and would love to have more features, such as
- adjusting temperature
- duration (not only the sensor)
regards from vienna

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2024.9.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
