### ISSUE TITLE
Integration only showing daily cumulative sources instead of all sources

### ISSUE THREAD

**Issue by Indrid0222** [home-assistant/home-assistant.github.io#34727]
### Feedback

After setting up my SolarEdge integration to Home Assistant, the only entities that can be added to the Energy dashboard are listed below and appear to only show cumulative, not current data:

- solaredge (Consumption Energy)
This shows the cumulative amount of energy consumed by the home for the last 24 hours.
- solaredge (Exported Energy)
This shows the cumulative amount of energy exported to the grid for the last 24 hours.
- solaredge (Imported Energy)
This shows the cumulative amount of energy imported from the grid for the last 24 hours.
- solaredge (Lifetime energy)
This shows the cumulative amount of energy produced by solar for the life of the system.
- solaredge (Production Energy)
This shows the cumulative amount of energy produced by solar for the last 24 hours.
- solaredge (SelfConsumption Energy)
This shows the cumulative amount of energy consumed from solar for the last 24 hours.

The integration tracks the below current data entities that I would like to be able to add to the Energy dashboard for correct data display/gathering:

- solaredge (Current Power)
This shows the current amount of excess energy produced by solar that isn't being stored to the battery.
- solaredge (Grid Power)
This shows the current amount of energy being exported and imported from the grid (shown in positive and negative values).
- solaredge (Power Consumption)
This shows the current amount of energy being consumed by the home.
- solaredge (Solar Power)
This shows the current amount of energy produced by solar.
- solaredge (Storage Level)
This shows the current percentage of the battery (up to 100%).
- solaredge (Storage Power)
This shows the current amount of energy being stored or used by the battery (shown in positive and negative values).

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2024.9.1

### Additional information

I am using v2023.7.3 of Home Assistant, which is the most up to date version supplied by SynoCommunity.

**Comment by klaasnicolaas** [comment]
This FAQ explains exactly why you can't use power entities in the energy dashboard 😉
https://www.home-assistant.io/docs/energy/faq/#energy-vs-power

./Klaas

**Comment by Indrid0222** [comment]
> This FAQ explains exactly why you can't use power entities in the energy dashboard 😉 https://www.home-assistant.io/docs/energy/faq/#energy-vs-power
> 
> ./Klaas

Thank you for this clarification. I wasn't aware there was a distinction. Given this, I don't appear to have Energy-related entities for what is going in to and out of my Battery from the integration.
![image](https://github.com/user-attachments/assets/5320dd34-3365-4f27-ae29-4de2db2e5b25)
