### ISSUE TITLE
App password section changed in Google account

### ISSUE THREAD

**Issue by martindell** [home-assistant/home-assistant.github.io#34731]
### Feedback

No longer an option as described here:
5. At the bottom of the 2-Step Verification page, click App Passwords.

I found it by searching for app passwords, but I have no idea where this option actually lives

### URL

https://www.home-assistant.io/integrations/imap/

### Version

2024.9.1

**Comment by jbouwh** [comment]
Google is your best friend :-)

https://support.google.com/mail/answer/185833?hl=en

**Comment by jbouwh** [comment]
I checked the google docs, I cannot think of a reason to update the docs, so I'll close this issue.
