### ISSUE TITLE
Missing State for Covers

### ISSUE THREAD

**Issue by PySchilling** [home-assistant/home-assistant.github.io#34744]
### Feedback

I missing a State thet indicates end ERROR or and UNKNOWN position. For example my garage door has a obstical detection and stops moving in case and object touch the door. In this case I have an error situation, the door stops and neighter indicate open nor closed.

What about susch possible states, or are they handled in a different way?

Best regards,
Volker

### URL

https://www.home-assistant.io/integrations/cover.mqtt/

### Version

2024.9.1

**Comment by jbouwh** [comment]
Returning `null` as a value in a value template or `None` will set the state to `unknown`.
The state entity does not support a `jammed` state like `lock` does. Is your cove capable of reporting a `jammed` state?

https://developers.home-assistant.io/docs/core/entity/cover/

**Comment by PySchilling** [comment]
Hi jbouwh,

thanks for your reply. I build the door myself, It is possible to detect a jammend state and also send this via mqtt. I think personaly I'm good with cover, and just use the unknown state here.

**Comment by jbouwh** [comment]
It is possible to add a binary sensor. A fault state is not supported as you can see via the link I supplied. Strictly that would not be an issue but a feature request. Also an architectural discussion is needed to approve the new state and trigger implementation.

**Comment by jbouwh** [comment]
I suggest closing this issue, as I do not think that the `mqtt` cover implementation or its documenation has issues.
