### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by Darmok7** [home-assistant/home-assistant.github.io#34746]
### Feedback

Please add a section about Homeassistant Green and the known working Bluetooth adapters. 
Are there already 5.3 or 5.4 Adapters?
It is unclear what is required to get bluetooth integration for bluetooth

### URL

https://www.home-assistant.io/integrations/bluetooth/

### Version

2024.9.1

**Comment by frenck** [comment]
> Please add a section about Homeassistant Green and the known working Bluetooth adapters.

There is already a list on that page.

> Are there already 5.3 or 5.4 Adapters?

That is possible, at this point, no community contributions have been made to list ones that are working.

> It is unclear what is required to get bluetooth integration for Bluetooth

I'm not sure what is unclear about it... you'd need a Bluetooth stick, as you are aware yourself considering this feedback. Could you explain what is unclear?

../Frenck
