### ISSUE TITLE
Create improved layout for documentation

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant.github.io#3477]
This is the last remaining issue from #1603 and splitted out to make it easier to track for the Hacktoberfest.

> Currently our UI is not good for having long nav bars. Something like [this](https://www.polymer-project.org/1.0/start/) and [this](http://redux.js.org/) is beautiful. You can individually scroll the nav from the main content. I can see us having to implement a special layout that doesn't contain the normal header/sidebar just for docs sections.

**Comment by nicholasgriffintn** [comment]
Personally, I'd say simply reworking the site to use Polymer or another Material Design framework would be a better option in the long run, that will provide the ability to add scrolling sidebars, but it is also extendable, customisable, and it will actually be a lot less cluttered than the current code.

**Comment by balloob** [comment]
Changing the tech is not a requirement to make a better flowing UI and is also way too much work. We have over a 1000 pages. We need to find an incremental approach.

I like the documentation UI of http://redux.js.org/

 - No top bar, just a sidebar
 - Individual scrolling sidebar
 - No distractions

**Comment by nicholasgriffintn** [comment]
Well, I didn't say it was a requirement, I just said it might be more extendable, customisable, and less cluttered for all pages, not just the documentation, simply an opinion on that. I would agree with the example @balloob and I would say that's the design that needs to happen, however, I think using something like Google's Material Design Framework (https://getmdl.io/), would make that really easy to implement and easy for others to contribute to.

**Comment by brianjking** [comment]
What are your thoughts on using [MkDocs Material](https://squidfunk.github.io/mkdocs-material/)?

**Comment by nicholasgriffintn** [comment]
@brianjking I'd+1 that

**Comment by balloob** [comment]
Obviously we can't just use any off the shelf theme. We need a theme for Jekyll, as that's the static site generator that we use.
