### ISSUE TITLE
Govee H617A and HomeAssistant

### ISSUE THREAD

**Issue by dshort313** [home-assistant/home-assistant.github.io#34786]
### Feedback

H617A needs to be added to the plugin as these are awesome strip lights.  Thanks 

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.9.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
