### ISSUE TITLE
Dark mode doesn't work on documentation page(s)

### ISSUE THREAD

**Issue by SDPismo** [home-assistant/home-assistant.github.io#34790]
### Feedback

Every time I click on the documentation link for an update in HA I am hit with the stark blasting white background even though I have dark mode set for my browser as well as my system.

Can this be fixed please?

### URL

https://www.home-assistant.io/latest-release-notes/

### Version

unk

**Comment by soumajit23** [comment]
I think there is no support for dark mode in the website as a whole. So dark mode needs to be added as a new feature.

**Comment by Ruffzi069** [comment]
Hey @SDPismo ! I can help fixing this issue ! Can you assign it to me?

**Comment by frenck** [comment]
There is nothing to fix; we currently do not support / provide a dark mode version of the website. Alternatively, you could use an browser extension like Dark Reader for this specific use case.

Nevertheless, thanks for your suggestion, we might add it in the future.

../Frenck
