### ISSUE TITLE
Invalid Authentication 

### ISSUE THREAD

**Issue by SteveBarnard14** [home-assistant/home-assistant.github.io#34818]
### Feedback

Trying to login - message “invalid authentication”
Using the correct username and password. No firewall or adblocker

### URL

https://www.home-assistant.io/integrations/sleepiq/

### Version

2024.9.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by kbickar** [comment]
Just a follow up: the SleepIQ was down for maintenance at this time
