### ISSUE TITLE
The device_tracker.see action does not manually update the state of a device tracker

### ISSUE THREAD

**Issue by JohnMacHeli** [home-assistant/home-assistant.github.io#34815]
### Feedback

The device_tracker.see action requires dev-id which is documented to be: The object_id, for example tardis for device_tracker.tardis

I have tried this with a couple phone device trackers and no matter what I put into this field it yields no action (but with no errors reported).  An example is one of my phones is device_tracker.sm_s921u.  Per the example given in the documentation, it would appear that I should use dev-id = sm_s021u.  A call to the Device tracker:see to change location from home to not_home does not work.  There is little to no current information in any online documentation of how to get dev-id for a device tracker other than the example shown here.  Could you provide more details of how to get dev-id?

### URL

https://www.home-assistant.io/integrations/device_tracker/

### Version

2024.9.1

**Comment by MartinHjelmare** [comment]
The `device_tracker.see` service is only applicable to legacy device tracker platforms. Not modern config entry based device trackers.

Device trackers that track phones coming from the mobile app integration use the modern device tracker implementation.

**Comment by JohnMacHeli** [comment]
Can you point me to the "moderrn" device tracker implementation.  I don't see anything for it in the documentation.  Thanks

**Comment by MartinHjelmare** [comment]
Here's the dev docs:
https://developers.home-assistant.io/docs/core/entity/device-tracker

There are no services for the modern device tracker.

**Comment by JohnMacHeli** [comment]
Since this was labeled as Provide Feedback in Home Assistant Device Tracker document, maybe the document should be updated.  Thanks.

**Comment by MartinHjelmare** [comment]
Yes, we're aware and PR is welcome.
