### ISSUE TITLE
Would it be possible to add the following functionality?

### ISSUE THREAD

**Issue by sotoniak** [home-assistant/home-assistant.github.io#34829]
### Feedback

Thank you for your great work. I have a suggestion for improvement.
- Reboot the Wallbox
- After a manual stop: resume schedule and ecosmart mode

https://github.com/SKB-CGN/wallbox

### URL

https://www.home-assistant.io/integrations/wallbox/

### Version

2024.9.2

**Comment by hesselonline** [comment]
Hi @sotoniak, thnx for the feedback, I'm still considering adding the reboot function, just a bit anxious it might cause issues with peoples devices (rebooting at an inconvenient time for example). I'm not sure what you mean with your other request, seems like something you should automate  (using an automation in HASS) yourself maybe?
Also, for future feedback, please use the community forum as I don't think that this form is intended for feature requests, thnx ;-)

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
