### ISSUE TITLE
firewall issues

### ISSUE THREAD

**Issue by Josesanm** [home-assistant/home-assistant.github.io#34827]
### Feedback

What is the range of IP addresses that must be allowed in the firewall in order to configure the home assistant?

### URL

https://www.home-assistant.io/developers/cla/

### Version

2024.9.2

### Additional information

I can't perform updates or upload images on raspberry pi 5

**Comment by frenck** [comment]
Hi there @Josesanm 👋 

Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

../Frenck
