### ISSUE TITLE
How do you create an API key?

### ISSUE THREAD

**Issue by jtrumpio** [home-assistant/home-assistant.github.io#34848]
### Feedback

It would be great to include a link to documentation on how to create a Unifi User user and/or API key... Why does everything have to be a wild goose chase?

### URL

https://www.home-assistant.io/integrations/uvc/

### Version

2024.9.2

**Comment by c0ffeeca7** [comment]
What type of NVR do you have, specifically?
Is this [the docs](https://www.greenfieldsolutions.site/unifi-video-nvr-driver/) you are looking for, maybe?
