### ISSUE TITLE
Motionblinds integration works with Smart Home DD 7006A (P-Box)

### ISSUE THREAD

**Issue by AndreasTUHU** [home-assistant/home-assistant.github.io#34893]
### Feedback

Motionblinds integration works with Smart Home DD 7006A (P-Box) 
Please add it to the supported modells in the documentation.

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2024.6.4

**Comment by starkillerOG** [comment]
@AndreasTUHU thanks for the feedback, I added it to the list of supported bridges in this PR: https://github.com/home-assistant/home-assistant.io/pull/35012

If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.
