### ISSUE TITLE
z-station is listed as a z-wave 800 controller, its a z-wave 700 controller using zgm130s chip

### ISSUE THREAD

**Issue by chali272** [home-assistant/home-assistant.github.io#34895]
### Feedback

z-station is listed as a z-wave 800 controller, its a z-wave 700 controller using zgm130s chip.
vesternet sell this as z-wave 800 but when checking with z-wave.me they stat its z-wave 700, looking in the documentation it state zgm130s chip and that's z-wave 700, looking on zwavealience it stats the same zgm130s 

### URL

https://www.home-assistant.io/docs/z-wave/controllers/

### Version

2024.9.3

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @chali272 :+1:
