### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by cybernard** [home-assistant/home-assistant.github.io#34912]
### Feedback

I would like the add-on to track more stats.  Like when I start a game and how long I play it.  Maybe even when my friends are online.

### URL

https://www.home-assistant.io/integrations/steam_online/

### Version

2024.9.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
