### ISSUE TITLE
Custom Polling Interval?

### ISSUE THREAD

**Issue by Avventato** [home-assistant/home-assistant.github.io#34917]
### Feedback

Explanation is completely unclear. This link is supposed to give indications on how to change the polling interval of a GoodWe inverter. But in no place you can find any reference on how to modify some numeric parameter to change the polling interval. Perhaps the link is wrong.

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2024.9.3

**Comment by frenck** [comment]
There is no numeric parameter you can adjust.

If you like a custom interval, you can do so using an automation and define your own interval, schema's or conditions on when to trigger updates. 

It is extensively described here: <https://www.home-assistant.io/integrations/goodwe/#inverter-polling-interval>

../Frenck
