### ISSUE TITLE
Follow up the polling interval 

### ISSUE THREAD

**Issue by Avventato** [home-assistant/home-assistant.github.io#34918]
### Feedback

In addition I don't see anything similar to the window reported in the article (with options to choose of targets). Perhaps this is due to change of release?

### URL

https://www.home-assistant.io/integrations/goodwe/

### Version

2024.9.3

**Comment by frenck** [comment]
> to the window reported in the article

![CleanShot 2024-09-25 at 09 35 06@2x](https://github.com/user-attachments/assets/2997ab33-4923-4ec2-afe3-536acfcc168d)

Unsure what you mean by this documentation suggestion. Can you clarify?

Thanks! 👍 

../Frenck
