### ISSUE TITLE
To little information for a new user

### ISSUE THREAD

**Issue by plug-it-in** [home-assistant/home-assistant.github.io#34935]
### Feedback

So as per the instructions I added the user name and password. And yes when I restart HA I get a  Integration of Honeywell Evohome. But where do I go from here? How do I actually incorporate the integration? I have added a sensor to a dashboard but thats next to useless. How do I get so I can control Evohome from HA exactly or close to how I do in the Web or App?

### URL

https://www.home-assistant.io/integrations/evohome/

### Version

2024.9.3

### Additional information

NA

**Comment by zxdavb** [comment]
I am not sure this is the correct place to resolve your issue.

You'll have more success looking in the docs / asking in the forums: 
 - https://www.home-assistant.io/docs/
 - https://community.home-assistant.io/
