### ISSUE TITLE
Wrong url link to blog about ModelIDs

### ISSUE THREAD

**Issue by DeepCoreSystem** [home-assistant/home-assistant.github.io#34947]
### Feedback

In the release notes, in the section [Other noteworthy changes](https://rc.home-assistant.io/blog/2024/09/25/release-202410/#other-noteworthy-changes) the link to the blog post about adding ModelIDs is wrong.

**Wrong**
`https://developers.home-assistant.io/blog/2024/06/15/model-ids`
**Right**
`https://developers.home-assistant.io/blog/2024/07/16/device-info-model-id`

### URL

https://rc.home-assistant.io/blog/2024/09/25/release-202410/#other-noteworthy-changes

**Comment by frenck** [comment]
Fixed in https://github.com/home-assistant/home-assistant.io/pull/34951
