### ISSUE TITLE
Unsupported devices - Wallmount Switch

### ISSUE THREAD

**Issue by MatthiasDVB** [home-assistant/home-assistant.github.io#34956]
### Feedback

Hello, I'm, from Germany and I ordered this pretty wall-mount switches with 3,5" LC display.
It has 3way switch embedded.
This device is unsupported, can you help me how to get it supported by Tuya integration for home assistant ?

![1234](https://github.com/user-attachments/assets/d69de493-6c36-41d9-8526-32c80fe49508)

![2222](https://github.com/user-attachments/assets/a72f6f0f-38f4-4415-bfc9-77a7cfd92466)

It works fine in Tuya/Smartlife App and Tuya IoT cloud, but has no entities at Home Assistant.
It would be perfect using the 3 switches via HA.

Thank you :)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.9.3

**Comment by DieReu** [comment]
Hello everyone, I have the same problem with the "ME201W Level Sensor (unsupported)
from Tuya"
Works with the app, but has no entities in HA.
What can I do?
