### ISSUE TITLE
Feedreader has dead link and lacks information

### ISSUE THREAD

**Issue by GsakuL** [home-assistant/home-assistant.github.io#34964]
### Feedback

a) the example on the bottom of the page is dead now, because it is not a permalink.
This is essentially a re-open for  #33634

b) the old `max_entries` from the yaml can now be configured per-feed. but that's only after the feed-url was added. One needs to click the "configure" button. And it defaults to `20`. These two bits might be nice to know

@mib1185

### URL

https://www.home-assistant.io/integrations/feedreader/

### Version

2024.9.3

**Comment by mib1185** [comment]
> a) the example on the bottom of the page is dead now, because it is not a permalink.

The link has been updated by the owner of the example 6 years ago (_see #4957_) Maybe the owner can provide a new permanent link? If not we should remove the example at all to avoid any further confusion.

> b) the old `max_entries` from the yaml can now be configured per-feed. but that's only after the feed-url was added. One needs to click the "configure" button. And it defaults to `20`. These two bits might be nice to know

Fell free to add a note about this, like you would find it useful and helpful for other users, thx :+1:
