### ISSUE TITLE
What if already edited the default dashboard 

### ISSUE THREAD

**Issue by meinioz** [home-assistant/home-assistant.github.io#34967]
### Feedback

After the sentence “However, once you start editing the default dashboard, it no longer updates automatically.” it would be good to learn what to do if one already edited the default dashboard and wants to return it to the original state, so it automatically updates again. 

### URL

https://www.home-assistant.io/getting-started/onboarding_dashboard/

### Version

2024.9.3

### Additional information

I am a new user reading the manual after I tinkered with HA a bit. That way it is not just theory and much easier to comprehend.

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @meinioz :+1:
