### ISSUE TITLE
No Apprise entities appear in Home Assistant after configuring per documentation

### ISSUE THREAD

**Issue by bwirt** [home-assistant/home-assistant.github.io#34961]
### Feedback

After restarting Home Assistant, no related entities appear in Home Assistant.  Have also tried removing the "/notify/hass" in the url as docs don't provide an example or what the url should look like.  This results in no change in behavior.

Config is as follows in configuration.yaml:

```# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.20.20

notify:
  - name: Apprise
    platform: apprise
    url: https://apprise.lan.mydomain.org/notify/hass
```

### URL

https://www.home-assistant.io/integrations/apprise/

### Version

2024.9.3

**Comment by caronc** [comment]
Is this something that worked before but doesn't work now? I'm still confused what the issue is here? 🙏

**Comment by bwirt** [comment]
This is my first time setting up the integration.  It doesn't seem to work.  Issues I see:
* In /config/integrations/dashboard, icon indicates this integration depends on the cloud (see image).  Shouldn't be the case as I'm running Apprise locally.
![image](https://github.com/user-attachments/assets/c16ec636-e627-4ff6-891a-1a266daeece8)

* No configured entities appear in /config/integrations/integration/apprise after enabling the integration and restarting.  Docs indicate these should be visible.
![image](https://github.com/user-attachments/assets/ea1808e7-1a9a-4f32-9389-a98593f2a27f)

Would include debug logs but it's not clear where to find these.  I don't see any alongside the HA logs.

**Comment by bwirt** [comment]
I did try an Apprise action from the developer tools as well:
![image](https://github.com/user-attachments/assets/258139b8-d9c2-4bc1-9506-4f89dc95d059)

Looks like it's trying to send a message but getting 400:
```
2024-09-29 06:15:59.076 DEBUG (SyncWorker_38) [apprise] Apprise API POST URL: https://apprise.my.org/notify/hass (cert_verify=True)
2024-09-29 06:15:59.076 DEBUG (SyncWorker_38) [apprise] Apprise API Payload: {'title': 'test1', 'body': 'testtest', 'type': 'info', 'format': 'text'}
2024-09-29 06:15:59.127 WARNING (SyncWorker_38) [apprise] Failed to send Apprise API notification: Bad Request - Unsupported Parameters., error=400.
2024-09-29 06:15:59.127 DEBUG (SyncWorker_38) [apprise] Response Details:
b'{"error": "Bad Attachment"}'
```

**Comment by caronc** [comment]
This is a bug, but not with Home Assistant. It's likely because you're not using my docker container. Use my official container for now and I'll investigate the popular third party alternative when i get back from traveling.

More on discussion here: https://github.com/caronc/apprise/discussions/1200

**Comment by caronc** [comment]
Additionally useful info, see a blogpost i wrote a few years ago, it's still valid now (if it helps at all); https://nuxref.com/2020/12/15/setup-apprise-notifications-on-home-assistant/

**Comment by bwirt** [comment]
Very helpful, thanks.  Would be nice to link to it from the HA docs.

**Comment by bwirt** [comment]
No longer getting the "bad attachment" with your container, but calls fail with 424 if "tags" is omitted from the body.  This didn't happen with the "other" container.

**Comment by caronc** [comment]
424 is an error you might get if you associated tags with your Apprise URLs. Then you try to query the API without using a tag combination that references any of the URLs you defined.

Try using the tag `all` which will trigger all of the URLs regardless of tags assigned

**Comment by bwirt** [comment]
Understood. Looks like the cause is HA is not adding “tags” in the request. 

Will see if I can define them else use a different config, no biggie.

**Comment by caronc** [comment]
You're using the `target` HA parameter?

**Comment by bwirt** [comment]
> You're using the `target` HA parameter?

Yes, working now.  Thank you.
