### ISSUE TITLE
Add information about ha-qr-code in markdown card 

### ISSUE THREAD

**Issue by sevorl** [home-assistant/home-assistant.github.io#34977]
### Feedback

markdown card supports the <ha-qr-code> tag to create qr codes.
This is not documentend anywhere, but there are hints about the existance of this feature in the beta release notes for 2024-17 https://rc.home-assistant.io/blog/2024/09/25/release-202410/#yaml-editor-improvements

![image](https://github.com/user-attachments/assets/37e97acf-942b-49d1-933b-b67afcc55ce2)

<img width="772" alt="image" src="https://github.com/user-attachments/assets/270ab830-c406-444f-81fe-9ee430b79e90">

Please add documentation about all available parameters for this tag

### URL

https://www.home-assistant.io/dashboards/markdown/

### Version

2024.9.3

**Comment by c0ffeeca7** [comment]
Thank you for the catch and the fix, @sevorl :+1: 
Closing this as fixed by your PR https://github.com/home-assistant/home-assistant.io/pull/34981
