### ISSUE TITLE
Is it possible to get a sensor entity which states whether the garage is open or closed?

### ISSUE THREAD

**Issue by SkiBoard** [home-assistant/home-assistant.github.io#34979]
### Feedback

Is it possible to get a sensor entity which states whether the garage is open or closed?

This would help me design a new card with bigger, better and more intuitive buttons for the control card. 

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.9.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
