### ISSUE TITLE
Is there any possibility to add custom registers to the SMO40?

### ISSUE THREAD

**Issue by Anders7107** [home-assistant/home-assistant.github.io#35007]
### Feedback

Dear all,
I´m running the Nibe Heatpump integration on a Raspberry Pi4 together with a Lilygo ESP32. Downstream there is a conventional F model of the SMO40 and a F2120-16 heatpump. It works really great but I have to admit that I´m missing the two custom registers used on the OpenHAB binding for Nibe. They are 45780 (Silent mode frequency 1) and 49806 (Silent mode frequency 2). I know these are not visible in the Nibe Modbusmanager and I guess this is why they are not present in the integration.
Would it be a lot of work to add one or both of these registers to the Nibe Heatpump/SMO40? When the heatpump is monitored and managed remotely it is a great advantage if the silent frequency can be changed on the fly so to say in order to have the pump run in the most effivient way.
Many thanks in advance, I hope this message was posted in the right place and sorry if not. As You probably note I´m not quite used to things like this,
Anders

### URL

https://www.home-assistant.io/integrations/nibe_heatpump/

### Version

2024.9.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
