### ISSUE TITLE
Tested succesfully with Model RLC-843A

### ISSUE THREAD

**Issue by micjon24** [home-assistant/home-assistant.github.io#35005]
### Feedback

I have today tested with a Reolink Domekamera Model RLC-843A succesfully.

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.9.3

**Comment by micjon24** [comment]
No issue, only Information.

**Comment by starkillerOG** [comment]
@micjon24 thanks for the feedback!

I added the model to the list of supported models in this PR: https://github.com/home-assistant/home-assistant.io/pull/35008

Hope you enjoy the Reolink integration!

If you appreciate the reolink integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library or purchase Reolink products through [this affiliate link](https://reolink.pxf.io/q44QWq).
