### ISSUE TITLE
Support SIP telephony connections to Assist

### ISSUE THREAD

**Issue by PenguinNexus** [home-assistant/home-assistant.github.io#35020]
### Feedback

Hi, I'd love for there to be a tutorial for connecting a SIP Extention and/or trunk to Home Assistant, and for this to be officially supported alongside the Grandstream.
For example, I use FreePBX which uses an underlying Asterisk installation.

Here are some pre-existing tutorials and posts that show interest in this idea, but I was personally unable to get working:

- [https://lieven.kks36.be/2023/05/21/call-home-assistant-from-freepbx/](https://lieven.kks36.be/2023/05/21/call-home-assistant-from-freepbx/)
- [https://community.home-assistant.io/t/voice-over-ip-integration-call-from-any-sip-softphone/567762](https://community.home-assistant.io/t/voice-over-ip-integration-call-from-any-sip-softphone/567762)
- [https://www.reddit.com/r/homeassistant/comments/1371nf6/how_to_configure_a_voip_phone_not_analog_as_the/](https://www.reddit.com/r/homeassistant/comments/1371nf6/how_to_configure_a_voip_phone_not_analog_as_the/)

I would either love to see an integration that allows a SIP number to be dialed that reaches Home Assistant or for an Asterisk/FreePBX method to be officially supported 

Kind Regards

### URL

https://www.home-assistant.io/integrations/voip/

### Version

2024.9.3

**Comment by balloob** [comment]
Feature requests should go to the forums. We don’t however have the capacity to maintain such tutorials. I recommend you write one and share it under community guides on discourse.
