### ISSUE TITLE
Where in the yaml do I activate the diaspora boolean?

### ISSUE THREAD

**Issue by NDude1** [home-assistant/home-assistant.github.io#35024]
### Feedback

Where in the yaml do I activate the diaspora boolean?
I understand the need to do this, but I cannot figure out where or what the syntax should be. I've used HA for quite awhile, and so I've tried a few different ways of doing this, but nothing seems to work.

I already have the following included in my configuration.yaml

> jewish_calendar:
>   language: english
>   diaspora: true
>   havdalah_minutes_after_sunset: 72
> 

When I look at the available states for the Yom Tov sensor, I don't see any chag sheini options listed.
I do see duplicated chol hamoed options for sukkot and pesach.

### URL

https://www.home-assistant.io/integrations/jewish_calendar/

### Version

2024.10.0

**Comment by tsvi** [comment]
The Jewish calendar integration had moved to GUI configuration.
In 2024.11 you'll have the option to reconfigure and change the diaspora setting. Until then only the setting that was set during the initial configuration is accepted. To change the value, you'll have to remove and add the integration again.

@home-assistant close

**Comment by tsvi** [comment]
@home-assistant close
