### ISSUE TITLE
Can not login to complete integration 

### ISSUE THREAD

**Issue by Basajaun** [home-assistant/home-assistant.github.io#35045]
### Feedback

Hi, thanks for all your great work. Just want to help pointing an issue I found on this particular integration. On 2024.9 and 2024.10 can not complete de login process to setup rituals genie add on. The rituals credentials have been verified and I can manage de rituals genie with the rituals app

### URL

https://www.home-assistant.io/integrations/rituals_perfume_genie/

### Version

2024.10.0

### Additional information

The username/password has been validated and the device is properly connected to WiFi

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
