### ISSUE TITLE
KEY_EXIT is also supported

### ISSUE THREAD

**Issue by robji** [home-assistant/home-assistant.github.io#35048]
### Feedback

In the Navigation section, a row should be added for ["KEY_EXIT" | Exit] as that is also supported and useful for exiting out of all menus no matter how deep.

### URL

https://www.home-assistant.io/integrations/samsungtv/

### Version

2024.10.0

**Comment by robji** [comment]
This would still be helpful, and again it is already supported. This is just a documentation change.

**Comment by chemelli74** [comment]
Go ahead and summit a PR ;-)
