### ISSUE TITLE
Feedback about the Diagnostics Integrations

### ISSUE THREAD

**Issue by ovizii** [home-assistant/home-assistant.github.io#35043]
### Feedback

I am referring to this page: https://www.home-assistant.io/integrations/diagnostics/ 

I think the description could be improved. I still do not understand, how to enable this integration or if it is pre-enabled? It might be me though since English isn't my native language. I jsut thought I'd ask for a betetr description how this integration works and where to find it.

### URL

https://www.home-assistant.io/integrations/diagnostics/

### Version

2024.10.0

**Comment by klaasnicolaas** [comment]
It is an internal building block and present in all integrations that support it, it is not a separate integration that you can add via the UI.

./Klaas

**Comment by ovizii** [comment]
Thanks, not sure if I completely overlooked this last sentence or if you just added it but this completely clarifies my confusion:


> The diagnostics integration is by default enabled, no action is required to enable it. However, not all integrations provide the possibility to download diagnostic data.
