### ISSUE TITLE
Documentation Not Available Where Advertised

### ISSUE THREAD

**Issue by MikNolhan** [home-assistant/home-assistant.github.io#35055]
### Feedback

Your documentation here says to follow instructions on the plugin, yet the plugin does not have any instruction outside of: 
 
"The RTSPtoWebRTC integration requires a server to translate RTSP streams into WebRTC. Enter the URL to the RTSPtoWebRTC server."

### URL

https://www.home-assistant.io/integrations/rtsp_to_webrtc/

### Version

2024.10.0

**Comment by allenporter** [comment]
Yes it links to the server in the first paragraph. This integration does not explain how you set up that server, the upstream project is responsible for that.

But to your point, this is not easy. This integration will be deprecated and replaced with go2rtc running in home assistant core. You can use the go2rtc server in the mean time which has better documentation.

**Comment by MikNolhan** [comment]
Thanks for the quick reply. I set up Go2RTC. Very simple yet functional web interface which was great. I was really thrown off by the different modules. I have no issue setting it up, I usually end up compiling everything myself for photo and media services I host. I just was thrown off as to why there were both, especially when I did not see an option to add an RTSP stream to Go2RTC.
