### ISSUE TITLE
Fix Multiple repairs

### ISSUE THREAD

**Issue by IoT-CI-Ltd** [home-assistant/home-assistant.github.io#35063]
### Feedback

It would be really good if we can fix multiple issues (That all require the same fix, The unit of this entity changed, for example where I am happy for all 200 entities all the update the DB to the latest unit)

Otherwise, I am now stuck 1 by 1 clicking the same thing over 200 times :-)

### URL

https://www.home-assistant.io/integrations/repairs/

### Version

2024.10.0

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by IoT-CI-Ltd** [comment]
Hey @frenck 

No worries, I just clicked on the Feedback link here as I thought this may be useful feedback... however on reading that page again it would appear that the feedback button actually looks like it refers to the documentation only... :-) My bad....

![image](https://github.com/user-attachments/assets/0614ad9f-ad03-46ce-85da-cb7adddd71eb)

**Comment by frenck** [comment]
Hi there @IoT-CI-Ltd 👋 

Thanks! Yeah, indeed, it is for documentation feedback. Feedback is appreciated in general, but in case of feature requests, collecting them in a single place is needed (especially considering the size of the project).

So please use the community forums for suggestions like these, it really helps us define future improvements for the software side of things 🙏 

../Frenck

**Comment by IoT-CI-Ltd** [comment]
done! --> https://community.home-assistant.io/t/fix-multiple-repairs-at-once/778586
