### ISSUE TITLE
be good if your install script worked ! 

### ISSUE THREAD

**Issue by Baalsgate** [home-assistant/home-assistant.github.io#35078]
### Feedback

worst installation ive come across in a long time .. installed latest image and got as far as connecting to the host on the lan to have , installation errors in in the script and failing to install .
Ridiculous !

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2024.10.1

**Comment by frenck** [comment]
Het there @Baalsgate,

Sorry to here you having problems. However, the feedback you have submitted is rather unusable.

There is nothing in your suggestion that I can use to either help you or improve our documentation.

I can tell you are frustrated, but please note, Home Assistant is build by, supported by and maintained by a community of volunteers. Together we all try to make something awesome here by working together; reaching already a million active installations out there. Your response doesn't really help with any of that.

I really think you should try out [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

Those places have many other users around that are happy to help with anything. And if your learnings there turn out to be solvable by a documentation adjustment, we are happy to learn and help making that improvement happen.


Thanks! 👍 

../Frenck
