### ISSUE TITLE
be an idea to mention how to set the wifi manually not everyone has an ethernet network available !

### ISSUE THREAD

**Issue by Baalsgate** [home-assistant/home-assistant.github.io#35077]
### Feedback

the install instructions for the pi need a lot of work very little information on how to proceed .

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.10.1

**Comment by LifeofDan-EL** [comment]
I agree about this because I don't have ethernet and when I installed Home Assistant first, I had to look at some Youtube videos to resolve it. Working to make a PR now.

**Comment by frenck** [comment]
We strongly discourage the use of Wi-Fi on these devices. Hence it is not in our installation documentation either.

Please use an ethernet connection instead.

../Frenck

**Comment by Baalsgate** [comment]
wow thats a really ignorant response ! , so what about peoples freedom of
choice , what do you do when theres not a ethernet connection available ,
how about just providing the instructions .. you want feedback but dont
like the feedback your getting ? your documentation is really crap !

**Comment by frenck** [comment]
> wow thats a really ignorant response

> your documentation is really crap !

Sorry m8, but you cannot expect any serious response or discussion after your last response. To me, that was uncalled for and needed.

../Frenck

edit: locking this conversation for the above reasoning.
