### ISSUE TITLE
Add the hacktoberfest-accepted label

### ISSUE THREAD

**Issue by BinaryBhakti** [home-assistant/home-assistant.github.io#35076]
Thanks, @BinaryBhakti 👍 

../Frenck

_Originally posted by @frenck in https://github.com/home-assistant/home-assistant.io/pull/35052#pullrequestreview-2346561691_

CAN YOU ADD THE HACKTOBERFEST-ACCEPTED LABEL IN THE ISSUE ?

**Comment by klaasnicolaas** [comment]
That is not necessary in this case, It is also not necessary to create a separate issue for this.

./Klaas

**Comment by BinaryBhakti** [comment]
I just wanted to say that it was not getting updated on my Hacktober fest page, it is not showing pr mergered. Also the pr which I raised is merged and closed so I can't put a comment on that. So I created this. If possible add a label in that PR (#35052).

Thank you

**Comment by klaasnicolaas** [comment]
It takes some time before a PR is visible and then there is a review period of 7 days. We don't work with a `hacktoberfest-accepted` label because we already use a `hacktoberfest` tag global on the repository and that is sufficient.

./Klaas
