### ISSUE TITLE
Wled firmware

### ISSUE THREAD

**Issue by Pankotskiy** [home-assistant/home-assistant.github.io#35089]
### Feedback

Hi!
I have an issue with Wled firmware. I have preflashed Wled controller and can’t update it to version 14.0. Home assistant core doesn’t support older firmware anymore. Please help

### URL

https://www.home-assistant.io/integrations/wled/

### Version

2024.10.1

**Comment by frenck** [comment]
There is not much of help we can offer from our side; Home Assistant needs 0.14 or higher.

If you are experiencing issues upgrading your WLED device, we advise you to check out the WLED project/community/support.

../Frenck
