### ISSUE TITLE
Transition property only works in certain situations

### ISSUE THREAD

**Issue by BlackRockCity** [home-assistant/home-assistant.github.io#35081]
### Feedback

The docs mention an optional transition property but I found it didn't work with my bulb with the light.turn_on action. Some say it works with light.toggle on the same bulb hardware. I recommend that someone who knows the limitations of transition clarify this.

### URL

https://www.home-assistant.io/integrations/light/

### Version

2024.10.1

### Additional information

[https://community.home-assistant.io/t/light-transition-not-working-simple-light-transition/458967/12](https://community.home-assistant.io/t/light-transition-not-working-simple-light-transition/458967/12)

**Comment by frenck** [comment]
In general, Home Assistant provides a generic framework / universal interface to all your devices and options. This means, that for certain options to work, your device needs to support it.

If your light doesn't support transitions, it will obviously not work. Similar example, we also document how to set a color on your light, but if your light doesn't support colors at all, those features won't work.

This does not apply only to lights, this applies to virtually anything in Home Assistant. We can't add features to the hardware you buy.

../Frenck

**Comment by BlackRockCity** [comment]
Your response doesn’t address either issue. 

1) bulbs that support transitions are purportedly only transitioning when light.toggle is called. Perhaps, if true, that’s a bug. 

2) the documentation should say that transition only works when light.toggle is called and will not work when light.turn_on is called.

it also wouldn’t hurt to state that some bulbs don’t support transitions because that would be a user friendly thing to say. 

 I realize that a bulb that doesn’t display colors will never display colors. That’s moot.

**Comment by frenck** [comment]
> bulbs that support transitions are purportedly only transitioning when light.toggle is called. Perhaps, if true, that’s a bug.

If you suspect a bug, you'd need to report it to the Core issue tracker.

> the documentation should say that transition only works when light.toggle is called and will not work when light.turn_on is called.

That seems indeed like a bug, thus not a documentation issue


../Frenck
