### ISSUE TITLE
Additional sensor for current consumption in the month

### ISSUE THREAD

**Issue by Davidginz** [home-assistant/home-assistant.github.io#35087]
### Feedback

Can you add current month consumption reading?

### URL

https://www.home-assistant.io/integrations/rympro/

### Version

2024.10.1

### Additional information

Current month consumption sensor will be nice to have.

**Comment by OnFreund** [comment]
I don't know if/when I'll get to it, but in the meantime you can use the [Utility Meter Integration](https://www.home-assistant.io/integrations/utility_meter/) to achieve this.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
