### ISSUE TITLE
limitless led not working

### ISSUE THREAD

**Issue by cybernard** [home-assistant/home-assistant.github.io#35080]
### Feedback

![462083186_8423119181058719_7282911810702427448_n](https://github.com/user-attachments/assets/8a22397d-a1d5-4f87-b135-2417bf9a4ed6)

nmap shows 

PORT      STATE         SERVICE
6668/tcp  open          irc
8123/tcp  filtered      polipo
64190/udp open|filtered unknown

Yet when I use google to control the LED it uses a 40068
tcpdump has this to say

19:13:49.656203 IP 35.162.13.26.8886 > 192.168.5.232.40068: Flags [P.], seq 2852059452:2852059745, ack 803905405, win 65535, length 293
        0x0000:  4500 014d 3441 4000 f006 5e1d 23a2 0d1a  E..M4A@...^.#...
        0x0010:  c0a8 05e8 22b6 9c84 a9fe f93c 2fea 9f7d  ...."......</..}
        0x0020:  5018 ffff 625c 0000 1703 0301 20c8 3b3b  P...b\........;;
        0x0030:  966d 1464 b854 1187 d432 e528 6610 b493  .m.d.T...2.(f...
        0x0040:  75a1 db60 0517 3518 6df1 7a6c e533 716b  u..`..5.m.zl.3qk
        0x0050:  0327 7d0c 844e 1c94 43d5 7f04 535d 0fe6  .'}..N..C...S]..
        0x0060:  3bca 3e01 18ad 7bd4 8378 2cb2 5828 e9a0  ;.>...{..x,.X(..
        0x0070:  b55c ae4a 73b7 c13d ee68 ad16 2005 3804  .\.Js..=.h....8.
        0x0080:  8cae 8295 c055 2c42 fe6a 3fe3 ae0f c79e  .....U,B.j?.....
        0x0090:  f053 985c 6b19 4b77 5639 d0d9 d73c d982  .S.\k.KwV9...<..
        0x00a0:  2287 baf6 9ddf 8f51 7225 5a66 9beb 037c  "......Qr%Zf...|
        0x00b0:  72ac bd44 76e6 4521 5297 dad7 69a2 a7d0  r..Dv.E!R...i...
        0x00c0:  37bf f5c2 4094 1639 add6 3c24 8ce6 dc09  7...@..9..<$....
        0x00d0:  ef55 ccab 3503 46c2 8e29 965e ade1 f794  .U..5.F..).^....
        0x00e0:  c40f 93c2 256c 30ce 4e1f 2746 26a3 f983  ....%l0.N.'F&...
        0x00f0:  3147 75e5 2f5f 0c43 256a 7fb2 6bfb e459  1Gu./_.C%j..k..Y
        0x0100:  ed9d 252d f584 b8f0 4338 9bc2 fcbc 7bb1  ..%-....C8....{.
        0x0110:  fb7d 377d bde2 0937 78e9 f7b2 1dfb 1bc7  .}7}...7x.......
        0x0120:  f92a 800b e815 2297 0b5b b899 a965 cce0  .*...."..[...e..
        0x0130:  5239 461d 7b86 72e3 25fa 1af7 f663 4581  R9F.{.r.%....cE.
        0x0140:  6727 70ee 18f0 eefa 2191 c3f8 25         g'p.....!...%
19:13:49.792171 IP 35.162.13.26.8886 > 192.168.5.232.40068: Flags [P.], seq 293:362, ack 182, win 65535, length 69
        0x0000:  4500 006d 3442 4000 f006 5efc 23a2 0d1a  E..m4B@...^.#...
        0x0010:  c0a8 05e8 22b6 9c84 a9fe fa61 2fea a032  ...."......a/..2
        0x0020:  5018 ffff b268 0000 1703 0300 40a1 4d96  P....h......@.M.
        0x0030:  252b 827e 1a26 c9fa f009 56f0 b6f1 c28e  %+.~.&....V.....
        0x0040:  1f7e 6903 4154 5509 836e 742b 3ac1 f05d  .~i.ATU..nt+:..]
        0x0050:  c3a3 b725 67f8 66b2 24db 8fbb c217 3910  ...%g.f.$.....9.
        0x0060:  b8ac 40df 8bc4 32aa baf0 b9e3 76         ..@...2.....v
19:13:56.945450 IP 35.162.13.26.8886 > 192.168.5.232.40068: Flags [P.], seq 362:655, ack 182, win 65535, length 293
        0x0000:  4500 014d 3443 4000 f006 5e1b 23a2 0d1a  E..M4C@...^.#...
        0x0010:  c0a8 05e8 22b6 9c84 a9fe faa6 2fea a032  ...."......./..2
        0x0020:  5018 ffff 23ae 0000 1703 0301 2055 5705  P...#........UW.
        0x0030:  e725 791d da88 8d0b 71c7 e8a7 eb76 bddb  .%y.....q....v..
        0x0040:  d98e 25e5 ea77 31a9 e225 26a9 2114 051a  ..%..w1..%&.!...
        0x0050:  e9f0 d904 e9e2 4f04 05dc f791 061c 0bec  ......O.........
        0x0060:  05ac 19e9 ab25 3ad1 c5e4 e39f 8d19 c3cd  .....%:.........
        0x0070:  c663 55dd d86c 64a2 576d 17a1 7202 37d9  .cU..ld.Wm..r.7.
        0x0080:  8164 f163 76d0 2344 c93f 78f6 ef8b 5337  .d.cv.#D.?x...S7
        0x0090:  ad99 78c7 7728 682d a8b9 4605 5eab 9523  ..x.w(h-..F.^..#
        0x00a0:  2dcc 87b0 270c 2ed9 5761 4b1f f80d 369e  -...'...WaK...6.
        0x00b0:  1caf ffb3 212a 340a 1600 7181 5947 5e2e  ....!*4...q.YG^.
        0x00c0:  2bf5 e17b 5e0d be36 6e20 1a76 2870 10b3  +..{^..6n..v(p..
        0x00d0:  e6bb e151 63b6 1bcc b302 e559 454a 6059  ...Qc......YEJ`Y
        0x00e0:  d5c7 ed6f 471a f3ae dda7 80b4 94fe eb10  ...oG...........
        0x00f0:  cc12 49c0 4f1c 06f1 5c3a 92c8 7f70 0ecc  ..I.O...\:...p..
        0x0100:  e1db 146e 0e97 c7ba 9988 1ba5 0d14 a4f4  ...n............
        0x0110:  3a98 1801 1684 bc77 13ec 154b 32af 0f64  :......w...K2..d
        0x0120:  1730 b6b3 52b8 eaf9 7944 81fb 51b8 3270  .0..R...yD..Q.2p
        0x0130:  d19b 38c0 e923 b3b6 db7f 3313 63d4 b1dc  ..8..#....3.c...
        0x0140:  0825 3d11 e48f 6b3a 8700 e1ad e4         .%=...k:.....
19:13:57.117243 IP 35.162.13.26.8886 > 192.168.5.232.40068: Flags [P.], seq 655:724, ack 363, win 65535, length 69
        0x0000:  4500 006d 3444 4000 f006 5efa 23a2 0d1a  E..m4D@...^.#...
        0x0010:  c0a8 05e8 22b6 9c84 a9fe fbcb 2fea a0e7  ...."......./...
        0x0020:  5018 ffff d6f2 0000 1703 0300 40cd 7c8b  P...........@.|.
        0x0030:  225e 49a3 d970 ba2e 70bf 77ad 89f4 6ee0  "^I..p..p.w...n.
        0x0040:  e418 1b1a d9c5 faa5 89b2 810c 9561 3a47  .............a:G
        0x0050:  145a 669b f666 3d50 bdcc e500 ca50 a7af  .Zf..f=P.....P..
        0x0060:  5a00 cb68 cdcd 0a1d e52d 392f 66         Z..h.....-9/f

so clearly something is different about my device

### URL

https://www.home-assistant.io/integrations/limitlessled/

### Version

2024.10.1

**Comment by frenck** [comment]
Hi there @cybernard 👋 

It seems like you are experiencing issue with a Home Assistant integration, however, you have submitted documentation feedback. If you want to report an integration issue, please report it here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
