### ISSUE TITLE
Add-on is necessary

### ISSUE THREAD

**Issue by stebrau** [home-assistant/home-assistant.github.io#35094]
### Feedback

There should be a hint that the Syncthing-Add-on is necessary!

### URL

https://www.home-assistant.io/integrations/syncthing/

### Version

2024.10.1

**Comment by frenck** [comment]
Hi there @stebrau 

Thanks for the feedback, however, your statement is not correct.

This integration integrates Syncthing with Home Assistant and isn't tied to a specific installation method. It requires Syncthing, but how you install it, it up to you.

Please refer to the Syncthing documentation for installation instructions.


../Frenck
