### ISSUE TITLE
Zigbee radiotor valves not showing

### ISSUE THREAD

**Issue by smacpi** [home-assistant/home-assistant.github.io#35110]
### Feedback

Have you found a method for zigbee (new ones) to show in the api 

### URL

https://www.home-assistant.io/integrations/geniushub/

### Version

2024.10.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
