### ISSUE TITLE
Potential `.io` TLD issues 

### ISSUE THREAD

**Issue by pfefferle** [home-assistant/home-assistant.github.io#35111]
### Feedback

The future of the `.io` domain seems unclear, as the UK will give sovereignty of Chagos Islands to Mauritius: https://domainincite.com/30406-five-times-icann-deleted-a-cctld-and-what-it-means-for-io

Maybe you should consider an alternative/fallback domain to be on the safe side.

### URL

https://www.home-assistant.io/

**Comment by frenck** [comment]
Thanks, @pfefferle 👍 

It is on our radar and we keep watching what happens.

../Frenck
