### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by navikynas** [home-assistant/home-assistant.github.io#35112]
### Feedback

No longer works after core update, is there any solution?

### URL

https://www.home-assistant.io/integrations/autarco/

### Version

2024.10.1

**Comment by frenck** [comment]
Hi there @navikynas 👋 

You are experiencing issues with the integration and want to report a bug. However, you have submitted documentation feedback. Please report issues with integrations:

<https://www.github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
