### ISSUE TITLE
Blank error message

### ISSUE THREAD

**Issue by MattJTC** [home-assistant/home-assistant.github.io#35122]
### Feedback

Suggest adding a note in troubleshooting that the "blank error" obtained on the final step of linking your account can be a result of a timeout when using a reverse proxy to secure your HA. I have found I needed to up this to above 2 minutes to complete the final step of the integration.

Thanks for the integration! 
Any plans to add in the hot water control for the learning thermostat?

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.10.1

**Comment by frenck** [comment]
Hi there @MattJTC 👋 

> Suggest adding a note in troubleshooting that the "blank error" obtained on the final step of linking your account can be a result of a timeout when using a reverse proxy to secure your HA. 

A blank error should never happen; therefore, we should not document it. Could you raise this as a bug report for the integration on our Core issue tracker? You can find it here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
