### ISSUE TITLE
Netgear Plus support of switch GS110EMX

### ISSUE THREAD

**Issue by joke-air** [home-assistant/home-assistant.github.io#35139]
### Feedback

Thank you for your effort to integrate things to HA, even if not simple like NON-SNMP/NON-CLI compatible.

I have a new switch 1/10Gb switch GS110EMX which, when local temperature is close to 25°C (often in summer in Europe/Switzerland..) and using intensively ports 9 and 10 in 10Gbps, and can, sometime drop TCP traffic, and I would like to monitor it on Home-Assistant to have an eye on IT.

Do you expect to ensure that this model GS110EMX will be also working with your Intergation module ?

### URL

https://www.home-assistant.io/integrations/netgear/

### Version

2024.10.1

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍

**Comment by joke-air** [comment]
> Thank you for reaching out.
> 
> We use GitHub for tracking issues, not for tracking feature requests.
> 
> If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).
> 
> Thanks! 👍

Hi Nicolaas,

I don't know how to create a feature request with appropriate Subject on such Integration module topic and link.
I can't find this module on your link forum.

BR
