### ISSUE TITLE
Instructions on how to authenticate Kasa/Tapo devices that require it.

### ISSUE THREAD

**Issue by fugros** [home-assistant/home-assistant.github.io#35149]
### Feedback

Unless I am missing something big, I cannot figure out how to authenticate Kasa/Tapo devices that require it.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.10.1

**Comment by rytilahti** [comment]
I'm not sure I understand what you mean, would you mind clarifying what you mean by authentication? Provisioning the device that is not yet connected to your wifi network?

If the device requires authentication, you will be prompted for the e-mail and the password, but if it's not necessary you can add the device without any extra steps.

**Comment by fugros** [comment]
Thanks for your reply. Let me explain my problem as I maybe I am assuming the solution too quickly.
I have a 2x Kasa HS100 plugs. One is hardware version 2.1 and connects fine. The other is hardware version 4.1 and does not connect. I get the attached error. On reading the documentation, I was thinking it may have been an issue with authentication.
![image](https://github.com/user-attachments/assets/d318df18-d75e-4eee-bdb2-0058d796d824)

**Comment by sdb9696** [comment]
You may have an issue with discovery running on your network which is required for version 4.1.  If you raise an issue https://github.com/home-assistant/core we can troubleshoot there and I'd suggest uploading some logs when you open that ticket.

**Comment by sdb9696** [comment]
@home-assistant close
