### ISSUE TITLE
Zengee doesnt work

### ISSUE THREAD

**Issue by JMS1717** [home-assistant/home-assistant.github.io#35142]
### Feedback

The problem
The Zengge integration is failing to load due to a missing requirement. When attempting to use the Zengge integration, Home Assistant reports the following configuration warning:
Platform error 'light' from integration 'zengge' - Requirements for zengge not found: ['bluepy==1.3.0'].

This error prevents the Zengge lights from being integrated into Home Assistant.
What type of installation are you running?
Generic x64-x86
Integration causing the issue
Zengge
Link to integration documentation on our website
https://www.home-assistant.io/integrations/zengge/
Example YAML snippet
text
light:
  - platform: zengge
    devices:
      "XX:XX:XX:XX:XX:XX":
        name: Living Room Light

Additional information
The error suggests that the bluepy library version 1.3.0 is not installed or not found by Home Assistant.
Attempts to manually install bluepy have been unsuccessful due to compilation issues or system restrictions.
This issue seems to be related to the known problem of the Zengge integration relying on outdated Bluetooth libraries (bluepy and pybluez) that are no longer compatible with newer Python versions.
Possible solutions to investigate
Update the Zengge integration to use a more modern Bluetooth library like bleak.
Provide a pre-compiled wheel for bluepy compatible with the Home Assistant environment.
Create a custom component that replaces the official Zengge integration with one that uses updated libraries.
Any assistance or guidance on resolving this issue would be greatly appreciated.

### URL

https://www.home-assistant.io/integrations/zengge/

### Version

2024.10.1

**Comment by Alive1984** [comment]
same issue. follow the documentation but itegration doesn't appear. 
core: 2024.10.3
Operating System:  13.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by Alive1984** [comment]
@klaasnicolaas Hi!
the documentation does not achieve the desired result. I don't know if there is a problem with the documentation or with the integration. So you're telling me that integration has problems? It seems premature to close the request.
