### ISSUE TITLE
Wallbox Copper SB

### ISSUE THREAD

**Issue by Sjorsdeman** [home-assistant/home-assistant.github.io#35144]
### Feedback

I cannot connect the wallbox via the manual. I have a wallbox Copper SB.

### URL

https://www.home-assistant.io/integrations/wallbox/

### Version

2024.10.1

**Comment by hesselonline** [comment]
Hi @Sjorsdeman, I believe this is an attempt by you to get personal support for your home setup. However, this is not the place. Please discuss difficulties in setting up the integration on the Home Assistant (if you're really stuck, send me a dm there (but please, some more info;-)).

**Comment by hesselonline** [comment]
Hi @Sjorsdeman, I believe this is an attempt by you to get personal support for your home setup. However, this is not the place. Please discuss difficulties in setting up the integration on the Home Assistant (if you're really stuck, send me a dm there (but please, some more info;-)). 
@home-assistant close

**Comment by hesselonline** [comment]
@home-assistant close
