### ISSUE TITLE
Troubleshooting: Unknown error occurred

### ISSUE THREAD

**Issue by viking272** [home-assistant/home-assistant.github.io#35150]
### Feedback

I get this a lot, so would be good to have it covered in the documentation...

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2024.10.1

**Comment by RAj5517** [comment]
can you explain please, what the problem is so that I can work on that !

**Comment by viking272** [comment]
Hi,
Thanks for the reply.

I had a working HA setup in docker v2024.1
HACS was on 1.3.
I updated both and then Unifi Protect wasn't recognised.
I removed it all and tried to rejoin my UDMPRO but it immediately gave me
the 'unknown error occurred whilst still in the dialog box to connect to my
local UDMPRO.

I am on UDMPRO OS 4.0.20 and Protect 5, maybe that's the issue?
Otherwise is Unifi Protect support removed?

Thanks,
Simon

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
