### ISSUE TITLE
Disappearance of TLD .io, hence of home-assistant.io

### ISSUE THREAD

**Issue by mathieumd** [home-assistant/home-assistant.github.io#35165]
### Feedback

I just stumbled on https://every.to/p/the-disappearance-of-an-internet-domain

> The decision to transfer the islands to their new owner will result in the loss of one of the tech and gaming industry’s preferred top-level domains: .io.

I though you should not miss this.

### URL

https://www.home-assistant.io/

**Comment by frenck** [comment]
We are aware, thanks 👍 

../Frenck
