### ISSUE TITLE
Support to H601A

### ISSUE THREAD

**Issue by borislubomirsky** [home-assistant/home-assistant.github.io#35172]
### Feedback

Hi there, I wonder when if you are planning to add the support to the H601A product. 

Thank you.

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.10.1

### Additional information

would like to support as well if it will expedite the process.

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
