### ISSUE TITLE
Missing port mapping instructions for Docker Desktop

### ISSUE THREAD

**Issue by NickDrouin** [home-assistant/home-assistant.github.io#35173]
### Feedback

The ports are not exposed when following the instructions for Docker when running Docker Desktop for Windows.

See topic: 
https://community.home-assistant.io/t/homeassistant-running-on-docker-desktop-for-windows-but-not-accessible-from-browser/370731/3

The solution is to add:

```
    ports:
      - "8123:8123"
```

Within the docker compose file.

As this does not apply to every docker situation, a comment in the document is likely the most prudent change. 
This will be submitted as a PR shortly.

### URL

https://www.home-assistant.io/installation/alternative

**Comment by NickDrouin** [comment]
https://github.com/home-assistant/home-assistant.io/pull/35174

**Comment by frenck** [comment]
Hi there @NickDrouin 👋 

Closing this issue, as the suggest / raised issue is using an unsupported method of running Home Assistant. Please consult or installation documentation for the available installation methods for your environment.

Thanks! 👍 

../Frenck
