### ISSUE TITLE
Default zigbee2MQTT install sets MQTT Protocol to unsupported version in default MQTT install

### ISSUE THREAD

**Issue by Busta999** [home-assistant/home-assistant.github.io#35179]
### Feedback

I suspect this is impacting users who are creating zigbee2MQTT services.

The default zigbee2MQTT install sets MQTT protocol version to v4 and cannot be overwritten in zigbee2MQTT UI.

Has to be set in the configuration.yaml file to one of the supported MQTT protocols in the default Mosquitto install, either 5.0, 3.1.1 or 3.1.

4 is not supported and seems to manifest in the issue where if a user try to set a Device Settings such as Retain in the UI it is automatically removed before the user can press the Save button.

### URL

https://www.zigbee2mqtt.io/guide/installation/03_ha_addon.html

### Version

2024.10.1

### Additional information

Suspect this is has been an issue since at least Christmas 2023.

Users with a working zigbee2MQTT won't have an issue but I suspect all new users will.

**Comment by frenck** [comment]
The MQTT v4 specific doesn't exists, see also: https://mqtt.org/mqtt-specification/

../Frenck

**Comment by Busta999** [comment]
Exactly!!!

Why does the default install of zigbee2MQTT set MQTT version to 4 then?
/Mike

**Comment by frenck** [comment]
Good question, but this isn't the Zigbee2MQTT project...

../Frenck

**Comment by Busta999** [comment]
Gulp sorry :-)

Ha

OK

**Comment by Busta999** [comment]
I thought Home Assistant managed its add ons, never mind I figured it out.
