### ISSUE TITLE
Power cycle your gateway

### ISSUE THREAD

**Issue by Surki69** [home-assistant/home-assistant.github.io#35185]
### Feedback

In the documentation you mention for offline gateway issues: Usually, this resolves itself after a while, but if this state persists, try to power cycle your gateway.

can you explain in the documentation how to "power cycle your gateway" please?

### URL

https://www.home-assistant.io/integrations/vicare/

### Version

2024.10.2

### Additional information

A general comment as a new starter in HA. The documentation is super rich and certainly very helpful but often it is not very clear what to do and how to do it. I think it is a problem of experts speaking to experts but there are not only experts out there. ;-)

**Comment by CFenner** [comment]
Hey, in my case (Heatbox1/2) I can just poll the plug of the separate gateway. In case of an E3 device, you probably need to restart the whole heating device?

**Comment by Surki69** [comment]
yes, my comm device it is integrated in the heating device. I need to figure out if I can do a soft start of the comm device without unpowering the whole heating.

**Comment by CFenner** [comment]
This is how it looks like with a dedicated gateway device. 

![IMG_6125](https://github.com/user-attachments/assets/0e1196ec-4261-43dd-a3a8-ae8109fb6d9a)

**Comment by Surki69** [comment]
It has come back spontaneously after some time. I also saw an offline status in the native ViCare App. The server seems to be offline from time to time.

**Comment by CFenner** [comment]
@home-assistant close
