### ISSUE TITLE
Add a linear-interpolation option please

### ISSUE THREAD

**Issue by thoath2** [home-assistant/home-assistant.github.io#35182]
### Feedback

If it were possible to incorporate an option interpolation: [True/False], which ensures that gaps are closed that can arise from a temporary failure. The integration from the last existing meter value (e.g. at energy meters) could interpolate the missing meter readings linearly before the failure. With the calculated meter readings, the integration could fill the gaps after the sensor is returned.
That would be a top-feature.

### URL

https://www.home-assistant.io/integrations/utility_meter/

### Version

2024.10.2

**Comment by dgomes** [comment]
Sorry but this is for tracking bugs not feature requests.

Please use https://community.home-assistant.io/c/feature-requests/13

Having pointed the obvious, I think what you want is already available https://www.home-assistant.io/integrations/utility_meter/#periodically-resetting
