### ISSUE TITLE
The configuration help is too terse

### ISSUE THREAD

**Issue by garethhowell** [home-assistant/home-assistant.github.io#35191]
### Feedback

When adding the integration, you need to provide a URL to the emoncms instance. However, there is no guidance on what form this URL should take. e.g. http:// or https:// or just an address. I tried all three and got errors.

### URL

https://www.home-assistant.io/integrations/emoncms/

### Version

2024.10.2

**Comment by alexandrecuer** [comment]
I agree the documentation has to be improved
For the URL, there is some (small) guidance in the field description where you fill in the URL `server url staring with the protocol (http or https)`
![image](https://github.com/user-attachments/assets/edf08199-9275-403e-ae18-4e4e797ff3ee)
