### ISSUE TITLE
APS log in error. 

### ISSUE THREAD

**Issue by mrhess9873495** [home-assistant/home-assistant.github.io#35194]
### Feedback

APS customer. Getting "Invalid authentication" when username and pw are typed into setup screen. 

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2024.10.2

**Comment by thewolfman56** [comment]
I just upgraded from 2024.8.2 to 2024.10.2 specifically for this integration and am having the same issue.  I double checked that I could login in to the APS website with the same credentials.

**Comment by frenck** [comment]
Hi there @thewolfman56 and @mrhess9873495 👋 

It seems like you are experiencing an issue with setting up an integration and want to report that issue. However, you have submitted documentation feedback instead.

Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
