### ISSUE TITLE
Probably some key config entries are missing

### ISSUE THREAD

**Issue by Vladx71** [home-assistant/home-assistant.github.io#35190]
### Feedback

Hi,

I'm trying to implement a snapshot upload to google photos using this integration. Google Photos integration is configured, so I have a google_photos.upload action. This action requires Integration ID, Filename and Album as parameter. The first two is ok, but what should be in the Album? I've tried both human readable name and the albumID as it can be seen in the url. None of these are working. Is this a deprecated integration or something is missing from the documentation?

Thanks
L:

### URL

https://www.home-assistant.io/integrations/google_photos/

### Version

2024.10.2

**Comment by allenporter** [comment]
Home Assistant can only access data created by Home Assistant, so you can't upload to an existing album. When you specify a name, it will create a new album with that name, or upload into the existing album if home assistant previously created it.  So, just put the name of a new album you'd like.

... Can update the documentation to make this more clear.

**Comment by Vladx71** [comment]
After a couple of tries, it was able to add snapshots to an existing album,
so statement is not entirely true, it CAN add photos to existing albums as
well.

L:

**Comment by allenporter** [comment]
Ok don't expect that to work long. It's not intended and likely functionality going away from the API in the future.
