### ISSUE TITLE
Missing concepts in documentation

### ISSUE THREAD

**Issue by luisrosety** [home-assistant/home-assistant.github.io#35200]
### Feedback

Hi,
I am starting with Home Assistant and encountering difficulties with some concepts. Your page [Getting Started - Concepts & Terminology](https://www.home-assistant.io/getting-started/concepts-terminology/) is really helpful, but I feel some important concepts are missing:
    Domains
    Services
It would be beneficial to include these in your documentation for newcomers.
Thank you!

### URL

https://www.home-assistant.io/getting-started/concepts-terminology/

### Version

2024.10.2

**Comment by j4n-e4t** [comment]
Hi @luisrosety! I totally get your point. What exactly would you find helpful to know about domains and services? I'm thinking  of updating the documentation but I'm not quite sure what exactly someone like you would need?

**Comment by luisrosety** [comment]
Hi,

As a complete newcomer to Home Assistant (HA), I initially struggled to
understand automations and scripting. I came across examples using terms
like "domain" and "service," which took me some time to grasp. Eventually,
I realized that "services" are somewhat similar to methods in
object-oriented programming (OOP) — essentially, actions that an object can
perform. However, the concept of "domain" is still unclear to me. I
understand it might be similar to "integration," but I haven't fully
figured out the difference yet.

Thank you so much for your quick response to my question, and of course,
for your excellent work!

Luis Rosety

**Comment by j4n-e4t** [comment]
@luisrosety 
I created a quick draft of the new page. Might taking a look? 
https://deploy-preview-35205--home-assistant-docs.netlify.app/getting-started/concepts-terminology/#integrations

Also, the term "service" is deprecated and was replaced with "action" last month. This hopefully makes it a bit clearer what  it actually does.

**Comment by luisrosety** [comment]
Great!
I think it is much clearer now.
Thanks Julian
Luis

**Comment by j4n-e4t** [comment]
It seems as if such a detailed explanation is not ment to be inside the onboarding. -> https://github.com/home-assistant/home-assistant.io/pull/35205

However, I'm glad I could help!

Have a nice day,
Julian
