### ISSUE TITLE
Website installations "used by ... active installations" analytics inaccurate?

### ISSUE THREAD

**Issue by ARW-online** [home-assistant/home-assistant.github.io#35201]
### Feedback

The https://www.home-assistant.io/integrations/eafm/ page states that it is used by 0 (zero) active installations -- but I am using it, I have been for a couple of months now, and I have all analytics enabled on my installation.
```
The UK Environment Agency Flood Monitoring integration was introduced in Home Assistant 0.115, and it's used by [0](https://analytics.home-assistant.io/integrations) active installations.
```

Is there something amiss with my reporting, or is there an issue in analytics?

### URL

https://www.home-assistant.io/integrations/eafm/

### Version

2024.10.2

**Comment by j4n-e4t** [comment]
Hi @ARW-online! Generally said, the analytics for Home Assistant are opt in which means that these numbers don't track the  entire ecosystem. However, 0 installs seems a bit suspicious to me I and can look into that if you want to. Weirdly, the integration also doesn't come up here https://analytics.home-assistant.io/integrations/

**Comment by ARW-online** [comment]
Thanks! Yes please. It's not that important to me, per-se, but in general I would not like integrations to be undervalued due to inconsistent stats.  I realise not everyone would opt-in... But I am opted in, so would expect the counter to say at least 1 active user!

**Comment by j4n-e4t** [comment]
Hi @ARW-online,

sadly, I wasn't able to figure out, what's the exact issue with the `eafm` integration. However, I've seen other integrations with "0" users. Could be a bigger issue then but I could be wrong...
