### ISSUE TITLE
Podcast Complete Example of Feedreader GitHub Link Broken

### ISSUE THREAD

**Issue by Sythsaz** [home-assistant/home-assistant.github.io#35209]
### Feedback

I get
 "404 - page not found
The master branch of Home-AssistantConfig does not contain the path config/packages/hasspodcast.yaml."
when trying to access the example listed at "https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/hasspodcast.yaml". Thanks

### URL

https://www.home-assistant.io/integrations/feedreader/

### Version

2024.10.2

**Comment by mib1185** [comment]
- duplicate of #34964
