### ISSUE TITLE
How to accomodate different pv orientations within the Forecast Solar integration

### ISSUE THREAD

**Issue by climbernl** [home-assistant/home-assistant.github.io#35204]
### Feedback

I recently installed the Forecast Solar integration, but when configuring the right parameters, it seems I can only add one  orientation for the panels. I have 10 panels but with different angles and orientation (4x), but all connected to one (SolardEdge) inverter.
Or should I duplicate the integration for each of the orientations. Please advice here.

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2024.10.2

**Comment by klaasnicolaas** [comment]
You add each zone/orientation separately by going through the config flow of the forecast.solar again.

This is also documented:
> If you have more than one plane of solar modules with different properties (e.g. several sides of the roof on different strings or on different buildings, with different directions or declinations) you can add the integration multiple times setting parameters accordingly.

./Klaas
