### ISSUE TITLE
Cannot find Bluetooth IRK on latest MacOS

### ISSUE THREAD

**Issue by KE55ARD** [home-assistant/home-assistant.github.io#35220]
### Feedback

These instructions are not relevant on the latest version of MacOS (Sequoia) because the Keychain Access app has been replaced by a new Passwords app which does not seem to have a way of exposing the same information.

### URL

https://www.home-assistant.io/integrations/private_ble_device/

### Version

2024.10.2

**Comment by Jc2k** [comment]
I am unable to help with this ticket because I don't have anything running that version of macOS. Hopefully someone from the community can help.

**Comment by JoLambinon** [comment]
Go to Spotlight search on MacOS (Sequoia) and search for keychain access and not passwords app, process remains the same.

**Comment by KE55ARD** [comment]
Spotlight search found the app, but still opened the new Passwords app.

I did however find a way to open it, by navigating to "/System/Library/CoreServices/Applications/Keychain Access" and opening it from there, and even then it asked if I wanted to open it or Passwords instead.

Might be worth adding this workaround to the page still?

Thanks
