### ISSUE TITLE
YAML example

### ISSUE THREAD

**Issue by mitchger** [home-assistant/home-assistant.github.io#35223]
### Feedback

Example of config would be helpful for people not too familiar with YAML; I don't know how to structure the variables.

### URL

https://www.home-assistant.io/integrations/flic/

### Version

2024.10.2

**Comment by frenck** [comment]
Hi there @mitchger 👋 

There is:

![CleanShot 2024-10-14 at 13 18 55@2x](https://github.com/user-attachments/assets/0a029954-f8fa-473d-992a-5c973e0d5102)


Could you clarify what you mean by your feedback in that case? As it isn't clear to me.

../Frenck
