### ISSUE TITLE
I can't add the ECOVACS add-on

### ISSUE THREAD

**Issue by c40s68** [home-assistant/home-assistant.github.io#35227]
### Feedback

When i try to install the ECOVACS add-on i get this error: {"message":"Invalid handler specified"}.
In the system log: Error occurred loading flow for integration ecovacs: No module named '_lzma'
i've tried to install lzma.
What can i do?
Thanks.

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.10.2

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
