### ISSUE TITLE
typo in example?

### ISSUE THREAD

**Issue by fotovlieger** [home-assistant/home-assistant.github.io#35229]
### Feedback

I believe 'conditions:' in the automation example should be 'condition:' (singular). Had to change it to make it work...

### URL

https://www.home-assistant.io/integrations/input_boolean/

**Comment by frenck** [comment]
Hi there @fotovlieger 👋 

It sounds like you are using an older version of Home Assistant. The documentation reflects the latest stable version of Home Assistant. This particular syntax has changed in the October 2024 release.

../Frenck
