### ISSUE TITLE
Is there an option to add an attachement?

### ISSUE THREAD

**Issue by jaspov** [home-assistant/home-assistant.github.io#35255]
### Feedback

documentation does not mention the option. 

### URL

https://www.home-assistant.io/integrations/google_mail/

### Version

2024.10.2

### Additional information

see above

**Comment by frenck** [comment]
Hi there @jaspov 👋 

Unfortunately, there is no such option. Sorry!

../Frenck

**Comment by jaspov** [comment]
Hi Frenck,

Wow that is fast, thanks!
will continue looking for an alternative.

regards,
Jasper
