### ISSUE TITLE
Where are the downloads

### ISSUE THREAD

**Issue by rumoldus** [home-assistant/home-assistant.github.io#35259]
### Feedback

Hi, I am reading the installation instructions and all looks quite OK (moving to a new device, so some previous experience). This time I want to install HAOS, but nowhere do I find a download button. There is 'read more', but that is only indeed additional information. I do not see a download section in the top menu either. Of course it is there somewhere, but it could be somewhat more clear for nearsighted older near-boomers like me. Thanks.

### URL

https://www.home-assistant.io/installation/

### Version

2024.10.2

**Comment by frenck** [comment]
Which device are you trying to install on?

**Comment by rumoldus** [comment]
Dear Franck,Thanks for reacting so fast. The hardware is yet to arrive (stuck in DHL) but it is Intel based NUC type. I wanted to prepare a bootable USB already.Dankjewel!- Marcel Payens(from cell phone)Op 16 okt 2024 om 22:45 heeft Franck Nijhof ***@***.***> het volgende geschreven:﻿
Which device are you trying to install on?

**Comment by frenck** [comment]
@rumoldus Small tip: GitHub is very bad at handling responses via email (if you look at your response on GitHub you can see the mess 😬). I would recommend using the web interface instead.

Anyways, the instructions can be found here: <https://www.home-assistant.io/installation/generic-x86-64#install-home-assistant-operating-system>

There are two installation paths available. The download links are shown at the appropriate steps there as well.

../Frenck
