### ISSUE TITLE
Add mention of email in the HTML5 notification doc

### ISSUE THREAD

**Issue by thibaultmol** [home-assistant/home-assistant.github.io#35261]
### Feedback

I started to use the integration for the first time and I was (and frankly still am) VERY confused why an html push notification integration needs my emailadres. It would be nice if the docs explained this because currently it's not even mentioned anywhere

### URL

https://www.home-assistant.io/integrations/html5/

### Version

2024.10.2

**Comment by thibaultmol** [comment]
(also unrelated but: it seems like there is some funkyness to using it with Nabu Casa. I also can't get it working : https://community.home-assistant.io/t/remote-access-nabu-casa-push-notifications/107099/6 )
I got it setup but can't actually get any notifications get sent (probably because of similar issues but I can't figure out what to do). So maybe the docs need some stuff about Nabu Casa setups

**Comment by alexyao2015** [comment]
See this https://blog.mozilla.org/services/2016/08/23/sending-vapid-identified-webpush-notifications-via-mozillas-push-service/

The email itself isn't actually validated, so you could theoretically use any random email.

**Comment by thibaultmol** [comment]
Interesting, is there a way why home assistant doesn't just generate a random one for you then?

**Comment by alexyao2015** [comment]
That would be bad practice and against spec

**Comment by thibaultmol** [comment]
ok. so in that case I guess it's best to mention this in the docs and explain.

And maybe also worth looking into the problem with Nabu Casa users which might need some more configuring to get it working?
