### ISSUE TITLE
Google Nest / intergration home assistant 

### ISSUE THREAD

**Issue by sjaakie09** [home-assistant/home-assistant.github.io#35264]
### Feedback

I have the google nest thermostate. ive bought it a year ago and first it worked fine with home assistant. 

But since recently the google nest stopped working with home assistant. it stil works in the app.

whenever i try connecting the goolge nest to home assistant using the intergration i get a error in google cloud.
anyone else know whats the problem. am i correct that the api is been changed and not working atm if so when will it work again or what needs to be done to get it working in home assistant. 

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.10.2

**Comment by allenporter** [comment]
Hi, you're going to need to give more detail if you'd like assistance. You'll need to follow the instructions exactly. You can also review https://www.home-assistant.io/integrations/application_credentials/ -- however, this is not really a support issue channel, that's better to go to the community forums https://community.home-assistant.io/

**Comment by sjaakie09** [comment]
did anyon e have a fix?

**Comment by allenporter** [comment]
@sjaakie09 see my previous post
