### ISSUE TITLE
EcoVacst50pro is not working

### ISSUE THREAD

**Issue by kmsg0000** [home-assistant/home-assistant.github.io#35266]
### Feedback

Cleaning and other operation buttons do not work I'm attaching the file
[config_entry-ecovacs-01JADF3NW6QTMEA4GBWDR9FF0D.json](https://github.com/user-attachments/files/17414774/config_entry-ecovacs-01JADF3NW6QTMEA4GBWDR9FF0D.json)

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.10.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
