### ISSUE TITLE
Integration / Host 

### ISSUE THREAD

**Issue by Mfr1010** [home-assistant/home-assistant.github.io#35269]
### Feedback

Dear all, 

i experienced issues with the integration of Lupusec.

It seems that, no matter what information I enter in the initial integration dialogue (where i am asked for Host, User and password), i always get an "unexpected error". 

Is there any specific form or requirement for the host name? I am running out of ideas.

Best
Michael

### URL

https://www.home-assistant.io/integrations/lupusec/

### Version

2024.10.2

**Comment by suaveolent** [comment]
@Mfr1010 is there anything in the logs on why the error occurs? 

Which system do you have?

**Comment by Mfr1010** [comment]
Sorry for bothering, found the issue and was able to resolve it myself. Thanks for your work!
