### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by DelanoLima** [home-assistant/home-assistant.github.io#35273]
### Feedback

I suggest using "- logical_operator: or" instead of "- condition: or". In my opinion it is more user-friendly.

### URL

https://www.home-assistant.io/docs/automation/action/

### Version

2024.10.2

**Comment by frenck** [comment]
Hi there @DelanoLima 👋 

Thanks for the suggestion. We are not planning on making that syntax change, however, we do have a short hand syntax available you might like.

`- or:`

This short-hand is available for `or`, `and`, and `not`.

See also here: https://www.home-assistant.io/docs/scripts/conditions/#logical-conditions

../Frenck
