### ISSUE TITLE
MELCloud

### ISSUE THREAD

**Issue by Ashleyde42** [home-assistant/home-assistant.github.io#35275]
### Feedback

This only tells me how to add MELCloud integration.  How do I follow instructions on screen which ask for userid and password.  Where do I get these from?
Ash

### URL

https://www.home-assistant.io/integrations/melcloud/

### Version

2024.10.2

**Comment by frenck** [comment]
Hi there @Ashleyde42 👋 

It is the same credentials as you would use to log into your MELCloud applications/apps.

https://www.melcloud.com/

Using those will grant this Home Assistant integration access to your MELCloud account.

../Frenck

**Comment by Ashleyde42** [comment]
But when I go to Integration entries i press ADD ENTRY.  Then I enter my userid and password and i get a response fro MELCLOUD That the integration is already configured for this email. Access toekn has been refreshed.

**Comment by Ashleyde42** [comment]
But I do not see any of my two air conditioners showing up.  How do I add the air conditioners? Ash

**Comment by frenck** [comment]
It sounds like you are in need for support or want to report an issue for this integration.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). 

If you want to report an issue with an Home Assistant integration, please report them here:

<https://github.com/home-assistant/core/issues>

You are more likely to get the answer you are looking for in those places.

../Frenck
