### ISSUE TITLE
EcoVacs  t50pro is not working

### ISSUE THREAD

**Issue by kmsg0000** [home-assistant/home-assistant.github.io#35272]
### Feedback

Cleaning and other operation buttons do not work I'm attaching the file
[config_entry-ecovacs-01JAE9PZ13J0N3PQXZBXRQ4DBC1.json](https://github.com/user-attachments/files/17426123/config_entry-ecovacs-01JAE9PZ13J0N3PQXZBXRQ4DBC1.json)

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.10.2

**Comment by mib1185** [comment]
- duplicate of your own report #35266
