### ISSUE TITLE
Tile Card Feature: confirmation

### ISSUE THREAD

**Issue by Fjury** [home-assistant/home-assistant.github.io#35280]
### Feedback

I wish it would be possible to confirm unlocking the door.

I know this is possible using buttons tap_action. 

type: tile
entity: lock.danalock
features: 
 - type: lock-commands
    confirmation:
       - open
          confirmation_text: „open Door?“
       - close
          confirmation_text: „close Door?“

Maybe you can add this to a later release :-)

### URL

https://www.home-assistant.io/dashboards/features/

### Version

2024.10.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
