### ISSUE TITLE
Integration no longer works

### ISSUE THREAD

**Issue by ASTPlatinum** [home-assistant/home-assistant.github.io#35286]
### Feedback

Maybe you could check the bugs section and find out for yourself. I'm not writing it here!

### URL

https://www.home-assistant.io/integrations/icloud/

### Version

2024.10.3

**Comment by Stoepf72** [comment]
Same for me as well. Deleted iCloud folder but want work anymore. Authorization is not possible

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
