### ISSUE TITLE
Rooms to Clean

### ISSUE THREAD

**Issue by RobMou** [home-assistant/home-assistant.github.io#35287]
### Feedback

So far I have googled and googled but nothing found. The old integration (HACS) I can see has the possibility to set up room cleaning, but not this new one, there are no instructions on how to do it anyway, why would you replace an integration that worked with a new integration that has less core functionality or at least way worse documentation? Then a dude ask the same question as me, and gets some explanation with A=0 B=1, but the problem is, app does not give the room number anymore, so your new integration is now more or less a start stop button for the vacuum, could you please help get more instuctions on using zone cleaning with your integration, and not some so so workaround… or at least make the old integration available on HACS again…

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.10.3

**Comment by frenck** [comment]
Hi there @RobMou 👋 

Let me start with: This is not HACS; we do not aim to deliver the same as every custom integration does. In the Home Assistant project we try to maintain standards across all integrations, meaning that not every functionality found in custom integrations will find its way to the built-in integrations. It could also simply be the fact it hasn't been built yet 🤷 

I've looked at the source code and didn't find any related functionality to what you are asking for. This means the documentation is correctly not listing anything about it.

> or at least make the old integration available on HACS again…

The Home Assistant project doesn't make, maintain or publish custom integrations. You are asking that question in the wrong place.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck

**Comment by RobMou** [comment]
Frenck
This integration is as far as I know the old Deeboot 4 Home Assistant that existed on HACS. This integration was taken down, because it was made a part of home assistant, it says so directly on the GitHub page for Deebot 4 Home Assistant. So a working integration has been removed from HACS for this integration that does not have CORE functionally. An on off button is really not what most are looking for integrating the vacuum in the smart home for. The answer you provide is not really covering what I as, why remove the Deebot 4 Home Assistant, and replace it with this?

**Comment by frenck** [comment]
> This integration is as far as I know the old Deeboot 4 Home Assistant that existed on HACS. 

@RobMou yes, it seem that way. The contribution towards our core repository was most likely based on that. 

> This integration was taken down, because it was made a part of home assistant, it says so directly on the GitHub page for Deebot 4 Home Assistant.

That is an decision for the custom integration author, not the Home Assistant project. We don't maintain or create custom integrations. Your comment therefore isn't fitting in our project.

> r. The answer you provide is not really covering what I as, why remove the Deebot 4 Home Assistant, and replace it with this?

You will not get that answer here, as that isn't part of our project. We don't control that stuff, it is a third-party thing. You are barking up the wrong tree here 😄 

../Frenck

**Comment by RobMou** [comment]
Dear Frenck 

From the Deebot 4 Home Assistant page 

"This integration has been available directly in the Home Assistant core since version 2024.2.0. For more information, please check out the Ecovacs HA documentation <https://www.home-assistant.io/integrations/ecovacs/>.”

“THIS” in the first sentence referring to the fact that it is the same integration, just directly in home assistant and not through HACS. So can you confirm that what Deebot 4 Home assistant writes on the GitHub page for that is false?

One thing is for certain, the two integrations are not the same, and how do I get the old integration, because the native one, really does not work.


/Mads
