### ISSUE TITLE
Switchbot Light strip support

### ISSUE THREAD

**Issue by jburkett617** [home-assistant/home-assistant.github.io#35285]
### Feedback

I opened my home assistant and I noticed that the switchbot light strip i have had connect to home assistant for awhile via this integration no longer works, it says its been disabled. Does this mean that the light strip is no longer compatible with this intergration?

### URL

https://www.home-assistant.io/integrations/switchbot/

### Version

2024.10.3

**Comment by frenck** [comment]
Hi there @jburkett617 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. If you'd like to report an issue, please report it here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
