### ISSUE TITLE
Doc content does not match ASUSWRT integration's availiable Options.

### ISSUE THREAD

**Issue by vb7445** [home-assistant/home-assistant.github.io#35291]
### In the Documentation under the **Options** section these options are listed:
**Consider home**
Number of seconds that must elapse before considering a disconnected device not at home.
**Track unknown**
Enable this option to track also devices that do not have a name. Name will be replaced by mac address.
**Interface**
The interface that you want statistics from (e.g. eth0,eth1 etc).
**Dnsmasq**
The location in the router of the dnsmasq.leases file.
**Require IP**
If devices must have IP (this option is available only for access point mode).

### The only Options actually available in the Integration are:
**Consider home**
Number of seconds that must elapse before considering a disconnected device not at home.
**Track unknown**
Enable this option to track also devices that do not have a name. Name will be replaced by mac address.

### URL

https://www.home-assistant.io/integrations/asuswrt/

### Version

2024.10.3

**Comment by ollo69** [comment]
The other 3 options are available only when you configure integration using SSH or Telnet protocol, HTTP(S) do not require that options.

**Comment by vb7445** [comment]
Okay.
I forget, but I guess I configured the protocol when I installed the integration initially and it can’t be changed afterwards? Yes/no?

-Phil
***@***.***

On Oct 19, 2024, at 9:48 AM, ollo69 ***@***.***> wrote:

﻿

The other 3 options are available only when you configure integration using SSH or Telnet protocol, HTTP(S) do not require that options.

**Comment by ollo69** [comment]
Used protocol is on initial integration configuration. If you wand to change it, you must delete and then reconfigure integration.

**Comment by vb7445** [comment]
Thanks. Perhaps some clarity in the docos would be prudent, or not, up to you.

**Comment by vb7445** [comment]
I guess many developers still resist comprehensiveness in the documentation. Being a retired developer myself I know that docos are not the fun part of the job. Might as well close this out.
