### ISSUE TITLE
One contract , 2 floors separate zones

### ISSUE THREAD

**Issue by AndreiDidenko1970** [home-assistant/home-assistant.github.io#35300]
### Feedback

Hi! Sorry, I'm not a programmer. I have set up your integration to myself in the HA , everything is very good - thank you very much!
Maybe you can help me? My contract with (the house) has two floors, these are two zones. Each floor can be separately secured as ( at home and not at home) . That is, I have two sliders.. I'll show you in the screenshot. You can add a second slider for the second floor. I can help you and give you temporary access to my Prosegur webpage. Well, there is also a 360 degree camera. Can we cooperate?! thank you)))

https://github.com/user-attachments/assets/bd3b638c-867f-4a85-aecf-bb62e6d80b9f

![IMG_A1C82BDB5DAE-1](https://github.com/user-attachments/assets/1817b691-0e0d-4551-b3c1-bbe0e69ff44e)
![IMG_DE1F8621DC53-1](https://github.com/user-attachments/assets/c449ad12-fa6e-4b97-baa1-e3d060543ab1)

https://github.com/user-attachments/assets/0c6962f1-47b7-458b-9cf5-fb8ee2c94415

### URL

https://www.home-assistant.io/integrations/prosegur/

### Version

2024.10.3

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
