### ISSUE TITLE
Cleaning start button stop button stop button not working on ecovacs t50pro I bought in China

### ISSUE THREAD

**Issue by kmsg0000** [home-assistant/home-assistant.github.io#35316]
### Feedback

I can provide the records Please help me I tried to spin the api but neither mitmproxy,sharkwire worked I think it is decrypting
[config_entry-ecovacs-01JAE9PZ13J0N3PQXZBXRQ4DBC (2).json](https://github.com/user-attachments/files/17456399/config_entry-ecovacs-01JAE9PZ13J0N3PQXZBXRQ4DBC.2.json)

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.10.3

### Additional information

I can provide the records Please help me I tried to spin the api but neither mitmproxy,sharkwire worked I think it is decrypting[](url)

**Comment by mib1185** [comment]
It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:
https://github.com/home-assistant/core/issues
Thanks! 👍
