### ISSUE TITLE
AWS (Alexa) configuration can use ports other than 443

### ISSUE THREAD

**Issue by kiat-huang** [home-assistant/home-assistant.github.io#35311]
### Feedback

The help page is very useful - it walked me through getting me setup as intended.  Great work!

One thing I noticed though is that the assertion that one's site HA must be accessible by SSL port 443  for AWS/Alexa to integrate, is not correct. I use 8443 and made it work by appending ":8443" to the FQDN ,(my dynamic DNS) in all the AWS configs noted in the page.

### URL

https://www.home-assistant.io/integrations/alexa.smart_home/

### Version

2024.10.3

**Comment by jbouwh** [comment]
Okay, that is good to hear. The last year this explains was a bit unpredictable.

**Comment by jbouwh** [comment]
~@kiat-huang Can you open a PR (targetting the current branch) with the changes you suggest?~
