### ISSUE TITLE
"total commits to the Home Assistant orga"

### ISSUE THREAD

**Issue by reedy** [home-assistant/home-assistant.github.io#35326]
### Feedback

https://github.com/home-assistant/home-assistant.io/blob/current/source/developers/credits.markdown?plain=1 uses `total commits to the Home Assistant orga`; I don't think `orga` is a common abbreviation, `org` is more common...

https://github.com/home-assistant/hass-release/pull/60 to fix it in the script and then can be updated in https://github.com/home-assistant/home-assistant.io/issues/35247...

### URL

https://www.home-assistant.io/developers/credits/

**Comment by frenck** [comment]
Thanks, @reedy. However, there is no need to create issues for PRs.

Closing this one for that reason 👍 

../Frenck
