### ISSUE TITLE
S86WMUPR support?

### ISSUE THREAD

**Issue by soupman98** [home-assistant/home-assistant.github.io#35324]
### Feedback

Will this support the AprilAire S86WMUPR thermostat - I really would like a somewhat native humidity / dehumidifier controll

### URL

https://www.home-assistant.io/integrations/aprilaire/

### Version

2024.10.3

### Additional information

S86WMUPR

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
