### ISSUE TITLE
bi weekly setting

### ISSUE THREAD

**Issue by nevrenuf1** [home-assistant/home-assistant.github.io#35344]
### Feedback

Hi i was wondering if there is a way to do a bi-weekly event addition.
Thank you
Dickie

### URL

https://www.home-assistant.io/integrations/local_calendar/

### Version

2024.10.3

**Comment by frenck** [comment]
Hi there @nevrenuf1 👋 

Unfortunately, our local calendar currently does not allow such a recurring period.

![CleanShot 2024-10-23 at 08 55 10@2x](https://github.com/user-attachments/assets/c29d09db-7218-42b2-9993-085b44233674)

../Frenck
