### ISSUE TITLE
How do I refresh the login for the SeventeenTrack integration?

### ISSUE THREAD

**Issue by felafel** [home-assistant/home-assistant.github.io#35356]
### Feedback

DEBUG (MainThread) [pyseventeentrack.profile] Packages response: {'Code': -6, 'Message': "You haven't logged in for a long time, for your account security, please login again."}

I have logged in on another computer so it is not that I have not logged in anywhere in a long time.

### URL

https://www.home-assistant.io/integrations/seventeentrack/

### Version

2024.10.3

**Comment by frenck** [comment]
Hi there @felafel 👋 

There is currently no way to reconfigure the credentials for this integration. The only solution at this moment in time, is to remove and re-add the integration.

../Frenck

**Comment by felafel** [comment]
Thanks for the reply.  I actually deleted the service and then added it again.  Works again but I needed to choose the "new" service in my automation.
