### ISSUE TITLE
Documentation provides non-working example

### ISSUE THREAD

**Issue by hifigraz** [home-assistant/home-assistant.github.io#35357]
### Feedback

The example is not working.

![image](https://github.com/user-attachments/assets/3c4c60fe-e37a-4bc7-8ddb-e9939ccaacd9)

### URL

https://www.home-assistant.io/integrations/media_source/

### Version

2024.10.3

**Comment by frenck** [comment]
`robert` is not a valid key to use (and also not in our documentation example).

The message you see, is thus correct and a valid indicator your YAML is incorrect.

../Frenck
