### ISSUE TITLE
it works with Kasa Cameras ?

### ISSUE THREAD

**Issue by Roberto00001** [home-assistant/home-assistant.github.io#35354]
### Feedback

I can´t do it work with Kasa cameras.

### URL

https://www.home-assistant.io/integrations/emulated_kasa/

### Version

2024.10.3

### Additional information

I can´t do it work with Kasa cameras.

**Comment by kbickar** [comment]
This only shares energy usage over the network using the standard protocol Kasa devices use.  If the Cameras aren't using the same protocol it might not work

**Comment by frenck** [comment]
As per the integration description, this integration isn't aimed at cameras:

> The Emulated Kasa integration emulates a TP-Link Kasa smart plug and announces the power usage of configured devices to any that might request it on the local network.

../Frenck
