### ISSUE TITLE
It stops working it starts working as soon as i restart HA

### ISSUE THREAD

**Issue by jigarashah** [home-assistant/home-assistant.github.io#35373]
### Feedback

It stops working after a while. if i restart HA it starts working . I have docker img on qnap

### URL

https://www.home-assistant.io/integrations/wiz/

### Version

2024.10.3

### Additional information

suggest if u need logs. i am not expert on HA but can get with instruction

**Comment by frenck** [comment]
Hi there @jigarashah 👋 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
