### ISSUE TITLE
Recomment ecowitt-proxy-addon

### ISSUE THREAD

**Issue by n0nk** [home-assistant/home-assistant.github.io#35379]
### Feedback

Currently there's a suggestion to use NGINX TLS Proxy Add-on. In my opinion the better solution is 
https://github.com/ChrisRomp/addon-ecowitt-proxy
Instead of exposing the whole HA via HTTP it is forwarding HTTP traffic from ecowitt Gateway to HA.

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2024.10.3

**Comment by frenck** [comment]
Thanks for the suggestion @n0nk 👍 

However, we cannot recommend the use of third-party integrations, add-ons or plugins in our documentation.

../Frenck
