### ISSUE TITLE
17Track not updating

### ISSUE THREAD

**Issue by Slimhaven** [home-assistant/home-assistant.github.io#35389]
### Feedback

17Track worked great until first package delivered and hasn't updated since. Seems to be set up correctly and this is an awesome addition if it would update. It would even be better if it would be able to pickup the orders from the different carriers instead of having to load them individually.

### URL

https://www.home-assistant.io/integrations/seventeentrack/

### Version

2024.10.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
