### ISSUE TITLE
Belkin Wemo - Integration Documentation

### ISSUE THREAD

**Issue by bamcauliffe** [home-assistant/home-assistant.github.io#35395]
### Feedback

In the information about the Belkin Wemo - Integration, it mentions about adding static IP addresses to the configuration.yaml file. I have looked in my file and found there was very very little in there, with only 10 lines of text. There is no text containing "Wemo" in this file. My configuration.yaml does include;
!include_dir_merge_named themes
!include Automations.yaml
!inlcude Scripts.yaml
!include Scenes.yaml

Does the current Wemo Integration still put the Integration configuration (like static IPs) in the configuration.yaml file? If so I need to get to the bottom of why it is not in mine. 
I have seen some discussions on the Home Assistant Community about "Configuration.yaml file empty". 
If the location of the configuration & the location to put the static IP addresses has changed, for the Wemo Integration, then I request the new location of the configuration & the process to add Static IP addresses be added to the documentation, if this is still an appropriate way to handle Wemo device on a different network.  

I also wanted to confirm the wording regarding the firewall rules and port 8989. Based on the wording, I assume that this port is for the destination, rather than the source. Is this correct?

Thank you for the work that you have done on the Wemo Integration.

### URL

https://www.home-assistant.io/integrations/wemo/

### Version

2024.10.4

**Comment by bamcauliffe** [comment]
Sorry, I thought that the configuration.yaml file would have a bunch of stuff in there from some or all integration.
I now understand that this file is just to add customizations to.
I have been able to add the required information to the configuration.yaml file and get the Wemo devices added and working.
So item can be closed.

**Comment by esev** [comment]
@home-assistant close
