### ISSUE TITLE
Pb with 

### ISSUE THREAD

**Issue by Titi9562** [home-assistant/home-assistant.github.io#35397]
### Feedback

Thank you for this integration. 
The spa is regularly no longer accessible by home assistant. I then have to delete the entry and then add it again.
However, the IP address has not changed. 
What should I do? 
THANKS
![image](https://github.com/user-attachments/assets/092e85af-e4af-4903-819c-aba20d890c20)

### URL

https://www.home-assistant.io/integrations/balboa/

### Version

2024.10.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
