### ISSUE TITLE
APS Gives Invalid Authentication error

### ISSUE THREAD

**Issue by kmcelroy** [home-assistant/home-assistant.github.io#35390]
### Feedback

No matter how many times I enter my login credentials for my Arizona Public Service account, triple checking the correct spelling/capitalization, etc. I get “Invalid Authentication” and cannot add the integration.

### URL

https://www.home-assistant.io/integrations/opower/

### Version

2024.10.4

**Comment by xpucu** [comment]
Same here. I entered the exact same credentials at http://aps.opower.com and they work, but the integration says they are invalid: 

 ``` 
File "/usr/local/lib/python3.12/site-packages/opower/utilities/aepbase.py", line 141, in async_login
    raise InvalidAuth("Username/Password are invalid")
opower.exceptions.InvalidAuth: Username/Password are invalid

```

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
