### ISSUE TITLE
Inverter Temperature

### ISSUE THREAD

**Issue by joernbeutel** [home-assistant/home-assistant.github.io#35409]
### Feedback

Hi, can the inverter temperature please be added to the integration?
However, the integration works, some data need helpers to be converted in order to match working with other items f.e.building group sensors.
Thanks a lot
Joe

### URL

https://www.home-assistant.io/integrations/sma/

### Version

2024.10.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
