### ISSUE TITLE
manual install of pycomfoconnect required?

### ISSUE THREAD

**Issue by MarcDorval** [home-assistant/home-assistant.github.io#35401]
### Feedback

One point is unclear: is it required to manually install [pycomfoconnect ](https://github.com/michaelarnauts/comfoconnect/tree/master/pycomfoconnect) to use the integration?

### URL

https://www.home-assistant.io/integrations/comfoconnect/

### Version

2024.10.4

### Additional information

I end up with the notification below 
![image](https://github.com/user-attachments/assets/739ddb20-ccdf-4a2a-87d8-69bd2775b855)

**Comment by frenck** [comment]
Manually installation of Python dependencies is never needed in Home Assistant. It seems like you've made an error in writing out the YAML configuration.


We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
