### ISSUE TITLE
I'd like to install SmartThings plugin before I install HAOS to my old laptop

### ISSUE THREAD

**Issue by jfgoodhew1** [home-assistant/home-assistant.github.io#35403]
### Feedback

I haven't installed my HA yet, I'm installing to an old Windows laptop and just want to add all the plugins before I start the install. I'll have to connect to it after completion and install this one

### URL

https://www.home-assistant.io/integrations/smartthings/

### Version

2024.10.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
