### ISSUE TITLE
APS (Arizona Public Service)

### ISSUE THREAD

**Issue by J-Fads** [home-assistant/home-assistant.github.io#35408]
### Feedback

Listed as works with Opower but it is not part of the drop-down list and therefore APS customers cannot register.
![image](https://github.com/user-attachments/assets/7f46ed41-8afa-423d-a84f-ec1a5c857f58)

### URL

https://www.home-assistant.io/integrations/aps/

### Version

2024.10.4

**Comment by tronikos** [comment]
It's there for me.
<img width="365" alt="image" src="https://github.com/user-attachments/assets/0ecc4cf3-650a-4240-b0ed-8a828431696a">

My guess is you are using the Core installation (Manual installation using Python virtual environment) and you need to upgrade the opower package.

**Comment by tronikos** [comment]
Even after updating the opower package you will likely not be able to login. There is an open issue for APS.

**Comment by J-Fads** [comment]
Was able to get it by adding integration as opposed to doing it manually -
"To add the Arizona Public Service (APS) integration to your Home Assistant instance, use this My button:"

Don't know why, but sometimes giving it the side eye helps...
