### ISSUE TITLE
More guidance needed on how to customize climate presets

### ISSUE THREAD

**Issue by illright** [home-assistant/home-assistant.github.io#35413]
### Feedback

There is a concept of climate presets like "home", "away", "night", etc., which is exposed through the Thermostat card, and is really nice, but the default temperatures are not to my liking. I'd like to customize the temperatures of existing presets or make my own, but I can't find any information in the docs on how to do that.

I would like to have a section that would point me towards the right settings in `configuration.yaml` to customize the default presets or add my own

### URL

https://www.home-assistant.io/integrations/climate/

### Version

2024.10.4

**Comment by illright** [comment]
I found a comment on a closed issue that says that these presets are defined by the device, not by home assistant: https://github.com/home-assistant/home-assistant.io/issues/17153#issuecomment-808855551

Fair, I can confirm that, but it would be really nice to add this information to the docs, otherwise I found myself really scratching my head when trying to deduce where to go

**Comment by gjohansson-ST** [comment]
What part of the documentation would hint that you can define your own presets?

**Comment by illright** [comment]
I'm not sure I understand the question. Do you mean "what led you to believe that defining custom presets is possible"? In this case, nothing, I just assume that there can be as many presets as desirable

**Comment by gjohansson-ST** [comment]
You can make your own presets using `scene`, `automation` or `script` but you can't expand the `climate` entity itself with custom presets.
Probably `scene.apply` is the main way to go https://www.home-assistant.io/integrations/scene/#applying-a-scene-without-defining-it
Closing this as it's not an issue in itself, possibly could be a feature request which then should be dealt with in our [community forum](https://community.home-assistant.io/)

**Comment by illright** [comment]
I'd like to have a note in the docs that says that the climate entity itself is responsible for presets, and not Home Assistant. This issue was not intended as a feature request for customizing presets, but rather as a request to add some information about them to the docs that is now scattered in closed issues on this topic. I think this should stay open

**Comment by gjohansson-ST** [comment]
Could you be a bit more specific about what you're missing.
I get that we could clarify that presets are provided by the entity itself and is not something the user can provide on his own. But where should it go into the docs you mean and something must have triggered you to think it was maybe possible so something might have to be "rewritten" to be clarified in such case?

**Comment by illright** [comment]
Ideally, I'd like a whole prominent section called "Climate presets" in [the docs page of the climate integration](https://www.home-assistant.io/integrations/climate/), much like there is already an "HVAC state" section. From reading this entire page and other UI terminology, I've set myself up to expect climate presets to be a concept that would have a definition and applicability boundaries, so having an easy-to-locate section about it would probably curb all my insecurities.
