### ISSUE TITLE
Please Add a writing function 

### ISSUE THREAD

**Issue by servussepp** [home-assistant/home-assistant.github.io#35414]
### 

Please add a function for setting values, such as “warm water adjustment.” If there is surplus power from the solar panels, the system could heat up to store the extra energy.

### URL

https://www.home-assistant.io/integrations/wolflink/

### Version

2024.10.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
