### ISSUE TITLE
tuya无法反馈设备状态/ tuya cannot feedback device status

### ISSUE THREAD

**Issue by ptcar** [home-assistant/home-assistant.github.io#35418]
### Feedback

最近涂鸦无法反馈状态，不知道是涂鸦服务器的问题，还是homeassistant的问题？
Tuya has been unable to report status recently. Is it a problem with the Tuya server or HomeAssistant?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.10.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
