### ISSUE TITLE
Provide in de documentation if Matter is used

### ISSUE THREAD

**Issue by Travelbacon** [home-assistant/home-assistant.github.io#35420]
### Feedback

Could the documentation specify when Matter isn’t being used? 

The reason is that Home Assistant (HA) now includes built-in (beta) support for Matter, but this integration can only function if no other add-on is running a Matter server. Currently, it’s unclear in the documentation whether Hue connects to the bridge via Matter. Additionally, the Hue integration itself functions as a Matter server.

### URL

https://www.home-assistant.io/integrations/hue/

### Version

2024.10.4

**Comment by marcelveldt** [comment]
I'm sorry but I didn't understand your report at all. Can you describe in more detail what is wrong?

**Comment by Travelbacon** [comment]
> I'm sorry but I didn't understand your report at all. Can you describe in more detail what is wrong?

I´ve rewritten my issue in a more readable piece of text.

**Comment by frenck** [comment]
Hi there @Travelbacon 👋 

Hue won't be a problem, as it is not an add-on. 

../Frenck
