### ISSUE TITLE
Govee Scene Control Ability

### ISSUE THREAD

**Issue by mwaurch** [home-assistant/home-assistant.github.io#35425]
### Feedback

Wish for future integration with ability to select scenes from govee in HA from a preset list. Like Amazon Alexa can. 
![IMG_0341](https://github.com/user-attachments/assets/1f4873c5-875a-44c8-b191-08c1a67decca)

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.10.4

**Comment by cyberchan** [comment]
+1

**Comment by frenck** [comment]
Oh hi there @mwaurch @cyberchan 👋 

Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
