### ISSUE TITLE
Dual Fuel settings

### ISSUE THREAD

**Issue by Gree-G** [home-assistant/home-assistant.github.io#35445]
### Feedback

Is there a way to set a heat source from HA for Nest?
It would be greatly appreciated.
I want to use the excess of electricity from the Tesla batteries, but to stop before depletion, so no power is drained from the grid.
I have data pulled from batteries, but no way to switch the heat source on the Nest.
I see it is somehow implemented here: https://github.com/gboudreau/nest-api/blob/master/examples.php

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.10.4

**Comment by allenporter** [comment]
Hi not sure I totally follow the question and I suspect the answer is no, but this is not really a support forum. You can definitely post in the community forums https://community.home-assistant.io/ or home assistant discord.

Respectfully closing.
