### ISSUE TITLE
This documentation is incorrect

### ISSUE THREAD

**Issue by cjramseyer** [home-assistant/home-assistant.github.io#35441]
### Feedback

The documentation specifically states to add

scene:
  - platform: lifx_cloud
    token: lifxtoken

This would be for a specific scene, not the lifx cloud integration, and is also incorrect as this would require name + entities etc.
Both need to be correct since the lifx_cloud integration cannot currently be added from the UI

### URL

https://www.home-assistant.io/integrations/lifx_cloud/

### Version

2024.10.4

**Comment by frenck** [comment]
Hi there @cjramseyer 👋 

I have checked the code in the integration against the documentation, and concluded it is actually matching.

This integrations only provides scenes, and since it is a legacy integration, the configuration still uses a very old YAML style format.

../Frenck
