### ISSUE TITLE
can I use this integration to send tcp command

### ISSUE THREAD

**Issue by sukumarkonduru** [home-assistant/home-assistant.github.io#35459]
### Feedback

I need to send command upon user clicking on increase/decrease volume.  As sensor it worked, but it will keep increasing volume. Is it possible to  enhance to be able to use to send command upon user clicking to use in script or service. Apprecite it.

### URL

https://www.home-assistant.io/integrations/tcp/

### Version

2024.10.4

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
