### ISSUE TITLE
change domain option 

### ISSUE THREAD

**Issue by FrankAMS** [home-assistant/home-assistant.github.io#35450]
### Feedback

I'd like to use the integration, I am on a Dutch portal from ista (mijn.ista.com) which looks like is has the same data access as ecotrend. However I can not use this integration, since it seems to ecotrend.ista.com which I assume is the german login portal.
Would it be possible to add access through mijn.ista.com domain to the integration?

### URL

https://www.home-assistant.io/integrations/ista_ecotrend/

### Version

2024.10.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
