### ISSUE TITLE
Enable and disable routing

### ISSUE THREAD

**Issue by Meppies** [home-assistant/home-assistant.github.io#35465]
### Feedback

Is it possibe to add enabling and disabling of route route rules? On this way you can route your tv to different vpn tunnels.

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.10.4

**Comment by ovsims** [comment]
not sure if this is proper to second this request. I used to be able to toggle traffic rules before but now it says it's no longer supported. I have no idea what update broke the functionality but it would be great to get that back

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
