### ISSUE TITLE
The documentation is outdated

### ISSUE THREAD

**Issue by Obicom** [home-assistant/home-assistant.github.io#35466]
### Feedback

I try to use piper in automation and follwed the documentation but it doesn't work. I am not able to pick a media after I select mediaplayer instance. Please double check and adapt the documentation.

### URL

https://www.home-assistant.io/voice_control/using_tts_in_automation/

### Version

2024.10.4

**Comment by Obicom** [comment]
I try to choose play media:
![image](https://github.com/user-attachments/assets/5b1fc875-75d2-4682-8502-fac962a15842)
and if I selct the mediaplayer for one of my alexas it says:
![image](https://github.com/user-attachments/assets/ba20f01a-344f-4a4f-9be1-37f3b1c03af0)

**Comment by frenck** [comment]
It seems to be correct and working fine. 

In the first screenshot you van pick a media, in the second you select an device that doesn't support that.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
