### ISSUE TITLE
SharkIQ

### ISSUE THREAD

**Issue by srmora** [home-assistant/home-assistant.github.io#35460]
### Feedback

it wont allow me to login suing my shark credentials.. it worked in the past.  Did Shark change it authentication method? Thanks.. 

### URL

https://www.home-assistant.io/integrations/sharkiq/

### Version

2024.10.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
