### ISSUE TITLE
Tank A Level (unsupported)

### ISSUE THREAD

**Issue by Horinajiri** [home-assistant/home-assistant.github.io#35476]
### Feedback

Is it possible to add a level sensor to your integration? Your integration sees it but doesn't assign any entities to it. Thank you.

[tuya-87d0ea7abce7fea6c10dbd986e8a8150-Dešťovka-cd2be83201d46a7d035ba7e6012a45de.json](https://github.com/user-attachments/files/17568052/tuya-87d0ea7abce7fea6c10dbd986e8a8150-Destovka-cd2be83201d46a7d035ba7e6012a45de.json)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.10.4

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
