### ISSUE TITLE
Unclear which pi image to use for Zero, Zero 2, etc

### ISSUE THREAD

**Issue by warpling** [home-assistant/home-assistant.github.io#35484]
### Feedback

As a pi noob, it took some work to figure out which image to use on my pi zero 2. Since it's a pretty new piece of hardware I almost wrongly assumed the latest pi version (5) would be correct. 

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.10.4

**Comment by ghost** [comment]
Based on https://community.home-assistant.io/t/raspberry-pi-zero-2-w/351137, would assume that even though the CPU would probably be fine, the RAM is gonna be the bottleneck, so I would assume that the RAM restrictions is the reason they don't have/list a reason why there isn't a listed version.

"(Raspberry Pi 3 Model B is ok to get started, but the Model A does not have enough RAM)." from https://www.home-assistant.io/installation/raspberrypi/ leads me to assume this as well.

**Comment by frenck** [comment]
> it took some work to figure out which image to use on my pi zero 2

Those are not supported, so there is no correct image for it.

../Frenck
