### ISSUE TITLE
CCM15 Not working properly

### ISSUE THREAD

**Issue by MaxwellEdisons** [home-assistant/home-assistant.github.io#35504]
### Feedback

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Shanghai",
    "os_name": "Linux",
    "os_version": "6.6.54-haos",
    "supervisor": "2024.10.3",
    "host_os": "Home Assistant OS 13.2",
    "docker_version": "27.2.0",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.8.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "deebot": {
      "documentation": "https://deebot.readthedocs.io/integrations/home-assistant",
      "version": "v0.0.0",
      "requirements": [
        "deebot-client==5.1.0",
        "numpy>=1.23.2"
      ]
    },
    "bemfa": {
      "documentation": "https://github.com/larry-wong/bemfa",
      "version": "1.4.0",
      "requirements": [
        "paho-mqtt==1.6.1"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "xiaomi_miot": {
      "documentation": "https://github.com/al-one/hass-xiaomi-miot",
      "version": "0.7.21",
      "requirements": [
        "construct>=2.10.68",
        "python-miio>=0.5.12",
        "micloud>=0.5"
      ]
    },
    "xiaomi_gateway3": {
      "documentation": "https://github.com/AlexxIT/XiaomiGateway3",
      "version": "4.0.6",
      "requirements": [
        "zigpy>=0.52.3"
      ]
    },
    "ds_air": {
      "documentation": "https://github.com/mypal/ha-dsair",
      "version": "1.3.5",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "ccm15",
    "name": "Midea ccm15 AC Controller",
    "codeowners": [
      "ocalvo"
    ],
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/ccm15",
    "iot_class": "local_polling",
    "requirements": [
      "py-ccm15==0.0.9"
    ],
    "is_built_in": true
  },
  "setup_times": {
    "null": {
      "setup": 2.6153000362683088e-05
    },
    "01JBHPQF36KNWF1WFWAEZ4WKVP": {
      "wait_import_platforms": -0.9916782959999182,
      "wait_base_component": -0.001575316000071325,
      "config_entry_setup": 1.250759374000154
    }
  },
  "data": {}
}

I added 192.168.110.200 through the configuration page, and it was added successfully, but it said that the device could not be discovered. I can access http:--192.168.110.200 normally through the browser

### URL

https://www.home-assistant.io/integrations/ccm15/

### Version

2024.10.4

**Comment by frenck** [comment]
Hi there @MaxwellEdisons 👋 

It seems like you want to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
