### ISSUE TITLE
Energy distribution card and section dashboard

### ISSUE THREAD

**Issue by pvklink** [home-assistant/home-assistant.github.io#35507]
### Feedback

The current Energy distribution card is only configurable via yaml.
Is it possible to adjust this card so it is configurable via the the way the sections dashboard and it cards are setup

### URL

https://www.home-assistant.io/dashboards/energy/

### Version

2024.10.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
