### ISSUE TITLE
please add support for command signing

### ISSUE THREAD

**Issue by cramlr** [home-assistant/home-assistant.github.io#35513]
### Feedback

very disappointed that the ability for command signing isn't supported.  It would be nice to do a quick check during install/config.

### URL

https://www.home-assistant.io/integrations/tesla_fleet/

### Version

2024.10.4

**Comment by Bre77** [comment]
The intergration documentation is clear that this isnt currently supported.
It was a very difficult thing to get implemented, however the PR for this has been open for 2 weeks.
https://github.com/home-assistant/core/pull/128407

If you want something that works sooner, use [Teslemetry](http://teslemetry.com/) or Tessie

**Comment by Bre77** [comment]
@home-assistant close

**Comment by cramlr** [comment]
Thank you! I know security encryption and identity are very complex!It’s moot hopefully, but adding a “not yet implemented” vs “check the docs” would have saved me time and angst.  MarcOn Oct 31, 2024, at 12:56 PM, Brett Adams ***@***.***> wrote:﻿
@home-assistant close
