### ISSUE TITLE
Missing server for holland

### ISSUE THREAD

**Issue by KarelQuick** [home-assistant/home-assistant.github.io#35526]
### Feedback

I am missing the server for holland: https://server.growatt.com
Please add it to the list and let me login to my account.

### URL

https://www.home-assistant.io/integrations/growatt_server/

### Version

2024.10.4

**Comment by frenck** [comment]
This server has been removed previously based on data provided by Growatt. 

![CleanShot 2024-11-10 at 17 13 35@2x](https://github.com/user-attachments/assets/83a91845-2e8f-4a03-91da-ab17e87278a5)

It has been marked deprecated to be used.

Nevertheless, thank you for your feedback 👍 

../Frenck
