### ISSUE TITLE
Please provide an example on how to use the tibber.get_prices

### ISSUE THREAD

**Issue by jrebergen** [home-assistant/home-assistant.github.io#35523]
### Feedback

I'd like to have a graph with today's and tomorrows prices from Tibber. But there is no documentation on how to do that! I get the action working (after a lot of reading), but then I'm stuck on how to use the response data. If you follow the links provided, you go down a rabbit hole that doesn't provide any clear answers. This should be made easy, but it isn't. I'm going to use the 'ENTSO-e Transparency Platform' integration for now because that's ready to use. Please make it easier to use the prices in a graph.

### URL

https://www.home-assistant.io/integrations/tibber/

### Version

2024.10.4

**Comment by Danielhiversen** [comment]
You can find some examples here https://community.home-assistant.io/t/tibber-schedul-prices-upcoming-24-hours-prices/391565/255
