### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by IDKWHATKINDA** [home-assistant/home-assistant.github.io#35522]
### Feedback

error 
{
  "error": "unauthorized_client",
  "error_description": "Invalid client id",
  "state": "eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp..........."
}

### URL

https://www.home-assistant.io/integrations/home_connect/

### Version

2024.10.4

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
