### ISSUE TITLE
Instructions to find user ID are wrong

### ISSUE THREAD

**Issue by tabell** [home-assistant/home-assistant.github.io#35530]
### Setting up auth_providers allowed_users

Docs say to look in Settings -> People -> View User Detail, but I don't see that option under People, just a list of people. Clicking on one opens a modal that includes Allow Login, Username, Local Access Only, etc. but no mention of user ID

I managed to find it under Users, not People. not sure if there's a way to navigate there through the UI but manually entering URL of ha:8123/config/users worked

Might also be good to mention that User IDs are in the form of a 32-character hex string to make it clearer that `user1_id` is not the username

### URL

https://www.home-assistant.io/docs/authentication/providers/

### Version

2024.10.4

**Comment by jmealo** [comment]
@frenck : `/config/users` doesn't work in recovery mode. Not sure if it works in regular mode yet.

This works in non-recovery mode. However, if folks are trying to configure Continuously Cast Dashboards, and don't understand they need to use their hex-id, and they get into a recovery situation, there's no way to retrieve the hex id and rectify the configuration error (which is odd).
