### ISSUE TITLE
Bring back map feature?

### ISSUE THREAD

**Issue by jonathanheywood** [home-assistant/home-assistant.github.io#35557]
### Feedback

In the pre-official version of the Automower integration, there was a wonderful feature to show the position and path of the Automower on a map of your garden. Now I have switched to the official release, I can't find the setup and it is not documented.
Are you planning on bringing back this feautre?

### URL

https://www.home-assistant.io/integrations/husqvarna_automower/

### Version

2024.10.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
