### ISSUE TITLE
Wolf BM Uhrzeit - unkown

### ISSUE THREAD

**Issue by TheND71** [home-assistant/home-assistant.github.io#35575]
### Feedback

Hi,
Thanks so far for the good Integration. 
I just want to report that the entity 
“Wolf BM Uhrzeit”
shows “unbekannt” on my system: ISM7e operated with the older Bedienmodul (BM) on a gas operated CGS.
Is there any fix how to display the system time in HA?
Again many thanks.

### URL

https://www.home-assistant.io/integrations/wolflink/

### Version

2024.10.4

**Comment by frenck** [comment]
Hi there @TheND71 👋 

It seems like you wanted to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck
