### ISSUE TITLE
Apparent temperature

### ISSUE THREAD

**Issue by Marco82tn** [home-assistant/home-assistant.github.io#35571]
### Feedback

Buongiorno, l'integrazione funziona ottimamente, sarebbe utile aggiungere la temperatura apparente che la stazione meteo indica sul proprio display, il dato viene inviato anche in Ecowitt.net

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2024.10.4

**Comment by frenck** [comment]
Hi there @Marco82tn 👋 

Unfortunately, I have no clue on what is writing in this issue. Home Assistant is an English speaking community.

Closing this documentation feedback for that reason.

../Frenck
