### ISSUE TITLE
Client ID and secret and not user code

### ISSUE THREAD

**Issue by jthulstrup** [home-assistant/home-assistant.github.io#35587]
### Feedback

The instructions state that you need an access code to setup the Tuya integration, but when I click the link, I am prompted to enter client ID and secret.

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.10.4

**Comment by klaasnicolaas** [comment]
Most of the time when we see these kinds of issues it is usually because:

- You are running an old version of Home Assistant
- A custom integration of Tuya is installed

./Klaas
