### ISSUE TITLE
heating fuel

### ISSUE THREAD

**Issue by lucaferrucci** [home-assistant/home-assistant.github.io#35606]
### Feedback

Hello everyone, I have a pellet heating system, through the integration I have control of the system, I can obtain the consumption that obviously I display in the energy dashboard, it would be appropriate to have the obligation to use gas for the display, why don't you make it possible to change the type of fuel used?
It's really strange that you haven't already thought about it, there are also other heating sources besides gas and electricity.
Can we hope for this change? it's just a matter of being able to change the name of the fuel from gas to another fuel in the screen.
Thanks in advance, I'm sure you'll do something
Luca

### URL

https://www.home-assistant.io/docs/energy/

### Version

2024.10.4

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
