### ISSUE TITLE
Totally doesn't match what the integration itself says. Baffling. 

### ISSUE THREAD

**Issue by skipgub** [home-assistant/home-assistant.github.io#35603]
### Feedback

The instructions to 'add entry' on the Ecowitt integration are completely different from the linked documentation. See screenshots below. (I am unable to use the WS View app. I have the Ecowitt app. So, utterly different.) This seemingly straightforward job is bewildering. 

### URL

https://www.home-assistant.io/integrations/ecowitt/

### Version

2024.10.4

### Additional information

<img width="666" alt="Screenshot 2024-11-06 at 12 58 12" src="https://github.com/user-attachments/assets/06f082bc-1e08-46dc-99ef-63d525c21f83">
<img width="816" alt="Screenshot 2024-11-06 at 12 59 54" src="https://github.com/user-attachments/assets/c8c94396-0c98-4169-8b49-7576db216f80">

**Comment by klaasnicolaas** [comment]
Check that you are not using a custom integration from ecowitt, this is what the core integration shows and it matches the instructions on the website.

![image](https://github.com/user-attachments/assets/e4d66be0-6bcf-4186-8555-2dcabbb83afd)

Edit: you are using this integration https://github.com/garbled1/homeassistant_ecowitt

./Klaas

**Comment by skipgub** [comment]
Thanks. OK. I don't know what that means, but how would I know if it's not the core one? How can there be more than one? Is there a way to delete the integration and start afresh? (Apologies: I am very new to HA and everything about it is completely bewildering)

**Comment by klaasnicolaas** [comment]
You probably used HACS (Home Assistant Community Store) and installed the custom integration through that route. And for questions specific to the custom integration, it is best to consult the repository of that project. 

![image](https://github.com/user-attachments/assets/068b32a0-59c9-4074-a720-27336c0cfd40)
![image](https://github.com/user-attachments/assets/9c2a7879-3ed3-4c1c-82ed-38adc894187b)
You can see from the box icon whether it is a custom integration

Nevertheless we use GitHub for tracking issues, not for providing support. You should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e). You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas

**Comment by skipgub** [comment]
Understood. Thanks. That integration has a link called 'Documentation' which goes to https://www.home-assistant.io/integrations/ecowitt. Hence my confusion.

**Comment by klaasnicolaas** [comment]
That's because the manifest refers to the official docs, which it shouldn't do at all.
https://github.com/garbled1/homeassistant_ecowitt/blob/master/custom_components/ecowitt/manifest.json#L6

./Klaas
