### ISSUE TITLE
NONE of the Mealie instructions work

### ISSUE THREAD

**Issue by antisane** [home-assistant/home-assistant.github.io#35601]
### Feedback

NONE of the Mealie instructions work

### URL

https://www.home-assistant.io/integrations/mealie/

### Version

2024.10.4

**Comment by joostlek** [comment]
Thanks for the feedback. Unfortunately, it worked for at least 682 other people, so they at least managed to do it. Without more information or explanation we can't do anything with this feedback

**Comment by antisane** [comment]
There is nowhere on the mealie website to login or even create a user account, which is step 1.

**Comment by antisane** [comment]
Nevermind, It seems they screwed up their own website. The only way to login now is VIA their demo.
