### ISSUE TITLE
Extend the Spotify Integration

### ISSUE THREAD

**Issue by psjnr84** [home-assistant/home-assistant.github.io#35623]
### Feedback

Hi Team,

I’ve been reading through the Spotify API documentation and have noticed that there are other media types available such as tracks / albums etc.

Would it be possible to extend the Spotify integration in home assistant to have a method to allow for searching the Spotify engine for tracks / albums etc not in your favourites library?

All the available controls are available I believe in the native home assistant environment to allow a user to have a search bar / media type dropdown and a button to submit the query and then a list type to populate the results back from the API search, which if then clicked could be sent to a speaker for playback.

Punxaphil’s Custom Sonos Card code I think could be extended to take benefit of this, so do you think it would be possible to wireframe / code this out and see what could be done? I’m not an experienced developer, but reading the API documentation suggests this functionality should be possible.

This would help remove the need to go outside the home assistant environment and stay inside completely, which is desirable overall for many community members.

### URL

https://www.home-assistant.io/integrations/spotify/

### Version

2024.11.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
