### ISSUE TITLE
how to generate a new QR code for TUYA

### ISSUE THREAD

**Issue by 57234rs59** [home-assistant/home-assistant.github.io#35627]
### Feedback

Hi, to integrate TUYA the shown QR code isn`t value any more. So how to generate a new one or where to get a new one?

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.11.0

**Comment by frenck** [comment]
Close the window, and try again. Every time the setup is started, a new QR code is requested.

../Frenck
