### ISSUE TITLE
Ruckus One - Connecting to MSP Customer tenants

### ISSUE THREAD

**Issue by ablanken** [home-assistant/home-assistant.github.io#35651]
### Feedback

MSPs can create Ruckus One tenants for their customers. Customers can have varying levels of access to these tenants while the MSP manages licensing, and can assist with config, setup, and troubleshooting.

Customer admin users can create API tokens for these tenants.

My MSP customer tenant dashboard URL looks like the following (when I log in as a customer): 
https://MSPNAME.msp.ruckus.cloud/<identifier>/t/dashboard

I entered this URL as per the documentation, but received a connection error message. I then removed "MSPNAME.msp." from the URL and the integration started working.

It would be great if MSP customer URLs could be handled automatically, or if the documentation could be updated to help MSP customer users with the setup. My tenant is US-based. I'm guessing that EU and Asia MSP customer users may need to make slightly different modifications. 

### URL

https://www.home-assistant.io/integrations/ruckus_unleashed/

### Version

2024.11.0

### Additional information

I also found it interesting that when an MSP admin logs in to one of these customer tenants, the URL takes the standard form (e.g. https://ruckus.cloud/tenantid/t/<page>). One possible interim solution could be to refer to your MSP as to what the dashboard URL should be set to.

**Comment by ms264556** [comment]
I've asked about the EU and Asia URLs on the Ruckus Community forum. Once I get a response then I'll create a bugfix PR to handle these extra URL patterns.

If you independently discover the relevant MSP URLs for Asia & EU then please add them in a comment here: it's hit and miss with the Ruckus Community whether you get a quick response from a Ruckus rep, or no response at all.

**Comment by ablanken** [comment]
Thanks for looking into this. 

The settings to manage the customer portal are normally hidden until (per region) MSP licenses are activated.

I appended /v/portalSetting to the end of the URL after switching tenant region to reveal the MSP URL patterns for those regions:

![image](https://github.com/user-attachments/assets/e019124f-9068-40e4-a6c9-316a94b4994e)


XYZ.msp.eu.ruckus.cloud & XYZ.msp.asia.ruckus.cloud

**Comment by ms264556** [comment]
Great. That's what I wanted to know. I'll make the change tonight.

**Comment by ms264556** [comment]
This should be fixed now, in the latest patch release [2024.11.2](https://github.com/home-assistant/core/releases/tag/2024.11.2).

Thanks for reporting and helping to investigate this bug!

**Comment by ablanken** [comment]
Great stuff - thanks for sorting this quickly!
