### ISSUE TITLE
Activating WiFi 

### ISSUE THREAD

**Issue by scnash59** [home-assistant/home-assistant.github.io#35652]
### Feedback

New installation. Home Assistant running with Ethernet connection. Access Network config. Add WLAN parameters.  Get  "Failed to change Network settings" Object does not exist...
![image](https://github.com/user-attachments/assets/ab017d1d-72ce-4cde-8592-855e097eac62)

### URL

https://www.home-assistant.io/getting-started/onboarding/

### Version

2024.11.0

**Comment by frenck** [comment]
Hi there @scnash59 👋 

It seems like you want to report an issue with Home Assistant; however, you have submitted documentation feedback instead. Please report this issue in the following issue tracker:

https://github.com/home-assistant/supervisor/issues

Thanks! 👍 

../Frenck
