### ISSUE TITLE
Adding compressor % in HA integration

### ISSUE THREAD

**Issue by Satefan1973** [home-assistant/home-assistant.github.io#35668]
### Feedback

The HA integration works well and provides great information. It would be great to also use the compressor % in HA.

Keep up the good work!

### URL

https://www.home-assistant.io/integrations/weheat/

### Version

2024.11.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
