### ISSUE TITLE
Great documentation

### ISSUE THREAD

**Issue by mburdych** [home-assistant/home-assistant.github.io#35673]
### Feedback

Hey mates,

Thanks to your documentation and especially thanks to Note about efibootmgr --create --disk /dev/<drivename> --part 1 --label "HAOS" --loader '\EFI\BOOT\bootx64.efi' I was able to install and make funcional my the first HAOS on obsolete Shuttle desktop, 
Now is time to start make automatization and integrate devices and services. Hope, documentation will be same master level.

Thanks a lot

### URL

https://www.home-assistant.io/installation/generic-x86-64/

### Version

2024.11.1

**Comment by frenck** [comment]
Thanks for your message, I'll pass it along to the team.

Wish you a great Home Assistant ride!

../Frenck
