### ISSUE TITLE
unifi couldn't connect while in 2FA configuration (which is mandatory now) 

### ISSUE THREAD

**Issue by jluc2808** [home-assistant/home-assistant.github.io#35685]
### Feedback

since i have installed 2FA Unifi Verify (which is mandatory now for Unifi logging) i couldn't connect the Unifi Plugin and there is a retry every 5 minutes every days beetween 1:30 Am and 3:40 Am 

could that be bypassed ? or Corrected ? 
thanks 

### URL

https://www.home-assistant.io/integrations/unifi/

### Version

2024.11.1

**Comment by Kane610** [comment]
Hello. Read the documentation and follow the instructions

**Comment by jluc2808** [comment]
thanks for these infos,  
at least i succeed with a lot of try to find the right parameters 

i have red the documentation before but wasn't sure of the right process, because a lot of screen, infos, mentions listed on the doc have changed a lot and wasn't with the same words, at the same place and on the screen. 
just to mention : 
- to Check Restrict to local access only  ==> now we have disable the check box remote access  
- to Select Full Management for Network ==> there no choice with that option , we have to set administrator 
- OS Settings are not used, so they can be set to None  ==> there is no OS settings option (so impossible to set to None) 
- there is a new password option ==> to oblige to change by the user at connection , which i don't know if this will be  OK to set or unset . 
- the add button is before the choice of these screens and has been replaced by invite which send a new invited command to the mail setted 
- the is a new filed mandatory  ==> email which couldn't be an already used email in the admin setting 

if the documentation mentionned could be replaced and updated, this will be more evident for newby like me.

**Comment by Kane610** [comment]
> thanks for these infos, at least i succeed with a lot of try to find the right parameters
> 
> i have red the documentation before but wasn't sure of the right process, because a lot of screen, infos, mentions listed on the doc have changed a lot and wasn't with the same words, at the same place and on the screen. just to mention :
> 
> * to Check Restrict to local access only  ==> now we have disable the check box remote access
> * to Select Full Management for Network ==> there no choice with that option , we have to set administrator
> * OS Settings are not used, so they can be set to None  ==> there is no OS settings option (so impossible to set to None)
> * there is a new password option ==> to oblige to change by the user at connection , which i don't know if this will be  OK to set or unset .
> * the add button is before the choice of these screens and has been replaced by invite which send a new invited command to the mail setted
> * the is a new filed mandatory  ==> email which couldn't be an already used email in the admin setting
> 
> if the documentation mentionned could be replaced and updated, this will be more evident for newby like me.

The documentation has been recently updated and reflects the latest release of unifi network hosted on unifi os

**Comment by jluc2808** [comment]
sorry to deny for the documentation 

i will post some screenshot of the doc and the real site doc and you will see what i ask for 
![doc unifi 0](https://github.com/user-attachments/assets/5f9f20be-076e-4f93-a8f4-236175559675)
![doc unifi 1](https://github.com/user-attachments/assets/49e0e76a-2893-4522-b6af-a840dda11e02)

4 and 5 aren't OK 
the online page is 

![screen unifi 1](https://github.com/user-attachments/assets/330f23cf-2260-4896-8b36-65c6f52a6d96)
with:  
- to Check Restrict to local access only ==> now we have disable the check box remote access

![screen unifi 2](https://github.com/user-attachments/assets/5191f476-660d-4f5d-848e-a300164e3e44)
- to Select Full Management for Network ==> there no choice with that option , we have to set administrator
- OS Settings are not used, so they can be set to None ==> there is no OS settings option (so impossible to set to None)
- the add button is before the choice of these screens and has been replaced by invite which send a new invited command to the mail setted

![screen unifi 3](https://github.com/user-attachments/assets/eb6d6b20-aff6-4734-9808-4b0424448cc4)
- the mail address is mandatory 
- there is a new field set admin password :  which should ask to change the password at the 1rst login ?

**Comment by Kane610** [comment]
Are you running a self hosted version of the unifi network app?

**Comment by jluc2808** [comment]
Self-Hosted Network 8.4.62 on synology

i just take a look to the dream machine i have on another site and this is exatcly what is on the doc 

so you put the finger on the problem that the selfhosted aren't the same than the UDR (or perhaps another unifi machine)
