### ISSUE TITLE
Dashboard page does not have pointers to how to script

### ISSUE THREAD

**Issue by jpravetz** [home-assistant/home-assistant.github.io#35684]
### Feedback

The dashboard page should have a top level link to how to customize using scripting. Maybe the link is there somewhere, but I  haven't found it yet.
```
[[[
          if (entity.state) return 'lime';
          else return 'orange';
        ]]]
```

### URL

https://www.home-assistant.io/dashboards/

### Version

2024.11.1

**Comment by frenck** [comment]
there is no such script in Home Assistant itself, thus correctly not documented.

There are third-party extensions some people use to add such capabilities, but that is not supported or recommended by the Home Assistant project.

../Frenck

**Comment by jpravetz** [comment]
Thanks for that. After a few years of using HA I didn't know that. Maybe this fact in itself can be documented, right on the Introduction page? It would help with people searching for answers. My example is from the `custom:button-card` but I didn't know this was unique to this card.

**Comment by frenck** [comment]
> Maybe this fact in itself can be documented, right on the Introduction page?

That isn't functionality of Home Assistant.

> My example is from the custom:button-card but I didn't know this was unique to this card.

That is something custom and not something we provide, please consult the documentation of the custom third-party software you are using for information on the usage of your customization.

../Frenck

**Comment by jpravetz** [comment]
On the [Custom Card page](https://developers.home-assistant.io/docs/frontend/custom-ui/custom-card/) you could change the opening sentence to

[Dashboards](https://www.home-assistant.io/dashboards/) are our approach to defining your user interface for Home Assistant. We offer a lot of built-in cards, but you're not just limited to the ones that we decided to include in Home Assistant. You can use one of the Custom Community Cards, some of which offer a lot of customization, including scripting of values. Or you can build and use your own!

**Comment by frenck** [comment]
That is not end-user documentation.

Additionally, again, we do not support or recommend the use of custom third-party software.

Nevertheless, thanks for your suggestions.

../Frenck

**Comment by jpravetz** [comment]
I'm not sure what you mean by the Custom Card Page not being end user documentation.

And you link to these 3rd party Custom Community Cards from the [Introduction page](https://www.home-assistant.io/dashboards/).  

This is about educating your users on how to achieve custom outcomes. I have to assume that this is what the Custom Card page is for.

**Comment by frenck** [comment]
The developer documentation is aimed at developers, not end-users.

We do not recommend using custom cards.

../Frenck

**Comment by jpravetz** [comment]
Since you don't recommend using custom cards, can you remove the link to these 3rd party Custom Community Cards from the [Introduction page](https://www.home-assistant.io/dashboards/)? Sparse documentation should be sparse. Users can buy a book or search thru blog posts if they want to learn and get the full picture.
