### ISSUE TITLE
Why is it so hard to find download links?

### ISSUE THREAD

**Issue by acochrane** [home-assistant/home-assistant.github.io#35686]
### Feedback

I have been on the getting started page for a few minutes and I haven't found links to download the install images mentioned in "install on x86" section

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.11.1

**Comment by frenck** [comment]
The download link is in the first step:

![CleanShot 2024-11-10 at 20 20 41@2x](https://github.com/user-attachments/assets/6a0fda52-bd30-4467-ae49-f5e8a4cd6ade)


The software will download and flash the right images for you. There is no need to manually download images using the recommended steps.

../Frenck
