### ISSUE TITLE
Contradiction between NOTE and Configuration Variables (Restore)

### ISSUE THREAD

**Issue by jca001** [home-assistant/home-assistant.github.io#35687]
### Feedback

In the NOTE it states However, automations using the timer.finished event will not trigger if the timer expires when Home Assistant is not running.
But in the Configuration Variables (Restore) it states If an active timer was supposed to end while Home Assistant is stopped, the timer.finished event will fire on startup for that timer.

Which one is true?

### URL

https://www.home-assistant.io/integrations/timer/

### Version

2024.11.1

**Comment by frenck** [comment]
Both, if Home Assistant isn't running, it will not be able to fire; however, it will fire later on startup of Home Assistant in case the previous window was missed.

../Frenck

**Comment by jca001** [comment]
I think the NOTE could be a little more clear. State timer.finished will NOT fire while Home Assistant is not running, but if Restore is true, then when Home Assistant starts again a timere.finished will fire if the timer would have expired.
