### ISSUE TITLE
ecovacs deebot t30 omni missing entity 

### ISSUE THREAD

**Issue by xtra0581** [home-assistant/home-assistant.github.io#35691]
### Feedback

Hi there, 

the ecovacs deebot t30 omni is missing a select option for cleaning speed right now. See attachment. 

Would be nice, if added.
![Screenshot_2024-11-10-22-53-50-321_com eco global app-edit](https://github.com/user-attachments/assets/185e20c8-6cf7-4d2c-bdfd-b05503a43994)

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.11.1

**Comment by edenhaus** [comment]
Hi

This sounds more like an feature request?
Please use the [feature request](https://community.home-assistant.io/c/feature-requests) section of our forum to contribute on existing or create new feature requests.
For sure, contributions are always welcome, so please feel free to create a PR on your own.

Thanks! 👍

btw. this is mentioned at least two times before you can create a new issue report :wink: 

![image](https://github.com/user-attachments/assets/39acc717-cd1d-48ab-a86f-9608102b9465)

![image](https://github.com/user-attachments/assets/79e0250f-eb75-445c-b978-7ad21ca47d2f)
