### ISSUE TITLE
Failed to update supervisor and core on 2024.11.3 (supervisor) / 2024.11.1 (core) 

### ISSUE THREAD

**Issue by snipiba** [home-assistant/home-assistant.github.io#35700]
### Feedback

Nepodarilo sa vykonať akciu update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=2024.11.3&fromImage=ghcr.io%2Fhome-assistant%2Faarch64-hassio-supervisor&platform=linux%2Farm64: Internal Server Error ("toomanyrequests: retry-after: 485.867µs, allowed: 44000/minute")

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2024.10.4

### Additional information

First was shown an update for core to 2024.11.1, but for raspberrypi4-64 are no tag available to download and install... then, supervisor got that 500 server error for too many requests...

**Comment by snipiba** [comment]
Nepodarilo sa vykonať akciu update/install. Error updating Home Assistant Supervisor: Update of Supervisor failed: Can't install ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3: 404 Client Error for http+docker://localhost/v1.47/images/ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3/json: Not Found ("No such image: ghcr.io/home-assistant/aarch64-hassio-supervisor:2024.11.3")

**Comment by JosephRDawson** [comment]
I am getting the same error using HA Greene.
![Settings-–-Home-Assistant(2)](https://github.com/user-attachments/assets/e4336bc6-8250-45ed-85fd-a744702263c3)
.

**Comment by klaasnicolaas** [comment]
Duplicate of: https://github.com/home-assistant/supervisor/issues/5405
