### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by meyxiam** [home-assistant/home-assistant.github.io#35728]
### Feedback

Hello, i have a custom integration https://github.com/Vost3/hass-palazzetti
I don't found the officiel integration  https://www.home-assistant.io/integrations/palazzetti/ when i search in 
[ Settings > Devices & Services]
 and In the bottom right corner, select the [ Add Integration]

How correct it ?
i'm in 2024.11.2

### URL

https://www.home-assistant.io/integrations/palazzetti/

### Version

2024.11.1

**Comment by dotvav** [comment]
Hi @meyxiam, there seems to be a conflict between the custom integration and the core integration, as they are both claiming the domain `palazzetti`. You'll have to uninstall the custom integration to let the core one work. Be aware though, that there is currently a bug in the Core integration that makes it report the wrong current temperature with certain models. The bug will be fixed in the next release (or in the dev version).

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas

**Comment by meyxiam** [comment]
thanks for your answers.
I have others questions.
In this integration, i don't have the temperature of the ballon, the pellet consumption.
With the connection box, you can use this url http://[IP_CONNBOX]/cgi-bin/sendmsg.lua?cmd=GET+ALLS for obtains

`{
    "INFO": {
        "RSP": "OK",
        "CMD": "GET ALLS",
        "TS": 1731689493
    },
    "SUCCESS": true,
    "DATA": {
        "T2": 20.7,
        "F2LF": 0,
        "PQT": 4325,
        "PWR": 2,
        "CHRSTATUS": 1,
        "FANLMINMAX": [0, 5, 0, 5, 0, 5],
        "FDR": 0,
        "F2V": 0,
        "MOD": 1228,
        "DPT": 0,
        "APLWDAY": 5,
        "MAC": "xxxxxxxxxxxx",
        "SETP": 24,
        "APLTS": "2024-11-15 18:05:42",
        "STATUS": 1,
        "T3": 22,
        "T1": 0,
        "PUMP": 0,
        "T5": 19.8,
        "F1RPM": 0,
        "OUT": 0,
        "SN": "LTxxxxxxxxxxx",
        "F1V": 0,
        "EFLAGS": 0,
        "LSTATUS": 1,
        "T4": 0,
        "F3L": 3,
        "F2L": 2,
        "CORE": 32,
        "F4L": 1,
        "IN": 9,
        "DP": 0,
        "FWDATE": "2020-07-29",
        "VER": 1,
        "MBTYPE": 0
    }
}
`

The PQT value is my pellet consumption. It's very interesting. Can you add this evolution ?
You can see exemples here : https://github.com/Domochip/WirelessPalaControl

I would like to have all properties.
Thanks you

**Comment by dotvav** [comment]
@meyxiam this is the repo for the HA documentation. Please do not make HA feature requests here, make them there: https://github.com/home-assistant/core/issues

That being said, what you are asking is on my roadmap. You can join the [HA discord server](https://discord.gg/srh3NNkY) or [mine](https://discord.gg/YSKvDNK2) if you need support or want to discuss.

**Comment by klaasnicolaas** [comment]
The community forum is for feature requests, the core issues tracker is for integration issues 😉 

./Klaas

**Comment by dotvav** [comment]
Cool, my bad.
