### ISSUE TITLE
Supervisor was not able to update

### ISSUE THREAD

**Issue by kaars001** [home-assistant/home-assistant.github.io#35720]
### Feedback

I am not able to do any update:

Command line yields:
~ # ha supervisor update
Processing... Done.

Error: No supervisor update available - 2024.11.2

ha supervisor logs shows a warning for what it is worth:
2024-11-12 12:00:14.361 WARNING (MainThread) [supervisor.addons.options] Option 'bash' does not exist in the schema for Advanced SSH & Web Terminal (a0d7b954_ssh)

~ # ha supervisor info
addons:
- icon: true
  name: Z-Wave JS
  repository: core
  slug: core_zwave_js
  state: started
  update_available: true
  version: 0.8.1
  version_latest: 0.9.0
- icon: true
  name: Samba share
  repository: core
  slug: core_samba
  state: started
  update_available: false
  version: 12.3.2
  version_latest: 12.3.2
- icon: true
  name: FTP
  repository: a0d7b954
  slug: a0d7b954_ftp
  state: started
  update_available: false
  version: 5.1.1
  version_latest: 5.1.1
- icon: true
  name: Terminal & SSH
  repository: core
  slug: core_ssh
  state: started
  update_available: false
  version: 9.15.0
  version_latest: 9.15.0
- icon: true
  name: Node-RED
  repository: a0d7b954
  slug: a0d7b954_nodered
  state: started
  update_available: false
  version: 18.1.1
  version_latest: 18.1.1
- icon: true
  name: Log Viewer
  repository: a0d7b954
  slug: a0d7b954_logviewer
  state: started
  update_available: false
  version: 0.17.1
  version_latest: 0.17.1
- icon: true
  name: Advanced SSH & Web Terminal
  repository: a0d7b954
  slug: a0d7b954_ssh
  state: started
  update_available: false
  version: 19.0.0
  version_latest: 19.0.0
- icon: true
  name: File editor
  repository: core
  slug: core_configurator
  state: started
  update_available: false
  version: 5.8.0
  version_latest: 5.8.0
- icon: true
  name: Matter Server
  repository: core
  slug: core_matter_server
  state: started
  update_available: false
  version: 6.6.0
  version_latest: 6.6.0
addons_repositories:
- name: Local add-ons
  slug: local
- name: Music Assistant
  slug: d5369777
- name: Official add-ons
  slug: core
- name: Home Assistant Community Add-ons
  slug: a0d7b954
- name: ESPHome
  slug: 5c53de3b
arch: aarch64
auto_update: true
channel: stable
debug: false
debug_block: false
diagnostics: true
healthy: false
ip_address: 172.30.32.2
logging: info
supported: true
timezone: Europe/Amsterdam
update_available: false
version: 2024.11.2
version_latest: 2024.11.2
wait_boot: 5

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2024.11.1

### Additional information

Any advice is appreciated

**Comment by klaasnicolaas** [comment]
This has already been fixed and a lot of duplicated issues.

./Klaas
