### ISSUE TITLE
Integration to an existing raspian is missing

### ISSUE THREAD

**Issue by flobee** [home-assistant/home-assistant.github.io#35729]
### Feedback

Please provide source.list options and howtos :-) Thank you!

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.11.1

**Comment by frenck** [comment]
We do not have any. Home Assistant is meant to be installed as an dedicated appliance.

../Frenck

**Comment by flobee** [comment]
ok,grrr,  thx! ;-)
