### ISSUE TITLE
supervisor update mislukt hoe los ik dit op 

### ISSUE THREAD

**Issue by peterijmker** [home-assistant/home-assistant.github.io#35738]
### Feedback

ik heb de aangegeven adviezen in HA opgevolgd maar niets werkt 

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2024.11.1

### Additional information

supervisor update mislukt hoe los ik dit op

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
