### ISSUE TITLE
To be removed in HA 2025.5 - so what to do now?

### ISSUE THREAD

**Issue by jaspov** [home-assistant/home-assistant.github.io#35742]
### Feedback

I had a message in HA that this functionality will be removed in HA 2025.5. Link added to that message points here, was hoping for some indication of what to now? What do I need to do to keep this working?

### URL

https://www.home-assistant.io/integrations/local_file/

### Version

2024.11.1

### Additional information

See above - "learn more" link points here
![2024-11-13_17h17_09](https://github.com/user-attachments/assets/ce5a2be8-c5d4-404e-a7b4-a44af25f9139)

**Comment by frenck** [comment]
Nothing, everything has been imported into the UI already.

All there is left to do is:

![CleanShot 2024-11-13 at 17 23 11@2x](https://github.com/user-attachments/assets/da55ea85-95ab-4e3b-99a9-d21d56db33ab)

Once you've done that, everything should be as normal.

../Frenck

**Comment by jaspov** [comment]
Thank you. Highly appreciated!

**Comment by frenck** [comment]
No problem! 👍
