### ISSUE TITLE
Tesla cloud integration - add help for the case more Tesla verhicles need to be integrated

### ISSUE THREAD

**Issue by Jn115759** [home-assistant/home-assistant.github.io#35740]
### Feedback

_Command signing 
Certain vehicles, including all vehicles manufactured since late 2023, require vehicle commands to be encrypted end-to-end and signed with a private key. The Tesla Fleet integration is unable to perform this encryption at this time, so certain features may be disabled or throw an exception when used._

**Adding multiple vehicles
After setting up the integration and adding the first vehicle, the browser will keep you logged in on the Tesla website. First logout on the Tesla web page before adding a second vehicle in the integration.**

_Entities 
These are the entities available in the Tesla Fleet integration. Not all entities are enabled by default, and not all values are always available._

### URL

https://www.home-assistant.io/integrations/tesla_fleet/

### Version

core-2024.11.1

**Comment by Bre77** [comment]
https://github.com/home-assistant/core/pull/130576 is going to make this issue redundant.

**Comment by Jn115759** [comment]
@Bre77 , thank you for this improvement!. Great
