### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rtrofimenkov** [home-assistant/home-assistant.github.io#35745]
### Feedback

Add the ability to control color and effects via the master switch in Home Assistant. This would allow for more convenient control of an LED strip with multiple segments by synchronizing them in terms of color and effects. Such a feature would simplify usage and enhance flexibility when working with multiple segments. Thank you very much for this amazing integration and for any future consideration of this feature!

### URL

https://www.home-assistant.io/integrations/wled/

### Version

2024.11.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
