### ISSUE TITLE
Other functionalityes

### ISSUE THREAD

**Issue by Guijar** [home-assistant/home-assistant.github.io#35741]
### Feedback

Hi!!

First of all thanks for this great integration, you did a nice job.

On the other hand I want to know if there is any way to set other AVR options, like late night mode or listening mode. I'm not an active developer of HA integrations, but I work in software development and maybe I can help upgrading the functionalities.

Sorry about my poor english hehe.

Thanks!!!

### URL

https://www.home-assistant.io/integrations/onkyo/

### Version

2024.11.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
