### ISSUE TITLE
Multiple zoneminder servers and support for 1.37

### ISSUE THREAD

**Issue by michlalp** [home-assistant/home-assistant.github.io#35753]
### Feedback

Hello, 
how can we setup Home assistant for getting data from multiple ZM servers and what about ZM 1.37? Lot of things changed since 1.36...

### URL

https://www.home-assistant.io/integrations/zoneminder/

### Version

2024.11.1

**Comment by nabbi** [comment]
multi-server support PR is in progress yet needs further validations  https://github.com/rohankapoorcom/zm-py/pull/69/commits/2350e0c0353cf7cbf9269956d5521b6ff6277fad 

I created a zm 1.37 tracking request @ https://github.com/rohankapoorcom/zm-py/issues/70
more details as what does not work would be helpful

 time and resources impacts these efforts and remains in maintenance mode

**Comment by michlalp** [comment]
...I think you refer to multi-server setup in ZM, that would be definitely nice to have, but I'm talking about multiple independent ZM instances in single hass. I have very limited bandwidth to multiple remote locations so ZM is good way to get motion alerts from those sites  ex. ZM@rPi5 with 2 cameras uses only 10kbit of bandwidth which is less than onvif without image, but I can add only one ZM instance to hass https://www.home-assistant.io/integrations/zoneminder/ another problem is that the switch controls all cameras at once. It should be definitely linked to single monitor, not all cameras linked to rhat ZM instance.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by michlalp** [comment]
...so the docs should include info that it can handle only single instance of ZM and the version 1.37 is not supported. Thanks.

**Comment by frenck** [comment]
> ...so the docs should include info that it can handle only single instance of ZM and the version 1.37 is not supported

This should be supported -> bug report. Meaning this is still the wrong location.

../Frenck
