### ISSUE TITLE
Add Kelvin as temperature unit

### ISSUE THREAD

**Issue by IgnacioHR** [home-assistant/home-assistant.github.io#35751]
### Feedback

I own a De Dietrich boiler and I'm adding some entities whose values are expressed in K, for example the Histeresis (measures the amount of temperature that changes over time or something like that). That unit is missing in Home Assistant.

Side note: the light color is also measured in the same unit so you now know what 5000 K means for a light

### URL

https://www.home-assistant.io/integrations/number/

### Version

2024.11.1

### Additional information

Additional information can be obtained from here: https://en.wikipedia.org/wiki/Kelvin

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
