### ISSUE TITLE
Nest Integration - Pub/Sub must create a topic. 

### ISSUE THREAD

**Issue by ajproe** [home-assistant/home-assistant.github.io#35768]
### Feedback

In Pub/Sub need to manually create a topic before you can finish adding the nest integration or it will say an unknown error has occurred in home assistant. It stalls out after the "Link Google Account" step unless you do this. 
https://console.cloud.google.com/cloudpubsub/topic

### URL

https://www.home-assistant.io/integrations/nest/

### Version

2024.11.1

### Additional information

n/a

**Comment by allenporter** [comment]
This is not correct. You need to use the existing SDM topic as described in the config flow screen.

If you create your own topic you won't see any updates.

**Comment by allenporter** [comment]
You are correct it stops the error due to a bug in 2024.11.1 being fixed in 2024.11.2. the error happens if you never had any subscription before.

**Comment by ajproe** [comment]
I didn't use the manually created topic, I was able to select SDM topic but for whatever reason it wouldn't proceed forward for me if I didn't make my own first. For anyone still on 2024.11.1 try that out or maybe wait for a fix in 2024.11.2.

**Comment by allenporter** [comment]
OK great. Should now be resolved that 2024.11.2 is released. Thanks for your patience on this.
