### ISSUE TITLE
ThinQ login invalid for PAT

### ISSUE THREAD

**Issue by bchojna** [home-assistant/home-assistant.github.io#35762]
### Feedback

In trying to setup the integration, I receive invalid login notices when trying to access the personal access token website at LG.  Is it region locked?

### URL

https://www.home-assistant.io/integrations/lg_thinq/

### Version

2024.11.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
