### ISSUE TITLE
32/64bit confusion on page for HA install

### ISSUE THREAD

**Issue by Psi-nz** [home-assistant/home-assistant.github.io#35766]
### Feedback

The page is not clear if the "Raspberry Pi Imager" procedure will install a 32 or 64bit version.
The Raspberry Pi Imager itself also does not provide any information about this for a HA install.
It would be nice if the selected HA image included the numbers 32/64 instead of just "Home Assistant OS 13.2 (RPi 4/400)"

### URL

https://www.home-assistant.io/installation/raspberrypi/

### Version

2024.11.1

**Comment by frenck** [comment]
Hi there @Psi-nz,

We only have 64 bits of images we publish.

../Frenck
