### ISSUE TITLE
Risco linksys doesn't work anymore

### ISSUE THREAD

**Issue by zodracom** [home-assistant/home-assistant.github.io#35779]
### Feedback

the Risco integration isn't working anymore 
![image](https://github.com/user-attachments/assets/75a53212-b331-4b1c-9b43-7d526b8047c7)

### URL

https://www.home-assistant.io/integrations/risco/

### Version

2024.11.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
