### ISSUE TITLE
Config as webui doesn't work, use TV and limited input devices instead

### ISSUE THREAD

**Issue by x-myth** [home-assistant/home-assistant.github.io#35789]
### Feedback

Firstly followed instructions on webpage, which indicates in credentials setup to select webui, see step 13 and 14 below. Couldn't get the calendar integration to work, it fails (connection timeout) once you click a link that is opening back to home assistant app. Then timeout. 

When using the add credentials button in home assistant itself, I found out the instructions differ. It indicates to config Oauth credentials as TV and limited input devices. This method does work! 

------------------

Webpage:
13. Set the Application type to Web application and give this credential set a name (like “Home Assistant Credentials”).
14. Add https://my.home-assistant.io/redirect/oauth to Authorized redirect URIs then select Create.
This is not a placeholder. It is the URI that must be used.

Home assistant:
3. Select TV and Limited Input devices for the Application Type.

### URL

https://www.home-assistant.io/integrations/google/

### Version

2024.11.2

**Comment by allenporter** [comment]
Ok either way works, but web is preferred.

The timeout usually indicates one of:
- your network is blocking traffic to Google like an as blocker or
-  ipv6 is misconfigured and you need to fix it or disable it.
