### ISSUE TITLE
12 minutes earlier 

### ISSUE THREAD

**Issue by MuhammadYacoub** [home-assistant/home-assistant.github.io#35790]
### Feedback

isha id 12 min early

### URL

https://www.home-assistant.io/integrations/islamic_prayer_times/

### Version

2024.11.2

**Comment by frenck** [comment]
Hi there @MuhammadYacoub 👋 

It sounds like you want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks! 👍 

../Frenck
