### ISSUE TITLE
Nibe heat pump setup fails

### ISSUE THREAD

**Issue by WimDeceuninck** [home-assistant/home-assistant.github.io#35796]
### Feedback

Hi, 

I do no succeed to install the Nibe Heat Pump integration.

I run into the 'The specified URL is not wel formed nor supported.' - error message.

Does anyone know how to fix the setup of the integration?

Kind regards,
Wim

<img width="299" alt="Screenshot 2024-11-16 223727" src="https://github.com/user-attachments/assets/fa3ec9b9-5f07-44e3-9dc6-1e6821364b69">

### URL

https://www.home-assistant.io/integrations/nibe_heatpump/

### Version

2024.11.2

**Comment by elupus** [comment]
Drop the brackets [].

**Comment by WimDeceuninck** [comment]
Thank you Joachim!Kind regards,WimVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Joakim Plate ***@***.***> Datum: 16/11/2024  22:42  (GMT+01:00) Aan: "home-assistant/home-assistant.io" ***@***.***> Cc: Willem de Zwijger ***@***.***>, Author ***@***.***> Onderwerp: Re: [home-assistant/home-assistant.io] Nibe heat pump setup fails (Issue #35796) 
Drop the brackets [].

**Comment by WimDeceuninck** [comment]
Thank you @elupus!

Although, I still do not uderstand why the brakets [  ] re used is the installation procedure.

Any idea?

I am a slow adaptor, but I am eager to learn.

Kind regards,
Wim

**Comment by elupus** [comment]
Because they mark something to replace in an example string. Might have been enough with uppercase but, its common practice to use some indicator. Brackets are common.

**Comment by WimDeceuninck** [comment]
Thanks you @elupus!

I'll remind that :-)

Kind regards,
Wim
