### ISSUE TITLE
There is no information about "zones".

### ISSUE THREAD

**Issue by Adastreia** [home-assistant/home-assistant.github.io#35799]
### Feedback

I think information about zones would be fitting on this page as it is related to organizing and you can edit _areas_, _labels_ and _zones_ in one context in the admin. 

On a related note! It would be nice to be able to edit the floors and categories in the same context to :)

### URL

https://www.home-assistant.io/docs/organizing/

### Version

2024.11.2

### Additional information

As a UX designer I _applaud_ the great work you are making with Home Assistant. I know for a fact that it is a lot of work that takes commitment and a great deal of communication, by everyone!, before it ever gives results. You are _all_ really making a lot of progress and **I'm _so_ impressed!** Keep it up!

**Comment by frenck** [comment]
Zones are not related to the organization capabilities of Home Assistant.

Nevertheless, thanks for the suggestion 👍 

../Frenck
