### ISSUE TITLE
Logged out after 24 hours (or due to HA update?)

### ISSUE THREAD

**Issue by mhurk** [home-assistant/home-assistant.github.io#35793]
### Feedback

After installation it is not clear (at least not te me, a relative HA newbie) where I can review or update the linked account. I installed the WeHeat integration yesterday and this worked fine. After exactly 24 hours I am logged out and see some authentication errors. Don't know how to re-enter this or reactivate the WeHeat integration. 

(Not sure if this is the right location for this question)

### URL

https://www.home-assistant.io/integrations/weheat/

### Version

2024.11.2

**Comment by mhurk** [comment]
As addition: reinstalling (after remove and reboot) or disable - enable cycles all makes no difference. 

![image](https://github.com/user-attachments/assets/1ea31e20-bc49-4347-a964-dd0b872eaa59)

![image](https://github.com/user-attachments/assets/413026c5-a747-4aad-a1a3-085db5fafd79)

**Comment by mhurk** [comment]
@jesperraemaekers Can it also be related to the HA version? I updated to 2024.11.2 and that does not match weheat/manifest.json.

I'd like to propose this change (did not create the pull request yet as I did not test it)
![image](https://github.com/user-attachments/assets/bd3ee12c-4858-4dc4-abe2-aed887c2e7c6)

Or something like `"requirements": ["weheat>=2024.11.02"]` which also takes care of future upgrades (fingers crossed as tha may break other things)

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
