### ISSUE TITLE
Ecovacs AVA Andy air purification robot cannot be controlled

### ISSUE THREAD

**Issue by zhongjunxiao** [home-assistant/home-assistant.github.io#35813]
### Feedback

Ecovacs AVA Andy air purification robot cannot be controlled by this plug-in.This air purification robot can be synchronized and displayed, but multiple buttons including 'start' cannot control the robot properly.
![屏幕截图 2024-11-18 193541](https://github.com/user-attachments/assets/1c9635e1-d1db-47e3-a40e-389fe11b09ba)
![屏幕截图 2024-11-18 193701](https://github.com/user-attachments/assets/208d6b2a-08e6-4208-ad82-8d1eb74283af)

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.11.2

**Comment by zhongjunxiao** [comment]
您给我发送的邮件我已经收到，谢谢，我会尽快阅读。
——海里淡水鱼（ZJX)

**Comment by mib1185** [comment]
Hi @zhongjunxiao 
we are an English speaking community, so please keep using the English language, so the community is able to get and properly help with your issue.
thx :+1:

**Comment by edenhaus** [comment]
The Ava Air purification robot is currently not supported by the HA integration. Please feel free to add support for it directly in the library https://github.com/DeebotUniverse/client.py

Closing this issue as this is a feature request and we use GitHub only to track issues
