### ISSUE TITLE
V2C Trydan: "Device already added" even If none has been added before"

### ISSUE THREAD

**Issue by xccose** [home-assistant/home-assistant.github.io#35818]
### Feedback

Followed all the steps. When I add the integration, I get the following message "device already configured" even if I get no possibility to choose a specific Trydan to add and I never added a charger before. No device neither attributes appear in home assistant.
Should I activate the OCPP protocol in the Trydan? Thank you

### URL

https://www.home-assistant.io/integrations/v2c/

### Version

2024.11.2

**Comment by dgomes** [comment]
Could you please check the logs ?

This integration does not use OCPP but the private local HTTP interface of Trydan

**Comment by xccose** [comment]
Thank you for the fast reply. No logs related with this issue; neither in "raw logs"

**Comment by dgomes** [comment]
have you ever used the custom-integration ?

**Comment by xccose** [comment]
no, never. Should I try and report?

**Comment by dgomes** [comment]
trying to figure out that error without ever having setup before...

https://`MY HOME ASSISTANT IP`/config/integrations/integration/v2c

No entries ? 

Can you enable debug in that page ?

**Comment by xccose** [comment]
Thank you, problem solved. Entering in that URL I was able to delete the integration and add it again....this time successfully. In the previous attempts the integration did not show in the integrations panel neither the entities were created. Probably a bad wifi coverage in the initial attempt? Anyway problem solver, thank you!
