### ISSUE TITLE
Tuya integration bug on Smart wifi Thermostat

### ISSUE THREAD

**Issue by Postixer** [home-assistant/home-assistant.github.io#35824]
### Feedback

Hi, i have a problem with Smart wifi Thermostat, the scale of temperature in app tuya is set on °C and in home assistant integration in °F, and not there is no possibility to change it like in the sensors, with the old version this bug was not present.
![Senza titolo](https://github.com/user-attachments/assets/45dc0efa-2cc2-4ab0-9bfe-71f84a3757a7)
![Senza titolo2](https://github.com/user-attachments/assets/66e2e306-8f6a-4c6e-9a1e-b4054411c14f)

### URL

https://www.home-assistant.io/integrations/tuya/

### Version

2024.11.2

**Comment by frenck** [comment]
Hi there @Postixer 👋 

Thanks for your message, however, it seems like you tried to report an issue with an Home Assistant integration; however, you have submitted documentation feedback instead.

If you are unsure where to go, please consult: https://www.home-assistant.io/help

Thanks! 👍 

../Frenck
