### ISSUE TITLE
Also Gardena BLE is supported 

### ISSUE THREAD

**Issue by sonorobby** [home-assistant/home-assistant.github.io#35835]
### Feedback

Cause the Lawnmovers are often selled as Gardena Lasn Mover maybe is better to call it husquarna and gardena ble ?

### URL

https://www.home-assistant.io/integrations/husqvarna_automower_ble/

### Version

2024.11.2

**Comment by frenck** [comment]
We don't give integration duplicate names. It is, however, possible to introduce a virtual integration that uses the code base of another integration.

Unfortunately, this is not an documentation change, but a code change that needs to be done in our core code repository. For that reason, I'll go ahead and close this documentation feedback on this end.

../Frenck
