### ISSUE TITLE
Issue with integration LG Thinq

### ISSUE THREAD

**Issue by RESONANCE111** [home-assistant/home-assistant.github.io#35841]
### Feedback

There is an issue logging into the account on the website https://connect-pat.lgthinq.com/login. I have tried two different email addresses and used a VPN, but it keeps saying "login failed."

### URL

https://www.home-assistant.io/integrations/lg_thinq/

### Version

2024.11.1

**Comment by frenck** [comment]
Hi there @EMAKASS 👋 

It seems like you have an issue with an third-party website. For that issue, please contact the party that provides that third-party website. You have submitted documentation feedback for the Home Assistant project documentation, there is no amount of documentation we can adjust to fix an issue on a third-party website we do not control. 

Thanks 👍 

../Frenck
