### ISSUE TITLE
[OpenWetaherMap] Parameters to remove

### ISSUE THREAD

**Issue by szczukot** [home-assistant/home-assistant.github.io#35850]
### Feedback

Please remove 
Latitude
Longitude

from documentation. I think that now they are taken from the global HA configuration and not entered in this integration.

### URL

https://www.home-assistant.io/integrations/openweathermap/

### Version

2024.11.2

**Comment by klaasnicolaas** [comment]
The longitude and latitude data is still a configuration option when setting up the integration and thus it should be included in the documentation, regardless of whether it is already filled in by default with your global settings.

./Klaas

**Comment by szczukot** [comment]
Where?
![image](https://github.com/user-attachments/assets/937bd744-43b4-490c-9c5b-c5bbfbb1e717)

**Comment by freekode** [comment]
These are options, you can't change location here. When you create a new integration, latitude and longitude fields will be in the form.
