### ISSUE TITLE
restart supervisor page

### ISSUE THREAD

**Issue by unkledunkle** [home-assistant/home-assistant.github.io#35853]
### Feedback

You haven't explained or linked to what a CLI is. 

### URL

https://www.home-assistant.io/more-info/unhealthy/supervisor/

### Version

2024.11.2

**Comment by frenck** [comment]
Hi there @unkledunkle 👋 

If you get this message, it means you are running Home Assistant Supervised.

This is a highly technical and complex installation method, for which our documentation warns. It is assumed and expected one has advanced knowledge about Linux administration and complex networking. For those group of people, this would not be a question.

If you run into this and have to ask yourself what a CLI is, I honestly think you should consider switching to a different installation method (don't get me wrong, I don't mean bad with that comment, I really do think it is a way better step for yourself at that point).


../Frenck

**Comment by unkledunkle** [comment]
You're assuming a whole backstory there from the sentence "You haven't explained or linked to what a CLI is."

I had solved my 'problem' long before I got to that page, I just spotted some poorly structured documentation and thought I'd be a good community member and suggest an improvement.

Jeez man, be lazy like me, and just go add a hyperlink - it would've taken less time than replying to tell me I need to lower my horizons. I do know where google is, I remember when all we had was freakin' BBS for heaven's sake.


________________________________
