### ISSUE TITLE
howto add new climate devices

### ISSUE THREAD

**Issue by pilot1981** [home-assistant/home-assistant.github.io#35854]
### Feedback

after login on FGLAIR, what I have to do to add new climate device? it get all devices already added in FGLAIR app?

### URL

https://www.home-assistant.io/integrations/fujitsu_fglair/

### Version

2024.11.2

**Comment by crevetor** [comment]
Duplicate of [131053 ](https://github.com/home-assistant/core/issues/131053) closing.

@home-assistant close
