### ISSUE TITLE
Listening mode information

### ISSUE THREAD

**Issue by yzpmpgq** [home-assistant/home-assistant.github.io#35868]
### Feedback

I used the yaml onkyo integration for years and it worked great.  With the latest HA upgrades, i installed the Onkyo integration and the basics work fine, but I would like some documentation on adding additional options.  For example, I usd to use:
  - sensor:
      - name: "Listening Format"
        state: "{{ state_attr('media_player.onkyo', 'audio_information').format }}"
  - sensor:
      - name: Listening Mode
        state: "{{ state_attr('media_player.onkyo', 'audio_information').listening_mode }}"
  - sensor:
      - name: Listening inputch
        state: "{{ state_attr('media_player.onkyo', 'audio_information').input_channels }}"        
  - sensor:
      - name: Listening outch
        state: "{{ state_attr('media_player.onkyo', 'audio_information').output_channels }}"        
  - sensor:
      - name: Video outres
        state: "{{ state_attr('media_player.onkyo', 'video_information').output_resolution }}"  
  - sensor:
      - name: Video inres
        state: "{{ state_attr('media_player.onkyo', 'video_information').input_resolution }}"  

How do I accomplish the same thing now?

### URL

https://www.home-assistant.io/integrations/onkyo/

### Version

2024.11.2

**Comment by arturpragacz** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature or have additional questions, feel free to join our  [Community Forum](https://community.home-assistant.io/) or our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by arturpragacz** [comment]
@home-assistant close
