### ISSUE TITLE
add info how to restart D-Bus

### ISSUE THREAD

**Issue by nerdoc** [home-assistant/home-assistant.github.io#35901]
### Feedback

the page https://www.home-assistant.io/more-info/unhealthy/setup links to https://www.home-assistant.io/more-info/unsupported/dbus, and there it only says "start D-Bus". Even for an experienced Linux user like me it is not obvious how to do that under HA. There is no bash available where I can do a `systemctl start dbus`.
Maybe you add a line on where to start D-Bus under HA.

### URL

https://www.home-assistant.io/more-info/unsupported/dbus/

### Version

2024.11.3

**Comment by frenck** [comment]
> Even for an experienced Linux user like me it is not obvious how to do that under HA

I'm confused, this is not an Home Assistant thing. It is dbus on your host system, the system you maintain.

../Frenck

**Comment by nerdoc** [comment]
Oh, I forgot, I am using HA OS, in a proxmox container.

**Comment by frenck** [comment]
This error should not happen on an HAOS system, this page is targeted across Supervised installation method users, not Home Assistant operating system.

Please report this issue in the Supervisor issue tracker.

Thanks! 👍 

../Frenck

**Comment by nerdoc** [comment]
ok. Thanks.
