### ISSUE TITLE
Shelly Plus 2PM can't connect - Connection error: -15 / Invalid WebSocket handshake response

### ISSUE THREAD

**Issue by lanort** [home-assistant/home-assistant.github.io#35922]
### Feedback

Using Home Assistant 2014.11.3 and trying to integrate Shelly Plus2PM (FW 1.4.4)

Following the instructions I have set Outbound websoocket to wss://192.168.0.108:8123/api/shelly/ws and also tried ws://192.168.0.108:8123/api/shelly/ws, so with wss and ws protocol.

For **wss** I get the following in diagnostics:
```
shelly_http_client.:303 0x3ffe35ec: WSS wss://192.168.0.108:8123/api/shelly/ws (CA *)
07:10:47
shelly_http_client.:611 0x3ffe35ec: Finished; bytes 0, code 0, redir 0/3, auth 0, status -1: Connection error: -15
```

For **ws** the following is written in the logs:
```
shelly_http_client.:308 0x3ffe2c04: WS ws://192.168.0.108:8123/api/shelly/ws
07:14:58
shelly_http_client.:611 0x3ffe2c04: Finished; bytes 240, code 404, redir 0/3, auth 0, status -19: Invalid WebSocket handshake response
```

I also tried [wscat](https://github.com/websockets/wscat) for testing.

**WSS** has an SSL issue
```
> alexa@penguin:~$ wscat -n -c wss://192.168.0.108:8123/api/shelly/ws
error: write EPROTO 0058F2E75A7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:354:
```

**WS** is not found (404)
```
> alexa@penguin:~$ wscat -n -c ws://192.168.0.108:8123/api/shelly/ws
error: Unexpected server response: 404
```

On the other hand I could connect to the **standard websocket**:
```
> alexa@penguin:~$ wscat -n -c ws://192.168.0.108:8123/api/websocket
Connected (press CTRL+C to quit)
< {"type":"auth_required","ha_version":"2024.11.3"}
...
```

So it looks like there is an additional / different step needed as WS is not found at all, and WSS (even with ignoring TLS) fails as well.

If I try to **add a Shelly integration** with homeassistant I am asked for IP and port. If I enter the IP and port 80 it tells me, that the connection failed.

### URL

https://www.home-assistant.io/integrations/shelly/

### Version

2024.11.3

**Comment by bieniu** [comment]
Only battery powered devices needs websocket outbound. Plus 2PM doesn’t need it. This is clearly written in the documentation.
Besides that, this is a documentation repository, this isn’t a right place to open an issue related to the integration.
