### ISSUE TITLE
Xiaomi tv box

### ISSUE THREAD

**Issue by aartoudbier** [home-assistant/home-assistant.github.io#35949]
### Feedback

I tried everything you showed and a bunch of youtube videos and internet suggestions but I just can't get my tv on home assistant. I dont know what Im doing wrong what if there are other ways to do it. Please help.

### URL

https://www.home-assistant.io/integrations/xiaomi_tv/

### Version

2024.11.3

### Additional information

Mibox4

**Comment by aartoudbier** [comment]
Thats not what the problem is

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking documentation feedback, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
