### ISSUE TITLE
Riemann values?

### ISSUE THREAD

**Issue by n9yty** [home-assistant/home-assistant.github.io#35962]
### Feedback

It would be helpful for those who have never used this feature to have a better example of how to configure the energy produced and energy returned to grid.  It seems promising but it is elusive since I don't know what the steps are for the consumption meter configuration.

### URL

https://www.home-assistant.io/integrations/fronius/

### Version

2024.11.3

**Comment by farmio** [comment]
Hi 👋! 
Detailed instructions on how to configure that are found in the linked docs page of the Riemann sum integration. 
AFAIK all you need is to choose the right entity in the helper config, so really not that much to add imho... but if you can find better wording for the Fronius documentation, feel free to open a PR. Just remember that Riemann isn't part of Fronius, so it should be separated documents.

**Comment by n9yty** [comment]
Thanks, I'm re-reading it all and can make no sense of it...

Consumption path meter 
Recommended energy dashboard configuration for meter location in consumption path:

Use Riemann sum to integrate Power grid import and Power grid export entities into energy values (kWh).
Use these energy entities for Grid consumption and Return to grid in the energy dashboard configuration.


It tells me to use it, and gives some things like "Power grid import" and "Power grid export" but nothing saying what goes into the Riemann config.

I've tried googling to find other setup notes and come up empty. It would have been nice, but seems elusively out of my grasp.

I also find it odd that the Fronius plugin shows a SolarNet device that seems to be what I would need but I can't configure those in the energy dashboard.

Oh well, thanks for the reply, just can't figure it out for now.

**Comment by farmio** [comment]
> It tells me to use it, and gives some things like "Power grid import" and "Power grid export" but nothing saying what goes into the Riemann config

"Power grid import" and "Power grid export" are the (english) names of the 2 entities you'd need to set up with Riemann.

> I also find it odd that the Fronius plugin shows a SolarNet device that seems to be what I would need but I can't configure those in the energy dashboard.

For some cases the Fronius API only provides *power* values, the energy dashboard configuration requires *energy* values. That's where Riemann comes into play.

**Comment by n9yty** [comment]
Still greek to me. There are lots of fields on the Riemann dialog. This is what I meant, a few screenshots would have been very helpful. But I've taken enough of your time, I'm going to shelve it as unobtanium.

**Comment by n9yty** [comment]
Okay, I think I may have it.

Two helpers:

Go to Settings -> Helpers and select "+ Create Helper" button.

Select "Integral sensor".

Give it a name, choose "k" for metric prefix, set Hours for the time unit, and choose the input sensor, use "Left Riemann sum".  I didn't set precision or max sub-interval.

The sensor in my case was "SolarNet Power grid import" (sensor.solarnet_power_grid_import) or "SolarNet Power grid export" (sensor.solarnet_power_grid_export).

I set up both a helper for Energy Imported and Energy Exported.

In Energy Configuration:

Electricity Grid:
Grid consumption:  Energy Imported
Return to grid: Energy Exported

Solar panes:
Solar production:  Primo 10.0.1 208-240 (1) Total energy

It takes a while for data to populate as I understand it measures "power" over time to get "energy".

I won't know if this is working for sure or not because solar production is well over for the day at this point.

**Comment by farmio** [comment]
That sounds about right 👍
