### ISSUE TITLE
Change calibration factor usage

### ISSUE THREAD

**Issue by Jan-Jaap** [home-assistant/home-assistant.github.io#35969]
### Feedback

A simple change to calibration factor calculation would make it's usage more ituituative:

In the new calculation the calibration factor would be in the range 0..1 or a percentage correspoding with level of insulation.
0 or 0% would correspond with no insulation and crit_temp == outdoor_temp
1 or 100% would correspond with perfect insulation and crit_temp == indoor_temp

old documentation:
```
calibration_factor = (temp_indoor - temp_outdoor) / (temp_criticalpoint - temp_outdoor)
```

old code sensor.py :
```
# first calculate the approximate temperature at the calibration point
        self._crit_temp = ( self._outdoor_temp + (self._indoor_temp - self._outdoor_temp) / self._calib_factor )
```

new documentation: 
```
calibration_factor =  (temp_criticalpoint - temp_outdoor) / (temp_indoor - temp_outdoor)
```

new code sensor.py:
```
# first calculate the approximate temperature at the calibration point
        self._crit_temp = ( self._outdoor_temp + (self._indoor_temp - self._outdoor_temp) * self._calib_factor )
```

### URL

https://www.home-assistant.io/integrations/mold_indicator/

### Version

2024.11.3

**Comment by frenck** [comment]
Hi there @Jan-Jaap 👋 

Thanks for your comment. It seems like you want to suggest an improvement to the integration itself, however, you have submitted documentation feedback instead. There is no amount of documentation I can adjust to make the integration behave differently.

If you want to suggest a feature or improvement, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

../Frenck
