### ISSUE TITLE
Authentication expired? Invalid authentication?

### ISSUE THREAD

**Issue by Kaaremi** [home-assistant/home-assistant.github.io#35974]
### Feedback

The integration has served me well for about a year, but now all entities have turned unavailable. Password is correct, but I keep receiving the error message "Invalid authentication".

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2024.11.3

**Comment by rikroe** [comment]
This is a known issue. You have posted in the wrong repository, as `home-assistant/home-assistant.io` focuses on the documentation (and issues with it).

The correct one is `home-assistant/core` with issue https://github.com/home-assistant/core/issues/128598.

**Comment by rikroe** [comment]
@home-assistant close
