### ISSUE TITLE
Logboek waarschuwing: Detected code that accesses the database without the database executor

### ISSUE THREAD

**Issue by Gigabit99** [home-assistant/home-assistant.github.io#35973]
### Feedback

Hello,

In my explanation below I get the message Please report this issue.
So here is the message:
Logger: homeassistant.helpers.frame
Bron: helpers/frame.py:156
Eerst voorgekomen: 24 november 2024 om 13:57:19 (2 gebeurtenissen)
Laatst gelogd: 24 november 2024 om 13:57:19

Detected code that accesses the database without the database executor; Use homeassistant.components.recorder.get_instance(hass).async_add_executor_job() for faster database operations. Please report this issue.

I use HA on Synology NAS with VIrtual Machine Manager
Core 2024.11.3
Supervisor 2024.11.4
Operating System 13.2
Frontend 20241106.2

### URL

https://www.home-assistant.io/

### Version

2024.11.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
