### ISSUE TITLE
Forecast.Solar different azimuth

### ISSUE THREAD

**Issue by bobrowski** [home-assistant/home-assistant.github.io#35989]
### Feedback

your documentation is wrong for azimuths

you say 180deg is south, but https://doc.forecast.solar/api:estimate says south is 0deg

i have verified by pinging forecast solar api, 0 results in more W outputted than 180

### URL

https://www.home-assistant.io/integrations/forecast_solar/

### Version

2024.11.3

**Comment by bobrowski** [comment]
ok nevermind i see they have a note about this

**Comment by klaasnicolaas** [comment]
Where the API uses -180 to 180, the integration uses a circle from 0 to 360.

./Klaas
