### ISSUE TITLE
 implement the batterytemperature sensor

### ISSUE THREAD

**Issue by ChiliApple** [home-assistant/home-assistant.github.io#35986]
### Feedback

Hello,
would it be possible to implement the batterytemperature sensor as an entity? Tessie reads it in the app.
Thank you & best regards

### URL

https://www.home-assistant.io/integrations/tessie/

### Version

2024.11.3

**Comment by Bre77** [comment]
This issue is raised against the wrong repo, and is also a feature request not an issue.

Please post your request here: https://community.home-assistant.io/c/feature-requests/13

This is definitely something I can implement but is not high on my priority list.

**Comment by Bre77** [comment]
@home-assistant close
