### ISSUE TITLE
Breaking unavailable bug

### ISSUE THREAD

**Issue by air720boarder** [home-assistant/home-assistant.github.io#35999]
### Feedback

The current integration has a usage breaking bug, where 30-60 seconds after turning on, the device goes unavailable in homeassistant. There are numerous bug reports that go back over a year. 

### URL

https://www.home-assistant.io/integrations/twinkly/

### Version

2024.11.3

### Additional information

Please find the original contributor or encourage our community you take it over.

**Comment by klaasnicolaas** [comment]
Hi there  👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
