### ISSUE TITLE
More entities available?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [home-assistant/home-assistant.github.io#36002]
### Feedback

What about the inside temperature? If AC is started via remote the information about this temperature is rather important.
BR
Micha

### URL

https://www.home-assistant.io/integrations/renault/

### Version

2024.11.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by MichaelSchaaf999** [comment]
Thanks, Franck!
Added it to the Feature Requests then.

Best regards
Michael


Michael Claßen  | fon +49 172  52 33 6 33  | fax +49  7172  30 64 98 4   |  Härtsfeldstr. 1  73553 Alfdorf   | mail: ***@***.***



------ Originalnachricht ------
Von "Franck Nijhof" ***@***.******@***.***>>
An "home-assistant/home-assistant.io" ***@***.******@***.***>>
Cc "Michael Schaaf" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Datum 27.11.2024 08:54:31
Betreff Re: [home-assistant/home-assistant.io] More entities available? (Issue #36002)


Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our Community Forum: Feature Requests<https://community.home-assistant.io/c/feature-requests>.

If you have additional questions, feel free to join our Discord chat server<https://discord.gg/c5DvZ4e>.

Thanks! 👍
