### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by wiste95** [home-assistant/home-assistant.github.io#36046]
### Feedback

Hi there,
Is there a way to integrate the Fully Kiosk "acoustic motion sensor" as a switch entity in home assistant? 

I have a problem with my tablet in combination with Fully Kiosk and Home Assistant that my RAM runs full and as a result the browser or app crashes all the time, making the tablet inaccessible via Home Assistant. I use the acoustic motion sensor and have noticed that the RAM fills up most when my roborock is vacuuming at home. I would therefore like to deactivate the acoustic motion sensor with an automation for the time of cleaning.

### URL

https://www.home-assistant.io/integrations/fully_kiosk/

### Version

2024.11.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
