### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by gestature** [home-assistant/home-assistant.github.io#36056]
### Feedback

I was very impressed by the quality of your documentation.

Links to detailed articles, examples, even some notes to remove ambiguity. The form of it is very nice too.

Well done.

### URL

https://www.home-assistant.io/docs/automation/basics/

### Version

2024.11.3

**Comment by frenck** [comment]
Thanks for the compliments @gestature ❤️ 

That is appreciated! 😄 

../Frenck
