### ISSUE TITLE
"Captcha validation missing" error on setup

### ISSUE THREAD

**Issue by apzuckerman** [home-assistant/home-assistant.github.io#36064]
### Feedback

I'm getting a ""Captcha validation missing" error on setup when I put in my UN and PW. Any ideas?
![mini](https://github.com/user-attachments/assets/e5908680-21e2-4125-aaaf-027564938710)

### URL

https://www.home-assistant.io/integrations/bmw_connected_drive/

### Version

2024.11.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas

**Comment by rikroe** [comment]
See https://github.com/home-assistant/core/issues/128598.
