### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by cguay** [home-assistant/home-assistant.github.io#36086]
### Feedback

Instructions on how to add the cost per individual device. 

### URL

https://www.home-assistant.io/docs/energy/individual-devices/

### Version

2024.11.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
