### ISSUE TITLE
Typo in mqtt docs?

### ISSUE THREAD

**Issue by chelming** [home-assistant/home-assistant.github.io#36103]
### Feedback

It says "en availability." Is this a typo?

https://github.com/home-assistant/home-assistant.io/blob/current/source/_integrations/mqtt.markdown?plain=1#L959

### URL

https://www.home-assistant.io/integrations/mqtt/#discovery-messages-en-availability

**Comment by jbouwh** [comment]
It must have been my native behavior: `en` is Dutch for `and`.
