### ISSUE TITLE
Improve glossary

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant.github.io#3612]
If #3568 we introduced the new Glossary. Now, we need to make it as user-friendly as possible.

It's very simple to contribute, just edit/update/modify the [data file](https://github.com/home-assistant/home-assistant.github.io/blob/current/source/_data/glossary.yml), save it, create a PR and you are done.

**Comment by decode-dev** [comment]
@fabaff Would like to work on this?
Any instruction on this?

**Comment by arsaboo** [comment]
@decode-dev Just modify the [data file](https://github.com/home-assistant/home-assistant.github.io/blob/current/source/_data/glossary.yml) to update the glossary.

**Comment by fabaff** [comment]
To be clear: This glossary is about Home Assistant's terminology and the entry should be specific to Home Assistant.

**Comment by Maxr1998** [comment]
@fabaff what about some technical terms like Z-Wave/MQTT?

**Comment by DanielXYZ2000** [comment]
From my point of view Z-Wave and MQTT are not Home Assistant related. But I think it would be good to have also these technical terms in a glossary. 
Maybe we could make a general one? 
Or maybe the glossary entries could be tagged (hass, general,...)?

**Comment by fabaff** [comment]
Let's stick to terms which are relevant for Home Assistant.

**Comment by fabaff** [comment]
I think that if you can use a search engine for a term and get results we only would duplicate existing definitions. Sure, there is a grey area but if we start to create a glossary for "common" terms it would be a never ending list. 

I'm open-minded. The glossary is something new and if people think that it add value then we should do.

**Comment by fabaff** [comment]
@DanielXYZ2000 tagging should definitely be considered.

**Comment by Maxr1998** [comment]
@fabaff ok, thanks for clearing that up.
