### ISSUE TITLE
Setup and prerequisite information for Documentation re bridge and app

### ISSUE THREAD

**Issue by 6ffm70** [home-assistant/home-assistant.github.io#36134]
### Feedback

@LennP, @jerrybboy, thank you for providing this! Just checking whether to buy one of the Motionblinds Bluetooth motors, and looking if they go well with HA. Two things don't become clear:
- is any (official) bridge required? Probably some words on practical application seeing that most Zigbee or Wifi installations have networks throughout the home, but Bluetooth rarely.
- is the official app required for setup?

### URL

https://www.home-assistant.io/integrations/motionblinds_ble/

### Version

2024.11.3

### Additional information

none

**Comment by LennP** [comment]
Hi!

> - is any (official) bridge required? Probably some words on practical application seeing that most Zigbee or Wifi installations have networks throughout the home, but Bluetooth rarely.

No, the motors work with plain Bluetooth without need for an official bridge. Most Motionblinds motors also support 433MHz, but support for that is provided by the [Motionblinds](https://www.home-assistant.io/integrations/motion_blinds/) integration, and 433MHz does require a bridge. The other main difference is that using Bluetooth, HA first needs to establish a connection to the motor causing a slight delay, which is not the case with 433MHz as it does not require a connection. However, depending on the location you want to install your blinds and whether or not your device that HA is running on has a Bluetooth adapter, it could be useful to install an [ESPHome Bluetooth proxy](https://esphome.io/components/bluetooth_proxy.html). But Motionblinds Bluetooth motors will also work fine without such a proxy given the motor is sufficiently close to your device running HA.

> - is the official app required for setup?

I think you should be able to do pretty much everything without the app (programming end limits, etc). The HA integration contains pretty much everything that the mobile app has (apart from configuring end limits which can also be done using physical buttons on most motors I believe, and setting timers within the motor that automatically move the blind at a set time). Which Motionblinds motor are you looking to buy?

@jerrybboy

**Comment by jerrybboy** [comment]
@6ffm70 as LennP has explained a bridge is not needed and most functions that the bridge gives you will be similar to what the bluetooth integration does. The downside right now is that the bluetooth integration does not update the position when someone interacts with the blind through a remote control or by pull function. If you use a bridge this will be updated. This might be added in the future for the bluetooth integration. 

For setting up the end limits of the blind we recommend using the bluetooth app or using the physical buttons on the motor (Depending on motor type). After setup is done you can simply use the integration in HA. As you explained it is necessary to have some Bluetooth proxies or a dongle in your home in order for it to work. 

If you don't want to make this, you can always have a look at our bridge for instance the CMD-01. The bridge needs a cloud for setup, but once setup you can use the local api integration in order for it to work with HA.

**Comment by 6ffm70** [comment]
Cheers guys. I'm looking to test a MotionBlinds CMD-03 Bluetooth, and will give this a go. Fortunately, it's in the same room with the HA instance with BT activated. I'll foresee the BT proxies when I get more blinds for my flat next summer.

@jerrybboy the remark about manual position update and its current limitation might also be important for the documentation page - seeing that some people first look into the official HA documentation for integration status _before_ buying.
