### ISSUE TITLE
Finding an H5100?

### ISSUE THREAD

**Issue by apzuckerman** [home-assistant/home-assistant.github.io#36132]
### Feedback

I have an H5100 that I can see via the Govee app, but when I try to set it up in HA (add integration -> Bluetooth) it returns an error: "No devices found on the network". 

Any ideas on how to get it added? Thanks!

### URL

https://www.home-assistant.io/integrations/govee_ble/

### Version

2024.11.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
