### ISSUE TITLE
Information on how to download to external directories

### ISSUE THREAD

**Issue by ErnstHKStelzer** [home-assistant/home-assistant.github.io#36149]
### Feedback

Hello, I am using HA to take a snap shots with a **Blink camera** and store them in a `/config/tmp` subdirectory. This works fine. I then select the files e.g. in Studio Code, right click and use `Download..` to transfer the jpg-files to my Mac's `Downloads directory`. I noticed that there seem to be solutions in the **community comments** on how to access an external directory directly, otherwise `Download..` would not work. Therefore, I was wondering if it would not make sense to include up-to-date examples for access to external directories in your documentation, since I am definitely not the only person with a specific interest in a solid HA-conform solution. Sincerely Ernst Stelzer

### URL

https://www.home-assistant.io/integrations/downloader/

### Version

2024.11.3

**Comment by erwindouna** [comment]
The Download integration is not supporting to download to external directories, since it's based on the filesystem of your HA installation. It's not in its scope to support a direct download, like the browser allows you your local machine.
