### ISSUE TITLE
Wait for confirmation please

### ISSUE THREAD

**Issue by hl1234** [home-assistant/home-assistant.github.io#36159]
### Feedback

While on my iPad, I opened the card on settings announcing the new version.  I browsed the release notes then accidentally touched the Update option instead of Skip. So off to the races with the new update. For something as significant as an update it seems like an additional confirmation step would be beneficial. Yes I was logged in as admin but I use the iPad to be able to go around the house easily as I try to figure out this and that since I am only about 2 weeks along this journey. 

Sorry if this is a duplicate. 

### URL

https://www.home-assistant.io/integrations/update/

### Version

2024.11.3

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
