### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by vAFaLgCevpk3j6** [home-assistant/home-assistant.github.io#36166]
### Feedback

I am trying to find out how to format the Heading Card configuration in Sections.  I can't find any information on how to make the heading bold or make the font larger.  I would be very helpful to have an example here.

### URL

https://www.home-assistant.io/dashboards/heading/

### Version

2024.12.0

**Comment by frenck** [comment]
>  I can't find any information on how to make the heading bold or make the font larger.

There are not options for those, so it is correct these are not documented 👍 

../Frenck
