### ISSUE TITLE
Feature wanted from the Hacs variant of the nordpol integration

### ISSUE THREAD

**Issue by Ferdinand99** [home-assistant/home-assistant.github.io#36178]
### Feedback

In the Hacs version of the Nordpol integration there is one sensor with attributes of the power price for the whole day. I would like to see a sensor like this for easier automation of example hot water.

I also miss the opportunity to se a difference in the price where my power delivery company is giving a discount on the price for 12 months. I would love to add this as an "additional cost" section when setting up areas and currency

### URL

https://www.home-assistant.io/integrations/nordpool/

### Version

2024.12.0

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
