### ISSUE TITLE
c100 returns error 500 to passthrough

### ISSUE THREAD

**Issue by TheLich2112** [home-assistant/home-assistant.github.io#36177]
### Feedback

The latest update of 05/12/24 showed that the c100 I have here is again recognized, I thought great this should be easy.. Famous last words, error code 500 to passthrough! wow where do I even start debugging that? googlefu failed too :( might just have to implement Pi Zero's all over the house instead :)

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.12.0

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
