### ISSUE TITLE
Can I add air purifiers to the list of supported devices? Cobos air purifiers have Z series (models such as Z1) and have many demand groups. I hope the big shots will consider it.

### ISSUE THREAD

**Issue by JonXman** [home-assistant/home-assistant.github.io#36182]
### Feedback

Can I add air purifiers to the list of supported devices?
Cobos air purifiers have Z series (models such as Z1) and have many demand groups. I hope the big shots will consider it.

### URL

https://www.home-assistant.io/integrations/ecovacs/

### Version

2024.12.0

**Comment by mib1185** [comment]
Do you ask us to add support for this device to the integration or did you already tested the device and can confirm it is working with the integration?

**Comment by JonXman** [comment]
> 您是否要求我们将对此设备的支持添加到集成中，或者您是否已经测试了该设备并可以确认它正在与集成配合使用？

Yes, boss. The air purifier "沁宝Z1" and the air quality detector "Z1检测仪" in the link https://www.ecovacs.cn/atmbot/airbotz1 are currently not in the integrated support equipment list. The above devices will be recognized as sweaters in versions before core version 2024.12.0, but they will not be recognized at all since core version 2024.12.0.
It is desirable to add these devices to the integrated device support list and use the device's functions correctly.

**Comment by mib1185** [comment]
this sounds like an issue report, not a documentatuon feedback. Further there are already similar issue reported, that prior working devices do not anymore since 2024.12 update. This is caused by some necessary changes in the underlying library. Please follow https://github.com/home-assistant/core/issues/132335
