### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by petitpiton** [home-assistant/home-assistant.github.io#36187]
### Feedback

Husqvarna have announced the API is being replaced with a new version from February next year. The new API will be available to develop against from 20 December 2024. 
https://app.qa-developer-portal.dss.husqvarnagroup.net/news/added-new-event-format

### URL

https://www.home-assistant.io/integrations/husqvarna_automower/

### Version

2024.12.0

**Comment by Thomas55555** [comment]
This repository is for doumentation. There is an "issue" in the core repository:
https://github.com/home-assistant/core/issues/132720
So I'm closing this.

**Comment by Thomas55555** [comment]
@home-assistant close
