### ISSUE TITLE
Specify what user should execute hass command

### ISSUE THREAD

**Issue by LucaVs** [home-assistant/home-assistant.github.io#36198]
### Feedback

In the tutorial it's not specified what user to use to when executing the hass command for the first time.

### URL

https://www.home-assistant.io/installation/raspberrypi-other/

### Version

2024.3.3

**Comment by frenck** [comment]
Unless I'm missing something, it actually is.

If the guide is followed step-by-step as provided, it will result in using the user-created and switched to.

![CleanShot 2024-12-06 at 20 17 08](https://github.com/user-attachments/assets/15cafb25-3174-4d6d-a59f-2bb3fef59dfa)

../Frenck
