### ISSUE TITLE
scene support

### ISSUE THREAD

**Issue by redeyef15** [home-assistant/home-assistant.github.io#36207]
### Feedback

It would be nice if a scene could be selected when automation is accomplished 

### URL

https://www.home-assistant.io/integrations/govee_light_local/

### Version

2024.12.1

### Additional information

I'm trying to use the toggle on, but a color is needed to be selected.  I must manually select a scene after the automation runs and turns the light string on.

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
