### ISSUE TITLE
Voice recognition

### ISSUE THREAD

**Issue by Boudicca1000** [home-assistant/home-assistant.github.io#36212]
### Feedback

good day, i´m an user from germany. i do have the s3 integration and also the hardware according to the specification. certain probs turning up: i have a phrase: erker licht an. the response of the system is: RK is not recognized. seems to be a buck?????? :) sorry for trbls. Kai

### URL

https://www.home-assistant.io/voice_control/

### Version

2024.12.1

### Additional information

non

**Comment by klaasnicolaas** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

./Klaas
