### ISSUE TITLE
bug: input_text can be set to maximum characters length 5000

### ISSUE THREAD

**Issue by helgek** [home-assistant/home-assistant.github.io#36219]
### Feedback

<img width="696" alt="Screenshot 2024-12-08 at 05 16 03" src="https://github.com/user-attachments/assets/6d2158c9-3d0b-43d3-9549-1a51600027cc">

In the UI for the input_text settings HA accepts and keeps 5000 as maximum character length setting although it only accepts 255. This is very confusing.

### URL

https://www.home-assistant.io/integrations/input_text/

### Version

2024.12.1

**Comment by frenck** [comment]
Quick check: I can't reproduce this issue: 

![CleanShot 2024-12-11 at 09 54 20](https://github.com/user-attachments/assets/f5a1b48a-39d9-461c-919c-8371c428809a)


That said, you have submitted documentation feedback, while you tried to report an issue with the Home Assistant frontend. Please check if you can still reproduce the issue, if so, please report it here:

<https://github.com/home-assistant/frontend/issues>

Thanks 👍 

../Frenck
