### ISSUE TITLE
3day blinds integration

### ISSUE THREAD

**Issue by conceptnext** [home-assistant/home-assistant.github.io#36213]
### Feedback

These steps apply to anyone who has 3Dayblinds and hub installed and looking to access the API Key via the 3DayBlinds iOS 
![IMG_8058B27E4E30-1](https://github.com/user-attachments/assets/4acbcada-a697-4818-8afb-b1192a493fe3)
App

1. Start at 3 Day Blinds App home screen
2. Select “hamburger” icon on upper left
3. Select “gear” icon in upper left
4. Select “About” from the bottom
5. Quickly tap the 3 Day Blinds icon in the center of the screen 5 times
API key is presented

Key can be input into the Motoinblinds integration. Side note that I ran into: make sure UDP Port 32100 is open from Home Assistant to the 3 Day Blinds bridge.

### URL

https://www.home-assistant.io/integrations/motion_blinds/

### Version

2024.12.1

**Comment by starkillerOG** [comment]
I added specific instructions for the 3day blinds app: https://github.com/home-assistant/home-assistant.io/pull/36231
although they are basically identical to all the other apps.
Feel free to fine tune the documentation by opening a PR.

If you appreciate the motion blinds integration and want to support its development, please consider [sponsering](https://github.com/sponsors/starkillerOG) the upstream library.
