### ISSUE TITLE
Add Unique ID

### ISSUE THREAD

**Issue by epcodijk** [home-assistant/home-assistant.github.io#36214]
### Feedback

I’m unable to edit the NAD platform due to a missing unique_id. I’ve tried to manually add it with the NAD D-7050 MAC address but after restarting HA an error due to unique_id not being a valid entry.

Logger: homeassistant.config
Bron: config.py:942
Eerst voorgekomen: 18:39:03 (1 gebeurtenissen)
Laatst gelogd: 18:39:03

Invalid config for 'media_player' from integration 'nad' at configuration.yaml, line 36: 'unique_id' is an invalid option for 'nad.media_player', check: unique_id, please check the docs at https://www.home-assistant.io/integrations/nad

### URL

https://www.home-assistant.io/integrations/nad/

### Version

2024.12.1

**Comment by frenck** [comment]
Hi there 👋 

You can't add unique IDs, that is a limitation not a configuration.
The documentation is thus correctly not listing that option.

../Frenck
