### ISSUE TITLE
Home assistant OS wrong configuration path

### ISSUE THREAD

**Issue by lunix33** [home-assistant/home-assistant.github.io#36215]
### Feedback

The documentation on "How to find the configuration directory" says the following when using Home Assistant OS:

> Home Assistant Operating System: the configuration.yaml is in the /config folder of the installation.

And also shows a way to validate the path from the UI. But from my experience both of those are wrong.

From the UI, it shows the configuration directory from within the docker container, which isn't the path on the actual device.
Inspecting the docker container, I figured out the actual path is `/mnt/data/supervisor/homeassistant`, the path `/config` simply doesn't exists.

I'm using the following versions:
- Core: core-2024.12.1
- Supervisor: supervisor-2024.11.4
- OS: Home Assistant OS 14.0

I'm running Home Assistant OS in a KVM VM within Proxmox.

### URL

https://www.home-assistant.io/docs/configuration/

### Version

2024.12.1

**Comment by frenck** [comment]
Hi there @lunix33 👋 

The documentation is correct.

You are correct as well, but it isn't meant to be approached from the OS level. The OS can be accessed for debug purposes, but isn't needed for daily use.

Nevertheless, thanks for your feedback 👍 


../Frenck
