### ISSUE TITLE
WebControlPro device itself is integrated, not the blinds.

### ISSUE THREAD

**Issue by TommyKuehne** [home-assistant/home-assistant.github.io#36222]
### Feedback

I have added WebControlPro to the network and can easily control the 6 Warema blinds via browser/app.

I have also integrated WebControlPro into Home Assistant

However, only the WebControlPro device itself is integrated, not the blinds.

Mr. Krebs from Warema Support was able to recreate this with the same effect. Only the WebControl Pro was integrated, but not the blinds.

### URL

https://www.home-assistant.io/integrations/wmspro/

### Version

2024.12.1

**Comment by mback2k** [comment]
Blinds are not yet supported. The docs state awnings, lights and scenes. Sorry, but I didn't have time to support blinds yet.

**Comment by mback2k** [comment]
@home-assistant close
