### ISSUE TITLE
Rename "Home/Away" to "Connected/Disconnected"

### ISSUE THREAD

**Issue by Maxterious** [home-assistant/home-assistant.github.io#36236]
### Feedback

Since the homeassistant app also uses "Home" and "Away" it can be confusing if this state is either from the App or FritzBox integration. Especially when the device is named the same in both integrations. Furthermore the state connected/disconnected seems technically more precise then "home/away". 
I hope this is the right place to give feedback :)

### URL

https://www.home-assistant.io/integrations/fritz/

### Version

2024.12.1

**Comment by mib1185** [comment]
Hi @Maxterious 

you're giving feedback to the documentation, but not the integration itself.
Further we use GitHub for tracking issues/bugs with Home Assistant itself, not for providing support - you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://www.home-assistant.io/join-chat) to discuss such architectural change requests

Thanks! 👍
