### ISSUE TITLE
unit_of_measurement purpose unclear, needs an example

### ISSUE THREAD

**Issue by didier9** [home-assistant/home-assistant.github.io#36242]
### Feedback

the article shows the two types of graphs and says that to obtain the second type (the plot over time), there needs to be a "unit_of_measurement" but that is not present in the example. On my Home Assistant setup, entering a unit of measurement (degree C in my case) does not result in a plot

### URL

https://www.home-assistant.io/dashboards/history-graph/

### Version

2024.12.1

**Comment by frenck** [comment]
> there needs to be a "unit_of_measurement" but that is not present in the example

It refers to the sensor used (sensors have values with units), not the graph.

../Frenck
