### ISSUE TITLE
Deebot documentation not reporting supported devices

### ISSUE THREAD

**Issue by msavazzi** [home-assistant/home-assistant.github.io#36259]
### Feedback

The last change in the integration has introduces a major issue and several, if not quite all, devices are not working anymore.
The documentation page does not report the breaking change, does not provide information on how to diagnose and solve, how to configure devices

### URL

https://www.home-assistant.io/integrations/ecovacs

### Version

Core 2024.12.1

### Additional information

linked to issue [https://github.com/home-assistant/core/issues/132335#issuecomment-2528306434](url)

**Comment by mib1185** [comment]
That's not correct, the breaking change is (_as usual_) mentioned in the [release notes of 2024.12](https://www.home-assistant.io/blog/2024/12/04/release-202412/#backward-incompatible-changes), further there is a proper [Troubleshooting](https://www.home-assistant.io/integrations/ecovacs#troubleshooting) section in the Ecovacs documentation.
