### ISSUE TITLE
Missing pages revision number or revision date

### ISSUE THREAD

**Issue by NicolaP8** [home-assistant/home-assistant.github.io#36260]
### Feedback

It's very difficult to track updates on documentation without any reference.
Eg. in the provided URL there is a "new" variable (platform) from the last time i checked that page.
Having at least the date of last modification would be important.

### URL

https://www.home-assistant.io/integrations/button.mqtt/

**Comment by frenck** [comment]
Adding just a last modified date, wouldn't really help IMHO.

Nevertheless, all our documentation is under full version control, so you can look up all the history in any point in time you'd like.

For example, for this page, on the current stable documentation branch: <https://github.com/home-assistant/home-assistant.io/commits/current/source/_integrations/button.mqtt.markdown>

../Frenck
