### ISSUE TITLE
tile card wasted space

### ISSUE THREAD

**Issue by NewAstronaut7451** [home-assistant/home-assistant.github.io#36268]
### Feedback

Why is the tile card enforcing a minimum size size that wastes so much screen space? 

It will not allow small buttons.

### URL

https://www.home-assistant.io/dashboards/tile/

### Version

2024.12.1

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
