### ISSUE TITLE
Hunter Hydrawisw

### ISSUE THREAD

**Issue by Lgagnon43** [home-assistant/home-assistant.github.io#36266]
### Feedback

It is not possible to connect to de integration this is some time that it is not working :(

### URL

https://www.home-assistant.io/integrations/hydrawise/

### Version

2024.12.1

### Additional information

connection impossible

**Comment by dknowles2** [comment]
See https://github.com/home-assistant/core/issues/130857

**Comment by dknowles2** [comment]
@home-assistant close
