### ISSUE TITLE
Controll same Raspberry Pi GPIO with home assistant

### ISSUE THREAD

**Issue by kodonci** [home-assistant/home-assistant.github.io#36279]
### Feedback

I would like to controll that Raspberry Pi 4's GPIOs which one is running the home assistant system. Is this possible?

### URL

https://www.home-assistant.io/integrations/remote_rpi_gpio/

### Version

2024.12.1

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
