### ISSUE TITLE
Shark Integration "fails to setup"

### ISSUE THREAD

**Issue by michguy2000** [home-assistant/home-assistant.github.io#36307]
### Feedback

Hello.  For about the last three weeks, Shark Integration will not load.  I believe it to be an authentication issue.  Both of my vacuums have been down in Home Assistant, but have worked without issue for months.  They now only work in the Shark, Google Home and Alexa apps.   I contacted Shark, but they are not able to provide me with any help.  We tried deleting the devices, but that only resulted in my not being able to add the shark integration/devices back into HA.  I had to restore to my previous nights image in order to get them back, even though I cannot use them.  I cannot find any log entries for this, so if there is a specific area I should be looking I'm happy to provide you with the info.
Thanks for any assistance.

Current Versions:
Core 2024.12.1
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.6

### URL

https://www.home-assistant.io/integrations/sharkiq/

### Version

2024.12.2

**Comment by michguy2000** [comment]
![Shark Integration error](https://github.com/user-attachments/assets/7d86d1fe-d3b9-43ff-a508-9f979de2a877)

**Comment by DysfunktionalSD** [comment]
Same issue for me. Hoping someone can shed some light since j switched from Roomba to this thinking the integration would work as I upgraded my vacuum.

**Comment by Lucas319315** [comment]
I am having this same issue and I cannot get it to connect in. This was working in the past.

**Comment by frenck** [comment]
Hi there @michguy2000 👋 

It seems like you want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

../Frenck
