### ISSUE TITLE
Voice setup

### ISSUE THREAD

**Issue by PGutti** [home-assistant/home-assistant.github.io#36309]
### Feedback

I try to use Voice commands to switch lights on/off.  The entity is exposed. I can write the command and it es executed. BUT the microphone is not accessible. So i have voice assistant without voice. 
![Captura 2024-12-12 a las 8 56 16](https://github.com/user-attachments/assets/1d99b321-849e-4bb4-9bf6-3f737e12e274)

I would use voice at home only. From remote i can use the usual HA UI. 

If this is possible without modifying SSH ... pls explain it in this chapter

### URL

https://www.home-assistant.io/voice_control/

### Version

2024.12.2

**Comment by frenck** [comment]
It is not possible, as the dialog explains, the browser doesn't give access to the microphone without it.

../Frenck

**Comment by PGutti** [comment]
Hi FranckI meant that The documentation should explain better what to do. I enabled a light entity and gave it a name. Now I can write “entity on”.  But when talking it’s not understood. Same in deutsch. May be the system can be trained?!?Saludos GrüssePeter Güttinger-––————————————————El 12 dic 2024, a las 9:03, Franck Nijhof ***@***.***> escribió:﻿
It is not possible, as the dialog explains, the browser doesn't give access to the microphone without it.
../Frenck
