### ISSUE TITLE
No firmware version

### ISSUE THREAD

**Issue by timpauladams** [home-assistant/home-assistant.github.io#36306]
### Feedback

Please can we add the ability to see firmware and advise on new firmware releases? 

### URL

https://www.home-assistant.io/integrations/solaredge/

### Version

2024.12.2

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
