### ISSUE TITLE
Question about how to find the PW for the reolink device

### ISSUE THREAD

**Issue by apzuckerman** [home-assistant/home-assistant.github.io#36315]
### Feedback

I'm having trouble with the Home Assistant authentication screen after a camera was discovered. Where can I find the device password? I tried the Reolink pw but can't seem to get this to work. 

Thanks!
![reolink](https://github.com/user-attachments/assets/4c192a98-2864-45ce-ab30-06fa5b6a7124)

### URL

https://www.home-assistant.io/integrations/reolink/

### Version

2024.12.2

**Comment by starkillerOG** [comment]
Already answered on reddit: https://www.reddit.com/r/reolinkcam/s/TqOCD1MerQ
