### ISSUE TITLE
Tapo Cameras

### ISSUE THREAD

**Issue by Slimhaven** [home-assistant/home-assistant.github.io#36320]
### Feedback

It doesn't matter what Ido Home Assistantt refuses my TP-Link Credentials. I have tried at least twenty times and it still says I ma wrong. I log out of TP-Link and log back in with the ones I am using to try and make Home Assistant work and it logs me in without fail. This is the first time HA has failed me and it is definitely on HA end not TP-Link. Any thoughts on making this problem go away will be greatly appreciated. 

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.12.2

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
