### ISSUE TITLE
Parametri di configurazione

### ISSUE THREAD

**Issue by DESAF78** [home-assistant/home-assistant.github.io#36339]
### Feedback

Non è chiaro dove si possano trovare i parametri di configurazione sia per il 
Serial bridge che per il Vedo system. (Porta e PIN)

### URL

https://www.home-assistant.io/integrations/comelit/

### Version

2024.12.3

**Comment by chemelli74** [comment]
I bet you are connecting via web page or Comelit app to your system. You should then be able to retrive the port from there.

About the PIN, this is the one you use to login (Bridge) or enable/disable alarm (Vedo).

**Comment by DESAF78** [comment]
Ok, but I Have a problem because my first pin number is a 0 and the
interface not admit it.
*Fabio de Santis*



Il giorno sab 14 dic 2024 alle ore 14:39 Simone Chemelli <
***@***.***> ha scritto:

**Comment by chemelli74** [comment]
> Ok, but I Have a problem because my first pin number is a 0 and the interface not admit it. 

If you have a problem, you should open a issue on the core repo.
This repo is for documentation only.
