### ISSUE TITLE
Sure Petcare HomeAssistant Integration

### ISSUE THREAD

**Issue by oliver70112** [home-assistant/home-assistant.github.io#36335]
### Feedback

Not an issue but functionality request.  I am looking to change the indoor mode for my cats. Is that something you could add?  Or does Sure Petcare not allow access to that feature?

Thanks

### URL

https://www.home-assistant.io/integrations/surepetcare/

### Version

2024.12.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
