### ISSUE TITLE
impossible de configurer 

### ISSUE THREAD

**Issue by voyagers21** [home-assistant/home-assistant.github.io#36345]
### Feedback

Bonjour l'inviter sur la Freebox ne s'ouvre jamais je ne peux donc pas valider la connexion, freebox pop dernière version

### URL

https://www.home-assistant.io/integrations/freebox/

### Version

2024.12.3

**Comment by frenck** [comment]
Hi there @voyagers21 👋 

Thanks for your documentation feedback, however, we are an English speaking community. Unfortunately, we don't speak this language; therefore closing this issue.

../Frenck
