### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by FriGiN** [home-assistant/home-assistant.github.io#36340]
### Feedback

egads i can not make the "THANK YOU" big enough. I've been trying to beat my head against a wall for a couple days. why oh why cant this be added to integrations or even hacs!!! please oh lord please.

### URL

https://www.home-assistant.io/integrations/tplink/

### Version

2024.12.3

**Comment by frenck** [comment]
> why oh why cant this be added to integrations or even hacs!!! 

This is in core and shipped built-in into Home Assistant.

../Frenck
