### ISSUE TITLE
Unifi Protect AI Sensors not updating

### ISSUE THREAD

**Issue by bbow987** [home-assistant/home-assistant.github.io#36353]
### Feedback

Hi team, having issues with the sensor update on an AI Pro camera for 'License Plate Detection'.

'License Plate Detection' state never moves from 'clear' despite confirmation it does so in the unifi protect app. Confirmed all other sensors are working, as motion and person/vehicle detection update as applicable. 

### URL

https://www.home-assistant.io/integrations/unifiprotect/

### Version

2024.12.3

**Comment by RaHehl** [comment]
Hi @bbow987,

this repo is related to the Homeassistant Website, please raise an issue at https://github.com/home-assistant/core/issues

**Comment by RaHehl** [comment]
@home-assistant close
