### ISSUE TITLE
AVM FRITZ!Box Call Monitor Example YAML Code fail

### ISSUE THREAD

**Issue by ErnstHKStelzer** [home-assistant/home-assistant.github.io#36362]
### Feedback

The example cannot be used. Complains about data. `Message malformed: extra keys not allowed @ data['automation'].` I know that some changes were made to YAML orders and namings but I assume you will see the issues immediately. Sorry for not being helpful.

### URL

https://www.home-assistant.io/integrations/fritzbox_callmonitor/

### Version

2024.12.3

**Comment by cdce8p** [comment]
Hey @ErnstHKStelzer, thanks for the issue. Are you sure about it? I just added the example form the docs to my test instance and it seems to work fine.

Could you double check, especially if the indentation is correct? Note also that you'll need to remove `automation:` if you're inserting it directly into `automations.yaml`.

**Comment by ErnstHKStelzer** [comment]
Hey @cdce8p, thank you very much for your quick response. At least I have a version that I can save. I will respond in more detail by Thursday. I am currently traveling.

**Comment by ErnstHKStelzer** [comment]
@cdce8p As you suggested, I made a mistake and have to remove `Automation:`.  I try to avoid the `automation.yaml` file and use `Automations & scenes` instead. Nevertheless, could you add a reference to the documentation on `from_name, ...` ? I also added a `variable`, but I failed to have a single `sensor.fritz_..._call_monitor_telefonbuch`, instead of the current two. I usually keep my documents & comments with code but comments are removed.

```
alias: FRITZ!Phone Status
description: AVM FRITZ!Phone Status V1.1
triggers:
  - trigger: state
    entity_id: sensor.fritz_box_7590_ax_call_monitor_telefonbuch
conditions: []
actions:
  - action: notify.mobile_app_ernst_iphone_16_pro
    metadata: {}
    data:
      title: Phone
      message: |-
        {% if is_state(sensorphone, "idle") %}
          Phone is idle
        {% elif is_state(sensorphone, "dialing") %}
          Calling {{ state_attr(sensorphone, 'to_name') }} ({{ state_attr(sensorphone, 'to') }})
        {% elif is_state(sensorphone, "ringing") %}
          Incoming call from {{ state_attr(sensorphone, 'from_name') }} ({{ state_attr(sensorphone, 'from') }})
        {% else %}
          Talking to {{ state_attr(sensorphone, 'with_name') }} ({{ state_attr(sensorphone, 'with') }})
        {% endif %}
variables:
  sensorphone: sensor.fritz_box_7590_ax_call_monitor_telefonbuch
mode: single

```

**Comment by cdce8p** [comment]
> Nevertheless, could you add a reference to the documentation on `from_name, ...` ?

Could you explain in a bit more detail what exactly it is you'd like me to do? `from_name` is already included in the docs example.

**Comment by ErnstHKStelzer** [comment]
@cdce8p I understand that the set of available attributes varies according to the phone's status. This can be followed in the `Developer Tools States`. I assume that the attributes and their values are documented by AVM. If that is the case it might be useful to indicate where this documentation can be found. If not, as you point out, your docs example contains all the required and available information.

**Comment by ErnstHKStelzer** [comment]
@cdce8p I also found a workaround that uses the variable `sensorphone`.
```
...
triggers:
  - value_template: "{{ states(sensorphone) }}"
    trigger: template
conditions: []
...
```

**Comment by cdce8p** [comment]
> I assume that the attributes and their values are documented by AVM.

This is the official AVM site for their dev docs: https://avm.de/service/schnittstellen/
However, I couldn't find it there. The library documentation is actually more helpful but I don't think it should be part of the Home Assistant docs. https://fritzconnection.readthedocs.io/en/1.14.0/sources/call_monitoring.html

_Anyway, going to mark this issue as resolved now then._
