### ISSUE TITLE
Qingping Air Quality Monitor CSG2 support

### ISSUE THREAD

**Issue by felafel** [home-assistant/home-assistant.github.io#36392]
### Feedback

Are there plans to integrate this device into the Qingping integration?

Thanks

### URL

https://www.home-assistant.io/integrations/qingping/

### Version

2024.12.3

**Comment by klaasnicolaas** [comment]
Thank you for reaching out.

We use GitHub for tracking issues, not for tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

Thanks! 👍
