### ISSUE TITLE
Appears broken in 2024.12.3

### ISSUE THREAD

**Issue by starman2k01** [home-assistant/home-assistant.github.io#36390]
### Feedback

Worked immediately before upgrade to 2024.12.x; now can't connect to Shield at same IP address. "failed setup, will retry"

### URL

https://www.home-assistant.io/integrations/nfandroidtv/

### Version

2024.12.3

**Comment by frenck** [comment]
Hi there @starman2k01 👋 

It seems like you want to report an issue with an Home Assistant integration. However, you have submitted documentation feedback instead. Please report issues with integrations here:

<https://github.com/home-assistant/core/issues>

Thanks 👍 

../Frenck

**Comment by starman2k01** [comment]
Roger that. Turns out it was a crashed Android app that was the problem.
