### ISSUE TITLE
System Service Data from Bryan Evolution SAM Integration

### ISSUE THREAD

**Issue by bryanvaz** [home-assistant/home-assistant.github.io#36401]
### Feedback

I'm trying to figure out how to pull all the data in the HVAC Tech's Service menu into a proper data logger (normally found by holding the"Service" button on the thermostat for 10 seconds waiting for the icon to turn green). 

@danielsmyers when you built the SAM integration, was there any mention of how to pull the more detailed real-time unit data from the bus? The data fields would normally be the following:

**Furnace Status**

- Gas heat: 100%
- Indoor Airflow CFM: 745
- Blower RPM: 808
- Static pressure: 0.50
- Inducer RPM: 0
- Leaving Air Temperature: N/A
- Lockout time left: -
  - 33-LIMIT FAULT

**Heat Pump Status**

- Heat pump heating: off
- Compressor RPM: 0 RPM
- Outdoor coil temperature: 47 F
- Suction pressure: 136 PSI
- Suction temperature: 47 F
- Suction superheat: 0 F
- Discharge temperature: 69 F
- Line Voltage: 207 V
- Outside Temperature: 48 F
- Curtailment: NO
- Indoor airflow CFM: 357 CFM
- Static pressure: 0.16 inches
- Lockout timer: 89 minutes
- Blower RPM: 430 RPM
- Discharge Pressure: 136 PSI
- Discharge superheat: 21.23 F
- Outdoor Fan RPM: 0 RPM
- Heating EXV Position: 0%
- Vapor injection EXV position N/A
- Low Ambient Cooling: ON
- AC line current: 0.0 A
- DC bus voltage: 0.0 V
- PFCM temperature: 0.0 F
- IPM temperature: 0.0 F

### URL

https://www.home-assistant.io/integrations/bryant_evolution/

### Version

2024.12.4

**Comment by danielsmyers** [comment]
Hi Bryan,

I'm afraid I'm of no help here -- the integration I wrote uses the Bryant
serial protocol, which AFAICT does not expose this data.

Docs for the protocol are here:
https://www.behler-young.com/UserFiles/Resource/APSAM01-03.pdf

**Comment by bryanvaz** [comment]
Sad beans. 

Based on the disclaimer on page 2 it looks like they intentionally don't expose system maintenance data via the SAM:

> Remote monitoring via the Internet, along with
> maintenance and system fault notifications by email may require a
> subscription fee to Bryant for access. Refer to the system website at
> www.MyEvolution.Bryant.com for more information.
> The System Access Module may be used for home automation
> access, only, if desired. Any applicable fee for remote access via
> the Internet is not required if only home automation connection via
> the SAM is desired

Sounds like painful reverse engineering the RS-485 bus is the only way to get the data.
