### ISSUE TITLE
Tractive visuel on a map

### ISSUE THREAD

**Issue by FrankFrance** [home-assistant/home-assistant.github.io#36434]
### Feedback

It's more a question, is there anyway to make the dog visible on a map, just as possible on your phone? Many Thanks, Frank

### URL

https://www.home-assistant.io/integrations/tractive/

### Version

2024.12.4

**Comment by bieniu** [comment]
This is not the right place to ask for help, you should ask your question on community https://community.home-assistant.io/

As for the dashboard map, you can find information about it in the documentation https://www.home-assistant.io/dashboards/dashboards/#map-dashboard
