### ISSUE TITLE
Where exactly is the option to change the unit of measurement?

### ISSUE THREAD

**Issue by E020** [home-assistant/home-assistant.github.io#36431]
### Feedback

<img width="962" alt="Schermafbeelding 2024-12-19 om 12 55 56" src="https://github.com/user-attachments/assets/91418d05-e4d7-4dfb-a477-5d3555c22daf" />
<img width="354" alt="Schermafbeelding 2024-12-19 om 12 55 34" src="https://github.com/user-attachments/assets/64b7feb1-8a81-4d96-981e-1d84d40733dc" />

I read the instruction but I can't find the option to change the unit of measurement. Perhaps better to (also) ask when the user adds the integration?

### URL

https://www.home-assistant.io/integrations/dexcom/

### Version

2024.12.4

**Comment by frenck** [comment]
Integrations do not provide capabilities to change the unit of measurement (as they don't measure things). Sensor entities, however, do measure stuff!

So, click on the sensor entity you'd like to have a different unit, hit the cog icon of it to configure the entity. At this place, you can change the name, entity_id and many more thing, including the unit of measurement.

This is not just limited to this integration, this ability is available for all sensors using generically known units in Home Assistant.

../Frenck
