### ISSUE TITLE
Mobile Phone as a Player Provider (ish)?

### ISSUE THREAD

**Issue by mattc2** [home-assistant/home-assistant.github.io#36464]
### Feedback

aI would love to see the ability to play back on an iPhone/Android phone. I Appreciate that this is sort of counter to the concept of MA, but it would be nice. Thanks 

### URL

https://www.home-assistant.io/integrations/music_assistant/

### Version

2024.12.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
