### ISSUE TITLE
API availability for integration

### ISSUE THREAD

**Issue by lapl1971** [home-assistant/home-assistant.github.io#36463]
### Feedback

Hi I am trying to run in Home Assistant  but get this error over the days: 
 % curl -H "Content-Type: application/json" \ 
   -d '{"client_id":"eufyhome-app", "client_Secret":"****", "email":"****@gmail.com", "password":"*****"}' \
   https://home-api.eufylife.com/v1/user/email/login
{"res_code":500,"message":"Service is temporarily unavailable. Please try again later."}%                                                                                                                                                                          lpl@Luiss-Mac-mini ~ % 

Thank you!!

### URL

https://www.home-assistant.io/integrations/eufy/

### Version

2024.12.3

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Ps. I would strongly advise you to change your account details and your client_secret, as you have just made this information public....

Thanks! 👍

./Klaas
