### ISSUE TITLE
syntax for local folders - in the docs

### ISSUE THREAD

**Issue by gang-himself** [home-assistant/home-assistant.github.io#36474]
### Feedback

As i spent some time to find the right syntax to play files from the local folders, this could be mentioned in the docs…
for the local „/media“-Folder of the homeassistant-installation the sy ntax is /media/local/filename

### URL

https://www.home-assistant.io/integrations/vlc_telnet/

### Version

2024.12.5

**Comment by MartinHjelmare** [comment]
This is already documented here:
https://www.home-assistant.io/integrations/media_source/#local-media

It's not specific for the VLC Telnet media player.

**Comment by gang-himself** [comment]
Ah, thanks, I didn‘t find this. 
Maybe a little hint to this in the docs of the integration?
