### ISSUE TITLE
Homewizard, Nord Pool and Amber are missing

### ISSUE THREAD

**Issue by BDVGitHub** [home-assistant/home-assistant.github.io#36524]
### Feedback

Add [Homewizard](https://www.homewizard.com/) for energy consumption reading, there is an [HA Homewizard integration](https://www.home-assistant.io/integrations/homewizard/).
For energy prices [Nord pool integration](https://www.home-assistant.io/integrations/nordpool/) or [Amber integration](https://www.home-assistant.io/integrations/amberelectric/) can be used.

### URL

https://www.home-assistant.io/docs/energy/electricity-grid/

### Version

2024.12.5

**Comment by frenck** [comment]
Hi there @BDVGitHub there are actually dozens of integration that can be used, this page is here to provide a generic overview, but you can find many more energy-related integrations (that almost all are usable) here:

https://www.home-assistant.io/integrations/#energy

Nevertheless, thanks for your suggestion!

../Frenck
