### ISSUE TITLE
Sensors name are outdated 

### ISSUE THREAD

**Issue by dapuzz** [home-assistant/home-assistant.github.io#36521]
### Feedback

I think that sensor.transmission_current_status is now named just as sensor.transmission_status 

Please pay attantion entity names [have been translated](https://github.com/home-assistant/core/pull/96761), so in italian I have sensor.transmission_stato, and this breaks the custom lovelace card. Not sure translating entity name is always a good idea.

Thank you very much for your work.
Bye

### URL

https://www.home-assistant.io/integrations/transmission/

### Version

2024.12.5

**Comment by frenck** [comment]
> so in italian I have sensor.transmission_stato, and this breaks the custom lovelace card.

This is an issue with the custom card, not the integration or documentation. Users can change entity IDs or might have multiple instances of integrations running (using multiple transmissions on different locations). It is up to the custom card to handle this.

I'll open up a PR to adjust the documentation on our end.

../Frenck
