### ISSUE TITLE
Needle configuration

### ISSUE THREAD

**Issue by sloukas** [home-assistant/home-assistant.github.io#36534]
### Feedback

Could not detect how to get rid of excess accuracy. For example, consumed electricity power is visible in [W] with two decimals. I would like to get rid of those two decimals. I was trying to find that information from documentation but could not find it.

### URL

https://www.home-assistant.io/dashboards/gauge/

### Version

2025.1.0

**Comment by frenck** [comment]
Hi there @sloukas 👋 

There is currently no option available on the Gauge card to control the precision of the value shown on the card. The documentation is thus correct.

If you want to raise a feature request for this, please use our community forums (it has a section for feature requests).

Thanks! 👍 

../Frenck
