### ISSUE TITLE
2025.1 beta Doc Auto Backup

### ISSUE THREAD

**Issue by mpgoebel** [home-assistant/home-assistant.github.io#36531]
### Feedback

I have been using the Home Assistant Google Drive Backup HACS integration by Stephen Beechen for years and it seems to have much of the functionality the new beta has in it.  You made a comment that no integration has done this but if I read that correctly your statement would be false and you should at least make a mention of this integration existing.  

### URL

https://rc.home-assistant.io/blog/2024/12/23/release-20251/

### Version

2024.12.xx

**Comment by mike4001** [comment]
You are misunderstanding this comment.

No integration provides the functionality so the official backup solution can use their cloud storage.

So the Google Drive integration / OneDrive integration / .... have to be adjusted so it works with the official backup service and so on.

**Comment by mpgoebel** [comment]
Ah I understand now.  Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by klaasnicolaas** [comment]
google drive backup is an add-on and not an integration, in the release notes we specifically talk about integrations that do not yet offer this feature.

./Klaas
