### ISSUE TITLE
LR should be supported by now

### ISSUE THREAD

**Issue by Kurisutian** [home-assistant/home-assistant.github.io#36565]
### Feedback

In the docs it is stated under the 800 Series Controllers "Z-Wave JS does not support Z-Wave Long Range yet." but meanwhile it does support it.  Should be changed now. 
Also it might be interesting to mention that there is a own zwave controller being worked on and the current status of it. Currently there is no status information about this anywhere and it might be a nice place to put it there as well.

### URL

https://www.home-assistant.io/docs/z-wave/controllers/

### Version

2024.12.5

**Comment by frenck** [comment]
The driver supports it, but Home Assistant does not yet. Hence the documentation is correct.

> Also it might be interesting to mention that there is a own zwave controller being worked on and the current status of it. Currently there is no status information about this a

Our documentation does not mention possible future work, it reflects the current state of our software.

../Frenck
