### ISSUE TITLE
Wolf ventilation system (CWL-T-300 Excellent) no connection 

### ISSUE THREAD

**Issue by MKniet** [home-assistant/home-assistant.github.io#36592]
### Feedback

Hello

I have a Wolf ventilation system (CWL-T-300 Excellent) and it is connected to the Wolf interface module ISM7E Link Pro LAN/WLAN. Everything works with the Wolf app.

My problem is that I want to integrate the ventilation system into the Home Assistant but I can't do it. Can you help me?

Below is the error message that I received.

Thank you!

Regards
Michael Knietsch

Guten Tag 

Ich habe eine Wolf Lüftung (CWL-T-300 Excellent) und diese ist verbunden mit Wolf Schnittstellenmodul ISM7E Link Pro LAN/WLAN. Mit der Wolf App läuft alles. 

Mein Problem ist nun, dass ich die Lüftung in den Home Assistant einbinden möchte aber ich dass nicht hinbekomme. Können Sie mir da helfen? 

Unten ist der Fehlertext, denn ich bekommen habe. 

Danke!
Gruß
Michael Knietsch

### URL

https://www.home-assistant.io/integrations/wolflink/

### Version

2024.12.5

### Additional information

Logger: homeassistant.config_entries
Quelle: config_entries.py:640
Erstmals aufgetreten: 11:01:10 (3 Vorkommnisse)
Zuletzt protokolliert: 11:16:54

Error setting up entry Dachgeschoss for wolflink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wolflink/__init__.py", line 54, in async_setup_entry
    parameters = await fetch_parameters_init(wolf_client, gateway_id, device_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wolflink/__init__.py", line 169, in fetch_parameters_init
    return await fetch_parameters(client, gateway_id, device_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/wolflink/__init__.py", line 162, in fetch_parameters
    fetched_parameters = await client.fetch_parameters(gateway_id, device_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wolf_comm/wolf_client.py", line 127, in fetch_parameters
    result = [WolfClient._map_view(view) for view in tab_views]
              ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/wolf_comm/wolf_client.py", line 300, in _map_view
    in view['SVGHeatingSchemaConfigDevices'][0]['parameters'] if 'unit' in unit])
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'parameters'

**Comment by klaasnicolaas** [comment]
Hi there 👋

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
