### ISSUE TITLE
Device info

### ISSUE THREAD

**Issue by BilleHol** [home-assistant/home-assistant.github.io#36595]
### Feedback

It would be good to be able to have a text field that is editable for each device.
So that you can note e.g. date of purchase, place of purchase, location, etc.

### URL

https://www.home-assistant.io/docs/organizing/

### Version

2024.12.5

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking documentation feedback, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
