### ISSUE TITLE
Invalid hostname or IP address

### ISSUE THREAD

**Issue by sylvainkalache** [home-assistant/home-assistant.github.io#36620]
### Feedback

It automatically detected my MinusA2 and auto-populated the "host".local. I gathered the token from the app and getting a "Invalid hostname or IP address" when submitting
<img width="380" alt="Screen Shot 2024-12-30 at 8 10 12 PM" src="https://github.com/user-attachments/assets/b87de941-2788-48a9-8781-76e45dc9c34c" />

### URL

https://www.home-assistant.io/integrations/rabbitair/

### Version

2024.12.5

**Comment by klaasnicolaas** [comment]
Hi there 

It seems like you want to report an issue with an Home Assistant integration, however, you have submitted documentation feedback instead. Please raise an issue in the Home Assistant core issue tracker instead:

https://github.com/home-assistant/core/issues

Thanks! 👍

./Klaas
