### ISSUE TITLE
Glossary Typo

### ISSUE THREAD

**Issue by itchaboy** [home-assistant/home-assistant.github.io#3764]
```
Event:
When somethings happen.
```
Should be: "When something happens"

Also, I tried to edit the page and it's constructed in an automated way? Doesn't look like anyone can go in and add or change anything.

Also also, would it be a good idea to create hyperlinks on all the terms leading to their place in the website? The only term that currently does this is "Services". Seems like a good idea to me.

**Comment by nicholasgriffintn** [comment]
Let me know if the above pull does what you wanted.

**Comment by itchaboy** [comment]
Typo fixed!

**Comment by nicholasgriffintn** [comment]
So about one of those pull mentions, I pulled the second request to my own repo (I do that often lol), anyway, I've made another one with some other glossary changes, feel free to let me know if you have some suggestions for that, I made a few link additions and changed the text up so I made it a separate pull so things could be discussed.
