### ISSUE TITLE
Theme list gets cut off at the top when list is long

### ISSUE THREAD

**Issue by tboyce021** [home-assistant/home-assistant.github.io#3765]
When the theme list is very long (long enough to need to scroll), the top entry (Backend-selected) gets cut off and can't be selected by clicking/tapping.

![image](https://user-images.githubusercontent.com/1326315/31967867-d325c62e-b8d4-11e7-9736-ae4d639ee20c.png)

**Comment by nicholasgriffintn** [comment]
This isn't a home-assistant.github.io issue, this is probably an issue that should be mentioned in the main Home Assistant Github page, which you can find here: https://github.com/home-assistant/home-assistant

**Comment by tboyce021** [comment]
Oops, I actually meant to put this in https://github.com/home-assistant/home-assistant-polymer.
