### ISSUE TITLE
Google Assistant setup has incorrect numbering

### ISSUE THREAD

**Issue by tboyce021** [home-assistant/home-assistant.github.io#3778]
The setup steps for Google Assistant has a code block after 2 that causes the numbering to start back at 1 after the block. It shows up correctly on GitHub but not on the actual website. This causes problems when trying to add multiple users because it says to go back to 7, which is currently actually labeled as 5.

**Comment by nicholasgriffintn** [comment]
Yeah the problem seems to be that this Github page: https://github.com/home-assistant/home-assistant.github.io/blob/current/source/_components/google_assistant.markdown hasn't actually synced to this page: https://home-assistant.io/components/google_assistant/ just to summarise.

**Comment by fabaff** [comment]
GitHub uses a different solution to rendering the output. The preview may create a different result. Use `rake preview` to get the actual output.

**Comment by frenck** [comment]
Assigned myself, I think I'm able to fix that.

**Comment by tboyce021** [comment]
Still an issue. In fact, it happens twice on that page now.

**Comment by fortepc** [comment]
Just bumping to say this is still an issue. Numbering repeats multiple times.

**Comment by jjanderson** [comment]
Hi, can author update this page based on the latest release? Would also be good to get instruction on how to get the additional parameters required..

**Comment by DubhAd** [comment]
An update to the docs is in the queue for approval.

The numbering is now fixed though, so I'm going to close this.
