### ISSUE TITLE
Should depend on flask_sqlalchemy package

### ISSUE THREAD

**Issue by GrahamTheCoder** [home-assistant/home-assistant.github.io#3800]
I think flask_sqlalchemy is no longer included in the sqlalchemy package.
When I first ran `hass --open-ui` it errored setting up the recorder because it couldn't find sqlalchemy (sorry I don't have the output or log).
I did `pip install flask_sqlalchemy`, then ran `hass --open-ui` again and it worked.
Inspired by this [SO](https://stackoverflow.com/a/41230648/1128762) post

**Comment by fabaff** [comment]
I assume that `flask_sqlalchemy` pulls in `sqlalchemy` and `sqlalchemy` solved your issue. We need no `flask`-related modules.

**Comment by GrahamTheCoder** [comment]
Sorry I was in a big rush and put this in the wrong place. The fact that installing hass didn't install sqlalchemy still sounds like an issue to me. Is it this project/file sqlalchemy should be in: https://github.com/home-assistant/home-assistant/blob/master/setup.py ? It does seem to be in this file, but I don't know what the text file that generates is for: https://github.com/home-assistant/home-assistant/blob/master/requirements_all.txt

**Comment by fabaff** [comment]
> Is it this project/file sqlalchemy should be in: https://github.com/home-assistant/home-assistant/blob/master/setup.py ?

No, dependencies are installed during the startup of Home Assistant if a platform/component require it and are not core requirements. For tests all dependencies are required. Home Assistant can be used without the `recorder` component.

Also, sqlalchemy is present in `requirements_all.txt` which allows one to install everything with `pip3 install -r requirements_all.txt`.

**Comment by GrahamTheCoder** [comment]
Makes sense after your explanation :+1:
