### ISSUE TITLE
Error code: 520 error

### ISSUE THREAD

**Issue by jorgen-k** [home-assistant/home-assistant.github.io#3858]
The website community.home-assistant.io gives the above error continuously.

**Comment by nicholasgriffintn** [comment]
That's an internal server error, more than likely a temporary thing that will fix itself.

**Comment by jorgen-k** [comment]
Well yes, it has fixed itself or someone has.

My impression was more a server problem than a problem in cloudflare - response from server timed out. Anyways, it is working now so I will close this myself.
