### ISSUE TITLE
Link to Source from Docs

### ISSUE THREAD

**Issue by n8henrie** [home-assistant/home-assistant.github.io#3869]
I did a quick search and don't see an issue about this in this repo, so apologies if it's been covered --

One feature that I've often been surprised to find lacking was a link to source code in each of the components pages. I'm often using the docs to try to figure out how to configure a component, but if I still have questions, I refer to the source code. And every time I do this, I wish there were just a direct link from the documentation on a component (or platform) directly to that source.

Anybody else think this would be a reasonable feature? I'd be happy to try to figure out a script to automate the bulk of the work to add the links (might take me a little while, I'm no pro). I am downright rotten at frontend design and UI, however, so it might be best if someone helped me choose where the link should go (to keep it consistent across platforms, components, etc.).

I figure it should link to the `master` branch, and likely just to the "current" version -- we could have it link to the version at a specific point in time (so that if you went through the git log for the docs, you would see a link to the version of the source at that point in time), but I think this would make things unnecessarily complicated.

**Comment by n8henrie** [comment]
> Components will need some more work because some are in their own folder and should point to xyz/__init__.py instead of xyz.py.

Example:

- Docs: https://home-assistant.io/components/remember_the_milk/
- Source: https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/remember_the_milk/__init__.py
- Docs: https://home-assistant.io/components/datadog/
- Source: https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/datadog.py

Should I try to add these manually somewhere to the components docs? Seems like it would be better to automate the process, but I agree it's not immediately obvious to me how this should be done when the docs URL is identical but the path to the source file differs.

**Comment by fabaff** [comment]
It should be automated. We could do some kind of mapping for the components we are not able to pull out of the main repo if we decide to go down that route. One issue here is that it would require a GitHub API key because we would probably hit the request limit.

Another option could be to start organizing the component and platform docs according the main repo. Meaning that we move the platforms to subfolder.

**Comment by n8henrie** [comment]
What determines whether a component goes into the `__init__.py` of its own package vs just a module? The presence of child platforms?

If so, is this something we could test for? i.e. [`file_parts.size == 2`](https://github.com/home-assistant/home-assistant.github.io/blob/89ad9d863e289eede1305c861e1cb8e031242a39/source/_includes/asides/component_navigation.html#L14) and `has_children` would mean definitely should be a package, and otherwise should be looking for a module?
