### ISSUE TITLE
Documentation still says Python 3.4

### ISSUE THREAD

**Issue by smadgerano** [home-assistant/home-assistant.github.io#3894]
Various pages on the site still state that Python 3.4 is ok...

https://home-assistant.io/docs/installation/
https://home-assistant.io/docs/installation/troubleshooting/

...even though it's being abandoned...

https://home-assistant.io/blog/2017/10/06/deprecating-python-3.4-support/

**Comment by fabaff** [comment]
Python 3.4 is deprecated not abandoned.

**Comment by smadgerano** [comment]
OK, my choice of words was not accurate :) but there isn't much point still telling new users to use 3.4 if it will stop being a supported in a few months. 

I know the whole Python version "situation" is a nightmare, so I understand the problems, but I think it should be made as clear as possible for new users which version to go with. 

HASSIO is using 3.6, which worked flawlessly for me, whereas a vanilla 3.5 setup has problems, telling people to use 3.4 just puts another layer of potential problems.

**Comment by fabaff** [comment]
We don't tell people to use Python 3.4.2. It's is just the minimal requirement to run Home Assistant as it was shipped with Debian 8. With Debian 9 it's 3.5.2 anyway if I remember correctly.

**Comment by smadgerano** [comment]
Fair enough, agreed, you don't specifically tell people to install 3.4, and I hate to keep arguing about trivial semantics, but you do give the impression in places that it is the required version, in the troubleshooting section...

"This utility should have been installed as part of the Python 3.4 installation. Check if Python 3.4 is installed by running python3 --version. If it is not installed, download it here."

To me, that says I SHOULD be using 3.4, not any other.

Not everyone is going to be using Debian 9 either. On the https://home-assistant.io/docs/installation/python/ page you have a link to an instructional video for how to install on Ubuntu 14.04, again when it's on the official site this implies to me that this is the version I SHOULD be using.

Again I know this is all done by lots of people giving up their time and I'm not trying to be a ungrateful, but if we have the opportunity to be as specific as possible, we should do it.
