### ISSUE TITLE
Problems accessing Forums pages

### ISSUE THREAD

**Issue by VdkaShaker** [home-assistant/home-assistant.github.io#3900]
Not sure if its just me, but I'm constantly having problems connecting to the Forums.  I'm getting redirected to the Cloudflare pages saying the live pages are down.  

> This page (https://community.home-assistant.io/c/hass-io) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site. We will keep checking in the background and, as soon as the site comes back, you will automatically be served the live version. Always Online™ is powered by Cloudflare | Hide this Alert

**Comment by bassclarinetl2** [comment]
According to Twitter, it's a forum upgrade that got borked.

**Comment by VdkaShaker** [comment]
Thanks.  Seems to happen often (last few weeks were problems).  Do you know where I can check for updates on the issue?

**Comment by fabaff** [comment]
Twitter https://twitter.com/home_assistant
