### ISSUE TITLE
Wider search link

### ISSUE THREAD

**Issue by cstuder** [home-assistant/home-assistant.github.io#3974]
<img width="118" alt="bildschirmfoto 2017-11-13 um 14 45 04" src="https://user-images.githubusercontent.com/288493/32728630-536660c6-c881-11e7-821c-b680de73e26c.png">

Hitting the small search icon isn't as easy as it should be.

Suggestion: Add a text label `Search`.

**Comment by BLX-S** [comment]
I'm working on a PR right now.
