### ISSUE TITLE
thethingsnetwork component not loading

### ISSUE THREAD

**Issue by peerv** [home-assistant/home-assistant.github.io#4035]
After working for weeks thethingsnetwork component is not loading anymore after a restart.
The logging function is loaded.
There is no entry at all in the error log about thethingsnetwork.
No change was made to the configuration file.
Any idea where to look?

**Comment by MartinHjelmare** [comment]
This is the wrong repo to report issues. This is the documentation repo of home assistant.

If you think there's a bug, please open an issue here:
https://github.com/home-assistant/home-assistant
