### ISSUE TITLE
Google Assistant: list supported entity types

### ISSUE THREAD

**Issue by bmesuere** [home-assistant/home-assistant.github.io#4036]
While a lot of information is present on how to get Google Assistant working, the supported features are not explained at all. 

- From the documentation, it is not clear which types/domains are natively supported by Google Assistant and to which types the natively unsupported ones are mapped. Covers, for example, seem to be mapped to lights. 

- The docs mention the `google_assistant_type` config value, but it's not clear it these are HA types or Google Assistant types and which ones are valid.
```
google_assistant_type: Can be used to override the domain/type of an entity. For example a switch can be treated as a light
```

- What about sensors and retrieving (status) information?

**Comment by arsaboo** [comment]
PRs welcome :)

**Comment by bmesuere** [comment]
I'd be happy to help if I had more information about the actual supported functions. From experience, Google Assistant currently supports lights, switches, scenes and thermostats. By default the following mapping is made by the component:

* lights
  * actual lights (on/off, brightness and color support)
  * covers (on/off, brightness being mapped to the position)
  * media players (on/off, brightness being mapped to volume)
* switches (on/off only)
  * switches
  * fans
* scenes (I think these can only be enabled)
  * groups (can't be turned off?)
  * scenes
  * switches
* thermostats
  * climate (no idea about supported features)

Side effects: If you ask google assistant to turn on all lights, your media player and covers will also turn on. If you don't use the brightness to position or volume feature, it's better to map them to switches using the `google_assistant_type`.

**Comment by BLX-S** [comment]
@bmesuere  An additional note I would like to add is the media_control entity. It appears it can be passed as a supported component type but it's still unclear as to how one can control it through Google Assistant.
