### ISSUE TITLE
hassio automation and scripts issue

### ISSUE THREAD

**Issue by cooper2751** [home-assistant/home-assistant.github.io#4072]
so as i've been working on a automation and trying different ways to work it. (automations and automations triggering scripts) ive noticed the save button works in strange ways. seems to be the same for both. (keeping it simple time trigger light on) if you open a new automation set your trigger and automation (json correct (no red box)) click save all is fine and automation is saved. BUT

if i then go back in to edit it some think like adding a 20sec transition to full brightness (json fine (no red box))
click save,  
and jumps back to how it was before the edit.
so edit again.  ( or as i've now started doing copy anything i've edited  so when this happens i can just re paste) click save and its fine all saved. doesn't seem to matter what is edited automation trigger or even then automation name.

on one occasion (in frustration) i kept clicking the save button and the automation seemed to be loading  or undoing back to previous saved versions.
don't know if this is isolated to me.
thanks.

**Comment by MartinHjelmare** [comment]
This is the issue tracker for the home assistant documentation. As this seems to be a home assistant frontend issue, you should open an issue here:
https://github.com/home-assistant/home-assistant-polymer/issues

Have a look at this issue, which also affects the automation editor:
https://github.com/home-assistant/home-assistant-polymer/issues/681
