### ISSUE TITLE
All the sudden: Error reading status line from remote server

### ISSUE THREAD

**Issue by halsafar** [home-assistant/home-assistant.github.io#4126]
I am using hassio on a rpi3.  Home-Assistant was working perfectly for a few days.  Reverse proxy with HTTPS following the instructions here: https://home-assistant.io/docs/ecosystem/apache/

All the sudden I cannot connect via the proxy (removed my URL):
`WebSocket connection to [HIDDEN] failed: Error during WebSocket handshake: Invalid status line`

Error in reverse proxy apache log:
`[Sat Dec 02 15:23:08.181612 2017] [proxy_http:error] [pid 7001] (20014)Internal error (specific information not available): [client 192.168.1.1:50753] AH01102: error reading status line from remote server 192.168.1.33:8123, referer: [HIDDEN]`

Running: Apache/2.4.18

I've restarted HassIo, full reboot.

I've restarted the apache server running the reverse proxy, also a full reboot.

Any idea?

**Comment by fabaff** [comment]
This is the bug/issue tracker for Home Assistant Documentation. Please use the [forum](https://community.home-assistant.io/) for questions about installation, setup, and configuration.
