### ISSUE TITLE
Display issues on the History menu in Safari and in the iOS app

### ISSUE THREAD

**Issue by Lato80** [home-assistant/home-assistant.github.io#4139]
The data in the History menu is not displayed in Safari (macOS & iOS) and not in the iOS app.

It does not matter what attitude I use:

```
frontend:
  javascript_version: latest | auto | es5
```

But does not seem to be a fundamental problem, because in Mozilla Firefox or Google Chrome, the data is displayed to me.

**Comment by MartinHjelmare** [comment]
This is the documentation repo for home assistant. You should report this issue in the frontend repo for home assistant.

https://github.com/home-assistant/home-assistant-polymer
