### ISSUE TITLE
IMAP E-mail Content Reader Problem

### ISSUE THREAD

**Issue by arretx** [home-assistant/home-assistant.github.io#4164]
After configuring this component, all of the e-mail in my Gmail account was coming in as thought it had already been read by me.

As a result, I would often miss messages because I was unaware that this was happening.  So, I disabled it.

If there was a way to ensure that the e-mails in the inbox were still marked as unread, it would be a good component and tool for e-mail automation triggers.

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.
