### ISSUE TITLE
zwave installation needs gmake

### ISSUE THREAD

**Issue by dmshimself** [home-assistant/home-assistant.github.io#4225]
The guide works fine for freenas 11.1, but if you want to use a zwave device, openzwave also needs a 
pkg install gmake
as part of the pre-reqs

It might also be an idea to have the homeassistant user set up as a member dialer group
pw groupmod dialer -m homeassistant

**Comment by overkill32** [comment]
@dmshimself Can you provide a link to the guide you are referring to?   I can take a look at updating it.
