### ISSUE TITLE
Dominos component example should not use a real person's details.

### ISSUE THREAD

**Issue by vsnine** [home-assistant/home-assistant.github.io#4235]
Hello,

Currently the example contained in the Dominos component at https://github.com/home-assistant/home-assistant.github.io/blob/current/source/_components/dominos.markdown includes the name and address of a real person, Justin Trudeau, the Prime Minister of Canada. 

This should be changed to use fictitious details, such as the following:
John Doe
123 Main St
Anytown, USA

Thanks.

**Comment by frenck** [comment]
I do agree with this, feel free to open a PR.
(or anybody reading this).
