### ISSUE TITLE
Add template example to Input Datetime

### ISSUE THREAD

**Issue by BLX-S** [home-assistant/home-assistant.github.io#4259]
Can someone add an example of the date time input being used in an automation or at least how the syntax works in a template? This would make using this input a lot easier for noobs (like me ;-P).

https://home-assistant.io/components/input_datetime/

**Comment by mf-social** [comment]
^ only just spotted this - PR submitted.

**Comment by mf-social** [comment]
@cdce8p - can you close this too, now the PR is merged? Ta.

**Comment by arsaboo** [comment]
Fixed via #4715
