### ISSUE TITLE
Hass.io cannot install websocket-client

### ISSUE THREAD

**Issue by LordVaderXIII** [home-assistant/home-assistant.github.io#4276]
Since for Port 8001 to work we need websockets how would we get this working on hass.io since you cannot run "pip3 install"?

Is there a workaround for this?

**Comment by LordVaderXIII** [comment]
This is to get the samsung TV component working on port 8001

**Comment by penright** [comment]
@LordVaderXIII  did you get this figured out? What model do you have?
Looking at the model tree, I have a two Hxxxx. Looks like H is a 2014 model year and I am running hass.io.
According to this web [site](http://www.samsung.com/uk/support/tv-audio-video/what-do-samsung-tv-model-numbers-actually-mean-why-are-they-so-long/).

So, Looks like I need the 55000 non-websocket model, but all I see is a grey control. I started wondering if it is an issue with my hasss.io not an old tv? That is why I posted the question here.

**Comment by LordVaderXIII** [comment]
@penright I have the MU6100 (2017) model, I have gotten it to work now. To be honest I dont know why it started working. When I first set it up I could only turn the tv on. Since Im assuming that works via WOL, it made sense that websockets was the issue. However it suddenly started working. I have found that if I run the AppDaemon Hassio add on it stops working and will only turn on. Im not sure if its because that uses websockets as well. 

It would be nice to find out exactly what the problem is but I dont know these things well enough to figure it out.

**Comment by frenck** [comment]
I'm closing your issue since it looks misplaced. This is the issue tracker for the Home Assistant Documentation & Homepage. 

Please report technical Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

Thanks!
