### ISSUE TITLE
Product Database

### ISSUE THREAD

**Issue by BLX-S** [home-assistant/home-assistant.github.io#4295]
As mentioned in the Home Assistant Podcast, I think it would be a good idea to start discussing the possibility of a product database. This would make it especially handy for beginners to get into Home Assistant. Apart from this I think it would really complement the existing components page.

**Comment by fabaff** [comment]
This topic is coming up from time to time. The main issue is that this requires a large amount of time to maintain even if the community is heavily involved and the level to add/edit/modify/remove is very low. We are not talking about one kind of device, e.g., a wireless router, but pretty much about everything with a network connection in our apartments or homes.

I see the benefit for a beginners. Thus, if everybody is coming up with a plan I'm all for it.

**Comment by tschmidty69** [comment]
I agree this would be really nice to have. For beginners it would be an obvious advantage (will this work/is supported).

A great secondary benefit would be tracking users who own and are willing to test certain devices, would not need to be public. So for instance, github users could be tagged as having a device so if we were trying to iron out issues we could contact people to test if needed.

So a prerequisite is having a database or something we could use and that people could submit their devices to. So *someone* needs to find or code something, that's the first obstacle. Second is then getting buy in to submit devices, but that shouldn't be too difficult.

**Comment by BLX-S** [comment]
@tschmidty69 I'm proposing this because I think it's great to have an index of supported devices with maybe a link to instructions on how to set them up. I think you brought up some ideas which could pose additional value to the community like the device testing but more importantly people sharing experiences with devices in a centralised and concrete way.

@fabaff I don't think community contributions will be a huge bottleneck. Besides we don't necessarily have to add every possible device. The real value would be in providing a solid starting point for beginners and inspiration for more advanced users. If we get the basics down, the rest will follow.

**Comment by forrestjr** [comment]
What attributes would we want to track?  I don't recommend self-reporting because you will have everyone and their mother reporting different names for things; some correct, most likely not.

**Comment by tschmidty69** [comment]
I was thinking again about this last night, the big thing is just to get something together to comment on. If I get time I'll dig in.

**Comment by dgomes** [comment]
Can we start small ?

Example:
https://openwrt.org/toh/start

**Comment by dgomes** [comment]
Just to update everyone:

https://www.hadevices.com

There is more information https://community.home-assistant.io/t/home-assistant-device-database/49947

Guess the issue can be closed 🗡

**Comment by michaeldeborst** [comment]
Damn @dgomes great work. Maybe open up a GH repo for it?

**Comment by dgomes** [comment]
I can't take the credit... check the discussion in the community
