### ISSUE TITLE
Dublin Bus and Huawei Use the wrong file endings

### ISSUE THREAD

**Issue by ioangogo** [home-assistant/home-assistant.github.io#4368]
The componets Dublin but and Huawei use the wrong file extention

Dublin Bus should have ```.png``` and Huawei should have ```.svg```

I was going to do this, but i have poorly maintained my fork of this repo and havent got it on my local machine yet so ill allow someone else to do it

**Comment by jumpalottahigh** [comment]
#4370 Should take care of that.
