### ISSUE TITLE
Time-based statistics sensor suggestion

### ISSUE THREAD

**Issue by bonterra** [home-assistant/home-assistant.github.io#4380]
Updating the statistics sensor to include a time limit was great, even better would be to make the sample size truly optional, i.e. not having a default value at all, and instead make either sample_size or max_age required.

That way a user wouldn't have to guess how many samples are required for a given sensor. Today one could make "sample size: 100 000" or even 1 000 000 to be on the safe side. Making it truly optional the user could specify "max_age: 30 days" instead of both sample_size and max_age, not having to worry about running out of sample size.

**Comment by MartinHjelmare** [comment]
You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum. Thanks!
