### ISSUE TITLE
Add a reference to homebridge in the components

### ISSUE THREAD

**Issue by BLX-S** [home-assistant/home-assistant.github.io#4395]
I know it's not a component in the strictest sense of the word, but it is something which I believe many people will find useful. A lot of people have Apple devices and since the Google Assistant, and Alexa integrations are featured so prominently it would be great to do the same for Siri / HomeKit via homebridge.

**Comment by frenck** [comment]
My question would be, where do we stop? There are many many more tools and integrations, should we list all of them in the future?

**Comment by datafx** [comment]
It looks like Homekit integration may soon be it's own [native component](https://github.com/home-assistant/home-assistant/pull/12488).  If (most likely when) this component gets added, it will have it's own documentation.

**Comment by BLX-S** [comment]
@frenck I totally understand your concerns but I speak from experience that I was hesitant to start with homeassistant till I found out it was homekit compatible (in a way).  I mean homebridge is included as a Hassio addon so it might be worth a mention in the docs.

@datafx even though it's a bit primitive it would be cool to see that component merged. I hope this leads to a fullfledged HB integration.

**Comment by c727** [comment]
Homebridge is a workaround and native homekit is still WIP
