### ISSUE TITLE
HA Error dealing with request

### ISSUE THREAD

**Issue by itm1960** [home-assistant/home-assistant.github.io#4433]
I've configured an IFTTT applet as per the example for Logitech Squeezebox, but HA is reporting errors with the request. 
IFTT webhook:
`URL: https://mydns.ddns.net:8123/api/services/media_player/play_media?api_password=mypassword`
Method: POST
Content Type: application/json
Body: `{ "entity_id": "media_player.kitchen", "command": "playlist", "parameters": ["loadtracks", "album.titlesearch={{TextField}}"] }`

This generates the following in the HA log:
```
2018-01-16 11:11:50 ERROR (MainThread) [homeassistant.core] Invalid service data for media_player.play_media: extra keys not allowed @ data['command']. Got 'playlist'
extra keys not allowed @ data['parameters']. Got ['loadtracks', 'album.titlesearch=late for the sky']
required key not provided @ data['media_content_id']. Got None
required key not provided @ data['media_content_type']. Got None
```

**Comment by MartinHjelmare** [comment]
Please provide a link to the example in the docs that you're following.

**Comment by itm1960** [comment]
I'm following these instructions:
https://github.com/home-assistant/home-assistant.github.io/blob/current/source/_components/media_player.squeezebox.markdown

https://home-assistant.io/components/media_player.squeezebox/

**Comment by MartinHjelmare** [comment]
I think the endpoint you're using is wrong. You should use the squeezebox service call method endpoint.
https://home-assistant.io/components/media_player.squeezebox/#service-squeezebox_call_method

**Comment by MartinHjelmare** [comment]
Something like:
`https://mydns.ddns.net:8123/api/services/media_player/squeezebox_call_method...`

Fill in the end yourself.

**Comment by itm1960** [comment]
Ok I tried changing the URL to:
https://mydns.ddns.net:8123/api/services/media_player/squeezebox_call_method/?api_password=myspipassword

But that gave a 404 error.

**Comment by MartinHjelmare** [comment]
Can you call the corresponding service via the developer service tool in the home assistant GUI?

**Comment by itm1960** [comment]
I don't see squeezebox_call_method listed in the Services dropdown in the HA GUI. Does that mean my LMS server hasn't registered with HA?

**Comment by MartinHjelmare** [comment]
What home assistant version are you on?

**Comment by itm1960** [comment]
I'm on 0.60.0

**Comment by MartinHjelmare** [comment]
The service was added in 0.61.

I'm closing here now, cause I don't think this is a bug, and the documentation is correct, although it could perhaps make the example better with a step by step guide.

**Comment by itm1960** [comment]
OK thanks - that has probably saved me alot of time!
I've just tried upgrading (python3 -m pip install --upgrade homeassistant) but v0.61.0 does not seem to have been installed. Is it not currently available to Ubuntu users?

**Comment by itm1960** [comment]
Could I please re-open this one? -  I've just upgraded to 0.61.0, and can see and call the media_player.squeezebox_call_method from the HA GUI. The IFTTT link remains broken, though - the following request returns a 404 error from the HA server:
URL: https://mydns.ddns.net:8123/api/services/media_player/squeezebox_call_method/?api_password=mypassword

Body:{ "entity_id": "media_player.kitchen", "command": "playlist", "parameters": ["loadtracks", "album.titlesearch={{TextField}}"] }

I just copied and pasted the Body content into the HA Services call (substituting the album name for {{TextField}}) and the album played fine.

**Comment by MartinHjelmare** [comment]
I would try curling in to the REST API and first test another service that should work eg `switch.turn_on`. You can use a demo platform if you don't have any switches. Do this to rule out other problems like IFTTT.

**Comment by itm1960** [comment]
So before curling the REST API I thought I'd try calling the media_player.squeezebox_call_method again from the Services menu of the HA GUI (using the same JSON data as before). I got a message after 10 seconds saying that the service had been called, but this time there was no playback on the Squeezebox player. I was tailing the HA log and nothing showed up there either.
Presumably if the media_player.squeezebox_call_method was listed in the dropdown on the HA services page then my Squeezebox server was recognised?

**Comment by itm1960** [comment]
OK a restart of HA and everything was back to normal. The request from IFTTT is now working, too. For some reason if I play to non-official Squeezebox clients (e.g. a Chromecast linked to the LMS server using a plugin) I get no audio, even though the LMS server shows that audio is playing. I'll run that past the guys in another forum
Thanks for your help.
