### ISSUE TITLE
RFC: Discourse for comments

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#4502]
# Motivation

Currently, the blog is partially disconnected from the community. The comments are only visible in blog posts, but their attention may vary. Secondly, it creates another place where discussions are taking place.

This issue was created to poll the support for this RFC.

## Proposed changes

Replace the Disqus integration with Discourse and move the discussion into our own community.

Reasoning:
- Removes another platform
- Removes another place where discussions are taking place
- Moderators/Admins are centrally defined and present
- The responses left at a later moment (e.g. a couple of weeks later) will still pop up and may be answered.
- Promotes community interactions, self-help, and binding

## Ref

Some quick Google-foo.
https://joebuhlig.com/discourse-commenting-for-jekyll/
https://meta.discourse.org/t/migrating-from-disqus-to-discourse-for-static-blog-comments/19947

**Comment by balloob** [comment]
Your wish is my command; starting 0.62 this is live for all blog posts.

Category on the forums that holds the topics: https://community.home-assistant.io/c/blog
