### ISSUE TITLE
Improve wording on page https://home-assistant.io/getting-started/configuration/

### ISSUE THREAD

**Issue by dumbo25** [home-assistant/home-assistant.github.io#4579]
I thought I was doing this right, "Add the following to configuration.yaml file to add a link to the Configurator in the sidebar:" but everything went away.

I would change to: Open configuration.yaml file and add the following, which creates a link to the Configurator in the sidebar:"

I had to reflash the microSD card and restart the process.

**Comment by c727** [comment]
There is an edit button on every page to submit changes
