### ISSUE TITLE
Move all developer docs to standalone website

### ISSUE THREAD

**Issue by balloob** [home-assistant/home-assistant.github.io#4580]
We already have https://dev-docs.home-assistant.io/ but are not really using it.

As Home Assistant is growing, it's time to decouple development and usage docs. We keep the main website for normal docs and move our developer docs to the dev-docs website. This would include most things under `/developers` on the site.

**Comment by fabaff** [comment]
Shouldn't be that hard with some `pandoc` and `sed` magic to move the existing docs to https://github.com/home-assistant/development-docs.

**Comment by balloob** [comment]
We currently use Sphinx which has the added benefit that it can also generate API docs for the functions inside Home Assistant. It also means that we can easily link to functions and their API docs inside the other docs.

I would probably want to stick with Sphinx.

**Comment by fabaff** [comment]
I didn't plan to use something else than Sphinx. I was talking about converting the markdown files to rst with `pandoc` which you allow us to use Sphinx and all its benefits without adding markdown support.

**Comment by balloob** [comment]
oh, I see.

I would rather add markdown support to Sphinx so we don't keep 2 markup languages around. (I am personally also a lot more comfortable in Markdown)

**Comment by balloob** [comment]
Going to close this. Keep an eye out for an announcement in the next few days 😉
