### ISSUE TITLE
RPi2 image does not work on RPi2 B

### ISSUE THREAD

**Issue by marcinkowalczyk** [home-assistant/home-assistant.github.io#4604]
Hi,
 
Seems that RPi2 image from 1.1 release does not work on RPi2. When I've dowloaded RPi2 version
 https://github.com/home-assistant/hassio-build/releases/download/1.1/resinos-hassio-1.1-raspberrypi2.img.bz2 green status led blinks and does not boot. It does work with RPi1 image.

**Comment by MartinHjelmare** [comment]
Please raise this issue in the hassio-build repository instead.
