### ISSUE TITLE
Samsung Smart TV 2014 TV encryption

### ISSUE THREAD

**Issue by rpcaeiro** [home-assistant/home-assistant.github.io#4702]
In the Samsung Smart TV component is stated: "None of the 2014 (H) and 2015 (J) model series (e.g. J5200) will work, since Samsung have used a different (encrypted) type of interface for these."

Not sure if this helps, but the author of the below link claims that he can remotely control 2014+ TVs
https://github.com/timelery/Samsung-RemoteControl

Can we integrate this into Samsung component? the article has more then a year, so I'm assuming  this was already tried, but never know...

My TV is one of those starting with H :)

**Comment by c727** [comment]
Use forums for feature requests
