### ISSUE TITLE
[META] cookbook spring cleaning

### ISSUE THREAD

**Issue by c727** [home-assistant/home-assistant.github.io#4709]
read here first: #4710

```
**Name:**

your name or the "name" of your repo/config/automation/...


**Url:**

GitHub prefed, don't upload your whole config to the docs anymore


**Description:**

1-2 sentences that describe your repo


**Highlights (if you link to a whole repo):**

my diy-project XXX integrated in HA, advanced automations/ templates, python script to do XXX, automated glasshouse, voice automation flows to control the TV

```

**Comment by atomicpapa** [comment]
**Name:**

AtomicPapa


**Url:**

https://github.com/atomicpapa/Home-AssistantConfig


**Description:**

Floorplan based HASS implementation.  Also, Broadlink, Generic Cameras, and Google Assistant


**Highlights (if you link to a whole repo):**

Floorplan

**Comment by mf-social** [comment]
**Name:**

mf_social 


**Url:**

https://github.com/mf-social/Home-Assistant


**Description:**

Package-based configuration with cut-and-paste examples of an intermediate to advanced setup. Includes examples of templating, organisation and backup strategies. 


**Highlights (if you link to a whole repo):**

Virtual device packages, such as a multi-room music player, alarm clocks and maintenance manager

**Comment by stanvx** [comment]
**Name:**

stanvx


**Url:**

https://github.com/stanvx/Home-Assistant-Configuration


**Description:**

Home Assistant, Floorplan and HADashboard configurations featuring a large variety of automations and component/device integrations.


**Highlights (if you link to a whole repo):**

Floorplan, HADashboard, AC split system control, Harmony activity control, burglar alarm utilizing Xiaomi gateway, Chromecast radio player, presence based vacuum, hide inactive media players, voice notifications via Google Assistant webserver.

**Comment by CCOSTAN** [comment]
**Name**:

ccostan

**Url:**

https://github.com/CCOSTAN/Home-AssistantConfig

**Description:**
My repo is a working living copy of my exact home configuration updated in realtime.   My associated [blog](www.ipmer.com) has additional write ups and explanations for many of the design choices and automations found in the repo.  

**Highlights** (if you link to a whole repo):

Updated continually. Drop In Packages, Updated Readme files with Blog Support links, Floorplan, ESP8266 based alarm, extensive Text to Speech capabilities, Realtime Tweet Support (@BearStoneHA) and so much more..

**Comment by DubhAd** [comment]
**Name:**
Tinkerer, aka DubhAd

**Url:**
https://github.com/DubhAd/Home-AssistantConfig/

**Description:**
My live configuration, as used on my Home Assistant install. Using Floorplan for a high level overview, HA Dashboard for finger friendly controls/20 foot view, and presence detection.

**Highlights (if you link to a whole repo):**

1. Parsing of emails for recycling collection information, with sensors to indicate whether the collection is past, upcoming, tomorrow, or today. Uses notification messages, and in Floorplan.
2. Automatically turning on the garden lights when the rear doors are opened and leaving them on when the door is closed, but then turning them off the next time the door is closed. Unless we leave it open for more than a predefined time - in which case it's turned off immediately.
3. Commute delay automations, using transport sensors, calendars, and workday sensors. Return commute delay notifications based upon geolocation.

**Comment by geekofweek** [comment]
**Name:**

geekofweek


**Url:**

https://github.com/geekofweek/homeassistant


**Description:**

Home Assistant setup of my personal working automations and configs with some interesting and complex automations.


**Highlights (if you link to a whole repo):**

Frequently updated Docker based installation with some included custom management tools.   

- Multiple location based automation that will trigger lights, door locks, garage doors, etc contextually based on each user
- Media player automations that control lights based on sun position, type of media player, and time of day
- Text to speech automations based on individual users location
- Advanced climate automations that adjust based on household members and day of week.
- Holiday lighting automation that auto selects holiday
- Vacuum based automations that run and cancel vacuum jobs dependent on user location, time of day, and day of week.
- Room occupancy automations that will turn lights on or off based on room presence
- Custom alarm system that utilizes siren, lights, notifications, and text to speech

**Comment by arsaboo** [comment]
**Name:**
arsaboo

**Url:**
https://github.com/arsaboo/homeassistant-config

**Description**
Always updated repository for my Home Assistant setup. Includes a range of devices, integrations, complex automations, and scripts!

**Highlights (if you link to a whole repo):**
The repository covers lot of friendly code for users to accomplish some fancy stuff. Here are some things that I find really: 1) presence detection using `python_script` and Bayesian sensor, 2) entirely automated home security system based on presence, 3) automations with actionable notifications and alerts, 4) lot of templates, and scripts for a wide range of devices.

**Comment by happyleavesaoc** [comment]
**Name:**

happyleaves


**Url:**

https://github.com/happyleavesaoc/my-home-automation/tree/master/homeassistant


**Description:**

Personal Home Assistant configuration that tracks `dev` branch. Packaged-based for easy browsing & ideas.

**Highlights (if you link to a whole repo):**

- Complex templates
- DIY multi-room audio
- Broad array of meta-sensors

**Comment by skalavala** [comment]
Name:

@Vasiley 

Url:

https://github.com/vasiley/Home-Assistant-Main/

Description:
Running multiple instances of Home Assistant, each dedicated to a special purpose. Uses various types of hardware, custom DIY solutions...etc. 


Highlights (if you link to a whole repo):

Fish Tank Automation, DIY Thermostat with Home Assistant, and Various automations around Washing Machine, PiHole, Blinds, Cameras, Printers, Wax Warmers, Hue Lights and more...

**Comment by SilvrrGIT** [comment]
**Name:**

SilvrrGIT


**Url:**
https://github.com/SilvrrGIT/HomeAssistant


**Description:**
Home Assistant instance running using as many non 'cloud' devices as possible.   


**Highlights (if you link to a whole repo):**
IOT/Home Automation security discussion and automations, power outage detection automations, automations for power savings, and presence based HVAC control.

**Comment by GreenTurtwig** [comment]
**Name:**

GreenTurtwig


**Url:**

https://github.com/GreenTurtwig/personal-home-automation


**Description:**

Personal configuration for Home Assistant, with most but not all (yet) currently owned IoT devices.


**Highlights (if you link to a whole repo):**

None really. Although I don't own many devices, so it could be easier for new users to understand.

**Comment by ntalekt** [comment]
**Name:**

ntalekt

**Url:**

https://github.com/ntalekt/homeassistant

**Description:**

Personal Home Assistant configuration kept up to date with many documented examples for novice or elite users to reference.

**Highlights (if you link to a whole repo):**

- Many IoT Devices integrations (Ring, Nest, Sonos, Alexa, Hue, Logitech Harmony etc.)
- Many automations split out into different categories (e.g. Notification, lighting, media, occupancy etc.) for easy consumption.
- Scripts/Customizations

**Comment by cbulock** [comment]
**Name:**

cbulock

**Url:**

https://github.com/cbulock/home-assistant-configs

**Description:**

1-2 sentences that describe your repo


**Highlights (if you link to a whole repo):**

* RBG notification system based on events that need attention
* Presence awareness, including awareness around how long people have been gone
* Voice prompts to give a status on things that need attention while people were away once they have returned
* I think the configs are a good example of breaking the config out, especially where the automations are concerned

(Planning to re-work the README to highlight some of the better automations, haven't had time this last week)
