### ISSUE TITLE
Doc for removed hass component

### ISSUE THREAD

**Issue by cmsimike** [home-assistant/home-assistant.github.io#4711]
Hi,

I was reading the HTTP Binary Sensor doc, https://home-assistant.io/components/binary_sensor.http/ and went to look at the source code, https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/binary_sensor/http.py however that 404s. Looking into the repo, there doesn't seem to be an HTTP sensor anymore:
https://github.com/home-assistant/home-assistant/tree/master/homeassistant/components/binary_sensor
Am I missing it and the doc just needs to be updated or should this doc be deleted?

**Comment by fabaff** [comment]
The `http` sensors are "built-in platforms" which don't have a source file because they are based on the REST functionality . We are generating the link to the source in the sidebar automatically for all docs. 

Looks like that we need to update part that is responsible for the link.
