### ISSUE TITLE
Home page does not show the current point release

### ISSUE THREAD

**Issue by lindsaymarkward** [home-assistant/home-assistant.github.io#4789]
The page at https://home-assistant.io/components/sensor.scrape/ says "The current release Home Assistant is published on https://home-assistant.io/" but the version does not appear to be up to date.

Currently, the home page says that `64.0` is the current release, but the blog says `64.1`, which is correct.

What needs updating so that the home page shows the actual current release including point updates?

**Comment by c727** [comment]
Use forums or chat if you have problems with components

**Comment by lindsaymarkward** [comment]
Thanks for the update, but I don't understand. My problem was not with a component, but the fact that the website was incorrect. Hence, I posted an issue in the website repo.
In future, perhaps I shouldn't provide background context as to why or how I came to notice. I.e. in this case, perhaps mentioning the scrape component distracted you from the actual issue?

I see that the website currently shows `64.3`, so perhaps it's a lag issue not that it doesn't ever show the point updates.
