### ISSUE TITLE
password: null in configurator add-on

### ISSUE THREAD

**Issue by hasscasts** [home-assistant/home-assistant.github.io#4822]
Hi, All
I am struggling to find a piece of code.

When I add the Configurator addon in hass.io the json sample config has the password parameter down as being null. This is a required parameter and null doesn't work.

I can obviously change it in the config box but that's not the point.

I have tried looking at different branches and through the blame history but I cannot see where it originates. I see that the username and password options were originally called "credentials" and then split into two with the password then defaulting to "secret".

Am I missing something here? Is it changed to null somewhere in the presentation layer so that a user has to enter their own password or have I just missed it?

I can folk & submit a PR if I know where to change it.

Please help me to help the repo :-)

![Screenshot of default config in v0.2.6](https://user-images.githubusercontent.com/36940037/36937053-72dcb33a-1f05-11e8-8420-ad6d98f71d1c.png)

John

**Comment by c727** [comment]
If we set a default password we could also drop the password requirement. Also this repo is about docs not hassio add-ons
