### ISSUE TITLE
64.3 lost limitlessled/milight while led strip controllers

### ISSUE THREAD

**Issue by duecedriver** [home-assistant/home-assistant.github.io#4826]
64.3 update broke control of white led strip controllers from limitiless led.

this use to work up to this latest update

light:
  platform: limitlessled
  bridges:
    - host: 192.168.0.5
      groups:
      - number: 1
        type: rgbw
        name: Bedside Lights
        fade: on
      - number: 3
        type: rgbw
        name: Entry
        fade: on
      - number: 4
        type: rgbw
        name: Garage Door
      - number: 1
        type: rgbww
        name: Towers
        fade: on
      - number: 3
        type: white
        name: Curio
        fade: on
      - number: 4
        type: white
        name: Kitchen
        fade: on

does something in this need to be changed now?  These lights were paired to the v6 hub using the limitlessled ios app.. using 2 different virtual controllers and has been working for over a year.

any suggestions appreciated.

**Comment by c727** [comment]
this is the correct repo https://github.com/home-assistant/home-assistant
