### ISSUE TITLE
MQTT Discovery light.mqtt_json

### ISSUE THREAD

**Issue by Kyklas** [home-assistant/home-assistant.github.io#4879]
Hi,

I am about to setup my esp32 to support a light component. I like the light.mqtt_json because it is very flexible and uses a single topic. 

I looked at MQTT Discovery to make the setup easier. It is pretty cool. However it only support light.mqtt as component. Would there be a possibility to support light.mqtt_json ?

The name can be changed in the customization which is pretty cool. Could the platform type be changed ?

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, feature requests and usage.
