### ISSUE TITLE
Synology Installation fails with Home Assistant >0.64

### ISSUE THREAD

**Issue by dfrap** [home-assistant/home-assistant.github.io#4897]
The current Python3 version from Synology is 3.5.1.  The current install directions for Synology will install Home Assistant version 6.5 which will not run.  

Replace: 
`# ./python3 -m pip install homeassistant`
with:
`# ./python3 -m pip install homeassistant==0.64.3`

Add note:  
The current Python3 version from Synology is 3.5.1. Until Synology updates Python, Home Assistant must not be updated beyond 0.64 because versions starting with 0.65 require the minimum Python 3.5.3 level.

**Comment by johnsmunoz** [comment]
Was this implemented?  I see that it was closed but my DSM is still only showing 3.5.1
