### ISSUE TITLE
how to control tv volume? 

### ISSUE THREAD

**Issue by plutosherry** [home-assistant/home-assistant.github.io#4927]
if i used homeassistant to manage the smart TV,but how to control tv volume? 
I can only control the TV switch at the moment
`  - platform: samsungtv
    host: 192.168.1.10
    port: 8001
    name: Samsung TV`
And there are automations.yaml
`- service: media_player.turn_on
    entity_id: media_player.samsung_tv`

**Comment by Landrash** [comment]
For support go to the [need help](https://home-assistant.io/help/) page.
