### ISSUE TITLE
ios component doesn't show up in component search

### ISSUE THREAD

**Issue by JensTimmerman** [home-assistant/home-assistant.github.io#4972]
https://home-assistant.io/components/#search/ios

doesn't show ios component.
Googling however sends me to https://home-assistant.io/docs/ecosystem/ios/
where I discover that there is in fact an ios component, and ios app which offers great tracking and interaction features.

**Comment by point-4ward** [comment]
I thought this too, (having recently moved my other-half's phone over to the ios app for presence detection after it inexplicably stopped reporting on Bluetooth).

Should definitely be moved to the component pages IMO.

**Comment by fabaff** [comment]
The component page was moved to the "Ecosystem" section in the docs a while back and a redirect created. I will replace the redirect with a page that the component will show up in the overview.
