### ISSUE TITLE
Ikea Motion sensor

### ISSUE THREAD

**Issue by neslekkim** [home-assistant/home-assistant.github.io#4998]
State reports battery level?, how can I create an trigger for presence when it reports battery level instead of state?
![image](https://user-images.githubusercontent.com/281342/37857785-55c6ab1c-2efe-11e8-9cbb-7ce3c2b854f8.png)

**Comment by NovapaX** [comment]
The sensors and remotes are not supported (yet) on the tradfri component, nor in pytradfri (the library that gets used for the tradfri integration)
So you can't use them as a trigger. 

Also, this is a home-assistant issue. (you're currently in home-assistant.github.io which is for the website and documentation)

**Comment by MartinHjelmare** [comment]
If you need help please use our help channels:
https://home-assistant.io/help/#communication-channels

Thanks!
