### ISSUE TITLE
Request: Expansion and Clarification of the Documentation Standards

### ISSUE THREAD

**Issue by fortepc** [home-assistant/home-assistant.github.io#4999]
Referenced in the pull request template is the [Documentation Standards](https://home-assistant.io/developers/documentation/standards/). Reading through it however still leaves a lot of room for improvisation. 

My specific issue was in #4978 where I was was unsure if you were supposed to keep the surrounding marks or not. The context was of the example code block used `*marks around the part*` that I had to replace with my own bits. Some documentation uses `[brackets]` some use `"double quotes"` some use `'single quotes'` some don't use anything at all surrounding what you're supposed to replace with your own parts.

I personally prefer putting `[brackets]` around that kind of thing like the [Google Assistant](https://home-assistant.io/components/google_assistant/) docs, but when I put in #4978 I changed it to that but it was refused to be accepted. 

Regardless what the end result is, this is a kind of thing that really should be decided as a uniform decision across all the documentation.

**Comment by frenck** [comment]
Hi @fortepc,

Thanks for the issue. Documentation standard is open for improvement and has improved/changed a lot the last months (including build processes, review e.d.).

In this example change, just like I stated in the PR, the change you proposed was in a piece of yaml code, where `[]` actually has a function/meaning. So I declined the RFC in that case, which is the best thing to do. Leaving the brackets in can cause unexpected behavior. So I would suggest on modifying those Google Assistant docs as well.

Yes, the documentation has a lot of different standards. This is a form of debt, standards have changed/evolved, but the older documentation has not. The actual question/suggestion you have is, how do we delimit a bit that needs to be replaced by the user.

Some options/suggestions collected:
- `[replace me]` -> `[]` has a yaml function, not an option.
- `<replace me>` -> `<>` has a function in Markdown, not an option imho.
- `*replace me*` -> `**` has a function in Markdown, not an option imho.
- `#replace me#`
-  `REPLACE_ME`

**Comment by DubhAd** [comment]
Given that Home Assistant (almost) entirely uses lower case, the last option `REPLACE_ME` (or `REPLACE ME`) seems the most obvious

**Comment by point-4ward** [comment]
I agree, just put things that need replacing in block capitals.

**Comment by fortepc** [comment]
I personally like ```#REPLACE_ME_WITH_YADDA_YADDA#``` the most. 

Is there someone who can weigh in with a more official stamp of approval? I don't want to go on editing this standards page myself, but if someone adds the appropriate ruling to it, I'd be happy to go around helping updating old docs with the new standard.

**Comment by fortepc** [comment]
If only you could do `code` blocks inside of 
```
code blocks
``` 
that would be the best way to do it...

**Comment by fabaff** [comment]
In a lot of places we used just capital letters and `_`. E.g., 

```yaml
sensor:
  - platform: openweathermap
    api_key: YOUR_API_KEY
```

This way the users are often able to launch Home Assistant without significant errors as it's a valid string. Sure, the setup of the component or platform will fail. If we prefix the values with `#` then there will be validation errors instead of login issue or a like. Either way it's logged.

For newbies and people not familiar with YAML it might be more clear if we avoid prefixing it with `#` and just use `REPLACE_ME`. 

Sometimes it's necessary to use quotes are around a string as it's YAML.
