### ISSUE TITLE
Customizing entities device class section incomplete.

### ISSUE THREAD

**Issue by PurelyNicole** [home-assistant/home-assistant.github.io#5034]
The "[Device Class](https://www.home-assistant.io/docs/configuration/customizing-devices/#device-class)" section of [Customizing Entities](https://www.home-assistant.io/docs/configuration/customizing-devices/) is incomplete. Add [all classes](https://github.com/home-assistant/home-assistant-polymer/blob/27d343b4888a0678d8cb828b05a3ac47e29424f1/src/util/hass-util.html#L77) to the list.

**Comment by DubhAd** [comment]
If you can submit an edit suggestion, then that would be much appreciated ;)

**Comment by PurelyNicole** [comment]
I'm planning on fixing this one myself actually. Just wanted to get it logged before I started.

**Comment by PurelyNicole** [comment]
This was me misunderstanding the functionality. Not acutally an issue.
