### ISSUE TITLE
Debian 9/Python 3.6 support?

### ISSUE THREAD

**Issue by ttaidapos** [home-assistant/home-assistant.github.io#5061]
libjson0-dev // Unable to locate package

sudo apt-get -t jessie-backports install libav-tools libavcodec-extra libavcodec-dev libavfilter-dev libavformat-dev //This fails all together

I ran it with:
sudo apt-get install git libav-tools libavcodec-extra libavcodec-dev libavfilter-dev libavformat-dev

sudo make install //produces the following:

make clean && make
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package json was not found in the pkg-config search path.
Perhaps you should add the directory containing `json.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json' found
Package json was not found in the pkg-config search path.
Perhaps you should add the directory containing `json.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json' found
Package ao was not found in the pkg-config search path.
Perhaps you should add the directory containing `ao.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ao' found
Package ao was not found in the pkg-config search path.
Perhaps you should add the directory containing `ao.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ao' found
 CLEAN
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package json was not found in the pkg-config search path.
Perhaps you should add the directory containing `json.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json' found
Package json was not found in the pkg-config search path.
Perhaps you should add the directory containing `json.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json' found
Package ao was not found in the pkg-config search path.
Perhaps you should add the directory containing `ao.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ao' found
Package ao was not found in the pkg-config search path.
Perhaps you should add the directory containing `ao.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ao' found
    CC  src/main.c
In file included from src/main.c:51:0:
src/libpiano/piano.h:32:20: fatal error: gcrypt.h: No such file or directory
 #include <gcrypt.h>
                    ^
compilation terminated.
Makefile:107: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 1

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.
