### ISSUE TITLE
Nest does not work unless you are owner of structure

### ISSUE THREAD

**Issue by abarbaccia** [home-assistant/home-assistant.github.io#5114]
My wife setup the nest account under her login, and added me as a user.  When I added the nest component to HA under my account, it would error out.   Adding it under hers does not produce any errors.  

I think this may be an error in the API because the same issue occurred with the Shield TV nest application.  I would not be able to see any camera streams with my account, but logging in as my wife solved the issue.

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.
