### ISSUE TITLE
DSP-W115 dont work

### ISSUE THREAD

**Issue by yabbah** [home-assistant/home-assistant.github.io#5148]
I bought a D-link wi-fi smrt plug DSP-W115 today. I manage to get it into home assistant. But not able to switch it on/off.

**Comment by yabbah** [comment]
Username should be "Admin", not "admin" as specified in the doc :)

**Comment by yabbah** [comment]
Didn't work anyway. I'm able to access the webpage of the unit and login with the same credentials I use in hass-config.

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

**Comment by camui-alexandru** [comment]
Yea, it is not working in HA !

**Comment by frenck** [comment]
Please don't dig up old closed issues, instead, create a new one. Thanks! :+1:

**Comment by jonassjoh** [comment]
In case anyone is still interested I created a library to interface with the DSP-W115 and the DSP-W245. You can find the library below.

https://github.com/jonassjoh/dspW245
