### ISSUE TITLE
Adding an image to a page

### ISSUE THREAD

**Issue by sebk-666** [home-assistant/home-assistant.github.io#5171]
I made the attached screenshot showing all the icons of the various device classes for binary sensors and I'd like to add it to the [binary sensor documentation](https://www.home-assistant.io/components/binary_sensor/).

I've never added an image to the HA docs before. 
As far as I can see, I'd need to upload the file to the `home-assistant.github.io/source/_components/` directory and then reference it from the `binary_sensor.markdown` page?
However, I don't have permissions to upload the file to the _components directory.

Is anyone able to assist?

Sebastian

![binary_sensor_classes](https://user-images.githubusercontent.com/21690487/38769858-1b797b0c-400a-11e8-9125-9a3605f3c2f3.png)

**Comment by point-4ward** [comment]
You need to clone/fork the repo, add your screenshot to the images folder in your fork, add the link to the image to the doc you're editing, and then create a pull request for your changes (which will be one PR with 2 changed files).

Hope this helps.

**Comment by sebk-666** [comment]
Thanks a lot! That worked!

Sebastian
