### ISSUE TITLE
Hue docs seem outdated:

### ISSUE THREAD

**Issue by kristoffernolgren** [home-assistant/home-assistant.github.io#5256]
I'm trying to install hue hub, but the docs are not the same as the actual thing. The config shows up in configuration/integrations, and, atleast for me, no configfile is created. Though, I also get some errors when rebooting.

https://github.com/home-assistant/home-assistant.github.io/blob/current/source/_components/hue.markdown

**Comment by frenck** [comment]
I've been testing the doc myself yesterday, and it seems to be fine.
Therefore I'm closing this issue.

If you don't agree, feel free to re-open the issue and provide some more details.
