### ISSUE TITLE
how to set scan_interval for hue lights

### ISSUE THREAD

**Issue by tropas2001** [home-assistant/home-assistant.github.io#5324]
This link https://www.home-assistant.io/docs/configuration/platform_options/ uses the old style configuration for hue bulbs and I'm trying to set a scan interval with the new style and can't get anything to work. Please can you update this page?

**Comment by fabaff** [comment]
> Please can you update this page?

Page is generic now -> https://github.com/home-assistant/home-assistant.github.io/commit/07acbae2fb1c0d35efa598ff535a6a88984acee5
