### ISSUE TITLE
Apache as proxy, maybe websocket url is wrong

### ISSUE THREAD

**Issue by steniofilho** [home-assistant/home-assistant.github.io#5326]
In the example that demonstrates how you can configure Apache to act as a proxy for Home Assistant, maybe the url started with ws://localhost is wrong.

I had success changing ws:// to wss://

https://www.home-assistant.io/docs/ecosystem/apache/

**Comment by frenck** [comment]
`ws://` is the correct one to use.
When you are in need for `wss://`, it will be because your Home Assistant runs with SSL certificates.
Not sure why you would do that on a local connection...
