### ISSUE TITLE
Cannot activate home assistant skill

### ISSUE THREAD

**Issue by jasperslot** [home-assistant/home-assistant.github.io#5348]
Hello,

Today I activated the home assistant cloud to try out this great feature. I succeeded in creating and activating account. Unfortunately I cannot use the activate home assistant skill link (https://assistant.google.com/services/a/uid/00000091fd5fb875). It results in a 404 error. The link is completly dead.

I use hassio with home assistant 0.68.1.

Please fix.

Thanks!

**Comment by DubhAd** [comment]
As covered in the [blog post](https://www.home-assistant.io/blog/2018/04/24/launch-google-assistant-support/), this is known and Google hasn't made it live. An update to the docs mentioning this is coming.

Please use the setup steps covered in the blog post.

**Comment by jasperslot** [comment]
I am sorry... I feel a bit stupid right now :(
