### ISSUE TITLE
Schlage Z-Wave Lock Issues

### ISSUE THREAD

**Issue by RonJ103** [home-assistant/home-assistant.github.io#5391]
I own two Schlage Z-Wave locks, the model numbers are FE599NX and BE469.  They both have the following two issues:

1. The "clear_usercode" service does not work.

2. The "lock_status" attribute does not update when Home Assistant is used to lock or unlock the door.  This makes it so automation that are triggered off the lock_status attribute won't be triggered if the same user code unlocks the door multiple times in a row.

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, and usage.

/move to home-assistant/home-assistant
