### ISSUE TITLE
fast.com component overlooking RPi bandwidth limitation

### ISSUE THREAD

**Issue by mitchatmcc** [home-assistant/home-assistant.github.io#5540]
The component for fast.com (https://www.home-assistant.io/components/sensor.fastdotcom/) overlooks that the RPi LAN adapter is limited to 100 MBit/s, and would skew results.

The Speedtest component (https://www.home-assistant.io/components/sensor.speedtest/) has this note:

> When running on Raspberry Pi, just note that the maximum speed is limited by its 100 Mbit/s LAN adapter. 

I attempted to add this note to the fast.com component, but I'm not great at GitHub yet, and didn't want to fork the entire project for one comment.

**Comment by metbril** [comment]
PR #5547 merged. Issue can be closed.
