### ISSUE TITLE
NSW Fuel Sensor

### ISSUE THREAD

**Issue by DavidFW1960** [home-assistant/home-assistant.github.io#5555]
It's ignoring the entered station name. I had to change the friendly name in customize for it to work properly.

**Comment by fabaff** [comment]
There is no support for [entering the station name](https://next.home-assistant.io/components/sensor.nsw_fuel_station/#configuration). The station name should be retrieved according to the station ID.

**Comment by DavidFW1960** [comment]
I see it’s been removed. The docs I saw on github for it had it in there! There were no official docs for b0

**Comment by DavidFW1960** [comment]
It actually still shows it here:
https://github.com/home-assistant/home-assistant/pull/14757
When I click on the docs from the release notes the page doesn't exist.

**Comment by fabaff** [comment]
> It actually still shows it here: home-assistant/home-assistant#14757

That is the configuration which was submitted when the pull request was opened. 

> When I click on the docs from the release notes the page doesn't exist.

The docs PR is now tagged for 0.72.
