### ISSUE TITLE
Auto generated link outdated

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/home-assistant.github.io#5567]
I noticed that on https://www.home-assistant.io/components/sensor.loop_energy/ the link in the right hand column (to `loop_energy.py`) is broken and should point to [loopenergy.py](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/loopenergy.py). I gather this part of the webpage is auto-generated. The component was added in 0.17 so perhaps other old links are outdated also.

**Comment by fabaff** [comment]
Thanks for the report. Should be fixed now.
