### ISSUE TITLE
new platform available: Apple Airport Router, bring  us an Internet Connection binary sensor and new device tracker.

### ISSUE THREAD

**Issue by xcray** [home-assistant/home-assistant.github.io#5599]
Excuse me pls, I'am not familiar with github yet.
I don't know how to make contributions as well as required, Just share a piece of good news.
I've just tested today.

https://github.com/xcray/Apple_Airport_hass_devicetracker_and_Internet_Connection_Sensor

Maybe someone could help to merge to the doc site.

**Comment by frenck** [comment]
I'm not sure about your question.

The link you gave shows a Python script, but this thing is not Home Assistant related.
The documentation contains stuff regarding features of Home Assistant itself, not external scripts.

Feel free to open a Feature request on the community forum:

<https://community.home-assistant.io>

**Comment by xcray** [comment]
Thanks for your comment!
In fact, I think make a new feature to receive syslog messages (the only way available for apple airport routers) is more difficult. Since rsyslog has become the factual standard, especially on various Linux distributions, and it has a cool interface (omprog) to call external program, and Home Assistant has also a cool API interface, I think the best choice is thus a very simple script, if the Apple Airport routers' users want to integrate the router into HA.
Very similar to [OpenWRT](https://www.home-assistant.io/components/device_tracker.openwrt/), if there are instructions on the official HA document site, more people could be benefited.
On the other hand, the instruction page of OpenWRT and this one, could be real samples of the usage of HA API.
