### ISSUE TITLE
RfxTrx Documentation: Potentially invalid IDs 

### ISSUE THREAD

**Issue by drgrandios** [home-assistant/home-assistant.github.io#5608]
When configuring an RfxTrx packet ID which is made of digits only within the YAML file, the ID is registered as a number (which will be reported as an invalid device later). Adding the ID within double quotes solves the issue - this should be mentioned in the RfxTrx doc, especially in the description how to add switches: [https://www.home-assistant.io/components/switch.rfxtrx/](https://www.home-assistant.io/components/switch.rfxtrx/)

See also this thread:
[https://community.home-assistant.io/t/problems-adding-rfxtrx-switches/32194/3](https://community.home-assistant.io/t/problems-adding-rfxtrx-switches/32194/3)

**Comment by frenck** [comment]
Valid point, this needs to be addressed.

**Comment by metbril** [comment]
Does this only apply to switches or to any rfxtrx device? My guess is the lattter.

**Comment by drgrandios** [comment]
It's a generic YAML "feature" and applies to all RfxTrx devices.

**Comment by frenck** [comment]
This is indeed a YAML thingy. YAML will try to "guess" the type. In case of numbers it guesses int, which strips of the zero (`0`) in the beginning, in this case, they do matter.

**Comment by metbril** [comment]
So we need to modify any rfxtrx related component and/or the platform. Not just the switch.

- [ ] switch
- [ ] light
- [ ] cover
- [ ] sensor
- [ ] binary sensor

**Comment by metbril** [comment]
I'm working on a PR.

Suggested text:

```
<p class='note warning'>
If a device ID consists of only numbers, please make sure to surround it with quotes. 
This is a known limitation in YAML, because the device ID will be interpreted it as a number otherwise.
</p>
```

Will this do?

**Comment by frenck** [comment]
@metbril Don't forget about the examples...

**Comment by metbril** [comment]
No I won’t. ;-)

**Comment by drgrandios** [comment]
Very nice, thank you guys!!

**Comment by frenck** [comment]
The PR fixing the documentation has been merged.
Closing this issue.
