### ISSUE TITLE
Update on docker image on Synology NAS not clear

### ISSUE THREAD

**Issue by gwystyl** [home-assistant/home-assistant.github.io#5619]
**The documentation states:** 
[begin documentation]
Remark: to update your Home Assistant on your Docker within Synology NAS, you just have to do the following:

Go to the Docker-app and move to "Image"-section
Download the "homeassistant/home-assistant" image - don't care, that it is already there
wait until the system-message/-notification comes up, that the download is finished (there is no progress bar)
Move to "Container"-section
Stop your container if it's running
Right-click on it and select "Action"->"Clear". You won't lose any data, as all files are stored in your config-directory
Start the container again - it will then boot up with the new Home Assistant image
[end documentation]

I was under the impression that I could somehow download the new image in the image-section. This isn't the case; it has to be done in the "register" section. Can this be changed or added?

**Comment by frenck** [comment]
Seems like this one is in progress, see #5335
