### ISSUE TITLE
"Xiaomi Cameras" and "Yi Home Camera" are almost redundant, and not accurate about rtsp method

### ISSUE THREAD

**Issue by xcray** [home-assistant/home-assistant.github.io#5632]
Why two duplicated platforms?
And ftp is a good choice for cameras? at least 1 minitus ago.......
In fact, I think RTSP with FFMPEG is the best choice for at least Yi 720P models.
I am using this way, and the official Mijia (MiHome) & Yi apps works well at the same time.

**Comment by bachya** [comment]
Please read the docs (especially for Yi); there is a clear explanation of (a) why RTSP isn’t feasible and (b) why FTP was chosen.

Also, although the codebases are similar, there is a high likelihood that they will diverge at some point; separation at this stage will make this future state easier.

**Comment by xcray** [comment]
Yes, there IS statement in the docs saying:

> Some alternative Yi firmwares enable an experimental RTSP server, which will allow you to connect to your camera via other Home Assistant camera platforms. However, this RTSP server disables the ability to use the supremely-useful Yi Home app. In order to maintain both Home Assistant compatibility and the native app, this platform retrieves videos via FTP.

But on my integration, Yi 720p works quite well, and native apps (both of Mijia, MiHome and Yi apps) also works quite well.

On other models, maybe there isn't a prover version of RTSP server, but on Yi 720p, there IS, originally named rtspM, works well on the newest firmware, 1.8.7.0C_201705091058.

And these two platforms looks so Maybe, FTP camera is a better name, for both xiaomi camera and yi camera here, for all the cameras could run ftp server, just like ffmpeg camera, for all the cameras could be connected by ffmpeg.
