### ISSUE TITLE
Balloob incorrectly modified Cast page

### ISSUE THREAD

**Issue by dcnoren** [home-assistant/home-assistant.github.io#5673]
https://github.com/home-assistant/home-assistant.github.io/commit/895e74b44b8fe4d82e7d5b8dcaa408d329755a36

cast: as the top-level YAML isn't working. Needs to be media_player: as top level. Balloob changed it, but just tested changes on latest version of hass and the changes break cast integration. Charges from 15 days ago need to be undone.

**Comment by mnoorenberghe** [comment]
It works for me. Did you enable the Cast component by going to the Integrations page as the change in question mentions?

**Comment by frenck** [comment]
Closing this is per solution above.
