### ISSUE TITLE
[EPIC] Jekyll -> Hugo migration

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#5744]
Please note, this is an EPIC issue and functions as a parent that groups all tickets/issues for this project. Please check our Waffle board for the current progress:

[https://waffle.io/home-assistant/home-assistant.io](https://waffle.io/home-assistant/home-assistant.io?epics=none&epic=5b4514ff7a6ed6001d1a3233)

Preview of the `hugo` branch is build by Netlify (just like our site) and can be found here:

https://deploy-preview-5746--home-assistant-docs.netlify.com/

This project is, for now, lead by @frenck and @balloob.

## Pre-warning

This project is not definitive and is currently in an exploratory and experimental state.

This project is currently not in a stage where you could jump in the help development. We'll update this issue as soon as that becomes possible.

## Problem / Motivation

Generating and maintaining our website (and documentation) becomes a more significant problem every day.

Some issues:
- **Jekyll is freaking slow**. A build takes ages and often fails due to time-outs.
- Complicated for users to set up an actual local environment
  - Causes PR's to be "untested".
  - Causes PR's to need multiple commits and build to actually succeed.

There are probably more issues with the current site (how about adding multiple languages? New forms of navigation?); nevertheless, the bove is the biggest hurt at this moment.

## Requirements

Well, it needs to solve the above-listed problems at least. Everything else would be nice.

Another thing would be a possible migration path that we could handle. There are thousands of pages on our website (estimated 2k+ pages), and we surely don't want to rewrite them all. That would be simply impossible. Being able to reuse the content is also quite mandatory because of the open PRs and running changes.

## Direction

I've been looking into multiple solutions for quite some time now. One of those is currently used at the [developers documentation](https://developers.home-assistant.io/) implemented by @balloob; [Docusaurus](https://docusaurus.io/).

Docusaurus is incredible, especially for documentation and "smaller" websites. However, it will suffer from similar problems as Jekyll when used at the scale we currently do for our website.

I've also looked at many more (Next, Gatsby, Hexo), but most are Javascript based and Go based: Hugo.

## Hugo

[Hugo](https://gohugo.io) is one of the other popular choices (27K+ GitHub stars).
Some selling points:

- Hugo is written in Go and shipped as single pre-compiled static binaries for almost every platform in this world. Users could just get the executable, run it and start developing on our documentation/website. The installation steps are well [documented](https://gohugo.io/getting-started/installing/).

- Hugo is very similar in terms of structure and general way of working. Initial tests with our current files, where not even that disappointing.

- It is blazing fast! A screenshot with a local basic rendering of our (almost) whole site:

![image](https://user-images.githubusercontent.com/195327/42534072-041a0190-848c-11e8-86e9-3c2bb5a77bb9.png)

- Hugo has internationalization built-in (for future use).

- Netlify = still a go.

## Approach

We'll start by developing this project in a separate branch [`hugo`](https://github.com/home-assistant/home-assistant.github.io/tree/hugo), which will actually never be merged into our main branch. The reason for this is that our main branches and this branch will diverge big time, even merging in the upstream regularly would be impossible/hell.

The primary goal is to create the basic setup, templates and work out the quirks. After completion of the project, the migration will be done "again" on the main branches. The exact strategies for this will be planned in a later stage of the project.

@frenck will start with the basic setup and create as much issues/tickets as needed.
After Hugo is able to run, feel free to jump in on the issues created.

## References

<https://gohugo.io>
<https://kubernetes.io/blog/2018/05/05/hugo-migration/>
<https://www.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here/>
<https://www.smashingmagazine.com/2016/08/using-a-static-site-generator-at-scale-lessons-learned/>

<https://github.com/netlify/victor-hugo>
<https://github.com/kubernetes/website>

## Final notes

The above is incomplete and will grow over time. 
Feel free to edit the start topic and add to it, or discuss in this issue.
Another good place for discussion would be the #documentation channel on our Discord server.

**Comment by balloob** [comment]
Another motivation for me is that with Hugo internationalization is built-in.

**Comment by fabaff** [comment]
I'm all for a change as I hate to wait for the builds to pass. Especially if we can bring it down from 10 min to 30 seconds, it doesn't need to be 4 seconds and it will most likely not be. 

Built-in support I18n/l10n support is indeed nice.

As you want local previews for larger changes, the generator needs to easy installable. I'm not a big fan of "single pre-compiled static binaries" but it will definitely lower that barrier to contribute to the docs. Oh, it's just `$ sudo dnf -y install hugo`...

**Comment by frenck** [comment]
@fabaff It is indeed installable via multiple sources. Most distro's (including Mac brew) have Hugo available. I think we could also provide a Dockerfile/container to allow local development with a simple Docker run command.

4 seconds is probably unrealistic when everything is ported properly. The screenshot is just there to provide some insights. For me personally, 5 minutes would be kinda the border of being acceptable or not, but I'm quite sure Hugo will be able to beat that with ease.

**Comment by frenck** [comment]
# Status update

Got the branch going. Things are moving forward pretty OK.
So far:
- Removed all Jekyll stuff.
- Added basic Hugo configuration and setup.
- Added a Hugo theme, which was extended with some features.
- Added Netlify builds (see URL in OP).

Not pushed to the `hugo` branch yet:
- Started on documenting a Migration plan/steps.
- Moved all static files (e.g. images) into their new locations.
- Moved all content into new location, so it actuall can render.
- Added `linkable_titles` migration.
- Added `raw` / `endraw` migration.
- Added `site_root` migration.
- Added Syntax Highlighting (based on Chroma, Pygments compatible output).

Currently, the build time is still under 4 seconds.

**Comment by frenck** [comment]
update, still working on this for time to time. Planning on continuing soon.
