### ISSUE TITLE
Docker for local documentation/website development

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#5751]
Child of #5744 

Add a Dockerfile/Docker container that allows for the local development of the documentation.

This would remove the need for installing Hugo locally and would remove specific version dependencies.

**Comment by frenck** [comment]
Please don't my little bot friend.

**Comment by fredrikbaberg** [comment]
This might be a bit too "simple", but would it be enough with the following? Or do you want a dedicated Dockerfile/container?

`docker run --rm -it -p 1313:1313 -v $(pwd):/usr/share/blog monachus/hugo`

**Comment by frenck** [comment]
That would probably do, yes.
But I can imagine we are having our own version to lock down the version used.

**Comment by frenck** [comment]
Close it for now.
