### ISSUE TITLE
Picture Elements Card - Firefox

### ISSUE THREAD

**Issue by Tyre88** [home-assistant/home-assistant.github.io#5753]
The elements are not placed well in firefox, they are not placed inside of the picture but below it.  
![bild](https://user-images.githubusercontent.com/4730856/42568070-1ce33edc-850c-11e8-865e-9924fa81be9d.png)

In Chrome it looks like this:
![bild](https://user-images.githubusercontent.com/4730856/42568096-3025bbbe-850c-11e8-8aa5-c5c4d4f15046.png)

**Comment by fabaff** [comment]
This is the bug/issue tracker for the Home Assistant documentation. Please use the [forum](https://community.home-assistant.io/) for questions about installation, setup and configuration.
