### ISSUE TITLE
Inconsistent/insufficient info about new hassos network config

### ISSUE THREAD

**Issue by scop** [home-assistant/home-assistant.github.io#5775]
https://www.home-assistant.io/hassio/installation/

The above doc says that for networking configuration, the file `network/my-network` should be created on the SD card. But it fails to mention on which volume of the SD card it should be placed in. There are four volumes on the card after writing it using etcher: data, hassos-data, hassos-kernel, and hassos-overlay. (At least hassos-overlay didn't seem to work.)

https://www.home-assistant.io/blog/2018/07/11/hassio-images/

This blog entry doesn't mention the `network/my-network` file at all, nor the possibility to write it on the SD card. Instead it refers to using an USB stick, and a different `network/resin-sample` file on it.

**Comment by cogneato** [comment]
Yes, there is a bit of old vs new going on, as a result of re-using old documentation.

- References to using the SD card for the network configuration should be dropped altogether.
- The instruction for putting "resin-sample" on the USB is also not correct (as this is no longer resinOS)
- The network connection files can have any name, as it was before. "resin-sample" was the default name for the older resinOS base.

**Comment by scop** [comment]
I hope there is/will be a way to use the SD card someway, as requiring an additional USB stick is pretty cumbersome. Can't access my HA SD card right now, but IIRC I managed to make some settings to /etc/NetworkManager/system-connections/[connection-name] on the hassos-overlay volume but that was after the first boot. Assuming that's correct, perhaps that volume and file could be used similarly for provisioning network settings before the first boot?

**Comment by kajmaj** [comment]
Anyhow I tried several USBs formated FAT, FAT32, NTFS, various versions od connection configuration - auto mode,  static IP but no result at all.
Apparently it has something to do with HassOS, because with HassIO there was no problem at all.

**Comment by fairchildbrad** [comment]
I continue to have these issues as well.  The official documentation does not work when it comes to setting up a network on hassio/hassos, specifically a static ip on a wired (802.3) network.

**Comment by pabelanger** [comment]
How is this issue stale? This is a valid issue, as I've just ran into it myself.

**Comment by omigeot** [comment]
Looks like it still a problem. How do we set up networking on a recent Hassos install?

**Comment by CarlosGS** [comment]
Yep, newbie here also fighting with network config.

Edit: Nevermind, the /hassio-boot partition was hidden and had to mount it manually. All working now!
