### ISSUE TITLE
Add reminder about "/local/"

### ISSUE THREAD

**Issue by jakubradziwon** [home-assistant/home-assistant.github.io#5804]
Can you post on site small reminder about what "/local/" is (regarding for example location of images) in lovelace section? Additionaly it is worth to say, that although lovelace refreshes easily, to show "/local" to HA one must restart HA. It took me a long while to figure out how to use pictures on cards.
Best regards

**Comment by frenck** [comment]
Hi there @jakubradziwon!

Thank you for your suggestion, feel free to open a pull request with the suggested changes! ❤️

**Comment by jakubradziwon** [comment]
Hi @frenck ,
this is my first time, I hope I did it correctly : https://github.com/home-assistant/home-assistant.io/pull/5828

**Comment by fabaff** [comment]
Was merged.
