### ISSUE TITLE
Dead link in addons section

### ISSUE THREAD

**Issue by olskar** [home-assistant/home-assistant.github.io#5827]
The component custom_deps links to this page that does not exist: https://www.home-assistant.io/addons/custom_deps/

I guess it is because it does not exist in here?
https://github.com/home-assistant/home-assistant.io/tree/next/source/_addons

**Comment by fabaff** [comment]
Where is that link located?

**Comment by olskar** [comment]
@fabaff https://github.com/home-assistant/hassio-addons/blob/master/custom_deps/config.json
