### ISSUE TITLE
Include full URLs in atom xml feeds

### ISSUE THREAD

**Issue by grischard** [home-assistant/home-assistant.github.io#5856]
The current xml feed uses relative URLs:

```html
<a href="/components/#version/0.74">
<img src="/images/blog/2018-07-0.74/components.png" style="border: 0;box-shadow: none;" />
</a>
```

By the time the feed is displayed to a human, the human's feed downloader/reader pipeline might have lost track of what the base url should be. The feed might be displayed in a web browser on another base url entirely.

Would it please be possible to include full URLs in the atom xml feed? Like so:

```html
<a href="https://www.home-assistant.io/components/#version/0.74">
<img src="https://www.home-assistant.io/images/blog/2018-07-0.74/components.png" style="border: 0;box-shadow: none;" />
</a>
```

https://github.com/home-assistant/home-assistant.io/blob/next/source/atom.xml already pipes through [octopress-filters' `full_urls`](https://github.com/octopress/filters) but the right gem isn't included in the Gemfile.

**Comment by grischard** [comment]
This is still the case.

**Comment by frenck** [comment]
Correct and seems not fixable at this point to be honest. I've tried several solutions, but a solid fix is not something I foresee at this point. Enabling the octopress filter also did nothing.

**Comment by grischard** [comment]
So should this be closed as wontfix?

**Comment by frenck** [comment]
Yep, let us do that for now.
