### ISSUE TITLE
Issue with automation and Lovelace

### ISSUE THREAD

**Issue by edoardop13** [home-assistant/home-assistant.github.io#5874]
After updating to 0.74 only the automations appeared with the "On" or "off" flag. 
Can you go back to the old switch? 

After upgrade to 0.74
<img width="491" alt="schermata 2018-07-24 alle 18 33 07" src="https://user-images.githubusercontent.com/40502451/43152922-2bc80982-8f70-11e8-947a-a3e7d0863cb7.png">

Before upgrade
<img width="385" alt="schermata 2018-07-24 alle 18 33 54" src="https://user-images.githubusercontent.com/40502451/43152951-41ad8d44-8f70-11e8-8283-251f09bbbf06.png">

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
