### ISSUE TITLE
rpi_camera documentation not working

### ISSUE THREAD

**Issue by Chamondgl** [home-assistant/home-assistant.github.io#5920]
The documentation for rpi_camera is not accurate. Hassio and rpi_camera seems broken according to multiple posts on Github and the forum.

https://www.home-assistant.io/components/camera.rpi_camera/

**Comment by fabaff** [comment]
The platform is not broken, it's just not supported as `raspistill` is not included in the image.

Please use the forum for a [feature requests](https://community.home-assistant.io/c/feature-requests). Thanks
