### ISSUE TITLE
telegram_bot service delete_message: missing reference

### ISSUE THREAD

**Issue by omhy** [home-assistant/home-assistant.github.io#5932]
Parameter's "message_id" descriptions is missing reference for property.
There should be "trigger.event.data.message.message_id" instead of empty string.

**Comment by MartinHjelmare** [comment]
Please fill in the issue template completely and add a link to the referenced code in the source.

**Comment by omhy** [comment]
Sorry, It's my first created issue on github ever.
Looks like there is a lot of places where is used info in "{{ some_data_that_should_be_visible_in_web }}" format which is evaluated to empty quotes in web.
![issue](https://user-images.githubusercontent.com/15945133/43449190-7de94ee0-94b8-11e8-8702-da4e3dd20ab1.gif)

**Comment by MartinHjelmare** [comment]
Looks like those templates are missing `%raw%` and `%endraw%` tags around them.
