### ISSUE TITLE
door/window sensor tuya

### ISSUE THREAD

**Issue by razion12** [home-assistant/home-assistant.github.io#5968]
hello a great project you have on the run! Is it possible to integrate the door window sensor in hassio? Thx

**Comment by MartinHjelmare** [comment]
You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum. Thanks!

**Comment by razion12** [comment]
@MartinHjelmare ok
