### ISSUE TITLE
Wrong message in spanish translation

### ISSUE THREAD

**Issue by etatus** [home-assistant/home-assistant.github.io#5982]
Hi there, I recently installed Home Assistant and I detected a wrong message when you configure a switch (mqtt in my case) and you turn it on/off. Despite it works, the message always says there is an error:

“Error al llamar al servicio switch/turn_on”
“Error al llamar al servicio switch/turn_off”

In English the message is correct (no errors) and logs don't show errors, so I guess it is a problem related to the translation that maybe affects to other modules.

**Comment by frenck** [comment]
Translations are not maintained in this repository.
For more information on translations and how to contribute/change them:

https://developers.home-assistant.io/docs/en/internationalization_translation.html
