### ISSUE TITLE
Wrong section in the description

### ISSUE THREAD

**Issue by labrats-x7** [home-assistant/home-assistant.github.io#5987]
`The result set will include your chat ID as id in the from section:`

should be "**chat**" not "**from**"

https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/notify.telegram.markdown

**Comment by frenck** [comment]
Maybe submit a PR? 

![bitmoji](https://render.bitstrips.com/v2/cpanel/a4838507-86be-4787-a65e-74221faa8027-82100c49-8c0a-4ae4-9b04-3a6d3eac9cc2-v1.png?transparent=1&palette=1&width=246)
