### ISSUE TITLE
example config invalid

### ISSUE THREAD

**Issue by tmechen** [home-assistant/home-assistant.github.io#6007]
the example config on this [page](https://www.home-assistant.io/addons/git_pull/) 
is invalid. not because of the invalid key or the wrong repository, it just throws a ``not a valid value for dictionary value`` error without the keys for user and password. After adding this two lines it allows me to save the config.
> "deployment_user":  
> "deployment_password": "",

**Comment by DubhAd** [comment]
Can you use the *Edit this page on GitHub* link on that page and submit a PR with those changes please.

**Comment by tmechen** [comment]
i am currently trying to verify a way to actually use the deployment_key at all... i can only use this addon with the user/pw combination...   
*edit*
okay nvm, i am pretty stupid :D i deactivated the ssh option for my git installation, therefore i obviously cannot use a deployment key to pull via ssh.

**Comment by frenck** [comment]
Fixed, thanks for reporting @tmechen! 👍
