### ISSUE TITLE
Migrate away from using "--net=host" mode in the docker install guide

### ISSUE THREAD

**Issue by jwater7** [home-assistant/home-assistant.github.io#6025]
Using ports (-p option) is a more versatile approach (e.g. supports multiple instances, etc) that is better accepted as "best practice" for running docker containers.  We should update the documentation so that it uses named ports as the primary/preferred way of setting up the container here:
https://www.home-assistant.io/docs/installation/docker/

**Comment by pvizeli** [comment]
That could not work with home-assistant. There are so many library and discovery functions they need run on host.

**Comment by jwater7** [comment]
I know it will probably mostly work because that’s how I run it.  Which things are you concerned about?  Maybe they could be spelled out as limitations (and would also encourage good practices for implementing different services)
