### ISSUE TITLE
Getting Started - z-wave: Shows soft reset instructions that break z-stick until restart

### ISSUE THREAD

**Issue by john-ruddy** [home-assistant/home-assistant.github.io#606]
Starting to get z-wave configured and ran across a forum post that said the soft reset instructions break z-stick until restart. I'm not having this problem but it seems there should be a note on  https://home-assistant.io/getting-started/z-wave/ about this configuration not working.

Relevant post
https://community.home-assistant.io/t/zwave-freak-out-overnight/1987

**Comment by Landrash** [comment]
Fixed with https://github.com/home-assistant/home-assistant.github.io/pull/935
