### ISSUE TITLE
Xiaomi Robot token

### ISSUE THREAD

**Issue by weidenka** [home-assistant/home-assistant.github.io#6092]
I were following the description for iOS at https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/vacuum.xiaomi_miio.markdown to get the token for the XiaoMi Cloud. 

Unfortunatly, the *.sqlite database does not contain which matches
```SELECT ZTOKEN FROM ZDEVICE WHERE ZNAME LIKE "%Vacuum%"```. 
All I can find is a key named ```XiaoMi```. Is this the correct one? Or is it not possible anymore to obtain the token in that way? The version of Mi Home App is currently 4.8.4.

**Comment by azogue** [comment]
I had to recover a new token a few months ago (May, 11) and I had no problems doing it, but I don't know what Mi Home app version I was running nor I know if it has changed its data base recently. 

Have you got the correct .sqlite db? **Have you tried to open and explore it?** It has one row for each device you own, so it is not very big (in my case, three rows, for a yeelight strip, a Xiaomi router and the vacuum cleaner)

Mine was:
![mi_home_db](https://user-images.githubusercontent.com/9748301/44657326-bc408d80-a9fc-11e8-9d45-3f178917c225.png)

**Comment by weidenka** [comment]
Ok now I understand. I get the same:
![screen shot 2018-08-27 at 13 38 42](https://user-images.githubusercontent.com/2812521/44657860-b64bac00-a9fe-11e8-9138-d89325bbc51c.png)
Probably you should change the database command from
```SELECT ZTOKEN FROM ZDEVICE WHERE ZNAME LIKE "%Vacuum%"```
to
```SELECT ZTOKEN FROM ZDEVICE WHERE ZMODEL LIKE "%vacuum%"```
I guess ```ZNAME``` is the name that I give to the device at setup and therefore depends on the setup.

**Comment by azogue** [comment]
> Probably you should change the database command from
SELECT ZTOKEN FROM ZDEVICE WHERE ZNAME LIKE "%Vacuum%"
to
SELECT ZTOKEN FROM ZDEVICE WHERE ZMODEL LIKE "%vacuum%"
I guess ZNAME is the name that I give to the device at setup and therefore depends on the setup.

**You are totally right**. Feel free to open a small PR in [home-assistant.io](https://github.com/home-assistant/home-assistant.io/pulls) to change it, please!

**Comment by fabaff** [comment]
Was fixed with https://github.com/home-assistant/home-assistant.io/pull/6095/commits/7c2a2bce6adf06a1722ecee7cc10f68fccc6b5ed
