### ISSUE TITLE
Docker Automatic updates Sugestion

### ISSUE THREAD

**Issue by vincentcox** [home-assistant/home-assistant.github.io#6123]
In the documentation (https://github.com/home-assistant/home-assistant.io/blob/current/source/_docs/installation/docker.markdown) is stated the following:

`To update your Home Assistant on your Docker within Qnap/Synology NAS, you just remove container and image and do steps again (Don’t remove “config” folder).`

What I use for my docker containers on my NAS is [watchtower](https://github.com/v2tec/watchtower). 

----------

With watchtower you can update the running version of your containerized app simply by pushing a new image to the Docker Hub or your own image registry. Watchtower will pull down your new image, gracefully shut down your existing container and restart it with the same options that were used when it was deployed initially.

----------

It automaticly pulls the latest version at a user specified time (let's say in the night). And it will make sure that you are always using the latest version without going trough the steps. 

For security reasons I think it's important that users keep their docker images updated.

**Comment by Kane610** [comment]
You can add this as an example in a PR directly from Githubs frontend👍

**Comment by vincentcox** [comment]
Ok great, I will add this as soon as I have time to double check my commands (reproduce it on my NAS) and check their documentation.
