### ISSUE TITLE
page on mosquitto unclear to me

### ISSUE THREAD

**Issue by WouterrV** [home-assistant/home-assistant.github.io#6187]
This page: https://www.home-assistant.io/addons/mosquitto/

Starts out with a JSON object. What is this json for? Isn't home-assistant configured with YAML? This is not a retorical question, I'm a beginner with home-assistant.

**Comment by fabaff** [comment]
This is the documentation for the Mosquitto Hass.io Add-on.

You are looking for [this](https://www.home-assistant.io/components/mqtt/).
