### ISSUE TITLE
Error install home assistant on ubuntu server 16.04

### ISSUE THREAD

**Issue by sangt1989hn** [home-assistant/home-assistant.github.io#6216]
i wan't install home assistant but, it's display as flow
![capture](https://user-images.githubusercontent.com/36691791/45208728-7cf42580-b2b5-11e8-8610-810d4d3c2334.PNG)

**Comment by fabaff** [comment]
Please check https://www.home-assistant.io/docs/installation/

Use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
