### ISSUE TITLE
small spelling mistake

### ISSUE THREAD

**Issue by nickrout** [home-assistant/home-assistant.github.io#6233]
in https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/konnected.markdown there is a ref to configuration.yml instead of .yaml

**Comment by frenck** [comment]
Created a PR to solve this.

BTW: Feel free to edit the documentation yourself! 👍

**Comment by nickrout** [comment]
How do I do that? Is it only by PR?

**Comment by frenck** [comment]
@nickrout Every page in the documentation has an "Edit this page" link at the top right. This will allow you to edit the documentation in the browser and create a PR.

**Comment by nickrout** [comment]
Well bugger me, I never saw the edit button before. Excellent, I have spotted some other typos and I will do what I can to fix them. Love to help in any way I can.
