### ISSUE TITLE
iAlarm component also compatible with other vendors

### ISSUE THREAD

**Issue by RyuzakiKK** [home-assistant/home-assistant.github.io#6282]
Here https://github.com/RyuzakiKK/pyialarm/issues/1 a user confirmed that the pyialarm library used for iAlarm systems also works with the Meian ST-VGT.
It seems that it is a Chinese alarm system, also sold as Emooluxr ST-VGT here https://www.aliexpress.com/item/433MHz-Focus-Alarm-ST-VGT-TCP-IP-GSM-Alarm-Control-Panel-System-Support-WEB-IE-Programmable/32570899449.html

What's the best way to describe this? I was thinking about adding this information in the `alarm_control_panel.ialarm.markdown` page, but I'm not sure if this is the best way to handle this situation.

**Comment by fabaff** [comment]
There are already a bunch of platforms which are mentioning that they are working for different brands. For users it can be useful to add a list that covers this. Feels free to add it to the iAlarm documentation.
