### ISSUE TITLE
Update to OneWire integration text

### ISSUE THREAD

**Issue by icewraithuk** [home-assistant/home-assistant.github.io#6297]
https://github.com/home-assistant/home-assistant.github.io/tree/current/source/_components/sensor.onewire.markdown

Please could you add this text under the RPi section, I've just fought my way through making this work and would like to make it easier for others-

> The RPi does not start the OneWire system by default, so you have to remove the SD card and plug it into a (windows) computer. It does not mount under OSX. You are looking for the Boot drive, and a file called config.txt - edit this file with notepad and add the following line:
dtoverlay=w1-gpio-pullup,gpiopin=4

> Save the file and safely eject the SD card before plugging back into your RPi, once it has booted up again you'll be able to see a new device on your dashboard (assuming you've already put the code into the configuration.yaml file under the **sensor** heading (  - platform: onewire). It is that weird long name that you can then put under names instead of some_id and give it a friendly name that makes sense to you. Reload your config again and your new sensor should be showing with the name you gave it.

**Comment by fabaff** [comment]
Well, the first section looks like duplicating the content which is provided by Waveshare and the included link. 

The second section pretty much describes in words what the configuration of the platform is doing.

**Comment by icewraithuk** [comment]
Correct, it's about putting it all in one place and making it easy/accessible, currently you have to hunt around in forums, get annoyed, eventually figure it out, this is to help someone else get a simple thing done quickly

**Comment by fabaff** [comment]
Following one link is "not hunting around", this is easy accessible.

Please create a PR with the changes you are proposing. Just keep in mind, that every content we duplicate from a third party source has to be maintained.
