### ISSUE TITLE
Check the IoT classes

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant.github.io#6387]
The [`ha_iot_class`](https://developers.home-assistant.io/docs/en/documentation_create_page.html#configuration) entries could be outdated. Check if the class still matches the current implementation.

This the tracking issue. Please don't close but add as a reference to your Pull request.

**Comment by fabaff** [comment]
#6408

**Comment by klaasnicolaas** [comment]
will look if I can help with this 😉

**Comment by fabaff** [comment]
That would be awesome. Adding a feature to filter the integration according the `ha_iot_class` is still on the ToDo list somewhere.

**Comment by klaasnicolaas** [comment]
not `stale` still a work in progress
