### ISSUE TITLE
Add Integration Quality Scale

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant.github.io#6388]
The [Integration Quality Scale](https://www.home-assistant.io/docs/quality_scale) is brand new. To make this information available for the users it should be added to the platform and component documentation.

- "Internal" integrations are except (see https://github.com/home-assistant/architecture/issues/82)
- Check the [Integration Quality Scale Developer documentation](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html) for the requirements.

This the tracking issue. Please don't close but add as a reference to your Pull request.

**Comment by WebSpider** [comment]
Two questions on this:

1) If a component doesn't qualify for "No score" because it doesn't follow coding standards, how do we mark the component?
2) What is the ha_qa_style tag for "No score", is it "none" ?

**Comment by frenck** [comment]
@WebSpider 1. We don't add the marker. 2. We don't add the marker. 😉

**Comment by WebSpider** [comment]
OK, so how to you keep track of 'we haven't looked at this plugin yet' vs 'this doesn't have a IQS rating'?

**Comment by frenck** [comment]
@WebSpider We currently don't.
But you already knew that, since you've opened an RFC on the architecture repository about that.

Ref: home-assistant/architecture#96

**Comment by WebSpider** [comment]
Well, I wasnt sure, but now I am :)
For now I will add a comment in the commit and PR which ones I've reviewed so far to prevent people from doing double work.

**Comment by WebSpider** [comment]
Don't think this general ticket should be closed

**Comment by rohankapoorcom** [comment]
Removing stale from this issue
