### ISSUE TITLE
Enriching the updater with a rest sensor and a (cool) automation to give all release juicy stuff

### ISSUE THREAD

**Issue by ohadbenita** [home-assistant/home-assistant.github.io#6809]
See my [post ](https://community.home-assistant.io/t/hass-released-version-automation-with-release-notes/73103)from the HASS forum

**Comment by fabaff** [comment]
Please create a PR to include it in the [Examples section](https://www.home-assistant.io/cookbook/).

**Comment by ohadbenita** [comment]
Sorry for my (probably dumb) question but how can this be done @fabaff ?

**Comment by fabaff** [comment]
To get started: https://developers.home-assistant.io/docs/en/documentation_index.html
