### ISSUE TITLE
Icon color 

### ISSUE THREAD

**Issue by folrewef** [home-assistant/home-assistant.github.io#6860]
I do not really have an issue but am looking for help.

I notice inte the glance card that the light icon changes color depending on state. In the default it is blue when off and yellow when on. It is also "off-yellow" if the brightness is reduced.

I notice the in the picture-glance card this is not the case. Instead the icon is either gray or white.

I am using a custom card (button-card). I would like to use color settings that are:

when off = the color of the bulb related to the theme I am using
when on = yellow and off yellow.

I solved this partly by:

Setting the color when off to "var(--state-icon-color)" and making sure that state-icon-color is defined in the theme if different from default.
Setting the color when off to "var(--state-icon-active-color)".

This makes it correspond to what you have in the glance card with the exception of that no change is seen relating to brightness.

I would be really interesting to understand how the colors of a light are set in the glance card and if I could use that in a custom card such as button-card.

Thank you for any help.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
