### ISSUE TITLE
'Device class' link is broken

### ISSUE THREAD

**Issue by WofWca** [home-assistant/home-assistant.github.io#6904]
[Here](https://www.home-assistant.io/docs/configuration/customizing-devices/#device_class
). 'device_class' labeled link.
This would work if the page was a component page.

https://github.com/home-assistant/home-assistant.io/blob/99f69a0674fafcd1896c8f775767c198d5646ff2/plugins/configuration.rb#L5

**Comment by klaasnicolaas** [comment]
I think this has also passed on Discord #Documentation

**Comment by fabaff** [comment]
https://github.com/home-assistant/home-assistant.io/pull/6791

**Comment by WofWca** [comment]
Whoops, sorry.
