### ISSUE TITLE
Outdated page?

### ISSUE THREAD

**Issue by WofWca** [home-assistant/home-assistant.github.io#6905]
https://www.home-assistant.io/docs/configuration/customizing-devices/#changing-the-entity_id

> 1. Select the entity, either from or from the frontend, or by clicking  next to the entity in the dev-states menu
> 2. Click on the **cog in the right corner of the entity's dialog**

Can't see any cog.

![image](https://user-images.githubusercontent.com/39462442/47095807-2389f980-d258-11e8-9b4d-4fb80f85d258.png)

**Comment by nwesterhausen** [comment]
I don't believe this is outdated, I can use those steps to modify the Name and Entity ID of my sensors and lights.

Unsupported entities will not show the settings button to be able to change the Name or ID

**Comment by WofWca** [comment]
Ok, gonna close this for now then.
