### ISSUE TITLE
why we can't set a customize "DEVICE CLASS"

### ISSUE THREAD

**Issue by czdeee** [home-assistant/home-assistant.github.io#6956]
i have some sensor by hcho and pm25
and i have a "voice input device",i need ha response device class to analysis device unit and then speak the devices states

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration, feature requests and usage.
