### ISSUE TITLE
Adding a note about behaviour when asking for help on the help page

### ISSUE THREAD

**Issue by miawgogo** [home-assistant/home-assistant.github.io#7008]
So i am opening a issue here before making a PR as i feel like it needs discussion before doing any changes

A few people who help on the discord have raised a concern about the ammount of people joining the discord, and demanding help without doing any work themselves, as the people who raised concerned said "expecting to be spoon fed".

My question is, should we add a disclaimer before the communications channels saying 

```these resources are not stackoverflow, we expect you to read the docs & our suggestions and give full sentence responses when you can```

or something similar

**Comment by fabaff** [comment]
That's already covered in the "welcome-rules".

**Comment by frenck** [comment]
I agree with @fabaff...

**Comment by frenck** [comment]
The issue is running stale (an in our opinion, not an issue), closing it.
