### ISSUE TITLE
Discord Notify - Require OAuth2 Code Grant: Is this correct?

### ISSUE THREAD

**Issue by timmo001** [home-assistant/home-assistant.github.io#7051]
## Description

The Discord notify component docs say to `activate Require OAuth2 Code Grant`. Doing this causes the authorize step to fail with discord erroring with `Requires Grant`. If I don't activate this, The bot is authorized and can send messages in my server.

Is this an error in docs or is there an issue with the component itself not using OAuth2?

## Docs page

https://www.home-assistant.io/components/notify.discord

**Comment by fabaff** [comment]
> Is this an error in docs or is there an issue with the component itself not using OAuth2?

Hard to tell. It could be that there was a migration.
