### ISSUE TITLE
Credits Generator NPM High Severity Vulnerability 

### ISSUE THREAD

**Issue by uchagani** [home-assistant/home-assistant.github.io#7310]
I'm getting this when running `npm install` inside the `credits_generator` directory:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/1053584/47832136-23b2ea80-dd6a-11e8-8ef8-968b1547a5dd.png">

**Comment by fabaff** [comment]
This is another reason we want to move away from the current implementation.

**Comment by fabaff** [comment]
`update_credits.js` was moved to `hass-release`.
