### ISSUE TITLE
media_player.spotify `cache_path` unclear documentation

### ISSUE THREAD

**Issue by kmdm** [home-assistant/home-assistant.github.io#7330]
The `cache_path` description on the [media_player.spotify](https://www.home-assistant.io/components/media_player.spotify/) documentation is not clear. 

It says both "Path to the cache authentication token" and "defaults to configuration directory". 

Yet it appears to expect a path to a *file* and not a directory as the documentation reads.

**Comment by frenck** [comment]
Code: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/spotify.py#L40

So you are correct.

**Comment by frenck** [comment]
This is addressed by @nwesterhausen in #7598 👍
