### ISSUE TITLE
The water_heater documentation about away mode is not correct

### ISSUE THREAD

**Issue by kennedyshead** [home-assistant/home-assistant.github.io#7368]
https://www.home-assistant.io/components/water_heater/#water-heater-control-services

It shoud not be `turn_away_mode_on` / `turn_away_mode_off` but rather `set_away_mode`

**Comment by klaasnicolaas** [comment]
If this has to be adjusted, the [python code](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/water_heater/__init__.pyt) must also be looked at, because I see functions with: `turn_away_mode_on` / `turn_away_mode_off`.

So not only the documentation should then be adjusted.

**Comment by nwesterhausen** [comment]
We may need someone more familiar with how the components are supposed to work, but when I read through the water heater __init__ some things stand out to me:

The only mentions that match turn_away_mode_off/on are functions which get called by a handler for the "away_mode" attribute [here](https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/water_heater/__init__.py#L240)

It also has the exposed service for away mode being "set_away_mode" with it wanting an entity id and a boolean for away mode on/off [here](https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/water_heater/__init__.py#L63)

I will go ahead and do a PR to change the documentation. If I'm wrong at understanding the python, we can just not accept the PR.

**Comment by frenck** [comment]
PR's have been merged. Crisis diverted 😆
