### ISSUE TITLE
wrong triger

### ISSUE THREAD

**Issue by omegawang** [home-assistant/home-assistant.github.io#7374]
I used the many kind of xiaomi,aqara wireless switches, they have something wrong: single click for one time. but the Home assistant will get 2 single and 2 double clicks sign. 
what wrong with it?

**Comment by klaasnicolaas** [comment]
I think you can better place this issue [here](https://github.com/home-assistant/home-assistant), this repo represented the documentation of HA.

**Comment by frenck** [comment]
Yep, @omegawang... @klaasnicolaas is correct, please file an issue with the Home Assistant project itself. This is the project documentation repository.
