### ISSUE TITLE
Replace Google Analytics by Matomo or other privacy friendly software

### ISSUE THREAD

**Issue by alexara** [home-assistant/home-assistant.github.io#7378]
On your website (https://www.home-assistant.io/) you describe yourself with the following sentence:

> Open source home automation that puts local control and **privacy first**. 

and concurrently you use Google Analytics, which obviously contradicts each other.

Would you therefore mind to replace it by Matomo or similar?

**Edit:** Not to mention graph.facebook.com ;-)

**Comment by arsaboo** [comment]
That is only the website traffic and is not embedded in the HA code.

**Comment by fabaff** [comment]
Well, it's would be nice to not depend on third-party service providers to improve Home Assistant but for now we have to because there are no resources to maintain our own infrastructure for Git, web hosting, CI, website stats, etc.
