### ISSUE TITLE
Hassbian install service fails

### ISSUE THREAD

**Issue by linus-dev** [home-assistant/home-assistant.github.io#7443]
Hi

When I try to install Hassbian on my Pi3 the service fails about 30 seconds after boot.
Running `sudo systemctl` show me: 
`● home-assistant@homeassistant.service                                                         loaded    failed failed    Home Assistant for homeassistant`

When I run `sudo systemctl` as soon as I logged in it says `active running` instead of `failed failed`. But after 30 seconds it goes red.

Manually starting the service does not work either. 
Ruinning v.1.5.0 Autumn bump. 

Do you have any clue what can cause this?

Thanks.

**Comment by pvizeli** [comment]
Please asking the right repository
