### ISSUE TITLE
Home assistant authentication

### ISSUE THREAD

**Issue by RobertVilaplana** [home-assistant/home-assistant.github.io#7484]
Hello,

I'm trying start my home assistan since initial options and I have problems when acces since all computers. 

![captura](https://user-images.githubusercontent.com/44929390/48397994-d9454c80-e71f-11e8-93b9-0cbba02f3449.PNG)

Always that I try acces the "login attempt failed" message appear.

I have only a one username and password

Log image

![captura](https://user-images.githubusercontent.com/44929390/48398392-f595b900-e720-11e8-930f-ce5b80d3d52d.PNG)

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
