### ISSUE TITLE
packages documentation broken link

### ISSUE THREAD

**Issue by DeKemp** [home-assistant/home-assistant.github.io#7550]
Link at the bottom of this page is broken https://www.home-assistant.io/docs/configuration/packages/

It links to this url:
https://www.home-assistant.io/docs/configuration/packages/docs/configuration/customizing-devices/

**Comment by nwesterhausen** [comment]
It should link to [customizing entities](https://www.home-assistant.io/docs/configuration/customizing-devices/). I'll fix with a PR
