### ISSUE TITLE
Vera Component Request

### ISSUE THREAD

**Issue by Raynman77** [home-assistant/home-assistant.github.io#7613]
The Vera Component discovery and device import does not include a way to exclude scenes. This is a problem because Vera will assign scenes with the same id's as devices. Therefore, if excluding a device the way it is implemented now, the device that has the same id as a scene will be excluded from the import.

`vera:
  vera_controller_url: http://192.168.1.161:3480/
  # Optional to exclude devices - this is a list of vera device ids
  exclude: [ 13, 14, 16, 20, 23, 72, 73, 74, 75, 76, 77, 78, 88, 89, 99]
  # Optional to import switches as lights - this is a list of vera device ids
  lights: [15, 17, 19, 21, 22, 24, 26, 43, 64, 70, 87]`

**Comment by fabaff** [comment]
This is the issue tracker. Please use the forum for [feature requests](https://community.home-assistant.io/c/feature-requests) as stated in the PR template. Thanks
