### ISSUE TITLE
Include non-API warning for 17track

### ISSUE THREAD

**Issue by alexbarcelo** [home-assistant/home-assistant.github.io#7655]
Most "Postal Service sensors" have a warning including something along:

> The FedEx sensor logs into the FedEx Delivery Manager website to scrape package data. It does not use an API. Use at your own risk. 

PR #7303 included the documentation for the 17track component, which uses [py17track](https://pypi.org/project/py17track/), which specificies:

> Since this is uses an unofficial API, there's no guarantee that 17track.net will provide every field for every package, all the time. Additionally, this API may stop working at any moment.

So, should we include the same generic warning box (as in the other Postal Service sensors)?

LightningEdit: Well, it is a bit different, 17track _is_ using an API, just an unofficial one. But nevertheless, the question remains, should we include a warning box explaining that an unofficial API is being used?

**Comment by nwesterhausen** [comment]
Hive, Tado, and Toon all mention that they use an unofficial API but do not have a warning box. To the end user, is it more beneficial to have the warning calling it out? If so, we should also update the other component documentation that does that. If not, then we just need to mention that it uses an unofficial API. The FedEx component is not using an API at all, literally scraping the web page. Maybe this is the warning cutoff?

I think at the very least we should mention that this component uses an unofficial API (I didn't see that the documentation included something to that effect in #7303)

**Comment by alexbarcelo** [comment]
@bachya what do you think? Mentioning the unofficial API should be there IMHO. I don't know if a warning box is overkill.

**Comment by bachya** [comment]
I see a big difference between a library that scrapes HTML – and is therefore _very_ likely to break – and a private API that has been reverse engineered. A large number of Home Assistant's integrations rely on private APIs that have been stable for a long time; I question whether a "beware" message actually provides value or if it unnecessarily scares, communicates that the integration is inferior, etc.

I suppose I don't have a real solid opinion and am open. 😆One additional thought: this should probably be addressed in conjunction with the [Integration Quality Scale](https://deploy-preview-92--developers-home-assistant.netlify.com/docs/en/next/integration_quality_scale_index.html).

**Comment by fabaff** [comment]
Most users don't care if it's an official API, an unofficial API or scraping the website. All integrations which are depending on a third-party service can break at any time but then we try to fix them.

I think that the IQS shouldn't care about what kind of technique is used to get the data because that's not a quality characteristic. I'm more in favor of adding a proper attribution.

**Comment by alexbarcelo** [comment]
Ok, so do you guys think if the warning box should be *removed* the from the other components?

The issue I have is that, right now, the documentation feels not consistent amongst components. But maybe it's only my feelings.

**Comment by frenck** [comment]
I think it is fine to remove them in most cases. But adding and/or leaving them harms no one as well.
