### ISSUE TITLE
Missing important Homematic IP component

### ISSUE THREAD

**Issue by Obicom** [home-assistant/home-assistant.github.io#7728]
The flush-mounted dimmers are not supported from Homematic IP integration. This component is often used and should be integrated ASAP. (HmIT-FDT, HmIP-BDT)

**Comment by MartinHjelmare** [comment]
You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum. Thanks!
