### ISSUE TITLE
xiaomi Gateway light rgb_color parameter cannot be used in if judgment

### ISSUE THREAD

**Issue by laynexx** [home-assistant/home-assistant.github.io#7732]
**example**
`  - service: light.turn_on
    entity_id: light.gateway_light_xxxx
    data_template:
      brightness: 100
      rgb_color: >
        {% if  now().hour >= 7 and now().hour < 10 %}
        [255,0,0]
        {% endif %}`
**does not works**
`  - service: light.turn_on
    entity_id: light.gateway_light_xxxx
    data_template:
      brightness: 10
      color_name: >
        {% if  now().hour >= 7 and now().hour < 10 %}
        red
        {% endif %}`
**works**

**and without if**
` - service: light.turn_on
    entity_id: light.gateway_light_xxxx
    data_template:
      brightness: 100
      rgb_color: [255,0,0] `
**works**

**Comment by nwesterhausen** [comment]
This repository is for the documentation, and this issue looks to be related to the component not responding to the input from a template (i.e. not documentation). You can open this issue in [the main Home Assistant repo](https://github.com/home-assistant/home-assistant/issues)

**Comment by laynexx** [comment]
ok thank u
