### ISSUE TITLE
Edit HA documention

### ISSUE THREAD

**Issue by KickingAss2024** [home-assistant/home-assistant.github.io#7765]
Can we change the HA file here

<img width="346" alt="capture" src="https://user-images.githubusercontent.com/14849762/49635950-efa7a500-fa4c-11e8-90ea-1a4ed9cf8220.PNG">

to this 
{
 "message" : "hello world"
}

thanks

**Comment by ludeeus** [comment]
Every page on our website have a button you can click to suggest changes :)
![image](https://user-images.githubusercontent.com/15093472/49644999-9a52a000-fa1a-11e8-8a0b-df249f0dd64d.png)

**Comment by nwesterhausen** [comment]
@adtwomey The only difference between what you suggested and what is there is spacing. How does spacing out the JSON improve the documentation?

Also, you didn't mention what page of the documentation this is for, which would be helpful.

**Comment by fabaff** [comment]
I updated the formatting but the suggested change doesn't add value as it's valid JSON.
