### ISSUE TITLE
system_log.markdown image not found

### ISSUE THREAD

**Issue by McCroden** [home-assistant/home-assistant.github.io#7786]
There is a broken image link in the [./source/_components/system_log.markdown](https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/system_log.markdown) file.

Actual markdown text:  
`<img src='/images/components/system_log/system_log_entry.png' />`

It resolves to:
[https://www.home-assistant.io/images/components/system_log/system_log_entry.png](https://www.home-assistant.io/images/components/system_log/system_log_entry.png)

I don't know what this image looked like nor do I know how to try to find the images to fix this myself.

**Comment by nwesterhausen** [comment]
I searched the repository for the image linked in the markdown for the system_log component and could not find any reference to the image (being added to the repo or deleted). When I searched `system_log` I did find the picture from the blog 2017-11-0.58 but it does not seem to match the text description of the system log in the markdown.

Here is how I searched: `git log --summary | Select-String system_log_entry`  and `git log --summary | Select-String system_log` to find the blog post.

The commit that added the image is #4549 but it doesn't include the image. I could be looking for this all wrong but it seems like the image just didn't get added.
