### ISSUE TITLE
intent_script: request for detailed documentation

### ISSUE THREAD

**Issue by escoand** [home-assistant/home-assistant.github.io#7806]
I started using Snips.AI hassio addon and wondered how it is working out-of-the box with my hass installation.
I was able to say "turn the light off" but "turn the light on" doesn't work. After some deeper digging I found the build in intents HassTurnOn and HassTurnOff which aren't mentioned at all in the docs.

So, I would request a much more detailed documentation about the build-in functionality and how to work with. How is the mapping to existing entities done? How is everything working together?

**Comment by klaasnicolaas** [comment]
I still have a [PR open](https://github.com/home-assistant/home-assistant.io/pull/7154) about the intent_script, only ended up in a pile of all the other PRs.

**Comment by escoand** [comment]
@klaasnicolaas any update?
