### ISSUE TITLE
MyChevy Component Document update needed

### ISSUE THREAD

**Issue by tommyjlong** [home-assistant/home-assistant.github.io#7827]
As of 0.84, MyChevy component no longer requires Selenium, yet the 
current documentation says Selenium is needed.

This component works with my Chevy Volt (with a V), so may want to add it
to the list of supported cars to the documentation as well.

**Comment by nwesterhausen** [comment]
I created a pull request to make your suggested changes to the documentation.

If you ever wanted to, anyone is able to create a pull request with documentation changes, using the "Edit on GitHub" button at the top of the documentation page.
