### ISSUE TITLE
Request: Support of Xiaomi PHILIPS Zhirui 9290019202 Smart Bedside Lamp

### ISSUE THREAD

**Issue by AsWaM** [home-assistant/home-assistant.github.io#7866]
Hello,

Would it be possible to add support for the bedside lamp?

I could not get the token yet, but i will try the current support.

http://www.xiaomimagazine.com/xiaomi-philips-zhirui-smart-bedside-lamp-review/

**Comment by MartinHjelmare** [comment]
You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum. Thanks!
