### ISSUE TITLE
Nest Away Mode Documentation

### ISSUE THREAD

**Issue by kjacksonmusic** [home-assistant/home-assistant.github.io#7953]
The documentation states the away mode is set with "away" or "home". 

If you try to call the service with these settings it fails. Changing this to "true" or "false" resolves the issue and future confusion.

**Comment by nwesterhausen** [comment]
I tested this on my Home Assistant (version 0.84.6) and was successfully in calling `nest.set_away_mode` with `{"away_mode":"home"}` and `{"away_mode":"away"}` and actually failed when calling it with `{"away_mode":"false"}` and `{"away_mode":"true"}`.

Can you provide more details on what you're doing that isn't working?

**Comment by kjacksonmusic** [comment]
Thanks for trying this out. 
I was calling the service via the frontend, while troubleshooting a automation that I set to call it as well. 
I just re tried this and got the same message. 
[Here are photos](https://photos.app.goo.gl/5mFL9u2DJpCc7iKG7) showing the error message as well as the exact method I am using to execute this. 

I am running Hassio 0.84.6 my thermostat is a Nest E. 

Thanks

**Comment by nwesterhausen** [comment]
Thanks for the additional information. I think I see the issue: there is a separate service named `nest.set_away_mode` that I was calling. In your pictures, you are calling `climate.set_away_mode` which is explained both beneath it on the frontend, where the default is 'false' and [here](https://www.home-assistant.io/components/climate/) on the documentation site (slightly different services than [nest](https://www.home-assistant.io/components/nest/))

**Comment by kjacksonmusic** [comment]
Yup. My mistake thanks for the clarification!
