### ISSUE TITLE
`rake preview` not updating from markdown

### ISSUE THREAD

**Issue by farmio** [home-assistant/home-assistant.github.io#7966]
I am trying to work on some documentation on my local device (Macbook), but the live preview isn't updating my changes from the .markdown files.
I am modifying `source/_components/light.knx.markdown`.
I am sure I have saved the changes and have also cleared my browser cache (Safari 12.0.2).

I have installed everything according to https://developers.home-assistant.io/docs/en/documentation_index.html 
```
brew update
brew install ruby
sudo gem install bundler

cd home-assistant.io

bundle
bundle exec rake generate
bundle exec rake preview
```

When I do `bundle exec rake generate` and `bundle exec rake preview` a second time, my updates are shown in the browser - but this takes over 15 minutes.

**Comment by fabaff** [comment]
You could try to limited the build to the changed page with `isolate[filename-of-blogpost-or-component]`.

**Comment by farmio** [comment]
Thank you! This worked after i found out that i have to escape the brackets when using zsh 
`bundle exec rake isolate\[light.knx.markdown\]`
