### ISSUE TITLE
Unknown min_max sensor value

### ISSUE THREAD

**Issue by RonJ103** [home-assistant/home-assistant.github.io#8006]
Hopefully this is in the right place.  I created this forum post in the home assistant community: https://community.home-assistant.io/t/min-max-platform-mean-showing-unknown/84407

My min_max sesnor is displaying "unknown" with a unit of "err".  It seems like it is this issue from the documentation:
```
Sensors with an unknown state will be ignored in the calculation. If the unit of measurement of the sensors differs, the min_max sensor will go to an error state where the value is UNKNOWN and unit of measurement is ERR.
```
However, when I check the individual sensors, they both have the same units (degrees F)

**Comment by nwesterhausen** [comment]
I replied to you on the forums. I cannot get your issue to duplicate. With more information maybe we can figure out what's going on.

I looked at the sensor and it should put an error in the log saying which sensor it is having a problem with. What is in your log?

**Comment by RonJ103** [comment]
Thank you for the reply.  It is working at the moment.  I suspect it had to do with one of the sensors (Xiaomi) becoming unavailable.  I am not 100% sure.  I'll report back with more details if I see it again.

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
