### ISSUE TITLE
History Graph not refesh

### ISSUE THREAD

**Issue by alex206cc** [home-assistant/home-assistant.github.io#8045]
hi,
in lovelance home assistant 0.84.6 i configuring the refresh but not function:

  - title: Internet performance
    refresh_interval: 20
    hours_to_show: 6
    entities:
      - sensor.internet_upload
      - sensor.internet_download
    type: history-graph

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new or use the [forum](https://community.home-assistant.io/) for questions about installation, setup, configuration and usage.
