### ISSUE TITLE
Quotes on binary_sensor.command_line

### ISSUE THREAD

**Issue by Konstigt** [home-assistant/home-assistant.github.io#8069]
In the examples and guide text regarding payload_on/off on https://www.home-assistant.io/components/binary_sensor.command_line/ there are no quotes, single quotes, double quotes + a note in the bottom that says that you should use single quotes.

Confusing yes?

**Comment by emontnemery** [comment]
Then please submit a PR to improve the examples and guide text. This can be done by just clicking the "edit this page on GitHub" link.

**Comment by Konstigt** [comment]
Sorry, can't. Because I don't know what is the correct one of these three options. That's why I visited the page in the first place :)

**Comment by emontnemery** [comment]
Aha, I didn't realize it was a question!

yaml supports both no quotes, single quotes and double quotes for strings.

With double quotes, escaping is possible, maybe this is why there is a suggestion to use single quotes to not have unintended escaping of commands.

@bphermansson you added the note about using single quotes, can you comment?

**Comment by bphermansson** [comment]
My experience is that single quotes is what's working with system commands.
