### ISSUE TITLE
Lovelace default themostat is unusable.

### ISSUE THREAD

**Issue by sblantipodi** [home-assistant/home-assistant.github.io#8077]
As title.
I'm using celsius degrees and in celsius half degree is important.

1) The new lovelace UI does not let me choose 20.5 degree but only 20 or 21.

2) I cannot visually set the away mode.

3) New UI does not have an history of temp and furnance use like the old one.
https://postimg.cc/hhY45kBP

I think that this "component" in this state is a huge regression over the older one.
Please remove it until it is in a usable state.

**Comment by Vasiley** [comment]
This is the wrong repo this is for doc changes and you erased the template of relevant information

**Comment by sblantipodi** [comment]
sorry
