### ISSUE TITLE
Template Developer Tool on / off don't need to be quoted

### ISSUE THREAD

**Issue by JustinDwy** [home-assistant/home-assistant.github.io#8092]
The template developer tool will work fine with unwrapped on / off, but the same yaml used in configuration.yaml will work differently due to needed 'on', etc.

**Comment by frenck** [comment]
Thanks for letting us know, although, I'm unsure what you are suggestion right now...?

**Comment by JustinDwy** [comment]
The built in Templating Tool accepts yaml with on / off not wrapped in quotes. But then a user can paste that "working" yaml into their config file and it will not work the same way. But it won't throw an error either. The user will struggle to find out why their thing doesn't work when it works in the Template Tool. 

Either unwrapped on / off needs to throw an error, or the Templating Tool needs to render unwrapped on / off the same way that it'll be rendered by HA when run.

Does that clarify?

**Comment by JustinDwy** [comment]
Nevermind, must have been fixed in a recent version. 

```
{% if states('binary_sensor.workday_today') == on %} false
{% else %} true
{% endif %}

{% if states('binary_sensor.workday_today') == "on" %} false
{% else %} true
{% endif %}
```

That was returning the same result in the Templating Tool, but different results when ran. Now it seems to be working properly in Templating Tool too.

Closed.
