### ISSUE TITLE
Automation editor with "Automation old" error config

### ISSUE THREAD

**Issue by marcogazzola** [home-assistant/home-assistant.github.io#8110]
In this [commit](https://github.com/home-assistant/home-assistant.io/commit/f6b1e6aa8c519b47fb15cce55928cb8ef1118f6d#diff-7e0a13a3a96b84134f13c39a07a53a05) there is an error.

the correct config should be:
```
automation: !include_dir_merge_list automations/
automation old: !include automations.yaml
```

**Comment by point-4ward** [comment]
Nope, the configuration as stated in the commit is correct.

To use the automation editor you must use

```
automation: !include automations.yaml
```

If you want to add other automations to the system in other files you must add them separately, and can merge them in any of the available formats such as 

```
automation 2: !include my_other_automations.yaml
```

The suggested tag of 'old' in the docs, with the suggested merge method is to make it easier for people to understand, but it is definitely correct.

**Comment by frenck** [comment]
Yep, the documentation is correct.
