### ISSUE TITLE
OpenUV free plan change

### ISSUE THREAD

**Issue by Dudu67** [home-assistant/home-assistant.github.io#8123]
The free OpenUV plan limitation will change on the 1. Feb 2019.
The free plan will go from 500 free request per day to 50 request per day.
The actual default parameter is set to 1800s (that's 48 request a day) that meen no more buffer as intendeed.
It will be maybe good to reduce the number of request per day to limit the risk of over request.

proposition:
1800 -> 2400s

Olivier

**Comment by frenck** [comment]
Fixed in #8124
