### ISSUE TITLE
WV-1716 supported 

### ISSUE THREAD

**Issue by bossie78** [home-assistant/home-assistant.github.io#8188]
Is the oldest version WV-1716 supported in Home Assistant. It is a bit unclear. In the first part of the text the version is included (tested on) WV-1716, but a bit further down the version is not mentioned. 

So is the version included? If not would it be possible to support this version? I am very new to HA and a noob, so thanks for your help! :-)

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
