### ISSUE TITLE
README : Razberry board - config.txt editable from Linux systems

### ISSUE THREAD

**Issue by kouinkouin** [home-assistant/home-assistant.github.io#8200]
Hi,

https://github.com/home-assistant/home-assistant.io/blob/current/source/hassio/zwave.markdown#-linkable_title-razberry-board-

Just a note to say the config.txt is editable from a Linux system.
You have to mount the partition `/dev/mmcblk0p1`, from the gnome-disk-utility, or manually.
It's a partition FAT, and for me, the edition doesn't damage the partition or the boot.

I can of course do a PR for edition of the README. I just want to know if it's relevant to notice it.

**Comment by nwesterhausen** [comment]
To me that page is trying to say you can't edit config.txt from the system running from the SD card, and perhaps we should reword that sentence to be more specific so it can't be read as though you can't edit the config.txt from a Linux system.

**Comment by DubhAd** [comment]
PR submitted
