### ISSUE TITLE
Alarm ever activate arm_away never arm_home

### ISSUE THREAD

**Issue by Obicom** [home-assistant/home-assistant.github.io#8202]
**Home Assistant release with the issue:** 0.84.6/0.85.0/0.85.1

**Last working Home Assistant release (if known)**: unknown

**Operating environment (Hass.io/Docker/Windows/etc.):** Hass.io

Component/platform:
https://www.home-assistant.io/components/alarm_control_panel.manual_mqtt/
https://www.home-assistant.io/components/alarm_control_panel.manual/
https://www.home-assistant.io/components/alarm_control_panel.homematicip_cloud/

**Description of problem:**
I have the issue that the alarmcontrol panel activates everytime arm_way equal if I switch arm_home or arm_away. If you switch on arm_home it needs some second (pending) and comes back with swichting both alarmpanel actors (away & home) to "armed_away". in HmIP App it shows every time "Vollschutz aktiv". I checked this with some other German hassio users and they confirmed this issue. 

@sander76: Is this something for you would you could check?

In addition the Alarm Panel shows the wrong status. Real status from HmIP is always "Armed away" but Alarm Panel shows (wrong) status "Home" when I tried to activate "Arme Home".

P.S: coreGreenbaret confirms: That's in hassio. The api supports both methods.

**Comment by klaasnicolaas** [comment]
Think that it is better to put the issue [here](https://github.com/home-assistant/home-assistant/issues). This repository is about the documentation of HA not HA itself
