### ISSUE TITLE
Refactor jewish_calendar to work as binary_sensor and sensor.

### ISSUE THREAD

**Issue by arigilder** [home-assistant/home-assistant.github.io#8238]
Based on comment on https://github.com/home-assistant/home-assistant.io/pull/7838 and https://github.com/home-assistant/home-assistant/pull/19278 the issur_melacha_in_effect sensor should be a binary_sensor platform. 
@tsvi

**Comment by frenck** [comment]
@arigilder I do not get what issue you are trying to raise?
Is the documentation incorrect?

**Comment by tsvi** [comment]
This issue should be moved to the home-assistant repository.

**Comment by frenck** [comment]
check.
/move home-assistant/home-assistant
