### ISSUE TITLE
Sense Duplication ?

### ISSUE THREAD

**Issue by dgomes** [home-assistant/home-assistant.github.io#8248]
I'm unsure if this is a duplication or not. @kbickar since you edited one of them, can you check ?

https://www.home-assistant.io/components/sense/
https://www.home-assistant.io/components/sensor.sense/

**Comment by frenck** [comment]
The second one is the right one:

https://www.home-assistant.io/components/sensor.sense/

**Comment by kbickar** [comment]
The second one should redirect to the first one.  The sensor platform "sense" was replaced by the component "sense" that creates sensors and binary sensors
