### ISSUE TITLE
GeoFency documentation is incompete

### ISSUE THREAD

**Issue by brianharwell** [home-assistant/home-assistant.github.io#8362]
I followed the instructions in the [docs](https://www.home-assistant.io/components/geofency/) and the part that changes was...

> To configure Geofency, you must set it up via the integrations panel in the configuration screen. You must then configure the iOS app (via the Webhook feature) to send a POST request to your Home Assistant server at the webhook URL provided by the integration during setup. Use the default POST format. Make sure to enable the ‘Update Geo-Position’ functionality for mobile beacons.

I did that, and restarted HA, and configured the iPhone app. Posting from the app works but in HA logs I see...

Received message for unregistered webhook 31212bfd284124b6ac865478bc68aaf1c6d74bd6f1f43b85003db5820

**Comment by nwesterhausen** [comment]
You might get better traction troubleshooting your issue at the [forums](https://community.home-assistant.io/) or [chat](https://discord.gg/c5DvZ4e). This repository is for the documentation, and you mention the documentation is incomplete.. but your statement is about an error in Home Assistant without clear reasons to suggest the documentation is wrong.

I googled for "home assistant geofency webhook" and found someone [posted to the forums 19 hours ago](https://community.home-assistant.io/t/geofency-webhook-not-working/95895) with a similar issue to yours -- might be a good place to start. It might be an error with the component itself and not the documentation.

**Comment by brianharwell** [comment]
Yes that is my post. I am suggesting the documentation is incomplete because there seems to be a step missing from the set up. I thought by posting an issue here the author of the change would hopefully fill in the missing step(s). If I find the solution I will submit a PR to amend the docs but until then I am at an impass.

In addition, the link to the `geofency.py` file on [this](https://www.home-assistant.io/components/device_tracker.geofency/) page points to a page that does not exist. The correct source code link is [here](https://www.home-assistant.io/components/device_tracker.geofency/)

**Comment by nwesterhausen** [comment]
@rohankapoorcom authored the recent changes to the docs and to the component in Home Assistant. Hopefully he can help straighten everything out

**Comment by rohankapoorcom** [comment]
Thanks for the tag. There's a small bug where things don't work if you don't have the `geofency:` section in configuration.yaml (which shouldn't be needed).

https://github.com/home-assistant/home-assistant/pull/20631 fixes this and should be merged soon.

**Comment by brianharwell** [comment]
@rohankapoorcom I have that entry in my configuration.yaml.

**Comment by rohankapoorcom** [comment]
Do you have any mobile beacons defined? I think the same bug may require at least one mobile beacon to finish setup. If you look at your logs, do you see the geofency component loading successfully?

**Comment by brianharwell** [comment]
I do not have any mobile beacons.

I do not see anything in my `home-assistant.log` matching `geofency`. I have logger configuration set to `warn`. Should I set it to `info` and restart HA?

Or can I see if geofency loaded another way?

**Comment by rohankapoorcom** [comment]
If you go to the info page (part of the sidebar, `/dev-info`), you should see a link that has a list of loaded components.

**Comment by brianharwell** [comment]
Got it. Thanks. Yes, geofency is loaded. As well as webhook.

**Comment by brianharwell** [comment]
So to fix the issue I remove geofency from my `configuration.yaml`?

**Comment by brianharwell** [comment]
With 0.87.0 update, this still doesn't work.  See [comment](https://github.com/home-assistant/home-assistant/pull/20631#issuecomment-461428604)

@rohankapoorcom @balloob
