### ISSUE TITLE
Trusted network without authentification

### ISSUE THREAD

**Issue by dagobert** [home-assistant/home-assistant.github.io#8364]
I am happy that you added a required Login mechanism for HASS. It is also glad that you have a "trusted network" option. I am not sure what your plans are for authentication. I read the Documentation and there is a hint that you are planning to enhance it anyway.

I would propose the following change:

In a trusted network one does not need to do any action to see the WebUI. 
Right now one has to select the trusted network option in the WebUI and select a user. Since there is no password verification this step is unnecessary and prevents the easy use of the WebUI in a trusted environment such as using it on central tablet for everyone's convenience.
This should be until rights management is implemented. After that there should be an "anonymous" user without login in a trusted network. It would be the default user that has rights to all necessary features of HASS to live in the home. If one wants to elevate ones privileges there should be a login button such it is on any other Webpage in the internet (amazon, ebay...)

**Comment by klaasnicolaas** [comment]
-> https://github.com/home-assistant/home-assistant

**Comment by dagobert** [comment]
Sorry completely missed that I should use the forum.
