### ISSUE TITLE
Add instructions in FAQ for potential prerequisites for manual pip install

### ISSUE THREAD

**Issue by dlo** [home-assistant/home-assistant.github.io#8372]
Hi all! I just wanted to add something small to the FAQ. 

When running the pip installation command, I got a missing header error for <Python.h>. Being around the block a few times, I knew that this was because my RPi install was missing the python3-dev package. After installing this package via apt-get, the pip installation went smoothly. I'm just not sure how to add a FAQ entry so figured I'd post this here to get some direction. Thanks!

https://www.home-assistant.io/faq/#pip3-command-not-found

Prerequisite installation commands for my RPi B+:

```
sudo apt-get install python3-dev libffi-dev libssl-dev
```

**Comment by nwesterhausen** [comment]
All the FAQ sections are [here](https://github.com/home-assistant/home-assistant.io/tree/current/source/_faq), looks like they all get combined into the [documentation page](https://www.home-assistant.io/faq)

**Comment by dlo** [comment]
@nwesterhausen Thanks! I'll submit a PR.
