### ISSUE TITLE
Embedded platform source links don't work

### ISSUE THREAD

**Issue by rohankapoorcom** [home-assistant/home-assistant.github.io#8374]
Ever since we started embedding components into platforms, a bunch of the "source" links in the documentation started 404'ing.

https://www.home-assistant.io/components/light.hue/ source link points to https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/light/hue.py

The file that should be pointed to is now here: https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/hue/light.py

This appears to be generated here (thanks for the pointer @Ludeeus) https://github.com/home-assistant/home-assistant.io/blob/current/source/_includes/asides/component_navigation.html#L61

We need to improve this such that it works for both embedded and non embedded platforms.

**Comment by balloob** [comment]
I think that the one true solution is to migrate every Python platform file to the new embedded format.

**Comment by rohankapoorcom** [comment]
Then we'll need to adjust the links for all component/platform sources to point to the correct place. Definitely easier to maintain just one approach moving forward.

**Comment by rohankapoorcom** [comment]
I pushed up a PR (https://github.com/home-assistant/home-assistant.io/pull/8379) with the changes needed to make this work (once https://github.com/home-assistant/home-assistant/pull/20677 is merged).
