### ISSUE TITLE
Lovelace: Cannot delete card on mobile

### ISSUE THREAD

**Issue by Nebukadneza** [home-assistant/home-assistant.github.io#8497]
When using a mobile (mobile simulation in firefox, iOS 12.1.3), cards cannot be deleted in lovlace »configure ui« mode. It works fine on desktop browsers / in desktop mode, where a javascript alert is shown for confirmation. This alert is missing alltogether on mobile.

I couldn’t find a open bug for this, please excuse me if i’ve overlooked one.

Thanks for the great project, and best~,
-Dario

**Comment by klaasnicolaas** [comment]
This Repo is for the documentation of Home Assistant, you must look here: https://github.com/home-assistant/home-assistant

**Comment by Nebukadneza** [comment]
Sorry! Indeed, i had both tabs open, and caught the wrong one :/. Sorry for the additional work and inconvenience!
