### ISSUE TITLE
Use data from TOSDR to complete component documentation

### ISSUE THREAD

**Issue by arthurlutz** [home-assistant/home-assistant.github.io#8500]
Follow up of #6402 

It would be awesome to use data and grading from https://tosdr.org/ to add context to help users select their components and the services they are associated with. 

I think the home page "pitch" "Open source home automation that puts local control and **privacy first**. " would be benefit from this. 

TOSDR has some easy to read categories A/B/C/D with colors associated.

For example, using the services features on the components page right now we could link to : 

* https://tosdr.org/#google 
* https://tosdr.org/#amazon
* https://tosdr.org/#ifttt

**Comment by frenck** [comment]
I like the idea, but I fail to see how that would relate to #6402.

The problem with linking to such a source is the endorsement.
We linking to that particular website, is kinda telling our users that that website is right, which is something we cannot assure. Since this has to do with legal, I would reframe from doing this.

Secondly, the first two examples linked (Google & Amazon) are already incorrect. Google and Amazon have different sets of TOS and Privacy Statement's, depending on the service you are using. This is something the suggested website fails to take into account.

**Comment by arthurlutz** [comment]
Hi @frenck thanks for taking a look at this. 

If legal is involved, is there a way to phrase or present the information in a way that says "this is not an endorsement, the linked information is a collaborative effort to summarize terms of service, it might be inaccurate". 

The relation with #6402 is that to empower the home assistant users to choose components that put their privacy first, I think choosing cloud services that respect their privacy it a requirement. See the topics TOSDR takes a look at https://tosdr.org/topics.html 

For the Amazon and Google multiple terms of services, I'll report a bug to the project to see if something can be done about that.

**Comment by frenck** [comment]
> "this is not an endorsement, the linked information is a collaborative effort to summarize terms of service, it might be inaccurate".

IMHO a reason not to do it. Everybody has to agree to TOS and stuff when they use/buy/signup for a service. I don't believe HA should take part in that. (But that is my opinion).

From a maintainability point of view, having the score from "TOSDR" in our page, is not really wished for. Who is maintaining and updating those?

**Comment by arthurlutz** [comment]
Indeed, a better technical solution would be to have a bit of javascript (or a simple svg link like badges) that gets and displays the classification from the original data source. I'm checking with the project if such ease of integration can be done.

> Everybody has to agree to TOS and stuff when they use/buy/signup for a service.

Sure, but very rare are the people who spend time reading them. If home-assistant stands for **privacy first**, then I think home-assistant should take part in advising it's users on what components they activate and what that entails. 

> Who is maintaining and updating those ?

https://tosdr.org/about.html explains who is currently participating in the project.

**Comment by balloob** [comment]
https://github.com/home-assistant/home-assistant.io/pull/8498#issuecomment-462849329
