### ISSUE TITLE
How to edit the link on the side bar? Github link is broken

### ISSUE THREAD

**Issue by GuyKh** [home-assistant/home-assistant.github.io#8617]
In [notify.telegram](https://www.home-assistant.io/components/notify.telegram/) the github link is broken.
Tried to tackle this myself, but under the [notify.telegram.markdown](https://github.com/home-assistant/home-assistant.io/blob/next/source/_components/notify.telegram.markdown) - there's no github link whatsoever.

Thanks

**Comment by klaasnicolaas** [comment]
See also #8619
