### ISSUE TITLE
Script Editor not creating friendly entity id

### ISSUE THREAD

**Issue by DoctorIOT** [home-assistant/home-assistant.github.io#8668]
When creating a script using the Script Editor the script is saved with an alias as entered in the name field along with a numeric entity id. This entity id is not displayed or editable from the script editor. The result is that the script is hard to choose from elsewhere unless to know the random numeric id.

Modify the script editor to allow editing of the entity id and default it to a sanitized name.

**Comment by klaasnicolaas** [comment]
https://github.com/home-assistant/home-assistant-polymer

**Comment by fabaff** [comment]
This is the issue tracker for the documentation.

Please use the forum for [feature requests](https://community.home-assistant.io/c/feature-requests). Thanks
