### ISSUE TITLE
FitBit sensor unable to configure

### ISSUE THREAD

**Issue by CountParadox** [home-assistant/home-assistant.github.io#8678]
Hello, 

I and a few other users ([`see`](https://community.home-assistant.io/t/fitbit-unable-to-authorize/80470/4) are having difficulty setting up the fitbit sensor component, the issue occurs when authorizing our custom application to fitbit, 

When it comes time to
```
Please authorize Fitbit by visiting 
https://domain.com:port/api/fitbit
```

Checking the boxes, and clicking allow takes to a Home Assistant error page that says
```
500 Internal Server Error
Server got itself in trouble
```

I am unsure how to proceed from here in diagnosing the problem so I am opening this issue.

**Comment by klaasnicolaas** [comment]
This repo is for the documentation of Home Assistant, I think that you should be here: https://github.com/home-assistant/home-assistant
