### ISSUE TITLE
option to stop covers by re-triggering last up or down movement

### ISSUE THREAD

**Issue by increddibelly** [home-assistant/home-assistant.github.io#8687]
my rflink klik-aan-klik-uit cover switch do not respond to STOP commands. If I want to stop them halfway while going up, I have to press up once more, and that stops them.

**proposal:**
add option to cover component, 'resend_to_stop', default false. 
if this option is set to true, the stop script doesn't send a stop command, but resends the last sent command. It probably helps to cache the last sent command per cover switch.

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please use the forum for [feature requests](https://community.home-assistant.io/c/feature-requests). Thanks
