### ISSUE TITLE
SSH daemon has debug logging

### ISSUE THREAD

**Issue by robin13** [home-assistant/home-assistant.github.io#8689]
In the ssh daemon configuration, debug logging is enabled:

```
LogLevel DEBUG
```
This results in this line being output every time one connects:

```
debug1: permanently_set_uid: 0/0
```
And this in turn breaks backuppc from being able to connect to make a backup and other ssh based automations.

Is it possible to set LogLevel to INFO?

**Comment by fabaff** [comment]
This is the issue tracker for the Home Assistant Documentation. 

Please report Home Assistant issues at https://github.com/home-assistant/home-assistant/issues/new. It's hard to tell where that issue belongs as there are only generic information available.

Hassbian, Hass.io, Docker, default installation...

**Comment by robin13** [comment]
See: https://github.com/home-assistant/home-assistant/issues/21325
