### ISSUE TITLE
Clarify the config of the new people component

### ISSUE THREAD

**Issue by Joshfindit** [home-assistant/home-assistant.github.io#8714]
Request from an end-user: Could the documentation be updated to cover the following?

1. Where the `user_id` can be found? _Not just for the logged-in user, but for other users._
2. What the requirements are for the `id:`. Could it just be `1` and `2`? `alyssa` and `seth`?

**Comment by MartinHjelmare** [comment]
2. The requirement for `id` is that it's unique among persons. No person should have the same id as another person.

**Comment by MartinHjelmare** [comment]
1. `user_id` of users can be inspected in the users/manage users screen in the configuration panel.

**Comment by Joshfindit** [comment]
(Disregard 88a3b1d, it was against next. 7cba3dc targets current.)

**Comment by Joshfindit** [comment]
Merged. Closing issue. Cheers!
