### ISSUE TITLE
Component "Last Updated Release" Attribute

### ISSUE THREAD

**Issue by dougclarknc** [home-assistant/home-assistant.github.io#8762]
As a Hass User, I like to stay up to date with releases.
However, breaking changes are not infrequent and may be missed if skimming the release notes.
This leads to occasional config errors where Dev-Info panel simply states that some component did not load.
It would be nice to have an attribute on each components page in their right panel that details the last release this component was updated; similar to their "introduced in release:" attribute.
![image](https://user-images.githubusercontent.com/8637207/53510870-fadb0180-3a8c-11e9-9388-2557b443713f.png)
This would facilitate debugging after an update.

**Comment by fabaff** [comment]
I'm not sure where we should draw the line here. If we only increment the release number if there is a breaking change then will it lead to a wrong impression. There are integrations which are changed/improved/modified on a regular base. Technically they are updated.

In most cases the documentation should be up-to-date when a breaking change occurs and then the log entry is pointing one to the documentation.

The topic about integrating changelog entries per integration in the documentation is coming up from time to time but as long as we are not able to do it automatically it will not happen.

**Comment by awarecan** [comment]
Could be done via https://github.com/home-assistant/architecture/issues/179
