### ISSUE TITLE
Uncaught exceptions in Denon component - patch included

### ISSUE THREAD

**Issue by sebk-666** [home-assistant/home-assistant.github.io#882]
I just started using home-assistant, so sorry if this is the wrong place.
I'm currently running 0.27.1 and I have added the media_player/denon component to my configuration to access my AV receiver.
My AVR is configured to not keep the network alive when it's turned off, i.e. I can't turn it on over the net and it won't answer pings in "OFF" state.
Trying to connect to the AVR when its off, results in a "host unreachable" error, which is currently not caught by the denon component.

This would change this:
```
*** denon.py.orig      	Thu Sep  1 18:46:54 2016
--- denon.py   	Thu Sep  1 18:46:16 2016
***************
*** 70,76 ****
          """Get the latest details from the device."""
          try:
              telnet = telnetlib.Telnet(self._host)
!         except ConnectionRefusedError:
              return False

          self._pwstate = self.telnet_request(telnet, "PW?")
--- 70,76 ----
          """Get the latest details from the device."""
          try:
              telnet = telnetlib.Telnet(self._host)
!         except (ConnectionRefusedError, OSError):
              return False

          self._pwstate = self.telnet_request(telnet, "PW?")
```

It would be great to see this included. Thanks!

Sebastian

**Comment by fabaff** [comment]
This repository is for the documentation of Home Assistant. Please use the [Home Assistant issue](https://github.com/home-assistant/home-assistant/issues/new) tracker to report problems with components and platforms.

**Comment by sebk-666** [comment]
Done. Thanks!
