### ISSUE TITLE
Problems with NGINX reverse proxy server.

### ISSUE THREAD

**Issue by bobcroft** [home-assistant/home-assistant.github.io#8835]
Hi people I hope someone can help me.  I installed the duck DNS addon and that appeared to load OK and there are no errors in the logs.  I then installed the Nginx reverse proxy addon.  In both configs I set my domain to "xxxx.duckdns.org".  in my configuration.yaml I have base_url set to xxxx.duckdns.org.  I have forwarded external port 443 to internal port 8123 and also port 80 forwarded to port 80 on my Has.IO device.  I am running Hass.IO on an Intel NUC.  My router is an EE smart hub.  My PC from which I am trying to connect to the NUC is a Windows 10*64 running Chrome browser.  I have been trying different things based on Google searches and basically all I get is 'connection took too long to respond'.  I been trying to solve this for days and getting nowhere!  Everything else under Hass.IO  is working perfectly, Grafana, InfluxDb, Node-RED, Glances, ESPhome etc.
I have also tried to access HA from a Linux machine with exactly the same result.  I have also removed and re-installed Nginx reverse proxy server all to no avail.  The router is, of course common to both systems.  I can ping the NUC at 192.168.1.xx and it responds.  I can also access HA on http://192.168.1.xx and access it via winSCP without problem.  I cannot see any errors in any of the error logs that I am aware of. 
I would really appreciate any suggestions as to what the problem might be.

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by bobcroft** [comment]
Franck, thanks for pointing out my error, sorry about that.  I thought it funny that I couldn’t see it on the community forum.

 

Bob
