### ISSUE TITLE
tplink switch documentation still available

### ISSUE THREAD

**Issue by speedmann** [home-assistant/home-assistant.github.io#8872]
Hi all,

i just saw the "old" tplink documentation is still available at https://www.home-assistant.io/components/switch.tplink/ and https://www.home-assistant.io/components/light.tplink/

I think after [#18091](https://github.com/home-assistant/home-assistant/pull/18091)  it should redirect to https://www.home-assistant.io/components/tplink/ (Like the ikea documentation does)

I'm not sure if this is desired, if not the linked documentation is outdated.
I would create a PR for this in the future, when someone gave feedback which of those two solutions are considered correct

**Comment by klaasnicolaas** [comment]
We can close this PR, the pages are already merged and the `switch` and `light` platform pages are removed.
