### ISSUE TITLE
Iliad Italy Component

### ISSUE THREAD

**Issue by raxpa** [home-assistant/home-assistant.github.io#8996]
Hi everyone the "Iliad Italy" component introduced in release 0.7 is not available anymore. Looks like there was no python script in 0.8x release neither in this 0.9

**Comment by fabaff** [comment]
Component was removed: https://github.com/home-assistant/home-assistant/pull/22175

**Comment by fabaff** [comment]
Was already in the 0.91 release thus integration will be gone with the next release.

The issue you see is related to #8619
