### ISSUE TITLE
Device Tracker page doesn't list Google Home

### ISSUE THREAD

**Issue by mrand** [home-assistant/home-assistant.github.io#8998]
The list on the right side of https://www.home-assistant.io/components/device_tracker/ doesn't include Google Home (https://www.home-assistant.io/components/googlehome/).  

Maybe there is some distinction about "platforms" that I don't understand, but it seems like a it should be listed regardless since most users would assume the Device Tracker page would list all the possible components that could act as device trackers.

I didn't go looking to see if any others are missing.

**Comment by klaasnicolaas** [comment]
![image](https://user-images.githubusercontent.com/20448157/57375977-1fdfa500-719f-11e9-89e9-93da761fce7c.png)

In the meantime, the Google Home now also has the presence detection label
