### ISSUE TITLE
I need code for voice recorder in Basic or javascribt language

### ISSUE THREAD

**Issue by 3M1F** [home-assistant/home-assistant.github.io#9096]
please help me I have delivery the program after two days

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
