### ISSUE TITLE
default_config docs point to a file that is no longer useful

### ISSUE THREAD

**Issue by jimmycuadra** [home-assistant/home-assistant.github.io#9209]
https://www.home-assistant.io/components/default_config says "The components that will be loaded can be found [here](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/default_config/__init__.py)," but it seems the list of components was removed from that file in https://github.com/home-assistant/home-assistant/pull/23024. Can this reference be updated to something useful, or can the information just be moved into the documentation proper?

**Comment by klaasnicolaas** [comment]
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/default_config/manifest.json

Pherhaps it is this file?

**Comment by jimmycuadra** [comment]
Yeah, that appears to be where the information moved. I think just having that list be in the documentation itself, with links to each of the default components' documentation pages, would be much better UX, though.

**Comment by klaasnicolaas** [comment]
Well make a PR and make it better 😉

**Comment by jimmycuadra** [comment]
Still relevant.

**Comment by frenck** [comment]
Agreed. Adding it to the project board.

**Comment by frenck** [comment]
### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by klaasnicolaas** [comment]
Think that we can close this PR now
