### ISSUE TITLE
Fan support for HomeKit controller support ?

### ISSUE THREAD

**Issue by Hucksleyy91** [home-assistant/home-assistant.github.io#9240]
When trying to add my HomeKit bridge to home assistant with the HomeKit controller support addon it shows the bridge let’s me add it then it goes away so it must of worked but nothing shows up 

Would that be because it contains a fan accessory that is not shows as supported 

Is it normal for no accessories to show up at all

**Comment by andrewsayre** [comment]
This is not an issue with the website or documentation...  Please seek help in one of the [appropriate channels](https://www.home-assistant.io/help/).
