### ISSUE TITLE
MQTT link to EMQ is not working

### ISSUE THREAD

**Issue by DBaakman** [home-assistant/home-assistant.github.io#9248]
On the page https://www.home-assistant.io/docs/mqtt/broker the link 'EMQ' points to http://emqtt.io/ which gives an empty page.

When googling a bit, I found two possible replacements:
- https://www.emqx.io/ : Homepage of the company that creates EMQ; included links to the open source version of EMQ, but also to closed source commercial offerings.
- https://github.com/emqx/emqx : Github page of the open source version of EMQ

Because I don't know which one would be best, I opened this Issue instead of creating a Pull request directly. If there is consensus about the best link I can update the page and create a PR.

**Comment by fabaff** [comment]
Thanks for bringing it up.
