### ISSUE TITLE
Example configuration doesn't work

### ISSUE THREAD

**Issue by Darthmonkey** [home-assistant/home-assistant.github.io#9378]
Using either the default settings or the example configuration from 'https://www.home-assistant.io/addons/dhcp_server/' provide the error:

> not a valid value for dictionary value @ data['options']. Got {'domain': 'mynetwork.local', 'dns':['8.8.8.8', '8.8.4.4'], 'networks': [{'subnet': '192.168.1.0', 'netmask': '255.255.255.0', 'range_start': '192.168.1.100', 'range_end': '192.168.1.200', 'broadcast': '192.168.1.255', 'gateway': '192.168.1.1', 'interface': 'eth0'}], 'hosts': [{'name': 'webcam_xy', 'mac': 'aa:bb:ee:cc', 'ip': '192.168.1.40'}]}

The same error is shown if all the values are changed to valid ones, and the hosts section is removed completely, see 'https://community.home-assistant.io/t/cannot-start-dhcp-server-with-default-or-suggested-configuration/113589' for further information.

**Comment by frenck** [comment]
We are currently migration add-on documentation to the add-ons itself.
As soon as that is completed, the site will be adjusted accordingly.

The correct documentation for this particular add-on can be viewed by clicking on the add-on in the add-on store or by visiting the repository of the addon:

<https://github.com/home-assistant/hassio-addons/tree/master/dhcp_server>
