### ISSUE TITLE
Broken links to source in the configurator component docs

### ISSUE THREAD

**Issue by andrewpmiller** [home-assistant/home-assistant.github.io#9428]
Links to the source from the [documentation for the configurator component](https://www.home-assistant.io/components/configurator/) result in 404 errors.

Possibly related to Issues #3869 (stale/closed) and #8619 (closed).

Link text: "the source of the demo component"  
404: https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/demo.py#L132

Link text: "the source"  
404: https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/configurator.py#L39

**Comment by klaasnicolaas** [comment]
I have made a PR to fix the 404 errors
