### ISSUE TITLE
HassIO doc addition: Arch Linux simple install commands

### ISSUE THREAD

**Issue by PieBru** [home-assistant/home-assistant.github.io#9455]
Hi, just a quick note on how I successfully installed HassIO on computers running Arch Linux.
Maybe it can be added to https://www.home-assistant.io/hassio/installation/#alternative-install-on-generic-linux-server , which now explains only Debian.

`
 $ sudo pacman -S docker apparmor avahi ca-certificates curl dbus jq socat

 $ sudo -i

 \# curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s
`

These three commands should be enough on a fresh Arch install with working network link, done following the official Arch Linux installation guide: https://wiki.archlinux.org/index.php/Installation_guide

Just my 2 cents...
Piero

**Comment by joostvanbeek** [comment]
@PieBru Thanks for your post.
The url is causing a 404 this is the updated link

curl -sL "https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh" | bash -s

Maybe you can update it
