### ISSUE TITLE
components/rest does not mention scan_interval

### ISSUE THREAD

**Issue by flemmingss** [home-assistant/home-assistant.github.io#9461]
I se a lot of people using scan_interval with the rest component, but it is not documented.
regarding this documentation: https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/rest.markdown

If this is a feature that is avaiable it should be documented, but I don't think I know enaugh about how it works to do it.

Some examples of people using it:
https://community.home-assistant.io/t/using-an-input-number-for-scan-interval/66497
https://community.home-assistant.io/t/rest-sensor-update-interval/53034
https://gist.github.com/Cavemanz/b38e31969d15ed0a9ce1d560f8755997

**Comment by fabaff** [comment]
`scan_interval` is available for most integrations that are polling and [documented](https://www.home-assistant.io/docs/configuration/platform_options/#scan-interval).
