### ISSUE TITLE
[HADashboard/AppDaemon] Link to the Hassbian installation scripts is broken

### ISSUE THREAD

**Issue by DominikPalo** [home-assistant/home-assistant.github.io#9477]
Link to the [Hassbian installation scripts](https://github.com/home-assistant/hassbian-scripts/blob/dev/docs/appdaemon.md) (to install AppDaemon) located on the page https://www.home-assistant.io/docs/ecosystem/hadashboard/ is broken and points to 404. Could you please fix that link?

**Comment by klaasnicolaas** [comment]
I have opened a PR to fix it 😉
