### ISSUE TITLE
Delay example incorrect for slider

### ISSUE THREAD

**Issue by Genestealer** [home-assistant/home-assistant.github.io#949]
Line of example code is incorrect and reports error not finding input_slider.
'delay: {% raw %}'00:{{ input_slider.minute_delay | int }}:00'{% endraw %}`

It works if changed to:
'delay: {% raw %}'00:{{ state.input_slider.minute_delay.state | int }}:00'{% endraw %}`

**Comment by fabaff** [comment]
Yes, should be `delay: {% raw %}'00:{{ states.input_slider.minute_delay.state | int }}:00'{% endraw %}`
