### ISSUE TITLE
Create API Key (at Google) isn't an option, initially

### ISSUE THREAD

**Issue by GoWithitRoger** [home-assistant/home-assistant.github.io#9536]
Regarding:

> If you want to use the google_assistant.request_sync service, to update devices without unlinking and relinking, in Home Assistant, then enable Homegraph API for your project:
  > 2. Select your project and click Enable Homegraph API. 
  > 3. Go to Credentials, which you can find on the left navigation bar under the key icon, and **select API Key** from Create Credentials. 
  > 4. Note down the generated API Key and use this in the configuration.

When trying to get an API key from Google for the 'google_assistant:' yaml configuration, the instructions suggest that Create Credentials > API Key is an option. API Key isn't/wasn't an option when I tried it. It did become an option *after* I created a Service Account Key (I've no idea if this is correct; I simply tried something).

**Comment by jan-rivo** [comment]
Was this ever solved?

**Comment by GoWithitRoger** [comment]
I assume not, but I haven’t checked. I eventually found where the create a key interface was moved to, but I forget exactly where.

**Comment by jan-rivo** [comment]
I found out where, for future reference I had to create an api key at a higher level, basically I had to select credentials relating to APIs and Services and NOT relating directly to Homegraph

**Comment by miff2000** [comment]
> I found out where, for future reference I had to create an api key at a higher level, basically I had to select credentials relating to APIs and Services and NOT relating directly to Homegraph

I've just done this today. I went to the [HomeGraph API](https://console.cloud.google.com/apis/api/homegraph.googleapis.com/), clicked on Credentials on the left, then clicked the link that says "To view all credentials or create new credentials visit [Credentials in APIs & Services](https://console.cloud.google.com/apis/credentials)". Under that screen there's a "Create credentials" button to create API keys

**Comment by Stefan300381** [comment]
Hi, ran into the same issue today. The documentation needs to be updated
