### ISSUE TITLE
Recommend clarification in Docker on Synology docs

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/home-assistant.github.io#9592]
As per [this thread](https://community.home-assistant.io/t/whitelist-external-dirs-path-in-docker/120794) the docs for using HA in Docker on Synology could be clearer. I recommed a change e.g. from:
`
Within “Volume” click on “Add Folder” and choose either an existing folder or add a new folder. The “mount path” has to be “/config”, so that Home Assistant will use it for the configs and logs.
`

to something like:
`
Within “Volume” click on “Add Folder” and choose either an existing folder or add a new folder. The “mount path” has to be “/config”, so that Home Assistant will use it for the configs and logs. It is therefore recommended that the folder you choose should be named "config" or "homeassistant/config" to avoid confusion when referencing it within service calls.
`

@arsaboo

**Comment by arsaboo** [comment]
Sounds good to me 👍

**Comment by klaasnicolaas** [comment]
Merged 😉
