### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by ghost** [home-assistant/home-assistant.github.io#9601]
Delete

**Comment by klaasnicolaas** [comment]
You can skip this step and continue with the steps below.

**Comment by YRRK** [comment]
Pfffew with a lot of trail and error, and making use of my regular PC to detect the AppleTV bridge ID. I managed to get it working.

So it works now. But if you start from scratch with a clean homeassistent setup....the manual is outdated. Please revise the manual according to the current situation :-)

**Comment by YRRK** [comment]
Maybe keep the post open for anyone to see the manual needs revision.

**Comment by klaasnicolaas** [comment]
You can always create a PR yourself with the changes you would like 😉

**Comment by YRRK** [comment]
Hmm I definately want to contribute to the homeassistent society. But i'm still such a noob that i don't want to mixup other peoples hard work writing it. :-) Plus I did so many trial and error, I accutually don't know what I did anymore
