### ISSUE TITLE
0.94 update broke OpenCV image processing

### ISSUE THREAD

**Issue by warcanoid** [home-assistant/home-assistant.github.io#9615]
No OpenCV library found! Install or compile for your system following instructions here: http://opencv.org/releases.html

How to get opencv dependecies back?

**Comment by warcanoid** [comment]
https://imgur.com/a/GKPgGml

**Comment by DubhAd** [comment]
Would appear to be related to [your previous issue](https://github.com/home-assistant/home-assistant/issues/24456)

Also, the *documentation repository* is not where you need to open issues about the back end.

**Comment by warcanoid** [comment]
I updated HA from 0.94.3 to 0.94.4 and something again deleted OpenCV library:No OpenCV library found! Install or compile for your system following instructions here: http://opencv.org/releases.html
Is this a bug? Delete library after each update?

**Comment by robbiet480** [comment]
@warcanoid Please don't use the documentation repository to report issues in the code. The documentation repository only relates to the documentation of Home Assistant. Furthermore, please don't comment on closed issues trying to revive them unless it was improperly closed. Finally, please don't spam the same comment on multiple issues. Thank you.

Locking as dupe of https://github.com/home-assistant/hassio-opencv/issues/1
