### ISSUE TITLE
Alexa account linking with custom port

### ISSUE THREAD

**Issue by RyuzakiKK** [home-assistant/home-assistant.github.io#9636]
Following the [Alexa guide](https://www.home-assistant.io/components/alexa.smart_home/) I saw that if I used an `Authorization URI` and an `Access Token URI` with a custom port number I wasn't able to link the amazon skill.

To solve that I forwarded my HA 8123 port to the 443 and used an url like `https://[YOUR HOME ASSISTANT URL]/auth...`

If someone confirms that Alexa is not able to handle custom port numbers we should point it out in the guide.

**Comment by frenck** [comment]
This is the issue tracker for our website and documentation.

For support and getting answers to your questions, please use our community forum or hop onto our Discord chat server 👍 

If you find the answer and conclude the documentation is incorrect, feel free to open an issue or even better, create a PR that addresses it!

../Frenck
