### ISSUE TITLE
Microsoft Text-to-Speech issues when add language code: vi-VN

### ISSUE THREAD

**Issue by nguyenanh87** [home-assistant/home-assistant.github.io#9637]
HI,
When i config Microsoft TTS service with language code is vi-VN, the system say:

Invalid config for [tts.microsoft]: value is not allowed for dictionary value @ data['language']. Got 'vi-VN'. (See ?, line ?). Please check the docs at https://home-assistant.io/components/tts.microsoft/

I've checked language code, type at the document: https://docs.microsoft.com/en-us/azure/cognitive-services/Speech/api-reference-rest/bingvoiceoutput

![Screen Shot 2019-06-15 at 22 32 20](https://user-images.githubusercontent.com/40736871/59552145-16c3ce00-8fbe-11e9-8e95-50fbfedab64a.png)

![Screen Shot 2019-06-15 at 22 32 33](https://user-images.githubusercontent.com/40736871/59552147-1deadc00-8fbe-11e9-96c1-5694932e3505.png)

Please suggest me the solutions or add more language support to source code.

**Comment by klaasnicolaas** [comment]
What if you do it lowercase? like `vi-vn`

**Comment by nguyenanh87** [comment]
I’ve tried with same issues

**Comment by aidbish** [comment]
The only supported languages currently for the component are

    'ar-eg', 'ar-sa', 'ca-es', 'cs-cz', 'da-dk', 'de-at', 'de-ch', 'de-de',
    'el-gr', 'en-au', 'en-ca', 'en-gb', 'en-ie', 'en-in', 'en-us', 'es-es',
    'es-mx', 'fi-fi', 'fr-ca', 'fr-ch', 'fr-fr', 'he-il', 'hi-in', 'hu-hu',
    'id-id', 'it-it', 'ja-jp', 'ko-kr', 'nb-no', 'nl-nl', 'pl-pl', 'pt-br',
    'pt-pt', 'ro-ro', 'ru-ru', 'sk-sk', 'sv-se', 'th-th', 'tr-tr', 'zh-cn',
    'zh-hk', 'zh-tw',

**Comment by frenck** [comment]
Let's add the list to the integration page.

**Comment by frenck** [comment]
### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by aidbish** [comment]
PR submitted.
https://github.com/home-assistant/home-assistant.io/pull/9721

**Comment by frenck** [comment]
PR merged. Thanks for addressing this @nguyenanh87! 
And @aidbish, thanks for doing the PR, your help is greatly appreciated ❤️
