### ISSUE TITLE
Examples config causes error - source/_lovelace/entities.markdown

### ISSUE THREAD

**Issue by mgguinne** [home-assistant/home-assistant.github.io#9664]
The following Lovelace example page at source/_lovelace/entities.markdown produces an error in the UI config page (for special row). Though it does actually still work. Just not good for new users trying to copy paste (aka me).

![image](https://user-images.githubusercontent.com/10627164/59806773-e8851c00-9338-11e9-8a0f-b261ecf629b1.png)

**Comment by frenck** [comment]
Thanks for reporting @mgguinne! That is appreciated.

**Comment by frenck** [comment]
### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by jensihnow** [comment]
Instead of adding a hint to the documentation the better approach would be to support the additional entity types like divider and weblink within the UI editor and not promting an issue for them. Well in the meantime we a one line should be enough.
