### ISSUE TITLE
Add adding card to lovelace video.

### ISSUE THREAD

**Issue by Petro31** [home-assistant/home-assistant.github.io#9670]
So many people cannot find that orange plus button to add a card.  I usually have to spend 10 replies in a 'beginner' thread showing these people where the button is to create a card instead of editing because the video doesn't show creating a card.

We could move the button, but honestly, it's in the best spot.  So I would recommend adding a video that adds a card as well as edits a card.

**Comment by frenck** [comment]
Hmm, that is interesting. We could add a screenshot, animation or video. But to be honest, I think this is not a documentation issue.

If users are having trouble finding things in an interface, then it is usually a problem with UX.

I'm moving this issue to a different location to see if we can improve the UX.

ESPHome is a nice example, it draws attention to those areas the first time using a background:

![image](https://user-images.githubusercontent.com/195327/60337072-561cf200-99a2-11e9-9d8d-d0caebab7bdc.png)
