### ISSUE TITLE
Nederlandse spoorwegen intergration

### ISSUE THREAD

**Issue by thostie2002** [home-assistant/home-assistant.github.io#9683]
Hello, as password for the nederlandse spoorwegen account you neet to have a special sing like an @ but this is not supported for the config. What will
Work or do you please wanna fix it.

**Comment by frenck** [comment]
Hi, there @thostie2002,

Please file a bug report @ https://github.com/home-assistant/home-assistant/issues

This GitHub repository is purely for tracking issues with the documentation.

Thanks already 👍
