### ISSUE TITLE
Hassbian database links are 404

### ISSUE THREAD

**Issue by robmarkcole** [home-assistant/home-assistant.github.io#9700]
The links for databases on https://www.home-assistant.io/docs/installation/hassbian/customization/

**Comment by frenck** [comment]
### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by leytpapas** [comment]
Just did a pull request.
The .md files were moved from '/hassbian-scripts/blob/master/docs' to 'hassbian-scripts/blob/master/docs/suites' so apart from fixing the configuration/ page each script(in the hassbian repository) must have its links updated for proper navigation. 

Will update when fixing them too

**Comment by frenck** [comment]
Documentation has been adjusted.
