### ISSUE TITLE
Remove Bluetooth BCM43xx add-on from docs

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#9709]
This add-on is no longer available and was already deprecated since HassOS was introduced.

Page to remove: <https://www.home-assistant.io/addons/bluetooth_bcm43xx/>

Also, remove it from the index on <https://www.home-assistant.io/addons/> (which is dynamical, so removing the page should do it).

**Comment by frenck** [comment]
### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by aidbish** [comment]
PR Submitted https://github.com/home-assistant/home-assistant.io/pull/9728

**Comment by frenck** [comment]
PR is merged! Thanks again @aidbish! ❤️
