### ISSUE TITLE
Update getting start on configuration, some parts moved to UI

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#9729]
https://www.home-assistant.io/getting-started/configuration/

> Find the homeassistant: configuration block, which should be the first thing in configuration.yaml. In this block, update name, latitude, longitude, unit_system and time_zone to match yours.

This is no longer true since it now can be done via the UI.

**Comment by frenck** [comment]
### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by leytpapas** [comment]
Just did a pull request.
The .md files were moved from '/hassbian-scripts/blob/master/docs' to 'hassbian-scripts/tree/dev/docs/suites' so apart from fixing the configuration/ page each script must have its links updated for proper navigation. Will update when fixing them too
