### ISSUE TITLE
Fixing 404's

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant.github.io#9774]
A simple scan showed a bunch of links leading to 404 pages.
This issue tries to keep track of that.

- [ ] homeassistant://auth-callback
- [ ] http://192.168.0.109:8123
- [ ] http://192.168.1.1
- [ ] http://192.168.1.10
- [ ] http://192.168.1.10/analog/2
- [ ] http://192.168.1.10/digital/7
- [ ] http://192.168.1.10/temperature
- [ ] http://192.168.1.21:2112
- [ ] http://192.168.10.100:80
- [ ] http://HOST:PORT/html/docs/cli-api.html?player=
- [ ] http://IP:8080/sensors.json
- [ ] http://aa.usno.navy.mil/data/docs/AltAz.php
- [ ] http://bluesensenetworks.com
- [ ] http://docs.micropython.org/en/latest/esp8266/py-modindex.html
- [ ] http://elinux.org/Beagleboard:BeagleBoneBlack
- [ ] http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt.javascript.git/tree/src
- [ ] http://github.com/homeassistant/homeassistant-cli/commit/edbe4bf42e7d0993d68a367ca04ad80217aac395
- [ ] http://hassbian.local:8123
- [ ] http://hassbian:8123
- [ ] http://ipaddress:8123
- [ ] http://localhost
- [ ] http://localhost:3000/login
- [ ] http://localhost:8000
- [ ] http://localhost:8083
- [ ] http://localhost:8123
- [ ] http://localhost:8124
- [ ] http://localhost:8888
- [ ] http://logentries.com
- [ ] http://nbviewer.jupyter.org/github/home-assistant/home-assistant-notebooks/blob/master/DataExploration-1/DataExploration-1.ipynb
- [ ] http://nbviewer.jupyter.org/github/home-assistant/home-assistant-notebooks/blob/master/DataExploration-2/DataExploration-2.ipynb
- [ ] http://nbviewer.jupyter.org/github/home-assistant/home-assistant-notebooks/blob/master/database-examples.ipynb
- [ ] http://nbviewer.jupyter.org/github/home-assistant/home-assistant-notebooks/blob/master/database-statistics.ipynb
- [ ] http://nbviewer.jupyter.org/github/home-assistant/home-assistant-notebooks/blob/master/graph-single-sensor.ipynb
- [ ] http://pushetta.com/pushetta-api
- [ ] http://spotcrime.com
- [ ] http://technewsdir.com/top-5-videos-from-embedded-linux-conference-and-openiot-summit-2016
- [ ] http://www.bom.gov.au/products/IDx60801/%5Bstation%5D.shtml
- [ ] http://www.growlforwindows.com
- [ ] http://www.hooksmarthome.com
- [ ] http://www.international.zehnder-systems.com/products-and-systems/comfosystems/zehnder-comfoair-q350-st
- [ ] http://www.international.zehnder-systems.com/products-and-systems/comfosystems/zehnder-comfoair-q450-st
- [ ] http://www.radiothermostat.com/filtrete/products
- [ ] http://www.salda.lt/en/products/category/compact-counter-flow-units
- [ ] http://www.salda.lt/en/products/item/5637227077
- [x] http://www.telldus.se/products/tellstick
- [ ] http://www2.meethue.com/en-us/support/search/?q=Another+brand
- [ ] http://xxx.xxx.xxx.xxx:8123/api/events/do_button_pressed?api_password=xxxxxxxx
- [ ] http://xxx.xxx.xxx.xxx:8123/api/services/light/turn_on?api_password=xxxxxxxx
- [ ] http://xxx.xxx.xxx.xxx:8123/api/services/switch/turn_off?api_password=xxxxxxxx
- [ ] https://192.168.1.10
- [ ] https://192.168.1.32:9090
- [ ] https://api.atlassian.com/site/55872e9f-047e-a619-b32c-19d37fbc6038/conversation/26c98c26-0ffd-a11e-3a55-1b397cb71fe0/message
- [ ] https://api.coinbase.com/v2/currencies
- [ ] https://api.hipchat.com
- [ ] https://api.telegram.org/botYOUR_API_TOKEN/getUpdates
- [ ] https://chemnitzer.linux-tage.de/2017/en/programm/beitrag/356
- [ ] https://cla.github.com
- [x] https://community.home-assistant.io/c/contest-2017
- [x] https://community.home-assistant.io/t/entry-automating-a-nursing-home/14872
- [x] https://community.home-assistant.io/t/entry-dedicated-hardware-for-coding-testing-building-and-contributing-to-home-assistant/15515
- [x] https://community.home-assistant.io/t/entry-for-hardware-contest-part-of-iot-course/14827
- [x] https://community.home-assistant.io/t/entry-hassio-home-assistant-hub-for-dummies/16037
- [x] https://components/emoncms_history
- [x] https://components/notify.matrix
- [ ] https://countryside.example.org
- [ ] https://developer.amazon.com/alexa-skills-kit/flash-briefing
- [ ] https://developer.telldus.com/wiki/TellStick_conf
- [ ] https://developer.toon.eu/user/me/apps
- [ ] https://developers.coinbase.com/api/v2
- [ ] https://discordapp.com/api/oauth2/authorize?client_id=%5BCLIENT_ID%5D&scope=bot&permissions=0
- [ ] https://discuss.ninjablocks.com/t/ninja-blocks-whats-been-happening-whats-happening-next/3608
- [x] https://docs.google.com/presentation/d/1PUnOpeFZxNj4LEjaohGqH_1hOGQGuS5yRHD1ThHr6nk/edit?usp=sharing
- [ ] https://example.com:8123/local/google123456789.html
- [x] https://github.com/DrTexxOfficial
- [x] https://github.com/commandtab
- [x] https://github.com/eltoro81
- [x] https://github.com/fedor1210
- [ ] https://github.com/home-assistant/hassbian-scripts/blob/dev/docs/appdaemon.md
- [ ] https://github.com/home-assistant/home-assistant-notebooks/blob/master/first-notebook.ipynb
- [ ] https://github.com/home-assistant/home-assistant-polymer/blob/master/script/sw-precache.js
- [x] https://github.com/home-assistant/home-assistant.github.io/blob/current/source/_components/media_player.panasonic_bluray.markdown
- [x] https://github.com/home-assistant/home-assistant.github.io/blob/next/source/_components/binary_sensor.random.markdown
- [x] https://github.com/home-assistant/home-assistant.github.io/blob/next/source/_components/media_player.panasonic_viera.markdown
- [x] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/_components/media_player.aquostv.markdown
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/announcements/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/cloud/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/community/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/device-tracking/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/esp8266/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/how-to/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/ibeacons/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/internet-of-things/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/iot-data/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/media/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/merchandise/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/micropython/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/mqtt/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/organization/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/owntracks/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/presence-detection/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/public-service-announcement/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/release-notes/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/survey/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/talks/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/technology/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/user-stories/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/video/index.html
- [ ] https://github.com/home-assistant/home-assistant.github.io/tree/current/source/blog/categories/website/index.html
- [ ] https://github.com/home-assistant/home-assistant/blob/dev/config/configuration.yaml.example
- [ ] https://github.com/home-assistant/home-assistant/blob/dev/docs/swagger.yaml
- [ ] https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/cloud/iot.py
- [ ] https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/updater.py
- [ ] https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/calendar/todoist.py
- [ ] https://github.com/invalid-email-address
- [x] https://github.com/teachingbirds
- [ ] https://habitica.com/api/v3
- [ ] https://hacktoberfest.digitalocean.com/sign_up/register
- [ ] https://hass-example.duckdns.org
- [ ] https://home-assistant-lovelace-gallery.netlify.com
- [ ] https://home.example.org
- [x] https://ifttt.com/maker
- [ ] https://layla.amazon.com
- [ ] https://localhost:8123/local/index.html
- [ ] https://myhome.duckdns.org/api/locative?api_password=HA_PASSWORD
- [ ] https://ossmetrics.com/leaderboard
- [ ] https://play.google.com/store/apps/details?id=org.jtb.alogcat&hl=en
- [ ] https://recollect.net/solutions/waste
- [ ] https://stream.watsonplatform.net/text-to-speech/api
- [ ] https://support.google.com/googlehome/answer/7506443
- [ ] https://twitter.com/ToddW_Logitech
- [ ] https://twitter.com/ToddW_Logitech/status/1075222154726100993?ref_src=twsrc%5Etfw
- [ ] https://twitter.com/ToddW_Logitech/status/1075225822850560000?ref_src=twsrc%5Etfw
- [ ] https://www.asus.com/support/faq/1005449
- [ ] https://www.home-assistant.io/blog/2015/11/22/survey-november-2015/components/light.mqtt
- [ ] https://www.home-assistant.io/blog/2017/02/04/hassbian-toybox/hassbian.local
- [ ] https://www.home-assistant.io/blog/2017/11/05/frontend-translations
- [ ] https://www.home-assistant.io/blog/2019/02/04/introducing-home-assistant-cli/github-hass-cli
- [ ] https://www.home-assistant.io/blog/posts/github-hass-cli
- [ ] https://www.home-assistant.io/blog/posts/hassbian.local
- [ ] https://www.home-assistant.io/component/mailbox.asterisk_mbox
- [ ] https://www.home-assistant.io/components/__init__
- [ ] https://www.home-assistant.io/components/aws_sns
- [ ] https://www.home-assistant.io/components/aws_sqs
- [ ] https://www.home-assistant.io/components/binary_sensor.command
- [ ] https://www.home-assistant.io/components/binary_sensor.insteon_plm
- [ ] https://www.home-assistant.io/components/camera.__init__
- [ ] https://www.home-assistant.io/components/cloud.const
- [ ] https://www.home-assistant.io/components/config.__init__
- [ ] https://www.home-assistant.io/components/config.automation
- [ ] https://www.home-assistant.io/components/cover.ryobi_gdo
- [ ] https://www.home-assistant.io/components/fan.insteon_local
- [ ] https://www.home-assistant.io/components/fan.nest
- [ ] https://www.home-assistant.io/components/gc100/binary-sensor
- [ ] https://www.home-assistant.io/components/homematicip
- [ ] https://www.home-assistant.io/components/image_processing.__init__
- [ ] https://www.home-assistant.io/components/image_processing.demo
- [ ] https://www.home-assistant.io/components/insteon_local
- [ ] https://www.home-assistant.io/components/insteon_plm
- [ ] https://www.home-assistant.io/components/light.__init__
- [ ] https://www.home-assistant.io/components/light.demo
- [ ] https://www.home-assistant.io/components/mqtt.discovery
- [ ] https://www.home-assistant.io/components/notify.aws_sns
- [ ] https://www.home-assistant.io/components/notify.aws_sqs
- [x] https://www.home-assistant.io/components/notify.telstra
- [ ] https://www.home-assistant.io/components/qwikswitch/components/binary_sensor
- [ ] https://www.home-assistant.io/components/remote.services.yaml
- [ ] https://www.home-assistant.io/components/rollershutter.command_line
- [x] https://www.home-assistant.io/components/sensor.bloomsky
- [ ] https://www.home-assistant.io/components/sensor.command_sensor
- [x] https://www.home-assistant.io/components/sensor.esphome
- [ ] https://www.home-assistant.io/components/sensor.homematicip
- [x] https://www.home-assistant.io/components/sensor.iliad_italy
- [x] https://www.home-assistant.io/components/sensor.netatmo_public
- [ ] https://www.home-assistant.io/components/switch.command_switch
- [ ] https://www.home-assistant.io/components/switch.insteon_plm
- [x] https://www.home-assistant.io/components/switch/rfxtrx
- [x] https://www.home-assistant.io/components/telegram_bot.__init__
- [ ] https://www.home-assistant.io/components/thermostat.heat_control
- [x] https://www.home-assistant.io/components/zwave.api
- [x] https://www.home-assistant.io/cookbook/automation_kodi_dynamic_input_select
- [x] https://www.home-assistant.io/cookbook/customize_polling_interval
- [ ] https://www.home-assistant.io/cookbook/perform_actions_based_on_input_select/components/media_player.cast
- [ ] https://www.home-assistant.io/developers/frontend_translation
- [x] https://www.home-assistant.io/developers/rest_api.markdown
- [x] https://www.home-assistant.io/docs/hassbian
- [x] https://www.home-assistant.io/guidelines
- [x] https://www.home-assistant.io/images/components/mystrom/mystrom-advanced.png
- [x] https://www.home-assistant.io/topics/service_calls
- [ ] https://www.newlook.dteenergy.com
- [x] https://www.openhome.org
- [ ] https://www.pencomdesign.com
- [ ] https://www.pencomdesign.com/relay-boards

**Comment by klaasnicolaas** [comment]
https://github.com/miniconfig <- This link is still working

**Comment by sinclairpaul** [comment]
Any chance of re-running while excluding the _posts, which is likely to be out of date?

**Comment by frenck** [comment]
Did a rescan, updated original openings post.
