### ISSUE TITLE
Hassbian random freezes over ssh

### ISSUE THREAD

**Issue by Garfius** [home-assistant/home-assistant.github.io#9826]
I just updated from 0.84, and realized this version randomly freezes ssh with no apparent reason. 

Looke like an O.S. issue?

If needed, will upload video.

Thanks a lot.

**Comment by frenck** [comment]
Hi there m8!

This is the repository for the project documentation and mainly for tracking issues and tasks with the docs and our website.

For Hassbian, I would highly recommend you to jump onto our Discord chat server and ask in the `#hassbian` channel. This makes troubleshooting way quicker.

Thanks 👍
