### ISSUE TITLE
serial.markdown example code uses deprecated methods

### ISSUE THREAD

**Issue by truglodite** [home-assistant/home-assistant.github.io#9842]
The example code given in /source/_components/serial.markdown was written for an older version of ArduinoJSON.h (v5), and it will not compile with the current library (v6). Using the new methods in v6, the example code can be replaced by something like this:
```c
#include <ArduinoJson.h>

void setup() {
  Serial.begin(115200);
}

void loop() {
  StaticJsonBuffer<100> jsonBuffer;
  jsonBuffer[temperature] = analogRead(A0);
  jsonBuffer[humidity] = analogRead(A1);

  serializeJson(jsonBuffer, Serial);
  Serial.println();

  delay(2000);
}
```
Perhaps this can be expanded on by adding additional lines from the library example code "JsonGeneratorExample.ino". I'm too much a github noob to make a PR for this, so just wanted to post this as low hanging fruit for someone else to help out.

**Comment by surlymatt** [comment]
Got a fix for it using the latest arduinojson driver... all I have to do now is work out how to make a pull request..  Coincidentially the same doc I was going to update anyway so adding your changes will be done at the same time.

**Comment by surlymatt** [comment]
see pr #9844

**Comment by surlymatt** [comment]
PR #9844 closed as I couldn't work out how to rebase onto the correct branch.
PR #9845 has your requested changes.  Hope you like them.
