### ISSUE TITLE
Do some testing of setup use cases

### ISSUE THREAD

**Issue by Bazmundi** [home-assistant/home-assistant.github.io#9852]
I burnt an sd card, set up network on usb, booted, waited, system came up and prompted for name, password, so I entered the details I wanted recorded. 

I then went to the page in wizard which asked for my locale.  I selected link for it to grab my locale automatically, but it missed by not a few kilometers.

I thought the link to openmap would allow me go into the map to move the pointer,  it simply went to a brochure of open map.  Ah well, I hit back button.  

The browser fell back into page account creation page.  However, it won't let me add my details again BECAUSE, the account had been created.  

There is otherwise no means to move to next step once this happens, other than trashing sd card and start over again.   

If the links embedded in the locale setting break your wizard, please remove them.   

Or if an account has been created, don't go back to account creation page.

**Comment by frenck** [comment]
That is not a website or documentation issue, however, you did report it at our documentation repository.

Please create the issue in the appropriate location, furthermore, you are adding a lot of stuff in there (like your SD card) which does not matter for the bug you are reporting. Please, keep things simple and to the point if you consider reporting it again.

👍
