### ISSUE TITLE
Mosquitto docs outdated

### ISSUE THREAD

**Issue by augustjanse** [home-assistant/home-assistant.github.io#9880]
On [this page](https://www.home-assistant.io/addons/mosquitto/), under "Using Mosquitto with Hass.io", step 3 doesn't work. Instead it appears that the `logins` config needs to be set. In addition, there is a warning about ACLs that seems to be correct, but it should probably be added as an explicit step. See home-assistant/hassio-addons#626 for more info.

**Comment by ristomatti** [comment]
@augustjanse Did you get it working in the end? I've setup Mosquitto a couple of times on itself but these instructions seem strangely confusing considering how important MQTT integration is to most DYI home automation environments. I've installed Mosquitto addon from the store and enabled anonymous login out of curiosity, as that is what I would prefer it to have. I see authentication as another source of configuration frustration on the client side as I'll be having devices with no SSL support. Authentication seems quite pointless if the user and password will be sent in plain text.

I was able to connect on the installed Mosquitto server then using MQTT Snooper on Android without any credentials but a Sonoff running Espurna failed to connect. I'm reluctant to do the ACL setup to just hack it to work as I would like to understand why it is needed and why doesn't the anonymous setting work as I would expect. I'm currently evaluating if Hass.io/Home Assistant would simplify things in contrast to my old setup built mainly with Node-RED, Mosquitto and Blynk, but HA seems to be all the rage these days. I have to sat it doesn't feel very convincing if an addon providing a core DYI home automation feature like MQTT can suddenly just break on a custom OS with controlled updates...

Edit: fixed typos

**Comment by augustjanse** [comment]
Yes, it was quite easy when I found the correct instructions (which took me very long though). To be honest, I have given no thought to security or other considerations at all.

**Comment by frenck** [comment]
We are currently working on updating all add-on documentation and relocating them.

**Comment by ristomatti** [comment]
@augustjanse Were the ACL settings required?

@frenck Great, thanks for the update! I'll maybe postpone my initial setup until then if there's some other similar issues. There seems to be quite a lot of confusion like the OP described especially with the Mosquitto addon. I hope it's high on the priority!

**Comment by augustjanse** [comment]
I believe they were, yes. Though I'm not entirely sure I tried it with `logins` in the config but without ACL settings.

**Comment by jgfdsa** [comment]
Can anybody update on the staus on how to configure MQTT broker under latest hassio version?

I have one week following every possible guide, but with no luck.

**Comment by augustjanse** [comment]
@jgfdsa Did you try [these](https://community.home-assistant.io/t/mosquitto-mqtt-4-1-doesnt-work-after-update/104855/225)?
