### ISSUE TITLE
HVAC mode value must be double quoted

### ISSUE THREAD

**Issue by WeaselBreath** [home-assistant/home-assistant.github.io#9900]
initial_hvac_mode
(string)(Optional)Set the initial HVAC mode. Valid values are `heat`, `cool` or `auto`. Value has to be double quoted. If this parameter is not set, it is preferable to set a *keep_alive* value. This is helpful to align any discrepancies between *generic_thermostat* and *heater* state.

and in example configuration.yaml

initial_hvac_mode: "off"

**Comment by frenck** [comment]
Feel free to open up a PR with the suggested change 👍

**Comment by WeaselBreath** [comment]
It's not about double quotes.  Docs list 3 options for initial_hvac_mode.  heat, cool or auto, but then in the example configuration.yaml a fourth option of "off" is listed.

**Comment by jensihnow** [comment]
Already fixed, see https://github.com/home-assistant/home-assistant.io/commit/26701e281a5011b6db5d9c2009463ebb166d00b0#diff-f49b7881f35f9fa104fcae2eebeb53c3 which seems to be correct looking at https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/generic_thermostat/climate.py#L78

**Comment by frenck** [comment]
Check, thanks! So we can close this issue 👍
