### ISSUE TITLE
Hassio Docker Image

### ISSUE THREAD

**Issue by AlienPlan** [home-assistant/home-assistant.github.io#9922]
Hi home-assistant community,
I'm totally new to home assistant but really like the idea of it when fully working. I did install home assistant and then also hassio on another instance and decided to use hassio. 
I'm running Ubuntu 18.4 on Odroid XU4 I also have docker ce running. I would like to download hassio docker image but I only see homeassistant/odroid-xu-homeassistant. Just wondering if someone could push me in the right direction here. thanks in advance

**Comment by frenck** [comment]
Hi there @Johnatservice! 

Welcome to Home Assistant 🎉 

For installing Hass.io on a generic Linux distribution (like Ubuntu), please follow this part of the manual: <https://www.home-assistant.io/hassio/installation/#alternative-install-on-a-generic-linux-host>

Please note, that we use GitHub for tracking issues and bugs, not for support. If you are in need of support, please try our community forum or hop on to our Discord chat server!

../Frenck

**Comment by AlienPlan** [comment]
Hi Frank
thank you for the push in the right direction here. I also found what i was
doing wrong,  -m arm71 was wrong machine, armhf fixed everything
Thank you again
JOhn

**Comment by frenck** [comment]
Happy you got it resolved! 🎉

**Comment by AlienPlan** [comment]
Hello there,

I just signed the petition "Hydro One: Hydro One Change All Time To Off
Peak Amid Covid-19" and wanted to see if you could help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/XkHPQY28rf

Thanks!
Giannis
