### ISSUE TITLE
Miss-Truths on the updater integration page

### ISSUE THREAD

**Issue by miawgogo** [home-assistant/home-assistant.github.io#9949]
Currently the updater component page contains miss-truths about what is stored about the user. Currently it states

> No identifiable information (i.e., IP address, GPS coordinates, etc.) will ever be collected

Whilst accurate on the component end, according to the back-end documentation the home assistant project is storing GeoIP determined latitude & longitude. Whilst GeoIP in most cases is inaccurate(Most databases think I'm in Westminster, London), it can sometime be accurate depending on the data source and if the user has updated there location in these databases to be accurate.

This means the aforementioned statement is a miss-truth and might mislead users. This is of course if the back end documentation is up to date(why I'm opening this issue before making changes).

Also from the stand point of a user, I see little need for home assistant to collect GeoIP determined latitude, longitude and zip codes, i feel like the city would be the most level of detail home assistant would need

**Comment by miawgogo** [comment]
Pages in question
Backend: https://www.home-assistant.io/docs/backend/updater/
Component: https://www.home-assistant.io/components/updater/

**Comment by fabaff** [comment]
Looks like that we need some clarification.
