### ISSUE TITLE
Home assistant and RFXCOM

### ISSUE THREAD

**Issue by paultje95** [home-assistant/home-assistant.github.io#9986]
hello 

i recently installed them home assistant on my raspberry pi B3 +.  now I would like to connect my RFXCOM to my rapsberry pi (via usb) and then with my home assistant I want to operate my click on click off switches.  is this possible and how should I do this?

greeting paul

**Comment by klaasnicolaas** [comment]
The issues here are to report problems with the documentation, we do not offer support through this route. I will therefore close this issue.

For help with your installation I would like to refer you to the [community forum](https://community.home-assistant.io) and the [Discord server](https://discord.gg/c5DvZ4e).

Ps. Take a look at the [RFXtrx integration](https://www.home-assistant.io/components/rfxtrx/) 😉
