### ISSUE TITLE
Add two devices xiaomi air purifier 2s

### ISSUE THREAD

**Issue by maresob** [home-assistant/home-assistant.github.io#9991]
Hi, 
I have two devices zhimi.airpurifier.mc1 and i'm able to integrate only one... 
Integration "fan" allows add only one device...

**Comment by Vasiley** [comment]
your configuration must be wrong and please do not delete template.... fill in what it ask to give info but here is a example of 3 purifiers configed in my system https://github.com/Vasiley/Home-Assistant-Main/blob/master/packages/xiaomi_purifier.yaml#L81
