### ISSUE TITLE
z-wave Climate instructions need updating

### ISSUE THREAD

**Issue by nickrout** [home-assistant/home-assistant.github.io#9997]
Oops posted too soon

https://github.com/home-assistant/home-assistant.io/blob/current/source/_components/zwave.markdown#automating-z-wave-climate-devices

Has the example has climate.set_operation_mode, which I think is now deprecated for climate.set_hvac_mode. However I am not sure enough about the new climate stuff to correct it, there may be other stuff that needs correcting too.

**Comment by frenck** [comment]
Feel free to jump in and help by changing it and opening up a PR 👍
